### ISSUE TITLE
how to try titan store engine in recent tidb cluster

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#10011]
i have an tidb cluster in production env,  

after i readed the article Titan 的设计与实现 (https://www.pingcap.com/blog-cn/titan-design-and-implementation/), than i want to try it.

but there some question i want to know before i do it, 

as the article says,:

"在 TiKV 中使用 Titan
目前 Titan 在 TiKV 中是默认关闭的，我们通过 TiKV 的配置文件来决定是否开启和设置 Titan，相关的配置项包括 [rocksdb.titan] 和 [rocksdb.defaultcf.titan]， 开启 Titan 只需要进行如下配置即可"

is that means i only just to add this config to the tikvl.toml and restart tikv-server will done?

other, i want to try this operation,
add a new tikv instance into cluster, and only set this tikv [rocksdb.titan] enabled = true, 
but the old tikv instance didn't apply this config, and i use store delete command to tomb the old tikv instance, do it one by one, after all tikv instance is replaced.
after i using titan, and i will check the range query performce if i cant accpet, if i didn't accpet the perfomence, i want to rollback the none-titan tikv,   can i use the operation that one by one to replace titan-tikv to none-titan-tikv?

**Comment by qw4990** [comment]
@ericisme Thanks for your feedback, but maybe it's better to ask this question at [TiKV](https://github.com/tikv/tikv) repository.

**Comment by ericisme** [comment]
@qw4990 ok thanks, i will ask it at TiKV repository.
