### ISSUE TITLE
Use SQL to get the DDL owner info.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10024]
## Feature Request

**Is your feature request related to a problem? Please describe:**

currently there's builtin function can know whether the TiDB which the client is connected is DDL owner. But cannot get which one is owner.

**Describe the feature you'd like:**

Implement a builtin function `tidb_ddl_owner()`. It can return the IP:PORT information and label information if exists .

**Comment by zimulala** [comment]
@winkyao  Now we have the SQL of `admin show ddl`. Could this SQL meet your needs?
```
mysql> admin show ddl;
+------------+--------------------------------------+---------------+--------------+--------------------------------------+-------+
| SCHEMA_VER | OWNER_ID                             | OWNER_ADDRESS | RUNNING_JOBS | SELF_ID                              | QUERY |
+------------+--------------------------------------+---------------+--------------+--------------------------------------+-------+
|         28 | 37e58e76-de68-4c66-b14a-3f443ac5d7a1 | 127.0.0.1:4000         |              | 37e58e76-de68-4c66-b14a-3f443ac5d7a1 |       |
+------------+--------------------------------------+---------------+--------------+--------------------------------------+-------+
```

**Comment by winoros** [comment]
@zimulala I've checked the code of its implementation. It will always show ip and port unless we're in standalone testing mode right?
I tested it in test mode and in cluster. It shows full information when is in cluster and only show port when it's in test mode.

**Comment by zimulala** [comment]
@winoros Yes.

**Comment by winoros** [comment]
confirmed by OPS
this can meet their needs
