### ISSUE TITLE
ticlient doesn't make request in a round-robin fashion any more

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb#10037]
In the past, ticlient will try to make requests to all the followers when leader is unable to be connected. But due to pingcap/tidb#6880, it will not try to connect followers anymore.

Note that the a region can still elect a new leader and serve requests within the isolation of PD. So just depending on information in PD may keep TiDB out of service for an unnecessary long time in extreme conditions.

**Comment by shenli** [comment]
@jackysp @tiancaiamao PTAL

**Comment by BusyJay** [comment]
Actually it's an old feature that was removed. :rofl:
