### ISSUE TITLE
PD health check fails during deployment

### ISSUE THREAD

**Issue by jklofs** [pingcap/tidb#10041]
pd-ctl的health命令的结果和curl http://ip:2379/health健康结果不一样

使用tidb-ansible脚本start.yml进行启动tidb集群
执行命令：
```
ansible-playbook start.yml
```

结果：
![image](https://user-images.githubusercontent.com/24784965/55529612-cdf5bc00-56d4-11e9-832d-797cfe371d20.png)

执行pd-ctl -u http://10.100.249.234:2379

结果：
![image](https://user-images.githubusercontent.com/24784965/55529639-e960c700-56d4-11e9-8d70-71bec8c322b6.png)

执行curl http://10.100.249.233:2379/health

结果：
![image](https://user-images.githubusercontent.com/24784965/55529650-fd0c2d80-56d4-11e9-8088-5e47e04cf939.png)

理论上应该都是健康的，可是pd-ctl和curl返回的值不一样

tidb的版本是v2.1.6

**Comment by zimulala** [comment]
@jklofs 
Thanks for your feedback!
PTAL @nolouch

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
