### ISSUE TITLE
prometheus start with error

### ISSUE THREAD

**Issue by lwlw217** [pingcap/tidb#10045]
1. 启动prometheus时报错：报错信息如下
level=error ts=2019-04-04T07:40:11.53411309Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/data/mysql/tidb/deploy/conf/prometheus.yml): parsing YAML file /data/mysql/tidb/deploy/conf/prometheus.yml: yaml: line 82: did not find expected key"
2. 查看配置文件/data/mysql/tidb/deploy/conf/prometheus.yml
![image](https://user-images.githubusercontent.com/21055334/55547507-082a8200-5704-11e9-95af-d9d7e5576dba.png)
发现job_name 模块缩进有问题
3. level=error ts=2019-04-04T07:45:15.852696951Z caller=main.go:582 err="Error loading config couldn't load configuration (--config.file=/data/mysql/tidb/deploy/conf/prometheus.yml): parsing YAML file /data/mysql/tidb/deploy/conf/prometheus.yml: yaml: line 109: did not find expected key"
![image](https://user-images.githubusercontent.com/21055334/55547581-2c865e80-5704-11e9-9231-027621d4e0d6.png)
此处缩进也出现问题

缩进改正确后prometheus启动正常。

**Comment by shenli** [comment]
@wl21787 Have you change anything in yaml file before deploying the cluster?

**Comment by wl21787** [comment]
My yaml file(inventory.ini) like this:
![image](https://user-images.githubusercontent.com/21055334/55696107-17ece380-59ee-11e9-9ca2-3200acd3d582.png)

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
