### ISSUE TITLE
Offline TiKV nodes still shown in the Grafana

### ISSUE THREAD

**Issue by lwlw217** [pingcap/tidb#10052]
问题描述：
tikv曾经做过故障演练：增加节点、删除节点，以及系统重装模拟服务器故障等操作。现有tikv为三节点，但是在grafana中显示出现了历史存在的节点。

如下图：
![image](https://user-images.githubusercontent.com/21055334/55547889-d8c84500-5704-11e9-9b6a-12a03448e867.png)

红色标注的都是已经下线的tikv节点。
更为严重的时tikv-dashboard中都有同样的问题。

**Comment by shenli** [comment]
@wl21787 Thanks for your feedback! 
@nolouch Could you take a look?

**Comment by zhangjinpeng1987** [comment]
@wl21787 These offline TiKV nodes are still running or exited?

**Comment by wl21787** [comment]
离线的tikv节点是我故障演练的时候故意造成的。也就是说已经退出了。

**Comment by wl21787** [comment]
我升级版本到v2.1.7，offline tikv 节点的显示信息已经正常了。
![image](https://user-images.githubusercontent.com/21055334/55696404-62bb2b00-59ef-11e9-913d-d765e80e3ec7.png)

但是leader balance ratio 和 region balance ratio显示依然是100%
![image](https://user-images.githubusercontent.com/21055334/55696432-7f576300-59ef-11e9-8cca-394254d751a5.png)

**Comment by xujingbin** [comment]
@wl21787 @shenli I also encountered this problem, but the version upgrade to v3.0.0-rc.1 did not solve it。
![image](https://user-images.githubusercontent.com/22829724/58140664-ac479880-7c72-11e9-89c6-c2be5680ad96.png)
![image](https://user-images.githubusercontent.com/22829724/58140674-b7022d80-7c72-11e9-8049-b6d4b01ae564.png)

**Comment by liubo0127** [comment]
@xujingbin Please take a screenshot and send the `Store Size` metrics, as follow:
![image](https://user-images.githubusercontent.com/28344969/58154448-32c89e00-7ca4-11e9-94e3-b4fc96868fae.png)

**Comment by xujingbin** [comment]
@liubo0127 
![image](https://user-images.githubusercontent.com/22829724/58183685-514d8a00-7ce2-11e9-8276-ac219430b819.png)
![image](https://user-images.githubusercontent.com/22829724/58183729-65918700-7ce2-11e9-8e97-b3497e624682.png)

**Comment by liubo0127** [comment]
It seems that the expression is wrong and I suspect it has been modified. You can re-import it using the dashboard in the corresponding `tidb-ansible`.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
