### ISSUE TITLE
Known Compatibility page not working

### ISSUE THREAD

**Issue by hiqbn** [pingcap/tidb#10059]
This page 
https://github.com/pingcap/tidb/blob/master/sql/mysql-compatibility.md
on 
https://github.com/pingcap/tidb

is not found

also, auto increment counter supported? would like to chk out the difference between the two

**Comment by morgo** [comment]
This page is now [available here](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md).

**Comment by Isaacoco** [comment]
Same problem; https://github.com/Isaacoco/Help-for-Code

**Comment by nullnotnil** [comment]
It is better to provide a link to the website, as this will include redirects: https://docs.pingcap.com/tidb/stable/mysql-compatibility

I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
