### ISSUE TITLE
Question about NODE_disk_read_latency_more_than_32ms

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb#10062]
## General Question

Alert Rules :
```
 88   - alert: NODE_disk_read_latency_more_than_32ms
 89     expr: ( (rate(node_disk_read_time_ms{device=~".+"}[5m]) / rate(node_disk_reads_completed{device=~".+"}[5m])) or (irate(node_disk_read_time_ms{devi    ce=~".+"}[5m]) / irate(node_disk_reads_completed{device=~".+"}[5m])) ) > 32
 90     for: 3m
 91     labels:
 92       env: ENV_LABELS_ENV
 93       level: warning
 94       expr: ( (rate(node_disk_read_time_ms{device=~".+"}[5m]) / rate(node_disk_reads_completed{device=~".+"}[5m])) or (irate(node_disk_read_time_ms{de    vice=~".+"}[5m]) / irate(node_disk_reads_completed{device=~".+"}[5m])) ) > 32
 95     annotations:
 96       description: 'cluster: ENV_LABELS_ENV, instance: {{ $labels.instance }}, values: {{ $value }}'
 97       value: '{{ $value }}'
 98       summary: disk_read_latency_more_than_32ms
```
```
100   - alert: NODE_disk_write_latency_more_than_16ms
101     expr: ( (rate(node_disk_write_time_ms{device=~".+"}[5m]) / rate(node_disk_writes_completed{device=~".+"}[5m])) or (irate(node_disk_write_time_ms{d    evice=~".+"}[5m]) / irate(node_disk_writes_completed{device=~".+"}[5m]))  )> 16
102     for: 3m
103     labels:
104       env: ENV_LABELS_ENV
105       level: warning
106       expr: ( (rate(node_disk_write_time_ms{device=~".+"}[5m]) / rate(node_disk_writes_completed{device=~".+"}[5m])) or (irate(node_disk_write_time_ms    {device=~".+"}[5m]) / irate(node_disk_writes_completed{device=~".+"}[5m]))  )> 16
107     annotations:
108       description: 'cluster: ENV_LABELS_ENV, instance: {{ $labels.instance }}, values: {{ $value }}'
109       value: '{{ $value }}'
110       summary: disk_write_latency_more_than_16ms
```

Questions:

1. In Line 89  and line 101 you use rate/rate to get latancy,  but I think the result should be a multiple instead of a millisecond;

2. Why did you use 16 and 32, we use the alert rules and have got a lot of alerts；

3. Would you  please provide some advice to optimization this alarm;

**Comment by lysu** [comment]
@XSHui  Thanks for your feedback!
@liubo0127 @superlzs0476 PTAL?

**Comment by XSHui** [comment]
@liubo0127, @superlzs0476

**Comment by liubo0127** [comment]
1. Please check the description of the two expressions, you can refer to https://wiki.lnd.bz/display/LFTC/Node+Exporter and https://github.com/prometheus/node_exporter/issues/666
2. The default alarm value is a reference, and it certainly cannot match all scenarios. Users need to adjust according to their own environment.
3. Users need to adjust with the business, we can not provide reasonable advice without business information. Take the disk alarm as an example. If the service sensitivity is high, you can reduce the threshold.

**Comment by XSHui** [comment]
In question 1, I still don't quite understand why you use rate/rate to as the standard.
Why not use
```
node_disk_read_time_ms{device=~".+"}[5m]/node_disk_reads_completed{device=~".+"}[5m]
```
@liubo0127

**Comment by liubo0127** [comment]
You can check out prometheus related information. The node_disk_read_time_ms type is counter, rate() is best suited for alerting, and for graphing of slow-moving counters.. 
The other two references https://promcon.io/2017-munich/slides/monitoring-cloudflares-planet-scale-edge-network-with-prometheus.pdf and http://git.openstack.org/cgit/openstack/openstack-helm-infra/tree/prometheus/values.yaml?id=aac1c4e8c02680a159235c6097db0ed66cfbe104

**Comment by XSHui** [comment]
Thanks ！

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
