### ISSUE TITLE
not support show open table 

### ISSUE THREAD

**Issue by bkkkd** [pingcap/tidb#10070]
## Bug Report

1. What did you do?
If possible, provide a recipe for reproducing the error.

I use heidisql,  and meet error caused by unsupported `show open tables` command.

2. What did you expect to see?

no error

3. What did you see instead?

```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 9 near "OPEN TABLES"
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by erjiaqing** [comment]
Seems that TiDB does not have such operation like open a table in MySQL, maybe we can return a fake data, for example 0 or -1?

**Comment by lysu** [comment]
@bkkkd  Thanks for feedback.

TiDB has no concept like mysql's "table cache" and "open table", but we can adapte this to give a no error result in future

**Comment by bkkkd** [comment]
when I run it.

`SHOW OPEN TABLES FROM erp WHERE `in_use`!=0;
/* SQL错误（1105）：line 1 column 9 near " TABLES FROM erp WHERE `in_use`!=0" (total length 43) */`

**Comment by bkkkd** [comment]
and it try run a new version.but it has a error always.
MySQL [(none)]> show OPEN TABLES FROM erp WHERE `in_use`!=0;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 9 near "OPEN TABLES FROM erp WHERE `in_use`!=0"

**Comment by bkkkd** [comment]
> @bkkkd Thanks for feedback.
> 
> TiDB has no concept like mysql's "table cache" and "open table", but we can adapte this to give a no error result in future

thanks.

**Comment by morgo** [comment]
For simplicity, I think we can just return an empty result with the same structure as MySQL's `SHOW OPEN TABLES`. I prefer this to faked data.
