### ISSUE TITLE
Documentation for transaction retries is misleading

### ISSUE THREAD

**Issue by aphyr** [pingcap/tidb#10077]
TiDB's [documentation](https://www.pingcap.com/docs/sql/transaction-isolation/) repeatedly claims to offer snapshot isolation. However, two automatic retry mechanisms (#10075, #10076), invalidate this claim. The first mechanism is partly documented, but the documentation is confusing. The second is undocumented. Until these mechanisms can be disabled or fixed, I suggest updating the documentation in the following ways:

1. At the top of the transaction isolation page, claims like "TiDB implements Snapshot Isolation consistency" should include a prominent warning that this claim does not apply to current versions of TiDB; in general, transactions may exhibit lost updates due to automatic retries.

2. "Description of optimistic transactions" currently says:

> To disable the automatic retry of explicit transactions, configure the `tidb_disable_txn_auto_retry global variable:`
> ```
> set @@global.tidb_disable_txn_auto_retry = 1;
> ```

This paragraph should explain that `tidb_disable_txn_auto_retry` does not disable all retries; users need to set `tidb_retry_limit = 0` as well.

3. The section "Description of optimistic transactions" sounds like it's describing the difference between optimistic and pessimistic concurrency control:

> Because TiDB uses the optimistic transaction model, the final result might not be as expected if the transactions created by the explicit BEGIN statement automatically retry after meeting a conflict.

...

> Under the automatic retry mechanism of TiDB, all the executed statements for the first time are re-executed again. When whether the subsequent statements are to be executed or not depends on the results of the previous statements, automatic retry cannot guarantee the final result is as expected.

Optimistic transactions *do* execute differently than pessimistic ones, and users commonly ask questions about the semantics of conflicts and retries in optimistic databases. In addition, many MVCC databases *do* provide an automatic transaction retry mechanism which does *not* violate snapshot isolation. These factors could lead users to misinterpret this documentation, failing to realize that the retry mechanism invalidates fundamental properties of TiDB's transactional model.

Since these are properties specifically of TiDB's retry mechanism, and not optimistic transactions in general, you might consider changing the section title from "Description of optimistic transactions" to "Transactional anomalies caused by automatic retries". I also suggest changing language like "automatic retry cannot guarantee the final result is expected" to "automatic retry can violate snapshot isolation, causing lost updates."

**Comment by morgo** [comment]
> Until these mechanisms can be disabled or fixed, I suggest updating the documentation in the following ways

Thank you for reporting this issue!

We are discussing a longer-term fix to (#10075, #10076), so as you suggest I will interpret this issue as for the documentation specifically. I have created https://github.com/pingcap/docs/pull/1027 - I believe I have updated all the cases you mentioned, but appreciate a review too :-)
