### ISSUE TITLE
Support to show analyze status

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10081]
## Feature Request

**Is your feature request related to a problem? Please describe:**

To help DBAs know the progress of the `ANALYZE` statement.

**Describe the feature you'd like:**

Implement some SQL like `admin show analyze`.
It can return that how many regions information have been collected.

**Comment by winoros** [comment]
@lamxTyler @lzmhhh123 PTAL

**Comment by morgo** [comment]
Why not just estimated progress in `show processlist` output?

**Comment by winoros** [comment]
@morgo 
The result of the current `show processlist` is
```
mysql> show processlist;
+------+------+-----------+------+---------+------+-------+------------------+------+
| Id   | User | Host      | db   | Command | Time | State | Info             | Mem  |
+------+------+-----------+------+---------+------+-------+------------------+------+
|    1 | root | 127.0.0.1 | test | Query   |    0 | 2     | show processlist |    0 |
+------+------+-----------+------+---------+------+-------+------------------+------+
1 row in set (0.00 sec)
```

There's no appropriate column to store the progress status of `ANALYZE` i think.

**Comment by morgo** [comment]
@winoros Others have used the `State` column for this:
https://www.percona.com/blog/2009/11/17/new-tokudb-2-2-0-feature-more-query-progress-information/

Currently `2` means `autocommit`, which is not very useful. I would love to see us do something more with this column :-)
