### ISSUE TITLE
Implementation detail about SET TRANSACTION ISOLATION LEVEL

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tidb#10092]
I'm confused when working on this PR: https://github.com/pingcap/tidb/pull/10065.

I find that, `SET TRANSACTION ISOLATION LEVEL` will affect two internal variables:
1. `tx_isolation`
2. `transaction_isolation`

Can any body tell me, what's the difference between the two variables?

**Comment by lysu** [comment]
@marsishandsome 

just alias, and mysql's old stuff.

>"transaction_isolation was added in MySQL 5.7.20 as an alias for tx_isolation, which is now deprecated and is removed in MySQL 8.0. Applications should be adjusted to use transaction_isolation in preference to tx_isolation."

and there are same history question `tx_read_only`

> Prior to MySQL 5.7.20, use tx_isolation and tx_read_only rather than transaction_isolation and transaction_read_only.
