### ISSUE TITLE
import data from hive to TiDB is slower than MySQL

### ISSUE THREAD

**Issue by weishaopeng** [pingcap/tidb#10094]
我在使用hive2Tidb的过程中，发现写入速度比MySQL慢好几倍，甚至十几倍的情况。

**Comment by lysu** [comment]
thanks for feedback @weishaopeng 

TiDB's architecture is different from MySQL, so if compare with single node write speed, TiDB may be slower than single node MySQL, but TiDB can scale up write speed with more db & kv nodes， what is your hardware like?

besides that, what's your import sql? take look more grafana's  tikv/tidb also helps to find the import bottleneck.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
