### ISSUE TITLE
Does TiDB scale linearly with writes / reads?

### ISSUE THREAD

**Issue by hiqbn** [pingcap/tidb#10118]
Does TiDB scale linearly with writes / reads as I add more nodes to it? What's the limitation to the scaling in terms of speed in QPS?

**Comment by lysu** [comment]
@hiqbn Thanks for feedback.

TiDB can scale up with add nodes, it's unnormal to meet limit  if you have infine nodes, does you meet any question?

**Comment by hiqbn** [comment]
1. where are the benchmarks for these nodes and linear scaling?
2. secondary indexes for tidb will not affect scaling at scale?

**Comment by lysu** [comment]
1. maybe can take a look at this: https://github.com/pingcap/docs/blob/master/benchmark/sysbench.md#scenario-two-tidb-horizontal-scalability-test

2. secondary indexes data also be stored as kv datas in tikv, and it will scale up as region split when indexes data grow just like normal table data.

**Comment by hiqbn** [comment]
Can it do full text search like mysql? otherwise is the search sequential? 
the benchmark seems too good. any downsides of tidb in general or what should we be looking out for?

**Comment by morgo** [comment]
> Can it do full text search like mysql? otherwise is the search sequential?
> the benchmark seems too good. any downsides of tidb in general or what should we be looking out for?

`FULLTEXT` is not supported.  See [this page](https://www.pingcap.com/docs/sql/mysql-compatibility/) for compatibility with MySQL.
