### ISSUE TITLE
how to configurate single tikv process use multiple hard disk.

### ISSUE THREAD

**Issue by taoanqi** [pingcap/tidb#10128]
```
[raftstore]
# The default value is true, which means writing the data on the disk compulsorily. If it is not in a business scenario
# of the financial security level, it is recommended to set the value to false to achieve better performance.
sync-log = true

# Raft RocksDB directory. The default value is Raft subdirectory of [storage.data-dir].
# If there are multiple disks on the machine, store the data of Raft RocksDB on different disks to improve TiKV performance.
# raftdb-dir = "/tmp/tikv/store/raft"

```

tikv tuning guide said: "If there are multiple disks on the machine, store the data of Raft RocksDB on different disks to improve TiKV performance.", how to store data of raft rocksdb data on different disk?

**Comment by lysu** [comment]
@taoanqi Hi, it means configurate `raftdb-dir` to anther dir that be mounted to different disk, the disk is different to `storage.data-dir`'s mounted disk.

and we can see disk mount info by linux command `df `.

**Comment by taoanqi** [comment]
@lysu 你好，您的意思是存储数据和安装路径可以配置不同磁盘？我的问题是需要将数据存在不同磁盘里

**Comment by shenli** [comment]
@taoanqi One tikv instance embedded two rocksdb instances. One for data, and another one for raft log. For each rocksdb instance, it could only use one disk.

**Comment by taoanqi** [comment]
@shenli 非常感谢，看官方文档理解上有些误差，是因为rocksdb自身的限制问题吗？

**Comment by shenli** [comment]
@taoanqi Yes

**Comment by taoanqi** [comment]
@shenli 非常感谢，了解了
