### ISSUE TITLE
My hostname is ip, and tidb-ansible can only get the prefix.

### ISSUE THREAD

**Issue by saup007** [pingcap/tidb#10135]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

My hostname is ip, and tidb-ansible can only get the prefix.

for examp：
```
IP: 10.14.11.10 hostname 10.13.11.10  PD TIDB
IP:  10.14.11.11 hostname 10.13.11.11  PD  TIDB
IP:  10.14.11.12 hostname 10.13.11.12  PD  TIDB
IP:  10.14.11.13 hostname 10.13.11.13  TIKV
IP:  10.14.11.14 hostname 10.13.11.14   TIKV
IP:  10.14.11.15 hostname 10.13.11.15    TIKV
```

Ansible FAILED! => playbook: deploy.yml; TASK: check_system_dynamic : Preflight check - Does every node in cluster have different hostname; message: {"changed": false, "msg": "hostnames of all nodes in cluster: ['10', '10', '10', '10', '10', '10']\n"}

set different hostname:

hostnamectl set-hostname h12128
/etc/sysconfig/network

```
IP: 10.14.11.10 hostname h10
IP:  10.14.11.11 hostname h11
IP:  10.14.11.12 hostname h12
IP:  10.14.11.13 hostname h13
IP:  10.14.11.14 hostname h14
IP:  10.14.11.15 hostname h15

```

but pd start failed.

all pd name is pd_10。

scripts/run_pd.sh
```
exec bin/pd-server \
    --name="pd_10" \
    --client-urls="http://10.14.11.10:38002" \
    --advertise-client-urls="http://110.14.11.10:38002" \
    --peer-urls="http://10.14.11.10:38003" \
    --advertise-peer-urls="http://10.14.11.10:38003" \
    --data-dir="/data1/tidb39002/data.pd" \
    --initial-cluster="pd_10=http://10.14.11.10:38003,pd_10=http://10.14.11.11:38003,pd_10=http://10.14.11.12:38003" \
    --config=conf/pd.toml \
    --log-file="/data1/tidb39002/log/pd.log" 2>> "/data1/tidb39002/log/pd_stderr.log"
```

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidb 2.1.7  && tidb-ansible-2.1.7

**Comment by tiancaiamao** [comment]
PTAL @liubo0127

**Comment by liubo0127** [comment]
Thanks for the feedback, I will test it and reply later.

**Comment by liubo0127** [comment]
Tested, if the hostname contains '.', it will be truncated with '.', this exception is generated when ansible gets machine information, you can give an issue to [ansible](https://github.com/ansible/ansible). It is currently recommended that the hostname not include ‘.’. 

**Solution**: After resetting the hostname using `hostnamectl set-hostname $hostname`, execute ansible-playbook deploy.yml to deploy it.

**Comment by saup007** [comment]
> Tested, if the hostname contains '.', it will be truncated with '.', this exception is generated when ansible gets machine information, you can give an issue to [ansible](https://github.com/ansible/ansible). It is currently recommended that the hostname not include ‘.’.
> 
> **Solution**: After resetting the hostname using `hostnamectl set-hostname $hostname`, execute ansible-playbook deploy.yml to deploy it.

hostnamectl set-hostname h12128
/etc/sysconfig/network

IP: 10.14.11.10 hostname h10
IP:  10.14.11.11 hostname h11
IP:  10.14.11.12 hostname h12
IP:  10.14.11.13 hostname h13
IP:  10.14.11.14 hostname h14
IP:  10.14.11.15 hostname h15

but pd start failed. all pd name is pd_10。

scripts/run_pd.sh
```
exec bin/pd-server \
    --name="pd_10" \
    --client-urls="http://10.14.11.10:38002" \
    --advertise-client-urls="http://110.14.11.10:38002" \
    --peer-urls="http://10.14.11.10:38003" \
    --advertise-peer-urls="http://10.14.11.10:38003" \
    --data-dir="/data1/tidb39002/data.pd" \
    --initial-cluster="pd_10=http://10.14.11.10:38003,pd_10=http://10.14.11.11:38003,pd_3=http://10.14.11.12:38003" \
    --config=conf/pd.toml \
    --log-file="/data1/tidb39002/log/pd.log" 2>> "/data1/tidb39002/log/pd_stderr.log"
```

**Comment by liubo0127** [comment]
> hostnamectl set-hostname h12128
> /etc/sysconfig/network

> IP: 10.14.11.10 hostname h10
> IP: 10.14.11.11 hostname h11
> IP: 10.14.11.12 hostname h12
> IP: 10.14.11.13 hostname h13
> IP: 10.14.11.14 hostname h14
> IP: 10.14.11.15 hostname h15

Please explain the detailed operation.

**Comment by saup007** [comment]
> > hostnamectl set-hostname h12128
> > /etc/sysconfig/network
> 
> > IP: 10.14.11.10 hostname h10
> > IP: 10.14.11.11 hostname h11
> > IP: 10.14.11.12 hostname h12
> > IP: 10.14.11.13 hostname h13
> > IP: 10.14.11.14 hostname h14
> > IP: 10.14.11.15 hostname h15
> 
> Please explain the detailed operation, confirm the hostname of the machine in the cluster.

hostnamectl set-hostname h10 && hostname
hostnamectl set-hostname h11 && hostname
hostnamectl set-hostname h12 && hostname
hostnamectl set-hostname h13 && hostname
hostnamectl set-hostname h14 && hostname
hostnamectl set-hostname h15 && hostname

execute ansible-playbook deploy.yml  success, but pd start failed. all pd name is pd_10。

**Comment by liubo0127** [comment]
Execute `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"` in the `tidb-ansible` directory, and send a screenshot

**Comment by saup007** [comment]
> Execute `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"` in the `tidb-ansible` directory, and send a screenshot. This command will output the hostname of each node.

nsible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
PD1 | FAILED | rc=-1 >>
The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'

PD2 | FAILED | rc=-1 >>
The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'

PD3 | FAILED | rc=-1 >>
The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'

**Comment by liubo0127** [comment]
> > Execute `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"` in the `tidb-ansible` directory, and send a screenshot. This command will output the hostname of each node.
> 
> ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
> PD1 | FAILED | rc=-1 >>
> The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'
> 
> PD2 | FAILED | rc=-1 >>
> The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'
> 
> PD3 | FAILED | rc=-1 >>
> The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'

Execute `ansible pd_servers -m setup` first, then execute `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"`.

**Comment by saup007** [comment]
> > > Execute `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"` in the `tidb-ansible` directory, and send a screenshot. This command will output the hostname of each node.
> > 
> > 
> > ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
> > PD1 | FAILED | rc=-1 >>
> > The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'
> > PD2 | FAILED | rc=-1 >>
> > The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'
> > PD3 | FAILED | rc=-1 >>
> > The task includes an option with an undefined variable. The error was: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'ansible_hostname'
> 
> Execute `ansible pd_servers -m setup` first, then execute `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"`.


```
$ ansible pd_servers -m setup first, then execute ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"

ERROR! Extraneous options or arguments

$ ansible --version
ansible 2.6.14
  config file = /usr/home/tidb/tidb-ansible-2.1.7/ansible.cfg
  configured module search path = [u'/usr/home/tidb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

```

**Comment by liubo0127** [comment]
This is two commands:
- `ansible pd_servers -m setup`
- `ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"`

Only need the result of the second command.

**Comment by shenli** [comment]
@saup007 Does it solved your problem?

**Comment by saup007** [comment]
```
ansible pd_servers -m setup

ansible pd_servers -m shell -a "echo {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
PD3 | SUCCESS | rc=0 >>
h102

PD2 | SUCCESS | rc=0 >>
224

PD1 | SUCCESS | rc=0 >>
h223
```

I have deployed with the new environment and are using v2.1.8,Now it is working fine.

thanks.

I don't think it's a good idea to use a hostname.
