### ISSUE TITLE
TiDB Alpine run like MySQL docker image

### ISSUE THREAD

**Issue by jniltinho** [pingcap/tidb#10141]
## Info -> https://gitlab.com/jniltinho/tidb-alpine

Today I created a build project in my gitlab.com, to generate a TiDB image the same as the MySQL docker image, so that people will gradually test and thus I can more easily migrate their environment to TiDB.

https://cloud.docker.com/repository/docker/jniltinho/tidb-alpine/general

**Comment by morgo** [comment]
@jniltinho nice work!

/cc @gregwebs @tennix @kolbe @c4pt0r

**Comment by gregwebs** [comment]
@jniltinho thanks, I like this image as an option for end users to easily run a single node tidb. @morgo how would we direct users to this option?

**Comment by morgo** [comment]
@gregwebs I agree!

@jniltinho A few things to mention:
- We recently added [homebrew](https://pingcap.com/docs/dev/how-to/get-started/local-cluster/install-from-homebrew/) and [dbdeployer](https://pingcap.com/docs/dev/how-to/get-started/local-cluster/install-from-dbdeployer/) install options to our manual. We like to include a caveat that this installation method is for testing, and slower than tikv.
- We have a section of our manual for third-party blog posts and tutorials. If you want to write a quick Howto, we'd be happy to link from here.
- Is it possible for users to be able to customize the timezone? If not, UTC may be a better default.

**Comment by gregwebs** [comment]
I created an issue in the docs repo, that is probably the best place to contribute this information. https://github.com/pingcap/docs/pull/1060
