### ISSUE TITLE
The result order of a query `select .. order by .. limit N` is not the same when the N is different

### ISSUE THREAD

**Issue by fxrs111** [pingcap/tidb#10148]
## Bug Report

在使用order by排序和limit分页查询时，按照时间(时间有相同的)排序分别查询0到10 和0到20时，返回的结果顺序不一致是什么原因

在使用MySQL或者其它数据库时没有类似的问题
![排序问题](https://user-images.githubusercontent.com/46838109/56113520-b0580a80-5f90-11e9-9268-03f608f3a602.png)

[](url)

**Comment by tiancaiamao** [comment]
Hi, @fxrs111 
You're using `order by create_time` and ask for `item_name` to be ordered

**Comment by fxrs111** [comment]
如果使用多个字段就增加了查询的时候，性能会受影响

**Comment by tiancaiamao** [comment]
Did you test that? @fxrs111 
If the plan is not changed, I think there is no performance issue here.

**Comment by shenli** [comment]
Please refer to this question: https://dba.stackexchange.com/questions/6051/what-is-the-default-order-of-records-for-a-select-statement-in-mysql/6064

> In the SQL world, order is not an inherent property of a set of data. Thus, you get no guarantees from your RDBMS that your data will come back in a certain order -- or even in a consistent order -- unless you query your data with an ORDER BY clause.

So, to answer your question:

MySQL sorts the records however it wants without any guarantee of consistency.
If you intend to rely on this order for anything, you must specify your desired order using ORDER BY. To do anything else is to set yourself up for unwelcome surprises.
This is a property of all SQL, not just MySQL. The relevant text in the SQL-92 spec is:

If an <order by clause> is not specified, then the ordering of the rows of Q is implementation-dependent.
