### ISSUE TITLE
Error 1105: [try again later]: WriteConflict: startTS=407719599396618242, conflictTS=407719599396618241, key={tableID=302, handle=1} primary={tableID=302, indexID=1, indexValues={53083503, 1, }}

### ISSUE THREAD

**Issue by android-coco** [pingcap/tidb#10155]
## General Question

Error 1105: [try again later]: WriteConflict: startTS=407719599396618242, conflictTS=407719599396618241, key={tableID=302, handle=1} primary={tableID=302, indexID=1, indexValues={53083503, 1, }}

**Comment by Bruce2jiang** [comment]
How to solve it

**Comment by Bruce2jiang** [comment]
@android-coco How to solve it
