### ISSUE TITLE
disable strict sql mode should not ignore bad null error

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#10153]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
drop table if exists t;
create table t (i int not null);
set sql_mode = '';
insert into t values (null);
```

2. What did you expect to see?
```
ERROR 1048 (23000) at line 4: Column 'i' cannot be null
```

3. What did you see instead?
No error returned.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
9d25a85bda58a19e0c34b09fc88af8c3ccc01b52 at master branch.

**Comment by shenli** [comment]
How do you find this bug?

**Comment by jackysp** [comment]
I'm porting MySQL tests.
