### ISSUE TITLE
Failed to install tidb 2.1.8 with ansible 2.1.8

### ISSUE THREAD

**Issue by bqwzhl20** [pingcap/tidb#10164]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
TASK [local : cp tispark] **************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "cp -v /home/tidb/tidb-ansible/downloads/core/target/tispark-core-*-SNAPSHOT-jar-with-dependencies.jar \"/home/tidb/tidb-ansible/resources/bin/tispark-SNAPSHOT-jar-with-dependencies.jar\"", "delta": "0:00:00.227253", "end": "2019-04-16 15:03:31.680292", "msg": "non-zero return code", "rc": 1, "start": "2019-04-16 15:03:31.453039", "stderr": "cp: cannot stat ‘/home/tidb/tidb-ansible/downloads/core/target/tispark-core-*-SNAPSHOT-jar-with-dependencies.jar’: No such file or directory", "stderr_lines": ["cp: cannot stat ‘/home/tidb/tidb-ansible/downloads/core/target/tispark-core-*-SNAPSHOT-jar-with-dependencies.jar’: No such file or directory"], "stdout": "", "stdout_lines": []}

[tidb@db-ansible target]$ pwd
/home/tidb/tidb-ansible/downloads/core/target
[tidb@db-ansible target]$ ll
total 27908
-rw-r--r-- 1 tidb tidb   506913 Apr 15 22:23 tispark-core-2.1-SNAPSHOT.jar
-rw-r--r-- 1 tidb tidb   658025 Apr 15 22:23 tispark-core-2.1-SNAPSHOT-javadoc.jar
-rw-r--r-- 1 tidb tidb    71252 Apr 15 22:23 tispark-core-2.1-SNAPSHOT-sources.jar
-rw-r--r-- 1 tidb tidb 27335740 Apr 15 22:23 tispark-core-2.1-SNAPSHOT-spark-2.3.3-jar-with-dependencies-jar-with-dependencies.jar

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.1.8

**Comment by tiancaiamao** [comment]
PTAL @liubo0127

**Comment by liubo0127** [comment]
Tispark has been repackaged, it should be fine now, please try again.

**Comment by bqwzhl20** [comment]
it's ok，thanks
