### ISSUE TITLE
DATE_FORMAT function wrongly causes " ERROR 1265 (01000): Data Truncated"

### ISSUE THREAD

**Issue by luckyfish0826** [pingcap/tidb#10171]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I insert data into a table, yet in the process, I used DATE_FORMAT function in my where statement,
---   DATE_FORMAT(transaction_date, '%Y%m%D')= 20190414

2. What did you expect to see?
insert done without any problem.

3. What did you see instead?
ERROR 1265 (01000): Data Truncated

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.5-1-g0bd6b1b
Git Commit Hash: 0bd6b1b60816bf8a2022e657d7a472311548d82e
Git Branch: release-2.1
UTC Build Time: 2019-02-28 08:17:03
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

5. My explain to this bug.
More: 
If I drop this where statement, no error. If I changed where statement to something else, such as "1=1", "flag=true", no error, too.
My guess:
if any data truncated during insert, tidb reports error, this is fine. Yet, when execute DATE_FORMAT function, it change "2019-04-13 22:56:26" into "20190413", so tidb thought there is data tuncate, report error. This is not right. It should only report error when truncate happend during final insert stage, not any other stage.

Fix should be easy, but now I really didn't have time to do this. Hope you guys can do it.
Contact me at young0826@qq.com for any problem.

**Comment by luckyfish0826** [comment]
if used DATE_FORMAT (“2019-01-15 00:00:00” ,'%Y%m%d'), no error, because there is not data lost. This confirms my guess.

**Comment by kolbe** [comment]
Can you please clarify what you're doing? Where does `transaction_date` originate in your INSERT statement? Can you reproduce this with a small sample table?

**Comment by tiancaiamao** [comment]
Could provide the SQL and table schema so we can reproduce it? @luckyfish0826 

```
mysql> create table xx (dt datetime);
Query OK, 0 rows affected (0.10 sec)

mysql> select * from xx where date_format(dt, '%Y%m%D') = 20190414;
Empty set (0.00 sec)
```

**Comment by luckyfish0826** [comment]
Close this as I could not exactly reproduce this issue. Thanks for your attention
