### ISSUE TITLE
How use Tidb on k8s  / Raid HDD instead of SSD

### ISSUE THREAD

**Issue by Livezxy** [pingcap/tidb#10182]
we plan to use tidb on production environment , 
but our server is k8s-cluster, 
and storge is Raid 5 of 10 x 4TB HDD  

May i use Raid instead of SSD?  how large Tidb need  ?
And..  any way to use tidb with k8s ?

**Comment by tiancaiamao** [comment]
It's not recommand to deploy on HDD @live-xy 
See https://pingcap.com/docs/op-guide/recommendation/

I guess @tennix would like to answer k8s deployment related questions

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
