### ISSUE TITLE
TiDB binlog drainer only write to one partition

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#10185]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Setup TiDB binlog, write data to kafka

2. What did you expect to see?

data written to different partitions evenly

3. What did you see instead?

only wrote to first partition

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.1.4

**Comment by tiancaiamao** [comment]
PTAL @july2993

**Comment by july2993** [comment]
this is work as expected now, but we will support writing multi partition later.

**Comment by zz-jason** [comment]
Oh, this issue is about writing binglog to multiple Kafka partition, not related to the partition table.

**Comment by tiancaiamao** [comment]
I'll close it, a better place for this issue is https://github.com/pingcap/tidb-tools ... I mean, if it's really a problem.
