### ISSUE TITLE
support "SHOW PROCESSLIST MEMINFO"

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#10199]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In https://github.com/pingcap/tidb/pull/8543, we removed the memory info from the result of `show processlist`. As discussed in https://github.com/pingcap/tidb/pull/8543#issuecomment-444119260, we decide to add a new command like `show processlist meminfo` to show the process lists + meminfo

**Describe the feature you'd like:**

use `show processlist meminfo` to show the result of process lists and meminfo

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by ngaut** [comment]
Can we add a new column to the output of "show processlist"? It should be more convenient.
What do you guys think? @morgo @kolbe

**Comment by morgo** [comment]
@ngaut It actually was on `show processlist`, the previous PR removed it. The memory feature does not work exactly as described - it only records memory of some parts of execution, which makes it confusing for new users (and me:-)).

**Comment by ngaut** [comment]
Great, let's make it work properly.

**Comment by zz-jason** [comment]
> @ngaut It actually was on `show processlist`, the previous PR removed it. The memory feature does not work exactly as described - it only records memory of some parts of execution, which makes it confusing for new users (and me:-)).

We can trace memory usage in distsql now. It's much precise than before. However the memory info for some simple statements can still be zero. Because they are not memory intensive queries. 

I think we can optimize it in these ways:
1. Display the memory info in `show processlist`. Don'y display zero memory usage for simple queries. We can display a message like "little".
2. Display the memory info in `show processlist meminfo`. Display the exact memory usage we tracked.

**Comment by kolbe** [comment]
Why don't we just add a column to information_schema.processlist instead of fooling around w/ extra SHOW PROCESSLIST syntax?

**Comment by morgo** [comment]
+1 to @kolbe's suggestion. It is easier to extend `i_s` because applications can write SQL to customize it. For `SHOW` commands it is better to remain compatible.

**Comment by zz-jason** [comment]
@morgo, @kolbe To summary, the refinements we should do are:
1. add a column named `mem` for table `information_schema.processlist`
2. add a new command `show processlist meminfo` to display the result of `show processlist` plus a `mem` column.

Am I right? If so, @SunRunAway is going to address this issue.

**Comment by kolbe** [comment]
I think we should only do #1 (add a column to `information_schema.processlist`). There is no great benefit to extending `show processlist` with additional syntax.
