### ISSUE TITLE
How to modify the `auto_increment` attribute and the column type?

### ISSUE THREAD

**Issue by fxrs111** [pingcap/tidb#10190]
在使用的过程中发现有几个问题：
1、若数据表初始设计主键不是自增，后期再想设置成自增时会报unsupported modify column set auto_increment，有没有什么方式能够解决修改自增
2、数据表字段初始设计时是long，后期想转成varchar时更改不了
3、数据字段的长度修改，把数据字段长度从大修改成小一些的时候，修改不了

数据库版本使用的是2.1.2

有没有什么方式能够进行修改呢

**Comment by tiancaiamao** [comment]
Alter table to add the `auto_increment` attribute is unsupported, you can create a new table and copy the old table to the new one
Change the column type from long to varchar is not supported

See here for the alter table modify column limitation:
https://github.com/pingcap/docs-cn/blob/master/sql/ddl.md#alter-table-%E8%AF%AD%E6%B3%95

Maybe you have the create a new table and copy data for all those changes @fxrs111

**Comment by zimulala** [comment]
The related issue(#18283) about changing the column type

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!

**Comment by llplmlyd** [comment]
excuse me? the link @tiancaiamao provided can not be opened now. Can anybody update this issue?

**Comment by crazycs520** [comment]
Current TiDB still not support modify column to add `auto_increment`:

TiDB:

```sql
test> create table t (a int key);
Query OK, 0 rows affected
Time: 0.005s
test> alter table t modify column a int auto_increment;
(8200, "Unsupported modify column: can't set auto_increment")
```

In mysql 8.0:
```sql
test> create table t (a int key);
Query OK, 0 rows affected
Time: 0.024s
test> alter table t modify column a int auto_increment;
Query OK, 0 rows affected
```

**Comment by tiancaiamao** [comment]
About the restrictions of `auto_increment`:
https://docs.pingcap.com/tidb/v6.0/auto-increment#restrictions

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
