### ISSUE TITLE
Support TLS 1.3 handshake 

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#10249]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

MySQL 8.0 support TLS1.3 https://dev.mysql.com/doc/refman/8.0/en/encrypted-connection-protocols-ciphers.html

Go adds opt-in support for TLS 1.3 https://golang.org/doc/go1.12#tls_1_3

now it's disabled by default  but maybe enabled in future new version golang. 

but with `GODEBUG=tls13=1` to run tidb test `TestTLS` 

2. What did you expect to see?

test success

3. What did you see instead?

```
FAIL: tidb_test.go:297: TidbTestSuite.TestTLS

tidb_test.go:351:
    c.Assert(err, IsNil)
... value *net.OpError = &net.OpError{Op:"remote error", Net:"", Source:net.Addr(nil), Addr:net.Addr(nil), Err:0x28} ("remote error: tls: handshake failure")
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v3.0.0-beta.1-156-ga28d8779c
Git Commit Hash: a28d8779c18d0fae4362b99928511711584d7eb9
Git Branch: master
UTC Build Time: 2019-04-24 07:07:04
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by ngaut** [comment]
Related: https://github.com/pingcap/tidb/issues/10187
