### ISSUE TITLE
invalid range,range.start should be smaller than range.end

### ISSUE THREAD

**Issue by superlzs0476** [pingcap/tidb#10242]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Execute query output errors .
SQL:
select count(*) from transaction_stats_tab WHERE (whs_id = 'IDG' AND transaction_type = 2
2. What did you expect to see?
Execute successful.

3. What did you see instead?
ERROR 1105(HY0000):other error: unknown error StringError("[src/coprocessor/dag/executor/table_scan.rs:56]: invalid range,range.start should be smaller than range.end, but got [[116, 128, 0, 0, 0, 0, 0, 19, 96, 95, 114, 254, 66, 203, 60, 110, 208, 160, 57],[116, 128, 0, 0, 0, 0, 0, 19, 96, 95, 114, 0, 28, 248, 3, 250, 72, 160, 57])")

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-5-g4dad722
Git Commit Hash: 4dad722bbf573050477328ce8ff5bcb7f1a1c7f1
Git Branch: release-2.1
UTC Build Time: 2018-12-07 02:29:19
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by shenli** [comment]
@superlzs0476 Could please provide the schema?

**Comment by superlzs0476** [comment]
`mysql> show create table transaction_stats_tab \G
*************************** 1. row ***************************
       Table: transaction_stats_tab
Create Table: CREATE TABLE `transaction_stats_tab` (
  `id` bigint(20) UNSIGNED NOT NULL COMMENT 'primary key',
  `transaction_sid` bigint(20) UNSIGNED NOT NULL COMMENT 'global unique identifier',
  `transaction_type` tinyint(4) UNSIGNED NOT NULL COMMENT 'transaction type',
  `whs_id` varchar(4) NOT NULL COMMENT 'warehouse identifier, e.g. IDG',
  `sheet_id` varchar(32) NOT NULL COMMENT 'id of related sheet',
  `sheet_time` int(10) UNSIGNED NOT NULL COMMENT 'process time of related sheet',
  `sheet_type` tinyint(4) UNSIGNED NOT NULL COMMENT 'type of related sheet',
  `shop_id` int(10) UNSIGNED NOT NULL COMMENT 'shop identifier',
  `sku_id` varchar(64) NOT NULL COMMENT 'sku identifier',
  `sku_name` varbinary(1024) NOT NULL COMMENT 'sku name',
  `category_id` int(10) UNSIGNED NOT NULL COMMENT 'sku category identifier',
  `quantity` int(10) UNSIGNED NOT NULL COMMENT 'transaction quantity',
  `direct_flag` tinyint(1) UNSIGNED NOT NULL COMMENT 'flag of transaction quantity: minus/plus',
  `uom` varchar(16) NOT NULL DEFAULT 'pcs' COMMENT 'unit of material',
  `location_id` varchar(64) NOT NULL COMMENT 'location identifier',
  `from_location_id` varchar(64) NOT NULL COMMENT 'from location identifier',
  `to_location_id` varchar(64) NOT NULL COMMENT 'to location identifier',
  `close_quantity` int(10) UNSIGNED NOT NULL COMMENT 'close quantity of to sku location',
  `batch_trans` json DEFAULT NULL COMMENT 'batch transfer info',
  `operator` varchar(64) NOT NULL DEFAULT '' COMMENT 'transaction operator',
  `extra` json DEFAULT NULL COMMENT 'extra data',
  `ctime` int(10) UNSIGNED NOT NULL COMMENT 'creation time',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_transaction_sid` (`transaction_sid`),
  KEY `idx_sku_location_id` (`sku_id`,`location_id`),
  KEY `idx_location_id` (`location_id`),
  KEY `idx_sheet_type_id` (`sheet_type`,`sheet_id`),
  KEY `idx_sheet_time` (`sheet_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='table used to store transactions statics related to inventory.Statics are collected on transaction direct dimension, i.e, CR or DR'
1 row in set (0.00 sec)`

**Comment by superlzs0476** [comment]
```sql
mysql> explain select count(*) from transaction_stats_tab WHERE (whs_id = 'IDG' AND transaction_type = 2 );
+--------------------------+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------+
| id                       | count   | task | operator info                                                                                                                              |
+--------------------------+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------+
| StreamAgg_20             | 1.00    | root | funcs:count(col_0)                                                                                                                         |
| └─TableReader_21         | 1.00    | root | data:StreamAgg_9                                                                                                                           |
|   └─StreamAgg_9          | 1.00    | cop  | funcs:count(1)                                                                                                                             |
|     └─Selection_19       | 37.07   | cop  | eq(staging_shopee_wms_log_db.transaction_stats_tab.transaction_type, 2), eq(staging_shopee_wms_log_db.transaction_stats_tab.whs_id, "IDG") |
|       └─TableScan_18     | 2556.00 | cop  | table:transaction_stats_tab, range:[-inf,+inf], keep order:false                                                                           |
+--------------------------+---------+------+--------------------------------------------------------------------------------------------------------------------------------------------+
5 rows in set (0.00 sec)```

**Comment by lamxTyler** [comment]
@superlzs0476 Could you also provide the statistics?

**Comment by lamxTyler** [comment]
The wrong range comes from feedback when split ranges. Can we cherry-pick the part that relates to feedback of https://github.com/pingcap/tidb/pull/7921? @winoros
