### ISSUE TITLE
Installing tidb-2.0 on CentOS6.4 meet error.

### ISSUE THREAD

**Issue by Jonyezog** [pingcap/tidb#10245]
CentOS6.4安装tidb2.0 在中控机进行初始化的时候提示操作系统版本需要CentOS7.3及以上 这个怎么绕过？

**Comment by shenli** [comment]
We do not support low version centos.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
