### ISSUE TITLE
One of TiKV node can not startup

### ISSUE THREAD

**Issue by Cavinlz** [pingcap/tidb#10257]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

> One of TiKV store can not be up since last server restarted. Please check the tikv.log as follows:
> ""
> 2019/04/24 06:12:32.135 INFO tikv-server.rs:464: connect to PD cluster 6683011657363757862
> 2019/04/24 06:12:32.144 INFO mod.rs:343: starting working thread: addr-resolver
> 2019/04/24 06:12:32.149 ERRO tikv-server.rs:166: failed to create kv engine: "Corruption: error in middle of record"
> ""
> 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

> Release Version: v2.1.6
> Git Commit Hash: 66e639e8e127f71662f37287eb984dd84d169cba
> Git Branch: HEAD
> UTC Build Time: 2019-03-15 09:09:07
> GoVersion: go version go1.11.2 linux/amd64
> Race Enabled: false
> TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
> Check Table Before Drop: false

**Comment by siddontang** [comment]
seem the data is corrupted, before the restart, did your machine crash? 

how about the output of `dmesg`?

**Comment by Cavinlz** [comment]
Thx for the replies.   Actually the sever had encountered some problems and shutted down unexpectly once. So any further action or advice could be done to settle the issue  ?  How to repair and restart the  TiKV node again  ? Thx.
