### ISSUE TITLE
tikv1's available size is different in grafana 

### ISSUE THREAD

**Issue by xujingbin** [pingcap/tidb#10315]
## General Question

![image](https://user-images.githubusercontent.com/22829724/56906125-30738980-6ad4-11e9-8aba-c0cf381b4cee.png)
I once started a tidis and registered with the cluster

**Comment by xujingbin** [comment]
How do I delete a capacity that shouldn't exist

**Comment by winkyao** [comment]
@nolouch PTAL

**Comment by nolouch** [comment]
@xujingbin Could you show the result in the panel of the query `tikv_store_size_bytes{instance=~"$instance", type="available"}` and adjust the `legend format`.
Like: 
![DeepinScreenshot_select-area_20190430160424](https://user-images.githubusercontent.com/6428910/56948037-775b9080-6b61-11e9-98aa-8dfe3afffcc1.png)

**Comment by xujingbin** [comment]
![image](https://user-images.githubusercontent.com/22829724/56949397-6745b000-6b65-11e9-9cf8-d1ae7584a284.png)

**Comment by xujingbin** [comment]
![image](https://user-images.githubusercontent.com/22829724/56949517-b7bd0d80-6b65-11e9-83d2-05b5f185e9c1.png)

**Comment by nolouch** [comment]
Why no data?

**Comment by xujingbin** [comment]
![image](https://user-images.githubusercontent.com/22829724/56953263-b04e3200-6b6e-11e9-94a6-3b745a93cd42.png)
it need variable "instance"，Is this Prometheus' problem? How can i clean the Prometheus data

**Comment by nolouch** [comment]
@xujingbin I does no idea about your instance `work1` and `node1` report in grafana. please check your environment.
