### ISSUE TITLE
do you have a group of dingding or wechat？

### ISSUE THREAD

**Issue by naah69** [pingcap/tidb#10330]
## General Question

do you have a group of dingding or wechat？
i have a question that may need to answer by your technical personnel.
it is 'how did you do about auto-shard when the node were added'

**Comment by shenli** [comment]
@naah69 There are many posts in our blog. FYI: https://pingcap.com/blog-cn/

**Comment by winkyao** [comment]
@naah69 https://zhuanlan.zhihu.com/p/26967545 This is a blog which you may be interested.

**Comment by shenli** [comment]
@naah69 Feel free to re-open this issue if you need more information.
