### ISSUE TITLE
Wrong feedback for unsigned column.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10365]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Just using our unit-test.
`TestUnsignedFeedbackRanges` in `statistics` package.
Don' create `tinyint` column, create `bigint` column instead.

2. What did you expect to see?

Result not changed, test can be passed.

3. What did you see instead?
```
FAIL: update_test.go:1472: testStatsSuite.TestUnsignedFeedbackRanges

update_test.go:1526:
    c.Assert(tbl.Columns[1].ToString(0), Equals, tests[i].hist)
... obtained string = "" +
...     "column:1 ndv:16 totColSize:0\n" +
...     "num: 8 lower_bound: 0 upper_bound: 7 repeats: 0\n" +
...     "num: 8 lower_bound: 8 upper_bound: 15 repeats: 0"
... expected string = "" +
...     "column:1 ndv:30 totColSize:0\n" +
...     "num: 8 lower_bound: 0 upper_bound: 7 repeats: 0\n" +
...     "num: 8 lower_bound: 8 upper_bound: 15 repeats: 0\n" +
...     "num: 14 lower_bound: 16 upper_bound: 255 repeats: 0"
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master 0106361cd92da0a5f79557d33613841bab9271b3

**Comment by winoros** [comment]
This is because the unsigned part and signed part is splitted to two request, and so do feedback. Then one bucket in histogram may be corresponded to two feedback. Then the updating of the feedback will be wrong.

Do you have a idea to solve it? I'm still thinking how to solve it. @lamxTyler

**Comment by lamxTyler** [comment]
I will take a look.

**Comment by lamxTyler** [comment]
Maybe we can merge them when we use the feedback to update the bucket count.
