### ISSUE TITLE
`performance_schema.events_statements_current` memory leak.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1037]
This memory table do not has a primary key, every time a statement executed, it adds a new record, the memory table keeps growing.
@nieyy

**Comment by nieyy** [comment]
@coocood we will handle it next week after finished current coprocessor demo works.

**Comment by nieyy** [comment]
Used `BoundedTable` to replace 'MemoryTable` for statistics tables, include:
- `EVENTS_STATEMENTS_CURRENT`
- `EVENTS_STATEMENTS_HISTORY`
- `EVENTS_STATEMENTS_HISTORY_LONG`
- `PREPARED_STATEMENTS_INSTANCES`
- `EVENTS_TRANSACTIONS_CURRENT`
- `EVENTS_TRANSACTIONS_HISTORY`
- `EVENTS_TRANSACTIONS_HISTORY_LONG`
- `EVENTS_STAGES_CURRENT`
- `EVENTS_STAGES_HISTORY`
- `EVENTS_STAGES_HISTORY_LONG`

**Comment by nieyy** [comment]
@coocood , one you confirm `sqllogicaltest` is ok, I can close this issue.
