### ISSUE TITLE
when run spark sql, it reports, "com.pingcap.tikv.exception.IgnoreUnsupportedTypeException: Unsupported type found in fields: set,year,json,time,enum"

### ISSUE THREAD

**Issue by ericgogo** [pingcap/tidb#10401]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
we run a  sql  with tiSpark,  the sql is like "select f from t" , but f is time type.  
We got the below exception.
com.pingcap.tikv.exception.IgnoreUnsupportedTypeException: Unsupported type found in fields: set,year,json,time,enum

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
the version 2.0.0

How to resolve this issue? thanks.

**Comment by zimulala** [comment]
@EricGogo 
Thanks for your feedback!
PTAL @zhexuany

**Comment by xiongjiwei** [comment]
close due to it very old version, feel free to reopen if the issue still exists
