### ISSUE TITLE
ways to trace hot region and resolve hot region

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#10420]
As I know, in tidb v2.1.4, to use pdctl and tidbctl can trace hot region

The pdctl tells several hot region-ids, how can I judge which region the hotter? Can I judge it with the key `hot_degree`? Is the value is smaller that means the region hotter?

What can I do to resolve the hot-region?

**Comment by zimulala** [comment]
@dayuanyuan1989 
Thanks for your report!
`Hot_degree` is the time that this region becomes a hotspot. The larger the value, the longer the region becomes a hotspot. `flow_bytes` is `flow_bytes` is data traffic.

**Comment by dayuanyuan1989** [comment]
@zimulala 
Thanks for your reply.
When I get the hot regions, what can I do to resolve the hot regions? What can I do is to wait pd to resolve the hot regions automatically?

**Comment by zimulala** [comment]
@dayuanyuan1989 
About hotspots writing you can scatter the hotspots, ref：https://github.com/pingcap/docs/blob/master/v2.1/FAQ.md#how-to-scatter-the-hotspots
About hotspots reading you can split region by pd-ctl（`operator add split-region`）, ref：https://pingcap.com/docs/dev/reference/tools/pd-control/

**Comment by dayuanyuan1989** [comment]
@zimulala 

Thanks for your support, I got it.
