### ISSUE TITLE
Error message is not clear

### ISSUE THREAD

**Issue by z2665** [pingcap/tidb#10449]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
When I use Snapshot. the correct statement is 
```
set @@tidb_snapshot='2019-04-29 00:00:00';
```
When I use 
```
set @@tidb_snapshot='20190429-00:00:00';
```
I can get clear error message like 
```
ERROR 1292 (22007): Incorrect datetime value: '20190429-00:00:00'
```
but if I use this statement 
```
 set @@tidb_snapshot=1557756930;
```
I get a not clear error message.
```
ERROR 1105 (HY000): snapshot is older than GC safe point 20190428-01:41:16 +0000 UTC
```
I think the error message need more clearly.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
| Release Version: v2.1.8
Git Commit Hash: 9a2d2da372947a50a02f9b9238a49f2db7ab9971
Git Branch: HEAD
UTC Build Time: 2019-04-12 07:48:47
GoVersion: go version go1.11.2 linux/amd64

**Comment by jackysp** [comment]
Please refer to https://pingcap.com/docs/dev/reference/garbage-collection/#tidb-garbage-collection-gc
