### ISSUE TITLE
JSON field should only accept JSON text

### ISSUE THREAD

**Issue by breezewish** [pingcap/tidb#10469]
## Bug Report

MySQL:

```
mysql> create table tx (col json);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into tx values ('"3"');
Query OK, 1 row affected (0.01 sec)

mysql> insert into tx values (3);
ERROR 3140 (22032): Invalid JSON text: "not a JSON text, may need CAST" at position 0 in value for column 'tx.col'.
```

TiDB:

```
mysql> create table tx (col json);
Query OK, 0 rows affected (0.13 sec)

mysql> insert into tx values ('"3"');
Query OK, 1 row affected (0.04 sec)

mysql> insert into tx values (3);
Query OK, 1 row affected (0.00 sec)
```

**Comment by nullnotnil** [comment]
Confirming this issue still exists:
```sql
drop table if exists tx;
create table tx (col json);
insert into tx values ('"3"');
insert into tx values (3);

..

mysql> insert into tx values ('"3"');
Query OK, 1 row affected (0.02 sec)

mysql> insert into tx values (3);
Query OK, 1 row affected (0.01 sec)

mysql> 
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-870-g2a8b96845
Edition: Community
Git Commit Hash: 2a8b968453520e4fcf9d6ff46c9f23b4ad23feee
Git Branch: master
UTC Build Time: 2020-07-31 08:45:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

```

**Comment by xiongjiwei** [comment]
it is not easy for us to fix, MySQL allows cast int to json, modify int column to json but not insert. tidb uses the same way to implement the type convert in `insert` and `modify column`, so we have the consistent behavior in `insert` and `modify columns`

**Comment by YangKeao** [comment]
@xiongjiwei I wonder when / how they are implicitly converted. 

As I was developing https://github.com/pingcap/tidb/pull/37579, I found in the sql `create table t(j JSON); insert into t values (CURDATE());`, `CURDATE()` is automatically converted to json string. However, it doesn't hit any breakpoint of the related cast (time/string) as json function :thinking: .

**Comment by xiongjiwei** [comment]
> @xiongjiwei I wonder when / how they are implicitly converted.
> 
> As I was developing #37579, I found in the sql `create table t(j JSON); insert into t values (CURDATE());`, `CURDATE()` is automatically converted to json string. However, it doesn't hit any breakpoint of the related cast (time/string) as json function 🤔 .

it is in `table.CastValue` function

**Comment by YangKeao** [comment]
> it is not easy for us to fix, MySQL allows cast int to json, modify int column to json but not insert. tidb uses the same way to implement the type convert in insert and modify column, so we have the consistent behavior in insert and modify columns

@xiongjiwei So you mean, implicitly cast is the expected behavior of TiDB? (The former example also has the same problem: `create table t(j JSON); insert into t values (CURDATE());` will cause error in mysql: `Invalid JSON text: "not a JSON text, may need CAST"`, but in https://github.com/pingcap/tidb/pull/37579 it will be automatically casted to json date.

**Comment by xiongjiwei** [comment]
@YangKeao 
> So you mean, implicitly cast is the expected behavior of TiDB

Yes, I prefer it is expected

**Comment by YangKeao** [comment]
> Yes, I prefer it is expected

Good. I'll close this issue as it's expected. If anyone has more opinion on this problem, feel free to reopen it :smiley:
