### ISSUE TITLE
Incorrect GROUP BY for JSON values

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#10467]
## Bug Report

```sql
create table tx2 (col json);
insert into tx2 values (json_array(3.0));
insert into tx2 values (json_array(3));
select col, count(1) from tx2 group by col;
```

MySQL:

```
mysql> create table tx2 (col json);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into tx2 values (json_array(3.0));
Query OK, 1 row affected (0.00 sec)

mysql> insert into tx2 values (json_array(3));
Query OK, 1 row affected (0.00 sec)

mysql> select col, count(1) from tx2 group by col;
+-------+----------+
| col   | count(1) |
+-------+----------+
| [3.0] |        2 |
+-------+----------+
1 row in set (0.00 sec)
```

TiDB:

```
mysql> create table tx2 (col json);
Query OK, 0 rows affected (0.13 sec)

mysql> insert into tx2 values (json_array(3.0));
Query OK, 1 row affected (0.02 sec)

mysql> insert into tx2 values (json_array(3));
Query OK, 1 row affected (0.01 sec)

mysql> select col, count(1) from tx2 group by col;
+------+----------+
| col  | count(1) |
+------+----------+
| [3]  |        1 |
| [3]  |        1 |
+------+----------+
2 rows in set (0.01 sec)
```

This simply indicates that generating the group key by using serialized value is incorrect. For JSON values, it is very clear that different memory / serialized values are treated as the same group.

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 300

## Mentor
 * @qw4990

**Comment by nullnotnil** [comment]
Confirming this issue still exists in master:
```sql
drop table if exists tx2;
create table tx2 (col json);
insert into tx2 values (json_array(3.0));
insert into tx2 values (json_array(3));
select col, count(1) from tx2 group by col;

..

mysql> select col, count(1) from tx2 group by col;
+-----+----------+
| col | count(1) |
+-----+----------+
| [3] |        1 |
| [3] |        1 |
+-----+----------+
2 rows in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-750-g8a661044c
Edition: Community
Git Commit Hash: 8a661044cedf8daad1de4fbf79a390962b6f6c3b
Git Branch: master
UTC Build Time: 2020-07-10 10:52:37
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
I think the best way to fix this is to add the JSON type of decimal (see: https://github.com/pingcap/tidb/issues/9988 ).

There was a proposed PR for this which used float64 to compare, but that produces inaccurate results for some cases. If when grouping JSON values decimal is used, it should be safe for all cases.

**Comment by morgo** [comment]
Re-opening for TiKV investigation.

**Comment by XuHuaiyu** [comment]
What does `for TiKV investigation` mean?

**Comment by XuHuaiyu** [comment]
If there is any development task that needs to be done,
I think we can create a new issue for it but not keep the `bug` issue opened.

**Comment by morgo** [comment]
Sounds good to me. I will reclose.

**Comment by breeswish** [comment]
> If there is any development task that needs to be done,
> I think we can create a new issue for it but not keep the `bug` issue opened.

I think while this PR is closing a bug, it opens another one, due to not identical implementations between TiDB and TiKV. The fail case could be constructed. This might not be considered as a complete fix.
