### ISSUE TITLE
Incorrect result / plan for UNSIGNED primary key

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#10465]
## Bug Report

```sql
set sql_mode = '';
create table tx (id bigint unsigned key);
insert into tx values (9223372036854775808);
insert into tx values (5);
select count(1), id from tx where id > 1 order by id;
```

MySQL:

```
+----------+----+
| count(1) | id |
+----------+----+
|        2 |  5 |
+----------+----+
1 row in set (0.00 sec)
```

TiDB:

```
mysql> select count(1), id from tx where id > 1 order by id;
+----------+---------------------+
| count(1) | id                  |
+----------+---------------------+
|        2 | 9223372036854775808 |
+----------+---------------------+
1 row in set (0.01 sec)

mysql> explain select count(1), id from tx where id > 1 order by id;
+--------------------------+---------+------+----------------------------------------------------------+
| id                       | count   | task | operator info                                            |
+--------------------------+---------+------+----------------------------------------------------------+
| Sort_6                   | 1.00    | root | test.tx.id:asc                                           |
| └─StreamAgg_20           | 1.00    | root | funcs:count(col_0), firstrow(col_1)                      |
|   └─TableReader_21       | 1.00    | root | data:StreamAgg_12                                        |
|     └─StreamAgg_12       | 1.00    | cop  | funcs:count(1), firstrow(test.tx.id)                     |
|       └─TableScan_19     | 3333.33 | cop  | table:tx, range:(1,+inf], keep order:false, stats:pseudo |
+--------------------------+---------+------+----------------------------------------------------------+
5 rows in set (0.00 sec)
```

Notice that stream agg must NOT be used in this case, because we are not scanning data in a memory comparable order for UNSIGNED primary key.

**Comment by shenli** [comment]
cc @zz-jason @winoros

**Comment by zz-jason** [comment]
We've split the range for unsigned int64 into two parts:
* one part for those whose most significant bit is 1, which is the unsigned ranges in `executor.splitRanges()`
* another part for those whose most significant bit is 0, which is the signed ranges in `executor.splitRanges()`

I think the root cause for this issue is the keep order is `false` in `TableScan_19`

**Comment by zz-jason** [comment]
If the keep order is true, we can produce the right result:
```sql
TiDB(root@127.0.0.1:test) > select * from t where a > 1 order by a;
+---------------------+
| a                   |
+---------------------+
|                   5 |
| 9223372036854775807 |
| 9223372036854775808 |
| 9223372036854775809 |
+---------------------+
4 rows in set (0.00 sec)

TiDB(root@127.0.0.1:test) > desc select * from t where a > 1 order by a;
+--------------------+---------+------+--------------------------------------------------------+
| id                 | count   | task | operator info                                          |
+--------------------+---------+------+--------------------------------------------------------+
| TableReader_12     | 3333.33 | root | data:TableScan_11                                      |
| └─TableScan_11     | 3333.33 | cop  | table:t, range:(1,+inf], keep order:true, stats:pseudo |
+--------------------+---------+------+--------------------------------------------------------+
2 rows in set (0.00 sec)
```

In your cases, the `count()` result is 2, which means that 9223372036854775808 is also counted into the result, because it satisfies `id > 1`. The result is not compatible with MySQL is caused by the unordered cop tasks I think.

**Comment by breeswish** [comment]
Yes, I mean, I think the character that unsigned PK is not memory comparable is the root cause of these series issues. Suppose that unsigned PK is simply stored using big endian which is memory comparable, then you just don't need "split the range for unsigned int64 into two parts", and don't need "keep order is true". Everything will be just correct and simple, without any hacks.

**Comment by breeswish** [comment]
Additionally notice that due to this encoding, the following of two will never BOTH be true:
- Ranges in the request are sent in order (i.e. `range[0].start < range[0].end <= range[1].start < range[1].end`).
- The scanned data are ordered.

**Comment by zz-jason** [comment]
> Yes, I mean, I think the character that unsigned PK is not memory comparable is the root cause of these series issues. Suppose that unsigned PK is simply stored using big endian which is memory comparable, then you just don't need "split the range for unsigned int64 into two parts", and don't need "keep order is true". Everything will be just correct and simple, without any hacks.

Yeah, personally I also think this is a cleaner way, but it involves a lot of changes.

But we still can make it work right, on the current encoding rules.

**Comment by zz-jason** [comment]
> and don't need "keep order is true"

No we should keep order

**Comment by breeswish** [comment]
> But we still can make it work right, on the current encoding rules.

Yes. My concern is just it looks to be a very complex problem and is very difficult to make it right everywhere following current encoding rules. We already have this issue and other similar issues, and undoubtedly there will be future issues I think :) Anyway it's up to TiDB to decide how to fix it. I simply file this issue as a case that current logic is problematic some where.

**Comment by zz-jason** [comment]
> > But we still can make it work right, on the current encoding rules.
> 
> Yes. My concern is just it looks to be a very complex problem and is very difficult to make it right everywhere following current encoding rules. We already have this issue and other similar issues, and undoubtedly there will be future issues I think :) Anyway it's up to TiDB to decide how to fix it. I simply file this issue as a case that current logic is problematic some where.

Agree, we've already met a lot of issues with unsigned primary key. For the long term plan, I think we should have a different encoding for unsigned columns. But for 3.0, it's too late to do the refactor.

I think we'd better to add test cases for unsigned int as many as possible, fix them under the current encoding rule. These tests can also be used when we need to test the refactored encoding in the future.

**Comment by zz-jason** [comment]
after discussing with @winoros and compared the behavior, this is not a bug.

**Comment by winoros** [comment]
@breeswish 
In the standard SQL execution, the execution order of a simple SQL should be
```
FROM clause
GROUP BY clause
HAVING clause
SELECT clause
ORDER BY clause
LIMIT clause
```
Aggregate happens earlier than ORDER BY && LIMIT. The inner execution logic don't need to always satisfy the outer order property.
The order you got is by accident with MySQL's execution logic. If you you use `DESC` in MySQL. It still returns `2`.

**Comment by winoros** [comment]
And for `Notice that stream agg must NOT be used in this case, because we are not scanning data in a memory comparable order for UNSIGNED primary key.`
The order information only exists between each group. Since there's no `GROUP BY` clause, stream aggregate don't need to consider any order. Aggregate don't permit any order information inside one group.
