### ISSUE TITLE
DDL too slowly

### ISSUE THREAD

**Issue by wonderful1984** [pingcap/tidb#10473]
## Performance Questions

- What version of TiDB are you using?
Release Version:   3.0.0-beta.1
Git Commit Hash:   26e2a854879d729896aa6a22408f1ae65f54cd71
Git Commit Branch: master
UTC Build Time:    2019-05-13 05:27:42
Rust Version:      rustc 1.36.0-nightly (e305df184 2019-04-24)

- environment
1.single machine（128G mem，E5-2690 v2，PCIe SSD，Centos 7.2）
2.1 pd, 1 tidb, 3 tikv

- What's the observed and your expected performance respectively?
DDL too slowly

- For a specific slow SQL query, please provide the following information:
using sysbench 1.0.6
prepare stage
sysbench /usr/share/sysbench/oltp_read_write.lua --tables=20 --table-size=1000000 --threads=20 --max-requests=100000 --db-driver=mysql --mysql-db=sbtest  --mysql-user=sbtest --mysql-password=sbtest --mysql-socket=/tmp/tidb10080.sock --report-interval=10 prepare

+------+--------+-----------+--------+---------+-------+-------+----------------------------------+
| Id   | User   | Host      | db     | Command | Time  | State | Info                             |
+------+--------+-----------+--------+---------+-------+-------+----------------------------------+
|    6 | sbtest | localhost | sbtest | Query   |  3377 | 2     | CREATE INDEX k_16 ON sbtest16(k) |
|    2 | sbtest | localhost | sbtest | Query   | 27024 | 2     | CREATE INDEX k_12 ON sbtest12(k) |
|    5 | sbtest | localhost | sbtest | Query   | 32656 | 2     | CREATE INDEX k_11 ON sbtest11(k) |
|   11 | sbtest | localhost | sbtest | Query   | 43311 | 2     | CREATE INDEX k_20 ON sbtest20(k) |
|   10 | sbtest | localhost | sbtest | Query   | 38649 | 2     | CREATE INDEX k_18 ON sbtest18(k) |
|    3 | sbtest | localhost | sbtest | Query   | 21142 | 2     | CREATE INDEX k_13 ON sbtest13(k) |
|    4 | sbtest | localhost | sbtest | Query   | 47911 | 2     | CREATE INDEX k_15 ON sbtest15(k) |
|    9 | sbtest | localhost | sbtest | Query   | 49849 | 2     | CREATE INDEX k_19 ON sbtest19(k) |
|    7 | sbtest | localhost | sbtest | Query   |  9120 | 2     | CREATE INDEX k_17 ON sbtest17(k) |
|    8 | sbtest | localhost | sbtest | Query   | 15343 | 2     | CREATE INDEX k_14 ON sbtest14(k) |

 
  
[2019/05/15 10:55:24.172 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391232962428930"] [takes=4.453s]
[2019/05/15 10:55:24.553 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391232962428930"] [takes=4.828s]
[2019/05/15 10:55:26.263 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391232962428930"] [takes=6.544s]
[2019/05/15 10:55:29.992 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391234679472130"] [takes=3.698s]
[2019/05/15 10:55:30.772 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391234679472130"] [takes=4.478s]
[2019/05/15 10:55:32.584 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391234679472130"] [takes=6.29s]
[2019/05/15 10:55:35.678 +08:00] [WARN] [process.rs:204] ["[region 220] scheduler handle command: prewrite, ts: 408391234679472130"] [takes=3.09s]

last_tikv.toml

`log-level = "info"
log-file = "/apps/logs/tidb/tikv20160.log"
log-rotation-timespan = "1d"
panic-when-unexpected-key-or-data = false
[readpool.storage]
high-concurrency = 4
normal-concurrency = 4
low-concurrency = 4
max-tasks-per-worker-high = 2000
max-tasks-per-worker-normal = 2000
max-tasks-per-worker-low = 2000
stack-size = "10MB"

[readpool.coprocessor]
high-concurrency = 32
normal-concurrency = 32
low-concurrency = 32
max-tasks-per-worker-high = 2000
max-tasks-per-worker-normal = 2000
max-tasks-per-worker-low = 2000
stack-size = "10MB"

[server]
addr = "127.0.0.1:20160"
advertise-addr = ""
status-addr = "127.0.0.1:20180"
status-thread-pool-size = 1
grpc-compression-type = "none"
grpc-concurrency = 8
grpc-concurrent-stream = 1024
grpc-raft-conn-num = 24
grpc-stream-initial-window-size = "2MB"
grpc-keepalive-time = "10s"
grpc-keepalive-timeout = "3s"
concurrent-send-snap-limit = 32
concurrent-recv-snap-limit = 32
end-point-recursion-limit = 1000
end-point-stream-channel-size = 8
end-point-batch-row-limit = 64
end-point-stream-batch-row-limit = 128
end-point-enable-batch-if-possible = true
end-point-request-max-handle-duration = "1m"
snap-max-write-bytes-per-sec = "100MB"
snap-max-total-size = "0KB"
stats-concurrency = 1
heavy-load-threshold = 300
heavy-load-wait-duration = "1ms"

[server.labels]

[storage]
data-dir = "/apps/dbdat/tidb_data2379/tikv20160"
gc-ratio-threshold = 1.1
max-key-size = 4096
scheduler-notify-capacity = 10240
scheduler-concurrency = 2048000
scheduler-worker-pool-size = 8
scheduler-pending-write-threshold = "100MB"

[storage.block-cache]
shared = true
num-shard-bits = 16
strict-capacity-limit = false
high-pri-pool-ratio = 0.0

[pd]
endpoints = ["127.0.0.1:2379"]

[metric]
interval = "15s"
address = ""
job = "tikv"

[raftstore]
sync-log = true
prevote = true
raftdb-path = ""
capacity = "0KB"
raft-base-tick-interval = "1s"
raft-heartbeat-ticks = 2
raft-election-timeout-ticks = 10
raft-min-election-timeout-ticks = 0
raft-max-election-timeout-ticks = 0
raft-max-size-per-msg = "1MB"
raft-max-inflight-msgs = 256
raft-entry-max-size = "8MB"
raft-log-gc-tick-interval = "10s"
raft-log-gc-threshold = 50
raft-log-gc-count-limit = 73728
raft-log-gc-size-limit = "72MB"
raft-entry-cache-life-time = "30s"
raft-reject-transfer-leader-duration = "3s"
split-region-check-tick-interval = "10s"
region-split-check-diff = "32MB"
region-compact-check-interval = "5m"
clean-stale-peer-delay = "10m"
region-compact-check-step = 100
region-compact-min-tombstones = 10000
region-compact-tombstones-percent = 30
pd-heartbeat-tick-interval = "1m"
pd-store-heartbeat-tick-interval = "10s"
snap-mgr-gc-tick-interval = "1m"
snap-gc-timeout = "4h"
lock-cf-compact-interval = "10m"
lock-cf-compact-bytes-threshold = "256MB"
notify-capacity = 40960
messages-per-tick = 4096
max-peer-down-duration = "5m"
max-leader-missing-duration = "2h"
abnormal-leader-missing-duration = "10m"
peer-stale-state-check-interval = "5m"
leader-transfer-max-log-lag = 10
snap-apply-batch-size = "10MB"
consistency-check-interval = "0s"
report-region-flow-interval = "1m"
raft-store-max-leader-lease = "9s"
right-derive-when-split = true
allow-remove-leader = false
merge-max-log-gap = 10
merge-check-tick-interval = "10s"
use-delete-range = false
cleanup-import-sst-interval = "10m"
local-read-batch-size = 1024
apply-max-batch-size = 1024
apply-pool-size = 2
store-max-batch-size = 1024
store-pool-size = 2
future-poll-size = 1

[coprocessor]
split-region-on-table = true
batch-split-limit = 10
region-max-size = "144MB"
region-split-size = "96MB"
region-max-keys = 1440000
region-split-keys = 960000

[rocksdb]
wal-recovery-mode = 2
wal-dir = ""
wal-ttl-seconds = 0
wal-size-limit = "0KB"
max-total-wal-size = "4GB"
max-background-jobs = 24
max-manifest-file-size = "256MB"
create-if-missing = true
max-open-files = 65535
enable-statistics = true
stats-dump-period = "10m"
compaction-readahead-size = "0KB"
info-log-max-size = "1GB"
info-log-roll-time = "0s"
info-log-keep-log-file-num = 10
info-log-dir = ""
rate-bytes-per-sec = "0KB"
rate-limiter-mode = 2
auto-tuned = false
bytes-per-sync = "1MB"
wal-bytes-per-sync = "512KB"
max-sub-compactions = 1
writable-file-max-buffer-size = "1MB"
use-direct-io-for-flush-and-compaction = false
enable-pipelined-write = true

[rocksdb.defaultcf]
block-size = "64KB"
block-cache-size = "32GB"
disable-block-cache = false
cache-index-and-filter-blocks = true
pin-l0-filter-and-index-blocks = true
use-bloom-filter = true
optimize-filters-for-hits = true
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
read-amp-bytes-per-bit = 0
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]
write-buffer-size = "256MB"
max-write-buffer-number = 8
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "1GB"
target-file-size-base = "512MB"
level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 3
dynamic-level-bytes = true
num-levels = 7
max-bytes-for-level-multiplier = 10
compaction-style = 0
disable-auto-compactions = false
soft-pending-compaction-bytes-limit = "64GB"
hard-pending-compaction-bytes-limit = "256GB"
prop-size-index-distance = 4194304
prop-keys-index-distance = 40960

[rocksdb.defaultcf.titan]
min-blob-size = 1024
blob-file-compression = "lz4"
blob-cache-size = "0KB"
min-gc-batch-size = "16MB"
max-gc-batch-size = "64MB"
discardable-ratio = 0.5
sample-ratio = 0.1
merge-small-file-threshold = "8MB"

[rocksdb.writecf]
block-size = "64KB"
block-cache-size = "19307MB"
disable-block-cache = false
cache-index-and-filter-blocks = true
pin-l0-filter-and-index-blocks = true
use-bloom-filter = true
optimize-filters-for-hits = false
whole-key-filtering = false
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
read-amp-bytes-per-bit = 0
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]
write-buffer-size = "256MB"
max-write-buffer-number = 8
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "1GB"
target-file-size-base = "512MB"
level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 3
dynamic-level-bytes = true
num-levels = 7
max-bytes-for-level-multiplier = 10
compaction-style = 0
disable-auto-compactions = false
soft-pending-compaction-bytes-limit = "64GB"
hard-pending-compaction-bytes-limit = "256GB"
prop-size-index-distance = 4194304
prop-keys-index-distance = 40960

[rocksdb.writecf.titan]
min-blob-size = 4294967296
blob-file-compression = "lz4"
blob-cache-size = "0KB"
min-gc-batch-size = "16MB"
max-gc-batch-size = "64MB"
discardable-ratio = 0.5
sample-ratio = 0.1
merge-small-file-threshold = "8MB"

[rocksdb.lockcf]
block-size = "16KB"
block-cache-size = "1GB"
disable-block-cache = false
cache-index-and-filter-blocks = true
pin-l0-filter-and-index-blocks = true
use-bloom-filter = true
optimize-filters-for-hits = false
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
read-amp-bytes-per-bit = 0
compression-per-level = ["no", "no", "no", "no", "no", "no", "no"]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "128MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 1
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 0
dynamic-level-bytes = true
num-levels = 7
max-bytes-for-level-multiplier = 10
compaction-style = 0
disable-auto-compactions = false
soft-pending-compaction-bytes-limit = "64GB"
hard-pending-compaction-bytes-limit = "256GB"
prop-size-index-distance = 4194304
prop-keys-index-distance = 40960

[rocksdb.lockcf.titan]
min-blob-size = 4294967296
blob-file-compression = "lz4"
blob-cache-size = "0KB"
min-gc-batch-size = "16MB"
max-gc-batch-size = "64MB"
discardable-ratio = 0.5
sample-ratio = 0.1
merge-small-file-threshold = "8MB"

[rocksdb.raftcf]
block-size = "16KB"
block-cache-size = "128MB"
disable-block-cache = false
cache-index-and-filter-blocks = true
pin-l0-filter-and-index-blocks = true
use-bloom-filter = true
optimize-filters-for-hits = true
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
read-amp-bytes-per-bit = 0
compression-per-level = ["no", "no", "no", "no", "no", "no", "no"]
write-buffer-size = "128MB"
max-write-buffer-number = 5
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "128MB"
target-file-size-base = "8MB"
level0-file-num-compaction-trigger = 1
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 0
dynamic-level-bytes = true
num-levels = 7
max-bytes-for-level-multiplier = 10
compaction-style = 0
disable-auto-compactions = false
soft-pending-compaction-bytes-limit = "64GB"
hard-pending-compaction-bytes-limit = "256GB"
prop-size-index-distance = 4194304
prop-keys-index-distance = 40960

[rocksdb.raftcf.titan]
min-blob-size = 4294967296
blob-file-compression = "lz4"
blob-cache-size = "0KB"
min-gc-batch-size = "16MB"
max-gc-batch-size = "64MB"
discardable-ratio = 0.5
sample-ratio = 0.1
merge-small-file-threshold = "8MB"

[rocksdb.titan]
enabled = false
dirname = ""
disable-gc = false
max-background-gc = 1

[raftdb]
wal-recovery-mode = 2
wal-dir = ""
wal-ttl-seconds = 0
wal-size-limit = "0KB"
max-total-wal-size = "4GB"
max-background-jobs = 4
max-manifest-file-size = "20MB"
create-if-missing = true
max-open-files = 40960
enable-statistics = true
stats-dump-period = "10m"
compaction-readahead-size = "0KB"
info-log-max-size = "1GB"
info-log-roll-time = "0s"
info-log-keep-log-file-num = 10
info-log-dir = ""
max-sub-compactions = 2
writable-file-max-buffer-size = "1MB"
use-direct-io-for-flush-and-compaction = false
enable-pipelined-write = true
allow-concurrent-memtable-write = false
bytes-per-sync = "1MB"
wal-bytes-per-sync = "512KB"

[raftdb.defaultcf]
block-size = "64KB"
block-cache-size = "1GB"
disable-block-cache = false
cache-index-and-filter-blocks = true
pin-l0-filter-and-index-blocks = true
use-bloom-filter = false
optimize-filters-for-hits = true
whole-key-filtering = true
bloom-filter-bits-per-key = 10
block-based-bloom-filter = false
read-amp-bytes-per-bit = 0
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]
write-buffer-size = "256MB"
max-write-buffer-number = 8
min-write-buffer-number-to-merge = 1
max-bytes-for-level-base = "1GB"
target-file-size-base = "512MB"
level0-file-num-compaction-trigger = 4
level0-slowdown-writes-trigger = 20
level0-stop-writes-trigger = 36
max-compaction-bytes = "2GB"
compaction-pri = 0
dynamic-level-bytes = true
num-levels = 7
max-bytes-for-level-multiplier = 10
compaction-style = 0
disable-auto-compactions = false
soft-pending-compaction-bytes-limit = "64GB"
hard-pending-compaction-bytes-limit = "256GB"
prop-size-index-distance = 4194304
prop-keys-index-distance = 40960

[raftdb.defaultcf.titan]
min-blob-size = 1024
blob-file-compression = "lz4"
blob-cache-size = "0KB"
min-gc-batch-size = "16MB"
max-gc-batch-size = "64MB"
discardable-ratio = 0.5
sample-ratio = 0.1
merge-small-file-threshold = "8MB"

[security]
ca-path = ""
cert-path = ""
key-path = ""
cipher-file = ""

[import]
import-dir = "/tmp/tikv/import"
num-threads = 8
num-import-jobs = 8
num-import-sst-jobs = 2
max-prepare-duration = "5m"
region-split-size = "512MB"
stream-channel-window = 128
max-open-engines = 8
upload-speed-limit = "512MB"
min-available-ratio = 0.05`

**Comment by shenli** [comment]
@wonderful1984 Thanks  for your feedback!
Have read the FAQ?

**Comment by wonderful1984** [comment]
This is unusual.

1 million rows of table，it takes 13000+ seconds

>select count(*) from sbtest11;
+----------+
| count(*) |
+----------+
|  1000000 |
+----------+
1 row in set (0.81 sec)

*************************** 1. row ***************************
   SCHEMA_VER: 100
     OWNER_ID: 0209a5b4-efe1-4d02-9110-8d9cdfc31a52
OWNER_ADDRESS: :10080
 RUNNING_JOBS: ID:85, Type:add index, State:running, SchemaState:write reorganization, SchemaID:39, TableID:83, RowCount:585728, ArgLen:0, start time: 2019-05-15 02:00:15.887 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:408397479500054529
      SELF_ID: 0209a5b4-efe1-4d02-9110-8d9cdfc31a52
        QUERY: CREATE INDEX k_11 ON sbtest11(k)

>show processlist;             
+------+--------+-----------+--------+---------+-------+-------+----------------------------------+
| Id   | User   | Host      | db     | Command | Time  | State | Info                             |
+------+--------+-----------+--------+---------+-------+-------+----------------------------------+
|    2 | sbtest | localhost | sbtest | Query   | 57047 | 2     | CREATE INDEX k_12 ON sbtest12(k) |
|   84 | root   | localhost | sbtest | Query   |     0 | 2     | show processlist                 |
|    5 | sbtest | localhost | sbtest | Query   | 62679 | 2     | CREATE INDEX k_11 ON sbtest11(k) |
|    8 | sbtest | localhost | sbtest | Query   | 45366 | 2     | CREATE INDEX k_14 ON sbtest14(k) |
|    3 | sbtest | localhost | sbtest | Query   | 51165 | 2     | CREATE INDEX k_13 ON sbtest13(k) |
|    6 | sbtest | localhost | sbtest | Query   | 33400 | 2     | CREATE INDEX k_16 ON sbtest16(k) |
|    7 | sbtest | localhost | sbtest | Query   | 39143 | 2     | CREATE INDEX k_17 ON sbtest17(k) |
+------+--------+-----------+--------+---------+-------+-------+----------------------------------+


   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                      
124036 apps      20   0 13.739g 6.950g  12788 R 99.9  5.5 233:49.18 sched-worker-po                                                                                                              
124031 apps      20   0 13.739g 6.950g  12788 R 99.7  5.5 240:45.51 sched-worker-po                                                                                                              
124037 apps      20   0 13.739g 6.950g  12788 S 12.9  5.5 260:11.15 sched-worker-po                                                                                                              
124030 apps      20   0 13.739g 6.950g  12788 S 12.3  5.5 221:16.71 sched-worker-po                                                                                                              
124060 apps      20   0 13.739g 6.950g  12788 S  0.7  5.5   5:24.32 raftstore-5-0                                                                                                                
124083 apps      20   0 13.739g 6.950g  12788 S  0.7  5.5   2:39.90 transport-stats 

Samples: 95K of event 'cycles', Event count (approx.): 60542821916                                                                                                                                
Overhead  Shared Object       Symbol                                                                                                                                                              
  44.01%  [kernel]            [k] copy_user_enhanced_fast_string
  40.93%  tikv-server         [.] rocksdb::crc32c::crc32c_3way
   7.41%  [kernel]            [k] put_page
   3.01%  [kernel]            [k] __find_get_page

**Comment by wonderful1984** [comment]
start time: 2019-05-15 02:00:15.887 

1 million rows，it takes 62679 second......

This is unusual.

**Comment by wonderful1984** [comment]
Only indexing is slow

**Comment by shenli** [comment]
Adding Index need to backfill the data. It could be slow. Please read our document.
