### ISSUE TITLE
When will service discovery of tidb and tikv be supported ?

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb#10489]
## General Question

Now，when pd cluster changed(scale out、scale down or migrate), we need to rebuild pd、tikv、tidb cluster  in sequence. 

If tikv and tidb support service discovery， we need do nothing when pd cluster changed.

When will service discovery of tidb and tikv be supported ?

**Comment by AlexNewTao** [comment]
I also have the same question about service discovery.

**Comment by zimulala** [comment]
@XSHui 
Thanks for your report!
What your means of `rebuild` PD 、TiKV、TiDB? I think if PD cluster changed(scale out、scale down or migrate), it doesn't need to restart TiDB and TiKV.

**Comment by XSHui** [comment]
I means when add a new pd node or delete an old node from pd cluster, we need to do rolling upgrade the entire cluster, which includs jobs like rebuild start.sh、 config and so on.


Reference ：

https://pingcap.com/docs-cn/dev/how-to/scale/with-ansible/

- 扩容 PD 节点
- 缩容 PD 节点


@zimulala

**Comment by jebter** [comment]
Please refer: https://docs.pingcap.com/tidb/stable/production-deployment-using-tiup. I will close this issue. If there are any updates you can reopen it.
