### ISSUE TITLE
create 1024 sysbench tables with 256 threads could fail

### ISSUE THREAD

**Issue by hicqu** [pingcap/tidb#10490]
To create 1024 standard sysbench tables (16 records per table) could fail. The command is
```bash
$ sysbench oltp_read_write --mysql-host=172.16.30.65 --mysql-port=30445 --mysql-user=root --mysql-db=sbtest0 --tables=1024 --table-size=16 --db-driver=mysql --threads=256 --percentile=99 prepare
```
Got some error log when run the command:
```
FATAL: mysql_drv_query() returned error 1105 (Information schema is changed.) for query 'CREATE TABLE sbtest78(
  id INTEGER NOT NULL AUTO_INCREMENT,
  k INTEGER DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  PRIMARY KEY (id)
) /*! ENGINE = innodb */ '
```
After the command returns, I just find `351` tables in `sbtest0` with `show tables`.

I guess some DDLs failed because infomation schema is changed. So how about enlarge the retry backoff time for DDL?

**Comment by ljluestc** [comment]
`sysbench oltp_read_write --mysql-host=172.16.30.65 --mysql-port=30445 --mysql-user=root --mysql-db=sbtest0 --tables=1024 --table-size=16 --db-driver=mysql --threads=256 --percentile=99 --mysql-ignore-errors=all --mysql-ssl=off --mysql-use-ssl=off --oltp-retry-backoff=5 --oltp-retry-count=10 prepare
`
In the above command, the --oltp-retry-backoff option sets the time in seconds to wait between retries for DDL statements, and --oltp-retry-count sets the maximum number of times to retry a failed DDL statement. The values can be adjusted based on your specific requirements.
