### ISSUE TITLE
panic_hook

### ISSUE THREAD

**Issue by kxiaoba** [pingcap/tidb#10507]
ERRO panic_hook.rs:104: thread 'raftstore-9' panicked '[region 173] 5059536 unexpected raft log index: last_index 5 < applied_index 243077' at "src/raftstore/store/peer_storage.rs:470"

how to reslove it?

**Comment by breeswish** [comment]
@overvenus @hicqu PTAL

**Comment by shenli** [comment]
@kxiaoba Please keep the issue template and provide more information.

**Comment by siddontang** [comment]
do you set `sync-log` to false?

which version do you use?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
