### ISSUE TITLE
Support " DISABLE KEYS" in alter table statement

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1051]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.5.3
2. What operating system and processor architecture are you using (`go env`)?
   Linux
3. What did you do?
   Run SQL: /*!40000 ALTER TABLE `app_versions` DISABLE KEYS */
4. What did you expect to see?
   Run sucess
5. What did you see instead?
   error: line 1 column 28 near "DISABLE"^[[0m
   2016/04/05 12:13:08 conn.go:241: ^[[0;31m[error] dispatch error line 1 column 28 near "DISABLE"

**Comment by shenli** [comment]
See: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html
For MyISAM tables, key updating can be controlled explicitly. Use ALTER TABLE ... DISABLE KEYS to tell MySQL to stop updating nonunique indexes. Then use ALTER TABLE ... ENABLE KEYS to re-create missing indexes. MyISAM does this with a special algorithm that is much faster than inserting keys one by one, so disabling keys before performing bulk insert operations should give a considerable speedup. Using ALTER TABLE ... DISABLE KEYS requires the INDEX privilege in addition to the privileges mentioned earlier.

**Comment by shenli** [comment]
I use --skip-disable-keys option in mysqldump to avoid create disable/enable keys statement.

**Comment by holys** [comment]
@shenli  It seems we can close it now.

**Comment by shenli** [comment]
OK
