### ISSUE TITLE
how do I perform a performance to exhasut the system resources

### ISSUE THREAD

**Issue by dengwfxx** [pingcap/tidb#10531]
## Performance Questions

- What version of TiDB are you using?
**2.1.3**

- What's the observed and your expected performance respectively?
**I want to see high system resources usage.**

- For a general performance question, e.g. the benchmark result you got by yourself is not expected, please provide the following information:
    - Your cluster's topology architecture.
      **I have two instance of PD and two instance of tidb, they shared two node, one instance in each node.
      I have three tikv instance, one instance in each node.
     All node has the same configuration : Intel 2650v4*2 / 256G Memory / Intel P3650 2T SSD /10000Base fiber**

    - A simple description of you workload.
   It's just batch insert. The table ddl like this:
   create tbl_1 {
	id  varchar(32) index not unique,
	pos varchar(64) index not unique,
	time datetime index not unique,
	type byte,
	remarh varchar(128),
  }
 Multi thread batch insert records into the table while the batch size is 1000 record.While benchmarking, there was enough room for system resource usage of TiDB and TiKV like follows:
(CPU usage was around 20% and IO utilization was under 20% and Network was 200-300Mbps). 
 Like [#3595](https://github.com/tikv/tikv/issues/3595)， I saw thread  "raft store" and "async apply"   has  the CPU usage  close to 100%, so I followed the comment and added one SSD for eatch tikv node, then doubled tikv instance, resulting each node has two tikv instance while each instace has one SSD. But it  dosn't work. The system resource usage is still low, and the performance is same.(Even same as SAS disk)

**Comment by shenli** [comment]
Please try the 3.0.0-rc.1 or the latest master. The single thread bottle-neck is eliminated in 3.0. 
 See the release notes: https://github.com/pingcap/docs/blob/master/releases/3.0beta.md#tikv

>  I saw thread "raft store" and "async apply" has the CPU usage of these threads close to 100%

**Comment by dengwfxx** [comment]
> Please try the 3.0.0-rc.1 or the latest master. The single thread bottle-neck is eliminated in 3.0.
> See the release notes: https://github.com/pingcap/docs/blob/master/releases/3.0beta.md#tikv
> 
> > I saw thread "raft store" and "async apply" has the CPU usage of these threads close to 100%

Thanks， I'll try。And Is't there any suggestion why SAS disk has same performance like SSD?

**Comment by shenli** [comment]
The bottleneck is raftstore and apply worker thread, not disk IO.

**Comment by dengwfxx** [comment]
> The bottleneck is raftstore and apply worker thread, not disk IO.

Today， I try the 3.0.0-rc.1 version, but there are some errors when installing. The hint is no support for EPOLLEXCLUSIVE option, but this feature is only available when kernal version>4.5.
Is it mean I have to update Centos7.5 kernel to > 4.5 ?
Thanks!

**Comment by siddontang** [comment]
yes, but as far as I know, you only need to upgrade a version of CentOS 7.3, but 7.5 is fine.

**Comment by dengwfxx** [comment]
> yes, but as far as I know, you only need to upgrade a version of CentOS 7.3, but 7.5 is fine.

Sorry. The monitor server is Centos7.2. I'll upgrade to 7.5.

**Comment by dengwfxx** [comment]
I tried the 3.0.0-rc.1 versions and there are more problem:

1. As 2.1.7 version,  the system resource usages are still low, despite the IO utilization was up to 40%, CPU usage was around 20% and Network was 200-300Mbps

2. I sample the insert rate every 10 seconds, occasionally the rate became zero. This problem never happened when using 2.1.7 verison;

3. when using nmon watching the CPU usage, there are some CPU wait time occasionally, also, never happened when using 2.1.7 version.

**Comment by shenli** [comment]
@dengwfxx We just released 3.0.0. Could you try this release? It fixes many issue in rc1.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
