### ISSUE TITLE
`IGNORE NULLS` in window function not implemented but no error thrown

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10556]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
SELECT FIRST_VALUE(i) IGNORE NULLS OVER () FROM t1;
```

2. What did you expect to see?

Error thrown, `This version of TiDB hasn't supported IGNORE NULLS currently`.

3. What did you see instead?

executes successfully.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by SunRunAway** [comment]
The expected error should be similar with mysql output.
```
ERROR 1235 (42000): This version of MySQL doesn't yet support 'IGNORE NULLS'
```

**Comment by SunRunAway** [comment]
Ping @wty4427300 , any update?

**Comment by lzmhhh123** [comment]
@SunRunAway This version of `MySQL` or `TiDB`? May `TiDB` is better?
