### ISSUE TITLE
TiKV_coprocessor_request_error when i upgrade to v3.0.0-rc.1

### ISSUE THREAD

**Issue by xujingbin** [pingcap/tidb#10562]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

upgrade from v2.1.0 to v3.0.0-rc.1 this morning,then all tikv nodes alert TiKV_coprocessor_request_error:

alertname="TiKV_coprocessor_request_error" cluster="test-cluster" env="test-cluster" expr="increase(tikv_coprocessor_request_error{reason!="lock"}[10m]) > 100" instance="10.3.0.182:20180" job="tikv" level="warning" monitor="prometheus" reason="not_leader"
--

 Grafana doesn't have the picture
![image](https://user-images.githubusercontent.com/22829724/58141473-16157180-7c76-11e9-834e-46db9546b120.png)

![image](https://user-images.githubusercontent.com/22829724/58141480-1ada2580-7c76-11e9-9ca1-e183aa9d7e0f.png)

**Comment by BusyJay** [comment]
It seems that some region doesn't work properly. Can you see which region reports NotLeader error in tidb logs? And what logs says about the region in TiKV side?

**Comment by xujingbin** [comment]
log/tikv.log:[2019/05/22 13:24:21.719 +08:00] [ERROR] [endpoint.rs:452] [error-response] [err="region Error { message: \"peer is not leader\", not_leader: Some(NotLeader { region_id: 4268, leader: None, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }), region_not_found: None, key_not_in_region: None, epoch_not_match: None, server_is_busy: None, stale_command: None, store_not_match: None, raft_entry_too_large: None, unknown_fields: UnknownFields { fields: None }, cached_size: CachedSize { size: 0 } }"]

There  no further alarm, but grafana still showed that it was abnormal

**Comment by BusyJay** [comment]
Do you mean that the Granada still has no data points in the leader panel?

**Comment by xujingbin** [comment]
yes

**Comment by nullnotnil** [comment]
I took a look at reproducing this today against master. There is no included alert named TiKV_coprocessor_request_error, but the graph for TiKV coprocessor request errors will fill with data if the cluster is under load (I generated a tpcc benchmark w/10 warehouses, 32 threads).

It is possible that "lock" was renamed to "meet_lock", but based on the definition that should not be an issue:

![image](https://user-images.githubusercontent.com/67764674/87493098-49992500-c609-11ea-9686-bc7e741863cb.png)
