### ISSUE TITLE
question about JSON performance

### ISSUE THREAD

**Issue by Still4** [pingcap/tidb#10560]
最近我们遇到一个数据，包含上百个字段，需要进行求和操作的字段目前还不确定

所以我想了解下如果存储为JSON，存储为字符串以JSON去解析，所需的索引会单独提出字段来存储，类似
CREATE TABLE `test` (
  `id` varchar(25) NOT NULL,
  `date` date NOT NULL,
  `full_data` blob DEFAULT NULL,
  PRIMARY KEY (`id`,`date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

那么在对其中某个字段求和的时候，性能开销会很大吗，这样后续需求变更的时候我们改动就不会很大

比如统计10万行数据，大概会跟100万行的普通数据时间近似，或者更高，或者更低？

谢谢

**Comment by winoros** [comment]
You mean you want to do something like `sum(json_extract())`

**Comment by Still4** [comment]
> You mean you want to do something like `sum(json_extract())`
yes, that's correct, as I know some Java libs will use a lot of cpu and memory when decoding some big json, but I don't know about golang, so I need help

**Comment by winoros** [comment]
@Still4 For now, we don't recommend you to do it. We haven't bench the performance of JSON seriously. So you'd better avoid heavy computation on JSON column.

**Comment by Still4** [comment]
@winoros OK I see, thanks a lot.
