### ISSUE TITLE
mydumper:24017

### ISSUE THREAD

**Issue by simpson9527** [pingcap/tidb#10565]
** (mydumper:24017): CRITICAL **: 14:35:54.810: Couldn't acquire global lock, snapshots will not be consistent: FLUSH TABLES WITH READ LOCK is not supported.  Please use @@tidb_snapshot

mydumper cmd is：mydumper -h 127.0.0.1 -P 4000 -u root -t 8 -F 64  -B database -c -o /data

**Comment by morgo** [comment]
This error message is generated because mydumper attempted to execute `FLUSH TABLES WITH READ LOCK` on a TiDB server (the command is not supported).

Please use the [mydumper](https://pingcap.com/docs/dev/reference/tools/mydumper/) bundled with TiDB tools. Support for TiDB has [merged](https://github.com/maxbube/mydumper/pull/155) into upstream mydumper, and will be available starting with the next release.

**Comment by simpson9527** [comment]
That mydumper what I'm using is bundled with TiDB tools.so i comment this problem.

**Comment by simpson9527** [comment]
the mydumper

**Comment by simpson9527** [comment]
# ll
total 24380
-rwxr-xr-x 1 zus zus 12759264 Jan  7 11:48 mydumper
-rwxr-xr-x 1 zus zus 12201592 Jan  7 11:48 myloader

[root@**** /data/deploy/tools/mydumper-linux-amd64/bin] 
# pwd
/data/deploy/tools/mydumper-linux-amd64/bin

**Comment by simpson9527** [comment]
ok,i will try again

**Comment by morgo** [comment]
@simpson9527 Just checking in. How did it go? :-)

**Comment by simpson9527** [comment]
everything goes well

**Comment by simpson9527** [comment]
i had some problems when i use mydumper backup mysql data,shall we make some changes for mydumper.
here is the situation: when i dump a table,the column default value is illegality,for example,the datatype date's default value is '1970-00:00 00:00:00' in mysql，but which is illegality in tidb.shall we automatic transfer the default value from mysql to tidb when dump tables.

**Comment by morgo** [comment]
> i had some problems when i use mydumper backup mysql data,shall we make some changes for mydumper.
> here is the situation: when i dump a table,the column default value is illegality,for example,the datatype date's default value is '1970-00:00 00:00:00' in mysql，but which is illegality in tidb.shall we automatic transfer the default value from mysql to tidb when dump tables.

It is now illegal by default in MySQL as well. TiDB actually behaves the same - you can remove the sql_modes `NO_ZERO_IN_DATE` (and probably `NO_ZERO_DATE`) from TiDB's configuration to make it behave the old way:
```
SET GLOBAL sql_mode='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
```

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
