### ISSUE TITLE
make test failed

### ISSUE THREAD

**Issue by leobuzhi** [pingcap/tidb#10577]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
make test

2. What did you expect to see?

pass

3. What did you see instead?

FAIL: fail_test.go:46: testSuite.SetUpSuite

fail_test.go:48:
    c.Assert(err, IsNil)
... value *net.OpError = &net.OpError{Op:"listen", Net:"unix", Source:net.Addr(nil), Addr:(*net.UnixAddr)(0xc0001f2d00), Err:(*os.SyscallError)(0xc000168d40)} ("listen unix new_session:12379: bind: address already in use")

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
commit 3c31331f9a0c85d485b2611d97d5bb1ca2f0a548

5. more info

COMMAND     PID     FD   TYPE            DEVICE SIZE/OFF NODE NAME
rapportd    266     3u  IPv4 0xe829e7c14f2e23b      0t0  TCP *:57183 (LISTEN)
rapportd    266     4u  IPv6 0xe829e7c1340d27b      0t0  TCP *:57183 (LISTEN)
mongod      736    11u  IPv4 0xe829e7c24c14f3b      0t0  TCP localhost:27017 (LISTEN)
Code\x20H  3651    39u  IPv4 0xe829e7c2469523b      0t0  TCP localhost:9032 (LISTEN)
Shadowsoc  4287    14u  IPv4 0xe829e7c2469b23b      0t0  TCP localhost:1089 (LISTEN)
Shadowsoc  4287    15u  IPv6 0xe829e7c1340e3bb      0t0  TCP localhost:1089 (LISTEN)
ss-local   4295     6u  IPv4 0xe829e7c174f28bb      0t0  TCP localhost:1086 (LISTEN)
privoxy    4300     3u  IPv4 0xe829e7c24a1a23b      0t0  TCP localhost:1087 (LISTEN)
Code\x20H  4556    38u  IPv4 0xe829e7c1831bf3b      0t0  TCP localhost:5122 (LISTEN)
Code\x20H  4835    38u  IPv4 0xe829e7c1859e23b      0t0  TCP localhost:9670 (LISTEN)
Code\x20H  9284    39u  IPv4 0xe829e7c24e42f3b      0t0  TCP localhost:58721 (LISTEN)
Code\x20H 11781    38u  IPv4 0xe829e7c294e053b      0t0  TCP localhost:17453 (LISTEN)

go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/someone/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/someone/Program/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/dm/wdc8k6f140z_0ztx0b7g3n4h0000gn/T/go-build229848719=/tmp/go-build -gno-record-gcc-switches -fno-common"

go version
go version go1.12.5 darwin/amd64

**Comment by winoros** [comment]
@leobuzhi Thanks for your reporting. Which `fail_test.go` failed? I saw that there're many `fail_test.go` in TiDB's unit test.

**Comment by leobuzhi** [comment]
> @leobuzhi Thanks for your reporting. Which `fail_test.go` failed? I saw that there're many `fail_test.go` in TiDB's unit test.

I'm sorry that I reply you so late.

In github.com/pingcap/tidb/owner

----------------------------------------------------------------------
FAIL: fail_test.go:46: testSuite.SetUpSuite

fail_test.go:48:
    c.Assert(err, IsNil)
... value *net.OpError = &net.OpError{Op:"listen", Net:"unix", Source:net.Addr(nil), Addr:(*net.UnixAddr)(0xc000226500), Err:(*os.SyscallError)(0xc00000e4a0)} ("listen unix new_session:12379: bind: address already in use")


----------------------------------------------------------------------
MISS: fail_test.go:65: testSuite.TestFailNewSession
OOPS: 0 passed, 1 FAILED, 1 MISSED
--- FAIL: TestT (0.00s)
FAIL
coverage: 3.7% of statements
FAIL	github.com/pingcap/tidb/owner	0.031s

**Comment by XuHuaiyu** [comment]
Hi
The error message is:
`"listen unix new_session:12379: bind: address already in use"`
You may check whether the port 4001 is occupied by another process.

**Comment by leobuzhi** [comment]
> Hi
> The error message is:
> `"listen unix new_session:12379: bind: address already in use"`
> You may check whether the port 4001 is occupied by another process.

1. the port 4001 is **NOT** occupied by another process.
2. why the port 4001 rather then 12379?

**Comment by XuHuaiyu** [comment]
My mistake...
Is the port 12379 occupied by another process?

**Comment by leobuzhi** [comment]
As more info on the first floor, the port 12379 is not occupied by another process.

**Comment by XuHuaiyu** [comment]
1. Can this problem be reproduced now?
2. If it can be reproduced, what's the ouput of `lsof -i:12379`

**Comment by leobuzhi** [comment]
> 1. Can this problem be reproduced now?
> 2. If it can be reproduced, what's the ouput of `lsof -i:12379`

1. Yes
2. As the picture shows
<img width="1429" alt="tidb_build_test" src="https://user-images.githubusercontent.com/10794816/58487856-ea751880-819a-11e9-8b5c-ad47268f18c0.png">

**Comment by XuHuaiyu** [comment]
You may remove the `new_session:12379` file under the `owner` directory.

**Comment by leobuzhi** [comment]
owner directory? you mean ~ ?
There is not exist new_session:12379.

**Comment by XuHuaiyu** [comment]
tidb/owner

**Comment by leobuzhi** [comment]
> tidb/owner

Thanks a lot, all tests passed.
