### ISSUE TITLE
propagate more possible props to enlarge search space

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#10579]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For an index access path, if some prefix columns of it are covered by exactly one equal conditions, that index access path can provide more than one physical properties. 

For example: index(a, b, c), the predicate is `a = x and b = y`, the physical properties that this access path can provide are:
1. (a, b, c)
2. (b, c), because a is constant
3. (c), because a and b is constant

**Describe the feature you'd like:**

Like I described in the above.

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by eurekaka** [comment]
For cases like:
```sql
create table t(a int primary key, b int, index idx_b(b));
```
if predicate is like:
```
b = xxx
```
the access path can provide these properties:
- (b), because b is constant
- (b, a), because b is non-unique, and `a` satisfies 'PKIsHandle', according to our encoding strategy, order of `a` is guaranteed as well;
