### ISSUE TITLE
the error was happen when using the  tools of xorm-cmd

### ISSUE THREAD

**Issue by fadefeng** [pingcap/tidb#10570]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Using the  tools of xorm-cmd to generate the structure of go

2. What did you expect to see?
no error

3. What did you see instead?
[Error] reverse.go:320 17:40: illegal character NUL-package test’,i guess it's the return of table info.table's ddl  is in below

`type TApp struct {
	Id                 int       `xorm:"not null pk autoincr comment('主键') INT(11)"`
	IsDeleted          int       `xorm:"not null default b'0' comment('是否已被删除') BIT(1)"`
}`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidbversion:5.7.10-TiDB-v2.0.4-1-g06a0bf5
xorm-cmd:latest

**Comment by XuHuaiyu** [comment]
Hi, @fadefeng 
Sorry that I do not really understand the problem of what you mentioned in the description. 
May you format it or describe the problem more detailed? 
And, if possible, you can try v2.1.10 to check whether the problem still exists.

**Comment by ljluestc** [comment]
```

CREATE TABLE `TApp` (
    `Id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `IsDeleted` BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否已被删除',
    PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
