### ISSUE TITLE
does tidb support arm64 architecture?

### ISSUE THREAD

**Issue by qiangcz** [pingcap/tidb#10592]
咨询下：TIDB是否支持ARM64架构的服务器？
请帮忙评估，急。。。

**Comment by XuHuaiyu** [comment]
Hi @qiangcz , thanks for your feedback.
We've tried that TiDB can run successfully on ARM, but we do not have a detailed test for whether it works well on everything.

You may test it, and feel free to let us know if you meet any problems.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
