### ISSUE TITLE
Use tidb-ansible to automatically upgrade errors

### ISSUE THREAD

**Issue by 799983050** [pingcap/tidb#10618]
Automatic upgrade to v2.1.10 using tidb-ansible 。
![图片](https://user-images.githubusercontent.com/45658355/58456166-0a361d80-8156-11e9-8258-e45fea06ea9e.png)

**Comment by tiancaiamao** [comment]
PTAL @july2993

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/issues/10610

**Comment by 799983050** [comment]
#10610  It was mentioned by my colleague.  He answered incorrectly. Automatic upgrade  Has not been able to use normally.

**Comment by liubo0127** [comment]
```
1. git clone -b v2.1.10 https://github.com/pingcap/tidb-ansible.git
2. Modify tidb-ansible according to the original configuration information(inventory.ini、conf/tikv.yml ...)
3. ansible-playbook local_prepare.yml
4. ansible-playbook rolling_update.yml
5. ansible-playbook rolling_update_monitor.yml
```
