### ISSUE TITLE
How to Use Regular Filtering Correctly

### ISSUE THREAD

**Issue by wang543635182** [pingcap/tidb#10611]
When using Syncer, the MySQL table test_00 is synchronized to TiDB, but there are tables test_v1 in the MySQL library at the same time. How to filter the test_v1 table? Thank you！

**Comment by july2993** [comment]
- you can set `ignore-table` to ignore some table, take a look at https://github.com/pingcap/tidb-enterprise-tools/blob/master/loader/config.toml
- if you want Sharding support, take a look at [DM](https://github.com/pingcap/dm)
DM supports merging the original sharded instances and tables into TiDB, but with some [restrictions](https://pingcap.com/docs/dev/reference/tools/data-migration/features/shard-merge#restrictions)

**Comment by shenli** [comment]
@wang543635182 Hope your problem is solved. I will close this issue. Feel free to reopen it if you have any more question.
