### ISSUE TITLE
Decrease  TiKV node ,but state always Offline , not the correct state Tombstone

### ISSUE THREAD

**Issue by dbhelp** [pingcap/tidb#10619]
Hi !

I want to decrease one TiKV node(total 3 TiKV nodes).
I waited about one day, the TiKV state always  “Offline”, not the correct state Tombstone.

Through pd.log from PD node , I saw the following warnings,
`2019/05/28 14:25:58.996 cluster.go:492: [warning] store id:5 address:"10.5.5.174:20160" state:Offline version:"2.1.10"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2019/05/28 14:26:58.997 cluster.go:492: [warning] store id:5 address:"10.5.5.174:20160" state:Offline version:"2.1.10"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica`

That means TiKV node has not enough space, I check TiKV nodes disk info ,the data dir just usage 3% space .
[root@tikv-03 /]# df -Th
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/sda3      xfs        50G  3.5G   47G   7% /
devtmpfs       devtmpfs   17G     0   17G   0% /dev
tmpfs          tmpfs      17G     0   17G   0% /dev/shm
tmpfs          tmpfs      17G  8.8M   17G   1% /run
tmpfs          tmpfs      17G     0   17G   0% /sys/fs/cgroup
**/dev/sda2      ext4      229G  5.2G  212G   3% /data**
/dev/sda1      xfs      1014M  153M  862M  16% /boot
tmpfs          tmpfs     3.4G     0  3.4G   0% /run/user/0

$ /home/tidb/tidb-ansible-2.1.10/resources/bin/pd-ctl -u "http://10.5.5.171:2379" -d store
{
  "count": 3,
  "stores": [
    {
      "store": {
        "id": 4,
        "address": "10.5.5.173:20160",
        "version": "2.1.10",
        "state_name": "Up"
      },
      "status": {
        "capacity": "228 GiB",
        "available": "223 GiB",
        "leader_count": 16,
        "leader_weight": 1,
        "leader_score": 992,
        "leader_size": 992,
        "region_count": 44,
        "region_weight": 1,
        "region_score": 3929,
        "region_size": 3929,
        "start_ts": "2019-05-28T13:42:59+08:00",
        "last_heartbeat_ts": "2019-05-28T14:40:54.936242542+08:00",
        "uptime": "57m55.936242542s"
      }
    },
    {
      "store": {
        "id": 1,
        "address": "10.5.5.172:20160",
        "version": "2.1.10",
        "state_name": "Up"
      },
      "status": {
        "capacity": "228 GiB",
        "available": "223 GiB",
        "leader_count": 11,
        "leader_weight": 1,
        "leader_score": 1708,
        "leader_size": 1708,
        "region_count": 44,
        "region_weight": 1,
        "region_score": 3929,
        "region_size": 3929,
        "start_ts": "2019-05-28T13:42:59+08:00",
        "last_heartbeat_ts": "2019-05-28T14:40:53.323584106+08:00",
        "uptime": "57m54.323584106s"
      }
    },
    {
      "store": {
        "id": 5,
        "address": "10.5.5.174:20160",
        "state": 1,
        "version": "2.1.10",
        "state_name": "**Offline**"
      },
      "status": {
        "capacity": "228 GiB",
        "available": "223 GiB",
        "leader_count": 17,
        "leader_weight": 1,
        "leader_score": 1229,
        "leader_size": 1229,
        "region_count": 44,
        "region_weight": 1,
        "region_score": 3929,
        "region_size": 3929,
        "start_ts": "2019-05-28T13:42:59+08:00",
        "last_heartbeat_ts": "2019-05-28T14:40:53.274445891+08:00",
        "uptime": "57m54.274445891s"
      }
    }
  ]
}

I need your help，thank you!

**Comment by dbhelp** [comment]
I am very sorry, Brain shorted！  At least 3 TiKV nodes in TiDB cluster， i will remove one of three ，the warning was correct！

**Comment by shenli** [comment]
@dbhelp OK. I will close this issue. Thanks for your attention to TiDB.
