### ISSUE TITLE
tidb-tools-v2.1.10-linux-amd64.tar.gz  404 not found

### ISSUE THREAD

**Issue by acuitong** [pingcap/tidb#10610]
## Bug Report

![image](https://user-images.githubusercontent.com/40566190/58414844-32b70c80-80af-11e9-8d75-2a43c7fc4d46.png)

**Comment by july2993** [comment]
@acuitong 
- can you tell me where you get this link and what tools you want to download?
- maybe you can get what you want from http://download.pingcap.org/tidb-v2.1.10-linux-amd64.tar.gz

**Comment by acuitong** [comment]
I get this link from Ansible rolling upgrade,The address specified by the program is this link.

**Comment by july2993** [comment]
@acuitong 
can you specify the origin problem? Failed to rolling upgrade cause ansible try to download this?
@liubo0127 PTAL

**Comment by acuitong** [comment]
I use this method 'https://www.pingcap.com/docs-cn/dev/how-to/upgrade/rolling-updates-with-ansible/',

**Comment by liubo0127** [comment]
Version upgrade requires the use of the corresponding `tidb-ansible` (the upgrade between individual minor versions does not require updating `tidb-ansible`)

**Comment by acuitong** [comment]
ok,this problem has been solved. thanks

**Comment by july2993** [comment]
feel free to reopen if you still have problem.

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/58456640-48800c80-8157-11e9-8139-0ce379aa12fa.png)
We want to tried to use Ansible rolling upgrade , Auto download has been unable to download , Failed to rolling upgrade cause ansible try to download this link http://download.pingcap.org/tidb-tools-v2.1.10-linux-amd64.tar.gz  ,  and We use manual downloads, I want to upgraded version 2.1.10, why did my upgraded version become 2.1.6?

**Comment by acuitong** [comment]
@july2993 Why the rolling upgrade auto download unable to download ??

**Comment by acuitong** [comment]
I use the process
first : Modify the value of the tidb_version parameter in /home/tidb/tidb-ansible/inventory.ini
next : 
![image](https://user-images.githubusercontent.com/40566190/58458028-ab26d780-815a-11e9-942b-339e8f5a1265.png)
finally : The address specified by the program is this link
What can I do to use the auto download ??

**Comment by 799983050** [comment]
![图片](https://user-images.githubusercontent.com/45658355/58458258-559efa80-815b-11e9-90ac-b0869003234b.png)
@july2993  Error picture

**Comment by liubo0127** [comment]
Sorry, the documentation is somewhat misleading, and manual upgrades are not available in all versions. We recommend upgrading with the corresponding `tidb-ansible`, as follow:

```
1. git clone -b v2.1.10 https://github.com/pingcap/tidb-ansible.git
2. Modify tidb-ansible according to the original configuration information(inventory.ini、conf/tikv.yml ...)
3. ansible-playbook local_prepare.yml
4. ansible-playbook rolling_update.yml
5. ansible-playbook rolling_update_monitor.yml
```
