### ISSUE TITLE
There are some slow queries but I can't catch them in "show full processlist "

### ISSUE THREAD

**Issue by kevin0509** [pingcap/tidb#10625]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I executed sql like this :SELECT id FROM `table1` WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM `table2` WHERE 1 = 1 AND (id = 34285599));

2. What did you expect to see?
I want to get the info from "show fulll processlist"

3. What did you see instead?
Nothing i got from "show fulll processlist"

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.1.4

**Comment by tiancaiamao** [comment]
Is it displayed in `show processlist` ? @kevin0509

**Comment by kevin0509** [comment]
not yet. that is why i post this issue to you guys

**Comment by tiancaiamao** [comment]
Do you mean `show fulll processlist` and `show processlist` are both return empty results?

**Comment by kevin0509** [comment]
YES，this is a slow query sql. I wanted to kill it,but I could not get any info about this sql from "show processlist" and "show full processlist". Actually,it ran on the tikv nodes,and found in the slow log files.

**Comment by tiancaiamao** [comment]
> Actually,it ran on the tikv nodes,and could be found in the slow log files.

That means the query has already finished, so you don't find it in `show processlist`...
slow log record the query when it's finshed

**Comment by kevin0509** [comment]
if I delete "not exists" and reorganization the sql like :SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) ,the info of this sql can be shown from "show processlist" and "show full processlist"

**Comment by tiancaiamao** [comment]
How long this SQL takes "SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599)"
and how long this one takes "SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599))"

`show processlist` shows **the running query** ... if a query takes long, it's more likely for you to catch it in the result. @kevin0509

**Comment by kevin0509** [comment]
> How long this SQL takes "SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599)"
> and how long this one takes "SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599))"
> 
> `show processlist` shows **the running query** ... if a query takes long, it's more likely for you to catch it in the result. @kevin0509

"SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599))" takes more than 5 minitues. "SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599)" takes only about 20 seconds.

**Comment by tiancaiamao** [comment]
"SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599))"
Are you sure this one is not shown in the `show processlist` results?
Do you execute the `show processlist` in another session during the query is running?

**Comment by kevin0509** [comment]
> "SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599))"
> Are you sure this one is not shown in the `show processlist` results?
> Do you execute the `show processlist` in another session during the query is running?

YES,I am pretty sure!  For your another question, I executed the show processlist in another session during the query is running.

**Comment by tiancaiamao** [comment]
Would you mind providing the table schema so we can reproduce it?

**Comment by tiancaiamao** [comment]
By the way, did you deploy a tidb cluster, or a single tidb node?
If it's a tidb cluster and there is a proxy, your request may be not route to the right tidb, then the `show processlist` may not return what you want.

**Comment by kevin0509** [comment]
> Would you mind providing the table schema so we can reproduce it?

CREATE TABLE `xxx` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` varchar(20) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` varchar(32) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` varchar(32) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` varchar(64) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '',
  `xxx` varchar(50) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` tinyint(4) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `xxx` text CHARSET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '',
  `xxx` text CHARSET utf8 COLLATE utf8_bin DEFAULT NULL COMMENT '',
  `xxx` varchar(255) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` varchar(4096) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` varchar(15) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT 'pc' COMMENT '',
  `xxx` tinyint(4) NOT NULL DEFAULT '-1' COMMENT '',
  `xxx` float NOT NULL DEFAULT '-1' COMMENT '',
  `xxx` varchar(1024) CHARSET utf8 COLLATE utf8_bin NOT NULL DEFAULT '' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` tinyint(4) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` bigint(20) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '0' COMMENT '',
  `xxx` int(11) NOT NULL DEFAULT '1' COMMENT '',
  PRIMARY KEY (`id`),
  KEY `create_time` (`create_time`),
  KEY `mobile` (`mobile`),
  KEY `from_order_id` (`from_order_id`),
  KEY `from_tmp_task_type` (`from`,`tmk_task_type`),
  KEY `call_id` (`call_id`),
  KEY `idx_fp` (`push_result`,`follow_time`),
  KEY `idx_mfp` (`mis_user_id`,`from`,`push_result`),
  KEY `idx_ff` (`follow_time`),
  KEY `idx_nt` (`notify_time`),
  KEY `idx_aoi` (`apply_order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=153832387876859 COMMENT=''

**Comment by kevin0509** [comment]
> By the way, did you deploy a tidb cluster, or a single tidb node?
> If it's a tidb cluster and there is a proxy, your request may be not route to the right tidb, then the `show processlist` may not return what you want.

We do not use any proxy of this cluster.
It is a tidb cluster,and have three tidb nodes、three pd nodes、 three tikv nodes .  I execute this slow sql only on the designated tidb node, and I check the results of 'show processlist' on all of tidb nodes. But I  get nothing of this slow sql from these results .

**Comment by tiancaiamao** [comment]
The real problem is that, you find some slow query in the slow query log, and you want to know why it's slow?
And you want use `show processlist` to see the process of that query to verify that?

`id` is the primary key, so it's unlikely to take 20 seconds/5 minutes for those query, it must be an accident that TiDB do not use the right index.

Could you provide the result of the following SQL:

```
EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599));

EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599);

SELECT COUNT(1) FROM table1;
```

**Comment by kevin0509** [comment]
> The real problem is that, you find some slow query in the slow query log, and you want to know why it's slow?
> And you want use `show processlist` to see the process of that query to verify that?
> 
> `id` is the primary key, so it's unlikely to take 20 seconds/5 minutes for those query, it must be an accident that TiDB do not use the right index.
> 
> Could you provide the result of the following SQL:
> 
> ```
> EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599));
> 
> EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599);
> 
> SELECT COUNT(1) FROM table1;
> ```

I want to kill it , that is why I want to use show processlist.  That sql is only an example, the actual column is not "ID".

**Comment by tiancaiamao** [comment]
Usually we use `explain` to check why a SQL is slow, **COULD YOU PROVIDE THE RESULT OF THIS SQL:**

`EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599));`  

@kevin0509 

Do we have any public document about how to debug the slow query? @XuHuaiyu

**Comment by XuHuaiyu** [comment]
It seems that we only have this document for slow query
English version: https://pingcap.com/docs/dev/how-to/maintain/identify-slow-queries/#%E6%9F%A5%E8%AF%A2-slow-query-%E7%A4%BA%E4%BE%8B
中文：https://pingcap.com/docs-cn/dev/how-to/maintain/identify-slow-queries/#%E6%9F%A5%E8%AF%A2-slow-query-%E7%A4%BA%E4%BE%8B

**Comment by kevin0509** [comment]
> Usually we use `explain` to check why a SQL is slow, **COULD YOU PROVIDE THE RESULT OF THIS SQL:**
> 
> `EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599));`
> 
> @kevin0509
> 
> Do we have any public document about how to debug the slow query? @XuHuaiyu

我可以说中文么？我不明白 "show processlist中无法抓到当前正在运行的sql" 这个问题的解决跟查看执行计划有啥关系？ 表结构和示例sql都出来了，只要自己执行下含有 not exist的sql，就可以重现问题了呀？

**Comment by tiancaiamao** [comment]
>  "show processlist中无法抓到当前正在运行的sql" 


How to know that SQL is currently running?
If it's not slow, if it finish in < 4ms ... how could you catch it in the "show processlist"?

I need the explain result to convince me that it maybe slow, and maybe catched by "show processlist"

 
Why you can't post the explain result?

> EXPLAIN SELECT id FROM table1 WHERE 1 = 1 AND (id = 34285599) AND NOT EXISTS (SELECT id FROM table2 WHERE 1 = 1 AND (id = 34285599));

**Comment by kevin0509** [comment]
我开启第一个会话,SQL一直在运行中,然后再开启第二个会话，执行show processlist，无法获得该sql信息。
直到至少五分钟后第一个会话中的sql执行结束为止，在第二个会话中都无法获得该sql的信息

**Comment by kevin0509** [comment]
![image](https://user-images.githubusercontent.com/13518166/58547823-a9ccdc00-823a-11e9-83b3-b32445021193.png)

**Comment by kevin0509** [comment]
上述执行计划对应的sql为:explain SELECT XXX FROM `XXX` WHERE 1 = 1 AND (XXX = 34285599) AND NOT EXISTS (SELECT XXX FROM `XXX` WHERE 1 = 1 AND (XXX = 34285599))

**Comment by tiancaiamao** [comment]
Test on TiDB master, can't reproduce

```
mysql> show create table t1;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                    |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=4230001 |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create table t2;
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                    |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t2    | CREATE TABLE `t2` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5100001 |
+-------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select count(*) from t1;
+----------+
| count(*) |
+----------+
|  4215298 |
+----------+
1 row in set (0.58 sec)

mysql> select count(*) from t2;
+----------+
| count(*) |
+----------+
|  5083331 |
+----------+
1 row in set (0.62 sec)

mysql> select id from t1 where not exists (select 1 from t2 where  t1.id = t2.id);                                                                                                                    Empty set (2.91 sec)
```

```
mysql> show full processlist;
+------+------+-----------+------+---------+------+-------+----------------------------------------------------------------------------+
| Id   | User | Host      | db   | Command | Time | State | Info                                                                       |
+------+------+-----------+------+---------+------+-------+----------------------------------------------------------------------------+
| 4381 | root | 127.0.0.1 |      | Query   |    0 | 2     | show full processlist                                                      |
|    2 | root | 127.0.0.1 | test | Query   |    1 | 2     | select id from t1 where not exists (select 1 from t2 where  t1.id = t2.id) |
+------+------+-----------+------+---------+------+-------+----------------------------------------------------------------------------+
2 rows in set (0.00 sec)
```

**Comment by tiancaiamao** [comment]
And test with TiDB v2.1.4, can't reproduce.

```
mysql>  select id from t1 where not exists (select 1 from t2 where  t1.id = t2.id);
Empty set (2.80 sec)

mysql> select tidb_version();
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.4
Git Commit Hash: a1d10c17039ec289ef490481b25c7091dba7ac31
Git Branch: HEAD
UTC Build Time: 2019-05-29 12:55:58
GoVersion: go version go1.11.3 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> 
```

```
mysql> show full processlist;
+------+------+-----------+------+---------+------+-------+----------------------------------------------------------------------------+-------+
| Id   | User | Host      | db   | Command | Time | State | Info                                                                       | Mem   |
+------+------+-----------+------+---------+------+-------+----------------------------------------------------------------------------+-------+
|    1 | root | 127.0.0.1 | test | Query   |    2 | 2     | select id from t1 where not exists (select 1 from t2 where  t1.id = t2.id) | 16880 |
|    2 | root | 127.0.0.1 |      | Query   |    0 | 2     | show full processlist                                                      |     0 |
+------+------+-----------+------+---------+------+-------+----------------------------------------------------------------------------+-------+
2 rows in set (0.00 sec)
```

**Comment by kevin0509** [comment]
你加一列name，然后这样写试试：select id from t1 where not exists (select 1 from t2 where  name = 'xxx');

**Comment by tiancaiamao** [comment]
```
mysql> show full processlist;
+------+------+-----------+------+---------+------+-------+--------------------------------------------------------------------------+------+
| Id   | User | Host      | db   | Command | Time | State | Info                                                                     | Mem  |
+------+------+-----------+------+---------+------+-------+--------------------------------------------------------------------------+------+
|    1 | root | 127.0.0.1 | test | Query   |    0 | 2     | show full processlist                                                    |    0 |
|    2 | root | 127.0.0.1 | test | Query   |    1 | 2     | select id from t1 where not exists (select 1 from t2 where name = 'xxx') |    0 |
+------+------+-----------+------+---------+------+-------+--------------------------------------------------------------------------+------+
2 rows in set (0.00 sec)
```

**Comment by tiancaiamao** [comment]
"show processlist" show the **running query**, the lifetime of a query including 
Parse + Compile + Execute + Write Result ...
And "show processlist" currently works on those query in the Execute phase
@kevin0509

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
