### ISSUE TITLE
syncer error

### ISSUE THREAD

**Issue by simpson9527** [pingcap/tidb#10627]
Here is the thing:
I deleted some mysql binlogs from the root account, then syncer was Abnormal exit. and i was like i'm confused
#error log:
2019/05/28 18:19:21 main.go:79: [error] ERROR 1236 (HY000): Could not open log file
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:636: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:193:  
2019/05/28 18:19:21 syncer.go:1130: [error] [syncer] kill last connection 424762 err Error 1094: Unknown thread id: 424762

Now, i restart syncer, but it cannot stand up
#output logs:
[2019/05/29 10:18:31] [error] binlogstreamer.go:77 close sync with err: ERROR 1236 (HY000): Could not find first log file name in binary log index file
[2019/05/29 10:18:31] [info] binlogsyncer.go:163 syncer is closing...
[2019/05/29 10:18:31] [info] binlogsyncer.go:178 syncer is closed

#binlog
-rw-r----- 1 mysql mysql 539453184 May 28 14:29 binlog.003920
-rw-r----- 1 mysql mysql 552836567 May 28 14:29 binlog.003921
-rw-r----- 1 mysql mysql 537394206 May 28 14:29 binlog.003922
-rw-r----- 1 mysql mysql 541512164 May 28 14:29 binlog.003923
-rw-r----- 1 mysql mysql 537394200 May 28 14:29 binlog.003924
-rw-r----- 1 mysql mysql 538423695 May 28 14:29 binlog.003925
-rw-r----- 1 mysql mysql 554895541 May 28 14:29 binlog.003926
-rw-r----- 1 mysql mysql 551807068 May 28 14:29 binlog.003927
-rw-r----- 1 mysql mysql 549748098 May 28 14:29 binlog.003928
-rw-r----- 1 mysql mysql 539453186 May 28 14:30 binlog.003929
-rw-r----- 1 mysql mysql 367528265 May 28 18:22 binlog.003930
-rw-r----- 1 mysql mysql       198 May 28 18:23 binlog.003931
-rw-r----- 1 mysql mysql       177 May 29 10:15 binlog.003932
-rw-r----- 1 mysql mysql       154 May 29 10:15 binlog.003933
-rw-r----- 1 mysql mysql       602 May 29 10:15 binlog.index

**Comment by XuHuaiyu** [comment]
PTAL @july2993

**Comment by july2993** [comment]
check your meta file of Syncer
```
binlog-name = "mysql-bin.000003"
binlog-pos = 930143241
```

Syncer will start at the according file and pos, but the file way delete by you, so it can't work anymore.
you must start at a position which is not purged by mysql.

**Comment by simpson9527** [comment]
thks,problem  solved. i have a suggestion:shall we print the logfile and pos in logs when the syncer can't open binlog file .cause i don't know how to choose which binlog file to sync without losing data.

**Comment by july2993** [comment]
Thanks for you suggestion, we will consider it.
