### ISSUE TITLE
TIDB loader：[invalid insert sql][sql]

### ISSUE THREAD

**Issue by sakufo** [pingcap/tidb#10639]
## General Question

TIDB loader error, my export command is:
./mydumper -h 172.31.0.111 -u root -P 4000 -t 16 -F 64 -B papa_members --skip-tz-utc -o /data/papa_members
No error was reported throughout the process and ended normally.
When executed: ./loader -h 10.10.8.46 -u root -P 4000 -t 64 -d /data/papa_members
Always report the following error:
2019/05/29 17:59:39 loader.go:146: [fatal] restore data file (papa_members.papa_members_play_game_time_log.000000014.sql) failed, err: [invalid insert sql][sql],1538474681,1538474967),( 13360948,70040329,3242509557,60,1538474681,1538474681), (13360949,34704331,2178284194,180,1538474682,1538474682);

It is normal to migrate another library before. This library is relatively large and has 56G. Request help

**Comment by XuHuaiyu** [comment]
PTAL @july2993

**Comment by july2993** [comment]
can you show some data near encounter position: like search `1538474681,1538474967`

in file 1538474681,1538474967

**Comment by sakufo** [comment]
> 你能在遭遇位置附近显示一些数据：比如搜索 `1538474681,1538474967`
> 
> 在文件1538474681,1538474967

![5](https://user-images.githubusercontent.com/9942967/58605887-0af0c000-82cc-11e9-85f4-561af9b0190d.png)

**Comment by july2993** [comment]
@sakufo 
Issue is closed, if your problem solved?

**Comment by sakufo** [comment]
> @sakufo
> 问题已经关闭，你的问题解决了吗？

不小心点关闭了，问题没解决。我尝试忽略最大的一个表，导出备份现在是26G,现在导入仍然报类似错误

2019/05/30 11:35:29 loader.go:146: [fatal] restore data file (papa_members.papa_members_play_game_time_batch_log.000000036.sql) failed, err: [invalid insert sql][sql]"d3e255a6-fc2a-460c-ab54-ad01959a4094"),(20636488,"[{\"uid\":26632807,\"game_id\":31879427,\"play_time\":0}]",1526989807,"6a90405a-8c73-4bbe-94ed-2faf11d97715"),(20636489,"[{\"uid\":45239933,\"game_id\":3857949147,\"play_time\":167}]",1526989808,"4d6ca573-1111-4e16-a68b-7da1604b1ad4");
[root@VM_8_2_centos bin]#

**Comment by july2993** [comment]
@sakufo 
can you show the whole sql in the data file (the failed one and the previous one), and more log?

**Comment by sakufo** [comment]
@july2993 
log:
2019/05/30 11:35:29 loader.go:161: [info] [loader][restore table data sql]/data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000022.sql[finished]
2019/05/30 11:35:29 loader.go:154: [info] [loader][restore table data sql]/data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000187.sql[start]
2019/05/30 11:35:29 db.go:295: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_batch_log.000000009.sql already exists, skip it.
2019/05/30 11:35:29 db.go:295: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_batch_log.000000233.sql already exists, skip it.
2019/05/30 11:35:29 db.go:295: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_batch_log.000000039.sql already exists, skip it.
2019/05/30 11:35:29 db.go:295: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_batch_log.000000036.sql already exists, skip it.
2019/05/30 11:35:29 loader.go:212: [info] data file /data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000039.sql scanned finished.
2019/05/30 11:35:29 loader.go:161: [info] [loader][restore table data sql]/data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000039.sql[finished]
2019/05/30 11:35:29 loader.go:154: [info] [loader][restore table data sql]/data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000198.sql[start]
2019/05/30 11:35:29 db.go:295: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_batch_log.000000088.sql already exists, skip it.
2019/05/30 11:35:29 loader.go:146: [fatal] restore data file (papa_members.papa_members_play_game_time_batch_log.000000036.sql) failed, err: [invalid insert sql][sql]"d3e255a6-fc2a-460c-ab54-ad01959a4094"),(20636488,"[{\"uid\":26632807,\"game_id\":31879427,\"play_time\":0}]",1526989807,"6a90405a-8c73-4bbe-94ed-2faf11d97715"),(20636489,"[{\"uid\":45239933,\"game_id\":3857949147,\"play_time\":167}]",1526989808,"4d6ca573-1111-4e16-a68b-7da1604b1ad4");

data:
/*!40101 SET NAMES binary*/;
/*!40014 SET FOREIGN_KEY_CHECKS=0*/;
INSERT INTO `papa_members_play_game_time_batch_log` VALUES
(21188086,"[{\"uid\":57964127,\"game_id\":721834261,\"play_time\":695}]",1527247235,"a747d118-f4ed-4b8d-b87e-378b8a50785e"),
(20636484,"[{\"uid\":49268974,\"game_id\":1663697867,\"play_time\":57}]",1526989807,"c8db2c9d-8e35-4dae-8402-2d2d1b918678"),
(20636485,"[{\"uid\":60216030,\"game_id\":1736527658,\"play_time\":49}]",1526989807,"3545e580-f2df-4f26-b67f-1da2e0603e1e"),
(20636486,"[{\"uid\":26718617,\"game_id\":1628758300,\"play_time\":521}]",1526989807,"92f8fa64-4dd7-4f4a-8621-0d75cb4b17c1"),
(20636487,"[{\"uid\":0,\"game_id\":509474702,\"play_time\":1901}]",1526989807,"d3e255a6-fc2a-460c-ab54-ad01959a4094"),
(20636488,"[{\"uid\":26632807,\"game_id\":31879427,\"play_time\":0}]",1526989807,"6a90405a-8c73-4bbe-94ed-2faf11d97715"),
(20636489,"[{\"uid\":45239933,\"game_id\":3857949147,\"play_time\":167}]",1526989808,"4d6ca573-1111-4e16-a68b-7da1604b1ad4");

**Comment by sakufo** [comment]
@july2993

Probably found the cause of the problem
My statement using mysqldump to export the problem table is:
INSERT INTO `papa_members_play_game_time_batch_log` VALUES (213,'[{\"uid\":14,\"game_id\":509474702,\"play_time\":1000}
The data exported using mydumper is:
INSERT INTO papa_members.papa_members_play_game_time_batch_log VALUES
(21188086,"[{"uid":57964127,"game_id":721834261,"play_time":695}]",1527247235,"a747d118-f4ed-4b8d-b87e-378b8a50785e");

Note that the second field of values, mysqldump is a single quote, can be imported normally; and mydumper is double quotes. Direct copy to mysql command line execution is also reported.

**Comment by july2993** [comment]
https://github.com/pingcap/mydumper/pull/27/files
we have change it to use single quote, can you try again?

**Comment by sakufo** [comment]
@july2993 

[root@VM_8_2_centos bin]# ./mydumper -h 172.31.0.111 -u root -P 4000 -t 16 -F 64 -B papa_members --regex '^(?!(papa_members.papa_members_login_log))' --skip-tz-utc -o /data/papa_members     

** (mydumper:20278): CRITICAL **: 14:00:27.985: Couldn't generate @@tidb_snapshot: line 0 column 11 near " STATUS" (total length 18)

**Comment by july2993** [comment]
https://github.com/pingcap/tidb/issues/8284
you tidb version don't support `show master status` you can use -z options to specify the snapshot

**Comment by sakufo** [comment]
@july2993 

** (mydumper:1546): CRITICAL **: 11:04:05.439: Failed to set tidb_snapshot: invalid time format

**Comment by july2993** [comment]
what the format you specify? you can check the docs how to use it:
https://pingcap.com/docs/dev/reference/tools/mydumper/

search about `tidb-snapshot`

**Comment by sakufo** [comment]
2019/05/31 12:36:11 loader.go:161: [info] [loader][restore table data sql]/data/papa_members/papa_members.papa_members_reg_log.000000012.sql[finished]
2019/05/31 12:36:11 loader.go:154: [info] [loader][restore table data sql]/data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000090.sql[start]
2019/05/31 12:36:11 db.go:315: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_batch_log.000000010.sql already exists, skip it.
2019/05/31 12:36:11 loader.go:146: [fatal] restore data file (papa_members.papa_members_play_game_time_batch_log.000000002.sql) failed, err: [invalid insert sql][sql]me\":62}]',1516252861,'359e3988-98c9-4778-b7f4-16b7ca6a2c7c'),(346594,'[{\"uid\":49817578,\"game_id\":122078927,\"play_time\":0}]',1516252861,'9324d793-2bb0-4885-b69f-a4a2591e34e1'),(346595,'[{\"uid\":5110272,\"game_id\":509474702,\"play_time\":856}]',1516252861,'2e0adaa0-0371-4451-ab68-b82327d7ed6c'),(346596,'[{\"uid\":50847169,\"game_id\":1056989342,\"play_time\":218}]',1516252861,'feec783b-f51b-40a4-a90f-b560219f52d0');


Copying the statement from the file is no problem in the mysql command line. Use the loader to import the above error.

INSERT INTO `papa_members_play_game_time_batch_log` VALUES
(3121465,'[{\"uid\":40417224,\"game_id\":530554297,\"play_time\":2}]',1518174307,'ce22e76e-9bc3-44fd-bbf6-c88bfc6d6e7b'),
(3121466,'[{\"uid\":22344124,\"game_id\":2465501517,\"play_time\":109}]',1518174307,'0151a880-8917-4db7-8381-041722b1105e'),
(346596,'[{\"uid\":50847169,\"game_id\":1056989342,\"play_time\":218}]',1516252861,'feec783b-f51b-40a4-a90f-b560219f52d0');

**Comment by july2993** [comment]
the laster `INSERT INTO...` if not the same as where the error encounter.
```
(papa_members.papa_members_play_game_time_batch_log.000000002.sql) failed, err: [invalid insert sql][sql]me":62}]',1516252861,'359e3988-98c9-4778-b7f4-16b7ca6a2c7c'),(346594,'[{"uid":49817578,"game_id":122078927,"play_time":0}]',1516252861,'9324d793-2bb0-4885-b69f-a4a2591e34e1'),(346595,'[{"uid":5110272,"game_id":509474702,"play_time":856}]',1516252861,'2e0adaa0-0371-4451-ab68-b82327d7ed6c'),(346596,'[{"uid":50847169,"game_id":1056989342,"play_time":218}]',1516252861,'feec783b-f51b-40a4-a90f-b560219f52d0');
```
the means loader wrongly split the `INSERT INTO..` at a start position `me":62}]',1516252861,'359e3988`, you can check the origin data file about this posttion.

**Comment by july2993** [comment]
close as duplicated of https://github.com/pingcap/tidb/issues/10679
