### ISSUE TITLE
set tidb_snapshot error

### ISSUE THREAD

**Issue by Still4** [pingcap/tidb#10631]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
mysql> set @@tidb_snapshot="2019-05-28 20:00:00";

2. What did you expect to see?

3. What did you see instead?
ERROR 1105 (HY000): parsing time "20190508-13:00:31 +0000" as "20060102-15:04:05 -0700 MST": cannot parse "" as "MST"

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.9
Git Commit Hash: 7eaea3059bf8b0678746f6d757dd4c9d083bf417
Git Branch: HEAD
UTC Build Time: 2019-05-06 11:34:16
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by XuHuaiyu** [comment]
Hi, @Still4 what's the timezone of your tidb-server?

**Comment by Still4** [comment]
@XuHuaiyu 
mysql> SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| UTC                | UTC                 | 
+--------------------+---------------------+

**Comment by XuHuaiyu** [comment]
Can you provide us the tidb log related to this problem?

**Comment by Still4** [comment]
[2019/05/29 06:36:05.852 +00:00] [WARN] [session.go:816] ["run statement error"] [conn=68700211] [schemaVersion=13250] [error="parsing time \"20190508-13:00
:31 +0000\" as \"20060102-15:04:05 -0700 MST\": cannot parse \"\" as \"MST\""] [errorVerbose="parsing time \"20190508-13:00:31 +0000\" as \"20060102-15:04:0
5 -0700 MST\": cannot parse \"\" as \"MST\"\ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap
/errors@v0.11.1/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/errors@v0.11.1/j
uju_adaptor.go:15\ngithub.com/pingcap/tidb/executor.validateSnapshot\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/
set.go:212\ngithub.com/pingcap/tidb/executor.(*SetExecutor).setSysVariable\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/exe
cutor/set.go:173\ngithub.com/pingcap/tidb/executor.(*SetExecutor).Next\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executo
r/set.go:96\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tid
b/executor/adapter.go:289\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/e
xecutor/adapter.go:245\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/tidb.g
o:198\ngithub.com/pingcap/tidb/session.(*session).executeStatement\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/ses
sion.go:813\ngithub.com/pingcap/tidb/session.(*session).execute\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/sessio
n.go:883\ngithub.com/pingcap/tidb/session.(*session).Execute\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/session.g
o:832\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/driver_tid
b.go:235\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn
.go:912\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:
658\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:506\ngith
ub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/server.go:384\nruntime.goex
it\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"] [session="{\n  \"currDBName\": \"bi_system\",\n  \"id\": 68700211,\n  \"status\": 2,\n  \"strictMode\": t
rue,\n  \"user\": {\n    \"Username\": \"root\",\n    \"Hostname\": \"10.84.170.133\",\n    \"CurrentUser\": false,\n    \"AuthUsername\": \"\",\n    \"Auth
Hostname\": \"\"\n  }\n}"]
[2019/05/29 06:36:05.853 +00:00] [WARN] [conn.go:522] ["dispatch error"] [conn=68700211] [connInfo="id:68700211, addr:10.84.170.133:19365 status:2, collatio
n:latin1_swedish_ci, user:root"] [sql="set @@tidb_snapshot=\"2019-05-28 20:00:00\""] [err="parsing time \"20190508-13:00:31 +0000\" as \"20060102-15:04:05 -
0700 MST\": cannot parse \"\" as \"MST\"\ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/er
rors@v0.11.1/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/pkg/mod/github.com/pingcap/errors@v0.11.1/juju
_adaptor.go:15\ngithub.com/pingcap/tidb/executor.validateSnapshot\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/set
.go:212\ngithub.com/pingcap/tidb/executor.(*SetExecutor).setSysVariable\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/execut
or/set.go:173\ngithub.com/pingcap/tidb/executor.(*SetExecutor).Next\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/executor/s
et.go:96\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/e
xecutor/adapter.go:289\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/exec
utor/adapter.go:245\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/tidb.go:1
98\ngithub.com/pingcap/tidb/session.(*session).executeStatement\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/sessio
n.go:813\ngithub.com/pingcap/tidb/session.(*session).execute\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/session.g
o:883\ngithub.com/pingcap/tidb/session.(*session).Execute\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/session/session.go:8
32\ngithub.com/pingcap/tidb/server.(*TiDBContext).Execute\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/driver_tidb.g
o:235\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go
:912\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:658
\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/conn.go:506\ngithub.
com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/workspace/release_tidb_2.1-ga/go/src/github.com/pingcap/tidb/server/server.go:384\nruntime.goexit\
n\t/usr/local/go/src/runtime/asm_amd64.s:1337"]
