### ISSUE TITLE
batch Insert BUG

### ISSUE THREAD

**Issue by acuitong** [pingcap/tidb#10645]
![image](https://user-images.githubusercontent.com/40566190/58606149-e9dc9f00-82cc-11e9-89f8-f85ff7835167.png)
I need to insert 4 million pieces of data,This is my configuration,But after inserting 2 million data,The process will be killed by the program,not unusually message

**Comment by jackysp** [comment]
@acuitong , please follow our issue template to fill your question, thanks!

**Comment by acuitong** [comment]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
    'set @@SESSION.tidb_bathc_insert = 1; set @@SEESION.tidb_dml_batch_size = 5000;'
    I need to insert 4 million pieces of data
    this is already set up in SQL

2. What did you expect to see?
   


3. What did you see instead?
    it stopped at 2 million, view database process , the process is killed by the program , there are no 
    error messages 
  
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

    tidb version 2.1.10,

**Comment by jackysp** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/10640
