### ISSUE TITLE
Batch insert question

### ISSUE THREAD

**Issue by acuitong** [pingcap/tidb#10646]
![image](https://user-images.githubusercontent.com/40566190/58606655-fc57d800-82ce-11e9-95b2-5f96c5b3ad41.png)

I need to insert 4 million pieces of data,This is my configuration,But after inserting 2 million data,The process will be killed by the program,not unusually message

**Comment by jackysp** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/10640
