### ISSUE TITLE
Foreign Key Update/Delete Constraints: ON DELETE/CREATE

### ISSUE THREAD

**Issue by steffengy** [pingcap/tidb#1064]
Is there any plan to support `ON [DELETE|CREATE]` for constraints in the future
since they are helpful to ensure integrity ?

Also currently if you for example design a schema with Mysql Workbench or similar tools,
the exported SQL may be incompatible with TIDB because tidb's SQL parser isn't aware of these keywords, so that would also be an improvement in
terms of compatibility.

[1] http://dev.mysql.com/doc/refman/5.7/en/create-table-foreign-keys.html

**Comment by ngaut** [comment]
@steffengy Thanks for reporting the issue. 
Currently we don't have any plans to support foreign-key constraints. Since it would be very slow on big tables( thousands of billion of rows).

**Comment by steffengy** [comment]
@ngaut 
Am I right that currently foreign keys are supported by the parser and simply
ignored during anything related to storage?
If so, wouldn't it be advisable to also support the `ON [DELETE|UPDATE]` syntax
atleast in the parser to be able to use common mysql tools?

**Comment by ngaut** [comment]
Yes, you are right. We may let the parser to support the ON [DELETE|UPDATE] syntax later. @shenli

**Comment by shenli** [comment]
@steffengy TiDB can work with Workbench. Have you met any problem when use some db admin tools?

**Comment by steffengy** [comment]
@shenli 
Of course it does work with Workbench for common tasks.
But my point is that if you're using workbench (or any other tool exporting the mysql dialect)
to design a database workbase may generate `ON [DELETE|UPDATE] ` clauses,
which requires manual patching of the generated SQL to prevent that tidb throws an error 
(since these keywords are unknown) to create the database.

**Comment by shenli** [comment]
@steffengy We will support those syntax (at lease prevent parser error).
Thanks for your report!

**Comment by coocood** [comment]
Syntax support is done by https://github.com/pingcap/tidb/pull/1152
