### ISSUE TITLE
transactions

### ISSUE THREAD

**Issue by acuitong** [pingcap/tidb#10640]
Now you can insert local variables that bypass large transactions. Do you want to provide a one-time change to global variables;

**Comment by XuHuaiyu** [comment]
Hi, @acuitong 
Thanks for your feedback.
Sorry that I do not really understand what do you mean.
Can you show me an example?

**Comment by acuitong** [comment]
now,I need to insert 4 million data through a single transaction,Local variables are set 'tidb_batch_insert',Is there a global variable that has the same meaning??

**Comment by jackysp** [comment]
Sorry, there is no similar global variable. The behavior after tidb_batch_insert is turned on is very difficult to control. If it is turned on globally, it will have too much impact on correctness.

**Comment by acuitong** [comment]
![image](https://user-images.githubusercontent.com/40566190/58605439-55713d00-82ca-11e9-8265-bcd9bcc503f3.png)
I need to insert 4 million data through a single transaction,Here are my Settings,but it stopped at 2 million,and not unusually.What's the reason, please

**Comment by jackysp** [comment]
What does "a single transaction" look like? The batch insert will only work on the autocommitted transactions. Please check out the TiDB's documents.

**Comment by acuitong** [comment]
We have a business scenario where we need to insert 4 million data at once，Previous mysql business scenarios，The business scenario is a one-time submission,

**Comment by acuitong** [comment]
INSERT INTO ods_order_item_base_two (
		non_tax_code...
	 ) 
	SELECT
		ei.non_tax_code.......
	FROM
	   order_item oi
	JOIN order_item_details oid ON oi.item_no = oid.item_no
	JOIN order_item_extra oie ON oi.item_no = oie.item_no
	JOIN order_header oh ON oi.trans_no = oh.trans_no
	JOIN expenses_item ei ON ei.id = oi.setmanag_item_id
    where
        oi.status_id = '80';
This is my SQL statement , This statement has 4 million pieces of data

**Comment by jackysp** [comment]
So what's the error message? And the TiDB version?
It is best to follow the issue template, so that we don't have to ask questions again and again.

**Comment by acuitong** [comment]
No error message,the process will be killed by the program,tidb version is 2.1.10

**Comment by jackysp** [comment]
> ![image](https://user-images.githubusercontent.com/40566190/58605439-55713d00-82ca-11e9-8265-bcd9bcc503f3.png)
> I need to insert 4 million data through a single transaction,Here are my Settings,but it stopped at 2 million,and not unusually.What's the reason, please

I think you've answered the reason in the following reply.

> No error message,the process will be killed by the program,tidb version is 2.1.10

**Comment by acuitong** [comment]
I use this method,these problems were found,this is already set up in SQL

**Comment by acuitong** [comment]
'set @@SESSION.tidb_bathc_insert = 1; set @@SEESION.tidb_dml_batch_size = 5000;'   
this is already set up in SQL,but it stopped at 2 million , no error message , 
the process is killed by the program,
tidb version 2.1.10, 
is this a bug??

**Comment by jackysp** [comment]
> 'set @@SESSION.tidb_bathc_insert = 1; set @@SEESION.tidb_dml_batch_size = 5000;'
> this is already set up in SQL,but it stopped at 2 million , no error message ,
> the process is killed by the program,
> tidb version 2.1.10,
> is this a bug??

I just want to know the reason for "the process is killed by the program,".
Setting variables also does not guarantee that the process will not be killed. There is no reason for the process to be killed without any errors?

**Comment by acuitong** [comment]
it stopped at 2 million, view database process , the process is killed by the program , there are no error messages , If there is, I will make it clear

**Comment by jackysp** [comment]
"the process is killed by the program"
I need to know the process name and the program name.
If the process is tidb-server, plz check out the log files of it, tidb.log and tidb_stderr.log

**Comment by 799983050** [comment]
@jackysp If we encounter a mistake, will we not say it?Now the fact is that data is inserted into more than 2 million .execute show full PROCESSLIST,insert into thread disappear. No error message was reported.

**Comment by jackysp** [comment]
@799983050 plz describe your question more clearly.

**Comment by jackysp** [comment]
@acuitong maybe you could email me all your information in Chinese. yusp@pingcap.com

**Comment by 799983050** [comment]
@jackysp Sorry, we've been looking at the Navicat client without error messages. 
 We want to insert a lot of data. The format of the statement executed is as follows：
`  INSERT INTO ods_order_item_base_two (
	non_tax_code...
 ) 
SELECT
	ei.non_tax_code.......
FROM
   order_item oi
JOIN order_item_details oid ON oi.item_no = oid.item_no
JOIN order_item_extra oie ON oi.item_no = oie.item_no
JOIN order_header oh ON oi.trans_no = oh.trans_no
JOIN expenses_item ei ON ei.id = oi.setmanag_item_id
where
    oi.status_id = '80';`

we've been looking at the Navicat client without error messages
Now the fact is that data is inserted into more than 2 million .
execute show full PROCESSLIST,insert into thread disappear. No error message was reported.
**Can we see this error from somewhere else?**

**Comment by 799983050** [comment]
@jackysp  Let me send an email.  I'm his colleague.

**Comment by 799983050** [comment]
@jackysp  The mail has been sent .
