### ISSUE TITLE
sysbench for tidb3.0

### ISSUE THREAD

**Issue by DBKent** [pingcap/tidb#10659]
## General Question
|Release Version: v3.0.0-rc.1-114-gcc74145ff
sysbench :  sysbench 1.0.17

table:10
table_size=100000000
prepare command: 
nohup sysbench /usr/share/sysbench/oltp_common.lua --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=X --mysql-password=X  --tables=10 --table-size=100000000 prepare &

why I  run oltp_read_write.lua  sometimes have error?
![image](https://user-images.githubusercontent.com/51220911/58679686-368cac80-8397-11e9-909f-29c8511d0449.png)

run command:
ohup sysbench /usr/share/sysbench/oltp_read_write.lua --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=x --mysql-password='x'  --tables=10 --table-size=100000000 --num-threads=64  --report-interval=10 --rand-type=uniform --max-time=1800 --max-requests=0 --percentile=95 run >> mix64.log &

my config is default,just change sync-log to false,what problem to this sysbench test?
this error just in oltp_read_write.lua ,other test haven't error like oltp_insert.lua,oltp_point_select.lua.

**Comment by lamxTyler** [comment]
@DBKent Thanks for your feedback. The error means that there are two transactions modified the same row, and usually, TiDB will retry a certain number of times. You can see the log of TiDB for detailed info.

**Comment by DBKent** [comment]
@lamxTyler  this is my tidb log,and why just run oltp_read_write have this problem?
![image](https://user-images.githubusercontent.com/51220911/58687280-d1937f80-83b3-11e9-8ae3-43de2b794b1c.png)

**Comment by lamxTyler** [comment]
@DBKent Because there are two transactions modified the same row，and the tidb has disabled the auto retry. You can try to set the session variable `tidb_disable_txn_auto_retry` to off.

**Comment by DBKent** [comment]
@lamxTyler , ok! I'll try it,thanks for your suggestion.
