### ISSUE TITLE
TiDB server was killled when oom

### ISSUE THREAD

**Issue by konser** [pingcap/tidb#10666]
-- 2个TiDB server分别在两台不同机器 硬件配置48G内存 SSD
-- 数据量26849546 player_register_log、数据量174769814 player_login_log
查询语句
select b.date_str,count(DISTINCT a.device_id ) 
from (select role_id, device_id from register.player_register_log) a,
(select date_format(log_time,"%Y-%m-%d") as date_str, role_id  from login.player_login_log group by date_str,role_id) b 
where a.role_id = b.role_id GROUP BY b.date_str;

查询后报内存溢出，能否将一条sql计算分散到多个TiDB server去，这样就可以快速查询出结果了

**Comment by konser** [comment]
补充一下，我在执行过程中查看另一台TiDB server 是没有负载的

**Comment by konser** [comment]
那位pingcap的大哥可以解答下我的问题，谢谢了

**Comment by lamxTyler** [comment]
@konser TiDB does not support distribute the computation to another TiDB server currently.

**Comment by shenli** [comment]
You need to optimize the [query plan](https://pingcap.com/docs/dev/reference/performance/understanding-the-query-execution-plan/#understand-the-query-execution-plan).

**Comment by konser** [comment]
explain select b.date_str,count(DISTINCT a.device_id )  from (select role_id, device_id from register.player_register_log) a, (select date_format(log_time,"%Y-%m-%d") as date_str, role_id  from login.player_login_log group by date_str,role_id) b  where a.role_id = b.role_id GROUP BY b.date_str;
+--------------------------------+--------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                             | count        | task | operator info                                                                                                                                                                                |
+--------------------------------+--------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_12                  | 26993672.00  | root | b.date_str, 8_col_0                                                                                                                                                                          |
| └─HashAgg_15                   | 26993672.00  | root | group by:b.date_str, funcs:count(distinct register.player_register_log.device_id), firstrow(b.date_str)                                                                                      |
|   └─HashRightJoin_17           | 26993672.00  | root | inner join, inner:Projection_18, equal:[eq(cast(register.player_register_log.role_id), cast(login.player_login_log.role_id))]                                                                |
|     ├─Projection_18            | 26993672.00  | root | register.player_register_log.role_id, register.player_register_log.device_id, cast(register.player_register_log.role_id)                                                                     |
|     │ └─TableReader_20         | 26993672.00  | root | data:TableScan_19                                                                                                                                                                            |
|     │   └─TableScan_19         | 26993672.00  | cop  | table:player_register_log, range:[-inf,+inf], keep order:false                                                                                                                               |
|     └─Projection_21            | 40586336.37  | root | date_format(login.player_login_log.log_time, "%Y-%m-%d"), login.player_login_log.role_id, cast(login.player_login_log.role_id)                                                               |
|       └─HashAgg_26             | 40586336.37  | root | group by:col_2, col_3, funcs:firstrow(col_0), firstrow(col_1)                                                                                                                                |
|         └─TableReader_27       | 40586336.37  | root | data:HashAgg_22                                                                                                                                                                              |
|           └─HashAgg_22         | 40586336.37  | cop  | group by:date_format(login.player_login_log.log_time, "%Y-%m-%d"), login.player_login_log.role_id, funcs:firstrow(login.player_login_log.log_time), firstrow(login.player_login_log.role_id) |
|             └─TableScan_25     | 174784571.00 | cop  | table:player_login_log, range:[-inf,+inf], keep order:false                                                                                                                                  |
+--------------------------------+--------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
11 rows in set (0.00 sec)

**Comment by lamxTyler** [comment]
@konser 

- What is the schema of table `player_register_log` and `player_login_log `?
- What is the result of `select count(distinct date_str, role_id) from login.player_login_log`?
- Can `select b.date_str,count(*)  from (select role_id, device_id from register.player_register_log) a, (select date_format(log_time,"%Y-%m-%d") as date_str, role_id  from login.player_login_log group by date_str,role_id) b  where a.role_id = b.role_id GROUP BY b.date_str;` run sucessfully?

**Comment by konser** [comment]
@lamxTyler 统计每天的活跃设备数量

**Comment by konser** [comment]
CREATE TABLE `player_login_log` (
  `log_id` char(32) NOT NULL DEFAULT '' COMMENT '日志ID',
  `log_time` datetime NOT NULL COMMENT '日志时间',
  `log_ip` varchar(255) DEFAULT NULL,
  `server_ip` varchar(255) DEFAULT NULL,
  `pf` varchar(255) DEFAULT NULL,
  `area_id` int(11) DEFAULT NULL,
  `original_server_id` int(11) DEFAULT '0' COMMENT '原服务器id',
  `server_id` int(11) DEFAULT '0' COMMENT '当前服务器id',
  `open_id` varchar(255) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `role_id` int(11) DEFAULT NULL,
  `peak_level` int(11) DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  KEY `idx_log_time` (`log_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `player_register_log` (
  `log_id` char(32) NOT NULL DEFAULT '' COMMENT '日志ID',
  `log_time` datetime NOT NULL COMMENT '日志时间',
  `log_ip` varchar(255) DEFAULT NULL,
  `pf` varchar(255) DEFAULT NULL,
  `area_id` int(11) DEFAULT NULL,
  `original_server_id` int(11) DEFAULT '0' COMMENT '原服务器id',
  `server_id` int(11) DEFAULT '0' COMMENT '当前服务器id',
  `open_id` varchar(255) DEFAULT NULL,
  `role_id` varchar(255) DEFAULT NULL,
  `role_name` varchar(255) DEFAULT NULL,
  `role_career` int(11) DEFAULT NULL,
  `role_sex` int(11) DEFAULT NULL,
  `app_id` varchar(255) DEFAULT NULL,
  `client_version` varchar(255) DEFAULT NULL,
  `sys_software` varchar(255) DEFAULT NULL,
  `sys_hardware` varchar(255) DEFAULT NULL,
  `telecom_oper` varchar(255) DEFAULT NULL,
  `network` varchar(255) DEFAULT NULL,
  `screen_width` int(11) DEFAULT NULL,
  `screen_hight` int(11) DEFAULT NULL,
  `density` float DEFAULT NULL,
  `reg_channel` int(11) DEFAULT NULL,
  `cpu_hardware` varchar(255) DEFAULT NULL,
  `memory` int(11) DEFAULT NULL,
  `gl_render` varchar(255) DEFAULT NULL,
  `gl_version` varchar(255) DEFAULT NULL,
  `device_id` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`log_id`),
  KEY `idx_log_time` (`log_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

**Comment by konser** [comment]
@lamxTyler 我加大了swap内存 运行结果出来了，不过很慢 我的机器内存是48G swap加到了40G 用了15min

**Comment by konser** [comment]
@lamxTyler 非常高兴能收到你的回复，感谢你的指点。

**Comment by konser** [comment]
向我这种12亿数据量的表 字段新建立一个索引需要多长时间

**Comment by konser** [comment]
308 | root | 127.0.0.1 | login    | Query   | 4364 | 2     | ALTER TABLE `player_login_log`
ADD INDEX `idx_role_id` (`role_id`) |

**Comment by konser** [comment]
建立索引的速度可以优化吗，还是我建的有问题

**Comment by konser** [comment]
我用kill 308这个命令杀不掉这个操作

**Comment by lamxTyler** [comment]
@konser You can use `admin show ddl jobs` to get the current status of add index, and you can estimate the remaining time.And you can use `ADMIN CANCEL DDL JOBS job_id` to cancel the ddl jobs. See https://pingcap.com/docs-cn/dev/reference/sql/statements/admin/#admin-%E8%AF%AD%E5%8F%A5

**Comment by lamxTyler** [comment]
Feel free to reopen it if you have further questions.
