### ISSUE TITLE
Question about `order by` behavior

### ISSUE THREAD

**Issue by minifan321** [pingcap/tidb#10665]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. 添加数据?
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('1', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('2', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('3', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('4', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('5', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('6', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('7', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('8', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('9', '2019-05-31 17:03:35');
INSERT INTO `yilian_emr`.`sys_test`(`id`, `create_time`) VALUES ('10', '2019-05-31 17:03:35');

2. 执行查询语句：
SELECT id,create_time FROM `sys_test` ORDER BY create_time;

SELECT id,create_time FROM `sys_test` ORDER BY create_time LIMIT 0,5;

SELECT id,create_time  FROM `sys_test` ORDER BY create_time LIMIT 5,5;

3. What did you see instead?
SELECT id,create_time FROM `sys_test` ORDER BY create_time;
![image](https://user-images.githubusercontent.com/51229325/58695513-348f1180-83c8-11e9-8afa-15730cd7bed9.png)
SELECT id,create_time FROM `sys_test` ORDER BY create_time LIMIT 0,5;
![image](https://user-images.githubusercontent.com/51229325/58695546-48d30e80-83c8-11e9-9ecc-d8cff62f7bb1.png)
SELECT id,create_time  FROM `sys_test` ORDER BY create_time LIMIT 5,5;
![image](https://user-images.githubusercontent.com/51229325/58695578-55effd80-83c8-11e9-8bd0-8e2a8731b392.png)

为何ID=1的数据丢失了

4. What version of TiDB are you using ?
Release Version: v2.1.0-rc.3-232-ga3e25b2
Git Commit Hash: a3e25b2f8f286694d8ee35d61d04ec755136811d
Git Branch: master
UTC Build Time: 2018-11-26 03:19:27
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by tiancaiamao** [comment]
See also https://github.com/pingcap/tidb/issues/10148

**Comment by tiancaiamao** [comment]
For the same `create_time`, order by `create_time`, the `id` column values could be unordered
If you want them to be both ordered, you need 
order by `create_time`, `id`
