### ISSUE TITLE
loader error：failed, err: [invalid insert sql]

### ISSUE THREAD

**Issue by sakufo** [pingcap/tidb#10679]
2019/06/03 16:23:31 db.go:295: [info] checkpoint id:4c66d3 filename papa_members.papa_members_play_game_time_log.000000016.sql already exists, skip it.
2019/06/03 16:23:31 loader.go:146: [fatal] restore data file (papa_members.papa_members_play_game_time_batch_log.000000079.sql) failed, err: [invalid insert sql][sql]_time\":0}]',1534948960,'f49a04f4-e5d3-4da4-b9a6-28b3d1b724c2');

I use the mysql command to import the wrong file can be imported normally, use the loader to import the above error.
Mysql -uroot -p -h10.10.8.2 -P4000 papa_members < /data/papa_members/papa_members.papa_members_play_game_time_batch_log.000000079.sql

The following is part of my data file, please help me, this problem has been bothering me for several days. thank you very much.
INSERT INTO `papa_members_play_game_time_batch_log` VALUES
(40729681,'[{\"uid\":67704592,\"game_id\":3857949147,\"play_time\":73}]',1534827282,'8e7215d4-81a8-43e6-82b1-f0eebcc45662'),
(40729682,'[{\"uid\":47433859,\"game_id\":338506589,\"play_time\":1004}]',1534827283,'a8074cb1-dc07-4437-835a-b88bb18e40de'),
(40729683,'[{\"uid\":67703886,\"game_id\":2465501517,\"play_time\":0}]',1534827283,'3ed0bfbd-8928-4db8-8223-11314debc915'),
(40729684,'[{\"uid\":67482412,\"game_id\":2851631854,\"play_time\":1998}]',1534827283,'17006c91-0765-45e7-b1b6-743d64a800d0'),
(40729685,'[{\"uid\":16426828,\"game_id\":1001856052,\"play_time\":3474}]',1534827283,'02f58ea5-2026-48f8-998b-a88be14b4901'),
(41249924,'[{\"uid\":60464455,\"game_id\":105674098,\"play_time\":84}]',1534948960,'281690ad-3a5a-4ac5-ba62-221215f2cca8'),
(41249925, '[{\"uid\":4610944,\"game_id\":530554297,\"play_time\":2508}]',1534948960,'523858f2-d69e-4208-a700-05bc80956ca8'),
(41249926, '[{\"uid\":57527610,\"game_id\":1736527658,\"play_time\":0}]',1534948960,'f49a04f4-e5d3-4da4-b9a6-28b3d1b724c2');

**Comment by sakufo** [comment]
Suspect whether the field splitting problem is caused by single or double quotes.

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @july2993

**Comment by july2993** [comment]
please update in the origin issue https://github.com/pingcap/tidb/issues/10639, don't create new one for reply.
can you try to use [DM](https://github.com/pingcap/dm) ?

**Comment by sakufo** [comment]
@july2993 
My need is for data to migrate from tidb to tidb.

**Comment by GregoryIan** [comment]
@sakufo can you provide your raw file `papa_members.papa_members_play_game_time_batch_log.000000079.sql)`? According to loder's logic, if there is a `\n` in the middle of the data file, then this error will occur.
 I need the raw file to reproduce this error.

**Comment by sakufo** [comment]
@GregoryIan 
Several files have this error, please provide a mailbox. I will send you the download address of the file.

**Comment by sakufo** [comment]
@july2993 
Is the comma in the string field causing the field to be split incorrectly, causing the insertion to fail?

'[{"uid":16426828,"game_id":1001856052,"play_time":3474}]'

**Comment by july2993** [comment]
> @july2993
> Is the comma in the string field causing the field to be split incorrectly, causing the insertion to fail?
> 
> '[{"uid":16426828,"game_id":1001856052,"play_time":3474}]'

no, you can send files to et@pingcap.com

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
