### ISSUE TITLE
Missing data in query result

### ISSUE THREAD

**Issue by beebol** [pingcap/tidb#10674]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
执行一个复杂查询（关联多个库查询），正常执行时间在500秒左右，但有时会只查询几秒钟就完成了，结果只有部分数据，程序没有抛任务异常。同样的sql在mysql中跑是没有出现过这种现象。相同的数据，相同的sql。

2. What did you expect to see?
tidb:  16core  128G内存
确认是bug还是配置有问题？

3. What did you see instead?

tidb日志：
[2019/06/03 01:22:03.305 +08:00] [WARN] [compiler.go:79] [EXPENSIVE_QUERY] [SQL="        select v.user_uuid,\n        CONCAT(v.vip_id,'_^',\n            if(v.product_id =0,0,p.renew),'_^',v.product_id,'_^',v.channel_uuid,'_^',\n            if(v.price =0,0,1),'_^',if(p.days is null,0,p.days),'_^',if(g.level is null,0,g.level),'_^',if( o.platform_id is null,0, o.platform_id)) as vip_renew,\n            CAST(1 AS signed) as cnt from vip_service v left join product p on p.id = v.product_id left join vip_growth g on v.user_uuid = g.user_uuid \n                    left join `order` o on o.uuid = v.order_uuid\n                    where v.vip_end_time > '2019-06-02' and v.vip_begin_time < '2019-06-03'  and v.created_at < '2019-06-03' and v.channel_uuid != 'CCCCCCCCCCCC'   and v.status = 0 \n                    and  1=1  GROUP BY v.user_uuid\n        "]
[2019/06/03 01:22:03.943 +08:00] [INFO] [coprocessor.go:721] ["[TIME_COP_PROCESS] resp_time:484.424788ms txnStartTS:408812551741898783 region_id:47584 store_addr:10.43.208.210:20160 kv_process_ms:481 scan_total_write:154186 scan_processed_write:154185 scan_total_data:154185 scan_processed_data:154185 scan_total_lock:1 scan_processed_lock:0"]
[2019/06/03 01:22:04.254 +08:00] [INFO] [coprocessor.go:721] ["[TIME_COP_PROCESS] resp_time:794.956568ms txnStartTS:408812551741898783 region_id:44524 store_addr:10.43.101.89:20160 kv_process_ms:794 scan_total_write:192264 scan_processed_write:192263 scan_total_data:192263 scan_processed_data:192263 scan_total_lock:1 scan_processed_lock:0"]
[2019/06/03 01:22:04.377 +08:00] [INFO] [coprocessor.go:721] ["[TIME_COP_PROCESS] resp_time:918.225464ms txnStartTS:408812551741898783 region_id:44648 store_addr:10.43.208.210:20160 kv_process_ms:916 scan_total_write:224551 scan_processed_write:224550 scan_total_data:224550 scan_processed_data:224550 scan_total_lock:1 scan_processed_lock:0"]
[2019/06/03 01:22:04.416 +08:00] [INFO] [coprocessor.go:721] ["[TIME_COP_PROCESS] resp_time:957.60428ms txnStartTS:408812551741898783 region_id:36268 store_addr:10.43.101.90:20160 kv_process_ms:956 scan_total_write:194706 scan_processed_write:194704 scan_total_data:194705 scan_processed_data:194704 scan_total_lock:1 scan_processed_lock:0"]
...

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
[tidb@iZ2ze2d8u10y3fuv5c6w0yZ bin]$ ./tidb-server -V
Release Version: v3.0.0-beta.1-133-g27a56180b
Git Commit Hash: 27a56180bd20a4151458ea60cd3667f2de598264
Git Branch: master
UTC Build Time: 2019-04-22 05:31:36
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by lamxTyler** [comment]
@beebol Thanks for your feedback! Could you provide the SQL text and the related table schemas?

**Comment by beebol** [comment]
@lamxTyler 
SQL:
 select v.user_uuid,\n        CONCAT(v.vip_id,'_^',\n            if(v.product_id =0,0,p.renew),'_^',v.product_id,'_^',v.channel_uuid,'_^',\n            if(v.price =0,0,1),'_^',if(p.days is null,0,p.days),'_^',if(g.level is null,0,g.level),'_^',if( o.platform_id is null,0, o.platform_id)) as vip_renew,\n            CAST(1 AS signed) as cnt from vip_service v left join product p on p.id = v.product_id left join vip_growth g on v.user_uuid = g.user_uuid \n                    left join `order` o on o.uuid = v.order_uuid\n                    where v.vip_end_time > '2019-06-02' and v.vip_begin_time < '2019-06-03'  and v.created_at < '2019-06-03' and v.channel_uuid != 'CCCCCCCCCCCC'   and v.status = 0 \n                    and  1=1  GROUP BY v.user_uuid

Table schemas:
CREATE TABLE `vip_service` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT 'xxxx',
  `user_uuid` char(32) NOT NULL DEFAULT '' COMMENT 'xxx',
  `order_uuid` char(32) NOT NULL DEFAULT '' COMMENT 'xxx',
  `product_id` int(11) NOT NULL COMMENT 'xxxx',
  `vip_begin_time` datetime NOT NULL COMMENT '开始时间',
  `vip_end_time` datetime NOT NULL COMMENT '结束时间',
  `vip_id` tinyint(1) NOT NULL COMMENT 'xxx',
  `days` int(8) NOT NULL COMMENT 'xxx',
  `price` int(11) NOT NULL COMMENT 'xxxx',
  `channel_uuid` char(32) NOT NULL DEFAULT '' COMMENT '渠道uuid',
  `batch_id` int(5) NOT NULL COMMENT 'xxx',
  `device_id` varchar(128) NOT NULL COMMENT 'xxxx',
  `voucher_number` tinyint(4) NOT NULL COMMENT 'xxx',
  `created_at` datetime NOT NULL COMMENT '创建时间',
  `updated_at` datetime NOT NULL COMMENT '更新时间',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '0:正常;1禁用;2:已删除;3:xx',
  `renew` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'xxxx',
  `priority` int(5) NOT NULL DEFAULT '0' COMMENT '优先级',
  `cate` int(5) NOT NULL DEFAULT '0' COMMENT 'xxxxx',
  PRIMARY KEY (`id`),
  KEY `device_id` (`device_id`),
  KEY `idx_user_uuid` (`user_uuid`,`vip_end_time`),
  KEY `idx_order_uuid` (`order_uuid`),
  KEY `union_vip_time_vip_id_created_index_101` (`vip_begin_time`,`vip_end_time`,`vip_id`,`created_at`),
  KEY `union_vip_time_cate_user_uuid_index_101` (`created_at`,`vip_end_time`,`vip_begin_time`,`cate`,`user_uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=193387999

CREATE TABLE `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `name` varchar(128) NOT NULL,
  `days` int(11) NOT NULL,
  `kind` int(11) NOT NULL,
  `price` int(11) NOT NULL,
  `cate` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `show` int(11) NOT NULL,
  `vip_id` int(11) DEFAULT NULL,
  `pid_alias` varchar(64) DEFAULT '' COMMENT 'xxx',
  `mark` varchar(128) DEFAULT NULL,
  `mark_weight` int(11) NOT NULL,
  `operator_type` int(11) NOT NULL,
  `sync_sid` varchar(128) DEFAULT NULL COMMENT 'xxxx',
  `join_at` datetime NOT NULL,
  `show_price` int(11) NOT NULL,
  `promotion` varchar(128) DEFAULT NULL,
  `ct_json_stored` varchar(512) DEFAULT NULL,
  `renew` tinyint(3) unsigned DEFAULT '0' COMMENT '0 xx 1 xxx',
  `single_sale` int(11) DEFAULT NULL COMMENT 'xx,单位：折',
  `pay_channel` varchar(256) DEFAULT '' COMMENT 'xxx',
  `client_type` tinyint(1) unsigned DEFAULT '1' COMMENT 'xxxx',
  `location` tinyint(1) unsigned DEFAULT NULL COMMENT '显示位置',
  `invoker` varchar(255) DEFAULT NULL COMMENT 'xxxx',
  `pay_channel_black` varchar(255) DEFAULT NULL COMMENT 'xxxx',
  `ott_product_id` int(11) unsigned DEFAULT NULL COMMENT 'xxxx',
  `vip_discount` tinyint(1) unsigned DEFAULT '0' COMMENT 'xxxx',
  `settle_price` int(6) unsigned DEFAULT '0' COMMENT '结算价格',
  `black_version` varchar(1024) NOT NULL DEFAULT '' COMMENT 'xxx',
  `up_uuid` varchar(64) NOT NULL DEFAULT '' COMMENT 'xxxx',
  `renew_pid` int(11) unsigned NOT NULL DEFAULT '0' COMMENT 'xxx',
  `prod_set_id` int(11) NOT NULL DEFAULT '0' COMMENT 'xxxx',
  `renew_before_days` int(11) NOT NULL DEFAULT '0' COMMENT 'xxxx',
  `first_level` varchar(64) NOT NULL DEFAULT '' COMMENT 'xxxx',
  `limit_cnt` int(11) NOT NULL DEFAULT '0' COMMENT '限制数量,xx',
  `phone_price` int(11) NOT NULL DEFAULT '0' COMMENT 'xxx',
  `service_type_id` int(11) NOT NULL DEFAULT '0' COMMENT '产品所属服务类ID,xxxxxx',
  PRIMARY KEY (`id`),
  KEY `product_4da47e07` (`name`),
  KEY `product_21ec032f` (`kind`),
  KEY `product_063d78c2` (`vip_id`),
  KEY `client_type` (`client_type`),
  KEY `idx_service_type` (`service_type_id`),
  KEY `union_client_type_cate_renew_vip_id_101` (`cate`,`client_type`,`renew`,`vip_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=360033

  CREATE TABLE `vip_growth` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `user_uuid` char(32) NOT NULL DEFAULT '' COMMENT '用户uuid',
  `score` int(11) NOT NULL DEFAULT '0' COMMENT 'xx',
  `level` int(4) NOT NULL DEFAULT '0' COMMENT 'xxx',
  `update_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '更新时间',
  `upgrade_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '最近升级日期',
  `degrade_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '最近降级日期',
  `daily_update_time` datetime NOT NULL DEFAULT '1970-01-01 08:00:00' COMMENT '日常更新时间',
  `status` tinyint(1) NOT NULL DEFAULT '0' COMMENT '状态(0:有效;1:删除)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_uuid` (`user_uuid`),
  KEY `idx_upgrade_degrade` (`upgrade_time`,`degrade_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=54901620 COMMENT='xxx'

 CREATE TABLE `order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `uuid` varchar(255) NOT NULL,
  `channel_id` int(11) NOT NULL,
  `business_id` int(11) NOT NULL,
  `platform_id` int(11) NOT NULL,
  `status` int(11) NOT NULL,
  `paid_at` datetime DEFAULT NULL,
  `amount` int(11) NOT NULL,
  `account_id` int(11) NOT NULL,
  `relation_order_id` int(11) DEFAULT NULL,
  `version` varchar(255) DEFAULT NULL,
  `mac` varchar(255) DEFAULT NULL,
  `uip` char(56) DEFAULT NULL,
  `voucher_id` int(11) NOT NULL DEFAULT '0' COMMENT 'xxx',
  `voucher_amount` int(11) NOT NULL DEFAULT '0' COMMENT 'xxx',
  `cxid` char(64) DEFAULT NULL COMMENT 'xxx',
  `price` int(11) unsigned DEFAULT '0' COMMENT 'xxx',
  `is_test` tinyint(1) unsigned DEFAULT '0' COMMENT 'xxx',
  `source_uuid` char(32) NOT NULL DEFAULT '' COMMENT 'xxxx',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `order_9e85bf2d` (`channel_id`),
  KEY `order_e3d75fef` (`platform_id`),
  KEY `order_93025c2f` (`account_id`),
  KEY `union_paid_at_updated_at_channel_id_platform_101_index` (`paid_at`,`updated_at`,`channel_id`,`platform_id`),
  KEY `idx_created_at` (`created_at`),
  KEY `union_updated_at_channel_id_platform_101_index` (`updated_at`,`channel_id`,`platform_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=466511263

**Comment by lamxTyler** [comment]
@beebol I think it is a fixed problem. Could you try the latest master or 3.0 rc2?

**Comment by beebol** [comment]
@lamxTyler Do you have a detailed description of this problem? Upgraded to the latest version（v3.0.0-rc.2）.
$ ./tidb-server -V
Release Version: v3.0.0-rc.2
Git Commit Hash: 06f3f63d5a87e7f0436c0618cf524fea7172eb93
Git Branch: HEAD
UTC Build Time: 2019-05-28 12:48:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by lamxTyler** [comment]
@beebol Is the problem fixed?

**Comment by beebol** [comment]
@lamxTyler  It needs to be tested, because this problem is not inevitable.

**Comment by lamxTyler** [comment]
@beebol Have you tested it?

**Comment by beebol** [comment]
@lamxTyler It's been tested and there's no further problem. 3Q!

**Comment by beebol** [comment]
@lamxTyler A new problem. 
SQL:
select o.account_id,sum(o.amount),sum(if(c.open_type = 1,o.amount,0)),sum(if(c.open_type = 1,1,0)),sum(if(c.open_type != 1,o.amount,0)),sum(if(c.open_type != 1,1,0))
                         from `order` o left join invoice i on i.order_id = o.id left join product p on i.product_id = p.id  
                         left join channel c on c.id = o.channel_id  where o.account_id = 134139663 and i.end_time >=  '2019-06-07'  and  i.delivered_at >= '2019-05-05 13:01:48' and  i.delivered_at < '2019-06-07'  and p.cate =1 and i.status =1 and c.open_type in (1,2,3)

Error:
(1105, "inconsistent index order_93025c2f handle count 31 isn't equal to value count 30")

**Comment by jackysp** [comment]
Hi @beebol,
Could you please execute `admin check index order order_93025c2f`?

**Comment by beebol** [comment]
@jackysp 
mysql> admin check index `order` order_93025c2f;
Query OK, 0 rows affected (17 min 38.66 sec)

**Comment by jackysp** [comment]
Does this error still occur? @beebol 
Could you plz provide the explain results of

```sql
explain select o.account_id,sum(o.amount),sum(if(c.open_type = 1,o.amount,0)),sum(if(c.open_type = 1,1,0)),sum(if(c.open_type != 1,o.amount,0)),sum(if(c.open_type != 1,1,0))
from order o left join invoice i on i.order_id = o.id left join product p on i.product_id = p.id
left join channel c on c.id = o.channel_id where o.account_id = 134139663 and i.end_time >= '2019-06-07' and i.delivered_at >= '2019-05-05 13:01:48' and i.delivered_at < '2019-06-07' and p.cate =1 and i.status =1 and c.open_type in (1,2,3)
```

**Comment by jackysp** [comment]
Friendly ping @beebol .

**Comment by beebol** [comment]
@jackysp i'm still testing.
+----------------------------------------+-----------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_11                          | 1.00      | root | boss.o.account_id, 9_col_0, 9_col_1, 9_col_2, 9_col_3, 9_col_4                                                                                                                                                                     |
| └─StreamAgg_16                     | 1.00      | root | funcs:sum(col_0), sum(col_1), sum(col_2), sum(col_3), sum(col_4), firstrow(col_5)                                                                                                                                                  |
|   └─Projection_138                 | 65.51     | root | cast(boss.o.amount), cast(if(eq(boss.c.open_type, 1), boss.o.amount, 0)), cast(if(eq(boss.c.open_type, 1), 1, 0)), cast(if(ne(boss.c.open_type, 1), boss.o.amount, 0)), cast(if(ne(boss.c.open_type, 1), 1, 0)), boss.o.account_id |
|     └─HashLeftJoin_136             | 65.51     | root | inner join, inner:IndexReader_130, equal:[eq(boss.o.channel_id, boss.c.id)]                                                                                                                                                        |
|       ├─IndexJoin_51               | 72.07     | root | inner join, inner:TableReader_50, outer key:boss.i.product_id, inner key:boss.p.id                                                                                                                                                 |
|       │ ├─IndexJoin_78           | 72.07     | root | inner join, inner:IndexLookUp_77, outer key:boss.o.id, inner key:boss.i.order_id                                                                                                                                                   |
|       │ │ ├─IndexLookUp_98     | 71.94     | root |                                                                                                                                                                                                                                    |
|       │ │ │ ├─IndexScan_96   | 71.94     | cop  | table:o, index:account_id, range:[134139663,134139663], keep order:false                                                                                                                                                           |
|       │ │ │ └─TableScan_97   | 71.94     | cop  | table:order, keep order:false                                                                                                                                                                                                      |
|       │ │ └─IndexLookUp_77     | 213658.17 | root |                                                                                                                                                                                                                                    |
|       │ │   ├─Selection_75     | 0.00      | cop  | not(isnull(boss.i.order_id))                                                                                                                                                                                                       |
|       │ │   │ └─IndexScan_73 | 1.00      | cop  | table:i, index:status, order_id, range: decided by [eq(boss.i.order_id, boss.o.id) eq(boss.i.status, 1)], keep order:false                                                                                                         |
|       │ │   └─Selection_76     | 213658.17 | cop  | ge(boss.i.delivered_at, 2019-05-05 13:01:48.000000), ge(boss.i.end_time, 2019-06-07 00:00:00.000000), lt(boss.i.delivered_at, 2019-06-07 00:00:00.000000), not(isnull(boss.i.product_id))                                          |
|       │ │     └─TableScan_74   | 0.00      | cop  | table:invoice, keep order:false, stats:pseudo                                                                                                                                                                                      |
|       │ └─TableReader_50         | 0.80      | root | data:Selection_49                                                                                                                                                                                                                  |
|       │   └─Selection_49         | 0.80      | cop  | eq(boss.p.cate, 1), not(isnull(boss.p.id))                                                                                                                                                                                         |
|       │     └─TableScan_48       | 1.00      | cop  | table:p, range: decided by [boss.i.product_id], keep order:false                                                                                                                                                                   |
|       └─IndexReader_130            | 0.91      | root | index:Selection_129                                                                                                                                                                                                                |
|         └─Selection_129            | 0.91      | cop  | not(isnull(boss.c.id))                                                                                                                                                                                                             |
|           └─IndexScan_128          | 0.91      | cop  | table:c, index:open_type, client_type, renew, range:[1,1], [2,2], [3,3], keep order:false, stats:pseudo                                                                                                                            |
+----------------------------------------+-----------+------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
20 rows in set (0.01 sec)

**Comment by beebol** [comment]
@jackysp This query can be queried normally through the console.

**Comment by jackysp** [comment]
@qw4990 PTAL

**Comment by jackysp** [comment]
@beebol , do you delete the data of this `order` table at the same time? Then, after discovering the problem, have you restarted tikv?

**Comment by beebol** [comment]
@jackysp It is possible to delete data from this order table at the same time.  (mysql->DM-TIDB)  .

 No restarted tikv, but expansion before this problem.

**Comment by jackysp** [comment]
Have you changed the gc life time? Please take a look at the result of `select * from mysql.tidb where variable_name='tikv_gc_life_time'`. For your convenience, please leave your WeChat account, we could contact on WeChat. @beebol

**Comment by beebol** [comment]
@jackysp  WeChat: itopers
mysql> select * from mysql.tidb where variable_name='tikv_gc_life_time';
+-------------------+----------------+----------------------------------------------------------------------------------------+
| VARIABLE_NAME     | VARIABLE_VALUE | COMMENT                                                                                |
+-------------------+----------------+----------------------------------------------------------------------------------------+
| tikv_gc_life_time | 10m0s          | All versions within life time will not be collected by GC, at least 10m, in Go format. |
+-------------------+----------------+----------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by jackysp** [comment]
Hi @beebol , https://github.com/pingcap/tidb/pull/10927 will fix this bug. Thanks for your report!
