### ISSUE TITLE
unsupported modify column %!s(ast.ColumnOptionType=12)

### ISSUE THREAD

**Issue by Mingdr** [pingcap/tidb#10731]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`CREATE TABLE `t1` (
  b char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ;

ALTER TABLE t1  MODIFY COLUMN b char(1) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci ;`

2. What did you expect to see?

3. What did you see instead?

unsupported modify column %!s(ast.ColumnOptionType=12)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.0.0-rc.2
Git Commit Hash: 06f3f63d5a87e7f0436c0618cf524fea7172eb93
Git Branch: HEAD
UTC Build Time: 2019-05-28 12:48:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

I would got the error when I used COLLATE.

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @crazycs520
