### ISSUE TITLE
when does disk usage release

### ISSUE THREAD

**Issue by Still4** [pingcap/tidb#10744]
## Performance Questions

- What version of TiDB are you using?
 Release Version: v2.1.11
Git Commit Hash: 5ea2830cd7793b166d811d0a65a9c618296cd963
Git Branch: HEAD
UTC Build Time: 2019-06-03 09:17:59
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

- What's the observed and your expected performance respectively?
 
From Grafana I see such disk usage performance 

start execute sql analyze table xxx;
<img width="472" alt="image" src="https://user-images.githubusercontent.com/13746605/59169168-afe08800-8b6b-11e9-84bd-d65ecdf13ac8.png">

start execute sql alter table xxx add index;
<img width="503" alt="image" src="https://user-images.githubusercontent.com/13746605/59169176-bc64e080-8b6b-11e9-8b62-869006cb48c7.png">

start execute sql alter table xxx drop index;
<img width="522" alt="image" src="https://user-images.githubusercontent.com/13746605/59169188-c8e93900-8b6b-11e9-85cd-e30321e9718b.png">

I'm a little confused here, from drop index we see disk released very quickly, why does analyze table released over 240G disk?
I thought disk usage might be released every few hours, each time not too much, not like this, and also will this effect snapshot versions ?

**Comment by jackysp** [comment]
Analyze will not release space, look at monitoring, the total amount of data before the analyze is generally rising, may produce a large number of old versions at this time. TiDB internally has a gc mechanism to periodically recycle old data, and it needs to be combined with rocksdb's compaction to free space. I think the analyze which free the space is just a coincidence.
See our documents for gc here, https://pingcap.com/docs/dev/reference/garbage-collection/#tidb-garbage-collection-gc .

**Comment by Still4** [comment]
thanks for the answer, we insert and delete multiple summary data every day, seems some deleted data didn't gc correctly 

<img width="463" alt="image" src="https://user-images.githubusercontent.com/13746605/59187682-901b8500-8ba8-11e9-8f98-32b809e888b7.png">

another question, why didn't we run auto analyze, seems config is correct
mysql> show variables where name like '%analyze%';    
+------------------------------+-------------+
| Variable_name                | Value       |
+------------------------------+-------------+
| tidb_auto_analyze_start_time | 00:00 +0000 | 
| tidb_auto_analyze_ratio      | 0.5         | 
| tidb_auto_analyze_end_time   | 23:59 +0000 | 
+------------------------------+-------------+

should we set tidb_auto_analyze_ratio as a globle variable?

**Comment by jackysp** [comment]
We've improved our implementation of GC, I think that worked.
For the second question, these three variables are all global scope's ones. Maybe the stats healthy is still higher than 0.5.

**Comment by Still4** [comment]
some table healthy is already 0, we even have 2 tables without info in INFORMATION_SCHEMA.TABLES, this shouldn't be right.

I read source code
`	sql := fmt.Sprintf("select variable_name, variable_value from mysql.global_variables where variable_name in ('%s', '%s', '%s')",
		variable.TiDBAutoAnalyzeRatio, variable.TiDBAutoAnalyzeStartTime, variable.TiDBAutoAnalyzeEndTime)
`
but turns out they are gone.

mysql> select variable_name, variable_value from mysql.global_variables where variable_name = 'tidb_auto_analyze_ratio';  
Empty set (0.00 sec)

mysql> select count(1) from mysql.global_variables;
+----------+
| count(1) |
+----------+
|      498 | 
+----------+

mysql> show global variables;
...
560 rows in set (0.01 sec)

seems not right, is there a switch can sync these configs?

**Comment by jackysp** [comment]
@lamxTyler please take a look at the stats issue.
For the global_variables issue, thanks for your report!
I'm curious about the missing tables in INFORMATION_SCHEMA.TABLES, could you please show more info?

**Comment by Still4** [comment]
actually it's stats_meta missing, my bad

mysql> SHOW STATS_META WHERE Db_name LIKE 'bi_raw_wow%';      
+------------+-------------------------+---------------------+--------------+-----------+
| Db_name    | Table_name              | Update_time         | Modify_count | Row_count |
+------------+-------------------------+---------------------+--------------+-----------+
| bi_raw_wow | user_relogin            | 2019-05-30 01:55:14 |          346 |       346 | 
| bi_raw_wow | user_link               | 2019-05-30 02:00:43 |         5969 |     82905 | 
| bi_raw_wow | device_link             | 2019-05-27 01:15:14 |         6006 |    163039 | 
| bi_raw_wow | fb_campaign_ua          | 2019-04-16 10:57:19 |          256 |       256 | 
| bi_raw_wow | user_attribution        | 2019-05-30 02:57:35 |          884 |     82877 | 
| bi_raw_wow | bi_event                | 2018-08-17 02:56:05 |            0 |         0 | 
| bi_raw_wow | install                 | 2019-04-19 18:04:09 |            0 |     57597 | 
| bi_raw_wow | install_lastclick_cheat | 2018-10-30 06:35:19 |            0 |         0 | 
| bi_raw_wow | install_reyun           | 2018-08-17 02:56:10 |            0 |         0 | 
| bi_raw_wow | retargeting             | 2019-04-08 09:42:11 |          894 |         0 | 
| bi_raw_wow | uac_tracking_log        | 2018-08-17 02:56:14 |            0 |         0 | 
| bi_raw_wow | user_event              | 2018-08-17 02:56:16 |            0 |         0 | 
| bi_raw_wow | user_event_google       | 2018-08-17 02:56:17 |            0 |         0 | 
| bi_raw_wow | user_pay                | 2019-05-30 02:57:29 |          265 |      4138 | 
| bi_raw_wow | user_profile            | 2019-06-04 11:59:19 |          963 |     82908 | 
| bi_raw_wow | user_register           | 2019-05-28 23:05:14 |         1386 |     82893 | 
| bi_raw_wow | user_retargeting        | 2019-02-13 07:42:40 |          967 |         0 | 
| bi_raw_wow | user_source             | 2019-02-21 11:21:15 |            0 |     57267 | 
| bi_raw_wow | user_source_google      | 2018-08-17 02:56:25 |            0 |         0 | 
| bi_raw_wow | organic_install         | 2019-05-30 01:57:27 |         1219 |     21207 | 
| bi_raw_wow | user_arab_pay           | 2018-11-29 11:38:38 |            0 |         0 | 
| bi_raw_wow | user_login              | 2019-06-08 14:35:41 |            0 |    532615 | 
+------------+-------------------------+---------------------+--------------+-----------+
22 rows in set (0.01 sec)

mysql> SHOW TABLES;
+-------------------------+
| Tables_in_bi_raw_wow    |
+-------------------------+
| bi_event                | 
| device_link             | 
| fb_campaign_ua          | 
| install                 | 
| install_lastclick_cheat | 
| install_reyun           | 
| organic_install         | 
| retargeting             | 
| uac_tracking_log        | 
| user_arab_pay           | 
| user_attribution        | 
| user_event              | 
| user_event_google       | 
| user_firstpay           | 
| user_link               | 
| user_login              | 
| user_pay                | 
| user_profile            | 
| user_register           | 
| user_relogin            | 
| user_retargeting        | 
| user_source             | 
| user_source_google      | 
+-------------------------+
23 rows in set (0.00 sec)

table user_firstpay has no stats info, looks like the same problem.

**Comment by jackysp** [comment]
PTAL @lamxTyler

**Comment by lamxTyler** [comment]
@Still4 Tables not in `stats_meta` means that they do not have stats created. You can just analyze the table. Only tables with more than 1000 rows will be auto analyzed, you can check their table rows.

**Comment by Still4** [comment]
@lamxTyler 
mysql> use bi_raw_wow;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select count(1) from user_firstpay;
+----------+
| count(1) |
+----------+
|     1170 | 
+----------+
1 row in set (0.02 sec)

and data in this table hasn't been modified for a few months.

I don't think auto analyze jobs run correctly, please see above.

**Comment by lamxTyler** [comment]
@Still4 TiDB uses info in the `stats meta` to determine if it is needed to auto analyze, not the `select count(*)`. To check if the auto analyze is running, just refer to the `statistics` panel in the grafana.

**Comment by Still4** [comment]
@lamxTyler How about tables don't have stats meta, if stats are not collected, TiDB will not know this table has over 1000 rows right? so auto analyze will never run on these tables right?
I just don't understand why some tables has stats meta while some don't, these tables were created on Aug 2018, maybe some errors already have been fixed I suppose?
And for statistics panel in the grafana, could you give me a sceenshot please, I just can't find it.
