### ISSUE TITLE
Data Lost in tidb3.0

### ISSUE THREAD

**Issue by DBKent** [pingcap/tidb#10752]
HI, when i use this sql:
 insert into B.test  select * from A.test ;

it happen: transaction too large, len:300001
so i set @@session.tidb_batch_insert=1;
and success to insert.
but when i insert finished,then  data in A.test is lost... 

my tidb Version: v3.0.0-rc.1-114-gcc74145ff

**Comment by jackysp** [comment]
The source data are lost after insert finished? @DBKent 
Could you please give us a reproducible case for it?

**Comment by DBKent** [comment]
@jackysp Yes,the source are lost after insert  finished a few minute later.
I do it again ,it still lost after insert finished.

**Comment by DBKent** [comment]
@jackysp 
And i try insert into B.test select **one row** from A.test;
so i diden't set @@session.tidb_batch_insert=1;
after insert ,my source data isn't lost.

**Comment by jackysp** [comment]
I've tried your case, but cannot reproduce it. @DBKent 
My case as below,
```sql
mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
|   327680 |
+----------+
1 row in set (3.91 sec)

mysql> use test2;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> truncate table t;
Query OK, 0 rows affected (0.02 sec)

mysql> set tidb_batch_insert = on;
Query OK, 0 rows affected (0.00 sec)

mysql> set @@session.tidb_batch_insert=1;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into test2.t select * from test.t;
Query OK, 327680 rows affected (18.08 sec)
Records: 327680  Duplicates: 0  Warnings: 0

mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select count(*) from t;
+----------+
| count(*) |
+----------+
|   327680 |
+----------+
1 row in set (4.22 sec)
```
Could you please provide a reproducible case for it?

**Comment by DBKent** [comment]
HI, @jackysp  I think i find the problem.
i use create table like . and find it  link source data like:

mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|   641917 |
+----------+
1 row in set (0.19 sec)

mysql> create table test2.t like test.t;
Query OK, 0 rows affected (0.09 sec)

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|   641917 |
+----------+
1 row in set (0.21 sec)

i just create like table ,and the new table have source data
Now, i delete new table data limit 1, the source data also be deleted.

mysql> delete from test2.t limit 1;
Query OK, 1 row affected (2.02 sec)

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|   641916 |
+----------+
1 row in set (0.19 sec)

mysql> select count(1) from test.t;
+----------+
| count(1) |
+----------+
|   641916 |
+----------+
1 row in set (0.19 sec)

And I truncate new table, source data also be truncated few minute later.
mysql> truncate table test2.t;
Query OK, 0 rows affected (0.17 sec)

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

-- about 5 minute later --

mysql> select count(1) from test.t;
+----------+
| count(1) |
+----------+
|        0 |
+----------+
1 row in set (0.01 sec)

**Comment by jackysp** [comment]
Can not reproduce it in this way. `create table like` creates a new empty table, and does not link the data.
```
mysql> create table test2.t like test.t;
Query OK, 0 rows affected (0.01 sec)

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|        0 |
+----------+
1 row in set (0.01 sec)

mysql> select count(1) from test.t;
+----------+
| count(1) |
+----------+
|   327680 |
+----------+
1 row in set (7.09 sec)

mysql> set tidb_batch_insert = on;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into test2.t select * from test.t;
Query OK, 327680 rows affected (22.94 sec)
Records: 327680  Duplicates: 0  Warnings: 0

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|   327680 |
+----------+
1 row in set (5.19 sec)

mysql> select count(1) from test.t;
+----------+
| count(1) |
+----------+
|   327680 |
+----------+
1 row in set (4.29 sec)

mysql> delete from test2.t limit 1;
Query OK, 1 row affected (0.01 sec)

mysql> select count(1) from test2.t;
+----------+
| count(1) |
+----------+
|   327679 |
+----------+
1 row in set (4.42 sec)

mysql> select count(1) from test.t;
+----------+
| count(1) |
+----------+
|   327680 |
+----------+
1 row in set (4.26 sec)
```

**Comment by jackysp** [comment]
Seems the question is not about batch insert. So I think it is easy to reproduce it with a new table with few rows in it. 
btw: It seems you're using a binary from an non-release tag as your tidb-server, do you use the tikv server as your storage nodes? What's the tikv version of your cluster?

**Comment by DBKent** [comment]
yah,is not about batch insert, is about why i creat table like  have data...
@jackysp , i'm not using a binary . I use ansible : https://pingcap.com/docs-cn/dev/how-to/deploy/orchestrated/offline-ansible/
I have 5 nodes:
1 db
1 pd
3 kv
My tikv version:TiKV 3.0.0-beta.1

**Comment by jackysp** [comment]
Do you have a wechat account? We could discuss it on wechat with our developers of ddl team.

**Comment by DBKent** [comment]
ok my account id :kentchen

**Comment by DBKent** [comment]
> CREATE TABLE `y` (
>   `RoundDate` date NOT NULL,
>   `UserID` int(10) unsigned NOT NULL DEFAULT '0',
>   `Username` varchar(30) DEFAULT NULL,
>   `AGID` int(10) unsigned NOT NULL DEFAULT '0',
>   `Type` smallint(5) unsigned NOT NULL DEFAULT '0',
>   `Cu` varchar(6) NOT NULL DEFAULT 'RMB',
>   `ExchangeRate` decimal(9,6) unsigned NOT NULL DEFAULT '0.000000',
>   `HallID` int(10) unsigned NOT NULL DEFAULT '0',
>   `XXID` int(10) unsigned NOT NULL DEFAULT '0',
>   `YYID` int(10) unsigned NOT NULL DEFAULT '0',
>   `ZZID` int(10) unsigned NOT NULL DEFAULT '0',
>   `XXTotal` int(10) unsigned NOT NULL DEFAULT '0',
>   `BetYY` decimal(16,4) unsigned NOT NULL DEFAULT '0.0000',
>   `Commissionable` decimal(16,4) unsigned NOT NULL DEFAULT '0.0000',
>   `Commission` decimal(16,4) unsigned NOT NULL DEFAULT '0.0000',
>   `PXX` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SSAmount` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `CCAmount` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SAmount` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `AGAmount` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SCHolding` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `COHolding` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SAHolding` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `AGHolding` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SCHngJP` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `COHgJP` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SAHdingJP` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `AGHngJP` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SCmm` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `COmm` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `SAmm` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `AGComm` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `MEomm` decimal(16,4) NOT NULL DEFAULT '0.0000',
>   `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
>   `Platform` tinyint(3) unsigned NOT NULL DEFAULT '0',
>   `Client` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '術',
>   `Portal` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '入口',
>   PRIMARY KEY (`ID`,`RoundDate`),
>   KEY `AGID` (`AGID`),
>   KEY `XXID` (`XXID`),
>   KEY `YYID` (`YYID`),
>   KEY `ZZID` (`ZZID`),
>   KEY `HallID` (`HallID`),
>   KEY `RoundDate` (`RoundDate`,`UserID`,`GameType`),
>   KEY `UserID` (`UserID`,`RoundDate`,`HallID`),
>   KEY `GameType` (`GameType`,`RoundDate`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
> PARTITION BY RANGE COLUMNS(rounddate) (
>   PARTITION p201901 VALUES LESS THAN ("2019-02-01"),
>   PARTITION p201902 VALUES LESS THAN ("2019-03-01"),
>   PARTITION p201903 VALUES LESS THAN ("2019-04-01"),
>   PARTITION p201904 VALUES LESS THAN ("2019-05-01"),
>   PARTITION p201905 VALUES LESS THAN ("2019-06-01"),
>   PARTITION p201906 VALUES LESS THAN ("2019-07-01"),
>   PARTITION p201907 VALUES LESS THAN ("2019-08-01"),
>   PARTITION p201908 VALUES LESS THAN ("2019-09-01"),
>   PARTITION p201909 VALUES LESS THAN ("2019-10-01"),
>   PARTITION p201910 VALUES LESS THAN ("2019-11-01"),
>   PARTITION p201911 VALUES LESS THAN ("2019-12-01"),
>   PARTITION p201912 VALUES LESS THAN ("2020-01-01"),
>   PARTITION others VALUES LESS THAN (MAXVALUE)
> ) 
附上table schema  只有更動 名字，型態沒變

**Comment by jackysp** [comment]
I'm afraid it is an issue about partition table.

**Comment by DBKent** [comment]
i think so ...

**Comment by jackysp** [comment]
I've reproduced it. @DBKent 
```sql
mysql> set tidb_enable_table_partition=on;
Query OK, 0 rows affected (0.00 sec)

mysql> create table t (i int) partition by range columns (i) (partition p0 values less than (10));                                                                                                                                                                                                                         
Query OK, 0 rows affected (0.08 sec)

mysql> insert into t values (1),(2),(3),(4);                                                                                                                                                                                                                                                                               
Query OK, 4 rows affected (0.02 sec)
Records: 4  Duplicates: 0  Warnings: 0

mysql> create table test2.t like test.t;
Query OK, 0 rows affected (0.07 sec)

mysql> select * from test2.t;
+------+
| i    |
+------+
|    1 |
|    2 |
|    3 |
|    4 |
+------+
4 rows in set (0.00 sec)
```
PTAL @tiancaiamao
