### ISSUE TITLE
config tikv.yml error ?

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#10751]
fatal: [tikv1]: FAILED! => {"ansible_facts": {"tikv_conf_custom": {}}, "ansible_included_var_files": [], "changed": false, "message": "Syntax Error while loading YAML.\n  expected <block end>, but found '<block mapping start>'\n\nThe error appears to have been in '/home/tidb/tidb-ansible/conf/tikv.yml': line 22, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n   compaction-readahead-size: \"2MB\"\n  defaultcf:\n  ^ here\n"}

tikv.yml

global:
  # log level: trace, debug, info, warn, error, off.
  # log-level: "info"

readpool:
  storage:
  coprocessor:

server:
   grpc-concurrency: 8
   grpc-raft-conn-num: 24

storage:
pd:
metric:
coprocessor:
rocksdb:
   compaction-readahead-size: "2MB"
  defaultcf:
     compression-per-level: ["lz4", "lz4", "lz4", "lz4", "lz4", "zstd", "zstd"]
  writecf:
     block-cache-size: "2G"
  lockcf:

raftdb:
  defaultcf:
     block-cache-size: "512MB"

security:

import:

**Comment by jackysp** [comment]
I think it is already showing the reason `Syntax Error while loading YAML`, @shenlijungg 
PTAL @liubo0127

**Comment by liubo0127** [comment]
Please send the `/home/tidb/tidb-ansible/conf/tikv.yml` file when the error occurs. I suspect that the format of the configuration file has been modified incorrectly.

**Comment by shenlijungg** [comment]
@liubo0127 
https://github.com/shenlijungg/tidb/blob/master/tikv.yml
