### ISSUE TITLE
tidb  start failed!

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#10754]
2019/06/10 18:53:19.811 tidb.go:64: [info] store tikv-6554270889113038470 new domain, ddl lease 45s, stats lease 3000000000
2019/06/10 18:53:19.813 ddl.go:289: [info] [ddl] start delRangeManager OK, with emulator: false
2019/06/10 18:53:19.817 ddl.go:297: [info] [ddl] start DDL:793059f9-ac5e-445d-a443-2ee249b430f9
2019/06/10 18:53:19.818 ddl_worker.go:71: [info] [ddl] cleaning jobs in the adding index queue finished.
2019/06/10 18:53:19.830 manager.go:269: [info] [ddl] /tidb/ddl/fg/owner ownerManager 793059f9-ac5e-445d-a443-2ee249b430f9, owner is 793059f9-ac5e-445d-a443-2ee249b430f9
2019/06/10 18:53:19.925 domain.go:86: [info] [ddl] not update self schema version to etcd
2019/06/10 18:53:19.925 manager.go:234: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 793059f9-ac5e-445d-a443-2ee249b430f9 isn't the owner
2019/06/10 18:53:19.929 manager.go:245: [info] [ddl] /tidb/ddl/fg/owner ownerManager 793059f9-ac5e-445d-a443-2ee249b430f9 break campaign loop, revoke err <nil>
2019/06/10 18:53:19.929 delete_range.go:105: [info] [ddl] closing delRange session pool
2019/06/10 18:53:19.929 ddl.go:344: [info] close DDL:793059f9-ac5e-445d-a443-2ee249b430f9
2019/06/10 18:53:19.929 ddl.go:307: [info] stop DDL:793059f9-ac5e-445d-a443-2ee249b430f9
2019/06/10 18:53:19.929 tidb.go:72: [error] [ddl] init domain failed line 1 column 50 near " "\"", 1)" (total length 59)
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/tables/gen_expr.go:72: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/tables/tables.go:93: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/infoschema/builder.go:280: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/infoschema/builder.go:257: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:115: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:304: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:498: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/tidb.go:72: 
2019/06/10 18:53:20.930 tidb.go:64: [info] store tikv-6554270889113038470 new domain, ddl lease 45s, stats lease 3000000000
2019/06/10 18:53:20.931 ddl.go:289: [info] [ddl] start delRangeManager OK, with emulator: false
2019/06/10 18:53:20.935 ddl.go:297: [info] [ddl] start DDL:0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf
2019/06/10 18:53:20.936 ddl_worker.go:71: [info] [ddl] cleaning jobs in the adding index queue finished.
2019/06/10 18:53:20.945 manager.go:269: [info] [ddl] /tidb/ddl/fg/owner ownerManager 0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf, owner is 0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf
2019/06/10 18:53:21.043 domain.go:86: [info] [ddl] not update self schema version to etcd
2019/06/10 18:53:21.043 manager.go:234: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf isn't the owner
2019/06/10 18:53:21.047 delete_range.go:105: [info] [ddl] closing delRange session pool
2019/06/10 18:53:21.047 ddl.go:344: [info] close DDL:0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf
2019/06/10 18:53:21.047 ddl.go:307: [info] stop DDL:0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf
2019/06/10 18:53:21.047 manager.go:245: [info] [ddl] /tidb/ddl/fg/owner ownerManager 0ad02c8a-b8b6-4bbc-b6e0-fa20ee8b3acf break campaign loop, revoke err <nil>
2019/06/10 18:53:21.047 tidb.go:72: [error] [ddl] init domain failed line 1 column 50 near " "\"", 1)" (total length 59)
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/tables/gen_expr.go:72: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/tables/tables.go:93: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/infoschema/builder.go:280: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/infoschema/builder.go:257: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:115: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:304: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:498: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/tidb.go:72: 
2019/06/10 18:53:22.548 tidb.go:64: [info] store tikv-6554270889113038470 new domain, ddl lease 45s, stats lease 3000000000
2019/06/10 18:53:22.549 ddl.go:289: [info] [ddl] start delRangeManager OK, with emulator: false
2019/06/10 18:53:22.552 ddl.go:297: [info] [ddl] start DDL:6ec0e729-677e-4c14-8a88-15398978f632
2019/06/10 18:53:22.553 ddl_worker.go:71: [info] [ddl] cleaning jobs in the adding index queue finished.
2019/06/10 18:53:22.563 manager.go:269: [info] [ddl] /tidb/ddl/fg/owner ownerManager 6ec0e729-677e-4c14-8a88-15398978f632, owner is 6ec0e729-677e-4c14-8a88-15398978f632
2019/06/10 18:53:22.650 domain.go:86: [info] [ddl] not update self schema version to etcd
2019/06/10 18:53:22.651 manager.go:234: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 6ec0e729-677e-4c14-8a88-15398978f632 isn't the owner
2019/06/10 18:53:22.651 manager.go:194: [info] [ddl] /tidb/ddl/fg/owner ownerManager 6ec0e729-677e-4c14-8a88-15398978f632 etcd session is done, creates a new one
2019/06/10 18:53:22.651 manager.go:198: [info] [ddl] /tidb/ddl/fg/owner ownerManager 6ec0e729-677e-4c14-8a88-15398978f632 break campaign loop, NewSession err context canceled
2019/06/10 18:53:22.654 delete_range.go:105: [info] [ddl] closing delRange session pool
2019/06/10 18:53:22.654 ddl.go:344: [info] close DDL:6ec0e729-677e-4c14-8a88-15398978f632
2019/06/10 18:53:22.654 ddl.go:307: [info] stop DDL:6ec0e729-677e-4c14-8a88-15398978f632
2019/06/10 18:53:22.655 tidb.go:72: [error] [ddl] init domain failed line 1 column 50 near " "\"", 1)" (total length 59)

**Comment by shenlijungg** [comment]
@jackysp

**Comment by jackysp** [comment]
There is an error here,
```
2019/06/10 18:53:22.655 tidb.go:72: [error] [ddl] init domain failed line 1 column 50 near " """, 1)" (total length 59)
```
Please provide your tidb-server version.

**Comment by shenlijungg** [comment]
@jackysp  tidb_version = v2.0.0

**Comment by shenlijungg** [comment]
@jackysp   非常着急  ，生产启动不起来。请帮忙看看这个是啥错

**Comment by shenlijungg** [comment]
@jackysp 
2019/06/10 19:30:58.263 tidb.go:64: [info] store tikv-6554270889113038470 new domain, ddl lease 45s, stats lease 3000000000
2019/06/10 19:30:58.264 ddl.go:289: [info] [ddl] start delRangeManager OK, with emulator: false
2019/06/10 19:30:58.267 ddl.go:297: [info] [ddl] start DDL:48bf3b5b-f25a-44a1-a07d-118d00637796
2019/06/10 19:30:58.268 ddl_worker.go:71: [info] [ddl] cleaning jobs in the adding index queue finished.
2019/06/10 19:30:58.278 manager.go:269: [info] [ddl] /tidb/ddl/fg/owner ownerManager 48bf3b5b-f25a-44a1-a07d-118d00637796, owner is 48bf3b5b-f25a-44a1-a07d-118d00637796
2019/06/10 19:30:58.366 domain.go:86: [info] [ddl] not update self schema version to etcd
2019/06/10 19:30:58.366 manager.go:234: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 48bf3b5b-f25a-44a1-a07d-118d00637796 isn't the owner
2019/06/10 19:30:58.366 manager.go:194: [info] [ddl] /tidb/ddl/fg/owner ownerManager 48bf3b5b-f25a-44a1-a07d-118d00637796 etcd session is done, creates a new one
2019/06/10 19:30:58.366 manager.go:198: [info] [ddl] /tidb/ddl/fg/owner ownerManager 48bf3b5b-f25a-44a1-a07d-118d00637796 break campaign loop, NewSession err context canceled
2019/06/10 19:30:58.369 delete_range.go:105: [info] [ddl] closing delRange session pool
2019/06/10 19:30:58.369 ddl.go:344: [info] close DDL:48bf3b5b-f25a-44a1-a07d-118d00637796
2019/06/10 19:30:58.369 ddl.go:307: [info] stop DDL:48bf3b5b-f25a-44a1-a07d-118d00637796
2019/06/10 19:30:58.370 tidb.go:72: [error] **[ddl] init domain failed line 1 column 50 near " "\"", 1)" (t**otal length 59)
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/tables/gen_expr.go:72: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/tables/tables.go:93: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/infoschema/builder.go:280: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/infoschema/builder.go:257: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:115: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:304: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/domain/domain.go:498: 
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/tidb.go:72: 
2019/06/10 19:30:58.370 manager.go:245: [info] [ddl] /tidb/ddl/fg/owner ownerManager 48bf3b5b-f25a-44a1-a07d-118d00637796 break campaign loop, revoke err grpc: the client connection is closin

**Comment by tiancaiamao** [comment]
Could you describe what did you do before you meet this error? @shenlijungg

**Comment by lysu** [comment]
@shenlijungg  do you have any running TiDB instance in cluster now? and have any table definition use generated column like this: `CREATE TABLE test_gc_read(a int primary key, b int, c int as ....)` ?

**Comment by shenlijungg** [comment]
@lysu     @tiancaiamao    没有实列在运行，已执行了ansible-playbook  stop.yml。  然后再执行      ansible-playbook  start.yml      tidb 启动不了。

**Comment by jackysp** [comment]
Hi @shenlijungg , do you have a wechat account, maybe we could discuss it on wechat.

**Comment by shenlijungg** [comment]
@jackysp  SH-A-8888
