### ISSUE TITLE
Tidb failed to write binlog sometimes

### ISSUE THREAD

**Issue by alex-lx** [pingcap/tidb#10757]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
We deployed a binlog-cluster for sync data from tidb to Elasticsearch. 

2. What did you expect to see?
The tidb server is always writing binlog successfully.

3. What did you see instead?
It works at most of the times, but sometimes it writes a log `write binlog fail but error ignored` and stops writing binlog anymore. While we didn't find a related log in the pump's and drainer's log.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.2

**Comment by amyangfei** [comment]
hello @alex-lx, before log `write binlog fail but error ignored` there should be another log like `write binlog fail with <pump client error stack>`, could you find it in tidb log?

**Comment by amyangfei** [comment]
besides the `2.1.2` version often raises `no available pump error` when rolling update cluster, you can try to upgrade the cluster to the latest version.
some related pr:
https://github.com/pingcap/tidb-binlog/pull/433
https://github.com/pingcap/tidb-tools/pull/165

**Comment by alex-lx** [comment]
@amyangfei Yes, there's a `no availiable pump` error before it, but we didn't rolling update our cluster(both binlog and tidb) when this error happened.
```
tidb-2019-05-12T11-10-10.983.log-2019/05/11 01:10:05.104 binloginfo.go:114: [error] write binlog fail no avaliable pump to write binlog
tidb-2019-05-12T11-10-10.983.log-github.com/pingcap/tidb-tools/tidb-binlog/pump_client.init
tidb-2019-05-12T11-10-10.983.log-       /Users/alex/Projects/go/pkg/mod/github.com/pingcap/tidb-tools@v2.1.1-0.20181218072513-b2235d442b06+incompatible/tidb-binlog/pump_client/client.go:60
tidb-2019-05-12T11-10-10.983.log-main.init
tidb-2019-05-12T11-10-10.983.log-       <autogenerated>:1
tidb-2019-05-12T11-10-10.983.log-runtime.main
tidb-2019-05-12T11-10-10.983.log-       /usr/local/go/src/runtime/proc.go:189
tidb-2019-05-12T11-10-10.983.log-runtime.goexit
tidb-2019-05-12T11-10-10.983.log-       /usr/local/go/src/runtime/asm_amd64.s:1333
tidb-2019-05-12T11-10-10.983.log:2019/05/11 01:10:05.104 binloginfo.go:116: [error] write binlog fail but error ignored
```

**Comment by amyangfei** [comment]
have you checked the `pump` status using `binlog-ctl` when error happend

**Comment by alex-lx** [comment]
No, we don't know when it would happen. But every time we checked it, it says online.
Here're the recent result.
```

[tidb@jumpserver bin]$ ./binlogctl -pd-urls XXXXXXXXXXX --cmd pumps
INFO[0000] pump: &{NodeID:tidb-tikv06-localdisk:8250 Addr:XXXXXXXXXXX:8250 State:online IsAlive:false Score:0 Label:<nil> MaxCommitTS:409006351232270349 UpdateTS:409006351123218436} 
INFO[0000] pump: &{NodeID:tidb-tikv07-localdisk:8250 Addr:XXXXXXXXXXX:8250 State:online IsAlive:false Score:0 Label:<nil> MaxCommitTS:409006351122169874 UpdateTS:409006351110111234} 
INFO[0000] pump: &{NodeID:tipd00:8250 Addr:XXXXXXXXXXX:8250 State:offline IsAlive:false Score:0 Label:<nil> MaxCommitTS:405899432952594433 UpdateTS:405899433188524070} 
INFO[0000] pump: &{NodeID:tipd01:8250 Addr:XXXXXXXXXXX:8250 State:offline IsAlive:false Score:0 Label:<nil> MaxCommitTS:405898999903813633 UpdateTS:405899000390352899} 
INFO[0000] pump: &{NodeID:tipd02:8250 Addr:XXXXXXXXXXX:8250 State:offline IsAlive:false Score:0 Label:<nil> MaxCommitTS:405899008279314439 UpdateTS:405899008438173697} 
INFO[0000] pump: &{NodeID:tidb-tikv04-localdisk:8250 Addr:XXXXXXXXXXX:8250 State:online IsAlive:false Score:0 Label:<nil> MaxCommitTS:409006350965669895 UpdateTS:409006350861074433} 
INFO[0000] pump: &{NodeID:tidb-tikv05-localdisk:8250 Addr:XXXXXXXXXXX:8250 State:online IsAlive:false Score:0 Label:<nil> MaxCommitTS:409006351253241874 UpdateTS:409006351110111235} 
```
NOTE: the third to fifth pump is offline cause we don't use them any more.

**Comment by amyangfei** [comment]
This error often caused by the following reasons:
1. during `pump cluster` restart, retry time of pump client is slow, and may treat available `pump server` as offline.
2. short time network issue may cause this error.

We have made many improvements in newer version binlog, we suggest you to upgrade cluster to the latest `2.1.x` version.

**Comment by alex-lx** [comment]
Thanks for your advice, and we'd like to try it.
And one more thing to be confirmed: which cluster should be upgraded, tidb, binlog or both?

**Comment by amyangfei** [comment]
both clusters should be upgraded
