### ISSUE TITLE
How to use tidb in beego orm or other golang orms?

### ISSUE THREAD

**Issue by umbrellala** [pingcap/tidb#10767]
Hello! 
I had a api framework written by beego,  and want to change the database from mysql to tidb. In beego's docs, it says that i should import the tidb driver firstly. 
I tried `go get -v github.com/pingcap/tidb` but failed. 
```
# go get -v github.com/pingcap/tidb
can't load package: package github.com/pingcap/tidb: no Go files in /root/go/src/github.com/pingcap/tidb
```

Then I use git to clone this repo, and make it. but it still can't work.
I am confused if these golang orm support tidb actually.
Thank you.

Here is my test code:
```golang
import (
        "encoding/json"
        "github.com/astaxie/beego"
        "github.com/astaxie/beego/orm"
        _ "github.com/pingcap/tidb"
        "time"
)
func main() {
        err := orm.RegisterDriver("tidb", orm.DRTiDB)
        if err!=nil{
                beego.Error("register error",err)
        }
        err := orm.RegisterDataBase("default", "tidb", "root:root@/orm_test?charset=utf-8")
        orm.RegisterModel(new(Task))
        if err != nil {
                beego.Error(err)
        }
}
```

**Comment by lysu** [comment]
@umbrellala TiDB use mysql-protocol, so should try this

```
import (
        "encoding/json"
        "github.com/astaxie/beego"
        "github.com/astaxie/beego/orm"
        _ "github.com/go-sql-driver/mysql"
        "time"
)
func main() {
        err := orm.RegisterDriver("tidb", orm.DRTiDB)
        if err!=nil{
                beego.Error("register error",err)
        }
        err := orm.RegisterDataBase("default", "tidb", "root:root@/orm_test?charset=utf-8")
        orm.RegisterModel(new(Task))
        if err != nil {
                beego.Error(err)
        }
}
```

**Comment by umbrellala** [comment]
> @umbrellala TiDB use mysql-protocol, so should try this
> 
> ```
> import (
>         "encoding/json"
>         "github.com/astaxie/beego"
>         "github.com/astaxie/beego/orm"
>         _ "github.com/go-sql-driver/mysql"
>         "time"
> )
> func main() {
>         err := orm.RegisterDriver("tidb", orm.DRTiDB)
>         if err!=nil{
>                 beego.Error("register error",err)
>         }
>         err := orm.RegisterDataBase("default", "tidb", "root:root@/orm_test?charset=utf-8")
>         orm.RegisterModel(new(Task))
>         if err != nil {
>                 beego.Error(err)
>         }
> }
> ```

Thanks for your advice, but I got error below:
`[ORM]2019/06/11 17:13:44 register db `default`, sql: unknown driver "tidb" (forgotten import?)`
It seems that the tidb driver haven't been registered.

**Comment by lysu** [comment]
hi @umbrellala  after look some beegoo's code

```
import (
	"github.com/astaxie/beego"
	"github.com/astaxie/beego/orm"
	_ "github.com/go-sql-driver/mysql"
)

func main() {
	err := orm.RegisterDriver("mysql", orm.DRMySQL)
	if err!=nil{
		beego.Error("register error",err)
	}
	err = orm.RegisterDataBase("default", "mysql", "root:root@/test?charset=utf8")
	orm.RegisterModel(new(Task))
	if err != nil {
		beego.Error(err)
	}
}
```

we can direct use mysql's driver....it seems `orm.DRMySQL` can not work now, maybe can fire a issue in beego's repo :D

**Comment by umbrellala** [comment]
> hi @umbrellala after look some beegoo's code
> 
> ```
> import (
> 	"github.com/astaxie/beego"
> 	"github.com/astaxie/beego/orm"
> 	_ "github.com/go-sql-driver/mysql"
> )
> 
> func main() {
> 	err := orm.RegisterDriver("mysql", orm.DRMySQL)
> 	if err!=nil{
> 		beego.Error("register error",err)
> 	}
> 	err = orm.RegisterDataBase("default", "mysql", "root:root@/test?charset=utf8")
> 	orm.RegisterModel(new(Task))
> 	if err != nil {
> 		beego.Error(err)
> 	}
> }
> ```
> 
> we can direct use mysql's driver....it seems `orm.DRMySQL` can not work now, maybe can fire a issue in beego's repo :D

I tried to connect to tidb using the very very origin code which used for connecting mysql, and it works! Amazing!
