### ISSUE TITLE
Support for gbk character set

### ISSUE THREAD

**Issue by elitecodegroovy** [pingcap/tidb#10760]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB doesn't support gdk encoding when creating a table.

e.g. 
```
CREATE TABLE Untitled  (
  `ID` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NOT NULL,
  `APP_ID` varchar(50) CHARACTER SET gbk COLLATE gbk_chinese_ci NULL DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE = MyISAM CHARACTER SET = gbk COLLATE = gbk_chinese_ci ROW_FORMAT = Dynamic;
```

**Comment by jackysp** [comment]
Thanks for your attention, @elitecodegroovy !
gbk supports will be on our long-term plan.

**Comment by zimulala** [comment]
For the same problem, see issue https://github.com/pingcap/tidb/issues/26812
