### ISSUE TITLE
In docker. Why did it not take effect after setting the  slow-query-file value?

### ISSUE THREAD

**Issue by sundayha** [pingcap/tidb#10779]
```
tidb_version(): Release Version: v3.0.0-rc.1-172-g3760c63da
Git Commit Hash: 3760c63daba56842e1abb99c14f1b7360920d2f8
Git Branch: master
UTC Build Time: 2019-06-10 09:50:06
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```
use docker compose
```
git clone https://github.com/pingcap/tidb-docker-compose.git

```

```
# Stores slow query log into separated files.
slow-query-file = "/logs/slow-tidb.log"

# Queries with execution time greater than this value will be logged. (Milliseconds)
slow-threshold = 300

Save the changes。docker-compose restart
```

execution time:
```
8117 rows retrieved starting from 1 in 47 s 458 ms (execution: 47 s 366 ms, fetching: 92 ms)
```

```
mysql> admin show slow top 5;
Empty set (0.01 sec)
```
<img width="1504" alt="SQL execution time" src="https://user-images.githubusercontent.com/13161708/59329200-ea3f5600-8d20-11e9-9d90-8c60124c8bb5.png">

<img width="760" alt="" src="https://user-images.githubusercontent.com/13161708/59329895-933a8080-8d22-11e9-84aa-5737e1c4f01b.png">

**Comment by jackysp** [comment]
Thanks for your attention!
@tennix PTAL thanks!

**Comment by tennix** [comment]
The default log level in tidb-docker-compose is `error`, however, slow log is not error log, so it will not output in the log files. To enable slow log, you have to set tidb log level to `info` explictily in the configuration file.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
