### ISSUE TITLE
Tiny improvement about skyline pruning

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#10781]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

In skyline pruning, if we have the following case:
```
where t.a in (1) and t.b > 1 and t.b < 10 order by t.b
```
There're two indexes (a, b) and (b).
Obviously, whatever `ORDER BY t.b` is used or not, (b) is always worse than (a, b).
But currently the skyline pruning in TiDB doesn't prune (b) when `ORDER BY t.b` is considered.

2. What did you expect to see?

Index b is pruned. So that whatever the statistics changed, We always use index (a, b).

3. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

3f4f3d0bd9bbd01ad56880914e1b431bb84080f3

**Comment by francis0407** [comment]
It seems that this issue is also fixed by https://github.com/pingcap/tidb/pull/11749. The reason why it didn't prune (b) is that (a, b) doesn't match the property `sort by b` with the condition `a in (1)`.

**Comment by winoros** [comment]
Good, closed by #11749
