### ISSUE TITLE
use tidb-lightning problem

### ISSUE THREAD

**Issue by DBKent** [pingcap/tidb#10796]
what is this problem for tidb-lightning:
![image](https://user-images.githubusercontent.com/51220911/59410307-1a532b80-8deb-11e9-8db6-23a26e662d57.png)
why it show remote checksum complete,and next step have error for checksum 0 vs 16077.....
 I do for tidb-lightning-ctl --checkpoint-error-destroy=all  and retry to strat lightning.
 _from https://pingcap.com/docs-cn/dev/how-to/troubleshoot/tidb-lightning/_
It always show this error,but my tidb have data and really can be selected.

**Comment by qw4990** [comment]
@kennytm PTAL~

**Comment by kennytm** [comment]
@DBKent hi, sorry for late reply. Could you try running

```
ADMIN CHECKSUM TABLE `ReportDB`.`FastReportDBS`
```

on TiDB after importing and see if it returns nonzero values? Thanks.

**Comment by DBKent** [comment]
OK,i drop my table and retry it.
![image](https://user-images.githubusercontent.com/51220911/59649009-92d33700-91b3-11e9-9fa4-92d6d410610a.png)
it returns zero values..
but i count it,have data.
![image](https://user-images.githubusercontent.com/51220911/59649061-c1511200-91b3-11e9-846a-573ecbeefec3.png)

**Comment by kennytm** [comment]
Thanks, looks like a problem in TiDB or TiKV. Could you show the TiDB and TiKV versions?

```sql
select tidb_version();
```

```sh
bin/tikv-server --version
```

and also verify if the data really exists?

```sql
select * from FastREportDB5 limit 1;
```

**Comment by DBKent** [comment]
Tidb: Release Version: v3.0.0-rc.1-114-gcc74145ff
Tikv: Release Version:   3.0.0-beta.
mysql> select * from FastREportDB5 limit 1\G
*************************** 1. row ***************************
     RoundDate: 2014-11-02
      GameType: 0
          AGID: 41633846
      Currency: RMB
  ExchangeRate: 1.000000
        Payoff: -99.8100
      .....
      ....
       ....
      Platform: 0
        Client: 0
        Portal: 0
          test: NULL
1 row in set (0.00 sec)

**Comment by lonng** [comment]
@DBKent Is there any `warn` or `error` log about checksum?

**Comment by DBKent** [comment]
@lonng  , log about checksum in tidb_lightning.log?
it's all of error log in tidb_lightning.log
![image](https://user-images.githubusercontent.com/51220911/59651755-a4b9d780-91bd-11e9-9e76-908f0a0aa19c.png)

**Comment by kennytm** [comment]
@DBKent The log in `tidb.log` and `tikv.log` after executing `ADMIN CHECKSUM TABLE ReportDB.FastReportDB5` from the mysql client.

**Comment by DBKent** [comment]
@kennytm  ,no log in tidb.log and tikv.log after executing ` ADMIN CHECKSUM TABLE ReportDB.FastReportDB5`

**Comment by kennytm** [comment]
@DBKent 🤔. Would you mind joining our TiDB Community Slack chatroom (https://pingcap.com/tidbslack) for real-time investigation? You could DM me (`@kennytm`) there. (We could also use WeChat if you like)

If you prefer to continue here, could you check 

1. Whether all of the following return the same values? (this checks if it is caused by case-sensitivity)

    ```sql
    ADMIN CHECKSUM TABLE FastREportDB5;
    --                        ^ note the capital E
    ADMIN CHECKSUM TABLE `ReportDB`.`FastREportDB5`;
    ```

2. Insert a single row into the table. Is the CHECKSUM changed? (this checks if the table range is lost)

    ```sql
    INSERT INTO FastREportDB5 VALUES ( ... );
    SELECT count(1) FROM FastREportDB5;
    -- should become 40226103

    ADMIN CHECKSUM TABLE FastREportDB5;
    -- the normal case should return `Total_kvs = 241356618`
    -- the abnormal case could return `Total_kvs = 0` or `Total_kvs = 6`.
    ```

3. Is the checksum mismatch still reproducible if we drop the table `FastREportDB5`, and only import 10 rows through Lightning? (this checks if the error is caused by data or schema)

Thanks!

**Comment by kennytm** [comment]
After a discussion on Slack, we have determined the real cause of this issue is that **ADMIN CHECKSUM does not support partitioned tables**.

```sql
create table a(a int) partition by hash(a) partitions 5;
insert into a values (1), (2), (3);
admin checksum table a;
-- returns 0 checksum
```
