### ISSUE TITLE
 Support UPDATE xxx T0 LEFT OUTER JOIN

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#108]
Tests from
https://github.com/ngaut/beego/tree/tidb-support/orm

Error message:
tidb.go:105: [error] compiling UPDATE `user` T0 LEFT OUTER JOIN `user_profile` T1 ON T1.`id` = T0.`profile_id` SET T0.`profile_id` = ? WHERE T0.`profile_id` IN (?) 
, error: line 1 column 18 near "LEFT"

**Comment by ngaut** [comment]
@shenli Any update?

**Comment by shenli** [comment]
I am working on this.

**Comment by shenli** [comment]
Fixed in https://github.com/pingcap/tidb/pull/146
