### ISSUE TITLE
about id

### ISSUE THREAD

**Issue by 450302324** [pingcap/tidb#10807]
I use uuid(binary) as tables' prime key.However,I can't find data by uuid class.My ORM is JPA.Please help me how to deal that.Thank you.

**Comment by qw4990** [comment]
@450302324 Thanks for your feedback.
Could you please give us more details about your problem? 
For example, your table schema and any SQL can reproduce this problem.

**Comment by 450302324** [comment]
My entity like that

```
@MappedSuperclass
public abstract class UUIDEntity implements Serializable {

    @Id
//    @GeneratedValue(generator = "system-uuid")
    private UUID id = UUID.randomUUID();

    //声明两个时间列，用来作为创建时间和更新时间
    @Temporal(TemporalType.TIMESTAMP)
    private Date update_timestamp;

    @Temporal(TemporalType.TIMESTAMP)
    private Date create_timestamp;

    //在创建时，对创建时间和更新时间进行刷新
    @PrePersist
    public void prePersist(){
        this.update_timestamp = new Date();
        this.create_timestamp = this.update_timestamp;
    }

    //在更新时，对更新时间进行刷新
    @PreUpdate
    public void preUpdate(){
        this.update_timestamp = new Date();
    }

    // Getter and Setter

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public Date getUpdate_timestamp() {
        return update_timestamp;
    }

    public void setUpdate_timestamp(Date update_timestamp) {
        this.update_timestamp = update_timestamp;
    }

    public Date getCreate_timestamp() {
        return create_timestamp;
    }

    public void setCreate_timestamp(Date create_timestamp) {
        this.create_timestamp = create_timestamp;
    }
}

```

table:
```
-- auto-generated definition
create table project
(
	id binary(255) not null
		primary key,
	create_timestamp datetime null,
	update_timestamp datetime null,
	is_deleted int null,
	name varchar(255) null
)
;
```

It will create an UUID as prime key and save successful when I save the entity.But I can't find data or delete data from table by this id.The id format is 7299ee7c-0640-4b0d-bcf2-493aba7d2adb.

 ```
public synchronized void delete(UUID uuid) {
        logger.info("ProjectService delete start,uuid:"+uuid);


        this.projectRepository.deleteById(uuid);
        this.projectRepository.flush();

        logger.info("ProjectService delete end,return:void");

    }


```

I try it successful by SQL just now.
`select hex(id) from project where id =unhex('7299EE7C06404B0DBCF2493ABA7D2ADB0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000');`

It is too complex.
1.jpa didn't have the method to implement  unhex().And considering the possibility of changing databases, I try not to write SQL statements.
2.I must use UUID(binary),because String(varchar) indexes are inefficient.
3.I want search criteria more simple like normal uuid but binary.

                                                                                                                                               thank you.

**Comment by qw4990** [comment]
Could you please open `general log` on TiDB and execute your `delete` function again, and then find the actual delete SQL that TiDB received from `JPA` on the general log?

**Comment by morgo** [comment]
I am going to close this issue as stale, but please feel free to re-open it (or ask again on asktug.com) if you have additional questions. Thank you!
