### ISSUE TITLE
TiKV cluster not bootstrapped, please start TiKV first"

### ISSUE THREAD

**Issue by tooapi** [pingcap/tidb#10812]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by qw4990** [comment]
@tooapi Thanks for your feedback. 
Could you please describe your problem more detailedly?

**Comment by shenli** [comment]
@tooapi Please provide more information. Thanks!

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
