### ISSUE TITLE
why ssd iops very low on cloud ssd?

### ISSUE THREAD

**Issue by meeepo** [pingcap/tidb#10840]
I use tidb and it use rocksb as storage engine and running on aliyun cloud server with cloud ssd.

The ssd iops performance test is 15k iops via 4k write block size and 1k iops via 3k write block size(it's looks like a disk bug and appear on all cloud ssd)

And i found disk util very high to over 80%,iostat shows that avgrq-sz about 6.25,that means my ssd iops performance down to only 1/15 .

I tried set block-size to 32k ,nothing change.

Is avgrq-sz=6 normal? how to make average write data size over 4k so ssd can run at normal performance?

thanks!

![image](https://user-images.githubusercontent.com/9400642/59681712-22560580-9207-11e9-8467-db3907e2be57.png)

**Comment by lonng** [comment]
Related issue: https://github.com/tikv/tikv/issues/4916

**Comment by shenli** [comment]
@meeepo I will close this issue due to that it is duplicated with the issue in TiKV repo. TiKV repo is a more suitable place to discuss this issue.
