### ISSUE TITLE
TiDB cluster is unavailable after kv conponents disconnected

### ISSUE THREAD

**Issue by aeoluswing** [pingcap/tidb#10843]
Tidb version: 2.1.11
Env: 10 nodes for Production Environment

When pd.logs show lots of `[region/store]send keepalive failed:EOF`,the kv nodes restart one after another,this takes the transformation of stats between up with disconnection on all stores.I guess our kv cluster is crashed because of the synchronization of kv nodes,at the same time `region change leader` occurs frequently.

Trying `unsafe-recover remove-fail-stores` command for disconnecting store will  cause error below:
```
0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:227
             at libstd/panicking.rs:475
   3: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   4: rust_begin_unwind
             at libstd/panicking.rs:325
   5: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   6: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   7: tikv_ctl::new_debug_executor
             at /checkout/src/libcore/result.rs:782
             at src/bin/tikv-ctl.rs:95
   8: tikv_ctl::main
             at src/bin/tikv-ctl.rs:1601
   9: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  10: main
  11: __libc_start_main
  12: <unknown>
```
or
```
/TiKV-01/deploy/bin$ ./tikv-ctl --db /home/tidb/data/TiKV-01/deploy/data/db unsafe-recover remove-fail-stores -s 4,5 --all-regions
removing stores [4, 5] from configrations...
Debugger::remove_fail_stores: StringError("Store 4 in the failed list")
```

Does anyone know how to resolve this complexion?Any Suggestions are welcome.

**Comment by qw4990** [comment]
Thanks for your feedback @aeoluswing , but it seems that this is an issue about TiKV, so it's better to ask this question on [TiKV repo](https://github.com/tikv/tikv/issues).

**Comment by aeoluswing** [comment]
All right.I'll transfer this issue and close current one here.
