### ISSUE TITLE
pre-commit hooks will emit an error while there is no `goword` installed

### ISSUE THREAD

**Issue by lonng** [pingcap/tidb#10842]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

Should install `goword` automatically instead of emitting an error.

3. What did you see instead?

```
Checking for files that need goword... .git/hooks/pre-commit: line 56: goword: command not found
.git/hooks/pre-commit: line 56: goword: command not found
```

**Comment by nullnotnil** [comment]
The [CONTRIBUTING guide](https://github.com/pingcap/community/blob/master/contributors/README.md )no longer suggests anything about installing git hooks. This could be in error...

If it's intentional, that would make this issue obsolete. What do you think?
