### ISSUE TITLE
The Host and Info column of `show processlist` are not same as mysql

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#10903]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

open 2 mysql client and run `show processlists;` both.

2. What did you expect to see?

The `Info` column of `show processlist` should be NULL if it is not executing any statement.
See https://dev.mysql.com/doc/refman/5.5/en/processlist-table.html
> The statement the thread is executing, or NULL if it is not executing any statement.

The `Host` column should be host_name:client_port format.
> The host name of the client issuing the statement (except for system user, for which there is no host). The host name for TCP/IP connections is reported in host_name:client_port format to make it easier to determine which client is doing what.

```
mysql> show processlist;
+----+------+-----------------+------+---------+------+----------+------------------+
| Id | User | Host            | db   | Command | Time | State    | Info             |
+----+------+-----------------+------+---------+------+----------+------------------+
| 13 | root | localhost:53239 | test | Sleep   |   15 |          | NULL             |
| 14 | root | localhost:53268 | test | Query   |    0 | starting | show processlist |
+----+------+-----------------+------+---------+------+----------+------------------+
2 rows in set (0.00 sec)


```

3. What did you see instead?

```mysql
mysql> show processlist;
+------+------+-----------+------+---------+------+-------+------------------+
| Id   | User | Host      | db   | Command | Time | State | Info             |
+------+------+-----------+------+---------+------+-------+------------------+
|    1 | root | 127.0.0.1 | test | Query   |    0 | 2     | show processlist |
|    2 | root | 127.0.0.1 | test | Sleep   |    2 | 2     |                  |
+------+------+-----------+------+---------+------+-------+------------------+
2 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.0.0-rc.1-221-g5cd77cdc8
Git Commit Hash: 5cd77cdc8d59300cee70f61cfdd08fa042d1e89f
Git Branch: master
UTC Build Time: 2019-06-21 10:26:09
GoVersion: go version go1.12.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by XuHuaiyu** [comment]
fixed in #10985

**Comment by SunRunAway** [comment]
> The `Host` column should be host_name:client_port format.

Have it been fixed?

**Comment by XuHuaiyu** [comment]
@SunRunAway It will be fixed in another PR.

**Comment by nullnotnil** [comment]
Confirming this issue still exists in master:
```sql
mysql> show processlist;
+------+------+-----------+------+---------+------+------------+------------------+
| Id   | User | Host      | db   | Command | Time | State      | Info             |
+------+------+-----------+------+---------+------+------------+------------------+
|   21 | root | 127.0.0.1 | test | Query   |    0 | autocommit | show processlist |
+------+------+-----------+------+---------+------+------------+------------------+
1 row in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-870-g2a8b96845
Edition: Community
Git Commit Hash: 2a8b968453520e4fcf9d6ff46c9f23b4ad23feee
Git Branch: master
UTC Build Time: 2020-07-31 08:45:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

```
