### ISSUE TITLE
Invalid SQL can be parsed successfully

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#10906]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Connect a TiDB server through mycli, execute `drop table if exists t';`

2. What did you expect to see?
In MySQL 5.7,
```sql
mysql root@127.0.0.1:test> drop table if exists t';                             
(1064, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ''' at line 1")
```

3. What did you see instead?
```sql
mysql root@127.0.0.1:test> drop table if exists t';                             
Query OK, 0 rows affected
Time: 0.001s
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
+--------------------------------------------------------------------------+
| tidb_version()                                                           |
+--------------------------------------------------------------------------+
| Release Version: v3.0.0-rc.1-210-g421de5ef2                              |
| Git Commit Hash: 421de5ef20ae421ea3234a7b4367a8acd89fbabe                |
| Git Branch: master                                                       |
| UTC Build Time: 2019-06-21 02:19:38                                      |
| GoVersion: go version go1.12.5 linux/amd64                               |
| Race Enabled: false                                                      |
| TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
| Check Table Before Drop: false                                           |
+--------------------------------------------------------------------------+
```

**Comment by lonng** [comment]
Can you submit a PR to fix this problem?

**Comment by tangenta** [comment]
Of course! I can try it.

**Comment by pkbmh** [comment]
@tangenta  I can't reproduce this bug in my local system. 
For me both mysql-5.7 and tidb both are entering in the incomplete query shell. 
<img width="1501" alt="Screen Shot 2019-06-23 at 10 53 04 PM" src="https://user-images.githubusercontent.com/11595732/59977942-d7266300-9609-11e9-8ac3-e07a9dc0b921.png">

**Comment by tangenta** [comment]
@pkbmh That's probably because MySQL client parsed the string in a unique way. You can try it on different client, like [mycli ](https://www.mycli.net/) or [tidiff](https://github.com/pingcap/tidiff).

**Comment by pkbmh** [comment]
@tangenta thanks for the clarification.
