### ISSUE TITLE
Add a tool to do bootstrap jobs

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1096]
We use a independent tool to do bootstrap jobs. Then we do not need to do bootstrap jobs when TiDB starts. The current way is error prone.

**Comment by ngaut** [comment]
I strongly recommend we do bootstrap automatically.

**Comment by shenli** [comment]
We will check if already bootstrapped when encounter error.

**Comment by c4pt0r** [comment]
Is there enough information or log output when tidb is running bootstrap job?

**Comment by shenli** [comment]
No，we do not know if other tidb-server is running bootstrap. And it is not necessary to know this. The bootstrapping stage it divided  into ddl stage and dml stage. The ddl stage is safe to run concurrently. The dml stage use a transaction to insert data into system tables. So only one tidb-server will won. Than there will be a variable in statue table to indicate the bootstrap stage is finished. So other tidb-server will know this. @c4pt0r
