### ISSUE TITLE
window function: group_concat error message is not compatible

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#10996]
## Description

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
mysql> select group_concat('3') over ();
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 29 near "over ()"
```

2. What did you expect to see?

```
mysql> select group_concat('3') over ();
ERROR 1235 (42000): This version of MySQL doesn't yet support 'group_concat as window function'
```

## Score

* 50

## Mentor(s)

* @SunRunAway 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang Programming.
* Be familiar with window function and TiDB Parser.

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by SunRunAway** [comment]
Hi, @yangwenmai 
Sorry for the late response,

**Comment by SunRunAway** [comment]
Hi, @yangwenmai 
Sorry for the late response, I've tried to modify `parser.y` like yours and run `make test` with no error.
Could you provide a branch with this problem in your `parser` repo and let me take a look?

**Comment by yangwenmai** [comment]
https://github.com/yangwenmai/parser/tree/fix_group_cast

**Comment by SunRunAway** [comment]
Can't reproduce :(
The error message you pasted shows that the failing test is at https://github.com/yangwenmai/parser/blob/fix_group_cast/parser_test.go#L3276-L3343

Could you take another investigation?

**Comment by yangwenmai** [comment]
OK, Thanks.

**Comment by francis0407** [comment]
Is this issue in the challenge program now? @zz-jason

**Comment by zz-jason** [comment]
Yes, I moved it to the `difficulty/easy` column.
