### ISSUE TITLE
window function: should check fuction's arguments firstly.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11008]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT NTH_VALUE(fieldA, -1) OVER (w1 PARTITION BY fieldB ORDER BY fieldB , fieldA ) AS 'ntile', fieldA, fieldB FROM ( SELECT `pk` AS fieldA, `col_date_key` AS fieldB FROM `table70_int_autoinc` ) as t WINDOW w1 AS ( ORDER BY fieldB ASC, fieldA DESC );
```

2. What did you expect to see?

```mysql
ERROR 1210 (HY000): Incorrect arguments to nth_value
```

3. What did you see instead?

```mysql
ERROR 3581 (HY000): A window which depends on another cannot define partitioning.
```
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by gaoxingliang** [comment]
I will look into this issue.

**Comment by gaoxingliang** [comment]
Hi @SunRunAway 
it has been fixed in https://github.com/pingcap/tidb/pull/9596/files.

**Comment by SunRunAway** [comment]
Hi, @gaoxingliang 
I think you've misunderstood this issue. `nth_value` is already implemented but what this issue describes is the error message problem.

**Comment by gaoxingliang** [comment]
@SunRunAway I test with latest master branch, it shows the correct error message (if you mean the index should be > 0, that's NTH_VALUE(fieldA, -1) , -1 is illegal):
Example:
```
mysql> SELECT
    ->     employee_name,
    ->     salary,
    ->     NTH_VALUE(employee_name, -1) OVER  (
    ->         ORDER BY salary DESC
    ->     ) second_highest_salary
    -> FROM
    ->     basic_pays;
ERROR 1210 (HY000): Incorrect arguments to nth_value
```

**Comment by SunRunAway** [comment]
Hi, your test case is different from what this issue describes which a window is depends on another.

**Comment by gaoxingliang** [comment]
@SunRunAway Okay. now I can reproduce it and I will look more into this.
