### ISSUE TITLE
Should not add an index of length 0 to columns of type Blob, text, etc.

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#11049]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(a blob(10), index(a(0)));
```

2. What did you expect to see?
```
mysql> create table t(a blob(10), index(a(0)));
ERROR 1391 (HY000): Key part 'a' length cannot be 0
```

3. What did you see instead?
```
tidb> create table t(a blob(10), index(a(0)));
Query OK, 0 rows affected (0.01 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
["Release Version"=v3.0.0-rc.1-264-gcb23b524a]
["Git Commit Hash"=cb23b524accce9ff1d1168acb0b5a102f3e7a22c]

**Comment by tiancaiamao** [comment]
Would you like to handle it? if so, you may assign this issue to yourself. @zimulala

**Comment by zimulala** [comment]
We want it to return an error.

**Comment by Rustin-Liu** [comment]
I am working on it.

**Comment by zimulala** [comment]
@Rustin-Liu 
Thank you for your participation！
