### ISSUE TITLE
check table column not exsists null value may lead to table scan

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb#11078]
https://github.com/pingcap/tidb/blob/master/ddl/column.go

```
// checkForNullValue ensure there are no null values of the column of this table.
// `isDataTruncated` indicates whether the new field and the old field type are the same, in order to be compatible with mysql.
func checkForNullValue(ctx sessionctx.Context, isDataTruncated bool, schema, table, oldCol, newCol model.CIStr) error {
	sql := fmt.Sprintf("select count(*) from `%s`.`%s` where `%s` is null limit 1;", schema.L, table.L, oldCol.L)
	rows, _, err := ctx.(sqlexec.RestrictedSQLExecutor).ExecRestrictedSQL(ctx, sql)
	if err != nil {
		return errors.Trace(err)
	}
	rowCount := rows[0].GetInt64(0)
	if rowCount != 0 {
		if isDataTruncated {
			return errInvalidUseOfNull
		}
		return ErrWarnDataTruncated.GenWithStackByArgs(newCol.L, rowCount)
	}
	return nil
}
```
the sql "select count(*) from `%s`.`%s` where `%s` is null limit 1" is same with "select count(*) from `%s`.`%s` where `%s` is null", then it may count all null values，that may lead to table scane

**Comment by tiancaiamao** [comment]
The logic here has to scan the whole table, in the worst case.
The problem you point out is that `select count() from %s.%s where %s is null limit 1` scan the whole table, in all cases. @jiyfhust 
Maybe it's better to change it to `select 1 from %s.%s where %s is null limit 1`

**Comment by jiyfhust** [comment]
need i send a pull request for this issue?

**Comment by jiyfhust** [comment]
@tiancaiamao

**Comment by tiancaiamao** [comment]
I'm glad that you can take this job, come on!
