### ISSUE TITLE
How do I compile tidb in goland

### ISSUE THREAD

**Issue by zplinuxlover** [pingcap/tidb#11119]
## General Question
I import tidb source code into goland， but I compile the code using goland, But I got the error, 
the error is below, But when i use make to compile the code , I do not get any error, which tool do you use to develop tidb, goland or vim ?

the error message is 

# github.com/coreos/etcd/clientv3
../coreos/etcd/clientv3/auth.go:121:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
../coreos/etcd/clientv3/auth.go:126:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
../coreos/etcd/clientv3/auth.go:131:152: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
../coreos/etcd/clientv3/auth.go:136:144: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
../coreos/etcd/clientv3/auth.go:141:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
../coreos/etcd/clientv3/auth.go:146:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
../coreos/etcd/clientv3/auth.go:151:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
../coreos/etcd/clientv3/auth.go:156:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
../coreos/etcd/clientv3/auth.go:161:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
../coreos/etcd/clientv3/auth.go:166:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
../coreos/etcd/clientv3/auth.go:166:106: too many errors
# github.com/pingcap/tidb/store/tikv/tikvrpc
tidb/store/tikv/tikvrpc/tikvrpc.go:169:9: undefined: tikvpb.BatchCommandsEmptyRequest

**Comment by winoros** [comment]
Did your Goland open the `Go Modules(vgo)`?

**Comment by zplinuxlover** [comment]
can you give me a document of how to setup tidb in goland?

**Comment by winoros** [comment]
@zplinuxlover 
TiDB uses `go module` instead of vendor to manage dependencies.
You need to open the `vgo` feature in Goland https://blog.jetbrains.com/go/2019/01/22/working-with-go-modules/

**Comment by kolbe** [comment]
@zplinuxlover  I was able to run tidb-server/main.go in GoLand 2019.2.3 by creating a new project and choosing vgo. I'm going to close this issue now, but if you still have trouble building/running tidb-server in GoLand, please re-open this issue.
