### ISSUE TITLE
How to disable auto_increment increasing?

### ISSUE THREAD

**Issue by lexesv** [pingcap/tidb#11115]
Hello!
How to disable auto_increment increasing (+30000) at all?
I not found answer

**Comment by winkyao** [comment]
Why do you want to disable auto_increment increasing(+30000)? Could you give more details?

**Comment by winkyao** [comment]
Will this [docs](https://pingcap.com/docs-cn/v3.0/reference/mysql-compatibility/#%E8%87%AA%E5%A2%9E-id) can help?

**Comment by winkyao** [comment]
You can not disable this feature in TiDB.

**Comment by nullnotnil** [comment]
Starting with TiDB 3.0, the cache size is configurable. See docs; https://docs.pingcap.com/tidb/stable/auto-increment#cache-size-control

I am going to close this issue as stale, but please feel free to re-open if you have additional questions. Thanks!
