### ISSUE TITLE
support SELECT ... INTO OUTFILE

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#11112]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No

**Describe the feature you'd like:**

From MySQL documentation [13.2.10.1 SELECT ... INTO OUTFILE Syntax](https://dev.mysql.com/doc/refman/8.0/en/select-into.html):
> SELECT ... INTO OUTFILE writes the selected rows to a file. Column and line terminators can be specified to produce a specific output format.

It helps us to store the query result in a CSV form.

After this issue https://github.com/pingcap/parser/issues/722, you have to implement a `SelectIntoExec` like the `ExplainExec` to let TiDB support this new syntax.
**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by tsthght** [comment]
let me try it~
