### ISSUE TITLE
Question about TiDB Binlog

### ISSUE THREAD

**Issue by BeyongTheMemory** [pingcap/tidb#11126]
请问为什么TiDB不选择收集TiKV中的raft日志来实现Binlog呢？是出于解耦的考虑或是读TiKV日志的方式实现起来会出现很大的问题吗？
由于我们只需要KV查询功能，所以基于TiKV做了数据库，现在需要类似binlog的功能想请教一下你们当时选型的原因，非常感谢

**Comment by shenli** [comment]
We need to provide transaction binlog. Make sure the binlog is the same order as the transaction. It is much simpler to implement binlog from `tidb-server` side.

**Comment by BeyongTheMemory** [comment]
Many tks. If all of the pump servers down,  write operate will fail，right?

**Comment by shenli** [comment]
@BeyongTheMemory Yes, but you can set [an option](https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L298) to change the behavior.
We are planning to refactor the `binlog` component to improve high availability and usability.

**Comment by BeyongTheMemory** [comment]
ok, thanks
