### ISSUE TITLE
Raft: Laze Peer

### ISSUE THREAD

**Issue by Ryan-Git** [pingcap/tidb#11129]
Recently I found a ppt about TiDB in QCon 2019 BJ (here's a [link](https://myslide.cn/slides/18419), at page 21), which states a raft new feature called "Lazy Peer".

What does it exactly mean?

**Comment by ljluestc** [comment]
The slide link has been invalid please close it or change the link, thanks.

**Comment by jebter** [comment]
I will close this issue. If there are any updates, you can reopen it.
