### ISSUE TITLE
A question about add table index code 

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb#11127]
hi,  i read code about add table index.

i have a question about it.

code file [link]( https://github.com/pingcap/tidb/blob/master/ddl/index.go "With a Title")

    func (w *worker) addPhysicalTableIndex(t table.PhysicalTable, indexInfo *model.IndexInfo, 
        ...
        for {
		    kvRanges, err := splitTableRanges(t, reorgInfo.d.store, startHandle, endHandle)
		    ...
		    remains, err := w.sendRangeTaskToWorkers(t, idxWorkers, reorgInfo, 
    &totalAddedCount, kvRanges)
		     ...
		    if len(remains) == 0 {
			    break
		    }
		    startHandle, _, err = decodeHandleRange(remains[0])
		    if err != nil {
			    return errors.Trace(err)
		    }
	    }
	    return nil
    }

the function "addPhysicalTableIndex" call  "sendRangeTaskToWorkers"，

"sendRangeTaskToWorkers" one time sends len(idxWorkers) regionRanges to idxWorkers，and wait all of them to finish.

why not send new to idxWorker at once  when one idxworker finish, other than wait all they finish?

thank you very much!

**Comment by winkyao** [comment]
We already file a PR for this issue https://github.com/pingcap/tidb/pull/9537

**Comment by winkyao** [comment]
Thanks for your attention.

**Comment by jiyfhust** [comment]
oh. 666
