### ISSUE TITLE
为什么我使用ansible-playbook start.yml -l 启动某个挂掉的kv节点后在监控平台上还是显示他是down掉的

### ISSUE THREAD

**Issue by wangsiyu34567** [pingcap/tidb#11148]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
我的TIKV节点不知道因为什么原因挂掉了三个(一开始只挂掉一个，后来有台服务器上的两台节点都挂掉了，并且监控平台上看不到这台服务器的信息)

2. What did you expect to see?
我希望所有的tikv节点都能正常运作

3. What did you see instead?
一共三台服务器，6个kv节点  现在挂了三个,
我使用ansible-playbook start.yml -l 命令或者关闭后重启集群依然起不来挂掉的三个节点

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.6

**Comment by winkyao** [comment]
Could you give some error message？

**Comment by winkyao** [comment]
@breeswish @hicqu PTAL

**Comment by wangsiyu34567** [comment]
我在使用ansible-playbook start.yml -l 命令或者重启时都没有报错  没有错误信息， 但是监控平台上显示依旧是三个节点死掉

**Comment by wangsiyu34567** [comment]
E0501 02:20:57.215682168   21180 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0501 02:20:58.732688234   21184 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0501 02:20:58.735579097   21186 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0501 02:21:00.733621032   21187 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0501 02:21:08.133655201   21181 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0501 02:21:08.136551872   21178 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0501 02:21:08.137514427   21182 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0508 01:10:49.690607987   21184 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0511 09:41:00.651473528   21180 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0611 17:02:03.380923324    4726 chttp2_transport.c:2763]    keepalive_ping_end state error: 0 (expect: 1)
E0629 20:42:37.145640340   17629 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0630 00:58:00.253418297   17695 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1561827480.253354272","description":"polling_island_create","file":"/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1561827480.253352481","description":"OS Error","errno":23,"file":"/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_create1"}]}
E0630 00:58:00.253794474   17695 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1561827480.253765547","description":"polling_island_create","file":"/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1561827480.253764488","description":"OS Error","errno":23,"file":"/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_create1"}]}
E0630 00:58:00.254215878   17695 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1561827480.254189918","description":"polling_island_create","file":"/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1561827480.254188913","description":"OS Error","errno":23,"file":"/rust/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_create1"}]}

**Comment by disksing** [comment]
`"Too many open files in system"` Could you take a look at the ulimit setting?

**Comment by wangsiyu34567** [comment]
[tidb@tikv42 ~]$ ulimit -n
1000000

**Comment by disksing** [comment]
em, 1000000 should be enough for tikv. Could you use `lsof` to count current open files of `tikv-server` and the whole system?

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
