### ISSUE TITLE
`update t1 set a=(select 1);` gets the wrong result.

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#1116]
1. What did you do?
```
create table t1 (a int not null);
insert into t1 values (1);
update t1 set a=(select 1);
```
2.What did you expect to see?

Query OK, 0 rows affected (0.01 sec)

3.What did you see instead?

ERROR 1105 (HY000): Column a can't be null.

**Comment by coocood** [comment]
Already fixed.
