### ISSUE TITLE
The result of function COMPRESS is different from MySQL

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11163]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
SELECT LENGTH(COMPRESS('a'));
```

2. What did you expect to see?

```mysql
mysql> SELECT LENGTH(COMPRESS('a'));
+-----------------------+
| LENGTH(COMPRESS('a')) |
+-----------------------+
|                    13 |
+-----------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> SELECT LENGTH(COMPRESS('a'));
+-----------------------+
| LENGTH(COMPRESS('a')) |
+-----------------------+
|                    17 |
+-----------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

fdbc149b72db7034d024acf1209e455c0ad4ca9d

**Comment by amyangfei** [comment]
This issue may due to the `zlib.compress` implement way in golang, if we use raw golang API we could hardly get format compatible compress result.
https://github.com/golang/go/issues/28594
https://stackoverflow.com/questions/27852940/how-can-i-use-zlib-in-golang-to-cooperate-with-zlib-in-c

**Comment by SunRunAway** [comment]
Thanks @amyangfei 
I'll close this issue for now.
