### ISSUE TITLE
Function OCTET_LENGTH is not implemented but the documentation says yes. 

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11195]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Function `OCTET_LENGTH` is not implemented but it is documented at https://pingcap.com/docs/dev/reference/sql/functions-and-operators/string-functions/
```mysql
mysql> select OCTET_LENGTH(1);
```

2. What did you expect to see?

```mysql
mysql> select OCTET_LENGTH(1);
+-----------------+
| OCTET_LENGTH(1) |
+-----------------+
|               1 |
+-----------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```mysql
mysql> select OCTET_LENGTH(1);
ERROR 1305 (42000): FUNCTION octet_length does not exist
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by gaoxingliang** [comment]
this issue seems not fixed yet on master branch. If so, I will look into this issue.
