### ISSUE TITLE
Can't support `select 999999999999999999999999999999;`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#1121]
1.What did you do?

`select 999999999999999999999999999999;`

2.What did you expect to see?
+--------------------------------+
| 999999999999999999999999999999 |
+--------------------------------+
| 999999999999999999999999999999 |
+--------------------------------+

3.What did you see instead?

ERROR 1105 (HY000): line 1 column 8 near "999999999999999999999999999999" integer literal: strconv.ParseUint: parsing "999999999999999999999999999999": value out of range

**Comment by mccxj** [comment]
@zimulala It works now. issue should be close.

```
Tidb>select 999999999999999999999999999999;
+--------------------------------+
| 999999999999999999999999999999 |
+--------------------------------+
| 999999999999999999999999999999 |
+--------------------------------+
1 row in set (0.00 sec)
```

**Comment by winoros** [comment]
@mccxj Thanks for reminding!
