### ISSUE TITLE
result of 'select @@tidb_disable_txn_auto_retry' should be a number

### ISSUE THREAD

**Issue by tptpp** [pingcap/tidb#11221]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
set @@tidb_disable_txn_auto_retry = 0;
set @@tidb_disable_txn_auto_retry = 1;

set @@tidb_disable_txn_auto_retry = on;
set @@tidb_disable_txn_auto_retry = off;

select @@tidb_disable_txn_auto_retry;

2. What did you expect to see?
result of 'select @@tidb_disable_txn_auto_retry' should be a number

3. What did you see instead?
result of 'select @@tidb_disable_txn_auto_retry' is a number or string, depending on the 'set' commend

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb_version(): Release Version: v3.0.0-rc.1-316-g60de9b981
Git Commit Hash: 60de9b981fd29af9a1bc1d46d706d8800ddce278
Git Branch: tptpp/usage-test-flags
UTC Build Time: 2019-07-11 07:29:50
GoVersion: go version go1.12.4 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by lonng** [comment]
Closed due to duplicated with #11222
