### ISSUE TITLE
Result of JDBC batch update is different from MySQL

### ISSUE THREAD

**Issue by ssnijik** [pingcap/tidb#11235]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I'm trying to batch update/delete hundrads of records using PrepareStatement#executeBatch through JDBC. The method will return an array with updated count(`0` or `1`) or response code(`-2` for success or `-3` for failure) for each record. If in MySQL, all record will return updated count or success code, but in TiDB, only first record of batch will be updated, all of the remaining ones will fail. This behavior can be reproduced by different JDBC driver(`org.mariadb.jdbc.Driver` and `com.mysql.jdbc.Driver`) through TiDB v2.0 to v3.0. The difference only occurs during batch update and delete, for batch insert it is the same with MySQL.

2. What did you expect to see?
The following results are produced in MySQL using `org.mariadb.jdbc.Driver` 
> [DEBUG] 2019-07-12 01:12:55.128 [pool-2-thread-2] BatchUpdateDBProcessor - jdbc result: List{0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1}
> 

> [DEBUG] 2019-07-12 01:13:12.756 [pool-2-thread-2] BatchUpdateDBProcessor - jdbc result: List{1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1}

3. What did you see instead?
The following results are produced in TiDB using `org.mariadb.jdbc.Driver`. `-3` will be `0` when using `com.mysql.jdbc.Driver` due to JDBC implementation difference.
> [DEBUG] 2019-07-12 01:22:22.912 [pool-2-thread-2] BatchUpdateDBProcessor - jdbc result: List{0,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3}

> [DEBUG] 2019-07-12 01:22:28.780 [pool-2-thread-2] BatchUpdateDBProcessor - jdbc result: List{1,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3,-3}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
`First happens in v2.0.0, upgradation to v3.0.0 doesn't help`
Release Version: v3.0.0
Git Commit Hash: 60965b006877ca7234adaced7890d7b029ed1306
Git Branch: HEAD
UTC Build Time: 2019-06-28 12:14:07
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by lonng** [comment]
@ssnijik Thanks for your report, I will investigate it.

**Comment by lysu** [comment]
@ssnijik do you use `useServerPrepStmts=true` in jdbc params?

maybe give a look at tidb's log and it seems to be caused by this issue https://github.com/pingcap/tidb/issues/4617  if see `Can not prepare multiple statements` in tidb.log

jdbc' batch update will rewrite multiple updates into "multiple stmt"(e.g. `update t1 set .. where..;update t2 set.. where ...`, delete also do the same thing, this can cut off network around trip between client and server), current tidb hasn't support prepare multiple stmts...

so, to workaround now, maybe can:

- turn `useServerPrepStmts=false` for those batch update logic
- or, don't use batch update: send individual stmts or manually rewrite sql into [`update when case`](https://stackoverflow.com/questions/35726910/bulk-update-mysql-with-where-statement) to do batch..

**Comment by ssnijik** [comment]
@lysu Thanks for looking into this! Batch update is the best choice for our case. It seems that set `useServerPrepStmts=false` does't work. Can you help me to see whether there is other property I need to change?    

>     val config = new HikariConfig
>     config.setDriverClassName("org.mariadb.jdbc.Driver")
>     config.addDataSourceProperty("cachePrepStmts", "true")
>     config.addDataSourceProperty("prepStmtCacheSize", "600")
>     config.addDataSourceProperty("prepStmtCacheSqlLimit", "2048")
>     config.addDataSourceProperty("useServerPrepStmts", "false")
>     config.addDataSourceProperty("useLocalSessionState", "true")
>     config.addDataSourceProperty("rewriteBatchedStatements", "true")
>     config.addDataSourceProperty("cacheResultSetMetadata", "true")
>     config.addDataSourceProperty("cacheServerConfiguration", "true")
>     config.addDataSourceProperty("elideSetAutoCommits", "true")
>     config.addDataSourceProperty("maintainTimeStats", "false")

**Comment by lysu** [comment]
@ssnijik  Hi，could you give a screenshot for this panel in grafana

![image](https://user-images.githubusercontent.com/528332/61194134-33087700-a6f2-11e9-8ea8-51e15d166014.png)

and does any error log in tidb.log(can use `grep dispatch` to grep error) ~? thanks

**Comment by ssnijik** [comment]
![2019-07-15_13-05-29](https://user-images.githubusercontent.com/3711535/61196462-5be43880-a701-11e9-891b-b030b02efdde.png)

**Comment by ssnijik** [comment]
Also I don't find any "dispatch error" related to batch update in tidb.log

**Comment by lysu** [comment]
@ssnijik problem has been identified... current multiple SQL responses are not compatible with mysql protocol, we will fix it soon, sorry for the trouble.
