### ISSUE TITLE
Define all system variables in go type.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11269]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For now, all system variables are defined in a map with type string.
```go
	// systems variables, don't modify it directly, use GetSystemVar/SetSystemVar method.
	systems map[string]string
```
If we need a system variable in which the real type is an integer, for example, we must do string conversation. It's hard to code and bad to performance.

```go
	valStr, _ := ctx.GetSessionVars().GetSystemVar(variable.MaxAllowedPacket)
	maxAllowedPacket, err := strconv.ParseUint(valStr, 10, 64)
	if err != nil {
		return nil, err
	}
```

**Describe the feature you'd like:**

We need to define all system variables with their real type in go code. So that all of them can be called directly without performance loss.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

All the system variables defined in MySQL are located in https://github.com/mysql/mysql-server/blob/8.0/sql/system_variables.h#L174

**Comment by kilgaloon** [comment]
I guess this can be mapped to ‘interface{}’ then type asserted later for usage?

**Comment by ngaut** [comment]
It's not a good idea, we should set system variables explicitly.

**Comment by nullnotnil** [comment]
This is required for fixing compatibility issues. i.e. When you run `SHOW VARIABLES LIKE 'x'` in MySQL you should get a string type, but `SELECT @@x` should return the actual type. I am tracking a request for typed variables in https://github.com/pingcap/tidb/issues/15131 , so I am going to close this issue to reduce duplication. Thanks!
