### ISSUE TITLE
View INFORMATION_SCHEMA.TIKV_STORE_STATUS data error reporting

### ISSUE THREAD

**Issue by zhangxia1030** [pingcap/tidb#11294]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
look at INFORMATION_SCHEMA.TIKV_STORE_STATUS data

3. What did you see instead?
![图片](https://user-images.githubusercontent.com/11935969/61366157-9e517500-a8bb-11e9-86ee-4afdf3dfac97.png)
SQL ERROR [1105] [HY000]: json: cannot unmarshal number 1073734235.1328125 into Go struct field StoreDetailStat.region_score of type int64

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.0-rc.1-340-g7403ce331

**Comment by zhangxia1030** [comment]
Why is the data stored in the INFORMATION_SCHEMA.TIKV_STORE_STATUS table floating-point type and the receiving type defined by StoreDetailStat.region_score int64?

**Comment by lonng** [comment]
@zhangxia1030 Thanks for your report, it's a TiDB bug.

**Comment by lonng** [comment]
@winoros Protocol incompatible with PD, introduced by: https://github.com/pingcap/tidb/pull/10248

**Comment by lonng** [comment]
FIxed #11969
