### ISSUE TITLE
Query too slow for 3 rows 

### ISSUE THREAD

**Issue by chenzheng1024** [pingcap/tidb#11305]
## Performance Questions

- Questions
The table has 3 rows ,use more than 8 seconds for a query.NOT always , sometimes it happends,last for some hours,how can i solve that?

- What version of TiDB are you using?

| Release Version: v2.1.13
Git Commit Hash: 6b5b1a6802f9b8f5a22d8aab24ac80729331e1bc
Git Branch: HEAD
UTC Build Time: 2019-06-21 12:27:08
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |

- What's the observed and your expected performance respectively?

```
mysql> select * from chaininfo;
+----------------------------------+-----------+----------+------------+-------------------+-----------+-----------------------------------------------------------+---------------------+--------------------------------------------------------------------------+
| id                               | chainname | blocknum | onlinetime | coincount         | txcount   | version                                                   | updatetime          | remark                                                                   |
+----------------------------------+-----------+----------+------------+-------------------+-----------+-----------------------------------------------------------+---------------------+--------------------------------------------------------------------------+
| bf1558da724b485e9444e1faa75343e9 | btc       |   585888 | 1231006505 | 17823600.00000000 | 436186158 | main                                                      | 2019-07-18 10:36:37 | eyJzaXplX29uX2Rpc2siOjIzNzQ0Mzk2NjIxOSwidmVyaWZpY2F0aW9ucHJvZ3Jlc3MiOjB9 |
| 560be9ab565f43a2b111899b0fb2f2e1 | eth       |  8172114 | 1438197973 | 0.00000000        | 500044303 | Geth/v1.9.0-unstable-50e3795e-20190612/linux-amd64/go1.10 | 2019-07-18 10:54:01 | eyJhY2NvdW50cyI6W10sImdhc1ByaWNlIjoiMjAwMDAwMDAwMDAifQ==                 |
| 4c641fa0b4274feab1aecbbd41331c62 | tron      |  7940103 |          0 | 0.00000000        | 336578367 | main                                                      | 2019-07-18 01:41:56 | e30=                                                                     |
+----------------------------------+-----------+----------+------------+-------------------+-----------+-----------------------------------------------------------+---------------------+--------------------------------------------------------------------------+
3 rows in set (8.81 sec)
```

it should be less than 1 sec

- Have you compared TiDB with other databases? If yes, what's their difference?

- For a specific slow SQL query, please provide the following information:

1.occasionally runs slowly,but last for hours.

2.EXPLAIN:
```
mysql> explain select * from chaininfo;
+-----------------+-------+------+--------------------------------------------------------------------+
| id              | count | task | operator info                                                      |
+-----------------+-------+------+--------------------------------------------------------------------+
| TableReader_5   | 3.00  | root | data:TableScan_4                                                   |
| └─TableScan_4 | 3.00  | cop  | table:chaininfo, range:[-inf,+inf], keep order:false, stats:pseudo |
+-----------------+-------+------+--------------------------------------------------------------------+
2 rows in set (0.09 sec)
```

3.show CREATE table chaininfo

_CREATE TABLE `chaininfo` (
  `id` varchar(32) NOT NULL COMMENT '唯一标识',
  `chainname` varchar(16) DEFAULT '' COMMENT '链标识-BTC,ETH,EOS',
  `blocknum` bigint(20) DEFAULT '0' COMMENT '最新块号',
  `onlinetime` bigint(20) DEFAULT '0' COMMENT '上线时间',
  `coincount` decimal(30,8) DEFAULT '0.00000000' COMMENT '当前币总数',
  `txcount` bigint(20) DEFAULT '0' COMMENT '交易总量',
  `version` varchar(128) DEFAULT '' COMMENT '版本',
  `updatetime` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '信息update时间',
  `remark` text DEFAULT NULL COMMENT '其他信息',
  PRIMARY KEY (`id`),
  KEY `chainname_index` (`chainname`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin_

4.DumpFile：
`{"database_name":"tcmdb_1","table_name":"chaininfo","columns":{"blocknum":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166},"chainname":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":10,"last_update_version":409794707820380166},"coincount":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166},"id":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":96,"last_update_version":409794707820380166},"onlinetime":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166},"remark":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":132,"last_update_version":409794707820380166},"txcount":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166},"updatetime":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166},"version":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":65,"last_update_version":409794707820380166}},"indices":{"chainname_index":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166},"primary":{"histogram":{"ndv":0},"cm_sketch":null,"null_count":0,"tot_col_size":0,"last_update_version":409794707820380166}},"count":3,"modify_count":1822875,"partitions":null}`

5. slow query log:

Time: 2019-07-18T15:52:48.371035969+08:00
Txn_start_ts: 409845461231861790
User: root@10.10.70.206
Conn_ID: 27663
Query_time: 8.039381648
Process_time: 0.026 Wait_time: 8.013 Request_count: 1 Total_keys: 18 Process_keys: 3
DB: tcmdb_1
Is_internal: false
Digest: 983b2b2372545a233beacd14efca74491b16bd15cd3862fc7aaf98eeb815961e
Stats: chaininfo:pseudo
Num_cop_tasks: 1
Cop_proc_avg: 0.026 Cop_proc_p90: 0.026 Cop_proc_max: 0.026
Cop_wait_avg: 8.013 Cop_wait_p90: 8.013 Cop_wait_max: 8.013
Mem_max: 566
SELECT * FROM chaininfo;

  - For a general performance question, e.g. the benchmark result you got by yourself is not expected, please provide the following information:
    - Your cluster's topology architecture.
       2 servers for tidb and pd
       4 servers for tikv
       Server Info：
       OS: CentOS Linux release 7.6.1810
       CPU: Intel(R) Xeon(R) Silver 4110 CPU @ 2.10GHz X32
       MEM: total 255G  and 150G available
       
    - A simple description of you workload.

**Comment by lonng** [comment]
@chenzheng1024 Seems the major consume time is `Cop_wait_avg`, Is your TiKV overload?

**Comment by breeswish** [comment]
According to 

```
Cop_proc_avg: 0.026 Cop_proc_p90: 0.026 Cop_proc_max: 0.026
Cop_wait_avg: 8.013 Cop_wait_p90: 8.013 Cop_wait_max: 8.013
```

this request is processed instantly but took a long time waiting for other requests to complete.

**Comment by lonng** [comment]
@chenyang8094 Can you export the metrics in PDF to help us to figure out the reason why wait time is so long?

**Comment by chenzheng1024** [comment]
> 
> 
> @chenyang8094 Can you export the metrics in PDF to help us to figure out the reason why wait time is so long?

[metrics_201907191012.pdf](https://github.com/pingcap/tidb/files/3409141/metrics_201907191012.pdf)
This is my grafana report file in 5 minutes.
And as you say ， the cpu usage is nearly 100%

- top -H

![top](https://user-images.githubusercontent.com/19483855/61504962-dcf84400-aa0f-11e9-85d0-e8e51b18171d.png)

- perf top  -p 417098 --call-graph graph
![proc](https://user-images.githubusercontent.com/19483855/61505135-5859f580-aa10-11e9-99a4-724c02781900.png)

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates you can reopen it.
