### ISSUE TITLE
`update t1 set a=b where a=1 order by b;` gets the wrong result

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#1130]
1.What did you do?
```
create table t1 (a int not null, b int not null);
insert into t1 values (1,2),(1,100);
update t1 set a=b where a=1 order by b;
select * from t1;
```

2.What did you expect to see?
+-----+-----+
| a   | b   |
+-----+-----+
|   2 |   2 |
| 100 | 100 |
+-----+-----+

3.What did you see instead?
+-----+-----+
| a   | b   |
+-----+-----+
| 100 |   2 |
| 100 | 100 |
+-----+-----+

**Comment by XuHuaiyu** [comment]
I get correct result in my TiDB, please have a try again.
@zimulala

**Comment by zimulala** [comment]
Yep, TiDB can get correct result now.
