### ISSUE TITLE
Wrong original column returned

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#11323]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

`select if(1, x, x) as a from t`.

2. What did you expect to see?

ColName is `a`, original column name is empty.

3. What did you see instead?

Both colName and orignal column name is `a`.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by qw4990** [comment]
Close since it is resolved.
