### ISSUE TITLE
What's the roadmap of TiDB 4.0?

### ISSUE THREAD

**Issue by vkingnew** [pingcap/tidb#11348]
## What's the roadmap of TiDB 4.0?

**Comment by shenli** [comment]
@vkingnew Thanks for your question. 
We will publish the updated roadmap next week.

**Comment by meilihao** [comment]
[TiDB V4.0 Roadmap](https://pingcap.com/docs/dev/roadmap/)

**Comment by nullnotnil** [comment]
I am going to close this issue now, but please feel free to re-open if you have further questions. Thanks!
