### ISSUE TITLE
add INFORMATION_SCHEMA.INNODB_TRX table for TiDB

### ISSUE THREAD

**Issue by alwaystest18** [pingcap/tidb#11371]
mysql中可以通过INFORMATION_SCHEMA.INNODB_TRX表来查看当前的事务id等信息，然后结合processlist来关联事务的具体内容，但是tidb中没有这个表，建议增加相关数据，方便跟进当前tidb的中的事务信息

**Comment by jackysp** [comment]
I think it is better to add transaction info to processlist table. There're many columns in innodb_trx not suitable for TiDB. Thanks for your suggestion, @alwaystest18 !

**Comment by nullnotnil** [comment]
It might also be possible to add something like performance_schema.data_locks (which replaces innodb_trx in MySQL 8.0).

**Comment by zbingwen** [comment]
I think  it is better .  I get lock detail difficult  by lock manager in grafana.

**Comment by morgo** [comment]
TiDB now has [lock view.](https://docs.pingcap.com/tidb/dev/information-schema-data-lock-waits) Does this satisfy your request?

**Comment by takaidohigasi** [comment]
https://docs.pingcap.com/tidb/stable/information-schema-tidb-trx

* information_schema.CLUSTER_TIDB_TRX
* information_schema.TIDB_TRX

may help
