### ISSUE TITLE
Why data ID increment 1000?.

### ISSUE THREAD

**Issue by insionng** [pingcap/tidb#1139]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.1

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN="/mnt/Gopath/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/mnt/Gopath"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -fmessage-length=0"
CXX="g++"
CGO_ENABLED="0"

```

3. What did you do?
If possible, provide a recipe for reproducing the error.

Program does not have any errors, it seems this is tidb certain default settings?

4. What did you expect to see?
```
http://inchina.xin:8000/topic/1/
http://inchina.xin:8000/topic/2/
http://inchina.xin:8000/topic/3/
http://inchina.xin:8000/topic/4/
```

5. What did you see instead?

I use tidb inside a Web application based on golevedb. I found the data row ID to 1000 range for growth.
Like this:
```
http://inchina.xin:8000/topic/1/
http://inchina.xin:8000/topic/1001/
http://inchina.xin:8000/topic/2001/
http://inchina.xin:8000/topic/4001/
```

**Comment by shenli** [comment]
@insionng Thanks for your feedback.
For performance issue, we allocate auto_increment id in a batch way.
For example if two sessions are insert data in the same time and the global auto_increment id is 0. One session will get id range 1~1000, the other session will get id range 1001~2000. So for the second session, it will use ids from 1001.
In brief, TiDB guarantee allocate increment ids but not continuous increment ids.
So I guess you insert each row with a unique session?

**Comment by shenli** [comment]
May I see your schema and SQL statement?

**Comment by insionng** [comment]
@shenli I can probably guess are designed to performance.
However, this figure could one day grow to very large it? that can't afford it?

**Comment by shenli** [comment]
For each table we have a unique auto_id counter. Its type is int64. So I guess it is OK.
Or we can shrink the batch size.

**Comment by insionng** [comment]
@shenli Then, this figure can I change it?

**Comment by shenli** [comment]
Unfortunately it is a private attribute :( https://github.com/pingcap/tidb/blob/master/meta/autoid/autoid.go#L29

**Comment by insionng** [comment]
@shenli Well, thanks for your answer!
