### ISSUE TITLE
Is there any plan for the support of big transactions?

### ISSUE THREAD

**Issue by dnfhujun** [pingcap/tidb#11398]
目前了解到如果要从mysql同步到tidb，tidb只能支持单个事务30万行的数据，这个支持行数比较少，有考虑后期在大事务这块的支持么，这个也是从mysql迁移到tidb最大的困扰

**Comment by jackysp** [comment]
Yes, it is in our plan now. We plan to enlarge the limit of transaction size to 10GB, and remove the kv count limit. Thanks for your report, @dnfhujun !

**Comment by dnfhujun** [comment]
Is there a specific time node?

**Comment by jackysp** [comment]
This December (release 4.0).

**Comment by nullnotnil** [comment]
Support for large transactions was added in 4.0: https://pingcap.com/blog/large-transactions-in-tidb

I am going to close this issue now, but please feel free to re-open if you have additional questions. Thanks!
