### ISSUE TITLE
Insert zero date successfully in default sql mode

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#11403]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(a date);
insert into t values('0000-00-0');
```

Relate issue: #8637

2. What did you expect to see?
```
mysql> create table t(a date);
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t values('0000-00-0');
ERROR 1292 (22007): Incorrect date value: '0000-00-0' for column 'a' at row 1
```

3. What did you see instead?
```
mysql> create table t(a date);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values('0000-00-0');
Query OK, 1 row affected (0.00 sec)

mysql> select * from t;
+------------+
| a          |
+------------+
| 0000-00-00 |
+------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
master

**Comment by jackysp** [comment]
Thanks for your report, @wjhuang2016 ! Would you want to fix it?

**Comment by wjhuang2016** [comment]
> Thanks for your report, @wjhuang2016 ! Would you want to fix it?

Yeah, I will try to fix it.

**Comment by jackysp** [comment]
Thanks, @wjhuang2016 !
