### ISSUE TITLE
It might be better for some date function to return null when the format is invalid

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#1141]
`DATA_ADD`, `DAYNAME`, etc. should probably return NULL for a invalid time format as https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html says:

> Other functions expect complete dates and return NULL for incomplete dates. These include functions that perform date arithmetic or that map parts of dates to names.

---

Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
   go1.6.1

2. What operating system and processor architecture are you using (`go env`)?
   linux_amd64

3. What did you do?
   `SELECT DATE_ADD('2010-10-0', INTERVAL 1 DAY);`

4. What did you expect to see?
```
+---------------------------------------+
| DATE_ADD('2010-10-0', INTERVAL 1 DAY) |
+---------------------------------------+
| NULL                                  |
+---------------------------------------+
1 row in set, 1 warning (0.00 sec)

```

5. What did you see instead?
```
ERROR 1105 (HY000): DateArith invalid args, need date but get types.Datum
```

**Comment by shenli** [comment]
@zyguan Thanks for your report!
Have test this case on MySQL in strict mode?

**Comment by zyguan** [comment]
I'm not very sure. I tested it on the latest mysql docker image and it said that strict mode became the default since 5.7.

**Comment by zyguan** [comment]
@shenli Here is the output:
```
mysql> show variables like 'sql_mode';
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| Variable_name | Value                                                                                                                                     |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
| sql_mode      | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+---------------+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> SELECT DATE_ADD('2010-10-0', INTERVAL 1 DAY);
+---------------------------------------+
| DATE_ADD('2010-10-0', INTERVAL 1 DAY) |
+---------------------------------------+
| NULL                                  |
+---------------------------------------+
1 row in set, 1 warning (0.00 sec)

mysql>
```

**Comment by shenli** [comment]
In strict mode, warning will be treated as error. 
"1 row in set, 1 warning (0.00 sec)"

http://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_allow_invalid_dates

**Comment by zyguan** [comment]
I see, invalid date format causes error in statements like `INSERT` and `UPDATE`. However, for `SELECT`, null is retured in mysql. So, for simplicity, just keep things as is.
