### ISSUE TITLE
Use global timestamp to check bgJob owner and ddlJob owner

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1142]
We use local time to check bgJob owner and ddlJob owner. This will meet error when two machine with different time. So we should use global timestamp.

**Comment by ngaut** [comment]
Is it been fixed ? @zimulala

**Comment by zimulala** [comment]
No, it isn't. @ngaut

**Comment by coocood** [comment]
Fixed by etcd owner manager.
