### ISSUE TITLE
durt read and GC life time is shorter than transaction duration

### ISSUE THREAD

**Issue by flyinget** [pingcap/tidb#11453]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

firt error:
when tikv_gc_life_time=10m
query sql or update sql take error
java.sql.SQLException: GC life time is shorter than transaction duration, transaction starts at 2019-07-25 00:50:40.158 +0000 UTC, GC safe point is 2019-07-25 00:54:22.858 +0000 UTC

when restart application
GC ERROR temporary  disappear 
but
at next gc time this error may be happen.

second error:
the update sql get dirt read record

for example
update number_interval_rule SET modifier = ?, gmt_modified = now() ,value_current=? ,date_current=? ,version_number=version_number+1 WHERE id=? and agent_id = ? and version_number = ?

at 15:34 we can see  version_number = 7566 in the log

at 18:00 we can se version_number = 7566 the same to  the record at 15:34

but between two times，version_number is  accumulation from 7566 and has many successful log
2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.0.0-rc.1-359-gd977edf8a
Git Commit Hash: d977edf8a39ccd1972d1fe1b17855b63b934a09d
Git Branch: master
UTC Build Time: 2019-07-19 11:50:55
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

other info
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>druid</artifactId>
            <version>1.1.10</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.11</version>
        </dependency>

**Comment by flyinget** [comment]
before update sql
we select * from number_interval_rule  where id =XX

**Comment by crazycs520** [comment]
@flyinget Thanks for your reporting.
In TiDB, If the duration of the transaction execution more than GC lifetime (10 min default), the transaction will return an error like `GC lifetime is shorter than transaction duration....`

You can reduce transaction size to avoid this problem.
