### ISSUE TITLE
make: *** [godep] Error 129 / Unknown Git parameter

### ISSUE THREAD

**Issue by bitcubate** [pingcap/tidb#1146]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

go version go1.4.2 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/opt/tidb/tidb-master/"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?

[root@mych-server-2 tidb-master]# make

4. What did you expect to see?

Expected it to build

5. What did you see instead?

go get google.golang.org/grpc
git -C $(echo /opt/tidb/tidb-master/|cut -d':' -f1)/src/google.golang.org/grpc checkout dec33edc378cf4971a2741cfd86ed70a644d6ba3
Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
make: *** [godep] Error 129

**Comment by shenli** [comment]
@bitcubate Thanks for your report!
"git -C checkout version" is a temporary solution to make etcd compatible with grpc. The "-C" parameter maybe not supported by old git client.
We will remove this when etcd compatible with the latest grpc.

**Comment by bitcubate** [comment]
Okay, thanks. The solution would be get the latest git client I guess
