### ISSUE TITLE
CI failed

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#11481]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
One of the unit tests failed, See the details: https://circleci.com/gh/pingcap/tidb/42094?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

[build_42094_step_102_container_0.txt](https://github.com/pingcap/tidb/files/3439743/build_42094_step_102_container_0.txt)

**Comment by winkyao** [comment]
@amyangfei is investigating this issue.

**Comment by winkyao** [comment]
@ngaut It is fixed by https://github.com/pingcap/tidb/pull/11465/files

**Comment by winkyao** [comment]
The error message is:
```
----------------------------------------------------------------------
FAIL: client_fail_test.go:32: testClientSuite.TestPanicInRecvLoop

client_fail_test.go:57:
    c.Assert(err, IsNil)
... value *errors.fundamental = injected error in batchRecvLoop ("injected error in batchRecvLoop")


----------------------------------------------------------------------
```
