### ISSUE TITLE
select group by not always return the first row 

### ISSUE THREAD

**Issue by chrissata** [pingcap/tidb#11497]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
**1)create table.**

> CREATE TABLE `testtable` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `deleted` smallint(6) NOT NULL,
  `m_id` bigint(20) DEFAULT NULL,
  `title` varchar(250) NOT NULL,
  `seq` bigint(20) DEFAULT '0',
  `val` varchar(64) DEFAULT '31',
  `online` smallint(6) DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `ix_testtable_deleted` (`deleted`),
  KEY `testtable_mid_seq` (`m_id`,`seq`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1000;

**2) insert into testtable  at least 33(more than 32) records with same m_id and unique seq value** 

**3) do sql query:** 

> select 
  tmp.* 
from
  (SELECT 
    p.id,
    p.title,
    p.m_id
  FROM
    testtable p 
  WHERE p.m_id IN (1001) 
  ORDER BY p.seq DESC
  limit 5000000) tmp 
GROUP BY tmp.m_id;

2. What did you expect to see?
The sql output should be the one who has the biggest seq value.

3. What did you see instead?
Sometimes the result was the one who has the biggest seq value and sometimes not.
If the inner subquery returns less than 32, the result works as expected just like mysql.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.1.8
Git Commit Hash: 9a2d2da372947a50a02f9b9238a49f2db7ab9971
Git Branch: HEAD
UTC Build Time: 2019-04-12 07:48:47
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by winoros** [comment]
@chrissata 
This is expected behavior. If you want max value. Use aggregate function `MAX`. We don't guarantee the result if it's not a strict GROUP BY.

**Comment by chrissata** [comment]
> @chrissata
> This is expected behavior. If you want max value. Use aggregate function `MAX`. We don't guarantee the result if it's not a strict GROUP BY.
> We won't keep the same bahavior as MySQL. That would influence the execution speed.

Thanks for your reply.
But I'm not expecting the max value , what I want are the records which contains the max value for each group.  And now I'm quite sure that tidb-2.1 just can not handle those kind of scenarios which are quite common buzz requirements. Due to the limitation, I will try to upgrade to 3.0 which supports window fuction feature  and that should meet my requirements.
