### ISSUE TITLE
Left outer join reports "Column colx is ambiguous" error

### ISSUE THREAD

**Issue by wuzk** [pingcap/tidb#11496]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
使用mysql执行以下语句是好的，但是在tidb中执行报 “SQL错误(1105) : Column workreport_its.b.id is ambiguous”  workreport_it是数据库名，b 是左连接的表的别名，见下语句。
	SELECT
			A.ID ,
			a.missiontype,
			a.employeeid,
			b.projectcode,
			b.projectname,
			a.MISSIONSTATUS,
			a.startdate,
			a.enddate,
			C.username AS MISSIONEMPNAME,
			e.departmentname,
			d.username AS EMPLOYEENAME,
			'1' AS fromTable
		FROM
			pg_information a
		LEFT JOIN sys_project b ON a.projectid = b.id
		LEFT JOIN USER_USERINFO C ON A.MISSIONEMPID = C.USERID
		LEFT JOIN user_userinfo d ON a.EMPLOYEEID = d.userid
		LEFT JOIN dept_department e ON a.departmentid = e.departmentid
		WHERE
			a.bgapproveempid = 1
		AND missiontype IN ('1', '2')
		AND MISSIONAPPROVESTATUS IS NULL
		AND missionstatus IN ('0', '1')
		AND a.validflag = '0'
		UNION
			SELECT
				A.ID,
				a.missiontype,
				a.employeeid,
				b.projectcode,
				b.projectname,
				a.MISSIONSTATUS,
				a.startdate,
				a.enddate,
				C.username AS MISSIONEMPNAME,
				e.departmentname,
				d.username AS EMPLOYEENAME,
				'2' AS fromTable
			FROM
				pg_information_approve a
			LEFT JOIN sys_project b ON a.projectid = b.id
			LEFT JOIN USER_USERINFO C ON A.MISSIONEMPID = C.USERID
			LEFT JOIN user_userinfo d ON a.EMPLOYEEID = d.userid
			LEFT JOIN dept_department e ON a.departmentid = e.departmentid
			WHERE
				1 = 1
			AND a.missionapprovestatus = '0'
			AND enddate > str_to_date('2019-07-29', '%Y-%m-%d')
			AND a.projectid IN (
				SELECT
					id
				FROM
					sys_project
				WHERE
					concat(',' , mainprojpj , ',') IN (',1,')
			)

2. What did you expect to see?
希望执行效果和mysql一致。

3. What did you see instead?
 “SQL错误(1105) : Column workreport_its.b.id is ambiguous”

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.0
Git Commit Hash: 60965b006877ca7234adaced7890d7b029ed1306
Git Branch: HEAD
UTC Build Time: 2019-06-28 12:14:07
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by wuzk** [comment]
[union_ambiguous.txt](https://github.com/pingcap/tidb/files/3440480/union_ambiguous.txt)

**Comment by winoros** [comment]
@wuzk This bug is fixed in the later commit of release-3.0 branch.
We'll release a minor release this week. Upgrade to it later can solve the problem.

**Comment by yanbinghui** [comment]
Hi, @winoros Have this bug fixed now? I also encounter this issue.

**Comment by lzmhhh123** [comment]
@yanbinghui The master branch has been fixed. We will publish release 3.0.2 tomorrow. Also will be fixed in this release.
