### ISSUE TITLE
window function: function name of ErrWindowInvalidWindowFuncUse should be lowercase

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11508]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
mysql> delete from table60_int_autoinc order by (SUM(a) over());
```

2. What did you expect to see?

```mysql
mysql> delete from table60_int_autoinc order by (SUM(a) over());
ERROR 3593 (HY000): You cannot use the window function 'sum' in this context.'
```

3. What did you see instead?

```mysql
mysql> delete from table60_int_autoinc order by (SUM(a) over());
ERROR 3593 (HY000): You cannot use the window function 'SUM' in this context.'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by tcmichael** [comment]
@lamxTyler 
I have hard time to add unit test for https://github.com/pingcap/tidb/blob/a92902aeee3a49c835d5f0beb8f1e6dbb645fc3a/planner/core/logical_plan_builder.go#L1244

Could you give me an example sql to cover that line?

**Comment by lamxTyler** [comment]
What about the sql in the issue description?

**Comment by tcmichael** [comment]
The sql goes here: https://github.com/pingcap/tidb/blob/a92902aeee3a49c835d5f0beb8f1e6dbb645fc3a/planner/core/expression_rewriter.go#L326

**Comment by SunRunAway** [comment]
Maybe this one, `SELECT * from table60_int_autoinc having ROW_NUMBER() over() ;`
