### ISSUE TITLE
executor: distsql.selectResult is not necessary to fetch asynchronously.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11501]
## Performance Questions

- What version of TiDB are you using?

ebfb2ae on the master branch

- What's the observed and your expected performance respectively?

[`distsql.selectResult`](https://github.com/pingcap/tidb/blob/master/distsql/select_result.go#L58) uses [`kv.Response.Next()`](https://github.com/pingcap/tidb/blob/master/kv/kv.go#L244) to fetch data from TiKV, since `kv.Response` is already asynchronously implemented by [`copIterator`](https://github.com/pingcap/tidb/blob/master/store/tikv/coprocessor.go#L324), perhaps `distsql.selectResult` is not necessary to fetch asynchronously again.

If deciding to do this, we need a benchmark result in avoiding performance regression.

**Comment by ichn-hu** [comment]
I am interested to investigate more on this issue, wil start to read related source code!
