### ISSUE TITLE
Use two goroutines to speed up "load data"

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#11517]
According to https://github.com/pingcap/tidb/blob/77b6858bf08c2c20dd16b9f7f8d291b17c13b91e/server/conn.go#L1057

There are two steps for "load data" statement, we can use two goroutine to speed up the process, one goroutine for preparing data, and another goroutine for committing.

**Comment by cfzjywxk** [comment]
will do some experiments on this. Things need to consider
- consume memory resources, especailly when commit is slow
- load data statement may be changed to atomic like innodb in the future, this optimization may not work
