### ISSUE TITLE
tidb 2.1.9 upgrade  to 3.0.1 ,grafana no data point

### ISSUE THREAD

**Issue by yester354** [pingcap/tidb#11546]
after upgrading to tidb 3.0.1，the monitor data of tikv appear abnormal

1、tidb 2.1.9 runs well，grafana work good
2、using ansible-playbook upgrade to tidb 3.0.1 and upgrade monitor 
3、only the monitor data of tikv display no data point in grafana web 
4、there are no errors in grafana and promethus logs
5、by visiting promethus status data on web，tikv endpoints are all up，and Scrape Duration is less then 200ms
6、i can also click metrics url to visit tikv monitor data by promethus targets web url
7、promethus version 2.8.1，grafana-6.1.6 ，pushgateway-0.7.0

**Comment by winkyao** [comment]
@liubo0127 PTAL

**Comment by liubo0127** [comment]
Note that when upgrading the cluster version, you also need to execute `ansible-playbook rolling_update_monitor.yml` to upgrade the monitor.

TiKV monitoring data was collected by `Pushgateway` before the upgrade. In version `3.0 or later`, it was changed to `Prometheus` to pull the monitoring data directly. The expressions also have some changes, which will cause the original TiKV dashboard to display anomalies.

In addition, in versions `3.0 or later`, TiKV dashboard is divided into three dashboards: `tikv_detail`, `tikv_summary`, and `tikv_trouble_shooting` depending on the object. These three dashboards are available in the new version. If there are problems with these three dashboards, please feedback again.

**Comment by yester354** [comment]
it wokrs ，thanks
