### ISSUE TITLE
TiKv节点的机器磁盘扩容

### ISSUE THREAD

**Issue by vito16** [pingcap/tidb#11569]
版本：3.0.1
之前安装TiKV的时候，是在阿里云的ecs上，每个TiKV节点的磁盘大小为500G（系统盘）
现在想扩容2000G，自己能想到的方法这几个？哪一个合适一点呢？ 我需要保留现有数据。  
1. 新加数据盘（2000G），这种方案我是否应该还要做数据迁移以及其他挂载的动作？
2. LVM扩容方案，这种不知道对数据会不会有影响。

**Comment by gregwebs** [comment]
LVM does have a noticeable performance overhead when combining disk, so it is not recommended if you need maximum write performance. I am not familiar with disk on Ali cloud, but someone else might be able to help you.

**Comment by iamxy** [comment]
It is not recommended to use the system disk as a data disk. I recommend that you mount a large data disk separately, and then follow the steps below.

1. Mount a new disk to ECS instance with size > 2000G
2. Stop the TiDB cluster
2. Copy tikv/pd 's data to a directory on the new disk
3. Modify the command line parameters of tikv/pd , make sure to use the new path for data-dir
4. Try to start cluster

Note
If you are using an AliCloud network disk, you must know that using network disks will significantly affect the performance of database read-write latency.

**Comment by vito16** [comment]
> It is not recommended to use the system disk as a data disk. I recommend that you mount a large data disk separately, and then follow the steps below.
> 
> 1. Mount a new disk to ECS instance with size > 2000G
> 2. Stop the TiDB cluster
> 3. Copy tikv/pd 's data to a directory on the new disk
> 4. Modify the command line parameters of tikv/pd , make sure to use the new path for data-dir
> 5. Try to start cluster
> 
> Note
> If you are using an AliCloud network disk, you must know that using network disks will significantly affect the performance of database read-write latency.

thanks, @iamxy  @gregwebs 
I understand what you mean.
I am also using the new data disk and copying the original tidb-data to the new datta disk.
But with regard to the 4 you mentioned

> 4. Modify the command line parameters of tikv/pd , make sure to use the new path for data-dir

 how should I modify the configuration?

other question：
I found the data-dir on  

> /home/tidb/deploy/data/db/

But the documentation tells me that on

> /tmp/tikv/store

Did I understand the mistake?

**Comment by iamxy** [comment]
If you are deploying clusters with TiDB Ansible, you can find instructions here.
[Ansible Deployment](https://pingcap.com/docs/v3.0/how-to/deploy/orchestrated/ansible/
)

or if you deploy binaries from scratch, refer to this guide.
[From binary](https://pingcap.com/docs/v3.0/how-to/get-started/deploy-tidb-from-binary/)

**Comment by vito16** [comment]
> If you are deploying clusters with TiDB Ansible, you can find instructions here.
> [Ansible Deployment](https://pingcap.com/docs/v3.0/how-to/deploy/orchestrated/ansible/)
> 
> or if you deploy binaries from scratch, refer to this guide.
> [From binary](https://pingcap.com/docs/v3.0/how-to/get-started/deploy-tidb-from-binary/)

Yeah,i deploying tidb with tidb-ansible.
I have successfully added the data disk and switched the new data-dir.
1. stop tidb-service
```
ansible-playbook stop.yml
```
2. update inventory.ini  
```
## Global variables
[all:vars]
##deploy_dir = /home/tidb/deploy
deploy_dir = /data1/deploy
```
3. move old data-dir to new data-dir(tikv and tidb)
```
eg:/home/tidb/deploy  -->  /data1/deploy
```
4. check&change new data-dir's user and group(tikv and tidb)
```
deploy'user and group must be tidb-deploy-user(eg:tidb)
```
like this:
```
drwxr-xr-x 14 tidb tidb  4096 May 24 00:41 deploy
```
5. start tidb-service
```
ansible-playbook start.yml
```

enjoy  -,-
