### ISSUE TITLE
Kill pd leader cause wrong result

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1156]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
Linux

3. What did you do?
Run a sql statement when killing pd leader.

4. What did you expect to see?
Get right result set.

5. What did you see instead?
Get empty result set.

**Comment by ngaut** [comment]
Fixed.
