### ISSUE TITLE
Too many regions

### ISSUE THREAD

**Issue by junplus** [pingcap/tidb#11575]
our storage size is nearly 7.8TB, but the number of regions is almost 390,000.

if each region is full of 64M, we can calculate the number of regions should be 120,000.

we have already enable the 'region merge' feature,  but effect was not obvious.

is there any solution ? can i expand the region size to 128M or 256M ?

**Comment by disksing** [comment]
Hi @junplus . There are some reasons could lead the mismatch:
1. Region data is compressed before persistent to disk in SST format, so storage size is less than the sum of all regions sizes.
2. By default, PD only merges regions that are less than 20MB. If the workload is uniformity delete keys, it could end up with all regions size are slightly larger than 20MB.

Increase region size is an option here. You may want to increase pd's `max-merge-region-size` option too. By the way, if it is the performance overhead bothers you when there are too many regions, you can try the hibernate region feature.

**Comment by junplus** [comment]
> Hi @junplus . There are some reasons could lead the mismatch:
> 
> 1. Region data is compressed before persistent to disk in SST format, so storage size is less than the sum of all regions sizes.
> 2. By default, PD only merges regions that are less than 20MB. If the workload is uniformity delete keys, it could end up with all regions size are slightly larger than 20MB.
> 
> Increase region size is an option here. You may want to increase pd's `max-merge-region-size` option too. By the way, if it is the performance overhead bothers you when there are too many regions, you can try the hibernate region feature.

thx,  the 'max-merge-region-size' option is currently 64M, i'll try to increase region size later.
