### ISSUE TITLE
privilege: support FILE privilege in TiDB like MySQL

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#11583]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

support FILE privilege in TiDB like MySQL, so users can control file related operations by users to reduce secure risks

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by morgo** [comment]
This has already been added for `SELECT INTO OUTFILE` in https://github.com/pingcap/tidb/pull/19553

It is not applicable for the two remaining cases:

`LOAD DATA` does not support the local option:
```sql
mysql> LOAD DATA INFILE '/tmp/t.txt' INTO table test.t1;
ERROR 1105 (HY000): Load Data: don't support load data without local field
```

The function `LOAD_FILE()` has not been added, see https://github.com/pingcap/tidb/issues/8436

```sql
mysql> SELECT LOAD_FILE('/tmp/t.txt');
ERROR 1305 (42000): FUNCTION load_file does not exist
```

As such, I am going to go ahead and close this issue.
