### ISSUE TITLE
we need to forbid modifying binary column or regenerate data

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#11597]
# Bug Report

## 1. What did you do?

```sql
create table t(a binary(20))
```

change the data type of column `a`:

```sql
alter table t modify column a binary(10);
```

## 2. What did you expect to see?

When modifying a column from `BINARY[X]` to `BINARY[Y]`, the underlying data should be regenerated. 

* a short workaround is to forbid these kind of alter table DDLs
* better to be fixed by regenerating the data when `x` is not equals to `y`.

## 3. What did you see instead?

The data type of column `a` is modified successfully.

## 4. What version of TiDB are you using?

```
➜ ./bin/tidb-server -V
Release Version: v4.0.0-alpha-18-gcfee8c098
Git Commit Hash: cfee8c09843b4b061880fa4d83529b2cfdbe3be2
Git Branch: master
UTC Build Time: 2019-08-03 07:36:37
GoVersion: go version go1.12.5 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by nullnotnil** [comment]
This is now forbidden in master:
```sql
mysql> create table t(a binary(20));
Query OK, 0 rows affected (0.10 sec)

mysql> alter table t modify column a binary(10);
ERROR 8200 (HY000): Unsupported modify column: length 10 is less than origin 20
mysql> 
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-798-gd941ff5cc
Edition: Community
Git Commit Hash: d941ff5cc8b4babf9dcfdd91b66a5c53b798c122
Git Branch: master
UTC Build Time: 2020-07-18 05:54:02
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue because full support is being tracked in https://github.com/pingcap/tidb/issues/18283

Please feel free to re-open this if I am in error :-) Thanks!
