### ISSUE TITLE
Privileges for connection are re-checked after creating user with more specific hostname

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#11596]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I connect as 'root'@'%' and then create a user with a host that more specifically matches the IP I connect from, in this case 127.0.0.1. It seems that TiDB re-checks privileges for the existing connection and, since the new user 'root'@'127.0.0.1' does not have any privileges yet, my GRANT is denied.
```
MySQL [test]> show processlist;
+------+------+-----------+------+---------+------+-------+------------------+
| Id   | User | Host      | db   | Command | Time | State | Info             |
+------+------+-----------+------+---------+------+-------+------------------+
|    1 | root | 127.0.0.1 | test | Query   |    0 | 2     | show processlist |
+------+------+-----------+------+---------+------+-------+------------------+
1 row in set (0.027 sec)

MySQL [test]> select current_user();
+----------------+
| current_user() |
+----------------+
| root@%         |
+----------------+
1 row in set (0.029 sec)

MySQL [test]> create user 'root'@'127.0.0.1';
Query OK, 1 row affected (0.185 sec)

MySQL [test]> grant all privileges on *.* to 'root'@'127.0.0.1' with grant option;
ERROR 1105 (HY000): privilege check fail
```

2. What did you expect to see?

TiDB should follow the MySQL practice that "Global privileges and passwords are unaffected for a connected client. These changes take effect only in sessions for subsequent connections." (https://dev.mysql.com/doc/refman/5.7/en/privilege-changes.html)

3. What did you see instead?

(above)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
tidb_version(): Release Version: v3.0.1
Git Commit Hash: 9e4e8da3c58c65123db5f26409759fe1847529f8
Git Branch: HEAD
UTC Build Time: 2019-07-16 01:03:40
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by tiancaiamao** [comment]
Verified this bug exists on v3.0.1, and is fixed on v3.0.14 afterword, v4.0+
