### ISSUE TITLE
wrong results when IF function along with float argument

### ISSUE THREAD

**Issue by jingyugao** [pingcap/tidb#11601]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
SELECT  IF(0.1, 1, 2) FROM t1;
2. What did you expect to see?
+---------------+
| IF(0.1, 1, 2) |
+---------------+
|             1 |
+---------------+
1 row in set (0.00 sec)

3. What did you see instead?
+---------------+
| IF(0.1, 1, 2) |
+---------------+
|             2 |
+---------------+
1 row in set (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: None
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by jingyugao** [comment]
In tidb, almost all builtIn*Sig function use the result of `evalInt` to check true or false.
This is not ok when args is float64 which is less than 1, it will be convert to 0 by `evalInt`.
So we should replace `evalInt` with `evalReal`.(By the way,if the argis to small and is out of the float64 accuracy,such as 1e-1000, it should be converted to 0)

**Comment by zz-jason** [comment]
`evalInt` means this expression signature should return an `int` result. For this case, we should implement `evalInt`. But in order to get the correct result, we should calling `args[0].EvalReal()` other than `args[0].EvalInt()`.

**Comment by jingyugao** [comment]
> `evalInt` means this expression signature should return an `int` result. For this case, we should implement `evalInt`. But in order to get the correct result, we should calling `args[0].EvalReal()` instead of `args[0].EvalInt()`.

Yes,I have fix the logic op https://github.com/pingcap/tidb/pull/11587,but many builtinfunc doesnt implement `evalReal`, so it may be difficult to handle.

**Comment by lance6716** [comment]
> `evalInt` means this expression signature should return an `int` result. For this case, we should implement `evalInt`. But in order to get the correct result, we should calling `args[0].EvalReal()` instead of `args[0].EvalInt()`.

Seems that when `getFunction` `arg[0]`'s type is `ETInt`, so 0.1 cast to 0. But if we change the type to `ETReal`, many int-returned functions added a unnatural cast as below (from #15016)

```
need:
... if(ne(Column#9, 0) ...
got:
... if(cast(ne(Column#9, 0)) ...
```

didn't find a good way to handle

**Comment by SunRunAway** [comment]
`CASE` has a similar problem,

W/ MySQL 5.7
```mysql
mysql> select case when 0.1 then 1 else 2 end;
+---------------------------------+
| case when 0.1 then 1 else 2 end |
+---------------------------------+
|                               1 |
+---------------------------------+
1 row in set (0.00 sec)
```

W/ TiDB,
```mysql
mysql> select case when 0.1 then 1 else 2 end;
+---------------------------------+
| case when 0.1 then 1 else 2 end |
+---------------------------------+
|                               2 |
+---------------------------------+
1 row in set (0.00 sec)
```
