### ISSUE TITLE
replace `context.WithValue` string key to typed `struct{}` key

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#11634]
Current TiDB many places uses a string as the context key which leads to allocations.

for example:

https://github.com/pingcap/tidb/blob/eae30ebbcb8464d4644598db459337998ab1d43b/store/tikv/coprocessor.go#L52

https://github.com/pingcap/tidb/blob/7f3bff8afef001c4d93f4c7632ad9a9595cded8b/session/session.go#L505

https://golang.org/pkg/context/#WithValue 

> To avoid allocating when assigning to an interface{}, context keys often have concrete type struct{}. Alternatively, exported context key variables' static type should be a pointer or interface.

https://www.dropbox.com/s/9u74uvpq8vowwdo/Screenshot%202019-07-30%2012.39.20.png?dl=0

instead, we'd better using `type xKey struct{}` just like opentracing does https://github.com/opentracing/opentracing-go/blob/master/gocontext.go#L12 to reduce alloc

**Comment by lauhg** [comment]
I can work on this if nobody else is.
