### ISSUE TITLE
Add support for sqlectron.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1165]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   go version go1.6 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/lq/project"
   GORACE=""
   GOROOT="/home/lq/go"
   GOTOOLDIR="/home/lq/go/pkg/tool/linux_amd64"
   GO15VENDOREXPERIMENT="1"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="g++"
   CGO_ENABLED="1"
3. What did you do?
   Open sqlectron, connect to TiDB
4. What did you expect to see?
   Normal log in TiDB's log
5. What did you see instead?
   sqlectron seems run the following loop:
   
     SELECT routine_name, routine_type
     FROM information_schema.routines
     WHERE routine_schema = database()
     ORDER BY routine_name

**Comment by morgo** [comment]
The statement now works in TiDB (returning empty results).  I downloaded sqlectron-gui 1.30 and verified that it seems to work fine in TiDB.  No statements were logged as failing.

I am going to close this issue for now.  Please feel free to re-open it if you have any questions.  Thanks!
