### ISSUE TITLE
SHARD_ROW_ID_BITS seems no effect

### ISSUE THREAD

**Issue by junplus** [pingcap/tidb#11669]
![image](https://user-images.githubusercontent.com/28999107/62671794-c4ee6180-b9ca-11e9-8681-3b124e23d591.png)

it seems that most of keys are currently written to one tikv instance.
i set 'SHARD_ROW_ID_BITS' to 4 at 10:10, but it doesn't work well.

**Comment by zimulala** [comment]
@junplus Thanks for your feedback!
I don't know how you can confirm that this has no effect. "SHARD_ROW_ID_BITS" just modify a table. Could you confirm the TiKV region where this table is located? Or only write to this table at the time.

**Comment by junplus** [comment]
> @junplus Thanks for your feedback!
> I don't know how you can confirm that this has no effect. "SHARD_ROW_ID_BITS" just modify a table. Could you confirm the TiKV region where this table is located? Or only write to this table at the time.

we have 3 tables  and we run 'SHARD_ROW_ID_BITS=4' on each table.

**Comment by zimulala** [comment]
@junplus 
Could you show me the result of "show create table" and "select tidb_version()"?
What about the written statement? Will there be a lot of rows inserted in a transaction?

**Comment by junplus** [comment]
> @junplus
> Could you show me the result of "show create table" and "select tidb_version()"?
> What about the written statement? Will there be a lot of rows inserted in a transaction?

1.schema
CREATE TABLE `t` (
  `c0` varchar(10) NOT NULL DEFAULT '0' ,
  `c1` smallint UNSIGNED NOT NULL DEFAULT '0',
  `c2` mediumint NOT NULL DEFAULT ‘0',
  `c3` json NOT NULL ,
  `c4` bigint UNSIGNED NOT NULL DEFAULT '0',
  `c5` bigint UNSIGNED NOT NULL DEFAULT '0',
  `c6` bigint UNSIGNED NOT NULL,
  PRIMARY KEY (`c0`,`c1`,`c2`,`c6`),
  KEY `k1` (`c0`,`c4`),
  KEY `k2` (`c6`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE ( `c6` ) (
  PARTITION rx0 VALUES LESS THAN (1561910400000),
  PARTITION rx1 VALUES LESS THAN (1564588800000),
  PARTITION rx2 VALUES LESS THAN (1567267200000)
  ...
)
i've changed the column name and erase the comment.

2.version
Release Version: v2.1.8
Git Commit Hash: 9a2d2da372947a50a02f9b9238a49f2db7ab9971
Git Branch: HEAD
UTC Build Time: 2019-04-12 07:48:47
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

3.Will there be a lot of rows inserted in a transaction?
no, each transaction contains only one 'insert' statement.

**Comment by junplus** [comment]
i've got that 'SHARD_ROW_ID_BITS' is not well supported by partition table in v2.x
