### ISSUE TITLE
How to know if there are hot regions from PD statistics

### ISSUE THREAD

**Issue by junplus** [pingcap/tidb#11661]
i've got a tikv with 10000 regions, and  the current number of "Hot write Region’s leader distribution" is 4 or 5.

how can i know if there are hot regions.

**Comment by youjiali1995** [comment]
`Hot write Region's leader distribution` is the total number of leader Regions under hot write on each TiKV instance.

**Comment by junplus** [comment]
> `Hot write Region's leader distribution` is the total number of leader Regions under hot write on each TiKV instance.

means the larger the better?

**Comment by youjiali1995** [comment]
No. It means there are 4 or 5 hot leader regions in the TiKV.

**Comment by youjiali1995** [comment]
Ideally, it should be 0 or uniformly distributed.

**Comment by junplus** [comment]
> Ideally, it should be 0 or uniformly distributed.

thx, i've got the point.
