### ISSUE TITLE
[Question] About IPv6 support

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb#11701]
## General Question

Q1 :
Tikv doesn't support ipv6 .
Whether Pd support ipv6 ? How about tidb、pump & drainer ？

Q2 :
Whether tools such as pd-ctl, binglogctl, kv-ctl support ipv6?
eg：
`./pd-ctl -u http://[ipv6]:port`

I'm so sorry, we have no env to do the test currently.

**Comment by XuHuaiyu** [comment]
@XSHui 
Sorry for the late reply, we did not try to deploy the TiDB cluster using IPv6,
so we are not sure.

**Comment by XSHui** [comment]
@Xuanwo 

We deploy tidb cluster with ipv4, and transfer ipv6  as param to pd-ctl.

https://github.com/pingcap/pd/issues/1675

**Comment by Xuanwo** [comment]
Welcome to `X` family!

**Comment by Defined2014** [comment]
We support ipv6 since v6.5.1, so close this issue.
