### ISSUE TITLE
Data truncation: invalid time format: '{1969 12 31 17 0 1 0}'

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tidb#11727]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
SET time_zone = '-7:00';
create table t(col0 timestamp not null);
insert into t values('1969-12-31 17:00:01.0');
```

2. What did you expect to see?

normal

3. What did you see instead?

```
Data truncation: invalid time format: '{1969 12 31 17 0 1 0}'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Can be reproduced in both `v2.0.11` and `v2.1.15`

**Comment by bb7133** [comment]
Hi @birdstorm , this issue is closed by #13614, thank you for reporting!
