### ISSUE TITLE
RFE on doc: brief comparison between tidb and vitess

### ISSUE THREAD

**Issue by tjyang** [pingcap/tidb#1173]
Hi

Is it possible to document the difference with [vitess](https://github.com/youtube/vitess) when making  comparison with other DB solution ?
So far my understanding is that vitess is an add-on solution to existing mysql deployment while vitess will need to swap out the mysql instance with tidb.

**Comment by shenli** [comment]
@tjyang Thanks for your feedback!
Vitess is a MySQL sharding solution. It runs as a MySQL proxy. So you need to put MySQL server behind vitess. It does not support distributed transactions.
TiDB is a brand new distributed database which support mysql protocol and syntax. It is a MySQL drop-in replacement. You can enjoy horizontal scalability without losing distributed transactions.

**Comment by tjyang** [comment]
Shen
Thanks for the clarification, Hopefully in the future TiDB vs others DB solution document, vitess invented and used by youtube can by mentioned. Just to show TiDB has special feature Vitess doesn't have.

**Comment by shenli** [comment]
@tjyang OK! Thanks for your report. Please keep eyes on TiDB.
