### ISSUE TITLE
Build failed from Dockerfile 

### ISSUE THREAD

**Issue by darionyaphet** [pingcap/tidb#11738]
## General Question

When I try to build image from source code and using `docker build -t tidb:v3.0.2 .`. 

I found some info like this:

```
go: golang.org/x/sys@v0.0.0-20190109145017-48ac38b7c8cb: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
go: golang.org/x/sys@v0.0.0-20180905080454-ebe1bf3edb33: unrecognized import path "golang.org/x/sys" (https fetch: Get https://golang.org/x/sys?go-get=1: dial tcp 216.239.37.1:443: i/o timeout)
```

Has anyone had the similar problem?

**Comment by aylei** [comment]
Seems like you encountered a network problem, could you please try to configure a network proxy for your docker daemon?

**Comment by aylei** [comment]
Hi @darionyaphet , have you tried later?

**Comment by darionyaphet** [comment]
thanks @aylei I will try it later

**Comment by kolbe** [comment]
@darionyaphet have you had a chance to try this again? Please let us know if you are still encountering problems building from the Dockerfile.

**Comment by darionyaphet** [comment]
yep it have already been solved. thanks ~
