### ISSUE TITLE
Server crashed while doing import from a mysqldump-ed file

### ISSUE THREAD

**Issue by elffikk** [pingcap/tidb#1174]
Please answer these questions before submitting your issue. Thanks!
1. What version of Go are you using (`go version`)?
   1.6
2. What operating system and processor architecture are you using (`go env`)?
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/go-dev"
   GORACE=""
   GOROOT="/usr/local/go"
   GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
   GO15VENDOREXPERIMENT="1"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
   CXX="g++"
   CGO_ENABLED="1"
3. What did you do?
   run server: tidb-server -path /tidb-data
   then mysql import from a mysqldump-ed file of ~700Mb gzipped
4. What did you expect to see?
   data to be imported, or if there are errors to be warned about them
5. What did you see instead?
   it worked for 10+ minutes and some tables where imported
   but then crashed with  

goroutine 46 [select, 10 minutes, locked to thread]:
runtime.gopark(0x1637620, 0xc82072c728, 0x12cd440, 0x6, 0xc8202dfd18, 0x2)
        /usr/local/go/src/runtime/proc.go:262 +0x163
runtime.selectgoImpl(0xc82072c728, 0x0, 0x18)
        /usr/local/go/src/runtime/select.go:392 +0xa67
runtime.selectgo(0xc82072c728)
        /usr/local/go/src/runtime/select.go:215 +0x12
runtime.ensureSigM.func1()
        /usr/local/go/src/runtime/signal1_unix.go:279 +0x358
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1998 +0x1

goroutine 47 [chan receive, 10 minutes]:
main.main.func1(0xc82084c2a0, 0xc821185a40)
        /go-dev/src/github.com/pingcap/tidb/tidb-server/main.go:98 +0x4d
created by main.main
        /go-dev/src/github.com/pingcap/tidb/tidb-server/main.go:102 +0xf32

goroutine 48 [IO wait, 10 minutes]:
net.runtime_pollWait(0x7fc57b670498, 0x72, 0x0)
        /usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(_pollDesc).Wait(0xc8201cec30, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(_pollDesc).WaitRead(0xc8201cec30, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(_netFD).accept(0xc8201cebd0, 0x0, 0x7fc57b670710, 0xc82083a980)
        /usr/local/go/src/net/fd_unix.go:426 +0x27c
net.(_TCPListener).AcceptTCP(0xc8201b5e60, 0x7360a1, 0x0, 0x0)
        /usr/local/go/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8201b5e60, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2427 +0x41
net/http.(_Server).Serve(0xc82084a300, 0x7fc57b6706d8, 0xc8201b5e60, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2117 +0x129
net/http.(_Server).ListenAndServe(0xc82084a300, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2098 +0x136
net/http.ListenAndServe(0xc82023eab6, 0x6, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2195 +0x98
github.com/pingcap/tidb/tidb-server/server.(_Server).startStatusHTTP.func1.1(0xc821185a40)
        /go-dev/src/github.com/pingcap/tidb/tidb-server/server/server.go:211 +0xd3
created by github.com/pingcap/tidb/tidb-server/server.(_Server).startStatusHTTP.func1
        /go-dev/src/github.com/pingcap/tidb/tidb-server/server/server.go:212 +0x34

**Comment by shenli** [comment]
@elffikk Thanks for your report!
May I have your mysqldump version? And your dumped file.
It seems that the log is not only part of the panic output log. Can you show me more?

**Comment by keithyau** [comment]
Same here

![image](https://cloud.githubusercontent.com/assets/659311/20060714/648d64e4-a537-11e6-8970-4fc3099b394e.png)


import a .sql file have error like the picture show. it is OK in mysql

**Comment by keithyau** [comment]
during import with source command

![image](https://cloud.githubusercontent.com/assets/659311/20060813/ef427ed0-a537-11e6-9bfe-f34e29ed7091.png)

**Comment by kolbe** [comment]
I don't think these two reports are related. The first resulted in a crash, the 2nd a syntax error. Without the SQL output for either of them, it's impossible to reproduce or debug the issues, so I'm going to close this. If you see any additional occurrences like this, please provide the full tidb-server log as well as as much of the SQL dump file as is necessary to reproduce the issue.
