### ISSUE TITLE
tikv leader distribution is unbalance, 1 store has no leader

### ISSUE THREAD

**Issue by wfxxh** [pingcap/tidb#11772]
tidb v3.0.2，Deployed on three nodes,but one of them has no leader,all of them are in default config.
![图片](https://user-images.githubusercontent.com/22764286/63241201-5e4c2c00-c285-11e9-8957-d0addf780a0b.png)

**Comment by shafreeck** [comment]
Would you like to supply the running schedulers from metrics or `pd-ctl -u <pd-address> scheduler show`

**Comment by shafreeck** [comment]
related issue from asktug: https://asktug.com/t/tidb-v3-0-2-tikv-leader/593

**Comment by wfxxh** [comment]
thanks
