### ISSUE TITLE
alter table failed with bit column

### ISSUE THREAD

**Issue by tohghua** [pingcap/tidb#11800]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
create table t (i int, b bit);
alter table t modify b bit first;

2. What did you expect to see?
sql runs successfully.

3. What did you see instead?
SQL Error [1105] [HY000]: unsupported modify column unsigned false not match origin true

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.16
Git Commit Hash: 86ad1a96c3a626dd69d8769cd5f8f7196c0c7a56
Git Branch: HEAD
UTC Build Time: 2019-08-15 10:21:49
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by zz-jason** [comment]
@zimulala PTAL

**Comment by zimulala** [comment]
@tohghua 
Thanks for your feedback!
I will fix it.

**Comment by tohghua** [comment]
@zimulala 
Thanks! 
This sql also fails:
create table t (i int, b bit);
alter table t modify b int;
alter table t modify b int unsigned;

**Comment by tohghua** [comment]
@zimulala Execuse me, how is it going now?

**Comment by zimulala** [comment]
@tohghua 

> create table t (i int, b bit);
alter table t modify b int;
alter table t modify b int unsigned;

We don't support these DDLs. For support on the "modify/change column" operation, you can refer to the [documentation](https://pingcap.com/docs/v3.0/reference/mysql-compatibility/#ddl).
