### ISSUE TITLE
Deploy/prometheus2.0.0.data.metrics/01DJHANS1M8TT20XNWZ2CATDBY/chunks/000001 What are these files for? Can I delete them?

### ISSUE THREAD

**Issue by wangsiyu34567** [pingcap/tidb#11836]
## General Question
Recently, the tidb server hangs up because the server disk space is full. Checked that tidb has generated a lot of 512M files. I wonder if they can delete them?

`
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DGQCQMTAWT86NEEJ18D48NPY/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DH2ZGWHQK27T748DB17BQQDJ/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DHV31Q95NSQ5PPKC5HHXMFJF/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DHZYFZ6JN6WPGXQVFT1KPVZQ/chunks/000001
172M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DHZYFZ6JN6WPGXQVFT1KPVZQ/chunks/000002
444M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DJQ42CXXMFBQMGQDW3MG6YH4/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DGHKB0E6YFPA4S47A4ACQ83X/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DH8RXG5MNCGYYFVZFYA2W6GM/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DHEJA3CW6WJA08QKC9HVZ86J/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DHMBPRCY9X1P4HBJSH88HXM1/chunks/000001
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DJ6VE3HPF3MPXG0RS45N457K/chunks/000001
404M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DJ6VE3HPF3MPXG0RS45N457K/chunks/000002
512M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DGX6488F5HAFX2AAD5JNDGZK/chunks/000001
343M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DJBH95JT65NX8PQRPG03458E/chunks/000001
467M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DJWXF0T9NJ8527ZEVQ5WS0VA/chunks/000001
472M	/home/tidb/deploy/prometheus2.0.0.data.metrics/01DJHANS1M8TT20XNWZ2CATDBY/chunks/000001

`

**Comment by lamxTyler** [comment]
@wangsiyu34567 Thanks for your feedback!

These data are generated by tidb metrics, you can delete them but I think it is a dangerous operation. A better way is to adjust prometheus storage retention time like:

```
tidb-ansible/roles/prometheus/defaults/main.yml
prometheus_storage_retention: “10d”
```

**Comment by wangsiyu34567** [comment]
> tidb-ansible/roles/prometheus/defaults/

谢谢！
