### ISSUE TITLE
RFE on packaging: Using Jenkins project's packaging framework

### ISSUE THREAD

**Issue by tjyang** [pingcap/tidb#1184]
Hi 
This is a comment on future tidb software packaging effort. Not sure if your team decided on how to release tidb native package for different OS.

I like to propose using [Jeninkin project's packaging framework](https://github.com/jenkinsci/packaging). 

This my effort on [packaging gogs](https://github.com/tjyang/gogspkg) using the same packaging framework for Go supported OS. it will be pushed back into https://github.com/gogits/packaging

**Comment by shenli** [comment]
@tjyang Thanks for your advice! 
We haven't considered about packaging. In most common scenario, TiDB will be deployed together with [TiKV](https://github.com/pingcap/tikv) and [PD](https://github.com/pingcap/pd). So I think it is not enough to just package TiDB. We use docker to make deploy easier.
I am not familiar with software packaging. Will it be a good solution for this scenario?

**Comment by tjyang** [comment]
>We haven't considered about packaging. In most common scenario, TiDB will be deployed together with TiKV and PD. 
Sorry, I haven't use golang to create tidb binary by myself yet. Will TiKV and PB be part of tidb main binary ? if it is not part of same binary that is ok too. 
> Will it be a good solution for this scenario?
Yes, I think so. I think Jenkins' packaging framework is flexible enough and it is battle tested. Also it is designed for CI/CD.  One just need to change the target from jenkins.war to tidb related files.
One concern I have is the license compatibility.

**Comment by shenli** [comment]
> Will TiKV and PB be part of tidb main binary ? if it is not part of same binary that is ok too.
TiDB is a SQL engine with pluggable storage engine. It can work with local storage engine (such as goleveldb) or distributed storage engine (such as [TiKV](https://github.com/pingcap/tikv), Hbase). TiKV is a distributed KV engine written in rust. It is the best choice for TiDB. We will use TiKV as storage engine for TiDB in production environment. TiDB and TiKV will be deployed as separated process, not in the same binary. [PD](https://github.com/pingcap/tikv) acts as the administration node for TiKV. We also have a admin tool to config and deploy TiDB/TiKV/PD.

So our Ti storage solution contains three components. I think docker is a better solution. Especially TiKV depends on [RocksDB](https://github.com/facebook/rocksdb) which depends on gcc/clang with C++11 support, gflags, snappy and so on. Docker will make the deployment easier.

**Comment by tjyang** [comment]
>So our Ti storage solution contains three components. I think docker is a better solution. Especially TiKV depends on RocksDB which depends on gcc/clang with C++11 support, gflags, snappy and so on. Docker will make the deployment easier.

Jenekins packaging frame work has[docker packaging solution](https://github.com/jenkinsci/packaging/tree/master/docker) also.  docker is just one of ways to deliver software. Not every one is using or have to use docker.  It is good to have a software support native package format from different OS.

**Comment by coocood** [comment]
@tjyang 
Thank you for your advice.
Supporting multiple OS is good, but it requires more development and testing resource.
Currently, we only support Linux, and Docker is the recommended way to deploy our system.
We will consider native packaging solution when we need to support multiple OS.

**Comment by tjyang** [comment]
>Thank you for your advice.

Sorry, I may sounded my providing advice. This is just a need from a potential user.  Currently my work place is not  one of the docker users. We deploy software using yum or apt-get into production Linux systems, not docker.

Also PinCAP doesn't have to do the whole native packaging stuff yourselves. People want the native tidb package will contribute and test too. 

For me, I will create rpm for my tidb testing purpose. I like to see who well gogs work with tidb.

Thanks for your time and listening.
