### ISSUE TITLE
tidb crashes when executing the query

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb#11840]
Hi all.
I am checking the availability and load capacity of TiDB with the following scenario:
I have 8 workers:
- 4 workers execute transaction insert with `1000 record/transaction`.
- 1 worker executes query statement:
 
```sql
SELECT count(*), SUM(amount) FROM test_translog.transLog GROUP BY userID
```
- 1 worker executes query statement:

```sql
SELECT SUM(amount) FROM test_translog.transLog GROUP BY appID
```

- 1 worker executes query statement:

```sql
SELECT MAX(amount) FROM test_translog.transLog201701 WHERE appTransID > ? AND appTransID < ?
```

- 1 worker executes query statement:

```sql
UPDATE test_translog.transLog201701 SET amount = ? WHERE transID = ?
```
I run all workers about 6 hours and workers connect the same TiDB. Then, there are some phenomena happening:
- Workers Insert and update still work. Worker execute query which do not work. I try test on workbench. And result is timeout (~30s).
- TiDB `crashed shortly after`. TiKV's RAM increased from `9GB to 15GB within 2 minutes`.

**RAM TiKV**
![Screen Shot 2019-08-23 at 11 19 33 AM](https://user-images.githubusercontent.com/38773351/63566645-310ac100-c598-11e9-963d-1e90c80c07e9.png)

**CPU TiKV**
![Screen Shot 2019-08-23 at 11 23 41 AM](https://user-images.githubusercontent.com/38773351/63566759-821ab500-c598-11e9-8ed1-8f5640985cd9.png)

**Image TiDB**
<img width="1325" alt="Screen Shot 2019-08-23 at 7 08 26 AM" src="https://user-images.githubusercontent.com/38773351/63566781-95c61b80-c598-11e9-9f12-002d9bd0b351.png">

I think that TiDB used `lots of memory` when it execute sql that makes the TiDB crash. TiDB cache lots of data on memory. My idea that we should use [stream](https://grpc.io/docs/guides/concepts/) to send result from TiKV to TiDB and from TiDB to Client. Because it help minimize the data saved on memory. And we do not wait all result from TiKV, then TiDB just send it to client. 

I use TiDB version 3. And i deploy 3 node TiDB, 3 node TiKV, 3 node PD.  And node has  32GB, CPU 16 core.

This is [link](https://github.com/phamtai97/test-tidb/tree/master) project that I used to test.

**Comment by lamxTyler** [comment]
Thanks for your feedback! @phamtai97 
- What is the detailed version of tidb? You can get it using `select tidb_version()`;
- For the query time out, what is the detailed reason or log of the faild query?
- For the memory problem, can you provide the log of tikv at that time? Does TiDB server also crashes?
- For streaming, can you check the query plan of `group by` queries using `explain`? If TiDB chooses `HashAgg`, then streaming may help little here because it has to buffer all the data before return the result.

**Comment by phamtai97** [comment]
Hi @lamxTyler 
- Version TiDB is v3.0.1
- I inserted about 55 milions record.
- I used query:
   - `SELECT count(*), SUM(amount) FROM test_translog.transLog GROUP BY userID`
   - `SELECT MAX(amount) FROM test_translog.transLog201701 WHERE appTransID > ? AND appTransID < ?`
   - `SELECT SUM(amount) FROM test_translog.transLog GROUP BY appID`
All querys is timeout.
- Only TiKV is crashed. TiDB did not crash.
This is log TiDB from RAM increases:
   - TiKV: 
[tikv.log](https://github.com/pingcap/tidb/files/3534165/tikv.log)
  - TiDB:
[tidb.log](https://github.com/pingcap/tidb/files/3534133/tidb.log)
  - PD:
[pd.log](https://github.com/pingcap/tidb/files/3534163/pd.log)

**Comment by lamxTyler** [comment]
Could help on the TiKV oom issue? @Connor1996

**Comment by breeswish** [comment]
Hi, could you provide the metrics in TiKV Coprocessor panel and TiKV Tasks panel? Also how many distinct `userID` and distinct `appID` are there in the table? Looks like the reason of TiKV OOM could be processing too many groups as well as processing too many requests.

**Comment by phamtai97** [comment]
Hi
This is a image TiKV Coprocessor when TiKV is crashed: 
![image](https://user-images.githubusercontent.com/38773351/63665013-973f5000-c7f3-11e9-8f7d-ed72f1a8b941.png)

This is a image TiKV task: 
![image](https://user-images.githubusercontent.com/38773351/63665111-04eb7c00-c7f4-11e9-9912-8484cb5a1262.png)

 I ran program about 6 hour. And i generated AppID and userID in the range `997000000 to 999999999`. And In the table, it has about  ~50 millions record (counting duplicate records).

**Comment by breeswish** [comment]
@phamtai97 Thanks a lot. Indeed there are huge amount of scans in TiKV side, which will cause OOM. Currently we do have streaming feature. However they may be buggy. On the other hand, could you run `explain xxx` and post us the result? If the query plan shows that your SQL uses Hash Aggregation, then changing to Stream Aggregation may help reduce memory cost.

**Comment by breeswish** [comment]
BTW when did you start your benchmark? Does the OOM happens right after you started the benchmark, or suddenly occurs after some time?

**Comment by phamtai97** [comment]
Thank you. I will run explain after soon. And i am running benchmark to make sure. I will answer your question after soon.

**Comment by breeswish** [comment]
@phamtai97 Good to hear! Feel free to update this issue after you get something new :)

**Comment by phamtai97** [comment]
Hi @breeswish 
Yesterday, I have run the scenario again, but i run on other instance. And I run about 22 hour. So I see the RAM of TiKV increase and decrease continuously and sometimes `up to 37G`.

And I run SQL:
```sql
explain SELECT count(*), SUM(amount) FROM test_translog.transLog201701 GROUP BY userID;
```
Result: 
![image](https://user-images.githubusercontent.com/38773351/63734966-7be24c80-c8a8-11e9-88bf-f890c9929ee1.png)

This is image RAM:
![image](https://user-images.githubusercontent.com/38773351/63734984-8866a500-c8a8-11e9-88c3-d6de4e7f6442.png)

I think that instance node which I ran program yesterday was strongly then last times. So instance TiKV do not crash. But I do not image that TiKV used to a lot of RAM. If tTiKV really uses that much ram, then maybe in the near future it will also crash. That is dangerous for the systems which use it.

And i am to run other tests like using SQL Join statements.

**Comment by breeswish** [comment]
@phamtai97 Did you run this SQL in parallel (i.e. multiple connections concurrently) or in serial (only one SQL at a time)? Also how many cores are there on your machine?

**Comment by phamtai97** [comment]
@breeswish I ran all SQL in parallel the same as [here](https://github.com/pingcap/tidb/issues/11840#issue-484359976) and [this project](https://github.com/phamtai97/test-tidb/tree/master).
Infomation system:
- 32 Core
- 64 RAM

**Comment by breeswish** [comment]
@phamtai97 Thanks for the information! So according to your hardware configuration, there could be 25 parallel requests being handled at TiKV side, with each request contains a notable amount of hash aggregation groups (where each group becomes a hash table item). This shall be the cause of the OOM issue you observed.

- To eliminate the memory usage, you may consider grouping over a sorted column, so that it becomes stream aggregation instead of hash aggregation.

- The explanation above is only a theory according to current phenomenon. You could also tell me how to run your test / bench project so that I can reproduce it and help verify the theory locally.

**Comment by phamtai97** [comment]
This is my project https://github.com/phamtai97/test-tidb.  You can clone it and go to the directory test-tidb. Then, you run cmd:

```sh
// build
$ go build

// run
$ ./test-tidb
```

**Comment by breeswish** [comment]
@phamtai97 Thanks a lot. I will run it locally against my debug branch to verify this theory. BTW what is your TiDB & TiKV version?

**Comment by phamtai97** [comment]
@breeswish I use TiDB & TiKV version 3.0.1

**Comment by phamtai97** [comment]
Hi @breeswish, i just discovered one more phenomenon, the RAM suddenly dropped and didn't increase anymore. While my program still runs normally.

![image](https://user-images.githubusercontent.com/38773351/63748270-3d15bc00-c8d3-11e9-9e5e-b67821738076.png)

**Comment by breeswish** [comment]
Hmm. I tried to reproduce your problem locally.. This is my metrics:

![image](https://user-images.githubusercontent.com/1916485/63772885-a1a13d00-c90c-11e9-9ac9-ee2e47c05c4c.png)

Is your bandwidth full? How long does it take to finish a single query?

**Comment by phamtai97** [comment]
Hi, when i execute SQL:
```sql
SELECT count(*), SUM(amount) FROM test_translog.transLog GROUP BY userID
```
I spent about 150 seconds, sometimes up to 400 seconds. 
How long have you run reproduce? How many record in DB?

**Comment by phamtai97** [comment]
At first, we had to run the test again within about 3 hours, and when I run query the same as above SQL many times, TiKV's RAM soared and then TiKV crashed. This is metric of TiKV: 
![image](https://user-images.githubusercontent.com/38773351/63774501-95ff4780-c907-11e9-92dc-72f2f29bf064.png)

Then I checklog service, I see error: `Out of memory: Kill process 17463 (tikv-server)`. It seems that OS killed the TiKV process because it used too much RAM suddenly. 

I think that the main reason here could be that TiKV has `cached so much data on memory` when executing the query.  And when TiKV stored `more and more data`, then executing queries the same as my query, there will be increased in RAM. Although we have strong server such as many RAM, there will be times when a TiKV crash like me, it will happen sooner or later.

**Comment by breeswish** [comment]
Would you like to export all metrics and send it to me via breezewish@pingcap.com ? This could be more efficient. You can do this by either clicking the export button, or printing the page as PDF through your browser (after you expanded all panels).

**Comment by phamtai97** [comment]
Do you run parallel and continuous queries? I do not quite understand your question.
You try run SQL:
```sql
SELECT MAX(transLog201906.amount), sum(transLog201906.amount)
FROM test_translog.transLog201906  
WHERE transLog201906.transID 
IN (SELECT  transLog201906.transID FROM test_translog.transLog201906 JOIN test_translog.transLog201701
ON transLog201906.userID = transLog201701.userID)
GROUP BY transLog201906.appID;
```

**Comment by phamtai97** [comment]
This is image of gRPC panel:

![image](https://user-images.githubusercontent.com/38773351/63780818-e9c35e00-c912-11e9-9518-67691b77ea15.png)

**Comment by breeswish** [comment]
@phamtai97 I didn't not manually run SQLs. I only started your test-tidb.

**Comment by phamtai97** [comment]
@breeswish How did you deploy the cluster?

**Comment by breeswish** [comment]
@phamtai97 I deployed only 1 tidb, 1 tikv and 1 pd. Normally SQLs in your project are handled within 20 seconds. I cannot run the SQL 

```sql
SELECT MAX(transLog201906.amount), sum(transLog201906.amount)
FROM test_translog.transLog201906  
WHERE transLog201906.transID 
IN (SELECT  transLog201906.transID FROM test_translog.transLog201906 JOIN test_translog.transLog201701
ON transLog201906.userID = transLog201701.userID)
GROUP BY transLog201906.appID;
``` since there is only `transLog201906` table.

**Comment by phamtai97** [comment]
ah, I'm sorry for this query.
I still haven't found a reason why you can run without the phenomenon like me. But why only 1 TiKV you can still run.

**Comment by breeswish** [comment]
@phamtai97 In 1 TiKV mode data only has one replica. How is your tikv config? Did you use the default one, or..?

**Comment by phamtai97** [comment]
I use 3 TiKV, 3 TiDB, 2PD. And 3 TiKV located on 3 different nodes, 3 TiDB nodes are located on 3 similar TiKV nodes. 

As you say "*However the memory usage of block cache should be only increased and becomes stable.*", so Why does my TikV Ram run up and down continuously during the test run?

Can you show me your log nohup in service like that:
![image](https://user-images.githubusercontent.com/38773351/63784513-f6e34b80-c918-11e9-9cef-e154a9dc719b.png)

**Comment by breeswish** [comment]
Aha, so your TiDB node and TiKV node is deployed on the same machine? How is the machine CPU?

**Comment by phamtai97** [comment]
Can you show me your log nohup in service like that.
![image](https://user-images.githubusercontent.com/38773351/63785381-79b8d600-c91a-11e9-9753-ecb5463dba5b.png)

Ah, My CPU:` 32 core, RAM 64 GB`. I think you try deploy the same as me. Then you ran program test for 12 -> 24 hours continuously.

**Comment by phamtai97** [comment]
I think the problem here is mainly because TiKV has used a lot of RAM, You can see [this](https://github.com/pingcap/tidb/issues/11840#issuecomment-525103921). My opinion, I think that if my test is not enough to make your TiKV crash. But the purpose of my test is to check how much RAM the TiKV uses. And as you can see, it uses quite a bit of RAM.

**Comment by breeswish** [comment]
@phamtai97 It's like:

```
INFO[0136] Worker QueryMaxAmountTransAppID takes: 15850 millisecond
INFO[0141] Worker QuerySumAmountAppID takes: 29096 millisecond 
INFO[0152] Worker QueryMaxAmountTransAppID takes: 15551 millisecond
INFO[0169] Worker QueryMaxAmountTransAppID takes: 17036 millisecond 
```

You can manually set the block size of the TiKV, which by default uses about 50% amount of memory. If you deploy TiKV and TiDB on the same machine then looks like it is very necessary. I'm not sure about why there are spikes in your metrics, which varies for about 20GB. It is very abnormal.

**Comment by phamtai97** [comment]
I will find out, if I find anything new, I'll let you guys know.

**Comment by breeswish** [comment]
@phamtai97 Good to hear! Considering that memory usage varies for about 20GB, you may want to set TiKV's block cache to something lower than 50%, in order to sustain this 20GB change. You can also send full grafana metrics to me, so that we can investigate where these 20GB memory comes from. Looks like it is not very related to your query.

**Comment by phamtai97** [comment]
But, every time I query, TiKV's Ram increases, I think it's relevant. Because when I was querying, I had to scan all the tables. I will send you the metric soon.

**Comment by breeswish** [comment]
Yes, your query does contribute to Tikv's memory. There are block cache to fill (which will not release the occupied memory after request is finished) and runtime memory (which will be freed after request).

**Comment by phamtai97** [comment]
In your opinion, which instance of TiDB and TiKV consumes more RAM when executing queries. Because I deploy TiKV and TiDB on on the same machine, so i don't know which one used a lot of RAM.

**Comment by phamtai97** [comment]
@breeswish I have a question that my TiKV gets killed by OS because of too much RAM. So if I didn't configure the OS kill process TiKV when it use lot of memory, and TiKV ran out of RAM, what would happen? 
Can we execute the query?
How will TiKV handle that?

Because the amount of RAM that TiKV uses depends on the amount of data and our queries. So there will be times when TiKV uses up RAM. I need to know what happens when that happens. Let us take the appropriate action.

**Comment by breeswish** [comment]
@phamtai97 Our typical topology is that TiDB and TiKV runs in different machines and in typical scenarios TiDB uses more *runtime* memory. However many clients assign large memory to TiKV as well, whose purpose is to make block cache bigger which notably decrease the latency.

**Comment by phamtai97** [comment]
Are you sure that TiDB uses more memory than TiKV?
So when block cache of TiKV full, the latency will increase when we execute SQL.

**Comment by breeswish** [comment]
@phamtai97 It depends on how efficient block cache are used, how much latency you can bear and how complex your SQL is. The full of block cache does not mean that the latency will drop. In fact in most user cases block cache is always filled after several queries. What matters is that are these block cache used efficiently? For example, if your block cache is very small, then most data to read are not cached so that the latency will be large. On the other hand if the block cache is big and hit rate is 99% then the latency shall be very low. You can review your block cache hit rate in "RocksDB - KV" panel. The more hit rate, the lower latency.

**Comment by phamtai97** [comment]
oh, thanks @breeswish a lot. 
And I read documents of TiDB and [issues](https://github.com/pingcap/tidb/issues/8254), i see both TiDB and TiKV can OOM. So How do right config TiDB and TiKV ?

**Comment by breeswish** [comment]
@lamxTyler Could you help with the TiDB part?

For TiKV, if you deploy it alone then default configuration shall work normally. If there is still OOM, then you need to manually set the block cache size to some smaller value. If you deploy it with other components like TiDB then block cache size should be definitely lowered (and even after that the OOM risk is still high).

Currently there is no run time memory control strategy in TiKV since very rare clients meet TiKV OOM. However we planned to do it right in the next big release (i.e. 4.0).

**Comment by lamxTyler** [comment]
TiDB does provide ways to control memory, you can take a look at https://pingcap.com/docs/v3.0/how-to/configure/memory-control/

**Comment by phamtai97** [comment]
oh, thank @lamxTyler, @breeswish e

**Comment by phamtai97** [comment]
@breeswish I deployed TiDB and TiKV on the same machine. So the metric panel RAM, CPU of TiKV on Grafana is of `TiKV or of general TiKV and TiDB`.

Example image:
![image](https://user-images.githubusercontent.com/38773351/63989983-80a73a80-cb0c-11e9-9364-a4675d64f915.png)

**Comment by breeswish** [comment]
@phamtai97 Hi, it is the memory used by TiKV process.

**Comment by phamtai97** [comment]
@breeswish I still do not clear about this image. Why do only TiKV of node 173 have RAM increase ? 

![image](https://user-images.githubusercontent.com/38773351/63991641-d1219680-cb12-11e9-8142-27e5c98a9050.png)

**Comment by breeswish** [comment]
@phamtai97 Could you take a look at whether the request is balanced for all TiKV instances? You can check it out by reviewing the gRPC metrics (gRPC Count) (and maybe change expression to `xxx by (instance)` to view these metrics by instance).

**Comment by phamtai97** [comment]
Image gRPC count Node 174:
![image](https://user-images.githubusercontent.com/38773351/63992570-ab968c00-cb16-11e9-8f32-25891cf8523c.png)

Image gRPC count Node 173:
![image](https://user-images.githubusercontent.com/38773351/63992578-b18c6d00-cb16-11e9-8523-ade9e624e5a8.png)

@breeswish I see gRPC message count node 173 more than node 174

**Comment by phamtai97** [comment]
@lamxTyler If i config `oom-action: "log"`, my TiDB still can crash but it can write to log. If i config `oom-action: "cancel"`, my TiDB will not crash and return error to client. So, configing `oom-action: "cancel"` seems to be safer. I understand this is true ?

**Comment by phamtai97** [comment]
@breeswish I have a question? Does TiKV provide a mechanism for reporting OOM errors to users? Or when TiKV got OOM, TIKV is crashed.

**Comment by lamxTyler** [comment]
@phamtai97 Yes, you understanding is correct and it is safer to use `cancel`.

**Comment by phamtai97** [comment]
@breeswish

**Comment by phamtai97** [comment]
@lamxTyler thank you.
