### ISSUE TITLE
Planner:eliminate redundant projection 

### ISSUE THREAD

**Issue by jingyugao** [pingcap/tidb#11863]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
     CREATE TABLE `t` (  `a` int(11) DEFAULT NULL) ;
   EXPLAIN SELECT  
    1+Num
  FROM
    (
      SELECT
        1+a as Num  from t
    ) t
```

2. What did you expect to see?
There is only one projection.
3. What did you see instead?

```shell
Projection_4	10000.00	root	plus(1, t.num)
└─Projection_5	10000.00	root	plus(1, test.t.a)
  └─TableReader_7	10000.00	root	data:TableScan_6
    └─TableScan_6	10000.00	cop	table:t, range:[-inf,+inf], keep order:false, stats:pseudo
```shell

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.25-TiDB-v4.0.0-alpha-123-gf24866a40

**Comment by francis0407** [comment]
Hmm, I think it is hard to remove this projection. `TableDual` is only used to generate rows, while, the `Projection(23)` generates the `Num` column, which is used for the `case when` expression. Both `Projection` have their own meaning of existence.

It seems that this is not a bug here.

**Comment by jingyugao** [comment]
> Hmm, I think it is hard to remove this projection. `TableDual` is only used to generate rows, while, the `Projection(23)` generates the `Num` column, which is used for the `case when` expression. Both `Projection` have their own meaning of existence.
> 
> It seems that this is not a bug here.

Sorry for bad example.I have updated the sql. PTAL.

**Comment by jingyugao** [comment]
I have also run it in postgresql.
```shell
EXPLAIN VERBOSE SELECT  
    1+Num
  FROM
    (
      SELECT
        a+1 as Num
				FROM tb
    ) t;
Seq Scan on public.tb  (cost=0.00..40.60 rows=2040 width=4)
  Output: (1 + (tb.a + 1))
```
It seems pg can eliminate the projection.

**Comment by francis0407** [comment]
Yeah, we do need a  `Projection coalesce` here. Could please update the issue description? This is a enhancement for planner instead of a bug. Thanks for reporting this.
