### ISSUE TITLE
Support logical replication / CDC

### ISSUE THREAD

**Issue by july2993** [pingcap/tidb#11864]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Users would like to keep their data mirrored in full-text indexes, analytics engines, and big data pipelines, among others.

It will be great for TiDB to support logical replication / CDC.

**Describe the feature you'd like:**

Users can create `CHANGFEED`. Changefeeds target a whitelist of tables, partitions, rows, called the "watched rows". Every change to a watched row is emitted as a record in a configurable format(JSON or Protobuf etc) to a configurable sink (Kafka). Changefeeds can be paused, unpaused, and canceled.

For example, with table:
`create table t(id primary key, a varchar(255), b varchar(255))`
when inserting a row: insert into t(id, a, b) values(1, "afoo", "bfoo")

we can get an event like this:
key: {id:1}, value: {a: "afoo", b: "bfoo"}

when deleting the row with `id = 1`, we can get an event like this:
key: {id:1}, value: nil

When a new changefeed is created, a user-given timestamp can be set to only emits all changes after the user-given timestamp.

**Describe alternatives you've considered:**

[TiDB-Binlog](https://github.com/pingcap/tidb-binlog) can also emit changes to Kafka in the format at the Transaction level. But have some shortcomings

- Pump is not high available(no data replication) and deploying it take another cost to save the change data，we can get the change data while KV later directly to avoid this.

- It's unfriendly for huge transactions, the message will be too huge and in many case, we don't need to handle the change data by transaction.

**Teachability, Documentation, Adoption, Migration Strategy:**

The key/value store(TiKV) should give clients the ability to register for notification when a transaction is committed that changes the value associated with a specificfic key.

The harder question is we should convert the KV to sql row. We must match a `TableInfo` that is valid for the timestamp it's executing at.

**Comment by nullnotnil** [comment]
@IANTHEREAL can we close this issue as a duplicate of TiCDC?

**Comment by july2993** [comment]
close by https://github.com/pingcap/ticdc
