### ISSUE TITLE
 How to synchronize data from tidb to kafka

### ISSUE THREAD

**Issue by wangdabin1216** [pingcap/tidb#11879]
目前，我们通过tidb同步数据到kafka
但是通过storm或者flink进行处理的时候，无法解析对应的kafka数据
请问如何处理

**Comment by lamxTyler** [comment]
Thanks for your feedback. PTAL @suzaku

**Comment by suzaku** [comment]
@wangdabin1216 So you are parsing the payloads in Java, right? This newly contributed tutorial may be useful to you: https://github.com/pingcap/tidb-tools/pull/264

**Comment by zz-jason** [comment]
Hi @wangdabin1216, I'm going to close this issue. If you have any other question, feel free to ask again.
