### ISSUE TITLE
Can not insert -1 as Type BIT

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#11895]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```mysql
drop table if exists t1;
create table t1(c1 bit(64));
insert into t1 value(-1);
```

2. What did you expect to see?

`Query OK, 1 row affected`

3. What did you see instead?

`ERROR 1264 (22003): Out of range value for column 'c1' at row 1`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by wjhuang2016** [comment]
Please fix the test https://github.com/pingcap/tidb/blob/cea80ae21bfd2ce6fdbf53c2b3d2c41979096aec/executor/join_test.go#L399-L407
