### ISSUE TITLE
In tidb3.0, sometimes it will appear [arguments: 1566932400, 1566936000]: other error: Eval error: InvalidDataType("invalid range,range.start should be smaller than range.end,

### ISSUE THREAD

**Issue by huzhongluwei** [pingcap/tidb#11907]
After upgrading tidb3.0, execute delete from report where create_time >= ? and create_time < ? limit 10000, the following error will not occur frequently：
[arguments: 1566932400, 1566936000]: other error: Eval error: InvalidDataType("invalid range,range.start should be smaller than range.end, but got [[116, 128, 0, 0, 0, 0, 2, 175, 78, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 3, 128, 0, 0, 0, 93, 101, 125, 177],[116, 128, 0, 0, 0, 0, 2, 175, 78, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 3, 128, 0, 0, 0, 93, 101, 125, 176, 3, 128, 0, 0, 0, 0, 23, 115, 3, 3, 128, 0, 0, 0, 0, 0, 1, 100])")

**Comment by lamxTyler** [comment]
@huzhongluwei Thanks for your feedback! Could you provide

- The detaild tidb version using `select tidb_version()`
- The schema of `report` table.
- The stats of `report` table using `curl http://{TiDBIP}:10080/stats/dump/{db}/{table}`

**Comment by huzhongluwei** [comment]
hi,Here are some of the information you need
version:
Release Version: v3.0.2
Git Commit Hash: 94498e7d06a244196bb41c3a05dd4c1f6903099a
Git Branch: HEAD
UTC Build Time: 2019-08-07 02:35:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
schema:
CREATE TABLE `operation_report` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `camp_id` int(11) DEFAULT '0' COMMENT 'camp id',
  `clicks` int(11) DEFAULT '0',
  `unique_clicks` int(11) DEFAULT '0',
  `conversions` int(11) DEFAULT '0' ,
  `pay_out` decimal(32,3) DEFAULT '0.000' COMMENT '支出',
  `revenue` decimal(32,3) DEFAULT '0.000' COMMENT '收入',
  `create_time` int(11) DEFAULT '0' COMMENT '创建时间 一般为整点时间戳',
  `is_tmp` tinyint(4) DEFAULT '0' COMMENT '0正常数据  1 临时数据',
  `currency` varchar(10) DEFAULT 'USD',
  `amount` decimal(32,3) DEFAULT '0.000' COMMENT '总金额',
  `platform_id` tinyint(4) DEFAULT '0' COMMENT '平台id',
  `event_id` int(11) DEFAULT '1' COMMENT 'event id',
  `is_private` tinyint(4) DEFAULT '0' COMMENT '是否是private event数据 0.否 1.是',
  `pending_conversions` int(11) DEFAULT '0' COMMENT 'pending conversions',
  `pending_pay_out` decimal(32,3) DEFAULT '0.000' COMMENT 'pending pay out',
  `pending_revenue` decimal(32,3) DEFAULT '0.000' COMMENT 'pending revenue',
  `pending_amount` decimal(32,3) DEFAULT '0.000' COMMENT 'pending amount',
  `rejected_conversions` int(11) DEFAULT '0' COMMENT 'rejected conversions',
  `rejected_pay_out` decimal(32,3) DEFAULT '0.000' COMMENT 'rejected pay out',
  `rejected_revenue` decimal(32,3) DEFAULT '0.000' COMMENT 'rejected revenue',
  `rejected_amount` decimal(32,3) DEFAULT '0.000' COMMENT 'rejected amount',
  `create_year` varchar(10) DEFAULT '' COMMENT '所属年份:YYYY',
  `create_month` varchar(10) DEFAULT '' COMMENT '所属年份:YYYY-MM',
  `create_day` varchar(20) DEFAULT '' COMMENT '所属天:YYYY-MM-dd',
  `create_hour` datetime DEFAULT NULL COMMENT '所属天:YYY-MM-dd HH:mm:ss', 
  PRIMARY KEY (`id`),
  KEY `create_camp_aff` (`create_time`,`camp_id`,`aff_id`),
  KEY `create_time` (`create_time`),
  KEY `create_hour` (`create_hour`),
  KEY `camp_id` (`camp_id`),
  KEY `adv_id` (`adv_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

stats:
0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0
      ]
     }
    ],
    "default_value": 0
   },
   "null_count": 0,
   "tot_col_size": 0,
   "last_update_version": 410775871830097942,
   "correlation": 0
  }
 },
 "count": 2109617,
 "modify_count": 729035,
 "partitions": null

**Comment by lamxTyler** [comment]
The stats is not complete, you can save it in a file and update it, thank you.

**Comment by lamxTyler** [comment]
And did you modify the schema? There are no columns called `aff_id` and `adv_id` but they do occur in the index. @huzhongluwei

**Comment by huzhongluwei** [comment]
Yes, I deleted some fields and may involve some business information fields

**Comment by huzhongluwei** [comment]
delete from report where create_time >= and create_time < ? limit 10000 is only related to the create_time field, create_time is int(11), saves the timestamp of UTC zero time zone

**Comment by lamxTyler** [comment]
@huzhongluwei Please provide the result file of stats dump. It could be something related with stats.

**Comment by huzhongluwei** [comment]
@lamxTyler This is the stats information file 
[2884_28.log](https://github.com/pingcap/tidb/files/3554076/2884_28.log)

**Comment by huzhongluwei** [comment]
@lamxTyler  Is there any progress on your side?

**Comment by lamxTyler** [comment]
I have located the problem and trying to fix it now.

**Comment by huzhongluwei** [comment]
thanks,good job
