### ISSUE TITLE
An idea about OOM when big table aggregation 

### ISSUE THREAD

**Issue by jingyugao** [pingcap/tidb#11964]
## Feature Request

**Is your feature request related to a problem? Please describe:**

```sql
  CREATE TABLE `bills` ( `order_ref` bigint,`day` int) ;
```
For example,I have a table `bills` which records each order and day it occors.
If I want to statistics the oorder count every month.Then I write sql like this:
```
select day/100 as month,count(1) from bills group by day/100
```
If the table is very large,it will cause an OOM.
Then we will `sharde the sql` by half year. Just like this:
```
select day/100 as month,count(1) from bills where day >='20190101' and day<'20190701' group by day/100;
select day/100 as month,count(1) from bills where day >='20180701' and day<'20190101' group by day/100;
....
```
After execute these sql, we do an union of all the result by hand.
This seem very ugly, however, it really works. 
So I want to know if tidb could do `sql sharding` automatically by statistics.
It will cost more time but less memory.

**Describe the feature you'd like:**

TiDB could do `sql sharding` automatically by statistics.
This may be a `hint` just for OLAP.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by francis0407** [comment]
How do we save the intermediate result? It seems that we still need to dump the result of those parts to avoid OOM?

**Comment by jingyugao** [comment]
> How do we save the intermediate result before `Union`? It seems that we still need to dump the result of those parts to avoid OOM?

In most cases,the intermediate result is very small, even only several records.For example,each half-year only have six records.
Hovever,the children of `union`  will executed concurrently. This may increase the probability of OOM.We can even even execute the `union` serially if each child is very large.

**Comment by francis0407** [comment]
If the intermediate result is very small, why would it cause OOM? 
As far as I know, in HashAgg, the number of hashtable slots depends on the number of distinct value of `group by key`. Sharding won't reduce the memory usage if we don't dump the intermediate result. What's worse, sharding may degrade the performance of the Scan.

**Comment by zz-jason** [comment]
We can improve this by achieving the `shuffle` operator in this proposal: https://github.com/pingcap/tidb/pull/14453. The execution plan for this can be like this:

```
table scan -> partition and shuffle by day/100 -> hash aggregate
```

The hash aggregate only processes several data partitions (partition by day/100) at the same time, other unprocessed data partitions can be stored temporally in the disk. Thus avoids the OOM in tidb-server.

**Comment by zz-jason** [comment]
I'm going to close this feature request since we already have solutions (but not implemented yet). feel free to reopen it if the solution above can not fulfill the requirements.
