### ISSUE TITLE
Can 't insert data to decimal(65, 0)

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#11983]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

CREATE TABLE `ABC` (
  `uuid` char(36) NOT NULL DEFAULT '',
  `id` int(11) NOT NULL,
  `time` int(11) NOT NULL,
  `pe` tinyint(4) NOT NULL,
  `ype` tinyint(4) NOT NULL,
  `unt` decimal(65,0) DEFAULT NULL,
  `nce` decimal(65,0) DEFAULT NULL,
  `mark` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`uuid`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

insert into ABC values("cdbb4c57-822e-4fad-bd74-8f6f3917731b",7345,1545672,19,2,17000000000000000000,-17000000000000000000,NULL);

ERROR 1264 (22003): Out of range value for column 'nce' at row 1

2. What did you expect to see?

success

3. What did you see instead?

the error "out of range"

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

3.0.2
I did same test from 2.1.4 failed with same error. 

The sql works from 5.7.27.

**Comment by lonng** [comment]
This BUG has been fixed.
