### ISSUE TITLE
function no longer support string as integer in 3.x

### ISSUE THREAD

**Issue by Still4** [pingcap/tidb#11998]
mysql> select date_format(from_unixtime((1567375200000 + '7200000')/1000),'%Y-%m-%d');
ERROR 1427 (42000): For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column '').

after we changed '7200000' to 7200000, the error is gone

mysql> select date_format(from_unixtime((1567375200000 + 7200000)/1000),'%Y-%m-%d');  
+-----------------------------------------------------------------------+
| date_format(from_unixtime((1567375200000 + 7200000)/1000),'%Y-%m-%d') |
+-----------------------------------------------------------------------+
| 2019-09-02                                                            | 
+-----------------------------------------------------------------------+

it worked fine with 1.x 2.x, also 1+'1' is fine

mysql> select 1+'1'; 
+-------+
| 1+'1' |
+-------+
|     2 | 
+-------+

 I'm wondering if this check is intentioned or just some situation didn't realise, thanks.

Release Version: v3.0.3
Git Commit Hash: 836982c617fbaa42d74616eb9ba9ed4cae46c46b
Git Branch: HEAD
UTC Build Time: 2019-08-30 02:42:42
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by eurekaka** [comment]
@Still4 Thanks for the feedback, it is a bug. Do you have interest to take a look into this problem and fix it? or we would fix it then.

**Comment by Still4** [comment]
@eurekaka Sorry, I'm not quite familiar with golang, might not able to help
