### ISSUE TITLE
TIKV  Server version: 5.7.25-TiDB-v2.1.16 

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tidb#11997]
[ERROR] [panic_hook.rs:104] ["thread 'raftstore-4' panicked '[region 488] 490 entries[1296559:1296592] is unavailable from storage' at \"/rust/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raft_log.rs:448\"\nstack backtrace:\n   0:     0x7fe0d60ecb3c - backtrace::backtrace::libunwind::trace::h102c40391864e832\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54\n                         - backtrace::backtrace::trace::h74b1dbace51da4c0\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70\n   1:     0x7fe0d5a287d9 - tikv::util::panic_hook::set_exit_hook::{{closure}}::h965cf825badc4c0a\n                        at /home/jenkins/.target/release/build/backtrace-4ca9820cec07bbc1/out/capture.rs:79\n   2:     0x7fe0d617de1f - std::panicking::rust_panic_with_hook::h60a37fb79e459606\n                        at libstd/panicking.rs:479\n   3:     0x7fe0d617dc7e - std::panicking::continue_panic_fmt::hb542a58a3d52cb5c\n                        at libstd/panicking.rs:390\n   4:     0x7fe0d617dc22 - std::panicking::begin_panic_fmt::ha198d387c12d5535\n                        at libstd/panicking.rs:345\n   5:     0x7fe0d61e204a - <raft::raft_log::RaftLog<T>>::slice::h1d506c011824440c\n                        at /home/jenkins/workspace/release_tidb_2.1/tikv/<panic macros>:8\n   6:     0x7fe0d5780537 - <raft::raft::Raft<T>>::hup::h71c7428c55565570\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raft.rs:1073\n   7:     0x7fe0d5781939 - <raft::raft::Raft<T>>::step::h6e5b0591986b29ac\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raft.rs:1009\n   8:     0x7fe0d588cb8a - <raft::raft::Raft<T>>::tick_election::h6d11f0b226d67f08\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raft.rs:682\n                         - <raft::raft::Raft<T>>::tick::hde0febe266ceed86\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raft.rs:664\n                         - <raft::raw_node::RawNode<T>>::tick::hc1b5d6eb02f275f3\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/raft-0.4.3/src/raw_node.rs:267\n                         - tikv::raftstore::store::fsm::peer::<impl tikv::raftstore::store::fsm::Store<T, C>>::on_raft_base_tick::h9d989d1979084ffe\n                        at /home/jenkins/workspace/release_tidb_2.1/tikv/src/raftstore/store/fsm/peer.rs:150\n                         - tikv::raftstore::store::fsm::store::<impl mio::handler::Handler for tikv::raftstore::store::fsm::Store<T, C>>::timeout::ha35dce1fa111c174\n                        at /home/jenkins/workspace/release_tidb_2.1/tikv/src/raftstore/store/fsm/store.rs:1117\n   9:     0x7fe0d57c7190 - <mio::event_loop::EventLoop<H>>::timer_process::hfb92f07ebc1df8b0\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:368\n                         - <mio::event_loop::EventLoop<H>>::run_once::h21b1ad99a7957e28\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:300\n  10:     0x7fe0d58aaed0 - <mio::event_loop::EventLoop<H>>::run::hef440b77ed162a25\n                        at /rust/registry/src/github.com-1ecc6299db9ec823/mio-0.5.1/src/event_loop.rs:247\n                         - tikv::raftstore::store::fsm::store::<impl tikv::raftstore::store::fsm::Store<T, C>>::run::hf58707898ccd8fd2\n                        at /home/jenkins/workspace/release_tidb_2.1/tikv/src/raftstore/store/fsm/store.rs:469\n  11:     0x7fe0d578d068 - <tikv::server::node::Node<C>>::start_store::{{closure}}::h41b8d88464a2417e\n                        at /home/jenkins/workspace/release_tidb_2.1/tikv/src/server/node.rs:373\n                         - std::sys_common::backtrace::__rust_begin_short_backtrace::h1ef3e984e0ec3d94\n                        at /checkout/src/libstd/sys_common/backtrace.rs:136\n  12:     0x7fe0d58c4eb2 - std::thread::Builder::spawn::{{closure}}::{{closure}}::hc7e3a6cd82f954c6\n                        at /checkout/src/libstd/thread/mod.rs:409\n                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::he4bcc6c7cd3ae9aa\n                        at /checkout/src/libstd/panic.rs:313\n                         - std::panicking::try::do_call::hb0d08aba7be9080f\n                        at /checkout/src/libstd/panicking.rs:310\n                         - std::panicking::try::ha56d72cbcf92cf1e\n                        at /checkout/src/libpanic_unwind/lib.rs:106\n                         - std::panic::catch_unwind::h8a354355b248955b\n                        at /checkout/src/libstd/panic.rs:392\n                         - std::thread::Builder::spawn::{{closure}}::hd56ccad66617cee3\n                        at /checkout/src/libstd/thread/mod.rs:408\n                         - <F as alloc::boxed::FnBox<A>>::call_box::h996887afeca93cba\n                        at /checkout/src/liballoc/boxed.rs:640\n  13:     0x7fe0d616c203 - std::sys::unix::thread::Thread::new::thread_start::h96884314b12ba24c\n                        at /checkout/src/liballoc/boxed.rs:650\n  14:     0x7fe0d4b9cdc4 - start_thread\n  15:     0x7fe0d46b3cec - clone\n  16:                0x0 - <unknown>"]

**Comment by eurekaka** [comment]
@dbaspace Please follow the issue template to provide more detailed information about the problem you want to report, thanks.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to re-open it with additional details. Thanks!
