### ISSUE TITLE
compile fail on Windows

### ISSUE THREAD

**Issue by fuxiaohei** [pingcap/tidb#12]
![qq 20150906173942](https://cloud.githubusercontent.com/assets/2142787/9703736/0d477ec8-54bf-11e5-88e4-c98460d15a9d.png)

two questions:

1. `syscall.Dup2()` can't works on Windows. There is any plan for Windows support.

2. it needs `iconv.h` as cgo library. Is it possible to use pure go codes instead of cgo codes ?

`

**Comment by ngaut** [comment]
Could you fix this issue ?
Currently we are using Linux and Mac OS X.

**Comment by fuxiaohei** [comment]
I make a pull request for log library

https://github.com/ngaut/log/pull/1

It can work on Windows.

But I find that `tidb` don't use the breaking api `log.CrashLog()`.... so funny.

**Comment by ngaut** [comment]
Does TiDB works on windows now?  @fuxiaohei

**Comment by fuxiaohei** [comment]
tidb can be compiled and running by using bat script in https://github.com/pingcap/tidb/pull/130.

thanks a lot.  I will test more cases in windows.

If something breaks, I make a new issue.
