### ISSUE TITLE
parser/parser.y: TableIdentList grammar clarification needed

### ISSUE THREAD

**Issue by cznic** [pingcap/tidb#120]
Attempting to resolve the last few S/R conflicts:

```yacc
TableIdentList:
	{
		$$ = []table.Ident{}
	}
|	TableIdent
	{
		tbl := []table.Ident{$1.(table.Ident)}
		$$ = tbl
	}
|	TableIdentList ',' TableIdent
	{
		$$ = append($1.([]table.Ident), $3.(table.Ident))
	}
 ```
[source](https://github.com/pingcap/tidb/blob/6d058fe3e825a2d2429f55170313009d971f826c/parser/parser.y#L2105)

The `TableIdentList` production accepts

- ɛ
- foo
- foo, bar
- foo, bar, baz
- , foo
- , foo, bar

(Where foo, bar is possibly a.foo and b.bar.)

Is that intended? I guess not, because then, for example, this would be valid statements

- DROP TABLE
- DROP TABLE , foo

etc.

My guess is that `TableIdentList` should read like

```yacc
TableIdentList:
	TableIdent
	{
		tbl := []table.Ident{$1.(table.Ident)}
		$$ = tbl
	}
|	TableIdentList ',' TableIdent
	{
		$$ = append($1.([]table.Ident), $3.(table.Ident))
	}
```

But I have little knowledge of MySQL grammar. Please clarify.

Blocks #73 .

**Comment by coocood** [comment]
@cznic I referenced TableIdentList related syntax in MySQL docs.
You are right, `TableIdentList` should never be empty.

**Comment by cznic** [comment]
Thanks for the clarification!
