### ISSUE TITLE
tidb可以做物联网相关产品的数据仓库么？

### ISSUE THREAD

**Issue by liujunhui** [pingcap/tidb#12004]
我们在做一个物联网产品，每天采集海量的数据（大概每天20亿条）。我想咨询一下TIDB可以做这样的海量数据仓库么？如果可以，因为是物联网的数据，对事务没有要求，只对时序有要求的这种场景，需要在TIDB做哪些配置呢？

**Comment by eurekaka** [comment]
@liujunhui It depends on your workload pattern and query latency requirement.
