### ISSUE TITLE
Query_time is not correct in SlowQuery Log

### ISSUE THREAD

**Issue by lynch0227** [pingcap/tidb#12025]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
When I check the slowquery log, I find there is so many internal querys.
Here is the logs:
Time: 2019-09-04T16:52:20.96932679+08:00
Txn_start_ts: 410933563469070339
Query_time: 9223372036.854776
Process_time: 0.001 Request_count: 1 Total_keys: 1
Index_ids: [2]
Is_internal: true
Digest: 28a4a8e02337290d2dbc6e123f8b3abf1aabd02f3dedbaf4fd0783ae118f7f8a
Stats: bind_info:pseudo
Num_cop_tasks: 1
Cop_proc_avg: 0.001 Cop_proc_p90: 0.001 Cop_proc_max: 0.001 Cop_proc_addr: 172.22.12.13:20160
Cop_wait_avg: 0 Cop_wait_p90: 0 Cop_wait_max: 0 Cop_wait_addr: 172.22.12.13:20160
Mem_max: 144
Succ: true
select original_sql, bind_sql, default_db, status, create_time, update_time, charset, collation from mysql.bind_info where update_time >= "0000-00-00 00:00:00";

2. What did you expect to see?
The Query_time is not correct actually, the query is so fast.

3. What did you see instead?
None.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
(4000)-[test]> select tidb_version()\G;
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-102-g5ee0847ca
Git Commit Hash: 5ee0847cabb3cf80f079e2235f6a218f02ca7aa4
Git Branch: master
UTC Build Time: 2019-08-20 03:16:50
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by zz-jason** [comment]
Thanks for your feedback! It's fixed by https://github.com/pingcap/tidb/pull/11822, you can update the tidb-server to the latest master branch to fix it.

**Comment by zz-jason** [comment]
fixed by https://github.com/pingcap/tidb/pull/11822
