### ISSUE TITLE
请问tikv最少几个才能保证高可用？

### ISSUE THREAD

**Issue by mefly521** [pingcap/tidb#12036]
我使用 官方例子 tidb-docker-compose 起了3个tikv, 手动stop ,如果stop 了1个，没有问题，如果stop2个， 就是还剩一个tikv 时，无法访问了，是不是有要求最少起动2个呢，我看文档上没有详细说明。谢谢。

**Comment by francis0407** [comment]
TiKV uses **Raft** as its consensus algorithm. Raft makes sure that the system always keeps consistent when **more than half of the nodes** are alive.

For example, if you have a TiKV cluster of **3 nodes**, TiKV couldn't work when **2 nodes** failed. If you have a cluster of **5 nodes**, TiKV couldn'd work when **3 nodes** failed.

Raft paper reference: https://raft.github.io/raft.pdf
