### ISSUE TITLE
Vectorize hash calculation in hashJoin.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#12048]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In `hashJoin`, we do the hash calculation for a chunk row by row https://github.com/pingcap/tidb/blob/1ff620d/executor/hash_table.go#L143-L153, can try to vectorize it for performance.

**Describe the feature you'd like:**

- [x] vectorize hash calculation during building hash table. #12076 by @sduzh 
- [x] vectorize hash calculation during probing. #12669 by @sduzh 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by sduzh** [comment]
I can fix it

**Comment by shenli** [comment]
@sduzh Cool

**Comment by SunRunAway** [comment]
Hi @sduzh, Thanks for your awesome contribution.
Do you have time to do another job? 
We can also vectorize the way to calculate hash values for the probe rows.

**Comment by sduzh** [comment]
> Hi @sduzh, Thanks for your awesome contribution.
> Do you have time to do another job?
> We can also vectorize the way to calculate hash values for the probe rows.

Yes, no problem. @SunRunAway

**Comment by SunRunAway** [comment]
@sduzh A friendly ping, how's it going?

**Comment by sduzh** [comment]
> @sduzh A friendly ping, how's it going?

I finished the vectorized hash value calculation of probe phase weeks ago but the benchmark scores are decreased. 
I will take an investigation of that this weekend and try to resolve it.
