### ISSUE TITLE
query both max and min very slow

### ISSUE THREAD

**Issue by bearHunting** [pingcap/tidb#12040]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
for a field with index, such as fa, query with both max and min, such as select max(fa), min(fa) from table_name

2. What did you expect to see?
result comes out very quickly

3. What did you see instead?
query running without any comeout.
but when run for single max(fa) or min(fa), result comes out in a second

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.13
![tidb bug report](https://user-images.githubusercontent.com/51019717/64317470-5eb92680-cfea-11e9-9a6e-3b94945532ad.png)

**Comment by francis0407** [comment]
Thanks for your reporting.
TiDB only rewrites single `max/min` to `sort + limit 1` currently, I'm gonna fix this.
