### ISSUE TITLE
Store 40tb data, how to allocate TiDB, PD, TiKV nodes？

### ISSUE THREAD

**Issue by sundayha** [pingcap/tidb#12066]
This is my plan：
```
10 tidb nodes
10 pd nodes
20 tikv nodes
```
Is this possible to distribute? Any better suggestions?

**Comment by lucklove** [comment]
Hi~ @sundayha , it seems something is still not very clear:
- what's your workload? OLTP or OLAP?
- how busy is your business? eg. what's your expected QPS or TPS?
- what's your expected availability? 99.99%，99.999% or 99.9999%?
- the disk capacity for each tikv node?

**Comment by dbaoutdo** [comment]
Hi @sundayha .
I am TiDB internet Architect, Maybe we can have a chat with wechat, you can add me（dbaoutdo）.
