### ISSUE TITLE
Call For Participation: vectorize all Decimal builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12102]
This issue is used to trace all vectorized Decimal builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----
- [x] builtinArithmeticPlusDecimalSig
- [x] builtinArithmeticMinusDecimalSig
- [x] builtinArithmeticMultiplyDecimalSig
- [x] builtinArithmeticDivideDecimalSig
- [x] builtinArithmeticModDecimalSig
- [x] builtinCastIntAsDecimalSig
- [x] builtinCastRealAsDecimalSig
- [x] builtinCastDecimalAsDecimalSig
- [x] builtinCastStringAsDecimalSig
- [x] builtinCastTimeAsDecimalSig
- [x] builtinCastDurationAsDecimalSig
- [x] builtinCastJSONAsDecimalSig
- [x] builtinCoalesceDecimalSig
- [x] builtinGreatestDecimalSig @Reminiscent https://github.com/pingcap/tidb/pull/12077
- [x] builtinLeastDecimalSig
- [x] builtinCaseWhenDecimalSig
- [x] builtinIfDecimalSig  #12140
- [x] builtinIfNullDecimalSig
- [x] builtinAbsDecSig https://github.com/pingcap/tidb/pull/12158
- [x] builtinRoundDecSig
- [x] builtinRoundWithFracDecSig
- [x] builtinCeilIntToDecSig
- [x] builtinCeilDecToDecSig
- [x] builtinFloorIntToDecSig
- [x] builtinFloorDecToDecSig
- [x] builtinTruncateDecimalSig
- [x] builtinDecimalAnyValueSig
- [x] builtinNameConstDecimalSig
- [x] builtinUnaryMinusDecimalSig
- [x] builtinUnixTimestampDecSig

**Comment by FateTHarlaown** [comment]
can I work at `builtinAbsDecSig` ? ^_^

**Comment by tangwz** [comment]
Let me fix:
builtinCeilIntToDecSig
builtinCeilDecToDecSig
builtinFloorIntToDecSig
builtinFloorDecToDecSig

**Comment by Thincher** [comment]
let me fix:
builtinUnixTimestampDecSig

**Comment by ZhaoQian888** [comment]
I will fix :
 builtinCastRealAsDecimalSig
 builtinCastDurationAsDecimalSig
 builtinCastStringAsDecimalSig
 builtinCastJSONAsDecimalSig

**Comment by pingyu** [comment]
Let me fix:
`builtinUnaryMinusDecimalSig`

**Comment by qw4990** [comment]
Close due to finish.
