### ISSUE TITLE
Call For Participation: vectorize all String builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12106]
This issue is used to trace all vectorized Real builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----
- [x] builtinCastIntAsStringSig
- [x] builtinCastRealAsStringSig
- [x] builtinCastDecimalAsStringSig
- [x] builtinCastStringAsStringSig
- [x] builtinCastTimeAsStringSig
- [x] builtinCastDurationAsStringSig
- [x] builtinCastJSONAsStringSig
- [x] builtinCoalesceStringSig
- [x] builtinGreatestStringSig
- [x] builtinGreatestTimeSig
- [x] builtinLeastStringSig
- [x] builtinLeastTimeSig
- [x] builtinCaseWhenStringSig
- [x] builtinIfStringSig  #12140
- [x] builtinIfNullStringSig
- [x] builtinAesDecryptSig
- [x] builtinAesDecryptIVSig
- [x] builtinAesEncryptSig
- [x] builtinAesEncryptIVSig
- [x] builtinDecodeSig
- [x] builtinEncodeSig
- [x] builtinPasswordSig
- [x] builtinRandomBytesSig
- [x] builtinMD5Sig
- [x] builtinSHA1Sig
- [x] builtinSHA2Sig
- [x] builtinCompressSig
- [x] builtinUncompressSig
- [x] builtinDatabaseSig
- [x] builtinCurrentUserSig
- [x] builtinCurrentRoleSig
- [x] builtinUserSig
- [x] builtinVersionSig
- [x] builtinTiDBVersionSig
- [x] builtinJSONTypeSig
- [x] builtinJSONUnquoteSig
- [x] builtinJSONQuoteSig
- [x] builtinConvSig
- [x] builtinStringAnyValueSig
- [x] builtinInetNtoaSig @Reminiscent https://github.com/pingcap/tidb/pull/12088
- [x] builtinInet6AtonSig
- [x] builtinInet6NtoaSig
- [x] builtinNameConstStringSig
- [x] builtinUUIDSig
- [x] builtinRowSig
- [x] builtinSetVarSig
- [x] builtinGetVarSig
- [x] builtinGetParamStringSig
- [x] builtinConcatSig
- [x] builtinConcatWSSig
- [x] builtinLeftBinarySig
- [x] builtinLeftSig
- [x] builtinRightBinarySig
- [x] builtinRightSig
- [x] builtinRepeatSig @qw4990 https://github.com/pingcap/tidb/pull/12014
- [x] builtinLowerSig @qw4990 https://github.com/pingcap/tidb/pull/12013
- [x] builtinReverseBinarySig
- [x] builtinReverseSig
- [x] builtinSpaceSig
- [x] builtinUpperSig
- [x] builtinReplaceSig
- [x] builtinConvertSig
- [x] builtinSubstringBinary2ArgsSig
- [x] builtinSubstring2ArgsSig
- [x] builtinSubstringBinary3ArgsSig
- [x] builtinSubstring3ArgsSig
- [x] builtinSubstringIndexSig
- [x] builtinHexStrArgSig
- [x] builtinHexIntArgSig
- [x] builtinUnHexSig
- [x] builtinTrim1ArgSig
- [x] builtinTrim2ArgsSig
- [x] builtinTrim3ArgsSig
- [x] builtinLTrimSig
- [x] builtinRTrimSig
- [x] builtinLpadBinarySig
- [x] builtinLpadSig
- [x] builtinRpadBinarySig
- [x] builtinRpadSig
- [x] builtinCharSig
- [x] builtinMakeSetSig
- [x] builtinOctIntSig
- [x] builtinOctStringSig
- [x] builtinQuoteSig
- [x] builtinBinSig
- [x] builtinEltSig
- [x] builtinExportSet3ArgSig
- [x] builtinExportSet4ArgSig
- [x] builtinExportSet5ArgSig
- [x] builtinFormatWithLocaleSig
- [x] builtinFormatSig
- [x] builtinFromBase64Sig
- [x] builtinToBase64Sig
- [x] builtinInsertBinarySig
- [x] builtinInsertSig
- [x] builtinDateFormatSig
- [x] builtinMonthNameSig
- [x] builtinDayNameSig
- [x] builtinFromUnixTime2ArgSig
- [x] builtinGetFormatSig
- [x] builtinAddTimeStringNullSig
- [x] builtinAddStringAndDurationSig
- [x] builtinAddStringAndStringSig
- [x] builtinAddDateAndDurationSig
- [x] builtinAddDateAndStringSig
- [x] builtinTimeFormatSig
- [x] builtinTimestampAddSig

---

Prefer to implement them by go generate, see https://docs.google.com/document/d/17XdYo_EwYaWANqbjS3i3OVSz3oLlovU2fIo1bRx4YqA/edit#, and find your interest and take a job.

builtinSubDateAndDurationSig
builtinSubDateAndStringSig
builtinSubDatetimeAndDurationSig
builtinSubDatetimeAndStringSig
builtinSubDurationAndDurationSig
builtinSubDurationAndStringSig
builtinSubStringAndDurationSig
builtinSubStringAndStringSig
builtinSubTimeDateTimeNullSig
builtinSubTimeDurationNullSig
builtinSubTimeStringNullSig

**Comment by shihongzhi** [comment]
Let me fix:
builtinLeftSig
builtinRightSig

**Comment by tsthght** [comment]
Let me fix:
 builtinCastIntAsStringSig
 builtinCastRealAsStringSig
 builtinCastDecimalAsStringSig
 builtinCastStringAsStringSig
 builtinCastTimeAsStringSig
 builtinCastDurationAsStringSig
 builtinCastJSONAsStringSig

**Comment by shihongzhi** [comment]
Let me fix:
 builtinTrim1ArgSig
 builtinTrim2ArgsSig
 builtinTrim3ArgsSig
 builtinLTrimSig
 builtinRTrimSig

**Comment by tsthght** [comment]
let me fix:
builtinNameConstStringSig
builtinUUIDSig

**Comment by mmyj** [comment]
let me fix:
builtinStringAnyValueSig

**Comment by tsthght** [comment]
let me fix:
builtinConvertSig

**Comment by mmyj** [comment]
let me fix:
builtinOctStringSig

**Comment by mmyj** [comment]
let me fix:
builtinEncodeSig

**Comment by mmyj** [comment]
let me fix:
builtinDecodeSig

**Comment by mmyj** [comment]
let me fix: 
builtinMD5Sig
builtinSHA1Sig
builtinSHA2Sig

**Comment by shihongzhi** [comment]
Let me fix:
builtinCompressSig
builtinUncompressSig

**Comment by mmyj** [comment]
Let me fix: 
builtinAesDecryptSig
builtinAesDecryptIVSig
builtinAesEncryptSig
builtinAesEncryptIVSig

**Comment by mmyj** [comment]
Let me fix:
builtinPasswordSig

**Comment by mmyj** [comment]
Let me fix:
builtinGreatestStringSig

**Comment by mmyj** [comment]
Let me fix:
builtinCoalesceStringSig

**Comment by mmyj** [comment]
Let me fix:
builtinRandomBytesSig

**Comment by mmyj** [comment]
Let me fix:
builtinInet6AtonSig

**Comment by shihongzhi** [comment]
Let me fix:
builtinTimestampAddSig

**Comment by icditwang** [comment]
let me fix:
builtinReverseBinarySig

**Comment by TennyZhuang** [comment]
@qw4990 please add `builtinTiDBDecodeKeySig` in checklist.

**Comment by js00070** [comment]
let me fix:
builtinAesDecryptSig
builtinAesDecryptIVSig
builtinAesEncryptSig
builtinAesEncryptIVSig

**Comment by shihongzhi** [comment]
Let me fix:
 builtinCurrentUserSig
 builtinCurrentRoleSig
 builtinUserSig

**Comment by js00070** [comment]
let me fix:
builtinHexIntArgSig

**Comment by mmyj** [comment]
let me fix:
builtinConcatWSSig

**Comment by shihongzhi** [comment]
let me fix:
 builtinSubStringAndDurationSig
 builtinSubStringAndStringSig
 builtinSubTimeStringNullSig
 builtinSubDateAndDurationSig
 builtinSubDateAndStringSig

**Comment by pku-hjw** [comment]
let me fix：
builtinFormatWithLocaleSig

**Comment by Tian-JQ** [comment]
let me fix:
builtinLeastTimeSig

**Comment by qin-xun** [comment]
let me fix:
builtinCharSig

**Comment by SilvaXiang** [comment]
let me fix:
builtinSubTimeStringNullSig

**Comment by mmyj** [comment]
let me fix:
builtinLpadBinarySig

**Comment by icditwang** [comment]
let me fix:
builtinInet6NtoaSig

**Comment by js00070** [comment]
let me fix:
builtinAesEncryptIVSig
builtinAesDecryptIVSig

**Comment by lance6716** [comment]
let me fix:
builtinFormatWithLocaleSig

**Comment by qw4990** [comment]
Close due to finish. Thanks to all our contributors.
