### ISSUE TITLE
Call For Participation: vectorize all JSON builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12104]
This issue is used to trace all vectorized JSON builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----
- [x] builtinCastIntAsJSONSig
- [x] builtinCastRealAsJSONSig
- [x] builtinCastDecimalAsJSONSig
- [x] builtinCastStringAsJSONSig
- [x] builtinCastDurationAsJSONSig
- [x] builtinCastTimeAsJSONSig
- [x] builtinCastJSONAsJSONSig
- [x] builtinCoalesceJSONSig
- [x] builtinCaseWhenJSONSig
- [x] builtinIfJSONSig @Reminiscent https://github.com/pingcap/tidb/pull/12081
- [x] builtinIfNullJSONSig
- [x] builtinJSONExtractSig
- [x] builtinJSONSetSig
- [x] builtinJSONInsertSig
- [x] builtinJSONReplaceSig
- [x] builtinJSONRemoveSig
- [x] builtinJSONMergeSig
- [x] builtinJSONObjectSig
- [x] builtinJSONArraySig
- [ ] builtinJSONArrayAppendSig
- [x] builtinJSONArrayInsertSig
- [ ] builtinJSONSearchSig
- [x] builtinJSONKeysSig
- [x] builtinJSONKeys2ArgsSig
- [x] builtinJSONAnyValueSig
- [x] builtinNameConstJSONSig
- [x] builtinJSONUnquoteSig

**Comment by js00070** [comment]
working on builtinJSONObjectSig

**Comment by tsthght** [comment]
let me fix:
builtinCastDecimalAsJSONSig
builtinCastStringAsJSONSig
builtinCastDurationAsJSONSig
builtinCastTimeAsJSONSig
builtinCastJSONAsJSONSig

**Comment by tsthght** [comment]
let me fix:
builtinJSONAnyValueSig

**Comment by zhenghaoz** [comment]
Let me fix:
- builtinJSONSearchSig

**Comment by icditwang** [comment]
let me fix :
builtinJSONArraySig

**Comment by pingyu** [comment]
let me fix:
builtinJSONExtractSig

**Comment by scarydemon2** [comment]
let me fix:
 builtinJSONSetSig

**Comment by zhang2j** [comment]
let me fix:
builtinJSONReplaceSig

**Comment by scarydemon2** [comment]
let me fix:
builtinJSONInsertSig
builtinJSONReplaceSig

**Comment by Darkone0** [comment]
Let me fix
builtinJSONInsertSig

**Comment by Darkone0** [comment]
Let me fix
builtinJSONInsertSig

**Comment by scarydemon2** [comment]
let me fix:
 builtinJSONRemoveSig

**Comment by js00070** [comment]
let me fix:
builtinJSONArrayAppendSig
builtinJSONArrayInsertSig
