### ISSUE TITLE
Call For Participation: vectorize all Date/Time builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12101]
This issue is used to trace all vectorized Data/Time builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----
- [x] builtinCastIntAsTimeSig
- [x] builtinCastRealAsTimeSig
- [x] builtinCastDecimalAsTimeSig
- [x] builtinCastStringAsTimeSig
- [x] builtinCastTimeAsTimeSig
- [x] builtinCastDurationAsTimeSig
- [x] builtinCastJSONAsTimeSig
- [x] builtinCoalesceTimeSig
- [x] builtinCaseWhenTimeSig
- [x] builtinIfTimeSig  #12140
- [x] builtinIfNullTimeSig
- [x] builtinTimeAnyValueSig
- [x] builtinNameConstTimeSig
- [x] builtinDateSig @hey-kong https://github.com/pingcap/tidb/pull/12136
- [x] builtinDateLiteralSig
- [x] builtinFromDaysSig
- [x] builtinFromUnixTime1ArgSig
- [x] builtinStrToDateDateSig
- [x] builtinStrToDateDatetimeSig
- [x] builtinSysDateWithFspSig
- [x] builtinSysDateWithoutFspSig
- [x] builtinCurrentDateSig
- [x] builtinUTCDateSig
- [x] builtinUTCTimestampWithArgSig
- [x] builtinUTCTimestampWithoutArgSig
- [x] builtinNowWithArgSig
- [x] builtinNowWithoutArgSig
- [x] builtinTimestamp1ArgSig @Reminiscent https://github.com/pingcap/tidb/pull/12339
- [x] builtinTimestamp2ArgsSig @Reminiscent https://github.com/pingcap/tidb/pull/12352
- [x] builtinTimestampLiteralSig
- [x] builtinAddTimeDateTimeNullSig
- [x] builtinAddDatetimeAndDurationSig
- [x] builtinAddDatetimeAndStringSig
- [ ] builtinConvertTzSig
- [x] builtinMakeDateSig
- [x] builtinLastDaySig
- [x] builtinTidbParseTsoSig
---

Prefer to implement them by go generate, see https://docs.google.com/document/d/17XdYo_EwYaWANqbjS3i3OVSz3oLlovU2fIo1bRx4YqA/edit#, and find your interest and take a job.

builtinAddDateStringStringSig
builtinAddDateStringIntSig
builtinAddDateStringRealSig
builtinAddDateStringDecimalSig
builtinAddDateIntStringSig
builtinAddDateIntIntSig
builtinAddDateIntRealSig
builtinAddDateIntDecimalSig
builtinAddDateDatetimeStringSig
builtinAddDateDatetimeIntSig
builtinAddDateDatetimeRealSig
builtinAddDateDatetimeDecimalSig
builtinAddDateDurationStringSig
builtinAddDateDurationIntSig
builtinAddDateDurationRealSig
builtinAddDateDurationDecimalSig

builtinSubDateStringStringSig
builtinSubDateStringIntSig
builtinSubDateStringRealSig
builtinSubDateStringDecimalSig
builtinSubDateIntStringSig
builtinSubDateIntIntSig
builtinSubDateIntRealSig
builtinSubDateIntDecimalSig
builtinSubDateDatetimeStringSig
builtinSubDateDatetimeIntSig
builtinSubDateDatetimeRealSig
builtinSubDateDatetimeDecimalSig
builtinSubDateDurationStringSig
builtinSubDateDurationIntSig
builtinSubDateDurationRealSig
builtinSubDateDurationDecimalSig

builtinSubDateAndDurationSig
builtinSubDateAndStringSig
builtinSubDatetimeAndDurationSig
builtinSubDatetimeAndStringSig
builtinSubDurationAndDurationSig
builtinSubDurationAndStringSig
builtinSubStringAndDurationSig
builtinSubStringAndStringSig
builtinSubTimeDateTimeNullSig
builtinSubTimeDurationNullSig
builtinSubTimeStringNullSig

**Comment by tsthght** [comment]
let me fix:
builtinTimeAnyValueSig
builtinNameConstTimeSig

**Comment by mmyj** [comment]
let me fix:
'builtinUTCTimeWithArgSig' 
'builtinUTCTimestampWithArgSig'
'builtinUTCTimeWithoutArgSig'
'builtinUTCTimestampWithoutArgSig'

**Comment by ekalinin** [comment]
`builtinCoalesceTimeSig` implemented in #13015

**Comment by lwxwx** [comment]
expression: implement vectorized evaluation for 'builtinNowWithoutArgSig' #13341

**Comment by hakwolf** [comment]
这个咋找没有实现的函数？感觉上面列出来的函数我搜了下代码都写好了。

**Comment by Thincher** [comment]
let me fix :
'builtinAddDateIntStringSig'

**Comment by jiangyuzhao** [comment]
let me fix:
`builtinSubTimeDateTimeNullSig`

**Comment by Tian-JQ** [comment]
let me fix:
builtinTimestampLiteralSig

**Comment by Tyrone-Wu** [comment]
let me fix:
builtinSubDurationAndDurationSig

**Comment by pku-hjw** [comment]
let me fix：
builtinAddDateIntIntSig

**Comment by ZhaoQian888** [comment]
I will fix 
builtinSubDateStringStringSig

**Comment by pingyu** [comment]
Let me fix:
`builtinDateLiteralSig`

**Comment by pingyu** [comment]
Let me fix:
`builtinStrToDateDateSig`

**Comment by icditwang** [comment]
let me fix:
builtinAddDateStringDecimalSig
builtinAddDateIntStringSig
builtinAddDateIntRealSig
builtinAddDateIntDecimalSig

**Comment by SilvaXiang** [comment]
let me fix builtinSubTimeDateTimeNullSig

**Comment by ekalinin** [comment]
JFYI:

There's a plan to to use `template` package to generate some built-in functions:
- https://docs.google.com/document/d/17XdYo_EwYaWANqbjS3i3OVSz3oLlovU2fIo1bRx4YqA

Functions like `builtinAddDate*`, `builtinSubDate*` are in that list.

**Comment by lelouchB** [comment]
Hi, I would like to work on
builtinConvertTzSig
