### ISSUE TITLE
Call For Participation: vectorize all Real builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12105]
This issue is used to trace all vectorized Real builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----
- [x] builtinArithmeticPlusRealSig
- [x] builtinArithmeticMinusRealSig
- [x] builtinArithmeticMultiplyRealSig
- [x] builtinArithmeticDivideRealSig
- [x] builtinArithmeticModRealSig
- [x] builtinCastIntAsRealSig @jacklightChen https://github.com/pingcap/tidb/pull/12214
- [x] builtinCastRealAsRealSig
- [x] builtinCastDecimalAsRealSig
- [x] builtinCastStringAsRealSig
- [x] builtinCastTimeAsRealSig
- [x] builtinCastDurationAsRealSig
- [x] builtinCastJSONAsRealSig
- [x] builtinCoalesceRealSig
- [x] builtinGreatestRealSig
- [x] builtinLeastRealSig
- [x] builtinCaseWhenRealSig
- [x] builtinIfRealSig #12140
- [x] builtinIfNullRealSig
- [x] builtinAbsRealSig
- [x] builtinRoundRealSig
- [x] builtinRoundWithFracRealSig
- [x] builtinCeilRealSig
- [x] builtinFloorRealSig
- [x] builtinLog1ArgSig @Handora https://github.com/pingcap/tidb/pull/12285
- [x] builtinLog2ArgsSig
- [x] builtinLog2Sig
- [x] builtinLog10Sig @qw4990 https://github.com/pingcap/tidb/pull/12012
- [x] builtinRandSig
- [x] builtinRandWithSeedSig
- [x] builtinPowSig @tsthght https://github.com/pingcap/tidb/pull/12242
- [x] builtinSqrtSig https://github.com/pingcap/tidb/pull/12187
- [x] builtinAcosSig @jacklightChen https://github.com/pingcap/tidb/pull/12221
- [x] builtinAsinSig @jacklightChen https://github.com/pingcap/tidb/pull/12222
- [x] builtinAtan1ArgSig @jacklightChen  https://github.com/pingcap/tidb/pull/12227
- [x] builtinAtan2ArgsSig
- [x] builtinCosSig
- [x] builtinCotSig
- [x] builtinDegreesSig
- [x] builtinExpSig
- [x] builtinPISig
- [x] builtinRadiansSig
- [x] builtinSinSig
- [x] builtinTanSig
- [x] builtinTruncateRealSig
- [x] builtinRealAnyValueSig
- [x] builtinNameConstRealSig
- [x] builtinUnaryMinusRealSig
- [x] builtinDayNameSig

**Comment by tsthght** [comment]
builtinPowSig @tsthght

**Comment by ZoeShaw101** [comment]
builtinLog2Sig @ZowShaw101

**Comment by tsthght** [comment]
let me fix :
builtinAbsRealSig
builtinRoundRealSig
builtinRoundWithFracRealSig
builtinCeilRealSig
builtinFloorRealSig
builtinLog1ArgSig
builtinLog2ArgsSig

**Comment by hellojujian** [comment]
Let me fix it:
`builtinCastRealAsRealSig`

**Comment by tsthght** [comment]
Let me fix it:
builtinTruncateRealSig
builtinPISig

**Comment by polyrabbit** [comment]
Working on:
builtinCastTimeAsRealSig

**Comment by tsthght** [comment]
Let me fix it:
builtinRealAnyValueSig
builtinNameConstRealSig
builtinRandWithSeedSig
builtinUnaryMinusRealSig
builtinIfNullRealSig

**Comment by PiotrNewt** [comment]
@qw4990  Is something wrong?
Because we saw this issue in [the list of performance challenges](https://github.com/pingcap/tidb/projects/26#column-6922454).

**Comment by pingyu** [comment]
Let me fix it:
`builtinCastStringAsRealSig`

**Comment by VieDica** [comment]
Let me fix it:
builtinCastRealAsRealSig

**Comment by VieDica** [comment]
Let me fix it:
builtinValuesRealSig

**Comment by qw4990** [comment]
Close due to finish.
