### ISSUE TITLE
Call For Participation: vectorize all Int builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12103]
This issue is used to trace all vectorized Int builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----
- [x] builtinArithmeticPlusIntSig
- [x] builtinArithmeticMinusIntSig
- [x] builtinArithmeticMultiplyIntUnsignedSig
- [x] builtinArithmeticMultiplyIntSig
- [x] builtinArithmeticIntDivideIntSig
- [x] builtinArithmeticIntDivideDecimalSig
- [x] builtinArithmeticModIntSig
- [x] builtinCastIntAsIntSig @qw4990 https://github.com/pingcap/tidb/pull/11826
- [x] builtinCastRealAsIntSig
- [x] builtinCastDecimalAsIntSig
- [x] builtinCastStringAsIntSig
- [x] builtinCastTimeAsIntSig
- [x] builtinCastDurationAsIntSig
- [x] builtinCastJSONAsIntSig
- [x] builtinCoalesceIntSig
- [x] builtinGreatestIntSig
- [x] builtinLeastIntSig
- [x] builtinIntervalIntSig
- [x] builtinIntervalRealSig
- [x] builtinLTIntSig
- [x] builtinLTRealSig
- [x] builtinLTDecimalSig
- [x] builtinLTStringSig
- [x] builtinLTDurationSig
- [x] builtinLTTimeSig
- [x] builtinLTJSONSig
- [x] builtinLEIntSig
- [x] builtinLERealSig
- [x] builtinLEDecimalSig
- [x] builtinLEStringSig
- [x] builtinLEDurationSig
- [x] builtinLETimeSig
- [x] builtinLEJSONSig
- [x] builtinGTIntSig
- [x] builtinGTRealSig
- [x] builtinGTDecimalSig
- [x] builtinGTStringSig
- [x] builtinGTDurationSig
- [x] builtinGTTimeSig
- [x] builtinGTJSONSig
- [x] builtinGEIntSig
- [x] builtinGERealSig
- [x] builtinGEDecimalSig
- [x] builtinGEStringSig
- [x] builtinGEDurationSig
- [x] builtinGETimeSig
- [x] builtinGEJSONSig
- [x] builtinEQIntSig
- [x] builtinEQRealSig
- [x] builtinEQDecimalSig
- [x] builtinEQStringSig
- [x] builtinEQDurationSig
- [x] builtinEQTimeSig
- [x] builtinEQJSONSig
- [x] builtinNEIntSig
- [x] builtinNERealSig
- [x] builtinNEDecimalSig
- [x] builtinNEStringSig
- [x] builtinNEDurationSig
- [x] builtinNETimeSig
- [x] builtinNEJSONSig
- [x] builtinNullEQIntSig
- [x] builtinNullEQRealSig
- [x] builtinNullEQDecimalSig
- [x] builtinNullEQStringSig
- [x] builtinNullEQDurationSig
- [x] builtinNullEQTimeSig
- [x] builtinNullEQJSONSig
- [x] builtinCaseWhenIntSig
- [x] builtinIfIntSig  #12140
- [x] builtinIfNullIntSig
- [x] builtinUncompressedLengthSig
- [x] builtinFoundRowsSig
- [x] builtinConnectionIDSig
- [x] builtinLastInsertIDSig
- [x] builtinLastInsertIDWithIDSig
- [x] builtinTiDBIsDDLOwnerSig
- [x] builtinBenchmarkSig
- [x] builtinRowCountSig
- [x] builtinJSONContainsPathSig
- [x] builtinJSONContainsSig
- [x] builtinJSONDepthSig
- [x] builtinJSONLengthSig
- [x] builtinLikeSig
- [x] builtinRegexpBinarySig
- [x] builtinRegexpSig
- [x] builtinAbsIntSig
- [x] builtinAbsUIntSig
- [x] builtinRoundIntSig
- [x] builtinRoundWithFracIntSig
- [x] builtinCeilIntToIntSig
- [x] builtinCeilDecToIntSig
- [x] builtinFloorIntToIntSig
- [x] builtinFloorDecToIntSig
- [x] builtinCRC32Sig
- [x] builtinSignSig
- [x] builtinTruncateIntSig
- [x] builtinTruncateUintSig
- [x] builtinSleepSig
- [x] builtinLockSig
- [x] builtinReleaseLockSig
- [x] builtinIntAnyValueSig
- [x] builtinInetAtonSig
- [x] builtinIsIPv4Sig
- [x] builtinIsIPv4CompatSig
- [x] builtinIsIPv4MappedSig
- [x] builtinIsIPv6Sig
- [x] builtinNameConstIntSig
- [x] builtinLogicAndSig
- [x] builtinLogicOrSig
- [x] builtinLogicXorSig
- [x] builtinBitAndSig
- [x] builtinBitOrSig
- [x] builtinBitXorSig
- [x] builtinLeftShiftSig
- [x] builtinRightShiftSig
- [x] builtinRealIsTrueSig
- [x] builtinDecimalIsTrueSig
- [x] builtinIntIsTrueSig
- [x] builtinRealIsFalseSig
- [x] builtinDecimalIsFalseSig
- [x] builtinIntIsFalseSig
- [x] builtinBitNegSig
- [x] builtinUnaryNotRealSig
- [x] builtinUnaryNotDecimalSig
- [x] builtinUnaryNotIntSig
- [x] builtinUnaryMinusIntSig
- [x] builtinDecimalIsNullSig
- [x] builtinDurationIsNullSig
- [x] builtinIntIsNullSig
- [x] builtinRealIsNullSig
- [x] builtinStringIsNullSig @b41sh https://github.com/pingcap/tidb/pull/12128
- [x] builtinTimeIsNullSig
- [x] builtinInIntSig
- [x] builtinInStringSig
- [x] builtinInRealSig
- [x] builtinInDecimalSig
- [x] builtinInTimeSig
- [x] builtinInDurationSig
- [x] builtinInJSONSig
- [x] builtinBitCountSig
- [x] builtinLengthSig
- [x] builtinASCIISig
- [x] builtinStrcmpSig
- [x] builtinLocateBinary2ArgsSig
- [x] builtinLocate2ArgsSig
- [x] builtinLocateBinary3ArgsSig
- [x] builtinLocate3ArgsSig
- [x] builtinBitLengthSig
- [x] builtinCharLengthBinarySig
- [x] builtinCharLengthSig
- [x] builtinFindInSetSig
- [x] builtinFieldIntSig
- [x] builtinFieldRealSig
- [x] builtinFieldStringSig
- [x] builtinOrdSig
- [x] builtinInstrSig
- [x] builtinInstrBinarySig
- [x] builtinDateDiffSig
- [x] builtinHourSig
- [x] builtinMinuteSig
- [x] builtinSecondSig
- [x] builtinMicroSecondSig
- [x] builtinMonthSig @qw4990 https://github.com/pingcap/tidb/pull/12018
- [x] builtinDayNameSig
- [x] builtinDayOfMonthSig
- [x] builtinDayOfWeekSig
- [x] builtinDayOfYearSig
- [x] builtinWeekWithModeSig
- [x] builtinWeekWithoutModeSig
- [x] builtinWeekDaySig
- [x] builtinWeekOfYearSig
- [x] builtinYearSig
- [x] builtinYearWeekWithModeSig
- [x] builtinYearWeekWithoutModeSig
- [x] builtinExtractDatetimeSig
- [x] builtinExtractDurationSig
- [x] builtinTimestampDiffSig
- [x] builtinUnixTimestampCurrentSig
- [x] builtinUnixTimestampIntSig
- [x] builtinPeriodAddSig
- [x] builtinPeriodDiffSig
- [x] builtinQuarterSig
- [x] builtinTimeToSecSig
- [x] builtinToDaysSig
- [x] builtinToSecondsSig

**Comment by tangwz** [comment]
let me fix `builtinLeastIntSig` and `builtinGreatestIntSig `.

**Comment by tangwz** [comment]
let me fix:
`builtinAbsIntSig`
`builtinAbsUIntSig `
`builtinRoundIntSig`
`builtinRoundWithFracIntSig`

**Comment by XiaTianliang** [comment]
I want to handle
builtinArithmeticPlusIntSig

**Comment by big747386** [comment]
let me fix:
builtinTruncateIntSig

**Comment by tangwz** [comment]
let me fix:
builtinLastInsertIDSig
builtinLastInsertIDWithIDSig
builtinCeilIntToIntSig
builtinCeilDecToIntSig
builtinFloorIntToIntSig
builtinFloorDecToIntSig

**Comment by liuhao2050** [comment]
let me if:
 builtinRealIsTrueSig
 builtinDecimalIsTrueSig
 builtinIntIsTrueSig
 builtinRealIsFalseSig
 builtinIntIsFalseSig
 builtinDecimalIsFalseSig

**Comment by gtygo** [comment]
let me fix:
builtinSignSig

**Comment by gtygo** [comment]
i will fix:  builtinNullEQDecimalSig

**Comment by tsthght** [comment]
let me fix:
builtinIntervalIntSig

**Comment by snithish** [comment]
I will take up `builtinBitOrSig`

**Comment by snithish** [comment]
I am also picking up `builtinBitAndSig` and `builtinBitXorSig`

**Comment by fzhedu** [comment]
Let me fix:
` builtinEQRealSig`
 `builtinEQDecimalSig`
 `builtinEQStringSig`
 `builtinEQDurationSig`
` builtinEQTimeSig`
 `builtinEQJSONSig`
` builtinNERealSig`
` builtinNEDecimalSig`
` builtinNEStringSig`
 `builtinNEDurationSig`
 `builtinNETimeSig`
 `builtinNEJSONSig`

**Comment by tangwz** [comment]
Let me fix:
 builtinCastRealAsIntSig
 builtinCastDecimalAsIntSig
 builtinCastStringAsIntSig
 builtinCastTimeAsIntSig
 builtinCastDurationAsIntSig
 builtinCastJSONAsIntSig

**Comment by snithish** [comment]
I am picking up `builtinLeftShiftSig` and `builtinRightShiftSig`

**Comment by snithish** [comment]
Picking up `builtinIsIPv4CompatSig`

**Comment by chacha923** [comment]
let me fix:
builtinWeekDaySig

**Comment by gtygo** [comment]
i will fix :
builtinNullEQIntSig
 builtinNullEQDurationSig
 builtinNullEQTimeSig
 builtinNullEQJSONSig

**Comment by rogaps** [comment]
I would like to try:
builtinHourSig
builtinMinuteSig
builtinSecondSig
builtinMicroSecondSig

**Comment by js00070** [comment]
working on:
builtinArithmeticMultiplyIntSig
builtinArithmeticPlusIntSig

**Comment by tsthght** [comment]
let me fix:
builtinLTIntSig
builtinLEIntSig
builtinGTIntSig
builtinEQIntSig
builtinNEIntSig

**Comment by icditwang** [comment]
let me fix:
builtinArithmeticIntDivideIntSig

**Comment by edytagarbarz** [comment]
let me fix:
builtinDayOfWeekSig

**Comment by cosmic-jc** [comment]
let me fix:
 builtinArithmeticModIntSig

**Comment by TommyCpp** [comment]
let me fix:
builtinIsIPv6Sig

**Comment by TommyCpp** [comment]
let me fix:
builtinIsIPv4CompatSig
builtinIsIPv4MappedSig

**Comment by shihongzhi** [comment]
Let me fix:
 builtinQuarterSig
 builtinTimeToSecSig
 builtinToDaysSig
 builtinToSecondsSig

**Comment by shihongzhi** [comment]
Let me fix:
 builtinTimestampDiffSig
 builtinUnixTimestampCurrentSig
 builtinUnixTimestampIntSig
 builtinPeriodAddSig
 builtinPeriodDiffSig

**Comment by 710698117** [comment]
Let me fix:
builtinDayOfYearSig

**Comment by TommyCpp** [comment]
Let me fix:
builtinInetAtonSig
builtinCRC32Sig
builtinStrcmpSig

**Comment by js00070** [comment]
let me fix:
builtinUncompressedLengthSig

**Comment by icditwang** [comment]
let me fix:
builtinFindInSetSig

**Comment by chenseifer** [comment]
let me fix builtinCastStringAsIntSig

**Comment by Tyrone-Wu** [comment]
let me fix:
builtinFoundRowsSig

**Comment by moodsjinxin** [comment]
let me fix:
builtinExtractDatetimeSig

**Comment by TommyCpp** [comment]
let me fix:
builtinUnixTimestampIntSig

**Comment by js00070** [comment]
let me fix:
builtinBitCountSig

**Comment by AerysNan** [comment]
Working on: `builtinBitNegSig`  and `builtinBitCountSig`.

**Comment by pingyu** [comment]
Let me fix:
`builtinArithmeticIntDivideDecimalSig`

**Comment by pingyu** [comment]
Let me fix:
`builtinBenchmarkSig`

**Comment by pingyu** [comment]
Let me fix:
`builtinLikeSig`

**Comment by Jargon96** [comment]
Let me fix:
**builtinReleaseLockSig**

**Comment by wtianyou** [comment]
Let me fix:
**builtinLockSig**

**Comment by shihongzhi** [comment]
let me fix:
builtinSleepSig

**Comment by younfor** [comment]
builtinBitCountSig

**Comment by ziyi-yan** [comment]
builtinSleepSig is done. ✅ @qw4990
