### ISSUE TITLE
Show coprocessor request duration in `explain analyze`

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#12148]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Sometimes slow query is caused by slow network, following is an example
![explain_analyze](https://user-images.githubusercontent.com/12077877/64665673-fbb20e80-d485-11e9-9d07-eba92192f744.png)
From the analyze result, we cannot know if it is the network slow or some other problem in tidb.

**Describe the feature you'd like:**

Add stats of the duration from sending a cop request to receiving a response.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
https://github.com/pingcap/tidb/pull/12003 is addressing this issue

**Comment by disksing** [comment]
Cool @zz-jason
