### ISSUE TITLE
Call For Participation: vectorize all Duration builtin functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#12176]
This issue is used to trace all vectorized Duration builtin functions, which is a part of https://github.com/pingcap/tidb/issues/12058.

**NOTE**:
1. Feel free to join us in the [`wg-vec-expr` working group](https://github.com/pingcap/community/blob/master/working-groups/wg-vec-expr.md)
2. Please comment on this issue if you are working on any of the functions.

**Note For Performance Challenge Teams: each PR on this issue has 50 score.**

-----

- [x] builtinDurationDurationTimeDiffSig
- [x] builtinTimeTimeTimeDiffSig
- [x] builtinDurationStringTimeDiffSig
- [x] builtinStringDurationTimeDiffSig
- [x] builtinTimeStringTimeDiffSig
- [x] builtinStringTimeTimeDiffSig
- [x] builtinStringStringTimeDiffSig
- [x] builtinNullTimeDiffSig
- [x] builtinStrToDateDurationSig
- [x] builtinCurrentTime0ArgSig
- [x] builtinCurrentTime1ArgSig
- [x] builtinTimeSig
- [x] builtinTimeLiteralSig
- [x] builtinAddTimeDurationNullSig
- [x] builtinAddDurationAndDurationSig
- [x] builtinAddDurationAndStringSig
- [x] builtinMakeTimeSig
- [x] builtinSecToTimeSig
- [x] builtinUTCTimeWithoutArgSig
- [x] builtinUTCTimeWithArgSig
- [x] builtinCastIntAsDurationSig
- [x] builtinCastRealAsDurationSig
- [x] builtinCastDecimalAsDurationSig
- [x] builtinCastStringAsDurationSig
- [x] builtinCastTimeAsDurationSig
- [x] builtinCastDurationAsDurationSig
- [x] builtinCastJSONAsDurationSig
- [x] builtinCaseWhenDurationSig
- [x] builtinIfDurationSig #12140
- [x] builtinIfNullDurationSig
- [x] builtinDurationAnyValueSig
- [x] builtinNameConstDurationSig
- [x] builtinCoalesceDurationSig

Prefer to implement them by go generate, see https://docs.google.com/document/d/17XdYo_EwYaWANqbjS3i3OVSz3oLlovU2fIo1bRx4YqA/edit#, and find your interest and take a job.

builtinAddDateStringStringSig
builtinAddDateStringIntSig
builtinAddDateStringRealSig
builtinAddDateStringDecimalSig
builtinAddDateIntStringSig
builtinAddDateIntIntSig
builtinAddDateIntRealSig
builtinAddDateIntDecimalSig
builtinAddDateDatetimeStringSig
builtinAddDateDatetimeIntSig
builtinAddDateDatetimeRealSig
builtinAddDateDatetimeDecimalSig
builtinAddDateDurationStringSig
builtinAddDateDurationIntSig
builtinAddDateDurationRealSig
builtinAddDateDurationDecimalSig

builtinSubDateStringStringSig
builtinSubDateStringIntSig
builtinSubDateStringRealSig
builtinSubDateStringDecimalSig
builtinSubDateIntStringSig
builtinSubDateIntIntSig
builtinSubDateIntRealSig
builtinSubDateIntDecimalSig
builtinSubDateDatetimeStringSig
builtinSubDateDatetimeIntSig
builtinSubDateDatetimeRealSig
builtinSubDateDatetimeDecimalSig
builtinSubDateDurationStringSig
builtinSubDateDurationIntSig
builtinSubDateDurationRealSig
builtinSubDateDurationDecimalSig

builtinSubDateAndDurationSig
builtinSubDateAndStringSig
builtinSubDatetimeAndDurationSig
builtinSubDatetimeAndStringSig
builtinSubDurationAndDurationSig
builtinSubDurationAndStringSig
builtinSubStringAndDurationSig
builtinSubStringAndStringSig
builtinSubTimeDateTimeNullSig
builtinSubTimeDurationNullSig
builtinSubTimeStringNullSig

**Comment by tsthght** [comment]
let me fix:
builtinDurationAnyValueSig

**Comment by mmyj** [comment]
let me fix it:
builtinCurrentTime0ArgSig
builtinCurrentTime1ArgSig

**Comment by mmyj** [comment]
let me fix it:
builtinDurationDurationTimeDiffSig

**Comment by mmyj** [comment]
let me fix it:
builtinAddDateDurationStringSig

**Comment by mmyj** [comment]
let me fix it:
builtinUTCTimeWithoutArgSig
builtinUTCTimeWithoutArgSig

**Comment by jiangyuzhao** [comment]
let me fix:
`builtinSubDurationAndDurationSig`

**Comment by chenseifer** [comment]
let me fix builtinCastDecimalAsDurationSig

**Comment by pingyu** [comment]
Let me fix:
`builtinStrToDateDurationSig`

**Comment by ZhaoQian888** [comment]
let me fix :
builtinTimeTimeTimeDiffSig
 builtinAddDateDurationIntSig
builtinAddDateDurationDecimalSig
 builtinAddDateDurationRealSig
builtinSubDateDurationStringSig

**Comment by Thincher** [comment]
(●'◡'●)  let me fix:
 builtinTimeSig
builtinTimeLiteralSig

**Comment by js00070** [comment]
let me fix:
builtinValuesDurationSig

**Comment by TommyCpp** [comment]
let me fix:
builtinMakeTimeSig

**Comment by rickif** [comment]
let me fix:
builtinCastRealAsDurationSig

**Comment by SilvaXiang** [comment]
let me fix builtinSubTimeDurationNullSig

**Comment by SilvaXiang** [comment]
let me fix
builtinSubDurationAndDurationSig
builtinSubDurationAndStringSig

**Comment by SunRunAway** [comment]
@SilvaXiang builtinSubXXXAndYYYSig may be resolved by go generate, could you take a look at https://docs.google.com/document/d/17XdYo_EwYaWANqbjS3i3OVSz3oLlovU2fIo1bRx4YqA/edit#

**Comment by qw4990** [comment]
Close due to finish.
