### ISSUE TITLE
COMMIT很慢

### ISSUE THREAD

**Issue by wonderful1984** [pingcap/tidb#12266]
1、使用pt-archive工具做数据归档
2、使用replace insert方式

环境：
CPU：Silver 4114 CPU @ 2.20GHz  (40 cores)
MEM：192G
DISK：12 * 6TB SATA Raid 10

碰到的问题是，commit很慢
<pre>
# Time: 2019-09-18T19:49:28.140573077+08:00
# Txn_start_ts: 411253437908123652
# User: ptarchiver@localhost
# Conn_ID: 26
# Query_time: 3.034497128
# Prewrite_time: 2.983078965 Commit_time: 0.051161617 Get_commit_ts_time: 0.000161934 Local_latch_wait_time: 7.748e-06 Write_keys: 5 Write_size: 464 Prewrite_region: 5
# DB: userDB
# Is_internal: false
# Digest: 9505cacb7c710ed17125fcc6cb3669e8ddca6c8cd8af6a31f6b3cd64604c3098
# Num_cop_tasks: 0
# Cop_proc_avg: 0 Cop_proc_p90: 0 Cop_proc_max: 0 Cop_proc_addr: 
# Cop_wait_avg: 0 Cop_wait_p90: 0 Cop_wait_max: 0 Cop_wait_addr: 
# Succ: true
commit;
</pre>

**Comment by wonderful1984** [comment]
![image](https://user-images.githubusercontent.com/39042682/65146148-b7a6a700-da4d-11e9-9a4d-8c65af2dc0fc.png)

**Comment by IT-xiaoge** [comment]
找到问题了吗？
