### ISSUE TITLE
tikv cpu usage is high

### ISSUE THREAD

**Issue by weenong** [pingcap/tidb#12295]
tikv在数据持续插入的时候，cpu占用率特别高，内存很低
Release Version: v3.0.2
Git Commit Hash: 94498e7d06a244196bb41c3a05dd4c1f6903099a
Git Branch: HEAD
UTC Build Time: 2019-08-07 02:35:52
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by zhouqiang-cl** [comment]
can you provide the grafana metrics  about  tikv's metric

**Comment by weenong** [comment]
![image](https://user-images.githubusercontent.com/20277992/65382538-57a84d00-dd3a-11e9-8ed8-85a1056d0ed1.png)
谢谢

**Comment by weenong** [comment]
![image](https://user-images.githubusercontent.com/20277992/65382799-edde7200-dd3e-11e9-992a-de8817ded9dc.png)
![image](https://user-images.githubusercontent.com/20277992/65382805-0babd700-dd3f-11e9-94d0-50730c6ab8a9.png)
![image](https://user-images.githubusercontent.com/20277992/65382820-4ada2800-dd3f-11e9-9512-9beb047aef6c.png)


> can you provide the grafana metrics about tikv's metric

**Comment by zhangjinpeng1987** [comment]
@weenong What is your expect?

**Comment by you06** [comment]
The metrics show that the CPU usage is not very high.

**Comment by zz-jason** [comment]
Hi @weenong, does this issue still exist?

**Comment by zz-jason** [comment]
closed due to outdated. feel free to reopen it once the same issue appears again.
