### ISSUE TITLE
Importing a 9MB SQL file consumes too many resource

### ISSUE THREAD

**Issue by snakeh36** [pingcap/tidb#12297]
大佬们，你好，目前在试着使用TIDB，在我笔记本上安装官方推荐的docker环境tidb-docker-compose，在导入9M多的sql文件时，出现卡死，笔记本风扇狂转问题，不知怎么优化解决。

**Comment by snakeh36** [comment]
➜  tidb-docker-compose git:(master) docker-compose stop
Stopping tidb-docker-compose_tispark-slave0_1 ...
Stopping tidb-docker-compose_tispark-master_1 ... error
Stopping tidb-docker-compose_tidb_1           ...
Stopping tidb-docker-compose_tikv0_1          ... error
Stopping tidb-docker-compose_tikv1_1          ... error
Stopping tidb-docker-compose_tikv2_1          ... error
Stopping tidb-docker-compose_grafana_1        ...
Stopping tidb-docker-compose_pd2_1            ... error
Stopping tidb-docker-compose_pd1_1            ... error
Stopping tidb-docker-compose_pushgateway_1    ...
Stopping tidb-docker-compose_prometheus_1     ...
Stopping tidb-docker-compose_tidb-vision_1    ...
Stopping tidb-docker-compose_pd0_1            ... error
ERROR: for tidb-docker-compose_grafana_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: for tidb-docker-compose_pushgateway_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: for tidb-docker-compose_tidb-vision_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: for tidb-docker-compose_tispark-slave0_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: for tidb-docker-compose_prometheus_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: for tidb-docker-compose_tidb_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
➜  tidb-docker-compose git:(master)

**Comment by snakeh36** [comment]
logs:
[logs.tar.gz](https://github.com/pingcap/tidb/files/3639805/logs.tar.gz)

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to reopen it if you need any further help.
