### ISSUE TITLE
make dev reports go generate error

### ISSUE THREAD

**Issue by XiaTianliang** [pingcap/tidb#12294]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
make dev

git diff from master
go.mod
+       google.golang.org/appengine v1.4.0 // indirect

go version go1.12.7 darwin/amd64

2. What did you expect to see?
paas

3. What did you see instead?
Great, All tests passed
explaintest end
go generate ./...
./tools/check/check-gogenerate.sh
make: *** [gogenerate] Error 1

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
master, latest

**Comment by bopjiang** [comment]
@XiaTianliang, I faced the same issue. How did you solve it?
