### ISSUE TITLE
Planner: support index advisor - Phase 1

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#12303]
## Description

Some basic functionality: 
- advising about removing an unused index.
- advising about adding an index that improves the query performance.

## Category

- Feature
- Performance
- Usability

### Value Description

Makes TiDB easier to use, reduces the SQL Tunning time during the application testing phase.

### Value  Score

> Optional value: 1~5

- 4

### Workload Estimation

> Workload contains coding, documenting, and testing.
> 1 Point for 1 Person/Work Day

- 45 Points

**Comment by lamxTyler** [comment]
Currently we are discussing the feature at #wg-index-advisor of [community slack](https://pingcap.com/tidbslack/), feel free to join and discuss the [design docs](https://docs.google.com/document/d/1duUO3FD4p0bQXCuEtwi8ad75xz6mDfwzG0c2pJ-LTwQ/edit) and [working plan](https://docs.google.com/document/d/1fsZJKiZV_To53Pvy2lE75g3KpJ1Jw6YO3HVNWQvp-Z8/edit) there.

**Comment by zz-jason** [comment]
With the system view described in https://github.com/pingcap/tidb/issues/17508, we can know the unused index for each table.

**Comment by qw4990** [comment]
The new design and implementation, please see https://github.com/pingcap/tidb_workload_analysis/tree/main/index_advisor.
