### ISSUE TITLE
Skip writing binlog in a backoff manner on error

### ISSUE THREAD

**Issue by aylei** [pingcap/tidb#12323]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, when a tidb-server with `ignore-error` set to `true` encounters an error when writing binlog, it will stop writing binlog anymore until get restarted. Therefore, users are forced to restart the tidb-servers to recover the binlog, and this will affect the traffic.

**Describe the feature you'd like:**

When an error occurs when writing binlog, the tidb-server should only skip writing binlog for an interval. This interval can be increased in a backoff manner (e.g. exponential backoff) if the writing binlog error continuously appear.

**Describe alternatives you've considered:**

Try to write binlog despite the errors anyway that have happened. This strategy is simple but may affect the performance.

cc @july2993 @tennix

**Comment by jebter** [comment]
Starting from TiDB v7.5.0, technical support for the data replication feature of TiDB Binlog is no longer provided. It is strongly recommended to use TiCDC as an alternative solution for data replication:https://docs.pingcap.com/tidb/dev/tidb-binlog-overview#tidb-binlog-cluster-overview . I will close this issue. If there are any updates, you can reopen it.
