### ISSUE TITLE
when execute SQL: `grant all on  ...`, Grant_priv should not be set to Y 

### ISSUE THREAD

**Issue by tsthght** [pingcap/tidb#12324]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
create user "ght1";
grant all on *.* to 'ght1'@'%' identified by 'Poiuy123';
select * from mysql.user where user='ght1'\G
*************************** 1. row ***************************
           Grant_priv: Y

If this is a bug, i want to fix it. @tiancaiamao 

2. What did you expect to see?
only `grant .... with grant option` should set Grant_priv to Y 
*************************** 1. row ***************************
           Grant_priv: N

3. What did you see instead?
create user "ght1";
grant all on *.* to 'ght1'@'%' identified by 'Poiuy123';
select * from mysql.user where user='ght1'\G
*************************** 1. row ***************************
           Grant_priv: N

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
*************************** 1. row ***************************
tidb_version(): Release Version: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: None
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by nullnotnil** [comment]
Confirming this is fixed in master:
```sql
drop user if exists ght1;
create user ght1;
grant all on *.* to ght1 identified by 'Poiuy123';
select Grant_priv from mysql.user where user='ght1';

..

mysql> select Grant_priv from mysql.user where user='ght1';
+------------+
| Grant_priv |
+------------+
| N          |
+------------+
1 row in set (0.00 sec)

mysql> 
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-807-g824df7675
Edition: Community
Git Commit Hash: 824df767559b8544af0cb71509135d322de1cd47
Git Branch: master
UTC Build Time: 2020-07-20 04:47:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now. Thanks!
