### ISSUE TITLE
Table with range columns can't add partition

### ISSUE THREAD

**Issue by Fatpa** [pingcap/tidb#12320]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Table Schema is 
```
CREATE TABLE `test4` (
  `stime` datetime DEFAULT NULL,
  KEY `stime` (`stime`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin 
PARTITION BY RANGE columns (stime) (
  PARTITION p20190901 VALUES LESS THAN ('2019-09-02 00:00:00'),
  PARTITION p20190902 VALUES LESS THAN ('2019-09-03 00:00:00')
);
```
and run the sql
```
ALTER TABLE test4 add partition (PARTITION p20190903 VALUES LESS THAN ('2019-09-04 00:00:00'));
```

2. What did you expect to see?
```Query OK, 0 rows affected```

3. What did you see instead?
```ERROR 1659 (HY000): Field '"2019-09-02 00:00:00"' is of a not allowed type for this type of partitioning```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
V3.0.2

**Comment by Fatpa** [comment]
It seems that can't work with string or datetime type.

**Comment by tiancaiamao** [comment]
Well, `partition by range` and `partition by range columns` shares some code, and `partition by range` has the constraint that **only int value is allowed in the partition expression**, this constraint is mistakenly imposed on `partition by range columns` and cause this bug.

**Comment by Fatpa** [comment]
The TODO on`ddl/partition.go`
```
// TODO: Remove the test 's.Partition.Expr == nil' when we support 'PARTITION BY RANGE COLUMNS'
if len(constraints) == 0 || s.Partition.Expr == nil {
	return nil
}
```
It looks like that the condition `s.Partition.Expr == nil` needs to be removed.

**Comment by tiancaiamao** [comment]
@crazycs520 is working on it.

**Comment by Fatpa** [comment]
Duplicate of #12792
