### ISSUE TITLE
Adding a syntax to display all supported builtin functions

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/tidb#12372]
TiDB has a lot of builtin functions, but sometimes I can't recall the name, but it is a little bit annoying to check the documentation just for a name (some functions don't even have documentation). If TiDB can add a new syntax and display all supported builtin functions, it seems convenient. Such as: SHOW BUILTINS or HELP BUILTINS.

**Comment by tangwz** [comment]
let me fix it.

**Comment by c4pt0r** [comment]
@tangwz  Hi, how's thing going? Just feel free to ask if you need any help  :)

**Comment by tangwz** [comment]
I will do it on holiday :)

**Comment by c4pt0r** [comment]
Well done! Looking forward to the implementation on tidb side.

**Comment by tangwz** [comment]
Did the builtin functions means the `funcs` in `expression/builtin.go`?

**Comment by c4pt0r** [comment]
Yes, I think so

**Comment by Kifen** [comment]
@tangwz are you working on this issue?

**Comment by tangwz** [comment]
@Kifen  I see ekalinin add a PR.

**Comment by zz-jason** [comment]
already fixed by https://github.com/pingcap/tidb/pull/12941
