### ISSUE TITLE
 For float(M,D), double(M,D) or decimal(M,D), M must be >= D

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#12450]
## Bug Report

```
SELECT 'o' DIV ( `col_tinyint_unsigned` / '2023-04-13 14:45:58.015569' ) AS field1 FROM `table1000_int_autoinc` LIMIT 185
```

See table schema and data at #12200
## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

**Comment by wjhuang2016** [comment]
Cannot reproduce it in both release3.0, release 4.0, and master.
