### ISSUE TITLE
Query plan display issue

### ISSUE THREAD

**Issue by Damon-PingCap** [pingcap/tidb#12475]
![image](https://user-images.githubusercontent.com/50732087/65829324-f3a3fc80-e2d6-11e9-9424-c9289f01ccee.png)
 range：decideb by 与实际用到的索引 range 不一致

version  2.1.9

**Comment by winoros** [comment]
@Damon-PingCap 
For the SQL like `select * from t, t1 where t.a=t1.c`.
If there's index (a) on t, then we can perform a index join and use t as the driven table. In this case, the `dicided by` msg would `decided by [t1.c]`. i.e. The `decided by` information of the driven table is the columns from the driving table.
So I cannot tell you that the message is wrong only by the information you given. We need more information like the full SQL text.

**Comment by Damon-PingCap** [comment]
The index contains three columns，school_id,order_type,state,  in the red frame of the picture and no user_id column. The range accessed through this index does not include user_id ,which is inconsistent with the decided by information.  Is this ambiguous?

**Comment by winoros** [comment]
@Damon-PingCap 
If the SQL is `driven_table.school_id=driving_table.user_id and driven_table.order_type=driving_table.school_id`, this explain result is correct.

**Comment by Damon-PingCap** [comment]
Thanks for your explanation, I can understand this query plan just feels that this display is ambiguous.

**Comment by winoros** [comment]
@Damon-PingCap 
It would become `eq(driven_table.col, driving_table.col)` in newer TiDB.

**Comment by Damon-PingCap** [comment]
ok，thanks 。
