### ISSUE TITLE
expected key separator '=', but got 'd' instead

### ISSUE THREAD

**Issue by wangchengting** [pingcap/tidb#12494]
2019/09/30 11:15:58 printer.go:52: [info] Welcome to syncer
2019/09/30 11:15:58 printer.go:53: [info] Release Version: v1.0.0-74-g5dfb795
2019/09/30 11:15:58 printer.go:54: [info] Git Commit Hash: 5dfb7950ae6f6d20c75d7de777bbd4e7d267f1e1
2019/09/30 11:15:58 printer.go:55: [info] Git Branch: master
2019/09/30 11:15:58 printer.go:56: [info] UTC Build Time: 2019-09-12 07:53:29
2019/09/30 11:15:58 printer.go:57: [info] Go Version: go version go1.12 linux/amd64
2019/09/30 11:15:58 main.go:55: [info] config: {"log-level":"info","log-file":"syncer.log","log-rotate":"day","status-addr":":8271","server-id":101,"meta":"/home/tidb/dumpdata/metadata","persistent-dir":"","flavor":"mysql","worker-count":16,"batch":100,"max-retry":100,"replicate-do-table":null,"replicate-do-db":null,"replicate-ignore-table":null,"replicate-ignore-db":null,"skip-ddls":[],"skip-dmls":null,"route-rules":null,"from":{"host":"192.168.196.164","user":"test","port":3306,"max-allowed-packet":67108864},"to":{"host":"127.0.0.1","user":"root","port":4000,"max-allowed-packet":67108864},"enable-gtid":false,"auto-fix-gtid":false,"disable-detect":false,"safe-mode":false,"config-file":"syncer_config.toml","stop-on-ddl":false,"execute-ddl-timeout":"3h","execute-dml-timeout":"1m","execute-queue-length":5000,"enable-ansi-quotes":false,"timezone":""}
2019/09/30 11:15:58 main.go:79: [error] Near line 1 (last key parsed 'Started'): expected key separator '=', but got 'd' instead
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/meta.go:97: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:163:  
[tidb@box164 tidb-enterprise-tools-latest-linux-amd64]$ sz syncer.log 

[tidb@box164 tidb-enterprise-tools-latest-linux-amd64]$ 
[syncer.log](https://github.com/pingcap/tidb/files/3668997/syncer.log)

**Comment by wangchengting** [comment]
I try to syncer mysql(5.7.26-log) data into tidb(5.7.25-TiDB-v3.0.0-beta.1-154-gd5afff70c) , it failed with above errors.

**Comment by kolbe** [comment]
@wangchengting This seems to be a problem with the format of the metadata. Can you zip up the contents of /home/tidb/dumpdata/metadata and upload it?

**Comment by tiancaiamao** [comment]
PTAL @GregoryIan

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to reopen it if you need any further help.
