### ISSUE TITLE
Unexpected error when execute "SELECT * FROM table WHERE column(varchar) > 0" ;

### ISSUE THREAD

**Issue by v01dstar** [pingcap/tidb#1254]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
Linux AMD64

3. What did you do?
SELECT COUNT(*) FROM pre_common_usergroup WHERE type='special' and system>0;
Schema of pre_common_usergroup:  
 
| Field           | Type                              | Null | Key | Default | Extra          |
|-----------------|-----------------------------------|------|-----|---------|----------------|
| groupid         | smallint(6) unsigned              | NO   | PRI | NULL    | auto_increment |
| radminid        | tinyint(3)                        | NO   |     | 0       |                |
| type            | enum('system','special','member') | NO   |     | member  |                |
| system          | varchar(255)                      | NO   |     | private |                |
| grouptitle      | varchar(255)                      | NO   |     |         |                |
| creditshigher   | int(10)                           | NO   | MUL | 0       |                |
| creditslower    | int(10)                           | NO   |     | 0       |                |
| stars           | tinyint(3)                        | NO   |     | 0       |                |
| color           | varchar(255)                      | NO   |     |         |                |
| icon            | varchar(255)                      | NO   |     |         |                |
| allowvisit      | tinyint(1)                        | NO   |     | 0       |                |
| allowsendpm     | tinyint(1)                        | NO   |     | 1       |                |
| allowinvite     | tinyint(1)                        | NO   |     | 0       |                |
| allowmailinvite | tinyint(1)                        | NO   |     | 0       |                |
| maxinvitenum    | tinyint(3) unsigned               | NO   |     | 0       |                |
| inviteprice     | smallint(6) unsigned              | NO   |     | 0       |                |
| maxinviteday    | smallint(6) unsigned              | NO   |     | 0       |                |  
Data in this table:  

| groupid | radminid | type    | system  | grouptitle         | creditshigher | creditslower | stars | color | icon | allowvisit | allowsendpm | allowinvite | allowmailinvite | maxinvitenum | inviteprice | maxinviteday |
|---------|----------|---------|---------|--------------------|---------------|--------------|-------|-------|------|------------|------------|------------|-----------------|--------------|-------------|--------------|
|       1 |        1 | system  | private | 管理员             |             0 |            0 |     9 |       |      |          1 |           1 |           1 |               1 |            0 |           0 |           10 |
|       2 |        2 | system  | private | 超级版主           |             0 |            0 |     8 |       |      |          1 |           1 |           1 |               1 |            0 |           0 |           10 |
|       3 |        3 | system  | private | 版主               |             0 |            0 |     7 |       |      |          1 |           1 |           1 |               1 |            0 |           0 |           10 |
|       4 |        0 | system  | private | 禁止发言           |             0 |            0 |     0 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |            0 |
|       5 |        0 | system  | private | 禁止访问           |             0 |            0 |     0 |       |      |          0 |           1 |           0 |               0 |            0 |           0 |            0 |
|       6 |        0 | system  | private | 禁止 IP            |             0 |            0 |     0 |       |      |          0 |           1 |           0 |               0 |            0 |           0 |            0 |
|       7 |        0 | system  | private | 游客               |             0 |            0 |     0 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|       8 |        0 | system  | private | 等待验证会员       |             0 |            0 |     0 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |            0 |
|       9 |        0 | member  | private | 限制会员           |      -9999999 |            0 |     0 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |            0 |
|      10 |        0 | member  | private | 新手上路           |             0 |           50 |     1 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      11 |        0 | member  | private | 注册会员           |            50 |          200 |     2 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      12 |        0 | member  | private | 中级会员           |           200 |          500 |     3 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      13 |        0 | member  | private | 高级会员           |           500 |         1000 |     4 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      14 |        0 | member  | private | 金牌会员           |          1000 |         3000 |     6 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      15 |        0 | member  | private | 论坛元老           |          3000 |      9999999 |     8 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      16 |        3 | special | private | 实习版主           |             0 |            0 |     7 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      17 |        2 | special | private | 网站编辑           |             0 |            0 |     8 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      18 |        1 | special | private | 信息监察员         |             0 |            0 |     9 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
|      19 |        3 | special | private | 审核员             |             0 |            0 |     7 |       |      |          1 |           1 |           0 |               0 |            0 |           0 |           10 |
4. What did you expect to see?
`0`

5. What did you see instead?
`ERROR 1105 (HY000): [1 strconv.ParseFloat: parsing "private": invalid syntax]`

**Comment by coocood** [comment]
Duplicated to https://github.com/pingcap/tidb/issues/1283
