### ISSUE TITLE
add unsupported mode

### ISSUE THREAD

**Issue by v01dstar** [pingcap/tidb#1257]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
Linux AMD64

3. What did you do?
SELECT @@sql_mode

4. What did you expect to see?
STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION

5. What did you see instead?
NO_ENGINE_SUBSTITUTION

**Comment by coocood** [comment]
Fixed in https://github.com/pingcap/tidb/pull/1263
