### ISSUE TITLE
`YEAR` column is not compatible with MySQL

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#12615]
## Bug Report

This PR https://github.com/pingcap/tidb/pull/9856 fixed part of the issue. But we may need more fix.

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql> create table t (y year);
Query OK, 0 rows affected (0.01 sec)

mysql> insert ignore into t values(2156);
Query OK, 1 row affected, 1 warning (0.01 sec)
```

2. What did you expect to see?
On MySQL:

```
mysql> select * from t;
+------+
| y    |
+------+
| 0000 |
+------+
1 row in set (0.00 sec)
```

3. What did you see instead?
On TIDB:

```
mysql> select * from t;
+------+
| y    |
+------+
| NULL |
+------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-459-gebc122bb4
Git Commit Hash: ebc122bb48355149a8a18963f28e8d4e85e65551
Git Branch: master
UTC Build Time: 2019-10-11 03:10:45
GoVersion: go version go1.12.9 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by lzmhhh123** [comment]
@cyliu0 Thank you for your report. Do you have any interest to fix it?

**Comment by cyliu0** [comment]
> @cyliu0 Thank you for your report. Do you have any interest to fix it?

Sure. Let me have a try.
