### ISSUE TITLE
go get -u github.com/pingcap/tidb/types/parser_driver raises error

### ISSUE THREAD

**Issue by typhoonzero** [pingcap/tidb#12648]
## Bug Report

1. What did you do?

run `go get -u github.com/pingcap/tidb/types/parser_driver` results in:

```
# github.com/pingcap/tidb/util/logutil
/go/src/github.com/pingcap/tidb/util/logutil/log.go:61:3: unknown field 'LogRotate' in struct literal of type "github.com/pingcap/log".FileLogConfig
/go/src/github.com/pingcap/tidb/util/logutil/log.go:295:4: unknown field 'LogRotate' in struct literal of type "github.com/pingcap/log".FileLogConfig
```

As mentioned in https://github.com/pingcap/parser/blob/master/parser_example_test.go#L19 importing github.com/pingcap/tidb/types/parser_driver now fails.

**Comment by rarpainting** [comment]
Please read the go.mod in tidb
```
	github.com/pingcap/log v0.0.0-20190307075452-bd41d9273596
```
```shell
> cd src/github.com/pingcap/log
> git checkout bd41d9273596
```

Recommended to turn on `GO111MODULE`

**Comment by wjhuang2016** [comment]
Can't reproduce, `LogRotate` does not appear in the code now.
