### ISSUE TITLE
unique decimal index allow duplicated entry. 

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1265]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6

2. What operating system and processor architecture are you using (`go env`)?
OS X x64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

`create table t (a decimal unique)`
`insert values ('100')`
`insert values ('1e2')`

4. What did you expect to see?
The second insert fail.

5. What did you see instead?
The second insert executed successfully.

**Comment by shenli** [comment]
Is this a bug in our decimal implementation?

**Comment by qiuyesuifeng** [comment]
@shenli  Yes, there is a bug in TiDB decimal codec, i will fix it later.

**Comment by BusyJay** [comment]
Thx, both two cases will work just fine in TiKV.

**Comment by qiuyesuifeng** [comment]
Fixed in https://github.com/pingcap/tidb/pull/1266
