### ISSUE TITLE
aesDecryptFunctionClass.getFunction get variable.BlockEncryptionMode error

### ISSUE THREAD

**Issue by mmyj** [pingcap/tidb#12743]
## Bug Report

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
go test -v -benchmem -bench=BenchmarkVectorizedBuiltinEncryptionFunc -run=BenchmarkVectorizedBuiltinEncryptionFunc -args 'builtinAesDecryptSig'
```

3. What did you see instead?

`panic: unsupported block encryption mode - `

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

300

## Mentor

- @lzmhhh123

**Comment by mmyj** [comment]
Maybe error in `expression/builtin_encryption.go:120`
```
blockMode, _ := ctx.GetSessionVars().GetSystemVar(variable.BlockEncryptionMode)
mode, exists := aesModes[strings.ToLower(blockMode)]
if !exists {
	return nil, errors.Errorf("unsupported block encryption mode - %v", blockMode)
}
```
maybe the reason is `variable.BlockEncryptionMode` is null when run benchmark test

**Comment by wjhuang2016** [comment]
I can't reproduce it in both release 4.0 and master.

**Comment by wjhuang2016** [comment]
I tested it by some commits around 16 Oct 2019, and it still can not reproduce.
