### ISSUE TITLE
replace disable-xxx with enable-xxx in configuration

### ISSUE THREAD

**Issue by lucklove** [pingcap/tidb#12748]
## Feature Request

**Is your feature request related to a problem? Please describe:**

log.disable-timestame
log.disable-error-stack

**Describe the feature you'd like:**

log.enable-timestame
log.enable-error-stack

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by ichn-hu** [comment]
I'm closing this issue because it has been fixed by #12853
