### ISSUE TITLE
syntax error found in extracting data to tidb 

### ISSUE THREAD

**Issue by yann28** [pingcap/tidb#12783]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Extracting a data to TiDB table and MySQL table with SAP Data Services(version 4.1).

2. What did you expect to see?
The data successfully inserted into TiDB table and MySQL table both

3. What did you see instead?
Failed to insert into TiDB table, but the insertion of MySQL table is successful.
The error in the tidb.log : 
>  [ERROR] [misc.go:114] **["syntax error"] [error="line 1 column 18 near \"\"test\".\"MATCHTABLE_S\" (\"ID\", \"MATCHID\") VALUES (?, ?) \" "]** [errorVerbose="line 1 column 18 nea
> r \"\"test\".\"MATCHTABLE_S\" (\"ID\", \"MATCHID\") VALUES (?, ?) \" \ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/workspace/release_tidb_3.0/go/pkg/mod/github.com/pingcap/errors@v0.11.4/errors.go:17
> 4\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/workspace/release_tidb_3.0/go/pkg/mod/github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15\ngithub.com/pingcap/parser.(*Parser).Parse\n\t/home/jenkins/work
> space/release_tidb_3.0/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190910041007-2a177b291004/yy_parser.go:139\ngithub.com/pingcap/tidb/executor.(*PrepareExec).Next\n\t/home/jenkins/workspace/release_tidb_3
> .0/go/src/github.com/pingcap/tidb/executor/prepared.go:125\ngithub.com/pingcap/tidb/session.(*session).PrepareStmt\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/session/session.g
> o:1168\ngithub.com/pingcap/tidb/server.(*TiDBContext).Prepare\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/driver_tidb.go:312\ngithub.com/pingcap/tidb/server.(*clientConn
> ).handleStmtPrepare\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/conn_stmt.go:52\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/workspace/release
> _tidb_3.0/go/src/github.com/pingcap/tidb/server/conn.go:908\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/conn.go:652\ngi
> thub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/server.go:440\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1337"] [
> stack="github.com/pingcap/tidb/util.SyntaxError\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/util/misc.go:114\ngithub.com/pingcap/tidb/executor.(*PrepareExec).Next\n\t/home/jenk
> ins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/executor/prepared.go:131\ngithub.com/pingcap/tidb/session.(*session).PrepareStmt\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pi
> ngcap/tidb/session/session.go:1168\ngithub.com/pingcap/tidb/server.(*TiDBContext).Prepare\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/driver_tidb.go:312\ngithub.com/ping
> cap/tidb/server.(*clientConn).handleStmtPrepare\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/conn_stmt.go:52\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/ho
> me/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/conn.go:908\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap
> /tidb/server/conn.go:652\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/workspace/release_tidb_3.0/go/src/github.com/pingcap/tidb/server/server.go:440"]

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
TiDB version : v3.0.4
MySQL version : 5.6.10

**Comment by nullnotnil** [comment]
I believe this might be a configuration issue. MySQL by default does not allow quotes to enclose identifiers - the SQL mode `ANSI_QUOTES` needs to be enabled. TiDB has full support for ANSI_QUOTES, it just needs to be enabled:

```sql
mysql> CREATE TABLE MATCHTABLE_S (
    ->  ID INT NOT NULL PRIMARY KEY auto_increment,
    ->  MATCHID INT NOT NULL
    -> );
Query OK, 0 rows affected (0.09 sec)

mysql> 
mysql> set sql_mode = DEFAULT;
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO "test"."MATCHTABLE_S" ("ID", "MATCHID") VALUES (1, 1);
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 18 near ""test"."MATCHTABLE_S" ("ID", "MATCHID") VALUES (1, 1)" 
mysql> set sql_mode = 'ANSI_QUOTES';
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO "test"."MATCHTABLE_S" ("ID", "MATCHID") VALUES (1, 1);
Query OK, 1 row affected (0.02 sec)

```

**Comment by nullnotnil** [comment]
I am going to close this issue now, but please feel free to reopen if you have additional questions. Thanks!
