### ISSUE TITLE
inconsistent index idx_created_at handle count 1040 isn't equal to value count 617

### ISSUE THREAD

**Issue by nick-yangg** [pingcap/tidb#12829]
Exception in tidb deleting according to condition。
```
DELETE from table WHERE created_at < '2011-06-02 13:45:00'
```
There are about 50 million pieces of data in this table, and then delete 500 pieces according to the conditions. But I made a mistake. 
```
inconsistent index idx_created_at handle count 1040 isn't equal to value count 617
```
My tidb version：

Release Version: v4.0.0-alpha-544-gae811b91c
Git Commit Hash: ae811b91c9be4cfa9777614b2bbc1ea417ddcd39
Git Branch: master
UTC Build Time: 2019-10-17 03:05:31
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by shenli** [comment]
@nick-yangg Is the error returned by the delete statement?

**Comment by jackysp** [comment]
Could you please provide your table schema of the delete statement? @nick-yangg

**Comment by nick-yangg** [comment]
> @ nick-yangg delete语句返回错误吗？

Yes, the error I returned when using delete

**Comment by nick-yangg** [comment]
> Could you please provide your table schema of the delete statement? @nick-yangg



> Could you please provide your table schema of the delete statement? @nick-yangg

I have 53 fields in this table

**Comment by jackysp** [comment]
How many expected affected rows of `DELETE from table WHERE created_at < '2011-06-02 13:45:00'` this statement? 500? 
From this error message
```
inconsistent index idx_created_at handle count 1040 isn't equal to value count 617
```
I think it at least has 617 rows.

BTW: did you use `tidb_batch_delete` or `tidb_batch_insert` when running the statment? https://pingcap.com/docs/dev/reference/configuration/tidb-server/tidb-specific-variables/#tidb_batch_delete

**Comment by jackysp** [comment]
\cc @qw4990 @tiancaiamao

**Comment by nick-yangg** [comment]
> `DELETE from table WHERE created_at < '2011-06-02 13:45:00'`该语句预期影响多少行？500？
> 从此错误消息
> 
> ```
> inconsistent index idx_created_at handle count 1040 isn't equal to value count 617
> ```
> 
> 我认为它至少有617行。
> 
> 顺便说一句：您使用过`tidb_batch_delete`或`tidb_batch_insert`在运行语句时？https://pingcap.com/docs/dev/reference/configuration/tidb-server/tidb-specific-variables/#tidb_batch_delete

**Comment by nick-yangg** [comment]
> `DELETE from table WHERE created_at < '2011-06-02 13:45:00'`该语句预期影响多少行？500？
> 从此错误消息
> 
> ```
> inconsistent index idx_created_at handle count 1040 isn't equal to value count 617
> ```
> 
> 我认为它至少有617行。
> 
> 顺便说一句：您使用过`tidb_batch_delete`或`tidb_batch_insert`在运行语句时？https://pingcap.com/docs/dev/reference/configuration/tidb-server/tidb-specific-variables/#tidb_batch_delete

I haven't run these two statements. I don't know what to send.

**Comment by nick-yangg** [comment]
> `DELETE from table WHERE created_at < '2011-06-02 13:45:00'`该语句预期影响多少行？500？
> 从此错误消息
> 
> ```
> inconsistent index idx_created_at handle count 1040 isn't equal to value count 617
> ```
> 
> 我认为它至少有617行。
> 
> 顺便说一句：您使用过`tidb_batch_delete`或`tidb_batch_insert`在运行语句时？https://pingcap.com/docs/dev/reference/configuration/tidb-server/tidb-specific-variables/#tidb_batch_delete

I haven't run these two statements. I don't know what to send.

**Comment by shenli** [comment]
May I have the type of created_at and the definition of the index on this column?

**Comment by nick-yangg** [comment]
@shenli Yes, I created the index

**Comment by shenli** [comment]
@nick-yangg If it is convenient for you, could you send the result of `show create table t;` to `shenli@pingcap.com`? Thanks!

**Comment by jackysp** [comment]
Could you please provide your TiKV version? @nick-yangg 
`tikv-server --version`

**Comment by jackysp** [comment]
Friendly ping @nick-yangg .

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
