### ISSUE TITLE
Make evaluator continue to evaluate even encountered an error.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1283]
When there is Truncated error, the evaluator should continue the evaluation, and return a result that computed from truncated values.

For select statement, Truncated error should be ignored, for INSERT, UPDATE and DELETE statement, Truncated error should stop the execution if `sql_mode` is strict. should not stop execution and return warning if `sql_mode` is not strict.

**Comment by shenli** [comment]
So we can add a variable in session to indicate if we should continue or fail when we encounter an truncated error?

**Comment by coocood** [comment]
Yes, there is already a `StrictSQLMode` variable in `sessionctx/variable/SessionVars` struct.
But it is only used in check default value and converting input value to column type.
