### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by moguding** [pingcap/tidb#1287]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by moguding** [comment]
go version 1.6
system mac
when i was make tidb 

pingcap/tidb/parser/yy_parser.go:71: undefined: NewLexer
pingcap/tidb/parser/yy_parser.go:73: undefined: yyParse

**Comment by shenli** [comment]
@moguding Thanks for your report!
Can you run "make parser" and show me the output? If it success, please try to make again.

**Comment by moguding** [comment]
@shenli  do as you say,it's ok. ths!

**Comment by shenli** [comment]
@moguding Great! Please feel free to contact us when you meet any problem with TiDB/TiKV. Thanks!
