### ISSUE TITLE
TiDB Grafana PD ROLE No Value

### ISSUE THREAD

**Issue by centosvnc** [pingcap/tidb#12871]
![Screenshot (22)](https://user-images.githubusercontent.com/56868764/67272653-cda2ef80-f471-11e9-8f8d-db007a181143.png)

I deploy a TiDB cluster using tidb-docker-compose. But On Grafana PD Role No Value.
also,
curl http://127.0.0.1:2379/pd/api/v1/stores
curl: (7) Failed connect to 127.0.0.1:2379; Connection refused

But Everything is Working Fine!!

Can you Guys please check the docker-swarm.yml pd0 never able to connect.. something misconfigured.
please don't neglect docker and compose.
It's easier to learn and deploy infra than Kubernetes
Lot's of Developer Love Docker!!!!!!!!
Thanks Team

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to reopen it if you need any further help.
