### ISSUE TITLE
spark-2.3.2-bin-hadoop2.7.tgz download error

### ISSUE THREAD

**Issue by nick-yangg** [pingcap/tidb#12918]
I have a download error using ansible, and I have the same problem when I download it separately using a browser.

**Comment by nick-yangg** [comment]
![image](https://user-images.githubusercontent.com/55170104/67473542-770dff00-f685-11e9-9f68-53ba84c36dfc.png)

**Comment by liubo0127** [comment]
Sorry, this error due to some problems with the data source, and it has now returned to normal. Please try again.

**Comment by SunRunAway** [comment]
Hi, @nick-yangg 
I've closed this issue right now, feel free to reopen it if you have any similar problem.
