### ISSUE TITLE
Why ExecStmt handleNoDelayExecutor do not return a sqlexec.RecordSet ?

### ISSUE THREAD

**Issue by tumayun** [pingcap/tidb#12921]
## General Question

为何 ExecStmt handleNoDelayExecutor 方法没有返回 sqlexec.RecordSet 呢？
该方法所有 return 返回的第一个参数都是 nil

**Comment by XuHuaiyu** [comment]
If an executor is no-delay-executor, it will [be executed immediately](https://github.com/pingcap/tidb/blob/master/executor/adapter.go#L528).
