### ISSUE TITLE
Refactor evaluator

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1293]
In our current evaluator, every operation needs to handle computation and also type conversion, which makes our code more complex. And to support sql_mode, we have to treat truncated error differently than other errors. As truncated errors mostly occur in conversion, It's hard to do in our current implementation as we need to change many places.

In new evaluator, every operation only handles computation except for `convert` operation.
The operands in an operation are of the same type. If operands in an operation are of different types, we rewrite the expression by inserting a `convert` function.

After this refactor, our evaluator would be much simpler, and it would be much easier to implement more functions in both TiDB and TiKV coprocessor.

**Comment by c4pt0r** [comment]
Any updates?
