### ISSUE TITLE
change the default value of `mem-quota-query`

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#12937]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The default value of `mem-quota-query` is 32GB now. 
In TiDB 4.0 most executors which consumes memory before will use temporary disk when memory usage exceeds `mem-quota-query`,  so that it's too large.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SunRunAway** [comment]
About the memory limit of a query


### TiDB:

https://github.com/pingcap/tidb/blob/1f922559dfda3655a8f11fba5921c743c4ebfb8b/config/config.toml.example#L34-L38

The default is 32GB, which controls the entire query. When a query exceeds this limit, the operator will be placed on the market. Only hash join is currently controlled.


### greenpulm:

https://gpdb.docs.pivotal.io/43250/ref_guide/config_params/guc-list.html#statement_mem

128MB, limits the entire query, the effect is similar to the current implementation of TiDB.

### cockroachdb:

https://www.cockroachlabs.com/docs/stable/cluster-settings.html


sql.distsql.temp_storage.joins boolean true set to true to enable use of disk for distributed sql joins
sql.distsql.temp_storage.sorts boolean true set to true to enable use of disk for distributed sql sorts
sql.distsql.temp_storage.workmem byte size 64 MiB maximum amount of memory in bytes a processor can use before falling back to temp storage


64MB, limit a processor(executor). Controls only `join` and `sort`.


### mysql:

https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_join_buffer_size

256KB, limits an executor. Controls only `join`.


### postgres:

https://www.postgresql.org/docs/9.3/runtime-config-resource.html#RUNTIME-CONFIG-RESOURCE-MEMORY


work_mem (integer)

Specify the amount of memory to be used by internal sort operations and hash tables before writing to temporary disk files. The value defaults to one megabyte (1MB). Note that for a complex query, several sort or hash operations might be running in parallel; each operation will be allowed to use as much memory as this value specifies before it starts to write data into temporary files. Also, several running sessions could be doing such operations concurrently. Therefore, the total memory used could be many times the value of work_mem ; it is necessary to keep this fact in mind when choosing the value. Sort operations are used for ORDER BY, DISTINCT, and merge joins. Hash tables are used in hash joins, hash-based aggregation, and hash-based processing of IN subqueries .


1MB, limits an executor. Controls only `join` and `sort`.

**Comment by tsthght** [comment]
let me fix it

**Comment by SunRunAway** [comment]
We may change the default value to 1GB.

**Comment by djshow832** [comment]
It's modified in https://github.com/pingcap/tidb/pull/14951
