### ISSUE TITLE
Does tidb client have java api?

### ISSUE THREAD

**Issue by litao-buptsse** [pingcap/tidb#1296]
I have a java application and want to use tidb as a local sql storage. Does it have java client api or supporting jdbc interface?

**Comment by shenli** [comment]
@litao-buptsse You can use any java mysql client to connect to TiDB.

**Comment by litao-buptsse** [comment]
@shenli :+1: Thanks, I will have a try

**Comment by shenli** [comment]
If you meet any problem, feel free to raise an issue or submit a PR.  @litao-buptsse
