### ISSUE TITLE
Improve the performance of `CREATE INDEX` statement

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#12963]
## Description
In TiDB, `CREATE INDEX`(or `ALTER TABLE ... ADD INDEX`) is a DDL statement that is frequently used, some existing [benchmarks](https://pingcap.com/docs-cn/v3.0/benchmark/add-index-with-load/) has been done on parameters `tidb_ddl_reorg_worker_cnt`, `tidb_ddl_reorg_batch_size`, alone with online workloads. We aim to improve the performance of this DDL statement.

Some of the possible ideas are:
* Before start inserting index data, pre-split index regions with the similar approach as `SPLIT TABLE ...  INDEX` [statement](https://pingcap.com/docs/v3.0/reference/sql/statements/split-region/), the number of index region distribution can be approximated from [table statistics](https://pingcap.github.io/docs/v3.0/reference/performance/statistics/). 
* Automatically adjust the value of `tidb_ddl_reorg_worker_cnt` and `tidb_ddl_reorg_worker_cnt` according to the real-time online workloads. For example, set the large value when TiDB cluster is ratively idle, decrease their values when the load is heavy.
* Push more operations in `CREATE INDEX` down to TiKV as a new Coprocessor task, for example, some work in [index.Create()](https://github.com/pingcap/tidb/blob/5590f42e904b2a991cd9d55f05b53342baa8529c/table/tables/index.go#L195) function can be done in TiKV side. 

## Difficulty
* Medium
## Score 
* 3000
## Mentor(s)
* @crazycs520
* @lonng
## Recommended Skills
* Protocol buffer
* TiDB and TiKV architecture
* Go and Rust language

**Comment by Defined2014** [comment]
The DDL Architecture changed a lot and we already support fast ddl, so close this issue. If you still have some questions, feel free to reopen it.
