### ISSUE TITLE
unnecessary code `fmt.Println` on branch release-2.1

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#12968]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Caused by https://github.com/pingcap/tidb/blob/8e80122af807c402cc7ca26adde4d14e9fa7f9b9/expression/builtin_miscellaneous.go#L141

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
mysql> select sleep(1);
```

2. What did you expect to see?
Nothing weird happened.

3. What did you see instead?
On the tidb-server console, there is so much output as below:
================
================
================
================
================
================
================
================
================
================
================
================
================
================
================
================

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
tidb_version(): Release Version: v2.1.17-41-g8e80122af
Git Commit Hash: 8e80122af807c402cc7ca26adde4d14e9fa7f9b9
Git Branch: HEAD
UTC Build Time: 2019-10-28 08:06:58
GoVersion: go version go1.13.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by SunRunAway** [comment]
Fixed in #12968
