### ISSUE TITLE
PCP-4: Improve the performance of `WindowExec` by using multi-thread hash grouping

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#12966]
## Description

TiDB implements window function feature compatible with mysql(https://dev.mysql.com/doc/refman/8.0/en/window-functions.html). The performance has much space to improve.

Considering using a multi-thread hash grouping, to run each window partition in parallel.  

Goals:

* Use a multi-thread hash grouping, to run each window partition in parallel. 

## Difficulty

* Medium

## Score 

* 2100

## Mentor(s)

* @SunRunAway

## Recommended Skills

* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by SunRunAway** [comment]
@pingyu Do you have any ideas or plans to do this PCP, we can make a meeting to discuss it.

**Comment by pingyu** [comment]
@SunRunAway 
That's great !
I am working on it, and writing a document of my plans. Talk to you later~
