### ISSUE TITLE
PCP-2: Improve the performance of `groupChecker` by vectorization

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#12976]
## Description

The `groupChecker` is used in `StreamAgg` and `Window` executors to check if a new group appear. Now the `groupChecker` compares input data row by row to check whether it meet a new group, which can be optimized.

We can vectorize this processing to get a better performance, for example: comparing one column once.

## Difficulty

* Medium

## Score 

* 1200

## Mentor(s)

* @qw4990
* @SunRunAway

## Recommended Skills

* Golang Profiling

**Comment by ekalinin** [comment]
It looks like this Issue is fixed by #12903, right?

**Comment by SunRunAway** [comment]
> It looks like this Issue is fixed by #12903, right?

Yes, fixed by #12903 and #13852, thanks for your reminding.
