### ISSUE TITLE
Implement PointGet for partitioned table

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#12977]
## Description

The PointGet request is much faster than normal requests because it bypasses the optimizer. However, PointGet is not implemented on partitioned tables because partition pruning is required to locate the partition,  and  partition pruning is implemented in the optimizer.

Find a way to implement PointGet for partitioned table.
You may start from the `locatePartition` function in table/tables/partitionedTable, or you may calculate point range to decide which partition the PointGet request belongs to.

## Difficulty

* Medium

## Score 

* 1200

## Mentor(s)

* @tiancaiamao

## Recommended Skills

* Golang
* TiDB architecture

**Comment by qw4990** [comment]
Close since it is finished by https://github.com/pingcap/tidb/issues/24476.
