### ISSUE TITLE
omit the compute process when where clause is ` xxx * 0`

### ISSUE THREAD

**Issue by H-ZeX** [pingcap/tidb#12994]
## Feature Request

**Is your feature request related to a problem? Please describe:**
No.

**Describe the feature you'd like:**
The sql such as this, its where clause has `* 0`, then we can return a empty set directly, without computing.
```sql
SELECT '1982-11-28 14:24:44.008377' + `col_datetime` AS field1
FROM `table1000_int_autoinc`
WHERE (- (((`col_bigint_unsigned` DIV -8747960801190477824) DIV `col_decimal`) MOD
          (`col_varchar_1` + `col_varchar_1_key`))) * 0 /* QNO 792 CON_ID 161 */ ;

```

**Comment by SunRunAway** [comment]
@H-ZeX 
Good idea, will you have a try?

**Comment by H-ZeX** [comment]
@SunRunAway Such sql will rarely appear in real code, and impl this feature will make normal sql slow. So this feature is not necessary.
