### ISSUE TITLE
Auto_increment is not compatible with MySQL

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#13032]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t2(a int auto_increment, b int key);
```

2. What did you expect to see?
mysql 8.0.17
![image](https://user-images.githubusercontent.com/5506767/67846614-79b49c80-fb3c-11e9-945b-fc96682fcd3c.png)

3. What did you see instead?
tidb
![image](https://user-images.githubusercontent.com/5506767/67846534-5853b080-fb3c-11e9-8720-9b423cb47ef9.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v2.1.17-41-g8e80122af
Git Commit Hash: 8e80122af807c402cc7ca26adde4d14e9fa7f9b9
Git Branch: HEAD
UTC Build Time: 2019-10-29 02:19:18
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by SunRunAway** [comment]
@bb7133 PTAL

**Comment by zimulala** [comment]
In MySQL 5.7.20, this SQL also reports errors.
<img width="848" alt="Screen Shot 2020-02-12 at 11 10 29" src="https://user-images.githubusercontent.com/4242506/74299651-54186f80-4d88-11ea-84a7-ccc13ecdd96e.png">

**Comment by Rustin-Liu** [comment]
I am working on it.

**Comment by zimulala** [comment]
@Rustin-Liu  
Thanks for your PR.
