### ISSUE TITLE
Test if TiDB can work with spark.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1307]
Spark has MySQL connector, TiDB should works since TiDB compatible with MySQL.  But we need to do some tests.

**Comment by shenli** [comment]
Good idea! I will do  this.

**Comment by shenli** [comment]
@ngaut TiDB works fine with Spark through jdbc.
I will compare the performance of TiDB and TiDB+Spark.

**Comment by ngaut** [comment]
Cool

**Comment by kobebry80** [comment]
@shenli 
hello, is there any results of comparing the performance TiDB and TiDB+Spark ?

**Comment by shenli** [comment]
@kobebry80 For small or medium size data set, TiDB beats Spark. For big data set or extremely sql, Spark is better.

**Comment by kobebry80** [comment]
@shenli 
thanks a lot!could you show me the the detail data of the performance TiDB?
