### ISSUE TITLE
Admin checksum while region split/merge

### ISSUE THREAD

**Issue by NingLin-P** [pingcap/tidb#13077]
## General Question

When TiDB push down admin checksum request to TiKV, if a region are happen to be splitted or merged during TiKV handle these request, will TiDB detect that happen and resend the request to TiKV to avoid re-calculate or miss-calculate some key range?

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to reopen it if you need any further help.
