### ISSUE TITLE
wrong result when use `REGEX` function with `CHARSET latin1 COLLATE latin1_general_cs`

### ISSUE THREAD

**Issue by Deardrops** [pingcap/tidb#13137]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
create table t (c CHAR(10) CHARSET latin1 COLLATE latin1_general_cs);
insert into t value('A');
select c, c REGEXP 'a' from t;
```

or one line:
```sql
select CONVERT('A' USING latin1) COLLATE latin1_general_cs REGEXP 'a';
```
2. What did you expect to see?

![image](https://user-images.githubusercontent.com/9463871/68176053-4f406480-ffbe-11e9-94b0-f805d54e8f85.png)

3. What did you see instead?

![image](https://user-images.githubusercontent.com/9463871/68176064-58c9cc80-ffbe-11e9-85b3-c0afab9aeaa7.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v4.0.0-alpha-693-gada724a2a

**Comment by wjhuang2016** [comment]
Fixed by https://github.com/pingcap/tidb/pull/17255
