### ISSUE TITLE
Disk-based merge join.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#13256]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If merge join meets lots of rows with same join key, it may consume lots of memory.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by ichn-hu** [comment]
Done by https://github.com/pingcap/tidb/pull/13946, I am closing it.
