### ISSUE TITLE
Can't use Chunk encode type when streaming is enable.

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#13293]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
CREATE TABLE tt(a INT, b INT, c INT, d INT);
INSERT INTO tt VALUES (1,1,1,1), (2,2,4,2), (3,3,9,3);

SELECT sum(c/d)  FROM tt  group by a, b;
```
Enable-streaming is enable but the hashagg can't push down, then we should use chunk encode type but got default format.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
master

**Comment by XuHuaiyu** [comment]
Not a bug.
I'll convert this to feature-request.
