### ISSUE TITLE
on tidb docker hub page images not loading

### ISSUE THREAD

**Issue by jude-zhu** [pingcap/tidb#13361]
both on pincap/tikv and pincap/tidb docker hub page, the images linked URL are 404.

![1](https://user-images.githubusercontent.com/51590253/68575742-b458f600-04a7-11ea-9d42-8fd09a11fcad.jpg)

**Comment by nullnotnil** [comment]
It's the following URLs not loading:
https://hub.docker.com/r/pingcap/docs/logo_with_text.png
https://hub.docker.com/r/pingcap/images/tikv_stack.png

I'll ping an admin to take a look.

**Comment by n0vad3v** [comment]
Thanks for you feedback, it's now been fixed.

**Comment by nullnotnil** [comment]
Thanks! Closing this issue.
