### ISSUE TITLE
Designing statement summary tables in TiDB

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#13426]
## General Question

Before asking a question, make sure you have:
For now, we have a statement summary table `events_statements_summary_by_digest`, and I'm adding more fields to it. But here are the problems: 
 - Fields are too many, making it hard to analyze.
 - Some statements don't need some of the fields. For example, SELECT don't need commit details, INSERT don't need CopTask details.

So we have two proposals:
1. Split the table into smaller tables, e.g. 3 tables, each corresponding to SELECT / other DML / other SQL. Then you can join them together to see the whole summary.
2. Just use one big table, and create separate views for each goal.

Which is better? Or is there any better idea?

For reference, tables are not split for each SQL type in MySQL and Oracle.

**Comment by AndrewDi** [comment]
I perfer the second one, view is good to complete this job.

**Comment by tisonkun** [comment]
@djshow832 why do you close this issue? Is there a PR fix it?
