### ISSUE TITLE
Alter table statements are not parsed properly 

### ISSUE THREAD

**Issue by parthibd** [pingcap/tidb#13424]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```ALTER TABLE app1.notification ADD CONSTRAINT fk_notification_id FOREIGN KEY (calendarid) REFERENCES app1.calendars (id) ON UPDATE RESTRICT ON DELETE SET NULL .``` 

I believe this fixes the problem .

https://github.com/pingcap/parser/pull/548

Since this is not cherry picked into the v3.0.1 , hence the error .

2. What did you expect to see?

To see it get parsed knowing foreign key is not supported because I have a long list of Liquibase migrations that I can't ignore out .

3. What did you see instead?

``` ERROR: Change Set changelog-4.0-clean::changelog-4.0-clean::author failed.  Error: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 159 near "UPDATE RESTRICT ON DELETE SET NULL"  [Failed SQL: (1064) ALTER TABLE app1.notification ADD CONSTRAINT fk_notification_id FOREIGN KEY (calendarid) REFERENCES app1.calendars (id) ON UPDATE RESTRICT ON DELETE SET NULL]```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v3.0.1

**Comment by tangenta** [comment]
Related issue: pingcap/parser#280

**Comment by parthibd** [comment]
Will this be fixed in the next minor release ?

**Comment by tangenta** [comment]
@parthibd Sure.

**Comment by parthibd** [comment]
This issue was fixed in v3.0.6 . Thank you so much guys! I am closing this now .
