### ISSUE TITLE
Delete a TiKV node and add it back. The node cannot be seen in the cluster.

### ISSUE THREAD

**Issue by zhuww0236** [pingcap/tidb#13433]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
[tikv_servers]
10.197.163.35
10.197.163.36
10.197.163.37

Delete a TiKV node 10.197.163.37:
https://pingcap.com/docs-cn/stable/how-to/scale/with-ansible/   缩容 TiKV 节点

Add 10.197.163.37 back:
https://pingcap.com/docs-cn/stable/how-to/scale/with-ansible/   扩容 TiDB/TiKV 节点

 The node 10.197.163.37 cannot be seen in the cluster:
http://10.197.163.35:2379/pd/api/v1/stores

2. What did you expect to see?
Delete a TiKV node that is not seen in the cluster. 
After you add the node back, you can see it in the cluster.

3. What did you see instead?
Delete a TiKV node that is not seen in the cluster. 
After adding the node back, the node is still not visible in the cluster.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 ./tidb-server -V
Release Version: v4.0.0-alpha-842-g3ca8661b5

**Comment by disksing** [comment]
Hi, it is designed behaviour. You need to remove tikv data before rejoining into the cluster.

**Comment by tisonkun** [comment]
closed as wontfix
