### ISSUE TITLE
Is there a complete solution to the problem of autoincrement primary keys?

### ISSUE THREAD

**Issue by Bruce2jiang** [pingcap/tidb#13437]
Is there a complete solution to the problem of autoincrement primary keys?

**Comment by tangenta** [comment]
What problem do you actually mean?

**Comment by Bruce2jiang** [comment]
Is there a completion solution for autoincrement primary key generating hot spots

**Comment by tangenta** [comment]
There is an experimental [new feature](#13127) `auto_shard_bits` is being developed.
However, it's unlikely to be merged until release-4.0. For now, you can use `auto_increment` and `unique` without specifying the primary key and set the table option `shard_row_id_bits` to ease the hot spot.
