### ISSUE TITLE
3.0 or about to release 4.0, TiDB for large table JOIN query, TiDB is optimized, can you talk about how to disperse computing tasks in detail?

### ISSUE THREAD

**Issue by Bruce2jiang** [pingcap/tidb#13434]
3.0 or about to release 4.0, TiDB for large table JOIN query, TiDB is optimized, can you talk about how to disperse computing tasks in detail?

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to reopen it if you need any further help.
