### ISSUE TITLE
Unify log library

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#13459]
Currently, there are a few different kinds of log library are used.  Things found in go.sum.

Please take a look.

github.com/chzyer/logex v1.1.10/go.mod h1:+Ywpsq7O8HXn0nuIou7OrIPyXbp3wmkHB+jjWRnGsAI=
github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b h1:VKtxabqXZkF25pY9ekfRL6a582T4P37/31XEstQ5p58=
github.com/golang/glog v0.0.0-20160126235308-23def4e6c14b/go.mod h1:SBH7ygxi8pfUlaOkMMuAQtPIUF8ecWP5IEl/CR7VP2Q=
github.com/pingcap/log v0.0.0-20190715063458-479153f07ebd/go.mod h1:WpHUKhNZ18v116SvGrmjkA9CBhYmuUTKL+p8JC9ANEw=
github.com/pingcap/log v0.0.0-20191012051959-b742a5d432e9 h1:AJD9pZYm72vMgPcQDww9rkZ1DnWfl0pXV3BOWlkYIjA=
github.com/pingcap/log v0.0.0-20191012051959-b742a5d432e9/go.mod h1:4rbK1p9ILyIfb6hU7OG2CiWSqMXnp3JMbiaVJ6mvoY8=
github.com/sirupsen/logrus v1.0.5/go.mod h1:pMByvHTf9Beacp5x1UXfOR9xyW/9antXMhjMPG0dEzc=
github.com/sirupsen/logrus v1.2.0 h1:juTguoYk5qI21pwyTXY3B3Y5cOTH3ZUyZCg1v/mihuo=
github.com/sirupsen/logrus v1.2.0/go.mod h1:LxeOpSwHxABJmUn/MG1IvRgCAasNZTLOkJPxbbu5VWo=
gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2/go.mod h1:Xk6kEKp8OKb+X14hQBKWaSkCsqBpgog8nAV2xsGOxlo=

**Comment by siddontang** [comment]
another log 

```
go.uber.org/zap v1.9.1/go.mod h1:vwi/ZaCAaUcBkycHslxD9B2zi4UTXhF60s6SWpuDF0Q=
go.uber.org/zap v1.10.0 h1:ORx85nbTijNz8ljznvCMR1ZBIPKFn3jQrag10X2AsuM=
go.uber.org/zap v1.10.0/go.mod h1:vwi/ZaCAaUcBkycHslxD9B2zi4UTXhF60s6SWpuDF0Q=
```

**Comment by hsqlu** [comment]
Which one should we use? The latest github.com/pingcap/log?

**Comment by ngaut** [comment]
Yes. @hsqlu

**Comment by kennytm** [comment]
The `go.sum` contains entries of removed modules, so appearing in `go.sum` doesn't mean it is really used. I'm not sure the mechanism how `go mod tidy` GC the entries, but if only the `*/go.mod` entry remains (e.g. logex) it is definitely not used. Judging from `go mod why`, 

* **github.com/golang/glog** v0.0.0-20160126235308-23def4e6c14b<br>— needed by `google.golang.org/grpc`
* **github.com/pingcap/log** v0.0.0-20191012051959-b742a5d432e9<br>— (the replacement target)
* [ ] **github.com/sirupsen/logrus** v1.2.0<br>— still imported in several places: https://github.com/pingcap/tidb/search?q=logrus&unscoped_q=logrus
* **go.uber.org/zap** v1.12.0<br>— needed by `github.com/pingcap/log`

The only realistic unification is removing logrus. We can't remove glog unless we convince gRPC to abandon glog and switch to zap 🙃.
