### ISSUE TITLE
Could not commit JDBC transaction; nested exception is java.sql.SQLException: Write conflict, txnStartTS=412540805026152457, conflictStartTS=412540805026152455, conflictCommitTS=412540808827240449, key={tableID=230, indexID=1, indexValues={4000007901, }} primary={tableID=226, indexID=1, indexValues={3563484, }} [try again later]=> 

### ISSUE THREAD

**Issue by Bruce2jiang** [pingcap/tidb#13462]
Could not commit JDBC transaction; nested exception is java.sql.SQLException: Write conflict, txnStartTS=412540805026152457, conflictStartTS=412540805026152455, conflictCommitTS=412540808827240449, key={tableID=230, indexID=1, indexValues={4000007901, }} primary={tableID=226, indexID=1, indexValues={3563484, }} [try again later]=>

**Comment by whalezhao** [comment]
我也遇到了这个问题,请问是什么原因导致的.???

**Comment by CaiusBallad** [comment]
同问最后关闭问题的原因
