### ISSUE TITLE
Possible performance issue when partition number is large

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tidb#13485]
https://github.com/pingcap/tidb/blob/master/planner/core/logical_plan_builder.go#L2456 will iterator all partitions for each statement, if the statement is simple and the partition number is  large like 1024 the cost here  is not trivial.

**Comment by nullnotnil** [comment]
Should this be closed as a duplicate of https://github.com/pingcap/tidb/issues/18548 ?

**Comment by qw4990** [comment]
> Should this be closed as a duplicate of #18548 ?

Yes, this issue is duplicated with https://github.com/pingcap/tidb/issues/18548;
