### ISSUE TITLE
In the same tidb cluster, how to import DDL and DML data from one database into another database

### ISSUE THREAD

**Issue by Bruce2jiang** [pingcap/tidb#13514]
In the same tidb cluster, how to import DDL and DML data from one database into another database

**Comment by zz-jason** [comment]
I'm Sorry I don't get your point. Did you mean to copy all the table from one database to another database, and these 2 databases are in the same TiDB cluster?

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
