### ISSUE TITLE
"Invalid time format" caused by time zone issue

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#13605]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I am in the `-8:00` time zone.
```
➜  work date -R
Tue, 19 Nov 2019 15:51:45 -0800
```
With the following operation, I meet the invalid time format issue.
```
use test;
set @@time_zone = '+0:00';
SELECT @@global.time_zone, @@session.time_zone;
create table t (ts timestamp);
insert into t values ("2018-03-11 02:00:16");
```

2. What did you expect to see?
```
Query OK, 1 row affected (0.01 sec)
```

3. What did you see instead?
```
ERROR 1292 (22007): invalid time format: '{2018 3 11 2 0 16 0}'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
| Release Version: v4.0.0-alpha-921-g77faf6466-dirty
Git Commit Hash: 77faf64668213114ea33f565c84dde52a5359667
Git Branch: master
UTC Build Time: 2019-11-19 11:23:59
GoVersion: go version go1.13.4 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by bb7133** [comment]
This bug is related to the Daylight Saving Times and we will fix it soon.
