### ISSUE TITLE
`desc table` is not compatible with MySQL

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#13635]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
According to https://dev.mysql.com/doc/refman/8.0/en/show-columns.html
> A UNIQUE index may be displayed as PRI if it cannot contain NULL values and there is no PRIMARY KEY in the table.

2. What did you expect to see?
On MySQL
```
mysql> create table t (a int not null, b int not null, c int not null);
Query OK, 0 rows affected (0.02 sec)

mysql> alter table t add unique index i_ab(a, b);
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0

mysql> desc t;
+-------+---------+------+-----+---------+-------+
| Field | Type    | Null | Key | Default | Extra |
+-------+---------+------+-----+---------+-------+
| a     | int(11) | NO   | PRI | NULL    |       |
| b     | int(11) | NO   | PRI | NULL    |       |
| c     | int(11) | NO   |     | NULL    |       |
+-------+---------+------+-----+---------+-------+
3 rows in set (0.01 sec)
```

3. What did you see instead?
On TiDB, run TiDB with config file contains `alter-primary-key = true`
```
mysql> create table t (a int not null, b int not null, c int not null);
Query OK, 0 rows affected (0.01 sec)

mysql> alter table t add unique index i_ab(a, b);
Query OK, 0 rows affected (0.03 sec)

mysql> desc t;
+-------+---------+------+------+---------+-------+
| Field | Type    | Null | Key  | Default | Extra |
+-------+---------+------+------+---------+-------+
| a     | int(11) | NO   | MUL  | NULL    |       |
| b     | int(11) | NO   |      | NULL    |       |
| c     | int(11) | NO   |      | NULL    |       |
+-------+---------+------+------+---------+-------+
3 rows in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-934-ga08ead157-dirty
Git Commit Hash: a08ead1576b92f5873fb0f44d81fa3963add7d31
Git Branch: master
UTC Build Time: 2019-11-20 08:42:37
GoVersion: go version go1.13.1 darwin/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by nullnotnil** [comment]
This behavior makes sense for MySQL, since InnoDB does actually promote the first not-null index to a primary key, in the absence of a defined primary key. TiDB instead creates a hidden primary key in this instance (and other instances, such as when the primary key is non-numeric). If you remove the `NOT NULL` attribute, MySQL will not do this - and you can see the same output.

I think this behavior makes sense for TiDB, so I think we should close this as "won't fix". But I will leave this open for a bit to collect feedback. Thanks!

**Comment by tisonkun** [comment]
closed as wontfix
