### ISSUE TITLE
Replace gometalinter with golangci-lint

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#13675]
[`gometalinter`](https://github.com/alecthomas/gometalinter) is DEPRECATED and the project will be archived on 2019-04-07. See [#590](https://github.com/alecthomas/gometalinter/issues/590) for discussion.

The maintainer of  `gometalinter` suggests switching to [golangci-lint](https://github.com/golangci/golangci-lint).

**Comment by xiekeyi98** [comment]
This is a PR: https://github.com/pingcap/tidb/pull/12264
