### ISSUE TITLE
use the time zone variable instead of local time

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#13791]
## Bug Report

There are 5 places in the code base that use `gotime.Local`. If any of these is correct, we can add a comment explaining why. If they are not correct, they should be switched to reference the time zone setting. A user has already contributed a PR to fix one instance: https://github.com/pingcap/tidb/pull/13752

@shenli this is a possible source of user reporte timezone issues.

**Comment by Rustin-Liu** [comment]
I will fix it one by one. #13626

**Comment by gregwebs** [comment]
duplicate of #13626
