### ISSUE TITLE
seems builtin greatest not implement

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#1380]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

```sql
CREATE TABLE t1 (a INT PRIMARY KEY AUTO_INCREMENT);

INSERT INTO t1 VALUES (), (), ();

SELECT 1 AS c1
FROM t1
ORDER BY (
  SELECT 1 AS c2
  FROM t1
  GROUP BY GREATEST(LAST_INSERT_ID(), t1.a) ASC
  LIMIT 1);
```

4. What did you expect to see?

```
c1
1
1
1
```

5. What did you see instead?

ERROR 1105 (HY000): line 6 column 20 near "("

**Comment by shenli** [comment]
Yes, it is not implemented.
