### ISSUE TITLE
No Apache License found in repository

### ISSUE THREAD

**Issue by jserv** [pingcap/tidb#1382]
File [README.md](https://github.com/pingcap/tidb/blob/master/README.md) mentioned:
> TiDB is under the Apache 2.0 license. See the LICENSE file for details.

However, the link to "LICENSE file" is not available at the moment.

**Comment by shenli** [comment]
@jserv Thanks for your report!
We have Apache license in each source file. But we forget to put it into LICENSES dir. I will fix it.

**Comment by jserv** [comment]
@shenli, At present, there are only two BSD-style license files:
* QL-LICENSE
* STRUTIL-LICENSE

No file containing Apache License 2.0 with explicit copyright ownership can be accessed in directory `LICENSES` though.

**Comment by shenli** [comment]
@jserv The apache-2.0 license is in the root directory.  See: https://github.com/pingcap/tidb/blob/master/LICENSE
LICENSES is use to store the license of the projects we used in TiDB.

**Comment by jserv** [comment]
@shenli, Thanks for clarifying.
