### ISSUE TITLE
When there are a lot of users in a cluster, the authentication performance would be not good

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#13830]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We should pay attention to the performance of TiDB when there are many users (for example 10k users). MySQL has this feature: https://bugs.mysql.com/bug.php?id=90244

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nullnotnil** [comment]
This has been fixed. TiDB now uses a hash table (map) as well.
