### ISSUE TITLE
[help wanted] Provide binary distribution package

### ISSUE THREAD

**Issue by c4pt0r** [pingcap/tidb#1385]
Since we've already launched the beta, there must be some guys who want to have a try, if we provide a binary distro and some handy scripts, that would be easier for others to use.

**Comment by c4pt0r** [comment]
1. Linux / OS X binary package, tar.gz
2. Debian package .deb, support apt-get
3. Docker image

**Comment by shenli** [comment]
Should also consider rpm package for Centos and Fedora.

**Comment by overvenus** [comment]
Hi, I have wrote a Makefile which packs tidb and ticlient into one deb file. Although, the deb file works fine in my machine(Ubuntu 14LTS, AMD64), I am not sure if this works in yours.

You can get it via apt-get

```sh
sudo apt-add-repository ppa:overvenus/tidb
sudo apt-get update
sudo apt-get install tidb
```

or download it directly from [link](https://launchpad.net/~overvenus/+archive/ubuntu/tidb/+build/10430189/+files/tidb_0.0.1~beta20160630-1_amd64.deb)

Check out my work at [debian-package](https://github.com/overvenus/tidb/tree/debian-package/dist)
I am not a debian expert, so it did not follow [Chapter 6. Best Packaging Practices](https://www.debian.org/doc/manuals/developers-reference/best-pkging-practices.html) 100%. If you think it ok, then I'm glad to send a PR. : )

**Comment by shenli** [comment]
@overvenus Great to hear that! I will test it on my machine.

**Comment by Librazy** [comment]
An AUR package for Arch Linux using binary package:
https://aur.archlinux.org/packages/tidb-bin/
