### ISSUE TITLE
CONTRIBUTORS.md: link failed

### ISSUE THREAD

**Issue by tptpp** [pingcap/tidb#13861]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

  nil

2. What did you expect to see?

`Contributors` should be linked to:

https://github.com/pingcap/community/blob/master/architecture/contributor-list.md#tidb-contributors

after this commit:https://github.com/pingcap/community/commit/0ff4a855977b3b5fdd9045b1df6c2c1348240dac#diff-81adb8eea5703c97ab1a45ec3b989e4d

3. What did you see instead?

`Contributors` is now linked to:

https://github.com/pingcap/community/blob/master/contributors#tidb-contributors

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

  nil

**Comment by bb7133** [comment]
Close this issue since it is fixed by #13862, thanks!
