### ISSUE TITLE
Memory leak after executing large transaction

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#13883]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I'm testing the large transaction code in the master branch.
I find that after executing a large transaction, there is still quite a lot of memory used by TiDB.
Even I close the connection, the memory can't be released.

![image](https://user-images.githubusercontent.com/1420062/70064814-1929eb00-1625-11ea-9b49-ebe57b9d7260.png)

2. What did you expect to see?

TiDB should release all the memory after a large transaction finish.

3. What did you see instead?

Memory leak.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master 093b27aea8ced42159b7c62d30dd9f811dd2c435

**Comment by tiancaiamao** [comment]
I'm not sure why but here is a suspicious place:

https://github.com/pingcap/tidb/blob/093b27aea8ced42159b7c62d30dd9f811dd2c435/statistics/handle/update.go#L401

I'll verify it tomorrow.

**Comment by tiancaiamao** [comment]
Yes, it's the leak!
The system session's `sessionVar` keeps `commitDetail`, and the `commitDetail` reference memory data from 2PC and so on.

**Comment by shenli** [comment]
nice catch!
