### ISSUE TITLE
Tick leak while meeting errors

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#13897]
There is a branch which forgot to stop the time ticker. See https://github.com/pingcap/tidb/blob/master/store/tikv/oracle/oracles/pd.go#L130

**Comment by ngaut** [comment]
One more: https://github.com/pingcap/tidb/blob/master/util/expensivequery/expensivequery.go#L54

**Comment by disksing** [comment]
@ngaut First one is correct. It only break the `select` block.

**Comment by ngaut** [comment]
Should we use the defer release pattern?

**Comment by disksing** [comment]
Good idea.
