### ISSUE TITLE
Support information_schema.PARTITIONS

### ISSUE THREAD

**Issue by benmaoer** [pingcap/tidb#13905]
## Feature Request
I'm always frustrated when I'm trying to find partitioned tables in TiDB. I have to get table info then check partition through parser, get highest partition info, then add partition. It's too complicated. 

In MySQL, the PARTITIONS table provides information about table partitions. Each row in this table corresponds to an individual partition or subpartition of a partitioned table. [Link](https://dev.mysql.com/doc/refman/5.7/en/partitions-table.html)

**Comment by eurekaka** [comment]
@benmaoer thanks for reporting. Do you have interest to file PR to provide this functionality? If you need any help, you can refer to @tiancaiamao

**Comment by tangwz** [comment]
let me fix it.
