### ISSUE TITLE
Does tidb support the x protocol of MySQL?

### ISSUE THREAD

**Issue by canfeit** [pingcap/tidb#13903]
tidb有支持mysql的x协议的计划吗？能通过mysql shell访问tidb吗？

**Comment by eurekaka** [comment]
@canfeit thanks for reporting. @jackysp PTAL

**Comment by jackysp** [comment]
> tidb有支持mysql的x协议的计划吗？

I tried to support it in 2017, but the work of full support is relatively large...
> 能通过mysql shell访问tidb吗？

Of course. You can use the classic protocol of MySQL shell.

<img width="536" alt="企业微信截图_20191205191929" src="https://user-images.githubusercontent.com/4352397/70230862-33cea200-1794-11ea-9af2-2221710cd9ce.png">
