### ISSUE TITLE
Inconsistent `Rand()` with seed implementation compared to MySQL

### ISSUE THREAD

**Issue by andylokandy** [pingcap/tidb#13963]
## Bug Report

1. What did you do?

```sql
TiDB> select rand(1);
+--------------------+
| rand(1)            | 
+--------------------+
| 0.6046602879796196 | 
+--------------------+
```

2. What did you expect to see?

```sql
mysql> select rand(1);
+---------------------+
| rand(1)             | 
+---------------------+
| 0.40540353712197724 | 
+---------------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
[play.tidb.io](play.tidb.io)

This bug was found during the implementation of vectorized push down (https://github.com/tikv/tikv/pull/6117), where the correct mysql implementation is done (in review) on TiKV side. 

There is a related issue that `RandWithSeed` should not be pushed down for constant arg, or else inconsistency may happen. (https://github.com/pingcap/tipb/pull/162)

**Comment by Rustin-Liu** [comment]
I want to working on this issue. Could we add REQ-PCP title for this issue?

**Comment by nullnotnil** [comment]
Confirmed this is fixed in master:
```sql
select rand(1);

..

mysql> select rand(1);
+---------------------+
| rand(1)             |
+---------------------+
| 0.40540353712197724 |
+---------------------+
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-798-gd941ff5cc
Edition: Community
Git Commit Hash: d941ff5cc8b4babf9dcfdd91b66a5c53b798c122
Git Branch: master
UTC Build Time: 2020-07-18 05:54:02
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now. Thanks!
