### ISSUE TITLE
Go Report card OOM when test TiDB

### ISSUE THREAD

**Issue by xiekeyi98** [pingcap/tidb#13960]
![image](https://user-images.githubusercontent.com/7782671/70375226-41bc2880-1936-11ea-906c-6358b7028cbe.png)

We could see it in: https://goreportcard.com/report/github.com/pingcap/tidb
And I think it is OOM in the goreportcard...

**Comment by xiekeyi98** [comment]
File an issue try to solve this : https://github.com/gojp/goreportcard/issues/303

**Comment by nullnotnil** [comment]
In master this is an A+ again, so I am going to close this issue as fixed.
