### ISSUE TITLE
multiple instances of tidb-server may use the same temporary directory

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#13981]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Multiple instances of tidb-server may use the same temporary directy.
See https://github.com/pingcap/tidb/blob/0e0faeeb30c340e3dc091aaba01c336427a38f3c/util/chunk/disk.go#L47, if two of `tidb-server`s have same instance name but in different directory, each of them will share the same folder and the next start of one instance will  remove this directory so that another instance may face unexpected problem.

2. What did you expect to see?

- different instances in on node use different directories.
- if one tidb-server uses a temporary directory which another is in use, it should panic.
- When tidb-server starts, find a way to safely remove the temporary directory created when it last starts.
- We need ensure that `tidb-server` instance has the READ/WRITE privilege for the directory, otherwise, panic when starts up.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

4.0.0-alpha

**Comment by hsqlu** [comment]
How about using "tidb-server-" + os.Getpid() as the subdirectory?

**Comment by SunRunAway** [comment]
> How about using "tidb-server-" + os.Getpid() as the subdirectory?

After #14600, the path of temporary directory is defined specifically in the config file, so that we cannot use `os.Getpid()` as path automatically.

**Comment by SunRunAway** [comment]
IMO, If one instance starts and holds a temporary directory, it can save a lock file (https://github.com/nightlyone/lockfile) into the directory.
And if another instance starts and tries to hold the same directory, it panics.

**Comment by SunRunAway** [comment]
2. What did you expect to see?

- different instances in on node use different directories.
    + It depends on config files written by users
- if one tidb-server uses a temporary directory which another is in use, it should panic.
    + Use `lockfile` to handle this
- When tidb-server starts, find a way to safely remove the temporary directory created when it last starts.
    + If a directory is not locked by other instance, an instance can hold and lock this directory and safely remove the old temporary files when it starts.
- We need ensure that `tidb-server` instance has the READ/WRITE privilege for the directory, otherwise, panic when starts up.
    + It can check through reading/writing `lockfile`

**Comment by hsqlu** [comment]
I have a look at the [gofslock](https://github.com/danjacques/gofslock). Sounds like it is to lock a file instead of a path. Does it mean we have to create something like a lockfile under the dir to determine if this dir are hold by another tidb instance?

**Comment by SunRunAway** [comment]
> I have a look at the [gofslock](https://github.com/danjacques/gofslock). Sounds like it is to lock a file instead of a path. Does it mean we have to create something like a lockfile under the dir to determine if this dir are hold by another tidb instance?

Exactly.
