### ISSUE TITLE
Can I debug this project through the source code? 

### ISSUE THREAD

**Issue by huangpeilong** [pingcap/tidb#1398]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go1.6.2 windows/amd64

2. What operating system and processor architecture are you using (`go env`)?
set GOARCH=amd64
set GOBIN=
set GOEXE=.exe
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOOS=windows
set GOPATH=C:\Users\Hplong\Documents\projects\go
set GORACE=
set GOROOT=C:\Go
set GOTOOLDIR=C:\Go\pkg\tool\windows_amd64
set GO15VENDOREXPERIMENT=1
set CC=gcc
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0
set CXX=g++
set CGO_ENABLED=1

3. What did you do?
If possible, provide a recipe for reproducing the error.
Download the source code, run the tidb_test.go

4. What did you expect to see?
The project starts up and I can debug the project step by step.
(now I can only run the test cases through parser_test.go, but still can not debug it.)

5. What did you see instead?
Errors reported from liteIDE informs that “Fail to start the process”

**Comment by shenli** [comment]
@huangpeilong Thanks for your report!
TiDB is a pure go project. You can use any method which is work for go to debug it.
For example [GDB](https://golang.org/doc/gdb).

**Comment by tiancaiamao** [comment]
I'm not familiar with liteIDE, but [Delve](https://github.com/derekparker/delve) should work.
Maybe you can try it on command line:

```
cd $GOPATH/src/github.com/pingcap/tidb
ln -s _vendor/vendor vendor
dlv test .
b tidb_test.go:168
r
c
```

**Comment by huangpeilong** [comment]
@shenli But when I press 'F5' and try to debug the project , it reports "16:43:56 debug: not find execute file in path C:/Users/Hplong/Documents/projects/go/src/github.com/pingcap/tidb", which means I don't have the .exe file of the project. Now I can run the parser_test.go and tidb_test.go through the liteIDE, but I just can not debug the code step by step . Should I create a new empty project, and then  copy the tidb project files in it, invoking the functions in *_test.go? Or do you have any other suggestion?

**Comment by ngaut** [comment]
We are developing TiDB on linux or mac. And we haven't test it on windows. It may works on windows, but i am not sure. And you are welcome to make TiDB work on windows.

**Comment by shenli** [comment]
You can build the tidb-server first by "make server". It will create a binary file tidb-server in the directory tidb-server. Then you can debug it. @huangpeilong

**Comment by huangpeilong** [comment]
@ngaut Ok, I am trying to debug it on windows.
@shenli Now I use the "make server" under the TiDB dictionary, and it reports
"C:\Users\Hplong\Documents\projects\go\src\github.com\pingcap\tidb>make server
[Parser]
Parse table entries: 420495 of 1042566, x 16 bits == 840990 bytes
Parse table entries: 420495 of 1042566, x 16 bits == 840990 bytes
[Build]
godep: No Godeps found (or in any parent directory)
[Install]
godep: No Godeps found (or in any parent directory)
[Test]
godep: No Godeps found (or in any parent directory)
[Done]"
And there is only a "main.go" file under tidb-server dictionary, I can not find the binary file in tidb-server, so it's still not working now. Did you already debug the code on windows and do you have steps to suggest?
What's more I can see dodep.exe in the "C:\Users\Hplong\Documents\projects\go\bin", and that path is added to the environment.

**Comment by shenli** [comment]
We use vendor to solve golang's dependency. When running "make server", it will add soft link for vendor directory. Seems it does not work on Windows. See: https://github.com/pingcap/tidb/blob/master/Makefile#L138 

We suggest running TiDB on Linux/Mac and do not guarantee all the things work on Windows.
Could you send us a PR to fix it?

**Comment by huangpeilong** [comment]
What's "PR"?

**Comment by shenli** [comment]
PR is short for Pull Request. @huangpeilong 
It means sending us a patch for a feature or bug.

**Comment by huangpeilong** [comment]
@shenli ok, I am trying it on linux now. And when I running "make server",it reports as below:
"hplong@ubuntu:~/Downloads/tidb-master$ make server
go get github.com/qiuyesuifeng/goyacc
go get github.com/qiuyesuifeng/golex
$(which goyacc) -o /dev/null -xegen temp_parser_file parser/parser.y
Parse table entries: 420495 of 1042566, x 16 bits == 840990 bytes
$(which goyacc) -o parser/parser.go -xe temp_parser_file parser/parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; system("rm -f temp_parser_file"); exit 1;}}'
rm -f temp_parser_file
rm -f y.output
$(which golex) -o parser/scanner.go parser/scanner.l
fatal: Not a git repository (or any of the parent directories): .git
rm -rf vendor && ln -s _vendor/vendor vendor
# github.com/pingcap/tidb/parser
../../../Documents/go/src/github.com/pingcap/tidb/parser/yy_parser.go:63: undefined: yySymType
make: *** [server] Error 2"

**Comment by huangpeilong** [comment]
@shenli @ngaut Now the make&make server is ok, I can run the "tidb-server" file, but when I debug the tidb-server using "F5", the following error occur：

“/usr/local/go/bin/go build -gcflags "-N -l" [/home/hplong/Documents/go/src/github.com/pingcap/tidb/tidb-server]
# github.com/pingcap/tidb/store/tikv/mock-tikv
../store/tikv/mock-tikv/pd.go:40: cannot use pdClient literal (type *pdClient) as type pd.Client in return argument:
	*pdClient does not implement pd.Client (wrong type for GetRegion method)
		have GetRegion([]byte) (*metapb.Region, error)
		want GetRegion([]byte) (*metapb.Region, *metapb.Peer, error)
Command exited with code 2.”

**Comment by shenli** [comment]
@huangpeilong We updated pingcap/pd repo, but did not update pingcap/tidb repo. It seems that your tidb-server is built with pd in GOPTAH, not in vendor directory. Please try this solution:
Rollback pingcap/pd in your GOPATH to commit version 3fe05c948c17bdd18fc2cc7acf62e699f20b0583 

I will update tidb's vendor and fix this problem soon.

**Comment by huangpeilong** [comment]
ok，thanks! @shenli
