### ISSUE TITLE
The "varchar" type column flags are not compatible with MySQL

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#13992]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
CREATE TABLE t (
    ->  c varchar(120) DEFAULT NULL
    -> ) CHARSET=utf8 COLLATE=utf8_bin;

 select c from t;
```

2. What did you expect to see?
<img width="158" alt="Screen Shot 2019-12-09 at 16 41 02" src="https://user-images.githubusercontent.com/4242506/70420445-b6ac7100-1aa2-11ea-998c-140941be547a.png">

3. What did you see instead?
<img width="581" alt="Screen Shot 2019-12-09 at 17 00 31" src="https://user-images.githubusercontent.com/4242506/70421758-74386380-1aa5-11ea-8fb6-22133673e868.png">

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.18-32-g8ddd007c7-dirty
Git Commit Hash: 8ddd007c7b3aafbd571bf43d5b7fe4ad7fb9704c
Git Branch: heads/zimuxia/drop-col

**Comment by nullnotnil** [comment]
Confirming that I can still reproduce this in master:
```sql
DROP TABLE IF EXISTS t;
CREATE TABLE t (
 c varchar(120) DEFAULT NULL
) CHARSET=utf8 COLLATE=utf8_bin;

SELECT c FROM t;

..

mysql> SELECT c FROM t;
Field   1:  `c`
Catalog:    `def`
Database:   `test`
Table:      `t`
Org_table:  `t`
Type:       VAR_STRING
Collation:  utf8_bin (83)
Length:     360
Max_length: 0
Decimals:   0
Flags:      

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-771-gca41972fb
Edition: Community
Git Commit Hash: ca41972fbac068c8a5de107d9075f09ac68842ac
Git Branch: master
UTC Build Time: 2020-07-14 02:41:21
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)


vs mysql:

mysql [localhost:5731] {msandbox} (test) > SELECT c FROM t;
Field   1:  `c`
Catalog:    `def`
Database:   `test`
Table:      `t`
Org_table:  `t`
Type:       VAR_STRING
Collation:  utf8_general_ci (33)
Length:     360
Max_length: 0
Decimals:   0
Flags:      BINARY 
```

**Comment by blacktear23** [comment]
The simple fix is if we meet collation in [charset.CollationUTF8, charset.CollationUTF8MB4, charset.CollationASCII, charset.CollationLatin1], just add `mysql.BinaryFlag` to column's `Flag`. But due to https://github.com/pingcap/tidb/pull/9689 client will get `NOT_NULL BINARY` as column type result. And this is also not compatible with MySQL.

**Comment by wjhuang2016** [comment]
MySQL's behavior is strange, and we decide not to fix it unless it really affect the usage.
