### ISSUE TITLE
Make golint happy

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#14025]
## Feature Request

**Is your feature request related to a problem? Please describe:**

According to https://goreportcard.com/report/github.com/pingcap/tidb,
![image](https://user-images.githubusercontent.com/17380469/70613215-34a77e00-1c43-11ea-9436-0befa137739c.png)

Please address these warnings.

**Comment by Tian-JQ** [comment]
Let me do it

**Comment by wjhuang2016** [comment]
Close by #14034
