### ISSUE TITLE
Optimize the hash table used by `HashAggExec`

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14024]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When testing TPCH Q18, we find that the hash table used by `HashAggExec` is slow and causes a lot of memory allocations, which can be optimized.
![image](https://user-images.githubusercontent.com/7499936/70608246-c2cb3680-1c3a-11ea-9a1e-01963ab3b188.png)

One way to optimize it is that we can replace it with our new hash map defined in `executor/hash_table.go`, which is used by `HashJoinExec`.

**Comment by b41sh** [comment]
Let me do this.

**Comment by qw4990** [comment]
After investigating and discussing with @b41sh and @SunRunAway, we find that the way using the `HashMap` used by `HashJoin` to optimize this issue is useless.

Now in the implementation of `HashAgg`, after merging intermediate results into `partialResult` we can discard input data.
If we use the `HashMap`, we have to keep input data since in probe phase it will be used to match group keys(https://github.com/pingcap/tidb/blob/master/executor/hash_table.go#L140)
So the memory consumption will not decrease.
