### ISSUE TITLE
what's the different between tidb and hawq

### ISSUE THREAD

**Issue by lordk911** [pingcap/tidb#1403]
I learn about tidb from infoQ , looks like tidb is a distributed mpp database , so I want to know the different between tidb and hawq which derived from greenplum db,and what's the advancement of tidb.

**Comment by shenli** [comment]
@lordk911 In one word, TiDB is an OLTP database and hawq/gpdb is OLAP database. 
To handle large dataset, TiDB supports mpp. But we will focus on OLTP now and only support simple OLAP function.

PS: We encourage describe issue in English. So people from all the world could read your issue.

**Comment by lordk911** [comment]
ok.thanks.
