### ISSUE TITLE
Let `PointGet` be a choice of `DataSource`'s PhysicalPlan.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#14044]
## Feature Request

There're two api to access data in TiKV. One is kv's Get/BatchGet, the other is coprocessor. Get/BatchGet is lighter than coprocessor. There's no other calculation(like filter or aggregate). The Get will have significant stronger performance compared with coprocessor.

So there is a need to make the `PointGet` as a choice of `DataSource`'s Physical Plan.

**Comment by zz-jason** [comment]
> The Get will have significant stronger performance compared with coprocessor.

Do we have some benchmark result to quantify the performance difference?
