### ISSUE TITLE
lazyMemBuffer cache gets nil instance occasionally.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1405]
This code panics in very rare case, but `lmb.mb` should not be nil after get from cache.
```go
func (lmb *lazyMemBuffer) Seek(k Key) (Iterator, error) {
	if lmb.mb == nil {
		lmb.mb = p.get()
	}

	return lmb.mb.Seek(k)
}
```

The following code is the only place MemBuffer is put into cache.
 `lmb.mb` should not be nil too.
```go
func (lmb *lazyMemBuffer) Release() {
	if lmb.mb == nil {
		return
	}

	lmb.mb.Release()

	p.put(lmb.mb)
	lmb.mb = nil
}
```

**Comment by disksing** [comment]
Does it mean that the `lazyMemBuffer` is accessed concurrently somehow?

**Comment by coocood** [comment]
No, it is created in `AddRecord` method.

https://github.com/pingcap/tidb/blob/master/table/tables/tables.go#L319

And used at.

https://github.com/pingcap/tidb/blob/master/table/tables/tables.go#L359

**Comment by disksing** [comment]
Do we need to call Rollback here?
https://github.com/pingcap/tidb/blob/master/kv/txn.go#L52

**Comment by shenli** [comment]
@disksing I think we need.

**Comment by coocood** [comment]
fixed by https://github.com/pingcap/tidb/pull/1411
