### ISSUE TITLE
PCP: Fix implementation of `builtinRandWithSeedSig`

### ISSUE THREAD

**Issue by andylokandy** [pingcap/tidb#14079]
## Description

Refer to https://github.com/pingcap/tidb/issues/13963.

For this task: 
- Both non-vectorized and vectorized version should be fixed.
- ColumnRef-only push-down should also be enabled for `RandWithSeedFirstGen`.
- Rename `builtinRandWithSeedSig` to `builtinRandWithSeedFirstGenSig`

## Difficulty

- Easy

## Score

- 100

## Mentor(s)

- @andylokandy 
- @breeswish 

## Recommended Skills

- Go programming

**Comment by Rustin-Liu** [comment]
Here are the snippets I copied from MySQL source code:

// definition of rng
struct rand_struct {
  unsigned long seed1,seed2,max_value;
  double max_value_dbl;
};

// gen()
double my_rnd(struct rand_struct *rand_st)
{
  rand_st->seed1= (rand_st->seed1*3+rand_st->seed2) % rand_st->max_value;
  rand_st->seed2= (rand_st->seed1+rand_st->seed2+33) % rand_st->max_value;
  return (((double) rand_st->seed1) / rand_st->max_value_dbl);
}

// create rng
void randominit(struct rand_struct *rand_st, ulong seed1, ulong seed2)
{                                               /* For mysql 3.21.# */
  rand_st->max_value= 0x3FFFFFFFL;
  rand_st->max_value_dbl=(double) rand_st->max_value;
  rand_st->seed1=seed1%rand_st->max_value ;
  rand_st->seed2=seed2%rand_st->max_value;
}

// for seed by arg
void Item_func_rand::seed_random(Item *arg)
{
  /*
    TODO: do not do reinit 'rand' for every execute of PS/SP if
    args[0] is a constant.
  */
  uint32 tmp= (uint32) arg->val_int();
  randominit(rand, (uint32) (tmp*0x10001L+55555555L),
             (uint32) (tmp*0x10000001L));
}

// for seed by time, where they cache the rng globally. We can cache it per request in metadata
randominit(&sql_rand,(ulong) server_start_time,(ulong) server_start_time/2);
Some of the fields (.eg max_value) can be extracted to constants.

**Comment by Rustin-Liu** [comment]
The more details you can find in: https://github.com/tikv/tikv/pull/6117#issuecomment-562489078

**Comment by Rustin-Liu** [comment]
I am working on it.
