### ISSUE TITLE
Testing tidb with mattermost-server

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#14108]
mattermost-server can use MySQL as default database, we could test it with TiDB.

See more: https://github.com/mattermost/mattermost-server

**Comment by wwar** [comment]
mattermost requires `FULLTEXT` index support: https://github.com/pingcap/tidb/issues/1793

The schema [can be seen here](https://github.com/mattermost/mattermost-server/blob/master/scripts/mattermost-mysql-5.0.sql).

**Comment by nullnotnil** [comment]
Because it is blocked by FULLTEXT search (https://github.com/pingcap/tidb/issues/1793), I am going to close this issue.

Please feel free to re-open it if you would like to discuss it further. Thanks!
