### ISSUE TITLE
What's the default user and password for TiDB

### ISSUE THREAD

**Issue by fenggolang** [pingcap/tidb#14137]
tidb 容器启动默认用户密码是多少

docker pull pingcap/tidb

**Comment by tiancaiamao** [comment]
User = root, no password.
Note the port is 4000, not 3306

> mysql -h 127.0.0.1 -u root -P 4000

By the way, you can use Chinese in https://asktug.com/
That website is for our user group and github maybe something preferred by the developers

**Comment by zz-jason** [comment]
close due to answered. feel free to open any issue on github if you met any problem 😄
