### ISSUE TITLE
Does TiDB support zabbix?

### ISSUE THREAD

**Issue by geekard** [pingcap/tidb#1415]
@shenli ，你在pull request #1196 里提到TiDB支持zabbix了！这非常令人兴奋！

我们的zabbix系统数据库负载非常大(每天新增70GB左右监控数据)，经常出问题，想使用TiDB来解决数据库的shard、吞吐问题，所以请问下你的测试情况，现在迁移有问题么？

== English ==
@shenli Your PR #1196 shows that TiDB is now support Zabbix! That's awesome.

The workload of our zabbix system is very heavy (70GB new data per day), we want to use TiDB instead of MySQL to avoid shading, and handle the throughput. Does TiDB ready for this?

**Comment by shenli** [comment]
@geekard We have tested running zabbix on TiDB a few month before. It works. But we do not satisfied with the speed. 
We are improving the performance of TiDB.  You can try the latest master. If you meet any problem, please raise an issue or send us a PR.

PS: We encourage describing issue in English.

**Comment by geekard** [comment]
Thanks shenli ! I will try the latest master.

**Comment by shenli** [comment]
@geekard I change the title to English. Hope you don't mind. :)
Please let us know if you meet any problem.

**Comment by geekard** [comment]
Never mind. :)

@shenli, Do you have any suggestions before testing? I'm very appreciated!

**Comment by shenli** [comment]
If you use TiKV as storage engine, I recommend you deploy TiDB/TiKV on machines with SSD disk.

**Comment by geekard** [comment]
@shenli, I run the latest docker image, but grant privileges failed:

% mysql -h 127.0.0.1 -P 4000 -u root -D test
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10006
Server version: 5.5.31-TiDB-1.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [test]> grant all privileges on zabbix.* to zabbix@localhost identified by '<password>';
ERROR 1105 (HY000): line 1 column 11 near "privileges"

**The following is from container logs:**

2016/07/08 08:45:05 txn.go:113: [debug] [kv] commit txn 384818873708838912
2016/07/08 08:45:07 session.go:394: [warning] compiling grant all privileges on zabbix.* to zabbix@localhost identified by '<password>', error: line 1 column 11 near "privileges"
2016/07/08 08:45:07 conn.go:260: [debug] [TIME_CMD] 160.645µs 3
2016/07/08 08:45:07 conn.go:241: [warning] dispatch error line 1 column 11 near "privileges"
/go/src/github.com/pingcap/tidb/parser/yy_parser.go:87: 
/go/src/github.com/pingcap/tidb/session.go:395: 
/go/src/github.com/pingcap/tidb/server/conn.go:376: , conn: 172.17.0.1:52674, status: 2, charset: utf8, user: root, lastInsertId: 0
2016/07/08 08:45:07 conn.go:242: [warning] cmd: grant all privileges on zabbix.* to zabbix@localhost identified by '<password>'

**Comment by shenli** [comment]
May I have your Zabbix version? @geekard

**Comment by geekard** [comment]
I only executed two sql statements, has no relationship with zabbix:

% mysql -h 127.0.0.1 -P 4000 -u root -D test
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 10027
Server version: 5.5.31-TiDB-1.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [test]> create database zabbix character set utf8 collate utf8_bin;
Query OK, 0 rows affected (0.03 sec)

MySQL [test]> grant all privileges on zabbix.* to zabbix@localhost identified by '<password>';
ERROR 1105 (HY000): line 1 column 11 near "privileges"

**Comment by ngaut** [comment]
Thanks for your report. We will fix it later.

**Comment by shenli** [comment]
@geekard Sorry for the late reply. It is a bug in our parser. We miss "grant all privileges" syntax. It is fixed in this PR: https://github.com/pingcap/tidb/pull/1417

BTW:  You should add quote mark for username and host. For example:
grant all privileges on zabbix.* to 'zabbix'@'localhost' identified by 'password';

**Comment by geekard** [comment]
@shenli  I run zabbix successfully now, using the latest docker image!

But when displaying 'Status of zabbix', it took 74 seconds, which is too long.

The following is debug output. I will try TiKV later.

******************** Script profiler ********************
Total time: 74.026581
Total SQL time: 74.044125
SQL count: 16 (selects: 13 | executes: 3)
Peak memory usage: 2M
Memory limit: 128M

。。。。ignore 。。。。

SQL (71.520362): SELECT COUNT(DISTINCT t.triggerid) AS cnt,t.status,t.value FROM triggers t WHERE NOT EXISTS (SELECT f.functionid FROM functions f JOIN items i ON f.itemid=i.itemid JOIN hosts h ON i.hostid=h.hostid WHERE f.triggerid=t.triggerid AND (i.status<>0 OR h.status<>0)) AND t.flags IN (0,4) GROUP BY t.status,t.value
zabbix.php:21 → require_once() → ZBase->run() → ZBase->processRequest() → CView->getOutput() → include() → make_status_of_zbx() → get_status() → DBselect() in include/func.inc.php:2012


MySQL [zabbix]> explain SELECT COUNT(DISTINCT t.triggerid) AS cnt,t.status,t.value FROM triggers t WHERE NOT EXISTS (SELECT f.functionid FROM functions f JOIN items i ON f.itemid=i.itemid JOIN hosts h ON i.hostid=h.hostid WHERE f.triggerid=t.triggerid AND (i.status<>0 OR h.status<>0)) AND t.flags IN (0,4) GROUP BY t.status,t.value;
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
| id   | select_type | table    | type | possible_keys | key  | key_len | ref  | rows | Extra       |
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+
|    1 | SIMPLE      | triggers | ALL  | NULL          | NULL | NULL    | NULL | 0    | Using where |
+------+-------------+----------+------+---------------+------+---------+------+------+-------------+

**Comment by shenli** [comment]
@geekard There is a few query with subquery and join which may run slow in TiDB.  We are working on impoving them. 
If there is any performance improvement. I will let you know.
May I have your zabbix verson? I will test it on my machine.

**Comment by geekard** [comment]
@shenli  Thanks!

I use the latest zabbix docker image(current version is 3.0.3). The commands are following:

$ docker run --name tidb-server -d -p 4000:4000 pingcap/tidb:latest
$ mysql  -h 127.0.0.1 -P 4000 -u root -e "create database zabbix character set utf8 collate utf8_bin;"
$ mysql  -h 127.0.0.1 -P 4000 -u root -e "create user 'zabbix'@'%' identified by '123';"
$ mysql  -h 127.0.0.1 -P 4000 -u root -e "grant all privileges on zabbix.* to 'zabbix'@'%';"
$ cd /path/to/zabbix-3.0.3/database/mysql # you can download source code from here: http://www.zabbix.com/download.php
$ mysql  -h 127.0.0.1 -P 4000 -u root zabbix <schema.sql
$ mysql  -h 127.0.0.1 -P 4000 -u root zabbix <images.sql
$ mysql  -h 127.0.0.1 -P 4000 -u root zabbix <data.sql
$ docker run -d --name zabbix -p 80:80 -p 10051:10051 -v  /etc/localtime:/etc/localtime:ro --link tidb-server:zabbix.db --env="ZS_DBHost=zabbix.db" --env="ZS_DBPassword=123"  --env="ZS_DBPort=4000" monitoringartist/zabbix-3.0-xxl:latest

Then open http://127.0.0.1，login using account "Admin/zabbix".

You can turn on debug mode by: Adminstration -> Users -> Zabbix administrator, then check on 'Debug mode'

**Comment by shenli** [comment]
@geekard Thanks!

**Comment by shenli** [comment]
@geekard  We add a new sql optimizer in TiDB. The performance benefits a lot from it. 
The new optimizer is not finished yet, so it is not the default sql optimizer. You can enable it by passing an argument to tidb-server.
"docker run --name tidb-server -d -p 4000:4000 pingcap/tidb:latest   --newplan=1"
On my machine, displaying 'Status of zabbix' costs less than one second. Please try the latest master.

**Comment by geekard** [comment]
@shenli Well Done!  It's amazing to see the performance benefits! 

But, when I import online data to TiDB, it reported following error:

```
% head valuemaps.txt
'4','APC Battery Replacement Status'
'5','APC Battery Status'
'7','Dell Open Manage System Status'
'6','HP Insight System Status'
'2','Host status'
'14','Maintenance status'
'9','SNMP device status (hrDeviceStatus)'
'11','SNMP interface status (ifAdminStatus)'
'8','SNMP interface status (ifOperStatus)'
'1','Service state'

% mysqlimport --local --fields-terminated-by=, --fields-enclosed-by="'" --fields-escaped-by=/ -h 127.0.0.1 -P 4000 -u root zabbix_server valuemaps.txt
mysqlimport: Error: 1105 line 1 column 36 near ";"
```
```
mysql> use zabbix_server
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql>
mysql>  LOAD DATA LOCAL INFLIE 'valuemaps.txt' INTO TABLE valuemaps fields terminated by "," fields enclosed by "'" fields escaped by "/";
ERROR 1105 (HY000): line 1 column 1 near "LOAD"
mysql>

```

**Comment by geekard** [comment]
@shenli  Our online history.*/trends.* tables were partitioned and we have some views/procedures,  when I restored them, I saw lots of errors as following. Does TiDB support partition/view/procedures? Or, we don't need them any more?

```
ERROR 1105 (HY000): line 10 column 1 near "PARTITION"
ERROR 1105 (HY000): line 8 column 1 near "PARTITION"
ERROR 1105 (HY000): line 1 column 6 near "VIEW"
ERROR 1105 (HY000): line 1 column 8 near "DEFINER"
ERROR 1105 (HY000): line 1 column 8 near "ALGORITHM"
```

**Comment by shenli** [comment]
@geekard Thanks for your trying.
TiDB does not support partition/view/procedures. 
For a distributed database, we do not need explicit partition.
Implement view and procedures will bring some problems. So We are not sure whether we will support them.

Could you show me TiDB's error log for the following problem?
> % mysqlimport --local --fields-terminated-by=, --fields-enclosed-by="'" --fields-escaped-by=/ -h 127.0.0.1 -P 4000 -u root zabbix_server valuemaps.txt
mysqlimport: Error: 1105 line 1 column 36 near ";"

**Comment by geekard** [comment]
@shenli Thanks!  The following are containter logs:

**part one:**
2016/07/22 01:03:07 txn.go:54: [debug] [kv] get key:6d 42 67 4a 6f 62 4f 77 6e ff 65 72 00 00 00 00 00 00 f9 00 00 00 00 00 00 00 73, txn:385128696923553792
2016/07/22 01:03:07 txn.go:59: [debug] [kv] set key:6d 42 67 4a 6f 62 4f 77 6e ff 65 72 00 00 00 00 00 00 f9 00 00 00 00 00 00 00 73, txn:385128696923553792
2016/07/22 01:03:07 ddl_worker.go:148: [debug] [ddl] become background job owner e5e21620-637c-4707-9c02-929b244eb7fa
2016/07/22 01:03:07 txn.go:54: [debug] [kv] get key:6d 42 67 4a 6f 62 4c 69 73 ff 74 00 00 00 00 00 00 00 f8 00 00 00 00 00 00 00 4c, txn:385128696923553792
2016/07/22 01:03:07 txn.go:113: [debug] [kv] commit txn 385128696923553792
2016/07/22 01:03:07 ddl_worker.go:317: [debug] [ddl] wait 10s to check DDL status again
2016/07/22 01:03:07 txn.go:48: [debug] [kv] Begin txn:385128696923815936
2016/07/22 01:03:07 txn.go:54: [debug] [kv] get key:6d 44 44 4c 4a 6f 62 4f 77 ff 6e 65 72 00 00 00 00 


**Part two:**
2016/07/22 01:03:38 txn.go:113: [debug] [kv] commit txn 385128705246887936
2016/07/22 01:03:38 conn.go:260: [debug] [TIME_CMD] 570.666µs 4
2016/07/22 01:03:45 session.go:395: [warning] compiling LOAD DATA LOCAL INFLIE 'valuemaps.txt' INTO TABLE valuemaps fields terminated by "," fields enclosed by "'" fields escaped by "/", error: line 1 column 1 near "LOAD"
2016/07/22 01:03:45 conn.go:260: [debug] [TIME_CMD] 163.332µs 3
2016/07/22 01:03:45 conn.go:241: [warning] dispatch error line 1 column 1 near "LOAD"
/go/src/github.com/pingcap/tidb/parser/yy_parser.go:87: 
/go/src/github.com/pingcap/tidb/session.go:396: 
/go/src/github.com/pingcap/tidb/server/conn.go:376: , conn: 172.17.0.1:60688, status: 2, charset: utf8, user: root, lastInsertId: 0
2016/07/22 01:03:45 conn.go:242: [warning] cmd: LOAD DATA LOCAL INFLIE 'valuemaps.txt' INTO TABLE valuemaps fields terminated by "," fields enclosed by "'" fields escaped by "/"
2016/07/22 01:03:47 ddl_worker.go:317: [debug] [ddl] wait 10s to check DDL status again
2016/07/22 01:03:47 txn.go:48: [debug] [kv] Begin txn:385128707409313792

**Comment by shenli** [comment]
@geekard Thanks!

I will fix the following bug.
> [warning] compiling /!40101 set @@character_set_database=binary */;, error: line 1 column 36 near ";"

After reading [MySQL's document about partition](https://dev.mysql.com/doc/refman/5.7/en/partitioning-overview.html) I have an idea. Maybe we could ignore the PARTITION keyword, it will do no harm.
TiDB will automatically partition data into many slices. I will have a try.

**Comment by ngaut** [comment]
Hi @geekard:
 We just supported the "Load data" command in the master branch.
