### ISSUE TITLE
Error while importing data from mysql dump file

### ISSUE THREAD

**Issue by neer1304** [pingcap/tidb#14173]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
 /usr/local/mysql/bin/mysql  --local-infile=1 -u root -h 127.0.0.1 -P 4000 < dump-03.sql
File size ~ 6.2 GB

2. What did you expect to see?
Data exported successfully in tidb

3. What did you see instead?
ERROR 9001 (HY000) at line 190464: PD server timeout

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.5-dirty
[pd_server_timeout.log](https://github.com/pingcap/tidb/files/3992880/pd_server_timeout.log)

**Comment by winoros** [comment]
@jackysp PTAL

**Comment by jackysp** [comment]
Could you provide the log of pd-server? @neer1304

**Comment by neer1304** [comment]
[tidb-docker-compose_pd0_1.log](https://github.com/pingcap/tidb/files/3998662/tidb-docker-compose_pd0_1.log)
[tidb-docker-compose_pd1_1.log](https://github.com/pingcap/tidb/files/3998663/tidb-docker-compose_pd1_1.log)
[tidb-docker-compose_pd2_1.log](https://github.com/pingcap/tidb/files/3998664/tidb-docker-compose_pd2_1.log)
PFA the logs

**Comment by jackysp** [comment]
There are many 
```
error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
PTAL @overvenus , thanks!

**Comment by jackysp** [comment]
\cc @nolouch

**Comment by rleungx** [comment]
@neer1304 Could you provide the full pds' log?

**Comment by neer1304** [comment]
@rleungx What do you mean by full pds log. I have attached the logs of pd container above.
I have following container running right now -
tidb-docker-compose_tidb_1
tidb-docker-compose_tikv0_1
tidb-docker-compose_tikv2_1
tidb-docker-compose_tikv1_1
tidb-docker-compose_grafana_1
tidb-docker-compose_pd1_1
tidb-docker-compose_pd0_1
tidb-docker-compose_pd2_1

**Comment by nolouch** [comment]
according 
https://github.com/pingcap/tidb-docker-compose/blob/1c4da862e3f5e11d7bfc4b7152cb4dd7eb6bd773/docker-compose.yml#L3-L22
, the logs file be in  ./logs/xxx.log
@neer1304

**Comment by neer1304** [comment]
[logs.zip](https://github.com/pingcap/tidb/files/3999813/logs.zip)
PFA attached the logs folder. @nolouch @rleungx

**Comment by rleungx** [comment]
@neer1304 Can you use `curl http://ip:port/pd/api/v1/health` to see if all members are healthy?

**Comment by neer1304** [comment]
@rleungx curl http://127.0.0.1:32768/pd/api/v1/health
[
  {
    "name": "pd0",
    "member_id": 2569432990168970607,
    "client_urls": [
      "http://pd0:2379"
    ],
    "health": true
  },
  {
    "name": "pd1",
    "member_id": 5121893302248312363,
    "client_urls": [
      "http://pd1:2379"
    ],
    "health": true
  },
  {
    "name": "pd2",
    "member_id": 6077736303471108965,
    "client_urls": [
      "http://pd2:2379"
    ],
    "health": true
  }
]

**Comment by rleungx** [comment]
How about `curl http://127.0.0.1:32768/pd/api/v1/members`?

**Comment by neer1304** [comment]
curl http://127.0.0.1:32768/pd/api/v1/members
{
  "header": {
    "cluster_id": 6771658276302724361
  },
  "members": [
    {
      "name": "pd0",
      "member_id": 2569432990168970607,
      "peer_urls": [
        "http://pd0:2380"
      ],
      "client_urls": [
        "http://pd0:2379"
      ]
    },
    {
      "name": "pd1",
      "member_id": 5121893302248312363,
      "peer_urls": [
        "http://pd1:2380"
      ],
      "client_urls": [
        "http://pd1:2379"
      ]
    },
    {
      "name": "pd2",
      "member_id": 6077736303471108965,
      "peer_urls": [
        "http://pd2:2380"
      ],
      "client_urls": [
        "http://pd2:2379"
      ]
    }
  ],
  "leader": {
    "name": "pd2",
    "member_id": 6077736303471108965,
    "peer_urls": [
      "http://pd2:2380"
    ],
    "client_urls": [
      "http://pd2:2379"
    ]
  },
  "etcd_leader": {
    "name": "pd2",
    "member_id": 6077736303471108965,
    "peer_urls": [
      "http://pd2:2380"
    ],
    "client_urls": [
      "http://pd2:2379"
    ]
  }
}
@rleungx

**Comment by rleungx** [comment]
@neer1304 The timestamp of the last log is `12/24 15:01` and from the log, it says there is no etcd leader. But from the output of the member, we can find the etcd leader is pd2. Is this situation still continuing? If so, could you provide the latest log?

**Comment by neer1304** [comment]
@rleungx When I freshly started the data migration and after sometime hit the api I get following
BLRM-300068335:logs 300068335$ curl http://127.0.0.1:32768/pd/api/v1/members
no leader
Attached the recent logs
[logs.zip](https://github.com/pingcap/tidb/files/4000568/logs.zip)

**Comment by rleungx** [comment]
@neer1304 The default log level in docker-compose is "error", you can change it to "info" by using `curl -X POST -H "Content-Type: application/json" http://ip:port/pd/api/v1/admin/log --data '"info"'`. It will provide more information about why there is no leader. BTW, you can check if your containers' status is ok or the output of health is ok when you encounter the `no leader` problem.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
