### ISSUE TITLE
Data Truncated error shown while it should not be an error

### ISSUE THREAD

**Issue by ldblovepeace** [pingcap/tidb#14176]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
create table if not exists test(
    -- 必填字段
    data_source        varchar(32)   not NULL 
	)
ENGINE=InnoDB DEFAULT CHARSET=utf8;

replace into test
select 1 from dual
where 1+' ' > 0;
```

2. What did you expect to see?

> insert success into table test

3. What did you see instead?

```
replace into test
select 1 from dual
where 1+' ' > 0
> 1265 - Data Truncated
> 时间: 0.038s
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

> Release Version: v3.0.5-1-gc0a14b50e4
> Git Commit Hash: c0a14b50e4cd113dd4ce827de5e790a824ca98b6
> Git Branch: HEAD
> UTC Build Time: 2019-11-01 03:41:19
> GoVersion: go version go1.13 linux/amd64
> Race Enabled: false
> TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
> Check Table Before Drop: false

**Comment by winoros** [comment]
@jackysp PTAL

**Comment by jackysp** [comment]
Thanks for your report, @ldblovepeace . We'll investigate it.

**Comment by nullnotnil** [comment]
I tested this against master, and it now produces the same result as MySQL:
```sql
DROP TABLE IF EXISTS test;
CREATE TABLE test (data_source varchar(32) NOT NULL);
REPLACE INTO test SELECT 1 FROM dual WHERE 1 + ' ' > 0;
SELECT * FROM test;
..

mysql> REPLACE INTO test SELECT 1 FROM dual WHERE 1 + ' ' > 0;
Query OK, 1 row affected (0.03 sec)
Records: 1  Duplicates: 0  Warnings: 0

mysql> SELECT * FROM test;
+-------------+
| data_source |
+-------------+
| 1           |
+-------------+
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-807-g824df7675
Edition: Community
Git Commit Hash: 824df767559b8544af0cb71509135d322de1cd47
Git Branch: master
UTC Build Time: 2020-07-20 04:47:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to reopen if you have any further questions. Thanks!
