### ISSUE TITLE
default column order by 

### ISSUE THREAD

**Issue by guoshp** [pingcap/tidb#14198]
what's default column order by

**Comment by winoros** [comment]
@guoshp Can you provide more information?

**Comment by guoshp** [comment]
For a large table, the results of multiple limit queries are not in the same order

**Comment by guoshp** [comment]
> @guoshp Can you provide more information?

For a large table, the results of multiple limit queries are not in the same order

**Comment by nullnotnil** [comment]
Unless there is an explicit `ORDER BY`, TiDB is free to return the results in any order. Even though sometimes the order may appear to be the same, it is not recommended to rely on this, as a change in execution plan could modify the order.

This is SQL-standard behavior, and other databases behave similarly.
