### ISSUE TITLE
tidb drop in replacement on rails error

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [pingcap/tidb#1421]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6.2 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mmc/dev/golang/3rdLibs:/Users/mmc/dev/golang/myApps"
GORACE=""
GOROOT="/Users/mmc/dev/golang/go"
GOTOOLDIR="/Users/mmc/dev/golang/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
I just started tidb beta version, i want to make a drop in replacement of mysql on rails.
But when i run "rake db:create" in rails, it thows error, here are the snapshots.
I installed mysql by 
```
brew install mysql
```
![tidb_err](https://cloud.githubusercontent.com/assets/7458713/16721223/32dce93a-4770-11e6-9d2b-47010e154901.png)
![rails_db_create_err](https://cloud.githubusercontent.com/assets/7458713/16721224/333515d8-4770-11e6-8490-b844a87ecb55.png)

4. What did you expect to see?
Database created successfully as mysql.

5. What did you see instead?
Please see the snapshots, tidb throws an error when parse the sql, thank you very much!

**Comment by shenli** [comment]
@ziyouchutuwenwu Thanks for your report!
Seems there is a bug in TiDB's parser. We will fix it.

**Comment by shenli** [comment]
@ziyouchutuwenwu There is a branch named shenli/fix-1421. You can try this branch. We will merge it into master soon.

**Comment by shenli** [comment]
@ziyouchutuwenwu Please try the latest master.

**Comment by ziyouchutuwenwu** [comment]
I switched to the branch, but compile error.
I'm trying again, but the poor net speed……

I will show the result later, thanks for your hard work.

**Comment by ziyouchutuwenwu** [comment]
hi, the branch shenli/fix-1421 is closed, i re git cloned and make, but compile error，here is the error msg
![error](https://cloud.githubusercontent.com/assets/7458713/16724964/c05bad3e-4787-11e6-92f8-f85609dd9aa0.png)

**Comment by shenli** [comment]
@ziyouchutuwenwu  Please use the latest master.
May I have your go version. It is not compiling error. It is go vet error. So you can run make server to build the binary.

**Comment by ziyouchutuwenwu** [comment]
go version
go version go1.6.2 darwin/amd64

**Comment by shenli** [comment]
@ziyouchutuwenwu I use go with the same version with you. But I didn't meet the error. 
Could try the latest master? 
If the error is still there. Please help us check if branch shenli/fix-vet is OK.

**Comment by ziyouchutuwenwu** [comment]
creating and droping database with rails ok
but when i create some model, and run "rake db:migrate", there is still error, seems to be sql parser error, 

my steps
```
rails g model User name:string password:string
rake db:migrate
```

error screenshots
![migrate_error](https://cloud.githubusercontent.com/assets/7458713/16726439/c8f7739a-478e-11e6-8cef-891454bab198.png)
![rails_error](https://cloud.githubusercontent.com/assets/7458713/16726443/cc6eeb8e-478e-11e6-9dcd-7c78915cd423.png)

**Comment by shenli** [comment]
@ziyouchutuwenwu TiDB do not support Get_Lock() function.
Is "ActiveRecod::Migration" frequently used in rails?

**Comment by ziyouchutuwenwu** [comment]
I'm not clear about the details of ActiveRecord::Migration
but active record was very popular in ruby, not only rails

what a pity

**Comment by shenli** [comment]
@ziyouchutuwenwu We will discus whether we will support get_lock() function. I will let you know the result.
Is there any error when you run "make check" on the latest master?

**Comment by ziyouchutuwenwu** [comment]
i have the error yet
```
(python2) mmcdeMacBook-Air:tidb mmc$ git pull
Already up-to-date.
mmcdeMacBook-Air:tidb mmc$ make check
bash gitcookie.sh
go get github.com/golang/lint/golint
vet
executor/new_executor.go:606: github.com/pingcap/tidb/table.Column composite literal uses unkeyed fields
make: *** [check] Error 1
```

**Comment by shenli** [comment]
And how about branch "shenli/fix-vet"? If it fix the error, I will create a PR.

**Comment by ziyouchutuwenwu** [comment]
branch "shenli/fix-vet" works fine, thanks for your patience

**Comment by shenli** [comment]
@ziyouchutuwenwu ActiveRecord Migrations needs mysql's get_lock()/release_lock() function. In TiDB, there will be only one worker which could run ddl statement. So I think may be we do not need get_lock() for schema migration. I pushed a new branch named "**shenli/get-lock**". It parse get_lock/release_lock syntax but do nothing.
Would you please test rails on this experimental branch? Thanks!

**Comment by ziyouchutuwenwu** [comment]
get_lock error not appeared, but other error occured. My steps:
```
rails g model User name:string password:string
rake db:migrate
```

![ar_error](https://cloud.githubusercontent.com/assets/7458713/16764913/c01215f2-4863-11e6-96ec-838b92b87119.png)
![1](https://cloud.githubusercontent.com/assets/7458713/16764914/c23d14c6-4863-11e6-8029-b602a1d90c59.png)
![2](https://cloud.githubusercontent.com/assets/7458713/16764921/c4eb5bc4-4863-11e6-8e64-9daff93c5e17.png)

**Comment by ziyouchutuwenwu** [comment]
here is the migration rb file
```
20160712110144_create_users.rb
```
content
```
class CreateUsers < ActiveRecord::Migration[5.0]
  def change
    create_table :users do |t|
      t.string :name
      t.string :password

      t.timestamps
    end
  end
end
```

here are the exported sql files
```
ar_internal_metadata.sql
```
```
/*
 Navicat Premium Data Transfer

 Source Server         : mysql_local
 Source Server Type    : MySQL
 Source Server Version : 50542
 Source Host           : localhost
 Source Database       : rico_tidb_development

 Target Server Type    : MySQL
 Target Server Version : 50542
 File Encoding         : utf-8

 Date: 07/12/2016 19:15:11 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `ar_internal_metadata`
-- ----------------------------
DROP TABLE IF EXISTS `ar_internal_metadata`;
CREATE TABLE `ar_internal_metadata` (
  `key` varchar(255) NOT NULL,
  `value` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Records of `ar_internal_metadata`
-- ----------------------------
BEGIN;
INSERT INTO `ar_internal_metadata` VALUES ('environment', 'development', '2016-07-12 11:14:19', '2016-07-12 11:14:19');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
```

```
schema_migrations.sql
```
```
/*
 Navicat Premium Data Transfer

 Source Server         : mysql_local
 Source Server Type    : MySQL
 Source Server Version : 50542
 Source Host           : localhost
 Source Database       : rico_tidb_development

 Target Server Type    : MySQL
 Target Server Version : 50542
 File Encoding         : utf-8

 Date: 07/12/2016 19:15:19 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `schema_migrations`
-- ----------------------------
DROP TABLE IF EXISTS `schema_migrations`;
CREATE TABLE `schema_migrations` (
  `version` varchar(255) NOT NULL,
  PRIMARY KEY (`version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- ----------------------------
--  Records of `schema_migrations`
-- ----------------------------
BEGIN;
INSERT INTO `schema_migrations` VALUES ('20160712110144');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
```

```
users.sql
```
```
/*
 Navicat Premium Data Transfer

 Source Server         : mysql_local
 Source Server Type    : MySQL
 Source Server Version : 50542
 Source Host           : localhost
 Source Database       : rico_tidb_development

 Target Server Type    : MySQL
 Target Server Version : 50542
 File Encoding         : utf-8

 Date: 07/12/2016 19:15:26 PM
*/

SET NAMES utf8;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
--  Table structure for `users`
-- ----------------------------
DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `password` varchar(255) DEFAULT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET FOREIGN_KEY_CHECKS = 1;
```

**Comment by shenli** [comment]
@ziyouchutuwenwu Thanks for your information! I get the point. There are a few system tables in information_schema database. TiDB does not support all of them. I will add empty tables to prevent error. I will update the branch latter.

BTW: TiDB does not support foreign key constraint. It is parsed but ignored.

**Comment by ziyouchutuwenwu** [comment]
👍  i will try your new branch later. fk is not necessary for me, i just need it to make active record working.
Thank you!

**Comment by shenli** [comment]
@ziyouchutuwenwu I add a empty table for information_schema.key_column_usage. Please update the branch "shenli/get-lock" and have a try.
Thanks!

**Comment by ziyouchutuwenwu** [comment]
well done! db:migrate works ok, thanks very much!

**Comment by shenli** [comment]
@ziyouchutuwenwu I will merge it to master.
Thanks!
