### ISSUE TITLE
PCP: Vectorize the merge join executor

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14216]
## Description
Currently, the merge join executor in TiDB is row-based, which compares and joins data from its children row by row.
We can vectorize it to let it do the processing group by group like what we do in the stream aggregation executor.
You can use the [`vecGroupChecker`](https://github.com/pingcap/tidb/blob/master/executor/aggregate.go#L952) to find the next group.

## Difficulty

- Medium

## Score

- 3000

## Mentor(s)
 
- @SunRunAway 
- @XuHuaiyu 
- @qw4990 

## Recommended Skills

- Go programming

**Comment by SunRunAway** [comment]
Hi, @catror 
Do you have any ideas or plans to do this PCP, we can make a meeting to discuss it along with @XuHuaiyu and @qw4990 if you have time.

**Comment by catror** [comment]
> Hi, @catror
> Do you have any ideas or plans to do this PCP, we can make a meeting to discuss it along with @XuHuaiyu and @qw4990 if you have time.

I'm busy these days. But I'm almost done with this issue, please expect a PR this weekend.

**Comment by qw4990** [comment]
Hi @catror , thanks for your contribution! 
Do you use Slack? I'd like to discuss this issue with you on Slack more detailly before you open a PR 😺.
