### ISSUE TITLE
FLUSH PRIVILEGES does not privilege check

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#14213]
## Bug Report

1. What did you do?

```
mysql> create user nobody;
Query OK, 0 rows affected (0.37 sec)

mysql> ^DBye
$ mysql -unobody -e 'flush privileges';
```

2. What did you expect to see?

This is an error in MySQL:
```
ERROR 1227 (42000): Access denied; you need (at least one of) the RELOAD privilege(s) for this operation
```

3. What did you see instead?

It worked fine in TiDB. This is not a major issue, but it could lead to excessive memory usage by unprivileged users, or it could possibly be combined with another vulnerability if a user manages to privilege escalate and insert into the mysql.* tables.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-1246-g7f8c3c808
Git Commit Hash: 7f8c3c8083ced5a0d05684c1b55654577896a846
Git Branch: master
UTC Build Time: 2019-12-24 02:06:14
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)
```

**Comment by winoros** [comment]
@tiancaiamao PTAL
