### ISSUE TITLE
Use binary search to group by in Stream Aggregation.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#14215]
All issues are open and welcomed to contributors. You can join **#sig-exec** on [tidb community slack](https://pingcap.com/tidbslack/) to discuss and get help from someone.

## Feature Request

**Is your feature request related to a problem? Please describe:**

During Stream Aggregation, TiDB needs to determine boundaries for a chunk by `group by` keys, which is implemented in [`vecGroupChecker`](https://github.com/pingcap/tidb/blob/a1b90715ee60c0ba0bf3b005b3475e1f931bcfe2/executor/aggregate.go#L952).

**Describe the feature you'd like:**

Now it iterates each entry in a sorted list and determine the boudaries, but we can optimize it using binary seach.

**Describe alternatives you've considered:**

If NDV(number of distinct values) of the input table is not small enough (for example, a 1000 rows table, each row is distinct), binary searching may be less effective than the current implementation, so we may need to benchmark and determine a threshold of NDV, to determine whether to use binary searching or list interating.

**Teachability, Documentation, Adoption, Migration Strategy:**

## Difficulty

* Medium

## Score 

* 1000

## Mentor(s)

* @SunRunAway 

## Recommended Skills

* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by rubb1sh** [comment]
let me complete this feature.

**Comment by krzysztofpioro** [comment]
I'd like to work on this

**Comment by SunRunAway** [comment]
#17077 solves that when `firstRowDatums` are equal to `lastRowDatums` then there is no need to evaluate chunk. 
It extracts getting `firstRowDatums` and `lastRowDatums` from `evalGroupItemsAndResolveGroups` and call  `evalGroupItemsAndResolveGroups` only when `firstGroupKey` is different than `lastGroupKey`.

I think #17077 is enough for performance. So I'm going to close this issue. If someone has a performance benchmark showing that binary search is better than the current implementation. Feel free to comment here.
