### ISSUE TITLE
Insert query failing with error Transaction is too large

### ISSUE THREAD

**Issue by neer1304** [pingcap/tidb#14220]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Trying to create a new table at runtime with around 2 million records 

2. What did you expect to see?
New Table created successfully

3. What did you see instead?
ERROR [http-bio-11301-exec-2] 2019-12-25 at 12:19:54.163 
Application logs -
org.hibernate.engine.jdbc.spi.SqlExceptionHelper:146 logExceptions - Transaction is too large, size: 1073741888
  WARN  [http-bio-11301-exec-2] 2019-12-25 at 12:19:54.167 org.hibernate.engine.jdbc.spi.SqlExceptionHelper$StandardWarningHandler:233 logWarning - Transaction is too large, size: 1073741888
javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: could not execute statement
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1763)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1677)
	at org.hibernate.jpa.spi.AbstractEntityManagerImpl.throwPersistenceException(AbstractEntityManagerImpl.java:1771)
	at org.hibernate.jpa.spi.AbstractQueryImpl.executeUpdate(AbstractQueryImpl.java:87)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v4.0.0-alpha-1234-g2bdd4368d

**Comment by winoros** [comment]
@neer1304 
Yes, we have a limitation of one transaction's size currently. You can refer to docs [中文](https://pingcap.com/docs-cn/stable/reference/transactions/transaction-model/) [English](https://pingcap.com/docs/stable/reference/transactions/transaction-model/).
This limitation is used to be common restriction in NewSQL such as Google Spanner and CockroachDB.
If you're just loading data. You can set variable `tidb_batch_insert`([中文](https://pingcap.com/docs-cn/stable/reference/configuration/tidb-server/tidb-specific-variables/#tidb_batch_insert), [English](https://pingcap.com/docs/stable/reference/configuration/tidb-server/tidb-specific-variables/#tidb_batch_insert)). But you should note that this breaks the atomicity of a transaction.

But yes, we're going to support large transaction. It's developing now and we are going to ship this feature in next year.

**Comment by winoros** [comment]
This is the best practice guide for optimistic transaction in chinese: [乐观事务最佳实践](https://pingcap.com/docs-cn/stable/reference/best-practices/optimistic-transaction/#%E4%B9%90%E8%A7%82%E9%94%81%E4%BA%8B%E5%8A%A1%E6%9C%80%E4%BD%B3%E5%AE%9E%E8%B7%B5).

**Comment by XuHuaiyu** [comment]
Close this issue due to no feedback for a long time.
Feel free to re-open it if you need any further help.
