### ISSUE TITLE
Maybe incorrect const usage in binary json

### ISSUE THREAD

**Issue by Fullstop000** [pingcap/tidb#14247]
In `types/json/binary.go`, we use a well-defined format to encode json object and array:
```
object ::= element-count size key-entry* value-entry* key* value*

array ::= element-count size value-entry* value*
```
So we need to encode the total size after the `element-count`. But in the implementation below, the total data size is encoded after `dataSizeOff` instead of something like `elementCountSize`
https://github.com/pingcap/tidb/blob/7a024a2d25b6034fc2467474a8742201aa2ac1ac/types/json/binary.go#L552-L555
And it seems that because of the same size as the `element-count` and `size` (both are `u32`),  there is no bug by such an implementation.

**Comment by qw4990** [comment]
Close since there is no bug by such an implementation.
