### ISSUE TITLE
when use left join and date_add, the sql exec error

### ISSUE THREAD

**Issue by freyfl** [pingcap/tidb#14277]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
when run the sql in tidb: 
b.date=date_add(a.date,INTERVAL  1 day) and a.date=date_add(b.date,INTERVAL  1 day) has the different results.
![image](https://user-images.githubusercontent.com/48233548/71554411-8a5c9280-2a59-11ea-88a0-ecda18d2af07.png)

2. What did you expect to see?
when run in mysql, there is no error
![image](https://user-images.githubusercontent.com/48233548/71554449-26869980-2a5a-11ea-9a1c-1eaf8172412d.png)

3. What did you see instead?
the table is
create table t1 (id int,date datetime,name varchar(50));
create table t2 (id int,date datetime,name varchar(50));
create table t3 (id int,date datetime,name varchar(50));
create table t4 (id int,date datetime,name varchar(50));
create table t5 (id int,date datetime,name varchar(50));

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v3.0.0

**Comment by AilinKid** [comment]
Thanks for reminding us, we found it fixed with PR #11160. The phenomenon above will behaviors normal in master now and release-3.0.2.

**Comment by freyfl** [comment]
thank you, it is already fixed
