### ISSUE TITLE
Check field length when doing DDL.

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1431]
--error ER_TOO_BIG_FIELDLENGTH
CREATE TABLE b15776 (a char(4294967295));

"M × w bytes, 0 <= M <= 255, where w is the number of bytes required for the maximum-length character in the character set. See Section 15.8.3, “Physical Row Structure of InnoDB Tables” for information about CHAR data type storage requirements for InnoDB tables."
See: http://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html

**Comment by morgo** [comment]
I believe this has been fixed:
```
MySQL [test]> CREATE TABLE b15776 (a char(4294967295));
ERROR 1074 (42000): Column length too big for column 'a' (max = 255); use BLOB or TEXT instead
```

I am going to close this issue now.  Please feel free to re-open it if you have any questions.  Thanks!
