### ISSUE TITLE
inconsistent result with push-down to mocktikv or not

### ISSUE THREAD

**Issue by lonng** [pingcap/tidb#14326]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

1. Open the switcher make the cast string as real push down. (https://github.com/tikv/tikv/pull/6390)
2. Imports the test data `https://github.com/tikv/copr-test/blob/master/push-down-test/prepare/0_data.sql`
3. Executes the query `SELECT PI( ) AS field1 FROM `table10_int_autoinc` WHERE NULL + ( POW( 7270, `col_varchar_64` ) ) /* QNO 1681 CON_ID 204 */` in following mode will obtain the different result.
    - GO_FAILPOINTS="github.com/pingcap/tidb/expression/PushDownTestSwitcher=return(\"\");github.com/pingcap/tidb/expression/PanicIfPbCodeUnspecified=return(true)"
 - GO_FAILPOINTS=""

2. What did you expect to see?

The same result.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v4.0.0-alpha-1301-g044bc2c16-dirty
Git Commit Hash: 044bc2c16a51a524840cc4fb03701593b5efa5a8
Git Branch: open-cast-string-real
UTC Build Time: 2020-01-03 03:14:36
GoVersion: go1.13.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by nullnotnil** [comment]
This appears to be fixed by https://github.com/pingcap/tidb/pull/14323

@lonng can we close this issue?
