### ISSUE TITLE
Reduce the memory usage of InsertExec/ UpdateExec

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#14355]
## Description
InsertExec consumes too much memory space during execution. We can compare the memory usage between `InsertSelect` and `Insert` from the following steps.

Step1: 
``` sql
CREATE TABLE `t` (
  `a` bigint(20) DEFAULT NULL,
  `b` bigint(20) DEFAULT NULL,
  `c` bigint(20) DEFAULT NULL,
  `d` bigint(20) DEFAULT NULL,
  `e` bigint(20) DEFAULT NULL,
  `f` bigint(20) DEFAULT NULL,
  `g` bigint(20) DEFAULT NULL,
  `h` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

CREATE TABLE `t1` (
  `a` bigint(20) DEFAULT NULL,
  `b` bigint(20) DEFAULT NULL,
  `c` bigint(20) DEFAULT NULL,
  `d` bigint(20) DEFAULT NULL,
  `e` bigint(20) DEFAULT NULL,
  `f` bigint(20) DEFAULT NULL,
  `g` bigint(20) DEFAULT NULL,
  `h` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

CREATE TABLE `t2` (
  `a` bigint(20) DEFAULT NULL,
  `b` bigint(20) DEFAULT NULL,
  `c` bigint(20) DEFAULT NULL,
  `d` bigint(20) DEFAULT NULL,
  `e` bigint(20) DEFAULT NULL,
  `f` bigint(20) DEFAULT NULL,
  `g` bigint(20) DEFAULT NULL,
  `h` bigint(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

Step 2:
``` 
insert ~500,000 tuples into table t
```

Step 3:
``` 
insert into t1 select * from t;
insert into t2 values ( 500,000 rows);
```

Step 4:

Check the memory usage of TiDB in grafana:
![insert_memory](https://user-images.githubusercontent.com/9039012/71804115-7ccc8b80-309d-11ea-8129-aac14f76f8c3.png)

We can see from the Grafana that `Insert` uses much more memory space than `InsertSelect`.
A difference between the implementation of `InsertSelect` and `Insert` is that `InsertSelect` [handles a batch of tuples every time](https://github.com/pingcap/tidb/blob/master/executor/insert_common.go#L409-L455), while `Insert` buffers all the tuples in memory and [handles the whole tuples at the end](https://github.com/pingcap/tidb/blob/master/executor/insert_common.go#L220-L262).

~We can reduce the memory usage of `InsertExec` refer to the implementation of `InsertSelect`.~  refer: https://github.com/pingcap/tidb/pull/14568#issuecomment-585125315

~`UpdateExec` can also be optimized using the same approach.~

## Difficulty

- Medium

## Score

- 1000

## Mentor(s)
 
- @XuHuaiyu 
- @SunRunAway 
- @qw4990 

## Recommended Skills

- Go programming

**Comment by b41sh** [comment]
I'd like to do this issue, and I will finish [tikv/tikv#5702](https://github.com/tikv/tikv/issues/5702) ASAP

**Comment by jackysp** [comment]
The memory usage of `insert select` statement is optimized in https://github.com/pingcap/tidb/pull/13815.

**Comment by XuHuaiyu** [comment]
@jackysp 
The PR optimized `insertRowsFromSelect`, `insertRows` can also be optimized using the same way.

**Comment by XuHuaiyu** [comment]
Note:
According to [this comment](https://github.com/pingcap/tidb/pull/14568#issuecomment-585125315), the memory usage can not be optimized using the way mentioned in the description.

**Comment by XuHuaiyu** [comment]
I bench the heap usage of:
``` sql
TiDB(root@127.0.0.1:test) > update t1 set a = 1;
Query OK, 300000 rows affected (9.93 sec)
Rows matched: 300000  Changed: 300000  Warnings: 0
```

The memory consumption of the `CloneRow` may be reduced:
```
(pprof) top
Showing nodes accounting for 478.35MB, 97.05% of 492.88MB total
Dropped 52 nodes (cum <= 2.46MB)
Showing top 10 nodes out of 73
      flat  flat%   sum%        cum   cum%
  145.57MB 29.53% 29.53%   145.57MB 29.53%  github.com/pingcap/tidb/types.CloneRow
  144.57MB 29.33% 58.87%   144.57MB 29.33%  github.com/pingcap/tidb/util/chunk.Row.GetDatumRow
      96MB 19.48% 78.34%       96MB 19.48%  github.com/pingcap/tidb/store/tikv/latch.NewLatches
   36.78MB  7.46% 85.81%    36.78MB  7.46%  github.com/pingcap/tidb/kv/memdb.newArenaBlock
   13.88MB  2.82% 88.62%   304.02MB 61.68%  github.com/pingcap/tidb/executor.(*UpdateExec).fetchChunkRows
   13.55MB  2.75% 91.37%    13.55MB  2.75%  github.com/pingcap/tidb/session.(*session).StmtAddDirtyTableOP
   11.50MB  2.33% 93.71%    11.50MB  2.33%  github.com/pingcap/tidb/store/tikv/latch.(*Latches).acquireSlot
    5.84MB  1.19% 94.89%    61.18MB 12.41%  github.com/pingcap/tidb/executor.(*UpdateExec).exec
    5.50MB  1.12% 96.01%     5.50MB  1.12%  github.com/pingcap/tidb/store/tikv/latch.(*Latches).releaseSlot
    5.16MB  1.05% 97.05%     5.16MB  1.05%  github.com/pingcap/tidb/server.(*packetIO).readOnePacket
```

@b41sh is working on this.

**Comment by XuHuaiyu** [comment]
related PR: https://github.com/pingcap/tidb/pull/15325

**Comment by XuHuaiyu** [comment]
related PR: https://github.com/pingcap/tidb/pull/15362
