### ISSUE TITLE
docker-compose部署tidb无法停止

### ISSUE THREAD

**Issue by debugsw** [pingcap/tidb#14350]
使用 docker-compose部署tidb后，再次使用 docker-compose down无法关闭，报错ERROR: error while removing network: network tidb-docker-compose_default id a082ab0edf30c062f40d2da70152883a9e9e91694bd9abcb1e21c6448d34caa3 has active endpoints

**Comment by qw4990** [comment]
@debugsw Sorry for my late reply and thanks for your feedback.
I guess this is a deploy or environment problem, so it's better to report this problem in our [user group forum](https://asktug.com/), thanks for your understanding ~

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
