### ISSUE TITLE
tidb seems not support mycli (a python tool)

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [pingcap/tidb#1436]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
```
go version go1.6.2 darwin/amd64
```

2. What operating system and processor architecture are you using (`go env`)?
```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/mmc/dev/golang/3rdLibs:/Users/mmc/dev/golang/myApps"
GORACE=""
GOROOT="/Users/mmc/dev/golang/go"
GOTOOLDIR="/Users/mmc/dev/golang/go/pkg/tool/darwin_amd64"
GO15VENDOREXPERIMENT="1"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

3. What did you do?
```
mycli -h 127.0.0.1 -P 4000 -u root
```

4. What did you expect to see?
![ok](https://cloud.githubusercontent.com/assets/7458713/16772684/c81b2738-4887-11e6-9e99-69ba78c1ba5a.png)

5. What did you see instead?
![error](https://cloud.githubusercontent.com/assets/7458713/16772691/ce728cb6-4887-11e6-9e7f-9b7e7b8278f2.png)

mycli was very helpful, will tidb make support of it?

**Comment by shenli** [comment]
@ziyouchutuwenwu Thanks for your report!
Seems mycli try to access table mysql.help_topic. I wil figure out if we could provide that table.

**Comment by ziyouchutuwenwu** [comment]
wonderful! 
mycli works! 
Thank you very much!

**Comment by shenli** [comment]
@ziyouchutuwenwu Great to hear that! I will create a PR.
