### ISSUE TITLE
The Scan and ReverseScan method of rawkv client can't respond rightly

### ISSUE THREAD

**Issue by ldnvnbl** [pingcap/tidb#14363]
## Bug Report

1. What did you do?

I used the rawkv client in my program, when I scan something,  it does not respond to me, even waiting a long time.

The pkg path:

```
github.com/pingcap/tidb/store/tikv
```

Problem functions

```go
func (c *RawKVClient) Scan(startKey, endKey []byte, limit int) {}
func (c *RawKVClient) ReverseScan(startKey, endKey []byte, limit int) {}
```

2. What did you expect to see?

The scan method not respond to me, It was stuck.

3. What did you see instead?

Respond success.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
github.com/pingcap/tidb/store/tikv@84e4386
```

**Comment by ldnvnbl** [comment]
I debugged it and  found the loop in scan method not break, even startKey > endKey

**Comment by qw4990** [comment]
@ldnvnbl Thanks for your feedback and your PR!
