### ISSUE TITLE
ipv4地址监听问题

### ISSUE THREAD

**Issue by snakeh36** [pingcap/tidb#14371]
https://asktug.com/t/topic/2403

**Comment by qw4990** [comment]
@snakeh36 Thanks for your feedback.
According to the discussion in [topic/2403](https://asktug.com/t/topic/2403), it seems your problem has been solved, so could we close this issue now?

**Comment by qw4990** [comment]
According to the discussion on the TUG forum, it seems this problem has been solved, so I will close this issue now.
