### ISSUE TITLE
Count the number of hash table collisions and failures during Hash Join.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#14387]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently we use native [FNV](https://golang.org/pkg/hash/fnv/#New64) to build hash table. We need measure whether the hash function is effective with real dataset.

**Describe the feature you'd like:**

I propose to add three metrics into `explain analyze` result in each hash join.
1. Count of hash collisions when probing, which means we do extra scans for hashed values.
2. Count of hash failures when probing, which means we do unused scans for hashed values and keys when hash key is not matched.
3. Time cost to finish building hash table in a single goroutine.

After that, we can evaluate whether the hash function we currently used is suitable and can do experiments for other hash functions.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by wangyi-fudan** [comment]
just mention wyhash, the fastest high quality conventional hash function.
https://github.com/wangyi-fudan/wyhash

**Comment by zz-jason** [comment]
> just mention wyhash, the fastest high quality conventional hash function.
> [wangyi-fudan/wyhash](https://github.com/wangyi-fudan/wyhash)

@wangyi-fudan Thanks, we'll take a look!
