### ISSUE TITLE
70% performance regression on wide_table_200 and 4%  regression on TPCC workload

### ISSUE THREAD

**Issue by mahjonp** [pingcap/tidb#14432]
## Performance Questions

- What version of TiDB are you using?

9563ec77e48b4d7f974a799641809cf31e944a4c

- What's the observed and your expected performance respectively?

compare with: b9091b0ce2abc4da55610f35ff66edbc0e229cdc

```
# TPCC
Measured tpmC (NewOrders): 23924.50 ± 1.85% (std=266.44), delta: -4.10% (p=0.001)

# wide_table_200

workload: <wide_point_select>

tidb_max_cpu: 5.10, delta: -73.13%
tikv_max_cpu: 2.45, delta: -64.16%
tidb_max_memory: 302.94 MiB, delta: -23.73%
tikv_max_memory: 12228.06 MiB, delta: -14.49%

tps : 14130.40 ± 0.2713% (std=24.35) delta: -76.09%
qps : 14130.40 ± 0.2713% (std=24.35) delta: -76.09%
lat_avg : 18.11 ± 0.2853% (std=0.03) delta: 318.28%
lat_99th : 38.48 ± 1.1954% (std=0.33) delta: 218.54%

```

- Have you compared TiDB with other databases? If yes, what's their difference?

None.

As mentioned at #14369: "there may exist possible performance regression", we found that there exist a 70% performance regression on wide_point_select of wide_table_200 and 4% performance regression on TPCC workload and the other one inner workloads.

## How to reproduce

for wide table, you can refer to https://github.com/siddontang/dbbench/tree/master/sysbench/wide to prepare data and run benchmark.

**Comment by djshow832** [comment]
It's because each plan is different in point get, and it's fixed in PR https://github.com/pingcap/tidb/pull/14471.

**Comment by djshow832** [comment]
Another reason is because there're too many kinds of summaries to fit in the cache, and creating a new summary needs to lock the cache, so much time is spent on waiting for the lock.
It's fixed in PR https://github.com/pingcap/tidb/pull/14490.
