### ISSUE TITLE
Can't read from some information_schema tables when cascades planner is enabled

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#14447]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Not a big deal, but wanted to file a bug so you can track it:

```
mysql> set tidb_enable_cascades_planner = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from information_schema.slow_query;
ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
```

This is also the case for information_schema.processlist. cluster_processlist and cluster_slow_query return zero results which is worse / inconsistent.

2. What did you expect to see?

Query should succeed.

3. What did you see instead?

Error or no results.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-1334-g07e642c92
Git Commit Hash: 07e642c9230ccb7c1537b27442f1fe8433e65f8a
Git Branch: master
UTC Build Time: 2020-01-08 08:32:04
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

```

**Comment by wwar** [comment]
Certain diagnostics commands also fail, like  `ADMIN SHOW DDL JOBS`.

**Comment by zz-jason** [comment]
The cascades planner is under development now, you can see the progress through this project: [cascades planner](https://github.com/pingcap/tidb/projects/16). Not generally available yet.

Please turn it off to test or use TiDB.
