### ISSUE TITLE
Investigate and propose parallel sort-merge join

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14441]
## Description

In this PR(https://github.com/pingcap/tidb/pull/14238), we introduce the shuffle executor.
We may use this shuffle executor to implement the parallel sort-merge join by nesting some sort and merge-join executors into a shuffle executor:
```
ShuffleExec
    - MergeJoinExec
        - SortExec
    - MergeJoinExec
        - SortExec
    ...
``` 

Compared with the hash-join we implement now, whose building phase is not parallel, it may utilize more CPU resources to get better performance.

- [x] Modify the original `shuffle` to let it support multiple `datasources` and pass all existed tests
- [x] Introduce a new variable to control concurrency of `merge_join`
- [x] Support `shuffle + merge_join`
- [ ] Add some correct tests and benchmarks about `shuffle + merge_join`

## Score

6600

## Mentor

@qw4990 (Slack ID: Zhang Yuanjia)

## Recommend Skills

- Golang

**Comment by hftsin** [comment]
@qw4990 can you add a `challenge-program` label to this issue?
