### ISSUE TITLE
ANALYZE TABLE fails on json-extracted virtual column

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#14455]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

This is the example from https://pingcap.com/docs/stable/reference/sql/generated-columns/ -- with the generated column changed to VIRTUAL, since this should now work.

```
DROP TABLE IF EXISTS person;
CREATE TABLE person (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address_info JSON,
    city VARCHAR(64) AS (JSON_UNQUOTE(JSON_EXTRACT(address_info, '$.city'))) VIRTUAL,
    KEY (city)
);

INSERT INTO person (name, address_info) VALUES ('wwar', JSON_OBJECT('city', 'Chicago'));

mysql> ANALYZE TABLE person;
ERROR 1105 (HY000): invalid encoded key
```

2. What did you expect to see?

This should not be an error.

3. What did you see instead?

See above.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-1334-g07e642c92
Git Commit Hash: 07e642c9230ccb7c1537b27442f1fe8433e65f8a
Git Branch: master
UTC Build Time: 2020-01-08 08:32:04
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by bb7133** [comment]
I planned to put this issue to Milestone 3.0.10, is it OK for you? @lamxTyler

**Comment by lamxTyler** [comment]
@wwar I cannot reproduce it on my local machine with this version and the latest version. Can you provide the detailed logs of tidb? If you are using deploy tidb with tikv, please also provide the tikv version.

**Comment by lamxTyler** [comment]
@bb7133 Let me first find the root cause first.

**Comment by wwar** [comment]
I can no longer reproduce on the latest either. It looks like it was fixed:
```
mysql> ANALYZE TABLE person;
Query OK, 0 rows affected (0.20 sec)

mysql> SELECT version()\G
*************************** 1. row ***************************
version(): 5.7.25-TiDB-v4.0.0-alpha-1369-ge39b50417
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-1369-ge39b50417
Git Commit Hash: e39b504177da2efee6a8981b31c45ac775c03612
Git Branch: master
UTC Build Time: 2020-01-15 11:45:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by wwar** [comment]
I will clarify that it was not a transient error when I reproduced it last time (it failed several times in a row). I think we can close this issue, I will re-open if I manage to reproduce again.
