### ISSUE TITLE
Questions about add index performance

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#14454]
## Performance Questions

- What version of TiDB are you using?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-alpha-1334-g07e642c92
Git Commit Hash: 07e642c9230ccb7c1537b27442f1fe8433e65f8a
Git Branch: master
UTC Build Time: 2020-01-08 08:32:04
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

Hardware:
8 core (16 thread), 64GiB RAM, NVMe storage

## Question

I have been casually comparing performance between TiDB and MySQL 8 (on a single server, so some skew). First off, I am quite happy with the import speed of [LOAD DATA](https://pingcap.com/docs/stable/how-to/get-started/import-example-database/) in TiDB. It looks to be greatly improved from earlier versions:
```
$ time import-bikeshare-tidb 
real	2m51.036s
user	0m0.643s
sys	0m1.627s

$  time import-bikeshare-mysql
real	1m35.188s
user	0m0.847s
sys	0m1.997s
```
The workload is still in memory, which is a case where InnoDB should be winning. To be within 2x is good enough for now.

But for my next step, I tried adding an index:
```
mysql8> ALTER TABLE trips ADD INDEX (start_date);
Query OK, 0 rows affected (30.10 sec)
Records: 0  Duplicates: 0  Warnings: 0

tidb> ALTER TABLE trips ADD INDEX (start_date);
Query OK, 0 rows affected (23 min 13.38 sec)
```
TiDB is ~50x worse by default :( I can tune it to get a lot of performance back:
```
SET GLOBAL tidb_ddl_reorg_batch_size = 10240;
SET GLOBAL tidb_ddl_reorg_worker_cnt = 32;

tidb> ALTER TABLE trips ADD INDEX (start_date);
Query OK, 0 rows affected (2 min 51.78 sec)
```

That is better! Side note, the documentation is incorrect about the defaults: https://github.com/pingcap/docs/issues/1764

It does not seem reasonable that with defaults, adding the index would take ~10x what loading the full data set again takes. My first question is, can the defaults be changed for `tidb_ddl_reorg_batch_size` and `tidb_ddl_reorg_worker_cnt`?

My second question is, do you have planned any of the optimizations that MySQL is doing here? I know the architecture of TiDB is different, so I am not sure how many apply:

- Is it possible to disable the REDO log during the creation of index pages? Or even the raft log (and then batch copy as a final phase)?
- Is it possible to push more of this down to the coprocessor? MySQL essentially lets InnoDB handle this.

**Comment by bb7133** [comment]
Thank you for reporting! The documents are wrong and it will be fixed soon.

About the optimization, there was a plan in TiDB performance challenge program: https://github.com/pingcap/tidb/issues/12963 , it would be great if you're interested in the challenge :)

**Comment by reafans** [comment]
Thank you for your suggestion！

For the frist question，the defaults value for `tidb_ddl_reorg_batch_size` and `tidb_ddl_reorg_worker_cnt` can be changed. We can make it auto adjust to the current load or other condition.

For the second question, due to the different architecture between TiDB and MySQL, we can only push some operations down to TiKV as a new Coprocessor task. 

And there are some other method to Improve the performance of `CREATE INDEX` like pre-split index regions, [#9537](https://github.com/pingcap/tidb/pull/9537) and so on. I plan to do this improvement [#12963](https://github.com/pingcap/tidb/issues/12963) in the near future, it would be better if you could join me, And I can give you some advice for the progress.

**Comment by wwar** [comment]
> About the optimization, there was a plan in TiDB performance challenge program: #12963 , it would be great if you're interested in the challenge :)

I'm sorry, I can't contribute code under CLA right now. But I am happy to follow along and report feedback :-) It is great to see you are working on this, thanks for pointing the issue out!

**Comment by wwar** [comment]
An update on the current performance numbers.

With defaults (different host, this one has faster CPUs but actually slower SATA storage):
```
tidb> ALTER TABLE trips ADD INDEX (start_date);
Query OK, 0 rows affected (6 min 44.42 sec)
```

With `tidb_ddl_reorg_batch_size=10240` and `tidb_ddl_reorg_worker_cnt=32`:

```
tidb> ALTER TABLE trips ADD INDEX (start_date);
Query OK, 0 rows affected (3 min 29.34 sec)
```

So it looks much better. There is a 2x discrepancy to optimizing values, not a 10x.

**Comment by lance6716** [comment]
close it due to questions are answered
