### ISSUE TITLE
Use select for update to find the same data under pessimistic transactions

### ISSUE THREAD

**Issue by liuhuanHappyStudy** [pingcap/tidb#14462]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Use **go language** to test the function of account withdrawal.
process:
-- Do the following for the same account:
```
Start transaction
1> select current_bal, v from act_balance where sub_acct_no = 'xxx' limit 1 for update; #v is the balance version
2> Update the balance and version information in the act_balance table
3> Insert flow information into the tables act_withdraw, act_account_hold, act_account_change, each table.
commit
```

Pressure test operation:
50 threads, pressure test 600 seconds
Pressure test results:
97%+ of withdrawal operations failed.

**tidb.log：**There is a lot of information in the log, as follows. 
```
[2020/01/13 10:54:31.236 +08:00] [INFO] [adapter.go:506] ["pessimistic write conflict, retry statement"] [conn=18084] [txn=413894985859727368] [forUpdateTS=413894985899048965] [conflictCommitTS=413894985938370561]
```

2. What did you expect to see?
Step 1: At any one time, only one thread can obtain the balance and version information, and the other threads are waiting.

3. What did you see instead?
 There are many threads that get the same balance and version information.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
> select tidb_version();
Release Version: v3.0.8
Git Commit Hash: 8f13cf1449bd8903ff465a4f12ed89ecbac858a4
Git Branch: HEAD
UTC Build Time: 2019-12-31 11:14:59
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by XuHuaiyu** [comment]
@liuhuanHappyStudy 

1. Do Step 2 update the balance and version information of the same account specified in step1?
2. I do not understand what does step 3 mean, can you explain it a little bit more?

**Comment by liuhuanHappyStudy** [comment]
> @liuhuanHappyStudy
> 
> 1. Do Step 2 update the balance and version information of the same account specified in step1?
Reply：
Yes! All operations are performed on the same account.
> 2. I do not understand what does step 3 mean, can you explain it a little bit more?
Reply：
 step 3：For tables: act_withdraw, act_account_hold, act_account_change, each table inserts a record to record the withdrawal information.
Thank you very much for your reply!
@XuHuaiyu

**Comment by tiancaiamao** [comment]
Hi, @liuhuanHappyStudy
If the `sub_acct_no` has no index, the first step query would not the lock data as we do not support the gap lock.

Could you post the result of this query?

```
explain select current_bal, v from act_balance where sub_acct_no = 'xxx' limit 1 for update;
```

**Comment by liuhuanHappyStudy** [comment]
> sub_acct_no
After increasing the index on the sub_acct_no column and setting it to not null, the above problem was solved. Thank you very much! @tiancaiamao
