### ISSUE TITLE
tidbv3.0.8, sequel pro Cannot open table structure on MAC 

### ISSUE THREAD

**Issue by liuhuanHappyStudy** [pingcap/tidb#14463]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
TiDB is rollingly upgraded from version v3.0.4 to v3.0.8. Sequel Pro on MAC cannot directly view the table structure. You can use the command: show create table tablename to view the table structure. It can be viewed normally in version v3.0.4. Both SQLyog and Navicat on the window can operate normally before and after the upgrade.

exactly:
In version v3.0.8, Sequel Pro has a small number of tables that can be viewed by the Structure button. Most of the tables are consistently stuck on the Loading page.

2. What did you expect to see?
In the Sequel Pro management interface, select the table and click Structure to view the table structure and edit it.

3. What did you see instead?
When you click the Structure button, Sequel Pro consistently stuck on the Loading interface.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.8
Git Commit Hash: 8f13cf1449bd8903ff465a4f12ed89ecbac858a4
Git Branch: HEAD
UTC Build Time: 2019-12-31 11:14:59
GoVersion: go version go1.13 linux/amd64
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by XuHuaiyu** [comment]
Can you provide some screenshots for this problem to make it more understandable?

**Comment by liuhuanHappyStudy** [comment]
@XuHuaiyu Thank you very much for your reply!
It is a problem with the character set in the table. I changed utf8 to utf8mb4 in the table, and then sequel pro can work normally.
