### ISSUE TITLE
Support the JSON function `JSON_STORAGE_SIZE`

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14488]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Support the JSON function `JSON_STORAGE_SIZE`.
In MySQL:
```
mysql> CREATE TABLE jtable (jcol JSON);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO jtable VALUES  ('{"a": 1000, "b": "wxyz", "c": "[1, 3, 5, 7]"}');
Query OK, 1 row affected (0.00 sec)

mysql> select jcol, JSON_STORAGE_SIZE(jcol) as size from jtable;
+-----------------------------------------------+------+
| jcol                                          | size |
+-----------------------------------------------+------+
| {"a": 1000, "b": "wxyz", "c": "[1, 3, 5, 7]"} |   47 |
+-----------------------------------------------+------+
```

In TiDB:
```
mysql> CREATE TABLE jtable (jcol JSON);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO jtable VALUES  ('{"a": 1000, "b": "wxyz", "c": "[1, 3, 5, 7]"}');
Query OK, 1 row affected (0.00 sec)

mysql> select jcol, JSON_STORAGE_SIZE(jcol) as size from jtable;
ERROR 1305 (42000): FUNCTION JSON_STORAGE_SIZE does not exist
```

**Comment by francis0407** [comment]
What are the first three characters of the issue title? In my Chrome, the title `Support the JSON function `JSON_STORAGE_SIZE`. Is it expected?
`

**Comment by qw4990** [comment]
> What are the first three characters of the issue title? In my Chrome, the title is
> ![image](https://user-images.githubusercontent.com/25431723/72677059-2fa3dd00-3ad3-11ea-9480-180357f45a1d.png)
> . Is it expected?
> `

Is it ok now? In my Chrome is show nothing before `Support...`.

**Comment by francis0407** [comment]
It's OK now.

**Comment by stoksc** [comment]
Is anyone working on this? I could take a shot.
