### ISSUE TITLE
SELECT tidb_version() should list tikv and pd versions

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#14487]
## Feature Request

**Describe the feature you'd like:**

In a couple of bug reports I've been asked the tikv and pd versions. I know TiDB knows them, since they are in `information_schema`. It would help out the quality of bug reports if they could be included in `tidb_version()`.

If there are discrepancies, you might want to show a list of all versions encountered.

**Describe alternatives you've considered:**

The alternative is to ask for more commands to be run in the bug report request. But that takes more work on users.

You could also ask for something from the new diagnostics frameworks, but I have worked for companies that consider instance counts + hostnames proprietary information, and would likely not share all the data this collects in public. A slightly extended `tidb_version()` function seems like a good balance.

**Teachability, Documentation, Adoption, Migration Strategy:**

Should be straight forward.

**Comment by scsldb** [comment]
Maybe we need to add TiFlash、TiCDC

**Comment by zz-jason** [comment]
> It would help out the quality of bug reports if they could be included in tidb_version()

We can achieve this by `information_schema.cluster_info` table, is it still need to enhance the `tidb_version()` function?

An example:

```sql
TiDB(root@127.0.0.1:test) > select * from information_schema.cluster_info;
+------+----------------------+----------------------+--------------+------------------------------------------+---------------------------+---------------------+
| TYPE | INSTANCE             | STATUS_ADDRESS       | VERSION      | GIT_HASH                                 | START_TIME                | UPTIME              |
+------+----------------------+----------------------+--------------+------------------------------------------+---------------------------+---------------------+
| tidb | 192.168.56.103:4000  | 192.168.56.103:10080 | 4.0.0-beta.2 | b2922a70987e0b3a9b5e1392375af156162de346 | 2020-07-20T20:43:39+08:00 | 20h39m0.46296187s   |
| pd   | 192.168.56.103:2379  | 192.168.56.103:2379  | 4.1.0-alpha  | d9bd722fd81413c46d1d63b6d03e7b9e4e3543ec | 2020-07-20T20:38:08+08:00 | 20h44m31.462966059s |
| tikv | 192.168.56.103:20160 | 192.168.56.103:20180 | 4.1.0-alpha  | 22a94c81211d805c5938b0812482fa63e6696558 | 2020-07-20T20:43:28+08:00 | 20h39m11.462967853s |
+------+----------------------+----------------------+--------------+------------------------------------------+---------------------------+---------------------+
3 rows in set (0.00 sec)
```

**Comment by nullnotnil** [comment]
It is important to trim the hostnames and anything that directly reveals server count. So something like:
```sql
mysql> SELECT type AS component, group_concat(DISTINCT concat(version, ':', git_hash)) AS versions FROM information_schema.cluster_info GROUP BY type;
+-----------+-------------------------------------------------------+
| component | versions                                              |
+-----------+-------------------------------------------------------+
| tidb      | 4.0.0-beta.2:824df767559b8544af0cb71509135d322de1cd47 |
| pd        | 4.1.0-alpha:082217c47f164f0f471051bafa7991064e614356  |
| tikv      | 4.1.0-alpha:d51ef93cec1a0be7fd168d743ba108a9c79b426f  |
+-----------+-------------------------------------------------------+
3 rows in set (0.00 sec)
```

**Comment by zz-jason** [comment]
How about making `select tidb_version();` to display the same result of the following query:

```sql
SELECT type AS component,	
       concat(version, ':', git_hash) AS version,
       count(*) as instances
FROM information_schema.cluster_info
GROUP BY type, concat(version, ':', git_hash);
```

If there are different versions on a component, the result would not be too long to be displayed in a single line, it also summarizes the instance count of that version:

```
+-----------+-------------------------------------------------------+-----------+
| component | version                                               | instances |
+-----------+-------------------------------------------------------+-----------+
| pd        | 4.1.0-alpha:d9bd722fd81413c46d1d63b6d03e7b9e4e3543ec  |         1 |
| tidb      | 4.0.0-beta.2:b2922a70987e0b3a9b5e1392375af156162de346 |         1 |
| tikv      | 4.1.0-alpha:22a94c81211d805c5938b0812482fa63e6696558  |         1 |
+-----------+-------------------------------------------------------+-----------+
3 rows in set (0.00 sec)
```

**Comment by nullnotnil** [comment]
Per the alternatives considered:

> .. I have worked for companies that consider instance counts + hostnames proprietary information, and would likely not share all the data this collects in public.

I think it is better to leave this info out.

**Comment by zz-jason** [comment]
> Per the alternatives considered:
> 
> > .. I have worked for companies that consider instance counts + hostnames proprietary information, and would likely not share all the data this collects in public.
> 
> I think it is better to leave this info out.

Got it. Leave the instance count and hostnames out of the result looks good to me.

**Comment by breeswish** [comment]
Notice that it might be quite challenge for a function to return multiple datums. How about using some other syntax, like `SHOW CLUSTER VERSIONS`? Additionally I think it would be better *not* to put version and git hash together. It avoids confusing our users, although putting them together is more technically correct.

**Comment by nullnotnil** [comment]
> Notice that it might be quite challenge for a function to return multiple datums. How about using some other syntax, like `SHOW CLUSTER VERSIONS`? Additionally I think it would be better _not_ to put version and git hash together. It avoids confusing our users, although putting them together is more technically correct.

I think it is fine to truncate after 3 versions. The goal of having it in `select tidb_version()` is to simplify the bug reporting procedure. If there is another command, that makes it slightly harder.
