### ISSUE TITLE
Can binlog send data to rocketmq no to fakaf

### ISSUE THREAD

**Issue by loveichong** [pingcap/tidb#14493]
hello, im a architect from xiame,Chian. 
tidb  is  such a  good  database and i lovce it so much
Our company use it currently.
But now i want to use tidb binlog to send data to rocketmq no to kafak.
Can this thing be happen ?
What shuold i do if it can?

**Comment by XuHuaiyu** [comment]
PTAL
@WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
drainer support  send binlog to kafka, you can read the document https://pingcap.com/docs-cn/stable/reference/tidb-binlog/deploy/, search `db-type`

**Comment by WangXiangUSTC** [comment]
I close this issue now, you can reopen it if have other questions. @loveichong
