### ISSUE TITLE
support modify field type length reduction

### ISSUE THREAD

**Issue by melin** [pingcap/tidb#14492]
mysql 数据通过otter 同步到tidb，如果mysql中修改表字段长度大小，tidb 不支持字段长度往小的修改，导致同步失败。mysql 限制index 长度大小，开始创建表的时候varchar 设置的比较大，后面需要添加索引，重新调整varchar 长度，或者从text修改varchar。这种场景比较多

**Comment by bb7133** [comment]
Hi @melin , thanks for reporting!

This feature is actually the support of "full column type change", and it is in the roadmap of our 2020.

**Comment by bb7133** [comment]
By the way, would you please rename the title to English? Thank you.

**Comment by nullnotnil** [comment]
I am going to close this as a duplicate since it is a subset of https://github.com/pingcap/tidb/issues/18283

Please feel free to re-open if you have any additional questions. Thanks!
