### ISSUE TITLE
Add `show table $table_name next_row_id` syntax

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#14567]
## Feature Request

Add `show table $table_name next_row_id` to get the next global table row id. 

**Is your feature request related to a problem? Please describe:**

Currently, TiDB has `admin show $table_name next_row_id` to get the next global table row id. 

But `admin show` syntax needs the `super` privilege. Getting the `next_row_id` no need to use `super` privilege, only use `SELECT` privilege will be ok. We can add `show $table_name next_row_id` syntax to get `next_row_id`.

**Describe the feature you'd like:**

```sql
test> show table test.t next_row_id;
+---------+------------+-------------+--------------------+
| DB_NAME | TABLE_NAME | COLUMN_NAME | NEXT_GLOBAL_ROW_ID |
+---------+------------+-------------+--------------------+
| test    | t          | _tidb_rowid | 30001              |
+---------+------------+-------------+--------------------+
```

**Teachability, Documentation, Adoption, Migration Strategy:**

For compatibility, we can't remove `admin show $table_name next_row_id` soon.

**Comment by zhang555** [comment]
I want solve this issue , but I have a problem . 

For add  `show $table_name next_row_id` syntax , I edit `parser.y` file .


before my edit : 
```
ShowStmt:
	"SHOW" ShowTargetFilterable ShowLikeOrWhereOpt
	{
		stmt := $2.(*ast.ShowStmt)
		if $3 != nil {
			if x, ok := $3.(*ast.PatternLikeExpr); ok && x.Expr == nil {
				stmt.Pattern = x
			} else {
				stmt.Where = $3.(ast.ExprNode)
			}
		}
		$$ = stmt
	}
|	"SHOW" "CREATE" "TABLE" TableName
	{
		$$ = &ast.ShowStmt{
			Tp:    ast.ShowCreateTable,
			Table: $4.(*ast.TableName),
		}
	}
```

after my edit :
```
ShowStmt:
	"SHOW" ShowTargetFilterable ShowLikeOrWhereOpt
	{
		stmt := $2.(*ast.ShowStmt)
		if $3 != nil {
			if x, ok := $3.(*ast.PatternLikeExpr); ok && x.Expr == nil {
				stmt.Pattern = x
			} else {
				stmt.Where = $3.(ast.ExprNode)
			}
		}
		$$ = stmt
	}
|	"SHOW" TableName "NEXT_ROW_ID"
	{
		$$ = &ast.ShowStmt{
			Tp:     ast.ShowTableNextRowId,
			Tables: []*ast.TableName{$2.(*ast.TableName)},
		}
	}
|	"SHOW" "CREATE" "TABLE" TableName
	{
		$$ = &ast.ShowStmt{
			Tp:    ast.ShowCreateTable,
			Table: $4.(*ast.TableName),
		}
	}
```

but when I make it ,   I get a error :

```
gofmt (simplify)
bin/goyacc -o parser.go -p yy -t Parser parser.y
conflicts: 1 reduce/reduce
conflicts: 7 shift/reduce
Please check y.output for more information
make: *** [parser.go] Error 1
```

what went wrong with  `parser.y` file ?

**Comment by crazycs520** [comment]
@zhang555 ， Thanks for your contribution. 
After consideration, since `SHOW` syntax has many syntaxes,  
`SHOW TALBLE $table_name NEXT_ROW_ID` maybe a better syntax.
