### ISSUE TITLE
charset: full collations support for TiDB

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#14573]
## Feature Request

For now, TiDB supports [binary collations only](https://pingcap.com/docs/stable/reference/sql/statements/show-collation/), we have several issues related to this limitation:

- https://github.com/pingcap/tidb/issues/222
- https://github.com/pingcap/tidb/issues/1161
- https://github.com/pingcap/tidb/issues/3580
- https://github.com/pingcap/tidb/issues/7519

Now a proposal has been landed for all other collations from MySQL:

https://github.com/pingcap/tidb/pull/14574

This issue is created for the discussions of rationales/options in this proposal, please feel free to express your opinions on the collations in TiDB, thank you!

**Comment by yayuntian** [comment]
I have high expectations for support utf8_general_ci

**Comment by bb7133** [comment]
Close this issue since it has been done, please see https://github.com/pingcap/tidb/projects/33 for more details.
