### ISSUE TITLE
Refine `EXPLAIN`'s output

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#14603]
The following changes are exported from some internal or external DBAs.
- [x] Distinguish the full scan or range scan by changing the name of the executor.
 detailed issue #14601 
- [x] Show the driven side and driving side of `Join` and `IndexLookUpReader` in `EXPLAIN` result. detailed issue #14602 
- [ ] Clear the name of some field. Change the `Count` column to `EstRows`(estimated rows). For `EXPLAIN ANALYZE`, extract actual rows information as an individual column `ActRows` out from the `execution info` column. And put the `EstRows` close to the `ActRows`.

**Comment by winoros** [comment]
And if you have more suggestions on the `EXPLAIN`'s output you can talk with us via the slack channel #sig-planner.

**Comment by LittleFall** [comment]
I'm working for this. :)

**Comment by LittleFall** [comment]
I'm working for this.
