### ISSUE TITLE
Distinguish FullScan and the RangeScan more clearly.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#14601]
This is one advice from DBAs.

The following one is the current explain result.
```
mysql> explain select * from t;
+-------------------+----------+-----------+------------------------------------------------------------+
| id                | count    | task      | operator info                                              |
+-------------------+----------+-----------+------------------------------------------------------------+
| TableReader_5     | 10000.00 | root      | data:TableScan_4                                           |
| └─TableScan_4     | 10000.00 | cop[tikv] | table:t, range:[-inf,+inf], keep order:false, stats:pseudo |
+-------------------+----------+-----------+------------------------------------------------------------+
2 rows in set (0.00 sec)
mysql> explain select * from t where a > 1;
+-------------------+---------+-----------+---------------------------------------------------------+
| id                | count   | task      | operator info                                           |
+-------------------+---------+-----------+---------------------------------------------------------+
| TableReader_6     | 3333.33 | root      | data:TableScan_5                                        |
| └─TableScan_5     | 3333.33 | cop[tikv] | table:t, range:(1,+inf], keep order:false, stats:pseudo |
+-------------------+---------+-----------+---------------------------------------------------------+
2 rows in set (0.00 sec)

```
The advice is that 
- changing the `TableScan` to `TableFullScan` and don't output the range info in `operator info` if it's a full table scan
- changing the `TableScan` to `TableRangeScan` if it's not a full scan.
- For `IndexReader`, it's the same.
- For `IndexLookUpReader`, the `IndexScan` is the same with others, and we just change the `TableScan` to `TableRowIDScan` to make its meaning more clearly.

**Comment by hsqlu** [comment]
I am working on this.

**Comment by francis0407** [comment]
We already have a issue https://github.com/pingcap/tidb/issues/14529 which is similar to this. Shall we only keep one of these two issues open?

**Comment by hsqlu** [comment]
BTW, what does the below exactly mean?
- For IndexReader, it's the same.
- For IndexLookUpReader, the IndexScan is the same with others, and we just change the TableScan to TableRowIDScan to make its meaning more clearly.

**Comment by francis0407** [comment]
@hsqlu 
1. For IndexReader, we can split `IndexScan` to `FullIndexScan` and `RangeIndexScan`.
2. For IndexLoopUpReader, it has two children: `IndexScan` and `TableScan`. `IndexScan` could be `FullIndexScan` or `RangeIndexScan`, as well. But we'd better change `TableScan` to `TableRowIDScan`.
