### ISSUE TITLE
Faild to deploy tidb when running import script of importing grafana dashboards

### ISSUE THREAD

**Issue by aeoluswing** [pingcap/tidb#14613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

After preparing steps(include deploy),run `ansible-playbook start.yml` to start the tidb cluster.

2. What did you expect to see?
Start successfully.

3. What did you see instead?
Some error when importing grafana dashboards - run import script.This error can reproducing.
![image](https://user-images.githubusercontent.com/16639881/73707434-85fd5680-4736-11ea-9162-0ade77acbf06.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb version: v3.0.0 - v.3.0.9

This problem happened when i update tidb version from 2.x to 3.0.0,and upgrading could not resolve,by the way,2.x won't lead this problem before.

**Comment by eurekaka** [comment]
@aeoluswing thanks for reporting, but I think https://github.com/pingcap/tidb-ansible/issues is a more proper place to report this issue. @liubo0127 please help take a look.

**Comment by aeoluswing** [comment]
@eurekaka thx for your advisor
