### ISSUE TITLE
Push down Count(distinct) cases

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tidb#14623]
## Feature Request

**Is your feature request related to a problem? Please describe:**
User found using
`SELECT DISTINCT A from TBL GROUP BY B`
is almost 10 times faster than 
`SELECT COUNT(DISTINCT A) FROM TBL GROUP BY B`
which is 0.8 sec vs 7.1 sec

**Describe the feature you'd like:**
Rewrite push down SQL into 
`SELECT A FROM TBL GROUP BY B, A` 
Similarly 
`SELECT count(distinct A), sum(B) FROM TBL GROUP BY C`
into 
`SELECT A, sum(B) FROM TBL GROUP BY C, A`
And TiDB do the rest of the job.

**Describe alternatives you've considered:**
TiKV / TiFlash provide a distinct_bag function which group all distinct values of a group in to chunk and TiDB will do a final dedup. This might be a cleaner and faster solution for this. But Array type not supported and memory consumption might be an issue.

**Teachability, Documentation, Adoption, Migration Strategy:**
All low NDV distinct cases will be improved. This is a major case for internet company for daily analysis.

**Comment by winoros** [comment]
For this case, you should pay attention to the `NULL` value.
```
mysql> create table t(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values(1), (null), (null);
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0

mysql> select count(distinct a) from t;
+-------------------+
| count(distinct a) |
+-------------------+
|                 1 |
+-------------------+
1 row in set (0.01 sec)

mysql> select count(*) from t group by a;
+----------+
| count(*) |
+----------+
|        2 |
|        1 |
+----------+
2 rows in set (0.01 sec)
```

**Comment by eurekaka** [comment]
This rewrite may not always be beneficial, e,g,
```
mysql> explain select count(distinct a), sum(b) from t group by c;
+-----------------------+----------+-----------+--------------------------------------------------------------------------------------------+
| id                    | count    | task      | operator info                                                                              |
+-----------------------+----------+-----------+--------------------------------------------------------------------------------------------+
| HashAgg_5             | 8000.00  | root      | group by:Column#9, funcs:count(distinct Column#7)->Column#5, funcs:sum(Column#8)->Column#6 |
| └─Projection_12       | 10000.00 | root      | test.t.a, cast(test.t.b)->Column#8, test.t.c                                               |
|   └─TableReader_9     | 10000.00 | root      | data:TableScan_8                                                                           |
|     └─TableScan_8     | 10000.00 | cop[tikv] | table:t, range:[-inf,+inf], keep order:false, stats:pseudo                                 |
+-----------------------+----------+-----------+--------------------------------------------------------------------------------------------+
```
if `NDV(c,a)` is huge while `NDV(c)` is small, the rewrite may generate a worse plan, so it is better to be decided by cost. Put this improvement in Cascades is easier, otherwise, we may introduce one more switch to control this optimization.

**Comment by zz-jason** [comment]
related to https://github.com/pingcap/tidb/issues/7539
