### ISSUE TITLE
Implement approximate solution of distinct count

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tidb#14632]
## Feature Request

**Is your feature request related to a problem? Please describe:**
User found distinct count very slow and might consume high amount of memory.

**Describe the feature you'd like:**
SELECT HLL_DISTINCT_COUNT(A) from TBL;
Either TiKV Cop or TiFlash Cop compute hyperloglog of distinct key from each region and group. TiDB therefore merge the HLL result from each group. Essentially HLL provide a data structure that support add, count and merge. Results from each region cop / group can be merged together forms a final results. This final results has a bounded error margin.
https://en.wikipedia.org/wiki/HyperLogLog

**Describe alternatives you've considered:**
No.

**Teachability, Documentation, Adoption, Migration Strategy:**
A simple new function. Just need to tell user its not accurate but a lot faster.

**Comment by zz-jason** [comment]
@SunRunAway PTAL

**Comment by zz-jason** [comment]
maybe we can utilize this package: https://pkg.go.dev/github.com/DataDog/hyperloglog?tab=doc

**Comment by solotzg** [comment]
@zz-jason It better to use BJKST algorithm for lower error rate. According to http://www.vldb.org/pvldb/vol11/p499-harmouch.pdf. This algorithm is also default for clickhouse.
