### ISSUE TITLE
charset: make `CompareString` support Collation

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14657]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The `CompareString` function is used to compare strings, in order to provide full collation support in TiDB, we should make it support Collation.

**Teachability, Documentation, Adoption, Migration Strategy:**

Please see TiDB RFC #14574 for more details on collations support in TiDB.

**Comment by bb7133** [comment]
Close this PR due to https://github.com/pingcap/tidb/pull/14913
