### ISSUE TITLE
lower() does not work if string contains ’

### ISSUE THREAD

**Issue by kaeverens** [pingcap/tidb#14665]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
create table testlower(name text);
insert into testlower values("one week’s time TEST"); // note: that's not an apostrophe...
insert into testlower values("one week's time TEST");
select lower(name) from testlower;
```

2. What did you expect to see?

```
+------------------------+
| lower(name)            |
+------------------------+
| one week’s time test   |
| one week's time test   |
+------------------------+
```

3. What did you see instead?

```
+------------------------+
| lower(name)            |
+------------------------+
| one week’s time TEST   |
| one week's time test   |
+------------------------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v4.0.0-beta-80-g58c14adc0

**Comment by wshwsh12** [comment]
Thanks for your feedback.
It seems that something wrong in (b *builtinLowerSig) vecEvalString. We will fix the bug. https://github.com/pingcap/tidb/blob/master/expression/builtin_string_vec.go#L49
