### ISSUE TITLE
Support online reload with new certificates

### ISSUE THREAD

**Issue by DanielZhangQD** [pingcap/tidb#14666]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Usually, there will be an expiration of the TLS certificates, we have to support online reload with new certificates instead of just restart the process.
Suggest all the PingCAP components and tools to implement the cert reload feature in the same way.
**Describe the feature you'd like:**

Support online reload with new certificates.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by coderplay** [comment]
+1
