### ISSUE TITLE
expression: update built-in function `SUBSTRING_INDEX()` to support collations.

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#14694]
## Feature Request

**Describe the feature you'd like:**

In order to provide full collation support in TiDB, the implementation of function `SUBSTRING_INDEX()` should be updated to be collation-aware.

**Teachability, Documentation, Adoption, Migration Strategy:**

Please see TiDB RFC #14574 for more details on collations support in TiDB.

**Comment by wjhuang2016** [comment]
Close becase `SUBSTRING_INDEX()` is not collation-aware.
