### ISSUE TITLE
Add a debug command to TiDB.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1469]
Sometimes we want to debug internal data structures,. we need a simple way to get internal information.

**Comment by shenli** [comment]
We have inspectkv tools. @zimulala

**Comment by zimulala** [comment]
Yep，but we only have some simple functions like `show DDL info` now. It's better to list the specific requirements, so that we can gradually realize it in the inspectkv tools.

**Comment by idlesummerbreeze** [comment]
Hi @shenli ,

I have learned golang just since two weeks. I found nothing than GDB to debug GO code. This is very hard to do debug with Interface:

1. cast an interface to a subinterface
2. call a method on the interface

can you show me how can one do it.

Best Regards,
Yu

**Comment by ngaut** [comment]
We don't use debugger at all, it's hard to debug a distributed system with a debugger. Log and distributed tracing tools are very helpful.

**Comment by shenli** [comment]
You can try the IDE for golang from jetbrain. It could analyze interface and its implementations in realtime.

**Comment by tiancaiamao** [comment]
GDB sucks for Go, you may like this https://github.com/derekparker/delve for command line debugging, but @ngaut is right, actually.

**Comment by idlesummerbreeze** [comment]
Hi @ngaut, @shenli and @tiancaiamao ,

thx for your information! I will give it a try.

besides it, **Happy Christmas!**
