### ISSUE TITLE
make the memory tracing in `HashAggExec` more accurate

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14705]
## Feature Request

**Is your feature request related to a problem? Please describe:**

A `memTracker` is used to trace memory consumed by `Chunks` in `HashAggExec`, but in some cases(https://github.com/pingcap/tidb/issues/14024), the `aggPartialResultMapper` used to store intermediate results consumes a lot of memory but we don't trace it now.

Please help us to make the memory tracing in `HashAggExec` more accurate by tracing all memory consumed by the `aggPartialResultMapper`.

If you are interested in this issue, welcome to join [our SIG-EXEC channel](https://tidbcommunity.slack.com/archives/CMRD79DRR) to discuss it with us.
Thanks for your contribution:D

**Comment by tangwz** [comment]
let me fix it.

**Comment by qw4990** [comment]
> let me fix it.

Nice, thanks very much. If you have any problem or question, please feel free to discuss with us :D

**Comment by SunRunAway** [comment]
@tangwz Friendly ping~

**Comment by SunRunAway** [comment]
Another case:
https://asktug.com/t/topic/32980

**Comment by tangwz** [comment]
@SunRunAway PTAL.

**Comment by SunRunAway** [comment]
Duplicate of #14103

**Comment by qw4990** [comment]
Close since all tasks have been finished. Thanks @b41sh @mmyj  and all other Contributors!!! 🎊
