### ISSUE TITLE
About the args of  yyParse

### ISSUE THREAD

**Issue by flike** [pingcap/tidb#1471]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.2

2. What operating system and processor architecture are you using (`go env`)?
MacOS

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?
When I install TiDB from source code,The function `yyParse` in parse.go is like this:
`func yyParse(yylex yyLexer) int`.
But In yy_parser.go call yyParse like this:
```
func (parser *Parser) Parse(sql, charset, collation string) ([]ast.StmtNode, error) {
	if charset == "" {
		charset = mysql.DefaultCharset
	}
	if collation == "" {
		collation = mysql.DefaultCollationName
	}
	sql = handleMySQLSpecificCode(sql)
	l := NewLexer(sql)
	l.SetCharsetInfo(charset, collation)
	yyParse(l, &parser.cache)
	//yyParse(l)
	if len(l.Errors()) != 0 {
		return nil, errors.Trace(l.Errors()[0])
	}
	return l.Stmts(), nil
}
```
So I compile TiDB error. I want to check is this a bug? Thank you

5. What did you see instead?

**Comment by coocood** [comment]
@flike 
'parser.go' is generated by 'make parser' command.
We recently updated our parser generator to `github.com/pingcap/goyacc`.
Have you tried run 'make' command again? It will regenerate the parser.

**Comment by flike** [comment]
done. Thank you.
