### ISSUE TITLE
Query very slow with order and limit

### ISSUE THREAD

**Issue by phamtai97** [pingcap/tidb#14814]
Hi all.
I have data about 9 million records. I try query SQL as follows:
```sql
SELECT * FROM log WHERE 1 = 1
AND log.accounting_time >= 1581267600000  
AND log.accounting_time <= 1581354000000 
ORDER BY log.recorded_time LIMIT 10, 0; 
```
 Recorded_time and accounting_time is type bigint(20).
This query SQL takes 100 seconds to complete.

So, I try to change SQL:
```sql
SELECT * FROM log WHERE 1 = 1;
AND log.accounting_time >= 1581267600000  
AND log.accounting_time <= 1581354000000 
ORDER BY log.recorded_time LIMIT 10000, 0; 
```
It is very fast.

And, I try to change SQL:
```sql
SELECT * FROM log WHERE 1 = 1
AND log.recorded_time >= 1581267600000  
AND log.recorded_time <= 1581354000000 
ORDER BY log.recorded_time LIMIT 10, 0; 
```
It is very fast, too.

So, I don't know what happened with that SQL. Can you help me?

**Comment by francis0407** [comment]
Thanks for your feedback. I'm going to help you find out what happens.
Could you please run `explain analyze select * .....` with both the two queries and post the results here?

**Comment by phamtai97** [comment]
Hi @francis0407.
-  SQL:
```sql
explain SELECT * FROM log WHERE 1 = 1
AND log.recorded_time >= 1581267600000  
AND log.recorded_time <= 1581354000000 
ORDER BY log.accounting_time LIMIT 10, 0; 
```
- Result:
![Screen Shot 2020-02-17 at 4 35 30 PM](https://user-images.githubusercontent.com/38773351/74641464-ef07b400-51a3-11ea-8c9b-9e989de35e25.png)

-  SQL:
```sql
explain SELECT * FROM log WHERE 1 = 1;
AND log.accounting_time >= 1581267600000  
AND log.accounting_time <= 1581354000000 
ORDER BY log.recorded_time LIMIT 10000, 0; 
```
- Resutl:
![Screen Shot 2020-02-17 at 4 41 51 PM](https://user-images.githubusercontent.com/38773351/74641787-73f2cd80-51a4-11ea-867d-b452ea517ca3.png)

- SQL: 
```sql
explain SELECT * FROM log WHERE 1 = 1
AND log.recorded_time >= 1581267600000  
AND log.recorded_time <= 1581354000000 
ORDER BY log.recorded_time LIMIT 10, 0; 
```
- Result:
![Screen Shot 2020-02-17 at 4 44 21 PM](https://user-images.githubusercontent.com/38773351/74641976-c502c180-51a4-11ea-84be-da5082b69295.png)

**Comment by francis0407** [comment]
Hi @phamtai97,
In your first description, you mentioned that the query
```
SELECT * FROM log WHERE 1 = 1
AND log.accounting_time >= 1581267600000  
AND log.accounting_time <= 1581354000000 
ORDER BY log.recorded_time LIMIT 10, 0; 
```
takes more than 100 seconds.

Could you also provide the explain result of this query?

BTW, which version of TiDB are you using? (you can run `select tidb_version();` to check it.)

**Comment by phamtai97** [comment]
Hi you.
1.
- SQL:

```sql
explain SELECT * FROM account_log WHERE 1 = 1
AND account_log.accounting_time >= 1581267600000  
AND account_log.accounting_time <= 1581354000000 
ORDER BY account_log.recorded_time LIMIT 10, 0;
```

- Result:
<img width="1028" alt="Screen Shot 2020-02-17 at 8 11 18 PM" src="https://user-images.githubusercontent.com/38773351/74656909-b2e34c00-51c1-11ea-8e0d-3d29643bc1fc.png">

2. I use TiDB v3.0.1
3. This is schema:
```sql
CREATE TABLE `account_log` (
  `id` bigint(20) NOT NULL, 
  `order` smallint(6) NOT NULL,
  `ledger_id` int(11) NOT NULL, 
  `currency_code` smallint(6) NOT NULL, 
  `trans_id` varchar(64) NOT NULL,
  `flow_id` varchar(16) NOT NULL, 
  `system_id` int(11) NOT NULL,
  `amount` bigint(20) NOT NULL,
  `accounting_time` bigint(20) NOT NULL,
  `extra` json NOT NULL,
  `balance` bigint(20) NOT NULL,
  `recorded_time` bigint(20) NOT NULL,
  PRIMARY KEY (`voucher_id`,`order`,`account_id`),
  KEY `trans_id` (`trans_id`, `trans_system_id`),
  KEY `global_trans_id` (`global_trans_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

**Comment by francis0407** [comment]
Yeah, I think it could be a bug here. The optimizer chooses a wrong index for this query.

One way to speed up this query is to force use the index `accounting_time`:
```sql
SELECT * FROM account_log use index (accounting_time) WHERE 1 = 1
AND account_log.accounting_time >= 1581267600000  
AND account_log.accounting_time <= 1581354000000 
ORDER BY account_log.recorded_time LIMIT 10, 0;
```

**Comment by phamtai97** [comment]
Oh, that's right. But my business must use recorded_time to query. Will this bug be fixed?

**Comment by francis0407** [comment]
It's hard to be fixed. It is a very comment problem that the query optimizer chooses a bad index for the query. Maybe you can run `analyze table` to update the statistic which could help the optimizer.

**Comment by phamtai97** [comment]
How to run `analyze table` in TiDB ?

**Comment by francis0407** [comment]
FYI https://pingcap.com/docs/stable/reference/sql/statements/analyze-table/

**Comment by phamtai97** [comment]
oh, I try it.
