### ISSUE TITLE
Support performance schema functions

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#14886]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Once we have created a view on system tables in performance_schema, the row data are always hard to understand.

For example, 
```
mysql> select AVG_MEM, AVG_LATENCY from events_statements_summary_by_digest limit 1;
+----------+-------------+
| AVG_MEM  | AVG_LATENCY |
+----------+-------------+
| 19074000 |    23338886 |
+----------+-------------+
1 row in set (0.00 sec)
```
One can hardly understand how much memory or time does it really cost.

**Describe the feature you'd like:**

In MySQL, [performance schema functions](https://dev.mysql.com/doc/refman/8.0/en/performance-schema-functions.html) are used to convert these integers into strings that are easy to understand.

The expected result is
```
select format_bytes(AVG_MEM) as AVG_MEM, format_nano_time(AVG_LATENCY) as AVG_LATENCY from events_statements_summary_by_digest limit 1;
+-----------+-------------+
|  AVG_MEM  | AVG_LATENCY |
+-----------+-------------+
| 19.07 MiB |    23.33 ms |
+-----------+-------------+
```

For now, we only need `FORMAT_BYTES` and `FORMAT_NANO_TIME`, as time unit in TiDB is always nanosecond, not picosecond.

**Teachability, Documentation, Adoption, Migration Strategy:**

These functions are commonly used in system views in sys schema.

**Comment by gauss1314** [comment]
Let me fix it.

**Comment by djshow832** [comment]
> Let me fix it.

Thanks!
