### ISSUE TITLE
UCP: Privilege check in statement summary tables

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#14889]
## Description

**Is your feature request related to a problem? Please describe:**

Now statement summary tables show all performance data for whichever user, but it's not safe. 

**Describe the feature you'd like:**

We need privilege check for the data, and wish that the user could only see his own SQLs. Users with super privilege can see all SQLs.

## Score

* 300

## Mentor

* @djshow832 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang programming
* Database privilege management
* MySQL performance schema

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)
* [Document of Statement Summary Tables](https://pingcap.com/docs/stable/reference/performance/statement-summary/)
* [Document of Privilege Management](https://pingcap.com/docs/stable/reference/security/privilege-system/#privilege-management)

**Comment by chenlx0** [comment]
Hi, I have some problems in modifying tests.

I passed ```sessionctx.context``` to ```stmtsummary.ToCurrentDatum``` and ```stmtsummary.ToHistoryDatum``` so that we can check privileges when querying data from statement summaries.

My code is here:

https://github.com/chenlx0/tidb/commit/30142b1c621a3530a5e6a99c122cf06318fef2c3

And then I want to modify the test. I tried to use ```session.CreateSession4Test```  to generate a session for test, but it could result in import cycle problem.

```
# github.com/pingcap/tidb/util/stmtsummary
import cycle not allowed in test
package github.com/pingcap/tidb/util/stmtsummary (test)
	imports github.com/pingcap/tidb/session
	imports github.com/pingcap/tidb/bindinfo
	imports github.com/pingcap/tidb/util/stmtsummary
FAIL	github.com/pingcap/tidb/util/stmtsummary [setup failed]
```

https://github.com/pingcap/tidb/blob/649dfdd2434fe72c39212f8309f1021c1c131158/bindinfo/handle.go#L524

Could you give me some advice on solving this problem?

Or, can we move the test file to another package?

**Comment by djshow832** [comment]
There're some ways to solve this:
1. Replace "package stmtsummary" to "package stmtsummary_test" in statement_summary_test.
2. Move this test to infoschema/perfschema package, refer to https://github.com/pingcap/tidb/pull/13844.
I suggest the second one, because stmtsummary only represents internal data, but perfschema represents tables.
BTW, you can contact me in slack so that I'll be notified ASAP. @chenlx0

**Comment by djshow832** [comment]
Maybe you can just pass `User` and `isSuper` to stmtsummary, instead of pass `privilege`. Thus `stmtsummary` imports less packages, avoiding potential import problems in future.

**Comment by chenlx0** [comment]
Thanks. I have improved my code and pulled request.
