### ISSUE TITLE
Clean up embed TiDB driver.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1495]
There is no need to keep embed driver, Since we support MySQL protocol.
We should remove https://github.com/pingcap/tidb/blob/master/driver.go

**Comment by ngaut** [comment]
Ping @coocood

**Comment by ngaut** [comment]
@Unknwon TiDB can listening on local socket, if you use TiDB as an embeddable database, TiDB doesn't need to listen on any ports.

**Comment by shenli** [comment]
@ngaut There is still a few tests depend on driver. I will update those tests. Hope it could be done in this week.

**Comment by tboerger** [comment]
Why do you want to drop the option to embed tidb? I really like the idea of an embedded database as some kind of alternative to sqlite in pure go.

**Comment by ngaut** [comment]
Hi @tboerger, you can still use TiDB as an embed database. TiDB acts as MySQL server by listening on unix socket or network socket. To making things simple and clean, users should use any of MySQL drivers.

**Comment by tboerger** [comment]
But if I need a server to provide the socket it's not embedded?

**Comment by Unknwon** [comment]
A follow up question: does TiDB right now can only be started with `./tidb-server`?

**Comment by ngaut** [comment]
Yes. @Unknwon

**Comment by mjmfighter** [comment]
Another follow up question: Is there a plan to implement a way to start the server without using the binary, so it can be a fully embedded solution?

**Comment by shenli** [comment]
@mjmfighter  We do not intend to be an embedded database. So there is no solution.

**Comment by tboerger** [comment]
I thought tidb can be a real sqlite alternative, sad that this don't happen.

**Comment by coocood** [comment]
Done
