### ISSUE TITLE
planner/cascades: estimate the cost of `PhysicalProjection` and `PhysicalWindow`

### ISSUE THREAD

**Issue by francis0407** [pingcap/tidb#14967]
## Feature Request

**Is your feature request related to a problem? Please describe:**

1. We forgot to implement the `CalcCost` method for `ProjectionImpl` in cascades planner.

2. We didn't calculate the cost of `PhsyicalWindow` in both plannercore and cascades planenr.

**Describe the feature you'd like:**

1. Implement `CalcCost` method for `ProjectionImpl`.

2. Implement `CalcCost` method for `WindowImpl`, and implement `attach2Task` method for `PhysicalWindow`.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
@francis0407  Hi, could I take this issue?

**Comment by francis0407** [comment]
> @francis0407 Hi, could I take this issue?

Of course! You can set the **assignee** of this issue as yourself.

**Comment by Yisaer** [comment]
@francis0407  In fact, I can't.  🤔
