### ISSUE TITLE
Is the regular expression supported by TiDB ICU or Henry Spencer?

### ISSUE THREAD

**Issue by canfeit** [pingcap/tidb#14992]
Is TiDB's regular expression the ICU of MySQL8 or the Henry Spencer of MySQL5.7?

**Comment by zz-jason** [comment]
Do you mean the implementation of builtin function [regexp](https://dev.mysql.com/doc/refman/8.0/en/regexp.html#operator_regexp)?

TiDB's implementation is based on the `regexp` package of golang. I'm not sure whether golang implements the regexp function the same way as Henry Spencer did.

Have you met any problems with TiDB's `regexp()` behavior?

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
