### ISSUE TITLE
UCP: record access statistics of databases, tables and indices

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14998]
## Description
Support access statistics analysis of databases, tables, and indices, for example, tell the user usage counts of all indices, which can help them optimize their tables and indices.

## Score 

* 1294

## Mentor(s)

* @qw4990 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* SQL
* Golang 

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by zz-jason** [comment]
related with this issue: https://github.com/pingcap/tidb/issues/14607

**Comment by qw4990** [comment]
@you06 The sre-bot seems wrong, please help us.

**Comment by you06** [comment]
@AndrewDi try again please.

**Comment by AngleNet** [comment]
@AndrewDi Hi，shall we cowork on this issue?

**Comment by you06** [comment]
@AndrewDi Dear contributor, our [rules](https://github.com/pingcap/community/blob/master/challenge-programs/challenge-program-season-2-cn.md#%E7%AC%AC%E4%BA%8C%E6%AD%A5%E9%A2%86%E5%8F%96%E4%BB%BB%E5%8A%A1) has been updated. We will remove your pick if there is no update in 7 days(but feel free to pick up again).

**Comment by qw4990** [comment]
@rebelice Would you like to try this task?

**Comment by rebelice** [comment]
OK, I want to try to solve it

**Comment by qw4990** [comment]
> OK, I want to try to solve it

Nice. This issue is duplicated with #14607, so you can see #14607 to get more details.

**Comment by zz-jason** [comment]
for the usage statistics of index, it's duplicated with https://github.com/pingcap/tidb/issues/17508

**Comment by zz-jason** [comment]
I'm going to close this issue since it's duplicated with https://github.com/pingcap/tidb/issues/14607 and lack of discussion. let's trace the progress and discuss it in https://github.com/pingcap/tidb/issues/14607
