### ISSUE TITLE
Support reorganize partition with the merge operation

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#14999]
## Description

The `alter table ... reorganize partition` statement can merge adjacent partitions into one:

```
ALTER TABLE members REORGANIZE PARTITION s0,s1 INTO (
    PARTITION p0 VALUES LESS THAN (1970)
);
```

**Comment by mjonss** [comment]
Closed by https://github.com/pingcap/tidb/issues/38535.
