### ISSUE TITLE
UCP: Support the `get_lock` functions

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#14993]
## Description

Support the [`get_lock`](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html#function_get-lock) function, which can be used to implement application locks or to simulate record locks.

## Score 

* 3488

## Mentor(s)

* @qw4990 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* SQL
* Golang 

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by zz-jason** [comment]
related with https://github.com/pingcap/tidb/issues/14994

**Comment by qw4990** [comment]
Close due to duplicated with https://github.com/pingcap/tidb/issues/14994.
