### ISSUE TITLE
Support Global Index for Partition Table

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#15003]
## Description

In the current table partition implementation, a partition and its indices are encoded to the same key-value range.

```
table t
...
partition1 
-- data start key
-- data end key
-- index start key
-- index end key
...

...
partition2
-- data start key
-- data end key
-- index start key
-- index end key
...

```

The global index would require another kind of encoding schema:

```
table t
...
partition1 
-- data start key
-- data end key
...

...
partition2
-- data start key
-- data end key
...

index
-- index start key
-- index end key
...
```

The most challenging part of this task is keeping compatible with the older versioned TiDB.

**Comment by morgo** [comment]
You are correct, it is not supported.

cc @mjonss

**Comment by zz-jason** [comment]
close since it's duplicated with https://github.com/pingcap/tidb/issues/18032
