### ISSUE TITLE
support `REORGANIZE PARTITION` for range partitioned table

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#15000]
## Description

```
mysql> SHOW CREATE TABLE members\G
*************************** 1. row ***************************
       Table: members
Create Table: CREATE TABLE `members` (
  `id` int(11) DEFAULT NULL,
  `fname` varchar(25) DEFAULT NULL,
  `lname` varchar(25) DEFAULT NULL,
  `dob` date DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1
/*!50100 PARTITION BY RANGE ( YEAR(dob))
(PARTITION n0 VALUES LESS THAN (1970) ENGINE = InnoDB,
 PARTITION n1 VALUES LESS THAN (1980) ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN (1990) ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN (2000) ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN (2010) ENGINE = InnoDB) */
1 row in set (0.00 sec)
```

Suppose that you would like to move all rows representing members born before 1960 into a separate partition. As we have already seen, this cannot be done using `ALTER TABLE ... ADD PARTITION`. However, you can use another partition-related extension to ALTER TABLE to accomplish this:

```
ALTER TABLE members REORGANIZE PARTITION n0 INTO (
    PARTITION s0 VALUES LESS THAN (1960),
    PARTITION s1 VALUES LESS THAN (1970)
);
```

`ALTER TABLE ... REORGANIZE` is a DDL operation. Split partition may need to move data, so this is a more difficult task than https://github.com/pingcap/tidb/issues/15005

There are two possible ways to move the data: logical and physical.
It's a bonus point if we can implement the physical one: telling the TiKV part of the range of data will be moved to another range, and after it's done, modify the DDL meta information in TiDB.

How to keep TiDB processing new read/write requests and handling the split operation in the meanwhile is a challenge.

## Score

7684

## Mentor(s)

* @tiancaiamao 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* DDL 

## Learning Materials

* [MySQL document about partitioning management](https://dev.mysql.com/doc/refman/5.7/en/partitioning-management-range-list.html)
* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by zz-jason** [comment]
I noticed https://github.com/pingcap/tidb/issues/15002, so this issue I think is only focused on the REORGANIZE PARTITION` for range partitioned table.

**Comment by mjonss** [comment]
Closed by https://github.com/pingcap/tidb/issues/38535.
