### ISSUE TITLE
UCP: Add more specified execution information for executor and record in slow log.

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#15009]
## Description

This is the subtask of issue https://github.com/pingcap/tidb/issues/14974.

**Collection more specified information of executor**

Such as HashJoin:

* time cost of build memory table.
* time cost of join

Such as IndexLookupReader:

* time cost of read index.
* time cost of read rows,
* the number of the read indexs and rows.
...

And we also need to collect execution information for `insert/delete/update` executor, and get tso time.

Below are some executor list that needs to add specified execution information:

* TableReaderExecutor
* IndexLookUpExecutor
* HashJoinExec
* IndexLookUpJoin
* IndexLookUpMergeJoin
* IndexNestedLoopHashJoin
* MergeJoinExec
* NestedLoopApplyExec
...

****

## Score

* 1294

## Mentor(s)

* [crazycs520](https://github.com/crazycs520)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* SQL Executer
* SQL Plan

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by crazycs520** [comment]
I will do it 😂

**Comment by SunRunAway** [comment]
@crazycs520 Would you like to add a documentation?
