### ISSUE TITLE
UCP: Migrate `DataForAnalyzeStatus` from package `infoschema` to `executor`

### ISSUE THREAD

**Issue by lonng** [pingcap/tidb#15021]
## Description

This is sub-task of https://github.com/pingcap/tidb/issues/14828

The package `infoschema` should be used to store meta-information for virtual tables only.
But there is some retrieval data logic of the virtual table, which messes the `infoschema` .
PR #14704 has begun to migrate them. You can reference #14704 to help you migrate the `DataForAnalyzeStatus`.

## Score 

* 50

## Mentor(s)

* @crazycs520 

## Recommended Skills

* Go

## Learning Materials

- PR: #14704

**Comment by you06** [comment]
@yzwqf try again please
