### ISSUE TITLE
GC does not work

### ISSUE THREAD

**Issue by fewdan** [pingcap/tidb#15097]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

When I performed the TPCC test, I found that the QPS curve was jittery.

2. What did you expect to see?

The QPS curve remains stable.

3. What did you see instead?

QPS curve was jittery. And GC did not work.

![image](https://user-images.githubusercontent.com/16437100/75764694-303dbd80-5d79-11ea-81fd-7e5b068da0c8.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
| Release Version: v4.0.0-beta-257-g1771cf887
Git Commit Hash: 1771cf8870f999fa229552e9a3034d166708fbad
Git Branch: master
UTC Build Time: 2020-03-02 03:09:06
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by jackysp** [comment]
The GC stop is as expected. Because the code of benchmarksql was changed incorrectly, the logic entered an endless loop, and the transaction was not committed, which blocked the GC.
