### ISSUE TITLE
can't select CLUSTER_INFO table when TLS between server components is enabled

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb#15120]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
enableTLSCluster, See https://github.com/pingcap/tidb-operator/blob/master/charts/tidb-cluster/values.yaml#L61.

2. What did you expect to see?
select  INFORMATION_SCHEMA.CLUSTER_INFO table

3. What did you see instead?
```
 [INFORMATION_SCHEMA]> select * from CLUSTER_INFO;
ERROR 1105 (HY000): Get http://db-pd:2379/pd/api/v1/config/cluster-version: EOF
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v4.0.0-beta.1

**Comment by jackysp** [comment]
PTAL @lysu
