### ISSUE TITLE
 run server failed: listen tcp 192.168.1.1:2380: bind: cannot assign requested address

### ISSUE THREAD

**Issue by chijey** [pingcap/tidb#15135]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
在启动pd的时候，pd一直启动不起来，然后端口也没有被占用

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by 5kbpers** [comment]
Could you upload the log of pd? @chijey

**Comment by tabokie** [comment]
@chijey Can you verify the IP you're trying to bind is listed in `ifconfig`? If not, it's probable that you're binding to the public IP on a server behind NAT.

**Comment by zan7755** [comment]
> @chijey您可以验证要绑定的IP列表在`ifconfig`吗？如果不是，则很可能是您绑定到了NAT后面的服务器上的公共IP。

you are right .thank you
