### ISSUE TITLE
UCP: Refine the error message of `add index`

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#15152]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When I run `create index` statement, it may occur some errors like GCTooEarly. It should report "GC life time is shorter than transaction duration", but this real reason is always overwritten by "cancelled DDL job", and it makes users confusing.

**Describe the feature you'd like:**

Expose all the real reasons of failure to users, not "cancelled DDL job".

## Score

* 200

## Mentor

* @zimulala @djshow832 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang programming
* TiDB DDL
* F1 Online Schema Change

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)
* [Admin Document](https://pingcap.com/docs-cn/stable/reference/sql/statements/admin/#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B)

**Comment by zimulala** [comment]
@wq1019 
Sorry, @tsthght has picked up this issue.

**Comment by zimulala** [comment]
The scenario described here should be that when an error similar to "GCTooEarly" error, it may not be able to exit the DDL processing flow until the error count reaches errorCountLimit. However, the error message will be overwritten by the "cancelled DDL" error.  This issue hopes to return the "cancelled DDL" error message with the original error message.
