### ISSUE TITLE
UCP: Support collate for user session variable

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#15168]
## Description

```
mysql> set names utf8mb4 collate utf8mb4_general_ci;
Query OK, 0 rows affected (0.00 sec)

mysql> set @a = "a";
Query OK, 0 rows affected (0.00 sec)

mysql> select collation(@a);
+---------------+
| collation(@a) |
+---------------+
| utf8mb4_bin   |
+---------------+
1 row in set (0.00 sec)
```
The expected result is `utf8mb4_general_ci`.
A problem is that we use a map(string[string]) to store the session variable. If we try to support collation, we may need to change the map to `string[datum]`

## Score

* 50

## Mentor

* @wjhuang2016 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang programming

## Learning Materials

* English: [MySQL Document](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_collation_connection)

**Comment by you06** [comment]
@AngleNet try again please, I think it's caused by unstable network.

**Comment by you06** [comment]
@AngleNet the challenge is misspelled.

**Comment by AngleNet** [comment]
> @AngleNet the challenge is misspelled.

Uh Ha ! Thank you very much.

**Comment by AngleNet** [comment]
That's right~~~ Let me try this later.

**Comment by you06** [comment]
@SeaRise try again please
