### ISSUE TITLE
How to use `tidb-ctl` to connect a TiDB Cluster with TLS enabled

### ISSUE THREAD

**Issue by weekface** [pingcap/tidb#15173]
## General Question

I started the TiDB Cluster with TLS enabled: https://pingcap.com/docs/stable/how-to/secure/enable-tls-between-components/.

I can't use `tidb-ctl` to connect to the TiDB Server, because the document of TiDB Control don't have the TLS related options.  https://pingcap.com/docs/stable/reference/tools/tidb-control/

**Comment by weekface** [comment]
@shenli PTAL

**Comment by zz-jason** [comment]
@lysu PTAL

**Comment by lysu** [comment]
tidb-ctl support tls in yesterday and will update docs in https://github.com/pingcap/docs-cn/pull/2417

**Comment by lysu** [comment]
ps: tidb-ctl will be deprecated and full be replaced with tidb-dashboard or tidb cluster virtual table
