### ISSUE TITLE
Cannot select from information_schema.tiflash_replica

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tidb#15187]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

MySQL [(none)]> set @@session.tidb_isolation_read_engines='tiflash';
Query OK, 0 rows affected (0.00 sec)

MySQL [(none)]> select * from information_schema.tiflash_replica;

2. What did you expect to see?

+--------------+------------+----------+---------------+-----------------+-----------+----------+
| TABLE_SCHEMA | TABLE_NAME | TABLE_ID | REPLICA_COUNT | LOCATION_LABELS | AVAILABLE | PROGRESS |
+--------------+------------+----------+---------------+-----------------+-----------+----------+
| test         | t          |      151 |             1 |                 |         1 |        1 |
| test         | t2         |      158 |             1 |                 |         1 |        1 |
+--------------+------------+----------+---------------+-----------------+-----------+----------+
2 rows in set (0.00 sec)

3. What did you see instead?
ERROR 1815 (HY000): Internal : Can not find access path matching 'tidb_isolation_read_engines'(value: 'tiflash') and tidb-server config isolation-read(engines: '[tikv tiflash]'). Available values are 'tikv'.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v3.1.0-beta.1-11-g99660f439
   Git Commit Hash: 99660f439ef1a5c927d8480f2ec2f98a441dbccc
   Git Branch: release-3.1
   UTC Build Time: 2020-03-06 08:29:53

**Comment by lzmhhh123** [comment]
already fix in https://github.com/pingcap/tidb/pull/15141
