### ISSUE TITLE
different behavior of `select CURRENT_ROLE()` between TiDB and MySQL 8.0

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#15199]
## General Question
 
TiDB

```
mysql> SELECT CURRENT_ROLE();
+----------------+
| CURRENT_ROLE() |
+----------------+
|                |
+----------------+
```

MySQL 8.0

```
mysql> SELECT CURRENT_ROLE();
+----------------+
| CURRENT_ROLE() |
+----------------+
| NONE           |
+----------------+
```

**Comment by SunRunAway** [comment]
@jackysp PTAL

**Comment by tisonkun** [comment]
assign

**Comment by tisonkun** [comment]
I've sent a pull request as https://github.com/pingcap/tidb/pull/25438

**Comment by tisonkun** [comment]
... however, the patch changes user facing behavior. @SunRunAway could you be the judger here whether or not we should include this change? Though I don't think it is in a significant way.

**Comment by tisonkun** [comment]
The problem here is that when CURRENT_ROLE returns empty roles, MySQL behavior is displayed as `NONE` while TiDB displays empty string.

**Comment by tisonkun** [comment]
See also [this page](https://dev.mysql.com/doc/refman/8.0/en/information-functions.html#function_current-role) for MySQL spec.
