### ISSUE TITLE
add document about how to use `opt_rule_blacklist`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#15207]
## Feature Request

**Is your feature request related to a problem? Please describe:**

There isn't a document about how to use `opt_rule_blacklist`. For example, what rules can be put into that table?

**Describe the feature you'd like:**

Add document about this table. List all the rule names, explain all the logical rules TiDB has.

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by francis0407** [comment]
BTW, `opt_rule_blacklist` is a server level configuration now. I think it is supposed to be a session variable. What do you think? @zz-jason

**Comment by zz-jason** [comment]
Yes, It's better to support session level configuration.
