### ISSUE TITLE
rename `sm_join` to `merge_join`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#15200]
## Feature Request

**Is your feature request related to a problem? Please describe:**

these hints are used to control the join algorithms:

* Hash Join: hash_join()
* Merge Join: sm_join()
* Index Hash Join: inl_hash_join()
* Index Merge join: inl_merge_join()

It's better to change `sm_join()` to `merge_join()` for these reasons:
* What is `sm` short for? It makes user confused.
* `merge_join()`/`inl_merge_join()` and `hash_join()`/`inl_hash_join()`, keeping the same naming pattern makes people much easier to remember these 4 hints.

**Describe the feature you'd like:**

As the title said, change `sm_join` to `merge_join`, merge it to release 4.0 before it's GA.

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by lawyerphx** [comment]
Do we need to be compatible with the name 'ms_join'? (to prevent compatibility issues for old users)
