### ISSUE TITLE
UCP: support hint 'USE_CASCADES(ON|OFF)' to use/disuse cascades planner in a single query

### ISSUE THREAD

**Issue by francis0407** [pingcap/tidb#15215]
## Description
Cascades planner is a new optimizer in TiDB. Currently, we uses a session variable `tidb_enable_cascades_planner` to determine whether uses the cascades planner or not. But sometimes, we only want to use cascades planner for a single query, without affecting other queris in the same session. 
For example:
```sql
# This query should be forced to use cascades planner.
select /*+ USE_CASCADES(ON) */ * from t;
```

```sql
# This query should be forced to use core planner(the old one).
select /*+ USE_CASCADES(OFF) */ * from t;
```
## Score

* 300
## Mentor(s)

* @francis0407 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang
* SQL

## Learning Materials
* PR for `tidb_enable_cascades_planner`: https://github.com/pingcap/tidb/pull/7879
* Chinses blog for cascades planner: https://pingcap.com/blog-cn/tidb-cascades-planner/

**Comment by gauss1314** [comment]
@you06 help~

**Comment by gauss1314** [comment]
Hi @francis0407 , there are other hint like `USE_TOJA(true)`, `ENABLE_PLAN_CACHE(false)`,
so for consistency, how about just change `ON|OFF` to `true|false`?
```
# This query should be forced to use cascades planner.
select /*+ USE_CASCADES(true) */ * from t;
# This query should be forced to use core planner(the old one).
select /*+ USE_CASCADES(false) */ * from t;
```

**Comment by francis0407** [comment]
@gauss1314 good catch! Use `true|false` then.

**Comment by you06** [comment]
@gauss1314 the pick problem is fixed and this task is in review stage now, you can pick up new issues.
