### ISSUE TITLE
Change default behavior of `oom-action` to `cancel`

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#15224]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently the default behavior of `oom-action` (when a single SQL statement exceeds the memory quota specified by `mem-quota-query` and cannot be spilled over to disk) is just printing a log.

```
# What to do when mem-quota-query is exceeded and can not be spilled over to disk any more.
# Valid options: ["log", "cancel"]
oom-action = "log"
```

Since most executors support spilling in v4.0, `oom-action` is better to defaults to `cancel`

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
Hi, can I take this? @SunRunAway

**Comment by SunRunAway** [comment]
> Hi, can I take this? @SunRunAway

Sure.
