### ISSUE TITLE
wrong results when CASE...WHEN function along with float argument

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#15291]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?

W/ MySQL 5.7
```mysql
mysql> select case when 0.1 then 1 else 2 end;
+---------------------------------+
| case when 0.1 then 1 else 2 end |
+---------------------------------+
|                               1 |
+---------------------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

W/ TiDB,
```mysql
mysql> select case when 0.1 then 1 else 2 end;
+---------------------------------+
| case when 0.1 then 1 else 2 end |
+---------------------------------+
|                               2 |
+---------------------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

b504d3792

**Comment by SunRunAway** [comment]
@lance6716
Would you like to take a look?

**Comment by lance6716** [comment]
> @lance6716
> Would you like to take a look?

OK, since `CASE` function has a seperated issue, I'm going to let #15016 close #11601
