### ISSUE TITLE
remove the usage of mysql.TypeDecimal

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#15328]
mysql.TypeDecimal means TypeUnspecified, but it is always though as TypeNewDecimal by mistake. We can use mysql.TypeUnspecified instead mysql.TypeDecimal in TiDB.

related issue: https://github.com/pingcap/parser/issues/767

- [x] replace mysql.TypeDecimal to mysql.TypeUnspecified in TiDB
- [x] remove the difinition of TypeDecimal in https://github.com/pingcap/parser

**Comment by HuGanghui** [comment]
I think this issue that is fixed can be closed.
