### ISSUE TITLE
Does tidb can support index full scan and index fast full scan？

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tidb#15343]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by King-Dylan** [comment]
Does tidb can support index full scan and index fast full scan. fast full means that you can scan without index order. This can speed up index scans using multiple block reads。

**Comment by shenli** [comment]
In the `explain` result, you can see there is a field named `keep order` for `IndexScan` operator. If it is false, then the operator will not promise data order. I think this is what you are looking for.
For example https://pingcap.com/docs/stable/reference/performance/understanding-the-query-execution-plan/#example-usage-1
