### ISSUE TITLE
performance_schema contains annoying differences from MySQL

### ISSUE THREAD

**Issue by wwar** [pingcap/tidb#15348]
## Bug Report

I have a performance_schema GUI that I use to review MySQL slow queries. I tried to port it to TiDB, and there are annoying differences.

2. What did you expect to see?

It would be nice if there was a best effort to be MySQL compatible.

3. What did you see instead?

In the table `performance_schema.events_statements_summary_by_digest`:

* The TiDB column `EXEC_COUNT` is `COUNT_STAR` in MySQL.
* The TiDB column `SUM_LATENCY` is `SUM_TIMER_WAIT` in MySQL.
* All times in TiDB are in nanoseconds. In MySQL they are picoseconds (previously reported as #14211). I was surprised this was handled as a docs bug, it is hard to keep track of this.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta-385-g107b071e0
Git Commit Hash: 107b071e0c1d8c5678911ccb2808e42db0abf63c
Git Branch: master
UTC Build Time: 2020-03-11 03:54:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by wwar** [comment]
https://github.com/pingcap/tidb/pull/15946 is another difference. It proposes to remove "noisy" statements from the digest summary.

**Comment by bb7133** [comment]
Hi @wwar , thanks for reporting this!

> I have a performance_schema GUI that I use to review MySQL slow queries. I tried to port it to TiDB, and there are annoying differences.

BTW, is the GUI you mentioned available for public? We can also try it and improve the statement summaries.

**Comment by wwar** [comment]
> BTW, is the GUI you mentioned available for public? We can also try it and improve the statement summaries.

In the future, yes :-) But it's a hobby project. In the mean time I am happy to file bugs. You can see that a lot of the [issues I file](https://github.com/pingcap/tidb/issues/created_by/wwar) are on pfs.

**Comment by djshow832** [comment]
Thanks for your advise.
Concepts in TiDB are so much different with that in MySQL. e.g. a SQL is treated as an event in MySQL, but there's no such concept in TiDB.
Once I proposed the names `COUNT_STAR` and `SUM_TIMER_WAIT` in my team, they thought it's not friendly. We pay much attention to usability, and we think most of TiDB users may want a more straightforward name.
In the future, I think we won't keep everything consistent with MySQL, especially those features which improve usability.
I feel sorry that it couldn't help you on the monitoring tool. Actually, TiDB Dashboard is public in TiDB 4.0, and it integrates statement summary. Most of users will use Dashboard rather than a generic third-party monitoring tool, so we decided not to change it.

**Comment by wwar** [comment]
> Thanks for your advise.
> Concepts in TiDB are so much different with that in MySQL. e.g. a SQL is treated as an event in MySQL, but there's no such concept in TiDB. Even if these two column names are fixed, we can't make all the columns consistent with MySQL, because some metrics such as `SUM_CREATED_TMP_TABLES` make no sense in TiDB.

I get that part, I'm fine with that being `NULL` in TiDB.

> Once I proposed the names `COUNT_STAR` and `SUM_TIMER_WAIT` in my team, they thought it's not friendly. We pay much attention to usability, and we think most of TiDB users may want a more straightforward name.
> In the future, I think we won't keep everything consistent with MySQL, especially those features which improve usability.

I think if that were the case, it would be better to rename the table and not use the name `performance_schema.events_statements_summary_by_digest`.

I also have to disagree on the rationale. It does not improve usability if you rename individual columns for the sake of renaming them. It is the contrary, because now all these differences have to be documented (which they are not), and honestly leads to a feeling of mistrust when trying to port apps.. because if the TiDB developers were so willing to adhoc rename a column, what else is going to break??

> I feel sorry that it couldn't help you on the monitoring tool. Actually, TiDB Dashboard is public in TiDB 4.0, and it integrates statement summary. Most of users will use Dashboard rather than a generic third-party monitoring tool, so we decide not to change it.

Never mind my app. There are other consequences here.

**Comment by djshow832** [comment]
OK. Since there're many columns TiDB has not supported yet, but they're meaningful, such as `SUM_SORT_ROWS`, so it's a safe choice to rename the table. And `events_statements_summary_by_digest` will stay empty.
I'll do that soon.

**Comment by wwar** [comment]
That makes sense to me. May I suggest moving to information_schema as well, since perfschema always uses pico seconds?

Then the manual can say something like "TiDB does not implement performance_schema, but comparable metrics can be found in TiDB's information_schema tables".

**Comment by djshow832** [comment]
LGTM. 
Actually, there're some system tables used for profiling in `performance_schema`, e.g. `tidb_profile_cpu`. But they don't contain any timing fields, so it'd be OK.
