### ISSUE TITLE
UCP: Speed up slow_query

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#15354]
## Description

TiDB has an `SLOW_QUERY` system table, it's data is parse from slow-log when user query this table.

Currently, TiDB user synchronous parsing slow-log file when parrent executor calling `Next` method. But we can 
use another goroutine to Asynchronous parsing slow-log to speed up query `SLOW_QUERY`. the progress maybe like below:

```go
func (e *slowQueryRetriever) initialize(sctx sessionctx.Context) error {
	...
	go e.parseSlowLog()
	...
}

func (e *slowQueryRetriever) retrieve(ctx context.Context, sctx sessionctx.Context) ([][]types.Datum, error) {
	...
	// get rows from cache channel
	rows := <- e.resultCh
	...
}

```

## Score

* 200

## Mentor(s)

* [@crazycs](https://github.com/crazycs520)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* go

## Learning Materials

* [慢查询文档](https://pingcap.com/docs-cn/dev/how-to/maintain/identify-abnormal-queries/identify-slow-queries/)

**Comment by ziyi-yan** [comment]
I found out that only the `retrieve()` method is called by `memTableRetriever` interface at [here](https://github.com/pingcap/tidb/blob/039a22ab508010fd349953e63a3f3347873a2cdb/executor/memtable_reader.go#L69) (other than test code). If we want to achieve this optimization, we might need to call `initialize()` when we construct the `slowQueryRetriever`, such as here:

https://github.com/pingcap/tidb/blob/9e98f706ae2c21047cfdf123566d5a062744562b/executor/builder.go#L1428
Is it OK to put some initialization code here?

**Comment by ziyi-yan** [comment]
I just submit a draft PR for further discussion. It seems that it's kind of hard to do initialization when constructing the `slowQueryRetriever`, because we cannot return error in `buildMemTable()`: https://github.com/pingcap/tidb/pull/15363/files#diff-badfcd30d7596a08cd207b8e6ae778e6R1448-R1453
