### ISSUE TITLE
UCP: Speed up parse slow-log when query slow_query

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#15371]
## Description

After Issue https://github.com/pingcap/tidb/issues/15354 laster, I found the performance improvement is not significant. The Read slow log file and parse process are slow.

So, we still need to speed up it.
 
## Score

Use a bench test to judge the score, the bench test should in the below situation:

* compare the time cost of `select count(*) from information_schema.slow_query`
*  And the `slow-log.log` file is 300M.
* Should do bench test in NVME or SSD.

Below is the score: 

* improve 10X -1000
* improve 9X -900
* improve 8X -800
......
* improve 2X -200

At least has 2x performance improvement, the max score is 1000.

## Mentor(s)

* [@crazycs](https://github.com/crazycs520)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

## Learning Materials

* * [慢查询文档](https://pingcap.com/docs-cn/dev/how-to/maintain/identify-abnormal-queries/identify-slow-queries/)
* use `slowQueryRetriever` search in TiDB code to see related implemention code.

**Comment by you06** [comment]
@yzwqf the issue should be fixed and I noticed that you have 150 points in this repo, the medium level tasks required at least 200 points before picking up.
@crazycs520 I assign with 1000 points for this issue by default, you may use `/award-point` to adjust score in the pull request. eg. `/award-point 600`

**Comment by yzwqf** [comment]
> @yzwqf the issue should be fixed and I noticed that you have 150 points in this repo, the medium level tasks required at least 200 points before picking up.
> @crazycs520 I assign with 1000 points for this issue by default, you may use `/award-point` to adjust score in the pull request. eg. `/award-point 600`

it didn't make sense, would u please check [#15021](https://github.com/pingcap/tidb/issues/15021), [#15036](https://github.com/pingcap/tidb/issues/15036), [#15401](https://github.com/pingcap/tidb/issues/15401), [#15031](https://github.com/pingcap/tidb/issues/15031).

**Comment by you06** [comment]
@yzwqf I see, #15467 is not related with #15401, you may use `UCP #xxx` to UCP mention issue in PR description. I've fix the points issue, and you can pick this, congrats!

**Comment by yzwqf** [comment]
> @yzwqf I see, #15467 is not related with #15401, you may use `UCP #xxx` to UCP mention issue in PR description. I've fix the points issue, and you can pick this, congrats!

thx a lot

**Comment by jyz0309** [comment]
Alkaid will fix it this week :)
