### ISSUE TITLE
unexpected result when executing DDL  and DML concurrently

### ISSUE THREAD

**Issue by jzdxeb** [pingcap/tidb#15386]
CODE master

```sql
create table t (a int, b int)
insert into t values(1,1);
```

connection 1

```sql
alter table t drop column b;
```
connection2 

```sql
update t  set a=2,b=2;
update t set a=10,where b=2;
select * from t;
```

result
mysql> Select * from t;
+------+
| a    |
+------+
|    2 |
+------+
1 row in set (0.00 sec)

**Comment by zz-jason** [comment]
Could you describe the order of executing these SQLs to help us reproduce this issue? For example, describe them in this form:

| time | connection 1 | connection 2 |
| ---  | ------------ | ------------ |
| t1   | xxx          |              |
| t2   |              | xxx          |


Also, what's the tidb version are you using?

**Comment by jzdxeb** [comment]
> Could you describe the order of executing these SQLs to help us reproduce this issue? For example, describe them in this form:
> 
> time	connection 1	connection 2
> t1	xxx	
> t2		xxx
> Also, what's the tidb version are you using?

| time  | connection1  |        connection2 |
|---|:---:|:---:|
| t1      |  drop column |
|t2     |   column state(write only)|  update  t set a =2 ,b=2|
|t3       | column state (write only) | update t set a=20 where b=2| 
|t4       | column state (none)    |      select * from t |

**Comment by zimulala** [comment]
@jzdxeb 
I cannot reproduce this problem with the master version. Could you describe to us the steps for reproduction? And how do you keep the TiDB on "write-only" state to execute the update statement?

**Comment by jzdxeb** [comment]
for easy to produce this problem you can add 
diff --git a/ddl/column.go b/ddl/column.go
index f38a774d5..4489e9ad1 100644
--- a/ddl/column.go
+++ b/ddl/column.go
@@ -265,6 +265,7 @@ func onDropColumn(t *meta.Meta, job *model.Job) (ver int64, _ error) {
                job.SchemaState = model.StateDeleteOnly
                colInfo.State = model.StateDeleteOnly
                ver, err = updateVersionAndTableInfo(t, job, tblInfo, originalState != colInfo.State)
+               time.Sleep(50 * time.Second)
        case model.StateDeleteOnly:
                // delete only -> reorganization
                job.SchemaState = model.StateDeleteReorganization

**Comment by zimulala** [comment]
@jzdxeb 
Thank you very much for your feedback! I am working on it.
