### ISSUE TITLE
Updating Question: TiDB version from v2.0.11 to v3.0.0

### ISSUE THREAD

**Issue by racecdj** [pingcap/tidb#15392]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I try to update the version of TiDB from v2.0.11 to v3.0.0.
Before updating, I add two PD, one TiDB and three TiKV in version v2.0.11. The information on the monitor shows the add operation is successful.  In this way, I have three PD, two TiDB and five TiKV.

After that, I notice the regions cannot distribute to the new three TiKV servers. Therefore, I try to update the version to solve it.
Base on the guidance, I make the updating step by step. https://pingcap.com/docs-cn/stable/how-to/upgrade/from-previous-version/

2. What did you expect to see?
Our aim is to complete the updating and make the regions automatically distribute to each TiKV server.

3. What did you see instead?
When dealing with the operation:
ansible-playbook excessive_rolling_update.yml
1） I met the timeout in each PD server:

`[Central control machine IP]: Ansible FAILED! => playbook: excessive_rolling_update.yml; TASK: wait until the PD port is down; message: {"changed": false, "elapsed": 300, "msg": "the PD port 2379 is not down"}
`
To continue the operation, I run `stop_pd.sh` script in deploy directory of each PD server, which can make the rolling update continue.

2）After that, I met a new question:

`[Central control machine IP]: Ansible FAILED! => playbook: excessive_rolling_update.yml; TASK: wait until the TiDB port is up; message: {"changed": false, "elapsed": 300, "msg": "the TiDB port 4000 is not up"}`
However, I find the TiDB process is run in the server. And I also try to run script `start_tidb.sh`. But it seems to unsolvable.

3）I also check the logs in the central control machine.
In TiDB log, it writes:
`[FATAL] [session.go:1587] ["check bootstrapped failed"] [error="[tikv:9001]PD server timeout"] [errorVerbose="[tikv:9001]PD server timeout\ngithub.com/pingcap/errors.
`
In TiKV log, it writes:
`[ERROR] [endpoint.rs:454] [error-response] [err="region message: \"peer is not leader\" not_leader { region_id: 12 leader { id: 37 store_id: 4 } }"]
`
In PD log, it writes:
`[WARN] [grpclog.go:60] ["transport: http2Server.HandleStreams failed to read frame: read tcp central control machine IP:2379->central control machine IP:55726: read: connection reset by peer"]
`
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
I notice the old version of TiDB including tidb-server(v2.0.11
), tikv-server(v2.0.11) and pd-server(v.2.0.10). Does it necessary to keep them in the same version? If necessary, what should I do?

Version Details:

 **./pd-server -V**
Release Version: v2.0.10
Git Commit Hash: 860ef894f1cae254dead276ab9d6078455b10bf1
Git Branch: release-2.0
UTC Build Time:  2019-01-03 09:25:39

**./tidb-server -V**
Release Version:  v2.0.11
Git Commit Hash:  83889a5d821f40412be1af2ad2f2393737f517fd
Git Commit Branch:  release-2.0
UTC Build Time:  2019-01-03 09:27:12
GoVersion:  go version go1.11.2 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1

**./tikv-server -V**
TiKV 
Release Version:   2.0.11
Git Commit Hash:   c666277d3565164a00451b95666012cb04274d93
Git Commit Branch: release-2.0
UTC Build Time:    2019-01-03 09:29:52
Rust Version:      1.27.0-nightly (48fa6f963 2018-04-05)

I am looking forward to your solution or advise.

**Comment by lysu** [comment]
@liubo0127  PTAL

**Comment by racecdj** [comment]
Now I am trying to update the verison of PD form v2.0.10 to v2.0.11. The operation is :
s1: check the tidb version in `inventory.ini` is v2.0.11
s2: ansible-playbook rolling_update.yml --tags=pd
However,  the central control machine also shows the same issue I met in updating to version 3.0.0. The two issues maybe the same. Here I post the error detail:

`[central control machine IP]: Ansible FAILED! => playbook: rolling_update.yml; TASK: wait for PD up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in central control machine IP:2379"}
`

**Comment by racecdj** [comment]
The detail of `inventory.ini`:
![image](https://ibb.co/vVzY4qN)

**Comment by liubo0127** [comment]
> Now I am trying to update the verison of PD form v2.0.10 to v2.0.11. The operation is :
> s1: check the tidb version in `inventory.ini` is v2.0.11
> s2: ansible-playbook rolling_update.yml --tags=pd
> However, the central control machine also shows the same issue I met in updating to version 3.0.0. The two issues maybe the same. Here I post the error detail:
> 
> `[central control machine IP]: Ansible FAILED! => playbook: rolling_update.yml; TASK: wait for PD up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in central control machine IP:2379"} `

Please check the logs of the failed `PD` nodes.

**Comment by racecdj** [comment]
> > Now I am trying to update the verison of PD form v2.0.10 to v2.0.11. The operation is :
> > s1: check the tidb version in `inventory.ini` is v2.0.11
> > s2: ansible-playbook rolling_update.yml --tags=pd
> > However, the central control machine also shows the same issue I met in updating to version 3.0.0. The two issues maybe the same. Here I post the error detail:
> > `[central control machine IP]: Ansible FAILED! => playbook: rolling_update.yml; TASK: wait for PD up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in central control machine IP:2379"} `
> 
> Please check the logs of the failed `PD` nodes.

The pd.log in deploy/log does not update. The last log happened 8 hours ago.
The details:
PD .249(central control machine):
```
2020/03/16 02:50:21.320 server.go:97: [info] PD config - Config({FlagSet:0xc000188de0 Version:false ClientUrls:http://xxx.xxx.xxx.249:2379 PeerUrls:http://xxx.xxx.xxx.249:2380 AdvertiseClientUrls:http://xxx.xxx.xxx.249:2379 AdvertisePeerUrls:http://xxx.xxx.xxx.249:2380 Name:pd1 DataDir:/home/tidb/deploy/data.pd InitialCluster:pd1=http://xxx.xxx.xxx.249:2380,pd2=http://xxx.xxx.xxx.252:2380,pd3=http://xxx.xxx.xxx.251:2380 InitialClusterState:new Join: LeaderLease:3 Log:{Level:info Format:text DisableTimestamp:false File:{Filename:/home/tidb/deploy/log/pd.log LogRotate:true MaxSize:300 MaxDays:0 MaxBackups:0}} LogFileDeprecated: LogLevelDeprecated: TsoSaveInterval:3s Metric:{PushJob:pd1 PushAddress:xxx.xxx.xxx.249:9091 PushInterval:15s} Schedule:{MaxSnapshotCount:3 MaxPendingPeerCount:16 MaxMergeRegionSize:0 SplitMergeInterval:1h0m0s PatrolRegionInterval:100ms MaxStoreDownTime:30m0s LeaderScheduleLimit:4 RegionScheduleLimit:4 ReplicaScheduleLimit:8 MergeScheduleLimit:8 TolerantSizeRatio:5 LowSpaceRatio:0.8 HighSpaceRatio:0.6 EnableRaftLearner:false Schedulers:[{Type:balance-region Args:[] Disable:false} {Type:balance-leader Args:[] Disable:false} {Type:hot-region Args:[] Disable:false} {Type:label Args:[] Disable:false}]} Replication:{MaxReplicas:3 LocationLabels:[]} Namespace:map[] QuotaBackendBytes:0 AutoCompactionRetention:1 TickInterval:500ms ElectionInterval:3s Security:{CAPath: CertPath: KeyPath:} LabelProperty:map[] configFile:conf/pd.toml WarningMsgs:[] NamespaceClassifier:default nextRetryDelay:1000000000 disableStrictReconfigCheck:false heartbeatStreamBindInterval:{Duration:60000000000} leaderPriorityCheckInterval:{Duration:60000000000}})
2020/03/16 02:50:21.324 server.go:123: [info] start embed etcd
2020/03/16 02:50:21.324 systime_mon.go:24: [info] start system time monitor
2020/03/16 02:50:21.324 log.go:86: [info] embed: [listening for peers on  http://10.132.141.249:2380]
2020/03/16 02:50:21.324 log.go:86: [info] embed: [pprof is enabled under /debug/pprof]
2020/03/16 02:50:21.324 log.go:86: [info] embed: [listening for client requests on  10.132.141.249:2379]
```

PD .252:
`[2020/03/16 02:50:57.819 +00:00] [WARN] [probing_status.go:70] ["prober detected unhealthy status"] [round-tripper-name=ROUND_TRIPPER_RAFT_MESSAGE] [remote-peer-id=3bfad21fa9d6cda7] [rtt=948.111µs] [error="dial tcp central control machine:2380: connect: connection refused"]
PD . 251:
`[2020/03/16 02:50:51.610 +00:00] [FATAL] [main.go:111] ["run server failed"] [error="listen tcp 10.132.141.251:2380: bind: address already in use",errorVerbose="listen tcp central control machine:2380: bind: address already in use\ngithub.com/pingcap/pd/server.(*Server).
``

**Comment by liubo0127** [comment]
The time does not match should be due to different time zones.
The node that failed to start above should be 252. The reason for the failure to start is that port 2380 is occupied by other services. Solve the port occupation and then retry the operation.

**Comment by racecdj** [comment]
> The time does not match should be due to different time zones.
> The node that failed to start above should be 252. The reason for the failure to start is that port 2380 is occupied by other services. Solve the port occupation and then retry the operation.

I try several times of restarting pd clusters, but it failed. Thus, I use pd-recover to create a new pd cluster. After use the commond:
`./pd-recover -endpoints http://xxx.xxx.xxx.249:2379 -cluster-id current_cluster_data -alloc-id a number larger than the current_id 
`
I restart the pd cluster:
`ansible-playbook rolling_update.yml --tags=pd
`
However, when i am trying to restart tikv and tidb with the command:
`ansible-playbook rolling_update.yml --tags=tidb,tikv
`
I met a new error:
`Ansible FAILED! => playbook: rolling_update.yml; TASK: remove evict-leader-scheduler; message: {"msg": "The task includes an option with an undefined variable. The error was: 'store_id' is undefined\n\nThe error appears to have been in '/home/tidb/tidb-ansible/common_tasks/add_evict_leader_scheduler.yml': line 3, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: remove evict-leader-scheduler\n  ^ here\n"}
`


The task includes an option with an undefined variable. The error was: 'store_id' is undefined\n\nThe error appears to have been in

**Comment by racecdj** [comment]
Now, the tidb log shows:
```
2020/03/16 19:39:26.110 backoff.go:218: [warning] backoffer.maxSleep 20000ms is exceeded, errors:
region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"
region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"
region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"
2020/03/16 19:39:26.110 session.go:1297: [fatal] check bootstrapped err [tikv:9001]PD server timeout[try again later]

```

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates you can reopen it.
