### ISSUE TITLE
UCP: Control the concurrency of all types of executors in one session variable

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#15428]
## Description

Currently, TiDB has several variables to control each type of executor,

See https://github.com/pingcap/tidb/blob/45d83d1adb3eedc83bf5f59f21e6666dfcf8696f/sessionctx/variable/session.go#L1282-L1309

And each of them has its own default value.
I propose to add one session variable named like`ExecutorConcurrency` to control the concurrency of all types of executors and make the default value as the number of the CPU cores.

For compatibility of the old variables, take `HashJoinConcurrency` as an example,
1) The default value of `ExecutorConcurrency` is  the number of the CPU cores.
2) Remove the default value of `HashJoinConcurrency`. 
3) If `HashJoinConcurrency` is unset, the concurrency of Hash Join is applied by `ExecutorConcurrency`. If `select @tidb_hash_join_concurrency;` is queried, the value of `ExecutorConcurrency` is outputted.
4) If `HashJoinConcurrency` is set specifically,  the concurrency of Hash Join is applied by `HashJoinConcurrency`. If `select @tidb_hash_join_concurrency;` is queried, the value of `HashJoinConcurrency` is outputted.

## Score

* 300

## Mentor(s)

* @SunRunAway 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by you06** [comment]
@ZiheLiu Dear contributor, our [rules](https://github.com/pingcap/community/blob/master/challenge-programs/challenge-program-season-2-cn.md#%E7%AC%AC%E4%BA%8C%E6%AD%A5%E9%A2%86%E5%8F%96%E4%BB%BB%E5%8A%A1) has been updated. We will remove your pick if there is no update in 7 days(2020-04-06, but feel free to pick up again).

**Comment by niedhui** [comment]
Hi @SunRunAway , Do you mean remove all the existing concurrency `system variable`, and make these as `user-defined variable` for compatibility?

**Comment by SunRunAway** [comment]
> Hi @SunRunAway , Do you mean remove all the existing concurrency `system variable`, and make these as `user-defined variable` for compatibility?

Exactly.

**Comment by niedhui** [comment]
hi @SunRunAway , PR pushed. PTAL when you're free, thanks.

**Comment by niedhui** [comment]
As a summary
1. Introduce a new system variable `tidb_executor_concurrency` , deprecate `tidb_index_lookup_concurrency`, `tidb_index_lookup_join_concurrency`,`tidb_hashagg_partial_concurrency`,
`tidb_hashagg_final_concurrency`,`tidb_window_concurrency`,`tidb_projection_concurrency`,`tidb_hash_join_concurrency` . The default value of `tidb_executor_concurrency` was set to **5**(the largest default value of the these deprecated variables).
2. `tidb_distsql_scan_concurrency`, `tidb_index_serial_scan_concurrency` was kept as they are.

**Comment by SunRunAway** [comment]
@niedhui Would you like to add a documentation PR in pingcap/doc-cn for this enhancement?
