### ISSUE TITLE
Does tidb support mysql "load data" command for import data from csv file into database ?

### ISSUE THREAD

**Issue by terryzhao** [pingcap/tidb#1543]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

2. What operating system and processor architecture are you using (`go env`)?

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

4. What did you expect to see?

5. What did you see instead?

**Comment by ngaut** [comment]
Thank you for your report, We will support "load command" later in the next two weeks.
Currently you may use mysqldump  to dump data from MySQL, then use mysql client to import data to TiDB.

**Comment by terryzhao** [comment]
OK, Thanks for you quick feedback. Hope that time quickly in the next two weeks!

**Comment by foobar** [comment]
I am also expecting the support for "LOAD DATA INFILE". Nice to see it's already on the list!

**Comment by ngaut** [comment]
@foobar @terryzhao 

We just supported the "Load data" command :)

**Comment by terryzhao** [comment]
Very Good News for me!!!  Great job!




原始邮件
发件人:goroutinenotifications@github.com
收件人:pingcap/tidbtidb@noreply.github.com
抄送:terryzhaoterryzhao1981@gmail.com; Mentionmention@noreply.github.com
发送时间:2016年8月30日(周二) 16:08
主题:Re: [pingcap/tidb] Does tidb support mysql "load data" command forimport data from csv file into database ? (#1543)


@foobar @terryzhao
We just supported the "Load data" command :)
