### ISSUE TITLE
SELECT nextval reset after kill tidb

### ISSUE THREAD

**Issue by Tsuki** [pingcap/tidb#15441]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```sql
CREATE SEQUENCE seq;
SELECT nextval(seq);
+--------------+
| nextval(seq) |
+--------------+
|            1 |
+--------------+

SELECT nextval(seq);
+--------------+
| nextval(seq) |
+--------------+
|            2 |
+--------------+

docker kill tidb
SELECT nextval(seq);
+--------------+
| nextval(seq) |
+--------------+
|            1 |
+--------------+

```

2. What did you expect to see?
nextval will continuous

3. What did you see instead?
nextval of seq reseted

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
 Release Version: v4.0.0-beta.1
Git Commit Hash: 700d9def026185fe836dd56b0c39e0b4df3c320b
Git Branch: heads/refs/tags/v4.0.0-beta.1
UTC Build Time: 2020-02-28 12:11:30
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

**Comment by lysu** [comment]
hi @Tsuki thanks for you feedback.

your commit hash are develop commit that not full implement sequence, allocate logic is implement after your git hash in https://github.com/pingcap/tidb/pull/14829

and it also many fix commit abount performance, binlog support, show create table and so on

so many you can update repo to latest master to trial sequence fetual :D
