### ISSUE TITLE
Does tidb has log audit feature?

### ISSUE THREAD

**Issue by zengyongjie** [pingcap/tidb#15447]
## General Question

Does tidb have log audit feature? We want to record the detail opearation  of specific user  logined to tidb-server.

if tidb support ,  which  reference I can refer to.   I found all over the website ,  But I cannot find related topics.

tks

**Comment by lysu** [comment]
Hi @zengyongjie, TiDB core has provided an Audit plugin SPI https://github.com/pingcap/tidb/blob/master/plugin/audit.go#L79

For the third-part developer can develop their audit logic by implementing it by developing its new plugin.  https://github.com/pingcap/tidb/blob/master/docs/design/2018-12-10-plugin-framework.md

And TiDB Enterprise Edition also provides "audit log" plugin, welcome to contact us via info@pingcap.com or [contact-link](http://pingcaptidb.mikecrm.com/LxRiDG8) to learn more about Enterprise Edition
