### ISSUE TITLE
READ_FROM_STORAGE hint doesn't work as expect

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#15457]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

CREATE TABLE `t` (
  `c1` int(11) DEFAULT NULL,
  `c2` varchar(64) DEFAULT NULL
)
desc select /*+ READ_FROM_STORAGE(TIKV[t1], TIKV[t2]) */ * from t t1, t t2 where t1.c1 = t2.c1;

2. What did you expect to see?
read t1 from tikv (cop[tikv])

3. What did you see instead?
+------------------------------+------------+--------------+----------------------------------------------+
| id                           | estRows    | task         | operator info                                |
+------------------------------+------------+--------------+----------------------------------------------+
| HashLeftJoin_8               | 1048576.00 | root         | inner join, equal:[eq(test.t.c1, test.t.c1)] |
| ├─TableReader_18(Build)      | 1024.00    | root         | data:Selection_17                            |
| │ └─Selection_17             | 1024.00    | cop[tikv]    | not(isnull(test.t.c1))                       |
| │   └─TableFullScan_16       | 1024.00    | cop[tikv]    | table:t2, keep order:false                   |
| └─TableReader_15(Probe)      | 1024.00    | root         | data:Selection_14                            |
|   └─Selection_14             | 1024.00    | cop[tiflash] | not(isnull(test.t.c1))                       |
|     └─TableFullScan_13       | 1024.00    | cop[tiflash] | table:t1, keep order:false                   |
+------------------------------+------------+--------------+----------------------------------------------+

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v4.0.0-beta.1-412-gd2ef363

**Comment by zz-jason** [comment]
@lzmhhh123 PTAL
