### ISSUE TITLE
Improve the coverage of key path in table

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#15629]
## Development Task

- [x] [column.go#L382](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/column.go#L382)

- [x] [column.go#L399](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/column.go#L399)

- [x] [index.go#L324](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/tables/index.go#L324) (always >= 10 unreachable now but add a case)

- [x] [index.go#L332](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/tables/index.go#L332) 

- [x] [index.go#L404](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/tables/index.go#L404) 

- [ ] [partition.go#L275](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/tables/partition.go#L275) （unreachable but impl is correct）

- [ ] [partition.go#L331](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/tables/partition.go#L331)

**Comment by lysu** [comment]
[partition.go#L331](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/table/tables/partition.go#L331) it seems many caller of `GetPartition` didn't check nil result for this method, I'm not sure is it the real world situation?(maybe not)..

please help retake look this nil result:

https://github.com/pingcap/tidb/blob/6814f8c94b1d239f6be66a33cf3a7aa11d9f1f12/table/tables/partition.go#L331

at the partition test project if free @tiancaiamao @imtbkcat
