### ISSUE TITLE
collate: SQL from show-create-table with collate binary parses error

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#15633]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
As vividly illustrated as below, show create table result will contain the collate content.
but when SQL with the collate binary will be parsed error in return, it's wired! 
```
mysql> create table t(a int) charset=binary;
Query OK, 0 rows affected (0.15 sec)

mysql> show create table t;
+-------+--------------------------------------------------------------------------------------+
| Table | Create Table                                                                         |
+-------+--------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=binary COLLATE=binary |
+-------+--------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> drop table t;
Query OK, 0 rows affected (0.15 sec)

mysql> CREATE TABLE `t` (`a` int(11) DEFAULT NULL) ENGINE=InnoDB DEFAULT CHARSET=binary COLLATE=binary;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'binary' at line 1
```

### 2. What did you expect to see?
MySQL won't show the collate in the show-create-table result.
Since TiDB has already shown the collate in the result, we need to handle this!

1：parser the collate=binary in the parser
2：ignore the collate element in the show-create-table result when collate is binary.

### 3. What did you see instead?
show-create-result should execute successfully.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
4.0/3.1/3.0/2.1 all them

**Comment by zz-jason** [comment]
@AilinKid Could this issue breaks the data migration from TiDB to TiDB?

**Comment by AilinKid** [comment]
> @AilinKid Could this issue break the data migration from TiDB to TiDB?

I think it will.
