### ISSUE TITLE
Improve the coverage of key path in kv

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#15656]
## Development Task

- [ ] [kv.go#L273](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/kv/kv.go#L273)

- [x] [arena.go#L61](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/kv/memdb/arena.go#L61)

- [x] [arena.go#L85](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/kv/memdb/arena.go#L85)

**Comment by bobotu** [comment]
[arena.go#L61](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/kv/memdb/arena.go#L61) has been removed from new arena implementation.
https://github.com/pingcap/tidb/blob/57db6cec7ffad78e74b6ac6c67a2bfe9a6718d17/kv/memdb/arena.go#L99-L101

**Comment by jackysp** [comment]
ok

**Comment by tisonkun** [comment]
closed as UCP end and codebase changes a lot. We may later give a report on the nightly master and see how to improve UT coverage.
