### ISSUE TITLE
Improve the coverage of key path in session

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#15670]
## Development Task

- [ ] [bootstrap.go#L298](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/bootstrap.go#L298)

- [ ] [bootstrap.go#L437](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/bootstrap.go#L437)

- [ ] [bootstrap.go#L549](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/bootstrap.go#L549)

- [ ] [bootstrap.go#L604](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/bootstrap.go#L604)

- [ ] [bootstrap.go#L956](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/bootstrap.go#L956)

- [ ] [bootstrap.go#L1054](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/bootstrap.go#L1054)

- [ ] [session.go#L274](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L274)

- [ ] [session.go#L389](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L389)

- [ ] [session.go#L567](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L567)

- [ ] [session.go#L610](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L610)

- [ ] [session.go#L669](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L669)

- [ ] [session.go#L724](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L724)

- [ ] [session.go#L762](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L762)

- [ ] [session.go#L788](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L788)

- [ ] [session.go#L934](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L934)

- [ ] [session.go#L960](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L960)

- [ ] [session.go#L1175](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1175)

- [ ] [session.go#L1252](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1252)

- [ ] [session.go#L1288](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1288)

- [ ] [session.go#L1357](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1357)

- [ ] [session.go#L1420](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1420)

- [ ] [session.go#L1466](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1466)

- [ ] [session.go#L1603](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1603)

- [ ] [session.go#L1607](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1607)

- [ ] [session.go#L1637](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1637)

- [ ] [session.go#L1675](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1675)

- [ ] [session.go#L1689](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1689)

- [ ] [session.go#L1830](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1830)

- [ ] [session.go#L1962](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1962)

- [ ] [session.go#L1990](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L1990)

- [ ] [session.go#L2068](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/session.go#L2068)

- [ ] [tidb.go#L58](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/tidb.go#L58)

- [ ] [tidb.go#L82](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/tidb.go#L82)

- [ ] [tidb.go#L299](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/tidb.go#L299)

- [ ] [tidb.go#L313](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/tidb.go#L313)

- [ ] [txn.go#L275](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/txn.go#L275)

- [ ] [txn.go#L287](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/txn.go#L287)

- [x] [txn.go#L334](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/txn.go#L334)

- [ ] [txn.go#L376](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/txn.go#L376)

- [ ] [txn.go#L444](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/txn.go#L444)

**Comment by bobotu** [comment]
[txn.go#L334](https://codecov.io/gh/pingcap/tidb/src/36e89f8220e8618ea81430122a06ebc4bf04de3b/session/txn.go#L334) has been removed on master
https://github.com/pingcap/tidb/blob/51015c1c21f36e792baacad63f15f1775c016c3f/session/txn.go#L392-L399

**Comment by jackysp** [comment]
ok

**Comment by tisonkun** [comment]
Closed as code changed a lot. Perhaps we can generate new tasks from current coverage.
