### ISSUE TITLE
Improve the coverage of key path in DDL

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#15677]
## Development Task

- [ ] [column.go#L421](https://codecov.io/gh/pingcap/tidb/src/master/ddl/column.go#L421)

- [ ] [column.go#L471](https://codecov.io/gh/pingcap/tidb/src/master/ddl/column.go#L471)

- [ ] [ddl_api.go#L189](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L189)

- [ ] [ddl_api.go#L318](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L318)

- [ ] [ddl_api.go#L367](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L367)

- [ ] [ddl_api.go#L456](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L456)

- [ ] [ddl_api.go#L515](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L515)

- [ ] [ddl_api.go#L567](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L567)

- [ ] [ddl_api.go#L601](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L601)

- [ ] [ddl_api.go#L813](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L813)

- [ ] [ddl_api.go#L824](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L824)

- [ ] [ddl_api.go#L829](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L829)

- [ ] [ddl_api.go#L908](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L908)

- [ ] [ddl_api.go#L1889](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L1889)

- [ ] [ddl_api.go#L2077](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L2077)

- [ ] [ddl_api.go#L2355](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L2355)

- [ ] [ddl_api.go#L2560](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L2560)

- [ ] [ddl_api.go#L2619](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L2619)

- [ ] [ddl_api.go#L3188](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L3188)

- [ ] [ddl_api.go#L3227](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L3227)

- [ ] [ddl_api.go#L3262](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L3262)

- [ ] [ddl_api.go#L4385](https://codecov.io/gh/pingcap/tidb/src/master/ddl/ddl_api.go#L4385)

**Comment by tisonkun** [comment]
Closed as code changed a lot. Perhaps we can generate new tasks from current coverage.
