### ISSUE TITLE
Improve the coverage of key path in domain package

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#15679]
## Development Task

- [ ] [domain.go#L417](https://codecov.io/gh/pingcap/tidb/src/master/domain/domain.go#L417)

- [ ] [domain.go#L431](https://codecov.io/gh/pingcap/tidb/src/master/domain/domain.go#L431)

- [ ] [domain.go#L830](https://codecov.io/gh/pingcap/tidb/src/master/domain/domain.go#L830)

- [ ] [domain.go#L833](https://codecov.io/gh/pingcap/tidb/src/master/domain/domain.go#L833)

- [ ] [domain.go#L843](https://codecov.io/gh/pingcap/tidb/src/master/domain/domain.go#L843)

- [ ] [domain.go#L1062](https://codecov.io/gh/pingcap/tidb/src/master/domain/domain.go#L1062)

- [ ] [info.go#L202](https://codecov.io/gh/pingcap/tidb/src/master/domain/infosync/info.go#L202)

- [ ] [info.go#L237](https://codecov.io/gh/pingcap/tidb/src/master/domain/infosync/info.go#L237)

- [ ] [info.go#L497](https://codecov.io/gh/pingcap/tidb/src/master/domain/infosync/info.go#L497)

**Comment by tisonkun** [comment]
Closed as code changed a lot. Perhaps we can generate new tasks from current coverage.
