### ISSUE TITLE
executor, planner: IndexJoin error with limit

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#15691]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
download the file with all DDLs 
[randgen_index_merge_join.txt](https://github.com/pingcap/tidb/files/4381467/randgen_index_merge_join.txt)
```
source randgen_index_merge_join.txt
```
```
SELECT   /*+INL_JOIN(table1,table2,table3,table4,table5,table6,table7,table8,table9,table10,table11,table12)*/ distinct  table2 . `col_int_key` AS field1 FROM   W AS table1  RIGHT  JOIN I AS table2 ON  table1 . `col_int_key` =  table2 . `col_int`   LEFT  JOIN N AS table3 ON  table2 . `col_varchar_1024_utf8` =  table3 . `col_varchar_1024_latin1`  WHERE table1 . `col_int` IS NOT NULL   ORDER BY field1  LIMIT 4 ;
```

### 2. What did you expect to see?
MySQL
+--------+
| field1 |
+--------+
|   NULL |
|      0 |
|      1 |
|      2 |
+--------+
### 3. What did you see instead?
+--------+
| field1 |
+--------+
|   NULL |
|   NULL |
|      0 |
|      1 |
+--------+
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
5.7.25-TiDB-v4.0.0-beta-523-g7eba696bb

**Comment by XuHuaiyu** [comment]
I can not reproduce this.

**Comment by fzhedu** [comment]
> I can not reproduce this.

set tidb_max_chunk_size=2 like https://github.com/pingcap/tidb/issues/15696

**Comment by XuHuaiyu** [comment]
StreamAgg will cause this bug, HashAgg works fine.
The root cause of this issue may be the same as #15690
