### ISSUE TITLE
Fail to install TiDb by TiOps （4.0.0-beta.1）

### ISSUE THREAD

**Issue by ChinaLym** [pingcap/tidb#15729]
## Bug Report

![tidb-tiOps](https://user-images.githubusercontent.com/42663173/77630689-6dffc180-6f86-11ea-8e84-76ec2d18fdf3.PNG)

### 1. What did you do?

install TiDb by TiOps

### 2. What did you expect to see?

installed success

### 3. What did you see instead?

an network error

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

4.0.0-beta.1

**Comment by qw4990** [comment]
@cyliu0 Could you please help us with this problem?

**Comment by jebter** [comment]
Please use tiup: https://docs.pingcap.com/tidb/stable/tiup-reference
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.

**Comment by ChinaLym** [comment]
已收到~感谢来信！
