### ISSUE TITLE
gc_worker: Green GC may leave unresolved locks after resolvelock 

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/tidb#15760]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

 Test Green GC with [this tipocket case](https://github.com/pingcap/tipocket/pull/112) with nemesis: 
kill_tidb,kill_tikv,subcritical_skews,big_skews,shuffle-leader-scheduler,shuffle-region-scheduler,random-merge-scheduler

### 2. What did you expect to see?

Green GC works normally

### 3. What did you see instead?

Some locks were left after running Green GC.
![image](https://user-images.githubusercontent.com/9948422/77716903-21fe5c80-701a-11ea-82ec-83fcb0a35f26.png)

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

https://github.com/MyonKeminta/tidb/commit/03724b530d339f283b63870c8d884ac115686360
(branched from https://github.com/pingcap/tidb/commit/78dc0ed8cf52d4a5851a0c083b7a12be4b895900 , release-4.0 branch)

Green GC need to be disabled to ensure 4.0 rc's reliability.

**Comment by zhangjinpeng1987** [comment]
I think it is a critical bug of GreenGC, please fix it as soon as possible.

**Comment by MyonKeminta** [comment]
Disabled on master and release-4.0 branch. We'll investigate and fix it later.

**Comment by youjiali1995** [comment]
Fixed by https://github.com/pingcap/tidb/pull/16536 and https://github.com/pingcap/tidb/pull/16413.
