### ISSUE TITLE
planner: mergeJoin returns errors

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#15770]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

download the file with all DDLs 
[randgen_index_merge_join.txt](https://github.com/pingcap/tidb/files/4381467/randgen_index_merge_join.txt)

```
source randgen_index_merge_join.txt
```
```
explain SELECT   /*+merge_JOIN(table1,table2,table3,table4,table5,table6,table7,table8,table9,table10,table11,table12)*/ table2 . `col_int` AS field1 , table2 . `col_int_key` AS field2 FROM  B AS table1  RIGHT  JOIN Y AS table2 ON  table1 . `col_varchar_1024_utf8` =  table2 . `col_varchar_10_latin1_key`  WHERE ( table2 . `pk` <> 9 AND table2 . `pk` NOT IN (6) )   ORDER BY field1, field2 DESC LIMIT 100 OFFSET 1;
```

### 2. What did you expect to see?
run correctly
### 3. What did you see instead?
ERROR 1815 (HY000): Internal : Can’t find a proper physical plan for this query

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
5.7.25-TiDB-v4.0.0-beta-523-g7eba696bb

**Comment by francis0407** [comment]
I'm investigating.
