### ISSUE TITLE
Add interface method (ddl.DDL).CreateTableByInfo 

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#15795]
## Development Task

Add the following two method to the [`ddl.DDL` interface](https://github.com/pingcap/tidb/blob/master/ddl/ddl.go#L78):

```go
// CreateSchemaWithInfo creates a database (schema) given its database info.
// If `ifNotExists` is true, this method does nothing when a database of the
// same name already exists. Otherwise `ifNotExists` is false, returns an error.
// If `tryRetainID` is true, this method will try to keep the database ID
// specified in the `info` rather than generating new ones. This is just a hint
// though, if the ID collides with an existing database a new ID will always be
// used.
CreateSchemaWithInfo(
    ctx sessionctx.Context, 
    info *model.DBInfo, 
    ifNotExists bool, 
    tryRetainID bool) error

// CreateTableWithInfo creates a table, view or sequence given its table info.
CreateTableWithInfo(
    ctx sessionctx.Context, 
    info *model.TableInfo, 
    ifNotExists bool, 
    tryRetainID bool) error
```

To directly construct a table given its info. Since `CreateTable` etc already performed the conversion-to-info before sending out the job, the effort needed to support these APIs should be minimal.

These two functions are intended to be used by tools which embed TiDB as a library, including BR, Lightning and DM (schema tracker). This is intended to solve at least the following without changing the parser syntax:

* #14030
* pingcap/br#215

Furthermore, it is also a performance improvement since these tools natively receive a `*model.TableInfo` rather than a `*ast.CreateTableStmt`, so we could avoid the (ConstructResultOfShowCreateTable → Parse → buildTableInfo) round trip.

**Comment by L-maple** [comment]
@kennytm what is the reason that tidb hasn't supported tryRetainID? 
As I debug this code piece, I see tbInfo.ID is zero, that means the `hint TableID` specified by SQL stmt doesn't make effect?
![image](https://user-images.githubusercontent.com/20724552/155126531-2a0eb896-d8dd-435f-add6-8a33c3103f16.png)
