### ISSUE TITLE
Add remaining MySQL 5.7 functions

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#158]
Via the [MySQL Manual](https://dev.mysql.com/doc/refman/5.7/en/functions.html):

- [x] Control Flow Functions (verified as done)
- [x] String Functions https://github.com/pingcap/tidb/issues/310
- [x] Numeric Functions (appear done, not competely verified)
- [x] Date and Time Functions https://github.com/pingcap/tidb/issues/236
- [x] Bit Functions (appears done)
- [x] Cast Functions (appears done)
- [ ] Encryption and Compression https://github.com/pingcap/tidb/issues/2632
- [ ] Information Functions https://github.com/pingcap/tidb/issues/8438
- [ ] JSON https://github.com/pingcap/tidb/issues/7546
- [ ] Aggregate Functions https://github.com/pingcap/tidb/issues/7623
- [x] Misc Functions https://github.com/pingcap/tidb/issues/8439

**Comment by w5s5j** [comment]
Hi, I would like to contribute to tidb and after watching the presentation of Qi Liu, I guess this might be a good starting point. It would be nice if some further pointers could be provided. Thanks in advanced :)

**Comment by ngaut** [comment]
Thank you @w5s5j 
I think #236 is a good start :)
Fire an issue when you are ready to hunt any of the functions in #236

**Comment by c4pt0r** [comment]
@Tratar 
we have a document for contributors who wants to add built-in functions to TiDB, you can pick one function in https://github.com/pingcap/tidb/issues/236, and follow the steps in https://pingcap.github.io/blog/2016/12/19/adding-built-in-function/ 
Happy hacking :)

**Comment by shenli** [comment]
@Tratar You can refer to https://github.com/pingcap/tidb/issues/310 and  https://github.com/pingcap/tidb/issues/236 for the unimplemented builtin functions. If you have any problem, please let us know.
Thanks!
