### ISSUE TITLE
Lost connection in creating sequence  seq maxvalue=9223372036854775808

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#15820]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
create sequence seq maxvalue=9223372036854775808;
```

### 2. What did you expect to see?
create sequence failure

### 3. What did you see instead?
```
mysql> create sequence seq maxvalue=9223372036854775808;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-beta.2-91-g3ea709e71
Git Commit Hash: 3ea709e71f13857652581793c450d7f5120f870e
Git Branch: release-4.0
UTC Build Time: 2020-03-30 02:13:52
GoVersion: go1.14.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by AilinKid** [comment]
Actually it's a common case in TiDB parser.
If a value exceeds int64/uint64 that defined, it will cause connection lost.

**Comment by AilinKid** [comment]
close suggested.
