### ISSUE TITLE
grafana shows "request error"

### ISSUE THREAD

**Issue by bearHunting** [pingcap/tidb#15950]
### 1. What did you do?
I open grafana, select 7 days range

### 2. What did you expect to see?
show system conditions correctly

### 3. What did you see instead?
red alerm on some panels says "reqeust error"  
details please refer to https://asktug.com/t/topic/2227/9
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
3.0.5

**Comment by XuHuaiyu** [comment]
hi, @bearHunting 
Maybe you can try to set the `configuration-->Datasource-->[your cluster]-->Query timeout` to a larger value, and see whether it'll work.

**Comment by bearHunting** [comment]
Hi Huaiyu,
Confirmed that it's gateway timeout setting issue. Our dba has changed it. Works fine now. I'll close it
