### ISSUE TITLE
Tiflash bootstrap failed because sync sequence schema error

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#15957]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
# firstly 
use test;
create sequence seq

# secondly
# ./tiflash server --config-file conf/tiflash.toml
```

### 2. What did you expect to see?
Tiflash bootstrap success

### 3. What did you see instead?
Tiflash bootstrap failed

2020.04.01 08:06:21.426501 [ 1 ] <Error> **Application: Bootstrap failed because sync schema error**: DB::Exception: void TiDB::TableInfo::deserialize(const String&): Parse TiDB schema JSON failed (TableInfo): Null pointer, json: {"id":45,"name":{"O":"seq","L":"seq"},"charset":"","collate":"","cols":null,"index_info":null,"fk_info":null,"state":5,"pk_is_handle":false,"comment":"","auto_inc_id":0,"max_col_id":0,"max_idx_id":0,"update_timestamp":415689164486606856,"ShardRowIDBits":0,"max_shard_row_id_bits":0,"auto_random_bits":0,"pre_split_regions":0,"partition":null,"compression":"","view":null,"sequence":{"sequence_start":1,"sequence_cache":true,"sequence_order":false,"sequence_cycle":false,"sequence_min_value":1,"sequence_max_value":9223372036854775806,"sequence_increment":1,"sequence_cache_value":1000,"sequence_comment":""},"Lock":null,"version":3,"tiflash_replica":null}
 We will sleep 3 seconds and try again.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-beta.2-115-g52bf81d
Git Commit Hash: 52bf81d651188fdd7fc86f3e1de3a7cfffd2cf38
Git Branch: HEAD
UTC Build Time: 2020-03-31 12:20:04
GoVersion: go1.13.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

TiFlash 4.0.0
Release Version: bfc188f41
Git Commit Hash: bfc188f419c862ab753b3f88e17c610ed1d3d75f
Git Branch:      release-4.0
UTC Build Time:  2020-03-11 01:37:06

Raft Proxy
Release Version:   4.0.0-beta
Git Commit Hash:   f8b08ed44b94ab5a88d93c434b162cb8e8c21aac
Git Commit Branch: HEAD
UTC Build Time:    2020-03-11 01:05:10
Rust Version:      rustc 1.42.0-nightly (0de96d37f 2019-12-19)
```

**Comment by zz-jason** [comment]
@bb7133 PTAL
