### ISSUE TITLE
composite index expired

### ISSUE THREAD

**Issue by zhangtw1** [pingcap/tidb#16035]
table：
CREATE TABLE `ss_robot_task_statistics_data_origin` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `type` int(8) unsigned NOT NULL,
  `status` tinyint(3) unsigned NOT NULL,
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_create_time_type_status` (`create_time`,`type`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=864650805；

when i use "explain select * from urobot.ss_robot_task_statistics_data_origin  where create_time= '2019-01-01' and type  = 1 and status = 1;" index work;
when i use "explain select * from urobot.ss_robot_task_statistics_data_origin  where create_time= '2019-01-01' ;"it doesnt work;
i didn't find the answer when i google it，hope someone help

------------------------------------------------------------------------------------------------
Maybe I read the wrong result，when i excute again，both of them used index。
when i use  “explain select * from urobot.ss_robot_task_statistics_data_origin  where create_time > '2010-01-03 11:49:05' and status = 3;”  return 700 million data and index dosent work.
so i use "index hint" to solve the problem？

**Comment by winoros** [comment]
@zhangtw1 Could you show us the `explain analyze` result of the two cases?

**Comment by zhangtw1** [comment]
i can't excute the `explain analyze`，because the second sql return 700 million data。

**Comment by zimulala** [comment]
PTAL @winoros

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates you can reopen it.
