### ISSUE TITLE
record whether a statement hit plan cache in slow log

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#16197]
## Development Task

we may need to record whether a statement hit plan cache in slow log. There are some beneficial:
1. to identify the slow reason is related to the planner.
2. if a plan is sub-optimal, we can further figure out whether it's caused by the plan cache.

**Comment by zz-jason** [comment]
@eurekaka How do you think?

**Comment by eurekaka** [comment]
> @eurekaka How do you think?

Sounds reasonable.

**Comment by ChenPeng2013** [comment]
verified on 
master: v4.0.0-beta.2-547-g94a722e2d
release-4.0: v4.0.0-19-g13522b901
