### ISSUE TITLE
Failed Integration Push Down Test

### ISSUE THREAD

**Issue by lawyerphx** [pingcap/tidb#16190]
### 1. What did you do?
I got Failed Integration Push Down Test failed when I merged my PR and ran `tidb_ghpr_integration_copr_test`.
It seems that no relevant codes are modified in my [PR](https://github.com/pingcap/tidb/pull/15941)
This error logs are listed [here](https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/3315/pipeline)

### 2. What did you expect to see?

No error

### 3. What did you see instead?

Error logs shown before.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
tidb/master

**Comment by SunRunAway** [comment]
[log (3).txt](https://github.com/pingcap/tidb/files/4449289/log.3.txt)
