### ISSUE TITLE
record plan cache hit ratio or count in statement summary table

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#16217]
## Development Task

It's a [suggestion](https://github.com/pingcap/tidb/issues/16127#issuecomment-611286377) from @wwar while we discussing how to observe whether a statement hits the plan cache. The benefit is like he said:

> This will help with observing the ratio in real-time.

**Comment by wwar** [comment]
> Do you mean to show whether the prepared statement is put into the plan cache?

Yes, but more specifically, I was thinking of the timestamp. For example in MySQL 8.0 which has query samples, it will show you:

```
                DIGEST_TEXT: SELECT * FROM `events_statements_summary_by_digest`
..
          QUERY_SAMPLE_TEXT: select * from events_statements_summary_by_digest
          QUERY_SAMPLE_SEEN: 2020-04-08 21:14:09.267143
```

A bit of a tangent, but TiDB has `DIGEST_TEXT` and `QUERY_SAMPLE_TEXT`, but not `QUERY_SAMPLE_SEEN` (could be useful!).

My suspicion is that older plan caches may suffer more from data drift, so that is why knowing "when" the cache was prepared is useful. Rebuilding the cache could also change the plan (either positively or negatively), so it could also be interesting if there are any plan cache refreshes which correspond to significant changes in performance.

So something like the following (there are already fields for `PLAN` and `PLAN_DIGEST`):

`PLAN_IN_CACHE`: bool (if it is currently in the cache)
`PLAN_CACHE_HITS`: uint64
`PLAN_CACHE_MISSES`: uint64
`PLAN_LAST_UPDATED`: timestamp

**Comment by lawyerphx** [comment]
> `PLAN_IN_CACHE`: bool (if it is currently in the cache)
> `PLAN_CACHE_HITS`: uint64
> `PLAN_CACHE_MISSES`: uint64
> `PLAN_LAST_UPDATED`: timestamp

Do you have any suggestions for the system variable names of these four variables?

> My suspicion is that older plan caches may suffer more from data drift, so that is why knowing "when" the cache was prepared is useful. Rebuilding the cache could also change the plan (either positively or negatively), so it could also be interesting if there are any plan cache refreshes which correspond to significant changes in performance.


For memory-saving considerations, I plan to use "not changed" as the value of `PLAN_LAST_UPDATED` for the plans that have not been modified since being created by `prepare` statements.

**Comment by wwar** [comment]
> Do you have any suggestions for the system variable names of these four variables?

I looked at your PR, and I think there is a misunderstanding :-) I had intended for these to be statistics recorded per query digest (i.e. the table `performance_schema.events_statements_summary_by_digest ` which will be renamed in https://github.com/pingcap/tidb/pull/16188 ).

They don't need to be session variables - the session variable trick was only for `last_statement_found_in_plan_cache`, to avoid having to send the client a warning).

i.e. only a boolean for the last statement makes sense in session context. For the other statistics mentioned here it is digest context in `events_statements_summary_by_digest`.

**Comment by eurekaka** [comment]
> My suspicion is that older plan caches may suffer more from data drift, so that is why knowing "when" the cache was prepared is useful.

I still didn't get the point of `PLAN_LAST_UPDATED`, what problem is this information intended to solve? Plan is put into cache by `execute`, I guess what is needed here is to show the parameters of the `execute` when the plan is put into cache?

**Comment by wwar** [comment]
> I still didn't get the point of `PLAN_LAST_UPDATED`, what problem is this information intended to solve? Plan is put into cache by `execute`, I guess what is needed here is to show the parameters of the `execute` when the plan is put into cache?

The discussion forked from `execute`. This is for a global table which shows all statement digests executed on the server. In this context, assuming the plan cache is global it is nice to know when the cache was created.

(If the cache is not global, this makes less sense. But I assume it is?)

**Comment by eurekaka** [comment]
Plan cache is not global for now, each session would hold its own cache.

**Comment by ChenPeng2013** [comment]
plan_in_cache doesn't be set to 0 when last_plan_from_cache is false  https://github.com/pingcap/tidb/pull/18067
