### ISSUE TITLE
Support ComSetOption

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1623]
See http://dev.mysql.com/doc/internals/en/com-set-option.html
http://dev.mysql.com/doc/internals/en/multi-statement.html

**Comment by morgo** [comment]
I believe this has been added: https://github.com/pingcap/tidb/blob/master/server/conn_stmt.go#L545-L574

**Comment by lysu** [comment]
yes, this has be addressed by https://github.com/pingcap/tidb/pull/1628, let's close it.
