### ISSUE TITLE
only_full_group_by is checked wrongly

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#16279]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
``` sql
create table s(a int);
select count(a) , date_format(a, '%Y-%m-%d') from s group by date_format(a, '%Y-%m-%d');
```

### 2. What did you expect to see?
``` sql
mysql> select count(a) , date_format(a, '%Y-%m-%d') from s group by date_format(a, '%Y-%m-%d');
Empty set (0.00 sec)
```

### 3. What did you see instead?
``` sql
tidb> select count(a) , date_format(a, '%Y-%m-%d') from s group by date_format(a, '%Y-%m-%d');
ERROR 1055 (42000): Expression #2 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'test.s.a' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
`496cb870d50922ac0801307bfcfc229e1acb1009` on master

**Comment by zz-jason** [comment]
@XuHuaiyu Please fix it ASAP.

**Comment by XuHuaiyu** [comment]
This problem is introduced by https://github.com/pingcap/tidb/pull/14963
