### ISSUE TITLE
UCP: Refine the explain message of expression 

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#16276]
## Description

```
TiDB(root@127.0.0.1:test) > create index expr_idx on t((lower(a)));
Query OK, 0 rows affected (0.02 sec)

TiDB(root@127.0.0.1:test) > explain select lower(a) from t where lower(a) = 'a';
+------------------------+---------+-----------+-----------------------------------------+-------------------------------------------------+
| id                     | estRows | task      | access object                           | operator info                                   |
+------------------------+---------+-----------+-----------------------------------------+-------------------------------------------------+
| IndexReader_6          | 10.00   | root      |                                         | index:IndexRangeScan_5                          |
| └─IndexRangeScan_5     | 10.00   | cop[tikv] | table:t, index:expr_idx(_V$_expr_idx_0) | range:["a","a"], keep order:false, stats:pseudo |
+------------------------+---------+-----------+-----------------------------------------+-------------------------------------------------+
2 rows in set (0.00 sec)
```

index:expr_idx(_V$_expr_idx_0)

The `_V$_expr_idx_0` is used internally and should be output as the expression of the index.

## Score

* 300

## Mentor(s)

* @wjhuang2016 

Contact the mentors: **#sig-planner** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang

## Learning Materials

* Chinese: [表达式索引](https://pingcap.com/docs-cn/stable/reference/sql/statements/create-index/#create-index)
* English: [expression index](https://pingcap.com/docs/stable/reference/sql/statements/create-index/#create-index)

**Comment by nullnotnil** [comment]
See also https://github.com/pingcap/tidb/issues/16822 for another simple issue related to EXPLAIN output.

**Comment by wjhuang2016** [comment]
@yufan022 
Hi, if you have any problem with this issue, we can discuss it in the DDL slack channel.

**Comment by yufan022** [comment]
> @yufan022
> Hi, if you have any problem with this issue, we can discuss it in the DDL slack channel.

Thanks, ending my traveling before a few day, i will continue this issue.
