### ISSUE TITLE
Green GC may miss locks when there are newly added stores

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#16308]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead?
GC worker doesn't check cleaned stores when retrying. If a region is transferred to newly added stores and then it's transferred back to cleaned stores, locks in this region are missed. For example:
1. A cluster has 1 TiDB and 3 TiKVs. Each region has 1 replica.
2. TiDB registers lock observers to 3 TiKVs and scans locks of them.
3. TiKV-4 is added and region-1 is transferred to TiKV-4.
4. The first round of physical resolve lock is failed due to newly added TiKV-4.
5. Region-1 is transferred back to TiKV-1.
6. TiDB retries to resolve uncleaned TiKV-4 and it's cleaned at final.
7. All locks in region-1 are missed.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
4.0

**Comment by zhangjinpeng1987** [comment]
Find the root cause, still need to test to check if there are other cases can cause such problem.

**Comment by youjiali1995** [comment]
Sorry, I got it wrong. Green GC won't miss locks in such case..😢
