### ISSUE TITLE
unit test TestWriteWriteConflict fails

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#16345]
FAIL: isolation_test.go:106: testIsolationSuite.TestWriteWriteConflict

## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
make gotest
```

### 3. What did you see instead?

```
FAIL: isolation_test.go:106: testIsolationSuite.TestWriteWriteConflict

isolation_test.go:75:
    c.Assert(kv.IsTxnRetryableError(err) || terror.ErrorEqual(err, terror.ErrResultUndetermined), IsTrue)
... obtained bool = false
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

master branch (e90aac271)

**Comment by SunRunAway** [comment]
@disksing PTAL

**Comment by qw4990** [comment]
+1 https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33355/pipeline

**Comment by SunRunAway** [comment]
@cfzjywxk Another occurrence.
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/34207/pipeline
