### ISSUE TITLE
Support more scan details

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#16350]
### Is your feature request related to a problem? Please describe:

Currently the scan detail returned to TiDB is not conforming the documentation, and it does not contain enough information as well.

Kvproto PR https://github.com/pingcap/kvproto/pull/600 adds more fields to the scan detail structure in the protocol, so that we can add more info into it.

Also related to https://github.com/tikv/tikv/issues/7436.
### Describe the feature you'd like:

Introduce the following fields, in TiKV slow query, as well as when returning to TiDB;

```rust
    uint64 processed_versions = 1;
    uint64 total_versions = 2;
    uint64 rocksdb_delete_skipped_count = 3;
    uint64 rocksdb_key_skipped_count = 4;
    uint64 rocksdb_block_cache_hit_count = 5;
    uint64 rocksdb_block_read_count = 6;
    uint64 rocksdb_block_read_byte = 7;
```

- Processed_versions means the number of visible versions. For example, deleted versions are not included.
- Total_versions means the number of all scanned versions Deleted versions are included.
- The rest fields: See [RocksDB PerfContext Wiki](https://github.com/facebook/rocksdb/wiki/Perf-Context-and-IO-Stats-Context)

In order to keep compatibility with old TiDB, we still need to preserve the original return data structure (and fill data for it).

**Comment by qw4990** [comment]
Support this feature after https://github.com/tikv/tikv/pull/7563 is merged.

**Comment by breeswish** [comment]
Implemented in https://github.com/pingcap/tidb/pull/20492
