### ISSUE TITLE
When the primary key column inserts null and 0 values through "ignore", it should return a "duplicate entry" warning

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#16366]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
```
create table t(c numeric primary key);
insert ignore into t values(null);
insert into t values(0);
select * from t;
```

### 2. What did you expect to see?
```
mysql> insert into t values(0);
ERROR 1062 (23000): Duplicate entry '0' for key 'PRIMARY'
mysql> select * from t;
+---+
| c |
+---+
| 0 |
+---+
1 row in set (0.00 sec)
```

### 3. What did you see instead?
```
tidb> insert into t values(0);
Query OK, 1 row affected (0.00 sec)

tidb> select * from t;
+---+
| c |
+---+
| 0 |
| 0 |
+---+
2 rows in set (0.00 sec)
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-beta.2-221-g15e961ad3
Git Commit Hash: 15e961ad379c4f98bdcef2dc6485d1ce4587e292
Git Branch: master

**Comment by zz-jason** [comment]
@SunRunAway PTAL

**Comment by Reminiscent** [comment]
Same with #16025
