### ISSUE TITLE
Optimize "select max(id) from t"

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1638]
If there is an index on id column, we should build a better plan which will use index to calculate max(id).

**Comment by shenli** [comment]
Why close this issue? @hanfei1991

**Comment by hanfei1991** [comment]
@shenli because we have implemented steamed agg.

**Comment by shenli** [comment]
But we could use index to get max/min value of a column. It is better than streamed aggregation.

**Comment by hanfei1991** [comment]
Well, we should rewrite select max(id) from t to select id from t order by id desc limit 1.

**Comment by winoros** [comment]
We should rewrite `select max(id) from t` to `select id from (select 1) tmp left outer join t where not isnull(id) order by id limit 1 `.

**Comment by hanfei1991** [comment]
`select max(id) from (select id from t order by id desc limit 1 where id is not null) t` is also ok.
