### ISSUE TITLE
Index merge doesn't take effect when using prefix key

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#16407]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
```
create table t(a int,b char(100),key(a),key(b(10));
desc select /*+ use_index_merge(t) */ * from t where a=10 or b="x";
```
### 2. What did you expect to see?
use_index_merge takes effect
### 3. What did you see instead?
```
+-------------------------+----------+-----------+---------------+-------------------------------------+
| id                      | estRows  | task      | access object | operator info                       |
+-------------------------+----------+-----------+---------------+-------------------------------------+
| TableReader_7           | 8000.00  | root      |               | data:Selection_6                    |
| └─Selection_6           | 8000.00  | cop[tikv] |               | or(eq(d1.t.a, 10), eq(d1.t.b, "x")) |
|   └─TableFullScan_5     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo      |
+-------------------------+----------+-----------+---------------+-------------------------------------+
3 rows in set, 1 warning (0.01 sec)
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-rc-33-gd69868961
Git Commit Hash: d69868961361126d4788b68fd6cd597adb3ef66c
Git Branch: release-4.0
UTC Build Time: 2020-04-15 02:59:00
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by zz-jason** [comment]
@lzmhhh123 PTAL

**Comment by qw4990** [comment]
@tangwz Do you willing to help us fix this?

**Comment by tangwz** [comment]
@qw4990 I will give a try. 

/aasign

**Comment by tangwz** [comment]
I saw a comment in function `accessPathsForConds(conditions []expression.Expression, usedIndexCount int)`:

```
// If AccessConds is empty or tableFilter is not empty, we ignore the access path.
// Now these conditions are too strict.
```

I think for prefix key we need change these conditions especially the condition **tableFilter is not empty**.

Should I change that limit?
