### ISSUE TITLE
IndexMerge get wrong result

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#16404]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
download the file with all DDLs 
[randgen_index_merge.txt](https://github.com/pingcap/tidb/files/4479741/randgen_index_merge.txt)
```
source randgen_index_merge.txt
```    
```
SELECT /*+ use_index_merge(table_20_utf8_4) */ count(*) FROM table_20_utf8_4 where `col_char(20)_key_signed` = "it's" or `col_bigint_key_signed` > -2617317647556123437;
```   
### 2. What did you expect to see?
16
### 3. What did you see instead?
0
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-rc-33-gd69868961
Git Commit Hash: d69868961361126d4788b68fd6cd597adb3ef66c
Git Branch: release-4.0
UTC Build Time: 2020-04-15 02:59:00
GoVersion: go1.13.8
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by zz-jason** [comment]
@eurekaka PTAL

**Comment by eurekaka** [comment]
https://github.com/pingcap/tidb/pull/17032 can fix this problem.

**Comment by ChenPeng2013** [comment]
verified on
master: v4.0.0-beta.2-524-g73fe3ca4d
release-4.0: v4.0.0
