### ISSUE TITLE
Empty `tidb_enable_stmt_summary` after TiDB cluster is initialized.

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#16438]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Setup a new TiDB cluster, and then check system variable `tidb_enable_stmt_summary`:

### 2. What did you expect to see?

A non-empty result.

### 3. What did you see instead?

An empty result:
```
tidb> select @@tidb_enable_stmt_summary;
+----------------------------+
| @@tidb_enable_stmt_summary |
+----------------------------+
|                            |
+----------------------------+
1 row in set (0.00 sec)
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Latest master.

**Comment by bb7133** [comment]
PTAL @djshow832

**Comment by djshow832** [comment]
Default value is '', indicating reading a higher level configuration. 
If session value is '', read the global value. If the global value is '', read the config.
MySQL has no variables acting like that, so we have no reference.
If I change the result to `1` or `0`, then users can't know the current value.
