### ISSUE TITLE
Can't start tidb-server in cluster

### ISSUE THREAD

**Issue by qiuyi21** [pingcap/tidb#1643]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.6.3 linux/amd64

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
I follow https://github.com/pingcap/docs/blob/master/op-guide/clustering.md to setup cluster with 3 nodes.

4. What did you expect to see?

5. What did you see instead?
When I run **tidb-server --store=tikv --path="10.202.91.1:2379,10.202.91.2:2379,10.202.91.3:2379?cluster=1"** it will failed:
`2016/08/26 15:26:31 rpc_worker.go:115: [info] [pd] connect to pd server http://10.202.91.2:2379
2016/08/26 15:26:31 rpc_worker.go:118: [warning] [pd] failed connect pd server: dial tcp: too many colons in address http://10.202.91.2:2379, will retry later
2016/08/26 15:26:32 rpc_worker.go:115: [info] [pd] connect to pd server http://10.202.91.2:2379
2016/08/26 15:26:32 rpc_worker.go:118: [warning] [pd] failed connect pd server: dial tcp: too many colons in address http://10.202.91.2:2379, will retry later`

**Comment by siddontang** [comment]
@huachaohuang

**Comment by shenli** [comment]
@qiuyi21 May I have your TiDB/PD's git version?

**Comment by qiuyi21** [comment]
@shenli 
pd: d062c207379d9800f4b41fdc70d98ef59abca047
tidb: 8169806756ae65d605bc65e97bdd8edec17af66c
tikv: 8bd91c6cb51ba63cc7bc684d4f5885968dfe9ddc

**Comment by huachaohuang** [comment]
@qiuyi21 May I have your completed log of TiDB?

**Comment by shenli** [comment]
It seems that you are using out of date code. Please use the latest code for TIDB/TiKV/PD

➜  tidb git:(master) ✗ git log | grep -A 5 8169806756ae65d605bc65e97bdd8edec17af66c
commit 8169806756ae65d605bc65e97bdd8edec17af66c
Author: Shen Li <shenli3514@gmail.com>
Date:   Sat Jul 30 12:08:36 2016 +0800

    *: Use prometheus for metrics (#1525)

**Comment by shenli** [comment]
@qiuyi21 Have you run TiDB cluster successfully?

**Comment by qiuyi21** [comment]
@shenli Thank you! I will try it and report the result tomorrow.
