### ISSUE TITLE
plan cache: capacity can be set to -1

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#16452]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
prepared-plan-cache.capacity=0
./tidb-server --config ../config/config.toml.example --config-check

prepared-plan-cache.capacity=-1
./tidb-server --config ../config/config.toml.example --config-check
```
### 2. What did you expect to see?
```
prepared-plan-cache.capacity=0
./tidb-server --config ../config/config.toml.example --config-check
load config file: /Users/chenpeng/go/src/github.com/pingcap/tidb/config/config.toml.example
invalid config capacity in [prepared-plan-cache] should be at least 1

prepared-plan-cache.capacity=-1
./tidb-server --config ../config/config.toml.example --config-check
load config file: /Users/chenpeng/go/src/github.com/pingcap/tidb/config/config.toml.example
invalid config capacity in [prepared-plan-cache] should be at least 1
```
### 3. What did you see instead?
```
prepared-plan-cache.capacity=0
./tidb-server --config ../config/config.toml.example --config-check
load config file: /Users/chenpeng/go/src/github.com/pingcap/tidb/config/config.toml.example
invalid config capacity in [prepared-plan-cache] should be at least 1

prepared-plan-cache.capacity=-1
./tidb-server --config ../config/config.toml.example --config-check
config check successful
```
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-rc-55-ga6ba42e60
Git Commit Hash: a6ba42e6011fedc1bda3516f588948d0522c0878
Git Branch: release-4.0
UTC Build Time: 2020-04-16 03:14:48
GoVersion: go1.13.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by eurekaka** [comment]
`prepared-plan-cache-capacity` is defined as `uint` in configuration, so when parsing the toml config file, the `-1` is converted to `18446744073709551615` hence the checker does not report error. Values in toml file are type-defined, so I think we don't need to change this behavior?

**Comment by zz-jason** [comment]
> `prepared-plan-cache-capacity` is defined as `uint` in configuration, so when parsing the toml config file, the `-1` is converted to `18446744073709551615` hence the checker does not report error. Values in toml file are type-defined, so I think we can update the documentation in [pingcap.com/docs-cn/stable/reference/configuration/tidb-server/configuration-file/#capacity](https://pingcap.com/docs-cn/stable/reference/configuration/tidb-server/configuration-file/#capacity) and don't need to change the code behavior?

Make sense, I've moved this issue to the `Need User Document` column in `SIG Plan Kanban`, please update the user document.

**Comment by ChenPeng2013** [comment]
verified on docs-cn

**Comment by ChenPeng2013** [comment]
@eurekaka Do we need to update the english document ?
