### ISSUE TITLE
UCP: make "AutoRandom" to be `auto_increment_increment`-aware.

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#16508]
## Description

Feature "AutoRandom" is added to TiDB v3.1 and v4.0, as a replacement of "AutoIncrement". This feature aims to provide a better solution to automatically generate primary key ID and avoid hotspots during a heavy write scenario.

For now, as an alternative to generate "auto" keys, "AutoRandom" is not `auto_increment_increment` aware, which lead to the following unexpected results when using JDBC, for example:

```
# Using MySQL client.
tidb> create table t(a bigint key auto_random)
Query OK, 0 rows affected, 1 warning (0.02 sec)
tidb> set global auto_increment_increment=2;                                                           
Query OK, 0 rows affected (0.00 sec)
```
And then,
```
// Scala code
object Test {
  val tidbUrl = s"jdbc:mysql://127.0.0.1:4000/test"

  def main(args: Array[String]): Unit = {
    val conn = DriverManager.getConnection(tidbUrl, username, password)
    val stmt = conn.createStatement()
    val incremental = {
      val res = stmt.executeQuery("select @@auto_increment_increment")
      res.next()
      res.getInt(1)
    }
    println(s"Current auto_increment_increment: $incremental")
    stmt.executeUpdate("insert into t values (), (), (), ()", Statement.RETURN_GENERATED_KEYS)
    val res = stmt.getGeneratedKeys()
    new Iterator[String] {
      def hasNext = res.next()
      def next() = res.getString(1)
    }.toStream.foreach(println)
    stmt.close()
    conn.close()
  }
}
```
Run the codes above, you'll get something like:
```
Current auto_increment_increment: 2
1879048217
1879048219
1879048221
1879048223
```
However, the actual inserted keys are:
```
tidb> select * from t;
+------------+
| a          |
+------------+
| 1879048217 |
| 1879048218 |
| 1879048219 |
| 1879048220 |
+------------+
4 rows in set (0.00 sec)
```

Reason of the wrong answer is that JDBC tries to calculate the generated keys through `LastInsertID()` and `auto_increment_increment`.

You can refer to #14301 to get the way how it is supported by "AutoIncrement".

## Score

* 1680

## Mentor(s)

* [@AilinKid ](https://github.com/AilinKid)
* [@tangenta](https://github.com/tangenta)

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Golang only.

## Learning Materials
 
* [AUTO_RANDOM column option](https://pingcap.com/docs/dev/reference/sql/attributes/auto-random/)
* [System variable 'auto_increment_increment' and 'auto_increment_offset'](https://dev.mysql.com/doc/refman/8.0/en/replication-options-master.html#sysvar_auto_increment_increment)
* [Closed issue 14245](https://github.com/pingcap/tidb/issues/14245)
* [Retrieving AUTO_INCREMENT Column Values through JDBC](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-usagenotes-last-insert-id.html)

**Comment by niedhui** [comment]
@bb7133 @tangenta Hi mentors, currently I had a pending pr waiting for review, may I do this without pick-up-challenge first?

**Comment by tangenta** [comment]
@niedhui Sorry, I am working on this issue because the deadline is coming soon. We are appreciated that if you could pick another challenge.
