### ISSUE TITLE
Record checksums for temporary chunks in disk

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#16532]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now we have spilled chunks data to disk when Join or Sort exceeds the memory quota. But the data in disk should be appended with a checksum (like crc64), to ensure that the data read from disk is exactly the same as the data written.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

The disk implementation is in https://github.com/pingcap/tidb/blob/827edde/util/chunk/disk.go

**Comment by mmyj** [comment]
pick
