### ISSUE TITLE
Major version not compatible with `go mod`

### ISSUE THREAD

**Issue by yujunz** [pingcap/tidb#16568]
### 1. What did you do?

```
➜  go mod init example.com/m
➜  go get github.com/pingcap/tidb
go: github.com/pingcap/tidb upgrade => v2.0.11+incompatible
➜  go get github.com/pingcap/tidb@v3.1.0
go get github.com/pingcap/tidb@v3.1.0: github.com/pingcap/tidb@v3.1.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v3
go get github.com/pingcap/tidb
```

### 2. What did you expect to see?

Get latest or specified version of tidb module

### 3. What did you see instead?

* Latest is parsed as ` v2.0.11+incompatible` which seems the last version NOT using `go mod`
* v3 module is incompatible with `go mod`

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

Not relevant.

**Comment by tiancaiamao** [comment]
Duplicated by https://github.com/pingcap/tidb/issues/16381
