### ISSUE TITLE
planner: eliminate aggregation with distinct

### ISSUE THREAD

**Issue by SeaRise** [pingcap/tidb#16581]
## Description
for table t (a int, b int, key int)
```
(10, 20, 10)
(10, 10, 10)
(20, 10, 13)
```

```
select count(distinct a), sum(b) from t group by key

==>

select count(a), sum(sum_b)
from (
	select a, sum(b) as sum_b, gid from (
		Expand(
			 projections = 
					[(a, null, key, 0),
                                         (null, b, key, 1)
					], 
			 t)
	)
	group by a, gid, key
)
group by key
```

`Expand` is extand `t` to `t_extend(a int, b int, key int, gid int)`
```
(10, null, 10, 0)
(null, 20, 10, 1)

(10, null, 10, 0)
(null, 10, 10, 1)

(20, null, 13, 0)
(null, 10, 13, 1)
```

spark sql use a operator `Extend` to extend `t` to `t_extend`.
we can use sql as follows to extend
```
	mem_table(gid int)
        (0)
	(1)
	
select if((gid = 0) a else null), if ((gid = 1) b else null), gid from t join mem_table
```
or implement a more efficient operator like `Extend` to extend `t` to `t_extend`.

## Score
1200

## SIG slack channel（must）:
Contact us in channel `#sig-planner` of [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)
## Mentor(must)
@winoros 
## Recommended Skills：
- Relational algebra

**Comment by ThySinner** [comment]
Sorry I didn't get the point. Why expand the table? I found the following sql
```sql
select count(a), sum(sum_b)
from (
	select a, sum(b) as sum_b, gid from t
	group by a, key
)
group by key
```
has an equivalent semantic and will generate less execution operators, which means it is more likely to have a better performance.
However, if we add an `expand` operator like Spark SQL does, we could use it to implement `with rollup` and `with cube` clauses.

**Comment by Tangruilin** [comment]
I'm interested in this problem, was it solved by others? /cc @winoros
