### ISSUE TITLE
Control to perform write operations more than two DDL states

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#1659]
If a write operation during execution the DDL changes two or more states, it has problems.

**Comment by disksing** [comment]
I think we can add a `Context` arguments for `txn.Commit()` and cancel the context when the commit process is not suppose to continue.
Correspondingly, we need to check the context at every step of 2PC commit, abort the txn as soon as context canceled.

**Comment by coocood** [comment]
Fixed by https://github.com/pingcap/tidb/pull/2327
