### ISSUE TITLE
different returns of STR_TO_DATE from mysql

### ISSUE THREAD

**Issue by Illyrix** [pingcap/tidb#16599]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

execute `select STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s');`

### 2. What did you expect to see?

on mysql 5.7.28:
+---------------------------------------------------------+
| STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s') |
+---------------------------------------------------------+
| 0000-00-00 00:00:00                                     |
+---------------------------------------------------------+
1 row in set (0.56 sec)

### 3. What did you see instead?

on tidb v4.0.0rc:
+---------------------------------------------------------+
| STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s') |
+---------------------------------------------------------+
| NULL                                                    |
+---------------------------------------------------------+
1 row in set, 1 warning (0.00 sec)

but tidb v3.0.12 is ok

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
5.7.25-TiDB-v4.0.0-rc

**Comment by dyzsr** [comment]
If `sql_mode` contains `NO_ZERO_DATE`, the result would be `NULL`.
```
mysql> select STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s');
+---------------------------------------------------------+
| STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s') |
+---------------------------------------------------------+
| NULL                                                    |
+---------------------------------------------------------+

mysql> select @@sql_mode;
+----------------------------------------+
| @@sql_mode                             |
+----------------------------------------+
| ... ,NO_ZERO_IN_DATE,NO_ZERO_DATE, ... |
+----------------------------------------+
```

Otherwise, it would be the expected answer.

```
mysql> set @@sql_mode := replace(@@sql_mode, 'NO_ZERO_DATE', '');
Query OK, 0 rows affected (0.00 sec)

mysql> select @@sql_mode;
+---------------------------+
| @@sql_mode                |
+---------------------------+
| ... ,NO_ZERO_IN_DATE, ... |
+---------------------------+

mysql> select STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s');
+---------------------------------------------------------+
| STR_TO_DATE('0000-00-00 00:00:00', '%Y-%m-%d %H:%i:%s') |
+---------------------------------------------------------+
| 0000-00-00 00:00:00                                     |
+---------------------------------------------------------+
```
