### ISSUE TITLE
Wrap all the data in tidb into a struct

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#166]
We should define a struct like:
type TidbData struct {
    Type *FieldType
    Value interface{} 
}
When doing string encode/decode/compare we need know charset/collation information. But we can not get this information at anywhere. For examples:
In cast/convert we do not known the current encoding. 
In compare, we do not known the collation for string (collation is used to decide case-sensitive of case-insensitive).

And with this struct, we could abandon mysql.Time mysql.Duration.

**Comment by siddontang** [comment]
Maybe we can refer MySQL supplying a total Item struct holding whole necessary things.

**Comment by coocood** [comment]
supported by Datum.
