### ISSUE TITLE
when `tidb_use_plan_baselines` is disabled, tidb-server should return a warning for `show bindings` statements

### ISSUE THREAD

**Issue by lzmhhh123** [pingcap/tidb#16608]
## Feature Request

**Is your feature request related to a problem? Please describe:**
It's strange for users when `tidb_use_plan_baselines` is false but `show bindings` has some bindings whose status is `using`.

**Describe the feature you'd like:**

We should return a warning to tell users "although the status of bindings is using, it doesn't affect any query plan".

**Comment by zz-jason** [comment]
@lzmhhh123 is it better to add a warning when `tidb_use_plan_baselines` is set to `false`?
