### ISSUE TITLE
Change TiDB's behavior by SetStatement

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1664]
We should find a way to control TiDB's behavior (such as parallel level, log level, binlog switch) without restart TiDB.
Using SetStatement may be the best way.

**Comment by coocood** [comment]
We can define some system variable, use them the same way as `autocommit`, `sql_mode` ...

**Comment by shenli** [comment]
It is a good idea. But if we sync data to MySQL through binlog, MySQL will reject unknown system variable. How could we handle this?

**Comment by ngaut** [comment]
Are you sure MySQL will reject unknown system variable ? if so we can create another "tidb-system-table"

**Comment by shenli** [comment]
➜  ~ mysql -uroot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.7.9 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SET SESSION sql_xxxx_mode = 'TRADITIONAL';
ERROR 1193 (HY000): Unknown system variable 'sql_xxxx_mode'
mysql>

**Comment by coocood** [comment]
@shenli We don't need to sync system variable through binlog.

This issue is duplicated to #1646
