### ISSUE TITLE
SQL binding should record how bindings are created.

### ISSUE THREAD

**Issue by lzmhhh123** [pingcap/tidb#16748]
## Feature Request

There are three ways to create bindings in TiDB.
1. create bindings by SQL like `create binding for ...`.
2. enable the `tidb_capture_plan_baselines`, then TiDB capture bindings automatically.
3. enable the `tidb_evolve_plan_baselines`, the TiDB evolve bindings to create new bindings.

We'd better have a field to distinguish these bindings by creating ways.

**Comment by ChenPeng2013** [comment]
verified on
master: v4.0.0-beta.2-632-g6c305e2a4
release-4.0: v4.0.0-66-gcf781a347
