### ISSUE TITLE
Mustn't check txn status with maxUint64 as callerStartTs

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#16778]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

| txn1 | txn2 |
| ----- | ----- |
| lock key1 and key2. Key1 is the primary key | |
| | point get key2 with maxUint64 as startTs |
| | meet the lock on key2 and check txn status with maxUint64 as callerStartTs |
| | the minCommitTs of txn1 is wrong(It overflows in TiKV) |

I also find analyze uses maxUint64 as startTs too. But it ignores locks and reads old data: https://github.com/pingcap/tidb/issues/16570. Is it intended?

### 2. What did you expect to see?
Point get in the autocommit transaction shouldn't use maxUint64 as startTs. It's useless in v4.0.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
v4.0

**Comment by jackysp** [comment]
`analyze` won't write something.

**Comment by AndreMouche** [comment]
I do not think so, if we meet a lock which is not primary, we should check the primary's status

**Comment by youjiali1995** [comment]
Solved by https://github.com/tikv/tikv/pull/7639
