### ISSUE TITLE
Does not support the config keyword field

### ISSUE THREAD

**Issue by pymjer** [pingcap/tidb#16804]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

> create table people(config varchar(1000));

### 2. What did you expect to see?
Query OK, 0 rows affected (0.16 sec)

### 3. What did you see instead?
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 26 near "config varchar(1000))"

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-rc
Git Commit Hash: 79db9e30ab8f98ac07c8ae55c66dfecc24b43d56
Git Branch: heads/refs/tags/v4.0.0-rc
UTC Build Time: 2020-04-08 07:32:25
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by qw4990** [comment]
@pymjer Thanks for your feedback. The reason is that `config` becomes a keyword of TiDB v4.0.x. I will fix this problem ASAP.

**Comment by qw4990** [comment]
Close due to resolved.
