### ISSUE TITLE
i would like to use it on windows,but the tidb server seems not support to run on windows.

### ISSUE THREAD

**Issue by mengpengfei** [pingcap/tidb#16833]
i would like to use it on windows,but the tidb server seems not support to run on windows.can you update the code to support windows,or what can i do to let tidb server to support windows?

**Comment by zz-jason** [comment]
Do you mean to build and develop tidb on Windows or to deploy a tidb cluster on Windows, run applications on that cluster?

**Comment by scsldb** [comment]
We are focused Linux platform and do not have the resource accommodate this requirement.
