### ISSUE TITLE
tikv-ctl in the tikv docker image

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb#16875]
It would be really convenient to have `tikv-ctl` in the tikv docker image so that you can just kubectl exec into the pod to run local tikv-ctl commands.

**Comment by tirsen** [comment]
For symmetry, pd-ctl is available in the pd image:
```/ # ls
bin        etc        lib        media      opt        pd-server  root       sbin       sys        usr
dev        home       lib64      mnt        pd-ctl     proc       run        srv        tmp        var
```

**Comment by zhangjinpeng1987** [comment]
@tirsen The new docker image(from v4.0.0) includes the tikv-ctl binary.
