### ISSUE TITLE
Show disk usage of a query in slow query and statement summary

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#16883]
## Description

1. Show disk usage of a query in slow query log and SLOW_QUERY table. (https://pingcap.com/docs/stable/how-to/maintain/identify-abnormal-queries/identify-slow-queries/)
2. Show disk usage of a query in statement summary table (https://pingcap.com/docs/stable/reference/performance/statement-summary/#statement-summary-tables)
## Score

* 50

## Mentor(s)

* @SunRunAway 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* skills 1
* skills 1

## Learning Materials

* [Slow qeury]https://pingcap.com/docs/stable/how-to/maintain/identify-abnormal-queries/identify-slow-queries/
* [Statement summary]https://pingcap.com/docs/stable/reference/performance/statement-summary/#statement-summary-tables
* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by mmyj** [comment]
pick

**Comment by SunRunAway** [comment]
@hidehalo You should pick this issue again.

**Comment by SunRunAway** [comment]
@hidehalo Would you like to create a documentation PR in pingcap/docs-cn?

**Comment by hidehalo** [comment]
@SunRunAway Yes, I'd like to. I need some guide.

**Comment by SunRunAway** [comment]
These two documents may need to be modified.
https://github.com/pingcap/docs-cn/blob/master/identify-slow-queries.md
https://github.com/pingcap/docs-cn/blob/master/statement-summary-tables.md

**Comment by hidehalo** [comment]
@SunRunAway Ok

**Comment by hidehalo** [comment]
> These two documents may need to be modified.
> https://github.com/pingcap/docs-cn/blob/master/identify-slow-queries.md
> https://github.com/pingcap/docs-cn/blob/master/statement-summary-tables.md

@SunRunAway Take a look please

https://github.com/pingcap/docs-cn/pull/3923
