### ISSUE TITLE
Support table-level/query-level replica read

### ISSUE THREAD

**Issue by 5kbpers** [pingcap/tidb#16893]
## Development Task

Add a table-level/query-level hint for indicating all the read requests of a table should always read from follower peers.

**Comment by 5kbpers** [comment]
@zz-jason @SunRunAway

**Comment by SunRunAway** [comment]
Should it be configurated in `placement-rules`? instead of a hint.

**Comment by nullnotnil** [comment]
I think the best way to do this is with: https://github.com/pingcap/tidb/issues/18672

If you can specify an `AS OF TIMESTAMP` for each table, and for the time use a helper function of `experimental_follower_read_timestamp()`, that would allow a replica read to be used.

**Comment by zz-jason** [comment]
@5kbpers do you mean to modify the `create table` schema of the specified table. without modifying the queries to that table?

**Comment by zz-jason** [comment]
I think a better solution is the local replica read described in https://github.com/pingcap/tidb/issues/18033.

**Comment by 5kbpers** [comment]
Sorry for the so late reply.😥 @SunRunAway @zz-jason @nullnotnil 

> I think a better solution is the local replica read described in #18033.

They are not exactly the same.
Sometimes we only want to use replica read on a part of tables or queries, we need some way to specify them explicitly.


> Should it be configurated in `placement-rules`? instead of a hint.

Surely this can address the requirement of table-level, but I think we also need a hint to support query-level.


> I think the best way to do this is with: #18672
> 
> If you can specify an `AS OF TIMESTAMP` for each table, and for the time use a helper function of `experimental_follower_read_timestamp()`, that would allow a replica read to be used.

Sounds great for the history read, but what about the realtime read which needs to get the latest data?

**Comment by nullnotnil** [comment]
> They are not exactly the same.
> Sometimes we only want to use replica read on a part of tables or queries, we need some way to specify them explicitly.

https://github.com/pingcap/tidb/issues/18672 supports this use-case:

```sql
SELECT * FROM old_table AS OF SYSTEM TIME '2005-04-04 09:30:00' INNER JOIN new_table ON ..
```

The `old_table` will have a different `SYSTEM TIME` to `new_table`.

> > If you can specify an `AS OF TIMESTAMP` for each table, and for the time use a helper function of `experimental_follower_read_timestamp()`, that would allow a replica read to be used.
> 
> Sounds great for the historical read, but what about the realtime read which needs to get the latest data?

That is the implicit default to provide ACID guarantees. I prefer the behavior that replicas are used automatically if the requested timestamp is far enough in the past that it's known to be correct for that timestamp.

**Comment by 5kbpers** [comment]
@nullnotnil Cool, that would be great if we could use replica read automatically.

**Comment by zz-jason** [comment]
> I prefer the behavior that replicas are used automatically if the requested timestamp is far enough in the past that it's known to be correct for that timestamp.

This is what we called local read (https://github.com/pingcap/tidb/issues/18033)

**Comment by zz-jason** [comment]
I think we can close this feature request because the following requests can cover the use cases of it:

1. https://github.com/pingcap/tidb/issues/18033 local replica read can provide the ability of automatically read from leader or follower based on the required staleness.
2. https://github.com/pingcap/tidb/issues/18748 the `set_var` query hint and `tidb_replica_read` variable together can provide query level replica read.

**Comment by zz-jason** [comment]
I'm going to close this feature request. Feel free to reopen it if the current solution can not fulfill the requirements.
