### ISSUE TITLE
use_cascades hint works incorrectly on partition table

### ISSUE THREAD

**Issue by Illyrix** [pingcap/tidb#16896]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

execute: 
```
create table t(id int not null auto_increment, col_int int not null, col_float float, primary key(id, col_int)) partition by range(col_int) (partition p0 values less than (100), partition pn values less than (MAXVALUE));
insert into t values(1, 10, 1), (101, 100, 101);

SELECT /*+ use_cascades(TRUE)*/ * from t;
```

### 2. What did you expect to see?

same result as normal select statement:
```
SELECT * from t;
+-----+---------+-----------+
| id  | col_int | col_float |
+-----+---------+-----------+
| 101 |     100 |       101 |
|   1 |      10 |         1 |
+-----+---------+-----------+
2 rows in set (0.00 sec)
```

### 3. What did you see instead?
```
SELECT /*+ use_cascades(TRUE)*/ * from t;
Empty set (0.00 sec)
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
5.7.25-TiDB-v4.0.0-beta.2-305-g94011e606

## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

**Comment by siddontang** [comment]
Great catch!!!

**Comment by francis0407** [comment]
This is because cascades planner is still under development. And partition table hasn't been supported yet.

**Comment by Defined2014** [comment]
Already fixed, close this issue.
