### ISSUE TITLE
failed to use insert ... duplicate key update

### ISSUE THREAD

**Issue by ozszsh** [pingcap/tidb#16908]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
use insert ... duplicate key update to batch insert or update values.
rows > 10k

### 3. What did you see instead?
failed to execute. It said "syntax error"

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
v3.0.13

**Comment by winoros** [comment]
@ozszsh Could you provide more information like the error stack in the log file when the error occurred?

**Comment by ozszsh** [comment]
Already fixed. Thx.
