### ISSUE TITLE
Ingore foreign key after parsing create table statement

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1691]
We do not support foreign key constraint now. We only parse it and store it in the meta data. When using mysqldump to dump database from TiDB. We output foreign key information. This may cause error when we do not output table in proper order.
I suggest that we should ignore foreign key  in TiDB. Just parse it and ignore it. 
@coocood @zimulala @tiancaiamao @hanfei1991 PTAL
/cc @ngaut @siddontang @zhangjinpeng1987

**Comment by morgo** [comment]
I am not sure that mysqldump reorders tables for foreign keys.  Instead, it always sets `SET FOREIGN_KEY_CHECKS=0` to allow restore in any order (most dumpers for mysql do this).

(Related) While there is dependency tracking in infoschema for Foreign keys, there was not for views and routines until MySQL 8.0.  See: https://dev.mysql.com/worklog/task/?id=11864  -- mysqldump is quite lose as a result.

**Comment by gregwebs** [comment]
It looks like this was implemented already as proposed. There is newer work on this issue already linked to this issue.
