### ISSUE TITLE
util: potential double lock in `Tracker.remove` if `rootExceed == t`

### ISSUE THREAD

**Issue by BurtonQin** [pingcap/tidb#16944]
### 1. What did you do?

Analyze the functions in util/memory/tracker.go.
Find a path that leads to double-lock.

The first lock is `t.mu.Lock()` in `remove()`. 
https://github.com/pingcap/tidb/blob/b0ce4131ce67c39a41d3d20df9d888fe9bc5a650/util/memory/tracker.go#L155-L163
Then `remove()` calls `t.Consume()`.
https://github.com/pingcap/tidb/blob/b0ce4131ce67c39a41d3d20df9d888fe9bc5a650/util/memory/tracker.go#L201-L205
```     
        var rootExceed *Tracker
	for tracker := t
        rootExceed = tracker
```
There is a path that leads to `rootExceed == t`.
If that is the case, `Action(rootExceed)` is equal to `Action(t)`.
https://github.com/pingcap/tidb/blob/b0ce4131ce67c39a41d3d20df9d888fe9bc5a650/util/memory/tracker.go#L221

Then `Action()` calls `t.String()`.
https://github.com/pingcap/tidb/blob/b0ce4131ce67c39a41d3d20df9d888fe9bc5a650/util/memory/action.go#L61

Then `t.toString()`.
https://github.com/pingcap/tidb/blob/b0ce4131ce67c39a41d3d20df9d888fe9bc5a650/util/memory/tracker.go#L252-L254

The second lock is `t.mu.Lock()` in `toString()`.
https://github.com/pingcap/tidb/blob/b0ce4131ce67c39a41d3d20df9d888fe9bc5a650/util/memory/tracker.go#L258-L265

### 2. What did you expect to see?
--

### 3. What did you see instead?
--

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master branch, commit b0ce4131ce67c39a41d3d20df9d888fe9bc5a650

**Comment by Yisaer** [comment]
I think the `Consume` in `remove`  shouldn't Exceed Action as the value is negative. What about creating a new Consume function which only for negative value. This function would do the same thing as `Consume` without checking exceeding.

**Comment by Yisaer** [comment]
If we choose to split Consume into 2 situations. Receiving positive value and non-postioive value. Maybe we should also check the value in the `Consume` function and explain the reason?
