### ISSUE TITLE
We can't execute `delete ... where colName ...` when the column is `DeleteOnly` state

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#16972]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?
```
create table t (a int, b int)
insert into t values(1,1);
```
Do the following:
| time  | connection1  |        connection2 |
|---|:---:|:---:|
| t1      |  drop column b|
|t2     |   column state (delete only) |  delete from where b=1;|

A similar issue is #15567.

### 2. What did you expect to see?
Return an error like `[planner:1054]Unknown column 'b' in 'where clause'`.

### 3. What did you see instead?
Statement executed successfully

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
Release Version: v4.0.0-beta.2-365-gfbea0b31f
Git Commit Hash: fbea0b31fc4bf60f5568085ef5ac0b780f402ccf
Git Branch: master

**Comment by jzdxeb** [comment]
why expect an error return? 
i think retrun successful is appropriate

**Comment by AilinKid** [comment]
> why expect an error return?
> i think retrun successful is appropriate

The deletion of known data associated by an invisible column does not meet the definition of the delete only state.

**Comment by tutulove1234** [comment]
> > why expect an error return?
> > i think retrun successful is appropriate
> 
> The deletion of known data associated by an invisible column does not meet the definition of the delete only state. (the invisible column is transparent to use)

那报错合适么？delete 的where条件携带了这个列，只需要将数据删除即可，报错不符合预期。不可读是针对与 select 的 where 。
