### ISSUE TITLE
ucp: Remove the default `asc` order in explain result

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#16974]
## Description

```mysql
mysql> desc select * from t order by b;
+-------------------------+----------+-----------+---------------+--------------------------------+
| id                      | estRows  | task      | access object | operator info                  |
+-------------------------+----------+-----------+---------------+--------------------------------+
| Sort_4                  | 10000.00 | root      |               | test.t.b:asc                   |
| └─TableReader_8         | 10000.00 | root      |               | data:TableFullScan_7           |
|   └─TableFullScan_7     | 10000.00 | cop[tikv] | table:t       | keep order:false, stats:pseudo |
+-------------------------+----------+-----------+---------------+--------------------------------+
3 rows in set (0.00 sec)
```

The order information `asc` in `Sort_4` is redundant and can be removed because we all know the default order is ascending.

Related places:
1. order by in select, like `select * from t order by a`
2. order by in group_concat, like `select group_concat(order by a) from t`
3. order by in window function, like `select lag(a,1) over (order by a asc) from t`
## Score

* 50

## Mentor(s)

* @SunRunAway

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* golang

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by ChenPeng2013** [comment]
verified on
master: v4.0.0-beta.2-576-g2a2c93bc6
