### ISSUE TITLE
I think the `DecodeInt` function in the *util/codec/number.go* may not works as it was expected

### ISSUE THREAD

**Issue by jjakj1** [pingcap/tidb#16985]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

I used the function in talent-plan path1 project1 to decode the number which was encoded before. However, I can not get the number I want.

### 2. What did you expect to see?

Here is a simple example

```golang
buf := make([]byte, 4)
buf = codec.EncodeInt(buf, 20)
buf, num, err := codec.DecodeInt(buf)
fmt.Println(buf, num, err)
```

I think the num I get are supposed to be `20`, and the buf should be 4 bytes and totally empty.

### 3. What did you see instead?

I actually get num = -9223372034707292160

First, I think the `DecodeCmpUintToInt` function is not right. It may need to be 

```golang
func DecodeCmpUintToInt (u uint64) int64 {
	return int64(u & ~signMask)
}
```

Also,  I think the slice we get in the `DecodeInt` function should be the last 8 bytes, not the highest 8 bytes.

```golang
func DecodeInt(b []byte) ([]byte, int64, error) {
	if len(b) < 8 {
		return nil, 0, errors.New("insufficient bytes to decode value")
	}

	u := binary.BigEndian.Uint64(b[len(b) - 8:])
	v := DecodeCmpUintToInt(u)
	b = b[:len(b)-8]
	return b, v, nil
}
```

Cause I'm totally new to golang and the talent-plan, if I misunderstood the usage of the function, I'm sorry for wasting your time. Looking forward to your replay.

**Comment by wjhuang2016** [comment]
Hi, @jjakj1 

I think you misunderstood the first argument of function `EncodeInt`.
The first argument is not the buffer but the data previously written in.
So the correct usage is:
```
bug := codec.EncodeInt(nil, 20)
buf, num, err := codec.DecodeInt(buf)
fmt.Println(buf, num, err)
```
Since we encode data one by one into `buf`, we should decode them one by one, so  `u := binary.BigEndian.Uint64(b[:8])` is correct.

**Comment by jjakj1** [comment]
Thank you for your reply. So that mean before I use `DecodeInt`, I need to ensure there isn't any prefix string before the number I added?

**Comment by wjhuang2016** [comment]
No, if you need to make sure the data is written by Encode(). And In your example, you create a buffer with 4 0x00 bytes, which is not valid.

**Comment by jjakj1** [comment]
Ok, thanks for all your assistant!!
