### ISSUE TITLE
the session variable of last_plan_from_cache can be affected by other connection

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#17019]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

prepared-plan-cache.enabled=true
[test code](https://gist.github.com/ChenPeng2013/2c15aaa752148e8ccf920c7b865d571f)

### 2. What did you expect to see?
```
last_plan_from_cache=1
```

### 3. What did you see instead?
```
last_plan_from_cache=0
```

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
```
Release Version: v4.0.0-beta.2-394-g5d74cf582
Git Commit Hash: 5d74cf582dab03d8c8c1783be66f927e47749700
Git Branch: master
UTC Build Time: 2020-05-06 02:23:09
GoVersion: go1.14.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by zz-jason** [comment]
@eurekaka PTAL

**Comment by eurekaka** [comment]
DDLs in the test code would increase schema version, so the key may be different when querying the cache, hence the `last_plan_from_cache` is `0`. This is not a problem, it works as expected, so close this issue.
