### ISSUE TITLE
Some function's collation information are covered by InferType4ControlFuncs

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#17063]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
create table t(a char, b char) collate utf8mb4_general_ci;
insert into t values("a", "b");
insert into t values("a", "B");
select * from t where if(a="x", a, b) = "b";
```

### 2. What did you expect to see?
Two lines.
### 3. What did you see instead?
Only one line.
### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master

**Comment by SunRunAway** [comment]
@qw4990 Please help triage this issue.
