### ISSUE TITLE
sql_mode: provide better prompt for sql execution errors caused by misuse of sql_mode

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb#17060]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When I run sqls and get errors caused by misuse of sql_mode
```
mysql> create table t (a DATE DEFAULT "00-00-00");
ERROR 1067 (42000): Invalid default value for 'a'
mysql> show warnings;
+-------+------+-------------------------------+
| Level | Code | Message                       |
+-------+------+-------------------------------+
| Error | 1067 | Invalid default value for 'a' |
+-------+------+-------------------------------+
1 row in set (0.01 sec)
```
It's hard to find out that it's caused by the misuse of sql_mode.

The results of mysql:
```
mysql> create table t (a DATE DEFAULT "00-00-00");
ERROR 1067 (42000): Invalid default value for 'a'
mysql> show warnings;
+-------+------+----------------------------------------------------------+
| Level | Code | Message                                                  |
+-------+------+----------------------------------------------------------+
| Error | 1292 | Incorrect date value: '00-00-00' for column 'a' at row 1 |
| Error | 1067 | Invalid default value for 'a'                            |
+-------+------+----------------------------------------------------------+
2 rows in set (0.02 sec)
```

**Describe the feature you'd like:**

Expect TiDB to provide better prompt for sql execution errors caused by misuse of sql_mode

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lichunzhu** [comment]
@bb7133 @zz-jason

**Comment by zz-jason** [comment]
I noticed that both TiDB and MySQL return `ERROR 1067 (42000): Invalid default value for 'a'`.

> Expect TiDB to provide better prompt for sql execution errors caused by misuse of sql_mode

Could you describe more about the expected behavior with some examples?

**Comment by lichunzhu** [comment]
It seems not easy for users think that there is a problem with `sql_mode` from the error message `ERROR 1067 (42000): Invalid default value for 'a'`.

**Comment by zz-jason** [comment]
It's hard to decide whether to improve this: if we modify the error message, it breaks the compatibility with MySQL.

@lichunzhu How about this. Since we are adding workarounds for the errors exposed to users in this project: https://github.com/pingcap/tidb/projects/55, maybe we can do it here.

**Comment by lichunzhu** [comment]
As long as users can get info to check `sql_mode`, it looks fine to me.

**Comment by zz-jason** [comment]
> It's hard to decide whether to improve this: if we modify the error message, it breaks the compatibility with MySQL.
> 
> @lichunzhu How about this. Since we are adding workarounds for the errors exposed to users in this project: [pingcap/tidb/projects/55](https://github.com/pingcap/tidb/projects/55), maybe we can do it here.

@IANTHEREAL How do you think?

**Comment by scsldb** [comment]
I suggest keeping with MySQL, because MySQL has more information and more clarity.
