### ISSUE TITLE
kubernetes helm deploy

### ISSUE THREAD

**Issue by yl-yue** [pingcap/tidb#17069]
## Feature Request

**Is your feature request related to a problem? Please describe:**
no

**Describe the feature you'd like:**
support kubernetes helm deploy and provide a quick experience version

**Comment by bb7133** [comment]
Hi @yl-yue , Looks that the [TiDB Operator](https://pingcap.com/docs-cn/tidb-in-kubernetes/stable/tidb-operator-overview/) exactly fit your needs, please check it.

**Comment by IANTHEREAL** [comment]
@yl-yue If you mean deploying tidb cluster on k8s, you can refer to tidb-operator document
English: https://docs.pingcap.com/tidb-in-kubernetes/stable
Chinese: https://docs.pingcap.com/zh/tidb-in-kubernetes/stable

I will close this issue, if you have any questions, feel free to reopen it
