### ISSUE TITLE
Support the functionality of `sql_select_limit`

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#17087]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, TiDB has the variable [`sql_select_limit`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_select_limit) but takes no effect.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by ahmedkrmn** [comment]
Hi Feng,
What do you suggest to start working on this?

**Comment by SunRunAway** [comment]
1. A global and session scope variable should be added in https://github.com/pingcap/tidb/blob/838de2ad26a1e494b7b7ed102004eaa3c5510fef/sessionctx/variable/sysvar.go#L627 and https://github.com/pingcap/tidb/blob/997b986387283d68713f50a3cdf5d44abbfccb5a/session/session.go#L1973
2. If the original plan is a select statement and has no _LIMIT_ Plan on top of it, handle this variable, and add a _LIMIT_ Plan  on top of the original plan in this [file](https://github.com/pingcap/tidb/blob/746c88a461aef16e043348cf1c8a96522f971928/planner/optimize.go)
3. The _EXECUTE_ statement should be considered carefully because the additional _Limit_ Plan should not be cached. Consider this case, 
```mysql
mysql> set session sql_select_limit = 2;
Query OK, 0 rows affected (0.00 sec)

mysql> prepare p1 from 'select * from t1';
Query OK, 0 rows affected (0.00 sec)
Statement prepared

mysql> EXECUTE p1;
+------+------+
| id   | sex  |
+------+------+
|    1 | F    |
|    2 | F    |
+------+------+
2 rows in set (0.01 sec)

mysql> set session sql_select_limit = 3;
Query OK, 0 rows affected (0.00 sec)

mysql> EXECUTE p1;
+------+------+
| id   | sex  |
+------+------+
|    1 | F    |
|    2 | F    |
|    3 | F    |
+------+------+
3 rows in set (0.00 sec)
```
