### ISSUE TITLE
UCP: print a log when setting global variable.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#17091]
## Description

```mysql
mysql> set session max_execution_time=0;
Query OK, 0 rows affected (0.00 sec)
```

tidb-server prints a log.

```
[2020/05/11 16:16:09.210 +08:00] [INFO] [set.go:207] ["set session var"] [conn=1] [name=max_execution_time] [val=0]
```

But, 
```mysql
set global max_execution_time=0;
```

tidb-server prints nothing in log.

## Score

* 50

## Mentor(s)

* @SunRunAway 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* skills 1
* skills 1

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by doggeral** [comment]
I'd like to work on the issue. Could you help to explain a little bit?
