### ISSUE TITLE
After launch, TiDB can only be connected from local machine, can not be connected from other machines.

### ISSUE THREAD

**Issue by haterbj** [pingcap/tidb#1709]
开始没有指定HOST地址，显示的是0.0.0.0:4000，本机可以连上服务，其它机器连不了
指定IP地址xx.xx.89.69后，其它机器还是没法通过MYSQL协议连上来，这是为何呢。
谢谢
[root@iZ256zv7z3dZ bin]# ./tidb-server -host xx.xx.89.69
2016/09/09 00:35:57 printer.go:30: [info] Welcome to the TiDB.
2016/09/09 00:35:57 printer.go:31: [info] Version:
2016/09/09 00:35:57 printer.go:32: [info] Git Commit Hash: d6f386926143d716c858111ba8c2691b303fea7a
2016/09/09 00:35:57 printer.go:33: [info] UTC Build Time:  2016-09-08 04:02:28
2016/09/09 00:35:57 kv.go:296: [info] [kv] New store /tmp/tidb 
2016/09/09 00:35:57 domain.go:94: [info] [ddl] loadInfoSchema 9
2016/09/09 00:35:57 domain.go:307: [info] [ddl] SetValidity, original:false current:true
2016/09/09 00:35:57 session.go:618: [info] RollbackTxn for session close. 
2016/09/09 00:35:57 server.go:146: [info] Server run MySql Protocol Listen at [xx.xx.89.69:4000]
2016/09/09 00:35:57 systime_mon.go:11: [info] start system time monitor 
2016/09/09 00:35:57 server.go:232: [info] Listening on :10080 for status and metrics report.

**Comment by shenli** [comment]
@haterbj Thanks for your report!
Which client do you use to connect to TiDB? May I have your connection URI or command line arguments? Is there any error log in TiDB when your connection failed?

**Comment by coocood** [comment]
@haterbj Please check your iptable status
```
service iptables status
```

**Comment by coocood** [comment]
@haterbj 
It has been many days since you report the issue, so I'll just close it, please reply if your issue still exists.
