### ISSUE TITLE
Dump memory status of all SQLs when server is consuming lots of memory

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#17095]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When `tidb-server` is killed by system oom-killer, we have no information to investigate which SQL is suspect that consumes unexpected memory and causes process down.

**Describe the feature you'd like:**

When a tidb-server is consuming most of the system memory(like 80% of system memory), `tidb-server` could automatically dump the memory status of all SQLs before system oom-killer kills tidb-server. The dumped status can help us investigate which SQL is suspect.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

We can implement this feature by adding a check inside the current expensive query handle, see https://github.com/pingcap/tidb/blob/8666a6f038a8e93686ac576884852e29b5faf660/util/expensivequery/expensivequery.go#L50

cc @zz-jason @siddontang

**Comment by zz-jason** [comment]
> We can implement this feature by adding a check inside the current expensive query handle

The expensive query is a query level validator. I think what you need is to monitor the memory usage of the process periodically, dump the memory profile and `show full processlists` once the memory in use exceeds a certain threshold.

@SunRunAway Am I correct?

**Comment by SunRunAway** [comment]
> > We can implement this feature by adding a check inside the current expensive query handle
> 
> 
> 
> The expensive query is a query level validator. I think what you need is to monitor the memory usage of the process periodically, dump the memory profile and `show full processlists` once the memory in use exceeds a certain threshold.
> 
> 
> 
> @SunRunAway Am I correct?

Yes. And this periodical checker logic can be stayed together with the existing preiodical checker which sniffs the expensive query.
