### ISSUE TITLE
Expression index returns `Cancelled DDL job` error

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#17111]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

```
mysql> create table t1 (a varchar(10), b varchar(10)) ;
Query OK, 0 rows affected (0.01 sec)
mysql> alter table t1 add unique index ei_ab ((concat(a, b)));
ERROR 8214 (HY000): Cancelled DDL job
```

### 2. What did you expect to see?

I'm not sure this statement is illegal or not, but TiDB should not throw a `Cancelled DDL job` error anyway.

### 3. What did you see instead?

Either no error or a better error message.

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)

master

commit 014d101a5d7fbd78f4bc306251181c01c0f01c7c
Author: Mingcong Han <hanmingcong123@hotmail.com>
Date:   Thu May 7 14:27:05 2020 +0800

**Comment by wjhuang2016** [comment]
Caused by https://github.com/pingcap/tidb/pull/16600
