### ISSUE TITLE
Potential bugs on old cores: using 64-bit functions sync/atomic

### ISSUE THREAD

**Issue by BurtonQin** [pingcap/tidb#17122]
### 1. What did you do?

I noticed that there are usages of atomic.LoadInt64, atomic.AddInt64, etc.
These 64-bit functions in sync/atomic can cause errors on old cores. Please see: https://golang.org/pkg/sync/atomic/#pkg-note-BUG
I am not sure if some users are running tidb on these old cores.

I reported this bug because I saw grpc-go developers viewed the usage of atomic64 functions as a bug and they easily fixed it in this [pull](https://github.com/grpc/grpc-go/pull/1411).
Maybe it is not a problem for tidb if users rarely use [those old cores](https://golang.org/pkg/sync/atomic/#pkg-note-BUG) mentioned by golang. Feel free to close this issue if you want.

Usage Position: (There may be more)
https://github.com/pingcap/tidb/blob/cf6c2107195d90ee83912b53d551b59530e5d85b/util/expensivequery/expensivequery.go#L51
https://github.com/pingcap/tidb/blob/cf6c2107195d90ee83912b53d551b59530e5d85b/util/expensivequery/expensivequery.go#L74

### 2. What did you expect to see?

--

### 3. What did you see instead?

--

### 4. What version of TiDB are you using? (`tidb-server -V` or run `select tidb_version();` on TiDB)
master branch,
commit: cf6c2107195d90ee83912b53d551b59530e5d85b

**Comment by fzhedu** [comment]
We do not see any bug resulted from this, so I close it.
