### ISSUE TITLE
enable agg push down union by default

### ISSUE THREAD

**Issue by lzmhhh123** [pingcap/tidb#17130]
## Feature Request

After tidb supports the partition table, we execute the query from the partition table by `union all` oparator. But aggregation push down optimization for `union all` is disabled by default. It's very unfriendly for users.

**Comment by lzmhhh123** [comment]
PTAL. @ilovesoup @zz-jason

**Comment by ilovesoup** [comment]
Or just make it pushdown for partition table's union instead of union in general. Might help to make things simple.
