### ISSUE TITLE
testSplitTable.TestShowTableRegion unit test is not stable

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#17189]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

Run CI  https://github.com/pingcap/tidb/pull/16706

### 2. What did you expect to see?

No error

### 3. What did you see instead?

```
----------------------------------------------------------------------
FAIL: executor_test.go:4247: testSplitTable.TestShowTableRegion

executor_test.go:4260:
    // Table t_regions should have 5 regions now.
    // 4 regions to store record data.
    // 1 region to store index data.
    c.Assert(len(rows), Equals, 5)
... obtained int = 6
... expected int = 5
```

This can be reproduce in the local environment, just run this several times:

```
cd executor
go test -check.f TestShowTableRegion
```

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
