### ISSUE TITLE
Init disk tracker of executors on demand

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#17237]
## Development Task

Currently, the disk tracker would be initialized for each query. If the Query doesn't use disk, we wouldn't initialize disk tracker and Attach to the Global Disk Tracker.

**Comment by SunRunAway** [comment]
I do not think this issue can be achieved. It's the executor's responsibility to decide whether to use the temporary disk during a SQL execution, so the initialization can not be omitted.

**Comment by Yisaer** [comment]
Currently, for each query, we will first initialize the sessionctx's disk tracker. Then, for each executor, we would initialize its distracker and attach to the sessionctx's disk tracker.

Whabt about initializing the sessionctx's disk tracker during executor's initializing. That is to say, we wouldn't initialize the sessionctx's disk tracker in `ResetContextOfStmt`, and for each executor's initializing, if the executor found that the seesionctx's disk tracker is nil, it would also initialize the sessionctx's disk tracker and attach its disk tracker to the sessionctx's disk tracker.

cc @SunRunAway

**Comment by SunRunAway** [comment]
@Yisaer I think what you described can work very well if we implement it carefully. But to introduce an example, we have an example `diskTrackerA` -> `diskTrackerB` -> `GlobalDiskTracker`, `diskTrackerA`, `diskTrackerB` and `GlobalDiskTracker` should check if exists and be initialized in sequence and exclusively if not exists when `diskTrackerA.Consume` called each time.
So I do not think it will give us much performance gain and we'd better keep code simple and readable.
