### ISSUE TITLE
ALTER USER USER()  IDENTIFIED BY PASSWORD do nothing

### ISSUE THREAD

**Issue by heidawei** [pingcap/tidb#17247]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
exec ALTER USER USER()  IDENTIFIED BY PASSWORD {new password};
>Query OK

but the user password do not charged.
search https://dev.mysql.com/doc/refman/5.7/en/alter-user.html 
we do not support IDENTIFIED BY PASSWORD, but the SQL can exec success.

### 1. Minimal reproduce step (Required)

![image](https://user-images.githubusercontent.com/11207613/82043780-c3329680-96de-11ea-8372-349e6685cce3.png)

### 3. Affected version (Required)
v3.0.5

**Comment by heidawei** [comment]
we exec the same SQL in mysql server.
![image](https://user-images.githubusercontent.com/11207613/82044364-cd08c980-96df-11ea-980a-da4013643938.png)
syntax error!!!!

**Comment by wjhuang2016** [comment]
Hi, @heidawei 
Could you give us some sql of false information?

**Comment by heidawei** [comment]
@wjhuang2016  can you reproduce the false?
I change the user password by "IDENTIFIED BY PASSWORD", the SQL result is "OK", but the password hasn't changed, In tiDB code, I see mysql 5.7 do not support "IDENTIFIED BY PASSWORD", and the same SQL on mySQL5.7 return syntax error.

**Comment by wjhuang2016** [comment]
HI, @heidawei 
I tested it and found that the password is changed, however, it's not equal to the specified password. Does this fit your description?

**Comment by heidawei** [comment]
@wjhuang2016  you test successful in tiDB **v3.0.5** with SQL "

> ALTER USER USER() IDENTIFIED BY PASSWORD {new password}

", I tested it several times and the password hasn't been changed。

**Comment by wjhuang2016** [comment]
Hi, @heidawei

How did you know that the password isn't changed?

**Comment by heidawei** [comment]
> select user, host,password ......

**Comment by wjhuang2016** [comment]
Hi, @heidawei 
`select password` will return the ciphertext instead of plaintext, it's normal to see that it's different from the setting plaintext.

**Comment by nullnotnil** [comment]
Here is a testcase against master:
```sql
SELECT user,authentication_string FROM mysql.user WHERE user='root';
ALTER USER USER() IDENTIFIED BY "*B50FBDB37F1256824274912F2A1CE648082C3F1F";
SELECT user,authentication_string FROM mysql.user WHERE user='root';
SET password="test";
SELECT user,authentication_string FROM mysql.user WHERE user='root';
..

mysql> SELECT user,authentication_string FROM mysql.user WHERE user='root';
+------+-----------------------+
| user | authentication_string |
+------+-----------------------+
| root |                       |
+------+-----------------------+
1 row in set (0.00 sec)

mysql> ALTER USER USER() IDENTIFIED BY "*B50FBDB37F1256824274912F2A1CE648082C3F1F";
ERROR 1396 (HY000): Operation ALTER USER failed for 'root'@'127.0.0.1'
mysql> SELECT user,authentication_string FROM mysql.user WHERE user='root';
+------+-----------------------+
| user | authentication_string |
+------+-----------------------+
| root |                       |
+------+-----------------------+
1 row in set (0.00 sec)

mysql> SET password="test";
Query OK, 0 rows affected (0.03 sec)

mysql> SELECT user,authentication_string FROM mysql.user WHERE user='root';
+------+-------------------------------------------+
| user | authentication_string                     |
+------+-------------------------------------------+
| root | *94BDCEBE19083CE2A1F959FD02F964C7AF4CFC29 |
+------+-------------------------------------------+
1 row in set (0.00 sec)
```

The `ALTER USER` and the `SET PASSWORD` should both change the authentication_string in the mysql.user table, except `ALTER USER` encounters a permission error. I am logged in as root.
