### ISSUE TITLE
Provide more details about this error: Unsupported add primary key, alter-primary-key is false

### ISSUE THREAD

**Issue by zhangysh1995** [pingcap/tidb#17270]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I got the following message:

````
ERROR 8200 (HY000) at line 17: Unsupported add primary key, alter-primary-key is false
````

When try to use:
````
ALTER TABLE tpch.region
ADD PRIMARY KEY (R_REGIONKEY);
````

I tried to set the variables, which didn't work:
````
mysql> set alter-primary-key=true;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 9 near "alter-primary-key=true" 
mysql> set global alter-primary-key=true;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 16 near "alter-primary-key=true" 
````

Then I searched online and found the link to the [documentation](https://pingcap.com/docs/stable/tidb-configuration-file/#alter-primary-key).

**Describe the feature you'd like:**

It should report something like this:
````
ERROR 8200 (HY000) at line 17: Unsupported add primary key, alter-primary-key is false. Please check the documentation for the tidb-server configuration file
````

**Describe alternatives you've considered:**

````
ERROR 8200 (HY000) at line 17: Unsupported add primary key, alter-primary-key is false. Please check <some urls>
````

**Teachability, Documentation, Adoption, Migration Strategy:**

This is originally provided by MySQL. The doc is [here](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html).

**Comment by wjhuang2016** [comment]
@zimulala PTAL

**Comment by zimulala** [comment]
@zhangysh1995 
Thanks for your feedback! We will improve and unify the error information of TiDB in the near future.

**Comment by Abingcbc** [comment]
@zimulala @tangenta I would like to take this issue. 
Is there a standard for error messages? How about the message mentioned above `ERROR 8200 (HY000): Unsupported add primary key, alter-primary-key is false. Please check https://docs.pingcap.com/tidb/stable/tidb-configuration-file` ?

Thanks!

**Comment by tangenta** [comment]
@Abingcbc Sorry for the late reply. 

There is no standard about the error message. Let's set it to
```
Please check the documentation for the tidb-server configuration file
```
