### ISSUE TITLE
fail to upgrade from v4.0.0-rc1 to rc2

### ISSUE THREAD

**Issue by beanww** [pingcap/tidb#17299]
dc01 ~]$tiup cluster upgrade bbb v4.0.0-rc.2
Starting component `cluster`: /bbb/.tiup/components/cluster/v0.6.2/cluster upgrade lcqb v4.0.0-rc.2
+ [ Serial ] - SSHKeySet: privateKey=/bbb/.tiup/storage/cluster/clusters/bbb/ssh/id_rsa, publicKey=/bbb/.tiup/storage/cluster/clusters/bbb/ssh/id_rsa.pub
+ [Parallel] - UserSSH: user=tidb, host=dc01
+ [Parallel] - UserSSH: user=tidb, host=dc06
+ [Parallel] - UserSSH: user=tidb, host=dc02
+ [Parallel] - UserSSH: user=tidb, host=dc01
+ [Parallel] - UserSSH: user=tidb, host=dc01
+ [Parallel] - UserSSH: user=tidb, host=dc03
+ [Parallel] - UserSSH: user=tidb, host=dc01
+ [Parallel] - UserSSH: user=tidb, host=dc02
+ [Parallel] - UserSSH: user=tidb, host=dc02
+ [Parallel] - UserSSH: user=tidb, host=dc06
+ [Parallel] - UserSSH: user=tidb, host=dc05
+ [Parallel] - UserSSH: user=tidb, host=dc05
+ [Parallel] - UserSSH: user=tidb, host=dc03
+ [Parallel] - UserSSH: user=tidb, host=dc01
+ [ Serial ] - Download: component=alertmanager, version=v0.17.0, os=linux, arch=amd64
+ [ Serial ] - Download: component=prometheus, version=v4.0.0-rc.2, os=linux, arch=amd64
+ [ Serial ] - Download: component=tikv, version=v4.0.0-rc.2, os=linux, arch=amd64
+ [ Serial ] - Download: component=grafana, version=v4.0.0-rc.2, os=linux, arch=amd64
+ [ Serial ] - Download: component=pd, version=v4.0.0-rc.2, os=linux, arch=amd64
+ [ Serial ] - Download: component=tidb, version=v4.0.0-rc.2, os=linux, arch=amd64

Error: rename /tmp/tiup-cluster/pd-v4.0.0-rc.2-linux-amd64.tar.gz /bbb/.tiup/storage/cluster/packages/pd-v4.0.0-rc.2-linux-amd64.tar.gz: invalid cross-device link

Verbose debug logs has been written to /home/policeyg/logs/tiup-cluster-debug-2020-05-19-21-03-17.log.
Error: run `/bbb/.tiup/components/cluster/v0.6.2/cluster` (wd:/bbb/.tiup/data/RzRGfCo) failed: exit status 1

Is this a bug? rename need change to mv?

**Comment by wjhuang2016** [comment]
@lonng  PTAL

**Comment by lonng** [comment]
@beanww please force update cluster component via
```
tiup update cluster --force
```

**Comment by beanww** [comment]
I have destroyed cluster and redeloy v4.0.0-rc.2 directly, it works.
