### ISSUE TITLE
create key partition table panic

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#17323]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t(a char(5), unique key(a(5))) partition by key() partitions 5;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

Lost connection

### 4. Affected version (Required)

4.0

### 5. Root Cause Analysis

Null pointer reference in `checkPartitioningKeysConstraints` function.

**Comment by wjhuang2016** [comment]
Close by https://github.com/pingcap/tidb/pull/17242
