### ISSUE TITLE
count agg's type infer for decimal property is inaccurate

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#17367]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

use MySQL client connect tidb with `--column-type-info`

execute `select count(1) from t`; (t can be any table have data)

### 2. What did you expect to see? (Required)

```
Field   1:  `count(1)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     21
Max_length: 1
Decimals:   0
Flags:      NOT_NULL BINARY NUM 


+----------+
| count(1) |
+----------+
|        2 |
+----------+
1 row in set (0.014 sec)
```

### 3. What did you see instead (Required)

```
MySQL [test]> select count(1) from tt;
Field   1:  `count(1)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       LONGLONG
Collation:  binary (63)
Length:     21
Max_length: 1
Decimals:   31
Flags:      NOT_NULL BINARY NUM 


+----------+
| count(1) |
+----------+
|        2 |
+----------+
1 row in set (0.003 sec)
```

### 4. Affected version (Required)

4.0 and master

### 5. Root Cause Analysis

count agg's type infer for decimal property is unaccurate

**Comment by ChenPeng2013** [comment]
verified on
master: v4.0.0-beta.2-779-g9e5e2a933
release-4.0: v4.0.2-45-gb4da443a3
release-3.1: v3.1.2-56-g9a1cc53d1
release-3.0: v3.0.16-4-g338a0bd90
