### ISSUE TITLE
Q3, Q17 and Q18 of TPCH sometimes met "ERROR 1105 (HY000): Out Of Memory Quota!" using TiKV isolated reading

### ISSUE THREAD

**Issue by shuke987** [pingcap/tidb#17360]
[all-tidb.log](https://github.com/pingcap/tidb/files/4667056/all-tidb.log)
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Deploy TiDB on AWS with 32GB memory VM.
Run TPCH with TiKV isolation read.
Q3, Q17 and Q18 of TPCH sometimes met "ERROR 1105 (HY000): Out Of Memory Quota!"

### 2. What did you expect to see? (Required)
Query finished without error.

### 3. What did you see instead (Required)
Error 1105

### 4. Affected version (Required)

4.0.0-rc.1

**Comment by fzhedu** [comment]
what is the scale factor of TPCH?
what is the Memory Quota of a query, which is 1 GB by default, you may need to increase it.

**Comment by XuHuaiyu** [comment]
I checked the log:
```
...\"mem-quota-query\":1073741824,\"tmp-storage-quota\":-1...
```

The memory usage is limited to 1GB, thus the error happened.

**Comment by XuHuaiyu** [comment]
Not a bug, I'll remove the bug label and close this issue.
