### ISSUE TITLE
Add a transaction mode label for certain transaction metrics

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#17377]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It is not easy to distinguish the workload transaction mode in Grafana.

**Describe the feature you'd like:**

Add a transaction mode label for certain transaction metrics to distinguish between pessimistic and optimistic transactions.

**Describe alternatives you've considered:**

It is better to add the label in TPS, Transaction Write Byte Size...

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by qrr1995** [comment]
jira-sync test comment

**Comment by jackysp** [comment]
I'll do it myself.
