### ISSUE TITLE
Why create index soo slow?

### ISSUE THREAD

**Issue by beanww** [pingcap/tidb#17434]
What's the normal speed of create index? (eg. 6kv  per 4c/128G/2TB-nvme / 10gb net)

We have imported about 400,000,000 records with lightning，
And after that,  we began to create index on this table,  this job has during 17 hours, but only 
30,000,000 rows created with command admin show ddl jobs, Is it unnormal?

**Comment by wwar** [comment]
See also: https://github.com/pingcap/tidb/issues/14454

It has gotten better recently, but add index performance is often still slower than reloading the data from scratch.

**Comment by beanww** [comment]
I have done this before create this index, It's still slow:
SET GLOBAL tidb_ddl_reorg_batch_size = 10240;
SET GLOBAL tidb_ddl_reorg_worker_cnt = 100;

attachment is the diagnose report, It seams 192.168.2.106 is very busy, anything help?thanks!
[TiDB Dashboard Diagnosis Report_files.zip](https://github.com/pingcap/tidb/files/4706790/TiDB.Dashboard.Diagnosis.Report_files.zip)

**Comment by bb7133** [comment]
Thanks for reporting! @tangenta Would you please take a look?

**Comment by beanww** [comment]
After a week's working, 
'admin show ddl jobs ' show the state of this job becomes 'rollback done'.
Can I  create a new empty table with index,  and batch import data with insert into ..select ...  or lightning, and rename this new table back? 
Any advice for creating index of big table,  create index first or import data first? thans alot!

**Comment by tangenta** [comment]
@beanww Importing data with `insert into ... select` is slower than creating index directly because it runs sequentially. Could you provide the log when running `create index`?

**Comment by beanww** [comment]
How to get the create index log?
any clue from the diagnose report?thx!

**Comment by tangenta** [comment]
@beanww If you are using TiDB Dashboard, it should be convenient to download the logs in the panel 'Search Logs'. 
It is recommended to set `tidb_ddl_reorg_worker_cnt` to a smaller value if there are concurrent updates to the same table.

**Comment by beanww** [comment]
[logs-createindexslow.zip](https://github.com/pingcap/tidb/files/4733419/logs-createindexslow.zip)
I have attached warning+ logs from dashboard with time condition is the time when beginning create index to 10 minute later, please check, thanks!

BTW, we have created index for another big table(400,000,000), the speed is normal: about 4 hours, the difference between 2 tables is the row size of issue table is much larger (about 10 times)than no issue table, that's all.

**Comment by beanww** [comment]
THIS ISSUE IS FIXED! 
We found the reason is WRONG configuration lead to this issue, You can found from diagnose report:

storage.block-cache.capacity | 32

We lost 'GB' unit in deployment yml,  just set the value 32,  
And after change 32 to 32GB, the performance is great,
the usetime of creating index for 400,000,000 big table, is only 30min!

this wrong config leads to TiKV's memory usage only max to about 4GB per kv instance(I dont know why 32 leadto 4GB, not 32KB?....), now is 32GB, memory resources is not idle now.

**Comment by tangenta** [comment]
I didn't notice this configuration...

Anyway, we should make some improvements to these problems. For example, the unit must be specified. @bb7133

**Comment by tangenta** [comment]
The usability issue has been tracked in #17847.

@beanww Thanks for reporting! Let's close this since it is not a problem anymore.
