### ISSUE TITLE
The extracted TopN(most common values) doesn't take effect as we expected.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#17467]
## Development Task

There's a rare probability that Count-Min Sketch would meet the collision that a small value totally collides a big value. And the estimation of the small value will be close to the big value, leading TiDB to choose a sub-optimal plan.

We introduced the TopN to avoid this. But the TopN currently is extracted from the histograms whose bucket haven't store its own NDV(number of distinct value) yet. So it's very likely that the histogram cannot find the real TopN values(since it calculate the appearance of each value by the independent assumption).

We need to use another way to store the TopN, to avoid the hash collision problem of cm sketch.

**Comment by zz-jason** [comment]
We need more tests to ensure correctness.

**Comment by winoros** [comment]
The new version has corrected it. But since it's not opened by default. Still mark it as opening.

**Comment by winoros** [comment]
New stats is opened as default. Closed this issue.
