### ISSUE TITLE
Flag to not print arguments in slowlog

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb#17463]
We would like a flag that disables the printing of argument values in the slowlog. Only the query should be printed.

**Comment by bb7133** [comment]
Hi @tirsen , thanks for this request!

We used to have the plan that treats this as part of the Data Masking, however, the latter one is something big.

Now we're going to provide a system variable like `tidb_slow_log_no_arguments' and behave exactly what you described.

This feature will be added in 4.0.2, thanks!
