### ISSUE TITLE
"failed to load schema diff" cause full schema load

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#17477]
## Development Task

I see the following log during I play with https://github.com/pingcap/tidb/pull/17149

```
alter table pt partition p0 exchange with table nt;
```

> [2020/05/28 11:30:14.142 +08:00] [ERROR] [domain.go:122] ["failed to load schema diff"] [error="[schema:1146]Table '(Schema ID 1).(Table ID 3995)' doesn't exist"]
> [2020/05/28 11:30:14.191 +08:00] [INFO] [domain.go:143] ["full load InfoSchema success"] [usedSchemaVersion=486] [neededSchemaVersion=487] ["start time"=48.457978ms]

If the schema change diff contains some unknown type of DDL operation type (such as alter table exchange partition), then the ApplyDiff would fail and full load InfoSchema is called.

I'm not sure that's the cause, or maybe the encoding of some meta key is wrong (see the error message).

**CAUTIONNNNNNNNNNNN**: Full load schema is heavy and has potential problems:
1. consume too much memory and may lead to OOM
2. takes too long and cause the whole TiDB unavailable

**Comment by zimulala** [comment]
This is not due to unknown DDL, but because `ApplyDiff` did not get the correct updates in this #17149, I [comment](https://github.com/pingcap/tidb/pull/17149/files#r433028457) it.

**Comment by tiancaiamao** [comment]
Er... I haven't investigate the details

>  I'm not sure that's the cause

Thank you for pointing out the root cause. @zimulala

**Comment by tiancaiamao** [comment]
Exchange partition is merged, and this problem does not exist in the master
