### ISSUE TITLE
Error message not formatted

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#17489]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
select 888888888888888888888888888888888888888888888888888888888888888888888888888888888888;
```

### 2. What did you expect to see? (Required)

Formatted error message.

### 3. What did you see instead (Required)

```
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 91 near "888888888888888888888888888888888888888888888888888888888888888888888888888888888888"
decimal literal: [types:1690]%s value is out of range in '%s'
```

### 4. Affected version (Required)

```
Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

**Comment by zhangysh1995** [comment]
I found a related issue last week, check (here)[https://github.com/tidb-challenge-program/bug-hunting-issue/issues/83]
