### ISSUE TITLE
Could TiDB provide index use view or table

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17508]
## Feature Request

**Describe the feature you'd like:**

Could TiDB provide index usage view or table? Such as MySQL The [`schema_unused_indexes`](https://dev.mysql.com/doc/refman/5.7/en/sys-schema-unused-indexes.html) view function:

> These views display indexes for which there are no events, which indicates that they are not being used. By default, rows are sorted by schema and table.
>
> This view is most useful when the server has been up and processing long enough that its workload is representative. Otherwise, presence of an index in this view may not be meaningful.

Users can drop unused indexes to reduce storage space consumption.

From AskTUG: https://asktug.com/t/topic/34614/12

**Describe alternatives you've considered:**

N/A

**Comment by zz-jason** [comment]
I'm going to close it since it's duplicated and lack of discussion. Let's track the issue and discuss it here: https://github.com/pingcap/tidb/issues/14607
