### ISSUE TITLE
Could support resource isolation in multi-instance deployment

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17511]
## Feature Request
**Describe the feature you'd like:**
Could support resource isolation in multi-instance deployment

**Describe alternatives you've considered:**
Different instance will not impact each other

https://asktug.com/t/topic/34614/15

**Comment by zhangjinpeng1987** [comment]
https://github.com/pingcap/docs-cn/pull/3612 can relieve the isolation issue.
