### ISSUE TITLE
slow log auto delete

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17518]
## Feature Request

**Describe the feature you'd like:**
slow log auto delete

**Describe alternatives you've considered:**
decrease hardware space use

https://asktug.com/t/topic/34614/20

**Comment by zz-jason** [comment]
@yilongrong Would it helpful to rotate the slow log automatically, leave the log remove operation to the user?

**Comment by yilongrong** [comment]
yes, It will useful.  but different user maybe have different requirement .  maybe we could use one parameter control the slow log max size?

**Comment by zz-jason** [comment]
@yilongrong Let's make the user story clearer. If the user wants to clear the stale slow log periodically, the best rotate strategy is based on the date, not size. Am I correct?

**Comment by scsldb** [comment]
Keep two strategies (date and size) to give users choices that might be a little better.

**Comment by Defined2014** [comment]
Slow log already supports rotate by size. The requirements have been basically met and the issue has no further discussion a lot of time. So close it.
