### ISSUE TITLE
partion table  no need use partition key 

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17517]
## Feature Request

**Describe the feature you'd like:**
Partion table  no need use partition key , like Oralce partition table

**Describe alternatives you've considered:**
easy to use partition table 

https://asktug.com/t/topic/34614/9

**Comment by zz-jason** [comment]
@yilongrong Sorry I'm confused about the request description. Could you describe in more detail with some examples, or could you provide the oracle user document link about the requested feature?

**Comment by yilongrong** [comment]
wait customer feedback
