### ISSUE TITLE
Stability improvement

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17520]
## Feature Request

**Describe the feature you'd like:**
Stability improvement:
Region physical isolation: splitting, merging, and scheduling require scanning keys to achieve performance cost
Indistinguishable MVCC: read and write amplification, lower performance, GC will bring performance jitter
Compaction: performance jitter
Hotspots: Reduce the impact of hotspots on the system (barrel effect, our current barrel short board is too low)
Fault isolation: The breakdown of a component should theoretically not affect the services of the entire cluster (such as PD switching Leader, which will cause QPS to fall temporarily)

**Describe alternatives you've considered:**

Stability improvement 

https://asktug.com/t/topic/34614/24

**Comment by scsldb** [comment]
New issue has been suggested, see https://github.com/pingcap/tidb/issues/18005
