### ISSUE TITLE
Support Changing Column Types

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17526]
### Description

Support changing column types. Tasklist:

- [x] P0: https://github.com/pingcap/tidb/issues/18261 Support Changing Column Type in the TiFlash Side
- [x] P0: https://github.com/pingcap/tidb/issues/18283 Support Changing Column Type in the TiDB Side

### Category

Feature

### Value

* Changing column type is a basic function of the database, many inconveniences are brought to our users and DBAs from TiDB without full support.
* The user experience of syncing data from MySQL to TiDB with DM is usually very poor, lot's of column type changing DDL statements needed to be specifically handled.

### Join Us
Weekly Report: [TiDB v5.0 Project Management Weekly Report - Column Type Changes](https://docs.google.com/document/d/10MXVdI2J_9hHhYL9ubTkzCDytgY3YhRXrJSECoyoZRY/edit#heading=h.4djbdyo32xia)

**Comment by bb7133** [comment]
Sure, I believe that the 'column type change' feature is in the roadmap of v5.0

**Comment by zimulala** [comment]
You can see the link(https://github.com/pingcap/tidb/projects/66) to support the progress of changing column types on the TIDB side.
