### ISSUE TITLE
Could TiDB support  migrate from monogdb

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#17527]
## Feature Request

**Describe the feature you'd like:**
Could TiDB support migrate from monogdb:
support full and incremental migrate 

**Describe alternatives you've considered:**
easy migrate  from monogdb to tidb

https://asktug.com/t/topic/34614/27

**Comment by scsldb** [comment]
There are no plans in the short term, thank you.

**Comment by scsldb** [comment]
Short to medium term aggregation on relational databases, no plans yet.

**Comment by zz-jason** [comment]
It's glad to see this feature request! But at present, we are focused on the relational databases, there isn't a plan to support NoSQL features. Due to the longterm product roadmap, this feature request is rejected and closed. Thanks anyway.
