### ISSUE TITLE
Support Alter Table Modify statement

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#1753]
See: http://dev.mysql.com/doc/refman/5.7/en/alter-table.html
When there is some data in a table. It is better to use modify than drop+add to change the type of existing columns.

**Comment by catroot** [comment]
> ALTER TABLE `person` MODIFY `id` INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY;
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/ddl/ddl_api.go:1129: [ddl:203]unsupported modify column constraint - 1

Some clues?

**Comment by jackysp** [comment]
Hi @catroot , TiDB has some limitations on primary key, please see this document https://github.com/pingcap/docs/blob/master/sql/ddl.md#alter-table-syntax for details.
