### ISSUE TITLE
Log cpu time of a SQL in slow query log and statement summary

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#17559]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It's nice to have CPU usage in slow query log and statement summary, especially collect the CPU usage in TiDB side and TiKV(TiFlash) side.

**Describe the feature you'd like:**

We can add an option to enable CPU time recording in a time window configured by the user. In such a time window, the CPU time of all SQLs can be recorded.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

1. TiDB side, maybe [pprof.WithLabel](https://golang.org/pkg/runtime/pprof/#WithLabels) can help.
2. TiKV side, we need to find a way

**Comment by SunRunAway** [comment]
Better to show them in `show processlist`

**Comment by johnhaxx7** [comment]
Hi @SunRunAway, is this still open and need help?

**Comment by SunRunAway** [comment]
We have [Top SQL](https://docs.pingcap.com/tidb/stable/top-sql) now.
I think this issue can be closed.
