### ISSUE TITLE
Revise the Configuration for SimpleLRUCache

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#17567]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In my view, some configurations for `SimpleLRUCache` is misleading and some are over-designed.

For `max-memory`, the description in our [document](https://pingcap.com/docs/stable/tidb-configuration-file/#max-memory) misleads and may let user to think  `max-memory` is only for managing `SimpleLRUCache` memory usage.

However, in our [config.example.toml](https://github.com/pingcap/tidb/blob/7b2d79c38948c7c7f4767c7135f8360557220411/config/config.toml.example#L200), `max-memory` is described as the memory quota for a single tidb-server. And in https://github.com/pingcap/tidb/pull/16777 , and we also let `max-memory` to control the memory quota as a tidb-server. The difference between the usage and description for `max-memory` may make user confusion.

https://github.com/pingcap/tidb/issues/17298 also pointed out this.

Also, as `GlobalLRUMemUsageTracker` introduced in https://github.com/pingcap/tidb/pull/16777 , I think the `memory-guard-ratio` is no longer needed and `Capacity` is enough for the elimination strategy.

**Describe the feature you'd like:**

To remove the misleading and unnecessary configuration, I think we can

1. introduce a new configuration like `server-memory-quota` for the memory quota for a single tidb-server.  https://github.com/pingcap/tidb/pull/17532
2. Fix the annotation in tidb.toml.example and tell the readers that max-memory is only for Plan Cache in tidb.toml.example in all release branches(v2.1, v3.0, v3.1, v4.0)
3. marked `max-memory` after v4.0

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
Hi @dbjoa, from the description above, we are going to abandon `memory-guard-ratio` in the config file, what's your opinion?

**Comment by dbjoa** [comment]
Hi @zz-jason,
I agree with you if we can control the memory usage of `plan cache` as we done so far.

**Comment by SunRunAway** [comment]
> 4. remain capacity strategy and removed the memory ratio strategy in SimpleLRUCache.

IMO, the memory ratio strategy should be kept for compatibility of the upgraded server.

**Comment by Yisaer** [comment]
> > 1. remain capacity strategy and removed the memory ratio strategy in SimpleLRUCache.
> 
> IMO, the memory ratio strategy should be kept (but disabled by default) for compatibility of the upgraded server.

It's ok for me.

**Comment by fzhedu** [comment]
We should set different memory pool: server memory = plan memory + executor memory + cache memory + othres, similar to MySQL, Oracle and others.

**Comment by Yisaer** [comment]
After discuss with @SunRunAway , we decide still remain `memory-guard-ration` and use `server-mem-quota` as its quota instead of `max-memory`
