### ISSUE TITLE
Reduce the memory usage of large transaction

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#17574]
## Development Task
Now the memory amplification is about 5 times the data size, e.g., a 10GB size transaction will consume about 50GB memory, we need to optimize it.

**Comment by jackysp** [comment]
I think it could help. https://github.com/pingcap/tidb/pull/15480

**Comment by tiancaiamao** [comment]
Link https://github.com/pingcap/tidb/issues/17479

**Comment by zhangjinpeng1987** [comment]
@youjiali1995 The issue description is too simple to see what you want to do exactly because there are many things that can do to reduce the large transaction's memory usage.

**Comment by zhangjinpeng1987** [comment]
I think this issue is duplicated with https://github.com/pingcap/tidb/issues/17479, so close it.
