### ISSUE TITLE
Disconnect then reconnect to DB, the SEQUENCE "SELECT lastval();" return null

### ISSUE THREAD

**Issue by GhostChild** [pingcap/tidb#17586]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

step1. connect to Database
step2.create a SEQUENCE (CREATE SEQUENCE seq_test1 start 1 increment 1 NOCACHE;)
step3 SELECT nextval(seq_test1); 
step4 disconnect DB
step5 connect to DB
step6 SELECT lastval(seq_test1); 

![image](https://user-images.githubusercontent.com/22742106/83494648-2b5be780-a4e9-11ea-98f4-35ef7f25a197.png)

renonnect to DB must be run nextval(); //SELECT nextval(seq_test1);
then the nextval() will be return right.

### 2. What did you expect to see? (Required)
![image](https://user-images.githubusercontent.com/22742106/83495375-2d727600-a4ea-11ea-8069-9127565ae0f2.png)

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/22742106/83494648-2b5be780-a4e9-11ea-98f4-35ef7f25a197.png)

### 4. Affected version (Required)

Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by nullnotnil** [comment]
I believe this behavior is intended. From the [MariaDB docs](https://mariadb.com/kb/en/previous-value-for-sequence_name/):

> If the sequence has not yet been used by the connection, PREVIOUS VALUE FOR returns NULL (same thing applies when the server is restarted, a new connection doesn't see a last value for an existing sequence).

i.e. `lastval()` is a function of session scope. Here is a pasteable testcase to confirm as well:
```sql
DROP SEQUENCE IF EXISTS seq_test1;
CREATE SEQUENCE seq_test1 start 1 increment 1 NOCACHE;
SELECT nextval(seq_test1);
SELECT lastval(seq_test1);
..
# in a new session
SELECT lastval(seq_test1);
```

**Comment by AilinKid** [comment]
The `lastval` is implemented as a map in the session scope. 
new session / reconnecting / haven't filled the map will get NULL value when you try to get `lastval` function.

**Comment by AilinKid** [comment]
PTAL @nullnotnil @GhostChild  Closing issue suggested
