### ISSUE TITLE
`drop tables t1, t2, t3` is valid for mysql  

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#176]
I am very surprised that MySQL supports `drop tables` but I don't find any reference about the "s"  in http://dev.mysql.com/doc/refman/5.7/en/drop-table.html.

@shenli

**Comment by shenli** [comment]
Maybe this is an old syntax not mentioned in new doc.

**Comment by qiuyesuifeng** [comment]
I think support `drop table t1, t2, t3` is enough.
