### ISSUE TITLE
Some string value can't insert to the column of SET type

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#17634]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t8(a set('a', ' ')) charset utf8 collate utf8_general_ci;
tidb> insert into t8 values ('a ');
ERROR 1105 (HY000): cannot convert datum from char to type set.
```

Also with enum type.

### 2. What did you expect to see? (Required)
insert successfully.

**Comment by ChenPeng2013** [comment]
verified on
master: v4.0.0-beta.2-779-g9e5e2a933
release-4.0: v4.0.2-45-gb4da443a3
