### ISSUE TITLE
How to change values of GLOBAL VARIABLES like 'tidb_replica_read'

### ISSUE THREAD

**Issue by rachitmanit** [pingcap/tidb#17650]
## General Question
Regarding running standard benchmark on test TiDB cluster setup.
I was going through follower read: https://pingcap.com/docs/dev/follower-read/ to get optimised read latencies.

Variable **tidb_replica_read** is a SESSION variable which needs to be set once. Requirement is to change its default value to **follower**.
Is there some way to change its default value using configuration?
Want information regarding how to change MySQL **my.cnf** file like changes in TiDB

```
mysql> set @@global.tidb_replica_read='follower';
ERROR 1105 (HY000): Variable 'tidb_replica_read' is a SESSION variable and can't be used with SET GLOBAL 
```

**Comment by qw4990** [comment]
@overvenus @disksing PTAL

**Comment by qw4990** [comment]
@lysu PTAL

**Comment by SunRunAway** [comment]
I think making ** tidb_replica_read** in the global scope is reasonable.

**Comment by SunRunAway** [comment]
@rachitmanit Would you like to send a pull request?
