### ISSUE TITLE
tablecodec.DecodeIndexKey parse failed if key contains null value

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#17662]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
[`tablecodec.DecodeIndexKey`](https://github.com/pingcap/tidb/blob/e85b2c5166c385d0eddd3b125cac14b41431411a/tablecodec/tablecodec.go#L136-L159) will return error  if input index key contains null value.
example Input: 「74800000000000042f5f69800000000000000100038000000000000001」
```
$ mok 74800000000000042f5f69800000000000000100038000000000000001
"74800000000000042f5f69800000000000000100038000000000000001"
└─## decode hex key
  └─"t\200\000\000\000\000\000\004/_i\200\000\000\000\000\000\000\001\000\003\200\000\000\000\000\000\000\001"
    └─## table index key
      ├─table: 1071
      ├─index: 1
      └─"\000\003\200\000\000\000\000\000\000\001"
        └─## decode index values
          ├─kind: Null, value:
          └─kind: Int64, value: 1
```

### 2. What did you expect to see? (Required)
Should parse successfully.

### 3. What did you see instead (Required)
return err `cannot convert datum from nil(type null) to type string. `

### 4. Affected version (Required)
all versions

### 5. Root Cause Analysis
`tablecodec.DecodeIndexKey` use `Datum.ToString()` to transform datum to string, but it will return error if datum is nil. 
Possible Solution:
- return a `null` string for null value `Datum` instead of directory call `Datum.ToString()` and return error directly.
- change return type to `[][]byte` instead of `[]string`

**Comment by gengliqi** [comment]
@disksing I remember it's your work. Could you take a look?

**Comment by disksing** [comment]
Possible related PR: https://github.com/pingcap/tidb/pull/6457
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
I'll take a look
