### ISSUE TITLE
plancodec: Update the format of plan encode to sync with plan explain.

### ISSUE THREAD

**Issue by LittleFall** [pingcap/tidb#17684]
## Development Task
The result of plan explain has 5 cols: "id", "estRows", "task", "access object", "operator info".

But the result of plan encode only has 4 cols, it merges "access object" and "operator info" as "explain info".

The result of plan encode should be updated.

Possible improvement: reused the code to meet both demand..

Note: after updating encode and decode, **tidb_decode_plan should still be able to deocde the encode string of previous version correctly.**

**Comment by qw4990** [comment]
Close since it is resolved.
