### ISSUE TITLE
Record/Anonymize Parameter Values for Parameterized Queries

### ISSUE THREAD

**Issue by breezewish** [pingcap/tidb#17690]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some users reported that for the Statement sample text, when performing Parameterized Queries (a.k.a. Prepared Statements), the parameter value is missing. This makes it impossible to re-execute the SQL when user discovered something wrong with the Statement.

**Describe the feature you'd like:**

Record query parameters in the sample text.

**Describe alternatives you've considered:**

Notice that, some users also request for the anonymization of parameters in the Slow Log for security considerations (see https://github.com/pingcap/tidb/issues/17463). We can expect that such users also want parameters in Statement be anonymized as well. Thus, we should provide a global variable as the first step to allow user decide whether these parameters shall be anonymized.

Some query parameters will appear in plan. We should remember to anonymize them as well.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by wwar** [comment]
See also: https://github.com/pingcap/tidb/issues/16653

**Comment by scsldb** [comment]
Note: Desensitization needs to be considered.
