### ISSUE TITLE
Mark `SingleReadOnly` transaction for further optimization.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1773]
When `autocommit` is set to 1 and there is no explicit `begin`, a SELECT statement will run in its own transaction and this transaction will never do write operation and read for only once, we can mark the transaction as `SingleReadOnly`.

We can do some optimization on it, like ignore lock check, as there will never be repeated read, we don't need to guarantee repeatable read.

Notice: some select statement, like join or sub-query may read the same row for more than once based on the execution plan, we can't mark them as `SIngleReadOnly`.

**Comment by tisonkun** [comment]
I don't find anything matches `SingleReadOnly` in current codebase.

@coocood could you please check whether the issue theoretically exists now?
