### ISSUE TITLE
Can not connect to the TiDB Server using the username and correct password

### ISSUE THREAD

**Issue by ruiaylin** [pingcap/tidb#1775]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
      go version go1.7.1 linux/amd64
2. What operating system and processor architecture are you using (`go env`)?
   [root@l20-8-65 ~]# cat /etc/redhat-release
    CentOS release 6.7 (Final)
3. What did you do?
    When the deployment of the TiDB server was done . I connect to the server using default username root like this : 
   
    mysql -uroot -h10.20.8.xxx  -P4000 
    // create a user 
   mysql> CREATE USER 'ruiaylin'@'%' IDENTIFIED BY 'ruiaylin'
    -> ;
   Query OK, 1 row affected (0.01 sec)

  // grant the privileges 
 mysql> GRANT ALL ON *.* TO  'ruiaylin'@'%'  ;
Query OK, 1 row affected (0.01 sec)

The Commands are executed successfully . But i can not connect to the server using the username i have create before . 

[root@l20-8-65 ~]# mysql -uruiaylin -pruiaylin -h10.20.8.6xxx -P4000
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1105 (HY000): ERROR 1045 (28000): Access denied for user 'ruiaylin'@'10.20.8.65' (using password: Yes)

TiDB's log show that : 

[root@l20-8-65 ~]# mysql -uruiaylin -pruiaylin -h10.20.8.64 -P4000
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1105 (HY000): ERROR 1045 (28000): Access denied for user 'ruiaylin'@'10.20.8.65' (using password: Yes)

4. What did you expect to see?

I  want to know why ? 
Is this a Bug?

**Comment by shenli** [comment]
@ruiaylin Thanks for your feedback!
Some clients do not set capability properly. We will fix it in this PR: https://github.com/pingcap/tidb/pull/1772

**Comment by coocood** [comment]
fixed by https://github.com/pingcap/tidb/pull/1772
