### ISSUE TITLE
Add unnecessary vendor `lint` after `make check`

### ISSUE THREAD

**Issue by overvenus** [pingcap/tidb#1778]
After including `_vendor/src` to `GOPATH`, we may add unnecessary vendor `lint` after `make check` if there is no `lint` present.

```sh
neil:tidb/ (master*) $ gst                                                                                                             [12:21:18]
On branch master
Your branch is up-to-date with 'upstream/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	_vendor/pkg/
	_vendor/src/github.com/golang/lint/

no changes added to commit (use "git add" and/or "git commit -a")
```

ref: #1748 

/cc: @tiancaiamao

**Comment by overvenus** [comment]
I think .gitignore is the quickest solution.

**Comment by overvenus** [comment]
`make install` may fails too.

**Comment by tiancaiamao** [comment]
let `go get github.com/golang/lint/golint` use the origin GOPATH ?
@shenli

**Comment by tiancaiamao** [comment]
`make install` can be removed, I think

**Comment by tiancaiamao** [comment]
and @coocood , what's your option?

**Comment by coocood** [comment]
How about go get golint before set _vendor to GOPATH?

**Comment by coocood** [comment]
go get golint use origin GOPATH is better.

**Comment by overvenus** [comment]
Not only golint. Glide, errcheck and anything relate to `go (get|build|install)` may be affected.

**Comment by overvenus** [comment]
close via #1782
