### ISSUE TITLE
question about the function EncodeIndexSeekKey

### ISSUE THREAD

**Issue by markjenny** [pingcap/tidb#17831]
## General Question

The EncodeIndexSeekKey encodes an index value to kv.key. So the length of returned `kv.Key` should be equals to the length of `t+tableID+_r+idxID+columnValues`.
But now, when initial the key, we only offer the `prefixLen+len(encodedValue)` bytes capacity for the key to use. The handle will also use 8 bytes, then the capacity of the key is not enough and the space of the key will be reallocated.
So at the beginning of the function, should we initial the variable `key` with the `RecordRowKeyLen + len(encodedValue)` capacity?
The code showed as below:
```
func EncodeIndexSeekKey(tableID int64, idxID int64, encodedValue []byte) kv.Key {
	key := make([]byte, 0, RecordRowKeyLen+len(encodedValue))
	key = appendTableIndexPrefix(key, tableID)
	key = codec.EncodeInt(key, idxID)
	key = append(key, encodedValue...)
	return key
}
```

**Comment by djshow832** [comment]
LGTM. I'll appreciate much if you submit a PR for TiDB.

**Comment by markjenny** [comment]
> LGTM. I'll appreciate much if you submit a PR for TiDB.

OK, I will submit a PR for this question.
