### ISSUE TITLE
Compile TiDB on master branch

### ISSUE THREAD

**Issue by hailanwhu** [pingcap/tidb#17835]
## General Question
When I compile the latest master, I meet the error:

```
go: github.com/pingcap/br@v0.0.0-20200521085655-53201addd4ad requires
	github.com/pingcap/tidb@v1.1.0-beta.0.20200509133407-a9dc72cf2558 requires
	github.com/pingcap/pd/v4@v4.0.0-rc.1.0.20200422143320-428acd53eba2: invalid pseudo-version: revision 428acd53eba2 is not a descendent of preceding tag (v4.0.0-rc.1)
```

When I checkout 4.0-perf branch and compile it, this question doesn't exist.

I use GoLand 2020.1 with go version 1.13.4.

**Comment by 3pointer** [comment]
I didn't reproduce it in laster master, could provide the TiDB commit hash when meet this error?

**Comment by hailanwhu** [comment]
Thanks for replying. I try to fork a new repo and this problem is solved. I think the problem is in my local env.
