### ISSUE TITLE
tidb-server crashed when i am tring to insert lots of data

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1784]
mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 57344 rows affected (0.92 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 114688 rows affected (1.92 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 229376 rows affected (3.87 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 458752 rows affected (7.36 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 917504 rows affected (14.38 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 1835008 rows affected (30.47 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
Query OK, 3670016 rows affected (55.83 sec)

mysql> INSERT INTO t2 SELECT \* FROM t2;
ERROR 2013 (HY000): Lost connection to MySQL server during query
mysql> desc t1;
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
ERROR 2003 (HY000): Can't connect to MySQL server on '127.0.0.1' (111)
ERROR: 
Can't connect to the server

TiDB crashed here because of OOM. Here is the schema information.

mysql> desc t1;
No connection. Trying to reconnect...
Connection id:    10001
Current database: test

+-------+--------------+------+------+---------+-------+
| Field | Type         | Null | Key  | Default | Extra |
+-------+--------------+------+------+---------+-------+
| name  | varchar(128) | YES  |      | NULL    |       |
| email | varchar(128) | YES  |      | NULL    |       |
+-------+--------------+------+------+---------+-------+
2 rows in set (0.00 sec)

Table t2 has the same schema of t1.

After i restart tidb-server:
mysql> select count(_) from t2;
+----------+
| count(_) |
+----------+
|  7340032 |
+----------+
1 row in set (44.94 sec)

The count is slow at the first time

mysql> select count(_) from t2;
+----------+
| count(_) |
+----------+
|  7340032 |
+----------+
1 row in set (2.87 sec)

I am using the branch: origin/busyjay/add-iterate-bound

**Comment by zhangjinpeng1987** [comment]
The first `select count() from t2` encounter many locks left by the last `INSERT INTO t2 SELECT * FROM t2`, and need wait the locks timeout.

**Comment by ngaut** [comment]
mysql> select count(*) from t2;
+----------+
| count(*) |
+----------+
| 26380032 |
+----------+
1 row in set (9.53 sec)

mysql> insert into t2 select * from t2 limit 4000000;
Query OK, 4000000 rows affected (1 min 18.82 sec)

mysql> insert into t2 select * from t2 limit 4000000;
Query OK, 4000000 rows affected (1 min 21.77 sec)

mysql> insert into t2 select * from t2 limit 4000000;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by zhangjinpeng1987** [comment]
I encounter the same problem. I observe the memory usage and find when the last `insert into ...` is running, the tidb progress used over 90% memory of the machine and then was killed by kernel. I guess it is because the memory used by the previous sqls has not been released by gc modular yet.
```
mysql> insert into t1 select count(*) from t1 limit 4000000;
ERROR 1105 (HY000): Column count 2 doesn't match value count 1
mysql> insert into t1 select * from t1 limit 4000000;
Query OK, 4000000 rows affected (1 min 16.01 sec)

mysql> insert into t1 select * from t1 limit 4000000;
Query OK, 4000000 rows affected (2 min 49.39 sec)

mysql> mysql> insert into t1 select * from t1 limit 4000000;
Query OK, 4000000 rows affected (1 min 19.46 sec)

mysql> insert into t1 select * from t1 limit 4000000;
Query OK, 4000000 rows affected (1 min 49.41 sec)

mysql> insert into t1 select * from t1 limit 4000000;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

**Comment by gejigeji** [comment]
I also met the problem when I load over 10 million lines of data.
I tried twice, first time, It loaded 11480000 lines, second time, It loaded 7980000 lines.

mysql> load data local infile 'path_to_data' into table t_table;   
ERROR 2013 (HY000): Lost connection to MySQL server during query

mysql> select count(*) from t_table;
+----------+
| count(*) |
+----------+
|  7980000 |
+----------+

**Comment by shenli** [comment]
@gejigeji Could you show me the log of tidb-server? Especially the error logs.

**Comment by gejigeji** [comment]
@shenli 
2017/02/15 12:15:18 conn.go:645: [error] load data rollback failed: [kv:8]invalid transaction
2017/02/15 12:15:18 conn.go:342: [error] /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:77: [server:3]invalid sequence 123 != 0
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:94:

**Comment by shenli** [comment]
Could you send me the whole log file? You can send compressed log file to shenli@pingcap.com. Thanks!

**Comment by gejigeji** [comment]
@shenli have sent to u
