### ISSUE TITLE
executor: update the usage of the channel to improve the produce-consume relationship among operators 

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#17849]
## Description
As explained in the source code reading of [hash join](https://pingcap.com/blog-cn/tidb-source-code-reading-9/) and [hash aggregation](https://pingcap.com/blog-cn/tidb-source-code-reading-22/), the relationship is
1 input : N worker : 1 output. Before one work joining tuples, the worker has to ask one empty chunk from the output, and get one non-empty chunk from the input. Note that it has to synchronously wait for the input or the output once the latters are not ready. 

Besides, We observe 20ms ~ 30ms free time for works by tracing the join. @SunRunAway 

To improve this produce-consume relationship, we may do as followers:

- [ ] increase the channel resouces among them. This may observe some improvements, but it is not better to do the following way. 
- [ ] update the usage of `go channel`, among 1 input and N worker, it just need one channle, instead of 1 + N channels, which is the current implementation. This causes more resources, complexes the code, makes it hard to understand. So we should change the current implementation by using one channel. Similar problem exists among N work : 1 outpe.  Then we dynamically set the size of the channel among producers and consumers to improve the online throughput.

## Score 

* score number 1000

## Mentor(s)

* @fzhedu 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* skills 1 know the usage of `go channel`
* skills 1 understand the produce-consume relationship in hash Join and hash aggregation.

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by TszKitLo40** [comment]
@fzhedu Can I try this issue?
