### ISSUE TITLE
release: v4.0.1

### ISSUE THREAD

**Issue by uglyengineer** [pingcap/tidb#17866]
pr merge
- [x] pr merge

release note
- [x] [release note-eng](https://github.com/pingcap/docs/pull/2816)
(note: transferred from [pr](https://github.com/pingcap/tidb-prm/pull/14))
- [x] [release note-chn](https://github.com/pingcap/docs-cn/pull/3600)

hash
- [x] TiDB：689a6b6439ae7835947fcaccf329a3fc303986cb（same as v4.0.0）
- [x] TiKV：511c346a4654f166845ec23fdffc70a94885d360
- [x] PD：30f0b014b7ff3cd1b5f041bf7ce73448dc0d0fe8
- [x] TiFlash：e134030e694906860b3d5b8729092351258e256c
- [x] Tools：
BR：78edafe5fdb45874eb7143319fb6e7649ad944c8
binlog: a75036cf8933a581cac42c1007bf92c9e5417b90（same as v4.0.0）
lightning: 391db4a233a870fc2044494caa770da791f49734（same as v4.0.0）
importer: b01e6b61014c43ce1cafbc95fe157165c84aa19b
tidb-tools: 6dd445d83fe05df5515662984d914a8a6523cc05（same as v4.0.0）
ticdc: b66fffd08bc444fb9c1d3c579a9f27f3f6a2fc3a（same as v4.0.0）

release works
- [x] Update docs ([pr1](https://github.com/pingcap/docs-cn/pull/3602))
- [x] [Testing report](https://docs.google.com/document/d/1L0h2VY09KmS9cevM2u3n_5FkuWZsAlTvMx5Endv8Gd4/edit#heading=h.pes7ci9vs44t)
- [x] Update tiup kits
- [x] Official Website downloading update
- [x] Clean up provisional tag from repository/ Close milestone

**Comment by liubo0127** [comment]
importer: b01e6b61014c43ce1cafbc95fe157165c84aa19b

**Comment by uglyengineer** [comment]
> importer: b01e6b61014c43ce1cafbc95fe157165c84aa19b

updated
