### ISSUE TITLE
Using kubernetes to deliver the TiDB cluster.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1787]
Currently deploy and rolling update the cluster is kind of pain, i guess the better way is using kubernetes to do all the staff.

**Comment by GregoryIan** [comment]
[how to easily install a secure Kubernetes cluster](http://kubernetes.io/docs/getting-started-guides/kubeadm/) . The new tool kubeadm in Kubernetes 1.4.

**Comment by ArvinDevel** [comment]
Can we currently deploy TiDB cluster over kubernetes easily? I think the k8s' auto-scale is very good, but it maybe not suitable for stateful db app. Have you guys solved related issue?

**Comment by shenli** [comment]
@ArvinDevel Yes, we can host a TiDB cluster in k8s. It rely on a component named TiDB-operator which is similar to etch-operator.

**Comment by ArvinDevel** [comment]
@shenli sounds good. thank you.

**Comment by morgo** [comment]
TiDB Operator is now available:
https://github.com/pingcap/tidb-operator

Should we close this issue?

**Comment by ngaut** [comment]
Sure, thanks.
