### ISSUE TITLE
Move `auto_random` out of experimental features

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#17882]
## Development Task

Since the attribute `auto_random` is stable now, we can move the option `allow-auto-random` out of the [experimental] section in the configuration file.

**Comment by tangenta** [comment]
@kennytm Yes.

**Comment by kolbe** [comment]
@tangenta @kennytm  IMO this should *not* be cherry-picked to release-3.1 and release-4.0. Customers expect configuration options to be stable. Any customers using --config-strict and experimental/allow-auto-random will find that their clusters refuse to start after doing a minor version upgrade.

**Comment by tangenta** [comment]
@kolbe I added this configuration option to the deprecated list. Now the old version clusters can be upgraded normally.
https://github.com/pingcap/tidb/pull/18618
