### ISSUE TITLE
Could hash partition and range partition be used together when creating a table?

### ISSUE THREAD

**Issue by Tongzhenguo** [pingcap/tidb#17908]

**Comment by djshow832** [comment]
No, it doesn't support.

**Comment by djshow832** [comment]
What's your requirement? Can you describe it? Maybe there's a way to walk around.

**Comment by Tongzhenguo** [comment]
> Can you describe your requirement? Maybe there's a way to walk around.

场景是gid的时序特征，以gid做hash分区，分散用户
以时间做范围分区，方便取某段时间的特征；

不过，用户分散压力不大的话，点查范围分区应该可以应付

**Comment by tiancaiamao** [comment]
Range partition table is mainly used in the drop partition scenario.
Hash partition is mainly used to avoid hot spot.

TiDB does not support subpartition yet.
If both feature are required, try to create a range partition and use [`shard_row_id_bits`](https://pingcap.com/docs/dev/tidb-specific-system-variables/#shard_row_id_bits), it can also scatter data to avoid hot spot.

B.T.W, we encourage using English in github(this community is mainly for developers)
Welcome to [AskTUG](https://asktug.com/) for general questions.

**Comment by Tongzhenguo** [comment]
> Range partition table is mainly used in the drop partition scenario.
> Hash partition is mainly used to avoid hot spot.
> 
> TiDB does not support subpartition yet.
> If both feature are required, try to create a range partition and use [`shard_row_id_bits`](https://pingcap.com/docs/dev/tidb-specific-system-variables/#shard_row_id_bits), it can also scatter data to avoid hot spot.
> 
> B.T.W, we encourage using English in github(this community is mainly for developers)
> Welcome to [AskTUG](https://asktug.com/) for general questions.

thanks,may be I don't use hash partition(any user only one record),just using range partition to  drop  old data is ok;
and I'll register AskTUG for general questions.
