### ISSUE TITLE
LOAD DATA LOCAL INFILE in v4.0.0 rc not supported

### ISSUE THREAD

**Issue by dolphinsboy** [pingcap/tidb#17903]
## Bug Report
cat << EOF > /tmp/t.csv
a,b
1,2
2,3
2,4
3,4
EOF

Please answer these questions before submitting your issue. Thanks!
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 16
Server version: 5.7.25-TiDB-v4.0.0-rc TiDB Server (Apache License 2.0), MySQL 5.7 compatible

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use test
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> DROP TABLE IF EXISTS t1;
Query OK, 0 rows affected (0.49 sec)

mysql> CREATE TABLE t1 (a INT NOT NULL PRIMARY KEY, b INT NOT NULL);
Query OK, 0 rows affected (0.29 sec)

mysql> LOAD DATA LOCAL INFILE '/tmp/t.csv' IGNORE INTO TABLE t1 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n';
ERROR 1148 (42000): The used command is not allowed with this MySQL version

**Comment by nrc** [comment]
Sounds like this issue is solved, so I'll close it. Please comment if you think this was an error and it can be reopened.
