### ISSUE TITLE
Legal partition name of a ranged table partition must begin with string? or must begin with 'p'?

### ISSUE THREAD

**Issue by Tongzhenguo** [pingcap/tidb#17914]
MySQL [feature]> CREATE TABLE feature.user_hot_click_list_weekly (
    ->     gid BIGINT NOT NULL,
    ->     feat_val VARCHAR(4000) NOT NULL,
    ->     create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    -> )
    -> PARTITION BY RANGE ( UNIX_TIMESTAMP(create_time) ) (
    ->     PARTITION 2020061000 VALUES LESS THAN ( UNIX_TIMESTAMP('2020-06-10 00:00:00') ),
    ->     PARTITION 9999999999 VALUES LESS THAN (MAXVALUE)
    -> )
    -> ;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 7 column 25 near "2020061000 VALUES LESS THAN ( UNIX_TIMESTAMP('2020-06-10 00:00:00') ),
    PARTITION 9999999999 VALUES LESS THAN (MAXVALUE)
)"

**Comment by tiancaiamao** [comment]
partition name needs to be an identifier, and pure number is not a valid identifier.
It does not need to start with 'p', here is legal identifiers:
https://dev.mysql.com/doc/refman/5.7/en/identifiers.html

@Tongzhenguo

**Comment by Tongzhenguo** [comment]
好的，明白了；之前hive写```date_p=yyyymmdd```，写习惯了
