### ISSUE TITLE
tidb-server crashed when i inserted 2 million rows in one transaction contiguously 

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1791]
I am using the latest master branch of tidb, tikv and pd.

mysql> insert into t1 select \* from t1 limit 2000000;
Query OK, 2000000 rows affected (1 min 13.37 sec)

mysql> insert into t1 select \* from t1 limit 2000000;
Query OK, 2000000 rows affected (1 min 31.87 sec)

mysql> insert into t1 select \* from t1 limit 2000000;
Query OK, 2000000 rows affected (1 min 0.80 sec)

mysql> insert into t1 select \* from t1 limit 2000000;
ERROR 2013 (HY000): Lost connection to MySQL server during query

**Comment by c4pt0r** [comment]
[ 6800.429480] Out of memory: Kill process 4343 (tidb-server) score 503 or sacrifice child
[ 6800.429495] Killed process 4343 (tidb-server) total-vm:4480864kB, anon-rss:4039668kB, file-rss:0kB, shmem-rss:0kB
[ 6800.660483] oom_reaper: reaped process 4343 (tidb-server), now anon-rss:0kB, file-rss:8kB, shmem-rss:0kB

**Comment by c4pt0r** [comment]
seems tidb-server didn't release memory in time.

**Comment by ngaut** [comment]
And after i restarted tidb-server, it could not count the table forever. I guess there is a bug related to GC or lock.

➜  [118] tidb-bin mysql -h127.0.0.1 -P4000 -uroot
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10010
Server version: 5.5.31-TiDB-1.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from t1 limit 1;
+------+---------------+
| name | email         |
+------+---------------+
| bob  | bob@gmial.com |
+------+---------------+
1 row in set (0.01 sec)

mysql> select count(*) from t1;
ERROR 1105 (HY000): [try again later]: backoffer.maxSleep 10000ms is exceeded, errors: [send tikv request error: read tcp 192.168.199.118:59389->192.168.199.116:20160: i/o timeout, ctx: region_id:300 region_epoch:<conf_ver:3 version:68 > peer:<id:303 store_id:6 > , try next peer later stale_epoch:<>  send tikv request error: read tcp 192.168.199.118:60354->192.168.199.116:20160: i/o timeout, ctx: region_id:300 region_epoch:<conf_ver:3 version:68 > peer:<id:303 store_id:6 > , try next peer later send tikv request error: read t
mysql> select count(*) from t1;
ERROR 1105 (HY000): [try again later]: backoffer.maxSleep 10000ms is exceeded, errors: [send tikv request error: read tcp 192.168.199.118:35541->192.168.199.116:20160: i/o timeout, ctx: region_id:300 region_epoch:<conf_ver:3 version:68 > peer:<id:303 store_id:6 > , try next peer later send tikv request error: read tcp 192.168.199.118:59397->192.168.199.116:20160: i/o timeout, ctx: region_id:300 region_epoch:<conf_ver:3 version:68 > peer:<id:303 store_id:6 > , try next peer later send tikv request error: read tcp 192.168.199.1

**Comment by ngaut** [comment]
From the log of tidb, looks like ticlient always got a NotLeder error.

 
2016/10/04 00:13:28 kv.go:211: [warning] tikv reports `NotLeader`: region_id:2 leader:<id:7 store_id:6 > , ctx: region_id:2 region_epoch:<conf_ver:3 version:2 > peer:<id:5 store_id:4 > , retry later
2016/10/04 00:13:28 backoff.go:158: [warning] send tikv request error: read tcp 192.168.199.118:42147->192.168.199.116:20160: i/o timeout, ctx: region_id:300 region_epoch:<conf_ver:3 version:68 > peer:<id:303 store_id:6 > , try next peer later, retry later(totalSleep 9877ms, maxSleep 10000ms)
2016/10/04 00:13:28 backoff.go:158: [warning] stale_epoch:<> , retry later(totalSleep 9977ms, maxSleep 10000ms)
2016/10/04 00:13:28 backoff.go:158: [warning] send tikv request error: read tcp 192.168.199.118:42170->192.168.199.116:20160: i/o timeout, ctx: region_id:2 region_epoch:<conf_ver:3 version:2 > peer:<id:7 store_id:6 > , try next peer later, retry later(totalSleep 64ms, maxSleep 10000ms)
2016/10/04 00:13:28 kv.go:211: [warning] tikv reports `NotLeader`: region_id:2 leader:<id:7 store_id:6 > , ctx: region_id:2 region_epoch:<conf_ver:3 version:2 > peer:<id:5 store_id:4 > , retry later
2016/10/04 00:13:28 backoff.go:158: [warning] send tikv request error: read tcp 192.168.199.118:42161->192.168.199.116:20160: i/o timeout, ctx: region_id:2 region_epoch:<conf_ver:3 version:2 > peer:<id:7 store_id:6 > , try next peer later, retry later(totalSleep 8034ms, maxSleep 10000ms)

**Comment by tiancaiamao** [comment]
After investigate this bug for a while, I find some clues.

One observation is that tidb-server never release memory as long as the session is alive, there must be something wrong.

Another found is that there is bug may cause resource leak, the detail info:

`partialResult` don't release resource on Close (wait its fetch goroutine exit) https://github.com/pingcap/tidb/blob/efc96a73a6e66c155082e863d620b4ca9984d48f/distsql/distsql.go#L255

when `partialResult.Next` meet an error and Close, background fetch goroutine may block on `<-pr.done` forever, so the unmarshaled `*Chunk` data can never released by GC.


Here is the pprof of inuse heap, that give clues to this bug.

```
(pprof) top
2842.86MB of 2850.59MB total (99.73%)
Dropped 316 nodes (cum <= 14.25MB)
Showing top 10 nodes out of 13 (cum >= 1208.47MB)
      flat  flat%   sum%        cum   cum%
 1583.18MB 55.54% 55.54%  1583.18MB 55.54%  github.com/pingcap/tipb/go-tipb.(*Chunk).Unmarshal
 1208.47MB 42.39% 97.93%  1208.47MB 42.39%  github.com/pingcap/kvproto/pkg/coprocessor.(*Response).Unmarshal
   51.20MB  1.80% 99.73%  1634.39MB 57.34%  github.com/pingcap/tipb/go-tipb.(*SelectResponse).Unmarshal
         0     0% 99.73%  1209.47MB 42.43%  github.com/golang/protobuf/proto.Unmarshal
         0     0% 99.73%  1209.47MB 42.43%  github.com/golang/protobuf/proto.UnmarshalMerge
         0     0% 99.73%  1209.47MB 42.43%  github.com/pingcap/kvproto/pkg/msgpb.(*Message).Unmarshal
         0     0% 99.73%  1209.47MB 42.43%  github.com/pingcap/kvproto/pkg/util.ReadMessage
         0     0% 99.73%  1634.39MB 57.34%  github.com/pingcap/tidb/distsql.(*partialResult).fetch
         0     0% 99.73%  1208.47MB 42.39%  github.com/pingcap/tidb/store/tikv.(*copIterator).handleTask
         0     0% 99.73%  1208.47MB 42.39%  github.com/pingcap/tidb/store/tikv.(*copIterator).work
```

**Comment by tiancaiamao** [comment]
Get pprof info http://xxx.xxx.xxx:port/debug/pprof/goroutine?debug=1

```
goroutine profile: total 68
47 @ 0x42ff3a 0x43002e 0x406c38 0x4069fd 0x9ea610 0x460cd1
#	0x9ea60f	github.com/pingcap/tidb/distsql.(*partialResult).fetch+0x38f	/home/tiancaiamao/project/src/github.com/pingcap/tidb/distsql/distsql.go:175

2 @ 0x42ff3a 0x42a82b 0x429f89 0x48c698 0x48c704 0x48df41 0x49ebc0 0x8942c4 0x85566c 0x856315 0x856497 0xa5e4fe 0xa5e2ff 0x88ed35 0x89563d 0x899653 0x460cd1
#	0x429f88	net.runtime_pollWait+0x58			/usr/local/go/src/runtime/netpoll.go:160
#	0x48c697	net.(*pollDesc).wait+0x37			/usr/local/go/src/net/fd_poll_runtime.go:73
#	0x48c703	net.(*pollDesc).waitRead+0x33			/usr/local/go/src/net/fd_poll_runtime.go:78
#	0x48df40	net.(*netFD).Read+0x1a0				/usr/local/go/src/net/fd_unix.go:243
#	0x49ebbf	net.(*conn).Read+0x6f				/usr/local/go/src/net/net.go:173
#	0x8942c3	net/http.(*connReader).Read+0x143		/usr/local/go/src/net/http/server.go:586
#	0x85566b	bufio.(*Reader).fill+0x10b			/usr/local/go/src/bufio/bufio.go:97
#	0x856314	bufio.(*Reader).ReadSlice+0xb4			/usr/local/go/src/bufio/bufio.go:330
#	0x856496	bufio.(*Reader).ReadLine+0x36			/usr/local/go/src/bufio/bufio.go:359
#	0xa5e4fd	net/textproto.(*Reader).readLineSlice+0x5d	/usr/local/go/src/net/textproto/reader.go:55
#	0xa5e2fe	net/textproto.(*Reader).ReadLine+0x2e		/usr/local/go/src/net/textproto/reader.go:36
#	0x88ed34	net/http.readRequest+0xa4			/usr/local/go/src/net/http/request.go:793
#	0x89563c	net/http.(*conn).readRequest+0x10c		/usr/local/go/src/net/http/server.go:765
#	0x899652	net/http.(*conn).serve+0x3d2			/usr/local/go/src/net/http/server.go:1532

2 @ 0x42ff3a 0x42a82b 0x429f89 0x48c698 0x48c704 0x48df41 0x49ebc0 0x8ab214 0x85566c 0x855852 0x8abe31 0x460cd1
#	0x429f88	net.runtime_pollWait+0x58		/usr/local/go/src/runtime/netpoll.go:160
#	0x48c697	net.(*pollDesc).wait+0x37		/usr/local/go/src/net/fd_poll_runtime.go:73
#	0x48c703	net.(*pollDesc).waitRead+0x33		/usr/local/go/src/net/fd_poll_runtime.go:78
#	0x48df40	net.(*netFD).Read+0x1a0			/usr/local/go/src/net/fd_unix.go:243
#	0x49ebbf	net.(*conn).Read+0x6f			/usr/local/go/src/net/net.go:173
#	0x8ab213	net/http.(*persistConn).Read+0x153	/usr/local/go/src/net/http/transport.go:1256
#	0x85566b	bufio.(*Reader).fill+0x10b		/usr/local/go/src/bufio/bufio.go:97
#	0x855851	bufio.(*Reader).Peek+0x61		/usr/local/go/src/bufio/bufio.go:129
#	0x8abe30	net/http.(*persistConn).readLoop+0x1a0	/usr/local/go/src/net/http/transport.go:1413

2 @ 0x42ff3a 0x43f4c9 0x43e2bc 0x8ad9dd 0x460cd1
#	0x8ad9dc	net/http.(*persistConn).writeLoop+0x3bc	/usr/local/go/src/net/http/transport.go:1641
```

This line means there are 68 goroutines totally:

`goroutine profile: total 68`

And 47 of them block at distsql.go:175

```
47 @ 0x42ff3a 0x43002e 0x406c38 0x4069fd 0x9ea610 0x460cd1
#	0x9ea60f	github.com/pingcap/tidb/distsql.(*partialResult).fetch+0x38f	
/home/tiancaiamao/project/src/github.com/pingcap/tidb/distsql/distsql.go:175
```

I use a slightly changed version for testing, and distsql.go:175 is actually https://github.com/pingcap/tidb/blob/efc96a73a6e66c155082e863d620b4ca9984d48f/distsql/distsql.go#L169

In a word, goroutine leak, memory referenced by it is not freed.

**Comment by tiancaiamao** [comment]
after PR https://github.com/pingcap/tidb/pull/1834 , maybe there is still leak under very heavy throughput, infrequency and take longer to debug, I'll come back later.

this is the place may leak:
https://github.com/pingcap/tidb/blob/6938f973cb01b4f1209d7af6bf9d2e789b23ab51/store/tikv/coprocessor.go#L328

**Comment by coocood** [comment]
Now TiDB has enforced row limit in one transaction.
