### ISSUE TITLE
can use tidb store picture? 

### ISSUE THREAD

**Issue by lygn128** [pingcap/tidb#17929]
can use tidb to store many many  pictures?   thank you very much

**Comment by djshow832** [comment]
It's OK to store many objects using `BLOB`. But we need more details about the workload.
- What's the QPS of writes and reads? 
- How big is one picture? One value can not exceed 6MB due to TiKV raft limitation.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
