### ISSUE TITLE
Try to increase the pessimistic transaction commit success rate with concurrent DDLs

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#17932]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, schema check will be done during two-phase transaction commit in TiDB. If there are any schema change happens to the transaction-related tables during its execution, the commit will be rejected to ensure correctness, and the client will receive the `ErrSchemaChanged` error and is required to retry the transaction.

**Describe the feature you'd like:**

For pessimistic transaction execution, the related data are pessimistically locked and for some schema change types, some changes could be done to the transcation memory buffer so that this transaction is aware of the concurrent schema change. Thus this conflict could be serialized and the pessimistic transaction could commit and the data consistency is kept.

**Describe alternatives you've considered:**

Implement another MySQL `meta data lock` like utility to block concurrent DDLs when pessimistic transactions are ongoing.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
It looks good to me. I'm curious about the priority of this issue. @cfzjywxk Could you give some advice about the priority, is it expected to be finished in TiDB 5.0?

**Comment by cfzjywxk** [comment]
It's duplicate with https://github.com/pingcap/tidb/issues/18098, I thought there was no issues on GitHub at first.
