### ISSUE TITLE
Speed memdb inside of goleveldb by removing locks.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1794]
Currently we are using memdb in a single thread, so the lock is not necessary.

**Comment by tiancaiamao** [comment]
Once upon a time, I've tried to remove the lock in the memdb rand.Source, but get runtime panic, and later fix it in this commit:
https://github.com/pingcap/goleveldb/commit/c131135d59a38f4212f627cde570dddfe5261c43

So maybe it's not the truth "memdb in a single thread" and lock can't be avoid.

**Comment by coocood** [comment]
Resolved by https://github.com/pingcap/goleveldb/pull/4 and https://github.com/pingcap/tidb/pull/1812
