### ISSUE TITLE
DM迁移过程中报错：the max entry size is 6291456, the size of data is 11943317，然后后面报bad connection和connection is already closed

### ISSUE THREAD

**Issue by hezhiqiang** [pingcap/tidb#17973]
我在用DM迁移MySQL数据时报了标题中的错误，检查了MySQL中的数据，有个content字段，是LongText类型，那条记录这个字段有5969395字段，它应该没有超过LongText的最大长度，TiDB无法存储这么大的字段吗？

**Comment by july2993** [comment]
Due to the limitations of the underlying storage engine, TiDB requires a single row to be no more than 6 MB。
for the detail, pls see https://pingcap.com/docs/dev/transaction-overview/#transaction-size-limit

**Comment by GregoryIan** [comment]
tidb will relax the limit in this pr https://github.com/pingcap/tidb/pull/17986/files.

If you

**Comment by GregoryIan** [comment]
@hezhiqiang  If you are in a hurry, you can build a tidb-server first and then use tiup to replace tidb-server bianry offline. 

refer document https://docs.pingcap.com/zh/tidb/dev/tiup-cluster#%E6%9B%B4%E6%96%B0%E7%BB%84%E4%BB%B6

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates you can reopen it.
