### ISSUE TITLE
The implement of index scan for cluster index is not correct

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#17977]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
After #17853 is merged.
I tried these following statements:
```
mysql> CREATE TABLE pkt1 (a varchar(255), b int, index idx(b), primary key(a,b));
Query OK, 0 rows affected (0.01 sec)

mysql> insert into pkt1 values ('aaa',1);
Query OK, 1 row affected (0.00 sec)

mysql> select b from pkt1 where b = 1;
+---+
| b |
+---+
| 1 |
+---+
1 row in set (0.00 sec)
mysql> select b from pkt1 use index(primary);
Empty set (0.00 sec)
mysql> select a from pkt1 where a="aaa";
Empty set (0.00 sec)


CREATE TABLE pkt2 (a varchar(255), b int, unique index idx(b), primary key(a,b));
insert into pkt2 values ('aaa',1);
mysql> select * from pkt2 use index(b);
ERROR 1176 (42000): Key 'b' doesn't exist in table 'pkt2'


```

### 2. What did you expect to see? (Required)
select b from pkt1 use index(primary);

Return one row.
### 3. What did you see instead (Required)
Empty.

### 4. Affected version (Required)
master.

**Comment by wjhuang2016** [comment]
Besides：
![image](https://user-images.githubusercontent.com/17380469/84648102-0cbd0e00-af37-11ea-9774-9dd929d5822b.png)

**Comment by coocood** [comment]
fixed by https://github.com/pingcap/tidb/pull/18302
