### ISSUE TITLE
[Proposal]Add version in tidb

### ISSUE THREAD

**Issue by astaxie** [pingcap/tidb#18]
Version is a good flag for users. User can use version to update and report issues.

**Comment by ngaut** [comment]
We have already support version. https://github.com/pingcap/tidb/blob/master/util/printer/printer.go#L23

**Comment by astaxie** [comment]
That's weird. Why put the version in the util package? From the structure it's not make sense.

**Comment by ngaut** [comment]
We may use it in interpreter. MySQL protocol layer. Or HBase engine.
Put to util package, so we keep it DRY.

**Comment by astaxie** [comment]
You mean you will use the version in many other packages? Then the version is out of control. :smile_cat:

**Comment by ngaut** [comment]
WOW, User could pass version information to those variables :)

**Comment by xiang90** [comment]
@ngaut Well... You can make then read-only.

**Comment by ngaut** [comment]
It's read only after assignment.

**Comment by c4pt0r** [comment]
any updates? @ngaut

**Comment by ngaut** [comment]
@astaxie

**Comment by astaxie** [comment]
I have no idea on the version now. AFAIK https://github.com/pingcap/tidb/blob/master/util/printer/printer.go#L23 looks not good enough.

**Comment by Unknwon** [comment]
+1 

Need something like `Version()` around [here](https://github.com/pingcap/tidb/blob/master/tidb.go#L45), and it should return semantic version, so app can check it in case a bug was introduced in older version but fixed in newer one.

**Comment by fuxiaohei** [comment]
the version number is useful to version control.

Now I find that if tidb code updated, the old goleveldb data directory can't load.

So I need lock a version to make sure to develop and compile.

**Comment by ngaut** [comment]
Currently TiDB is evolving extremely fast.   The version information is generated automatically by makefile:

LDFLAGS += -X "github.com/pingcap/tidb/util/printer.TiDBBuildTS=$(shell date -u '+%Y-%m-%d %I:%M:%S')"
LDFLAGS += -X "github.com/pingcap/tidb/util/printer.TiDBGitHash=$(shell git rev-parse HEAD)"

Does that sound ok?   @fuxiaohei
