### ISSUE TITLE
Make Expression Index generally available

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18008]
### Description
Since TiDB 4.0, one can put indexes on expressions, aka expression indexes. This feature is quite useful when dealing with JSON functions.

However, it is still an experimental feature: https://docs.pingcap.com/tidb/dev/sql-statement-create-index#expression-index

> Warning:
>
> Expression index is still an experimental feature. It is NOT recommended that you use it in the production environment.

We plan to make it stable enough to be production-ready in the near future.

### Category
Feature, Performance.

### Value
it helps to improve the performance of queries whose filter contains expressions. 

### Schedule
- Start Date:2020-07-01
- End Date: 2020-08-31
- GanttProgress: 50%

**Comment by nullnotnil** [comment]
As noted in the description, this is useful for JSON. But this use case is currently not supported by the optimizer due to a regression: https://github.com/pingcap/tidb/issues/14456

**Comment by Defined2014** [comment]
Close this issue as expression index is GA since v6.5
