### ISSUE TITLE
Reduce latency jitter caused by balance

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18012]
### Description
Reduce latency jitter caused by Hotspots （read、write region or index)
### Category
Stability

#### P0 Reduce unnecessary scheduling
- [x] https://github.com/tikv/pd/issues/3050  Reduce unnecessary hot region operator during rolling upgrade TiKV
- [x] https://github.com/tikv/pd/pull/3269  reduce the unnecessary  balance region operator caused by the space used ratio
- [x] https://github.com/tikv/pd/pull/3344 reduce the unnecessary balance caused by the empty region
 
#### P1 Optimal scheduling strategy
- [ ] https://github.com/pingcap/pd/issues/2520. HotRegion Scheduler Consider QPS

### Value
Improve system stability.

### Time

GanttStart: 2020-09-11
GanttDue: 2020-11-28
GanttProgress: 100%

### Weekly Report
https://docs.google.com/document/d/1iQb-s1QCP8I5MAZlZcGCFurKAQLeD5J1W7qXmqaYKZU/edit#

**Comment by nolouch** [comment]
all P0 is done, I'm going to close this issue.
