### ISSUE TITLE
Need record point-get RPC  time cost in slow log

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#18037]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Below is a slow log:

```sql
# Time: 2020-06-15T18:40:09.280216+08:00
# Txn_start_ts: 417390213722275841
# User: root@127.0.0.1
# Conn_ID: 1
# Query_time: 302.256927773
# Parse_time: 0.000037113
# Compile_time: 0.000025758
# Rewrite_time: 0.00000092
# Optimize_time: 0.000006145
# Wait_TS: 0.000131557
# DB: test
# Is_internal: false
# Digest: 443fb1af91248b6a2943fcaeba3186e9360601dc7db9dbed9e921347ef9172ca
# Num_cop_tasks: 0
# Prepared: false
# Plan_from_cache: false
# Has_more_results: false
# Succ: true
# Plan: tidb_decode_plan('XsAwCTM4XzEJMAkyCXRhYmxlOkdMT0JBTF9WQVJJQUJMRVMsIGluZGV4OlBSSU1BUlkoERmQX05BTUUpLCBrZWVwIG9yZGVyOmZhbHNlLCBkZXNjOmZhbHNlCg==')
# Plan_digest: 9030fefb1d63c5747f83dfe86dd2720052a602bf9d8ff31b21ad4add7a8defc8
select * from mysql.global_variables where variable_name in ("autocommit","sql_mode");
```

It's was hard to see the reason of the query so slow,  since it doesn't record the RPC request duration of `BatchPointGet`. `PointGet` is too.

**Describe the feature you'd like:**

Record the RPC request time of `PointGet` and `BatchPointGet`.

**Describe alternatives you've considered:**

Maybe we can record the duration of all kinds of RPC requests.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by crazycs520** [comment]
should be addressed in https://github.com/pingcap/tidb/pull/17591

**Comment by zz-jason** [comment]
@crazycs520 can we close this issue now?

**Comment by crazycs520** [comment]
Ok, and this issue should also be addressed in https://github.com/pingcap/tidb/pull/18666
