### ISSUE TITLE
memory leak in mockstore

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tidb#18048]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
package main

import (
	"os"
	"runtime/pprof"

	"github.com/pingcap/tidb/session"
	. "github.com/pingcap/tidb/store/mockstore"
)

func testMock() {
	opts := []MockTiKVStoreOption{WithStoreType(MockTiKV)}
	store, _ := NewMockStore(opts...)
	defer store.Close()

	dom, _ := session.BootstrapSession(store)
	defer dom.Close()
}

func main() {
	for i := 0; i < 10; i++ {
		testMock()
	}
	f, _ := os.Create("heap_profile")
	pprof.WriteHeapProfile(f)
}
```

### 2. What did you expect to see? (Required)
free the memory when dom.Close()
### 3. What did you see instead (Required)
![out](https://user-images.githubusercontent.com/35025882/84737184-604e4c80-af75-11ea-95f3-440da54bc4fa.png)

### 4. Affected version (Required)
tidb master

**Comment by tiancaiamao** [comment]
Yes, I can confirm the memory leak.
It's caused by some global variable references, but I do not know which global variable.

**Comment by tiancaiamao** [comment]
Those are the global variables of the test program.
I use `dlv attach` to get them.

[global.LOG](https://github.com/pingcap/tidb/files/4812056/global.LOG)

**Comment by csuzhangxc** [comment]
Most of global variables will not increase memory usage, I think we can just let them stay there.

But some of them may increase memory usage after repeated `NewMockStore`/`BootstrapSession`/`Close`, I think we should fix them.

**Comment by tiancaiamao** [comment]
The global variable itself does not increase memory usage, but the may reference some other variable and make the variable can not be released by GC, thus leak.

**Comment by tiancaiamao** [comment]
I find one place of the leak https://github.com/pingcap/tidb/blob/c9c0daf310b5194a53995b119f998e02786ecceb/expression/builtin_vectorized.go#L48   @qw4990

**Comment by csuzhangxc** [comment]
@tiancaiamao @qw4990 Is anyone still working on this?

**Comment by tiancaiamao** [comment]
No progress on this issue. @csuzhangxc 
I've tried my best but found it's too difficult to check **all the global variable references**.

**Comment by csuzhangxc** [comment]
@tiancaiamao can you fix the one you found above first?

https://github.com/pingcap/tidb/blob/c9c0daf310b5194a53995b119f998e02786ecceb/expression/builtin_vectorized.go#L48

**Comment by csuzhangxc** [comment]
ping anyone

**Comment by qw4990** [comment]
Sorry for my late reply. Could you please give me your `go.mod`? I cannot reproduce this problem now. @csuzhangxc

**Comment by qw4990** [comment]
Since this problem only occurs in `mockstore`, its severity is degraded to minor.

**Comment by GMHDBJD** [comment]
[test.tar.gz](https://github.com/pingcap/tidb/files/5627183/test.tar.gz)
I reproduce with master tidb.(both mocktikv and unistore)

**Comment by zhangysh1995** [comment]
@ichn-hu Could you please add a label for the bug fixing challenge that I could pick up this issue?

**Comment by wjhuang2016** [comment]
> @ichn-hu Could you please add a label for the bug fixing challenge that I could pick up this issue?

You can fire a PR to fix it directly.

**Comment by GMHDBJD** [comment]
Ping

**Comment by lance6716** [comment]
found that `domap` still holds a reference to Domain after Domain is closed, but after cleaning the map the memory still can't decrease

https://github.com/pingcap/tidb/blob/7755d25aba5120dafde98fff11ab3b98ca4d192f/session/tidb.go#L103-L105

**Comment by gozssky** [comment]
I found statisticsList will always hold the statistics which is probably a `*ddl.ddl`.
https://github.com/pingcap/tidb/blob/c26038ba5eb32bc12689f00fb6c73763dfbc0339/sessionctx/variable/statusvar.go#L46-L50

After clear domap and comment the follow two lines, the memory didn't increase all the time.

https://github.com/pingcap/tidb/blob/c26038ba5eb32bc12689f00fb6c73763dfbc0339/bindinfo/handle.go#L120
https://github.com/pingcap/tidb/blob/c26038ba5eb32bc12689f00fb6c73763dfbc0339/ddl/ddl.go#L386
