### ISSUE TITLE
request to support `ST_GeoHash()` functions

### ISSUE THREAD

**Issue by hezhiqiang** [pingcap/tidb#18047]
希望能够支持st_geohash等函数

**Comment by zz-jason** [comment]
@hezhiqiang Do you mean to support all the Spatial Geohash Functions in MysQL?

**Comment by hezhiqiang** [comment]
@zz-jason support all is best~

**Comment by zz-jason** [comment]
Could you describe more about the usage of these functions, for example, do you use TiDB to store spatial data and doing the spatial analysis?

**Comment by nullnotnil** [comment]
I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/6347 , which is a more broad request for SPATIAL functions and indexes. Thanks!
