### ISSUE TITLE
Support hints for `INSERT` statements

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#18049]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In https://github.com/pingcap/tidb/pull/16966 , we are going to support `MEMORY_QUOTA` hint for `insert`. However, maybe there existed others hints could be supported for `InsertStmt`. 

**Describe the feature you'd like:**

After I search the available hints in the [document](https://docs.pingcap.com/zh/tidb/v4.0/optimizer-hints#optimizer-hints). In my view, `MAX_EXECUTION_TIME` and `MEMORY_QUOTA` could be supported for `InsertStmt`.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
- For `insert ... select ...` statements, we can put the hints to the `select` query block.
- For `insert ... values ...` statements, do we really need hints for these kinds of statements? Could you describe more on the use cases? @Yisaer

**Comment by Yisaer** [comment]
> * For `insert ... select ...` statements, we can put the hints to the `select` query block.
> * For `insert ... values ...` statements, do we really need hints for these kinds of statements? Could you describe more on the use cases? @Yisaer

For the second cases, I think the current supported hints status is enough.

**Comment by zz-jason** [comment]
are all the hints supported for the insert statement?
