### ISSUE TITLE
Support the operation of adding multi-indexes in one statement

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#18053]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Adding multiple indexes in the same DDL statement is currently not supported:

```sql
DROP TABLE IF EXISTS t;
CREATE TABLE t (a int, b int);
ALTER TABLE t ADD INDEX (a), ADD INDEX (b);

..
mysql> ALTER TABLE t ADD INDEX (a), ADD INDEX (b);
ERROR 8200 (HY000): Unsupported multi schema change
```
**Describe the feature you'd like:**

```
mysql>  ALTER TABLE t ADD INDEX (a), ADD INDEX (b);
Query OK, 0 rows affected (0.03 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

Support adding multi-columns in one statement, the syntax as follows:
```
ALTER TABLE tbl_name
    [alter_option [, alter_option] ...]

alter_option:
ADD {INDEX | KEY} [index_name]
        [index_type] (key_part,...) [index_option] ...
| ADD [CONSTRAINT [symbol]] UNIQUE [INDEX | KEY]
        [index_name] [index_type] (key_part,...)
        [index_option] ...
```

Refer to: https://dev.mysql.com/doc/refman/5.7/en/alter-table.html

We can refer to the implementation of #5092(Support the operation of adding multi-columns).

## Score
3600

## Mentor(s)
* @zimulala

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Recommended Skills
* DDL
* Golang

## Learning Materials
MySQL's [document](https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html) for syntax reference.
[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by morgo** [comment]
(I have updated the description. The example showed dropping multiple indexes at once using incorrect syntax.)

**Comment by tangenta** [comment]
Adding multiple indexes is supported by https://github.com/pingcap/tidb/pull/35989.

```sql
mysql> CREATE TABLE t (a int, b int);
Query OK, 0 rows affected (0.04 sec)

mysql> ALTER TABLE t ADD INDEX (a), ADD INDEX (b);
Query OK, 0 rows affected (0.09 sec)

mysql> show create table t;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                            |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  KEY `a` (`a`),
  KEY `b` (`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
