### ISSUE TITLE
Support LIST COLUMNS partitioning

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#18052]
## Feature Request

**Is your feature request related to a problem? Please describe:**

MySQL support [LIST COLUMNS](https://dev.mysql.com/doc/refman/8.0/en/partitioning-columns-list.html) partition but TiDB didn't support it now.

support it will help mysql user migrate to TiDB

**Describe the feature you'd like:**

Compatible with  MySQL's [LIST COLUMNS](https://dev.mysql.com/doc/refman/8.0/en/partitioning-columns-list.html) partition 

**Describe alternatives you've considered:**

n/a

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
list partition is useful in the geo-partition scenario. take the following table (from [LIST COLUMNS partitioning - MySQL](https://dev.mysql.com/doc/refman/8.0/en/partitioning-columns-list.html)) as an example:

```sql
CREATE TABLE customers (
    first_name VARCHAR(25),
    last_name VARCHAR(25),
    street_1 VARCHAR(30),
    street_2 VARCHAR(30),
    city VARCHAR(15),
    renewal DATE
)

PARTITION BY LIST COLUMNS(city) (
    PARTITION pRegion_1 VALUES IN('Oskarshamn', 'Högsby', 'Mönsterås'),
    PARTITION pRegion_2 VALUES IN('Vimmerby', 'Hultsfred', 'Västervik'),
    PARTITION pRegion_3 VALUES IN('Nässjö', 'Eksjö', 'Vetlanda'),
    PARTITION pRegion_4 VALUES IN('Uppvidinge', 'Alvesta', 'Växjo')
);
```

with placement rules (https://github.com/pingcap/tidb/issues/18030), we can define a location constraint for each partition to achieve better read/write performance.

**Comment by zz-jason** [comment]
@crazycs520 PTAL

**Comment by crazycs520** [comment]
Should be supported in https://github.com/pingcap/tidb/pull/20279
