### ISSUE TITLE
 cannot create index on virtual generated column.

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tidb#18061]
## Bug Report

 Cannot create index on virtual generated column gened by primary key after #18045 merge.

### 1. Minimal reproduce step (Required)
```
drop database if exists `db`;
create database `db`;
use `db`;
create table t1 (id int, PRIMARY KEY (id));
insert into t1 values(1);
alter table t1 add column gen_id int as (id+1);
alter table t1 add index idx(`gen_id`);
```

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
```
ERROR 8202 (HY000): Cannot decode index value, because Miss column
```
### 4. Affected version (Required)
Server version: 5.7.25-TiDB-v4.0.0-beta.2-636-gc19018e06

**Comment by zimulala** [comment]
@wjhuang2016 PTAL
