### ISSUE TITLE
Support SQL based import/export/backup/restore/TiCDC

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18089]
### Description
Support SQL based import/export/backup/restore/TiCDC

### Category
Feature

### Value
Improve system usability.

**Comment by IANTHEREAL** [comment]
We have implemented sql based backup & recovery in https://github.com/pingcap/tidb/pull/16960 in 4.0

sql based import/export will be implemented as a sub-task of https://github.com/pingcap/tidb/issues/18629

sql based TiCDC will be implemented as sub-task of https://github.com/pingcap/ticdc/issues/736
