### ISSUE TITLE
in tidb v4.0.1(and v4.0.0) version,whether or not  the default value type of timestamp cann't be setting with 'CURRENT_TIMESTAMP'

### ISSUE THREAD

**Issue by 331527583** [pingcap/tidb#18088]
## v4.0.1 version timestamp default value can't be setting with CURRENT_TIMESTAMP
when i import data table from v4.0.0 to v4.0.1,i found there is a table whose column type is timestamp and column default value been setted with 'CURRENT_TIMESTAMP' ,then it can't 
be created  successfully.Tidb log tell me that below this :
```
[types:1067]Invalid default value for 'update_time'
```

And when i insert a value to the kind of table likes below  ：
```
INSERT INTO `tag_var_tree` (`id`, `pid`, `name`, `whole_code`, `sort_id`, `var_flag`, `var_code`, `up_cyc`, `var_obj`, `src`, `remark`, `valid_flag`, `update_user`, `update_time`) VALUES
	(128, 0, '个人特征', NULL, 57, NULL, NULL, 1, 1, NULL, 'root', 1, NULL, 'CURRENT_TIMESTAMP')
```
it also can't be done successfully .

when i do selecting data  from tidb server  which has been upgrading from v3.0.5 to v4.0.0  , and it's outputting  like below this:
```
update_time(column name)
CURRENT_TIMESTAMP (column value)
```
and i import data from v4.0.0 to v4.0.1 ,it's failed because of 'CURRENT_TIMESTAMP '.So i cant import data column of timestamp which default value has been setting with 'CURRENT_TIMESTAMP '  from tidb v4.0.0 to v4.0.1 database.And what can we deal with the past table that has already  used with 'CURRENT_TIMESTAMP'

**Comment by jebter** [comment]
Please refer: https://docs.pingcap.com/tidb/stable/date-and-time-functions. I will close this issue. If there are any updates, you can reopen it.
