### ISSUE TITLE
SQL use like statement，show Utf8Error

### ISSUE THREAD

**Issue by JackDrogon** [pingcap/tidb#1808]
ENV:
go version: `go1.6.1 linux/amd64`

go env:

```
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/xuruiliang/.go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GO15VENDOREXPERIMENT="1"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0"
CXX="g++"
CGO_ENABLED="1"
```

Problem:
I use sql to search data like '%{', an error happened like that `ERROR 1105 (HY000): other error: unknown error Codec(Encoding(Utf8Error { valid_up_to: 253 }))`

SQL: `select * from contents where data like "{%";`, Data like that:  `{"__plat":"pc_web","content":"现在我发现这些八卦记者真能忽悠"}`

**Comment by coocood** [comment]
@JackDrogon 
Thank you for your report, we will look into it.

**Comment by coocood** [comment]
@JackDrogon 
How is your data inserted? can you reproduce this error?

**Comment by JackDrogon** [comment]
I can reproduce this error. I use gorm as orm, db.update for insert data. `select * from contents limit 10;` can show the data. the result as
```
|  1 | 33739414 |  55666 | 1475990130 | {"__plat":"android","content":"那只浣熊怎么弄的"}
```
but I use `select * from contents where data like "{%";` what report error.
mysql uri is `root:@tcp(127.0.0.1:4000)/test?charset=utf8&parseTime=True&loc=Local`

**Comment by coocood** [comment]
The input data is written in code or parsed from some text file?

**Comment by JackDrogon** [comment]
The input data is from kafka.

**Comment by JackDrogon** [comment]
The data is ` `data` varchar(255) DEFAULT NULL` in tidb.

**Comment by coocood** [comment]
Maybe the data in kafka is not UTF8, can you confirm that?

**Comment by coocood** [comment]
Can you provide sample input data, so we can reproduce it.

**Comment by JackDrogon** [comment]
I can output data in my go progrma. My terminal's encoding is utf8. So I think the data is utf8.

**Comment by JackDrogon** [comment]
Some data is about my company's privacy? Can you offer me your email address. I can give you some data by email.

**Comment by coocood** [comment]
Please send it to email at my profile page.
Thank you.

**Comment by JackDrogon** [comment]
OK.
