### ISSUE TITLE
Support Allowing TiDB to write directly to TiFlash

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18086]
### Description
Support Allowing TiDB to write directly to TiFlash. Including Raft leader role implementation、 upsert and other DML, simplified txn、DM and lightning.

### Category
Feature

### Value
This will allow TiDB truly hybrid storage format. 
* Lower cost. At least ¼ TiFlash cases uses only realtime updatable columnar storage for gathering and analyze data. They need no row format.
Speedup: we can build up low cost upsert behavior for dumping and writing data. And thus better supporting batch scenarios for finance sector and also real time data warehouses or so called datahub.
* A lot larger region size and lower rate of schedule is potentially allowed thus larger storage capacity.
* Better supporting our current real time data warehouse cases: Enable auto cold data archive. Easier append-only cases support. 
* This will be a huge boost to our realtime warehousing scenarios. If users need to store data silos in other systems, the legitimacy of TiDB in such cases will be eliminated.

**Comment by zz-jason** [comment]
@zanmato1984 PTAL

**Comment by zz-jason** [comment]
I think it's duplicated with https://github.com/pingcap/tidb/issues/18300. Can we close one of these issues? @scsldb @zanmato1984

**Comment by zanmato1984** [comment]
Dup with https://github.com/pingcap/tidb/issues/18300, closing.
