### ISSUE TITLE
Optimize GC strategy

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18093]
### Description
Optimize GC strategy. including: 
* Supports setting table level GC https://github.com/pingcap/tidb/issues/18117
* force a GC (to purge deleted data a.s.a.p.)
* Supports GC setting for dropped/truncated tables 

### Category
Feature、Reliability

### Value
* Flexible data versioning and space management
* Free up disk space; Really remove secret data 

### Workload Estimation
300

**Comment by jackysp** [comment]
What's the original JIRA link of this issue? @scsldb

**Comment by zhangjinpeng1987** [comment]
I think https://github.com/pingcap/tidb/issues/18117 can replace this issue, let's close this one.
