### ISSUE TITLE
Support all Binlog features in CDC

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18100]
### Description
Support all Binlog features in CDC

### Category
Feature

### Value
Compatible with the original binlog function to improve usability

**Comment by IANTHEREAL** [comment]
this issue is too simple,  and duplicate with https://github.com/pingcap/ticdc/issues/690, I will close it firstly, and if https://github.com/pingcap/ticdc/issues/690 doesn't meet your request, then you can add more description and reopen it
