### ISSUE TITLE
Make TestRepairTable pass normally

### ISSUE THREAD

**Issue by songyzh** [pingcap/tidb#18135]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Uncomment TODO lines in TestRepairTable, this test will be failed after the [#18003](https://github.com/pingcap/tidb/pull/18003).

### 2. What did you expect to see? (Required)

Pass this test.

### 3. What did you see instead (Required)

This test will be failed.

### 4. Affected version (Required)

After merge [#18003](https://github.com/pingcap/tidb/pull/18003).

**Comment by zimulala** [comment]
PTAL @AilinKid
