### ISSUE TITLE
If TiDB could support partition table use  index join 

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#18179]
## Feature Request
If TiDB could support partition table use index join

**Is your feature request related to a problem? Please describe:**

please check AskTUG https://asktug.com/t/topic/35538 

![image](https://user-images.githubusercontent.com/55389305/85354864-0bdf3a00-b53e-11ea-97c9-510f509eda5c.png)

![image](https://user-images.githubusercontent.com/55389305/85354832-fe29b480-b53d-11ea-8a49-ecc0bd883196.png)

customer want use index join improve sql performance.

**Describe the feature you'd like:**

please help support partition table could use index join

**Describe alternatives you've considered:**

use index join could improve sql performance.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
duplicated with https://github.com/pingcap/tidb/issues/15612
