### ISSUE TITLE
Adding placement rules for a table through DDL

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#18200]
### Background

It's a part of project "Placement rules in SQL".

Adding a placement rule for a table is implemented in `ADD PLACEMENT` clause:

```sql
ALTER TABLE table_name
	ADD PLACEMENT LABEL=label ROLE=role COUNT=count,
        ADD PLACEMENT LABEL=label ROLE=role COUNT=count,
	...
```

`LABEL`, `ROLE` and `COUNT` correspond to `label_constraints`, `role` and `count` in placement rules in PD.

### Tasks

- Support `ADD PLACEMENT` clause in parser 
- Validate the SQL
- Construct a placement rule based on the SQL
- Notify PD to add the placement rule

### Notice

- Only unpartitioned table needs to be considered now.
- As it's complicated, each task above should be solved in at least one PR.

**Comment by morgo** [comment]
Superceded by https://github.com/pingcap/tidb/issues/26581 and https://github.com/pingcap/tidb/issues/26580
