### ISSUE TITLE
Altering placement rules for a table through DDL

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#18201]
### Background

It's a part of project "Placement rules in SQL". It should accomplished after adding placement rules (https://github.com/pingcap/tidb/issues/18200).

Altering a placement rule for a table is implemented in `ALTER PLACEMENT` clause:

```sql
ALTER TABLE table_name
	ALTER PLACEMENT LABEL=label ROLE=role COUNT=count,
        ALTER PLACEMENT LABEL=label ROLE=role COUNT=count,
	...
```

`LABEL`, `ROLE` and `COUNT` correspond to `label_constraints`, `role` and `count` in placement rules in PD.

### Tasks

- Support `ALTER PLACEMENT` clause in parser 
- Validate the SQL
- Construct a placement rule based on the SQL
- Notify PD to alter the placement rule

**Comment by morgo** [comment]
Superceded by https://github.com/pingcap/tidb/issues/26581 and https://github.com/pingcap/tidb/issues/26580
