### ISSUE TITLE
suggestion: document minimum number of servers

### ISSUE THREAD

**Issue by jojo05** [pingcap/tidb#1823]
Can you document/define the most basic configurations, i.e. with 2, 3 or 4 servers?

Also, will you support rpi3 ARM64 nodes?

rpi3 + 1TB disk could be great for additional nodes

http://wdlabs.wd.com/products/wd-pidrive-1tb-kit/

**Comment by ngaut** [comment]
Thanks for your report. @jojo05 
We will support rpi3 ARM64 nodes, and we need some help to test rpi3.

The minimum setup should be at lease 3 servers since we should keep 3 replicas.

**Comment by shenli** [comment]
@jojo05 Hope this document will be helpful. https://github.com/pingcap/docs/blob/master/op-guide/overview.md
