### ISSUE TITLE
Support Changing Column Type in the TiFlash Side

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18261]
### Description

Support changing column types.

### Category

Feature

### Value

* Changing column type is a basic function of the database, many inconveniences are brought to our users and DBAs from TiDB without full support.
* The user experience of syncing data from MySQL to TiDB with DM is usually very poor, lot's of column type changing DDL statements needed to be specifically handled.

**Comment by zimulala** [comment]
Done. Related issues: https://github.com/pingcap/tics/issues?q=is%3Aissue+%22Column+Type+Change%22+is%3Aclosed+
