### ISSUE TITLE
Copr-test failed for randgen-topn.

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#18287]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/6029/pipeline/

**Comment by SunRunAway** [comment]
Lack of information, maybe duplicates of #17351, closing it.
