### ISSUE TITLE
Improve ExtractEqAndInCondition to handle DNF filters

### ISSUE THREAD

**Issue by eurekaka** [pingcap/tidb#18289]
## Development Task

`a = 1 and (b = 1 or b = 2) and c = 1` equals to `a = 1 and b in (1, 2) and c = 1`, handle DNF in ExtractEqAndInCondition to utilize as many index columns as possible when matching a index.

**Comment by zz-jason** [comment]
can the method described above also solve this issue: https://github.com/pingcap/tidb/issues/18118?

**Comment by eurekaka** [comment]
Not really, that is a different issue, i.e, normalization of multi-arguments IN expression
