### ISSUE TITLE
Need the Introduction documentation of copr-cache

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#18299]

**Comment by breeswish** [comment]
https://docs.pingcap.com/zh/tidb/v4.0/coprocessor-cache This one?

**Comment by SunRunAway** [comment]
Thanks. 
The documentation need to be updated after this epic is closed. https://github.com/pingcap/tidb/labels/epic%2Fcopr-cache

**Comment by SunRunAway** [comment]
@lzmhhh123 PTAL
