### ISSUE TITLE
how config multiple tables in syncer's configuration file to skip delete dmls?

### ISSUE THREAD

**Issue by ericgogo** [pingcap/tidb#18306]
## General Question

the document describe as below, but no multiple tables.

# skip-dmls 支持跳过 DML binlog events，type 字段的值可为：'insert'，'update' 和 'delete'
# 跳过 foo.bar 表的所有 delete 语句
# [[skip-dmls]]
# db-name = "foo"
# tbl-name = "bar"
# type = "delete"
#
# 跳过所有表的 delete 语句
# [[skip-dmls]]
# type = "delete"
#
# 跳过 foo.* 表的 delete 语句
# [[skip-dmls]]
# db-name = "foo"
# type = "delete"

**Comment by EricGogo** [comment]
anynone know how to configure multi-tables to skip the dmls statements？

**Comment by EricGogo** [comment]
upup

**Comment by jebter** [comment]
Recommend using cdc: https://docs.pingcap.com/tidb/stable/ticdc-filter.The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
