### ISSUE TITLE
consider index merge access path for CNF filters

### ISSUE THREAD

**Issue by eurekaka** [pingcap/tidb#18319]
## Development Task

Currently, IndexMerge only supports union operation on indexes, consider intersection strategy for indexes as well.

The benefit of intersection strategy is that, we can reduce the risk of wrong choice among several indexes, especially for a kind of cases like `select * from t where idx_1_col > 1 and idx_2_col > 1`.

This feature would enlarge search space of access paths, and it has risk of potential regression, i.e, a single index scan may be more efficient than an intersection between indexes, but planner chooses index merge due to wrong row count estimation.

**Comment by SunRunAway** [comment]
Is it a duplicate of https://github.com/pingcap/tidb/issues/15759?

**Comment by eurekaka** [comment]
Yes.
