### ISSUE TITLE
how to install tidb via tar.gz file

### ISSUE THREAD

**Issue by l1t1** [pingcap/tidb#18324]
## General Question
I downlod a big gz file( https://download.pingcap.org/tidb-community-server-v4.0.1-linux-amd64.tar.gz) from https://pingcap.com/download-cn/community/,
but I cannot found the guide of **use it** in the link of that page bottom (https://docs.pingcap.com/zh/tidb/v4.0/production-deployment-using-tiup)

**Comment by l1t1** [comment]
unzip the gz file,
```
tar -xf ../tidb-community-server-v4.0.1-linux-amd64.tar.gz
ln -s /tmp/tidb/tidb-community-server-v4.0.1-linux-amd64  /usr/local/tidb
```
i got a sh file and many json files and gz files.
and I run the ./local_install.sh
it only  returns 
Set mirror to /usr/local/tidb success

**Comment by l1t1** [comment]
if i want install all components and start the sever, which label should i use?

**Comment by jebter** [comment]
Recommend using tiup: https://docs.pingcap.com/tidb/stable/tiup-overview.The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
