### ISSUE TITLE
Consider service safepoint when checking transaction visibility

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#18358]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Make a table huge enough that its checksum time can exceed 10 mins.
2. Set GC execution period to 10 mins.
3. `BACKUP` this table.

### 2. What did you expect to see? (Required)
Backup success since BR sets service safepoint.

### 3. What did you see instead (Required)
Backup failed with `[tikv:9006]GC life time is shorter than transaction duration` when doing checksum.

### 4. Affected version (Required)
v4.0.1

### 5. Root Cause Analysis
We issue this error here:
https://github.com/pingcap/tidb/blob/180c02127105bed73712050594da6ead4d70a85f/store/tikv/kv.go#L186-L190
However, the `cachedSafePoint` is gotten by this key:
https://github.com/pingcap/tidb/blob/180c02127105bed73712050594da6ead4d70a85f/store/tikv/safepoint.go#L33-L36
which (seems) won't consider the service checkpoint.

**Comment by MyonKeminta** [comment]
Service safe point is considered here: 
https://github.com/pingcap/tidb/blob/43d7b0e11b4141326bf14fd41326785011c87e78/store/tikv/gcworker/gc_worker.go#L492
which happens in prepare phase of GC, and the saved_safe_point is updated here:
https://github.com/pingcap/tidb/blob/43d7b0e11b4141326bf14fd41326785011c87e78/store/tikv/gcworker/gc_worker.go#L554
where prepare has finished.

So service safe point should be considered. I think there are other reason that leads you to this problem.

**Comment by MyonKeminta** [comment]
I think BR didn't set service safepoint properly during checksum, so GC safe point goes exceed the ts that BR uses. Please confirm whether BR has this problem.

**Comment by YuJuncen** [comment]
OK, I think probably it's because that we set a 5mins service safepoint and don't reset it during checksumming... let me close this issue before we find something new...
