### ISSUE TITLE
Support commit pessimistic transaction with modify/change column type concurrent DDLs

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#18356]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, the two-phase commit will fail if there is a concurrent DDL on related tables before commit.

**Describe the feature you'd like:**

Try to amend transaction memory buffer before committing for pessimistic transactions, if there are concurrent DDLs with drop index type.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

Subtask of https://github.com/pingcap/tidb/projects/50.

**Comment by scsldb** [comment]
@zz-jason This is a subtask of change column type?

**Comment by zz-jason** [comment]
@cfzjywxk Please describe more about this feature request. It's hard to tell what's the problem you wish to solve this issue. How it's related with other requests, etc.

**Comment by zz-jason** [comment]
It's a sub-task of https://github.com/pingcap/tidb/issues/18098. I'm going to move it out of the feature request.
