### ISSUE TITLE
Add more test cases

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#18357]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Add more test cases covering all state change for supported DDL types, it's important to ensure the data consistency.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

Subtask of https://github.com/pingcap/tidb/projects/50.

**Comment by zz-jason** [comment]
@cfzjywxk can we close this issue now since https://github.com/pingcap/tidb/projects/50 is finished?
