### ISSUE TITLE
ddl: misleading 'the index already exists' error message when creating an index

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#18363]
## Feature Request

**Is your feature request related to a problem? Please describe:**
When creating an existing index in TiDB that is already adding in the background. The error message is confusing:

Suppose we have a large table `t` in TiDB, for which `ADD INDEX` statement requires a noticeable time to finish it.
(In session 1):
```
mysql> ALTER TABLE t ADD INDEX a(...)
```
(In session 2):
```
(suppose the process id of session 1 is 22)
mysql> KILL TIDB 22;
```
Please notice that in TiDB, a DDL job is not canceled by closing the session the statement is running, the only way to cancel it is by `ADMIN CANCEL ...`. **Before the job is done**, trying to create an index with the same name leads to an error: 
(In session 2):
```
mysql> ALTER TABLE t ADD INDEX a(...)
ERROR 1061 (42000): index already exist a
```

**Describe the feature you'd like:**
The error message `index already exist a` is confusing for the customers don't know clearly the internal way DDL run in TiDB. It's better to offer a message that is more clear to notify that a 'background job' is trying to adding the same index.

**Teachability, Documentation, Adoption, Migration Strategy:**
In MySQL, when a long-running DDL job is killed because of the killed session, it is canceled: https://dev.mysql.com/doc/refman/8.0/en/kill.html:

> ALTER TABLE operations that make a table copy check the kill flag periodically for each few copied rows read from the original table. If the kill flag was set, the statement is aborted and the temporary table is deleted.

**Comment by zimulala** [comment]
I think it can check the index state in https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L4244  to handle it.
