### ISSUE TITLE
add an example supporting OPA based Authz

### ISSUE THREAD

**Issue by joe-getcouragenow** [pingcap/tidb#18371]
https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4

**Comment by SunRunAway** [comment]
@tennix Would you like to take a look?

**Comment by joe-getcouragenow** [comment]
Like this: https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4

**Comment by zz-jason** [comment]
@joe-getcouragenow It basically generates conditions in the `where` clause to limit access to databases, seems we don't need to do anything to this OPA based authorization?

**Comment by zz-jason** [comment]
I'm going to close this feature request, feel free to reopen it if more discussion is needed.
