### ISSUE TITLE
should we add tableInfo into ddl job?

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/tidb#1842]
I think we can add the associated tableInfo into dll job (addColumn,dropColumn,addIndex, dropIndex) before we place it into history ddl job queue.

The cause is  TiDB-Binlog need to compute the new schema base on ddl job.
I don't think it can guaranteed completely correct, so load from TiDB maybe is the best way.

@shenli @coocood @iamxy

**Comment by coocood** [comment]
Yes, add full TableInfo in ALTER TABLE DDL job doesn't add much cost.
When we need it, we can use it directly. Otherwise we have to a lot of computing to reconstruct it.

**Comment by shenli** [comment]
@zimulala PTAL

**Comment by iamxy** [comment]
Good point !!
So we can restore the schema state of any time point by the job list.

**Comment by GregoryIan** [comment]
I think I should add that we need tbInfo in CreateTable, AlterTable(Truncate Table), DBInfo in CreateDB.  
In conclusion, All operations that change tableinfo are required to carry tbInfo.
