### ISSUE TITLE
Modify the storage format of DDL jobs to support parallel DDL

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#18425]
### Background

It's a part of the issue "Support DDL parallel execution".
Currently, we use two queues to save the "add index" and other DDLs in storage. And we have two workers to handle these DDL jobs. 
Problems of current storage format:
* A current DDL job is stored by means of (special prefix), data key (encoded by meta key), and value. Therefore, for a certain queue (such as "add index" queue), write conflicts will occur when adding and deleting the DDL job.

### Two suggestions

- Store DDL job in an internal table 

- The queue storage mode will be modified. Meta key and data key will be directly changed into one key (stored in the mode of ` mDDLJobListKey`+`_jobID `). 

### Notice

- handling dependence jobs
- compatibility issues

**Comment by Defined2014** [comment]
Seems we already supported parallel DDL, so close this issue.
