### ISSUE TITLE
After drop table, metrics shows that scan command takes too much time

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#1845]
In most cases, only keys (or indexed columns) must be load for delete, using Scan is a waste.

Possible fix 1: Instead of using kv.scan, ddl worker use distSQL to load only keys and necessary columns.
Possible fix 2: Add a new kv command 'deleteRange', push it down to tikv.

**Comment by coocood** [comment]
I think we need a mutation coprocessor, which can be used to do many kind of mutation operations.

**Comment by disksing** [comment]
It turns out that using scan is not the main reason. We have fixed some other issues, now the performance improves a lot.
Refer: 
https://github.com/pingcap/tidb/pull/1888
https://github.com/pingcap/tidb/pull/1882
