### ISSUE TITLE
Planner: choose the indexScan rather than TableScan when the limited count cannot reach

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#18460]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `audio_info` (   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',    `status` int(11) NOT NULL DEFAULT '0' COMMENT 'status',   `url` varchar(255) NOT NULL DEFAULT '' COMMENT 'url',   PRIMARY KEY (`id`),    KEY `audio_info_status` (`status`) );

insert into audio_info values (1,1,'22'),(2,2,'1'),(3,3,'22'),(4,4,'1'),(5,5,'52'),(6,6, '62');

analyze table audio_info;


```
### 2. What did you expect to see? (Required)
use the index scan to avoid the full table scan.

### 3. What did you see instead (Required)
```
explain select * from audio_info where status = 4 limit 2;
+-------------------------------+---------+-----------+------------------+----------------------------------+
| id                            | estRows | task      | access object    | operator info                    |
+-------------------------------+---------+-----------+------------------+----------------------------------+
| Limit_8                       | 2.00    | root      |                  | offset:0, count:2                |
| └─TableReader_14              | 2.00    | root      |                  | data:Limit_13                    |
|   └─Limit_13                  | 2.00    | cop[tikv] |                  | offset:0, count:2                |
|     └─Selection_12            | 2.00    | cop[tikv] |                  | eq(test.audio_info.status, 4)    |
|       └─TableRangeScan_11     | 12.00   | cop[tikv] | table:audio_info | range:[0,+inf], keep order:false |
+-------------------------------+---------+-----------+------------------+----------------------------------+
5 rows in set (0.00 sec)
```
### 4. Affected version (Required)
mysql> select version();
+------------------------------------------+
| version()                                |
+------------------------------------------+
| 5.7.25-TiDB-v4.0.0-beta.2-737-g5f983b860 |
+------------------------------------------+
1 row in set (0.00 sec)

### 5. Root Cause Analysis
correcting the cost of full table scan is not right.

**Comment by nullnotnil** [comment]
There is another case (a bit different I realize) where table scan can be faster because it improves parallelism: https://github.com/pingcap/tidb/issues/6497

(I state this not fully understanding the consequences of this change, but hoping there are no regressions added.)

**Comment by fzhedu** [comment]
It is esstially caused by the estimation from CMsketch.
