### ISSUE TITLE
Fix the inappropriate heuristic method to estimate the equal condition selectivity

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#18461]
## Development Task
Now in the planner, if the estimated value is out of range, which means we cannot find it in the `CMSketch`, a heuristic method is used, which is `selectivity = 1 / NDV * (ModifyRows / TotalRows)`.
Compared with Oracle's method `selectivity = 1 / NDV`, our method may result in an inappropriate low selectivity, especially when there are a few rows modified, for example, if one row is modified, it would be `1 / NDV * (1 / TotalRows)`.

It's better to use `1 / NDV` or `1 / NDV * (1 - ModifyRows / TotalRows)`.

**Comment by qw4990** [comment]
Here is PG's method in this case: `sel = (1 - nullFrac - mcvSumFrac) / othersNDV`.
Compared with simply setting the `sel` to `1 / NDV`, minus `mcvSumFrac` from it can avoid wrong selectivities caused by small NDV.
Since TiDB doesn't maintain an MCV list, and for simplicity, we can use the magic number `outOfRangeBetweenRate` which already exists in TiDB:
```
if ndv < outOfRangeBetweenRage { ndv = outOfRangeBetweenRage }
sel := 1 / ndv
```

**Comment by lmduean** [comment]
> Here is PG's method in this case: `sel = (1 - nullFrac - mcvSumFrac) / othersNDV`. Compared with simply setting the `sel` to `1 / NDV`, minus `mcvSumFrac` from it can avoid wrong selectivities caused by small NDV. Since TiDB doesn't maintain an MCV list, and for simplicity, we can use the magic number `outOfRangeBetweenRate` which already exists in TiDB:
> 
> ```
> if ndv < outOfRangeBetweenRage { ndv = outOfRangeBetweenRage }
> sel := 1 / ndv
> ```

Why don't we directly use 1/NDV, just like Oracle does?
use this doesn't make sense, for example:

//disable auto analyze
create table t1(type int, key type_idx(type));
insert into t1 values (1); // repeat 1024
analyze table t1;
insert into t1 values (2); // repeat 1024

explain select count(*) from t1 where type=2;
+-----------------------------+---------+-----------+--------------------------------+---------------------------------+
| id                          | estRows | task      | access object                  | operator info                   |
+-----------------------------+---------+-----------+--------------------------------+---------------------------------+
| StreamAgg_17                | 1.00    | root      |                                | funcs:count(Column#5)->Column#3 |
| └─IndexReader_18            | 1.00    | root      |                                | index:StreamAgg_9               |
|   └─StreamAgg_9             | 1.00    | cop[tikv] |                                | funcs:count(1)->Column#5        |
|     └─IndexRangeScan_16     | 20.48   | cop[tikv] | table:t1, index:type_idx(type) | range:[2,2], keep order:false   |
+-----------------------------+---------+-----------+--------------------------------+---------------------------------+
4 rows in set (0.00 sec)

without this adjust:
+-----------------------------+---------+-----------+--------------------------------+---------------------------------+
| id                          | estRows | task      | access object                  | operator info                   |
+-----------------------------+---------+-----------+--------------------------------+---------------------------------+
| StreamAgg_17                | 1.00    | root      |                                | funcs:count(Column#5)->Column#3 |
| └─IndexReader_18            | 1.00    | root      |                                | index:StreamAgg_9               |
|   └─StreamAgg_9             | 1.00    | cop[tikv] |                                | funcs:count(1)->Column#5        |
|     └─IndexRangeScan_16     | 2048.00 | cop[tikv] | table:t1, index:type_idx(type) | range:[2,2], keep order:false   |
+-----------------------------+---------+-----------+--------------------------------+---------------------------------+
4 rows in set (0.00 sec)

I think 1/NDV is better
