### ISSUE TITLE
reduce Txn Committer memory footprint

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#1847]
Txn Committer consume too much memory.

transaction data is batch written to memdb before send to tikv. 
memdb data can't be send directly, it must be marshaled to kv protobuf, so we need memdb x2 sized memory.

to make the most of golang, txn committer use multi goroutines for sending data, much of them would be blocked at network, their referenced memory can't be free.

what is worse, transaction may conflict and abort, but [those worker goroutines still sending data](https://github.com/pingcap/tidb/blob/f4c5511640ce891976b30de59f6c4a6eb024861c/store/tikv/txn_committer.go#L148) and don't release memory.

when I'm looking into this https://github.com/pingcap/tidb/issues/1791 , I find it's easy for txn committer to occupy 800M~1G+ , and for a long time. 

although not leak, it's really bad for TiDB to use so much memory.

**Comment by shenli** [comment]
@tiancaiamao Any solution for this issue?
