### ISSUE TITLE
DDL: admin show next_row_id return empty set

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#18532]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. set @@sql_mode="";
2. create table t(a int not null, time timestamp not null default '0000-00-00 00:00:00', primary key (a));
3.  admin show t next_row_id;

### 2. What did you expect to see? (Required)
something like that:
+---------+------------+-------------+--------------------+
| DB_NAME | TABLE_NAME | COLUMN_NAME | NEXT_GLOBAL_ROW_ID |
+---------+------------+-------------+--------------------+
| test    | t          | _tidb_rowid |                  1 |
+---------+------------+-------------+--------------------+

### 3. What did you see instead (Required)
empty set

### 4. Affected version (Required)

TiDB master branch(v4.0.2 has no such problem)

**Comment by tangenta** [comment]
It is an expected behavior after https://github.com/pingcap/tidb/pull/18326. I didn't realize this before. Sorry :)
