### ISSUE TITLE
Re-implement partition pruning module 

### ISSUE THREAD

**Issue by imtbkcat** [pingcap/tidb#18548]
## Development Task
Current partition pruning module can not purning condition like `or`, `a = b and b = 1`, `in`.
Re-implement partition pruning module have these two target：

- Support more condition in partition pruning
- Keep performance of partition pruning.

design doc: https://docs.google.com/document/d/1odyY2EtIMGN-Q5axEU9EmsoKOyXFDYe31KDmvzniPxE/edit

**Comment by qw4990** [comment]
This issue is duplicated with https://github.com/pingcap/tidb/issues/18548, so I close it now.
