### ISSUE TITLE
Implement `PartitionTableReader` for query on partition table

### ISSUE THREAD

**Issue by imtbkcat** [pingcap/tidb#18546]
## Feature Request
**Is your feature request related to a problem? Please describe:**

Originally, query on partition table would be deal in plan building phase. This bring some performance issues like:

- Plan of partition table can not be cached in prepare plan cache.
- Some condition relay on runtime result can not be pruned.

**Describe the feature you'd like:**

- Create a `PartitionTableReader` to replace `Union Partition`
- Build range and pruning partition
- build key range 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

https://docs.google.com/document/d/1pwQ8nzROQcV956jqcmbcikMPveQQWfsUZq2Zd7R8xQM/edit#heading=h.efxhx09hxyyo

**Comment by zz-jason** [comment]
it's more like a performance enhancement than a feature request, moved it out of the kanban.
