### ISSUE TITLE
Implement index choose and statistic information for `PartitionTableReader` 

### ISSUE THREAD

**Issue by imtbkcat** [pingcap/tidb#18551]
## Development Task
Currently, index choose in partition table will be distributed into each partition after building logical plan.
In order to implement `PartitionTableReader`,  index choose phase will be done before build physical plan. 
For `PartitionTableReader`, statistic information will be collected globally, not in each partition.

target:
- `PartitionTableReader` could choose index according to global statistic information.

design doc: 
https://docs.google.com/document/d/1pwQ8nzROQcV956jqcmbcikMPveQQWfsUZq2Zd7R8xQM/edit#

**Comment by qw4990** [comment]
Close since it is duplicated with https://github.com/pingcap/tidb/issues/24150.
