### ISSUE TITLE
Can materialized views and "select into from" be supported?

### ISSUE THREAD

**Issue by DevilMayCrySamsara** [pingcap/tidb#18560]
## General Question
Can materialized views and "select into from" be supported?

**Comment by nullnotnil** [comment]
`SELECT INTO OUTFILE` support was added in TiDB 4.0 :-) Is this what you had in mind, or something else?

Support for materialized views can be tracked in https://github.com/pingcap/tidb/issues/18023

**Comment by nullnotnil** [comment]
I am going to close this issue, as support for materialized views will be tracked in #18023.

Please feel free to re-open if you have additional questions. Thanks!
