### ISSUE TITLE
Documentation for users about Joins

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#18576]
## Development Task

here's only one place to describe the join algorithm,
zh: https://docs.pingcap.com/zh/tidb/stable/query-execution-plan#%E5%A6%82%E4%BD%95%E9%98%85%E8%AF%BB-join-%E7%9A%84%E6%89%A7%E8%A1%8C%E8%AE%A1%E5%88%92
en: https://docs.pingcap.com/tidb/stable/query-execution-plan#join

I propose having an individual page to talk about Joins under `Performance Tuning - SQL Optimization` section,
1. talk about different join algorithms (Merge Join, Hash Join, Index Join)
2. talk about how users can tune join algorithms with hints
3. What situation is good for Hash Join, and what is good for Index Join
4. How we tune Hash Join into Index Join by adding a suitable index.

reference: https://docs.microsoft.com/en-us/sql/relational-databases/performance/joins?view=sql-server-ver15

cc @winoros  @nullnotnil @zz-jason

**Comment by zz-jason** [comment]
Great! Let's do it ASAP

**Comment by nullnotnil** [comment]
It should show hash joins, with examples of on-disk, in memory, and how to understand collision statistics.
