### ISSUE TITLE
Support to modify the value of foreign_key_checks system variable is ON

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18641]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Support to modify the value of foreign_key_checks system variable is ON, the current value can not be modified to OFF can not adapt to java flyway

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nullnotnil** [comment]
May I suggest implementing it with similar semantics to https://docs.pingcap.com/tidb/stable/system-variables#tidb_skip_isolation_level_check ?

There are risks to allowing it by default - in that applications (and users) may believe foreign keys are enforced by DML. You can not rely on them reading the manual to find out they are not.

**Comment by nullnotnil** [comment]
If the motivation is for flyway compatibility, there is an alternative fix which is safer. See https://github.com/pingcap/tidb/issues/15131#issuecomment-611311153 for an explanation.

**Comment by YangKeao** [comment]
Currently, the `foreign_key_checks` is supported, and TiDB also supports foreign key function (though it's an experimental function). I'll close this issue.
