### ISSUE TITLE
Support `transfer-region` in `pd-ctl` when placement rule enabled

### ISSUE THREAD

**Issue by scsldb** [pingcap/tidb#18643]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When the placement rules function is enabled, after execution, ‘operator add transfer-region 126977 1 4 5’, the system outputs the error message "Failed! [500] "transfer region is not supported when placement rules enabled"

**Describe the feature you'd like:**

1. Provide related solutions to ensure compatibility between features.
2. Support the execution of transfer-region scheduling according to different roles

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nolouch** [comment]
there is the same issue: https://github.com/pingcap/pd/issues/2533

**Comment by Yisaer** [comment]
closed in https://github.com/tikv/pd/pull/3047

**Comment by Yisaer** [comment]
@scsldb can we close the issue?

**Comment by Yisaer** [comment]
Close this as solved.
