### ISSUE TITLE
keep backward compatibility when making an experimental feature generally available

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#18661]
## Motivation & Background

From @kolbe:

> Customers expect configuration options to be stable. Any customers using --config-strict and experimental/allow-auto-random will find that their clusters refuse to start after doing a minor version upgrade.

See the discussion in https://github.com/pingcap/tidb/issues/17882#issuecomment-658923959 for details.

## Goals

We should keep backward compatibility when making an experimental feature generally available. For example, don't remove an existing config item.

**Comment by nullnotnil** [comment]
I chatted to @shuke987 and devs and QA will add this check to design review. Because the original issue has since been fixed, I am going to go ahead and close this issue. Thanks!
