### ISSUE TITLE
DDL owner eats too much cpu if lease is 1ms

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1869]
Currently, the lease of DDL owner is (4 * lease), when i want to import data, i set lease to 1ms. It eats too much CPU even i didn't do anything.

We may need to set Max(3s, lease) as the lease of DDL owner.

**Comment by shenli** [comment]
@zimulala Please take a look at this issue.

**Comment by zimulala** [comment]
I know it and I will solve it. @shenli
