### ISSUE TITLE
support `super_read_only` global variable

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#18733]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This issue is created based on https://github.com/pingcap/tidb/issues/18426. Let's discuss the `super_read_only` variable here. The problem is the same as https://github.com/pingcap/tidb/issues/18426:
> Today, there's no easy way to make a cluster read-only. This could be useful in migration situations, and in situations where TiDB-Binlog or TiCDC is used to sync an upstream TiDB cluster to a downstream TiDB cluster (that may require additional support in the privilege system).

`super_read_only` is more strict than `read_only`: If `super_read_only` is enabled, the server prohibits client updates, even from users who have the `SUPER` privilege.

**Describe the feature you'd like:**

From MySQL document about [Server System Variables](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html):

> - If `super_read_only` is enabled, the server prohibits client updates, even from users who have the `SUPER` privilege.
> - Setting `super_read_only` to `ON` implicitly forces `read_only` to `ON`.
> - Setting `read_only` to `OFF` implicitly forces `super_read_only` to `OFF`.

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by jebter** [comment]
The tidb_super_read_only variable has been implemented:https://docs.pingcap.com/tidb/stable/system-variables#tidb_super_read_only-new-in-v531.I will close this issue. If there are any updates, you can reopen it.
