### ISSUE TITLE
Add a documentation page related to tidb-specific built-in function

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#18746]
## Development Task

- [x] tidb_version
- [x] tidb_is_ddl_owner
- [x] tidb_decode_key
- [x] tidb_decode_plan
- [x] tidb_parse_tso

All the functions above have been documented in https://github.com/pingcap/docs/pull/5699.

**Comment by SunRunAway** [comment]
@taozhengcn

**Comment by nullnotnil** [comment]
This sounds like a great thing to add. May I recommend adding it under `Functions and Operators`? i.e. https://docs.pingcap.com/tidb/stable/functions-and-operators-overview

**Comment by dveeden** [comment]
With https://docs.pingcap.com/tidb/stable/tidb-functions being there, it looks to me that we can close this?
