### ISSUE TITLE
Improve selectivity computing for DNF filters

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#18740]
## Feature Request

**Is your feature request related to a problem? Please describe:**
For now, TiDB can't handle DNF condition with multiple columns in selectivity calculation. E.g., in the query `select * from t where a > 1 or b = 1;`, currently it's impossible to cover the condition `a > 1 or b = 1` no matter what indices you have. We will simply use 0.8 as selectivity for this uncovered condition currently.

**Describe the feature you'd like:**
We can use the independence assumption to handle the condition above with stats on column a and column b respectively. `selectivity(a > 1 or b = 1)` can be calculated as `selectivity(a > 1) + selectivity(b = 1) - selectivity(a > 1) * selectivity(b = 1)`.

More generaly, cases like `... and (a > 1 or b = 1) and ...` and `... and (a > 1 or b = 1 or c = 1 or d = 1) and ...` need be handled.

**Comment by zz-jason** [comment]
@time-and-fate It's more like an internal improvement, not a feature request.

**Comment by time-and-fate** [comment]
> @time-and-fate It's more like an internal improvement, not a feature request.

Oh...I didn't notice that Development Task template. I'll pay attention next time.
