### ISSUE TITLE
Separate general log from tidb.log

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tidb#18771]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

TiDB will write general log in tidb.log when enabled general log. Suggest to separate general log from `tidb.log`. Because it's not easy to analysis general log when there are lots of error log in `tidb.log`.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
MySQL supports [`--general_log_file`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_general_log_file) config to specify the log file of the general log:

> By default, the general query log is disabled. To specify the initial general query log state explicitly, use --general_log[={0|1}]. With no argument or an argument of 1, --general_log enables the log. With an argument of 0, this option disables the log. To specify a log file name, use --general_log_file=file_name. To specify the log destination, use the log_output system variable (as described in Section 5.4.1, “Selecting General Query Log and Slow Query Log Output Destinations”).

**Comment by zz-jason** [comment]
It also supports [`general_log_file`](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_general_log_file) to alter the log file dynamically.

**Comment by dragonly** [comment]
I am currently working on the general log performance optimization. I'll track this issue.

**Comment by Defined2014** [comment]
Already supported in v8.0.0, https://docs.pingcap.com/tidb/stable/tidb-configuration-file#general-log-file-new-in-v800. Close this issue.
