### ISSUE TITLE
should select count(1) from table group by column be ordered?

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#18782]
![批注 2020-07-24 230537](https://user-images.githubusercontent.com/20839912/88408014-8b924a00-ce05-11ea-8e6f-aa54affa208e.jpg)

seems `MySql` guarantee the order, I run many times, it always 6 3

**Comment by nullnotnil** [comment]
MySQL historically default-ordered results in the same order as `GROUP BY`, but this was a deprecated behavior and went away in MySQL 8.0.

Default ordering the results limits what optimizations can be applied during query execution. It is better to require the user to specify an order if they require one.
