### ISSUE TITLE
add statistics of locked tables

### ISSUE THREAD

**Issue by jacktd9** [pingcap/tidb#18799]
单表频繁被更新，统计信息收集不及时或采集有偏差会导致执行计划变差，如果提供锁定单表统计信息的功能，预期会比较好。

**Comment by zz-jason** [comment]
> 锁定单表统计信息的功能

Do you mean to use the out-dated statistics instead of `pseudo`? In TiDB, you can enlarge the `pseudo-estimate-ratio` config and disable query feedback by setting the `feedback-probability` config to `0.0`. Would that be a workaround for the application?

Are there other databases that provide a similar feature? It would be great that you can provide some references to help us improve the statistics management mechanism.

**Comment by jacktd9** [comment]
是一个建议，在确认当前的统计信息是合适的，通过锁定统计信息禁止采样，稳定执行计划。
oracle：
EXECUTE DBMS_STATS.LOCK_TABLE_STATS ('owner name', 'table name');

**Comment by zz-jason** [comment]
There are 3 procedures in Oracle to lock/unlock stats:

- [LOCK_PARTITION_STATS](https://docs.oracle.com/database/121/ARPLS/d_stats.htm#BABFJDFA) and [UNLOCK_PARTITION_STATS]()
- [LOCK_TABLE_STATS](https://docs.oracle.com/database/121/ARPLS/d_stats.htm#i1043993) and [UNLOCK_TABLE_STATS](https://docs.oracle.com/database/121/ARPLS/d_stats.htm#i1040393)
- [LOCK_SCHEMA_STATS](https://docs.oracle.com/database/121/ARPLS/d_stats.htm#i1043184) and [UNLOCK_SCHEMA_STATS](https://docs.oracle.com/database/121/ARPLS/d_stats.htm#i1043314)

Take the behavior of `LOCK_TABLE_STATS` as an example:

> - To invoke this procedure you must be owner of the table, or you need the ANALYZE ANY privilege. For objects owned by SYS, you need to be either the owner of the table, or you need the ANALYZE ANY DICTIONARY privilege or the SYSDBA privilege.
> - When statistics on a table are locked, all the statistics depending on the table, including table statistics, column statistics, histograms and statistics on all dependent indexes, are considered to be locked.
> - The SET_\*, DELETE_\*, IMPORT_\*, GATHER_\* procedures that modify statistics in the dictionary of an individual table, index or column will raise an error if statistics of the object is locked.
> - Procedures that operates on multiple objects (such as GATHER_SCHEMA_STATS) will skip modifying the statistics of an object if it is locked. Many procedures have force argument to override the lock.
> - This procedure either freezes the current set of the statistics or keeps the statistics empty (uncollected) to use dynamic statistics.
> - The locked or unlocked state is not exported along with the table statistics when using EXPORT_\*_STATS procedures.
> - Neither the UNLOCK_SCHEMA_STATS Procedure nor the UNLOCK_TABLE_STATS Procedure is designed to unlock statistics of corresponding partitions. When you invoke the LOCK_TABLE_STATS Procedure, it sets the statistics lock bit at the table level. In that case, you cannot gather statistics on dependent objects such as partitions and indexes. By the same token, if table statistics are locked, the dependents are locked and you do not need to explicitly invoke the LOCK_PARTITION_STATS Procedure.

**Comment by hawkingrei** [comment]
It has been implemented. Here is [documents](https://docs.pingcap.com/tidb/dev/sql-statement-lock-tables-and-unlock-tables).
