### ISSUE TITLE
ddl: support dropping a column with single-value indices

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#18812]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Support dropping a column with single-value indices. For now, the `ALTER TABLE ... DROP COLUMN` statement returns an error when dropping a column that is covered with index:

```
tidb> create table t(a int, b int, index idx_b(b));
Query OK, 0 rows affected (0.01 sec)

tidb> alter table t drop column b;
ERROR 8200 (HY000): can't drop column b with index covered now
```

**Describe the feature you'd like:**
See #3364 for the full feature requests.

**Describe alternatives you've considered:**
Manually, the `ALTER TABLE ... DROP COLUMN` in TiDB can be archived by 2 separate steps:
1. Drop all indices that cover the column to be dropped.
2. Drop the column without any index.

However, for some third-party frameworks that relies on dropping columns directly, workarounds have to be done for this limitation. This can be disappointing.

**Teachability, Documentation, Adoption, Migration Strategy:**
Compared with #3364, which is the full support for `ALTER TABLE ... DROP COLUMN`, this task is relatively easy. We can achieve by combining the current codes of `ALTER TABLE ... DROP COLUMN` and `ALTER TABLE ... DROP INDEX`. More help is available by referring:

* [The internal algorithm of TiDB online DDL](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md), more specifically [AddColumn](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md#add-column-operation) action and [AddIndex](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md#add-index-operation) action.
* The key schema state change codes:
  * [onDropColumns()](https://github.com/pingcap/tidb/blob/56fd348d20cbc1983fa5afa88a62192cc01d59fa/ddl/column.go#L383)
  * [onDropIndex()](https://github.com/pingcap/tidb/blob/56fd348d20cbc1983fa5afa88a62192cc01d59fa/ddl/index.go#L586)
  * [applyDiff()](https://github.com/pingcap/tidb/blob/56fd348d20cbc1983fa5afa88a62192cc01d59fa/infoschema/builder.go#L41), which updates the information schema served as a schema cache in TiDB server.
* The related PR that supports atomical multiple schema objects change: #15540

Here are some major code changes that may be helpful:
1. Update function [isDroppableColumn](https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L4663) by removing the restriction of dropping column/columns that are covered by single-value indicies

2. Update function [onDropColumn](https://github.com/pingcap/tidb/blob/1e7454c81d1f4fae464e835d1a4023a911cfa87b/ddl/column.go#L383) and [onDropColumns](https://github.com/pingcap/tidb/blob/1e7454c81d1f4fae464e835d1a4023a911cfa87b/ddl/column.go#L383)(maybe they can/should be combined together): check if they're droppable and retrieve all the single-value indices that cover the columns, and change the state of indicies with the columns(`StatePublic` -> `StateWriteOnly` -> `StateDeleteOnly` -> `StateDeleteReorgnization` -> `StateNone`). It would be much better if we can reuse the codes in [onDropIndex](https://github.com/pingcap/tidb/blob/1e7454c81d1f4fae464e835d1a4023a911cfa87b/ddl/index.go#L586) by some code refactorings.

3. Update function [insertJobIntoDeleteRangeTable](https://github.com/pingcap/tidb/blob/1e7454c81d1f4fae464e835d1a4023a911cfa87b/ddl/delete_range.go#L248) to add the range information for dropped columns along with all the indicies.

4. May need to update [ApplyDiff](https://github.com/pingcap/tidb/blob/1e7454c81d1f4fae464e835d1a4023a911cfa87b/infoschema/builder.go#L41). It is possible that this function works fine without modification because the state of column/index has been updated together with the new `TableInfo`. However, it is worth checking this function still.

5. Add unit tests/integration tests. It should be aware that, for a specific column, the related index/indices can be changed when the 'DropTable' DDL job is waiting in the DDL queue and it's worth making some tests for it.

6. Update `rollingbackDropColumn` function to process rollback.

**Comment by lance6716** [comment]
https://github.com/pingcap/dm/pull/801

DM has patch this some days ago, FYR

**Comment by blacktear23** [comment]
@bb7133 there has 6 item, we should edit rollingback.go: `rollingbackDropColumn` function to process rollback

**Comment by bb7133** [comment]
> @bb7133 there has 6 item, we should edit rollingback.go: `rollingbackDropColumn` function to process rollback

Thanks, updated.

I will close this feature since #18852 is merged.

**Comment by zz-jason** [comment]
can we backport it to release 4.0?

**Comment by bb7133** [comment]
> can we backport it to release 4.0?

Unless it is critical for some users, it's better to keep it in V5.0 since this feature is just a part of the multiple schema changes.
