### ISSUE TITLE
How to build TiDB?

### ISSUE THREAD

**Issue by sotex** [pingcap/tidb#1881]
1. What version of Go are you using (`go version`)?
   
   ```
   > go version
   go version go1.7.3 linux/amd64
   ```
2. What operating system and processor architecture are you using (`go env`)?
   
   ```
   > go env
   GOARCH="amd64"
   GOBIN=""
   GOEXE=""
   GOHOSTARCH="amd64"
   GOHOSTOS="linux"
   GOOS="linux"
   GOPATH="/home/o/dataBase/tidb"
   GORACE=""
   GOROOT="/usr/lib/go"
   GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
   CC="gcc"
   GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build937879331=/tmp/go-build -gno-record-gcc-switches"
   CXX="g++"
   CGO_ENABLED="1"
   ```
3. What did you do?
   
   Nothing, how to build TiDB is all I want to konw.
   For now, still no idea.
4. What did you expect to see?
   
   A brief instruction of how to build it.(For people who are less familiar with golang.)

**Comment by overvenus** [comment]
你好，

你可以用下面的命令来编译：
```sh
sudo apt-get install make
make build
```

编译完成的 tidb-server 在 bin 文件夹下。

**Comment by shenli** [comment]
@sotex You can get the compiled binaries here: https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md
