### ISSUE TITLE
TiDB supports read-only function

### ISSUE THREAD

**Issue by gejibin** [pingcap/tidb#18820]
Want TiDB to support  read-only function.

In public cloud environment, when disk usage rate reaches 75% or more, TiDB needs to be set to read-only mode.

**Comment by shenli** [comment]
@gejibin is this something that you are asking for? https://github.com/pingcap/tidb/issues/18426
We are working on the `read_only` feature.

**Comment by nullnotnil** [comment]
There is also a feature request to limit write requests when TiKV is near full: https://github.com/pingcap/tidb/issues/18007

Please let me know if your feature request is not covered by these two features (read only, and limit write requests near full). Thanks!

**Comment by gejibin** [comment]
when set to read-only mode， tidb can only read but not write，it‘s ok for us.
like mysql, set global read_only=1;

**Comment by nullnotnil** [comment]
Thanks @gejibin 

I am going to close this as a duplicate of https://github.com/pingcap/tidb/issues/18426 - please subscribe to this issue for updates. Thanks!
