### ISSUE TITLE
Emit better message for deprecated config options.

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#18838]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Today, a deprecated configuration option causes a message like this to be written to the error log:

`config file /etc/tidb/tidb.toml contained unknown configuration options: experimental.allow-auto-random`

**Describe the feature you'd like:**
The message for a deprecated option should be different than the message for a truly "unknown" configuration option. The message could say "deprecated" instead of "unknown".

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
@wangggong PTAL
