### ISSUE TITLE
BatchPointGet returns wrong results with condition `in (null)` in some cases

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#18843]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t ( id bigint(10) primary key, f varchar(191) default null, unique key `idx_f` (`f`));
insert into t values (1, "");
select * from t where f in (null);
```

### 2. What did you expect to see? (Required)
Return an empty set.

### 3. What did you see instead (Required)
```
mysql> select * from t where f in (null);
+----+------+
| id | f    |
+----+------+
|  1 |      |
+----+------+
1 row in set (0.00 sec)
```

### 4. Affected version (Required)

Master branch:
```
mysql> select version();
+------------------------------------------+
| version()                                |
+------------------------------------------+
| 5.7.25-TiDB-v4.0.0-beta.2-849-gac581ee01 |
+------------------------------------------+
1 row in set (0.00 sec)
```

### 5. Root Cause Analysis

`Datum.ToString()` returns "" if its type is `KindNull`, which conflicts with empty strings.

**Comment by qw4990** [comment]
This problem seems introduced by this PR(https://github.com/pingcap/tidb/pull/17894), PTAL @tiancaiamao

**Comment by zhouqiang-cl** [comment]
@Hexilee PTAL
