### ISSUE TITLE
Since CI tests take a long time, it is necessary to optimize CI to shorten the test time

### ISSUE THREAD

**Issue by liubo0127** [pingcap/tidb#18860]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. What did you expect to see? (Required)
CI tests should be completed within three minutes

### 2. What did you see instead (Required)
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_integration_common_test/
  > All tests take more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/
  > More than 95% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_sqllogic_test_2/
  > More than 90% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/
  > More than 65% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_common_test/
  > More than 40% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_integration_ddl_test/
  > More than 30% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_sqllogic_test_1/
  > More than 30% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_integration_copr_test/
  > More than 30% of the tests took more than three minutes
- https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_build/
  > More than 8% of the tests took more than three minutes

### 3. Affected version (Required)
master branch

**Comment by sykp241095** [comment]
https://internal.pingcap.net/idc-jenkins/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/16326/pipeline

Still costs more than 10mins.

**Comment by sykp241095** [comment]
Seems to be fixed.
