### ISSUE TITLE
Halt on select INFORMATION_SCHEMA table for normal user

### ISSUE THREAD

**Issue by nwind** [pingcap/tidb#18864]
### 1. Minimal reproduce step (Required)

1. create a new user，like `CREATE USER 'newuser'@'%' IDENTIFIED BY 'password';`
2. login use that user
3. `select * from INFORMATION_SCHEMA.COLUMNS limit 1`

### 2. What did you expect to see? (Required)

get table result

### 3. What did you see instead (Required)

nothing return, halt.

### 4. Affected version (Required)

v4.0.3

But works on v4.0.1

**Comment by wjhuang2016** [comment]
@nwind Thanks for your report.
Fixe PR: https://github.com/pingcap/tidb/pull/18854, will be work in v4.0.4.

**Comment by qw4990** [comment]
Close since it is fixed.
