### ISSUE TITLE
Support init_connect

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#18894]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We should support the `init_connect` option the same way it's supported in MySQL: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_init_connect

This would make it easier to cause clients to automatically set particular variables at connect time to work around TiDB-specific behavior or emulate some expected behavior in MySQL.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nullnotnil** [comment]
I think I can take a look.
