### ISSUE TITLE
Add a flag to print the version (Git Commit Hash) and timestamp (UTC Build Time)

### ISSUE THREAD

**Issue by Librazy** [pingcap/tidb#1890]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
N/A

2. What operating system and processor architecture are you using (`go env`)?
N/A

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

Try to figure out the pre-compiled binary's version and UTC Build Time without running it (or run it with -h --help -v --version that widely used in Linux to identify an binary's version)

4. What did you expect to see?

Run with some flag (typically -v or --version) will print the Git Commit Hash and UTC Build Time then exit.

5. What did you see instead?

Can only get the version and timestamp by running it (and it's hard to find out version&timestamp in a lot of logs).

And it's better to see an timestamp file in the pre-compiled binary (http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz).

**Comment by shenli** [comment]
@Librazy Good idea! Could you send us a PR?

**Comment by Librazy** [comment]
#1896 Here it is～
