### ISSUE TITLE
tidb is too low

### ISSUE THREAD

**Issue by zhangdan1** [pingcap/tidb#18905]
My TiDB Cluster is running slow,and I make a diagnosis.The following is Diagnosis Result of TiDB Cluster Diagnostics Report,Is there any good suggestion to improve performance?
min data-block-cache-hit rate of X.X.X.X:20180 tikv is too low
max duration of X.X.X.X:20180 tikv rocksdb-seek-duration is too slow
max duration of X.X.X.X:20180 tikv rocksdb-write-duration is too slow
max duration of X.X.X.X:20180 tikv scheduler-cmd-duration is too slow
max duration of X.X.X.X:10080 tidb tso-duration is too slow
min filter-block-cache-hit rate of X.X.X.X:20180 tikv is too low
min index-block-cache-hit rate of X.X.X.X:20180 tikv is too low

**Comment by nullnotnil** [comment]
@zhangdan1 can you provide some details about the setup of your cluster? Such as how many TiDB and TiKV servers, and what are the hardware specs.

**Comment by lance6716** [comment]
Hi @zhangdan1 ,  could you provide some information about your cluster? you could reference out doc here https://docs.pingcap.com/zh/tidb/stable/hardware-and-software-requirements

**Comment by zhangdan1** [comment]
Hi,
&nbsp; &nbsp;My TiDB Cluster Diagnostics Report is attached, which provides&nbsp;information about mysql cluster.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pingcap/tidb"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月3日(星期一) 中午11:39
收件人:&nbsp;"pingcap/tidb"<tidb@noreply.github.com&gt;;
抄送:&nbsp;"★◎☆"<2931516196@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pingcap/tidb] tidb is too low (#18905)





 
Hi @zhangdan1 ,  could you provide some information about your cluster? you could reference out doc here https://docs.pingcap.com/zh/tidb/stable/hardware-and-software-requirements

**Comment by lance6716** [comment]
> Hi, &nbsp; &nbsp;My TiDB Cluster Diagnostics Report is attached, which provides&nbsp;information about mysql cluster.
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "pingcap/tidb" <notifications@github.com&gt;; 发送时间:&nbsp;2020年8月3日(星期一) 中午11:39 收件人:&nbsp;"pingcap/tidb"<tidb@noreply.github.com&gt;; 抄送:&nbsp;"★◎☆"<2931516196@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [pingcap/tidb] tidb is too low (#18905) Hi @zhangdan1 , could you provide some information about your cluster? you could reference out doc here https://docs.pingcap.com/zh/tidb/stable/hardware-and-software-requirements — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

Hi, reply by email seems can't upload attachments to Github, please return to this issue https://github.com/pingcap/tidb/issues/18905 , or turn to our Chinese forum https://asktug.com/. Glad to help you

**Comment by zhangdan1** [comment]
My problem is resolved, thanks
