### ISSUE TITLE
The bug report template is not suitable to report bugs

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#18908]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Create a [bug issue](https://github.com/pingcap/tidb/issues/new?labels=type%2Fbug&template=bug-report.md)

### 2. What did you expect to see? (Required)

Ask users to fill some necessary fields

### 3. What did you see instead (Required)

Current bug report asks more than what users know.

For example, it asked for "4. Affected version (Required)". How would user know the affected version of the bug? User only know the version he is using.

It also contains a field called "5. Root Cause Analysis". This means that the user issue will be modified by PingCAP, which is generally not a good idea. The root cause of the issue is usually posted as a comment before the issue is closed. I have never seen any popular repository want to modify what user posts so frequently.

On the other hand, some fields I guess useful is missing, for example, the git hash of TiDB (via `select tidb_version()`), the version of TiKV, which deployment tool is used (tiup? tidb-operator?), etc.

**Comment by SunRunAway** [comment]
LGTM
cc @zz-jason

**Comment by nullnotnil** [comment]
LGTM too.

The version of tikv should be handled in https://github.com/pingcap/tidb/issues/14487
