### ISSUE TITLE
Data truncation: Invalid JSON text: "The document is empty." at position 0 in value for column column_name | quiljs contents

### ISSUE THREAD

**Issue by HimanshuChugh2** [pingcap/tidb#18922]
Hello,

I am using QuillJs wysiwyg editor, it uses json to represent the data which its editor contains.
i want to save its content in mysql database.
i am using Java Spring Boot as server side language.
(i am a beginner)
so i have JSONObject (org.json.JSONObject) in my entity class `private JSONObject data;` which will contain the data that quill's editor contain.
i am getting the editor's contents by javascript like this: 	`document.getElementById("datajso").value=  JSON.stringify(quill.getContents().ops);`

`datajso` is mapped to the ` JSONObject data` by using thymeleaf.

so when i take image from my pc storage and put it on my editor, quill converts the image to base64 code.
i am saving the base64 code to mysql.
i saved an image(which is in base64) of 1.08MB to the database, it gets saved in database as base64 code.
for this `JSONObject data` i have JSON type in MySql.

so i saved this 1.08MB image successfully, but when i tried with another image which is of 1.84MB. i get the below error

```
Failed to complete request: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement
2020-07-31 23:29:53.612 ERROR 92352 --- [nio-8080-exec-8] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.DataException: could not execute statement] with root cause

com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Invalid JSON text: "The document is empty." at position 0 in value for column 'create_content.data'.
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104) ~[mysql-connector-java-8.0.20.jar:8.0.20]

```

i have tried to use String, LONGTEXT instead of JSON,  type but i am not able to get rid of this error.
i need help.

i tried to copy the base64 text of that 1.86MB image(2mn+ characters) and tried to execute an insert query in mysql workbench, but there it gave me this error: 
please note that in the editor the data is not only images its text also.

`Error Code: 3140. Invalid JSON text: "Invalid encoding in string." at position 2726003 in value for column 'create_content.data'.
`

this is how my insert query looks like: 
		insert into korenani.create_content values(11,'[{"insert":{"image":"data:image/jpeg;base64,/9j/4QL+RXhpZgAASUkqAAgAAAANAAABBAABAAAAwA8AAAEBBAABAAAARAcAAA8BAgAI(more characters of this base64 code are there but not able to add the actual query)}

looks like github uses 65536 for one text area;
please help me get rid of this error.
if there is any other good approach to save QuillJs editor's data into database, please let me know.
This is my first "Post" request.

Any help would be appreciated.

Thank you in advance

**Comment by nullnotnil** [comment]
Hi @HimanshuChugh2 

I tried to reproduce with a testcase just in SQL. I can insert a 2MB+ document similiar to yours with no problems. It is possible that some part of your application is truncating the string, which is causing MySQL to error. Please try out my test-case, and confirm that it works for you, with your version of TiDB. If I am missing something, let me know. Thanks!

[issue18922.zip](https://github.com/pingcap/tidb/files/5009326/issue18922.zip)

**Comment by HimanshuChugh2** [comment]
Hey @nullnotnil,  

i tried it with your file, its working fine with your file, but why is it not working with the json i am giving it.
below is the same file you shared but with my json text
please take a look and tell me what i am missing.
i think the error is with these kind of brackets [], but please let me know how to make it right.
[Files.zip](https://github.com/pingcap/tidb/files/5010155/Files.zip)

 Thank you

**Comment by nullnotnil** [comment]
With the test case you provided, TiDB is responding the same as MySQL 5.7:

```sql
mysql [localhost:5731] {msandbox} (test) > insert into create_content values(11,'');
ERROR 3140 (22032): Invalid JSON text: "The document is empty." at position 0 in value for column 'create_content.data'.
```

I suspect what might be happening, is that when base64 encoding the string exceeds a certain size, your application then attempts to insert an empty string into a JSON column. This is considered invalid for a JSON column, as you must insert either `[]` or `{}` at a minimum:

```sql
mysql [localhost:5731] {msandbox} (test) > insert into create_content values(11,'{}');
Query OK, 1 row affected (0.01 sec)

mysql [localhost:5731] {msandbox} (test) > insert into create_content values(12,'[]');
Query OK, 1 row affected (0.01 sec)
```

**Comment by HimanshuChugh2** [comment]
`I suspect what might be happening, is that when base64 encoding the string exceeds a certain size, your application then attempts to insert an empty string into a JSON column. This is considered invalid for a JSON column, as you must insert either [] or {} at a minimum:`

yes this is whats happening, the data i am passing from my html to my controller is not being passed when the file size is around 1.5MB, i am using java spring boot, will you be able to help me with this ?

i cant thank u enough for helping me this much, really appreciate that.

**Comment by nullnotnil** [comment]
> yes this is whats happening, the data i am passing from my html to my controller is not being passed when the file size is around 1.5MB, i am using java spring boot, will you be able to help me with this ?

I'm sorry, I don't know java! With this error not TiDB specific, you could also try asking this on the MySQL Community Slack or StackOverflow.
