### ISSUE TITLE
Enable tidb_enable_collect_execution_info by default?

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#18937]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This is an issue to **discuss** whether `tidb_enable_collect_execution_info` shall be enabled by default.

**Describe the feature you'd like:**

`tidb_enable_collect_execution_info` is introduced in https://github.com/pingcap/tidb/pull/17573 , which can be pretty helpful to see what happens for a slow query.

By enabling it by default, the overall performance affection is 0.2% ~ 3%.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
> By enabling it by default, the overall performance affection is 0.2% ~ 3%.

It's better to clearly describe the performance impacts for several parts:
- the benchmark
- QPS impact
- CPU impact
- duration impact
- log size impact
- etc.

**Comment by breeswish** [comment]
@crazycs520 PTAL

**Comment by crazycs520** [comment]
Great, I will do a bench test later.

**Comment by breeswish** [comment]
Since this parameter is already enabled by default in v4.0.3, I'm going to close this issue.
