### ISSUE TITLE
support [SHOW MASTER STATUS]

### ISSUE THREAD

**Issue by GregoryIan** [pingcap/tidb#1893]
I think we can support `SHOW MASTER STATUS` in order to make TiDB more friendly to be synchronized.

Use scenario:
While we deploy TiDB-Binlog,  we can do like blew:
1. deploy pump and cistern component to persist Binlog.
2. use  [myDumper](https://github.com/maxbube/mydumper) to dump TiDB data, schema, meta to file at one time point
3. read metadata file to get dump point **max ts over all TiDBs**, then use the ts start drainer to sync binlog to target db.

[[myDumper](https://github.com/maxbube/mydumper)] How to dump data?
```
1. Connect db
2. FLUSH TABLES WITH READ LOCK
3. START TRANSACTION /!40108 WITH CONSISTENT SNAPSHOT
4. SHOW MASTER STATUS
5. Create child threads
       [child thread]
      1. Connect to db
      2. SET SESSION TRANSACTION ISOLATION LEVEL REPEATABLE
      3. START TRANSACTION /!40108 WITH CONSISTENT SNAPSHOT /
      4. Pop tasks from queue to execute
6. Push tasks to  queue
7. UNLOCK TABLES / FTWRL 
```

[`SHOW MASTER STATUS`]
```
+------------------+----------+--------------+------------------+-------------------+
| File             | Position | Binlog_Do_DB | Binlog_Ignore_DB  | Executed_Gtid_Set |
+------------------+----------+--------------+------------------+-------------------+
| mysql-bin.000002 |      120 |              |                  |                              |
+------------------+----------+--------------+------------------+-------------------+
```
 we can make the file to constant like `TiDB-Binlog`, and the Position to Ts

@shenli @coocood @iamxy

**Comment by iamxy** [comment]
The core problem is how to retrieve the position which is the latest written commitTS over all TiDBs. Where store this value ?

**Comment by GregoryIan** [comment]
It's hard to make TiDB support it, we will get the max ts from cistern or pump after master service stop for some time while we switch Master / Slave or others.
