### ISSUE TITLE
index Create method return value 

### ISSUE THREAD

**Issue by jzdxeb** [pingcap/tidb#18979]
## General Question
```go
// Create creates a new entry in the kvIndex data.
// If the index is unique and there is an existing entry with the same key,
// Create will return the existing entry's handle as the first return value, ErrKeyExists as the second return value.
func (c *index) Create(ctx sessionctx.Context, rm kv.RetrieverMutator, indexedValues []types.Datum, h int64,
	opts ...*table.CreateIdxOpt) (int64, error) {
	var opt *table.CreateIdxOpt
	if len(opts) > 0 {
		opt = opts[0]
	}
	if opt == nil {
		opt = &table.CreateIdxOpt{}
	}
	writeBufs := ctx.GetSessionVars().GetWriteStmtBufs()
	skipCheck := ctx.GetSessionVars().LightningMode || ctx.GetSessionVars().StmtCtx.BatchCheck
	key, distinct, err := c.GenIndexKey(ctx.GetSessionVars().StmtCtx, indexedValues, h, writeBufs.IndexKeyBuf)
	if err != nil {
		return 0, err
	}

	if opt.Untouched {
		txn, err1 := ctx.Txn(true)
		if err1 != nil {
			return 0, err1
		}
		// If the index kv was untouched(unchanged), and the key/value already exists in mem-buffer,
		// should not overwrite the key with un-commit flag.
		// So if the key exists, just do nothing and return.
		_, err = txn.GetMemBuffer().Get(key)
		if err == nil {
			return 0, nil
		}
	}

	// save the key buffer to reuse.
	writeBufs.IndexKeyBuf = key
	if !distinct {
		// non-unique index doesn't need store value, write a '0' to reduce space
		value := []byte{'0'}
		if opt.Untouched {
			value[0] = kv.UnCommitIndexKVFlag
		}
		err = rm.Set(key, value)
		return 0, err                   //  < ------- why not return h ,err?
	}

	if skipCheck || opt.Untouched {
		value := EncodeHandle(h)
		// If index is untouched and fetch here means the key is exists in TiKV, but not in txn mem-buffer,
		// then should also write the untouched index key/value to mem-buffer to make sure the data
		// is consistent with the index in txn mem-buffer.
		if opt.Untouched {
			value = append(value, kv.UnCommitIndexKVFlag)
		}
		err = rm.Set(key, value)
		return 0, err            // < ------- why not return h ,err?
	}

	var value []byte
	value, err = rm.Get(key)
	if kv.IsErrNotFound(err) {
		v := EncodeHandle(h)
		err = rm.Set(key, v)
		return 0, err     // < ----- why not return h ,err?
	}

	handle, err := DecodeHandle(value)
	if err != nil {
		return 0, err
	}
	return handle, kv.ErrKeyExists
}
```

https://github.com/pingcap/tidb/blob/release-3.0.13/table/tables/tables.go

**Comment by lance6716** [comment]
`err` is prior to `h` or `0` to caller function, so both are fine.

**Comment by jzdxeb** [comment]
> `err` is prior to `h` or `0` to caller function, so both are fine.

i dont think so.
in ddl/index.go 
Error is keyexsit 
handle is checked,so return 0 maybe incorrect 

Actually I think this is a bug in release-3

**Comment by lance6716** [comment]
> > `err` is prior to `h` or `0` to caller function, so both are fine.
> 
> i dont think so.
> in ddl/index.go
> Error is keyexsit
> handle is checked,so return 0 maybe incorrect
> 
> Actually I think this is a bug in release-3

Do you mean apart from `return handle, kv.ErrKeyExists`, `(*index).Create` also return `0, kv.ErrKeyExists`? Where does this happen?

**Comment by lance6716** [comment]
PTAL @tiancaiamao @AilinKid

**Comment by jzdxeb** [comment]
> > > `err` is prior to `h` or `0` to caller function, so both are fine.
> > 
> > 
> > i dont think so.
> > in ddl/index.go
> > Error is keyexsit
> > handle is checked,so return 0 maybe incorrect
> > Actually I think this is a bug in release-3
> 
> Do you mean apart from `return handle, kv.ErrKeyExists`, `(*index).Create` also return `0, kv.ErrKeyExists`? Where does this happen?
in ddl/index.go
if err == ErrKeyExists 
then 
return handle and kv. ErrKeyExists
if err != ErrKeyExists  0 or handle is ok 

bug case 
```sql
create table t(a int) shard_row_id_bits = 2 pre_split_regions=2;
for i range 2000{
insert into t (i);
}
alter table add index aa on (a); 
```
add index count will be incorrect when reorg worker meet error

**Comment by AilinKid** [comment]
1: explanation about the old code:
the first several the finish path return with `Get Func` or `Set with uncommit flag`, which means they may already be in the TiKV but mem buffer, `Set with uncommit flag` will fill the mem buffer. `Get Func` return success means the mem buffer is also already filled with it, `Set with uncommit flag` can be eliminated. So both of these scenarios won't occur KeyExist errors.

2: explanation about the new code.
the handle is substituted with a KV.Handle interface, there are all return nil now
