### ISSUE TITLE
Encryption for temporary chunks in disk

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#18971]
## Feature Request

**Is your feature request related to a problem? Please describe:**
Now we have spilled chunks data to disk when Join or Sort exceeds the memory quota. But the data in disk should be encrypted, to ensure that others can't read the temp file to steal user data.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by XuHuaiyu** [comment]
finished already
