### ISSUE TITLE
TXN not rollback when context deadline exceeded

### ISSUE THREAD

**Issue by heidawei** [pingcap/tidb#18976]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

insert rows(sample insert sql), but failed, return context deadline exceeded
then I see GC work try to clear TXN records, and some insert slow for lock conflict。
### 2. What did you expect to see? (Required)
I think we should rollback the txn when return context deadline exceeded
### 4. Affected version (Required)
V4.0.1

## SIG slack channel

 [#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score

- 900

## Mentor

* @lzmhhh123

**Comment by ichn-hu** [comment]
Hi @heidawei , could you please privide more details on this bug? E.g. example SQLs to reproduce it?

Moreover, can you still reproduce this bug on current master?

**Comment by cfzjywxk** [comment]
@lysu @jackysp 
I think it's not a bug, what do you think?

**Comment by jackysp** [comment]
Yes, I think it is by design.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
