### ISSUE TITLE
Can the tidb run as production?

### ISSUE THREAD

**Issue by mysqlbranch** [pingcap/tidb#1900]
Can the tidb run as production? Thanks.

**Comment by ngaut** [comment]
Many of customer are using TiDB in production with our support. Please contact us if you want to use it in production now. You may also use it when we release the GA version in the next a few months.

**Comment by mysqlbranch** [comment]
Thanks, What time the GA version will release?

**Comment by geekard** [comment]
Also want to know the time of GA version.

**Comment by ngaut** [comment]
We plan to release the GA version around april, please stay turned.
