### ISSUE TITLE
Returns error indicates that we don't support ALTER TABLE ADD PRIMARY KEY

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#1905]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
Go 1.7

2. What operating system and processor architecture are you using (`go env`)?
darwin64

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
create table t (a int);
alter table t add primary key(a);
```

4. What did you expect to see?

An error indicates that this is not supported.

5. What did you see instead?

return OK

**Comment by zz-jason** [comment]
already supported.
