### ISSUE TITLE
'admin reload statistics' reports 'Unsupported ast.AdminStmt'

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#19066]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
admin reload statistics;
```

### 2. What did you expect to see? (Required)

```
Query OK (0.00sec)
```

### 3. What did you see instead (Required)

```console
(8108, 'Unsupported ast.AdminStmt(*ast.AdminStmt) for buildAdmin')
```

### 4. What is your TiDB version? (Required)

master
```
Release Version: v4.0.0-beta.2-917-ge4451be54
Edition: Community
Git Commit Hash: e4451be54c4eb1a7e5572a8fa7602128ccbcde40
Git Branch: HEAD
UTC Build Time: 2020-08-07 10:45:03
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by eurekaka** [comment]
https://github.com/pingcap/tidb/pull/18880 adds support for this statement.
