### ISSUE TITLE
Insert on duplicate key update does not return error when there is conflict

### ISSUE THREAD

**Issue by ekexium** [pingcap/tidb#19063]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t ( c_int int, c_string varchar(40) collate utf8mb4_bin , primary key (c_string), unique key (c_int));

```sql
create table t ( c_int int, c_string varchar(40) collate utf8mb4_bin , primary key (c_string), unique key (c_int));

begin;
replace into t values (22, 'gold witch'), (24, 'gray singer'), (21, 'silver sight');
commit;
begin;
insert into t values (21,'black warlock'), (22, 'dark sloth'), (21,  'cyan song') on duplicate key update c_int = c_int + 1, c_string = concat(c_int, ':', c_string);
commit;
select * from t;
drop table t;
```

### 2. What did you expect to see? (Required)

For the insert statement, it should return:

```
ERROR 1062 (23000): Duplicate entry '22' for key 't.c_int'
```

The select statement should return:

```
mysql> select * from t;
+-------+--------------+
| c_int | c_string     |
+-------+--------------+
|    21 | silver sight |
|    22 | gold witch   |
|    24 | gray singer  |
+-------+--------------+
3 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

The insert statement returns:

```
Query OK, 5 rows affected (0.00 sec)
Records: 3  Duplicates: 2  Warnings: 0
```

The select statement returns:

```
mysql> select * from t;
+-------+--------------------+
| c_int | c_string           |
+-------+--------------------+
|    22 | gold witch         |
|    24 | gray singer        |
|    23 | 23:22:silver sight |
|    21 | cyan song          |
+-------+--------------------+
4 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

v4.0.0-beta.2-913-gceff1fcaf

**Comment by cfzjywxk** [comment]
release-4.0 branch with commit "7cac557b024f0aaca6825193477e5e6daea7055b" dose not reproduce this problem,
master branch has this problem

**Comment by jackysp** [comment]
https://github.com/pingcap/tidb/pull/18877 introduced it.
