### ISSUE TITLE
"id bigint NOT NULL generated by default as identity" is not support?

### ISSUE THREAD

**Issue by njfanxun** [pingcap/tidb#19079]

**Comment by nullnotnil** [comment]
Hi @njfanxun,

`id bigint not null` can generate an auto_increment value by using either the [auto_increment](https://docs.pingcap.com/tidb/stable/auto-increment) or [auto_random](https://docs.pingcap.com/tidb/stable/auto-random) attribute. For MySQL compatibility, there is also a datatype alias for `serial`, which is a `BIGINT NOT NULL PRIMARY KEY auto_increment`:
```sql
mysql> CREATE TABLE t1 (id SERIAL);
Query OK, 0 rows affected (0.10 sec)

mysql> INSERT INTO t1 VALUES (),();
Query OK, 2 rows affected (0.04 sec)
Records: 2  Duplicates: 0  Warnings: 0

mysql> SELECT * FROM t1;
+----+
| id |
+----+
|  1 |
|  2 |
+----+
2 rows in set (0.00 sec)

mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001
1 row in set (0.00 sec)
```

Let me know if this answers your question. Thanks!

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
