### ISSUE TITLE
ddl change, after canceling, the DDL queue cannot be closed

### ISSUE THREAD

**Issue by madonhe** [pingcap/tidb#19085]
[https://stackoverflow.com/questions/63316476/tidb-ddl-after-the-operation-the-queue-still-exists-and-cannot-be-closed](url)

mysql> ADMIN SHOW DDL;
+------------+--------------------------------------+---------------------+--------------+--------------------------------------+-------+
| SCHEMA_VER | OWNER_ID                             | OWNER_ADDRESS       | RUNNING_JOBS | SELF_ID                              | QUERY |
+------------+--------------------------------------+---------------------+--------------+--------------------------------------+-------+
|         92 | e536315c-6e87-4bc7-b5bb-e6603f8b8db5 | 172.16.116.133:4000 |              | e536315c-6e87-4bc7-b5bb-e6603f8b8db5 |       |
+------------+--------------------------------------+---------------------+--------------+--------------------------------------+-------+
1 row in set (0.00 sec)

mysql> ADMIN SHOW DDL JOBS;
+--------+---------+------------+---------------------+--------------+-----------+----------+-----------+---------------------+---------------------+-----------+
| JOB_ID | DB_NAME | TABLE_NAME | JOB_TYPE            | SCHEMA_STATE | SCHEMA_ID | TABLE_ID | ROW_COUNT | START_TIME          | END_TIME            | STATE     |
+--------+---------+------------+---------------------+--------------+-----------+----------+-----------+---------------------+---------------------+-----------+
|    108 | test    |            | create table        | none         |        52 |      107 |         0 | 2020-08-08 20:00:12 | 2020-08-08 20:12:32 | cancelled |
|    106 | test    |            | create table        | none         |        52 |      105 |         0 | 2020-08-08 19:43:05 | 2020-08-08 19:44:51 | cancelled |
|    104 | test    |            | create table        | none         |        52 |      103 |         0 | 2020-08-08 19:42:17 | 2020-08-08 19:44:50 | cancelled |
|    102 | test    |            | create table        | none         |        52 |      101 |         0 | 2020-08-08 19:25:55 | 2020-08-08 19:30:14 | cancelled |
|    100 | test    |            | create table        | none         |        52 |       99 |         0 | 2020-08-08 19:24:48 | 2020-08-08 19:25:49 | cancelled |
|     98 | test    |            | create table        | none         |        52 |       97 |         0 | 2020-08-08 19:03:38 | 2020-08-08 19:19:58 | cancelled |
|     96 | test    |            | create table        | none         |        52 |       95 |         0 | 2020-08-08 19:01:42 | 2020-08-08 19:03:02 | cancelled |
|     94 | test    |            | create table        | none         |        52 |       93 |         0 | 2020-08-08 18:57:27 | 2020-08-08 18:59:47 | cancelled |
|     92 | test    |            | create table        | none         |        52 |       91 |         0 | 2020-08-08 18:49:51 | 2020-08-08 18:57:01 | cancelled |
|     90 | test    | example    | set tiflash replica | none         |        52 |       79 |         0 | 2020-08-08 18:45:55 | 2020-08-08 18:57:00 | cancelled |
+--------+---------+------------+---------------------+--------------+-----------+----------+-----------+---------------------+---------------------+-----------+
10 rows in set (0.01 sec)

mysql> 
mysql> 
mysql> ADMIN CANCEL DDL JOBS 92;
+--------+-----------------------------------------+
| JOB_ID | RESULT                                  |
+--------+-----------------------------------------+
| 92     | error: [admin:8224]DDL Job:92 not found |
+--------+-----------------------------------------+
1 row in set (0.00 sec)

**Comment by madonhe** [comment]
> /label component/DDL
> 
> clickable url: https://stackoverflow.com/questions/63316476/tidb-ddl-after-the-operation-the-queue-still-exists-and-cannot-be-closed

没听懂 您像传递给我的意思。我应该怎么处理这个问题呢

**Comment by lance6716** [comment]
> > /label component/DDL
> > clickable url: https://stackoverflow.com/questions/63316476/tidb-ddl-after-the-operation-the-queue-still-exists-and-cannot-be-closed
> 
> 没听懂 您像传递给我的意思。我应该怎么处理这个问题呢

这些是分流信息，工作时间会有 SIG DDL 的开发者查看、解决问题。另外可以在 https://asktug.com/ 中文论坛提问，会有更及时的响应。

**Comment by madonhe** [comment]
问题已解决。3.x 版本角色有：pump_servers。要进行重新部署。
write detect binlog to pump failed   导致的问题
