### ISSUE TITLE
SHOW GLOBAL VARIABLES displays SESSION only variables

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#19095]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
SHOW GLOBAL VARIABLES
```

### 2. What did you expect to see? (Required)

No session only variables are displayed.

In MySQL, `SHOW GLOBAL VARIABLES` will not display SESSION variables like `last_insert_id`.

### 3. What did you see instead (Required)

Some session only variables are also displayed, like `tidb_enable_slow_log`.

Note, these variables cannot be called using `SET GLOBAL`:

```
mysql> set global tidb_enable_slow_log=0;
ERROR 1105 (HY000): Variable 'tidb_enable_slow_log' is a SESSION variable and can't be used with SET GLOBAL
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-893-g4e829aaee
Edition: Community
Git Commit Hash: 4e829aaee7b656aa807814708ae05af5233302af
Git Branch: HEAD
UTC Build Time: 2020-08-04 07:57:53
GoVersion: go1.13.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by zz-jason** [comment]
duplicated with https://github.com/pingcap/tidb/issues/18517

**Comment by zz-jason** [comment]
I'm going to close issue, let's discuss it in https://github.com/pingcap/tidb/issues/18517.
