### ISSUE TITLE
Query results are different if there is an index

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#19100]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1, t2;
create table t1 (c decimal);
create table t2 (c decimal, key(c));
insert into t1 values (null);
insert into t2 values (null);
select count(*) from t1 where not c; -- 0
select count(*) from t2 where not c; -- 1
```

### 2. What did you expect to see? (Required)

The two select statement should return same result (mysql returns 0).

### 3. What did you see instead (Required)

```sql
mysql> select count(*) from t1 where not c; -- 0
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.06 sec)

mysql> select count(*) from t2 where not c; -- 1
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.05 sec)

```

### 4. What is your TiDB version? (Required)

both master and release-4.0

**Comment by nullnotnil** [comment]
This appears to be caused by incorrect boolean coercion on the value decimal value. When explicitly searching for IS NULL / IS NOT NULL, results are correct:

```sql
mysql> select count(*) from t2 IGNORE INDEX (c) where c IS NOT NULL;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from t2 IGNORE INDEX (c) where c IS NULL;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from t2 where c IS NOT NULL;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

mysql> select count(*) from t2 where c IS NULL;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

There is a similar bug in https://github.com/pingcap/tidb/issues/12233 (it is not identical, it didn't depend on if the value was indexed or not.)

**Comment by wshwsh12** [comment]
https://github.com/pingcap/tidb/pull/17117 This pr can cover the case.
