### ISSUE TITLE
Supports transitions between the same type (Time types) 

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#19122]
### Description

Supports transitions between the same types, including unsigned transitions.

### Value

- Support conversion between Time types
    + The DATE, DATETIME, and TIMESTAMP Types
    + The TIME Type
    +  The YEAR Type

**Comment by xhebox** [comment]
I am picking up this one.

**Comment by xhebox** [comment]
It looks like the problem is that, there is actually no conversion support for `Year`(which is added in [`8.0.22`](https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html)). Maybe I should make another issue for this problem first?

**Comment by xhebox** [comment]
Ah.. I dont think this should be closed. Maybe we need a new issue to track those TODOs? @AilinKid
