### ISSUE TITLE
Supports transitions between the same type (other Numeric types)

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#19121]
### Description

Supports transitions between the same types, including unsigned transitions.

### Value

- Support conversion between other Numeric types
    + Fixed-Point Types (Exact Value) - DECIMAL, NUMERIC
    + Floating-Point Types (Approximate Value) - FLOAT, DOUBLE
    + Bit-Value Type - BIT

**Comment by wangggong** [comment]
I'll pick it up if nobody is working on it now. Thx.

**Comment by AilinKid** [comment]
> I'll pick it up if nobody is working on it now. Thx.

I only handled the column type change between decimal in #20012, you can still the handle the Float Types and Bit.

**Comment by wangggong** [comment]
> > I'll pick it up if nobody is working on it now. Thx.
> 
> I only handled the column type change between decimal in #20012, you can still the handle the Float Types and Bit.

I'll see it. Thx.
