### ISSUE TITLE
tidb slow query

### ISSUE THREAD

**Issue by zhangdan1** [pingcap/tidb#19129]
## Description
my tidb cluster has many slow queries , I don't know how to reslove it ,could you give me some suggestions ?
![image](https://user-images.githubusercontent.com/20087068/89870885-1a1a1000-dbe9-11ea-8b15-30d616565870.png)

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @SunRunAway

**Comment by nullnotnil** [comment]
The time of 670.3 ms is not a wall time, but a cumulative time from multiple threads. From what I can tell, this is also just one query in isolation, as the dashboard will draw a histogram if there are multiple. i.e.

![image](https://user-images.githubusercontent.com/67764674/90089804-90993980-dcdf-11ea-89d4-cb5d9103bc58.png)

Did you want to ask this question in Chinese on https://asktug.com/ ? I'm sorry, I'll only be able to assist you in English.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
