### ISSUE TITLE
Support Label configurations for TiDB

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#19149]
## Feature Request

**Is your feature request related to a problem? Please describe:**

To support auto-scaling in PD, PD needs to organize the each instances by groups in the cluster. The current way to marking the several instances as a group is to mark them with the same group label.

For TiKV, If Store 1 and Store 2 both have the same label `group=A`, then PD will think them as one group. As TiKV already have metapb.StoreLabel to handle the label logic, TiDB currently haven't the similar logic to handle it.

**Describe the feature you'd like:**

As we don't need to update label during runtime in auto-scaling, one simple way to archive this target is to add the labels configuration and make it register into PD etcd by `TopoInfoSyncer`, then PD could visit the etcd and get each TiDB instance's label information.

**Describe alternatives you've considered:**

Add a new configuration `labels` and its type is `map[string]string`. For `TopoInfoSyncer` will also sync the label information into PD etcd.  That's all.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Yisaer** [comment]
@coocood @lysu  @lonng WDYT?

**Comment by lonng** [comment]
> To support auto-scaling in PD, PD needs to organize the each instances by groups in the cluster. The current way to marking the several instances as a group is to mark them with the same group label.

Can you expand the details why the auto-scaling need group instances first?

**Comment by Yisaer** [comment]
The direct reason PD needs to group the instances in auto-scaling case is to directly mapping the instances in cloud (for tidb-operator, the heterogeneous cluster are managed by different group/ for tidb cloud, the machine types are managed by different machine group) which would be clear to cover the whole auto-scaling process in cloud.

Moreover, I think support label configuration for TiDB may also be helpful for other cases like follower read( tidb could directly read the specific tikv if they are in the same group). auto-scaling is one of the user-cases for grouping instances (also the most needed) and group instances is also the one of the user-cases after label configuration is supported.

**Comment by zz-jason** [comment]
> group instances is also the one of the user-cases after label configuration is supported

would the tidb-servers in the same group share the same configuration?

**Comment by Yisaer** [comment]
@zz-jason No, they won't. Label is the independent component in the configuration and only PD will organize them into groups, but I think in real user cases (like tidb-cloud), they may(as user manually keep the same configuration in one group).

**Comment by zz-jason** [comment]
I mark this feature request as accepted. Let's move on to the technical design progress.

**Comment by Yisaer** [comment]
@zz-jason  I think the design will be very simple and I updated the alternatives in the description.
