### ISSUE TITLE
Incompatibility with MySQL for ADDTIME()

### ISSUE THREAD

**Issue by ekexium** [pingcap/tidb#19150]
### 1. Minimal reproduce step (Required)

```sql
select ADDTIME('2020-05-13 14:01:24', '2020-04-29 05:11:19');
```

### 2. What did you expect to see? (Required)
In MySQL 8.0.21

```sql
mysql> select ADDTIME('2020-05-13 14:01:24', '2020-04-29 05:11:19');
+-------------------------------------------------------+
| ADDTIME('2020-05-13 14:01:24', '2020-04-29 05:11:19') |
+-------------------------------------------------------+
| NULL                                                  |
+-------------------------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> select ADDTIME('2020-05-13 14:01:24', '2020-04-29 05:11:19');
+-------------------------------------------------------+
| ADDTIME('2020-05-13 14:01:24', '2020-04-29 05:11:19') |
+-------------------------------------------------------+
| 2020-05-13 19:12:43                                   |
+-------------------------------------------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-944-gae779e150
Edition: Community
Git Commit Hash: ae779e1502cf99d65511387a4e1eb171bd9eb9c7
Git Branch: master
UTC Build Time: 2020-08-11 03:55:14
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @SunRunAway

**Comment by Tangruilin** [comment]
https://github.com/pingcap/tidb/pull/30653
