### ISSUE TITLE
DML failed on table with column _tidb_rowid

### ISSUE THREAD

**Issue by windtalker** [pingcap/tidb#19167]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table test_1(id int, value int, `_tidb_rowid` int);
Query OK, 0 rows affected (0.08 sec)

mysql> insert into test_1 values(1,2,3);
ERROR 1105 (HY000): insert, update and replace statements for _tidb_rowid are not supported.
mysql> select _tidb_rowid from test_1;
ERROR 1060 (42S21): Duplicate column name '_tidb_rowid'
```

### 2. What did you expect to see? (Required)
DML succeed or DDL failed when creating a table with column `_tidb_rowid`

### 3. What did you see instead (Required)
DDL succeed but DML failed.

### 4. What is your TiDB version? (Required)
master

**Comment by tangenta** [comment]
Duplicate with #12835.
