### ISSUE TITLE
result of select collation(concat(NULL,NULL)) is wrong

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#19166]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
select collation(concat(NULL,NULL));

### 2. What did you expect to see? (Required)

binary

### 3. What did you see instead (Required)
utf8mb4_general_ci
### 4. What is your TiDB version? (Required)

master

**Comment by Patrick0308** [comment]
Can I take it?

**Comment by xiongjiwei** [comment]
btw, `select coercibility(concat(1,1));` get result 5, should 4

**Comment by xiongjiwei** [comment]
`select collation(conv('a' collate utf8mb4_general_ci, 16, 2));` should use connect collation

**Comment by wjhuang2016** [comment]
> Can I take it?

I think @xiongjiwei 's PR can fix this issue already. If you are interested in something related to collation, you can try #17063.
