### ISSUE TITLE
About Contribution

### ISSUE THREAD

**Issue by Wheeeeeeeeels** [pingcap/tidb#19230]

**Comment by nullnotnil** [comment]
For details on contributing: [README.md](https://github.com/pingcap/community/blob/master/contributors/README.md)

For ideas on what to work on, you can use this filter:
https://github.com/pingcap/tidb/issues?q=is%3Aissue+is%3Aopen+label%3Astatus%2Fhelp-wanted

Thanks!

**Comment by Wheeeeeeeeels** [comment]
ok,thank you
