### ISSUE TITLE
Consider a switch to force TopN push down

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#19288]
## Development Task

At present, TopN pushdown to TiKV Coprocessor is controlled by the physical optimization phase. This task aims to provide a switch to force TopN pushing down. like [`agg_to_cop()`](https://docs.pingcap.com/tidb/stable/optimizer-hints#agg_to_cop), maybe we can add a `topn_to_cop()` optimizer hint.

An alternative approach is to provide an instance level variable to control whether the `TopN` operator on that tidb instance is forcibly pushed to the coprocessor.

To gain better performance, we'd better handle all the coprocessor tasks for a tikv to calculate the TopN on that tikv instance, then gather all the TopN result from all the tikv instances, calculate the final TopN result in the tidb instance.

**Comment by qw4990** [comment]
@tangwz Would you like to help us fix this issue?

**Comment by qw4990** [comment]
Since TopN pushdown is in the physical optimization phase, the plan which contains the pushed-down TopN may be cut down by other plans with lower cost.
Would you have any idea about implementing this hint gracefully? @zz-jason

**Comment by zz-jason** [comment]
when the hint is enabled, I think we can only choose to push topN to the coprocessor, no need to consider any other possible plans which topN is not pushed down.

**Comment by zz-jason** [comment]
the difficulty but performance-beneficial part is to handle cop tasks on different scan ranges to the same tikv coprocessor at once. we may need to change the task send logic in the tidb part, optimize the task handle part in the tikv coprocessor layer.

**Comment by zz-jason** [comment]
consider this case: there are only 3 tikv, but we have 1000 coprocessor tasks (this is usually the common case on table rowid scan), each coprocessor tasks only returns ~1 records, we want to calculate the top 100 records. the best strategy is to calculate the top 100 for tikv 1-3 on all the coprocessor tasks handled in each tikv, not to calculate the top 100 for a single coprocessor task.
