### ISSUE TITLE
Upgrade PD dependencies

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tidb#19306]
## Development Task

As PD is transferred to the TiKV organization, it is necessary to upgrade the dependencies of each repo.
Due to the circular dependency of `tidb` `br` `unistore` `tidb-tools`, each repo needs to be upgraded twice. Record the upgrade process in this issue.

**Comment by HunDunDM** [comment]
Stage 1: Upgrade PD in `br` `unistore` `tidb-tools`. At this stage, these repos will not be compiled.

* [ ] br
* [ ] unistore
* [ ] tidb-tools

**Comment by HunDunDM** [comment]
Stage 2: Upgrade `pd` `br` `unistore` `tidb-tools` in `tidb`

* [ ] tidb

**Comment by HunDunDM** [comment]
Stage 3: Upgrade `tidb` in `br` `unistore` `tidb-tools`

* master
  * [ ] br
  * [ ] unistore
  * [ ] tidb-tools
* release-4.0
  * [ ] br

**Comment by nolouch** [comment]
It's too difficult to update the dependency :(

**Comment by HunDunDM** [comment]
All tasks have been completed and this issue will be closed.
