### ISSUE TITLE
Cannot alter YEAR column

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#19342]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists x;
create table x(c year(4) comment 'xxx');
alter table x modify c year(4) not null;
```

### 2. What did you expect to see? (Required)

Altered c to remove its coment.

### 3. What did you see instead (Required)

```
8200 - Unsupported modify column: can't change unsigned integer to signed or vice versa, Time: 0.003000s
```

Notice that according to `SHOW CREATE TABLE`, the column `c` is *NOT* unsigned:

```sql
CREATE TABLE `x` (
  `c` year(4) DEFAULT NULL COMMENT 'xxx'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

### 4. What is your TiDB version? (Required)

v4.0.4

**Comment by xhebox** [comment]
This should be a subissue of the big issue #19116.

**Comment by breeswish** [comment]
@xhebox They might be different issues. I didn't modify the signed / unsigned flag. I only removed the field comment.

**Comment by xhebox** [comment]
The root cause is that ModifyColumn does not invoke `ColumnDefToCol`. Thus the flag of new column is not processed as the created column.
Do you think it is a standalone problem?

**Comment by breeswish** [comment]
@xhebox I have no idea about the implementation faults you talked. I see that #19116 is talking about "supports changing the column type", so that I guess they are not related --- why would removing the field comment lead to changing a column type? It should be either a bug that is not covered by the description of #19116, for example, maybe changing a comment *mistakenly* changes the type, or #19116 is covering more than it claims to be? Also I found that this bug does not exist if you change type from YEAR to INT.

**Comment by zimulala** [comment]
@xhebox 
Are you interested in fixing this problem？

**Comment by wjhuang2016** [comment]
This issue has nothing to do with column type change. In fact,  `year` can't be `unsigned` or  `sign`.

**Comment by xhebox** [comment]
@wjhuang2016 Then there is another bug. I think that the unsigned flag of `year` comes from https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L620. So here should be another check of the type.

**Comment by wjhuang2016** [comment]
> @wjhuang2016 Then there is another bug. I think that the unsigned flag of `year` comes from https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L620.

Yeah, `unsigned` here is an attribute. It will not show in `show create table`.
