### ISSUE TITLE
insert into will be update 

### ISSUE THREAD

**Issue by chestnutsj** [pingcap/tidb#19352]
## Bug Report
  insert into will be update 

### 1. Minimal reproduce step (Required)
1 . CREATE TABLE test (
	id bigint primary key,
	name varchar(256) ,
	ts int
)

2.  insert into test values( 1, 'test1', 0);

3. 

begin;
   update test set name='xxx' where id =1 and ts <> 0 ;
    insert into test values( 1, 'test2', 0);   <= this will success
commit ;
 

### 2. What did you expect to see? (Required)

 Duplicate entry '1' for key 'PRIMARY'
 
select * from test;
 +----+-------+------+
| id | name  | ts   |
+----+-------+------+
|  1 | test1 |    0 |
+----+-------+------+

### 3. What did you see instead (Required)
   
select * from test;
+----+-------+------+
| id | name  | ts   |
+----+-------+------+
|  1 | test2 |    0 |
+----+-------+------+
1 row in set (0.00 sec)

### 4. What is your TiDB version? (Required)
  

 Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by ekexium** [comment]
I cannot reproduce it in 4.0.4. This bug should have been fixed.
You can try using latest releases.

**Comment by chestnutsj** [comment]
are you sure ? @ekexium 

MySQL [test]> SELECT tidb_version()
    -> ;
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.3-4-gc61fc7247
Edition: Community
Git Commit Hash: c61fc7247e9f6bc773761946d5b5294d3f2699a5
Git Branch: release-4.0.4
UTC Build Time: 2020-07-29 01:47:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> drop table test;
ommit ;Query OK, 0 rows affected (0.13 sec)

MySQL [test]> CREATE TABLE test (
    -> id bigint primary key,
    -> name varchar(256) ,
    -> ts int
    -> );
Query OK, 0 rows affected (0.09 sec)

MySQL [test]> insert into test values( 1, 'test1', 0);
Query OK, 1 row affected (0.06 sec)

MySQL [test]> begin;
Query OK, 0 rows affected (0.00 sec)

MySQL [test]> update test set name='xxx' where id =1 and ts <> 0 ;
Query OK, 0 rows affected (0.01 sec)
Rows matched: 0  Changed: 0  Warnings: 0

MySQL [test]> select * from test;
+----+-------+------+
| id | name  | ts   |
+----+-------+------+
|  1 | test1 |    0 |
+----+-------+------+
1 row in set (0.00 sec)

MySQL [test]> insert into test values( 1, 'test2', 0);
Query OK, 1 row affected (0.00 sec)

MySQL [test]> commit ;
Query OK, 0 rows affected (0.05 sec)

MySQL [test]> select * from test;
+----+-------+------+
| id | name  | ts   |
+----+-------+------+
|  1 | test2 |    0 |
+----+-------+------+
1 row in set (0.00 sec)

**Comment by ekexium** [comment]
@chestnutsj Here's my test.

```sql
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.3-59-g7cac557b0
Edition: Community
Git Commit Hash: 7cac557b024f0aaca6825193477e5e6daea7055b
Git Branch: release-4.0
UTC Build Time: 2020-08-07 09:52:18
GoVersion: go1.14.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> drop table test if exist;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 18 near "if exist"
mysql> CREATE TABLE test (id bigint primary key,name varchar(256),ts int);
ERROR 1050 (42S01): Table 'test.test' already exists
mysql> insert into test values( 1, 'test1', 0);
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> update test set name='xxx' where id =1 and ts <> 0 ;
Query OK, 0 rows affected (0.01 sec)
Rows matched: 0  Changed: 0  Warnings: 0

mysql> insert into test values( 1, 'test2', 0);
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test;
+----+-------+------+
| id | name  | ts   |
+----+-------+------+
|  1 | test1 |    0 |
+----+-------+------+
1 row in set (0.01 sec)
```

**Comment by chestnutsj** [comment]
wow  ,thanks
