### ISSUE TITLE
record each db duration like record-db-qps feature 

### ISSUE THREAD

**Issue by pepezzzz** [pingcap/tidb#19360]
## Feature Request

**Is your feature request related to a problem? Please describe:**

record each db duration when types of workload use different db in the same tidb cluster.
**Describe the feature you'd like:**

like record-db-qps feature, a new parameter  record-db-duration in tidb configuration file controls this feature enable or not .
After feature enable, these metrics related to db duration send to Prometheus.
**Describe alternatives you've considered:**

N/A
**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by zz-jason** [comment]
I think it's duplicated with https://github.com/pingcap/tidb/issues/17688. close due to duplicated.

**Comment by zz-jason** [comment]
let's discuss this feature request at https://github.com/pingcap/tidb/issues/17688.
