### ISSUE TITLE
Unit test TestTablesLockDelayClean fails

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#19479]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![image](https://user-images.githubusercontent.com/867381/91283116-c3056500-e7bc-11ea-873e-73ea8a008782.png)

**Comment by blacktear23** [comment]
@SunRunAway this test case fail on `TestTablesLockDelayClean` not `TestIfNotExists` please fix issue title.

**Comment by blacktear23** [comment]
I will fix this.

**Comment by SunRunAway** [comment]
> @SunRunAway this test case fail on `TestTablesLockDelayClean` not `TestIfNotExists` please fix issue title.

Thanks. Fixed.
