### ISSUE TITLE
Execute the no-dependent DDL job as soon as possible

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#19476]
## Feature Request

**Is your feature request related to a problem? Please describe:**

```sql
test> admin show ddl jobs;
+--------+---------+-------------------------+--------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------+
| JOB_ID | DB_NAME | TABLE_NAME              | JOB_TYPE     | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID | ROW_COUNT | START_TIME          | END_TIME            | STATE   |
+--------+---------+-------------------------+--------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------+
| 58     | test    | t                       | add index    | write reorganization | 1         | 56       | 0         | 2020-08-26 16:09:42 | <null>              | running |
| 59     | test    | t                       | add column   | none                 | 1         | 56       | 0         | 2020-08-26 16:09:44 | <null>              | none    |
| 61     | test    |                         | create table | none                 | 1         | 60       | 0         | 2020-08-26 16:09:47 | <null>              | none    |
+--------+---------+-------------------------+--------------+----------------------+-----------+----------+-----------+---------------------+---------------------+---------+
```

As you can see, DDL job `59` is blocked by DDL job `58`, since they are both modify the table `t`, this is reasonable.

But DDL job `61` is also been blocked, it is blocked by DDL job `59`, since they are in the same DDL job queue. This can be optimized because it doesn't have a dependent DDL job.

**Implementation**

In the function `handleDDLJobQueue`, we can change `getFirstDDLJob` into `getFirstNoDependencyDDLJob` to find the first job that has no dependency. We also need to handle the dequeue logic properly.

## Score
300

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)
* @tangenta

## Recommended Skills
* DDL
* Golang

## Learning Materials
MySQL's [document](https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html) for syntax reference.
[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by tangenta** [comment]
This issue is related to https://github.com/pingcap/tidb/issues/32031.
