### ISSUE TITLE
Record the time consuming of memory operation of Insert Executor in Runtime Information

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#19512]
## Development Task

INSERT IGNORE from a table of 300,000 rows,

```mysql
INSERT IGNORE INTO t SELECT * FROM t1
```
And we got the following slow query log.
![image](https://user-images.githubusercontent.com/867381/91382035-6016db00-e85b-11ea-8935-23d6fb85e915.png)

Unfortunately, with this log, we have no clue where the time is consumed. 

Then we must investigate this problem by using go profile or trace.

![image](https://user-images.githubusercontent.com/867381/91382564-96088f00-e85c-11ea-9850-dfea23c81a3d.png)

With the above go profile graph, I propose to add two extra time-consuming sections in runtime information and trace span,
1. Check Duplicate, including [`getKeysNeedCheck`](https://github.com/pingcap/tidb/blob/650be7c4383a197a0311433572d082eb087217a2/executor/insert_common.go#L952) and [`txn.Get` from memory buffer](https://github.com/pingcap/tidb/blob/650be7c4383a197a0311433572d082eb087217a2/executor/insert_common.go#L978), but except the RPC time.
2. Add Records, for the memory operation of memtable.

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

**Comment by crazycs520** [comment]
@jyz0309 PTAL
