### ISSUE TITLE
find_in_set is not compatible with MySQL

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#19521]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
select find_in_set('b', 'a,b ,b'); /* use general_ci */ 

In MySQL, got 3. But in TiDB, got 2.
Because MySQL does not consider padding here, but TiDB does.  

### 4. What is your TiDB version? (Required)

mastert

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

**Comment by LENSHOOD** [comment]
Seems the issue has been fixed.

```sql
mysql> select find_in_set('b', 'a,b ,b'); /* use general_ci */
+----------------------------+
| find_in_set('b', 'a,b ,b') |
+----------------------------+
|                          3 |
+----------------------------+
1 row in set (0.00 sec)
```

```sql
mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v4.0.0-beta.2-1314-gb61f8bb9e
Edition: Community
Git Commit Hash: b61f8bb9ed14a41dd04fbed389cba58d5271ab39
Git Branch: issue#19521
UTC Build Time: 2020-09-29 01:17:06
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by wjhuang2016** [comment]
> Seems the issue has been fixed.
> 
> ```sql
> mysql> select find_in_set('b', 'a,b ,b'); /* use general_ci */
> +----------------------------+
> | find_in_set('b', 'a,b ,b') |
> +----------------------------+
> |                          3 |
> +----------------------------+
> 1 row in set (0.00 sec)
> ```
> 
> ```sql
> mysql> select tidb_version();
> +--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | tidb_version()                                                                                                                                                                                                                                                                                                                 |
> +--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> | Release Version: v4.0.0-beta.2-1314-gb61f8bb9e
> Edition: Community
> Git Commit Hash: b61f8bb9ed14a41dd04fbed389cba58d5271ab39
> Git Branch: issue#19521
> UTC Build Time: 2020-09-29 01:17:06
> GoVersion: go1.15
> Race Enabled: false
> TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
> Check Table Before Drop: false |
> +--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> ```

No, you have to enable new collation.

**Comment by LENSHOOD** [comment]
> > Seems the issue has been fixed.
> > ```sql
> > mysql> select find_in_set('b', 'a,b ,b'); /* use general_ci */
> > +----------------------------+
> > | find_in_set('b', 'a,b ,b') |
> > +----------------------------+
> > |                          3 |
> > +----------------------------+
> > 1 row in set (0.00 sec)
> > ```
> > 
> > 
> > ```sql
> > mysql> select tidb_version();
> > +--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> > | tidb_version()                                                                                                                                                                                                                                                                                                                 |
> > +--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> > | Release Version: v4.0.0-beta.2-1314-gb61f8bb9e
> > Edition: Community
> > Git Commit Hash: b61f8bb9ed14a41dd04fbed389cba58d5271ab39
> > Git Branch: issue#19521
> > UTC Build Time: 2020-09-29 01:17:06
> > GoVersion: go1.15
> > Race Enabled: false
> > TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
> > Check Table Before Drop: false |
> > +--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
> > 1 row in set (0.00 sec)
> > ```
> 
> No, you have to enable new collation.

Yes, after enable new collation now I can reproduce this issue, thx.

**Comment by wjhuang2016** [comment]
@nullnotnil 
Hi, do you think we need to fix this compatible problem?  It seems that TiDB's result is more correct.

**Comment by nullnotnil** [comment]
@wjhuang2016 I agree with you. At first I thought this might be related to MySQL 8.0 utf8mb4 collations being NOPAD, but that appears not to be the case. i.e.

```sql
mysql [localhost:8021] {msandbox} ((none)) > select "a " = "a"; # In MySQL 5.7 under latin1/utf8/ut8 this is TRUE
+------------+
| "a " = "a" |
+------------+
|          0 |
+------------+
1 row in set (0.00 sec)
```

But even in MySQL 5.7, or MySQL 8.0 with utf8mb4_general_ci (instead of `utf8mb4_0900_ai_ci`), you get the following result:
```sql
select find_in_set('a', 'à,a'); # =1
select find_in_set('a', 'A,a'); # =1
select find_in_set('A', 'a,a'); # =1
select find_in_set('a', 'A ,a'); # =2
```

I think MySQL is wrong here, because it is not considering the `PAD` attribute of the collation, and is always treating it as `NOPAD` regardless.

**Comment by LENSHOOD** [comment]
In MySQL 5.7, the doc say [Nonbinary strings have PAD SPACE behavior for all collations](https://dev.mysql.com/doc/refman/5.7/en/charset-binary-collations.html#charset-binary-collations-trailing-space-comparisons).

Otherwise MySQL 8.0 has changed that to [assign a single *pad attribute* to every collations](https://dev.mysql.com/doc/refman/8.0/en/charset-binary-collations.html#charset-binary-collations-trailing-space-comparisons):

```sql
mysql> SELECT COLLATION_NAME, PAD_ATTRIBUTE
       FROM INFORMATION_SCHEMA.COLLATIONS
       WHERE CHARACTER_SET_NAME = 'utf8mb4';
+----------------------------+---------------+
| COLLATION_NAME             | PAD_ATTRIBUTE |
+----------------------------+---------------+
| utf8mb4_general_ci         | PAD SPACE     |
| utf8mb4_bin                | PAD SPACE     |
| utf8mb4_unicode_ci         | PAD SPACE     |
| utf8mb4_icelandic_ci       | PAD SPACE     |
...
| utf8mb4_0900_ai_ci         | NO PAD        |
| utf8mb4_de_pb_0900_ai_ci   | NO PAD        |
| utf8mb4_is_0900_ai_ci      | NO PAD        |
...
| utf8mb4_ja_0900_as_cs      | NO PAD        |
| utf8mb4_ja_0900_as_cs_ks   | NO PAD        |
| utf8mb4_0900_as_ci         | NO PAD        |
| utf8mb4_ru_0900_ai_ci      | NO PAD        |
| utf8mb4_ru_0900_as_cs      | NO PAD        |
| utf8mb4_zh_0900_as_cs      | NO PAD        |
| utf8mb4_0900_bin           | NO PAD        |
+----------------------------+---------------+
```

According to doc, `utf8mb4_genereal_ci` are always PAD SPACE no matter 5.7 or 8.0. Maybe MySQL treat find_in_set() as a special case, but no doc to mention that. I'll try to find MySQL source code about this.

**Comment by xiongjiwei** [comment]
> I'll try to find MySQL source code about this.

@LENSHOOD hi, do you have any conclusion？

**Comment by LENSHOOD** [comment]
> > I'll try to find MySQL source code about this.
> 
> @LENSHOOD hi, do you have any conclusion？

Forgot to do this after checkout mysql source code...
I'll check it in the next few days...

**Comment by LENSHOOD** [comment]
> > > I'll try to find MySQL source code about this.
> > 
> > 
> > @LENSHOOD hi, do you have any conclusion？
> 
> Forgot to do this after checkout mysql source code...
> I'll check it in the next few days...

@xiongjiwei 
Hi, I've did some research:
In MySQL 5.7 source code, there's a `CHARSET_INFO.txt` file to illustrate method info relate to charset and collation. 
It's said that:
```
MY_COLLATION_HANDLER
====================
strnncoll()   - compares two strings according to the given collation
strnncollsp() - like the above but ignores trailing spaces for PAD SPACE
                collations. For NO PAD collations, identical to strnncoll.
```

In the code implementation, *find_in_set()* call `strnncoll()` to compare the element, but *str_cmp()* will call `strnncollsp()`. That's why *find_in_set()* cannot apply the PAD SPACE attribute.
(*finde_in_set()* located at `item_func.cc`, *str_cmp()* located at `item_cmpfunc.cc`)

Hence, the *find_in_set()* implementation in MySQL 5.7 do seems not properly. We should keep the TiDB behavior of PAD SPACE.

**Comment by xiongjiwei** [comment]
> Hi, I've did some research

That's a good job, thank you for your investigation, it's very helpful.

**Comment by wjhuang2016** [comment]
@LENSHOOD @xiongjiwei It occurs to me that MySQL would ignore padding in `set`. And this why `find_in_set`

**Comment by LENSHOOD** [comment]
> > Hi, I've did some research
> 
> That's a good job, thank you for your investigation, it's very helpful.

No problem.
