### ISSUE TITLE
Able to handle big transaction

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#1954]
Currently user may send very big transaction to tidb-server, we should handle it properly.
Such as: 
Add  millions of rows.
Delete millions of rows.
Update or replace millions of rows.

**Comment by morgo** [comment]
This is documented for now https://www.pingcap.com/docs/sql/mysql-compatibility/#large-transactions

**Comment by nullnotnil** [comment]
Several restrictions have been lifted in TiDB 4.0: https://pingcap.com/blog/large-transactions-in-tidb
Limits are also documented at https://docs.pingcap.com/tidb/stable/tidb-limitations

I am going to close this issue, but please feel free to re-open if there are any specific limits not covered here. Thanks!
