### ISSUE TITLE
field() return wrong result

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#19550]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql root@127.0.0.1:test> create table t (p1 varchar(255) character set utf8, n1 varchar(255) character set utf8)
Query OK, 0 rows affected
Time: 0.028s
mysql root@127.0.0.1:test> insert into t values("0aa1!测试テストמבחן         ", "0aa1!测试テストמבחן ");
Query OK, 1 row affected
Time: 0.006s
mysql root@127.0.0.1:test> select field(p1,n1) from t;
```

### 2. What did you expect to see? (Required)
On MySQL:
```
mysql root@127.0.0.1:test> select field(p1,n2) from t1;
+--------------+
| field(p1,n2) |
+--------------+
| 1            |
+--------------+
1 row in set
Time: 0.016s
```

### 3. What did you see instead (Required)
On TiDB:
```
mysql root@127.0.0.1:test> select field(p1,n2) from t1;
+--------------+
| field(p1,n2) |
+--------------+
| 0            |
+--------------+
1 row in set
Time: 0.016s
```

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.0-beta.2-1072-g07453ff73
Edition: Community
Git Commit Hash: 07453ff73503f146d830a4d1b692ac390ff177f6
Git Branch: master
UTC Build Time: 2020-08-27 13:27:18
GoVersion: go1.14.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by cyliu0** [comment]
@jebter @aytrack Plz check this issue. Found by an internal test case TICASE-1582

**Comment by wjhuang2016** [comment]
@cyliu0 Did you check new_collation_enabled?
mysql> select * from mysql.tidb;
+-----------------------+----------------+----------------------------------------------------+
| VARIABLE_NAME         | VARIABLE_VALUE | COMMENT                                            |
+-----------------------+----------------+----------------------------------------------------+
| bootstrapped          | True           | Bootstrap flag. Do not delete.                     |
| tidb_server_version   | 50             | Bootstrap version. Do not delete.                  |
| system_tz             | Asia/Shanghai  | TiDB Global System Timezone.                       |
| **new_collation_enabled | True**           | If the new collations are enabled. Do not edit it. |
+-----------------------+----------------+----------------------------------------------------+
4 rows in set (0.00 sec)

**Comment by cyliu0** [comment]
No... I didn't find the configuration described in the precondition of the case. After I enabled it, the case works fine. I'll close this one. And can we update the precondition of TICASE-1582? @jebter @aytrack
