### ISSUE TITLE
Supports transitions between the same type (String types)

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#19571]
### Description

Supports transitions between the same types, including unsigned transitions.

### Value

- Support conversion between String types
    + The CHAR and VARCHAR Types
    + The BINARY and VARBINARY Types
    + The BLOB and TEXT Types
    + The ENUM Type
    + The SET Type

**Comment by Patrick0308** [comment]
I think I can help you.

**Comment by zimulala** [comment]
@Patrick0308 
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU) on slack in your spare time to discuss or get help with us.
