### ISSUE TITLE
Why `go get github.com/pingcap/tidb/store` failed

### ISSUE THREAD

**Issue by fouzhe** [pingcap/tidb#19589]
## General Question

Hi, all!
Why `go get github.com/pingcap/tidb/store` failed?
Thanks for your time!

**Comment by fouzhe** [comment]
https://oss-fuzz-build-logs.storage.googleapis.com/log-8ac2ecff-a4ab-4a0f-a85a-b8b00862cdb9.txt

**Comment by time-and-fate** [comment]
Hi~

We use Go modules to manage dependency now, which means a `go.mod` file is used to declare module path and dependencies. 

If you're using Go modules and want to add `github.com/pingcap/tidb/store` to dependencies, you can try `GO111MODULE=on go get github.com/pingcap/tidb/store@master`.
If you just want to get the source code, you can clone this repo directly.

**Comment by fouzhe** [comment]
@time-and-fate Thank you so much! :)
