### ISSUE TITLE
not suppot alter table to change a column definition

### ISSUE THREAD

**Issue by steven88888** [pingcap/tidb#1958]
ALTER TABLE user_device CHANGE id  id INT AUTO_INCREMENT NOT NULL COMMENT '1000000000 userId'

===

got a error as following:

ERROR 1105 (HY000): line 0 column 30 near " id  id INT AUTO_INCREMENT NO...

**Comment by zimulala** [comment]
@steven88888 
Now the parser can pass this SQL.
But we don't support changing `AUTO_INCREMENT`.  You can refer to [doc-cn](https://github.com/pingcap/docs-cn/blob/master/sql/mysql-compatibility.md).
