### ISSUE TITLE
fail to compile master version of tidb-server

### ISSUE THREAD

**Issue by alitrack** [pingcap/tidb#19615]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
go get -u github.com/pingcap/tidb/tidb-server
```

### 2. What did you expect to see? (Required)

successfully compile and get tidb-server

### 3. What did you see instead (Required)

```
go: finding module for package github.com/pingcap/pd/pd-client
.go/pkg/mod/github.com/pingcap/tidb@v2.0.11+incompatible/store/tikv/kv.go:28:2: module github.com/pingcap/pd@latest found (v2.1.19+incompatible), but does not contain package github.com/pingcap/pd/pd-client

```

I notice there is no github.com/pingcap/pd/pd-client, but exists github.com/pingcap/pd/client

### 4. What is your TiDB version? (Required)

just want to compile it, so not version info.

**Comment by ZenoTan** [comment]
go get should add a hash number.

**Comment by alitrack** [comment]
I successfully compile it by using make command, thanks.
