### ISSUE TITLE
TiDB unsupported modify column type varchar(20) not match origin bigint

### ISSUE THREAD

**Issue by lijiawen** [pingcap/tidb#19638]
how to modify column type?
TiDB not support bigint to varchar

**Comment by nolouch** [comment]
Hi, @lijiawen, you can read the [documents](https://docs.pingcap.com/zh/tidb/stable/sql-statement-change-column#mysql-%E5%85%BC%E5%AE%B9%E6%80%A7).

**Comment by AilinKid** [comment]
hi~ column type change is under development, following the issue, https://github.com/pingcap/tidb/issues/19116
