### ISSUE TITLE
Large Memory Usage While Running TPC-H

### ISSUE THREAD

**Issue by youwithouto** [pingcap/tidb#19644]
## Performance Questions
When running a particular TPC-H query, TiDB was using around 2 GB of memory. Is this the correct behaviour?
The context is given below.

- What version of TiDB are you using?
  v4.0.4

- What's the observed and your expected performance respectively?
  Around 2 GB of memory was used while running one of the queries.

- Have you compared TiDB with other databases? If yes, what's their difference?
  No

- For a specific slow SQL query, please provide the following information:

  - Whether you analyzed the tables involved in the query and how long it is after you ran the last `ANALYZE`.

  - Whether this SQL query always or occasionally runs slowly.
    Yes

  - The `EXPLAIN ANALYZE` result of this query if your TiDB version is higher than 2.1, or you can just provide the `EXPLAIN` result.

  - The plain text of the SQL query and table schema so we can test it locally. It would be better if you can provide the dumped statistics information.

     <img width="1525" alt="Screen Shot 2020-09-01 at 3 26 37 pm" src="https://user-images.githubusercontent.com/15098497/91798404-27666f80-ec68-11ea-8868-b99ebe6fe30d.png">

    - Table Generation

      `go-tpc tpch prepare -H 10.240.0.11 -P 4000 -D tpch --sf 4 --analyze`

    - Query

      ```sql
      SELECT
      nation,
      o_year,
      sum (amount) AS sum_profit
      FROM
      (
          SELECT
          n_name AS nation,
          extract (
              year
              FROM
              o_orderdate
          ) AS o_year,
          l_extendedprice * (? - l_discount) - ps_supplycost * l_quantity AS amount
          FROM
          part,
          supplier,
          lineitem,
          partsupp,
          orders,
          nation
          WHERE
          s_suppkey = l_suppkey
          AND ps_suppkey = l_suppkey
          AND ps_partkey = l_partkey
          AND p_partkey = l_partkey
          AND o_orderkey = l_orderkey
          AND s_nationkey = n_nationkey
          AND p_name LIKE ?
      ) AS profit
      GROUP BY
      nation,
      o_year
      ORDER BY
      nation,
      o_year DESC;
      ```  

- For a general performance question, e.g. the benchmark result you got by yourself is not expected, please provide the following information:

  - Your cluster's topology architecture.

    - Platform
      - Google Cloud
      - Machine Type: tested on both n1-standard-8 (30 GB memory) and e2-standard-2 (8 GB memory)
      - OS: ubuntu-1804-lts (with nvme ssd)

    - 3 TiDB nodes: 
      - TiDB and PD
    - 3 TiKV nodes: 
      - TiKV
    - 1 Monitor node:
      - Monitoring Server, Grafana, Alert Manager

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
