### ISSUE TITLE
maybe (*Scanner).scan can be optimized

### ISSUE THREAD

**Issue by tsthght** [pingcap/tidb#19687]
## Performance Questions

![image](https://user-images.githubusercontent.com/13314548/91875768-8353e700-ecae-11ea-88da-018f6b88a0f7.png)

![image](https://user-images.githubusercontent.com/13314548/91875883-a9798700-ecae-11ea-9b41-8c04c20e6d5c.png)

![image](https://user-images.githubusercontent.com/13314548/91875903-ae3e3b00-ecae-11ea-807b-789e637ae7ce.png)

maybe (*Scanner).scan can be optimized

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 300

## Mentor
 * @qw4990

**Comment by ZenoTan** [comment]
Can you be more specific about the optimization?

**Comment by tsthght** [comment]
> Can you be more specific about the optimization?

Thank you for your advice. I'll add something specific optimization  as soon as possible.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
