### ISSUE TITLE
Call For Participation: add memory trace for group concat agg functions

### ISSUE THREAD

**Issue by b41sh** [pingcap/tidb#19737]
## Development Task

This issue is used to trace group concat agg functions, which is a part of [19369](https://github.com/pingcap/tidb/issues/19369)

Please comment on this issue if you are interested in.

## SIG slack channel
[#sig-exec](https://slack.tidb.io/invite?team=tidb-community&channel=sig-exec&ref=high-performance)

## Score
- 600

## Mentor
* @b41sh

## Recommended Skills
* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by XuHuaiyu** [comment]
@William0423 Friendly ping~
Do you have any problem when solving the issue? 
If so, feel free to let us know, we'll glad if we could be of help.

**Comment by William0423** [comment]
> @William0423 Friendly ping~
> Do you have any problem when solving the issue?
> If so, feel free to let us know, we'll glad if we could be of help.

I am reading the source code now, will ask you guys help in case of any problem, thanks for supporting.
