### ISSUE TITLE
Call For Participation: add memory trace for ntile agg functions

### ISSUE THREAD

**Issue by b41sh** [pingcap/tidb#19741]
## Development Task

This issue is used to trace ntile agg functions, which is a part of [19369](https://github.com/pingcap/tidb/issues/19369)

Please comment on this issue if you are interested in.

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 600

## Mentor
* @b41sh

## Recommended Skills
* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by Howie66** [comment]
i could do this

**Comment by XuHuaiyu** [comment]
@Howie66 Thanks. Please comment `/pick-up` to pick up this task.
