### ISSUE TITLE
Call For Participation: add memory trace for row number agg functions

### ISSUE THREAD

**Issue by b41sh** [pingcap/tidb#19746]
## Development Task

This issue is used to trace row number agg functions, which is a part of [19369](https://github.com/pingcap/tidb/issues/19369)

Please comment on this issue if you are interested in.

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 600

## Mentor
* @b41sh

## Recommended Skills
* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by Rustin-Liu** [comment]
@b41sh  Could you please add challenge-program label and high-performance label for these issues?

**Comment by b41sh** [comment]
> @b41sh Could you please add challenge-program, high-performance and SIG labels for these issues?

@Rustin-Liu labels have added.
