### ISSUE TITLE
Call For Participation: add memory trace for max min agg functions

### ISSUE THREAD

**Issue by b41sh** [pingcap/tidb#19740]
## Development Task

This issue is used to trace max min agg functions, which is a part of [19369](https://github.com/pingcap/tidb/issues/19369)

Please comment on this issue if you are interested in.

## SIG slack channel
[#sig-exec](https://tidbcommunity.slack.com/archives/CMRD79DRR)

## Score
- 600

## Mentor
* @b41sh

## Recommended Skills
* SQL Optimization
* Golang Profiling
* Code Refactoring

**Comment by xiaodong-ji** [comment]
pick `max min agg functions`

**Comment by xiaodong-ji** [comment]
@TszKitLo40 I've already chosen, Can you choose other?
