### ISSUE TITLE
Support setting new_collations_enabled_on_first_bootstrap=true to enable CI Collation after cluster first bootstrap

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tidb#19782]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If I forgot to set `new_collations_enabled_on_first_bootstrap=true` at cluster bootstrap or I want to set `new_collations_enabled_on_first_bootstrap=true` in cluster which upgrade from `v3.0`, need to create a new cluster and set `new_collations_enabled_on_first_bootstrap=true` at bootstrap. And then migrate the data on old cluster  to new cluster.

**Describe the feature you'd like:**

Support setting `new_collations_enabled_on_first_bootstrap=true` to enable CI Collation after cluster first bootstrap.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by AilinKid** [comment]
PTAL @wjhuang2016 @bb7133

**Comment by nullnotnil** [comment]
The value of this setting changes the on-disk format, so I suspect it might be hard to dynamically allow the change?

As a suggested alternative, may I suggest changing the default for new clusters starting with TIDB 5.0. It can be similar to the change from optimistic to pessimistic locking, where upgrades from existing clusters still retained the previous default.

This helps avoid the same problem, where users didn't know there was a setting for collations until after they had started loading data.

**Comment by scsldb** [comment]
There are compatibility issues and it is easy to make mistakes, it is recommended to consult others.

**Comment by jebter** [comment]
new_collations_enabled_on_first_bootstrap defaults to true: https://docs.pingcap.com/tidb/stable/tidb-configuration-file#new_collations_enabled_on_first_bootstrap . I will close this issue. If there are any updates, you can reopen it.
