### ISSUE TITLE
Program exit during import a large data from MySQL Dump (7GB)

### ISSUE THREAD

**Issue by keithyau** [pingcap/tidb#1978]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.6.3

2. What operating system and processor architecture are you using (`go env`)?
![image](https://cloud.githubusercontent.com/assets/659311/20099741/26fd38e8-a5f5-11e6-8a22-55cfbc7d4337.png)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.

source a sql file in mysql client

4. What did you expect to see?
import finish

5. What did you see instead?
program exited after a few hours
![image](https://cloud.githubusercontent.com/assets/659311/20099710/f88bb034-a5f4-11e6-991c-dad89ee3194b.png)

**Comment by shenli** [comment]
@keithyau May I have the full panic stack?

**Comment by keithyau** [comment]
Just a "killed", no other log

**Comment by shenli** [comment]
@keithyau Any information in dmesg? Or any log for the reason why the process is killed, such as OOM.

**Comment by keithyau** [comment]
in tidbserver log, like below, then killed
![image](https://cloud.githubusercontent.com/assets/659311/20125420/642a4f8a-a668-11e6-94d1-6385864e3069.png)

at myloader, it is like this

![image](https://cloud.githubusercontent.com/assets/659311/20125440/7b7b4428-a668-11e6-94e6-859d63c7049b.png)


The tables got something, but not all imported.

![image](https://cloud.githubusercontent.com/assets/659311/20125465/9ade77d6-a668-11e6-8b00-dba9031bec69.png)


I guess the count(*) so long due to im importing.

thanks
Keith

**Comment by shenli** [comment]
@keithyau Thanks! We will discuss this bug today and keep you updated.

**Comment by keithyau** [comment]
some more log

![image](https://cloud.githubusercontent.com/assets/659311/20139348/99e52368-a6c0-11e6-91b1-a26d068145e2.png)

**Comment by shenli** [comment]
@keithyau From your recent logs, we can tell that your TiDB cluster is too busy. May I have your hardware info and deployment info?

**Comment by keithyau** [comment]
2G 14G * 3

**Comment by shenli** [comment]
How many thread do you use to load data?

**Comment by keithyau** [comment]
How to check? i only use all default value

**Comment by tiancaiamao** [comment]
@keithyau 
-q Number of queries per transaction, default 1000
ref https://github.com/pingcap/tidb/issues/1576

**Comment by shenli** [comment]
@keithyau Please use 1 for parameter -q.

**Comment by ngaut** [comment]
@keithyau Any updates?

**Comment by ngaut** [comment]
Feel free to reopen it if you still have any questions.
