### ISSUE TITLE
Question: How long it take to import a 7GB mysqldump  ?

### ISSUE THREAD

**Issue by keithyau** [pingcap/tidb#1980]
FYI, it is just a question. or i need some settings ? currently just using default settings.

**Comment by shenli** [comment]
@keithyau It depends on the schema and your hardware.
We do not recommend use mysqldump  to import large data. Compared with MySQL, TiDB has higher latency. So use single thread to import data will be slow. 
TiDB could reach higher throughput that MySQL. We usually use mydumper/myloader to migrate data from MySQL to TiDB. You can refer to this [docs](https://github.com/pingcap/docs-cn/blob/master/op-guide/migration.md#使用-mydumpermyloader-全量导入数据).

**Comment by keithyau** [comment]
will try, thanks
