### ISSUE TITLE
How to deploy tidb cluster on kubernetes without network components

### ISSUE THREAD

**Issue by foxchenlei** [pingcap/tidb#19823]
## Feature Request

**Describe the feature you'd like:**
I want to deploy tidb cluster on kubernetes using Daemonset. The k8s cluster has no network componets or  Persistent Storage.
The TidbCluster looks like rely on network .  Do you have any ways without network to deploy tidb on kubernetes ?
Thanks

**Comment by lichunzhu** [comment]
Can [this article](https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tidb-operator#offline-installation) meet your expectations? 
But for tidbcluster TiKV will need persistent storage.

**Comment by foxchenlei** [comment]
fine.  I will have a try

**Comment by foxchenlei** [comment]
> Can [this article](https://docs.pingcap.com/tidb-in-kubernetes/stable/deploy-tidb-operator#offline-installation) meet your expectations?
> TiKV in tidbcluster will need persistent storage.

Hi, My k8s cluster has no network componets, not offline. local-volume-provisioner still needs network componets.
`Could not get node information (remaining retries: 2): Get https://10.96.0.1:443/api/v1/nodes/192.168.127.83: dial tcp 10.96.0.1:443: connect: connection timed out`

**Comment by DanielZhangQD** [comment]
@foxchenlei What do you mean with `no network componets`? You mean no `kube-proxy`? And how do Pods in the cluster access each other?
For `no Persistent Storage`, the PD and TiKV need to persistent data, how can you do that without persistent storage.

**Comment by DanielZhangQD** [comment]
BTW, you do not need to use TiDB Operator, right?

**Comment by foxchenlei** [comment]
> @foxchenlei What do you mean with `no network componets`? You mean no `kube-proxy`? And how do Pods in the cluster access each other?
> For `no Persistent Storage`, the PD and TiKV need to persistent data, how can you do that without persistent storage.

yes, no `kube-prxoxy`

**Comment by DanielZhangQD** [comment]
OK, then you do not need to use TidbCluster CR and TiDB Operator, you can write your own yaml files to deploy the TiDB cluster.

**Comment by DanielZhangQD** [comment]
@foxchenlei Do you use hostNetwork for your Kubernetes cluster?

**Comment by heming79** [comment]
Yes , use hostNetwork  , such as  DaemonSet StatefulSet 。

**Comment by DanielZhangQD** [comment]
> Could not get node information (remaining retries: 2): Get https://10.96.0.1:443/api/v1/nodes/192.168.127.83: dial tcp 10.96.0.1:443: connect: connection timed out

Is this error reported when you deploy local-volume-provisioner with HostNetwork enabled?

BTW, are you just trying the TiDB on the Kubernetes? If yes, you can try our [get-started guide](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#%E4%BD%BF%E7%94%A8-kind-%E5%88%9B%E5%BB%BA-kubernetes-%E9%9B%86%E7%BE%A4) with Kind, which is very easy to setup.

**Comment by foxchenlei** [comment]
yes，pod will request k8s svc ip .

**Comment by DanielZhangQD** [comment]
Are you just trying the TiDB on the Kubernetes? If yes, you can try our [get-started guide](https://docs.pingcap.com/zh/tidb-in-kubernetes/stable/get-started#%E4%BD%BF%E7%94%A8-kind-%E5%88%9B%E5%BB%BA-kubernetes-%E9%9B%86%E7%BE%A4) with Kind.

**Comment by foxchenlei** [comment]
no， I wish deploy TiDB on production.

**Comment by DanielZhangQD** [comment]
OK, I think you can build your own yaml files to deploy TiDB Cluster without TiDB Operator.
Please note that, without TiDB Operator (Which also needs to access kube-apiserver via service IP), you have to manually transfer the PD leader during PD Upgrade/ScaleIn and you have to manually transfer the TiKV region leader during TiKV upgrade and delete the TiKV store during TiKV scale-in.
Without PV management, after scale-in, you have to clean the data in the host path.

**Comment by DanielZhangQD** [comment]
Or would you like to help improve the TiDB Operator to deploy in pure HostNetwork Kubernetes cluster?

**Comment by foxchenlei** [comment]
The point is TiDB Operator need to access kube-apiserver via service IP

**Comment by DanielZhangQD** [comment]
Yes, we have to improve it or you have to go with your own YAML files and manual operations.

**Comment by foxchenlei** [comment]
Thank you for your answer

**Comment by heming79** [comment]
> Yes, we have to improve it or you have to go with your own YAML files and manual operations.
May i have your Wechat number , We can talk in Wechat (heming_0120) , I always talk to dongxu in Wechat , my email heming@emar.com
