### ISSUE TITLE
tidb hangs with unable to connect

### ISSUE THREAD

**Issue by elvizlai** [pingcap/tidb#19858]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
All tikv crashed with OOM, after tikv recovered, one of our tidb can't connected, dashboard can't show related info before restart. 

tiup cluster shows everything is ok.

### 2. What did you expect to see? (Required)
All works well.

### 3. What did you see instead (Required)
TiDB can not establish new connection.

### 4. What is your TiDB version? (Required)
v4.0.5

debug info before tidb restart.
[debug.zip](https://github.com/pingcap/tidb/files/5185920/debug.zip)

**Comment by wshwsh12** [comment]
Is there any error information in tidb.log? Could you please provide tidb.log?  Maybe we can get some useful information from it.

**Comment by XuHuaiyu** [comment]
No response for a long time.
I'll close this issue.
Feel free to reopen this if you need any further help.
