### ISSUE TITLE
str_to_date / concat date_format syntax problem

### ISSUE THREAD

**Issue by keithyau** [pingcap/tidb#1985]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?

1.6.3
2. What operating system and processor architecture are you using (`go env`)?
![image](https://cloud.githubusercontent.com/assets/659311/20142447/bbeb258e-a6cf-11e6-97e7-d975bdaa6748.png)

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
select count(*) as accumulate_count, sum(payAmount) as accumulate_payamount, booktime from order_master where bookTime > str_to_date(concat(@START_DAY,@check_time_start, '%Y-%m-%d%H'));

4. What did you expect to see?
can run

5. What did you see instead?
ERROR 1105 (HY000): line 0 column 133 near "concat(@START_DAY,@check_time_start, '%!Y(MISSING)-%!m(MISSING)-%!d(MISSING)%!H(MISSING)'))"

Looks like concat or str_to_date func not 100% same behavior as mySQL?

**Comment by shenli** [comment]
@keithyau We do not support str_to_date now.  Please refer to the [doc](https://github.com/pingcap/docs-cn/blob/master/op-guide/mysql-compatibility.md#内建函数). We will implement it soon.

**Comment by morgo** [comment]
`str_to_date` is now supported:
```
MySQL [test]> SELECT STR_TO_DATE("August 10 2017", "%M %d %Y");
+-------------------------------------------+
| STR_TO_DATE("August 10 2017", "%M %d %Y") |
+-------------------------------------------+
| 2017-08-10                                |
+-------------------------------------------+
1 row in set (0.00 sec)
```
I am going to go ahead and close this issue.  Please feel free to re-open it if I am mistaken.
