### ISSUE TITLE
Support Mac OS X deploy via homebrew

### ISSUE THREAD

**Issue by leaxoy** [pingcap/tidb#1986]

**Comment by shenli** [comment]
@leaxoy Thanks for your suggestion. 
We do not have plan to publish to homebrew. We encourage users deploy TiDB cluster on Linux. 
If you are interested in this, could you help us to do this?

**Comment by morgo** [comment]
See https://github.com/Homebrew/homebrew-core/pull/37634

You can `brew install ./tidb-server.rb` while waiting or it to merge into official homebrew.  I am going to close this issue here so we can track progress in one place.

Thank you for the suggestion!
