### ISSUE TITLE
mysqlslap: Cannot run query SELECT intcol1,charcol1 FROM t1 ERROR : table mysqlslap.t1

### ISSUE THREAD

**Issue by gqf2008** [pingcap/tidb#1989]
mysqlslap -a -c 500 --auto-generate-sql-write-number=100000 -T -i 10  -h 10.25.175.125 -P 4000 -uroot
mysqlslap: Cannot run query SELECT intcol1,charcol1 FROM t1 ERROR : table mysqlslap.t1

不能完成测试。。。

**Comment by shenli** [comment]
@gqf2008 Thanks for your report! We will check it out and keep you updated.

**Comment by shenli** [comment]
@gqf2008 We have already allocated the bug. It will be fixed soon.

**Comment by shenli** [comment]
@gqf2008 We fixed this bug. Please try the latest master.

**Comment by gqf2008** [comment]
好的

**Comment by gqf2008** [comment]
mysqlslap -a -c 500 --auto-generate-sql-write-number=100000 -T -i 10 -h 127.0.0.1 -P 4000 -u root
mysqlslap: Cannot run query INSERT INTO t1 VALUES (73673339,'BN3152Gza4GW7atxJKACYwJqDbFynLxqc0kh30YTwgz3FktQ43XTrqJ4PQ25frn7kXhfXD8RuzN1j8Rf3y8ugKy6es3IbqPJM6ylCyD6xS7YcQCfHKZxYNvB7yTahm') ERROR : Information schema is out of date.
很遗憾，不能跑完测试

tidb-server错误日志：

2017/02/07 00:40:48 server.go:192: [info] [239] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.496815582s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [146][TIME_QUERY] 1m57.491960023s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [146] dispatch error:
id:146, addr:127.0.0.1:45640 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [146] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.495164896s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [232][TIME_QUERY] 1m57.522066231s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [232] dispatch error:
id:232, addr:127.0.0.1:45876 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [232] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [278][TIME_QUERY] 1m57.518926179s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [278] dispatch error:
id:278, addr:127.0.0.1:46072 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [278] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.521309289s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [107][TIME_QUERY] 1m57.546996418s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [107] dispatch error:
id:107, addr:127.0.0.1:45720 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [107] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.668531203s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [238][TIME_QUERY] 1m57.693958271s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [238] dispatch error:
id:238, addr:127.0.0.1:45856 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [238] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.721137323s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [102][TIME_QUERY] 1m57.746508867s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [102] dispatch error:
id:102, addr:127.0.0.1:45744 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [102] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.772612916s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [84][TIME_QUERY] 1m57.796215649s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [84] dispatch error:
id:84, addr:127.0.0.1:45615 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [84] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.820856912s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.817213771s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [245][TIME_QUERY] 1m57.852591469s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [245] dispatch error:
id:245, addr:127.0.0.1:45884 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [245] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [373][TIME_QUERY] 1m57.843835157s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [373] dispatch error:
id:373, addr:127.0.0.1:46044 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [373] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.838727777s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.87370067s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [193][TIME_QUERY] 1m57.864497443s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [193] dispatch error:
id:193, addr:127.0.0.1:45892 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [193] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.872991895s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.884947704s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [150][TIME_QUERY] 1m57.905097763s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [150] dispatch error:
id:150, addr:127.0.0.1:45796 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [150] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [148][TIME_QUERY] 1m57.905051731s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [148] dispatch error:
id:148, addr:127.0.0.1:45788 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [148] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [171][TIME_QUERY] 1m57.913010581s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [171] dispatch error:
id:171, addr:127.0.0.1:45814 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [171] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.98042924s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m57.964377332s backoff(96ms [tikvRPC]) region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m58.021276697s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [305][TIME_QUERY] 1m58.02040803s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [305] dispatch error:
id:305, addr:127.0.0.1:46012 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [305] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [488][TIME_QUERY] 1m57.996948538s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [488] dispatch error:
id:488, addr:127.0.0.1:46416 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [488] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m58.039085492s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [195][TIME_QUERY] 1m58.049919497s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [195] dispatch error:
id:195, addr:127.0.0.1:45890 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [195] close connection
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m58.07315682s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 coprocessor.go:339: [info] [TIME_COP_TASK] 1m58.066203698s region(2 3 1) ranges(1) store(10.28.92.2:20160)
2017/02/07 00:40:48 adapter.go:167: [warning] [139][TIME_QUERY] 1m58.083875755s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [139] dispatch error:
id:139, addr:127.0.0.1:45644 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [139] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [259][TIME_QUERY] 1m58.119766816s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [259] dispatch error:
id:259, addr:127.0.0.1:45968 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [259] close connection
2017/02/07 00:40:48 adapter.go:167: [warning] [121][TIME_QUERY] 1m58.110015164s SELECT intcol1,charcol1 FROM t1
2017/02/07 00:40:48 conn.go:354: [warning] [121] dispatch error:
id:121, addr:127.0.0.1:45558 status:2, collation:latin1_swedish_ci, user:root
SELECT intcol1,charcol1 FROM t1
connection was bad
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:146:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:769:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:677:
2017/02/07 00:40:48 server.go:192: [info] [121] close connection
2017/02/07 00:41:09 metrics.go:303: [warning] [EXPENSIVE_QUERY] select * from mysql.user order by host, user;
2017/02/07 00:41:09 metrics.go:303: [warning] [EXPENSIVE_QUERY] select * from mysql.db order by host, db, user;
2017/02/07 00:41:09 metrics.go:303: [warning] [EXPENSIVE_QUERY] select * from mysql.tables_priv
2017/02/07 00:41:09 metrics.go:303: [warning] [EXPENSIVE_QUERY] select * from mysql.columns_priv

**Comment by tiancaiamao** [comment]
hi, @gqf2008 
The error log `ERROR : Information schema is out of date` says TiDB can't load the schema within a lease. To solve this, you can try to add a command line argument `-lease 10s` when TiDB start.

By the way, this seems to be a resource consuming test, I run it under my laptop and it eat up the whole memory. So, you'd better use TiKV, deploy them separately to get the best performance.

**Comment by gqf2008** [comment]
测试机器一共有4台，3台pb，tikv(16c 32g 1t ssd)，1台tidb（8c 16g），出现故障时我观察了pb和kitv的机器，内存、io、cpu其实都不高，但是tidbcpu很高，所以我不确定是不是tidb的问题

**Comment by tiancaiamao** [comment]
TiDB是无状态的，如果瓶颈是在TiDB的CPU，那么实际应用中我们可以部署多台TiDB来解决。

针对这个测试，CPU高只是某些地方跑起来有性能瓶颈，应该并不会使测试挂掉的。TiDB默认的lease时间1秒不适合生产环境使用，你可以先把lease调高了试试。

**Comment by gqf2008** [comment]
好的
