### ISSUE TITLE
support `show variables where` syntax

### ISSUE THREAD

**Issue by cppmule** [pingcap/tidb#199]
2015/09/19 21:39:04 session.go:235: [error] Syntax error: /* mysql-connector-java-5.1.35 ( Revision: 5fb9c5849535c13917c2cf9baaece6ef9693ef27 ) */SHOW VARIABLES WHERE Variable_name ='language' OR Variable_name = 'net_write_timeout' OR Variable_name = 'interactive_timeout' OR Variable_name = 'wait_timeout' OR Variable_name = 'character_set_client' OR Variable_name = 'character_set_connection' OR Variable_name = 'character_set' OR Variable_name = 'character_set_server' OR Variable_name = 'tx_isolation' OR Variable_name = 'transaction_isolation' OR Variable_name = 'character_set_results' OR Variable_name = 'timezone' OR Variable_name = 'time_zone' OR Variable_name = 'system_time_zone' OR Variable_name = 'lower_case_table_names' OR Variable_name = 'max_allowed_packet' OR Variable_name = 'net_buffer_length' OR Variable_name = 'sql_mode' OR Variable_name = 'query_cache_type' OR Variable_name = 'query_cache_size' OR Variable_name = 'license' OR Variable_name = 'init_connect'

**Comment by siddontang** [comment]
@cppmule 

We have not supported `show variables where` syntax, we will support it later.
Thank you very much.

**Comment by siddontang** [comment]
Hi @cppmule 

Can you checkout branch siddontang/fix-issue-199 and help us to test it again?

**Comment by cppmule** [comment]
Passed, thanks.
I got more errors:
2015/09/19 22:52:40 conn.go:257: [error] cmd: -- MySQL dump 10.13  Distrib 5.5.34, for Linux (x86_64)
--
-- Host: localhost    Database: icar_qa
-- ------------------------------------------------------
-- Server version	5.5.34-log
/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;



Seems you didn't ignore comments.

**Comment by qiuyesuifeng** [comment]
Thanks for your report.
Yes, we have not support sql comment like `select c /* this is a comment */ from t` now.
We will support it later.
btw, is it convenient for u to remove sql comment temporarily to check whether have any other problems? Thanks again.

**Comment by ngaut** [comment]
The comments are generated by some java tools. And there are too many comments.
We should strip those comments.

/**/ 

 --

**Comment by siddontang** [comment]
Move comment discussion to #203  :smile:
