### ISSUE TITLE
Reduce the impact on DML when executing partition DDL

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#19913]
### Example

Table schema:
```sql
create table t(id int primary key) 
    partition by hash(id) partitions 4;
```

Conn1:
```sql
begin;
# insert into partition p1.
insert into t values(1);
```

Conn2:
```sql
alter table t truncate partition p0;
```

Conn1:
```sql
commit;
```

Executing the last statement `commit` reports an error:
```
ERROR 8028 (HY000): Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]
```

### Explanation

DDL will make the concurrent transactions fail, as long as the transactions are writing to the same tables.
The tables which the transactions wrote to are recorded in a map. After the schema of a table changes, TiDB will check whether the changed table exists in the map. If it's true, the transaction will fail.

Assuming we are always writing to the newest partition and truncating the oldest partition, the two partitions are always different. But currently, the truncating operations affect the writing operations.

### Solution

Only put the ids of affected partitions in the map if the table is a partitioned table. Thus the map contains both partition ids and table ids. When judging whether to abort a transaction, just compare the ids, regardless of whether they are partition ids or table ids.

## Score

- 300

## Mentor

 * @djshow832

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## SIG Slack Channel

You can join [#sig-ddl](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU) on slack in your spare time to discuss and get help with mentors or others.

## Recommended Skills

* DDL
* Transaction
* Golang

## Learning Materials

* [TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by AilinKid** [comment]
Some considerations of this issue.
For hash partition: hash number is used to probe the inserted partition for DML dynamically.

For example: hash(id) partition 5, DDL truncate 2 partition
when we insert id = 7, the probed hash partition is 7%5=2
After DDL (Retry)
when we insert id = 7, the probed hash partition is 7%3=1

Although the target inserted partition and truncated partition is always different, the truncate action does make the recomputation of the target inserted partition necessary. PTAL @tiancaiamao
