### ISSUE TITLE
Support display the process of some DDL operations

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#19923]
## Feature Request

Now we only have the `job.RowCount` to display the process of `add index`. But, we are supporting `modify/change column` and `drop column with indexes` which has some tasks of backfilling data. 
e.g.
```
create table t (a int not null default 1, b int not null default 0, index idx2(c));
insert into t values(1, 2), (11, 22);
alter table t change column b cc mediumint;
```
In this operation of the `change column`, we need to rewrite the `b` column data(backfill task 1) in rows and `idx2` data(backfill task 2).

So it has two backfill tasks in this case. If we only show `RowCount`, can't know which task is being processed. We'd better show the specific backfill task.

Besides, the metrics of `BackfillTotalCounter` and `AddIndexProgress` in "metrics/ddl.go" only counts the progress of the `add index` operation. They also need to be updated.

## Score

- 450

## Mentor

- @bb7133 

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Recommended Skills
* DDL
* Golang

## Learning Materials
MySQL's [document](https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html) for syntax reference.
[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by pengdaqian2020** [comment]
@zimulala 
I cannot run this on tidb
![image](https://user-images.githubusercontent.com/71140907/94511198-43e7ce80-024b-11eb-919c-ebf3efb8a4e9.png)
 Does it means ?
```
create table t (a int not null default 1, b int not null default 0, index idx2(b));
insert into t values(1, 2), (11, 22);
alter table t change column b cc bigint;
```

btw

when I run 
```
alter table t change column b cc bigint;
```
the backfill tasks don't run 

it comes to
```
runDDLJob
->onModifyColumn
    ->doModifyColumn
```

Could you please give me more case ?
