### ISSUE TITLE
auto analyze the newly added index

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#19933]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Adding a new index for a table whose `modify_row_count/total_row_count` is smaller than the auto-analyze ratio (0.5 by default). Currently, the auto-analyze job is at table level, it's impossible to auto-analyze the newly added index to get the correct statistics for it. Users have to execute the `analyze table xxx index xx` statement to collect the statistics manually.

**Describe the feature you'd like:**

auto analyze the newly added index if it's in the time window of auto analyze.

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by jebter** [comment]
The function has been realized.I will close this issue. If there are any updates, you can reopen it.
