### ISSUE TITLE
Support VALUES and TABLE statements syntax

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#19934]
## Description

Related parser issue: https://github.com/pingcap/parser/issues/869

### Example

The [`TABLE`](https://dev.mysql.com/doc/refman/8.0/en/table.html) and [`VALUES`](https://dev.mysql.com/doc/refman/8.0/en/values.html) statements are two query specification statements introduced in [MySQL 8.0.19](https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-19.html#mysqld-8-0-19-sql-syntax).

```sql
TABLE tbl_name [ORDER BY col_name] [LIMIT limit [OFFSET offset]];

VALUES ROW(val1, val2, …), … [ORDER BY column_N [LIMIT limit [OFFSET offset]]];
```

### Explaination

These can be used in place everywhere a `SELECT` statement was expected, including:

* UNION
* JOIN
* subqueries
* SELECT INTO OUTFILE
* INSERT INTO SELECT
* CREATE TABLE SELECT

### Solution
For a reference, please see https://github.com/pingcap/parser/pull/680 and learn how to support a new syntax in the parser. 

## Score

* 300

## SIG Slack Channel

You can join [#sig-ddl](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU) on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)

* @tangenta 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Parser
* Golang

## Learning Materials

* [Parser Quickstart](https://github.com/pingcap/parser/blob/master/docs/quickstart.md)
* [Parser implementation(CN)](https://pingcap.com/blog-cn/tidb-source-code-reading-5/)

**Comment by kennytm** [comment]
We should reopen this. #20314 only updated the parser deps, but did not actually implement the feature. Currently using TABLE and VALUES statement just crashes (#21486).
