### ISSUE TITLE
Support right join for join reorder

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#19940]
## Description
We haven't support right join in join reorder algorithm.

## Score（must）
     1200
## SIG slack channel（must）:
Contact us in channel `#sig-planner` of [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)
## Mentor(must)
@winoros 
## Recommended Skills：
- Graph theory

**Comment by zhaoxugang** [comment]
I'm Interested in this issue, can you give me some advice? thanks @winoros

**Comment by winoros** [comment]
@zhaoxugang Sure, i'll give some reference today.

**Comment by zhaoxugang** [comment]
> @zhaoxugang Sure, i'll give some reference today.

OK, look forward to it!

**Comment by winoros** [comment]
@zhaoxugang 
Hi would please join our community slack channel and contact us in #sig-planner channel or directly dm me(Cui Yiding in workspace).

**Comment by Tangruilin** [comment]
I'm not familiar with Graph theory, could I try to solve this problem? /cc @winoros
