### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by lunny** [pingcap/tidb#1995]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
go version go1.7.3 darwin/amd64

2. What operating system and processor architecture are you using (`go env`)?
mac osx 10.12.1

3. What did you do?
go get -u -v github.com/pingcap/tidb
make build

4. What did you expect to see?
compile no error

5. What did you see instead?
➜  tidb git:(master) make build
GOPATH=/Users/lunny/gopath/src/github.com/pingcap/tidb/_vendor:/Users/lunny/gopath GO15VENDOREXPERIMENT="1" go build
# github.com/pingcap/tidb/parser
parser/lexer.go:81: undefined: yySymType
parser/misc.go:479: undefined: yySymType
parser/yy_parser.go:73: undefined: yySymType
parser/yy_parser.go:74: undefined: yySymType
parser/yy_parser.go:75: undefined: yySymType
make: *** [build] Error 2

**Comment by shenli** [comment]
@lunny Please use `make`. Or you should run `make parser` before `make build`.

**Comment by lunny** [comment]
sorry for that. resolved.
