### ISSUE TITLE
support using where clause to dump one table's data in a key range

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb#19951]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In the past, dumpling uses `_tidb_rowid` to dump data in a table parallelly.
When TiDB enables clustered index and if the customer doesn't specify an integer type primary key, dumpling still need to split the table into chunks. In TiDB, `start key` can satisfy our expectations.
```
mysql> select start_key, table_id from information_schema.tikv_region_status s, information_schema.tables t where s.table_id = t.tidb_table_id and t.table_name = 't1' and is_index = 0 order by start_key;
+--------------------------------------------------------+----------+
| start_key                                              | table_id |
+--------------------------------------------------------+----------+
| 7480000000000000FF3100000000000000F8                   |       49 |
| 7480000000000000FF315F720131393630FF30303000FE000000FC |       49 |
| 7480000000000000FF315F720132383234FF30303000FE000000FC |       49 |
+--------------------------------------------------------+----------+
```
However, dumpling still need to decode this start_key to primary keys to dump data in a key range.

**Describe the feature you'd like:**

Support getting data in a key range through a where clause. For example, `select * from t where _tidb_start_key < 7480000000000000FF3A5F720137000000FF00000000F8013000FF000000000000F800FE;`. If tidb supports this, dumpling and other applications don't need to decode `start_key` any more.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lichunzhu** [comment]
Related dumpling issue. https://github.com/pingcap/dumpling/issues/149

**Comment by coocood** [comment]
replaced by https://github.com/pingcap/tidb/issues/20567
