### ISSUE TITLE
Extract some conflicting info from TiKV to TiDB to construct the lock wait related information view

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#19960]
## Description
Now it's very difficult to investigate transaction conflicts issues in TiDB, e.g., are there many transactions waiting for the same lock, which two or more transactions are waiting for one another which causes deadlock. If we have a system table containing transaction waiting info, we can diagnose such issues much easier.

## Score

* 20000

## SIG Slack Channel

You can join [#sig-transaction](https://tikv-wg.slack.com/archives/CU0TU3GSE) on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)

* @cfzjywxk 
* @youjiali1995 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* TiDB
* TiKV
* Transaction

## Learning Materials

* [PingCAP Infra Meetup No.119 TiDB 悲观事务](https://www.bilibili.com/video/BV1FJ411i7Fb?p=2)
* [TiDB 悲观事务实现](https://docs.google.com/document/d/1x_sntnxn9IJWNOJFVAU-9ji6fiZLSG1j7FBHhXgF2Ko/edit#)
* [TiDB 悲观事务 slide](https://docs.google.com/presentation/d/1hEXpsXj9ChZhrTjkyFR_EkAt9ODbWP7huymyP-8ifwc/edit#slide=id.g5e40386e4f_9_0)
* You can refer to how other databases implement it.

**Comment by ichn-hu** [comment]
This sounds intriguing to me.

**Comment by Deardrops** [comment]
Is this a `tptc` issue or not? I cannot find this issue in [tptc related issue list](https://github.com/pingcap/community/blob/master/challenge-programs/high-performance-tidb-challenge-cn.md).

@youjiali1995 @cfzjywxk

**Comment by youjiali1995** [comment]
No. It' an issue of high performance lessons. @Deardrops

**Comment by jianzhiyao** [comment]
marked

**Comment by youjiali1995** [comment]
Close it because we're working on it.
