### ISSUE TITLE
Support conversion from Numeric types to others

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#19970]
### Background
With the development of the implementation of column type change, we have break the process into two phases.

1. implement the architecture and column type change between the same type. [phase 1](https://github.com/pingcap/tidb/issues/19116)
2. implement the column type change between the different types and some TODO lists. [phase 2](https://github.com/pingcap/tidb/issues/19939)

### Problem
Numeric Types includes:

- Floating-Point Types: float, double
- Fixed-Point Types: decimal
- Bit-Value Type: bit

Support conversion from Numeric types to others
For example: 

- change decimal to string
- change float to int
- change bit to time
- ...

### Solution
Generally speaking, these changes may all need the reorganize the data, you can refer to the previous issue in phase 1 for the implementation of architecture details. 

In the process of your development, maybe you should also take the SQL Mode into consideration, handling some warnings or errors.

### Score

- 300

### Mentor

- AilinKid

## Recommended Skills

[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by LENSHOOD** [comment]
depend on https://github.com/pingcap/tidb/pull/20623 to avoid repetitive work.
