### ISSUE TITLE
alter table t drop partition where ts < '2008-04-01 00:00:00'

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#20024]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This feature request is initially required by https://asktug.com/t/topic/33424/2

**Describe the feature you'd like:**

We support `alter table t drop partition p0,p1 ...`, but this statement is not convenient enough.

```
CREATE TABLE quarterly_report_status (
       report_id INT NOT NULL,
       report_status VARCHAR(20) NOT NULL,
       report_updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)
    PARTITION BY RANGE (UNIX_TIMESTAMP(report_updated)) (
    PARTITION p0 VALUES LESS THAN (UNIX_TIMESTAMP('2020-03-30 00:00:00')),
    PARTITION p1 VALUES LESS THAN (UNIX_TIMESTAMP('2020-03-31 00:00:00')),
    PARTITION p2 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-01 00:00:00')),
    PARTITION p3 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-02 00:00:00')),
    PARTITION p4 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-03 00:00:00')),
    PARTITION p5 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-04 00:00:00')),
    PARTITION p6 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-05 00:00:00')),
    PARTITION p7 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-06 00:00:00')),
    PARTITION p8 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-07 00:00:00')),
    PARTITION p9 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-08 00:00:00')));
```

After the table is created, there is no information about the date and partition names. 
Worse still, 'less than' is converted to an integer:

```
CREATE TABLE `quarterly_report_status` (
  `report_id` int(11) NOT NULL,
  `report_status` varchar(20) NOT NULL,
  `report_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE ( UNIX_TIMESTAMP(`report_updated`) ) (
  PARTITION `p0` VALUES LESS THAN (1585497600),
  PARTITION `p1` VALUES LESS THAN (1585584000),
  PARTITION `p2` VALUES LESS THAN (1585670400),
  PARTITION `p3` VALUES LESS THAN (1585756800),
  PARTITION `p4` VALUES LESS THAN (1585843200),
  PARTITION `p5` VALUES LESS THAN (1585929600),
  PARTITION `p6` VALUES LESS THAN (1586016000),
  PARTITION `p7` VALUES LESS THAN (1586102400),
  PARTITION `p8` VALUES LESS THAN (1586188800),
  PARTITION `p9` VALUES LESS THAN (1586275200)
)
```

If a user says: "I want to truncate date older than '2008-04-01 00:00:00'", the solution is not obvious.

If we support `alter table t drop partition where XXX` statement, it's much more convenient for such a scene.

```
ALTER TABLE quarterly_report_status DROP PARTITION WHERE report_updated < '2008-04-01 00:00:00' 
```

**Describe alternatives you've considered:**

Handle partition names manually, like 

```
    PARTITION BY RANGE (UNIX_TIMESTAMP(report_updated)) (
    PARTITION p20200330 VALUES LESS THAN (UNIX_TIMESTAMP('2020-03-30 00:00:00')),
    PARTITION p20200331 VALUES LESS THAN (UNIX_TIMESTAMP('2020-03-31 00:00:00')),
    PARTITION p20200401 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-01 00:00:00')),
    PARTITION p20200402 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-02 00:00:00')),
    PARTITION p20200403 VALUES LESS THAN (UNIX_TIMESTAMP('2020-04-03 00:00:00')),
...
```

and use the old DDL statement:

```
ALTER TABLE quarterly_report_status DROP PARTITION p20200330,p20200330,p20200401 ...
```

**Teachability, Documentation, Adoption, Migration Strategy:**

Implement this feature is not difficult, just use partition pruning for the 'where' statement to get the partitions.

Cons: User friendly
Pros: MySQL compatibility

**Comment by nullnotnil** [comment]
What is the expected behavior if the `WHERE` is split between a partition?

I think for this to work correctly, it would have to be on exact partition boundaries, otherwise you are mixing and matching DDL and DML semantics. If the user has to get the boundary exactly right, I am not sure how much easier this is.

**Comment by tiancaiamao** [comment]
> What is the expected behavior if the WHERE is split between a partition?

This may happen in a hash partition table. 
We can limit the usage of this SQL to woke only on the range partition table.

Or some other query like 

```
ALTER TABLE quarterly_report_status DROP PARTITION WHERE report_updated in ('2008-04-01', '2008-05-06', '2009-02-03')
```

We can support this one, or deny this kind of query if the partition pruning results in `where` condition is not continuous, both strategies is OK.

`where quarterly_report_status between XXX` seems to work as expected.

---------

> I think for this to work correctly, it would have to be on exact partition boundaries,


The user can use

```
EXPLAIN SELECT * FROM quarterly_report_status WHERE report_updated < '2008-04-01 00:00:00' 
```

To get the partitions, and then execute the DDL statement.

This feature just combines the two steps into one to ease the work.

**Comment by zz-jason** [comment]
@tiancaiamao Is there a similar feature in other databases?

**Comment by zhangjinpeng1987** [comment]
It' better to show the partition in a readable format when executing `show create table t`.

**Comment by tiancaiamao** [comment]
> @tiancaiamao Is there a similar feature in other databases?

AFAIK, there is no similar feature in MySQL and Oracle. @zz-jason 



> It' better to show the partition in a readable format when executing `show create table t`.

Well, maybe we can add the information in COMMENT  @zhangjinpeng1987 

```
PARTITION BY RANGE ( UNIX_TIMESTAMP(`report_updated`) ) (
  PARTITION `p0` VALUES LESS THAN (1585497600) COMMENT 'UNIX_TIMESTAMP('2020-03-30 00:00:00')',
  PARTITION `p1` VALUES LESS THAN (1585584000) COMMENT 'UNIX_TIMESTAMP('2020-03-31 00:00:00')',
  PARTITION `p2` VALUES LESS THAN (1585670400) COMMENT 'UNIX_TIMESTAMP('2020-04-01 00:00:00')',,
```

**Comment by nullnotnil** [comment]
@tiancaiamao You can annotate it without an actual comment too. [Here is a case](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_show_old_temporals) where MySQL has annotated `SHOW CREATE TABLE` in the past.

**Comment by tiancaiamao** [comment]
A potential risk of implement this feature is the +-1 range of partition pruning results.

For example, 'select * from t where dt < 2008-04-15', 
partition p0 less than '2008-04-01'
partition p1 less than '2008-05-01'

The partition pruning result is p0, p1

But for `alter table drop partition where dt < 2008-04-15`, drop partition `p1` is certainly unacceptable.

**Comment by zz-jason** [comment]
Considered the complexity and uncertainty, I think it's better to use the current method to explicitly specify the partitions to be dropped.

**Comment by mjonss** [comment]
Related to RANGE INTERVAL partitioning, that will solve similar things (needs to be tested with Timestamp / UNIX_TIMESTAMP function), see https://github.com/pingcap/tidb/issues/35683.
