### ISSUE TITLE
Restore: use sql restore will change the global config of TiDB.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#20037]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Restore data via SQL.

### 2. What did you expect to see? (Required)
The config alter-pk won't change.
<img width="568" alt="屏幕快照 2020-09-16 下午5 48 34" src="https://user-images.githubusercontent.com/5906259/93321762-237c4500-f845-11ea-8e3b-cb0da21d3caa.png">

### 3. What did you see instead (Required)
it changed.
<img width="504" alt="屏幕快照 2020-09-16 下午5 49 09" src="https://user-images.githubusercontent.com/5906259/93321737-1cedcd80-f845-11ea-80c6-d59362497293.png">

### 4. What is your TiDB version? (Required)

```
Release Version: v4.0.5
Edition: Community
Git Commit Hash: 9c1c21270001a0084dcb5d842c50e1fbea5d1fa8
Git Branch: heads/refs/tags/v4.0.5
UTC Build Time: 2020-08-28 10:07:42
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

**Comment by zimulala** [comment]
@3pointer 
Is there any reason?
The reason for not doing this at that time was to discuss with several departments, considering that it is best not to modify this variable at will.

**Comment by wjhuang2016** [comment]
It's a BR problem and it had been fixed.
