### ISSUE TITLE
`cross-join` cause unexpected errors

### ISSUE THREAD

**Issue by SE-Bin** [pingcap/tidb#20090]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When  I set the `cross-join = false` in TiDB. I found that it will raise the error " Cartesian product is unsupported ", even though having the condition of both sides tables, when having a where condition of join column with a constant.

```sql
MySQL [test]> create table t1 (id bigint,c1 varchar(10));
Query OK, 0 rows affected (0.02 sec)

MySQL [test]> create table t2 (id bigint,c1 varchar(10));
Query OK, 0 rows affected (0.01 sec)

MySQL [test]> insert into t1 values (1,'abc'),(2,'cdef');
Query OK, 2 rows affected (0.00 sec)
Records: 2  Duplicates: 0  Warnings: 0

MySQL [test]> insert into t2 values (1,'fffg'),(2,'gggh');
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

MySQL [test]> select * from t1 inner join t2 on t1.id = t2.id;
+------+------+------+------+
| id   | c1   | id   | c1   |
+------+------+------+------+
|    1 | abc  |    1 | fffg |
|    2 | cdef |    2 | gggh |
+------+------+------+------+
2 rows in set (0.01 sec)

MySQL [test]> select * from t1 inner join t2 on 1=1;
ERROR 8110 (HY000): Cartesian product is unsupported
MySQL [test]> select * from t1 inner join t2 on t1.id = t2.id where t1.id = 1;
ERROR 8110 (HY000): Cartesian product is unsupported
```
### 2. What did you expect to see? (Required)
It will not cause the error

### 3. What did you see instead (Required)
It cause the error

### 4. What is your TiDB version? (Required)
tidb_version(): Release Version: v4.0.4
Edition: Community
Git Commit Hash: c61fc7247e9f6bc773761946d5b5294d3f2699a5
Git Branch: HEAD
UTC Build Time: 2020-09-14 07:26:54
GoVersion: go1.13.11
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by lysu** [comment]
IMHO, it's cross-join in definition even if `t1.id = 1` filter both children as only one record.

but it's better to consult our planner/execution team member, PTAL  @SunRunAway

**Comment by SunRunAway** [comment]
Could we deprecate this `cross-join` option now?

@eurekaka

**Comment by zz-jason** [comment]
This config item is used to forbid the Cartesian Product on two tables. It's better to keep it.

**Comment by SunRunAway** [comment]
```
MySQL [test]> select * from t1 inner join t2 on 1=1;
ERROR 8110 (HY000): Cartesian product is unsupported
```
This case is reasonable to forbid.

---

```mysql
MySQL [test]> select * from t1 inner join t2 on t1.id = t2.id where t1.id = 1;
ERROR 8110 (HY000): Cartesian product is unsupported
```

IMO, this should not be forbidden from the user perspective, because it really has a join condition `t1.id = t2.id`.

**Comment by eurekaka** [comment]
Looks like MySQL does not have this `cross-join` option? do we have clear definition on the behavior under this option?

**Comment by SunRunAway** [comment]
Although the definition is not documented, it is well defined in [code](https://github.com/pingcap/tidb/blob/84e07a2a593b6dd9a85712f1910883e5f7281b07/planner/core/optimizer.go#L303).

So I think Case 2 is just a miss judge because of constant propagate.

**Comment by eurekaka** [comment]
I don't believe it is cost-effective to maintain whether a filter is a column equal join condition originally (e.g, before constant propagation) just for this `cross-join` check purpose. I prefer "won't fix" for this issue.
