### ISSUE TITLE
how to config TiDB to prevent OOM when retrieve data from TiDB to Hive via Sqoop

### ISSUE THREAD

**Issue by ermazi** [pingcap/tidb#20226]
tidb必定oom，请问该如何调整

- version: tidb v4.0.5

**Comment by lzmhhh123** [comment]
请问 oom 报错信息是什么？

**Comment by lzmhhh123** [comment]
What's the error message of the oom?

**Comment by ethercflow** [comment]
使用sqoop从tidb中抽取数据到hive中，内存控制不住，总是oom，请问怎么配置？

**Comment by lzmhhh123** [comment]
> 使用sqoop从tidb中抽取数据到hive中，内存控制不住，总是oom，请问怎么配置？

请问 OOM 的报错信息是什么？

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
