### ISSUE TITLE
Adapt ScanDetailV2 in KvGet and KvBatchGet Response

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#20256]
## Description

After https://github.com/tikv/tikv/issues/8756 is implemented, we can do something similar to https://github.com/pingcap/tidb/issues/20255: The `ScanDetailV2` in the response in KvGet and KvBatchGet can be utilized and outputted in these places:

- EXPLAIN ANALYZE execution info
- Slow Query
- Statements

## Score

- 1000

## Mentor(s)

- @crazycs520 
- @qw4990 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

## Learning Materials

* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by TszKitLo40** [comment]
@breeswish @crazycs520 Can I try this issue?
