### ISSUE TITLE
Error when explain a query

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#2026]
Please answer these questions before submitting your issue. Thanks!

1. What version of Go are you using (`go version`)?
1.7.3

2. What operating system and processor architecture are you using (`go env`)?
GOARCH="amd64"
GOBIN="/usr/local/go/bin"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/gopkg"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build018490638=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

3. What did you do?
If possible, provide a recipe for reproducing the error.
A complete runnable program is good.
```
drop table if exists t2, t3;
create table t2(b int);
create table t3(a int);
explain select * from t3 where a >= all (select b from t2);
```
4. What did you expect to see?

5. What did you see instead?
`[error] json: error calling MarshalJSON for type *plan.Projection: json: error calling MarshalJSON for type *plan.Selection: json: error calling MarshalJSON for type *plan.PhysicalApply: invalid character '3' after array element`

**Comment by hanfei1991** [comment]
This problem will be fix in #2063
