### ISSUE TITLE
Add support for statement "show profiles"

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tidb#2028]
![show](https://cloud.githubusercontent.com/assets/23513271/20413819/fa6a4614-ad69-11e6-8df0-83a415fadcbb.png)
可以查询  但会提示

**Comment by ngaut** [comment]
Thanks for your report @dbaspace , I translated the title of this issue to english. 
We will fix the issue later.  @shenli

**Comment by leon4py** [comment]
这个问题 还没解决, 我在5.7.1-tidb-0.9.0 还是存在这个问题, @ngaut @shenli

**Comment by shenli** [comment]
@leon4py We will fix it soon.

**Comment by shenli** [comment]
@tiancaiamao PTAL

**Comment by shenli** [comment]
@dbaspace @leon4py Please try the latest master.
