### ISSUE TITLE
有些mysql支持的类型转换 或者长度转换 能不能加一个force指令 兼容一下

### ISSUE THREAD

**Issue by heming79** [pingcap/tidb#20290]
## Feature Request

**有些mysql支持的类型转换 或者长度转换 能不能加一个force指令 兼容一下:** 
不然业务想做大表类型转换只能重建表 迁移数据就很麻烦, 有时 缩小字段类型可以优化数据库

**Comment by bb7133** [comment]
Hi, the column type change is working in progress. For example, arbitrary changes between integers have been allowed in `master` branch. You can check https://github.com/pingcap/tidb/issues/18283 for the progress.

**Comment by bb7133** [comment]
May I close this issue since this feature request have been accepted and it is WIP?

**Comment by heming79** [comment]
OK
