### ISSUE TITLE
Enable Prepared Statement cache by default

### ISSUE THREAD

**Issue by nullnotnil** [pingcap/tidb#20306]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Forked from https://github.com/pingcap/docs/pull/3960

Currently, the prepared statement cache is not enabled by default. This means that a user has to know this feature exists, and know that they need to enable it to take advantage.

**Describe the feature you'd like:**

Enable the prepared statement cache by default.

**Describe alternatives you've considered:**

(maintain current behavior)

**Teachability, Documentation, Adoption, Migration Strategy:**

This will increase the adoption of prepared statement cache.

**Comment by zz-jason** [comment]
Thanks to @nullnotnil, This feature request LGTM. @SunRunAway Prepare plan cache has passed the internal QA testing, we can enable it in the master branch and the future TiDB v5.0.x releases.

**Comment by SunRunAway** [comment]
@nullnotnil Would you like to have a pull request?

**Comment by nullnotnil** [comment]
Sure, I'll work on it.
