### ISSUE TITLE
Refine the error message for the expression index for INDEX ((CONCAT('')))

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#20319]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE t1 (col1 INT, INDEX ((CONCAT(''))));
Error 1167: The used storage engine can't index column '_V$_expression_index_0'
```

### 2. What did you expect to see? (Required)
The used storage engine cannot index the expression 'concat('')'.
### 4. What is your TiDB version? (Required)

master

**Comment by johanavril** [comment]
Hi @wjhuang2016 , I would like to work on this
