### ISSUE TITLE
Refine the error message for the expression index on auto-increment column

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#20317]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
mysql> CREATE TABLE t1 (t1_id INT NOT NULL AUTO_INCREMENT PRIMARY KEY);
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE INDEX idx1 ON t1 ((t1_id + t1_id));
ERROR 3109 (HY000): Generated column '' cannot refer to auto-increment column.
```

### 2. What did you expect to see? (Required)

Expression index 'idx1' cannot refer to an auto-increment column.

### 4. What is your TiDB version? (Required)

master

**Comment by Howie59** [comment]
i want to do this in my spare time

**Comment by wjhuang2016** [comment]
The error message should be `expression index`, not `functional index`.

**Comment by wjhuang2016** [comment]
@Howie59 Hi, I have a comment about the merged PR, could you fix it again?

**Comment by Howie59** [comment]
> @Howie59 Hi, I have a comment about the merged PR, could you fix it again?

ok, i could do this after get off work
