### ISSUE TITLE
The link under CONTRIBUTING.md in README.md is dead

### ISSUE THREAD

**Issue by felixvo** [pingcap/tidb#20395]
README.md
>Contributions are welcomed and greatly appreciated. See [CONTRIBUTING.md](https://github.com/pingcap/community/blob/master/CONTRIBUTING.md) for details on submitting patches and the contribution workflow. For more contributing information, click on the contributor icon above.

the link: https://github.com/pingcap/community/blob/master/CONTRIBUTING.md is dead.
I guess it should be:
- https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md or
- https://github.com/pingcap/community/blob/master/contributors/README.md

**Comment by francis0407** [comment]
Thanks for reporting it.

https://github.com/pingcap/tidb/pull/20328 is fixing this.

**Comment by Defined2014** [comment]
It works well on [d1ee574](https://github.com/pingcap/tidb/commit/d1ee57433a538efa1708b03de965992c8f076fbe), so close this issue.
