### ISSUE TITLE
use source filename.sql command, after a while, prompt "InfomationSchema is out of date."

### ISSUE THREAD

**Issue by shuxiang** [pingcap/tidb#2045]
I use latest tidb today, and source command to load a big sql file, after a minutes, tidb prompt something like:

Query OK, 542 rows affected (0.19 sec)

Query OK, 541 rows affected (0.20 sec)

Query OK, 540 rows affected (0.18 sec)

ERROR 1105 (HY000) at line 1020 in file: '/home/sx/soft/big_data-2016-11-21.sql': context canceled
ERROR 1105 (HY000) at line 1021 in file: '/home/sx/soft/big_data-2016-11-21.sql': InfomationSchema is out of date.
ERROR 1105 (HY000) at line 1022 in file: '/home/sx/soft/big_data-2016-11-21.sql': InfomationSchema is out of date.
ERROR 1105 (HY000) at line 1023 in file: '/home/sx/soft/big_data-2016-11-21.sql': InfomationSchema is out of date.
ERROR 1105 (HY000) at line 1024 in file: '/home/sx/soft/big_data-2016-11-21.sql': InfomationSchema is out of date.

so, what configure file and configuration I should change, make it work again? thanks

**Comment by shenli** [comment]
@shuxiang Please check the log of tidb-server. It seems that tidb-server could not access tikv-server.

**Comment by shenli** [comment]
@shuxiang Please refer to this doc: https://github.com/pingcap/docs-cn/blob/master/trouble-shooting.md

**Comment by shuxiang** [comment]
thanks，tikv is done
