### ISSUE TITLE
The system disk of the TiDB cluster is formatted, is there any possibility of recovery? Hurry!

### ISSUE THREAD

**Issue by 26Wongfox** [pingcap/tidb#20461]
File: [/overview.md](https://docs.pingcap.com/zh/tidb/stable/overview)

**Comment by ethercflow** [comment]
TiDB集群的系统盘格式化了，还有恢复的可能吗？急急急！

**Comment by lzmhhh123** [comment]
Do you mean to recover the data of tikv?

**Comment by lzmhhh123** [comment]
If only the system disk is formatted and the physical disk is not, you can try to reload the operating system and redeploy the tidb cluster environment.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
