### ISSUE TITLE
tiup command not found

### ISSUE THREAD

**Issue by zdl-king** [pingcap/tidb#20466]
按照快速上手文档指示：
第一种：使用 TiUP Playground 快速部署本地测试环境
执行tiup playground命令后提示 tiup command not found

**Comment by ran-huang** [comment]
@zz-jason PTAL.
Related docs: [TiDB 数据库快速上手指南](https://docs.pingcap.com/zh/tidb/dev/quick-start-with-tidb#%E7%AC%AC%E4%B8%80%E7%A7%8D%E4%BD%BF%E7%94%A8-tiup-playground-%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2%E6%9C%AC%E5%9C%B0%E6%B5%8B%E8%AF%95%E7%8E%AF%E5%A2%83)

**Comment by zz-jason** [comment]
have you installed `tiup` via `curl --proto '=https' --tlsv1.2 -sSf https://tiup-mirrors.pingcap.com/install.sh | sh`?
