### ISSUE TITLE
'failed Error 1105: other error: Memory limit (for query) exceeded ' Error please help  add tiflash note 

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#20508]
## Feature Request

**Is your feature request related to a problem? Please describe:**

https://asktug.com/t/topic/62913   

**Describe the feature you'd like:**

‘ failed Error 1105: other error: Memory limit (for query) exceeded: would use 9.31 GiB (attempt to allocate chunk of 1048576 bytes), maximum: 9.31 GiB execute run failed, err execute query’ Error add tiflash note

**Describe alternatives you've considered:**

Customer will easily find the issue relate to tiflash 

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by LittleFall** [comment]
After merging the two PRs in TiFlash, this error message becomes like:
```
ERROR 1105: [FLASH:Coprocessor:MemoryLimitExceeded] Memory limit (for query) exceeded: would use 4.00 KiB (attempt to allocate chunk of 4096 bytes), maximum: 1.00 B
```
