### ISSUE TITLE
JOIN is slow

### ISSUE THREAD

**Issue by shuxiang** [pingcap/tidb#2053]
I have 2 table， each table have 1Million data，order_unit.order_detail_id ref to order_detail.id, but it is not a reference key, just integer type. 
when I query like this:
select od.* from order_unit ou join order_detail od on ou.order_detail_id = od.id where ou.id > 90000 and ou.id < 100000 order by ou.id desc limit 20;

takes: 20 rows in set (7 min 0.35 sec)

query: select count(1) from order_unit; takes: 1 row in set (1.19 sec)
query: select * from order_unit order by id desc limit 20; takes: 20 rows in set (0.02 sec)

Summary: simple query is fast, count is a little slow, join is terrible.

tidb has 3 kv, 1pd, 1tidb. ubuntu running in vbox  1core 2G men.

**Comment by shenli** [comment]
@shuxiang Thanks for your feedback. May I have your schema?

**Comment by shenli** [comment]
@shuxiang Could you try "select od.* from order_unit ou join order_detail od on ou.order_detail_id = od.id where ou.id > 90000 and ou.id < 100000 order by ou.id limit 20;"

**Comment by shuxiang** [comment]
Thanks, looks like the code need some warm up time, I try the code half hour later, it takes 10 seconds. It is better but still must slower than mysql. Expect more optimization.
