### ISSUE TITLE
Support SELECT FROM TABLESAMPLE

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#20567]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, it is not easy to get some row samples without scanning the whole table.

Scenario: https://github.com/pingcap/dumpling/issues/149 needs to get a row from each region, in order to support concurrently dumping data from a table.

**Describe the feature you'd like:**

TABLESAMPLE is used in a query to deal with table sampling. For example:
```sql
select * from t TABLESAMPLE REGIONS;
```
The above statement scans all of the table regions and returns 1 row from each of them.

PostgreSQL: https://www.postgresql.org/docs/current/tablesample-method.html
SQL Server: https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2008-r2/ms189108(v=sql.105)

**Describe alternatives you've considered:**

- We can ``show table `t` regions;`` and use the builtin function `tidb_decode_key()` to decode the `start_key` or `end_key` of a region, but in some cases, the keys cannot be decoded.

- ``select * from `t` order by rand() limit n;`` returns random rows, but a table full scan is required.

**Teachability, Documentation, Adoption, Migration Strategy:**

This feature can be implemented by scanning one row from the `start_key` of each table region, and aggregate them together.

In the future, TiDB can support more `TABLESAMPLE` clauses:
- `select * from t TABLESAMPLE (n ROWS);`
- `select * from t TABLESAMPLE (n PERCENT);`

**Comment by kennytm** [comment]
In both PostgreSQL and MS SQL Server, the `TABLESAMPLE` clause can only appear in a SELECT statement of a table. However in the SQL:2003 standard, the TABLESAMPLE clause can [appear almost anywhere a table source was expected](https://wiki.postgresql.org/wiki/TABLESAMPLE_Implementation):

```sql
DELETE FROM foo TABLESAMPLE SYSTEM (1);               -- ಠ_ಠ
UPDATE foo TABLESAMPLE SYSTEM (1) SET col1 = 'col1';  -- ಠ_ಠ
```

I suggest we don't support these syntax as they make no sense, and I can't find any DBMS implementing it. 

<details><summary>The clause syntax for variant dialects:</summary>

```ebnf
(* SQL standard since 2003 *)
sample_clause = "TABLESAMPLE" ( "BERNOULLI" | "SYSTEM" ) '(' number ')' 
                [ "REPEATABLE" '(' number ')' ];

(* PostgreSQL 9+ *)
(* https://www.postgresql.org/docs/13/sql-select.html *)
sample_clause = "TABLESAMPLE" identifier '(' argument [',' ...] ')' 
                [ "REPEATABLE" '(' number ')' ];

(* MS SQL *)
(* https://docs.microsoft.com/en-us/sql/t-sql/queries/from-transact-sql?view=sql-server-ver15 *)
sample_clause = "TABLESAMPLE" [ "SYSTEM" ] '(' number [ "PERCENT" | "ROWS" ] ')' 
                [ "REPEATABLE" '(' number ')' ];

(* Oracle *)
(* https://docs.oracle.com/en/database/oracle/oracle-database/20/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6 *)
sample_clause = "SAMPLE" [ "BLOCK" ] '(' number ')' 
                [ "SEED" '(' number ')' ];

(* Snowflake *)
(* https://docs.snowflake.com/en/sql-reference/constructs/sample.html *)
sample_clause = ( "TABLESAMPLE" | "SAMPLE" ) [ "BERNOULLI" | "ROW" | "SAMPLE" | "BLOCK" ] '(' number [ "ROWS" ] ')'
                [ ( "REPEATABLE" | "SEED" ) '(' number ')' ];
```

</details>

MySQL does not support TABLESAMPLE yet, but [work has been done in the backend](https://dev.mysql.com/worklog/task/?id=9127) to support sampling. 

----

Assuming we don't require Oracle compatibility, for best compatibility, our syntax would look like a mix of PostgreSQL and SQL Server:

```ebnf
sample_clause = "TABLESAMPLE" [ "BERNOULLI" | "SYSTEM" ] '(' number [ "PERCENT" | "ROWS" ] ')'
                [ "REPEATABLE" '(' number ')' ]
```

now the question is how do the sampling method we actually want fit in:

```sql
-- this doesn't make sense at all.
SELECT * FROM tbl TABLESAMPLE REGIONS (33.3 PERCENT);

-- may work, but not much better than using LIMIT directly.
-- and need to consider what to do when the input number of rows exceeds the number of regions
-- though the number is an approximation anyway.
SELECT * FROM tbl TABLESAMPLE REGIONS (5 ROWS);

-- PostgreSQL's syntax actually requires at least one argument, so this isn't really a compatibility solution
-- plus for this we need to consider meaning of TABLESAMPLE BERNOULLI ();
SELECT * FROM tbl TABLESAMPLE REGIONS ();

-- ...?
SELECT * FROM tbl TABLESAMPLE REGIONS (NULL);
SELECT * FROM tbl TABLESAMPLE REGIONS (MAXVALUE);

-- create a special case for REGIONS, not treating it as a sampling_method
SELECT * FROM tbl TABLESAMPLE REGIONS;
```

----

we should ensure applying a TABLESAMPLE to a view results in an error.

```sql
CREATE VIEW v AS ...;

SELECT * FROM v TABLESAMPLE ...;
-- on PostgreSQL: 0A000 TABLESAMPLE clause can only be applied to tables and materialized views

```

----

<details><summary>Parser test cases</summary>

Positive syntax cases:

```sql
select * from tbl tablesample system (50);
select * from tbl tablesample system (50 percent);
select * from tbl tablesample system (49.9 percent);
select * from tbl tablesample system (120 row);
select * from tbl tablesample bernoulli (50);
select * from tbl tablesample (50);
select * from tbl tablesample (50) repeatable (123456789);
select * from tbl as a tablesample (50);
select * from tbl `tablesample` tablesample (50);
select * from tbl1 tablesample (10), tbl2 tablesample (20);
select * from tbl1 a tablesample (10) join tbl2 b tablesample (20) on a.id <> b.id;
select * from tbl1 tablesample (50) where id > 20;
select * from tbl tablesample ('34'); -- cast the string to a number
select * from tbl tablesample (0 percent);
select * from tbl tablesample (0 rows); -- mssql rejects this but why not
select * from tbl tablesample (100 percent);

-- optional: 
select * from tbl tablesample (33.3 + 44.4);
select * from tbl tablesample (33.3 + 44.4 percent);
select * from tbl tablesample (33 + 44 rows);
select * from tbl tablesample (33 + 44 rows) repeatable (55 + 66);

select * from tbl tablesample (200); -- syntax ok, but runtime error (percent > 100)
select * from tbl tablesample (-10); -- syntax ok, but runtime error (percent < 0)
select * from tbl tablesample (null); -- syntax ok, but runtime error (percent cannot be cast to number)
select * from tbl tablesample (33.3 rows); -- syntax ok, but runtime error (rows is not integer)
select * from tbl tablesample (-4 rows); -- syntax ok, but runtime error (negative rows)
select * from tbl tablesample (50) repeatable ('ssss'); -- syntax ok, but runtime error (seed is not integer)
```

Negative syntax cases:

```sql
select * from tbl tablesample system(50) a;
select * from tbl where id > 20 tablesample system(50);
select * from (select * from tbl) a tablesample system(50);
select * from tbl tablesample system(50) tablesample system(50);
select * from tbl tablesample system(50, 50); -- accepted in postgresql but doesn't worth the generalization.
select * from tbl tablesample dhfksdlfljcoew(50);
select * from tbl tablesample system;
select * from tbl tablesample system (33) repeatable;
```

</details>

**Comment by tangenta** [comment]
@zz-jason @nullnotnil PTAL

**Comment by zz-jason** [comment]
> Scenario: pingcap/dumpling#149 needs to get a row from each region, in order to support concurrently dumping data from a table.

seems it's hard to write a query based on `tablesample`, maybe one of the feasible solution is:

1. get region boundaries 
2. construct a SQL to decode all the region boundaries to row data
3. construct a SQL to retrieve all the rows indicated by the region boundaries

**Comment by kennytm** [comment]
The issue with `tidb_decode_key` is that 

1. the region boundary is not necessarily a valid key, maybe just a partial prefix, which will fail `tidb_decode_key`.

2. collated strings are stored in the key as `weight_string()` (the sort key) rather than the string itself, and the `weight_string()` is generally irreversible.

3. even if we don't decode `weight_string()`, the optimizer does not recognize `weight_string(col) >= x'abcdef'`, so this will result in an Index/Table Full Scan rather than an Index Range Scan. TBH if we have to perform a Full Scan we can just use the standard `ntile()` window function instead, at least it's portable 🤷.

----

I don't see why `TABLESAMPLE REGIONS` (*not* the standard probability-based sampling!) cannot fulfill the requirement. Dumpling will perform this query to get the region boundary values:

```sql
select col1, col2, col3 from tbl tablesample regions;
```

with this we'll obtain tuples like `(v001, v002, v003)`, `(v101, v102, v103)`, `(v201, v202, v203)` etc which are decoded from the *value* of the first KV pair of each data region. Then we dump all values with

```sql
select * from tbl where (v101, v102, v103) <= (col1, col2, col3) and (col1, col2, col3) < (v201, v202, v203);
```

**Comment by nullnotnil** [comment]
I think this is a useful extension to MySQL. In terms of corresponding syntax, @kennytm is correct in that there is an internal sampling API but it is not exposed via SQL syntax.  The closes thing in terms of syntax is [explicit partition selection](https://dev.mysql.com/doc/refman/8.0/en/partitioning-selection.html):

```sql
mysql> SELECT
    ->     e.id AS 'Employee ID', CONCAT(e.fname, ' ', e.lname) AS Name,
    ->     s.city AS City, d.name AS department
    -> FROM employees AS e
    ->     JOIN stores PARTITION (p1) AS s ON e.store_id=s.id
    ->     JOIN departments PARTITION (p0) AS d ON e.department_id=d.id
    -> ORDER BY e.lname;
+-------------+---------------+-----------+------------+
| Employee ID | Name          | City      | department |
+-------------+---------------+-----------+------------+
|          14 | Fred Goldberg | Bellingen | Delivery   |
|           5 | Mary Jones    | Nambucca  | Sales      |
|          17 | Mark Morgan   | Bellingen | Delivery   |
|           9 | Andy Smith    | Nambucca  | Delivery   |
|           8 | June Wilson   | Bellingen | Sales      |
+-------------+---------------+-----------+------------+
5 rows in set (0.00 sec)
```
> In both PostgreSQL and MS SQL Server, the `TABLESAMPLE` clause can only appear in a SELECT statement of a table. However in the SQL:2003 standard, the TABLESAMPLE clause can [appear almost anywhere a table source was expected](https://wiki.postgresql.org/wiki/TABLESAMPLE_Implementation):
> 
> ```sql
> DELETE FROM foo TABLESAMPLE SYSTEM (1);               -- ಠ_ಠ
> UPDATE foo TABLESAMPLE SYSTEM (1) SET col1 = 'col1';  -- ಠ_ಠ
> ```
> 
> I suggest we don't support these syntax as they make no sense, and I can't find any DBMS implementing it.

I agree here. We can always add it later if there is a use case discovered which supports it.

> -- PostgreSQL's syntax actually requires at least one argument, so this isn't really a compatibility solution
> -- plus for this we need to consider meaning of TABLESAMPLE BERNOULLI ();
> SELECT * FROM tbl TABLESAMPLE REGIONS ();

I like the parens because it makes it easier to differntiate from a table alias. My understanding in the explicit partition selection case is that they are required. But the use case is a little bit different in that partition selection is very binary. I don't mind if you implement differently too.
