### ISSUE TITLE
Parallelize stream aggregation executors by using shuffle executors

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#20651]
## Description

In this PR(https://github.com/pingcap/tidb/pull/14238), we introduce the shuffle executor.
Like https://github.com/pingcap/tidb/issues/14441, we may use this shuffle executor to implement parallel stream aggregation by nesting some sort and stream-aggg executors into a shuffle executor:
```
ShuffleExec
    - StreamAgg
        - Sort
    - StreamAgg
        - Sort
    ...
``` 
It can utilize more CPU resources to get better performance.

- [x] Introduce a new variable to control concurrency
- [x] Support `shuffle + stream_agg` and add some tests and benchmarks simply
- [ ] Add more tests and benchmarks about `shuffle + stream_agg`
- [x] Support `range_spliter`

## Score

6600

## Mentor

@qw4990 (Slack ID: Zhang Yuanjia)

## Recommend Skills

- Golang

**Comment by SunRunAway** [comment]
Tips: https://github.com/pingcap/tidb/issues/9244#issuecomment-686237166

**Comment by qw4990** [comment]
> Tips: [#9244 (comment)](https://github.com/pingcap/tidb/issues/9244#issuecomment-686237166)

Thanks, @SunRunAway . Here is [a demo version of this feature](https://github.com/pingcap/tidb/compare/master...SunRunAway:shuffle-sort-agg), PTAL @JinLingChristopher

**Comment by JinLingChristopher** [comment]
thanks for your work, I would help me a a lot.
