### ISSUE TITLE
Support conversion from Time types to others

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#20661]
### Background
With the development of the implementation of column type change, we have broken the process into two phases.

1. implement the architecture and column type change between the same type. [phase 1](https://github.com/pingcap/tidb/issues/19116)
2. implement the column type change between the different types and some TODO lists. [phase 2](https://github.com/pingcap/tidb/issues/19939)

### Problem
Time Types includes:

- Year
- Date/Datetime
- Time/Timestamp
- ...

Support conversion from Time types to others
For example: 

- change Year to String
- change Time to Int
- ...

### Solution
Generally speaking, these changes may all need the reorganize the data, you can refer to the previous issue in phase 1 for the implementation of architecture details. 

In the process of your development, maybe you should also take the SQL Mode into consideration, handling some warnings or errors.

For time type special, you need to take Time Zone into consideration (eg: timestamp type).

### Score

- 300

### Mentor

- AilinKid

## Recommended Skills

[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by AilinKid** [comment]
sig/DDL

**Comment by zz-jason** [comment]
@AilinKid no need to create feature requests related to column type change since https://github.com/pingcap/tidb/issues/19939 is accepted. Please create these issues as development tasks instead.

I'm going to remove this issue from the feature request list, let's treat it as a normal development task.
