### ISSUE TITLE
Support default partition for list (columns) partition table

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#20679]
## Feature Request

**Is your feature request related to a problem? Please describe:**

N/A

**Describe the feature you'd like:**

The default partition of list partition table is from [ORACLE](https://docs.oracle.com/database/121/VLDBG/GUID-8928C3B0-2F83-4213-B765-EFBBF0372F64.htm), MYSQL doesn't support this, but it is a very useful feature.

Here is an example, I want to create a list partition table, the list partition depends on the year.

```sql
create table t (a date) partition by list (year(a)) (
    partition p0 values in (2020));
```

But I execute the following SQL will fail:

```sql
> insert into t values ('2019-10-27 17:36:10');
(1526, 'Table has no partition for value 2019')
```  

I know the upper behavior is expected, So I want to add a default partition to store the data that doesn't match the other partitions. Such as:

```sql
create table t (a date) partition by list (year(a)) (
    partition p0 values in (2020), 
    partition p1 values in (default));
```

Then the following SQL will be successfully inserted into the default partition.

```sql
insert into t values ('2019-10-27 17:36:10'),('2021-10-27 17:36:10'),('2000-10-27 17:36:10');
```
```
------------------------------------------------------------------------------------------------
```
**Another feature-request is**, should we support the ORACLE list partition syntax? Some customers are using ORACLE syntax to test the list partition.

**Describe alternatives you've considered:**

The upper features aren't hard to implement, I already implemented this here: https://github.com/bb7133/tidb/pull/33

**Teachability, Documentation, Adoption, Migration Strategy:**

N/A

**Comment by crazycs520** [comment]
@zz-jason PTAL

**Comment by zz-jason** [comment]
I noticed that there is a worklog in MySQL which discusses to support the `default` list partition: [WL#5781: DEFAULT/catch-all partition for LIST partitioning](https://dev.mysql.com/worklog/task/?id=5781), the feature request in MySQL is [Bug #50566](https://bugs.mysql.com/bug.php?id=50566).

The Syntax is like Oracle:


```sql
CREATE TABLE t (a INT, b TEXT)
PARTITION BY LIST (a)
(PARTITION p0 VALUES IN (1,5,6,7),
 PARTITION p1 VALUES IN (3,4,9),
 PARTITION pDefault VALUES IN (DEFAULT));
```

Please note:

> When using a DEFAULT partition, it will not longer be possible to ADD a partition, but one must instead REORGANIZE the DEFAULT partition, just like MAXVALUE partition in RANGE partitioning.

**Comment by zz-jason** [comment]
> Another feature-request is, should we support the ORACLE list partition syntax? Some customers are using ORACLE syntax to test the list partition.

@crazycs520 I think it's better to keep the MySQL syntax since we are claimed to be MySQL compatible. BTW, it's better to discuss only one feature request at one issue.

**Comment by zz-jason** [comment]
This feature request LGTM
