### ISSUE TITLE
"float unsigned" should not be allowed when creating table

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#2072]
"float unsigned" is not a valid type.

**Comment by zimulala** [comment]
The executed result on MySQL are as follows：
mysql> create table t1(a float unsigned);
Query OK, 0 rows affected (0.01 sec)

I execute this statement on MySQL use two version: `Server version: 5.7.9 MySQL Community Server (GPL)` and `Server version: 5.6.33-0ubuntu0.14.04.1-log (Ubuntu)`
