### ISSUE TITLE
Schema Version corresponds to the logic for row data value

### ISSUE THREAD

**Issue by SoulSong** [pingcap/tidb#20736]
## General Question
主要想了解在进行column变更时，schema version如何与数据行进行对应更新，及其流程。当前已了解相关内容如下：
**Add Column 操作**
Add Column 整个操作不关心表的数据行内容，其整个操作只需要进行 5 个状态的变更即可。此操作前后做了两个优化： 
新加列的 Default Value 是一个空值，那么就不需要实际的去填充。之后对此列的读取时，从 TiKV 返回的列值为空时，查看此列的元信息，如果它是 NULL 约束则可直接返回空值（这逻辑会在 Coprocess 处理）。
 新加列的 Default Value 的值为非空的情况下，也不用将 Default Value 存储到 TiKV，只需将此默认值存到一个 schema 的字段（Original Default Value）中。在之后做读取操作时，如果发现 TiKV 返回此列的的值为空，且这个 schema 字段中的值为非空，那么将此字段中的值填充给这一列，然后返回（这逻辑会在 Coprocess 处理）。

**Drop Column 操作**
Drop Column 也只要修改 table 的元信息，把 table 元信息中对应的要删除的 column 删除。drop Column 不会删除原有 table 数据行中的对应的 Column 数据，在 decode 一行数据时，会根据 table 的元信息来 decode。其整个过程仍然不涉及数据行的变更，而是在读取数据时的 decode 操作下根据 table 元数据信息进行具体的数据变更处理。

**Schema元数据信息**
TiDB 中每个 Database 和 Table 都有元信息，也就是其定义以及各项属性。这些信息也需要持久化，TiDB 将这些信息也存储在了 TiKV 中。
每个 Database/Table 都被分配了一个唯一的 ID，这个 ID 作为唯一标识，并且在编码为 Key-Value 时，这个 ID 都会编码到 Key 中，再加上 m_ 前缀。这样可以构造出一个 Key，Value 中存储的是序列化后的元信息。
除此之外，TiDB 还用一个专门的 (Key, Value) 键值对存储当前所有表结构信息的最新版本号。这个键值对是全局的，每次 DDL 操作的状态改变时其版本号都会加 1。目前，TiDB 把这个键值对持久化存储在 PD Server 中，其 Key 是 "/tidb/ddl/global_schema_version"，Value 是类型为 int64 的版本号值。TiDB 参考了 Google F1 的 Online Schema 变更算法，有一个后台线程在不断地检查 PD Server 中存储的表结构信息的版本号是否发生变化，并且保证在一定时间内一定能够获取版本的变化。

**数据行存储格式**
每行数据按照如下规则编码成 (Key, Value) 键值对：
```
Key:   tablePrefix{TableID}_recordPrefixSep{RowID}
Value: [col1, col2, col3, col4]
```

## 疑问
当前算法实现下，数据行value和schema version的对应关系比较复杂，且数据读取时的decode操作均需要进行数据行内容与对应schema version下的元数据信息比对，然后进行对应的数据操作，该过程对于单行数据处理效率上看不出太多的损耗，但当出现批量提取百万行数据时，其比对变更过程势必带来较大的性能开销。且其假设保证在一定时间内一定能够获取版本的变化，在频繁进行column场景下具体的表现不是很了解。但如果从存储value出发，将schema version与value绑定，类似规则编码如下：
```
Key:   tablePrefix{TableID}_recordPrefixSep{RowID}
Value: n[col1, col2, col3, col4]
```
其主要变化就是在真实数据数组前面加了一个schema-version信息，故如果将所有的表进行分离version管控会更好。在实际数据读取时，其比对过程仅仅是n与version的比对，仅当不一致时需要进行数据变更处理，且同时能够支持多版本schema。

不知道这个方式是不是有可行性？

**Comment by wjhuang2016** [comment]
@SoulSong Hi, Thanks for your advice. 
1. CockroachDB separates the schema version for tables while TiDB doesn't.  I think there are some advantages to separate them, for example, more parallelism. But there still some corner cases to consider, for example, rename table. We will investigate it more carefully and decide whether to separate them.
2. I don't think storing scheme version in row value is a good idea. A problem is, it's not easy to get the specified scheme for the row record. 
3. After implementing https://github.com/pingcap/tidb/blob/master/docs/design/2018-07-19-row-format.md, I think the decode operation performance is acceptable now.

**Comment by SoulSong** [comment]
@wjhuang2016 Thank you for your reply.
