### ISSUE TITLE
PLEASE SHARE MARATHON JSON CONFIG FILE FOR PD,TIKV AND TIDB TO DEPLOY ON MESOS CLUSTER

### ISSUE THREAD

**Issue by spf913** [pingcap/tidb#20831]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
please share marathon json config file for a complete tidb cluster (3 pd, 3 tikv and 1 tidb) (container version) to deploy tidb cluster on mesos cluster or DC/OS with persistent data volume (tidb,tikv,pd).

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by bb7133** [comment]
Hi @kamaljitsinghsikhamazon ,

For now, we don't officially provide support for deploying TiDB on Mesos, most of the TiDB users use K8s instead. So far as I know, a few customers did deploy TiDB on Mesos but the details are not public.

Can you try TiDB on K8s instead? Or there are some frameworks that 'mock' K8s on Mesos like https://github.com/mesosphere but I don't know much about it.

**Comment by spf913** [comment]
@bb7133 can you pls just help me little bit to contribute??
https://github.com/pingcap/tidb-operator/issues/3455#issuecomment-723711705
