### ISSUE TITLE
use  order by sorts and pagination，  get error data

### ISSUE THREAD

**Issue by dhw-daniel** [pingcap/tidb#20834]
tidb_version()    is   4.0

**Comment by bb7133** [comment]
Hi @dhw-daniel , can you provide some minimal data/SQLs to reproduce the error?

**Comment by dhw-daniel** [comment]
I can get the data. When I sort by primary key and paginate, the data is correct. When I use other fields to sort and paginate, the data is wrong。I'm not sure if there's something wrong with my DB ORM。How can I solve this problem

**Comment by bb7133** [comment]
Sorry but I need more detailed information about your issue, how the data is 'incorrect'? What is the expected data? Is there any way to reproduce it for the others?

For example, this issue https://github.com/pingcap/tidb/issues/20869 provides a sequence of SQLs, expected results and incorrect results, so we can easily diagnosis it and fix it. Can you give some instructions like that?

**Comment by dhw-daniel** [comment]
I found the cause of the error. When I sorted and paginated using sorts, I selected ID and name to get error data. When I select id, sort gets the correct data

this error json data
```
{"code":0,"msg":"success","data":{"list":[{"id":56,"name":"[\"首页\",\"home\"]"},{"id":52,"name":"[\"天泰影院\",\"video\"]"},{"id":53,"name":"[\"电视直播\",\"tv\"]"},{"id":30062,"name":"[\"叫醒服务\",\"alarm\"]"},{"id":30064,"name":"[\"精致生活\",\"life\"]"},{"id":55,"name":"[\"天泰商城\",\"mall\"]"},{"id":30061,"name":"[\"音乐天地\",\"music\"]"},{"id":30063,"name":"[\"智能控制\",\"smart\"]"},{"id":54,"name":"[\"酒店服务\",\"Hotel Service\"]"},{"id":51,"name":"[\"商旅出行\",\"travel\"]"}],"page":"1","pageSize":"10","totalCount":12}}

```
this correct  json data
`{"code":0,"msg":"success","data":{"list":[{"id":56,"sorts":8},{"id":52,"sorts":7},{"id":53,"sorts":6},{"id":30070,"sorts":0},{"id":30069,"sorts":0},{"id":30064,"sorts":0},{"id":30063,"sorts":0},{"id":30062,"sorts":0},{"id":30061,"sorts":0},{"id":55,"sorts":0}],"page":"1","pageSize":"10","totalCount":12}}`

I can't use select* . this is bug?

**Comment by SunRunAway** [comment]
@dhw-daniel Could you provide the table schema and the SQL?

**Comment by XuHuaiyu** [comment]
No response for a long time.
I'll close this issue.
Feel free to reopen this if you need any further help.
