### ISSUE TITLE
Support running Harmmerdb on TiDB

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#2084]
See: http://www.hammerdb.com/
HammerDB is an open source database load testing and benchmarking tool for Oracle Database, Microsoft SQL Server, IBM DB2, TimesTen, MySQL, MariaDB,  PostgreSQL, Postgres Plus Advanced Server, Greenplum, Redis, Amazon Aurora and Redshift and Trafodion SQL on Hadoop.

**Comment by nullnotnil** [comment]
I downloaded and took a look at this. hammerdb uses mysql's stored procedures, which makes it very difficult to port to TiDB.

I am going to close this for now as won't fix, since stored procedures are not on the current plan.
