### ISSUE TITLE
Change read slow-log file module to concurrent

### ISSUE THREAD

**Issue by jyz0309** [pingcap/tidb#20890]
## Description
Currently, reading the slow-log is a serial operation, which greatly reduces the efficiency of the slow log query, so we can change the read operation to a concurrent mode to speed up it.
IMO, We can try to use multiple threads to read one slow log file, which I think will greatly speed up the slow log file reading speed.

**You can see `/executor/slow_query.go` to know more.**

## Score

- 300

## Mentor

- @jyz0309
- @crazycs520 

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills

* Go

## Learning Materials
* [慢查询文档](https://pingcap.com/docs-cn/dev/how-to/maintain/identify-abnormal-queries/identify-slow-queries/)
* use `slowQueryRetriever` search in TiDB code to see related implemention code.
* Chinese: [TiDB 精选技术讲解文章](https://github.com/pingcap/presentations/blob/master/hackathon-2019/reference-document-of-hackathon-2019.md)
* English: [Awesome-Database-Learning](https://github.com/pingcap/awesome-database-learning)

**Comment by jyz0309** [comment]
This pr has been idle for too long, so I will pick up and complete it.

**Comment by hidehalo** [comment]
> This pr has been idle for too long, so I will pick up and complete it.

Hi @jyz0309 , have you working on it?

**Comment by jyz0309** [comment]
> > This pr has been idle for too long, so I will pick up and complete it.
> 
> Hi @jyz0309 , have you working on it?

sry to response too late... When I try to fix this issue, I find that read one slog-log file by multi goroutine can not make the “reading file” module faster because of the IO limit. But if you want to try, welcome)

**Comment by jyz0309** [comment]
> > This pr has been idle for too long, so I will pick up and complete it.
> 
> Hi @jyz0309 , have you working on it?

@hidehalo sry to response too late... When I try to fix this issue, I find that read one slog-log file by multi goroutine can not make the “reading file” module faster because of the IO limit. But if you want to try, welcome)

**Comment by hidehalo** [comment]
> > > This pr has been idle for too long, so I will pick up and complete it.
> > 
> > 
> > Hi @jyz0309 , have you working on it?
> 
> @hidehalo sry to response too late... When I try to fix this issue, I find that read one slog-log file by multi goroutine can not make the “reading file” module faster because of the IO limit. But if you want to try, welcome)

Thx, I'd like to take a try.

**Comment by hidehalo** [comment]
@jyz0309 Do you have a slack account in TiDB community? I have to take a discuss to you plz.

**Comment by jyz0309** [comment]
> @jyz0309 Do you have a slack account in TiDB community? I have to take a discuss to you plz.

Alkaid Jiang~
