### ISSUE TITLE
I got warning: get timestamp too slow

### ISSUE THREAD

**Issue by will835559313** [pingcap/tidb#2097]
I deploy tidb on centos7 all in one node by reading this article https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md#standalone-cluster-deployment

I got a warning : get timestamp too slow
tow error : [error] [ddl] SetValidity, schema validity is false, lastSuccTS:387990267072086017

and when I use mysql client to connect tidb import some data than mysqldump from mysql , I got this error: ERROR 1105 (HY000) at line 420 in file: '/server/software/sdb_b2c_members.sql': InfomationSchema is out of date.

this is the log from pd

2016/11/25 17:19:53 tso.go:122: [warning] clock offset: 201.859059ms, prev: 2016-11-25 17:19:52.868617921 +0800 CST, now: 2016-11-25 17:19:53.07047698 +0800 CST
2016/11/25 17:19:53 tso.go:122: [warning] clock offset: 491.182246ms, prev: 2016-11-25 17:19:53.07047698 +0800 CST, now: 2016-11-25 17:19:53.561659226 +0800 CST
2016/11/25 17:19:53 tso.go:126: [warning] invalid physical timestamp, prev: 2016-11-25 17:19:53.561659226 +0800 CST, now: 2016-11-25 17:19:53.561900752 +0800 CST, re-update later
2016-11-25 17:19:53.680096 W | etcdserver: apply entries took too long [146.04305ms for 1 entries]
2016-11-25 17:19:53.710747 W | etcdserver: avoid queries with large range/delete range!
2016-11-25 17:20:00.761738 W | etcdserver: apply entries took too long [118.253557ms for 1 entries]
2016-11-25 17:20:00.761773 W | etcdserver: avoid queries with large range/delete range!
2016-11-25 17:20:00.938928 W | etcdserver: apply entries took too long [171.67921ms for 1 entries]
2016-11-25 17:20:00.938951 W | etcdserver: avoid queries with large range/delete range!
2016-11-25 17:20:08.578604 W | etcdserver: apply entries took too long [156.535257ms for 1 entries]
2016-11-25 17:20:08.578634 W | etcdserver: avoid queries with large range/delete range!
2016/11/25 17:20:08 tso.go:122: [warning] clock offset: 361.082481ms, prev: 2016-11-25 17:20:08.211681046 +0800 CST, now: 2016-11-25 17:20:08.572763527 +0800 CST
2016-11-25 17:20:12.073173 W | etcdserver: apply entries took too long [25.271654ms for 1 entries]
2016-11-25 17:20:12.073198 W | etcdserver: avoid queries with large range/delete range!
2016/11/25 17:20:23 conn.go:75: [error] read request message err EOF
2016-11-25 17:20:26.627528 W | etcdserver: apply entries took too long [64.413632ms for 1 entries]
2016/11/25 17:20:26 tso.go:122: [warning] clock offset: 184.163556ms, prev: 2016-11-25 17:20:26.409493309 +0800 CST, now: 2016-11-25 17:20:26.593656865 +0800 CST
2016-11-25 17:20:26.627659 W | etcdserver: avoid queries with large range/delete range!
2016/11/25 17:20:29 tso.go:126: [warning] invalid physical timestamp, prev: 2016-11-25 17:20:29.535929191 +0800 CST, now: 2016-11-25 17:20:29.53600628 +0800 CST, re-update later
2016/11/25 17:20:29 tso.go:126: [warning] invalid physical timestamp, prev: 2016-11-25 17:20:29.657106527 +0800 CST, now: 2016-11-25 17:20:29.657619445 +0800 CST, re-update later
2016-11-25 17:20:34.402114 W | etcdserver: apply entries took too long [297.675748ms for 1 entries]
2016-11-25 17:20:34.402151 W | etcdserver: avoid queries with large range/delete range!
2016/11/25 17:20:34 util.go:202: [warning] txn runs too slow, resp: &{cluster_id:2037210783374497686 member_id:13195394291058371180 revision:674 raft_term:2  true [response_put:<header:<revision:674 > > ]}, err: <nil>, cost: 1.838928603s
2016/11/25 17:20:34 tso.go:122: [warning] clock offset: 2.061606613s, prev: 2016-11-25 17:20:32.459558159 +0800 CST, now: 2016-11-25 17:20:34.521164772 +0800 CST

I see the log string like '2016/11/25 17:25:15 leader.go:195: [info] PD cluster leader pd is ready to serve '  in the pd log many times

what does it mean? please help me

**Comment by siddontang** [comment]
Hi @will835559313 , thanks for your report. 

I see that you deploy whole TiDB components in one machine, but it seems that your machine has a high load and the TiDB cluster can't supply normal service.

The standalone deployment is only for user first try, you can do some simple operations, but if you want to do more test and benchmark, I suggest deploying TiDB cluster in multi machines :-)

**Comment by will835559313** [comment]
thank you for help me.
When I use 3 virtual machines( every virtual machines has 4 cores and 2G ram) to deploy tidb, I also got that problem.  what should I do ?

**Comment by siddontang** [comment]
Hi @will835559313 

Seem that you run PD + TiKV in one VM too, the load is still high. 
The warning message `get timestamp too slow` is not serious, just shows that your TiDB getting TSO from PD slow (maybe network slow, or machine load high, etc..), but the cluster can still work well, you can even ignore this waring if possible. 

What I care more is `InfomationSchema is out of date`, this error is much serious, which means your TiKV is very busy and can't work. 

Btw, we prefer using more powerful machines to test the cluster, see https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md.

**Comment by will835559313** [comment]
ok,thank you.
I will try do a test on aliyun use 6 ecs machine(4 cores, 16G ram)

**Comment by tiancaiamao** [comment]
@zimulala Please check the git version of the binary we published and verify whether it use a version with bug ?

**Comment by zimulala** [comment]
It's not friendly to user but not a bug. And It's more correct. Now this be resolved after #2094 #2110 @tiancaiamao
