### ISSUE TITLE
ProvideRun TiDB with Docker (multiple nodes)

### ISSUE THREAD

**Issue by sjmudd** [pingcap/tidb#2102]
The [Quick Start](https://github.com/pingcap/tidb/blob/master/docs/QUICKSTART.md) page shows you how to run TiDB via docker on a single container, but real-life usage is going to need us to run this on more than one node (otherwise we might as well just use MySQL).

It would be quite nice if you can provide an example setup with TiDB split over several docker containers. 
* That allows us to check the exact required configuration needed in a more realistic setup.
* I would expect that it should then be reasonably straight forward to add another node and see how TiDB behaves when such a node is added
* Further more simulating failure of a node should be straightforward with this setup just by stopping one of the containers.

For such a test case storage is not really important. This is just for testing but it gives a newcomer an easier way to start to trying out TiDB in a throw-away environment.

**Comment by ngaut** [comment]
Thank you for your valuable advice. @sjmudd 
I added a todo label to this issue. 
We are adding more and more documents, they are coming soon 😄 
We will let you know of any further related documents.

**Comment by shenli** [comment]
@sjmudd I guess you need this doc: https://github.com/pingcap/docs/blob/master/op-guide/docker-deployment.md#multi-nodes-deployment

**Comment by siddontang** [comment]
Thanks for your report @sjmudd 

The multiple docker deployment document is here https://github.com/pingcap/docs/blob/master/op-guide/docker-deployment.md, seem that we should let user find cluster deployment with binary and docker more easily in the quick start. /cc @shenli 

Adding/Removing PD/TiKV/TiDB node is easy, see https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md#addremove-node-dynamically, but now the guide has not been completed, we will improve it and add examples later.

**Comment by AkihiroSuda** [comment]
Docker 1.13 ([RC available](https://github.com/docker/docker/releases)) supports built-in "Docker Compose on Swarm-mode" feature
https://blog.nimbleci.com/2016/11/17/whats-coming-in-docker-1-13/#deploy-stacks-from-a-docker-compose-file

It would be great if we can use TiDB with that feature

**Comment by siddontang** [comment]
Cool @AkihiroSuda 

I think we can try it in CI and test first. @iamxy

**Comment by morgo** [comment]
We recently released a [Kubernetes Operator](https://github.com/pingcap/tidb-operator), which makes it easier to deploy TiDB across multiple nodes.

As Shen Li mentioned, we have also documented a [multi-node Docker](https://pingcap.com/docs/op-guide/docker-deployment/) deployment, although I suspect over time the Kubernetes deploy will become more popular :-)

I am going to close this issue for now, but please feel free to re-open it if you have any follow up questions.  Thanks!
