### ISSUE TITLE
txn:make amended transaction semantic compatible

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#21069]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The transaction [amend](https://github.com/pingcap/tidb/projects/50) may indrocude some incompatilities, we need to solve these issues for specific amend type. 

Issues like:
- https://github.com/pingcap/tidb/issues/20912. For add column amend type, since the newest value on the added column will not be recorded in the amended transaction memory buffer, the amend will overwrite the newest written data, which causes lost update.

**Describe the feature you'd like:**

Make the amended transaction semantic compatible.

**Describe alternatives you've considered:**

We need to consider if memory buffer amend is needed under certain circumstances. Also, we need to evaluate the risk and benefit.

**Teachability, Documentation, Adoption, Migration Strategy:**

Check the [amend](https://github.com/pingcap/tidb/projects/50) project and `sig-transaction` for more information.

**Comment by Defined2014** [comment]
The `amend txn` is deprecated in [v6.5.0](https://docs.pingcap.com/tidb/stable/release-6.5.0#deprecated-feature). There should be no any progress on this issue, so close it.
