### ISSUE TITLE
After retry failed it does nothing with the current transaction

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#2107]
If there is a statement that is retried 10 times, but it still failed, we do nothing with the current transaction.

**Comment by kolbe** [comment]
@zimulala Hi! Do you know if this is still an issue, or has this been resolved by now?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Many things have happened since the issue was created: retry is disabled by default, and the default locking is pessimistic.

Please feel free to re-open if you have additional questions. Thanks!
