### ISSUE TITLE
Why no Views?

### ISSUE THREAD

**Issue by nnordrum** [pingcap/tidb#2119]
Apologies if I'm just blind and not seeing it, but I see that Views are not supported "because they cannot be implemented well in distributed scenario."

Is it documented somewhere what the difficulties are with the unsupported features? I feel like this would be important so if somebody has an idea on how to solve the problem, maybe even partially, they know what the known hurdles are. Or maybe something could be optimized in a another way (e.g. try and clump data on fewer nodes, instead of all spread out, so the view would be less expensive).

**Comment by shenli** [comment]
@nnordrum Thanks for your suggestion.
I am agree with you and view is on our plan. But it will not be included in the GA version, because of time.
