### ISSUE TITLE
ORM and application Support 

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#212]
Python:
- [ ] SQLAlchemy
- [ ] Peewee
- [ ] django
- [ ] ponyorm

Go:
Orm:
- [x] xorm: https://github.com/go-xorm/xorm
- [x] beego: https://github.com/astaxie/beego/tree/master/orm
- [x] go-sql-test: https://github.com/bradfitz/go-sql-test
- [ ] upper.io: https://upper.io/db.v1/mysql

Application:
- [x] Gogs: https://github.com/gogits/gogs
- [ ] Dalga: https://github.com/cenkalti/dalga

Java：
- [x] Mybatis
- [ ] Jdbctemplate
- [ ] Hibernate
- [ ] Play

PHP:
- [ ] phabricator: http://phabricator.org/
- [x] phpmyadmin 
- [x] wordpress
- [ ] yii: http://www.yiiframework.com/doc/guide/1.1/en/database.ar
- [ ] discuz!: http://www.discuz.net/ 
- [ ] drupal: https://www.drupal.org/
- [ ] [Eloquent](https://laravel.com/docs/5.5/eloquent)

Dotnet:
- [ ] [Entity Framework Core](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql)

**Comment by ngaut** [comment]
@shenli Any update ?

**Comment by shenli** [comment]
I will go through the list tomorrow. @ngaut

**Comment by shenli** [comment]
sqlalchemy unit test:
 25 failed, 404 passed, 51 skipped in 34.78 seconds 
I will fix the failed cases.

**Comment by catroot** [comment]
pls add ponyorm for python to the list

**Comment by starplanet** [comment]
Does tidb support sqlalchemy now?

I change my python application from mysql to tidb, it will report the error:
`ALTER TABLE applications ADD CHECK (allow_create_user in (0, 1)`

I know tidb doesn't support check constraint, but can let sqlalchemy ORM auto deal with tidb non-support features?

**Comment by lotaku** [comment]
pls add django orm  to the list

**Comment by kocoten1992** [comment]
Hello, please add Eloquent from laravel, it a big player, deserve be on here

**Comment by shenli** [comment]
@kocoten1992 @lotaku @starplanet @catroot Thanks for your advice! I added them to the list.

**Comment by zaaack** [comment]
please add entity framework core/https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by shenli** [comment]
@zaaack Done! Thanks!

**Comment by shenli** [comment]
@zaaack Thanks!

**Comment by shenli** [comment]
@zaaack May I have your tidb's version? You can get it by `select tidb_version();`.

**Comment by zaaack** [comment]
$ mysql -h 127.0.0.1 -P 4000 -u root  --prompt="tidb> "  
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 4
Server version: 5.7.1-TiDB-0.9.0 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

tidb> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                          |
+-----------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: 0.9.0
Git Commit Hash: ca048c058297e6826f5eb975d3ff963942cd876a
Git Branch: master
UTC Build Time: 2017-10-05 02:40:50 |
+-----------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by kocoten1992** [comment]
Should each ORM open their own issue then link to this issue, cause thing gonna get messy real quick

**Comment by zaaack** [comment]
@kocoten1992 Good advice, I just opend a new issue here: https://github.com/pingcap/tidb/issues/4840

**Comment by catroot** [comment]
```
2017/12/13 04:55:55.933 session.go:732: [warning] [10] parse error:
line 1 column 60 near "" (total length 60)
ALTER TABLE `content_type` DROP COLUMN `name` CASCADE
2017/12/13 04:55:55.933 conn.go:437: [warning] [10] dispatch error:
id:10, addr:127.0.0.1:36496 status:2, collation:latin1_swedish_ci, user:root
"ALTER TABLE `content_type` DROP COLUMN `name` CASCADE"
line 1 column 60 near "" (total length 60)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:733:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:757:
2017/12/13 04:55:55.935 server.go:297: [info] [10] close connection
```

"ALTER TABLE `table_name` DROP COLUMN `column_name` CASCADE" isn`t supported yet?

**Comment by lamxTyler** [comment]
@catroot Yes, we do not support it yet.

**Comment by catroot** [comment]
@lamxTyler, is there in plans to implemet this?

**Comment by lamxTyler** [comment]
@catroot Currently, we do not have any plan to implement it.

**Comment by phoenixg** [comment]
I'm using eloquent, the MySQL JSON format field value cannot query out, the same table works well on my local machine (MySQL 5.7.20), but it won't work on TiDB:

```
class TiTransactionPlus extends TiDBModel
{
    protected static $table_name = 'transaction_plus';

    public $incrementing = false;

    protected $primaryKey = 'trans_id';

    protected $guarded = [];
    protected $casts = [
        'trans_metadata' => 'array',
        'trans_extra' => 'array',
    ];
}
```

**Comment by lamxTyler** [comment]
@phoenixg Can you provide us the query SQL or code and your tidb version so that we can reproduce this problem?

**Comment by phoenixg** [comment]
@lamxTyler 

**TiDB version:**
Release Version: 1.0.0
Git Commit Hash: 1a175b562bc679694f606c336131a9373064b324
Git Commit Branch: release-1.0
UTC Build Time: 2017-10-19 02:38:02

**SQL code:**
I use `TiTransactionPlus::db()->getQueryLog()` to print out SQL executed: 

```sql
select * from transaction_plus where trans_id = ? limit 1;
```

It's totally OK in MySQL client, so I think it's framework problem. Here is my composer dependency:

```json
"require": {
        "php": ">=5.6.0",
        "illuminate/database": "~5.2.37",
        "illuminate/events": "~5.2.37",
        "illuminate/pagination": "~5.2.37",
        "doctrine/dbal": "~2.5"
    }
```

**Comment by lamxTyler** [comment]
@phoenixg  Is it correct if we do not cast the `trans_extra`? Can you give an example of `trans_extra`?

**Comment by phoenixg** [comment]
@lamxTyler Not correct if I don't cast the `trans_extra`, the value is any JSON data, eg:

```json
{"user":"testname@domain.com"}
```

**Comment by lamxTyler** [comment]
@phoenixg I think maybe there is something wrong when you insert the JSON. Can the SQL generated by framework be inserted into tidb successfully? Can the inserted value be queried out successfully?  If not, please provide an example of the SQL.

**Comment by evvo** [comment]
I've created a small library that extends the Eloquent's MySQL connection class and should improve compatibility with Laravel:
https://packagist.org/packages/evvo/tidb-laravel

Migrations should be working now.

**Comment by Xuanwo** [comment]
https://github.com/bitnami/bitnami-docker-phabricator/issues/123

It looks like tidb can't be used in phabricator

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Compatibility has improved a lot in the last two years, and if there are any specific problems discovered, it is best to create a specific issue.

**Comment by zz-jason** [comment]
let's track the unsupported ORMs in https://github.com/pingcap/tidb/issues/24194
