### ISSUE TITLE
TiDB can sense all TiFlash replicas have been down and make a plan to access TiKV.

### ISSUE THREAD

**Issue by SunRunAway** [pingcap/tidb#21254]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, if all TiFlash replicas of a query's data have been down, tidb-server would still make those plans to acesse TiFlash.

**Describe the feature you'd like:**

Provide a configuration to let users choose the storage fallback policy. It should defaut to not fallback, because the workload for TiFlash may make TiKV cluster overload. If it is changed to fallback mode, the following plans made by optimizer should sense the offline of the TiFlash nodes and make plan to access to TiKV until TiFlash back to normal.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by SunRunAway** [comment]
cc @lzmhhh123 @nolouch 
Do you have any suggestions?

**Comment by zz-jason** [comment]
duplicated with https://github.com/pingcap/tidb/issues/20423
