### ISSUE TITLE
get all tidb-server nodes 

### ISSUE THREAD

**Issue by liushiqi1001** [pingcap/tidb#21291]
## General Question
I want to know how many tidb-server nodes online ,is there  any restful api ???
http://${host}:${port}/status ,it is too little information

**Comment by ichn-hu** [comment]
You might want to try

```
select * from information_schema.cluster_info;
```

**Comment by liushiqi1001** [comment]
> 
> 
> You might want to try
> 
> ```
> select * from information_schema.cluster_info;
> ```thanks

**Comment by ichn-hu** [comment]
Please feel free to close this issue if your question is resolved.

liushiqi1001 <notifications@github.com>于2020年11月26日 周四下午6:08写道：
