### ISSUE TITLE
Support lazy open union children

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#21441]
## Development Task

In #19827, we support concurrency control for  Union's children execution.

but Union executor still `Init` all children before execute `Next`

init children will cause sub-plan nodes's `Init` be called

combined with #14320, partition table will make the "buildCopTasks takes too much time" problem even worse.

so for a partition table with 128 partitions

```
select * from partition_table limit 1;
```
it will build all copTask in memory for each 128 partitions before send any request to tikv(and finally maybe only 1 request is useful)

**Comment by tiancaiamao** [comment]
There is such an attempt some time ago  https://github.com/pingcap/tidb/pull/16815

**Comment by XuHuaiyu** [comment]
reopen this issue cause the fix is reverted in https://github.com/pingcap/tidb/pull/23276
