### ISSUE TITLE
start with multi-ip addresses `--advertise-address=192.168.7.210 xxx.xxx.18.210` couldn't connect server success

### ISSUE THREAD

**Issue by heming79** [pingcap/tidb#21448]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Tidb 4.0.7 vim /etc/hosts
192.168.7.210 yz-mbg-018210
xxx.xxx.18.210 yz-mbg-018210
hostname -i 输出  192.168.7.210 xxx.xxx.18.210
启动tidb 会导致启动参数 --advertise-address=192.168.7.210 xxx.xxx.18.210
此时4000端口监听正常 ，但是 mysql连接报授权失败

### 2. What did you expect to see? (Required)
希望做一下参数判断 如果 --advertise-address 超过一个值就报异常 ，不要启动端口监听 ，避免前端lvs或者 haproxy 认为后端可用不利于高可用 ，不利于查问题 

### 4. What is your TiDB version? (Required)

4.0.7

**Comment by heming79** [comment]
或者检查一下 为什么这种情况tidb服务不可用

**Comment by lysu** [comment]
thanks for your feedback.

yes, `-advertise-address` should add check, but it seems there are some misunderstand for you about `advertise-address` usage.

First, for go's `flag.String`, you can not split multiple parameters with SPACE(" "), so for your command tidb only recieve `192.168.7.210`.
Second, `-advertise-address` only a advertise address to others, real bind host is `-host`(why need two configuration, https://github.com/pingcap/tidb/pull/7078#issue-201983880 has some explain), but we also cannot bind multi `host` now

**Comment by TszKitLo40** [comment]
I have filed a PR, PTAL @lysu
