### ISSUE TITLE
Add information_schema.variables_info view

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#21446]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This is a subset of an earlier proposal https://github.com/pingcap/tidb/issues/19332

The behavior of instance scoped variables is still being discussed, but part of the proposal which can be decoupled is `information_schema.variables_info`.

**Describe the feature you'd like:**

MySQL 8.0 exposes meta-data about sysvars through `performance_schema.variables_info`. I would like to propose the same in TiDB (but in `information_schema`):

```sql
CREATE TABLE variables_info (
  `VARIABLE_NAME` varchar(64) NOT NULL,
  `CONFIGURATION_NAME` varchar(64) NULL, 
  `VARIABLE_SOURCE` enum('COMPILED','GLOBAL',’INSTANCE',’COMMAND_LINE’, ’CONFIGURATION’, 'SESSION') DEFAULT 'COMPILED',
  `VARIABLE_SCOPE` SET('GLOBAL','INSTANCE', 'SESSION'),
  `MIN_VALUE` varchar(64) DEFAULT NULL,
  `MAX_VALUE` varchar(64) DEFAULT NULL,
  `DEFAULT_VALUE` varchar(255) DEFAULT NULL,
  `CURRENT_VALUE` varchar(255) DEFAULT NULL,
 PRIMARY KEY (VARIABLE_NAME),
 UNIQUE (CONFIGURATION_NAME)
);
```

Notes:
* The `CONFIGURATION_NAME` permits null values. This reflects that the `VARIABLE_NAME` is the canonical source, and while some sysvars may have a configuration_name, all have a `VARIABLE_NAME`.
* The `VARIABLE_SOURCE` matches TiDB sources.
* The `MIN_VALUE`/`MAX_VALUE` apply to numeric sysvars only. If non-numeric, the value will be `NULL`.
* The `CURRENT_VALUE` reflects the current session, which could be weird if the session has been changed from the global, but this is an information-schema like semantic (which can use the user's context). See `variables_by_thread` in alternatives.

**Describe alternatives you've considered:**

Showing the `CURRENT_VALUE` has a strange behavior, because it is from *your current session* (and global + other sessions may differ). MySQL's performance_schema has something called `variables_by_thread`, but I think this adds complexity. It should be possible to see the `VARIABLE_SOURCE` is 'SESSION' to indicate that it's been changed.

**Teachability, Documentation, Adoption, Migration Strategy:**

I don't think it will be used by too many users, but it is possible to do things like see which sysvars you have changed from the defaults with:
```sql
SELECT * FROM variables_info WHERE current_value != default_value;
```

It will be useful for debugging when variables are expanded to support instance scope (see: `variable_source`). Currently there is no easy way to see if a variable is instance scope, which is a really handy addition. The [documentation for sysvars](https://docs.pingcap.com/tidb/stable/system-variables) can also be partially generated (or validated) using this view. Maintaining it correctly has proven difficult as options have been added or changed.

**Comment by SunRunAway** [comment]
I actually don’t really recommend putting variables in the tidb‘s table

for example:
Now enable a log_redact configuration, users need to change PD's configuration, tiflash's configuration, and tidb's.

It's ideal that after setting @@global.tidb_redact_log=1, all components can read it.

If we put the variable in the tidb's table, it will be difficult to read when other components are started, because the startup sequence of tidb-server is generally not the first one.

It seems to be fine that the variables can be placed in a public place (for example, etcd) and all components can read it.

The original MySQL is implemented in this way because it is a stand-alone database, and there is no such problem.

**Comment by morgo** [comment]
> I actually don’t really recommend putting variables in the tidb‘s table
> 
> for example:
> Now enable a log_redact configuration, users need to change PD's configuration, tiflash's configuration, and tidb's.
> 
> It's ideal that after setting @@global.tidb_redact_log=1, all components can read it.
> 
> If we put the variable in the tidb's table, it will be difficult to read when other components are started, because the startup sequence of tidb-server is generally not the first one.
> 
> It seems to be fine that the variables can be placed in a public place (for example, etcd) and all components can read it.
> 
> The original MySQL is implemented in this way because it is a stand-alone database, and there is no such problem.

That makes sense to me too, but it can be handled independent of this task. `Information_schema.variables_info` is a view, and won't make any changes to persistence.

The meta data it shows is read from `variable.sysVars map[string]*SysVar` and `SessionVars.systems map[string]string` through accessor methods (`SessionVars.systems` is populated by `mysql.GLOBAL_VARIABLES`, but that does not need touching in this task).
