### ISSUE TITLE
Compared with mysql cluster

### ISSUE THREAD

**Issue by ch-lgs** [pingcap/tidb#2151]
Compared with MySQL Cluster,what's the advantage of TiDB?

**Comment by shenli** [comment]
@ch-lgs Compare with proxy, TiDB has horizontal scalability, online schema changes, consistent distributed transactions.

**Comment by ch-lgs** [comment]
what I mean is not the mysql cluster with proxy,but mysql cluster that MySQL official provides

**Comment by shenli** [comment]
@ch-lgs I think TiDB has the following advantages against MySQL cluster: 

-  You can deploy TiDB cluster across data centers. We use raft to replicate data between replica. In this scenario, even the whole data center is down, your data is also safe and your service is still on.

- TiDB could handle complex query better. Our optimizer is suitable for distributed computing.

- Adding or removing node into/from TiDB cluster is very easy.

- TiDB supports real distributed transaction. 

- TiDB is easy to deploy and maintain.

**Comment by ch-lgs** [comment]
Thank you for your answer.And i want to know when TiDB can release stable version.

**Comment by shenli** [comment]
@ch-lgs We are going to release RC1 in the next week. GA will be released early in the next year (may be around Chinese New Year).

**Comment by manualsh** [comment]
MySql Cluster has increased number of Nodes to 255.  Can above answer be updated to latest in 2023.
