### ISSUE TITLE
Can I use while

### ISSUE THREAD

**Issue by xiaoyang1999** [pingcap/tidb#21528]
在ELT过程中，数据UPDATE量过大，抛出事务大小超过10M，后来打算使用while方式来分批修改，但是语法报错

**Comment by xiaoyang1999** [comment]
You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 16 near "PROCEDURE pro_insert () BEGIN

**Comment by sev7ndayyoo** [comment]
Please paste the complete sql.

**Comment by morgo** [comment]
The error is caused when trying to create a stored procedure, which TiDB does not support. This is documented under [MySQL compatibility](https://docs.pingcap.com/tidb/stable/mysql-compatibility#unsupported-features).

(If you would like to ask questions in Chinese, may I suggest [AskTUG](https://asktug.com/).)

**Comment by morgo** [comment]
@xiaoyang1999 I am going to close this question as answered, but please feel free to re-open if you have any additional questions. Thanks!
