### ISSUE TITLE
misleading error message with sysbench

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb#2161]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

    sysbench --test=./lua-tests/db/oltp.lua --mysql-host=127.0.0.1 --mysql-port=4000 --mysql-user=root --mysql-password= --oltp-tables-count=1 --oltp-table-size=100 --rand-init=on prepare

2. What did you expect to see?

note that I didn't provide ``--mysql-db``, so sysbench should fail with table not found.

3. What did you see instead?

```
FATAL: unable to connect to MySQL server on host '127.0.0.1', port 4000, aborting...
FATAL: error 2013: Lost connection to MySQL server at 'reading authorization packet', system error: 0
FATAL: failed to execute function `prepare': ./lua-tests/db/common.lua:103: Failed to connect to the database
```

4. What version of Go are you using (`go version`)?

official binary from download.pingcap.net

While what mysql reports:
```
FATAL: unable to connect to MySQL server on host '127.0.0.1', port 3306, aborting...
FATAL: error 1049: Unknown database 'sbtest'
FATAL: failed to execute function `prepare': ./lua-tests/db/common.lua:103: Failed to connect to the database
```

**Comment by coocood** [comment]
Tried the latest master, it reports the same error as MySQL.

**Comment by phamtai97** [comment]
Has this bug been fixed yet?
