### ISSUE TITLE
`select _tidb_rowid` does not work now

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#21611]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t (a varchar(20) primary key, b int, unique index idx(b)); 
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values ('1',1);
Query OK, 1 row affected (0.01 sec)

mysql> select _tidb_rowid from t;
ERROR 1054 (42S22): Unknown column '_tidb_rowid' in 'field list'
```

### 2. What did you expect to see? (Required)
Display the row id.

### 3. What did you see instead (Required)
Error.

### 4. What is your TiDB version? (Required)

```
| Release Version: v4.0.0-beta.2-1765-g3b1e1027f
Edition: Community
Git Commit Hash: 3b1e1027fda874aed4017f87b265a142dc054793
Git Branch: master
UTC Build Time: 2020-12-09 11:17:24
GoVersion: go1.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by wjhuang2016** [comment]
This is the expected behavior. Because the clustered index is enabled by default.
When using the clustered index and the primary key is varchar, there is no _tidb_rowid.
