### ISSUE TITLE
Support vector and vector index

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tidb#21647]
## Feature Request

**Is your feature request related to a problem? Please describe:**
According to rising attentions for traffic monitoring, image / video retrieval, recommendation system, more and more application use AI / Deep learning to process data. TiDB are usually used as meta data storage solution for those cases: store raw video / image in a blob store and store image tags and meta info in TiDB. When users retrieve data, they will be using vector index for vector similarity search. If this is supported, TiDB will have broader adoption in those areas.

**Describe the feature you'd like:**
1. Feature Vector stored in TiDB as a new data type, for example, `feature VECTOR(1024)`. It looks like a floating array.
2. Supporting building ANN index on feature vector, such as hnsw, ivf.
3. Supporting order by based on similarity. Such as 

`ORDER BY cosine_distance(array[0.2,0.12,...0.23],feature)`

**Comment by shizn** [comment]
Hey everyone, we are excited to announce that we've started rolling out Vector Search as a private beta on TiDB Serverless. This feature aims to address the growing needs for sophisticated data processing and retrieval methods in domains like AI and deep learning, as highlighted in this issue. If you are interested in taking part and exploring the new capabilities, you can sign up for the private beta at [TiDB Cloud AI](https://tidb.cloud/ai). Also you can get more details [here in the blog post](https://www.pingcap.com/blog/integrating-vector-search-into-tidb-for-ai-applications/). We are looking forward to your feedback and contributions to make TiDB even more powerful and versatile for modern applications.

**Comment by longlongago7777** [comment]
How is the progress now ？Only for cloud，Any  release plan for OP version？

**Comment by dveeden** [comment]
https://docs.pingcap.com/tidb/dev/vector-search-overview

**Comment by breezewish** [comment]
This feature is now available to all TiDB product offers, including cloud version and open-source version. The tracking issue of development is here: https://github.com/pingcap/tidb/issues/54245
