### ISSUE TITLE
integration_test.go:testIntegrationSerialSuite.TestPreferRangeScan failed

### ISSUE THREAD

**Issue by KivenChen** [pingcap/tidb#21723]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/66520/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_check_2/66520/display/redirect</a>

**Comment by XuHuaiyu** [comment]
Out of date test case.
Merging the latest master can solve this problem.
