### ISSUE TITLE
DATA RACE:github.com/pingcap/tidb/session.(*TxnState).changeToInvalid() failed

### ISSUE THREAD

**Issue by KivenChen** [pingcap/tidb#21726]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/60730/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/60730/display/redirect</a>

**Comment by tiancaiamao** [comment]
I meet this too

**Comment by XuHuaiyu** [comment]
@wjhuang2016 Do you work on this?

**Comment by XuHuaiyu** [comment]
It seems to be caused by https://github.com/pingcap/tidb/pull/21650

@Yisaer PTAL
