### ISSUE TITLE
DATA RACE:github.com/pingcap/tidb/session.(*TxnState).initStmtBuf() failed

### ISSUE THREAD

**Issue by KivenChen** [pingcap/tidb#21730]
Latest build: <a href="https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/60730/display/redirect">https://internal.pingcap.net/idc-jenkins/job/tidb_ghpr_unit_test/60730/display/redirect</a>

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
