### ISSUE TITLE
Question about the kv engine under tidb. (tidb的底层 KV 问题)

### ISSUE THREAD

**Issue by yemt** [pingcap/tidb#2177]
您好，ＴＩＤＢ的架构是不是ＫＶ是单独一层（ＫＶ单独配置），ＴＩＤＢ类似于中间件？

**Comment by shenli** [comment]
@yemt Thanks for your feedback!
TiDB is the SQL layer and TiKV is the storage engine layer. Their relationship is just like Google's F1 and Spanner.
TiDB is not a proxy, it is a SQL engine.
BTW: We encourage discuss in English in this repo. So people from all the world could take part in.
