### ISSUE TITLE
Support JSON object with key length >= 65536

### ISSUE THREAD

**Issue by dyzsr** [pingcap/tidb#21781]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Original issue: #9995
A temporary fix: #21779

TiDB produces wrong result when creating JSON object if there's any key length >= 65536. The key length will be truncated to `uint16`, since it is stored into `uint16` instead of larger integer types. And this issue cannot be fixed easily like #21594 , which will break the backward compatibility.

``` mysql
mysql root@127.0.0.1:test> select json_object( REPEAT('a', 2 * 16 ), 1 );
+-----------------------------------------+
| json_object( REPEAT('a', 2 * 16 ), 1 )  |
+-----------------------------------------+
| {"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa": 1} |
+-----------------------------------------+
1 row in set
Time: 0.020s

mysql root@127.0.0.1:test> select json_object( REPEAT('a', 64 * 1024), 1 );
+------------------------------------------+
| json_object( REPEAT('a', 64 * 1024), 1 ) |
+------------------------------------------+
| {"": 1}                                  |
+------------------------------------------+
1 row in set
Time: 0.009s

mysql root@127.0.0.1:test> select json_object( REPEAT('a', 64 * 1024 + 5), 1 );
+----------------------------------------------+
| json_object( REPEAT('a', 64 * 1024 + 5), 1 ) |
+----------------------------------------------+
| {"aaaaa": 1}                                 |
+----------------------------------------------+
1 row in set
Time: 0.008s
```

**Describe the feature you'd like:**

Support JSON object with key length >= 65536 without breaking backward compatibility.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by xiongjiwei** [comment]
close due to not problem

```
create table t(a json);
mysql> insert into t values (json_object( REPEAT('a', 65 * 1024), 1 ));
ERROR 3151 (22032): The JSON object contains a key name that is too long.
```

MySQL reports the error if the JSON needs to be formatted.
