### ISSUE TITLE
Limit and Offset not work

### ISSUE THREAD

**Issue by elvizlai** [pingcap/tidb#2180]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

using go mysql driver `github.com/go-sql-driver/mysql`

sql: `select id from x LIMIT 10 OFFSET 5`

or

sql: `select id from x LIMIT 5,10`

2. What did you expect to see?

10 results returns

3. What did you see instead?

15 results returns (But I run that command in mysql client, it works. Did I missing something?)

4. What version of Go are you using (`go version`)?

go 1.7.4

**Comment by zimulala** [comment]
@elvizlai Thanks for your report. Can you give us some cases?

**Comment by hanfei1991** [comment]
@elvizlai Can you post your create table stmt and insert data stmt?

**Comment by elvizlai** [comment]
very strange. I tried a test case, but it works now, I'll check.

**Comment by elvizlai** [comment]
the fmt mislead

**Comment by zet4** [comment]
Encountered same issue when I tried to use tidb alongside micro/user-srv (haven't tried other srv's from micro with tidb yet), [sql source](https://github.com/micro/user-srv/tree/master/db/db.go), errors:
```
H:\gopath\src\github.com\micro\user-srv>user-srv --database_url="root@tcp(192.168.99.100:4000)/users"
2016/12/31 12:43:02 Prepering searchEmail SELECT id, username, email, salt, password, created, updated from %s.%s where email = ? limit ? offset ?
2016/12/31 12:43:02 Error 1105: line 0 column 104 near " offset ?"
```
(note the Preparing log is my addition, not part of master branch of user-srv)
This issue seems to only occur to statements containing limit & offset.
TiDB is simply ran from latest image in local docker container.

**Comment by shenli** [comment]
@zet4 Thanks for your feedback! We will look into it.

**Comment by shenli** [comment]
@zet4 It is a bug about limit/offset with prepare statement. I will fix it.

**Comment by shenli** [comment]
@zet4 This will be fixed in https://github.com/pingcap/tidb/pull/2364. You can try the branch shenli/issue-2180 or use the latest master after this PR is merged.
Thanks again for your report!  Happy New Year!

**Comment by zet4** [comment]
Thanks, you too!

**Comment by shenli** [comment]
@zet4 Please try the latest master. If there is also something wrong, feel free to reopen this issue.
Thanks!

**Comment by zet4** [comment]
Sorry to bother you but it still doesn't seem to work:
```
H:\gopath\src\github.com\micro\user-srv>user-srv.exe --database_url="root:111111@tcp(192.168.99.100:32769)/users"
2017/01/03 09:37:18 Listening on [::]:51318
2017/01/03 09:37:18 Broker Listening on [::]:51319
2017/01/03 09:37:18 Registering node: go.micro.srv.user-744cb455-d187-11e6-9f03-0a0027000008
2017/01/03 09:37:24 Deregistering node: go.micro.srv.user-744cb455-d187-11e6-9f03-0a0027000008

H:\gopath\src\github.com\micro\user-srv>user-srv.exe --database_url="root@tcp(192.168.99.100:32770)/users"
2017/01/03 09:37:40 Prepering list SELECT id, username, email, salt, password, created, updated from users.sessions limit ? offset ?
2017/01/03 09:37:40 Error 1105: line 0 column 88 near " offset ?"
```
port ending with 69 is an alpine-mysql container and works OK with it, but port ending in 70 is latest tidb and doesn't work, version: 
```
2017/01/03 07:33:13 printer.go:31: [info] Welcome to TiDB.
2017/01/03 07:33:13 printer.go:32: [info] Version:
2017/01/03 07:33:13 printer.go:33: [info] Git Commit Hash: 3f9a101ce6a31d508d184aa03f2ebb8209a9e480
2017/01/03 07:33:13 printer.go:34: [info] UTC Build Time:  2017-01-03 04:43:44
```

latest record in the log for tidb after one attempt is: 
```
2017/01/03 07:37:40 server.go:115: [info] [25] new connection 192.168.99.1:51333
2017/01/03 07:37:40 conn.go:350: [warning] [25] dispatch error:
id:25, addr:192.168.99.1:51333 status:2, collation:utf8_general_ci, user:root
SELECT id, username, email, salt, password, created, updated from users.accounts limit ? offset ?
line 0 column 88 near " offset ?"
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/prepared.go:125: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn_stmt.go:50: 
2017/01/03 07:37:40 conn.go:340: [error] read tcp 172.17.0.5:4000->192.168.99.1:51333: read: connection reset by peer
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:72: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/packetio.go:94:  
2017/01/03 07:37:40 txn.go:126: [info] [kv] Rollback txn 388872027526397952
2017/01/03 07:37:40 server.go:192: [info] [25] close connection
```
I also attached entire docker container log file: [logs.txt](https://github.com/pingcap/tidb/files/681842/logs.txt)

**Comment by shenli** [comment]
@zet4 Please update your binary/source. 3f9a101ce6a31d508d184aa03f2ebb8209a9e480 is not the latest githash.

**Comment by zet4** [comment]
Okay yeah, pulling it again worked, but now I have a new error, when actually using the limit/offset:
```
2017/01/03 09:28:23 logical_plan_builder.go:447: [error] Invalid type int64 for Limit/Offset
2017/01/03 09:28:23 tidb.go:194: [info] RollbackTxn for ddl/autocommit error.
2017/01/03 09:28:23 txn.go:126: [info] [kv] Rollback txn 388873769071935488
2017/01/03 09:28:23 conn.go:350: [warning] [2] dispatch error:
id:2, addr:192.168.99.1:52674 status:2, collation:utf8_general_ci, user:root
user
[11:1210]Incorrect arguments to EXECUTE
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/optimizer.go:45:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/prepared.go:235:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/adapter.go:96:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/tidb.go:200:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:564:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/driver_tidb.go:66:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn_stmt.go:168:
```
I believe the query in question was 
```
SELECT id, username, email, salt, password, created, updated from users.accounts where username = ? limit ? offset ?
```
with arguments `user`, `1`, `0`. (`r, err = st["searchUsername"].Query(username, 1, 0)`)

**Comment by shenli** [comment]
@zet4 The value for limit/offset should be integer(or a string could be parsed to integer).
May I know your command? Still the following command?
`H:\gopath\src\github.com\micro\user-srv>user-srv.exe -- database_url="root:111111@tcp(192.168.99.100:32769)/users"`

**Comment by zet4** [comment]
That one was used for alpine-mysql, my commands right now are
`H:\gopath\src\github.com\micro\user-srv>user-srv.exe --database_url="root@tcp(192.168.99.100:4000)/users"
`
to launch and then I did `query go.micro.srv.user Account.Create {"user": {"username":"user"}, "password": "pass"}` to create account and `query go.micro.srv.user Account.Login {"username": "user", "password": "pass"}` which is where it should've returned a session but returned error `error calling go.micro.srv.user.Account.Login: Error 1210: Incorrect arguments to EXECUTE`

As far as I saw on those lines its passing integers to offset/limit

**Comment by shenli** [comment]
@zet4 OK, I will check it out and fix it soon.

**Comment by coocood** [comment]
Fixed by https://github.com/pingcap/tidb/pull/2648
