### ISSUE TITLE
Validate statements for read-only transactions

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#21824]
## Background

This is a subtask of #21094.

Staleness transactions can only be read-only, and statements in these transactions must be read-only.

## Implementation

Call `planner.IsReadOnly` after the statement is parsed and before it's compiled.

Don't miss these special cases:
- Point get & batch point get
- Prepared statements

These cases don't need to be considered:
- `FOR UPDATE` statements are already handled by `planner.IsReadOnly`
- DDL won't be in read-only transactions

**Comment by Yisaer** [comment]
According to https://github.com/pingcap/parser/pull/1145 , it seems we can't think `Prepared statements` as `read-only`. @djshow832

**Comment by djshow832** [comment]
> According to [pingcap/parser#1145](https://github.com/pingcap/parser/pull/1145) , it seems we can't think `Prepared statements` as `read-only`. @djshow832

Prepared statements can't be taken as read-only in the transaction retrial mechanism, but it can be executed in read-only staleness transactions because it doesn't touch the database. You don't need to rely on `IsReadOnly` totally.
