### ISSUE TITLE
Is “distinct-agg-push-down" same as "agg-push-down-join" ?

### ISSUE THREAD

**Issue by zgcbj** [pingcap/tidb#21825]
https://github.com/pingcap/tidb/blob/7fac2ba027aee70cad4f4a307240ef5b7e6a64f8/config/config.go#L439

**Comment by lzmhhh123** [comment]
Will be fixed in 5.0.1 and 4.0.13

**Comment by zgcbj** [comment]
> Will be fixed in 5.0.1 and 4.0.13

I can`t find any change in 5.0.1 and 4.0.13
