### ISSUE TITLE
dbForge Can't connect to TiDB

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#2183]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
use dbForge Studio for MySQL to connect TiDB

2. What did you expect to see?
connect successful

3. What did you see instead?
Table 'information_schema.SESSION_VARIABLES' doesn't exist.

4. What version of Go are you using (`go version`)?
1.7

**Comment by ddrsql** [comment]
> Please answer these questions before submitting your issue. Thanks!
> 
> 1. What did you do?
>    use dbForge Studio (2019/2020) for MySQL to connect TiDB
> 2. What did you expect to see?
>    connect successful
> 3. What did you see instead?
>    Table 'performance_schema.session_variables' doesn't exist.
> 4. What version of Go are you using (`go version`)?
>    Deploy a local test environment using TiUP Playground
Release Version: v4.0.7
Edition: Community
Git Commit Hash: ed939f3f11599b5a38352c5c160c917df3ebf3eb
Git Branch: heads/refs/tags/v4.0.7
UTC Build Time: 2020-09-29 06:56:48
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
@hanfei1991 
I am searching for a long time on net. But no use. Please help or try to give some ideas how to achieve this. Thanks in advance.
