### ISSUE TITLE
forbid to create tiflash replica for tables under `mysql` database

### ISSUE THREAD

**Issue by marsishandsome** [pingcap/tidb#22046]
## Feature Request

**Is your feature request related to a problem? Please describe:**

`tidb-server` fail to restart after create tiflash replica for table `mysql.user`

**Describe the feature you'd like:**

forbid to create tiflash replica for tables under `mysql` database

```
ALTER TABLE mysql.user SET TIFLASH REPLICA 1;
ERROR 1142 (42000): ALTER command denied to user 'root'@'%' for table 'user'
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by crazycs520** [comment]
@zz-jason PTAL

**Comment by AilinKid** [comment]
ALTER privilege is already implemented in replica setting
```
mysql> alter table mysql.user set tiflash replica 1;
ERROR 1142 (42000): ALTER command denied to user 'testUser'@'127.0.0.1' for table 'user'
```
I think what we need is to ban the behavior for all users
```
mysql> alter table mysql.user set tiflash replica 1;
ERROR 1105 (HY000): couldn't set tiflash replica for tables in MySQL system database
```
