### ISSUE TITLE
`Can't find column` errors when using group_concat

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#22082]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `tx` (
  `ct_name` varchar(100) DEFAULT NULL,
  `employee_name` varchar(100) DEFAULT NULL
);

select group_concat(ct_name_tt order by ct_nums_tt)
from (
  select  ct_name_t as ct_name_tt ,ct_nums_t as ct_nums_tt
  from
      (
      select  t1.ct_name as ct_name_t, t1.ct_name+' ' as ct_nums_t, t1.employee_name
      from (
          select employee_name, ct_name
          from tx
          group by employee_name,ct_name
          ) t1
      ) t
  group by ct_name_t,ct_nums_t
) tt;
```

### 2. What did you expect to see? (Required)
The query above returns an empty result without any error.

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Can't find column tt.ct_nums_tt in schema Column: [test.t.ct_name_t,t.ct_nums_t] Unique key: [[test.t.ct_name_t,t.ct_nums_t]]
```

### 4. What is your TiDB version? (Required)

Release-3.0.20
```
mysql> select version();
+---------------------+
| version()           |
+---------------------+
| 5.7.25-TiDB-v3.0.20 |
+---------------------+
1 row in set (0.00 sec)
```

**Comment by TszKitLo40** [comment]
In master version, the result is NULL. It seems that this issue has been fixed.

**Comment by XuHuaiyu** [comment]
@qw4990 Maybe we need to check which commit in master fixed this issue.

**Comment by yudongusa** [comment]
@qw4990 @XuHuaiyu since it's been quite awhile after this was fixed and probably hard to locate the PR actually fixed the issue, should we go ahead to close it?

**Comment by winoros** [comment]
Since 3.0.x is not maintained now. We are going to close this issue.
If you meet this one, upgrading would solve it. :)
