### ISSUE TITLE
information_schema.cluster_info contains an extra weird row

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#22093]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Use tiup to deploy a 4.0.9 tidb cluster, patch it with release-5.0-rc binaries. Run `select * from information_schema.cluster_info`

### 2. What did you expect to see? (Required)
The result is correct

### 3. What did you see instead (Required)
The result contains an extra row `tidb    :4000   :10080  None    None    2020-12-30T04:43:35Z    3m13.313395286s 3134106`
```bash
$ mycli -h 172.16.4.83 -P 33110 -u root -e 'select * from information_schema.cluster_info'
TYPE    INSTANCE        STATUS_ADDRESS  VERSION GIT_HASH        START_TIME      UPTIME  SERVER_ID
tidb    10.0.2.79:4000  10.0.2.79:10080 4.0.0-beta.2    f99982b0c594c14ed3c92f62329e3dfd68e884d5        2020-12-30T03:49:17Z    57m31.313387838s        0
tidb    :4000   :10080  None    None    2020-12-30T04:43:35Z    3m13.313395286s 3134106
pd      10.0.2.80:2379  10.0.2.80:2379  5.0.0-alpha     8ff72c9eda8f358a4f9a5f8d7787dfb13511b5aa        2020-12-30T03:50:52Z    55m56.313398796s        0
tikv    10.0.2.82:20160 10.0.2.82:20180 5.0.0-alpha     d71c78ef7c74b65e429ce24bd91389d06eb8ec0b        2020-12-30T03:49:54Z    56m54.313402256s        0
tikv    10.0.2.78:20160 10.0.2.78:20180 5.0.0-alpha     d71c78ef7c74b65e429ce24bd91389d06eb8ec0b        2020-12-30T03:50:34Z    56m14.31340542s 0
tikv    10.0.2.76:20160 10.0.2.76:20180 5.0.0-alpha     d71c78ef7c74b65e429ce24bd91389d06eb8ec0b        2020-12-30T03:50:14Z    56m34.313408671s        0
```

### 4. What is your TiDB version? (Required)

Check the above output

**Comment by jebter** [comment]
This issue cannot be reproduced in the latest version 8.1.0. I will close it. Please try the latest version. If there are any updates, you can reopen it.
