### ISSUE TITLE
start tidb service failed

### ISSUE THREAD

**Issue by alex-jin** [pingcap/tidb#22189]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. contennt of topo.yaml (same as in document)

  global:
   user: "tidb"
   ssh_port: 22
   deploy_dir: "/tidb-deploy"
   data_dir: "/tidb-data"
  
  monitored:
   node_exporter_port: 9100
   blackbox_exporter_port: 9115
  
  server_configs:
   tidb:
     log.slow-threshold: 300
   tikv:
     readpool.storage.use-unified-pool: false
     readpool.coprocessor.use-unified-pool: true
   pd:
     replication.enable-placement-rules: true
     replication.location-labels: ["host"]
   tiflash:
     logger.level: "info"
  
  pd_servers:
   - host: 172.21.64.26
  
  tidb_servers:
   - host: 172.21.64.26
  
  tikv_servers:
   - host: 172.21.64.26
     port: 20160
     status_port: 20180
     config:
       server.labels: { host: "logic-host-1" }
  
   - host: 172.21.64.26
     port: 20161
     status_port: 20181
     config:
       server.labels: { host: "logic-host-2" }
  
   - host: 172.21.64.26
     port: 20162
     status_port: 20182
     config:
       server.labels: { host: "logic-host-3" }
  
  tiflash_servers:
   - host: 172.21.64.26
  
  monitoring_servers:
   - host: 172.21.64.26
  
  grafana_servers:
   - host: 172.21.64.26

2. tiup cluster deploy myti20210103 v4.0.8 ./topo.yaml --user root -p 
3. tiup cluster start myti20210103

### 2. What did you expect to see? (Required)
deploy succeed
### 3. What did you see instead (Required)
Starting component `cluster`: /root/.tiup/components/cluster/v1.3.1/tiup-cluster start myti20210103
Starting cluster myti20210103...
+ [ Serial ] - SSHKeySet: privateKey=/root/.tiup/storage/cluster/clusters/myti20210103/ssh/id_rsa, publicKey=/root/.tiup/storage/cluster/clusters/myti20210103/ssh/id_rsa.pub
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [Parallel] - UserSSH: user=tidb, host=172.21.64.26
+ [ Serial ] - StartCluster
Starting component pd
	Starting instance pd 172.21.64.26:2379
	Start pd 172.21.64.26:2379 success
Starting component node_exporter
	Starting instance 172.21.64.26
	Start 172.21.64.26 success
Starting component blackbox_exporter
	Starting instance 172.21.64.26
	Start 172.21.64.26 success
Starting component tikv
	Starting instance tikv 172.21.64.26:20162
	Starting instance tikv 172.21.64.26:20160
	Starting instance tikv 172.21.64.26:20161
	Start tikv 172.21.64.26:20162 success
	Start tikv 172.21.64.26:20160 success
	Start tikv 172.21.64.26:20161 success
Starting component tidb
	Starting instance tidb 172.21.64.26:4000

Error: failed to start tidb: failed to start: tidb 172.21.64.26:4000, please check the instance's log(/tidb-deploy/tidb-4000/log) for more detail.: timed out waiting for port 4000 to be started after 2m0s

Verbose debug logs has been written to /root/.tiup/logs/tiup-cluster-debug-2021-01-05-21-07-36.log.
Error: run `/root/.tiup/components/cluster/v1.3.1/tiup-cluster` (wd:/root/.tiup/data/SLDyckF) failed: exit status 1

/tidb-deploy/tidb-4000/log/tidb_stderr.log file is empty.

below is ubuntu /var/log/syslog. ubuntu version is 16.04
Jan  5 21:14:13 localhost systemd[1]: tidb-4000.service: Service hold-off time over, scheduling restart.
Jan  5 21:14:13 localhost systemd[1]: Stopped tidb service.
Jan  5 21:14:13 localhost systemd[1]: Started tidb service.
Jan  5 21:14:13 localhost run_tidb.sh[18550]: [2021/01/05 21:14:13.444 +08:00] [FATAL] [terror.go:257] ["unexpected error"] [error="open /run/lxcfs/controllers/cpu,cpuacct/system.slice/cpu.cfs_quota_us: permission denied"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20201022083903-fbe80b0c40bb/terror/terror.go:257\nmain.setGlobalVars\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/src/github.com/pingcap/tidb/tidb-server/main.go:509\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/src/github.com/pingcap/tidb/tidb-server/main.go:172\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"] [stack="github.com/pingcap/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20201022083903-fbe80b0c40bb/terror/terror.go:257\nmain.setGlobalVars\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/src/github.com/pingcap/tidb/tidb-server/main.go:509\nmain.main\n\t/home/jenkins/agent/workspace/tidb_v4.0.8/go/src/github.com/pingcap/tidb/tidb-server/main.go:172\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:203"]
Jan  5 21:14:13 localhost systemd[1]: tidb-4000.service: Main process exited, code=exited, status=1/FAILURE
Jan  5 21:14:13 localhost systemd[1]: tidb-4000.service: Unit entered failed state.
Jan  5 21:14:13 localhost systemd[1]: tidb-4000.service: Failed with result 'exit-code'.
### 4. What is your TiDB version? (Required)
v4.0.8

**Comment by wjhuang2016** [comment]
Hi，@alex-jin 
Please post your problem to https://asktug.com.  They would reply to your problem ASAP.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
