### ISSUE TITLE
Upgrade go version to 1.16.4

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#22198]
## Development Task

TiDB uses go version 1.13.4 currently. If we want to use the newer version, we need more tests for it.
We have better to discuss what tests we need in this issue.

**Comment by wjhuang2016** [comment]
@zz-jason @shuke987 PTAL

**Comment by morgo** [comment]
I am not a mac user, but I expect users will soon want to build with go 1.16 because of the native M1 support.

**Comment by tisonkun** [comment]
@wjhuang2016 I'd suggest change the title name to `Upgrade Go Version to 1.16` and thus we get it clear.

I know that @CadmusJiang and @zhouqiang-cl are in charge for upgrading Go Version to 1.16 and most of validation works are done manually. Hopefully we get it done in this month and I'd like to use this existing issue as a tracking issue.

Upgrading the whole TiDB stack Go Version including

- pingcap/tidb
- tikv/pd issue to be created
- pingcap/tidb-binlog issue to be created
- pingcap/br issue to be created
- pingcap/ticdc issue to be created
- pingcap/dm issue to be created
- pingcap/dumpling issue to be created

**Comment by CadmusJiang** [comment]
Get go1.16 image:  `docker pull hub.pingcap.net/pingcap/centos7_golang-1.16:latest`

**Comment by tisonkun** [comment]
possible failure case: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/5742/pipeline

**Comment by tisonkun** [comment]
closed by #24527 

other repository upgrade will be tracked in issues linked above.

**Comment by tisonkun** [comment]
cc @wjhuang2016

**Comment by purelind** [comment]
@tisonkun @nolouch pd jenkins ci already upgrade go version from 1.13 to 1.16.4 (only branch master)

**Comment by tisonkun** [comment]
@purelind thanks for your information. I've done the code upgrade part.

**Comment by purelind** [comment]
@tisonkun @Ehco1996 @lance6716 dm jenkins ci already upgrade go version from 1.13 to 1.16.4 (branch master only)

**Comment by purelind** [comment]
@tisonkun @BusyJay tikv integration test ci already upgrade go version from 1.13 to 1.16.4 (branch master only)

**Comment by purelind** [comment]
@tisonkun @3pointer @overvenus @amyangfei  binlog / br / ticdc ci already upgrade go version from 1.13 to 1.16.4 (branch master only)

**Comment by tisonkun** [comment]
closed as almost done. Let tidb-operator tracks in pingcap/tidb-operator#3988 by itself.
