### ISSUE TITLE
undefined: yySymType

### ISSUE THREAD

**Issue by idlesummerbreeze** [pingcap/tidb#2220]
Hello TiDB's developer,

I tired to build TiDB from master branch and it run into these following errors:

# github.com/pingcap/tipb/go-binlog
/home/dev/go/src/github.com/pingcap/tipb/go-binlog/cistern.pb.go:130: undefined: grpc.SupportPackageIsVersion3
/home/dev/go/src/github.com/pingcap/tipb/go-binlog/pump.pb.go:159: undefined: grpc.SupportPackageIsVersion3
# github.com/pingcap/tidb/parser
/home/dev/go/src/github.com/pingcap/tidb/parser/lexer.go:92: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/misc.go:494: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/yy_parser.go:60: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/yy_parser.go:61: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/yy_parser.go:62: undefined: yySymType

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze Please use `make` to build the project. Do not use `go build`.

**Comment by tiancaiamao** [comment]
Should we add it to FAQ or put parser.go in the repo? @shenli

**Comment by idlesummerbreeze** [comment]
Hi Shenli,

thx for your help! Did you mean that man only need to run make under the project folder? I did it, but saw simliar errors below:

# github.com/pingcap/tidb/parser
/home/dev/go/src/github.com/pingcap/tidb/parser/lexer.go:92: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/misc.go:494: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/yy_parser.go:60: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/yy_parser.go:61: undefined: yySymType
/home/dev/go/src/github.com/pingcap/tidb/parser/yy_parser.go:62: undefined: yySymType

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze Do you put tidb dir in GOPATH?
From your error log, it seems that there is no parser.go in parser dir. Could you should me the file list in parser package?

**Comment by idlesummerbreeze** [comment]
HI @shenli ,

I see the mentioned file there:

drwxr-xr-x  4 dev dev    4096 Dec 10 20:39 ./
drwxr-xr-x 36 dev dev    4096 Dec 10 22:20 ../
drwxr-xr-x  2 dev dev    4096 Dec  9 23:00 goyacc/
-rw-r--r--  1 dev dev   13653 Dec  9 23:00 lexer.go
-rw-r--r--  1 dev dev    5647 Dec  9 23:00 lexer_test.go
-rw-r--r--  1 dev dev   15523 Dec  9 23:00 misc.go
drwxr-xr-x  2 dev dev    4096 Dec  9 23:00 opcode/
-rw-r--r--  1 dev dev 3980691 Dec 10 20:39 **parser.go**
-rw-r--r--  1 dev dev   51621 Dec  9 23:00 parser_test.go
-rw-r--r--  1 dev dev  115615 Dec  9 23:00 parser.y
-rw-r--r--  1 dev dev    5158 Dec  9 23:00 yy_parser.go

Regards,
Yu

**Comment by idlesummerbreeze** [comment]
Hello @shenli ,

any new idea? what could be the reason of this compilation error?

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze Could you show me your GOPATH and the absolute path of your TiDB source code?
Please make sure that TiDB's source code is in your GOPATH.

**Comment by idlesummerbreeze** [comment]
Hi @shenli,

I get it now. I copy the text from the FAQ here. I think that the description below is not so much precise. The steps should be:

1. under a directory for example $HOME/tidb: git clone 
2. run git get
3. go to the directory: $GOPATH/github.com/pingcap/tidb and then run make parser
4. go to the directory: $HOME/tidb and then run make. 

Regards,
Yu

 
使用go get方式安装TiDB为什么报错了?

**请手动将TiDB克隆到GOPATH目录，然后运行make命令**。TiDB是一个项目而不是一个库，它的依赖比较复杂，并且parser也是根据parser.y生成的，我们不支持go get方式，而是使用Makefile来管理。

如果你是开发者并且熟习Go语言，你可以尝试在TiDB项目的根目录运行make parser; ln -s _vendor/src vendor，之后就可以使用go run, go test go install等命令，但是并不推荐这种做法。

**Comment by romber2001** [comment]
i got the same error, and when i run make parser command, it shows error:
remove this command later, when our CI script doesn't call it

what do i suppose to do ?
