### ISSUE TITLE
from_unixtime does not accept 64-bit integers

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#22206]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiDB suffers from the same bug as MySQL https://bugs.mysql.com/bug.php?id=102157 
```
mysql> select from_unixtime(5000000000);
+---------------------------+
| from_unixtime(5000000000) |
+---------------------------+
| NULL                      |
+---------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

Even though the data type `TIMESTAMP` still needs to be fixed to handle 64-bit values, there is a usecase for `FROM_UNIXTIME` to be fixed now. Y2K38 will be here soon.

### 3. What did you see instead (Required)

`NULL`

### 4. What is your TiDB version? (Required)

```sql
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-1976-g9f6b8482e-dirty
Edition: Community
Git Commit Hash: 9f6b8482e05df2431f9a14e236e9bd05ab2ea777
Git Branch: security-enhanced-2
UTC Build Time: 2021-01-06 02:04:32
GoVersion: go1.13.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)```

**Comment by TszKitLo40** [comment]
Should we fix it now or after it has been fixed by MySQL?

**Comment by morgo** [comment]
> Should we fix it now or keep compatible with MySQL?

Since MySQL acknowledges it is a bug, it should be fine to fix now. We are only 17 years away from it breaking.
