### ISSUE TITLE
read packet timeout, close this connection

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#22230]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After execute lots of random SQL, TiDB report
```
show tables;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```
And tidb-server reports
```
["read packet timeout, close this connection"] [conn=60057] [idle=1.000184459s] [waitTimeout=1] [error="read tcp 127.0.0.1:4000->127.0.0.1:38864: i/o timeout"]
```

### 2. What did you expect to see? (Required)
table shows

### 3. What did you see instead (Required)
```
["read packet timeout, close this connection"] [conn=60057] [idle=1.000184459s] [waitTimeout=1] [error="read tcp 127.0.0.1:4000->127.0.0.1:38864: i/o timeout"]
```

### 4. What is your TiDB version? (Required)

```
 Release Version: v4.0.0-beta.2-1968-g4bfd10cec
Edition: Community
Git Commit Hash: 4bfd10cec89dd1640c82441ac8f4939304134662
Git Branch: master
UTC Build Time: 2021-01-05 12:47:53
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by morgo** [comment]
@zhouqiang-cl I spent a little bit too much time looking at this, but it is not a bug :-)

The error message shows:
> [idle=1.000184459s] [waitTimeout=1]

So it looks like your `wait_timeout` (or `interactive_timeout` as it applies to sessions with the interactive bit set) has been set to only 1 second. I can reproduce it on my side with a 1 or 2 second timeout and deliberately pausing after creating a connection:

```
[2021/03/01 14:40:11.376 -07:00] [INFO] [conn.go:757] ["read packet timeout, close this connection"] [conn=5] [idle=1.00011459s] [waitTimeout=1] [error="read tcp 127.0.0.1:4000->127.0.0.1:43960: i/o timeout"]
[2021/03/01 14:40:16.405 -07:00] [INFO] [conn.go:757] ["read packet timeout, close this connection"] [conn=6] [idle=2.000149242s] [waitTimeout=2] [error="read tcp 127.0.0.1:4000->127.0.0.1:43974: i/o timeout"]
```

**Comment by zhouqiang-cl** [comment]
> interactive_timeout

Got it, thank you @morgo
