### ISSUE TITLE
The type of column and default value don't match

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#2229]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
 CREATE TABLE ttt (id int(11) DEFAULT now());

2. What did you expect to see?
ERROR 1067 (42000): Invalid default value for 'id'

3. What did you see instead?
Query OK, 0 rows affected (0.01 sec)

**Comment by yuanwhy** [comment]
@zimulala the bug is fixed, so close the issue ?

**Comment by zz-jason** [comment]
this issue is fixed.
