### ISSUE TITLE
How to embed rocksdb into tidb, I only see that leveldb is embedded！

### ISSUE THREAD

**Issue by IT-MorningStar** [pingcap/tidb#22317]

**Comment by bb7133** [comment]
Hi @IT-MorningStar , would you please change the title to English, or do you mind if we do the translateion?

**Comment by zz-jason** [comment]
RocksDB is used in TiKV, which is the storage layer of a TiDB cluster. LevelDB embedded in TiDB is only used for unit tests.

**Comment by IT-MorningStar** [comment]
OK, thank you！

**Comment by ichn-hu** [comment]
@IT-MorningStar Do you have further questions? You are more than welcomed to close the issue yourself if your questions are resovled.
