### ISSUE TITLE
the log() log2() log10() func not affact in

### ISSUE THREAD

**Issue by skybook888** [pingcap/tidb#2232]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
query is  select log(a) from b wil return an error

2. What did you expect to see?

it's work on mysql

3. What did you see instead?

error occured

4. What version of Go are you using (`go version`)?

not so sure, i used the docker from the tutorial 2 months ago

**Comment by shenli** [comment]
@skybook888 Thanks for your feedback! 
We haven't implemented log/log2/log10 in TiDB. Would you please send us a PR to add those functions?

**Comment by hamo** [comment]
@shenli  please help to review #2258 for this issue

**Comment by tiancaiamao** [comment]
TiDB supports those functions now, so I close this issue.
If you find something wrong with those functions, feel free to reopen this issue.
@skybook888
