### ISSUE TITLE
no support builtinfunction instr()

### ISSUE THREAD

**Issue by hyj0** [pingcap/tidb#2234]
https://dev.mysql.com/doc/refman/5.7/en/string-functions.html#function_instr
btw, this doc https://github.com/ngaut/builddatabase/blob/master/tidb/builtin.md seems out of date, parser/scanner.l has been remove, and parser/misc.go instead . ?

**Comment by shenli** [comment]
@hyj0 Thanks for your feedback! 
The document you mentioned is out of date. I will send you an updated document for builtin function this week.
