### ISSUE TITLE
Questions about file system and system tables

### ISSUE THREAD

**Issue by spihiker** [pingcap/tidb#22383]
最近测试、试用了V4.0.9版本的tidb。有2个问题想咨询下：
（1）发现系统表里，有一些字段是timestamp类型。作为长久考虑的产品，会不会有2038的问题？
（2）现在centos7默认文件系统是xfs，但官方文档还是推荐的ext4.请问，有没有在xfs上做过大量测试和生产实践。xfs上运行可靠吗？能否生产环境上使用？
   谢谢！

**Comment by arronliu1989** [comment]
You can also ask questions in Chinese at asktug（asktug.com）, thanks!

**Comment by blacktear23** [comment]
@spihiker 
1. yes, timestamp still have 2038 issue.
2. In CentOS 7 default file system is XFS and you can change it on the installation step. But if not I think you can keep root format as XFS and your data disk (such as /dev/sdb) format as EXT4.

**Comment by morgo** [comment]
The issue to track timestamp Y2K38 is https://github.com/pingcap/tidb/issues/20522

Another solution is to convert to `DATETIME` type.

**Comment by spihiker** [comment]
What do i want to know is XFS suitiable for TIDB in production environment. Thanks.

**Comment by blacktear23** [comment]
I think this is related to history. At begining of TiDB I remembered @ngaut told me xfs triggered some bug on rocksdb. So TiDB best practice is using ext4. So most of tikv is running on ext4, even very large cluster. So for xfs I do not know is there still has some corner case can break rocksdb.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
