### ISSUE TITLE
Latency increased during tidb cluster rolling upgrade

### ISSUE THREAD

**Issue by tennix** [pingcap/tidb#22393]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is not yet reproduced.

TiDB cluster is deployed in k8s, the original procedure is changing the log level of pd/tikv/tidb configuration, and tidb-operator will roll upgrade the whole cluster.

### 2. What did you expect to see? (Required)

Low latency during rolling upgrade

### 3. What did you see instead (Required)

A latency spike appeared during TiKV rolling upgrade.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/7932127/104558203-662c1d80-567d-11eb-9bd7-b8ae5509e33e.png">
<img width="614" alt="image" src="https://user-images.githubusercontent.com/7932127/104558245-7b08b100-567d-11eb-9ba3-bc7eb4970701.png">
The application latency also increased to 13s.

Though the TiKV leader from the Grafana did not drop to zero during tikv upgrade. It did drop to zero from PD's monitoring
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/7932127/104558468-cfac2c00-567d-11eb-9371-34ec784094cc.png">

### 4. What is your TiDB version? (Required)

v4.0.9

**Comment by zyguan** [comment]
No update for a long time, feel free to reopen it if the issue still exists.
