### ISSUE TITLE
feature request support for redisdb kv 

### ISSUE THREAD

**Issue by abdulrahmantkhalifa** [pingcap/tidb#2240]
it would be useful to have support for a more well-known  kv database , for example, Redis DB 
I am already in the process of implementing this but wanted to create a feature request to reference the commit before contributing 

Also , wanted to inquire about SQL benchmark tests , if they are available in the project , to avoid importing  unnecessary packages  for testing

**Comment by coocood** [comment]
@abdulrahmantkhalifa 
Thank you for your willing to contribute.
But I'm sorry, we don't have the plan to support Redis API.
Supporting a new Database API is useful, but it is a long-term commitment, which requires a lot of work on implementation,  documentation, and testing, and most importantly, it makes our existing code much more complicated, increases maintenance cost.

The most welcomed contribution is bug-fix, but that requires understanding the project.
We will be impressed if a contributor can do it without much help.

**Comment by coocood** [comment]
@abdulrahmantkhalifa 
Sorry, I misunderstood your issue.

RedisDB is not an embeded storage engine, I'm not sure if it should be implemented as localstore.

**Comment by coocood** [comment]
@abdulrahmantkhalifa 
For benchmark tests, you can edit `bench_test.go` to use the new engine, and run 
```
go test -run=none -bench=.
``` 
on project directory.
But I guess local store on remote Redis engine will run much slower.

**Comment by abdulrahmantkhalifa** [comment]
thank you for your quick response ; 
the benchmark does not seem to have correct versioning , i tried the command without altering the bench_test.go file just to see if it works ,the results were a fail

**Comment by coocood** [comment]
@abdulrahmantkhalifa 
When we run `go test` vendor is not used.
Try this command
```
GOPATH=$(pwd)/_vendor:$GOPATH go test -bench=. -run=none
```

**Comment by abdulrahmantkhalifa** [comment]
@coocood 
As you said the bench marks are slower on a remote redis , but a local one , not as much.
so concerning the code it will remain on the fork if you require the feature at any point in the future  , inform and i will create a pull request or you can create a pull request yourself , 

thank you again for all your help.

**Comment by coocood** [comment]
@abdulrahmantkhalifa 
Good job to implement the redis store!
I'm sorry we can't accept this feature right now.
Thank you for your understanding.
