### ISSUE TITLE
Got unexpected `Error 1105: Can't find column` when executing tp-test

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#22404]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Not a minimal one. I ran [tp-test](https://github.com/PingCAP-QE/tp-test/tree/tp-test/tp-test) to verify latest release-4.0 and found a test failed with `Error 1105: Can't find column`. It's unexpected because tp-test will create database for each test and there is no related ddl when doing transactions in a test.

[Here](https://gist.github.com/zyguan/2f88c59e911a6c9571a9019de5267eb6) is the failed test and the log of tidb can be found [here](http://fileserver.pingcap.net/download/pingcap/qa/draft/tp-test-ddl-issue.log).

### 2. What did you expect to see? (Required)

No error reported.

### 3. What did you see instead (Required)

Error 1105: Can't find column db1__14c2c3fe_d1e6_40c9_973f_598add7765fb.t2.c_int in schema Column.

### 4. What is your TiDB version? (Required)

release-4.0 (efa487eddc1fd3dafca86a310200fe5d317332c0)

**Comment by eurekaka** [comment]
Minimal reproduction steps:
```sql
drop table if exists t1;
create table t1(c_int int, c_str varchar(40), primary key(c_int, c_str)) partition by hash (c_int) partitions 2;

begin;
insert into t1 values (2, 'bb');
explain select c_str from t1 where (c_int, c_str) in ((4, 'cc')) and (c_int, c_str) in ((3, 'dd'));
```

**Comment by eurekaka** [comment]
master branch(`3dff7cd348666fd31dca0ba50befe748b2a2eb63`) does not has this problem.

**Comment by eurekaka** [comment]
A more simpler reproduction:
```sql
drop table if exists t1;
create table t1(c_int int, c_str varchar(40)) partition by hash (c_int) partitions 2;

begin;
insert into t1 values (2, 'bb');
explain select c_str from t1 where c_int = 1 and c_int = 2;
```

**Comment by eurekaka** [comment]
This can be fixed by https://github.com/pingcap/tidb/pull/21640, but it was not cherry-picked to 4.0.

**Comment by winoros** [comment]
https://github.com/pingcap/tidb/pull/22624 4.0's PR merged.
