### ISSUE TITLE
i find a vulnerability of tidb it can crash tidb remote how i can connect you i have not found mail of you

### ISSUE THREAD

**Issue by Z000000** [pingcap/tidb#2242]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Go are you using (`go version`)?

**Comment by Z000000** [comment]
if you hava read it  please send email   xmaszh@gmail.com

**Comment by shenli** [comment]
@Z000000 Thanks for your report! I sent an email to you.

**Comment by Z000000** [comment]
have you confirmed?

**Comment by shenli** [comment]
@Z000000 Confirmed! We are working on this. Thanks very much!
