### ISSUE TITLE
Automatic Partition Maintenance

### ISSUE THREAD

**Issue by ethan7811** [pingcap/tidb#22441]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

For time range partitioned table,  tidb does not have a mechanism to  automatic drop partition after xx days and add new partition for new day (which can implemented by stored procedure and event), so how can i maintain fix days partition automatically in tidb?

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by morgo** [comment]
I think this is a duplicate of https://github.com/pingcap/tidb/issues/19132 , would you agree?

The title says "add partition automatically", but the feature request refers to INTERVAL PARTITIONING and ttl tables.

**Comment by zz-jason** [comment]
Yes, I think we can track the progress in https://github.com/pingcap/tidb/issues/19132
