### ISSUE TITLE
Does tidb support MySQL builtin function `find_in_set`?

### ISSUE THREAD

**Issue by bhzhu203** [pingcap/tidb#2244]
tidb支持  find_in_set 这个mysql函数吗 ，还有多少个函数还没有支持的？
select id,count(id) as cnt from (select a.id,b.sale_adviser from ebk_refunds a inner join ebk_acoin_orders b on find_in_set(b.id,a.buy_ids) where a.post_time between 1477929600 and 1480521599 and a.money>0 group by a.id,b.sale_adviser) tbl group by id having cnt>1;

ERROR 1105 (HY000): line 0 column 124 near "b.id,a.buy_ids) where a.post_time between 1477929600 and 1480521599 and a.money>0 group by a.id,b.sale_adviser) tbl group by id having cnt>1"

最新版本的tidb，

**Comment by coocood** [comment]
No, this function has not been supported yet, supported functions can be found here
https://github.com/pingcap/tidb/blob/master/evaluator/builtin.go

**Comment by kaiwu** [comment]
@bhzhu203 please notice that `find_in_set` can be mostly handled directly using approach like [this](https://www.periscopedata.com/blog/splitting-comma-separated-values-in-mysql.html)

**Comment by ngaut** [comment]
@bhzhu203 We have supported the find_in_set function, feel free to open the issue if you have any questions.
