### ISSUE TITLE
Cannot see DB when connect TiDB with navicat

### ISSUE THREAD

**Issue by bhzhu203** [pingcap/tidb#2245]
使用navicat 连接tidb的时候看不到DB，navicat 11.017-premium，tidb最新版本

是不是因为在tidb中
 INFORMATION_SCHEMA |
| PERFORMANCE_SCHEMA

这2个数据库是大写的缘故

**Comment by shenli** [comment]
@bhzhu203 Please try the latest navicat.
We are working on the compatible problems between TiDB and old version navicat.

**Comment by iroi44** [comment]
@bhzhu203  Thanks a lot for your interest in TiDB.  You can send an email to info@pingcap.com. We can assist you in person in case you encounter other problem.

**Comment by breeswish** [comment]
Just tried with Navicat 11.0.17 and latest TiDB, works well.
