### ISSUE TITLE
PD cannot store the configuration persistently

### ISSUE THREAD

**Issue by wangtianyi2004** [pingcap/tidb#22498]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
I use ./pd-ctl -u http://XXXX:22379 store limit all 20 command to update the store limitation. 
But after I restart the pd leader, the store limit change to the default value 15.
More details as following 
[root@r10 bin]# ./pd-ctl -u http://r11:22379 store limit
{
 "1": {
 "add-peer": 15,
 "remove-peer": 15
 },
 "4": {
 "add-peer": 15,
 "remove-peer": 15
 },
 "5": {
 "add-peer": 15,
 "remove-peer": 15
 }
}

[root@r10 bin]# ./pd-ctl -u http://r11:22379 store limit all 20
Success!

192.168.12.11:22379 pd 192.168.12.11 22379/22380 linux/x86_64 Up|L /opt/tidb/data/pd-22379 /opt/tidb/pd-22379

[root@r11 ~]# systemctl restart pd-22379

[root@r10 bin]# ./pd-ctl -u http://r11:22379 store limit
{
  "1": {
    "add-peer": 15,
    "remove-peer": 15
  },
  "4": {
    "add-peer": 15,
    "remove-peer": 15
  },
  "5": {
    "add-peer": 15,
    "remove-peer": 15
  }
}

### 2. What did you expect to see? (Required)
The store limitation should be store in etcd persistently.

### 3. What did you see instead (Required)
After the pd leader restart, the store limitation change to the default values 15. 

### 4. What is your TiDB version? (Required)
v4.0.9

**Comment by rleungx** [comment]
It has been fixed in v4.0.11 and you can find more details in https://github.com/tikv/pd/pull/3380

**Comment by nolouch** [comment]
fixed.
