### ISSUE TITLE
The coprocessor cache dashboard doesn't work in Grafana

### ISSUE THREAD

**Issue by wangtianyi2004** [pingcap/tidb#22493]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
The dashboard TiDB -> distsql -> coprocessor cache  doen't work 

![image](https://user-images.githubusercontent.com/16875363/105459807-d104d680-5cc5-11eb-8513-10d8932bdfc9.png)

I check the method in Grafana for this dashboard, it show me 
histogram_quantile(1, sum(rate(tidb_distsql_copr_cache_buckets[1m])) by (type))

It seems tidb_distsql_copr_cache_bucket here for this method. 

### 2. What did you expect to see? (Required)
The Grafana should be works here. 

### 3. What did you see instead (Required)
No data point.

### 4. What is your TiDB version? (Required)

v4.0.9

**Comment by breeswish** [comment]
@lzmhhh123 Please take a look to see whether this is a known problem. Thanks!

**Comment by jebter** [comment]
Please try the latest version. I will close it, if there are any updates, you can reopen it.
