### ISSUE TITLE
Feature Request: add `up` to metrics

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb#2250]
In order to monitor process uptime in prometheus, I need something like:

```
uptime{instance="172.233.1.196:3306",job="tidb"}
```

in metrics.
counts from 0 in seconds.

**Comment by andelf** [comment]
EDIT: use ``uptime`` instead of ``up``.

**Comment by c4pt0r** [comment]
LGTM

**Comment by nullnotnil** [comment]
These statistics are now available in prometheus. I am going to close this issue now. Thanks!
