### ISSUE TITLE
Is the tiflash source code open source?

### ISSUE THREAD

**Issue by newHE3DBer** [pingcap/tidb#22553]
## Question

Whether the tiflash source code is open source, if it is open source, please tell the tiflash source code address, if it is not open source, please tell when you plan to open source

**Comment by ilovesoup** [comment]
TiFlash is on its way for open sourcing. It is closed source for now because we haven't got time cleaning up code and other related stuff. The schedule is within this year.

**Comment by nautaa** [comment]
how is the progress

**Comment by zhiweio** [comment]
Can you tell us that which coding language the TiFlash written by?

**Comment by raintean** [comment]
> 

C++?

**Comment by mickar** [comment]
Hello,
Have you any news ?

**Comment by it2911** [comment]
> Hello, Have you any news ?

TiFlash have been open source at 4/1. Please confirm it link below.
https://github.com/pingcap/tiflash
