### ISSUE TITLE
tidb always crash

### ISSUE THREAD

**Issue by yester354** [pingcap/tidb#22569]
version tidb 3.0.5
tidb always crash ,when i restart tidb process,it can work right,but after a few minutes ,it crash,one time after another
errors as below:
ithub.com/pingcap/errors.AddStack
        github.com/pingcap/errors@v0.11.4/errors.go:174
github.com/pingcap/errors.Trace
        github.com/pingcap/errors@v0.11.4/juju_adaptor.go:15
github.com/pingcap/tidb/server.(*packetIO).flush
        github.com/pingcap/tidb@/server/packetio.go:172
github.com/pingcap/tidb/server.(*clientConn).flush
        github.com/pingcap/tidb@/server/conn.go:961
github.com/pingcap/tidb/server.(*clientConn).writeError
        github.com/pingcap/tidb@/server/conn.go:1025
github.com/pingcap/tidb/server.(*clientConn).Run
        github.com/pingcap/tidb@/server/conn.go:689
github.com/pingcap/tidb/server.(*Server).onConn
        github.com/pingcap/tidb@/server/server.go:440
runtime.goexit
        runtime/asm_amd64.s:1357

**Comment by buggithubs** [comment]
@yester354 Please provide the following **tidb-server** startup parameters

**Comment by yester354** [comment]
> @yester354 Please provide the following **tidb-server** startup parameters
startup parameters as below:
# TiDB Configuration.

compatible-kill-query = false
enable-streaming = false
host = "0.0.0.0"
lease = "45s"
lower-case-table-names = 2
oom-action = "log"
run-ddl = true
socket = "/tmp/mysql4000.sock"
split-table = true
store = "tikv"
token-limit = 1000

[log]
disable-timestamp = false
expensive-threshold = 10000
format = "text"
level = "info"
query-log-max-len = 2048
slow-threshold = 300

[log.file]
log-rotate = true
max-backups = 0
max-days = 0
max-size = 300

[security]
cluster-ssl-ca = ""
cluster-ssl-cert = ""
cluster-ssl-key = ""
ssl-ca = ""
ssl-cert = ""
ssl-key = ""

[status]
report-status = true

[performance]
cross-join = true
feedback-probability = 0.05
force-priority = "NO_PRIORITY"
max-procs = 0
pseudo-estimate-ratio = 0.8
query-feedback-limit = 1024
run-auto-analyze = true
stats-lease = "3s"
stmt-count-limit = 5000
tcp-keep-alive = true

[proxy-protocol]
header-timeout = 5
networks = ""

[prepared-plan-cache]
capacity = 100
enabled = false
memory-guard-ratio = 0.1

[opentracing]
enable = false
rpc-metrics = false

[opentracing.reporter]
buffer-flush-interval = 0
local-agent-host-port = ""
log-spans = false
queue-size = 0

[opentracing.sampler]
max-operations = 0
param = 1.0
sampling-refresh-interval = 0
sampling-server-url = ""
type = "const"

[tikv-client]
commit-timeout = "41s"
grpc-connection-count = 16
grpc-keepalive-time = 10
grpc-keepalive-timeout = 3

[txn-local-latches]
capacity = 2048000
enabled = true

[binlog]
ignore-error = false
write-timeout = "15s"

[pessimistic-txn]
default = false
enable = false
max-retry-count = 256
ttl = "30s"

**Comment by wjhuang2016** [comment]
Handled in AskTUG https://asktug.com/t/topic/68239
