### ISSUE TITLE
Can't find column when using group concat

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#22573]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t` (
  `a` time DEFAULT NULL
);
desc select group_concat(c order by b), min(c) as d from (select a as b, x.a as c from t x) tx;
```

### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)
```
mysql> desc select group_concat(c order by b), min(c) as d from (select a as b, x.a as c from t x) tx;
ERROR 1105 (HY000): Can't find column test.tx.b in schema Column: [test.x.a] Unique key: []
```
### 4. What is your TiDB version? (Required)

v3.0.16

**Comment by eurekaka** [comment]
Latest master and 4.0 has fixed this error in the last round of refactor for expression package, those changes I suppose are pretty hard to be cherry-picked to 3.0.
