### ISSUE TITLE
Support spill HashAgg to disk

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#22611]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, HashAgg cannot spill to disk, which means that large joins that use HashAgg use a huge amount of memory and can trigger OOM.

**Describe the feature you'd like:**

Support spilling HashAgg to disk! 🙂

https://github.com/eurekaka/tidb/commit/b2f70d17c0c20b3cc5fdcf6a7522b10d9d67744e is one implementation of this that could be considered.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tisonkun** [comment]
closed as superseded by https://github.com/pingcap/tidb/issues/25882
