### ISSUE TITLE
BR in sql performance issue

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#22637]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

This bug is found by @cosven. And @overvenus is working on the investigation.

### 1. Minimal reproduce step (Required)

Restore 2TB tpcc data via br in sql

### 2. What did you expect to see? (Required)
Expect performance as binary. 

### 3. What did you see instead (Required)
As you can see in the below picture, the first 2 binary br restores works w/ reasonable duration, the last one br in SQL restore is much slower than binary.
<img width="916" alt="WeChatWorkScreenshot_e74d579d-1d18-4ae3-bfdc-b544a2a49083" src="https://user-images.githubusercontent.com/35356271/106408854-3e5cf800-647a-11eb-886d-209d070fbdf9.png">

### 4. What is your TiDB version? (Required)

```
tidb_version()
Release Version: v4.0.0-beta.2-2079-gea6ccf82e
Edition: Community
Git Commit Hash: ea6ccf82e93415e07a1310d335f5b6a36ac304cb
Git Branch: master
UTC Build Time: 2021-01-29 05:00:57
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

```

**Comment by YuJuncen** [comment]
The concurrency of BRIE via SQL seems is always `4`.

**Comment by 3pointer** [comment]
Close it since it's a concurrency parameter issue. you can try `mysql> restore database test to 'xxx' concurrency=128;` to work around.
