### ISSUE TITLE
Add the index key prefix limit

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#2272]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
 create table t(a varchar(3073), index(a));
 create table t(a varchar(1073), b varchar(2000), index(a, b));

2. What did you expect to see?

ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes

3. What did you see instead?

Query OK, 0 rows affected (0.00 sec)

**Comment by idlesummerbreeze** [comment]
Hi @zimulala,

may I give it a try to fix the problem?

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze Of course! If you need any help, please let us know.

**Comment by idlesummerbreeze** [comment]
Hi @shenli,

if a field is defined with int or char, how can I know how many bytes does this field take? The code below return a ColumnInfo but its Flen is -1.

`findCol(tblInfo.Columns, ic.Column.Name.O)`

**Comment by shenli** [comment]
@idlesummerbreeze -1  means unspecified field length. 
For integer, we do not to care about field length. For char/varchar, if you define a column with field length, we will store it in Flen field.

**Comment by ngaut** [comment]
Thank you for asking. @idlesummerbreeze 

Since -1 makes us confused, we should define it as constant. @shenli

**Comment by shenli** [comment]
@ngaut There is already a constant named UnspecifiedLength in types package.

**Comment by idlesummerbreeze** [comment]
Hi @shenli,

if we cannot get the physical length in byte/char for unspecified columns, we cannot handle the following situation for compound index:

no error:
`create table t(a varchar(3072), index(a));` 

 with error:
`create table t(a varchar(3072), b int, index(a,b));`

ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze You can refer to this doc: http://dev.mysql.com/doc/refman/5.7/en/storage-requirements.html
For each type of integer, there is a specified physical length.

**Comment by idlesummerbreeze** [comment]
Hi @shenli,

the current maxPrefixLength is 767. Should we increase the value to  3072?

I have found a new bug. for example:

`create table (b blob, index(b))`

doesn't run into error. Atually an error is expected: ERROR 1170 (42000): BLOB/TEXT column 'b' used in key specification without a key length.

I'm going to fix this new bug together.

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze Yes it is a bug. I am glade if you could fix it.
For the maxPrefixLength, why you want to increase it to 3072?

**Comment by idlesummerbreeze** [comment]
Hi @shenli,

since @zimulala has written in her comment that it should be 3073. 3073 ist the new max length in mysql 5.7 and 767 is from 5.5. 

by the way, if i want to define the physical size of unspecified types, in which file should i code it.

**Comment by shenli** [comment]
@idlesummerbreeze OK!
You can define those constants in mysql/const.go.

**Comment by zimulala** [comment]
It fixed by #2380
