### ISSUE TITLE
Duplicate rows occur in primary/unique key in optimistic transaction

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#22730]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Use optimistic transaction.
```sql
set @@tidb_txn_mode = '';
```
```sql
commit;
drop table if exists t;
create table t (a enum('A') primary key);
insert into t values ('A');
begin;
insert into t values ('A');
select * from t;
```

### 2. What did you expect to see? (Required)

```console
+---+
| a |
+---+
| A |
+---+
```

### 3. What did you see instead (Required)

```console
+---+
| a |
+---+
| A |
| A |
+---+
```

Other types like `char`, `varchar` and others also have this issue.

### 4. What is your TiDB version? (Required)

master `4c0fe88a710682089dcc0e55dc08c6ada858e69f`

**Comment by tangenta** [comment]
Integer column as the primary key does not have this issue:
```sql
commit;
drop table if exists t;
create table t (a int primary key);
insert into t values (1);
begin;
insert into t values (1);
select * from t;
```
```console
+---+
| a |
+---+
| 1 |
+---+
```

**Comment by morgo** [comment]
I believe this is intentional, and depends on the setting `tidb_constraint_check_in_place`:
```sql
mysql> set tidb_constraint_check_in_place = 1;
Query OK, 0 rows affected (0.00 sec)

mysql> set @@tidb_txn_mode = '';
Query OK, 0 rows affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> drop table if exists t;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t (a enum('A') primary key);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values ('A');
Query OK, 1 row affected (0.00 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> insert into t values ('A');
ERROR 1062 (23000): Duplicate entry 'A' for key 'PRIMARY'
mysql> select * from t;
+---+
| a |
+---+
| A |
+---+
1 row in set (0.00 sec)

```

**Comment by cfzjywxk** [comment]
I think it's the expected behaviours and not a bug for the optimistic transactions just like the `affected rows` field. For optimistic transactions, the related constraint check or affected rows calculation may not be accurate during the execution.

**Comment by lysu** [comment]
the inconsist behavior seems be caused by those addition check

https://github.com/pingcap/tidb/blob/47a182f76a2185cf1778174fc22d00e0416154a3/executor/union_scan.go#L217-L227

it only do additional dup check in intHandle..

however, no matter what user saw in side transaction block, it could NOT commit success, maybe not a bug +1

**Comment by tangenta** [comment]
So we are not planning to fix this inconsistency, right?

**Comment by lysu** [comment]
> So we are not planning to fix this inconsistency, right?

IMHO, maybe we can keep current impl - -    how do you think about this  @coocood @cfzjywxk

**Comment by tangenta** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/24195.
