### ISSUE TITLE
Build failed because of existing LDFLAGS env var

### ISSUE THREAD

**Issue by silentred** [pingcap/tidb#2274]
An existing LDFLAGS will cause build failure. In my case, I set LDFLAGS=-L/lib/path long time age. So `make server` reports error with flag package. 
Do you think it should be `LDFLAGS = ` instead of `+=` at https://github.com/pingcap/tidb/blob/master/Makefile#L22 ?

**Comment by shenli** [comment]
@silentred I think it is OK to change L22 from '+=' to '='.

**Comment by morgo** [comment]
@silentred I wanted to follow up and check-in.  Some time has elapsed, can we close this issue?

**Comment by silentred** [comment]
> @silentred I wanted to follow up and check-in. Some time has elapsed, can we close this issue?

Feel free to close this issue.
