### ISSUE TITLE
Add TTL Table support to automatically reclaim data with given retention policy and garbage collect granularity.

### ISSUE THREAD

**Issue by sunxiaoguang** [pingcap/tidb#22762]
## Feature Request

**Describe the feature you'd like:**
Add TTL Table support to automatically reclaim data with given retention policy and garbage collect granularity.

**Describe alternatives you've considered:**
Manually reclaiming expired data.

**Teachability, Documentation, Adoption, Migration Strategy:**
It's pretty straightforward idea and should be understandable by most people, especially for those who have used systems with such capabilities such as Redis.

**Comment by SunRunAway** [comment]
TTL feature is released with TiDB v6.5: https://docs.pingcap.com/tidb/stable/time-to-live#periodically-delete-expired-data-using-ttl-time-to-live

tracking issue: https://github.com/pingcap/tidb/issues/39262
