### ISSUE TITLE
Why sqls on information_schema is handled differently?

### ISSUE THREAD

**Issue by idlesummerbreeze** [pingcap/tidb#2278]
Hello TiDB's team,

I am learning the source code and debuging some executors. I have seen that sqls on information_schema is differently handled in compare to those sqls on test schema. Could you please explain me the reason and your desgin behind it?

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze information_schema is a virtual table which exists only in the memory of tidb-server.
For most of sql statements, we need to refer to schema/table/index/column information when we building query plans. We keep all those info in the memory for performance consideration. So we do not need to store those data as normal tables, we could get what we need from the memory.

**Comment by idlesummerbreeze** [comment]
Hi @shenli ,

thx for your answer! Are there more documents about the Inside of TiDB? 

Regards,
Yu

**Comment by shenli** [comment]
I am writing a document and it will be release in this week. I will keep you updated.

**Comment by idlesummerbreeze** [comment]
@shenli 

That's great!

Regards,
Yu
