### ISSUE TITLE
Scatter region when creating tables is not work

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#22788]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. `set global tidb_scatter_region = 1;`
2. create table without pre-split option in a new session.
3. grep logs of pd leader to find 'add operator' and then 'mv light peer'.

### 2. What did you expect to see? (Required)
Get the operator log.

### 3. What did you see instead (Required)
No this operator log.

### 4. What is your TiDB version? (Required)
c9af430996323e81a7919ba0e3f30db934cf4aee

**Comment by jackysp** [comment]
This pr #20980 introduced it. It used the batch API `ScatterRegions` instead of `ScatterRegion`, but the batched API doesn't have the same behavior as the single API except it will scatter multi-regions. It is not easy to use the single API directly, because pd doesn't have a single API with an option, which is introduced in #19844 . #19844 is an optimization that could not be reverted directly.
PTAL @Yisaer @JmPotato

**Comment by wjhuang2016** [comment]
It seems that the basic test is missing.

**Comment by nolouch** [comment]
fixed.
