### ISSUE TITLE
query result for float type is incompatible with previous version

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#22791]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table tf(f1 float(10,2));
insert into tf values("-34028234.66");
select * from  tf;

### 2. What did you expect to see? (Required)
```
mysql> select * from tf;
+--------------+
| f1           |
+--------------+
| -34028236.00 |
+--------------+
1 row in set (0.00 sec)

```
This result is the same with tidb version v4.0 and mysql.

### 3. What did you see instead (Required)
```
mysql> select * from tf;
+-----------+
| f1        |
+-----------+
| -34028236 |
+-----------+
1 row in set (0.01 sec)

```

Seems the float type logic is changed in the master branch and incompatibility is introduced.

### 4. What is your TiDB version? (Required)
master version with commit hash `9cb9b69b61a76e9cc3f8cfa27f86635c2496cf16`

**Comment by b41sh** [comment]
MySQL don't support FLOAT(M,D) and DOUBLE(M,D) since 8.0.17
https://dev.mysql.com/doc/refman/8.0/en/floating-point-types.html
we ignored decimal in PR [21788](https://github.com/pingcap/tidb/pull/21788)

**Comment by cfzjywxk** [comment]
@b41sh Got, do we have related document to remind users about this incompatibily doing upgrade.

**Comment by b41sh** [comment]
@cfzjywxk  This is recently modified, the document should not have been modified yet.

**Comment by johan-j** [comment]
There is still issues with float type.
To reproduce:
create table t(a float);
insert into t( -34028236.66);

mysql8:
```
+-----------+
| a         |
+-----------+
| -34028200 |
+-----------+

tidb:
+-----------+
| a         |
+-----------+
| -34028236 |
+-----------+

The issue reported here in (22791), seems to have started after https://github.com/pingcap/tidb/pull/21788.

**Comment by johan-j** [comment]
The bug in string representation of floats seem to be because mysql has their own implementation of it as explained here. https://dev.mysql.com/doc/dev/mysql-server/latest/dtoa_8cc.html#ad70328b1022e48cb98875d3dae4a6f32

maybe to resolve these number display bugs, we need to implement the same custom float to string converter? how do you think?

**Comment by johan-j** [comment]
Im working on this in https://github.com/pingcap/tidb/pull/22823

The issue I mention in the comment above:
```
create table t(a float);
insert into t(a) values(-34028236.66);
```
Can be solved without solving the deprecated double(m,n)/float(m,n) compatibility issue mentioned in this issue.
So Im thinking if I should create a new issue for this instead, to track them separately?
So 2 issues:
- https://github.com/pingcap/tidb/issues/22791: query result for float type is incompatible with previous version
- <new issue>: Float column type, returns to specific result

Solving the float(m,n) problem I can do by printing in scientific format, the same way as: https://github.com/pingcap/tidb/issues/21692. If this is OK solution, I can implement that and solve both.

**Comment by xiongjiwei** [comment]
we have a document that says the [difference](https://docs.pingcap.com/zh/tidb/stable/data-type-numeric#:~:text=%E4%B8%8E%E5%9C%A8%20MySQL,123456790%20%E5%92%8C%201.2345679%E3%80%82)

**Comment by bb7133** [comment]
Close it since we decide not to fix it.
