### ISSUE TITLE
How to add second disk for TiKV

### ISSUE THREAD

**Issue by alex-quan-001** [pingcap/tidb#22797]
## General Question

I have two SSD disk, how to config it to use the second SSD disk.
Currently the documentation only provides the way to raid, but my first fast disk is almost full, how to expand the second disk up.
Here is a post about the same problem, but did not answer directly whether it is feasible
https://asktug.com/t/topic/34251

**Comment by zhangjinpeng1987** [comment]
One TiKV instance only can use one data-dir.

**Comment by jebter** [comment]
The answer has been given above.The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
