### ISSUE TITLE
How to run a single test?

### ISSUE THREAD

**Issue by idlesummerbreeze** [pingcap/tidb#2279]
Hello TiDB's team,

I am going to run a single test function under the executor package in the following way:

go test -v -run TestAggregation

Though there was no errors, it seems that the test doesn't get executed in this way.

Regards,
Yu

**Comment by shenli** [comment]
@idlesummerbreeze Try this: go test -check.f TestAggregation

**Comment by idlesummerbreeze** [comment]
@shenli thx! it works with gocheck.
