### ISSUE TITLE
Add FileSort in util package

### ISSUE THREAD

**Issue by yanzhe-chen** [pingcap/tidb#2283]
Used by SortExec in executor/executor.go.

Required since the input might exceed the memory capacity.

A typical interface of FileSort might look like this:

```
type FileSorter struct {
    
}

func (fs *FileSorter) Input(row []types.Datum, byIdx []int, byDesc []bool) {
    
}

func (fs *FileSorter) Output() []types.Datum {
    return nil
}
```

Caller need to create a instance of `FileSorter` to sort a group of input.

Input is fed by calling `Input` method.

Sorted output can be lazily fetched by calling `Output` method.

Caller needs to follow the strict usage pattern: **N** times `Input` followed by **N** times `Output`.

Any violation of this pattern should throw an error.

**Comment by mccxj** [comment]
@coocood maybe we should close it.

**Comment by coocood** [comment]
@mccxj  thanks for the remind
