### ISSUE TITLE
Need more tests on DDL/transaction conflicts and parallel executions

### ISSUE THREAD

**Issue by xhebox** [pingcap/tidb#22849]
## Development Task

The bug of #22819 is fixed, though. We should have more tests about DDL/transaction conflicts in CI or somewhere. There is only `grep -r -H 8028 | wc -l == 6` tests about this error.

And `grep -r -H testControlParallelExecSQL | wc -l == 23` tests in `db_change_test.go` that executes different SQLs in parallel. `grep -r -H testParallelExec | wc -l == 17` tests that executes same SQL in parallel. Little parallel tests and they are not related to transaction at all.

**Comment by AilinKid** [comment]
ParallelTest in TiDB unit test only tests the concurrent SQL execution in the single TiDB node. We should test DDL/Txn logic on multi-nodes.

**Comment by xhebox** [comment]
I actually added a unit test for that issue. It is reproducible with single node TiDB.

**Comment by xhebox** [comment]
Conrruent  DDL is on the roadmap and scheduled, close this for now.
