### ISSUE TITLE
Improve readability of auto-analyze log content

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#22919]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

Currently the log content of auto-analyze doesn't show the exact sql statement such as `[sql="analyze table test.t"]` but shows `[sql="analyze table %n.%n"]`, which gives less information.

<img width="1296" alt="Screen Shot 2021-02-24 at 5 02 27 PM" src="https://user-images.githubusercontent.com/30385241/108976106-26b41080-76c2-11eb-8fda-a6528a047e07.png">

**Describe alternatives you've considered:**
Change `[sql="analyze table %n.%n"]` to the exact sql statement like`[sql="analyze table test.t"]` in the log content of auto-analyze.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by hidehalo** [comment]
@xuyifangreeneyes Hi, could I pick up this issue?

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes Hi, could I pick up this issue?

I think #23522 has already fixed the issue. I will close it
