### ISSUE TITLE
the  error  after  execute 'alter table '

### ISSUE THREAD

**Issue by zxsciro** [pingcap/tidb#2293]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
a.Build the TIDB on five machine ,according to the  document 'https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md'  .
b.Start  pd,tikv,tidb succeed!
c.Use mysql client connect to tidb for test :  
    create  database  'tidbtest'  used 2 second  
   create table   zx   and insert  two records .
   finally    alter table zx add  b int not null default '' ;  
  
2. What did you expect to see?
ERROR 1067 (42000): Invalid default value for 'b'
 
  
3. What did you see instead?
the server is not response 
the log is showed 
2016/12/21 17:14:04 domain.go:71: [info] [ddl] diff load InfoSchema from version 1749 to 1750, in 3.100626ms
2016/12/21 17:14:06 ddl_worker.go:329: [info] [ddl] run DDL job ID:29, Type:add column, State:running, SchemaState:write reorganization, SchemaID:19, TableID:27, RowCount:0, ArgLen:0, Query:
alter table zx add b int not null default ''
2016/12/21 17:14:06 reorg.go:64: [info] [ddl] run reorg job done 
2016/12/21 17:14:06 ddl_worker.go:374: [error] [ddl] run ddl job err [types:1265]Data Truncated
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/util/types/convert.go:286: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/util/types/convert.go:166: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/util/types/convert.go:145: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/util/types/datum.go:1205: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/util/types/datum.go:796: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/table/column.go:119: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/table/column.go:278: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/ddl/column.go:308: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/ddl/reorg.go:66: 
/home/jenkins/workspace/BUILD_TIDB_WORKFLOW/go/src/github.com/pingcap/tidb/ddl/column.go:178: 
2016/12/21 17:14:06 domain.go:71: [info] [ddl] diff load InfoSchema from version 1750 to 1751, in 2.393608ms

4. What version of Go are you using (`go version`)?
go version go1.7.1 linux/amd64

**Comment by shenli** [comment]
@zxsciro DDL on TiDB is slower than on MySQL. You can refer to the [FAQ](https://github.com/pingcap/docs/blob/master/TiDB_FAQ.md#why-is-the-ddl-statement-so-slow-when-using-tidb) doc for the reason. If you have only one tidb-server, you could set the --lease to 0. And the speed of DDL statement will be fast.

**Comment by zxsciro** [comment]
@shenli thanks  , but the server  show the message frequently .
[error] [ddl] run ddl job err [types:1265]Data Truncated ....
[warning] [ddl] DDL job 30 is not in history, maybe not run

**Comment by zimulala** [comment]
@zxsciro Thanks for your report. This is a bug, and I will fix it.

**Comment by shenli** [comment]
@zxsciro There are two things we should do.
1. Check if the default value is valid before running the job.
2. When meet fatal error, we should cancel the ddl job.

@zimulala Will fix it. If you are interested in this, you can send us a PR. :)

**Comment by zxsciro** [comment]
@zimulala  now insert to  table zx  return the message  'ERROR 1265 (01000): Data Truncated' 
and  all the  ddl  is  not response

**Comment by zimulala** [comment]
@zxsciro Yes, this is a bug. If it happens, the job will keep trying and affect the execution of other DDL jobs. You need to restart the TiDB to resolve it. 
The right way to handle this is to cancel the DDL job when we meet this error. And This is easy to fix. Do you want to send a PR to us?

**Comment by zxsciro** [comment]
after  restart  all the service  the error log  still  exists.
as for  the bug fix , it is difficult for me . 
the server  conld not  catch the error   'default value Invalid'. so  can not set the  job to 'JobCancelled'  and the bug occurred ?

**Comment by zimulala** [comment]
@zxsciro I'm sorry. It needs to restart TiKV too. Fixing this bug requires some background knowledge. I will fix it.

**Comment by zimulala** [comment]
@zxsciro  This bug is fixed. You can try the latest master code and remove the old data.

**Comment by zxsciro** [comment]
mysql> create  table zz (a int not null ,b int not null)
    -> ;
Query OK, 0 rows affected (2.02 sec)
mysql> alter table zz add  c int not null default '';  
ERROR 1265 (01000): Data Truncated
mysql> show create table  zz ;
+-------+------------------------------------------------------------------------------------+
| Table | Create Table                                                                       |
+-------+------------------------------------------------------------------------------------+
| zz    | CREATE TABLE `zz` (
  `a` int(11) NOT NULL,
  `b` int(11) NOT NULL
) ENGINE=InnoDB |
+-------+------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> insert into zz (a,b) values (1,2)
    -> ;
ERROR 1265 (01000): Data Truncated

then  the server is response the  error   ,but the  table zz   could not use  for write .

**Comment by zimulala** [comment]
@zxsciro  This bug has two things we should do.
1. Check if the default value is valid before running the job.
2. When meet fatal error, we should cancel the ddl job.

Now we have only done the second thing. We are doing the first thing.

**Comment by zimulala** [comment]
@zxsciro This bug is fixed now. You can try the latest master code.
