### ISSUE TITLE
select count(*) from information_schema.columns run into error

### ISSUE THREAD

**Issue by idlesummerbreeze** [pingcap/tidb#2295]
Hi TiDB's Team

I tried to solve the following problem by myself, but without success. I suppose that the reason starts very deeply from the build of plan or executors, since the e.columns is empty:

		columns := make([]*table.Column, len(e.schema))
		for i, v := range e.columns {
			columns[i] = table.ToColumn(v)
		}

Perhaps the problem comes back to the different handling between normal tables and info tables.

Regards,
Yu

2016/12/21 11:53:51 conn.go:330: [error] lastCmd select count(*) from information_schema.columns, runtime error: invalid memory address or nil pointer dereference, goroutine 98 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc8200be000)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/conn.go:329 +0xc1
panic(0x104e040, 0xc82000e130)
	/usr/local/go/src/runtime/panic.go:426 +0x4e9
github.com/pingcap/tidb/infoschema.(*infoschemaTable).getRows(0xc8202f3bc0, 0x7fdceefbd1c8, 0xc820456d70, 0xc820595840, 0x2, 0x2, 0xc820466000, 0x20c, 0x400, 0x0, ...)
	/home/ray/devel/go/src/github.com/pingcap/tidb/infoschema/tables.go:643 +0x454
github.com/pingcap/tidb/infoschema.(*infoschemaTable).IterRecords(0xc8202f3bc0, 0x7fdceefbd1c8, 0xc820456d70, 0x0, 0x0, 0x0, 0xc820595840, 0x2, 0x2, 0xc820595850, ...)
	/home/ray/devel/go/src/github.com/pingcap/tidb/infoschema/tables.go:655 +0xed
github.com/pingcap/tidb/executor.(*TableScanExec).nextForInfoSchema(0xc8204b5200, 0xc81ffd0e99, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/executor/executor.go:1396 +0x1e6
github.com/pingcap/tidb/executor.(*TableScanExec).Next(0xc8204b5200, 0xc820032c00, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/executor/executor.go:1349 +0x4e
github.com/pingcap/tidb/executor.(*HashAggExec).innerNext(0xc8200a63c0, 0x0, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/executor/executor.go:1058 +0x6e
github.com/pingcap/tidb/executor.(*HashAggExec).Next(0xc8200a63c0, 0xc8205957e0, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/executor/executor.go:998 +0xa5
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc8205f8680, 0xc82049f7c0, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/executor/adapter.go:52 +0x4e
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc820595830, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/driver_tidb.go:267 +0x5e
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc8200be000, 0x7fdceefc2810, 0xc820595830, 0xc820590000, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/conn.go:655 +0xae
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc8200be000, 0xc8205e2751, 0x2f, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/conn.go:600 +0x205
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc8200be000, 0xc8205e2751, 0x2f, 0x2f, 0x0, 0x0)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/conn.go:390 +0x7ff
github.com/pingcap/tidb/server.(*clientConn).Run(0xc8200be000)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/conn.go:345 +0x274
github.com/pingcap/tidb/server.(*Server).onConn(0xc8202f3e00, 0x7fdceeeee0c8, 0xc8203e9308)
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/server.go:209 +0x294
created by github.com/pingcap/tidb/server.(*Server).Run
	/home/ray/devel/go/src/github.com/pingcap/tidb/server/server.go:173 +0x311

**Comment by coocood** [comment]
@idlesummerbreeze 

Thank you for your report and kindly try to fix this issue.
You almost addressed the issue, good job!
Elements in `columns` should not be nil.
It looks like the length of `e.schema` is different than the length of `e.columns`.

**Comment by idlesummerbreeze** [comment]
Hi @coocood ,

i'm not sure. perhaps it has to do with prunning column. After debugging i found that: prunning column works differently for the following sqls:

-- for a info table of the information schema
select count(*) from columns;

-- for a normal table of the schema test
select count(*) from x 

Regards,
Yu

**Comment by coocood** [comment]
@idlesummerbreeze 

The root cause is that the aggregation `count(*)` has been pushed down to memory table.
So the `e.schema` is aggregation function `count(*)`, but memory table cannot handle it.

When we handle normal table, we send a request to TiKV coprocessor which can handle aggregation function.

`e.columns` is empty because we don't need any columns, we just need row count, so all the infoschema columns has been pruned.
See https://github.com/pingcap/tidb/pull/2296
