### ISSUE TITLE
Handle truncate when convert string to integer

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb#2299]
In some cases, coprocessor will convert string to integer, which will always report Error when truncation happens.

**Comment by coocood** [comment]
@BusyJay 
Is this issue fixed by https://github.com/pingcap/tikv/pull/1423 ?

**Comment by BusyJay** [comment]
No entirely, still need to merge pingcap/tikv#1437.

**Comment by ngaut** [comment]
Can we close this issue now?
