### ISSUE TITLE
Make linter enable `unused`

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#23013]
## Development Task
ref https://github.com/pingcap/tidb/issues/22979

check the package like:
```
➜  tidb git:(master) ✗ cd ddl
➜  ddl git:(master) ✗ go list ./...| grep -vE "cmd|github.com\/pingcap\/tidb\/tests" |  sed 's|github.com/pingcap/tidb/||'
ddl
ddl/failtest
ddl/placement
ddl/testutil
ddl/util
➜ tidb git:(master) ✗ tools/bin/golangci-lint run -v --disable-all --deadline=3m --enable=misspell  --enable=ineffassign --enable=unused ddl ddl/failtest ddl/placement ddl/testutil ddl/util
ddl/error.go:56:2: var `errUnknownTypeLength` is unused (unused)
ddl/column_type_change_test.go:43:2: field `dbInfo` is unused (unused)
INFO File cache stats: 0 entries of total size 0B
```

pacakge tasklist:
- [ ] bindinfo
- [ ] config
- [x] ddl
- [ ] distsql
- [ ] domain
- [ ] errno
- [ ] executor
- [ ] expression
- [ ] infoschema
- [ ] kv
- [ ] lock
- [ ] meta
- [ ] metrics
- [ ] owner
- [ ] planner
- [ ] plugin
- [ ] privilege
- [x] server
- [ ] session
- [ ] sessionctx
- [ ] statistics
- [ ] store
- [ ] structure
- [ ] table
- [ ] tablecodec
- [ ] telemetry
- [ ] tidb-server
- [ ] type

**Comment by tisonkun** [comment]
@xhebox sorry I just see your assignment. Could you please help on the review of #24212 ? Or if you already work on this issue, I'm glad to help on the review side also.

**Comment by xhebox** [comment]
@tisonkun I am not working on other packages. I will review your PR.
