### ISSUE TITLE
some comments make one confused

### ISSUE THREAD

**Issue by idlesummerbreeze** [pingcap/tidb#2305]
Hi TiDB's Team,

I am reading the source code from ast package and have found some comments that are not very clear. I think that one should write implements `ExprNode` interface instead of `Expression` interface.

Regards,
Yu

`// expressionNode is the struct implements Expression interface.
// Expression implementations should embed it in.
type exprNode struct {
	node
	types.Datum
	Type types.FieldType
	flag uint64
}

// SetDatum implements Expression interface.
func (en *exprNode) SetDatum(datum types.Datum) {
	en.Datum = datum
}

// GetDatum implements Expression interface.
func (en *exprNode) GetDatum() *types.Datum {
	return &en.Datum
}

// SetType implements Expression interface.
func (en *exprNode) SetType(tp *types.FieldType) {
	en.Type = *tp
}

// GetType implements Expression interface.
func (en *exprNode) GetType() *types.FieldType {
	return &en.Type
}

// SetFlag implements Expression interface.
func (en *exprNode) SetFlag(flag uint64) {
	en.flag = flag
}

// GetFlag implements Expression interface.
func (en *exprNode) GetFlag() uint64 {
	return en.flag
}`

**Comment by coocood** [comment]
Good catch!
Would you please send a PR to fix this?

**Comment by idlesummerbreeze** [comment]
@coocood ,

ok, i give me try.

Regards,
Yu
