### ISSUE TITLE
Adding unique index on duplicate rows hangs (clustered_index + new collation)

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#23106]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
[config]
new_collations_enabled_on_first_bootstrap = true
```

Remove old data. For example,
```
$ rm /tmp/tidb -r
```

**Note that the clustered index is enabled.**

```sql
drop table if exists t;
create table t (id1 int, id2 varchar(10), a1 int, primary key(id1, id2) clustered) collate utf8mb4_general_ci;
insert into t values (1, 'asd', 1), (1, 'dsa', 1);
alter table t add unique index t_idx(id1, a1);
```

### 2. What did you expect to see? (Required)

```
ERROR 1062 (23000): Duplicate entry '1-1' for key 't_idx'
```

### 3. What did you see instead (Required)

Error message: "number of columns in two handle is different"

```
[INFO] [ddl_worker.go:535] ["[ddl] run DDL job failed, sleeps a while then retries it."] [worker="worker 4, tp add index"] [waitTime=1s] [error="number of columns in two handle is different"]
```

### 4. What is your TiDB version? (Required)

master `2cdd8a30ca99a17fabce6fb888b93aa80b9290a1`

**Comment by tangenta** [comment]
This bug is found by reading the source code of the function `tablecodec.DecodeIndexKV`.
```go
func DecodeIndexKV(key, value []byte, colsLen int, hdStatus HandleStatus, columns []rowcodec.ColInfo) ([][]byte, error)
```
The root cause is that the assumption of the argument `columns` is changed after https://github.com/pingcap/tidb/pull/20220: it should consist of index columns **plus common handle columns**. However, the usages of this function are not updated.

More test case:
```sql
drop table if exists t;
create table t (id1 int, id2 varchar(10), a1 int, primary key(id1, id2) clustered, unique key t_idx(id1, a1)) collate utf8mb4_general_ci;
begin;
insert into t values (1, 'asd', 1);
select * from t use index (t_idx);
```
```console
ERROR 1105 (HY000): runtime error: index out of range [3] with length 2
```

**Comment by zz-jason** [comment]
would it block other DDL jobs in the job queue?

**Comment by bb7133** [comment]
I will change it to 'critical' since it makes the DDL hangs for a long time(keep retrying), which blocks the succeeding DDLs.
