### ISSUE TITLE
what is the purpose of this code block?

### ISSUE THREAD

**Issue by idlesummerbreeze** [pingcap/tidb#2311]
Hi TiDB's Team,

I ofen see code that is similar to the following block. I cannot figure out why you use blank identifier here.

Regards
Yu

`var (
	_ DDLNode = &AlterTableStmt{}
	_ DDLNode = &CreateDatabaseStmt{}
	_ DDLNode = &CreateIndexStmt{}
	_ DDLNode = &CreateTableStmt{}
	_ DDLNode = &DropDatabaseStmt{}
	_ DDLNode = &DropIndexStmt{}
	_ DDLNode = &DropTableStmt{}
	_ DDLNode = &TruncateTableStmt{}

	_ Node = &AlterTableSpec{}
	_ Node = &ColumnDef{}
	_ Node = &ColumnOption{}
	_ Node = &ColumnPosition{}
	_ Node = &Constraint{}
	_ Node = &IndexColName{}
	_ Node = &ReferenceDef{}
)`

**Comment by ngaut** [comment]
To make sure all of those statements implement the DDLNode interface. It's quite common in Go :)

**Comment by idlesummerbreeze** [comment]
Hi @ngaut ,

ok, i get it now, since in golang there aren't keywords like implements/extends of java to make the extenstion/implementation explicitly.

this is really a brilliant way for verification and make code more readable.

Best Regards,
Yu
