### ISSUE TITLE
How to get the IO consumed of a SQL in TiDB 4.0

### ISSUE THREAD

**Issue by 24681430** [pingcap/tidb#23151]
## Description
hi:
May I Chinese?
tidb request a SQL read blocks count
为提高效率，请提供以下信息，问题描述清晰能够更快得到解决：

【TiDB 版本】
4.0
【问题描述】
在mysql可能通过开启profie来查看消耗的IO，但TIDB中并不支持，TIDB中有类似于下面命令的功能吗？用取SQL所需要消耗的IO
set profiling=1;

**Comment by djshow832** [comment]
What do you mean by IO? The disk usage or the number of network/disk accessing?

**Comment by djshow832** [comment]
There's no concept of "read block count" in TiDB. Similar concepts in TiDB are total keys and processed keys.
You can get this either from the `TOTAL_KEYS` of statements summary or `proc_keys` of `Explain Analyze`.
The Chinese docs are https://docs.pingcap.com/zh/tidb/stable/statement-summary-tables and https://docs.pingcap.com/zh/tidb/stable/sql-statement-explain-analyze#%E7%A4%BA%E4%BE%8B

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
