### ISSUE TITLE
wrong behavior ignore index for select result

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#2318]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
create table t1 (id int, dt datetime);
insert into t1 values (1,"2001-08-14 00:00:00"),(2,"2001-08-15 00:00:00"),(3,"2001-08-16 00:00:00"),(4,"2003-09-15 01:20:30");
create index dt on t1 (dt);
select * from t1 ignore index (dt) where dt > 20021020;
```

2. What did you expect to see?

```
+------+---------------------+
| id   | dt                  |
+------+---------------------+
|    4 | 2003-09-15 01:20:30 |
+------+---------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```
+------+---------------------+
| id   | dt                  |
+------+---------------------+
|    1 | 2001-08-14 00:00:00 |
|    2 | 2001-08-15 00:00:00 |
|    3 | 2001-08-16 00:00:00 |
|    4 | 2003-09-15 01:20:30 |
+------+---------------------+
```

**Comment by idlesummerbreeze** [comment]
Hi @tiancaiamao ,

it is possible that tidb handles the 20021020 as an integer (unix time?)

`$26 = {github.com/pingcap/tidb/ast.exprNode = {github.com/pingcap/tidb/ast.node = {text = 0x0 ""}, github.com/pingcap/tidb/util/types.Datum = {k = 1 '\001', 
      collation = 0 '\000', decimal = 0, length = 0, i = **20021020**, b = {array = 0x0, len = 0, cap = 0}, x = {_type = 0x0, data = 0x0}}, Type = {Tp = 8 '\b', Flag = 0, 
      Flen = -1, Decimal = -1, Charset = 0xef090e "binary", Collate = 0xef090e "binary", Elems = {array = 0x0, len = 0, cap = 0}}, flag = 0}}`

It's very wired that a query like `select * from t1 where dt > 20021020` sometimes returns right results but sometimes not. Using str_to_date returns always correct results at my local.

Regards,
Yu

**Comment by coocood** [comment]
Fixed
