### ISSUE TITLE
When use BEGIN OPTIMISTIC and open general log，tidb log txn_mode still use session txn mode.

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#23207]
## General Question

When use BEGIN OPTIMISTIC and open general log，tidb log txn_mode still use session txn value.
If txn_mode set txn value should better? 

![image](https://user-images.githubusercontent.com/55389305/110449240-f8d8be00-80fc-11eb-8ffb-ab0d30bb1f2d.png)

**Comment by ljluestc** [comment]
```

-- Check current global and session-level settings
SHOW GLOBAL VARIABLES LIKE 'tidb_txn_mode';
SHOW SESSION VARIABLES LIKE 'tidb_txn_mode';

-- Set global and session-level transaction modes
SET GLOBAL tidb_txn_mode = 'pessimistic';
SET SESSION tidb_txn_mode = 'pessimistic';
```

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
