### ISSUE TITLE
Is the "tiflash_proxy_tikv_encryption_ *" metric available?

### ISSUE THREAD

**Issue by wjma90** [pingcap/tidb#23222]
## General Question

metric "tiflash_proxy_tikv_encryption_ *" not found or exposed in prometheus.
tiflash: **v4.0.8**
tidb operator: v1.1.10

![image](https://user-images.githubusercontent.com/4097850/110514515-5e18b900-80d5-11eb-8c28-eaa4d43cd7ad.png)

![image](https://user-images.githubusercontent.com/4097850/110514656-86081c80-80d5-11eb-8946-51c7a1115c7f.png)

**Comment by solotzg** [comment]
Do you enable encryption config in tiflash?

**Comment by wjma90** [comment]
How do you enable encryption at rest? i have reviewed [this](https://github.com/pingcap/docs/blob/master/tiflash/tiflash-configuration.md) information and it doesn't indicate how it's done

**Comment by wjma90** [comment]
tidbcluster yaml:
![image](https://user-images.githubusercontent.com/4097850/111008037-3d16c900-835e-11eb-8398-df799f2047fe.png)

tiflash json log - config.toml:
![image](https://user-images.githubusercontent.com/4097850/111007943-fcb74b00-835d-11eb-83e6-81e31e141a8c.png)

tiflash-pod log:
![image](https://user-images.githubusercontent.com/4097850/111007867-d1346080-835d-11eb-9edd-039149ec5c55.png)

**Comment by solotzg** [comment]
You can check https://github.com/pingcap/docs/pull/3850

**Comment by solotzg** [comment]
You can check https://docs.pingcap.com/zh/tidb/stable/encryption-at-rest#tiflash-静态加密-从-v405-版本开始引入

**Comment by wjma90** [comment]
crash
![image](https://user-images.githubusercontent.com/4097850/111106329-e8707b00-8522-11eb-898c-79b579b66f53.png)

**Comment by solotzg** [comment]
Is there any error shown in tiflash server log ?

**Comment by wjma90** [comment]
i had to uninstall tiflash and reinstall it.
