### ISSUE TITLE
Wrong result of comparison operation

### ISSUE THREAD

**Issue by wanliyi** [pingcap/tidb#23236]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
create table t1(a date, b varchar(255));
insert into t1 values("2021-03-10", "a");
```

### 2. What did you expect to see? (Required)
```mysql
mysql> select a = b from t1;
+-------+
| a = b |
+-------+
|     0 |
+-------+
1 row in set (0.04 sec)

mysql> select a != b from t1;
+--------+
| a != b |
+--------+
|      1 |
+--------+
1 row in set (0.03 sec)
```
### 3. What did you see instead (Required)
```mysql
mysql> select a = b from t1;
+-------+
| a = b |
+-------+
| NULL  |
+-------+
1 row in set (0.03 sec)

mysql> select a != b from t1;
+--------+
| a != b |
+--------+
| NULL   |
+--------+
1 row in set (0.03 sec)
```
### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-2209-gfebac515b
Edition: Community
Git Commit Hash: febac515b1369643216e1efc971a262615dc4794
Git Branch: master
UTC Build Time: 2021-03-01 03:47:27
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by XuHuaiyu** [comment]
This is a corner case that we almost never encountered in production scenarios.
And TiDB will return a warning for such case, thus I think we do not need to fix this issue.
``` sql
tidb> select a=b from t1;
+-----+
| a=b |
+-----+
| NULL |
+-----+
1 row in set, 1 warning (0.00 sec)

tidb> show warnings;
+---------+------+-------------------------------+
| Level   | Code | Message                       |
+---------+------+-------------------------------+
| Warning | 1292 | Incorrect datetime value: 'a' |
+---------+------+-------------------------------+
1 row in set (0.00 sec)
```
