### ISSUE TITLE
How to deploy TiDB in different IDCs?

### ISSUE THREAD

**Issue by ch-lgs** [pingcap/tidb#2328]
I have two IDCs in shanghai and hangzhou.Now I deploy mysql cluster in these two IDCs and use otter(a middleware consume mysql binlog to sync data between different IDCs) to keep data consistent.

**Comment by siddontang** [comment]
Hi @ch-lgs 

Raft must use at lease 3 replicas to guarantee data safety, 2 DC can't guarantee it. If one DC is down, the cluster can't work. 

If you have 3 DCs, PD can schedule the replicas to different DC automatically, and we will support it soon, see https://github.com/pingcap/pd/issues/454.

**Comment by ngaut** [comment]
Feel free to re-open the issue if you still have any questions.
