### ISSUE TITLE
The column name is inconsistent with mysql when character set utf8 

### ISSUE THREAD

**Issue by wanliyi** [pingcap/tidb#23291]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```mysql
mysql> create table t1(`COL1` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PRIMARY KEY (`COL1`) USING BTREE);
Query OK, 0 rows affected (0.18 sec)

mysql> insert into t1 values("a");
Query OK, 1 row affected (0.01 sec)
```

### 2. What did you expect to see? (Required)
```mysql
mysql> select col1 from t1 where col1 = "a";
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.02 sec)
```
### 3. What did you see instead (Required)
```mysql
mysql> select col1 from t1 where col1 = "a";
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.04 sec)
```
### 4. What is your TiDB version? (Required)
```mysql
Release Version: v4.0.0-beta.2-2209-gfebac515b
Edition: Community
Git Commit Hash: febac515b1369643216e1efc971a262615dc4794
Git Branch: master
UTC Build Time: 2021-03-01 03:47:27
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by xiongjiwei** [comment]
I may not agree it is a bug. it is more like a compatibility issue. we use the name you specified in `create table` stmt, but MySQL uses the lower case of the name string.

**Comment by morgo** [comment]
I actually think this could be a serious issue. Consider the case that a user's ORM references results not by index, but by a hash which is case sensitive. In this case, the results of TiDB are problematic.

**Comment by morgo** [comment]
I can't reproduce this issue - is it possible there could be another setting involved? I tried against both master and the hash that you provided. The result is the same as MySQL:

```sql
drop table if exists t1;
create table t1(`COL1` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PRIMARY KEY (`COL1`) USING BTREE);
insert into t1 values("a");
SELECT * FROM t1;
SELECT col1 FROM t1;
```

TiDB:
```sql
mysql> drop table if exists t1;
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> create table t1(`COL1` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PRIMARY KEY (`COL1`) USING BTREE);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values("a");
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t1;
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql> SELECT col1 FROM t1;
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-2209-gfebac515b
Edition: Community
Git Commit Hash: febac515b1369643216e1efc971a262615dc4794
Git Branch: HEAD
UTC Build Time: 2021-03-15 02:17:57
GoVersion: go1.13.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```
MySQL:

```sql
..
mysql [localhost:5731] {msandbox} (test) > SELECT * FROM t1;
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql [localhost:5731] {msandbox} (test) > SELECT col1 FROM t1;
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

..

mysql [localhost:8023] {msandbox} (test) > SELECT * FROM t1;
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql [localhost:8023] {msandbox} (test) > SELECT col1 FROM t1;
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)
```

**Comment by wanliyi** [comment]
> 我无法重现此问题-是否可能涉及其他设置？我尝试同时使用master和您提供的哈希。结果与MySQL相同：
> 
> ```sql
>  如果存在t1，则删除表；
> 创建 表 T1（` COL1 `  VARCHAR（255）CHARACTER SET UTF8 COLLATE utf8_general_ci NOT NULL，PRIMARY KEY（` COL1 `）USING BTREE）;
> 插入t1值（“ a ”）；
> 选择 * 从t1;
> 从t1中选择col1 ;
> ```
> 
> TiDB：
> 
> ```sql
> mysql > 删除 表（ 如果存在）
> 查询OK，0行的影响，1个警告（0。00秒）
> 
> 的MySQL >创建表t1（` COL1 `  VARCHAR（255）CHARACTER SET UTF8 COLLATE utf8_general_ci NOT NULL，PRIMARY KEY（` COL1 `）USING BTREE）; 
> 查询OK，0行受到影响（0。01秒）
> 
> 的MySQL > 插入到t1值（“ a ”）；
> 查询行，1行受影响（0。00秒）
> 
> 的MySQL >  SELECT  *  FROM T1;
> + - ---- + 
> | COL1 | + - ---- + 
> | 一个| + - ---- + 1行中集合（0。00秒）
> 的MySQL > SELECT COL1 FROM T1;
> + - ---- + 
> | col1 | +
> 
> 
>  
>  
> - ---- + 
> | 一个| + - ---- + 1行中集合（ 0。 00秒）
> 的MySQL >选择tidb_version（）\ G变
> ************************ *** 1。row **************************** 
> tidb_version（）：发行版本： v4。0。0 - beta。2 - 2209 - gfebac515b
> 版：社区
> 的Git提交哈希：febac515b1369643216e1efc971a262615dc4794
> 的Git分支：HEAD
> 
>  
>   
> UTC建造时间：2021 - 03 - 15  02：17：57 
> GoVersion：GO1。13。15
> 种族启用：false 
> TiKV最低版本：v3。0。0 - 60965b006877ca7234adaced7890d7b029ed1306
> 检查表删除之前：假
> 1行中 集（0。00秒）
> ```
> 
> MySQL：
> 
> ```sql
> ..
> mysql [localhost:5731] {msandbox} (test) > SELECT * FROM t1;
> +------+
> | COL1 |
> +------+
> | a    |
> +------+
> 1 row in set (0.00 sec)
> 
> mysql [localhost:5731] {msandbox} (test) > SELECT col1 FROM t1;
> +------+
> | col1 |
> +------+
> | a    |
> +------+
> 1 row in set (0.00 sec)
> 
> ..
> 
> mysql [localhost:8023] {msandbox} (test) > SELECT * FROM t1;
> +------+
> | COL1 |
> +------+
> | a    |
> +------+
> 1 row in set (0.00 sec)
> 
> mysql [localhost:8023] {msandbox} (test) > SELECT col1 FROM t1;
> +------+
> | col1 | + - ---- + 
> | 一个| + - ---- + 1行中集合（0。00秒）
> 
> 
>  
> ```
select col1 from t1 where col1 = "a"

**Comment by morgo** [comment]
Thanks! verified as described:
```sql
mysql> SELECT col1 FROM t1 where col1="a";
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.01 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-2209-gfebac515b
Edition: Community
Git Commit Hash: febac515b1369643216e1efc971a262615dc4794
Git Branch: HEAD
UTC Build Time: 2021-03-15 02:17:57
GoVersion: go1.13.15
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
Here is the correct testcase, verified against master and MySQL 8.0:
```sql
drop table if exists t1;
create table t1(`COL1` varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL, PRIMARY KEY (`COL1`) USING BTREE);
insert into t1 values("a");
SELECT * FROM t1; -- should be upper (correct)
SELECT col1 FROM t1; -- should be lower (correct)
SELECT col1 FROM t1 where col1="a"; -- should be lower (incorrect)
```

Results (tidb and mysql 8.0):
```sql
mysql> SELECT * FROM t1; -- should be upper (correct)
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql> SELECT col1 FROM t1; -- should be lower (correct)
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql> SELECT col1 FROM t1 where col1="a"; -- should be lower (incorrect)
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql [localhost:8023] {msandbox} (test) > SELECT * FROM t1; -- should be upper (correct)
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql [localhost:8023] {msandbox} (test) > SELECT col1 FROM t1; -- should be lower (correct)
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql [localhost:8023] {msandbox} (test) > SELECT col1 FROM t1 where col1="a"; -- should be lower (incorrect)
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

```

**Comment by xiongjiwei** [comment]
I get the point, it should be a bug, I will fix it.

**Comment by morgo** [comment]
I've updated the testcase based on that it does not sem to be related to the character set. It only occurs on columns defined as the primary key:

```sql
drop table if exists t1, t2;
create table t1(`COL1` varchar(255), PRIMARY KEY (`COL1`));
create table t2(`COL1` varchar(255));
create table t3(`COL1` varchar(255), index(COL1));
insert into t1 values("a");
insert into t2 values("a");
insert into t3 values("a");

SELECT col1 FROM t1 where col1="a"; -- should be lower (incorrect)
SELECT col1 FROM t2 where col1="a"; -- should be lower (correct)
SELECT col1 FROM t3 where col1="a"; -- should be lower (correct)

..

mysql> SELECT col1 FROM t1 where col1="a"; -- should be lower (incorrect)
+------+
| COL1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql> SELECT col1 FROM t2 where col1="a"; -- should be lower (incorrect)
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)

mysql> SELECT col1 FROM t3 where col1="a"; -- should be lower (incorrect)
+------+
| col1 |
+------+
| a    |
+------+
1 row in set (0.00 sec)
```

So the likelyhood is a now far less common. The user would have to perform a lookup based on a primary key, and then also explicitly select the column for the primary key (when they already know it).

**Comment by xiongjiwei** [comment]
it may relate to `Point_Get`. When using `unique index`
```sql
create table t4(`COL1` varchar(255), unique index(COL1));
insert into t4 values("a");
mysql root@localhost:test> SELECT col1 FROM t4 where coL1="a"; -- should be lower
+------+
| COL1 |
+------+
| a    |
+------+
```
