### ISSUE TITLE
tidb modify  server-version ，@@version and show variables like '%version%' not take effect

### ISSUE THREAD

**Issue by wentaojin** [pingcap/tidb#23315]
modify server-version  5.7.31-TiDB-v4.0.9 ，@@version and show variables like '%version%' not take effect
![image](https://user-images.githubusercontent.com/34805682/111127416-cae8f300-85ae-11eb-86d3-206c181a7f6c.png)
![image](https://user-images.githubusercontent.com/34805682/111127686-0e436180-85af-11eb-9a52-43a241e5534f.png)

**Comment by Howie59** [comment]
@WentaoJin how did u modify server version? modify the configuration directly?

**Comment by WentaoJin** [comment]
> @WentaoJin how did u modify server version? modify the configuration directly?
@Howie59 yes，modify tidb config parameter  server-version ,then reload tidb-server

**Comment by Defined2014** [comment]
It's same as #27210 , already fixed in master branch.
Cloud you close this issue? @tisonkun

**Comment by tisonkun** [comment]
Duplicate of #27210

Thanks for your report. Also you can update #27210  with affects & backport label if any.
