### ISSUE TITLE
optimize count(distinct a) to count(a) if there is an unique key on a

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#23436]
## Feature Request

**Is your feature request related to a problem? Please describe:**
``` sql
tidb> create table t(a int , unique key(a));
Query OK, 0 rows affected (0.01 sec)
tidb> desc select count(distinct a) from t;
+--------------------------+----------+-----------+---------------------+------------------------------------------+
| id                       | estRows  | task      | access object       | operator info                            |
+--------------------------+----------+-----------+---------------------+------------------------------------------+
| StreamAgg_6              | 1.00     | root      |                     | funcs:count(distinct test.t.a)->Column#3 |
| └─IndexReader_14         | 10000.00 | root      |                     | index:IndexFullScan_13                   |
|   └─IndexFullScan_13     | 10000.00 | cop[tikv] | table:t, index:a(a) | keep order:false, stats:pseudo           |
+--------------------------+----------+-----------+---------------------+------------------------------------------+
3 rows in set (0.00 sec)
```

TiDB will OOM if there are too many tuples in table `t`.

**Describe the feature you'd like:**
Actually we can optimize `count(distinct a)` to `count(a)` since there is an unique key on column a.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by winoros** [comment]
This one can be added in `rule_aggregation_elimination.go`.
And the case can be limited to the most simple one:
- No group by.
- Only agg funcs with same distinct column.
- There's unique key on the column.

**Comment by TszKitLo40** [comment]
I want to try this issue

**Comment by winoros** [comment]
yeah, if you have questions, just contact us via slack!
