### ISSUE TITLE
`SHOW ANALYZE STATUS` missed the finish time for each task

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#23451]
## Feature Request

**Describe the feature you'd like:**

![image](https://user-images.githubusercontent.com/7846227/111944496-ba86ca00-8b12-11eb-849d-040aa8657b7e.png)

We've have `show analyze status` grammar to show the current analyze status. But we only have the column of the created time and the current status. No finish time. It's a little hard for now to know when the analyze is finished.(Since currently the feedback will directly modify the histogram).

**Describe alternatives you've considered:**

If we don't change the behavior of the feedback. We need to show the finish time of each analyze task.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by winoros** [comment]
duplicated with #23587

**Comment by LittleFall** [comment]
sorry for the duplicate (
