### ISSUE TITLE
I can't use sysbench to test tidb

### ISSUE THREAD

**Issue by 496080199** [pingcap/tidb#2346]
I have a host(4core,2GB memory,100GB disk) to run tidb,method like this:

https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md#%E5%8D%95%E8%8A%82%E7%82%B9%E6%96%B9%E5%BC%8F%E5%BF%AB%E9%80%9F%E9%83%A8%E7%BD%B2

my test like this:

sysbench --test=oltp --db-driver=mysql --mysql-table-engine=innodb --oltp-table-size=1000000  --num-threads=4  --mysql-host=192.168.2.183 --mysql-user='root' --mysql-password='' --mysql-port=4000 --mysql-db='test' prepare

this statement is OK.but when I do this:

sysbench --test=oltp --db-driver=mysql --mysql-table-engine=innodb --oltp-table-size=1000000  --num-threads=4  --mysql-host=192.168.2.183 --mysql-user='root' --mysql-password='' --mysql-port=4000 --mysql-db='test' run

it throwed some error like this:

sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 4

Doing OLTP test.
Running mixed OLTP test
Using Special distribution (12 iterations,  1 pct of values are returned in 75 pct cases)
Using "BEGIN" for starting transactions
Using auto_inc on the id column
Maximum number of requests for OLTP test is limited to 10000
Threads started!
ALERT: failed to execute mysql_stmt_execute(): Err1105 Malform packet error
FATAL: database error, exiting...
ALERT: failed to execute mysql_stmt_execute(): Err1105 Malform packet error
FATAL: database error, exiting...
ALERT: failed to execute mysql_stmt_execute(): Err1105 Malform packet error
FATAL: database error, exiting...
ALERT: failed to execute mysql_stmt_execute(): Err1105 Malform packet error
FATAL: database error, exiting...
Done.

how to slove this problem?

**Comment by shenli** [comment]
@496080199 Thanks for your feedback!
We will fix it soon.
@tiancaiamao PTAL

**Comment by shenli** [comment]
@496080199 This is fixed in #2351 . Please try the latest master.

**Comment by shenli** [comment]
@496080199 Have you tested sysbench with the latest TiDB?
