### ISSUE TITLE
Change mysql.user Host field to char(255)

### ISSUE THREAD

**Issue by Win-Man** [pingcap/tidb#23476]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I want to set IP white list, but it exceed char(64).

**Describe the feature you'd like:**

Change mysql.user Host field to char(255).

```
root@127.0.0.1 : (none) 08:17:51> select version();
+-----------+
| version() |
+-----------+
| 8.0.19    |
+-----------+
1 row in set (0.00 sec)

root@127.0.0.1 : (none) 08:18:03> desc mysql.user;
+--------------------------+-----------------------------------+------+-----+-----------------------+-------+
| Field                    | Type                              | Null | Key | Default               | Extra |
+--------------------------+-----------------------------------+------+-----+-----------------------+-------+
| Host                     | char(255)                         | NO   | PRI |                       |       |
```

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by morgo** [comment]
This came up in the review of the design in Dynamic privileges: https://github.com/pingcap/tidb/pull/23224#discussion_r593739601

I agree, I think we should fix it.

**Comment by Defined2014** [comment]
In Mysql-5.7, the type of Host in mysql.user table is char(60). I think we should compatible with mysql-5.7?

**Comment by morgo** [comment]
> In Mysql-5.7, the type of Host in mysql.user table is char(60). I think we should compatible with mysql-5.7?

Often when there is a discrepancy we follow MySQL 8.0 behavior (this is also a feature request, not a bug.)

The reason why MySQL 8.0 switched is to support long hostnames, such as those that exist on AWS.
