### ISSUE TITLE
integration testing for mysql packet protocol

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#2353]
Currently, testing for packet protocol related is insufficient for TiDB.
Unit testing have a drawback: TiDB must ensure compatibility for all kinds of drivers, not just Go sql driver.

Test cases should involve: 

* Different driver, maybe java, Go, mysql native client, sysbench, and so on...
* Different Conn Capability setting...
* Coverage all kinds of packet, COM_QUERY, COM_STMT_PREPARE, COM_STMT_EXECUTE...

This issue is important, we have already meet packet protocol problem several time, such as https://github.com/pingcap/tidb/pull/1772 https://github.com/pingcap/tidb/pull/2351 https://github.com/pingcap/tidb/pull/1684 and maybe more.

**Comment by morgo** [comment]
@tiancaiamao I believe this issue can now be closed?  We have JDBC, Go etc in the test suite.

**Comment by tiancaiamao** [comment]
Well, I'll not sure it's all fixed, but I believe the compatibility has improved since the time this issue was filed.
