### ISSUE TITLE
Compatible with mysql 5.7 noop variables:  innodb_default_row_format

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tidb#23541]
## Feature Request
Compatible with mysql 8.0 parameter innodb_default_row_format

**Is your feature request related to a problem? Please describe:**
jira is required for  innodb_default_row_format = dynamic 

**Describe the feature you'd like:**
user can set innodb_default_row_format and can use set variables  change value

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by djshow832** [comment]
As the row format is not suitable for TiKV, does it mean TiDB can allow users to set its value and just ignore it?

**Comment by King-Dylan** [comment]
> As the row format is not suitable for TiKV, does it mean TiDB can allow users to set its value and just ignore it?

yes

**Comment by morgo** [comment]
I agree in this instance it is fine to ignore. What JIRA is doing is a little bit silly:

- `innodb_default_row_format` was introduced in 5.7 where the default is `DYNAMIC`. Prior to this, you needed to specify the row format per-table.
- JIRA is setting it to `DYNAMIC`, very likely to ensure that indexes on `varchar(255)` + utf8mb4 are supported. So it is essentially only handling the case that a user might change the default (users rarely would).

**Comment by morgo** [comment]
@King-Dylan I have a PR available to fix this, but I've not tagged it for cherry picking to a release branch. Let's chat on Feishu/Slack if you would like it to be.
