### ISSUE TITLE
Add column `End_time` in `show analyze status` and add related infromation in logs.

### ISSUE THREAD

**Issue by LittleFall** [pingcap/tidb#23587]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I suggest a customer analyze a table, it cost a lot of time, but we all don't know when it is ended.

**Describe the feature you'd like:**

1. Add column `End_time` in `show analyze status`:
```sql
mysql> show analyze status;
+--------------+------------+----------------+-----------------+----------------+---------------------+----------+
| Table_schema | Table_name | Partition_name | Job_info        | Processed_rows | Start_time          | State    |
+--------------+------------+----------------+-----------------+----------------+---------------------+----------+
| test         | t          |                | analyze columns |              0 | 2021-03-26 08:27:27 | finished |
+--------------+------------+----------------+-----------------+----------------+---------------------+----------+
1 row in set (0.00 sec)
```

2. And when the analysis ended, print information to log.

**Describe alternatives you've considered:**

Can't find an alternative.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by hidehalo** [comment]
@LittleFall Hello! I want to pick up this issue.

**Comment by LittleFall** [comment]
> @LittleFall Hello! I want to pick up this issue.

welcome!
