### ISSUE TITLE
PD version in cluster info is different from pd-server -V

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#23613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
ubuntu@ip-172-31-58-248:~$ tiup pd:v5.0.0-nightly -V
Starting component `pd`: /home/ubuntu/.tiup/components/pd/v5.0.0-nightly/pd-server -V
Release Version: v5.0.0-nightly
Edition: Community
Git Commit Hash: 687acfc8db8378e01e47ab21dd38473a3ff8d800
Git Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time:  2021-03-27 04:49:25
ubuntu@ip-172-31-58-248:~$ tiup tikv:v5.0.0-nightly -V
Starting component `tikv`: /home/ubuntu/.tiup/components/tikv/v5.0.0-nightly/tikv-server -V
TiKV
Release Version:   5.0.0-rc.x
Edition:           Community
Git Commit Hash:   4db8ee36f69b3ec2d5c5281800e1161ee7af7665
Git Commit Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time:    2021-03-27 16:52:50
Rust Version:      rustc 1.51.0-nightly (bc39d4d9c 2021-01-15)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
ubuntu@ip-172-31-58-248:~$ mycli -h 172.31.19.4 -P 4000 -u root -e "select * from information_schema.cluster_info"
TYPE    INSTANCE        STATUS_ADDRESS  VERSION GIT_HASH        START_TIME      UPTIME  SERVER_ID
tidb    172.31.21.226:4000      172.31.21.226:10080     5.0.0-nightly   638272efb2aa3be419a0dd56cb546121a9b5ff7a        2021-03-28T02:52:49Z    3h52m55.698831885s      0
tidb    172.31.19.4:4000        172.31.19.4:10080       5.0.0-nightly   638272efb2aa3be419a0dd56cb546121a9b5ff7a        2021-03-28T02:52:47Z    3h52m57.698834761s      0
pd      172.31.11.157:2379      172.31.11.157:2379      5.0.0-rc.x      687acfc8db8378e01e47ab21dd38473a3ff8d800        2021-03-28T02:49:49Z    3h55m55.698836386s      0
pd      172.31.3.29:2379        172.31.3.29:2379        5.0.0-rc.x      687acfc8db8378e01e47ab21dd38473a3ff8d800        2021-03-28T02:49:42Z    3h56m2.698837548s       0
pd      172.31.2.59:2379        172.31.2.59:2379        5.0.0-rc.x      687acfc8db8378e01e47ab21dd38473a3ff8d800        2021-03-28T02:49:44Z    3h56m0.698838792s       0
tikv    172.31.16.17:20160      172.31.16.17:20180      5.0.0-rc.x      4db8ee36f69b3ec2d5c5281800e1161ee7af7665        2021-03-28T02:51:41Z    3h54m3.698840054s       0
tikv    172.31.17.242:20160     172.31.17.242:20180     5.0.0-rc.x      4db8ee36f69b3ec2d5c5281800e1161ee7af7665        2021-03-28T02:52:42Z    3h53m2.698841122s       0
tikv    172.31.18.97:20160      172.31.18.97:20180      5.0.0-rc.x      4db8ee36f69b3ec2d5c5281800e1161ee7af7665        2021-03-28T02:51:01Z    3h54m43.69884267s       0
ubuntu@ip-172-31-58-248:~$
```

### 2. What did you expect to see? (Required)
They have the same version

### 3. What did you see instead (Required)
They are 5.0.0-nightly and 5.0.0-rc.x

**Comment by breeswish** [comment]
According to the text you provide, this system is exactly displaying what -v shows:

```
Starting component `pd`: /home/ubuntu/.tiup/components/pd/v5.0.0-nightly/pd-server -V
Release Version: v5.0.0-nightly
^^^^^^^^^^^^
...

Starting component `tikv`: /home/ubuntu/.tiup/components/tikv/v5.0.0-nightly/tikv-server -V
TiKV
Release Version:   5.0.0-rc.x
^^^^^^^^^^^^
```

What's the problem you think it's wrong?

**Comment by jebter** [comment]
`localhost ~ % tiup tikv:nightly -V
Starting component tikv: /Users/.tiup/components/tikv/v8.2.0-alpha-nightly/tikv-server -V
TiKV 
Release Version:   8.2.0-alpha
Edition:           Community
Git Commit Hash:   485c434512d38f5c4dc1d270a30fcd1b21f537c6
Git Commit Branch: HEAD
UTC Build Time:    2024-07-08 03:34:06
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           dist_release
localhost ~ % tiup pd:nightly -V  
Starting component pd: /Users/.tiup/components/pd/v8.2.0-alpha-nightly/pd-server -V
Release Version: v8.2.0-alpha-121-gbdbe73e8
Edition: Community
Git Commit Hash: bdbe73e8b03d0439bdde41d3d02eb2cb73c15bea
Git Branch: HEAD
UTC Build Time:  2024-07-08 08:15:34

 select * from information_schema.cluster_info
+------+------------------------------------------------------------+------------------------------------------------------------+-------------+------------------------------------------+---------------------+------------------+-----------+
| TYPE | INSTANCE                                                   | STATUS_ADDRESS                                             | VERSION     | GIT_HASH                                 | START_TIME          | UPTIME           | SERVER_ID |
+------+------------------------------------------------------------+------------------------------------------------------------+-------------+------------------------------------------+---------------------+------------------+-----------+
| tidb | tc-tidb-0.tc-tidb-peer.testbed-tps-7548514-1-187.svc:4000  | tc-tidb-0.tc-tidb-peer.testbed-tps-7548514-1-187.svc:10080 | 8.2.0-alpha | 1b872e5d6ad29ffeb817a0b55b4ef6eef3de3ac2 | 2024-07-09 02:33:39 | 10m51.029776145s | 1914      |
| pd   | tc-pd-0.tc-pd-peer.testbed-tps-7548514-1-187.svc:2379      | tc-pd-0.tc-pd-peer.testbed-tps-7548514-1-187.svc:2379      | 8.2.0-alpha | bdbe73e8b03d0439bdde41d3d02eb2cb73c15bea | 2024-07-09 02:32:20 | 12m10.029779176s | 0         |
| tikv | tc-tikv-0.tc-tikv-peer.testbed-tps-7548514-1-187.svc:20160 | 10.200.39.213:20180                                        | 8.2.0-alpha | 485c434512d38f5c4dc1d270a30fcd1b21f537c6 | 2024-07-09 02:32:52 | 11m38.029780174s | 0         |
+------+------------------------------------------------------------+------------------------------------------------------------+-------------+------------------------------------------+---------------------+------------------+-----------+
`
Please try the latest version. I will close it,if there are any updates, you can reopen it.
