### ISSUE TITLE
set pessimistic-txn.enabled=false in 4.x version, when upgrade to 5.0.0, the txn mode maybe changed

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#23709]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. config pessimistic-txn.enabled=false in 4.x version,
2. upgrade to 5.0.0 version
3. check default txn mode

### 2. What did you expect to see? (Required)
current behavior maybe has the risk of incompatible, should record in release notes
### 4. What is your TiDB version? (Required)

v5.0.0-nightly

**Comment by zyguan** [comment]
Since it's a major version upgrade, and we've already announce that the config is replaced by system variable `tidb_txn_mode` in our [release notes](https://docs.pingcap.com/tidb/stable/release-5.0.0#configuration-file-parameters). I don't think we need to guarantee that compatibility.
