### ISSUE TITLE
config: data races in tests

### ISSUE THREAD

**Issue by xhebox** [pingcap/tidb#23748]
## Bug Report

The root cause of data race in config packages is that, it stores the pointer of the global config: https://github.com/pingcap/tidb/blob/master/config/config.go#L676-L684. Lots of tests fail due to this.

So when two goroutines access one single field in the struct pointed by the pointer, it races. The following race example will clarify:

```
func (s *testConfigSuite) TestRace(c *C) {
        cfg1 := GetGlobalConfig()
        cfg2 := GetGlobalConfig()
        var wg sync.WaitGroup
        wg.Add(2)
        go func() {
                for i := 0; i < 200; i++ {
                        cfg1.AlterPrimaryKey = true
                }
                wg.Done()
        }()
        go func() {
                f := false
                for i := 0; i < 200; i++ {
                        f = cfg2.AlterPrimaryKey
                }
                fmt.Println(f)
                wg.Done()
        }()
        wg.Wait()
}
```

There is one PR trying to fix: #17964. But it is incorrect.

```
func UpdateGlobal(f func(conf *Config)) {
	g := GetGlobalConfig()
	newConf := *g
	f(&newConf)
	StoreGlobalConfig(&newConf)
}
```

`GetGlobalConfig` and `StoreGlobalConfig` is atomic, but the returned pointer of config is not guarded by the atomic. `newConf := *g` is not race free.

We have three solutions:

1. Return by value, i.e. load/store the whole Config struct. But it may have data loss: goroutine A get the global config, goroutine B modified the config, goroutine A stored the config, the modifications of B was lost.
2. Mutex on the pointer, and rely two accessors `UpdateGlobal`, `GetGlobalVar(xxx)`. It needs a large refactor. But it does not have data loss.

The third solution: expose more races by reverting #17964.

Race-free solutions do not save you from the real problem: if two tests are accessing the same field, the behavior may be undefined, even race-free: the test and SQLs expect the global config unchanged, but it is changed by another test. Or even worse, like ABA problems. We should not let those two tests run in parallel:

```
3635:// TestDeprecateSlowLogMasking should be in serial suite because it changes a global variable.
3636:func (s *testSessionSerialSuite) TestDeprecateSlowLogMasking(c *C) {
```

As for user, it is really rare that they will modify the same global switch in such a short time, that a race occurred. If it does, their application logic may be wrong, just like our tests.

It is already safe enough that TiDB did not race on that global pointer. Different goroutines/sessions can already modify different global options without races, in most cases.

### 1. Minimal reproduce step (Required)

The example above could reproduce. Run with `-race`.

### 4. What is your TiDB version? (Required)

master branch, but I guess the problem exists on 4.0 or 3.0, too.

**Comment by tangenta** [comment]
https://github.com/pingcap/tidb/pull/19765 Perhaps we can modify this PR to make it applicable global config test cases.

**Comment by AilinKid** [comment]
> #19765 Perhaps we can modify this PR to make it applicable global config test cases.

Do you mean to make these tests including the global config modification run serially as failpoint case does?

**Comment by xhebox** [comment]
I do mean so.

**Comment by xhebox** [comment]
Changed severity since it is neither a tracking issue or a concrete bug.
