### ISSUE TITLE
system variable "tidb_dml_batch_size " is a session vars in 4.0.x, will lost after upgrade to 5.0.0

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#23789]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

MySQL [(none)]> set global tidb_dml_batch_size=3000;                                                                                                  │
ERROR 1105 (HY000): Variable 'tidb_dml_batch_size' is a SESSION variable and can't be used with SET GLOBAL

### 2. What did you expect to see? (Required)
this var can be saved as global

### 3. What did you see instead (Required)
after upgrade, this value will lost

### 4. What is your TiDB version? (Required)

v5.0.0

**Comment by seiya-annie** [comment]
this behavior is expected.

**Comment by morgo** [comment]
This

**Comment by morgo** [comment]
(Reclosing; I thought this broke an upgrade case, but I misunderstood).
