### ISSUE TITLE
Output cost of plans in explain "verbose" mode

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#23793]
## Feature Request

For now the "verbose" mode of explain is not implemented. I propose that we can output the cost as the first step. It has following advantages:

- When we use `horoscope` to test TiDB's plan, it's possible to run a lot of plans. Like tpch query 2, there are nearly 1000 plans including mpp plans. It makes no sense to enumerate every plan. It's better to sort the plans by cost and run several of them.
- Once we have the cost information, we can check the correctness of the cost model by comparing the cost and executiont time of plans.

## Feature Design

###grammar

We have had `format = “verbose”` but it's not yet used. We can enable it and add extra column `estCost` for it.

###output

For example, If we execute
```
mysql> explain format = "verbose" select count(*) from lineitem;
```
we can get : (the cost data is fake)

```
+------------------------------|-------------+--------------+-------------------+----------------+-----------------------------------+
| id                           | estCost     | estRows      | task              | access object  | operator info                     |
+------------------------------|-------------+--------------+-------------------+----------------+-----------------------------------+
| HashAgg_23                   |  10000.00   | 1.00         | root              |                | funcs:count(Column#24)->Column#18 |
| └─TableReader_25             |   8000.00   | 1.00         | root              |                | data:ExchangeSender_24            |
|   └─ExchangeSender_24        |   7000.00   | 1.00         | batchCop[tiflash] |                | ExchangeType: PassThrough         |
|     └─HashAgg_8              |   6000.00   | 1.00         | batchCop[tiflash] |                | funcs:count(1)->Column#24         |
|       └─TableFullScan_22     |   5000.00   | 119994608.00 | batchCop[tiflash] | table:lineitem | keep order:false                  |
+------------------------------+-------------|--------------+-------------------+----------------+-----------------------------------+
```

## tech design

add an interface `getCost` for physical plan. we can assign the cost to physical plan when they attach to any task. Because every physical plan is only attached once, the assignment of cost is unique and clear.

## test design

unit test will suffice

**Comment by qw4990** [comment]
I agree and here is another point from our user https://github.com/pingcap/tidb/issues/20676#issuecomment-731929203.

**Comment by qw4990** [comment]
Is there any progress to accept and promote feature requirements from outside(other teams or contributors)? @zz-jason 
This requirement looks good to me, so should I approve it?
And what're your options about this requirement? @winoros @eurekaka

**Comment by zz-jason** [comment]
@hanfei1991 please write a detailed proposal about this feature, including feature design, tech design, and test design.

**Comment by hanfei1991** [comment]
@zz-jason add some info in the description.
