### ISSUE TITLE
unreserved keyword mustn't be in select field alone. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#238]
```
tidb> select value;
+-------+
| value |
+-------+
| NULL  |
+-------+
```

```
mysql> select value;
ERROR 1054 (42S22): Unknown column 'value' in 'field list'
```

**Comment by shenli** [comment]
@siddontang 
Seems only a few elements can be in select from dual field list. I think this is handled in SelectFieldsDefaultPlan when evaluate field list.
mysql> select xxx;
ERROR 1054 (42S22): Unknown column 'xxx' in 'field list'
