### ISSUE TITLE
expression index using autoinc column

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb#23815]
## Feature Request

If I try to create an expression index on an autoincremented column like this:

```
CREATE TABLE customers (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  PRIMARY KEY (id),
  INDEX vitess_hash_8_msb((vitess_hash(id) >> 56))                     
)
```

I get the following error:
```
Error 3754: Expression index 'vitess_hash_8_msb' cannot refer to an auto-increment column
```

We have a use case where we do need an expression index on an auto-incremented column.

**Comment by tirsen** [comment]
I'm guess it's because the auto increment value hasn't been assigned when the expression pseudo-column is evaluated?

**Comment by kolbe** [comment]
This restriction also exists in MySQL: https://bugs.mysql.com/bug.php?id=78290
```
REASON FOR THE LIMITATION:

It's a necessary limitation; the order of ops is:
fill_record() (sql layer)
write_row() (engine-specific call).
the generated column is calculated by update_generated_write_fields() called
from fill_record(). Autoinc value is determined by storage engine in
write_row() (because different engines have different ways to store autoinc
global counter, and to retrieve it, with special concurrency measures). So,
if generated column depends on autoinc value, it cannot be calculated as
autoinc value isn't yet known.
```

If we're lucky, the TiDB architecture and order-of-operations is different enough that we might be able to more easily lift this restriction.

**Comment by morgo** [comment]
TiDB often has the same restrictions as MySQL so that it doesn't lock users in (for example: the number of columns on a table). We will have to check if it is one of those cases, in which case a config option can be added to lift the restriction.

**Comment by wjhuang2016** [comment]
> This restriction also exists in MySQL: https://bugs.mysql.com/bug.php?id=78290
> 
> ```
> REASON FOR THE LIMITATION:
> 
> It's a necessary limitation; the order of ops is:
> fill_record() (sql layer)
> write_row() (engine-specific call).
> the generated column is calculated by update_generated_write_fields() called
> from fill_record(). Autoinc value is determined by storage engine in
> write_row() (because different engines have different ways to store autoinc
> global counter, and to retrieve it, with special concurrency measures). So,
> if generated column depends on autoinc value, it cannot be calculated as
> autoinc value isn't yet known.
> ```
> 
> If we're lucky, the TiDB architecture and order-of-operations is different enough that we might be able to more easily lift this restriction.

I tested it and TiDB can work as expected. So maybe we can add an option to relax the restriction.

**Comment by bezmax** [comment]
If this is going to be implemented, I think this restriction is as arbitrary (and very similar too):
```
mysql> alter table customers add column vitess_shard bigint unsigned as (vitess_hash(id) >> 56);
ERROR 3109 (HY000): Generated column 'vitess_shard' cannot refer to auto-increment column.
```

**Comment by wjhuang2016** [comment]
> If this is going to be implemented, I think this restriction is as arbitrary (and very similar too):
> 
> ```
> mysql> alter table customers add column vitess_shard bigint unsigned as (vitess_hash(id) >> 56);
> ERROR 3109 (HY000): Generated column 'vitess_shard' cannot refer to auto-increment column.
> ```

Yeah, the reason that the expression index can not use the auto-increment column is that the generated column can not use it. This limit is inherited from the generated column.
