### ISSUE TITLE
show drainer status will get panic when All pd have been replaced

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#23829]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. scale out new pd
2. scale in all the old pd
3. execute `show drainer status`

### 2. What did you expect to see? (Required)
statement executed successfully.

### 3. What did you see instead (Required)
tidb get panic

### 4. What is your TiDB version? (Required)
master version

**Comment by bb7133** [comment]
Close this issue since binlog-based replication has been deprecated for a long time.
