### ISSUE TITLE
improve update ignore & Insert on duplicate ignore performance

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#23824]
## Development Task

currently, "update" or "insert on duplicate update" modify Int Primary Key or Clustered Primary Key will trigger a special code path called "handle change" in write.go: `updateRecord()` method

https://github.com/pingcap/tidb/blob/master/executor/write.go#L192

handle change means we need change KV pair's key due to primary changed, but it's not very effective

specially, when  "update" or "insert on duplicate update" works  with "ignore" keyword.

it will precheck each unique key with additional KVGet requests before removing the old record and add the new record, the old code want to avoid miss remove record like https://github.com/pingcap/tidb/issues/23809

but it's better to use the same mechanism like "handle no changed" code path

https://github.com/pingcap/tidb/blob/master/executor/write.go#L218

instead of precheck with additional RPC, uses rollbackable buffer named `StagingHandle`

https://github.com/pingcap/tidb/blob/master/table/tables/tables.go#L322
 
check duplicate at add record or index to Staging buffer time, rollback buffer if any error.

**Comment by TszKitLo40** [comment]
I want to try this issue. But if I have question, can I get help from you in Slack? @lysu

**Comment by lysu** [comment]
> I want to try this issue. But if I have question, can I get help from you in Slack? @lysu

surely, my nickname in community is robi

**Comment by cfzjywxk** [comment]
Do we have other pathes which do the samething like this? 
BTW, the `on duplicate/ignore` path seems need much more test enhancements :frowning: .
