### ISSUE TITLE
How to use TiGraph?

### ISSUE THREAD

**Issue by kilik52** [pingcap/tidb#23851]
## General Question

Hi, i cannot found any documents about TiGraph except one PR report. i wonder if TiGraph is useable or still under development. thx

**Comment by crazycs520** [comment]
@kilik52 TiGraph is in another repo, here is a usage demo:
https://github.com/tigraph/tidb/blob/master/demo.md

**Comment by tisonkun** [comment]
Closed as answered and no more followups.
