### ISSUE TITLE
support regular expression related functions

### ISSUE THREAD

**Issue by windtalker** [pingcap/tidb#23881]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

From MySQL 8.0, more [regular expression](https://dev.mysql.com/doc/refman/8.0/en/regexp.html) function is supported, I would like TiDB to support more regular expression functions(`REGEXP_INSTR()`,`REGEXP_LIKE()`,`REGEXP_REPLACE()`,`REGEXP_SUBSTR()`) as well. 
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Mini256** [comment]
Anything updated about this issue? 🤔

**Comment by xzhangxian1008** [comment]
> Anything updated about this issue? 🤔
> 
> I want to use the REGEXP_SUBSTR function in the SQL query to intercept the string in the query result, but I found that TIDB does not support the use of regular expressions for string extraction.
> 
> Is there any other alternative way to achieve the same function?

We will start this feature as soon as possible.
