### ISSUE TITLE
Record evicted information of statements_summary

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#23920]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, `statements_summary_history` use LRU cache strategy to cache recent 200 statements and each statement with 24 histories by default. 

The old statements which frequently executed before may be evicted by the new statements. Then we can't see it at some time in the past.

In short, we want to record the following information for a certain period of time:

* evicted_statements_count

**Describe the feature you'd like:**

Add a new system table such as: `statements_summary_lost`, query this this will get the following information:

| Begin_time          | End_time            | Evicted_count |
| ------------------- | ------------------- | ------------- |
| 2021-04-08 12:00:00 | 2021-04-08 12:30:00 | 10            |
| 2021-04-08 12:30:00 | 2021-04-08 13:00:00 | 50            |

As, neet provide a related cluster table such as: `cluster_statements_summary_lost`:

Instance | Begin_time | End_time | Evicted_count |
-- | -- | -- | -- |
tidb-0 | 2021-04-08 12:00:00 | 2021-04-08 12:30:00 | 10 | 
tidb-1 | 2021-04-08 12:00:00 | 2021-04-08 12:30:00 | 50 | 

**Describe alternatives you've considered:**

related work PR: https://github.com/pingcap/tidb/pull/23714

**Teachability, Documentation, Adoption, Migration Strategy:**

I will provide a detailed design doc later ...

**Comment by crazycs520** [comment]
@breeswish PTAL

**Comment by breeswish** [comment]
The evicted_count of `cluster_xxx` table will be very inaccurate if we simply add them together. Can we resolve it?

**Comment by Max-Cheng** [comment]
> The evicted_count of `cluster_xxx` table will be very inaccurate if we simply sum records together. Can we resolve it?

My idea was to use a hash table to filter through but was rejected by @crazycs520 , the rest of the solution may be to add more information to `Evictedinfo` to determine but it may increase the processing time

**Comment by breeswish** [comment]
> > The evicted_count of `cluster_xxx` table will be very inaccurate if we simply sum records together. Can we resolve it?
> 
> My idea was to use a hash table to filter through but was rejected by @crazycs520 , the rest of the solution may be to add more information to `Evictedinfo` to determine but it may increase the processing time

@crazycs520 remind me that maybe we just don't need the sum of cluster evict count, as we only need max evict count in different nodes in order to adjust the evict settings.

**Comment by Max-Cheng** [comment]
> > > The evicted_count of `cluster_xxx` table will be very inaccurate if we simply sum records together. Can we resolve it?
> > 
> > 
> > My idea was to use a hash table to filter through but was rejected by @crazycs520 , the rest of the solution may be to add more information to `Evictedinfo` to determine but it may increase the processing time
> 
> @crazycs520 remind me that maybe we just don't need the sum of cluster evict count, as we only need max evict count in different nodes in order to adjust the evict settings.

I'll look at the design docs tomorrow and hopefully build a preview version over the weekend

**Comment by morgo** [comment]
The historical MySQL way to do this would be to implement a status counter. i.e. `SHOW GLOBAL STATUS LIKE 'statements_summary_evicted_count'`. Unfortunately this would not map to the time windows nicely, so you would have to poll this statistic to keep track.

**Comment by crazycs520** [comment]
> The historical MySQL way to do this would be to implement a status counter. i.e. `SHOW GLOBAL STATUS LIKE 'statements_summary_evicted_count'`. Unfortunately this would not map to the time windows nicely, so you would have to poll this statistic to keep track.

Yes, so I prefer providing a system table to display this information. 
What do you think of this idea? 
If so, can the table name be called `statements_summary_evicted_count` or `statements_summary_lost `.  Since MySQL uses the name `lost`. https://dev.mysql.com/doc/refman/5.7/en/performance-schema-status-variables.html#statvar_Performance_schema_digest_lost

**Comment by morgo** [comment]
I like the idea of copying MySQL. statements_summary is similar to performance_schema, but we have renamed it because it is not exactly the same.
