### ISSUE TITLE
The query in a concurrent transaction returns incorrect results

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#23966]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* init */ drop table if exists t;
/* init */ create table t (c1 int primary key, c2 int, index(c2));
/* init */ insert into t values (1,1);
/* t1 */ begin;
/* t1 */ select * from t;
/* t1 */ update t set c1=2 where c1=1;
/* t2 */ begin;
/* t2 */ select * from t;
/* t2 */ delete from t;
/* t1 */ commit;
/* t2 */ select * from t;
```

### 2. What did you expect to see? (Required)

The last select should return empty set.
```
MySQL [test]> select * from t;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
MySQL [test]> select * from t;
+----+------+
| c1 | c2   |
+----+------+
|  1 |    1 |
+----+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

release-5.0 & release-4.0

**Comment by wjhuang2016** [comment]
`delete from t;` should be blocked and failed, please check it again.
``` sql
mysql> delete from t;
ERROR 1205 (HY000): Lock wait timeout exceeded; try restarting transaction
```

**Comment by cfzjywxk** [comment]
This behaviour is compatible with MySQL, the reason for this is still the mixed usage of current read and snapshot read, I think we could document about this clearer.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
