### ISSUE TITLE
Use hint to enforce TiDB run query in MPP mode

### ISSUE THREAD

**Issue by leiysky** [pingcap/tidb#23990]
## Feature Request

**Is your feature request related to a problem? Please describe:**
So far, TiDB doesn't have ability to enforce query to be ran in MPP mode.

Since CBO of MPP query is not stable enough, TiDB may choose plan randomly in some case, which may cause serious degredation of performance.

We need an approach(e.g. hint) to enforce TiDB run specific query in MPP mode.

**Describe the feature you'd like:**
Add a hint to enforce TiDB run query in MPP mode.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**
TODO

**Comment by fzhedu** [comment]
approved

**Comment by LittleFall** [comment]
closed by https://github.com/pingcap/tidb/pull/25302
(hint todo)
