### ISSUE TITLE
Using HTTP API to enable/disable async commit and 1PC for TIDB 5.0 is invalid

### ISSUE THREAD

**Issue by opsfarmer** [pingcap/tidb#24017]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
From TIDB 4.0.11 upgrade to TIDB 5.0，have no “tidb_enable_async_commit”  system variable
"set global" is invalid:
SQL >  set global tidb_enable_async_commit = ON; 
Query OK, 0 rows affected (0.00 sec)

Wed Apr 14 15:45:58 2021
SQL > set global tidb_enable_1pc = ON;
Query OK, 0 rows affected (0.00 sec)

SQL >  show variables like '%tidb_enable_async_commit%';
Empty set (0.83 sec)

SQL > show variables like '%tidb_enable_1pc%';         
Empty set (0.00 sec)

In addition，Using HTTP  API Setting is invalid:
curl -X POST -d "tidb_enable_async_commit=1" http://{TiDBIP}:10080/settings
curl -X POST -d "tidb_enable_async_commit=0" http://{TiDBIP}:10080/settings
curl -X POST -d "tidb_enable_1pc=1" http://{TiDBIP}:10080/settings
curl -X POST -d "tidb_enable_1pc=1" http://{TiDBIP}:10080/settings
### 2. What did you expect to see? (Required)
enable/disable async commit is  valid 
### 4. What is your TiDB version? (Required)
TIDB 5.0 GA

 Release Version: v5.0.0
Edition: Community
Git Commit Hash: bdac0885cd11bdf571aad9353bfc24e13554b91c
Git Branch: heads/refs/tags/v5.0.0
UTC Build Time: 2021-04-06 16:36:29
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by sticnarf** [comment]
They are "feature switch variables", which means they don't appear in `SHOW VARIABLES` statements

https://github.com/pingcap/tidb/blob/master/sessionctx/variable/tidb_vars.go#L708

You can use `select @@tidb_enable_async_commit` and `select @@tidb_enable_1pc` to query .

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
