### ISSUE TITLE
Record all evicted statements information by sum

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#24083]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

`statements_summary` uses LRU cache to store the statements information. So, when the LRU cache is full, it will remove the oldest statement.

I think TiDB can also collect the removed statement information by sum. Here is some example:

**Before this Issue**

```sql
select * from statements_summary:
```

| digest        | EXEC_COUNT | SUM_LATENCY | ...  |
| ------------- | ---------- | ----------- | ---- |
| statement_1   | 1          | 1           |      |
| statement_2   | 2          | 2           |      |
| statement_3   | 3          | 3           |      |
| .......       |            |             |      |
| statement_200 | 200        | 200         |      |

By default, `tidb_stmt_summary_max_stmt_count` variable value is `200`, means the capacity of LRU cache is `200`, So tidb can only store atmost `200` statements.

**This Issue request**

```sql
select * from statements_summary:
```

| digest        | EXEC_COUNT | SUM_LATENCY | ...  |
| ------------- | ---------- | ----------- | ---- |
| statement_1   | 1          | 1           |      |
| statement_2   | 2          | 2           |      |
| statement_3   | 3          | 3           |      |
| .......       |            |             |      |
| statement_200 | 200        | 200         |      |
| Other         | 1000       | 1000        |      |

As you can see, we can use `Other` to store the removed statements information. with this information, I can know the toal query `sum_latency` in the current time range.

### Alternative plan

Except record `Other` informantion as aforementioned. We can just provide another system table to export related data:

related issue here: https://github.com/pingcap/tidb/issues/23920

We can also provide more informantion in `statements_summary_meta` table, such as:

* total evicted statement count
* total exec statement count
* total exec statement latency
* total cop process time
...

**Comment by crazycs520** [comment]
@breeswish @djshow832 PTAL

**Comment by breeswish** [comment]
Does this mean that if we implement this one, then we no longer need the evict count?
