### ISSUE TITLE
Add design document for common table expression

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#24107]
## Development Task

Related PR：https://github.com/pingcap/tidb/pull/18247 and https://github.com/pingcap/tidb/pull/19253

But they are not detailed enough, for example, they don't take the ‘MPP’ into consideration.

**Comment by tisonkun** [comment]
IMO supports for MPP can be considered individually, given that planning and execution model of tidb and those of tiflash(which contains MPP logics) is actually different. We can hardly consider all details up front but prevent blocking further evolving.

**Comment by wjhuang2016** [comment]
> IMO supports for MPP can be considered individually, given that planning and execution model of tidb and those of tiflash(which contains MPP logics) is actually different. We can hardly consider all details up front but prevent blocking further evolving.

No, we do need to consider them as a whole feature. That's why the detailed design is not decided yet.

**Comment by tisonkun** [comment]
ref https://github.com/pingcap/tidb/issues/17472
