### ISSUE TITLE
does tidb support procedure?

### ISSUE THREAD

**Issue by tracymacding** [pingcap/tidb#2413]
Does tidb support mysql procedure?

**Comment by shenli** [comment]
@tracymacding No, we do not support Stored Procedure.

**Comment by tracymacding** [comment]
any roadmap?

**Comment by shenli** [comment]
We do not have any plan for it.

**Comment by jmesyan** [comment]
oh, out mysql database use so many Stored Procedure, can't support it?

**Comment by coocood** [comment]
@jmesyan 
We still do not have a plan for it.

**Comment by jmesyan** [comment]
It's a pity @tracymacding
