### ISSUE TITLE
KILL TIDB or global KILL should cancel DDL

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#24144]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is forked from https://github.com/pingcap/tidb/issues/24031

Currently DDL tasks must be killed with `ADMIN CANCEL DDL x`. The MySQL compatible way should be to use the `KILL` statement.

It should be possible for `KILL TIDB` / `KILL` (with global kill) to understand it is a DDL statement and execute `ADMIN CANCEL DDL`.

**Comment by morgo** [comment]
I chatted with some colleagues on this - some of this might be historical (before global kill). There is also the case that some DDL jobs can not actually be canceled, so having a different statement may be useful since it can retrun an error to the caller etc.

**Comment by dveeden** [comment]
With MySQL if you kill a query/connection that somehow can't be killed it will still be in the processlist with a state of 'Killed' until it is really gone. So TiDB could do something similar. A warning/info message about this would be good indeed.

See also: https://dev.mysql.com/doc/refman/8.0/en/general-thread-states.html
