### ISSUE TITLE
Should we replace `a/b*b` scripts with `a - a%b` forms?

### ISSUE THREAD

**Issue by ClSlaid** [pingcap/tidb#24158]
## Should we replace `a/b*b` scripts with `a - a%b` forms?

Yesterday I came up with GoLang code in TiDB respository similar to following code:

```Go
// package foo

// var now int
now := time.Now().Unix()
// var interval int
interval := foo.getInterval()

intervalTime := now/interval*interval
```
The last line cut off `now` into intervalTime.

However, it's not as straight forward as following code:

```Go
intervalTime := now - now%interval
```

This two lines do actrually same thing, but why doing `a/b*b` instead of `a - a%b`? Performance issues?

I know few about ASM but you can check out [godbolt](https://godbolt.org/z/TrYcYzdWG) here, so I made some benchmarks and it came out like this:

![image](https://user-images.githubusercontent.com/44747719/115349662-b1a71800-a1e6-11eb-98d6-3464dbe7c049.png)

We can conclude that `a/b*b` is by no ways faster than `a - a%b`, and is not as that straight forward.

It is a good idea replace `a/b*b` with `a - a%b`.

**Comment by ichn-hu** [comment]
Hi @ClSlaid thanks for your question, I don't see any particular reason why we use a/b*b here, but it is also by no means less straight forward, you are welcomed to propose a PR to add a line of comment to help illustrate.
