### ISSUE TITLE
Correctness testing 2: test direct reading with other operators

### ISSUE THREAD

**Issue by zhuo-zhi** [pingcap/tidb#24162]
## Development Task

Subitems from #24150 

- [x]  <code>BatchGet</code> and <code>PointGet</code>
- [x]  <code>Order</code> + <code>Limit</code>
- [x]  All kinds of Joins, especially <code>IndexLookUpJoin</code>
- [x]  All kinds of Aggregations

**Comment by qw4990** [comment]
Close since all work items have been finished 🎊
