### ISSUE TITLE
Implement Lock View

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/tidb#24199]
## Development Task

We are going to implement the feature Lock View in Sprint3, which will be helpful and much improves the experience when diagnosing transaction lock contention, blocking and deadlocking issue. 

The development tasks will be done by me and @longfangsong .

Design doc: https://github.com/pingcap/tidb/pull/24375

Major development tasks: 

- [ ] Implement `TIDB_TRX` table which provides information of ongoing transactions. 
  - [x] Basic implementation @longfangsong https://github.com/pingcap/tidb/pull/22908
  - [x] Implement `ALL_SQL_DIGESTS` field @MyonKeminta https://github.com/pingcap/tidb/pull/24750
  - [x] Avoid potential inconsistency among columns caused by not atomically fetching different fields ([ref](https://github.com/pingcap/tidb/pull/22908#issuecomment-839563292)) @MyonKeminta https://github.com/pingcap/tidb/pull/24750
  - [ ] Implement other non-important fields in our design
- [x] Update the protocol in kvproto to pass necessary information around @MyonKeminta https://github.com/pingcap/kvproto/pull/752
- [x] TiKV Support reporting full wait chain information for deadlock errors @MyonKeminta https://github.com/tikv/tikv/pull/10085
- [x] Implement TiKV APIs to support exposing lock waiting information to TiDB @longfangsong https://github.com/tikv/tikv/pull/10153
- [x] TiDB support passing information about the statement (SQL Digest) to TiKV when acquiring pessimistic lock @MyonKeminta  https://github.com/pingcap/tidb/pull/24380
- [x] Implement `DATA_LOCK_WAIT` table that shows lock waiting information. @longfangsong https://github.com/pingcap/tidb/pull/24750
- [ ] Implement `DEADLOCK` table that shows recent several deadlock events. 
  - [x] Basic implementation @MyonKeminta  https://github.com/pingcap/tidb/pull/24524
  - [ ] Query `CLUSTER_TIDB_TRX` on deadlock for more rich information for the related transactions
  - [x] Configurable history capacity @longfangsong  https://github.com/pingcap/tidb/pull/24925

Documentation

- [x] User document @MyonKeminta https://github.com/pingcap/docs-cn/pull/6408

Optional improvements:
- [ ] Record information of not-finished statement to `statements_summary`, so that it can be used to find statements that's being blocked and can't finish.
- [ ] Add metrics to monitor memory usage of lock manager and deadlock detector.
- [ ] Display internal transactions' information in TIDB_TRX
- [ ] Avoid full scanning for TIDB_TRX and DATA_LOCK_WAITS to reduce the performance risk since TiDB automatically queries it when it encounters deadlocks.
- [ ] Check if TIDB SQL memquota can work for lock view

Misc
- Design document patch for renaming and introducing configs https://github.com/pingcap/tidb/pull/24718  https://github.com/pingcap/tidb/pull/24904
- Renaming of TIDB_TRX's LEN and SIZE column https://github.com/pingcap/tidb/pull/25061
- Remove the unimplemented ALL_SQL_DIGESTS field from the deadlocks table https://github.com/pingcap/tidb/pull/24939
- Fix unstable test https://github.com/tikv/tikv/pull/10311

**Comment by MyonKeminta** [comment]
Ok, I'm the bot :)

**Comment by MyonKeminta** [comment]
@longfangsong Maybe you need to implement the get_lock_wait_info api first (Implement TiKV APIs to support exposing lock waiting information to TiDB)

**Comment by longfangsong** [comment]
> @longfangsong Maybe you need to implement the get_lock_wait_info api first (Implement TiKV APIs to support exposing lock waiting information to TiDB)

Yes, I think these two should be implemented together.

**Comment by MyonKeminta** [comment]
Ok, I'll assign you both

**Comment by morgo** [comment]
I played around with this feature today, and it looks really useful! I have a couple of questions/suggestions:

1. The `digest` seems to be the last statement executed; but the len+size relates to the whole transaction. Is it possible to actually "digest" a transaction, so that I could see the statements that it is composed of? If this is not planned initially, maybe it is better to rename it to `LAST_STATEMENT_DIGEST` to be clearer? I was initially confused because all my digests were the same, but that was because I was querying `select * from information_schema.tidb_trx` in the trx session!

2. Related to the above question, I would love to have a way to see historical transactions as well as active (by digest). As well as locks held, I would like to know a count of the number of statements, the wall time of statements executing, and the wall time of the transaction. MySQL does not currently offer this functionality, but cockroachdb has this ([and actually more](https://www.cockroachlabs.com/docs/v21.1/ui-transactions-page.html)).

**Comment by MyonKeminta** [comment]
@morgo Thanks for  your feedback!
1. Currently the `digest` field shows the last executed statement, but that's actually not an expected behavior. In our design, it should show the *current executing statement*, which is corrected along with [this PR](https://github.com/pingcap/tidb/pull/24863). I agree that the naming is kind of confusing, and I'll propose a patch to the design to rename it to `CURR_STMT_DIGEST`. It's ok since the feature is not released in any version yet. As for the *transaction digest*, it sounds a good idea to me. However, it's not planned in this sprint, and I think we don't have enough time to implement it in addition.
2. We used to discuss about the information about historical transactions, but finally we thought the time is too short in this sprint, so we didn't plan it in the first version.

Though there are many useful things we didn't plan due to the time limit, we still have chance to continue improving it in the next sprint, but it depends on our PMs' decisions. For now, I think you can still expect that it will be improved in the next version.

**Comment by MyonKeminta** [comment]
Known issue +1 https://github.com/pingcap/tidb/issues/25029

**Comment by MyonKeminta** [comment]
Sprint 3 have ended. This issue will be closed and remaining tasks will be done in the future.
Future works will be managed by [this GitHub project](https://github.com/pingcap/tidb/projects/67).
