### ISSUE TITLE
The error code and info is incompatible doing alter table

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#24305]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t (k varchar(10) primary key, v int);
alter table t change column k k text;
```

### 2. What did you expect to see? (Required)
```
ERROR 1071 (42000): Specified key was too long; max key length is 3072 bytes
```
The error reported from tidb v4.0 and mysql.

### 3. What did you see instead (Required)
```
E8200: Unsupported modify column: column type conversion between 'varchar' and 'non-varchar' is currently unsupported yet
```
The error reporeted from tidb v5.0 and master branch

### 4. What is your TiDB version? (Required)
master `7e1533392030514440d27ba98001c374cdf8808f` branch

**Comment by cfzjywxk** [comment]
Is this error information change is expected? 
/cc @wjhuang2016 @bb7133

**Comment by wjhuang2016** [comment]
No, It should be "ERROR 1170 (42000): BLOB/TEXT column 'k' used in key specification without a key length"

**Comment by cfzjywxk** [comment]
@wjhuang2016 
Could someone help fix this, it will make some regression test suite keep failing.

**Comment by jianzhiyao** [comment]
For now, it's unable to change column type from ``varchar`` to ``text``.
Should we allow column changing from ``varchar`` to ``text``?
@cfzjywxk @wjhuang2016

**Comment by wjhuang2016** [comment]
> For now, it's unable to change column type from `varchar` to `text`.
> Should we allow column changing from `varchar` to `text`?
> @cfzjywxk @wjhuang2016

I think so, @AilinKid PTAL

**Comment by bb7133** [comment]
Verified in v5.1, v5.2, v5.3 and master:

```
tidb> tidb> drop table if exists t; create table t (k varchar(10) primary key, v int);
Query OK, 0 rows affected (0.02 sec)

Query OK, 0 rows affected (0.02 sec)

tidb> alter table t change column k k text;
ERROR 1170 (42000): BLOB/TEXT column 'k' used in key specification without a key length

tidb> drop table if exists t; create table t (k varchar(10), v int);
Query OK, 0 rows affected (0.02 sec)

Query OK, 0 rows affected (0.01 sec)

tidb> alter table t change column k k text;
Query OK, 0 rows affected (0.01 sec)
```

Now the behavior is the same with MySQL because of the support of 'changing column types'.
