### ISSUE TITLE
the `where 1` condition  was caused different results like mysql did

### ISSUE THREAD

**Issue by TheNorthMemory** [pingcap/tidb#2430]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
CREATE TABLE `test` (
`a` varchar(20) NOT NULL,
`b` int(11) DEFAULT NULL,
PRIMARY KEY (`a`)
) ENGINE=InnoDB;
insert into `test` values('x',1),('y',2),('z',3),('p', 3);

```

2. What did you expect to see?

 `select * from test where 1 limit 1,1;`

```
+---+------+
| a | b    |
+---+------+
| y |    2 |
+---+------+
1 rows in set (0.04 sec)
```

3. What did you see instead?

```
+---+------+
| a | b    |
+---+------+
| x |   1  |
| y |    2 |
+---+------+
2 rows in set (0.04 sec)
```

4. What version of Go are you using (`go version`)?

golang 1.6

**Comment by hanfei1991** [comment]
Thank you for your report ! this is a bug, i will fix it soon.
