### ISSUE TITLE
Wrong behavior when executing `alter table t add index c (c(3));`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#2432]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
create table t(c char);
alter table t add index c (c(3));

2. What did you expect to see?
ERROR 1089 (HY000): Incorrect prefix key; the used key part isn't a string, the used length is longer than the key part, or the storage engine doesn't support unique prefix keys

3. What did you see instead?
Query OK, 0 rows affected (0.01 sec)

**Comment by idlesummerbreeze** [comment]
Hi @zimulala ,

 I am going to give it a try. Is it ok ?

**Comment by ngaut** [comment]
Sure, feel free to fix it, thank you @idlesummerbreeze

**Comment by zimulala** [comment]
Fixed by #2441
