### ISSUE TITLE
When synchronizing data, the length of MySQL table name and field name is legal, but tidb is not

### ISSUE THREAD

**Issue by GdCwh** [pingcap/tidb#24377]
1. What did you do? If possible, provide a recipe for reproducing the error.

   MySQL synchronizes data to tidb, but the table name and field name are in Chinese

2. What did you expect to see?

   Even if the table name and field name are in Chinese, the synchronization is successful

3. What did you see instead?

   Identifier name '啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊' is too long

4. Versions of the cluster
   dm：v2.0.0
   tidb:  5.0

**Comment by xiongjiwei** [comment]
may be fixed by https://github.com/pingcap/tidb/pull/24337
