### ISSUE TITLE
ddl: the schema state is not appropriate for some removed-type ddl

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#24420]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![Screenshot_20210506_142031](https://user-images.githubusercontent.com/15825830/117252397-79efcf80-ae78-11eb-817c-d809cf5e6219.png)

As you see in the pic above
state-none has two meanings:
1. one for adding-type DDL, the job hasn't started yet / the job has been rollbacked.
2. one for removed-type DDL, the job hasn't started yet / the job has done.

### 2. What did you expect to see? (Required)
For some of those, queueing has a good semantic explanation, but not for the others.

### 3. What did you see instead (Required)
None/Queueing

### 4. What is your TiDB version? (Required)

master

**Comment by wjhuang2016** [comment]
I think it should be a feature request?

**Comment by zimulala** [comment]
Maybe not. It was changed by https://github.com/pingcap/parser/pull/1210. 
@Howie59 Would you be interested in dealing with it?

**Comment by Howie59** [comment]
> Maybe not. It was changed by [pingcap/parser#1210](https://github.com/pingcap/parser/pull/1210).
> @Howie59 Would you be interested in dealing with it?

ok. i could do this in my spare time
