### ISSUE TITLE
store: unistore will hang over in some case.

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#24428]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://github.com/pingcap/automated-tests/pull/658/files
```
start local tidb
cd ticase/column_type_change
go build
./column_type_change run -i suite.jsonnet TICASE-4941
```

The related goroutine
[tidb_debug_20210506140729.zip](https://github.com/pingcap/tidb/files/6433446/tidb_debug_20210506140729.zip)

I've tested it with a real tikv, it works.

### 2. What did you expect to see? (Required)
Test success.

### 3. What did you see instead (Required)
The test hangs over, do did the TiDB

### 4. What is your TiDB version? (Required)

master <commit 207ce344cbb044ffb1b2681f1ba320a154979f6d >

**Comment by tiancaiamao** [comment]
That's weird... from the goroutine stack, the code seems blocked in bager engine... it might happen when the `runFlushMemTable` goroutine exit  exceptionally.

Can it reproduce?

**Comment by zyguan** [comment]
No update for a long time, feel free to reopen it if the issue still exists.

**Comment by tiancaiamao** [comment]
The data race **might be** a possible reason... concurrent write breaks unistore and make it hang https://github.com/pingcap/tidb/issues/26832
