### ISSUE TITLE
0.99999 query latency is very high

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#2446]
0.99999 query latency is very high in our user's production environment. Please take a look.

![99](https://cloud.githubusercontent.com/assets/878009/21850506/dc62bde8-d845-11e6-8df7-61dc4a6b732a.png)

**Comment by ngaut** [comment]
The lowest latency is 500ms

**Comment by disksing** [comment]
In fact, the 99.999% graph could be easily misleading. When we have 1 long query that takes more than 8 seconds, it will fall into the <= 16s bucket and increases 99.999% duration to 16s in next 1 minute.

**Comment by ngaut** [comment]
Is that the real reason, are there any long queries every few seconds?

**Comment by disksing** [comment]
Only one long query at the beginning of the peak. It lasts 1 minute because we use `[1m]` to calculate rate

**Comment by andelf** [comment]
Prometheus's histogram type can't express `max req time` correctly.
the percentile value phi must satisfies:

Total_Requests > 1 / ( 1 - phi)

So phi is a dynamic value changes with total requests. 

OK to be more `9`s under heavy load, but will give upper bucket border under light load.

**Comment by coocood** [comment]
Outdated.
