### ISSUE TITLE
dynamic partition pruning mode cannot use PointGet and BatchGet

### ISSUE THREAD

**Issue by zhuo-zhi** [pingcap/tidb#24476]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create database test_batchget_pointget;

use test_batchget_pointget;

set @@tidb_partition_prune_mode = 'dynamic';

create table trange(a int, unique key(a)) partition by range(a) (
		partition p0 values less than (30),
		partition p1 values less than (60),
		partition p2 values less than (90),
		partition p3 values less than (120));


explain select a from trange where a=10;
```

### 2. What did you expect to see? (Required)

Use PointGet.

### 3. What did you see instead (Required)

Use IndexReader

### 4. What is your TiDB version? (Required)

Release Version: v4.0.0-beta.2-2792-g337beb1f8-dirty

**Comment by qw4990** [comment]
I remove the `type/bug` and add `type/enhancement` since this non-optimal plan can still work and return the correct result.
Would you like to take a look at this issue and finish this enhancement?  @zhuo-zhi 
`PointGet` can support `hash-partition` and it is handled in the function `TryFastPlan`, you can read through it to see why it cannot handle `hash-range`.

**Comment by zhuo-zhi** [comment]
> I remove the `type/bug` and add `type/enhancement` since this non-optimal plan can still work and return the correct result.
> Would you like to take a look at this issue and finish this enhancement? @zhuo-zhi
> `PointGet` can support `hash-partition` and it is handled in the function `TryFastPlan`, you can read through it to see why it cannot handle `hash-range`.

OK

**Comment by zhuo-zhi** [comment]
This issue is kind of similar with #12977

**Comment by zhuo-zhi** [comment]
The problem is because we haven't implemented PointGet and BatchGet for range/list partition table. Related Pull Requests are: [pr#14318](https://github.com/pingcap/tidb/pull/14318), [pr#15327](https://github.com/pingcap/tidb/pull/15327/files).

I'll try to continue on this development.
