### ISSUE TITLE
wrong incremental analyze index task if using version 3 stats

### ISSUE THREAD

**Issue by eurekaka** [pingcap/tidb#24545]
## Development Task

In version 3 stats, `buildAnalyzeTable` would be called for `analyze incremental table t index idx`, hence we would incremental analyze all the indexes of the table then, which would cause unexpected results. Do not build incremental analyze task in version 3 stats.

**Comment by zhangjinpeng1987** [comment]
What is the "unexpected results"?

**Comment by time-and-fate** [comment]
> What is the "unexpected results"?

The statistics will likely be inaccurate or totally wrong. The new analyze method is not designed to be used together with incremental analyze.
