### ISSUE TITLE
gran all privileges with database name wildcard is error

### ISSUE THREAD

**Issue by lauyoume** [pingcap/tidb#2456]
I want to grant privileges to dynamic database name with prefix

```
GRANT ALL PRIVILEGES ON `dddb_%`.* TO 'dduser'@'%' IDENTIFIED by '123456';
```
It's error. but mysql is ok.

```
ERROR 1105 (HY000): Unknown schema name: dddb_%!(NOVERB)
```

**Comment by tiancaiamao** [comment]
We've working on privilege related issues already, and the current situation would be improved in RC2.
Thanks for your feedback, please stay concerned.

**Comment by tiancaiamao** [comment]
hi, @lauyoume 

Grant privileges database name with prefix is supported now, you can try it like this:

```
CREATE USER 'dduser'@'%' IDENTIFIED by '123456';
GRANT ALL PRIVILEGES ON `dddb_%`.* TO 'dduser'@'%';
```

Create user and grant privilege written into one SQL is still not supported, we're working on it.

You can have a try, and  feel free to let know if you meet any problem.

**Comment by lauyoume** [comment]
This is good , It's very perfect.
