### ISSUE TITLE
update stmt get panic and wrong result

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#24567]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a int);
create table t1(b int);
```
### 2. What did you expect to see? (Required)
```sql
mysql> update (select 1 as a) as t set a=1;
ERROR 1288 (HY000): The target table t of the UPDATE is not updatable
mysql> update (select 1 as a) as t, t1 set a=1;
ERROR 1288 (HY000): The target table t of the UPDATE is not updatable
```
### 3. What did you see instead (Required)
```sql
mysql> update (select 1 as a) as t set a=1;
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
mysql> update (select 1 as a) as t, t1 set a=3;
Query OK, 0 rows affected (0.00 sec)
Rows matched: 0  Changed: 0  Warnings: 0
```

**Comment by guo-shaoge** [comment]
I cann't reproduce this on master.

    drop table if exists t;
    drop table if exists t1;
    create table t(a int);
    create table t1(b int);
    update (select 1 as a) as t set a=1;
    update (select 1 as a) as t, t1 set a=1;

No errors:

    mysql> update (select 1 as a) as t set a=1;
    Query OK, 0 rows affected (0.00 sec)
    Rows matched: 0  Changed: 0  Warnings: 0
    
    mysql> update (select 1 as a) as t, t1 set a=1;
    Query OK, 0 rows affected (0.00 sec)
    Rows matched: 0  Changed: 0  Warnings: 0

**Comment by lzmhhh123** [comment]
![image](https://user-images.githubusercontent.com/26040259/120283043-57bd6600-c2ed-11eb-9e38-8b9750057e3a.png)

https://github.com/pingcap/tidb/pull/24614 @xiongjiwei You claimed it is a bug in MySQL. What's your opinion?

**Comment by xiongjiwei** [comment]
@lzmhhh123 please see: https://bugs.mysql.com/bug.php?id=103665&thanks=unsub. MySQL will give an error, but it should not

**Comment by xiongjiwei** [comment]
it is different from this issue, this issue is tidb's bug

**Comment by AilinKid** [comment]
```
mysql> update (select 2) as t set a=1;
ERROR 1288 (HY000): The target table t of the UPDATE is not updatable

mysql> update (select 2) as t, (select 1) as t1 set a=1;
ERROR 1054 (42S22): Unknown column 'a' in 'field list'
```
some unreasonable presentation about this in MySQL8, I think this two should be the same.

after quick fix
```
mysql> update (select 1 as a) as t set a=1;
ERROR 1288 (HY000): The target table t of the UPDATE is not updatable

mysql> update (select 1 as a) as t, (select 1 as b) as t1 set a=1;
ERROR 1288 (HY000): The target table t of the UPDATE is not updatable
```

**Comment by ailing-octavio** [comment]
> ![image](https://user-images.githubusercontent.com/26040259/120283043-57bd6600-c2ed-11eb-9e38-8b9750057e3a.png)
> 
> [#24614](https://github.com/pingcap/tidb/pull/24614) [@xiongjiwei](https://github.com/xiongjiwei) You claimed it is a bug in MySQL. What's your opinion?





https://off-canvas-menu-invulner.github.io/Q2974oIRWf7mHWfrouoPXtW4lU2xusl4ETBlBYUDszE3eWpslTEShfr/
