### ISSUE TITLE
Should log table and index name when data inconsistencies occour

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#24643]
## Bug Report

TiDB will report and log an error message if it detects data inconsistencies, but it only logs the index name. We don't know the table name! For example,
https://github.com/pingcap/tidb/blob/b7c22aa31d062b77a96493519a6b50ca9b627971/executor/distsql.go#L1215-L1223

TiDB should log enough information.

**Comment by youjiali1995** [comment]
@aytrack It's not critical. It's only related to log...

**Comment by jyz0309** [comment]
It seems that this issue have been fixed. I will close it.
