### ISSUE TITLE
SessionPool may contain sessions with valid transaction state which results in TiDB unavailable

### ISSUE THREAD

**Issue by youjiali1995** [pingcap/tidb#24640]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

It's hard to reproduce but it happened.

1. TiDB fails to execute a restricted SQL due to network partition, and the internal session has got a start timestamp.
2. The TiDB is partitioned for a long time and the GC safepoint is greater than the session's start timestamp.
3. Network partition recovers, the internal session will report `GC life time is shorter than transaction duration` forever.

### 2. What did you expect to see? (Required)

TiDB is normal.

### 3. What did you see instead (Required)

As we can see from the log, the session which executes the internal SQL has a valid transaction state and its timestamp is behind the GC safepoint. It may result in TiDB unavailable for new connections because they can't load global variables.
```
[2021/05/12 09:04:49.469 +08:00] [WARN] [conn.go:575] ["open new session failure"] [conn=6546415] [error="[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2021-05-09 18:59:21.141 +0800 CST, GC safe point is 2021-05-12 08:46:39.215 +0800 CST"]
[2021/05/12 09:04:51.190 +08:00] [ERROR] [domain.go:916] ["update bindinfo failed"] [error="[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2021-05-09 18:59:21.741 +0800 CST, GC safe point is 2021-05-12 08:46:39.215 +0800 CST"]
```

The root cause is that we don't roll back the session if an error occurs in the `ExecRestrictedStmt` like https://github.com/pingcap/tidb/pull/14269 did.
https://github.com/pingcap/tidb/blob/b7c22aa31d062b77a96493519a6b50ca9b627971/session/session.go#L1370-L1375

### 4. What is your TiDB version? (Required)
v4.0.6, maybe affect all versions.

**Comment by youjiali1995** [comment]
BTW, it's confusing that there is not only one `sessionPool` struct and `sessionPool` interface. All of them should roll back the session before putting it back to the pool. More ridiculous, the `sessionPool` in `domain` package is private but it's exported by a exported function and implements other package's private interface!(`sessionPool` interface in session package)

**Comment by tiancaiamao** [comment]
This is a serious problem, I will take a look

**Comment by youjiali1995** [comment]
@tiancaiamao Seems v5.x doesn't have this problem because you have refactored once. I reproduced this in v4.x by partitioning TiDB and TiKV.
