### ISSUE TITLE
TIDB5.0.0 can't execute ddl by drainer send 

### ISSUE THREAD

**Issue by kimmy-github** [pingcap/tidb#24678]
Here is my issue:
I have a TIDB2.1.15 CLUSER,NOW I'd like to migrate to TIDB5.0.5,and I use tidb binlog to migrate data;After I set up pump and drainer and they all begin to work,I found there is no data from TIDB2.1.15 to TIDB5.0.0;

this is the drainer's log:
2021/05/14 12:12:55 syncer.go:516: [info] [ddl][start]use test_keystat; create table test2(name varchar(11));[commit ts]424883679751569418
2021/05/14 12:12:55 sql.go:86: [error] [exec][sql]use test_keystat; create table test2(name varchar(11));[args][][error]Error 1046: No database selected
2021/05/14 12:12:58 sql.go:86: [error] [exec][sql]use test_keystat; create table test2(name varchar(11));[args][][error]Error 1046: No database selected
2021/05/14 12:13:01 sql.go:86: [error] [exec][sql]use test_keystat; create table test2(name varchar(11));[args][][error]Error 1046: No database selected
2021/05/14 12:13:04 sql.go:86: [error] [exec][sql]use test_keystat; create table test2(name varchar(11));[args][][error]Error 1046: No database selected
2021/05/14 12:13:07 sql.go:86: [error] [exec][sql]use test_keystat; create table test2(name varchar(11));[args][][error]Error 1046: No database selected
2021/05/14 12:13:07 syncer.go:360: [fatal] Error 1046: No database selected
github.com/pingcap/errors.AddStack
/home/jenkins/workspace/release_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
/home/jenkins/workspace/release_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb-binlog/pkg/sql.ExecuteTxnWithHistogram
/home/jenkins/workspace/release_tidb_2.1/go/src/github.com/pingcap/tidb-binlog/pkg/sql/sql.go:91
github.com/pingcap/tidb-binlog/pkg/sql.ExecuteSQLsWithHistogram
/home/jenkins/workspace/release_tidb_2.1/go/src/github.com/pingcap/tidb-binlog/pkg/sql/sql.go:57
github.com/pingcap/tidb-binlog/drainer/executor.(*mysqlExecutor).Execute
/home/jenkins/workspace/release_tidb_2.1/go/src/github.com/pingcap/tidb-binlog/drainer/executor/mysql.go:33
github.com/pingcap/tidb-binlog/drainer.execute
/home/jenkins/workspace/release_tidb_2.1/go/src/github.com/pingcap/tidb-binlog/drainer/util.go:124
github.com/pingcap/tidb-binlog/drainer.(*Syncer).sync
/home/jenkins/workspace/release_tidb_2.1/go/src/github.com/pingcap/tidb-binlog/drainer/syncer.go:356
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1337

this is the tidb's log:

[2021/05/14 12:12:26.142 +08:00] [INFO] [session.go:2761] [“CRUCIAL OPERATION”] [conn=66077] [schemaVersion=59] [cur_db=] [sql=“create schema if not exists tidb_binlog”] [user=root@xxxxxxxx]
[2021/05/14 12:12:26.142 +08:00] [INFO] [session.go:2761] [“CRUCIAL OPERATION”] [conn=66077] [schemaVersion=59] [cur_db=] [sql=“create table if not exists tidb_binlog.checkpoint(clusterID bigint unsigned primary key, checkPoint MEDIUMTEXT)”] [user=root
@xxxxxxxx]
[2021/05/14 12:12:27.181 +08:00] [INFO] [conn.go:812] [“command dispatched failed”] [conn=66079] [connInfo=“id:66079, addr:xxxxxxxxxxxx:18906 status:11, collation:utf8_general_ci, user:root”] [command=Query] [status=“inTxn:1, autocommit:1”] [sql=“use t est_keystat; create table test2(name varchar(11));”] [txn_mode=PESSIMISTIC] [err="[planner:1046]No database selected\ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/e
rrors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15
ngithub.com/pingcap/tidb/planner/core.(*preprocessor).handleTableName\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:1116\ngithub.com/pingcap/tidb/planner/core.(*preprocessor
).Leave\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:355\ngithub.com/pingcap/parser/ast.(*TableName).Accept\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-a
md/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210325072920-0d17053a8a69/ast/dml.go:403\ngithub.com/pingcap/parser/ast.(*CreateTableStmt).Accept\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v
0.0.0-20210325072920-0d17053a8a69/ast/ddl.go:1036\ngithub.com/pingcap/tidb/planner/core.Preprocess\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:89\ngithub.com/pingcap/tidb/
server.(*clientConn).prefetchPointPlanKeys\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1555\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/
optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1482\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go
:1030\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:795\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspa
ce/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:477\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"]
[2021/05/14 12:12:30.182 +08:00] [INFO] [conn.go:812] [“command dispatched failed”] [conn=66079] [connInfo=“id:66079, addr:xxxxxx:18906 status:11, collation:utf8_general_ci, user:root”] [command=Query] [status=“inTxn:1, autocommit:1”] [sql=“use t est_keystat; create table test2(name varchar(11));”] [txn_mode=PESSIMISTIC] [err="[planner:1046]No database selected\ngithub.com/pingcap/errors.AddStack\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/e
rrors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15
ngithub.com/pingcap/tidb/planner/core.(*preprocessor).handleTableName\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:1116\ngithub.com/pingcap/tidb/planner/core.(*preprocessor
).Leave\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:355\ngithub.com/pingcap/parser/ast.(*TableName).Accept\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-a
md/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20210325072920-0d17053a8a69/ast/dml.go:403\ngithub.com/pingcap/parser/ast.(*CreateTableStmt).Accept\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/pkg/mod/github.com/pingcap/parser@v
0.0.0-20210325072920-0d17053a8a69/ast/ddl.go:1036\ngithub.com/pingcap/tidb/planner/core.Preprocess\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/planner/core/preprocess.go:89\ngithub.com/pingcap/tidb/
server.(*clientConn).prefetchPointPlanKeys\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1555\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/
optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:1482\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go
:1030\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/conn.go:795\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspa
ce/optimization-build-tidb-linux-amd/go/src/github.com/pingcap/tidb/server/server.go:477\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1357"]

from these logs,i can see the tidb receive the right binlog but it can't execute it in a right way;so what's gone do for this issue?

**Comment by kimmy-github** [comment]
the dest TiDB cluster is TIDB5.0.0,not 5.0.5

**Comment by bb7133** [comment]
Hi @kimmy-github , thanks for reporting it, we'll try to reproduce it.

**Comment by kimmy-github** [comment]
> reproduce it

how to reproduce it,should i provide information details?thank you

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
