### ISSUE TITLE
Add new telemetry statistic data within sprint3

### ISSUE THREAD

**Issue by kaixu120811** [pingcap/tidb#24695]
## Feature Request

Add statistic about SQL execution, transaction conflict, server load and cluster index.

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kaixu120811** [comment]
I will finish it by myself.

**Comment by bb7133** [comment]
Could we add the ['new collation'](https://docs.pingcap.com/tidb/stable/character-set-and-collation/#new-framework-for-collations) as well? It is added since v4.0.

**Comment by kaixu120811** [comment]
> Could we add the ['new collation'](https://docs.pingcap.com/tidb/stable/character-set-and-collation/#new-framework-for-collations) as well? It is added since v4.0.

Let's check it first, thanks.
