### ISSUE TITLE
Add comments to explain why here's no preview telemetry data  when telemetry is disabled.

### ISSUE THREAD

**Issue by kaixu120811** [pingcap/tidb#24707]
## Feature Request

If telemetry is disabled by configuration file or sys config, here is no preview telemetry data when a preview command is input .

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Defined2014** [comment]
Telemetry is removed, so close this issue.
