### ISSUE TITLE
Too many slow logs when loading data

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb#24734]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tiup bench tpcc -H tidb_host -P tidb_port -D tpcc --warehouses 84000 -T 32 prepare

### 2. What did you expect to see? (Required)

The command can run successfully.

### 3. What did you see instead (Required)

The command stuck at some point and disk is full. There are too many slow log generated and about 18GiB logs are generated per day. Some logs are look like following:
```
# Time: 2021-05-18T15:22:44.268946189Z
# Txn_start_ts: 425027531921948675
# User@Host: root[root]
# Conn_ID: 5289115
# Query_time: 0.435462345
# Parse_time: 0.008536968
# Compile_time: 0.005883545
# Rewrite_time: 0.001081781
# Optimize_time: 0
# Wait_TS: 0.000010719
# Prewrite_time: 0.346042114 Commit_time: 0.06598248 Get_commit_ts_time: 0.000375801 Write_keys: 2048 Write_size: 175279 Prewrite_region: 2
# DB: tpcc
# Is_internal: false
# Digest: 8c32252067051c91094efb6a37bc9012238470654b6b7fe6f70c318cda3c1046
# Num_cop_tasks: 0
# Mem_max: 986287
# Prepared: false
# Plan_from_cache: false
# Plan_from_binding: false
# Has_more_results: false
# KV_total: 3.080938895
# PD_total: 0.000388257
# Backoff_total: 0
# Write_sql_response_total: 0
# Succ: true
# Plan: tidb_decode_plan('xwHIMAkyN18xCTAJMAlOL0EJMAl0aW1lOjguNDFtcywgbG9vcHM6MSwgcHJlcGFyZToyLjU5ARkkaW5zZXJ0OjUuOAUoYGNvbW1pdF90eG46IHtwcmV3cml0ZTozNDYBLAxn
ZXRfESEoczozNzUuOMK1cywNNQQ6NgUlNHJlZ2lvbl9udW06MiwgBUAkX2tleXM6MjA0OBERZGJ5dGU6MTc1Mjc5fQk5NjMuMiBLQglOL0EK')
"INSERT INTO order_line ...
```

### 4. What is your TiDB version? (Required)
Release Version: v5.0.1
Edition: Community
Git Commit Hash: 1145e347d3469d8e89f88dce86f6926ca44b3cd8
Git Branch: heads/refs/tags/v5.0.1
UTC Build Time: 2021-04-23 05:51:17
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by xiongjiwei** [comment]
I think this issue should be an enhancement instead of bug

**Comment by BusyJay** [comment]
Why? Is it expected that keep loading data into TiDB will stuck at some point even though there are still enough space in TiKV?

**Comment by xiongjiwei** [comment]
> Why? Is it expected that keep loading data into TiDB will stuck at some point even though there are still enough space in TiKV?

sorry, misunderstand your point, thought there is a performance issue that makes the slow log too much.

**Comment by bb7133** [comment]
I don't think this is a bug: the current behavior is by-design. 

If there are too many slow log files, you can increase the threshold for slow queries, disable the slow log or set related parameters like `max-backups`.
