### ISSUE TITLE
Transaction MemDB size potential overflow

### ISSUE THREAD

**Issue by MyonKeminta** [pingcap/tidb#24795]
## Bug Report

Currently, the `MemDB` in transaction uses `int` type to record it's `Len` (count of keys) and `Size` (count of bytes) 

https://github.com/pingcap/tidb/blob/542da5d60bb6d7e63e694e908d11f8bde3bce920/store/tikv/unionstore/memdb.go#L62-L63

It seems that if a transaction is too large (over 2GB), the `size` field may overflow. And though it's not very likely to happen, the `len` field may also overflow if we support larger transactions in the future. I think It's better to replace them with `uint64`.

**Comment by hanlins** [comment]
Hi @MyonKeminta, do you have seen related bugs, or can you reproduce this issue in a large transaction? I think the size of `int` is dependant on the system. If the system is on a 32-bit platform (e.g. x86) then it will be 4 bytes in size, if on a 64-bit platform (e.g. x86-64) then it will be 8 bytes in size. Check [this](https://play.golang.org/p/hm10U-lHzqh) out.

Generally, I think it won't be a problem for typical 64-bit platforms. We can still change those types to make it more consistent with other fields, but if you have seen a failure for a large transaction, I would suspect it's related to something else.

**Comment by MyonKeminta** [comment]
@hanlins Ah, yes, you are right, it's actually safe. Being the one that usually use int64 explicitly in this case, I just feel the code  suspicious. Thanks for replying.
