### ISSUE TITLE
About the generative mechanism of TrackingID 

### ISSUE THREAD

**Issue by YinWeiling** [pingcap/tidb#24811]
## General Question
Thank for the great work. I have some questions to ask.
What's the generative mechanism of TrackingID? Under what circumstances (eg. restart, change of IP address, scale in & out, etc. ) will it change?

**Comment by tisonkun** [comment]
You can post the question on internals.tidb.io and our experts will take care of new posts for answering the question. Issues suffer from a large traffic of concrete development task and bug reports.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.

**Comment by YinWeiling** [comment]
邮件已经收到啦～
