### ISSUE TITLE
Issue found by Svace static analyzer(DEREF_AFTER_NULL)

### ISSUE THREAD

**Issue by vvdvortsova** [pingcap/tidb#24871]
## Development Task
Hello
This warning found with the Svace.
After having been compared to nil value, pointer 'store' is dereference.
https://github.com/pingcap/tidb/blob/d5e0ed0aaed72d2f2dfe24e9deec31cb6cb5fdf0/session/tidb.go#L54
https://github.com/pingcap/tidb/blob/d5e0ed0aaed72d2f2dfe24e9deec31cb6cb5fdf0/session/tidb.go#L60

**Comment by AilinKid** [comment]
I don't get it, @tiancaiamao do you figure it out?

**Comment by vvdvortsova** [comment]
Here the variable 'store' may be nil
https://github.com/pingcap/tidb/blob/d5e0ed0aaed72d2f2dfe24e9deec31cb6cb5fdf0/session/tidb.go#L60

**Comment by tiancaiamao** [comment]
The code is:

```
if  len(dm.domains) == 1 && store == nil { 
      return
}

store.UUID()
```

The static analyse maybe find a  case that if `len(dm.domains) != 1` and `store == nil`, the code panics.
However, `len(dm.domains) != 1` and `store == nil` is not a legal input for this function.
The equivalent code is:

```
if store == nil {
      if len(do.domains) == 1 {
          return ...
      } else {
          panic("illegal input")
      }
}
...
store.UUID()
```
