### ISSUE TITLE
Column type change test for GA

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#24910]
## Development Task

Currently, there are only some unit and functional tests for this feature. To make this function more stable, the following tests are added:

- Design ticases
  - [x] Conversion between the same types @zimulala
  - [x] Conversion between different types @zimulala
  - [x] Correctness test @AilinKid 
  - [x] Compatibility test with other features @AilinKid 
  
- Conversion between the same types

  - [x] Type conversion between Integer type @tangenta 
  - [x] Type conversion between String type  @tangenta 
  - [x] Type conversion between Time type @zimulala 
  - [x] Type conversion between Numeric type @AilinKid 

- Conversion between different types

  - [x] Integer type to other types  @tangenta 
  - [x] String type to other types    @tangenta       
  - [x] Numeric to other types    @zimulala  
  - [x] Time type to other types   @AilinKid 
  - [x] Json type to other types @AilinKid 

- Correctness test   

  - [x] Each state in the column type changing(CTC) process is accompanied by CRUD operations @AilinKid 

- Concurrent DDL (CTC Included) long-term stability test  @AilinKid 
   - [x] make ctc run in schr test alongside with other ddl and dml  

- Compatibility test with other features

  - [x] Compatibility with 1PC and async commit @AilinKid 
  - [x] Compatibility with Invisible Index  @AilinKid 
  - [x] Compatibility with Auto Increment @AilinKid 
  - [x] Compatibility with Collation @zimulala 

- Unsupported features：@zimulala 

  - [x] Compatibility with Cluster Index
  - [x] Compatibility with Generated Column
  - [x] Compatibility with Partition Table
  - [x] Compatibility with Expression Index

**Comment by zimulala** [comment]
The weekly report link:https://docs.google.com/document/d/10MXVdI2J_9hHhYL9ubTkzCDytgY3YhRXrJSECoyoZRY/edit#heading=h.fulmy43pr0uv

**Comment by tisonkun** [comment]
Hi @zimulala ! I can see that there is still 3 remaining issues in the project board. Why this tracking issue gets closed when there are remaining issues?
