### ISSUE TITLE
Restore database requires ALTER TABLE privilege

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#24912]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> SHOW GRANTS;
+------------------------------------------------+
| Grants for User                                |
+------------------------------------------------+
| GRANT USAGE ON *.* TO 'backupadmin'@'%'        |
| GRANT BACKUP_ADMIN ON *.* TO 'backupadmin'@'%' |
+------------------------------------------------+
2 rows in set (0.00 sec)

mysql> BACKUP DATABASE * TO 'local:///tmp/test';
+-------------------+------+--------------------+---------------------+---------------------+
| Destination       | Size | BackupTS           | Queue Time          | Execution Time      |
+-------------------+------+--------------------+---------------------+---------------------+
| local:///tmp/test | 3444 | 425215585720729602 | 2021-05-26 16:38:52 | 2021-05-26 16:38:52 |
+-------------------+------+--------------------+---------------------+---------------------+
1 row in set (0.02 sec)

mysql> RESTORE DATABASE * FROM 'local:///tmp/test';
ERROR 8125 (HY000): Restore failed: [planner:1142]ALTER command denied to user 'backupadmin'@'%' for table 't'
```

### 2. What did you expect to see? (Required)

It is useful to have a minimally privileged user be able to backup and restore data without having access to read the data. The scenario for backup is more common (and works), but restore is nice for `RESTORE` be orthogonal in permissions.

### 3. What did you see instead (Required)

I should ideally not need the super permission here.

### 4. What is your TiDB version? (Required)

```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.1.0-alpha-13-gd5e0ed0aa-dirty
Edition: Community
Git Commit Hash: d5e0ed0aaed72d2f2dfe24e9deec31cb6cb5fdf0
Git Branch: master
UTC Build Time: 2021-05-24 14:39:20
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
@kennytm do you have any strong opinions on this, or would you like me to take a look at it?

**Comment by morgo** [comment]
@jingshanglu This only affects master, and it is a case where a use-case requires more privileges than expected (not less). So it is more like moderate/major to me.

**Comment by morgo** [comment]
I chatted with @SunRunAway and we will use a new dynamic privilege called `RESTORE_ADMIN`. This handles the case that a user requires more privileges to restore than to backup a database.

In MySQL there is not a direct comparison, but the closest is with the [clone plugin](https://dev.mysql.com/doc/refman/8.0/en/clone-plugin-remote.html):

> "On the donor, the clone user requires the BACKUP_ADMIN privilege for accessing and transferring data from the donor, and for blocking DDL during the cloning operation." 
> "On the recipient, the clone user requires the CLONE_ADMIN privilege for replacing recipient data, blocking DDL during the cloning operation, and automatically restarting the server. The CLONE_ADMIN privilege includes BACKUP_ADMIN and SHUTDOWN privileges implicitly."

The privilege name `CLONE_ADMIN` doesn't make sense here. Because the name `RESTORE_ADMIN` strongly implies restoring, I will not add the implicit inclusion feature either.

**Comment by SunRunAway** [comment]
@morgo should RESTORE_ADMIN be documented here? https://github.com/morgo/tidb/blob/master/docs/design/2021-03-09-dynamic-privileges.md
