### ISSUE TITLE
Make AsOf compatible with Prepare

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#24932]
## Background
AsOf mainly used in the stale read scenes. details in https://github.com/pingcap/tidb/issues/21094. we need to let it compatible with Prepare. 

As Prepare will cache the `Plan` and also cache the `schema version`.  we may use the As Of such as :
```
"PREPARE mystmt SELECT * FROM table t AS OF TIMESTAMP NOW() - 2 SECOND where id=?";
```
If the schema is changed we should rebuild the prepare object in the cache.
## Details Implement
Currently, the prepare process already has the check schema version step:
https://github.com/pingcap/tidb/blob/e87d0359373f261d50106a29f0a9dd3d8de46214/planner/core/common_plans.go#L258-L273

We need to use the schema in the paste (define in the as of) to compare, do not use the latest schema. we may need to cache the as of Expr, then calculate the snapshots and the relative schema.

**Comment by nolouch** [comment]
cc @xhebox @JmPotato 
Can you help to solve this?

**Comment by xhebox** [comment]
I am on it.
