### ISSUE TITLE
UNIX_TIMESTAMP, Lost connection

### ISSUE THREAD

**Issue by shlomi-noach** [pingcap/tidb#2496]
Related: https://github.com/pingcap/tidb/pull/2369

1. What did you do?
```
tidb> select unix_timestamp(now());
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

2. What did you expect to see?

The time now.

3. What did you see instead?

```
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

4. What version of Go are you using (`go version`)?
```
go version go1.7.3 darwin/amd64
```

I've pulled `master` latest from today (2017-01-17) and attempted to run a few queries, which failed. I narrowed the error down to running `unix_timestamp(some_argument)` with any argument. `now()` being just a trivial example.

**Comment by shenli** [comment]
@shlomi-noach Thanks for your report! We will fix it.

**Comment by shenli** [comment]
@shlomi-noach It will be fixed in https://github.com/pingcap/tidb/pull/2497
