### ISSUE TITLE
alter table add partition error when sql_mode is set to ANSI_QUOTES

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#24980]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Originally reported from https://asktug.com/t/topic/69811

### 1. Minimal reproduce step (Required)

```
mysql> create TABLE TBL_KFK_VEHICLE_TEST (
    -> SourceId varchar(64) DEFAULT NULL,
    -> DeviceId varchar(64) DEFAULT NULL,
    -> PassTime timestamp NULL DEFAULT NULL,
    -> channelId varchar(64) DEFAULT NULL,
    -> address varchar(255) DEFAULT NULL,
    -> KEY DeviceId (DeviceId)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
    -> PARTITION BY RANGE (unix_timestamp(passtime))(
    -> PARTITION p20210429 VALUES LESS THAN ( UNIX_TIMESTAMP('2021-04-30 00:00:00') ),
    -> PARTITION p20210430 VALUES LESS THAN ( UNIX_TIMESTAMP('2021-05-01 00:00:00') ),
    -> PARTITION p20210501 VALUES LESS THAN ( UNIX_TIMESTAMP('2021-05-02 00:00:00') )
    -> );
Query OK, 0 rows affected (0.00 sec)

mysql> set @@sql_mode='ANSI_QUOTES';
Query OK, 0 rows affected (0.00 sec)

mysql>    ALTER TABLE TBL_KFK_VEHICLE_TEST ADD PARTITION (PARTITION p20210422 VALUES LESS THAN ( UNIX_TIMESTAMP('2021-06-23 00:00:00') ));
ERROR 1054 (42S22): Unknown column '2021-06-23 00:00:00' in 'expression'
```

### 2. What did you expect to see? (Required)

No error.

### 3. What did you see instead (Required)

The error message is misleading... what the hell is it actually?

----------

When `ANSI_QUOTES` is set,  UNIX_TIMESTAMP('2021-05-02 00:00:00’) is internally translated to 

```
SELECT UNIX_TIMESTAMP("2021-05-02 00:00:00") 
```

And when the session reuse the parser to parse the SQL, it's translated to:

```
SELECT UNIX_TIMESTAMP(`2021-05-02 00:00:00`)
```

And anything inside ``` is recognized as column name.

### 4. What is your TiDB version? (Required)

master, 5.x

**Comment by tiancaiamao** [comment]
PTAL @mjonss @qw4990

**Comment by djshow832** [comment]
closed by https://github.com/pingcap/tidb/pull/35379
