### ISSUE TITLE
Better explanation on errors

### ISSUE THREAD

**Issue by Unknwon** [pingcap/tidb#25]
Hi, 

I'm using https://github.com/go-xorm/tidb as driver for xorm, and when xorm executes following command:

```sql
SELECT `TABLE_NAME`, `ENGINE`, `TABLE_ROWS`, `AUTO_INCREMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB') [data/gogs.tidb]
```

TiDB gives me error:

```
[error] Compile sql error: use gogs.tidb - 1:9 expected one of [$end, ';', CHARACTER, CHARSET, COLLATE, DEFAULT]
```

So, which exactly this `1:9` points to? Maybe error message can be more clear like how MySQL does:

```
xxx near "my statement"
```

Or 

```
expect xx but found yy 
```

can be very helpful, too!

Thanks!

**Comment by shenli** [comment]
Hello Unknwon,
    "1:9" means there is an error near line 1 and column 9. 
     For your error log, there is a compile error in "use gogs.tidb" near the dot (the 9th character). I check parser/parser.y and find that use statement does not allow dbname with a dot. See: https://github.com/pingcap/tidb/blob/master/parser/parser.y#L3268

Thanks!

**Comment by shenli** [comment]
@Unknwon  please review this https://github.com/pingcap/tidb/pull/33

**Comment by Unknwon** [comment]
OK, thanks!

But please add this to docs.

**Comment by Unknwon** [comment]
Just tested again without dot in db name:

```
2015/09/07 05:32:52 session.go:123: [error] Compile sql error: use gogs-tidb - 1:9 expected one of [$end, ';', CHARACTER, CHARSET, COLLATE, DEFAULT]
[xorm] [info]  2015/09/07 05:32:52.159445 [sql] SELECT `TABLE_NAME`, `ENGINE`, `TABLE_ROWS`, `AUTO_INCREMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB') [data/gogs-tidb]
```

Exactly same error...

**Comment by Unknwon** [comment]
My bad.... `-` can be used either. :sob:

**Comment by mathiasrw** [comment]
@Unknwon try `_`

**Comment by shenli** [comment]
@Unknwon we only support letters, numbers and  '_'  in dbname and it must starts with a letter. Try gogs_tidb please.
You got the old style error log? Have you pulled the latest code and rebuild TiDB?

**Comment by Unknwon** [comment]
Thank you both @mathiasrw @shenli

Please put that on docs... it is very confusing.

**Comment by shenli** [comment]
I will improve the docs. Thanks!
