### ISSUE TITLE
cast: convert float value to json have different precision with MySQL

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#25032]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t(a json);
insert into t values("323232323.3232323232");
select * from t;

### 2. What did you expect to see? (Required)
MySQL
```
mysql> select * from t;
+-------------------+
| a                 |
+-------------------+
| 323232323.3232323 |
+-------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
TiDB
```
mysql> select * from t;
+--------------------+
| a                  |
+--------------------+
| 323232323.32323235 |
+--------------------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

**Comment by xiongjiwei** [comment]
maybe not a bug https://docs.pingcap.com/zh/tidb/stable/data-type-numeric#double-%E7%B1%BB%E5%9E%8B

**Comment by djshow832** [comment]
Maybe it's duplicate with #22791

**Comment by xiongjiwei** [comment]
we have a document that says the [difference](https://docs.pingcap.com/zh/tidb/stable/data-type-numeric#:~:text=%E4%B8%8E%E5%9C%A8%20MySQL,123456790%20%E5%92%8C%201.2345679%E3%80%82)
