### ISSUE TITLE
A better strategy to cache region's address.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#2511]
Currently, we cached all of the region address that we ever used, i think LRU is a better idea, especially when the database is huge.

**Comment by BusyJay** [comment]
Do we cache address for per region? @disksing A better idea is to cache address for store. There are just a few stores in a whole cluster.

**Comment by disksing** [comment]
The stores' addresses are cached by storeID, which is small and not frequently update.
And for the regions we have accessed, their metas are cached in an rbtree.
