### ISSUE TITLE
Bring some tests back online before 2021-06-18

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#25157]
## Five unstable tests should bring online before 2021-06-18
- [x] TestTopSQLCPUProfile @crazycs520 by ???
- [x] TestAnalyzeGlobalStatsWithOpts @qw4990 by https://github.com/pingcap/tidb/pull/25487
- [x] TestAnalyzeGlobalStatsWithOpts2 @qw4990 by https://github.com/pingcap/tidb/pull/25487
- [ ] TestGlobalKillSuite.TestLostConnection @ichn-hu  
- [ ] testSerialSuite1.TestMergeJoinInDisk @wshwsh12 

They are skipped in:
- https://github.com/pingcap/tidb/pull/25155
- https://github.com/pingcap/tidb/pull/25170

**Comment by zhouqiang-cl** [comment]
https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-nightly/detail/tidb-unit-test-nightly/1408/pipeline

**Comment by tisonkun** [comment]
closed as part resolved, and other parts logged as https://github.com/pingcap/tidb/issues/26409 and https://github.com/pingcap/tidb/issues/26410
