### ISSUE TITLE
admin: query all the regions a table covers

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#2516]
Sometimes, we want to know all the regions a table covers. Maybe we can support a SQL like `admin shows regions from table`

**Comment by morgo** [comment]
I opened a similar feature request via https://github.com/pingcap/tidb/issues/7714

I recommend using `information_schema` where possible, because it is more [discoverable](https://mysqlserverteam.com/making-mysql-easier-to-use-our-new-server-usability-guidelines/) for users.

**Comment by nullnotnil** [comment]
This is available as `SHOW TABLE REGIONS`. In docs: https://docs.pingcap.com/tidb/stable/sql-statement-show-table-regions

I am going to close this issue now. Thanks!
