### ISSUE TITLE
Local temporary table

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#25204]
## Description

A temporary table is a special table whose rows data are only temporarily available. https://github.com/pingcap/tidb/issues/24169

TiDB has implemented [global temporary tables](https://github.com/pingcap/tidb/projects/60), which is not enough to be released. We need also to implement local temporary tables.

## Document Collection

- Proposal doc: https://github.com/pingcap/tidb/pull/24168
- Weekly report: https://docs.google.com/document/d/1fUyXVkAJ06X3AIXc7TCu6DSaxS68KeqzH4pDURT1l-0

## Talent Challenge Program information

- Mentor of this issue: @djshow832 
- Recommended skills: Golang, SQL.
- Estimated Workloads: (3 Man-Months)

## Milestones and action items

Milestone 1: Finish local temporary table, Expected finish date: 7.31

- [ ] Finish in-memory local temporary table.

**Comment by tisonkun** [comment]
@djshow832 is this issue a subtask of #24169 ? If so, can we set up the reference between this two issues?

I can see that #24169 has a lot of `todo`s  so which ones this issue would contain?

**Comment by djshow832** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/24169
