### ISSUE TITLE
Support cancel session

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#2528]
Every session should bind a context to support cancel, and when the session context is canceled, stop all computation in this session immediately.

Providing that a session is cancelable, we could implement killing session feature, which is useful when the query runs too long.

see also https://github.com/pingcap/tidb/issues/2526

**Comment by c4pt0r** [comment]
any updates?

**Comment by tiancaiamao** [comment]
It should be basically available now.
