### ISSUE TITLE
have no way to get stable UNION result

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#25291]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1(c1 text COLLATE utf8_general_ci);
create table t2(c1 varchar(229) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'jLzPDUDsOmS');
insert into t1 select 'w';
insert into t2 select 'W';
```

run  this SQL several times 

```
 select c1 from t1 union select c1 from t2 order by c1
```

### 2. What did you expect to see? (Required)

stable result

### 3. What did you see instead (Required)

```
mysql> select c1 from t1 union select c1 from t2 order by c1;
+------+
| c1   |
+------+
| W    |
+------+
1 row in set (0.01 sec)

mysql> select c1 from t1 union select c1 from t2 order by c1;
+------+
| c1   |
+------+
| w    |
+------+
1 row in set (0.02 sec)
```

### 4. What is your TiDB version? (Required)

f81ef5579551a0523d18b049eb25ab3375bcfb48

**Comment by lzmhhh123** [comment]
It is because the `first_row` aggregate function returns the unstable collation sensitive value.

**Comment by lzmhhh123** [comment]
I think it's not a bug.

**Comment by qw4990** [comment]
> It is because the `first_row` aggregate function returns the unstable collation sensitive value.

I remove the bug label and add the enhancement label.

**Comment by lysu** [comment]
maybe we can do not fix this ...
