### ISSUE TITLE
v5.1.0 tidb new added config can't find in config.toml.example

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#25332]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
following configs are exist in select @@tidb_config, but don't exist in config.toml.example in 5.1 branch 
security.enable-sem
performance.tcp-no-delay
pessimistic-txn.deadlock-history-capacity

### 2. What did you expect to see? (Required)
new config should add in config.toml.example to show it's  default value

### 3. What did you see instead (Required)
can't find

### 4. What is your TiDB version? (Required)
v5.1.0

**Comment by morgo** [comment]
For sem, I've added it to master in https://github.com/pingcap/tidb/pull/25315 but not cherry picked it.
