### ISSUE TITLE
tidb 5.0.2  character set utf8mb4_general_ci is still case sensitive

### ISSUE THREAD

**Issue by An0nymous0** [pingcap/tidb#25368]
![image](https://user-images.githubusercontent.com/6836030/121664664-4983fc80-cada-11eb-9cff-1e4974639197.png)
![image](https://user-images.githubusercontent.com/6836030/121664675-4c7eed00-cada-11eb-810a-9729d15e5910.png)
![image](https://user-images.githubusercontent.com/6836030/121664794-73d5ba00-cada-11eb-99f1-29fd97665015.png)

**Comment by xiongjiwei** [comment]
please check the result 
```sql
SELECT VARIABLE_VALUE FROM mysql.tidb WHERE VARIABLE_NAME='new_collation_enabled';
```

ref https://docs.pingcap.com/tidb/stable/character-set-and-collation#new-framework-for-collations

**Comment by An0nymous0** [comment]
我是从5.0.1升级到的5.0.2出现的这个问题,我也修改了mysql.tidb表中的new_collation_enabled字段为ture同样无效。

**Comment by aytrack** [comment]
> This problem occurred when I upgraded from 5.0.1 to 5.0.2.
> 
> It's good after modifying new_collation_enabled is ture,The document says that new_collations_enabled_on_first_bootstrap cannot be set for existing clusters. I added that it took effect after restarting.
> 
> Also is it related to #24541

Did you mean it took effect while you just edited the config and restarted the cluster?  This should not take effect without deploying a new cluster.

**Comment by Defined2014** [comment]
No reply for a long time, so close this issue
