### ISSUE TITLE
Make clean will modify git workspace.

### ISSUE THREAD

**Issue by dianqihanwangzi** [pingcap/tidb#25401]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
make clean
```

### 2. What did you expect to see? (Required)
Git workspace not changed.

### 3. What did you see instead (Required)
Git workspace was changed(go.sum changed),it may broke CI.

### 4. What is your TiDB version? (Required)
dc40a093a0058b95fc859f60d4b84337dbdff9f6

**Comment by morgo** [comment]
@dianqihanwangzi Please paste the output of `go version`. Depending on what version you have, it can change the `go.sum` file

**Comment by dianqihanwangzi** [comment]
> @dianqihanwangzi Please paste the output of `go version`. Depending on what version you have, it can change the `go.sum` file
```
go version go1.13.4 darwin/amd64
```
the same as go.mod file defined. It seems some dependencies of "pingcap/failpoint" was not tracked in go.sum, but make clean command will build "pingcap/failpoint/failpoint-ctl".
```
go get github.com/pingcap/failpoint/code@v0.0.0-20210316064728-7acb0f0a3dfd
```
Excute this cmd may fix this.

**Comment by morgo** [comment]
@DanielZhangQD we updated master to 1.16 a couple of weeks ago. This branch (5.0) should still be on 1.13 though, so it might be an issue with a cherry pick pulling changes from master.
