### ISSUE TITLE
after upgrading v5.0.2 to v5.1.0，running go-tpc report some errors

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#25415]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a v5.0.2 tidb cluster with 3pd 2db 1ha 4kv.
2. upgrade v5.0.2 to v5.1.0
3. run go-tpc -H x -P x-D tpcc30k tpcc run -T 400 --warehouses 30000 --time 10h --ignore-error

### 2. What did you expect to see? (Required)

1. after upgrade to v5.1.0-20210608，run go-tpc can success

### 3. What did you see instead (Required)
after run go-tpc for few minutes，report some errors as follow
![tpc](https://user-images.githubusercontent.com/84712107/122003557-d2a27880-cde5-11eb-88d8-22f19865648a.png)

### 4. What is your TiDB version? (Required)
<img width="576" alt="无标题" src="https://user-images.githubusercontent.com/84712107/122004179-a89d8600-cde6-11eb-8be1-57365941e06c.png">

**Comment by lysu** [comment]
@Lily2025 maybe duplicated to https://github.com/pingcap/tidb/issues/25412
