### ISSUE TITLE
tidb_analyze_version default value is different when upgrade from 4.x and 5.x

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#25422]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

upgrade from 4.0.13 to 5.1.0, tidb_analyze_version=2 after upgrade;
upgrade from 5.0.2 to 5.1.0, tidb_analyze_version=1 after upgrade;

### 4. What is your TiDB version? (Required)

| Release Version: v5.1.0-20210611
Edition: Community
Git Commit Hash: 29bfbb2
Git Branch: heads/refs/tags/v5.1.0-20210611
UTC Build Time: 2021-06-11 07:52:09
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by winoros** [comment]
We want the old cluster to keep the original statistics behavior and the new cluster to use the new one. Wait for 1 sprint or 2 to use the new statistics for all clusters by default.
But after some investigation, we find that it's hard to identify the rolling update cluster and the whole new cluster by current code base.
So a not elegant solution is after you upgrade, reset the global `tidb_analyze_version` to 1.

**Comment by lilyjazz** [comment]
What is the influence for users between versions 1 and 2?
Why do we need to keep the tidb_analyze_version version 1 after we have a more accurate way (version 2) to collect data?

**Comment by xuyifangreeneyes** [comment]
#28352 describes the same problem.
