### ISSUE TITLE
Updating data reports `index out of range` when dropping columns with a single index

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#25462]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Find this issue when fix #24951. Related #25186.
```
 drop table t;
 CREATE TABLE t (a int, b int, index(a));
 insert into t set a = 123;
```

|  conn1                                                     | conn2   |
-----------------------------------------------------------|-----------
| `ALTER TABLE t DROP COLUMN a;` ||
| |(Delete Only/Delete reorg) UPDATE t SET b = '18';|

### 2. What did you expect to see? (Required)
`Query OK, 0 rows affected (0.00 sec)`

### 3. What did you see instead (Required)
`index out of range [1] with length 1`

### 4. What is your TiDB version? (Required)

```
Release Version: v5.2.0-alpha-73-gb52a38981-dirty
Edition: Community
Git Commit Hash: b52a38981ca107cc4206965a83f210566cfdf8ae
Git Branch: master
```

**Comment by zimulala** [comment]
#25342

**Comment by AilinKid** [comment]
Caused by golang slice index out of range

**Comment by wjhuang2016** [comment]
Drop column with index is not GA yet. So I think we can change it to moderate. /cc @bb7133

**Comment by bb7133** [comment]
OK, it is not even exposed to the end-user. I will downgrade the severity.

**Comment by Defined2014** [comment]
Seems it's already been fixed. Use the code below to prove this
```

func TestWriteDataWrite1(t *testing.T) {
	store, dom := testkit.CreateMockStoreAndDomainWithSchemaLease(t, dbTestLease)

	tk := testkit.NewTestKit(t, store)
	tk2 := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("CREATE TABLE t (a int, b int, index(a));")
	tk.MustExec("insert into t set a = 123;")
	tk2.MustExec("use test")

	originalCallback := dom.DDL().GetHook()
	defer dom.DDL().SetHook(originalCallback)

	hook := &callback.TestDDLCallback{Do: dom}
	hook.OnJobRunBeforeExported = func(job *model.Job) {
		if job.SchemaState != model.StateDeleteReorganization {
			return
		}
		tk2.MustExec("UPDATE t SET b = '18';")
	}
	dom.DDL().SetHook(hook)
	tk.MustExec("ALTER TABLE t DROP COLUMN a;")
}

```
