### ISSUE TITLE
Refine the behavior of `@@txn_scope` value and Local Txn

### ISSUE THREAD

**Issue by JmPotato** [pingcap/tidb#25479]
## Feature Request

Now, if we configure the `zone` label for a TiDB instance, then the default value of `@@txn_scope` will be "local", which is not quite reasonable. Because:

* User may only want to use the zone label to make sure the stale read could read the nearest data without enabling the Local TSO feature for the PD.
* Labeling a TiDB instance with a zone label without configuring the PD to enable Local TSO will get a PD timeout error because `@@txn_scope` is "local" by default, which is confusing.

So I suggest setting the default value of `@@txn_scope` to "global".

**Comment by nolouch** [comment]
@JmPotato I think the main reason is that `@@txn_scope` at the session level. It is unreasonable to set each connection in the application if the local transaction is used, so we directly use local in default if exist label configuration in TiDB. At that time, only local transactions could be used with label configuration. I think maybe we need a global variable to control the default value of local/global transaction's txn scope. cc @Yisaer

**Comment by tisonkun** [comment]
Is this issue part of https://github.com/pingcap/tidb/issues/21094?
