### ISSUE TITLE
Use telemetry to collate usages of sql_mode

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#25483]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB supports many sql_mode as MySQL. But we don't know if users really use it.
It would be better to use telemetry to collate the usages of SQL modes. It can help us to decide how to treat these SQL modes.

**Describe the feature you'd like:**

Use telemetry to collate usages of sql_mode.

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by Defined2014** [comment]
Telemetry already removed from TiDB repo, so close this issue.
