### ISSUE TITLE
Remove useless exported const `model.{AddIndexStr,AddPrimaryKeyStr}` from pingcap/parser

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tidb#25507]
## Development Task

In [pingcap/parser ddl.go](https://github.com/pingcap/parser/blob/af39ecc734c1f416d5fccf0eed9730df85c78278/model/ddl.go#L84-L88), we export 2 constants `AddIndexStr`,`AddPrimaryKeyStr` strangely. I think it is because TiDB need them in [ddl/ddl_worker.go](https://github.com/pingcap/tidb/blob/9e08fc559c8175d00aefd71fc84667ac4d5dfc21/ddl/ddl_worker.go#L447-L452) to make another DDL worker queue for adding index.

But I think we can change `newMetaWithQueueTp(txn kv.Transaction, tp string)` to `newMetaWithQueueTp(txn kv.Transaction, tp workerType)` and eliminate the usage of `model.{AddIndexStr,AddPrimaryKeyStr}` like this [compare/master...JaySon-Huang:remove_useless_const](https://github.com/pingcap/tidb/compare/master...JaySon-Huang:remove_useless_const?expand=1). It is also better to compare by a byte but not a string.

After changing it, we can remove the two useless exported const `model.{AddIndexStr,AddPrimaryKeyStr}` from `pingcap/parser`.

**Comment by tisonkun** [comment]
@ichn-hu @tiancaiamao any ideas?

**Comment by tiancaiamao** [comment]
I totally agree with @JaySon-Huang 
This issue is labeled as 'help wanted', the change is easy, hope someone will do it.

**Comment by tisonkun** [comment]
@JaySon-Huang we don't close this issue by #26218 . Do you intend to remove the definition in pingcap/parse also and then close this one?

**Comment by JaySon-Huang** [comment]
@tisonkun Yes, but I may do it later this weekend.

**Comment by JaySon-Huang** [comment]
I am going to close this issue since we have remove those exported vars from parser
