### ISSUE TITLE
transaction too large error when load a 17 megabytes insert

### ISSUE THREAD

**Issue by kaiwu** [pingcap/tidb#2554]
Please answer these questions before submitting your issue. Thanks!

## 1. What did you do?
If possible, provide a recipe for reproducing the error.

1. dumped a database with mydumper and option `-F 128`, one of the dumped file is over
17 megabytes
2. load the dumped files to tidb

## 2. What did you expect to see?

expect load to succeed, as this was not an issue before, did TiDB add some extra guarding
variables recently ?  it seems no documentation explained the needed parameters configuring
the transactions, what is the recommended size of a transaction ?

## 3. What did you see instead?

load failed with error :  `transaction too large`

## 4. What version of Go are you using (`go version`)?

tested on tidb rc1.1

```
Welcome to TiDB.
Version:
Git Commit Hash: 6befa6ddb72e2351b4f52a5a55980c00aa6f2367
UTC Build Time:  2017-01-23 03:53:30
```

**Comment by shenli** [comment]
@kaiwu May I have all the argument of your mydumper command?

**Comment by kaiwu** [comment]
@shenli  yes, it was 

```
docker run -it --rm -v dump:/data tidb:mydumper mydumper -h xxx.xxx.xxx.xxx -P xxxx -u xxxxx -p xxxxx -B xxxxx -t 16 -F 128 -o /data
```

where `tidb:mydumper` is an image built from [yfix/baseimage](https://github.com/yfix/docker-mydumper), could it be a mydumper problem ?

**Comment by shenli** [comment]
When use myload to load data, please add -q 1 in command line. Or you can use the `load` tool developed by us. See https://github.com/pingcap/docs-cn/blob/master/op-guide/migration.md#向-tidb-导入数据

**Comment by kaiwu** [comment]
i am using loader with option `-q 1` with above tests.
i just tried to dump with option `-F 8` to chop the dump to around 8 megabytes, still failed at `transaction too large` here is the trace

```
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/kv/memdb_buffer.go:106: [kv:11]transaction too large, len:100001
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/table/tables/tables.go:344:
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/executor/executor_write.go:661:
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/executor/adapter.go:135:
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/tidb.go:169:
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/session.go:468:
/home/jenkins/workspace/BRANCH_MANUAL_BUILD_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:659:
2017/01/25 14:29:29 terror.go:279: [warning] Unknown error class: kv code: 11
```

please kindly suggest, meanwhile i will be trying mydumper using `-F 4`. BTW,  the loading is on a 64g RAM machine so should not be a hardware issue.

what could be the `limit` for TiDB transactions ?

**Comment by shenli** [comment]
@kaiwu Do you have a table with only a few columns and with integer type? We set a limitation on the key-value entry count and size of a single transaction. For each row/index, there will be a key-value entry.
We increase the limitation from 100k to 300k a few days ago. You can try the latest master of tidb or download the [newest binary](http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz).

**Comment by kaiwu** [comment]
i see, your guess was right, the table is like below with only integers 

```sql 
  4 CREATE TABLE `goods_viewlog` (
  5   `log_id` mediumint(8) NOT NULL AUTO_INCREMENT,
  6   `member_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  7   `goods_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  8   `number` mediumint(8) unsigned DEFAULT '0',
  9   `createtime` int(10) unsigned DEFAULT NULL,
 10   PRIMARY KEY (`log_id`),
 11   UNIQUE KEY `unique_goods_id` (`member_id`,`goods_id`),
 12   KEY `idx_c_member_id` (`member_id`),
 13   KEY `idx_c_goods_id` (`goods_id`)
 14 ) ENGINE=InnoDB
```

could you kindly provide the commit sha value for your change, as rc1.1 was also only a few days ago, i could  check with commit logs

**Comment by shenli** [comment]
@kaiwu This feature is not merged into rc1.1 and we will release rc2 tomorrow. You can try the latest master. The commit is https://github.com/pingcap/tidb/commit/de9b134c50381123b9fa710ab4e2c110735f73b4

**Comment by kaiwu** [comment]
@shenli i confirm that latest master works with files dumped by mydumper using option `-F 2` in my case, and rc1.1 fails them with `transaction too large` error

**Comment by shenli** [comment]
@kaiwu Yes, we will release a new tag from master tomorrow. Please use master now.
