### ISSUE TITLE
Primary key Duplicate problem

### ISSUE THREAD

**Issue by lookhua** [pingcap/tidb#25572]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 4. What is your TiDB version? (Required)
tidb v4.0.13

Release Version: v4.0.13
Edition: Community
Git Commit Hash: 4f31cb49f083870f6b8e0f1ecc9183bc40c4ba42
Git Branch: heads/refs/tags/v4.0.13
UTC Build Time: 2021-05-19 04:40:49
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by aytrack** [comment]
seems some information was lost, please provide more informations
