### ISSUE TITLE
High GC CPU consumption when running sysbench point select

### ISSUE THREAD

**Issue by sticnarf** [pingcap/tidb#25573]
### 1. Minimal reproduce step (Required)

3 TiDB under one haproxy, 3 TiKV

sysbench 16 tables 10,000,000 rows per table

Run sysbench point select.  

### 2. What did you expect to see? (Required)

GC should not consume much CPU

### 3. What did you see instead (Required)

It is possible that `gcBgMarkWorker` consumes much CPU:
<img width="899" alt="图片" src="https://user-images.githubusercontent.com/17217495/122549250-ddb70c00-d064-11eb-9058-ceb9a6f4e7b6.png">

But it cannot be reproduced all the time.

### 4. What is your TiDB version? (Required)

TiDB 5.1 compiled with Go 1.16.4

**Comment by sticnarf** [comment]
In this profile zip, two TiDB instances (38_135.prof, 39_41.prof) encounter the issue, while the other one (35_167.prof) does not.
[510_prof.zip](https://github.com/pingcap/tidb/files/6676493/510_prof.zip)

**Comment by zhangjinpeng1987** [comment]
any update?

**Comment by zhangjinpeng1987** [comment]
Who is following this issue?

**Comment by sticnarf** [comment]
@zhangjinpeng1987 

The cause is that the strategy of triggering a GC in golang is too trivial:

>  A collection is triggered when the ratio of freshly allocated data to live data remaining after the previous collection reaches this percentage. The default is GOGC=100.

When running a workload with low memory usage (e.g. point select), the Go runtime triggers GC collections too frequently, leading to high CPU usage.

It seems not possible to solve the problem. Adjusting GOGC to a very high value is unreasonable in practice because TiDB also needs to support workloads that use lots of memory.

And Go does not support advanced strategies of GC triggering. It is by design because the Go team just wants it to be simple.

**Comment by zhangjinpeng1987** [comment]
@sticnarf Can we close this issue?

**Comment by sticnarf** [comment]
This is a case that needs to be optimized. But we don't have a good solution yet.

So I would like to keep this issue open, but we can lower the severity to `minor` because it is not a real performance regression. cc @aytrack

**Comment by tiancaiamao** [comment]
`GOGC=100` is the default value of the Go runtime.

What we should do is optimize the object allocation ...
I will take a look

**Comment by sticnarf** [comment]
@tiancaiamao 
I don't find it is a real regression for TiDB 5.1. It can also happen on older versions of TiDB.

My thought is that it is actually unnecessary for the Go runtime to collect the garbage that fast. For a server-side application which usually owns all resources of the machine, it is not so meaningful to keep the actual memory usage low. In this case, lower the frequency of GC by increasing `GOGC` greatly improves the performance.

**Comment by tiancaiamao** [comment]
Keep the GC CPU less than 25% of the total throughput is very, very important.
You can imagine the the Go runtime dedicate part of the CPU resource to the Mark&Sweep. However, when the GC speed can not catch up with the allocation speed, the runtime has to slow down the application, ask the goroutines to help with the recycling. That makes the application slower and cause latency jitter.

I find some places to optimize the allocation, but it's more important to find a way to observe those performance changes.
https://github.com/pingcap/tidb/issues/25754

Without micro performance benchmark, even though we can do some tiny optimizations when the problem emerge, we can't stop it from happening. And everyone change the code base and every change might be suspectable, we can't rely on someone to optimize it occasionally.

**Comment by tiancaiamao** [comment]
Increase `GOGC` is a trade-off, the process use more RAM for better GC throughput.

**Comment by dbsid** [comment]
should we increase GOGC from the default value, in order to mitigate this issue? I think most cases we want TiDB to be more aggressive on  memory allocation.

**Comment by tiancaiamao** [comment]
> should we increase GOGC from the default value, in order to mitigate this issue?

I don't think this is the best solution.
Maybe for some of the users that is a good option, but for some other users that change is not acceptable for them.

We should optimize TiDB to reduce unnecessary object allocation.

**Comment by tiancaiamao** [comment]
Sorry for the Chinese, I'll translate it later.
The observation is, if we can cut down the allocs/op by 30% (from 101 -> 67), we can get a performance improvement near 30%(from 9578 -> 6925)

```
BenchmarkPreparedPointGet-16    	  115844	      9578 ns/op	    7792 B/op	     101 allocs/op


EnableCollectExecutionInfo: false,
BenchmarkPreparedPointGet-16    	  132540	      8613 ns/op	    7224 B/op	      89 allocs/op


func (txn *LazyTxn) recreateTxnInfo()
BenchmarkPreparedPointGet-16    	 4501532	      7929 ns/op	    6973 B/op	      87 allocs/op
BenchmarkPreparedPointGet-16    	 4485886	      7964 ns/op	    6845 B/op	      86 allocs/op


干掉 snapshot 里面的 resolvedLocks 之后
BenchmarkPreparedPointGet-16    	 4558528	      8039 ns/op	    6621 B/op	      81 allocs/op

KVSnapshot 从 KVTxn 里面分配之后
BenchmarkPreparedPointGet-16    	 4580366	      7869 ns/op	    6605 B/op	      80 allocs/op

UnionStore 从 KVTxn 里面分配之后
BenchmarkPreparedPointGet-16    	 4611040	      7782 ns/op	    6613 B/op	      79 allocs/op


ResetStmtCtx

CTEStorageMap 干掉
每次不再 ClearStmtVars()
tikvTxn 里面的 id=>tableinfo 映射干掉
BenchmarkPreparedPointGet-16    	 4602043	      7682 ns/op	    6469 B/op	      76 allocs/op

memtracker 的分配搞掉
BenchmarkPreparedPointGet-16    	 4749812	      7488 ns/op	    6437 B/op	      72 allocs/op

SysVar 的 Clone()
BenchmarkPreparedPointGet-16    	 4737213	      7291 ns/op	    6245 B/op	      71 allocs/op

直接把 StmtCtx 的内存在 SessionVars 中分配
BenchmarkPreparedPointGet-16    	 5254296	      7008 ns/op	    5221 B/op	      70 allocs/op


优化 planbuilder 中间对象
BenchmarkPreparedPointGet-16    	 5242168	      6925 ns/op	    5173 B/op	      69 allocs/op

memtracker 不再处理 oom action
BenchmarkPreparedPointGet-16    	 5036514	      7116 ns/op	    5109 B/op	      67 allocs/op
```

**Comment by bb7133** [comment]
I do not think this is a bug and changed it to 'enhancment' instead.

**Comment by tiancaiamao** [comment]
I think we can close it now.
We're [monitoring the performance changes](http://www.zenlife.tk:18081/) now, if something goes wrong, we will find it soon.
