### ISSUE TITLE
control the size of TIDB-server log

### ISSUE THREAD

**Issue by zdjkea** [pingcap/tidb#25602]
目前我这里不是并测试tidb 5.02的版本。发现tidb.log很多，两天的时间就已经40G+了。能不能限制下日志的空间大小，测试的时候空间并不大。一旦超过会导致tidb服务故障不能使用

**Comment by ichn-hu** [comment]
https://docs.pingcap.com/zh/tidb/v3.1/tidb-configuration-file#logfile

**Comment by ichn-hu** [comment]
另外，类似的问题建议您一方面先搜索一番，另一方面是可以在 https://asktug.com/ 平台上提问，我们在 github 上主要是做开发相关的讨论~
