### ISSUE TITLE
Fuction adddate/subdate return type is different from mysql when the frist argument is varchar/char 

### ISSUE THREAD

**Issue by yuqi1129** [pingcap/tidb#25688]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run master branch in PC and do the following 
```
mysql -uroot -h127.0.0.1 -p --column-type-info
```
```
select adddate('2020-01-01', interval 1 day);
```

### 2. What did you expect to see? (Required)
**MySQL**
```
mysql>  select adddate('2020-01-01', interval 1 day);
Field   1:  `adddate('2020-01-01', interval 1 day)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     116
Max_length: 10
Decimals:   31
Flags:


+---------------------------------------+
| adddate('2020-01-01', interval 1 day) |
+---------------------------------------+
| 2020-01-02                            |
+---------------------------------------+
1 row in set (0.00 sec)

mysql>
```

### 3. What did you see instead (Required)
**TiDB** 
```
mysql> select adddate('2020-01-01', interval 1 day);
Field   1:  `adddate('2020-01-01', interval 1 day)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       DATETIME
Collation:  binary (63)
Length:     29
Max_length: 10
Decimals:   31
Flags:      NOT_NULL BINARY


+---------------------------------------+
| adddate('2020-01-01', interval 1 day) |
+---------------------------------------+
| 2020-01-02                            |
+---------------------------------------+
1 row in set (0.00 sec)

mysql>
```
`Type:       DATETIME` that means return type is different from mysql 

### 4. What is your TiDB version? (Required)
master

**Comment by lzmhhh123** [comment]
The length doesn't affect anything. The Max_length and Decimals are consistent.

**Comment by yuqi1129** [comment]
@lzmhhh123 It's the different return type that this issue addresses

**Comment by lzmhhh123** [comment]
> @lzmhhh123 It's the different return type that this issue addresses

Yep, however, IMHO, the datetime type is more reasonable.

**Comment by yuqi1129** [comment]
@lzmhhh123 Yes, i do agree with you on this point, but when you execute the following sql in MySQL and TiDB
```
select adddate('2020-01-01 16:00:00.123456789', interval 1 day) a, adddate('2020-01-01 15:59:00.12', interval 2 day)  % 2 b;
```
the value of b is different

the reason lies in here
![image](https://user-images.githubusercontent.com/15794564/124272048-d0c00f80-db70-11eb-8dc6-4081202a1de7.png)
