### ISSUE TITLE
support notifications by query (not just table) like RethinkDB

### ISSUE THREAD

**Issue by nkev** [pingcap/tidb#257]
It would be great to have RethinkDB style notifications for building real-time apps. For example, something like: 

```SQL
SELECT * FROM scores ORDER BY points DESC LIMIT 5 SUBSCRIBE
```
would return the top 5 scores the first time it is called, but it would also continue returning results to the calling function (Goroutine?) whenever the result changes. 

To unsubscribe from this notification, you could later send:

```SQL
SELECT * FROM scores ORDER BY points DESC LIMIT 5 UNSUBSCRIBE
```

Even more flexible would be a way to receive JSON updates to your API:

```SQL
SELECT * FROM scores ORDER BY points DESC LIMIT 5 SUBSCRIBE JSON  `http://localhost:8000/update-score`
```

Thoughts?

**Comment by ngaut** [comment]
Obviously, this is a cool feature. But currently we are focusing on the features in roadmap [https://github.com/pingcap/tidb/blob/master/ROADMAP.md].

**Comment by nkev** [comment]
shame you didn't put this into some kind of todo list, even if longer term. I think you will regret it down the line.

**Comment by ngaut** [comment]
HI, @nkev:
Thanks for you advice. The better choice would be RethinkDB or pipelinedb or some other streaming database if you need stream SQL. TiDB is mainly for OLTP.
