### ISSUE TITLE
why use a defer function just for log the connection is closed?

### ISSUE THREAD

**Issue by jiajunhuang** [pingcap/tidb#25717]
## General Question

I'm reading source code of TiDB, I found there is a statement like:

```go
    defer func() {
        logutil.Logger(ctx).Debug("connection closed")
    }()
```

in `server/server.go`, it seems it's unnecessary.

**Comment by morgo** [comment]
I agree it is unnecessary - it might have been code refactored incorrectly. Thank you for the PR!

**Comment by jiajunhuang** [comment]
> I agree it is unnecessary - it might have been code refactored incorrectly. Thank you for the PR!

I also found there is another case in the `server/conn.go`:

```go
// It also gets a token from server which is used to limit the concurrently handling clients.
// The most frequently used command is ComQuery.
func (cc *clientConn) dispatch(ctx context.Context, data []byte) error {
    defer func() {
        // reset killed for each request
        atomic.StoreUint32(&cc.ctx.GetSessionVars().Killed, 0)
    }()
```
I've push it to the PR.
