### ISSUE TITLE
slow query file requires a maximum storage time and maximum file limit

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#25716]
slow query file requires a maximum storage time and maximum file limit, like tidb.log

**Comment by glkappe** [comment]
i need labels

**Comment by yiduoyunQ** [comment]
seems just need `MaxDays` and `MaxBackups` of SlowQueryFile at https://github.com/pingcap/tidb/blob/v5.1.1/util/logutil/slow_query_logger.go#L25

**Comment by djshow832** [comment]
Closed by https://github.com/pingcap/tidb/pull/27625
