### ISSUE TITLE
tidb_ghpr_integration_common_test failed on Integration MySQL Test

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#25738]
~~It seems caused by https://github.com/pingcap/tidb/pull/25553~~

IT report https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/5363/pipeline/

**Comment by tisonkun** [comment]
cc @windtalker

**Comment by zhouqiang-cl** [comment]
Seems it caused by tidb-test changes in https://github.com/pingcap/tidb-test/pull/1220/files

**Comment by tisonkun** [comment]
closed by https://github.com/pingcap/tidb-test/pull/1224
