### ISSUE TITLE
Micro benchmark regularly and display benchmark result

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#25754]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We do not use the benchmark well.

Benchmarks can guide us the evaluation of the product performance.

- We just cover the typical TPCH  TPCC Sysbench test which is too high level.
- We just run the benchmark tests before a new release.

But they are too high level.

**Describe the feature you'd like:**

I'd like to have some micro benchmarks and run them regularly.

For example, if we have a `make bench` command to run the micro benchmarks, and the result is collected, 
and visualized, then we know the performance regression early.

**Describe alternatives you've considered:**

For example, there is a scheme benchmark website, https://ecraven.github.io/r7rs-benchmarks/
From which we can see the performance between different scheme compile implementation easily.

Another example is the rust pref https://perf.rust-lang.org/

I'd like TiDB to have something similar, there are may micro benchmarks and the result can be compared by day.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tiancaiamao** [comment]
The performance regression by such kind of changes should be captured by the micro benchmark https://github.com/tikv/client-go/issues/145

**Comment by tiancaiamao** [comment]
And the point get query performance regression like this one https://github.com/pingcap/tidb/issues/25573

**Comment by tiancaiamao** [comment]
I manually run some regression tests and collect the data:


![BenchmarkTableScan](https://user-images.githubusercontent.com/1420062/123641075-6ea39980-d854-11eb-92b4-fa36abe873b7.png)
![BenchmarkStringIndexLookup](https://user-images.githubusercontent.com/1420062/123641078-6fd4c680-d854-11eb-97d9-28c4f32239f5.png)

From this data, I can say apparently there are performance regression from 2021-06-08 to 2021-06-11

![BenchmarkBasic](https://user-images.githubusercontent.com/1420062/123641079-706d5d00-d854-11eb-81dd-0f2a24d023ba.png)

And from 2021-05-21 to 2021-05-26 BenchmarkBasic result become worse.

**Comment by tiancaiamao** [comment]
B.T.W, golang also have a page about  perf https://perf.golang.org/, but I dislike it. It's not visualized.

**Comment by tiancaiamao** [comment]
The data of the last few months is now available here http://www.zenlife.tk:18081/
The final goal is to move it to perf page https://perf.pingcap.com/

**Comment by tiancaiamao** [comment]
Performance regression of BenchmarkInsertIntoSelect

![image](https://user-images.githubusercontent.com/1420062/153810872-99c4a933-4697-4bc6-9648-862aadda48d7.png)

and BenchmarkIntegerIndexLookup

![image](https://user-images.githubusercontent.com/1420062/153810984-81458e7e-7ba8-47a7-994d-8468f4bd957c.png)

**Comment by bb7133** [comment]
> BenchmarkInsertIntoSelect

@tiancaiamao Could you locate the PR/commit that introduces this regression?

**Comment by tiancaiamao** [comment]
> > BenchmarkInsertIntoSelect
> 
> @tiancaiamao Could you locate the PR/commit that introduces this regression?

https://github.com/pingcap/tidb/issues/32604  I create an issue for it. @bb7133
