### ISSUE TITLE
BUG: sql_mode='ANSI_QUOTES' doesn't work

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb#2576]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
SET sql_mode='ANSI_QUOTES';
select * from "mysql"."db";
```

2. What did you expect to see?

sql_mode changes, and support ANSI ``"`` as identifier quote.

3. What did you see instead?

    ERROR 1105 (HY000): line 0 column 21 near "."db"" (total length 26)

**Comment by tiancaiamao** [comment]
Fixed in https://github.com/pingcap/tidb/pull/2754
