### ISSUE TITLE
compatibility issue about tidb_snapshot and mydumper

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#25779]
## General Question

`tidb_snapshot` system variable is introduced to support reading history data. it may affect the transaction characteristic. In MySQL, set transaction characteristic is not permitted within transactions https://dev.mysql.com/doc/refman/8.0/en/set-transaction.html :
```
mysql> START TRANSACTION;
Query OK, 0 rows affected (0.02 sec)

mysql> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
ERROR 1568 (25001): Transaction characteristics can't be changed
while a transaction is in progress
```

before https://github.com/pingcap/tidb/pull/25468, `tidb_sanpshot` can be set in the transaction, that's is not reasonable. at that PR, we unify the behavior of set `tidb_sanpshot` and `set xxx as of timestamp xxx`.But our `mydumper` relies on the old behavior https://github.com/pingcap/mydumper/pull/48. it will cause a compatibility issue about the older version `mydumper` cannot use the latest TiDB. because we no longer release new versions of mydumper.  may we need to make tidb_snapshot compatibility with mydumper?

**Comment by nolouch** [comment]
cc @leoppro

**Comment by xhebox** [comment]
FYI, one line change is enough to revert the changes back.

**Comment by leoppro** [comment]
Yes, to avoid breaking compatibility, I suggest that we roll back this behavior.
