### ISSUE TITLE
syntax .tbl_name is not supported

### ISSUE THREAD

**Issue by andelf** [pingcap/tidb#2578]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
MySQL [mysql]> use mysql;
Database changed
MySQL [mysql]> select * from .db;
ERROR 1105 (HY000): line 0 column 15 near "db" (total length 17)
```

refer: https://dev.mysql.com/doc/refman/5.7/en/identifier-qualifiers.html

**Comment by mccxj** [comment]
This syntax is deprecated as of MySQL 5.7.20 and will be removed in a future version of MySQL.

@coocood

**Comment by coocood** [comment]
@mccxj 
Thanks, we can close it now.
