### ISSUE TITLE
Using existing etcd cluster instead of a new PD cluster

### ISSUE THREAD

**Issue by wegel** [pingcap/tidb#2579]
Hello,

   We're currently looking at TiDB to replace a MySQL cluster, which is orchestrated by etcd. It seems that it would be quite redundant to have both an etcd cluster and a PD cluster running on the hosts. Is there a way fo TiDB to use the existing etcd cluster directly? Thanks.

**Comment by ngaut** [comment]
Sorry, there is no way to do that. Interesting, PD support a separate etcd cluster in the very earlier versions, it's too complex for users to deploy one more component, so we embedded etcd to PD.
