### ISSUE TITLE
The python ponyorm fails with tidb

### ISSUE THREAD

**Issue by catroot** [pingcap/tidb#2580]
pymysql.err.ProgrammingError: (1146, "Table 'information_schema.table_constraints' doesn't exist")

Will the information_schema updated to contain the necessary tables?

These orm uses several tables from information_schema:

```
 cat mysql.py |grep information_schema
        if case_sensitive: sql = 'SELECT table_name FROM information_schema.tables ' \
        else: sql = 'SELECT table_name FROM information_schema.tables ' \
        if case_sensitive: sql = 'SELECT index_name FROM information_schema.statistics ' \
        else: sql = 'SELECT index_name FROM information_schema.statistics ' \
        if case_sensitive: sql = 'SELECT constraint_name FROM information_schema.table_constraints ' \
        else: sql = 'SELECT constraint_name FROM information_schema.table_constraints ' \

```
Only information_schema.table_constraints missed in tidb.

**Comment by ngaut** [comment]
Thank you for your report @catroot 
Looks like we need to add an empty table_constraints. Is that right? @shenli

**Comment by catroot** [comment]
According to [this document](https://dev.mysql.com/doc/refman/5.7/en/table-constraints-table.html) it will be perfect to fill this table with appropriate values.
Because ponyorm uses this data to determine tables relation.

**Comment by shenli** [comment]
@catroot We will add this table into tidb's information_schema.

**Comment by catroot** [comment]
Thank you!
When you are done with this and ponyorm will take a ride over tidb, i'll build my next project on TiDB.
My best wishes to you, team!

**Comment by shenli** [comment]
@catroot Thanks!

**Comment by shenli** [comment]
@catroot Please try the latest master or the latest binary.

**Comment by catroot** [comment]
Great! Ponyorm now creates the tables for my models!
Thank you for operativeness!
