### ISSUE TITLE
proposal: remove TiDB-to-TiDB RPC from tikv client

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#25808]
Now TiDB can access TiDB by RPC to grab some runtime information. It is implemented by defining a store type `TiDB` in the tikv client and all RPCs are served as coprocessor calls.

I think it is a bad idea because:
- As the client of TiKV, accessing TiDB is not quite reasonable.
- The processing flow of accessing TiDB is so different from accessing TiKV or TiFlash that it needs special treatment for TiDB in various places.
- The request for grabbing runtime information is not quite the same as what we usually understand as a coprocessor (DAG push down)
- Need some hack to make it possible for mocktikv/unistore to connect TiDB through network https://github.com/pingcap/tidb/pull/25777

I guess a better way would be for TiDB to start its own gRPC client to access other TiDBs. It looks like a lot of work, so I write down the issue first and would like to hear suggestions.

## mentor

- [crazycs520](https://github.com/crazycs520)

If you have any questions about this issue, you can comment on this issue, we will reply you as soon as possible.

**Comment by tisonkun** [comment]
@crazycs520 from the [v5.2 planning topic](https://internals.tidb.io/t/topic/219) I see you are the owner of this proposal, is that true? If so, could you assign yourself so that we know it is taken?

**Comment by xxchan** [comment]
Can you give an example of TiDB-to-TiDB RPC?

**Comment by disksing** [comment]
Hi @xxchan , you can search `kv.TiDB` and `tikvrpc.TiDB` in tidb source code.

**Comment by xxchan** [comment]
I found there are only these TiDB-to-TiDB RPCs (in `rpcServer`):
- `diagnosticspb.RegisterDiagnosticsServer`: This uses `sysutil.DiagnosticsServer`, and isn't copr.
- `tikvpb.TikvServer`: copr
  - globalkill
  - cluster memtable

**Comment by crazycs520** [comment]
In `client-go`'s view, TiDB is also a storage engine, just like `TiKV` and `TiFlash`, so you can't remove the `TiDB` engine from `client-go`.

**Comment by tisonkun** [comment]
FYI, TiDB implements Coprocessor API in `rpc_server.go`
