### ISSUE TITLE
No data re-balanced when adding new tikv instances

### ISSUE THREAD

**Issue by yuekui2** [pingcap/tidb#2581]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I am testing out TiDB. As described in the doc, I used 6 machines, 1tidb, 3 pd, and 3 tikv. Things work greatly when adding and querying data. I added ~10M number of records into the system. But when I tried to do horizontal scaling by adding 2 more tikv instances, there is no data moving from other tikv instances. I wait several hours and still no data moved. Then I tried to delete a tikv store using pd-ctrl tool, data starts to move to one of the newly added tikv, but the other newly added tikv still gets no data.

For reference, I also tried to add PD and remove it, and things work well. so does adding tidb.

2. What did you expect to see?
After adding 2 more tikv instances, should the system automatically re-balance the data cross all the tikv instances?

3. What did you see instead?
No data being moved to the new tikv instances.

4. What version of Go are you using (`go version`)?
I downloaded the latest binary directly from github.

**Comment by yuekui2** [comment]
Clarify, I use the way of checking the sst files under tikv#/db folder to decide if there is data re-balanced over.

**Comment by siddontang** [comment]
Hi @yuekui2 

PD will balance data to other TiKV when the data size exceeds a threshold. Assume your TiKV's capacity is 500GB, and the default `min-balance-diff-ratio` is 0.01, so you should insert at lease 5GB data, then PD will begin to move the data to the empty TiKV. 

If you want to test balance, you can:

+ Start TiKV with `--capacity` with a little value, like `1GB`. 
+ Change `min-balance-diff-ratio` in PD config file to 0.001 or more less and start PD.
+ Use `pd-ctl` to change `min-balance-diff-ratio` dynamically.

**Comment by ngaut** [comment]
We should add the details to FAQ. @shenli @siddontang

**Comment by yuekui2** [comment]
Just wonder the underlying reason to use such a design choice. Why not just try to evenly distribute data cross all available tikv instances instead, like Cassandra. 

I set min-balance-diff-ratio to a very small value (0.000001) using pd-ctl, and the entire disk is 1TB. Yet, I still did not see the data moved to the empty tikv. NOTE that my previous "force" data moving by deleting a tikv is still ongoing. Could this be the cause? The "force" data moving itself is very slow, the db folder size is about 5GB, <1GB actually moved to another machine after several hours. 

More over, let us say capacity is 10G, ratio is 0.1, and 3 tikv instances with data of 4GB each. After adding a new tikv instance, will it evenly re-balance to ~3GB each?

Thanks.

**Comment by ngaut** [comment]
Yes, it's because of the data moving.
 
The reason of "force" data moving itself is very slow is the limit of PD, which can be configured too. By default it's very slow, because we don't want to make any impact for online transactions.  We will boost the moving and rebalancing speed after RC2. Currently it depends on  https://github.com/pingcap/tikv/pull/1561 

> More over, let us say capacity is 10G, ratio is 0.1, and 3 tikv instances with data of 4GB each. After adding a new tikv instance, will it evenly re-balance to ~3GB each?

Yes

**Comment by siddontang** [comment]
Hi @yuekui2 

You can use `store` in `pd-ctl` to see the current TiKV cluster information. It is more clear than checking the db folder directly. 

For the `min-balance-diff-ratio`, assume we have two TiKV, both capacity is 1TB, one data used size is S1 and the other is S2, if `S1 / 1TB - S2 / 1TB < min-balance-diff-ratio`, PD will consider starting balance, of course, the real balance algorithm is more complex.

**Comment by yuekui2** [comment]
The re-balance did eventually reach, but very very slow, taking >58h for my data set.
2017-02-03 14:03:57.528554864 -0800 PST
id regions
1  3026
4  2936
5  2414
17293  94
3907515  94

2017-02-05 12:43:57.506226421 -0800 PST
id regions
1  1340
4  2400
17293  2643
3907515  2695

**Comment by yuekui2** [comment]
BTW, the data size on the re-balanced instances are between 1.5GB ~ 2GB, based on the info returned by http://xxx:2379/pd/api/v1/stores

**Comment by siddontang** [comment]
The default balance seems slow, and it is strange that why 1 has only 1340 now? @huachaohuang 

@yuekui2  We have been improving the balance, will release a version next week.

**Comment by huachaohuang** [comment]
Because we balance according to storage ratio for now, we should balance the region count.
The next version will remove some restrictions and configurations, and will be more intuitive.

**Comment by coocood** [comment]
fixed by https://github.com/pingcap/pd/pull/506
