### ISSUE TITLE
multi clustered index + partition table, insert ignore... on duplicate key update return wrong result

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#25846]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE `tbl_51` (
  `col_334` mediumint(9) NOT NULL DEFAULT '-3217641',
  `col_335` mediumint(8) unsigned NOT NULL DEFAULT '2002468',
  `col_336` enum('alice','bob','charlie','david') COLLATE utf8_general_ci NOT NULL DEFAULT 'alice',
  PRIMARY KEY (`col_334`,`col_336`,`col_335`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `idx_116` (`col_334`,`col_335`),
  UNIQUE KEY `idx_117` (`col_336`,`col_334`),
  KEY `idx_118` (`col_336`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
PARTITION BY HASH( `col_334` )
PARTITIONS 6;
insert into tbl_51 values(-3112969,3273861,'charlie'),(-3040776,4159759,'charlie');
insert ignore into tbl_51 (col_336) values ( 'alice' ) , ( 'david' ) , ( 'charlie' ) , ( 'charlie' ) , ( 'alice' ) on duplicate key update col_335 = 7685969;

### 2. What did you expect to see? (Required)

mysql> select * from tbl_51;
+----------+---------+---------+
| col_334  | col_335 | col_336 |
+----------+---------+---------+
| -3112969 | 3273861 | charlie |
| -3217641 | 7685969 | alice   |
| -3217641 | 2002468 | charlie |
| -3040776 | 4159759 | charlie |
+----------+---------+---------+

### 3. What did you see instead (Required)

only occur on 5.0 and partition table, master is the same as expect

mysql> select * from tbl_51;
+----------+---------+---------+
| col_334  | col_335 | col_336 |
+----------+---------+---------+
| -3040776 | 4159759 | charlie |
| -3112969 | 3273861 | charlie |
| -3217641 | 7685969 | alice   |
+----------+---------+---------+

### 4. What is your TiDB version? (Required)

Release Version: v5.0.2-42-g18d69e5
Edition: Community
Git Commit Hash: 18d69e521f06d46d9917dec6d5d2e418e2861694
Git Branch: HEAD
UTC Build Time: 2021-06-28 18:22:53
GoVersion: go1.13.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by lysu** [comment]
```
CREATE TABLE `tbl_51` (
  `col_334` mediumint(9) NOT NULL DEFAULT '-3217641',
  `col_335` mediumint(8) unsigned NOT NULL DEFAULT '2002468',
  `col_336` enum('alice','bob','charlie','david') COLLATE utf8_general_ci NOT NULL DEFAULT 'alice',
  PRIMARY KEY (`col_334`,`col_336`,`col_335`) /*T![clustered_index] CLUSTERED */,
  UNIQUE KEY `idx_116` (`col_334`,`col_335`),
  UNIQUE KEY `idx_117` (`col_336`,`col_334`),
  KEY `idx_118` (`col_336`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci
PARTITION BY HASH( `col_334` )
PARTITIONS 6;

insert ignore into tbl_51(col_335, col_336) values(7685969, 'alice'),(2002468, 'bob');
insert ignore into tbl_51(col_335, col_336) values(2002468, 'david') on duplicate key update col_335 = 7685969;
```

```
select * from tbl_51;
```

should be 

```
+----------+---------+---------+
| col_334  | col_335 | col_336 |
+----------+---------+---------+
| -3217641 | 7685969 | alice   |
| -3217641 | 2002468 | bob     |
+----------+---------+---------+
```

but got 

```
+----------+---------+---------+
| col_334  | col_335 | col_336 |
+----------+---------+---------+
| -3217641 | 7685969 | alice   |
+----------+---------+---------+
```

**Comment by cfzjywxk** [comment]
@lysu 
The release-3.0 pick is not merged yet, shall we close this issue?
