### ISSUE TITLE
386 build is broken again.

### ISSUE THREAD

**Issue by luckcolors** [pingcap/tidb#2584]
Hi.
I'm trying to compile TiDB on armhf (armv7) and but build failed.
It seems that in a previous issue #356 the problem was fixed, but it now seems to happen again on these files.

```
# github.com/pingcap/tidb/util/types
../Gopath/src/github.com/pingcap/tidb/util/types/convert.go:205: constant 9223372036854775807 overflows int
../Gopath/src/github.com/pingcap/tidb/util/types/time.go:1759: constant 4294967295 overflows int
../Gopath/src/github.com/pingcap/tidb/util/types/time.go:1766: constant 4294967295 overflows int

```
My go version is 1.7.4.

**Comment by ngaut** [comment]
Thanks for reporting. We don't have any plan to make TiDB work on 386. Could you please send a PR to fix it?

**Comment by luckcolors** [comment]
Ok so with this pull request the databse successfully builds.
Here's the output of my make test.
[test.log.zip](https://github.com/pingcap/tidb/files/752444/test.log.zip)

**Comment by shenli** [comment]
Fixed in https://github.com/pingcap/tidb/pull/2591
