### ISSUE TITLE
Rename `status/help-wanted` to `help wanted`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#25869]
## Enhancement

GitHub supports shows issues with "help wanted" label on the repository (see below) and it is one of [default labels](https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels#about-default-labels) for all repositories. We'd better name it as normal as most developers assume it to be.

![image](https://user-images.githubusercontent.com/18818196/124109379-a3ecf900-da99-11eb-94dc-d09a4827ea9e.png)

... when you click the link, you will be redirected to https://github.com/pingcap/docs-cn/issues?q=label%3A%22help+wanted%22+is%3Aissue+is%3Aopen

**Comment by tisonkun** [comment]
cc @zz-jason @bb7133 @ngaut @c4pt0r

**Comment by bb7133** [comment]
Sounds like a good idea, I've made the change. Thanks!

**Comment by tisonkun** [comment]
@bb7133 Yes. I can see the reflection on org view. Thanks! 

![image](https://user-images.githubusercontent.com/18818196/124229126-b7eb3600-db3f-11eb-915b-8af96b01cda1.png)

closed as resolved.
