### ISSUE TITLE
Support spill HashAgg to disk

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#25882]
### Background
[Feature Request](https://github.com/pingcap/tidb/issues/22611)
At present, HashAgg cannot spill to disk, which means that large joins that use HashAgg use a huge amount of memory and can trigger OOM.

### Plan
- [x] Finish design docs(https://github.com/pingcap/tidb/pull/25792)
- [x] Implement(https://github.com/pingcap/tidb/pull/25714)
- [x] #26187
  - [x] Correctness Test
  - [x] Performance Test

**Comment by tisonkun** [comment]
So what's the different between this issue and #22611? Shall we close that one as superseded by this one? From my perspective they are just the same.

**Comment by tisonkun** [comment]
BTW you can create issues to track subtasks instead of just link PRs since you may have multiple PRs to one topic but exactly one issue for that topic.
