### ISSUE TITLE
Tracking issue for unstable tests

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#25899]
## Timeout test

* [x] #27438 
* [x] #27439 
* [x] #27440 
* [x] #27441 
* [x] #27443 
* [x] #27444 
* [x] #27445 
* [x] #27446 
* [x] #27447 
* [x] #27449 
* [x] #27450
* [x] #27620
* [ ] #28017
* [ ] #28019

## Integration tests

* [x] #27124 

## race

* [x] #27979
* [x] #25003
* [x] #25013
* [x] #25073
* [x] #25189
* [x] #25270
* [x] #25393 
* [x] #25643
* [x] #25691
* [x] #25782
* [x] #25898
* [x] #26539 
* [x] #26538
* [x] #26718 
* [x] #27114
* [x] #27307
* [x] #27473
* [x] #27474 
* [x] #27476
* [x] #27485
* [x] #27821
* [x] #27822
* [x] #27876
* [x] #28318
* [x] #28777
* [x] #29164
* [x] #29721 
* [x] #29726 
* [x] #29727
* [x] #29728
* [x] #29731

## leak

* [x] #25271
* [x] #25392
* [x] #26997
* [x] #26999 
* [x] #27437
* [x] #27475
* [x] #28816

## hang

* [x] #27966
* [x] #25770
* [x] #25894
* [x] #25895
* [x] #26186
* [x] #26458 
* [x] #27410
* [x] #27420

## logical error

* [x] #25584
* [x] #28299

## Timeout
* [x] #26717 

## unknown

* [x] #25010
* [x] #25014
* [x] #25157
* [x] #25187
* [x] #25188
* [x] #25190
* [x] #25269
* [x] #25272
* [x] #25274
* [x] #25395
* [x] #25585
* [x] #25634
* [x] #25589
* [x] #25640
* [x] #25642
* [x] #25690
* [x] #25692
* [x] #25780
* [x] #25781
* [x] #25783
* [x] #25893
* [x] #25896
* [x] #25897
* [x] #26009
* [x] #26018
* [x] #26099
* [x] #26138
* [x] #26185
* [x] #25986
* [x] #15862
* [x] #26235
* [x] #18945
* [x] #26321 
* [ ] #26409
* [ ] #26410
* [x] #24010
* [ ] #24679
* [x] #25458 
* [x] #25783 
* [x] #14931
* [x] #26684 
* [x] #25187
* [x] #23977
* [x] #26796
* [x] #26934
* [x] #22212
* [x] #25122
* [x] #26947
* [x] #26986
* [x] #27115
* [x] #27116
* [x] #27448
* [x] #27651
* [x] #27711
* [x] #27820 
* [x] #27888
* [x] #27889
* [x] #27892
* [x] #28020
* [x] #28049
* [x] #28054
* [x] #28348
* [x] #28349 
* [x] #28350 
* [x] #28351 
* [x] #28553
* [x] #28676
* [ ] #28646
* [x] #29264
* [x] #29283
* [x] #29734
* [x] #29989
* [x] #31590

**Comment by tisonkun** [comment]
@LittleFall thanks for fixing #25584 ! I'd like to know whether or not its cause fits one of entries listed above? Or it seems like a logical errors.

**Comment by LittleFall** [comment]
it's a logical error (of test framework)

**Comment by tisonkun** [comment]
@karuppiah7890 updated. Thank you!

**Comment by karuppiah7890** [comment]
I think we will have to add #28206 to the list

**Comment by feitian124** [comment]
i believe https://github.com/pingcap/tidb/issues/28553 is unstable, please check and add to list.

**Comment by jyz0309** [comment]
We could add #28706  to the list.

**Comment by tisonkun** [comment]
Hi audience of this thread,

I'm going to close this issue as it grows too long and we actually overcome most of the items.

Fighting with test stability should take some time and I'd prefer tag all related issue with `component/test` + `type/bug` instead of such a tracking issue. At least we can bump the tracking issue to a new (clean) one.
