### ISSUE TITLE
Improve pd.Client.GetTS performance.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#2589]
Currently, we only use one PD client connection to get TS.
Requests may be blocked waiting for other requests to be finished.
Switching to gRPC can resolve this issue.

**Comment by shenli** [comment]
When will we switch to grpc?

**Comment by siddontang** [comment]
@disksing has been working for it, we will release this in RC2.

**Comment by tiancaiamao** [comment]
> Switching to gRPC can resolve this issue.

Is this solved now? @coocood

**Comment by tiancaiamao** [comment]
I've done some benchmark in https://github.com/pingcap/pd/pull/653

As far as I know, change to streaming and use moderate batch size can archive the best QPS,
but no performance improvement shows in the real scenario get timestamp in TiDB.
