### ISSUE TITLE
check `tidb_constraint_check_in_place` for insert and update

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#25923]

**Comment by lcwangchao** [comment]
I wonder if we should keep all behaviors some with normal table, for example：

```
create table test.tn (id int unique key);
insert into test.tn values(1);
set tidb_constraint_check_in_place=0;
begin optimistic;
insert into test.tn values(1);
select * from test.tn;
```

It will output:

```
+------+
| id   |
+------+
|    1 |
|    1 |
+------+
2 rows in set (0.01 sec)
```

The purpose of `tidb_constraint_check_in_place` is for improving performance, but it is not necessary for temporary tables because all data is stored in temporary.

**Comment by djshow832** [comment]
It's unnecessary to keep them the same. Temporary tables can just ignore `tidb_constraint_check_in_place`.
