### ISSUE TITLE
Incorrect type inferring of 'now(2)+0'

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#2593]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```sql
select now(2)+0
```

2. What did you expect to see?
The result type should be `DECIMAL`.

3. What did you see instead?
The result type is `BIGINT`.

4. What version of Go are you using (`go version`)?
```
go version go1.7.4 linux/amd64
```

Besides, time functions (with an option fsp arg) like CURTIME also suffer from this issue.

**Comment by shenli** [comment]
@zyguan Thanks!
@coocood @hanfei1991 PTAL

**Comment by shenli** [comment]
@zyguan This is already fixed. Please use the latest master.
