### ISSUE TITLE
do not allow historical read in local temporary tables

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#25938]

**Comment by sylzd** [comment]
It can be closed by #27270.

details are as follows: 
https://github.com/pingcap/tidb/pull/27270/files#diff-ff7af5dbd454cd98c804a32d8049cd73e476ad819042c63dbe690502f915afeeR8905

```go
	for _, query := range queries {
		localSQL := genLocalTemporarySQL(query.sql)
		queries = append(queries, struct{ sql string }{sql: localSQL})
	}
```
and

```go
	tk.MustExec("set @@tidb_snapshot=NOW(6)")
	for _, query := range queries {
		// Will success here for compatibility with some tools like dumping
		rs := tk.MustQuery(query.sql)
		rs.Check(testkit.Rows())
	}
```

**Comment by lcwangchao** [comment]
@sylzd I think we should forbid history read on local temporary table. This behavior is different from global temporary tables which need to be compatible with some tools like dumpling.

**Comment by sylzd** [comment]
Got it~ local temporary tables do not need adapt to dumpling.

**Comment by sylzd** [comment]
> > @sylzd I think we should forbid history read on local temporary table. This behavior is different from global temporary tables which need to be compatible with some tools like dumpling.
> 
> Got it~ local temporary tables do not need adapt to dumpling.

done with #27363
