### ISSUE TITLE
How to make `tidb_mem_quota_query` take effect globally

### ISSUE THREAD

**Issue by zdjkea** [pingcap/tidb#25945]
你好。这边有个工程查询的数据库比较大。所以经常会导致内存溢出，看了官方的说明是执行set @@tidb_mem_quota_query = 10 << 30;  就可以。但是测试下来。这种执行只能是当前会话的。如何在服务器端设置永久有效？

**Comment by tangenta** [comment]
Hi, there is a corresponding option in the configuration file: https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file#mem-quota-query

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
