### ISSUE TITLE
Forbid setting tiflash in local temporary tables

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#25943]

**Comment by sylzd** [comment]
tidb return ddl error as follows, and I think it's resonable.
```
ERROR 8200 (HY000): TiDB doesn't support ALTER TABLE for local temporary table
```

**Comment by lcwangchao** [comment]
> tidb return ddl error as follows, and I think it's resonable.
> 
> ```
> ERROR 8200 (HY000): TiDB doesn't support ALTER TABLE for local temporary table
> ```

I think just adding a test for `alter table xxx set tiflash replica n` is enough
