### ISSUE TITLE
Add cases that local temporary table works well for cte

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#25951]
```
 create temporary table t1 (i int);
 insert into t1 values (5),(4),(1),(2),(3);

# TODO: MySQL: err Error 1137: Can't reopen table: 't1'
 with c1 as (select i from t1), c2 as (select i from c1 where c1.i=2) select i from c1 where i > 3 union  select i from c2;
```

After discussion in #27174 . The above is a bug from mysql's implement, so we need not to follow it.

See:
- https://bugs.mysql.com/bug.php?id=10327 
- https://bugs.mysql.com/bug.php?id=98458

Just keep temporary table works well in cte.

**Comment by djshow832** [comment]
It's a bug in MySQL and we don't need to be compatible with it.
