### ISSUE TITLE
add index row count doesn't match the actual row count

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#25968]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (id bigint key,b int);
split table t by (10),(20),(30);
 insert into t values (0,0),(10,10),(20,20),(30,30);
alter table t add index idx1(b);
admin show ddl jobs;
select count(*) from t;
```

![image](https://user-images.githubusercontent.com/26020263/124440649-68aa3d00-ddad-11eb-8b4c-67cb59d0cf20.png)

### 2. What did you expect to see? (Required)

add index row count match the actual row count.

### 3. What did you see instead (Required)

doesn't match.

### 4. What is your TiDB version? (Required)

```sql
test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.0.2
Edition: Community
Git Commit Hash: dc40a093a0058b95fc859f60d4b84337dbdff9f6
Git Branch: HEAD
UTC Build Time: 2021-07-05 08:12:38
GoVersion: go1.16
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by wjhuang2016** [comment]
```
Region：      [0, 10)   [10, 20),  [20, 30),  [30, ...)
Record:         0,          10,      20,        30
------------------------------------------------
startKey: 0 endKey: 30
addIndex Splited KV range(according to region):
[0: 10],  [10, 20], [20, 30]
  2     +     2      +   2          =   6
```

I found the root cause, but it's not easy to fix it.

**Comment by bb7133** [comment]
Mark the issue as 'enhancement' because the 'add index row' is now an estimation, it is not accurate by design.

**Comment by dcswinner01** [comment]
When will this bug be fixed?
