### ISSUE TITLE
metrics/grafana/tidb.json has the duplicate ID

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#25963]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

[TiDB DDL backfill progress](https://github.com/pingcap/tidb/blob/master/metrics/grafana/tidb.json#L9961
) and [The duration of the transaction](https://github.com/pingcap/tidb/blob/master/metrics/grafana/tidb.json#L3991) have the same id(193) in metrics/grafana/tidb.json. 

This will cause the metrics panel to be overwritten.

### 4. What is your TiDB version? (Required)

Release Version: v5.2.0-alpha-206-gcb06e116c
Edition: Community
Git Commit Hash: cb06e116c1bfb1089c2e1df5072e889a3b7decd3
Git Branch: master

**Comment by jyz0309** [comment]
Have fixed it in #26350 ,PTAL

**Comment by Defined2014** [comment]
fixed by #32581, close this issue.
