### ISSUE TITLE
set config instance return invalid instance 

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#25976]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
> set config 'db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20160' `resource-metering.agent-address`='0.0.0.0:10101';
(1105, 'invalid instance db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20160')
```

### 2. What did you expect to see? (Required)

execute success

### 3. What did you see instead (Required)

failed

### 4. What is your TiDB version? (Required)

```sql
+------+----------------------------------------------------------+----------------------------------------------------------+---------+------------------------------------------+----------------------+--------------------+-----------+
| TYPE | INSTANCE                                                 | STATUS_ADDRESS                                           | VERSION | GIT_HASH                                 | START_TIME           | UPTIME             | SERVER_ID |
+------+----------------------------------------------------------+----------------------------------------------------------+---------+------------------------------------------+----------------------+--------------------+-----------+
| tidb | db-tidb-extra-service.tidb1373933076657430562.svc:4000   | db-tidb-extra-service.tidb1373933076657430562.svc:10080  | 5.0.2   | dc40a093a0058b95fc859f60d4b84337dbdff9f6 | 2021-07-05T05:37:23Z | 6h40m10.504327936s | 0         |
| tidb | db-tidb-0.db-tidb-peer.tidb1373933076657430562.svc:4000  | db-tidb-0.db-tidb-peer.tidb1373933076657430562.svc:10080 | 5.1.0   | 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e | 2021-07-05T10:54:58Z | 1h22m35.504332222s | 0         |
| pd   | db-pd-0.db-pd-peer.tidb1373933076657430562.svc:2379      | db-pd-0.db-pd-peer.tidb1373933076657430562.svc:2379      | 5.1.0   | 8bc9675a923f81f79d8a566e208c8afdcf4ea3f3 | 2021-07-05T10:37:04Z | 1h40m29.504334487s | 0         |
| pd   | db-pd-1.db-pd-peer.tidb1373933076657430562.svc:2379      | db-pd-1.db-pd-peer.tidb1373933076657430562.svc:2379      | 5.1.0   | 8bc9675a923f81f79d8a566e208c8afdcf4ea3f3 | 2021-07-05T10:36:15Z | 1h41m18.504336616s | 0         |
| pd   | db-pd-2.db-pd-peer.tidb1373933076657430562.svc:2379      | db-pd-2.db-pd-peer.tidb1373933076657430562.svc:2379      | 5.1.0   | 8bc9675a923f81f79d8a566e208c8afdcf4ea3f3 | 2021-07-05T10:35:39Z | 1h41m54.504338316s | 0         |
| tikv | db-tikv-0.db-tikv-peer.tidb1373933076657430562.svc:20160 | db-tikv-0.db-tikv-peer.tidb1373933076657430562.svc:20180 | 5.1.0   | 5a2d13fe14a31edee3c98715ac575b1663c0df47 | 2021-07-05T10:54:31Z | 1h23m2.504340839s  | 0         |
| tikv | db-tikv-2.db-tikv-peer.tidb1373933076657430562.svc:20160 | db-tikv-2.db-tikv-peer.tidb1373933076657430562.svc:20180 | 5.1.0   | 5a2d13fe14a31edee3c98715ac575b1663c0df47 | 2021-07-05T10:51:56Z | 1h25m37.504343302s | 0         |
| tikv | db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20160 | db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20180 | 5.1.0   | 5a2d13fe14a31edee3c98715ac575b1663c0df47 | 2021-07-05T10:53:23Z | 1h24m10.50434522s  | 0         |
+------+----------------------------------------------------------+----------------------------------------------------------+---------+------------------------------------------+----------------------+--------------------+-----------+
```

**Comment by Hatho86** [comment]
I found this issue on ovio.org and would love to contribute! [add other relevant info about you]

**Comment by Hatho86** [comment]
Reference in new issue

**Comment by Hatho86** [comment]
Reference in new issue

**Comment by hatho286** [comment]
> ## Bug Report
> 
> Please answer these questions before submitting your issue. Thanks!
> 
> ### 1. Minimal reproduce step (Required)
> 
> ```
> > set config 'db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20160' `resource-metering.agent-address`='0.0.0.0:10101';
> (1105, 'invalid instance db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20160')
> ```
> 
> 
> 
> ### 2. What did you expect to see? (Required)
> 
> execute success
> 
> ### 3. What did you see instead (Required)
> 
> failed
> 
> ### 4. What is your TiDB version? (Required)
> 
> 
> 
> ```sql
> +------+----------------------------------------------------------+----------------------------------------------------------+---------+------------------------------------------+----------------------+--------------------+-----------+
> | TYPE | INSTANCE                                                 | STATUS_ADDRESS                                           | VERSION | GIT_HASH                                 | START_TIME           | UPTIME             | SERVER_ID |
> +------+----------------------------------------------------------+----------------------------------------------------------+---------+------------------------------------------+----------------------+--------------------+-----------+
> | tidb | db-tidb-extra-service.tidb1373933076657430562.svc:4000   | db-tidb-extra-service.tidb1373933076657430562.svc:10080  | 5.0.2   | dc40a093a0058b95fc859f60d4b84337dbdff9f6 | 2021-07-05T05:37:23Z | 6h40m10.504327936s | 0         |
> | tidb | db-tidb-0.db-tidb-peer.tidb1373933076657430562.svc:4000  | db-tidb-0.db-tidb-peer.tidb1373933076657430562.svc:10080 | 5.1.0   | 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e | 2021-07-05T10:54:58Z | 1h22m35.504332222s | 0         |
> | pd   | db-pd-0.db-pd-peer.tidb1373933076657430562.svc:2379      | db-pd-0.db-pd-peer.tidb1373933076657430562.svc:2379      | 5.1.0   | 8bc9675a923f81f79d8a566e208c8afdcf4ea3f3 | 2021-07-05T10:37:04Z | 1h40m29.504334487s | 0         |
> | pd   | db-pd-1.db-pd-peer.tidb1373933076657430562.svc:2379      | db-pd-1.db-pd-peer.tidb1373933076657430562.svc:2379      | 5.1.0   | 8bc9675a923f81f79d8a566e208c8afdcf4ea3f3 | 2021-07-05T10:36:15Z | 1h41m18.504336616s | 0         |
> | pd   | db-pd-2.db-pd-peer.tidb1373933076657430562.svc:2379      | db-pd-2.db-pd-peer.tidb1373933076657430562.svc:2379      | 5.1.0   | 8bc9675a923f81f79d8a566e208c8afdcf4ea3f3 | 2021-07-05T10:35:39Z | 1h41m54.504338316s | 0         |
> | tikv | db-tikv-0.db-tikv-peer.tidb1373933076657430562.svc:20160 | db-tikv-0.db-tikv-peer.tidb1373933076657430562.svc:20180 | 5.1.0   | 5a2d13fe14a31edee3c98715ac575b1663c0df47 | 2021-07-05T10:54:31Z | 1h23m2.504340839s  | 0         |
> | tikv | db-tikv-2.db-tikv-peer.tidb1373933076657430562.svc:20160 | db-tikv-2.db-tikv-peer.tidb1373933076657430562.svc:20180 | 5.1.0   | 5a2d13fe14a31edee3c98715ac575b1663c0df47 | 2021-07-05T10:51:56Z | 1h25m37.504343302s | 0         |
> | tikv | db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20160 | db-tikv-1.db-tikv-peer.tidb1373933076657430562.svc:20180 | 5.1.0   | 5a2d13fe14a31edee3c98715ac575b1663c0df47 | 2021-07-05T10:53:23Z | 1h24m10.50434522s  | 0         |
> +------+----------------------------------------------------------+----------------------------------------------------------+---------+------------------------------------------+----------------------+--------------------+-----------+
> ```
> 
>

**Comment by Sampriti-Mitra** [comment]
@crazycs520 can I take this?

**Comment by morgo** [comment]
I think this might have been fixed, so best to re-check :-) There was a problem where only IP addresses were accepted, but it now accepts any resolvable hostname.
