### ISSUE TITLE
ALTER MODIFY statement support

### ISSUE THREAD

**Issue by catroot** [pingcap/tidb#2598]
Another dip on my way with TiDB:
```ALTER TABLE authors MODIFY name varchar(100) NULL```
TiDB says:
`[ddl:203]unsupported modify column`

Thus, i can't modify fields?

And another one:

```
ALTER TABLE payments ALTER date_applied DROP DEFAULT;
```
TiDB reports error:
line 1 column 7 near " `date_applied` DROP DEFAULT" (total length 62)

**Comment by coocood** [comment]
@catroot 
Thank you for your report.

Those two DDL statements can be supported soon.
But for modifing the length of a varchar column, we can only support increasing the length.

**Comment by catroot** [comment]
If it's totally impossible to shrink the lenght of varchar, pls report back 0 altered, instead of rising exception.
Better to log info about unsupported shrinking for varchars.

**Comment by coocood** [comment]
@catroot 
Thank you for your advice.

I think returning error is the right behavior for the not supported feature.
MySQL also returns an error when there is data longer than the specified length.

The error message should be more specific, we will improve that.

**Comment by catroot** [comment]
Returning error will broke things in orm, that relies on mysql features, and mysql can shrink varchar fields. So this error will raise some unexpected and unhandled errors in orm.

**Comment by coocood** [comment]
@catroot 
We hope we can support those DDL operations too, but if the DDL operation requires checking every row in the table, it would be difficult to implement.

So my sugguestion is that during development phase, schema changes frequently, you can just use MySQL, when schema is settled down, you can switch to TiDB seamlessly.

**Comment by catroot** [comment]
Project lifetime usually requires updates and improvements, Schema must not be static.
Often schema changes requires not only checking every row, but in case of indexed column it requires rebuid all column indexes. If you talking about difficulties for iterating rows in db, pls tell me, what db is for? This is base db feature - to iterate rows, filter them and aggregate their data. There must be no problem with this at all. 
A db with static schema is not the one i'm looking for. It's much better to find the way to apply schema changes at petabyte db in a piece of second.

**Comment by coocood** [comment]
@catroot 

Currently, we only support online DDL change, when you add a column or index, the table is not locked, can still be written and read.

The difficulty is that when we are checking every row in the table, new rows may be inserted, which may exceed the new length.

We do have the plan to support it, but not in the next few months, but when more users asking for this feature, we will put it on a higher priority.

**Comment by catroot** [comment]
The solution is to use information_schema as information about the schema.
Since column altered - schema will contain new lenght and new inserts must meet this property.
We don't need to achieve goal for every row contain data strongly limited to the schema, operating with part of data defined in schema is enought. Later, on resharding, optimizing or other write operations data will be shrinked according to the schema, no need to enforce this at the ALTER level. IMHO.

**Comment by coocood** [comment]
@catroot 
When ALTER TABLE returns successfully, users will expect all rows in the table have the limited length, returning a row longer than the limit may result in more serious errors.

One way to solve the problem is that we can truncate the column value when reading it.

But this can be only applied when strict SQL mode is not set.

In strict SQL mode, every row must be less than the new length or the DDL fails.

**Comment by catroot** [comment]
If db truncates fileds according to the schema lenght - no one can select something longer than schema defines.
Thus, with truncating even in strict SQL mode lenght will always meet.
Bad way to give away untruncated data. Bad way to store untruncated data.
Thus, speed improvement can be achieved with this way. No need to digg all data to truncate them at their place. This can be a very expensive job. This job can be left to the optimize or repair table query.

**Comment by coocood** [comment]
@catroot 
According to MySQL docuement
```
This conversion may result in alteration of data. For example, if you shorten a string column, values may be truncated. To prevent the operation from succeeding if conversions to the new data type would result in loss of data, enable strict SQL mode before using ALTER TABLE (see Section 6.1.8, “Server SQL Modes”).
```

Strict SQL mode is used to prevent alteration of data, so checking every row is required.

**Comment by catroot** [comment]
In case of preventing truncation of data - agree.

**Comment by zimulala** [comment]
> Those two DDL statements can be supported soon.

We support it now, you can try the latest master code. @catroot

**Comment by catroot** [comment]
Binary distribution doesn't contain this fix yet? Or this is something different one?
```
ALTER TABLE `payment_type` MODIFY `name` varchar(100) NULL
[ddl:203]unsupported modify column
```

**Comment by shenli** [comment]
@catroot Could you show me the result of `tidb-server -V` ?

**Comment by catroot** [comment]
./tidb-server -V
Git Commit Hash: 96e8ab6128ad4f2a9b936290d975936f18851e0f
UTC Build Time:  2017-02-13 06:10:08

**Comment by zimulala** [comment]
> Those two DDL statements can be supported soon.
> But for modifying the length of a varchar column, we can only support increasing the length.
Are sure your case is in line with the second point?

**Comment by catroot** [comment]
I suppose this restriction will be for strict sql mode.
For my case the field lenght equals.
SQL restrictions are default:
`STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION`

**Comment by zimulala** [comment]
@catroot  Could you show me the statement of `Create table`?

**Comment by catroot** [comment]
```
CREATE TABLE `payment_type` (
	`id` INT(11) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(100) NOT NULL,
	`provider_label` VARCHAR(100) NOT NULL,
	`descr` VARCHAR(100) NOT NULL,
	PRIMARY KEY (`id`)
);
```

**Comment by zimulala** [comment]
@catroot  Please make sure that the process you are using is the latest binary process. 
BTW, the `drop default` statement should be `ALTER TABLE `payment_type` ALTER column `name` DROP DEFAULT;`

**Comment by catroot** [comment]
Yes, with the 'column' statement DROP DEFAULT works. 
But, according to [this document](https://dev.mysql.com/doc/refman/5.7/en/alter-table.html) the 'column' statement is not mandatory and can be ommited, and orms often omits unnesessary statements.

**Comment by zimulala** [comment]
Yep, we will support the field of `column` optional soon.
This statement of `ALTER TABLE payment_type DROP COLUMN name CASCADE` is not supported yet.

**Comment by catroot** [comment]
Does it mean that `DROP COLUMN name CASCADE` will not be supported in the near future?

**Comment by zimulala** [comment]
Yes. @catroot

**Comment by catroot** [comment]
Sad. @zimulala

**Comment by zimulala** [comment]
We support the field of `column` optional now, you can try the latest master code. @catroot

**Comment by catroot** [comment]
Thank you!
Let me know when `DROP COLUMN name CASCADE` will be supported.
This will let the project to be a little closer to open the door for the django community.
I believe this will be a important milestone for the project. 
I mean elimination of incomatibles with the django orm and migration tools.

**Comment by zimulala** [comment]
OK, no problem. Thank you for your feedback. @catroot
