### ISSUE TITLE
Add default value checking when `create table`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#2600]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
create table t (b int not null default '' ) ;

2. What did you expect to see?
ERROR 1067 (42000): Invalid default value for 'b'

3. What did you see instead?
Query OK, 0 rows affected (0.00 sec)

**Comment by coocood** [comment]
Make sure to force use strict mode to check default value in DDL.
