### ISSUE TITLE
Tracking issue for restructure tests

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26022]
## Brief Motivation

This issue tracks the efforts to restructure TiDB tests, focusing on unit tests and integration tests, especially on separating `integration_test.go` as well as unifying test infrastructure in [testify](https://github.com/stretchr/testify).

For the detailed design, see also:

* [x] #26023

## Join force

We are currently on the first phase on the effort and focus on migrating tests to testify. If you want to participant the movement, you can directly comment under any open issues below without assignee to require assignment.

You can take a look at https://github.com/pingcap/tidb/pull/26375 as an example to do the migration.

## Note

**Before writing code, please take a look at PRs merged already and keep consistent code style.**

* parallel
  * As mentioned in #30692, we decided to run all tests in serial.
  * ~Keep test cases as parallel as possible.~
  * ~When some test cases should be run in serial, take use of go testing subtests (`t.Run(name string, f func(t *T))`) and parallel the parent test only. In this way, test cases in the same subtests set run in serial.~
  * ~https://github.com/pingcap/tidb/issues/26022#issuecomment-891656074~
  * ~When test cases should be run in serial at top level, move them into `xxx_serial_test.go` file.~
* Avoid using suite of testify as discussed https://github.com/pingcap/tidb/pull/26082#issuecomment-877230972 and https://github.com/pingcap/tidb/issues/27178#issuecomment-921842586
* Make use of testify checkers when the original code writes plain go testing cases.
* `c.Assert` is almost `require.Xxx`

## Migration

* [x] #26025
* [x] #27177
* [x] #27178
* [x] #27844
* [x] #27179
* [x] #27180
* [x] #26156
* [x] #26306
* [x] #26155
* [x] #26081
* [x] #26854
* [x] #26855
* [x] #28319
* [x] #26436
* [x] #26100
* [x] #26740
* [x] #26741
* [x] #26742
* [x] #26743
* [x] #28887
* [x] #26856
* [x] #26857
* [x] #26858
* [x] #26860
* [x] #26861
* [x] #26862
* [x] #26744
* [x] #26745
* [x] #26746
* [x] #26863
* [x] #26864
* [x] #27140
* [x] #27141
* [x] #27142
* [x] #27874
* [x] #33461
* [x] #33462
* [x] #33463
* [x] #27143
* [x] #27139
* [x] #26865
* [x] #26866
* [x] #26867
* [x] #26537
* [x] #26747
* [x] #26374
* [x] #26521
* [x] #33453

## Kits

* [x] #26106
* [x] #26107
* [x] #26108
* [x] #26289

## Reference

* testify suffers from parallelizing tests in suite https://github.com/stretchr/testify/issues/187

**Comment by jyz0309** [comment]
A little question, if we use testify to instead `pingcap/check`, maybe we need to restructure the `/utils/testkit` first? It seem that we use `TestKit.MustExec` to exec sql in TiDB test, and MustExec need to use `pingcap/check`.

**Comment by tisonkun** [comment]
@jyz0309 Yes of course. That is in the plan and we will create testkit with go testing & testify. We use go-check for matchers almost and it won't be too complex.

**Comment by tisonkun** [comment]
@july2993 BTW #26102 & #26103 are still free to be assigned. If you want to take one of them, feel free to comment there.

**Comment by tisonkun** [comment]
In an offline discussion with @tiancaiamao it seems we'd better consider test timeout in this effort also.

gocheck provides a `check.timeout` mechanism but the current state seems unsatisfied (why?). golang itself doesn't provides timeout per function.

After a little investigation, I write a helper for this requirement

```go
func RunWithTimeout(t *testing.T, d time.Duration, f func(*testing.T)) {
	timeout := time.After(d)
	done := make(chan bool)
	go func() {
		defer func() {
			done <- true
		}()
		f(t)
	}()
	select {
	case <-timeout:
		t.Fatalf("timeout: %s", d.String())
	case <-done:
	}
}
```

... which is used as

```go
func TestName(t *testing.T) {
	testkit.RunWithTimeout(t, 1 * time.Second, func(t *testing.T) {
		require.Equal(t, 2, 2)
		time.Sleep(2 * time.Second)
	})
}
```

.. one more level of ident but works well.

However, @tiancaiamao means the original issue is that a panic from a previous test cause the whole test hang. I don't know what does it mean, since a main goroutine panic will fail the test immediately.

**Comment by tiancaiamao** [comment]
> the original issue is that a panic from a previous test cause the whole test hang. I don't know what does it mean

It's a problem of gocheck, it spawn new goroutines to run the test cases, so a panic does not make the process exit immediately. @tisonkun

**Comment by PragmaTwice** [comment]
Hi @tisonkun, I'd like to migrate some tests under `utils` pkg, is there any task still free to assign?

**Comment by tisonkun** [comment]
@PragmaTwice most of `util/xxx` are free to assign, you may just jump to subtasks listed above.

**Comment by beyoung** [comment]
Hi @tisonkun ,I'd like to migrate util/plancodec pkg , which is not listed above, please create a subtask and assign to me . Thx.

**Comment by tisonkun** [comment]
> Hi @tisonkun ,I'd like to migrate util/plancodec pkg , which is not listed above, please create a subtask and assign to me . Thx.

Aha! That's it. Let me create one for you.

**Comment by tisonkun** [comment]
> @tisonkun It seems failpoints conflict with each others. Let me batch domain_test to run in serial.
> @xhebox failpoints and global config are both serial-safe, maybe mention it in the tracking issue.

https://github.com/pingcap/tidb/pull/26752

**Comment by tisonkun** [comment]
Hi, audience of this thread.

I'd like to share you an under reviewing dev guide section [Write and Run Unit Tests](https://github.com/pingcap/tidb-dev-guide/pull/75). It collects best practices found in this effort and hopefully we guide every developer how to write unit tests in idiom and run tests by yourself.

**Comment by feitian124** [comment]
not sure how many works left, but i write a [migrate-helper](https://github.com/feitian124/migrate-helper) to make this work easier.
welcome to have a try.

**Comment by jiaxiang521** [comment]
Hi @tisonkun, I'd like to migrate tests under `tablecodec` pkg. Please create a subtask and assign to me.

**Comment by tisonkun** [comment]
@jiaxiang521 you can comment `/assign` under #26867

**Comment by maxshuang** [comment]
@tisonkun  I found all this migration tests replace the testleak with goleak directly.  Would it cause some false-positive problems?

like when we use testleak, we will ignore some stack functions as follows:
```
func interestingGoroutines() (gs []string) {
         buf := make([]byte, 2<<20). 
         buf = buf[:runtime.Stack(buf, true)]. 
         ignoreList := []string{. 
                 "created by github.com/pingcap/tidb.init",  
                 "testing.RunTests",  
                 "check.(*resultTracker).start",  
                 "check.(*suiteRunner).runFunc",  
         ...
  ```

but when we use goleak, in options.go, it only ignore follow stacks by default:
```
 teststack/syscallstack/stdlibstack/tracestack
```

**Comment by tisonkun** [comment]
@maxshuang yes the result is not just the same. But I don't regard it as false-positive since we now have fine-grand control for leaks. Previously testleak ignore too much patterns which cause a larger whitelist than required.

**Comment by w169q169** [comment]
migrate  is a litter tired(always rewrite code line by line),  so I write [migrate-tools](https://github.com/w169q169/migrate-tools) (similar to  [migrate-helper](https://github.com/feitian124/migrate-helper) but use ast to rewrite)to reduce some work.
support rule is shown on the below.

welcome to try it(any idea or suggestion is ok),  I hope the tool could be useful for everyone and help make migrate work more easily.

**Comment by tisonkun** [comment]
@w169q169 https://github.com/pingcap/tidb/issues/26022#issuecomment-898806106 yes you guys can always write tools :)

Just a reminder: manually check before sending a PR, I've seen some bad/corner case where the tools don't cover. Please avoid letting reviewers fix the tools short-coming.

**Comment by maxshuang** [comment]
I had written a simple script using sed to do some duplicated work😁, ref
to ticdc_script <https://github.com/maxshuang/ticdc_script>.

**Comment by w169q169** [comment]
@tisonkun  You idea is same as me, tools could do easy work and more complex work need be checked manually .
Review is always necessary,  bad/corner cases that I dont know such as [`c.Check(len(bindData.Bindings), Equals, 0)`](https://github.com/pingcap/tidb/pull/28070#discussion_r709685254) and [`c.Assert(err, IsNil)`](https://github.com/pingcap/tidb/pull/28070#discussion_r709685398), I have added feature to fix the tools .
![image](https://user-images.githubusercontent.com/12460574/134278589-90941b61-5c7b-4ab9-962b-179ed40cd23b.png)

**Comment by tisonkun** [comment]
As mentioned in #30692, we decided to run all tests in serial.

Thanks to @tangenta for driving the decision and I've updated the description in this issue. Thanks for all of your participants.

**Comment by dveeden** [comment]
@tisonkun I assume https://pingcap.github.io/tidb-dev-guide/get-started/write-and-run-unit-tests.html#parallel needs updating? Should that section be replaced by an explanation about why we want to run things in serial? or keep it?

**Comment by tisonkun** [comment]
So...

As #33296 got merged, we have new subtasks to resolve.

**Comment by tisonkun** [comment]
Closed as all subtasks resolved. Thanks for everyone help in this thread!
