### ISSUE TITLE
Tracking issue for heuristic rules enhancement for index selection

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#26020]
## Enhancement

This issue tracks the status of the heuristic rules used for index selection to pruning some indexes by rule. This can help TiDB avoid choosing some wrong indexes by the out-date/not-good statistics.

* [x] #27227
* [x] #26319
* [x] #26320
* [x] #27228
* [x] #27229
* [x] Scenario tests if needed (No need)
* [x] #27230

Follow ups:

* [x] #27313

**Comment by tisonkun** [comment]
Hello @winoros ! We published a planning for TiDB v5.2 development cycle. Is this feature to be included? If so, would you mind to comment on the [thread](https://internals.tidb.io/t/topic/219) so that the author can update information?

**Comment by tisonkun** [comment]
@xuyifangreeneyes @winoros do we briefly describe todo items or draft a proposal? What heuristic rules we'd like to implement? Is there a framework already or we will introduce a framework at first.

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes @winoros do we briefly describe todo items or draft a proposal? What heuristic rules we'd like to implement? Is there a framework already or we will introduce a framework at first.

Here is a [design doc](https://docs.google.com/document/d/1pzm6LV7jbPK2oPCMFe-iEUXu7Jf7R5cvaSq9Lgo-a1U/edit?usp=sharing).

**Comment by tisonkun** [comment]
@xuyifangreeneyes can we make a proposal follow [design doc process](https://github.com/pingcap/tidb/blob/master/docs/design/README.md)?

**Comment by tisonkun** [comment]
Also this document is private that cannot be accessed.

**Comment by xuyifangreeneyes** [comment]
> Also this document is private that cannot be accessed.

sorry, check the link: https://docs.google.com/document/d/1pzm6LV7jbPK2oPCMFe-iEUXu7Jf7R5cvaSq9Lgo-a1U/edit?usp=sharing

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes can we make a proposal follow [design doc process](https://github.com/pingcap/tidb/blob/master/docs/design/README.md)?

Sure, I will write one.

**Comment by tisonkun** [comment]
@xuyifangreeneyes is there any schedule to push a design document? At least I think @winoros or you can create a subtask for it now.

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes is there any schedule to push a design document? At least I think @winoros or you can create a subtask for it now.

@tisonkun I write a design document https://github.com/pingcap/tidb/pull/27223. I doesn't have the access to modify the tracking issue. Maybe @winoros or you can update the tracking issue? The untracked PR list as following:
- Design doc for rule based index selection: https://github.com/pingcap/tidb/pull/27223
- Add test for always-good heuristics: https://github.com/pingcap/tidb/pull/26917
- Output skyline pruning information when executing EXPLAIN: https://github.com/pingcap/tidb/pull/26748
- Docs-cn update for rule based index selection: https://github.com/pingcap/docs-cn/pull/6815
- Refine prefer-range-scan behavior: https://github.com/pingcap/tidb/pull/27123

**Comment by tisonkun** [comment]
@xuyifangreeneyes thanks for your information. Updated.

**Comment by tisonkun** [comment]
@xuyifangreeneyes please check whether we can close this issue as all tasks done.

**Comment by xuyifangreeneyes** [comment]
> @xuyifangreeneyes please check whether we can close this issue as all tasks done.

There is another open pr https://github.com/pingcap/tidb/pull/27527 related to skyline pruning. IMHO we can close the issue after the pr is merged.

**Comment by tisonkun** [comment]
@xuyifangreeneyes thanks! Updated the information on issue description. I do think @github should enable contributors to associate/create subtasks >_<

**Comment by tisonkun** [comment]
Closed as #27527 merged.
