### ISSUE TITLE
About any user can select the cluster-* tables of information schema 

### ISSUE THREAD

**Issue by it2911** [pingcap/tidb#26044]
## Bug Report

Any user can get the TiDB cluster information by select information_schema.cluster_info table. It is problem to cluster security.

### 1. Minimal reproduce step (Required)

The user who only have least privilage can read the information of TiDB cluster.

Example
select * from CLUSTER_HARDWARE;

### 2. What did you expect to see? (Required)

Don't allow any user can read the cluster info else who have purview. Only root user can read this info is the best.

### 4. What is your TiDB version? (Required)

5.1

**Comment by bb7133** [comment]
At least for now, this is by-design. The 'security enhanced mode' is used for your requirement: https://github.com/pingcap/tidb/blob/master/docs/design/2021-03-09-security-enhanced-mode.md

**Comment by djshow832** [comment]
This is under development. Some are finished. Refer to https://github.com/pingcap/tidb/issues/26120

**Comment by tisonkun** [comment]
Duplicate of #26120
