### ISSUE TITLE
tidb using unix socket cannot restart if after SIGKILL

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#26058]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```bash
shell1> ./bin/tidb-server -socket /tmp/tidb.sock
shell2> pkill -SIGKILL tidb-server
shell1> ./bin/tidb-server -socket /tmp/tidb.sock
```

### 2. What did you expect to see? (Required)
Success / tidb-server started again

### 3. What did you see instead (Required)
FATAL error, server not started
```
[2021/07/08 11:23:10.190 +02:00] [FATAL] [main.go:626] ["failed to create the server"] [error="listen unix /tmp/tidb.sock: bind: address already in use"] [stack="main.createServer\n\t/repos/tidb/tidb-server/main.go:626\nmain.main\n\t/repos/tidb/tidb-server/main.go:190\nruntime.main\n\t/usr/lib/go-1.16/src/runtime/proc.go:225"] [stack="main.createServer\n\t/repos/tidb/tidb-server/main.go:626\nmain.main\n\t/repos/tidb/tidb-server/main.go:190\nruntime.main\n\t/usr/lib/go-1.16/src/runtime/proc.go:225"]
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.2.0-alpha-227-g14adc4625
Edition: Community
Git Commit Hash: 14adc46253e4c47b15798b143dcd4055440c5915
Git Branch: master
UTC Build Time: 2021-07-08 09:22:04
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by mjonss** [comment]
The reason is that `kill -9` does not execute any cleanups etc, leaving the socket file and it cannot be opened next time. MySQL seems to solve this by also having a lock file with the process id of the creator of the socket file, and if the socket file and lock file exists when the server is starting, it reads the lock file and checks if the process id is still matching a running process and if not it will remove the socket file and recreate it and update the lock file.

**Comment by dveeden** [comment]
If there is nothing listening on that socket the entry from `/proc/net/unix` for it should be gone.

**Comment by dveeden** [comment]
```go
package main

import (
	"bufio"
	"fmt"
	"os"
	"strings"
)

func main() {
	fmt.Println("vim-go")

	f, _ := os.Open("/proc/net/unix")

	scan := bufio.NewScanner(f)
	for scan.Scan() {
		p := strings.Fields(scan.Text())
		if len(p) > 7 {
			fmt.Printf("Listening UNIX socket: %s\n", p[7])
		}
	}
}
```

**Comment by dveeden** [comment]
https://pkg.go.dev/github.com/prometheus/procfs can be used as an abstraction layer if needed

**Comment by mjonss** [comment]
Will it work on all linux systems? It seems like it there are no `/proc` on macOS :(

**Comment by dveeden** [comment]
yes that works on all linux systems

**Comment by bb7133** [comment]
@aytrack I do not think it is a major bug, PTAL
