### ISSUE TITLE
run make check on arm64 machines always failed

### ISSUE THREAD

**Issue by purelind** [pingcap/tidb#26074]
### 1. Minimal reproduce step (Required)
* run 'make check' on an arm64 machine always failed. Error message as follows:
`` Generate errors.toml failed: exit status 1, output:
_errdoc-generator/main.go:17:15: expected 'STRING', found '.'
``

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
`` Generate errors.toml failed: exit status 1, output:
_errdoc-generator/main.go:17:15: expected 'STRING', found '.'
``
More info please see [this](https://ci.pingcap.net/blue/organizations/jenkins/tidb_nightly_test_arm64/detail/master/50/pipeline/)
### 4. What is your TiDB version? (Required)
Branch master

**Comment by zhouqiang-cl** [comment]
log is https://ci.pingcap.net/blue/organizations/jenkins/tidb_nightly_test_arm64/detail/master/50/pipeline/

**Comment by bb7133** [comment]
Close this issue since it cannot be reproduced on the existing ARM64 node.
