### ISSUE TITLE
Always push down TopN when N is less than a specific variable

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#26089]
## Enhancement
Currently, in the planner, the choice between push down TopN or not is cost-based. But sometimes the cost calculation is not accurate enough to make the correct choice. When we choose not to push down TopN when it should, the SQL execution will become very slow sometimes. Considering the risk and benefit, always choose to push down the TopN may be a better strategy.

**Comment by qw4990** [comment]
Please see https://github.com/pingcap/tidb/pull/26550 for more details
