### ISSUE TITLE
Improve row count estimation for Limit/TopN

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#26088]
## Enhancement
Currently, when doing row count estimation for the index/table scan in a SQL with LIMIT, we'll adjust the row count according to the LIMIT number and the correlation from statistics. This is a good strategy but sometimes it makes the planner choose `TableScan` when it should choose `IndexScan`, and the SQL execution becomes very slow. We'll try to fix it.

**Comment by qw4990** [comment]
Please see https://github.com/pingcap/tidb/pull/26445 for more examples and details.
