### ISSUE TITLE
詢問如何單純部署tidb

### ISSUE THREAD

**Issue by chabater** [pingcap/tidb#26092]
我透過tiup的方式部署tidb集群使用，使用起來覺得非常合適使用，有研究網站上也有kubernetes的部屬方式，為了取得各自的優勢，我想部署幾個tidb的container到kubernetes上，並且共用我目前的pd,tikv,tiflash，請問你們是否可以單獨部署tidb container並設定自定義的集群設定呢？

**Comment by tisonkun** [comment]
Hi @chabater ! Thanks for your question on TiDB. We host a forum for answering user questions in Chinese. You can refer to https://asktug.com/c/administration and report the question there.

Closing as redirected...
