### ISSUE TITLE
Implement testkits for server tests

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26108]

**Comment by jyz0309** [comment]
Does this mean that we need to re-implement a TestKit and let it gradually replace `utils/testkit`? Or just make changes to the original `testkit`?
A little concern, now testkit is used by many test. If we make changes to the original testkit directly, this is a big change.

**Comment by tisonkun** [comment]
[x] re-implement a TestKit and let it gradually replace utils/testkit

> That is in the plan and we will create testkit with go testing & testify. We use go-check for matchers almost and it won't be too complex.

**_We use go-check for matchers ( in testkit ) almost and it won't be too complex._**

**Comment by tisonkun** [comment]
Fixed by a series of PR referred above. With  https://github.com/pingcap/tidb/pull/26712 merged, what we have to do is only migrating tests and add few methods of Result or TestKit on demand.

Closing...
