### ISSUE TITLE
migrate test-infra to testify for `util/admin` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26102]

**Comment by evilbinary** [comment]
Hi @tisonkun, I'd like to migrate tests under `util/admin` pkg. Please create a subtask and assign to me.

**Comment by tisonkun** [comment]
/assign @evilbinary 

Glad to see your interest @evilbinary ! That is the subtask and I will assign it to you.

**Comment by jyz0309** [comment]
Hello~ @evilbinary 
I see the `admin_integration_test.go` have used a lot of `testKit.MustExec()`. And we have not implemented another `testkit` yet. So I think you can migrate test-infra to testify for `admin_test.go` first.
What do you think? @tisonkun

**Comment by tisonkun** [comment]
Yep. That makes sense. Besides, we shall make the first migration of `testkit.TestKit` example asap :P
