### ISSUE TITLE
migrate test-infra to testify for `util/arena` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26103]

**Comment by tisonkun** [comment]
@Ranxy do you want to take this issue? You can comment `/assign` to assign the issue to you. Please assign the issue to you first and then start working.

**Comment by Ranxy** [comment]
@tisonkun Thank you for the reminder.

**Comment by tisonkun** [comment]
@Ranxy thanks for your contribution! You can figure out other package doesn't migrate and ask for a subtask in the tracking issue #26022 . Also you can put an eye on the logic covered by tests to see whether there is potential improvement.
