### ISSUE TITLE
migrate test-infra to testify for `util/logutil` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26154]

**Comment by tisonkun** [comment]
Assignee may take a look at https://github.com/pingcap/log/pull/16 and see how to make log tests

**Comment by ofey404** [comment]
Hi @tisonkun, I'd like to migrate tests under `util/logutil` pkg. Please create a subtask and assign to me ;)

Cloned [pingcap/log#16](https://github.com/pingcap/log/pull/16), I think I understand how log test works now XD

**Comment by tisonkun** [comment]
/assign @ofey404 

Thanks for taking this issue. Go ahead!

**Comment by tisonkun** [comment]
@ofey404 before writing code, you are suggested to take a look at PR merged already and keep consistent code style.
