### ISSUE TITLE
migrate test-infra to testify for `util/checksum` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26169]

**Comment by Ranxy** [comment]
Hi @tisonkun, I'd like to migrate this pkg. Please assign it to me.

**Comment by tisonkun** [comment]
/assign @Ranxy 

Go ahead!

**Comment by Ranxy** [comment]
@tisonkun There is a lot of copy and paste in the test code, should we refactor this?

**Comment by tisonkun** [comment]
@Ranxy Yes that makes sense to me. You may also give a descriptive name for "TestTiCase3648" and others.
