### ISSUE TITLE
migrate test-infra to testify for `util/dbterror` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26174]

**Comment by Fedomn** [comment]
Hi @tisonkun, I'd like to migrate tests under `util/dbterror` pkg. Please create a subtask and assign to me.

**Comment by tisonkun** [comment]
/assign @Fedomn 

Go ahead! BTW this is the dedicated subtask for `util/dbterror`. In the tracking issue I mentioned

> Also you can directly comment under any open issues below without assignee to require assignment.

... this is the case.

**Comment by Fedomn** [comment]
okay, thanks for your reminder
