### ISSUE TITLE
migrate test-infra to testify for `util/chunk` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26170]

**Comment by xxchan** [comment]
- [ ] https://github.com/pingcap/tidb/pull/26772
- [ ] https://github.com/pingcap/tidb/pull/27026
- [ ] https://github.com/pingcap/tidb/pull/27028

**Comment by tisonkun** [comment]
@xxchan Thanks for working on this issue! Nice work.
