### ISSUE TITLE
migrate test-infra to testify for `util/filesort` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26178]

**Comment by kevgeo** [comment]
Hi @tisonkun,  I'd like to migrate tests under util/filesort pkg.

**Comment by tisonkun** [comment]
@kevgeo Thanks for your interest! Go ahead. It seems you just assign yourself, that's great. Welcome to ask anything if you found stuck.

**Comment by kevgeo** [comment]
Hi @tisonkun, I have one doubt.
I have written a dummy program to check equivalent 'require' statements for 'assert' and have replaced all the assert statements .

How do we actually run the main_test.go file and verify the changes in filesort_test.go?

**Comment by tisonkun** [comment]
@kevgeo 

For running from CLI, see also [this page](https://golang.org/doc/tutorial/add-a-test).

For running from GoLand, see also [this page](https://www.jetbrains.com/help/go/performing-tests.html#run-tests-from-the-context-menu).

You remind me to finished our development guide with [Write and Run Unit test](https://pingcap.github.io/tidb-dev-guide/get-started/write-and-run-unit-tests.html) : P
