### ISSUE TITLE
migrate test-infra to testify for `util/kvcache` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26182]

**Comment by tisonkun** [comment]
@yeyypp it seems @jyz0309 assigned himself days ago. You may first ping @jyz0309 to see whether it is already started.

**Comment by tisonkun** [comment]
... and wait for a while said a week or half.

**Comment by jyz0309** [comment]
@yeyypp Hello, I am sorry that I have no time to do this issue recently, if you want to do it, welcome~ And if you have any questions, just ask me~
