### ISSUE TITLE
consider using pkg/errors instead juju/errors

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#2622]
Now we use juju errors and use `errors.Wrap` to wrap the error for later getting error stack. It is not convenient because we have to use `errors.Wrap` in every error return. 

Most of the time, we just want to know the error stack, so  it is better to use pkg/errors instead. We can use "%+v" to get the error stack and no need to wrap error when return every time. 

Refer https://github.com/pkg/errors

**Comment by zhexuany** [comment]
@siddontang Any updates about this proposal? 

I created a PR about error handling several day ago. I believe it is will be better if we finish error handling and then do the improvement. Currently, some math operation does not return error code correctly i.e `select pow(10, 700)`. We need investigate this.
