### ISSUE TITLE
how to improve unit tests pass rate

### ISSUE THREAD

**Issue by hey-hoho** [pingcap/tidb#26236]
## General Question

I downloaded the TiDB v4.0.11 source code, then run all unit tests by `go test ./... -v --cover `,this is test result summary:
```
OOPS: 0 passed, 1 FAILED, 1 FIXTURE-PANICKED, 12 MISSED
OOPS: 254 passed, 15 FAILED
OOPS: 4 passed, 5 FAILED
OOPS: 14 passed, 1 FAILED
OOPS: 26 passed, 6 FAILED, 4 PANICKED
OOPS: 531 passed, 1 skipped, 6 FAILED
OOPS: 25 passed, 3 FAILED
OOPS: 2 passed, 1 FAILED
OOPS: 6 passed, 2 FAILED
OOPS: 85 passed, 4 FAILED, 1 PANICKED
OOPS: 186 passed, 1 skipped, 9 FAILED
OOPS: 47 passed, 1 skipped, 1 FAILED
OOPS: 134 passed, 12 FAILED
OOPS: 17 passed, 4 FAILED
```
Many cases are failed. I think the number of failures is a bit high.
How to ensure that all unit tests can run and pass?

My test environment:

- 4Core CPU 20G memory 

``` shell
[root@localhost ~]# cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)

[root@localhost ~]# go version
go version go1.13.5 linux/amd64
```

**Comment by zhouqiang-cl** [comment]
Thank you @hey-hoho 
 Maybe you can try `-parallel 2` and post more log here

**Comment by tisonkun** [comment]
Hi @hey-hoho, thanks for reporting this issue.

TiDB uses [failpoint](https://github.com/pingcap/failpoint) for tests. You can refer to [Makefile](https://github.com/pingcap/tidb/blob/ed659df5e3b4389648ba94d1fa5c2209ce5ea062/Makefile) to see how to run tests.

Generally you can run `make test` for running tests. I created an issue https://github.com/pingcap/tidb-dev-guide/issues/51 to include how to run tests in our dev guide.

**Comment by hey-hoho** [comment]
@zhouqiang-cl @tisonkun Thanks for your suggestions, I will try it now.

**Comment by hey-hoho** [comment]
@tisonkun I use `make test`, all tests have passed. 👍
