### ISSUE TITLE
limit the time of a single unit test case

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#26289]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some of the test case panic may cause the whole testing programming hang:

https://github.com/pingcap/tidb/issues/26186

Find out which test cause the problem case by case is time consuming, and we have already met this issue several times.

**Describe the feature you'd like:**

It's better to limit the time a single test case can run (maybe 3min) so we don't wait so long and find the program hang after 10mins.

And also I'd like the testing framework to handle the panic case, and exit in as soon as possible.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tiancaiamao** [comment]
As PR https://github.com/pingcap/tidb/pull/26546 shows, if we limit the time of single unit test case, we can also make our CI much faster. And it can prevent the CI slow again.

**Comment by tisonkun** [comment]
cherry-pick the demo fixture from #26022 , keep hacking..

```go
func RunWithTimeout(t *testing.T, d time.Duration, f func(*testing.T)) {
	timeout := time.After(d)
	done := make(chan bool)
	go func() {
		defer func() {
			done <- true
		}()
		f(t)
	}()
	select {
	case <-timeout:
		t.Fatalf("timeout: %s", d.String())
	case <-done:
	}
}
```

... which is used as

```go
func TestName(t *testing.T) {
	testkit.RunWithTimeout(t, 1 * time.Second, func(t *testing.T) {
		require.Equal(t, 2, 2)
		time.Sleep(2 * time.Second)
	})
}
```

**Comment by tisonkun** [comment]
Hi @tiancaiamao , given that we have method to require duration on single test, do you still want to implement a time limiter and enable it on some tests? If so, you can comment those tests and we can start using our fixture from there.

**Comment by tiancaiamao** [comment]
> Hi @tiancaiamao , given that we have method to require duration on single test as in #26578, do you still want to implement a time limiter and enable it on some tests? If so, you can comment those tests and we can start using our fixture from there.

There are actually two things we need to solve:
1. Prevent the test case run too long to slow down the CI
2. Make it easier to find out which panic cause the whole unit test hang

We could have modify the testing framework, to solve both 1 and 2 at the same time.

Now #26578 implement 1, by some simple and dirty script instead of hacking the testing framework.

2 is not solved yet, but after we refactoring all the tests, it will be done because the standard Go test exit on the first panic.
It's OK to close this one, I believe 2 will be resolved eventually.
