### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jmuyuyang** [pingcap/tidb#263]
when I select a database not exists 

2015/09/24 15:24:38 tidb.go:89: [debug] compiling use mysqls
2015/09/24 15:24:38 session.go:242: [warning] session:{
  "currDBName": "",
  "sid": 3
}, err:Database not exist
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x30 pc=0x4a0986]

goroutine 22 [running]:
github.com/pingcap/tidb/tidb-server/server.(*clientConn).Close(0xc820112160, 0x0, 0x0)
	/data/go/golib/src/github.com/pingcap/tidb/tidb-server/server/conn.go:110 +0xd6
github.com/pingcap/tidb/tidb-server/server.(*clientConn).readHandshakeResponse(0xc820112160, 0x0, 0x0)
	/data/go/golib/src/github.com/pingcap/tidb/tidb-server/server/conn.go:193 +0x527
github.com/pingcap/tidb/tidb-server/server.(*clientConn).handshake(0xc820112160, 0x0, 0x0)
	/data/go/golib/src/github.com/pingcap/tidb/tidb-server/server/conn.go:84 +0x9d
github.com/pingcap/tidb/tidb-server/server.(*Server).onConn(0xc82000bb00, 0x7ffe01f19d38, 0xc82002a030)
	/data/go/golib/src/github.com/pingcap/tidb/tidb-server/server/server.go:141 +0x199
created by github.com/pingcap/tidb/tidb-server/server.(*Server).Run
	/data/go/golib/src/github.com/pingcap/tidb/tidb-server/server/server.go:120 +0x203

**Comment by shenli** [comment]
@jmuyuyang Thanks for your feedback!
Could u please provide more details?
1. What MySQL client you are using? MySQL official client or others?
2. What's your SQL statement?"use mysqls;"?
3. What's the TiDB version? It is shown as `Git Commit Hash` when tidb-server start.

**Comment by jmuyuyang** [comment]
hello
1,the golang environment is 1.5.1 version,tidb-server version is the newest master branch
2,use php mysql pdo client
```
$config = array("username" => 'root',"password" => "");
$dsn = "mysql:dbname=mysqls;host=127.0.0.1;port=3006";
$pdo = new PDO($dsn, $config['username'], $config['password'], array(
                 PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES utf8"
));
```

**Comment by shenli** [comment]
@jmuyuyang Thanks for your reply.
We have fix this bug. You can try this branch: shenli/fix-issue-263. We will merge it to master later today.

One more thing, I notice that there is an unexists database in your dsn named "mysqls". Is it a typo?

**Comment by jmuyuyang** [comment]
@shenli dsn named "mysqls" is my test case 
thanks,i notice that you have fix this bug

**Comment by shenli** [comment]
@jmuyuyang 
Thanks again for your report! Please keep eyes on TiDB.
