### ISSUE TITLE
can we open github dependabot feature to keep use latest dependency

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tidb#26316]
## General Question

github lanched a very nice feature than can keep our go.mod is always up-to-date

mode details: https://github.blog/2020-06-01-keep-all-your-packaages-up-to-date-with-dependabot/

and i think is make our cdebase more robust, maybe we can turn this feature on?

**Comment by dveeden** [comment]
There is a typo in the URL. The correct one is https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/

**Comment by dveeden** [comment]
https://github.com/pingcap/tidb/issues/26983 seems related

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
