### ISSUE TITLE
Support Encryption and Compression Functions

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#2632]
**List of Functions**
- [x] AES_DECRYPT()	Decrypt using AES
- [x] AES_ENCRYPT()	Encrypt using AES
- [x] COMPRESS()	Return result as a binary string
- [x] DECODE()	Decodes a string encrypted using ENCODE()
- [x] ENCODE()	Encode a string
- [x] MD5()	Calculate MD5 checksum
- [x] PASSWORD() (deprecated 5.7.6)	Calculate and return a password string
- [x] RANDOM_BYTES()	Return a random byte vector
- [x] SHA1(), SHA()	Calculate an SHA-1 160-bit checksum
- [x] SHA2()	Calculate an SHA-2 checksum
- [x] UNCOMPRESS()	Uncompress a string compressed
- [x] UNCOMPRESSED_LENGTH()	Return the length of a string before compression
- [ ] VALIDATE_PASSWORD_STRENGTH()	Determine strength of password #9741

*Removed in MySQL 8.0, will not add:*

- DES_DECRYPT() (deprecated 5.7.6)	Decrypt a string 
- DES_ENCRYPT() (deprecated 5.7.6)	Encrypt a string 
- OLD_PASSWORD()	Return the value of the pre-4.1 implementation of PASSWORD
- ENCRYPT() (deprecated 5.7.6)	Encrypt a string https://github.com/pingcap/tidb/issues/4025 

*MySQL [Enterprise Edition functions](https://dev.mysql.com/doc/refman/5.7/en/enterprise-encryption-functions.html), not required to add:*

- ASYMMETRIC_DECRYPT()	Decrypt ciphertext using private or public key
- ASYMMETRIC_DERIVE()	Derive symmetric key from asymmetric keys
- ASYMMETRIC_ENCRYPT()	Encrypt cleartext using private or public key
- ASYMMETRIC_SIGN()	Generate signature from digest
- ASYMMETRIC_VERIFY()	Verify that signature matches digest
- CREATE_ASYMMETRIC_PRIV_KEY()	Create private key
- CREATE_ASYMMETRIC_PUB_KEY()	Create public key
- CREATE_DH_PARAMETERS()	Generate shared DH secret
- CREATE_DIGEST()	Generate digest from string

**Comment by morgo** [comment]
There is a separate issue open for password validation, so I am going to close this now. Everything else has been implemented.
