### ISSUE TITLE
Wrong warning for Out-of-Range and Overflow Handling

### ISSUE THREAD

**Issue by b41sh** [pingcap/tidb#26361]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE t1 (i1 TINYINT, i2 TINYINT UNSIGNED);
SET sql_mode = '';
INSERT INTO t1 (i1, i2) VALUES(256, 256);
```
### 2. What did you expect to see? (Required)
```
mysql> show warnings;
+---------+------+---------------------------------------------+
| Level   | Code | Message                                     |
+---------+------+---------------------------------------------+
| Warning | 1264 | Out of range value for column 'i1' at row 1 |
| Warning | 1264 | Out of range value for column 'i2' at row 1 |
+---------+------+---------------------------------------------+
2 rows in set (0.00 sec)
```
### 3. What did you see instead (Required)
```
mysql> show warnings;
+---------+------+--------------------------------+
| Level   | Code | Message                        |
+---------+------+--------------------------------+
| Warning | 1690 | constant 256 overflows tinyint |
| Warning | 1690 | constant 256 overflows tinyint |
+---------+------+--------------------------------+
2 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta-6176-g8e5dd485e
Edition: Community
Git Commit Hash: 8e5dd485e7ad0d1f70eef449d77e73735973f794
Git Branch: master
UTC Build Time: 2021-07-19 15:57:10
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)
```

**Comment by hihihuhu** [comment]
hi @tisonkun, can i take this issue as my first task? thanks!

**Comment by tisonkun** [comment]
@hihihuhu thanks for taking over this issue. If you don't have a PR yet, I'd suggest you comment your idea to fix this first.

**Comment by Sampriti-Mitra** [comment]
@tisonkun  is this still open?

**Comment by tisonkun** [comment]
@Sampriti-Mitra Yes. You can just verify as shown on the description.

**Comment by jebter** [comment]
`TiDB root@127.0.0.1:test> CREATE TABLE t1 (i1 TINYINT, i2 TINYINT UNSIGNED);
Query OK, 0 rows affected
Time: 0.076s
TiDB root@127.0.0.1:test> SET sql_mode = '';
Query OK, 0 rows affected
Time: 0.000s
TiDB root@127.0.0.1:test> INSERT INTO t1 (i1, i2) VALUES(256, 256);
Query OK, 1 row affected
Time: 0.003s
TiDB root@127.0.0.1:test> show warnings;
+---------+------+---------------------------------------------+
| Level   | Code | Message                                     |
+---------+------+---------------------------------------------+
| Warning | 1264 | Out of range value for column 'i1' at row 1 |
| Warning | 1264 | Out of range value for column 'i2' at row 1 |
+---------+------+---------------------------------------------+

2 rows in set
Time: 0.003s
TiDB root@127.0.0.1:test> select tidb_version() \G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v8.1.0
Edition: Community
Git Commit Hash: 945d07c5d5c7a1ae212f6013adfb187f2de24b23
Git Branch: HEAD
UTC Build Time: 2024-05-21 03:52:40
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

1 row in set
Time: 0.001s`
Please try the latest version. I will close it,if there are any updates, you can reopen it.
