### ISSUE TITLE
optimize query statements summary table by avoid decode plan by conditional pushdown

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#26379]
## Background

PR https://github.com/pingcap/tidb/pull/25843 enlarge the `tidb_stmt_summary_max_stmt_count` default value to 3000. It's great for diagnose problem since the `statements_summary ` can record more SQL. But it will also slow down the performance when query `statements_summary`. Mostly the reasons affecting performance is cause by `DecodePlan` for each row in `statements_summary`.

https://github.com/pingcap/tidb/pull/25892 already has optimized the performance by prune column. But it doesn't optimize for the following SQL which will be used in [tidb-dashboard](https://github.com/pingcap/tidb-dashboard): 

```sql
select * 
from `STATEMENTS_SUMMARY` 
where 
    digest='8019af26debae8aa7642c501dbc43212417b3fb14e6aec779f709976b7e521be' 
    and 
    unix_timestamp(summary_begin_time) = 1626769800;
```

The upper SQL need query all columns value, so https://github.com/pingcap/tidb/pull/25892 which use prune column method can't optimize it.

But we can use `conditional pushdown` to do optimization. As you can see the condition is `digest='8019af26debae8aa7642c501dbc43212417b3fb14e6aec779f709976b7e521be'  and   unix_timestamp(summary_begin_time) = 1626769800`. Mostly There is very little data that meets this condition, so we can use `conditional pushdown` to only fetch the row which meets the condition.

## Reference

How to do conditional pushdown for query system table?

- You can use `MemTablePredicateExtractor` to implements conditional pushdown.

You can reference the following PR which also do conditional pushdown for query system table:

- https://github.com/pingcap/tidb/pull/18092
- https://github.com/pingcap/tidb/pull/14840

##  mentor

-  [crazycs520](https://github.com/crazycs520)

If you have any questions about this issue, you can comment on this issue, I will reply you as soon as possible.

**Comment by TszKitLo40** [comment]
Can I try this issue? @crazycs520
