### ISSUE TITLE
Can I know the trace information of SQL that I have run in the past?

### ISSUE THREAD

**Issue by irisyou55** [pingcap/tidb#26387]
## Performance Questions
It seems that the trace command can only let me know the current running status of a certain SQL, can I get the trace of the SQL that I have run in the past?

**Comment by ljluestc** [comment]
There are other ways to collect and analyze historical SQL query information in TiDB:

Slow Query Log (SQL Audit): TiDB supports the Slow Query Log, which can be enabled to log queries that take longer than a configured threshold to execute. This log can provide valuable information about historical slow queries, including their execution time, query plans, and other details. You can configure the Slow Query Log using the slow_query configuration options in the TiDB configuration file.

Query Performance Monitoring Tools: There are third-party monitoring tools and solutions that can be integrated with TiDB to capture and analyze historical query performance. These tools can provide more advanced and in-depth insights into the performance of past SQL queries.

Profiling Tools: You can use profiling tools like "pt-query-digest" from the Percona Toolkit to analyze the slow query log and extract valuable performance statistics and insights from historical SQL queries.

Performance Schema (Experimental): TiDB supports the MySQL Performance Schema (PFS), which can be enabled to collect detailed performance-related data. However, as of my knowledge cutoff, the support for PFS in TiDB was experimental and not fully featured

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
