### ISSUE TITLE
backoffer.maxSleep 10000ms is exceeded, errors: stale_epoch:<> 

### ISSUE THREAD

**Issue by simingli** [pingcap/tidb#2638]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
start tidb server 

2. What did you expect to see?

3. What did you see instead?

2017/02/14 16:01:13 domain.go:289: [error] [ddl] reload schema in loop err /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:186: backoffer.maxSleep 10000ms is exceeded, errors:
stale_epoch:<> 
not leader: region_id:2 , ctx: region_id:2 region_epoch:<conf_ver:2 version:1 > peer:<id:3 store_id:1 > 
stale_epoch:<> 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:186: [try again later]
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/store/tikv/snapshot.go:204: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/store/tikv/snapshot.go:176: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/structure/string.go:40: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/structure/string.go:47: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/domain/domain.go:59: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/domain/domain.go:263: 

4. What version of Go are you using (`go version`)?
not use go

**Comment by shenli** [comment]
@simingli Thanks for your feedback!
It seems that tidb-server could not get data from tikv-server. Could you show us your tikv-server's log?

**Comment by simingli** [comment]
tikv-server log:

2017/02/14 16:13:35.097 raft.rs:879: [INFO] [region 2] 3 is starting a new election at term 68
2017/02/14 16:13:35.097 raft.rs:666: [INFO] [region 2] 3 became candidate at term 69
2017/02/14 16:13:35.097 raft.rs:752: [INFO] [region 2] 3 received MsgRequestVoteResponse from 3 at term 69
2017/02/14 16:13:35.098 raft.rs:732: [INFO] [region 2] 3 [logterm: 6, index: 34] sent MsgRequestVote request to 6 at term 69
2017/02/14 16:13:35.098 server.rs:480: [INFO] resolve store 5 address ok, addr 10.2.1.103:20160
2017/02/14 16:13:35.099 server.rs:179: [WARN] remove store connection for store 5 with token Token(1190)
2017/02/14 16:13:49.937 raft.rs:879: [INFO] [region 2] 3 is starting a new election at term 69
2017/02/14 16:13:49.937 raft.rs:666: [INFO] [region 2] 3 became candidate at term 70
2017/02/14 16:13:49.937 raft.rs:752: [INFO] [region 2] 3 received MsgRequestVoteResponse from 3 at term 70
2017/02/14 16:13:49.937 raft.rs:732: [INFO] [region 2] 3 [logterm: 6, index: 34] sent MsgRequestVote request to 6 at term 70
2017/02/14 16:13:49.939 server.rs:480: [INFO] resolve store 5 address ok, addr 10.2.1.103:20160
2017/02/14 16:13:49.939 server.rs:179: [WARN] remove store connection for store 5 with token Token(1191)

**Comment by shenli** [comment]
@siddontang @BusyJay PTAL

**Comment by shenli** [comment]
@simingli How many tikv-server instance do you deployed? It seems that there is something wrong with the instance on 10.2.1.103. Could your show me the logs of this instance?

**Comment by simingli** [comment]
@shenli I have 3 tikv-servier.  10.2.1.101, 10.2.1.102. 10.2.103.  Error is on 101.

103 log:(time is wrong)

2017/02/15 00:25:50.490 tikv-server.rs:667: [INFO] Start listening on 10.2.1.103:20160...
2017/02/15 00:25:50.491 mod.rs:193: [INFO] starting working thread: end-point-worker
2017/02/15 00:25:50.492 mod.rs:193: [INFO] starting working thread: snap-handler
2017/02/15 00:25:50.492 server.rs:153: [INFO] TiKV is ready to serve
2017/02/15 00:35:50.489 compact.rs:84: [INFO] compact range for cf lock finished
2017/02/15 00:45:50.488 compact.rs:84: [INFO] compact range for cf lock finished
2017/02/15 00:55:50.489 compact.rs:84: [INFO] compact range for cf lock finished

**Comment by siddontang** [comment]
Hi @simingli 

Does `2017/02/14 16:13:49.939 server.rs:179: [WARN] remove store connection for store` occur too many times?

**Comment by shenli** [comment]
@simingli It seems that the tikv on 10.2.1.101 could not contact with the tikv on 10.2.1.102. It may be related with firewall. Could you shutdown your firewall or check the rules?

**Comment by simingli** [comment]
@siddontang yes

**Comment by simingli** [comment]
@shenli 10.2.1.101 can ping 102,103 success.

**Comment by siddontang** [comment]
Using `telenet 10.2.1.103 20160` can work? 

Do you start the TiKV on 10.2.1.103?

**Comment by shenli** [comment]
@simingli But the firewall may prevent incoming packet on port 20160. So we suggest shutdown firewall or add rules into iptables.
Please try @siddontang 's command.

**Comment by simingli** [comment]
@shenli @siddontang OK, Let me try.

**Comment by simingli** [comment]
@shenli @siddontang thanks very much. The 103 firewall is running. When I closed it. Tidb is Work.

**Comment by shenli** [comment]
@simingli Cool! 
You could find some useful information [here]( https://github.com/pingcap/docs/blob/master/trouble-shooting.md#tidb-cluster-troubleshooting-guide) when you meet any problem.
