### ISSUE TITLE
alter-primary-key is deprecated in doc but actually it's still visible and modifiable in v5.1.0

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tidb#26405]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- This doc said alter-primary-key was deprecated: https://docs.pingcap.com/tidb/stable/tidb-configuration-file,
 but it still visible and modifiable in v5.1.0, which  is confused to users. 

- Please make sure alter-primary-key is unavailable for users if it has been deprecated.

### 4. What is your TiDB version? (Required)

v5.1.0

**Comment by tangenta** [comment]
"Deprecated" means it will be removed in the future.

Do you mean `show config` should annotate the deprecated options with "(deprecated)"?

**Comment by tangenta** [comment]
You can reopen this issue if there is a further question.
