### ISSUE TITLE
migrate test-infra to testify for `util/ranger` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26411]

**Comment by feitian124** [comment]
i am migrating `util/ranger` which depends on `util/testkit` and `util/testutil`
i see you re-implemented a TestKit and let it gradually replace utils/testkit in #26108 , how about `util/testutil`? 
and does not find a tracker  for `util/testutil` in #26022

**Comment by tisonkun** [comment]
`util/testutil` is going to be dropped. You may move functions to `testkit/` or if the function used in few places which means uncommon, inline it.

**Comment by feitian124** [comment]
found 518 usage of `util/testutil` in whole repo.
i am afraid we have to use similiar manner like `util/testkit`: re-implemented `util/testutil` in `testkit/` and let it gradually replace the old one
