### ISSUE TITLE
migrate test-infra to testify for `util/sem` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26416]

**Comment by PragmaTwice** [comment]
Hi @tisonkun, I'd like to migrate this pkg. Please assign it to me.
Just a first try, maybe more pkg could be assign to me after this.

**Comment by tisonkun** [comment]
/assign @PragmaTwice 

Go ahead!

**Comment by tisonkun** [comment]
Yes. `util` contains utilities whose functionality is simple and thus its tests are simple. We will face major challenges when it's up to `executor`, `ddl`, `planner`, and so on.
