### ISSUE TITLE
Drop local temporary table is not atomic

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#26456]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Prepare
```
set @@tidb_enable_noop_functions=1;
create temporary table taa (id int);
drop table taa, tnexist;
```

The drop clause will fail here because table tnexist not exist. And then execute sql:

```
select * from taa;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from taa;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from taa;
ERROR 1146 (42S02): Table 'test.taa' doesn't exist
```

### 4. What is your TiDB version? (Required)

master

**Comment by bb7133** [comment]
I don't think this is a bug, actually, we didn't make `DROP TABLE` atomic for the consideration of the compatibility of MySQL 5.7. This script in the issue can be reproduced in MySQL 5.7 but not MySQL 8.

And it is not only related to 'temporary table', you can see that the 'DROP' for multiple physical tables is not atomic either.

I think it's better to:
- Hold the PR #26464 until we decide to be compatible with MySQL 8 in the future
- Or, merge #26464 and then try to make `DROP TABLE` atomic for all tables(to be compatible with MySQL 8 now).

PTAL @Howie59 , @lcwangchao , @morgo , @aytrack , @zimulala .

**Comment by morgo** [comment]
I prefer 'make DROP TABLE atomic for all'. The fact that MySQL 5.7 is not atomic is not really a feature that we need to strive for compatibility with. When there are discrepancies between 5.7 and 8.0 behavior we have usually been picking the 8.0 behavior for quite a while too.

**Comment by bb7133** [comment]
Sure, let's do that.
