### ISSUE TITLE
Is it possible to support something like changefeeds in RethinkDB?

### ISSUE THREAD

**Issue by gonotes** [pingcap/tidb#2645]
It is important for some apps monitor database's change to implement something linke Pub/Sub.
Is it possible to support something like changefeeds in RethinkDB for TiDB? Or does something already exist?
Thank you.

**Comment by morgo** [comment]
It is not as convenient, but it is possible to get a feed of changes through the TiDB binlog:
https://www.pingcap.com/docs/tools/tidb-binlog-cluster/

**Comment by zz-jason** [comment]
Maybe https://github.com/pingcap/ticdc is what you need.

**Comment by zz-jason** [comment]
I'm going to close this feature request. Please feel free to reopen it if `ticdc` can not fulfill your application requirements.
