### ISSUE TITLE
tidb 4.0.13 Non root users in tidb database cannot change their own password

### ISSUE THREAD

**Issue by Araon-Li** [pingcap/tidb#26512]
tidb version:v4.0.13

Non root users in tidb database cannot change their own passwords. In the tidb
![passswod](https://user-images.githubusercontent.com/83341022/126760314-df9b3a46-01e7-407e-b28e-0e2e57119ae3.jpg)
 version 5.0, non root users can change their own passwords.

The SQL statements used are as follows:

set password for xxx=password('123')

Errors are reported as follows:

ERROR 1044 (42000) Access denied for user ''@'' to database 'mysql'

alter user xxx identified by '123'

ERROR 1227 (42000) Access denied; you need (at least one of) the CREATE USER privilege(s)...

**Comment by aytrack** [comment]
Hi, could you provide the details of the TiDB version, I can't set the password for a nonroot user it's self.
tidb 5.0(f5bf404c50e463fdb67b932), v5.0.3, v5.0.0
```sql
mysql> set password for 'u1'=password('aaa');
ERROR 1044 (42000): Access denied for user ''@'' to database 'mysql'
mysql> set password for 'u1'@'%'=password('aaa');
ERROR 1044 (42000): Access denied for user ''@'' to database 'mysql'
mysql> alter user 'u1'@'%' identified by 'aaa';
ERROR 1227 (42000): Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation
mysql> select tidb_version();
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                         |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.0.3-9-gf5bf404c5
Edition: Community
Git Commit Hash: f5bf404c50e463fdb67b932baeb1cc9d82eb08e5
Git Branch: release-5.0
UTC Build Time: 2021-07-23 10:07:55
GoVersion: go1.16.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

but the MySQL  8.0 could set the password.
mysql 8.0.23
```sql
mysql> alter user 'u1'@'%' identified by 'abc';
Query OK, 0 rows affected (0.05 sec)

mysql> show grants;
+--------------------------------+
| Grants for u1@%                |
+--------------------------------+
| GRANT USAGE ON *.* TO `u1`@`%` |
+--------------------------------+
1 row in set (0.04 sec)
```

**Comment by Araon-Li** [comment]
my tidb version is v5.1.0

**Comment by Araon-Li** [comment]
[tidb@TiDB ~]$ mysql -u jack -P 4000 -h 192.168.10.143 -ptidb
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 7
Server version: 5.7.25-TiDB-v5.1.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Copyright (c) 2000, 2020, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.1.0
Edition: Community
Git Commit Hash: 8acd5c88471cb7b4d4c4a8ed73b4d53d6833f13e
Git Branch: heads/refs/tags/v5.1.0
UTC Build Time: 2021-06-24 07:10:32
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> alter user 'jack'@'192.168.10.143' identified by 'pingcap';
Query OK, 0 rows affected (0.02 sec)

mysql>

**Comment by Defined2014** [comment]
I think no update plan for v4.x right now. So close this issue firstly.
