### ISSUE TITLE
Support SHOW PLACEMENT

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#26582]
This is a sub-task of Placement Rules in SQL: #18030

This requires the following subtasks:

* [x] Parser: `SHOW PLACEMENT LIKE 'x';
* [x] Parser: Add `SHOW PLACEMENT FOR [{DATABASE | SCHEMA} schema_name] [TABLE table_name] [PARTITION partition_name]`
* [ ] `SHOW PLACEMENT LIKE` should return a list of `PLACEMENT POLICIES` that have been loaded in the TiDB server.
  - #27531
* [ ] `SHOW PLACEMENT FOR` should summarize the placement rules of the object that has been specified. It will need to query PD to show the current scheduling state. See the "SHOW PLACEMENT" section of the syntax RFC.
* [ ] Privileges for `SHOW PLACEMENT` and `SHOW PLACEMENT FOR`

**Comment by lcwangchao** [comment]
Parser finished with pr: 

- https://github.com/pingcap/parser/pull/1292

**Comment by morgo** [comment]
I have moved the tasks of this sub-issue to https://github.com/pingcap/tidb/issues/18030

This was a suggestion to make it easier to see what tasks are unassigned. It makes sense to me, so I am going to close this issue.
