### ISSUE TITLE
PASS: fail_test.go:64: testSuite.TestFailNewSession	5.448s @zimulala

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#26624]

**Comment by lysu** [comment]
I have no idea how to improve it, and maybe move to some to other slow task CI?, original author @zimulala  PTAL~

**Comment by tiancaiamao** [comment]
And another problems is ... this test seems to run twice

**Comment by lysu** [comment]
this package has two`func TestT(t *testing.T) `, maybe remove one of them can avoid this.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
