### ISSUE TITLE
How  to set  statement timeout  on SpringBoot + Mybatis

### ISSUE THREAD

**Issue by nieshoujun** [pingcap/tidb#26628]
## General Question
if we   use  mybatis   select  
some  sql  use  about  30S ,so   how to  set  a timeout  
if  > 5s  so  return timeout exception

**Comment by ljluestc** [comment]
Doesn't look like related at all. Would you mind sharing mybatis-config.xml or something similar?

**Comment by jebter** [comment]
I will close this issue. If there are any updates, you can reopen it.
