### ISSUE TITLE
Why the pessimistic locks were executed many times within an update statement

### ISSUE THREAD

**Issue by irisyou55** [pingcap/tidb#26667]
## Bug Report
I have deployed [minitrace](https://github.com/pingcap/tidb/pull/19557)  to my tidb cluster. It is indeed a useful tool. However, after I ran the tpcc workload, I checked the trace information.I was surprised to find that some update statements contain multiple records of pessimistic locks that look very similar. I don’t know why.

![image](https://user-images.githubusercontent.com/45091006/127158180-85d5a870-7750-42d5-a6ba-bc7b8ed0a4be.png)
![image](https://user-images.githubusercontent.com/45091006/127158222-ed340ceb-b288-4aa1-816e-c91c74892f25.png)

**Comment by jebter** [comment]
Please post your problem to https://asktug.com. They would reply to your problem ASAP.I will close this issue. If there are any updates, you can reopen it.
