### ISSUE TITLE
Support information_schema.placement_rules

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#26681]
Support an information_schema table to summarize all placement rules.

Relates to https://github.com/pingcap/tidb/issues/26582

**Comment by xhebox** [comment]
The work could start, IMO. `TableInfo` now has realated info.

> The INFORMATION_SCHEMA.PLACEMENT_RULES will not show the simplified syntactic sugar forms like PRIMARY_REGION or REGIONS, since that makes the table consistent and avoids having logic in the readers of this information schema.

From what we have done now, `PRIMARY_REGION` should be displayed. We don't have transformation from `PRIMARY_REGION` to `XXX_CONSTRAINTS`, but directly to the internal struct.

**Comment by mjonss** [comment]
> The work could start, IMO. `TableInfo` now has realated info.

I have added PLACEMENT POLICY and DIRECT PLACEMENT for tables into my working branch: https://github.com/pingcap/tidb/pull/27478
Have Schema and Partition level DIRECT PLACEMENT been implemented/merged too? Any hints on where to access it?

> > The INFORMATION_SCHEMA.PLACEMENT_RULES will not show the simplified syntactic sugar forms like PRIMARY_REGION or REGIONS, since that makes the table consistent and avoids having logic in the readers of this information schema.
> 
> From what we have done now, `PRIMARY_REGION` should be displayed. We don't have transformation from `PRIMARY_REGION` to `XXX_CONSTRAINTS`, but directly to the internal struct.

I think it would be more user friendly to transform `PRIMARY_REGION`/`REGIONS` to `XXX_CONSTRAINTS` so one can query the is.placement_rules table directly on the `XXX_CONSTRAINTS` columns, without having logic to also check PRIMARY_REGION/REGIONS.
Also including PRIMARY_REGION/REGIONS in the is.placement_rules would be OK, to show that syntactic sugar was used.

**Comment by xhebox** [comment]
> Have Schema and Partition level DIRECT PLACEMENT been implemented/merged too? Any hints on where to access it?

No. I guess it will be in `PartitionDef()` and `DBInfo`.

> I think it would be more user friendly to transform PRIMARY_REGION/REGIONS to XXX_CONSTRAINTS so one can query the is.placement_rules table directly on the XXX_CONSTRAINTS columns.

I could provide one, once #27814 is merged. I've leave the decision to you :)

**Comment by mjonss** [comment]
> > Have Schema and Partition level DIRECT PLACEMENT been implemented/merged too? Any hints on where to access it?
> 
> No. I guess it will be in `PartitionDef()` and `DBInfo`.

OK, then I will follow up on the github issue where it will be implemented. Possibly seeing if we can merge the work so far (having information_schema.placement_rules only covering `PLACEMENT POLICY` and DIRECT PLACEMENT for tables so far, and add DIRECT PLACEMENT for schemas and partitions later, when they are in place.
 
> > I think it would be more user friendly to transform PRIMARY_REGION/REGIONS to XXX_CONSTRAINTS so one can query the is.placement_rules table directly on the XXX_CONSTRAINTS columns.
> 
> I could provide one, once #27814 is merged. I will leave the decision to you :)

Yes, please provide a function transforming the syntax sugar to XXX_CONSTRAINTS, which would make it more user friendly to search in the information_schema.placement_rules table :)
