### ISSUE TITLE
Time Zone Support is not compatible with mysql (not bug)

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#26709]
## Enhancement
In tidb, Only the values of the Timestamp data type is affected by time zone. This is because the Timestamp data type uses the literal value + time zone information. Other data types, such as Datetime/Date/Time, do not have time zone information, thus their values are not affected by the changes of time zone.

In MySQL 8.0.19 and later, you can specify a time zone offset when inserting a TIMESTAMP or DATETIME value into a table.

it need to be improved.

**Comment by morgo** [comment]
@hawkingrei can you include a testcase for the issue?

**Comment by hawkingrei** [comment]
> @hawkingrei can you include a testcase for the issue?

I find the problem when i run the test in the django orm.

**Comment by hawkingrei** [comment]
i think this could be a testing issue. so closed.
