### ISSUE TITLE
ddl, store: some `select` operations may block forever

### ISSUE THREAD

**Issue by BurtonQin** [pingcap/tidb#26804]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

We found 5 blocking bugs through a WIP Fuzzing project by system-pclub, PSU. 

### 2. What did you expect to see? (Required)

The `select` operation shall not block forever whatever the order of the concurrent messages.

### 3. What did you see instead (Required)

We found the 5 blocking bugs by fuzzing the code from
Entry point 1:
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/ddl_test.go#L60
1.	Blocked at `select` in function `limitDDLJobs` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/ddl_worker.go#L258-L277
The channel is created in function `newDDL` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/ddl.go#L308-L312
2.	Blocked at `select` in function `startEmulator` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/delete_range.go#L138-L146
The channels are created in function `newDelRangeManager` at 
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/delete_range.go#L75-L83
3.	Blocked at `select` in function `StartDeadlockDetection` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/mvcc.go#L1284-L1294
The channels are created in function `NewMVCCStore` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/mvcc.go#L74
and in function `NewDetectorClient` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/deadlock.go#L129-L132

Entry point 2:
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/util/syncer_test.go#L47
4.	Blocked at `select` in function `StartCleanWork ` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/util/syncer.go#L429-L451
The channel is created in function `NewSchemaSyncer` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/util/syncer.go#L127
Entry point 3:
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/tikv_test.go#L24
5.	Blocked at `select` in function `run` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/write.go#L95-L100
The channels are created in function `NewDBWriter` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/write.go#L186-L191
and in function `Open` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/write.go#L193-L201

### 4. What is your TiDB version? (Required)
branch: master
commit: 7e6690df8e8d5474b1872edbd279bb1b3c510ee5

**Comment by ChenPeng2013** [comment]
@bb7133 PTAL,  is it a bug, thanks

**Comment by xhebox** [comment]
It is safe **under the current impl**.

For example, the first one `<-d.limitJobCh` is blocking, but it checks for length. And there is only one receiver, which means it will increase monotonically for this goroutine. So it is completely safe to block. Similar to case 5.

The other cases are safe, as long as we send the quit chan, it won't be a dead loop. I choose to close the issue, if you have futher concerns that I did not come up, I will reopen and fix it.
