### ISSUE TITLE
store/mockstore: Some `wg.Wait()` operations may block forever

### ISSUE THREAD

**Issue by BurtonQin** [pingcap/tidb#26805]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

We found 2 blocking bugs through a WIP Fuzzing project by system-pclub, PSU. 

### 2. What did you expect to see? (Required)

The `wg.Wait()` operation shall not block forever whatever the order of the concurrent messages.

### 3. What did you see instead (Required)

We found the 2 bugs by fuzzing the code from entry point:
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/ddl/ddl_test.go#L60
1.	Blocked at `Wait()` in function `acquireOne` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/region.go#L107-L111
2.	Blocked at `Wait()` in function `Write` at
https://github.com/pingcap/tidb/blob/fa71a0e46d427e8a7450a2dce27f8c0d4c02a45c/store/mockstore/unistore/tikv/write.go#L227-L233

### 4. What is your TiDB version? (Required)
branch: master
commit: 7e6690df8e8d5474b1872edbd279bb1b3c510ee5

**Comment by ChenPeng2013** [comment]
@sticnarf PTAL, is it a bug, thanks

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
