### ISSUE TITLE
Set variable `tidb_skip_isolation_level_check` seems not work as expected

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#26810]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Set variable `tidb_skip_isolation_level_check` to on and exit
```
mysql> set global tidb_skip_isolation_level_check=1;
Query OK, 0 rows affected (0.09 sec)
mysql> select @@tidb_skip_isolation_level_check;
+-----------------------------------+
| @@tidb_skip_isolation_level_check |
+-----------------------------------+
|                                 1 |
+-----------------------------------+
1 row in set (0.00 sec)
mysql> exit
Bye
```

Login in to mysql and set unsupported isolation level
```
mysql> set tx_isolation='serializable';
ERROR 8048 (HY000): The isolation level 'SERIALIZABLE' is not supported. Set tidb_skip_isolation_level_check=1 to skip this error
mysql> select @@tidb_skip_isolation_level_check;
+-----------------------------------+
| @@tidb_skip_isolation_level_check |
+-----------------------------------+
|                                 1 |
+-----------------------------------+
1 row in set (0.00 sec)

mysql> set tx_isolation='serializable';
Query OK, 0 rows affected, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                       |
+---------+------+---------------------------------------------------------------------------------------------------------------+
| Warning | 8048 | The isolation level 'SERIALIZABLE' is not supported. Set tidb_skip_isolation_level_check=1 to skip this error |
+---------+------+---------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
After this variable is enabled, if setting unsupported tx_isolation, no error is reported.

### 3. What did you see instead (Required)
Need to query the variable first and set unsupported tx_isolation.

### 4. What is your TiDB version? (Required)
v5.1.0

**Comment by youngwookim** [comment]
Works on 5.0.3 version but 5.1 and 5.2 version do not work as expected. Any alternatives to avoid this bug for now?

**Comment by fzhan** [comment]
Using tidb-operator to set this variable but doesn't seems to be effective:

```
set global tidb_skip_isolation_level_check='on';
show VARIABLES where Variable_name = 'tidb_skip_isolation_level_check'; 
```
Results in
```
set global tidb_skip_isolation_level_check='on'
> OK
> Time: 0.05s
```
But
|tidb_skip_isolation_level_check | Off|

**Comment by zyguan** [comment]
So what's the progress of https://github.com/pingcap/tidb/pull/28953 ? Can we close this issue if it won't be merged?

**Comment by sunxiaoguang** [comment]
> So what's the progress of #28953 ? Can we close this issue if it won't be merged?

Waiting for triage for next 5.1 and 5.2 release

**Comment by zyguan** [comment]
Close the issue because https://github.com/pingcap/tidb/pull/28953 & https://github.com/pingcap/tidb/pull/28957 are already waiting for triage.
