### ISSUE TITLE
Comment on how to add TiDB specific system variable is outdated

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#26838]
## Enhancement

In `sessionctx/variable/tidb_vars.go`, there is comment about steps to add a new TiDB specific system variable. However, the steps are outdated after refactor. For example, there is no `session.loadCommonGlobalVarsSQL` mentioned at step 7 and there is no `ValidateSetSystemVar` mentioned at step 8. Besides, there seems no need to update `variable.SetSessionSystemVar`. Maybe we can update the comment.

**Comment by xuyifangreeneyes** [comment]
@morgo PTAL

**Comment by morgo** [comment]
@xuyifangreeneyes Thank you for spotting this! Actually all steps after 3 are technically out of date. I will fix it shortly.
