### ISSUE TITLE
Support binding query with 

### ISSUE THREAD

**Issue by tirsen** [pingcap/tidb#26849]
## Feature Request

**Is your feature request related to a problem? Please describe:**

We have lots of queries with bad query plans that we would like to create bindings for. Unfortunately they use IN-clauses with hundreds of parameters. It's not feasible to create bindings for each of these queries.

**Describe the feature you'd like:**

Syntax and semantics needs to be defined.

For example we could say that the parameterization of an IN clause is always variadic.

Something like this:
```
CREATE BINDING FOR 
  SELECT * FROM t WHERE a IN (1,2,3) 
USING 
  SELECT * FROM t use index  (idx) WHERE a IN (1,2,3)
```

This would create a binding for a variadic query like this:
```
SELECT * FROM t WHERE a IN (...)
```

Or perhaps like this with unary statement with an ARRAY parameter?
```
SELECT * FROM t WHERE a IN ?
```

**Describe alternatives you've considered:**

The alternative is to create hundreds of bindings which is cumbersome and might create performance problems?

**Teachability, Documentation, Adoption, Migration Strategy:**

This behaviour is somewhat surprising so would obviously need to be documented. :-)

**Comment by eurekaka** [comment]
I believe we have already supported this kind of variadic normalization for IN expressions?

```
mysql> create table t(a int, b int, index idx(a));
Query OK, 0 rows affected (0.00 sec)

mysql> create global binding for select * from t where a in (1,2,3) using select * from t use index(idx) where a in (1,2,3);
Query OK, 0 rows affected (0.01 sec)

mysql> show global bindings;
+-------------------------------------------------+-----------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql                                    | Bind_sql                                                        | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------------------------------+-----------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from `test` . `t` where `a` in ( ... ) | SELECT * FROM `test`.`t` USE INDEX (`idx`) WHERE `a` IN (1,2,3) | test       | using  | 2021-08-04 17:20:27.729 | 2021-08-04 17:20:27.729 | utf8    | utf8_general_ci | manual |
+-------------------------------------------------+-----------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
1 row in set (0.00 sec)

mysql> select * from t where a in (4,5);
Empty set (0.00 sec)

mysql> select @@last_plan_from_binding;
+--------------------------+
| @@last_plan_from_binding |
+--------------------------+
|                        1 |
+--------------------------+
1 row in set (0.00 sec)
```

**Comment by eurekaka** [comment]
It is supported from the beginning by https://github.com/pingcap/parser/pull/32/files#diff-48bbd2ba87d738045c9257feb9af5f078c0392af4cd1a0351ea6c67c3ad57e1cR189
