### ISSUE TITLE
Query using index has a duplicated result.

### ISSUE THREAD

**Issue by VoxT** [pingcap/tidb#26846]
## Bug Report

We have 2 TiDB clusters, one master and one slave. Data replicated from master to slave by TiDB-binlog.
When query by index on the slave, the result has a duplicated row, but the result is corrected when executing the same query on master.

Currently, the bug only affected one record, no other duplicate record found so far.

### 1. Minimal reproduce step (Required)

Table schema:
```sql
CREATE TABLE `log` (
  `field_1` bigint(20) NOT NULL,
  `field_2` smallint(6) NOT NULL,
  `field_3` bigint(20) NOT NULL,
  `field_4` int(11) NOT NULL,
  `field_5` varchar(64) NOT NULL,
  `field_6` smallint(6) NOT NULL,
  `field_7` varchar(64) NOT NULL,
  `field_8` varchar(64) NOT NULL,
  `field_9` varchar(16) NOT NULL DEFAULT '-1',
  `field_10` smallint(1) NOT NULL,
  `field_11` int(11) NOT NULL,
  `field_12` int(11) NOT NULL,
  `field_13` bigint(20) NOT NULL,
  `field_14` bigint(20) NOT NULL,
  `field_15` json NOT NULL,
  `field_16` bigint(20) NOT NULL,
  `field_17` bigint(20) NOT NULL,
  `field_18` bigint(20) NOT NULL,
  `field_19` bigint(20) NOT NULL,
  `field_20` bigint(20) NOT NULL,
  `field_21` varchar(1024) NOT NULL,
  `field_22` varchar(1024) NOT NULL,
  PRIMARY KEY (`field_1`,`field_2`,`field_3`),
  KEY `key_1` (`field_7`,`field_11`),
  KEY `key_2` (`field_20`),
  KEY `key_3` (`field_14`),
  KEY `key_4` (`field_8`),
  KEY `key_5` (`field_3`,`field_19`),
  KEY `key_6` (`field_5`,`field_4`,`field_12`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

1.   Query by index (key_1, key_2, key_3, key_4) has the incorrect result (which has a duplicate row). Other index (which has less unique value) is not verify due to large of data.
```sql
select field_1, field_2, field_3 from log where field_7='PU210610000124334';
select field_1, field_2, field_3 from log where field_20=1623269827689;
select field_1, field_2, field_3 from log where field_14=1623269827689;
select field_1, field_2, field_3 from log where field_8='210610000124334';
```
- The result is the same for 4 queries above:
<img width="342" alt="dup-result" src="https://user-images.githubusercontent.com/13825568/127984359-9000e2bc-6087-460e-a1bb-0dd918d320ad.png">

- The explain analyze:
```sql
explain analyze select field_1, field_2, field_3 from log where field_7='PU210610000124334';
--- result:
id,count,task,"operator info","execution info",memory
Projection_4,0.00,root,"zas.log.field_1, zas.log.field_2, zas.log.field_3","time:5.042769ms, loops:2, rows:5",N/A
└─IndexLookUp_10,0.00,root,,"time:5.031902ms, loops:2, rows:5","9.68359375 KB"
"  ├─IndexScan_8",0.00,cop,"table:log, index:field_7, field_11, range:["PU210610000124334","PU210610000124334"], keep order:false","time:0s, loops:1, rows:5",N/A
"  └─TableScan_9",0.00,cop,"table:log, keep order:false","time:0s, loops:1, rows:5",N/A

explain analyze select field_1, field_2, field_3 from log where field_14=1623269827689; -- field_20 has the same result.
--- result:
id,count,task,"operator info","execution info",memory
IndexLookUp_10,1270371.65,root,"zas.log.field_1, zas.log.field_2, zas.log.field_3","time:4.038591ms, loops:2, rows:5","17.83984375 KB"
├─IndexScan_8,1270371.65,cop,"table:log, index:field_14, range:[1623269827689,1623269827689], keep order:false","time:0s, loops:1, rows:5",N/A
└─TableScan_9,1270371.65,cop,"table:log, keep order:false","time:0s, loops:1, rows:5",N/A

explain analyze select field_1, field_2, field_3 from log where field_8='210610000124334';
--- result:
id,count,task,"operator info","execution info",memory
Projection_4,0.00,root,"zas.log.field_1, zas.log.field_2, zas.log.field_3","time:10.568519ms, loops:2, rows:5",N/A
└─IndexLookUp_10,0.00,root,,"time:10.555061ms, loops:2, rows:5","9.68359375 KB"
"  ├─IndexScan_8",0.00,cop,"table:log, index:field_8, range:["210610000124334","210610000124334"], keep order:false","time:1ms, loops:1, rows:5",N/A
"  └─TableScan_9",0.00,cop,"table:log, keep order:false","time:1ms, loops:1, rows:5",N/A
```

2. Query by the first field on the compose primary key. The result is corrected
```sql
select field_1, field_2, field_3 from log where field_1=100122019622518784;
```
- The result:
<img width="337" alt="correct-result" src="https://user-images.githubusercontent.com/13825568/127983764-ab9b4e50-5d95-4b1f-a7f8-23bc6d0ee22e.png">

- The explain analyze:
```sql
explain analyze select field_1, field_2, field_3 from log where field_1=100122019622518784;
--- result:
id,count,task,"operator info","execution info",memory
IndexReader_6,0.00,root,index:IndexScan_5,"time:2.215023ms, loops:2, rows:4","274 Bytes"
└─IndexScan_5,0.00,cop,"table:log, index:field_1, field_2, field_3, range:[100122019622518784,100122019622518784], keep order:false","time:0s, loops:1, rows:4",N/A
```

### 2. What did you expect to see? (Required)
Non-duplicate result by any query criteria.

### 3. What did you see instead (Required)
Duplicate result if query using index.

### 4. What is your TiDB version? (Required)

'5.7.25-TiDB-v3.0.12'

**Comment by aytrack** [comment]
could you provide the data of the table? 
Does the data of the table is consistent between that master and slave?

**Comment by yudongusa** [comment]
@VoxT could you please run the following query and show the results?

select * from log where field_1=100122019622518784;

**Comment by VoxT** [comment]
> @VoxT could you please run the following query and show the results?
> 
> select * from log where field_1=100122019622518784;

@yudongusa The result:
[data.csv](https://github.com/pingcap/tidb/files/6928107/data.csv)

**Comment by VoxT** [comment]
> could you provide the data of the table?

The data is too large and has sensitive data so I can't. But the data related to this record and some sample data then yes.

> Does the data of the table is consistent between that master and slave?

We use TiDB-binlog to replicate data. This table accepts the write from the TiDB-binlog only, so I think it is consistent.
Noe:  it has some index on the slave but the master does not.
As I mention, in the master all those queries above have the same result and it is corrected.
<img width="337" alt="correct-result" src="https://user-images.githubusercontent.com/13825568/128111697-bbb0f5ca-96e9-4552-aea1-e1342669ef91.png">

**Comment by bb7133** [comment]
Hi @VoxT , could you please run the following command for the `log` table of slave cluster?

```
admin check table log;
```

Thanks.

**Comment by VoxT** [comment]
> Hi @VoxT , could you please run the following command for the `log` table of slave cluster?
> 
> ```
> admin check table log;
> ```
> 
> Thanks.

@bb7133 
It takes a long-running and throws this error:
```bash
ERROR 9006 (HY000) at line 1: GC life time is shorter than transaction duration, transaction starts at 2021-08-05 10:52:19.008 +0700 +07, GC safe point is 2021-08-05 11:00:45.108 +0700 +07
```

**Comment by jebter** [comment]
@lichunzhu PTAL

**Comment by lichunzhu** [comment]
> > Hi @VoxT , could you please run the following command for the `log` table of slave cluster?
> > ```
> > admin check table log;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks.
> 
> @bb7133
> It takes a long-running and throws this error:
> 
> ```shell
> ERROR 9006 (HY000) at line 1: GC life time is shorter than transaction duration, transaction starts at 2021-08-05 10:52:19.008 +0700 +07, GC safe point is 2021-08-05 11:00:45.108 +0700 +07
> ```

Could you please set a longer gc_life_time?
```sql
update mysql.tidb set VARIABLE_VALUE = '144h' where VARIABLE_NAME = 'tikv_gc_life_time';
```

**Comment by VoxT** [comment]
> 
> Could you please set a longer gc_life_time?
> 
> ```sql
> update mysql.tidb set VARIABLE_VALUE = '144h' where VARIABLE_NAME = 'tikv_gc_life_time';
> ```

@lichunzhu 

already set and re-run `admin check table log;`, please wait for the result.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/13825568/128511622-1c54e6f4-cd21-49fb-8a46-66e4477fa9bd.png)

**Comment by VoxT** [comment]
@lichunzhu 

Is there another way to check the table? The `admin check table log;` run too long and has been failed due to connection lost after 4 days.
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/13825568/128801747-b5e9c87c-b044-4fc3-a0de-a43a13814293.png)

**Comment by anhldbk** [comment]
Guys, does this bug relate to the following fix in v4? https://github.com/pingcap/tidb/pull/24634

**Comment by Defined2014** [comment]
This issue has not been responded to for a long time, so I will close it for now. If you need it, please open it again.
