### ISSUE TITLE
migrate test-infra to testify for `executor`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26854]
* [x] #26160
* [x] #27097
* [x] #27404
* [x] #27459
* [x] #28074
* [x] #28075
* [x] #28076
* [x] #28440
* [x] #28498
* [x] #28562
* [x] #28563
* [x] #28564
* [x] #28565
* [x] #28566
* [x] #28567
* [x] #28568
* [x] #28569
* [x] #28570
* [x] #28571
* [x] #28572
* [x] #28573
* [x] #28574
* [x] #28575
* [x] #28576
* [x] #28577
* [x] #28578
* [x] #28579
* [x] #28580
* [x] #28581
* [x] #28582
* [x] #28583
* [x] #28584
* [x] #28585
* [x] #28586
* [x] #28587
* [x] #28588
* [x] #28589
* [x] #28590
* [x] #28591
* [x] #28592
* [x] #28593
* [x] #28594
* [x] #28595
* [x] #28596
* [x] #28597
* [x] #28598
* [x] #28599
* [x] #28600
* [x] #28601
* [x] #28602
* [x] #28603
* [x] #28604
* [x] #28605
* [x] #28606
* [x] #28607
* [x] #28608
* [x] #28609
* [x] #28610
* [x] #28611
* [x] #28612
* [x] #28613
* [x] #28614
* [x] #28615
* [x] #28616
* [x] #28617
* [x] #28618
* [x] #28619
* [x] #28620
* [x] #28621
* [x] #28622
* [x] #28623
* [x] #28624
* [x] #28625
* [x] #28626
* [x] #28627

**Comment by tisonkun** [comment]
This package is too complex to have its own issue and we'd migrate then in multiple batches. Please comment the filename you want to do and I will update the checklist.

**Comment by unconsolable** [comment]
Some tests has both serial suite and suite, for example `cte_test.go` has both `CTETestSuite` and `CTESerialTestSuite`. Serial suite in pingcap/check can be replaced by suite in testify, while suite can not because parallel execution is not supported in testify.

IMO a parent test may be built and acted as `SetUpSuite` and `TearDownSuite`, and other tests are introduced by sub tests. Also stretchr/testify#1109 are working on parellel execution, which is waiting to be reviewed.

So should we wait for the upstream PR? Or propose other alternatives?

**Comment by tisonkun** [comment]
@unconsolable almost we use testify checkers only and it is viable to setup/teardown tests with go testing.

See also https://pkg.go.dev/testing#hdr-Subtests_and_Sub_benchmarks.

testify is already aware of this issue https://github.com/stretchr/testify/issues/187 years ago and the author of stretchr/testify#1109 isn't one of the maintainer. I don't think they will enable this feature soon.

You can see how we migrate suite to go testing + testify previously.

**Comment by unconsolable** [comment]
Please add #27097 as a sub task

**Comment by tisonkun** [comment]
@unconsolable done. Thank you!

**Comment by unconsolable** [comment]
When migrating the tests in `executor`, please check the unexpected goroutine leak issues manually. See also https://github.com/pingcap/tidb/pull/27103#issuecomment-901548669

> We don't have to add it now since there are multiple tests leak on never closing domain, etc. We will perform another pass to fix the leak problem but I'd prefer it soon after we migrate the tests. And thus during the migration, I hope the author manually check whether or not the tests leak.
>
> etcd related leaks is somehow "expected", domain's, badger's are unexpected.

**Comment by tisonkun** [comment]
@unconsolable I hope we can enable goleak by https://github.com/pingcap/tidb/pull/27405.

**Comment by unconsolable** [comment]
@tisonkun 
As currently tests under `executor` packages are using both `pingcap/check` and `testify`, should we move the code in `TestT` to `main_test.go` to set up all of the tests?
https://github.com/pingcap/tidb/blob/76267b21aee467f33426c2bdc1ccd3a5bd966b77/executor/executor_test.go#L89-L111
From my point of view, code related to `pingcap/check` can still in `TestT`, while code related to `testleak` may be replaced by `goleak` enabled in `TestMain`. All the other code, may be moved to `TestMain`. WDYT

**Comment by tisonkun** [comment]
@unconsolable reasonable. I'd suggest you create an issue and start to work on it if you want to. Ask me to linked at this issue.

**Comment by unconsolable** [comment]
@tisonkun Created https://github.com/pingcap/tidb/issues/28440

**Comment by karuppiah7890** [comment]
Let's create issues for each of the files like other package issues?

**Comment by tisonkun** [comment]
@karuppiah7890 yes. Creating...

**Comment by tisonkun** [comment]
Closed as all subtasks done. Finally!
