### ISSUE TITLE
migrate test-infra to testify for `expression`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26855]
You may try to analyze first and spawn more subtasks instead of one big PR handle the whole package which is hard to review.

* [x] #27904
* [x] migrate test-infra to testify for `expression/bench_test.go`
* [x] migrate test-infra to testify for `expression/builtin_arithmetic_test.go`
* [x] migrate test-infra to testify for `expression/builtin_arithmetic_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_cast_bench_test.go`
* [x] migrate test-infra to testify for `expression/builtin_cast_test.go`
* [x] migrate test-infra to testify for `expression/builtin_cast_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_compare_test.go`
* [x] migrate test-infra to testify for `expression/builtin_compare_vec_generated_test.go`
* [x] migrate test-infra to testify for `expression/builtin_compare_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_control_test.go`
* [x] migrate test-infra to testify for `expression/builtin_control_vec_generated_test.go`
* [x] migrate test-infra to testify for `expression/builtin_encryption_test.go`
* [x] migrate test-infra to testify for `expression/builtin_encryption_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_info_test.go`
* [x] migrate test-infra to testify for `expression/builtin_info_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_json_test.go`
* [x] migrate test-infra to testify for `expression/builtin_json_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_like_test.go`
* [x] migrate test-infra to testify for `expression/builtin_like_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_math_test.go`
* [x] migrate test-infra to testify for `expression/builtin_math_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_miscellaneous_test.go`
* [x] migrate test-infra to testify for `expression/builtin_miscellaneous_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_op_test.go`
* [x] migrate test-infra to testify for `expression/builtin_op_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_other_test.go`
* [x] migrate test-infra to testify for `expression/builtin_other_vec_generated_test.go`
* [x] migrate test-infra to testify for `expression/builtin_other_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_regexp_vec_const_test.go`
* [x] migrate test-infra to testify for `expression/builtin_string_test.go`
* [x] migrate test-infra to testify for `expression/builtin_string_vec_generated_test.go`
* [x] migrate test-infra to testify for `expression/builtin_string_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_test.go`
* [x] migrate test-infra to testify for `expression/builtin_time_test.go`
* [x] migrate test-infra to testify for `expression/builtin_time_vec_generated_test.go`
* [x] migrate test-infra to testify for `expression/builtin_time_vec_test.go`
* [x] migrate test-infra to testify for `expression/builtin_vectorized_test.go`
* [x] #28849
* [x] #28850
* [x] #28851
* [x] #28853
* [x] #28854
* [x] #29132
* [x] #29133
* [x] #29134
* [x] #29135
* [x] #29136
* [x] #29137
* [x] #29138
* [x] #29139
* [x] #29140
* [x] #29141
* [x] #29142
* [x] #29143
* [x] #29144
* [x] #30628

**Comment by penthaapatel** [comment]
Hi @tisonkun, I'd like to migrate tests under `expression/aggregation` pkg. So I created a new issue #27904 to track the changes easily. Could you add the newly created issue as a subtask of this issue?

**Comment by tisonkun** [comment]
@penthaapatel added. Thanks a lot for your participant!

**Comment by tisonkun** [comment]
Closed as all subtasks done.

**Comment by hawkingrei** [comment]
In fact, Many task like ```analyze_test.go``` are not migrated

**Comment by tisonkun** [comment]
@hawkingrei sorry that I miss the file :P

**Comment by tisonkun** [comment]
Closed as all subtasks done.

@hawkingrei could you please do a sanity check?
