### ISSUE TITLE
migrate test-infra to testify for `planner/core`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26857]
You may try to analyze first and spawn more subtasks instead of one big PR handle the whole package which is hard to review.

* [x] #27432
* [x] #28386
* [x] #28387
* [x] #28388
* [x] #28389
* [x] #28407
* [x] #28414
* [x] #28408
* [x] #28405
* [x] #28406
* [x] #28404
* [x] #28413
* [x] #28412
* [x] #28411
* [x] #28410
* [x] #28403
* [x] #28402
* [x] #28401
* [x] #28400
* [x] #28409
* [x] #28390
* [x] #28391
* [x] #28392
* [x] #28393
* [x] #28394
* [x] #28395
* [x] #28396
* [x] #28397
* [x] #28398
* [x] #28399

**Comment by karuppiah7890** [comment]
@tisonkun You can maybe add this list of sub tasks per file ?

- planner/core/cache_test.go
- planner/core/cacheable_checker_test.go
- planner/core/cbo_test.go
- planner/core/enforce_mpp_test.go
- planner/core/errors_test.go
- planner/core/exhaust_physical_plans_test.go
- planner/core/expression_rewriter_test.go
- planner/core/expression_test.go
- planner/core/find_best_task_test.go
- planner/core/indexmerge_test.go
- planner/core/integration_partition_test.go
- planner/core/integration_test.go
- planner/core/logical_plan_test.go
- planner/core/logical_plans_test.go
- planner/core/main_test.go
- planner/core/memtable_predicate_extractor_test.go
- planner/core/optimizer_test.go
- planner/core/partition_pruner_test.go
- planner/core/partition_pruning_test.go
- planner/core/physical_plan_test.go
- planner/core/plan_test.go
- planner/core/plan_to_pb_test.go
- planner/core/planbuilder_test.go
- planner/core/point_get_plan_test.go
- planner/core/prepare_test.go
- planner/core/preprocess_test.go
- planner/core/rule_inject_extra_projection_test.go
- planner/core/rule_join_reorder_dp_test.go
- planner/core/rule_result_reorder_test.go
- planner/core/stats_test.go

**Comment by tisonkun** [comment]
@karuppiah7890 thanks for your help! The description is updated.

main_test.go needs not to be migrated

You can start as the order I create this issues (see also the issues list page) the later is more complex in my opinion, especially for these I don't mark as "good first issue".

**Comment by tisonkun** [comment]
@karuppiah7890 also I suggest you take a look at the non testing code during the journey. They are one of the core functions of TiDB as a SQL engine. You can ask any question about the implementation or design at https://internals.tidb.io/c/sqlengine . I think there are many to-do works for an optimized optimizer.

**Comment by karuppiah7890** [comment]
You mean the main source code? Or the main source code which is not tested with golang tests?

**Comment by tisonkun** [comment]
@karuppiah7890 the main source code. If you find the main source code lack of test coverage, you can try to add one. It is highly encouraged.
