### ISSUE TITLE
migrate test-infra to testify for `server`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26863]
You may try to analyze first and spawn more subtasks on demand (no strict) instead of one big PR handle the whole package which is hard to review.

* [x] #27041 
* [x] #27342
* [x] #27343
* [x] #27618
* [x] #27619
* [x] #27804
* [x] #27805
* [x] #27806 
* [x] #27807 
* [x] #27808

**Comment by yedamao** [comment]
- [ ] #27041

**Comment by tisonkun** [comment]
> Please add #27041 as subtask of this issue.

done.

**Comment by yedamao** [comment]
Please add #27342 and #27343  as subtask of this issue.

**Comment by tisonkun** [comment]
> Please add #27342 and #27343 as subtask of this issue.

done

**Comment by yedamao** [comment]
@tisonkun Please add #27804 #27805 #27806 #27807 #27808 as subtask of this issue.

**Comment by tisonkun** [comment]
@yedamao updated. Thanks a lot for driving this issue!

**Comment by tisonkun** [comment]
@yedamao do you have a plan to continue the rest tasks? I suggest you to resolve them one suite and the other - each file seems too large to be finished at once.

Also you can trying to call for other contributors by sending a request on Twitter or WeChat moments or blogs. If so, feel free to add it to https://github.com/tisonkun/weekly/issues/11.

**Comment by tisonkun** [comment]
@yedamao I finished #27804 recently and there are #27805 & #27806 left.

**Comment by tisonkun** [comment]
Closed as all subtasks are done. Thank you so much for driving this issue @yedamao !
