### ISSUE TITLE
migrate test-infra to testify for `table/tables`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26866]
You may try to analyze first and spawn more subtasks on demand (no strict) instead of one big PR handle the whole package which is hard to review.

There may be several unstable tests, be careful or you may try to fix it. If not, keep logic as is.

* [x] #27588
* [x] #27589
* [x] #27590

**Comment by feitian124** [comment]
hello, please create subtask for me and put `index_test.go` as the first one.

- [x] migrate `index_test.go`
- [ ] migrate `partition_test.go`
- [ ] migrate `tables_test.go`

**Comment by tisonkun** [comment]
@feitian124 updated.
