### ISSUE TITLE
Track issue of merge BR into TiDB 

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#26877]
## Development Task 

This issue traces the effort to  merge BR into TiDB.

Original discussion is on https://internals.tidb.io/t/topic/256/8

* [x] #26879
* [x] https://github.com/pingcap/kvproto/issues/790
* [x] #26880
* [x] https://github.com/PingCAP-QE/ci/issues/353
* [x] #26983
* [x] #27624
* [x] #28089
* [x] #28911

**Comment by tisonkun** [comment]
Shall we review in order that first pingcap/kvproto#790 and then #26880 and then PingCAP-QE/ci#353?

**Comment by 3pointer** [comment]
> Shall we review in order that first [pingcap/kvproto#790](https://github.com/pingcap/kvproto/issues/790) and then #26880 and then [PingCAP-QE/ci#353](https://github.com/PingCAP-QE/ci/issues/353)?

Yes, After pingcap/kvproto#790, we need change the go.mod in #26880

**Comment by tisonkun** [comment]
All subtasks done. The proposal is useless months after the merge happened.
