### ISSUE TITLE
Replace the execution framework on unistore with TiDB's builtin execution framework

### ISSUE THREAD

**Issue by ichn-hu** [pingcap/tidb#26878]
## Enhancement

Currently, the execution framework on unistore handles coprocessor requests is built by empirical rules about the type of coprocessor DAG request, which is too rigid and increased the maintaining labor. If we want to support more executor on copr in the future (such as projection), it will require a lot more consideration and is error-prone.

https://github.com/pingcap/tidb/blob/cc64519feb7ae0a93d27c662a3974f38ae91092b/store/mockstore/unistore/cophandler/closure_exec.go#L101-L161

However, since unistore is embedded in TiDB, we can consider reuse the execution framework inside TiDB, as it already reused the expression framework.

To make it possible, we can either decode the TiPB request into physical plans (a reversed operation as ToPB on physical plans), and then build the executors, or build the executors directly from the TiPB request.

After the refactoring, pushing executors to coprocessor will be more straightforward than the current implementation.

**Comment by skyzh** [comment]
I'm quite confused about unistore. As far as I know, unistore is a separate project here https://github.com/ngaut/unistore. Is the code for unistore inside TiDB the same as the unistore repository?

**Comment by xxchan** [comment]
@skyzh I found this https://github.com/pingcap/tidb/pull/23837

**Comment by hslam** [comment]
@skyzh @xxchan 
The unistore code inside TiDB is the same as the ngaut/unistore repository. Because there was an interdependence problem. That PR is to remove the dependency of the TiDB on ngaut/unistore. The ngaut/unistore is developed as a separate project like TiKV. The embedded unistore is used to build tidb-server. The ngaut/unistore is  used to build unistore-server as the golang version of tikv-server. At present, the ngaut/unistore is no new development in the master branch, but the sharding branch is working on cloud native development, and the tidb-5.0 branch is for compatibility with previous TiDB versions.

**Comment by feitian124** [comment]
it there a more detailed plan?

**Comment by ichn-hu** [comment]
> it there a more detailed plan?

Not yet, you are welcomed to try to write a detailed proposal for it!

**Comment by feitian124** [comment]
> > it there a more detailed plan?
> 
> Not yet, you are welcomed to try to write a detailed proposal for it!

i'd like to but maybe next time, i am a freshman here still.
but i'd like to join the job if need

**Comment by ichn-hu** [comment]
> > > it there a more detailed plan?
> > 
> > 
> > Not yet, you are welcomed to try to write a detailed proposal for it!
> 
> i'd like to but maybe next time, i am a freshman here still.
> but i'd like to join the job if need

let's see if there is anybody who would like to give a design, perhaps by the end of next week, otherwise I'll come up one.

**Comment by ichn-hu** [comment]
I've created a design doc with the background introduced, and now it seems we have 3 options for the refactoring, and I need some help on filling the design details and decide with way to go.

https://docs.google.com/document/d/1LIMuHv1wcI1VgfWo8KQK9RPlPXzoAuJHNy4Est1paF4/edit?pli=1#heading=h.t9kaf7pahrr5

I will filling the design details for **Replace the Framework with MPP Execution Framework**, would @xxchan and @feitian124 help filling design details for **Replace the Framework with TiDB’s Executors** and **Refine the existing executors of coprocessor**?

**Comment by ichn-hu** [comment]
btw, you can tell me your email address and I can give editor permission to you @xxchan @feitian124

**Comment by feitian124** [comment]
@ichn-hu thanks for pin me.  
my email is `feitian124@gmail.com`, but currently i only touched the surface of tidb, i am not sure if i am capable of doing this work. i will read your design doc and reply later

**Comment by xxchan** [comment]
Hello @coocood, could you please tell us why unistore implements a closureExecutor to replace the volcano model? (https://github.com/ngaut/unistore/pull/76)

**Comment by coocood** [comment]
> Hello @coocood, could you please tell us why unistore implements a closureExecutor to replace the volcano model? ([ngaut/unistore#76](https://github.com/ngaut/unistore/pull/76))
> 
> And what's your opinion about the refactoring?

For better performance, but it doesn't matter much for embeded unistore.
