### ISSUE TITLE
Find a good way to test potiential goroutine leak.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#2689]
Our current executor is not easy to reproduce potential goroutine leak.
We should figure out a good way to verify goroutine leak issue.

**Comment by zhexuany** [comment]
@coocood  checkout this https://github.com/fortytw2/leaktest

According to its readme, it help `net/http` and the `cockroachdb` find the leakage of goroutine.

**Comment by zhexuany** [comment]
Alternatively, We can compare the number of goroutine before the execution of code  and after the execution of code. 

~~~
g0 := runtime.NumGoroutine()
	const numReq = 10
 //some code
	gd := runtime.NumGoroutine() - g0
	if gd > numReq/2 {
		t.Errorf("appeared to leak goroutines")
	}
~~~

**Comment by coocood** [comment]
@zhexuany 
Thank you for your advice.
`leaktest` is already used in test code.
The problem is that some goroutine leak can not be easily reproduced in unit test code, it requires a large amount of data.

Another problem is that when we test multiple packages in parallel, many tests affect the goroutine count.

The solution I can think of is to write a special integration test which runs in a single process.
