### ISSUE TITLE
Integrate SkyWalking-eyes to check license headers in CI

### ISSUE THREAD

**Issue by fgksgf** [pingcap/tidb#26956]
## Enhancement

Integrate [SkyWalking-eyes](https://github.com/marketplace/actions/license-eye) to check license headers in CI.

For some new contributors, they may do not know the license header is required, we can use the GitHub Action and check license headers in CI automatically.

**Comment by tisonkun** [comment]
Hi @fgksgf , Thanks for creating this issue!

I think it is a good point we enable license checker in CI. In my opinion, you can directly create a PR and let's see how this action works on our repo. Then if it is good to go, we push it to merge.

**Comment by fgksgf** [comment]
> Hi @fgksgf , Thanks for creating this issue!
> 
> I think it is a good point we enable license checker in CI. In my opinion, you can directly create a PR and let's see how this action works on our repo. Then if it is good to go, we push it to merge.

No problem, I will do this :)

**Comment by fgksgf** [comment]
I locally checked the project with  [SkyWalking-eyes](https://github.com/marketplace/actions/license-eye), and found that almost all license headers have one less sentence compared to [the standard one](https://www.apache.org/foundation/license-faq.html#Apply-My-Software).

**Comment by kezhenxu94** [comment]
Well, the missing line is "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.", I think this sentence is critical and a modified Apache license header is not called Apache license actually.

**Comment by fgksgf** [comment]
> > I locally checked the project with [SkyWalking-eyes](https://github.com/marketplace/actions/license-eye), and found that almost all license headers have one less sentence compared to [the standard one](https://www.apache.org/foundation/license-faq.html#Apply-My-Software).
> 
> Well, the missing line is "WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.", I think this sentence is critical and a modified Apache license header is not called Apache license actually. It's better to add it back.

I'm working on fixing them.

**Comment by dragonly** [comment]
Congrats! You just fixed an error from the Genesis Commit!!!!!!

https://github.com/dragonly/tidb/commit/0d6f270068e8ff2aedc1c314e907771b6a508ebd#diff-3d4a6b7d54b5107bc5694b7a06383f9ec4c68f9abe43ba0942f5d970f3a8ccacR10-R11

**Comment by fgksgf** [comment]
@tisonkun We may need create an issue to track the ignored files in `.github/.licenserc.yaml`.

**Comment by tisonkun** [comment]
> @tisonkun We may need create an issue to track the ignored files in `.github/.licenserc.yaml`.

Yes. Would you like to create one for them?

**Comment by tisonkun** [comment]
I'm creating the issue...

**Comment by tisonkun** [comment]
as #27356
