### ISSUE TITLE
migrate test-infra to testify for `util/math` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#26978]

**Comment by tisonkun** [comment]
@HuGanghui sorry I assign myself 3 days ago for using this issue as an example for https://github.com/pingcap/tidb-dev-guide/issues/51. I'm working on it and will remove your assignment. You can still look for other subtasks in #26022 .

**Comment by HuGanghui** [comment]
@tisonkun ok~ It is my oversight that i do not notice it.
