### ISSUE TITLE
backup failed summary should be quieter

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#27015]
## Enhancement

The current version of backup failed summary is very verbose: it prints each ranges failed to be backed up, with stack trace of the fail reason, even the reason is trivially 'context cancelled'. for example:
`[2021/08/09 02:14:32.193 +00:00] [INFO] [collector.go:195] ["Full backup failed summary"] [total-ranges=8533] [ranges-succeed=3332] [ranges-failed=5201] [backup-total-ranges=8533] [unit-name="range start:? end:?"] [error="rpc error: code = Canceled desc = context canceled"] [errorVerbose="rpc error: code = Canceled desc = context canceled\ngithub.com/tikv/pd/client.(*client).GetAllStores\n\tgithub.com/tikv/pd@v0.0.0-20210105112549-e5be7fd38659/client/client.go:657\ngithub.com/pingcap/br/pkg/conn.GetAllTiKVStores\n\tgithub.com/pingcap/br/pkg/conn/conn.go:78\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRange\n\tgithub.com/pingcap/br/pkg/backup/client.go:524\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRanges.func2.1\n\tgithub.com/pingcap/br/pkg/backup/client.go:472\ngithub.com/pingcap/br/pkg/utils.(*WorkerPool).ApplyOnErrorGroup.func1\n\tgithub.com/pingcap/br/pkg/utils/worker.go:73\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1371"] [unit-name="range start:? end:?"] [error="rpc error: code = Canceled desc = context canceled"] [errorVerbose="rpc error: code = Canceled desc = context canceled\ngithub.com/tikv/pd/client.(*client).GetAllStores\n\tgithub.com/tikv/pd@v0.0.0-20210105112549-e5be7fd38659/client/client.go:657\ngithub.com/pingcap/br/pkg/conn.GetAllTiKVStores\n\tgithub.com/pingcap/br/pkg/conn/conn.go:78\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRange\n\tgithub.com/pingcap/br/pkg/backup/client.go:524\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRanges.func2.1\n\tgithub.com/pingcap/br/pkg/backup/client.go:472\ngithub.com/pingcap/br/pkg/utils.(*WorkerPool).ApplyOnErrorGroup.func1\n\tgithub.com/pingcap/br/pkg/utils/worker.go:73\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
... (more than 80 replicates of the above omitted)`

It is annoying and also shadows information really useful. We can make it more friendly:

1. We can print each failed unit and its error in separated logs, the summary should be a simple summary. Line-based unix toolchains like `grep` could take good from this.
2. Stacktrace of trivial errors (including `context.Canceled` or `err if status.Code(err) == codes.Canceled`) shouldn't be printed. If (1) has been implemented, units failed due to these errors could be printed as lower level(say, don't print them to the terminal, or use the DEBUG level?).

A better failure log may seem like:
```
[INFO] ["Full backup failed summary"] [total-ranges=8533] [ranges-succeed=3332] [ranges-failed=5201] [backup-total-ranges=8533]
[ERROR] ["Failed unit information"] [unit-name="range start:? end:?"] [error="[BR:KV:ErrKVStorage]tikv storage occur I/O error"] [errorVerbose="[BR:KV:ErrKVStorage]tikv storage occur I/O error\ngithub.com/pingcap/errors.AddStack\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/errors.go:174\ngithub.com/pingcap/errors.Trace\n\tgithub.com/pingcap/errors@v0.11.5-0.20201126102027-b0a155152ca3/juju_adaptor.go:15\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRange\n\tgithub.com/pingcap/br/pkg/backup/client.go:538\ngithub.com/pingcap/br/pkg/backup.(*Client).BackupRanges.func2.1\n\tgithub.com/pingcap/br/pkg/backup/client.go:472\ngithub.com/pingcap/br/pkg/utils.(*WorkerPool).ApplyOnErrorGroup.func1\n\tgithub.com/pingcap/br/pkg/utils/worker.go:73\ngolang.org/x/sync/errgroup.(*Group).Go.func1\n\tgolang.org/x/sync@v0.0.0-20201020160332-67f06af15bc9/errgroup/errgroup.go:57\nruntime.goexit\n\truntime/asm_amd64.s:1371"]
[INFO] ["Canceled units"] [units="[?, ..., ?]"]
 ```

**Comment by fengou1** [comment]
it looks we still need an improvement here.
