### ISSUE TITLE
New placement rule engine

### ISSUE THREAD

**Issue by xhebox** [pingcap/tidb#27011]
## Enhancement

This is a sub-task of Placement Rules in SQL: #18030. Depends on #26580 and #26581. Once metadata has been finished, we need to add a new middle state to all related DDL jobs to sync rules to PD. Previous, we have already implemented similar code, so the work is more of a migration.

This requires the following subtasks:

- [ ] truncate table/partition
- [ ] exchange table/partition
- [ ] drop db/table/partition
- [ ] create db/table/partition
- [ ] alter db/table/partition
- [ ] flashback/recover table/partition, since metadata is stored in meta, we can revert #20622 and special infoschema treatment for placement rules

**Comment by morgo** [comment]
I have moved the tasks of this sub-issue to https://github.com/pingcap/tidb/issues/18030

This was a suggestion to make it easier to see what tasks are unassigned. It makes sense to me, so I am going to close this issue.
