### ISSUE TITLE
Speed up the DDL execution speed of TiDB backup data restore

### ISSUE THREAD

**Issue by IANTHEREAL** [pingcap/tidb#27036]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

The cluster has 6 TiB data, 30k tables, and 11 TiKVs. When I use BR to backup and restore the cluster, I find that the speed is particularly slow. After investigation, BR can only create 2 tables per second, the entire store speed takes nearly 4h, and the execution time spent creating tables is close to 4h. It can be seen that the execution speed of ddl is the bottleneck in the this scenario.

**Describe alternatives you've considered:**

In order to speed up the restore speed, I hope TiDB to speed up the execution of DDL. In this scenario, BR can create tables at 200 tables/s
 In terms of compatibility, Binlog/CDC is required to be able to replicate the table schema of these tables, and the restored data does not need to be replicated temporarily

- [x] #30272
- [x] #30284
- [x] #30516
- [ ] CDC can sync data between upstream (TiDB) to downstream

**Comment by YuJuncen** [comment]
The bottleneck of creating table is to waiting the schema version changed. 
Each time we creating table, we should at least wait for `CheckVersFirstWaitTime`.

https://github.com/pingcap/tidb/blob/e262e59842fbd0eb23f1da71448eaaf97581c4a8/ddl/util/syncer.go#L362-L367

Currently, BR uses an internal interface named `CreateTableWithInfo` to creating table, which creating table and wait the schema changing one-by-one, omitting the sync of the ddl job between BR and leader, the procedure of creating one table would be like this:
```go
for _, t := range tables {
  RunInTxn(func(txn) {
    m := meta.New(txn)
    schemaVesrion := m.CreateTable(t)
    m.UpdateSchema(schemaVersion)
  })
  waitSchemaToSync() // <- This would notify and then 
  // waiting for all other TiDB nodes are synced with the latest schema version. 
}
```

If possible, we can move that I/O bounded operation out of the for loop, like:
```go
RunInTxn(func(txn) {
  for _, t := range tables {
    m := meta.New(txn)
    schemaVesrion := m.CreateTable(t)
    m.UpdateSchema(schemaVersion)
  })
}
waitSchemaToSync() // <- only one time of waiting. 
```

**Comment by YuJuncen** [comment]
This need TiDB to provide a batch version of `CreateTableWithInfo`, which create tables in bulk with one DDL job, might seem like this:

```go
// CreateTablesWithInfo creates many tables via the information.
// If the AutoID / AutoRandomID was set in the table info, 
// those of the new created table would be rebased to that.
// (optional to implement) Try to use the original table ID filled in the table info, 
// only at conflict try to alloc new ID when tryRetainID is `true`.
func (d *DDL) CreateTablesWithInfo(ctx sessionctx.Context,
		schema model.CIStr,
		infos []*model.TableInfo,
		onExist OnExist,
		tryRetainID bool) error
```
