### ISSUE TITLE
Integrate TiDB with Active Record

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27040]

**Comment by tisonkun** [comment]
cc @hooopo @sykp241095

**Comment by hooopo** [comment]
* activerecord-tidb-adapter  https://github.com/pingcap/activerecord-tidb-adapter 
* Demo repo for Rails 6.1.4 with activerecord-tidb-adapter: https://github.com/hooopo/activerecord-tidb-adapter-demo
* ActiveRecord and TiDB compatibility test: https://github.com/tidb-incubator/rails
* CI for ActiveRecord and TiDB compatibility test: https://buildkite.com/hooopo

**Comment by tisonkun** [comment]
@hooopo do you have ideas about the progress when we can close this issue and mark the support of Active Record as delivered?

**Comment by hooopo** [comment]
The current version is delivered, but it needs long-term maintenance, and many things need to be improved

**Comment by tisonkun** [comment]
@hooopo get it. We can track further issues on that repo instead. For confirming we delivered a minimal viable product, could you comment below an example or demo for running TiDB with Active Record? I think then we can close this issue as finished.

**Comment by hooopo** [comment]
This is demo app using activerecord-tidb-adapter:  https://github.com/hooopo/activerecord-tidb-adapter-demo

**Comment by tisonkun** [comment]
@hooopo Thanks! I'm going to close this one and create an issue on https://github.com/pingcap/activerecord-tidb-adapter asking for a brief tutorial on how to build the demo app.

**Comment by tisonkun** [comment]
closed and superseded by https://github.com/pingcap/activerecord-tidb-adapter/issues/6
