### ISSUE TITLE
Add a switch for alter table/partition attributes

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb#27057]
## Development task

We need a switch to enable/disable the region label feature. Perhaps, adding a new global variable named `tidb_enable_alter_attributes` is enough.

**Comment by bb7133** [comment]
Hi @rleungx what is the use case of this variable. WIll it be removed after the feature is stable enough?

**Comment by rleungx** [comment]
> Hi @rleungx what is the use case of this variable. WIll it be removed after the feature is stable enough?

I'm going to hold this variable for now. It depends on the testing results. If it is stable enough before the end of the next sprint, I won't add this switch.

**Comment by rleungx** [comment]
The switch is not necessary and I'm going to close this issue.
