### ISSUE TITLE
Reduce the memory resources required for Sort Spilling

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#27069]
## Enhancement

Now SortExec supports spilling when memory usage is higher than mem-quota, but is still allocate a lot of untracked memory.

Here is a example, which can be used to analyze the memory usage of Sort Spilling.
![image](https://user-images.githubusercontent.com/14054293/128830962-a6907a3f-1eba-40e3-a201-1fa805abda9b.png)
 
After the tracking code, I find the memory allocated by the following code:
https://github.com/pingcap/tidb/blob/b24d8b7b96501601447270d7835897b99044ecb2/util/chunk/row_container.go#L431

And 
https://github.com/pingcap/tidb/blob/b24d8b7b96501601447270d7835897b99044ecb2/util/chunk/disk.go#L236

Every time a row of data is spilled, we need a rowPtr(8 Bytes) and an offsetsOfRows(8 Bytes) to ensure that we can read randomly. So when the number of data rows is large, this part of the memory will also be large. 
To make matters worse, if the average data size is less than 16 bytes, the spilling may take up more memory space.

The following questions can be considered:
1. Can the contents of the chunk be reconstructed so that rowptrs can be GC after sorting and spilling?
2. Can we optimize the memory allocation of offsetsOfRows, when we only need to read the data sequentially？Or spilling offsetsOfRows when we need to read the data randomly?

**Comment by fidelis-C** [comment]
Woo
