### ISSUE TITLE
migrate test-infra to testify for `store`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27142]
* [x] #27652
* [x] #27653
* [x] #27654
* [x] #27655
* [x] #27656
* [x] #27657

**Comment by sunxiaoguang** [comment]
* [ ] migrate test-infra to testify for store/mockstore
* [ ] migrate test-infra to testify for store/driver
* [ ] migrate test-infra to testify for store/copr
* [ ] migrate test-infra to testify for store/store_test.go
* [ ] migrate test-infra to testify for store/helper/helper_test.go
* [ ] migrate test-infra to testify for store/gcworker/gc_worker_test.go

**Comment by sunxiaoguang** [comment]
Hi @tisonkun, we may create sub issues for this package to break them into smaller tasks.

**Comment by tisonkun** [comment]
Thanks for your prepare. Updating...

**Comment by tisonkun** [comment]
closed as all subtasks done.
