### ISSUE TITLE
migrate test-infra to testify for `statistics`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27141]
* [x] #28116
* [x] #28117
* [x] #28118
* [x] #28119
* [x] #28120
* [x] #28121
* [x] #28122
* [x] #28123
* [x] #28124
* [x] #28125
* [x] #28126
* [x] #28127
* [x] #28128
* [x] #28129
* [x] #28130
* [x] #28131

**Comment by feitian124** [comment]
knowlege about statistics
https://github.com/pingcap/tidb-dev-guide/pull/70

**Comment by feitian124** [comment]
hi @tisonkun , please splite this task to sub tasks for me

**Comment by tisonkun** [comment]
@feitian124 ok. Do you have a plan how to split the tasks? In files?

**Comment by feitian124** [comment]
ok, it is fine.
2 small files and 2 large files, you can adjust.
```shell
❯ find statistics -name "*_test.go" -exec sh -c '[ -f "$0" ] && printf "%6s\t\t%s\n" "$(wc -l<"$0")" "$0"' {} \;
    42          statistics/analyze_jobs_test.go
   308          statistics/sample_test.go
   316          statistics/feedback_test.go
   264          statistics/scalar_test.go
   467          statistics/histogram_test.go
   108          statistics/fmsketch_test.go
   483          statistics/integration_test.go
   715          statistics/statistics_test.go
   307          statistics/cmsketch_test.go
   264          statistics/handle/ddl_test.go
  3075          statistics/handle/handle_test.go
  2331          statistics/handle/update_test.go
   136          statistics/handle/gc_test.go
    50          statistics/handle/update_list_test.go
   340          statistics/handle/dump_test.go
   966          statistics/selectivity_test.go
```

**Comment by tisonkun** [comment]
ok. I will create all these files for you. You can assign them to yourself.

**Comment by feitian124** [comment]
cheers :tada: 
`statistics` are almost done, next step is `statistics/handle`, hopefully finish in 2 weeks.
after that, i wish could allocate some time to do none-test-migrate tasks besides migrate tasks.

@tisonkun

**Comment by feitian124** [comment]
there are still lots todo,  `325` todo, `736` in total, in which about `30` cases are from parser package.
```sh
❯ find . -name "*_test.go" -not -path "./vendor/*"  | xargs grep "github.com/pingcap/check" | wc -l
325
❯ find . -name "*_test.go" -not -path "./vendor/*"  | wc -l
736

❯ find parser -name "*_test.go"   | wc -l
30
❯ find parser -name "*_test.go"   | xargs grep "github.com/pingcap/check" | wc -l
27

```
