### ISSUE TITLE
migrate test-infra to testify for `br/pkg`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27178]
* [x] #28164
* [x] #28165
* [x] #28166
* [x] #28167
* [x] #28168
* [x] #28169
* [x] #28170
* [x] #28171
* [x] #28172
* [x] #28173
* [x] #28174
* [x] #28175
* [x] #28176
* [x] #28177
* [x] #28178
* [x] #28179
* [x] #28180
* [x] #28181
* [x] #28182
* [x] #28183
* [x] #28184

**Comment by tisonkun** [comment]
`br` is original `pingcap/br`, we should break down more subtasks.

**Comment by YuJuncen** [comment]
Some analyses 🤔

### General

The most simple way for adapting go check is to use the [`suite` interface](https://pkg.go.dev/github.com/stretchr/testify/suite#SetupAllSuite) of `testify`: replace the call of `c.Assert` with corresponding `testify` method.

Some of "stateless" tests, which:
1. Has a suite of type `struct{}`
2. Defined nop lifecycle methods.

...can be refactored as plain go test cases.

### Suites

The [lifecycle methods](https://labix.org/gocheck#fixtures) of `gocheck` can be adapted via:
|testify|gocheck|
|---|---|
|`SetupSuite`|`SetUpSuite`|
|`SetupTest`|`SetUpTest`|
|`TearDownTest`|`TearDownTest`|
|`TearDownSuite`|`TearDownSuite`|

### Checkers

The following `Checker` are used by BR:
```go
BytesEquals // can be replaced with require.Equal
DeepEquals // same as above
Equals // same as above
// Reason see https://github.com/stretchr/testify/blob/acba37e5db06f0093b465a7d47822bf13644b66c/assert/assertions.go#L58-L76 

ErrorMatches // require.EqualError
FieldEquals // custom checker, using `zapcore.Field.Equals`
FitsTypeOf // maybe require.IsType
Greater // require.Greater
GreaterEqual // require.GreaterOrEqual
HasKey // ?
HasLen // require.Len
IsFalse // require.False
IsNil // require.Nil
IsTrue // require.True
Less // require.Less
LessEqual // require.LessOrEqual
Matches // require.Regexp?
Not // testify didn't support `Checker`, let alone combinators over them...
NotNil // require.NotNil
PanicMatches // maybe require.PanicsWith{Error,Object}?
RangeEquals // custom checker, checking the start key and end keys are equal.
isAbout // custom checker, checking whether two floating numbers are near enough.
jsonEquals // require.JSONEq
posEq // custom checker, checking the pos of a parser.
unblocksBetween // custom checker, checks whether a wait group done in a time interval. 
versionEquals // custom checker for semvers.
```

Some of the checkers has alternative methods in `Assertions` from `testify`. For custom checkers, we may make functions like `posEq(t *testing.T, <arg list of checker>, interface{}... msgAndArgs)`, and delegate the check to methods in `require`.

### `Commentf(...)`

Each assertions from `testify` accepts a sequence of `msgAndArgs`, the items in `Commentf` can be placed here.

### the possibility of auto migration

Given a normal test file here, we can migrate it from `gocheck` to `testify` via:

1. Check the test suite in the file(unexpectedly, some files may contains more than one or no suites).
2. if it is a "stateless" suite, do:
  a. remove the test suite.
  b. remove the accepter of test functions bound to this suite.
  c. replace the argument `c *C` with `t *testing.T`.
  d. replace calling to `c.Assert` with corresponding method in `testify`.
  e. if (d) meets a checker cannot be converted to method in `testify`, leave a hole here and hint the user, like:
```go
// TODO impl the custom checker
TODO_posEq(t, ...)
```
3. if it is a "stateful" suite, do:
  a. compose a `testify.Suite` in to the test suite.
  b. rename the lifecycle methods bound to the suite.
    (accessing to the `c` might would be fixed manually.)
  c. do the same thing for assertions as stateless test cases.

These steps (maybe?) are deterministic, which means it's possible to write a script with `go/ast` and `go/parser` to automate them. 🤔

Or we can also do these things manually, as a refinement or inspection of our test cases.

**Comment by tisonkun** [comment]
> The most simple way for adapting go check is to use the suite interface of testify

@YuJuncen No. We don't do that. Please see also https://github.com/pingcap/tidb/pull/26082#issuecomment-877230972 and this [Chinese post](https://mp.weixin.qq.com/s/8q776_5ZZDwA1IX_m-q1CQ) for details. And https://github.com/pingcap/tidb/pull/27747 for an example.

**Comment by tisonkun** [comment]
@YuJuncen @feitian124 already creates a tool you may make use of to automatically migrate https://github.com/pingcap/tidb/issues/26022#issuecomment-898806106 . However, I'd prefer just do it manually with some "global find and replace" for common pattern.

If you try to do something automatically and correctly, you're always in trouble - you're now find a new, and probably huge, question to resolve, which is unnecessary to the original problem.

**Comment by tisonkun** [comment]
> Commentf(...)

Just use `require.Equalf` and `require.Greaterf`.

**Comment by tisonkun** [comment]
Also, it is not a 1 to 1 mapping as `c.Assert(err, IsNil)` is almost `require.NoError(t, err)`, but `c.Assert(sth, IsNil)` is `require.Nil(t, sth)`. We don't push the migration to one man or two, as you see; we run it with join force and for `br` topic the current problem is to find a proper separation: possibly in packages or files.

If you can find such one, I'm glad to update the description and create subtasks.

**Comment by tisonkun** [comment]
The first thing I found is that these tests are all under `br/pkg`

**Comment by YuJuncen** [comment]
@tisonkun 
For suites: Well, if suite isn't acceptable, maybe TestMain can help to set up a test. 
For automating: Maybe refactor tools like [`eg`](https://pkg.go.dev/golang.org/x/tools/refactor/eg) can help?

**Comment by tisonkun** [comment]
> For automating: Maybe refactor tools like eg can help?

You're welcome to try on a subtask 😄

**Comment by tisonkun** [comment]
Closed as all subtasks done.
