### ISSUE TITLE
migrate test-infra to testify for `bindinfo` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27177]

**Comment by tisonkun** [comment]
Hi @w169q169 , is there any progress on this issue?

**Comment by w169q169** [comment]
> Hi @w169q169 , is there any progress on this issue?

I'm working on it, but this package need too much work  (65 test func and 417 assert statements). My plan is submitting changes in several stages(may be 4-5 pr).
1. split into serveral file(origin test file is too big and new tests is added on the same time)
2.  migrate some old tests in old file(bind_test.go) in new file
3.  submit a pr 
4. repeat ste-2,step-3

**Comment by tisonkun** [comment]
@w169q169 thanks for your updates! That makes sense for me. Yes I'd like to split into multiple test files also. Please let me know when you create the first PR. And ask for me updating the issue description if necessary.

**Comment by tisonkun** [comment]
@w169q169 hi! I'd like to take the part of `testSerialSuite` so that we get rid of one of the suites.

**Comment by w169q169** [comment]
@tisonkun  okay,  you  do the part of `testSerialSuite` as your wish . I will continue the remaining part.
