### ISSUE TITLE
migrate test-infra to testify for `ddl` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27180]
- [x] #27669
- [x] #27670
- [x] #27671
- [x] #27672
- [x] #28628
- [x] #28629
- [x] #28630
- [x] #28631
- [x] #28632
- [x] #30086
- [x] #28633
- [x] #28634
- [x] #28635
- [x] #28636
- [x] #28637
- [x] #28638
- [x] #28639
- [x] #29102
- [x] #29103
- [x] #29104
- [x] #29105
- [x] #29106
- [x] #29107
- [x] #29108
- [x] #29109
- [x] #29110
- [x] #29111
- [x] #29112
- [x] #29113
- [x] #29114
- [x] #29115
- [x] #29116
- [x] #31844
- [x] #32843

**Comment by tisonkun** [comment]
@karuppiah7890 glad to see you working on this!

`ddl` is one of our most complicated packages and domains. Even if we just do tests migration, I suggest you start from child package like `ddl/label`, `ddl/placement`, etc.

You can collaborate with me as how @yadamao did https://github.com/pingcap/tidb/issues/27618#issuecomment-907790848 .

**Comment by karuppiah7890** [comment]
Sure! Thanks @tisonkun ! I did think that this might be a hard one, looking at no one assigned themselves to it yet. I was planning on checking the package today to understand if it needs more subtasks, as I noticed more sub tasks for other issues. Looks like it does. I'll start from small packages that you mentioned 👍

I'll also note down all the test files and sub packages so that we can create sub tasks? Either GitHub issues or put a list in this issue as task list

**Comment by tisonkun** [comment]
> I'll also note down all the test files and sub packages so that we can create sub tasks? Either GitHub issues or put a list in this issue as task list

Either https://github.com/pingcap/tidb/issues/27618#issuecomment-907790848 or https://github.com/pingcap/tidb/issues/27142#issuecomment-907813161 is ok for me.

**Comment by karuppiah7890** [comment]
Hoping we won't have too much complex things to comment in the GitHub issues, I'll choose to create just subtasks here for now for easy managment instead of creating too many GitHub issues. But yeah, while creating PRs, we can't close this issue with `Fixes #...`. Let's see. First let me create a list like this - https://github.com/pingcap/tidb/issues/27142#issuecomment-907813161

**Comment by karuppiah7890** [comment]
Ah, https://github.com/pingcap/tidb/issues/27142#issuecomment-907813161 also has subtasks as GitHub issues, okay!

**Comment by karuppiah7890** [comment]
File level list that we need to migrate

- [ ] ddl/attributes_sql_test.go
- [ ] ddl/callback_test.go
- [ ] ddl/column_change_test.go
- [ ] ddl/column_test.go
- [ ] ddl/column_type_change_test.go
- [ ] ddl/db_change_test.go
- [ ] ddl/db_integration_test.go
- [ ] ddl/db_partition_test.go
- [ ] ddl/db_test.go
- [ ] ddl/ddl_algorithm_test.go
- [ ] ddl/ddl_test.go
- [ ] ddl/ddl_worker_test.go
- [ ] ddl/fail_test.go
- [ ] ddl/failtest/fail_db_test.go
- [ ] ddl/foreign_key_test.go
- [ ] ddl/index_change_test.go
- [ ] ddl/label/attributes_test.go
- [ ] ddl/label/rule_test.go
- [ ] ddl/options_test.go
- [ ] ddl/partition_test.go
- [ ] ddl/placement_sql_test.go
- [ ] ddl/placement/bundle_test.go
- [ ] ddl/placement/common_test.go
- [ ] ddl/placement/constraint_test.go
- [ ] ddl/placement/constraints_test.go
- [ ] ddl/placement/rule_test.go
- [ ] ddl/reorg_test.go
- [ ] ddl/restart_test.go
- [ ] ddl/rollingback_test.go
- [ ] ddl/schema_test.go
- [ ] ddl/sequence_test.go
- [ ] ddl/serial_test.go
- [ ] ddl/stat_test.go
- [ ] ddl/table_split_test.go
- [ ] ddl/table_test.go
- [ ] ddl/testutil/testutil.go
- [ ] ddl/util/syncer_test.go

Package level / directory level list that we need to migrate

- [ ] ddl
- [ ] ddl/failtest
- [ ] ddl/label
- [ ] ddl/placement
- [ ] ddl/testutil
- [ ] ddl/util

**Comment by tisonkun** [comment]
@karuppiah7890 thanks for your prepare. Updating...

**Comment by tisonkun** [comment]
@karuppiah7890 I created issues for all child packages. For files, I'd like to postpone a bit until you'd actually work on it. Maybe follow https://github.com/pingcap/tidb/issues/27618#issuecomment-907790848 and ask me to update the description, or ask me to create the issues.

**Comment by karuppiah7890** [comment]
I removed my assignment @tisonkun

**Comment by tisonkun** [comment]
@zimulala @tangenta I just notice that many tests under `ddl` package are tightly coupled and hardly break down to deal with one by one. Could you please take a look?

**Comment by hawkingrei** [comment]
Please add #30086 to the issue description.

**Comment by hawkingrei** [comment]
> @zimulala @tangenta I just notice that many tests under `ddl` package are tightly coupled and hardly break down to deal with one by one. Could you please take a look?

OK, I will.

**Comment by tisonkun** [comment]
> Please add #30086 to the issue description.

Updated.

**Comment by Adam-Kulju** [comment]
@tisonkun  Migrating schema_test, stat_test, and table_test to testify all spill over into restart_test so those will all have to be done at once I think. I'm working on them right now, hopefully restart_test won't end up spilling over into even more tests (if that's the case I'll probably give up).

> @karuppiah7890 I created issues for all child packages. For files, I'd like to postpone a bit until you'd actually work on it. Maybe follow [#27618 (comment)](https://github.com/pingcap/tidb/issues/27618#issuecomment-907790848) and ask me to update the description, or ask me to create the issues.

**Comment by GOODBOY008** [comment]
Hi,@tisonkun . testkit.go and testkit_test.go should migrate test-infra to testify too.

**Comment by tisonkun** [comment]
@GOODBOY008 I don't know what you mean. There is no such file in `ddl` package. If you mean that in `util/testkit` folder, please see its successors in `testkit` folder.

Also, existing migration examples should help.

**Comment by GOODBOY008** [comment]
> 

I got it.Thanks your patience explanation!

**Comment by xhebox** [comment]
#31844 is added to the task list, which is introduced by tiflash guys.

**Comment by tisonkun** [comment]
Finally we finish it! Closed as all subtasks resolved.
