### ISSUE TITLE
transaction: forbid a txn to read using a ts before GC safepoint.

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#2718]
There is potential risk in two cases:
a) user provides a too old timestamp for history read.
b) a txn runs really long and exceeds _gcLifetime_. It won't get successfully committed, but it may still read incomplete data.

**Comment by morgo** [comment]
@disksing @AndreMouche I am pretty sure this is fixed?  If I try and run a backup that takes longer than `tikv_gc_life_time`, I will get an error like this one: https://github.com/pingcap/tidb/issues/8896

I am going to close this issue now, but please re-open if I am in error.

**Comment by disksing** [comment]
@morgo Yes! It's already fixed.
