### ISSUE TITLE
TiDB modify column error

### ISSUE THREAD

**Issue by cwen0** [pingcap/tidb#2719]
Error log: 
[error] exec sqls[[use `database_name`; ALTER TABLE `table_name` MODIFY COLUMN `id` int(11) NOT NULL AUTO_INCREMENT;]] failed Error 1105: unsupported modify column

Exec sql: 
[query]ALTER TABLE `table_name` MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5

**Comment by zimulala** [comment]
It's duplicated with #2266
