### ISSUE TITLE
why tpch query is quit slowly

### ISSUE THREAD

**Issue by hzxjtx** [pingcap/tidb#2723]
hi,
   I use 6 machines(32core, 64g), and multi product mode, just like this
Name	Host IP	Services
node1	192.168.199.113	PD1, TiDB
node2	192.168.199.114	PD2
node3	192.168.199.115	PD3
node4	192.168.199.116	TiKV1
node5	192.168.199.117	TiKV2
node6	192.168.199.118	TiKV3

but when i use tpch(1g data) for query, the executor is so cost time.

the sql1 query cost 48s, but on postgres only cost 3s
can some one give me some information

**Comment by shenli** [comment]
@hzxjtx Thanks for your feedback. 
We have never tested tpc-h on TiDB. We will check it out.
