### ISSUE TITLE
BR should retry timed out scatter operators in huge clusters

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#27231]
## Enhancement
Currently, BR has a loose strategy for failures during scattering. In huge clusters, this may lead to an unbalanced cluster, hence not all nodes would execute the restore then the speed of restoration would slow down, moreover because of the skew of data, the performance after restore would be lower.

The figure shows an example of an unbalanced restore, where the TiKV-{3,5,8} contains 4x more data than other nodes.
<img width="308" alt="image" src="https://user-images.githubusercontent.com/36239017/129501951-249db6cb-6b20-4803-b698-8a6d65ee9fdb.png">

## roadmap

We check whether the region has been scattered here:

https://github.com/pingcap/tidb/blob/master/br/pkg/restore/split.go#L217-L220

Also, the scatter command was sent here:

https://github.com/pingcap/tidb/blob/master/br/pkg/restore/split.go#L131

Even there is a tight coupling between split & scatter. When retrying, we can retry scatter only. For example, call `RegionSplitter.ScatterRegions` after a "timed out" error found would be fine.

**Comment by okJiang** [comment]
I found that this requirement has already been implemented. If needed, please feel free to reopen it.
