### ISSUE TITLE
How to generate docker-compose. yaml from helm

### ISSUE THREAD

**Issue by zhankenson** [pingcap/tidb#27324]
## General Question

![image](https://user-images.githubusercontent.com/8385159/129835319-071d2bf2-3c18-4262-b9d0-ce3002d023e0.png)
https://docs.pingcap.com/zh/tidb/v3.0/deploy-test-cluster-using-docker-compose

**Comment by sunxiaoguang** [comment]
Hi @zhankenson, thanks for asking. Using docker compose was deprecated and not supported. I highly recommend trying tiup instead which was documented pretty well at [here](https://docs.pingcap.com/zh/tidb/dev/quick-start-with-tidb).  

Besides, if you really want to try docker-compose instead. The error message looks like something is wrong with download link or maybe network connection that preventing you from downloading compose. Please check document of the helm version you are using and make sure it doesn't make breaking changes rendering this command invalid.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
