### ISSUE TITLE
SetDDLErrorCountLimit doesn't work in tests

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#27334]
## Bug Report

The following code does not work in `countForPanic`.
```
TestCreateTableNoBlock
...
	save := variable.GetDDLErrorCountLimit()
	variable.SetDDLErrorCountLimit(1)
	defer func() {
		variable.SetDDLErrorCountLimit(save)
	}()
...
```

We need use `set @@global.tidb_ddl_error_count_limit = 1` instead of above code. In addition, there are quite a few places in the test where the above code is used, all of which need to be handled.

After the change, the test execution will be faster.

**Comment by tisonkun** [comment]
@unconsolable do you know which version this issue affects or should be backported?

**Comment by unconsolable** [comment]
> @unconsolable do you know which version this issue affects or should be backported?

I think it may not need to be backported, as all changes are made in test files.

**Comment by tisonkun** [comment]
> > @unconsolable do you know which version this issue affects or should be backported?
> 
> I think it may not need to be backported, as all changes are made in test files.

It doesn't the reason. Unstable test, if exists on release branch, could be also backported. Does this issue only affects master and fixed in master? cc @zimulala

**Comment by zimulala** [comment]
@tisonkun 
This is only in the test, and it does not affect the stability of the test, only the test execution time (the test execution time is relatively long without the fix). So I think we don't have to do any extra processing.
