### ISSUE TITLE
ERROR 8214 (HY000): Cancelled DDL job

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#27384]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
set @@tidb_enable_list_partition=on;
drop table if exists t3;
create table t3 (a char, b char) partition by list columns (a) (
    partition p0 values in ('z')
);
alter table t3 drop column a;
```

### 2. What did you expect to see? (Required)
```
mysql> alter table t3 drop column a;
ERROR 1054 (42S22): Unknown column 'a' in 'expression'
```

### 3. What did you see instead (Required)
release-5.0 & release-5.1 & release-5.2 & master
```
mysql> alter table t3 drop column a;
ERROR 8214 (HY000): Cancelled DDL job
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.2.0-alpha-567-gdba8e111f
Edition: Community
Git Commit Hash: dba8e111fe26b1db0742dd5a024309137d49f5d2
Git Branch: release-5.2
UTC Build Time: 2021-08-19 02:02:03
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by Defined2014** [comment]
It works well on master [84871df](https://github.com/pingcap/tidb/commit/84871df1903db9b65a5586871d56fee9e19e6453) which error msg is same as expect, so close this issue.
