### ISSUE TITLE
Support more sql_mode

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#2738]
SQL_Mode is important in MySQL. We should handle more modes, for example 'ANSI_QUOTES'.
See https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html

**Comment by morgo** [comment]
Every sql_mode is supported *except* the deprecated modes, with one exception: `ALLOW_INVALID_DATES`.  I suggest that we add it just so we can say we have full compatibility.

**Comment by morgo** [comment]
There is now a [dedicated issue](https://github.com/pingcap/tidb/issues/8263) for `ALLOW_INVALID_DATES`, so I am going to close this issue now.

Please feel free to re-open if you have any followup questions.  Thanks!
