### ISSUE TITLE
br slow to fail when PD requires TLS but no tls options given

### ISSUE THREAD

**Issue by kolbe** [pingcap/tidb#27415]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster using tiup with `enable_tls: true`
2. execute br without giving TLS options (`--ca`, `--cert`, `--key`)

### 2. What did you expect to see? (Required)

br should *fail fast* and *communicate to the user* that TLS is required for the connection.

### 3. What did you see instead (Required)

br takes nearly 2 minutes to fail, and gives a useless error message after that time.

```
ubuntu@ip-10-0-18-150:~$ time tiup br backup full --storage file:///tmp
Starting component `br`: /home/ubuntu/.tiup/components/br/v5.1.1/br backup full --storage file:///tmp
Detail BR log in /tmp/br.log.2021-08-20T00.04.33Z
[2021/08/20 00:06:13.178 +00:00] [INFO] [collector.go:66] ["Full backup failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: [pd] failed to get cluster id
Error: run `/home/ubuntu/.tiup/components/br/v5.1.1/br` (wd:/home/ubuntu/.tiup/data/Sga7L7h) failed: exit status 1

real    1m40.621s
user    0m0.143s
sys     0m0.026s
```

### 4. What is your TiDB version? (Required)
```
Starting component `br`: /home/ubuntu/.tiup/components/br/v5.1.1/br --version
Release Version: v5.1.1
Git Commit Hash: a34cc3d1d3aad1e31c423039f976b5ec90b82339
Git Branch: heads/refs/tags/v5.1.1
Go Version: go1.16.4
UTC Build Time: 2021-07-23 01:15:16
Race Enabled: false
```

**Comment by joccau** [comment]
It get pd failed with pd address for retry 100 times( one second per retry).
