### ISSUE TITLE
Import existing table

### ISSUE THREAD

**Issue by winkmichael** [pingcap/tidb#2742]
Trying to run this command on creating a new table

```
- MySQL dump 10.13  Distrib 5.7.11, for Linux (x86_64)
--
-- Host: localhost    Database: database
-- ------------------------------------------------------
-- Server version       5.7.11

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
```

I get this error;

```
cat database.sql |  mysql -h 127.0.0.1 -P 4000 -u root
ERROR 1105 (HY000) at line 26: line 6 column 15 near "" (total length 140)
```

Line  6 is a blank line...

**Comment by shenli** [comment]
@winkmichael Thanks for your feedback!
Could you send me the log of tidb-server?

**Comment by coocood** [comment]
The sets statements missing a `*`, should be `/*!` instead of `/!`.

**Comment by winkmichael** [comment]
File is produced by mysqldump

**Comment by coocood** [comment]
@winkmichael 
Sorry, I misunderstood your issue because the `*` is eaten by Markdown format.
I clicked `edit` button, then got the original text.

The error message `line 6` is the line of a single statement, not the file.
So the statement that failed to parse is not included, probably it's the CREATE TABLE statement.

Do you still have that dump file?

**Comment by kolbe** [comment]
@winkmichael we haven't heard anything from you on this issue in a long time, and we're unable to reproduce it without some more information, so I'm going to close it now. If you run into anything like this again, please open up a new issue and we'll be happy to take a look!
