### ISSUE TITLE
Timeout test `tidb_test.go:878: tidbTestSerialSuite.TestTLSAuto`

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#27450]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```

[2021-08-20T02:51:07.196Z] PASS: tidb_test.go:878: tidbTestSerialSuite.TestTLSAuto	6.702s
```
### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/27658/pipeline

**Comment by bb7133** [comment]
Close this issue since the timeout limitation has been removed.
