### ISSUE TITLE
Keep client connection alive while upgrading TIDB server.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#2745]
When upgrading TiDB server, we need to kill the process, then all the client connection will be closed, this may cause a large amount of query failure.

If we frequently updating TiDB server, this problem would make our users reluctant to upgrade, leave bugs in production.

One way to solve this problem is to use a local proxy which parses client query, and send to local TiDB server. 

The local proxy only has the minimum functionality, so it never needs to upgrade.

When we need to upgrade TiDB, the local proxy can forward client query to other TiDB servers, so the client never fails a query.

**Comment by ngaut** [comment]
I noticed that go and java provide something like maxConnectionLifetime, and the drivers handle the lifetime of connection very well. I guess we can simplify use this feature to support rolling upgrade.

**Comment by coocood** [comment]
@ngaut That is set by the user which we cannot control.
Most of the user do not set this parameter.

**Comment by morgo** [comment]
I think most users will have a proxy layer above TiDB.

As an alternative to keeping a connection open during maintenance, we could recommend proxies use the status port to check if a TiDB server is accepting __new connections__.  We could then wait up to 60 seconds to drain existing connections before forcefully shutting down.

It also makes sense to integrate this behavior with the `SHUTDOWN` command ( https://github.com/pingcap/tidb/issues/5046 ).  Potentially extending it to be `SHUTDOWN [NOW|GRACEFULLY]`.

**Comment by morgo** [comment]
A graceful wait during shutdown was added in https://github.com/pingcap/tidb/pull/20649 - it is not the same as what is described here, but can help in some of the same scenarios where tidb services needed to be rolling rotated out.

**Comment by djshow832** [comment]
Close it because we have [tiproxy](github.com/pingcap/tiproxy).
