### ISSUE TITLE
select use index merge return error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#27496]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tidb config:
new_collations_enabled_on_first_bootstrap: true

sql:
CREATE TABLE `tbl_61` (
  `col_405` binary(97) NOT NULL DEFAULT 'KGNIlmUZZdpMksaAec',
  `col_406` blob NOT NULL,
  `col_407` tinyint(3) unsigned NOT NULL DEFAULT '14',
  `col_408` tinyint(3) unsigned DEFAULT NULL,
  `col_409` bigint(20) NOT NULL DEFAULT '7571122415100149530',
  `col_410` time NOT NULL,
  `col_411` tinyint(1) NOT NULL DEFAULT '1',
  `col_412` bigint(20) DEFAULT '-442888255964125121',
  PRIMARY KEY (`col_410`,`col_411`,`col_405`,`col_407`,`col_406`(4),`col_409`) clustered,
  KEY `idx_374` (`col_407`,`col_405`,`col_409`,`col_408`,`col_412`),
  UNIQUE KEY `idx_375` (`col_406`(3),`col_412`,`col_411`,`col_407`,`col_408`,`col_405`),
  UNIQUE KEY `idx_376` (`col_408`,`col_407`)
);
CREATE TABLE `tbl_26` (
  `col_179` float NOT NULL DEFAULT '7707.736092164511',
  `col_180` timestamp NOT NULL,
  `col_181` timestamp NULL DEFAULT NULL,
  `col_182` set('Alice','Bob','Charlie','David') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `col_183` date NOT NULL DEFAULT '1971-09-15',
  `col_184` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`col_179`,`col_183`,`col_180`,`col_184`(5)) clustered,
  KEY `idx_130` (`col_179`,`col_180`,`col_182`,`col_181`),
  KEY `idx_131` (`col_184`(2),`col_183`,`col_181`),
  UNIQUE KEY `idx_132` (`col_181`,`col_179`),
  KEY `idx_133` (`col_184`(2),`col_183`,`col_182`,`col_180`,`col_179`),
  KEY `idx_134` (`col_181`,`col_179`,`col_183`,`col_182`),
  UNIQUE KEY `idx_135` (`col_183`,`col_179`,`col_181`),
  UNIQUE KEY `idx_136` (`col_181`,`col_179`,`col_184`(4),`col_183`,`col_182`),
  KEY `idx_137` (`col_180`)
);

set @@tidb_enable_index_merge=1;
select   tbl_26.col_179, tbl_26.col_180, tbl_26.col_181, tbl_26.col_182, tbl_26.col_183, tbl_26.col_184 from tbl_26 where col_184 in ( select col_406 from tbl_61 where not( tbl_61.col_410 not in ( '11:16:59.00' , '10:30:09.00' , '00:54:36.00' , '15:39:33.00' ) ) or not( IsNull( tbl_26.col_180 ) ) and not( tbl_61.col_407 in ( 126 , 28 , 55
) ) ) order by tbl_26.col_179,tbl_26.col_180,tbl_26.col_181,tbl_26.col_182,tbl_26.col_183,tbl_26.col_184 limit 148;
```

### 2. What did you expect to see? (Required)

success

### 3. What did you see instead (Required)

return error，as follow:

mysql> select   tbl_26.col_179, tbl_26.col_180, tbl_26.col_181, tbl_26.col_182, tbl_26.col_183, tbl_26.col_184 from tbl_26 where col_184 in ( select col_406 from tbl_61 where not( tbl_61.col_410 not in ( '11:16:59.00' , '10:30:09.00' , '00:54:36.00' , '15:39:33.00' ) ) or not( IsNull( tbl_26.col_180 ) ) and not( tbl_61.col_407 in ( 126 , 28 , 55
    -> ) ) ) order by tbl_26.col_179,tbl_26.col_180,tbl_26.col_181,tbl_26.col_182,tbl_26.col_183,tbl_26.col_184 limit 148;
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

### 4. What is your TiDB version? (Required)

only occur on release-5.0,version is:
Release Version: v5.0.0-nightly
Edition: Community
Git Commit Hash: dbc8017af9d4c75d53edeb0cd86901dbf885e198
Git Branch: heads/refs/tags/v5.0.0-nightly
UTC Build Time: 2021-08-22 21:43:37
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by xuyifangreeneyes** [comment]
@vivid392845427 #24061 has cherry-picked #23988 to release-5.0 so the error has been fixed on release-5.0. Can we close the issue now?
