### ISSUE TITLE
`Load data ...` don't work

### ISSUE THREAD

**Issue by snail2swift** [pingcap/tidb#2752]
1. What did you do?
Server version: 5.7.1-TiDB-1.0 MySQL Community Server (GPL)
mysql> load data infile '/tmp/std_pro_iver_cha_rso_event.txt' into table std_pro_iver_cha_rso_event fields TERMINATED by '|';

2. What did you expect to see?

3. What did you see instead?
ERROR 1105 (HY000): Load Data: don't support load data without local field

4. What version of Go are you using (`go version`)?

**tidb-server log:**

2017/02/28 11:05:21 session.go:511: [warning] [21] session error:
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/write.go:545: Load Data: don't support load data without local field
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/adapter.go:143: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/tidb.go:186: 
{
  "currDBName": "test",
  "id": 21,
  "stauts": 2,
  "strictMode": true,
  "user": "root@xxxx"
}
2017/02/28 11:05:21 conn.go:355: [warning] [21] dispatch error:
id:21, addr:xxxxx:47923 status:2, collation:utf8_general_ci, user:root
load data infile '/tmp/std_pro_iver_cha_rso_event.txt' into table std_pro_iver_cha_rso_event fields TERMINATED by '|'
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/write.go:545: Load Data: don't support load data without local field
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/adapter.go:143: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/tidb.go:186: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:513: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:660:

**Comment by zimulala** [comment]
@snail2swift  We don't support load data without `local` field. You can change the statement like this ` load data local infile '/tmp/std_pro_iver_cha_rso_event.txt' into table std_pro_iver_cha_rso_event fields TERMINATED by '|';`.

**Comment by snail2swift** [comment]
@zimulala 
mysql> load data local infile '/tmp/std_pro_iver_cha_rso_event.txt' into table std_pro_iver_cha_rso_event fields TERMINATED by '|';
ERROR 1148 (42000): the used command is not allowed with this TiDB version

**Comment by zimulala** [comment]
@snail2swift  Could you show me the result of tidb-server -V ?

**Comment by snail2swift** [comment]
@zimulala 
Git Commit Hash: 0282310e8b2aa286a76be95f9b4558f84def5d05
UTC Build Time:  2017-02-23 07:19:58

**Comment by zimulala** [comment]
@snail2swift Start some MySQL clients need to add `--local-infile=1` option.  The start MySQL client command like `mysql --local-infile=1 -u root -h 127.0.0.1 -P 4000`.

**Comment by snail2swift** [comment]
@zimulala This problem has been solved,thx!
