### ISSUE TITLE
update mode

### ISSUE THREAD

**Issue by YangFW** [pingcap/tidb#27546]
## General Question
tispark  TiBatchWrite data into tidb  like this

`
val df = spark.sql("select * from table1")

df.show(false)

df.write
.format("tidb")
.option("tidb.user", "root")
.option("tidb.password", "******")
.option("database","schema1")
.option("table","table2")
.mode("append")
.save()
`

but went wrong have this
`User class threw exception: com.pingcap.tikv.exception.TiBatchWriteException: currently user provided auto increment value is only supported in update mode!
please set parameter replace to true!`

**Comment by ljluestc** [comment]
Set replace to true:
Modify your code to set the replace option to true. This will enable updating existing records in the target table with the new data. However, please be cautious as this may lead to data overwrite if not used carefully.
```
val df = spark.sql("select * from table1")
df.show(false)

df.write
  .format("tidb")
  .option("tidb.user", "root")
  .option("tidb.password", "******")
  .option("database", "schema1")
  .option("table", "table2")
  .option("replace", "true") // Set the replace option to true
  .mode("append")
  .save()

```
Use the "overwrite" mode:
```
val df = spark.sql("select * from table1")
df.show(false)

df.write
  .format("tidb")
  .option("tidb.user", "root")
  .option("tidb.password", "******")
  .option("database", "schema1")
  .option("table", "table2")
  .mode("overwrite") // Use "overwrite" mode to replace entire table
  .save()

```

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
