### ISSUE TITLE
ERROR :transaction is too large when delete data

### ISSUE THREAD

**Issue by snail2swift** [pingcap/tidb#2755]
What i can do ?

mysql> select count(1) from std_pro_iver_cha_rso_event;
+----------+
| count(1) |
+----------+
|  1460000 |
+----------+
mysql> delete from std_pro_iver_cha_rso_event; 
ERROR 1105 (HY000): transaction is too large

mysql> set autocommit=0;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from std_pro_iver_cha_rso_event;
Query OK, 1460000 rows affected (8.33 sec)

mysql> commit;
ERROR 1105 (HY000): transaction is too large

**Comment by coocood** [comment]
@snail2swift 
We don't support large transaction.
You can limit the count in a delete statement or use `trunacate table`.
