### ISSUE TITLE
dateAdd function bug

### ISSUE THREAD

**Issue by mengxin9014** [pingcap/tidb#27573]
### 1. Minimal reproduce step (Required)
```mysql
drop table t;
create table t(a char(32));
insert into t values('20129');
select a, DATE_ADD(a, INTERVAL 1 day ) from t ; 
```

### 2. What did you expect to see? (Required)
```mysql
+------------+------------------------------+
| a          | DATE_ADD(a, INTERVAL 1 day ) |
+------------+------------------------------+
| 20129      | 2020-12-10                   |
+------------+------------------------------+
```
### 3. What did you see instead (Required)
```mysql
+------------+------------------------------+
| a          | DATE_ADD(a, INTERVAL 1 day ) |
+------------+------------------------------+
| 20129      | 2020-12-10 00:00:00          |
+------------+------------------------------+
```

### 4. What is your TiDB version? (Required)
v5.1.1

**Comment by aytrack** [comment]
> The return value depends on the arguments:
> DATE if the date argument is a DATE value and your calculations involve only YEAR, MONTH, and DAY parts (that is, no time parts).
> DATETIME` if the first argument is a DATETIME (or TIMESTAMP) value, or if the first argument is a DATE and the unit value uses HOURS, MINUTES, or SECONDS.
> String otherwise.

The returning type is wrong.
