### ISSUE TITLE
Ensure {CREATE|ALTER|DROP} PLACEMENT POLICY requires the PLACEMENT_ADMIN privilege

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#27603]
This is a sub-task of Placement Rules in SQL: https://github.com/pingcap/tidb/issues/18030

Support the ability to `CREATE PLACEMENT POLICY` with the same options available in `CREATE TABLE|ALTER TABLE` context.

The following subtasks are known:

* [ ] Ensure {CREATE|ALTER|DROP} PLACEMENT POLICY requires the PLACEMENT_ADMIN privilege
    * [ ] Require CREATE PLACEMENT POLICY with `PLACEMENT_ADMIN`
    * [ ] Require DROP PLACEMENT POLICY with `PLACEMENT_ADMIN`
    * [ ] Require ALTER PLACEMENT POLICY with `PLACEMENT_ADMIN`

**Comment by sylzd** [comment]
It seems can be closed by one pr.
