### ISSUE TITLE
Timeout test `testDDLTableSplitSuite.TestTableSplit`

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#27620]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```

[2021-08-26T02:53:15.432Z] PASS: table_split_test.go:36: testDDLTableSplitSuite.TestTableSplit	8.733s
```

### 1. Minimal reproduce step (Required)
in ci  https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/29283/pipeline/

**Comment by bb7133** [comment]
Close it since the time-out issues are not tracked('5s' is not a limit for now).
