### ISSUE TITLE
migrate test-infra to testify for `store_test.go` & `batch_coprocessor_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27655]

**Comment by SergeyHydra** [comment]
@tisonkun hi! I'm interested in issue. Can i resolve it?

**Comment by tisonkun** [comment]
/assign @SergeyHydra

Thanks for taking over this issue. Go ahead!

**Comment by tisonkun** [comment]
@SergeyHydra do you have a schedule on working for this issue?

**Comment by tisonkun** [comment]
Due to inactive assignee, I'll take over the task. @SergeyHydra you're welcome to participant in the review stage later.
