### ISSUE TITLE
migrate test-infra to testify for `store/helper`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#27656]

**Comment by 3mard** [comment]
Hi 
I'd like to take this

**Comment by tisonkun** [comment]
@3mard thanks for taking over it. Go ahead!

**Comment by tisonkun** [comment]
@3mard  do you have a schedule on working for this issue?

**Comment by 3mard** [comment]
Hi @tisonkun 
Sorry for being late, you can expect a pr by the end of the weekend

**Comment by 3mard** [comment]
Sorry for being late!
