### ISSUE TITLE
Support drop/truncate table when TiKV disk full

### ISSUE THREAD

**Issue by tier-cap** [pingcap/tidb#27665]
## Feature Request
1. When TiKV is disk full, the drop/truncate table should be allowed.

**Describe alternatives you've considered:**
N/A

**Teachability, Documentation, Adoption, Migration Strategy:**
1. When TiKV is disk full, some DML write operations will not be allowed. And for DDL operations with a small amount of writing, it is allowed. But with a huge amount of writing, not allowed.
2. When Drop/Truncate table is blocked because of other ddl with huge writing, then you shoud execute cancel for that ddls who causes blockage. Currently, you can just cancel the `create index` operations.

**Comment by tisonkun** [comment]
@tier-cap is this issue fixed by https://github.com/pingcap/tidb/pull/26302?
