### ISSUE TITLE
tidb doesn't support comments in chinese and navicat can't edit data directly

### ISSUE THREAD

**Issue by xiamw2000** [pingcap/tidb#2772]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1）我用navicat 连接tidb操作的时候，不能在编辑窗口直接修改数据
2）不支持中文注释
3）创建表或者其他的操作，常报1105的错误

2. What did you expect to see?

1）希望能直接在navicat操作数据
2）希望支持中文注释

3. What did you see instead?

4. What version of Go are you using (`go version`)?

**Comment by shenli** [comment]
@xiamw2000 Could you please provide your navicat version and platform?

**Comment by xiamw2000** [comment]
win7 + navicat premium 10.0.9

**Comment by shenli** [comment]
Could you try the latest navicat?

**Comment by xiamw2000** [comment]
sorry , my os is centos6 ,  pls tell me tidb support comments in chinese?  which version

**Comment by shenli** [comment]
TiDB support chinese comments, but may be it has compatibility problem with navicat.

**Comment by xiamw2000** [comment]
@shenli I setup tidb to ubuntu14.04,  but tidb do not support chinese comments on navicat premium 11.2.7,  which client is able to tidb? tks

**Comment by tiancaiamao** [comment]
From the error information, you're changing column definition. 
I guess it has nothing to do with Chinese comments, but the operation itself.
You can try English comments and check whether it returns the same error.

It would be helpful for debugging if you can provide the SQL command that navicat generated.

**Comment by xiamw2000** [comment]
@tiancaiamao tks,  pls tell me  which client be able to tidb?

**Comment by tiancaiamao** [comment]
The standard mysql client command line tool works.

**Comment by xiamw2000** [comment]
@tiancaiamao we wish navicat be able to tidb, we have used to navicat, tks!
