### ISSUE TITLE
Fix affected row in drop sql binding so that we can avoid clear cache if affected rows is 0

### ISSUE THREAD

**Issue by yuqi1129** [pingcap/tidb#27758]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Master branch

Drop bind sql use `UPDATE mysql.bind_info SET status = %?, update_time = %? WHERE original_sql = %? AND update_time < %?` to judge whether there exists the sql binding, but this is not true, the correct sql should add
`status != 'deleted'`, for example, if there exist several deleted sql binding.
![image](https://user-images.githubusercontent.com/15794564/131795977-f12a3655-9c00-4a2e-88c0-94336d836f31.png)

**Comment by tisonkun** [comment]
@yuqi1129 thanks for reporting this issue. I think it is more like an enhancement than a bug? We can save cycles while the original code is correct, but inefficent.

**Comment by yuqi1129** [comment]
Yes, This is a just enhancement, sorry for not describe it clearly

**Comment by tisonkun** [comment]
Never mind. Updated for you.
