### ISSUE TITLE
GRANT DROP VIEW on xxx  failed 

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tidb#27761]
## General Question

MySQL Doc：https://dev.mysql.com/doc/refman/5.7/en/drop-view.html

Is TiDB not designed with `drop view` permission?

```
MySQL [(none)]> GRANT DROP VIEW ON `XXXDB`.* TO 'XXX'@'%';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 15 near "VIEW ON `XXXDB`.* TO 'XXX'@'%'"
```

**TiDB version：5.2.0**

**Comment by ljluestc** [comment]
TiDB does not support the specific DROP VIEW permission in its SQL syntax. In TiDB, the SQL syntax is compatible with MySQL to a large extent, but there might be some differences in certain features and permissions.

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
