### ISSUE TITLE
Lightning: DBaaS import csv fails with InvalidRange if CSV file size is about 256MB when strict-format is true

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#27763]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
On DBaaS, try to import csv from S3, S3 bucket files like below:
[root@centos76_vm ~]# du -shl /minio/fubin/dbgen/xxx/*
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000000.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000001.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000002.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000003.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000004.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000005.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000006.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000007.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000008.csv
257M    /minio/fubin/dbgen/aaaa/aaaa.bbbb.000000009.csv
4.0K    /minio/fubin/dbgen/aaaa/aaaa.bbbb-schema.sql
4.0K    /minio/fubin/dbgen/aaaa/aaaa-schema-create.sql
4.0K    /minio/fubin/dbgen/aaaa/metadata

### 2. What did you expect to see? (Required)
Import should succeed

### 3. What did you see instead (Required)
Import failed.

### 4. What is your TiDB version? (Required)
Lightning: 5.2.0
[release-version=v5.2.0] [git-hash=05d2210647d6a1503a8d772477e43b14a024f609] [git-branch=heads/refs/tags/v5.2.0] [go-version=go1.16.4]

**Comment by fubinzh** [comment]
On DBaaS, strict-format is default to False, and this issue is not seen when strict-format is False.

**Comment by VelocityLight** [comment]
update
