### ISSUE TITLE
Add virtual table `TiDB_HOT_REGIONS_HISTORY `

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#27772]
ref https://github.com/pingcap/tidb/issues/25281

## Background

TiDB has a memory table `TIDB_HOT_REGIONS` that provides information about hotspot regions. But it only shows the current hotspot information. This leads to the fact that when DBAs want to query historical hotspot details, they have no way to find the corresponding hotspot information.

According to the [documentation](https://docs.pingcap.com/tidb/stable/information-schema-tidb-hot-regions) for the current `TIDB_HOT_REGIONS` table,  it can only provides information about recent hotspot regions calculated by PD according to the heartbeat from tikv.  It is inconvenient to obtain hotspot regions of past time, and locate which store the region is. For ease of use, we can store extened hotspot region infomation in PD. The DBA can query hotspot regions within a specified period by such statement in TiDB:

```SQL
SElECT * FROM information_schema.tidb_hot_regions_history WHERE update_time>='2019-04-01 00:00:00' and update_time<='2019-04-01 00:01:00';
```

## Details
Create a new table `TIDB_HOT_REGIONS_HISTORY` in the `INFORMATION_SCHEMAT` schema to retrieve history hotspot regions stored by PD periodically.

**Comment by IcePigZDB** [comment]
* TiDB's relative implmention PRs:
    1. #27373 
    2. #27374
    3. #27375
    4. #30500

**Comment by IcePigZDB** [comment]
* Docs
   * pingcap/docs/pull/6624
   * pingcap/docs-cn/pull/7164

**Comment by nolouch** [comment]
Done! thanks @IcePigZDB @qidi1
