### ISSUE TITLE
tidb-lightnling import failed after scale-in a tikv node

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#27782]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tiup cluster deploy 3_tikv
tiup cluster scale-in tikv_1
./tidb-lightning --config tidb-lightning.toml

### 3. What did you see instead (Required)
```
./tidb-lightning --config tidb-lightning.toml
tidb lightning encountered error:  build local backend failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 172.16.5.39:20161: connect: connection refused"
...

```

### 4. What is your TiDB version? (Required)

master
```
[root@IDC-172-16-6-53 bin]# ./tidb-lightning -V
Release Version: v5.2.0-alpha-778-g3ac81a376
Git Commit Hash: 3ac81a37661a574f7d500b36965509614b8ec6f7
Git Branch: HEAD
Go Version: go1.16.4
UTC Build Time: 2021-08-30 10:28:56
Race Enabled: false
```

**Comment by Little-Wallace** [comment]
Do not import data when cluster do not finish scale

**Comment by fubinzh** [comment]
this issue is handled by PR https://github.com/pingcap/br/pull/1334

**Comment by Little-Wallace** [comment]
this issue is handled by PR https://github.com/pingcap/tidb/pull/27774
