### ISSUE TITLE
select _ascii"">_ascii"\Z8D" is Incompatible with mysql

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#27885]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select _ascii"">_ascii"\Z8D";
```
### 2. What did you expect to see? (Required)
```
mysql> select _ascii"">_ascii"\Z8D";
+-----------------------+
| _ascii"">_ascii"\Z8D" |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set (0.05 sec)
```
### 3. What did you see instead (Required)
mysql> select _ascii"">_ascii"\Z8D";
+-----------------------+
| _ascii"">_ascii"\Z8D" |
+-----------------------+
|                     0 |
+-----------------------+
1 row in set (0.05 sec)
### 4. What is your TiDB version? (Required)

```
Release Version: v5.3.0-alpha-41-gaf70762cd
Edition: Community
Git Commit Hash: af70762cd52519f025daa5e869ba37465a7fb311
Git Branch: master
UTC Build Time: 2021-09-08 02:02:31
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by xiongjiwei** [comment]
it is expected, see [doc](https://docs.pingcap.com/zh/tidb/v5.0/character-set-and-collation#%E6%96%B0%E6%A1%86%E6%9E%B6%E4%B8%8B%E7%9A%84%E6%8E%92%E5%BA%8F%E8%A7%84%E5%88%99%E6%94%AF%E6%8C%81)   `\Z` is less than space
