### ISSUE TITLE
Lightning: remove the csv file name restriction

### ISSUE THREAD

**Issue by NingLin-P** [pingcap/tidb#27896]
## Enhancement

Currently, when import data through lightning with `csv` file, lightning expect the `csv` file name should be in a format like `{db_name}.{table_name}.{id}.csv` where the `id` should be padded with `0` to aligned with the largest `id`.  For example, when there is a file named `db.tbl.12345.csv`, the file name of the file with id `1`  should be `db.tbl.00001.csv` (padded with four `0`).

In some cases, the number of `csv` files is uncertain when each `csv` file is created,  so we can't determine how many `0` should be padded to the file name, and may need an extra step to format the file name. Instead, it may be better to remove the `csv` file name restriction to avoid such extra work.

**Comment by gozssky** [comment]
As far as I know, the `{id}`  is mainly used to distinguish between different files of a table. It does not need to be continuous and pad to fixed length.

**Comment by NingLin-P** [comment]
I had done some simple checks and indeed there is no such restriction, but I think it is better to update the doc though. https://github.com/pingcap/docs-cn/blob/3a30845d86/tidb-lightning/migrate-from-csv-using-tidb-lightning.md
