### ISSUE TITLE
SET GLOBAL tidb_skip_isolation_level_check=1 doesn't work as expected

### ISSUE THREAD

**Issue by sunxiaoguang** [pingcap/tidb#27897]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> SET GLOBAL tidb_skip_isolation_level_check=1;
Query OK, 0 rows affected (0.02 sec)
```
Disconnect and reconnect to TiDB
```
mysql> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
ERROR 8048 (HY000): The isolation level 'SERIALIZABLE' is not supported. Set tidb_skip_isolation_level_check=1 to skip this error
```

### 2. What did you expect to see? (Required)

```
mysql> SET GLOBAL tidb_skip_isolation_level_check=1;
Query OK, 0 rows affected (0.03 sec)
```
Disconnect and reconnect to TiDB
```
mysql> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
Query OK, 0 rows affected, 1 warning (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> SET GLOBAL tidb_skip_isolation_level_check=1;
Query OK, 0 rows affected (0.02 sec)
```
Disconnect and reconnect to TiDB
```
mysql> SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
ERROR 8048 (HY000): The isolation level 'SERIALIZABLE' is not supported. Set tidb_skip_isolation_level_check=1 to skip this error
```

### 4. What is your TiDB version? (Required)

5.1.0 and all the new versions

**Comment by morgo** [comment]
I commented on the PR, but I'm not sure this is a bug. GLOBAL scoped changes are not supposed to apply to the current session yet. They only apply to new sessions.

**Comment by sunxiaoguang** [comment]
> I commented on the PR, but I'm not sure this is a bug. GLOBAL scoped changes are not supposed to apply to the current session yet. They only apply to new sessions.

Oops, you are right. I agree that global changes should not affect current session. However I saw something strange that there might be some other issue as well. 

![image](https://user-images.githubusercontent.com/3982329/132605501-db8eaac1-22f2-4bad-88eb-c7816682764e.png)

The first time I restart client to check global variables and change isolation level to `SERIALIZABLE` without having trouble. However the second time it stopped working again with tidb_skip_isolation_level_check=1 configured.

I will take another look to this.

**Comment by sunxiaoguang** [comment]
> I commented on the PR, but I'm not sure this is a bug. GLOBAL scoped changes are not supposed to apply to the current session yet. They only apply to new sessions.

After checking comments in PR, I realized that you already pointed out the root cause. My last experiment failed because I didn't read variable before changing isolation level. Simply remove skipInit from `TiDBSkipIsolationLevelCheck` definition works well. Thanks! @morgo
