### ISSUE TITLE
The tidb was blocked when 'Create Index'

### ISSUE THREAD

**Issue by snail2swift** [pingcap/tidb#2791]
It seems that the tidb was blocked when 'Create Index idex_1 on t1 ...'，because 'Delete from t1 where date='2017-02-06' ' and 'Create table t2'   cannot execute.

**tidb version:**
Git Commit Hash: fc93cd51290c62bf760390b4c501f03e37c21c0e
UTC Build Time:  2017-03-06 02:38:56

**tidb status:**
mysql> show status;
+--------------------------+--------------------------------------+
| Variable_name            | Value                                |
+--------------------------+--------------------------------------+
| ddl_owner_id             | 46f91ed0-4566-4c19-8cbe-557714ce039b |
| ddl_job_last_update_ts   | 1488881607                           |
| ddl_job_args             | []                                   |
| server_id                | 46f91ed0-4566-4c19-8cbe-557714ce039b |
| ddl_schema_version       | 2316                                 |
| ddl_job_table_id         | 26                                   |
| ddl_job_reorg_handle     | 49440769                             |
| ddl_job_row_count        | 49440768                             |
| bg_owner_last_update_ts  | 1488881606                           |
| ddl_job_schema_state     | write reorganization                 |
| ddl_job_action           | add index                            |
| ddl_owner_last_update_ts | 1488881607                           |
| ddl_job_snapshot_ver     | 390300009275326466                   |
| bg_owner_id              | 46f91ed0-4566-4c19-8cbe-557714ce039b |
| ddl_job_error            |                                      |
| ddl_job_id               | 28                                   |
| ddl_job_schema_id        | 1                                    |
| ddl_job_state            | running                              |
| bg_schema_version        | 2316                                 |
+--------------------------+--------------------------------------+

**Comment by shenli** [comment]
@snail2swift Thanks for your feedback!
How many rows are there in t1?
Is there any error when you run `Delete from t1 where date='2017-02-06`?
DDL statement will run in sequence, so the statement may be waiting for the previous statement to finish.

**Comment by snail2swift** [comment]
@shenli 
How many rows are there in t1?   
**160 million**

Is there any error when you run Delete from t1 where date='2017-02-06?  
**A lot of time has passed，get this:
ERROR 1105 (HY000): Information schema is changed.**

DDL statement will run in sequence, so the statement may be waiting for the previous statement to finish.
**You can add new columns and indices without stopping or affecting the on-going operations.**

**Comment by zimulala** [comment]
@snail2swift 
You can try the branch in the [PR](https://github.com/pingcap/tidb/pull/2786) .

**Comment by shenli** [comment]
@snail2swift 
1. TiDB use a batch way (1024 rows per batch) to build index for existing. So 160 million rows will take some time.
2. The PR mentioned by zimulala will fix " Information schema is changed." error.
3. In the current implementation of TiDB, we only allow one active DDL worker in a TiDB cluster. May be we will improve this in the future.

**Comment by shenli** [comment]
@snail2swift Please try the latest master or binary.

**Comment by snail2swift** [comment]
@shenli OK.
