### ISSUE TITLE
Information schema is out of date: schema failed to update in 1 lease

### ISSUE THREAD

**Issue by birdstorm** [pingcap/tidb#27948]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tiflash_regression_test_daily/detail/tiflash_regression_test_daily/359/pipeline  

### 3. What did you see instead (Required)

TiFlash could not retrieve replica info from TiDB.

```
[2021/09/04 15:36:02.329 +00:00] [WARN] [session.go:1571] ["run statement failed"] [schemaVersion=10134] [error="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"] [session="{\n  \"currDBName\": \"\",\n  \"id\": 0,\n  \"status\": 2,\n  \"strictMode\": true,\n  \"user\": null\n}"]
[2021/09/04 15:36:02.329 +00:00] [WARN] [gc_worker.go:278] ["[gc worker] check leader"] [error="[domain:8027]Information schema is out of date: schema failed to update in 1 lease, please make sure TiDB can connect to TiKV"]  
```

### 4. What is your TiDB version? (Required)

branch release-5.2

**Comment by bb7133** [comment]
@birdstorm @XuHuaiyu @jebter 

I cannot see the `Information schema is out of date: schema failed to update in 1 lease` log from https://ci.pingcap.net/blue/organizations/jenkins/tiflash_regression_test_daily/detail/tiflash_regression_test_daily/359/pipeline. Also, I don't know why the test failed(there are too many logs).

Is the jenkins link wrong?

**Comment by birdstorm** [comment]
> @birdstorm @XuHuaiyu @jebter 
> 
> I cannot see the `Information schema is out of date: schema failed to update in 1 lease` log from https://ci.pingcap.net/blue/organizations/jenkins/tiflash_regression_test_daily/detail/tiflash_regression_test_daily/359/pipeline. Also, I don't know why the test failed(there are too many logs).
> 
> Is the jenkins link wrong?

@bb7133 hi, this issue was created a long time ago, I will try to recall what happened then...

**Comment by birdstorm** [comment]
@bb7133 it seems the original TiDB log was outdated and could not be downloaded, which should be available in `tiflash-jenkins-test-log-tiflash_regression_test_daily-359.tar.gz` otherwise

**Comment by bb7133** [comment]
The only known reason for `Information schema is out of date: schema failed to update in 1 lease` is the network issue between TiDB and TiKV, so I just suspect that it is something wrong with the test environment.

I will close this issue for now and feel free this issue can be reproduced without network partition.
