### ISSUE TITLE
Add placement rules for a schema via ALTER DATABASE 

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#27975]
## Enhancement

Part of https://github.com/pingcap/tidb/issues/18030

This extends https://github.com/pingcap/tidb/issues/18030 to add `ALTER DATABASE` support.

**Comment by morgo** [comment]
@sylzd This issue is for you. I've updated the PR to "close" it.

**Comment by sylzd** [comment]
> @sylzd This issue is for you. I've updated the PR to "close" it.

thanks~
