### ISSUE TITLE
Remove old legacy code for placement options

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#27971]
## Enhancement

Part of https://github.com/pingcap/tidb/issues/18030

The old placement options exist in the parser as `OldPlacementOptions`:

https://github.com/pingcap/parser/blob/ea70ab7caead1b51494db16e7b886221b1aaaf6f/parser.y#L1617-L1646

This is a followup task of https://github.com/pingcap/parser/pull/1299 where we can remove these options.

Some works:

- [x] #29548
- [x] Remove dependencies for `infoschema.bundleMap` in ddl operations.
  - [x] #29595
  - [x] #29618
  - [x] #29648
  - [x] #29827
- [x] #29602

**Comment by lcwangchao** [comment]
Some works:

- Remove ddl operation `AlterTableAlterPartition` from parser and tidb
- Remove dependencies for `infoschema.bundleMap` in ddl operations.
- Remove `infoschema.bundleMap`
- Remove old syntax in parser
