### ISSUE TITLE
migrate test-infra to testify for `export_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28003]

**Comment by karuppiah7890** [comment]
Looks like `types/export_test.go` doesn't have any tests

https://github.com/pingcap/tidb/blob/7755d25aba5120dafde98fff11ab3b98ca4d192f/types/export_test.go#L1-L18

Maybe we can close this issue?

**Comment by karuppiah7890** [comment]
cc @tisonkun

**Comment by tisonkun** [comment]
Thanks for spotting this @karuppiah7890 ! Closed as invalid.
