### ISSUE TITLE
Incorrect select result after point update nothing

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#28011]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiKV is required, then execute the following SQL.
```sql
/* test */ drop table if exists t1;
/* test */ create table t1(c_int int, c_str varchar(40), unique key uk(c_int));
/* test */ insert into t1 (`c_int`, `c_str`) values (6, 'relaxed chatelet');
/* test */ begin;
/* test */ update t1 set c_int = c_int + 5, c_str = 'dreamy taussig' where (c_int, c_str) in ((6, 'frosty hopper'), (6, 'funny sutherland'));
/* test */ select c_int from t1;
/* test */ select c_int, c_str from t1;
/* test */ commit;
```

This issue is introduced by #25730 and seems to be fixed by #26759 by accident (after which IndexLookUp gets used).

### 2. What did you expect to see? (Required)

```
/* test */ select c_int from t1;
-- test >> +-------+
-- test    | C INT |
-- test    +-------+
-- test    |     6 |
-- test    +-------+
/* test */ select c_int, c_str from t1;
-- test >> +-------+------------------+
-- test    | C INT |      C STR       |
-- test    +-------+------------------+
-- test    |     6 | relaxed chatelet |
-- test    +-------+------------------+
```

### 3. What did you see instead (Required)

```
/* test */ select c_int from t1;
-- test >> +-------+
-- test    | C INT |
-- test    +-------+
-- test    |     6 |
-- test    |     6 |
-- test    +-------+
/* test */ select c_int, c_str from t1;
-- test >> +-------+------------------+
-- test    | C INT |      C STR       |
-- test    +-------+------------------+
-- test    |     6 | relaxed chatelet |
-- test    +-------+------------------+
```

### 4. What is your TiDB version? (Required)

release-5.0
release-5.1

**Comment by cfzjywxk** [comment]
The cause is similar with https://github.com/pingcap/tidb/issues/28011, currently the merge operation done by the union scan operater will consider the handle key but not the unique key. As a result there will be some weird in transaction query results such as returning same index values for a unique index, like the examples described in https://github.com/pingcap/tidb/issues/28011.

The data consistency will not be affected, but It will be confusing if the user query data for some updates in transaction.

**Comment by cfzjywxk** [comment]
@zyguan 
As the root cause of this issue is related to the describtions in #28011, but the change in #25730 increases the rate encountered by the client, I think we could change the severity to `major`.

**Comment by vivid392845427** [comment]
duplicate with [24159](https://github.com/pingcap/tidb/issues/24195)
