### ISSUE TITLE
Timeout test  `builtin_time_vec_test.go:575: testVectorizeSuite2.TestVectorizedBuiltinTimeEvalOneVec`

### ISSUE THREAD

**Issue by karuppiah7890** [pingcap/tidb#28017]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

```bash
PASS: builtin_time_vec_test.go:575: testVectorizeSuite2.TestVectorizedBuiltinTimeEvalOneVec	8.250s
```

### 1. Minimal reproduce step (Required)

Run `make gotest` in local

### 2. What did you expect to see? (Required)

All tests to pass with no errors including time out errors

### 3. What did you see instead (Required)

Timeout errors

### 4. What is your TiDB version? (Required)

Commit - 64e1fd5e66bd72fe5eb9ede28d6a5f6c6eb6f2c5

**Comment by zanmato1984** [comment]
We already removed the timeout limit so this is no longer an issue. Closing.
