### ISSUE TITLE
'mysql -h XXX -P 4000 -D database' cmd failed

### ISSUE THREAD

**Issue by neoguojing** [pingcap/tidb#2803]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
mysql -h ip -P 4000 -D XXX (the XXX is our database name not default databases)

2. What did you expect to see?
I should login the databases

3. What did you see instead?
Mysql client log:
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0
tidb-server log:
2017/03/09 16:59:08 server.go:116: [info] [1] new connection XXXXX:52320
2017/03/09 16:59:08 session.go:523: [warning] [1] parse error:
line 0 column 9 near "" (total length 9)
use XXX   -----------------this is mys database name
2017/03/09 16:59:08 server.go:199: [info] handshake error line 0 column 9 near "" (total length 9)
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:524: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/driver_tidb.go:135: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:307: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:99: 
2017/03/09 16:59:08 server.go:193: [info] [1] close connection

4. What version of Go are you using (`go version`)?
1.7

**Comment by neoguojing** [comment]
Would you pls fix this issue as soon as possible ?

**Comment by neoguojing** [comment]
I updated the tidb to the latest version yesterday. The last version was OK

**Comment by coocood** [comment]
@neoguojing 
Thank you for your report anyway!

**Comment by neoguojing** [comment]
I mean the latest version was not Ok. The previous was OK.
Did this issue fixed ?

**Comment by shenli** [comment]
@neoguojing Could you show me the result of `tidb-server -V`?

**Comment by neoguojing** [comment]
tidb-server -V
Git Commit Hash: a623e670e64311d35001a41a86a991cafce3e06e
UTC Build Time:  2017-03-08 05:33:20

**Comment by neoguojing** [comment]
The previous version I have used:
Git Commit Hash: 31d3b87704d5bc8b624defaa34d3a060105482b7
UTC Build Time:  2017-02-15 05:35:13

**Comment by neoguojing** [comment]
Our Database name was 'quote'. Is this name a invalid name.

**Comment by neoguojing** [comment]
If you can not reproduce this issue, you could try to use 'quote' as the database name.

**Comment by shenli** [comment]
@neoguojing We will fix this soon.

**Comment by shenli** [comment]
@neoguojing Please try the latest master.
