### ISSUE TITLE
lightning: DBaaS lightning import doesn't fail if source folder not exist

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#28031]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
From DBaaS, start a import task, specify a S3 folder which doesn't exists.

### 2. What did you expect to see? (Required)
Appropriate error should be displayed to user to let user know import failed.

### 3. What did you see instead (Required)
Lightning doesn't report error for the import. And go through all the import steps: schema create, precheck, etc.

<img width="872" alt="dbaas_not_exist_folder" src="https://user-images.githubusercontent.com/7403864/133209576-95e9566a-fcb0-4443-a5fb-de066f73d8e6.PNG">

<img width="1774" alt="dbaas_not_exist_folder_2" src="https://user-images.githubusercontent.com/7403864/133209586-dcd527f6-b872-451f-b255-fed88e9d62ad.PNG">

### 4. What is your TiDB version? (Required)
Lightning: [release-version=v5.2.0] [git-hash=05d2210647d6a1503a8d772477e43b14a024f609]

**Comment by glorv** [comment]
NOTE: this bug also affects tidb-lightning v4.0, v5.0 and v5.1.
