### ISSUE TITLE
Unstable test `github.com/pingcap/tidb/plugin.Shutdown`

### ISSUE THREAD

**Issue by zhouqiang-cl** [pingcap/tidb#28054]
## Bug Report
```
[plugin.go:362] ["call OnShutdown for failure"] [plugin=tplugin] [error=EOF] [stack="github.com/pingcap/tidb/plugin.Shutdown\n\t/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/plugin/plugin.go:362\ngithub.com/pingcap/tidb/plugin.TestLoadPluginSkipError\n\t/home/jenkins/agent/workspace/tidb_ghpr_check_2/go/src/github.com/pingcap/tidb/plugin/plugin_test.go:174\ntesting.tRunner\n\t/usr/local/go/src/testing/testing.go:1193"]
```
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/33435/pipeline

**Comment by zimulala** [comment]
I can't find specific logs of test failures.
The `Call OnShutdown for Failure` log is also printed if the test passes.

**Comment by zimulala** [comment]
@zhouqiang-cl 
If you have a similar error, please post the link here.

**Comment by aytrack** [comment]
@zimulala it's failed again in ci: https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_coverage/detail/tidb_ghpr_coverage/1191/pipeline
PTAL~

**Comment by djshow832** [comment]
According to the logs in https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_coverage/detail/tidb_ghpr_coverage/1191/pipeline, the last running test was `TestAuditLog` and all the statements were finished. The case was added on 5th, Aug, and this CI failure begins on 15th, Sep. I doubt there may be a relationship between them but the `TestAuditLog` was removed and changed to another test case recently.
Let's wait and see if there are more failures.

**Comment by bb7133** [comment]
Close this issue and we can try to open it, when the fail happens again after #30165.
