### ISSUE TITLE
Out of range value for column '%s' at row %d

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#28052]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
use test;
drop table if exists t;
CREATE TABLE `t` (
  `col_tinyint_key_signed` tinyint(4) DEFAULT NULL,
  `col_year_key_signed` year(4) DEFAULT NULL,
  KEY `col_tinyint_key_signed` (`col_tinyint_key_signed`),
  KEY `col_year_key_signed` (`col_year_key_signed`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into t values(-100,NULL);
select /*+ inl_merge_join(t1, t2) */ count(*) from t t1 right join t t2 on t1. `col_year_key_signed` = t2. `col_tinyint_key_signed`;
```

### 2. What did you expect to see? (Required)
release-4.0 & mysql
```
mysql> select /*+ inl_merge_join(t1, t2) */ count(*) from t t1 right join t t2 on t1. `col_year_key_signed` = t2. `col_tinyint_key_signed`;
+----------+
| count(*) |
+----------+
|        1 |
+----------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)
release-5.0 & release-5.1 & release-5.2 & master
```
mysql> select /*+ inl_merge_join(t1, t2) */ count(*) from t t1 right join t t2 on t1. `col_year_key_signed` = t2. `col_tinyint_key_signed`;
ERROR 1264 (22003): Out of range value for column '%s' at row %d
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.3.0-alpha-109-g0854595a6
Edition: Community
Git Commit Hash: 0854595a69923e51cf5a39244559ef21b14704e1
Git Branch: master
UTC Build Time: 2021-09-15 02:28:16
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by tisonkun** [comment]
@yuqi1129 could you elaborate why this issue occurs and how you fix it as well as won't introduce regression?

**Comment by yuqi1129** [comment]
@tisonkun As far as i can see, In the join condition, value of tinyint will convert to type year, however convert '-100' to year will cause ErrWarnDataOutOfRange error and `inl_merge_join` do not handle this error.
more detail, please the the PR. 

As for the potential regression, the PR eliminates the possibility of DataOutOfRange error in type conversion and will not bring other problem i think.

**Comment by tisonkun** [comment]
@yuqi1129 could you help on cherry-pick the fix to

* release-5.0
* release-5.1
* release-5.2

@bb7133 how do we finish the cherry-pick?

**Comment by yuqi1129** [comment]
@tisonkun , I'am glad to do this job. Should i create new PRs to the related branch or others ?
@bb7133 Help is needed

**Comment by tisonkun** [comment]
Closed.
