### ISSUE TITLE
TiDB cannot support carriage characters(\r) in SQL statements

### ISSUE THREAD

**Issue by hey-hoho** [pingcap/tidb#28062]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I query this SQL in navicat:
```
SELECT count(1) from my_order
-- select * from my_order
where order_no='1015240524'
```

In fact, there is a hidden carriage return at the end of the annotated line.
The result I expect is a query with a where condition, but in fact I count the whole table.

I found the SQL text executed by tidb in the log:
```
[sql="select count(1) from my_order\n-- select * from my_order\rwhere order_no='1015240524'"]
```
Should the `\r` be parsed as a newline?

### 2. What did you expect to see? (Required)
result by where query

### 3. What did you see instead (Required)
whole table scan

### 4. What is your TiDB version? (Required)
v5.1.0

**Comment by kennytm** [comment]
the behavior (`\r` does *not* terminate the `--` comment) is compatible with MySQL 8.0.26:

```console
$ echo $'select 1\n-- 2\n+ 3 a;' | mysql -u root
a
4

$ echo $'select 1\n-- 2\r+ 3 a;' | mysql -u root
1
1
```

**Comment by hey-hoho** [comment]
Hi @kennytm , you means TiDB compatible MySQL 8.0, support for this feature will not be considered for a short time?

**Comment by kennytm** [comment]
I'd say it is a `wontfix` issue. Since we share the same behavior with MySQL I don't see much reason changing it.

The SQL standard (ISO 9075-2) does not mandate a `<newline>` must accept both `[\r\n]`.

> ### Syntax Rules
>
> 4\) `<newline>` is the **implementation-defined** end-of-line indicator.
>
> > NOTE 128 — `<newline>` is typically represented by U+000A (“Line Feed”) and/**or** U+000D (“Carriage Return”); however, this representation is not required by ISO/IEC 9075.

BTW SQLite3 also does not treat `\r` as line terminator.

```console
$ echo $'select 1\n-- 2\r+ 3;' | sqlite3
1
$ echo $'select 1\n-- 2\n+ 3;' | sqlite3
4
```

**Comment by dveeden** [comment]
I think we should keep this as is and close this issue.
