### ISSUE TITLE
Why tidb use occ to avoid write-write conflict ?

### ISSUE THREAD

**Issue by zcfrank1st** [pingcap/tidb#2807]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of Go are you using (`go version`)?

**Comment by shenli** [comment]
@zcfrank1st What is `occ`?

**Comment by ngaut** [comment]
OCC: Optimistic concurrency control. @shenli 

TiDB is designed for large database (more than thousands of millions of rows) and conflict is rare.
You may need to queue transactions if the contention is really high. @zcfrank1st
