### ISSUE TITLE
migrate test-infra to testify for `statistics/handle/dump_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28130]

**Comment by feitian124** [comment]
hi @lizhenda, what is your progress now?

**Comment by feitian124** [comment]
you can check https://github.com/pingcap/tidb/pull/28301 for some info incase you meet similiar diffcult.

**Comment by lizhenda** [comment]
@feitian124 Sorry, I don't have time to finish it. How to un-assign this issue?

**Comment by feitian124** [comment]
it's fine, i will do it.
