### ISSUE TITLE
Result of GetVar expression is wrong when argument is bit(4)

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#28152]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table if exists t1;
    create table t1(c1 bit(4));
    insert into t1 values(0x0f);
    set @a = 0x3135;
    select * from t1 where c1 in (@a);

### 2. What did you expect to see? (Required)
    mysql> select * from t1 where c1 in (@a);
    +------------+
    | c1         |
    +------------+
    | 0x0F       |
    +------------+
    1 row in set (0.00 sec)
### 3. What did you see instead (Required)
    mysql> select * from t1 where c1 in (@a);
    +------+
    | c1   |
    +------+
    |     |
    +------+
    1 row in set (0.00 sec)
### 4. What is your TiDB version? (Required)
master

**Comment by kennytm** [comment]
if you want to see `0x0F` you should pass `--binary-as-hex` when invoking the MySQL client:

```sh
mysql -u root -h 127.0.0.1 -P 4000 --binary-as-hex
```

i can't see any difference between MySQL and TiDB when `--binary-as-hex` are both provided or both not provided.

**Comment by guo-shaoge** [comment]
> if you want to see `0x0F` you should pass `--binary-as-hex` when invoking the MySQL client:
> 
> ```shell
> mysql -u root -h 127.0.0.1 -P 4000 --binary-as-hex
> ```
> 
> i can't see any difference between MySQL and TiDB when `--binary-as-hex` are both provided or both not provided.

Make sence.

**Comment by guo-shaoge** [comment]
> if you want to see `0x0F` you should pass `--binary-as-hex` when invoking the MySQL client:
> 
> ```shell
> mysql -u root -h 127.0.0.1 -P 4000 --binary-as-hex
> ```
> 
> i can't see any difference between MySQL and TiDB when `--binary-as-hex` are both provided or both not provided.

A related MySQL [bug](https://bugs.mysql.com/bug.php?id=104966&thanks=4)
