### ISSUE TITLE
migrate test-infra to testify for `br/pkg/lightning`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28170]
* [x] #28234
* [x] #28235
* [x] #28236
* [x] #28237
* [x] #28238
* [x] #28239
* [x] #28240
* [x] #28241
* [x] #28242
* [x] #28243
* [x] #28244
* [x] #28245

**Comment by YuJuncen** [comment]
`pkg/lightning` is merged from [pingcap/tidb-lightning](https://github.com/pingcap/tidb-lightning). Maybe we'd better split this into subtasks too?

**Comment by tisonkun** [comment]
Yes. Of course. If you'd like to take over some of them, please comment and ask for it.

**Comment by tisonkun** [comment]
@YuJuncen done.

**Comment by tisonkun** [comment]
Closed as all subtasks done.
