### ISSUE TITLE
After a TiKV node breaks down, others continue to write large amounts of logs, resulting in disk space exhaustion

### ISSUE THREAD

**Issue by jt20190617** [pingcap/tidb#28231]
## phenomenon
The cluster version is V4.0.12, there are 5 node 5 peers. Do cluster high availability walkthrough tests. One of the TiKV nodes is down, and then it is found that the other TiKV nodes are writing logs like crazy, causing the disk space to run out quickly; Found that files were switched every 3 to 4 minutes.

Then many other TiKV nodes went down because the disk space was occupied by log files(if users do not manage manually).

In this case, is it reasonable for other TiKV nodes to keep frantically brushing logs? For example, a TiKV process was down due to some accident, and the user did not discover or deal with it in time. As a result, the whole cluster became unavailable due to crazy log flushing and disk bursting.

I think this will have an impact on high availability features.

## Enhancement
When the number of TiKV nodes in the cluster is equal to the number of data copies, the log writing behavior and frequency of other TiKV nodes should be controlled after the failure of one TiKV node.

**Comment by kennytm** [comment]
(i think this issue should be filed to https://github.com/tikv/tikv/, not here)

**Comment by jt20190617** [comment]
> (i think this issue should be filed to https://github.com/tikv/tikv/, not here)

i am so sorry

**Comment by kennytm** [comment]
(the new issue is tikv/tikv#10972 for those interested)
