### ISSUE TITLE
Changing sql_auto_is_null is a noop (unsafe)

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#28230]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I was reading through the Django source code, and noticed that it had a flag for [`sql_auto_is_null`.](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_auto_is_null) I am not sure of any applications that actually use this feature, but TiDB has a "noop" handling, which is unsafe. It should instead refuse to change the sysvar.

```sql
SET sql_auto_is_null = 1;
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (id INT NOT NULL PRIMARY KEY auto_increment, b char(20));
INSERT INTO t1 VALUES (NULL, 'b');
SELECT * FROM t1 WHERE id IS NULL;
```

### 2. What did you expect to see? (Required)

```sql
mysql [localhost:5731] {msandbox} (test) > SELECT * FROM t1 WHERE id IS NULL;
+----+------+
| id | b    |
+----+------+
|  1 | b    |
+----+------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```sql
mysql> SELECT * FROM t1 WHERE id IS NULL;
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.3.0-alpha-118-gbf873602e-dirty
Edition: Community
Git Commit Hash: bf873602e25ea114598b5d68325a4edf5c367d63
Git Branch: add-last-insert-id
UTC Build Time: 2021-09-15 14:54:44
GoVersion: go1.16.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: true
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
**Note to implementers:** I don't think it's worth implementing this feature (it is too obscure). But advertising the sysvar and allowing it to be changed is problematic.

**Comment by unconsolable** [comment]
So can we just commented this variable as unsupported in `sysvar.go`, and when running this query, just throw error as follows?
```
mysql> SET sql_auto_is_null = 1;
ERROR 1193 (HY000): Unknown system variable 'sql_auto_is_null'
```

**Comment by unconsolable** [comment]
So can we just commented this variable as unsupported in `sysvar.go`, and when running this query, just throw error as follows? Or throw a warning instead?
```
mysql> SET sql_auto_is_null = 1;
ERROR 1193 (HY000): Unknown system variable 'sql_auto_is_null'
```

**Comment by morgo** [comment]
See: https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_noop_functions-new-in-v40

**Comment by unconsolable** [comment]
I will update `pingcap/docs` and `pingcap/docs-cn` to reflect the changes this issue and corresponding PR brings.
