### ISSUE TITLE
migrate test-infra to testify for `br/pkg/lightning/restore`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28241]
## Sub tasks

- [x] #32036

**Comment by tisonkun** [comment]
@disksing after some investigate I notice that `restore_schema_test.go` is buggy as failure occurs but not be reported.

You can step into the `gomock.Controller.Call` and breakpoint at `ctrl.T.Fatalf` to verify its failure. Due to bugs in `pingcap/check` the failure reported in child `check.C` isn't propagated properly in the suite the it reports false PASS.

That is, we're running tests report false positive for a long time :(

**Comment by tisonkun** [comment]
@lichunzhu we need either rewrite this test in testify or just remove it as it actually fails. Could you please take a look?

**Comment by tisonkun** [comment]
@lichunzhu @disksing if there is no response, I'll regard it as this test is lack of interest and prepare to remove it. It can be brought back anytime from VCS, though.

**Comment by disksing** [comment]
> @lichunzhu @disksing if there is no response, I'll regard it as this test is lack of interest and prepare to remove it. It can be brought back anytime from VCS, though.

good idea

**Comment by lichunzhu** [comment]
> @lichunzhu we need either rewrite this test in testify or just remove it as it actually fails. Could you please take a look?

@disksing filed a PR https://github.com/pingcap/tidb/pull/32065 to rewrite this to testify. We will try to merge this PR.
