### ISSUE TITLE
prepared-plan-cache: return wrong result using bigint column

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#28259]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

prepared-plan-cache.enable = true
```sql
use test;
drop table if exists UK_GCOL_VIRTUAL_18588;
CREATE TABLE `UK_GCOL_VIRTUAL_18588` (
  `COL1` bigint(20),
  UNIQUE KEY `UK_COL1` (`COL1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into UK_GCOL_VIRTUAL_18588 values("8502658334322817163");
prepare stmt from 'select col1 from UK_GCOL_VIRTUAL_18588 where col1 between ? and ? or col1 < ?';
set @a=5516958330762833919, @b=8551969118506051323, @c=2887622822023883594;
execute stmt using @a,@b,@c;
set @a=-1696020282760139948, @b=-2619168038882941276, @c=-4004648990067362699;
execute stmt using @a,@b,@c;
select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
```

### 2. What did you expect to see? (Required)
release-4.0 & release-5.0
```
mysql> execute stmt using @a,@b,@c;
Empty set (0.00 sec)

mysql> select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
release-5.1 & release-5.2 & master
```
mysql> execute stmt using @a,@b,@c;
+---------------------+
| col1                |
+---------------------+
| 8502658334322817163 |
+---------------------+
1 row in set (0.00 sec)

mysql> select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
Empty set (0.00 sec)

```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.1.1-58-gdc079337e
Edition: Community
Git Commit Hash: dc079337ef0c9d78eec2d2acb1eb31e12117d29b
Git Branch: release-5.1
UTC Build Time: 2021-09-22 02:01:55
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by Reminiscent** [comment]
mysql> prepare stmt from 'select col1 from UK_GCOL_VIRTUAL_18588 where col1 between ? and ? or col1 < ?';
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=5516958330762833919, @b=8551969118506051323, @c=2887622822023883594;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @a,@b,@c;
+---------------------+
| col1                |
+---------------------+
| 8502658334322817163 |
+---------------------+
1 row in set (0.01 sec)

mysql> explain for connection 3;
+------------------------+---------+-----------+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| id                     | estRows | task      | access object                                    | operator info                                                                                               |
+------------------------+---------+-----------+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
| IndexReader_6          | 1.00    | root      |                                                  | index:IndexRangeScan_5                                                                                      |
| └─IndexRangeScan_5     | 1.00    | cop[tikv] | table:UK_GCOL_VIRTUAL_18588, index:UK_COL1(COL1) | range:[-inf,2887622822023883594), [5516958330762833919,8551969118506051323], keep order:false, stats:pseudo |
+------------------------+---------+-----------+--------------------------------------------------+-------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> set @a=-1696020282760139948, @b=-2619168038882941276, @c=-4004648990067362699;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @a,@b,@c;
+---------------------+
| col1                |
+---------------------+
| 8502658334322817163 |
+---------------------+
1 row in set (0.00 sec)

mysql> explain for connection 3;
+-----------------------+---------+-----------+--------------------------------------------------+--------------------------------+
| id                    | estRows | task      | access object                                    | operator info                  |
+-----------------------+---------+-----------+--------------------------------------------------+--------------------------------+
| IndexReader_6         | 1.00    | root      |                                                  | index:IndexFullScan_5          |
| └─IndexFullScan_5     | 1.00    | cop[tikv] | table:UK_GCOL_VIRTUAL_18588, index:UK_COL1(COL1) | keep order:false, stats:pseudo |
+-----------------------+---------+-----------+--------------------------------------------------+--------------------------------+
2 rows in set (0.00 sec)

mysql> execute stmt using @a,@b,@c;
+---------------------+
| col1                |
+---------------------+
| 8502658334322817163 |
+---------------------+
1 row in set (0.00 sec)

mysql> select @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      1 |
+------------------------+
1 row in set (0.00 sec)

mysql> explain select col1 from UK_GCOL_VIRTUAL_18588 where col1 between -1696020282760139948 and -2619168038882941276 or col1 < -4004648990067362699;
+-------------------------+---------+-----------+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                      | estRows | task      | access object               | operator info                                                                                                                                                                            |
+-------------------------+---------+-----------+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| TableReader_7           | 0.33    | root      |                             | data:Selection_6                                                                                                                                                                         |
| └─Selection_6           | 0.33    | cop[tikv] |                             | or(and(ge(test.uk_gcol_virtual_18588.col1, -1696020282760139948), le(test.uk_gcol_virtual_18588.col1, -2619168038882941276)), lt(test.uk_gcol_virtual_18588.col1, -4004648990067362699)) |
|   └─TableFullScan_5     | 1.00    | cop[tikv] | table:UK_GCOL_VIRTUAL_18588 | keep order:false, stats:pseudo                                                                                                                                                           |
+-------------------------+---------+-----------+-----------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)

**Comment by Reminiscent** [comment]
The root case is when we rebuild the `IndexReader`, the condition left the `or` condition is constant false, so it will be convert to `indexFullScan`. More details, for the condition `col1 between $a and $b or col1 < $c`,  when `$a > $b` it wll be converted like `false or col1 < $3`. Then it will get the `indexFullScan`.

**Comment by Reminiscent** [comment]
In order to solve this problem, when we generate the `indexReader` without `selection` we need to check whether the condition contains the lazy constant.
