### ISSUE TITLE
Make fails with cannot find package `context`

### ISSUE THREAD

**Issue by zzl0** [pingcap/tidb#2826]
## What did I do?

``` shell
$ git clone https://github.com/pingcap/tidb.git $GOPATH/src/github.com/pingcap/tidb
$ cd $GOPATH/src/github.com/pingcap/tidb
$ make
```
## What did I expect to see?

nothing

## What did I see instead?

```
session.go:21:4: cannot find package "context" in any of:
```

## What version of Go am I using (`go version`)?

1.6

## How did I workaround this?

Upgrade my go version to 1.8.

## The root cause and possible way to fix it?

`context` became part of the standard library in Go 1.7, but [quick start](https://github.com/zzl0/tidb/blob/master/docs/QUICKSTART.md#pre-requirement) says tidb support Go >= 1.5.

Looking at the code, it seems tidb is inconsistent in the usage of `context` package, some files still use `golang.org/x/net/context`, should we use the standard `context` package and upgrade version Go >= 1.7?

**Comment by siddontang** [comment]
Thanks @zzl0 

Now we must use `golang.org/x/net/context` uniformly, like our other projects do.
Using standard `context` seems to be caused by auto package import here,  /cc @shenli

**Comment by zzl0** [comment]
Maybe you should add go 1.5 ~ 1.8 in [CI](https://github.com/pingcap/tidb/blob/master/.travis.yml) to avoid such issue also.

**Comment by siddontang** [comment]
Good idea!

**Comment by zzl0** [comment]
@siddontang @shenli  https://github.com/pingcap/tidb/pull/2853

Actually tidb team choose to update the go version to 1.7.
