### ISSUE TITLE
The Lazy Loading of Statistics Results in Execution Plans Change during the TPCH benchmark

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#28272]
## Enhancement
Because of the lazy loading of statistics, some queries get suboptimal plans at the first several runs of the benchmark thought we have analyzed all the tables before the benchmark, which results in performance downgrade of the TPCH benchmark.
We should make an enhancement to make sure the optimizer have the accurate statistics and get the optimal plans as soon as possible.

**Comment by dbsid** [comment]
@yudongusa  with prepared-plan-cache enabled and goes GA, it's critical that we got the right plan from the first place, for the prepared statements.
it's possible this first-time-suboptimal-plan issue will be amplified. I think we should investigate into this enhancement in the following sprint.

**Comment by chrysan** [comment]
Fixed in https://github.com/pingcap/tidb/pull/30026, will close it.
