### ISSUE TITLE
Prepared statement with point get path can not be cached

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#28334]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run sysbench oltp_read_write workload on 6tidb + 6tikv topo, arm machine.
16 tables each with 10m rows

### 2. What did you expect to see? (Required)
As a result of pr #23238, all the prepared statement with point get path can not be cached.
with prepared plan cache enable, every little cpu and memory allocation on planner.Optimize

### 3. What did you see instead (Required)
18% cpu on planner.Optimize and 20% alloc_objects on planner.Optimize

![image](https://user-images.githubusercontent.com/2316425/134771893-36b6f846-0ae7-4de4-9811-6449458e04ed.png)

### 4. What is your TiDB version? (Required)

v5.1.1

**Comment by tiancaiamao** [comment]
Yes, prepared plan cache... also here https://github.com/pingcap/tidb/issues/26868
