### ISSUE TITLE
Auto_analyze collection mechanism optimization

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#28352]
cluster version：v5.2.1

At present, auto_analyze will continue to work according to the previous version of auto_analyze, but this will make the tidb_analyze_version parameter time zone meaningful. When the cluster is upgraded from less than v5.1.0, the new rules for collecting statistics will not be effective.
I know that there are some manual ways to solve this situation, but this is very unfriendly and there is a relatively high risk.
@yudongusa

**Comment by xuyifangreeneyes** [comment]
The issues is duplicate with #25422
