### ISSUE TITLE
diifferent behaviors result between tidb and mysql when use the update statement to update the same field multiple times in one statement

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#28370]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```

create table t(a int not null,b int);
insert into t values(1,1);
update t set a=null,a=2; ---check
```

### 2. What did you expect to see? (Required)

`update failed because of a can not set null`

### 3. What did you see instead (Required)

```
update success；

mysql> select * from t;
+---+------+
| a | b    |
+---+------+
| 2 |    1 |
+---+------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```

 Release Version: v5.2.0-nightly
Edition: Community
Git Commit Hash: 13be486682046c7e61ec6494fcb1845678eb8a6a
Git Branch: heads/refs/tags/v5.2.0-nightly
UTC Build Time: 2021-09-26 05:43:04
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by XuHuaiyu** [comment]
Actually, I think it's expected behavior in TiDB. The assignments are evaluated from left to right, we can update a 
I reported a [bug](https://bugs.mysql.com/bug.php?id=105784) to mysql see what does they thought.

**Comment by XuHuaiyu** [comment]
If we need to fix this behavior, we can add a not-null check during the building of `newRowData`.
https://github.com/pingcap/tidb/blob/891517f23ec3443d971423d30d54feaa08fb51b3/executor/update.go#L334-L386

We need to add the check after line 353 and line 380 separately like this:
``` go
			// check not-null
			if err = col.HandleBadNull(&val, e.ctx.GetSessionVars().StmtCtx); err != nil {
				return nil, err
			}
```

**Comment by fuzhe1989** [comment]
> Actually, I think it's expected behavior in TiDB. The assignments are evaluated from left to right, we can update a I reported a [bug](https://bugs.mysql.com/bug.php?id=105784) to mysql see what does they thought.

IMO it is worth to fix. Thanks for your investigation.

**Comment by XuHuaiyu** [comment]
The bug is verified by the MySQL verification team, close this issue now.
