### ISSUE TITLE
Trigger sintax from previous mysql database incomptable with TiDB

### ISSUE THREAD

**Issue by manne45** [pingcap/tidb#28381]
## General Question

I tried to load a MySQL 5.7 dump file into the TiDB cluster v5.2.1 but I face the following issue when the table has a trigger: 

```
$ mysql -u web -p -P 4000 -h 192.168.0.158 or3 < sta20210907.sql  
Enter password: 
ERROR 1064 (42000) at line 1186: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 72 near "TRIGGER traspaso_automatico_entrada_det
BEFORE INSERT ON detalle_entrada
FOR EACH ROW
BEGIN
   DECLARE idt INT(10);
   SET idt = (select count(*) from traspaso);
  INSERT INTO detalle_traspaso
(idTraspaso,clave,cantidad,hora,idtienda)
VALUES(idt,NEW.clave,NEW.cantidad,now(),1);
END */" 
$ 
```

The tables before this one were loaded successfully. 

the triggers are not supported ? 

Thanks in advance .

**Comment by morgo** [comment]
That's correct - triggers are not supported. This is documented here: https://docs.pingcap.com/tidb/stable/mysql-compatibility#unsupported-features

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
