### ISSUE TITLE
migrate test-infra to testify for `planner/core/rule_join_reorder_dp_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28397]

**Comment by johnhaxx7** [comment]
Hi @tisonkun, to migrate this file, 
`s *testJoinReorderDPSuite` in function `newMockJoin` will be removed, which will cause 
`s.ctx` at line 61 and `s.statsMap` at line 63 is not able to pass to this function. Please check details from here: 
https://github.com/pingcap/tidb/blob/ad9430039f54bb9af78d44831c176bc5eafcbba0/planner/core/rule_join_reorder_dp_test.go#L61

In this case, https://github.com/pingcap/tidb/blob/6b1010f40557fd4aac702477cb2517517fbaf663/planner/core/rule_join_reorder_dp.go#L26 might needs to be refactored to pass in the context and statsMap. Is it ok to do so or do you have a better idea?

**Comment by johnhaxx7** [comment]
+ @hawkingrei for more visibility

**Comment by tisonkun** [comment]
@johnhaxx7 thanks for working on this issue. For the specific problem, I'll directly submit a PR for this issue so that it's explained by code. You can help on the review side then.
