### ISSUE TITLE
Region error (will back off and retry) message

### ISSUE THREAD

**Issue by liji2003888** [pingcap/tidb#28437]
看grafana监控发现 2h时间有大量查询请求阻塞，duration时间很久。查看tikv.log 出现大量Region Error信息，不知道是否是这个原因导致，有什么办法可以解决：
` [WARN] [endpoint.rs:527] [error-response] [err="Region error (will back off and retry) message: \"peer is not leader for region 8077, leader may Some(id: 8080 store_id: 5)\`

TiDB Version:
`Release Version: v4.0.0
Edition: Community
Git Commit Hash: 689a6b6439ae7835947fcaccf329a3fc303986cb
Git Branch: heads/refs/tags/v4.0.0
UTC Build Time: 2020-05-28 01:37:40
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false`

![image](https://user-images.githubusercontent.com/4416960/134905644-91161a03-95b3-4327-abc1-388a55f6a353.png)

![image](https://user-images.githubusercontent.com/4416960/134905938-90bf6218-6cbb-4d98-af60-0709f3493a5b.png)

![image](https://user-images.githubusercontent.com/4416960/134905995-3f4a0ca0-c17b-4778-9cd8-9a2f3d3814c6.png)

KV 监控信息：
![image](https://user-images.githubusercontent.com/4416960/134906347-8b03d355-01c9-4b51-bb23-65bc070d6395.png)
![image](https://user-images.githubusercontent.com/4416960/134906373-8b7bab59-3cb0-42d5-bf75-9f1837d1f26b.png)

![image](https://user-images.githubusercontent.com/4416960/134906443-4c5b874b-a81f-440e-b0a2-ab3c6ed034af.png)

![image](https://user-images.githubusercontent.com/4416960/134906471-6d80fc4c-4ba4-4431-89b9-4ece7f08591c.png)

PD监控信息：
![image](https://user-images.githubusercontent.com/4416960/134913931-8557f8c1-2aef-4831-9794-7382d0604f60.png)

**Comment by jebter** [comment]
Please post your problem to https://asktug.com. They would reply to your problem ASAP.I will close this issue. If there are any updates, you can reopen it.
