### ISSUE TITLE
cmd/ddltest TestDDLSuiteTestForIssue24621 doesn't run

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28435]
This test was introduced by https://github.com/pingcap/tidb/pull/27556 .

But it is _not_ triggered by check_dev_2 or [integration_ddl_test](https://github.com/PingCAP-QE/ci/blob/main/jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy).

I create https://github.com/pingcap/tidb/pull/28433 to verify my statement.

**Comment by tisonkun** [comment]
![image](https://user-images.githubusercontent.com/18818196/134913647-96737c1b-b9bb-40d5-8cbf-c06bc988dcc9.png)

**Comment by tisonkun** [comment]
verify check_dev_2 won't be affected https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_check_2/detail/tidb_ghpr_check_2/35912/pipeline

**Comment by tisonkun** [comment]
![image](https://user-images.githubusercontent.com/18818196/134925150-af7ac6af-f20f-474f-8ed5-e36bb1a6be90.png)

**Comment by Defined2014** [comment]
It was moved to tidb repo by #9052. Seems we will run it in IT after merge. I will check it.

**Comment by Defined2014** [comment]
I found the `tidb_ghpr_integration_ddl_test` will run those test cases.

The code:
https://github.com/PingCAP-QE/ci/blob/a93f3d641c45c8cfb1039be1317f22a134cbeb70/jenkins/pipelines/ci/tidb/tidb_ghpr_integration_ddl_test.groovy#L278-L301

The result:
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_ddl_test/detail/tidb_ghpr_integration_ddl_test/6333/pipeline/65

**Comment by tisonkun** [comment]
@Defined2014 please check it carefully, the code snippet you quoted run some tests, but not the `TestDDLSuiteTestForIssue24621` in issue.

```groovy
        tests["Integration DDL Insert Test"] = {
            run("ddl_test", "ddl_insert_test", "^TestSimple.*Insert\$")
        }

        tests["Integration DDL Update Test"] = {
            run("ddl_test", "ddl_update_test", "^TestSimple.*Update\$")
        }

        tests["Integration DDL Delete Test"] = {
            run("ddl_test", "ddl_delete_test", "^TestSimple.*Delete\$")
        }

        tests["Integration DDL Other Test"] = {
            run("ddl_test", "ddl_other_test", "^TestSimp(le\$|leMixed\$|leInc\$)")
        }

        tests["Integration DDL Column Test"] = {
            run("ddl_test", "ddl_column_index_test", "^TestColumn\$")
        }

        tests["Integration DDL Index Test"] = {
            run("ddl_test", "ddl_column_index_test", "^TestIndex\$")
        }
```
