### ISSUE TITLE
migrate test-infra to testify for `func_max_min_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28513]

**Comment by budougumi0617** [comment]
@tarzan114 
Hi, I have resolved a refactoring issue for the same package. My changes included refactoring of the methods that called by the tests in the target file of this issue. see my PR ( #28548 ) for more details. If you have not started working on this issue, I will take over this issue.
I will wait for your reply.

regards,

**Comment by tarzan114** [comment]
@budougumi0617 your welcome to make changes now that i unassigned myself thanks

**Comment by budougumi0617** [comment]
@tarzan114 I appreciate your quick response! I handle this issue.
