### ISSUE TITLE
Add support for sql_require_primary_key

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#28544]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

This is a feature from MySQL 8.0:
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sql_require_primary_key

It allows you to enforce tables have a primary key. ~It has more meaning in MySQL because row-based replication benefits from it~ (**Edit that:** it very much applies to TiCDC), and InnoDB is less efficient when using its internal primary key. But it's still useful.

**Describe alternatives you've considered:**

N/A - compatibility feature.

**Teachability, Documentation, Adoption, Migration Strategy:**

Compatibility feature

**Comment by 7yyo** [comment]
hello @morgo  I want to try to add this feature.

**Comment by morgo** [comment]
> hello @morgo I want to try to add this feature.

Glad to hear! Please feel free to /assign it to yourself.

**Comment by morgo** [comment]
I discovered that TiCDC does not replicate tables without a primary key by default (although there is now [an option for it](https://github.com/pingcap/tiflow/pull/1005)). So this feature request actually has a lot of usage in TiDB to ensure CDC replication.

**Comment by dveeden** [comment]
Note that MySQL now is getting another related feature that helps with this: [Generated Invisible Primary Keys](https://dev.mysql.com/doc/refman/8.0/en/create-table-gipks.html). It seems that this is already in the docs, but the version of MySQL that contains this (8.0.30) is not yet released.

This may also benefit TiCDC etc if we would implement it in TiDB.
