### ISSUE TITLE
migrate test-infra to testify for `executor_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28577]
All tests listed below is moved to `executor_legacy_test.go` file.

* [x] #33425
* [x] #33426
* [x] #33427
* [x] #33428
* [x] #33429
* [x] #33430
* [x] #33431
* [x] #33432
* [x] #33433
* [x] #33434
* [x] #33435
* [x] #33436
* [x] #33437
* [x] #33438
* [x] #33439
* [x] #33440
* [x] #33441
* [x] #33442
* [x] #33443

**Comment by karuppiah7890** [comment]
I see lot of test suite setup and tear down as part of this test. Just from an overview, it looks like we can also do the setup at test level. But if we still want to do the setup at test suite level - we can choose to use `TestMain` but that would be doing setup for all tests in the package and not just `executor_test.go` test, or we can try to use testify's test suite feature. Let me know what you folks think

cc @tisonkun

**Comment by tisonkun** [comment]
Hi @karuppiah7890 ! There is a similar case https://github.com/pingcap/tidb/pull/28300 you can refer to. I think it can directly answer your question. Let me know if still something unclear.

**Comment by karuppiah7890** [comment]
So, if I'm understanding right, we do setup once in a test and then use `t.Run` and run sub tests?

**Comment by hawkingrei** [comment]
@tisonkun @XuHuaiyu Yes, I think so. I start to split tests.

**Comment by tisonkun** [comment]
@hawkingrei I suggest you try to migrate tests rely on testdata so that we can remove the legacy testdata code.

**Comment by tisonkun** [comment]
@hawkingrei @karuppiah7890 I've split this issue into workable subtasks, and the skeleton is constructed in #33394 and you can refer to an example in #33402.

Welcome to take over some of the subtasks.

**Comment by tisonkun** [comment]
Accidentally closed. Reopen.
