### ISSUE TITLE
migrate test-infra to testify for `inspection_common_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28589]

**Comment by YufeiCh** [comment]
As the day of the behind committer has passed 22 days, I think I can self-assigned it

**Comment by tisonkun** [comment]
@YufeiCh I think there is already a pull request for this #30818. You can review it instead of duplicate works.

**Comment by YufeiCh** [comment]
> 

I agree with that, but the test suite in `inspection_summary_test` I want to migrate is related with this, so I want to migrate them together.

**Comment by YufeiCh** [comment]
@tisonkun the test suite is defined in `inspection_summary_test`, of course I will remove it after the migration, but this test suite is now used in `inspection_common_test`, the only way I can do without duplicated works is to move the definition of this test suite to `inspection_common_test`, and it will confict with the PR mentioned in this issue. So I want to migrate them all. But If you think move the test suite definition to inspection_common is better, I will do what you like.

**Comment by tisonkun** [comment]
@YufeiCh thanks for your information! I'm merging #30818 now, please rebase your work on the new master later.

**Comment by YufeiCh** [comment]
> 

OK，Thanks for your quick reply.
