### ISSUE TITLE
migrate test-infra to testify for `statement_context_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28619]

**Comment by hawkingrei** [comment]
@feitian124 Are you completing it?

**Comment by feitian124** [comment]
not yet

**Comment by hawkingrei** [comment]
> not begin, what can i do for you? @hawkingrei 

It is so easy. I plan to finish it in this week.

**Comment by feitian124** [comment]
yes, i start work from easy ones.
i assined myself about 10 issues and plan finish them this week.
if you are eager to finish some one in advance,  feel free to take over and leave a message in the issue.
i will check issue status before start work.

and this one is finished, please check pr, thanks. @hawkingrei
