### ISSUE TITLE
Check numeric overflow and raise ERROR 1690 (22003)

### ISSUE THREAD

**Issue by mtunique** [pingcap/tidb#2862]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
select power(10, 700);
```

2. What did you expect to see?
```
ERROR 1690 (22003): DOUBLE value is out of range in 'pow(10,700)'
```

3. What did you see instead?

```
+----------------+
| power(10, 700) |
+----------------+
|           +Inf |
+----------------+
1 row in set (0.01 sec)
```

We need check numeric value when we return value from builtin function.

**Comment by mtunique** [comment]
math operators also have this issue.

tidb:
```
select 10000000000000000000 + 10000000000000000000;
ERROR 1105 (HY000): operation overflo
```

mysql:
```
select 10000000000000000000 + 10000000000000000000;
ERROR 1690 (22003): BIGINT UNSIGNED value is out of range in '(10000000000000000000 + 10000000000000000000)'
```

**Comment by zhexuany** [comment]
@coocood I have some free time this weekend. If you do not mind, I want to take this.

**Comment by shenli** [comment]
@zhexuany Great! If you need any help, please let us know.

**Comment by coocood** [comment]
@zhexuany 
Looking forward to your PR.

**Comment by zhexuany** [comment]
@mtunique 

Could you tell me how to reproduce this bug?
~~~
select power(10, 700);
~~~

I connect tide-server via mysql, and above command give desired result. 

~~~
tidb> select power(10, 700);
+----------------+
| power(10, 700) |
+----------------+
|           +Inf |
+----------------+
1 row in set (0.00 sec)
~~~
