### ISSUE TITLE
Register the built-in function you're working on here.

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#2863]
In order to avoid repetitive work, if possible, please register the builtin function you're working on in the issue to let others know.  ^_^

**Comment by spongedu** [comment]
[builtin: add is_ipv4 built-in function](https://github.com/pingcap/tidb/pull/2864)

**Comment by silenceper** [comment]
[builtin: add oct built-in function](#2835)

**Comment by ariesdevil** [comment]
https://github.com/pingcap/tidb/pull/2845

**Comment by hiwjd** [comment]
[builtin: add insert built-in function](https://github.com/pingcap/tidb/pull/2855)

**Comment by spongedu** [comment]
[builtin: add any_value built-in function](https://github.com/pingcap/tidb/pull/2866)

**Comment by hsqlu** [comment]
[builtin: add elt built-in function]()

**Comment by spongedu** [comment]
[builtin: add is_ipv6 built-in function](https://github.com/pingcap/tidb/pull/2872)

**Comment by spongedu** [comment]
[builtin: add uuid built-in function](https://github.com/pingcap/tidb/pull/2875)

**Comment by ariesdevil** [comment]
[builtin: add format built-in functioin](https://github.com/pingcap/tidb/pull/2883)

**Comment by keviswang** [comment]
[build-in: add degrees, truncate build-in function](https://github.com/pingcap/tidb/pull/2886)

**Comment by cosmtrek** [comment]
[builtin: add maketime built-in function](https://github.com/pingcap/tidb/pull/2889)

**Comment by dsh0416** [comment]
[build-in: add cot build-in function](https://github.com/pingcap/tidb/pull/2909)

**Comment by zs634134578** [comment]
[builtin: add sha2 built-in function](https://github.com/pingcap/tidb/pull/2914)

**Comment by codeworm96** [comment]
[builtin: add quarter built-in function](https://github.com/pingcap/tidb/pull/2919)

**Comment by wusphinx** [comment]
[builtin: create-digest built-in function](https://github.com/pingcap/tidb/pull/2935/commits/42739a6d370527b696fdc101dcd5431075308023)

**Comment by spongedu** [comment]
#2983

**Comment by spongedu** [comment]
#2983 Built-in Function: 'TO_DAYS'

**Comment by spongedu** [comment]
#2984 builtin: 'TO_DAYS' builtin-function

**Comment by spongedu** [comment]
#2992 Builtin: 'TIMESTAMPADD' builtin function

**Comment by myrice** [comment]
[builtin: add ‘period_add’ built-in function](https://github.com/pingcap/tidb/pull/3001)

**Comment by fudali113** [comment]
[builtin: add ‘export_set’ built-in function](https://github.com/pingcap/tidb/pull/3036)

**Comment by woodpenker** [comment]
builtin: add ‘period_diff’ built-in function

**Comment by woodpenker** [comment]
[builtin: add ‘to_base64’ built-in function](https://github.com/pingcap/tidb/pull/3055)
