### ISSUE TITLE
migrate test-infra to testify for `ddl/ddl_worker_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28639]

**Comment by fanglee101** [comment]
[b]https://icq.im/AoLGnKtUsQZKGmUTjTA

https://t.me/chinadebitbank


This is arqidarknet from

torre,zorldcard, market pro,

I sell first hand pos data,atm datas,resellers welcome,
usable pos,atm 

bank logs,email access,password
RDP
hack bibbles
Cvv=address
eu-usa-asia


minimum order is  10pieces 

no test for new clients* consideration could be consider on basis.

[/b]


![photo_2021-10-06_08-41-11](https://user-images.githubusercontent.com/92568711/137446409-194422c9-2171-45d3-98a1-55e57fab10a7.jpg)
