### ISSUE TITLE
migrate test-infra to testify for `ddl/db_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#28636]
* [x] #32855
* [x] #32863
* [x] #32935
* [x] #32954
* [x] #32961
* [x] #32962
* [x] #32963
* [x] #32964
* [x] #32965
* [x] #32955
* [x] #32966
* [x] #32967
* [x] #33004

**Comment by tisonkun** [comment]
I'm splitting tests in this file.

**Comment by hawkingrei** [comment]
> I'm splitting tests in this file.

Good Job!

**Comment by wjhuang2016** [comment]
I plan to rewrite some tests related to cancelDDLJob.
Specifically, 

- [ ] TestCancelAddIndexPanic
- [ ] TestCancelDropIndex
- [ ] TestCancelDropPrimaryKey
- [ ] TestCancelTruncateTable
- [ ] TestCancelRenameIndex
- [ ] TestCancelDropTableAndSchema
- [ ] TestCancelAddTableAndDropTablePartition
- [ ] TestCancelJobWriteConflict
- [ ] TestPartitionCancelAddIndex
- [ ] TestPartitionCancelAddPrimaryKey
- [ ] TestCancelAddIndex1
- [ ] TestModifyColumnRollBack

**Comment by tisonkun** [comment]
@wjhuang2016 you may create an issue to do the rewriter at once or in multiple subtasks. I'm afraid that the todo list here would be forgotten later 🤣

**Comment by tisonkun** [comment]
Finally we finish it! Closed.
