### ISSUE TITLE
Increase default value for prepared-plan-cache.capacity from 100 to 1000+

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#28665]
## Enhancement
Typically a transaction for core-banking application will contains several hundreds of statement. The default value 100 for prepared-plan-cache.capacity is way too small, I'll propose to increase the default value to 1000+, anyway we have the memory-guard-ratio to protect from oom.

**Comment by tiancaiamao** [comment]
Is this value configurable?

**Comment by shaoxiqian** [comment]
@qw4990
more systench test case about the difference between 100 and 1000 with the threads 400 and 800
Config:
tables=32
table-size=10000000


### **oltp_update_non_index**
|400并发|800并发 
|--|--| 
|<table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>66824.24</td><td>68946.85</td><td>+3.18%</td></tr><tr><td>Latency (avg)</td><td>5.98</td><td>5.8</td><td>-3.01%</td></tr><tr><td>95th</td><td>13.22</td><td>12.30</td><td>-6.96%</td></tr></table>| <table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>77791.53</td><td>79277.98</td><td>+1.91%</td></tr><tr><td>Latency (avg)</td><td>10.28 </td><td>10.09</td><td>-1.85%</td></tr><tr><td>95th</td><td>23.10</td><td> 22.69</td><td>-1.77%</td></tr> </table>| 

### **oltp_update_index**
|400并发|800并发 
|--|--| 
|<table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>27559.82</td><td>27940.78</td><td>+1.83%</td></tr><tr><td>Latency (avg)</td><td>14.511</td><td>14.31</td><td>-1.38%</td></tr><tr><td>95th</td><td>25.74</td><td>25.28</td><td>-1.79%</td></tr></table>| <table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>30537.16</td><td>32723.53</td><td>+7.16%</td></tr><tr><td>Latency (avg)</td><td>25.97</td><td>24.44</td><td>-1.79%</td></tr><tr><td>95th</td><td>49.21</td><td>44.17</td><td>-10.24%</td></tr> </table>| 

### **oltp_insert**
|400并发|800并发 
|--|--| 
|<table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>36563.15</td><td>40551.89</td><td>+10.91%</td></tr><tr><td>Latency (avg)</td><td>21.87</td><td>19.72</td><td>-9.83%</td></tr><tr><td>95th</td><td>46.63</td><td>34.95</td><td>-25.05%</td></tr></table>| <table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>30537.16</td><td>32723.53</td><td>+7.16%</td></tr><tr><td>Latency (avg)</td><td>25.97</td><td>24.44</td><td>-1.79%</td></tr><tr><td>95th</td><td>49.21</td><td>44.17</td><td>-10.24%</td></tr> </table>| 
### **oltp_point_select**
|400并发|800并发 
|--|--| 
|<table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>230893.5</td><td>216613.29</td><td>-6.18%</td></tr><tr><td>Latency (avg)</td><td>1.73</td><td>1.85</td><td>+6.94%</td></tr><tr><td>95th</td><td>6.43</td><td>7.04</td><td>+9.49%</td></tr></table>| <table> <tr><th></th><th>100</th><th>1000</th><th>Diff(%)</th></tr><tr><td>QPS</td><td>230893.54</td><td>216613.29</td><td>-6.18%</td></tr><tr><td>Latency (avg)</td><td>1.73</td><td>1.85</td><td>+6.94%</td></tr><tr><td>95th</td><td>6.43</td><td>7.04</td><td>+9.49%</td></tr> </table>|

**Comment by dbsid** [comment]
@tiancaiamao @qw4990
From the test, for cases such as sysbench read-write on 32 tables, the number of prepared statement exceeds 100.
By increasing the limit from 100 to 1000, we basically get more qps、less cpu usage and lower latency, at the cost of more memory usage. We think it's a reasonable tradeoff. In real-world, it's super hard for user to spot the size limitation of plan cache and extend it correspondingly.
For other cases when the number of prepared statements does not exceeds 100 and just use query interface, we don't see performance penalty from this change.
