### ISSUE TITLE
PD version in the `cluster_info` table is wrong

### ISSUE THREAD

**Issue by HunDunDM** [pingcap/tidb#28679]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

* Start a cluster and patch PD or TiKV or TiFlash
* `SELECT type,version FROM information_schema.cluster_info WHERE type = 'pd';`

### 2. What did you expect to see? (Required)

* The PD version is displayed correctly.

### 3. What did you see instead (Required)

If TiKV is patched, and PD is not patched, then

```
+------+-------------+
| type | version     |
+------+-------------+
| pd   | 5.3.0-alpha |
+------+-------------+
```

If PD is patched, and TiKV is not patched, then

```
+------+---------+
| type | version |
+------+---------+
| pd   | 5.1.1   |
+------+---------+
```

### 4. What is your TiDB version? (Required)

v5.2.1

**Comment by HunDunDM** [comment]
The [code](https://github.com/pingcap/tidb/blob/v5.1.2/infoschema/tables.go#L1578) uses the `ClusterVersion` field to fill in the PD's `Version` field. In the PD, this field is used to indicate the node with the smallest version among all Store nodes (TiKV, TiFlash, etc.) in the cluster. It is used for version control and is not the version of the PD itself.

**Comment by 7yyo** [comment]
> The [code](https://github.com/pingcap/tidb/blob/v5.1.2/infoschema/tables.go#L1578) uses the `ClusterVersion` field to fill in the PD's `Version` field. In the PD, this field is used to indicate the node with the smallest version among all Store nodes (TiKV, TiFlash, etc.) in the cluster. It is used for version control and is not the version of the PD itself.

Should use `/pd/api/v1/status`？
