### ISSUE TITLE
Add new SQL syntax: limit n after whereclause

### ISSUE THREAD

**Issue by xialvjun** [pingcap/tidb#2874]
I know, it's really stupid to ask for new syntax, let alone syntax for sql.  But I do think it's a good idea, it solves the problem -- deep pagination. To show my idea more clearly, I use chinese:

SQL 标准中的分页是`limit n offset m`，加上排序的完整 SQL 语句则是`select * from table_a order by column_a limit n offset m`。
这在单机数据库上没有什么问题，就是先 order，然后 offset，最后 limit，取出需要的数据。。。
但是在集群数据库上，假如数据库集群有 p 台机器，且是深度分页，也就是 offset 非常大，例如 10000，则需要在每台机器中都 order，取出前 `offset + limit = m + n` 条数据，总共是 `(m+n)*p` 条数据，然后对这些数据再次排序，取出 offset m 之后的 limit n 条数据。。。。这种方式在 offset m 太大的时候，性能就太低了。。。

可是假如加上了新语法`limit n after id=the_last_id_i_accessed`，加上排序的完整 SQL 语句是`select * from table_a order by column_a limit n after id=the_last_id_i_accessed`。使用这种语法，深度分页的问题就基本上算是解决了的。
假设在集群上，仍然是 p 台机器，这条语句的执行步骤是，先执行`select * from table_a where id=the_last_id_i_accessed`，得到一个列表，对此列表进行 order 排序，取最后一条。然后使用这一条为基准，在 p 台机器上执行 order，取出各台机器上的按 order 排序规则会被排在此条记录后面的 limit n 条数据，总共是 `n*p` 条数据，然后把这些数据集合起来再次排序，取出前 limit n 条。。。这种逻辑相当于把 `(m+n)*p` 转变为 `n*p` ，也就是说 m 再大也没有关系，深度分页就这么解决了。。。

当然，事实上这并不是真正解决深度分页，因为两者的使用场景完全不一样。。。offset 是在毫无之前的查询基础就直接查询，例如我在没有查询前 999 页，就直接查询第 1000 页的数据（虽然我觉得这在现实中并没有多少使用场景），而 after whereclause 则必须要求之前查到了第 999 页的数据，得到最后一条记录，以此记录为基准得到第 1000 页的数据（个人感觉这种使用场景在现实中更常见）。。。

所以，真心希望你们能考虑下。。。当然，可能这个想法里没考虑到一些数据库的基本问题，这种语法没法实现，或者就算实现也达不到想要的效果，feel free to close this issue，如果是这样的话，能讲下为什么当然更好。

**Comment by hanfei1991** [comment]
Well, `select * from table_a order by column_a limit n after id=the_last_id_i_accessed` totally equals to `select * from table_a where id>the_last_id_i_accessed order by column_a limit n`. It seems we don't need to do that. Thank you for your suggestion :)

**Comment by hanfei1991** [comment]
Tikv uses range based partition. So select * from t where id > k will generate a plan that seeks for k directly.

**Comment by xialvjun** [comment]
No, they are not equal. ID column doesn't participate in the filter.

**Comment by xialvjun** [comment]
|id|age|
|:--|--:|
|97|13|
|34|25|
|25|46|
|36|23|
|78|35|
|12|45|

`select * from person order by age limit 2 after id=25`

|id|age|
|:--|--:|
|97|13|
|36|23|
|34|25|
|78|35|
|12|45|
|25|46|

Then it get:

|id|age|
|:--|--:|
|78|35|
|12|45|

**Comment by hanfei1991** [comment]
Well, I mean ID is PK handle. Your solution only works on unique column and cannot locate fast

**Comment by xialvjun** [comment]
@hanfei1991 , So I said:

> 先执行`select * from table_a where id=the_last_id_i_accessed`，得到一个列表，对此列表进行 order 排序，取最后一条。

如果取到的列表里没有数据，那就相当于取第一页的 n 条。。。这样，where clause 就不需要是 PK 了，而是一个通用意义上的 filter。

**Comment by hanfei1991** [comment]
Well, I try to understand you but fail. 
> 先执行select * from table_a where id=the_last_id_i_accessed，得到一个列表，对此列表进行 order 排序，取最后一条。
What is the meaning of `id`? the record handle ? Then you will always get a record instead of a list.

**Comment by xialvjun** [comment]
Well, just change id to other column.

`select * from person order by age limit 2 after name='xialvjun';`

Then if there is a table with data:

|id|name    |age|
|:-|:-------|:--|
|97|zhangsan|13|
|34|xialvjun|25|
|25|lisi    |46|
|36|wangwu  |23|
|78|zhaoliu |35|
|12|xialvjun|32|

First, we run `select * from person where name='xialvjun' order by age;`, get:

|id|name    |age|
|:-|:-------|:--|
|34|xialvjun|25|
|12|xialvjun|32|

Then, we run `order by age` to the total table, get: 

|id|name    |age|
|:-|:-------|:--|
|97|zhangsan|13|
|36|wangwu  |23|
|34|xialvjun|25|
|12|xialvjun|32|
|78|zhaoliu |35|
|25|lisi    |46|

Then we need `limit 2 after name='xialvjun';`, it means both the two rows are after everyone whose name is 'xialvjun'... Then, `78 zhaoliu` is after `34 xialvjun`, and it's after `12 xialvjun` too, so it's include, `25 lisi` is after `34 xialvjun`, and it's after `12 xialvjun` too, so it's include too.

Infact, since `12 xialvjun` is after `34 xialvjun`, so every row which is after `12 xialvjun` must be after `34 xialvjun`, so we needn't think of `34 xialvjun`, that's less calculation.

**Comment by xialvjun** [comment]
Since `name` column is not unique, if we use `name` as the after's where clause, we may lose those rows between the two `xialvjun`(well, the data in my table doesn't have rows between them).  So, use `id` as the after's where clause is a better choice.

**Comment by hanfei1991** [comment]
But how you locate the id in order of age? you must sort all the data in table.

**Comment by xialvjun** [comment]
I don't know why must it sort all the data in table but offset doesn't.  Just treat the rows as a PartialComparable, then **select a row** and then **top n row** bigger than it. The comparison just happens at `top n row`. But if we use `offset m`, we also need `top m+n row`, then select the last `n` row.

I think `offset m` do many more comparisions than `after where_clause`.

**Comment by coocood** [comment]
What if there is another 'xialvjun' and the age is 47, but the rows you want is zhaoliu and lisi?

**Comment by xialvjun** [comment]
Then you get nothing since there is no data after 'xialvjun 47'...
Of course you can `select * from person order by age limit 2 after name='xialvjun' and age=32;`
The `name='xialvjun' and age=32` is just one where clause and be controled by `after`.
So I said:

> So, use `id` as the after's where clause is a better choice.

**Comment by coocood** [comment]
I think this problem can be solved by creating an multi-column index `(age, id)`, the id is the primary key, then the where condition can be `select * from t where age > xx and id > yy limit 2`.

**Comment by xialvjun** [comment]
Well, infact, it can be repeated by:
```js
var last_row = sql(`select * from person where name='xialvjun';`)[0];
var result;
if(last_row) {
  result = sql(`select * from person where age>${last_row.age} order by age limit 2`);
  // it has nothing to do with id
} else {
  result = sql(`select * from person order by age limit 2`);
}
```

It's just repeat the order in the filter to filter the `offset m` out.
But if order and where condition is complex, things maybe different.

**Comment by xialvjun** [comment]
Nothing has to with ID, and maybe the ID is UUID.

**Comment by coocood** [comment]
Do you agree that the query `select * from t where age > xx and id > yy order by age, id limit 2` can solve the paging problem?

**Comment by hanfei1991** [comment]
I mean you need to find the position of `last_id`, how can you do it?

**Comment by xialvjun** [comment]
No, id doesn't participate in any sort or filter. You can see it just in the above data:
```
// with after syntax, the sql is `select * from person order by age limit 2 after name='xialvjun';`, result should be:
78	zhaoliu	35
25	lisi	46
// use sql `select * from person where age>32 and id>12 order by age, id limit 2;`
// the 32 and 12 is from `12	xialvjun	32`. then the result will be:
78	zhaoliu	35
25	lisi	46
// Well, the result is the same. But if we change lisi's id from 25 to 1, then the result of after syntax will not change, but the result of your sql will be only one `78	zhaoliu	35`

**Comment by coocood** [comment]
@xialvjun 
Please run the query on a real MySQL server and verify the result.

**Comment by xialvjun** [comment]
What do you mean by `find the position of last_id, how can you do it?` ..... 
I found the last_row with the after's where clause, then of course I can get the last_id. As to the after's where clause, it's the client give it to me. Why client has the where clause, because users read data from top to bottom normally.

**Comment by xialvjun** [comment]
real mysql

```
id     name       age
97	zhangsan	13
34	xialvjun	25
1	lisi	46
36	wangwu	23
78	zhaoliu	35
12	xialvjun	32
```

If with after syntax: `select * from person order by age limit 2 after name='xialvjun';`
So I need `select * from person where name='xialvjun' order by age;` and get the last one.
excute it and get:

```
34	xialvjun	25
12	xialvjun	32
```

So I pick `12	xialvjun	32`....

Then use your sql `select * from t where age > xx and id > yy order by age, id limit 2`, replace `xx` to `32` and `yy` to `12`, it's `select * from person where age > 32 and id > 12 order by age, id limit 2;`.   excute it and got:

```
78	zhaoliu	35
```

I run it with navicat, a gui mysql client, so it's not easy to copy, But the result is it.


Then if with after syntax. First, leave out the where clause and limit clause, just run `select * from person order by age`, it's: 

```
97	zhangsan	13
36	wangwu	23
34	xialvjun	25
12	xialvjun	32
78	zhaoliu	35
1	lisi	46
```

Then I want to get the top (limit 2) row after `name='xialvjun'`, it's: 

```
78	zhaoliu	35
1	lisi	46
```

**Comment by coocood** [comment]
I'm sorry, my query is not correct.
The correct query should be:
```
select * from t where (age = 32 and id > 12) or (aga > 32) order by age, id limit 2
```

**Comment by coocood** [comment]
@xialvjun 
This should get the expected rows.

**Comment by hanfei1991** [comment]
@xialvjun Of course you can get the value of `last_id`, if you want limit 2, you just read 2 records from the beginning of `last_id`. But the hardest question is: after you sort the age, how can you get the position of `last_id`? find one by one ? remember the id is out of order.

**Comment by xialvjun** [comment]
@coocood, well, just as
> result = sql(`select * from person where age>${last_row.age} order by age limit 2`);

but your sql is more accurate. But what if the id is uuid, or order by age desc.

Well, I have to admit we can achieve it with two sql excution, just need the server know more about SQL parse grammar. If it's

 `select * from person where age>20 and money<100 order by money desc limit 2 after id=123`,

 then the server need to excute

 `select * from person where age>20 and money<100 and id=123 order by money desc`, 
then 
`select * from person where age>20 and money<100 and (money<${last_row.money} or (money=${last_row.money} and id<${last_row.id}  ) ) order by money desc limit 2;`

I don't know if it is `id<${last_row.id}` or `id<${last_row.id}` and if we should add order by `id`...And it's at the imagine: ID is autoincreament.

**Comment by coocood** [comment]
@xialvjun 
If uuid is unique, it is the same as id.
If order by age desc, we can just change where to `(age = 32 and id < 12) or (age < 32)`.

**Comment by xialvjun** [comment]
Well, (age<=32 and id!=12) is less code.

**Comment by xialvjun** [comment]
OK, thanks. we can close this issue.

**Comment by coocood** [comment]
@xialvjun 
Not at all.
