### ISSUE TITLE
Placement option of FOLLOWERS=4 not supported

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#28767]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> CREATE TABLE t1 (a int) FOLLOWERS=4;
ERROR 1105 (HY000): failed to notify PD the placement rules: "[PD:placement:ErrBuildRuleList]build rule list failed, needs at least one leader or voter for range {7480000000000000FF5000000000000000F8, 7480000000000000FF5100000000000000F8}"
```

### 2. What did you expect to see? (Required)

This should work. It implies there is a leader, and now 4 followers with no constraints.

### 3. What did you see instead (Required)

Error

### 4. What is your TiDB version? (Required)

```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v5.3.0-alpha-1064-gfd42198c3-dirty
Edition: Community
Git Commit Hash: fd42198c3916cbe666c6339784418db646d4eef6
Git Branch: revoke-all-with-role-syntax
UTC Build Time: 2021-10-12 00:13:16
GoVersion: go1.16.7
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

```

**Comment by morgo** [comment]
This was first commented on https://github.com/pingcap/tidb/issues/27974 under the subject of validation. But it should be a legal case that is accepted/translated by the rules engine.

**Comment by AilinKid** [comment]
inference about the unmentioned constraints, what do you think @xhebox @lcwangchao
