### ISSUE TITLE
Tracking issue of merge Dumpling into TiDB

### ISSUE THREAD

**Issue by okJiang** [pingcap/tidb#28775]
# Development Task
This issue traces the effort to merge Dumpling into TiDB.

Original discussion is on https://internals.tidb.io/t/topic/434/9, you can checkout the design document at #28477 .

- [x] https://github.com/pingcap/tidb/issues/28843
- [x] https://github.com/pingcap/tidb/issues/28844

**Comment by tisonkun** [comment]
A knowledge you may be interested in:

To keep the commit history during the merge phase, if you use GitHub merge mechanism to merge PR, the commit message generated looks like `blablabla (#xxx)` , where `#xxx` should be an issue of the repo before merged, but later becomes the repo after merge.

To fix this issue, you should change `#xxx` to `original-repo#xxx`, a viable script is:

```bash
FILTER_BRANCH_SQUELCH_WARNING=1 git filter-branch -f --msg-filter 'perl -pe "s/#(\d+)/pingcap\/dumpling#\$1/"' -- HEAD...master
```

See more [information](https://git-scm.com/docs/git-filter-branch) about the `git filter-branch` command.

**Comment by tisonkun** [comment]
@okJiang your comment was hidden since it's too long. You can just start work with the prepared branch https://github.com/tisonkun/tidb/tree/merge-dumpling . I'll write a blog on the git magics, hope you don't have to deal with it...

**Comment by tisonkun** [comment]
shall we close this issue as tasks done?

**Comment by okJiang** [comment]
> shall we close this issue as tasks done?

I also think so.
