### ISSUE TITLE
Remove juju/xxx in go.sum

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#28855]
## Enhancement
After #28642 and #25290, we removed all `juju` related module in `go.mod`. But we still have some indirect `juju` module import in TiDB which includes by `cockroachdb/pebble` and `tikv/pd`. I'm not sure is this a problem or not, just give some advices below.

`tikv/pd` already opened a [issue](https://github.com/tikv/pd/issues/4206) to process it. We can update `tikv/pd` version after close this issue.

`cockroachdb/pebble` doesn't remove `juju` module depended in master branch right now. I have a hacky way to remove it which is to add `replace github.com/flosch/pongo2 => github.com/flosch/pongo2/v4 v4.0.2` to go.mod. Not sure is this a good way or not.

If you have some advices, please comment below.

**Comment by Defined2014** [comment]
Pushed the PR, I think it's not graceful.
@bb7133 PTAL

**Comment by kennytm** [comment]
can we use [`exclude`](https://golang.org/ref/mod#go-mod-file-exclude) to prevent it from ever appearing again?

**Comment by kennytm** [comment]
> Do we still need `juju/errors` or not?

absolutely no

**Comment by Defined2014** [comment]
> > Do we still need `juju/errors` or not?
> 
> absolutely no

It's not make sense. :(

By the way, `exclude` is only for the specified commits, which may not be suitable for our problem.

And we have a plan to add license check in dairly CI to prevent such problems.
