### ISSUE TITLE
Support GBK for builtin encryption and compression functions

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#28876]
- [x] https://github.com/pingcap/tidb/issues/29156   @unconsolable
- [x] #29168
- [x] #29169               
- [x] https://github.com/pingcap/tidb/issues/29257 @JayL-zxl  // Do nothing.

@Defined2014 
- [x] https://github.com/pingcap/tidb/issues/29090
- [x] https://github.com/pingcap/tidb/issues/29092
- [x] https://github.com/pingcap/tidb/issues/29091 // Do nothing.
- [x] #29335 // Do nothing.
- [x] #29336 // Do nothing.
- [x] #29334 // Do nothing.
- [x] #29442 // Do nothing.

@hawkingrei 
- [x] https://github.com/pingcap/tidb/issues/29314 
- [x] https://github.com/pingcap/tidb/issues/29167
- [x] #29353
- [x] #29355
- [x] #29356

**Comment by zimulala** [comment]
> > Assigned `DesEncrypt` #29257 Could you help me related? @xiongjiwei @zimulala
> 
> Excuse me, do I need to implement the evalString function on desEncrypt by myself?

1. Done.
2. You need to update the `evalString`, maybe you can refer to https://github.com/pingcap/tidb/pull/29165.

**Comment by xiongjiwei** [comment]
> Excuse me, do I need to implement the evalString function on desEncrypt by myself?

we do not have `desEncrypt` for now, I will remove this issue, maybe you can choose another one.

**Comment by hawkingrei** [comment]
Assigned Encode #29314 Could you help me related? @xiongjiwei @zimulala

**Comment by zimulala** [comment]
> Assigned Encode #29314 Could you help me related? @xiongjiwei @zimulala


Could you simply describe what this issue does specifically？For example: the unified encode function

**Comment by hawkingrei** [comment]
> > Assigned Encode #29314 Could you help me related? @xiongjiwei @zimulala
> 
> Could you simply describe what this issue does specifically？For example: the unified encode function

Added a few words.
