### ISSUE TITLE
Integrate UT coverage with CI pipeline

### ISSUE THREAD

**Issue by purelind** [pingcap/tidb#28947]
Related to https://github.com/PingCAP-QE/devops-config/issues/32

To tracking UT coverage at daily basis, even commit basis, UT coverage should be integrated into CI pipeline.
An UT fail case report and an UT coverage report in junit xml format will be much helpful.

There are two problems in current ci for unit-test:
* Current ci for unit-test print test result to jenkins console, it is not convenient to view failed cases. 
* Need a better way to display Unit-test coverage and ensure unit-test coverage is not below the baseline.

For the two reasons above, i suggest uniform unit-test and coverage output format(Junit XML). 

How to do?
1. use [go-junit-report](github.com/jstemmer/go-junit-report) to convert unit-test output to junit xml file
2. use [gocov](github.com/axw/gocov/gocov) and [gocov-xml](github.com/AlekSi/gocov-xml) to convert coverage report to junit xml file

What changes did we see after the modification?
1. A better ci display page for failed unit-test cases
![Xnip2021-10-25_14-19-47](https://user-images.githubusercontent.com/16618216/138644181-511a8a12-03e7-4618-8547-5e12b8c57811.jpg)
2. A better ci display page for unit-test coverage detail
![Xnip2021-10-25_14-30-14](https://user-images.githubusercontent.com/16618216/138645422-111d77d4-0020-4d76-a141-f83e77a9b59b.jpg)
![Xnip2021-10-25_14-30-35](https://user-images.githubusercontent.com/16618216/138645447-71046e46-dc91-46c8-a936-54df1aac3271.jpg)

**Comment by tisonkun** [comment]
I suggest you just inline the content of that doc in the issue. I don't think it requires a design but we'd better review the items you proposed. Also we can later split subtasks from this issue wrt the items.

**Comment by purelind** [comment]
closed by https://github.com/pingcap/tidb/pull/29848
