### ISSUE TITLE
Query with greatest/least function returns inconsistent result with mysql

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#29019]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://asktug.com/t/topic/183612

```
create table test.test_GREATEST(
    id bigint(20),
    datetime_1 datetime,
    datetime_2 datetime,
    datetime3_1 datetime(3),
    datetime3_2 datetime(3)
);

insert into test.test_GREATEST values(1,'2021-10-20 10:10:10.000','2021-10-20 10:10:10.000','2021-10-20 10:10:10.000','2021-10-20 10:10:10.000');

select
    *
from(
    select
        id,
        GREATEST(tg.datetime_1,tg.datetime_2) datetimes
    from test.test_GREATEST tg
) t
where t.datetimes = '2021-10-20 10:10:10.000';

```

### 2. What did you expect to see? (Required)
+------+---------------------+
| id   | datetimes           |
+------+---------------------+
|    1 | 2021-10-20 10:10:10 |
+------+---------------------+
1 row in set (0.00 sec)

### 3. What did you see instead (Required)
Empty set (0.00 sec)

### 4. What is your TiDB version? (Required)
master

**Comment by XuHuaiyu** [comment]
related to https://github.com/pingcap/tidb/issues/30261
