### ISSUE TITLE
BR: checksum takes hours, when restoring with stats

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#29033]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

restore a 60GB backup with 2820 tables,  --ignore-stats=false

### 2. What did you expect to see? (Required)
checksum completes in reasonable time, such as minutes

### 3. What did you see instead (Required)
checksum step of full restore takes hours

### 4. What is your TiDB version? (Required)

```
Release Version: v5.3.0-alpha-1142-g9f8c053
Edition: Community
Git Commit Hash: 9f8c053d06ebe3f6f3278576001bd4b9ebf6d1b1
Git Branch: HEAD
UTC Build Time: 2021-10-19 11:51:43
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by YuJuncen** [comment]
should already be fixed by #29180
