### ISSUE TITLE
ConnectionInfo for existing sessions  is not initialized when enable audit plugins.

### ISSUE THREAD

**Issue by dengqee** [pingcap/tidb#29038]
## Bug Report

https://github.com/pingcap/tidb/blob/42b0bec86dd6e1699dc9f111845908f0109f8b4d/sessionctx/variable/session.go#L761-L762
When the audit plugin is enabled, `SessionVars.ConnetcionInfo` is Initialized only when a new session is created. This will result in  the `SessionVars.ConnetcionInfo` is `nil` for other existing sessions.

Is it possible to initialize `SessionVars.ConnetcionInfo`  whether audit plugins are enabled or not?

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster with audit plugin
2. create a session to tidb server
3. create another session and execute `admin plugins enable audit;` to enable audit plugin 
4. the first session execute some sql command

### 2. What did you expect to see? (Required)

The audit log will output complete information with session connection information.

### 3. What did you see instead (Required)

The audit log lost session connection information.

### 4. What is your TiDB version? (Required)

v4.0.11

**Comment by xhebox** [comment]
It is closed by #36152.
