### ISSUE TITLE
migrate test-infra to testify for `ddl/schema_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#29111]

**Comment by GatorMao** [comment]
I could try to help this one out.

**Comment by tisonkun** [comment]
/assign @GatorMao 

Go ahead!

**Comment by GatorMao** [comment]
Much thanks @tisonkun. BTW, I'm new to this project and would you mind suggest one or two submitted PRs that I could use as reference for this change ? Thanks again.

**Comment by tisonkun** [comment]
@GatorMao you can just navigate to the tracking issue https://github.com/pingcap/tidb/issues/27180 and look up those closed with a pull request :)

**Comment by GatorMao** [comment]
Thanks @tisonkun. I'm currently working on the change and I realize the I also need to change other several files to make this one work. If you don't mind, could you assign the tickets regarding following files to me ? I need to submit one PR to include them all. The file list in ddl package:

- column_change_test.go
- column_test.go
- ddl_test.go
- ddl_worker_test.go
- util_test.go

Please let me know if you have any questions. I also have wechat if you want to get in contact. Thanks.

**Comment by GatorMao** [comment]
@tisonkun , looks like the change https://github.com/pingcap/tidb/pull/29288/files already contain fix for this ticket and all related files. Not sure why I didn't get this change from master branch.

**Comment by tisonkun** [comment]
#29288 doesn't get merged.

**Comment by tisonkun** [comment]
> could you assign the tickets regarding following files to me

You can find related issues to all these files in the tracking issue #27180  and assign yourself to them by commenting `/assign` separately.

**Comment by GatorMao** [comment]
@tisonkun , thanks. You are right. That change wasn't merged. I will assign these files to myself.

**Comment by GatorMao** [comment]
@tisonkun , I also noticed that file `ddl/util_test.go` does not have ticket created. We need to address that file as well.
