### ISSUE TITLE
migrate test-infra to testify for `ddl/stat_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#29114]

**Comment by JayL-zxl** [comment]
@tisonkun  i notice `stat_test.go` use `testGetTable` and `testCreateSchema` etc. functions. These functions have a very strong coupling relationship with other tests in the ddl package

**Comment by JayL-zxl** [comment]
@tisonkun  The migration of a single test file is not very easy to do. Why don't I replace all of them with testing and remove the previous tests using Check

**Comment by tisonkun** [comment]
@JayL-zxl you can always take multiple issues at the same time.

**Comment by JayL-zxl** [comment]
@tisonkun  i see ..

**Comment by tisonkun** [comment]
@JayL-zxl I'm ok if you'd like to just rewrite the tests. But maybe you should reach a consensus with ones of @tiancaiamao @zimulala @djshow832 .

Just create a new issue and close these migration tests if that one accepted and resolved.
