### ISSUE TITLE
migrate test-infra to testify for `ddl/table_test.go`

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#29116]

**Comment by clovis1122** [comment]
I'll take a look at this one!

**Comment by tisonkun** [comment]
/assign @clovis1122 

Thank you! Go ahead.

**Comment by clovis1122** [comment]
I replaced all the usages in table_test.go but it cascaded into other files. I'm fixing those files too.

**Comment by TejaSangaru** [comment]
can you please bit more ..

**Comment by tisonkun** [comment]
Closed as done in master.
