### ISSUE TITLE
br: Should print more valid message for checksum-duration

### ISSUE THREAD

**Issue by joccau** [pingcap/tidb#29158]
## Enhancement

As follow log from `br restore`, maybe it is no sense for "restore-checksum=1h57m24.639772777s" but [total-take=11m43.853700371s]. 
Should we print more valid message for checksum duration?

> [2021/10/21 17:08:09.280 +08:00] [INFO] [collector.go:66] ["Full restore success summary"] [total-ranges=1406] [ranges-succeed=1406] [ranges-failed=0] [split-region=18.662650702s] **[restore-checksum=1h57m24.639772777s]** [restore-ranges=1362] **[total-take=11m43.853700371s]** [restore-data-size(after-compressed)=43.71GB] [Size=43714987368] [BackupTS=428554737544069123] [total-kv=760000000] [total-kv-size=96.52GB] [average-speed=137.1MB/s]

**Comment by YuJuncen** [comment]
IMO just remove those would be fine...

**Comment by fengou1** [comment]
let me fix it.
