### ISSUE TITLE
The pd version numbers displayed by dashboard and CLUSTER_INFO are inconsistent

### ISSUE THREAD

**Issue by jebter** [pingcap/tidb#29204]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
![image](https://user-images.githubusercontent.com/4425235/139197964-ba8e5109-c6b4-4309-8ad5-14b8f05d65dd.png)

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/4425235/139198044-d89c3ce1-8dbd-458d-97b6-e2399d8c8e46.png)

### 4. What is your TiDB version? (Required)

 Release Version: v5.1.1-20211021

**Comment by nolouch** [comment]
fixed by https://github.com/pingcap/tidb/issues/28679.
