### ISSUE TITLE
Sequence cannot work when existing a temporary table with the same name

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#29277]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create sequence s1;
create temporary table s1 (id int);
select nextval(s1);
```

### 2. What did you expect to see? (Required)

```
mysql> select nextval(s1);
+-------------+
| nextval(s1) |
+-------------+
|           1 |
+-------------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)

```
mysql> select nextval(s1);
ERROR 1347 (HY000): 'test.s1' is not SEQUENCE
```

### 4. What is your TiDB version? (Required)

master

**Comment by JayL-zxl** [comment]
so If there is already a sequence called s1, we should check before creating a temporary table to prohibit this operation?
If it means that I can finish it

**Comment by lcwangchao** [comment]
> so If there is already a sequence called s1, we should check before creating a temporary table to prohibit this operation? If it means that I can finish it

It is not possible to avoiding a sequence and a temporary table with the same time because sequence may be created in another session.

**Comment by lcwangchao** [comment]
I'm thinking about whether it is bug or not...

**Comment by aytrack** [comment]
Maybe for the sequence functions, It's should use the sequence as the default parameter.

**Comment by lcwangchao** [comment]
> Maybe for the sequence functions, It's should use the sequence as the default parameter.

But I think this behavior requires some special code to process temporary tables and can introduce some extra effort to maintain this kind functions. @morgo @djshow832 What do you think about it?

**Comment by morgo** [comment]
> But I think this behavior requires some special code to process temporary tables and can introduce some extra effort to maintain this kind functions. @morgo @djshow832 What do you think about it?

There is not a specific example in MySQL we can point to, since it does not implement sequences :-)

But logically temporary tables have their own namespace, and you only have to worry about existing temporary tables that could conflict. I am not sure that a temporary sequence makes sense, so `select nextval(s1);` could also always only use base-tables?

**Comment by lcwangchao** [comment]
I tried the same operations in postgresql:

```
postgres=# create sequence s;
CREATE SEQUENCE
postgres=# create temporary table s(id int);
CREATE TABLE
postgres=# select nextval('s');
ERROR:  "s" is not a sequence
postgres=#
```

It also reports error when a temporary table with a same name exists. So I decided to close this issue temporarily.
