### ISSUE TITLE
Prepared statements can't see temporary tables when the SQL involves multiple tables

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#29282]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> create temporary table tmp(id int);
Query OK, 0 rows affected (0.00 sec)

mysql> prepare stmt from 'insert into t select * from tmp';
Query OK, 0 rows affected (0.01 sec)

mysql> execute stmt;
ERROR 1146 (42S02): Table 'tmpdb.tmp' doesn't exist
```

### 2. What did you expect to see? (Required)

```sql
mysql> create temporary table tmp(id int);
Query OK, 0 rows affected (0.03 sec)

mysql> prepare stmt from 'insert into t select * from tmp';
Query OK, 0 rows affected (0.00 sec)
Statement prepared

mysql> execute stmt;
Query OK, 0 rows affected (0.01 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

### 3. What did you see instead (Required)

```sql
mysql> execute stmt;
ERROR 1146 (42S02): Table 'tmpdb.tmp' doesn't exist
```

### 4. What is your TiDB version? (Required)

master

**Comment by JayL-zxl** [comment]
its litte difficult for me, but i am trying to solve it.

**Comment by lcwangchao** [comment]
I think it is caused by this pr: #26759 . Here(https://github.com/pingcap/tidb/pull/26759/files#diff-0a0c95887230cee4dde6537c6be06ea308529b392c4c3303c242509f53bb8f1aR89-R93) is returning an infoschema without local temporary tables.

**Comment by JayL-zxl** [comment]
> I think it is caused by this pr: #26759 . Here(https://github.com/pingcap/tidb/pull/26759/files#diff-0a0c95887230cee4dde6537c6be06ea308529b392c4c3303c242509f53bb8f1aR89-R93) is returning an infoschema without local temporary tables.

yes. so my modify here. but i am not confirm

**Comment by tiancaiamao** [comment]
@qw4990 Will prepared plan cache work in this case? and what happens when the temporary table is dropped?

**Comment by tiancaiamao** [comment]
> @qw4990 Will prepared plan cache work in this case? and what happens when the temporary table is dropped?

OK, I tested, plan cached is not used in this case; drop table and execute stmt reports error table not exist...
