### ISSUE TITLE
Upgrade: after upgrade pd and tidb, pd version from information_schema.cluster_info is not updated.

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb#29304]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Upgrade from 5.2.2 to master, first upgrade pd, check pd version in information schema, found that it is not updated. Then upgrade tidb, found tidb version is updated, while pd version is not update also.

### 2. What did you expect to see? (Required)
PD version should update in information_schema.cluster_info after pd upgrade succeeded.

### 3. What did you see instead (Required)
PD version only update in information_schema.cluster_info after tikv upgrade succeeded.

% k8 exec tc-pd-0 -it -- sh
/ # /pd-server -V
Release Version: v5.2.0-nightly
Edition: Community
Git Commit Hash: e65f0c55b6ae3725a0906baccf27f0fa9a355e24
Git Branch: heads/refs/tags/v5.2.0-nightly
UTC Build Time:  2021-11-01 05:38:32

mysql> select version,instance from information_schema.cluster_info;
+---------------+-----------------------------------------------------------+
| version       | instance                                                  |
+---------------+-----------------------------------------------------------+
| 5.2.0-nightly | tc-tidb-0.tc-tidb-peer.testbed-hongm-oltp-k7h5s.svc:4000  |
| 5.2.2         | tc-pd-0.tc-pd-peer.testbed-hongm-oltp-k7h5s.svc:2379      |
| 5.2.2         | tc-tikv-1.tc-tikv-peer.testbed-hongm-oltp-k7h5s.svc:20160 |
| 5.2.2         | tc-tikv-2.tc-tikv-peer.testbed-hongm-oltp-k7h5s.svc:20160 |
| 5.2.2         | tc-tikv-0.tc-tikv-peer.testbed-hongm-oltp-k7h5s.svc:20160 |
+---------------+-----------------------------------------------------------+

After upgrade tikv to master, pd version update to tikv version instead of pd-server version.
mysql> select version,instance from information_schema.cluster_info;
+---------------+-----------------------------------------------------------+
| version       | instance                                                  |
+---------------+-----------------------------------------------------------+
| 5.2.0-nightly | tc-tidb-0.tc-tidb-peer.testbed-hongm-oltp-k7h5s.svc:4000  |
| 5.3.0-alpha   | tc-pd-0.tc-pd-peer.testbed-hongm-oltp-k7h5s.svc:2379      |
| 5.3.0-alpha   | tc-tikv-2.tc-tikv-peer.testbed-hongm-oltp-k7h5s.svc:20160 |
| 5.3.0-alpha   | tc-tikv-0.tc-tikv-peer.testbed-hongm-oltp-k7h5s.svc:20160 |
| 5.3.0-alpha   | tc-tikv-1.tc-tikv-peer.testbed-hongm-oltp-k7h5s.svc:20160 |
+---------------+-----------------------------------------------------------+

5 rows in set (0.08 sec)
### 4. What is your TiDB version? (Required)
/ # /tidb-server -V
Release Version: v5.2.0-nightly
Edition: Community
Git Commit Hash: 80e14b4bffc8a0b9de6859daac85276adc8d7054
Git Branch: heads/refs/tags/v5.2.0-nightly
UTC Build Time: 2021-11-01 05:42:09
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: fals

**Comment by HunDunDM** [comment]
duplicate #28679, fixed by #29265

**Comment by mayjiang0203** [comment]
Will verify it after the pr merge.
