### ISSUE TITLE
test: tests call  `collate.SetNewCollationEnabledForTest(true)` should serial

### ISSUE THREAD

**Issue by feitian124** [pingcap/tidb#29319]
## Bug Report

we cannot make it parallel because of there is `collate.SetNewCollationEnabledForTest(true)` at L134

_Originally posted by @xiongjiwei in https://github.com/pingcap/tidb/pull/29125#discussion_r740047956_

### 1. Minimal reproduce step (Required)

see above

**Comment by feitian124** [comment]
i checked the git history of file `util/collate/collate.go` to find why tests call method `collate.SetNewCollationEnabledForTest(true) need run in serial.

the original implement of `SetNewCollationEnabledForTest` use Map:

```go
// SetNewCollationEnabledForTest sets if the new collation are enabled in test.
// Note: Be careful to use this function, if this functions is used in tests, make sure the tests are serial.
func SetNewCollationEnabledForTest(flag bool) {
	newCollationEnabled = flag
	if newCollationEnabled {
		collatorMap["utf8mb4_bin"] = &binPaddingCollator{}
		collatorMap["utf8_bin"] = &binPaddingCollator{}
		collatorMap["utf8mb4_general_ci"] = &generalCICollator{}
		collatorMap["utf8_general_ci"] = &generalCICollator{}

		collatorIDMap[46] = &binPaddingCollator{}
		collatorIDMap[83] = &binPaddingCollator{}
		collatorIDMap[45] = &generalCICollator{}
		collatorIDMap[33] = &generalCICollator{}
	} else {
		collatorMap["utf8mb4_bin"] = &binCollator{}
		collatorMap["utf8_bin"] = &binCollator{}
		collatorMap["utf8mb4_general_ci"] = &binCollator{}
		collatorMap["utf8_general_ci"] = &binCollator{}

		collatorIDMap[46] = &binCollator{}
		collatorIDMap[83] = &binCollator{}
		collatorIDMap[45] = &binCollator{}
		collatorIDMap[33] = &binCollator{}
	}
}
```
but now use atom:

```go
// SetNewCollationEnabledForTest sets if the new collation are enabled in test.
// Note: Be careful to use this function, if this functions is used in tests, make sure the tests are serial.
func SetNewCollationEnabledForTest(flag bool) {
	if flag {
		atomic.StoreInt32(&newCollationEnabled, 1)
		return
	}
	atomic.StoreInt32(&newCollationEnabled, 0)
}
```

if the comment `Note: Be careful to use this function, if this functions is used in tests, make sure the tests are serial.` is out of date and `SetNewCollationEnabledForTest` is safe for Concurrency?

@xiongjiwei @wjhuang2016

**Comment by xiongjiwei** [comment]
it relates to tests, it is a global variable, if the parallel test changes the value, some tests will get unexpected failure. (one test need this value to be true and another test changes it to false, because they are parallel)

**Comment by feitian124** [comment]
sorry my mistake, understand.
