### ISSUE TITLE
execute privilege related SQL failed in TiDB server when security.skip-grant-table=true

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#29317]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

#### background

I want to execute some `create user` and `grant privilege` SQL in the TiDB server which config `security.skip-grant-table=true`, but I meet some errors.

#### reproduce

1. start a TiDB server with `security.skip-grant-table=true`.
2. execute the following SQL in the TiDB server which `security.skip-grant-table=true`:

```sql
CREATE USER 'test1'@'%';
GRANT BACKUP_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTORE_ADMIN ON *.* TO 'test1'@'%';
GRANT RELOAD ON *.* TO 'test1'@'%';
GRANT SHUTDOWN ON *.* TO 'test1'@'%';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_VARIABLES_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_STATUS_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_CONNECTION_ADMIN, CONNECTION_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_USER_ADMIN ON *.* TO 'test1'@'%';
GRANT RESTRICTED_TABLES_ADMIN ON *.* TO 'test1'@'%';
GRANT PROCESS ON *.* TO 'test1'@'%';
GRANT SHUTDOWN ON *.* TO 'test1'@'%';
GRANT SELECT, INSERT, UPDATE, DELETE ON mysql.* TO 'test1'@'%';
GRANT SELECT ON information_schema.* TO 'test1'@'%';
GRANT SELECT ON performance_schema.* TO 'test1'@'%';
GRANT ALL PRIVILEGES ON *.* TO root;
revoke SHUTDOWN on *.* from root;
revoke CONFIG on *.* from root;


CREATE USER 'test2'@'%' IDENTIFIED BY '12345';
GRANT PROCESS, CONFIG ON *.* TO 'test2'@'%';
GRANT SHOW DATABASES ON *.* TO 'test2'@'%';
GRANT DASHBOARD_CLIENT ON *.* TO 'test2'@'%';
GRANT SYSTEM_VARIABLES_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_VARIABLES_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_STATUS_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_TABLES_ADMIN ON *.* TO 'test2'@'%';
GRANT RESTRICTED_USER_ADMIN ON *.* TO 'test2'@'%';
```

you will meet some errors, such as:

```sql
(none)> CREATE USER 'test'@'%';
(1396, "Operation CREATE USER failed for 'test'@'%'")
(none)> SHOW GRANTS FOR CURRENT_USER();
(1141, "There is no such grant defined for user 'root' on host '%'")
(none)> GRANT DASHBOARD_CLIENT ON *.* TO 'root'@'%';  -- TiDB server panic!!!
(1105, 'runtime error: invalid memory address or nil pointer dereference')
```

### 2. What did you expect to see? (Required)

Execute success.

### 3. What did you see instead (Required)

Execute failed.

### 4. What is your TiDB version? (Required)

```sql
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.3.0-alpha-1292-g4b6291f45
Edition: Community
Git Commit Hash: 4b6291f45cb2f34833ffa4d066b628bc197c25a3
Git Branch: master
UTC Build Time: 2021-11-01 09:28:59
GoVersion: go1.16.6
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by SunRunAway** [comment]
Should it be a critical bug? It is a Invalid features.
 @aytrack

**Comment by unconsolable** [comment]
I think it may due to https://github.com/pingcap/tidb/pull/9654, which will not enter `(*Domain).LoadPrivilegeLoop` in `skip-grant-table=true`, thus in `(*Handle).Update` will encounter runtime error. 
After remove the if statement everything is ok except `SHOW GRANTS FOR CURRENT_USER();`

**Comment by unconsolable** [comment]
I think these may be expected behaviors. https://github.com/pingcap/tidb/blob/a96deabe7e46385722cf96f7fc254de86fd5bd1a/privilege/privileges/privileges.go#L38-L39
If `security.skip-grant-table=true`, `ErrNonexistingGrant` is expected. However, shall the `runtime error: invalid memory address or nil pointer dereference` be replaced by a error?

**Comment by crazycs520** [comment]
I still get the following error in `tidb-server` which use `skip-grant-table=true`, but I'm not sure how to fix it, but I think we can handle this problem in another PR.

```sql
▶ mysql -u user_not_exist -h 127.0.0.1 -P 4000
mysql> show grants for current_user();
ERROR 1141 (42000): There is no such grant defined for user 'root' on host '%'
```

**Comment by unconsolable** [comment]
Sha we just keep the error msg consistent with MySQL? cc. @tiancaiamao

**Comment by unconsolable** [comment]
> Test results on MySQL 8.0.27
> ```
> mysql> CREATE USER 'test1'@'%';
> ERROR 1290 (HY000): The MySQL server is running with the --skip-grant-tables option so it cannot execute this statement
> mysql> SHOW GRANTS FOR CURRENT_USER();
> ERROR 1290 (HY000): The MySQL server is running with the --skip-grant-tables option so it cannot execute this statement
> mysql> GRANT ALL ON *.* TO 'root'@'%';
> ERROR 1290 (HY000): The MySQL server is running with the --skip-grant-tables option so it cannot execute this statement
> mysql> REVOKE ALL ON *.* FROM 'root'@'%';
> ERROR 1290 (HY000): The MySQL server is running with the --skip-grant-tables option so it cannot execute this statement
> ```

Shall we just keep the error message consistent with MySQL ? cc. @tiancaiamao

**Comment by tiancaiamao** [comment]
> I still get the following error in `tidb-server` which use `skip-grant-table=true`, but I'm not sure how to fix it, but I think we can handle this problem in another PR.
> 
> ```sql
> ▶ mysql -u user_not_exist -h 127.0.0.1 -P 4000
> mysql> show grants for current_user();
> ERROR 1141 (42000): There is no such grant defined for user 'root' on host '%'
> ```

It's introduced here https://github.com/pingcap/tidb/pull/10681/ and the current behaviour seems a feature rather than bug. @crazycs520 

When `skip-grant-table` is set, tidb doesn't load the privilege data, so the related handle is nil, and call `ShowGrants` method on that nil instance will panic...

**Comment by bb7133** [comment]
> > I still get the following error in `tidb-server` which use `skip-grant-table=true`, but I'm not sure how to fix it, but I think we can handle this problem in another PR.
> > ```sql
> > ▶ mysql -u user_not_exist -h 127.0.0.1 -P 4000
> > mysql> show grants for current_user();
> > ERROR 1141 (42000): There is no such grant defined for user 'root' on host '%'
> > ```
> 
> It's introduced here #10681 and the current behaviour seems a feature rather than bug. @crazycs520
> 
> When `skip-grant-table` is set, tidb doesn't load the privilege data, so the related handle is nil, and call `ShowGrants` method on that nil instance will panic...

@crazycs520 Exactly, I don't think this is a bug because `skip-grant-table` is not supposed to be working in this way. I think if we want to make `show grants` work, it should be a feature request/enhancement.
