### ISSUE TITLE
The update operation is invalid and TiDB server falls into an abnormal state

### ISSUE THREAD

**Issue by lpypl** [pingcap/tidb#29324]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

#### OP-List

```sql
/* 1. */ create table table_7_2(a int primary key, b int, c double);
/* 2. */ insert into table_7_2 values(676, 5012153, 2240641.4);
/* 3. */ select * from table_7_2; 
/* 4. */ update table_7_2 set b=5012153 and c=2240641.4 where a=676;
/* 5. */ select * from table_7_2; 
```

### 2. What did you expect to see? (Required)

The output of **OP-3** is `"676","5012153","2240641.4"`, that is normal.
However, the output of **OP-5** is `"676","1","2240641.4"`.

### 3. What did you see instead (Required)

The output of **OP-5** should be `"676","5012153","2240641.4"`.
And it seems that the Tidb will be abnormal after **OP-4**, I can't update the value of **b** successfully.

### 4. What is your TiDB version? (Required)
5.7.25-TiDB-v3.0.4
5.7.25-TiDB-v3.0.5
5.7.25-TiDB-v3.0.6

**Comment by kennytm** [comment]
I get `676`,`1`,`2240641.4` using "5.7.25-TiDB-v5.2.1", the same result as MySQL "8.0.26", as expected.

If you want to update both `b` and `c` columns in OP-4 the correct syntax is

```sql
update table_7_2 set b=5012153, c=2240641.4 where a=676;
--                            ^
```

otherwise it will be parsed as 

```sql
update table_7_2 set b=(5012153 and c=2240641.4) where a=676;
--                     ^                       ^
```

and that expression becomes `TRUE and TRUE` = `TRUE` = `1`.

**Comment by lpypl** [comment]
Thanks, it's a stupid error.😂
