### ISSUE TITLE
The parser cannot be compiled by executing the `make parser` command in the project root directory.

### ISSUE THREAD

**Issue by ou-bing** [pingcap/tidb#29322]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

executing the `make parser` command in the project root directory.

### 2. What did you expect to see? (Required)

I hope to compile the parser successfully.

### 3. What did you see instead (Required)

The terminal prompt: `remove this command later, when our CI script doesn't call it`

### 4. What is your TiDB version? (Required)

commit 476b8957c282ee6688c988f9e7b096cf63e5fd06

**Comment by ou-bing** [comment]
Now you can compile in the parser directory, but the old document asks us to compile in the project root directory. Should we restore this command?

**Comment by zhangyangyu** [comment]
@ou-bing where is the old document? Would you mind give me a link?

**Comment by dveeden** [comment]
Not sure what the "old document" is either. However https://github.com/pingcap/tidb/blob/master/parser/README.md and the links it contains might need some updates. Some of the links also need to be updated to point to the new location ( https://github.com/pingcap/tidb/tree/master/parser/docs )

**Comment by ou-bing** [comment]
@dveeden @zhangyangyu Documents refer to articles in official blogs 🤣.

**Comment by dveeden** [comment]
Do you mean this one? https://pingcap.com/zh/blog/30mins-become-contributor-of-tidb-20190808

https://pingcap.github.io/tidb-dev-guide/understand-tidb/parser.html at least needs updating

**Comment by zhangyangyu** [comment]
IMHO blogs represents the facts when are written and there is no need to update them. I have opened a PR to update the dev guide. And for `TiDB/parser/docs` and `TiDB/parser/README`, according to the [design](https://github.com/pingcap/tidb/blob/master/docs/design/2021-09-13-parser-as-submodule-of-tidb.md), seems parser is still in migration stage and we could update them after everything is settled. @xhebox

**Comment by xhebox** [comment]
> 
> 
> IMHO blogs represents the facts when are written and there is no need to update them. I have opened a PR to update the dev guide. And for `TiDB/parser/docs` and `TiDB/parser/README`, according to the [design](https://github.com/pingcap/tidb/blob/master/docs/design/2021-09-13-parser-as-submodule-of-tidb.md), seems parser is still in migration stage and we could update them after everything is settled. @xhebox

Nope, it is mostly finished for the first phase. You should be able to compile parser in `parser/` subdirectory. Sorry that I did not enough time working the migration of documents. I'll work that in this week.

**Comment by zimulala** [comment]
@xhebox PTAL
