### ISSUE TITLE
Placement Policy support for dumpling

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#29371]
## Feature Request

This is part of https://github.com/pingcap/tidb/issues/18030

**Is your feature request related to a problem? Please describe:**

Currently dumpling supports dumping tables + data, but it does not yet support correctly dumping tables with a `PLACEMENT POLICY` defined.

Placement Policies can be thought of as similar to "Roles". They are globally scoped and save a set of placement options under a common name. See https://github.com/pingcap/docs/pull/6618 for docs.

**Describe the feature you'd like:**

Dumpling should use the following procedure to dump placement policies:

1. Build a list of distinct placement policy names (`select distinct policy_name from information_schema.placement_rules;`)
2. Run `SHOW CREATE PLACEMENT POLICY foo` to get the recreatable version of the policy. This should be written to the top of the dump file.
3. Append `SET PLACEMENT_CHECKS=0` to the start of the dump file. This feature was developed with dumpling in mind, since it should be possible to disable failures if a dump is reimported into a newer server which has stricter interpretations of how placement policies should be validated/specified. It also helps if the labels differ on the physical server where data is being restored (since this should not prevent restore - that could be disasterous).

**Describe alternatives you've considered:**

None

**Teachability, Documentation, Adoption, Migration Strategy:**

It should automatically work assuming the server is a TiDB server.

**Comment by sylzd** [comment]
@morgo  @kennytm  Can I try this?  any idea or suggestion for me? 🤣

**Comment by morgo** [comment]
Please try! @lichunzhu is a good person to ask for suggestions.

**Comment by sylzd** [comment]
@morgo It seems done already.

**Comment by morgo** [comment]
> @morgo It seems done already, any other work left?

I have added several new issues to https://github.com/pingcap/tidb/issues/18030 just today (see the "Other" section).
