### ISSUE TITLE
SET timestamp=default is setting value to null

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#29415]
### 1. Minimal reproduce step (Required)
```sql
SET timestamp=default;
select @@timestamp;
```
### 2. What did you expect to see? (Required)
```sql
mysql> set timestamp = default;
Query OK, 0 rows affected (0.00 sec)

mysql> select @@timestamp;
+-------------------+
| @@timestamp       |
+-------------------+
| 1635956082.324848 |
+-------------------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> set timestamp = default;
Query OK, 0 rows affected (0.00 sec)

mysql> select @@timestamp;
+-------------+
| @@timestamp |
+-------------+
|             |
+-------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```sql
+-------------------------+--------------------------------------------------------------------------+
| Variable_name           | Value                                                                    |
+-------------------------+--------------------------------------------------------------------------+
| innodb_version          | 5.6.25                                                                   |
| protocol_version        | 10                                                                       |
| tidb_analyze_version    | 2                                                                        |
| tidb_row_format_version | 2                                                                        |
| tls_version             | TLSv1,TLSv1.1,TLSv1.2                                                    |
| version                 | 5.7.25-TiDB-v5.2.1                                                       |
| version_comment         | TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible |
| version_compile_machine | x86_64                                                                   |
| version_compile_os      | osx10.8                                                                  |
+-------------------------+--------------------------------------------------------------------------+
```

**Comment by morgo** [comment]
This is a good first issue for contributors. It requires a `GetSession` function to be added for the `Timestamp` system variable to read the internal timestamp which is used by temporal functions. See https://github.com/pingcap/tidb/pull/28072 for a previous example that is similar.

**Comment by myccccccc** [comment]
> This is a good first issue for contributors. It requires a `GetSession` function to be added for the `Timestamp` system variable to read the internal timestamp which is used by temporal functions. See #28072 for a previous example that is similar.

@morgo I got your point, could you please tell me where can I find such temporal function that provides internal TS

**Comment by morgo** [comment]
Temporal functions like `NOW()` call this function: https://github.com/pingcap/tidb/blob/9bbc7ad74a540d61a1d47f7212bd0f9cd0244b76/expression/helper.go#L135-L167

So the GetSession func would have to have similar logic - if there is a value for s.systems[Timestamp] use it, otherwise use s.StmtCtx.GetOrStoreStmtCache..
