### ISSUE TITLE
`make parser_yacc` fails due to junk bytes at the end of generated files

### ISSUE THREAD

**Issue by zhangyangyu** [pingcap/tidb#29410]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`make parser_yacc`

### 2. What did you expect to see? (Required)

test all passes

### 3. What did you see instead (Required)

`make parser_yacc` fails on the `diff` stage. Output too large to put here.

### 4. What is your TiDB version? (Required)

master branch, commit 731902de583687d7a7ad9a69b0038d16fd445741
go version 1.17.2
macOS monterey 12.0.1

The cause of the `diff` failure is due to there are two more invalid utf8 bytes `\xef\xbf` at the end of the generated go files. So https://github.com/pingcap/tidb/blob/731902de583687d7a7ad9a69b0038d16fd445741/parser/goyacc/main.go#L270 fails to format the generated file. The parser structure gets a `Tail`:
```
· Tail: &parser.Tail{
· · Value: "\n\xef\xbf",
· · Token: parser.y:13724:1: MARK "%%", Comments: [],
· }  
```
Don't know where the two bytes comes. The y files don't have the bytes at the end.

**Comment by zhangyangyu** [comment]
This issue could also be reproduced on CentOS, go version 1.16/1.17.

**Comment by kennytm** [comment]
![1-fs8](https://user-images.githubusercontent.com/103023/140298525-2315f1b8-8125-43c3-9aa4-1298386d46aa.png)

https://github.com/pingcap/tidb/blob/dcbfda914ad0b2647edc39788e0a6e8b5d90717d/parser/parser.y#L5083

The comment used a fullwidth `｜` which goyacc can't handle 😅. Changing this to the ASCII `|` should be enough.

**Comment by zhangyangyu** [comment]
No. I know there is a fullwidth `|` which is the only non-ASCII character in y files(`pcregrep -r --color='auto' -n '[^\x00-\x7F]'`). But it's not the cause. The two junk bytes are at the end of the file. `Tail` represents all contents after the second mark `%%`.

**Comment by zhangyangyu** [comment]
Sorry I've made a mistake that this problem will only occur with go 1.17, not 1.16(I forgot to delete the binary).

And the cause of this problem is that `bytes.Buffer.WriteRune` has changed its behavior between go 1.17 and previous versions, see https://go-review.googlesource.com/c/go/+/280492/ for the treatment of negative runes. 

In [`cnzic/golex/lex/api.go:next()`](https://gitlab.com/cznic/golex/-/blob/master/lex/api.go#L237), for the end of file, a `Token{Rune: -1, pos: 318723}` is generated and then in https://gitlab.com/cznic/parser/-/blob/master/yacc/lexer.go#L141, `bytes.Buffer.writeRune(-1)` is executed. In go 1.16, byte `255` is written and then abondoned in https://gitlab.com/cznic/parser/-/blob/master/yacc/lexer.go#L142. But in go 1.17, bytes `\xef\xbf\bd` (utf8 encoded unicode replacement character) are written. After abondon one byte, `\xef\bf` will be written to the end of file finally. That's what we see.

So `cnzic/golex` is not compatible with go 1.17.
