### ISSUE TITLE
v5.3.0, security.auto-tls default value change to  true, should be false

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#29432]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

get tidb  config

### 2. What did you expect to see? (Required)
security.auto-tls= false
### 3. What did you see instead (Required)
security.auto-tls = ture
### 4. What is your TiDB version? (Required)
v5.3.0

**Comment by dveeden** [comment]
Related: #27486

**Comment by bb7133** [comment]
Closed by #29472
