### ISSUE TITLE
The error message become "register error after initialized is prohibited" and panicked

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#29465]
## Bug Report

Please see https://github.com/pingcap/tidb/issues/29412 for details.

The following reproduce steps will not be able to reproduce the bug after https://github.com/pingcap/tidb/pull/29457 merged because the root cause of the error is fixed in the PR.

### 1. Minimal reproduce step (Required)

```
create table t1(a int);
create table t2(a double);
insert into t1 value(20);
select sum(distinct a) as x from t1 having x > some ( select a from t2 where x in (a));
```

### 2. What did you expect to see? (Required)

Report a meaningful error.

### 3. What did you see instead (Required)

ERROR 1105 (HY000): register error after initialized is prohibited

### 4. What is your TiDB version? (Required)

master

**Comment by time-and-fate** [comment]
As kennytm said in #29412:
> All uses of `dbterror.ClassOptimizer.NewStd(mysql.ErrInternal)` should be replaced by a global constant. There are 6 places.

**Comment by tiancaiamao** [comment]
Good!  Prevent the misuse of the terror API works as expected https://github.com/pingcap/tidb/pull/28438
Expose the error early and fix is better than expose it in the customer's production environment.
