### ISSUE TITLE
Insert decimal error : Parse uint64 out of range

### ISSUE THREAD

**Issue by ueizhou** [pingcap/tidb#2946]
1. What did you do?
I have a table such as : create table test (id decimal(20, 0));
And then I insert a row : insert into test values(12345678901234567890);

2. What did you expect to see?
execute success. 1 row affected

3. What did you see instead?
return a error msg. parse uint64 error, out of range

4. What version of Go are you using (`go version`)?
go 1.8

**Comment by shenli** [comment]
@ueizhou Could you please add more information in this issue?

**Comment by ueizhou** [comment]
it seems a bug in parser/lexer.go. 
The function "startWithNumber(s *Scanner) (tok int, pos Pos, lit string)" scans a value begins with number, but it not process decimal without '.' , so the function return intLit token. and then in function  "func (s *Scanner) Lex(v *yySymType)", toInt() will be invoked and return parse uint64 error.

**Comment by ueizhou** [comment]
But it execute succeed  when I quoted the decimal as below:
 insert into test values('12345678901234567890');

**Comment by shenli** [comment]
@ueizhou Thanks！
@tiancaiamao PTAL

**Comment by ueizhou** [comment]
sorry，the example is wrong. the error occurred
when number not start with 1, such as 22345678901234567890 etc.
