### ISSUE TITLE
QPS drops more than 50% when add index

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#29490]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
oltp_004_test
add index during run tpcc

### 2. What did you expect to see? (Required)
QPS drop less than 50%

### 3. What did you see instead (Required)
https://tcms.pingcap.net/dashboard/executions/plan/390261
![middle_img_v2_cbf80243-f6a9-42cf-a3d4-1a400bc32b2g](https://user-images.githubusercontent.com/84712107/140451576-8c836bb2-13d6-425b-9433-392f6a274027.png)

### 4. What is your TiDB version? (Required)
5.3.0 11.03 newest build

**Comment by zimulala** [comment]
@Lily2025 Please try again.

**Comment by wjhuang2016** [comment]
Close it since it's not a bug. We have discussed it internally.
