### ISSUE TITLE
tidb oom after inject tikv、pd、tidb network-loss

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#29538]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
TiKVFailover002 pass
TiKVFailover004 run 4min

### 2. What did you expect to see? (Required)
all instance are normal and workload run normally

### 3. What did you see instead (Required)
one tidb oom
workload run report some err
![image](https://user-images.githubusercontent.com/84712107/140670499-103d52d9-686b-4d61-8cb2-1bd420c9bda4.png)
2021-11-07T19:12:43.510Z	INFO	tikvpkg/tikv.go:41	[mysql] 2021/11/07 19:12:43 packets.go:36: unexpected EOF

2021-11-07T19:12:43.510Z	INFO	tikvpkg/tikv.go:41	[2021-11-07 19:12:43] execute run failed, err invalid connection

### 4. What is your TiDB version? (Required)
/ # ./tidb-server -V
Release Version: v5.3.0
Edition: Community
Git Commit Hash: e4a5f2ed2545da8c7408494daf492407fcc8a73b
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-05 09:16:24
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by winoros** [comment]
This one should be resolved during the 5.3 releasing.
