### ISSUE TITLE
analyze sample by rate may rise new warning message

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#29545]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster 
2. use go-sql-drive/mysql 1.3.0 connect the tidb, use 'strict=true'
3. execute analyze table

It's  a compatibility  issue, `go-sql-driver/mysql` since `v1.4.0` remove strict mod.but mysql-tester also use v1.3.0, which will  cause ci test failed with this. https://github.com/pingcap/mysql-tester/blob/master/go.mod#L6 
 but it's hard to say no customer not use this.
### 2. What did you expect to see? (Required)
analyze table should be successfully 
### 3. What did you see instead (Required)
```sql
Note 1105: Analyze use auto adjusted sample rate 1.000000 for table test.t1.
```
### 4. What is your TiDB version? (Required)
v5.3.0, master

**Comment by time-and-fate** [comment]
`go-sql-driver/mysql` removed this option in 1.4. Seems they also think this option is not quite reasonable.
https://github.com/go-sql-driver/mysql/wiki/strict-mode

**Comment by xuyifangreeneyes** [comment]
MySQL has a system variable `sql_notes`. If `sql_notes` turns off, the server would not record note-level warnings. But TiDB seems not implement the functionality of `sql_notes`.

**Comment by winoros** [comment]
This is not the first time that TiDB add a new warning/note result. Actually, there're many new warning/note we added for our optimizer hint system. So this case should not be considered more serious than the previous changes.

**Comment by aytrack** [comment]
failed again in ci : https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/7787/pipeline/144/ 
@winoros  PTAL~

**Comment by aytrack** [comment]
another failed with in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7643/pipeline/86
```bash
run test [row] err: sql:ANALYZE TABLE t1;: run "ANALYZE TABLE t1;" at line 131 err Note 1105: Analyze use auto adjusted sample rate 1.000000 for table row.t1.    
```
@winoros @time-and-fate seems there are several cases in mysqltest will be affected with this, could you check the cases  again and solve it.
