### ISSUE TITLE
can't join on date type columns

### ISSUE THREAD

**Issue by roobo** [pingcap/tidb#2955]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
create two table ta,tb
CREATE TABLE `ta` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `my_date` date DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB;
CREATE TABLE `tb` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `my_date` date DEFAULT NULL,
 PRIMARY KEY (`id`)
) ENGINE=InnoDB;

insert into ta values(NULL,'2017-03-29');
insert into tb values(NULL,'2017-03-29');

select ta.* from ta join tb on ta.my_date=tb.my_date ;

2. What did you expect to see?
table ta's data

3. What did you see instead?
ERROR 2013 (HY000): Lost connection to MySQL server during query

2017/03/29 20:13:57 metrics.go:338: [warning] [EXPENSIVE_QUERY] select ta.* from ta join tb on ta.my_date=tb.my_date
2017/03/29 20:13:57 conn.go:342: [error] lastCmd select ta.* from ta join tb on ta.my_date=tb.my_date, should never happen, goroutine 320397 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc4212a8160)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:334 +0xe2
panic(0xd4cb80, 0xc42199e490)
        /usr/local/go/src/runtime/panic.go:458 +0x243
github.com/pingcap/tidb/util/types.(*Datum).ConvertTo(0xc42199ab80, 0xc42197f0c0, 0xc420ee71a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/util/types/datum.go:677 +0x260
github.com/pingcap/tidb/executor.getHashKey(0xc42197f0c0, 0xc4206527f0, 0x1, 0x1, 0xc420e53e30, 0xc4206527f8, 0x1, 0x1, 0xc42199ab80, 0x1, ...)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/join.go:120 +0x1c0
github.com/pingcap/tidb/executor.(*HashJoinExec).prepare(0xc4213a8c00, 0x4428d0, 0xc42199c590)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/join.go:234 +0x3bb
github.com/pingcap/tidb/executor.(*HashJoinExec).Next(0xc4213a8c00, 0x1, 0x0, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/join.go:397 +0x36b
github.com/pingcap/tidb/executor.(*ProjectionExec).Next(0xc4207adc20, 0x42bc33, 0xc4212bfa58, 0x5d1fc9)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/executor.go:397 +0x43a
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc4207adc70, 0x5d1fc9, 0xc4212bfa98, 0xc4212bfaa8)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/adapter.go:62 +0x38
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc42199c5b0, 0x147c480, 0xc42199c5b0, 0xc42199c5b0, 0x10, 0x10)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/driver_tidb.go:293 +0x37
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc4212a8160, 0x147c460, 0xc42199c5b0, 0xc421990000, 0x0, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:720 +0xbb
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc4212a8160, 0xc42197efc1, 0x34, 0x0, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:673 +0xfb
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc4212a8160, 0xc42197efc1, 0x35, 0x34, 0x0, 0x0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:454 +0x42a
github.com/pingcap/tidb/server.(*clientConn).Run(0xc4212a8160)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:358 +0x148
github.com/pingcap/tidb/server.(*Server).onConn(0xc4207a5f00, 0x14864e0, 0xc4205f41c0)
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/server.go:210 +0x13e
created by github.com/pingcap/tidb/server.(*Server).Run
        /home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/server.go:174 +0x96

4. What version of Go are you using (`go version`)?
2017/03/29 19:52:24 printer.go:31: [info] Welcome to TiDB.
2017/03/29 19:52:24 printer.go:32: [info] Version:
2017/03/29 19:52:24 printer.go:33: [info] Git Commit Hash: cca10bab58a767570c3cf672f84b9a9660488317
2017/03/29 19:52:24 printer.go:34: [info] UTC Build Time:  2017-03-15 03:27:14

**Comment by ngaut** [comment]
Fixed, please try the master branch.
