### ISSUE TITLE
goword returns errors

### ISSUE THREAD

**Issue by dveeden** [pingcap/tidb#29552]
### 1. Minimal reproduce step (Required)

`make goword` returns a lot of errors

### 2. What did you expect to see? (Required)

A clean run or errors related to local changes

### 3. What did you see instead (Required)

```
[dvaneeden@dve-carbon tidb]$ make goword | sed 's/\.[0-9]*:.*$//' | sort | uniq -c | sort -rn | head
make: *** [Makefile:44: goword] Error 1
     93 br/pkg/lightning/backend/local/local.go
     70 util/stmtsummary/statement_summary.go
     51 config/config.go
     38 planner/core/physical_plans.go
     32 store/mockstore/unistore/config/config.go
     28 store/mockstore/unistore/cophandler/cop_handler_test.go
     26 util/stmtsummary/statement_summary_test.go
     26 planner/core/memtable_predicate_extractor.go
     26 executor/aggfuncs/aggfuncs.go
     24 planner/core/logical_plans.go
```

### 4. What is your TiDB version? (Required)

git master @ e98d587577d66e358c50edaa39f08852a0b3314d

My suggested solution is to:

- Fix the problems and enable goword checks on PRs
- OR: remove "make goword" etc.

**Comment by Defined2014** [comment]
`make goword` is removed by https://github.com/pingcap/tidb/pull/36871, so close this issue.
