### ISSUE TITLE
Lightning: found race in atom-ut.

### ISSUE THREAD

**Issue by missarten** [pingcap/tidb#29566]
## Bug Report

RunServer race:
https://ci.pingcap.net/job/atom-ut/1062/testReport/github/com_pingcap_tidb_br_pkg_lightning/TestRunServer/

GetDeleteTask race:
https://ci.pingcap.net/job/atom-ut/1062/testReport/github/com_pingcap_tidb_br_pkg_lightning/TestGetDeleteTask/
### 2. What did you expect to see? (Required)
No race.
### 3. What did you see instead (Required)
CI failed.
### 4. What is your TiDB version? (Required)

master

**Comment by glorv** [comment]
close by #29077 after making these cases serialized.

**Comment by glorv** [comment]
Only affect nightly.
