### ISSUE TITLE
v4.0.15 upgrade to v5.3.0, the default_db in sql binding lost after upgrade

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#29576]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in v4.0.15
use test;
drop table if exists t;
create table t(a int, b int, c int, index idx(a));
create global binding for select * from t where a < 1 using select * from t use index(idx) where a < 1;
create global binding for select * from t where a < 1 using select * from t ignore index(idx) where a < 1;
show global bindings;
[tidb@101 ~]$ mysql -h 172.16.5.101 -P 4000 -uroot -e 'show global bindings;'
+------------------------------------+-------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql                       | Bind_sql                                                    | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+------------------------------------+-------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from test . t where a < ? | SELECT * FROM `test`.`t` IGNORE INDEX (`idx`) WHERE `a` < 1 | test       | using  | 2021-11-08 21:20:19.415 | 2021-11-08 21:20:19.415 | utf8    | utf8_general_ci | manual |
+------------------------------------+-------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
upgrade to v5.3.0
show global bindings;
MySQL [(none)]> show global bindings;
+-------------------------------------------+--------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| Original_sql                              | Bind_sql                                                     | Default_db | Status | Create_time             | Update_time             | Charset | Collation       | Source |
+-------------------------------------------+--------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
| select * from `test` . `t` where `a` < ?  | SELECT * FROM `test`.`t` IGNORE INDEX (`idx`) WHERE `a` < 1  |            | using  | 2021-11-08 21:20:19.415 | 2021-11-08 21:35:01.760 | utf8    | utf8_general_ci | manual |
+-------------------------------------------+--------------------------------------------------------------+------------+--------+-------------------------+-------------------------+---------+-----------------+--------+
2 rows in set (0.01 sec)

### 2. What did you expect to see? (Required)
binding info will be same after upgrade to v5.3.0

### 3. What did you see instead (Required)
value in default_db is lost

### 4. What is your TiDB version? (Required)
------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.3.0
Edition: Community
Git Commit Hash: e401a0606bf84214bd8e765295ec6cfadd9ba24e
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-08 04:40:23
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by rebelice** [comment]
Losing `default_db` is the expected behavior. In the internal logic, `default_db` is no longer used. I think it's not a bug.
