### ISSUE TITLE
Time out test `table/tables`

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#29647]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```bash
[2021-11-09T09:06:20.320Z] FAIL	github.com/pingcap/tidb/table/tables	600.169s
```
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_coverage/detail/tidb_ghpr_coverage/1123/pipeline

**Comment by JayL-zxl** [comment]
see #29632. sorry my mistake. we have been solved it. and open a new pr. but it in reviews.

**Comment by aytrack** [comment]
> see #29632. sorry my mistake. we have been solved it. and open a new pr. but it in reviews.

OK, I will close this issue.
