### ISSUE TITLE
`skip-grant` tidb set password can't take affect

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#29653]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster with (node tidb1)
2. start a new tidb node  with `security.skip-grant-table=true` (node tidb2)
3. connect  tidb2 to set the password and `flush privileges`
4. connect tidb1 use the password

### 2. What did you expect to see? (Required)
1. can login successfully with the set password connect to tidb1
### 3. What did you see instead (Required)
1. can not use the set password connect tidb1
2. `select * from mysql.user` dispaly that the password was record correct
3. use tidb1 `flush privileges`, then it's will take affect
### 4. What is your TiDB version? (Required)
release-5.3(c6d652), master (99ab8bf16f6f61cb8d4a)

**Comment by djshow832** [comment]
It is caused by https://github.com/pingcap/tidb/pull/27958 and https://github.com/pingcap/tidb/pull/29358
A previous stack on 5.2.2:
`executeSetPwd`
    `NotifyUpdatePrivilege`
        `etcdClient.KV.Put`
`flushPrivilege`
    if skip: return
    else: `NotifyUpdatePrivilege`

The current stack on 5.3.0:
`executeSetPwd`
    `NotifyUpdatePrivilege`
           if skip: return
           else: `etcdClient.KV.Put`
`flushPrivilege`
     `NotifyUpdatePrivilege`
