### ISSUE TITLE
Add Support for "Built In Placement Policies"

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#29677]
This subtask is to implement [this part](https://github.com/pingcap/tidb/blob/master/docs/design/2020-06-24-placement-rules-in-sql.md#built-in-placement-policies) of the technical design doc:

> #### Built-in Placement Policies
> 
> By default every system will have two placement policies, which can be modified via `ALTER PLACEMENT POLICY` but never dropped:
> 
> * `default`: This policy is used only in the event that a policy has not been specified.
> * `system`: This policy is used for internal TiDB system tables.
> 
> Some common applications might be to increase the replica count on system or default tables. It is not typically recommended to add constraints to these policies as it will lead to cluster inbalance, but it is possible.

**Comment by nolouch** [comment]
The scenario is custom deploy TiDB in three data center, the policy want to make the remote data center does not have a leader and is only used for backup purposes.

**Comment by lcwangchao** [comment]
Some behaviors should be discussed:

- Should `SHOW CREATE PLACEMENT POLICY ...` be allowed for `default` or `system` policy. If it is allowed,  what is the result if user have never set a custom `default` or `system` policy (no constraints)? `SHOW PLACEMENTS` also has the same problem.

- If a `default` policy was set with some constraints. What should user do if he/she wants to place a table without any constraints.

**Comment by xhebox** [comment]
1. `default` is used to reset placement rules in the current design. It is conflicting with this behavior.
2. For implementation, it is easy to create a policy applied to all regions. But you will need to exclude regions one by one, for example `system` tables.

**Comment by morgo** [comment]
I've removed this part of the plan from the technical design. We can re-evaluate it in this issue and potentially re-add it in future.
