### ISSUE TITLE
small cached table doesn't support index merge

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#29682]
## Enhancement

While developing, I found this https://github.com/pingcap/tidb/pull/29443#discussion_r746302436, thanks to @lcwangchao for pointing it out. 
and seaching the issues list, there is a known issue https://github.com/pingcap/tidb/issues/28494 here

So **small cached table doesn't support index merge**

This limitation is imposed by the fact union scan doesn't support index merge... 
small cached table implemetation depends on union scan, so it gets the same limitation.

**Comment by Defined2014** [comment]
I think the IndexMerge works well with small cached table now. And IndexMerge already supported UnionScan by https://github.com/pingcap/tidb/pull/29875, so close this issue.
