### ISSUE TITLE
lightning checksum error when parallel import data

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#29692]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Use 2 lightning instance to parallel import data to TiDB, no data conflict in the data source

### 2. What did you expect to see? (Required)
1. Lightning import should succeed 

### 3. What did you see instead (Required)
1. Lighting reports checksum error 
```
Error: checksum mismatched remote vs local => (checksum: 11222303442876741793 vs 3225814776482587640) (total_kvs: 18161516 vs 9080796) (total_bytes:3368780389 vs 1684395306)\ntidb lightning encountered error:  checksum mismatched remote vs local => (checksum: 11222303442876741793 vs 3225814776482587640) (total_kvs: 18161516 vs 9080796) (total_bytes:3368780389 vs 1684395306)
```

### 4. What is your TiDB version? (Required)
/ # /tidb-lightning -V
Release Version: v5.3.0
Git Commit Hash: c6d65239a01662b239ff6f6c10abda4ab28ec8c5
Git Branch: heads/refs/tags/v5.3.0
Go Version: go1.16.4
UTC Build Time: 2021-11-10 14:29:25
Race Enabled: false

**Comment by kennytm** [comment]
18161516 = 9080796 × 2 − 76
3368780389 = 1684395306 × 2 − 10223
🤔
