### ISSUE TITLE
Internal error when pushdown agg into partitionUnion

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#29705]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
drop table if exists t;
create table t(id int) partition by hash(id) partitions 4;
insert into t values(1);
SELECT COUNT(1) FROM ( SELECT COUNT(1)  FROM t b GROUP BY id) a;

### 2. What did you expect to see? (Required)
```
MySQL [test]> SELECT COUNT(1) FROM ( SELECT COUNT(1)  FROM t b GROUP BY id) a;
+----------+
| COUNT(1) |
+----------+
|        1 |
+----------+
1 row in set (0.000 sec)
```

### 3. What did you see instead (Required)
ERROR 1105 (HY000): Internal error: UnionExec chunk column count mismatch, req: 1, result: 2
### 4. What is your TiDB version? (Required)
master

**Comment by wshwsh12** [comment]
Explain reuslt:
```
+----------------------------------+----------+-----------+-----------------------+-------------------------------------------------------------------------------------+
| id                               | estRows  | task      | access object         | operator info                                                                       |
+----------------------------------+----------+-----------+-----------------------+-------------------------------------------------------------------------------------+
| HashAgg_18                       | 1.00     | root      |                       | funcs:count(1)->Column#4                                                            |
| └─HashAgg_20                     | 24001.00 | root      |                       | group by:test.t.id, funcs:count(1)->Column#7                                        |
|   └─PartitionUnion_21            | 24001.00 | root      |                       |                                                                                     |
|     ├─HashAgg_24                 | 8000.00  | root      |                       | group by:test.t.id, funcs:firstrow(test.t.id)->test.t.id, funcs:count(1)->Column#8  |
|     │ └─TableReader_29           | 10000.00 | root      |                       | data:TableFullScan_28                                                               |
|     │   └─TableFullScan_28       | 10000.00 | cop[tikv] | table:b, partition:p0 | keep order:false, stats:pseudo                                                      |
|     ├─HashAgg_32                 | 1.00     | root      |                       | group by:test.t.id, funcs:firstrow(test.t.id)->test.t.id, funcs:count(1)->Column#9  |
|     │ └─TableReader_37           | 1.00     | root      |                       | data:TableFullScan_36                                                               |
|     │   └─TableFullScan_36       | 1.00     | cop[tikv] | table:b, partition:p1 | keep order:false, stats:pseudo                                                      |
|     ├─HashAgg_40                 | 8000.00  | root      |                       | group by:test.t.id, funcs:firstrow(test.t.id)->test.t.id, funcs:count(1)->Column#10 |
|     │ └─TableReader_45           | 10000.00 | root      |                       | data:TableFullScan_44                                                               |
|     │   └─TableFullScan_44       | 10000.00 | cop[tikv] | table:b, partition:p2 | keep order:false, stats:pseudo                                                      |
|     └─HashAgg_48                 | 8000.00  | root      |                       | group by:test.t.id, funcs:firstrow(test.t.id)->test.t.id, funcs:count(1)->Column#11 |
|       └─TableReader_53           | 10000.00 | root      |                       | data:TableFullScan_52                                                               |
|         └─TableFullScan_52       | 10000.00 | cop[tikv] | table:b, partition:p3 | keep order:false, stats:pseudo                                                      |
+----------------------------------+----------+-----------+-----------------------+-------------------------------------------------------------------------------------+
15 rows in set (1.732 sec)
```
I debug tidb-server, and find that PartitionUnion's schema only have one Column.

**Comment by wshwsh12** [comment]
Need release in 5.1.3/5.2.3

**Comment by qw4990** [comment]
PTAL @mjonss

**Comment by mjonss** [comment]
Fails on old/default static pruning mode, works with `set @@tidb_partition_prune_mode='dynamic'`.

**Comment by mjonss** [comment]
Regression from 68e32bb44e37e70952aaa1802af34e59e8d5aad3 / https://github.com/pingcap/tidb/pull/27798 / https://github.com/pingcap/tidb/issues/27797

**Comment by mjonss** [comment]
Also seems like the test case in https://github.com/pingcap/tidb/pull/27798 does not trigger the issue reported in those bugs, but manually running it on a standalone tidb-server does.
I.e. if I revert the code change in `planner/core/rule_aggregation_push_down.go`, the test still passes...

**Comment by lcwangchao** [comment]
This problem is caused by `LogicalAggregation.PruneColumns` . See: https://github.com/pingcap/tidb/blob/75f6225948e71c285254c70f10c6ef1b7bfcd812/planner/core/rule_column_pruning.go#L114-L135

Sometimes `LogicalAggregation` will add one new column after pruning but as its parent,  `LogicalUnionAll` does not handle situation.

Some related PRs:
- #10974
- #24937
- #25289

**Comment by lcwangchao** [comment]
It is easy to fix it just forcing LogicalAggregation's schema the same with it's children after pruning, but I don't know whether this way has some potential problems.

I think it has related to the semantics for `PruneColumns` . Should we allow `PruneColumns` to add extra columns after pruning which will require all its parent considering about this.

**Comment by lcwangchao** [comment]
Another way to fix it is to modify executor codes to make executor can correctly handle the case where the number of columns is 0 (The case where all agg functions is first_row should be processed too).

**Comment by time-and-fate** [comment]
> Also seems like the test case in #27798 does not trigger the issue reported in those bugs, but manually running it on a standalone tidb-server does. I.e. if I revert the code change in `planner/core/rule_aggregation_push_down.go`, the test still passes...

The reason behind this is that the default `tidb_partition_prune_mode` is `dynamic` in the test and the bug occurs in the `static` mode. I'll fix this in the PR for this issue.
