### ISSUE TITLE
executor: SQL after IndexLookUpExecutor may be slow

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#29716]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- 1. Create a table with a non-unique index, generate about 10,000,000 rows(I use this [script](https://gist.github.com/you06/c4f5032b6492864e72afea2119207c85)).
- 2. Make an indexlookup query with limit, once it's done, do `select 1;`.
- 3. Repeat step2.

### 2. What did you expect to see? (Required)

The `select 1;` query should be fast, at least less than 10ms.

### 3. What did you see instead (Required)

```sql
MySQL [test]> select * from t force index(i) where c2 > 1 and c2 < 12000000 and c3 in (3) order by c2 desc limit 11; select 1;
+----------+----------+------+
| c1       | c2       | c3   |
+----------+----------+------+
|  2925230 | 11999949 |    3 |
|  4950694 | 11999947 |    3 |
| 11778881 | 11999851 |    3 |
|  2244706 | 11999851 |    3 |
| 10488089 | 11999821 |    3 |
|  5891917 | 11999812 |    3 |
| 11706844 | 11999801 |    3 |
| 10178503 | 11999619 |    3 |
| 13321140 | 11999576 |    3 |
|  5117855 | 11999563 |    3 |
|  9638867 | 11999561 |    3 |
+----------+----------+------+
11 rows in set (0.00 sec)

+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.49 sec)
```

The `select 1;` costs about half a second.

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-87-g58c02d5bb
Edition: Community
Git Commit Hash: 58c02d5bb7b25aa810c8279c5eb7de95a0362356
Git Branch: master
UTC Build Time: 2021-11-11 11:47:06
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by you06** [comment]
The root cause of this issue is when indexlookup reads enough data(there is a limit executor), it responds the result and success to the client. The client then executes the next SQL. However, when TiDB receives the next SQL(like `select 1;`), the connection thread may still be blocked by the `Close` function.

The `Close` function won't return until all requests are done.

https://github.com/pingcap/tidb/blob/a4bd02e35ce0f0236ae055984a65d38494a8e247/executor/distsql.go#L684-L685

**Comment by fuzhe1989** [comment]
do other executors have the same problem?

**Comment by you06** [comment]
> do other executors have the same problem?

I took look at the [3 distsql executors](https://github.com/pingcap/tidb/blob/d3a4187f7e99a0c156912b6831686e89fc8b6a85/executor/distsql.go#L57-L61), and only find `IndexLookUpExecutor` has such a problem, not checked other executors yet.

**Comment by cfzjywxk** [comment]
Some situations could be simulated and the slow `close` may impact the query time much but we could not find useful information from the slow log, just like 
```
User: root@127.0.0.1
# Conn_ID: 1
# Query_time: 5.001170231
# Parse_time: 0.000072633
# Compile_time: 0.00013317
# Request_count: 5
# DB: test
# Is_internal: false
# Digest: f8ad2efeeeff50103069a7a675912139d9931bae98b8969191ab4f479aca76ed
# Stats: t:pseudo
# Num_cop_tasks: 5
# Cop_proc_avg: 0 Cop_proc_p90: 0 Cop_proc_max: 0 Cop_proc_addr: store1
# Cop_wait_avg: 0 Cop_wait_p90: 0 Cop_wait_max: 0 Cop_wait_addr: store1
# Mem_max: 105
# Prepared: false
# Has_more_results: false
# Succ: true
# Plan: tidb_decode_plan('ogGYMAkxNl83CTAJMTAJb2Zmc2V0OjAsIGNvdW50OjEwCjEJMzJfMTIJBSA4ZGF0YTpMaW1pdF8xMQoyAToMMTEJMVo7ABgzCTEwXzEwCSDodGFibGU6dCwgcmFuZ2U6Wy1pbmYsK2luZl0sIGtlZXAgb3JkZXI6ZmFsc2UsIHN0YXRzOnBzZXVkbwo=')
select * from t use index(primary) limit 10;
```

**Comment by you06** [comment]
> Some situations could be simulated and the slow `close` may impact the query time much but we could not find useful information from the slow log, just like

The latency appears between two statements, so no statement will record it. Maybe a `wait_start_time` would be helpful in diagnosing.
