### ISSUE TITLE
lightning output a lot of useless charset convert warn log

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#29744]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Running v5.3 tidb-lightning with default charset convert setting

### 3. What did you see instead (Required)
lightning output a lot of warn log as following:
```
[WARN] [charset_converter.70]["incompatible strings may be encountered during the transcoding process and will be replaced, please be aware of the risk of not being able to retain the original information"] ["source-character-set"="binary"]
```

**Comment by kennytm** [comment]
it should only be warned once.
