### ISSUE TITLE
one tidb oom after run insert workload 40min

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#29749]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
oltp_001_
load some sysbench data by br
run sysbench  insert 

### 2. What did you expect to see? (Required)
all pod are normal

### 3. What did you see instead (Required)
after 40min，one tidb oom
![image](https://user-images.githubusercontent.com/84712107/141611150-2f6d72f8-5156-462d-b550-e00eb49f35af.png)
NS：endless-oltp--tps-360668-1-571
grafana port：30778

### 4. What is your TiDB version? (Required)
/ # ./tidb-server -V
Release Version: v5.3.0
Edition: Community
Git Commit Hash: b00648b41f3641c0dae27b409449648196ea88f9
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-12 11:54:28
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by winoros** [comment]
We will use #30880 to trace it.
