### ISSUE TITLE
Refine only-full-group-by checker

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#29766]
## Enhancement

TiDB's only-full-group-by checker is not so compatible with MySQL. The incompatibility brings trouble to users and the current workaround is to remove `ONLY_FULL_GROUP_BY` from `sql_mode`. We need to make only-full-group-by checker more compatible with MySQL.

Here are the issues related to only-full-group-by checker:
- https://github.com/pingcap/tidb/issues/29418
- https://github.com/pingcap/tidb/issues/27723
- https://github.com/pingcap/tidb/issues/27539
- https://github.com/pingcap/tidb/issues/26576
- https://github.com/pingcap/tidb/issues/25199
- https://github.com/pingcap/tidb/issues/25196
- https://github.com/pingcap/tidb/issues/22694
- https://github.com/pingcap/tidb/issues/22301
- https://github.com/pingcap/tidb/issues/25089
- https://github.com/pingcap/tidb/issues/21848
- https://github.com/pingcap/tidb/issues/30024

One cause for some issues is that only-full-group-by checker is not smart enough to infer some functional dependency(See https://github.com/pingcap/tidb/issues/14580 for details).

**Comment by winoros** [comment]
The design doc:
https://pingcap.feishu.cn/docs/doccndyrRWfcGALhjcyVhOrxWYd

**Comment by winoros** [comment]
Splitted working items

- [ ] Introducing the basic structure for the functional dependency.
- [ ] Implementing the basic inserting logic of strict functional dependency.
- [ ] Implementing the basic inserting logic of strict equiv constraint.
- [ ] Implementing the basic inserting logic of lax functional dependency.
- [ ] Implementing the maintain for DataSource.
- [ ] Implementing the maintain for Selection.
- [ ] Implementing the maintain for inner join.
- [ ] Implementing the maintain for outer join.
- [ ] Implementing the maintain for Aggregation.
- [ ] Implementing the maintain for Projection.
- [ ] Implementing the maintain for Union/Except/Intersect.
- [ ] Implementing the maintain for View/CTE.
- [ ] Testing against the SQL mode.
