### ISSUE TITLE
a possible inconsistent snapshot

### ISSUE THREAD

**Issue by xiaozuan33** [pingcap/tidb#29760]
### 1. Minimal reproduce step (Required)
1. `git clone git@github.com:xiaozuan33/tidb_test.git`
2. follow the steps in stolon_wr/README.md

The tidb test will generate a series of pairs of transactions. Each pair of transactions consists of 1 insert transaction and 1 write transaction respectively over an unique key.

### 2. What did you expect to see? (Required)
Under snapshot isolation(or advertised as repeatable read to be compatible with MySQL):
- If a transaction finds that a key doesn’t exist and writes(update) a key immediately, the update-count of this write should be 0. 
- If two transactions write the same key concurrently, these two transactions cannot both commit. Here two transactions are executed concurrently means their intervals of [start timestamp, commit timestamp] overlap.

### 3. What did you see instead (Required)
We encounter two transactions(txn for short) similar to the following in the execution histories:

txn 1:
BEGIN;
SELECT val FROM table WHERE id = 9; 
INSERT INTO table (id, val) VALUES (9, 2);
COMMIT;

txn 1 firstly reads the value of key 9 and finds that key 9 doesn’t exist, and then inserts a value 2 and succeeds. 

txn 2:
BEGIN;
SELECT val FROM table WHERE id = 9;
UPDATE table SET val = 1 WHERE id = 9;
COMMIT;

txn 2 firstly reads the value of key 9 and finds that key 9 doesn’t exist, then updates the value of key 9 to 1. The returned update-count is positive. 

Here are just two different perspectives to consider the anomaly:
txn2 reads a snapshot that key 9 doesn’t exist, then it should be able to commit with the update-count=0 while the actual update-count is positive.

txn 2 could successfully update the key 9 and this implies that it had observed the effect of the insert operation in txn 1. Recall txn 2 also reads a snapshot before this insert, it implies these two transactions’ [start timestamp, commit timestamp] overlap. Then these two transactions should be unable to both commit by the definition in adya’s thesis.

### 4. What is your TiDB version? (Required)
Server version: 5.7.25-TiDB-v5.2.2 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

**Comment by sticnarf** [comment]
This behavior is consistent with MySQL 5.7. Even if the isolation level is set to "snapshot isolation", update in MySQL has RC semantics.
