### ISSUE TITLE
QPS drop can not meet expectations when run sysbench read-write and DDL（add index）

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#29773]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
oltp_004
run sysbench read-write 512 Threads
add index

### 2. What did you expect to see? (Required)
QPS drop less than 50%

### 3. What did you see instead (Required)
![mq8vPjrm3g](https://user-images.githubusercontent.com/84712107/141736855-0bfbc309-2831-4aae-ac17-3d95a32ab50b.png)

### 4. What is your TiDB version? (Required)
/ # ./tidb-server -V
Release Version: v5.3.0
Edition: Community
Git Commit Hash: b00648b
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-12 11:54:28
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by wjhuang2016** [comment]
Should be solved by `adding index by lightning` which would be GA in 6.5
