### ISSUE TITLE
`rand_seed` system variable does not support replication of the RAND() function

### ISSUE THREAD

**Issue by espresso98** [pingcap/tidb#29819]
## Bug Report
In TiDB, rand_seed variables are ignored.  The result should always respond 0.02887.

### 1. Minimal reproduce step 
Repeat this several times. 
```sql
set @@rand_seed1=10000000,@@rand_seed2=1000000;
select ROUND(RAND(),5);
```
### 2. What did you expect to see?
In MySQL
```sql
mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.02887 |
+-----------------+
1 row in set (0.00 sec)

mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.02887 |
+-----------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead 
In TiDB
```sql
mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.03 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.27441 |
+-----------------+
1 row in set (0.01 sec)

mysql> set @@rand_seed1=10000000,@@rand_seed2=1000000;
Query OK, 0 rows affected (0.00 sec)

mysql> select ROUND(RAND(),5);
+-----------------+
| ROUND(RAND(),5) |
+-----------------+
|         0.34586 |
+-----------------+
1 row in set (0.01 sec)

mysql> show variables like '%rand_seed%';
+---------------+----------+
| Variable_name | Value    |
+---------------+----------+
| rand_seed1    | 10000000 |
| rand_seed2    | 1000000  |
+---------------+----------+
2 rows in set (0.00 sec)
```

### 4. What is your TiDB version?
```sql
tidb_version(): Release Version: v5.2.2
Edition: Community
Git Commit Hash: da1c21fd45a4ea5900ac16d2f4a248143f378d18
Git Branch: heads/refs/tags/v5.2.2
UTC Build Time: 2021-10-20 06:03:29
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by Defined2014** [comment]
https://github.com/pingcap/tidb/blob/62b07a6c92f08fdfec02d49891a5492ab39e3b24/sessionctx/variable/noop.go#L278
https://github.com/pingcap/tidb/blob/62b07a6c92f08fdfec02d49891a5492ab39e3b24/sessionctx/variable/noop.go#L62

They are noop variable in TiDB. Maybe we can control them with `tidb_enable_noop_function`. What do you think of it? @morgo

**Comment by morgo** [comment]
> They are noop variable in TiDB. Maybe we can control them with `tidb_enable_noop_function`. What do you think of it? @morgo

It's possible, but we should check with tools team:

MySQL historically used statement-based replication (the default only changed to ROW in MySQL 5.7 and some users might have changed it back to statement). With statement-based replication, using `RAND()` in the SQL statement is still safe because it uses these variables internally to seed the rand function.

If TiDB replays a statement from a MySQL server with SBR, this issue could lead to data corruption (in a case where MySQL handles it fine). So either requiring `tidb_enable_noop_function` to be enabled, or supporting it is acceptable behavior. The current parse-but-ignore behavior here is not good.

**Comment by dveeden** [comment]
> > They are noop variable in TiDB. Maybe we can control them with `tidb_enable_noop_function`. What do you think of it? @morgo
> 
> It's possible, but we should check with tools team:
> 
> MySQL historically used statement-based replication (the default only changed to ROW in MySQL 5.7 and some users might have changed it back to statement). With statement-based replication, using `RAND()` in the SQL statement is still safe because it uses these variables internally to seed the rand function.
> 
> If TiDB replays a statement from a MySQL server with SBR, this issue could lead to data corruption (in a case where MySQL handles it fine). So either requiring `tidb_enable_noop_function` to be enabled, or supporting it is acceptable behavior. The current parse-but-ignore behavior here is not good.

From https://docs.pingcap.com/tidb-data-migration/stable/precheck#checking-items:
"DM only supports migration of the binlog in the ROW format"

**Comment by morgo** [comment]
OK, it doesn't look like it affects DM, so lets leave it as moderate.

**Comment by Defined2014** [comment]
> https://github.com/pingcap/tidb/blob/62b07a6c92f08fdfec02d49891a5492ab39e3b24/sessionctx/variable/noop.go#L278
> 
> 
> https://github.com/pingcap/tidb/blob/62b07a6c92f08fdfec02d49891a5492ab39e3b24/sessionctx/variable/noop.go#L62
> 
> They are noop variable in TiDB. Maybe we can control them with `tidb_enable_noop_function`. What do you think of it? @morgo

PR #20357 gives the reason why we didn't have `tidb_enable_noop_sysvars ` right now. :(
