### ISSUE TITLE
Add Metrics to Monitor PD API call exection time

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#29821]
This issue was reported by @AilinKid 

We should support the ability to time PD API calls so that we can better investigate user reported issues with placement rule DDL. There might be some scenarios where PD API call time takes longer than expected.

**Comment by jyz0309** [comment]
/assign
I think we can just time the [`requestPD(method, uri string, body io.Reader, res interface{}) error`](https://github.com/pingcap/tidb/blob/af5b449270128220e1cb559cacb62b43d6dacca9/store/helper/helper.go#L743) function, Is it?
