### ISSUE TITLE
Support internal function `to_binary()` for new charset

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#29863]
**The code changes about built-in functions in TiKV can be minimized.**

After the investigation about several built-in functions, I found some common patterns:

1. Create a new encoding.
1. Convert the arguments into new charset from utf8.
1. Apply these changes to the vectorized-version evaluation.

We can extract these patterns into another `Sig` named `builtinToBinarySig`(`to_binary()`) and wrap the cast function as follows:

The rewrite process **before** this proposal:
```sql
select some_builtin(arg1, arg2...)
```
is rewritten to 
```sql
select some_builtin(cast_as_string(arg1), cast_as_string(arg2)...)
```

The rewrite process **after** this proposal:
```sql
select some_builtin(arg1, arg2...)
```
is rewritten to 
```sql
select some_builtin(to_binary(cast_as_string(arg1)), to_binary(cast_as_string(arg2))...)
```

Then we can maintain a built-in function list to determine which function needs to be wrapped, instead of putting the boilerplates everywhere.

```go
var toBinaryMap = map[string]struct{}{
	ast.Hex: {}, ast.Length: {}, ast.OctetLength: {}, ast.ASCII: {},
	ast.ToBase64: {},
}
```

**Comment by tangenta** [comment]
@zimulala @xiongjiwei @ou-bing @Defined2014 @unconsolable @jackwener @chacha923 @hawkingrei @JayL-zxl FYI, please feel free to leave your suggestions.

**Comment by unconsolable** [comment]
Looks good since it can reduce code repetition, but I have a small question.
This code is from `(*builtinInternalToBinarySig).vecEvalString`
```go
	for i := 0; i < n; i++ {
		var str string
		if buf.IsNull(i) {
			result.AppendNull()
			continue
		}
		str = buf.GetString(i)
		str, err = enc.EncodeString(str)
```
I wonder whether an encode buffer should be introduced here to reduce memory allocation.

**Comment by tangenta** [comment]
@unconsolable Good catch! If you are interested in it you can file a PR to fix it. 

By the way, we are also trying to collect all the functions that can be wrapped by `to_binary()` and add them to the list, you can also include some of them in your PR.
