### ISSUE TITLE
Auto analyze throw GCTooEarly error

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#29862]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Generate a table that needs analyze more than 20min.
2. Trigger auto analyze.
3. Delate the table, and wait gc.
4. Auto analyze fails, and gets error `[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2021-11-17 14:09:54.756 +0800 CST, GC safe point is 2021-11-17 14:11:54.755 +0800 CST`

TiDB only gets all startTs from ProcessLists and reports to PD, but ignore internal session.

### 2. What did you expect to see? (Required)
Analyze success

### 3. What did you see instead (Required)
Analyze failed

### 4. What is your TiDB version? (Required)
master.

**Comment by winoros** [comment]
The gc worker doesn't watch the internal session. Other internal SQL which may run a lot of time may also meet this issue.

**Comment by winoros** [comment]
The gc worker doesn't watch the internal session. Other internal SQL which may run a lot of time may also meet this issue.

**Comment by AilinKid** [comment]
After discussion with Eason and Dev guys: this is reasonable, we don't need to extend GC interval to match the internal analyze start timestamp, cause the analyze result for should-be-GCed data doesn't have it meanings. Maybe the log level for the internal sql error should be adjusted lower.
