### ISSUE TITLE
lightning: setting `--log-file "-"` will not print any log to stdout

### ISSUE THREAD

**Issue by fengou1** [pingcap/tidb#29876]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create a tidb cloud cluster
2. import some data into cluster
3. check Loki/ES by cluster ID and orgID
4. lightning log been truncated

DBaaS run lightning by parameter: --log-file="-", issue can be reproduced in 5.3.0 env.

### 2. What did you expect to see? (Required)
After DBaaS import data done, Loki/ES shall able to show all lightning log.

### 3. What did you see instead (Required)
Loki/ES only show part of lightning log at very begin of lightning start.
![DelnFP9KnC](https://user-images.githubusercontent.com/85682690/142185611-9011bfcd-2a4c-4189-84f4-282953adca5f.png)

### 4. What is your TiDB version? (Required)
```
/tmp # /tidb-lightning -V
Release Version: v5.3.0
Git Commit Hash: c83f032b04a40b3148dff712392dd924ae064132
Git Branch: heads/refs/tags/v5.3.0
Go Version: go1.16.4
UTC Build Time: 2021-11-16 11:54:51
Race Enabled: false
```

**Comment by kennytm** [comment]
this bug is introduced by #29291, which skips initializing logger when the log file is set to empty.

https://github.com/pingcap/tidb/blob/34bd98d39e9b355abd85b76bd47cf8e5a3a78bda/br/pkg/lightning/lightning.go#L77-L82
