### ISSUE TITLE
"analyze table" has a potential oom risk

### ISSUE THREAD

**Issue by ChenPeng2013** [pingcap/tidb#29938]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a table
2. insert many data
3. analyze table t with 0.999999 samplerate;

### 3. What did you see instead (Required)
```
tidb-server invoked oom-killer: gfp_mask=0x600040(GFP_NOFS), nodemask=(null), order=0, oom_score_adj=0
```

### 4. What is your TiDB version? (Required)

release-5.3

**Comment by winoros** [comment]
A too large sample rate won't help the accuracy of the statistics.
We would make the command safer to execute.
