### ISSUE TITLE
xx-in-txn are missing in the Connection Idle Duration

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#29967]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
![image](https://user-images.githubusercontent.com/2316425/142786984-448cd3b2-e42c-4475-9195-59ff8fd3138c.png)

### 2. What did you expect to see? (Required)
deploy a v5.3.0 version

### 3. What did you see instead (Required)
no xx-in-txn metrics in Connection Idle Duration panel

### 4. What is your TiDB version? (Required)

v5.3.0

**Comment by zyguan** [comment]
Please show what are you running? why do you think there must be xx-in-txn?

**Comment by dbsid** [comment]
it turns out that for workload without transaction(oltp_point_select or oltp_read_only), there is no metrics for xx-in-transactions.
