### ISSUE TITLE
CI unstable test mysql `auto_increment` failed

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#29972]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/7787/pipeline/144/

may because the `CREATE TABLE t1 (c1 DOUBLE NOT NULL AUTO_INCREMENT, c2 INT, PRIMARY KEY (c1))\nENGINE=InnoDB;` user test database, but above use auto_increment database, conflict  with other cases.

**Comment by hawkingrei** [comment]
fixed

/close
