### ISSUE TITLE
member attributes `probeTypes` and `buildTypes` in `HashJoinExec` can be removed

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#29994]
## Enhancement
The member attributes `probeType` and `buildType` in `HashJoinExec` can be removed actually.
They are always the same.
A tiny code refactor needs to be done for this modification.

**Comment by JayL-zxl** [comment]
i have some problems about this issue..

**Comment by XuHuaiyu** [comment]
@JayL-zxl 
Feel free to ask

**Comment by JayL-zxl** [comment]
@XuHuaiyu I sent you a private message on slack

**Comment by JayL-zxl** [comment]
@XuHuaiyu

**Comment by JayL-zxl** [comment]
@XuHuaiyu  hi if remove probeType and buildType in HashJoinExec. may cause `runJoinWorker` and `Next` function can't easily get `probeType` and `buildType` ...

**Comment by XuHuaiyu** [comment]
It seems I misunderstood the meaning of the `probeType` and `buildType`. I thought they are totally the same before.
I check the code again, the `Flag` of `probeType` and `buildType` may be different. For example, when hashing a signed int value or an unsigned int value, the `UnsignedIntFlag` needs to be taken into consideration.
Thus we need to keep the existence of `probeType` and `buildType`.

Sorry for misleading you. @JayL-zxl

**Comment by XuHuaiyu** [comment]
Close this issue since we do not need to do this furthermore.
