### ISSUE TITLE
TiDB behaves differently than MySQL on authentication of users with the same name and different hosts when wild card involved

### ISSUE THREAD

**Issue by zhaopei05** [pingcap/tidb#29995]
### 1. Minimal reproduce step (Required)
Login as 'root' and create 2 users as follows:
create user 'test'@'%' identified by '%'
create user 'test'@'localhost' identified by 'localhost'
Try to login as 'test' from localhost with password '%'.

### 2. What did you expect to see? (Required)
MySQL will reject the login with error message like 'ERROR 1045 (28000): Access denied for user 'test'@'localhost' (using password: YES)

### 3. What did you see instead (Required)
Login succeeds, and CURRENT_USER() will be recognized as 'test'@'%'

### 4. What is your TiDB version? (Required)
v4.0.15

**Comment by mjonss** [comment]
MySQL maps '127.0.0.1' to 'localhost', which makes it hard to distinguish between using unix socket and tcp from+to loopback interface ipv4 127.0.0.1
TiDB does not currently map in between, so localhost is matching unix socket and 127.0.0.1 is matching ipv4 loopback network interface.

If the test would be extended with:
`create user 'test'@'127.0.0.1' identified by '127.0.0.1'`
it would show the difference between MySQL and TiDB more clearly (also notice on how to connect, through unix socket or tcp/ipv4)

**Comment by dveeden** [comment]
I've tested with TiDB v5.2.2, MySQL 5.7.36 and MySQL 8.0.

If I connect over TCP (e.g. `-h 127.0.0.1 -P 4000`) I indeed get a connection with TiDB as described and MySQL 5.7 and 8.0 will return an error. When connecting over a UNIX socket `-S /tmp/tidb.sock`, TiDB also returns an error.

While I would like TiDB to match the behavior of MySQL I also think having the same username but with `%` and `localhost` as hosts isn't something I would recommend.

**Comment by dveeden** [comment]
Changing the behavior isn't difficult btw.
```patch
diff --git a/server/conn.go b/server/conn.go
index 0277bd40a..877a47ea4 100644
--- a/server/conn.go
+++ b/server/conn.go
@@ -899,7 +899,11 @@ func (cc *clientConn) PeerHost(hasPassword string) (host, port string, err error
                err = errAccessDenied.GenWithStackByArgs(cc.user, addr, hasPassword)
                return
        }
-       cc.peerHost = host
+       if host == "127.0.0.1" {
+               cc.peerHost = "localhost"
+       } else {
+               cc.peerHost = host
+       }
        cc.peerPort = port
        return
 }
```

**Comment by morgo** [comment]
There is some special handling in session/session.go already. It might not be working correctly, so we will have to reconcile the two together:

https://github.com/pingcap/tidb/blob/71e64bf05e8ddd8720383e954aba8817441775d7/session/session.go#L2289-L2292

**Comment by dveeden** [comment]
@morgo I tried and `getHostByIP` is not getting called.

The `Auth()` function returns before it calls `getHostByIP` either if `user.Hostname == variable.DefHostname` or when `success`.

**Comment by zhaopei05** [comment]
> 
Thanks Mattias. '127.0.0.1' is just an example. Try replacing it with a remote IP in the case by logging in from a remote client, it will behave the same.

**Comment by zhaopei05** [comment]
> 
Thanks @mjonss . '127.0.0.1' is just an example. Try replacing it with a remote IP in the case by logging in from a remote client, it will behave the same.

**Comment by zhaopei05** [comment]
> MySQL maps '127.0.0.1' to 'localhost', which makes it hard to distinguish between using unix socket and tcp from+to loopback interface ipv4 127.0.0.1 TiDB does not currently map in between, so localhost is matching unix socket and 127.0.0.1 is matching ipv4 loopback network interface.
> 
> If the test would be extended with: `create user 'test'@'127.0.0.1' identified by '127.0.0.1'` it would show the difference between MySQL and TiDB more clearly (also notice on how to connect, through unix socket or tcp/ipv4)

Thanks @mjonss. It behaves the same with '127.0.0.1'. But by using a remote IP, it will be different, which is the same as MySQL.

**Comment by mjonss** [comment]
@dveeden @morgo 
Do you think we should change the behaviour of TiDB to fully support the mapping of '127.0.0.1' hostname to 'localhost' when it comes to authentication?

I just tested 8.0.27 with both 'localhost'@'localhost' and 'localhost'@'127.0.0.1' and it is a bit confusing for tcp loopback interface (127.0.0.1)
```
# Using tcp ipv4 over loop back interface 127.0.0.1
$ mysql -u localhost -p -h 127.0.0.1 -P 3306 --comments --database test --prompt="mysql> " -v
Enter password: <not password for 'localhost'@'127.0.0.1'>
ERROR 1045 (28000): Access denied for user 'localhost'@'localhost' (using password: YES)
# ^^ Here it returns the wrong user!

$ mysql -u localhost -p -h 127.0.0.1 -P 3306 --comments --database nonexistingdb --prompt="mysql> " -v
Enter password: <password for 'localhost'@'127.0.0.1'>
ERROR 1044 (42000): Access denied for user 'localhost'@'127.0.0.1' to database 'nonexistingdb'
# ^^ Here it returns the right user and that it does not have access to the nonexistingdb

$ mysql -u localhost -p -h 127.0.0.1 -P 3306 --comments --database test --prompt="mysql> " -v
Enter password: <password for 'localhost'@'127.0.0.1'>

mysql> select user();
+---------------------+
| user()              |
+---------------------+
| localhost@localhost |
+---------------------+
1 row in set (0,00 sec)

mysql> show grants;
+-------------------------------------------------------+
| Grants for localhost@127.0.0.1                        |
+-------------------------------------------------------+
| GRANT USAGE ON *.* TO `localhost`@`127.0.0.1`         |
| GRANT SELECT ON `test`.* TO `localhost`@`127.0.0.1` |
+-------------------------------------------------------+
2 rows in set (0,00 sec)

# Using Unix Socket
$ mysql -u localhost -p --comments test --prompt="mysql> " -v
Enter password: <not password for 'localhost'@'localhost'
ERROR 1045 (28000): Access denied for user 'localhost'@'localhost' (using password: YES)
$ mysql -u localhost -p --comments test --prompt="mysql> " -v
Enter password: <password for 'localhost'@'localhost'

mysql> select user();
+---------------------+
| user()              |
+---------------------+
| localhost@localhost |
+---------------------+
1 row in set (0,00 sec)

mysql> show grants;
+-------------------------------------------------------+
| Grants for localhost@localhost                        |
+-------------------------------------------------------+
| GRANT USAGE ON *.* TO `localhost`@`localhost`         |
| GRANT SELECT ON `test`.* TO `localhost`@`localhost` |
+-------------------------------------------------------+
2 rows in set (0,00 sec)

# Then if I drop the 'localhost'@'127.0.0.1' user it will map 'localhost'@'localhost'
$ mysql -u localhost -p -h 127.0.0.1 -P 3306 --comments --database test --prompt="mysql> " -v
Enter password: <password for 'localhost'@'127.0.0.1'>
ERROR 1045 (28000): Access denied for user 'localhost'@'localhost' (using password: YES)
$ mysql -u localhost -p -h 127.0.0.1 -P 3306 --comments --database test --prompt="mysql> " -v
Enter password: <password for 'localhost'@'localhost'>

mysql> select user();
+---------------------+
| user()              |
+---------------------+
| localhost@localhost |
+---------------------+
1 row in set (0,00 sec)

mysql> show grants;
+-------------------------------------------------------+
| Grants for localhost@localhost                        |
+-------------------------------------------------------+
| GRANT USAGE ON *.* TO `localhost`@`localhost`         |
| GRANT SELECT ON `test`.* TO `localhost`@`localhost` |
+-------------------------------------------------------+
2 rows in set (0,00 sec)

# Dropping the 'localhost'@'localhost' and adding 'localhost'@'127.0.0.1' and 'localhost'@'%'
# And logging in with unix socket
$ mysql -u localhost -p --comments test --prompt="mysql> " -v
Enter password: 
ERROR 1045 (28000): Access denied for user 'localhost'@'localhost' (using password: YES)
$ mysql -u localhost -p --comments test --prompt="mysql> " -v
Enter password: 

mysql> select user();
+---------------------+
| user()              |
+---------------------+
| localhost@localhost |
+---------------------+
1 row in set (0,00 sec)

mysql> show grants;
+-----------------------------------------------+
| Grants for localhost@%                        |
+-----------------------------------------------+
| GRANT USAGE ON *.* TO `localhost`@`%`         |
| GRANT SELECT ON `test`.* TO `localhost`@`%` |
+-----------------------------------------------+
2 rows in set (0,00 sec)

```

If we are changing the behaviour to also map 127.0.0.1 to localhost, how should we handle the case when there already exists an account with 'localhost' hostname?
If there are no account with the same user and '127.0.0.1' host name combination it will suddenly also allow logins from loopback interface (which could be a proxy?!)
And if there are two accounts with the same user and both 'localhost' and '127.0.0.1' as host, dropping access to the 127.0.0.1 user would still allow it to login (possibly with a different password/credential).

```
Accounts for hosts		| Unix Domain Socket connection	| TCP loop back connection (127.0.0.1)
Only localhost			| localhost			| localhost New access in TiDB!
Only 127.0.0.1			| 127.0.0.1 New access in TiDB!	| 127.0.0.1
Both localhost & 127.0.0.1	| localhost			| 127.0.0.1
Only '%'			| %				| %
```

**Comment by dveeden** [comment]
@mjonss Yes, I think the TiDB behavior should match the behavior from MySQL 8.0 more closely

**Comment by morgo** [comment]
> @mjonss Yes, I think the TiDB behavior should match the behavior from MySQL 8.0 more closely

Yes I agree too. I don't think it will be that useful, but the MySQL semantics are hard enough to describe. Creating entirely new semantics is problematic to decide on and explain to users.

**Comment by mjonss** [comment]
For reference, this is the only part I found about MySQL mapping loopback interface to 'localhost'
https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_skip_name_resolve
