### ISSUE TITLE
About the speed of SQL with join.

### ISSUE THREAD

**Issue by cdmikechen** [pingcap/tidb#3000]
目前有两张表，一张叫DJ_NSRXX，数量在1475200；一张叫SB_SPXX_RK，数量在3952499。
其中，DJ_NSRXX的NSRDZDAH为主键并加了索引，SB_SPXX_RK的RKRQ和NSRDZDAH都加了索引，并同时构建了一个RKRQ,NSRDZDAH的联合索引，并设置了NSRDZDAH的外键。
我将两张表做关联查询，搜索在一天范围内的信息数量并做关联查询，日期暂定为2015-2-8，具体以SB_SPXX_RK表作为基准表，数量在4508条。
SELECT * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d');
发现最后的结果需要20S才能出来，具体的执行计划如下：

mysql> explain SELECT * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d');
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
| ID               | Json

                                                                      | ParentID         |
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
| IndexScan_11     | {
    "db": "nbds",
    "table": "SB_SPXX_RK",
    "index": "idx_sb_spxx_rk_RKRQ",
    "ranges": "[[2015-02-08,2015-02-08]]",
    "desc": false,
    "out of order": true,
    "double read": true,
    "push down info": {
        "limit": 0,
        "access conditions": [
            "eq(rk.rkrq, 2015-02-08)"
        ],
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashRightJoin_21 |
| TableScan_20     | {
    "db": "nbds",
    "table": "DJ_NSRXX",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}
                                  | HashRightJoin_21 |
| HashRightJoin_21 | {
    "eqCond": [
        "eq(rk.nsrdzdah, nsr.nsrdzdah)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "IndexScan_11",
    "rightPlan": "TableScan_20"
}
                                                                                            |                  |
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
3 rows in set (0.00 sec)

请问此种情况我改如何调整SQL可以加快查询速度？

**Comment by shenli** [comment]
@cdmikechen May I have your tidb-server's version? You can get it by running `tidb-server -V`. I think in this scenario, you can use IndexLookupJoin operator which is supported in the latest version.

**Comment by cdmikechen** [comment]
@shenli 
./bin/tidb-server -V
Git Commit Hash: 9cb61b047d825f47ba5e9999de7b1e6e7f9592a7
UTC Build Time:  2017-03-31 01:40:47

http://hadoop2:10080/status
{"connections":2,"version":"5.7.1-TiDB-1.0","git_hash":"9cb61b047d825f47ba5e9999de7b1e6e7f9592a7"}

**Comment by winoros** [comment]
You can try this sql `SELECT /*+ TIDB_INLJ(RK) */ * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d');`
And please upload the explain result of this sql.

**Comment by cdmikechen** [comment]
mysql> explain SELECT /*+ TIDB_INLJ(RK) */ * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d');
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
| ID               | Json


                                                                      | ParentID         |
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
| IndexScan_11     | {
    "db": "nbds",
    "table": "SB_SPXX_RK",
    "index": "idx_sb_spxx_rk_RKRQ",
    "ranges": "[[2015-02-08,2015-02-08]]",
    "desc": false,
    "out of order": true,
    "double read": true,
    "push down info": {
        "limit": 0,
        "access conditions": [
            "eq(rk.rkrq, 2015-02-08)"
        ],
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashRightJoin_21 |
| TableScan_20     | {
    "db": "nbds",
    "table": "DJ_NSRXX",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}
                                  | HashRightJoin_21 |
| HashRightJoin_21 | {
    "eqCond": [
        "eq(rk.nsrdzdah, nsr.nsrdzdah)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "IndexScan_11",
    "rightPlan": "TableScan_20"
}
                                                                                            |                  |
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
3 rows in set (0.00 sec)

@winoros 
我目前数据库的数据大概是今年年初时候的基础数据，原来的版本也是年初大概RC1的版本，当时只是简单的做了下数据测试并没有做更深入的数据验证。最近只是替换了最新的包，但是数据相关的文件并没有动过。是否这个和本身数据库的数据文件有关系，是不是我需要重新创建表单导入一次数据？

**Comment by shenli** [comment]
@cdmikechen It seems that your mysql client drop the `TIDB_INLJ` hint. Which version of mysql-client do you use?

**Comment by cdmikechen** [comment]
mysql> status
--------------
mysql  Ver 14.14 Distrib 5.6.24, for Win32 (x86)

Connection id:          7
Current database:       mysql
Current user:           nbtais@144.24.155.114
SSL:                    Not in use
Using delimiter:        ;
Server version:         5.7.1-TiDB-1.0 MySQL Community Server (GPL)
Protocol version:       10
Connection:             144.24.155.115 via TCP/IP
Server characterset:    latin1
Db     characterset:    utf8
Client characterset:    latin1
Conn.  characterset:    latin1
TCP port:               4000
--------------

@shenli 
目前主要使用MySQLWorkbench 6.3.8 做数据测试，平台为win7。TIDB分在linux的4个节点上，PD和SERVER在一个（4CORE, 16G RAM, SATA），另外的3个KV分别在其他节点上（4CORE，8G RAM, SATA）。MySQL情况如上。

**Comment by shenli** [comment]
Please find the sql statement in tidb-server's logfile. You can use `grep "TIME_QUERY" name-of-tidb-log-file`. I doubt that the hint is dropped by client.

**Comment by cdmikechen** [comment]
@shenli 
使用workbench执行一次查询的执行情况如下：

2017/04/06 18:02:09 coprocessor.go:315: [info] [TIME_COP_TASK] 767.833117ms region(4197 5 251) ranges(10) store(144.24.155.126:20160)
2017/04/06 18:02:12 distsql.go:529: [info] [1] [TIME_INDEX_DOUBLE] time: 3.677202588s, table: SB_SPXX_RK(294), index: idx_sb_spxx_rk_RKRQ(1), partials: 1, concurrency: 0, rows: 4509, handles: 4508
2017/04/06 18:02:15 coprocessor.go:315: [info] [TIME_COP_TASK] 6.568872295s region(1813 5 193) ranges(1) store(144.24.155.111:20160)
2017/04/06 18:02:17 coprocessor.go:315: [info] [TIME_COP_TASK] 8.741429235s region(1805 5 192) ranges(1) store(144.24.155.126:20160)
2017/04/06 18:02:20 coprocessor.go:315: [info] [TIME_COP_TASK] 11.704699871s region(1837 5 198) ranges(1) store(144.24.155.111:20160)
2017/04/06 18:02:31 coprocessor.go:315: [info] [TIME_COP_TASK] 22.528313863s region(1833 5 197) ranges(1) store(144.24.155.111:20160)
2017/04/06 18:02:31 coprocessor.go:315: [info] [TIME_COP_TASK] 22.719192538s region(1801 5 193) ranges(1) store(144.24.155.111:20160)
2017/04/06 18:02:32 session.go:553: [warning] [2] compile error:
[schema:1146]Table 'performance_schema.threads' doesn't exist
SELECT st.* FROM performance_schema.events_statements_current st JOIN performance_schema.threads thr ON thr.thread_id = st.thread_id WHERE thr.processlist_id = 1
2017/04/06 18:02:32 conn.go:367: [warning] [2] dispatch error:
id:2, addr:144.24.155.114:53402 status:2, collation:utf8_general_ci, user:nbtais
SELECT st.* FROM performance_schema.events_statements_current st JOIN performance_schema.threads thr ON thr.thread_id = st.thread_id WHERE thr.processlist_id = 1
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/infoschema/infoschema.go:172: [schema:1146]Table 'performance_schema.threads' doesn't exist
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/resolver.go:367: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/resolver.go:35: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/preprocess.go:26: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/compiler.go:35: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/tidb.go:168: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:555: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:674: 
2017/04/06 18:02:32 session.go:553: [warning] [2] compile error:
[schema:1146]Table 'performance_schema.events_waits_history_long' doesn't exist
SELECT st.* FROM performance_schema.events_waits_history_long st WHERE st.nesting_event_id = 0
2017/04/06 18:02:32 conn.go:367: [warning] [2] dispatch error:
id:2, addr:144.24.155.114:53402 status:2, collation:utf8_general_ci, user:nbtais
SELECT st.* FROM performance_schema.events_waits_history_long st WHERE st.nesting_event_id = 0
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/infoschema/infoschema.go:172: [schema:1146]Table 'performance_schema.events_waits_history_long' doesn't exist
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/resolver.go:367: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/resolver.go:35: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/plan/preprocess.go:26: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/executor/compiler.go:35: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/tidb.go:168: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:555: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:674: 
2017/04/06 18:02:36 coprocessor.go:315: [info] [TIME_COP_TASK] 27.142422265s region(1817 5 195) ranges(1) store(144.24.155.126:20160)
2017/04/06 18:02:37 coprocessor.go:315: [info] [TIME_COP_TASK] 29.052327737s region(1797 5 192) ranges(1) store(144.24.155.126:20160)
2017/04/06 18:02:38 coprocessor.go:315: [info] [TIME_COP_TASK] 29.145959454s region(1809 5 194) ranges(1) store(144.24.155.126:20160)
2017/04/06 18:02:38 coprocessor.go:315: [info] [TIME_COP_TASK] 29.819103941s region(1825 5 196) ranges(1) store(144.24.155.126:20160)
2017/04/06 18:02:38 adapter.go:195: [warning] [1][TIME_QUERY] 29.819635405s SELECT * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.rkrq = date_format('2015-02-08', '%Y-%m-%d') and RK.nsrdzdah=NSR.nsrdzdah
LIMIT 0, 100

**Comment by coocood** [comment]
@cdmikechen 
MySQL client older than 5.7.7 strips comment by default, to keep comments, you can invode mysql client with `--comments`

**Comment by ngaut** [comment]
Could you also add to documents? @coocood

**Comment by coocood** [comment]
@ngaut 
Sure

**Comment by cdmikechen** [comment]
@coocood 
已经升级为5.7.17，但是执行计划发现原始SQL无变化，添加注解后提示错误。

mysql> status
--------------
mysql  Ver 14.14 Distrib 5.7.17, for Win64 (x86_64)

Connection id:          3
Current database:       nbds
Current user:           nbtais@144.24.155.114
SSL:                    Not in use
Using delimiter:        ;
Server version:         5.7.1-TiDB-1.0 MySQL Community Server (GPL)
Protocol version:       10
Connection:             144.24.155.115 via TCP/IP
Server characterset:    latin1
Db     characterset:    utf8
Client characterset:    latin1
Conn.  characterset:    latin1
TCP port:               4000
--------------

mysql> explain SELECT * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.rkrq = date_format('2015-02-08', '%Y-%m-%d') and RK.n
srdzdah=NSR.nsrdzdah ;
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
| ID               | Json


                                                                      | ParentID         |
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
| IndexScan_11     | {
    "db": "nbds",
    "table": "SB_SPXX_RK",
    "index": "idx_sb_spxx_rk_RKRQ",
    "ranges": "[[2015-02-08,2015-02-08]]",
    "desc": false,
    "out of order": true,
    "double read": true,
    "push down info": {
        "limit": 0,
        "access conditions": [
            "eq(rk.rkrq, 2015-02-08)"
        ],
        "index filter conditions": null,
        "table filter conditions": null
    }
} | HashRightJoin_21 |
| TableScan_20     | {
    "db": "nbds",
    "table": "DJ_NSRXX",
    "desc": false,
    "keep order": false,
    "push down info": {
        "limit": 0,
        "access conditions": null,
        "index filter conditions": null,
        "table filter conditions": null
    }
}
                                  | HashRightJoin_21 |
| HashRightJoin_21 | {
    "eqCond": [
        "eq(rk.nsrdzdah, nsr.nsrdzdah)"
    ],
    "leftCond": null,
    "rightCond": null,
    "otherCond": null,
    "leftPlan": "IndexScan_11",
    "rightPlan": "TableScan_20"
}
                                                                                            |                  |
+------------------+----------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------------------------------------
----------------------------------------------------------------------+------------------+
3 rows in set (0.00 sec)

mysql> explain SELECT /*+ TIDB_INLJ(RK) */ * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkr
q = date_format('2015-02-08', '%Y-%m-%d');
ERROR 1105 (HY000): line 0 column 35 near " * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rk
rq = date_format('2015-02-08', '%!Y(MISSING)-%!m(MISSING)-%!d(MISSING)')" (total length 154)
mysql>

后台错误信息：
2017/04/07 11:24:07 conn.go:367: [warning] [3] dispatch error:
id:3, addr:144.24.155.114:49312 status:2, collation:gbk_chinese_ci, user:nbtais

ERROR 1105 (HY000): command 9 not supported now
2017/04/07 11:24:24 session.go:539: [warning] [3] parse error:
line 0 column 35 near " * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d')" (total length 154)
explain SELECT /*+ TIDB_INLJ(RK) */ * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d')
2017/04/07 11:24:24 conn.go:367: [warning] [3] dispatch error:
id:3, addr:144.24.155.114:49312 status:2, collation:gbk_chinese_ci, user:nbtais
explain SELECT /*+ TIDB_INLJ(RK) */ * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d')
line 0 column 35 near " * FROM SB_SPXX_RK RK , DJ_NSRXX NSR WHERE RK.nsrdzdah=NSR.nsrdzdah AND RK.rkrq = date_format('2015-02-08', '%Y-%m-%d')" (total length 154)
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/parser/yy_parser.go:96: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/session.go:540: 
/home/jenkins/workspace/TIDB_POST_COMMIT_FLOW/go/src/github.com/pingcap/tidb/server/conn.go:674:

**Comment by winoros** [comment]
@cdmikechen Oh, this hint hasn't been merged into master at 3.31. You can try current master version.
Sorry for your inconvenience.

**Comment by c4pt0r** [comment]
@cdmikechen Please use English :)

**Comment by cdmikechen** [comment]
@winoros  have been solved, thanks.

**Comment by shenli** [comment]
@cdmikechen Great!
How long it takes when you use index lookup join operator?

**Comment by cdmikechen** [comment]
@shenli 
29-30S before, 0.5-0.6s by using `TIDB_INLJ` now.

**Comment by shenli** [comment]
@cdmikechen Glad to hear that!
