### ISSUE TITLE
SQL syntax error fails to be checked

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#30075]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t1 (id int, name char(10));
insert into t1 (id, name) values(1, 'aaa');
insert into t1 (id, name) values(2, 'bbb');
insert into t1 (id, name) values(3, 'ccc');
insert into t1 (id, name) values(4, 'ccc');
select id from t1 where name='ccc' order by id and id>=4;
```

### 2. What did you expect to see? (Required)
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 48 near "and id>=4"`

### 3. What did you see instead (Required)
```
test@v5.3.0>select id from t1 where name='ccc' order by id and id>=4;
+------+
| id   |
+------+
|    3 |
|    4 |
+------+
2 rows in set (0.01 sec)
```
### 4. What is your TiDB version? (Required)

```
Release Version: v5.3.0
Edition: Community
Git Commit Hash: 79e237d9d336e78f1933e38940f2e1703e383b1f
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-18 13:09:27
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false 
```

**Comment by hawkingrei** [comment]
I have tested this SQL in the master branch. It cannot be reproduced. It is fixed on the master branch. So i close this issue.

**Comment by Yui-Song** [comment]
I can reproduced it with the follwing version. But we can reproduced it with MySQL 8.0.26, too.

```
 Release Version: v5.4.0-alpha-217-gf45a8f051
Edition: Community
Git Commit Hash: f45a8f0511156855d2c109d216acdd1f900abe20
Git Branch: master
UTC Build Time: 2021-11-24 06:53:45
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

![image](https://user-images.githubusercontent.com/84501897/143195551-ffd1fa97-91ae-4956-886e-505b7e8f2abb.png)

**Comment by hawkingrei** [comment]
Sorry, I cannot reproduce the bug. Mysql 8.0.26 and 5.7.25-TiDB-v5.4.0-alpha-216-g481455728 report the same result. 

BTW, if add ```desc``` after ```order by id``` , both of them will report error.

**Comment by hawkingrei** [comment]
I have test this case in the ```79e237d9d336e78f1933e38940f2e1703e383b1f```. it is indeed bug. but it is fixed in the master.

**Comment by Yui-Song** [comment]
I have reported this bug to MySQL. https://bugs.mysql.com/bug.php?id=105699

**Comment by kennytm** [comment]
why is this considered an error in the first place? `id and id >= 4` is a perfectly valid expression.

**Comment by Yui-Song** [comment]
> why is this considered an error in the first place? `id and id >= 4` is a perfectly valid expression.

Because the predication `and id >= 4` is after the ORDER BY expression and SQL parser just ignore it and return the result of `select id from t1 where name='ccc' order by id`.
However, what I want is the result of `select id from t1 where name='ccc' and id >= 4 order by id ;`

**Comment by Yui-Song** [comment]
> why is this considered an error in the first place? `id and id >= 4` is a perfectly valid expression.

 And if add `desc ` after `order by id`, it will report error.
```
mysql>select id from t1 where name='ccc' order by id desc and id>=4;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'and id>=4' at line 1

```

**Comment by bb7133** [comment]
Personally, I don't think it's a major bug, because the syntax is barely used. And if we try to solve it, it would be potentially a compatibility breaker.

**Comment by Yui-Song** [comment]
MySQL has a special feature that apply to simple expressions used as predicates in conditions (such as in the WHERE clause). The condition

 ` where id and id >= 4`

is rewritten internally as

 ` where id <> 0 and id >= -4`

When you write a query like this one:

`select id from t1 where name='ccc' order by id and id>=4;`

That means that you are ordering the query by the Boolean result. That means that you will get 1 whenever the id is not equal to 0 AND id is greater or equal to 4. Hence, sorting will be done only by TRUE (1) or FALSE (0) and not by values of the column `id`.

AND is a keyword that produces a Boolean result, so sorting is done by one criteria only.


Therefore, 
`select id from t1 where name='ccc' order by id and id>=4;` 
is rewritten internally as 
 `select id from t1 where name='ccc' order by ( id <> 0 and id>=4);`
```

+------+
| id   |
+------+
|    3 |  => TRUE AND FALSE => 0
|    4 |  => TRUE AND TRUE => 1
+------+
```

```

create table t1 (id int, name char(10));
insert into t1 (id, name) values(1, 'aaa');
insert into t1 (id, name) values(2, 'bbb');
insert into t1 (id, name) values(3, 'ccc');
insert into t1 (id, name) values(4, 'ccc');
insert into t1 (id, name) values(5, 'ccc');
insert into t1 (id, name) values(-1,'ccc');
insert into t1 (id, name) values(0,'ccc'); 
mysql> select id from t1 where name='ccc' order by id and id>=-1;
+------+
| id   |
+------+
|    0 | =>  FALSE AND TRUE => 0
|    3 | => TRUE AND FALSE => 0
|    4 | => TRUE AND TRUE => 1
|    5 |  => TRUE AND TRUE => 1
|   -1 |  => TRUE AND TRUE => 1
+------+
5 rows in set (0.00 sec)
```
 The sorting will be done only by TRUE (1) or FALSE (0) and not by values of the column `id`.
 
It‘s a MySQL feature, not a bug.

**Comment by Yui-Song** [comment]
For more details, please refer to https://bugs.mysql.com/bug.php?id=105699
