### ISSUE TITLE
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error

### ISSUE THREAD

**Issue by luyee** [pingcap/tidb#301]
when  use mysql client connect to a tidb server  ,this happen and result  tidb server exit

**Comment by siddontang** [comment]
Hi @luyee 

Can you tell us what is the command you use with mysql client? Do you forget -u or -P ?

**Comment by shenli** [comment]
@luyee May I have your tidb-server git version and error log? 
Thanks!

**Comment by luyee** [comment]
thx  @siddontang changed cmd( mysql -h 127.0.0.1 -P 4000 -u root -D test ) to -p 4000 is ok

**Comment by siddontang** [comment]
no, no, use `mysql -h 127.0.0.1 -P 4000 -u root -p` please

**Comment by elvizlai** [comment]
➜  ~ mysql -h 127.0.0.1 -P 4000 -u root -D test
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0 "Internal error/check (Not system error)"


All I do is stop pd leader. After campaign, this happened.
Restart tidb, this can solve. But NOT automatic.

@ngaut @siddontang maybe re-open this issue.

**Comment by shenli** [comment]
@elvizlai Thanks for your report! I will check this.
