### ISSUE TITLE
The formula of calculating net cost for TiFlash plans is not aligned with TiKV plans'

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#30103]
## Enhancement
In `copTask.convertToRootTaskImpl`, we can see the formula of calculating net cost for TiKV plans is `est-row * row-size * net-factor`, while in `mppTask.convertToRootTaskImpl` the formula for TiFlash plans is `est-row * net-factor` where the `row-size` is lost.
That would let the cost of TiFlash plans be always relatively lower than TiKV plans', which can cause some wrong plans.

**Comment by zhangjinpeng1987** [comment]
It should be a bug? @qw4990

**Comment by qw4990** [comment]
> It should be a bug? @qw4990

Yep, we can regard this issue as a bug also, but it may not be appropriate.
To fix it, we have to design some experiments and test cases to evaluate the new formula to ensure there is no regression, which is what we are doing in Sprint6. 
It seems that we cannot fix it like a bug quickly, so I just labeled it with `enhancement` and planned to solve it in Sprint6 by the project Cardinality&Cost Enhancement.

**Comment by yudongusa** [comment]
This is part of cost model enhancement planned in Sprint 6 in which this and other related costing enhancement and issues will be examined and improved.
