### ISSUE TITLE
br s3 endpoint can't end with '/'

### ISSUE THREAD

**Issue by cyliu0** [pingcap/tidb#30104]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

This bug is a little bit frustrating. 

### 1. Minimal reproduce step (Required)

```
AWS_ACCESS_KEY_ID=xxxx AWS_SECRET_ACCESS_KEY=xxxxx tiup br backup full --s3.endpoint http://minio.pingcap.net:9000/ -s s3://tmp/sysbenc-empty-cy
```

### 2. What did you expect to see? (Required)
br backup successfully

### 3. What did you see instead (Required)
br backup failed
```
Error: error happen in store 1 at 127.0.0.1:20160: Io(Custom { kind: Other, error: "failed to put object Request ID: None Body: <?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>BadRequest</Code><Message>An error occurred when parsing the HTTP request PUT at &#39;/
/tmp/sysbenc-empty-cy/1_2_28_2550d727ffe3e408af41f541b134d5e064440c25988bbecfb665933d1195a45d_1637743793014_write.sst&#39;</Message><Resource>//tmp/sysbenc-empty-cy/1_2_28_2550d727ffe3e408af41f541b134d5e064440c25988bbecfb665933d1195a45d_1637743793014_write.sst</Resource><
RequestId></RequestId><HostId>bf48f99f-3f89-4a20-bd11-95d1658fa9c8</HostId></Error>" }): [BR:KV:ErrKVStorage]tikv storage occur I/O error
Error: run `/root/.tiup/components/br/v5.3.0/br` (wd:/root/.tiup/data/Spfa3FJ) failed: exit status 1
```

### 4. What is your TiDB version? (Required)

**5.3.0**

**Comment by 3pointer** [comment]
duplicated https://github.com/pingcap/br/issues/992

**Comment by fengou1** [comment]
S3 endpoint w/o slash works:
![GJXNkBwlaJ](https://user-images.githubusercontent.com/85682690/143402213-d963a309-6106-4c68-86da-f2257a981eee.png)

minio endpoint w/o slash works:
![middle_img_v2_92e165a6-4a16-48b4-9434-43830ef78b3g](https://user-images.githubusercontent.com/85682690/143402373-3ed15b19-edad-472d-b33e-d340ae10a122.png)

**Comment by fengou1** [comment]
According to definition of[ AWS endpoint](https://docs.aws.amazon.com/general/latest/gr/rande.html).

endpoint shall be a URL, and URL be w/o slash shall be valid.
