### ISSUE TITLE
IT Unstable case mysqltest `key`

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#30136]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7527/pipeline/86
```bash
run test [key] err: sql:select table_name, index_type from information_schema.statistics
where table_schema = 'test' and table_name like 't%' order by table_name;: failed to run query
"select table_name, index_type from information_schema.statistics
where table_schema = 'test' and table_name like 't%' order by table_name;"
 around line 167,
we need(215):
select table_name, index_type from information_schema.statistics
where table_schema = 'test' and table_name like 't%' order by table_name;
table_name      index_type
#
# Same applies when keys are added by ALTER TABLE
#

but got(215):
select table_name, index_type from information_schema.statistics
where table_schema = 'test' and table_name like 't%' order by table_name;
table_name      index_type
t2      BTREE
t2      BTREE
t2      BTREE
t2      BTREE
t2      BTREE
t2      BTREE
```

**Comment by qw4990** [comment]
This is a new test case introduced by https://github.com/pingcap/tidb-test/pull/1312.

**Comment by qw4990** [comment]
This issue is in [mysql_test/key](https://github.com/pingcap/tidb-test/blob/master/mysql_test/r/key.result), and it can be simplified as below:
```
CREATE TABLE t2 (
a INTEGER auto_increment PRIMARY KEY,
...
);
INSERT INTO t2 VALUES
...
(NULL, 8, 1, '2004-11-30 12:00:00', 105, 10, 0, 0, 0, 0);

...

DROP TABLE t1, t2;

...

select table_name, index_type from information_schema.statistics
where table_schema = 'test' and table_name like 't%' order by table_name;
```

It is expected that the last `select` cannot read any data related to `t2` since it has already been dropped before, but in this case some data about `t2` is returned.

This issue is related to DDL instead of the optimizer, and the table `information_schema.statistics` is for meta-info of tables instead of statistics for the optimizer, so I think it's better to let the SQL-infra Team investigate and resolve this issue.
So PTAL @bb7133 @morgo , if there is anything I can help with, please let me know.

**Comment by morgo** [comment]
Sure, I can fix. I agree it's a bug; the statistics for old tables should not be shown.

**Comment by morgo** [comment]
This is a harder fix than I thought, and other i_s tables might have the same problem :(

I assumed that the issue might be a `range` on the internal statistics table, but it is not. It is infact already ranging on the list of tables correctly:

```
func (e *memtableRetriever) setDataForStatistics(ctx sessionctx.Context, schemas []*model.DBInfo) {
	checker := privilege.GetPrivilegeManager(ctx)
	for _, schema := range schemas {
		for _, table := range schema.Tables {
			if checker != nil && !checker.RequestVerification(ctx.GetSessionVars().ActiveRoles, schema.Name.L, table.Name.L, "", mysql.AllPrivMask) {
				continue
			}
			e.setDataForStatisticsInTable(schema, table)
		}
	}
}
```

**Comment by bb7133** [comment]
@morgo Do you have any better idea on this? I don't think it's a major issue, but it makes the test unstable. Now I'm going to make it an 'enhancement' since the test case `key` has been removed from merge CI temporarily.

**Comment by morgo** [comment]
This has been fixed
