### ISSUE TITLE
Conflict transaction do not wait lock as expect

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#30141]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(k int primary key, v int)；
insert into t values (1, 1)；

s2: begin optimistic；
s1: begin pessimistic；
s1: update t set v = v + 1 where k = 1；
s2: update t set v = v + 1 where k = 1；
s2: commit ---check
```

### 2. What did you expect to see? (Required)

`wait s1 lock;`

### 3. What did you see instead (Required)

```
mysql> commit;
ERROR 9007 (HY000): Write conflict, txnStartTS=429342959393570817, conflictStartTS=429342960350396417, conflictCommitTS=0, key={tableID=57, handle=1} primary=[]byte(nil) [try again later]
```

### 4. What is your TiDB version? (Required)

```
only in master:
Release Version: v5.4.0-alpha-223-ge65f548a4
Edition: Community
Git Commit Hash: e65f548a40acedd51caa67bed9ee44f51baf852e
Git Branch: master
UTC Build Time: 2021-11-24 11:56:59
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by vivid392845427** [comment]
behavioral changes because of https://github.com/pingcap/tidb/issues/30141，close this issue

**Comment by cfzjywxk** [comment]
@vivid392845427 
After disscussion the behaviour change is regarded as an optimization and it's expected, we could close this issue and add an task to change the expected behaviour in test case.

**Comment by sticnarf** [comment]
I think the new behavior is mostly better.

In most cases, pessimistic locks will be finally committed. So, it will be wasting time for the optimistic transaction to wait for a pessimistic transaction whose timestamp is larger than itself.

**Comment by tiancaiamao** [comment]
> In most cases, pessimistic locks will be finally committed. 

The user send "rollback" manually, or the query is killed, or the pessimistic lock conflict with the other pessimistic txn, or dead lock etc ... although I can list many, all those are rare cases
