### ISSUE TITLE
dumpling: dump failed when a sequence created

### ISSUE THREAD

**Issue by sylzd** [pingcap/tidb#30149]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
tidb> use test;
tidb> create sequence seq;

./dumpling -h host -u test_user -p test_password -P 4000 --filetype sql --threads 32 -o .

```

return dump failed. Since many people do not know what seq is, and error info is `Error 1051: Unknown table ''`, it will make them confused and worried.

### 2. What did you expect to see? (Required)
dump successfully.

### 3. What did you see instead (Required)

```
dump failed: sql: SELECT * FROM `test`.`seq` LIMIT 1: Error 1051: Unknown table ''
```

### 4. What is your TiDB version? (Required)
master

**Comment by sylzd** [comment]
`show table status`(the default show table method) cannot distinguish `sequence` from `base table`
![image](https://user-images.githubusercontent.com/10683568/143437855-67c86b31-3abc-4b64-aa36-3a91fe11da28.png)


related code:


```
func prepareTableListToDump(tctx *tcontext.Context, conf *Config, db *sql.Conn) error {
	databases, err := prepareDumpingDatabases(tctx, conf, db)
	if err != nil {
		return err
	}

	tableTypes := []TableType{TableTypeBase}
	if !conf.NoViews {
		tableTypes = append(tableTypes, TableTypeView)
	}
	conf.Tables, err = ListAllDatabasesTables(tctx, db, databases, getListTableTypeByConf(conf), tableTypes...)
	if err != nil {
		return err
	}

	filterTables(tctx, conf)
	return nil
}

func getListTableTypeByConf(conf *Config) listTableType {
	// use listTableByShowTableStatus by default because it has better performance
	listType := listTableByShowTableStatus
	if conf.Consistency == consistencyTypeLock {
		// for consistency lock, we need to build the tables to dump as soon as possible
		listType = listTableByInfoSchema
	} else if conf.Consistency == consistencyTypeFlush && matchMysqlBugversion(conf.ServerInfo) {
		// For some buggy versions of mysql, we need a workaround to get a list of table names.
		listType = listTableByShowFullTables
	}
	return listType
}
```

**Comment by sylzd** [comment]
I think support sequence dump is a new feature, but dump failed is still a bug that should be fixed first (it will return error at once and affected other tables dump which makes tables dump incompletely!). the feature pr can replace the unsupported error then. @kennytm @lichunzhu

**Comment by lichunzhu** [comment]
> I think support sequence dump is a new feature, but dump failed is still a bug that should be fixed first (it will return error at once and affected other tables dump which makes tables dump incompletely!).

I agree.
