### ISSUE TITLE
IndexMerge didn't check if pushdown is enabled or not

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#30195]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table t1;
    create table t1(c1 varchar(100), c2 varchar(100), key(c1), key(c2), c3 varchar(100));
    insert into t1 values('ab', '10', '10');
    explain select /*+ use_index_merge(t1) */ * from t1 where c1 = 'ab' or c2 = '10' and substring(c3, 10) = 10;
    select /*+ use_index_merge(t1) */ * from t1 where c1 = 'ab' or c2 = '10' and substring(c3, 10) = 10;
    

### 2. What did you expect to see? (Required)

    mysql> select /*+ use_index_merge(t1) */ * from t1 where c1 = 'ab' or c2 = '10' and substring(c3, 10) = 10;
    +------+------+------+
    | c1   | c2   | c3   |
    +------+------+------+
    | ab   | 10   | 10   |
    +------+------+------+
### 3. What did you see instead (Required)

[components/tidb_query_expr/src/lib.rs:705]: ScalarFunction Substring2ArgsUtf8 is not supported in batch mode
### 4. What is your TiDB version? (Required)
master

**Comment by aytrack** [comment]
duplicated with #30200
