### ISSUE TITLE
ddl pkg  test  have a very strong coupling relationship with other tests in the ddl package

### ISSUE THREAD

**Issue by JayL-zxl** [pingcap/tidb#30194]
for much better migrate test-infra to testify for ddl pkg.
Need to modify the coupling function of the test file.

This makes the task of testing migration easier #27180

**Comment by JayL-zxl** [comment]
it's not a simple task as i view...

**Comment by JayL-zxl** [comment]
Next, I may be busy, and then catch up with the deadline of the paper, so this issue needs someone to complete it.

**Comment by tisonkun** [comment]
Closed as unclear. There is still 4 remaining subtasks for migrating all test under ddl pkg, @JayL-zxl you can take a look.
