### ISSUE TITLE
coprocessor streaming scans duplicated ranges

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#30207]
## Bug Report

Found by [comment](https://github.com/pingcap/tidb/pull/29612#pullrequestreview-816564000).

### 1. Minimal reproduce step (Required)

1. Add a failpoint in coprocessor streaming result handle.

    https://github.com/you06/tidb/blob/446238dbe70d9b98973d592eff789c4b75ad06d9/store/copr/coprocessor.go#L843-L851

2. Enable failpoints, build TiDB and run the playground.

```sh
GO_FAILPOINTS="github.com/pingcap/tidb/store/copr/streamRecvErr=return(true)" tiup playground nightly --monitor=false --tiflash=0 --db.binpath=./tidb-server
```

3. Prepare data with this [script](https://gist.github.com/you06/b941a0adaabfc4a59f0c6c9c3bc5d1d0)

4. Connect to TiDB and run the following SQLs.

```sql
MySQL [test]> set session tidb_enable_streaming = 1;
Query OK, 0 rows affected (0.001 sec)

MySQL [test]> select * from t;
...
```

### 2. What did you expect to see? (Required)

The select SQL returns 1,000 rows.

### 3. What did you see instead (Required)

The select SQL may return more than 1,000 rows.

```sql
MySQL [test]> select * from t;
+-----+------+
| id  | v    |
+-----+------+
|   0 |    0 |
|   1 |    1 |
|   2 |    2 |
...
| 994 |  994 |
| 995 |  995 |
| 996 |  996 |
| 997 |  997 |
| 998 |  998 |
| 999 |  999 |
+-----+------+
1872 rows in set (5.250 sec)
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-227-gdde1e0bf0-dirty
Edition: Community
Git Commit Hash: dde1e0bf0484475f37b3f04f8a865285afbfcbe1
Git Branch: master
UTC Build Time: 2021-11-29 02:59:56
GoVersion: go1.17.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by XuHuaiyu** [comment]
I do not think this is a bug, we deprecate this config in https://github.com/pingcap/tidb/pull/25906.
I'll change the label from `bug` to `enhancement`.

**Comment by you06** [comment]
#29612 made some reconstruction in review, this issue is fixed.
