### ISSUE TITLE
TiDB exited: panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Tammyxia** [pingcap/tidb#30215]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
 
- Deploy cluster through operator
- Run sysbench prepare : "sysbench --db-driver=mysql --mysql-host=upstream-tidb.cdc-testbe
d--tps-510577-1-815 --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=32 --table-size=100000 --time=10800 --debug=true --threads=32 oltp_write_only prepare" 
- Run sysnbench oltp_write_only : "sysbench --db-driver=mysql --mysql-host=upstream-tidb.cdc-testbe
d--tps-510577-1-815 --mysql-port=4000 --mysql-user=root --mysql-db=workload --tables=32 --table-size=100000 --time=10800 --debug=true --threads=32 oltp_write_only run"
- Check command exited: FATAL: mysql_stmt_execute() returned error 2013 (Lost connection to My
SQL server during query)

### 2. What did you expect to see? (Required)

- No error.

### 3. What did you see instead (Required)
 

- TiDB process restarted, then check stderr(kubectl logs -p upstream-tidb-0 -n testbedxxx) that's panic: 

- start tidb-server ...

/tidb-server --store=tikv --advertise-address=upstream-tidb-0.upstream-tidb-peer.cdc-testbed--tps-510577-1-815.svc --host=0.0.0.0 --path=upstream-pd:2379 --config=/etc/tidb/tidb.toml

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x20013b5]

goroutine 17389818 [running]:
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).GetResourceGroupTagByLabel(0xc0046f44e0, 0x2, 0x25, 0x2, 0x1)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/sessionctx/stmtctx/stmtctx.go:306 +0x375
github.com/pingcap/tidb/sessionctx/stmtctx.(*StatementContext).GetResourceGroupTagger.func1(0xc00e08f200)
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/sessionctx/stmtctx/stmtctx.go:290 +0x7d
github.com/tikv/client-go/v2/txnkv/transaction.actionCommit.handleSingleBatch(0x0, 0xc0037a9800, 0xc00eed94d0, 0xb4, 0x5, 0x25, 0x4310388, 0xc00d56e980, 0x1, 0x0, ...)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/txnkv/transaction/commit.go:77 +0x2166
github.com/tikv/client-go/v2/txnkv/transaction.(*batchExecutor).startWorker.func1(0xc008839980, 0xc010a4bd40, 0xb4, 0x5, 0x25, 0x4310388, 0xc00d56e980, 0x1)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/txnkv/transaction/2pc.go:1804 +0x197
created by github.com/tikv/client-go/v2/txnkv/transaction.(*batchExecutor).startWorker
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/txnkv/transaction/2pc.go:1787 +0x19e
### 4. What is your TiDB version? (Required)

```
./tidb-server -V
Release Version: v5.4.0-nightly
Edition: Community
Git Commit Hash: 724da32b122859d94898fbb967e4c44efa5c26ed
Git Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time: 2021-11-29 04:11:37
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
```

**Comment by mornyx** [comment]
Same as https://github.com/pingcap/tidb/issues/30140. Fix PR is merging

**Comment by mornyx** [comment]
Hi @Tammyxia , fix PR has been merged, please re-bench to see if the problem has been resolved, thanks!

**Comment by Tammyxia** [comment]
@mornyx  today 5.4-nightly tidb has not this issue yet, but has new issue: 
start tidb-server ...
/tidb-server --store=tikv --advertise-address=upstream-tidb-0.upstream-tidb-peer.cdc-testbed--tps-510707-1-141.svc --host=0.0.0.0 --path=upstream-pd:2379 --config=/etc/tidb/tidb.toml

panic: runtime error: index out of range [4294967295] with length 2

goroutine 24492959 [running]:
github.com/tikv/client-go/v2/internal/unionstore.(*nodeAllocator).getNode(...)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/internal/unionstore/memdb_arena.go:213
github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).getNode(...)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/internal/unionstore/memdb.go:754
github.com/tikv/client-go/v2/internal/unionstore.memdbNodeAddr.getRight(...)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/internal/unionstore/memdb.go:786
github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).traverse(0xc0175c32b0, 0xc045da3e30, 0x13, 0x13, 0x0, 0x60, 0x7f86257193c8)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/internal/unionstore/memdb.go:375 +0xd51
github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).GetFlags(0xc0175c32b0, 0xc045da3e30, 0x13, 0x13, 0x3bbecc0, 0x42a7f01, 0xc04336f6e0)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/internal/unionstore/memdb.go:223 +0x52
github.com/tikv/client-go/v2/internal/unionstore.(*KVUnionStore).HasPresumeKeyNotExists(0xc0acc30180, 0xc045da3e30, 0x13, 0x13, 0x13)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/internal/unionstore/union_store.go:141 +0x4c
github.com/tikv/client-go/v2/txnkv/transaction.actionPessimisticLock.handleSingleBatch(0xc00581ebe0, 0xc05f786000, 0xc0a1cbbd40, 0x488, 0x5, 0x98, 0x4319f38, 0xc0a6b869c0, 0x0, 0x12fe4c5, ...)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/txnkv/transaction/pessimistic.go:94 +0x1c7
github.com/tikv/client-go/v2/txnkv/transaction.(*batchExecutor).startWorker.func1(0xc0ab1b3740, 0xc0a6b86ae0, 0x488, 0x5, 0x98, 0x4319f38, 0xc0a6b869c0, 0x0)
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/txnkv/transaction/2pc.go:1804 +0x197
created by github.com/tikv/client-go/v2/txnkv/transaction.(*batchExecutor).startWorker
	/nfs/cache/mod/github.com/tikv/client-go/v2@v2.0.0-alpha.0.20211118154139-b11da6307c6f/txnkv/transaction/2pc.go:1787 +0x19e

Release Version: v5.4.0-nightly
Edition: Community
Git Commit Hash: 8fa0cae3c7d7d71ab1d5a8cd7772753d658f685f
Git Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time: 2021-11-30 04:10:24
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by Tammyxia** [comment]
Can reproduce it very often.
workload:  /go-tpc tpcc
--db workload --warehouses 50 -T 50 --host upstream-tidb.cdc-testbed--tps-510707-1-141 --port 4000 --parts 8 --time 1h0m0s run

**Comment by mornyx** [comment]
Hi @Tammyxia, it looks like this is a different problem, refer to https://github.com/pingcap/tidb/issues/30140#issuecomment-982314736

**Comment by mjonss** [comment]
Likely to be the same issue as https://github.com/pingcap/tidb/issues/26832

**Comment by tiancaiamao** [comment]
> Likely to be the same issue as #26832

Nop, this one is fixed by https://github.com/pingcap/tidb/pull/30181, I'll close it.

**Comment by tiancaiamao** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/30140
