### ISSUE TITLE
Weird View When a Record is Deleted by Two Concurrent Transactions

### ISSUE THREAD

**Issue by TrocTool** [pingcap/tidb#30239]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
/* init */ drop table if exists t;
/* init */ create table t(a int primary key, b int);
/* init */ insert into t values (1, 1), (2, 2);

/* s1 */ begin;
/* s1 */ select * from t; -- [(1, 1), (2, 2)]
/* s2 */ begin;
/* s2 */ delete from t where a = 1;
/* s2 */ commit;
/* s1 */ select * from t; -- [(1, 1), (2, 2)]
/* s1 */ delete from t where a = 1 or a = 2;
/* s1 */ select * from t;  -- [(1, 1)]
/* s1 */ commit;
```
### 2. What did you expect to see? (Required)

The last SELECT of s1 statement should get an empty set.

### 3. What did you see instead (Required)

The last SELECT of s1 statement gets (1, 1), although it has been deleted it.

### 4. What is your TiDB version? (Required)
```
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v5.3.0 |
+--------------------+
1 row in set (0.00 sec)
```

**Comment by vivid392845427** [comment]
duplicate，https://github.com/pingcap/tidb/issues/23966， and this action as same as mysql

**Comment by jebter** [comment]
Duplicate, let's close it.
