### ISSUE TITLE
TiDB returns an error when to try `select INTERVAL 1 DAY + "1997-12-31"`

### ISSUE THREAD

**Issue by espresso98** [pingcap/tidb#30253]
## Bug Report

 TiDB returns an error when to try  `select INTERVAL 1 DAY + "1997-12-31"` but, supports it in the reverse form.
### 1. Minimal reproduce step (Required)
```sql
select INTERVAL 1 DAY + "1997-12-31";
```
### 2. What did you expect to see? 
```sql
mysql> select INTERVAL 1 DAY + "1997-12-31";
+-------------------------------+
| INTERVAL 1 DAY + "1997-12-31" |
+-------------------------------+
| 1998-01-01                    |
+-------------------------------+
1 row in set (0.01 sec)

```

### 3. What did you see instead 
```sql
TiDB> select INTERVAL 1 DAY + "1997-12-31";
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 17 near "1 DAY + "1997-12-31"


TiDB> select "1997-12-31" + INTERVAL 1 DAY;
+-------------------------------+
| "1997-12-31" + INTERVAL 1 DAY |
+-------------------------------+
| 1998-01-01                    |
+-------------------------------+
1 row in set (0.00 sec)

```

### 4. What is your TiDB version? (Required)

```sql
tidb_version(): Release Version: v5.2.2
Edition: Community
Git Commit Hash: da1c21fd45a4ea5900ac16d2f4a248143f378d18
Git Branch: heads/refs/tags/v5.2.2
UTC Build Time: 2021-10-20 06:03:29
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by kennytm** [comment]
adding a parser rule mapping `"INTERVAL" Expression TimeUnit '+' BitExpr` should be sufficient to fix this.

https://github.com/pingcap/tidb/blob/13d0deb7fef7fd7391dce19f320abef4256223bd/parser/parser.y#L6626

**Comment by Defined2014** [comment]
Tried on #30312 , it will caused `select INTERVAL(0,1,1,1)` parse failed. 
And try to follow [mysql](https://github.com/mysql/mysql-server/blob/3290a66c89eb1625a7058e0ef732432b6952b435/sql/sql_yacc.yy#L10568), it caused shift/reduce problems.

**Comment by bb7133** [comment]
I don't think this is a major bug: `select INTERVAL 1 DAY + "1997-12-31";` is not a common usecase and it can be workarounded easily.
