### ISSUE TITLE
support is_uuid function

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#30295]
In the feature request https://github.com/pingcap/tidb/issues/20119 (PR: https://github.com/pingcap/tidb/pull/20140 ) 2 helper functions for UUIDs were added: `uuid_to_bin()` and `bin_to_uuid()`.

MySQL 8.0 also added a function `is_uuid()` which is helpful. This is a feature request to track this.

**Comment by unconsolable** [comment]
/assign
I'd like to try on it. I will remove assign if I can't do this.
