### ISSUE TITLE
does TiDB have a "slow shutdown" feature as MySQL?

### ISSUE THREAD

**Issue by chongchaoyu** [pingcap/tidb#30304]
I haven't find some features in TiDB,
1.does TiDB have a "slow shutdown" feature as MySQL?
2.TiDB uses DIRECTIO or cache when writing data to disk?
3.is it synchronized when TiDB writes data to disk, can it be changed?

And if not sp far, will they be features in the future? 

Thanks

**Comment by morgo** [comment]
For (1): Short answer: no

If by slow shutdown you mean [`innodb-fast-shutdown=0`](https://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_fast_shutdown), the main difference between 0 and 1 (default) is that the change buffer (aka insert buffer) is purged. TiDB (TiKV) does not have change buffering, so this doesn't apply.

For (2) See https://tikv.org/docs/dev/tasks/configure/rocksdb/#use-direct-io-for-flush-and-compaction

For (3) See https://tikv.org/docs/3.0/reference/faq/#does-tikv-have-the-innodb_flush_log_trx_commit-parameter-like-mysql-to-guarantee-the-security-of-data

**Comment by chongchaoyu** [comment]
Thanks a lot, I find that since 5.0, sync-log is forced to true, is that rtight?
"Delete the `raftstore.sync-log` configuration item. By default, written data is forcibly spilled to the disk. Before v5.0, you can explicitly disable `raftstore.sync-log`. Since v5.0, the configuration value is forcibly set to `true`"

**Comment by morgo** [comment]
> Thanks a lot, I find that since 5.0, sync-log is forced to true, is that rtight? "Delete the `raftstore.sync-log` configuration item. By default, written data is forcibly spilled to the disk. Before v5.0, you can explicitly disable `raftstore.sync-log`. Since v5.0, the configuration value is forcibly set to `true`"

Sorry, I should have linked you to the 5.0 version of the FAQ: https://tikv.org/docs/dev/reference/faq/#does-tikv-have-the-innodb_flush_log_trx_commit-parameter-like-mysql-to-guarantee-the-security-of-data

I don't think this is correct. It looks like this just a mistranlsation refering to defaults. See: https://tikv.org/docs/dev/tasks/configure/raftstore/#sync-log (it defaults to safe, but it is still configurable otherwise).

**Comment by chongchaoyu** [comment]
Thanks
