### ISSUE TITLE
Convert time to date : Tidb is not using set timestamp value 

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#30327]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
SET TIMESTAMP=978332400; # 2001-01-01
SELECT cast(TIME'23:59:59.4' as date);
--Tidb is not using set TIMESTAMP value instead using default timestamp.
```

### 2. What did you expect to see? (Required)
```sql
mysql> SELECT cast(TIME'23:59:59.4' as date);
+--------------------------------+
| cast(TIME'23:59:59.4' as date) |
+--------------------------------+
| 2001-01-01                     |
+--------------------------------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> SELECT cast(TIME'23:59:59.4' as date);
+--------------------------------+
| cast(TIME'23:59:59.4' as date) |
+--------------------------------+
| 2021-12-01                     |
+--------------------------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2021-11-29 16:57:51
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by jebter** [comment]
`TiDB root@127.0.0.1:test> SET TIMESTAMP=978332400; # 2001-01-01
Query OK, 0 rows affected
Time: 0.000s
TiDB root@127.0.0.1:test> SELECT cast(TIME'23:59:59.4' as date);
+--------------------------------+
| cast(TIME'23:59:59.4' as date) |
+--------------------------------+
| 2001-01-01                     |
+--------------------------------+

1 row in set
Time: 0.003s
TiDB root@127.0.0.1:test> select tidb_version() \G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v8.1.0
Edition: Community
Git Commit Hash: 945d07c5d5c7a1ae212f6013adfb187f2de24b23
Git Branch: HEAD
UTC Build Time: 2024-05-21 03:52:40
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

1 row in set
Time: 0.001s
`
Please try the latest version. I will close it,if there are any updates, you can reopen it.
