### ISSUE TITLE
tidb master idc-jenkins-ci-tidb/integration-copr-test  failed

### ISSUE THREAD

**Issue by fzhedu** [pingcap/tidb#30344]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/7305/pipeline

### 4. What is your TiDB version? (Required)
master

**Comment by aytrack** [comment]
duplicated with https://github.com/pingcap/tidb/issues/29755, maybe fixed by https://github.com/pingcap/tidb/pull/30236

**Comment by aytrack** [comment]
Not Encounter this after #30236 merged, close this issue .
