### ISSUE TITLE
IT mysqltest `mysql_replace` failed with auto_increment errors

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#30364]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7643/pipeline/86
```bash 
run test [mysql_replace] err: sql:insert into t1 values (0,"error");: failed to run query
"insert into t1 values (0,"error");"
 around line 16,
we need(103):
insert into t1 values (0,"error");
Error 1062: Duplicate entry '127' for key 'PRIMARY'
replace into t1
but got(103):
insert into t1 values (0,"error");
Error 1467: Failed to read auto-increment value from storage engine
```

**Comment by djshow832** [comment]
It's caused by https://github.com/pingcap/tidb/pull/30301

**Comment by djshow832** [comment]
After discussion with @bb7133 , we decide not to be compatible with MySQL and always report an error when the auto_inc values are used up.
