### ISSUE TITLE
How to start pd、tikv、tidb in one command in single machine

### ISSUE THREAD

**Issue by tohghua** [pingcap/tidb#3037]
这样可以提高易用性。

**Comment by siddontang** [comment]
@tohghua 

You can write a script to do it.

**Comment by tohghua** [comment]
@siddontang 
在pd没启动完成的时候启动tikv是会报错的，所以我只能在pd语句后面加sleep? 那样可行，但不完美，呵呵

**Comment by shenli** [comment]
@tohghua You can use `sleep` or check the status of pd-server.
btw: Please use English to discuss in this repo.

**Comment by tohghua** [comment]
@shenli Could you provide a startup script with the product so that new users can quickly run it?

**Comment by shenli** [comment]
@tohghua We have developed a tool based on ansible. It could deploy/stop/upgrade/destroy a cluster with one command. There are so many condition to think about, so It is not easy to implement this in a single script. 
But if you just want to start a test cluster on single machine, you can write a script like this:
```
# start pd
nohup ./bin/pd-server --data-dir=pd &
sleep 5
# start tikv
nohup ./bin/tikv-server --pd="127.0.0.1:2379"  --store=tikv &
sleep 5
# start tidb
nohup ./bin/tidb-server --store=tikv --path="127.0.0.1:2379" &
```
This should work.

**Comment by tohghua** [comment]
@shenli 
I know this can work, but 5s is somewhat too long :p

BTW, when I use this script 
nohup ./bin/tidb-server --path="127.0.0.1:2379" --store=tikv > tidb.log &
there will be many ESC char in the log file

**Comment by shenli** [comment]
We output logs into stderr. So you need to redirect it to stdout. Or you can use --log-file parameter to specify the log file.
In most cases sleep 2 seconds is enough.

**Comment by nullnotnil** [comment]
The easiest way to do this now is with TiUP: https://docs.pingcap.com/tidb/stable/quick-start-with-tidb

**Comment by wjhuang2016** [comment]
Close this issue because it's not active for a long time. For the beginning question, @nullnotnil has given an answer.
