### ISSUE TITLE
Lazy constraint check may cause data inconsistency

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#30410]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
/* t */ drop table if exists t;
/* t */ create table t (c0 int, c1 varchar(20), c2 varchar(20), unique key(c0), key(c2));
/* t */ insert into t (c0, c1, c2) values (1, null, 'green');

/* t */ set tidb_constraint_check_in_place=0;
/* t */ begin optimistic;
/* t */ insert into t (c0, c1, c2) values (1, 'red', 'white');
/* t */ delete from t where c1 is null;
/* t */ update t set c2 = 'green' where c2 between 'purple' and 'white';
/* t */ commit;
/* t */ admin check table t;
```

Note that tidb_constraint_check_in_place is off by default!

### 2. What did you expect to see? (Required)

No error reported by admin check table.

### 3. What did you see instead (Required)

```sql
/* t */ admin check table t;
-- t >> E8133: handle 1, index:types.Datum{k:0x1, decimal:0x0, length:0x0, i:1, collation:"", b:[]uint8(nil), x:interface {}(nil)} != record:<nil>
```

### 4. What is your TiDB version? (Required)

master (28446605c2e019e84e934602f4bd136294a61ff3)

**Comment by cfzjywxk** [comment]
The default `tidb_constraint_check_in_place` value is 0 so the `set tidb_constraint_check_in_place=0;` set statement is not a must to reproduce the issue.

**Comment by zyguan** [comment]
> The default `tidb_constraint_check_in_place` value is 0 so the `set tidb_constraint_check_in_place=0;` set statement is not a must to reproduce the issue.

Yes, I just mean to address it.

**Comment by zyguan** [comment]
https://github.com/pingcap/tidb/pull/30447 has been cherry-picked to all release branches and these PRs are waiting for triage. We can close this issue now.
