### ISSUE TITLE
Handle incompatible meta when recovering a table referring a policy

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#30417]
We should handle the below scene:

```sql
create policy p1 primary_region='r1' regions='r1,r2';
create table t (id int) placement policy p1;
drop table t;
drop table p1;
-- or create a new policy with a same name p1 here

recover table t; 
show create table t; -- should t still referring a policy p1 ?
```

Maybe there are two solutions:

1. recover all table's placement as direct options. For example, `show create table t` will return the result as:

```sql
CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL
)  /*T![placement] PRIMARY_REGION="r1" REGIONS="r1,r2" */ 
```

2. Fails if meta not match. It will check if the policy with the same ID exists when recovering, if not, it fails. Notice that we can set sys variable `placement_checks` to `false` to skip checking. At this time if the policy p1 does not exists (or with a different id) , it will recover a table without any placement settings.

**Comment by morgo** [comment]
I like option (1).

i.e. In the case of `drop table t; drop placement policy p1; create placement policy p1 ..; recover table t` I do not think it is correct to refer to the original policy p1.
