### ISSUE TITLE
br: storage is not balance after restore 2T data

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb#30425]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Just use br restore two database, every one has more than 1T data in.

### 2. What did you expect to see? (Required)
![image](https://user-images.githubusercontent.com/9443637/144793927-cc0ef65b-424a-4b62-bfd8-439556501659.png)

Need take 1 hours to balance after br restore.

![image](https://user-images.githubusercontent.com/9443637/144793754-66a143b1-7702-4d37-b03b-f5e872ad8bc5.png)

![image](https://user-images.githubusercontent.com/9443637/144793802-3d0c21f3-4b8c-43a0-8fe1-ddc0793f123c.png)

### 4. What is your TiDB version? (Required)
Latest 5.3.0-pre

latest 5.3.0-pre

**Comment by YuJuncen** [comment]
This is firstly be considered as a side-effect of https://github.com/pingcap/tidb/pull/27240, but @mayjiang0203 also tested over v5.2.2 (which doesn't contains #27240) and reproduced this problem. We need farther tests to make sure what is the wrong with that.
