### ISSUE TITLE
Error typeinfer of `SELECT FROM_UNIXTIME(12.1) + 1;`

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#3047]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
`SELECT FROM_UNIXTIME(12.1)+1;`

2. What did you expect to see?

`field type be DECIMAL`

3. What did you see instead?

`field type be BIGINT`

4. What version of Go are you using (`go version`)?
`go version go1.7.1 darwin/amd64`

**Comment by woodpenker** [comment]
I am using go1.7.3 && the latest code and I test ur issue.My return is 19700101080013.1 which is Decimal .

**Comment by XuHuaiyu** [comment]
@woodpenker 
Yeah, the result of this query is correct, but the field type is wrong which should be DECIMAL but not BIGINT.
You can use MySQLWorkbench to execute this sql and check the field type of the result.

**Comment by woodpenker** [comment]
@XuHuaiyu I find that this func divide the number into two part integralPart && fractionalPart to calculate,both  are Int.Then convert to MysqlTime. Maybe ur right.

**Comment by louishust** [comment]
this issue can be closed
