### ISSUE TITLE
FAIL to start tidb_server

### ISSUE THREAD

**Issue by leftloveu** [pingcap/tidb#3052]
I tried to start a TiDB test by following this: [binary-deployment](https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md#功能性测试部署)
When I tried to start the tidb-server. I got error message:

2017/04/14 14:48:12 printer.go:31: [info] Welcome to TiDB.
2017/04/14 14:48:12 printer.go:32: [info] Version:
2017/04/14 14:48:12 printer.go:33: [info] Git Commit Hash: a89879d61a1f6543753674418f841c62d5a37796
2017/04/14 14:48:12 printer.go:34: [info] UTC Build Time:  2017-03-28 07:13:29
2017/04/14 14:48:12 client.go:54: [info] [pd] create pd client with endpoints [132.97.135.50:2379]
2017/04/14 14:48:12 conn.go:67: [warning] failed to connect to  
2017/04/14 14:48:12 rpc_worker.go:254: [error] [pd] failed to get cluster id: [pd] rpc failed: mismatch header magic 4854 != daf4

I don't know what happened. How to handle this problem.

**Comment by dbjoa** [comment]
Would you check the version of pd-server?

**Comment by leftloveu** [comment]
@dbjoa I just got the latest version of tidb from here: http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz, so I don't know the version of pd-server. But the log of pd-server mentioned a version:

2017-04-14 14:41:32.895438 I | etcdserver: setting up the initial cluster version to 3.2
2017-04-14 14:41:32.895614 N | etcdserver/membership: set the initial cluster version to 3.2
2017-04-14 14:41:32.895667 I | etcdserver/api: enabled capabilities for version 3.2

Is this the version of pd-server?

**Comment by dbjoa** [comment]
You can check the Git Commit Hash by restarting "pd-server". You should see the messages as below:
2017/04/04 12:36:43 util.go:57: [info] Welcome to Placement Driver (PD).
2017/04/04 12:36:43 util.go:58: [info] Version:
2017/04/04 12:36:43 util.go:59: [info] ## **Git Commit Hash:** 6782d360109fc3d4c2dd24b8a5901573e6798fd2
2017/04/04 12:36:43 util.go:60: [info] UTC Build Time:  2017-03-27 09:44:51
...

From the commit of "b99b30f861deb162932f5313b862af9055abdf93", the protocol between tidb-server and pd-server might be changed to be used gRPC.

You can resolve the issue by choosing one of the two approachs below:
- use pd-server not using gRPC:
   you can build by checkout the last commit before using gRPC: 6782d360109fc3d4c2dd24b8a5901573e6798fd2
- use tidb-server using gRPC:
   you can build by checkout the recent commit after using gRPC: a89879d61a1f6543753674418f841c62d5a37796

**Comment by leftloveu** [comment]
@dbjoa Yes, my pd-server information as below:

2017/04/14 16:55:25 util.go:55: [info] Welcome to Placement Driver (PD).
2017/04/14 16:55:25 util.go:56: [info] Version:
2017/04/14 16:55:25 util.go:57: [info] Git Commit Hash: 15904a72224b678a089973ca30934e38cfc727ec
2017/04/14 16:55:25 util.go:58: [info] UTC Build Time:  2017-03-30 01:55:26
...

I can understand the meaning of your suggestion, but I am a beginner in TiDB and GitHub which means I don't know the details of your two approaches. Could you give me more information about how to deal with this problem?

**Comment by dbjoa** [comment]
Please read the document: https://github.com/pingcap/docs/blob/master/dev-guide/development.md#build-tidb.

In addition, please run the script https://github.com/pingcap/docs/blob/master/scripts/check_requirement.sh, which checks your environments to build the tidb

FYI, I recommend golang 1.8+, which might be more efficient than the previous versions: https://golang.org/doc/install

**Comment by coocood** [comment]
@dbjoa 
Thank you for replying issue for us!

**Comment by leftloveu** [comment]
@dbjoa OK, I will try and thanks a lot
