### ISSUE TITLE
syntax error if character_set_client is gbk

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#30565]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
set @@character_set_client=gbk;
select '啊';  -- in utf8 encoding terminal
```
### 2. What did you expect to see? (Required)

`no error`

### 3. What did you see instead (Required)

`syntax error`

**Comment by xiongjiwei** [comment]
it;s not easy to fix

**Comment by Defined2014** [comment]
> it's not easy to fix 😢

Found this. 😭

**Comment by xiongjiwei** [comment]
close by https://github.com/pingcap/tidb/pull/31039
