### ISSUE TITLE
bug of builtin func from_base64()

### ISSUE THREAD

**Issue by woodpenker** [pingcap/tidb#3056]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

**the mysql required:
    **Decoding recognizes and ignores newline, carriage return, tab, and space.
the go base64  DecodeString() doesn't ignore tab ,space****

2. What did you expect to see?
in mysql:
select from_base64("YW  Jj");
+-----------------------+
| from_base64("YW  Jj") |
+-----------------------+
| abc                   |
+-----------------------+
1 row in set (0.01 sec)

3. What did you see instead?
in tidb:
select from_base64("YW Jj");
ERROR 1105 (HY000): illegal base64 data at input byte 2

4. What version of Go are you using (`go version`)?
go 1.7.3

**so I fix it  -> please refer to the [PR](https://github.com/pingcap/tidb/pull/3055)

**Comment by tiancaiamao** [comment]
Fixed in https://github.com/pingcap/tidb/pull/3070
