### ISSUE TITLE
Insert 3 bytes of data into gbk column, result is inconsistent with MySQL

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#30581]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
set names gbk;
create table t3(a char(10) charset gbk);
insert into t3 values('一a');
```

```
xxx> select @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
```
mysql> insert into t3 values('一a');
ERROR 1366 (HY000): Incorrect string value: '\x80a' for column 'a' at row 1
```

### 3. What did you see instead (Required)
```
tidb> insert into t3 values('一a');
Query OK, 1 row affected (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

**Comment by tangenta** [comment]
This is the GBK incompatibility between MySQL and Golang package `simplifiedchinese`:

```go
// Microsoft's Code Page 936 extends GBK 1.0 to encode the euro sign U+20AC
// as 0x80. The HTML5 specification at http://encoding.spec.whatwg.org/#gbk
// says to treat "gbk" as Code Page 936.
case c0 == 0x80:
	r, size = '€', 1
```

`0x80` is a valid character in `simplifiedchinese`..

**Comment by xiongjiwei** [comment]
> This is the GBK incompatibility between MySQL and Golang package `simplifiedchinese`:
> 
> ```go
> // Microsoft's Code Page 936 extends GBK 1.0 to encode the euro sign U+20AC
> // as 0x80. The HTML5 specification at http://encoding.spec.whatwg.org/#gbk
> // says to treat "gbk" as Code Page 936.
> case c0 == 0x80:
> 	r, size = '€', 1
> ```
> 
> `0x80` is a valid character in `simplifiedchinese`..

ok, that explains.

**Comment by Defined2014** [comment]
https://github.com/pingcap/tidb/pull/30757/files#r774325510 Seems still have some problems with `insert` statement.
