### ISSUE TITLE
The error message for inserting data into a JSON column is different from that for MySQL when names is gbk

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#30618]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table tt;
set names gbk;
create table tt(a varchar(32),j json) charset utf8mb4;
insert into tt values("哈",'{"d": 100}');
```

### 2. What did you expect to see? (Required)
`ERROR 1406 (22001): Data too long for column 'a' at row 1`

### 3. What did you see instead (Required)
`ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 30 near "d": 100}')"`

### 4. What is your TiDB version? (Required)

```
tidb> select version();
+-----------------------------------------------+
| version()                                     |
+-----------------------------------------------+
| 5.7.25-TiDB-v5.4.0-alpha-345-g2a1ea89fd-dirty |
+-----------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by Defined2014** [comment]
Two questions here,
1. TiDB got error about parser. It's same as #30565
2. MySQL got `Data too long for column 'a' at row 1`. I think it's a MySQL bug. 🥲

**Comment by xiongjiwei** [comment]
yes, the no.2 problem is looks like mysql's bug
