### ISSUE TITLE
DATA RACE in the server

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#30642]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
 WARNING: DATA RACE
Read at 0x00c020bc49f0 by goroutine 143:
  github.com/pingcap/tidb/server.(*Server).Run()
      /go/tidb/server/server.go:367 +0x295
  github.com/pingcap/tidb/server.(*basicHTTPHandlerTestSuite).startServer.func1()
      /go/tidb/server/http_handler_test.go:470 +0x39
Previous write at 0x00c020bc49f0 by goroutine 141:
  github.com/pingcap/tidb/server.(*Server).Close()
      /go/tidb/server/server.go:483 +0x1c4
  github.com/pingcap/tidb/server.(*basicHTTPHandlerTestSuite).stopServer()
      /go/tidb/server/http_handler_test.go:486 +0x68
  github.com/pingcap/tidb/server.TestFailpointHandler·dwrap·49()
      /go/tidb/server/http_handler_serial_test.go:438 +0x47
  github.com/pingcap/tidb/server.TestFailpointHandler()
      /go/tidb/server/http_handler_serial_test.go:456 +0x50b
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 143 (running) created at:
  github.com/pingcap/tidb/server.(*basicHTTPHandlerTestSuite).startServer()
      /go/tidb/server/http_handler_test.go:469 +0x807
  github.com/pingcap/tidb/server.TestFailpointHandler()
      /go/tidb/server/http_handler_serial_test.go:448 +0x364
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.(*T).Run·dwrap·21()
      /usr/local/go/src/testing/testing.go:1306 +0x47
Goroutine 141 (running) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1306 +0x726
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1598 +0x99
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1259 +0x22f
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1596 +0x7ca
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1504 +0x9d1
  go.uber.org/goleak.VerifyTestMain()
      /home/prow/go/pkg/mod/go.uber.org/goleak@v1.1.12/testmain.go:53 +0x59
  github.com/pingcap/tidb/server.TestMain()
      /go/tidb/server/main_test.go:67 +0xd57
  main.main()
      _testmain.go:177 +0x264 
```

**Comment by bb7133** [comment]
I think it is caused for the following reason:

- TiDB server is started with a socket listener(read of `s.socket`): https://github.com/pingcap/tidb/blob/6756bd2ea824c5104cf7c326e24692bd7dad97fd/server/server.go#L367
- The test case tries to close the server, during this process `s.socket` is set to `nil`(write of it): https://github.com/pingcap/tidb/blob/6756bd2ea824c5104cf7c326e24692bd7dad97fd/server/server.go#L483

We have a ["waitUntilCustomeServerCanConnect"](https://github.com/pingcap/tidb/blob/53f33fa1a3e55b89f45a47d2d711d4b4502b9e85/server/server_test.go#L1931) method to make sure the listener is ready before the running of the rest test codes, but it did check for the connection given by `dsn`.

So it is possible that in extreme cases, the non-socket listener is ready and makes `waitUntilCustomeServerCanConnect` passed by the socket listener is not, then we may see a RACE for `s.socket`.

The `s.socket` is introduced in #29374 , but I don't think it is necessary:

https://github.com/pingcap/tidb/blob/a696b43bc9461ee4fbf13663a0a27eb5d4b7af14/server/http_handler_test.go#L462

I plan to remove it to avoid the race issue. /cc @hawkingrei @dveeden @mjonss

**Comment by dveeden** [comment]
@bb7133 That should be fine. In current master `newTestConfig()` sets `cfg.Socket = ""`, so anything that doesn't explicitly need a socket doesn't need to set socket names etc.
