### ISSUE TITLE
The JSON column returns a error message that are different with MySQL

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#30686]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
drop table t;
set names gbk;
create table t(a varchar(32), b blob(32), t text(32), j json, d datetime, index idx(b(16), d)) CHARSET=gbk COLLATE=gbk_bin;
insert into t values("\t","\t","\t",'{"赞": "好"}',"2018-10-13");
```

### 2. What did you expect to see? (Required)
`ERROR 3140 (22032): Invalid JSON text: "Missing a colon after a name of object member." at position 9 in value for column 't.j'.`

### 3. What did you see instead (Required)
`ERROR 3140 (22032): Invalid JSON text: The document root must not be followed by other values.`

### 4. What is your TiDB version? (Required)

`5.7.25-TiDB-v5.4.0-alpha-345-g2a1ea89fd-dirty`

**Comment by xiongjiwei** [comment]
dup of https://github.com/pingcap/tidb/issues/30565

**Comment by Defined2014** [comment]
The reason for decode failure is same as #30565.
But the error msg is hard to same as MySQL, we use `encoding/json` to check data is valid or not which will lost some information. 
https://github.com/pingcap/tidb/blob/529ce88c1cc65cbdcf6bd81c48c3a2d0efc424ba/types/json/binary.go#L396-L410
