### ISSUE TITLE
truncate float incorrectly. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#307]
```
create table t (float(8));
insert into t values (3.14);
select * from t;
```

we will get 3, not 3.14. 

@shenli

**Comment by coocood** [comment]
Do you mean `create table t (c1 float(0))`?

**Comment by siddontang** [comment]
No, `create table t (float(8))`, 8 is for field length, no decimal here.

**Comment by coocood** [comment]
@siddontang but I can not execute this statement in mysql.

**Comment by coocood** [comment]
And I changed that to `create table t (c float(8));`, `insert t values (3.14)`,  and got `3.14`.
