### ISSUE TITLE
S3's `check-path` is not specific enough

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#30709]
Please answer these questions before submitting your issue. Thanks!

### 1. What did you do?

1. dump some SQL files into `s3://some-bucket/some-prefix/` on AWS S3.
2. create a role, give it the `s3:ListBucket` and `s3:GetObject` permission, conditioned with `s3:prefix`=`some-prefix/`.
3. run Lightning using that role

### 2. What did you expect to see?

successfully restored.

### 3. What did you see instead?

failed due to an unnecessary `HeadBucket` call:

```
tidb lightning encountered error:  create storage failed: Bucket some-bucket is not accessible: Forbidden: Forbidden
        status code: 403, request id: ..., host id: ...: [BR:ExternalStorage:ErrStorageInvalidConfig]invalid external storage config
```

### 4. What version of BR and TiDB/TiKV/PD are you using?

master

**Comment by lance6716** [comment]
open since master didn't fix it 

https://github.com/pingcap/tidb/blob/ac25e9f04ccb775e228c946fa95f802a38d8291b/br/pkg/lightning/lightning.go#L294

https://github.com/pingcap/tidb/blob/ac25e9f04ccb775e228c946fa95f802a38d8291b/br/pkg/storage/s3.go#L287-L292
