### ISSUE TITLE
Improve the file format for cmd/explaintest/r/xxx.result

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#30718]
## Enhancement

Currently, we write the expected results one by one without any space character into `cmd/explaintest/r/xxx.result`. The logic to compare the actual results with the expected results is as follows:
```
// check test result now
gotBuf := t.buf.Bytes()[offset:]
buf := make([]byte, t.buf.Len()-offset)
if _, err = t.resultFD.ReadAt(buf, int64(offset)); !(err == nil || err == io.EOF) {
    return errors.Trace(errors.Errorf("run \"%v\" at line %d err, we got \n%s\nbut read result err %s", qText, query.Line, gotBuf, err))
}
if !bytes.Equal(gotBuf, buf) {
    return errors.Trace(errors.Errorf("run \"%v\" at line %d err, we need:\n%s\nbut got:\n%s\n", qText, query.Line, buf, gotBuf))
}
```
The result file format and the comparison logic lead to the problem like #29475. Though #30717 can fix #29475, it may blame on the next query if the previous query result is wrong. Maybe we can rewrite the results in json format to solve the problem and make it more readable.

**Comment by Defined2014** [comment]
We already use mysql-tester instead of `explaintest`, so close this issue.
