### ISSUE TITLE
Restore failure due to split region cause some key space unmap to region temporarily.

### ISSUE THREAD

**Issue by fengou1** [pingcap/tidb#30720]
### 1. Minimal reproduce step (Required)
There is no specific step to reproduce the issue.
issue happen occasionally.

### 2. What did you expect to see? (Required)
If PD split region ongoing, BR may need to wait until there are error or stuck during split region (timeout 5 mins in tidb)
![image](https://user-images.githubusercontent.com/85682690/146015449-9152f6e4-6f22-491a-a83f-d46611357281.png)

### 3. What did you see instead (Required)
Split region beyond 1.5 seconds, Restore will failure immediately.

### 4. What is your TiDB version? (Required)
5.0.1, it will happen also in all tidb version

**Comment by JmPotato** [comment]
Hi, thanks for reporting the problem although you should not mention anything about Oncall or post an internal Jira link here. We should be community-friendly in a GitHub repo. What you show is meaningless to the contributors of TiDB, they DO NOT and should not ever know or care these rather internal information. The right way should be to extract the key information in the problem and post it here.

**Comment by fengou1** [comment]
lower priority since retry restore can success and it happen rarely.
