### ISSUE TITLE
Return correct error code and message for query error

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#3073]
Currently, a lot of error code and error messages returned by TiDB is different than MySQL.

A detailed error message is important for users to address the issue, some application checks error code to handle the error.

We should return the correct error code and error message as much as possible.

An example PR that fix an error message looks like this

https://github.com/pingcap/tidb/pull/3017

**Comment by zhexuany** [comment]
https://github.com/pingcap/tidb/pull/3124/commits/538081b9595584d04817009914f0853f6412decb
this PR shall fix this issue.
