### ISSUE TITLE
SELECT right function error

### ISSUE THREAD

**Issue by luckrats** [pingcap/tidb#3074]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`SELECT left('123456',3),right('123456',3);`
reply error

2. What did you expect to see?
left('123456',3), right('123456',3)
'123', '456'

3. What did you see instead?
`SELECT left('123456',3),right('123456',3) Error Code: 1105. line 0 column 29 near "('123456',3) `

4. What version of Go are you using (`go version`)?
go 1.7

**Comment by shenli** [comment]
@luckrats May  I have your tidb-server's commit hash? You can get it by `tidb-server -V`.
The `right` function is not implemented yet. We will working on this.

**Comment by woodpenker** [comment]
I am working on this.Soon I will give a PR

**Comment by luckrats** [comment]
thx
