### ISSUE TITLE
binary literal in gbk columns is not handled

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#30798]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t(a char(10) charset gbk default 0xd2bb);
```

### 2. What did you expect to see? (Required)

`no error`

### 3. What did you see instead (Required)

`ERROR 1067 (42000): Invalid default value for 'a'`

**Comment by tangenta** [comment]
No affecting version because it is a developing feature.
