### ISSUE TITLE
Show tables Compatibility differences

### ISSUE THREAD

**Issue by unhappydepig** [pingcap/tidb#30803]
We use tidb and  elastic-job。
We have create job_execution_log in tidb。However, at startup, the program will also try to rebuild the table, because the table already exists, so the program will report an error.

By checking the source code, it is found that elastic job uses 【SHOW FULL TABLES LIKE 'JOB_EXECUTION_LOG';】 No results were returned。when we use lowercase [SHOW FULL TABLES LIKE 'job_execution_log';]It can return normally。

When we use MySQL。Whether in large or lowercase  It can return normally。

**Comment by hawkingrei** [comment]
dup of #29910
