### ISSUE TITLE
TiDB connection is lost due to "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by JZuming** [pingcap/tidb#30804]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

**Setup the environment:**

```
tiup playground --db.binpath /path/to/latest/tidb-server &
mysql -h "127.0.0.1" -u root -P 4000 -D testdb < mysql_bk.sql
```
_mysql_bk.sql:_ 
[mysql_bk.sql.txt](https://github.com/pingcap/tidb/files/7725907/mysql_bk.sql.txt)

**Test case**
```
mysql -h "127.0.0.1" -u root -P 4000 -D testdb
mysql> WITH
cte_0 AS (
select distinct
    avg(0) over w_ap1h0c as c2
  from
    (select 
          ref_0.c7 as c3,
          ref_0.c1 as c10
        from
          t_ai_sq as ref_0
        ) as subq_0
  window w_ap1h0c as ( partition by subq_0.c3 order by (subq_0.c3 - case when subq_0.c10 in (
            select null as c0) then subq_0.c3 else subq_0.c3 end ) desc))
select 1;

mysql> select 1;
```

### 2. What did you expect to see? (Required)

The connection will not be lost.

### 3. What did you see instead (Required)

The test case made the connection lost.
```
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    341
Current database: testdb
```

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-429-gd208b6202
Edition: Community
Git Commit Hash: d208b62025017f122a3d030d50ba802526e7ef48
Git Branch: master
UTC Build Time: 2021-12-16 08:36:57
GoVersion: go1.16
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by JZuming** [comment]
The log of tidb-server

> [2021/12/16 09:15:00.409 +00:00] [ERROR] [conn.go:1029] ["connection running loop panic"] [conn=341] [lastSQL="WITH \ncte_0 AS (\nselect distinct \n    avg(0) over w_ap1h0c as c2 \n  from \n    (select  \n          ref_0.c7 as c3, \n          ref_0.c1 as c10\n        from \n          t_ai_sq as ref_0\n        ) as subq_0\n  window w_ap1h0c as ( partition by subq_0.c3 order by (subq_0.c3 - case when subq_0.c10 in (\n            select null as c0) then subq_0.c3 else subq_0.c3 end ) desc))\nselect 1"] [err="runtime error: invalid memory address or nil pointer dereference"] [stack="goroutine 128262 [running]:\ngithub.com/pingcap/tidb/server.(*clientConn).Run.func1(0x41e9310, 0xc001edff20, 0xc001aa7040)\n\t/home/zuming/tidb/server/conn.go:1027 +0xf5\npanic(0x383b840, 0x5716440)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).checkOriginWindowSpec(0xc00089b1e0, 0x0, 0xc00109cd50, 0x1, 0x1, 0xc002fa9008, 0xc001ab9188)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:5679 +0x3a\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).checkOriginWindowFuncs(0xc00089b1e0, 0xc00152a400, 0x1, 0x1, 0xc00109cd50, 0x1, 0x1, 0x1, 0x4)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:5670 +0xe5\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildWindowFunctions(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0x4230410, 0xc001ab90a0, 0xc00014e0c0, 0xc00152a3f0, 0x1, 0x1, 0xc0015d6360, ...)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:5608 +0x579\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0xc0006c63c0, 0x4230410, 0xc001ab90a0, 0x0, 0x0)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:3712 +0x1845\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildResultSetNode(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0x4207da8, 0xc0006c63c0, 0x0, 0x0, 0x0, 0x0)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:374 +0xbe5\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildCte(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0xc000d31920, 0x0, 0xc00152a248, 0x0, 0x1, 0x0)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:6198 +0x129\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildWith(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0xc000ad2b40, 0x1, 0xc001d22e48)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:6440 +0x305\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0xc0006c6690, 0x0, 0x0, 0x0, 0x0)\n\t/home/zuming/tidb/planner/core/logical_plan_builder.go:3544 +0x24e7\ngithub.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc00089b1e0, 0x41e9310, 0xc001e22090, 0x4202160, 0xc0006c6690, 0xc001e224b0, 0xc00089b1e0, 0xc0024d2580, 0x1)\n\t/home/zuming/tidb/planner/core/planbuilder.go:714 +0xae8\ngithub.com/pingcap/tidb/planner.optimize(0x41e9310, 0xc001e22090, 0x4233838, 0xc000f41200, 0x4202160, 0xc0006c6690, 0x4228b78, 0xc00113cbd0, 0x0, 0x0, ...)\n\t/home/zuming/tidb/planner/optimize.go:355 +0x2ba\ngithub.com/pingcap/tidb/planner.Optimize(0x41e9310, 0xc001e22090, 0x4233838, 0xc000f41200, 0x4202160, 0xc0006c6690, 0x4228b78, 0xc00113cbd0, 0x0, 0x0, ...)\n\t/home/zuming/tidb/planner/optimize.go:238 +0x13b4\ngithub.com/pingcap/tidb/executor.(*Compiler).Compile(0xc000eccbe0, 0x41e9310, 0xc001e22090, 0x4207df8, 0xc0006c6690, 0x0, 0x0, 0x0)\n\t/home/zuming/tidb/executor/compiler.go:65 +0x36e\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt(0xc000f41200, 0x41e9310, 0xc001e22090, 0x4207df8, 0xc0006c6690, 0x0, 0x0, 0x0, 0x0)\n\t/home/zuming/tidb/session/session.go:1656 +0x4c9\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt(0xc001b59f50, 0x41e9310, 0xc001e22090, 0x4207df8, 0xc0006c6690, 0xc00198c160, 0x41e9310, 0xc001e22090, 0x0)\n\t/home/zuming/tidb/server/driver_tidb.go:222 +0x6b\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt(0xc001aa7040, 0x41e9268, 0xc001e22090, 0x4207df8, 0xc0006c6690, 0x5e75a28, 0x0, 0x0, 0x1, 0x0, ...)\n\t/home/zuming/tidb/server/conn.go:1960 +0x1d1\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc001aa7040, 0x41e9268, 0xc000ad2a80, 0xc000dc8181, 0x17a, 0x0, 0x0)\n\t/home/zuming/tidb/server/conn.go:1829 +0x498\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch(0xc001aa7040, 0x41e9268, 0xc000ad2a80, 0xc000dc8180, 0x17b, 0x17a, 0x0, 0x0)\n\t/home/zuming/tidb/server/conn.go:1334 +0xafd\ngithub.com/pingcap/tidb/server.(*clientConn).Run(0xc001aa7040, 0x41e9310, 0xc001edff20)\n\t/home/zuming/tidb/server/conn.go:1089 +0x2bc\ngithub.com/pingcap/tidb/server.(*Server).onConn(0xc000d17c70, 0xc001aa7040)\n\t/home/zuming/tidb/server/server.go:548 +0xa93\ncreated by github.com/pingcap/tidb/server.(*Server).startNetwo"]

**Comment by bb7133** [comment]
This is related to the optimizer for window functions, I will transfer the tag to `sig/planner`.
