### ISSUE TITLE
SQL alias rule is different with mysql 5.7

### ISSUE THREAD

**Issue by SelbyLiu** [pingcap/tidb#30841]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![image](https://user-images.githubusercontent.com/23331600/146172948-aee18ed3-53d9-4c09-bce2-eb5669c72bb7.png)
![image](https://user-images.githubusercontent.com/23331600/146172977-074732bd-1f85-4062-bea4-72e49232ca08.png)

in tidb 5.2.1 (linux)
when 'b' is table alias in from clause ,we use 'B' in group by clause and 'b' in order by clause, tidb popup error.
when 'b' is table alias in from clause ,we use 'B' in group by clause and 'B' in order by clause, sql is working.
in mysql 5.7.23(linux), sql is working in both situation, please help to check,thx.

### 2. What did you expect to see? (Required)
when 'b' is table alias in from clause ,we use 'B' in group by clause and 'b' in order by clause, sql working  as mysql.
### 3. What did you see instead (Required)
when 'b' is table alias in from clause ,we use 'B' in group by clause and 'b' in order by clause, tidb popup error.

### 4. What is your TiDB version? (Required)
5.2.1

![middle_img_v2_c7ec5500-e0f6-4fff-a554-a26362f77feg](https://user-images.githubusercontent.com/23331600/146505771-b2de47c9-57ca-43c1-a5cd-003d58232b0f.jpg)

**Comment by yudongusa** [comment]
@winoros this one seems a similar to alias issues we are currently investigating. Might be worthy to take this as refactor feature.

**Comment by winoros** [comment]
@SelbyLiu Could you give us a clear example to show the problem?

**Comment by winoros** [comment]
This one has been solved via the new impl of the `only_full_group_by` checker.
It would be released in the next release version.
We downgrade its severity currently.
