### ISSUE TITLE
pd client can't receive message larger than 4M

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#30845]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Access tidb ip:10080/tables/{db}/{table}/regions to get regions of a very large table.

### 2. What did you expect to see? (Required)

return the region information of this table

### 3. What did you see instead (Required)

rpc error: code = ResourceExhausted desc = grpc: received message larger than max (xxx vs. 4194304)

### 4. What is your TiDB version? (Required)

4.0
this should also exist on master

**Comment by nolouch** [comment]
ref https://github.com/tikv/pd/issues/4429

**Comment by jebter** [comment]
It has been fixed： https://github.com/tikv/pd/pull/4482
