### ISSUE TITLE
Stale read failed for read-committed isolation when autocommit=0

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#30872]
## Bug Report

Stale read failed for read-committed isolation

### 1. Minimal reproduce step (Required)

```
drop table if exists t1;
create table t1(id int primary key);
set tx_isolation = 'READ-COMMITTED';
set autocommit=0;
select * from t1 as of timestamp now() where id=1;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t1 as of timestamp now() where id=1;
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t1 as of timestamp now() where id=1;
ERROR 8024 (HY000): invalid transaction
```

### 4. What is your TiDB version? (Required)

master

**Comment by zyguan** [comment]
Hi, @lcwangchao , which commit do you use? I only got some `E1146: Table 'test.t1' doesn't exist` occasionally with latest master (55a38cb1627b2f5476e5b6fe0459d7b9a5706fea).

**Comment by lcwangchao** [comment]
@zyguan sorry, the description is not right and I just modified it. This error occurs when read-committed and autocommit=0 .

**Comment by zyguan** [comment]
It seems ts future won't be prepared since #29393 , tidb tried to active transaction for the point select statement (as the following stack shown), and then invalid transaction got returned [here](https://github.com/pingcap/tidb/blob/0d899cdd9eee90e4942d87f2b8fcb4854be3c133/session/session.go#L2166). @Yisaer could you take a look?
```
github.com/pingcap/tidb/executor.(*executorBuilder).getSnapshotTS
        /home/zyguan/src/pingcap/tidb/executor/builder.go:1502
github.com/pingcap/tidb/executor.(*executorBuilder).buildPointGet
        /home/zyguan/src/pingcap/tidb/executor/point_get.go:51
```
