### ISSUE TITLE
The query result of latin1 is not correct

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#30879]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `t` (
  `a` varchar(20) DEFAULT NULL,
  `b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
CREATE TABLE `t2` (
  `a` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin;
insert into t values("10",1);
insert into t2 values("10"),("a");
select min(a) as x from t  having x!=any(select a from t2 where x between 0 and 11);
```
### 2. What did you expect to see? (Required)
10
### 3. What did you see instead (Required)
empty result
### 4. What is your TiDB version? (Required)

Release Version: v5.4.0-alpha-447-g1721706b2
Edition: Community
Git Commit Hash: 1721706b2386b1600743da4c845c95319990b1c3
Git Branch: master
UTC Build Time: 2021-12-19 14:44:07
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by tangenta** [comment]
MySQL:
```sql
mysql> select min(a) as x from t  having x!=any(select a from t2 where x between 0 and 11);
ERROR 1247 (42S22): Reference 'x' not supported (reference to group function)
mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.25    |
+-----------+
1 row in set (0.00 sec)
```

**Comment by tangenta** [comment]
I can't reproduce it in master(74545cbd).
