### ISSUE TITLE
is there problem still  in spring transaction？

### ISSUE THREAD

**Issue by taotao365s** [pingcap/tidb#30906]
as it describle in 2.0，but now does it work fine in 5.x？

![image](https://user-images.githubusercontent.com/1212932/146886830-4596d775-a3cc-4ef9-925f-217dd3440629.png)

**Comment by cfzjywxk** [comment]
@taotao365s 
Hello, for this situation it's recommanded to use the pessimistic transaction [mode](https://docs.pingcap.com/zh/tidb/stable/pessimistic-transaction/).

For example

begin; // After v3.0.8 the newly deploed TiDB cluster will default use pessimistic transaction mode, if the cluster is upgraded use `begin pessimistic` instead. There's reference in the above document about how to enable pessimistic transaction mode.

select SeqValue from tab for update;  // Use for update the pessimistic transaction mode to read the current value and lock the record.
update xxx_tab set SeqValue = SeqValue + 1 where SeqValue = xxx;

commit;

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
