### ISSUE TITLE
Bug: turn AND NOT to AND ! Will cause no data to be queried

### ISSUE THREAD

**Issue by cjphaha** [pingcap/tidb#30955]
this is my demo
```go
func main() {
	sql := "select * from stu where mobile = 1 and not id = 1024"
	p := parser.New()
	stmt, err := p.ParseOneStmt(sql, "", "")
	if err != nil {
		panic(err)
	}
	buf := &bytes.Buffer{}
	restoreCtx := format.NewRestoreCtx(format.RestoreKeyWordUppercase|format.RestoreNameBackQuotes, buf)
	stmt.Restore(restoreCtx)
	fmt.Println(buf.String())
}
```
then it print 
```sql
SELECT * FROM `stu` WHERE `mobile`=1 AND !`id`=1024
```
however this sql can't get data from `Mysql 5.7`

The correct sql should be
```sql
SELECT * FROM `stu` WHERE `mobile`=1 AND `id`!=1024
```

my parser package and tidb package version is 
```bash
github.com/pingcap/parser v0.0.0-20200623164729-3a18f1e5dceb
github.com/pingcap/tidb v1.1.0-beta.0.20200630082100-328b6d0a955c
```

**Comment by cjphaha** [comment]
@kennytm Hi bro, I think mybe this is parser package's bug or characteristic? I found this problem when using the parser package alone

**Comment by kennytm** [comment]
@cjphaha the parser package has been merged back into the TiDB repo as a sub-module since October (#28644).

**Comment by cjphaha** [comment]
> @cjphaha the parser package has been merged back into the TiDB repo as a sub-module since October (#28644).

Ok~ got it,thx

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
