### ISSUE TITLE
Fine-grained type infer for Decimal type

### ISSUE THREAD

**Issue by windtalker** [pingcap/tidb#30961]
### Background
In TiFlash, the implementation of Decimal type is based on Interger, i.e. the internal storage of Decimal is actually Integer. And TiFlash has 4 subtype of Decimal
- Decimal32 with max precision of 9
- Decimal64 with max precision of 18
- Decimal128 with max precision of 38
- Decimal256 with max precision of 65

As shown in the name, the internal storage of these types are Int32, Int64, Int128 and Int256.
When doing decimal calculations, TiFlash will first align the scale, and then just using integer calculations. For exmple, 
`Decimal(15,2) + Decimal(15,3)`
The result type should be `Decimal(17,3)`, and it can be represented by Int64, so the decimal calculation is converted to int64 calculation:
`Decimal(15,2).getInt64 * 10 + Decimal(15,3).getInt64`

The above example shows that the efficiency of decimal calculation in TiFlash is directly related to its max precision.

### Problem
In TiDB, the type infer of Decimal tends to increase the max precision meaninglessly, since the TiDB's Decimal calculation is precision in-sensitive, so it is harmless to use a bigger precision, however, TiFlash's Decimal calculation is precision sensitive, and in order to be compatible with tidb, for each expression, TiFlash will cast its result's type to TiDB's type implicitly, so a meaningless high precision will hurt the performance of TiFlash.
I did an experiment using the query
`select SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))  from lineitem`
The data is based on TPCH-100, and the cluster has 3 TiFlash node, the data type of  L_EXTENDEDPRICE and  L_DISCOUNT are  both Decimal(15,2)
TiDB's plan of the sql is 
```
mysql> explain select SUM(L_EXTENDEDPRICE * (1 - L_DISCOUNT))  from lineitem;
+--------------------------------+--------------+-------------------+----------------+-----------------------------------------------------------------------------------------------------------------+
| id                             | estRows      | task              | access object  | operator info                                                                                                   |
+--------------------------------+--------------+-------------------+----------------+-----------------------------------------------------------------------------------------------------------------+
| HashAgg_20                     | 1.00         | root              |                | funcs:sum(Column#20)->Column#18                                                                                 |
| └─TableReader_22               | 1.00         | root              |                | data:ExchangeSender_21                                                                                          |
|   └─ExchangeSender_21          | 1.00         | batchCop[tiflash] |                | ExchangeType: PassThrough                                                                                       |
|     └─HashAgg_8                | 1.00         | batchCop[tiflash] |                | funcs:sum(Column#22)->Column#20                                                                                 |
|       └─Projection_31          | 600042649.00 | batchCop[tiflash] |                | mul(tpch_100_noncluster.lineitem.l_extendedprice, minus(1, tpch_100_noncluster.lineitem.l_discount))->Column#22 |
|         └─TableFullScan_19     | 600042649.00 | batchCop[tiflash] | table:lineitem | keep order:false                                                                                                |
+--------------------------------+--------------+-------------------+----------------+-----------------------------------------------------------------------------------------------------------------+
```

As you can see, `Projection_31` is a Decimal calculation of 
`mul(tpch_100_noncluster.lineitem.l_extendedprice, minus(1, tpch_100_noncluster.lineitem.l_discount))->Column#22`

On master TiDB, `Projection_31` costs 1.8s, and the type infer results is
1 - L_DISCOUNT => Decimal(25,2)
L_EXTENDEDPRICE * (1 - L_DISCOUNT) => Decimal(65,4)
So according to TiFlash's rule, the calculation happens in TiFlash is something like
`int256 * (cast(int64 - int64) as int128)`

However, if we use fine-grained type infer for Decimal type, then theoretically
1 - L_DISCOUNT => Decimal(16,2)
L_EXTENDEDPRICE * (1 - L_DISCOUNT) => Decimal(31,4)
then, the calculation happens in TiFlash should be 
`int128 * (int64 - int64)`
I hacked TiDB to generate plan using the above type infer results, and `Projection_31` now costs 0.9s.
### Proposal
Since TiFlash's Decimal is precision sensitive, TiDB should use a fine-grained type infer for Decimal type. And we can take [the type infer of sql server](https://docs.microsoft.com/en-us/sql/t-sql/data-types/precision-scale-and-length-transact-sql?view=sql-server-ver15) as a reference, for decimal operators like `+,-,*,%`, we can use the same type infer rules with sql-server, and for decimal divide, I think we can keep our current implementation since we need to keep compatible with MySQL

**Comment by winoros** [comment]
To be compatible with MySQL. We can add a Cast after the calculation so that the final output column info is the same as MySQL.

**Comment by winoros** [comment]
If the behavior of truncating would be influenced, I think this is a good choice. We can try to add a final cast after the calculation to give MySQL clients the same field type as the original MySQL.

**Comment by windtalker** [comment]
> If the behavior of truncating would be influenced, I think this is a good choice. We can try to add a final cast after the calculation to give MySQL clients the same field type as the original MySQL.

Even current TiDB's field type is not the same as MySQL, I tested the same query in MySQL, 
The return type of `1 - Decimal(15,2)` is `Decimal(18,2)`
The return type of `Decimal(15,2)*(1 - Decimal(15,2))` is `Decimal(33,4)`
