### ISSUE TITLE
improve util／types／compar.go by removing 'else' in function

### ISSUE THREAD

**Issue by zsy619** [pingcap/tidb#3099]
在if-else语句中，if已经return了，else显示是比较多余的
例如：
func CompareInt64(x, y int64) int {
	if x < y {
		return -1
	} else if x == y {
		return 0
	}

	return 1
}
修改后：
func CompareInt64(x, y int64) int {
	if x < y {
		return -1
	} 
        if x == y {
		return 0
	}

	return 1
}

**Comment by hanfei1991** [comment]
`else` always makes code clearer.
