### ISSUE TITLE
utils/types/datum.go error comments

### ISSUE THREAD

**Issue by zsy619** [pingcap/tidb#3100]
line 61：
x         interface{} // f hold all other types.

The comment should be: x hold all other types.

**Comment by zhexuany** [comment]
@zsy619 Please use English in this project. You are welcome to create a PR to correct this.

**Comment by ngaut** [comment]
Please feel free to send a PR.

**Comment by yuanwhy** [comment]
The PR fixed it https://github.com/pingcap/tidb/pull/2871
