### ISSUE TITLE
restore a 1TB dataset with 2 tiflash replicas takes over 24 hours

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#31005]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

restore a interval dataset over 1TB
    br restore full --pd "peer:12379" \
        --storage "s3://1tb" \
        --s3.endpoint "http://xxx" \
        --send-credentials-to-tikv=true \
                --check-requirements=false

### 2. What did you expect to see? (Required)

complete the restore much faster

### 3. What did you see instead (Required)
restore takes over 24 hours

### 4. What is your TiDB version? (Required)

```
Release Version: v5.4.0-alpha-459-g87ab28e
Edition: Community
Git Commit Hash: 87ab28ebb2ac87b6e8d7c252187338c517598318
Git Branch: HEAD
UTC Build Time: 2021-12-20 17:51:58
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by YuJuncen** [comment]
The download speed from the environment is slow. As a workaround, we can set `import.num-threads`(at TiKV) and `checksum-concurrency`(at BR) to higher for better utilizing the resource.

However, the download speed is weird -- I have tested the speed via `mc` and seems no connectivity problem between the environment and the storage. Maybe the S3 SDK have involved unnecessary backoff or something.

**Comment by dbsid** [comment]
after increasing the config, the restore time reduce from ~24h to ~4h
import.num-threads: 64
--checksum-concurrency 64
