### ISSUE TITLE
PR #30288 results in 5.4%-10% performance regression in read-heavy workloads

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#31014]
## Bug Report

PR #30288 results in 5.4%-10% performance regression in read-heavy workloads

### 1. Minimal reproduce step (Required)

1. Deploy a cluster with nightly version
2. Turn on Prepare plan cache
2. Run sysbench oltp_read_only or other read-heavy workloads

### 3. What did you see instead (Required)

The performance of workloads drops 5.4%-10% compared with their baseline.
You can take commit 755553660e6036ead13d1f0aa271eaf59d939fbd as baseline.

### 4. What is your TiDB version? (Required)

commit 4dc385ce8b7a3b194462e76670f89483de5884b7

**Comment by bb7133** [comment]
Interesting... we have found another performance regression(https://github.com/pingcap/tidb/issues/30936) and thought it was resolved by https://github.com/pingcap/tidb/pull/30937.

**Comment by Yui-Song** [comment]
The performance of sysbench read-heavy workloads like: oltp_read_write, oltp_read_only, select_random_points have been improved by https://github.com/pingcap/tidb/pull/30937. However, the performance of shenma, a read-heavy bank workload,   still drop 8.9%-10%. It's a CPU-consuming workload.

**Comment by Yui-Song** [comment]
Please refer to the internal OLTP Benchmark Overview page for more details.
