### ISSUE TITLE
We shouldn’t modify a column‘s charset by `alter table … modify column…`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#31011]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Currently we do not support "alter table…modify column…" to change the character set of a column (except utf8-> UTF8MB4).
```
create table t(a char(25) charset utf8mb4, b char(20)  charset gbk) charset gbk;
alter table t modify column a varchar(255) charset gbk;
create table t1(a varchar(25) charset utf8mb4, b char(20)  charset gbk) charset gbk;
alter table t1 modify column a varchar(255) charset gbk;
```

### 2. What did you expect to see? (Required)
```
tidb>  alter table t modify column a varchar(255) charset gbk;
ERROR 8200 (HY000): Unsupported modify charset from utf8mb4 to gbk
tidb>  alter table t1 modify column a varchar(255) charset gbk;
ERROR 8200 (HY000): Unsupported modify charset from utf8mb4 to gbk
```

### 3. What did you see instead (Required)
```
tidb>  alter table t modify column a varchar(255) charset gbk;
Query OK, 0 rows affected (2.52 sec)
tidb>  alter table t1 modify column a varchar(255) charset gbk;
ERROR 8200 (HY000): Unsupported modify charset from utf8mb4 to gbk
```

### 4. What is your TiDB version? (Required)

```
| Release Version: v5.4.0-alpha-501-g93d28b9d3-dirty
Edition: Community
Git Commit Hash: 93d28b9d3ffe2726640a72342a3c517f88bbd37d
Git Branch: HEAD
UTC Build Time: 2021-12-24 09:13:53
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by Defined2014** [comment]
one more case
```mysql
create table t(a char(20) charset utf8mb4, b char(20) charset gbk, c text, d json, e timestamp, f set('a一','b二','c三','d四'), g enum('a一','b二','c三','d四') default 'c三') charset gbk;
alter table t modify column c varchar(255) charset utf8mb4;
alter table t modify column d varchar(255) charset utf8mb4;
alter table t modify column e varchar(255) charset utf8mb4;
alter table t modify column f varchar(255) charset utf8mb4;
alter table t modify column g varchar(255) charset utf8mb4;
```

**Comment by Defined2014** [comment]
> one more case
> 
> ```sql
> create table t(a char(20) charset utf8mb4, b char(20) charset gbk, c text, d json, e timestamp, f set('a一','b二','c三','d四'), g enum('a一','b二','c三','d四') default 'c三') charset gbk;
> alter table t modify column c varchar(255) charset utf8mb4;
> alter table t modify column d varchar(255) charset utf8mb4;
> alter table t modify column e varchar(255) charset utf8mb4;
> alter table t modify column f varchar(255) charset utf8mb4;
> alter table t modify column g varchar(255) charset utf8mb4;
> ```

Seems we support those stmt. https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L3928
