### ISSUE TITLE
br: after br restore, tikv used storage is not balance  

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb#31034]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
run oltp_fun_001

### 2. What did you expect to see? (Required)
Restore finished at 18:26. Tikv used should be balance in all nodes.

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/9443637/147431117-e008a9be-90de-43b5-823b-f50facb886b6.png)

### 4. What is your TiDB version? (Required)
/ # /br -V
Release Version: v5.4.0-nightly
Git Commit Hash: 76aae0d5c594f538af62caa883c73188a44170c4
Git Branch: heads/refs/tags/v5.4.0-nightly
Go Version: go1.16.4
UTC Build Time: 2021-12-26 08:07:37
Race Enabled: false

/ # /tidb-server -V
Release Version: v5.4.0-nightly
Edition: Community
Git Commit Hash: 76aae0d5c594f538af62caa883c73188a44170c4
Git Branch: heads/refs/tags/v5.4.0-nightly
UTC Build Time: 2021-12-26 08:09:11
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

Logs and monitor can be get from minio using following testbed name.
endless-oltp--tps-542284-1-875

**Comment by mayjiang0203** [comment]
Seems it is hard to reproduce it. Didn't occur after try 4 times.
![image](https://user-images.githubusercontent.com/9443637/147526576-93bdf83b-5a69-4532-b232-247c80f1d34a.png)

**Comment by YuJuncen** [comment]
I've checked some of metrics. There are some strange things:

1. PD failed to create operator because of `unhealthy` regions. This can be retried after we using the new `ScatterRegions` API.
2. Seems BR sometimes scatters non-empty region.

**Comment by mayjiang0203** [comment]
It occur again, seems still caused by scatter failure.
![image](https://user-images.githubusercontent.com/9443637/148041829-a96dd04a-a8e9-430c-ae0d-573167fb7c5a.png)

**Comment by mayjiang0203** [comment]
Hit it again， and it take user 30 min to balance after br import, so mark it Major.
![image](https://user-images.githubusercontent.com/9443637/149060845-7ec35d55-059e-4d0b-9b30-7dfc1f5decd7.png)

**Comment by YuJuncen** [comment]
Note that v5.4 contains https://github.com/pingcap/tidb/pull/30899, which can probably allay this problem.

https://github.com/pingcap/tidb/pull/31691 would almost fix this problem.
