### ISSUE TITLE
PR #30169 results in 6.1%-6.6% performance regression in read-heavy workloads

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#31036]
## Bug Report

PR https://github.com/pingcap/tidb/pull/30169 results in 6.1%-6.6% performance regression in read-heavy workloads

### 1. Minimal reproduce step (Required)

1. Deploy a cluster with pr https://github.com/pingcap/tidb/pull/30680 
2. Turn on prepare plan cache 
2. Run sysbench oltp_read_only or other read-heavy workloads
3. Deploy a cluster with pr https://github.com/pingcap/tidb/pull/30169
4. Turn on prepare plan cache 
4. Run the same read-heavy workloads
5. Compare the performance of the two bench

### 2. What did you expect to see? (Required)
No performance regression.

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/84501897/147433510-51a9d17b-ca65-4aac-9b3e-4d24304da4b9.png)

![image](https://user-images.githubusercontent.com/84501897/147439067-7e007903-bc2b-4d63-a7fe-f21391ea909a.png)

### 4. What is your TiDB version? (Required)

Commit af259faacfa25d7516920ac4bd976eaeeaabbd82

**Comment by Reminiscent** [comment]
It's an enhancement for plan cache. So I change the tag to feature/developing and enhancement.
