### ISSUE TITLE
optimize util/types/helper.go

### ISSUE THREAD

**Issue by zsy619** [pingcap/tidb#3104]
function strToInt From line 130th to line 135th
code behind:
if str[i] == '-' {
		negative = true
		i++
	} else if str[i] == '+' {
		i++
	}
Can be changed to switch statement:
switch str[i] {
	case '-':
		negative = true
		i++
	case '+':
		i++
	}

**Comment by ngaut** [comment]
Thank you, could you send a PR?

**Comment by zsy619** [comment]
@ngaut what is PR?

**Comment by zhexuany** [comment]
@ngaut I do not think change if statement to switch statement is worth of creating a PR. If you may, just close this issue.

**Comment by yuanwhy** [comment]
@zsy619 PR is Pull Request https://help.github.com/articles/creating-a-pull-request/
