### ISSUE TITLE
lightning: storageDir seems not work

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#31046]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`storageDir` seems not work in code: https://github.com/pingcap/tidb/blob/393415782452903b417a539d7fc8cdcecc6ab1bf/br/pkg/lightning/config/config.go#L956

### 2. What did you expect to see? (Required)
a meaningful usage.
### 3. What did you see instead (Required)
storageDir did nothing.
### 4. What is your TiDB version? (Required)

master

**Comment by gozssky** [comment]
`storageSizeDir = filepath.Dir(storageSizeDir)` is useless here now.
It seems the original author wants to gets storage's capacity and available size even if the directory doesn't exist. However, we always create  the directory first and then check its size.
