### ISSUE TITLE
lightning: removeOneJob seems not used

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#31047]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
code removeOneJob not used :https://github.com/pingcap/tidb/blob/b266d7d57424812404b27bf35c0b27c75f235e99/br/pkg/lightning/restore/checksum.go#L219
should use it after addOneJob succeed in code : https://github.com/pingcap/tidb/blob/b266d7d57424812404b27bf35c0b27c75f235e99/br/pkg/lightning/restore/checksum.go#L330

### 4. What is your TiDB version? (Required)
master

**Comment by gozssky** [comment]
https://github.com/pingcap/tidb/blob/abb65829101d2f19b69b4e5a4dd0471dbed05915/br/pkg/lightning/restore/checksum.go#L132-L137

🤔

**Comment by glorv** [comment]
@gozssky We should do the same defer call at https://github.com/pingcap/tidb/blob/abb65829101d2f19b69b4e5a4dd0471dbed05915/br/pkg/lightning/restore/checksum.go#L328-L336
