### ISSUE TITLE
Consider make rule `location_labels` be empty

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#31052]
## Background

As issue https://github.com/tikv/pd/issues/4467 shown, creating placement rule by DDL will set the  `location_labels` be `region,zone,rack,host` in default. but the TiKV labels may not guarantee the relevant label hierarchy, which leads to un-expect scheduling.
```
 {
    "group_id": "TiDB_DDL_65",
    "id": "partition_rule_65_0",
    "index": 2,
    "start_key": "7480000000000000ff4100000000000000f8",
    "end_key": "7480000000000000ff4200000000000000f8",
    "role": "voter",
    "count": 3,
    "label_constraints": [
      {
        "key": "region",
        "op": "in",
        "values": [
          "us-west1"
        ]
      },
      {
        "key": "engine",
        "op": "notIn",
        "values": [
          "tiflash"
        ]
      }
    ],
    "location_labels": [
      "region",
      "zone",
      "rack",
      "host"
    ],
    "version": 1
  },
```
## Proposal

make  `location_labels` be empty,  it's more like an undefined behavior, we may consider deleting the filed `location_labels` in the rule later, and make it is affected by a global setting `location labels`. and  `empty` more friendly for the compatibility issue.

**Comment by nolouch** [comment]
ptal @xhebox @morgo @disksing

**Comment by xhebox** [comment]
I would like to see that, probably make `isolationLevel` global too. That makes much more sense to me than setting them in every single rule.

**Comment by disksing** [comment]
Good idea. I would like to add a situation. When `location_labels: []` is set, the rule does not take location isolation into consideration.
