### ISSUE TITLE
high cpu usage from reArrangeFallback of execution on apply operator

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#31065]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run a query with heavy Apply operator(nested loop join)

### 2. What did you expect to see? (Required)

high cpu usage from reArrangeFallback

### 3. What did you see instead (Required)

![image](https://user-images.githubusercontent.com/2316425/147519127-742201a9-f37d-404c-b650-074ee35f33c2.png)

### 4. What is your TiDB version? (Required)

v5.3.0

**Comment by ichn-hu** [comment]
duplicaetd with https://github.com/pingcap/tidb/issues/30353
