### ISSUE TITLE
rename column fail when doing column type change concurrently

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#31075]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t(a int, b int);
insert into t values (1, 1);
alter table t change column b b double; /* in session 1 */
alter table t rename column b to c;     /* in session 2 */
```

### 2. What did you expect to see? (Required)
No error.
### 3. What did you see instead (Required)
![origin_img_v2_056ed67a-b47c-4be5-9088-b4ce11349b1g](https://user-images.githubusercontent.com/17380469/147538277-0afb7b60-5042-4335-a863-258222afb1d0.png)

### 4. What is your TiDB version? (Required)
mater

**Comment by yudongusa** [comment]
@bb7133 assign to you for now.

**Comment by xhebox** [comment]
@wjhuang2016 Is there any plan to fix it recently?

**Comment by wjhuang2016** [comment]
No
