### ISSUE TITLE
alter column set default wrongly modify information_schema 

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#31074]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Modify code the make alter column slow.

![origin_img_v2_91b72c02-323a-4a78-8360-9e5488eceabg](https://user-images.githubusercontent.com/17380469/147537707-39a3f9fb-d351-40a9-8bcb-b65a086ea3bb.png)

### 2. What did you expect to see? (Required)
default 17

### 3. What did you see instead (Required)
default 18
### 4. What is your TiDB version? (Required)
master

**Comment by yudongusa** [comment]
@bb7133 assign this to you first.
