### ISSUE TITLE
Performance regression in pr/31072

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#31112]
## Enhancement

This is detected by https://github.com/pingcap/tidb/issues/25754

See the result here http://www.zenlife.tk:18081/alloc

![image](https://user-images.githubusercontent.com/1420062/147631909-08051330-beae-427a-a4c5-91a497ab69b9.png)

Verify it manually:

```
cd session;
go test -run TestXXX -bench BenchmarkCompileExecutePreparedStmt   -benchmem  -cpuprofile  cpu.out -memprofile mem.out  -benchtime 30s
```

Before:
```
BenchmarkCompileExecutePreparedStmt-16            102976            373211 ns/op          380850 B/op       2784 allocs/op
```

After:
```
BenchmarkCompileExecutePreparedStmt-16             93780            406044 ns/op          405387 B/op       3113 allocs/op
```

It introduce 11.8% extra allocation, and slightly slow down the ops

```
go tool pprof -http=:6060 -alloc_objects mem.out
```

![image](https://user-images.githubusercontent.com/1420062/147632044-0601060d-313c-429d-afaa-97feb7cfa592.png)

Caused by this line https://github.com/pingcap/tidb/pull/31072/files#diff-bca2046fd17f493604dd1124ab98d60de4aa21e57135324e365eb33e68b74f43R261

@xuyifangreeneyes

**Comment by xuyifangreeneyes** [comment]
`CollectColumnStatsUsage` increases some cost on sql optimization. The extra memory allocation comes from the `{tblID, colID} -> Column.UniqueID` map, which is relatively large if the table has many columns. I haven't come up with a good solution. #30816 will introduce a switch for `CollectColumnStatsUsage` and we will consider whether to turn the switch off by default.

**Comment by tiancaiamao** [comment]
It's disabled temporarily, so the regression is gone.

![image](https://user-images.githubusercontent.com/1420062/153787503-0d3b127b-df15-4631-a8d4-a867e228e991.png)
