### ISSUE TITLE
IndexNestedLoopHashJoin send on closed channel

### ISSUE THREAD

**Issue by ichn-hu** [pingcap/tidb#31129]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

the reproduce can be done by https://github.com/pingcap/tidb/pull/31128

checkout the code and run

```
make failpoint-enable
cd executor
go test -check.f TestIndexNestedLoopHashJoin > test.result
```

### 2. What did you expect to see? (Required)

no panic

### 3. What did you see instead (Required)

https://github.com/pingcap/tidb/blob/a5bbee9a7168c4070911def85a71f7e5bb6ef0ff/executor/test.result#L261

the reason for this panic is because if the result needs to be ordered and it got any error during `doJoinInOrder`

![image](https://user-images.githubusercontent.com/29735669/147644271-093d5d7c-7208-41f0-9ce4-69f3cf19266b.png)

the resultCh will be closed

however in indexHashJoinInnerWorker

![image](https://user-images.githubusercontent.com/29735669/147644406-477801fd-09ba-4d0b-997e-9e4e23d575f8.png)

the returned error will be sent to the resultCh which is already closed, causing the panic.

### 4. What is your TiDB version? (Required)

master

**Comment by yudongusa** [comment]
@XuHuaiyu assign this to you for now,
