### ISSUE TITLE
Do not retry for truncate error

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#3117]
When we meet truncate error in DML. We should not retry the statement.

**Comment by coocood** [comment]
@shenli 
I think this is an issue of `loader`.
https://github.com/pingcap/tidb-tools/blob/master/loader/db.go#L63

**Comment by coocood** [comment]
@shenli 
Added issue in tidb-tools
https://github.com/pingcap/tidb-tools/issues/114
