### ISSUE TITLE
`LIKE` does not work as expected for utf8_general_ci strings

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#31174]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
drop table if exists t;
create table t(a char(4) collate utf8_general_ci primary key /*T![clustered_index] clustered */);
insert into t values("`?");
explain select * from t where a like "`%";
select * from t where a like "`%";
```

### 2. What did you expect to see? (Required)

```console
+----+
| a  |
+----+
| `? |
+----+
```

### 3. What did you see instead (Required)

```sql
mysql> explain select * from t where a like "`%";
+-------------+---------+------+---------------+---------------+
| id          | estRows | task | access object | operator info |
+-------------+---------+------+---------------+---------------+
| TableDual_5 | 0.00    | root |               | rows:0        |
+-------------+---------+------+---------------+---------------+
1 row in set (0.00 sec)

mysql> select * from t where a like "`%";
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

8a83d01ac

**Comment by tangenta** [comment]
The root cause is the incorrect way to build range for pattern matching `%` in `LIKE`:

https://github.com/pingcap/tidb/blob/321d307f3b23877fb2be0e7534a9ecd6a655be05/util/ranger/points.go#L688-L705

This algorithm constructs the range in byte-level: for example, `ab%` is mapped to `[ab, ac]` by adding `1` to the last byte. However, this is incorrect for non-binary collation strings because the **sort key order** is not the same as **byte order**.

In this issue,  `` `% `` is mapped to the range `` [`, a] ``(where `` ` `` is `0x60` and `a` is `0x61`). Because the collation `utf8_general_ci` is case-insensitive, `a` and `A` have the same sort key. Finally, the range is like `` [`, A] `` which is actually an empty range.

**Comment by tangenta** [comment]
The reproduce conditions:
1. The `LIKE` operator is used. 
1. Pattern match syntax `%` is used.
1. The column type is non-binary collation string.
1. A boundary char of 2 ranges like "`" is used.

@aytrack Since this is a corner case bug, I prefer not to tag it with "severity/critical".

**Comment by aytrack** [comment]
degree to major since the 4th condition is a corner case.
