### ISSUE TITLE
Wrong result because of wrong table scan range

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#31216]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table if exists tbl_2;
    create table tbl_2 ( col_20 bigint not null , col_21 smallint not null , col_22 decimal(24,10) default null , col_23 tinyint default 71 not null , col_24 bigint not null , col_25 tinyint default 18 , col_26 varchar(330) collate utf8_bin not null , col_27 char(77) collate                    utf8mb4_unicode_ci , col_28 char(46) collate utf8_general_ci not null , col_29 smallint unsigned not null , primary key idx_13 ( col_27(5) ) , key idx_14 ( col_24 ) , unique key idx_15 ( col_23,col_21,col_28,col_29,col_24 ) ) collate utf8_bin ;
    insert ignore into tbl_2 values ( 5888267793391993829,5371,94.63,-109,5728076076919247337,89,'WUicqUTgdGJcjbC','SapBPqczTWWSN','xUSwH',49462 );
    select col_25 from tbl_2 where ( tbl_2.col_27 > 'nSWYrpTH' or not( tbl_2.col_27 between 'CsWIuxlSjU' and 'SfwoyjUEzgg' ) ) and ( tbl_2.col_23 <= -95);

### 2. What did you expect to see? (Required)

MySQL 8.0.23

    mysql> select col_25 from tbl_2 where ( tbl_2.col_27 > 'nSWYrpTH' or not( tbl_2.col_27 between 'CsWIuxlSjU' and 'SfwoyjUEzgg' ) ) and ( tbl_2.col_23 <= -95);
    +--------+
    | col_25 |
    +--------+
    |     89 |
    +--------+
    1 row in set (0.00 sec)
### 3. What did you see instead (Required)

    mysql>     select col_25 from tbl_2 where ( tbl_2.col_27 > 'nSWYrpTH' or not( tbl_2.col_27 between 'CsWIuxlSjU' and 'SfwoyjUEzgg' ) ) and ( tbl_2.col_23 <= -95);
    Empty set (0.00 sec)
### 4. What is your TiDB version? (Required)

    mysql> select tidb_version();
    +----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | tidb_version()
                              |
    +----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Release Version: v5.4.0-alpha-580-g072561c85b
    Edition: Community
    Git Commit Hash: 072561c85b92f253b84452f055d878b2df098980
    Git Branch: master
    UTC Build Time: 2021-12-31 05:52:02
    GoVersion: go1.16.4
    Race Enabled: false
    TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
    Check Table Before Drop: false |
    +----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    1 row in set (0.01 sec)

**Comment by guo-shaoge** [comment]
Looks like the range of `TableRangeScan_5` is wrong. It didn't consider the the range of `tbl_2.col_27 > 'nSWYrpTH'`, which makes the output number of `TableRangeScan_5` is 0(should be 1).


    mysql> explain select col_25 from tbl_2 where ( tbl_2.col_27 > 'nSWYrpTH' or not( tbl_2.col_27 between 'CsWIuxlSjU' and 'SfwoyjUEzgg' ) ) and ( tbl_2.col_23 <= -95);
    +----------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
    | id                         | estRows | task      | access object | operator info                                                                                                                                    |
    +----------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
    | Projection_4               | 2212.23 | root      |               | test.tbl_2.col_25                                                                                                                                |
    | └─TableReader_7            | 2212.23 | root      |               | data:Selection_6                                                                                                                                 |
    |   └─Selection_6            | 2212.23 | cop[tikv] |               | le(test.tbl_2.col_23, -95), or(gt(test.tbl_2.col_27, "nSWYrpTH"), or(lt(test.tbl_2.col_27, "CsWIuxlSjU"), gt(test.tbl_2.col_27, "SfwoyjUEzgg"))) |
    |     └─TableRangeScan_5     | 6656.67 | cop[tikv] | table:tbl_2   | range:[-inf,"CsWIu"], ["Sfwoy",+inf], keep order:false, stats:pseudo                                                                             |
    +----------------------------+---------+-----------+---------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
    4 rows in set (0.01 sec)

**Comment by winoros** [comment]
You should forget to open new collation by setting `new_collations_enabled_on_first_bootstrap` in the config to`true`.

**Comment by yudongusa** [comment]
@wjhuang2016 assign this to you as you have been fixing it.
