### ISSUE TITLE
TIDB v3.1.1 update configuration failed

### ISSUE THREAD

**Issue by zhangzhao0827** [pingcap/tidb#31217]
## Ask a Question
Please answer these questions before submitting your issue. Thanks!
### TIDB v3.1.1 update configuration failed
Failed to execute  `ansible-playbook rolling_update.yml --tags=pd,tikv`
error message：
`playbook: rolling_update.yml; TASK: check_config_tikv : Create configuration file; message: {"changed": false, "msg": "AttributeError: `
![image](https://user-images.githubusercontent.com/41892552/147807514-89c88c2f-fea4-4a3e-bee6-3cab73a06665.png)

**Comment by jebter** [comment]
The lifecycle of version 4.0 and earlier has ended. Let's close it. https://www.pingcap.com/tidb-release-support-policy/
