### ISSUE TITLE
lightning ignore-data-column should be placed after parser

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#31224]
lightning v5.3.0

import file type is parquet.10 columns in parquet. 11 columns in tidb table and all columns has default value.

 i know have a error-format column in parquet and i want ignore it.so i use mydumper.ignore-data-columns configuration

but i got a error `parquet.parser error`: 
![image](https://user-images.githubusercontent.com/21033020/147810634-0c0a4887-dbd4-4947-a383-b3be1d7d44bf.png)

**Comment by niubell** [comment]
It seems like the reason is the same with #31222, wo should support correct parse of `bool` type and transform it to 0/1 that TiDB is able to handle.
