### ISSUE TITLE
It is recommended that lightning convert the bool type of parquet to 0/1

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#31222]
lightning v5.3.0

After the content in parquet may be written by spark, the definition of bool is true or false. Regenerating the parquet file takes time, In tidb, bool behaves as tinyint, so proper type conversion will help improve the success rate of lightning import

parquet file：
![image](https://user-images.githubusercontent.com/21033020/147809823-214dcb34-0e10-4566-aa75-2109c0525144.png)

error：
![image](https://user-images.githubusercontent.com/21033020/147809929-cb84aec1-de1f-4a83-afc0-922c3c241aeb.png)

**Comment by yudongusa** [comment]
@XuHuaiyu assign this to you first.

**Comment by XuHuaiyu** [comment]
@kennytm PTAL, this seems to be an issue related to lightning.

**Comment by kennytm** [comment]
@glkappe  are those "true" and "false" being written as literal strings in  the Parquet file? if so there's no way Lightning can convert those non-integer strings into integers without special-casing the TiDB type conversion routine.

**Comment by glorv** [comment]
`bool` is a primary type in parquet-format. See: https://github.com/apache/parquet-format#types. We just doesn't support handle this type currently. 😂

**Comment by kennytm** [comment]
in principle adding a case for `bool` here is sufficient. 
https://github.com/pingcap/tidb/blob/3c797fdc64b82a8c7ec6897df2836a1324f26735/br/pkg/lightning/mydump/parquet_parser.go#L406

**Comment by Suha652** [comment]
/
