### ISSUE TITLE
CTE doesn't handle apply properly

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#31255]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

    drop table if exists t1, t2;
    create table t1(c1 int, c2 int);
    insert into t1 values(2, 1);
    insert into t1 values(2, 2);
    create table t2(c1 int, c2 int);
    insert into t2 values(1, 1);
    insert into t2 values(3, 2);
    select * from t1 where c1 > all(with cte1 as (select c1 from t2 where t2.c2 = t1.c2) select c1 from cte1);

### 2. What did you expect to see? (Required)

    mysql>     select * from t1 where c1 > all(with cte1 as (select c1 from t2 where t2.c2 = t1.c2) select c1 from cte1);
    +------+------+
    | c1   | c2   |
    +------+------+
    |    2 |    1 |
    +------+------+
### 3. What did you see instead (Required)

    mysql>     select * from t1 where c1 > all(with cte1 as (select c1 from t2 where t2.c2 = t1.c2) select c1 from cte1);
    +------+------+
    | c1   | c2   |
    +------+------+
    |    2 |    1 |
    |    2 |    2 |
    +------+------+
    2 rows in set (0.00 sec)
### 4. What is your TiDB version? (Required)
master

**Comment by wjhuang2016** [comment]
It's a corner case and only happens when CTE is on the inner side.
