### ISSUE TITLE
mysql test `row` failed.

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#31273]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select (1,2,(3,4)) IN ((3,2,(3,4)), (1,2,(3,4)));
```
### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
Operand should contain 2 column(s)
### 4. What is your TiDB version? (Required)
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/7946/pipeline/86/
master

**Comment by yudongusa** [comment]
@wjhuang2016 assign this to you as you are working on the fix.
