### ISSUE TITLE
Something goes wrong when start TiKV.

### ISSUE THREAD

**Issue by follitude** [pingcap/tidb#3129]
os: Ubuntu 16.04 
go version: 1.8
standalone mode.

According to the doc, I used the 4 commands to deploy TiDB. 
when I executed the second command to start TiKV, something went wrong.
There are somethings in tikv.log.

...

2017/04/24 21:57:27.241 client.rs:175: [WARN] failed to get cluster id from pd: Other(StringError("PD cluster stop responding"))
2017/04/24 21:57:28.242 client.rs:175: [WARN] failed to get cluster id from pd: Other(StringError("PD cluster stop responding"))
2017/04/24 21:57:29.243 client.rs:175: [WARN] failed to get cluster id from pd: Other(StringError("PD cluster stop responding"))
2017/04/24 21:57:39.695 panic_hook.rs:85: [ERROR] thread 'main' panicked 'called `Result::unwrap()` on an `Err` value: Other(StringError("failed to get cluster id from pd"))' at "/buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:868"
stack backtrace:
   0:     0x556bae010e5e - backtrace::backtrace::libunwind::trace
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace<closure>
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x556bae011503 - backtrace::capture::{{impl}}::new
                        at /home/jenkins/.target/release/build/backtrace-811cded9ab5b8ade/out/capture.rs:79
   2:     0x556badac5f17 - tikv::util::panic_hook::set_exit_hook::{{closure}}
                        at /home/jenkins/workspace/TIKV_POST_COMMIT_FLOW/go/src/github.com/pingcap/tikv/src/util/panic_hook.rs:84
   3:     0x556bae0f8378 - std::panicking::rust_panic_with_hook
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:546
   4:     0x556bae0f81f4 - std::panicking::begin_panic<collections::string::String>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:507
   5:     0x556bae0f8169 - std::panicking::begin_panic_fmt
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:491
   6:     0x556bae0f80f7 - std::panicking::rust_begin_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:467
   7:     0x556bae12546d - core::panicking::panic_fmt
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/panicking.rs:69
   8:     0x556bad9c8bea - core::result::unwrap_failed<tikv::pd::errors::Error>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:29
   9:     0x556bada59c8b - core::result::{{impl}}::unwrap<tikv::pd::client::RpcClient,tikv::pd::errors::Error>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/result.rs:745
                         - tikv_server::main
                        at /home/jenkins/workspace/TIKV_POST_COMMIT_FLOW/go/src/github.com/pingcap/tikv/src/bin/tikv-server.rs:900
  10:     0x556bae0ff50a - panic_unwind::__rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  11:     0x556bae0f8b16 - std::panicking::try<(),fn()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:429
                         - std::panic::catch_unwind<fn(),()>
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                         - std::rt::lang_start
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  12:     0x7f17b9bdf82f - __libc_start_main
  13:     0x556bad968f2d - <unknown>
  14:                0x0 - <unknown>

**Comment by shenli** [comment]
@follitude Thanks for your feedback. It seems that your pd-server is not running corrected. Please check the log of pd-server.

**Comment by follitude** [comment]
@shenli Here is my pd.log. Is there anything wrong, and how do I fix it?

2017/04/24 21:54:43 util.go:55: [info] Welcome to Placement Driver (PD).
2017/04/24 21:54:43 util.go:56: [info] Version:
2017/04/24 21:54:43 util.go:57: [info] Git Commit Hash: 7228945e967b406539a0501325aaeec7aae4b79d
2017/04/24 21:54:43 util.go:58: [info] UTC Build Time:  2017-04-19 05:57:54
2017/04/24 21:54:43 metricutil.go:83: [info] disable Prometheus push client 
2017/04/24 21:54:43 server.go:108: [info] PD config - Config({FlagSet:0xc420214420 Version:false ClientUrls:http://127.0.0.1:2379 PeerUrls:http://127.0.0.1:2380 AdvertiseClientUrls:http://127.0.0.1:2379 AdvertisePeerUrls:http://127.0.0.1:2380 Name:pd DataDir:pd InitialCluster:pd=http://127.0.0.1:2380 InitialClusterState:new Join: LeaderLease:3 LogLevel:info LogFile:pd.log TsoSaveInterval:3s Metric:{PushJob:pd PushAddress: PushInterval:0s} Schedule:{MaxSnapshotCount:3 MaxStoreDownTime:1h0m0s LeaderScheduleLimit:1024 RegionScheduleLimit:12 ReplicaScheduleLimit:16} Replication:{MaxReplicas:3 LocationLabels:[]} QuotaBackendBytes:0 AutoCompactionRetention:1 nextRetryDelay:1000000000 disableStrictReconfigCheck:false tickMs:500 electionMs:3000 configFile:})
2017/04/24 21:54:43 server.go:135: [info] start embed etcd 
2017/04/24 21:54:43 util.go:268: [info] I | embed: [listening for peers on  http://127.0.0.1:2380]
2017/04/24 21:54:43 util.go:268: [info] I | embed: [pprof is enabled under /debug/pprof]
2017/04/24 21:54:43 util.go:268: [info] I | embed: [listening for client requests on  127.0.0.1:2379]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [name = pd]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [data dir = pd]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [member dir = pd/member]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [heartbeat = 500ms]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [election = 3000ms]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [snapshot count = 100000]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [advertise client URLs = http://127.0.0.1:2379]
2017/04/24 21:54:43 util.go:268: [info] I | etcdserver: [restarting member b71f75320dc06a6c in cluster 1c45a069f3a1d796 at commit index 561]
2017/04/24 21:54:43 util.go:268: [info] I | raft: [b71f75320dc06a6c became follower at term 3]
2017/04/24 21:54:43 util.go:268: [info] I | raft: [newRaft b71f75320dc06a6c [peers: [], term: 3, commit: 561, applied: 0, lastindex: 561, lastterm: 3]]
2017/04/24 21:54:43 util.go:264: [warning] W | auth: [simple token is not cryptographically signed]
2017/04/24 21:54:44 util.go:268: [info] I | etcdserver: [starting server... [version: 3.2.0+git, cluster version: to_be_decided]]
2017/04/24 21:54:44 util.go:268: [info] I | etcdserver/membership: [added member b71f75320dc06a6c [http://127.0.0.1:2380] to cluster 1c45a069f3a1d796]
2017/04/24 21:54:44 util.go:266: [info] N | etcdserver/membership: [set the initial cluster version to 3.2]
2017/04/24 21:54:44 util.go:268: [info] I | etcdserver/api: [enabled capabilities for version 3.2]
2017/04/24 21:54:44 server.go:153: [info] create etcd v3 client with endpoints [http://127.0.0.1:2379]
2017/04/24 21:54:45 util.go:268: [info] I | raft: [b71f75320dc06a6c is starting a new election at term 3]
2017/04/24 21:54:45 util.go:268: [info] I | raft: [b71f75320dc06a6c became candidate at term 4]
2017/04/24 21:54:45 util.go:268: [info] I | raft: [b71f75320dc06a6c received MsgVoteResp from b71f75320dc06a6c at term 4]
2017/04/24 21:54:45 util.go:268: [info] I | raft: [b71f75320dc06a6c became leader at term 4]
2017/04/24 21:54:45 util.go:268: [info] I | raft: [raft.node: b71f75320dc06a6c elected leader b71f75320dc06a6c at term 4]
2017/04/24 21:54:45 util.go:268: [info] I | etcdserver: [published {Name:pd ClientURLs:[http://127.0.0.1:2379]} to cluster 1c45a069f3a1d796]
2017/04/24 21:54:45 util.go:268: [info] I | embed: [ready to serve client requests]
2017/04/24 21:54:45 util.go:266: [info] N | embed: [serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!]
2017/04/24 21:54:45 etcdutil.go:141: [warning] check etcd http://127.0.0.1:2379 status, resp: &{cluster_id:2037210783374497686 member_id:13195394291058371180 revision:553 raft_term:4  3.2.0+git 94208 13195394291058371180 563 4}, err: <nil>, cost: 1.429682119s
2017/04/24 21:54:45 server.go:193: [info] init cluster id 6412559700167079489
2017/04/24 21:54:45 leader.go:72: [warning] leader is still name:"pd" member_id:13195394291058371180 peer_urls:"http://127.0.0.1:2380" client_urls:"http://127.0.0.1:2379" , resign and campaign again
2017/04/24 21:54:45 tso.go:106: [info] sync and save timestamp: last 2017-04-24 21:54:25.710954495 +0800 CST save 2017-04-24 21:54:48.515211367 +0800 CST
2017/04/24 21:54:45 leader.go:209: [info] PD cluster leader pd is ready to serve

**Comment by follitude** [comment]
@shenli yep, on the same machine. Is that wrong?

**Comment by shenli** [comment]
@follitude May I have the command that you start the tikv-server?

**Comment by follitude** [comment]
@shenli The command I use:
./bin/tikv-server --pd="127.0.0.1:2379" --store=tikv --log-file=tikv.log
And here is the version details:
Git Commit Hash: 9bbb312acd583aa8926ad0dfd5ac514bf2abbff1
UTC Build Time:  2017-03-27 12:17:06
Rustc Version:   1.17.0-nightly (ba7cf7cc5 2017-02-11)
