### ISSUE TITLE
function found_rows() return wrong value

### ISSUE THREAD

**Issue by ueizhou** [pingcap/tidb#3131]
after select statement, select found_row() return wrong value. for example:
(1) select * from <table_name> // return n rows, n > 0
(2) select found_rows(); // should return n, but 0

**Comment by zhexuany** [comment]
@ueizhou It is kinda late ask you providing a reproduce guide. But I think it is worth to do so. Especially, your PR did not give any tests.

**Comment by ueizhou** [comment]
@zhexuany
reproduce:
create table test (id int);
insert into test values(1),(2);
select * from test;
select found_rows(); // correct value is 2, but return 0
select found_rows(); // correct value is 1, but return 0

I will provide testcases tonight.
Thanks for your suggestions!

**Comment by zhexuany** [comment]
@ueizhou sometime but fixed can come with no tests case changes. For your case, it should categorize into this. For now, our test only test a query is succeed or failed. We did not check the return value. Adding such test case may cost a lot. You can explain this in your PR or you can try to add test cases but it could be very difficult.

**Comment by ueizhou** [comment]
@zhexuany
That's it! The full tests need NewServer() as in tidb_test.go, I finished locally. But it makes buildin_info_test.go too complex. I'm thinking about a simpler way:)
