### ISSUE TITLE
Publish or remove Top SQL variables

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#31433]
## Enhancement

According to an accepted RFC https://github.com/pingcap/tidb/blob/master/docs/design/2021-07-29-hidden-sysvars.md we should consider removing Top SQL related hidden variables. Previously these hidden variables are hidden mainly for their advanced usages. As suggested in the RFC, these hidden variables should be either carefully checked and then release to the public, or removed.

My suggestion is:

| Variable | Action |
|---------|-------|
| tidb_top_sql_precision_seconds | Remove from the variable, as changing it is very likely to cause problems |
| tidb_top_sql_max_statement_count | Rename to reduce ambiguity + Public: tidb_top_sql_max_time_series_count |
| tidb_top_sql_max_collect | Rename to reduce ambiguity + Public: tidb_top_sql_max_meta_count |
| tidb_top_sql_report_interval_seconds | Remove from the variable, as changing it is very likely to cause problems |

**Comment by morgo** [comment]
Suggestions LGTM. When you do remove (or rename), there is now a feature called 'removed variables' which helps ease compatibility better: https://github.com/pingcap/tidb/pull/28931
