### ISSUE TITLE
TiDB digester generates different plan digests for the same plan

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#31437]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Execute the sysbench select_random_ranges workload:

```
sysbench --config-file=sysbench_config --threads=4 --table-size=1000000 select_random_ranges run
```

which effectively executes the following SQL statement:

```sql
SELECT
  count (`k`)
FROM
  `sbtest1`
WHERE
  `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
  OR `k` BETWEEN ?
  AND ?
```

### 2. What did you expect to see? (Required)

Only one execution plan for this statement can be observed.

### 3. What did you see instead (Required)

There are multiple plans:

Plan 1: c87966...

<img width="577" alt="image" src="https://user-images.githubusercontent.com/1916485/148484142-4d708264-4cf4-4e68-b2a7-ee5077d51da7.png">

Plan 2: de7a52...

<img width="596" alt="image" src="https://user-images.githubusercontent.com/1916485/148484166-c786b3d9-4ad6-4757-adde-7cd95db0e69c.png">

### 4. What is your TiDB version? (Required)

v5.4.0.

**Comment by crazycs520** [comment]
this issue is same with https://github.com/pingcap/tidb/issues/31438
