### ISSUE TITLE
Top SQL failed to report short DDL executions

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#31434]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I executed several short DDL statements, as:
<img width="334" alt="image" src="https://user-images.githubusercontent.com/1916485/148482446-418b559a-0f8f-4438-8e54-7414ee90a3a7.png">

which is an index creation for a table-size = 100000 created by sysbench.

### 2. What did you expect to see? (Required)

I can see these executed DDL in the UI dashboard, since they take several seconds to finish.

### 3. What did you see instead (Required)

According to the UI dashboard, TiDB does not report any DDL executed in several seconds:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/1916485/148482507-838b50a2-856b-4255-88bc-d63ad78de7a4.png">

### 4. What is your TiDB version? (Required)

v5.4.0

**Comment by crazycs520** [comment]
I can't reproduce this...

**Comment by breeswish** [comment]
Fixed by #33132
