### ISSUE TITLE
Normalized plan is not following the same format

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#31438]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Execute any workload with a coprocessor push down.

### 2. What did you expect to see? (Required)

For the normalized plan, we should know that the push down happens for TiKV or TiFlash, like:

```
	StreamAgg_17           	root     	...
	└─IndexReader_18       	root     	...
	  └─StreamAgg_9        	cop[tikv]	...
	    └─IndexRangeScan_16	cop[tikv]	...
```

### 3. What did you see instead (Required)

No TiKV or TiFlash push down information is included in the normalized plan:

```
	StreamAgg           	root	funcs:count(?)->?
	└─IndexReader       	root	index:StreamAgg_9
	  └─StreamAgg       	cop 	funcs:count(test.sbtest1.k)->?
	    └─IndexRangeScan	cop 	table:sbtest1, index:k_1(k), range:[?,?], keep order:false
```

Note that this is not the first time that a plan output is not displayed in the same way:

https://github.com/pingcap/tidb/issues/28731

### 4. What is your TiDB version? (Required)

v5.4.0

**Comment by crazycs520** [comment]
The expected result should be:

```
	StreamAgg           	root	funcs:count(?)->?
	└─IndexReader       	root	index:StreamAgg
	  └─StreamAgg       	cop[tikv] 	funcs:count(test.sbtest1.k)->?
	    └─IndexRangeScan	cop[tikv] 	table:sbtest1, index:k_1(k), range:[?,?], keep order:false
```

And since the `IndexReader` will always has 1 child, so the expected result can be:

```
	StreamAgg           	root	funcs:count(?)->?
	└─IndexReader       	root
	  └─StreamAgg       	cop[tikv] 	funcs:count(test.sbtest1.k)->?
	    └─IndexRangeScan	cop[tikv] 	table:sbtest1, index:k_1(k), range:[?,?], keep order:false
```

**Comment by crazycs520** [comment]
The plan with different cop task should has different plan digest , This PR https://github.com/pingcap/tidb/pull/20054 fix it.
