### ISSUE TITLE
log.slow-threshold seems not take effects

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#31466]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
v5.4.0
log.slow-threshold      300

### 3. What did you see instead (Required)
<img width="1277" alt="截屏2022-01-07 下午9 50 41" src="https://user-images.githubusercontent.com/53471087/148558360-e1b98c47-0e1c-4f7c-9d83-8f062c4219c4.png">

### 4. What is your TiDB version? (Required)

["Git Commit Hash"=a1cb65cb11600d38bad29a428741caf05426ca01]

**Comment by seiya-annie** [comment]
[all_config.txt](https://github.com/pingcap/tidb/files/7829427/all_config.txt)

**Comment by crazycs520** [comment]
Since the TiDB `log.level` is `debug`, so TiDB will awaly log out slow log. 

This behavior is introduce by this PR: https://github.com/pingcap/tidb/pull/30461
