### ISSUE TITLE
limit语句导致查询不走索引问题

### ISSUE THREAD

**Issue by lookhua** [pingcap/tidb#31462]
## General Question

EXPLAIN ANALYZE
SELECT
  RES.*
FROM
  ACT_HI_VARINST RES  -- USE INDEX(ACT_IDX_HI_PROCVAR_PROC_INST)
WHERE
  RES.PROC_INST_ID_ = '4a138302e3c84415b5f2b2880200b1c4'
ORDER BY
  RES.ID_ ASC 
LIMIT
  2147483647 OFFSET 0

  RES.PROC_INST_ID_ 上面有索引，但是执行计划里面显示走 主键索引，导致查询特别慢

**Comment by lookhua** [comment]
tidb 4.0.15

**Comment by TonsnakeLin** [comment]
What's the definition of table ACT_HI_VARINST  and the explain info for this sql
