### ISSUE TITLE
primary key conflict after updating non-unique keys

### ISSUE THREAD

**Issue by shaoxiqian** [pingcap/tidb#31503]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set @a='1';
set @e='ccc';
prepare stmt from 'SELECT * from ttt where t1=? and t2=?and t3=? and t4=? for update';
execute stmt using  @a, @a, @a, @a;
prepare stmt1 from 'update ttt set t1=? and t2=?and t3=? and t4=? and t5=? where t1=? and t2=?and t3=? and t4=?';
execute stmt1 using  @a, @a, @a, @a,@e,@a, @a, @a, @a;

https://github.com/pingcap/tidb/commits/release-5.3-20220107 

### 2. What did you expect to see? (Required)
update successfully
### 3. What did you see instead (Required)
Duplicate entry '3301000760000102408-ACII-T0000-II' for key 'tablename_i0'
### 4. What is your TiDB version? (Required)
https://github.com/pingcap/tidb/commits/release-5.3-20220107

**Comment by hawkingrei** [comment]
@shaoxiqian What is the table structure of ```ttt``` ?

**Comment by AilinKid** [comment]
seem as https://github.com/pingcap/tidb/issues/31495, closed
