### ISSUE TITLE
lightning: parallel importing with `incremental-import=false` causes incorrect duplicate rows

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#31515]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Prepare two tidb-lightning nodes and one empty tidb node,
2. Prepare two data sources , and one of them has duplicate rows,
3. Use tidb-lightning nodes  to parallelly import data , with `incremental-import=false` config,
4. Wait for importing, then execute  `select count(task_id) from lightning_task_info.conflict_error_v1` in tidb.
### 2. What did you expect to see? (Required)
1. Import sucessfully
2. Query result is 2x
### 3. What did you see instead (Required)
1. Import sucessfully
2. Query result is not equal to 2x
### 4. What is your TiDB version? (Required)
5.4.0

**Comment by gozssky** [comment]
Parallel importing relies on incremental-import. So `incremental-import` must be set to true. This will be documented in v5.4.0.

**Comment by sunzhaoyang** [comment]
Has described here: https://github.com/pingcap/docs-cn/pull/8129/files
