### ISSUE TITLE
invalid input value: Utf8Error { valid_up_to: 1, error_len: Some(1) }

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#31558]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in CI https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_integration-copr-test/detail/tikv_ghpr_integration-copr-test/1617/pipeline/
1. deploy a cluster with tikv
2. insert the test data and executing the sql
```sql
SELECT ( `col_tinyint` / -20307 ) - 11371 AS field1, SUBSTR( '02:49:29.056147' FROM ( ELT( ( 'l' >> `col_smallint_unsigned` ), ( POSITION( NULL IN ( ( ~ `col_tinyint_unsigned` ) NOT RLIKE `col_smallint_unsigned_key` ) ) ), NULL ) ) FOR `col_smallint_unsigned_key` ) AS field2 FROM `table20_int_autoinc` WHERE SUBSTR( ( CHAR( ( HEX( '1982-11-22 03:42:59.058504' ) ) USING latin1 ) ) FROM ( `col_tinyint` AND '2024-04-21' ) ) ORDER BY field1, field2 LIMIT 9 /* QNO 861 CON_ID 176 */ ;
```

### 2. What did you expect to see? (Required)
query successfully.
### 3. What did you see instead (Required)
```sql
(1105, 'invalid input value: Utf8Error { valid_up_to: 1, error_len: Some(1) }')
```
### 4. What is your TiDB version? (Required)
```bash
MySQL root@172.16.4.131:test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.4.0
Edition: Community
Git Commit Hash: 2562b030a8d9d5308e3e4b774ec9429255a75c4d
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-10 11:53:59
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by guo-shaoge** [comment]
The in arg of `substr` is latin1, we treat latin1 as utf8 for now, and it's not a valid utf8 string. After discussion we decide to change the case [copr-test](https://github.com/tikv/copr-test/pull/148) and fix this when latin1 is supported fully.
