### ISSUE TITLE
tidb-lightning import failed due to too many empty regions

### ISSUE THREAD

**Issue by fengdangxing** [pingcap/tidb#31620]
![image](https://user-images.githubusercontent.com/24405972/149117404-5ca38776-5e23-42ed-a18e-3c7d922efc46.png)
![image](https://user-images.githubusercontent.com/24405972/149117464-311d04c7-7693-4b82-88f8-1a6dc6cd86eb.png)
![image](https://user-images.githubusercontent.com/24405972/149117811-b727beba-8ba2-461e-a9bc-f31d87765950.png)
v5.3.0

**Comment by fengdangxing** [comment]
» config show
{
  "replication": {
    "enable-placement-rules": "true",
    "enable-placement-rules-cache": "false",
    "isolation-level": "",
    "location-labels": "host",
    "max-replicas": 3,
    "strictly-match-label": "false"
  },
  "schedule": {
    "enable-cross-table-merge": "true",
    "enable-joint-consensus": "true",
    "high-space-ratio": 0.7,
    "hot-region-cache-hits-threshold": 3,
    "hot-region-schedule-limit": 4,
    "hot-regions-reserved-days": 0,
    "hot-regions-write-interval": "10m0s",
    "leader-schedule-limit": 40,
    "leader-schedule-policy": "count",
    "low-space-ratio": 0.8,
    "max-merge-region-keys": 50000,
    "max-merge-region-size": 16,
    "max-pending-peer-count": 64,
    "max-snapshot-count": 20,
    "max-store-down-time": "30m0s",
    "merge-schedule-limit": 16,
    "patrol-region-interval": "10ms",
    "region-schedule-limit": 40,
    "region-score-formula-version": "v2",
    "replica-schedule-limit": 4,
    "split-merge-interval": "24h0m0s",
    "tolerant-size-ratio": 0
  }
}
"max-merge-region-size": 16,
"max-merge-region-keys": 50000,
 "enable-cross-table-merge": "true",
 "split-merge-interval": "24h0m0s"
After modifying the configuration, the empty ones are merged

**Comment by gozssky** [comment]
This behavior is introduced in v5.3 and documented in https://docs.pingcap.com/tidb/v5.3/tidb-lightning-prechecks. So I'm going to close this issue. If you have further questions, feel free to reopen it.
