### ISSUE TITLE
can't use collate clause for enum or set

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#31637]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
create table tt(a char(10), b enum('a', 'B', 'c'), c set('a', 'B', 'c'), d json) collate utf8mb4_general_ci;
insert into tt values ("a", "a", "a", JSON_OBJECT("a", "a"));
insert into tt values ("A", "A", "A", JSON_OBJECT("A", "A"));
insert into tt values ("b", "b", "b", JSON_OBJECT("b", "b"));
insert into tt values ("B", "B", "B", JSON_OBJECT("B", "B"));
insert into tt values ("c", "c", "c", JSON_OBJECT("c", "c"));
insert into tt values ("C", "C", "C", JSON_OBJECT("C", "C"));
select min(b collate utf8mb4_bin) from tt;
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
panic
### 4. What is your TiDB version? (Required)
master

**Comment by yudongusa** [comment]
@wjhuang2016 since SQL team has been working collation related refactor and improvement, assign the collation related issues to sig/sql-infra for now.
