### ISSUE TITLE
can't use collate clause for json when the new collation is enabled

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#31640]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `tt` (
  `a` char(10) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `b` enum('a','B','c') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `c` set('a','B','c') COLLATE utf8mb4_general_ci DEFAULT NULL,
  `d` json DEFAULT NULL
)
select min(d collate utf8mb4_bin) from tt;
```

### 2. What did you expect to see? (Required)
No error 
### 3. What did you see instead (Required)
```
Error 1253: COLLATION 'utf8mb4_bin' is not valid for CHARACTER SET 'binary'
```
### 4. What is your TiDB version? (Required)
master

**Comment by yudongusa** [comment]
@wjhuang2016 since SQL team has been working collation related refactor and improvement, assign the collation related issues to sig/sql-infra for now.
