### ISSUE TITLE
IT mysql `insert_update` failed

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#31651]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in ci https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_common_test/detail/tidb_ghpr_integration_common_test/8971/pipeline/

```bash
run test [insert_update] err: sql:SELECT * FROM t1;: failed to run query
"SELECT * FROM t1;"
 around line 293,
we need(34):
Warning 1048: Column 'c1' cannot b
but got(34):
SELECT * FROM t1;
id      c1      cnt
1       0       1
```

**Comment by djshow832** [comment]
Fixed by https://github.com/pingcap/tidb-test/pull/1301.
