### ISSUE TITLE
unstable integration test lightning_checkpoint_chunks

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#31664]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
SEE: https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/9563/pipeline

I think chunkRestore should wait deliverLoop finished before return to avoid this kind of `writing closed chan` painc.

**Comment by gozssky** [comment]
Fixed by https://github.com/pingcap/tidb/pull/34313.
