### ISSUE TITLE
v4.0.16 with sql binding upgrade to 5.4.0, reload tidb, will report "[sql-bind] failed to generate bind record from data row"] [error="[planner:1176]Key 'idx' doesn't exist in table 't'"]"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#31674]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. install tidb cluster with 4.0.16, log level is debug, other config as default.
2. 	Try(db.Query("use test;"))
        Try(db.Query("drop table if exists t;"))
	Try(db.Query("create table t(a int, b int, c int, index idx(a));"))
	Try(db.Query("create global binding for select * from t where a < 1 using select * from t use index(idx) where a < 1;"))
	Try(db.Query("create global binding for select * from t where a < 1 using select * from t ignore index(idx) where a < 1;"))
	Try(db.Query("create global binding for select * from test.t where a <= 1 using select * from test.t use index(idx) where a <= 1;"))
	Try(db.Query("create global binding for select * from test.t where a <= 1 using select * from test.t ignore index(idx) where a <= 1;"))
}
3. upgrade to v5.4.0
4. drop test.t;
5. create table t (c1 text, c2 int, c3 int, c4 int, c5 int, primary key (c1(5), c2), unique key (c3), key (c4));
6. tiup cluster reload -R tidb

### 3. What did you see instead (Required)

continually report :
[2022/01/13 21:03:38.349 +08:00] [DEBUG] [handle.go:163] ["[sql-bind] failed to generate bind record from data row"] [error="[planner:1176]Key 'idx' doesn't exist in table 't'"]
[2022/01/13 21:03:38.350 +08:00] [DEBUG] [handle.go:163] ["[sql-bind] failed to generate bind record from data row"] [error="[planner:1176]Key 'idx' doesn't exist in table 't'"]

### 4. What is your TiDB version? (Required)

| Release Version: v5.4.0
Edition: Community
Git Commit Hash: af3ed8246cbb959e56ef514321002ca3085d6253
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-12 13:34:51
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by seiya-annie** [comment]
[tidb.log](https://github.com/pingcap/tidb/files/7863029/tidb.log)

**Comment by rebelice** [comment]
This is not an upgrade bug. 
The debug-level log `[DEBUG] [handle.go:163] ["[sql-bind] failed to generate bind record from data row"] [error="[planner:1176]Key 'idx' doesn't exist in table 't'"]` caused by creating binding, dropping table t and re-creating table t without index ‘idx’. You can still see this log even without upgrading.
Minimal step:
```
1. install tidb cluster with 4.0.16, log level is debug, other config as default.
2. use test;
    drop table if exists t;
    create table t(a int, b int, c int, index idx(a));
    create global binding for select * from t where a < 1 using select * from t use index(idx) where a < 1;
3. drop test.t;
4. create table t (c1 text, c2 int, c3 int, c4 int, c5 int, primary key (c1(5), c2), unique key (c3), key (c4));
5. tiup cluster reload -R tidb OR restart tidb
```

**Comment by rebelice** [comment]
another issue https://github.com/pingcap/tidb/issues/31703
