### ISSUE TITLE
stmtStats.run takes over 10% tidb cpu with topsql disabled

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#31704]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run tpc-c benchmarksql 1000 warehouse against v5.4.0 over 10 hours

### 2. What did you expect to see? (Required)
with topsql disabled, no obvious cpu overhead from topsql feature

### 3. What did you see instead (Required)
10% cpu utilization
![image](https://user-images.githubusercontent.com/2316425/149507926-62384cbf-2f0d-484f-b2ac-a3723fcdae5d.png)

### 4. What is your TiDB version? (Required)

v5.4.0

**Comment by breeswish** [comment]
Fixed by https://github.com/pingcap/tidb/pull/31705
