### ISSUE TITLE
analyze failure on news_item of tpc-e with 5k rows

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#31726]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

restore tpc-e 5k customer dataset

### 2. What did you expect to see? (Required)
```
mysql> select count(*) from news_item;
+----------+
| count(*) |
+----------+
|     5000 |
+----------+
1 row in set (0.01 sec)
mysql> analyze table news_item;
ERROR 8004 (HY000): Transaction is too large, size: 104969237

CREATE TABLE `news_item` (
  `ni_id` bigint(12) NOT NULL,
  `ni_headline` varchar(80) NOT NULL,
  `ni_summary` varchar(255) NOT NULL,
  `ni_item` mediumblob NOT NULL,
  `ni_dts` datetime NOT NULL,
  `ni_source` varchar(30) NOT NULL,
  `ni_author` varchar(30) DEFAULT NULL,
  PRIMARY KEY (`ni_id`) /*T![clustered_index] CLUSTERED */
);
```
### 3. What did you see instead (Required)
analyze succeed.

### 4. What is your TiDB version? (Required)

master version
```
Release Version: v5.5.0-alpha
Edition: Community
Git Commit Hash: 8ee88265cdfdb9c1b8c6142cd8852628521551ce
Git Branch: heads/refs/tags/v5.5.0-alpha
UTC Build Time: 2022-01-13 14:57:06
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by dbsid** [comment]
no data change actually for the table news_item

```
mysql> show stats_meta where table_name = 'news_item';
+---------+------------+----------------+---------------------+--------------+-----------+
| Db_name | Table_name | Partition_name | Update_time         | Modify_count | Row_count |
+---------+------------+----------------+---------------------+--------------+-----------+
| tpce    | news_item  |                | 2022-01-14 15:06:42 |            0 |      5000 |
+---------+------------+----------------+---------------------+--------------+-----------+
1 row in set (0.00 sec)
```

seems the analyze job keep retrying
![image](https://user-images.githubusercontent.com/2316425/149709444-c5c0b845-73ab-42e6-92aa-e99b66edff72.png)

**Comment by dbsid** [comment]
![image](https://user-images.githubusercontent.com/2316425/149716755-ae9ea7c4-6c2c-41bf-97a3-f09cfa578a99.png)

error log
[analyze.go:177] ["save table stats to storage failed"] [error="[kv:8004]Transaction is too large, size: 104969237"]

**Comment by xuyifangreeneyes** [comment]
The analyze job keep retrying is because `analyze table news_item` has never succeeded.
<img width="1216" alt="Screen Shot 2022-01-17 at 3 42 17 PM" src="https://user-images.githubusercontent.com/30385241/149727885-6aa94762-0549-4a91-9409-247c08a7cb7c.png">

**Comment by xuyifangreeneyes** [comment]
`news_item` has column `ni_item` whose type is `mediumnblob` and average column size is `100004`. `ANALYZE` collects 500 topn and 256 buckets for each column by default. Each topn stores one column value and each buckets stores two column values(lower bound and upper bound). So storing the statistics of `ni_item` needs `(500 + 256 * 2) * 100004 = 10MB`, which reaches `txn-total-size-limit` and leads to analyze failure.

<img width="1158" alt="Screen Shot 2022-01-17 at 3 56 26 PM" src="https://user-images.githubusercontent.com/30385241/149745096-e5a52056-3488-4160-a73f-8255295e68a1.png">

![20220117-173916](https://user-images.githubusercontent.com/30385241/149745167-7291bc1e-75d0-4503-bf74-867b12638fb7.png)


![20220117-173951](https://user-images.githubusercontent.com/30385241/149745271-632bb694-4366-40ab-8a97-653172786f45.png)
