### ISSUE TITLE
pd config can't be auto resumed if lightning panic

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#31733]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run tidb-lightning with local backend
2. After tidb-lightning start running and pd-scheduler is patched, stop tidb-lightning process will `kill -9`

### 2. What did you expect to see? (Required)
The scheduler config should be restored to the origin value after 5min.

### 3. What did you see instead (Required)
The scheduler remained the changed value.

### 4. What is your TiDB version? (Required)
nightly

**Comment by 3pointer** [comment]
I have a draft PR to fix this issue. https://github.com/pingcap/tidb/pull/31725. but cannot verify in tests. because we cannot make sure the ttl works through api.

```
// update config with ttl
curl http://{PD_IP}/pd/api/v1/config?ttlSecond=100 -XPOST -d '{"schedule.max-merge-region-keys":0}'

// get config and found config still not changed.
curl http://{PD_IP}/pd/api/v1/config/schedule | grep max-merge-region-keys

  "max-merge-region-keys": 2000,
```

**Comment by 3pointer** [comment]
cc @rleungx, should PD provide an api to tell us the specified config's ttl worked?

**Comment by rleungx** [comment]
Yes, we should. See https://github.com/tikv/pd/issues/4596

**Comment by gozssky** [comment]
It is the same as https://github.com/pingcap/tidb/issues/33546 and fixed by https://github.com/pingcap/tidb/pull/33545.

**Comment by 3pointer** [comment]
it's not same as scheduler
