### ISSUE TITLE
statistics: do not use analyze version 2 as default config for new clusters since it was an experimental feature

### ISSUE THREAD

**Issue by yiwen92** [pingcap/tidb#31748]
## Enhancement
Since a lot of customers reported OOM when they are doing analyze table due to tidb_analyze_version = 2 in v5.1 and v5.2, and as this was defined as experimental feature, so we suggest not to use version 2 by default. Let's keep  tidb_analyze_version = 1 as default set for v5.1.x and v5.2.x.

affected version: v5.1.x and v5.2.x.

**Comment by windtalker** [comment]
I think it is an enhancement rather than a bug, so remove all the `affects-xxx` label.
