### ISSUE TITLE
Update Dumpling Behavior to not dump policies by default

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#31760]
In a call with the tools team, we discussed the current dumpling behavior of automatically dumping placement policies in dumpling backups. Because dumpling is a logical backup tool and is often used to restore to a destination which has a different physical layout, we agreed to change this. The new behavior will be:

- Dumping placement policies is disabled by default.
- A new option will be added to dumpling which will dump placement policies (TBD). Whether it dumps all placement policies or referenced tables is TBD.
- When the option is enabled, all placement policies will be dumped with `CREATE OR REPLACE PLACEMENT POLICY` syntax.

This doesn't affect the `SHOW CREATE TABLE` output which will include the placement policies in the table name. The restore will still need to enable `tidb_placement_mode='IGNORE'` for a safe restore if the policies don't exist.

**Comment by lcwangchao** [comment]
Dumpling do not need more development works now. The current behavior is:

1. Always dump placement policies with annotation format.
2. The placement sql will be dumped as `CREATE PLACEMENT POLICY ...` without "OR REPLACE" to stay the same with databases and tables. (The lightning will add the 'or replace' clause when importing it)
