### ISSUE TITLE
GCStats runs too many times

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#31778]
## Enhancement
There are ~4000 tables in tidb-server, and only 78 of them are frequently accessed.

From the dashboard we can see that the SQLs triggered by GCStats run too frequently.
<img width="1692" alt="截屏2022-01-18 下午9 22 22" src="https://user-images.githubusercontent.com/9039012/149945334-f99e6721-8373-4d12-9582-bb4119eeff5d.png">

Which causes the CPU to oscillate every 5mins:
<img width="816" alt="截屏2022-01-18 下午9 24 21" src="https://user-images.githubusercontent.com/9039012/149945681-680cc5d0-59f5-4a6b-b40a-a2871a1efba5.png">

**Comment by winoros** [comment]
ref https://github.com/pingcap/tidb/issues/45966
