### ISSUE TITLE
Testing tidb with Go fuzzer

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#318]
See https://github.com/dvyukov/go-fuzz-corpus/blob/master/sqlparser/main.go

**Comment by morgo** [comment]
We should also work with [google/oss-fuzz](https://github.com/google/oss-fuzz). They are looking for open source projects to work with, and have already [reported bugs in MySQL](https://github.com/google/oss-fuzz/issues/355).

**Comment by nullnotnil** [comment]
Support was added in https://github.com/pingcap/tidb/pull/17250 

I am going to close this issue for now. Thanks!
