### ISSUE TITLE
Unique binding-id to manage bindings

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#31852]
whe i will drop binding ,i can't find a true info confirm the binding to delete

![image](https://user-images.githubusercontent.com/21033020/150308934-fcdd5025-4897-4ecb-9b6a-65b118ad56fe.png)

now  I need to manually rewrite `Bind_sql` against `Original_sql`, which is too unclear. 

I don’t think such an operation and maintenance method is a function of GA

**Comment by Reminiscent** [comment]
Duplicate with https://github.com/pingcap/tidb/issues/27736, which we will consider implementing in this sprint.
