### ISSUE TITLE
How to set table TTL and TTL_GRANULARITY using ALTER TABLE? 

### ISSUE THREAD

**Issue by noobgramming** [pingcap/tidb#31869]
## General Question

Hi, I'm trying to set a row TTL for existing table. 

This reference gives example for setting TTL on new table https://en.pingcap.com/blog/managing-you-data-lifecycle-with-time-to-live-tables/

and says `You can also use ALTER TABLE to switch an existing table to a row-granularity TTL table.` but does not describe how to do it.

I have tried setting like let you configure ENGINE with `alter table tbl TTL='30h'` and that doesn't work.

syntax reference also says nothing about it https://docs.pingcap.com/tidb/stable/sql-statement-alter-table

Can you kindly link me to documentation on this or just reply how to do it?

**Comment by noobgramming** [comment]
I can see from https://github.com/pingcap/tidb/pull/22763 that I'm using proposed syntax correctly... So maybe this just isn't implemented yet

@sunxiaoguang I see you worked on that RFC and the blog post, maybe you can give me a hand on this?

**Comment by SunRunAway** [comment]
TTL feature is released with TiDB v6.5: https://docs.pingcap.com/tidb/stable/time-to-live#periodically-delete-expired-data-using-ttl-time-to-live

tracking issue: https://github.com/pingcap/tidb/issues/39262
