### ISSUE TITLE
Add a glue layer between SQL layer and KV API

### ISSUE THREAD

**Issue by dumbc4t** [pingcap/tidb#3190]
I'm trying to integrate TIDB with another storage system, but the only way to do so is to implement the KV interface, the problem is that KV API is too primitive, if the backend storage could get some more detail information about SQL, that really make things easier. What I plan to do is to add a glue layer (some hook points maybe) between SQL and KV. Is that make sense, any guides?

**Comment by ngaut** [comment]
That may needs lots of changes. The simplest way to integrate TiDB with another storage is implement the KV API.  But please feel free to do that, i am looking forward to the results.

**Comment by shenli** [comment]
@dumbc4t We have a DistSQL API between SQL and KV. SQL will send schema and operators to KV to read data and do some computing.

**Comment by dumbc4t** [comment]
@shenli Thanks, I'll check it out.
