### ISSUE TITLE
Can TiDB create dynamic partition based on time?

### ISSUE THREAD

**Issue by didip** [pingcap/tidb#31914]
## General Question

We want to compare Druid vs TiDB (specifically TiFlash for OLAP use-cases).

But our data is so huge that daily partition is a must. Can TiDB do that? I am having a hard time searching if it can do so.

**Comment by bb7133** [comment]
Hello!

For now, there is no built-in mechanism for making/dropping a partition in an automatic way. I'm afraid you have to do it by yourself(a scheduling task like crontab maybe).

It would be better to make your requirements more specific, say, what is the 'dynamic partition' exactly? How would you like to use it? We're doing some work for the enhancements for table partitioning in TiDB and would like to hear your usecase.
