### ISSUE TITLE
Weak read consistency cannot take effect

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#31933]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Enable weak read consistency (`set @@tidb_read_consistency = weak`) and execute some queries.
https://github.com/pingcap/tidb/pull/30943 set the isolation under some conditions, however the field will be overwritten by `SetFromSessionVars`.

### 2. What did you expect to see? (Required)
The [isolation field](https://github.com/pingcap/kvproto/blob/805ac3a35f883d87bf1fe70480ef5a7b9e64cd8f/proto/kvrpcpb.proto#L675) of rpc requests should be `RC`.

### 3. What did you see instead (Required)
It's still `SI`

### 4. What is your TiDB version? (Required)

master, release-5.4

**Comment by cfzjywxk** [comment]
A possible way to fix this is to merge the 
```
if e.ctx.GetSessionVars().StmtCtx.WeakConsistency {
		builder.SetIsolationLevel(kv.RC)
}
```
logic into 
`SetFromSessionVars`, so there would be a single entry setting `stmtCtx` related things.
