### ISSUE TITLE
unittest and check_dev_2 always timeout after dependency updated

### ISSUE THREAD

**Issue by peng1999** [pingcap/tidb#31941]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

#31122 and #31010 both updated kvproto to a version which requires changes on pd and go-client and both of them cannot pass the unittest due to a timeout. 

### 2. What did you expect to see? (Required)

N/A

### 3. What did you see instead (Required)

N/A

### 4. What is your TiDB version? (Required)

N/A

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
