### ISSUE TITLE
Target table in where clause for Update and Delete is not resulting error in TiDB.

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#31971]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1;
CREATE TABLE t1 (a int ,b int );
INSERT into t1 values (1, 1),(6, 1);
update t1 set b= 20 where a in (SELECT a from t1);
DELETE FROM t1 where a in (SELECT a from t1 );
```

### 2. What did you expect to see? (Required)
```sql
mysql> update t1 set b= 20 where a in (SELECT a from t1);
ERROR 1093 (HY000): You can't specify target table 't1' for update in FROM clause

mysql> DELETE FROM t1 where a in (SELECT a from t1 );
ERROR 1093 (HY000): You can't specify target table 't1' for update in FROM clause

```
### 3. What did you see instead (Required)
```sql
mysql> update t1 set b= 20 where a in (SELECT a from t1);
Query OK, 2 rows affected (0.01 sec)
Rows matched: 2  Changed: 2  Warnings: 0

mysql> DELETE FROM t1 where a in (SELECT a from t1 );
Query OK, 2 rows affected (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.4.0-alpha-264-g6efa36df6
Edition: Community
Git Commit Hash: 6efa36df6cff325106f67ecfe3d79816ba37ca6a
Git Branch: master
UTC Build Time: 2022-01-25 20:10:16
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by gengliqi** [comment]
According to https://dev.mysql.com/doc/refman/5.7/en/subquery-restrictions.html, MySQL has a restriction on subqueries that is we cannot modify a table and select from the same table in a subquery while TiDB can.
So I think it's a feature instead of a bug.

**Comment by zanmato1984** [comment]
> According to https://dev.mysql.com/doc/refman/5.7/en/subquery-restrictions.html, MySQL has a restriction on subqueries that is we cannot modify a table and select from the same table in a subquery, while TiDB does not have it. So I think it's a feature of TiDB, not a bug.

Agree. Closing.
