### ISSUE TITLE
Unstable test `dump_test.TestDumpBlock`

### ISSUE THREAD

**Issue by Ehco1996** [pingcap/tidb#32008]
```
=== RUN   TestDumpBlock
    dump_test.go:62:
        	Error Trace:	dump_test.go:62
        	Error:      	Target error should be in err chain:
        	            	expected: "canceling query due to user request"
        	            	in chain: "context canceled"
        	Test:       	TestDumpBlock
--- FAIL: TestDumpBlock (0.00s)
=== RUN   TestDumpBlock
    dump_test.go:62:
        	Error Trace:	dump_test.go:62
        	Error:      	Target error should be in err chain:
        	            	expected: "canceling query due to user request"
        	            	in chain: "context canceled"
        	Test:       	TestDumpBlock
--- FAIL: TestDumpBlock (0.00s)
=== RUN   TestDumpBlock
```

**Comment by hawkingrei** [comment]
```
[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36807/pipeline/#step-59-log-234)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36807/pipeline/#step-59-log-235)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36807/pipeline/#step-59-log-236)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36807/pipeline/#step-59-log-237)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36807/pipeline/#step-59-log-238)[](https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/36807/pipeline/#step-59-log-239)[2022-02-21T15:21:43.613Z] === FAIL: dumpling/export TestDumpBlock (1.00s)

[2022-02-21T15:21:43.613Z]     dump_test.go:65: 

[2022-02-21T15:21:43.613Z]         	Error Trace:	dump_test.go:65

[2022-02-21T15:21:43.613Z]         	Error:      	Target error should be in err chain:

[2022-02-21T15:21:43.613Z]         	            	expected: "canceling query due to user request"

[2022-02-21T15:21:43.613Z]         	            	in chain: "context canceled"

[2022-02-21T15:21:43.613Z]         	Test:       	TestDumpBlock
```

it still happen.

**Comment by Ehco1996** [comment]
i found even if i pass a cancelled ctx to `simpleQueryWithArgs`, it may return nil error  somethimes😂

maybe there is a bug on `sqlmock`
```
in ShowCreateDatabase
out ShowCreateDatabase (0x0,0x0)
    dump_test.go:66:
        	Error Trace:	dump_test.go:66
        	Error:      	Target error should be in err chain:
        	            	expected: "canceling query due to user request"
        	            	in chain: "context canceled"
        	Test:       	TestDumpBlock
--- FAIL: TestDumpBlock (1.00s)
=== RUN   TestDumpBlock
```

**Comment by Ehco1996** [comment]
i found even if i pass a cancelled ctx to `simpleQueryWithArgs`, it may return nil error  somethimes😂

maybe there is a bug on `sqlmock`
```
in ShowCreateDatabase
out ShowCreateDatabase (0x0,0x0)
    dump_test.go:66:
        	Error Trace:	dump_test.go:66
        	Error:      	Target error should be in err chain:
        	            	expected: "canceling query due to user request"
        	            	in chain: "context canceled"
        	Test:       	TestDumpBlock
--- FAIL: TestDumpBlock (1.00s)
=== RUN   TestDumpBlock
```

**Comment by hawkingrei** [comment]
> TestDumpBlock

Can you migrate this test case to use ```testkit```？ Most of them use ```testkit```.

**Comment by Ehco1996** [comment]
> i found even if i pass a cancelled ctx to `simpleQueryWithArgs`, it may return nil error sometimes😂
> 
> maybe there is a bug on `sqlmock`
> 
> ```
> in ShowCreateDatabase
> out ShowCreateDatabase (0x0,0x0)
>     dump_test.go:66:
>         	Error Trace:	dump_test.go:66
>         	Error:      	Target error should be in err chain:
>         	            	expected: "canceling query due to user request"
>         	            	in chain: "context canceled"
>         	Test:       	TestDumpBlock
> --- FAIL: TestDumpBlock (1.00s)
> === RUN   TestDumpBlock
> ```

@lichunzhu  i found the root cause: default query delay for `sqlMock` is `0`, and it not handle cancelled ctx rightly. e.g:

this [branch](https://github.com/DATA-DOG/go-sqlmock/blob/699dcdfa20ba013453a750bedd46364983ab35aa/sqlmock_go18.go#L36) would be trigged even if ctx is cancelld sometimes

so i add `WillDelayFor` for this test  in https://github.com/pingcap/tidb/pull/32667/files, `sqlmock` does the same thing in thier own test https://github.com/DATA-DOG/go-sqlmock/blob/699dcdfa20ba013453a750bedd46364983ab35aa/sqlmock_go18_test.go#L183

**Comment by Ehco1996** [comment]
> > TestDumpBlock
> 
> Can you migrate this test case to use `testkit`？ Most of them use `testkit`.

I think sqlmock would be more appropriate for this scenario as there is no concept of a session in dumpling like tidb
