### ISSUE TITLE
lightning: tracking issue for integrate lightning into dm

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#32010]
# Backend ground
tidb-lightning has been integrated into dm to replace loader by pingcap/tiflow#, but we found some issues then. This issue is created and track these compatible issues and bugs.

# Bugs 
- [x] pingcap/tiflow#4486
- [ ]  pingcap/tiflow#4489

# Feature Request
- Support table transfer columns. See pingcap/tidb-tools#520, pingcap/tiflow#3262

**Comment by lance6716** [comment]
long time no bug now
