### ISSUE TITLE
UT get back TestAnalyzeGlobalStatsWithOpts1

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#32035]
## Enhancement

Make the case stable and get it back!
Both `TestAnalyzeGlobalStatsWithOpts1` and `TestAnalyzeGlobalStatsWithOpts2` ... those two might be similar.

**Comment by hawkingrei** [comment]
TestAnalyzeGlobalStatsWithOpts2 is still in problem.

https://prow.pingcap.net/view/gs/pingcapprow/logs/bazel_test_tidb/1554315795041882112

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
