### ISSUE TITLE
Wrong select statement result

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3205]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I hope to get 3 UUID by select statement to insert.
select uuid() from (select 1 union all select 2 union all select 3 )a;

2. What did you expect to see?
MariaDB result:
| 515a5e53-2fdc-11e7-9409-42010a8c0011 |
| 515a5e5f-2fdc-11e7-9409-42010a8c0011 |
| 515a5e61-2fdc-11e7-9409-42010a8c0011 |
3 different UUID

3. What did you see instead?
TiDB result:
| fe808e4c-2fdc-11e7-81c1-4101543ef67a |
| fe808e4c-2fdc-11e7-81c1-4101543ef67a |
| fe808e4c-2fdc-11e7-81c1-4101543ef67a |
3 same UUID

4. What version of Go are you using (`go version`)?
2017/05/03 08:46:02 printer.go:31: [info] Welcome to TiDB.
2017/05/03 08:46:02 printer.go:32: [info] Version:
2017/05/03 08:46:02 printer.go:33: [info] Git Commit Hash: ec4eb933fa6786473ee31485c3d317ede63da5ac
2017/05/03 08:46:02 printer.go:34: [info] UTC Build Time:  2017-05-02 03:02:10

**Comment by ngaut** [comment]
Thank you for your report. Please take a look @coocood

**Comment by shenli** [comment]
@XuHuaiyu We should not apply ConstantFold on uuid().

**Comment by shenli** [comment]
@DavisLinDB [This PR](https://github.com/pingcap/tidb/pull/3207) will fix the bug.
