### ISSUE TITLE
may use Counter instead of Histogram for Packet IO metrics

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#32075]
## Enhancement

I found that we use Histogram to track the packet IO, see https://github.com/pingcap/tidb/blob/master/server/packetio.go#L52

But is it necessary to use Histogram here? In the Grafana, We have a Client Traffic Panel, see below, but in the panel, we can see that here we use histogram sum, and we can use a counter instead. 

![image](https://user-images.githubusercontent.com/1080370/151704740-b490c214-1cf1-48e0-9ce5-4eaa42c4ce20.png)

Counter is much faster than Histogram, I wrote a very simple benchmark here:

```go
func BenchmarkPromHistogram(b *testing.B) {
	r := PacketIOHistogram.WithLabelValues("read")
	for i := 0; i < b.N; i++ {
		r.Observe(10)
	}
}

func BenchmarkPromCounter(b *testing.B) {
	r := QueryTotalCounter.WithLabelValues("read", "write")
	for i := 0; i < b.N; i++ {
		r.Add(10)
	}
}
```

```bash
cpu: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
BenchmarkPromHistogram-8   	19636056	        60.26 ns/op
BenchmarkPromCounter-8     	95965551	        10.68 ns/op
```

**Comment by siddontang** [comment]
If we decide to advance this, I think we should list all the histogram metrics and check whether we need to use Counter instead.

**Comment by bb7133** [comment]
Checked the current metrics by:
* The calls of `prometheus.NewHistogram()` / `prometheus.NewHistogramVec()`
* The use of `{histogram_metrics}_sum` / `{histogram_metrics}_count`

One another metric that can be improved is `DistSQLCoprCacheHistogram`:
https://github.com/pingcap/tidb/blob/d5d8e13964009bf1d5b910fdd77740b018f5ee8d/metrics/distsql.go#L56

https://github.com/pingcap/tidb/blob/27348d67951c5d9e409c84ca095f0e5d3332c1fd/metrics/grafana/tidb.json#L6660

It was introduced as a histogram metric in #19979 but after #26338 and #30712(IMO the change is reasonable), it using a counter is enough.
