### ISSUE TITLE
dumpling doesn't write CSV with CRLF as line separator

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#32105]
## Bug Report

by inspecting the code, I found dumpling use `\n` as line separator. But [RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180#page-2) says we should use CRLF

walkaround: use utils like `unix2dos`

**Comment by lichunzhu** [comment]
/assign @docsir 
Could please do this job? We need to change this part from `LF` to `CRLF`.
https://github.com/pingcap/tidb/blob/b5245b50925f2553e917371906975a378b57fa50/dumpling/export/writer_util.go#L347
