### ISSUE TITLE
Wrong select random() statement result.

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3211]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I hope to get random Date from select statement.
select DATE_ADD("2016-01-01", INTERVAL RAND(20160101) * 364 DAY) from (select 1 union all select 2 union all select 3 union all select 4) a;

2. What did you expect to see?
MariaDB Result:
+-----------------------------------------------------------+
| DATE_ADD("2016-01-01", INTERVAL RAND(20160101) * 364 DAY) |
+-----------------------------------------------------------+
| 2016-11-25                                                |
| 2016-11-20                                                |
| 2016-09-23                                                |
| 2016-12-24                                                |
+-----------------------------------------------------------+
4 rows in set (0.00 sec)
Differrent date.

3. What did you see instead?
TiDB result:
+-----------------------------------------------------------+
| DATE_ADD("2016-01-01", INTERVAL RAND(20160101) * 364 DAY) |
+-----------------------------------------------------------+
| 2016-12-14                                                |
| 2016-12-14                                                |
| 2016-12-14                                                |
| 2016-12-14                                                |
+-----------------------------------------------------------+
4 rows in set (0.00 sec)
4 same Date.

4. What version of TiDB are you using (`tidb-server -V`)?
2017/05/05 01:33:38 printer.go:31: [info] Welcome to TiDB.
2017/05/05 01:33:38 printer.go:32: [info] Version:
2017/05/05 01:33:38 printer.go:33: [info] Git Commit Hash: ec4eb933fa6786473ee31485c3d317ede63da5ac
2017/05/05 01:33:38 printer.go:34: [info] UTC Build Time:  2017-05-02 03:02:10

I don't know which policy for ConstantFold, but I suggest do more test case.

**Comment by ngaut** [comment]
Thanks for your report, we will fix it later.

**Comment by XuHuaiyu** [comment]
@DavisLinDB 
Hi, thank you for your report, this bug has been fixed.
