### ISSUE TITLE
server: support `CLIENT_DEPRECATE_EOF` capability flag

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#32118]
## Enhancement

MySQL deprecated `EOF` packets since MySQL v5.7.5 and [`CLIENT_DEPRECATE_EOF`](https://dev.mysql.com/doc/internals/en/capability-flags.html) was introduced since then.

This flag, as well as the deprecation of EOF was not supported by TiDB. This is fine since this flag requires a server-client negotiation according to the MySQL protocol. All MySQL clients are able to communicate with TiDB by treating it as 'the old MySQL server'.

However, it is better to make it implemented for:
* EOF has been deprecated for a long time, we hope that TiDB could be 'up-to-date' for MySQL compatibilities.
* The 'old server' might not be fully tested for the new versions of MySQL clients. For example: [Connector/J bug #10625](https://bugs.mysql.com/bug.php?id=106252)

**Comment by dveeden** [comment]
@bb7133 I'm also interested in working on this
