### ISSUE TITLE
UT unstable test TestGetSchemaStorage

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#32153]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Found in CI

### 2. What did you expect to see? (Required)

CI success

### 3. What did you see instead (Required)

![origin_img_v2_6171c942-cb18-404c-a93a-d077cbd5ad8g](https://user-images.githubusercontent.com/1420062/152927774-471ae2f3-add7-4e2d-8e9c-42926b80c11e.png)

### 4. What is your TiDB version? (Required)

master 7a667225db947a3047aea1005457efeccbbfa006

**Comment by rahulk789** [comment]
Hello! Is it possible for me to know where the problematic code might lie?

**Comment by tiancaiamao** [comment]
```
cd server
go test -run TestGetSchemaStorage
```

Try many times and no reproduce ... I think it's safe to close this issue.
