### ISSUE TITLE
statement table `FIRST_SEEN`, `LAST_SEEN` field value is not sync with `time_zone` variable

### ISSUE THREAD

**Issue by baurine** [pingcap/tidb#32156]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Change `time_zone` to another value that is different from `system_time_zone`.

```
mysql> show variables like '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | UTC    |
| time_zone        | SYSTEM |
+------------------+--------+
2 rows in set (0.12 sec)

mysql> set global time_zone='+09:00';

// exit and reconnect

mysql> show variables like '%time_zone%';
+------------------+--------+
| Variable_name    | Value  |
+------------------+--------+
| system_time_zone | UTC    |
| time_zone        | +09:00 |
+------------------+--------+
2 rows in set (0.12 sec)
```

Check current time:

```
mysql> select now();
+---------------------+
| now()               |
+---------------------+
| 2022-02-08 15:16:07 |
+---------------------+
1 row in set (0.04 sec)
```

Run some SQLs:

```
mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.10 sec)

mysql> select sleep(1);
+----------+
| sleep(1) |
+----------+
|        0 |
+----------+
1 row in set (1.04 sec)
```

Query statement table:

```
mysql> select FIRST_SEEN, LAST_SEEN, QUERY_SAMPLE_TEXT from INFORMATION_SCHEMA.CLUSTER_STATEMENTS_SUMMARY_HISTORY order by LAST_SEEN desc limit 1\G
*************************** 1. row ***************************
       FIRST_SEEN: 2022-02-08 06:16:21
        LAST_SEEN: 2022-02-08 06:16:33
QUERY_SAMPLE_TEXT: select `sleep` ( ? )
1 row in set (0.14 sec)
```

### 2. What did you expect to see? (Required)

The `FIRST_SEEN` value should be the time of +9:00 time zone instead of UTC time zone (aka `system_time_zone` in this case). same as `LAST_SEEN`, `SUMMARY_BEGIN_TIME` and `SUMMARY_END_TIME` field.

### 3. What did you see instead (Required)

These filed values are shown as the UTC time zone (aka `system_time_zone` in this case).

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v5.3.0 |
+--------------------+
1 row in set (0.10 sec)
```

**Comment by crazycs520** [comment]
@LemonHX PTAL

**Comment by mjonss** [comment]
Related to #26642 but for different table/commands.

**Comment by mjonss** [comment]
For FIRST_SEEN and LAST_SEEN, the implementation sends the times in go time datatype in the location of the tidb server global system_time_zone, we need to propagate the session local `time_zone` location down to the FirstSeenStr/LastSeenStr entries in the columnValueFactoryMap, and add `.In(<session local location>)` like:
`return types.NewTime(types.FromGoTime(ssElement.firstSeen.In(<session local time zone location>)), mysql.TypeTimestamp, 0)`
