### ISSUE TITLE
Cannot add tiflash replica for table with gbk charset even when new_collation is disabled

### ISSUE THREAD

**Issue by lidezhu** [pingcap/tidb#32209]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start a new tidb cluster with tidb config `new_collations_enabled_on_first_bootstrap=false`.
run the following sql:
```
mysql> SELECT VARIABLE_VALUE FROM mysql.tidb WHERE VARIABLE_NAME='new_collation_enabled';
+----------------+
| VARIABLE_VALUE |
+----------------+
| False          |
+----------------+

mysql> CREATE TABLE test.t (a varchar(100)) CHARACTER SET 'gbk' COLLATE 'gbk_bin';

mysql> alter table test.t set tiflash replica 1;
```

### 2. What did you expect to see? (Required)
The sql success without error.

### 3. What did you see instead (Required)
ERROR 8200 (HY000): Unsupported ALTER table replica for table contain gbk charset

### 4. What is your TiDB version? (Required)
Release Version: v5.5.0-alpha-215-g37c9dc9e5
Edition: Community
Git Commit Hash: 37c9dc9e52066b685956bc6287133b9357efb7a4
Git Branch: master
UTC Build Time: 2022-02-09 09:08:13
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by zimulala** [comment]
Currently, TiFlash does not support the GBK character set. So this SQL will return an error. We add this info to the docs: https://github.com/pingcap/docs/pull/7416/files#diff-d814c7fc5fe39bf56a3839975e44bdeba3e92e16e8f6a01afa5c1cc7f685def1R91

**Comment by zimulala** [comment]
I close this issue first and can open it again if there are other questions.

**Comment by lidezhu** [comment]
But when new_collation is disabled, the character set should be ignored which is the behavior of previous tidb versions, and we can create tiflash replica for tables with any character set. Why we don't keep this behavior as before?

**Comment by lidezhu** [comment]
@zimulala

**Comment by lidezhu** [comment]
Got the answer. This is indeed not a bug. Sorry for the mistake.
