### ISSUE TITLE
empty strings and spaces are considered unique index conflicts

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#32231]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t (c1 varchar(10), c2 int, c3 int, c4 int, c5 int, primary key (c1) /*T![clustered_index] clustered */, unique key (c3), key (c4)); 
insert into t values ('  ', -1, 255, 10, 0);
insert into t values ('', 0, 127, 10, -1);

### 2. What did you expect to see? (Required)

insert success.

### 3. What did you see instead (Required)

insert failed.
mysql> insert into t values ('  ', -1, 255, 10, 0);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t values ('', 0, 127, 10, -1);
ERROR 1062 (23000): Duplicate entry '' for key 'PRIMARY'

### 4. What is your TiDB version? (Required)

Release Version: v5.5.0-alpha
Edition: Community
Git Commit Hash: adcaaa5cbe1058da8f363c173521929405d0ecb6
Git Branch: heads/refs/tags/v5.5.0-alpha
UTC Build Time: 2022-02-08 14:56:30
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by zyguan** [comment]
That's because new collation is enabled by default now, and the behaviour is already documented [here](https://docs.pingcap.com/tidb/stable/character-set-and-collation#new-framework-for-collations). You need to fix your cases.
