### ISSUE TITLE
update set statement changes unrelated column

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#3223]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
mysql> create table t (c1 datetime, c2 timestamp);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values ("2000-03-01", "2000-03-01 12:12:12");
Query OK, 1 row affected (0.01 sec)

mysql> select * from t;
+---------------------+---------------------+
| c1                  | c2                  |
+---------------------+---------------------+
| 2000-03-01 00:00:00 | 2000-03-01 12:12:12 |
+---------------------+---------------------+
1 row in set (0.00 sec)

mysql> update t set c1 = c2;
Query OK, 1 row affected (0.00 sec)

mysql> select * from t;
+---------------------+---------------------+
| c1                  | c2                  |
+---------------------+---------------------+
| 2000-03-01 12:12:12 | 2017-05-09 13:18:17 |
+---------------------+---------------------+
1 row in set (0.00 sec)

```

2. What did you expect to see?

```
mysql> select * from t;
+---------------------+---------------------+
| c1                  | c2                  |
+---------------------+---------------------+
| 2000-03-01 12:12:12 | 2000-03-01 12:12:12 |
+---------------------+---------------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

The `c2` column changed.

4. What version of TiDB are you using (`tidb-server -V`)?

Seems this bug exists for a long time already, before I notice it...

**Comment by hanfei1991** [comment]
MySQL also behave like this @tiancaiamao :

mysql> create table t (c1 datetime, c2 timestamp);
Query OK, 0 rows affected (0.05 sec)

mysql> insert into t values ("2000-03-01", "2000-03-01 12:12:12");
Query OK, 1 row affected (0.01 sec)

mysql> select * from t;
+---------------------+---------------------+
| c1                  | c2                  |
+---------------------+---------------------+
| 2000-03-01 00:00:00 | 2000-03-01 12:12:12 |
+---------------------+---------------------+
1 row in set (0.01 sec)

mysql> update t set c1 = c2;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from t;
+---------------------+---------------------+
| c1                  | c2                  |
+---------------------+---------------------+
| 2000-03-01 12:12:12 | 2017-05-09 16:57:39 |
+---------------------+---------------------+
1 row in set (0.01 sec)
