### ISSUE TITLE
Fix Int overflow when build on 32 bit

### ISSUE THREAD

**Issue by nsuper** [pingcap/tidb#3227]
1. What did you do?
Build with `GOOS=linux GOARCH=386`
`GOBUILD   := GOPATH=$(CURDIR)/_vendor:$(GOPATH) CGO_ENABLED=0 GOOS=linux GOARCH=386 $(GO) build`

2. What did you expect to see?

3. What did you see instead?
`const SQLMode` int overflow

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: 2bcd329d765c5914c15c3c2a5da3dd4f3985dd4b
UTC Build Time:  2017-05-08 10:15:02

### My patch
```patch
diff --git a/mysql/const.go b/mysql/const.go
index 14b1767..85c2a8c 100644
--- a/mysql/const.go
+++ b/mysql/const.go
@@ -329,7 +329,7 @@ var DefaultLengthOfTimeFraction = map[int]int{
 
 // SQLMode is the type for MySQL sql_mode.
 // See https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html
-type SQLMode int
+type SQLMode int64
 
 // consts for sql modes.
 const (

```

**Comment by ngaut** [comment]
Thank you, please feel free to file a pull request.

**Comment by hueypark** [comment]
Hi @ngaut 
I created the pull request(https://github.com/pingcap/parser/pull/191) for this issue.
Please review it.

**Comment by hueypark** [comment]
@ngaut 
I was working on changing int to int64 for 32bit support.
The above operation was successful in `parser`,  but in` tidb` it resulted in a lot of changes (aborted while fixing over 100 errors).
Besides, the readability of the resulting output is significantly lower than before.
Do you need 32bit support in 2019?
Thank you for your constructive review.

**Comment by tisonkun** [comment]
@kennytm @tangenta @xhebox I think this issue is still valid on current master. Shall we change the type of `SQLMode` to `int64`, or change the SQLMode abstraction to a general bitmap?

**Comment by xhebox** [comment]
@tisonkun I think `int64` is enough for now.

**Comment by xhebox** [comment]
Closed.

Nobody is caring this. Feel free to reopen if anyone cares.

**Comment by alarbada** [comment]
Hello, I'm one that cares :) @xhebox 
[go-mysql](https://github.com/go-mysql-org/go-mysql), which has tidb as a dependency, fails to build on 32bit archs.

Here's one of our [goreleaser failed actions](https://github.com/conduitio-labs/conduit-connector-mysql/actions/runs/13312008116/job/37176673456) as an example.

We'll build for 64bit archs for now, not really a blocker, but would be nice to support 32bit.

**Comment by kennytm** [comment]
The type of `SQLMode` has already been changed to `int64` since #55237 (v8.4.0), and go-mysql has upgraded the `tidb` dependency since go-mysql-org/go-mysql#948 (v1.10.0). The error is caused by a different issue unlike what OP reported:

```
Error:     │ ../../../go/pkg/mod/github.com/pingcap/tidb/pkg/parser@v0.0.0-20241118164214-4f047be191be/hintparser.go:1359:69:
 cannot use math.MaxInt64 (untyped int constant 9223372036854775807) as int value in argument to ErrWarnMemoryQuotaOverflow.GenWithStackByArgs (overflows)
```
https://github.com/pingcap/tidb/blob/62165a41faa800def93a0582dad918ad669ca435/pkg/parser/hintparser.y#L319

I think it is cleaner to submit a new issue.
