### ISSUE TITLE
Sort-merge join memory accounting problem

### ISSUE THREAD

**Issue by coderplay** [pingcap/tidb#32288]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. open a session
2. SET @@tidb_mem_quota_query = 1 << 30; -- 1GB
3. run a large sort-merge join:  `select /*+ MERGE_JOIN(t1, t2) */ * from t1，t2 where t1.id = t2.id;`

### 2. What did you expect to see? (Required)

The sort-merge should take 1GB memory

### 3. What did you see instead (Required)

It actually took 5+ GB, sometimes reach 9GB in our use case

### 4. What is your TiDB version? (Required)
 
5.2.2

### Triage

Check this image for [the heap profiling result](https://user-images.githubusercontent.com/107521/153682522-f5da1d89-95e4-4196-bda0-6f0bd3b292a0.svg), there are multiple parts that exceeded the 1GB limit we set

1. SortedRowContainer
2. chunkInDisk
3. chunk appendByCell
4. copIteratorWorker 

Counting in total, they are way larger than what we set to tidb_mem_quota_query.

**Comment by XuHuaiyu** [comment]
From the heap profiling result, it seems that the execution plan is built as `join{ {t1->sort}, {t2->sort} }`.
The sort operation consumes lots of memory and triggers the spill action (which is `sortAndSpillToDisk` in the profiling result). While the memory usage during the spilling is not counted by the memory tracker. 
This is really a good catch. But sorry for that, it seems we have no workaround for this use case for now.

**Comment by coderplay** [comment]
@XuHuaiyu  we are not seeking workaround, we are looking for a fix :)

**Comment by XuHuaiyu** [comment]
Close this issue because we fix this problem in the duplicate issue 
https://github.com/pingcap/tidb/issues/35632
