### ISSUE TITLE
TiDB Server crashing w/ OOM despite the tidb_mem_quota_query limit

### ISSUE THREAD

**Issue by coderplay** [pingcap/tidb#32287]
### 1. Minimal reproduce step (Required)

huge hash join 

### 2. What did you expect to see? (Required)

We are mimicking our production workloads to a dev TiDB cluster. One of the biggest queries is a huge hash join, which can consume ~50GB of memory. We reduce the `tidb_mem_quota_query` to 1GB to avoid system's oom-killing, but the setting didn't work.

After diving deeper into the `hashjoinExecutor` implementation, we figure out that's because below memory usages are not counted in the memory tracker:

1. The hash table used for joining: https://github.com/pingcap/tidb/blob/master/executor/hash_table.go#L187
2. The entryStore for above hash table: https://github.com/pingcap/tidb/blob/master/executor/hash_table.go#L324
3. The newly created chunks: https://github.com/pingcap/tidb/blob/master/executor/join.go#L281
Besides above `func (worker *copIteratorWorker) handleCopResponse` can take another 2~4 GB in our case.

I am attaching a heap profiling to this ticket, please check it out. We took the profiling when the TiDB server was still alive, taking around 15.8GB heap memory, but eventually, it can consume ~50GB.

### 3. What did you see instead (Required)

tidb server get killed by system's oom-killer

### 4. What is your TiDB version? (Required)

5.2.2 on kubernetes

**Comment by XuHuaiyu** [comment]
Hi, @coderplay
The largest part of the HashJoin memory usage is the underlying data of the hashtable, which has been counted in the memory tracker, and can be spilled to the disk. But as you mentioned in the description, the entryStore for the hash table, which is actually a pointer to the underlying data has not been tracked.
We are still working on improving the coverage of the memory tracker.

**Comment by XuHuaiyu** [comment]
We may try to set [tidb_enable_rate_limit_action](https://docs.pingcap.com/tidb/v5.2/system-variables/#tidb_enable_rate_limit_action) to `false` to see whether the SQL can be cancelled successfully.

**Comment by coderplay** [comment]
@XuHuaiyu 
> The largest part of the HashJoin memory usage is the underlying data of the hashtable, which has been counted in the memory tracker, 

IIUC,  the hashtable isn't accounted, see https://github.com/pingcap/tidb/blob/master/executor/hash_table.go#L187. Could you please let me know which lines of code it does the accounting?

Please be aware that there are 4 big memory consumers in this issue.

**Comment by XuHuaiyu** [comment]
1. The underlying data of hashtable is accounted in https://github.com/pingcap/tidb/blob/954e1e1e82adf723f1e37017b04838b092a9d047/executor/hash_table.go#L166

hashtable stores the key and rowPtr, the memory of it is not tracked:
https://github.com/pingcap/tidb/blob/954e1e1e82adf723f1e37017b04838b092a9d047/executor/hash_table.go#L82-L83

2. The newly created chunk is not accounted
https://github.com/pingcap/tidb/blob/954e1e1e82adf723f1e37017b04838b092a9d047/executor/join.go#L281

3. The copResponse is accounted in https://github.com/pingcap/tidb/blob/954e1e1e82adf723f1e37017b04838b092a9d047/store/copr/coprocessor.go#L550

**Comment by coderplay** [comment]
@XuHuaiyu yep, we are on the same page now.  Looking forward to the fix.

**Comment by wshwsh12** [comment]
There are three memory untracked issues mentioned in this issue
1. For the memory usage of hash table and entryStore, we have tracked them in the pr https://github.com/pingcap/tidb/pull/33918.
2. For the memory usage of `NewChunkWithCapacity` in func `buildHashTableForList`, the memory usage will be tracked when trying to add chunk into rowContainer in `HashJoinExec.buildHashTable`(https://github.com/pingcap/tidb/blob/master/executor/join.go#L783)
3. For the memory usage of handleCopResponse, currently we will control it through tidb_enable_rate_limit_action. But it seem not to work well at the moment, we will refactor the logic in the near future.

**Comment by XuHuaiyu** [comment]
Close this issue, because we fix this problem in the duplicate issue 
https://github.com/pingcap/tidb/issues/35627
