### ISSUE TITLE
CDC support for placement rules

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#32291]
For CDC it was determined that the placement rules will be replicated in the DDL stream, but as a comment (won't be applied on downstream systems). If in future a consumer of the CDC wants to make use of the placement rules it can do so, but because the CDC stream is logically, there is no current known common use case.

**Comment by lcwangchao** [comment]
To force placement will not be applied to the downstream, CDC should set `tidb_placement_mode` to `ignore` when the down stream is tidb.
