### ISSUE TITLE
go get tidb error

### ISSUE THREAD

**Issue by forestkeeper** [pingcap/tidb#3230]
cmd:
go get github.com/pingcap/tidb
# github.com/pingcap/tidb/parser
gopath/src/github.com/pingcap/tidb/parser/lexer.go:131: undefined: yySymType
gopath/src/github.com/pingcap/tidb/parser/misc.go:612: undefined: yySymType
gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:60: undefined: yySymType
gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:61: undefined: yySymType
gopath/src/github.com/pingcap/tidb/parser/yy_parser.go:62: undefined: yySymType

go version go1.7.1 darwin/amd64

**Comment by shenli** [comment]
@forestkeeper Please use git clone to get tidb's source code.
Or you can cd  `tidb-dir` and run `make parser`.
