### ISSUE TITLE
CREATE TEMPORARY TABLE should not be affected by LOCK TABLES stmt

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#32341]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1,t2;
create table t1 (i int);
lock tables t1 read;
create temporary table t2 (j int);
drop temporary table t2;
unlock tables;
drop table t1;
```

### 2. What did you expect to see? (Required)
```sql
mysql> create temporary table t2 (j int);
Query OK, 0 rows affected (0.00 sec)
```
### 3. What did you see instead (Required)
```sql
mysql> create temporary table t2 (j int);
ERROR 1100 (HY000): Table 't2' was not locked with LOCK TABLES
```
### 4. What is your TiDB version? (Required)
```sql
| Release Version: v5.5.0-alpha-182-gad9430039
Edition: Community
Git Commit Hash: ad9430039f54bb9af78d44831c176bc5eafcbba0
Git Branch: master
UTC Build Time: 2022-02-04 18:58:58
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by zimulala** [comment]
Since table lock itself can be considered as an invisible feature, it is only used internally (for locking bulk writes), so we will not define this issue as a bug for the time being.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it. You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese) or https://ask.pingcap.com/(English)
