### ISSUE TITLE
collation is different when concat binary and utf8mb4_unicode_ci

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#32361]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table
CREATE TABLE `tbl_12` (
  `col_0` varchar(183) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `col_1` char(63) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_2` tinytext COLLATE utf8mb4_bin NOT NULL,
  `col_3` text CHARACTER SET utf8mb4 NOT NULL,
  `col_4` longtext COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_5` json NOT NULL,
  `col_6` enum('Alice','Bob','Charlie','David') COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_7` set('1','2','3','4') COLLATE utf8mb4_general_ci NOT NULL,
  `col_8` binary  NOT NULL,
  `col_9` varbinary(1) NOT NULL,
  `col_10` blob NOT NULL,
  `col_11` year(4) NOT NULL,
  `col_12` bigint(20) NOT NULL,
  PRIMARY KEY (`col_1`,`col_12`),
  KEY `idx_1` (`col_12`,`col_6`),
  KEY `idx_2` (`col_6`,`col_7`,`col_9`(1),`col_0`)
)
PARTITION BY HASH( `col_12` )
PARTITIONS 2;

 insert into tbl_12 values('ab', 'c', 'dE', 'Fg', 'dsfjoiewiu', '{"a":"b"}','Alice', '1', 'w', 'g', '65535','2022', 111);
2. show collation for concat column
MySQL [lt]> select collation(col_1) from tbl_12;
+--------------------+
| collation(col_1)   |
+--------------------+
| utf8mb4_unicode_ci |
+--------------------+
1 row in set (0.00 sec)

MySQL [lt]> select collation(col_10) from tbl_12;
+-------------------+
| collation(col_10) |
+-------------------+
| binary            |
+-------------------+
1 row in set (0.00 sec)

MySQL [lt]> select collation(col_11) from tbl_12;
+-------------------+
| collation(col_11) |
+-------------------+
| binary            |
+-------------------+
1 row in set (0.00 sec)

MySQL [lt]> select collation(concat(col_1,col_10)) from tbl_12;
+---------------------------------+
| collation(concat(col_1,col_10)) |
+---------------------------------+
| binary                          |
+---------------------------------+
1 row in set (0.01 sec)

MySQL [lt]> select collation(concat(col_1,col_11)) from tbl_12;
+---------------------------------+
| collation(concat(col_1,col_11)) |
+---------------------------------+
| utf8mb4_unicode_ci              |
+---------------------------------+
1 row in set (0.01 sec)

MySQL [lt]> 

### 2. What did you expect to see? (Required)
collation for col_1  is utf8mb4_unicode_ci
collation for col_10  is binary
collation for col_11  is binary
collation for concat(col_1,col_10) is binary
but collation for concat(col_1,col_11) is utf8mb4_unicode_ci
why?
 collation for concat(col_1,col_11) should be binary too?
### 3. What did you see instead (Required)
 collation for concat(col_1,col_11) is utf8mb4_unicode_ci
and result in MySQL is same with tidb
### 4. What is your TiDB version? (Required)

| Release Version: v5.5.0-alpha
Edition: Community
Git Commit Hash: adcaaa5cbe1058da8f363c173521929405d0ecb6
Git Branch: heads/refs/tags/v5.5.0-alpha
UTC Build Time: 2022-02-08 14:56:30
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by Defined2014** [comment]
The result is same as MySQL. The reason is `coercibility` of year and blob is not same which are 5 and 2. 
MySQL rules: https://dev.mysql.com/doc/refman/8.0/en/charset-collation-coercibility.html
