### ISSUE TITLE
row_data of type errors in Lightning was empty

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#32360]
### 1. Minimal reproduce step (Required)

Enable Lightning's error reporting (set `max-error` to non zero).

Import a table with SQL error (e.g. insert a string to an integer field)

Check the error report

### 2. What did you expect to see? (Required)

The `row_data` in the report indicates the content of the row with error.

### 3. What did you see instead (Required)

The `row_data` just says "`/* ERROR */`".

### 4. What is your TiDB version? (Required)

5.3

**Comment by gozssky** [comment]
Fixed by https://github.com/pingcap/tidb/pull/29537.
