### ISSUE TITLE
table has not been backup, please ensure you has input a correct table name 

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#32400]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table with uppercase letter. `create table T(id int);`
2. use table backup and specify the name with lowercase letter. `tiup br:nightly backup table --db tpcc --table t ...`
3. use table restore and specify the name with lowercase letter.

### 2. What did you expect to see? (Required)
restore successful
### 3. What did you see instead (Required)
restore failed with error `table t has not been backup, please ensure you has input a correct table name`
### 4. What is your TiDB version? (Required)
v5.3.0

**Comment by 3pointer** [comment]
1. backup with table filter is okay.
2. backup and restore both are not case sensitive.
3. but the check in restore https://github.com/pingcap/tidb/blob/88e9f682bf2605e412f73f4e4fb584f9a318a9df/br/pkg/task/restore.go#L228 is case sensitive.

**Comment by 3pointer** [comment]
To fix this issue. I think we can simply transform 
1. `table.Info.Name.O` => `table.Info.Name.L`
2. `db.Info.Name.O` => `db.Info.Name.L`
in `CheckRestoreDBAndTable` and also transform `restoreTables` `restoreSchemas` to lower case. cc @kennytm WDYT?

**Comment by kennytm** [comment]
@3pointer  make sure the change is compatible with the use of `--case-sensitive` flag. rest lgtm.
