### ISSUE TITLE
travis-ci builds in parallel?

### ISSUE THREAD

**Issue by louishust** [pingcap/tidb#3241]
I found many PRs waiting for travis-ci to build, So travis-ci can just work one by one?

**Comment by gaocegege** [comment]
I am afraid that we could not control the logic of travis CI. Travis CI said that it serves all open source projects equally, but how it serves is a black box. Actually I think no one knows how many concurrent jobs the project gets.

ref https://github.com/travis-ci/travis-ci/issues/4915
