### ISSUE TITLE
Power BI connect TiDB have error "MySQL : FUNCTION UTC_TIME does noe exist"

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tidb#3244]
Power BI connect TiDB have error "MySQL : FUNCTION UTC_TIME does noe exist"

TIDB-server version d81e4ece5d267cce2c88376b1e398ac967e9c0ab

**Comment by shenli** [comment]
@buggithubs Thanks for your feedback!
Please update your tidb-server to the latest version. We have `UTC_TIME` now. :)

mysql> select UTC_TIME();
+------------+
| UTC_TIME() |
+------------+
| 05:27:49   |
+------------+
1 row in set (0.01 sec)
