### ISSUE TITLE
The result of inl_merge_join not correct

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#32467]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

source [1.txt](https://github.com/pingcap/tidb/files/8095511/1.txt)
SELECT /*+ inl_merge_join (t,t2) */ count(*) from t inner join t2 on t.a=t2.a;
### 2. What did you expect to see? (Required)
434
### 3. What did you see instead (Required)
665
### 4. What is your TiDB version? (Required)

Release Version: v5.5.0-nightly
Edition: Community
Git Commit Hash: 61986869ea1928547c1ad8f90f2a072244df6333
Git Branch: heads/refs/tags/v5.5.0-nightly
UTC Build Time: 2022-02-18 06:11:11
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by ChenPeng2013** [comment]
I replace latin with utf8mb4, the result still is wrong，so the severity be set to critical

**Comment by zanmato1984** [comment]
`inl_merge_join` is deprecated, and it's not in document either. Consider this not an issue.

Similar one: https://github.com/pingcap/tidb/issues/33612.

Closing.
