### ISSUE TITLE
Default collation causes inconsistent results 

### ISSUE THREAD

**Issue by where2me** [pingcap/tidb#32480]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
### 1. Minimal reproduce step (Required)
From the official document, I learned TiDB defaults to using a binary collation. I try the following two cases:
case 1:
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0(c0 DECIMAL);
INSERT INTO t0 VALUES(NULL);
UPDATE t0 SET c0 = 1 WHERE (t0.c0 IS NULL)>>('' COLLATE 'binary');
```
case 2:
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0(c0 DECIMAL);
INSERT INTO t0 VALUES(NULL);
UPDATE t0 SET c0 = 1 WHERE (t0.c0 IS NULL)>>('');
```

### 2. What did you expect to see? (Required)
I think case 1 and case 2 should both succeed or fail.
### 3. What did you see instead (Required)
case 2 failed and generated an error.
```sql
mysql> UPDATE t0 SET c0 = 1 WHERE (t0.c0 IS NULL)>>('');
ERROR 1292 (22007): Truncated incorrect INTEGER value: ''
```
### 4. What is your TiDB version? (Required)

mysql> SELECT tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()
                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by Defined2014** [comment]
> TiDB defaults to using a binary collation. This differs from MySQL, which uses a case-insensitive collation by default.

`A binary collation` means a collation with the suffix `_bin` like `utf8mb4_bin`, `utf8_bin` etc.

**Comment by solotzg** [comment]
In current master, both cases are failed.
```
MySQL [test]> UPDATE t0 SET c0 = 1 WHERE (t0.c0 IS NULL)>>('' COLLATE 'binary');
ERROR 1253 (42000): COLLATION 'binary' is not valid for CHARACTER SET 'utf8'
```
```
MySQL [test]> UPDATE t0 SET c0 = 1 WHERE (t0.c0 IS NULL)>>('');
ERROR 1292 (22007): Truncated incorrect INTEGER value: ''
```

**Comment by solotzg** [comment]
In tidb master, it has been fixed.

```
MySQL [mysql]> DROP TABLE IF EXISTS t0;
Query OK, 0 rows affected, 1 warning (0.00 sec)

MySQL [mysql]> CREATE TABLE t0(c0 DECIMAL);
= 1 WHERE (t0.c0 IS NULL)>>('' COLLATE 'binary');Query OK, 0 rows affected (0.07 sec)

MySQL [mysql]> INSERT INTO t0 VALUES(NULL);
Query OK, 1 row affected (0.00 sec)

MySQL [mysql]> UPDATE t0 SET c0 = 1 WHERE (t0.c0 IS NULL)>>('' COLLATE 'binary');
ERROR 1253 (42000): COLLATION 'binary' is not valid for CHARACTER SET 'utf8'
```

----

Analyze ...

tidb master
```
MySQL [mysql]> select * from mysql.tidb where VARIABLE_NAME='new_collation_enabled';
+-----------------------+----------------+----------------------------------------------------+
| VARIABLE_NAME         | VARIABLE_VALUE | COMMENT                                            |
+-----------------------+----------------+----------------------------------------------------+
| new_collation_enabled | True           | If the new collations are enabled. Do not edit it. |
+-----------------------+----------------+----------------------------------------------------+
```

tidb <= 5.4
```
MySQL [mysql]> select * from mysql.tidb where VARIABLE_NAME='new_collation_enabled';
+-----------------------+----------------+----------------------------------------------------+
| VARIABLE_NAME         | VARIABLE_VALUE | COMMENT                                            |
+-----------------------+----------------+----------------------------------------------------+
| new_collation_enabled | False          | If the new collations are enabled. Do not edit it. |
+-----------------------+----------------+----------------------------------------------------+
```

https://github.com/pingcap/tidb/blame/4d888ce22b08b9d2bbc2b66890d35195f666e90b/planner/core/expression_rewriter.go#L1177 If new collation is not enabled, then tidb won't check collation.

**Comment by zanmato1984** [comment]
This is a collation related issue. Changing to sig/sql-infra.

**Comment by Defined2014** [comment]
close this issue, you can see the explation [link](https://github.com/pingcap/tidb/issues/32480#issuecomment-1160085626)
