### ISSUE TITLE
analyze version 2 memory leak

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#32499]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Found in our customer's environment,  oncall 3776

![](https://user-images.githubusercontent.com/1420062/136778535-f911355d-f592-4157-a4e3-f81d5e9115a4.png)

### 2. What did you expect to see? (Required)

No memory leak, no OOM...

### 3. What did you see instead (Required)

Unexpected memory occupation

### 4. What is your TiDB version? (Required)

release-5.1
release-5.2

**Comment by chrysan** [comment]
Should be related to a known issue which is enhanced in v5.3 https://github.com/pingcap/tidb/pull/28999

**Comment by tiancaiamao** [comment]
This is a solved issue... we are writing the release note and find this PR without related issue, so I create one.
