### ISSUE TITLE
Run the unstable test cases seperately

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#32524]
## Enhancement

There are some unstable test cases, for example https://github.com/pingcap/tidb/issues/32303

A simple fail makes the whole UT fail.
We need to fix those unstable cases, but it takes time.

Maybe we can make a `unstable.txt` list, and run the stable test cases and unstable test cases seperately, according to the list.

***Note, we still run the unstable test cases, just  in another way.***

And after we fix a unstable test, we can remove it from the unstable list.

**Comment by tiancaiamao** [comment]
The unstable list can be found here https://github.com/pingcap/tidb/blob/master/unstable.txt

**Comment by tisonkun** [comment]
@tiancaiamao why to pin a closed issue?
