### ISSUE TITLE
make dev failed with golang 1.7.5

### ISSUE THREAD

**Issue by louishust** [pingcap/tidb#3252]
When run make dev with golang 1.7.5, there are some test failed.
But with 1.8.1, all pass.

Cause some code use the new function in 1.8.1 such as sort.Slice.

I think we should modify the CONTRIBUTING.md to note the golang version.

**Comment by shenli** [comment]
@louishust Thanks for your feedback! We are migrating to go1.8 now.
Would you send us a PR to correct the document?

**Comment by louishust** [comment]
@shenli ok, i'll give a PR

**Comment by shenli** [comment]
Cool! @louishust

**Comment by louishust** [comment]
@shenli  #3254
