### ISSUE TITLE
unstable test in the TestConcurrentLoadHistTimeout

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#32580]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
--- FAIL: TestConcurrentLoadHistTimeout (1.92s)
    assertion_compare.go:313: 
        	Error Trace:	handle_hist_test.go:130
        	Error:      	"0" is not greater than "0"
        	Test:       	TestConcurrentLoadHistTimeout
        	Messages:   	[]
```

https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_unit_test/detail/tidb_ghpr_unit_test/37572/tests

**Comment by tiancaiamao** [comment]
Still unstable https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-hourly/detail/tidb-unit-test-hourly/5740/pipeline
reopen it 2022.8.23

@chrysan

**Comment by hawkingrei** [comment]
This problem has been created at #36584.

**Comment by tiancaiamao** [comment]
> This problem has been created at #36584.

OK, let's use that one to trace it.
