### ISSUE TITLE
`STRCMP` function shows inconsistent behavior with MySQL

### ISSUE THREAD

**Issue by espresso98** [pingcap/tidb#32603]
## Bug Report
`STRCMP` function returns 0 if the strings are the same, -1 if the first argument is smaller than the second according to the current sort order, and 1 otherwise.

### 1. Minimal reproduce step 
```sql
CREATE TABLE t1 (a char(10) character set utf8 not null);
INSERT INTO t1 VALUES ('a'),('a\0'),('a\t'),('a ');
SELECT hex(a),STRCMP(a,'a'), STRCMP(a,'a ') FROM t1;
```

### 2. What did you expect to see?
```SQL
mysql> SELECT hex(a),STRCMP(a,'a'), STRCMP(a,'a ') FROM t1;
+--------+---------------+----------------+
| hex(a) | STRCMP(a,'a') | STRCMP(a,'a ') |
+--------+---------------+----------------+
| 61     |             0 |              0 |
| 6100   |            -1 |             -1 |
| 6109   |            -1 |             -1 |
| 61     |             0 |              0 |
+--------+---------------+----------------+
```

### 3. What did you see instead 
```sql
tidb> SELECT hex(a),STRCMP(a,'a'), STRCMP(a,'a ') FROM t1;
+--------+---------------+----------------+
| hex(a) | STRCMP(a,'a') | STRCMP(a,'a ') |
+--------+---------------+----------------+
| 61     |             0 |              0 |
| 6100   |             1 |              1 |
| 6109   |             1 |              1 |
| 61     |             0 |              0 |
+--------+---------------+----------------+
```

### 4. What is your TiDB version? 
```
tidb_version(): Release Version: v5.5.0-alpha-210-g11f4ca802
Edition: Community
Git Commit Hash: 11f4ca802083ee38d5972730ba8f9b72395316fb
Git Branch: master
UTC Build Time: 2022-02-24 04:52:01
GoVersion: go1.17.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by aytrack** [comment]
It's depend on the  collation and the padding behavior
> The implementation of padding in TiDB is different from that in MySQL. In MySQL, padding is implemented by filling in spaces. In TiDB, padding is implemented by cutting out the spaces at the end. The two approaches are the same in most cases. The only exception is when the end of the string contains characters that are less than spaces (0x20). For example, the result of 'a' < 'a\t' in TiDB is 1, but in MySQL, 'a' < 'a\t' is equivalent to 'a ' < 'a\t', and the result is 0.
