### ISSUE TITLE
Unnecessary warning from querying an empty table.

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#32628]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
DROP TABLE IF EXISTS t0;
CREATE TABLE t0 (c0 INT);
SELECT c0 FROM t0 WHERE 'a' > 0;
SHOW WARNINGS;
```

### 2. What did you expect to see? (Required)
I think SELECT should not throw a warning because the table is empty. Moreover, I try the following UPDATE statement, which does not  throw a warning.
```sql
UPDATE t0 SET c0 = 1 WHERE 'a' > 0;
SHOW WARNINGS;
```
### 3. What did you see instead (Required)
SELECT throws a warning.
```sql
mysql> SHOW WARNINGS;
+---------+------+---------------------------------------+
| Level   | Code | Message                               |
+---------+------+---------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'a' |
+---------+------+---------------------------------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by fanrenhoo** [comment]
I checked, this issue might make no much sense. The normal real cases with empty result is correct, But in the propsed issue, query with 'a' for INT, return a warning,  if use INT will right, so may not be perfect, but still not so wrong. I think no need to fix this.

**Comment by bestwoody** [comment]
The result in MySQL is the same as that in TiDB.

For MySQL8.0:
mysql> DROP TABLE IF EXISTS t0;
Query OK, 0 rows affected (0.05 sec)

mysql> CREATE TABLE t0 (c0 INT);
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT c0 FROM t0 WHERE 'a' > 0;
Empty set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+---------------------------------------+
| Level   | Code | Message                               |
+---------+------+---------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: 'a' |
+---------+------+---------------------------------------+
1 row in set (0.00 sec)
