### ISSUE TITLE
Select convert(), cast() with error message.

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3267]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
MySQL [test]> select cast(rand()*100000 as int);
ERROR 1105 (HY000): line 0 column 32 near ")" (total length 33)
MySQL [test]> select convert(rand()*100000, int);
ERROR 1105 (HY000): line 0 column 33 near ")" (total length 34)

2. What did you expect to see?
1234
5678
random numbers.

3. What did you see instead?
error message.
ERROR 1105 (HY000): line 0 column 33 near ")" (total length 34)

4. What version of TiDB are you using (`tidb-server -V`)?
2017/05/15 06:16:47 printer.go:32: [info] Version:
2017/05/15 06:16:47 printer.go:33: [info] Git Commit Hash: b2a7b8735f86c46713b160209d260b783957146d
2017/05/15 06:16:47 printer.go:34: [info] UTC Build Time:  2017-05-13 04:52:43

**Comment by shenli** [comment]
@DavisLinDB Thanks for your feedback!

**Comment by bobotu** [comment]
But I see MySQL 5.7 also return syntax error. And many online MySQL syntax checker also return syntax error. @DavisLinDB

**Comment by DavisLinDB** [comment]
Ok, maybe just MariaDB can use.
