### ISSUE TITLE
Error while start tidb-server.

### ISSUE THREAD

**Issue by free-hawk** [pingcap/tidb#3269]
2017/05/15 17:36:43 printer.go:31: [info] Welcome to TiDB.
2017/05/15 17:36:43 printer.go:32: [info] Version:
2017/05/15 17:36:43 printer.go:33: [info] Git Commit Hash: 10fc9fcd442629105cbedc072358775fe55e96c9
2017/05/15 17:36:43 printer.go:34: [info] UTC Build Time:  2017-05-04 12:07:59
2017/05/15 17:36:43 client.go:96: [info] [pd] create pd client with endpoints [10.10.16.71:2379]
2017/05/15 17:36:43 client.go:186: [info] [pd] leader switches to: http://10.10.16.70:2379, previous:
2017/05/15 17:36:43 client.go:114: [info] [pd] init cluster id 6420288802062381267
2017/05/15 17:36:43 gc_worker.go:104: [info] [gc worker] 5702dde32440002 start.
2017/05/15 17:36:58 txn.go:169: [info] [kv] Rollback txn 391863599930540035
2017/05/15 17:36:58 session.go:953: [fatal] check bootstrapped err [try again later]: backoffer.maxSleep 15000ms is exceeded, errors:
stale_epoch:<>
not leader: region_id:2 , ctx: region_id:2 region_epoch:<conf_ver:2 version:1 > peer:<id:3 store_id:1 >
stale_epoch:<>

**Comment by shenli** [comment]
@free-hawk Please check the status and log of pd-server and tikv-server.

**Comment by free-hawk** [comment]
2017/05/15 17:50:59.910 server.rs:179: [WARN] remove store connection for store 4 with token Token(1148)
2017/05/15 17:51:03.907 raft.rs:909: [INFO] [region 2] 3 is starting a new election at term 138
2017/05/15 17:51:03.907 raft.rs:694: [INFO] [region 2] 3 became candidate at term 139
2017/05/15 17:51:03.907 raft.rs:782: [INFO] [region 2] 3 received MsgRequestVoteResponse from 3 at term 139
2017/05/15 17:51:03.907 raft.rs:762: [INFO] [region 2] 3 [logterm: 6, index: 7] sent MsgRequestVote request to 5 at term 139
2017/05/15 17:51:03.910 server.rs:460: [INFO] resolve store 4 address ok, addr 10.10.0.49:20160
2017/05/15 17:51:17.106 raft.rs:909: [INFO] [region 2] 3 is starting a new election at term 139
2017/05/15 17:51:17.106 raft.rs:694: [INFO] [region 2] 3 became candidate at term 140
2017/05/15 17:51:17.107 raft.rs:782: [INFO] [region 2] 3 received MsgRequestVoteResponse from 3 at term 140
2017/05/15 17:51:17.107 raft.rs:762: [INFO] [region 2] 3 [logterm: 6, index: 7] sent MsgRequestVote request to 5 at term 140

**Comment by shenli** [comment]
@free-hawk Please make sure pd-server/tikv-server is in the right status. You can try to start tidb-server now.

**Comment by free-hawk** [comment]
@shenli I removed 10.10.0.49, It's not in 10.60.81.*.  I can start tidb-server now.

**Comment by shenli** [comment]
@free-hawk Great!
