### ISSUE TITLE
Incompatible result with MySQL in UPDATE statement

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#32718]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
DROP TABLE IF EXISTS t0; 
CREATE TABLE t0 (c0 INT); 
INSERT INTO t0 VALUES (1);
UPDATE t0 SET c0 = 2 WHERE 1 | BIN(100000000);
```

### 2. What did you expect to see? (Required)
The UPDATE should succeed as MySQL does.
### 3. What did you see instead (Required)
```sql
mysql> UPDATE t0 SET c0 = 2 WHERE 1 | BIN(100000000);
ERROR 1690 (22003): BIGINT value is out of range in '101111101011110000100000000'
```
### 4. What is your TiDB version? (Required)
```sql
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by gengliqi** [comment]
Maybe it's a bug in MySQL.

For another case:
``` sql
mysql> CREATE TABLE t0 (c0 BIGINT);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t0 VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> UPDATE t0 SET c0 = BIN(100000000);
ERROR 1264 (22003): Out of range value for column 'c0' at row 1

mysql> UPDATE t0 SET c0 = 1 | bin(100000000);
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> SELECT * from t0;
+---------------------+
| c0                  |
+---------------------+
| 9223372036854775807 |
+---------------------+
1 row in set (0.00 sec)
```
I dive into the MySQL code to find out the reason.
The function of casting string to int in MySQL ignores the out-of-range error. (https://github.com/mysql/mysql-server/blob/0cd98bdf981583a1cf4cb526581fc16e23bb839b/sql/item_strfunc.cc#L148-L159).
So `UPDATE t0 SET c0 = 1 | bin(100000000)` can succeed.

However, `UPDATE t0 SET c0 = BIN(100000000);` does not enter into the function of casting string to int but enters into here. (https://github.com/mysql/mysql-server/blob/0cd98bdf981583a1cf4cb526581fc16e23bb839b/sql/field.cc#L1430-L1455). 
So the out-of-range error can occur here.

In TiDB, both two SQL will enter into the function of casting string to int.

**Comment by zanmato1984** [comment]
I think our implementation is more self-consistent than MySQL. What do you think? @espresso98

**Comment by morgo** [comment]
I think the test case can be simplified to:
```sql
select 1 | BIN(100000000);
select 1 | BIN(1000000000000);
```

In TiDB this is a warning, versus in MySQL there is no warning. The warning in the context of an `UPDATE` statement gets converted to an error for strict mode.

I agree its a MySQL bug: the `bin` func in MySQL will not handle out of range correctly, which could cause other problems. TiDB improves upon it by returning the warning.

**Comment by gengliqi** [comment]
@morgo I agree it's a MySQL bug. 
BTW, the `bin` function can not get out of range error because it generates a string value. The bug should be in the function of casting a string to an integer.

**Comment by zanmato1984** [comment]
I think this issue is concluded and I'm closing it. Thanks all!
