### ISSUE TITLE
Wrong query result 

### ISSUE THREAD

**Issue by TarmoKople** [pingcap/tidb#32716]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Enable new_collation_framework (**new_collations_enabled_on_first_bootstrap = true**)

```
mysql> create table test (c varchar(5));
Query OK, 0 rows affected (0,10 sec)

mysql> insert into test (c) values ('1234');
Query OK, 1 row affected (0,02 sec)

mysql> select * from test where c='1234    ';
+------+
| c    |
+------+
| 1234 |
+------+
1 row in set, 1 warning (0,00 sec)
```

### 2. What did you expect to see? (Required)

```
mysql> select * from test where c='1234    ';
Empty set (0,00 sec)

```
### 3. What did you see instead (Required)
```
mysql> select * from test where c='1234    ';
+------+
| c    |
+------+
| 1234 |
+------+
1 row in set, 1 warning (0,00 sec)
```
Warning and wrong row

### 4. What is your TiDB version? (Required)
Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306

Tested versions v5.1.0 - v5.4.0, all versions return wrong query result

Explain output looks normal, seems that this error might be caused by TiKV
```
+-------------------------+---------+-----------+---------------+--------------------------------+
| id                      | estRows | task      | access object | operator info                  |
+-------------------------+---------+-----------+---------------+--------------------------------+
| TableReader_7           | 0.00    | root      |               | data:Selection_6               |
| └─Selection_6           | 0.00    | cop[tikv] |               | eq(test.test.c, "1234   ")     |
|   └─TableFullScan_5     | 1.00    | cop[tikv] | table:test    | keep order:false, stats:pseudo |
+-------------------------+---------+-----------+---------------+--------------------------------+
```

**Comment by mjonss** [comment]
This is wrong result, so I think it should have severity/critical.

**Comment by djshow832** [comment]
The reason is that the default collation of charset `utf8mb4` is different in MySQL and TiDB, which is announced in the document: 
> The default collations in TiDB (binary collations, with the suffix _bin) are different than [the default collations in MySQL](https://dev.mysql.com/doc/refman/8.0/en/charset-charsets.html) (typically general collations, with the suffix _general_ci). This can cause incompatible behavior when specifying an explicit character set but relying on the implicit default collation to be chosen.

**Comment by bb7133** [comment]
@TarmoKople Thanks for reporting it, I will close this issue since the behavior is expected. Feel free to re-open it if you have any further concern/question.

/cc @mjonss @djshow832
