### ISSUE TITLE
copr-test failed due to functions push down

### ISSUE THREAD

**Issue by Yisaer** [pingcap/tidb#32739]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run copr-test with `WithPushDown` test

### 2. What did you expect to see? (Required)

test success

### 3. What did you see instead (Required)

test failed due to `dayname`, `lastday` and `truncate` push down

### 4. What is your TiDB version? (Required)

master

**Comment by Yisaer** [comment]
We also find `left` caused  error in https://github.com/pingcap/tidb/issues/33255 https://github.com/pingcap/tidb/issues/33256

**Comment by Yisaer** [comment]
`tan` and `yearWeek` will cause cor-test failed in sometimes (not stable reporcedued, can't reproduced locally) https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_integration_copr_test/detail/tidb_ghpr_integration_copr_test/8812/pipeline/

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
