### ISSUE TITLE
Inner error happened in BIN function with | operator

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#32741]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
DROP TABLE IF EXISTS t0; 
CREATE TABLE t0 (c0 INT); 
INSERT INTO t0 VALUES (1);
SELECT * FROM t0 WHERE 1 | BIN(524288); 
SHOW WARNINGS;
```

### 2. What did you expect to see? (Required)
This error code may not return to users.
### 3. What did you see instead (Required)
```sql
mysql> SHOW WARNINGS;
+---------+------+------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                            |
+---------+------+------------------------------------------------------------------------------------+
| Warning | 8030 | Cast to signed converted positive out-of-range integer to it's negative complement |
+---------+------+------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)
```sql
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()

                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by sayJason** [comment]
I try other numbers for the BIN function. Any number in the range of 524287 and 1048576 will cause this inner error.

**Comment by bestwoody** [comment]
the reason why TiDB produce a warning is that BIN(524288) is a string "10000000000000000000", and 1 | "10000000000000000000" is 10000000000000000001 caused overflow of 64-bit. However, mysql produce a incorrect answer without any warning/error info. And it produce a max 64-bit signed integer instead, MySQL actually has overflowed( from 10000000000000000000 to 9223372036854775807), but it didn't produce a error info.

**Comment by sayJason** [comment]
> the reason why TiDB produce a warning is that BIN(524288) is a string "10000000000000000000", and 1 | "10000000000000000000" is 10000000000000000001 caused overflow of 64-bit. However, mysql produce a incorrect answer without any warning/error info. And it produce a max 64-bit signed integer instead, MySQL actually has overflowed( from 10000000000000000000 to 9223372036854775807), but it didn't produce a error info.

Yes, you're right. The overflow did happen in this case. Is there any a better way to display this information? I've noticed that it is an inner error that should return to the user.

**Comment by sayJason** [comment]
By the way, UPDATE and DELETE statement can succeed with this warning as mentioned in https://github.com/pingcap/tidb/issues/34051, Should this warning be an error in UPDATE and DELETE, especially when enabling strict SQL mode?

**Comment by bestwoody** [comment]
> strict SQL mode

you can execute "select 1|bin(524288)" or other exprs to see the result in MySQL or TiDB.

**Comment by bestwoody** [comment]
> #34051

you misunderstand the meaning of "strict SQL mode", you can refer to: [doc](https://dev.mysql.com/doc/refman/8.0/en/sql-mode.html#sql-mode-strict).   strict SQL will work when the value to be inserted or updated is out of range. However, for statement `"UPDATE t0 SET c0 = 2 WHERE 1 | BIN(524288);"` , `c0` is a normal value even though value in `where` condition is out of range. So it will succeed in strict SQL mode.  If the statement is `"UPDATE t0 SET c0 = 1 | BIN(524288);"`, that will fail since `c0` is out of range.

**Comment by bestwoody** [comment]
I'll close this issue, since result is correct and strict SQL both success between MySQL and TiDB.
