### ISSUE TITLE
support kill auto analyze

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#32808]
## Enhancement

Auto analyze is triggered when modify_count / count reaches threshold or a new index is added. Auto analyze may consume lots of resources and affect performance. We hope that there is a way to kill auto analyze once we find it affects performance. One way to do that is to let `show processlist` display the session running auto analyze and then execute `kill tidb id` to kill auto analyze.

**Comment by Icemap** [comment]
I guess you can using tidb-server config [run-auto-analyze](https://docs.pingcap.com/zh/tidb/stable/tidb-configuration-file#run-auto-analyze) to close auto analyze feature.
Is this exactly what you want? Please give us more information.

**Comment by Icemap** [comment]
Hmmmm…… Forget that, I found your PR. You can mention this issue in your PR to avoid others confused.
