### ISSUE TITLE
What's problem for : too many open files?

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3282]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

3 PDs
3 TiKVs
3 TiDBs
1 HAProxy for 3 TiDBs load balancing.

each VM: 8x vCore, 50G Ram, 256G SSD

another 5 VMs with apache and PHP.
testti.php which insert one record to testdata table and one record to customer table connect to HAProxy.
Then I use ab to test.
Test command is:
ab -n 100000 -c 100 -k http://localhost/testti.php

It's ok for use 1~4 VMs to test.
I can not finish 5 VMs test.
Error message is:
2017/05/17 04:23:23 server.go:171: [error] accept error accept tcp [::]:4000: accept4: too many open files
2017/05/17 04:23:23 main.go:174: [error] accept tcp [::]:4000: accept4: too many open files 
If the problem occurs, all 3 TiDBs stop.

What's problem and how to fix?

2. What did you expect to see?
Finish test.

3. What did you see instead?
TiDB stop.
error log:
2017/05/17 04:23:23 server.go:171: [error] accept error accept tcp [::]:4000: accept4: too many open files
2017/05/17 04:23:23 main.go:174: [error] accept tcp [::]:4000: accept4: too many open files 

4. What version of TiDB are you using (`tidb-server -V`)?
2017/05/17 04:24:38 printer.go:32: [info] Version:
2017/05/17 04:24:38 printer.go:33: [info] Git Commit Hash: b2a7b8735f86c46713b160209d260b783957146d
2017/05/17 04:24:38 printer.go:34: [info] UTC Build Time:  2017-05-13 04:52:43

**Comment by DavisLinDB** [comment]
I saw this setting in tikv.toml:
# max-open-files = 40960

If I set it larger, can fix the problem?
Any suggest value?

**Comment by shenli** [comment]
@DavisLinDB Please use `ulimit` to enlarge the max open file limitation of the machine which you run tidb-server.

**Comment by DavisLinDB** [comment]
@shenli 

Thank your for reply, problem solved.  

I have another problem for a test case.

testdata table has 100M+ records, 

mysql -h 10.140.0.22 -u root -p -P 4000 --connect-timeout=180 test

I execute the statement:
select count(*),sum(agold),sum(bgold) from testdata where adddate between '20160510' and '20160520';

I got the message after 30 seconds:
ERROR 2013 (HY000): Lost connection to MySQL server during query

MySQL has my.cfg to change setting, and how to change TiDB setting?
