### ISSUE TITLE
Changes to GLOBAL scoped variables will apply to old connection sessions with TiDB

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tidb#32862]
## Bug Report

Changes to GLOBAL scoped variables will apply to old connection sessions with TiDB
### 1. Minimal reproduce step (Required)
session A:
MySQL [test]> show session variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 128   |
+---------------------------+-------+
1 row in set (0.02 sec)

MySQL [test]> show global variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 128   |
+---------------------------+-------+
1 row in set (0.02 sec)
Session B:
MySQL [(none)]> set global tidb_ddl_reorg_batch_size=512;
Query OK, 0 rows affected (0.02 sec)

MySQL [(none)]> show session variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+
1 row in set (0.01 sec)

MySQL [(none)]> show global variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+
1 row in set (0.02 sec)

Session A:
MySQL [test]> show global variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+
1 row in set (0.01 sec)

MySQL [test]> show session variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+

### 2. What did you expect to see? (Required)
Session A:
MySQL [test]> show session variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 128   |
+---------------------------+-------+
1 row in set (0.02 sec)

MySQL [test]> show global variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+
1 row in set (0.02 sec)
### 3. What did you see instead (Required)
MySQL [test]> show session variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+
1 row in set (0.02 sec)

MySQL [test]> show global variables like 'tidb_ddl_reorg_batch_size';
+---------------------------+-------+
| Variable_name             | Value |
+---------------------------+-------+
| tidb_ddl_reorg_batch_size | 512   |
+---------------------------+-------+
1 row in set (0.02 sec)

**Comment by Defined2014** [comment]
It's by design. `tidb_ddl_reorg_batch_size` only have `global` scope. From the MySQL SHOW VARIABLES Statement [doc](https://dev.mysql.com/doc/refman/8.0/en/show-variables.html)
> With a SESSION modifier, the statement displays the system variable values that are in effect for the current connection. If a variable has no session value, the global value is displayed. LOCAL is a synonym for SESSION.

**Comment by Defined2014** [comment]
> It's by design. `tidb_ddl_reorg_batch_size` only have `global` scope. From the MySQL SHOW VARIABLES Statement [doc](https://dev.mysql.com/doc/refman/8.0/en/show-variables.html)
> 
> > With a SESSION modifier, the statement displays the system variable values that are in effect for the current connection. If a variable has no session value, the global value is displayed. LOCAL is a synonym for SESSION.

@morgo Do you think we need improve our doc about this issue?

**Comment by morgo** [comment]
I have some plans to improve it in the proposal here: https://github.com/pingcap/tidb/blob/master/docs/design/2021-12-08-instance-scope.md#documentation-changes

We are very close to MySQL behavior for session and global variables. It is only instance scope that I have trouble explaining clearly to MySQL users.
