### ISSUE TITLE
Upgrade go version to 1.18

### ISSUE THREAD

**Issue by purelind** [pingcap/tidb#32874]
## Enhancement
Upgrade go version to 1.18

**Comment by bb7133** [comment]
PTAL  @hawkingrei

**Comment by rleungx** [comment]
There are several issues when using `golangci-lint` with 1.18. More compatibility issues can be found in https://github.com/golangci/golangci-lint/pull/2438

**Comment by hawkingrei** [comment]
> There are several issues when using `golangci-lint` with 1.18. More compatibility issues can be found in [golangci/golangci-lint#2438](https://github.com/golangci/golangci-lint/pull/2438)

You can update the image except for linter.

**Comment by purelind** [comment]
ci pipeline on master branch has upgrade go version from go1.16 go go1.18.
