### ISSUE TITLE
Parser failed in `testAddColumn`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#3287]
[parser:1]syntax error, unexpected ‘?’
 s.testAddColumn(c)
```
/home/jenkins/workspace/iancaiamao_check-localstore-go/src/github.com/pingcap/tidb/util/testkit/testkit.go:130:
    tk.c.Assert(err, check.IsNil, check.Commentf(“sql:%s, %v”, sql, args))
... value *errors.Err = &errors.Err{message:“”, cause:(*terror.Error)(0xc4224e5900), previous:(*errors.Err)(0xc4224e5ae0), file:“/home/jenkins/workspace/iancaiamao_check-localstore-XB63HORLWVBFC4ENXNZD5S5APAER4TO7CAJM7MYTWURDGV5JR3JQ/go/src/github.com/pingcap/tidb/util/testkit/testkit.go”, line:104} (“[parser:1]syntax error, unexpected ‘?’“)
... sql:commit, []
```

**Comment by louishust** [comment]
Did this bug fixed?

My PR on travis got failed as following, but on my laptop make dev pass!

> ----------------------------------------------------------------------
> FAIL: tidb_test.go:78: TidbTestSuite.TestPreparedString
> tidb_test.go:80:
>     runTestPreparedString(c)
> server_test.go:108:
>     dbt.Assert(err, IsNil, Commentf("Query %s", query))
> ... value *mysql.MySQLError = &mysql.MySQLError{Number:0x451, Message:"syntax error, unexpected '?'"} ("Error 1105: syntax error, unexpected '?'")
> ... Query select * from test where 1 = ?
> 
Caused by this bug?

[https://travis-ci.org/pingcap/tidb/jobs/233483119](travis job)

**Comment by zimulala** [comment]
I think they are the same bug. And we are fixing this bug.

**Comment by zimulala** [comment]
@louishust
