### ISSUE TITLE
make dev failed

### ISSUE THREAD

**Issue by louishust** [pingcap/tidb#3289]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
make dev

2. What did you expect to see?
pass

3. What did you see instead?

> FAIL: tidb_test.go:62: TidbTestSuite.TestRegression
> 
> tidb_test.go:65:
>     runTestRegression(c, "Regression")
> server_test.go:183:
>     dbt.Fatal(err)
> ... Error: Error 1105: syntax error, unexpected '?'

4. What version of TiDB are you using (`tidb-server -V`)?

> ➜  tidb git:(master) ✗ bin/tidb-server -V
> Git Commit Hash: 302aa70f76f469a56f4977aea68a560e16a5370b
> UTC Build Time:  2017-05-17 01:24:16
>

**Comment by louishust** [comment]
Seems the same bug as #3287   ?

**Comment by tiancaiamao** [comment]
Yes, it's the same thing...

**Comment by louishust** [comment]
Duplicate with  #3287
