### ISSUE TITLE
admin recover index miss some rows

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#32915]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
MySQL [test]>  create table t(id bigint(20) primary key, col varchar(255) unique key);
Query OK, 0 rows affected (0.10 sec)

MySQL [test]> insert into t values(9223372036854775807, "test");
Query OK, 1 row affected (0.01 sec)

MySQL [test]> admin recover index t col;
+-------------+------------+
| ADDED_COUNT | SCAN_COUNT |
+-------------+------------+
|           0 |          0 |
+-------------+------------+
1 row in set (0.00 sec)

```

### 2. What did you expect to see? (Required)
SCAN_COUNT should be 1.

### 3. What did you see instead (Required)
<img width="651" alt="截屏2022-03-08 下午6 12 22" src="https://user-images.githubusercontent.com/5906259/157216117-2a358e69-db1d-4159-bab5-d086d0443acc.png">
### 4. What is your TiDB version? (Required)

master

**Comment by 3pointer** [comment]
The root cause is [here](https://github.com/pingcap/tidb/blob/9c64224c4951fdffb05f284b011c48c50c188a04/executor/admin.go#L302). 
`codec.EncodeKey(sctx, nil, types.MaxValueDatum()` is the byte `250` which is not the unlimited end key.

For intHandle it should be`codec.EncodeInt(nil, math.MaxInt64)`

**Comment by wjhuang2016** [comment]
> The root cause is [here](https://github.com/pingcap/tidb/blob/9c64224c4951fdffb05f284b011c48c50c188a04/executor/admin.go#L302). `codec.EncodeKey(sctx, nil, types.MaxValueDatum()` is the byte `250` which is not the unlimited end key.
> 
> For intHandle it should be`codec.EncodeInt(nil, math.MaxInt64)`

250 is fine, since we compare data by its prefix.
The problem is that in our implementation:

> 	// 1. unique-key is duplicate and the handle is equal, skip it.
	// 2. unique-key is duplicate and the handle is not equal, data is not consistent, log it and skip it.
	// 3. non-unique-key is duplicate, skip it.

According to "unique-key is duplicate and the handle is equal, skip it.", the scan row is skipped. We don't count for that.
It's not a bug, but I still think we can improve it.

**Comment by 3pointer** [comment]
> > The root cause is [here](https://github.com/pingcap/tidb/blob/9c64224c4951fdffb05f284b011c48c50c188a04/executor/admin.go#L302). `codec.EncodeKey(sctx, nil, types.MaxValueDatum()` is the byte `250` which is not the unlimited end key.
> > For intHandle it should be`codec.EncodeInt(nil, math.MaxInt64)`
> 
> 250 is fine, since we compare data by its prefix. The problem is that in our implementation:
> 
> > // 1. unique-key is duplicate and the handle is equal, skip it.
> > // 2. unique-key is duplicate and the handle is not equal, data is not consistent, log it and skip it.
> > // 3. non-unique-key is duplicate, skip it.
> 
> According to "unique-key is duplicate and the handle is equal, skip it.", the scan row is skipped. We don't count for that. It's not a bug, but I still think we can improve it.

I don't think so. 
the scanRowCount has been added in `fetchRecoverRows` https://github.com/pingcap/tidb/blob/9c64224c4951fdffb05f284b011c48c50c188a04/executor/admin.go#L385
whether skip or not, it will be recorded.

you can try add another record and the SCAN_COUNT will be 1. (which should be 2)
![image](https://user-images.githubusercontent.com/5906259/157371283-660cf7ed-8a29-4848-a056-e489a13e2136.png)
