### ISSUE TITLE
Can't run a single test in db_change_test.go.

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#32981]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

After this PR（https://github.com/pingcap/tidb/pull/32651）, we can't run a single test in db_change_test.go.
You can only run the `TestStateChange` test, and then run all the tests in this file.

### 2. What did you expect to see? (Required)
```
...
PASS
ok  	github.com/pingcap/tidb/ddl	1.327s
```

### 3. What did you see instead (Required)
```
go test -run TestParallelAlterModifyColumnAndAddPK
testing: warning: no tests to run
PASS
ok  	github.com/pingcap/tidb/ddl	0.817s
```

### 4. What is your TiDB version? (Required)

```
Release Version: v6.0.0-alpha-34-g7408e68a7-dirty
Edition: Community
Git Commit Hash: 7408e68a7503d3f845ddbcb7af3c3f2a6450be27
Git Branch: master
UTC Build Time: 2022-03-10 02:49:13
GoVersion: go1.16.4
```

**Comment by zimulala** [comment]
@tisonkun Please help to confirm this problem.

**Comment by tisonkun** [comment]
It's a usage of testify's suite, which I tend to get rid of these usages later. If you want to run `stateChangeSuite.TestParallelAlterModifyColumnAndAddPK`, use:

```
go test -run TestStateChange/TestParallelAlterModifyColumnAndAddPK
```

**Comment by tisonkun** [comment]
I hope we use testify assertions finally and don't need to understand `-testify.m` as like options :)

Closed as information delivered.
