### ISSUE TITLE
check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 321 near \"\u0000\" 

### ISSUE THREAD

**Issue by wuwo1952368901** [pingcap/tidb#32989]
When using C + + connection, SQL execution will report an error.

Error log：

[INFO] [conn.go:1007] ["command dispatched failed"] [conn=45] [connInfo="id:45, addr:xxx.xxx.xxx.xxx:52760 status:10, collation:latin1_swedish_ci, user:xxx"] [command=Prepare] [status="inTxn:0, autocommit:1"] [sql="CREATE TABLE `table` (`ID` BIGINT UNSIGNED NOT NULL DEFAULT 0,`SID` BIGINT UNSIGNED NOT NULL DEFAULT 0,`Type` INT UNSIGNED NOT NULL DEFAULT 0,`Day` INT UNSIGNED NOT NULL DEFAULT 0) ENGINE=InnoDB CHARACTER SET utf8\u0000"] [txn_mode=PESSIMISTIC] [err="[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 321 near \"\u0000\" "]

**Comment by bb7133** [comment]
Hi @wuwo1952368901 please make a step to reproduce this issue. Thanks.
