### ISSUE TITLE
mysql-connector-java error Variable 'character_set_results' can't be set to the value of 'NULL'

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tidb#32987]
## Bug Report

when i use mysql-connector-java to connect to tidb.
it occurs `java.sql.SQLSyntaxErrorException: Variable 'character_set_results' can't be set to the value of 'NULL'`

- tidb version: build after this commit https://github.com/pingcap/tidb/commit/77730b6d9e28270b5939c68a7135ebf9ad6b478c
- mysql-connector-java: 5.1.44 or 8.0.26. I guess other version may has the same problem

```
public class DBHelper {

  public static final String url = "jdbc:mysql://address=(protocol=tcp)(host=$host)(port=4000)/?user=root&password=&useSSL=false";
  public static final String name = "com.mysql.jdbc.Driver";

  public Connection conn = null;

  public DBHelper() {
    try {
      Class.forName(name);
      conn = DriverManager.getConnection(url);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }

  public static void main(String[] args) {
    DBHelper helper = new DBHelper();
  }


pom:
  <dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.26</version>
  </dependency>

**Comment by Defined2014** [comment]
@morgo Seems some tools depends on this feature, maybe we should revert https://github.com/pingcap/tidb/pull/32879
