### ISSUE TITLE
use coprocessor for loading schema 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#3301]
Now we may meet `information out of date` error in heavy write load. Now the loading schema is still using scheduler KV API, not coprocessor, so the write operations may block the following loading scan operation. And if the lease is small (1s), we may meet this error easily. 

I think using coprocessor for loading the schema is better. 

/cc @shenli

**Comment by coocood** [comment]
The lease is set much longer now, this optimization seems no longer benefit much.
