### ISSUE TITLE
INET6 doesn't work

### ISSUE THREAD

**Issue by guilhermehubner** [pingcap/tidb#3305]
I trying this on the `latest` docker image:

```sql
SELECT inet6_ntoa(inet6_aton('127.0.0.1'))
```

After see this https://github.com/pingcap/tidb/pull/3012, I tried:

```sql
SELECT inet6_nton(inet6_aton('127.0.0.1'))
```

It's doesn't work in both cases. 
In first case: #1305 - FUNCTION INET6_NTOA does not exist
Secound case: #1105 - line 0 column 18 near "inet_aton('127.0.0.1'))" (total length 41)

I have tried with IPv6 value too.

**Comment by shenli** [comment]
@guilhermehubner Thanks for your feedback!
Could you send us a PR to fix this?

**Comment by guilhermehubner** [comment]
@shenli  done
