### ISSUE TITLE
br restore doesn't exit after "epoch not match" error

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#33198]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Do br restore, br encountered "epoch not match" error due to PD issue https://github.com/tikv/pd/issues/4739
```
[import.go:428] ["ingest file failed"] ...[error="[BR:KV:ErrKVEpochNotMatch]epoch not match"] ;
 [ERROR] [client.go:860] ["restore files failed"] [error="rpc error: code = Canceled desc = context canceled"] [errorVerbose="rpc error: code = Canceled desc = context canceled
```

### 2. What did you expect to see? (Required)
1. br should fail and exit when reaching retry limit

### 3. What did you see instead (Required)
1. br doesn't fail and exit when error happens.

### 4. What is your TiDB version? (Required)
Release Version: v6.0.0-nightly
Git Commit Hash: 41fb3e75a51df36100d6dd5083a9332e5a88dc7d
Git Branch: heads/refs/tags/v6.0.0-nightly
Go Version: go1.16.4
UTC Build Time: 2022-03-15 18:10:12
Race Enabled: false

**Comment by 3pointer** [comment]
https://github.com/pingcap/tidb/pull/33201 fix it
