### ISSUE TITLE
alias produces error on insert/update

### ISSUE THREAD

**Issue by hyliu777** [pingcap/tidb#33230]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE `test`  (
  `col` varchar(255) NOT NULL,
  `cnt` int(11) NULL,
  PRIMARY KEY (`col`)
);

INSERT test ( col, cnt ) 
SELECT 
	col,
	IFNULL( cnt, 0 ) AS cnt 
FROM
	( SELECT 'test' col, 1 cnt ) a 
	ON DUPLICATE KEY UPDATE col = a.col,
	cnt = IFNULL( a.cnt, 0 )

### 2. What did you expect to see? (Required)

insert/update correctly

### 3. What did you see instead (Required)

1105 - runtime error: index out of range [1] with length 0

### 4. What is your TiDB version? (Required)

Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:32:39
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by aytrack** [comment]
I can't reprodue this on v5.3.0
```sql
MySQL root@127.0.0.1:test> CREATE TABLE test (
                       ->  col varchar(255) NOT NULL,
                       ->  cnt int(11) NULL,
                       ->  PRIMARY KEY (col)
                       ->  );
                       ->
                       ->  INSERT test ( col, cnt )
                       ->  SELECT
                       ->  col,
                       ->  IFNULL( cnt, 0 ) AS cnt
                       ->  FROM
                       ->  ( SELECT 'test' col, 1 cnt ) a
                       ->  ON DUPLICATE KEY UPDATE col = a.col,
                       ->  cnt = IFNULL( a.cnt, 0 )
Query OK, 0 rows affected
Time: 0.108s

Query OK, 1 row affected
Time: 0.011s
MySQL root@127.0.0.1:test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v5.3.0
Edition: Community
Git Commit Hash: 4a1b2e9fe5b5afb1068c56de47adb07098d768d6
Git Branch: heads/refs/tags/v5.3.0
UTC Build Time: 2021-11-24 13:31:24
GoVersion: go1.16.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

```

**Comment by hyliu777** [comment]
I reproduced it with  the following script

```CREATE TABLE test (
col varchar(255) NOT NULL,
cnt int(11) NULL,
PRIMARY KEY (col)
);

INSERT test ( col, cnt )
SELECT 'test', 2;

INSERT test ( col, cnt )
SELECT
col,
IFNULL( cnt, 0 ) AS cnt
FROM
( SELECT 'test' col, 1 cnt ) a
ON DUPLICATE KEY UPDATE col = a.col,
cnt = IFNULL( a.cnt, 0 )
;```

**Comment by hyliu777** [comment]
@aytrack I reproduced it with  the following script

```CREATE TABLE test (
col varchar(255) NOT NULL,
cnt int(11) NULL,
PRIMARY KEY (col)
);

INSERT test ( col, cnt )
SELECT 'test', 2;

INSERT test ( col, cnt )
SELECT
col,
IFNULL( cnt, 0 ) AS cnt
FROM
( SELECT 'test' col, 1 cnt ) a
ON DUPLICATE KEY UPDATE col = a.col,
cnt = IFNULL( a.cnt, 0 )
;```

**Comment by vivid392845427** [comment]
duplicate with known issue [tidb#28078](https://github.com/pingcap/tidb/issues/28078) , please use the new version.
