### ISSUE TITLE
TiKV cluster not bootstrapped, please start TiKV first>

### ISSUE THREAD

**Issue by lddlww** [pingcap/tidb#33289]
tidb version:
5.3.0

problem:
![image](https://user-images.githubusercontent.com/27006237/159261487-0ed18862-31fa-416d-aecb-cc0b3c25e3aa.png)

what' happend?

**Comment by zhangjinpeng1987** [comment]
@VelocityLight why tikv not started? What's kind of deployment tool you used? tiup or tidb-operator?

**Comment by zhangjinpeng1987** [comment]
The description is too simple to investigate.

**Comment by douglasjpd** [comment]
Hello,

I just follow the doc: "Deploy the TiKV cluster on multiple nodes for testing" from https://tikv.org/docs/7.1/deploy/install/test/, and I set 1 PD, and 2 TIKVs(I tested those commands under root and regular user, same error)

First start: 
[xxx@rocky810 ~]$ ./bin/pd-server --name=pd1 --data-dir=pd1 --client-urls="http://172.16.10.113:2379" --peer-urls="http://172.16.10.113:2380" --initial-cluster="pd1=http://172.16.10.113:2380" --log-file=pd1.log &

Then start:
[xxx@rocky810 ~] ./bin/tikv-server --pd-endpoints="172.16.10.113:2379" --addr="172.16.10.114:20160" --data-dir=tikv1 --log-file=tikv1.log &
			
[xxx@rocky810 ~]$ ./bin/tikv-server --pd-endpoints="172.16.10.113:2379" --addr="172.16.10.115:20160" --data-dir=tikv2 --log-file=tikv2.log &

And go back to PD to execute: 

[xxx@rocky810 ~] $ ./bin/pd-ctl store -u http://172.16.10.113:2379
Failed to get store: [500] "[PD:cluster:ErrNotBootstrapped]TiKV cluster not bootstrapped, please start TiKV first"


the 3 VMs are in the same LAN, and  can ping each other, no firewall setup...

Any hints? Thank you so much
