### ISSUE TITLE
Support mysql error code

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#333]
Sometimes server error code matters. 
Users may try exception and check error type. So we need to support some mysql error codes. 
Some testcases fail because of this. 
 Run 'grep "errors.Error" -r ./ | wc -l'  we get 328 places to handle. So it is a huge project.
- [ ] ErrKeyExists
- [ ] TableNotExists

**Comment by siddontang** [comment]
I think the first one may be key conflict error check. :-)

**Comment by shenli** [comment]
We should first define a map from terror class-code to mysql code. Then when a error occurs in conn.go distpatch(), we convert terror to sqlerror.
