### ISSUE TITLE
auto_increment is a non clustered index， each insert operation consumes 2 increment value

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#33307]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

drop table if exists t8;
CREATE TABLE `t8` (
  `a` int(11) NOT NULL AUTO_INCREMENT,
  `b` varchar(255) DEFAULT NULL,
  `c` varchar(1024) DEFAULT NULL,
  KEY `b` (`b`),
  PRIMARY KEY (`a`) NONCLUSTERED
);
insert into t8(b,c) values('a','a');
insert into t8(b,c) values('a','a');
insert into t8(b,c) values('a','a');
select * from t8; 

### 2. What did you expect to see? (Required)
mysql> select * from t8;
+---+------+------+
| a | b    | c    |
+---+------+------+
| 1 | a    | a    |
| 2 | a    | a    |
| 3 | a    | a    |
+---+------+------+
3 rows in set (0.00 sec)

### 3. What did you see instead (Required)
mysql> select * from t8; 
+---+------+------+
| a | b    | c    |
+---+------+------+
| 1 | a    | a    |
| 3 | a    | a    |
| 5 | a    | a    |
+---+------+------+
3 rows in set (0.00 sec)

### 4. What is your TiDB version? (Required)

Release Version: v6.0.0
Edition: Community
Git Commit Hash: e130e522904106ecf9815fdb3aaccad68dcb5ee0
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-18 10:27:02
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by tangenta** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/982.
