### ISSUE TITLE
how to sync tidb to some other db like solr?

### ISSUE THREAD

**Issue by maruixiang** [pingcap/tidb#3331]
Is there any way? Can syncer do this?

**Comment by shenli** [comment]
@maruixiang `syncer` could not do this. `syncer` is used to syncer binlog from MySQL to TiDB.
A possible way to sync data from TiDB to solr is using TiDB's binlog module. It will output data changing in format of protobuf or sql statement.

**Comment by maruixiang** [comment]
Great! Where can I find the document about  how to use TiDB's binlog module?

**Comment by weirui** [comment]
hello,Is this problem solved?

**Comment by shenli** [comment]
@maruixiang @weirui We have developed a binlog module. Several users are using it in their production environment. If you want to use it, please send a email to shenli@pingcap.com. I will send you the document and download address.

**Comment by weirui** [comment]
ok ,I have sent you an E-mail. Please check it. My mailbox is 1145610975@qq.com

**Comment by weirui** [comment]
@shenli  I have sent you an E-mail. Please check it. My mailbox is 1145610975@qq.com

**Comment by jy4618272** [comment]
@weirui have u get any response from shenli ? can u share with us?

**Comment by MichaelMt66** [comment]
@shenli Hi! can you share with me the documetation you mentioned, plesase. michael.mt66@gmail.com
