### ISSUE TITLE
incremental restore doesn't empty query job.

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#33322]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
It's hard to reproduce it but easy to fix.
because we use `ExecuteInternal` to Execute DDL job queries during incremental restore.
and sometimes this query might be nil. so the [check](https://github.com/pingcap/tidb/blob/9f72bcded79688a9f50f07f4cc76889c534bd633/session/session.go#L1601-L1603) will not pass.

To Fix it we can ignore the empty job.Query in https://github.com/pingcap/tidb/blob/49f291db70a466c1a05718f8068b5234f70db1da/br/pkg/restore/client.go#L750

### 2. What did you expect to see? (Required)
incremental restore succeed.
### 3. What did you see instead (Required)
```
[2022/03/22 11:04:16.790 +08:00] [ERROR] [restore.go:35] ["failed to restore"] [error="[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use run multiple statements internally is not supported"]
```
### 4. What is your TiDB version? (Required)
master

**Comment by WangLe1321** [comment]
There is another problem is sql mode of ddl job. For ddl jobs which don't belong to reorg ddl, there is no sql mode information recorded, and we can only set sql mode '' when execute these ddl jobs during restoring, which may result in errors or hidden bugs.
