### ISSUE TITLE
CI: Travis #Job 2 always fail

### ISSUE THREAD

**Issue by gaocegege** [pingcap/tidb#3335]
We import coverage build in #3150 , but the coverage builds fail all the time. I will take a look.

**Comment by gaocegege** [comment]
It seems that there is no enough memory to finish the build. https://travis-ci.org/pingcap/tidb/jobs/245293286#L298

**Comment by gaocegege** [comment]
https://github.com/pingcap/tidb/pull/4570 succeeds to report result to covealls, it is weird.

**Comment by shenli** [comment]
It seems that there is not enough resource in travis ci. It may success by chance.

**Comment by gaocegege** [comment]
I guess so.

How about migrate the logic to jenkins, since the jenkins build is private in your servers and maybe the capacity is enough

**Comment by gaocegege** [comment]
There is a way to allocate more memory in travis: https://docs.travis-ci.com/user/reference/overview/

```yml
sudo: required
dist: trusty
```

Sudo-enabled VM has 7.5G and default container-based VM has 4G. But since all of the PRs passes the coverage test now, I just closed the issue.

And if we meet the problem again, the way above may be helpful.
