### ISSUE TITLE
Restoring data with BR restore failed after deleting data

### ISSUE THREAD

**Issue by buchuitoudegou** [pingcap/tidb#33387]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create a table and insert 10,000 tuples into it.
2. `bin/br backup` the table to local storage.
3. execute sql `delete from tablename` and delete all data from it.
4. `bin/br restore ... --checksum=false`

### 2. What did you expect to see? (Required)
successfully restore the table.

### 3. What did you see instead (Required)
1. table restoring failed.
2. tikv consumes little CPU resources (which possibly means there is no rewrite happening).

### 4. What is your TiDB version? (Required)

commit 7cf784cf265a1268439a0d401084ffff96b74738

**Comment by joccau** [comment]
The reason for this:

1. The table ID is not changed.
2. The key-value in TiKV
     key(ts1) --- value1(put)           ------- original record
     key(ts2) --- value2(delete).    -------- delete record from table
     key(ts1) --- value1(put)           -------- br restore.

Because of the k-v records from `br restore` has smaller TS than `delete record`, so the operation is successful about `download and ingest sst in restore` but `checksum`.

**Comment by buchuitoudegou** [comment]
> The reason for this:
> 
> 1. The table ID is not changed.
> 2. The key-value in TiKV
>    key(ts1) --- value1(put)           ------- original record
>    key(ts2) --- value2(delete).    -------- delete record from table
>    key(ts1) --- value1(put)           -------- br restore.
> 
> Because of the k-v records from `br restore` has smaller TS than `delete record`, so the operation is successful about `download and ingest sst in restore` but `checksum`.
> 
> Should we deal this Scenes, I consider ?

At least we should get a warning from BR client instead of silently failing and obtain no further info.

**Comment by joccau** [comment]
The result is reasonable in this Scenes. So close it.
