### ISSUE TITLE
Old config no longer works

### ISSUE THREAD

**Issue by kokizzu** [pingcap/tidb#33423]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. git clone https://github.com/kokizzu/hugedbbench 
2. cd `2021/tidb`
3. `docker-compose -f docker-compose-single.yaml up` # or  docker-compose-multi.yaml
4. go test main_test.go

### 2. What did you expect to see? (Required)

no error like in the past, i don't know which version (4 months ago i think)

### 3. What did you see instead (Required)

error for single:
```
tidb_1   | config file /tidb.toml contained invalid configuration options: security.enable-sem, security.auto-tls, security.tls-version, security.rsa-key-size, tikv-client.resolve-lock-lite-threshold, pessimistic-txn.deadlock-history-capacity, pessimistic-txn.deadlock-history-collect-retryable, pessimistic-txn.pessimistic-auto-commit; check TiDB manual to make sure this option has not been deprecated and removed from your TiDB version if the option does not appear to be a typo
```
error for multi:
```
tidb_1   | config file /tidb.toml contained invalid configuration options: security.enable-sem, security.auto-tls, security.tls-version, security.rsa-key-size, tikv-client.resolve-lock-lite-threshold, pessimistic-txn.deadlock-history-capacity, pessimistic-txn.deadlock-history-collect-retryable, pessimistic-txn.pessimistic-auto-commit; check TiDB manual to make sure this option has not been deprecated and removed from your TiDB version if the option does not appear to be a typo
tidb_pd0_1 exited with code 1
tidb_pd0_1 exited with code 1
tidb_pd0_1 exited with code 1
tidb_pd0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_pd0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_pd0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_tikv0_1 exited with code 1
tidb_pd0_1 exited with code 1
tidb_tikv0_1 exited with code 1
```

### 4. What is your TiDB version? (Required)

`pingcap/tidb:latest`
not sure because it won't even start this time

already tried new config that are downloaded from latest master from this link https://docs.pingcap.com/tidb/dev/tidb-configuration-file

**Comment by Defined2014** [comment]
Seems the `pingcap/tidb:latest` is not the latest version for TiDB, you can use `pingcap/tidb:nightly` to get the newest one or use specified release version.
