### ISSUE TITLE
migrate test-infra to testify for `tidb-binlog/pump_client` pkg

### ISSUE THREAD

**Issue by tisonkun** [pingcap/tidb#33463]

**Comment by zanpocc** [comment]
let me try

**Comment by tisonkun** [comment]
@zanpocc thanks for your attempt. I'll assign you and you can assign yourself the next time.

/assign @zanpocc

**Comment by zanpocc** [comment]
> @zanpocc thanks for your attempt. I'll assign you and you can assign yourself the next time.
> 
> /assign @zanpocc

oh thanks
I'm new to tidb and I just submitted a pull request for this issue, maybe you can give me some advice for me :)
