### ISSUE TITLE
high compile cpu when using long in list with varbinary type

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#33494]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run a select statement with long in list with varbinary type

```
select * from t
where
`id` IN (...);

CREATE TABLE `t` (
  `id` varbinary(16) NOT NULL,
...
```
### 2. What did you expect to see? (Required)
fast compile

### 3. What did you see instead (Required)
long compile time
### 4. What is your TiDB version? (Required)

v5.3.1

![AromG9Yakg](https://user-images.githubusercontent.com/2316425/160321239-75a1f3ca-6783-4a98-aaa4-7e4fc1488283.png)

![middle_img_v2_fdbdb5e3-7b78-4540-9ea3-233437aaa48g](https://user-images.githubusercontent.com/2316425/160321338-de3087d2-a4c2-405f-a38d-ca80a22a6792.png)

**Comment by dbsid** [comment]
The new pdqsort might help reduce the cpu on sort in this case.
https://news.ycombinator.com/item?id=31106157

**Comment by zanmato1984** [comment]
This is more like a performance enhancement rather than a bug. Changing some labels.
