### ISSUE TITLE
Memory protection for range calculation of multi-col indexes

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#33512]
## Enhancement
When calculating access ranges for a multi-col index, the optimizer combines access ranges for each column to generate ranges for the index. This operation can generate a large number of ranges, which may use a lot of memory and even cause  OOM, for example, this query `select * from t where a in (1, 2, 3, ...10000) and b in (1, 2, 3, ...10000)` can generate `10000*10000` access ranges for the index `key(a, b)`. We should introduce some memory protection for this operation.

**Comment by morgo** [comment]
I believe this is a duplicate of https://github.com/pingcap/tidb/issues/30755

**Comment by qw4990** [comment]
> I believe this is a duplicate of #30755

Oh you are right. I'll close this issue now.
