### ISSUE TITLE
[Failed to start tidb]   failed to start tidb  in MacOS which use M1 chip

### ISSUE THREAD

**Issue by Cleverdada** [pingcap/tidb#33556]
## Bug Report

Failed to start tidb, use tiup playground. screenshot likes:

![image](https://user-images.githubusercontent.com/11186845/160554782-7decb2f1-b09d-49fa-8672-bdb4e0ad5326.png)

![image](https://user-images.githubusercontent.com/11186845/160554706-d5a6ce42-d9f3-41fc-a441-f0e0b0c7ca23.png)

**Comment by wjhuang2016** [comment]
I guess that you migrate the system from x86 platform. So your zsh is x86 arch, you can check it by `zsh --version`.
If so, reinstall zsh to arm, that will fix it.
