### ISSUE TITLE
br: incremental restore should rebase auto increment id even table exists;

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#33596]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table with _tidb_rowid. 
```
CREATE TABLE `d` (
  `o_id` int(11) NOT NULL,
  `w_id` int(11) NOT NULL,
  PRIMARY KEY (`o_id`,`w_id`)
```
2. do a full backup with this table.
3. insert more than 30000 rows data.
4. do an incremental backup with this table.

5. do a full restore with this table in restore cluster.
6. do an incremental restore with this table.
7. insert some data.

### 2. What did you expect to see? (Required)
insert succeed.
### 3. What did you see instead (Required)
Duplicate entry '30001' for key 'PRIMARY'
### 4. What is your TiDB version? (Required)
master

**Comment by 3pointer** [comment]
The root cause is we didn't handle auto increment id during incremental restore.

**Comment by WangLe1321** [comment]
If NEXT_GLOBAL_ROW_ID of a table changed and no ddl executed in the table between two incremental backups, the problem can happen after incremental restore.
