### ISSUE TITLE
INSERT ODKU EncodeRow error: data and columnID count not match

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#33608]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start tidb with binlog (like `tiup playground nightly --db 1 --drainer 1 --kv 1 --pd 1 --pump 1 --ticdc 1`)
Same test as in TestInsertOnDuplicateKey unit test:
```
create table a (x int primary key);
create table b (x int, y int);
insert into a values (1);
insert into b values (1, 2);
insert into a select x from b on duplicate key update a.x = b.y;
```

### 2. What did you expect to see? (Required)
Succeeded update.
### 3. What did you see instead (Required)
```
tidb> insert into a select x from b on duplicate key update a.x = b.y;
ERROR 1105 (HY000): EncodeRow error: data and columnID count not match 2 vs 1
```
### 4. What is your TiDB version? (Required)

```
Release Version: v6.1.0-alpha
Edition: Community
Git Commit Hash: af6f4ea3c98f52d8c56646b226d720fc50a3314c
Git Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time: 2022-03-26 18:03:22
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by zyguan** [comment]
Introduced by https://github.com/pingcap/tidb/pull/14412 . We append extra datums to the old row to resolve https://github.com/pingcap/tidb/issues/14164 , however it breaks binlog. We need to prevent [binlogRow](https://github.com/pingcap/tidb/blob/3393cf96a3806be673e333c39e645e6b4005491f/table/tables/tables.go#L1162) from including those extra datums.

**Comment by zanmato1984** [comment]
This should be a sig/transaction issue because the write path belongs to transaction team/module. Replacing the label.
