### ISSUE TITLE
PointGet plans can still use plan-cache when it's disabled

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#33628]
## Enhancement
![middle_img_v2_3d58d40b-723c-4b4d-9f89-9d9e9f1c47cg](https://user-images.githubusercontent.com/7499936/161020192-529e5801-d82f-4952-af6f-49fd2636ea5f.png)

From the metric, you can see there are still some point-get queries that can hit cache with plan-cache disabled.

**Comment by tiancaiamao** [comment]
This issue is actually **a critical bug** rather than a "enhancement"
But the feature is not enabled by default in 5.4.X, so we lower the severity.
