### ISSUE TITLE
br: unstable test `br_s3`

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#33644]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`/run-integration-br-test` in any PR.

### 2. What did you expect to see? (Required)

The test passed.

### 3. What did you see instead (Required)

The case `br-s3` doesn't pass, because:

`curl` exit with 0 even it met a 503 HTTP CODE. At this condition, mc would fail soon and so did the test.

### 4. What is your TiDB version? (Required)

Current master, however it doesn't matter.

**Comment by VelocityLight** [comment]
update
