### ISSUE TITLE
upgraded cluster `mysql.user` columns order is different from the new cluster

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#33650]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a v6.0.0  cluster show create table user
2. deploy a v4.0.16 cluster and upgrade to v6.0.0 show create table mysql.user

https://github.com/pingcap/tidb/blob/fa834a08063f857c77a8bba2362815702c9fd3a8/session/bootstrap.go#L88-L94

https://github.com/pingcap/tidb/blob/fa834a08063f857c77a8bba2362815702c9fd3a8/session/bootstrap.go#L1592-L1599

### 2. What did you expect to see? (Required)
the `mysql.user` table columns order is same
### 3. What did you see instead (Required)
the `mysql.user` table columns order is different
### 4. What is your TiDB version? (Required)
v6.0.0

**Comment by Defined2014** [comment]
caused by https://github.com/pingcap/tidb/pull/21856, will affect all version 5.x 😭
