### ISSUE TITLE
Checks for the region label id should be more robust

### ISSUE THREAD

**Issue by CharlesCheung96** [pingcap/tidb#33665]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```bash
➜  curl -X POST http://127.0.0.1:2379/pd/api/v1/config/region-label/rule -H "Content-Type: application/json" --data-binary @- <<DATA
{ "id": "tidb/meta/basic",
   "labels": [{"key": "data-type", "value": "meta"}],
   "rule_type": "key-range",
    "data": [{
         "start_key": "6d00000000000000f8",
         "end_key": "6e00000000000000f8"
   }]
}
DATA

➜  curl -X POST http://127.0.0.1:2379/pd/api/v1/config/region-label/rule -H "Content-Type: application/json" --data-binary @- <<DATA
{ "id": "tidb/meta",
   "labels": [{"key": "data-type", "value": "meta"}],
   "rule_type": "key-range",
    "data": [{
         "start_key": "6d00000000000000f8",
         "end_key": "6e00000000000000f8"
   }]
}
DATA
```

Run the following command from the mysql client:
```SQL
select * from information_schema.attributes;
ERROR 1105 (HY000): invalid label rule ID: tidb/meta
ERROR:
```

### 2. What did you expect to see? (Required)
```
+-----------------+-----------+------------------+------------------------------------------+
| ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
+-----------------+-----------+------------------+------------------------------------------+
| tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
| tidb/meta       | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
+-----------------+-----------+------------------+------------------------------------------+
```
or something like
```
+-----------------+-----------+------------------+------------------------------------------+
| ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
+-----------------+-----------+------------------+------------------------------------------+
| tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
+-----------------+-----------+------------------+------------------------------------------+
WARNING: invalid label rule ID: tidb/meta
```

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): invalid label rule ID: tidb/meta
ERROR:
```
### 4. What is your TiDB version? (Required)

```bash
Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:41:03
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
```

**Comment by nolouch** [comment]
cc @rleungx

**Comment by rleungx** [comment]
It is expected behavior, we recommend using TiDB to change attributes and if you want to use PD API in a TiDB cluster, the ID should meet the TiDB encoding rule.

**Comment by nolouch** [comment]
TiDB needs `schema/{DB}/{Table}/{PartitionID}` to be rule ID. 
https://github.com/pingcap/tidb/blob/ec637878d4ca6650a5a1ed3c5e94b11af537a941/executor/inspection_result.go#L1175-L1193

**Comment by CharlesCheung96** [comment]
> It is expected behavior, we recommend using TiDB to change attributes and if you want to use PD API in a TiDB cluster, the ID should meet the TiDB encoding rule.

Thanks for the explanation, I understand this behavior, but the question is whether it makes more sense for tidb to display the legal row before reporting an error when there is an illegal id. For the above example: 
```
+-----------------+-----------+------------------+------------------------------------------+
| ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
+-----------------+-----------+------------------+------------------------------------------+
| tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
+-----------------+-----------+------------------+------------------------------------------+
ERROR 1105 (HY000): invalid label rule ID: tidb/meta
```

**Comment by rleungx** [comment]
Because the attributes are only supported in the table level now, the above example breaks this assumption.

**Comment by nolouch** [comment]
I think 

> > It is expected behavior, we recommend using TiDB to change attributes and if you want to use PD API in a TiDB cluster, the ID should meet the TiDB encoding rule.
> 
> Thanks for the explanation, I understand this behavior, but the question is whether it makes more sense for tidb to display the legal row before reporting an error when there is an illegal id. For the above example:
> 
> ```
> +-----------------+-----------+------------------+------------------------------------------+
> | ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
> +-----------------+-----------+------------------+------------------------------------------+
> | tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
> +-----------------+-----------+------------------+------------------------------------------+
> ERROR 1105 (HY000): invalid label rule ID: tidb/meta
> ```

I think warning is ok.

**Comment by CharlesCheung96** [comment]
> I think
> 
> > > It is expected behavior, we recommend using TiDB to change attributes and if you want to use PD API in a TiDB cluster, the ID should meet the TiDB encoding rule.
> > 
> > 
> > Thanks for the explanation, I understand this behavior, but the question is whether it makes more sense for tidb to display the legal row before reporting an error when there is an illegal id. For the above example:
> > ```
> > +-----------------+-----------+------------------+------------------------------------------+
> > | ID              | TYPE      | ATTRIBUTES       | RANGES                                   |
> > +-----------------+-----------+------------------+------------------------------------------+
> > | tidb/meta/basic | key-range | "data-type=meta" | [6d00000000000000f8, 6e00000000000000f8] |
> > +-----------------+-----------+------------------+------------------------------------------+
> > ERROR 1105 (HY000): invalid label rule ID: tidb/meta
> > ```
> 
> I think warning is ok.

In the latest version, tidb reports decode errors due to changes in this [pr](https://github.com/pingcap/tidb/pull/32559).
```SQL
MySQL [INFORMATION_SCHEMA]> select * from information_schema.attributes;
ERROR 1105 (HY000): decode tableID from key m in rule schema/ticdc/metatest failed
```

**Comment by AndreMouche** [comment]
I'd like to fix this issue. we will do the following thing on TiDB:
1. TiDB only shows the table labels which are created by `tidb`(which means with legal `TIDB` ID)

For table labels which are not created by `tidb`, if the client want to show them in tidb, please use the same encode algorithm like `tidb`
