### ISSUE TITLE
BR incremental restore failed when tiflash server count is less than tiflash replica count

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#33661]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
i. increment backup on a cluster which has three tiflash replicas.
ii. incremental restore to another cluster which has only one tiflash server.

3. What did you expect to see?
incremental restore succeed.

4. What did you see instead?
["br failed"] [error="the tiflash replica count: 3 should be less than the total tiflash server count: 1"]

5. What version of BR and TiDB/TiKV/PD are you using?
v5.4.0

5. Operation logs
![origin_img_v2_ff0b51a5-5335-483e-9570-c3c4b862f77g](https://user-images.githubusercontent.com/45614653/161196987-28807f8f-cc78-4627-9c3e-3e7a0ae31fa1.png)

6. Configuration of the cluster and the task
   - `tidb-lightning.toml` for TiDB-Lightning if possible
   - `tikv-importer.toml` for TiKV-Importer if possible
   - `topology.yml` if deployed by TiUP

7. Screenshot/exported-PDF of Grafana dashboard or metrics' graph in Prometheus if possible

**Comment by WangLe1321** [comment]
We have fixed this bug in https://github.com/pingcap/tidb/pull/33384 . Now, DDL jobs about TiFlash are skipped.
