### ISSUE TITLE
question for tidb statistic ？

### ISSUE THREAD

**Issue by lddlww** [pingcap/tidb#33735]
my situation is：
there are some large tables in ```tib v5.3.0```, and these tables modified in low frequency most of time，only make a lot of changes for these tables at certain time，but these modify can not trigger tidb auto analyze and result in some ```select sql``` query long time，because ```tidb cbo``` choose incorrect index for statistic error

i find ```tidb_auto_analyze_ratio=0.5``` is global affect for all tables，how can i do to set it for some tables？

**Comment by ljluestc** [comment]
```

In TiDB, the `tidb_auto_analyze_ratio` parameter controls when automatic statistics update (analyze) is triggered. This setting applies globally and affects all tables in the system. As of my last update, TiDB does not support setting `tidb_auto_analyze_ratio` or other auto-analyze configurations at the table level directly through configuration parameters.

However, you can work around this limitation and achieve more fine-grained control over statistics updates for specific tables by using a combination of disabling the global auto-analyze feature and manually triggering analyzes on specific tables based on custom criteria or schedules. Here's how you can approach this:

### 1. Disable Global Auto-Analyze

First, disable the global auto-analyze feature to prevent TiDB from automatically analyzing tables. You can do this by setting the `tidb_auto_analyze_ratio` to a very high value (effectively disabling it) or explicitly setting `tidb_auto_analyze_end_time` before the current time to ensure it won't trigger:

```sql
SET GLOBAL tidb_auto_analyze_ratio = 100; -- Or any value that effectively disables auto analyze
-- OR
SET GLOBAL tidb_auto_analyze_end_time = '00:00 -0000'; -- Set to a time in the past
```

### 2. Manually Trigger Analyze for Specific Tables

Next, you can manually trigger `ANALYZE TABLE` commands for specific tables based on your own criteria or schedules. This approach allows you to control exactly when and which tables are analyzed, thus ensuring that their statistics are up-to-date according to your operational patterns.

You can schedule these `ANALYZE TABLE` operations using external tools or scripts. For example, you could use a cron job on Linux to run a script that connects to your TiDB database and executes the necessary `ANALYZE TABLE` statements at specific times.

Here is a simple example of a bash script that you could schedule with cron to analyze specific tables:

```bash
#!/bin/bash

# Set your database connection details
DB_HOST="127.0.0.1"
DB_PORT="4000"
DB_USER="root"
DB_PASSWORD="your_password"
DB_NAME="your_database"

# List of tables to analyze
TABLES=("table1" "table2")

# Loop through the tables and analyze each one
for TABLE in "${TABLES[@]}"
do
    echo "Analyzing table: $TABLE"
    mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USER" -p"$DB_PASSWORD" "$DB_NAME" -e "ANALYZE TABLE $TABLE;"
done
```

### 3. Schedule the Script Using Cron (Linux Example)

Edit your crontab file to add a new entry for the script. For example, to run the script every day at 3 AM:

```cron
0 3 * * * /path/to/your/script.sh
```

This approach requires manual setup and external scheduling, but it gives you the flexibility to update statistics for specific tables according to their unique usage patterns and operational needs.

Remember, direct support for table-level auto-analyze settings might be introduced in future versions of TiDB. Always refer to the latest TiDB documentation or community forums for new features and best practices.
```

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it. You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese) or https://ask.pingcap.com/(English)
