### ISSUE TITLE
expression test fails for ppc64le

### ISSUE THREAD

**Issue by YugandhaD** [pingcap/tidb#3376]
I am trying to build and test tidb master branch on ppc64le.
I found that test “github.com/pingcap/tidb/expression” fails on it.
If we run this  “github.com/pingcap/tidb/expression” test individually, using "go test" command inside the expression folder, I get following error.

```
FAIL: builtin_math_test.go:80: testEvaluatorSuite.TestExp

builtin_math_test.go:104:
    c.Assert(v, testutil.DatumEquals, types.NewDatum(t.ret))
... obtained types.Datum = types.Datum{k:0x4, collation:0x0, decimal:0x0, length:0x0, i:4613303445314885482, b:[]uint8(nil), x:interface {}(nil)}
... expected types.Datum = types.Datum{k:0x4, collation:0x0, decimal:0x0, length:0x0, i:4613303445314885481, b:[]uint8(nil), x:interface {}(nil)}

```
I could find out the issue and I found that it was minor changes in some values. I could fix the issue, and now the test is passing for ppc64le.
Please let me know if you are willing to have this patch for ppc64le.

**Comment by ngaut** [comment]
Please feel free to send a pull request.

**Comment by coocood** [comment]
@YugandhaD 
Any update?

**Comment by shenli** [comment]
This is fixed. Thanks! @YugandhaD
