### ISSUE TITLE
The internal session has no SessionManager

### ISSUE THREAD

**Issue by TonsnakeLin** [pingcap/tidb#33763]
## Bug Report
The client session has the SessionManager, but the internal session has no SessionManager. 

### 4. What is your TiDB version? (Required)
master/6.0/ before 6.0

**Comment by xhebox** [comment]
Could you please explain more about your problem? I don't get it, @TonsnakeLin .

**Comment by TonsnakeLin** [comment]
For client session, we call `cc.ctx.SetSessionManager(cc.server)` to store SessionManager, but for internal session, we don't store SessionManager so that we can't use SessionManager to do something.

**Comment by bb7133** [comment]
@TonsnakeLin I think this is expected. It doesn't lead to any wrong behavior to the user. I'm going to close this issue and feel free to have more comments here.
