### ISSUE TITLE
diagnose: try to differentiate between internal and external requests

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#33963]
## Enhancement

Currently the tidb-server could trigger several different types of internal requests, they could be triggered by some background tasks such as `auto analyze`, `statistics feedback`, `ddl backfill`, `gc resolve lock`,  `gc unsafe destroy range`, etc. Also, the entries are different some of them may use `ExecRestrictedSQL` and some may use raw transaction interfaces. These requests would be turned into kv requests just like the user kv requests, but there's no way to differentiate them conveniently. 

As these internal requests could use resources and affect the performance when the resources are limited on the cloud, it's difficult to do the performance tuning if the current bottleneck is introduced by some ongoing background tasks. To make the performance diagnosis easier, we could add separate tags for these internal kv requests and try to display how many resources are used by them so that it could be much easier to tell if the internal tasks affect the cluster performance a lot.

The detailed work plan is:
- [ ] Add a flag for the internal request in the RPC context of kvproto.
- [ ] Use this flag in requests generated by all the internal SQL execution or raw transaction command execution.
- [ ] Add or adjust corresponding monitor metrics in both tidb and tikv panels. For the tikv panel, we could distinguish the resources(the thread worker, read/write flow) used by internal requests and their impact on performance.

Note this is just to enhance the path from tidb to tikv, there're still some background tasks like `peer move`, `data compaction` in the tikv side, these internal tasks could be discussed in another [document](https://github.com/tikv/tikv/issues/12362).

**Comment by BornChanger** [comment]
Please be kindly reminded, there is a related pr.  Make sure we are on the same page and no dup work.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/97348524/176346949-6f009a1f-51a2-4b11-83cc-646169838fab.png">

**Comment by sticnarf** [comment]
> Please be kindly reminded, there is a related pr. Make sure we are on the same page and no dup work. <img alt="image" width="868" src="https://user-images.githubusercontent.com/97348524/176346949-6f009a1f-51a2-4b11-83cc-646169838fab.png">

Thanks for the reminder.

This issue is much more systematic work, trying to labeling all requests with their sources. Maybe we will reimplement #34861 with more unified mechanisms.

**Comment by you06** [comment]
> Maybe we will reimplement #34861 with more unified mechanisms.

#34861 pushed `InRestrictedSQL` flag into DAG requests only, we can move such flag into the KV context and separate [`request_source`](https://github.com/pingcap/kvproto/blob/ebdfc424a7e52ba2770c3afefd4e0648eac16b2f/proto/kvrpcpb.proto#L734) into `request_source` and `request_scope`, but it makes other TiKV user confused because they don't have the knowledge about "internal" requests.
