### ISSUE TITLE
The instance column in the information_schema.cluster_slow_query is empty when the system is cluster.

### ISSUE THREAD

**Issue by Yeaohai** [pingcap/tidb#33969]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

select instance, count(*) from information_schema.cluster_slow_query where time >= '2022-04-12 00:00:00' and  time < now() group by instance;

### 2. What did you expect to see? (Required)
In the Official website ,it is not empty
https://docs.pingcap.com/zh/tidb/v5.1/identify-slow-queries
![image](https://user-images.githubusercontent.com/99950214/163360977-444b4f63-b2ca-4b6b-9f3a-7c9b910fc3b4.png)

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/99950214/163361224-61b2cfce-9cef-4f53-ab13-9587323daea3.png)

### 4. What is your TiDB version? (Required)
Cluster version:    v5.4.0
![image](https://user-images.githubusercontent.com/99950214/163361615-dcf76b02-28fa-407f-a6ce-08a449550959.png)

**Comment by seiya-annie** [comment]
https://github.com/pingcap/tidb/issues/33974

**Comment by breeswish** [comment]
Fixed by https://github.com/pingcap/tidb/pull/26219
