### ISSUE TITLE
info key was not removed in pd when tidb exit

### ISSUE THREAD

**Issue by nexustar** [pingcap/tidb#34009]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

scale-in tidb

### 2. What did you expect to see? (Required)

the scale-in node not exist on tidb dashbosrd

related https://github.com/pingcap/tiup/issues/1752

### 3. What did you see instead (Required)

still exist

**Comment by breeswish** [comment]
As this thread is now a discussion about the behavior, I'm moving this to type/question.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it.
