### ISSUE TITLE
Telemetry data for TxnUsage may be too big when there are many tables 

### ISSUE THREAD

**Issue by qqqdan** [pingcap/tidb#34035]
## Enhancement
In the following telemetry logic, it will record the ClusterIndexUsage data for each table with hashed table names .  When the DB has large number of tables, the telemetry result Json will be larger than 256KB, which is too big to process and we will lose all the telemetry data from this cluster .
https://github.com/pingcap/tidb/blob/4844c833a9e5f7f8eab66f16ca8e0f8189ca46dc/telemetry/data_feature_usage.go#L125

Suggest to record the Statistics instead of the hashed table name .

**Comment by lucklove** [comment]
Suggestion: record summary statistic instead of every table.

**Comment by bb7133** [comment]
@qqqdan @lucklove 

We plan to change the struct `ClusterIndexUsage` to:

```
type ClusterIndexUsage struct {
        // The number of user's tables with clustered index enabled.
	NumClusteredTables uint64 `json:"numClusteredTables"`
        // The number of user's tables.
	NumTotalTables    uint64 `json:"numTotalTables"`
}
```
So the telemetry information will be changed from:
```
"clusterIndex":{
    "061499":{"clusterPKType":"NA","isClustered":false},
    "0af47d":{"clusterPKType":"NA","isClustered":false},
    "0d1c14":{"clusterPKType":"NA","isClustered":true},
    ...
}
...
```
To the JSON message like:
```
"clusterIndex":{
    "numClusteredTables": 1,
    "numTotalTables": 3
}
```
Also, please notice that the system tables from the following schema will not be counted because they're not created by the users, which is the same with previous telemetry message of clustered index:
* `INFORMATION_SCHEMA`
* `METRICS_SCHEMA`
* `PERFORMANCE_SCHEMA`
* `mysql`

**Comment by bb7133** [comment]
Let's do this:

```
"newClusterIndex":{
    "numClusteredTables": 1,
    "numTotalTables": 3
}
```
So that we could distinguish the old message and new one.

**Comment by littlelittlehorse** [comment]
> Let's do this:
> 
> ```
> "newClusterIndex":{
>     "numClusteredTables": 1,
>     "numTotalTables": 3
> }
> ```
> 
> So that we could distinguish the old message and new one.

Are both newClusterIndex and clusterIndex present？

**Comment by bb7133** [comment]
> Are both newClusterIndex and clusterIndex present at the same time？

Good question! Sorry that I forgot the update for current `ClusterIndex`, it should be kept but empty after your change,  something like:

```
"clusterIndex": {}
```

**Comment by littlelittlehorse** [comment]
> Good question! Sorry that I forgot the update for current `ClusterIndex`, it should be kept but empty after your change, something like:
> 
> ```
> "clusterIndex": {}
> ```

I thought about it, but I don't think it can exist at the same time, because the returned value is only return one of the two.

**Comment by lucklove** [comment]
> > Good question! Sorry that I forgot the update for current `ClusterIndex`, it should be kept but empty after your change, something like:
> > ```
> > "clusterIndex": {}
> > ```
> 
> I thought about it, but I don't think it can exist at the same time, because the returned value is only one of the two.

Then just use a new name other than the old one ("clusterIndex")
