### ISSUE TITLE
How to transfer data between tidb servers? 

### ISSUE THREAD

**Issue by ghostboyzone** [pingcap/tidb#3412]

**Comment by shenli** [comment]
@ghostboyzone Could you be more explicit?  Why need to transfer data between tidb-servers?

**Comment by ghostboyzone** [comment]
For example, I have one tidb cluster A, and I got anthor  tidb cluster B； I want to synchronize data from A to B without breaking the cluster inner relationship

**Comment by shenli** [comment]
We have a binlog module for this purpose. TiDB will output binlog and we can use this to synchronize data to another TiDB cluster or MySQL.

**Comment by ghostboyzone** [comment]
@shenli Already have binlog module or in development ?  Can you give a guide for open binlog in tidb

**Comment by morgo** [comment]
Thank you for the feature suggestion.  We recently announced Data Migration (DM) for this purpose.  Please see https://www.pingcap.com/docs/tools/data-migration-overview/

I am going to close this issue for now, but please feel free to re-open if you have followup questions.  Thanks!
