### ISSUE TITLE
unmarshall grpc packet cause OOM

### ISSUE THREAD

**Issue by bestwoody** [pingcap/tidb#34143]
## Enhancement
[https://internal.pingcap.net/jira/browse/ONCALL-4801](https://internal.pingcap.net/jira/browse/ONCALL-4801)

unmarsheal grpc packet consume too much memory，cause OOM。
for example：
Once enabled TiFlash, execution of one query with left outer semi join from customer is causing TiDB OOM and restart. the main memory hug is _unmarsheal grpc packet_

**Comment by XuHuaiyu** [comment]
After https://github.com/pingcap/tidb/pull/39151, the memory consumption of unmarshal the grpc packet in MPPIterator would not be a problem, close this issue.
