### ISSUE TITLE
br: adapt the new dynamic region feature

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#34167]
## Enhancement

[Dynamic Regions](https://github.com/tikv/rfcs/pull/82) ([Tracking Issue](https://github.com/tikv/tikv/issues/11515)) brings the ability of supporting region size up to GiB for TiKV.

For huge regions, BR did split the backup files into many 96MiB small files for preventing OOM errors, hence(hopefully) it is no need to do any adaptions for making backup work. 

However, if the dynamic region is enabled, when restoring, because we split region with the **end key of each file**, we may make many 96MiB "small" regions and eventually PD has to merge them, which may affect the cluster in a long period. We should do some adaptions.

The easiest way is to reuse the feature of "merging small files" has been introduced from v4.x: when this feature is enabled, BR would merge small files to a specified size, by using the two parameters:

- `--merge-region-size-bytes`, corresponding to `coprocessor.region-split-size`.
- `--merge-region-key-count`, corresponding to `coprocessor.region-split-key`.

The default value of those parameters are the same as the default value of their corresponding config in the TiKV coprocessor. But when dynamic region enabled, the default value may not be helpful, so we need:

- [x] #34370

Also, there is a old bug making BR panic during restoring, which has already be fixed:

- [x] https://github.com/pingcap/tidb/pull/33797

**Comment by BusyJay** [comment]
Can PD provide the configuration? @bufferflies

**Comment by 3pointer** [comment]
> > 
> 
> yes, the `/api/v1/pd/config` api will return the configuration.

should it be `/pd/api/v1/config`?

**Comment by 3pointer** [comment]
> > > 
> > 
> > 
> > yes, the `/api/v1/pd/config` api will return the configuration.
> 
> should it be `/pd/api/v1/config`?

And I didn't find the config of `region-split-key` and `region-split-size`, did I miss something? @bufferflies

**Comment by bufferflies** [comment]
the config of `region-split-key` and `region-split-size` belongs tikv.

**Comment by YuJuncen** [comment]
This should be done.
