### ISSUE TITLE
make program startup parameters consisitent

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#3417]
pd-server tikv-server and tidb-server use parameters differently and somewhat confusing for new users.

this is extracted from https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md

```bash
./bin/pd-server --data-dir=pd
./bin/tikv-server --pd="127.0.0.1:2379" --store=tikv
./bin/tidb-server --store=tikv --path="127.0.0.1:2379" 
```
pd-server will write data in directory pd, and tikv-server will write data in tikv directory
while for tidb-server  `--store=tikv`  means it uses tikv as storage engine.

why not change the `--store` param of tikv-server to `--data-dir`?
```bash
./bin/tikv-server --pd="127.0.0.1:2379" --data-dir=tikv
```
This looks more consisitent to me.

**Comment by siddontang** [comment]
Hi @Darren 

We have already supported `--data-dir` and this is the recommended flag later too, we will update the document.

**Comment by siddontang** [comment]
@andelf 

Please upgrade the deployment document :-).
