### ISSUE TITLE
禁用top下推后执行计划cop task数量和trace数量不一致

### ISSUE THREAD

**Issue by 311ybb** [pingcap/tidb#34198]
version: tidb 5.3.1
表sbtest7有2亿条记录，480+ region,  通过mysql.opt_rule_blacklist 禁用了topn_push_down之后Limit未下推到tikv
未禁用topn_push_down的执行计划和trace:
![image](https://user-images.githubusercontent.com/88499339/165008499-da3b6ca4-9442-4463-9fd2-cd7811f9ab60.png)
禁用后执行计划：
![image](https://user-images.githubusercontent.com/88499339/165007893-f83e959d-3cde-4cfa-ac90-e84c694c405b.png)
问题：
1、 禁用top下推后，Table_Reader显示actRows=32，这里tablereader 算子返回32行是依据什么算来的？
2、禁用topn下推后执行计划显示cop_task为1，而实际trace为15个，通过调整tidb_distsql_scan_concurrency=1 ，执行计划中实际的actRows与tidb_distsql_scan_concurrency默认值15时相同，也就是说禁用下topn 下推后 ，SQL执行仅扫描了一个region的所有数据就足够了，为什么执行计划显示1个cop task而trace里却有15个？另外是14个cop task是否真正的执行了？
![image](https://user-images.githubusercontent.com/88499339/165009009-82e09369-5772-4aae-9be6-281fad623ab2.png)

**Comment by jansu-dev** [comment]
已在 AskTUG 的该贴中回复 --> https://asktug.com/t/topic/664580
