### ISSUE TITLE
the ARM environment plan-cache cache is occasionally invalid

### ISSUE THREAD

**Issue by bob34007** [pingcap/tidb#34294]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Update data continuously for 15 minutes using Update Prepare via Jemter. 
2. Then pressure the INSERT statement with Jmeter prepare. 

### 2. What did you expect to see? (Required)
1. All insert prepare statements use plan-cache

### 3. What did you see instead (Required)
1. The insert prepare statement cannot use plan-cache
### 4. What is your TiDB version? (Required)

v5.4.0  
OS : Linux localhost.localdomain 4.14.0-115.el7a.0.1.aarch64 #1 SMP Sun Nov 25 20:54:21 UTC 2018 aarch64 aarch64 aarch64 GNU/Linux

**Comment by Yisaer** [comment]
same as https://github.com/pingcap/tidb/issues/34295
