### ISSUE TITLE
Continued growth of the empty regions

### ISSUE THREAD

**Issue by shhdgit** [pingcap/tidb#34318]
## General Question

There are many empty regions with continued growth when running TPC-H Q15 which includes `CREATE VIEW`, `DROP VIEW`. It can be reproduced in tidb v6.0.0, but not in tidb v5.4.0. Is it a bug?

![middle_img_v2_8ec8ba42-78b1-41e4-babe-5e606daed35g](https://user-images.githubusercontent.com/11549583/165706967-dee9b12e-f384-41a2-8db0-ba276085de1f.jpg)

### Minimal reproduce step

```
tiup playground v6.0.0 --tiflash 0
bin/go-tpc tpch prepare --threads 8
bin/go-tpc tpch run --queries q15
```

### tidb version
v6.0.0

**Comment by jebter** [comment]
Please modify split-table = false and test again.https://docs.pingcap.com/tidb/dev/tidb-configuration-file#split-table 
I will close it，if there are any updates, you can reopen it. You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese) or https://ask.pingcap.com/(English)
