### ISSUE TITLE
TestSubquery Failed

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#3441]
FAIL: join_test.go:348: testSuite.TestSubquery

join_test.go:460:
    result.Check(testkit.Rows(“1 0”, “2 1"))
/home/ubuntu/.go_project/src/github.com/pingcap/tidb/util/testkit/testkit.go:47:
    res.c.Assert(got, check.Equals, need, res.comment)
... obtained string = “[[1 0] [2 0]]”
... expected string = “[[1 0] [2 1]]”
... sql:select *, 0 < any (select count(id) from s where id = t.id) from t, []

**Comment by zimulala** [comment]
PTAL @hanfei1991

**Comment by hanfei1991** [comment]
Fixed
