### ISSUE TITLE
The function of `storeIsBootstrapped` is not very accurate

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#3449]
https://github.com/pingcap/tidb/pull/2800/files#diff-383483267e198cd997e4bd7c70028d12R166
This line can't make sure the Bootstrapped function is finished，so the domain may not be closed yet.
GCWorker may use Bootstrapped Domain to create a session, the domain will close after finishing the bootstrap operation.

**Comment by shenli** [comment]
Is this a bug?

**Comment by zimulala** [comment]
@shenli 
PTAL @disksing

**Comment by disksing** [comment]
I think it is a bug indeed.
