### ISSUE TITLE
TopSQL & statement summary use a lot of memory

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#34525]
## General Question

We test tidb with [sqllogic](https://github.com/pingcap/test-plan/blob/main/transaction/sqllogic.yaml) daily and it [fails recently](https://tcms.pingcap.net/dashboard/executions/plan?query=sqllogic&page=1&pageSize=20). The case fails because the tidb gets OOM killed and it seems that the memory is maily used by topsql & statement summary.

![2022-05-10_141922](https://user-images.githubusercontent.com/6850317/167561184-a7efdc05-a84b-454c-a39e-4026a7a0b4cd.png)

[heap-dump.tar.gz](https://github.com/pingcap/tidb/files/8658738/heap-dump.tar.gz)

**Comment by mornyx** [comment]
Hi @zyguan, could you please provide the version & commit id of this TiDB instance? Also includes the num of CPU cores and memory size of the machine.

**Comment by zyguan** [comment]
> Hi @zyguan, could you please provide the version & commit id of this TiDB instance? Also includes the num of CPU cores and memory size of the machine.

The latest master is used and resource quotas described [here](https://github.com/pingcap/test-infra/blob/main/sdk/resource/impl/k8s/assets/tidb-cluster.yaml).

**Comment by mornyx** [comment]
> The latest master is used and resource quotas described [here](https://github.com/pingcap/test-infra/blob/main/sdk/resource/impl/k8s/assets/tidb-cluster.yaml).

Did you turn on the TopSQL during the test?

**Comment by zyguan** [comment]
> > The latest master is used and resource quotas described [here](https://github.com/pingcap/test-infra/blob/main/sdk/resource/impl/k8s/assets/tidb-cluster.yaml).
> 
> Did you turn on the TopSQL during the test?

No special settings for enabling TopSQL, it shall be disabled by default.

**Comment by mornyx** [comment]
![image](https://user-images.githubusercontent.com/40526986/167814449-cee47558-f489-472c-bab3-6f8b3b135620.png)

https://github.com/pingcap/tidb/pull/34558 has been merged, so the green part should have been resolved. Whether the blue part will cause the leak is still unclear, so we need to continue to observe the next daily test report. cc @zyguan

**Comment by mornyx** [comment]
> Whether the blue part will cause the leak is still unclear, so we need to continue to observe the next daily test report.

Does the memory leak still exist in the latest test? I see that the `sqllogic` tests on TCMS all seem to succeed.

**Comment by zyguan** [comment]
> > Whether the blue part will cause the leak is still unclear, so we need to continue to observe the next daily test report.
> 
> Does the memory leak still exist in the latest test? I see that the `sqllogic` tests on TCMS all seem to succeed.

No, no OOM recently. It’s ok now.
