### ISSUE TITLE
sysvar: GPL?

### ISSUE THREAD

**Issue by AkihiroSuda** [pingcap/tidb#3458]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

`SELECT VARIABLE_VALUE FROM mysql.GLOBAL_VARIABLES WHERE VARIABLE_NAME = 'license';`
https://github.com/pingcap/tidb/blob/7b6e4475b3aef82fe4391481f6319c36cf4c0074/sessionctx/variable/sysvar.go#L460

2. What did you expect to see?

Apache License 2.0

3. What did you see instead?

GPL

**Comment by shenli** [comment]
@AkihiroSuda Thanks for your feedback!
It is a mistake. We should fix it. Could you send us a PR to fix it.

**Comment by AkihiroSuda** [comment]
sure
https://github.com/pingcap/tidb/pull/3460
