### ISSUE TITLE
bindings with `ignore_plan_cache_hint` cannot work

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#34596]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
-- enable the plan-cache --
create table t (a int);
create binding for select * from t using select /*+ ignore_plan_cache() */ * from t;
prepare stmt from 'select * from t';
execute stmt;
execute stmt;
select @@last_plan_from_cache;
```

### 2. What did you expect to see? (Required)
The second execute-stmt cannot hit the cache since we create a binding with ignore_plan_cache() for it.

### 3. What did you see instead (Required)
It can hit the cache.

### 4. What is your TiDB version? (Required)

Master

**Comment by glkappe** [comment]
do we have any plans to fix this

**Comment by fzzf678** [comment]
> do we have any plans to fix this

I'm working on it
