### ISSUE TITLE
pd-ctl store & pd-ctl region store return diff result

### ISSUE THREAD

**Issue by 311ybb** [pingcap/tidb#34597]
下线tikv后长时间处于pending offline状态，使用Pd-ctl store检查下线的store中 leader_count/region_count都是0 。使用pd-ctl region stoere单独查询某个store的region后却显示存在region，这些region都是选不出leader。相关帖子见下面
https://asktug.com/t/topic/664718
https://asktug.com/t/topic/603771/10
https://asktug.com/t/topic/664718/10

**Comment by seiya-annie** [comment]
for pd issue, submit it in https://github.com/tikv/pd/issues may get faster response. @311ybb

**Comment by jebter** [comment]
duplicate:https://github.com/tikv/pd/issues/4953
