### ISSUE TITLE
`GRANT` is not case insensitive in GRANT SELECT ON tablename

### ISSUE THREAD

**Issue by espresso98** [pingcap/tidb#34610]
### 1. Minimal reproduce step 
```sql
DROP DATABASE IF EXISTS d1; 

CREATE DATABASE d1;
USE d1;
CREATE USER user_1@localhost;
CREATE TABLE T1(f1 INT);
CREATE TABLE t1(f1 INT);
GRANT SELECT ON T1 to user_1@localhost;
GRANT SELECT ON t1 to user_1@localhost;

DROP DATABASE d1;
DROP USER user_1@localhost;
```
### 2. What did you expect to see? 
```sql
mysql> CREATE TABLE T1(f1 INT);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t1(f1 INT);
ERROR 1050 (42S01): Table 't1' already exists

mysql> GRANT SELECT ON T1 to user_1@localhost;
Query OK, 0 rows affected (0.00 sec)

mysql> GRANT SELECT ON t1 to user_1@localhost;
Query OK, 0 rows affected (0.00 sec)
```

### 3. What did you see instead
```sql
tidb> CREATE TABLE T1(f1 INT);
Query OK, 0 rows affected (0.00 sec)

tidb> CREATE TABLE t1(f1 INT);
ERROR 1050 (42S01): Table 'd1.t1' already exists

tidb> GRANT SELECT ON T1 to user_1@localhost;
Query OK, 0 rows affected (0.01 sec)

tidb> GRANT SELECT ON t1 to user_1@localhost;  -- not case insesitive, Table 'd1.t1' already exists
ERROR 1146 (42S02): Table 'd1.t1' doesn't exist     
```

### 4. What is your TiDB version? 
```
tidb_version(): Release Version: v6.1.0-alpha-391-g901f042d5
Edition: Community
Git Commit Hash: 901f042d5d3cca6c52e8d4921e109b2b6f14f594
Git Branch: master
UTC Build Time: 2022-05-12 03:19:29
GoVersion: go1.18.1
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by likzn** [comment]
I find the real error happened in `CREATE TABLE t1(f1 INT);`.Because of the `lower_case_table_names`.
https://docs.pingcap.com/zh/tidb/dev/mysql-compatibility
```
Default value of lower_case_table_names:
The default value in TiDB is 2 and currently TiDB only supports 2.
The default value in MySQL:
On Linux: 0
On Windows: 1
On macOS: 2
```

**Comment by seiya-annie** [comment]
> I find the real error happened in `CREATE TABLE t1(f1 INT);`.Because of the `lower_case_table_names`. https://docs.pingcap.com/zh/tidb/dev/mysql-compatibility
> 
> ```
> Default value of lower_case_table_names:
> The default value in TiDB is 2 and currently TiDB only supports 2.
> The default value in MySQL:
> On Linux: 0
> On Windows: 1
> On macOS: 2
> ```

so, is it not a bug?

**Comment by likzn** [comment]
> > I find the real error happened in `CREATE TABLE t1(f1 INT);`.Because of the `lower_case_table_names`. https://docs.pingcap.com/zh/tidb/dev/mysql-compatibility
> > ```
> > Default value of lower_case_table_names:
> > The default value in TiDB is 2 and currently TiDB only supports 2.
> > The default value in MySQL:
> > On Linux: 0
> > On Windows: 1
> > On macOS: 2
> > ```
> 
> so, is it not a bug?

Miss me, i ignore something.I think it is a bug.

**Comment by zimulala** [comment]
PTAL @tiancaiamao
