### ISSUE TITLE
Log backup task error status should be defined

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#34653]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Log backup task should enter error status when there is something wrong with the task, e.g. log backup in abnormal status for 24 hours, log backup checkpoint is smaller than gc safepoint, etc.
We should define how to notify user, what user can do in these scenario, and give user clear guidance/error message to handle these cases.

### 3. What did you see instead (Required)
e.g. when try to pause a task whose checkpoint_ts is smaller than gc safepoint:
![6ulCOXJuUh](https://user-images.githubusercontent.com/7403864/168418260-bebb0f42-acf2-4ffc-b322-af3e5e0b5b28.jpg)

### 4. What is your TiDB version? (Required)
Git Commit Hash: bbfbe137eba05f828a9fb40708a6f6805a3453f0
Git Branch: heads/refs/tags/v6.1.0-alpha
Go Version: go1.18
UTC Build Time: 2022-05-13 14:52:24
Race Enabled: false

**Comment by windtalker** [comment]
I believe it is an enhancemant instead of bug, so remove `type/bug` label.

**Comment by joccau** [comment]
Update it on doc of user.
