### ISSUE TITLE
hot tidb system upgrade

### ISSUE THREAD

**Issue by yuekui2** [pingcap/tidb#3469]
This is a general question. Assume we start to use tidb system now, in the future, when we need to upgrade the tidb to a new version, what is the recommended procedure? Could we do the upgrade without stopping the upstream services?

**Comment by shenli** [comment]
@yuekui2 
It depends on the versions of old/new instances. We will release RC3 in the end of this week. After this release, you could always do rolling upgrade without stop the whole cluster.
