### ISSUE TITLE
Optimize error message when backup file is broken in PiTR

### ISSUE THREAD

**Issue by WangLe1321** [pingcap/tidb#34743]
## Enhancement

When backupmeta file is broken, error message is `Error: proto: wrong wireType = 2 for field ClusterId`

When table data file is broken, error message is `Error: failed to restore kv files: execute over region id:2 start_key:"t\200\000\000\000\000\000\000\377\226\000\000\000\000\000\000\000\370" region_epoch:<conf_ver:5 version:119 > peers:<id:3 store_id:1 > peers:<id:87 store_id:4 > peers:<id:113 store_id:5 >  failed: Cannot read http://172.16.102.96:9000/stream/2022-05-17/3/v1/t00000150/20220517-433264245943042053-771f0333-0a43-47dd-99ef-49abe0b63c16.log into /tidb-data/tikv-20161/import/.temp/v1/t00000150/20220517-433264245943042053-771f0333-0a43-47dd-99ef-49abe0b63c16.log: sha256 not match, expect: [113, 22, 245, 65, 148, 66, 59, 204, 73, 97, 19, 52, 64, 158, 14, 153, 228, 94, 108, 25, 1, 239, 150, 135, 198, 217, 9, 130, 247, 55, 184, 125], calculate: [198, 130, 156, 31, 101, 127, 10, 159, 14, 25, 230, 125, 197, 71, 220, 87, 74, 138, 10, 213, 235, 6, 61, 85, 222, 96, 171, 125, 166, 190, 37, 129]; execute over region id:2 start_key:"t\200\000\000\000\000\000\000\377\226\000\000\000\000\000\000\000\370" region_epoch:<conf_ver:5 version:119 > peers:<id:3 store_id:1 > peers:<id:87 store_id:4 > peers:<id:113 store_id:5 >...`

These error messages seem more like for developer, but the error message output should be friendly to user.

**Comment by fubinzh** [comment]
This issue is not fixed yet.
When backupmeta is broken:
![BdVWeyX4t8](https://user-images.githubusercontent.com/7403864/181506339-c96264ee-f6aa-45ff-ad9a-d827b0ea35fc.jpg)

When data file broken, it only report error in 99.9x% restore in finished.
![BdVWeyX4t8](https://user-images.githubusercontent.com/7403864/181506471-8e39ff58-abf6-4ab7-8641-9e0664bfe776.jpg)
