### ISSUE TITLE
Illegal types of arguments (String, Int64) of function equals

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#34765]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table t1(c1 varchar(32), c2 datetime, c3 bigint, c4 varchar(64));
create table t2(b2 varchar(64));
alter table t1 set tiflash replica 1;
alter table t2 set tiflash replica 1;
select count(*) from (select row_number() over (partition by c1 order by c2) num from (select * from t1 left join t2 on t1.c4 = t2.b2) tem2 ) tx where num = 1;

### 2. What did you expect to see? (Required)
No error.
### 3. What did you see instead (Required)
ERROR 1105 (HY000): other error for mpp stream: DB::Exception: Illegal types of arguments (String, Int64) of function equals
### 4. What is your TiFlash version? (Required)
master

**Comment by LittleFall** [comment]
- why other operators won't break?
- most other operators' schema is reset by themself, only Window will inherit from sub-operator.

but it is still dangerous.

**Comment by MimeLyc** [comment]
update
