### ISSUE TITLE
when tidb has some deprecated configurations , upgrade from 6.0.0 to nightly fail 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#34771]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. install tidb cluster with following configs in v6.0.0:
  tidb:
    experimental.enable-global-kill: false
    enable-batch-dml: true
    security.require-secure-transport: false
    oom-action: log
    prepared-plan-cache.enabled: true
    prepared-plan-cache.capacity: 2000
    performance.txn-entry-size-limit: 6000000
    performance.txn-total-size-limit: 6000000
    mem-quota-query: 0
    performance.committer-concurrency: 120
    log.query-log-max-len: 4000
    performance.run-auto-analyze: false
   
2. upgrade to nightly

### 2. What did you expect to see? (Required)

deleted configs can be ignored during upgrade

### 3. What did you see instead (Required)

Error: init config failed: 172.16.5.101:4000: executor.ssh.execute_failed: Failed to execute command over SSH for 'tidb@172.16.5.101:22' {ssh_stderr: , ssh_stdout: [2022/05/18 14:25:43.951 +08:00] [FATAL] [terror.go:292] ["unexpected error"] [error="config file /home/tidb/deploy/tidb-4000/conf/tidb.toml contained invalid configuration options: mem-quota-query, experimental.enable-global-kill, log.query-log-max-len, performance.committer-concurrency, security.require-secure-transport; check TiDB manual to make sure this option has not been deprecated and removed from your TiDB version if the option does not appear to be a typo"] [stack="github.com/pingcap/tidb/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:292\ngithub.com/pingcap/tidb/config.InitializeConfig\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/config/config.go:987\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:170\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"] [stack="github.com/pingcap/tidb/parser/terror.MustNil\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:292\ngithub.com/pingcap/tidb/config.InitializeConfig\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/config/config.go:987\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:170\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]
, ssh_command: export LANG=C; PATH=$PATH:/bin:/sbin:/usr/bin:/usr/sbin /home/tidb/deploy/tidb-4000/bin/tidb-server --config-check --config=/home/tidb/deploy/tidb-4000/conf/tidb.toml }, cause: Process exited with status 1: check config failed

### 4. What is your TiDB version? (Required)

| Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:33:28
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by bb7133** [comment]
> bin/tidb-server --config-check --config=/home/tidb/deploy/tidb-4000/conf/tidb.toml }, cause: Process exited with status 1: check config failed

We have 3 deprecated configs, they should have been added to https://github.com/pingcap/tidb/blob/d2ada35afa3ce447038b0007ae46348eb7cd2699/config/config.go#L918

But the "section" part was missing in #34261(security.require_secure_transport) and #34305(log.query-log-max-len), while 'experimental.enable-global-kill' does not appear in `deprecatedConfig` in #34733.

BTW, we need to add a `--config-check` test for deprecated configurations to avoid those bugs in the future.
