### ISSUE TITLE
set performance.committer-concurrency=120, after upgrade, tidb_committer_concurrency  value changed to 128

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#34809]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. install v6.0.0 with following configs:
server_configs:
  tidb:
    enable-batch-dml: true
    experimental.enable-global-kill: false
    log.query-log-max-len: 4000
    mem-quota-query: 0
    performance.committer-concurrency: 120
    performance.run-auto-analyze: false
    performance.txn-entry-size-limit: 6000000
    performance.txn-total-size-limit: 6000000
    prepared-plan-cache.capacity: 2000
    prepared-plan-cache.enabled: true
    security.require-secure-transport: false
2. upgrade to nightly(6.1.0)
3. check system variable

### 2. What did you expect to see? (Required)
after upgrade, tidb_committer_concurrency value should be 120

### 3. What did you see instead (Required)
```sql
mysql> show variables like 'tidb_committer_concurrency';
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_committer_concurrency | 128   |
+----------------------------+-------+
1 row in set (0.00 sec)

mysql> show global variables like 'tidb_committer_concurrency';
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_committer_concurrency | 128   |
+----------------------------+-------+
1 row in set (0.00 sec)

mysql> 
```
### 4. What is your TiDB version? (Required)

Git Commit Hash: a9614850f9ddb83b60965137f810bd5b65b00bee
Git Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time: 2022-05-19 01:01:06

**Comment by seiya-annie** [comment]
log. tidb_query_log_max_len 
performance.run-auto-analyze: false
these two also have this problem.

**Comment by bb7133** [comment]
Hi @seiya-annie @espresso98 , I can confirm that the issue has been closed by https://github.com/pingcap/tidb/pull/34711.
