### ISSUE TITLE
After br log pausing, the global checkpoint is still moving forward

### ISSUE THREAD

**Issue by zhongmin-amin** [pingcap/tidb#34801]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run log pause

### 2. What did you expect to see? (Required)
1. the global checkpoint will not change until running log resume

### 3. What did you see instead (Required)
1. After br log pausing, the global checkpoint is still moving forward
![Xgf7GbUP9m](https://user-images.githubusercontent.com/81375082/169221991-08d7a79d-b897-42a9-a8cf-ef813f221f03.jpg)
![RX8BjPNDtO](https://user-images.githubusercontent.com/81375082/169222010-e9294f53-f45a-44dd-a8ed-4c91066a97a8.jpg)

After br pausing, the status is sended to the PD, but the changed status on PD is not watched by Tikv. This issue is may be related to the etcd.

### 4. What is your TiDB version? (Required)
v6.1.0-alpha

**Comment by fubinzh** [comment]
Close it, will use tikv bug https://github.com/tikv/tikv/issues/12583  to track the issue.
