### ISSUE TITLE
performance regression in https://github.com/pingcap/tidb/pull/34739

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#34802]
## Enhancement

Found by https://github.com/pingcap/tidb/issues/25754

![image](https://user-images.githubusercontent.com/1420062/169223604-3122b200-3d15-490a-8bb3-6ec5eb7349ed.png)

See http://www.zenlife.tk:18081/

```
cd session;
go test -run XXX -bench BenchmarkPreparedPointGet -benchmem
```

Before the commit vs after:

```
BenchmarkPreparedPointGet-16    	  103684	     11071 ns/op	    6104 B/op	      91 allocs/op
BenchmarkPreparedPointGet-16    	   71532	     15668 ns/op	    8120 B/op	     115 allocs/op
```

@qw4990

**Comment by bb7133** [comment]
IMHO this is expected, since we do not use plan cache for point get(when plan-cache is disabled)

**Comment by qw4990** [comment]
> IMHO this is expected, since we do not use plan cache for point get(when plan-cache is disabled)

+1, it's expected, after https://github.com/pingcap/tidb/pull/34739, point-get plans will be affected by the plan-cache switch as well, which means the optimizer won't cache point-get plan when prep-plan-cache is disabled.
Better to execute `set global tidb_enable_prepared_plan_cache=ON` before performance testing.
