### ISSUE TITLE
list columns of table is not correct in information_schema

### ISSUE THREAD

**Issue by iammyu** [pingcap/tidb#34834]
### 1. Minimal reproduce step (Required)

![middle_img_v2_3ef9e1c8-bec1-4eaf-acc1-cb7276b1fbcg](https://user-images.githubusercontent.com/95269537/169292022-43c7ec60-a81d-444b-9885-ac7526dd94c1.jpg)

### 2. What did you expect to see? (Required)

above.

### 3. What did you see instead (Required)

above.

### 4. What is your TiDB version? (Required)

master

**Comment by ChenPeng2013** [comment]
@iammyu did you set `tidb_enable_list_partition=on`?

**Comment by iammyu** [comment]
@ChenPeng2013 That is the question.
