### ISSUE TITLE
variable: sysvar `tidb_query_log_max_len` was not correctly inherited from upgraded clusters.

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#34836]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Set `log.query-log-max-len` to a customed value(4000, for example) and start a TiDB cluster in released version(v6.0, for example).

Check the config and `tidb_query_log_max_len`:

```
tidb> select @@tidb_config;
...
        "log": {
                "query-log-max-len": 4000,
        },
...
tidb> show variables like '%tidb_query_log_max_len%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| tidb_query_log_max_len | 4000  |
+------------------------+-------+
1 row in set (0.00 sec)
```

Please notice that `@@tidb_query_log_max_len` exists already in previous releases(#15833).

Then, we could upgrade the cluster to the latest nightly version(`a84299b8ff97d5ea30e7f2715fd7c83ec22392b6`) and check the value of system variable `tidb_query_log_max_len`.

### 2. What did you expect to see? (Required)

After upgrade:
```
tidb> show variables like '%tidb_query_log_max_len%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| tidb_query_log_max_len | 4000 |
+------------------------+-------+
1 row in set (0.00 sec)
```
### 3. What did you see instead (Required)
```
tidb> show variables like '%tidb_query_log_max_len%';
+------------------------+-------+
| Variable_name          | Value |
+------------------------+-------+
| tidb_query_log_max_len | 4096  |
+------------------------+-------+
1 row in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)
```
Release Version: v6.1.0-alpha-478-ga84299b8f
Edition: Community
Git Commit Hash: a84299b8ff97d5ea30e7f2715fd7c83ec22392b6
Git Branch: master
UTC Build Time: 2022-05-19 14:16:07
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by bb7133** [comment]
I suspect the bug may caused by the fact that `tidb_query_log_max_len` exists already, ref https://github.com/pingcap/tidb/issues/34809.

PTAL @morgo @espresso98

**Comment by morgo** [comment]
I'm going to close this as won't fix, because of the difficulty in knowing which is the correct behavior.
