### ISSUE TITLE
pitr need to discard unused checkpoint after scale-in tikv

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tidb#34832]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- execute full backup for tidb-cluster
- keep the workloads and open log backup
- scale-in one tikv
- check the log backup status

### 2. What did you expect to see? (Required)
the checkpoint of the scaled tikv will removed

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/23207893/169274065-ed607a1f-4dbd-4d3f-9d7a-7a0953a45545.png)

### 4. What is your TiDB version? (Required)
Release Version: v6.1.0-alpha
Git Commit Hash: a9614850f9ddb83b60965137f810bd5b65b00bee

**Comment by fubinzh** [comment]
Similar issue seen when deleting a store using cli "ctl pd store delete xx" to delete a store.

**Comment by 3pointer** [comment]
https://github.com/pingcap/tidb/pull/36114/files fix it
