### ISSUE TITLE
default values of system variable "tidb_enable_prepared_plan_cache " and " tidb_prepared_plan_cache_size " are incorrect after upgrade

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#34848]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

install a v6.0.0 tidb cluster without doing any configuration
upgrade to nightly(v6.1.0)
check default value of system variable

### 2. What did you expect to see? (Required)
tidb_enable_prepared_plan_cache	ON
tidb_prepared_plan_cache_size	100

### 3. What did you see instead (Required)
Our current processing behavior is that if a configuration item has not been specifically configured before the upgrade, the value of the configuration item after the upgrade should be the same as the default value of the newly installed cluster.
in v6.1.0, these two default values have changed to "ON" and "100"

after upgrade, the default value is:
tidb_enable_prepared_plan_cache	OFF
tidb_prepared_plan_cache_size	1000

### 4. What is your TiDB version? (Required)

Git Commit Hash: https://github.com/pingcap/tidb/commit/6a0239362da379223556fad1f76f42273654423b
Git Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time: 2022-05-19 15:26:56

**Comment by qw4990** [comment]
I think it's expected because we cannot know whether the value `(OFF, 1000)` is set by the user deliberately. So for safety, inheriting all confit items existing in the config file seems a better choice.

**Comment by qw4990** [comment]
Could you please give some suggestion for this issue? @bb7133 @morgo
