### ISSUE TITLE
add index on timestamp column causes index-lookup to fail

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#3485]
1. What did you do?

```sql
use test;
drop table if exists t1;
CREATE TABLE `t1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `datetime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
   PRIMARY KEY (`id`)
);

INSERT INTO `t1` VALUES (123381351,"2014-03-31 08:57:10");
select * from t1 where datetime='2014-03-31 08:57:10';
alter table t1 add key i_datetime (datetime);
select * from t1 where datetime='2014-03-31 08:57:10';
select * from t1;
```

2. What did you expect to see?

`select * from t1 where datetime='2014-03-31 08:57:10';` should return result after adding index on datetime

3. What did you see instead?

```sql
mysql> select * from t1 where datetime='2014-03-31 08:57:10';
Empty set (0.00 sec)

mysql> select * from t1;
+-----------+---------------------+
| id        | datetime            |
+-----------+---------------------+
| 123381351 | 2014-03-31 08:57:10 |
+-----------+---------------------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?

Git Commit Hash: fad663398a7eccd9948e9b4b8857151c6e188dce
UTC Build Time:  2017-06-15 06:43:00

it is reproducible with patch in  pr https://github.com/pingcap/tidb/pull/3478, so it seems not related to issue #3467, so I opened a new one

**Comment by shenli** [comment]
@Darren Thanks!
@tiancaiamao PTAL
