### ISSUE TITLE
Parser fails to detect an obvious error in Grant sql

### ISSUE THREAD

**Issue by bo-er** [pingcap/tidb#34856]
### 1. Minimal reproduce step 

```
func Test_InValidGrant(t *testing.T) {
	grant := "grant AAA ON *.* TO steve@'%' WITH GRANT OPTION;"
	p := parser.New()

	_, _, err := p.Parse(grant, "", "")
	if err == nil {
		t.Error("expect to get an error")
	}
}
```

### 2. What did you expect to see? 

I expect to see the testing passes.

### 3. What did you see instead 

I see it fails

### 4. What is your TiDB version? 

github.com/pingcap/tidb v1.1.0-beta.0.20220507000631-be484475e76b
github.com/pingcap/tidb/parser v0.0.0-20220507000631-be484475e76b

**Comment by bb7133** [comment]
Hi @bo-er , this syntax is valid in MySQL 8 and TiDB, so it is intentional.

**Comment by bo-er** [comment]
> 
@bb7133  Excuse me, but I have looked through the documentation(https://dev.mysql.com/doc/refman/8.0/en/grant.html) , and it doesn't mention supporting a custom syntax. I am new to the TIDB family, could you please shed more light on why it's intentional?   🙇🏻‍♂️ Best regards.

**Comment by bo-er** [comment]
I also observed TIDB parser recognized `grant execute on get_dmp_crew bo-er@localhost;` as a valid grant statement.   From my understanding, the SQL format of granting stored routine level privilege should be like: "GRANT EXECUTE ON [ PROCEDURE | FUNCTION ] object TO user;".  Am I having some misconception here or it's another deliberate design decision?
