### ISSUE TITLE
Wrong result when pushing down aggregate past outer joins

### ISSUE THREAD

**Issue by fixdb** [pingcap/tidb#34863]
### 1. Minimal reproduce step (Required)

```sql
create table customer2(c_id bigint);
create table orders2(o_id bigint, c_id bigint);
insert into customer2 values(1),(2),(3),(4),(5);
insert into orders2 values(1,1),(2,1),(3,2),(4,2),(5,2);

set @@tidb_opt_agg_push_down=1;
select count(*) from customer2 c left join orders2 o on c.c_id=o.c_id;
```

### 2. What did you expect to see? (Required)
```sql
tidb> select count(*) from customer2 c left join orders2 o on c.c_id=o.c_id;
+----------+
| count(*) |
+----------+
|        8 |
+----------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
```sql
tidb> select count(*) from customer2 c left join orders2 o on c.c_id=o.c_id;
+----------+
| count(*) |
+----------+
|        5 |
+----------+
1 row in set (0.00 sec)

tidb> explain select count(*) from customer2 c left join orders2 o on c.c_id=o.c_id;
+----------------------------------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------+
| id                               | estRows | task      | access object | operator info                                                                                              |
+----------------------------------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------+
| HashAgg_9                        | 1.00    | root      |               | funcs:count(Column#7)->Column#6                                                                            |
| └─HashJoin_10                    | 5.00    | root      |               | left outer join, equal:[eq(test.customer2.c_id, test.orders2.c_id)]                                        |
|   ├─HashAgg_16(Build)            | 4.00    | root      |               | group by:test.orders2.c_id, funcs:count(1)->Column#7, funcs:firstrow(test.orders2.c_id)->test.orders2.c_id |
|   │ └─TableReader_23             | 5.00    | root      |               | data:Selection_22                                                                                          |
|   │   └─Selection_22             | 5.00    | cop[tikv] |               | not(isnull(test.orders2.c_id))                                                                             |
|   │     └─TableFullScan_21       | 5.00    | cop[tikv] | table:o       | keep order:false, stats:pseudo                                                                             |
|   └─TableReader_13(Probe)        | 5.00    | root      |               | data:TableFullScan_12                                                                                      |
|     └─TableFullScan_12           | 5.00    | cop[tikv] | table:c       | keep order:false, stats:pseudo                                                                             |
+----------------------------------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------+
8 rows in set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

```sql
tidb> select version();
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v6.1.0-alpha-482-g0700ddd77 |
+-----------------------------------------+
1 row in set (0.01 sec)
```

**Comment by zanmato1984** [comment]
Why is it component tiflash? @ChenPeng2013 @jebter

**Comment by zanmato1984** [comment]
And why no sig/execution label any more? Are we deprecating sig labels?

**Comment by jebter** [comment]
The label is wrong, it has been fixed

**Comment by zanmato1984** [comment]
This is known as a planner rewriting issue. According to @windtalker , the null flag is not set properly during rewriting.

Besides, this issue only appears when `tidb_opt_agg_push_down` is `ON`, which defaults to `OFF`.

So changing the labels to planner and major.

**Comment by Yisaer** [comment]
I think the main reason is that `count(*)` becomes the different column between whether enable `tidb_opt_agg_push_down` or not. 

That is to say, if we disable `tidb_opt_agg_push_down`, the query is equal to 
```sql
select count(c.c_id) from customer2 c left join orders2 o on c.c_id=o.c_id;
```

and if we enabled `tidb_opt_agg_push_down`, the query is equal to 
```sql
select count(o.c_id) from customer2 c left join orders2 o on c.c_id=o.c_id;
```

I think a proper way is to forbid `count` pushed down if it didn't point out the dedicated column in its args.

**Comment by windtalker** [comment]
> I think the main reason is that `count(*)` becomes the different column between whether enable `tidb_opt_agg_push_down` or not.
> 
> That is to say, if we disable `tidb_opt_agg_push_down`, the query is equal to
> 
> ```sql
> select count(c.c_id) from customer2 c left join orders2 o on c.c_id=o.c_id;
> ```
> 
> and if we enabled `tidb_opt_agg_push_down`, the query is equal to
> 
> ```sql
> select count(o.c_id) from customer2 c left join orders2 o on c.c_id=o.c_id;
> ```
> 
> I think a proper way is to forbid `count` pushed down if it didn't point out the dedicated column in its args for outer join.

I think it is not enough, the root cause is for outer join, the columns generate from outer column after join is not the columns from outer table(it might convert to null if join is not matched) before join, so it is very dangerous to pushdown agg to the outer table. If we have to pushdown agg to the outer table, I prefer use a whitelist instead of a blacklist. 
As a concrete example, after patch you pr and pr in #34779, the following query still return wrong results
```
mysql> set @@tidb_opt_agg_push_down=0;
Query OK, 0 rows affected (0.00 sec)

mysql>  select sum(o.c_id is null) from customer2 c left join orders2 o on c.c_id=o.c_id;
+---------------------+
| sum(o.c_id is null) |
+---------------------+
|                   3 |
+---------------------+
1 row in set (0.01 sec)

mysql> set @@tidb_opt_agg_push_down=1;
Query OK, 0 rows affected (0.00 sec)

mysql>  select sum(o.c_id is null) from customer2 c left join orders2 o on c.c_id=o.c_id;
+---------------------+
| sum(o.c_id is null) |
+---------------------+
|                   0 |
+---------------------+
1 row in set (0.02 sec)

```

**Comment by Yisaer** [comment]
> > I think the main reason is that `count(*)` becomes the different column between whether enable `tidb_opt_agg_push_down` or not.
> > That is to say, if we disable `tidb_opt_agg_push_down`, the query is equal to
> > ```sql
> > select count(c.c_id) from customer2 c left join orders2 o on c.c_id=o.c_id;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and if we enabled `tidb_opt_agg_push_down`, the query is equal to
> > ```sql
> > select count(o.c_id) from customer2 c left join orders2 o on c.c_id=o.c_id;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I think a proper way is to forbid `count` pushed down if it didn't point out the dedicated column in its args for outer join.
> 
> I think it is not enough, the root cause is for outer join, the columns generate for outer table after join is not the columns from outer table(it might convert to null if join is not matched) before join, so it is very dangerous to pushdown agg to the outer table. If we have to pushdown agg to the outer table, I prefer use a whitelist instead of a blacklist. As a concrete example, after patch you pr and pr in #34779, the following query still return wrong results
> 
> ```
> mysql> set @@tidb_opt_agg_push_down=0;
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql>  select sum(o.c_id is null) from customer2 c left join orders2 o on c.c_id=o.c_id;
> +---------------------+
> | sum(o.c_id is null) |
> +---------------------+
> |                   3 |
> +---------------------+
> 1 row in set (0.01 sec)
> 
> mysql> set @@tidb_opt_agg_push_down=1;
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql>  select sum(o.c_id is null) from customer2 c left join orders2 o on c.c_id=o.c_id;
> +---------------------+
> | sum(o.c_id is null) |
> +---------------------+
> |                   0 |
> +---------------------+
> 1 row in set (0.02 sec)
> ```

Good catch, I think we can forbid push down agg to outer table in outer join for now, and find out the white list later.

**Comment by fixdb** [comment]
Sorry, I had the fix, but didn't get the chance to raise a PR.

I don't think it is wise to disable agg push down for outer joins. We can still push down agg for outer joins as long as the aggregate function arguments don't refer the columns from inner tables.

The root cause for this bug is that in function `aggregationPushDownSolver.getAggFuncChildIdx` doesn't consider the case count(*), or sum(1) ... that no columns are referenced from inner/outer tables, in which case `fromLeft` is false, `fromRight` is also false, the function just returns 1, which means from right. But the right child is inner child from left outer join, so we see the wrong result. But if the query is right outer join, we are fine.

So the fix should be update `aggregationPushDownSolver.getAggFuncChildIdx` to return correct number, and in `aggregationPushDownSolver.collectAggFuncs`, make sure for outer joins, all the aggregate arguments come from outer tables, if the arguments are constants, just put the the agg functions to outer funcs. By doing this, we can continue offering eager aggregate for outer joins.

**Comment by Yisaer** [comment]
After I discussed with @fixdb , we think there are 3 cases we can push agg across join in outer join:

1. The references columns in args expression from functions are all from outer table, then the agg can be push down to outer table
2. The args in functions are dedicated columns, then the agg can be push down to the table which depends on join type.  This is which i mentioned in https://github.com/pingcap/tidb/issues/34863#issuecomment-1135622767
4. The args in functions are constant, then the agg can only be possible to push down to outer table.
