### ISSUE TITLE
[Dynamic Region] Buckets are not working as expected.

### ISSUE THREAD

**Issue by SpadeA-Tang** [pingcap/tidb#34894]
## Description

After enabling `coprocessor.enable-region-bucket`, region will be split into buckets logically and reports region information as well as bucket keys to PD periodically. TiDB will use these buckets to split cop requests into bucket level sub tasks whose information can be found in `explain analyze select ...`. 

I set bucket size to be very small and insert some data that guarantee that the region will not be split but generate some bucket keys.

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`create database test1;`
`create table t (id int primary key, c int, d int);`
`insert into t values(i, i, i);` i from 1 to 20
Wait for 60 seconds which is enough for region to splits, generates buckets, and  reports to PD.
`select * from t;` The response carrys more update-to-date bucket version which makes TiDB to reload region from PD.
`explain analyze select * from t;`

We can see the followering which is good as cop_task number to be larger than 1.
![image](https://user-images.githubusercontent.com/71589810/169805734-133cd3bd-22ba-4fdc-8a55-df06617fed7c.png)

However, when I drop test1 and create database test2 and insert these data again. And do `explain analyze ...`. The result is as followers.
![image](https://user-images.githubusercontent.com/71589810/169809137-7919a433-218e-4b2a-a03b-8e39cac6b3f1.png)

### 2. What did you expect to see? (Required)
Cop_task num is expected to be larger than 1.

### 4. What is your TiDB version? (Required)

TiDB version:
0cf93b5f51a9fa510e7ccc6937051f42e07ed69b
TiKV version:
1fb8980ccab9ff40c1adc206df52952dab8e8ad8

**Comment by zanmato1984** [comment]
@ChenPeng2013 This seems to be a region bucket problem. Please contact the owner of region bucket. I'm removing the sig/execution label.

**Comment by SpadeA-Tang** [comment]
> 

Fine.
