### ISSUE TITLE
deploy with operator miss some metrics

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#34907]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy tidb cluster with operator
2. connect and do some analyze table
3. see the TiDB dashboard "Memory Usage", "Stats Cache LRU Cost", "Stats Cache LRU OPS" panel

### 2. What did you expect to see? (Required)
1. "Memory Usage" has "analyze-xxx"
2. "Statistics" has "Stats Cache LRU Cost", "Stats Cache LRU OPS" panel
### 3. What did you see instead (Required)
can't see them
### 4. What is your TiDB version? (Required)
```sql
MySQL root@rms-staging.pingcap.net:(none)> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.1.0
Edition: Community
Git Commit Hash: 9f7813ca6009fce061e92ae38a0b45cbfbc200f4
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-05-20 06:36:00
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by Yisaer** [comment]
For v6.1.0-pre initializer, it workes well.
