### ISSUE TITLE
deleted configs still can be found in 'select @@tidb_config\G;'

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#34945]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. scratch install a v6.1.0 tidb cluster, without doing any configuration
2. execute 'select @@tidb_config\G;'

### 2. What did you expect to see? (Required)
the deleted configs don't displayed in the result

### 3. What did you see instead (Required)
following configs can be found in result
	"enable-global-kill": true,
	"enable-batch-dml": false,
	"mem-quota-query": 0,
	"oom-action": ""
	"committer-concurrency": 0,
		"run-auto-analyze": false
       query-log-max-len: 0
      prepared-plan-cache.enabled: false,
      prepared-plan-cache.capacity: 1000,
 the Complete result: [610-tidb.txt](https://github.com/pingcap/tidb/files/8769053/610-tidb.txt)

### 4. What is your TiDB version? (Required)

Git Commit Hash: 7abf6f9696061c6ab6f09cb003282b39014bd067
Git Branch: heads/refs/tags/v6.1.0-alpha
UTC Build Time: 2022-05-24 14:58:32

**Comment by morgo** [comment]
This is fixed in https://github.com/pingcap/tidb/pull/34927

**Comment by morgo** [comment]
@CbcWestwolf Sorry, I'm going to reassign to myself because I have an existing PR open :-)
