### ISSUE TITLE
Possibility of Table-level ordering in TiCDC

### ISSUE THREAD

**Issue by zhenchuan9r** [pingcap/tidb#34951]
We have a downstram app that incorporates aggregation operations on the event stream.
For example, given the source table
```
create table table_source (
id bigint primary key,
a varchar(20)
)
```
we need to aggregate the cdc data by column a and fill the data into the destination table
```
create table table_destination (
final_id bigint,
a varchar(20) primary key
)
```
However, as TiCDC does not guarentee table-level ordering, the aggregated data can be inaccurated.
I wonder if there is any possibility to implement table-level ordering in TiCDC.
Or is there any hints on implementing the reordering of events in downstream apps?
Thanks very much.

**Comment by zhenchuan9r** [comment]
https://github.com/pingcap/tiflow/issues/5598
The same question in TiFlow repo.

**Comment by overvenus** [comment]
See comments in https://github.com/pingcap/tiflow/issues/5598#issuecomment-1139254845
