### ISSUE TITLE
system variables tidb_gc_max_wait_time do not taking effect on all tidb nodes

### ISSUE THREAD

**Issue by vivid392845427** [pingcap/tidb#34966]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
1. connect to tidb-0 and update the system variable value to: set global tidb_gc_max_wait_time = 1200;
2. connect to tidb-1 and query the system variable tidb_gc_max_wait_time value is 1200;
3. Execute tpcc 1000 warehouse, 1024 threads
4. check the tidb log, and confirm that gc and auto analyze are executed on the tidb-1 node, check the execution of gc and auto analyze.
```

### 2. What did you expect to see? (Required)

`gc safepoint is advanced after more than 20 minutes; auto analyze fails after more than 20 minutes`

### 3. What did you see instead (Required)

`gc safepoint does not advance for more than 30 minutes, and auto analyze is executed for more than 30 minutes without failure.`

### 4. What is your TiDB version? (Required)

```
Release Version: v6.1.0-nightly
Edition: Community
Git Commit Hash: dce5064e9e15d0b17c36f73e21fc71bcaa419e90
Git Branch: heads/refs/tags/v6.1.0-nightly
UTC Build Time: 2022-05-25 06:18:14
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
```

**Comment by TonsnakeLin** [comment]
is is caused by this code:
func (sv *SysVar) SkipSysvarCache() bool {
	switch sv.Name {
	case TiDBGCEnable, TiDBGCRunInterval, TiDBGCLifetime,
		TiDBGCConcurrency, TiDBGCScanLockMode, **TiDBGCMaxWaitTime**:
		TiDBGCConcurrency, TiDBGCScanLockMode:
		return true
	}
	return false
}
