### ISSUE TITLE
"Auto Analyze Duration 95" Its unit should be time

### ISSUE THREAD

**Issue by buggithubs** [pingcap/tidb#34984]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

https://github.com/pingcap/tidb/blob/0f85650aa43cb60a77ce507e02203db45584e914/metrics/grafana/tidb.json#L10696-L10718

"Auto Analyze Duration 95" Its unit should be time

`histogram_quantile(0.95, sum(rate(tidb_statistics_auto_analyze_duration_seconds_bucket{k8s_cluster="$k8s_cluster", tidb_cluster="$tidb_cluster", instance=~"$instance"}[1m])) by (le))`

<img width="604" alt="image" src="https://user-images.githubusercontent.com/11624213/170456567-b64dcdf7-9965-4f20-8a42-2cdc57fb5d53.png">

**Comment by hawkingrei** [comment]
It has been fixed by #50834.
