### ISSUE TITLE
Question about TiDB sysbench result

### ISSUE THREAD

**Issue by Zhoutall** [pingcap/tidb#3501]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I do a sysbench test for TiDB using the default configuration. The test result is not as good as expected. So what's wrong or how to fix it.
Three machines (32 cores, 128GB memory).
A: pd, tidb, tikv1
B: tikv2
C: tikv3

2. What did you expect to see?

3. What did you see instead?
Here is my test result.
select
100 threads, 4.2w read, 6.7ms rt
200 threads, 5w read, 8.2ms rt
500 threads, 5.7w read, 13.0ms rt
insert
100 threads, 1w write, 12ms rt
200 threads, 1.1w write, 20ms rt
500 threads, 0.96w write, 55ms rt
oltp
100 threads, 1450 tps, 2w read, 5700 write, 144ms rt
200 threads, 1660 tps, 2.3w read, 6600 write, 210ms rt
500 threads, 1750 tps, 2.5w read, 7000 write, 500ms rt

4. What version of TiDB are you using (`tidb-server -V`)?
The lastest release version, tidb-server rc2.

**Comment by shenli** [comment]
@Zhoutall Thanks for your feedback!
1. Please do not deploy pd and tikv on the same disk.
2. You could tune tikv according to this doc: https://github.com/pingcap/docs-cn/blob/master/op-guide/tune-tikv.md
3. Using SSD for tikv will improve performance.
4. How many tables and rows do you prepared for the test?

**Comment by DavisLinDB** [comment]
@shenli 

Some website say that TiDB can get million QPS in test environment.  Could you show that what's environment can get the high QPS?

**Comment by Zhoutall** [comment]
@shenli 
1. For select and oltp, --oltp-tables-count=10 --oltp-table-size=200000
2. For insert, --oltp-tables-count=10
3. All machines are using SSD.

**Comment by shenli** [comment]
@Zhoutall 
First at all, you should prepare more data. In our environment, we normally prepare more than 100 tables and more than 1 million rows in each table. Than you should tune TiKV following the document.
To get QPS more than 1 million, you should add more tidb-server and tikv-sever instance. You will get linear growth on the QPS as you adding tidb-server or tikv-server (It depends on the bottle neck. Please pay attention to the cpu consuming of tidb-servers  and cpu/io consuming of tikv-servers).

**Comment by c4pt0r** [comment]
@Zhoutall Any updates? I think shenli gave a clear explanation?
