### ISSUE TITLE
behaviour is not same as MySQL with `bit` type when sql_mode=''

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#35078]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set sql_mode='';
create table t(a bit not null);
insert into t values (NULL);
```

### 2. What did you expect to see? (Required)

```
mysql> insert into t values (NULL);
ERROR 1048 (23000): Column 'a' cannot be null
```

### 3. What did you see instead (Required)

```
mysql> insert into t values (NULL);
ERROR 8138 (HY000): writing inconsistent data in table: t, expected-values:{KindMysqlBit } != record-values:{KindMysqlBit 0x00}
```

**Comment by fanrenhoo** [comment]
I tested, this issue already changed the behavior, like:

MySQL [dbtest]> insert into t8 values (NULL);
Query OK, 1 row affected, 1 warning (0.00 sec)

MySQL [dbtest]> show warnings;
+---------+------+---------------------------+
| Level   | Code | Message                   |
+---------+------+---------------------------+
| Warning | 1048 | Column 'a' cannot be null |
+---------+------+---------------------------+
1 row in set (0.00 sec)

**Comment by fanrenhoo** [comment]
may this should be right I think, better than MySQL
