### ISSUE TITLE
Invalid time format

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#3509]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
CREATE TABLE t1 (ts int);
INSERT INTO t1 (ts) VALUES (Unix_timestamp('2002-10-27 01:00'));

2. What did you expect to see?
mysql> INSERT INTO t1 (ts) VALUES (Unix_timestamp('2002-10-27 01:00'));
Query OK, 1 row affected (0.00 sec)

mysql> select * from t1;
+------------+
| ts         |
+------------+
| 1035651600 |
+------------+
1 row in set (0.00 sec)

3. What did you see instead?
mysql>  INSERT INTO t1 (ts) VALUES (Unix_timestamp('2002-10-27 01:00'));
ERROR 1105 (HY000): invalid time format

In tidb-server log:

> 2017/06/19 22:49:33 constant_fold.go:40: [warning] There may exist an error during constant folding. The function name is unix_timestamp, args are [2002-10-27 01:00]
> 2017/06/19 22:49:33 tidb.go:166: [info] RollbackTxn for ddl/autocommit error. 
> 2017/06/19 22:49:33 txn.go:143: [info] [kv] Rollback txn 392661243935326208
> 2017/06/19 22:49:33 session.go:623: [warning] [1] session error:
> /Users/shenli/work/go/src/github.com/pingcap/tidb/util/types/time.go:33: invalid time format
> /Users/shenli/work/go/src/github.com/pingcap/tidb/util/types/time.go:573: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/util/types/time.go:1110: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/expression/builtin_time.go:1656: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/executor/write.go:827: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/executor/write.go:815: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/executor/write.go:647: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/executor/adapter.go:182: 
> /Users/shenli/work/go/src/github.com/pingcap/tidb/tidb.go:172: 
> {

4. What version of TiDB are you using (`tidb-server -V`)?
2017/06/19 22:49:27 printer.go:33: [info] Git Commit Hash: 4b4378fdd4d7f06fe3c3e0e20ef73bd093f0a1bf
2017/06/19 22:49:27 printer.go:34: [info] UTC Build Time:  2017-06-19 02:48:03

**Comment by shenli** [comment]
@tiancaiamao @XuHuaiyu PTAL

**Comment by XuHuaiyu** [comment]
@shenli 
TiDB can only handle some normal format of time string now,
the format mentioned in this issue will be added quickly.
