### ISSUE TITLE
Can the meaning of ErrKeyColumnDoesNotExits be more clear?

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#35102]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Some applications like DM need to retry basing on the error. Now ErrKeyColumnDoesNotExits has two meanings:

- If retry later, the DDL may succeed, like https://github.com/pingcap/tidb/blob/8401fa0263df9def3b8f4cf359782d40f0f8d101/ddl/column.go#L1551
- If retry later, the DDL will not succeed, like https://github.com/pingcap/tidb/blob/8401fa0263df9def3b8f4cf359782d40f0f8d101/ddl/ddl_api.go#L1870

**Describe the feature you'd like:**

Assign the first case a different error code.

**Describe alternatives you've considered:**

We use error message to tell them apart, but the error message may change in future.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
PTAL @zimulala @hawkingrei

**Comment by hawkingrei** [comment]
https://github.com/pingcap/tidb/blob/8401fa0263df9def3b8f4cf359782d40f0f8d101/ddl/column.go#L1551

it means as it describes. if it finds the columns have been changed when it is changing the columns. it will return errors. I think it can be changed by the other error id.
