### ISSUE TITLE
a little different in the field name with `SHOW TABLES LIKE` with MySQL and TiDB

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#35116]
## Enhancement

```
QUERY >	 SHOW TABLES LIKE 'apigw_routes'
TiDB  >
+-------------------+
| Tables_in_corteza |
+-------------------+
| apigw_routes      |
+-------------------+
MySQL >
+----------------------------------+
| Tables_in_corteza (apigw_routes) |
+----------------------------------+
| apigw_routes                     |
+----------------------------------+
```

**Comment by likzn** [comment]
And i find something else
1. `show databases ... like ...` also have this issue
2. If we do not use `like` , it will not append `LikePattern` name

Some ref in Mysql :https://github.com/mysql/mysql-server/blob/3e90d07c3578e4da39dc1bce73559bbdf655c28c/sql/dd/info_schema/show.cc#L537-L545
