### ISSUE TITLE
"PRIMARY KEY CLUSTERED (a, b)" doesn't fail but also doesn't take effect

### ISSUE THREAD

**Issue by Dieken** [pingcap/tidb#35121]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t (a int not null, b int not null, c varchar(100), primary key clustered (a, b));
show create table t;

### 2. What did you expect to see? (Required)

It should fail on SQL parsing, or make sure the primary key is clustered.

### 3. What did you see instead (Required)

`show create table t` reports non-clustered primary key.

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.0.0
Edition: Community
Git Commit Hash: 36a9810441ca0e496cbd22064af274b3be771081
Git Branch: heads/refs/tags/v6.0.0
UTC Build Time: 2022-03-31 10:27:25
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by tangenta** [comment]
For the MySQL-compatibility reason, the keyword `CLUSTERED` is not reserved. In this case, you are trying to assign the name "clustered" to the primary key. However, this name is ignored according to [MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/create-table.html):

> The name of a PRIMARY KEY is always PRIMARY.

The correct usage is:
```sql
create table t (a int not null, b int not null, c varchar(100), primary key (a, b) clustered);
```

Frankly speaking, this is really confusing. How about reporting a warning like "the primary key name 'clustered' is ignored"?  @easonn7 @bb7133

**Comment by tiancaiamao** [comment]
Try this to assign the name `clustered` to the primary key?
```
create table t (a int not null, b int not null, c varchar(100), primary key `clustered` (a, b));
```

Or make it a reserved keyword?

**Comment by tangenta** [comment]
@tiancaiamao Making it a reserved keyword can break the MySQL compatibility and TiDB's backward compatibility:

```
create table clustered (a int);

ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 20 near "clustered (a int)"
```

**Comment by Dieken** [comment]
I agree with @tangenta,  a warning is enough:

No warning(I don't mind it warns too):
```
create table t (a int not null, b int not null, c varchar(100), primary key `clustered` (a, b));
```

warning: `Do you mean "primary key (a, b) clustered" ?`
```
create table t (a int not null, b int not null, c varchar(100), primary key clustered (a, b));
```

According to https://docs.pingcap.com/tidb/stable/clustered-indexes, TiDB does support `primary key clustered` for single column, so people probably will forget `clustered` must follow the multiple columns in standalone primary key definition,  and due to https://docs.pingcap.com/tidb/stable/clustered-indexes#add-or-drop-clustered-indexes it's annoying to fix this mistake after the table is full of data.
