### ISSUE TITLE
partition prune has index out of range problem

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#35181]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t` (
`a` int(11) DEFAULT NULL,
`b` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`a`)
(PARTITION `p0` VALUES LESS THAN (2021),
PARTITION `p1` VALUES LESS THAN (3000))
```

 insert into t select * from t where a=3000;

### 2. What did you expect to see? (Required)
Success

### 3. What did you see instead (Required)
tidb> insert into t select * from t where a=3000;
ERROR 1105 (HY000): runtime error: index out of range [2] with length 2

### 4. What is your TiDB version? (Required)

master

**Comment by lcwangchao** [comment]
Seems here has some bug: https://github.com/pingcap/tidb/blob/36a9810441ca0e496cbd22064af274b3be771081/planner/core/rule_partition_processor.go#L875

When a condition `a=xxx` cannot match any partition, the start will get a value with `len(pruner.lessThan.data)`

**Comment by AilinKid** [comment]
> Seems here has a bug:
> 
> https://github.com/pingcap/tidb/blob/36a9810441ca0e496cbd22064af274b3be771081/planner/core/rule_partition_processor.go#L875
> 
> When a condition `a=xxx` cannot match any partition, the start will get a value with `len(pruner.lessThan.data)`

Yes, better use `a=x` for easy reproduction.  x is the upper bound of your last partition (NO MAXVALUE)

**Comment by zimulala** [comment]
@lcwangchao Do you interest to fix this issue?

**Comment by yiwen92** [comment]
The root cause here is for this sql-"insert into t select * from t where a=3000; " the 'a= 3000' is out of the range of defined partition value? So what will the behavior for the Minimal reproduce be like?
