### ISSUE TITLE
Derived table without alias is not resulting error in TiDB.

### ISSUE THREAD

**Issue by ramanich1** [pingcap/tidb#35194]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
drop table if exists t1,t2;
CREATE TABLE t1 ( a INT );
INSERT INTO t1 VALUES ( 1 );
CREATE TABLE t2 ( a INT );
INSERT INTO t2 VALUES ( 2 );

SELECT * FROM ((((SELECT 1 FROM t1)) UNION   SELECT 2 FROM t1));
```

### 2. What did you expect to see? (Required)
```sql
mysql> SELECT * FROM ((((SELECT 1 FROM t1)) UNION   SELECT 2 FROM t1));
ERROR 1248 (42000): Every derived table must have its own alias
```
### 3. What did you see instead (Required)
```sql
mysql> SELECT * FROM ((((SELECT 1 FROM t1)) UNION   SELECT 2 FROM t1));
+------+
| 1    |
+------+
|    2 |
|    1 |
+------+
2 rows in set (0.00 sec)
```
### 4. What is your TiDB version? (Required)

```sql
mysql> select version();
+-----------------------------------------------+
| version()                                     |
+-----------------------------------------------+
| 5.7.25-TiDB-v6.1.0-alpha-482-g81a852077-dirty |
+-----------------------------------------------+
```

**Comment by zanmato1984** [comment]
I don't think this should be treated as a bug. We just support something that MySQL considers as a restriction. This is actually a feature.

What do you guys think? @ramanich1 @seiya-annie

**Comment by zanmato1984** [comment]
I'm closing this issue. We don't consider this kind of mismatch, that is, MySQL has some restriction so does NOT implement but TiDB overcomes this restriction and supports, as a bug. Unless some correctness concerns are related, which I don't see in this specific case.
