### ISSUE TITLE
TiDBLogFileMaxDays and TiDBConfig should be ScopeInstance

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#35190]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

From manual inspection of code:
https://github.com/pingcap/tidb/blob/11e1f1417844305f0982a18c26fea5e1aec726fa/sessionctx/variable/sysvar.go#L203-L225

### 2. What did you expect to see? (Required)

These sysvars should be instance scoped. They have no relation to the current session.

### 3. What did you see instead (Required)

See above

### 4. What is your TiDB version? (Required)

master

**Comment by bb7133** [comment]
There was no instance scoped variables at the time `tidb_log_file_max_days` was introduced, so I would treat this issue as 'enhancement'.
