### ISSUE TITLE
I got a mysql prepare error

### ISSUE THREAD

**Issue by Ayugakki** [pingcap/tidb#35223]
## Bug Report
补充 DDL 和DML信息
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 591
Server version: 5.7.25-TiDB-v5.4.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible
DDL
```
CREATE TABLE IF NOT EXISTS `t_user_test`  (
    id   bigint UNSIGNED NOT NULL
        PRIMARY KEY,
    name varchar(64)     NOT NULL COMMENT 'name'
)
    COMMENT 'user-table'
    COLLATE = utf8mb4_unicode_ci;
INSERT INTO t_user_test (id, name) VALUES (1, 'jack');
INSERT INTO t_user_test (id, name) VALUES (2, 'rose');
```
DML
```
PREPARE stmt from  'SELECT * FROM `t_user_test` WHERE `id` IN (?) ORDER BY `id` DESC';
SET @id=1;
SET @id2=2;
EXECUTE  stmt using @id;
EXECUTE  stmt using @id2;
```
Result
```
mysql> CREATE TABLE IF NOT EXISTS `t_user_test`  (
    ->     id   bigint UNSIGNED NOT NULL
    ->         PRIMARY KEY,
    ->     name varchar(64)     NOT NULL COMMENT 'name'
    -> )
    ->     COMMENT 'user-table'
    ->     COLLATE = utf8mb4_unicode_ci;
Query OK, 0 rows affected, 1 warning (0.08 sec)

mysql> INSERT INTO t_user_test (id, name) VALUES (1, 'jack');
Query OK, 1 row affected (0.07 sec)

mysql> INSERT INTO t_user_test (id, name) VALUES (2, 'rose');
Query OK, 1 row affected (0.07 sec)

mysql> PREPARE stmt from  'SELECT * FROM `t_user_test` WHERE `id` IN (?) ORDER BY `id` DESC';
Query OK, 0 rows affected (0.07 sec)

mysql> SET @id=1;
Query OK, 0 rows affected (0.08 sec)

mysql> SET @id2=2;
Query OK, 0 rows affected (0.07 sec)

mysql> EXECUTE  stmt using @id;
+----+------+
| id | name |
+----+------+
|  1 | jack |
+----+------+
1 row in set (0.08 sec)

mysql> EXECUTE  stmt using @id2;
+----+------+
| id | name |
+----+------+
|  1 | jack |
+----+------+
1 row in set (0.07 sec)
```
我期望查询到两条记录分别为jack和rose；
但是实际上返回的两条记录都是jack。
这个问题仅发生在查询语句 ORDER BY id时（其中id为主键列）
对此十分疑惑 希望给出解答

以下是TIDB版本信息
Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:39:26
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by ChenPeng2013** [comment]
@Ayugakki can you provide the complete reproduce step? ddl and dml statements

**Comment by Ayugakki** [comment]
> @Ayugakki can you provide the complete reproduce step? ddl and dml statements

I added the whole experiment process, hope to get your help

**Comment by Reminiscent** [comment]
The result in the latest master is correct. It has been fixed. But the issue need to further locate. @Ayugakki

**Comment by Reminiscent** [comment]
The result in the latest master is correct. So close the issue.
