### ISSUE TITLE
analyze use MaxUint64 ts to read data

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#35233]
## Enhancement

#24575 makes analyze read data on snapshot. Combined with incremental update of modify_count and count at the end of analyze, we can get a more accurate modify_count especially when lots of updates happen during the long time analyze. However, long-time snapshot analyze can throw error `GC life time is shorter than transaction duration`(#29862) or block GC(#35062). Considering analyze doesn't require strong data consistency, we hope to change back to use MaxUint64 ts to read data in analyze.

**Comment by xhebox** [comment]
But the original issue of #24575 has concerns on overestimation of modify_count, maybe add another `TiDBAnalyzeVersion`?

**Comment by xuyifangreeneyes** [comment]
> #24575

Yes. We switch back to read the latest data rather than certain snapshot because analyze does't require strong data consistency and analyze on snapshot may bring some problems(auto analyze blocks gc or long-time auto analyze fails) more severe than inaccurate `modify_count`. When we use MaxUint64 ts to read data in analyze, there are two ways to update `modify_count` when analyze is finished. The first way is to update it incrementally(see #24720), which causes overestimation of `modify_count`. The second way is to just set it 0, which is the original implementation and causes underestimation of `modify_count`. Underestimation makes auto analyze fail to trigger when it should be triggered and has more risk than overestimation on cardinality/cost estimation. Thus we choose to use MaxUint64 ts in analyze and update `modify_count` incrementally. https://pingcap.feishu.cn/docs/doccnv4DHuubn6bj9OzeEQRHFFd has more details.
