### ISSUE TITLE
mysql-test union.test run failed

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#35250]
https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_common_test/detail/tidb_ghpr_common_test/10080/pipeline

```
sql:( SELECT *, 'a' FROM t1 LIMIT 10 )
UNION ALL ( SELECT *, 'b' FROM t1 order by 1 LIMIT 10 ) LIMIT 3;: failed to run query
\"( SELECT *, 'a' FROM t1 LIMIT 10 )
UNION ALL ( SELECT *, 'b' FROM t1 order by 1 LIMIT 10 ) LIMIT 3;\"
 around line 2316,
we need(116):
( SELECT *, 'a' FROM t1 LIMIT 10 )
UNION ALL ( SELECT *, 'b' FROM t1 order by 1 LIMIT 10 ) LIMIT 3;
a	a
1	a
2	a
2	a

but got(116):
( SELECT *, 'a' FROM t1 LIMIT 10 )
UNION ALL ( SELECT *, 'b' FROM t1 order by 1 LIMIT 10 ) LIMIT 3;
a	a
1	b
2	b
2	b
```

**Comment by Reminiscent** [comment]
The result in latest master is right. Maybe some PRs have fixed this issue already. So we just close it. If the issue happen again, feel free to reopen it.

**Comment by zimulala** [comment]
Test failed again：https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_mysql_test/detail/tidb_test_ghpr_mysql_test/1497/pipeline
@Reminiscent

**Comment by zimulala** [comment]
Related PR： https://github.com/pingcap/tidb-test/pull/1782

**Comment by zimulala** [comment]
Encounter again： https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_mysql_test/detail/tidb_test_ghpr_mysql_test/1514/pipeline/
