### ISSUE TITLE
timeout -1 not truncated to the nearest value 1 when execute SELECT GET_LOCK('test', -1);

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#35253]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
in session 1: 
mysql> SELECT GET_LOCK('test', 1);
in session 2:
mysql> SELECT GET_LOCK('test', -1);

### 2. What did you expect to see? (Required)
get_lock return 0 in 1 sec
### 3. What did you see instead (Required)
get_lock has no response for several minutes
### 4. What is your TiDB version? (Required)

Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11

**Comment by morgo** [comment]
This behavior is [documented here](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html):

> [GET_LOCK(str,timeout)](https://dev.mysql.com/doc/refman/5.7/en/locking-functions.html#function_get-lock)
> 
> Tries to obtain a lock with a name given by the string str, using a timeout of timeout seconds. **A negative timeout value means infinite timeout.**

TiDB doesn't support infinite, so 3600s is used.

**Comment by seiya-annie** [comment]
ok, will write it in doc
