### ISSUE TITLE
no warning for get_lock() with timeout param=NULL

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#35252]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
mysql> SELECT GET_LOCK("test", NULL);
+------------------------+
| GET_LOCK("test", NULL) |
+------------------------+
|                      1 |
+------------------------+
1 row in set (0.00 sec)

MySQL> 

mysql> SELECT GET_LOCK("test", 'a');
+-----------------------+
| GET_LOCK("test", 'a') |
+-----------------------+
|                     1 |
+-----------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1292 | Truncated incorrect INTEGER value: 'a' |
+---------+------+----------------------------------------+
1 row in set (0.00 sec)

mysql> 
```

### 2. What did you expect to see? (Required)
report warning for truncate NULL
### 3. What did you see instead (Required)
no warning
### 4. What is your TiDB version? (Required)

| Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11

**Comment by seiya-annie** [comment]
and What value will 'Null' be truncated to?

**Comment by tangenta** [comment]
I don't think this is a bug. Here is the result of MySQL:
```sql
mysql> select get_lock("test", null);
+------------------------+
| get_lock("test", null) |
+------------------------+
|                      1 |
+------------------------+
1 row in set (0.01 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.27    |
+-----------+
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
I agree with @tangenta - this is something I investigated when developing this. See this code:

https://github.com/pingcap/tidb/blob/06737ecd29b0ae633d9ac89b0660e7a43939c88d/expression/builtin_miscellaneous.go#L208-L214
