### ISSUE TITLE
Error message of duplicate primary key is not shown properly

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#35289]
## Enhancement

Actual:
```sql
mysql> CREATE TABLE t1 (a BINARY(16) PRIMARY KEY);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
ERROR 1062 (23000): Duplicate entry '{ W]�u����.�٧t' for key 'PRIMARY'
```

Expected:
```sql
mysql> CREATE TABLE t1 (a BINARY(16) PRIMARY KEY);
Query OK, 0 rows affected (0.05 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
Query OK, 1 row affected (0.02 sec)

mysql> INSERT INTO t1 VALUES (AES_ENCRYPT('a','a'));
ERROR 1062 (23000): Duplicate entry '{ W]\xA1\x06u\x9D\xBD\xB1\xA3.\xE2\xD9\xA7t' for key 't1.PRIMARY'
```

**Comment by rahulk789** [comment]
hello! I would like this issue to be assigned to me. This would be my first ever contribution on github.
Please give me 2 days of time. Thank you.

**Comment by rahulk789** [comment]
**Quick Update**
i have come up with a simple solution which you might like or not, I will describe it in detail in the pr. I'll have to read a ton of stuff just to understand the norms of making a pr into a production grade repository. Glad to be a part of this.

**Comment by tangenta** [comment]
@rahulk789 In case you didn't know, the [TiDB development Guide](https://pingcap.github.io/tidb-dev-guide/index.html) may be helpful to new contributors.

**Comment by rahulk789** [comment]
I have no idea as to why the CI tests are failing.

**Comment by rahulk789** [comment]
okay, looks like i have to think harder. Thanks for the response in the PR.

**Comment by measutosh** [comment]
Hi @tangenta, I have made a contribution at PR [#38254](https://github.com/pingcap/tidb/pull/38254).

please have a look.

thanks.
