### ISSUE TITLE
support encoding user vars for session manager

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#35288]
The session manager needs to get all the states for the current session through `show session_states` and restore them on the other session through `set session_states ...`.
This includes user-defined variables.

**Comment by morgo** [comment]
MySQL has support for this in the protocol: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_session_track_state_change (currently not supported by TiDB).

There was just a bug report on this here: https://github.com/pingcap/tidb/issues/35309

**Comment by djshow832** [comment]
> MySQL has support for this in the protocol: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_session_track_state_change (currently not supported by TiDB).
> 
> There was just a bug report on this here: #35309

I knew it. I didn't apply this approach because:
- According to https://dev.mysql.com/doc/internals/en/packet-OK_Packet.html#cs-sect-packet-ok-sessioninfo, there are only 4 predefined state types, and the type is encoded in an `int<1>`. However, TiDB has tens of state types, some of which are TiDB-specific. I'm afraid I cannot extend the state types because it will break forward compatibility if MySQL adds more state types in the future.
- Compared with maintaining every state anytime it changes, it takes less workload for developers to fetch the states at once with one `show session_states` statement, and it has a lower risk of bugs.
