### ISSUE TITLE
tidb-server log repeats "context deadline exceeded"

### ISSUE THREAD

**Issue by Li-Tao** [pingcap/tidb#3529]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I'm using TPCCRunner to load data into the tables by the following command:

java -cp bin/:lib/mysql-connector-java-5.1.7-bin.jar iomark.TPCCRunner.Loader conf/example/mysql/loader.properties

2. What did you expect to see?

what does the messsage in tidb-server log mean? will it impact the insert performance? if yes, how to tune it?

3. What did you see instead?

The load data process seems stuck after "end insert item". The following is the screen output:

Truncating 'item' ...
Truncating 'warehouse' ...
Truncating 'stock' ...
Truncating 'district' ...
Truncating 'customer' ...
Truncating 'history' ...
Truncating 'oorder' ...
Truncating 'order_line' ...
Truncating 'new_order' ...
------------- LoadData Start Date = Thu Jun 22 15:36:35 CST 2017-------------
2017-06-22 15:36:37.458 - thread 0  end insert warehouse_1_250
2017-06-22 15:36:50.67  - thread 3  end insert warehouse_751_1000
2017-06-22 15:36:51.035 - thread 1  end insert warehouse_251_500
2017-06-22 15:36:51.669 - thread 2  end insert warehouse_501_750
2017-06-22 15:37:06.965 - thread 0  end insert district_1_250
2017-06-22 15:37:30.779 - thread 3  end insert district_751_1000
 2017-06-22 15:37:33.083 - thread 1  end insert district_251_500
2017-06-22 15:37:53.065 - thread 2  end insert district_501_750
      2017-06-22 15:44:21.256 - thread 0  end insert item_1_25000
2017-06-22 15:44:25.646 - thread 3  end insert item_75001_100000
 2017-06-22 15:44:58.87  - thread 1  end insert item_25001_50000
 2017-06-22 15:45:55.183 - thread 2  end insert item_50001_75000
<do not print anything for a long time>

tidb-server log repeats the following message:

2017/06/22 17:00:55 region_cache.go:419: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/06/22 17:00:55 region_cache.go:419: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/06/22 17:00:55 region_cache.go:419: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/06/22 17:00:55 region_cache.go:419: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/06/22 17:00:55 region_cache.go:419: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded
2017/06/22 17:00:55 region_cache.go:419: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = DeadlineExceeded desc = context deadline exceeded

4. What version of TiDB are you using (`tidb-server -V`)?

Git Commit Hash: 2dd93852ad8b3d1e4fd8f3dba8c13d3a6d22a98b
UTC Build Time:  2017-06-14 12:58:13

**Comment by tiancaiamao** [comment]
Make sure pd and tikv is alive, and observe whether this log repeat infinitely or just for a while. @Li-Tao

**Comment by Li-Tao** [comment]
@tiancaiamao pd and tikv is alive. this log repeats for a long time. good news is the row count of the table being inserted moves on. i'm just wondering if this message indicates a performance issue.

**Comment by Li-Tao** [comment]
@tiancaiamao the insert speed seems not good.

mysql> select now();select count(*) from stock;
+---------------------+
| now()               |
+---------------------+
| 2017-06-22 17:29:17 |
+---------------------+
1 row in set (0.00 sec)

+----------+
| count(*) |
+----------+
|   712000 |
+----------+
1 row in set (33.50 sec)

mysql> select now();select count(*) from stock;
+---------------------+
| now()               |
+---------------------+
| 2017-06-22 17:29:56 |
+---------------------+
1 row in set (0.00 sec)

+----------+
| count(*) |
+----------+
|   718000 |
+----------+
1 row in set (46.62 sec)

the following is table definition:

mysql>   desc stock;
+--------------+--------------+------+------+---------+-------+
| Field        | Type         | Null | Key  | Default | Extra |
+--------------+--------------+------+------+---------+-------+
| s_w_id       | int(11)      | NO   |      | NULL    |       |
| s_i_id       | int(11)      | NO   |      | NULL    |       |
| s_quantity   | decimal(4,0) | YES  |      | NULL    |       |
| s_ytd        | decimal(8,2) | YES  |      | NULL    |       |
| s_order_cnt  | int(11)      | YES  |      | NULL    |       |
| s_remote_cnt | int(11)      | YES  |      | NULL    |       |
| s_data       | varchar(50)  | YES  |      | NULL    |       |
| s_dist_01    | char(24)     | YES  |      | NULL    |       |
| s_dist_02    | char(24)     | YES  |      | NULL    |       |
| s_dist_03    | char(24)     | YES  |      | NULL    |       |
| s_dist_04    | char(24)     | YES  |      | NULL    |       |
| s_dist_05    | char(24)     | YES  |      | NULL    |       |
| s_dist_06    | char(24)     | YES  |      | NULL    |       |
| s_dist_07    | char(24)     | YES  |      | NULL    |       |
| s_dist_08    | char(24)     | YES  |      | NULL    |       |
| s_dist_09    | char(24)     | YES  |      | NULL    |       |
| s_dist_10    | char(24)     | YES  |      | NULL    |       |
+--------------+--------------+------+------+---------+-------+
17 rows in set (0.00 sec)

**Comment by Li-Tao** [comment]
which place should be tuned?

**Comment by dbjoa** [comment]
@Li-Tao, 
Would you check the value of "sync-log" in "[raftstore]" section of the TiKV configuration file?

**Comment by tiancaiamao** [comment]
As you know, TiDB/TiKV is a distributed database, the data is shard by key range into regions.
When one region is big enough, it would split into two regions.

TiKV reports the region info to PD, TiDB gets them from PD and caches them.

If region splits and the cached region info is out of date, TiDB will drop the cache and display 
those logs, this is the normal case.

If TiDB fails to communicate with TiKV, it drops the cache and display those logs too, that's why
I tell you to check TiKV/PD is alive.
@Li-Tao

**Comment by Li-Tao** [comment]
@dbjoa I set it to sync-log = false.

**Comment by Li-Tao** [comment]
@tiancaiamao your explanation is what I seek. thank you.

**Comment by Li-Tao** [comment]
@c4pt0r yes, you can close it.
