### ISSUE TITLE
How to download package about golang.org/x/

### ISSUE THREAD

**Issue by shangfy** [pingcap/tidb#353]
How to deal with the following questions:
When I download github.com/pingcap/tidb, I always can't get package about golang.org？
$ go get -d github.com/pingcap/tidb
package golang.org/x/text/encoding: unrecognized import path "golang.org/x/text/encoding"
package golang.org/x/text/encoding/charmap: unrecognized import path "golang.org/x/text/encoding/charmap"
package golang.org/x/text/encoding/japanese: unrecognized import path "golang.org/x/text/encoding/japanese"
package golang.org/x/text/encoding/korean: unrecognized import path "golang.org/x/text/encoding/korean"
package golang.org/x/text/encoding/simplifiedchinese: unrecognized import path "golang.org/x/text/encoding/simplifiedchinese"
package golang.org/x/text/encoding/traditionalchinese: unrecognized import path "golang.org/x/text/encoding/traditionalchinese"
package golang.org/x/text/encoding/unicode: unrecognized import path "golang.org/x/text/encoding/unicode"
package golang.org/x/text/transform: unrecognized import path "golang.org/x/text/transform"

**Comment by qiuyesuifeng** [comment]
@shangfy 
Thanks for your report.

u can try as follows:
```
git clone https://github.com/pingcap/tidb.git $GOPATH/src/github.com/pingcap/tidb
cd $GOPATH/src/github.com/pingcap/tidb
make (if u meet an error for `go get github.com/golang/lint/golint`, u can ignore it.)
```

**Comment by hcconquer** [comment]
why not make independent path ?
