### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference (Maybe not a bug)

### ISSUE THREAD

**Issue by fuboat** [pingcap/tidb#35310]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
SET sql_mode="";
GRANT ALL PRIVILEGES ON *.* to '???';
```

### 2. What did you expect to see? (Required)

```
Query OK, 0 rows affected (0.00 sec)
ERROR 1410 (42000): You are not allowed to create a user with GRANT
```

### 3. What did you see instead (Required)

```
Query OK, 0 rows affected (0.00 sec)
ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference
```

### 4. What is your TiDB version? (Required)

```
Release Version: v6.2.0-alpha-97-g06737ecd2
Edition: Community
Git Commit Hash: 06737ecd29b0ae633d9ac89b0660e7a43939c88d
Git Branch: master
UTC Build Time: 2022-06-11 07:47:16
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore
```

**Comment by morgo** [comment]
The relevant sql-mode is `NO_AUTO_CREATE_USER`. It's completely removed from MySQL 8.0, but in 5.7 can still apply. So the user '???' is expected to be created with no password (obviously not a good idea, but that's the legacy mysql behavior.)

**Comment by djshow832** [comment]
Anyway, TiDB should never report `runtime error`, so it's still a bug.
