### ISSUE TITLE
the process for init_connect = -1 is incompatible with mysql

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#35324]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

in tidb v6.1.0
```sql
mysql> SET global init_connect = -1;
Query OK, 0 rows affected (0.01 sec)

mysql> show global variables like 'init_connect';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| init_connect  | -1    |
+---------------+-------+
1 row in set (0.00 sec)
```

in MySQL 8.0.29 
mysql> SET global init_connect = -1;
ERROR 1232 (42000): Incorrect argument type to variable 'init_connect'

### 2. What did you expect to see? (Required)
compatible with MySQL 

### 3. What did you see instead (Required)
tidb don't report error for invalid value type

### 4. What is your TiDB version? (Required)

Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11

**Comment by Defined2014** [comment]
We will transfer datum to str before validation [ref link](https://github.com/pingcap/tidb/blob/master/executor/set.go#L127). So we need to pass `datum` param for SetGlobalSysVar instead of `string` to fix this issue.

**Comment by likzn** [comment]
`SysVar` has `TypeFlag` with each system environment. And we also can get input type with `v.Expr.Eval(chunk.Row{})` in `Datum`. What about adding a check with type limit to resolve this issue.
https://github.com/pingcap/tidb/blob/9a77892ac8e513eba25813963de808310295d1ec/executor/set.go#L299-L314
