### ISSUE TITLE
miss record when where condition use right %

### ISSUE THREAD

**Issue by zwathz** [pingcap/tidb#35366]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
-- table info 
CREATE TABLE `cp_info` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(32) COLLATE utf8_general_ci DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */,
  KEY `idx_name` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1374818

MySQL [cp_center]> explain select * from cp_center.cp_info where name like '秦文政%';
+-------------+---------+------+---------------+---------------+
| id          | estRows | task | access object | operator info |
+-------------+---------+------+---------------+---------------+
| TableDual_5 | 0.00    | root |               | rows:0        |
+-------------+---------+------+---------------+---------------+
1 row in set (0.00 sec)

-- after drop name index
MySQL [cp_center]> select id, name from cp_center.cp_info where name like '秦文政%'\G
*************************** 1. row ***************************
                   id: 1310871
                 name: 秦文政

### 2. What did you expect to see? (Required)
MySQL [cp_center]> select id, name from cp_center.cp_info where name = '秦文政'\G
*************************** 1. row ***************************
                   id: 1310871
                 name: 秦文政

### 3. What did you see instead (Required)
MySQL [cp_center]> select id, name from cp_center.cp_info where name like  '秦文政%'\G
Empty set (0.00 sec)

### 4. What is your TiDB version? (Required)
Release Version: v5.4.1
Edition: Community
Git Commit Hash: be484475e76b3aaa2cad520111353c3327db35fa
Git Branch: heads/refs/tags/v5.4.1
UTC Build Time: 2022-05-07 04:31:32
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by Haaahei** [comment]
*_general_ci collate cause the problem

**Comment by aioas** [comment]
We have the same problem. Is there any plan to fix it?

**Comment by wjhuang2016** [comment]
The same as https://github.com/pingcap/tidb/issues/31174 , fixed by https://github.com/pingcap/tidb/pull/31278, version: 6.0.0
