### ISSUE TITLE
unexpected unresolved column error when the view refers to dual table

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#35527]
### 1. Minimal reproduce step (Required)
```sql
CREATE VIEW v0(c0) AS SELECT NULL;
SELECT v0.c0 FROM v0 WHERE (v0.c0 IS NULL) LIKE(NULL); -- ERROR 1105 (HY000) at line 2: Can't find column Column#1 in schema Column: [] Unique key: []
```
### 2. What did you expect to see? (Required)
No error information.

### 3. What did you see instead (Required)
ERROR 1105 (HY000) at line 2: Can't find column Column#1 in schema Column: [] Unique key: []

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-143-gcd731af05
Edition: Community
Git Commit Hash: cd731af05a5446bb8dcba83f0e163176c75f5cea
Git Branch: master
UTC Build Time: 2022-06-20 07:36:55
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore |

**Comment by bajinsheng** [comment]
The test case has no error in MySQL 8.0.

**Comment by tangenta** [comment]
@bajinsheng Thanks for your reporting. 

BTW, how did you find this issue? We would like to see if we can enhance our automated tests.

**Comment by bajinsheng** [comment]
Thanks for your reply! 
I'm a PhD student in the NUS Test Lab (see https://nus-test.github.io/) and found this and other bugs based on a new technique we are developing to improve SQLancer and other SQL fuzzers. 
We are glad to share our technique when it is done.
