### ISSUE TITLE
Fatal in sysbench oltp_update_index.

### ISSUE THREAD

**Issue by SpadeA-Tang** [pingcap/tidb#35525]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

sysbench oltp_common \
--threads=32 \
--rand-type=uniform \
--db-driver=mysql \
--mysql-db=sbtest \
--mysql-host=xxx \
--mysql-port=xxx \
--mysql-user=root \
--mysql-password="" \
prepare --tables=1 --table-size=10000

sysbench oltp_update_index \
--threads=30 \
--time=1200 \
--report-interval=3 \
--rand-type=uniform \
--db-driver=mysql \
--mysql-db=sbtest \
--mysql-host=xxx \
--mysql-port=xxx \
--mysql-user=root \
--mysql-password="" \
run --tables=1 --table-size=10000

### 2. What did you expect to see? (Required)
no error

### 3. What did you see instead (Required)
![zcup2D0E2K](https://user-images.githubusercontent.com/71589810/174567921-0c9637a6-2600-4bfb-a802-f1eeae94b302.png)

### 4. What is your TiDB version? (Required)
06737ecd29b0ae633d9ac89b0660e7a43939c88d

**Comment by cfzjywxk** [comment]
@ti-chi-bot 
Please do not add affected flags automatically...

**Comment by vivid392845427** [comment]
this problem also occurs in the release test of 5.4.2
errors mismatch: Error 1105: tikv aborts txn: Error(Txn(Error(Mvcc(Error(PessimisticLockNotFound { start_ts: TimeStamp(434197815277387782), key: [116, 128, 0, 0, 0, 0, 0, 54, 246, 95, 114, 128, 0, 0, 0, 0, 0, 0, 9] }))))) <> <nil> @(1656333213.975b95f6-023e-458b-a6dd-d440473f4572:37) "commit;"

http://rms.pingcap.net:31714/workflows/testground/plan-exec-850450?tab=workflow&nodeId=plan-exec-850450-3548398545

run sysbench oltp_update_index also occurs this proplem
 tikv log:
[2022/06/30 08:45:13.660 +00:00] [WARN] [prewrite.rs:359] ["conflicting write was found, pessimistic lock must be lost for the corresponding row key"] ["conflicting commit_ts"=434262169497108503] ["conflicting start_ts"=434262169497108503] [for_update_ts=434262169497108485] [start_ts=434262169497108485] [key=7480000000000017FFC05F698000000000FF0000010380000000FF0000024303800000FF00000010E6000000FC]
[2022/06/30 08:45:13.660 +00:00] [ERROR] [errors.rs:408] ["txn aborts"] [err_code=KV:Storage:PessimisticLockNotFound] [err="Error(Txn(Error(Mvcc(Error(PessimisticLockNotFound { start_ts: TimeStamp(434262169497108485), key: [116, 128, 0, 0, 0, 0, 0, 23, 192, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 3, 128, 0, 0, 0, 0, 0, 2, 67, 3, 128, 0, 0, 0, 0, 0, 16, 230] })))))"]

**Comment by ekexium** [comment]
It's caused by a rollback record on non-unique index keys whose ts is greater than the for_update_ts of the pessimistic transaction throwing the error.

The sequence of events can be like:
1. Pessimistic txn-A locks row key using for_update_ts = 1.
2. Optimistic txn-B with start_ts = 2 prewrites the index key.
3. txn-A finds the locks on index keys and rolls back txn-B, leaving rollback records of ts=2 on index keys.
4. txn-A prewrite index keys, and find a write conflict.

The problem exists since long ago but is easier to be detected recently because https://github.com/tikv/client-go/pull/513 makes it easier to check write conflicts on non-unique keys in pessimistic transactions.

**Comment by cfzjywxk** [comment]
@ekexium 
Have we changed the reported error information already?

**Comment by ekexium** [comment]
> @ekexium Have we changed the reported error information already?

Not yet.

**Comment by ekexium** [comment]
I think it has been fixed
