### ISSUE TITLE
run sql :select LOWER('TiDB'); bug:result is t,not tidb

### ISSUE THREAD

**Issue by zwljava** [pingcap/tidb#3560]
tidb ver:
    Git Commit Hash: 3ab3a61b5a0426aff04b0c3e71e8874b8acf70e8
    UTC Build Time:  2017-06-28 09:38:24
os: 
    centos 6.x

**Comment by zz-jason** [comment]
hi @zwljava, which version of TiDB are you using?

**Comment by zwljava** [comment]
tidb ver:
Git Commit Hash: 3ab3a61
UTC Build Time: 2017-06-28 09:38:24
os:
centos 6.x
@zz-jason

**Comment by zwljava** [comment]
tidb-latest-linux-amd64-centos6.tar.gz  @zz-jason

**Comment by shenli** [comment]
@zwljava Which client do you use to access TiDB? Do you use navicat?

**Comment by zwljava** [comment]
@zz-jason yes, navicat

**Comment by XuHuaiyu** [comment]
@zwljava the version of your Navicat?
And which OS do you use?

**Comment by zwljava** [comment]
@zz-jason 
Navicat 9.0.10 enterprise 
os: win xp pack 3

**Comment by zwljava** [comment]
@zz-jason  HeidiSQL_9.4.0.5125  is OK!

**Comment by zwljava** [comment]
@zz-jason  Navicat 9.0.10 have bug!

**Comment by XuHuaiyu** [comment]
There do exist some incomplete problems in type inferring process of TiDB,
on which may some versions of Navicat are relied.

We are working on this. @zwljava

**Comment by morgo** [comment]
I believe this has now been fixed in TiDB.  Confirming that the type TiDB returns is similar to MySQL 8.0 (where the default charset changes).  There is still a difference in collation, but both are correct.

```
tidb> select LOWER('TiDB');
Field   1:  `LOWER('TiDB')`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_general_ci (45)
Length:     16
Max_length: 4
Decimals:   31
Flags:      

+---------------+
| LOWER('TiDB') |
+---------------+
| tidb          |
+---------------+
1 row in set (0.00 sec)


mysql 8.0.13> select LOWER('TiDB');
Field   1:  `LOWER('TiDB')`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8_general_ci (33)
Length:     12
Max_length: 4
Decimals:   31
Flags:      

+---------------+
| LOWER('TiDB') |
+---------------+
| tidb          |
+---------------+
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to re-open if you have any further questions.  Thanks!
