### ISSUE TITLE
Parser accepts multiple ALTER PARTITION options

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#35621]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t (a int) partition by range (a) (partition p0 values less than (10));
alter table t add partition (partition p1 values less than (20)), add partition (partition p2 values less than (30));
```

This should be a syntax error (only one alter partition command is allowed in the MySQL parser).

### 2. What did you expect to see? (Required)
```
mysql> create table t (a int) partition by range (a) (partition p0 values less than (10));
Query OK, 0 rows affected (0,03 sec)

mysql> alter table t add partition (partition p1 values less than (20)), add partition (partition p2 values less than (30));
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ', add partition (partition p2 values less than (30))' at line 1
```

### 3. What did you see instead (Required)
```
tidb> create table t (a int) partition by range (a) (partition p1 values less than (10));
Query OK, 0 rows affected (0,01 sec)

tidb> alter table t add partition (partition p2 values less than (20)), add partition (partition p3 values less than (30));
ERROR 8200 (HY000): Unsupported multi schema change
```

### 4. What is your TiDB version? (Required)

```
Release Version: v6.2.0-alpha-156-g5c9ad77ae1
Edition: Community
Git Commit Hash: 5c9ad77ae1f172b4474664d7f83c5661b1ad2939
Git Branch: master
UTC Build Time: 2022-06-21 09:56:57
GoVersion: go1.18
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore
```

**Comment by mjonss** [comment]
MySQL Manual is not inline with MySQL implementation:
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html where `partition_options` are listed as one or more `partition_option`, while their [parser only allow it once](https://github.com/mysql/mysql-server/blob/8d8c986e5716e38cb776b627a8eee9e92241b4ce/sql/sql_yacc.yy#L8758).

**Comment by bb7133** [comment]
> MySQL Manual is not inline with MySQL implementation:
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html where partition_options are listed as one or more partition_option, while their [parser only allow it once](https://github.com/mysql/mysql-server/blob/8d8c986e5716e38cb776b627a8eee9e92241b4ce/sql/sql_yacc.yy#L8758).

Thanks @mjonss , I think we could mark this issue as 'won't fix' since it looks like a bug in MySQL parser. Also, TiDB report an error, TiDB just have a different error message which gives no much difference for the end-users.

**Comment by mjonss** [comment]
@bb7133 Sorry I think this should be reopened, one should not be able to have multiple partition_options in a single ALTER TABLE. The MySQL manual is wrong, but the implementation is correct in my view. Which means we should at least not allow it when multi-schema changes are supported.

However I am OK with having it as a wontfix, due to it will currently give an error, just not a parsing error.
