### ISSUE TITLE
Unexpected Result with a FALSE Expression in WHERE

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#35645]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0 (c0 NUMERIC);
CREATE INDEX i0 ON t0(c0);
INSERT INTO t0(c0) VALUES (NULL);

SELECT t0.c0 FROM t0 WHERE NOT (true AND t0.c0 <=> NULL); -- NULL
```
### 2. What did you expect to see? (Required)
Empty result.
As a reference, the expression in the WHERE is evaluated FALSE:
```sql
SELECT NOT (true AND t0.c0 <=> NULL) FROM t0; -- 0
```

### 3. What did you see instead (Required)
NULL.

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-159-ge0527ba27
Edition: Community
Git Commit Hash: e0527ba27c72b0a533b126fedfa025d47a209ca9
Git Branch: master
UTC Build Time: 2022-06-21 11:55:54
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore |

**Comment by hawkingrei** [comment]
I found it fixed in release-6.4
