### ISSUE TITLE
Unexpected Error by CAST and CHAR functions

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#35652]
### 1. Minimal reproduce step (Required)
```sql
SELECT CAST(CHAR(21474647) AS CHAR); --Cannot convert string 'G\xADW' from binary to utf8
```
### 2. What did you expect to see? (Required)
No error
As a reference, there is no error for MySQL: https://www.db-fiddle.com/f/gtq3wBBEJezuCxHy1cgWtL/0

### 3. What did you see instead (Required)
Cannot convert string 'G\xADW' from binary to utf8

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-159-ge0527ba27
Edition: Community
Git Commit Hash: e0527ba27c72b0a533b126fedfa025d47a209ca9
Git Branch: master
UTC Build Time: 2022-06-21 11:55:54
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore |

**Comment by xiongjiwei** [comment]
it is a MySQL bug, see https://bugs.mysql.com/bug.php?id=107645

**Comment by xiongjiwei** [comment]
close due to not bug
