### ISSUE TITLE
Expired pd address is used  when update region-label/rules

### ISSUE THREAD

**Issue by King-Dylan** [pingcap/tidb#35653]
## Bug Report
The drop database operation may fail after updated all pd addresses because the pd addresses in the region-rule (PDLabelManager.addrs ) were not updated in time.
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1.create new cluster
2.scale-out new pd member
3.scale-in all old pd member
4.drop database
### 3. What did you see instead (Required)
MySQL > drop database test1;
ERROR 1105 (HY000): Patch "http://xxx.xxx.xxx:2879/pd/api/v1/config/region-label/rules": dial tcp xxx.xxx.xxx.xxx:2879: connect: connection refused
### 4. What is your TiDB version? (Required)
v5.4

**Comment by seiya-annie** [comment]
duplicated with https://github.com/pingcap/tidb/issues/33908
