### ISSUE TITLE
Unexpected Connection Lost

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#35678]
### 1. Minimal reproduce step (Required)
```sql
SELECT CAST(REVERSE(-1502572527) AS DATE); -- ERROR 2013 (HY000): Lost connection to MySQL server during query
```
### 2. What did you expect to see? (Required)
No error.
### 3. What did you see instead (Required)
ERROR 2013 (HY000): Lost connection to MySQL server during query
### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-159-ge0527ba27
Edition: Community
Git Commit Hash: e0527ba27c72b0a533b126fedfa025d47a209ca9
Git Branch: master
UTC Build Time: 2022-06-21 11:55:54
GoVersion: go1.18.3
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
Store: unistore |

**Comment by seiya-annie** [comment]
i tried in mysql8.3 , no error reported.
```mysql> SELECT (NOT ('s' OR CAST(REVERSE(-1502572527) AS DATE)));
+---------------------------------------------------+
| (NOT ('s' OR CAST(REVERSE(-1502572527) AS DATE))) |
+---------------------------------------------------+
|                                              NULL |
+---------------------------------------------------+
1 row in set, 2 warnings (0.03 sec)

```

**Comment by seiya-annie** [comment]
and checked in log, seems this statement is not sent to tidb server. no log found for this.

**Comment by bb7133** [comment]
There are two issues for this bug, the minimal reproduction SQL is:

```
tidb> SELECT CAST("1111111111-" AS DATE);
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

1: It is about the details of `CAST` implementation from strings to datetime, when `1111111111-` is parsed, splited, the code goes to: 

https://github.com/pingcap/tidb/blob/5c9ad77ae1f172b4474664d7f83c5661b1ad2939/types/time.go/#L1067-L1070

Finally and I can see that an `EOF` error is returned by `fmt.Sscanf`.

2: The `EOF` error is not handled correctly, so there's no log or error returned to the client.
