### ISSUE TITLE
Syntax error: drop index idx on tableName;

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#357]
```
CREATE TABLE `emails` (`id` int ,`email` varchar(100));
CREATE INDEX idx_email_email ON `emails`(`email`);
DROP INDEX idx_email_email ON `emails`;
```
session.go:234: [error] Syntax error: DROP INDEX idx_email_email ON `emails`;
session.go:235: [error] Error occurs at line 1 column 28 near "ON".

**Comment by qiuyesuifeng** [comment]
@zimulala  
Seems this issue has been fixed?

**Comment by ngaut** [comment]
Ping @zimulala
