### ISSUE TITLE
When PD node down, can not query TIKV_REGION_STATUS

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#35708]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1.  use TiUP create a v5.4.0 tidb cluster (PD must not on same host)
2. tiup cluster stop one PD node 
3. select * from TIKV_REGION_STATUS  meet error 

### 2. What did you expect to see? (Required)
select * from TIKV_REGION_STATUS  should normal.
### 3. What did you see instead (Required)
ERROR 1105 (HY000): Get "http://172.xx.xx.162:18279/pd/api/v1/regions": dial tcp 172.xx.xx.162:18279: connect: connection refused

tidb.log erro stack:
`[2022/06/24 10:27:47.896 +08:00] [INFO] [conn.go:1115] ["command dispatched failed"] [conn=7] [connInfo="id:7, addr:172.xxx.xx.136:55676 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="select * from TIKV_REGION_STATUS"] [txn_mode=PESSIMISTIC] [err="Get \"http://172.xxx.xx.162:18279/pd/api/v1/regions\": dial tcp 172.xxx.xx.162:18279: connect: connection refused\ngithub.com/pingcap/errors.AddStack\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/nfs/cache/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tidb/store/helper.(*Helper).requestPD\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/helper/helper.go:813\ngithub.com/pingcap/tidb/store/helper.(*Helper).GetRegionsInfo\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/helper/helper.go:771\ngithub.com/pingcap/tidb/executor.(*memtableRetriever).setDataForTiKVRegionStatus\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:1449\ngithub.com/pingcap/tidb/executor.(*memtableRetriever).retrieve\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/infoschema_reader.go:141\ngithub.com/pingcap/tidb/executor.(*MemTableReaderExec).Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/memtable_reader.go:118\ngithub.com/pingcap/tidb/executor.Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:286\ngithub.com/pingcap/tidb/executor.(*recordSet).Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:149\ngithub.com/pingcap/tidb/server.(*tidbResultSet).Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:312\ngithub.com/pingcap/tidb/server.(*clientConn).writeChunks\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2165\ngithub.com/pingcap/tidb/server.(*clientConn).writeResultset\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2116\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1994\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1841\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1336\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1091\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:548\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"]`

### 4. What is your TiDB version? (Required)
v5.4.0

**Comment by tangenta** [comment]
@yilongrong Why do you think this is a bug? The implementation shows that PD is required to access `tikv_region_status`.

**Comment by yilongrong** [comment]
The TiDB cluster has 3 PD nodes. When a PD node is stopped, pd functions still normally
I think select * from TIKV_REGION_STATUS should be displayed normally.
The stopped PD node should be ignored.

**Comment by tangenta** [comment]
@yilongrong OK I get it. This issue is confirmed to be duplicated with https://github.com/pingcap/tidb/issues/26303. It has been fixed in v5.2 and later versions.

**Comment by tangenta** [comment]
This issue should be tracked in https://github.com/pingcap/tidb/issues/35319.
