### ISSUE TITLE
MergeCI coprocessor test not stable

### ISSUE THREAD

**Issue by zanmato1984** [pingcap/tidb#35714]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_integration-copr-test/detail/tikv_ghpr_integration-copr-test/2179/pipeline

### 4. What is your TiDB version? (Required)

5.3.2

**Comment by yibin87** [comment]
Previouly, copr test repo doesn't maintain different release version branches as TiDB/TiKV/PD does. However, one of its internal config file, functions.txt do changes on different release versions: in TiDB 6.0 releases, it adds "Mod" function.
So when use TiDB/TiKV/PD earlier than 6.0, with latest copr test master branch, TiDB will push down "Mod" function to TiKV, but TiKV wouldn't support, and failed the test.
Now, we add responding release branches for copr test, and fix the issue now.

**Comment by zanmato1984** [comment]
Closing.
