### ISSUE TITLE
Can't find column when update with CTE

### ISSUE THREAD

**Issue by chrysan** [pingcap/tidb#35758]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
create table t1 (a int, b int);
create table t2 (c int, d int);
create table t3 (e int, f int);
explain update t1
inner join (
	select t2.c from t2
	inner join
		(with temp as (select e from t3 where t3.f = 1234)
		select e from temp) tt
	on 
		t2.d = tt.e
	) t
on t1.a = t.c
set
t1.b = 4321;
```

### 2. What did you expect to see? (Required)
Workable plan

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Can't find column test.t2._tidb_rowid in schema Column: [test.t1.a,test.t1.b,test.t1._tidb_rowid,test.t2.c] Unique key: []
```

### 4. What is your TiDB version? (Required)

v5.3.0 ~ master

**Comment by elsa0520** [comment]
If the CTE is inline in the update or delete statement, this problem will still be triggered.
```
update t1 inner join (select t2.c from t2 inner join (with temp as (select /*+ merge() */ e from t3 where t3.f = 1234) select e from temp) tt on t2.d = tt.e) t on t1.a = t.c set t1.b = 4321; 
Error 1105: Can't find column test.t2._tidb_rowid in schema Column: [test.t1.a,test.t1.b,test.t1._tidb_rowid,test.t2.c]
```

Please reopen this issue

**Comment by chrysan** [comment]
> If the CTE is inline in the update or delete statement, this problem will still be triggered.
> 
> ```
> update t1 inner join (select t2.c from t2 inner join (with temp as (select /*+ merge() */ e from t3 where t3.f = 1234) select e from temp) tt on t2.d = tt.e) t on t1.a = t.c set t1.b = 4321; 
> Error 1105: Can't find column test.t2._tidb_rowid in schema Column: [test.t1.a,test.t1.b,test.t1._tidb_rowid,test.t2.c]
> ```
> 
> Please reopen this issue

@elsa0520 you can create a new one.
