### ISSUE TITLE
Support add column with parentheses

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#3575]
Please answer these questions before submitting your issue. Thanks!

1. What did you expect to see?
```
mysql> create table t(a int);
Query OK, 0 rows affected (0.03 sec)

mysql> alter table t add column (x int);
Query OK, 0 rows affected (0.05 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

2. What did you see instead?
```
mysql> create table t(a int);
Query OK, 0 rows affected (0.01 sec)

mysql>  alter table t add column (x int);
ERROR 1105 (HY000): line 0 column 26 near "x int)" (total length 32)
```

**Comment by zimulala** [comment]
@dreamquster TiDB doesn't support add multiple columns in one statement now. You can refer to [docs](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md) or [docs-cn](https://github.com/pingcap/docs-cn/blob/master/op-guide/mysql-compatibility.md)

**Comment by holys** [comment]
Please fix the issue   /cc @shenli

**Comment by shenli** [comment]
OK!

**Comment by holys** [comment]
@zimulala  @shenli  It still not support for `alter table t add column (x int, x1 int)`

**Comment by zimulala** [comment]
Related #3566
