### ISSUE TITLE
go generics type parameters name use uppercase

### ISSUE THREAD

**Issue by feitian124** [pingcap/tidb#35804]
## Enhancement

related #34586, #34197

i come here to see if tidb used some go 1.18 features and found a few generics related, IMO type parameters name should be short and in uppercase to make it clear that it is a type parameter.

if you agree with me, i can submit a pr. for example,

```go
// now
func Max[v constraints.Ordered](x v, xs ...v)

// after
func Max[T constraints.Ordered](x T, xs ...T)
```

**Comment by feitian124** [comment]
@hawkingrei

**Comment by feitian124** [comment]
and also i am interested in if it is possible to use [workspaces](https://go.dev/blog/get-familiar-with-workspaces) to resolve sub module issue of `parser` package.

why `parser/go.mod` still use go 1.13 ?

**Comment by hawkingrei** [comment]
> and also i am interested in if it is possible to use [workspaces](https://go.dev/blog/get-familiar-with-workspaces) to resolve sub module issue of `parser` package.
> 
> why `parser/go.mod` still use go 1.13 ?

Community users will use it to develop. We must maintain compatibility.
