### ISSUE TITLE
Unit test case 'session TestNonTransactionalDeleteShardingOnVarchar' can't run on real TiKV

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#35837]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I'm [testing paging protocol](https://github.com/pingcap/tidb/issues/35633) by running tidb UT with a real TiKV using this branch https://github.com/pingcap/tidb/pull/35647

```
tiup playground nightly --mode tikv-slim
cd session
go test -run ^TestNonTransactionalDeleteShardingOnVarchar$ -with-tikv 127.0.0.1:2379
```

### 2. What did you expect to see? (Required)

Success

### 3. What did you see instead (Required)

The test hang...
The test case `TestNonTransactionalDeleteShardingOnInt` also have the same problem.

### 4. What is your TiDB version? (Required)

master 

```
commit 47a4f3a017768dda0b9a826451486c5539bc8427 (HEAD -> master, origin/master, origin/HEAD)
Author: Weizhen Wang <wangweizhen@pingcap.com>
Date:   Wed Jun 29 20:16:40 2022 +0800

    *: enable unconvert (#35821)
    
    ref pingcap/tidb#35345
```

**Comment by ekexium** [comment]
I failed to reproduce the problem, though it take 300s to finish the test.

**Comment by tiancaiamao** [comment]
You're right, it's just slow with real tikv, not hang... @ekexium 

```
go test -run ^TestNonTransactionalDeleteShardingOnVarchar$  -with-tikv 127.0.0.1:2379
ok  	github.com/pingcap/tidb/session	372.274s
```

```
go test -run ^TestNonTransactionalDeleteShardingOnVarchar$ 
ok  	github.com/pingcap/tidb/session	2.961s
```
