### ISSUE TITLE
dbForge Can't connect to TiDB

### ISSUE THREAD

**Issue by fadyxu** [pingcap/tidb#35894]
![image](https://user-images.githubusercontent.com/41108848/177004218-3f4419f9-9ab1-4c7c-be60-14ecfa1d025a.png)

error : Table 'performance_schema.session_variables' doesn't exist

**Comment by hawkingrei** [comment]
Which version of tidb do you have ?

**Comment by fadyxu** [comment]
> Which version of tidb do you have ?

5.4

**Comment by Defined2014** [comment]
The `seesion_vaiables` table is in information_schema in TiDB which same as MySQL 5.x
