### ISSUE TITLE
goword report many errors?

### ISSUE THREAD

**Issue by dreamquster** [pingcap/tidb#3594]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
After pull from master,  goword report errors

goword ddl/owner_manager.go ddl/syncer.go executor/write_test.go expression/builtin_string.go mysql/const.go plan/expression_rewriter.go plan/logical_plan_builder.go plan/logical_plans.go plan/optimizer.go plan/plan.go plan/planbuilder.go plan/plans.go plan/resolver.go plan/task.go server/conn_stmt.go server/server.go store/tikv/client.go store/tikv/lock_resolver.go store/tikv/mock-tikv/cluster.go store/tikv/mock-tikv/mvcc.go store/tikv/mock-tikv/rpc.go store/tikv/txn.go util/ranger/range.go util/types/range.go util/types/time.go

2. What did you expect to see?
Checking for files that need goword... OK!

3. What did you see instead?

Checking for files that need goword... ERROR!

mysql/const.go.24: // The ServerVersion number should be three digits. (godoc-export: The -> ServerVersion?)
plan/logical_plan_builder.go.607: // colMatch(a,b) means that if a match b, e.g. t.a can match test.t.a but test.t.a can't match t.a. (godoc-local: colMatch(a,b) -> colMatch?)
plan/logical_plan_builder.go.657: // AggregateFuncExtractor visits Expr tree. (godoc-local: AggregateFuncExtractor -> havingAndOrderbyExprResolver?)
plan/logical_plans.go.188: // Originally the WHERE or ON condition is parsed into a single expression, (godoc-export: Originally -> Conditions?)
plan/logical_plans.go.196: // If ScanController is true, then the child of this selection is a scan, (godoc-export: If -> ScanController?)
plan/logical_plans.go.196: // If ScanController is true, then the child of this selection is a scan, (godoc-export: If -> ScanController?)
plan/logical_plans.go.201: // We will check this at decorrelate phase. (godoc-local: We -> controllerStatus?)
plan/logical_plans.go.201: // We will check this at decorrelate phase. (godoc-local: We -> controllerStatus?)
plan/logical_plans.go.350: // AddChild for parent. (godoc-local: AddChild -> addChild?)
plan/optimizer.go.203: // MySQL error code. (godoc-export: MySQL -> CodeNoDB?)
plan/plan.go.48: // Get all the parents. (godoc-export: Get -> Parents?)
plan/plan.go.50: // Get all the children. (godoc-export: Get -> Children?)
plan/plan.go.52: // Set the schema. (godoc-export: Set -> SetSchema?)
plan/plan.go.54: // Get the schema. (godoc-export: Get -> Schema?)
plan/plan.go.56: // Get the ID. (godoc-export: Get -> ID?)
plan/plan.go.58: // Get id allocator (godoc-export: Get -> Allocator?)
plan/plan.go.108: // requriedProp stands for the required physical property by parents. (godoc-local: requriedProp -> requiredProp?)
plan/plan.go.192: // If the count is calculated by pseudo table, it's not reliable. Otherwise it's reliable. (godoc-local: If -> reliable?)
plan/plan.go.192: // If the count is calculated by pseudo table, it's not reliable. Otherwise it's reliable. (godoc-local: If -> reliable?)
plan/planbuilder.go.237: // Detect aggregate function or groupby clause. (godoc-local: Detect -> detectSelectAgg?)
plan/plans.go.93: // Used by show variables (godoc-export: Used -> GlobalScope?)
plan/plans.go.93: // Used by show variables (godoc-export: Used -> GlobalScope?)
plan/resolver.go.67: /* For Select Statement. */ (godoc-local: For -> tableMap?)
plan/resolver.go.70: // table map to lookup and check derived-table(subselect) name conflict. (godoc-local: table -> derivedTableMap?)
plan/resolver.go.72: // tableSources collected in from clause. (godoc-local: tableSources -> tables?)
plan/resolver.go.74: // result fields collected in select field list. (godoc-local: result -> fieldList?)
plan/resolver.go.76: // result fields collected in group by clause. (godoc-local: result -> groupBy?)
plan/resolver.go.79: // The join node stack is used by on condition to find out (godoc-local: The -> joinNodeStack?)
plan/resolver.go.84: // When visiting TableRefs, tables in this context are not available (godoc-local: When -> inTableRefs?)
plan/resolver.go.84: // When visiting TableRefs, tables in this context are not available (godoc-local: When -> inTableRefs?)
plan/resolver.go.87: // When visiting on condition only tables in current join node are available. (godoc-local: When -> inOnCondition?)
plan/resolver.go.87: // When visiting on condition only tables in current join node are available. (godoc-local: When -> inOnCondition?)
plan/resolver.go.89: // When visiting field list, fieldList in this context are not available. (godoc-local: When -> inFieldList?)
plan/resolver.go.89: // When visiting field list, fieldList in this context are not available. (godoc-local: When -> inFieldList?)
plan/resolver.go.91: // When visiting group by, groupBy fields are not available. (godoc-local: When -> inGroupBy?)
plan/resolver.go.91: // When visiting group by, groupBy fields are not available. (godoc-local: When -> inGroupBy?)
plan/resolver.go.93: // When visiting having, only fieldList and groupBy fields are available. (godoc-local: When -> inHaving?)
plan/resolver.go.93: // When visiting having, only fieldList and groupBy fields are available. (godoc-local: When -> inHaving?)
plan/resolver.go.95: // When visiting having, checks if the expr is an aggregate function expr. (godoc-local: When -> inHavingAgg?)
plan/resolver.go.95: // When visiting having, checks if the expr is an aggregate function expr. (godoc-local: When -> inHavingAgg?)
plan/resolver.go.97: // OrderBy clause has different resolving rule than group by. (godoc-local: OrderBy -> inOrderBy?)
plan/resolver.go.97: // OrderBy clause has different resolving rule than group by. (godoc-local: OrderBy -> inOrderBy?)
plan/resolver.go.99: // When visiting column name in ByItem, we should know if the column name is in an expression. (godoc-local: When -> inByItemExpression?)
plan/resolver.go.99: // When visiting column name in ByItem, we should know if the column name is in an expression. (godoc-local: When -> inByItemExpression?)
plan/resolver.go.101: // If subquery use outer context. (godoc-local: If -> useOuterContext?)
plan/resolver.go.101: // If subquery use outer context. (godoc-local: If -> useOuterContext?)
plan/resolver.go.103: // When visiting multi-table delete stmt table list. (godoc-local: When -> inDeleteTableList?)
plan/resolver.go.103: // When visiting multi-table delete stmt table list. (godoc-local: When -> inDeleteTableList?)
plan/resolver.go.105: // When visiting create/drop table statement. (godoc-local: When -> inCreateOrDropTable?)
plan/resolver.go.105: // When visiting create/drop table statement. (godoc-local: When -> inCreateOrDropTable?)
plan/resolver.go.107: // When visiting show statement. (godoc-local: When -> inShow?)
plan/resolver.go.107: // When visiting show statement. (godoc-local: When -> inShow?)
plan/resolver.go.109: // When visiting create/alter table statement. (godoc-local: When -> inColumnOption?)
plan/resolver.go.109: // When visiting create/alter table statement. (godoc-local: When -> inColumnOption?)
plan/resolver.go.419: // handleTableSources checks name duplication (godoc-local: handleTableSources -> handleTableSource?)
plan/task.go.38: // TODO: In future, we should split copTask to indexTask and tableTask. (godoc-local: TODO: -> copTask?)
server/conn_stmt.go.358: // See https://dev.mysql.com/doc/internals/en/com-set-option.html (godoc-local: See -> handleSetOption?)
server/server.go.70: // When a critical error occurred, we don't want to exit the process, because there may be (godoc-local: When -> stopListenerCh?)
server/server.go.93: // Generate a random string using ASCII characters but avoid separator character. (godoc-local: Generate -> randomBuf?)
store/tikv/client.go.103: // TODO: Add flow control between RPC clients in TiDB ond RPC servers in TiKV. (godoc-local: TODO: -> rpcClient?)
store/tikv/lock_resolver.go.36: // Cache resolved txns (FIFO, txn id -> txnStatus). (godoc-local: Cache -> resolved?)
store/tikv/mock-tikv/cluster.go.317: // getPairsGroupByRegions groups the key value pairs into splitted regions. (godoc-local: getPairsGroupByRegions -> getEntriesGroupByRegions?)
store/tikv/mock-tikv/mvcc.go.240: // A Pair is a KV pair read from MvccStore or an error if any occurs. (godoc-export: A -> Pair?)
store/tikv/mock-tikv/rpc.go.92: // store id for current request (godoc-local: store -> storeID?)
store/tikv/mock-tikv/rpc.go.92: // store id for current request (godoc-local: store -> storeID?)
store/tikv/mock-tikv/rpc.go.94: // Used for handling normal request. (godoc-local: Used -> startKey?)
store/tikv/mock-tikv/rpc.go.97: // Used for handling coprocessor request. (godoc-local: Used -> rawStartKey?)
store/tikv/mock-tikv/rpc.go.100: // Used for current request. (godoc-local: Used -> isolationLevel?)
store/tikv/mock-tikv/rpc.go.100: // Used for current request. (godoc-local: Used -> isolationLevel?)
store/tikv/txn.go.68: // Implement transaction interface. (godoc-export: Implement -> Get?)
util/ranger/range.go.46: // Point is the end point of range interval. (godoc-local: Point -> point?)
util/types/range.go.147: // Convert2IndexRange implements the Convert2IndexRange interface. (godoc-export: Convert2IndexRange -> String?)
util/types/time.go.166: // TODO: Define a type for timestamp, remove its representation from here. (godoc-export: TODO: -> TimeZone?)
util/types/time.go.710: //Add adds d to d, returns a duration value. (godoc-export: adds -> Add?)

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by morgo** [comment]
This is being addressed in https://github.com/pingcap/tidb/issues/3120

I am going to close this issue as a duplicate.  Please feel free to re-open if you have questions.  Thanks!
