### ISSUE TITLE
[stats] auto analyze failed

### ISSUE THREAD

**Issue by zhuzhenwen-github** [pingcap/tidb#35948]
## Bug Report

[analyze.go:1435] ["analyze worker panicked"] [recover="runtime error: slice bounds out of range [-1:]"] [stack="github.com/pingcap/tidb/executor.(*AnalyzeColumnsExec).subBuildWorker.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/analyze.go:1435\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:838\nruntime.goPanicSliceB\n\t/usr/local/go/src/runtime/panic.go:117\ngithub.com/pingcap/tidb/statistics.BuildHistAndTopN\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/builder.go:346\ngithub.com/pingcap/tidb/executor.(*AnalyzeColumnsExec).subBuildWorker\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/analyze.go:1559\ngithub.com/pingcap/tidb/executor.(*AnalyzeColumnsExec).buildSamplingStats.func3\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/analyze.go:1136\ngithub.com/pingcap/tidb/executor.(*notifyErrorWaitGroupWrapper).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/analyze.go:2653"]

### 1. Minimal reproduce step (Required)
Execute commands manually "analyze table  ${tableName}"

### 2. What did you expect to see? (Required)
auto analyze success

### 3. What did you see instead (Required)
SHOW ANALYZE STATUS;
State:failed
Fail_reason:runtime error: slice bounds out of range [-1:]

### 4. What is your TiDB version? (Required)
Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by chrysan** [comment]
@zhuzhenwen-github Can you provide more details about the reproduce steps?

**Comment by chrysan** [comment]
@zhuzhenwen-github when I tried to reproduce in my local env, I got:
```
mysql> source [gt_eat_pay_t_eat_arr_order_main_son_meta.txt](https://github.com/pingcap/tidb/files/9052693/gt_eat_pay_t_eat_arr_order_main_son_meta.txt)
ERROR 1273 (HY000): Unsupported collation when new collation is enabled: 'utf8_general_mysql500_ci'
```
Is your env upgraded from old version? 
Can you help check your env:
1. value of config "new_collations_enabled_on_first_bootstrap"
2. 
```
mysql> show variables like "%collation%";
```

**Comment by zhuzhenwen-github** [comment]
> @zhuzhenwen-github when I tried to reproduce in my local env, I got:
> 
> ```
> mysql> source [gt_eat_pay_t_eat_arr_order_main_son_meta.txt](https://github.com/pingcap/tidb/files/9052693/gt_eat_pay_t_eat_arr_order_main_son_meta.txt)
> ERROR 1273 (HY000): Unsupported collation when new collation is enabled: 'utf8_general_mysql500_ci'
> ```
> 
> Is your env upgraded from old version? Can you help check your env:
>  yes, from 5.4 to  6.0,and then from 6.0 to 6.1
> 1. value of config "new_collations_enabled_on_first_bootstrap"
> 
![c1](https://user-images.githubusercontent.com/75345604/177671830-1adcc70c-914f-4dc9-b01c-ed6de832a458.png)

> ```
> mysql> show variables like "%collation%";
> ```
![c2](https://user-images.githubusercontent.com/75345604/177671865-8bb2355a-29de-48d8-8897-436f4c07804a.png)

**Comment by wjhuang2016** [comment]
Could you show us the result of 
```select * from mysql.tidb where VARIABLE_NAME="new_collation_enabled";```?

**Comment by zhuzhenwen-github** [comment]
> Could you show us the result of `select * from mysql.tidb where VARIABLE_NAME="new_collation_enabled";`?

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/75345604/178399809-fc4f9037-8d45-418a-a6d2-5b17bc1ac860.png">
