### ISSUE TITLE
Implement general_log printing

### ISSUE THREAD

**Issue by choleraehyq** [pingcap/tidb#3597]
Currently we've implemented the builtin variable [`general_log`]( https://github.com/pingcap/tidb/blob/439a47c0929e917aed2830ae42330fa2d9ac4109/sessionctx/variable/sysvar.go#L183) , but it doesn't really make sense.

**Comment by shenli** [comment]
@choleraehyq We have system variable general_log, but we do not implement its behaviour. It is a good suggestion. Maybe we could support it in the GA version.

**Comment by zimulala** [comment]
Done.
