### ISSUE TITLE
br: link in readme is failure

### ISSUE THREAD

**Issue by shawn0915** [pingcap/tidb#35997]
https://github.com/pingcap/tidb/blob/master/br/README.md

when click this link, we will get this error. `The 'pingcap/tidb' repository doesn't contain the 'br/COMPATIBLE_TEST.md' path in 'master'. `
```
See [COMPATBILE_TEST](./COMPATIBLE_TEST.md)
```

could be update link as `(./COMPATIBILITY_TEST.md)`

**Comment by PrajwalBorkar** [comment]
I like to work on this issue
