### ISSUE TITLE
[fatal] run table schema failed - driver: bad connection

### ISSUE THREAD

**Issue by usedev** [pingcap/tidb#3599]
导入数据提示错误，但是无法定位代码

2017/07/03 01:54:29 db.go:117: [warning] sql execution costs 18.114372 seconds, CREATE TABLE `user_interest` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`track_id` char(32) COLL
2017/07/03 01:54:29 loader.go:674: [fatal] run table schema failed - driver: bad connection
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:84:
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:558:

**Comment by iamzhout** [comment]
要是能提供出错的样例数据，会对定位问题有很大帮助。

**Comment by shenli** [comment]
@iamxy From the error message, I guess that there is something wrong with tidb-server. Could yougrep 'error' in tidb-server's log file?

**Comment by usedev** [comment]
[mysql] 2017/07/03 01:54:29 packets.go:33: unexpected EOF
2017/07/03 01:54:29 db.go:125: [warning] [exec][sql][use kanqu_zbb; CREATE TABLE `user_interest` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`track_id` char(32) COLL][error]driver: bad connection
2017/07/03 01:54:29 db.go:128: [error] [exec][sql][use kanqu_zbb; CREATE TABLE `user_interest` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`track_id` char(32) COLL][error]invalid connection
2017/07/03 01:54:29 db.go:117: [warning] sql execution costs 18.114154 seconds, CREATE TABLE `user_interest` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`track_id` char(32) COLL
2017/07/03 01:54:29 db.go:117: [warning] sql execution costs 18.114372 seconds, CREATE TABLE `user_interest` (`id` int(10) unsigned NOT NULL AUTO_INCREMENT,`track_id` char(32) COLL
2017/07/03 01:54:29 loader.go:674: [fatal] run table schema failed - driver: bad connection
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:84:
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:558:

**Comment by usedev** [comment]
2017/07/03 02:11:16 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:18 main.go:176: [error] <nil> 
2017/07/03 02:11:18 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:19 domain.go:312: [error] [ddl] reload schema in loop err /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:20 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:20 tidb.go:166: [info] RollbackTxn for ddl/autocommit error. 
2017/07/03 02:11:20 session.go:623: [warning] [0] session error:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:20 domain.go:515: [error] /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:22 txn.go:35: [error] [kv] RunInNewTxn error - [try again later]: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:22 ddl_worker.go:60: [error] [ddl] handle ddl job err /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:22 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:24 ddl.go:317: [error] [ddl] remove self version path failed context deadline exceeded
2017/07/03 02:11:24 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:26 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:28 domain.go:312: [error] [ddl] reload schema in loop err /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/store/tikv/backoff.go:184: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2017/07/03 02:11:28 pd.go:124: [error] updateTS error: rpc error: code = Unavailable desc = grpc: the connection is unavailable

**Comment by sunhao2017** [comment]
@usedev Could you provide your hardware configurations and deployment topologies of your TiDB cluster?

**Comment by wjhuang2016** [comment]
Close this issue because it's inactive for a long time.
