### ISSUE TITLE
To remove one particular label from store via pd-ctl

### ISSUE THREAD

**Issue by songrijie** [pingcap/tidb#36001]
### Background

pd-ctl provides a way to append a label, which is documented [here](https://docs.pingcap.com/zh/tidb/dev/pd-control#store-delete--cancel-delete--label--weight--remove-tombstone--limit--store_id---jqquery-string)

```
store [delete | cancel-delete | label | weight | remove-tombstone | limit ] <store_id> [--jq="<query string>"]
```

To append a label { zone = "cn" } to store 1:

```
store label 1 zone cn
```

However, there's no way to delete one particular label. Instead, we will have to reset all labels. 

### Proposal

Include a new command `remove-label`, that are able to delete one particular label. For example:

```
store remove-label 1 zone cn
```

**Comment by songrijie** [comment]
please take a look. @nolouch

**Comment by nolouch** [comment]
better transfer to pd repo.

**Comment by nolouch** [comment]
duplicated with https://github.com/tikv/pd/issues/5509
