### ISSUE TITLE
Remove restriction on table partitioning about all partition columns needs to be included in all unique keys.

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#36019]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When using table partitioning in TiDB one needs to include all partitioning columns in all unique keys, to ensure uniqueness. This sometimes leads to breaking the real properties of unique and primary keys simply because one wants to partition a table (like adding the partitioning columns to the PK).

**Describe the feature you'd like:**

Support unique indexes to not include the partitioning columns.

This can be done in different ways:
- Only enforce uniqueness within each partition (I would prefer to not break the table uniqueness, but we may want to give this possibility to the user/DBA). (like [EnterpriseDB](https://www.enterprisedb.com/docs/epas/latest/epas_compat_table_partitioning/))
- Support Global Index (separate [feature request](https://github.com/pingcap/tidb/issues/18032))
- Check all partitions for duplicates on insert/update (write), similar to how secondary indexes are searched, but cannot make use of partition pruning.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Defined2014** [comment]
We decided supports global index, and it GA in v8.5.0, so close this issue.
