### ISSUE TITLE
In `information_schema`.`columns` table, timestamp column's column_default is inconsistent with MySQL

### ISSUE THREAD

**Issue by lmduean** [pingcap/tidb#36027]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

> mysql> create table t ( `b` timestamp(3) NOT NULL DEFAULT '1970-01-01 08:00:01.000' COMMENT '');
> Query OK, 0 rows affected (0.08 sec)
> 
> mysql> show create table t;
> +-------+----------------------------------------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                                                 |
> +-------+----------------------------------------------------------------------------------------------------------------------------------------------+
> | t     | CREATE TABLE `t` (
>   `b` timestamp(3) NOT NULL DEFAULT '1970-01-01 08:00:01.000'
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
> +-------+----------------------------------------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> select column_default from information_schema.columns where TABLE_NAME='t';
> +-------------------------+
> | column_default          |
> +-------------------------+
> | 1970-01-01 00:00:01.000 |
> +-------------------------+
> 1 row in set (0.03 sec)

### 2. What did you expect to see? (Required)

In mysql:

> mysql> create table t ( `b` timestamp(3) NOT NULL DEFAULT '1970-01-01 08:00:01.000' COMMENT '');
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql> show create table t;
> +-------+-------------------------------------------------------------------------------------------------------------------------+
> | Table | Create Table                                                                                                            |
> +-------+-------------------------------------------------------------------------------------------------------------------------+
> | t     | CREATE TABLE `t` (
>   `b` timestamp(3) NOT NULL DEFAULT '1970-01-01 08:00:01.000'
> ) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
> +-------+-------------------------------------------------------------------------------------------------------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> select column_default from information_schema.columns where TABLE_NAME='t';
> +-------------------------+
> | column_default          |
> +-------------------------+
> | 1970-01-01 08:00:01.000 |
> +-------------------------+
> 1 row in set (0.01 sec)

### 3. What did you see instead (Required)

show create table's result and information_schema.columns's result are  inconsistent!

### 4. What is your TiDB version? (Required)

> mysql> mysql> select version();
> +-----------------------------------------+
> | version()                               |
> +-----------------------------------------+
> | 5.7.25-TiDB-v5.4.0-alpha-178-g02a8f0453 |
> +-----------------------------------------+
> 1 row in set (0.00 sec)

**Comment by lmduean** [comment]
possible fix for v3.0.5 https://github.com/lmduean/tidb/pull/1/files

**Comment by Defined2014** [comment]
Thanks for your reply, you can get much information from this issue https://github.com/pingcap/tidb/issues/35206

**Comment by lmduean** [comment]
> Thanks for your reply, you can get much information from this issue #35206

so, we will not fix it?

**Comment by Defined2014** [comment]
> > Thanks for your reply, you can get much information from this issue #35206
> 
> so, we will not fix it?

I think it will be better if both `information_schema.columns` and `show create table` were related with timezone. If you have interests, you can open a PR to fix it. It looks like you already have a PR for v3.0.5.

**Comment by xiongjiwei** [comment]
it is a mysql bug I think https://bugs.mysql.com/bug.php?id=107112
