### ISSUE TITLE
CVE issue

### ISSUE THREAD

**Issue by tain198127** [pingcap/tidb#36045]
#### 1.1.
view https://www.oscs1024.com/cd/1527794281950040064?sign=3eaf8972&report=1 

![image](https://user-images.githubusercontent.com/1415402/177945312-11b00076-3c50-47cf-8d0e-56b0ff06fefb.png)

it is show some security issues.  I found this issue is includ by tidb/tidb-binlog/driver/example/kafkaReader example project.

#### 1.2. 
open pom of sample, run 
```
mvn dependency:tree
```
#### 1.3.
you could found the some issue version in https://www.oscs1024.com/cd/1527794281950040064?sign=3eaf8972&report=1  report.

### 2. What did you expect to see? (Required)
upgrade some dependecny of pom to high version

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/1415402/177944854-9be298db-7cc4-4b2f-aebe-e3057eca0aec.png)

![image](https://user-images.githubusercontent.com/1415402/177945067-171890bf-c0ae-447b-a97d-4b479d580ec4.png)

### 4. What is your TiDB version? (Required)
master branch

**Comment by xhebox** [comment]
Duplicate of #36042
