### ISSUE TITLE
Thread-safety bug of GetOrStoreStmtCache()

### ISSUE THREAD

**Issue by zhaopei05** [pingcap/tidb#36158]
## Bug Report

Thread-safety bug of GetOrStoreStmtCache()

### 1. Minimal reproduce step (Required)

Sql statement composed of multiple unions, with each union invoking 'now()' function. May increase the concurrency by invoking 'now()' multiple times within each union. As this is thread-safety bug, it will be reproduced probabilistically.

### 2. What did you expect to see? (Required)

Sql executed successfully.

### 3. What did you see instead (Required)

TiDB server panic with fatal error: concurrent map writes. The stack output pointed to GetOrStoreStmtCache() (sysvar.go:122). As an analysis, unions can be executed concurrently, thus the timestamp cache of statement scope can be written/read in parallel.

### 4. What is your TiDB version? (Required)

v5.4.0

**Comment by jackysp** [comment]
Duplicate with https://github.com/pingcap/tidb/issues/36159

**Comment by Yisaer** [comment]
I closed this issue due to duplicated with with https://github.com/pingcap/tidb/issues/36159
