### ISSUE TITLE
TiFlash's table scan will not support `KeepOrder` anymore

### ISSUE THREAD

**Issue by windtalker** [pingcap/tidb#36231]
## Bug Report

In TiDB, it's assumed that when in cop mode, [TiFlash's table scan support `KeepOrder`](https://github.com/pingcap/tidb/blob/ce4edc9df4004ab76b10b9c9418a1379d1be4ece/planner/core/find_best_task.go#L1875), however, after https://github.com/pingcap/tiflash/issues/5376, TiFlash will not support `KeepOrder` even in cop mode, we should disable the related plan.

**Comment by flowbehappy** [comment]
https://github.com/pingcap/tidb/pull/35851 TiFlash fast mode cannot guarantee keep order.

**Comment by windtalker** [comment]
@seiya-annie 
We decide to add a flag in the protocol so, before this change
| TiFlash mode | can keep order |
|--|--|
| normal | yes |

After this change
| TiFlash mode | can keep order |
|--|--|
| normal | yes (when TiDB require TiFlash to keep order explicitly)|
| fast | no |

Since `fast` mode is a newly added mode, and for `normal` mode, TiFlash can still keep order when TiDB explictly set the `keep_order` field(which is what #36232 for), I think it is not a compatibility-breaker anymore.
