### ISSUE TITLE
SlowLog: Optimize_time is not updated when the sql is in prepare statement mode

### ISSUE THREAD

**Issue by TonsnakeLin** [pingcap/tidb#36359]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table t1(id1 int primary key, id2 int);
insert into t1 values(1,1);
prepare stmt1 from "insert into t1 values(?,?)"
set @var5 = '5',@var6 = '6';

set global tidb_slow_log_threshold=0;
begin;
SELECT * FROM t1;
execute stmt1  using @var5, @var5;
execute stmt1  using @var6, @var6;
commit;
set global tidb_slow_log_threshold=300;

### 2. What did you expect to see? (Required)
The Optimize_time in the slow log for every sql is different.

### 3. What did you see instead (Required)
The Optimize_time is always equal to the time of the first sql in the transaction.

### 4. What is your TiDB version? (Required)

v6.2.0-alpha-343-g08618d3

**Comment by chrysan** [comment]
Seems duplicated with https://github.com/pingcap/tidb/issues/39711, close this one.
