### ISSUE TITLE
Execute SQL returns wrong result

### ISSUE THREAD

**Issue by Damon-Guo** [pingcap/tidb#36398]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table t1 (id int primary key , b varchar(10) not null) ;
insert into t1 values (1,'a'),(2,'b'),(3,'c');

select * from 
(select id,b as c from t1 
union all 
select id,null as c from t1 ) c
where c.c is  null; 

### 2. What did you expect to see? (Required)
mysql 5.7
![image](https://user-images.githubusercontent.com/50732087/180127440-9696a074-0f0a-46a2-b305-e6a9fcaa95ec.png)
![image](https://user-images.githubusercontent.com/50732087/180127477-46d5207d-dbe6-4c4e-9e7d-d2131a7f2553.png)

### 3. What did you see instead (Required)
![ykjNq8fNNZ](https://user-images.githubusercontent.com/50732087/180127546-a4b14ff4-7b01-4473-b3b9-b5a73358cea5.jpg)

### 4. What is your TiDB version? (Required)
5.3.2
5.4.2

**Comment by fixdb** [comment]
Verified, the bug has been fixed.

**Comment by qw4990** [comment]
Fixed by https://github.com/pingcap/tidb/pull/31400
