### ISSUE TITLE
show columns from view error

### ISSUE THREAD

**Issue by shiyuhang0** [pingcap/tidb#36426]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE added (`id` int(11),`name` text,`some_date` timestamp);
CREATE TABLE incremental  (
  `id` int(11),
  `name`text,
  `some_date` timestamp
);
 create view
            temp_view
        as (
select * from `added`
where id > (select max(id) from `incremental`)
        );
 show columns from temp_view;
```

### 2. What did you expect to see? (Required)
success

### 3. What did you see instead (Required)
```
1356 - View 'test.temp_view' references invalid table(s) or column(s) or function(s) or definer/invoker of view lack rights to use them
```

### 4. What is your TiDB version? (Required)
v6.1.0

### 5. Other Info
TiDB 6.0.0 and MySQL 8.0.27 will success.

TIDB doc shows that `show columns from` is fully compatible with MySQL, so I think is a bug for TiDB v6.1.0
https://docs.pingcap.com/tidb/v5.4/sql-statement-show-columns-from#mysql-compatibility

**Comment by tangenta** [comment]
Introduced by #33946.

**Comment by shiyuhang0** [comment]
I think this pr should cherry pick to v6.1.0
