### ISSUE TITLE
read `information_columns` will produce cop request

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#36496]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

`create view with subquery` like `create view as select * from t where t.a > (select max(a) from t)`

`select * from information_schema.columns` will produce cop request

if we have many views, it will make `tikv/tiflash` increase CPU usage

![origin_img_v2_eec1fd42-ea93-438e-af12-39e40be65b3g](https://user-images.githubusercontent.com/20839912/180631166-540b2eb9-5291-4feb-bb45-0bef5be33f41.jpg)

problem introduce by https://github.com/pingcap/tidb/pull/22363

**Comment by xiongjiwei** [comment]
same risk with `show columns from table`

**Comment by tangenta** [comment]
Related to https://github.com/pingcap/tidb/issues/36426.

**Comment by tangenta** [comment]
I think an efficient solution for #22316 is to store the data type in the view when it is created.
