### ISSUE TITLE
Add a system variable to control whether to inline CTE or not

### ISSUE THREAD

**Issue by fixdb** [pingcap/tidb#36514]
## Enhancement
Currently, CTE can only be inlined through `MERGE()` hint. But for those queries that have many CTEs, and queries that are generated by BI, it is better to have a system variable to control whether to inline CTE or not.
Suggested var name:
`tidb_opt_inline_cte`

NB. `MERGE()` hint can override the `tidb_opt_inline_cte` variable.

**Comment by elsa0520** [comment]
docs: [https://github.com/pingcap/docs/pull/10343](url)

**Comment by elsa0520** [comment]
please assign to me ~
