### ISSUE TITLE
 select count(*) table with tiflash replica fail, and report: ERROR 1105 (HY000): rpc error: code = Unavailable desc = error reading from server: EOF

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#36512]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. install v5.1.4 tidb cluster
2. init bank wkload in this cluster
3. alter table bank.account SET TIFLASH REPLICA 1;
4. upgrade tidb cluster to v6.2.0 
6. select count(*) from bank.account;

### 2. What did you expect to see? (Required)
no error

### 3. What did you see instead (Required)
mysql> select count(*) from bank.account;
ERROR 1105 (HY000): rpc error: code = Unavailable desc = error reading from server: EOF

2022-07-25 13:58:54 (GMT+8)TiDB tidb-peer:14000[mpp.go:352] ["cancel task error"] [error="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 10.244.1.173:3930: connect: connection refused\""] ["query id"=434825781735063553] ["on addr"=tiup-peer:3930]
mysql> exit

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0
Edition: Community
Git Commit Hash: 0ea937e56adac89ea7df1ce5406c7dc20a3f83ae
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-07-23 10:09:51
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

**Comment by seiya-annie** [comment]
tidb log:
[tidb.log.gz](https://github.com/pingcap/tidb/files/9178470/tidb.log.gz)

**Comment by seiya-annie** [comment]
fix by https://github.com/pingcap/tidb/pull/36451

**Comment by guo-shaoge** [comment]
Should also be fixed in v6.2.

**Comment by seiya-annie** [comment]
fix by https://github.com/pingcap/tiflash/pull/5459
