### ISSUE TITLE
autocommit handles process issues

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tidb#36581]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

set autocommit = ON;
begin;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test.t1;
+-----+
| id  |
+-----+
| 590 |
+-----+
1 row in set (0.01 sec)

mysql> update test.t1 set id = id+1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from test.t1;
+-----+
| id  |
+-----+
| 591 |
+-----+
1 row in set (0.01 sec)

mysql> set autocommit = ON;
Query OK, 0 rows affected (0.01 sec)

mysql> rollback;
### 2. What did you expect to see? (Required)
consistent with mysql
select * from test.t1;
+-----+
| id  |
+-----+
| 590 |
+-----+
### 3. What did you see instead (Required)
select * from test.t1;
+-----+
| id  |
+-----+
| 591 |
+-----+
1 row in set (0.01 sec)
### 4. What is your TiDB version? (Required)

Release Version: v6.1.0
Edition: Community
Git Commit Hash: 1a89decdb192cbdce6a7b0020d71128bc964d30f
Git Branch: heads/refs/tags/v6.1.0
UTC Build Time: 2022-06-05 05:15:11
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by seiya-annie** [comment]
tested in mysql 8.0.23:
```sql
mysql> create table test(a int);
Query OK, 0 rows affected (0.05 sec)

mysql> insert into test values (590);
Query OK, 1 row affected (0.01 sec)

mysql> set autocommit = ON;
Query OK, 0 rows affected (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test;
+------+
| a    |
+------+
|  590 |
+------+
1 row in set (0.00 sec)

mysql> update test set a= a+1;
Query OK, 1 row affected (0.00 sec)
Rows matched: 1  Changed: 1  Warnings: 0

mysql> select * from test;
+------+
| a    |
+------+
|  591 |
+------+
1 row in set (0.00 sec)

mysql> set autocommit = ON;
Query OK, 0 rows affected (0.00 sec)

mysql> rollback;
Query OK, 0 rows affected (0.01 sec)

mysql> select * from test;
+------+
| a    |
+------+
|  590 |
+------+
1 row in set (0.00 sec)

mysql> exit
```

**Comment by seiya-annie** [comment]
tried on 4.0.16, exists the same issue

**Comment by cfzjywxk** [comment]
@seiya-annie 
Thanks for the analysis, it's needed to be fixed.
