### ISSUE TITLE
Support SAVEPOINT

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#3663]
https://dev.mysql.com/doc/refman/5.7/en/savepoint.html

**Comment by lotaku** [comment]
any update?

**Comment by kocoten1992** [comment]
can't write reusable module that interact with database without this feature, have to repeat my self every time

**Comment by morgo** [comment]
I am going to close this issue as a duplicate of https://github.com/pingcap/tidb/issues/6840

Please feel free to re-open it if you have any questions.  Thank you!

**Comment by Allan-Nava** [comment]
Any news?
