### ISSUE TITLE
set abnormal value for tidb_enable_noop_variables don't report error or warning

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#36646]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
mysql> SET global tidb_enable_noop_variables = 2;
Query OK, 0 rows affected (0.01 sec)

mysql> show global variables like '%tidb_enable_noop_variables%';
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_noop_variables | OFF   |
+----------------------------+-------+
1 row in set (0.00 sec)
mysql> show global variables like '%tidb_enable_noop_variables%';
+----------------------------+-------+
| Variable_name              | Value |
+----------------------------+-------+
| tidb_enable_noop_variables | OFF   |
+----------------------------+-------+
1 row in set (0.01 sec)

```

### 2. What did you expect to see? (Required)
return error
ERROR 1231 (42000): Variable 'tidb_enable_noop_variables' can't be set to the value of '2'

### 3. What did you see instead (Required)
no error, no warning

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0
Edition: Community
Git Commit Hash: 65f7e2e8b71ea7d312cfb35f87e6039271cb2dd8
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-07-27 10:10:50
GoVersion: go1.18.2

**Comment by djshow832** [comment]
This also applies to other system variables, such as `tidb_multi_statement_mode`.
We need to modify them all at once.

**Comment by morgo** [comment]
This was fixed by https://github.com/pingcap/tidb/issues/36647

ENUM variables can be specified by ordinal value as well (this is a MySQL compatible behavior). In latest master, it now only supports 0/1. Ideally, it should actually be changed to a TypeBool now. But that's a minor issue.
