### ISSUE TITLE
tidb not providing service after upgrading from 6.0.0 to 6.2.0

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#36659]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Upgrade TiDB cluster from v4.0.16 -> 5.0  ...  6.0.0 -> 6.2.0
2. After upgrading from 6.0.0 to 6.2.0, TiDB is not providing service

### 2. What did you expect to see? (Required)
TiDB should work correctly after upgrade.

### 3. What did you see instead (Required)

![image](https://user-images.githubusercontent.com/7403864/181442859-05dd61b1-3472-43cc-ae7d-c9c4f21b1d89.png)

### 4. What is your TiDB version? (Required)
/ # /tidb-server -V
Release Version: v6.2.0-alpha
Edition: Community
Git Commit Hash: 6c8bb7cf15730fd3b4f75f2d3e98e63decd58b1d
Git Branch: heads/refs/tags/v6.2.0-alpha
UTC Build Time: 2022-07-27 11:08:30
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by fubinzh** [comment]
[tidb.log](https://github.com/pingcap/tidb/files/9206402/tidb.log)

**Comment by Tammyxia** [comment]
Reproduce in tidb version (tiup cluster upgrade fron v5.4.2 to v6.2.0, still tiup start tidb failed):
Release Version: v6.2.0
Edition: Community
Git Commit Hash: 29fbcdf3da0121acf4e773eb802755231c1932e5
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-08-02 03:55:49
<img width="1556" alt="image" src="https://user-images.githubusercontent.com/78345569/182313764-9bbbc22f-686f-4c38-9f23-d8be8083bd50.png">
