### ISSUE TITLE
lighting import failed while import on DBAAS 

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tidb#36674]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create 1* TiDB, 3*Tikv 2u8G cluster.
2. try to import 100GB CSV file

### 2. What did you expect to see? (Required)
import success

### 3. What did you see instead (Required)
import fail,  and report Root cause: [Lightning:Restore:ErrRestoreTable]restore table `gotpc_1500`.`order_line` failed: EOF; EOF; EOF.

### 4. What is your TiDB version? (Required)

v6.1.0

**Comment by D3Hunter** [comment]
the error happens because TiKV restart in middle.

when lightning tries to write it will return `Unavailable` error in most case, but can return `io.EOF`

we will add retry on this error as an enhancement
