### ISSUE TITLE
connect to tidb-server on a non existent database reports error different from MySQL

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#3669]
1. What did you do?

Connect to TiDB server
```
# mysql -h 127.0.0.1  -P 4000 a_non_existent_db
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading authorization packet', system error: 0 "Internal error/check (Not system error)"
```

Connect to MySQL Server
```
# mysql  a_non_existent_db
ERROR 1049 (42000): Unknown database 'a_non_existent_db'
```

2. What did you expect to see?

ERROR 1049

3. What did you see instead?

ERROR 2013

4. What version of TiDB are you using (`tidb-server -V`)?

Git Commit Hash: f207800c80549483e312d8b1a2358a5fb85e17b2
UTC Build Time:  2017-07-07 09:45:22

**Comment by breeswish** [comment]
Duplicate https://github.com/pingcap/tidb/issues/3662

**Comment by winoros** [comment]
Closing for duplicate.
