### ISSUE TITLE
br log start failed with start-ts which is from the format of log start --help

### ISSUE THREAD

**Issue by MoCuishle28** [pingcap/tidb#36717]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run `br log start --help`
2. Run `br log start --pd 'IP:Port' --task-name pitr --start-ts '2022-07-29 12:00:00'

### 2. What did you expect to see? (Required)
log start should succeed.

### 3. What did you see instead (Required)
`Error: must set timezone when using datetime format ts`

### 4. What is your TiDB version? (Required)
6.2 nightly

**Comment by MoCuishle28** [comment]
PR https://github.com/pingcap/tidb/pull/36713 has fixed this issue.

**Comment by MoCuishle28** [comment]
PR https://github.com/pingcap/tidb/pull/36713 has fixed this issue.

**Comment by 3pointer** [comment]
it's better to give an example in error message.
