### ISSUE TITLE
v5.4.2 upgrade to v6.2.0 fail, tidb upgrade fail

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#36761]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

install tidb cluster with v5.4.2 version
upgrade to v6.2.0 version

### 2. What did you expect to see? (Required)
upgrade successfully

### 3. What did you see instead (Required)
upgrade fail

### 4. What is your TiDB version? (Required)

[root@tidb-0 bin]# ./tidb-server -V       
Release Version: v6.2.0
Edition: Community
Git Commit Hash: 1f14f4cf8b1954cf28cc75a9577b13563a733cc4
Git Branch: heads/refs/tags/v6.2.0
UTC Build Time: 2022-07-31 10:09:53
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by seiya-annie** [comment]
[tidb-4000.log.gz](https://github.com/pingcap/tidb/files/9230959/tidb-4000.log.gz)
[tidb-14000.log.gz](https://github.com/pingcap/tidb/files/9230961/tidb-14000.log.gz)

**Comment by seiya-annie** [comment]
workaround: deploy more than 1 pump

**Comment by seiya-annie** [comment]
workaround: deploy more than 1 pump

**Comment by seiya-annie** [comment]
if  binlog.ignore-error= true， upgrade will successfully. 
most of the customer clusters set   binlog.ignore-error= true, so degrade the severity to major

**Comment by bb7133** [comment]
PTAL @wjhuang2016
