### ISSUE TITLE
unstable test TestPBMemoryLeak

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#36789]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
     memory_test.go:68: 
        	Error Trace:	/home/jenkins/.tidb/tmp/04446c229c5a73c16deb3edddcb4db34/sandbox/processwrapper-sandbox/4823/execroot/__main__/bazel-out/k8-fastbuild/bin/executor/executor_test_/executor_test.runfiles/__main__/executor/memory_test.go:68
        	Error:      	"63111168" is not less than "53687091"
        	Test:       	TestPBMemoryLeak 
```

https://prow.pingcap.net/view/gs/pingcapprow/logs/bazel_test_tidb/1554270496122474496

**Comment by tiancaiamao** [comment]
I think we can remove this test or move it to other place.
This test is slow and unstable and not suitable for UT.

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
