### ISSUE TITLE
Inconsistent error response when authentication failed

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#3680]
MySQL:

```
$ mysql -u root -p --host=127.0.0.1 --port=3306
Enter password: 
ERROR 1045 (28000): Access denied for user 'root2'@'localhost' (using password: YES)
```

TiDB:

```
$ mysql -u root -p --host=127.0.0.1 --port=4000
Enter password: 
ERROR 1105 (HY000): ERROR 1045 (28000): Access denied for user 'root2'@'127.0.0.1' (using password: Yes)
```

**Comment by breeswish** [comment]
Fixed via #3696

**Comment by BrickXu** [comment]
@breeswish refs to your example, the error message shows "root2" but not "root", is it the password of root user ?

**Comment by breeswish** [comment]
@BrickXu I believe it should be a typo I made when pasting to the github since in my own machine `root` does not have a password and it will always auth successfully so that I used `root2` for authentication.

**Comment by BrickXu** [comment]
@breeswish thanks, but we meet a case that the ACL message shows the password instead of account, and I think I will open another issue for it.

**Comment by breeswish** [comment]
@BrickXu Ok
