### ISSUE TITLE
Support `\N`

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#3685]
MySQL:

mysql> select \N;
+------+
| NULL |
+------+
| NULL |
+------+
1 row in set, 1 warning (0.00 sec)

TiDB:

mysql> select \N;
ERROR 1105 (HY000): line 0 column 8 near "N" (total length 9)

**Comment by breeswish** [comment]
> Treatment of \N as a synonym for NULL in SQL statements is deprecated as of MySQL 5.7.18 and is removed in MySQL 8.0
