### ISSUE TITLE
The field of `select 'a' from t1;` is wrong

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#3686]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
create table t1(a int);
insert into t1 value(1);
select 'a' from t1;
```

2. What did you expect to see?
```
+---+
| a |
+---+
| a |
+---+
```

3. What did you see instead?
```
+------+
| 'a'  |
+------+
| a    |
+------+
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
- When sending field meta data, the field name comes from `columns_list`: https://github.com/mysql/mysql-server/blob/5.7/sql/sql_executor.cc#L104 . https://github.com/mysql/mysql-server/blob/5.7/sql/sql_executor.cc#L145
- `columns_list` is generated in parser token `select_item`: https://github.com/mysql/mysql-server/blob/5.7/sql/sql_yacc.yy#L9204
- In `PTI_expr_with_alias::itemize`, after `expr->itemize`:
  - if `expr` does not have a name, [expression text is used as the name](https://github.com/mysql/mysql-server/blob/5.7/sql/parse_tree_items.cc#L209)
  - [finally expr name will be used as item name](https://github.com/mysql/mysql-server/blob/5.7/sql/parse_tree_items.cc#L212)

When executing `select 'a'`, `expr` is `PTI_text_literal_text_string`, which `expr->itemize` [copies its content as the name](https://github.com/mysql/mysql-server/blob/5.7/sql/item.h#L3642)

When executing other statements: TODO
