### ISSUE TITLE
transport: Got too many pings from the client, closing the connection.

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#36861]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
TiDB meets many logs like "transport: Got too many pings from the client, closing the connection."

![image (1)](https://user-images.githubusercontent.com/4352397/182603765-72768e0e-fef3-454e-8795-7d9f3e1be315.png)

### 2. What did you expect to see? (Required)
No such log.

### 3. What did you see instead (Required)
Many logs.

### 4. What is your TiDB version? (Required)
v6.1.0

**Comment by geeklc** [comment]
this bug affect v5.4.3 also
