### ISSUE TITLE
upgrade Go 1.19

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#36879]
## Enhancement

Why we need to upgrade Go 1.19

- [x] important performance improvements (up to 20% for some generic programs)
- [ ] The garbage collector has added support for a soft memory limit, discussed in detail in [the new garbage collection guide](https://go.dev/doc/gc-guide#Memory_limit). The limit can be particularly helpful for optimizing Go programs to run as efficiently as possible in containers with dedicated amounts of memory. it is important for tidb.
- [ ] more metrics for Golang Runtime.  [runtime/metrics](https://tip.golang.org/pkg/runtime/metrics/)

For more information https://tip.golang.org/doc/go1.19

**Comment by Defined2014** [comment]
already use go1.19 in TiDB repo, close this issue.
