### ISSUE TITLE
Finish `todo` in builtin_cast.go#L1945

### ISSUE THREAD

**Issue by windtalker** [pingcap/tidb#36920]
## Enhancement
Finish `todo` in https://github.com/pingcap/tidb/blob/6be08109fb840ac0260eca9315bced582df9ab5e/expression/builtin_cast.go#L1945

**Comment by bb7133** [comment]
@windtalker Please don't ref a full link as a title. Could you change it?

**Comment by windtalker** [comment]
> @windtalker Please don't ref a full link as a title. Could you change it?

OK, change the title
