### ISSUE TITLE
error when changing a primary key column from int to bigint

### ISSUE THREAD

**Issue by qinix** [pingcap/tidb#3692]
1. What did you do?

```sql
ALTER TABLE `xxxx` CHANGE `id` `id` bigint NOT NULL AUTO_INCREMENT
```

Where the only difference around the alter table statement is the column type. `NOT NULL` and `AUTO_INCREMENT` are not changing.

2. What did you expect to see?

Change the `id` field from int to bigint.

3. What did you see instead?

An error occurred. It says: `unsupported modify column %!s(MISSING)`.

4. What version of TiDB are you using (`tidb-server -V`)?

```
Git Commit Hash: e356b2663f433aa9538da9f6674330d27b8bea13
UTC Build Time:  2017-07-05 11:39:29
```

**Comment by zimulala** [comment]
We can't support this operation now. You can read the [docs](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md) or [docs-cn](https://github.com/pingcap/docs-cn/blob/master/op-guide/mysql-compatibility.md).

**Comment by qinix** [comment]
@zimulala If I already had a large table with int primary key, and it's reaching 2147483648 (maximum of int) of rows, what should I do? That's why I'm trying TiDB now.

**Comment by zimulala** [comment]
@qinix I'm sorry the document is not stated. TiDB only checks if the `change` operation has the definition of `auto_increament` now.  Thanks for your report! We will fix it later in TiDB code.

**Comment by breeswish** [comment]
Fixed in https://github.com/pingcap/tidb/pull/3748
