### ISSUE TITLE
Resolve problems that join keys have different types. 

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#3694]
mysql> select * from t1 left join t2 on t1.a = t2.a;
+------+------+
| a    | a    |
+------+------+
|    0 | 0.00 |
|    0 | 9.00 |
|    2 | 0.00 |
|    2 | 9.00 |
+------+------+
4 rows in set (0.00 sec)

mysql> select * from t1;
+------+
| a    |
+------+
|    0 |
|    2 |
+------+
2 rows in set (0.00 sec)

mysql> select * from t2;
+------+
| a    |
+------+
| 0.00 |
| 9.00 |
+------+
2 rows in set (0.00 sec)

Currently we only use `MergeType` to infer a common type for join keys without specified length and fsp.
We can only solve this problem after refactoring `Equal` function with cast. @XuHuaiyu

**Comment by shenli** [comment]
@hanfei1991 Is this bug already fixed?
