### ISSUE TITLE
6.2.0 results in 1.9%-14% performance regression in sysbench workloads on AWS EC2 

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#36955]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Do the same sysbench benchmark on AWS EC2 instances with the same topology shown in the document below:
https://docs.pingcap.com/tidb/dev/benchmark-sysbench-v6.1.0-vs-v6.0.0

### 2. What did you expect to see? (Required)
No performance regression.
### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/84501897/183317639-1b9bacd1-34ab-43b9-90f8-3b8994e816b4.png)

### 4. What is your TiDB version? (Required)

commit 95c715790caf02ce5867234befd35c96023c01f0

**Comment by jebter** [comment]
can it be closed？

**Comment by Yui-Song** [comment]
Another root cause for this issue is the clock source of AWS EC2 instance i3.4xlarge: https://github.com/tikv/tikv/issues/13280
