### ISSUE TITLE
tidb-lightning need to support fields starting with `_` when the import file type is parquet

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#36980]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

tidb-lightning need to support fields starting with `_` when the import file type is parquet

### 1. Minimal reproduce step (Required)
1. fields starting with `_` of parquet
2. use tidb-lightning import 

### 2. What did you expect to see? (Required)
import success 
### 3. What did you see instead (Required)
```
Root cause: PreCheckFailed: TiDB schema `test`.`tbl` doesn't have column pargo_prefix__abc, please check table schema 
```
### 4. What is your TiDB version? (Required)
tidb、tidb-lightning ：v6.1.0

**Comment by D3Hunter** [comment]
duplicate with https://github.com/pingcap/tidb/issues/36981

**Comment by glkappe** [comment]
ok i wiil close this issue

**Comment by D3Hunter** [comment]
> ok i wiil close this issue

will close automatically after pr merged

**Comment by D3Hunter** [comment]
https://github.com/xitongsys/parquet-go/blob/7a9be66324ca29f6ce14c66b239ba79c4896bf25/common/common.go#L603
