### ISSUE TITLE
Start tikv failed

### ISSUE THREAD

**Issue by 123zhaglijian** [pingcap/tidb#3700]
4台Centos 6机器，采用TiDB Binary 部署方案，进行功能性测试部署，PD正常启动，TiKV启动失败，启动参数如下：
./bin/tikv-server --pd="172.17.0.171:2379" \
                  --addr="172.17.0.172:20160" \
                  --data-dir=tikv1 \
                  --log-file=tikv.log
报错信息如下
2017/07/11 10:21:21.197 tikv-server.rs:178: [INFO] rocksdb.max-open-files use default Some(40960)
2017/07/11 10:21:21.198 tikv-server.rs:103: [ERROR] Limit("the maximum number of open file descriptors is too small, got 1024, expect greater or equal to 40960")

**Comment by ngaut** [comment]
Please ref #3282
