### ISSUE TITLE
BackupTS in br full restore summary is not backupts of the backup actually

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#37029]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Do a br restore, and check restore summary

### 2. What did you expect to see? (Required)
The BackupTS in full restore summary should be the backupts of the backup.

### 3. What did you see instead (Required)
BackupTS in full restore summary is current time instead.

![cJkQUjFz4P](https://user-images.githubusercontent.com/7403864/183890117-25aa177e-3c19-415e-bcc1-2db1f127e1a6.jpg)
![n1F2FM8Ii1](https://user-images.githubusercontent.com/7403864/183890157-82a0cb96-9cc5-46bc-afcf-0892d58e9711.jpg)

### 4. What is your TiDB version? (Required)
V6.2.0

**Comment by MoCuishle28** [comment]
I think this issue has been fixed in PR https://github.com/pingcap/tidb/pull/36281.
