### ISSUE TITLE
dont support command: show grants for user

### ISSUE THREAD

**Issue by jeff-zou** [pingcap/tidb#3703]
version: 5.7.1-TiDB-1.0

i got err when i execute this command: show grants for tidb
ERROR 1105 (HY000): line 0 column 20 near "" (total length 20)

the user tidb has many privileges, so i hope get the result like this:
grants for tidb%ip1 .....
grants for tidb%ip2 .....

**Comment by morgo** [comment]
This command now works:
```
mysql> show grants for root;
+-------------------------------------------+
| Grants for root@%                         |
+-------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' |
+-------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
Closing this issue.  Please feel free to re-open if you have further questions.  Thanks!
