### ISSUE TITLE
TiDB Ansible deploy failed

### ISSUE THREAD

**Issue by flochman** [pingcap/tidb#3708]
Hi,

I try to deploy TiDB via TiDB Ansible. I am running Debian Stretch and have regulary installed ansible.

I download TiDB Ansible from github and made config cluster topology changes to inventory.ini

I tried deploy both from root account and normal sudo account.

When I started ansible-playbook local_prepare.yml this error occured:

PLAY [do local preparation] ****************************************************

TASK [local : create downloads and resources directories] **********************
ok: [localhost] => (item=/home/vric/tidb-ansible-master/downloads)
ok: [localhost] => (item=/home/vric/tidb-ansible-master/resources)
ok: [localhost] => (item=/home/vric/tidb-ansible-master/resources/bin)

TASK [local : include_vars] ****************************************************
ok: [localhost]

TASK [local : detect outbound network] *****************************************
ok: [localhost]

TASK [local : set outbound network fact] ***************************************
ok: [localhost]

TASK [local : detect GFW] ******************************************************
ok: [localhost]

TASK [local : set GFW fact] ****************************************************
ok: [localhost]

TASK [local : download tidb binary] ********************************************

TASK [local : download other binary] *******************************************

TASK [local : download other binary under gfw] *********************************

TASK [local : unarchive tidb binary] *******************************************
failed: [localhost] (item={u'url': u'http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz', u'version': u'latest', u'name': u'tidb'}) => {"changed": true, "cmd": "ls -1 tidb-latest.tar.gz | xargs -n1 tar xzf", "delta": "0:00:00.003991", "end": "2017-07-06 07:44:12.088576", "failed": true, "item": {"name": "tidb", "url": "http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz", "version": "latest"}, "rc": 123, "start": "2017-07-06 07:44:12.084585", "stderr": "ls: cannot access 'tidb-latest.tar.gz': No such file or directory\ntar: Old option 'f' requires an argument.\nTry 'tar --help' or 'tar --usage' for more information.", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [localhost] (item={u'url': u'http://download.pingcap.org/tidb-binlog-latest-linux-amd64.tar.gz', u'version': u'latest', u'name': u'tidb-binlog'}) => {"changed": true, "cmd": "ls -1 tidb-binlog-latest.tar.gz | xargs -n1 tar xzf", "delta": "0:00:00.004073", "end": "2017-07-06 07:44:12.204142", "failed": true, "item": {"name": "tidb-binlog", "url": "http://download.pingcap.org/tidb-binlog-latest-linux-amd64.tar.gz", "version": "latest"}, "rc": 123, "start": "2017-07-06 07:44:12.200069", "stderr": "ls: cannot access 'tidb-binlog-latest.tar.gz': No such file or directory\ntar: Old option 'f' requires an argument.\nTry 'tar --help' or 'tar --usage' for more information.", "stdout": "", "stdout_lines": [], "warnings": []}
failed: [localhost] (item={u'url': u'http://download.pingcap.org/tidb-tools-latest-linux-amd64.tar.gz', u'version': u'latest', u'name': u'tidb-tools'}) => {"changed": true, "cmd": "ls -1 tidb-tools-latest.tar.gz | xargs -n1 tar xzf", "delta": "0:00:00.003713", "end": "2017-07-06 07:44:12.321707", "failed": true, "item": {"name": "tidb-tools", "url": "http://download.pingcap.org/tidb-tools-latest-linux-amd64.tar.gz", "version": "latest"}, "rc": 123, "start": "2017-07-06 07:44:12.317994", "stderr": "ls: cannot access 'tidb-tools-latest.tar.gz': No such file or directory\ntar: Old option 'f' requires an argument.\nTry 'tar --help' or 'tar --usage' for more information.", "stdout": "", "stdout_lines": [], "warnings": []}
    to retry, use: --limit @retry_files/local_prepare.retry

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1  

I also tried to download listed packages manualy and copy them to /home/vric/tidb-ansible-master/downloads  directory but nothing changed and some error ocurred.

Please help. What to do ?

Thanks.

**Comment by tisonkun** [comment]
closed as TiDB Ansible already archived https://github.com/pingcap/tidb-ansible.
