### ISSUE TITLE
scientific notation compatibility

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#3709]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

exec `select 1e18;`

2. What did you expect to see?

```
mysql> select 1e18;
+------+
| 1e18 |
+------+
| 1e18 |
+------+
1 row in set (0.00 sec)
```

3. What did you see instead?

mysql> select 1e18;
+---------------------+
| 1e18                |
+---------------------+
| 1000000000000000000 |
+---------------------+
1 row in set (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
Supplementary:

```
mysql> select 1e14;
+-----------------+
| 1e14            |
+-----------------+
| 100000000000000 |
+-----------------+
1 row in set (0.00 sec)

mysql> select 1e15;
+------+
| 1e15 |
+------+
| 1e15 |
+------+
1 row in set (0.00 sec)
```
