### ISSUE TITLE
Insert "zero" value

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#371]
`row.Next`  get the "zero" value of time (`0000-00-00 00:00:00`)
but tidb-server returns  `65535-11-30 00:00:00` to the client.

**Comment by siddontang** [comment]
Please supply more detailed information.
e,g, table structure, insert/select query.

**Comment by zimulala** [comment]
got it.

**Comment by qiuyesuifeng** [comment]
@zimulala 
Can this OR be closed?
