### ISSUE TITLE
The wrong result about `select 1 limit 0;`

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#3710]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select 1 limit 0;
```

2. What did you expect to see?
```
Empty set (0.00 sec)
```

3. What did you see instead?
```
+------+
| 1    |
+------+
|    1 |
+------+
1 row in set (0.01 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by hanfei1991** [comment]
This will be fixed in new planner.
