### ISSUE TITLE
Support distributed processing of DDL reorg phase

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#37119]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB currently supports the parallel processing of DDL jobs on the owner. However, the resources of a single TiDB are limited. Even if the parallel framework is supported, the speed of DDL execution is limited, and the competition for resources will affect the daily operations of TiDB, such as TPS.

**Describe the feature you'd like:**

At present, the time-consuming and resource-consuming phase is the reorg phase. Considering the problems that can significantly improve DDL performance and TiDB resource utilization, we will implement distributed processing in the DDL reorg phase.

Feature branch: [distribute-reorg](https://github.com/pingcap/tidb/tree/feature/distribute-reorg)

##### Tech design
- [x] #37129
##### Development Plan
- Step 1（sprint 11-12） 
  - [x] #37120
  - [x] #37122
  - [x] #37124
  - [x]  Do demo and simple performance test

- Step 2 （sprint 13）
  - [x] #37123
  - [x] #37125
    - [x] Lighting accelerates Add Index adaptation
  - [ ] #37172
  - [x] #37127
  - [x] #41002
  - [x] #41144
  - [x] #41266
  - [ ] Test-related work
  
- Step 3（sprint 14）
  - [ ] #40298
  - [ ] #40933
  - [ ] Support distributed processing `LitMerge` in the `BackfillStateMerging`
  - [ ] Compatible with `admin cancel ddl jobs`
  - [ ] Compatible with the correct error and warning messages for DDL
  - [ ] Improved sync mode of txn-merge and lit-merge
  - [ ] Compatible with DDL retry methods (control retries based on `tidb_ddl_error_count_limit`)
  - [ ] Specification dist-reorg related log
  - [ ] Performance tuning
  - [ ] #37128
  - [ ] #38686
 
 - Step 4
  - Backfill processes the Backfill job scheduling policy, `Admin show DDL jobs` supports reorg progress display, get rid of the DDL owner design, etc.

- Related Issues
  - [x] #41106
  - [x] #41208
  - [x] https://github.com/pingcap/tidb/issues/41371
  - [x] #41576
  - [x] #42176
  - [x] #42199
- Unified table structure related issues
  - [x] https://github.com/pingcap/tidb/issues/41579
  - [x] https://github.com/pingcap/tidb/issues/42175

***Note***
Above sprint information is not delievery plan，this indicate dev time schedule，Maybe changed according real project situation

**Comment by YangKeao** [comment]
Will it notify the workers after inserting tasks into the table? Or just waiting for the workers to poll the table?

I'm implementing this for TTL (in https://github.com/pingcap/tidb/pull/40705) , maybe we should also consider this in the unified worker framework :thinking:

**Comment by zimulala** [comment]
> Will it notify the workers after inserting tasks into the table? Or just waiting for the workers to poll the table?
> 
> I'm implementing this for TTL (in #40705) , maybe we should also consider this in the unified worker framework 🤔

We do notify in https://github.com/pingcap/tidb/pull/40542/files#diff-a185df836b8926c4afe351d4def1b56d1e282c65aabe6677c2fa2c54590cc4b2R1063.

**Comment by YangKeao** [comment]
> > Will it notify the workers after inserting tasks into the table? Or just waiting for the workers to poll the table?
> > I'm implementing this for TTL (in #40705) , maybe we should also consider this in the unified worker framework thinking
> 
> We do notify in https://github.com/pingcap/tidb/pull/40542/files#diff-a185df836b8926c4afe351d4def1b56d1e282c65aabe6677c2fa2c54590cc4b2R1063.

Good. Thanks for pointing out. I think what I actually need (and how TTL's currently implemented) is something like `addingBackfillJob` :+1: .
