### ISSUE TITLE
run-ddl should be marked as removed

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#37185]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is a small cleanup required after https://github.com/pingcap/tidb/pull/35425

The run-ddl option is still present in tidb_config:
```sql
mysql> select @@tidb_config\G
*************************** 1. row ***************************
@@tidb_config: {
..
	"index-limit": 64,
	"instance": {
..
		"tidb_enable_ddl": true,
..
	},
..
	"run-ddl": true,
..
}
1 row in set (0.01 sec)
```

With other variables converted to instance scope, the previous usage has been marked as removed, so it patches out of @@tidb_config.

### 2. What did you expect to see? (Required)

There should be a line for run-ddl in this list:
https://github.com/pingcap/tidb/blob/9709249e523a92cf635ab330f6e2a0ef77a0843a/config/config.go#L990-L1039

### 3. What did you see instead (Required)

See above

### 4. What is your TiDB version? (Required)

master

**Comment by morgo** [comment]
@CbcWestwolf this is a small cleanup, did you mind taking a look?

**Comment by CbcWestwolf** [comment]
> did you mind taking a look?

Sure!
