### ISSUE TITLE
Column count doesn't match value count when executing insert SQL using prepare + execute 

### ISSUE THREAD

**Issue by Damon-Guo** [pingcap/tidb#37187]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table t1 (a int(11) ,b varchar(100) ,primary key (a));
create table t2 (c int(11) ,d varchar(100) ,primary key (c));
prepare in1 from "insert into t1 (a,b) select c,null from t2 t on duplicate key update b=t.d" ;
execute in1 ;

### 2. What did you expect to see? (Required)
![a972ceb77a6fb7cf1874a2d89715cc2](https://user-images.githubusercontent.com/50732087/185281549-558ff1f1-9c02-421d-82ab-6bbb07f75498.jpg)

### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/50732087/185281629-57574730-8b5f-41ab-8574-15566e8d1ffb.png)

### 4. What is your TiDB version? (Required)
v5.3.2
v6.1.0

**Comment by Reminiscent** [comment]
related to https://github.com/pingcap/tidb/pull/14412
