### ISSUE TITLE
sysvar: change the default value of `tidb_partition_prune_mode` to `'dynamic'`

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#37237]
## Enhancement

Currently, TiDB supports two kinds of [pruning modes](https://docs.pingcap.com/tidb/dev/partitioned-table#dynamic-pruning-mode) for table partitions. We plan to set "dynamic pruning" mode to the default one since the performance is better and it is stable enough.

**Comment by mjonss** [comment]
This should be done after https://github.com/pingcap/tidb/issues/33031 has been fixed and https://github.com/pingcap/tidb/pull/33098 is reverted.

**Comment by mjonss** [comment]
Done in https://github.com/pingcap/tidb/pull/37712 .
