### ISSUE TITLE
DM - refine the logic of adding indexes

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#37276]
In optimistic mode, the non-unique index behavior remains the same as add column, that is, when one sub-table finishes executing ddl, the combined table can be applied instead of waiting until all sub-tables are executed.

**Comment by glkappe** [comment]
For lossy changes, all sub-tables must be executed before they can be synchronized

**Comment by bb7133** [comment]
@glkappe Could you follow the 'bug report' format to describe this issue with more details? For example, what does 'sub-table' mean? What is the minimum reproduction of the bug?

**Comment by glkappe** [comment]
@bb7133  This is the logic optimization of ddl processing by dm in different modes, not tidb-server. The sub-task here actually refers to one of the multiple tables in the upstream mysql that need to be merged.

**Comment by glkappe** [comment]
move to https://github.com/pingcap/tiflow/issues/6862
