### ISSUE TITLE
JSON document does not report error even exceeds the maximum depth.

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#37292]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
select json_valid(repeat('[', 1000));
Error 3157: The JSON document exceeds the maximum depth.
```

### 2. What did you expect to see? (Required)

```
Error 3157: The JSON document exceeds the maximum depth.
```

### 3. What did you see instead (Required)

```
0
```

**Comment by windtalker** [comment]
There is a hard limit of max depth(100) of json type in [MySQL](https://github.com/mysql/mysql-server/blob/mysql-cluster-8.0.25/sql/json_syntax_check.cc#L80), while TiDB does not have such limits, so TiDB does not throw error. 
I think it should be a moderate or minor bug.

**Comment by YangKeao** [comment]
See https://github.com/golang/go/issues/31789

The standard library of golang has a default max depth for 10000, (but as I know, it doesn't provide a way to specify the depth). We can verify this limitation through:

In TiDB:

```
MySQL [test]> select json_valid(concat(repeat('[', 1001), repeat(']', 10001)));
+-----------------------------------------------------------+
| json_valid(concat(repeat('[', 1001), repeat(']', 10001))) |
+-----------------------------------------------------------+
|                                                         0 |
+-----------------------------------------------------------+
1 row in set (0.001 sec)

MySQL [test]> select json_valid(concat(repeat('[', 10001), repeat(']', 10001)));
+------------------------------------------------------------+
| json_valid(concat(repeat('[', 10001), repeat(']', 10001))) |
+------------------------------------------------------------+
|                                                          0 |
+------------------------------------------------------------+
1 row in set (0.001 sec)
```

See https://github.com/serde-rs/json/issues/162

The default recursion depth used in TiKV is 128 (by default), which is so different from the TiDB. Also, it's not configurable, but this limitation can be turned off: https://docs.rs/serde_json/latest/serde_json/struct.Deserializer.html#method.disable_recursion_limit .

**Comment by YangKeao** [comment]
We could handle this special error everywhere, if it's needed.
