### ISSUE TITLE
MySQL consume more storage for json type than tidb

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#37307]
## General Question

```sql
CREATE TABLE t (j JSON);
INSERT INTO t (j) VALUES('[1,2,3,4]');
INSERT INTO t (j) VALUES('[1]');
select JSON_STORAGE_SIZE(j) from t;
```

MySQL consume more storage for json type, I wonder if it is expected

**Comment by YangKeao** [comment]
> This function returns the number of bytes used to store the binary representation of a JSON document.

However, the implemenation in TiDB returns the length of json string (the result of `marshalTo`). I don't think it's expected. I'll submit a PR to modify it to return the size of `JSONBinary` :thinking:
