### ISSUE TITLE
*: better error message for `ADMIN CHECK/RECOVER/CLEANUP INDEX`

### ISSUE THREAD

**Issue by bb7133** [pingcap/tidb#37323]
## Enhancement

When a table is defined with clustered index, the 'primary key' does not exist actually(primary key = record), so for syntax like `ADMIN CHECK INDEX xxx `primary``, a better error message would be better:

Current:
```
tidb> create table t(a int key clustered);
tidb> admin recover index t `primary`;
ERROR 1105 (HY000): index `primary` is not found in table `t`
```

Not every user knows the definition of "clustered index", we could report another message like:

```
ERROR 1105 (HY000): index `primary` is not defined in table `t` when the clustered index is defined.
```

**Comment by azhsmesos** [comment]
please assigned it to me, i want to try it

**Comment by azhsmesos** [comment]
sorry，please assigned to @measutosh ，I've been really busy these days and I'm sorry
