### ISSUE TITLE
[Lightning]: Panic on invalid Mertic countter operation

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tidb#37338]
## Bug Report

Version: 6.1.0

Lightning panic on https://github.com/pingcap/tidb/blob/master/br/pkg/lightning/restore/restore.go#L2333

I think it's because float64(currOffset - startOffset) < 0.

```log
panic: counter cannot decrease in value

goroutine 202374 [running]:
github.com/prometheus/client_golang/prometheus.(*counter).Add(0x0?, 0xc069674c80?)
/go/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/counter.go:109 +0xf4
github.com/pingcap/tidb/br/pkg/lightning/restore.(*chunkRestore).deliverLoop(0xc0618805a0,
{0x445dbd8, 0xc0017c6040}

, 0xc06c80a3c0, 0xc0012af740, 0x3, 0xc002a8ff18?, 0xc002a8ffd0?, 0xc0016e5080)
/mnt/tidb/sql/br/pkg/lightning/restore/restore.go:2255 +0x7a3
github.com/pingcap/tidb/br/pkg/lightning/restore.(*chunkRestore).restore.func1()
/mnt/tidb/sql/br/pkg/lightning/restore/restore.go:2509 +0xab
created by github.com/pingcap/tidb/br/pkg/lightning/restore.(*chunkRestore).restore
/mnt/tidb/sql/br/pkg/lightning/restore/restore.go:2507 +0x31b
```

**Comment by D3Hunter** [comment]
value of `currOffset` comes from `parser.pos` which increase monotonically. the init value of `parser.pos` comes from `chunk.Chunk.Offset` which is the value of `startOffset`. so it should happen that `currOffset - startOffset < 0`

need to reproduce it.

**Comment by D3Hunter** [comment]
user changed lightning code, cannot find code related to hash b3ee7aef716e39dd5c6744e4dac0fbbb3529aca7

not sure  the root cause is from 6.1 code base or from user's customization

**Comment by D3Hunter** [comment]
update: the error happens when importing fixed-width text format file, not csv but pretend it as csv. in the datafile there're binary data which contains csv terminator which causes error.

cannot reproduce it now.

**Comment by lance6716** [comment]
Reproduced in a ONCALL ticket

**Comment by lance6716** [comment]
I printed `newOffset` and `cr.chunk.Chunk.EndOffset`

https://github.com/pingcap/tidb/blob/07508df51fbc35234573bf325f5e5c1f28954a5a/lightning/pkg/importer/chunk_process.go#L487

there's an off-by-1 error, the chunk reader does not stop

```
[2024/05/21 15:55:36.744 +08:00] [INFO] [chunk_process.go:485] ["lance test3"] [table=`test`.`gla_glis_quarter`] [engineNumber=0] [fileIndex=7] [path=test.gla_glis_quarter.csv:469762831] [offset=536871695] [EndOffset=536871696]
...
[2024/05/21 15:55:36.744 +08:00] [INFO] [chunk_process.go:485] ["lance test3"] [table=`test`.`gla_glis_quarter`] [engineNumber=0] [fileIndex=7] [path=test.gla_glis_quarter.csv:469762831] [offset=536871902] [EndOffset=536871696]
```

**Comment by lance6716** [comment]
root cause:

when strict-format = true, we try to seek every 256MiB and read the next line terminator as the chunk end position

https://github.com/pingcap/tidb/blob/aeafb18f3a7c1457172dc50ffcb5ad5f29e9fd7d/pkg/lightning/mydump/region.go#L455-L458

But unfortunately we seek to `\r` and `ReadUntilTerminator` then found `\n`. So end position of a chunk is set to `\n`. But elsewhere we use `\r` as the position. This causes the off-by-1 error
