### ISSUE TITLE
parser test failed on mac

### ISSUE THREAD

**Issue by yupengfei** [pingcap/tidb#3734]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I run 
go get github.com/pingcap/tidb
make parser
cd parser
go test parser_test.go

2. What did you expect to see?

I think test should pass

3. What did you see instead?

# command-line-arguments
./parser_test.go:41: undefined: New
./parser_test.go:184: undefined: New
./parser_test.go:477: undefined: New
./parser_test.go:489: undefined: New
./parser_test.go:1333: undefined: New
./parser_test.go:1570: undefined: New
./parser_test.go:1595: undefined: New
./parser_test.go:1607: undefined: New
./parser_test.go:1636: undefined: New
./parser_test.go:1686: undefined: New
./parser_test.go:1686: too many errors
FAIL	command-line-arguments [build failed]

4. What version of TiDB are you using (`tidb-server -V`)?

I get it today.

**Comment by breeswish** [comment]
Try:

```bash
cd src/github.com/pingcap/tidb
go test github.com/pingcap/tidb/parser -v
```

**Comment by tiancaiamao** [comment]
`go test .` instead of `go test parser_test.go`
