### ISSUE TITLE
【v6.1.0 vs v6.1.1 发版测试】tpc-ds 50G 的负载 发现多个 query 延迟上升幅度明显，执行计划改变，估算偏差大

### ISSUE THREAD

**Issue by shaoxiqian** [pingcap/tidb#37381]
tpc-ds 50G 的负载 发现多个 query 延迟上升幅度明显，执行计划不一致的情况
以 Q95 为例 v6.1.1 的 total 延迟 比 6.1.0 高出 35.7秒，且估算偏差挺大

执行计划截图：
![origin_img_v2_f698f8aa-0926-46bd-9c16-c1e5082b2e7g](https://user-images.githubusercontent.com/85105033/186601270-66b5783b-1fba-4ef1-8a80-bb16ccce8b10.jpg)

query:https://github.com/PingCAP-QE/perftest/blob/master/bench-toolset/tpcds50/query_95.sql
v6.1.0 执行计划：http://172.16.6.48:8030/plan_diff/plan/3000008/QUERY_95/benchbot/
v6.2.0 执行计划：http://172.16.6.48:8030/plan_diff/plan/2970004/QUERY_95/benchbot/

**Comment by Yisaer** [comment]
duplciated with https://github.com/pingcap/tidb/issues/36552
