### ISSUE TITLE
No IndexInfo for integer primary key?

### ISSUE THREAD

**Issue by huangjunwen** [pingcap/tidb#3746]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I'm writing a tool similar to [xo](https://github.com/knq/xo). By using tidb (in memory store) for SQL parsing and execution, I can extract database and SQL query meta information, then render templates into wrapper code. Everything so far is good until I found that `model.TableInfo.Indices` doesn't contain the primary index if the primary index contains only one integer field. 

These are the test cases:
```
CREATE TABLE user1 (
    id int AUTO_INCREMENT,
    id2 int,
    primary key (id, id2)
);

CREATE TABLE user2 (
    id varchar(32),
    primary key (id)
);

CREATE TABLE user3 (
    id float,
    primary key (id)
);

CREATE TABLE user4 (
    id int,
    primary key (id)
);

CREATE TABLE user5 (
    id int AUTO_INCREMENT,
    primary key (id)
);
```

2. What did you expect to see?
All 5 tables' `Indices` should contain the primary index

3. What did you see instead?
Only user1/user2/user3 contain the primary index

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: eea5cb22372b07b3e3b897dea705368c0361d668
UTC Build Time:  2017-06-26 06:43:27

**Comment by winoros** [comment]
Yes, integer primary key don't appear in the indicies, because it behaves different with other primary key and indicies in tidb with tikv.
If you want to get it. You can first check `model.TableInfo.PkIsHandle` then use TableInfo.GetPkColInfo to get the primary key column.

**Comment by huangjunwen** [comment]
I got it. Thank you :-)

**Comment by winoros** [comment]
My pleasure. Is there any problem?

**Comment by huangjunwen** [comment]
暂时没有了，谢谢～
