### ISSUE TITLE
Access control and privileges check use diffrent host when USER table has same username

### ISSUE THREAD

**Issue by wuliLSF** [pingcap/tidb#37488]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1.
mysql -uroot -p -h192.168.13.15 -P4000
create user dba_test@’%’ identified by ‘123456’;
GRANT SELECT,INSERT,UPDATE,DELETE ON test.* TO ‘dba_test’@’%’;
create user dba_test@‘192.168.%’ identified by ‘654321’;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER ON test.* TO ‘dba_test’@‘192.168.%’;

2.
mysql -udba_test -p654321 -h192.168.13.15 -P4000
MySQL [(none)]> use test;
Database changed
MySQL [test]> DROP TABLE IF EXISTS a;
ERROR 1142 (42000): DROP command denied to user ‘dba_test’@‘192.168.%’ for table ‘a’

3.
mysql -uroot -p -h192.168.13.15 -P4000
MySQL [(none)]> drop user dba_test@'%';
Query OK, 0 rows affected (0.23 sec)

4.
mysql -udba_test -p654321 -h192.168.13.15 -P4000
MySQL [(none)]> use test;
Database changed
MySQL [test]> DROP TABLE IF EXISTS a;
Query OK, 0 rows affected, 1 warning (0.01 sec)

### 2. What did you expect to see? (Required)
MySQL [test]> DROP TABLE IF EXISTS a;
Query OK, 0 rows affected, 1 warning (0.01 sec)

### 3. What did you see instead (Required)
MySQL [test]> DROP TABLE IF EXISTS a;
ERROR 1142 (42000): DROP command denied to user ‘dba_test’@‘192.168.%’ for table ‘a’

### 4. What is your TiDB version? (Required)
v5.4.1,v6.1.0

**Comment by zimulala** [comment]
PTAL @tiancaiamao
