### ISSUE TITLE
flash back time is equal to gc time, error message is not correct

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#37497]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
MySQL [(none)]> flashback cluster as of timestamp '22/08/30 10';
ERROR 8055 (HY000): snapshot is older than GC safe point 2022-08-30 11:53:18 +0800 CST
MySQL [(none)]> flashback cluster as of timestamp '2022-08-30 11:53:18';
ERROR 9006 (HY000): GC life time is shorter than transaction duration, transaction starts at 2022-08-30 11:53:18 +0800 CST, GC safe point is 2022-08-30 11:53:18.751 +0800 CST
MySQL [(none)]>
```

### 2. What did you expect to see? (Required)
return success or snapshot is older than GC safe point xxx

### 3. What did you see instead (Required)
error message does not make sense

### 4. What is your TiDB version? (Required)

flashback patch

**Comment by Defined2014** [comment]
The root cause is that we save GC time in both TiKV and PD, but they are different. In PD the precision is milliseconds, but in TiKV it is seconds.
