### ISSUE TITLE
`json_unquote` and `like` operator has different behavior after pushing down to TiKV

### ISSUE THREAD

**Issue by YangKeao** [pingcap/tidb#37501]
## Enhancement

```
create table t (i INT, j JSON);
insert into t values(3, cast(X'ABCD' as JSON));
select i from t where json_unquote(j) like 'base64:type253:q80=';
```

It returns empty with tikv store, but in MySQL (`base64:type16:q80=`) and TiDB unistore, it gives `3`

**Comment by xiongjiwei** [comment]
```sql
mysql root@localhost:test> select json_unquote(cast(X'ABCD' as JSON)) like 'base64:type253:q80=';
+----------------------------------------------------------------+
| json_unquote(cast(X'ABCD' as JSON)) like 'base64:type253:q80=' |
+----------------------------------------------------------------+
| 0                                                              |
+----------------------------------------------------------------+
```

**Comment by YangKeao** [comment]
> ```sql
> mysql root@localhost:test> select json_unquote(cast(X'ABCD' as JSON)) like 'base64:type253:q80=';
> +----------------------------------------------------------------+
> | json_unquote(cast(X'ABCD' as JSON)) like 'base64:type253:q80=' |
> +----------------------------------------------------------------+
> | 0                                                              |
> +----------------------------------------------------------------+
> ```

It's because the projection is not pushed down?

**Comment by xiongjiwei** [comment]
it is mysql8.0 result

**Comment by YangKeao** [comment]
> it is mysql8.0 result

Use `base64:type16:q80=` for MySQL? As the type code has a little difference

**Comment by xiongjiwei** [comment]
I see
