### ISSUE TITLE
DB level placement policy not works

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#37556]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
MySQL [test]> CREATE PLACEMENT POLICY primary_east PRIMARY_REGION="us-east-1" REGIONS="us-east-1,us-east-2,us-west-1";
MySQL [test]> ALTER DATABASE test PLACEMENT POLICY primary_east;
MySQL [test]> show placement;
+---------------------+--------------------------------------------------------------------+------------------+
| Target              | Placement                                                          | Scheduling_State |
+---------------------+--------------------------------------------------------------------+------------------+
| POLICY primary_east | PRIMARY_REGION="us-east-1" REGIONS="us-east-1,us-east-2,us-west-1" | NULL             |
| DATABASE test       | PRIMARY_REGION="us-east-1" REGIONS="us-east-1,us-east-2,us-west-1" | SCHEDULED        |
+---------------------+--------------------------------------------------------------------+------------------+
2 rows in set (0.01 sec)
```
But no scheduling: 
![image](https://user-images.githubusercontent.com/6428910/188053318-e81f16e6-32f2-4e13-bdb7-1a50aebfa029.png)

And no relative rule in PD:
![image](https://user-images.githubusercontent.com/6428910/188053402-f0341e41-041f-44dd-a0fa-f116bb249c14.png)

### 2. What did you expect to see? (Required)
PD should have the rule and all-region leaders of DB test location in store_id 1.

### 3. What did you see instead (Required)
no scheduling

### 4. What is your TiDB version? (Required)
MySQL [information_schema]> select type,version,git_hash from CLUSTER_INFO;
+------+---------+------------------------------------------+
| type | version | git_hash                                 |
+------+---------+------------------------------------------+
| tidb | 6.1.0   | 1a89decdb192cbdce6a7b0020d71128bc964d30f |
| pd   | 6.1.0   | d82f4fab6cf37cd1eca9c3574984e12a7ae27c42 |
| pd   | 6.1.0   | d82f4fab6cf37cd1eca9c3574984e12a7ae27c42 |
| pd   | 6.1.0   | d82f4fab6cf37cd1eca9c3574984e12a7ae27c42 |
| tikv | 6.1.0   | 080d086832ae5ce2495352dccaf8df5d40f30687 |
| tikv | 6.1.0   | 080d086832ae5ce2495352dccaf8df5d40f30687 |
| tikv | 6.1.0   | 080d086832ae5ce2495352dccaf8df5d40f30687 |
+------+---------+------------------------------------------+

**Comment by xhebox** [comment]
It is not a bug. Policy is inherited from the database **only at the creation**. That said, changing the default policy of the database won't affect existed tables. You should try to alter the policy of these tables, instead.
