### ISSUE TITLE
ebs restore failed

### ISSUE THREAD

**Issue by XuJianxu** [pingcap/tidb#37581]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

ebs backup to s3
try to restore

### 2. What did you expect to see? (Required)
restore success

### 3. What did you see instead (Required)
Below error happened
I0902 14:54:33.703400       9 restore.go:244] [2022/09/02 14:54:33.703 +00:00] [INFO] [base_client.go:378] ["[pd] switch leader"] [new-leader=http://basic-pd-0.basic-pd-peer.tidb-cluster.svc:2379/] [old-leader=]
I0902 14:54:33.703492       9 restore.go:244] [2022/09/02 14:54:33.703 +00:00] [INFO] [base_client.go:105] ["[pd] init cluster id"] [cluster-id=7138795429752494907]
I0902 14:54:33.703573       9 restore.go:244] [2022/09/02 14:54:33.703 +00:00] [INFO] [client.go:690] ["[pd] tso dispatcher created"] [dc-location=global]
I0902 14:54:33.734761       9 restore.go:244] [2022/09/02 14:54:33.734 +00:00] [INFO] [restore_ebs_meta.go:216] ["starting to remove some PD schedulers"]
I0902 14:54:33.736319       9 restore.go:244] [2022/09/02 14:54:33.736 +00:00] [INFO] [collector.go:246] ["EBS restore failed, please check the log for details."]
I0902 14:54:33.738403       9 restore.go:244] 
E0902 14:54:33.738557       9 manager.go:287] restore cluster tidb-cluster/rt-ebs from ebs failed, err: cluster tidb-cluster/rt-ebs, the CSB file not found, path: /var/lib/br-bin/csb_restore.json
E0902 14:54:33.746309       9 restore_status_updater.go:81] Failed to update resotre [tidb-cluster/rt-ebs], error: Operation cannot be fulfilled on [restores.pingcap.com](http://restores.pingcap.com/) "rt-ebs": the object has been modified; please apply your changes to the latest version and try again
I0902 14:54:33.768643       9 restore_status_updater.go:78] Restore: [tidb-cluster/rt-ebs] updated successfully
error: cluster tidb-cluster/rt-ebs, the CSB file not found, path: /var/lib/br-bin/csb_restore.json

### 4. What is your TiDB version? (Required)
nightly

**Comment by fengou1** [comment]
during the 1st restore, BR tried to stop the PD scheduler, however, it is meaningless since PD is not bootstrapped. we already test the issue, and it never happen.
