### ISSUE TITLE
tidb_enforce_mpp flag doesn't take effect

### ISSUE THREAD

**Issue by yibin87** [pingcap/tidb#37608]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table t(a int,b date);
insert into t values(1,"2020-10-10");
alter table t set tiflash replica 1;
set @@tidb_enforce_mpp=on;
explain select ifnull(max(b) = max('08:45:16'), count(a)) from t; -- 1

### 2. What did you expect to see? (Required)
max and count function pushed down to tiflash

### 3. What did you see instead (Required)
max and count function not pushed down to tiflash:
mysql> explain select ifnull(max(b) = max('08:45:16'), count(a)) from t;
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
| id                         | estRows | task      | access object | operator info                                                                                   |
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
| Projection_4               | 1.00    | root      |               | ifnull(eq(Column#4, cast(Column#5, datetime(6) BINARY)), Column#6)->Column#7                    |
| └─StreamAgg_11             | 1.00    | root      |               | funcs:max(test.t.b)->Column#4, funcs:max("08:45:16")->Column#5, funcs:count(test.t.a)->Column#6 |
|   └─TableReader_17         | 1.00    | root      |               | data:TableFullScan_16                                                                           |
|     └─TableFullScan_16     | 1.00    | cop[tikv] | table:t       | keep order:false, stats:pseudo                                                                  |
+----------------------------+---------+-----------+---------------+-------------------------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
### 4. What is your TiDB version? (Required)
| Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 21847fe58b51807696debf0f7650af948f2aa3e2
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-08-22 14:26:16
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by aytrack** [comment]
can not reproduce on master
```sql
MySQL root@127.0.0.1:test> create table t(a int,b date);
                       ->  insert into t values(1,"2020-10-10");
                       ->  alter table t set tiflash replica 1;
                       ->  select sleep(5);
                       ->  set @@tidb_enforce_mpp=on;
                       ->  explain select ifnull(max(b) = max('08:45:16'), count(a)) from t; -- 1
Query OK, 0 rows affected
Time: 0.107s

Query OK, 1 row affected
Time: 0.054s

Query OK, 0 rows affected
Time: 0.174s

+----------+
| sleep(5) |
+----------+
| 0        |
+----------+

1 row in set
Time: 5.030s

Query OK, 0 rows affected
Time: 0.001s

+----------------------------+----------+--------------+---------------+----------------------------------------------------------------------------------------------------+
| id                         | estRows  | task         | access object | operator info                                                                                      |
+----------------------------+----------+--------------+---------------+----------------------------------------------------------------------------------------------------+
| Projection_4               | 1.00     | root         |               | ifnull(eq(Column#4, cast(Column#5, datetime(6) BINARY)), Column#6)->Column#7                       |
| └─HashAgg_21               | 1.00     | root         |               | funcs:max(Column#12)->Column#4, funcs:max(Column#13)->Column#5, funcs:count(Column#14)->Column#6   |
|   └─TableReader_23         | 1.00     | root         |               | data:ExchangeSender_22                                                                             |
|     └─ExchangeSender_22    | 1.00     | mpp[tiflash] |               | ExchangeType: PassThrough                                                                          |
|       └─HashAgg_9          | 1.00     | mpp[tiflash] |               | funcs:max(test.t.b)->Column#12, funcs:max("08:45:16")->Column#13, funcs:count(test.t.a)->Column#14 |
|         └─TableFullScan_20 | 10000.00 | mpp[tiflash] | table:t       | keep order:false, stats:pseudo                                                                     |
+----------------------------+----------+--------------+---------------+----------------------------------------------------------------------------------------------------+

MySQL root@127.0.0.1:test> select tidb_version()\G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v6.3.0-alpha
Edition: Community
Git Commit Hash: 331707cfdc83d6bf856c675294a29718728b80c4
Git Branch: heads/refs/tags/v6.3.0-alpha
UTC Build Time: 2022-09-04 14:26:38
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

1 row in set
```

**Comment by jebter** [comment]
Please try the latest version. I will close it,if there are any updates, you can reopen it.
