### ISSUE TITLE
WHY the batch dml feature will be discarded?

### ISSUE THREAD

**Issue by L-maple** [pingcap/tidb#37660]
## General Question

I noticed the document below mentions TiDB will discard batch dml in the future because of its instability.
https://docs.pingcap.com/tidb/dev/non-transactional-dml#comparison-with-batch-dml

But I cannot imagine the circumstance (record inconsistent with index) in which this instability would happen.

Can somebody give me a NICE example when this bad case  happens?

**Comment by L-maple** [comment]
Hope a nice guy give me an answer or explanation :)

**Comment by L-maple** [comment]
@tiancaiamao

**Comment by tiancaiamao** [comment]
> But I cannot imagine the circumstance (record inconsistent with index) in which this instability would happen.
> Can somebody give me a NICE example when this bad case happens?

Batch DML work by split the data of a transaction into multiple pieces.
There is no transaction guarantee for it --- all success or all fail
Without the transaction atomic guaranteeing, it might fail in the middle of processing,
some data success and some not, **leaving a dirty state**.

People should avoid using it, or rethink the risk carefully.
Now that we have introduce some other feature to replace it, we'll make it deprecated in the future.

**Comment by L-maple** [comment]
> 

I understand it. But I have the following three questions:
1) Non-transaction-dml also has no atomic guaranteeing, and is almost the same as batch-dml. so I desire to know why we prefer non-transaction-dml to batch-dml in v6.1.0, just because it's user-friendly?
2) Besides, when we want to delete dozens of GBs, batch-dml is actually much better.  The reason is that the data volume for non-transactional-dml gives the SQL rather heavy burdens, even OOM. So how to use non-transactional-dml gracefully for large volume?
3) Lastly, CRDB implements bulk-delete in a different manner, which adds a RETURNING clause for DELETE statement. Have we ever considered it or compared non-transactional-dml with it?

**Comment by ekexium** [comment]
> The reason is that the data volume for non-transactional-dml gives the SQL rather heavy burdens

Have you met OOM issue on non-transactional DMLs? Can I ask your batch size when you use it? I suppose it shouldn't use much more memory than a single split SQL. 

> @ekexium do you known how CRDB do it and can we learn from them?

I'm not quite familiar with CRDB. It seems to me the `RETURNING` clause is to return the rows that are deleted. How does it help batch delete? Could you help illustrate a bit more about it?
I've checked their [bulk delete data](https://www.cockroachlabs.com/docs/v22.1/bulk-delete-data.html) suggestions. In essence that is similar to (if not same as) non-transactional DML in TiDB. The only difference is TiDB make it a built-in functionality for ease of use IMO.

**Comment by L-maple** [comment]
@ekexium @tiancaiamao  Happy Mid-Autumn Festival~  
I viewed batch-dml and non-transactional dml code and still have some confuses:
>  If you never encounter that, you won't see how important it is to avoid inconsistent data. 
1. In batch-dml implementation, the record row and its related index rows are deleted in the same split txn. Why broken data would happen?
> Have you met OOM issue on non-transactional DMLs?
2. I haven't yet met OOM. But batch-dml and non-transactional dml both scan all related rows first, and then split them into txns or jobs. If the scanned data is large enough(the data volumn satisfying the where clause is big), I think SQL may be OOM.
> The only difference is TiDB make it a built-in functionality for ease of use IMO.
3.  Though not important, what is `IMO`?

**Comment by ekexium** [comment]
> In batch-dml implementation, the record row and its related index rows are deleted in the same split txn. Why broken data would happen?

In short, the timestamp used to read data is different from the start_ts in the commit phase. Thus concurrent write may corrupt data. Note that when a row is modified, the row key is unchanged but index keys can be different.

> I haven't yet met OOM. But batch-dml and non-transactional dml both scan all related rows first, and then split them into txns or jobs. If the scanned data is large enough(the data volumn satisfying the where clause is big), I think SQL may be OOM.

Non-transactional DMLs only store boundries of split ranges in memory, and do not store all rows.

> Though not important, what is IMO?

Abbreviation for in my opinion.

**Comment by L-maple** [comment]
@ekexium @tiancaiamao  Thanks very much for your reply! Maybe we can parallel jobs of non-trantractional dml for better performance  in the future.

**Comment by ekexium** [comment]
Yes I've considered that. However it's not easy to implement it. See https://github.com/pingcap/tidb/blob/1f611c109ed581bc646db4cb7d5695697a507bea/docs/design/2022-03-25-non-transactional-dml.md?plain=1#L75

**Comment by L-maple** [comment]
Why not fetch, for example, four internal sessions to parallel the jobs? Is there any problems?

**Comment by ekexium** [comment]
Internal sessions are handled differently from user sessions. So it's not a good idea to use them.
