### ISSUE TITLE
wrong query result when when the query condition is varchar equals lecture number

### ISSUE THREAD

**Issue by fengleicn** [pingcap/tidb#37664]
![origin_img_v2_88a85645-60a9-4660-b24c-fb5114c7cf9g](https://user-images.githubusercontent.com/9327268/188819954-39bb7522-864d-4253-8a23-bc08a62a0516.jpg)

CREATE TABLE `device_delta_collect` (
       `reportTime` varchar(255) DEFAULT NULL,
       `deviceId` varchar(255) DEFAULT NULL,
       `multiple` varchar(255) DEFAULT NULL,
       `deltaJgs` varchar(255) DEFAULT NULL,
        KEY `device_delta_collect_deviceId_index` (`deviceId`),
        KEY `device_delta_collect_reportTime_index` (`reportTime`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

**Comment by atidat** [comment]
following...

**Comment by fengleicn** [comment]
close了 重新提了个bug
