### ISSUE TITLE
very difficult to find sharding information or where to understand the internal mechanics of how sharding works

### ISSUE THREAD

**Issue by vipsland** [pingcap/tidb#37672]
1. very difficult to find sharding information (configuration options)
2. where to understand the internal mechanics of how sharding works? are there a few ways to shard?
3. how does sharding work? by primary key or...? can we do the setting?

**Comment by ljluestc** [comment]
Understanding Sharding Mechanics in TiDB:

To understand how sharding works in TiDB and its internal mechanics, you can follow these steps:

a. TiDB Documentation: Start by referring to the [TiDB Architecture](https://docs.pingcap.com/tidb/stable/architecture-overview) section in the official documentation. This will give you an overview of how TiDB handles sharding and distribution of data.

b. Source Code Exploration: If you want to delve deeper into the implementation, you can explore the [TiDB GitHub repository](https://github.com/pingcap/tidb). Look for components related to sharding, such as the storage layer, data distribution logic, and query processing.

c. Community Resources: Engage with the TiDB community through forums, mailing lists, and discussion boards. You can find valuable insights from experienced users and contributors who can provide practical insights into sharding.

Sharding Methods in TiDB:

TiDB primarily uses range sharding, where data is divided into ranges based on primary key ranges. However, TiDB also supports hash sharding and composite sharding through its flexible sharding strategy configuration.

How Sharding Works in TiDB:

In TiDB, sharding is based on the primary key by default. Each table is divided into smaller ranges of primary key values, and these ranges are assigned to different TiKV (distributed Key-Value store) nodes. TiDB's Query Router then routes queries to the appropriate TiKV nodes based on the primary key.

TiDB also allows customizing sharding strategies by using the SHARD_ROW_ID_BITS configuration. This configuration determines the number of bits used from the primary key to determine the shard ID. This way, you can control the granularity of sharding and balance the distribution of data.
