### ISSUE TITLE
any crash recovery stuff? difficult to find online though i hvnt try crashing it yet. just wondering how to recover.

### ISSUE THREAD

**Issue by vipsland** [pingcap/tidb#37676]
any crash recovery stuff? difficult to find online though i hvnt try crashing it yet. just wondering how to recover if anything goes wrong.

also if i can understand the internal mechanics of how sharding works i can better prepare on backup strategies in case the failed node can be better remedied and isolated.

**Comment by ljluestc** [comment]
Data recovery in TiDB is mainly handled by the underlying storage engines. TiDB supports multiple storage backends, such as TiKV and TiFlash. These storage engines have their own mechanisms for data replication and crash recovery.

For example, TiKV uses the Raft consensus algorithm to replicate data across multiple nodes, ensuring that data is available even if some nodes fail. When a node crashes and comes back online, it can catch up with the latest data through the Raft replication process.
