### ISSUE TITLE
Remove deprecated code about LockExpire

### ISSUE THREAD

**Issue by ekexium** [pingcap/tidb#37742]
## Enhancement
It seems there is no place writing the variable. Related code could be removed
https://github.com/pingcap/tidb/blob/330ed6da3200f26ba84a956375963c79f76d1e25/sessionctx/variable/session.go#L209

**Comment by fatelei** [comment]
assign to me

**Comment by ekexium** [comment]
Hey @fatelei , I double checked it. Turns out it's still useful. My bad

**Comment by fatelei** [comment]
> Hey @fatelei , I double checked it. Turns out it's still useful. My bad

yes, i read the code, found it still useful
