### ISSUE TITLE
when partially insert, receive  an incorrect exception 

### ISSUE THREAD

**Issue by maruixiang** [pingcap/tidb#3801]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
CREATE TABLE `log_event` (
  `event_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `first_occur_time` datetime DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `last_occur_time` datetime DEFAULT NULL,
  `update_time` datetime DEFAULT NULL,
  `total_count` int(11) DEFAULT NULL,
  `last_alarm_time` datetime DEFAULT NULL,
  `features` varchar(100) DEFAULT NULL,
  `feature` varchar(100) DEFAULT NULL,
  `create_time` datetime DEFAULT NULL,
  `project_name` varchar(100) DEFAULT NULL,
  `exception_message` text DEFAULT NULL,
  `exception_name` varchar(255) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
 PRIMARY KEY (`event_id`),
  KEY `idx_time` (`last_occur_time`,`project_name`),
  UNIQUE KEY `idx_feature_project` (`feature`,`project_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=3;

insert into log_event(last_occur_time,update_time,total_count,create_time,exception_message,exception_name) values(
now(),now(),total_count+1,now(),'oh my god3', 'java.lang.Exception')

2. What did you expect to see?
   error:primary key need
3. What did you see instead?
 11:50:01	insert into log_event(last_occur_time,update_time,total_count,create_time,exception_message,exception_name) values( now(),now(),total_count+1,now(),'oh my god3', 'java.lang.Exception')	
Error Code: 2013. Lost connection to MySQL server during query	0.000 sec

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: e356b2663f433aa9538da9f6674330d27b8bea13
UTC Build Time:  2017-07-05 11:39:29

**Comment by morgo** [comment]
I believe the behavior here is correct - or at least correct for compatibility with MySQL since it behaves the same:

```
mysql57> select * from log_event\G
*************************** 1. row ***************************
         event_id: 3
 first_occur_time: NULL
            level: NULL
  last_occur_time: 2018-10-28 20:54:57
      update_time: 2018-10-28 20:54:57
      total_count: NULL
  last_alarm_time: NULL
         features: NULL
          feature: NULL
      create_time: 2018-10-28 20:54:57
     project_name: NULL
exception_message: oh my god3
   exception_name: java.lang.Exception
           status: NULL
1 row in set (0.00 sec)

tidb> select * from log_event\G
*************************** 1. row ***************************
         event_id: 3
 first_occur_time: NULL
            level: NULL
  last_occur_time: 2018-10-28 20:54:22
      update_time: 2018-10-28 20:54:22
      total_count: NULL
  last_alarm_time: NULL
         features: NULL
          feature: NULL
      create_time: 2018-10-28 20:54:22
     project_name: NULL
exception_message: oh my god3
   exception_name: java.lang.Exception
           status: NULL
1 row in set (0.00 sec)
```

Columns which have `DEFAULT` values are not required to be specified, and the `event_id` column does not need to be specified as it is `auto_increment`.

I am going to close this issue - but please feel free to re-open it if you have further questions.
