### ISSUE TITLE
how to update secondary indexes when record is updated

### ISSUE THREAD

**Issue by Xavier1994** [pingcap/tidb#38024]
## General Question

When a record is updated/inserted, how to update its secondary indexes? Whether tidb remove the record's old secondary indexes  before insert the new one?

**Comment by Defined2014** [comment]
Yes, TiDB will remove the old record and insert the new record. You could read the [code](https://github.com/pingcap/tidb/blob/1870d5f098b902b0d635b6bb28a091f16773fd86/pkg/executor/write.go#L178)
