### ISSUE TITLE
Dynamic Gorotinue Pool

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#38039]
## Enhancement

Dynamic Gorotinue Pool is a pool with fixed capacity, managing and recycling a massive number of goroutines, allowing developers to limit the number of goroutines in tidb.

So you can manage resources between pools to avoid affecting online query.

**Comment by jianzhiyao** [comment]
Could you describe more detail about this issue? I'm intresting in it.

**Comment by jianzhiyao** [comment]
Just like https://github.com/Jeffail/tunny or https://github.com/go-playground/pool ?

**Comment by hawkingrei** [comment]
@jianzhiyao  It is like https://github.com/panjf2000/ants. But it is still in development. it maybe merged after two weeks. but it just is a base library and it will not use it in the tidb for one or two months.

**Comment by hawkingrei** [comment]
But it is not the same as ```ants```. we need to schedule and rebalance the size of the different pools. it is a important feature.
