### ISSUE TITLE
view leads to information_schema.columns data_type null 

### ISSUE THREAD

**Issue by irwinai** [pingcap/tidb#38108]
### 1. Minimal reproduce step (Required)
1.create view such as ,so the information_schema.columns data_type can get null 
```SQL
 CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`1.1.1.1` SQL SECURITY DEFINER VIEW `v_test` (
   `type`) AS
SELECT
 NULL AS `type`,
FROM
 `test` AS `f`
```
2.so we can see the null or other type in information_schema.columns data_type
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h6eh2prflij20hc12kwgb.jpg)

### 2. What did you expect to see? (Required)
the right data_type just like mysql
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h6fl4ltq1wj209w0zq3zh.jpg)

### 3. What did you see instead (Required)
the null or wrong data_type
![](https://tva1.sinaimg.cn/large/e6c9d24egy1h6eh2prflij20hc12kwgb.jpg)

### 4. What is your TiDB version? (Required)
newest 6.2.0 and 4.0.x

**Comment by hawkingrei** [comment]
@irwinai Can you give me the information about ```test``` table ?
