### ISSUE TITLE
The DDL of dropped database/table wasn't restored by BR increment restore.

### ISSUE THREAD

**Issue by superlzs0476** [pingcap/tidb#38124]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Database List: db1
Table List: t1,t2,t3,t4

Step 1: full backup TiDB cluster
Step 2: Execute DDL: drop table t2
Step 3: increment backup TiDB cluster
Step 4: Execute DDL: drop database db1;
Step 5: restore full backup data;
Step 6: restore increment backup data;

### 2. What did you expect to see? (Required)

I can't find t2 on the db1 after the restore increment backup data is completed.

### 3. What did you see instead (Required)

Table t2 didn't be dropped in the Database db1.

### 4. What is your TiDB version? (Required)
v6.1.0

Asktug Link:  https://asktug.com/t/topic/183425/9

**Comment by superlzs0476** [comment]
The same question is in AskTUG. https://asktug.com/t/topic/183425

**Comment by IANTHEREAL** [comment]
Can we recommend users to upgrade TiDB and then use PITR? I understand that the architecture implementation design for incremental backup recovery is deficient, but PITR can work better. @superlzs0476

**Comment by superlzs0476** [comment]
Yes, we can. If they need to restore point-in-time, we will recommend the PiTR. The issue is from our customer feedback, they are exploring the new version of TiDB features.

**Comment by BornChanger** [comment]
@superlzs0476 Can you check if this problem is fixed?

**Comment by BornChanger** [comment]
Currently, this problem has no proper solution yet and we will let it be now.
