### ISSUE TITLE
incorrect mdl behavior when selecting a truncated table after begin

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#38132]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table x(a int);
create table t(a int); 
insert into t values(1);
    begin; --- session2
    select * from x; --- session2
truncate table t;
insert into t values(2);
    select * from t;    --- session2
```

### 2. What did you expect to see? (Required)

Error will occurs when selecting t in session2
```
mysql> select * from t;
ERROR 1412 (HY000): Table definition has changed, please retry transaction
```

### 3. What did you see instead (Required)

The error returns is not right and strange.

```
mysql> select * from t;
ERROR 1050 (42S01): Table 't' already exists
```

And then execute the above query again, the select returns a empty dataset successfully.

```
mysql> select * from t;
Empty set (0.05 sec)
```

It is still incorrect. Because the table t has never been empty after transaction begin.

**Comment by wjhuang2016** [comment]
fixed by https://github.com/pingcap/tidb/pull/39366, and the empty result is the expected behavior because of the truncate.
