### ISSUE TITLE
unstable test TestCoprocessorPagingSize

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#38158]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
    distsql_test.go:467: 
        	Error Trace:	/home/jenkins/.tidb/tmp/63a9840cd0739f2c243bb46478607469/sandbox/processwrapper-sandbox/6362/execroot/__main__/bazel-out/k8-fastbuild/bin/executor/executor_test_/executor_test.runfiles/__main__/executor/distsql_test.go:467
        	Error:      	"2" is not greater than "2"
        	Test:       	TestCoprocessorPagingSize
```

https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/1456/nodes/49/steps/52/log/?start=0

**Comment by tiancaiamao** [comment]
Only affects master from https://github.com/pingcap/tidb/pull/37920 until recently.
