### ISSUE TITLE
Is the nosql feature of tidb compatible with Mongodb protocol ?

### ISSUE THREAD

**Issue by goodforever** [pingcap/tidb#3815]
Is the nosql feature of tidb compatible with Mongodb protocol  ?
Can I import data from mongodb ?

**Comment by morgo** [comment]
While architecturally possible, TiDB at least currently does not plan to implement the MongoDB protocol.

Please take a look at the [ROADMAP](https://pingcap.com/docs/ROADMAP/) for upcoming plans.

**Comment by nullnotnil** [comment]
I am going to close this issue for now, but please feel free to re-open if you have additional questions. Thanks!
