### ISSUE TITLE
TiDB cluster is much slower than mysql standalone MySQL instance?

### ISSUE THREAD

**Issue by john-deng** [pingcap/tidb#3817]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
``` 
I deployed tidb cluster with 6 VMs followed the instructions from 
https://github.com/pingcap/tidb-ansible.

I also deployed mysql 5.7 single instance on a equivalent VM.
```
2. What did you expect to see?
```
inserted 1,000,000 rows data into a table

select count(id) my_table; it takes 1500 ms on tidb cluster, but it takes 180ms on 
mysql single instance with the same amount of rows. 
```

3. What did you see instead?
``` 
The query speed on tidb should faster that mysql.
``` 
4. What version of TiDB are you using (`tidb-server -V`)?
``` 
MySQL 5.7.1-TiDB-1.0

I'm new to TiDB, Where do I start to solve this issue? 
``` 

@coocood @shenli @zimulala

**Comment by deejross** [comment]
I just installed 3 KV, 3 PD, and 2 DB servers and have a similar experience. Table creation takes at least 10x longer, inserts are at least 5x slower, and reads are about 2x slower than a standalone MySQL instance. I used `mysqlslap -h the-host -P 4000 --auto-generate-sql --concurrency=50 --iterations 10 --verbose` for benchmarking.

Versions:
```
bin/pd-server --version
Git Commit Hash: c76b8c5b854dcbdc7f45706f2d14a5d4896c7c68
UTC Build Time:  2017-07-14 09:34:14

bin/tikv-server --version
TiKV 0.0.1
Git Commit Hash: 38547be23a1e039955d137d4426ed4d7de88f335
UTC Build Time:  2017-07-19 07:02:22
Rust Version:    1.19.0-nightly (d47cf08d5 2017-05-28)

bin/tidb-server -V
Git Commit Hash: 37d8ea3e38209d0f49a0f46c649220f8877b9fd8
UTC Build Time:  2017-07-19 02:19:35
```

**Comment by PHILO-HE** [comment]
In my case, it takes around 1s for TiDB with TiKV as storage to execute the SQL statement that creates a simple table. I have noticed the link https://github.com/pingcap/docs-cn/blob/master/FAQ.md#%E5%9C%A8%E4%BD%BF%E7%94%A8-tidb-%E6%97%B6ddl-%E8%AF%AD%E5%8F%A5%E4%B8%BA%E4%BB%80%E4%B9%88%E8%BF%99%E4%B9%88%E6%85%A2. But it is intolerable for my application to wait so much time for creating a table. I just deployed PD, TiDB and TiKV on one single node. But I think it doesn't matter too much. Can anyone reply to my problem? Thanks.

**Comment by deejross** [comment]
Seeing no updates on this in two months tells me that performance is not a concern for TiDB, which is a shame because it has the potential to be **the** clustering solution for applications needing a MySQL-compatible database and high performance and availability. It would be one thing if TiDB was 2x slower, but when it takes several minutes to create almost 100 tables over the few seconds it takes MySQL, that's more than noticeably slower; it's unusable in any serious environment. I'm betting it could be much faster than it is, just that performance is clearly not a priority.

**Comment by shenli** [comment]
@deejross Sorry for the late reply.
You can test the latest version. We speed up the DDL process. For create table statement, it will take less than 1s in normal case.
For DML, we can not beat MySQL on latency. But we could get linear increasing when you add more node to the cluster. I will show you a benchmark result based on sysbench next week.
We care performance very much.

**Comment by john-deng** [comment]
@shenli as you mentioned that you would show us the benchmark result in this week, any updates on the performance issue?

**Comment by shenli** [comment]
@john-deng Here is the benchmark result based on Sysbench: https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md
We will keep this document updated.

**Comment by nullnotnil** [comment]
Benchmarks are now available in the TiDB documentation. For example https://docs.pingcap.com/tidb/stable/benchmark-sysbench-v4-vs-v3

Since this issue is now a little stale, I am going to propose closing it for now. Please feel free to re-open though if you have additional questions. Thanks!
