### ISSUE TITLE
stats meta is not created after creating table

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#38189]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Create 2000 tables. Only 797 rows of stats meta are created, which means stats meta of some tables is not created.

### 2. What did you expect to see? (Required)
There should be 2000 rows of stats meta.

### 3. What did you see instead (Required)
Only 797 rows of stats meta are created.

### 4. What is your TiDB version? (Required)
v6.3.0

**Comment by xuyifangreeneyes** [comment]
The root cause is that when `DDLEventCh` is full(its capacity is 100), some ddl events may not be notified and corresponding stats meta cannot be created.
![20220927-124037](https://user-images.githubusercontent.com/30385241/192433867-b7063846-f4f0-4a3e-8d69-539e86766e44.jpeg)

The problem may occur when there are many ddl jobs.

**Comment by Yisaer** [comment]
Is this a major bug as the stats meta would be created as following code:

https://github.com/pingcap/tidb/blob/0875ae28490997f2376e3c808bf7bc8f8942b6bc/statistics/handle/handle.go#L621-L642

**Comment by xuyifangreeneyes** [comment]
I think it is a bug because we expect that there is a corresponding record in `mysql.stats_meta` after creating a table. Without stats meta, some statistics mechanism, such as triggering auto analyze and estimating row count / modify count, may not work as expected.
