### ISSUE TITLE
`br` restore log data too slow, and the speed is 8.14 GB/H per `tikv`

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#38211]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. downstream tidb cluster includes 3 tikv , every one is 8c32g and nvme disk
2. `br restore point` 

### 2. What did you expect to see? (Required)
1.  restore successfully
2.  restore log speed can reach 30GB/H per `tikv`
### 3. What did you see instead (Required)
1. restore successfully
2. restore log speed is 8.14 GB/H per `tikv`
```
[2022/09/28 00:29:36.286 +00:00] [INFO] [collector.go:69] ["restore log success summary"] [total-take=12h12m43.357650708s] 
[restore-from=436220682829824000] [restore-to=436279881427582986] [restore-from="2022-09-24 20:04:06 +0000"] 
[restore-to="2022-09-27 10:47:50.729 +0000"] [total-kv-count=2064569816] [total-size=305.6GB] [average-speed=6.951MB/s]
```
### 4. What is your TiDB version? (Required)
v6.3.0

**Comment by 3pointer** [comment]
From later internal performance test. we found the restore speed is 80G/h, after we choose an independent minio cluster and increase num-threads of tikv. 
So I think this issue is not a major bug but enhancement. WDYT @AkiraXie

**Comment by AkiraXie** [comment]
> From later internal performance test. we found the restore speed is 80G/h, after we choose an independent minio cluster and increase num-threads of tikv. So I think this issue is not a major bug but enhancement. WDYT @AkiraXie

LGTM
