### ISSUE TITLE
node.Text() incorrect in nested statements

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#3823]
I was trying to output `sel.Text()` in function `func (b *planBuilder) buildSelect(sel *ast.SelectStmt) LogicalPlan` of `logical_plan_builder.go`:

```go
fmt.Printf("sel.Text() = %s\n", sel.Text())
```

It works well in simple cases but gives wrong SQL statement in nested statements:

```
sel.Text() = select * from t2 where hello in (select hello from t1)   // outer, correct
sel.Text() = (select hello from t   // inner, incorrect
```

**Comment by zz-jason** [comment]
Please use `Restore()` instead. I'm going to close this issue seems it's stale. Feel free to reopen it if it still exists.
