### ISSUE TITLE
@Xavierj2800: Thanks for your review. The bot only counts approvals from reviewers and higher roles in [list](https://prow.tidb.net/tichi/repos/pingcap/tidb/pulls/38249/owners), but you're still welcome to leave your comments.

### ISSUE THREAD

**Issue by Xavierj2800** [pingcap/tidb#38252]
https://github.com/pingcap/tidb/pull/38249#issue-1390538174        @Xavierj2800: Thanks for your review. The bot only counts approvals from reviewers and higher roles in [list](https://prow.tidb.net/tichi/repos/pingcap/tidb/pulls/38249/owners), but you're still welcome to leave your comments.

<details>

In response to [this](https://github.com/pingcap/tidb/pull/38249#pullrequestreview-1125041472):

>

Instructions for interacting with me using PR comments are available [here](https://prow.tidb.net/command-help).  If you have questions or suggestions related to my behavior, please file an issue against the [ti-community-infra/tichi](https://github.com/ti-community-infra/tichi/issues/new?title=Prow%20issue:) repository.
</details>

_Originally posted by @ti-chi-bot in https://github.com/pingcap/tidb/issues/38249#issuecomment-1262081642_

**Comment by Defined2014** [comment]
Please describe your problem in detail. Close this issue.
