### ISSUE TITLE
TiKV Crashing due to fatal error - "range end index 6 out of range for slice of length 5"

### ISSUE THREAD

**Issue by sayeed123** [pingcap/tidb#38292]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
 TiDB for our production application last 3 weeks with EKS, it was working fine, but sudden TiKV keep crashing even for minimal load

### 2. What did you expect to see? (Required)
No crash 

### 3. What did you see instead (Required)
Getting below error
`[FATAL] [lib.rs:491] ["range end index 6 out of range for slice of length 5"] [backtrace="   0: tikv_util::set_panic_hook::{{closure}}\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tikv_util/src/lib.rs:490:18\n   1: std::panicking::rust_panic_with_hook\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:702:17\n   2: std::panicking::begin_panic_handler::{{closure}}\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:588:13\n   3: std::sys_common::backtrace::__rust_end_short_backtrace\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:138:18\n   4: rust_begin_unwind\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/panicking.rs:584:5\n   5: core::panicking::panic_fmt\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/panicking.rs:143:14\n   6: core::slice::index::slice_end_index_len_fail\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:43:5\n   7: <core::ops::range::Range<usize> as core::slice::index::SliceIndex<[T]>>::index\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:245:13\n      core::slice::index::<impl core::ops::index::Index<I> for [T]>::index\n             at rust/toolchains/nightly-2022-02-14-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/index.rs:15:9\n      tidb_query_expr::impl_like::like\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/impl_like.rs:48:42\n   8: <tidb_query_expr::types::function::Arg<Arg0_,tidb_query_expr::types::function::Arg<Arg1_,tidb_query_expr::types::function::Arg<Arg2_,tidb_query_expr::types::function::Null>>> as tidb_query_expr::impl_like::Like_Fn<C>>::eval\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/impl_like.rs:9:1\n      <tidb_query_expr::impl_like::Like_Evaluator<C> as tidb_query_expr::types::function::Evaluator>::eval\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/impl_like.rs:9:1\n      <tidb_query_expr::types::function::ArgConstructor<A,E> as tidb_query_expr::types::function::Evaluator>::eval\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/types/function.rs:254:17\n      <tidb_query_expr::types::function::ArgConstructor<A,E> as tidb_query_expr::types::function::Evaluator>::eval\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/types/function.rs:238:17\n   9: <tidb_query_expr::types::function::ArgConstructor<A,E> as tidb_query_expr::types::function::Evaluator>::eval\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/types/function.rs:238:17\n      tidb_query_expr::impl_like::like_fn_meta::run\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/impl_like.rs:9:1\n  10: tidb_query_expr::types::expr_eval::<impl tidb_query_expr::types::expr::RpnExpression>::eval_decoded\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/types/expr_eval.rs:254:31\n  11: tidb_query_expr::types::expr_eval::<impl tidb_query_expr::types::expr::RpnExpression>::eval\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_expr/src/types/expr_eval.rs:167:9\n      tidb_query_executors::selection_executor::BatchSelectionExecutor<Src>::handle_src_result\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_executors/src/selection_executor.rs:79:19\n      <tidb_query_executors::selection_executor::BatchSelectionExecutor<Src> as tidb_query_executors::interface::BatchExecutor>::next_batch\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_executors/src/selection_executor.rs:178:25\n      <tidb_query_common::execute_stats::WithSummaryCollector<C,T> as tidb_query_executors::interface::BatchExecutor>::next_batch\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_executors/src/interface.rs:105:22\n  12: <alloc::boxed::Box<T> as tidb_query_executors::interface::BatchExecutor>::next_batch\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_executors/src/interface.rs:74:9\n      tidb_query_executors::runner::BatchExecutorsRunner<SS>::internal_handle_request\n             at home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tikv/components/tidb_query_executors/src/runner.rs:589:26\n  13: tidb_query_executors::runner::BatchExecutorsRunner<SS>::handle_request::{{closure}}\n             at home/jenkins/agent/workspace/build-`

### 4. What is your TiDB version? (Required)
Release Version: v6.1.0
Edition: Community
GoVersion: go1.18.2
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306

**Comment by BusyJay** [comment]
@zanmato1984 PTAL

**Comment by XuHuaiyu** [comment]
@sayeed123 
Hi, can you provide us with a reproducible step for this issue, like the SQLs?

**Comment by zanmato1984** [comment]
Changing severity to major.

**Comment by mayjiang0203** [comment]
Close it for there is no enough information to debug. Please reopen if hit it again.
