### ISSUE TITLE
ERROR 8141 (HY000): assertion failed

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#38295]
## Bug Report

ERROR 8141 (HY000): assertion failed

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 BLOB(298) , c1 BLOB(182) , c2 NUMERIC);
CREATE VIEW v0(c0) AS SELECT t0.c1 FROM t0;
INSERT INTO t0 VALUES (-1, 'a', '2046549365');
CREATE INDEX i0 ON t0(c2);
SELECT t0.c1, t0.c2 FROM t0 GROUP BY MOD(t0.c0, DEFAULT(t0.c2));

UPDATE t0 SET c2=1413; -- ERROR 8141 (HY000): assertion failed: key: 7480000000000007f05f69800000000000000106301e8000000202c649750000000000000000000000000000038000000000000001, assertion: Exist, start_ts: 436435076383506432, existing start ts: 0, existing commit ts: 0
```

### 2. What did you expect to see? (Required)
No error.

### 3. What did you see instead (Required)
Assertion error.

### 4. What is your TiDB version? (Required)

| Release Version: v6.4.0-alpha-12-g51a6684fb
Edition: Community
Git Commit Hash: 51a6684fb767cfd86a8312e0e6447963b927c791
Git Branch: master
UTC Build Time: 2022-10-04 04:48:00
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |

**Comment by cfzjywxk** [comment]
If the index is created in the create table statement, the generated index would be corrected and the execution could succeed.
```
mysql> CREATE TABLE t0(c0 BLOB(298) , c1 BLOB(182) , c2 NUMERIC, key i0(c2));
Query OK, 0 rows affected (0.12 sec)

mysql> INSERT INTO t0 VALUES (-1, 'a', '2046549365');
Query OK, 1 row affected (0.04 sec)

mysql> UPDATE t0 SET c2=1413;
Query OK, 1 row affected (0.01 sec)
Rows matched: 1  Changed: 1  Warnings: 0

The index key:
7480000000000000505f698000000000000001060a008202c64975038000000000000001
```

The index generated by the DDL backfill worker seems to be wrong
```
7480000000000000145f69800000000000000104060eeb6835cc0002038000000000008fb5
```
