### ISSUE TITLE
TiKV from 4.0.10 upgrade to 5.1.4, TiDB Server encountered an error "tableWorker in IndexLookUpExecutor panicked"

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#38291]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiKV from 4.0.14 upgrade to 5.1.4, TiDB Server encountered an error "tableWorker in IndexLookUpExecutor panicked"

### 2. What did you expect to see? (Required)
TiDB server no error
### 3. What did you see instead (Required)

```
	// decode nullBitmap.
	if nullCount > 0 {
		numNullBitmapBytes := (col.length + 7) / 8
		col.nullBitmap = buffer[:numNullBitmapBytes:numNullBitmapBytes]
		buffer = buffer[numNullBitmapBytes:]
	} else {
		c.setAllNotNull(col)
	}
```

![image](https://user-images.githubusercontent.com/55389305/193548440-d42e4795-f98e-4cb2-af3c-f9dc415407e5.png)

### 4. What is your TiDB version? (Required)
v4.0.14,  v5.1.4

**Comment by zanmato1984** [comment]
@ChenPeng2013 Could you reproduce the bug?

**Comment by XuHuaiyu** [comment]
Discussed with @yilongrong offline, cannot reproduce it. And no error is reported after after the upgrade progress finished.

Close this issue.
