### ISSUE TITLE
No with rollup clause support

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#3831]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
    CREATE TABLE t (a INT)ENGINE=INNODB;
    INSERT t VALUES(1);
    SELECT '' FROM t GROUP BY 1 WITH ROLLUP HAVING GROUP_CONCAT('');
```

2. What did you expect to see?

```
mysql> SELECT '' FROM t GROUP BY 1 WITH ROLLUP HAVING GROUP_CONCAT('');
Empty set (0.01 sec)
```

3. What did you see instead?

```
mysql> SELECT '' FROM t GROUP BY 1 WITH ROLLUP HAVING GROUP_CONCAT('');
ERROR 1105 (HY000): line 0 column 32 near " ROLLUP HAVING GROUP_CONCAT('')" (total length 63)
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by morgo** [comment]
See also https://github.com/pingcap/tidb/issues/4250

This is also documented as a current limitation on the [Aggregation manual page](https://www.pingcap.com/docs/sql/aggregate-group-by-functions/).

**Comment by zz-jason** [comment]
I'm going to close this issue due to it's duplicated with #4250. Feel free to reopen it when needed.
