### ISSUE TITLE
In left join, index join cannot be enforced when in is a single value in the where condition

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#38328]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE `t1` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL,
  KEY `idx_n` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

```
CREATE TABLE `t2` (
  `id` int(11) DEFAULT NULL,
  `name` varchar(20) DEFAULT NULL,
  KEY `idx_n` (`name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

explain select /*+ INL_JOIN(t1,t2)*/ t1.id,t1.name,t2.id,t2.name from t1 left join t2 on t1.name=t2.name where t1.name in ('abc');

### 2. What did you expect to see? (Required)

+------------------------------------+---------+-----------+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| id                                 | estRows | task      | access object               | operator info                                                                                                                    |
+------------------------------------+---------+-----------+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| IndexJoin_12                       | 10.00   | root      |                             | left outer join, inner:IndexLookUp_11, outer key:test.t1.name, inner key:test.t2.name, equal cond:eq(test.t1.name, test.t2.name) |
| ├─IndexLookUp_27(Build)            | 10.00   | root      |                             |                                                                                                                                  |
| │ ├─IndexRangeScan_25(Build)       | 10.00   | cop[tikv] | table:t1, index:idx_n(name) | range:["abc","abc"], keep order:false, stats:pseudo                                                                              |
| │ └─TableRowIDScan_26(Probe)       | 10.00   | cop[tikv] | table:t1                    | keep order:false, stats:pseudo                                                                                                   |
| └─IndexLookUp_11(Probe)            | 1.00    | root      |                             |                                                                                                                                  |
|   ├─Selection_10(Build)            | 1.00    | cop[tikv] |                             | eq(test.t2.name, "abc"), not(isnull(test.t2.name))                                                                               |
|   │ └─IndexRangeScan_8             | 1250.00 | cop[tikv] | table:t2, index:idx_n(name) | range: decided by [eq(test.t2.name, test.t1.name)], keep order:false, stats:pseudo                                               |
|   └─TableRowIDScan_9(Probe)        | 1.00    | cop[tikv] | table:t2                    | keep order:false, stats:pseudo                                                                                                   |
+------------------------------------+---------+-----------+-----------------------------+----------------------------------------------------------------------------------------------------------------------------------+

### 3. What did you see instead (Required)
+------------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------+
| id                                 | estRows | task      | access object               | operator info                                       |
+------------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------+
| HashJoin_7                         | 100.00  | root      |                             | CARTESIAN left outer join                           |
| ├─IndexLookUp_20(Build)            | 10.00   | root      |                             |                                                     |
| │ ├─IndexRangeScan_18(Build)       | 10.00   | cop[tikv] | table:t2, index:idx_n(name) | range:["abc","abc"], keep order:false, stats:pseudo |
| │ └─TableRowIDScan_19(Probe)       | 10.00   | cop[tikv] | table:t2                    | keep order:false, stats:pseudo                      |
| └─IndexLookUp_14(Probe)            | 10.00   | root      |                             |                                                     |
|   ├─IndexRangeScan_12(Build)       | 10.00   | cop[tikv] | table:t1, index:idx_n(name) | range:["abc","abc"], keep order:false, stats:pseudo |
|   └─TableRowIDScan_13(Probe)       | 10.00   | cop[tikv] | table:t1                    | keep order:false, stats:pseudo                      |
+------------------------------------+---------+-----------+-----------------------------+-----------------------------------------------------+

### 4. What is your TiDB version? (Required)

6.1.0

**Comment by chrysan** [comment]
It's expected because `t1.name in ('abc')` and the inferred `t2.name in ('abc')` are pushed down to ranges, and `on t1.name=t2.name` is simplified and removed.

And there's warning message to tell the hint cannot be applied:
```
show warnings;
+---------+------+----------------------------------------------------------------------------------------------------------------------+
| Level   | Code | Message                                                                                                              |
+---------+------+----------------------------------------------------------------------------------------------------------------------+
| Warning | 1815 | Optimizer Hint /*+ INL_JOIN(t1, t2) */ or /*+ TIDB_INLJ(t1, t2) */ is inapplicable without column equal ON condition |
+---------+------+----------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

Th performance should be good since ranges pushed down. So close it.

**Comment by yilongrong** [comment]
This will greatly affect the efficiency of sql execution

```
explain analyze  select 
 c.id AS box_id,
 c.box_no,
 b.open_time,
 c.`status`,
 b.kit_status,
 a.accept_status
 FROM
 box_history_new c
 LEFT JOIN kit_box_mediate a ON a.box_no = c.box_no
 LEFT JOIN kit_history b ON b.kit_no = a.kit_no
 WHERE
 1 = 1
 AND c.box_no IN ('xxxxxx');
```

------index join------

------------------------------------------------------------------------------------------------------------------------------------------------
id	estRows	actRows	task	access object	execution info 
------------------------------------------------------------------------------------------------------------------------------------------------
Projection_8	25.81	10	root	 	time:3.39ms, loops:2, Concurrency:OFF
└─IndexJoin_12	25.81	10	root	 	time:3.38ms, loops:2, inner:{total:903.7µs, con
├─IndexJoin_26(Build)	25.71	10	root	 	time:2.2ms, loops:3, inner:{total:890.7µs, conc
│ ├─IndexLookUp_42(Build)	25.32	10	root	 	time:1.08ms, loops:3, index_task: {total_time:
│ │ ├─IndexRangeScan_40(Build)	25.32	10	cop[tikv]	table:c, index:idx_box_no(box_no)	time:518.7µs, loops:3, cop_task: {num: 2, max:
│ │ └─TableRowIDScan_41(Probe)	25.32	10	cop[tikv]	table:c	time:422.8µs, loops:2, cop_task: {num: 1, max:
│ └─IndexLookUp_25(Probe)	1.02	1	root	 	time:840.1µs, loops:2, index_task: {total_time:
│ ├─IndexRangeScan_23(Build)	1.02	1	cop[tikv]	table:a, index:box_no(box_no)	time:295.2µs, loops:3, cop_task: {num: 1, max:
│ └─TableRowIDScan_24(Probe)	1.02	1	cop[tikv]	table:a	time:450.8µs, loops:2, cop_task: {num: 1, max:
└─IndexLookUp_11(Probe)	1.00	1	root	 	time:854.2µs, loops:2, index_task: {total_time:
├─IndexRangeScan_9(Build)	1.00	1	cop[tikv]	table:b, index:PRIMARY(kit_no)	time:456.8µs, loops:3, cop_task: {num: 1, max:
└─TableRowIDScan_10(Probe)	1.00	1	cop[tikv]	table:b	time:296.1µs, loops:2, cop_task: {num: 1, max: 
------------------------------------------------------------------------------------------------------------------------------------------------


-------------hash join-----


---------------------------------------------------------------
id	estRows	actRows	task	access object	execution info 
------------------------------------------------------------------------------------------------------------------------------------------------
Projection_8	1106209050.23	10	root	 	time:2.81s, loops:2, Concurrency:5
└─HashJoin_21	1106209050.23	10	root	 	time:2.81s, loops:2, build_hash_table:{to
├─TableReader_36(Build)	6098004.00	6098279	root	 	time:371.4ms, loops:5965, cop_task: {num:
│ └─TableFullScan_35	6098004.00	6098279	cop[tikv]	table:b	tikv_task:{proc max:401ms, min:217ms, p80
└─HashJoin_24(Probe)	1101807060.79	10	root	 	time:1.38s, loops:2, build_hash_table:{to
├─IndexLookUp_30(Build)	12.64	10	root	 	time:1.04ms, loops:2, index_task: {total_
│ ├─IndexRangeScan_28(Build)	12.64	10	cop[tikv]	table:c, index:idx_box_no(box_no)	time:464.2µs, loops:3, cop_task: {num: 1,
│ └─TableRowIDScan_29(Probe)	12.64	10	cop[tikv]	table:c	time:429.4µs, loops:2, cop_task: {num: 1,
└─IndexLookUp_34(Probe)	87183384.00	1	root	 	time:1.38s, loops:2, index_task: {total_t
├─Selection_33(Build)	87183384.00	1	cop[tikv]	 	time:1.38s, loops:3, cop_task: {num: 94,
│ └─IndexFullScan_31	108979230.00	108997089	cop[tikv]	table:a, index:box_no(box_no)	tikv_task:{proc max:645ms, min:154ms, p80
└─TableRowIDScan_32(Probe)	87183384.00	1	cop[tikv]	table:a	time:549µs, loops:2, cop_task: {num: 1, m
------------------------------------------------------------------------------------------------------------------------------------------------
