### ISSUE TITLE
Table name and column name can not be scientific notation

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#3834]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
create table 1ea10 (1a20 int,1e int);
```

2. What did you expect to see?

Query OK, 0 rows affected (0.02 sec)

3. What did you see instead?

ERROR 1105 (HY000): line 0 column 15 near "a10 (1a20 int,1e int)"float literal: strconv.ParseFloat: parsing "1e": invalid syntax (total length 36)

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by kennytm** [comment]
This is no longer reproducible, I think some of the recent parser improvement has fixed this already. (Release Version: v3.0.0-beta.1-46-gad752611c)

**Comment by jackysp** [comment]
Thanks, @kennytm !
Closed.
