### ISSUE TITLE
Date type Default Value Can't be (curdate())

### ISSUE THREAD

**Issue by Bowen-Tang** [pingcap/tidb#38356]
## Bug Report
Date type Default Value Can't be (curdate()), But MySQL is OK.

### 1. Minimal reproduce step (Required)
CREATE TABLE DATE_TEST(
  id int,
  create_date date default (curdate())
)

### 2. What did you expect to see? (Required)
Query OK

### 3. What did you see instead (Required)
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 3 column 36 near "curdate()))"

### 4. What is your TiDB version? (Required)
6.0/6.1

**Comment by bb7133** [comment]
This is a new feature introduced in MySQL 8, so we will treat this issue as a feature request.

**Comment by bb7133** [comment]
See also https://github.com/pingcap/tidb/issues/10377
