### ISSUE TITLE
No table name validity check in drop table if exists

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#3835]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
drop table if exists ``;
```

2. What did you expect to see?

ERROR 1103 (42000): Incorrect table name ''

3. What did you see instead?

Query OK, 0 rows affected (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
Notice for bug fixers: Rules in #3838 should also be applied.

MySQL:

```
mysql> drop table if exists `t1 `;
ERROR 1103 (42000): Incorrect table name 't1 '
```
