### ISSUE TITLE
Create table should failed when column name is ``

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#3836]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
create table t1 (`` int);
```

2. What did you expect to see?

ERROR 1166 (42000): Incorrect column name ''

3. What did you see instead?

Query OK, 0 rows affected (0.01 sec)

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
Should we fail in parser (to produce the same parsing error as MySQL) or fail in validator?

**Comment by breeswish** [comment]
Fixed in #3927
