### ISSUE TITLE
splitTableRanges called for each batch in writePhysicalTableRecord

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#38436]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Code inspection.

In [ddl.Ctx.writePhysicalTableRecord](https://github.com/pingcap/tidb/blob/00791e7968ffad2de33d7af7f6f8a21580e2ab7e/ddl/backfilling.go#L621)
 for each batch of kvRanges it starts over and calls splitTableRanges again (meaning it requests information of all ranges that would match a full table, from startKey of current batch.

This results in waste of resources, it should either do the query once before the loop, or limit the query to max batchsize + 1 ranges (since the last range is needed later to see if there are any remaining range left to do).

### 4. What is your TiDB version? (Required)

Current master, as of 00791e7968ffad2de33d7af7f6f8a21580e2ab7e.

**Comment by zimulala** [comment]
I don't know if I got that right.
We will reset the startKey at https://github.com/pingcap/tidb/blob/00791e7968ffad2de33d7af7f6f8a21580e2ab7e/ddl/backfilling.go#L734. 
Besides, the region infos may update after we handle a batch of tasks, so we can split it again for remaining regions.

**Comment by mjonss** [comment]
> Besides, the region infos may update after we handle a batch of tasks, so we can split it again for remaining regions.

yes, so we only need to get `workCnt` + 1 kvRanges from `splitTableRanges`, (+1 so we can get the new startKey as you point out). But let say that splitTableRanges would give 1000 kvRanges (really regions) and we are only doing 4 (default `tidb_ddl_reorg_worker_cnt`) ranges at a time, that means we are first getting 1000 kvRanges from `splitTableRanges` the first time in the loop, the next time we will get 996 kvRanges, then 992... so every time we will call `splitTableRanges` but only do work with 4 of the kvRanges and check if there is any `remains` and if so use that as a startKey for the next loop and next call to `splitTableRanges`.

By having a limit of `workCnt` + 1 for `splitTableRanges` would decrease the resource usage (how many times will it need to go to PD for updating the cache?)
