### ISSUE TITLE
MySQL compatible AUTO_INCREMENT

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#38442]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, TiDB support AUTO_INCREMENT ID that is **unique**, **incremental**, but the IDs maybe **non-continuous**.

For example, where there are two TiDB instance, allocate from instance A get [0-20000), 
allocate from instance B get [20000-40000)... 
after instance A exhaust its cached IDs, the next allocation get 40000. 
The ID sequence looks like: ...19998, 19999, [the hole here], 40000, 40001...

**Describe the feature you'd like:**

I would like it to be fully MySQL-compatible

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

A centralized auto ID allocating service, so that the AUTO_INCREMENT ID could be **unique**, **incremental**, and **noncontinuous**, just like MySQL.

**Comment by tiancaiamao** [comment]
Split the original [PR](https://github.com/pingcap/tidb/pull/38449) to make the reviewer's life easier:

- design doc [tidb#38807](https://github.com/pingcap/tidb/pull/38807)
- kvproto changes [kvproto#1000](https://github.com/pingcap/kvproto/pull/1000)
- autoid centralized service [tidb#38810](https://github.com/pingcap/tidb/pull/38810)
- client side changes [tidb#38809](https://github.com/pingcap/tidb/pull/38809)
- test related [tidb#38808](https://github.com/pingcap/tidb/pull/38808/)

**Comment by dveeden** [comment]
@tiancaiamao can we close this issue?
