### ISSUE TITLE
Missing `RootTaskType` for agg causes `Can't find a proper physical plan` error

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#38478]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t1(a int, b int);
create table t2(a int, b int);
alter table t1 set tiflash replica 1;
alter table t2 set tiflash replica 1;
set @@tidb_opt_distinct_agg_push_down = 1;
```
case 1:
```sql
explain select /*+ read_from_storage(tikv[t1]) */count(distinct t2.a) from t1 join t2 on t1.b = t2.b;
```
case 2:
```sql
set @@tidb_allow_mpp=0;
explain select count(distinct t2.a) from t1 join t2 on t1.b = t2.b;
```
(sometimes you need to wait a moment or run them multiple times before the error appears)
### 2. What did you expect to see? (Required)

Display the execution plan.

### 3. What did you see instead (Required)

```
ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
```

### 4. What is your TiDB version? (Required)

master

This issue at least affects tidb from v6.0.0. TiDB before v6.0.0 should also be affected but I can't verify it on my machine.

**Comment by time-and-fate** [comment]
In the issue, the `LogicalAggregation` doesn't generate the `RootTaskType` property, so it won't try to generate a plan with the aggregation not pushed down. However, due to the existence of `LogicalJoin` and the `read_from_storage` hint, it can't successfully generate such a plan, then it failed to generate the physical plan.

##### The mechanism of `read_from_storage` hint
Unlike the `tidb_isolation_read_engines`, the `read_from_storage` hint doesn't prune the access paths during logical optimization. It only checks if it's valid and marks it in the `preferStoreType` field during logical optimization. During physical optimization, it won't generate plans that violate the hint.

##### The premise for `LogicalAggregation` to generate the `RootTaskType`
According to the logic in `getHashAggs()` (`getStreamAggs()` is similar), there are three cases where the `RootTaskType` property is generated:
1. There is `distinct` in the aggregation and `tidb_opt_distinct_agg_push_down` is off.
2. There is no `distinct` and no `agg_to_cop` hint.
3. It finds it can be pushed to neither tikv nor tiflash.

According to the comments, 1 is for assuring when `tidb_opt_distinct_agg_push_down` is on, the distinct agg should always be pushed down.

In any case, the 3 should have generated `RootTaskType` when that is necessary to generate a physical plan. But the checking logic in 3 is too simple to assure this.
In both two cases in this issue, it's only possible to generate a root task agg, but 3 doesn't generate `RootTaskType`:
1. The tiflash access path exists in the `possibleAccessPaths`, however, actually it can't be chosen because of the `read_from_storage` hint.
2. It must generate an MPP plan to push down the agg, but the MPP plan is disabled.

**Comment by AilinKid** [comment]
it should be closed when https://github.com/pingcap/tidb/issues/41014 is closed, it's the same thing. So it won't affect 6.6 and 7.0 and 7.1
