### ISSUE TITLE
flashback command will hang with multi tidb node cluster

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#38475]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. tidb cluster with 2tidb, 3pd, 5tikv
2. 300G data, run update with 1.7 kps for 1 hour
3. execute flashback cluster ddl

### 2. What did you expect to see? (Required)
ddl success 
### 3. What did you see instead (Required)
ddl hangs for 5 hours
|    356 |           |            | flashback cluster   | public       |         0 |        0 |         0 | 2022-10-14 10:50:41 | 2022-10-14 10:50:41 | 2022-10-14 15:05:36 | synced |
### 4. What is your TiDB version? (Required)

[root@10 ~]# /home/tidb/tidb-deploy/tidb-4000/bin/tidb-server -V
Release Version: v6.3.0-alpha-435-g6bf2dcf5d-dirty
Edition: Community
Git Commit Hash: 6bf2dcf5d16965eee4a5222dd2b90d65dadd544b
Git Branch: flashback-2-phase
UTC Build Time: 2022-10-12 13:18:00

**Comment by Defined2014** [comment]
should be fixed after https://github.com/tikv/client-go/pull/606 merged, testing now.

**Comment by Defined2014** [comment]
after PR merged, the test could pass.
