### ISSUE TITLE
Unknown table 't1' in MULTI DELETE

### ISSUE THREAD

**Issue by erwadba** [pingcap/tidb#38520]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
delete can't execute.

### 1. Minimal reproduce step (Required)

```
# tiup  playground v6.3.0 --host 0.0.0.0 
mysql> use test;
mysql> create table t1(id int);
mysql> create table t2(id int);
mysql> delete t1 from t1,t2 where t1.id=t2.id;
mysql> delete t1 from t1 a,t2 b where a.id=b.id;
ERROR 1109 (42S02): Unknown table 't1' in MULTI DELETE
mysql> 
```
### 2. What did you expect to see? (Required)
execute success.
### 3. What did you see instead (Required)
execute error
### 4. What is your TiDB version? (Required)
```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.3.0
Edition: Community
Git Commit Hash: ecd67531f1721d3e49eb15a202ac7c0ae02291ec
Git Branch: heads/refs/tags/v6.3.0
UTC Build Time: 2022-09-23 14:29:48
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)

mysql> 
```

**Comment by seiya-annie** [comment]
also fail in mysql:
mysql> delete t1 from t1 a,t2 b where a.id=b.id;
ERROR 1109 (42S02): Unknown table 't1' in MULTI DELETE

 mysql -V
mysql  Ver 8.0.23 for osx10.15 on x86_64 (Homebrew)

**Comment by seiya-annie** [comment]
![20221019-114622](https://user-images.githubusercontent.com/53471087/196593151-1664c529-9f2e-43a7-b03c-4106a459fe59.jpeg)
