### ISSUE TITLE
alter table does not check the field length limitation of char/varchar

### ISSUE THREAD

**Issue by shenyan129** [pingcap/tidb#3852]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

   alter table t2 add column varchar500000 varchar(500000) not null default '' comment '50Wtext';    可执行。时间(3.01 sec) 目前alter没有检查varchar的限制
           alter table t2 add column char500000 char(500000) not null default '' comment '50Wtextchar';   可执行。时间(3.01 sec) 目前alter没有检查char的限制

2. What did you expect to see?

希望出现报错ERROR 1105 (HY000): Column length too big for column 'char500000' (max = 255); use BLOB or TEXT instead

3. What did you see instead?

可以执行，并没有报错

4. What version of TiDB are you using (`tidb-server -V`)?

Git Commit Hash: d99f2974fb21b1215fed10c2c6dcfbc24073f706
UTC Build Time:  2017-07-12 03:36:02

**Comment by shenli** [comment]
@shenyan129 Thanks for your feedback!
We should check more constraint in the statement validator for [CreateTableStmt](https://github.com/pingcap/tidb/blob/master/plan/validator.go#L216).
