### ISSUE TITLE
PITR checkpoint not move forward during tikv and tidb advance owner network partition

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#38531]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Start log backup tasks
Run workloads
Inject network partition between one TiKV and one TiDB, the TiDB is PITR checkpoint advance owner.
Check PITR checkpoint status

### 2. What did you expect to see? (Required)
During one TiKV and one TiDB network partition, TiDB cluster can still provide services (though downgraded).
PITR checkpoint should move forward normally in this case to meet RPO.

### 3. What did you see instead (Required)
PITR checkpoint doesn't move forward in this case.

![image](https://user-images.githubusercontent.com/7403864/196423899-977f7dfc-08cf-42b9-98e7-5b397167bc5d.png)
![image](https://user-images.githubusercontent.com/7403864/196423959-920aac20-3289-4bba-a9df-019d795ac43f.png)

### 4. What is your TiDB version? (Required)
v6.3.0

**Comment by fubinzh** [comment]
The same issue seen during TiDB (advancer owner) and PD leader network partition.
![image](https://user-images.githubusercontent.com/7403864/196433755-f6c9239b-6836-4eec-b0c5-21cf00c8819a.png)

**Comment by 3pointer** [comment]
Actually the reason of checkpoint lag increase is network partition between nodes makes the part of tidb cluster not work as expect and according to current implement. PITR belongs to `part of tidb cluster`. when the tidb node(advance owner) cannot communicate with one tikv node for a long time. this part(PITR) of cluster cannot work as expected. and I believe there are same situation in ddl owner/cdc features.

**Comment by BornChanger** [comment]
Is the problem still active? @fubinzh

**Comment by BornChanger** [comment]
It's an expected behavior.

**Comment by fubinzh** [comment]
Closed the issue as it is by design.
