### ISSUE TITLE
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

### ISSUE THREAD

**Issue by SuJingyu111** [pingcap/tidb#38575]
Hi, I'm learning to use TiDB and tried to deploy it using Docker, following [tutorial](https://docs.pingcap.com/tidb/v3.0/test-deployment-using-docker). When I ran `mysql -h 127.0.0.1 -P 4000 -u root -D test`, it says `ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0`. 

I don't have that many nodes in the tutorial, so I deployed 1 pd server, 1 tikv server and 1 tidb server all on localhost. The commands I used to run the containers are:

1. PD:
```sh
docker run -d --name pd1   \
                  -p 2379:2379   \
                  -p 2380:2380   \
                  -v /etc/localtime:/etc/localtime:ro   \
                  -v /data:/data   \
                  pingcap/pd:latest   \
                  --name="pd1"  \
                  --data-dir="/data/pd1"   \
                  --client-urls="http://localhost:2379"   \
                  --advertise-client-urls="http://localhost:2379"   \
                  --peer-urls="http://localhost:2380"   \
                  --advertise-peer-urls="http://localhost:2380"   \
                  --initial-cluster="pd1=http://localhost:2380" 
```
2. TiKV:
```sh
docker run -d --name tikv1   \
                  -p 20160:20160   \
                  -v /etc/localtime:/etc/localtime:ro   \
                  -v /data:/data   \
                  pingcap/tikv:latest   \
                  --addr="localhost:20160"   \
                  --advertise-addr="localhost:20160"   \
                  --data-dir="/data/tikv1"   \
                  --pd="localhost:2379"  
```
3. TiDB:
```sh
docker run -d --name tidb   \
                  -p 4000:4000   \
                  -p 10080:10080   \
                  -v /etc/localtime:/etc/localtime:ro   \
                  pingcap/tidb:latest   \
                  --store=tikv   \
                  --path="localhost:2379"
```

Also, PD and TiDB containers seems to exit by themselves after a while. Runing `docker ps -a` after a few minutes and it shows:
![image](https://user-images.githubusercontent.com/55239247/196884052-4fe2c844-d014-449b-bb9a-253619bf7ff2.png)

I read a few issues with the same problem but they are all related to docker-compose instead of plain docker. Appreciate any help!

**Comment by Defined2014** [comment]
If you set `localhost` in docker env, it means the docker network instead of host network. This will cause tidb to fail to start.

I will close this issue, if you still have question, feel free to reopen it.
