### ISSUE TITLE
when simulate one AZ down，analyze-tc-tidb-0 memory abnormally rise

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#38579]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
simulate one AZ down for 10min

### 2. What did you expect to see? (Required)
no memory abnormally rise

### 3. What did you see instead (Required)
analyze-tc-tidb-0 memory abnormally rise
![image](https://user-images.githubusercontent.com/84712107/196908603-4f149d96-101f-4d63-96fe-f192bdd314fc.png)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v6.4.0-alpha
Edition: Community
Git Commit Hash: f343ffef6d9a0f3afd1d03491c8809e3506d09d8
Git Branch: heads/refs/tags/v6.4.0-alpha
UTC Build Time: 2022-10-11 11:10:16
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by chrysan** [comment]
Should be duplicated with https://github.com/pingcap/tidb/issues/39971，can you help verify if it can be reproduced with master? If cannot, we can close it.

**Comment by qw4990** [comment]
Can't reproduce this, please contact me if it occurs again.
