### ISSUE TITLE
Get TiFlash replica table region count by PD new API /pd/api/v1/stats/region\?count 

### ISSUE THREAD

**Issue by hehechen** [pingcap/tidb#38570]
## Enhancement
After this [PR](https://github.com/tikv/pd/pull/5610) merged, TiDB can get TiFlash replica table region count by PD new API `/pd/api/v1/stats/region\?count` to reduce the overhead of PD when there are many regions.

**Comment by CalvinNeo** [comment]
ref https://github.com/pingcap/tidb/issues/38480
