### ISSUE TITLE
fix a suspected go routine pool bug and improve the func task type

### ISSUE THREAD

**Issue by AlexStocks** [pingcap/tidb#3857]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
https://github.com/pingcap/tidb/blame/1592c7bc2873346565ab15ecfbc22749a775e014/util/goroutine_pool/gp.go#L106

Maybe the pool's lock should be used here.  Cause the lastRun user and assigner are not the same gr. 

What's more, the work func type is func() which can do so little type of work. 

2. What did you expect to see?

the lastRun type is time.Time which may be changed to int64 to store current time in second. and then you can load or store is by atomic. OR you lock is on line 106 by pool's mutex lock.

the work may be changed as follows:
     type WorkArg struct {
         inputArgss []interface{}
         returnValues []interface{}
     }

Then the work type is func(wa *WorkArg).

**Comment by shenli** [comment]
@AlexStocks Thanks for your feedback!
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
1. About the `lastRun`, no need to lock, because that goroutine is not put back to the pool yet, it won't be visited concurrently.
2. About the func type, closure is very powerful, you can do almost all you want with it. WorkArg has no benefits except make the API is ugly.

For example, anywhere you call

```
go func(a int, b string, c char) {
}()
```

you can change it to 

```
var a int
var b string
var c char
pool.Go(func() {
      //  a, b, c is available in the closure
})
```

**Comment by AlexStocks** [comment]
@tiancaiamao Your explanation is very splendid. Thank you for your timely feedback. I appreciate them so much.
