### ISSUE TITLE
CLUSTERED hint doesn't take effect

### ISSUE THREAD

**Issue by zhangjinpeng87** [pingcap/tidb#38608]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![2uBHDo7rGh](https://user-images.githubusercontent.com/19700528/197374724-16c9bfe9-322d-40a4-acb7-d398740b7c8d.jpg)

### 2. What did you expect to see? (Required)

Table t should have a clustered index.

### 3. What did you see instead (Required)

The CLUSTERED hint doesn't take effect.

### 4. What is your TiDB version? (Required)

Release Version: v6.3.0
Edition: Community
Git Commit Hash: ecd67531f1721d3e49eb15a202ac7c0ae02291ec

**Comment by jebter** [comment]
Deploying with tiup playground fails to reproduce, can you provide the cluster settings?
![image](https://user-images.githubusercontent.com/4425235/197443792-6167eddd-4f7a-437f-aa31-9260349dd605.png)

**Comment by zyguan** [comment]
@zhangjinpeng1987 Do you forget passing `--comments` to the mysql command?

**Comment by jebter** [comment]
Please try the latest version. The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
