### ISSUE TITLE
Supports LocaltionLabels in Placement Policy to specify survival goal

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#38605]
## Feature Request

**Is your feature request related to a problem? Please describe:**
 users hoped that the scale of high availability is controllable, not for the entire database.  they want to distribute data across regions with specified tables. Such as:
 
![image](https://user-images.githubusercontent.com/6428910/197327433-78ed0fd8-aab5-4a11-a9ee-a90e479e6729.png)

**Describe the feature you'd like:**

Supports SQL Placement Policy Like :
```
ALTER PLACEMENT POLICY myplacementpolicy FOLLOWERS=5 SURVIVAL_PREFERENCES=["region", "zone", "host"]; 
```
or 
```
ALTER PLACEMENT POLICY myplacementpolicy FOLLOWERS=5 LOCATION_LABLES=["region", "zone", "host"]; 
```

**Describe alternatives you've considered:**

PD Placement rules has `LocaltionLabels` filed,  you have deployed [region,zone,host] that defines a three-layer topology: the cluster has multiple Regions, each Region  has multiple zone(Availability Zone), and each rack has multiple hosts. When performing schedule, PD first tries to place the Region's peers in different Region. If this try fails (such as there are three replicas but only two regions in total), PD guarantees to place these replicas in different Zones. If the number of racks is not enough to guarantee isolation, then PD tries the host-level isolation.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by nolouch** [comment]
PTAL @SunRunAway

**Comment by SunRunAway** [comment]
I like this design!

Should throw an error if follower_constrants are conflicts with `SURVIVAL_PREFERENCES`
For example:
```
ALTER PLACEMENT POLICY myplacementpolicy FOLLOWERS=5 FOLLOWER_CONSTRAINTS="{+region=us-east-1: 5}"; SURVIVAL_PREFERENCES=["region", "zone", "host"]; 
```

**Comment by wxiaoke** [comment]
<img width="839" alt="image" src="https://user-images.githubusercontent.com/38338933/200983142-7e30a93f-cf92-4a81-ae54-faa5fa20e4d9.png">
I have a question about your design: why FOLLOWERS=5? according to the document :https://docs.pingcap.com/tidb/stable/placement-rules-in-sql#option-reference, FOLLOWERS=5 means that there will be 6 replicas of the data (5 followers and 1 leader).

**Comment by SunRunAway** [comment]
> <img alt="image" width="839" src="https://user-images.githubusercontent.com/38338933/200983142-7e30a93f-cf92-4a81-ae54-faa5fa20e4d9.png">
> 
> I have a question about your design: why FOLLOWERS=5? according to the document :https://docs.pingcap.com/tidb/stable/placement-rules-in-sql#option-reference, FOLLOWERS=5 means that there will be 6 replicas of the data (5 followers and 1 leader).

@wxiaoke Sorry, edited to 4
