### ISSUE TITLE
Update the handling of COM_SLEEP

### ISSUE THREAD

**Issue by igxlin** [pingcap/tidb#38612]
## Enhancement

The current tidb (commit `41518c9e02`) handles `COM_SLEEP` specially and doesn't take it as an unknown command.

```go
// server/conn.go:(*clientConn).dispatch()
	case mysql.ComSleep:
		// TODO: According to mysql document, this command is supposed to be used only internally.
		// So it's just a temp fix, not sure if it's done right.
		// Investigate this command and write test case later.
		return nil
```

However, the current mysql (commit `a246bad7`) takes it as an unknown command and raise an error. 

```c++
// sql/sql_parse.cc:dispatch_command()
    case COM_SLEEP:
    case COM_CONNECT:         // Impossible here
    case COM_TIME:            // Impossible from client
    case COM_DELAYED_INSERT:  // INSERT DELAYED has been removed.
    case COM_END:
    default:
      my_error(ER_UNKNOWN_COM_ERROR, MYF(0));
      break;
```

Should we follow the mysql implementation to return unknown error when handling this command?

**Comment by xhebox** [comment]
Which version is the mysql? If it is mysql5, we should follow.

If it is a newer version, from the point of compatibility, it is best to be silent.

**Comment by igxlin** [comment]
> Which version is the mysql? If it is mysql5, we should follow.
> 
> If it is a newer version, from the point of compatibility, it is best to be silent.

@xhebox , in mysql 5.7, it is also taken as an unknown command and error is raised. 

Source code: https://github.com/mysql/mysql-server/blob/c4f63caa8d9f30b2850672291e0ad0928dd89d0e/sql/sql_parse.cc#L1890

```c++
  case COM_SLEEP:
  case COM_CONNECT:				// Impossible here
  case COM_TIME:				// Impossible from client
  case COM_DELAYED_INSERT: // INSERT DELAYED has been removed.
  case COM_END:
  default:
    my_message(ER_UNKNOWN_COM_ERROR, ER(ER_UNKNOWN_COM_ERROR), MYF(0));
    break;
  }
```

**Comment by xhebox** [comment]
> I will create a PR on it if it is OK to you.

Sure, thanks for your contribution.
