### ISSUE TITLE
nightly version, lightning import report " invalid compression type 'bak'"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#38615]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

/tidb-lightning \"-backend\" \"tidb\" \"-sorted-kv-dir\" \"/tmp/sorted-kv-dir\" \"-d\" \"s3://nfs/fubin/dbgen/line_break/CR?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9000&force-path-style=true\" \"-pd-urls\" \"target-pd.fb-debug-testbed-75jdz:2379\" \"-tidb-host\" \"target-tidb.fb-debug-testbed-75jdz\" \"-tidb-port\" \"4000\" \"-tidb-user\" \"root\" \"-tidb-password\" \"\" \"-c\" \"/tmp/tidb-lightning.toml\"", "timeout": "10m", "resource name": "lightning"}

### 2. What did you expect to see? (Required)
import success
### 3. What did you see instead (Required)
 tidb lightning encountered error: [Lightning:Storage:ErrStorageUnknown]list file failed: apply file routing on file 'test.t3-schema.sql.bak' failed: invalid compression type 'bak'

### 4. What is your TiDB version? (Required)

/ # ./tidb-lightning -V
Release Version: v6.4.0-alpha
Git Commit Hash: 85b53e18781d459074f1637998014b37231283b0
Git Branch: heads/refs/tags/v6.4.0-alpha
Go Version: go1.19.1
UTC Build Time: 2022-10-22 11:04:32
Race Enabled: false

**Comment by niubell** [comment]
adjust the test case and ignore the bak/BAK check, some bak/BAK files may not be compressed files.
