### ISSUE TITLE
pitr task return error when inject node fault during flashback

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#38630]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. install a tidb cluster with pitr task started
2. run workload for 10 minutes
3. flashback to 10 minutes ago
4. during flashback restart and stop/start  tikv/pd/tidb

### 2. What did you expect to see? (Required)
after cluster is recovered, flashback command is executed successfully
data is consistent.
### 3. What did you see instead (Required)
```code
 Total 1 Tasks.
> #1 <
                    name: pitr
                  status: ○ ERROR
                   start: 2022-10-25 10:04:46.463 +0800
                     end: 2090-11-18 22:07:45.624 +0800
                 storage: s3://tmp/br-lt-log-backup
             speed(est.): 0.00 ops/s
      checkpoint[global]: 2022-10-25 13:01:04.363 +0800; gap=14m52s
          error[store=5]: KV:LogBackup:RaftReq
error-happen-at[store=5]: 2022-10-25 13:07:04.187 +0800; gap=8m53s
  error-message[store=5]: retry time exceeds: and error and error failed to get initial snapshot: failed to get the sn
                          apshot (region_id = 26102): Error during requesting raftstore: message: "region 26102 is in 
                          the flashback progress" flashback_in_progress { region_id: 26102 }: failed to get initial sn
                          apshot: failed to get the snapshot (region_id = 26102): Error during requesting raftstore: m
                          essage: "region 26102 is in the flashback progress" flashback_in_progress { region_id: 26102
                           }: failed to get initial snapshot: failed to get the snapshot (region_id = 26102): Error du
                          ring requesting raftstore: message: "region 26102 is in the flashback progress" flashback_in
                          _progress { region_id: 26102 }
```

```code
MySQL [flashback2]> admin check table user_data1;
ERROR 8223 (HY000): data inconsistency in table: user_data1, index: k_1, handle: 22152, index-values:"" != record-values:"handle: 22152, values: [KindMysqlTime 2022-10-25 13:03:13]"
MySQL [flashback2]> 
```

**Comment by seiya-annie** [comment]
operation:
 1030  tiup br log status
 1031  tiup cluster restart flashback -R tikv
 1032  tiup cluster restart flashback -R tidb
 1033  tiup cluster restart flashback -R pd
 1034  tiup cluster restart flashback -R tikv
 1035  tiup cluster stop flashback -R tidb
 1036* tiup cluster start flashback -R 
 1037  tiup cluster stop flashback -R pd
 1038  tiup cluster start flashback -R pd
 1039  tiup br log status

**Comment by 3pointer** [comment]
It looks like two different issue. @seiya-annie 
1. log backup task stopped.
2. flash back data inconsistent.

**Comment by seiya-annie** [comment]
yes, data inconsistent is tracked by https://github.com/tikv/tikv/issues/13672

**Comment by joccau** [comment]
The PiTR task do not get error at v6.5.0 when do `flashback`.
