### ISSUE TITLE
TiDB Ansible deploy error

### ISSUE THREAD

**Issue by wolaiye1010** [pingcap/tidb#3863]
到 启动这一步到时候报错 ansible-playbook start.yml，
错误内容如下：
TASK [wait up] **********************************************************************************************************************************************************************
fatal: [10.9.193.135]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for PID:/home/tidb/deploy/status/tikv.pid to stop."}
fatal: [10.9.193.136]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for PID:/home/tidb/deploy/status/tikv.pid to stop."}
fatal: [10.9.193.121]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for PID:/home/tidb/deploy/status/tikv.pid to stop."}
	to retry, use: --limit @retry_files/start.retry

PLAY RECAP **************************************************************************************************************************************************************************
10.9.193.119               : ok=23   changed=3    unreachable=0    failed=0
10.9.193.121               : ok=21   changed=3    unreachable=0    failed=1
10.9.193.135               : ok=19   changed=2    unreachable=0    failed=1
10.9.193.136               : ok=19   changed=2    unreachable=0    failed=1
localhost                  : ok=1    changed=0    unreachable=0    failed=0

我的配置文件：
# TiDB Cluster Part
[tidb_servers]
10.9.193.119
10.9.193.121

[pd_servers]
10.9.193.119
10.9.193.121

[tikv_servers]
10.9.193.135
#10.9.193.137
10.9.193.121
10.9.193.136

# Monitoring Part
[monitoring_servers]
10.9.193.119

[grafana_servers]
10.9.193.119

[monitored_servers:children]
tidb_servers
tikv_servers
pd_servers

## Binlog Part
[pump_servers:children]
tidb_servers

[cistern_servers]

[drainer_servers]

[pd_servers:vars]
# location_labels = ["zone","rack","host"]

## Global variables
[all:vars]
deploy_dir = /home/tidb/deploy

## Connection
# ssh via root:
 ansible_user = root
 ansible_become = true
 ansible_become_user = work

# ssh via normal user
#ansible_user = tidb

cluster_name = test-cluster

# misc
enable_elk = False
enable_firewalld = False
enable_ntpd = False
machine_benchmark = True
set_hostname = False

# binlog trigger
enable_binlog = False

**Comment by buggithubs** [comment]
@wolaiye1010 

0. 主机系统是否为ubuntu? 
    1. ubunut 注释become与become_user；修改ansible_user = work
1. 检查文件权限`/home/tidb/deploy/status/tikv.pid` 是否为`work`
2. 可以尝试登录节点手动执行，然后查看是否有错误信息。
3. 以上均无误，可以尝试多次执行`stop.yml & start.yml`。

**Comment by wolaiye1010** [comment]
@buggithubs ,
主机系统为 CentOS 6.6
/home/tidb/deploy/status/tikv.pid  是work 权限
多次 stop.yml & start.yml 都不行，报同一个错误
测试主机不能链接外网，但我的localhost可以，我是通过 localhost 进行的ansible-playbook start.yml

**Comment by zimulala** [comment]
@LinuxGit

**Comment by LinuxGit** [comment]
@wolaiye1010 refer to https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md. Please use CentOS 7 or later, default TiDB binaries is for CentOS7. And pd instances should be one or three.You can new issues in https://github.com/pingcap/tidb-ansible if you encounter any other deployment problems.

**Comment by wolaiye1010** [comment]
@LinuxGit ,
Think you, CentOS 7  is ok!
