### ISSUE TITLE
Unexpected Results by RIGHT JOIN

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#38654]
### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t0(c0 INT);
CREATE TABLE t1(c0 INT);
INSERT INTO t1 VALUES (1);

SELECT * FROM t0 RIGHT JOIN t1 ON t0.c0; -- {NULL|1}
SELECT ((NOT ('i'))AND(t0.c0)) IS NULL FROM  t0 RIGHT JOIN t1 ON t0.c0; -- {1}
SELECT * FROM t0 RIGHT JOIN t1 ON t0.c0 WHERE ((NOT ('i'))AND(t0.c0)) IS NULL; -- empty set
```

### 2. What did you expect to see? (Required)
`SELECT * FROM t0 RIGHT JOIN t1 ON t0.c0;` returns non-empty result and ` ((NOT ('i'))AND(t0.c0)) IS NULL` is evaluated to `true` in the second SELECT, but the third `SELECT` returns empty result.

### 4. What is your TiDB version? (Required)

```
| Release Version: v6.4.0-alpha-133-g6c55faf03
Edition: Community
Git Commit Hash: 6c55faf034e8c205ffd23126829c637fb8a47451
Git Branch: master
UTC Build Time: 2022-10-26 07:47:53
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: true
Store: unistore |
```

**Comment by wshwsh12** [comment]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/14054293/198209965-b73cabc4-abb6-4acd-a0e0-510bef208244.png">

It looks like the last sql using inner join, but the other sqls use right outer join.  I think it should be a planner issue. @winoros @AilinKid  PTAL

**Comment by xuyifangreeneyes** [comment]
It seems to relate to #38430

**Comment by bajinsheng** [comment]
You mean to focus on testing the JOIN? Currently, we don't support generating specific kinds of test cases but aim to generate diverse test case. Perhaps after it is fixed, I continue to test if there is any bug.

**Comment by winoros** [comment]
> You mean to focus on testing the JOIN? Currently, we don't support generating specific kinds of test cases but aim to generate diverse test case. Perhaps after it is fixed, I continue to test if there is any bug.

@bajinsheng, maybe JOIN is not very necessary. This issue is just like the previous issue

> It seems to relate to https://github.com/pingcap/tidb/pull/38430

We will test the predicates upon an outer join, checking whether it can filter all rows generated by OUTER JOIN's null supplement. If we test successfully, the outer join can be simplified as an inner join.

When there are `NOT`, `IS NULL`, and `IS NOT NULL` in predicates, the checking function may easily meet bugs. TiDB needs some complex expressions combining many `NOT` and `IS NULL`.

**Comment by bajinsheng** [comment]
The TLP oracle in SQLancer will generate these kinds of predicates. [link](https://github.com/sqlancer/sqlancer/blob/master/src/sqlancer/tidb/oracle/TiDBTLPWhereOracle.java)
