### ISSUE TITLE
insert very slow with go

### ISSUE THREAD

**Issue by jimmykuu** [pingcap/tidb#3866]
when I use `github.com/go-sql-driver/mysql` package insert 1000 rows data into TiDB, very slow.

First create a table just two fields.
```
CREATE TABLE `speed_test` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
```

the go code like that

```go
package main

import (
	"database/sql"
	"fmt"
	"time"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	db, err := sql.Open("mysql", "root:root@tcp(127.0.0.1:4000)/test?charset=utf8")

	t0 := time.Now()

	stmt, err := db.Prepare("INSERT INTO speed_test(name) VALUES(?)")
	if err != nil {
		panic(err)
	}
	defer stmt.Close()

	for i := 0; i < 1000; i++ {
		stmt.Exec("go mysql")
	}

	fmt.Println(time.Now().Sub(t0))
}
```
This takes more than 23s. I tried `github.com/ziutek/mymysql` and use transaction, almost cost the same time.

Use this code insert into MySQL, just cost 379ms.

I write a Python code test insert into TiDB, It's fast, and just cost 280ms.

```python
import time

from mysql import connector

conn = connector.connect(user='root', password='root', host='127.0.0.1', port=4000, database='test')
cur = conn.cursor()
t0 = time.time()
for i in range(1000):
    cur.execute("INSERT INTO speed_test(name) VALUES('name')")

conn.commit()
print time.time() - t0
```

Do I need to notice something when I insert record use go?

$ tidb-server -V
Git Commit Hash: 6d48faa8d2fdc8dd8207f784fd0ff47c2e838a59
UTC Build Time:  2017-07-23 07:54:25
```

**Comment by ngaut** [comment]
Have you checked the goroutine block profile? May be  goroutines are blocked somewhere @jimmykuu
We will take a deep look later.

**Comment by winkyao** [comment]
python client set autocommit = 0, and commit all the operation in one transaction, so it is faster than golang. I modify the golang client code to use one transaction, same as python, it run faster than python.

```
package main

import (
 "database/sql"
 "fmt"
 "time"

 _ "github.com/go-sql-driver/mysql"
)

func main() {
 db, err := sql.Open("mysql",
  "root:@tcp(xxx.xxx.xx.xxx:4000)/test?charset=utf8")
 t0 := time.Now()
 tx, _ := db.Begin()
 stmt, err := tx.Prepare("INSERT INTO speed_test(name) VALUES('golang')")
 if err != nil {
  panic(err)
 }

 for i := 0; i < 1000; i++ {
  stmt.Exec()
 }
 tx.Commit()
 stmt.Close()
 fmt.Println(time.Now().Sub(t0))
}

```

**Comment by winkyao** [comment]
@ngaut I am going to close this issue.
