### ISSUE TITLE
tidb oom when inject pd or tikv fault

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#38680]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

inject pd or tikv fault

### 2. What did you expect to see? (Required)
tidb not oom

### 3. What did you see instead (Required)
tidb  oom
log：http://minio.pingcap.net:42041/buckets/test-infra-testground/browse/YXJjaGl2ZS9nbGgtbWFzdGVyLXA0emx4L3RjLXRpZGItMC9vb21fcmVjb3JkL3JlY29yZDIwMjItMTAtMjZUMjI6MDQ6MTlaLw==
![image](https://user-images.githubusercontent.com/84712107/198204539-327bdce0-57bc-4ae4-9112-15906f9c1f8d.png)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v6.4.0-alpha
Edition: Community
Git Commit Hash: 0f6baa3f9b3eb7daa114f43a84fa6961ea4b0ab3
Git Branch: heads/refs/tags/v6.4.0-alpha
UTC Build Time: 2022-10-26 11:11:07
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by qw4990** [comment]
Can't reproduce this issue, please contact me if it occurs again.
