### ISSUE TITLE
IndexHashJoin got performance regression because of usage of sync.Pool

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#38695]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Internal process to reproduce(incall-211).

Performance of IndexHashJoin_242 got regression compared to v6.1.0. https://github.com/pingcap/tidb/pull/38591 revert this https://github.com/pingcap/tidb/pull/34878, IndexHashJoin_242 is normal again.

### 2. What did you expect to see? (Required)

![image](https://user-images.githubusercontent.com/7493273/198266106-a9598af1-f8ba-4df4-88de-055b4c54a12e.png)

### 3. What did you see instead (Required)
NewIterator4Slice() takes too much cpu.

![image](https://user-images.githubusercontent.com/7493273/198265978-4621c32e-9da8-4332-852f-16564d70c17e.png)

### 4. What is your TiDB version? (Required)
v6.2/v6.3

**Comment by XuHuaiyu** [comment]
Does it mean IndexHashJoin does not invoke the pool correctly?

**Comment by guo-shaoge** [comment]
Multiple goroutines of `IndexHashJoin` call `NewIterator4Slice` concurrently for each outer row(500W), I think the there are some lock contentions in `sync.Pool.Get()`
