### ISSUE TITLE
Stmt-summary.max-sql-length is useless and ignored by TiDB

### ISSUE THREAD

**Issue by AricSu** [pingcap/tidb#38757]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Deploy an cluster with version v6.3.0 and modify [stmt-summary.max-sql-length](https://docs.pingcap.com/zh/tidb/v5.3/tidb-configuration-file#max-sql-length);
![image](https://user-images.githubusercontent.com/76909042/198939907-3969f056-7228-4a50-a942-e1dcd1ed943d.png)
2. Command `tiup reload -R tidb` and check `tidb_stmt_summary_max_sql_length` by mysql client terminal;
![image](https://user-images.githubusercontent.com/76909042/198940046-9cedbd43-b719-4f35-871e-aca7eab57180.png)

3. I've tried v4.0.0 and v6.3.0 on TiDB about it.And, both of them have that problem.

4. It seems be caursed by this pr --> https://github.com/pingcap/tidb/pull/15682

5. And, i looked up one test case which has showed the problem --> https://internal.pingcap.net/jira/browse/TICASE-2507 

so, please fix this bug ASAP, thx.

### 2. What did you expect to see? (Required)
```
>show variables like '%tidb_stmt_summary_max_sql_length%';
+----------------------------------+-------+
| Variable_name                    | Value |
+----------------------------------+-------+
| tidb_stmt_summary_max_sql_length | 10  |
+----------------------------------+-------+
1 row in set (0.01 sec)
```

### 3. What did you see instead (Required)
```
>show variables like '%tidb_stmt_summary_max_sql_length%';
+----------------------------------+-------+
| Variable_name                    | Value |
+----------------------------------+-------+
| tidb_stmt_summary_max_sql_length | 4096  |
+----------------------------------+-------+
1 row in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

tidb v6.3.0

**Comment by aytrack** [comment]
All these configuration related to the statement summary tables items are removed since from 6.0.0.  You can check the [doc](https://docs.pingcap.com/tidb/v6.0/release-6.0.0-dmr#configuration-file-parameters) for details.

**Comment by jansu-dev** [comment]
thx for your response, and there are a best way to delete `stmt-summary.max-sql-length` and related parameters on offical website  for v4.0 ~ v6.0. Because of confusing for users.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it. You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese) or https://ask.pingcap.com/(English)
