### ISSUE TITLE
BR: 6.2.0 system table mysql.user can't be restored to 6.4.0

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#38785]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb changed mysql.user schema in 6.4.0
version95	add a column `User_attributes` to `mysql.user`
version98	add a column `Token_issuer` to `mysql.user`

when restore 6.2.0 mysql.user to 6.4.0 will report :
Error: column count mismatch, table: user, col in cluster: 38, col in backup: 37: [BR:Restore:ErrR

### 2. What did you expect to see? (Required)
restore success
### 3. What did you see instead (Required)
Error: column count mismatch, table: user, col in cluster: 38, col in backup: 37: [BR:Restore:ErrR
### 4. What is your TiDB version? (Required)

master

**Comment by IANTHEREAL** [comment]
@bb7133 Hi, do you know who is responsible for this modification(mysql.user schema change)?

**Comment by seiya-annie** [comment]
@wjhuang2016 PTAL
