### ISSUE TITLE
`br log truncate` shows 0 files and remove nothing but s3 data exists

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#38781]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. `/br log truncate --until "2022-10-28 08:45:08.963 +0000"  -s 'xxxxxxx'`

### 2. What did you expect to see? (Required)
1. shows file num is not 0
2. can remove data
### 3. What did you see instead (Required)
1. file num is zero
`
Detail BR log in /tmp/br.log.2022-11-01T03.39.07Z\n
Reading Metadata... DONE; take = 1m19.417501865s \n
We are going to remove 0 files, until 2022-10-28 08:45:08.9630.
`
2. data has not been removed

### 4. What is your TiDB version? (Required)
/br --version
Release Version: v6.4.0-alpha
Git Commit Hash: aff0c3693f11dacd68525423af9d7187a45b9a82
Git Branch: heads/refs/tags/v6.4.0-alpha
Go Version: go1.19.1
UTC Build Time: 2022-10-08 11:01:15
Race Enabled: false

**Comment by joccau** [comment]
- The kv event in log files is rollback event. the start-ts == commit-ts == 436902780927213670
- The detail about log:
```
                {
                    "sha256": "4aU/u7U9/SOfCxYJsfbsUWKkFYOHYhRQHKKbvAa24YM=",
                    "number_of_entries": 180,
                    "min_ts": 436902780927213670,
                    "max_ts": 437045495931076710,
                    "resolved_ts": 437045414653067349,
                    "region_id": 114605769,
                    "start_key": "dIAAAAAAABz/fF9ygAAAAAD/AvC9AAAAAAD6+e9Nd58n/34=",
                    "end_key": "dIAAAAAAABz/fF9ygAAAAAD/CJ8EAAAAAAD6+e9NfkcP/wc=",
                    "cf": "write",
                    "type": 1,
                    "table_id": 7292,
                    "length": 19512,
                    "min_begin_ts_in_default_cf": 436902780927213670,
                    "range_offset": 2323010,
                    "range_length": 6178,
                    "compression_type": 3
                },
```
- The detail about key
```
mok dIAAAAAAAB\16z/fF9ygAAAAAD/Bja+AAAAAAD6+e/PPE1z/5k=
"dIAAAAAAABz/fF9ygAAAAAD/Bja+AAAAAAD6+e/PPE1z/5k="
└─## decode base64 key
  └─"t\200\000\000\000\000\000\034\377|_r\200\000\000\000\000\377\0066\276\000\000\000\000\000\372\371\357\317<Ms\377\231"
    ├─## decode mvcc key
    │ ├─"t\200\000\000\000\000\000\034|_r\200\000\000\000\000\0066\276"
    │ │ ├─## table prefix
    │ │ │ └─table: 7292
    │ │ └─## table row key
    │ │   ├─table: 7292
    │ │   └─row: 407230
    │ └─ts: 436902780927213670 (2022-10-25 06:50:43.747 +0800 CST)
    └─## table prefix
      └─table: 7423
```
