### ISSUE TITLE
Global Resource Quota Control 

### ISSUE THREAD

**Issue by nolouch** [pingcap/tidb#38825]
# Feature Request
## Background
A Global Resource Control mechanism that limits multiple applications' resource usage in a shared TiDB cluster, avoids interference between applications.

## Design
RFC: https://github.com/pingcap/tidb/blob/master/docs/design/2022-11-25-global-resource-control.md

###  Interface and Configuration Part
Here a tiny example of the SQL interface.
```
CREATE RESOURCE GROUP `group_name` RRU_PER_SECOND=10000, WRU_PER_SECOND=10000.
ALTER RESOURCE GROUP `group_name` RRU_PER_SECOND= 20000;
/* bind resource group to user*/
ALTER USER user_name RESOURCE GROUP resouce_group_name;
/* reset to default systemn resource group for the current session*/
SET CURRENT RESOURCE GROUP DEFAULT;
```
Above the example shown, it's easy to set up for users or tenants. In theory, we can measure at the requested level,  it is able to aggregate at different levels, so it is possible to bind the resource unit limit to the user or the session to a group.

### SQL Interface
- [ ] Supports Resource Group Syntax
    - [x] Supports Create/Alter Syntax https://github.com/pingcap/tidb/pull/39546  @nolouch 
- [ ] DDL Part
     - [x] Supports Create/Alter/Delete Resource Group https://github.com/pingcap/tidb/pull/40188 @nolouch 
     - [x] Supports Bind Resource Group for Users  https://github.com/pingcap/tidb/pull/39561
     - [x] https://github.com/pingcap/tidb/issues/40380
- [ ] Usability
    - [x] Show Resource Groups with SQL interface
    - [x] #39781
    - [ ] Estimate total RU in a cluster @BornChanger  @glorv 
    - [ ] History RU Metrics @JmPotato 
        - [x] https://github.com/tikv/pd/issues/5854 
        - [x] https://github.com/pingcap/tidb/issues/40526
- [x] Privilege check & constraint syntax check.  https://github.com/pingcap/tidb/pull/40632 @tiancaiamao  
- [ ] Internal Job priority push to tikv/tiflash, like DDL, Analyze  @tiancaiamao @glorv 
- [ ] Test&Compatibility
    - [x] https://github.com/pingcap/tidb/issues/40371
    - [x] https://github.com/pingcap/tidb/issues/40370

### Proto
- [x] Protobuf relative
    - [x] https://github.com/pingcap/kvproto/pull/1019
    - [x] https://github.com/pingcap/kvproto/pull/1029

### Resource Group Meta Manager
- [x] https://github.com/tikv/pd/issues/5784  @nolouch 
    - https://github.com/tikv/pd/pull/5785 
- [x] Resource Group Sync to storage  https://github.com/tikv/pd/issues/5794 @HuSharp
    - [x] https://github.com/tikv/tikv/pull/14022
    
### Storage Node Level Control [For Scheduling]

- [x]  Supports make priority by resource group information
- [x]  Supports scheduling for read path  @glorv
    - [x] supports priority queue in yatp. https://github.com/tikv/yatp/pull/72 
    - [x] Implement mclock scheduling for read path in tikv https://github.com/tikv/tikv/pull/14001@glorv 
- [x] Supports scheduling for write path @Connor1996 
    - [x] https://github.com/tikv/tikv/pull/14002
    - [ ] https://github.com/tikv/tikv/pull/14004
    - [x] https://github.com/tikv/tikv/pull/14057
    
### Global Quote Flow Control Module [For Quota Limit] 
- [x] https://github.com/pingcap/tidb/pull/40732 @nolouch
- [x]  Global Token Buckets: grant quota to the client, consume in client  @nolouch @CabinfeverB 
    - [x] https://github.com/tikv/pd/pull/5809
    - [x] https://github.com/tikv/pd/pull/5810
    - [x] https://github.com/tikv/pd/pull/5811
    - [x] https://github.com/tikv/pd/pull/5868
- [ ] #40645 @JmPotato 
     - [x] https://github.com/tikv/client-go/pull/648 
     - [x] https://github.com/tikv/pd/pull/5862 @JmPotato 
- [ ]  Aggregate resource consumption of resource groups in each client 
     - [x] https://github.com/tikv/pd/pull/5855/
     
### Decouple priority
- [ ] 

#### BR #42266
- [x] Disable BR for v7.0 #42267

**Comment by BornChanger** [comment]
@nolouch please make an entry for @Connor1996 on write path scheduling

**Comment by BornChanger** [comment]
and make an entry to change protobuf for @hnes

**Comment by zhangjinpeng1987** [comment]
Better to add a command to show the status of current resource groups and which user has bind to which resource group.
