### ISSUE TITLE
The same SQL statement query cluster_slow_query and slow_query are inconsistent

### ISSUE THREAD

**Issue by jacktd9** [pingcap/tidb#38858]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Architecture information：6tikv(3 engines='tikv,tiflash,tidb'，3 engines='tiflash')

![image](https://user-images.githubusercontent.com/63033738/199673797-3511c2a6-9279-4321-892a-c61013e08b1b.png)
![image](https://user-images.githubusercontent.com/63033738/199674098-4f631350-7c59-47ed-88d8-a85935dc3fac.png)

If only count(*) is checked without where condition, the number of results of cluster_slow_query is greater than slow_query
![image](https://user-images.githubusercontent.com/63033738/199674158-21db0aad-865f-4a3e-9be2-60c36b0dfdcf.png)

### 2. What did you expect to see? (Required)
return the same result

### 3. What did you see instead (Required)
The return results are not the same

### 4. What is your TiDB version? (Required)
v5.4.1

**Comment by King-Dylan** [comment]
<img width="2314" alt="image" src="https://user-images.githubusercontent.com/50897894/200296432-58efa9cf-644b-4657-97e2-61f9462eaccc.png">

**Comment by crazycs520** [comment]
The issue was fixed by https://github.com/pingcap/tidb/pull/34322
