### ISSUE TITLE
ddl report "TiKV server timeout" when start a down tikv node 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#38852]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. 5 tikv nodes, stop 2 before ddl 
2. run flashback ddl
3. during flashback, start 1 tikv node

### 2. What did you expect to see? (Required)
ddl has no affect 
### 3. What did you see instead (Required)
```code
MySQL [tpcc]> flashback cluster to timestamp '2022-11-03 12:46:33';
ERROR 9002 (HY000): TiKV server timeout
MySQL [tpcc]> 
MySQL [tpcc]> 
MySQL [tpcc]> admin show ddl jobs;
```
### 4. What is your TiDB version? (Required)

master

**Comment by seiya-annie** [comment]
client will keep tring to get ddl job status in ddl history table. if the region of history table is in an unavailable tikv node, will report this error. this is not friendly to the user.

**Comment by Defined2014** [comment]
I think it's expected now. When 2 tikvs are down, this region cannot served, so tidb will reties many times and got an error. It's not a bug, so just change it to enhancement.
