### ISSUE TITLE
column must not null in engine CSV

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#3890]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
create table t1(a int) engine = csv;
```

2. What did you expect to see?

```
mysql> create table t1(a int) engine = csv;
ERROR 1178 (42000): The storage engine for the table doesn't support nullable columns
```

3. What did you see instead?

```
mysql> create table t1(a int) engine = csv;
Query OK, 0 rows affected (0.08 sec)
```

**Comment by morgo** [comment]
I believe TiDB has the correct behavior here.  It is [documented](https://www.pingcap.com/docs/sql/mysql-compatibility/#storage-engines) that TiDB allows other engines for compatibility, but behaves like InnoDB.

**Comment by nullnotnil** [comment]
I am going to close this issue as won't fix. We can revisit if it becomes known to cause any user issues.
