### ISSUE TITLE
Golang indexing servers don't pick up your project

### ISSUE THREAD

**Issue by yurivict** [pingcap/tidb#38921]
... because the module URL doesn't end with version.

[This line](https://github.com/pingcap/tidb/blob/master/go.mod#L1) should read ```github.com/pingcap/tidb/v6``` for a project with version 6.x.

**Comment by yurivict** [comment]
@lance6716 
Any chance to fix this?

**Comment by lance6716** [comment]
we choose not to follow the golang semantic version, one reason is we release major versions based on time and user's request rather than when breaking public API.
