### ISSUE TITLE
Why the data dir of TiKV disappear.

### ISSUE THREAD

**Issue by wolaiye1010** [pingcap/tidb#3893]
`为什么 TiKV 数据目录不见了

TiKV 的 --data-dir 参数默认值为 /tmp/tikv/store，在某些虚拟机中，重启操作系统会删除 /tmp 目录下的数据，推荐通过 --data-dir 参数显式设置 TiKV 数据目录`

  请问，通过TiDB Ansible 部署的集群，如果/tmp目录下内容被清除，存储的在tidb 里的数据会丢失吗，
如果会，inventory.ini 怎么设置才会避免这种情况呢？， 因为公司运维有脚本定期清理／tmp

**Comment by shenli** [comment]
Please use other path for TiKV's data path. You can config it in TiKV's yaml file.
