### ISSUE TITLE
tidb status port become unresponsive after enabling TLS config 

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#38977]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Found by our CI, it hang recently. https://ci.pingcap.net/blue/organizations/jenkins/br_ghpr_unit_and_integration_test/detail/br_ghpr_unit_and_integration_test/13913/pipeline/107/

To be more specifit, the bug is that after enabling TLS config, the 10080 port become unresponsive.

### 2. What did you expect to see? (Required)

It should work

### 3. What did you see instead (Required)

Not work as expected

### 4. What is your TiDB version? (Required)

v6.4

**Comment by bb7133** [comment]
Close this issue by #38985
