### ISSUE TITLE
Is generated foreign key name need to be compatible with mysql?

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb#39095]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tidb generated foreign key name is "fk_1", while mysql is "t2_ibfk_1".
so is it need to be compatible with mysql?
mysql:     static char dict_ibfk[] = "_ibfk_";

mysql>  CREATE TABLE t1(a INT PRIMARY KEY);
mysql> CREATE TABLE t2(a INT PRIMARY KEY, b INT, c INT, FOREIGN KEY (b) REFERENCES t1(a));
mysql> show create table t2\G

### 2. What did you expect to see? (Required)

mysql> show create table t2\G
*************************** 1. row ***************************
       Table: t2
Create Table: CREATE TABLE `t2` (
  `a` int NOT NULL,
  `b` int DEFAULT NULL,
  `c` int DEFAULT NULL,
  PRIMARY KEY (`a`),
  KEY `b` (`b`),
  CONSTRAINT `t2_ibfk_1` FOREIGN KEY (`b`) REFERENCES `t1` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
1 row in set (0.00 sec)

### 3. What did you see instead (Required)

mysql> show create table t2\G
*************************** 1. row ***************************
       Table: t2
Create Table: CREATE TABLE `t2` (
  `a` int(11) NOT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  PRIMARY KEY (`a`) /*T![clustered_index] CLUSTERED */,
  CONSTRAINT `fk_1` FOREIGN KEY (`b`) REFERENCES `test`.`t1` (`a`) /*T![FOREIGN KEY] INVALID */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin

### 4. What is your TiDB version? (Required)

master

**Comment by crazycs520** [comment]
In generated foreign key names, I prefer not compatible with MySQL, I think the behavior of MySQL is strange.
