### ISSUE TITLE
Support SQL like `select * from t where d < date '1998-01-01';`

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#3909]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
create table t (d date);
insert into t values ("1997-01-02");
select * from t where d < date '1998-01-01';

2. What did you expect to see?
+------------+
| d          |
+------------+
| 1997-01-02 |
+------------+

3. What did you see instead?
ERROR 1105 (HY000): line 0 column 17 near " date '1998-01-01'" (total length 35)

4. What version of TiDB are you using (`tidb-server -V`)?
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------+
| tidb_version()                                                                                |
+-----------------------------------------------------------------------------------------------+
| Git Commit Hash: a178c024e333384ecc4bc6d4afd69767f10fe1ad
UTC Build Time: 2017-07-24 04:17:43 |
+-----------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

**Comment by breeswish** [comment]
More related literals: https://dev.mysql.com/doc/refman/5.7/en/date-and-time-literals.html

```
DATE 'str'
TIME 'str'
TIMESTAMP 'str'
```

**Comment by breeswish** [comment]
Related: https://github.com/pingcap/tidb/issues/3934

**Comment by shenli** [comment]
- DATE 'str'
- TIME 'str'
- TIMESTAMP 'str'

**Comment by Xuanwo** [comment]
@shenli The support for `TIME 'str'` and ` TIMESTAMP 'str'` already added in https://github.com/pingcap/tidb/commit/a2393245ddd6a43a2ae0948eb7221310bbc6a5fd , this issue can be closed.

**Comment by morgo** [comment]
Thanks @Xuanwo 

I will close this issue now.
