### ISSUE TITLE
TiDB and MySQL handle SQL strings suffixed with `\0` differently

### ISSUE THREAD

**Issue by bob34007** [pingcap/tidb#39132]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

**C-CODE**
    char sql[50]="select * from test.tpre where id =1";
    int len = strlen(sql)+1;
    char *sql_exec =(char *)malloc(len);
    memset(sql_exec ,0x0,len);
    memcpy(sql_exec,sql,strlen(sql));
    //sql_exec[strlen(sql)]='\0';
    printf("sql is %s ,sql len %d,malloc len %d \n",sql_exec,strlen(sql_exec),len);
    stmt = mysql_stmt_init(conptr);
    if (!stmt)
    {
        print_error(conptr);
        res = -1 ;
        goto ERR;
    }
    res = mysql_stmt_prepare(stmt,sql_exec,len);
    printf("prepare sql return %d\n",res);

### 2. What did you expect to see? (Required)

sql is select * from test.tpre where id =1 ,sql len 35,malloc len 36 
prepare sql return 0

### 3. What did you see instead (Required)

sql is select * from test.tpre where id =1 ,sql len 35,malloc len 36 
prepare sql return 1

### 4. What is your TiDB version? (Required)
 v6.3.0

Release Version: v6.1.0-alpha-1906-g94aa804
Edition: Community
Git Commit Hash: 94aa80409637d0f970b917c5ca6cec8876e78fb3
Git Branch: master
UTC Build Time: 2022-11-10 06:24:15
GoVersion: go1.19.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by Defined2014** [comment]
```
[err="[parser:1064]You have an     error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 35 near \"\u0000\" "]
```

**Comment by Defined2014** [comment]
Note that only one `\0` at the end is fixed. There is also a problem if `\0` is not the last character. And if we want to fix all problems, we need scan all query which impact performance too much.
