### ISSUE TITLE
Panic happen when input mismatch parameter number 

### ISSUE THREAD

**Issue by lizhenhuan** [pingcap/tidb#39148]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
用户 TiDB 节点持续重启，tidb log 中存在大量 panic 。
err="runtime error: index out of range [0] with length 0"
uptime  monitor：
![db143cab-3e63-411d-be07-0d361b160d6d](https://user-images.githubusercontent.com/3417765/201818571-b8200c93-42dc-401a-895c-d747d6dda59f.jpeg)

 Welcome key word in tidb log
![2b39b3b1-ef20-4d27-a0bb-6bbd6712e4b6](https://user-images.githubusercontent.com/3417765/201818639-1b427323-3496-4e25-9666-2256d6fcef78.jpeg)

some log：
![95ebdd72-7b74-49c1-b138-af9e84b92bcd](https://user-images.githubusercontent.com/3417765/201818685-408c7f9c-c889-41e2-8d5a-f4676829ae4e.jpeg)

full log file：
[tidb.log.tar.gz](https://github.com/pingcap/tidb/files/10008838/tidb.log.tar.gz)

### 2. What did you expect to see? (Required)
error log and return error info to user, tidb server not restart
### 3. What did you see instead (Required)
panic happen , tidb keep restart , server is not aviable
### 4. What is your TiDB version? (Required)
Server version: 5.7.25-TiDB-v6.3.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Server version: 5.7.25-TiDB-v6.3.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

**Comment by dveeden** [comment]
Formatted stack:
```
github.com/pingcap/tidb/executor.(*outerWorker).run.func1
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:363
runtime.gopanic
	/usr/local/go/src/runtime/panic.go:884
runtime.goPanicIndex
	/usr/local/go/src/runtime/panic.go:113
github.com/pingcap/tidb/expression.(*ParamMarker).GetUserVar
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/constant.go:91
github.com/pingcap/tidb/expression.(*Constant).GetType
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/constant.go:122
github.com/pingcap/tidb/expression.(*builtinEQIntSig).vecEvalInt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/builtin_compare_vec.go:312
github.com/pingcap/tidb/expression.(*ScalarFunction).VecEvalInt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/scalar_function.go:48
github.com/pingcap/tidb/expression.(*Constant).VecEvalInt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/constant.go:134
github.com/pingcap/tidb/expression.EvalExpr
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/expression.go:573
github.com/pingcap/tidb/expression.VecEvalBool
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/expression.go:368
github.com/pingcap/tidb/expression.vectorizedFilter
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/chunk_executor.go:489
github.com/pingcap/tidb/expression.VectorizedFilterConsiderNull
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/chunk_executor.go:401
github.com/pingcap/tidb/expression.VectorizedFilter
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/expression/chunk_executor.go:379
github.com/pingcap/tidb/executor.(*SelectionExec).Next
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:1569
github.com/pingcap/tidb/executor.Next
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:324
github.com/pingcap/tidb/executor.(*outerWorker).buildTask
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:433
github.com/pingcap/tidb/executor.(*outerWorker).run
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/index_lookup_join.go:376
```

**Comment by YangKeao** [comment]
Same issue for https://github.com/pingcap/tidb/issues/38116

**Comment by YangKeao** [comment]
After several attempts, I cannot reproduce this problem: 

1. mysql-connector-java checks the parameters on the client-side. It cannot submit a query with wrong parameter number.
2. Even the packet is with wrong parameter number, the TiDB reads it according to the parameter number in prepared statement. If the packet is too short (without enough parameter), it will return an error.

I guess this problem is not because the parameter number mismatch, with two evidence:

1. The failing attempt to reproduce this issue above shows that the TiDB can properly handle the packet without enough parameters.
2. All panic happens in the `fetch` command (or other worker), but we already read parameters (according to the number in the statement) in `execute` command.

One assumption I could provide is that the TiDB cannot handle two parallel fetch properly. You could verify it with the following java program (or any other connector supports cursor fetch):

```java
public class Example {
    public static void main(String[] args) throws SQLException, InterruptedException {
        Connection conn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:4000/test?useCursorFetch=true&useServerPrepStmts=true&useSSL=false", "root", "");

        conn.setAutoCommit(false); // must set

        conn.prepareStatement("drop table if exists t").execute();
        conn.prepareStatement("create table t (id int auto_increment primary key, id_2 int)").execute();
        conn.prepareStatement("insert into t values (1,1)").execute();
        conn.prepareStatement("insert into t values (2,2)").execute();

        // submit a statement with more arguments:
        PreparedStatement statement1 = conn.prepareStatement("" +
                "select * " +
                "from " +
                "t " +
                "where id = ? and id_2 = ?");
        statement1.setFetchSize(500);
        statement1.setInt(1, 1);
        statement1.setInt(2, 2);
        ResultSet rs_1 = statement1.executeQuery();

        // submit a statement with less arguments:
        PreparedStatement statement2 = conn.prepareStatement("" +
                "select * " +
                "from " +
                "t " +
                "where (id = ?)");
        statement2.setFetchSize(500);
        statement2.setInt(1, 1);
        ResultSet rs_2 = statement2.executeQuery();

        // fetch the result from the first argument
        while (rs_1.next()) {
            int result = rs_1.getInt(1);

            System.out.println(result);
        }

        conn.close();

    }
}
```

It opens two cursor: one for statement1 with two parameters, and one for statement2 with one parameters. When it tries to read result from statement2, the TiDB will panic, as the parameters in the session has already been modified in the second statement. It produces nearly the same backtrace as shown in the issue, so I guess it's the root cause. @lizhenhuan Could you help to verify it?

This issue actually shared the same root cause with https://github.com/pingcap/tidb/issues/38116, both of them are because the session vars / statement vars of the cursor is shared with others.

**Comment by dveeden** [comment]
Thanks for the great explanation.

I think this:
"When it tries to read result from statement2, the TiDB will panic..."
probably should have been this:
"When it tries to read result from statement1, the TiDB will panic..."

**Comment by YangKeao** [comment]
> Thanks for the great explanation.
> 
> I think this: "When it tries to read result from statement2, the TiDB will panic..." probably should have been this: "When it tries to read result from statement1, the TiDB will panic..."

Nice catch :+1: . Thanks

**Comment by MimeLyc** [comment]
update
