### ISSUE TITLE
Support binding from history

### ISSUE THREAD

**Issue by fzzf678** [pingcap/tidb#39199]
## Enhancement
For manually create binding way, we can only write whole sql text with hint to create, sometimes may be not easy to fix a plan and sometime user wish to fix old plans. For easier use in these sceneries, we should expose a way to create binding directly from plan history.If one plan exists in memory,  such as a serial of Statement Summary Tables, SQL binding can be created and managed simply with a digest id.

**Comment by qw4990** [comment]
Most common hints have been supported, close this issue.
