### ISSUE TITLE
TiDB oom when sysbench random point and frequently drop/add column ddl

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#39192]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
sysbench --mysql-user=root --db-driver=mysql --time=0 --report-interval=10 --mysql-db=
test --mysql-host=tc-tidb.e2e-oltp-sysbench-rand-fun-tps-1306124-1-388 --mysql-port=4000 --threads=512 --tables=32 --table-size=10000000 --mysql-ignore-errors=2013,1213,1
105,8028,9007,1205,9004 --rand-type=uniform --random_points=183 --point_selects=15 select_random_points run
frequently drop/add column
```
tidb oom
![image](https://user-images.githubusercontent.com/7677963/202141791-9ccf74c0-973a-4307-b46c-c9986b3360ca.png)

### 4. What is your TiDB version? (Required)

./tidb-server -V
 Release Version: v6.5.0-alpha
Edition: Community
Git Commit Hash: 6af4e4b160dd5c04d7379caf2a16a3daeb9a3e56
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-15 11:15:45
GoVersion: go1.19.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by Defined2014** [comment]
The memory of both tidb nodes grows rapidly until one TiDB node down. Not sure it's related with DDL or not. Could you upload logs?

**Comment by lilinghai** [comment]
env is already released, record and upload logs if occurs next time.
