### ISSUE TITLE
support last row id when inserting with auto increment.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#392]
We use last insert id in MySQL OK package now, but it is not correct all time, we should return last row id instead. 

```
create table t (c int auto_increment, primary key(c))
```

 If we use `insert into t value()`, the last insert id is the same as row id, e.g, 1 here, but when we do `insert into t values (100)`, the last insert id is still 1 but row id is 100 now.

**Comment by coocood** [comment]
This is not a bug, MySQL has the same behavior.

**Comment by savas-yildirim** [comment]
@coocood  I apologize for them on behalf of MySql's error. Now, don't make mistakes like them. choose the right one...
