### ISSUE TITLE
tidb core and cannot restart

### ISSUE THREAD

**Issue by wupaopao** [pingcap/tidb#3920]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Firstly,I had established pd,tikv,tidb sucessfully by Docker.Secondly, I use 'sysbench prepare' to prepare data.Because it is too slow,so I stop it in the middle of execution.And then I use 'sysbench cleanup' to clean up.For about 2 hours tidb exited. When I restart,the log shows us that "panic: runtime error: index out of range".It stop at "ddl_worker.go:262   reorg.go:73"

If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

Start tidb normaly.

3. What did you see instead?

Cannot start tidb.

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by zimulala** [comment]
@wupaopao Thank you for your report.
Can you give us the TiDB version and the more detailed log?

**Comment by wupaopao** [comment]
TiDB version:
Git Commit Hash: d8396b8ed4dc
UTC Build Time: 2017-07-17 02:25:00

Please See attachment for detailed log 
![detailed_log](https://user-images.githubusercontent.com/10083199/28699767-21ab7768-737e-11e7-9c30-4ded1a78ab0e.jpg)

**Comment by zimulala** [comment]
@wupaopao  Could you show me the table structure and the statement of `add index`.

**Comment by wupaopao** [comment]
The table is auto created by sysbench.And I cannot show you the table  structue because I cannnot start TiDB now.
This picture show the table structure when I running 'sysbench' on mysql. For your information.

![table_structure](https://user-images.githubusercontent.com/10083199/28701764-ef7b964e-738a-11e7-80a4-6e745de00248.jpg)

**Comment by zimulala** [comment]
@wupaopao Could you show me all logs about `DDL job ID:185`? The query information is the log with the prefix of `start DDL Job`.

**Comment by zimulala** [comment]
@wupaopao Or could you show me the result of grep "start DDL job ID:185" tidb.log -A 10?

**Comment by wupaopao** [comment]
@zimulala  Sorry,I cannot find 'start DDL job ID:185' or 'start DDL job'  in tidb.log.  All logs about “DDL job ID:185” were showed in the third floor.

**Comment by zimulala** [comment]
@wupaopao Never mind. The log was printed before you restart the TiDB.
We will deal with it. Thanks for your report.

**Comment by wupaopao** [comment]
@zimulala Thanks so much.If there is any progress, please let me know in time.

**Comment by c4pt0r** [comment]
Any updates?

**Comment by zimulala** [comment]
@wupaopao I'm sorry for my late reply.
Could you make it happen again? I want more log information.
