### ISSUE TITLE
The query result is wrong and inconsistent with MySQL. It is suspected that it is a long integer type, and the accuracy is lost

### ISSUE THREAD

**Issue by fengleicn** [pingcap/tidb#39212]
## Bug Report
查询结果错误，与MySQL不一致，怀疑是长整数类型，出现了精度丢失。
建表语句
```sql
CREATE TABLE device_delta_collect
(
    reportTime varchar(255) DEFAULT NULL,
    deviceId   varchar(255) DEFAULT NULL,
    multiple   varchar(255) DEFAULT NULL,
    deltaJgs   varchar(255) DEFAULT NULL,
    KEY device_delta_collect_deviceId_index (deviceId),
    KEY device_delta_collect_reportTime_index (reportTime)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
  COLLATE = utf8mb4_bin;
```
插入语句
`insert into device_delta_collect (reportTime,  deviceId,  deltaJgs, multiple) values ('2022-08-20 22:33:58',  '1547034559760195585',  '1',  '1');`
查询语句
`select * from device_delta_collect a where a.deviceId = 1547034559760195587 limit 10;`
TiDB返回
```
reportTime |   deviceld  |  deltaJgs  | multiple
2022-08-20 22:33:58 |    1547034559760195585 |  1 |  1       
```
应该返回空集

**Comment by xhebox** [comment]
It is `deviceId` not `deviceld`. Also, you can reproduce the same result on mysql8.0. So I don't think it is a bug, especially that `deviceId` is of type `varchar(255)`.

**Comment by xhebox** [comment]
If you do want to select, then you should `where a.deviceId = "1547034559760195585"`. Any question? If not I'll close the issue. @fengleicn

**Comment by fengleicn** [comment]
> If you do want to select, then you should `where a.deviceId = "1547034559760195585"`. Any question? If not I'll close the issue. @fengleicn
> 
> 你应该写 `where a.deviceId = "1547034559760195585"`, 如果你想正常select. 如果没有其他问题, 我就关issue了.

但是 mysql 就可以直接写 where a.deviceId = 1547034559760195585 查到正确结果的。这个是为什么呀，因为这个问题公司mysql迁移tidb的时候就发生问题了。。

**Comment by fengleicn** [comment]
> It is `deviceId` not `deviceld`. Also, you can reproduce the same result on mysql8.0. So I don't think it is a bug, especially that `deviceId` is of type `varchar(255)`.
> 
> 是 `deviceId`, 不是 `deviceld`. 而且mysql8.0的行为也一样. 应该不算bug, 况且 `deviceId` 的类型是 `varchar(255)`.

嗯写错了修改了

**Comment by fengleicn** [comment]
> It is `deviceId` not `deviceld`. Also, you can reproduce the same result on mysql8.0. So I don't think it is a bug, especially that `deviceId` is of type `varchar(255)`.
> 
> 是 `deviceId`, 不是 `deviceld`. 而且mysql8.0的行为也一样. 应该不算bug, 况且 `deviceId` 的类型是 `varchar(255)`.

mysql 8.0 一样嘛。。mysql 5.7 好像可以查出正确结果，我去试一下

**Comment by fengleicn** [comment]
好的我close了
