### ISSUE TITLE
unstable test: TestAddIndexUniqueFailOnDuplicate

### ISSUE THREAD

**Issue by purelind** [pingcap/tidb#39223]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```shell
Error Trace:	/home/jenkins/.tidb/tmp/5b8829669b2a941b840f9eb369e2b54f/sandbox/processwrapper-sandbox/7158/execroot/__main__/bazel-out/k8-fastbuild/bin/ddl/ddl_test_/ddl_test.runfiles/__main__/ddl/index_modify_test.go:1084
        	Error:      	"6" is not less than "6"
        	Test:       	TestAddIndexUniqueFailOnDuplicate
```
link  https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-hourly/detail/tidb-unit-test-hourly/11783/tests

**Comment by tangenta** [comment]
Fix by the changes in https://github.com/pingcap/tidb/pull/39191/files#diff-1bbc7833321782b3a22a842b6237974b6a60cb07b49b246b85552ab5e915ed6eR352-R356
