### ISSUE TITLE
view  force index 

### ISSUE THREAD

**Issue by songxc1995** [pingcap/tidb#39234]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://asktug.com/t/topic/996224/13
5.4.3
create view 
select * from v_xx force index xx

![image](https://user-images.githubusercontent.com/96608064/202641365-59968a2a-111a-4f93-834d-b153e3f50605.png)

6.1.2 
create view 
select * from v_xx force index xx

![image](https://user-images.githubusercontent.com/96608064/202641155-17a14dc8-6cb6-4c9c-bbe3-4a992d1cbd7b.png)

### 4. What is your TiDB version? (Required)
5.4.3 
6.1.2

**Comment by Reminiscent** [comment]
Because we are not support the hint for view in the old version(We will support it in the v6.5). So it can not directly use the `force_index` hint for the view. In v5.4.3, it also can not take effect. But it may just lack some checks, so it doesn't report some errors.
