### ISSUE TITLE
Data inconsistency after PITR log restore

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#39240]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- PITR Log restore to 437353222858342528, and do data consistency check between usptream/dowstream  (passed)
- PITR log restore from 437353222858342528 to 437393542375014831, after successful restore, check consistency between upstream and downstream.

### 2. What did you expect to see? (Required)
Upstream and downstream data should be consistent

### 3. What did you see instead (Required)
Data is inconsistency

### 4. What is your TiDB version? (Required)
br version:
BR version: [2022/11/15 14:55:08.925 +00:00] [INFO] [global.go:34] ["Welcome to Backup & Restore (BR)"] [release-version=v6.5.0-alpha] [git-hash=ea26284ea3dd02f026430e4c6e8ac145d1360ad8] [git-branch=heads/refs/tags/v6.5.0-alpha] [go-version=go1.19.2] [utc-build-time="2022-11-08 13:17:14"] [race-enabled=false]

upstream tikv:
["Release Version: 6.4.0"]["Git Commit Hash: 220a263c665b42a43cec3e38f2d9b46ffe074ca9"]

downstream tikv:
Release Version: 6.4.0-alpha 
Edition: Community 
Git Commit Hash: 956610725039835557e7516828b069a44073c36d

**Comment by fubinzh** [comment]
PITR checkpoint lag status for the time range:
![3884d1d2-2dcd-40b7-897f-30dc658f8613](https://user-images.githubusercontent.com/7403864/202653694-482590e2-a20e-4d8a-b09d-e70f848c5d3a.jpeg)

**Comment by YuJuncen** [comment]
This should already be fixed by https://github.com/pingcap/tidb/pull/38772.
