### ISSUE TITLE
The use of string types in the IN keyword

### ISSUE THREAD

**Issue by AlexWonga** [pingcap/tidb#39258]
Consider the following statements:

```
SELECT "1gbnn" IN (1) -- expected: 0, actual: 1  
SELECT '1' IN (1) -- expected: 0, actual: 1 
SELECT "a" IN (0);  -- expected: 0, actual: 1  
SELECT 1 IN('1'); -- expected: 0, actual: 1 
```

for keyword IN, We expect that strings should not be converted to numeric values. however, in actual execution, string is converted to a numeric type.

database version: 5.7.25-TiDB-v6.1.2

**Comment by jebter** [comment]
Same behavior as mysql 8.0

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
