### ISSUE TITLE
The negative result of the bitwise operator

### ISSUE THREAD

**Issue by AlexWonga** [pingcap/tidb#39259]
Consider the following statements:
```
SELECT -5 & -4; -- expected: -8, actual: 18446744073709551608  
SELECT '-5' | '-4'; -- expected: -3, actual: 18446744073709551615  
SELECT '5' ^ '-4'; -- expected: -7, actual: 18446744073709551609
SELECT ~5; -- expected: -6, actual: 18446744073709551610 
SELECT -3 > ('5' ^ '-4'); -- expected: 1, actual: 0   
```

The result should be negative, but it actually becomes a large value, We think this should be a spillover issue.

database version: 5.7.25-TiDB-v6.1.2

**Comment by jebter** [comment]
Same behavior as mysql 8.0

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
