### ISSUE TITLE
Add TTL table support

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#39262]
### Feature Dev

- [x] #39263
- [x] #39268
- [x] #39269
- [x] #39270
- [x] #39271
- [x] #39272
- [x] #39351
- [x] #39364
- [x] #39339
- [x] #39428
- [x] #39465
- [x] #39859
- [x] #39480
- [x] #39554
- [x] #39626
- [x] Support time window for TTL schedule
- [x] #39848
- [x] #39852
- [x] #39877
- [x] #39895
- [x] #39957
- [x] #40345
- [x] #40215
- [x] #40265
- [x] #40361
- [x] #40486
- [x] #40502
- [x] #40654
- [x] #40519
- [x] #40807
- [x] #40810
- [x] #41419
- [x] #41276
- [x] #41597
- [x] https://github.com/pingcap/tiflow/issues/7997
- [x] #41585
- [ ] #40928
- [ ] Save the TTL scan task checkpoint and recover from it when failover
- [ ] TTL job manager should stop a job manually when it finds some schema change.
- [x] #42466
- [ ] Add some TTL charts in DBaaS / TiDB Cloud
- [ ] Check clock drifting in TiDB 
- [ ] Delete dropped/truncated table id in `mysql.tidb_ttl_table_status`
- [ ] Support to cancel a running TTL job
- [ ] Add TiDB launch option to disable running TTL jobs in current node
- [ ] #42393

# Timer Framework integration

- [x] #45164
- [x] #45268
- [x] #45285
- [x] #45468
- [x] #45610

### Bug Fix

- [x] #39633
- [x] #39864
- [x] #39917 
- [x] #40456
- [x] #41043
- [x] #42012
- [x] #40231
- [x] #44767
- [x] #45510

**Comment by YangKeao** [comment]
In 2022 / 12 / 16, the basic function of TTL works on master TiDB (and we are doing some performance test). We could try to cherry-pick these PRs to the 6.5. Here is a list of PRs (in order):

- https://github.com/pingcap/tidb/pull/39598 (IN REVIEW)
- https://github.com/pingcap/tidb/pull/39615 (IN REVIEW)
- https://github.com/pingcap/tidb/pull/39619 (IN REVIEW)
- https://github.com/pingcap/tidb/pull/39628 (IN REVIEW), depend on 39619

All following PRs need some rebase (or manually cherry-pick)

- https://github.com/pingcap/tidb/pull/39646
- https://github.com/pingcap/tidb/pull/39775
- https://github.com/pingcap/tidb/pull/39830
- https://github.com/pingcap/tidb/pull/39862
- https://github.com/pingcap/tidb/pull/39869
- https://github.com/pingcap/tidb/pull/39874
- https://github.com/pingcap/tidb/pull/39875
- https://github.com/pingcap/tidb/pull/39889
- https://github.com/pingcap/tidb/pull/39897
- https://github.com/pingcap/tidb/pull/39901
- https://github.com/pingcap/tidb/pull/39908
- https://github.com/pingcap/tidb/pull/39921
- https://github.com/pingcap/tidb/pull/39942
- https://github.com/pingcap/tidb/pull/39943
- https://github.com/pingcap/tidb/pull/39944
- https://github.com/pingcap/tidb/pull/39959
- https://github.com/pingcap/tidb/pull/39960

**Comment by bb7133** [comment]
Should we close this issue now?
