### ISSUE TITLE
Cannot Connect to Server After Specific Statements

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#39278]
### 1. Minimal reproduce step (Required)

```sql
USE test;
DROP DATABASE IF EXISTS database0;
CREATE DATABASE database0;
USE database0;
CREATE TABLE t0(c0 CHAR);
INSERT INTO t0(c0) VALUES ('\''');
INSERT INTO t0(c0) VALUES ('-') ON DUPLICATE KEY UPDATE c0=CAST('\r' AS SIGNED);--D
```

After executing all the above content in MySQL client, including the comment, I get the error: Can't connect to the server. After that, whatever statement I execute, I always get `Can't connect to the server` error.

### 2. What did you expect to see? (Required)
No error.

### 3. What did you see instead (Required)
Can't connect to the server.

### 4. What is your TiDB version? (Required)
```
| Release Version: v6.5.0-alpha-96-g3bcd5a889
Edition: Community
Git Commit Hash: 3bcd5a889bded9ab23e7d077ea5c69df7982a495
Git Branch: master
UTC Build Time: 2022-11-21 03:02:37
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |
```

MySQL client version:
```
mysql  Ver 8.0.31-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
```

**Comment by Defined2014** [comment]
same as https://github.com/pingcap/tidb/issues/35678, fixed by https://github.com/pingcap/tidb/pull/39405, close this.
