### ISSUE TITLE
Built-in function CHARSET not supported

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#3931]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```sql
SELECT CHARSET('a');
```

2. What did you expect to see?

```
+--------------+
| CHARSET('a') |
+--------------+
| utf8         |
+--------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```
ERROR 1305 (42000): FUNCTION CHARSET does not exist
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by morgo** [comment]
Confirming that this is still an issue:
```
mysql> SELECT CHARSET('a');
ERROR 1305 (42000): FUNCTION CHARSET does not exist
```

**Comment by zz-jason** [comment]
@qw4990 PTAL
