### ISSUE TITLE
Support IndexMerge Intersection (planner part)

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#39335]
## Feature Request
sub task of https://github.com/pingcap/tidb/issues/39333
**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by time-and-fate** [comment]
Implementation
---

### Hint

The intersection type IndexMerge will be generated and chosen only when we use hints to specify both table name and index names.

Reuse the `use_index_merge` hint.

### Generate intersection type IndexMerge access path

For every index specified in the hint, collect the corresponding normal access path. Then, for each of them, build the index range scan and index side filters into a partial access path. Finally, collect all table side filters, deduplicate them, and make them the selection above the final table scan.

Note that we follow a limitation the same as the union type IndexMerge here: we never consider a partial access path if it's a full scan, even if there is a selection above it.

### Add corresponding information to EXPLAIN

Display which type of IndexMerge it is in the operator info column in the displayed execution plan.
