### ISSUE TITLE
column TIME literal not support

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#3934]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`select TIME'11:11:11';`

2. What did you expect to see?

```
mysql> select TIME'22:11:11';
+----------------+
| TIME'22:11:11' |
+----------------+
| 22:11:11       |
+----------------+
1 row in set (0.00 sec)
```

3. What did you see instead?

```
mysql> select TIME'11:11:11';
ERROR 1105 (HY000): unknown column time
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by shenli** [comment]
Duplicate with #3909
