### ISSUE TITLE
stats healthy distribution still counts the dropped tables.

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#39349]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Create two tables and then drop both of them. Observe the stats healthy distribution panel.
```
mysql> create table t1(a int);
Query OK, 0 rows affected (0.62 sec)

mysql> create table t2(a int);
Query OK, 0 rows affected (0.57 sec)

mysql> drop table t1;
Query OK, 0 rows affected (1.10 sec)

mysql> drop table t2;
Query OK, 0 rows affected (1.05 sec)
```

### 2. What did you expect to see? (Required)
The total number of tables in the stats healthy distribution panel drops to 0 after the two tables are dropped.

### 3. What did you see instead (Required)
The total number of tables in the stats healthy distribution panel is still 2 after the two tables are dropped.
![Screen Shot 2022-11-24 at 1 36 36 AM](https://user-images.githubusercontent.com/30385241/203613418-a5ca29c7-4ca6-4143-b32e-073348bdfe58.png)

### 4. What is your TiDB version? (Required)
master

**Comment by hawkingrei** [comment]
<img width="1842" alt="image" src="https://github.com/pingcap/tidb/assets/3427324/48d59f1b-89b1-42c0-8497-57f9303d248c">

In the v6.5, the count will be negative.
