### ISSUE TITLE
tidb start takes for more than one hour

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#39393]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
restart one tidb

### 2. What did you expect to see? (Required)
tidb start quickly

### 3. What did you see instead (Required)
tidb start takes for more than one hour
![image](https://user-images.githubusercontent.com/84712107/203913652-49ca6090-6739-4fac-880c-ee11c59ba665.png)
![image](https://user-images.githubusercontent.com/84712107/203913670-924cee45-e243-4d58-8ca7-61abdabd4ed5.png)

### 4. What is your TiDB version? (Required)
/ # ./tidb-server -V
Release Version: v6.5.0-alpha
Edition: Community
Git Commit Hash: d100e933c8982ed13135abbca1224b472b167b53
Git Branch: heads/refs/tags/v6.5.0-alpha
UTC Build Time: 2022-11-24 11:14:14
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by tiancaiamao** [comment]
I think this is cause by bug that the tidb can't exit the graceful shutdown and maybe related to https://github.com/pingcap/tidb/issues/32110

This issue might have been fixed by https://github.com/pingcap/tidb/pull/44953
I'll mark it as  duplicated, if it reproduces, feel free to reopen this.
