### ISSUE TITLE
Some of tests in builtin_time_test fails

### ISSUE THREAD

**Issue by liangjiaxing** [pingcap/tidb#3944]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I git clone the repo and run `make dev` in `$GOPATH/src/github.com/pingcap/tidb`. I am in PST timezone.

2. What did you expect to see?
This is the first time I try to run `make dev`, I assume all the tests should pass.

3. What did you see instead?
I saw these 3 test case fail
```
FAIL: builtin_time_test.go:1179: testEvaluatorSuite.TestTimestamp

builtin_time_test.go:1218:
    c.Assert(result, Equals, test.expect)
... obtained string = "2017-01-18 11:30:59"
... expected string = "2017-01-18 12:30:59"


FAIL: builtin_time_test.go:588: testEvaluatorSuite.TestSubTimeSig

builtin_time_test.go:609:
    c.Assert(result, Equals, t.expect)
... obtained string = "2016-12-31 22:59:59.998890"
... expected string = "2016-12-31 23:59:59.998890"

FAIL: builtin_time_test.go:515: testEvaluatorSuite.TestAddTimeSig

builtin_time_test.go:540:
    c.Assert(result, Equals, t.expect)
... obtained string = "2017-01-01 01:02:02.221110"
... expected string = "2017-01-01 02:02:02.221110"
```

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: 8df4f7f753a359a32e920ec463568cf175f949c9
UTC Build Time:  2017-07-29 06:48:27

**Comment by shenli** [comment]
@liangjiaxing Thanks for your feedback! 
@tiancaiamao @XuHuaiyu PTAL

**Comment by liangjiaxing** [comment]
I am pretty sure this is a timezone issue. Once I changed the timezone to Beijing, all the tests just passed.
The bug should be reproducible on OSX if the timezone is San Fransisco.

**Comment by XuHuaiyu** [comment]
@tiancaiamao PTAL

**Comment by liangjiaxing** [comment]
To reproduce, run these two queries:
```
tidb> SET time_zone = 'US/Pacific';
Query OK, 0 rows affected (0.00 sec)

tidb> select addtime('2017-01-01 01:01:01.11', '0');
+----------------------------------------+
| addtime('2017-01-01 01:01:01.11', '0') |
+----------------------------------------+
| 2017-01-01 00:01:01.11                 |
+----------------------------------------+
1 row in set (0.00 sec)
```
The correct result should be `2017-01-01 01:01:01.11`

**Comment by tiancaiamao** [comment]
I can't reproduce the query, can you? @XuHuaiyu

**Comment by shenli** [comment]
I can not reproduce this issue neither.  What's is your local timezone @liangjiaxing ?

> ➜  tidb git:(master) ✗ mysql -uroot -h127.0.0.1 -P4000 test 
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 1
> Server version: 5.7.1-TiDB-1.0 MySQL Community Server (Apache License 2.0)
> 
> Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql> SET time_zone = 'US/Pacific';
> Query OK, 0 rows affected (0.01 sec)
> 
> mysql> select addtime('2017-01-01 01:01:01.11', '0');
> +----------------------------------------+
> | addtime('2017-01-01 01:01:01.11', '0') |
> +----------------------------------------+
> | 2017-01-01 01:01:01.11                 |
> +----------------------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> 
>

**Comment by liangjiaxing** [comment]
Hmmmm, my local timezone is PST

**Comment by shenli** [comment]
@tiancaiamao After setting my timezone to PDT, I reproduced this issue:

> ➜  tidb git:(master) ✗ date
> Wed Aug 16 08:53:36 PDT 2017
> ➜  tidb git:(master) ✗ 
> ➜  tidb git:(master) ✗ mysql -uroot -h127.0.0.1 -P4000 test 
> Welcome to the MySQL monitor.  Commands end with ; or \g.
> Your MySQL connection id is 1
> Server version: 5.7.1-TiDB-1.0 MySQL Community Server (Apache License 2.0)
> 
> Copyright (c) 2000, 2016, Oracle and/or its affiliates. All rights reserved.
> 
> Oracle is a registered trademark of Oracle Corporation and/or its
> affiliates. Other names may be trademarks of their respective
> owners.
> 
> Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
> 
> mysql> SET time_zone = 'US/Pacific';
> Query OK, 0 rows affected (0.00 sec)
> 
> mysql> select addtime('2017-01-01 01:01:01.11', '0');
> +----------------------------------------+
> | addtime('2017-01-01 01:01:01.11', '0') |
> +----------------------------------------+
> | 2017-01-01 00:01:01.11                 |
> +----------------------------------------+
> 1 row in set (0.00 sec)
> 
> mysql> quit
> Bye

**Comment by liangjiaxing** [comment]
Once I change the timezone to Beijing, I can't reproduce either.
My default timezone is PST

**Comment by liangjiaxing** [comment]
Thanks, it is working now.
