### ISSUE TITLE
br: br checkpoint lag > 10m when merging region

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#39441]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. tikv is region merging 
![image](https://user-images.githubusercontent.com/50363732/204443569-5553e371-005a-4e77-9ff7-cc03a86a46e3.png)
2. run cc ch sysbench workload

### 2. What did you expect to see? (Required)
1. lag is normal
### 3. What did you see instead (Required)
1. lag > 5min even 10min
![image](https://user-images.githubusercontent.com/50363732/204426021-0fb5136c-65d5-48f2-b4d0-a4b3fc3d185e.png)

### 4. What is your TiDB version? (Required)
master

**Comment by BornChanger** [comment]
@AkiraXie is the problem solved?

**Comment by JasonWu0506** [comment]
@AkiraXie why this bug is closed without any information

**Comment by AkiraXie** [comment]
> @AkiraXie is the problem solved?

not seen in recent tests
