### ISSUE TITLE
Truly kill a query when it exceeds max excution time even if mysql client gets stuck

### ISSUE THREAD

**Issue by gengliqi** [pingcap/tidb#39449]
## Enhancement

In the current implementation, the kill operation will take effect only after calling `next` function.
However, if a MySQL client doesn't receive data for a long time, the `next` function wasn't called for a long time either.
This case can lead to many resources(i.e. goroutine, memory) can not be released.
Also, many logs like below will be outputted each 100ms, which is very annoying.
<img width="1473" alt="image" src="https://user-images.githubusercontent.com/21253569/204463003-e9908fe1-3fee-4f60-ba75-979b086bd86a.png">

In order to improve robustness, we need to change the kill process to release resources as many as possible.

**Comment by wuhuizuo** [comment]
Can we close it since #44675 was solved.

**Comment by gengliqi** [comment]
close due to https://github.com/pingcap/tidb/pull/52882
