### ISSUE TITLE
What is the version of rocksDB in TiDB

### ISSUE THREAD

**Issue by Guanpx** [pingcap/tidb#39498]
## General Question

what is the version of rocksDB in TiDB(v6.1)?

**Comment by Defined2014** [comment]
I think you can check it in TiKV repo.
https://github.com/tikv/rocksdb and https://github.com/tikv/tikv

**Comment by Guanpx** [comment]
> I think you can check it in TiKV repo. https://github.com/tikv/rocksdb and https://github.com/tikv/tikv

thx~
