### ISSUE TITLE
tidb meets error: `ERROR 1008 (HY000): Can't drop database ''; database doesn't exist` when dropping database

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#39606]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. drop a db

### 2. What did you expect to see? (Required)
1. no error
### 3. What did you see instead (Required)
1. meets error
![image](https://user-images.githubusercontent.com/50363732/205538243-ed868366-e2e2-4b2a-b3e7-6af0f0006953.png)
2. releted log:
 [conn.go:1132] ["command dispatched failed"] [conn=1718422325004771875] [connInfo="id:1718422325004771875, addr:10.233.101.128:40939 status:10, collation:utf8mb4_0900_ai_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="drop database longrun_tpcc_p_range"] [txn_mode=PESSIMISTIC] [timestamp=437834811365916675] [err="[schema:1008]Can't drop database ''; database doesn't exist\ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211224045212-9687c2b0f87c/juju_adaptor.go:15\ngithub.com/pingcap/tidb/ddl.(*ddl).DoDDLJob\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/ddl/ddl.go:1059\ngithub.com/pingcap/tidb/ddl.(*ddl).DropSchema\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/ddl/ddl_api.go:610\ngithub.com/pingcap/tidb/executor.(*DDLExec).executeDropDatabase\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/ddl.go:314\ngithub.com/pingcap/tidb/executor.(*DDLExec).Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/ddl.go:160\ngithub.com/pingcap/tidb/executor.Next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:324\ngithub.com/pingcap/tidb/executor.(*ExecStmt).next\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:987\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:761\ngithub.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:609\ngithub.com/pingcap/tidb/executor.(*ExecStmt).Exec\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:538\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2213\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2077\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:231\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2049\ngithub.com/pingcap/tidb/server.(*clientConn).handleQuery\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1904\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1359\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1104\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:563\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"]
### 4. What is your TiDB version? (Required)
Release Version: v6.4.0-alpha
Edition: Community
Git Commit Hash: aff0c3693f11dacd68525423af9d7187a45b9a82
Git Branch: heads/refs/tags/v6.4.0-alpha
UTC Build Time: 2022-10-08 11:08:32
GoVersion: go1.19.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by tiancaiamao** [comment]
This may happen when you execute the 'drop database' operation on several tidb instance simultaneously.
When the request reach to the DDL owner in specific order, the first one may execute success, and the second one get the error. (The second one doesn't know a 'drop database' request prior to it is queuing)

Can you reproduce the error? If not, I think this behaviour is by design. @AkiraXie
