### ISSUE TITLE
select .78$123

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#3963]
```sql
select .78$123;
select .78_123;
```

MySQL:

```
mysql> select .78$123;
+------+
| $123 |
+------+
| 0.78 |
+------+
1 row in set (0.00 sec)
```

TiDB:

```
mysql> select .78$123;
ERROR 1105 (HY000): line 0 column 8 near "78$123" (total length 14)
```

Notice: fixing this issue need some tricks, since it requires knowledge about the parsing context at the lexer level. Consider the input `.78_123a` (pattern: dot, number, underscore):

In this context (https://github.com/pingcap/tidb/commit/5917a784be944903c12f2ce42d57665dbc608904), lexer should output `dot, identifier(78_123a)`:

```sql
SHOW COLUMNS FROM my_table.78_123a;
```

However in this context, lexer should output `decimal(.78), identifier(_123a)`:

```sql
SELECT .78_123a
```

**Comment by c4pt0r** [comment]
@breeswish Does that PR fix this issue?

**Comment by breeswish** [comment]
@c4pt0r Nop. That PR is a temporal solution for our RC3.1, fixes the most urgent issue https://github.com/pingcap/tidb/issues/3889 .

Solution to this issue may be very tricky..We might not fix this issue in the near future...

**Comment by wjhuang2016** [comment]
This behavior is very strange, and it isn't documented in MySQL.
```
mysql> select .78$421;
+------+
| $421 |
+------+
| 0.78 |
+------+
1 row in set (0.00 sec)

mysql> select .78$421+1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '+1' at line 1
mysql> select .78$421-1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-1' at line 1
```
I don't think users should rely on this behavior, and it shouldn't be taken as a bug.
