### ISSUE TITLE
[compatibility] STR_TO_DATE is not compatible with MySQL

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#3965]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
select str_to_date('04 /30/2004', '%m /%d/%Y');
```

2. What did you expect to see?

2004-04-30

3. What did you see instead?

2004-04-30 00:00:00

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by zz-jason** [comment]
@tiancaiamao PTAL, @XuHuaiyu after rewriting `builtinStrToDateSig`, this can be fixed ?

**Comment by zz-jason** [comment]
to #4080

**Comment by XuHuaiyu** [comment]
fixed in #4357
