### ISSUE TITLE
remove tidb_enable_foreign_key variable

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#39670]
## Dev Task

We should remove `tidb_enable_foreign_key ` before foreign key GA.

**Comment by YangKeao** [comment]
After discussing with @bb7133, this variable will not be removed (even after GA) to keep the compatibility with the old TiDB behavior without real foreign key. Keeping it will allow the users to create new tables with fake foreign key.

I'll close this PR. If anyone has other ideas, feel free to re-open and comment directly :beers: .
