### ISSUE TITLE
How to add/remove a node by Ansible?

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#3969]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I follow the https://pingcap.com/doc-ansible-deployment to create a TiDB cluster.  Any document show that how to add or remove a PD/TiDB/TiKV node by Ansible?

2. What did you expect to see?
Document or URL.

3. What did you see instead?
https://pingcap.com/doc-ansible-deployment

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by shenli** [comment]
@DavisLinDB You can edit the `inventory.ini` file and use `ansible-playbook rolling_update.yml` to update the cluster.

**Comment by LinuxGit** [comment]
refer: https://github.com/pingcap/docs/blob/master/op-guide/horizontal-scale.md
