### ISSUE TITLE
TiDB OOM when prepare/execute long insert statements

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#39717]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. enable prepared plan cache
2. prepare some long insert statements, e.g. insert into t values (...),...(...);
3. execute prepared statements in concurrency.

### 2. What did you expect to see? (Required)
No OOM

### 3. What did you see instead (Required)
TiDB OOM

### 4. What is your TiDB version? (Required)
v5.4.0

**Comment by qw4990** [comment]
Fixed by https://github.com/pingcap/tidb/pull/40080. Now the plan cache ignores simple insert-values-stmt like `insert into t values (...)`.
