### ISSUE TITLE
Decrease loading Region info in RegionCache when using `select * from table limit 1`

### ISSUE THREAD

**Issue by jansu-dev** [pingcap/tidb#39733]
## Enhancement

original problem : https://asktug.com/t/topic/996693

Background : 
1. We can see there was too many loadRegion from trace info and increased the query_time.
![image](https://user-images.githubusercontent.com/76909042/206171114-bd0791a9-2131-40d3-aaf8-9b9ed7d7ff1c.png)

2. Taking a deep look ：the calling chain is [func Select](https://github.com/pingcap/tidb/blob/cd8fb24c5f7ebd9d479ed228bb41848bd5e97445/distsql/distsql.go#L77) --> [func (c *CopClient) Send](https://github.com/pingcap/tidb/blob/cd8fb24c5f7ebd9d479ed228bb41848bd5e97445/store/copr/coprocessor.go#L82) --> [func buildCopTasks](https://github.com/pingcap/tidb/blob/cd8fb24c5f7ebd9d479ed228bb41848bd5e97445/store/copr/coprocessor.go#L163) --> [SplitKeyRangesByLocations](https://github.com/pingcap/tidb/blob/cd8fb24c5f7ebd9d479ed228bb41848bd5e97445/store/copr/region_cache.go#L62-L64) --> [LocateKey](https://github.com/tikv/client-go/blob/50651d6bb50cc78b5fa7c64fa9c11c39c780f749/internal/locate/region_cache.go#L912)  --> [findRegionByKey](https://github.com/tikv/client-go/blob/50651d6bb50cc78b5fa7c64fa9c11c39c780f749/internal/locate/region_cache.go#L940) -->  [loadRegion](https://github.com/tikv/client-go/blob/50651d6bb50cc78b5fa7c64fa9c11c39c780f749/internal/locate/region_cache.go#L1420:23) , the action how to actually loadRegion dues to ranges, in tableReader operand building, the ranges are table start_key and end_key. So, it causes a lot of loadRegion actions. 

Enhancement :  we think , in this scenario, it could be tuned in the way of just requesting specific region info.

**Comment by tiancaiamao** [comment]
This is a known issue, but not easy to fix.

"Build coprocessor request" component has no idea about the "limit 1" executor, it just see 'key ranges', which may be the whole table. For example, some query need to iterate the while table data (thus all its key range)  but just return 1 row...

A possible way to fix this might be making the 'SplitKeyRangesByLocations' lazy execution, so the cop task is built, but it region will be decided until the actual use.

**Comment by tiancaiamao** [comment]
Duplicated by https://github.com/pingcap/tidb/issues/14320
Close this one.
