### ISSUE TITLE
unstable test: TestCPUValue

### ISSUE THREAD

**Issue by purelind** [pingcap/tidb#39787]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
```shell
Stacktrace
=== RUN   TestCPUValue
    cpu_test.go:47: 
        	Error Trace:	/home/jenkins/.tidb/tmp/5b8829669b2a941b840f9eb369e2b54f/sandbox/processwrapper-sandbox/2101/execroot/__main__/bazel-out/k8-fastbuild/bin/util/cpu/cpu_test_/cpu_test.runfiles/__main__/util/cpu/cpu_test.go:47
        	Error:      	"1.3470625953046786" is not less than "1"
        	Test:       	TestCPUValue
--- FAIL: TestCPUValue (30.03s)
```
link  https://ci.pingcap.net/blue/organizations/jenkins/tidb-unit-test-hourly/detail/tidb-unit-test-hourly/13334/tests

**Comment by jebter** [comment]
@purelind Can this issue be closed?

**Comment by qw4990** [comment]
Close because this issue is not important and too old. Please reach me if it occurs again.
