### ISSUE TITLE
tidb ddl jobs is canceling, never synced.

### ISSUE THREAD

**Issue by chiamingiang** [pingcap/tidb#39808]
## Bug Report
无法删除表。无法创建表
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

前面tidb 组件有oom的情况。其中一个重启了 另外一个没有重启。
### 2. What did you expect to see? (Required)
我遇到过的有两种情况

我登录到每个tidb的服务器去重启tidb组件
### 3. What did you see instead (Required)
我有2个tidb组件。
分别重启后正常了。
### 4. What is your TiDB version? (Required)
6.3

https://asktug.com/t/topic/695043/3
这帖子描述的情况和我一样。我的问题后来是第二个回答解决的

**Comment by tiancaiamao** [comment]
The root cause of this is pd's unhealthy.
DDL is blocked by electing a new leader, and leader election depends on pd.
