### ISSUE TITLE
A question about raft.

### ISSUE THREAD

**Issue by wolaiye1010** [pingcap/tidb#3982]
1，据我了解，raft 是有leader，follower，构成，
所有的write 请求都会转发到leader，这样如果写请求很大到时候是有单点写入瓶颈的，
tidb 是怎么解决这个问题的呢？
2，raft 是过半数 成功就认为是成功，如果这样是否会有一段时间，比如两个client，一个链接到同步成功到机器，另一个链接到 同步不成功的机器，会不会两个client读取的内容不一样？

**Comment by shenli** [comment]
@wolaiye1010 
1. We have multiple raft groups in TiKV cluster. Their leaders distributed in the whole cluster.
2. Both writing and reading should processed by raft leader. The leader always have the latest data.

**Comment by aleafboat** [comment]
如果这样是否会有一段时间，比如两个client，一个链接到同步成功到机器，另一个链接到 同步不成功的机器，会不会两个client读取的内容不一样
------------------
你是说网络分区吧， 这个情况有 处理 看文章
https://asktug.com/t/tidb-follower-read/1286/2
