### ISSUE TITLE
how can i backup tidb

### ISSUE THREAD

**Issue by oklqh** [pingcap/tidb#3984]
sorry, it's just a normal question.

can i use mysqldump or other tools to backup tidb? i have read tidb's document, but there is nothing about backup. anyone konw this?

thank you.

**Comment by shenli** [comment]
You can refer to the following docs:
English: https://github.com/pingcap/docs/blob/master/op-guide/migration.md#1-exporting-data-from-mysql
Chinese: https://github.com/pingcap/docs-cn/blob/master/op-guide/migration.md#使用-mydumperloader-全量导入数据

**Comment by oklqh** [comment]
@shenli  thanks for your reply.

can i use mydumper to backup tidb?

there is another way i can imagine:
tidb --> mysql ---> xtrabacup

**Comment by shenli** [comment]
You can use mydumper to backup data from tidb and use loader to load the data to mysql or another tidb.
I have no idea about the `xtrabacup`.

**Comment by oklqh** [comment]
thank you @shenli 

英文不好，只是想让更多人看到这个问题。如果文档里有一节专门讲备份的就好了，你给的链接内容讲的都是从myql导出和向tidb导入，初看文档的人并不好确认mydumper是否就是tidb的备份工具。

tidb的理念和设计都很好，我们也正打算进行测试看是否能用于我们的线上环境，感谢你们的伟大创意和付出！

**Comment by shenli** [comment]
OK！We will add a document for backup and recover.
