### ISSUE TITLE
tidb can not start when inject one tidb restart

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#39854]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
inject one tidb restart

### 2. What did you expect to see? (Required)
tidb can start

### 3. What did you see instead (Required)
tidb can not start
github.com/pingcap/tidb/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:313\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:213\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250

### 4. What is your TiDB version? (Required)
master

**Comment by Defined2014** [comment]
After https://github.com/pingcap/tidb/pull/39616 merged, when an old TiDB cluster upgrade to the newest one, it will create distribute reorg table and set ddl version to 1 which will cause recreate MDL table and report error.
