### ISSUE TITLE
Refine the strategy of auto analyze partition table

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#39871]
## Enhancement

Assume table `t` has two partitions, `p0` and `p1`. Both partitions are frequently written and need auto analyze. Each time when `autoAnalyzeWorker` chooses `t` for auto analyze, it executes `analyze table t partition p0` since default value of `tidb_auto_analyze_partition_batch_size` is 1. As a result, `p1` has little change to be auto analyzed and merging global stats always fails.

![20221213-143009](https://user-images.githubusercontent.com/30385241/207243216-f90d4237-560c-41da-b185-a1d1b1dbba25.jpeg)
<img width="1678" alt="Screen Shot 2022-12-13 at 2 30 57 PM" src="https://user-images.githubusercontent.com/30385241/207243243-2a3a517d-7ed8-4b00-9fb4-25384b4dce75.png">

**Comment by hi-rustin** [comment]
We have updated the default value to 128, so there shouldn't be a major issue.
