### ISSUE TITLE
load data with generated column will report an error 

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#39885]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t(a int, b int generated ALWAYS AS (a+1));
Query OK, 0 rows affected (0.06 sec)

mysql> insert into t(a) values (1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into t(a) values (2);
Query OK, 1 row affected (0.00 sec)

mysql> load data infile '/tmp/1.sql' into table t;
ERROR 8067 (HY000): Load data: unmatched columns
```

### 2. What did you expect to see? (Required)

success

**Comment by cfzjywxk** [comment]
I thinl calculating generated columns in the load statements is not supported yet. 
@TonsnakeLin 
PTAL

**Comment by TonsnakeLin** [comment]
we can use the statement as below to load data into a table with generated column.
load data local infile 'tmp.txt' into table t(a);
So, TiDB supports load data into the table with generated column, but it must specify these columns that are not generated colmuns.

**Comment by TonsnakeLin** [comment]
what's the content of the file `/tmp/1.sql` ?  I think  it is a csv like file, not a  sql statements, right ?  @xiongjiwei

**Comment by xiongjiwei** [comment]
> what's the content of the file `/tmp/1.sql` ? I think it is a csv like file, not a sql statements, right ? @xiongjiwei

Yes. I insert some data into `t`, select them into file `/tmp/1.sql`

**Comment by xiongjiwei** [comment]
> we can use the statement as below to load data into a table with generated column. `load data local infile 'tmp.txt' into table t(a);` So, TiDB supports load data into the table with generated column, but it must specify these columns that are not generated colmuns.

Well, MySQL support this usage, which seems it can filter out the generated column automatic
