### ISSUE TITLE
pitr restore fail for "memory is limited;" with flashback data

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#39907]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. start pitr job
2. do full backup 
3. prepare 5 * 350000 * 100k data
4. run update for 20 minutes
5. do flashback to after prepare before update
6. pitr restore data to new cluster

### 2. What did you expect to see? (Required)
restore successfully
### 3. What did you see instead (Required)
restore fail 
try to change config: 
import.memory-use-ratio=0.0 or import.memory-use-ratio: 0.2
--pitr-concurrency=16 --pitr-batch-count=1 
tried many times but still can't restore successfully

### 4. What is your TiDB version? (Required)

[root@node1 ~]# tiup br:v6.5.0 -V
Starting component `br`: /root/.tiup/components/br/v6.5.0/br -V
Release Version: v6.5.0
Git Commit Hash: b6cd268da7509b9af382a353b50186c87956dded
Git Branch: heads/refs/tags/v6.5.0
Go Version: go1.19.3
UTC Build Time: 2022-12-07 06:59:49
Race Enabled: false
[root@node1 ~]#

**Comment by seiya-annie** [comment]
[tikv.log.gz](https://github.com/pingcap/tidb/files/10223970/tikv.log.gz)

**Comment by seiya-annie** [comment]
RCA: https://github.com/tikv/tikv/pull/13888 not merged in 6.5

**Comment by joccau** [comment]
fixed by https://github.com/pingcap/tidb/pull/41982
