### ISSUE TITLE
modify column for partition table with index cause data inconsistency

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#39915]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In test TestAlterModifyColumnOnPartitionedTable

add `admin check table t` after `alter table t modify b varchar(200) charset latin1`.
<img width="941" alt="image" src="https://user-images.githubusercontent.com/17380469/207505145-ea64cc4d-287d-4d6c-9f2d-c5582a220064.png">

### 2. What did you expect to see? (Required)
test pass
### 3. What did you see instead (Required)
```
[admin:8223]data inconsistency in table: t, index: b, handle: 7, index-values:"" != record-values:"handle: 7, values: [KindString 07]"

```

### 4. What is your TiDB version? (Required)
6.5 master

**Comment by mjonss** [comment]
This has only been reverted in 6.5 and should be fixed properly in master, so I am reopening this issue.

**Comment by wjhuang2016** [comment]
Close it since we disable modify column for partition now.
