### ISSUE TITLE
The queries in `autocommit` mode doesn't read with lock when pessimistic-auto-commit turned on

### ISSUE THREAD

**Issue by TonsnakeLin** [pingcap/tidb#39928]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

CREATE TABLE `sbtest3` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `k` int(11) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`) ,
  KEY `k_1` (`k`)
) 

-- session 1
begin;
insert into sbtest3 values(200002,111,"aaa","aaa");

-- session2
update sbtest3 set k = 222 where id = 200002;

### 2. What did you expect to see? (Required)
session2 is blocked because of lock wait.

### 3. What did you see instead (Required)
`Query OK, 0 rows affected (0.01 sec)
Rows matched: 0  Changed: 0  Warnings: 0`

### 4. What is your TiDB version? (Required)

| Release Version: v6.2.0-alpha-1709-gafb5cf6-dirty
Edition: Community
Git Commit Hash: afb5cf652a2a0c383b2e36b584d5e744e012c210
Git Branch: longtail-diag
UTC Build Time: 2022-12-14 07:51:55
GoVersion: go1.19
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

**Comment by zyguan** [comment]
The issue exists in point plans, we may need to check pessimistic-auto-commit [here](https://github.com/pingcap/tidb/blob/97a9e63d789ea5bace36b82526ea105a1ac65891/planner/core/point_get_plan.go#L611).
