### ISSUE TITLE
How is tidb/tikv implement  isolation level serializable 

### ISSUE THREAD

**Issue by ming-relax** [pingcap/tidb#3996]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I am trying to understand how tidb/tikv implement the `serializable` isolation level and compare it with MySQL. Here is what I was doing:

- Create a table and insert some values:
```
mysql> select * from test_counts;
+----+-------+
| id | count |
+----+-------+
|  1 |    14 |
|  2 |    14 |
+----+-------+
```

 - Open two tidb sessions (A, B) and type in the following:
```
`1: TX A`: start transaction;
`2: TX A`: set session transaction isolation level serializable;
`3: TX B`: start transaction;
`4: TX B`: set session transaction isolation level serializable;
`5: TX A`: select * from test_counts where count = 14;
`6: TX A`: update test_counts set count = 13 where id = 1;
`7: TX B`: select * from test_counts where count = 14;  (MySQL console get blocked here without any output)
`8: TX B`: update test_counts set count = 13 where id = 2;
`9: TX A`: commit;
`10: TX B`: commit;
```

In MySQL, step 7 will be blocked until step 9 committed the TX A. This is the supposed behavior of serializable isolation level.

In TiDB, step 7 is not blocked, and TX B finally get committed successfully. I thought that TiDB should abort TX B in TiDB. 

Am I missing something here?

2. What did you expect to see?

TiDB should abort TX B.

3. What did you see instead?

TX B runs successfully, and there is no blocking of TX B.

4. What version of TiDB are you using (`tidb-server -V`)?

tidb-server: `584a0c32dc795e2b898ea5051367c1e99656ca21`

tikv-server: `38547be23a1e039955d137d4426ed4d7de88f335`

**Comment by shenli** [comment]
@ming-relax TiDB implements an optimistic transaction model. So there will be no block operation and lock checking until meeting commit command. See： https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md#transaction

For Isolation Level, TiDB support Snapshot Isolation and Read Committed. SI is the default isolation level. 
If you want to achieve serializable, you need to use the `select for update` syntax.
