### ISSUE TITLE
There is a large gap with the actual memory used and tidb_server_memory_usage (analyze)

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#39971]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

analyze a big wide table(2k+ column size, 20+ columns and 4billion rows)  
![img_v2_14720524-259e-4de7-a7ff-50500a00e77g](https://user-images.githubusercontent.com/7677963/207815181-2e398c25-c72a-4fde-8eed-830b5d2d0486.jpg)
![88d2a262-857e-4059-ba98-f75c3ee98788](https://user-images.githubusercontent.com/7677963/207815195-e99afc63-55dc-4223-bae8-c76e26d33348.jpeg)

### 4. What is your TiDB version? (Required)

6.5

**Comment by chrysan** [comment]
![img_v2_3a2487ff-773d-4ccb-9b44-a93d28f638fg](https://user-images.githubusercontent.com/5151781/208337122-4e9ffff5-ed73-4738-82f9-8f6613ba23cd.jpg)
![DmGgzhkT6q](https://user-images.githubusercontent.com/5151781/208337142-65403da6-a1d5-4493-b49a-51520c713a6e.jpg)
The times finalizer is called is less than expected. It's not reliable, will close gc_aware firstly.
