### ISSUE TITLE
Optimize memdb in union_store.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#400]
Currently, we use goleveldb's memdb as in memory store.
We need a better implementation.

**Comment by xwb1989** [comment]
I'm interested in this issue but not sure where to start. 

Once thing caught my attention is `UnionIter.updateCur()` is implicitly depending on a contract that: 
* `memdb` and `snapshot`'s iterators are iterating their k/v storage deterministically and in the same order; it's presumably true if they use the same `COMPARE` function for ordering keys, and more specifically, `bytes.Compare` in current implementation. 

The caveat is there is no way to enforce such contract and we can not extend the contract to other `COMPARE` functions in current implementation.

**Comment by ngaut** [comment]
The problem of  memdb is performance and memory costs. You may simply  write a new implementation to replace memdb. Union store is the only place where currently use memdb. Actually snapshot use the Iterator interface, not memdb.

**Comment by ngaut** [comment]
@xwb1989 If you need any help, Please let me know. Thanks for contributing.
Looking forward your PR.

**Comment by xwb1989** [comment]
A handy option would be adopting the btree in this directory; I'm concerned that it's not a concurrent implementation and throughout would be limited under high contention. May I know more about the use case/requirement and do you have benchmark to evaluate the performance?

**Comment by xwb1989** [comment]
Well it seems that memkv is being used otherwhere but you have a plan to replace(according to comments), so it's better not to rely on that package.

**Comment by xwb1989** [comment]
NVM, just realized the only consumer of UnionStore is transaction, which is(I think as a standalone transaction) is never supposed to be in a concurrent context.

**Comment by ngaut** [comment]
@xwb1989 You are right. The only consumer of UnionStore is transaction.
