### ISSUE TITLE
PD cluster crash and restart can not up 

### ISSUE THREAD

**Issue by wfxxh** [pingcap/tidb#40053]
**My cluster topo is:**

![image](https://user-images.githubusercontent.com/22764286/208578474-e786d0a0-eec6-4775-ac40-f78a5b5631af.png)
![image](https://user-images.githubusercontent.com/22764286/208578584-7c3eee7c-0589-4530-8246-715cca832d09.png)
![image](https://user-images.githubusercontent.com/22764286/208578618-3c6fda9d-ee13-43cb-8bc8-1509fb61dfc2.png)

We have use tidb for about 4 years, and this year we update tidb version to v5.4.2 ,this version run about half a year.

![image](https://user-images.githubusercontent.com/22764286/208578712-e44aeafc-a693-4b15-b3e9-232c278bea7a.png)
![image](https://user-images.githubusercontent.com/22764286/208578768-21c0b47e-5f7c-4010-a22d-4021190fe0af.png)
Yestarday ,the pd dashboard show can not find prometheus. But my prometheus status is OK and no error log ,at the same time my grafana use the same prometheus ,the status of grafana is OK ,too . When i specify the prometheus url it is worked. 
About an hour, the pd cluster crash and restart failed. My tidb cluster crash. 

**This is pd log**

[https://asktug.com/t/topic/998131](url)

**Comment by jebter** [comment]
The issue failed to reproduce，I will close this issue, if there are any updates, you can reopen it.You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese).
