### ISSUE TITLE
The max_execution_time hint can not take effect 

### ISSUE THREAD

**Issue by Reminiscent** [pingcap/tidb#40057]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int, b int);
insert /*+ max_execution_time(10) */ into t value(sleep(1), sleep(1));
update /*+ max_execution_time(10) */ t set a = sleep(1);
delete /*+ max_execution_time(1) */ from t where a = sleep(1);
```

### 2. What did you expect to see? (Required)
The execution can be killed successful.

### 3. What did you see instead (Required)
![img_v2_86fab32c-392d-46c3-9fca-59461fcbd1dg](https://user-images.githubusercontent.com/41809508/208615325-ee880ce9-f33e-46ed-9b11-119c84d794b0.jpg)

### 4. What is your TiDB version? (Required)

lastest master

**Comment by hawkingrei** [comment]
I think it is relation with https://github.com/pingcap/tidb/pull/38671

**Comment by hawkingrei** [comment]
<img width="782" alt="image" src="https://user-images.githubusercontent.com/3427324/209102809-4eaaf2c2-0b65-45ac-a2ed-14c994c805aa.png">

I try it with MySQL. I found it is not a bug. It's action is the same as mysql
