### ISSUE TITLE
planner: ignore-plan-cache hint cannot work for insert-stmt

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#40079]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> create table t (a int);
Query OK, 0 rows affected (0.04 sec)

mysql> prepare st from 'insert /*+ ignore_plan_cache() */ t values (1)';
Query OK, 0 rows affected (0.01 sec)

mysql> execute st;
Query OK, 1 row affected (0.01 sec)

mysql> execute st;
Query OK, 1 row affected (0.00 sec)

mysql> select @@last_plan_from_cache;
+------------------------+
| @@last_plan_from_cache |
+------------------------+
|                      1 |
+------------------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
The result of `@@last_plan_from_cache` should be 0 since there is an `ignore-plan-cache` hint.

### 3. What did you see instead (Required)
It's 1.

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+-----------------------------------------+
| version()                               |
+-----------------------------------------+
| 5.7.25-TiDB-v6.6.0-alpha-40-g030c50604a |
+-----------------------------------------+
1 row in set (0.00 sec)
```

**Comment by XuHuaiyu** [comment]
Before this issue, the memory usage of batch insert scenario is high and even trigger OOM. 
![OB2fjuf5Wf](https://user-images.githubusercontent.com/9039012/217719856-7cb09bf8-deed-4b68-bfe7-fd37b930db34.jpg)

**Comment by XuHuaiyu** [comment]
After fixing this issue, the memory consumption goes down to a stable value.
![BSL7MACiXP](https://user-images.githubusercontent.com/9039012/217720157-82798bfc-1c69-4bc1-996b-227ca6dcce52.jpg)

**Comment by XuHuaiyu** [comment]
To reproduce the case with memory pressure, we can use this script:
[insert_memory_pressure.txt](https://github.com/pingcap/tidb/files/10693567/insert_memory_pressure.txt)
