### ISSUE TITLE
Request source context is not correctly set for DDL

### ISSUE THREAD

**Issue by you06** [pingcap/tidb#40099]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Prepare sysbench, and create a new index.

### 2. What did you expect to see? (Required)

No unknown internal request source metrics.

### 3. What did you see instead (Required)

![image](https://user-images.githubusercontent.com/9587680/209056465-a247ddbb-03a6-40f3-8d57-a20b11dbd674.png)

### 4. What is your TiDB version? (Required)

```
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: fc3f04b7b6a471449933b86b3eaa9d1d4bd6a02e
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2022-12-21 14:38:34
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv 
```

**Comment by cfzjywxk** [comment]
@you06 
Is the v6.4 affected?

**Comment by you06** [comment]
> Is the v6.4 affected?

Yes, it's affected, but v6.4 is a DMR release.

One interesting thing is that if we find metrics like `xxxx-internal_unknown`, it's an untagged DDL reorg task. Different from other unknown tasks, the DDL reorg task is marked as **internal**, just no specific DDL type.

**Comment by cfzjywxk** [comment]
> > Is the v6.4 affected?
> 
> Yes, it's affected, but v6.4 is a DMR release.
> 
> One interesting thing is that if we find metrics like `xxxx-internal_unknown`, it's an untagged DDL reorg task. Different from other unknown tasks, the DDL reorg task is marked as **internal**, just no specific DDL type.

/cc @dbsid
