### ISSUE TITLE
我想开启binlog，然后把binlog发送到rocketMq要怎么搞？

### ISSUE THREAD

**Issue by hanjieliao** [pingcap/tidb#40096]
## General Question

我想开启binlog，然后把binlog发送到rocketMq要怎么搞？ 我看官网好像只有同步到kafka的说明

**Comment by lichunzhu** [comment]
> 我想开启binlog，然后把binlog发送到rocketMq要怎么搞？ 我看官网好像只有同步到kafka的说明

TiDB-binlog only supports kafka now. Supporting rocketMq is not in our plan now. If you want to do it you may contribute to [TiDB-Binlog](https://github.com/pingcap/tidb-binlog/tree/master/drainer/sync).
