### ISSUE TITLE
txn: the left pessimistic lock may break the constraint check

### ISSUE THREAD

**Issue by cfzjywxk** [pingcap/tidb#40114]
### 1. Minimal reproduce step (Required)
```
drop table if exists t;
create table t(a int key, b int, key k(b));
insert into t values(1, 2);

begin pessimistic;
// Here inject an error though that the pessimistic lock is executed successfully and 
// skip the "asyncPessimisticRollback", so a pessimistic lock on row key "1" is left.  
// A more common case the user would encounter is:
// 1. The pessimistic lock requests are sent to serveral regions, for example, 2 regions.
// 2. The first pessimistic lock request is executed successfully, but the second one fails because of lock wait.
// 3. The statement receives lock wait timeout error, and the async pessimistic lock rollback fails.
// 4. The pessimistic lock on region 1 is left.
delete from t; 
// Try to insert another row with the same row key, the insert should fail because of "duplicated entry".
insert into t values(1, 5);
commit;
```

### 2. What did you expect to see? (Required)
```
mysql> insert into t values(1, 5);
ERROR 1062 (23000): Duplicate entry '1' for key 't.PRIMARY'
```

### 3. What did you see instead (Required)
```
mysql> begin pessimistic;
Query OK, 0 rows affected (0.00 sec)

mysql> delete from t;insert into t values(1, 5);
ERROR 1105 (HY000): injected error after successful locking for delete key={key 15 0 7480000000000001315f728000000000000001 <nil>}
Query OK, 1 row affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.01 sec)

mysql> select * from t;
+---+------+
| a | b    |
+---+------+
| 1 |    5 |
+---+------+
1 row in set (0.01 sec)

mysql> select * from t use index(k);
+---+------+
| a | b    |
+---+------+
| 1 |    2 |
| 1 |    5 |
+---+------+
2 rows in set (0.01 sec)

mysql> admin check table t;
ERROR 8134 (HY000): data inconsistency in table: t, index: k, col: b, handle: "1", index-values:"KindInt64 2" != record-values:"KindInt64 5", compare err:<nil>
```

The pessimistic lock request raised by the `insert` statement contains a `presumeNotExist` flag, because the lock is left by 
previous `delete` statement the constraint check is skipped, and the uniqueness constraint is broken.

### 4. What is your TiDB version? (Required)
Nightly with commit `aeccf77637e133b9c4edf04d422350d9db1a1822`

**Comment by MyonKeminta** [comment]
The cause of the problem seems be that when TiKV runs `acquire_pessimsitic_lock` on a key that's already locked by the same transaction (for providing idempotency), TiKV didn't check the `should_not_exist` flag. In this case, if we let TiKV check the `should_not_exist` flag and do not update the lock's `for_update_ts` if the check fails (so that it can still be removed by later-arriving `pessimistic_rollback`), the problem seems can be fixed. But I'm not sure if there's more complicated case that's still problematic.

**Comment by MyonKeminta** [comment]
The above data inconsistency is produced with assertion disabled. If assertion is enabled, an assertion failure will be reported when committing the problematic transaction.
