### ISSUE TITLE
To support drop column with index

### ISSUE THREAD

**Issue by blacktear23** [pingcap/tidb#4012]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```sql
create table `t` (`id` int(11), `name` varchar(255), key `idx_name` (`name`));
alter table `t` drop column `name`
```

2. What did you expect to see?

`name` column should be deleted with out any error. In MySQL:

```
mysql> alter table t drop column name;
Query OK, 0 rows affected (0.06 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

3. What did you see instead?

```
mysql> alter table t drop column name;
ERROR 1105 (HY000): can't drop column name with index covered now
```

this "feature" will break some ORM's migration scripts.

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
Currently we does not support dropping column with index. Please refer to [docs](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md).

**Comment by blacktear23** [comment]
Sure I know that. But the important thing is this will break some ORM's migration script. Such as django-orm.

**Comment by breeswish** [comment]
I modified your issue title to better fit your idea.

**Comment by zimulala** [comment]
It's duplicated with #3364
