### ISSUE TITLE
ddl: when enable global index on partition table, unique index constraint not normal 

### ISSUE THREAD

**Issue by jiyfhust** [pingcap/tidb#40145]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
1. enable global index

tidb.toml:
enable-global-index = true

2. create test_t1 with global index p_a
mysql> CREATE TABLE `test_t1` (
  `a` int(11) DEFAULT NULL,
  `b` int(11) DEFAULT NULL,
  `c` int(11) DEFAULT NULL,
  UNIQUE KEY `p_a` (`a`),
  KEY `p_b` (`b`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY RANGE (`c`)
(PARTITION `p0` VALUES LESS THAN (10),
 PARTITION `p1` VALUES LESS THAN (MAXVALUE));

3. insert data

mysql> insert into test_t1 values(1,1,1);
Query OK, 1 row affected (0.01 sec)

mysql> insert into test_t1 values(1,1,11);
Query OK, 1 row affected (0.00 sec)

because there is a unique index p_a on column a, it should report a duplicat error.
 
4. add log on tidb, print index type:

 ["index type"] [table=test_t1] [index=p_a] [global=false]
 ["index type"] [table=test_t1] [index=p_b] [global=false]

```

### 2. What did you expect to see? (Required)

```

ERROR 1062 (23000): Duplicate entry '1' for key 'test_t1.p_a'

```

### 3. What did you see instead (Required)

no error

### 4. What is your TiDB version? (Required)

master

**Comment by mjonss** [comment]
As an issue this has currently low priority, since global index is not yet supported, and does not really work yet. We hope to work on it after we implemented https://github.com/pingcap/tidb/issues/38535 and other missing MySQL features like alter a non-partitioned table to a partitioned table and vice versa.

**Comment by jiyfhust** [comment]
hi @mjonss ，can i give a small pr to fix it, it seems not complex，just one line is enough.
In the example above， index(p_a) is a global index，but create table forget to set the flag, then the error occur.

**Comment by mjonss** [comment]
> hi @mjonss ，can i give a small pr to fix it, it seems not complex，just one line is enough. In the example above， index(p_a) is a global index，but create table forget to set the flag, then the error occur.

@jiyfhust of course, all patches are welcome :)
