### ISSUE TITLE
ERROR 1105 (HY000): Can't find column Column#4 in schema Column: [test.t1.id,test.t1.dt1] Unique key: []

### ISSUE THREAD

**Issue by harry1129** [pingcap/tidb#40159]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> create table t1(id int,dt1 date);
Query OK, 0 rows affected (0.10 sec)

mysql> select id,dt2 from (select t1.id,ifnull(t1.dt1,now())dt2 from t1) v where dt2=str_to_date('2021-12-31','%Y-%m-%d');
ERROR 1105 (HY000): Can't find column Column#4 in schema Column: [test.t1.id,test.t1.dt1] Unique key: []
mysql> 

### 2. What did you expect to see? (Required)
No Error
### 3. What did you see instead (Required)
ERROR 1105
### 4. What is your TiDB version? (Required)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.1.1
Edition: Community
Git Commit Hash: 5263a0abda61f102122735049fd0dfadc7b7f8b2
Git Branch: heads/refs/tags/v6.1.1
UTC Build Time: 2022-08-25 10:36:00
GoVersion: go1.18.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by jebter** [comment]
This issue is fixed in v6.1.3

**Comment by harry1129** [comment]
Which pr? @jebter

**Comment by jebter** [comment]
I can reproduce on v6.1.1, but not on v6.1.3。

**Comment by zanmato1984** [comment]
Redirect to planner.

**Comment by qw4990** [comment]
Fixed by https://github.com/pingcap/tidb/pull/38802.
