### ISSUE TITLE
The TopN's result is not stable as before

### ISSUE THREAD

**Issue by zgcbj** [pingcap/tidb#40186]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
CREATE TABLE `table1` (
  `id` bigint(11) unsigned NOT NULL ,
  `table1_col2` varchar(128) DEFAULT '' ,
  `table1_col3` varchar(32) DEFAULT '' ,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ;
INSERT INTO `table1` VALUES (14786,'4973','2022-12-22'),(14794,'4974','2022-12-21'),(14810,'4972','2022-12-21'),(14828,'4973','2022-12-21'),(41109,'4974','2022-12-22'),(41128,'4818','2022-12-22'),(41132,'4819','2022-12-22'),(41134,'4972','2022-12-22'),(41136,'4975','2022-12-22'),(41186,'4818','2022-12-21'),(41188,'4819','2022-12-21'),(41191,'4975','2022-12-21');

CREATE TABLE `table2` (
  `id` bigint(11) unsigned NOT NULL ,
  `create_time` datetime NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

INSERT INTO `table2` VALUES (4818,'2022-12-20 15:40:22'),(4819,'2022-12-20 15:40:22'),(4972,'2022-12-22 11:23:46'),(4973,'2022-12-22 11:23:46'),(4974,'2022-12-22 11:23:46'),(4975,'2022-12-22 11:23:46');
```

query like this: 
```
mysql> SELECT o.id AS id,
    ->           o.create_time AS create_time,
    ->          r.table1_col3 AS table1_col3
    -> FROM
    ->     (SELECT table1_col2,
    ->          table1_col3
    ->            FROM table1
    ->     WHERE 1=1
    ->             AND table1_col3 >= '2022-12-15'
    ->             AND table1_col3 <= '2022-12-25 23:59:59'
    ->     GROUP BY  table1_col2,table1_col3 ) r
    -> LEFT JOIN table2 o
    ->     ON r.table1_col2=o.id
    -> ORDER BY  o.create_time DESC limit 0,10;
+------+---------------------+-------------+
| id   | create_time         | table1_col3 |
+------+---------------------+-------------+
| 4975 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4975 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4972 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4972 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4973 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4973 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4974 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4974 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-21  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-22  |
+------+---------------------+-------------+
10 rows in set (0.01 sec)

mysql> SELECT o.id AS id,           o.create_time AS create_time,          r.table1_col3 AS table1_col3 FROM      (SELECT table1_col2,          table1_col3            FROM table1     WHERE 1=1             AND table1_col3 >= '2022-12-15'             AND table1_col3 <= '2022-12-25 23:59:59'     GROUP BY  table1_col2,table1_col3 ) r LEFT JOIN table2 o     ON r.table1_col2=o.id ORDER BY  o.create_time DESC limit 10,10;
+------+---------------------+-------------+
| id   | create_time         | table1_col3 |
+------+---------------------+-------------+
| 4819 | 2022-12-20 15:40:22 | 2022-12-21  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-22  |
+------+---------------------+-------------+
```
query like this:
```
mysql> SELECT o.id AS id,           o.create_time AS create_time,          r.table1_col3 AS table1_col3 FROM      (SELECT table1_col2,          table1_col3            FROM table1     WHERE 1=1             AND table1_col3 >= '2022-12-15'             AND table1_col3 <= '2022-12-25 23:59:59'     GROUP BY  table1_col2,table1_col3 ) r LEFT JOIN table2 o     ON r.table1_col2=o.id ORDER BY  o.create_time DESC limit 0,20;
+------+---------------------+-------------+
| id   | create_time         | table1_col3 |
+------+---------------------+-------------+
| 4972 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4972 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4973 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4973 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4974 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4974 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4975 | 2022-12-22 11:23:46 | 2022-12-22  |
| 4975 | 2022-12-22 11:23:46 | 2022-12-21  |
| 4818 | 2022-12-20 15:40:22 | 2022-12-21  |
| 4818 | 2022-12-20 15:40:22 | 2022-12-22  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-21  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-22  |
+------+---------------------+-------------+
12 rows in set (0.00 sec)
```

### 2. What did you expect to see? (Required)
limit 0, 10 + limit 10, 10 = limit 0,20 
### 3. What did you see instead (Required)
limit 0, 10 + limit 10, 10 != limit 0,20
### 4. What is your TiDB version? (Required)
v5.4.0
v5.4.3
v6.1.3

**Comment by winoros** [comment]
```
| 4818 | 2022-12-20 15:40:22 | 2022-12-21  |
| 4818 | 2022-12-20 15:40:22 | 2022-12-22  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-21  |
| 4819 | 2022-12-20 15:40:22 | 2022-12-22  |
+------+---------------------+-------------+
```
The IDs 4818 and 4819 share the same create_time. So when you call `order by create_time desc limit 0, 10`. It's a valid result whether you return ID 4818 or ID 4819.

**Comment by zgcbj** [comment]
merge join is ok!
if hash join can`t work in this condation, tidb should choice other join method.

**Comment by zgcbj** [comment]
@c4pt0r  PTAL

**Comment by fixdb** [comment]
The result is ok. If you want stable result, you should specify id or table1_col3 in order by columns.

**Comment by zgcbj** [comment]
> The result is ok. If you want stable result, you should specify id or table1_col3 in order by columns.

Under the premise of not changing the data, the result set is stable, but it shows a stable error result.

In my understanding, limit is a view of the result set, each time a part of the result set is taken out, and finally the entire result set can be seen.

Does this behavior of TiDB conform to the SQL standard?

**Comment by zgcbj** [comment]
> 

Or, does it mean that select * from table order by create_time limit 0,10, if create_time repeats, you will not be able to get all the data in the table?

**Comment by zgcbj** [comment]
@3AceShowHand @3pointer @AilinKid @AndreMouche @Benjamin2037 @BornChanger @CbcWestwolf @CharlesCheung96 @ChenPeng2013 @D3Hunter @Deardrops @Defined2014 @Ehco1996 @GMHDBJD @IANTHEREAL @JmPotato @Leavrth @Little-Wallace @LittleFall @MyonKeminta @Reminiscent @SeaRise @SunRunAway @TonsnakeLin @TszKitLo40 @WizardXiao @XuHuaiyu @YangKeao @Yisaer @YuJuncen @amyangfei @andylokandy @asddongmen @aytrack @b41sh @bb7133 @ben1009 @breezewish @buchuitoudegou @c4pt0r @cfzjywxk @chrysan @coocood @crazycs520 @csuzhangxc @disksing @djshow832 @dsdashun @dveeden @ekexium @eurekaka @fengou1 @fixdb @francis0407 @fzzf678 @glorv @gozssky @guo-shaoge @hanfei1991 @hawkingrei @hi-rustin @hicqu @iamxy @ichn-hu @jackysp @joccau @js00070 @july2993 @kennytm @lance6716 @lcwangchao @lichunzhu @maxshuang @mengxin9014 @mjonss @mmyj @morgo @mornyx @ngaut @niubell @nolouch @nongfushanquan @okJiang @overvenus @pingyu @qiuyesuifeng @qw4990 @rebelice @rleungx @sdojjy @shenli @shihongzhi @siddontang @sticnarf @suzaku @sylzd @tangenta @tangwz @tiancaiamao @time-and-fate @tisonkun @windtalker @winkyao @winoros @wjhuang2016 @wshwsh12 @xhebox @xiongjiwei @xuyifangreeneyes @you06 @zanmato1984 @zhangjinpeng1987 @zhaoxinyu @zhongzc @zimulala @zyguan @zz-jason

**Comment by fixdb** [comment]
In a distributed database, a query with a LIMIT clause may return different results on different occasions, even if the query and the data in the database have not changed. This can occur because the data is distributed across multiple nodes and the query may be executed in parallel on different nodes.

For example, if you have a distributed database with three nodes and you run the following query:

```sql
SELECT * FROM my_table LIMIT 10, 10;
```
The database system may decide to execute the query in parallel on two of the nodes, with each node returning 10 rows. If the rows returned by the two nodes are not identical, the final result of the query may be different on different occasions.

To ensure a stable result in a distributed database, you may need to use additional query hints or modify the query to include an ORDER BY clause and a unique column in the SELECT list. This would allow the database system to more accurately determine the order of the rows and ensure that the same rows are returned on each occasion.

**Comment by lance6716** [comment]
A short answer:

SQL is a declarative language, which means the user's query can result in many behaviours. Database must not let the behaviour violates the user's query. But if the user only imagines a property while not writes it in the query, database is not aware of it so the property is broken.

As your two paging queries, TiDB will not know they are related. And because the queries only say `ORDER BY  o.create_time`, TiDB will only sort the result on this column and the results are different.

**Comment by zgcbj** [comment]
抱歉，我用中文回复下吧。
感谢各位大佬的回复，也对所有打扰到的reviewer表示抱歉。

这个问题看似是一个小问题，sql中另加一个唯一列参与到order by中就可以解决，但是这代表了 TiDB 对结果集稳定性的处理原则，之所以@了各位大佬，是希望各位大佬能对这类问题进行一些讨论。

我也理解fixdb大佬回复的分布式执行的问题，目前遇到的是hash join时结果集不稳定，换成merge join 就是稳定的，所以，这个结论的意思是 merge join 查询结果的稳定是不可靠的？ 进一步放大，tidb的结果集都是不稳定的吗？

如果答案是：不稳定。那么是否意味着 select * from table 用 limit 翻页，不一定能拿到所有结果，必须加上 order by 唯一列 才能保证能通过 limit 分页拿到表中所有数据？那以后用tidb查询，所有涉及到limit的sql，一定得加一列 order by 唯一列，才能保证结果的正确性对吗？我相信并不是所有用户都了解需要这样做，如果每个用户靠出错一次才意识到正确用法，那对tidb的口碑是会有消极影响的。

**Comment by winoros** [comment]
> 我也理解fixdb大佬回复的分布式执行的问题，目前遇到的是hash join时结果集不稳定，换成merge join 就是稳定的，所以，这个结论的意思是 merge join 查询结果的稳定是不可靠的？ 进一步放大，tidb的结果集都是不稳定的吗？


对的，merge join 稳定也是和它目前的实现方式有关，原则上 TiDB 不保证 merge join 未来一定可以继续稳定下去，只保证结果是合法的。

> 如果答案是：不稳定。那么是否意味着 select * from table 用 limit 翻页，不一定能拿到所有结果，必须加上 order by 唯一列 才能保证能通过 limit 分页拿到表中所有数据？那以后用tidb查询，所有涉及到limit的sql，一定得加一列 order by 唯一列，才能保证结果的正确性对吗？我相信并不是所有用户都了解需要这样做，如果每个用户靠出错一次才意识到正确用法，那对tidb的口碑是会有消极影响的。

目前只能通过 order by 多加一些列来保证。实际上后来的大多数据数据库在做执行性能的优化时，都会无法保证除了 SQL 本身所设置的 ORDER BY 之外，可以满足其他更多的稳定性
