### ISSUE TITLE
Function uncompress return invalid header error

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#4023]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

Uncompresses a string compressed by the COMPRESS() function. If the argument is not a compressed value, the result is NULL. 

```sql
create table t1 (a varchar(32) not null);                                
insert into t1 values ('foo');                                           
select * from t1 where uncompress(a) is null;                            
select *, uncompress(a) from t1;
```

2. What did you expect to see?

```
a
foo
a	uncompress(a)
foo	NULL
```

3. What did you see instead?

```
ERROR 1105 (HY000) at line 3: zlib: invalid header
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by jackysp** [comment]
In addition, `select uncompress(1)` returns `ERROR 1105 (HY000): unexpected EOF` in TiDB, where MySQL gets value `NULL` and a warning.

**Comment by breeswish** [comment]
This is fixed in https://github.com/pingcap/tidb/pull/4095.
