### ISSUE TITLE
Function encrypt not supported

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#4025]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql 
select length(encrypt('foo', 'ff')) <> 0;
```

2. What did you expect to see?

```
length(encrypt('foo', 'ff')) <> 0
1
```

3. What did you see instead?

```
ERROR 1305 (42000) at line 1: FUNCTION ENCRYPT does not exist
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by winkyao** [comment]
>Note
The ENCRYPT() function is deprecated as of MySQL 5.7.6, will be removed in a future MySQL release, and should no longer be used. Consider using AES_ENCRYPT() instead.

**Comment by winkyao** [comment]
see https://github.com/lattera/freebsd/blob/master/secure/lib/libcrypt/crypt-des.c

**Comment by winkyao** [comment]
If implement it use cgo, will make TiDB rely on specific platform, so the better way is port crypt function in golang, but the function is deprecated and will be removed in a future of MySQL, so it isn't a high priority issue now.

**Comment by morgo** [comment]
This function was removed from MySQL 8.0 to prevent users from using weak crypto.  I am going to close this issue for now, but we can re-consider if it becomes a blocking issue for someone.
