### ISSUE TITLE
ticdc auto increment primary key value not bi-directional replication

### ISSUE THREAD

**Issue by geeklc** [pingcap/tidb#40314]
## Bug Report

ticdc auto increment primary key value not bi-directional replication

### 1. Minimal reproduce step (Required)

create A and B cluster，create a table tbl_a with auto increment primary key on both cluster。
create ticdc bi-directional replication changefeeds;
insert value on A cluster，B cluster hava a replicative value;
insert value on B cluster， will error message "1062 duplicate entry '3' for key 'tbl_a.promary'";
insert again on B cluster, normal, and the value replication on A cluser;
and followed insert value on A cluser, normal!!! 

### 2. What did you expect to see? (Required)

auto increment primary key value bi-directional replication。

### 3. What is your TiDB version? (Required)
V6.5.0

Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by fubinzh** [comment]
@geeklc bi-directional replication has a limitation （https://docs.pingcap.com/tidb/stable/ticdc-bidirectional-replication#limitations） that 
"Bi-directional replication clusters cannot detect write conflicts, which might cause undefined behaviors. Therefore, you must ensure that there are no write conflicts from the application side."

In your steps，you create a table tbl_a with auto increment primary key on both cluster, which might result in write conflicts.

**Comment by geeklc** [comment]
@fubinzh with my steps, i write value without increment primary key,  and one side do worker well, not both write conflicts.

**Comment by fubinzh** [comment]
> @fubinzh with my steps, i write value without increment primary key, and one side do worker well, not both write conflicts.

@geeklc Do you mean you explicitly specify column values when inserting values to both clusters? 
It will be helpful if you can let us know the schema of tbl_a, how you created the changefeed, and the SQL you executed to insert values to A and B clusters, thanks.

**Comment by geeklc** [comment]
@fubinzh follow operations:

- create table test_a on both cluster:

```
CREATE TABLE `test_a` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL COMMENT '名字',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001;

````

-  create changefeed command:
```
# create changefeed  on cluster A：
./cdc cli changefeed create --server=http://127.0.0.1:8300 --sink-uri="mysql://root:123456@172.16.182.220:4000/" --changefeed-id="test-bdr"  --config=/home/tidb/bdr.toml
# create changefeed  on cluster B：
./cdc cli changefeed create --server=http://172.16.182.19:8300 --sink-uri="mysql://root:123456@172.16.182.212:4000/" --changefeed-id="test-bdr"   --config=/home/tidb/bdr.toml
````

- bdr.toml 
```
# 指定配置文件中涉及的库名、表名是否为大小写敏感
# 该配置会同时影响 filter 和 sink 相关配置，默认为 true
case-sensitive = true

# 是否输出 old value，从 v4.0.5 开始支持，从 v5.0 开始默认为 true
enable-old-value = true

# 开启双向同步，是否启用 bdr 模式，从v6.5.0开始
bdr-mode = true


# 是否开启 Syncpoint 功能，从 v6.3.0 开始支持，该功能默认关闭。
# 从 v6.4.0 开始，使用 Syncpoint 功能需要同步任务拥有下游集群的 SYSTEM_VARIABLES_ADMIN 或者 SUPER 权限
# enable-sync-point = false

# Syncpoint 功能对齐上下游 snapshot 的时间间隔
# 配置格式为 h m s，例如 "1h30m30s"
# 默认值为 10m，最小值为 30s
# sync-point-interval = "5m"

# Syncpoint 功能在下游表中保存的数据的时长，超过这个时间的数据会被清理
# 配置格式为 h m s，例如 "24h30m30s"
# 默认值为 24h
# sync-point-retention = "1h"

[mounter]
# mounter 解码 KV 数据的线程数，默认值为 16
# worker-num = 16

[filter]
# 忽略指定 start_ts 的事务
# ignore-txn-start-ts = [1, 2]

# 过滤器规则
# 过滤规则语法：https://docs.pingcap.com/zh/tidb/stable/table-filter#表库过滤语法
rules = ['test.*']

# 事件过滤器规则
# 事件过滤器的详细配置规则在下方的 Event Filter 配置规则中描述
# 第一个事件过滤器规则
[[filter.event-filters]]
matcher = ["test.worker"] # matcher 是一个白名单，表示该过滤规则只应用于 test 库中的 worker 表
ignore-event = ["insert"] # 过滤掉 insert 事件
ignore-sql = ["^drop", "add column"] # 过滤掉以 "drop" 开头或者包含 "add column" 的 DDL
ignore-delete-value-expr = "name = 'john'" # 过滤掉包含 name = 'john' 条件的 delete DML
ignore-insert-value-expr = "id >= 100" # 过滤掉包含 id >= 100 条件的 insert DML
ignore-update-old-value-expr = "age < 18" # 过滤掉旧值 age < 18 的 update DML
ignore-update-new-value-expr = "gender = 'male'" # 过滤掉新值 gender = 'male' 的 update DML
```

- operate steps：
```
# 1. insert value into cluster A
INSERT INTO `test`.`test_a`(`name`, `remark`, `create_time`) VALUES ('aa', 'aa', now());
successful ！！
# 2. select from both cluster, and value 'aa' exists.
# 3. insert value into cluster B
 INSERT INTO `test`.`test_a`(`name`, `remark`, `create_time`) VALUES ('bb', 'bb', now());
1062 - Duplicate entry '5' for key 'test_a.PRIMARY'
# 4. insert value into cluster B one more
 INSERT INTO `test`.`test_a`(`name`, `remark`, `create_time`) VALUES ('bb', 'bb', now());
successful !!
# 5. select from both cluster, and value 'bb' exists.
# 6. insert value into cluster A
INSERT INTO `test`.`test_a`(`name`, `remark`, `create_time`) VALUES ('aa1', 'aa1', now());
successful ！！
# 7. select from both cluster, and value 'aa1' exists.
# 8. insert value into cluster B
 INSERT INTO `test`.`test_a`(`name`, `remark`, `create_time`) VALUES ('bb1', 'bb1', now());
1062 - Duplicate entry '5' for key 'test_a.PRIMARY'
```

follow steps，cluster A to B  value replication, but auto-increment ID not  replication。cluster B to A worker well。

**Comment by asddongmen** [comment]
> 

I try to reproduce this issue by the steps but everything work well. Could you try it again and provide more infomation?
Here are my steps:
```
1. Create changefeed on cluster A and cluster B.
2. Create table `test.test_a` in cluster A and Cluster B.
3. Execute the DMLs you mention above in the same order.
4. No any error occurs. 

cluster A:
+----+------+--------+---------------------+
| id | name | remark | create_time         |
+----+------+--------+---------------------+
| 1  | aa   | aa     | 2023-01-11 10:17:49 |
| 2  | bb   | bb     | 2023-01-11 10:17:56 |
| 3  | bb   | bb     | 2023-01-11 10:18:05 |
| 4  | aa1  | aa1    | 2023-01-11 10:18:17 |
| 5  | bb1  | bb1    | 2023-01-11 10:18:29 |
+----+------+--------+---------------------+

cluster B:
+----+------+--------+---------------------+
| id | name | remark | create_time         |
+----+------+--------+---------------------+
| 1  | aa   | aa     | 2023-01-11 10:17:49 |
| 2  | bb   | bb     | 2023-01-11 10:17:56 |
| 3  | bb   | bb     | 2023-01-11 10:18:05 |
| 4  | aa1  | aa1    | 2023-01-11 10:18:17 |
| 5  | bb1  | bb1    | 2023-01-11 10:18:29 |
+----+------+--------+---------------------+
```

**Comment by xiongjiwei** [comment]
how many instances are in cluster A and B? and does the insert always connect to the same instance?

**Comment by geeklc** [comment]
@xiongjiwei 
![image](https://user-images.githubusercontent.com/104407836/211738064-37b85430-736b-4da3-866b-81c70ac06200.png)
![image](https://user-images.githubusercontent.com/104407836/211738208-433ba74d-6671-4a3a-b9ad-fc75697faf15.png)

insert values always connect to the same instance.

**Comment by xiongjiwei** [comment]
Steps 1-7 can have an explanation: step insert 5 into cluster A and replicate to cluster B, then B has a primary key 5. If the auto_increment cached value 5 and you execute an insert, there will be a duplicate key error, then the cached value increase to 6, insert success.

step 8 is wired, it could report an error but the duplicate key should be 6, not 5.

If you can provide the `select * from test_a` after each insert, it will be easier to locate the problem.

**Comment by geeklc** [comment]
@xiongjiwei @asddongmen i has located the problem,

changefeed sink tidb instance different operate tidb instance  can report this error。

for exmple:

- create changefeed commnad：
```
# create changefeed  on cluster A， sink cluster B tidb instance is 172.16.182.220，bug executed sql on cluster B 172.16.182.219：
./cdc cli changefeed create --server=http://127.0.0.1:8300 --sink-uri="mysql://root:123456@172.16.182.220:4000/" --changefeed-id="test-bdr"  --config=/home/tidb/bdr.toml
# create changefeed  on cluster B， sink cluster A tidb instance is 172.16.182.212,  execute sql on same instance。
./cdc cli changefeed create --server=http://172.16.182.19:8300 --sink-uri="mysql://root:123456@172.16.182.212:4000/" --changefeed-id="test-bdr"   --config=/home/tidb/bdr.toml
```
if changefeed sink instance same as execute instance both work well.

**Comment by asddongmen** [comment]
@geeklc Thank you, got it. We consider this is not an error, as @fubinzh mention above "bi-directional replication has a limitation （[https://docs.pingcap.com/tidb/stable/ticdc-bidirectional-replication#limitations）](https://docs.pingcap.com/tidb/stable/ticdc-bidirectional-replication#limitations%EF%BC%89) that "
"Bi-directional replication clusters cannot detect write conflicts, which might cause undefined behaviors. Therefore, you must ensure that there are no write conflicts from the application side."
It is recommended that you specify the primary key explicitly when inserting data rather than using an auto increment primary key, which is a potentially conflicting operation that cannot be avoided with bi-directional replication.

**Comment by okJiang** [comment]
maybe can close this issue

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it，if there are any updates, you can reopen it.
