### ISSUE TITLE
one tidb can not start when restart all pods

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#40330]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
restart all pods

### 2. What did you expect to see? (Required)
pods can start successfully

### 3. What did you see instead (Required)
one tidb can not start
![image](https://user-images.githubusercontent.com/84712107/210695900-0b2a0abc-eb21-4b46-9451-70c72b7f1dc0.png)
[tidb.zip](https://github.com/pingcap/tidb/files/10349187/tidb.zip)

[endless-ha-test-tps-1350438-1-988](https://kube-dashboard.pingcap.net:30009/#/workloads?namespace=endless-ha-test-tps-1350438-1-988)
logs：http://minio.pingcap.net:42041/buckets/test-infra-testground/browse/YXJjaGl2ZS9lbmRsZXNzLWhhLXRlc3QtdHBzLTEzNTA0MzgtMS05ODg=

### 4. What is your TiDB version? (Required)
/ # ./tidb-server -V
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: 1f344ba1081ebf66a8e45ee01c09853f79aa1458
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-01-03 11:59:29
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by Yisaer** [comment]
For now we add timeout for `updateStats exiting` and `start/exit` log for each background process in background, I prefer close this issue until we meet this again.
