### ISSUE TITLE
query reports "strconv.Atoi: parsing "M": invalid syntax"

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#40339]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
DROP TABLE IF EXISTS t1, t2;
CREATE TABLE t1 (c1 tinytext);
CREATE TABLE t2 (c2 datetime);
INSERT INTO t1 VALUES ('2_2(M');
select c2 from t1 left join t2 on c1 = c2;
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
strconv.Atoi: parsing "M": invalid syntax
### 4. What is your TiDB version? (Required)
master

**Comment by tangenta** [comment]
I think it is not common to join an invalid string with a datetime. Changed the severity into "moderate".
