### ISSUE TITLE
br full backup fail during flashback for dead lock

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#40404]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. run workload
2. run flashback to before workload run
3. br full backup during flashback
4. br restore to dest tidb from minio files
5. check dest tidb crc32 checksum
```code
flashback cluster to timestamp '2023-01-09 09:00';
tiup br backup full --pd [172.16.6.46:2379](http://172.16.6.46:2379/) --backupts '2023-01-09 10:48:00' --storage "s3://tmp/backup-46-snapshot-20230109104800-empty?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%[2fminio.pingcap.net](http://2fminio.pingcap.net/)%3a9001&force-path-style=true" --ratelimit 128 --log-file backupfull-46-0109.log
```

### 2. What did you expect to see? (Required)
backup success

### 3. What did you see instead (Required)
backup hang

### 4. What is your TiDB version? (Required)

master

**Comment by zimulala** [comment]
Could we close this issue? @Defined2014

**Comment by Defined2014** [comment]
> Could we close this issue? @Defined2014

Need `BR` and `TiKV` to fix it.

**Comment by zimulala** [comment]
Got it.

**Comment by Defined2014** [comment]
tikv's PR https://github.com/tikv/tikv/pull/14088
