### ISSUE TITLE
Cannot connect TiDB successfully

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tidb#40419]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. tiup cluster 
2. import some data
3. try to connect tidb with "mysql --comments --host 172.16.5.85 --port 61323 -u root -p"

### 2. What did you expect to see? (Required)

connect tidb successfully

### 3. What did you see instead (Required)

cannot connect tidb.
![image](https://user-images.githubusercontent.com/26538495/211267824-bb85a4e9-9403-4e9e-92a0-eada45341ebb.png)

log in tidb.log

[2023/01/09 16:37:56.218 +08:00] [WARN] [expensivequery.go:77] ["auto analyze timeout, kill it"] [costTime=93h1m27.929497395s] [maxAutoAnalyzeTime=12h0m0s] [processInfo="{id:7749771368937291779, user:, host:, db:<nil>, command:Sleep, time:334887, state:autocommit, info:analyze table `rtdb`.`zto_ssmx_bill_detail`}"]
[2023/01/09 16:37:56.218 +08:00] [INFO] [server.go:748] [kill] [connID=7749771368937291779] [query=true]

info in goroutine: http://172.16.5.85:61324/debug/pprof/goroutine?debug=1
![RuYoRCTKN6](https://user-images.githubusercontent.com/26538495/211268088-5c6de94d-bdc1-4bae-aad0-ce13e86f2a17.jpg)

### 4. What is your TiDB version? (Required)

./tidb-server -V
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: bf2cc452066cb0269f4036d748ad4fa96eb021b8
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-01-04 14:33:10
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by chrysan** [comment]
Close it since it's the same with https://github.com/pingcap/tidb/issues/40548
