### ISSUE TITLE
handle ddl event failed

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#40421]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

run the random test schrDDL, and check the log on the dashboard.
![Uploading img_v2_0d6f9e98-9446-46cb-afa2-d2d722f8382g.jpg…]()

### 4. What is your TiDB version? (Required)
master

**Comment by xuyifangreeneyes** [comment]
![20230112-103643](https://user-images.githubusercontent.com/30385241/211962599-9fc48bd6-ae21-4ac6-be9d-c056326c7642.jpeg)

**Comment by Rustin170506** [comment]
It fixed by https://github.com/pingcap/tidb/pull/57872

We don't drop any events anymore.
