### ISSUE TITLE
formatting of "PD server timeout" error seems wrong

### ISSUE THREAD

**Issue by dveeden** [pingcap/tidb#40439]
## Bug Report

`ADMIN CHECK TABLE...` can fail with a `PD server timeout` error like this:

```
sql> admin check table table1;
ERROR: 9001 (HY000): PD server timeout%!(EXTRA string=start timestamp may fall behind safe point)
```

It looks like https://github.com/pingcap/tidb/blob/b912237ac78b66057040e7d7d45fb84df6f81548/store/driver/error/error.go#L108 might be where `ErrPDServerTimeout` is used with an extra string.

This happened on v6.1.2 but the code from current master looks to be affected as well.

**Comment by dveeden** [comment]
@AndreMouche @hawkingrei  should add an argument to `errno.ErrPDServerTimeout` or would that create issues elsewhere?

**Comment by AndreMouche** [comment]
Good catch, would you like to fix it?
