### ISSUE TITLE
about storage engine

### ISSUE THREAD

**Issue by 6api** [pingcap/tidb#4048]
how can i use LMDB as storage engine?

**Comment by shenli** [comment]
You should implement a driver for LMDB and register is here: https://github.com/pingcap/tidb/blob/master/tidb-server/main.go#L83

Then you can choose LMDB as storage engine through this argument: https://github.com/pingcap/tidb/blob/master/tidb-server/main.go#L49


Here is examples of using goleveldb and boltdb as storage engine:
https://github.com/pingcap/tidb/blob/master/store/localstore/boltdb/boltdb.go
https://github.com/pingcap/tidb/blob/master/store/localstore/goleveldb/goleveldb.go

**Comment by blacktear23** [comment]
@6api you can reference my PR #4061
