### ISSUE TITLE
read multi-valued index get wrong result if using char(N)

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#40558]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
DROP TABLE t1;
CREATE TABLE t1 (f1 JSON, KEY i1((CAST(f1->"$[*]" AS CHAR(10) ARRAY))));
INSERT INTO t1(f1) VALUES(CAST('["abc"]' AS JSON));
INSERT INTO t1(f1) VALUES(CAST('["abc "]' AS JSON));
SELECT * FROM t1 WHERE "abc " MEMBER OF (f1->"$[*]");
```

### 2. What did you expect to see? (Required)

`abc `

### 3. What did you see instead (Required)

nothing

**Comment by qw4990** [comment]
The root cause is the underlying vir-col's charset and collation are not set to `binary`.
