### ISSUE TITLE
Support late materialization

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tidb#40601]
## Feature Request

**Is your feature request related to a problem? Please describe:**

For some query like `select * from t where a == 0`;, we now scan all columns and then do filter, which is heavy and we can do better.

**Describe the feature you'd like:**

Support late materialization. We can scan column(s) at first to filter out unnecessary data segment, and then just scan the rest columns and only read necessary rows.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by jim-tommaney** [comment]
An example where late materialization is highly useful for OLTP based loads:
` select * from T where <many_filters> order by <order_columns> limit 1000, 10;`

A late materialization plan which projects * only after reducing the rowids to 10 values will avoid performance degradation with:
1. arbitrarily deep offsets 
2. wide tables
3. non-covering indexes where either the filter or the order by includes columns not within any suitable index.
4. Selective filters - when filters eliminate most rows, late materialization will be faster

**Comment by Lloyd-Pottiger** [comment]
@jim-tommaney Yes, you are right. Push down topn operator can help improve the performance in some scenario. And we have plans to implement this https://github.com/pingcap/tiflash/issues/5829#issuecomment-1414851249 for TiFlash (TiDB columnar storage). 

But I am not sure how this would work in TiKV workloads? Could you please give a detail explaination? Much thanks!
