### ISSUE TITLE
Insert value with prefix date should not failed

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#4062]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
create table t1(
    a1 char(3) primary key,
    a2 smallint, 
    a3 char(3),
    a4 real,   
    a5 date
);
insert into t1 values('AME',0,'SEA',0.100,date'1942-02-19');
```

2. What did you expect to see?

```
Query OK, 1 row affected (0.00 sec)
```

3. What did you see instead?

```
ERROR 1105 (HY000) at line 8: line 0 column 58 near ")" (total length 59)
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
Duplicate https://github.com/pingcap/tidb/issues/3909
