### ISSUE TITLE
Fine grained privilege to RECOVER TABLE

### ISSUE THREAD

**Issue by plevart** [pingcap/tidb#40633]
## Feature Request

**Is your feature request related to a problem? Please describe:**
A user has CREATE and DROP privilege for tables in a particular schema (ON schema.*). He accidentally dropped a table. He wanted to RECOVER the table, but he didn't have SUPER privilege. Before he was able to contact DBA with SUPER privilege, the GC life time was over and DBA couldn't RECOVER the table either.

**Describe the feature you'd like:**
If a user has CREATE and DROP privilege for a particular table, (s)he could also be allowed to RECOVER that table. Or perhaps there could be a RECOVER privilege that would be bound to tables (like CREATE and DROP) so that it could be granted to users like CREATE and DROP privileges.

**Describe alternatives you've considered:**
Increase GC life time to 4 days or more which is max. expected time before DBA can be contacted and still have enough time to act. This could affect query performance though.

**Comment by dveeden** [comment]
And `FLASHBACK TABLE` should probably use the same permissions.

**Comment by Defined2014** [comment]
And aslo for [FLASHBACK DATABASE](https://docs.pingcap.com/tidb/stable/sql-statement-flashback-database)
