### ISSUE TITLE
a DELETE statement using 'EXISTS' or 'IN' keyword, wrong records deleted

### ISSUE THREAD

**Issue by EthanLauAL** [pingcap/tidb#4067]
What did you do?
---
If possible, provide a recipe for reproducing the error.

```
SELECT id FROM t1;

id
---
123

SELECT id FROM t2;

id
---
123

SELECT id FROM t1
WHERE id IN (SELECT id FROM t2);

id
---
123

-- the statement should delete the record 123, but does not
DELETE FROM t1
WHERE id IN (SELECT id FROM t2);

-- should not delete the record, but the record gone
DELETE FROM t1
WHERE id NOT IN (SELECT id FROM t2);
```

I still can not reproduce the error, the error only happens in some of my tables.

What version of TiDB are you using (`tidb-server -V`)?
---

```
> $ ./tidb-server -V                                                                                                    
Git Commit Hash: bae8fe46f9305cdfff52cf18d5701ae7ead14d75
UTC Build Time:  2017-08-06 01:02:35


> $ ./tikv-server -V
TiKV 0.0.1
Git Commit Hash: c2d36f5b081339b24064c9630e876fcd8429746f
UTC Build Time:  2017-08-06 01:52:37
Rust Version:    1.19.0-nightly (d47cf08d5 2017-05-28)

> $ ./pd-server -V
Git Commit Hash: 30115ae539e7e175e988b8c70b630f0908d7a77b
UTC Build Time:  2017-08-04 12:16:13
```

The error occurs after we update to RC4.
Only DELETE statement, SELECT and UPDATE are fine.
The problem cause important data lost.

**Comment by shenli** [comment]
@EthanLauAL Thanks for your feedback!
@winoros PTAL

**Comment by winoros** [comment]
@EthanLauAL hello, can you have a try using the current master? There seems to be no bug if using current master.

**Comment by EthanLauAL** [comment]
There seems to be no bug even I test on another table, the error only occurs in certain tables, I'm still working on how to reproduce it.

**Comment by shenli** [comment]
@EthanLauAL We have found the problem and it will be fix soon. Hope we can finish it today.

**Comment by EthanLauAL** [comment]
OK, I think I got it.

```
CREATE TABLE t1 (
id VARCHAR(32) NOT NULL,
PRIMARY KEY(id) );

INSERT INTO t1 VALUES('hello tidb');

CREATE TABLE t2 (
id VARCHAR(32) NOT NULL,
PRIMARY KEY(id) );

INSERT INTO t1 VALUES('hello tidb');

-- still fine
SELECT * FROM t1
WHERE id IN (SELECT id FROM t2);

-- things go wrong from here, 'hello tidb' not deleted as expected
DELETE FROM t1
WHERE id IN (SELECT id FROM t2);

-- disaster, data lost
DELETE FROM t1
WHERE NOT id IN (SELECT id FROM t2);

```

1. DELETE statement with 'EXISTS' or 'IN' keywords on primary key
2. primary key's type is VARCHAR

**Comment by winoros** [comment]
@EthanLauAL the master branch now has solved this problem and you may have a try. We will merge it to rc4 branch soon.
If there's any problem, you can reopen this issue.
