### ISSUE TITLE
avoid excessive PointGet request to a single tikv node for stale read when DDL happens

### ISSUE THREAD

**Issue by hihihuhu** [pingcap/tidb#40740]
## Enhancement

currently, to avoid to get the schema version for a `snapshotTs`, the `snapshotTs` of the stale read needs to be greater than the update timestamp of the current schema version. https://github.com/pingcap/tidb/blob/master/infoschema/cache.go#L111

this behavior causes significant load issue on the single tikv node stores the schema version when DDL happens. usually the stale read will request the data from a few second up to minutes before current timestamp. this mean, when DDL happens with `maxUpdatedSnapshotTS  = t0`, all of the stale read requests happens from `t0` to `t0 + t_staleness` will query the data of `snapshotTs` before `t0`, thus requires to get the schema version at that `snapshotTs`.

one solution i could think of is to change the change the schema version request from `GetRequest` to `VerGetRequest` to obtain the corresponding timestamp for each schema version change. in this way, tidb could maintain a local map of the schema version and its commit timestamp, so that it could completely avoid the point get request for schema version on stale read code path.

**Comment by xhebox** [comment]
I think we could just maintain a list of infoschemas sorted by snapshotTS. In fact, this list should be identical to the list of schemas sorted by schema version. Check the following function:

https://github.com/pingcap/tidb/blob/master/infoschema/cache.go#L132-L134

All schemas loaded into cache have corresponding TS. Only the maximum TS is maintained. I've suggested to maintain a map of TS/version, but it is not accepted and done in https://github.com/pingcap/tidb/pull/25322#issuecomment-858362388 .

I guess you could modify the cache into `cache []struct{infoshema, snapshotTS}` to target the problem.

**Comment by hihihuhu** [comment]
yes, i think use something like the `maxUpdatedSnapshotTS` as an approximation could be fine, though it is not as precise as the the exact version, it is probably good enough in practice.

if this is a good idea, i could draft a pr, wdyt @xhebox ?

**Comment by xhebox** [comment]
> yes, i think use something like the `maxUpdatedSnapshotTS` as an approximation could be fine, though it is not as precise as the the exact version, it is probably good enough in practice.
> 
> if this is a good idea, i could draft a pr, wdyt @xhebox ?

Of course.

**Comment by tonyxuqqi** [comment]
The ideal sounds reasonable to me.

**Comment by xhebox** [comment]
The implementation is problematic that the insertion TS is not accurate enough. Thus we will get errors if:

```
ver2       |      ver1
ts1|   ts2 | ts3
```

Think a cache like this, when we inserted `ver2` with `ts1`, and `ver1` with `ts3`. Get by ts2 will load `ver1`, while it should be `ver2`.

**Comment by hihihuhu** [comment]
yes, though this is same behavior as leader read, when the new schema is not loaded, it will still use old schema cache? @xhebox

**Comment by hihihuhu** [comment]
if we want this to be accurate, i think we could as the original issue says, use `VerGetRequest` to read the timestamp of the schema version from tikv and use it

**Comment by xhebox** [comment]
> yes, though this is same behavior as leader read, when the new schema is not loaded, it will still use old schema cache? @xhebox 

Or worse, when new schema loaded with an inaccurate cache ts, it messed some callers expecting accurate results.

**Comment by xhebox** [comment]
> if we want this to be accurate, i think we could do as the original description says, use `VerGetRequest` to read the timestamp of the schema version from tikv and use it

Probably yes, we need the absolute value to be correct.

**Comment by hihihuhu** [comment]
@xhebox could we agree on the approach to fix this? if so, i could put another fix

**Comment by hihihuhu** [comment]
just found `VerGetRequest` was removed, then it needs to store a schema version to timestamp mapping, then fetch it when read a new schema version

**Comment by xhebox** [comment]
> just found `VerGetRequest` was removed, then it needs to store a schema version to timestamp mapping, then fetch it when read a new schema version

Yep, we need mvcc to tell commitTS.

> one could argue it is similar, like says, a ddl happens with timestamp ts1, and tidb loads the schema at ts2, where ts2 > ts1, then for all the leader read in that tidb process between ts1 and ts2 will still use the old schema. and for stale read, it is same behavior.

I know. It is sometime accepted to lag for one version. But some API(I mean history read) expect accurate `GetSchemaBySnapshot`, it is not a stale read.

> i am not trying to say it is acceptable, but in some sense, it is consistent. that is why i said

Yeah, that is the problem. Either we need to do it accurately, or we need to treat stale read and history read differently, which seems weird for me.

> could we agree on the approach to fix this? if so, i could put another fix, thanks!

I agree that we can fix it by accurate TS. Just, I am actually oncalling these weeks. Feel free if you have any plan, as long as it is accurate.

**Comment by hihihuhu** [comment]
thanks for the reply, i will try to put another fix shortly, though may need 1-2 weeks
