### ISSUE TITLE
ddl: need cancel job，after met DropTableOrView error

### ISSUE THREAD

**Issue by ystaticy** [pingcap/tidb#40783]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

If the create and replace view ddl job in is interrupted after drop view , we may encounter table doesn't exist(In fact, the old view has been dropped ) in DropTableOrView when we restart tidb and the rerun the job by old view info.

### 2. What did you expect to see? (Required)
If the view was dropped in old ddl process, it need to be cancelled.

### 3. What did you see instead (Required)
The ddl job restart in a new ddl job, but it always try again with the old view id.

### 4. What is your TiDB version? (Required)

when 6.2 upgrade to 6.4

**Comment by Defined2014** [comment]
Fixed by https://github.com/pingcap/tidb/pull/40353, close this issue.
