### ISSUE TITLE
Blocked `alter table <table name> change` statement  does not appear at `mysql.tidb_mdl_view`

### ISSUE THREAD

**Issue by yahonda** [pingcap/tidb#40838]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Open a TiDB Connection and create t1 table
```sql
mysql -h $TIDB_SERVER1 -P 4000 -u root test
CREATE TABLE t1 (id int not null primary key AUTO_INCREMENT, col1 INT);
```
2. Open another TiDB connection and begin transaction to insert into t1
```sql
begin;
INSERT INTO t1 (col1) VALUES (1),(2),(3),(4),(5);
```
3. Keep the transaction open. Do not commit or rollback
4. Open another TiDB connection and execute `ALTER TABLE t1` to see how metadata lock works

```sql
mysql -h $TIDB_SERVER1 -P 4000 -u root test
ALTER TABLE t1 CHANGE col1 col2 INT;
```

### 2. What did you expect to see? (Required)
`ALTER TABLE t1 CHANGE col1 col2 INT;` is blocked and `mysql.tidb_mdl_view` shows blocked DDL.

### 3. What did you see instead (Required)
`ALTER TABLE t1 CHANGE col1 col2 INT;` is blocked , however no `mysql.tidb_mdl_view` rows returned.

```sql
MySQL [test]> SELECT * FROM mysql.tidb_mdl_view\G
Empty set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

```sql
MySQL [(none)]> SELECT tidb_version() \G
*************************** 1. row ***************************
tidb_version(): Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.00 sec)

MySQL [(none)]>
```

**Comment by YangKeao** [comment]
The root cause is that this job state is `done`, so it will not be shown in the `tidb_mdl_view`: this view is created with:

```
CREATE OR REPLACE VIEW mysql.tidb_mdl_view as (
	select JOB_ID, DB_NAME, TABLE_NAME, QUERY, SESSION_ID, TxnStart, TIDB_DECODE_SQL_DIGESTS(ALL_SQL_DIGESTS, 4096) AS SQL_DIGESTS from information_schema.ddl_jobs, information_schema.CLUSTER_TIDB_TRX, information_schema.CLUSTER_PROCESSLIST where ddl_jobs.STATE = 'running' and find_in_set(ddl_jobs.table_id, CLUSTER_TIDB_TRX.RELATED_TABLE_IDS) and CLUSTER_TIDB_TRX.SESSION_ID=CLUSTER_PROCESSLIST.ID);
```

However, even the job is `done`, it's needed to be blocked, because we need to forbid executing the next ddl statement :thinking: .
