### ISSUE TITLE
tidb cpu 100% caused by ResourceGroupsController.mainLoop

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#40876]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run the master tidb

### 2. What did you expect to see? (Required)

When there is no workload, the CPU usage is low

### 3. What did you see instead (Required)

![image](https://user-images.githubusercontent.com/1420062/215642431-abdbae12-bf25-4bbd-a468-f1b8bb03329d.png)

### 4. What is your TiDB version? (Required)

master

**Comment by tiancaiamao** [comment]
![image](https://user-images.githubusercontent.com/1420062/215642626-ab6e2849-20e8-4b2c-a670-01dfea646ce7.png)

Introduced here https://github.com/pingcap/tidb/blob/ee758bcf8b68ad52ce46cfe9d42647f71614ee26/store/driver/tikv_driver.go#L110

And here is the bug
https://github.com/tikv/pd/blob/62a7452b131857329732bd18e2dc7dc4cd0db05e/pkg/mcs/resource_manager/client/client.go#L281-L310

```
	for {
		select {
		case <-...:
                         ...
		default:
			...
		}
	}
```

**Comment by Yui-Song** [comment]
This issue causes performance regression in the following workloads:
oltp_read_only,oltp_point_select,select_random_points,select_random_ranges,taobench,bank,ycsb-workloada
![image](https://user-images.githubusercontent.com/84501897/215693163-3a7859dd-1c66-4196-9e77-c07c896c2f81.png)

**Comment by YangKeao** [comment]
Fixed by https://github.com/tikv/pd/pull/5891
