### ISSUE TITLE
Mpp maybe take up a lot of memory when SendRequest

### ISSUE THREAD

**Issue by wshwsh12** [pingcap/tidb#40926]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Insert some data.
```
drop table `sli-gauge-metric`;
CREATE TABLE `sli-gauge-metric` (
  `timestamp` bigint(20) NOT NULL,
  `instance` varchar(128) NOT NULL,
  `cluster_id` varchar(128) NOT NULL,
  `metrics` json DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```
insert 65536 rows, contains 10000 bytes json text in each row.

2. Set tiflase replica and wait sync.
3. Run sql ``desc analyze  select * from `sli-gauge-metric`  order by cluster_id;``
4. Use go profile to generate heap graph.

### 2. What did you expect to see? (Required)

Profile heap only contains the memory of MPP or Sort Executor.

### 3. What did you see instead (Required)

There are many memory usage in client-go GetRegionError() when recving the **FIRST** MPPPacket
![image](https://user-images.githubusercontent.com/14054293/215957386-f84f2fab-517b-485c-a961-bc06704b795b.png)

Related code:
https://github.com/tikv/client-go/blob/35416c4c4373bb0ee85e0feef38af777d7b63f4b/tikvrpc/tikvrpc.go#L960

### 4. What is your TiDB version? (Required)
master

**Comment by windtalker** [comment]
already fixed by https://github.com/tikv/client-go/pull/1108 in v8.1
