### ISSUE TITLE
lightning: data inconsistency after lighting parallel import single table with duplicate

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#40923]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. use two lightning nodes to parallelly import single table with duplicate rows and million data
2. check duplicate rows

import1: {"data-dir":"s3://nfs/tools_test_data/parallel/single_table_with_1m_dup/single_table_3g_2?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9001&force-path-style=true","backend":"local","sorted-kv-dir":"/tmp/sorted-kv-dir", "timeout":"10m","crc32-checksum":0, "config": "[tikv-importer]\nduplicate-resolution = \"remove\"\nincremental-import = true", "transfer-to-config": true}
import2: {"data-dir":"s3://nfs/tools_test_data/parallel/single_table_with_1m_dup/single_table_3g_1?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9001&force-path-style=true","backend":"local","sorted-kv-dir":"/tmp/sorted-kv-dir", "timeout":"10m","crc32-checksum":0, "config": "[tikv-importer]\nduplicate-resolution = \"remove\"\nincremental-import = true", "transfer-to-config": true}

admin check : [{"table": "IFRS9.ECL_RETAIL_LOAN_BIZ_INFO", "indexes":[]}]
duplicate_rows: 4540384

### 2. What did you expect to see? (Required)
import success

### 3. What did you see instead (Required)
[2023/01/31 19:36:24.821 +00:00] [ERROR] [admin_check.go:54] ["admin check error"] [error="Error 8223: data inconsis
tency in table: ECL_RETAIL_LOAN_BIZ_INFO, index: PRIMARY, handle: 53687489, index-values:\"handle: 28823037615171177
43, values: [KindMysqlTime 2028-04-15 KindString 73620807 KindString OwD]\" != record-values:\"handle: 53687489, val
ues: [KindMysqlTime 2028-04-15 KindString 73620807 KindString OwD]\""] [stack="github.com/pingcap/test-infra/caselib
/pkg/steps.adminCheckStep.Execute\n\t/root/go/src/test-infra/caselib/pkg/steps/admin_check.go:54\ngithub.com/pingcap
/test-infra/caselib/pkg/steps.(*Serial).Execute\n\t/root/go/src/test-infra/caselib/pkg/steps/step.go:31\nmain.main\n
\t/root/go/src/test-infra/caselib/case/lightning/parallelImportDuplicate/main.go:54\nruntime.main\n\t/usr/local/go/s
rc/runtime/proc.go:225"]
2023-01-31T19:36:24.827Z        FATAL   parallelImportDuplicate/main.go:55      ImportParallelWithDuplicate failed {
"error": "Error 8223: data inconsistency in table: ECL_RETAIL_LOAN_BIZ_INFO, index: PRIMARY, handle: 53687489, index
-values:\"handle: 2882303761517117743, values: [KindMysqlTime 2028-04-15 KindString 73620807 KindString OwD]\" != re
cord-values:\"handle: 53687489, values: [KindMysqlTime 2028-04-15 KindString 73620807 KindString OwD]\"", "errorVerb
ose": "Error 8223: data inconsistency in table: ECL_RETAIL_LOAN_BIZ_INFO, index: PRIMARY, handle: 53687489, index-va
lues:\"handle: 2882303761517117743, values: [KindMysqlTime 2028-04-15 KindString 73620807 KindString OwD]\" != recor
d-values:\"handle: 53687489, values: [KindMysqlTime 2028-04-15 KindString 73620807 KindString OwD]\"\ngithub.com/pin
gcap/errors.AddStack\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226aaa3/errors.go:1
74\ngithub.com/pingcap/errors.Trace\n\t/root/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20211009033009-93128226a
aa3/juju_adaptor.go:15\ngithub.com/pingcap/test-infra/caselib/pkg/steps.adminCheckStep.Execute\n\t/root/go/src/test-
infra/caselib/pkg/steps/admin_check.go:55\ngithub.com/pingcap/test-infra/caselib/pkg/steps.(*Serial).Execute\n\t/roo
t/go/src/test-infra/caselib/pkg/steps/step.go:31\nmain.main\n\t/root/go/src/test-infra/caselib/case/lightning/parall
elImportDuplicate/main.go:54\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:225\nruntime.goexit\n\t/usr/local/go
/src/runtime/asm_amd64.s:1371"}
### 4. What is your TiDB version? (Required)

[2023/01/31 16:23:15.702 +00:00] [INFO] [printer.go:34] ["Welcome to TiDB."] ["Release Version"=v6.6.0-alpha] [Edition=Community] ["Git Commit Hash"=920f0199c100bb38b36760e89e55dee20e6fdcd6] ["Git Branch"=heads/refs/tags/v6.6.0-alpha] ["UTC Build Time"="2023-01-31 11:49:14"] [GoVersion=go1.19.5] ["Race Enabled"=false] ["Check Table Before Drop"=false] ["TiKV Min Version"=6.2.0-alpha]

**Comment by seiya-annie** [comment]
[lightning.log.2023-01-31T19.31.04Z.gz](https://github.com/pingcap/tidb/files/10554415/lightning.log.2023-01-31T19.31.04Z.gz)
[lightning.log.2023-01-31T19.31.05Z.gz](https://github.com/pingcap/tidb/files/10554416/lightning.log.2023-01-31T19.31.05Z.gz)

**Comment by lichunzhu** [comment]
## Root Cause
Lightning 1: has local duplicate data, save hasDuplicate info into db, exit and let the other lightning to resolve conflict.
Lightning 2: local data are not dupe, remote data are not dupe, https://github.com/pingcap/tidb/blob/79a5d3b3e3cea7af0bf2165066503c61e74852a7/br/pkg/lightning/restore/table_restore.go#L813, Lightning will skip ResolveDuplicateRows.
## Fix
Improve logic to make sure lightning will ResolveDuplicateRows when other lightning has local dupe.
