### ISSUE TITLE
global index: drop global index or drop table but not delete global index range

### ISSUE THREAD

**Issue by L-maple** [pingcap/tidb#40953]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
I find the bug by debugging. I haven't find a way to show deleted regions correctly, because delete index is async.
when ddl is in onDropIndex reorg state, delete global index means partitionIDs should be nil, like the following. Otherwise, the logic would try to delete partitions' 

### 2. What did you expect to see? (Required)
dropping global index / drop table, but not delete global index range.

### 3. What did you see instead (Required)
dropping global index delete table partitions' index.

### 4. What is your TiDB version? (Required)
master

| Release Version: v6.6.0-alpha-290-g6676ca816-dirty
Edition: Community
Git Commit Hash: 6676ca8160c3681d0536482c5f8042ff82556b5f
Git Branch: local/fix_drop_global_index_master
UTC Build Time: 2023-02-01 09:01:32
GoVersion: go1.19.4
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore |

**Comment by L-maple** [comment]
cc @mjonss @tiancaiamao

**Comment by Defined2014** [comment]
Hi @L-maple, is this issue fixed? If the answer is yes, maybe we could close it.

**Comment by L-maple** [comment]
@Defined2014  Yes, the issue can be closed~ /close
