### ISSUE TITLE
br restore doesn't have `--concurrency` option 

### ISSUE THREAD

**Issue by zhaoxinyu** [pingcap/tidb#41084]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
As mentioned in [performance tuning](https://docs.pingcap.com/tidb/dev/sql-statement-restore#performance-fine-tuning), `RESTORE` SQL command has a CONCURRENCY parameter that defaults to 128, while this parameter is not seen in `br restore full` command.

### 2. What did you expect to see? (Required)
`--concurrency` is not hidden in `br restore` command.

### 3. What did you see instead (Required)
`--concurrency` is hidden. Ref:
https://github.com/pingcap/tidb/blob/ddaf0d7814fe5fe5b1aca0695ec34b3bfa9c6650/br/pkg/task/common.go#L258-L260

### 4. What is your TiDB version? (Required)
v6.5.0

**Comment by 3pointer** [comment]
see the discussion https://github.com/pingcap/tidb/pull/30085#discussion_r771129531

**Comment by joccau** [comment]
Fixed by https://github.com/pingcap/tidb/pull/30085
