### ISSUE TITLE
unexpected value for `COLUMN_DEFAULT` in `information_schema.COLUMNS`

### ISSUE THREAD

**Issue by corgiboygsj** [pingcap/tidb#41089]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I can't see the expected result using the following statement.
SQL: select * from  information_schema.COLUMNS WHERE TABLE_SCHEMA='dbcat_test' AND TABLE_NAME='TEST' \G;

I created a table using the following statement.
**DDL:** CREATE TABLE TEST (is_existed bit(1) default b'1');

### 2. What did you expect to see? (Required)

same dll in mysql5.7
![image](https://user-images.githubusercontent.com/24729637/216910983-df5a7a37-200b-471e-b759-a5aefcbf6cdc.png)

### 3. What did you see instead (Required)

![image](https://user-images.githubusercontent.com/24729637/216910742-1a3cb8af-fe1b-49d6-9b3b-237d6e95c8ab.png)

### 4. What is your TiDB version? (Required)

v5.4.1

**Comment by corgiboygsj** [comment]
Is there any way to deal with it temporarily?

**Comment by hawkingrei** [comment]
I think it is a easy way to upgrade the tidb. It has been fixed in the higher tidb.

**Comment by hawkingrei** [comment]
You can try [tidb-server v5.4.3](https://github.com/pingcap/tidb/releases/tag/v5.4.3)
