### ISSUE TITLE
fatal error `table already exists` after upgrade

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#41131]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. upgrade tidb from master to master

### 2. What did you expect to see? (Required)
1. no error 
### 3. What did you see instead (Required)
{"level":"FATAL","container":"tidb","pod":"maincluster-tidb-5","log":"[terror.go:300] [\"unexpected error\"] [error=\"[meta:1050]table already exists\"] [stack=\"[github.com/pingcap/tidb/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:236\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250](http://github.com/pingcap/tidb/parser/terror.MustNil//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300//nmain.createStoreAndDomain//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347//nmain.main//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:236//nruntime.main//n//t/usr/local/go/src/runtime/proc.go:250)\"] [stack=\"[github.com/pingcap/tidb/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:236\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250](http://github.com/pingcap/tidb/parser/terror.MustNil//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:300//nmain.createStoreAndDomain//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:347//nmain.main//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:236//nruntime.main//n//t/usr/local/go/src/runtime/proc.go:250)\"]","namespace":"xxxxxx"}
### 4. What is your TiDB version? (Required)
origin:
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: b5be9f6db297b7990bc94c6de91309dbc263ed87
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-01-29 11:49:43
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

target:
Release Version: v6.6.0-alpha
Edition: Community
Git Commit Hash: c017999d023db1357a3ee3faf8d57d6a43456ea5
Git Branch: heads/refs/tags/v6.6.0-alpha
UTC Build Time: 2023-02-06 11:51:08
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by Defined2014** [comment]
See details from https://github.com/pingcap/tidb/issues/41104.
