### ISSUE TITLE
Shared connection to host closed

### ISSUE THREAD

**Issue by smj227227** [pingcap/tidb#4114]
PLAY [monitored_servers] ***************************************************************************************************************************

TASK [restart node_exporter] ***********************************************************************************************************************
changed: [192.168.0.3] => (item=node_exporter)
changed: [192.168.0.1] => (item=node_exporter)
changed: [192.168.0.2] => (item=node_exporter)

TASK [wait up] *************************************************************************************************************************************
ok: [192.168.0.3]
ok: [192.168.0.1]
ok: [192.168.0.2]

PLAY [monitoring_servers] **************************************************************************************************************************

TASK [restart monitoring modules] ******************************************************************************************************************
changed: [192.168.0.3] => (item=pushgateway)
changed: [192.168.0.3] => (item=prometheus)

TASK [wait pushgateway up] *************************************************************************************************************************
ok: [192.168.0.3]

TASK [wait prometheus up] **************************************************************************************************************************
ok: [192.168.0.3]

PLAY [pd_servers] **********************************************************************************************************************************

TASK [restart PD] **********************************************************************************************************************************
changed: [192.168.0.3] => (item=pd)
changed: [192.168.0.1] => (item=pd)
changed: [192.168.0.2] => (item=pd)

TASK [wait up] *************************************************************************************************************************************
fatal: [192.168.0.3]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.0.3 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n File "/tmp/ansible_3FWk3S/ansible_module_wait_for.py", line 579, in \r\n main()\r\n File "/tmp/ansible_3FWk3S/ansible_module_wait_for.py", line 519, in main\r\n response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 0}

ulimit set 100000

**Comment by shenli** [comment]
@smj227227 Thanks for your report!
@LinuxGit PTAL

**Comment by LinuxGit** [comment]
Hi,  run `ansible bootstrap.yml` will set ulimit to 1000000 for you in /etc/security/limits.conf.  And Ansible default ssh_args parameter is "-o ControlMaster=auto -o ControlPersist=60s". We've killed close old control master before running plays to let ulimit works. If it doesn't work, you can wait a minute and try again. You can new issues in https://github.com/pingcap/tidb-ansible if you encounter any deployment problems.

**Comment by smj227227** [comment]
@LinuxGit  TIDB 正常运行一周后报告了这个问题，在正常运行前，已经依次运行了ansible-playbook local_prepare.yml ansible-playbook bootstrap.yml ansible-playbook deploy.yml -k等命令，但在运行一周后突然发生这样的问题，实在是难以理解

**Comment by smj227227** [comment]
@LinuxGit TASK [wait up] ************************************************************************************************************************************************************************************************************************************************************
ok: [192.168.0.1]
ok: [192.168.0.2]
**fatal: [192.168.0.3]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Shared connection to 192.168.0.3 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_udCgrj/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_udCgrj/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 0}**

PLAY [tikv_servers] *******************************************************************************************************************************************************************************************************************************************************

TASK [restart TiKV] *******************************************************************************************************************************************************************************************************************************************************
changed: [192.168.0.2] => (item=tikv)
changed: [192.168.0.1] => (item=tikv)

TASK [wait up] ************************************************************************************************************************************************************************************************************************************************************
ok: [192.168.0.1]
ok: [192.168.0.2]

PLAY [tidb_servers] *******************************************************************************************************************************************************************************************************************************************************

PLAY [grafana_servers] ****************************************************************************************************************************************************************************************************************************************************
	to retry, use: --limit @retry_files/start.retry

PLAY RECAP ****************************************************************************************************************************************************************************************************************************************************************
192.168.0.1                : ok=20   changed=3    unreachable=0    failed=0   
192.168.0.2                : ok=20   changed=3    unreachable=0    failed=0   
192.168.0.3                : ok=20   changed=3    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

[tidb@localhost tidb]$ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63010
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1000000
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 10240
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
