### ISSUE TITLE
pitr task hang when "[ddl] closing workerPool"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#41218]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

stop a inexist pitr task

### 2. What did you expect to see? (Required)
report task not found

### 3. What did you see instead (Required)
hang when closing workerPool
### 4. What is your TiDB version? (Required)

[2023/02/09 04:01:14.098 +00:00] [INFO] [info.go:49] ["Welcome to Backup & Restore (BR)"] [release-version=v6.6.0-alpha] [git-hash=93c6492418ae1bfa91479b8b465e61c78f29a995] [git-branch=heads/refs/tags/v6.6.0-alpha] [go-version=go1.19.5] [utc-build-time="2023-02-08 11:42:03"] [race-enabled=false]

**Comment by seiya-annie** [comment]
[br-pitr-hang.log](https://github.com/pingcap/tidb/files/10693457/br-pitr-hang.log)

**Comment by seiya-annie** [comment]
start pitr also blocked here

**Comment by YuJuncen** [comment]
Probably duplicated with https://github.com/pingcap/tidb/issues/41205. Close it for now, if anything new found, fell free to reopen it.

**Comment by YuJuncen** [comment]
As a workaround, if your BR get stuck in single core processors, please run br with `GOMAXPROCS=8` (Or any number greater than `1` you like).
