### ISSUE TITLE
create pitr task fail during doing flashback ddl

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#41234]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

br can only read data which backupts early than flashback execute time

### 2. What did you expect to see? (Required)
during flashback, can do start pitr task 

### 3. What did you see instead (Required)
[error=\"region 656 is in flashback progress, FlashbackStartTS is 43933607850619701
1\"] [errorVerbose=\"region 656 is in flashback progress, FlashbackStartTS is 439336078506197011\\ngithub.com/tikv/c
lient-go/v2/internal/locate.(*RegionRequestSender).onRegionError\\n\
### 4. What is your TiDB version? (Required)

master

**Comment by Defined2014** [comment]
I think it's by design. If you have need backup data during `flashback`, please use `br backup full` with `--backupts` param. And the value of `--backupts` should be earlier than the time when `flashback` ddl operation starts to execute.

**Comment by bb7133** [comment]
@Defined2014 Can we close this issue & update the user document?

**Comment by Defined2014** [comment]
> @Defined2014 Can we close this issue & update the user document?

https://github.com/pingcap/docs-cn/pull/13078 PTAL @bb7133
