### ISSUE TITLE
bug in printing float

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#4128]
select 1.797693134862315708145274237317043567981e+308 * 1

mysql is 1.7976931348623157e308
TiDB is 179769313486231570000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

**Comment by breeswish** [comment]
may be duplicate https://github.com/pingcap/tidb/issues/3709
