### ISSUE TITLE
`information_schema.cluster_log` cannot show tikv log

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#41309]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
`select count(*) from information_schema.cluster_log where time>'2023-02-11 23:59:00' and time<'2023-02-11 23:59:59' and type='tikv';`

### 2. What did you expect to see? (Required)
tikv logs 
### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/50363732/218272429-4c989ba2-bbcb-4bf9-8092-babc5d6128cc.png)

### 4. What is your TiDB version? (Required)
6.6

**Comment by xhebox** [comment]
Closed. Due to some misconfiguration of tikv `[log.log-file.filrname]`
