### ISSUE TITLE
first time show variables too slow.

### ISSUE THREAD

**Issue by xinbo** [pingcap/tidb#4135]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

mysql> SHOW VARIABLES LIKE 'datadir';
+---------------+------------------------+
| Variable_name | Value                  |
+---------------+------------------------+
| datadir       | /usr/local/mysql/data/ |
+---------------+------------------------+
1 row in set (2.81 sec)

mysql> SHOW VARIABLES LIKE 'datadir';
+---------------+------------------------+
| Variable_name | Value                  |
+---------------+------------------------+
| datadir       | /usr/local/mysql/data/ |
+---------------+------------------------+
1 row in set (0.00 sec)

first time call show variables like is too slow.

2. What did you expect to see?
how to improve it?

**Comment by tiancaiamao** [comment]
When the first time you execute ` SHOW VARIABLES LIKE 'datadir';`, TiDB need to load global variables from storage.
After that, those variables is cached in memory and not need to load again, so it's faster.

**Comment by xinbo** [comment]
some framework like python sqlalchemy use show variables like 'sqlmode' when connect to mysql db.
it's so sadly

**Comment by shenli** [comment]
@xinbo The speed depends on your hardware. Could you show me the detailed information of your machine?

**Comment by xinbo** [comment]
aliyun ecs.n1.7xlarge * 6,  32 cores, 64G RAM, 700G SSD @shenli

**Comment by wwar** [comment]
I believe this has been fixed / the variables list is cached.
