### ISSUE TITLE
The update field of the information_schema.tables view will not be automatically updated after ddl changes

### ISSUE THREAD

**Issue by xiaobingMo** [pingcap/tidb#41363]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

mysql> create table t(id bigint(5),name char(10));
Query OK, 0 rows affected (0.08 sec)

mysql> select TABLE_NAME,CREATE_TIME,UPDATE_TIME,CHECK_TIME,TIDB_TABLE_ID from information_schema.tables where table_name='t';
+------------+---------------------+-------------+------------+---------------+
| TABLE_NAME | CREATE_TIME         | UPDATE_TIME | CHECK_TIME | TIDB_TABLE_ID |
+------------+---------------------+-------------+------------+---------------+
| t          | 2023-02-14 10:36:53 | NULL        | NULL       |            69 |
+------------+---------------------+-------------+------------+---------------+
1 row in set (0.01 sec)

mysql> alter table t add column sno int(10);
Query OK, 0 rows affected (0.25 sec)

mysql> select TABLE_NAME,CREATE_TIME,UPDATE_TIME,CHECK_TIME,TIDB_TABLE_ID from information_schema.tables where table_name='t';
+------------+---------------------+-------------+------------+---------------+
| TABLE_NAME | CREATE_TIME         | UPDATE_TIME | CHECK_TIME | TIDB_TABLE_ID |
+------------+---------------------+-------------+------------+---------------+
| t          | 2023-02-14 10:38:37 | NULL        | NULL       |            69 |
+------------+---------------------+-------------+------------+---------------+
1 row in set (0.01 sec)

### 2. What did you expect to see? (Required)
UPDATE_TIME = 2023-02-14 10:38:37

### 3. What did you see instead (Required)
UPDATE_TIME field is null

### 4. What is your TiDB version? (Required)
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.1.4
Edition: Community
Git Commit Hash: ac6560f9b7239f0ed3f8c39482b79b48a6263de1
Git Branch: heads/refs/tags/v6.1.4
UTC Build Time: 2023-01-31 10:22:40
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by zimulala** [comment]
Duplicated https://github.com/pingcap/tidb/issues/5551.
