### ISSUE TITLE
panic: Out Of Memory Quota!

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#41476]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
panic: Out Of Memory Quota![conn_id=3971954969015222677]

goroutine 2161 [running]:
[github.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action](http://github.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action)(0xc78c02ba00, 0xc001246c80)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/util/memory/action.go:148](http://github.com/pingcap/tidb/util/memory/action.go:148) +0x11f
[github.com/pingcap/tidb/util/memory.(*Tracker).Consume.func2](http://github.com/pingcap/tidb/util/memory.(*Tracker).Consume.func2)(0x45440c0?, 0xc0002b5980?)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/util/memory/tracker.go:449](http://github.com/pingcap/tidb/util/memory/tracker.go:449) +0xff
[github.com/pingcap/tidb/util/memory.(*Tracker).Consume](http://github.com/pingcap/tidb/util/memory.(*Tracker).Consume)(0xc2087b3620?, 0x1000)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/util/memory/tracker.go:461](http://github.com/pingcap/tidb/util/memory/tracker.go:461) +0x2c2
[github.com/pingcap/tidb/util/memory.(*Tracker).ReplaceBytesUsed](http://github.com/pingcap/tidb/util/memory.(*Tracker).ReplaceBytesUsed)(0xc778af1540, 0xc0b4be5ef0?)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/util/memory/tracker.go:743](http://github.com/pingcap/tidb/util/memory/tracker.go:743) +0x3c
[github.com/pingcap/tidb/session.(*session).SetMemoryFootprintChangeHook.func1(0xc42b905388?)](http://github.com/pingcap/tidb/session.(*session).SetMemoryFootprintChangeHook.func1(0xc42b905388?))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:4096](http://github.com/pingcap/tidb/session/session.go:4096) +0xc5
[github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).SetMemoryFootprintChangeHook.func1()](http://github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).SetMemoryFootprintChangeHook.func1())
        /go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb.go:875](http://github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb.go:875) +0x2c
[github.com/tikv/client-go/v2/internal/unionstore.(*memdbArena).onMemChange(0xc42b9053c0?)](http://github.com/tikv/client-go/v2/internal/unionstore.(*memdbArena).onMemChange(0xc42b9053c0?))
        /go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb_arena.go:141](http://github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb_arena.go:141) +0x33
[github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).Cleanup](http://github.com/tikv/client-go/v2/internal/unionstore.(*MemDB).Cleanup)(0xc68ccfcd20, 0x1)
        /go/pkg/mod/[github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb.go:158](http://github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb.go:158) +0x185
[github.com/pingcap/tidb/store/driver/txn.(*memBuffer).Cleanup](http://github.com/pingcap/tidb/store/driver/txn.(*memBuffer).Cleanup)(0x38c057c?, 0xc68ccfcd20?)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/store/driver/txn/unionstore_driver.go:74](http://github.com/pingcap/tidb/store/driver/txn/unionstore_driver.go:74) +0x1c
[github.com/pingcap/tidb/session.(*LazyTxn).changeToInvalid(0xc008fd4c90)](http://github.com/pingcap/tidb/session.(*LazyTxn).changeToInvalid(0xc008fd4c90))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/txn.go:315](http://github.com/pingcap/tidb/session/txn.go:315) +0x4f
[github.com/pingcap/tidb/session.(*LazyTxn).reset(0x0?)](http://github.com/pingcap/tidb/session.(*LazyTxn).reset(0x0?))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/txn.go:555](http://github.com/pingcap/tidb/session/txn.go:555) +0x28
[github.com/pingcap/tidb/session.(*LazyTxn).Rollback(0xc008fd4c90)](http://github.com/pingcap/tidb/session.(*LazyTxn).Rollback(0xc008fd4c90))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/txn.go:436](http://github.com/pingcap/tidb/session/txn.go:436) +0xb4
[github.com/pingcap/tidb/session.(*session).RollbackTxn](http://github.com/pingcap/tidb/session.(*session).RollbackTxn)(0xc008fd4c80, {0x5297910?, 0xc10d6d9ad0?})
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:1112](http://github.com/pingcap/tidb/session/session.go:1112) +0xda
[github.com/pingcap/tidb/session.(*session).Close(0xc008fd4c80)](http://github.com/pingcap/tidb/session.(*session).Close(0xc008fd4c80))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/session/session.go:2564](http://github.com/pingcap/tidb/session/session.go:2564) +0x265
[github.com/pingcap/tidb/server.(*TiDBContext).Close(0xc007ee7fc8)](http://github.com/pingcap/tidb/server.(*TiDBContext).Close(0xc007ee7fc8))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/driver_tidb.go:268](http://github.com/pingcap/tidb/server/driver_tidb.go:268) +0xb7
[github.com/pingcap/tidb/server.closeConn](http://github.com/pingcap/tidb/server.closeConn)(0xc0077e5080, 0xc001968e40?)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn.go:356](http://github.com/pingcap/tidb/server/conn.go:356) +0x1dc
[github.com/pingcap/tidb/server.(*clientConn).Close(0xc0077e5080)](http://github.com/pingcap/tidb/server.(*clientConn).Close(0xc0077e5080))
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/conn.go:340](http://github.com/pingcap/tidb/server/conn.go:340) +0x89
[github.com/pingcap/tidb/server.(*Server).onConn.func3()](http://github.com/pingcap/tidb/server.(*Server).onConn.func3())
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/server.go:601](http://github.com/pingcap/tidb/server/server.go:601) +0x2f
[github.com/pingcap/tidb/server.(*Server).onConn](http://github.com/pingcap/tidb/server.(*Server).onConn)(0xc0046bc800, 0xc0077e5080)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/server.go:641](http://github.com/pingcap/tidb/server/server.go:641) +0xbb4
created by [github.com/pingcap/tidb/server.(*Server).startNetworkListener](http://github.com/pingcap/tidb/server.(*Server).startNetworkListener)
        /home/jenkins/agent/workspace/build-common/go/src/[github.com/pingcap/tidb/server/server.go:482](http://github.com/pingcap/tidb/server/server.go:482) +0x5ca
### 4. What is your TiDB version? (Required)
6.6.0

**Comment by XuHuaiyu** [comment]
Apply `Open` and `Close` the childExec over and over again.
A new memory tracker will be created in `Open` and attached to ApplyExec.memTracker. But the old memory trackers are not detached in `Close`, thus they'll hold large memory which can not be GCed.
![78e90ae8-e62c-4d6b-be53-5ffbfc3b4559](https://user-images.githubusercontent.com/9039012/219278878-1a7ecd3f-c018-4089-9b4a-a6e4be4ed6d2.jpeg)

**Comment by XuHuaiyu** [comment]
global memory controller killed a wrong sql.
``` sh
2022232:[2023/02/16 11:25:58.424 +08:00] [WARN] [servermemorylimit.go:126] ["global memory controller tries to kill the top1 memory consumer"] [connID=3971954969015222677] ["sql digest"=6d0590fcb088a7be00d3c625cec85e43f71d7f46e581b844b83be2dbf5b54da0] ["sql text"=] [tidb_server_memory_limit=27487790640] ["heap inuse"=32395190272] ["sql memory usage"=37856]
2022233:[2023/02/16 11:25:58.427 +08:00] [WARN] [tracker.go:458] ["global memory controller, NeedKill signal is received successfully"] [connID=3971954969015222677]
2022234:[2023/02/16 11:25:58.427 +08:00] [WARN] [expensivequery.go:118] ["memory exceeds quota"] [cost_time=0.006575794s] [conn_id=3971954969015222677] [user=root] [database=longrun_tpcc] [index_names="[new_order:PRIMARY]"] [txn_start_ts=439489123622846523] [mem_max="38177 Bytes (37.3 KB)"] [sql=]
2022235:[2023/02/16 11:25:58.427 +08:00] [ERROR] [coprocessor.go:1073] ["copIteratorWork meet panic"] [r="\"Out Of Memory Quota![conn_id=3971954969015222677]\""] ["stack trace"="github.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1075\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:449\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:461\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).sendToRespCh\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:963\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopResponse\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1342\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleCopPagingResult\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1244\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTaskOnce\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1183\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).handleTask\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:1086\ngithub.com/pingcap/tidb/store/copr.(*copIteratorWorker).run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/copr/coprocessor.go:782"]
2022236:[2023/02/16 11:25:58.428 +08:00] [ERROR] [conn.go:1064] ["connection running loop panic"] [conn=3971954969015222677] [lastSQL="SELECT no_o_id FROM new_order WHERE no_w_id = ? AND no_d_id = ? ORDER BY no_o_id ASC LIMIT 1 FOR UPDATE [arguments: (253, 5)]"] [err="Out Of Memory Quota![conn_id=3971954969015222677]"] [stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1067\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:884\ngithub.com/pingcap/tidb/util/memory.(*PanicOnExceed).Action\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/action.go:148\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume.func2\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:449\ngithub.com/pingcap/tidb/util/memory.(*Tracker).Consume\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:461\ngithub.com/pingcap/tidb/util/memory.(*Tracker).ReplaceBytesUsed\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/memory/tracker.go:743\ngithub.com/pingcap/tidb/session.(*session).SetMemoryFootprintChangeHook.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:4096\ngithub.com/tikv/client-go/v2/internal/unionstore.(*MemDB).SetMemoryFootprintChangeHook.func1\n\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb.go:875\ngithub.com/tikv/client-go/v2/internal/unionstore.(*memdbArena).onMemChange\n\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb_arena.go:141\ngithub.com/tikv/client-go/v2/internal/unionstore.(*MemDB).Cleanup\n\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.6-0.20230209044022-95ebf6a86301/internal/unionstore/memdb.go:158\ngithub.com/pingcap/tidb/store/driver/txn.(*memBuffer).Cleanup\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/store/driver/txn/unionstore_driver.go:74\ngithub.com/pingcap/tidb/session.(*LazyTxn).cleanupStmtBuf\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/txn.go:151\ngithub.com/pingcap/tidb/session.(*LazyTxn).cleanup\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/txn.go:559\ngithub.com/pingcap/tidb/session.(*session).StmtRollback\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/txn.go:730\ngithub.com/pingcap/tidb/session.finishStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/tidb.go:243\ngithub.com/pingcap/tidb/session.runStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2361\ngithub.com/pingcap/tidb/session.(*session).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2199\ngithub.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:247\ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:266\ngithub.com/pingcap/tidb/server.(*clientConn).executePlanCacheStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:224\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:216\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1407\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1129\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:625"]
```

**Comment by XuHuaiyu** [comment]
Corner case, downgrade severity to major

**Comment by XuHuaiyu** [comment]
reproduciable steps:
``` sql
CREATE TABLE `t` (
  `rk` varchar(16) NOT NULL,
  `cfq` varchar(10) NOT NULL,
  `ts` bigint(20) NOT NULL,
  `value` varchar(2048) DEFAULT NULL,
  PRIMARY KEY (`rk`,`cfq`,`ts`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

# insert 4,000,000 tuples

explain analyze SELECT   * FROM   t WHERE   rk = "aaa"   AND cfq = "bbb"   AND ts <(     SELECT       ts     WHERE       rk = "aaa"     AND cfq = "bbb"     ORDER BY       ts DESC     LIMIT       1    );
```
