### ISSUE TITLE
proxy-protocol.networks doesn't work as expected

### ISSUE THREAD

**Issue by TNTSCUT** [pingcap/tidb#41526]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
We have a 6.5.0 version tidb running on server xx.xx.xx.116,port: 34000, with config below
```
  tidb:
    proxy-protocol.networks: xx.xx.xx.115
```
haproxy running on server xx.xx.xx.115, with config
```
bind 0.0.0.0:5000
server tidb-3 xx.xx.xx.116:34000  send-proxy check inter 2000 rise 2 fall 3
```
on server xx.xx.xx.111, we connect to tidb using MySQL client, then execute sql "show processlist"。
```
mysql -uroot -p -hxx.xx.xx.115 -P5000
```
<img width="844" alt="image" src="https://user-images.githubusercontent.com/18673911/219400600-8443a4b0-5200-4a46-937f-53a19bd3b2f8.png">

### 2. What did you expect to see? (Required)
Real ip address of client server, in this case is xx.xx.xx.111

### 3. What did you see instead (Required)
IP address of haproxy server xx.xx.xx.115

### 4. What is your TiDB version? (Required)

<img width="547" alt="image" src="https://user-images.githubusercontent.com/18673911/219400363-40b4bf8d-22f1-4345-8266-d9268d6c1a81.png">

**Comment by TNTSCUT** [comment]
## Test in v6.1.2
### haproxy runs in server xx.xx.xx.15.
change the haproxy config pointing to  TiDB v6.1, reboot the haproxy process.
```
bind 0.0.0.0:5000
server tidb-3 xx.xx.xx.111:4100  send-proxy check inter 2000 rise 2 fall 3
```
### TiDB proxy-protocol.networks
```
  tidb:
    proxy-protocol.networks: xx.xx.xx.115
```
### login to v6.1 TiDB xx.xx.xx.115:5000
<img width="865" alt="image" src="https://user-images.githubusercontent.com/18673911/219540140-8372f110-77ac-4946-ac77-4f0f8d81157a.png">

### TiDB version
<img width="688" alt="image" src="https://user-images.githubusercontent.com/18673911/219540251-46f40fca-e95b-4250-a96b-2e8658a1bc8c.png">

**Comment by bb7133** [comment]
> Test in v6.1.2

Hi @TNTSCUT , looks like that you changed the servers when testing TiDB v6.1.2, just to confirm: do u mean that TiDB this issue does not happen for v6.1.2?

**Comment by bb7133** [comment]
Very likely that this is duplicated with https://github.com/pingcap/tidb/issues/41409.

@TNTSCUT If possible, you could have try the `nightly` build of TiDB and check if this has been fixed. /cc @xhebox

**Comment by TNTSCUT** [comment]
> 

nightly version works right.
<img width="969" alt="image" src="https://user-images.githubusercontent.com/18673911/220001454-cfb62e9b-4ab6-4314-a89d-2ec4dfd1fa7d.png">

**Comment by xhebox** [comment]
Cherry-picked solution to 6.5
