### ISSUE TITLE
potential goroutine leak problem

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#41557]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
``` sql
CREATE TABLE `t` (
  `rk` varchar(16) NOT NULL,
  `cfq` varchar(10) NOT NULL,
  `ts` bigint(20) NOT NULL,
  `value` varchar(2048) DEFAULT NULL,
  PRIMARY KEY (`rk`,`cfq`,`ts`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;

# insert 4,000,000 tuples

explain analyze SELECT   * FROM   t WHERE   rk = "aaa"   AND cfq = "bbb"   AND ts <(     SELECT       ts     WHERE       rk = "aaa"     AND cfq = "bbb"     ORDER BY       ts DESC     LIMIT       1    );
```

During the investigation of #41476 , I found there might be a potential goroutine leak problem.
The memory usage of `NewTracker` keeps growing even if the SQL is finished.
<img width="1696" alt="截屏2023-02-17 22 26 07" src="https://user-images.githubusercontent.com/9039012/219682872-06652b5e-07ea-4cfe-935a-7c10015bdc7c.png">
<img width="1688" alt="截屏2023-02-17 22 32 34" src="https://user-images.githubusercontent.com/9039012/219683082-f92b818a-14b0-463b-8071-b08bfb4ad943.png">
<img width="1692" alt="截屏2023-02-17 22 32 53" src="https://user-images.githubusercontent.com/9039012/219683180-65075c0b-e9a2-466d-a707-50b271bd2b48.png">

### 2. What did you expect to see? (Required)
The memory usage should not increase after SQL finished.

### 4. What is your TiDB version? (Required)

master 69a9dec7df944587e928e93253b7079ff6dcaac0

**Comment by SeaRise** [comment]
Close this issue as it cannot be reproduced.
