### ISSUE TITLE
Adding index on v6.6 is 5% slower than v6.5 when using tidb_ddl_enable_fast_reorg

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#41562]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
add index on ossinsight dataset

### 2. What did you expect to see? (Required)
no performance regression

### 3. What did you see instead (Required)
5% performance regression 
### 4. What is your TiDB version? (Required)
v6.6

v6.6

**Comment by zimulala** [comment]
There was some jitter in between, but in multiple tests, you can guess that this PR(https://github.com/pingcap/tidb/pull/40711) caused a 2-3% performance drop.  @you06 Please have a look.
<img width="760" alt="Screenshot 2023-02-26 at 10 39 37" src="https://user-images.githubusercontent.com/4242506/221389363-dc45c661-40e2-47f6-b792-58bf334a8fc7.png">
