### ISSUE TITLE
Inconsistent Flen of datetime between tidb and mysql

### ISSUE THREAD

**Issue by bailaohe** [pingcap/tidb#4165]
It seems TIDB's outputs of field metadata is inconsistent with Mysql in columns of type Datetime.

The column info in mysql is as follows, with flen 22.

> mysql> select c_datetime from t;
Field   1:  `c_datetime`
Catalog:    `def`
Database:   `testdb`
Table:      `t`
Org_table:  `t`
Type:       DATETIME
Collation:  binary (63)
Length:     22
Max_length: 22
Decimals:   2
Flags:      BINARY

In Tidb I get 0

>mysql> select c_datetime from t;
Field   1:  `c_datetime`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       DATETIME
Collation:  binary (63)
Length:     0
Max_length: 0
Decimals:   2
Flags:      BINARY

In typeinfer_tests, the flen of datetime is types.UnspecifiedLength.

**Comment by XuHuaiyu** [comment]
Thank you,
if possible, may you push a PR to make it right.
https://github.com/pingcap/tidb/blob/master/mysql/util.go#L21
This can be referred.

**Comment by zz-jason** [comment]
related to https://github.com/pingcap/tidb/issues/3983

**Comment by XuHuaiyu** [comment]
fixed by #4200
