### ISSUE TITLE
MySQL connector 6.06 cannot connect TIDB

### ISSUE THREAD

**Issue by aruanruan** [pingcap/tidb#4171]
com.mysql.cj.core.exceptions.UnableToConnectException(ExceptionFactory.java:73)
CLIENT_PLUGIN_AUTH is required

tidb 日志:
2017/08/14 17:13:22 server.go:219: [info] [775] new connection xxx.xxx.xxx.xxx:34777
2017/08/14 17:13:22 terror.go:274: [warning] Unknown error class: server code: 3
2017/08/14 17:13:22 server.go:225: [info] handshake error /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:77: [server:3]invalid sequence 0 != 1
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:94:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:290:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:99:
2017/08/14 17:13:22 server.go:219: [info] [775] close connection
2017/08/14 17:13:22 server.go:118: [info] [776] new connection xxx.xxx.xxx.xxx:34778
2017/08/14 17:13:22 server.go:118: [info] [777] new connection xxx.xxx.xxx.xxx:34779
2017/08/14 17:13:22 terror.go:274: [warning] Unknown error class: server code: 3
2017/08/14 17:13:22 server.go:225: [info] handshake error /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:77: [server:3]invalid sequence 0 != 1
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:94:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:290:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:99:
2017/08/14 17:13:22 server.go:219: [info] [776] close connection
2017/08/14 17:13:22 terror.go:274: [warning] Unknown error class: server code: 3
2017/08/14 17:13:22 server.go:225: [info] handshake error /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:77: [server:3]invalid sequence 0 != 1
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:94:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:290:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:99:
2017/08/14 17:13:22 server.go:219: [info] [777] close connection

**Comment by shenli** [comment]
TiDB does not support CLIENT_PLUGIN_AUTH now.
@tiancaiamao PTAL

**Comment by aruanruan** [comment]
ok, it is ok when back to connector of 5.x

**Comment by tiancaiamao** [comment]
Nothing serious, the client send a packet that TiDB can't recognise.
