### ISSUE TITLE
'Server Status/users and privileges' error in MySQL Workbench

### ISSUE THREAD

**Issue by aruanruan** [pingcap/tidb#4172]
click Management"Server Status" or "Users and Privileges" response:
QueryError: Error executing 'SHOW PLUGINS' line 0 column 12 near ""(total length 12).
SQL Error:1105

tidb.log shows:

2017/08/14 17:21:06 session.go:629: [warning] [1228] parse error:
line 0 column 12 near "" (total length 12)
SHOW PLUGINS
2017/08/14 17:21:06 conn.go:380: [warning] [1228] dispatch error:
id:1228, addr:10.74.152.207:63456 status:2, collation:utf8_general_ci, user:root
SHOW PLUGINS
line 0 column 12 near "" (total length 12)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:99:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:630:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:684:

**Comment by zimulala** [comment]
@tiancaiamao

**Comment by tiancaiamao** [comment]
Currently we don't support `SHOW PLUGINS` statement, so you meet error.
I'll do it later.
