### ISSUE TITLE
tidb oom when running tpc

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#41738]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. run tpc

### 3. What did you see instead (Required)
oomkilled
![image](https://user-images.githubusercontent.com/50363732/221458829-9f3a2e14-8c4a-483d-832a-41ceffb1b59e.png)

### 4. What is your TiDB version? (Required)
Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: 79558c08ad9e30a915872448a9988dbba97b50b3
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-02-18 11:41:38
GoVersion: go1.19.5
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by windtalker** [comment]
@AkiraXie can you provide some details about the oom? For example how many memory does the tidb node have and the data scale?

**Comment by XuHuaiyu** [comment]
It's strange that global memory killed the query successfully, but did not print the log `global memory controller killed the top1 memory consumer successfully`. After 8 seconds, tidb OOM and restarted.

**Comment by XuHuaiyu** [comment]
Not a bug, the OOM is possible because the tidb_mem_quota_query is set to 32GB, and the memory is only controlled by tidb_server_memory_limit. The memory pressure is high when killing the first query, and the second query is sent to tidb-server immediately, thus causeing the OOM.
