### ISSUE TITLE
How to elegantly parse a JSON string

### ISSUE THREAD

**Issue by gubinjie** [pingcap/tidb#41739]
My JSON contains arrays, how can I parse the data into multiple rows without using subscripts?

My JSON: `{
    "data":
    [
        {
            "items":
            [
                {
                    "name": "20_",
                    "nameCn": "发电量#日报",
                    "type": "FLOAT",
                    "unit": "MWh",
                    "value": 271.392
                },
                {
                    "name": "20_Ws",
                    "nameCn": "上网电量#日报",
                    "type": "FLOAT",
                    "unit": "MWh",
                    "value": 131.25
                },
                {
                    "name": "20_ss",
                    "nameCn": "发电厂用电量",
                    "type": "FLOAT",
                    "unit": "MWh",
                    "value": 28.93
                },
                {
                    "name": "20_ssa",
                    "nameCn": "2#日供电量",
                    "type": "FLOAT",
                    "value": 0.0
                }
            ],
            "name": "1.faji2",
            "nameCn": "2#发机"
        },
        {
            "items":
            [
                {
                    "name": "Q",
                    "nameCn": "1#实际供热量#日报",
                    "type": "FLOAT",
                    "unit": "GJ",
                    "value": 5496.0
                },
                {
                    "name": "Qg",
                    "nameCn": "1#实际供热量",
                    "type": "FLOAT",
                    "value": 5496.0
                }
            ],
            "name": "1.qji",
            "nameCn": "1轮机"
        }
    ],
    "dataSource": "1#组",
    "endTime": "2020-09-03 00:00:00",
    "period": "Day",
    "serviceCode": "LW",
    "startTime": "2020-09-02 00:00:00"
}`

**Comment by ljluestc** [comment]
```
import json

# Your JSON string
json_str = '''
{
    "data": [
        {
            "items": [
                {
                    "name": "20_",
                    "nameCn": "发电量#日报",
                    "type": "FLOAT",
                    "unit": "MWh",
                    "value": 271.392
                },
                {
                    "name": "20_Ws",
                    "nameCn": "上网电量#日报",
                    "type": "FLOAT",
                    "unit": "MWh",
                    "value": 131.25
                },
                {
                    "name": "20_ss",
                    "nameCn": "发电厂用电量",
                    "type": "FLOAT",
                    "unit": "MWh",
                    "value": 28.93
                },
                {
                    "name": "20_ssa",
                    "nameCn": "2#日供电量",
                    "type": "FLOAT",
                    "value": 0.0
                }
            ],
            "name": "1.faji2",
            "nameCn": "2#发机"
        },
        {
            "items": [
                {
                    "name": "Q",
                    "nameCn": "1#实际供热量#日报",
                    "type": "FLOAT",
                    "unit": "GJ",
                    "value": 5496.0
                },
                {
                    "name": "Qg",
                    "nameCn": "1#实际供热量",
                    "type": "FLOAT",
                    "value": 5496.0
                }
            ],
            "name": "1.qji",
            "nameCn": "1轮机"
        }
    ],
    "dataSource": "1#组",
    "endTime": "2020-09-03 00:00:00",
    "period": "Day",
    "serviceCode": "LW",
    "startTime": "2020-09-02 00:00:00"
}
'''

# Parse the JSON string
data = json.loads(json_str)

# Access the "data" key to get the array of objects
data_array = data["data"]

# Iterate through each object in the array and access the "items" key to get the array of items
for obj in data_array:
    items_array = obj["items"]
    for item in items_array:
        # Access the attributes of each item
        name = item["name"]
        nameCn = item["nameCn"]
        type_ = item["type"]
        unit = item["unit"]
        value = item["value"]
        
        # Print or process the attributes as needed
        print(f"name: {name}, nameCn: {nameCn}, type: {type_}, unit: {unit}, value: {value}")
```

**Comment by gubinjie** [comment]
TH
