### ISSUE TITLE
close of closed channel in (*HashAggExec).Close

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#41778]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE `6ea6fc5a` (
                            `b28e1129` json DEFAULT NULL,
                            `e6f9d33b` decimal(31,1) DEFAULT '-229239137389541701499094015080.1'
);

CREATE TABLE `02ed3374` (
                            `1b60d2bf` smallint(6) DEFAULT '-11385',
                            `3a7ec6ea` decimal(63,14) DEFAULT '-6197127648752447138876497216172307937317445669286.98661563645110',
                            KEY `76114f1d` (`1b60d2bf`)
) ENGINE=InnoDB DEFAULT CHARSET=ascii COLLATE=ascii_bin COMMENT='be783ecc'
    PARTITION BY HASH (`1b60d2bf`) PARTITIONS 3;


CREATE TABLE `cead3486` (
                            `1c73b98b` text DEFAULT NULL,
                            `b4e81697` float NOT NULL DEFAULT '1.8132474',
                            PRIMARY KEY (`b4e81697`) /*T![clustered_index] CLUSTERED */
);


insert into `6ea6fc5a` values (NULL,   1228.0);
insert into `6ea6fc5a` values ('"json string1"' ,    623.8);
insert into `6ea6fc5a` values (NULL,   1337.0);
insert into `6ea6fc5a` values ('-44' ,     24.0);
insert into `6ea6fc5a` values ('"json string1"' , 882543.0);
insert into `6ea6fc5a` values ('"json string1"' ,     24.0);
insert into `6ea6fc5a` values ('323232323.32323235' ,     24.0);
insert into `6ea6fc5a` values ('-44' ,     24.0);
insert into `6ea6fc5a` values ('"json string1"' ,     24.0);
insert into `6ea6fc5a` values ('"json string1"' ,     24.0);

select count(*)
from `6ea6fc5a`
where not (`6ea6fc5a`.`b28e1129` in (select `3a7ec6ea`
                                     from `02ed3374`
                                     where not (`6ea6fc5a`.`b28e1129` in (select `1c73b98b`
                                                                          from `cead3486`
                                                                          where `6ea6fc5a`.`e6f9d33b` in
                                                                                (select `3a7ec6ea`
                                                                                 from `02ed3374`
                                                                                 where not (`6ea6fc5a`.`e6f9d33b` between 61151 and 260381)
                                                                                   and IsNull(`6ea6fc5a`.`b28e1129`))))
                                        ));
```

**Comment by xiongjiwei** [comment]
stack 

<details> <summary>View Stack</summary>

"github.com/pingcap/tidb/executor.(*recordSet).Next.func1
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:170
runtime.gopanic
/usr/local/go/src/runtime/panic.go:884
runtime.closechan
/usr/local/go/src/runtime/chan.go:365
github.com/pingcap/tidb/executor.(*HashAggExec).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/aggregate.go:279
github.com/pingcap/tidb/executor.(*UnionExec).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:2001
github.com/pingcap/tidb/executor.(*baseExecutor).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:214
github.com/pingcap/tidb/executor.(*HashAggExec).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/aggregate.go:292
github.com/pingcap/tidb/executor.(*baseExecutor).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:214
github.com/pingcap/tidb/executor.(*HashJoinExec).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/join.go:190
github.com/pingcap/tidb/executor.(*baseExecutor).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:214
github.com/pingcap/tidb/executor.(*HashJoinExec).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/join.go:190
github.com/pingcap/tidb/executor.(*baseExecutor).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:214
github.com/pingcap/tidb/executor.(*SelectionExec).Close
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:1637
github.com/pingcap/tidb/parser/terror.Call
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:306
github.com/pingcap/tidb/executor.(*NestedLoopApplyExec).fetchAllInners
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/join.go:1417
github.com/pingcap/tidb/executor.(*NestedLoopApplyExec).Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/join.go:1468
github.com/pingcap/tidb/executor.Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:324
github.com/pingcap/tidb/executor.(*SelectionExec).Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:1661
github.com/pingcap/tidb/executor.Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:324
github.com/pingcap/tidb/executor.(*StreamAggExec).consumeCurGroupRowsAndFetchChild
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/aggregate.go:1406
github.com/pingcap/tidb/executor.(*StreamAggExec).consumeOneGroup
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/aggregate.go:1334
github.com/pingcap/tidb/executor.(*StreamAggExec).Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/aggregate.go:1323
github.com/pingcap/tidb/executor.Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:324
github.com/pingcap/tidb/executor.(*ExecStmt).next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1221
github.com/pingcap/tidb/executor.(*recordSet).Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:173
github.com/pingcap/tidb/server.(*tidbResultSet).Next
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:423
github.com/pingcap/tidb/server.(*clientConn).writeChunks
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2243
github.com/pingcap/tidb/server.(*clientConn).writeResultset
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2186
github.com/pingcap/tidb/server.(*clientConn).handleStmt
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2059
github.com/pingcap/tidb/server.(*clientConn).handleQuery
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1887
github.com/pingcap/tidb/server.(*clientConn).dispatch
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1384
github.com/pingcap/tidb/server.(*clientConn).Run
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1144
github.com/pingcap/tidb/server.(*Server).onConn
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:646"

</details>

**Comment by solotzg** [comment]
https://github.com/pingcap/tidb/blob/6f1bdf76cf3e1ea0496ca6217b8afdad745a1b5d/executor/aggregate.go#L267-L291

Maybe we need to reset `parallelExecInitialized`.
