### ISSUE TITLE
lightning: performance regression with duplicate detection enabled on v6.6.0

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb#41859]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Use Lightning to import some data into TiDB with duplicate detection enabled.

```
[tikv-importer]
duplicate-resolution = "remove"
```

### 2. What did you expect to see? (Required)
Lightning import data fast.

### 3. What did you see instead (Required)
Lightning run much slower than v6.5. Compression enabled means `tikv-importer.compress-kv-pairs` is enabled.

Version | Compression | Network traffic | Time cost
-- | -- | -- | --
6.5 | Disabled | 1.81TiB | 31m40s
6.6 | Enabled | 655GiB | 1h34m36s
6.6 | Disabled | 1.64TiB | 1h2m12s
6.6(retest) | Disabled | 1.66TiB | 1h4m32s

### 4. What is your TiDB version? (Required)
v6.6.0

**Comment by gozssky** [comment]
v6.5
![FysRW29kXp](https://user-images.githubusercontent.com/17199941/222369733-e4a79cba-958e-4921-b4b1-6b6fbc606178.jpg)


v6.6
![loBpNvlXYg](https://user-images.githubusercontent.com/17199941/222369687-5a9310e1-2992-4104-93b5-3889564d99dc.jpg)
