### ISSUE TITLE
If jdbc fetch and udv are used, the udv value is changed after fetch, and subsequent fetch results are incorrect.

### ISSUE THREAD

**Issue by bob34007** [pingcap/tidb#41891]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

## java code 
String sql_select = "select id from user where id < @a ";
stmt = conn.createStatement();
stmt.execute("set @a = 30");
pstmt_select.setFetchSize(2);
ResultSet res = pstmt_select.executeQuery();
//stmt.execute("set @a = 70");
while(res.next()) {
  int id = res.getInt("id") ;
  System.out.println("线程ID"+num +" id:" + id);
  stmt.execute("set @a = 70");
}
res.close();

### 2. What did you expect to see? (Required)
The console prints values less than 30 .

### 3. What did you see instead (Required)
The console prints values less than 70 .

### 4. What is your TiDB version? (Required)
v6.5.0

| Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

**Comment by YangKeao** [comment]
TiDB has many problems running multiple statement concurrently (through cursor fetch). It's not suggested to run any statement (include `commit`, `set` ...) between the `prepare`->`execute`->`fetch`->`close` cycle.

(But yes. It's regarded as a bug and will finally be fixed.)

**Comment by YangKeao** [comment]
I added a TODO here: https://github.com/pingcap/tidb/pull/41441/files#diff-788928fb76e3e47e40088ccea6e776e5483dc131828914422aa420720dffbabbR38 .
