### ISSUE TITLE
how real-time sync tidb data to elasticsearch ?

### ISSUE THREAD

**Issue by wolaiye1010** [pingcap/tidb#4190]
以前用mysql的时候，是使用阿里的 canal 监控binlog 
canal模拟mysql slave的交互协议，伪装自己为mysql slave，canal解析binary log对象 实时
把curd 的操作实时同步到elasticsearch，
我看tidb也有binlog，跟mysql  binlog一样吗，是否可以直接使用canal 搭建同步数据呢，
如果不行有没有其他的方案呢

**Comment by shenli** [comment]
@wolaiye1010 We have developed a binlog module for TiDB. You can get binlog from it with protobuf format. With the proto file, you can do anything with the binlog data.
@GregoryIan

**Comment by weirui** [comment]
解决了吗，求教程 @wolaiye1010

**Comment by ayzmkk** [comment]
@shenli 这个tidb-binlog的proto的schema在哪里定义的？

**Comment by jy4618272** [comment]
应该是这个：https://github.com/pingcap/tipb/blob/master/go-binlog/binlog.pb.go
