### ISSUE TITLE
grant privilege identified by password should be hash string

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#4196]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

In MySQL, it's invalid:

```
mysql> grant select on *.* to 'genius'@'%' identified by password '0101001';
ERROR 1827 (HY000): The password hash doesn't have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function.
```

2. What did you expect to see?

According to [mysql document](https://dev.mysql.com/doc/refman/5.7/en/grant.html#grant-accounts-passwords), grant privilege identified by password should be hash string.

3. What did you see instead?

TiDB accept the input `grant select on *.* to 'genius'@'%' identified by password '0101001';`

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by breeswish** [comment]
Additional note:

https://dev.mysql.com/doc/refman/5.7/en/sha256-pluggable-authentication.html

```sql
CREATE USER 'sha256user'@'localhost'
IDENTIFIED WITH sha256_password BY 'Sh@256Pa33';
```

**Comment by tiancaiamao** [comment]
We don't support authentication plugin now.

**Comment by MikeLing** [comment]
Hi, I'm new to tidb and I would like to get involved into it. I already clone and build tidb as the document session said, so what should I do next? How could I run and reproduce this issue **locally** ?

Thanks a lot :)

**Comment by breeswish** [comment]
@MikeLing You can just run `./bin/tidb-server`, then it will run in local mode, which doesn't need `pd` and `tikv`.

**Comment by coocood** [comment]
@MikeLing 
The contribution doc lacks run tidb in single machine mode step. we should add it later.

You can just run the binary `bin/tidb-server` without any arguments.

```
bin/tidb-server
```

Then use mysql client to connect to TiDB at port 4000.
```
mysql -h 127.0.0.1 -P4000 -u root test
```

**Comment by MikeLing** [comment]
Hi @coocood , yeah, that's exactly I want to ask about. Thank you and @breeswish !

And I also see some interesting thing happened. Actually, I run

`  mysql -u root -h localhost -P 4000 -p`

and type `grant select on *.* to 'genius'@'%' identified by password '0101001';`

 then, of course, I get 

`ERROR 1827 (HY000): The password hash doesn't have the expected format. Check if the correct password algorithm is being used with the PASSWORD() function.`

But the tidb server keep outputting log message like 

> 2017/11/06 13:22:20.440 domain.go:521: [info] [domain] reload privilege success.

should I worry about that? Thanks

**Comment by tiancaiamao** [comment]
Yes, that's a bug as I described:

> TiDB accept the input grant select on *.* to 'genius'@'%' identified by password '0101001';

TiDB should check the password string to be a legal one, something like a md5 hash, and reject the wrong input.

The right SQL statement should be 

```
select on *.* to 'genius'@'%' identified by password('0101001');
```

**Comment by MikeLing** [comment]
Hi, can I use `go test executor/grant_test.go ` to run the unit test if I don't want to run all the tests at once? Or?

**Comment by breeswish** [comment]
@MikeLing 

You can use  `go test github.com/pingcap/tidb/executor` to test a single package,
or `go test -check.f TestXXX` to test a single function.

If you encountered dependencies issues, you may want to add the dependency directory into GOPATH, for example, `GOPATH="$GOPATH/src/github.com/pingcap/tidb/_vendor:$GOPATH"  go test github.com/pingcap/tidb/executor`

**Comment by MikeLing** [comment]
Hello guys,

I have a naive question in here. What should I do to debug tidb step by step(like gdb or pdb)? Does godebug or delve help?  I just want to figure out how a SQL statement is translated and executed by tidb inside.  What should I do to call password function before the statement be passed into grant executor?

Thanks a lot!

**Comment by tiancaiamao** [comment]
`fmt.Println` is your friend... and also the choice by most of us. @MikeLing

**Comment by breeswish** [comment]
@MikeLing delve does help. For overviews about how internally a SQL statement is translated and executed, you may refer to our documentation, which has some explains about the flow.
