### ISSUE TITLE
grant privilege for database with certain option is not valid

### ISSUE THREAD

**Issue by wx-chevalier** [pingcap/tidb#4197]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
when i use dts to transfer data from rds to local tidb, it need to check privileges; and the following grant command is valid in mysql, but invalid in tidb.

2. What did you expect to see?

```
// in mysql
mysql> grant ALTER,DELETE,CREATE,TRIGGER,CREATE ROUTINE,INSERT,INDEX,CREATE VIEW,SELECT on `12345-datavisualization`.* TO 'root'@'%';
Query OK, 0 rows affected (0.07 秒)

```

3. What did you see instead?

```
// in tidb
mysql> grant ALTER,DELETE,CREATE,TRIGGER,CREATE ROUTINE,INSERT,INDEX,CREATE VIEW,SELECT on `12345-datavisualization`.* TO 'root'@'%';
ERROR 1105 (HY000): line 0 column 48 near ",INSERT,INDEX,CREATE VIEW,SELECT on `12345-datavisualization`.* TO 'root'@'%'" (total length 125)
```

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: 18f84dd3c673616c1edd546002ecbfb3dd324a20
UTC Build Time:  2017-08-08 02:32:12

**Comment by shenli** [comment]
@wxyyxc1992 Thanks for your feedback. TiDB does not support the keyword `CREATE ROUTINE`.

**Comment by wxyyxc1992** [comment]
Ok, i know; can u recommend any online data transfer tool for mysql? i have used kettle or mysql dump, but those doesn't works very well. i need some tools can be monitored and run as service

**Comment by morgo** [comment]
This no longer causes a parse error, but TiDB does not support the privileges named `CREATE ROUTINE` or `CREATE VIEW`:

```
MySQL [test]> grant ALTER,DELETE,CREATE,TRIGGER,CREATE ROUTINE,INSERT,INDEX,CREATE VIEW,SELECT on `12345-datavisualization`.* TO 'root'@'%';
ERROR 1105 (HY000): Unknown priv: 0
MySQL [test]> grant ALTER,DELETE,CREATE,TRIGGER,INSERT,INDEX,CREATE VIEW,SELECT on `12345-datavisualization`.* TO 'root'@'%';
ERROR 1105 (HY000): Unknown priv: 0
MySQL [test]> grant ALTER,DELETE,CREATE,TRIGGER,INSERT,INDEX,SELECT on `12345-datavisualization`.* TO 'root'@'%';
Query OK, 0 rows affected (0.08 sec)
```

**Comment by morgo** [comment]
@wxyyxc1992 I recommend taking a look at DM and mydumper:
https://pingcap.com/docs/tools/mydumper/
https://pingcap.com/docs/tools/data-migration-overview/

**Comment by nullnotnil** [comment]
This has been fixed in master:
```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-859-gccfc9b2ad
Edition: Community
Git Commit Hash: ccfc9b2ad0dcf8e447210de5f559d7fc208db968
Git Branch: master
UTC Build Time: 2020-07-29 09:37:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.01 sec)

mysql> grant ALTER,DELETE,CREATE,TRIGGER,CREATE ROUTINE,INSERT,INDEX,CREATE VIEW,SELECT on `12345-datavisualization`.* TO 'root'@'%';
Query OK, 0 rows affected (0.05 sec)
```

I am going to close this issue now. Thanks!
