### ISSUE TITLE
[Parser] How to avoid select count(*) covert to select count(1)?

### ISSUE THREAD

**Issue by zenghur** [pingcap/tidb#41988]
before parser: `select  count(*) from  tbl`
after parser: `select count(1) from tbl`

**Comment by zenghur** [comment]
> The sql string "select count(*) from tbl" will be handled to ast after the parsing step. The parsing step won't include sql optimization. It needs more infomation to find the answer. Just like all the indexes of the table and when it becomes "select count(1)"

Actually, select count(*) is converted to select count (1)  in the parsing phase. Using the following code snippet to reproduce:

```
func RestoreCTX() (*format.RestoreCtx, *strings.Builder) {
	var s strings.Builder
	return format.NewRestoreCtx(
		format.RestoreStringSingleQuotes|
			format.RestoreKeyWordLowercase|
			format.RestoreNameBackQuotes|
			format.RestoreStringWithoutCharset, &s), &s
}

func TestParse(t *testing.T) {
	sqls := []string{
		`select count(*) from tbl`,
	}

	for _, sql := range sqls {
		no, err := Parse(sql, "", "")
		if err != nil {
			t.Log(err)
			return
		}

		ctx, s := RestoreCTX()
		err = no.Restore(ctx)
		if err != nil {
			t.Error(err)
			return
		}
		t.Log(s.String())
		t.Log(no)
	}
}
```

And it prints select count(1) from `tbl`.

**Comment by leeraya** [comment]
In my opinion, the test you use to  reproduce the parser problem is not in line with reality.
TiDB layer is: Protocol Layer -> Parser -> Compiler -> Executor
I debug tidb-server locally ,and I check the breakpoint when it finished to parse sql to AST . Just at the entry of compiling.<img width="1402" alt="截屏2023-03-16 10 44 08" src="https://user-images.githubusercontent.com/32791076/225496990-f28027f9-d5d6-469c-aded-b1f0d953f30c.png">
You can try it by lanuch '/tidb-server/main.go'. and breakpoint at '/executor/compiler/Compile.

**Comment by laojianzi** [comment]
Hi @leeraya 
This is the result of my debugging, and I also want to avoid this situation.

![image](https://github.com/pingcap/tidb/assets/42930263/b2ee76e1-d313-4d45-a236-b1fed40a967b)
![image](https://github.com/pingcap/tidb/assets/42930263/768631bc-9b0b-47e8-9131-8e70987d8998)

**Comment by Defined2014** [comment]
You could read this [link](https://github.com/pingcap/tidb/blob/44f1c1408cc497c486419a47a326bbad660c7e25/pkg/parser/parser.y#L8496) to get more information. 

And I think we will not change it right now. If you need it, you can try it yourself.
