### ISSUE TITLE
logs always show warning"StoreNotMatch"

### ISSUE THREAD

**Issue by wupaopao** [pingcap/tidb#4199]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
install tidb by docker
I had install tidb sucessfully before.For some reason,I remove them and delete all data.Now,I install it again and tidb logs show "StoreNotMatch".
![tidb_log](https://user-images.githubusercontent.com/10083199/29350609-cea45968-8291-11e7-98b0-b6d2c736a42a.jpg)
tikv logs show:
![tikv_log](https://user-images.githubusercontent.com/10083199/29350632-e6ed7e6e-8291-11e7-925b-51665a99c7a8.jpg)

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: d8396b8ed

**Comment by siddontang** [comment]
Hi @wupaopao 

Seem you deleted a TiKV and start a new TiKV on the same machine with the same port. 
PD must have some time to remove all data from the original old TiKV.

**Comment by wupaopao** [comment]
How long will it be done? I have deleted all tikvs's data dir and pd's data manually.Is that effective?

**Comment by wupaopao** [comment]
@siddontang I cannot connect to TiDB now.Is there any solution to install TiDB once again.Looking forward to your reply.Thanks.

**Comment by zimulala** [comment]
PTAL @siddontang

**Comment by siddontang** [comment]
@wupaopao 

You said you delete all TIKV and PD data, sadly, seem you can't use this cluster anymore.

@disksing If StoreNotMatch, we must return the error and shut down the connection. Seem we must check store in the raft gRPC function.

**Comment by wupaopao** [comment]
@siddontang Sorry,I don't quite understand.I know I can't use this cluster anymore.But can't I reset TiDB totally? There are no more machines for me to test.

**Comment by siddontang** [comment]
@wupaopao 

Of course, you can re-deploy your whole cluster in the same machines again, but you should close and remove the old cluster.

**Comment by disksing** [comment]
Hi @wupaopao , seems there is something wrong with the 'stop -> clean data -> restart' operation process. Is the pd-server's log still preserved?

**Comment by zhuangsheng** [comment]
How to fix this ?

**Comment by disksing** [comment]
Hi, @zhuangsheng Do you encounter the same problem? Did you reset the cluster too?

**Comment by zhuangsheng** [comment]
I deleted  and reinstalled tikv using tidb-ansible

**Comment by disksing** [comment]
@zhuangsheng Do you run `ansible-playbook stop.yml` and `ansible-playbook cleanup_data.yml` before re-install? All data of TiKV should be removed and all TiDB instances should restart too.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
