### ISSUE TITLE
The burst resource group cannot be reported in the grafana

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#42053]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. create 3 resource group with burst and 1 resource group without burst
2. run echo workload for the 4 resoruce group
### 3. What did you see instead (Required)
resource group with burst appear for sometime and disappear then.
![fe0df428-5f7e-4c68-afc4-36f80aebe16b](https://user-images.githubusercontent.com/7677963/223944011-6eb1fafb-8168-4bd1-bd71-3e3964a8f268.jpeg)
### 4. What is your TiDB version? (Required)

Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: 00ccee238af50d03ef09a42ffe61d6690293c25e
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-03-04 11:42:06
GoVersion: go1.20.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by nolouch** [comment]
same as https://github.com/tikv/pd/issues/6118, fixed.
