### ISSUE TITLE
Resource group without burst is exceeded much

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#42087]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

5 tidb and 6 tikv cluster, using some different workload bingding with each resource group
The sesource group without burst is exceeded much
![4qVDm551Rf](https://user-images.githubusercontent.com/7677963/224220489-01d668d5-133b-459f-9ce2-dcaf626fa257.jpg)
![6cfebe95-7b42-47d2-99d6-458548692fa9](https://user-images.githubusercontent.com/7677963/224220508-f2baef2e-bf7c-493b-b852-73fe590c1e00.jpeg)

### 4. What is your TiDB version? (Required)

 Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: 7089399891f170ab000400e301aa53d3cd6e531b
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-03-09 11:42:11
GoVersion: go1.20.1
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by nolouch** [comment]
ptal @CabinfeverB
