### ISSUE TITLE
SELECT INTO OUTFILE doesn't take effect when using clustered index to filter data

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#42093]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table t (id int not null, primary key (id) /*T![clustered_index] CLUSTERED */ );
insert into t values(1);
select * from t where id=1 into outfile '/tmp/data.txt';

### 2. What did you expect to see? (Required)
The resulting row is written to the file `data.txt`.

### 3. What did you see instead (Required)
The resulting row is just displayed in terminal.

### 4. What is your TiDB version? (Required)
v6.6.0

**Comment by yibin87** [comment]
Seems a planner issue:
mysql> explain select * from t where id=1 into outfile '/tmp/data.txt';
+-------------+---------+------+---------------+---------------+
| id          | estRows | task | access object | operator info |
+-------------+---------+------+---------------+---------------+
| Point_Get_1 | 1.00    | root | table:t       | handle:1      |
+-------------+---------+------+---------------+---------------+
1 row in set (0.00 sec)
