### ISSUE TITLE
Change system variable tidb_ddl_distribute_reorg to tidb_dist_task

### ISSUE THREAD

**Issue by Benjamin2037** [pingcap/tidb#42179]
## Feature Request

**Is your feature request related to a problem? Please describe:**

This issue is used to change tidb_ddl_distribute_reorg to tidb_dist_task, to make this system variable more fit for unified distributed parallel execution framework.

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by tangenta** [comment]
Closed by #42200.
