### ISSUE TITLE
Yes should be possible, we'll add it. Thanks for the suggestion!

### ISSUE THREAD

**Issue by Gau8262** [pingcap/tidb#42226]
Yes should be possible, we'll add it. Thanks for the suggestion!

_Originally posted by @Alek99 in https://github.com/pynecone-io/pynecone/issues/662#issuecomment-1465088925_

**Comment by bb7133** [comment]
Hi @Gau8262 Looks your issue is nothing related to TiDB, so I'm going to close it.

Feel free to re-open this if you have any issues related to TiDB.
