### ISSUE TITLE
Parser should always allocate a new array for result 

### ISSUE THREAD

**Issue by yujiarista** [pingcap/tidb#42230]
## Enhancement
In parser.Parser.ParseSQL, the result slice is truncated and the underlying array is reused.
https://github.com/pingcap/tidb/blob/master/parser/yy_parser.go#L158
`parser.result = parser.result[:0]`

This makes it slightly more difficult to reuse the parser object in some cases. For example
`
q1 := parser.ParseSQL(query1)
q2 := parser.ParseSQL(query2)
// do something about q1 and q2
`
The code would not work because the second call is going to overwrite the result of the first call.

We are supposed to reuse the parser object since it is not lightweight but parse object is not goroutine safe. So one use case is to use the parser object synchronously but process parsing results in different goroutines. However, due to reusing of the result array, one need to make a copy of the result before processing it in goroutine. It would be better if the parse can allocate a new array for result every time.

**Comment by yujiarista** [comment]
It doesn't affect performance. The issue is user has to read this code before they know they have to make a copy. Otherwise it may cause data race. 
This should be a very small change. I can open a PR.

**Comment by yujiarista** [comment]
@lance6716 Created a PR https://github.com/pingcap/tidb/pull/42538

**Comment by xhebox** [comment]
Closed by #42572
