### ISSUE TITLE
Missing table name in admin show ddl result during drop table

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#42268]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

During drop table, execute `admin show ddl jobs`

### 2. What did you expect to see? (Required)
The result shows the table name.

### 3. What did you see instead (Required)
The table name is empty

### 4. What is your TiDB version? (Required)
master

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/tidb/blob/ad590923354bd27f9cb6d657a8de359888cdfee6/executor/executor.go#L531-L560

The reason is that ... during drop table, the table is removed from the infoschema
So `getTableName` found nothing.
