### ISSUE TITLE
`read_from_storage` doesn't affect

### ISSUE THREAD

**Issue by TonsnakeLin** [pingcap/tidb#42295]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
drop table if exists t1;
Create table t1(id1 int primary key, id2 int);
alter table t1 set tiflash replica 1;
insert into t1 values(1,1),(10,10),(100, 100),(1000, 1000);

analyze table t1;

explain select /*+ read_from_storage(tiflash[t1]) */ id1,id2 from t1;
explain select id1,id2 /*+ read_from_storage(tiflash[t1]) */  from t1;

### 2. What did you expect to see? (Required)
+-------------------------+----------+--------------+---------------+---------------------------------------+
| id                      | estRows  | task         | access object | operator info                         |
+-------------------------+----------+--------------+---------------+---------------------------------------+
| TableReader_11          | 10000.00 | root         |               | MppVersion: 1, data:ExchangeSender_10 |
| └─ExchangeSender_10     | 10000.00 | mpp[tiflash] |               | ExchangeType: PassThrough             |
|   └─TableFullScan_9     | 10000.00 | mpp[tiflash] | table:t1      | keep order:false, stats:pseudo        |
+-------------------------+----------+--------------+---------------+---------------------------------------+

### 3. What did you see instead (Required)
+-----------------------+----------+-----------+---------------+--------------------------------+
| id                    | estRows  | task      | access object | operator info                  |
+-----------------------+----------+-----------+---------------+--------------------------------+
| TableReader_5         | 10000.00 | root      |               | data:TableFullScan_4           |
| └─TableFullScan_4     | 10000.00 | cop[tikv] | table:t1      | keep order:false, stats:pseudo |
+-----------------------+----------+-----------+---------------+--------------------------------+

### 4. What is your TiDB version? (Required)

 Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: ed1b4cf44890e4346849bce7c9297bde7e7abee5
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-03-13 14:34:44
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by jebter** [comment]
Please refer to the hint syntax：https://docs.pingcap.com/tidb/dev/optimizer-hints#syntax

**Comment by TonsnakeLin** [comment]
Yes, I mean we should give a warning when using the hint like this "select id1,id2 /+ read_from_storage(tiflash[t1]) */ from t1", because it doesn't affect and gives a success response.

**Comment by fzzf678** [comment]
similar issue to https://github.com/pingcap/tidb/issues/42149, and close this
