### ISSUE TITLE
Incorrect FieldType.Decimal Inference for INT, BIGINT, FLOAT, DOUBLE, TIMESTAMP Column

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#4233]
SQL:

```sql
create table t (
		c_int int,
		c_bigint bigint,
		c_float float,
		c_double double,
		c_decimal decimal(6, 3),
		c_datetime datetime(2),
		c_time time,
		c_timestamp timestamp,
		c_char char(20))
```

`FieldType.Decimal` of `c_int`, `c_bigint`, `c_float`, `c_double`, `c_timestamp` is `-1`.

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

**Comment by XuHuaiyu** [comment]
you can support it in mysql/util.go: GetDefaultDecimal @breeswish

**Comment by jackysp** [comment]
Set default in parser.y?

**Comment by XuHuaiyu** [comment]
We may take this opportunity to unify this, set default in parser.y may be also feasible. @jackysp 
What's your opinion？ @breeswish 
MySQL uses `opt_field_length` and `opt_precision`（in sql/ sql_yacc.yy） to parse this, and set it to `NULL` to indicate that the length and dec to be default if length and dec is not set explicitly.

**Comment by breeswish** [comment]
Currently in ddl_api.go we sets the default value if it is unspecified.

**Comment by XuHuaiyu** [comment]
If we set flen and decimal of all types in parser.y,
we can avoid checking this in ddl_api.go.

**Comment by breeswish** [comment]
I think both is acceptable since they are identical in some ways. The only difference is when the default value is set.

**Comment by XuHuaiyu** [comment]
ok
