### ISSUE TITLE
auto_increment always be 1 when show create table

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb#4234]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
create table with field attached attribute auto_increment , then insert some values.  execute sql : show create table xxx, then result shown always is auto_increment=1, actually max value of the field attached attribute auto_increment  is more then 1.

2. What did you expect to see?
execute sql : show create table xxx, then result shown is auto_increment=number , the number is actually max value of the field attached attribute auto_increment.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: d961afcd77b0be733bcee30a3a3ed3e5e5850463
UTC Build Time:  2017-08-10 09:17:12

**Comment by breeswish** [comment]
Related: https://github.com/pingcap/tidb/issues/3747

**Comment by zimulala** [comment]
It's duplicated with #3747
