### ISSUE TITLE
tidb fatal error when upgrading

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#42401]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)
"[bootstrap.go:1227] [\"doReentrantDDL error\"] [error=\"[schema:1146]Table 'mysql.tidb_background_subtask' doesn't exist\"] [stack=\"github.com/pingcap/tidb/session.doReentrantDDL\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:1227\\ngithub.com/pingcap/tidb/session.upgradeToVer136\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:2409\\ngithub.com/pingcap/tidb/session.upgrade\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/bootstrap.go:1077\\ngithub.com/pingcap/tidb/session.runInBootstrapSession\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:3482\\ngithub.com/pingcap/tidb/session.BootstrapSession\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:3264\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:343\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:240\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:250\"]"
### 4. What is your TiDB version? (Required)
target: 
Release Version: v7.0.0
Edition: Community
Git Commit Hash: fc166ffae8576ac3efb2f5abac848d5edbaf2657
Git Branch: heads/refs/tags/v7.0.0
UTC Build Time: 2023-03-20 07:08:59
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
source:
Release Version: v6.7.0-alpha
Edition: Community
Git Commit Hash: 145b7cdf72feeecf7f2b0b3e01693c603712dce5
Git Branch: heads/refs/tags/v6.7.0-alpha
UTC Build Time: 2023-03-11 11:42:07
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by hawkingrei** [comment]
In fact, It is a temporary version of TiDB from old master to upgrade to the latest TiDB. so It is not a problem to block the TiDB release.
