### ISSUE TITLE
grafana show pitr lag more than 30m when inject kill one tidb

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#42419]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
http://perf.pingcap.net:3000/d/WOw1JWmVk/ha-test-case-detail?orgId=1&refresh=10s&var-case_id=2610659
kill one tidb

### 2. What did you expect to see? (Required)
pitr lag less than 5m

### 3. What did you see instead (Required)
grafana show pitr lag more than 30m when inject kill one tidb
![image](https://user-images.githubusercontent.com/84712107/226533482-9ba89816-aa9a-4b58-82fa-168442d26f33.png)

### 4. What is your TiDB version? (Required)
git hash：56412f514ecad4209cb0d92878b68644ed94469a

**Comment by fubinzh** [comment]
Tested it with fix:
TiDB rolling restart before the fix:
![image](https://github.com/user-attachments/assets/73e8310e-b0e1-457b-b253-1abc9d1a7fb9)

After the fix:
![image](https://github.com/user-attachments/assets/93e84d6a-89e7-4737-9d09-68f1f717f416)

[root@upstream-tidb-0 /]# /tidb-server -V
Release Version: v8.4.0-alpha
Edition: Community
Git Commit Hash: b91cb0191799a2f055793894c5172f838ed77afa
Git Branch: heads/refs/tags/v8.4.0-alpha
UTC Build Time: 2024-09-04 11:46:09
