### ISSUE TITLE
The "add index" operation is block when dist-reorg is enabled

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#42436]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@global.tidb_ddl_distribute_reorg = on;
create table t(a int, b int);
alter table t add index idx(a);
```

### 2. What did you expect to see? (Required)
This "add index" operation executes normally.

### 3. What did you see instead (Required)
This operation is blocked.
The error log：` ["[ddl] runBackfillJobs error"] [error="[ddl:8247]Ingest failed: ingest engine not found"]`

### 4. What is your TiDB version? (Required)

master, after the PR: https://github.com/pingcap/tidb/pull/42115
```
Release Version: v6.7.0-alpha-347-g3f8b0ccd81-dirty
Edition: Community
Git Commit Hash: 3f8b0ccd81374a27a466db2e934737503905b30c
Git Branch: master
UTC Build Time: 2023-03-21 07:22:27
```

**Comment by tangenta** [comment]
Fixed in release 7.0: https://github.com/pingcap/tidb/pull/42438
