### ISSUE TITLE
lightning: compared with v6.6.0, the performance of v7.0.0 lightning downgrades 32%

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#42457]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a TiDB Cluster with 1 tidb + 6 tikv
2. restore the data of ycsb
3. export the data with dumpling
4. import the data with lightning

### 2. What did you expect to see? (Required)
No performance regression
### 3. What did you see instead (Required)
![image](https://user-images.githubusercontent.com/84501897/226773692-f3a4d57b-1c7a-4e9b-9492-2a2a1fdf7329.png)

### 4. What is your TiDB version? (Required)

v7.0.0

**Comment by gozssky** [comment]
https://github.com/pingcap/tidb/pull/42136 adds a new option `add-index-by-sql` and enable for TiDB v7.0.0 by default. It means lightning will use SQL to add index. However, TiDB adding index is slower than lightning importing index, even `tidb_ddl_enable_fast_reorg` is enabled.

To avoid performance regression, https://github.com/pingcap/tidb/pull/42514 always disables `add-index-by-sql` by default.
