### ISSUE TITLE
Unstable test TestPlanStatsLoad

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#42461]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)
pass

### 3. What did you see instead (Required)
```
    plan_stats_test.go:110:
        	Error Trace:	planner/core/plan_stats_test.go:110
        	            				planner/core/plan_stats_test.go:216
        	Error:      	"0" is not greater than "0"
        	Test:       	TestPlanStatsLoad
[2023/03/22 10:02:12.687 +08:00] [INFO] [ddl_workerpool.go:82] ["[ddl] closing workerPool"]
```

### 4. What is your TiDB version? (Required)

Reproduce in https://github.com/pingcap/tidb/pull/42454
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/20200/pipeline

**Comment by Rustin170506** [comment]
Not found it anymore.
