### ISSUE TITLE
unstable test TestShowBuiltin

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#42467]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
    show_test.go:1527: 

        	Error Trace:	executor/showtest/show_test.go:1527

        	Error:      	Not equal: 

        	            	expected: 287

        	            	actual  : 288

        	Test:       	TestShowBuiltin

```

**Comment by hawkingrei** [comment]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/20228/pipeline/

**Comment by Defined2014** [comment]
I think it's not a flaky test. https://github.com/pingcap/tidb/pull/42464 added a builtin function without change UT. :(
