### ISSUE TITLE
graceful shutdown hang

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#42474]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start a tidb-server 
2. start a session and run `use test`
3. graceful shutdown (ctrl + c)
4. just wait, we can see that tidb-server cannot exit successfully for a long time
5. run `use test` using the previous session
6. we can see tidb-server exits successfully now

### 2. What did you expect to see? (Required)
graceful shutdown successfully

### 4. What is your TiDB version? (Required)
master

**Comment by tiancaiamao** [comment]
4. just wait, we can see that tidb-server cannot exit successfully for a long time

If you mean 15s is 'a long time', then it's expected. @XuHuaiyu
