### ISSUE TITLE
and 1=1 cause runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by zwljava** [pingcap/tidb#4249]
1.What version of Rust are you using (rustc --version)?
rc4

2.What operating system and processor architecture are you using?
cenost6.7

3.What did you do?
run sql:
select count(a.id) from shopping_goods a join shopping_store b
where a.goods_store_id=b.id
and 1=1
and b.store_status=2 and a.goods_status=0
is error!
but run sql:
select count(a.id) from shopping_goods a join shopping_store b
where a.goods_store_id=b.id
and b.store_status=2 and a.goods_status=0
is ok!
so,and 1=1 error!
but ver rc3 is ok!

4.What did you expect to see?

5.What did you see instead?
2017/08/19 18:20:20 conn.go:341: �[0;31m[error] lastCmd select count(a.id) from shopping_goods a join shopping_store b
where a.goods_store_id=b.id
and 1=1
and b.store_status=2 and a.goods_status=0, runtime error: invalid memory address or nil pointer dereference, goroutine 39970 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420f05a20)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:339 +0xcd
panic(0x1022080, 0x1b9ff50)
/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pingcap/tidb/expression.(*Constant).Equal(0xc420cefec0, 0x189d9c0, 0xc420d28e00, 0x0, 0x0, 0xc421c092a8)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/expression/expression.go:338 +0x5d
github.com/pingcap/tidb/statistics.getMaskAndRanges(0xc420cef900, 0xc420e4a060, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0xc421c092a8, 0x1, ...)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/statistics/selectivity.go:168 +0x342
github.com/pingcap/tidb/statistics.(*Table).Selectivity(0xc42139ee80, 0x188eb60, 0xc420f05ad0, 0xc420e4a060, 0x2, 0x2, 0x6d66288a72, 0x0, 0xc421e783c0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/statistics/selectivity.go:104 +0x324
github.com/pingcap/tidb/plan.(*DataSource).getStatsProfileByFilter(0xc4218186c0, 0xc420e4a060, 0x2, 0x2, 0xc421e780d0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:82 +0x1da
github.com/pingcap/tidb/plan.(*DataSource).prepareStatsProfile(0xc4218186c0, 0x189b800)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:91 +0x53
github.com/pingcap/tidb/plan.(*LogicalJoin).prepareStatsProfile(0xc420ba1b00, 0x189c040)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:209 +0xe6
github.com/pingcap/tidb/plan.(*LogicalAggregation).prepareStatsProfile(0xc420e57b80, 0x189bec0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:183 +0x83
github.com/pingcap/tidb/plan.(*Projection).prepareStatsProfile(0xc421352a00, 0x0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/stats.go:170 +0x83
github.com/pingcap/tidb/plan.dagPhysicalOptimize(0x18a1a80, 0xc421352a00, 0xc421352a01, 0x188eb60, 0xc420f05ad0, 0xc421d2f1d8)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/optimizer.go:158 +0x4f
github.com/pingcap/tidb/plan.doOptimize(0x37, 0x18a1a80, 0xc421352a00, 0x188eb60, 0xc420f05ad0, 0xc421d2f1d8, 0x1, 0xc420c9d8c0, 0xc421c097f8, 0xd0d861)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/optimizer.go:128 +0xdd
github.com/pingcap/tidb/plan.Optimize(0x188eb60, 0xc420f05ad0, 0x18850e0, 0xc420fa0320, 0x7f4622bdf0e8, 0xc4204abad0, 0x0, 0x0, 0x1bb5b40, 0x7f4622c7b960)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/optimizer.go:85 +0x27f
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc421c098f0, 0x188eb60, 0xc420f05ad0, 0x7f4622bdf1a8, 0xc420fa0320, 0xc421c098f0, 0x486342, 0xc420487380, 0xc420cef900)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/executor/compiler.go:41 +0x1b7
github.com/pingcap/tidb.Compile(0x188eb60, 0xc420f05ad0, 0x7f4622bdf1a8, 0xc420fa0320, 0x4, 0x118a5ad, 0x8, 0xc421d75cb0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/tidb.go:150 +0x57
github.com/pingcap/tidb.(*session).Execute(0xc420f05ad0, 0xc420bf0ff1, 0xed, 0xc421c09bb8, 0x410aac, 0xc421c09bb8, 0x411082, 0xc420d55e98)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/session.go:641 +0x515
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc421f101e0, 0xc420bf0ff1, 0xed, 0x0, 0x0, 0xc421c09c88, 0x470548, 0xc42176bf18)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/driver_tidb.go:187 +0x62
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420f05a20, 0xc420bf0ff1, 0xed, 0x0, 0x0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:681 +0x8d
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420f05a20, 0xc420bf0ff1, 0xee, 0xed, 0x0, 0x0)
/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:470 +0x42e
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420f05a20)
/home

**Comment by zz-jason** [comment]
hi, @zwljava what tidb version are you using ?

you can run command: `./bin/tidb-server -V`

**Comment by zwljava** [comment]
Git Commit Hash: a0017eda04a1d48e9ec088457afe279a8cd064f4
UTC Build Time:  2017-08-18 10:35:56

**Comment by zwljava** [comment]
@zz-jason Git Commit Hash:   a0017eda04a1d48e9ec088457afe279a8cd064f4
UTC Build Time:  2017-08-18 10:35:56

**Comment by zz-jason** [comment]
can you provide the sql statement of creating table `shopping_goods` and `shopping_store` ?

**Comment by zwljava** [comment]
@zz-jason 
I recreate shopping_store ,then ok! 
I guess index error!
-----------------------------------------------
CREATE TABLE `shopping_store` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `addTime` datetime DEFAULT NULL,
  `deleteStatus` bit(1) NOT NULL,
  `card_approve` bit(1) NOT NULL,
  `realstore_approve` bit(1) NOT NULL,
  `store_address` varchar(255) DEFAULT NULL,
  `store_credit` int(11) NOT NULL,
  `store_info` longtext,
  `store_msn` varchar(255) DEFAULT NULL,
  `store_name` varchar(255) DEFAULT NULL,
  `store_ower` varchar(255) DEFAULT NULL,
  `store_ower_card` varchar(255) DEFAULT NULL,
  `store_qq` varchar(255) DEFAULT NULL,
  `store_recommend` bit(1) NOT NULL,
  `store_recommend_time` datetime DEFAULT NULL,
  `store_seo_description` longtext,
  `store_seo_keywords` longtext,
  `store_status` int(11) NOT NULL,
  `store_telephone` varchar(255) DEFAULT NULL,
  `store_zip` varchar(255) DEFAULT NULL,
  `template` varchar(255) DEFAULT NULL,
  `validity` datetime DEFAULT NULL,
  `violation_reseaon` longtext,
  `area_id` bigint(20) DEFAULT NULL,
  `card_id` bigint(20) DEFAULT NULL,
  `grade_id` bigint(20) DEFAULT NULL,
  `sc_id` bigint(20) DEFAULT NULL,
  `store_banner_id` bigint(20) DEFAULT NULL,
  `store_license_id` bigint(20) DEFAULT NULL,
  `store_logo_id` bigint(20) DEFAULT NULL,
  `update_grade_id` bigint(20) DEFAULT NULL,
  `domain_modify_count` int(11) DEFAULT '0',
  `store_second_domain` varchar(255) DEFAULT NULL,
  `favorite_count` int(11) DEFAULT '0',
  `store_lat` decimal(6,2) DEFAULT NULL,
  `store_lng` decimal(6,2) DEFAULT NULL,
  `store_ww` varchar(255) DEFAULT NULL,
  `map_type` varchar(255) DEFAULT 'baidu',
  `delivery_begin_time` datetime DEFAULT NULL,
  `delivery_end_time` datetime DEFAULT NULL,
  `combin_begin_time` datetime DEFAULT NULL,
  `combin_end_time` datetime DEFAULT NULL,
  `weixin_begin_time` date DEFAULT NULL,
  `weixin_end_time` date DEFAULT NULL,
  `weixin_status` int(11) DEFAULT '0',
  `weixin_appId` varchar(255) DEFAULT NULL,
  `weixin_appSecret` varchar(255) DEFAULT NULL,
  `weixin_token` varchar(255) DEFAULT NULL,
  `weixin_welecome_content` longtext,
  `weixin_qr_img_id` bigint(20) DEFAULT NULL,
  `weixin_account` varchar(255) DEFAULT NULL,
  `store_weixin_logo_id` bigint(20) DEFAULT NULL,
  `weixin_store_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `FK1A2E9F4AFA5E3FC2` (`area_id`),
  KEY `FK1A2E9F4A8D04BD7` (`update_grade_id`),
  KEY `FK1A2E9F4A33028121` (`grade_id`),
  KEY `FK1A2E9F4A11D81442` (`weixin_qr_img_id`),
  KEY `FK1A2E9F4A929E09BB` (`store_logo_id`),
  KEY `FK1A2E9F4A7CE341A` (`store_banner_id`),
  KEY `FK1A2E9F4A9A6FEF94` (`card_id`),
  KEY `FK1A2E9F4AC98DF95A` (`store_weixin_logo_id`),
  KEY `FK1A2E9F4A33F45DA9` (`sc_id`),
  KEY `FK1A2E9F4AA10642E1` (`store_license_id`)
) ENGINE=MyISAM AUTO_INCREMENT=32776 DEFAULT CHARSET=utf8;

**Comment by zz-jason** [comment]
@zwljava what do you mean "I guess index error!" ?

Is the schema of table `shopping_store` before recreating the same with the schema after you recreating ?

**Comment by zwljava** [comment]
@zz-jason 
I first create table shopping_store  in RC3,so run in rc3 is ok!
then I upgrade to rc4,so  run in rc4 is error!
but I recreate table  shopping_store in rc4,then is ok.

**Comment by zwljava** [comment]
@zz-jason schema  is same!

**Comment by zz-jason** [comment]
ok, thanks for your feed back

**Comment by shenli** [comment]
@zwljava  Fixed in #4257 .
