### ISSUE TITLE
support `GROUP BY` modifiers

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4250]
## Request Description

MySQL and Oracle support [`ROLLUP`](https://dev.mysql.com/doc/refman/5.7/en/group-by-modifiers.html) modifier, SQL Server also supports `CUBE` and `GROUPING SETS`

References:
- MySQL: [GROUP BY Modifiers](https://dev.mysql.com/doc/refman/5.7/en/group-by-modifiers.html)
- Oracle Database:
	- [ROLLUP Extension to GROUP BY](https://docs.oracle.com/en/database/oracle/oracle-database/20/dwhsg/sql-aggregation-data-warehouses.html#GUID-01BBD582-E149-47D7-A4F8-F50C1AAC66AA)
	- [CUBE Extension to GROUP BY](https://docs.oracle.com/en/database/oracle/oracle-database/20/dwhsg/sql-aggregation-data-warehouses.html#GUID-C5FDD050-DCE0-4FE1-9741-420E2F970A36)
	- [GROUPING Functions](https://docs.oracle.com/en/database/oracle/oracle-database/20/dwhsg/sql-aggregation-data-warehouses.html#GUID-E4251C0F-8AD7-4826-BE35-845E5CE6C818)
	- [GROUPING SETS Expression](https://docs.oracle.com/en/database/oracle/oracle-database/20/dwhsg/sql-aggregation-data-warehouses.html#GUID-166E1BFC-51C6-4BB5-B10B-A8EB63472E49)
- SQL Server: [SELECT - GROUP BY](https://docs.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql?view=sql-server-ver15)

An example in MySQL:

```sql
drop table if exists t;
create table t(a bigint, b bigint, c bigint);
insert into t values(1, 2, 3), (2, 2, 3), (3, 2, 3);
```

```sql
MySQL > select a, min(b) from t group by a with rollup;
+------+--------+
| a    | min(b) |
+------+--------+
|    1 |      2 |
|    2 |      2 |
|    3 |      2 |
| NULL |      2 |
+------+--------+
4 rows in set (0.01 sec)
```

## Category

Feature

## Value

- Value Point: 2

It's hard to tell the value for now. Quoted from https://docs.oracle.com/cd/F49540_01/DOC/server.815/a68003/rollup_c.htm:

> One of the key concepts in decision support systems is "multi-dimensional analysis": examining the enterprise from all necessary combinations of dimensions. We use the term "dimension" to mean any category used in specifying questions. Among the most commonly specified dimensions are time, geography, product, department, and distribution channel, but the potential dimensions are as endless as the varieties of enterprise activity. The events or entities associated with a particular set of dimension values are usually referred to as "facts." The facts may be sales in units or local currency, profits, customer counts, production volumes, or anything else worth tracking.

I think the value of this request is to improve the usability and performance in Business Intelligence(BI) scenarios. No need to run several aggregate queries to get another level aggregate result. I'm curious about whether are some BI tools rely on this feature.

### Workload Estimation

> Workload contains coding, documenting, and testing.
> 1 Point for 1 Person/Work Day

- 60 Points, hard to say, most modifications are on the aggregate operator in execution engine.

**Comment by Lloyd-longfei** [comment]
My  also encountered the same problem with TIDB, and when writing SQL, the following mistakes were made:
```
Error : line 83 column 35 near " rollup" (total length 3865) 
```
This problem may directly affect the running of our online production environment, when can you increase the function, or tell us how to solve the problem. @hanfei1991

**Comment by zz-jason** [comment]
@Lloyd-longfei Thanks for your feed back, I'm sorry to tell you that `group by ... with rollup` is not on our roadmap now, but we'll support it as soon as possible.

For now, a workaround it to write another sql to get the aggregation summary, see https://dev.mysql.com/doc/refman/5.7/en/group-by-modifiers.html for more detail.

**Comment by morgo** [comment]
Confirming that this feature is still missing:
```
mysql> select a, min(b) from t group by a with rollup;
ERROR 1105 (HY000): line 1 column 39 near " rollup" (total length 46)
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                      |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-rc.3-385-gbb0e7a18f
Git Commit Hash: bb0e7a18f63b12b167eb1c5ba58bcf4cb6ea7a1b
Git Branch: socket
UTC Build Time: 2018-12-29 10:14:15
GoVersion: go version go1.11.4 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by vkingnew** [comment]
this feature is still not support as tidb 2.1.6,and which version to support ROLLUP and CUBE
>mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.7
Git Commit Hash: f5b52cb9dc5a8a546121aa6ce1fc672bd567ca48
Git Branch: HEAD
UTC Build Time: 2019-03-28 07:54:41
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by vkingnew** [comment]
this feature is still not support as tidb 2.1.7,and which version to support ROLLUP and CUBE
>mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.7
Git Commit Hash: f5b52cb9dc5a8a546121aa6ce1fc672bd567ca48
Git Branch: HEAD
UTC Build Time: 2019-03-28 07:54:41
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by bhzhu203** [comment]
TiDB-v5.0.0 still does not support the "ROLLUP" fuction. Our product managers and staff managers like to write the BI statistics queries with the "ROLLUP" fuction , and hard to remove all of the "ROLLUP" from  the losts of queries . 
The replacement of the  "ROLLUP" fuction costs a lot. The "ROLLUP" fuction exists in our BI queries over 40% . We still using the slow mysql  instance because that. Hope TiDB will support "ROLLUP"  . Thanks
