### ISSUE TITLE
run sql: SHOW FUNCTION STATUS LIKE '%', runtime error: index out of range

### ISSUE THREAD

**Issue by zwljava** [pingcap/tidb#4255]
1. What did you do?
run sql:
SHOW FUNCTION STATUS LIKE '%'

2. What did you expect to see?

3. What did you see instead?
2017/08/20 17:42:33 printer.go:31: [0;37m[info] Welcome to TiDB.[0m
2017/08/20 17:42:33 printer.go:32: [0;37m[info] Version:[0m
2017/08/20 17:42:33 printer.go:33: [0;37m[info] Git Commit Hash: a0017eda04a1d48e9ec088457afe279a8cd064f4[0m
2017/08/20 17:42:33 printer.go:34: [0;37m[info] UTC Build Time:  2017-08-18 10:35:56[0m
time="2017-08-20T17:42:33+08:00" level=info msg="[pd] create pd client with endpoints [127.0.0.1:2379]" 
time="2017-08-20T17:42:33+08:00" level=info msg="[pd] leader switches to: http://127.0.0.1:2379, previous: " 
time="2017-08-20T17:42:33+08:00" level=info msg="[pd] init cluster id 6456282942390704370" 
2017/08/20 17:44:49 conn.go:341: [0;31m[error] lastCmd SHOW FUNCTION STATUS LIKE '%', runtime error: index out of range, goroutine 92410 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420887b80)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:339 +0xcd
panic(0x1022080, 0x1b9ff90)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/pingcap/tidb/plan.(*nameResolver).fillShowFields(0xc42170a690, 0xc420fae750)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/resolver.go:1020 +0x891
github.com/pingcap/tidb/plan.(*nameResolver).Enter(0xc42170a690, 0x18851a0, 0xc420fae750, 0xc4218da4a0, 0x5, 0xc4218da4a0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/resolver.go:243 +0x2597
github.com/pingcap/tidb/ast.(*ShowStmt).Accept(0xc420fae750, 0x187c8a0, 0xc42170a690, 0x5, 0xc4218da4a0, 0x5)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/ast/dml.go:989 +0x4b
github.com/pingcap/tidb/plan.ResolveName(0x18851a0, 0xc420fae750, 0x7f6d1313c5e8, 0xc4208de150, 0x188eb60, 0xc42164afd0, 0x40f700, 0x18851a0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/resolver.go:45 +0x171
github.com/pingcap/tidb/plan.Preprocess(0x18851a0, 0xc420fae750, 0x7f6d1313c5e8, 0xc4208de150, 0x188eb60, 0xc42164afd0, 0x0, 0xc42002a800)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/plan/preprocess.go:25 +0x61
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc421e298f0, 0x188eb60, 0xc42164afd0, 0x1887fe0, 0xc420fae750, 0xc421e298f0, 0x486342, 0xc42052dc80, 0xc4215c4ec0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/executor/compiler.go:34 +0xd7
github.com/pingcap/tidb.Compile(0x188eb60, 0xc42164afd0, 0x1887fe0, 0xc420fae750, 0x4, 0x118a5ad, 0x8, 0xc4218da4c0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/tidb.go:150 +0x57
github.com/pingcap/tidb.(*session).Execute(0xc42164afd0, 0xc42176ac21, 0x1d, 0xc421e29bb8, 0x410aac, 0xc421e29bb8, 0x411082, 0xc420a5f698)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/session.go:641 +0x515
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc420cdb7a0, 0xc42176ac21, 0x1d, 0x0, 0x0, 0xc421e29c88, 0x470548, 0xc421312778)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/driver_tidb.go:187 +0x62
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420887b80, 0xc42176ac21, 0x1d, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:681 +0x8d
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420887b80, 0xc42176ac21, 0x1e, 0x1d, 0x0, 0x0)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:470 +0x42e
github.com/pingcap/tidb/server.(*clientConn).Run(0xc420887b80)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/conn.go:361 +0x13c
github.com/pingcap/tidb/server.(*Server).onConn(0xc420c86230, 0x188d260, 0xc42114e5c8)
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/server.go:236 +0x148
created by github.com/pingcap/tidb/server.(*Server).Run
	/home/jenkins/workspace/build_tidb_rc4/go/src/github.com/pingcap/tidb/server/server.go:185 +0xc5

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: a0017eda04a1d48e9ec088457afe279a8cd064f4
UTC Build Time:  2017-08-18 10:35:56

**Comment by shenli** [comment]
@zwljava Thanks for your feedback!

**Comment by zwljava** [comment]
@shenli  if you use apache squirrel-sql,you will find more bug!

**Comment by breeswish** [comment]
more: show plugins like '%'

**Comment by hanfei1991** [comment]
fixed
