### ISSUE TITLE
COUNT is slower than before

### ISSUE THREAD

**Issue by neoremind** [pingcap/tidb#4258]
1. What did you do?
We setup a cluster to see if we can migrate our MySQL cluster into Tidb.
We have 4 VMs each with 4 cpu cores, 8G mem and 300GB disk, and setup 4 Tikv, 2 PD, 2Tidb, with a VIP LB in the front.

2. What did you expect to see?
We have a table with schema like below.
```
CREATE TABLE `task_run` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `task_id` int(11) NOT NULL,
  `created` datetime NOT NULL,
  `completed` datetime DEFAULT NULL,
  `success` int(11) NOT NULL,
  `related_info` text(65535) DEFAULT NULL,
  `result_info` text(65535) DEFAULT NULL,
  `task_group_run_id` int(11) NOT NULL,
  `task_group_run_name` varchar(255) DEFAULT NULL,
  `dump_output_root` varchar(511) DEFAULT NULL,
  `dump_synced` tinyint(1) DEFAULT NULL,
  `dump_pickedup` datetime DEFAULT NULL,
  `dump_pickedup_flag` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `task_run_backup_20170803_task_id` (`task_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1
```
we run a sql:
```
mysql> select count(*) from task_run_backup_20170803;
+----------+
| count(*) |
+----------+
|  1502788 |
+----------+
1 row in set (2.55 sec)
```
It takes 2.55 sec to get the result. While in our MySQL server, it takes only 400ms.

3. What did you see instead?
I think `count` operator works slower than before, it is because of the design of tidb to leverage multi kv storage and uses rocksdb, so that it does not support nature statistic info. 
But does tidb have plan to enhance the performance of count?

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: 0.8.0
Git Commit Hash: 0d27b1f49e596a071b24e2a88ff9a3994910e5d0
Git Commit Branch: master
UTC Build Time:  2017-08-17 01:49:52

**Comment by shenli** [comment]
@neoremind Please do not expect performance improvement on this size of data compared with MySQL.
But  you can do some tuning work to make TiDB faster. Please refer to https://github.com/pingcap/docs/blob/master/sql/tidb-specific.md#system-variable

**Comment by neoremind** [comment]
@shenli Thanks for your quick response! I tried to set `set @@tidb_distsql_scan_concurrency = 10` in session level, it seems not working any better, per the doc you paste:
```
Scope: SESSION | GLOBAL Default value: 10 This variable is used to set the concurrency of the scan operation. Use a bigger value in OLAP scenarios, and a smaller value in OLTP scenarios. For OLAP scenarios, the maximum value cannot exceed the number of CPU cores of all the TiKV nodes.
```
Do the value bound the tidb server cpu cores? or total tikv?

**Comment by shenli** [comment]
10 is the default value. You can set this to 30. For `select count(*) from task_run_backup_20170803;` the computation is performed mainly on TiKV.

**Comment by neoremind** [comment]
Sorry, the doc is perfect I didn't see clearly. Anyway, I get the use case. 
BTW, besides Tidb, I have curious question. For system like tidb, cockroachdb which leverages spanner paper, does this kind of OLAP related queries like COUNT, SUM drops performance as expected because of a tradeoff to some other aspects like scalability?  What if user can not bear the performance? Do you guys meet clients with such scenario much?

**Comment by shenli** [comment]
It depends on the size of data that your query touches.

**Comment by neoremind** [comment]
I see, the test case I listed above should be a table with more than 1,500,000 rows and more than 150MB total size in MySQL with innodb engine, plus the resources I have like 4 tikvs, that would be a potential limit and can not improve by simply increasing concurrency level. But this is a case by case scenario, depends on dataset and computation resources. does my understand right?

**Comment by shenli** [comment]
For data size of 150MB, MySQL could cache all the data in memory. So the computing should be very fast. TiDB will send request from tidb-server to tikv-server. The network cost should be considerable in this case.
If you increase data size to tens of millions, the ratio of network cost will be much lower. I think TiDB should beat MySQL in this scenario.

**Comment by neoremind** [comment]
@shenli Your explanation makes sense. Thanks for your response!
