### ISSUE TITLE
CAST('4.5' as signed) diferent from MySQL

### ISSUE THREAD

**Issue by hicqu** [pingcap/tidb#4263]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
SELECT CAST('4.5' as signed);
```

2. What did you expect to see?
```
4
```

3. What did you see instead?
```
5
```

4. What version of TiDB are you using (`tidb-server -V`)?
TiDB is master branch.

**Comment by XuHuaiyu** [comment]
In mysql 
+-----------+
| version() |
+-----------+
| 5.7.18    |
+-----------+

returns 5.
@hicqu

**Comment by jackysp** [comment]
```
mysql> select cast('4.5' as signed);
+-----------------------+
| cast('4.5' as signed) |
+-----------------------+
|                     4 |
+-----------------------+
1 row in set, 1 warning (0.01 sec)
mysql> select version();
+-----------+
| version() |
+-----------+
| 5.7.19    |
+-----------+
1 row in set (0.00 sec)
```
MySQL's rule is a mystery.

**Comment by hicqu** [comment]
Yes, I think ours behavior is better. What do you think? @XuHuaiyu
