### ISSUE TITLE
The etcd client to the registry of Pump/Drainer info does not use auto-sync and fails when the PD cluster address changed

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#42643]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start a TiDB cluster with 3 PDs ① ② ③ and a Pump connected
2. Scale-out 3 more PDs ④ ⑤ ⑥
3. Wait 31 seconds
4. Scale-in the original PDs ① ② ③
5. Wait 31 seconds
6. Run `SHOW PUMP STATUS;`

### 2. What did you expect to see? (Required)

We see the status of the pump at step 6

### 3. What did you see instead (Required)

Context deadline exceeded in `etcd.(*Client).List`

### 4. What is your TiDB version? (Required)

v4.0.14

**Comment by kennytm** [comment]
In #9575 we added `AutoSyncInterval` so the etcd client can automatically refresh the PD member list. But this change is never carried into the tidb-tools/tidb-binlog package (later merged into this repository):

https://github.com/pingcap/tidb/blob/10f00936b7c88ae7a62d39291b411abb5003c1aa/util/etcd/etcd.go#L81-L85

(This might also manifest in the "MySQL-compatible AUTO_INCREMENT" feature #38809)

https://github.com/pingcap/tidb/blob/00d48f90e6b19676e6d2a18242ede6c0f98f69f9/meta/autoid/autoid.go#L588-L591

While it is easy to just add back the option `AutoSyncInterval: 30 * time.Second` in, I think a bigger issue is why do we need to have 4 different etcd clients rather than sharing the same one with all the correct config :shrug:

**Comment by jackysp** [comment]
similar issue in other repos,
https://github.com/pingcap/tiflow/blob/b20e1cac3e8142f00665e2bdd4e513f4b2514c3c/dm/pkg/etcdutil/etcdutil.go#L62
https://github.com/pingcap/dm/blob/da80bda17dce4d44c2bd830b58d822dac544b08b/dm/worker/server.go#L107
https://github.com/pingcap/tiflow/blob/b20e1cac3e8142f00665e2bdd4e513f4b2514c3c/dm/ctl/common/util.go#L167
https://github.com/pingcap/dm/blob/da80bda17dce4d44c2bd830b58d822dac544b08b/pkg/etcdutil/etcdutil.go#L74

**Comment by jackysp** [comment]
Although the pump drainer has been maintained, it seems that other tool components (dm, cdc) may also have similar issues. Should we fix them all at once? @nongfushanquan @overvenus @lance6716

**Comment by niezefeng** [comment]
Besides @jackysp listed, the following links also forget to set `AutoSyncInterval`. PTAL

https://github.com/pingcap/tiunimanager/blob/be9cf6dc09231c7b89f0094eb9641e6cfe03bc48/library/framework/etcd_client.go#L57
https://github.com/pingcap/dumpling/blob/562cb6c021782ce3e35c279a611e7a381979acfd/v4/export/util.go#L37
https://github.com/pingcap/tidb-cloud-backup/blob/6dca4ec3989b7949c7938fc588a82747debea68c/pkg/etcdmanager.go#L86
https://github.com/pingcap/tidb/blob/be75669f68a2eda401b5ea239a9842fb0369f907/dumpling/export/util.go#L36
https://github.com/pingcap/tidb-binlog/blob/efb767b595bb15e97fadc0728d193488ef459ff0/pkg/etcd/etcd.go#L48
https://github.com/pingcap/tiflow/blob/7397cfddc88f0f03ee129b39c0aafe5402c4405f/engine/pkg/meta/internal/etcdkv/connection.go#L81
https://github.com/pingcap/etcdv3-gateway/blob/9ccf8914fa9e25446631474d89f5580717bc930b/gateway/gateway.go#L35
https://github.com/pingcap/dm/blob/f9b9ed298b614e13973cef00156fcd3657876585/pkg/etcdutil/etcdutil.go#L74
https://github.com/pingcap/tidb-tools/blob/45729968487c9b4aa5820b3c00326be0c9bb89d5/sync_diff_inspector/utils/pd.go#L73
https://github.com/pingcap/tidb-tools/blob/00998a9a4bfd08eb63449186d147b0e6bb1fea5d/pkg/etcd/etcd.go#L80
https://github.com/pingcap/tidb-operator/blob/ca5d2a512699f0f65b54d564ca7dd62d5f551f8e/pkg/binlog/binlog.go#L52
https://github.com/pingcap/tiup/blob/00a67b8f7115f4709a1ef0064df9b244ae1a5fc8/pkg/cluster/api/binlog.go#L44
https://github.com/pingcap/tiflow/blob/15afac079600c1bc781a6fbdf5da00e02edbd541/engine/executor/fakejob/worker.go#L197
https://github.com/pingcap/tiflow/blob/0eba78d6a440a95876585c11319135807ceb9224/pkg/cmd/factory/factory_impl.go#L112
https://github.com/pingcap/tiflow/blob/97664e66e63cab9bac24580a7c8eb8da1d70ca6a/cdc/server/server.go#L148
https://github.com/pingcap/tidb/blob/afc9ca40379c90305b1e8db19b15943f588c7ee1/meta/autoid/autoid.go#L588
https://github.com/pingcap/diag/blob/b05d398f11ad26fb395ed063dbdbe8c1557a54a1/pkg/models/tidbcluster.go#L688

**Comment by hawkingrei** [comment]
I think we can create a linter to found this problem.
