### ISSUE TITLE
tidb dumpling导出的数据增加列信息

### ISSUE THREAD

**Issue by WUWEI111222333** [pingcap/tidb#42656]
希望dumpling工具导出的insert into语句增加列信息，这样当上游数据结构变化时，如果下游的数据库不支持改变列顺序功能（比如databend），也能使用dumpling进行导出
![image](https://user-images.githubusercontent.com/35459358/228409364-2ca8b24d-3ffb-4f73-98fe-ef5088783128.png)

**Comment by lichunzhu** [comment]
You're welcome. Feel free to open this issue any time if this problem is still not solved.
