### ISSUE TITLE
jdbc 相同的配置写入mysql 主从 和 tidb 集群，jdbc写mysql 比tidb快三倍

### ISSUE THREAD

**Issue by yqzdy1207** [pingcap/tidb#42706]
## Enhancement
描述 ： jdbc 相同的配置写入mysql 主从 和 tidb 集群，jdbc写mysql 比tidb快三倍
增强jdbc写入功能 : 
![8ea26958e03e8b36b41e32e37f757e8](https://user-images.githubusercontent.com/33902141/228725747-9b3d07ca-ac2a-4b71-968a-f452ea426508.png)

**Comment by bb7133** [comment]
Hi @yqzdy1207 , thanks for submitting an issue, however:

1. English is required for TiDB community, could you please translate your issue to English?
2. Please provide a way to reproduce your performance issue of JDBC.
