### ISSUE TITLE
TestBenchPool hang forever with `-test.cpu 1`

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#42721]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
cd util/gpool/spmc
go test -test.cpu 1 -run TestBenchPool
```

### 2. What did you expect to see? (Required)

Test pass

### 3. What did you see instead (Required)

The test hang forever

The case is problematic with `-test.cpu 1`

**Comment by hawkingrei** [comment]
I think ```-test.cpu 1``` is just slow but it doesn't hang.

we can reduce the count of loop. if we change it as 5, it takes 16s to complete. this value is 500 now. It needs to take 26min to complete.

**Comment by tiancaiamao** [comment]
OK, it's not **hang forever**... it just hangs (long enough that no one can bear with).
