### ISSUE TITLE
Make TestParallelNormalFlow/TestParallelErrFlow stable

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#42791]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/21115/nodes/54/steps/59/log/?start=0

### 3. What did you see instead (Required)
```
    dispatcher_test.go:163: 
        	Error Trace:	disttask/framework/dispatcher/dispatcher_test.go:163
        	            				disttask/framework/dispatcher/dispatcher_test.go:174
        	            				disttask/framework/dispatcher/dispatcher_test.go:247
        	Error:      	Not equal: 
        	            	expected: 2
        	            	actual  : 3
        	Test:       	TestParallelNormalFlow
```

### 4. What is your TiDB version? (Required)

master

**Comment by Defined2014** [comment]
same as #42767, don't forget colse #42767
