### ISSUE TITLE
incorrect results of `show stats_meta`

### ISSUE THREAD

**Issue by yqzdy1207** [pingcap/tidb#42837]
## Bug Report

1. row_count < modify_count,和官网介绍不一致
![image](https://user-images.githubusercontent.com/33902141/230297565-d76653c6-c5b9-49b9-bdfc-3161d09c1305.png)

### 4. What is your TiDB version? (Required)
6.5.0

**Comment by aytrack** [comment]
Could you provide more info about this.
Did you do some delete before check the stats_meta.

**Comment by yqzdy1207** [comment]
没有

**Comment by Rustin170506** [comment]
Please provide a minimal reproduction case.
