### ISSUE TITLE
NgMonitoring not started yet.

### ISSUE THREAD

**Issue by mayangzz** [pingcap/tidb#42898]
## Bug Report

NgMonitoring not started yet.

### 1. Minimal reproduce step (Required)

I am using TiDB v6.5 and have deployed a cluster consisting of 3 TiDB nodes, 5 TiKV nodes, 1 PD node, and 1 monitoring node. Initially, I deployed the monitoring node separately and encountered an error message stating that 'NgMonitoring not started yet.' When I attempted to manually start ngmonitoring, I received the error message shown in the provided screenshot.
![49eaddf7-3506-43f7-9979-5102e555626f](https://user-images.githubusercontent.com/48407274/230879968-3b53ddfe-782a-470d-b119-b22f448b02e9.jpeg)

I have verified that the pd_servers setting in ngmonitoring.toml is configured with the addresses of other nodes, but the error message indicates that it is accessing 127.0.0.1. I suspect that there might be an issue with the configuration file not being read correctly.

To verify this issue, I redeployed the TiDB cluster and colocated the monitoring node with the PD node. I then manually started ngmonitoring, and it was successful. I suspect that there might be a problem with the configuration file not being read correctly, and that ngmonitoring was not started when Prometheus was started.

### 2. What did you expect to see? (Required)

Based on the above, I believe there is an issue with the configuration file reading and ngmonitoring is not self-starting in TiDB v6.5.0, or perhaps the method I am using is incorrect.

**Comment by mayangzz** [comment]
I've resolved the issue. After taking a closer look at the endpoints section in the ngmonitoring.toml configuration file, I realized that the nodes were listed in an array format, but there were no commas separating them. After adding the commas, I manually started ngmonitoring, and it worked properly.🤨🤨🤨

**Comment by aytrack** [comment]
So is this your own configuration error, not a tidb bug?

**Comment by jebter** [comment]
I will close it，if there are any updates, you can reopen it. You can ask new questions at https://ask.pingcap.com/ or https://asktug.com/ (Chinese) or https://ask.pingcap.com/(English)
