### ISSUE TITLE
Add MySQL datatype aliases serial, dec, fixed

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#429]
`serial` is an alias for BIGINT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE.

`dec` and `fixed` are alias for decimal.

**Comment by kennytm** [comment]
SERIAL is already supported by pingcap/parser#481, FIXED is supported by pingcap/parser#556, and DEC is an alias of DECIMAL even before `pingcap/parser` was split out.

```sql
mysql> create table a(a serial, b dec, c fixed);
Query OK, 0 rows affected (0.01 sec)

mysql> show create table a\G
*************************** 1. row ***************************
       Table: a
Create Table: CREATE TABLE `a` (
  `a` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `b` decimal(11,0) DEFAULT NULL,
  `c` decimal(11,0) DEFAULT NULL,
  UNIQUE KEY `a` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set (0.01 sec)
```

Since all datatypes listed here are supported I'm closing this issue as FIXED.
