### ISSUE TITLE
Behavior of UTC_DATE() is different from mysql

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#4293]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
select UTC_DATE();
select UTC_DATE() + 2;
```

2. What did you expect to see?
```
mysql> select UTC_DATE();
+------------+
| UTC_DATE() |
+------------+
| 2017-08-22 |
+------------+
1 row in set (0.00 sec)

mysql> select UTC_DATE() + 2;
+----------------+
| UTC_DATE() + 2 |
+----------------+
|       20170824 |
+----------------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
MySQL [(none)]> select UTC_DATE();
+------------+
| UTC_DATE() |
+------------+
| 2017-08-22 |
+------------+
1 row in set (0.00 sec)

MySQL [(none)]> select UTC_DATE() + 2;
+----------------+
| UTC_DATE() + 2 |
+----------------+
|           2019 |
+----------------+
1 row in set, 1 warning (0.00 sec)

```

4. What version of TiDB are you using (`tidb-server -V`)?
Git Commit Hash: 365e4ab491b683a69c2004f30b1ae4f86256e2ad
Git Commit Branch: master
UTC Build Time:  2017-08-16 01:24:27

**Comment by shenli** [comment]
@tshqin Thanks!
@tiancaiamao @XuHuaiyu PTAL

**Comment by zz-jason** [comment]
fixed after rewriting function UTC_DATE() in this pr #4206
