### ISSUE TITLE
”write to tikv with no leader returned“ if we meet NotLeader which is caused by on-going schedule

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#43055]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
it's a corner case, and not easy to reproduce in normal run, even with very large mount of data, below is the timeline which may trigger this case:
- before we pause scheduler by key-range for a region, there's ongoing schedule which'll not be interrupted by pause
- lightning start import, but got NotLeader from tikv when ingest, and the ongoing schedule changes leader and peer-list at same time, but lightning only update leader on this case:
https://github.com/pingcap/tidb/blob/477fbaf864e631f449aa1c69fd5c00df90780727/br/pkg/lightning/backend/local/region_job.go#L598
- then on retry write we fail on this error
https://github.com/pingcap/tidb/blob/477fbaf864e631f449aa1c69fd5c00df90780727/br/pkg/lightning/backend/local/region_job.go#L350-L351
https://github.com/pingcap/tidb/blob/477fbaf864e631f449aa1c69fd5c00df90780727/br/pkg/lightning/backend/local/region_job.go#L358-L363

**Comment by D3Hunter** [comment]
cc @lance6716

**Comment by D3Hunter** [comment]
5.4 don't has this problem since writeAndIngestByRange always retry on error even non-retriable

**Comment by lance6716** [comment]
> but got NotLeader from tikv

lightning get this error when write or ingest?

**Comment by D3Hunter** [comment]
on ingest. updated
