### ISSUE TITLE
write statements to read on TiFlash only in strict sql mode

### ISSUE THREAD

**Issue by gengliqi** [pingcap/tidb#43090]
## Enhancement

Since some functions in TiFlash do not obey strict sql mode in write statements and it's hard to fix them all quickly, currently, it is better to read on TiFlash for write statements only in strict sql mode.

**Comment by seiya-annie** [comment]
Upgrade branch meets this issue:
source: <7.1
target: >=7.1.0
blocking stage: post upgrade
workaround: Use set session to change sql mode in 7.1 and later , or use set_var hint to change sql mode in 7.5 and later
