### ISSUE TITLE
Refine the naming of FieldType and Tp

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#4310]
Tp is referring to `FieldType.Tp` but it is also a acronym for Type, which is confusing for others. In addition, `evalTp` can be refined as well.

**Comment by zz-jason** [comment]
any ideas ?

**Comment by breeswish** [comment]
idea: FieldType -> DataType, Tp -> TypeName (it's type can be called DataTypeName)

**Comment by breeswish** [comment]
@XuHuaiyu PTAL

**Comment by zz-jason** [comment]
how about keep the name of `FieldType`, but change `FieldType.Tp` to `FieldType.MetaTp` ?

**Comment by breeswish** [comment]
I think we need to entirely avoid `Tp` in the field name, because we usually use Tp as a acronym for `Type` in variable names.

**Comment by XuHuaiyu** [comment]
For my part, I think we may refine evalTp which is not really explicit, 
but it's not really necessary to rename FieldType.Tp
which is readable to some extent.
