### ISSUE TITLE
upgrade from 6.1 to 6.5 will be  blocked when `server-version` is set in configuration file

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#43237]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. setup a cluster with 2 tidb (verson 6.1) nodes with custom version using `server-version` in config file
2. upgrade one tidb node to 6.5
3. upgrade will be blocked

### 2. What did you expect to see? (Required)

upgrade success

### 3. What did you see instead (Required)

upgrade blocked

**Comment by Benjamin2037** [comment]
After discussion, we will add a note on doc first, https://github.com/pingcap/docs-cn/pull/14569, And will refactor the code later.

**Comment by JasonWu0506** [comment]
why this bug has been fixed? if it is a doc change and decided not to fix, then we could have doc pr as fixing PR and close it properly
