### ISSUE TITLE
br: make some enhancements for checkpoint for backup/restore

### ISSUE THREAD

**Issue by Leavrth** [pingcap/tidb#43270]
## Enhancement
- [ ] No need to loads schemas from `backupSchema` every time. It can be moved into `client.InitSchemasReplaceForDDL`.
```Go
	// get full backup meta to generate rewrite rules.
	fullBackupTables, err := initFullBackupTables(ctx, cfg)
	if err != nil {
		return errors.Trace(err)
	}

	newTask := true
	if taskInfo != nil && taskInfo.Progress == checkpoint.InLogRestoreAndIdMapPersist {
		newTask = false
	}
	// get the schemas ID replace information.
	schemasReplace, err := client.InitSchemasReplaceForDDL(ctx, &restore.InitSchemaConfig{
		IsNewTask:       newTask,
		HasFullRestore:  len(cfg.FullBackupStorage) > 0,
		TableFilter:     cfg.TableFilter,
		TiFlashRecorder: cfg.tiflashRecorder,
		Tables:          fullBackupTables,
	})
```

- [ ] Support `--use-backupmeta-v2` when use checkpoint for backup. Currently to use less memory, we need to use backupmeta-v2 and it's better use checkpoint both.
- [ ] A better PD-scheduler config restore. Sometimes the user would give up the snapshot restore, the pd scheduler config would not be restored. Then when the user do the another restore, br saved the current not-restored pd scheduler config as original config.
- [ ] A better info when skip snapshot restore. BR should print this information to output.
- [ ] Add failpoints to make the test more deeply.
- [ ] Ensure `--use-checkpoint=false` available with `pitr-id-maps`.
- [ ] Clear the checkpoint information when the backup/restore finished. #43337 
- [ ] `pitr-id-maps` can be skipped when it is not the first execution.
- [ ] Currently when the snapshot restore failed, the checksum worker won't exited immediately, so don't close the checkpoint runner if there is an error.

**Comment by tonyxuqqi** [comment]
@Leavrth “ Support --use-backupmeta-v2 when use checkpoint for backup. Currently to use less memory, we need to use backupmeta-v2 and it's better use checkpoint both.”
I think use-backupmeta-v2 is not a good parameter name. Maybe just rename it to --use-checkpoint instead.

**Comment by Leavrth** [comment]
> @Leavrth `“ Support --use-backupmeta-v2 when use checkpoint for backup. Currently to use less memory, we need to use backupmeta-v2 and it's better use checkpoint both.”` I think use-backupmeta-v2 is not a good parameter name. What's the major improvement in backupmeta-v2 and we may just highlight the improvement in the naming.

@tonyxuqqi This is an experimental feature that already exist in v5.
backupmetaV1 saves all the schema infos in the memory at first, and then flush them into the external storage. 
backupmetaV2 limits the memory usage, so the schema infos are saved in many blocks, whose size is at most 128 MiB. When the size of one block exceeds the limit, the block would be flushed into external storage. Therefore, the memory usage can be limited to a fixed size.
