### ISSUE TITLE
building on virtual machine

### ISSUE THREAD

**Issue by b4nganto** [pingcap/tidb#4329]
hi all,
this is great, a lot of thank you for your great work. i have plan to run tidb/tikv/pd on our virtual environment. it is for non-production purpose.

1. What did you do?
If possible, provide a recipe for reproducing the error.

1. is it possible to run all component on the top of virtual machine.
2. if i run tidb/tikv/pd on the top of virtual machine, is it to keep following this recommendation? for cpu, mem and disk configuration. https://pingcap.com/doc-recommendation

2. What did you expect to see?

  my testing project run successfully.

3. What version of TiDB are you using (tidb-server -V)?

lastest release candidate.

thanks,
B4

**Comment by flochman** [comment]
I tried deploy TiDB on 5 virtualbox instances - nodes on Intel i5 but failed. Minimum mem requirements is 1260 MB.

**Comment by shenli** [comment]
@b4nganto You can get every document you need here: https://github.com/pingcap/docs
We do not encourage you to deploy tikv-server on virtual machine. Because tikv-server is very disk IO io intensive. The performance of disk is critical. 
For tidb-server, it is OK to be deployed in virtual machine.

**Comment by shenli** [comment]
@flochman Do you meet any problem?

**Comment by flochman** [comment]
@shenli 

Yes, I meet problems. 

I installed on Debian Stretch.

With TiDB-Ansible deploy I had not installed curl but Ansible outbound network check in local_prepare.yml  was passed as OK, but download of the binary did not started.

I needed install curl tool. It was nowhere mentioned that is needed curl tool for ansible deploy.

I am from Europe and network connection to China is slower, so I need to add timeout=500 flag to the file:

tidb-ansible-master/roles/local/tasks/main.yml

for example


name: download preGA tikv binary
  get_url: url=http://pingcap-dev.hk.ufileos.com/builds/pingcap/tikv/{{ tikv_sha1 }}/centos7/tikv-server.tar.gz dest={{ downloads_dir }}/tikv-server.tar.gz force=yes validate_certs=no timeout=500
  when: has_outbound_network

- name: download other binary
  get_url: url={{ item.url }} dest={{ downloads_dir }}/{{ item.name }}-{{ item.version }}.tar.gz validate_certs=no timeout=500
  with_items: "{{ third_party_packages }}"
  when: has_outbound_network and not under_gfw

I had convinced that TiKV-server is very disk IO io intensive and sensitive. This is probably the reason why my virtualbox instances did not run.

I did ansible local_prepare.yml, bootstrap.yml and deploy.yml with success.

I failed on start.yml when tikv servers did not answered.

**Comment by shenli** [comment]
@LinuxGit PTAL

**Comment by LinuxGit** [comment]
@flochman Sorry, we haven't tested it on Debian, CentOS 7 is recommended. We'll add curl dependency in doc. You can run start_tikv.sh in {{ deploy_dir }}/scripts and check tikv.log or tikv_stderr.log in {{ deploy_dir }}/log manully.

**Comment by b4nganto** [comment]
@shenli ok.. noted for disk io intensive. thank you very much shenli.
