### ISSUE TITLE
Query with CTE failed to recognize tmp table

### ISSUE THREAD

**Issue by fixdb** [pingcap/tidb#43318]
### 1. Minimal reproduce step (Required)
```sql
with base0 as (select 1 as a)
	,base1 as (
	WITH RECURSIVE cte(a) AS 
	(
	 with tmp as (select 1 as a)
	 SELECT a from tmp 
	 UNION 
	 SELECT a+1 FROM cte WHERE a < 5
	) 
	 SELECT * FROM cte
)
select *
from base0, base1
where base0.a = base1.a;
```
### 2. What did you expect to see? (Required)
```
+---+------+
| a | a    |
+---+------+
| 1 |    1 |
+---+------+
```

### 3. What did you see instead (Required)
```
ERROR 1146 (42S02): Table '.tmp' doesn't exist
```
### 4. What is your TiDB version? (Required)
master
6.1.2可以正常运行， 6.5.1/6.5.2 都报错。

**Comment by fixdb** [comment]
It is a critical issue, I believe it is a regression.

**Comment by elsa0520** [comment]
Please assign to me

**Comment by elsa0520** [comment]
I try to inline tmp table manually and the result is correct.
```
with base0 as (select 1 as a)
	,base1 as (
	WITH RECURSIVE cte(a) AS 
	(
	 SELECT a from (select 1 as a) tmp
	 UNION 
	 SELECT a+1 FROM cte WHERE a < 5
	) 
	 SELECT * FROM cte
)
select *
from base0, base1
where base0.a = base1.a;
```

So the tmp could be inline, the strategy of ```single-consume default inline``` is correct.

The main error is the implementation of tidb inline itself.

**Comment by elsa0520** [comment]
The main reason is "with a(with recursive b(with c )) select xxx from a" the outer with is inline.
1. The ```with c``` will be removed incorrectly when the outer b is a recursive cte. And the query will be changed as following:
```
with  base1 as (
	WITH RECURSIVE cte(a) AS 
	(
 //    with tmp as (select 1 as a) this line has been removed incorrectly
	 SELECT a from tmp
	 UNION 
	 SELECT a FROM cte
	) 
	 SELECT * FROM cte
)
```
2. The inline cte will be built twice. This first time is ```build cte base 1``` . The second time is ```build from clause base1```. Due to ```with tmp xxx``` has been removed at the first time, the second time about ```build from clause base 1``` will be error.

**Comment by elsa0520** [comment]
So triggering this bug requires two necessary conditions
1. A with recursive statement is declared and there is a with clause inside the statement. For example: ```with recursive (with tmp xxx)
2. The with recursive statement will be constructed repeatedly, for example, it is wrapped in the third inline cte.

**Comment by elsa0520** [comment]
The first build remove the with clause incorrectly.
![image](https://user-images.githubusercontent.com/111482174/233929017-5c69b3ed-fa14-4cf5-8173-187a06f8d9fb.png)

**Comment by elsa0520** [comment]
The second build :
![image](https://user-images.githubusercontent.com/111482174/233929392-06aeb6a3-7e97-4284-8001-4b50c447d0d1.png)
