### ISSUE TITLE
Unexpected results of subquery in `INSERT`

### ISSUE THREAD

**Issue by DerZc** [pingcap/tidb#43373]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Consider the following program:

```
CREATE TABLE t0(c0 BOOL, c1 BIGINT NOT NULL , c2 INTEGER  AUTO_INCREMENT );

INSERT INTO t0(c0, c1) VALUES (1, 1);

SELECT temp_table1.c0 AS c0, t0.c0 AS c1 FROM t0, (SELECT t0.c1 AS c0, t0.c2 AS c1, t0.c0 AS c2 FROM t0 WHERE t0.c2) AS temp_table1 WHERE ((VERSION())>=(temp_table1.c0));

CREATE TABLE temp_table2 (c0 INT, c1 BOOL);
INSERT INTO temp_table2 SELECT temp_table1.c0 AS c0, t0.c0 AS c1 FROM t0, (SELECT t0.c1 AS c0, t0.c2 AS c1, t0.c0 AS c2 FROM t0 WHERE t0.c2) AS temp_table1 WHERE ((VERSION())>=(temp_table1.c0));
SELECT * FROM temp_table2;
```
The first query returns one row:
```
c0      c1
1       1
```
I use the first query as a subquery in `INSERT` statement and get a new table `temp_table2`, but this table is empty, and the second `SELECT` query has empty results.

### 2. What did you expect to see? (Required)
The second query also returns one row.

### 3. What did you see instead (Required)
The second query has empty results.

### 4. What is your TiDB version? (Required)
```
Release Version: v7.2.0-alpha-18-geff3a8faf\nEdition: Community\nGit Commit Hash: eff3a8faf417665a0499febc20cdb0eb7b341535\nGit Branch: master\nUTC Build Time: 2023-04-24 10:56:14\nGoVersion: go1.20.3\nRace Enabled: false\nTiKV Min Version: 6.2.0-alpha\nCheck Table Before Drop: false\nStore: unistore
```

**Comment by yibin87** [comment]
There are warnings generated during the select query:
mysql> SELECT temp_table1.c0 AS c0, t0.c0 AS c1 FROM t0, (SELECT t0.c1 AS c0, t0.c2 AS c1, t0.c0 AS c2 FROM t0 WHERE t0.c2) AS temp_table1 WHERE ((VERSION())>=(temp_table1.c0));
+----+------+
| c0 | c1   |
+----+------+
|  1 |    1 |
+----+------+
1 row in set, 2 warnings (0.01 sec)

mysql> show warnings;
+---------+------+----------------------------------------------------------------------------+
| Level   | Code | Message                                                                    |
+---------+------+----------------------------------------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: '8.0.11-TiDB-v8.2.0-alpha-6-g8f138d5113' |
| Warning | 1292 | Truncated incorrect DOUBLE value: '8.0.11-TiDB-v8.2.0-alpha-6-g8f138d5113' |
+---------+------+----------------------------------------------------------------------------+
2 rows in set (0.00 sec)

**Comment by yibin87** [comment]
Currently, we will reject such insert select statement if select statement generate warnings.
