### ISSUE TITLE
dr-autosync: after switch to backup cluster in sync_recover mode, flashback to min-resolved-ts failed

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb#43386]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. During dr-autosync cluster running in sync_recover mode, shutdown the primary DC, switch to backup DC;
2. Get min-resolved-ts as follows:
```
tiup ctl:v6.5.1 pd -u http://pd3-peer.e2e-oltp-tiup-dr-auto-sync-3r-tps-1666585-1-567:2379/ min-resolved-ts
\"min_resolved_ts\": 440986319057584310
```
4. Parser the ts to timestamp
```
  MySQL [(none)]> SELECT TIDB_PARSE_TSO(440986334746902656);
  +------------------------------------+
  | TIDB_PARSE_TSO(440986334746902656) |
  +------------------------------------+
  | 2023-04-23 13:56:05.337000         |
  +------------------------------------+
  1 row in set (0.001 sec)
```
5. flashback the cluster to min-resolved-ts
```
MySQL [(none)]> FLASHBACK CLUSTER TO TIMESTAMP '2023-04-23 13:56:05.337000';
ERROR 1105 (HY000): cannot set flashback timestamp after min-resolved-ts(2023-04-23 13:46:09.837 +0800 CST)
```

### 2. What did you expect to see? (Required)
flashback works fine.

### 3. What did you see instead (Required)
flashback failed.

### 4. What is your TiDB version? (Required)
v6.5.1

**Comment by JmPotato** [comment]
The root cause here is that if TiDB failed to connect a TiKV store to fetch the latest `resolved_ts`, it will remain the out-of-dated value until the TiKV comes back, though PD will mark the store as unavailable and keep updating the minimal `resolved_ts` with other TiKV stores. We may need to keep these two behaviors the same or unify them.
