### ISSUE TITLE
when analyze a table,tidb return assertion error

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#43424]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. analyze table

### 3. What did you see instead (Required)
Error 8141: assertion failed: key: 7480000000000000145f69800000000000000104061926b21bbc208a0380000000000dc68a, assertion: Exist, start_ts: 441046127862612190, existing start ts: 0, existing commit ts: 0
### 4. What is your TiDB version? (Required)

Release Version: v7.1.0
Edition: Community
Git Commit Hash: c65e6ac233cf35d655ac13e94bda1988410be18c
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-04-21 02:36:25
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by xuyifangreeneyes** [comment]
maincluster-tidb-peer.stable-testbed-47l4r.svc:4000[conn.go:1151] ["command dispatched failed"] [conn=8509445942800322567] [connInfo="id:8509445942800322567, addr:10.233.91.64:8528 status:10, collation:utf8mb4_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="analyze table stock"] [txn_mode=PESSIMISTIC] [timestamp=441045744699834411] [err="[tikv:8141]assertion failed: key: 7480000000000000145f69800000000000000104061926b21bbc208a0380000000000dc68a, assertion: Exist, start_ts: 441046127862612190, existing start ts: 0, existing commit ts: 0
github.com/pingcap/errors.AddStack
	/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174
github.com/pingcap/errors.(*Error).GenWithStackByArgs
	/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/normalize.go:164
github.com/pingcap/tidb/session.(*session).handleAssertionFailure
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:732
github.com/pingcap/tidb/session.(*session).doCommit
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:675
github.com/pingcap/tidb/session.(*session).doCommitWithRetry
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:926
github.com/pingcap/tidb/session.(*session).CommitTxn
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1053
github.com/pingcap/tidb/session.autoCommitAfterStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/tidb.go:297
github.com/pingcap/tidb/session.finishStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/tidb.go:259
github.com/pingcap/tidb/session.runStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2369
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2207
github.com/pingcap/tidb/session.(*session).ExecuteInternal
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:1626
github.com/pingcap/tidb/statistics/handle.finishTransaction
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/ddl.go:349
github.com/pingcap/tidb/statistics/handle.SaveTableStatsToStorage.func2
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:1365
github.com/pingcap/tidb/statistics/handle.SaveTableStatsToStorage
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:1502
github.com/pingcap/tidb/statistics/handle.(*Handle).SaveTableStatsToStorage
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/statistics/handle/handle.go:1339
github.com/pingcap/tidb/executor.(*AnalyzeExec).handleResultsError
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/analyze.go:319
github.com/pingcap/tidb/executor.(*AnalyzeExec).Next
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/analyze.go:186
github.com/pingcap/tidb/executor.Next
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/executor.go:326
github.com/pingcap/tidb/executor.(*ExecStmt).next
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1194
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:939
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelay
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:764
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:564
github.com/pingcap/tidb/session.runStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2350
github.com/pingcap/tidb/session.(*session).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2207
github.com/pingcap/tidb/server.(*TiDBContext).ExecuteStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/driver_tidb.go:252
github.com/pingcap/tidb/server.(*clientConn).handleStmt
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:2061
github.com/pingcap/tidb/server.(*clientConn).handleQuery
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1852
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1339
github.com/pingcap/tidb/server.(*clientConn).Run
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1120
github.com/pingcap/tidb/server.(*Server).onConn
	/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:677
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1598
previous statement: update mysql.stats_histograms set last_analyze_pos = _binary'\u0003?\\0\\0\\0\\0\\0\u0007?\u0003?\\0\\0\\0\\0\u0001Xs' where table_id = 36495 and is_index = 1 and hist_id = 1"]

**Comment by bb7133** [comment]
Hi @AkiraXie , thanks for reporting this issue, but:

### 1. Minimal reproduce step (Required)
analyze table

This is *not* a reproduce step. "Reproduce Step" is about how the others can reproduce this issue, rather than how *you triggered this issue*.

**Comment by AkiraXie** [comment]
@bb7133 tidb cluster has run for months, the issue is from  mysql.stats_meta data inconsistency. but how to reproduce the issue is a myth, we are doing research on it

**Comment by MyonKeminta** [comment]
There's data inconsistency in mysql.stats_meta in that cluster.

The table's first two columns are `version bigint unsigned, table_id bigint`, but the corrupted row and one of its index keys seem to be encoded in format of `version bigint, table_id bigint unsigned`. It looks like that in some rare cases, the column type definition may be used in wrong order. Perhaps the column info array is accessed with wrong index.

I failed to reproduce the problem or find anything wrong from the code.

**Comment by xuyifangreeneyes** [comment]
Downgrade to major since we don't find a way to reproduce it.

**Comment by fixdb** [comment]
@chrysan Can you help close this issue? since it can be reproduced.
