### ISSUE TITLE
 Lightning does not use auto-sync and fails when the PD cluster address changed

### ISSUE THREAD

**Issue by lichunzhu** [pingcap/tidb#43436]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Start a TiDB cluster with 3 PDs ① ② ③ and a Lightning connected
2. Scale-out 3 more PDs ④ ⑤ ⑥
3. Wait 31 seconds
4. Scale-in the original PDs ① ② ③
5. Wait 31 seconds
6. Keep Lightning running.

### 2. What did you expect to see? (Required)

We make sure lightning succeed.

### 3. What did you see instead (Required)

Lightning will fail in some cases due to no valid pd-addr.

### 4. What is your TiDB version? (Required)

master

**Comment by lance6716** [comment]
many PD address usage not removed
