### ISSUE TITLE
TiDB doesn't sanitize the query content when logging failed query in the compile stage

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#43452]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/6.5/session/session.go#L2192

### 2. What did you expect to see? (Required)
Log the sanitized query content

### 3. What did you see instead (Required)
the original query content

### 4. What is your TiDB version? (Required)
6.5.0

**Comment by jackysp** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/41831
