### ISSUE TITLE
support `EXPLAIN [options] FOR CONNECTION connection_id`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4351]
support obtaining the execution plan for an explainable statement executing in a named connection by using this statement:

```sql
EXPLAIN [options] FOR CONNECTION connection_id;
```

> Because of changes to data (and supporting statistics) it may produce a different result from running EXPLAIN on the equivalent query text. This difference in behavior can be useful in diagnosing more transient performance problems. For example, **if you are running a statement in one session that is taking a long time to complete, using EXPLAIN FOR CONNECTION in another session may yield useful information about the cause of the delay.**

reference: [8.8.4 Obtaining Execution Plan Information for a Named Connection](https://dev.mysql.com/doc/refman/5.7/en/explain-for-connection.html)

**Comment by morgo** [comment]
Confirming that this feature request is still current:
```
mysql> explain for connection 3;
ERROR 1105 (HY000): line 1 column 11 near " connection 3" (total length 24)
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-305-gef0ad26da
Git Commit Hash: ef0ad26da8f99044a741fc0a781a0c4791446e8b
Git Branch: newmaster
UTC Build Time: 2018-12-10 05:50:33
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by zz-jason** [comment]
It's already supported since TiDB 3.0
