### ISSUE TITLE
is tidb support mysql multi hosts?

### ISSUE THREAD

**Issue by shalk** [pingcap/tidb#43546]
hi,all

i  see tidb compatible with mysql in most case.

But i am not sure  if tidb support mysql multi hosts url ?

 like

```
jdbc:mysql://[primary host][:port],[secondary host 1][:port][,[secondary host 2][:port]]...[/[database]]»
[?propertyName1=propertyValue1[&propertyName2=propertyValue2]...]
```

https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-config-failover.html

**Comment by dveeden** [comment]
When using MySQL Connector/J with multiple hosts you probably should try `jdbc:mysql:loadbalance://...` as all TiDB nodes are writable so there is no need or primary(rw)/secondary(ro) etc.
