### ISSUE TITLE
getFuncCallDefaultValue parse date_format function

### ISSUE THREAD

**Issue by livepo** [pingcap/tidb#43557]
## Enhancement

make getFuncCallDefaultValue parse date_format function so that a table cound have a default function value.

such as: create table blog(pubdate char(8) default date_format(current_date, '%Y%m%d'));

**Comment by mjonss** [comment]
What is the use case for this enhancement? Why not have a proper date column, and do the formatting either in the query or on the client side? Also this would need to update the manual and possibly need a feature flag, to handle this non-MySQL compatible extension.

**Comment by Defined2014** [comment]
Haven't updated for a long time, close this issue
