### ISSUE TITLE
br backup to ks3 failed

### ISSUE THREAD

**Issue by jebter** [pingcap/tidb#43581]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tiup br:v7.1.0-rc.0 backup full --storage="s3://xxxxxx/backup?access-key=xxxxx&secret-access-key=xxxxxxx&endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com&force-path-style=true" --pd=127.0.0.1:2379

Starting component `br`: /home/tidb/.tiup/components/br/v7.1.0-rc.0/br backup full --storage=s3://.../backup?access-key=......&secret-access-key=....&endpoint=http%3a%2f%2fks3-cn-beijing-internal.ksyuncs.com&force-path-style=true --pd=127.0.0.1:2379
Detail BR log in /tmp/br.log.2023-05-06T16.53.39+0800
[2023/05/06 16:53:40.600 +08:00] [INFO] [collector.go:73] ["Full Backup failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: failed to get region of bucket xxxxxx: Forbidden: Forbidden
	status code: 403, request id: fvf..........i0e, host id:

### 2. What did you expect to see? (Required)
backup successful
### 3. What did you see instead (Required)
Backup failed
### 4. What is your TiDB version? (Required)

Release Version: v7.1.0-rc.0
Git Commit Hash: ba71c5fcedf6da2ec68759513493b7484e2e97b5
Git Branch: heads/refs/tags/v7.1.0-rc.0
Go Version: go1.20.3
UTC Build Time: 2023-04-22 10:01:17
Race Enabled: false

**Comment by jebter** [comment]
The third level domain has the same problem：
tiup br:v7.1.0-rc.0 backup full --storage="s3://xxxx/backup?access-key=xxxx&secret-access-key=xxxxxx&endpoint=http%3a%2f%2fxxxx.ks3-cn-beijing-internal.ksyuncs.com&force-path-style=true" --pd=127.0.0.1:2379
Starting component `br`: /home/tidb/.tiup/components/br/v7.1.0-rc.0/br backup full --storage=s3://..../backup?access-key=.......&secret-access-key=......&endpoint=http%3a%2f%2f.......ks3-cn-beijing-internal.ksyuncs.com&force-path-style=true --pd=127.0.0.1:2379
Detail BR log in /tmp/br.log.2023-05-06T17.01.46+0800
[2023/05/06 17:01:47.696 +08:00] [INFO] [collector.go:73] ["Full Backup failed summary"] [total-ranges=0] [ranges-succeed=0] [ranges-failed=0]
Error: failed to get region of bucket qe-testing: NotFound: Not Found
	status code: 404, request id: fvfv.............25, host id:

**Comment by 3pointer** [comment]
it looks like ks3 doesn't support get region via bucket by `GetBucketRegionWithClient`. you can try add `--s3.provider="ks3"` and specify the region with `--s3.region` to workaround

**Comment by jebter** [comment]
this works：
Starting component `br`: /home/tidb/.tiup/components/br/v7.1.0-rc.0/br backup full --storage=s3://backup?access-key=xxxxxx&secret-access-key=xxxxxx&endpoint=http%3a%2f%2fxxxxxx.ks3-cn-beijing-internal.ksyuncs.com&force-path-style=true&region=Beijing --pd=127.0.0.1:2379 --s3.provider=ks
Detail BR log in /tmp/br.log.2023-05-06T17.15.32+0800
Full Backup <----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> 100.00%
Checksum <-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------> 100.00%
[2023/05/06 17:15:39.580 +08:00] [INFO] [collector.go:73] ["Full Backup success summary"] [total-ranges=49] [ranges-succeed=49] [ranges-failed=0] [backup-checksum=226.675579ms] [backup-fast-checksum=9.956016ms] [backup-total-ranges=116] [total-take=7.084790191s] [BackupTS=441283912312815617] [total-kv=796179] [total-kv-size=119.3MB] [average-speed=16.83MB/s] [backup-data-size(after-compressed)=53.44MB] [Size=53441637]
