### ISSUE TITLE
fake block when rename index

### ISSUE THREAD

**Issue by wengsy150943** [pingcap/tidb#43650]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

init schema:

```
create table table0 (a int);
alter table table0 add index idx0 (a);
```

create 3 sessions and execute queries below:

```
session1 > begin;
session1 > show create table table0;
session2 > alter table table0 rename index idx0 to idx1; -- blocked
session3 > show create table table0;
```

### 2. What did you expect to see? (Required)

initial schema with index name idx0, since the ddl in session2 is blocked, i.e., :

```
+--------+------------------------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                                       |
+--------+------------------------------------------------------------------------------------------------------------------------------------+
| table0 | CREATE TABLE `table0` (
  `a` int(11) DEFAULT NULL,
  KEY `idx0` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+--------+------------------------------------------------------------------------------------------------------------------------------------+
```

### 3. What did you see instead (Required)

changed schema with index name idx1:

```
+--------+------------------------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                                       |
+--------+------------------------------------------------------------------------------------------------------------------------------------+
| table0 | CREATE TABLE `table0` (
  `a` int(11) DEFAULT NULL,
  KEY `idx1` (`a`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+--------+------------------------------------------------------------------------------------------------------------------------------------+
```

Then try to abort ddl in session2 by ctrl+c, shows ` -- query aborted`. But when commit the transaction in session1, then session2 displays `Query OK, 0 rows affected (5 min 29.19 sec)` and `show create table table0;` still shows the changed schema.

### 4. What is your TiDB version? (Required)

| Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

**Comment by seiya-annie** [comment]
duplicate with https://github.com/pingcap/tidb/issues/43652?

**Comment by Defined2014** [comment]
This is expected, the specific explanation can be found at https://github.com/pingcap/tidb/issues/43730
