### ISSUE TITLE
Blocked rename index is not compatible with mysql5.7

### ISSUE THREAD

**Issue by wengsy150943** [pingcap/tidb#43652]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

init schema:

```
create table table0 (a int);
alter table table0 add index idx0 (a);
```

create 2 sessions and execute queries below:

```
session1 > begin;
session1 > show create table table0;
session2 > alter table table0 rename index idx0 to idx1; -- blocked
```

### 2. What did you expect to see? (Required)

The `rename index` ddl in session2 will not be blocked, as the performance in MySQL5.7.

### 3. What did you see instead (Required)

`rename index` is blocked.

It seems that this ddl is not blocked in fact but CLI displays as it is blocked. As [issue43650](https://github.com/pingcap/tidb/issues/43650) shows.

### 4. What is your TiDB version? (Required)

| Release Version: v6.5.0
Edition: Community
Git Commit Hash: 706c3fa3c526cdba5b3e9f066b1a568fb96c56e3
Git Branch: heads/refs/tags/v6.5.0
UTC Build Time: 2022-12-27 03:50:44
GoVersion: go1.19.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |

**Comment by Defined2014** [comment]
This is expected when `show create table` will get start_ts (https://github.com/pingcap/tidb/issues/43730), the specific explanation can be found at https://github.com/pingcap/tidb/issues/43730
