### ISSUE TITLE
report "Error 1105: region 5972 is in flashback progress, FlashbackStartTS is 441360701681827852" after flashback command finished

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#43673]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
[2023/05/09 06:02:43.009 +08:00] [INFO] [flashback_cluster_test.go:239] ["flashback cluster to timestamp '2023-05-08 21:56:43'"]
[2023/05/09 06:02:44.412 +08:00] [INFO] [flashback_cluster_test.go:248] ["select count(*) from tpcc.customer"]
[2023/05/09 06:02:44.502 +08:00] [INFO] [flashback_cluster_test.go:251] [error] ["select count(*) from table fail"="Error 1105: region 300
0 is in flashback progress, FlashbackStartTS is 441341277140942853"]

### 2. What did you expect to see? (Required)
sql can execute successfully after flashback
### 3. What did you see instead (Required)
report error
### 4. What is your TiDB version? (Required)

master

**Comment by Defined2014** [comment]
It happened when one TiKV node down and no enough log msgs. Need to wait for reappearance.

**Comment by Defined2014** [comment]
Should fixed by https://github.com/tikv/tikv/pull/14859, close it

**Comment by Defined2014** [comment]
Seems still have follow read problem, reopen it.

**Comment by cfzjywxk** [comment]
@Defined2014 
Is there a related client-go issue and are you still following it?

**Comment by Defined2014** [comment]
No further news, maybe we could close this until it happened again.
