### ISSUE TITLE
make load-data statement follow the control of outer-side pessimistic transaction

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#43679]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB
![image](https://github.com/pingcap/tidb/assets/15825830/3d90d7ae-5238-499e-b272-23899883b83f)

MySQL
![image](https://github.com/pingcap/tidb/assets/15825830/437a58a7-dc90-4f5c-b4f2-ebe568a734dc)

**Describe the feature you'd like:**

As the MySQL pic shows

**Describe alternatives you've considered:**

As the MySQL pic shows

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by jackysp** [comment]
Why is it a feature request? @AilinKid

**Comment by jackysp** [comment]
And it is not related to pessimistic only.

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/tidb/pull/49079
