### ISSUE TITLE
Incompatible errors between tidb and mysql about `GROUP_CONCAT`

### ISSUE THREAD

**Issue by CbcWestwolf** [pingcap/tidb#43761]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t(a INTEGER);
INSERT INTO t VALUES (1),(2);
SELECT (SELECT 1
	FROM t
	WHERE CONVERT(1 USING gbk) <> GROUP_CONCAT(x'a3')
);
```

### 2. What did you expect to see? (Required)

In MySQL 8, the result is 

```
mysql> SELECT (SELECT 1
    -> FROM t
    -> WHERE CONVERT(1 USING gbk) <> GROUP_CONCAT(x'a3')
    -> );
ERROR 3854 (HY000): Cannot convert string '\xA3' from binary to gbk
```

### 3. What did you see instead (Required)

In TiDB, the result is 

```
tidb> SELECT (SELECT 1
    -> FROM t
    -> WHERE CONVERT(1 USING gbk) <> GROUP_CONCAT(x'a3')
    -> );
ERROR 1111 (HY000): Invalid use of group function
```

### 4. What is your TiDB version? (Required)

master

**Comment by YangKeao** [comment]
Oops. This usage is also not allowed by MySQL, so I don't think it's a compatibility issue. If you execute:

```
SELECT 1 FROM t WHERE CONVERT(1 USING gbk) <> GROUP_CONCAT('a3')
```

It will give the same error: "ERROR 1111 (HY000): Invalid use of group function".

I don't think we can keep exactly the same error with MySQL (especially about the order of generating errors :man_facepalming: ). What's your opinion?

**Comment by CbcWestwolf** [comment]
> It will give the same error: "ERROR 1111 (HY000): Invalid use of group function".

The order of generating errors causes the incompatibility, found in a mysql-test case. Let's close this issue :-)
