### ISSUE TITLE
Is it possible to use TiDB's Parser in my C++ project?

### ISSUE THREAD

**Issue by jsyqrt** [pingcap/tidb#43766]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I need a MySQL compatible SQL parser and found TiDB's parser is great, but how can I use it in my C++ project.

**Describe the feature you'd like:**

does TiDB parser provides C ABIs, or any other ways to access the Parse interface?

**Describe alternatives you've considered:**

does it provide a JSON format of the parsed statement/query ast?

**Teachability, Documentation, Adoption, Migration Strategy:**

I found that [pg_query](https://github.com/pganalyze/libpg_query) is another useful parser, but I just need a parser that outputs ast in exactly the same format with MySQL expression's BNF, so TiDB's parser is preferred

**Comment by bb7133** [comment]
Hi @jsyqrt . Thanks for being interested in TiDB parser.

> does TiDB parser provides C ABIs, or any other ways to access the Parse interface?

No, I don't think we have a plan like this.

> does it provide a JSON format of the parsed statement/query ast?

No, there is nothing like this now, although this is possible if we add serialization/deserialization for all the nodes of AST.

IMHO if you need a MySQL-compatible parser for a C++ project, an easier way is to use the [parser from MySQL](https://github.com/mysql/mysql-server/blob/8.0/sql/sql_yacc.yy) itself, after all MySQL is a C++ based project.

**Comment by jsyqrt** [comment]
@bb7133 Thanks for your answer, I've got another solution for this, though still prefer to use TiDB's parser.
