### ISSUE TITLE
unable to kill query

### ISSUE THREAD

**Issue by mxlxm** [pingcap/tidb#4378]
1. What did you do?
`select sleep(10);`
hit `ctrl+c` with the same session to cancel, or `kill id` in another session. 

2. What did you expect to see?
kill the sleep query.

3. What did you see instead?
with `ctrl+c` shows `^C^C -- query aborted` but blocked until the sleep query completed.
with `kill id` returned ok but nothing happened, sleep query completed.

4. What version of TiDB are you using (`tidb-server -V`)?
master

**Comment by zimulala** [comment]
@tiancaiamao

**Comment by tiancaiamao** [comment]
This is a known issue.
We should change the builtin function implementation:

```
time.Sleep(duration)
```

to 

```
select {
case <-time.After(duration):
case <-ctx.Done():
}
```

**Comment by ladrift** [comment]
I am willing to tackle this issue. But, it's not easy for a new contributor to understand the structure of source code. I cannot find the related code about the builtin function `sleep` and its implementation.

Is there anyone can give me some hints?

**Comment by shenli** [comment]
@ladrift The implement of Sleep() is here: https://github.com/pingcap/tidb/blob/master/expression/builtin_miscellaneous.go#L99
