### ISSUE TITLE
load data replace error

### ISSUE THREAD

**Issue by nickzabc** [pingcap/tidb#43849]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Execution the following SQL：

```sql
use test;
drop table if exists t1;
create table t1(id int, name varchar(20), primary key(id) clustered);
load data local infile './a.dat' replace into table t1 fields terminated by ',' enclosed by '' (id,name);
load data local infile './b.dat' replace into table t1 fields terminated by ',' enclosed by '' (id,name);
```

Content of `a.dat`
```text
1,abc
2,cdef
3,asdf
```

Content of `b.dat`
```
1,AAA
2,BBB
3,asdf
```

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
load data local infile './b.dat' replace into table t1 fields terminated by ',' enclosed by '' (id,name);
ERROR 8141 (HY000): assertion failed: key: 7480000000000000885f728000000000000001, assertion: NotExist, start_ts: 441434804390461442, existing start ts: 441434803092848642, existing commit ts: 441434803092848643
### 4. What is your TiDB version? (Required)

6.5.2

**Comment by zyguan** [comment]
fixed by https://github.com/pingcap/tidb/pull/43858

**Comment by you06** [comment]
With refactor of #42565, the load data worker uses internal sessions and the assertion is turned off, so this replace error won't happen anymore.
Remove affect-7.1 and affect-7.3 labels.
