### ISSUE TITLE
why not use vendor dir instead of _vendor/src?

### ISSUE THREAD

**Issue by mccxj** [pingcap/tidb#4402]
see *: vendor tool migrate to glide #1743

Makefile add _vendor dir to GOPATH, why not use vendor instead? 
Makefile will be much cleanlily.

**Comment by shenli** [comment]
@mccxj If other project use tidb's source code as third-party library. `tidb/vendor` dir may make the project's dependency path dirty.
See: https://stackoverflow.com/questions/37351481/should-we-always-place-our-own-packages-in-vendor-folder-when-developing-a-gola

**Comment by mccxj** [comment]
ok.thx.
