### ISSUE TITLE
abandon the usage of functions like `evalExprToReal`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4405]
construct a bigint constant value named `a` and a double constant value named `b`, and test builtin expression `a+b` with constant folding being disabled.

`go tool pprof`:
```
(pprof) top
380ms of 400ms total (95.00%)
Showing top 10 nodes out of 21 (cum >= 40ms)
      flat  flat%   sum%        cum   cum%
     120ms 30.00% 30.00%      120ms 30.00%  runtime.usleep
      70ms 17.50% 47.50%       70ms 17.50%  runtime.duffcopy
      40ms 10.00% 57.50%      220ms 55.00%  github.com/pingcap/tidb/expression.(*builtinArithmeticPlusRealSig).evalReal
      30ms  7.50% 65.00%      110ms 27.50%  github.com/pingcap/tidb/expression.(*Constant).EvalReal
      30ms  7.50% 72.50%       80ms 20.00%  github.com/pingcap/tidb/expression.evalExprToReal
      20ms  5.00% 77.50%       20ms  5.00%  github.com/pingcap/tidb/expression.(*Constant).GetTypeClass
      20ms  5.00% 82.50%      280ms 70.00%  github.com/pingcap/tidb/expression.(*ScalarFunction).Eval
      20ms  5.00% 87.50%      240ms 60.00%  github.com/pingcap/tidb/expression.(*baseRealBuiltinFunc).eval
      20ms  5.00% 92.50%       50ms 12.50%  github.com/pingcap/tidb/expression.evalExprToInt
      10ms  2.50% 95.00%       40ms 10.00%  github.com/pingcap/tidb/expression.(*Constant).Eval
```

1. `(*Constant).GetTypeClass` appears and take `5%` of total cpu time, which should not
2. cpu time ratio of `runtime.duffcopy` is too high, which is `17.50%`

flame graph produced with the previous profiling file by `go-torch`:

<img width="1219" alt="2017-09-02 13 18 01" src="https://user-images.githubusercontent.com/5268763/29993162-37273288-8fe1-11e7-928f-ce380e0cc913.png">

take a inside look at `callgrind` of function `evalExprToReal`:

<img width="923" alt="2017-09-02 13 21 10" src="https://user-images.githubusercontent.com/5268763/29993174-ae2c997c-8fe1-11e7-9078-d79b6a0b095d.png">

So, we can summarize that:
1. the main cause of `runtime.duffcopy` is the duplication of `Datum` returned by `expr.Eval(Row)`
2. the root cause of `expression.(*Constant).GetTypeClass` is the function call `expr.GetTypeClass()`, which can be avoid totally

**Comment by shenli** [comment]
How can we do this?

**Comment by zz-jason** [comment]
@shenli when a `Constant` or `Column` is called through `EvalXXX`, for example `EvalReal`, it is guaranteed that this `Constant` or `Column` is storing or referencing a double value.

- for `Constant`, we can just return `Datum.GetXXX` in function `EvalXXX()`
- for `Column`, we can extract the `Datum` stored in `Row` and return `Datum.GetXXX` in function `EvalXXXX()`, too

**Comment by zz-jason** [comment]
blocked by #4080
