### ISSUE TITLE
abandon the usage of `for _, val := range []Datum`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4406]
<img width="955" alt="2017-09-03 14 29 57" src="https://user-images.githubusercontent.com/5268763/30001044-6a9904a6-90b4-11e7-84d3-e5bdb22a9858.png">

the usage of `for _, val := range []Datum` will cause a lot of `runtime.duffcopy` calls, if we do not change the origin value in the `for` loop, we can just use the origin value

**Comment by ngaut** [comment]
We should use reference instead of value copy

**Comment by zz-jason** [comment]
yes
