### ISSUE TITLE
How to get a ddl sql type using tidb sql parser ?

### ISSUE THREAD

**Issue by minicloudsky** [pingcap/tidb#44082]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I 'm developing a sql audit and auto execute platform by goInception and gh-ost, So I want to get a sql type user submitted so that i can use different database tools to automation sql executing. for example, when i got a `create table` statement, I use goInception to execute, here are some examples.
| sql type       | execute by  | except get tidb sql type              |
|----------------|-------------|----------------------------|
| create table   | goInception | ast.CreateTableStmt        |
| add index      | gh-ost      | ast.CreateIndexStmt        |
| add column     | gh-ost      | ast.AlterTableAddColumns   |
| modify column  | gh-ost      | ast.AlterTableModifyColumn |
| truncate table | goInception | ast.TruncateTableStmt      |
| drop index     | gh-ost      | ast.AlterTableDropIndex    |
| drop table     | goInception | ast.DropTableStmt          |
| rename table   | goInception | ast.RenameTableStmt        |

**Describe the feature you'd like:**

how can i get a sql type by tidb parser,get the tidb ast sql type by tidb parser
| sql type       | execute by  | except get tidb sql type              |
|----------------|-------------|----------------------------|
| create table   | goInception | ast.CreateTableStmt        |
| add index      | gh-ost      | ast.CreateIndexStmt        |
| add column     | gh-ost      | ast.AlterTableAddColumns   |
| modify column  | gh-ost      | ast.AlterTableModifyColumn |
| truncate table | goInception | ast.TruncateTableStmt      |
| drop index     | gh-ost      | ast.AlterTableDropIndex    |
| drop table     | goInception | ast.DropTableStmt          |
| rename table   | goInception | ast.RenameTableStmt        |
**Describe alternatives you've considered:**

My demo code like below.
```go
package main

import (
	"fmt"
	_ "github.com/go-sql-driver/mysql"
	"github.com/pingcap/tidb/parser"
	"github.com/pingcap/tidb/parser/ast"
	_ "github.com/pingcap/tidb/parser/test_driver"
	"strings"
)

func parse(sql string) (*ast.StmtNode, error) {
	p := parser.New()

	stmtNodes, _, err := p.Parse(sql, "", "")
	if err != nil {
		return nil, err
	}

	return &stmtNodes[0], nil
}

func main() {
	orderSqls := []string{
		"ALTER TABLE t_user ALGORITHM=INPLACE,LOCK=NONE, MODIFY COLUMN `status` tinyint(4) NOT NULL DEFAULT '1' COMMENT '状态1-运行中，2-结束'",
		"alter table t_host ALGORITHM=INPLACE,LOCK=NONE, add index idx_uid_update_time(`uid`,`update_time`), drop KEY `idx_updtime`"}
	for _, userOriginSql := range orderSqls {
		sqlList := strings.Split(userOriginSql, ";")
		for _, singleSql := range sqlList {
			node, _ := parse(singleSql)
			fmt.Println(node)
		}
	}
}
```
**Teachability, Documentation, Adoption, Migration Strategy:**

[gh-ost](https://github.com/github/gh-ost)
[goInception](https://github.com/hanchuanchuan/goInception)

**Comment by Defined2014** [comment]
Try pseudocode below
```
p := parser.New()
stmts, _, err := p.Parse(sql, "", "")
switch s := stmts.(type) {
case ast.CreateTableStmt:
	xxx
case xxx
}
```

**Comment by minicloudsky** [comment]
> Try pseudocode below
> 
> ```
> p := parser.New()
> stmts, _, err := p.Parse(sql, "", "")
> switch s := stmts.(type) {
> case ast.CreateTableStmt:
> 	xxx
> case xxx
> }
> ```

The above code sloved my problem, thanks~
