### ISSUE TITLE
Setting an int column with a default string value in sql_mode = "" should be disabled

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tidb#44176]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. tiup playground make a cluster
2. set sql_mode=""
3. create table t1 (a int default "abc", b int );

### 2. What did you expect to see? (Required)
some error information to disable the create table statement.

### 3. What did you see instead (Required)
create successfully

### 4. What is your TiDB version? (Required)
master

**Comment by JaySon-Huang** [comment]
already fixed by https://github.com/pingcap/tidb/pull/34947
