### ISSUE TITLE
When ALGORITHM = INPLACE is included in the DDL, tidb succeeds but MySQL fails. 

### ISSUE THREAD

**Issue by together-wang** [pingcap/tidb#44171]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

When ALGORITHM = INPLACE is included in the DDL, tidb succeeds but MySQL fails. As a result, ticdc synchronization is interrupted.

### 1. Minimal reproduce step (Required)
```
mysql> create table t(id int primary key,id1 bigint(20));
Query OK, 0 rows affected (0.09 sec)

mysql> alter table t MODIFY COLUMN id1 varchar(20) ,ALGORITHM = INPLACE;
Query OK, 0 rows affected, 1 warning (0.10 sec)

mysql> show warnings;
+-------+------+---------------------------------------------------------------------------------------------------+
| Level | Code | Message                                                                                           |
+-------+------+---------------------------------------------------------------------------------------------------+
| Error | 1846 | ALGORITHM=INPLACE is not supported. Reason: Cannot alter table by INPLACE. Try ALGORITHM=INSTANT. |
+-------+------+---------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

```

### 2. What did you expect to see? (Required)
Consistent with MySQL behavior.
![image](https://github.com/pingcap/tidb/assets/44355590/c0f96460-7228-4437-a339-b83fac3472d3)

### 3. What did you see instead (Required)
The TiDB SQL is successfully executed. 
![image](https://github.com/pingcap/tidb/assets/44355590/98ee5d20-a02f-45ba-bc81-23b98449c846)

### 4. What is your TiDB version? (Required)
mysql> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v7.0.0 |
+--------------------+
1 row in set (0.00 sec)

**Comment by Defined2014** [comment]
https://dev.mysql.com/doc/refman/5.7/en/show-columns.html

> A UNIQUE index may be displayed as PRI if it cannot contain NULL values and there is no PRIMARY KEY in the table. A UNIQUE index may display as MUL if several columns form a composite UNIQUE index; although the combination of the columns is unique, each column can still hold multiple occurrences of a given value.

**Comment by bb7133** [comment]
Hi @together-wang , this is (at least now) an expect behavior of TiDB DDL executions, please refer to:

> The ALGORITHM={INSTANT,INPLACE,COPY} syntax functions only as an assertion in TiDB, and does not modify the ALTER algorithm. See [ALTER TABLE](https://docs.pingcap.com/tidb/stable/sql-statement-alter-table) for further details.

from [MySQL compatibility of TiDB](https://docs.pingcap.com/tidb/stable/mysql-compatibility).
