### ISSUE TITLE
ERROR 1265 (01000): Data truncated for column '%s' at row %d

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#44274]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```SQL
CREATE TABLE t1 (c1 TEXT);
INSERT INTO t1 VALUES ('a');
UPDATE t1 SET c1 = CAST('61QW' AS DECIMAL);
```
### 2. What did you expect to see? (Required)
The error message should not have the %s, %d.
### 3. What did you see instead (Required)
```SQL
ERROR 1265 (01000): Data truncated for column '%s' at row %d
```
### 4. What is your TiDB version? (Required)

Release Version: v7.0.0
Edition: Community
Git Commit Hash: 7376954cd868dbc44fc3015c9ef89c53749339a7
Git Branch: heads/refs/tags/v7.0.0
UTC Build Time: 2023-03-29 13:32:13
GoVersion: go1.20.2
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by dveeden** [comment]
This also happens for at least one time related function:
```
sql> SELECT `from_unixtime` ('2023-05-29 17:12:50');
+-----------------------------------------+
| `from_unixtime` ('2023-05-29 17:12:50') |
+-----------------------------------------+
| 1969-12-31 20:33:43.000000              |
+-----------------------------------------+
1 row in set, 1 warning (0.0007 sec)
Warning (code 1265): Data truncated for column '%s' at row %d

sql> SELECT TIDB_VERSION()\G
*************************** 1. row ***************************
TIDB_VERSION(): Release Version: v7.1.0
Edition: Community
Git Commit Hash: 635a4362235e8a3c0043542e629532e3c7bb2756
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-30 10:58:57
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
1 row in set (0.0004 sec)
```

**Comment by zanmato1984** [comment]
After some offline discussion, we thought this issue is a common error that is critical for identifying the problematic row. So I'm adjusting the severity to major and hopefully it will be fixed in next few iterations.

**Comment by dveeden** [comment]
Looks like these are the same issue:
- https://github.com/pingcap/tidb/issues/43905
- https://github.com/pingcap/tidb/issues/27982
- https://github.com/pingcap/tidb/issues/25076

And https://github.com/pingcap/tidb/pull/27959#issuecomment-931879368 seems to have a useful comment about this.
