### ISSUE TITLE
Spatio-temporal query support 

### ISSUE THREAD

**Issue by rainoftime** [pingcap/tidb#4435]
Hi~ Is there any plan for supporting spatial-temporal database? Thank you!

**Comment by shenli** [comment]
@rainoftime We have a plan to support spatial index.

**Comment by icewukong** [comment]
Hi, @shenli:
Do you have specific completion time for the support of spatial index? And I can't wait to try.
The support of spatial index is very important for GIS, and this demand is huge.
Anyway, Tidb is a great project!

**Comment by MrWaggel** [comment]
Any updates on this?

**Comment by morgo** [comment]
@MrWaggel Spatial requires considerable effort and is not on our immediate roadmap right now. See also https://github.com/pingcap/tidb/issues/6347 and https://github.com/pingcap/tidb/issues/673

**Comment by kilik52** [comment]
Any updates on this?

**Comment by bigfacewo** [comment]
Any updates on this?

**Comment by yiwen92** [comment]
Recently, a Hackathon project we are doing this @dveeden  see [https://github.com/Hackathon-2022-GIS/tidb ](https://github.com/Hackathon-2022-GIS/tidb )
