### ISSUE TITLE
projection elimination spends so mach time in `Column.HashCode()`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4438]
a simple query with aggregation functions, do `Optimize()` 1000000 times:

<img width="1211" alt="2017-09-05 20 40 17" src="https://user-images.githubusercontent.com/5268763/30061587-7cd775a4-927a-11e7-9271-020dd0afe46b.png">

<img width="939" alt="2017-09-05 20 41 40" src="https://user-images.githubusercontent.com/5268763/30061650-bf029b70-927a-11e7-9d0f-d939eef3351f.png">

**Comment by shenli** [comment]
Any idea to solve this?

**Comment by zz-jason** [comment]
not yet, maybe we can try `fmt.Sprintf()`firstly

**Comment by coocood** [comment]
Maybe HashCode can be cached in the Column instead of generating every time?

**Comment by zz-jason** [comment]
we can cache it, but still need to change the way to calculate hash code for `Column`
