### ISSUE TITLE
`requiredProp.getHashKey()` takes a lot of time

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4439]
<img width="1461" alt="2017-09-05 21 21 44" src="https://user-images.githubusercontent.com/5268763/30063277-bc23556a-9280-11e7-892c-83888441a76f.png">

<img width="709" alt="2017-09-05 21 22 47" src="https://user-images.githubusercontent.com/5268763/30063284-c0dd0204-9280-11e7-8567-bf2212e16e84.png">

This function firstly makes a slice of `Datum`, then calls function `codec.EncodeValue()`.
There is only 4 value types in the `Datum` slice: `bool, string, int, float64`, maybe we can write a specific hash function for struct `requiredProp`

**Comment by coocood** [comment]
Cache the hash key may solve the problem.
