### ISSUE TITLE
retry transaction must have max retry number and delay time if retry. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#444]

**Comment by xwb1989** [comment]
Shall maximum retry limit be configurable by user or hard-coded? Also, I found this post might be helpful to implement the backoff: http://www.awsarchitectureblog.com/2015/03/backoff.html

**Comment by siddontang** [comment]
@xwb1989  maybe hard code at first. 
You can choose the best back off implementation you think and send up a PR. :-)

**Comment by xwb1989** [comment]
Sounds good for me. By the way, if any one wants to take this issue, just notify me and go for it. I'm putting effort at it but cannot guarantee enough spare time recently.

**Comment by siddontang** [comment]
Cool, we will wait your PR. :-)

**Comment by shenli** [comment]
Solved in https://github.com/pingcap/tidb/pull/658
