### ISSUE TITLE
`newBasePlan()` takes a lot of time

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#4440]
<img width="1456" alt="2017-09-05 21 37 43" src="https://user-images.githubusercontent.com/5268763/30063876-aa7414a6-9282-11e7-9da9-987df5e33afd.png">

<img width="807" alt="2017-09-05 21 37 28" src="https://user-images.githubusercontent.com/5268763/30063916-cf7abc0a-9282-11e7-9ffa-05ea3b16ae8f.png">

a lot of time is spent on `allocID()` and `runtime.concatstring2`. in function `allocID()`, much time is spent on `fmt.Sprintf()`

maybe we can let `allocID()` just return the `int` ID, and do `fmt.Sprintf()` outside, this can leave out a lot of `runtime.concatstring2` function calls

**Comment by shenli** [comment]
Good catch!
