### ISSUE TITLE
Data inconsistency after adding index in ingest mode

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#44449]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The issue is discovered by schrddl test.

Basically, it is hard to reproduce externally through MySQL client because it requires certain states.

### 2. What did you expect to see? (Required)

No error and admin check passed.

### 3. What did you see instead (Required)

Data inconsistency.

### 4. What is your TiDB version? (Required)

21934de7

**Comment by tangenta** [comment]
Additional information:

```
curl [http://127.0.0.1:10080/mvcc/index/test/7f8cd511/ae153eec/802\?95ef46ea\=1.0615997481014645](http://127.0.0.1:10080/mvcc/index/test/7f8cd511/ae153eec/802/?95ef46ea\=1.0615997481014645)
[
 {
  "key": "7480000000000053535F69800000000000000705BFF0FC5004789A20",
  "region_id": 18532,
  "value": {
   "info": {
    "writes": [
     {
      "start_ts": 441896362272358430,
      "commit_ts": 441896362272358430,
      "short_value": "AAAAAAAAAw4="
     }
    ]
   }
  }
 },
 {
  "key": "7480000000000053535F69FFFF00000000000705BFF0FC5004789A20",
  "region_id": 18532,
  "value": {
   "info": {
    "writes": [
     {
      "start_ts": 441896362927718424,
      "commit_ts": 441896362927718428,
      "short_value": "AAAIAAAAAAAAAydiAgAIAAAAAAAAAydiAAAIAAAAAAAAAyhiAgAIAAAAAAAAAyhiAAAIAAAAAAAAAyliAgAIAAAAAAAAAyliAAAIAAAAAAAAAypiAgAIAAAAAAAAAypiAAAIAAAAAAAAAytiAgAIAAAAAAAAAyti"
     },
     {
      "start_ts": 441896362770432533,
      "commit_ts": 441896362770432534,
      "short_value": "AAAIAAAAAAAAAydiAgAIAAAAAAAAAydiAAAIAAAAAAAAAyhiAgAIAAAAAAAAAyhiAAAIAAAAAAAAAyliAgAIAAAAAAAAAyliAAAIAAAAAAAAAypiAgAIAAAAAAAAAypiAAAIAAAAAAAAAyti"
     },
     {
      "start_ts": 441896362456121377,
      "commit_ts": 441896362456121378,
      "short_value": "AAAIAAAAAAAAAw5iAgAIAAAAAAAAAw5i"
     },
     {
      "start_ts": 441896362167501230,
      "commit_ts": 441896362167501253,
      "short_value": "AAAIAAAAAAAAAw5i"
     }
    ]
   }
  }
 }
]%
```

We can see the `short_value` of temporary index is overwritten between the commit TS `441896362456121378` and `441896362770432534`. This is because the lazy check is enabled:

https://github.com/pingcap/tidb/blob/6ba05018df74761fcd9578d46fc6c72cf6436bc6/table/tables/index.go#L282-L284

The original temp index value is overwritten, causing some operations to be lost. As a result, a redundant index record in detected by `admin check`.

**Comment by jackysp** [comment]
I don't know why it is not affected release 6.5?
