### ISSUE TITLE
dist framework: cancelled task status is overriden to running

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#44443]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- start task
- task process normal flow, but before it update task status as running, the task is cancelled
- framework continue update, and override the task status as running

if task has already cancelled before entering running, the cancel status will be overrided

https://github.com/pingcap/tidb/blob/223564afb6a20b324178c844b29dd59adcdd74ce/disttask/framework/storage/task_table.go#L397

### 2. What did you expect to see? (Required)
task status keep cancelled
### 3. What did you see instead (Required)
task is overrided to running

**Comment by ywqzzy** [comment]
close as #45932 fix it
