### ISSUE TITLE
CTE statement left spilled files unremoved 

### ISSUE THREAD

**Issue by yibin87** [pingcap/tidb#44477]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
CTE statment executed successfully, while left spilled files unremoved.

![Beq4amDf33](https://github.com/pingcap/tidb/assets/12403562/394e9084-0d67-405b-b739-3852e3e44540)
The CTEFullScan_68 occupied 2.6GB disk size, and not released finally.

### 4. What is your TiDB version? (Required)

v6.1.x

**Comment by guo-shaoge** [comment]
`select` stmt is ok, Ohter DML has this problem.
