### ISSUE TITLE
when there are lot of tables, copy-on-write mechanism for statistics updating take up all the CPU resource

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#44492]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![image](https://github.com/pingcap/tidb/assets/1420062/09bbd890-06d5-47c8-9c15-c29dcedf74ef)

[588k-tables-tidb-cpu-profiling.zip](https://github.com/pingcap/tidb/files/11679489/588k-tables-tidb-cpu-profiling.zip)

In a cluster, importing many tables, especially partition tables...
Before the statistics available (no manually analyze table) ... and 'select * from t limit 1' for the tables.

### 2. What did you expect to see? (Required)

The query execute fast.

### 3. What did you see instead (Required)

The query is slow ... and all the CPU resource are eat up by the statistics updating.

### 4. What is your TiDB version? (Required)

master bc45bdf3c0e51e3a33ab08913bd7d3631bb0f025

**Comment by qw4990** [comment]
Fixed by https://github.com/pingcap/tidb/issues/44461
