### ISSUE TITLE
Compile error: yy_parser.go

### ISSUE THREAD

**Issue by EtienneBruines** [pingcap/tidb#445]
Possibly related to #88. 

Running 64 bit Linux with Go 1.5

```
$ go get -u github.com/pingcap/tidb
# github.com/pingcap/tidb/parser
../../../github.com/pingcap/tidb/parser/yy_parser.go:17: undefined: yyLexer
../../../github.com/pingcap/tidb/parser/yy_parser.go:18: undefined: yyParse
```

I also manually used `go get` for `github.com/qiuyesuifeng/golex` and `github.com/qiuyesuifeng/goyacc`. It didn't help. 

I'm following the information [here](https://github.com/pingcap/tidb/blob/master/docs/USAGE.md). This does not mention the use of the `make` file. 

If I however, do try to use it, it gives me this:
```
go get github.com/tools/godep
go get github.com/qiuyesuifeng/goyacc
go get github.com/qiuyesuifeng/golex
a=`mktemp temp.XXXXXX`; \
goyacc -o /dev/null -xegen $a parser/parser.y; \
goyacc -o parser/parser.go -xe $a parser/parser.y 2>&1 | grep "shift/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; exit 1;}}';  \
rm -f $a; \
rm -f y.output 
/bin/sh: 2: goyacc: not found
sed: can't read parser/parser.go: No such file or directory
Makefile:28: recipe for target 'parser' failed
make: *** [parser] Error 2
```

**Comment by siddontang** [comment]
@EtienneBruines Do you set correct GOPATH and GOROOT, and append $GOPATH/bin to $PATH?

**Comment by EtienneBruines** [comment]
@siddontang Did not think of the latter (appending `$GOPATH/bin` to `$PATH`). Didn't know it was needed ;-).It works now. 

Perhaps the use of the `Makefile` should be documented at `USAGE.md` as well?

**Comment by ngaut** [comment]
@EtienneBruines Thanks for your report.
You are right, we should add more details to USAGE.md.
