### ISSUE TITLE
unstable test TestPiTRCreateUniqueIndex

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#44559]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
    common.go:253: 
        	Error Trace:	tests/realtikvtest/addindextest/common.go:253
        	            				tests/realtikvtest/addindextest/common.go:465
        	            				tests/realtikvtest/addindextest/common.go:358
        	            				tests/realtikvtest/addindextest/pitr_test.go:38
        	Error:      	"[ddl:8214]Cancelled DDL job" does not contain "Duplicate entry"
        	Test:       	TestPiTRCreateUniqueIndex
```

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/22320/pipeline

**Comment by BornChanger** [comment]
I checked recent running records and didn't see the problem again. If it's not so frequent, please close it or lower the priority. @hawkingrei

**Comment by hawkingrei** [comment]
I cannot see it for a long time.
