### ISSUE TITLE
Make topNSlowQueries configurable

### ISSUE THREAD

**Issue by xuyifangreeneyes** [pingcap/tidb#44567]
## Enhancement

https://github.com/pingcap/tidb/blob/f320bbe46944ca3d1a815d90712d4331e707a54c/domain/domain.go#L1024

Currently, we store 30 topn slow queries and 500 recent slow queries in memory. The two numbers are hard-coded and we hope to make them configurable.

**Comment by isabella0428** [comment]
Should we also make the other numbers configurable like capacity of the sysSessionPool size? Would it be better to define a variable at the beginning of the file or to make them function arguments with default value?

**Comment by xuyifangreeneyes** [comment]
> Should we also make the other numbers configurable like capacity of the sysSessionPool size? Would it be better to define a variable at the beginning of the file or to make them function arguments with default value?

Yeah, it would be better to define a variable as the sysSessionPool size. Do we need to expose it to users as a configuration item? cc @hawkingrei
