### ISSUE TITLE
DDL: The performance drop 70% 

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#44584]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Deploy a TiDB cluster with 1 TiDB and 6 TiKV.
2. Restore the data from the backup of [ossinsight](https://ossinsight.io/docs/workshop/ossinsight-lite/introduction) system
3. `set global tidb_ddl_enable_fast_reorg=ON;`
4. `alter table github_events add index test_idx(repo_id,type,action,closed_at,actor_login);`

### 2. What did you expect to see? (Required)
No performance regression

### 3. What did you see instead (Required)
![image](https://github.com/pingcap/tidb/assets/84501897/6604c395-a317-4d70-a687-e0baa51b07d6)

### 4. What is your TiDB version? (Required)

good commit: be8d86504402cf6e9648fa4972d29e6ac3f9e9a8
bad commit: 6fbf29981ed5facc1f47fcf041386254bb5e88d0

**Comment by Yui-Song** [comment]
> Can you explain in detail how can I reproduce this issue? specifically "ossinsight-ddl-add-index case"

@maryamekhlasi I'm glad to know that you are interested in reproducing this issue. I have updated the reproduce step in the Bug Report. 
"ossinsight-ddl-add-index case" is a DDL performance test case using [OSS Insight](https://ossinsight.io/docs/workshop/ossinsight-lite/introduction) dataset. In the test case, we add an index to table `github_event`. If you are interested in the dataset, you can try our [Chat2Query](https://www.pingcap.com/chat2query-an-innovative-ai-powered-sql-generator-for-faster-insights/#start), which is free, on TiDB Cloud. `github_events` is one of the four preset sample datasets.
If you want to reproduce the issue yourself, it's recommended to use [sysbench](https://github.com/akopytov/sysbench) as it's shown in https://github.com/pingcap/tidb/pull/44668.

![img_v2_a940428b-c477-4a47-9aac-94163e05f3cg](https://github.com/pingcap/tidb/assets/84501897/168f676b-2c69-4fd9-880f-2410f29869c1)

**Comment by maryamekhlasi** [comment]
> > Can you explain in detail how can I reproduce this issue? specifically "ossinsight-ddl-add-index case"
> 
> @maryamekhlasi I'm glad to know that you are interested in reproducing this issue. I have updated the reproduce step in the Bug Report. "ossinsight-ddl-add-index case" is a DDL performance test case using [OSS Insight](https://ossinsight.io/docs/workshop/ossinsight-lite/introduction) dataset. In the test case, we add an index to table `github_event`. If you are interested in the dataset, you can try our [Chat2Query](https://www.pingcap.com/chat2query-an-innovative-ai-powered-sql-generator-for-faster-insights/#start), which is free, on TiDB Cloud. `github_events` is one of the four preset sample datasets. If you want to reproduce the issue yourself, it's recommended to use [sysbench](https://github.com/akopytov/sysbench) as it's shown in #44668.
> 
> ![img_v2_a940428b-c477-4a47-9aac-94163e05f3cg](https://user-images.githubusercontent.com/84501897/245731753-168f676b-2c69-4fd9-880f-2410f29869c1.jpg)

Thanks for you detailed answer.

**Comment by maryamekhlasi** [comment]
> > Can you explain in detail how can I reproduce this issue? specifically "ossinsight-ddl-add-index case"
> 
> @maryamekhlasi I'm glad to know that you are interested in reproducing this issue. I have updated the reproduce step in the Bug Report. "ossinsight-ddl-add-index case" is a DDL performance test case using [OSS Insight](https://ossinsight.io/docs/workshop/ossinsight-lite/introduction) dataset. In the test case, we add an index to table `github_event`. If you are interested in the dataset, you can try our [Chat2Query](https://www.pingcap.com/chat2query-an-innovative-ai-powered-sql-generator-for-faster-insights/#start), which is free, on TiDB Cloud. `github_events` is one of the four preset sample datasets. If you want to reproduce the issue yourself, it's recommended to use [sysbench](https://github.com/akopytov/sysbench) as it's shown in #44668.
> 
> ![img_v2_a940428b-c477-4a47-9aac-94163e05f3cg](https://user-images.githubusercontent.com/84501897/245731753-168f676b-2c69-4fd9-880f-2410f29869c1.jpg)

Thanks for you detailed answer. Actually I am a performance analysis member of DORSAL lab and for my research purposes I decided to work on your problem, I need to enable openTracing in the last version of  Tidb, I could do that for V3.0.0 but not the last one here is the steps I followed: 1- enabled OpenTracing in the config files 2- cloned and replaced the jaeger-client-go in go.mod 3- build

**Comment by Yui-Song** [comment]
After https://github.com/pingcap/tidb/pull/44668 was merged, the regression reduced to 8%.
