### ISSUE TITLE
Create Table IfNotExists not use

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#446]
I see in the func CreateTableStmt.Exec(), CreateTableStmt.IfNotExists member  not pass to ddl.CreateTable(), so the sql "create table if not exist" will not work.

**Comment by ngaut** [comment]
It should be worked. Have you test it?
Please take a look at:
https://github.com/pingcap/tidb/blob/master/stmt/stmts/create.go#L76

**Comment by winkyao** [comment]
yeah, Create database, it works, but I mean the create table .

**Comment by ngaut** [comment]
oops, create table:
https://github.com/pingcap/tidb/blob/master/stmt/stmts/create.go#L119

**Comment by winkyao** [comment]
I saw this, but notice the CreateTableStmt.IfNotExists not pass to sessionctx.GetDomain(ctx).DDL().CreateTable(ctx, s.Ident.Full(ctx), s.Cols, s.Constraints), so the error never be ddl.ErrExists,

**Comment by winkyao** [comment]
I saw this, but notice the CreateTableStmt.IfNotExists not pass to sessionctx.GetDomain(ctx).DDL().CreateTable(ctx, s.Ident.Full(ctx), s.Cols, s.Constraints), so the error never be ddl.ErrExists,

**Comment by ngaut** [comment]
AH, You are right.
Could you fix this ?

**Comment by winkyao** [comment]
ok, I will fix it..it is easy.

**Comment by shenli** [comment]
https://github.com/pingcap/tidb/blob/master/ddl/ddl.go#L376
@winkyao

**Comment by shenli** [comment]
I test it using the newest master.
tidb> use test;
Query OK, 0 row affected (0.00 sec)
tidb> show tables;
Empty set (0.00 sec)
tidb> create table t(c int);
Query OK, 0 row affected (0.00 sec)
tidb> create table if not exists t(c int);
Query OK, 0 row affected (0.00 sec)
tidb>

**Comment by winkyao** [comment]
@shenli :) you are right. but is it correctly? I mean in mysql, if I wanna replace my table definition, I can just use "create table", and tidb return error when it was duplicated anyway.

**Comment by shenli** [comment]
If your statement has IfNotExists, TiDB will not return error. See:
https://github.com/pingcap/tidb/blob/master/stmt/stmts/create.go#L120
TiDB has the same behavior with mysql:
Database changed
mysql> drop table t;
Query OK, 0 rows affected (0.01 sec)
mysql> create table t(c int);
Query OK, 0 rows affected (0.03 sec)
mysql> create table t(c char);
ERROR 1050 (42S01): Table 't' already exists
mysql> create table if not exists t(c char);
Query OK, 0 rows affected, 1 warning (0.00 sec)
mysql> 

If you want to change table schema, your need to drop the table and recreate it. Or you can use alter table statement.

**Comment by winkyao** [comment]
I know what you mean, and It is diffrent from mysql, So I get confused..

**Comment by shenli** [comment]
You mean the error code is different? I tried TiDB. It is the same with mysql. So I am a few confused....
tidb> use test;
Query OK, 0 row affected (0.00 sec)
tidb> drop table t;
Query OK, 0 row affected (0.01 sec)
tidb> create table t(c int);
Query OK, 0 row affected (0.01 sec)
tidb> create table t(c char);
2015/10/23 19:19:33 main.go:231: [error] /Users/mac/workspace/go/src/github.com/pingcap/tidb/stmt/stmts/create.go:122: CREATE TABLE: table exists t
/Users/mac/workspace/go/src/github.com/pingcap/tidb/tidb.go:182: 
/Users/mac/workspace/go/src/github.com/pingcap/tidb/session.go:275: 
/Users/mac/workspace/go/src/github.com/pingcap/tidb/driver.go:302: 
/Users/mac/workspace/go/src/github.com/pingcap/tidb/interpreter/main.go:118:  
tidb> create table if not exists t(c char);
Query OK, 0 row affected (0.00 sec)
tidb>

**Comment by winkyao** [comment]
no, if you use "create table test xxx", and the table test is already existed, mysql will replace it, tidb is diffrent, but you don't have to follow mysql, because I think tidb is more safely in this way.

**Comment by shenli** [comment]
Maybe you miss understand mysql's behavior.
See: http://dev.mysql.com/doc/refman/5.7/en/create-table.html
"Existing Table with Same Name
The keywords IF NOT EXISTS prevent an error from occurring if the table exists. However, there is no verification that the existing table has a structure identical to that indicated by the CREATE TABLE statement."

I tried it with mysql, and it will not replace the existing table.
mysql> drop table t;
Query OK, 0 rows affected (0.01 sec)
mysql> create table t(c int);
Query OK, 0 rows affected (0.03 sec)
mysql> create table t(c char);
ERROR 1050 (42S01): Table 't' already exists
mysql> create table if not exists t(c char);
Query OK, 0 rows affected, 1 warning (0.00 sec)
mysql>

May I have your mysql server version?

**Comment by winkyao** [comment]
sorry, my test code drop it before I create it, you are right...

**Comment by shenli** [comment]
Thanks for your attention. Please keep eyes on TiDB.

PS: I worked in Qihoo for 3 years. Nice to meet you here. :)
