### ISSUE TITLE
[Dynamic Regions] br: br full restored to multirocksdb cluster and checksum failed using default config

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#44658]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
full restored to multirocksdb cluster 

### 3. What did you see instead (Required)
checksum would timeout if tikv.end-point-request-max-handle-duration is in default ,and the config changed to 1800s or more can avoid the issue, thus br may detect the config and change it according to region-size
### 4. What is your TiDB version? (Required)
7.1.0

**Comment by BornChanger** [comment]
@AkiraXie Is the problem still there on partitioned kv?

**Comment by AkiraXie** [comment]
the issue didn't show in recent tests
