### ISSUE TITLE
can not kill the session while query with sleep

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#44675]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
it comes from https://asktug.com/t/topic/1007504

1. init data
```sql
create table t(a int, b int);
insert into t values (1,1); -- insert more data
select sleep(1), a.* from t a;
```
2. kill the query session
### 2. What did you expect to see? (Required)
killed immediately 
### 3. What did you see instead (Required)
1. can not kill the query immediately
2. use a lot mem and can't affected by `tidb_mem_quota_query`
### 4. What is your TiDB version? (Required)
v6.5.2, v7.1.0

**Comment by Defined2014** [comment]
I think it same as https://github.com/pingcap/tidb/issues/39449. We only check kill status in `Next()` function.

**Comment by Defined2014** [comment]
For memTracker, it also checked memory every batches (like 1024 lines each), just like `KILL`.
