### ISSUE TITLE
Change escape character from "$" to "\" for `regexp_replace`

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tidb#44684]

**Comment by bb7133** [comment]
What is the behavior of MySQL? Is the change compatible?

**Comment by xzhangxian1008** [comment]
> What is the behavior of MySQL? Is the change compatible?

MySQL use `$` as escape character, however we think `\` is better as clickhouse and pg are the same behaviour.

**Comment by bb7133** [comment]
mmm...what about the users who're relying on '`$`' in their application code? We need to be very serious for the backward compatibility change & MySQL compatiiblity change.

**Comment by xzhangxian1008** [comment]
> mmm...what about the users who're relying on '`$`' in their application code? We need to be very serious for the backward compatibility change & MySQL compatiiblity change.

So far, no user relies on '$', as this function hasn't been released, so there is no compatibility change problem.
