### ISSUE TITLE
The ddl jobs cannot be canceled，It went on for days

### ISSUE THREAD

**Issue by zjHe** [pingcap/tidb#44687]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

my dll ：ALTER TABLE table_xxx ADD COLUMN tag int(11) COMMENT 'tag', ALGORITHM=INPLACE, LOCK= NONE

We performed a DDL operation with a small amount of data and no response for many days。

![image](https://github.com/pingcap/tidb/assets/34431616/3fc0a7ae-4581-43d4-ab0c-a474bc71799b)

Therefore, we cancelled the DDL operation later, but the cancelling state was always in, which had been for several days

![image](https://github.com/pingcap/tidb/assets/34431616/94aae06a-7a23-4ccd-be7b-4926aee39524)

### 2. What did you expect to see? (Required)

Fields can be added and DDL operations can be cancelled normally

### 3. What did you see instead (Required)

The field is created without any response and cannot be canceled

### 4. What is your TiDB version? (Required)

version: 6 .5

**Comment by seiya-annie** [comment]
could you please upload tidb log files? @zjHe

**Comment by Defined2014** [comment]
Maybe affects by MDL, you can follow this document to solve the problem. https://docs.pingcap.com/tidb/stable/metadata-lock

If you still have problems, feel free to reopen this issue and give us more details like `tidb.log` etc.
