### ISSUE TITLE
Unexpected error when `CHECK` a predicate that is always true.

### ISSUE THREAD

**Issue by DerZc** [pingcap/tidb#44689]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The following query triggers an error:
```
CREATE TABLE t0(c1 NUMERIC CHECK (true));
```

This is the error message:
```
Column check constraint 't0_chk_1' references other column.
```
A `true` predicate means no value will violate this constraint. This query can triggers this error in MySQL, and MySQL verified this is a bug.
https://bugs.mysql.com/bug.php?id=111421

### 2. What did you expect to see? (Required)
No error.
### 3. What did you see instead (Required)
```
Column check constraint 't0_chk_1' references other column.
```

### 4. What is your TiDB version? (Required)

```
Release Version: v7.2.0-alpha-421-gabd9ff5ca6\nEdition: Community\nGit Commit Hash: abd9ff5ca6fe866224f243c931844f050fb4952c\nGit Branch: master\nUTC Build Time: 2023-06-14 08:57:42\nGoVersion: go1.20.3\nRace Enabled: false\nCheck Table Before Drop: false\nStore: unistore
```

**Comment by CbcWestwolf** [comment]
@fzzf678 PTAL
