### ISSUE TITLE
Disaggregated Mode/Ban Tiflash Cop Mode couldn't co-exist with UnionScan

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#44705]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
ref the unit test cases
func TestReadPartitionTable(t *testing.T) {
...
}
better open tk.MustExec("set @@session.tidb_ban_tiflash_cop=OFF") to close the tiflash cop mode, and let the optimizer to choose MPP mode.

### 2. What did you expect to see? (Required)
```
Tiflash MPP Mode
+[HashAgg_15 1.00 root  funcs:count(Column#4)->Column#3]
+[└─PartitionUnion_16 2.00 root  ]
+[  ├─StreamAgg_18 1.00 root  funcs:count(1)->Column#4]
+[  │ └─UnionScan_22 10000.00 root  ]
+[  │   └─TableReader_25 10000.00 root  MppVersion: 1, data:ExchangeSender_24]
+[  │     └─ExchangeSender_24 10000.00 mpp[tiflash]  ExchangeType: PassThrough]
+[  │       └─TableFullScan_23 10000.00 mpp[tiflash] table:t, partition:p0 keep order:false, stats:pseudo]
+[  └─StreamAgg_32 1.00 root  funcs:count(1)->Column#4]
+[    └─UnionScan_36 10000.00 root  ]
+[      └─TableReader_39 10000.00 root  MppVersion: 1, data:ExchangeSender_38]
+[        └─ExchangeSender_38 10000.00 mpp[tiflash]  ExchangeType: PassThrough]
+[          └─TableFullScan_37 10000.00 mpp[tiflash] table:t, partition:p1 keep order:false, stats:pseudo]

Tiflash Cop Mode       	 
+[HashAgg_15 1.00 root  funcs:count(Column#4)->Column#3]
+[└─PartitionUnion_16 2.00 root  ]
+[  ├─StreamAgg_18 1.00 root  funcs:count(1)->Column#4]
+[  │ └─UnionScan_22 10000.00 root  ]
+[  │   └─TableReader_24 10000.00 root  data:TableFullScan_23]
+[  │     └─TableFullScan_23 10000.00 cop[tiflash] table:t, partition:p0 keep order:false, stats:pseudo]
+[  └─StreamAgg_30 1.00 root  funcs:count(1)->Column#4]
+[    └─UnionScan_34 10000.00 root  ]
+[      └─TableReader_36 10000.00 root  data:TableFullScan_35]
+[        └─TableFullScan_35 10000.00 cop[tiflash] table:t, partition:p1 keep order:false, stats:pseudo]
```
since what explain statement shows is a physical plan tree, while when building the executors, it couldn't successfully build the unionScan operator, which will lead to the final result set missing the uncommitted rows.

### 3. What did you see instead (Required)
the result set is same with the one under Tiflash Cop Mode

### 4. What is your TiDB version? (Required)

master

**Comment by guo-shaoge** [comment]
[here](https://github.com/pingcap/tidb/pull/44324/files#diff-d3c0a89b78f47003373eef281d3c2587ec98efa7e64ffa2d5e9647c62601490aR1350) disable MPPGather as child of UnionScan
