### ISSUE TITLE
"div" scientific notation values out of range

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#4477]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
select (1.175494351E-37 div 1.7976931348623157E+308);
```

2. What did you expect to see?

```
+-----------------------------------------------+
| (1.175494351E-37 div 1.7976931348623157E+308) |
+-----------------------------------------------+
|                                             0 |
+-----------------------------------------------+
```

3. What did you see instead?

```
ERROR 1690 (22003): %s value is out of range in '%s'
```

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by mccxj** [comment]
1. I will tru to fix it. it seems a bug when cast real to decimal.
2. I alsofound cast(xx as decimal(2,3)) will core.

**Comment by mccxj** [comment]
@jackysp it should be closed

**Comment by shenli** [comment]
@mccxj Yes.
