### ISSUE TITLE
the time returned to the client is inconsistent with the ddl job info for truncate table

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#44785]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. tiup playground nightly --tiflash 0
```sql
create table t02(a int, b int, primary key (a)) partition by hash(a) partitions 1000;
truncate table t02;
truncate table t02;
truncate table t02;
```

### 2. What did you expect to see? (Required)
the time for truncate table from ddl jobs info should consistent with client's time
### 3. What did you see instead (Required)
you can see that client wait a long time but the ddl info record only a few time.
![图片](https://github.com/pingcap/tidb/assets/10184437/2467d168-eb8d-430e-abb2-e0926c82dc7e)
![图片](https://github.com/pingcap/tidb/assets/10184437/fdaeb34a-b32d-4034-a185-a10cc7c11f96)

### 4. What is your TiDB version? (Required)
```sql
[16:34:51]TiDB root:test> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.2.0-alpha                             |
| Edition: Community                                        |
| Git Commit Hash: 8633c8ce9921bf17a92b582a6b5d299d95213ac6 |
| Git Branch: heads/refs/tags/v7.2.0-alpha                  |
| UTC Build Time: 2023-06-15 14:25:30                       |
| GoVersion: go1.20.3                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

**Comment by mjonss** [comment]
I would propose to move the preSplitAndScatter call into the ddl worker instead, probably directly after the new table/partitions are created, before they are public to be written.

**Comment by crazycs520** [comment]
I don't think this requirement is reasonable, and we don't promise that the DDL job time is equal to the execution time of the DDL SQL statement.
