### ISSUE TITLE
Report error during tiup playground using initialize-sql-file reset root password

### ISSUE THREAD

**Issue by qiaoxinke** [pingcap/tidb#44895]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create a initialize sql file "init.sql" including following contents
`set password for root@% ='password';`
2. create tidb.toml including belows
`initialize-sql-file = "/Users/xxx/xxx/init.sql"`
3. start tiup playground 
`tiup playground --db.config tidb.toml`

A error reported during tidb instance starting.
...
Start tidb instance:v7.1.0
Waiting for tidb instances ready
127.0.0.1:4000 ... Error
...

However if we use the password set in init.sql, we can log in successfully.
```
(base) xxx@192 Downloads % mysql --comments --host 127.0.0.1 --port 4000 -u root -ppassword
mysql: [Warning] Using a password on the command line interface can be insecure.
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 507
Server version: 5.7.25-TiDB-v7.1.0 TiDB Server (Apache License 2.0) Community Edition, MySQL 5.7 compatible

Copyright (c) 2000, 2023, Oracle and/or its affiliates.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
```

### 2. What did you expect to see? (Required)
No error reported or if the root password change is not supported, please add a notice in docs.

### 3. What did you see instead (Required)
A error reported during tidb instance starting.

### 4. What is your TiDB version? (Required)
v7.1.0

**Comment by Defined2014** [comment]
It relates with `tiup playground`, see codes below. https://github.com/pingcap/tiup/blob/c2ae2f613069ffd98127fba4776d3fef8db0393c/components/playground/main.go#L401
