### ISSUE TITLE
Bad error string in Incorrect partition name

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#44967]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
create table t (a int) partition by list (a) (partition `s1 s2 ` values in (0));
```

### 2. What did you expect to see? (Required)
Incorrect partition name

### 3. What did you see instead (Required)
Incorrect partition name%!(EXTRA string=s1 s2 )

### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v7.1.0
Edition: Community
Git Commit Hash: 635a4362235e8a3c0043542e629532e3c7bb2756
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-30 10:50:03
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv
```

**Comment by River2000i** [comment]
enter a error partition name in `alter table` also get the same error message

```sql
mysql> ALTER TABLE t ADD PARTITION (PARTITION `s1 s3 ` VALUES IN (5));
ERROR 1567 (HY000): Incorrect partition name%!(EXTRA string=s1 s3 )
```
