### ISSUE TITLE
code clean: refine similar functions in `tidb/util/codec` and `server/internal/dump/dump.go`

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#44970]
## Enhancement
There are some similar functions, we could refine and improve them. 

For example, the `dump.Uint64` function is very similar with `EncodeUint`. And also we could use `binary.BigEndian.AppendUint64` or `binary.LittleEndian.AppendUint64` instead of them either.

**Comment by Defined2014** [comment]
And also some simlar functions in `tidb/executor/aggfuncs/func_count_distinct.go`, like  https://github.com/pingcap/tidb/blob/0f20315681d20e94b550770d84ca97c1d28b68bd/executor/aggfuncs/func_count_distinct.go#L419

**Comment by NicoleRobin** [comment]
I want to solve this issue, please assign it to me.

**Comment by Defined2014** [comment]
> I want to solve this issue, please assign it to me.

Done @NicoleRobin

**Comment by Shivansh2407** [comment]
Hey @Defined2014 and @NicoleRobin, is this still being worked upon? I'd be happy to take this up. Thanks!
