### ISSUE TITLE
Stale read maybe always blocked cause by ResolvedTS blocked

### ISSUE THREAD

**Issue by crazycs520** [pingcap/tidb#44990]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. tidb-server config:

```yaml
[labels]
zone = "z1"
```

Then [stale read request](https://github.com/tikv/client-go/blob/5fde3098f9183d22507dbd16597ff5a5d7f84390/internal/locate/region_request.go#L546-L549) is always not GlobalStaleRead. Then when stale read requests meet `DataIsNotReady` error, TiDB will retry the next available region replica. But if the `ResolvedTS` is blocked, the stale read request will always recieve `DataIsNotReady` error.  In this situation, TiDB should send the stale read request to region leader, and remove the request.StaleRead flag, then the region leader can always handle it.

### 4. What is your TiDB version? (Required)

tidb v6.5.3

**Comment by tiancaiamao** [comment]
This issue should be a bug instead of enhancement? @crazycs520

**Comment by crazycs520** [comment]
already fixed.

**Comment by crazycs520** [comment]
release-6.5 already fixed by https://github.com/pingcap/tidb/pull/46137
