### ISSUE TITLE
UnionScan with partition table + keepOrder can't get correct result

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#45007]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a int, b int, primary key(b)) PARTITION BY HASH(b) partitions 4;
analyze table t;
begin;
insert into t(a, b) values (6,6),(3,3),(9,9),(4,4),(5,5),(7,7),(8,8);
select * from t where b > 1 order by b limit 5;
```

### 2. What did you expect to see? (Required)

```
mysql> select * from t where b > 1 order by b limit 5;
+------+---+
| a    | b |
+------+---+
|    3 | 3 |
|    4 | 4 |
|    5 | 5 |
|    6 | 6 |
|    7 | 7 |
+------+---+
5 rows in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> select * from t where b > 1 order by b limit 5;
+------+---+
| a    | b |
+------+---+
|    4 | 4 |
|    8 | 8 |
|    5 | 5 |
|    9 | 9 |
|    6 | 6 |
+------+---+
5 rows in set (0.00 sec)
```

**Comment by Defined2014** [comment]
We can disable topN pushdown when unionScan exists firstly. And let unionScan support partition table in next step.

**Comment by mjonss** [comment]
`set tidb_partition_prune_mode = 'static'` seems unaffected (since it sees each partition as a separate table), but the `dynamic` tidb_partition_prune_mode is affected by this bug.
