### ISSUE TITLE
the `AvailablePartitionIDs` of the table is not reset when the table is created by snapshot restore

### ISSUE THREAD

**Issue by Leavrth** [pingcap/tidb#45013]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. prepare a cluster with tiflash, and there is a table with partition.
2. snapshot backup the cluster
3. prepare another the same cluster with tiflash
4. snapshot restore to the cluster
5. show the tiflash_replica information:

```SQL
select * from information_schema.tiflash_replica;
```

### 3. What did you see instead (Required)

The table is not avaliable but progress is 1.

**Comment by JaySon-Huang** [comment]
When restore a table info into the new cluster, we should reset the `Info.TiFlashReplica.Available` to false and `TableInfo.TiFlashReplica.AvailablePartitionIDs` to be an empty array.
These fields' values should be updated in a later TiFlash replica poll tick but not copied from the backup table info. Or the available/progress status in the new cluster is not right.
