### ISSUE TITLE
code improve: support `ExtraPhysTblID` in UnionScan

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#45052]
## Enhancement

Now in the `memTableReader` and `memIndexReader`, we will not fill in the `ExtraPhysTblID` into result. The value in the row always equal to 0. Though **it will not impact any problem** now, we should fix it to reduce code risk.

Maybe helpful function shows below

https://github.com/pingcap/tidb/blob/dec0ff7b25503e34fa1fe897e71f3b6dcd059e4b/util/rowcodec/decoder.go#L383

**Comment by tiancaiamao** [comment]
@Defined2014 I'm doing a refactor here, so, as a kind remind, don't invest on the legancy code.

**Comment by Defined2014** [comment]
> @Defined2014 I'm doing a refactor here, so, as a kind remind, don't invest on the legancy code.

Do you have a related issue? I think we could create  a issue collects all unionScan related problems.

**Comment by tiancaiamao** [comment]
There is an issue about the performance https://github.com/pingcap/tidb/issues/43249
