### ISSUE TITLE
resource control ddl atomicity is not guaranteed in some scenario

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#45050]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

from https://asktug.com/t/topic/1007510
According to the description of the problem, it seems that the phenomenon is caused by the presence of the table in TiDB while it has been deleted in PD. It is possible that there was an error in the first deletion attempt in PD's RPC (although it was actually successful), which caused an error to be returned to TiDB and prevented the deletion of metadata in TiDB. However, the table was actually deleted in PD. This can result in the ability to query the table but not delete it.
During the execution of this DDL operation, it involves both TiDB and PD. However, the logic of the two components is not atomic, hence there is a probability of encountering similar issues.
### 4. What is your TiDB version? (Required)

master

**Comment by glorv** [comment]
v7.5 and v8.1 are not affected as this bug is already fixed.
