### ISSUE TITLE
CASE WHEN does not correctly handle `null` value from JSON_EXTRACT

### ISSUE THREAD

**Issue by wd0517** [pingcap/tidb#45071]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
mysql> CREATE TABLE `t1` (`a` JSON);
Query OK, 0 rows affected (0.01 sec)

mysql> INSERT INTO `t1` VALUES ('{"key1": null}');
Query OK, 1 row affected (0.00 sec)

mysql> SELECT * FROM t1;
+----------------+
| a              |
+----------------+
| {"key1": null} |
+----------------+
1 row in set (0.09 sec)
```

### 2. What did you expect to see? (Required)

MySQL 5.7 & 8.0

```
mysql> SELECT CASE JSON_EXTRACT(t1.a, '$.key1') WHEN 'null' THEN NULL WHEN true THEN true ELSE false END FROM t1;
+--------------------------------------------------------------------------------------------+
| CASE JSON_EXTRACT(t1.a, '$.key1') WHEN 'null' THEN NULL WHEN true THEN true ELSE false END |
+--------------------------------------------------------------------------------------------+
|                                                                                       NULL |
+--------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> SELECT CASE JSON_EXTRACT(t1.a, '$.key1') WHEN 'null' THEN NULL WHEN true THEN true ELSE false END FROM t1;
+--------------------------------------------------------------------------------------------+
| CASE JSON_EXTRACT(t1.a, '$.key1') WHEN 'null' THEN NULL WHEN true THEN true ELSE false END |
+--------------------------------------------------------------------------------------------+
|                                                                                          0 |
+--------------------------------------------------------------------------------------------+
1 row in set (0.10 sec)
```

### 4. What is your TiDB version? (Required)

can be repoduced in both `v6.6.0-serverless` and `v7.2.0`
```
 Release Version: v6.6.0-serverless
Edition: Community
Git Commit Hash: ad5f5337f879e3b9e50b5bbca95d5b1604fc19a2
Git Branch: release-6.6-serverless
UTC Build Time: 2023-06-25 08:01:46
GoVersion: go1.19.4
Race Enabled: false
TiKV Min Version: 6.1.0
Check Table Before Drop: false
Store: tikv
```

**Comment by yibin87** [comment]
It is a type conversion issue, tidb convert 'null' as json binary, and then compare with json_extract return value; while mysql convert to string to compare:

mysql> select cast(JSON_EXTRACT(t1.a, '$.key1') as char)  = 'null'  from t1;
+------------------------------------------------------+
| cast(JSON_EXTRACT(t1.a, '$.key1') as char)  = 'null' |
+------------------------------------------------------+
|                                                    1 |
+------------------------------------------------------+
1 row in set (0.00 sec)

mysql> explain SELECT CASE JSON_EXTRACT(t1.a, '$.key1') WHEN 'null' THEN NULL WHEN true THEN true ELSE false END FRom t1;
+-------------------------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| id                      | estRows | task      | access object | operator info                                                                                                                                        |
+-------------------------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
| Projection_3            | 1.00    | root      |               | case(eq(json_extract(test.t1.a, $.key1), cast(null, json BINARY)), <nil>, eq(json_extract(test.t1.a, $.key1), cast(1, json BINARY)), 1, 0)->Column#3 |
| └─TableReader_5         | 1.00    | root      |               | data:TableFullScan_4                                                                                                                                 |
|   └─TableFullScan_4     | 1.00    | cop[tikv] | table:t1      | keep order:false, stats:pseudo                                                                                                                       |
+-------------------------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------+
3 rows in set (0.00 sec)

**Comment by XuHuaiyu** [comment]
Compare the extracted JSON value against the string `'null'`:
   ```sql
   SELECT JSON_EXTRACT(t1.a, '$.key1') = 'null' FROM t1;
   ```
   Output:
   ```
   +---------------------------------------+
   | JSON_EXTRACT(t1.a, '$.key1') = 'null' |
   +---------------------------------------+
   |                                     0 |
   +---------------------------------------+
   ```
   This confirms that JSON `null` is not equal to the string `'null'`.
   
   I doubt this is a bug of MySQL instead of TiDB.
   I reported a [bug#116688](https://bugs.mysql.com/bug.php?id=116688) to the mysql team, waiting for their verification.

**Comment by XuHuaiyu** [comment]
Verified to be a bug of MySQL.
<img width="1543" alt="截屏2024-11-18 14 55 15" src="https://github.com/user-attachments/assets/c1921123-c511-42c3-837c-bbac19c73d7a">
