### ISSUE TITLE
cannot update rows with irregular enum value

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#4514]
1. Insert irregular enum value in NON-STRICT MODE (e.g. value = 0).
2. Update other column in STRICT MODE.

In MySQL, the above operation is OK. In TiDB it fails.

**Comment by winkyao** [comment]
Is the other type have the same issue?

**Comment by breeswish** [comment]
@winkyao `set` should have similar issues. issues exist for all kind of datums that truncated value is still invalid (i.e. trunc(trunc(..)) throws error).
