### ISSUE TITLE
Unexpectedly remove useful flags in PR 7112

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tidb#45194]

**Comment by Defined2014** [comment]
Hello, could you add some explanations for this issue?

**Comment by xzhangxian1008** [comment]
Location: builtin_cast.go:1722

`tp.Flag |= expr.GetType().Flag & mysql.UnsignedFlag` removes the useful flag, for example, when the column is nullable, this operation will remove the column's nullable attribute.
