### ISSUE TITLE
Storing tikv data in-memory 

### ISSUE THREAD

**Issue by codophobia** [pingcap/tidb#4520]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
The tikv server has 8 cores and 8G of RAM.
I read [here](http://rocksdb.org/blog/2014/03/27/how-to-persist-in-memory-rocksdb-database.html) that we can store the RocksDb data into memory by mounting it on tmpfs. So, I tried doing it with docker by running the following command for running tikv.
```
docker run -d --name tikv1 \
  --mount type=tmpfs,destination=/data \
  -p 20160:20160 \
  -v /etc/localtime:/etc/localtime:ro \
  pingcap/tikv:latest \
  --addr="0.0.0.0:20160" \
  --advertise-addr="172.20.22.52:20160" \
  --data-dir="/data/tikv1" \
  --pd="172.20.22.148:2379"
```

I have also tried to directly create the RocksDb directory in the /dev/shm but even this doesn't increase the performance.
```
docker run -d --name tikv1 \
  -p 20160:20160 \
  -v /etc/localtime:/etc/localtime:ro \
  pingcap/tikv:latest \
  --addr="0.0.0.0:20160" \
  --advertise-addr="172.20.22.52:20160" \
  --data-dir="/dev/shm" \
  --pd="172.20.22.148:2379"
```
2. What did you expect to see?
I expected to see improvement in read performance as I was using RAM for data storage.

3. What did you see instead?
 I am using sysbench for benchmarking. The results were same as the one I got by mounting RocksDb data on disk.  I got around 13k QPS by mounting /data on disk. The same result i got when I mounted /data on tmpfs. 
**Sysbench result(mounting /data on tmpfs)**
```
OLTP test statistics:
    queries performed:
        read:                            794254
        write:                           0
        other:                           0
        total:                           794254
    transactions:                        794254 (13235.61 per sec.)
    deadlocks:                           0      (0.00 per sec.)
    read/write requests:                 794254 (13235.61 per sec.)
    other operations:                    0      (0.00 per sec.)

Test execution summary:
    total time:                          60.0089s
    total number of events:              794254
    total time taken by event execution: 15356.5498
    per-request statistics:
         min:                                  1.23ms
         avg:                                 19.33ms
         max:                                 89.28ms
         approx.  95 percentile:              36.36ms

Threads fairness:
    events (avg/stddev):           3102.5547/19.94
    execution time (avg/stddev):   59.9865/0.00
```

4. What version of TiDB are you using (`tidb-server -V`)?
Latest version.

**Comment by shenli** [comment]
@codophobia If you do not have many data in your sysbench test, tikv will cache also most all the data in memory. Please refer to the [TiKV Tuning docs](https://github.com/pingcap/docs/blob/master/op-guide/tune-TiKV.md).

Please provide the CPU usage during your test.

**Comment by codophobia** [comment]
@shenli CPU usage of tikv server or the server from which I am running tests?

**Comment by coocood** [comment]
@codophobia 
This means the disk I/O is not the bottleneck for sysbench when the dataset is smaller than memory.

**Comment by codophobia** [comment]
@coocood disk I/O is of course not the bottleneck since i am storing all the data in RAM. But the problem is it's not getting faster when I store the data in RAM. I got around 13k qps by storing data on disk(1ps, 1 tidb, 3tikv servers). But this doesn't increase even when I clear the cache and store all the data on RAM.

**Comment by coocood** [comment]
@codophobia 
I mean when you store the data on disk, I/O is not the bottle neck.
It's completely normal for a small dataset benchmark.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
