### ISSUE TITLE
Incompatible query results by TO_BASE64 function

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#45253]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```SQL
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (c1 INT);
INSERT INTO t1 VALUES (1);
SELECT c1 FROM t1 WHERE TO_BASE64('牵'); -- actual: {}, expected: {1}
```
### 2. What did you expect to see? (Required)
SELECT returns the value {1}.
### 3. What did you see instead (Required)
SELECT returns empty.
### 4. What is your TiDB version? (Required)

Release Version: v7.2.0
Edition: Community
Git Commit Hash: 9fd5f4a8e4f273a60fbe7d3848f85a1be8f0600b
Git Branch: heads/refs/tags/v7.2.0
UTC Build Time: 2023-06-27 15:04:42
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by jebter** [comment]
TiDB root@127.0.0.1:test> DROP TABLE IF EXISTS t1;
                       -> CREATE TABLE t1 (c1 INT);
                       -> INSERT INTO t1 VALUES (1);
                       -> SELECT c1 FROM t1 WHERE TO_BASE64('牵'); 
You're about to run a destructive command.
Do you want to proceed? (y/n): y
Your call!
Query OK, 0 rows affected
Time: 0.467s

Query OK, 0 rows affected
Time: 0.135s

Query OK, 1 row affected
Time: 0.037s

+----+
| c1 |
+----+
| 1  |
+----+

1 row in set
Time: 0.003s
TiDB root@127.0.0.1:test> select tidb_version() \G
***************************[ 1. row ]***************************
tidb_version() | Release Version: v7.1.0
Edition: Community
Git Commit Hash: 635a4362235e8a3c0043542e629532e3c7bb2756
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-30 10:50:03
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

1 row in set
Time: 0.001s

**Comment by windtalker** [comment]
It seems to related to plan cache:
```
mysql> set tidb_enable_non_prepared_plan_cache=0;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT c1 FROM t1 WHERE TO_BASE64('牵');
+------+
| c1   |
+------+
|    1 |
+------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+------------------------------------------+
| Level   | Code | Message                                  |
+---------+------+------------------------------------------+
| Warning | 1292 | Truncated incorrect DOUBLE value: '54m1' |
+---------+------+------------------------------------------+
1 row in set (0.00 sec)

mysql> set tidb_enable_non_prepared_plan_cache=1;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT c1 FROM t1 WHERE TO_BASE64('牵');
Empty set, 2 warnings (0.00 sec)

mysql> show warnings;
+---------+------+----------------------------------------+
| Level   | Code | Message                                |
+---------+------+----------------------------------------+
| Warning | 1406 | Data Too Long, field len 0, data len 4 |
| Warning | 1292 | Truncated incorrect DOUBLE value: ''   |
+---------+------+----------------------------------------+
2 rows in set (0.00 sec)
```
Change the component to planner.

**Comment by qw4990** [comment]
The root cause is that the `Flen` of `to_base64` is not set correctly, so these 2 plans (there is a new but equivalent plan if the `non-prep` is enabled) cause different results.

**Comment by kennedy8312** [comment]
Regression Analysis
The issue happened on v7.2.0 but not v7.1.0.
