### ISSUE TITLE
Nullable(Int32) cannot be inside Nullable column when rollup

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#45273]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tpcds 10 scale with tiflash replica
query 18 and 27 raise error for `ERROR 1105 (HY000) at line 2: other error for mpp stream: Code: 44, e.displayText() = DB::Exception: Nullable(Int32) cannot be inside Nullable column, e.what() = DB::Exception`
### 4. What is your TiDB version? (Required)

Release Version: v7.3.0-alpha
Edition: Community
Git Commit Hash: 2b3abcdc74832eed9a71c6a025898cdc13d2e7d2
Git Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time: 2023-07-08 11:11:32
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by AilinKid** [comment]
seems the same as https://github.com/pingcap/tidb/issues/45275 after comparing the sql
