### ISSUE TITLE
Illegal types String and Decimal(10,0) of arguments of function multiply when rollup

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#45276]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tpcds 10 scale with tiflash replica
query 67 raises error for `ERROR 1105 (HY000) at line 2: other error for mpp stream: Code: 43, e.displayText() = DB::Exception: Illegal types String and Decimal(10,0) of arguments of function multiply, e.what() = DB::Exception`
### 4. What is your TiDB version? (Required)

Release Version: v7.3.0-alpha
Edition: Community
Git Commit Hash: 2b3abcdc74832eed9a71c6a025898cdc13d2e7d2
Git Branch: heads/refs/tags/v7.3.0-alpha
UTC Build Time: 2023-07-08 11:11:32
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by AilinKid** [comment]
the minimal reproduce case is as follows:
```
step1: source tpcds.sql from tidb-bench repo
step2: set necessary nightly tiflash envir
step3: select i_category,  sum(coalesce(ss_sales_price*ss_quantity,0)) sumsales     from store_sales     ,store     ,item     where       ss_item_sk=i_item_sk         and ss_store_sk = s_store_sk          group by i_category  with rollup;
```
