### ISSUE TITLE
lightning: meet "[PD:client:ErrClientTSOStreamClosed]encountered TSO stream being closed unexpectedly" during checksum

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#45301]
## Enhancement
in lightning 7.1.0 we met this error during get TSO before checksum for some table, but for other table it success. seems a retryable error, maybe we should add a retry to it

```
[2023/07/11 09:22:31.869 +00:00] [ERROR] [checksum_helper.go:83] ["remote checksum failed"] [table=t] [takeTime=54.710221ms] [error="fetch tso from pd failed: [PD:client:ErrClientTSOStreamClosed]encountered TSO stream being closed unexpectedly"]
```

**Comment by lance6716** [comment]
Oh I should pick https://github.com/pingcap/tidb/pull/44478 + https://github.com/pingcap/tidb/pull/44856 to release version 😂

**Comment by D3Hunter** [comment]
it's another error, `pd.IsLeaderChange` return false explicitly on it

**Comment by lance6716** [comment]
> ErrClientTSOStreamClosed

But the log says it's ErrClientTSOStreamClosed, and pd.IsLeaderChange will return true for it?

**Comment by D3Hunter** [comment]
you're right, i see it wrong😅

**Comment by lance6716** [comment]
No I mean I didn't pick https://github.com/pingcap/tidb/pull/44478 + https://github.com/pingcap/tidb/pull/44856 to release version 😂 If this is needed I can start cherry-pick

**Comment by D3Hunter** [comment]
yes, let's cp those 2.

**Comment by D3Hunter** [comment]
duplicate with https://github.com/pingcap/tidb/issues/44263
