### ISSUE TITLE
All the query by id result is incorrect due to the upgrade (5.2.3->5.4.3)

### ISSUE THREAD

**Issue by LemonRzx** [pingcap/tidb#45321]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
All the query by id result is incorrect due to the upgrade (5.2.3->5.4.3)

CREATE TABLE `temp_table` (
  `id` int(11) NOT NULL,
  `c` int(11) DEFAULT NULL,
  `d` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `c` (`c`)
) ENGINE=InnoDB;

insert into temp_table values (5,5,5),
(10,10,10),(15,15,15),(20,20,20),(25,25,25);

PREPARE stmt FROM 'select id,c,d from temp_table WHERE ( id in (?) )';
SET @1 = 10;
EXECUTE stmt USING @1;

SET @2 = 20;
EXECUTE stmt USING @2;
### 2. What did you expect to see? (Required)
![image](https://github.com/pingcap/tidb/assets/46312585/e150d196-210b-4729-ba15-749c2c870c54)
### 3. What did you see instead (Required)
![image](https://github.com/pingcap/tidb/assets/46312585/3d2813a4-6778-4194-9eec-2f2607c78f7a)

### 4. What is your TiDB version? (Required)
![image](https://github.com/pingcap/tidb/assets/46312585/ae8611ec-340c-48af-8e48-35345cf5fd69)

+--------------------+
| VERSION()          |
+--------------------+
| 5.7.25-TiDB-v5.4.3 |
+--------------------+

**Comment by qw4990** [comment]
This issue has been fixed on `v6.1` by this PR https://github.com/pingcap/tidb/pull/34739. I'll pick it back to the next version of `v5.4`.

**Comment by qw4990** [comment]
There is already a `v5.4` cherry-pick https://github.com/pingcap/tidb/pull/34782. I'll merge it this week.

**Comment by chrysan** [comment]
Close it since https://github.com/pingcap/tidb/pull/34782 is merged.
