### ISSUE TITLE
“process” is not allowed being as column name

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#4538]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`create table a (process double);`

2. What did you expect to see?
```
mysql> create table a (process double);
Query OK, 0 rows affected (0.05 sec)

mysql> desc a;
+---------+--------+------+-----+---------+-------+
| Field   | Type   | Null | Key | Default | Extra |
+---------+--------+------+-----+---------+-------+
| process | double | YES  |     | NULL    |       |
+---------+--------+------+-----+---------+-------+
1 row in set (0.00 sec)
```

3. What did you see instead?
```
MySQL [renee]> create table a (process double);
ERROR 1105 (HY000): line 0 column 23 near " double)" (total length 31)
MySQL [renee]> create table a (processa double);
Query OK, 0 rows affected (0.16 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: 0.8.0
Git Commit Hash: f4799b54328212bf725875fe580dc523484b1402
Git Commit Branch: pre-ga
UTC Build Time:  2017-09-13 10:34:15

**Comment by coocood** [comment]
Thank you for your report, it will be fixed soon.
