### ISSUE TITLE
region is stale

### ISSUE THREAD

**Issue by luoruixing** [pingcap/tidb#4546]
when i select a table like "select * from TABLE limit 5"

i see this error : 
ERROR 1105 (HY000): [try again later]: backoffer.maxSleep 15000ms is exceeded, errors:
message:"region is stale" stale_epoch:<new_regions:<id:2 start_key:"t\200\000\000\000\000\000\001C_r\200\000\000\000\000\000\007\310" end_key:"" region_epoch:<conf_ver:3 version:169 > peers:<id:3 store_id:1 > peers:<id:6 store_id:4 > peers:<id:7 store_id:5 > > new_regions:<id:1609 start_key:"t\200\000\000\000\000\000\0018_i\200\000\000\000\000\000\000\001\0017A5C3717\377-1267-46\37793-9D7D-\377030B3F80\377DAFD\000\000\000\000\373" end_key:"

how can i fix this table ? i restart tikv ,but not work

**Comment by coocood** [comment]
Are you inserting rows to the table when you select it?

**Comment by luoruixing** [comment]
Yes , How can I solve this problem？

**Comment by coocood** [comment]
Which version is the TiKV?

**Comment by luoruixing** [comment]
rc4,i will try ga now

**Comment by shenli** [comment]
@luoruixing Feel free to reopen this issue if you meet this error in the latest TiDB.
