### ISSUE TITLE
unstable TestAddIndexIngestMemoryUsage

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#45483]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/pull/45471

[ci.log](https://github.com/pingcap/tidb/files/12103347/ci.log)

### 3. What did you see instead (Required)

```
    integration_test.go:66: 
        	Error Trace:	tests/realtikvtest/addindextest/integration_test.go:66
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 176
        	Test:       	TestAddIndexIngestMemoryUsage
```

And I found two `create one backend for an DDL job` while one `close one backend for DDL job`

**Comment by tangenta** [comment]
This issue has not been reproduced recently.
