### ISSUE TITLE
Connection is unavailabel after inserting some random data using Tidb-bench

### ISSUE THREAD

**Issue by yeyuqiang** [pingcap/tidb#4548]
1. What did you do?
I have built a tidb cluster with 1 tidb server, 2 pd server and 3 tikv server.
I built the cluster by TiDB-ansible following the doc except I using HDD(about 1T each TiKV node) not SDD

2. What did you expect to see?
The tidb works well even whatever how much data inserted.

3. What did you see instead?
After inserting the data to about 350G , an error occured as below:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable

And also there's some error log in tikv.log
2017/09/18 10:06:06.493 util.rs:418: [ERROR] failed to connect to http://<MY_TIDB_HOST_IP>:2379, Grpc(RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") }))

And another error info:
[tidb@host0101 sysbench]$ mysql -u root -h <MY_TIDB_HOST_IP> -P 4000
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MySQL connection id is 56
Server version: 5.7.1-TiDB-0.8.0

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MySQL [(none)]> show databases;
ERROR 1105 (HY000): [try again later]: backoffer.maxSleep 5000ms is exceeded, errors:
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
get timestamp failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable
MySQL [(none)]>

4. What version of TiDB are you using (`tidb-server -V`)?
TiKV
Release Version:   0.9.0
Git Commit Hash:   f1266629a54e4725045fe7442142a02e857ce2ff
Git Commit Branch: pre-ga
UTC Build Time:    2017-09-12 03:05:27
Rust Version:      1.21.0-nightly (215e0b10e 2017-08-08)

Would you mind give some help about it?

**Comment by coocood** [comment]
It seems like PD is down, have you checked the PD log?

**Comment by yeyuqiang** [comment]
Thank you. And sorry for the wrong description, Currently I just have 1 pd server.
The msg from pd.log as below:
2017/09/18 11:49:54.415 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000240916s err context deadline exceeded
2017/09/18 11:49:54.433 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000186925s err context deadline exceeded
2017/09/18 11:49:54.987 log.go:80: [warning] rafthttp: [health check for peer b41cfdc97bc2af6d could not connect: read tcp 172.16.0.11:44666->172.16.1.57:2380: read: connection reset by peer]
2017/09/18 11:49:54.987 log.go:80: [warning] rafthttp: [the clock difference against peer b41cfdc97bc2af6d is too high [2.147167083s > 1s]]
2017/09/18 11:49:55.415 log.go:84: [info] etcdserver/api/v3rpc: [grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"]
2017/09/18 11:49:55.415 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.00030967s err context deadline exceeded
2017/09/18 11:49:55.707 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000170373s err context deadline exceeded
2017/09/18 11:49:55.707 leader.go:71: [error] get leader err context deadline exceeded
2017/09/18 11:49:56.063 log.go:80: [warning] rafthttp: [health check for peer 5731c08dde3ca83a could not connect: dial tcp 172.16.1.55:2380: getsockopt: connection refused]
2017/09/18 11:49:56.416 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000230232s err context deadline exceeded
2017/09/18 11:49:56.416 log.go:84: [info] etcdserver/api/v3rpc: [grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"]
2017/09/18 11:49:56.434 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000167756s err context deadline exceeded
2017/09/18 11:49:57.390 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000196141s err context deadline exceeded
2017/09/18 11:49:57.390 log.go:84: [info] etcdserver/api/v3rpc: [grpc: Server.processUnaryRPC failed to write status: stream error: code = DeadlineExceeded desc = "context deadline exceeded"]
2017/09/18 11:49:57.416 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000205249s err context deadline exceeded
2017/09/18 11:49:58.416 kv.go:261: [warning] kv gets too slow: key /pd/6465538042065301674/leader cost 10.000298884s err context deadline exceeded
2017/09/18 11:49:58.446 log.go:84: [info] raft: [e20f09c0da93b2f2 is starting a new election at term 11561]
2017/09/18 11:49:58.446 log.go:84: [info] raft: [e20f09c0da93b2f2 became candidate at term 11562]
2017/09/18 11:49:58.446 log.go:84: [info] raft: [e20f09c0da93b2f2 received MsgVoteResp from e20f09c0da93b2f2 at term 11562]
2017/09/18 11:49:58.446 log.go:84: [info] raft: [e20f09c0da93b2f2 [logterm: 112, index: 97889] sent MsgVote request to 5731c08dde3ca83a at term 11562]
2017/09/18 11:49:58.446 log.go:84: [info] raft: [e20f09c0da93b2f2 [logterm: 112, index: 97889] sent MsgVote request to b41cfdc97bc2af6d at term 11562]

**Comment by coocood** [comment]
Have you checked disk I/O with `iostats`?
Are you still inserting data when those errors occurred?

**Comment by yeyuqiang** [comment]
No, I am unable to insert any data now.
I saw the kB_read/s is only 1.05 in my PD server. and other as below.

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          10.51    0.00    1.84    0.18    0.00   87.46

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda              11.11         1.05       536.73     351260  179930440

All the tikv iostat info looks like:
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           6.35    0.00    2.03    0.73    0.00   90.89

Device:            tps    kB_read/s    kB_wrtn/s    kB_read    kB_wrtn
sda              56.45       382.08     20715.47  128043874 6942157880

According the error log, Does it mean that my PD server is too slow to find the data address from the TiKV server ?

**Comment by siddontang** [comment]
@yeyuqiang 

You said you have 2 PDs, but what `Currently I just have 1 pd server` means? do you close a PD?

**Comment by yeyuqiang** [comment]
@siddontang 
`I have built a tidb cluster with 1 tidb server, 2 pd server and 3 tikv server.`
I made a wrong description here, only 1 pd server.

**Comment by yeyuqiang** [comment]
I have inserted some data after rebuilding the cluster with some new machine. Still 1 tidb 1 pd 3 tikv
And another issue occured
`MySQL [test]> select count(1) from sbtest1;
ERROR 1105 (HY000): [try again later]: backoffer.maxSleep 20000ms is exceeded, errors:
message:"region is stale" stale_epoch:<new_regions:<id:136 start_key:"t\200\000\000\000\000\000\000\033_r\200\000\000\000\003J\237\230" end_key:"t\200\000\000\000\000\000\000\036_i\200\000\000\000\000\000\000\001\004\000\000\000\000\000\344\260\323\003\200\000\000\000\000\001r\n" region_epoch:<conf_ver:3 version:64 > peers:<id:137 store_id:1 > peers:<id:138 store_id:5 > peers:<id:139 store_id:4 > > new_regions:<id:3696 start_key:"t\200\000\

MySQL [test]> select * from sbtest1 limit 1;
+----+---------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| id | k       | c                                                                                                                       | pad                                                         |
+----+---------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|  1 | 5017637 | 66714608002-34855419412-84677238132-51704661573-51853598660-27180683576-27990676155-99831046215-46316470441-79779968328 | 24644591058-78294168486-87942339777-16123355995-46830956931 |
+----+---------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
1 row in set (0.00 sec)

`

**Comment by shenli** [comment]
How many machines do you use to deploy tikv servers? Do you have SSD?

**Comment by yeyuqiang** [comment]
3 tikv, I did not use SSD. Is SSD a must ? Currently SSD is not available for me

**Comment by shenli** [comment]
You deploy 3 tikv-servers on separate disks?

**Comment by yeyuqiang** [comment]
yes

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
