### ISSUE TITLE
Remove getRegions call by lightning in physical import mode

### ISSUE THREAD

**Issue by mittalrishabh** [pingcap/tidb#45507]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

When lightning runs in physical import mode, it runs this sql query

SELECT REGION_ID, APPROXIMATE_SIZE FROM information_schema.TIKV_REGION_STATUS WHERE TABLE_ID = ?

This call is made by each lightning process in parallel import mode and by multiple worker threads in a lightning process. It can potentially overload the PD if number of regions are too many. However, it appears that this call may be unnecessary since its purpose is to display a warning message and increment a counter in the SplitAndScatterRegionByRanges() function. Considering that lightning physical import always operates on a new table, splitting the new region should not pose any harm. 

### 2. What did you expect to see? (Required)
Less number of get region calls to PD
### 4. What is your TiDB version? (Required)
6.5

**Comment by AndreMouche** [comment]
It is a bug in this version since we have  https://github.com/pingcap/tidb/issues/39605 .
Meanwhile,As the @mittalrishabh  mentioned, is it necessary to take the region of the new table here? Is there any room for optimization?

**Comment by AndreMouche** [comment]
@niubell Please take a look, thanks

**Comment by lance6716** [comment]
Yes, seems the correct behaviour is `continue` the loop for a `skippedKey`

https://github.com/pingcap/tidb/blob/9e202089134da39a8445305fefba33ee42c529a1/br/pkg/lightning/backend/local/localhelper.go#L343-L364

But since we don't have a `continue` in code and everything works fine, I think remove the whole checking logic is acceptable. PTAL @niubell

**Comment by kennytm** [comment]
hi @niubell any update on this issue? thanks

**Comment by mittalrishabh** [comment]
I am going to create a PR for this issue. I have tested it internally.

**Comment by lance6716** [comment]
@mittalrishabh thanks!

**Comment by mittalrishabh** [comment]
filed PR https://github.com/pingcap/tidb/pull/46202
