### ISSUE TITLE
[Dynamic Regions] br: pitr task in error "retry time exceeds: error failed to get initial snapshot"

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#45517]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. open pitr task in partitioned raft kv cluster

### 3. What did you see instead (Required)
task error failed to get the snapshot (region_id = 1538): Error during requesting raftstore: message: "read index not ready, reason can not read index due to merge, region 1538
### 4. What is your TiDB version? (Required)
master

**Comment by tonyxuqqi** [comment]
https://github.com/tikv/tikv/pull/15243 should fix the merge issue.

**Comment by BornChanger** [comment]
@AkiraXie  Can you please verify if https://github.com/tikv/tikv/pull/15243 fixed the problem?

**Comment by AkiraXie** [comment]
> @AkiraXie Can you please verify if [tikv/tikv#15243](https://github.com/tikv/tikv/pull/15243) fixed the problem?

regression test shows the issue still exists

**Comment by BornChanger** [comment]
@AkiraXie PRs for Issue https://github.com/tikv/tikv/issues/15198 are just merged. Please check if the problem for this issue is fixed.

**Comment by AkiraXie** [comment]
tikv/tikv#15441 may resolve the issue ，so await the pr merged

**Comment by BornChanger** [comment]
https://github.com/tikv/tikv/pull/15441 is merged, can you check if the problem is fixed? @AkiraXie

**Comment by AkiraXie** [comment]
after https://github.com/tikv/tikv/pull/15441 merged ,and the issue is resolved
