### ISSUE TITLE
integration-common-test "SELECT SUM( (SELECT COUNT(a) FROM t2) ) FROM t1;" failed

### ISSUE THREAD

**Issue by overvenus** [pingcap/tidb#4556]
1. What did you do?
If possible, provide a recipe for reproducing the error.

`SELECT SUM( (SELECT COUNT(a) FROM t2) ) FROM t1;`

The detailed log can be found in http://45.249.247.133:8080/blue/organizations/jenkins/tikv_ghpr_integration_common_test/detail/tikv_ghpr_integration_common_test/21/pipeline#step-101-log-14

2. What did you expect to see?

```
SELECT SUM( (SELECT COUNT(a) FROM t2) ) FROM t1;
Error 1111: Invalid use of group fu
```

3. What did you see instead?

```
SELECT SUM( (SELECT COUNT(a) FROM t2) ) FROM t1;
SUM( (SELECT COUNT(a) FROM t2) )
0
```

**Comment by shenli** [comment]
@overvenus I could not see the version of tidb-server and tidb-test.

**Comment by shenli** [comment]
Please pull the latest code for tidb-test.
