### ISSUE TITLE
flaky test TestStatsLockAndUnlockTables

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#45615]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/28988/pipeline

in PR https://github.com/pingcap/tidb/pull/45480

**Comment by hawkingrei** [comment]
I think it has been fixed by https://github.com/pingcap/tidb/pull/45616.
