### ISSUE TITLE
slices.SortFunc API change breaks build

### ISSUE THREAD

**Issue by aaronbee** [pingcap/tidb#45629]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Update golang.org/x/exp dependency to latest.

### 2. What did you expect to see? (Required)

Successful build.

### 3. What did you see instead (Required)

Build failures due to API change for golang.org/x/exp/slices.SortFunc. SortFunc now takes a compare function (returns <= -1 for less, 0 for equal, >= 1 for greater) instead of a less function (returns true for less, false for greater than or equal).

See new API here: https://pkg.go.dev/golang.org/x/exp@v0.0.0-20230725093048-515e97ebf090/slices#SortFunc

Commit that introduced breaking change here: https://cs.opensource.google/go/x/exp/+/302865e7556b4ae5de27248ce625d443ef4ad3ed

### 4. What is your TiDB version? (Required)

master

**Comment by hawkingrei** [comment]
@aaronbee  Thank you for your report. We should upgrade to version 1.21 immediately. With its release, we can switch it to the standard library.

**Comment by joeycumines** [comment]
This is a significantly greater issue for anyone importing the parser module / parser driver implementation.

I've fixed it for that use case in a fork as a workaround. I didn't change all the other usages of `slices.SortFunc`, though, so I can't make a PR (it breaks the rest of the build).

Incomplete fixes, sufficient to get the parser + parser driver working: https://github.com/joeycumines/tidb/commit/2af76fb26a9f5e1d38625a5bf9b122ac5477218f

**Comment by gonnafaraway** [comment]
@hawkingrei 
Hi! Seems issue can be closed.

**Comment by StevenACoffman** [comment]
See #46373
