### ISSUE TITLE
tikv server disk I/O is too slow

### ISSUE THREAD

**Issue by weiweinews01** [pingcap/tidb#4563]
TASK [machine_benchmark : Preflight check - Does the write speed of tikv deploy_dir disk meet requirement] ************************************************************
fatal: [10.20.0.184]: FAILED! => {"changed": false, "failed": true, "msg": "dd: the write speed of tikv deploy_dir disk is too slow: 8.7 MB/s < 15 MB/s"}
fatal: [10.20.0.185]: FAILED! => {"changed": false, "failed": true, "msg": "dd: the write speed of tikv deploy_dir disk is too slow: 8.3 MB/s < 15 MB/s"}
fatal: [10.20.0.186]: FAILED! => {"changed": false, "failed": true, "msg": "dd: the write speed of tikv deploy_dir disk is too slow: 7.8 MB/s < 15 MB/s"}
        to retry, use: --limit @retry_files/bootstrap.retry

**Comment by shenli** [comment]
@weiweinews01 Please use better disk to deploy tikv.

PS: Please use English in this repo.

**Comment by LinuxGit** [comment]
Hi, the write speed of your disk is too slow. For OLTP scenarios, it is strongly recommended to use SSD disks for TiKV and PD, or there might be performance issues. You can change `machine_benchmark = True` to `machine_benchmark = False` to skip the check.
