### ISSUE TITLE
unstable test TestLFUFreshMemUsage

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#45649]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
=== RUN   TestLFUFreshMemUsage

    lfu_cache_test.go:60: 

        	Error Trace:	statistics/handle/cache/internal/lfu/lfu_cache_test.go:60

        	Error:      	Not equal: 

        	            	expected: 60

        	            	actual  : 52

        	Test:       	TestLFUFreshMemUsage

--- FAIL: TestLFUFreshMemUsage (0.00s)

```

**Comment by tiancaiamao** [comment]
It's still unstable ... or, it fails stably


cd statistics/handle/cache/internal/lfu
go test -run  TestLFUFreshMemUsage 
--- FAIL: TestLFUFreshMemUsage (0.00s)
    lfu_cache_test.go:81: 
                Error Trace:    /home/genius/project/src/github.com/pingcap/tidb/statistics/handle/cache/internal/lfu/lfu_cache_test.go:81
                Error:          Not equal: 
                                expected: 0x30
                                actual  : 0x0
                Test:           TestLFUFreshMemUsage
FAIL
exit status 1
FAIL    github.com/pingcap/tidb/statistics/handle/cache/internal/lfu    0.018s

**Comment by tiancaiamao** [comment]
On master barnch, it need the --tags intest flag to run.
