### ISSUE TITLE
Deploy TiDB meet error

### ISSUE THREAD

**Issue by weiweinews01** [pingcap/tidb#4565]
TASK [check_config_dynamic : Preflight check - System Time] ***********************************************************************************************************
fatal: [10.20.0.185]: FAILED! => {"changed": false, "failed": true, "msg": "System clock is wrong relative to current host: -7 seconds."}
fatal: [10.20.0.182]: FAILED! => {"changed": false, "failed": true, "msg": "System clock is wrong relative to current host: -8 seconds."}
fatal: [10.20.0.184]: FAILED! => {"changed": false, "failed": true, "msg": "System clock is wrong relative to current host: -8 seconds."}
fatal: [10.20.0.181]: FAILED! => {"changed": false, "failed": true, "msg": "System clock is wrong relative to current host: -8 seconds."}
fatal: [10.20.0.186]: FAILED! => {"changed": false, "failed": true, "msg": "System clock is wrong relative to current host: -8 seconds."}

**Comment by shenli** [comment]
Please use ntp to synchronize time among machines.

**Comment by weiweinews01** [comment]
[root@mysql01 tidb-ansible-master]# for host in mysql01 mysql02 mysql03 mysql04 mysql05 mysql06; do ssh $host date; done
Tue Sep 19 14:44:05 CST 2017
Tue Sep 19 14:44:06 CST 2017
Tue Sep 19 14:44:06 CST 2017
Tue Sep 19 14:44:06 CST 2017
Tue Sep 19 14:44:06 CST 2017
Tue Sep 19 14:44:06 CST 2017

**Comment by weiweinews01** [comment]
[root@mysql01 tidb-ansible-master]# for host in mysql01 mysql02 mysql03 mysql04 mysql05 mysql06; do ssh $host "crontab -l"; done
* * * * * ntpupdate 10.20.0.181
* * * * * ntpupdate 10.20.0.181
* * * * * ntpupdate 10.20.0.181
* * * * * ntpupdate 10.20.0.181
* * * * * ntpupdate 10.20.0.181

**Comment by LinuxGit** [comment]
You can change `max_time_diff_seconds: 5` to `max_time_diff_seconds: 30` in `tidb-ansible/roles/check_config_dynamic/defaults/main.yml` file to skip this error. We'll fix the check later.
