### ISSUE TITLE
TestHashChunkRow failed on arm64

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tidb#45686]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

on Linux localhost.localdomain 4.18.0-305.10.2.el7.aarch64 
execute：
go test -v --run=TestHashChunkRow

### 2. What did you expect to see? (Required)

<img width="592" alt="image" src="https://github.com/pingcap/tidb/assets/97376271/a3ac4a5e-bda2-411e-b7b1-0de52ead3ac0">

### 3. What did you see instead (Required)
<img width="791" alt="image" src="https://github.com/pingcap/tidb/assets/97376271/89e9b839-1bba-4a4f-9312-72e7cfac12c9">

### 4. What is your TiDB version? (Required)

master

**Comment by YangKeao** [comment]
TiDB uses a quite magic way to detect whether a numeric will loss precision while converting to float, see `BinaryJSON.HashValue`:

```
	case JSONTypeCodeUint64:
		if bj.GetUint64() == uint64(float64(bj.GetUint64())) {
			buf = append(buf, JSONTypeCodeFloat64)
			buf = appendBinaryFloat64(buf, float64(bj.GetUint64()))
		} else {
			buf = append(buf, bj.TypeCode)
			buf = append(buf, bj.Value...)
		}
```

It seems that it doesn't work well on arm64 (but I'm not sure whether it doesn't work well for some special cases or all cases). I'll take a look later.

**Comment by YangKeao** [comment]
> TiDB uses a quite magic way to detect whether a numeric will loss precision while converting to float, see `BinaryJSON.HashValue`:
> 
> ```
> 	case JSONTypeCodeUint64:
> 		if bj.GetUint64() == uint64(float64(bj.GetUint64())) {
> 			buf = append(buf, JSONTypeCodeFloat64)
> 			buf = appendBinaryFloat64(buf, float64(bj.GetUint64()))
> 		} else {
> 			buf = append(buf, bj.TypeCode)
> 			buf = append(buf, bj.Value...)
> 		}
> ```
> 
> It seems that it doesn't work well on arm64 (but I'm not sure whether it doesn't work well for some special cases or all cases). I'll take a look later.

For some big enough values, the `uint64(float64(x)))` always returned `MaxUint64`. It's a special case.

**Comment by YangKeao** [comment]
This issue not only affects arm64, it also affects x86_64. They are just different cases:

```
testHashChunkRowEqual(t, types.CreateBinaryJSON(int64(math.MinInt64)), types.CreateBinaryJSON(float64(math.MinInt64)), false)
```

This test will fail on x86_64 :facepalm: . I'll fix them all.
