### ISSUE TITLE
alter table error :  Invalid %!!(string=column)s(MISSING) state: %!!(model.SchemaState=5)v(MISSING)

### ISSUE THREAD

**Issue by bob34007** [pingcap/tidb#45744]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
create table variables_info  like  information_schema.variables_info;
alter table variables_info modify min_value varchar(200);

### 2. What did you expect to see? (Required)
alter table success
### 3. What did you see instead (Required)
ERROR 8210 (HY000): DDL job rollback, error msg: Invalid %!!(string=column)s(MISSING) state: %!!(model.SchemaState=5)v(MISSING)
### 4. What is your TiDB version? (Required)
 Release Version: v6.5.2
Edition: Community
Git Commit Hash: 29116c0256c52b224da2b34d712c1063d171c0ad
Git Branch: heads/refs/tags/v6.5.2
UTC Build Time: 2023-04-19 10:52:30
GoVersion: go1.19.8
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by zimulala** [comment]
At present, it is the `MaxColumnID` of the table in the `information_schema` database, which affects `modify column`, `add column`(this action has no problem in behavior, but can cause problems with column ids that are not unique)
. 
The table under `metrics_schema` has a similar problem, and the table under `performance_schema` does not.
