### ISSUE TITLE
 does Tidb support float  Vector dtype for Deep learning?

### ISSUE THREAD

**Issue by mullerhai** [pingcap/tidb#45803]
Hi ,I want to use Tidb store Embeddig Data,but I do not know  if it support or not

**Comment by winoros** [comment]
https://github.com/pingcap/tidb/issues/21647 
You can view this issue for tracking. It's not supported yet.

**Comment by mullerhai** [comment]
> #21647 You can view this issue for tracking. It's not supported yet.

I  want to know  ping use which Vector DB? milvus?

**Comment by mullerhai** [comment]
> > > #21647 You can view this issue for tracking. It's not supported yet.
> > 
> > 
> > I want to know ping use which Vector DB? milvus?
> 
> We haven't had a clear plan for it. So it's not decided yet whether to implement it by TiDB self or integrate with another open source project.

thanks

**Comment by shizn** [comment]
@mullerhai thanks for your request. Please check the updates in https://github.com/pingcap/tidb/issues/21647. We have a private beta environment for Vector datatype and search functionalities. Let us know if you are interested!
