### ISSUE TITLE
tidb oom for add clustered index

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#45816]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
[running_sql.txt](https://github.com/pingcap/tidb/files/12257974/running_sql.txt)

### 2. What did you expect to see? (Required)
add index execute successfully
### 3. What did you see instead (Required)
tidb oom
![20230804-145558](https://github.com/pingcap/tidb/assets/53471087/5ce0e759-88ab-4bce-a6a8-ecb58091e851)

### 4. What is your TiDB version? (Required)

v7.3.0

**Comment by seiya-annie** [comment]
[record2023-08-02T16:26:07Z.tar.gz](https://github.com/pingcap/tidb/files/12258012/record2023-08-02T16.26.07Z.tar.gz)

**Comment by lance6716** [comment]
![image](https://github.com/pingcap/tidb/assets/1689766/07731b82-7fc6-4216-aadd-fcd4a6a02855)

**Comment by seiya-annie** [comment]
After increasing the cpu configuration, the test passed.
