### ISSUE TITLE
"select * from table_name limit 10" will not always return first 10 rows data

### ISSUE THREAD

**Issue by yeyuqiang** [pingcap/tidb#4584]
1. What did you do?
select * from sbtest1 limit 10;

2. What did you expect to see?
always display first 10 rows data

3. What did you see instead?
the result changed when I run "select * from sbtest1 limit 10" serveral times

4. What version of TiDB are you using (`tidb-server -V`)?
pre-ga

**Comment by winoros** [comment]
If there isn't any `order by` clause, TiDB won't guarantee the order of returned row.

**Comment by yeyuqiang** [comment]
ok, got it
