### ISSUE TITLE
variable naming, meaningless prefix `nm`

### ISSUE THREAD

**Issue by okJiang** [pingcap/tidb#45851]
## Enhancement

https://github.com/pingcap/tidb/blob/de308048e240549f45cd434a9ade2bb5150f8140/tidb-server/main.go#L91-L132

should remove the prefix or change the prefix to `flag`

**Comment by okJiang** [comment]
If it should be, I can file a pr.

**Comment by gonnafaraway** [comment]
@okJiang 
Hi! It looks like prefix can't be removed cause of variables naming, also flag prefix does nothing to naming logic. Seems issue can be closed.

**Comment by okJiang** [comment]
Yes, I agree with you
