### ISSUE TITLE
No error is reported when the database name is empty

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tidb#45873]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table ``.ttt2(id int key);

### 2. What did you expect to see? (Required)
 mysql> create table ``.ttt2(id int key);
ERROR 1102 (42000): Incorrect database name ''

### 3. What did you see instead (Required)
mysql> create table ``.ttt2(id int key);
Query OK, 0 rows affected (0.03 sec)

### 4. What is your TiDB version? (Required)

Release Version: v7.4.0-alpha-21-gcd4cbcd742
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/cd4cbcd7422f133d88ffc87a41d077d9d8b07bb1
Git Branch: master
UTC Build Time: 2023-08-07 08:11:41
GoVersion: go1.20.5
Race Enabled: false
Check Table Before Drop: false
Store: unistore |

**Comment by git-hulk** [comment]
Hi @djshow832 Can I take this issue?

**Comment by tonisanta** [comment]
Hello! Seems it's allowing to have empty database and table names. So how would you like to solve it? When parsing stmt or have a later on validation?

**Comment by xmh1011** [comment]
I'd like to fix this issue, can you assign me? @djshow832 @keeplearning20221
