### ISSUE TITLE
bulk copy在将来是否可以实现回退

### ISSUE THREAD

**Issue by ricardodcfgh** [pingcap/tidb#45939]
## Enhancement
bulk copy在mysql中默认悲观事务执行可以正常回退，在TIDB文档中有写
《LOAD DATA 语句始终以乐观事务模式执行，不受 TiDB 事务模式设置的影响。》
在将来的那个版本可以实现bulk copy的回退功能

**Comment by lance6716** [comment]
Do you mean https://github.com/pingcap/tidb/issues/43679 ?

And please translate your issue into English
