### ISSUE TITLE
关于使用Bulk Copy导致事务失效

### ISSUE THREAD

**Issue by ricardodcfgh** [pingcap/tidb#45934]
【 TiDB 使用环境】测试
【 TiDB 版本】5.7.25-TiDB-v7.1.1
【复现路径】开启一个事务，先用insert插入A表数据，再使用Bulk Copy插入B表数据，在未commit的情况下，另外开启一个事务查询A表和B表
【遇到的问题：未提交情况下发现AB表已经写入了，使用ROLLBACK的事务无法回退，手动删除数据量太大，时间太长，需要实现Bulk Copy的回退，希望官方完善Bulk Copy的兼容度

**Comment by bb7133** [comment]
Hi @ricardodcfgh , could you please translate your issue to English?

**Comment by bb7133** [comment]
Only English is available for TiDB repository, thanks.
