### ISSUE TITLE
Scatter region should check success status 

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb#46001]
## Bug Report
For BR or using the `tidb_scatter_region` variable, we need to check the success status of the scatter operator. When we create a table, if the region is just splitted, the size might be the original region's size/n, which could not be less than 1. So PD will regard those regions as non-empty regions. Then they might be filtered by store limit.
But BR and client-go will think the scatter region succeeds since they are not in running status but cancel status.

https://github.com/tikv/tikv/blob/9dc7450ef22abde48e14e61fc16d4f22b137d450/components/raftstore/src/store/fsm/peer.rs#L4030-L4031

BR:
https://github.com/pingcap/tidb/blob/66033d576342aca687deb48757c1c18013d902a1/br/pkg/restore/split.go#L209

client-go:
https://github.com/tikv/client-go/blob/8a214402da13d5bdc1ffb1d2726bdbb47f9beb74/tikv/split_region.go#L287
https://github.com/tikv/client-go/blob/8a214402da13d5bdc1ffb1d2726bdbb47f9beb74/tikv/split_region.go#L325

The lightning has already been fixed through https://github.com/pingcap/tidb/pull/33625.

**Comment by mittalrishabh** [comment]
I opened a PR https://github.com/tikv/pd/pull/6953

**Comment by rleungx** [comment]
Also related to https://github.com/tikv/tikv/issues/15326
