### ISSUE TITLE
Incorrect variable to log size used in WriteToTiKV function

### ISSUE THREAD

**Issue by feran-morgan-pingcap** [pingcap/tidb#46084]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

tidb/br/pkg/lightning/backend/local/local.go is incorrectly writing to the logs.

### 1. Minimal reproduce step (Required)

Found in the code and observable in logs.
Found in the code here: https://github.com/pingcap/tidb/blob/release-6.6/br/pkg/lightning/backend/local/local.go#L1163
And here: https://github.com/pingcap/tidb/blob/release-6.6/br/pkg/lightning/backend/local/local.go#L1179

### 2. What did you expect to see? (Required)

Total size listed in the logs, but instead it's logging the size of each batch (after resetting to 0) when calling the WriteToTiKV function. 
It should be writing the "totalSize" variable, but instead writes the "size" variable.

### 3. What did you see instead (Required)

This causes the function to write a 0 instead of the total size in the logs since "size" is set to 0 repeatedly during the functions execution.

Found in the code here: https://github.com/pingcap/tidb/blob/release-6.6/br/pkg/lightning/backend/local/local.go#L1163
And here: https://github.com/pingcap/tidb/blob/release-6.6/br/pkg/lightning/backend/local/local.go#L1179

### 4. What is your TiDB version? (Required)

6.6.0

**Comment by lance6716** [comment]
thanks for reporting. We have fixed it in https://github.com/pingcap/tidb/pull/40692. You can find the line at line 320 in br/pkg/lightning/backend/local/region_job.go . 

That commit is included since v7.0.0

**Comment by gonnafaraway** [comment]
@lance6716  this issue can be closed.
