### ISSUE TITLE
Get `ERROR 1105 (HY000): context provider not set` error when run fast analyze with a partition table

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#46119]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
set @@tidb_enable_fast_analyze=true;
set @@tidb_analyze_version=1;
source a.txt;
analyze table test;
```

### 2. What did you expect to see? (Required)

analyze success

### 3. What did you see instead (Required)

```
mysql> analyze table yl_jms_spmi_operation_bill_sum_pt;
ERROR 1105 (HY000): context provider not set
```

### 4. What is your TiDB version? (Required)

[a.txt](https://github.com/pingcap/tidb/files/12343179/a.txt)

**Comment by Defined2014** [comment]
Version 6.1 also has problem with `ERROR 8024 (HY000): invalid transaction` error msg

**Comment by chrysan** [comment]
Fast analyze is an experimental feature and going to be removed later.

**Comment by Defined2014** [comment]
Fast analyze already removed in v7.5.0, so close this issue.

https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_fast_analyze
