### ISSUE TITLE
BR logStop not working

### ISSUE THREAD

**Issue by derhoerit** [pingcap/tidb#46121]
### 1. Minimal reproduce step

1. Deployed TiDB Via Kubernetes
2. Setup https://docs.pingcap.com/tidb-in-kubernetes/stable/backup-to-aws-s3-using-br#log-backup
3. Delete Backup without stopping backup Job first
4. Rerun job
5. Error Occured, try to edit backup by edit logStop: true
6. Nothing happens, try to delete backup and apply config again with logStop: true appended
7. Nothing happens. Still Error: It supports single stream log task currently: [BR:Stream:ErrStreamLogTaskExist]stream task already exists

### 2. What did you expect to see? 
Backup state stopped

### 3. What did you see instead
Error: It supports single stream log task currently: [BR:Stream:ErrStreamLogTaskExist]stream task already exists
I see in my S3 the backup is still running. But i can't debug and make it stop.

### 4. What is your TiDB version?

Release Version: v7.1.1
Edition: Community
Git Commit Hash: cf441574864be63938524e7dfcf7cc659edc3dd8
Git Branch: heads/refs/tags/v7.1.1
UTC Build Time: 2023-07-19 10:20:53
GoVersion: go1.20.6
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by Leavrth** [comment]
In the current version, the tidb operator cannot stop the log backup task by create a new `Backup CR` with configure `logStop: true`.
But you can stop the log backup task manually.

**Comment by derhoerit** [comment]
Hi @Leavrth , thanks for the feedback. Do you have any guide like docs or step how to stop the log backup task manually from TiDB cluster? Thanks

**Comment by BornChanger** [comment]
it's a tidb-operator issue.
