### ISSUE TITLE
config show new_collations_enabled_on_first_bootstrap result not correct after upgrade from v5.4.1 to v6.5.3

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#46136]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

TiUP deploy a new v5.4.1 version cluster. yaml file no need set new_collations_enabled_on_first_bootstrap.

mysql> show config where name like '%new_collations_enabled_on_first_bootstrap%';
+------+---------------+-------------------------------------------+-------+
| Type | Instance      | Name                                      | Value |
+------+---------------+-------------------------------------------+-------+
| tidb | 10.x.x.3:4923 | new_collations_enabled_on_first_bootstrap | false |
| tidb | 10.x.x.3:4913 | new_collations_enabled_on_first_bootstrap | false |
+------+---------------+-------------------------------------------+-------+

mysql> select * from mysql.tidb;
+-----------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| VARIABLE_NAME         | VARIABLE_VALUE                                                                                   | COMMENT                                                                                |
+-----------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| bootstrapped          | True                                                                                             | Bootstrap flag. Do not delete.                                                         |
| tidb_server_version   | 83                                                                                               | Bootstrap version. Do not delete.                                                      |
| system_tz             | Asia/Shanghai                                                                                    | TiDB Global System Timezone.                                                           |
| new_collation_enabled | False                                                                                            | If the new collations are enabled. Do not edit it.                                     |

upgrade v5.4.1 version to v6.5.3 version.

show config where name like '%new_collations_enabled_on_first_bootstrap%';
+------+---------------+-------------------------------------------+-------+
| Type | Instance      | Name                                      | Value |
+------+---------------+-------------------------------------------+-------+
| tidb | 10.x.x.3:4913 | new_collations_enabled_on_first_bootstrap | true  |
| tidb | 10.x.x.3:4923 | new_collations_enabled_on_first_bootstrap | true  |
+------+---------------+-------------------------------------------+-------+

 select * from mysql.tidb;
+-----------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| VARIABLE_NAME         | VARIABLE_VALUE                                                                                   | COMMENT                                                                                |
+-----------------------+--------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| bootstrapped          | True                                                                                             | Bootstrap flag. Do not delete.                                                         |
| tidb_server_version   | 91                                                                                               | Bootstrap version. Do not delete.                                                      |
| system_tz             | Asia/Shanghai                                                                                    | TiDB Global System Timezone.                                                           |
| new_collation_enabled | False                                                                                            | If the new collations are enabled. Do not edit it.                                     |

### 2. What did you expect to see? (Required)

show config where name like '%new_collations_enabled_on_first_bootstrap%';

The result should be false. 

The show config result should show the true value of the new_collations_enabled_on_first_bootstrap parameter.(not default value)

### 3. What did you see instead (Required)

show config where name like '%new_collations_enabled_on_first_bootstrap%';

The result is true

**Comment by Defined2014** [comment]
IMO, it's not a bug. The `show config` only show the current configuration of various components of TiDB which is not same as running system variables.

https://docs.pingcap.com/tidb/stable/sql-statement-show-config

For this issue, we could think `new_collations_enabled_on_first_bootstrap` equals to true in config file, but it does not take effect.

**Comment by jackysp** [comment]
However, it seems that `new_collations_enabled_on_first_bootstrap = true` is not in the configuration file(Please double check it @yilongrong.). The value shown by `show config` is the default value of the code, rather than the value in the configuration file.

**Comment by yilongrong** [comment]
new_collations_enabled_on_first_bootstrap is not configured in the yaml file.

**Comment by Defined2014** [comment]
So there are two interpretations of this question
1. Is it correct for `show config` return `new_collations_enabled_on_first_bootstrap = true`?
2. If the previous default value is false, do we need to change it to display true (the new default value) after the upgrade?

IMO, for the first one, it's absolutely right.

For the second one, it's same as other config variables. But `new_collations_enabled_on_first_bootstrap` is a bit special, it will not affected for an old cluster.

**Comment by Damon-Guo** [comment]
I agree to show the actual value of the parameter new_collations_enabled_on_first_bootstrap configuration，but this is a issue that needs to be solved。how to confirm the truly config of parameter new_collations_enabled_on_first_bootstrap simply in this situation？and there are some tools  may use this parameter like br 、lightning 。
I think tidb should not be allowed to set the parameter new_collations_enabled_on_first_bootstrap  to be inconsistent with the effective value。

**Comment by Defined2014** [comment]
> I agree to show the actual value of the parameter new_collations_enabled_on_first_bootstrap configuration，but this is a issue that needs to be solved。how to confirm the truly config of parameter new_collations_enabled_on_first_bootstrap simply in this situation？and there are some tools may use this parameter like br 、lightning 。 I think tidb should not be allowed to set the parameter new_collations_enabled_on_first_bootstrap to be inconsistent with the effective value。

@bb7133 Do you think we should do `new_collations_enabled_on_first_bootstrap` differently than other configurations?

**Comment by bb7133** [comment]
There are 2 things here:

1- The default value of `new_collations_enabled_on_first_bootstrap` is changed from `false` to `true` since v6.1, that's why `SHOW CONFIG` gives different result after the upgrades when you do not have explicit `new_collations_enabled_on_first_bootstrap` in the yaml file:

  * [default value in v5.4](https://docs.pingcap.com/tidb/v5.4/tidb-configuration-file#new_collations_enabled_on_first_bootstrap)
  * [default value in v6.1](https://docs.pingcap.com/tidb/v6.1/tidb-configuration-file#new_collations_enabled_on_first_bootstrap)


2- As indicated by the name, the value of `new_collations_enabled_on_first_bootstrap` applies on the first bootstrap of a TiDB cluster only. So its value might be different with `new_collation_enabled` in `mysql.tidb` table: if the customer want to confirm 'if the new collation framework is enabled', `new_collation_enabled` is the only ground truth to get.

**Comment by jackysp** [comment]
Another question, why don't we hide `new_collations_enabled_on_first_bootstrap` in the show config? Because it looks more like a disposable item.

**Comment by jackysp** [comment]
Furthermore, I'm also quite curious about something. The "show config" command displays some configurations that haven't actually taken effect. Is this reasonable?

**Comment by jackysp** [comment]
> There are 2 things here:
> 
> 1- The default value of `new_collations_enabled_on_first_bootstrap` is changed from `false` to `true` since v6.0(see the [release note of v6.1 DMR](https://docs.pingcap.com/tidb/stable/release-6.0.0-dmr#deployment-and-maintenance)), that's why `SHOW CONFIG` gives different result after the upgrades when you do not have explicit `new_collations_enabled_on_first_bootstrap` in the yaml file:
> 
> * [default value in v5.4](https://docs.pingcap.com/tidb/v5.4/tidb-configuration-file#new_collations_enabled_on_first_bootstrap)
> * [default value in v6.1](https://docs.pingcap.com/tidb/v6.1/tidb-configuration-file#new_collations_enabled_on_first_bootstrap)
> 
> 2- As indicated by the name, the value of `new_collations_enabled_on_first_bootstrap` applies on the first bootstrap of a TiDB cluster only. So its value might be different with `new_collation_enabled` in `mysql.tidb` table(and this is exactly _why they have different names_): if the customer want to confirm 'if the new collation framework is enabled', `new_collation_enabled` is the only ground truth to get.

You may need to add the second explanation to the document. 😄 @bb7133

**Comment by bb7133** [comment]
> You may need to add the second explanation to the document. 😄 @bb7133

You're right, we need more explanations. For now, there's no detail for `mysql.tidb` table.
