### ISSUE TITLE
TiDB should quit if have got cluster ID mismatch error.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#4614]
When TiDB connected to a wrong cluster, it will keep getting cluster ID mismatch error, and this error is not recoverable, we should quit the server, or it will slow down the DDL operation.

**Comment by shenli** [comment]
Is there any user scenario we meet this situation?

**Comment by coocood** [comment]
@shenli 
Only found in our test environment.

**Comment by shenli** [comment]
Got it.

**Comment by haoyougen** [comment]
I have the same problem.  Cause I changed the PD server from 2 old servers to 3 new servers. 
Then tidb can't startup and tikv can't connect to the new cluster. 
Any good suggestion how to resolve it ?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to re-open it if this problem is still occurring. Thanks!
