### ISSUE TITLE
AccessFollower will try to access unreachable leader peers

### ISSUE THREAD

**Issue by zyguan** [pingcap/tidb#46198]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run a stale read workload and inject network partition between two zones.

### 2. What did you expect to see? (Required)

KV client should never try to access unreachable peers.

### 3. What did you see instead (Required)

`accessFollower` may choose an unreachable leader peer as the target after fallback from data-not-ready error, which leads to unexpected long-tail queries.

![2023-08-17_173808](https://github.com/pingcap/tidb/assets/6850317/c5d8a20c-33f4-44ad-9a54-597056a97ad7)

### 4. What is your TiDB version? (Required)

release-6.5

**Comment by cfzjywxk** [comment]
@zyguan 
Should it be closed as it's fixed?

**Comment by zyguan** [comment]
> @zyguan Should it be closed as it's fixed?

Yes, fixed by https://github.com/tikv/client-go/pull/971
