### ISSUE TITLE
Resource control can't be limited under the ru set

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#46200]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
| rg3     | 10000      | MEDIUM   | NO        | NULL        | NULL       |
sysbench read write
```
![image](https://github.com/pingcap/tidb/assets/7677963/09b3e61b-dc24-4942-b245-25aaf6615ac7)

### 4. What is your TiDB version? (Required)

Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: cf8a74bb239d070c2857419ceeebd0f6cb05f37b
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-16 11:45:27
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by CabinfeverB** [comment]
introduce by https://github.com/pingcap/tidb/pull/44460. It causes the unique id of the client to be 0, so resource manager server can not handle RU request correctly
