### ISSUE TITLE
refine lightning retry on region scatter

### ISSUE THREAD

**Issue by mittalrishabh** [pingcap/tidb#46203]
## Bug Report

Lightning split a region into few regions and call scatter regions on all the regions once before it back off. In my view it should back off and retry scattering the same region if it is failed. This logic is similar to tikv client scatter logic. 

https://github.com/tikv/client-go/blob/a0ac170698524cbf20a869cb3471e969608d599a/tikv/split_region.go#L198

Advantage of this approach is
1. We don't send scatter unnecessarily to PD if it is failing. 
2. Each scatter operation creation increase the scatter count on a store even though it is cancelled later. It might cause some skewness.
 
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Set store limit to 16
4. Run lightning in physical import mode for large data set (100G)
5. You will see lot of scatter operators cancelled. And you might see skewed regions.

### 2. What did you expect to see? (Required)
I expect to see balanced regions and less number of operators cancelled

### 3. What did you see instead (Required)

I found regions skewed and scatter operations cancelled

### 4. What is your TiDB version? (Required)
6.5.1

**Comment by lance6716** [comment]
> retry scattering the same region if it is failed

lightning should already retry scattering. in `waitForScatterRegions` -> `checkRegionScatteredOrReScatter`, lightning will retry scattering when status is canceled

https://github.com/pingcap/tidb/blob/4084b077d615f9dc0a41cf2e30bc6e1a02332df2/br/pkg/lightning/backend/local/localhelper.go#L504-L513

> It might cause some skewness.

we should have fixed it in master and v7.1.1. This is the issue for skewness https://github.com/pingcap/tidb/issues/43510

**Comment by mittalrishabh** [comment]
I have created this PR. https://github.com/pingcap/tidb/pull/46245

It is not a final PR. But it will give you the clear idea what i am trying to do

**Comment by D3Hunter** [comment]
region skew part is duplicate with https://github.com/pingcap/tidb/issues/43510

**Comment by D3Hunter** [comment]
change to `enhancement` as region skew part has already fixed in https://github.com/pingcap/tidb/issues/43510

this issue is only for refine retry logic of region scatter

**Comment by D3Hunter** [comment]
> I have created this PR. #46245
> 
> It is not a final PR. But it will give you the clear idea what i am trying to do

#46245 will cause long tail issue when parallel importing using multiple instances, some instance might be very slow at split&scatter
for regions will less or more peers, i.e. not replicated regions, PD must wait peers = defined replicas before it start scatter, and PD's internal schedule of fixing peers is quite slow, but if lightning call scatterRegion, PD will try to fix peers for the regions with higher priority, see pr https://github.com/tikv/pd/pull/2757 (PD >=6.5.0 will have it). this issue https://github.com/tikv/pd/issues/2733 descriped that if a region is not replicated before split, all splitted new regions will also be not replicated. when import with multiple instance, there's more chance that some instance might split a region which is in scatter, and this causes more not-replicated regions.

#46245 will make calls to ScatterRegion until it returns with no error before it try scatter next region, if there are many regions to scatter, it will make split&scatter very slow, and long tail.

it affects LTS 7.5. For 8.1, we have unified split&scatter logic of br&lightning using batch scatter, so it should not have the issue in this ticket, and has no long tail issue too.

so i will close all related cherrypicks of  #46245. and let's fix long tail issue in LTS 7.5 later.

**Comment by mittalrishabh** [comment]
I understand the issue you described here. It is not really a problem for us because of two reasons : 1. Data is already sorted and 2. We presplit the table before we start import. 

>>so i will close all related cherrypicks of https://github.com/pingcap/tidb/pull/46245. and let's fix long tail issue in LTS 7.5 later.

I don't understand what you mean be close here. I see that this PR is already there in 7.5

**Comment by D3Hunter** [comment]
> I understand the issue you described here. It is not really a problem for us because of two reasons : 1. Data is already sorted and 2. We presplit the table before we start import.

@guoshouyan found the long tail issue when parallel importing with 18 instances.

> 
> > > so i will close all related cherrypicks of #46245. and let's fix long tail issue in LTS 7.5 later.
> 
> I don't understand what you mean be close here. I see that this PR is already there in 7.5

the cherry-picks are closed, not the pr

**Comment by okJiang** [comment]
> it affects LTS 7.5. For 8.1, we have unified split&scatter logic of br&lightning using batch scatter, so it should not have the issue in this ticket, and has no long tail issue too.

closed by https://github.com/pingcap/tidb/pull/52300
