### ISSUE TITLE
A question about the TiDB performance after inserting some data

### ISSUE THREAD

**Issue by yeyuqiang** [pingcap/tidb#4627]
What did you do?
If possible, provide a recipe for reproducing the error.
Set up a TiDB cluster with SSD as recommended in doc
[tidb_servers]
172.16.1.53
172.16.1.55
[tikv_servers]
172.16.1.59
172.16.1.61
172.16.1.63
[pd_servers]
172.16.1.53
172.16.1.55
172.16.1.57

Run Tidb-sysbench to insert 32 tables, each table with 100,000,000 row data.

What did you see instead?
Tidb cost about 32 hours to  prepare these data.
Is this reasonable? Is there any way to speed up?

What version of TiDB are you using (`tidb-server -V`)?
pre-ga

**Comment by ngaut** [comment]
Could you post the command line arguments of sysbench ?

**Comment by yeyuqiang** [comment]
Thanks for your reply

I used parallel-prepare.sh from latest tidb-bench/sysbench
I set the arguments in conf.sh as below
`
host=127.0.0.1
port=4000
user=root
password=''
tcount=32
tsize=100000000
threads=32
dbname=test

# report interval
interval=10

# max time in seconds
maxtime=600000

# just large enough to fit maxtime
requests=2000000000

driver=mysql
`

The sysbench command , arguments need rbe replaced from conf.sh
`
sysbench --test=./lua-tests/db/parallel_prepare.lua --db-driver=${driver} --mysql-host=${host} --mysql-port=${port} \
 --mysql-user=${user} --mysql-password=${password} --oltp-tables-count=${tcount} --mysql-db=${dbname} \
 --oltp-table-size=${tsize} --num-threads=${threads}  --rand-init=on run
`

The result as below
SQL statistics:			
    queries performed:			
        read:                            0			
        write:                           1212843			
        other:                           0			
        total:                           1212843			
    transactions:                        32     (0.00 per sec.)			
    queries:                             1212843 (11.11 per sec.)			
    ignored errors:                      0      (0.00 per sec.)			
    reconnects:                          0      (0.00 per sec.)			
			
General statistics:			
    total time:                          109148.6092s			
    total number of events:              32			
			
Latency (ms):			
         min:                            70253851.17			
         avg:                            104248935.83			
         max:                            109148608.48			
         95th percentile:                 100000.00			
         sum:                            3335965946.45			
			
Threads fairness:			
    events (avg/stddev):           1.0000/0.00			
    execution time (avg/stddev):   104248.9358/7870.33	

I have tried to tune the parameter in tikv.toml, such as grpc thread pool , scheduler work pool, write buffer size and etc. But I did not observe obvious improvements.

Anything went wrong here?

**Comment by nullnotnil** [comment]
Sysbench benchmarks are now published [in the documentation](https://docs.pingcap.com/tidb/dev/benchmark-sysbench-v4-vs-v3).

Your numbers do look very low, but a lot has changed since 2017. I am going to go ahead and close this issue as stale, but if you are still experimenting and facing issues, please feel free to open a new issue. Thanks!
