### ISSUE TITLE
etcd client leak when a table uses AUTO_ID_CACHE=1 and auto_increment 

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#46324]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
nowhere close this etcd client
https://github.com/pingcap/tidb/blob/1769f3a1ac3674b9267dca55bf1fc261ac804325/meta/autoid/autoid.go#L588

### 4. What is your TiDB version? (Required)
this code is introduced in tidb version >= 6.4.0

**Comment by tiancaiamao** [comment]
Ref https://github.com/pingcap/tidb/issues/48869
