### ISSUE TITLE
alter table tab1 add (col3 type1) is not supported in tidb

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#4639]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
tidb doesn't support () in add column clause:

`ALTER TABLE resource_index ADD (component_uuid VARCHAR (50) NULL);`

2. What did you expect to see?
```
mysql> ALTER TABLE resource_index ADD (component_uuid VARCHAR (50) NULL);
Query OK, 0 rows affected (0.06 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

3. What did you see instead?
```
MySQL [sonar]> ALTER TABLE resource_index ADD (component_uuid VARCHAR (50) NULL);
ERROR 1105 (HY000): line 0 column 32 near "component_uuid VARCHAR (50) NULL)" (total length 65)

MySQL [sonar]> ALTER TABLE resource_index ADD component_uuid VARCHAR (50) NULL;
Query OK, 0 rows affected (0.46 sec)

```

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: 0.9.0
Git Commit Hash: fa87ec45a9acf93fc6e740ecb617b4a100d0d867
Git Branch: HEAD
UTC Build Time: 2017-09-24 01:38:26 |

**Comment by zimulala** [comment]
Relate to #3575
