### ISSUE TITLE
alter database syntax support.

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#4641]
TiDB:

```
mysql> alter database test1 character set utf8 COLLATE uft8_general_ci;
ERROR 1105 (HY000): line 0 column 14 near " test1 character set utf8 COLLATE uft8_general_ci" (total length 63)
mysql> alter database test1 character set utf8 COLLATE uft8_general_ci;
ERROR 1105 (HY000): line 0 column 14 near " test1 character set utf8 COLLATE uft8_general_ci" (total length 63)
```

see https://dev.mysql.com/doc/refman/5.7/en/alter-database.html

**Comment by morgo** [comment]
It would be great to see this added :-)

There is a use case to `ALTER DATABASE` and change the character set to `utf8mb4`, as some applications know to use this over MySQL's `utf8`.

It is, of course, possible to set each individual table to `utf8mb4`, but this is more work.

**Comment by gregwebs** [comment]
I noticed this today. This error message is very poor, pointing to a location that is already past the error. Much better would be "ALTER DATABASE not supported".

**Comment by winkyao** [comment]
alter database is supported in https://github.com/pingcap/tidb/pull/10393, so I close this issue
