### ISSUE TITLE
flaky test TestChannelMap

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#46420]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
=== RUN   TestChannelMap

    misc_test.go:199: channel not closed: blocked

--- FAIL: TestChannelMap (0.00s)

```

**Comment by gonnafaraway** [comment]
![image](https://github.com/pingcap/tidb/assets/35832930/2ca02e85-caf4-43a5-a8b2-7fef5a21fca9)
Hi!
Tested locally, got no errors, how can i reproduce this problem?
@hawkingrei

**Comment by jiyfhust** [comment]
There seems to be  goroutine competition here: 

https://github.com/pingcap/tidb/blob/a631d2ff2e8f29ddadfbdee106805d1c8b3e99cb/util/util.go#L94C13-L94C13
https://github.com/pingcap/tidb/blob/a631d2ff2e8f29ddadfbdee106805d1c8b3e99cb/util/misc_test.go#L196
