### ISSUE TITLE
add index task rollback to txn-merge when inject some fault

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#46468]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、add index task rollback to txn-merge when kill ddl owner
        - name: "ha_tidb_ddl_owner_kill"
          warmUpTime: 5m
          faultType: kill
          selector: "tidb(ddl-owner)"
          period: "@every 5m"
          faultDuration: 1m
          faultTotalRunTime: 30m
2、add index task rollback to txn-merge when kill pd leader
        - name: "ha_pdleader_kill"
          warmUpTime: 5m
          faultType: kill
          selector: "pd(leader)"
          period: "@every 5m"
          faultDuration: 1m
          faultTotalRunTime: 30m
3、add index task rollback to txn-merge when kill one of tikv
        - name: "ha_tikv_random_kill"
          warmUpTime: 5m
          faultType: kill
          selector: "tikv(random)"
          period: "@every 5m"
          faultDuration: 1m
          faultTotalRunTime: 30m
4、add index task rollback to txn-merge when one of tikv network partition
        - name: "ha_tikv(random)_to_all_network_partition"
          warmUpTime: 5m
          faultType: network_partition
          selector: "tikv(random)_to_all"
          period: "@every 5m"
          faultDuration: 5m
          faultTotalRunTime: 30m
5、add index task rollback to txn-merge when network partition between pd leader and ddl owner
        - name: "ha_tidb(ddl-owner)_to_pdleader_network_partition"
          warmUpTime: 5m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_pdleader"
          period: "@every 5m"
          faultDuration: 5m
          faultTotalRunTime: 30m
6、add index task rollback to txn-merge when network partition between one of tikv and ddl owner
        - name: "ha_tidb(ddl-owner)_to_tikv(random)_network_partition"
          warmUpTime: 5m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_tikv(random)"
          period: "@every 5m"
          faultDuration: 5m
          faultTotalRunTime: 30m
7、add index task rollback to txn-merge when network_latency of pdleader
        - name: "ha_pdleader_to_all_network_latency(latency:50ms)"
          warmUpTime: 5m
          faultType: network_latency(latency:50ms)
          selector: "pdleader_to_all"
          period: "@every 5m"
          faultDuration: 5m
          faultTotalRunTime: 30m
8、add index task rollback to txn-merge when network_latency of one of tikv
        - name: "ha_tikv(random)_to_all_network_latency(latency:50ms)"
          warmUpTime: 5m
          faultType: network_latency(latency:50ms)
          selector: "tikv(random)_to_all"
          period: "@every 5m"
          faultDuration: 5m
          faultTotalRunTime: 30m
9、add index task rollback to txn-merge when network_latency of one of ddl owner
        - name: "ha_tidb(ddl-owner)_to_all_network_latency(latency:50ms)"
          warmUpTime: 5m
          faultType: network_latency(latency:50ms)
          selector: "tidb(ddl-owner)_to_all"
          period: "@every 5m"
          faultDuration: 5m
          faultTotalRunTime: 30m

### 2. What did you expect to see? (Required)
should not rollback to txn-merge when inject some fault

### 3. What did you see instead (Required)
add index task rollback to txn-merge when inject some fault

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: bfacaf888741f1c0e987c199b5a971c1d4be6797
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-08-26 11:43:36
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by tangenta** [comment]
Duplicated with the second problem mentioned in #47758.
