### ISSUE TITLE
Automatic collection of statistics cannot be killed at once

### ISSUE THREAD

**Issue by yilongrong** [pingcap/tidb#46465]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The analyze job is a partitioned table with many partitions, and after killing a job, it will automatically execute the next one

yl_test_relation summary_test_relation P_LT_2023-06-04 auto analyze index idx_create_time 0 pending 10.xx.xx.71:4000 1282626493289070595
yl_test_relation summary_test_relation P_LT_2023-06-04 auto analyze index idx_collect_no 0 pending 10.xx.xx.71:4000 1282626493289070595
yl_test_relation summary_test_relation P_LT_2023-06-04 auto analyze index idx_test_date 0 pending 10.xx.xx.71:4000 1282626493289070595
yl_test_relation summary_test_relation P_LT_2023-06-04 auto analyze index idx_test_no 0 pending 10.xx.xx.71:4000 1282626493289070595
yl_test_relation summary_test_relation P_LT_2023-06-04 auto analyze index PRIMARY 0 pending 10.xx.xx.71:4000 1282626493289070595
yl_test_relation summary_test_relation P_LT_2023-06-04 auto analyze columns 0 2023-08-18 14:35:23 running 10.xx.xx.71:4000 1282626493289070595

### 2. What did you expect to see? (Required)
Automatic collection of statistics can be killed at once
### 3. What did you see instead (Required)
Automatic collection of statistics cannot be killed at once
### 4. What is your TiDB version? (Required)
v6.5.3

**Comment by hawkingrei** [comment]
the same as https://github.com/pingcap/tidb/issues/45706.

It has been fixed in the v6.5.4.
