### ISSUE TITLE
 datetime zero in date when select or update with record with bad datetime field

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#4653]
This can be inserted

```sql
TiDB-Server [test]> create table t1  (id int, t datetime not null, primary key(id));
Query OK, 0 rows affected (1.01 sec)

TiDB-Server [test]> insert into t1 values(3, '2017-00-00 00:00:00');
Query OK, 1 row affected (0.00 sec)
```

But query will fail:

```sql
TiDB-Server [test]> select * from t1;
ERROR 1105 (HY000): datetime zero in date
```

And the erroneous record can not be updated either

```sql
TiDB-Server [test]> update t1 set t = '2017-01-01 00:00:00' where id=3;
ERROR 1105 (HY000): datetime zero in date
```

IMHO, tidb should validate before insertion or if record with bad datetime field CAN be inserted tidb should not report error when being selected or updated later.

**Comment by shenli** [comment]
@Darren Thanks for your feedback!
May I have your tidb version. You can get it by select tidb_version();

**Comment by Darren** [comment]
@shenli 

sorry,  I was about to add the version info before your such quick response.

Release Version: 0.9.0
Git Commit Hash: d2d14d8c48647436b3b71af16aacb63942976797
Git Commit Branch: master
UTC Build Time:  2017-09-22 04:44:57

**Comment by XuHuaiyu** [comment]
@Darren
Thank you, I'll fix this soon.

**Comment by XuHuaiyu** [comment]
This is a compatibility problem caused by not checking sql_mode
when converting a datum to Time type.

**Comment by Darren** [comment]
@XuHuaiyu 

Could you tell set  sql_mode to  which value can workaround this problem?

**Comment by XuHuaiyu** [comment]
Sorry for late reply, @Darren
This is not supported in the code level, maybe no workround can be used.
I'll fix this these two days.
