### ISSUE TITLE
not able to create table after upgrade TiDB cluster from 7.1.0 to master

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#46551]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Deploy 7.1.0 TiDB cluster with CDC component, start CDC changefeed
2. Upgrade TiDB cluster from 7.1.0 to master
3. execute DDL "CREATE TABLE IF NOT EXISTS finishmark (foo BIGINT PRIMARY KEY)"

### 2. What did you expect to see? (Required)
create table should be successful.

### 3. What did you see instead (Required)
Not able to create table for 4+ hours.

![image](https://github.com/pingcap/tidb/assets/7403864/e7b36e44-763d-48c5-8e1c-e41ebed55f16)

### 4. What is your TiDB version? (Required)
Before upgrade: 7.1.0, 635a4362235e8a3c0043542e629532e3c7bb2756
After upgrade: master, 61f882596bed2c7f41c4fab7cdbb5ac7defcb1bf

**Comment by jebter** [comment]
Requires tiup/operator adaptation

**Comment by zimulala** [comment]
Having similar problems, I adjusted the behavior through discussion with PM. Specific issue:https://github.com/pingcap/tidb/issues/46639 can reference
