### ISSUE TITLE
Unexpected Results by MERGE_JOIN

### ISSUE THREAD

**Issue by bajinsheng** [pingcap/tidb#46564]
### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1(c0 BLOB(16) , c1 BLOB(16) , c2 BLOB(16));
INSERT INTO t1 VALUES ('1', '2', 'a'), ('3', '4', 'b');
CREATE VIEW v0(c0) AS SELECT t1.c2 FROM t1;
SET @@sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
ANALYZE TABLE t1;

SELECT t1.c2, t1.c1 FROM t1, v0 WHERE t1.c0 GROUP BY POW(2, t1.c2); -- {b|4}
SELECT /*+ MERGE_JOIN(v0)*/t1.c2, t1.c1 FROM t1, v0 WHERE t1.c0 GROUP BY POW(2, t1.c2); -- {a|2}
```

### 3. What did you see instead (Required)
Two queries return different results.

### 4. What is your TiDB version? (Required)

| Release Version: v7.4.0-alpha-239-g4f2f5e1061
Edition: Community
Git Commit Hash: 4f2f5e1061ddc55a2dd349e1df67847c0edd1f23
Git Branch: master
UTC Build Time: 2023-08-30 12:06:00
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore |

**Comment by qw4990** [comment]
Same with https://github.com/pingcap/tidb/issues/46572: this query breaks the `only_full_group_by` attribute and multiple rows are in the same agg-group, so any one of those rows can be returned as the final result:
![image](https://github.com/pingcap/tidb/assets/7499936/80de4abe-dffe-4fd3-be3d-d1f7ef71f6db)

**Comment by mjonss** [comment]
Closing as duplicate of https://github.com/pingcap/tidb/issues/53175 (and since this is marked as wontfix, the last thing to do is to correctly handle the SQL_MODE in VIEW).
