### ISSUE TITLE
high cpu usage on PlanCacheParamList when using prepared statement

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#46579]
## Enhancement

After enable the prepared statement at client side, at the tidb cpu profile, we see 26% cpu on  variable.(*PlanCacheParamList).String for below workload, need cpu optimization on the function PlanCacheParamList

Workload: 50% write and 50% read
avg row size: 10KB
schema
```
create table test (`k` VARBINARY(64) NOT NULL, `v` BLOB, PRIMARY KEY (`k`) CLUSTERED);

```

![f03f10b2-374e-414a-b242-1976d52a1476](https://github.com/pingcap/tidb/assets/2316425/ee1138cd-c272-46e5-8a28-ac2a4816a139)

**Comment by qw4990** [comment]
I'll fix it soon.
