### ISSUE TITLE
Control the max number of row and bytes lighting sends to tidb

### ISSUE THREAD

**Issue by guoshouyan** [pingcap/tidb#46607]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In lightning physical backend, we can set the store-write-bwlimit to control how much data lightning send to tikv.
Can we have similar feature in logical mode?
We already have minDeliverBytes [here](https://github.com/pingcap/tidb/blob/b524a2316f08dbaade3b8cd3c7189f90895ea95e/br/pkg/lightning/importer/import.go#L2204) but it's not configurable. 
Can we make it configurable and also have another config like minDeliverRows to control the rows it sends?

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
Hi, not sure if I understand it correctly. In logical backend lightning will try to send data every 1MB. (`be.MaxChunkSize()` always return 1MB)

https://github.com/pingcap/tidb/blob/a4271136ecfdc8352f9ee30ddd6b707b04484236/br/pkg/lightning/backend/tidb/tidb.go#L614-L617

with the concurrency of `lightning.region-concurrency` from the configuration file. I think you want to make 1MB configurable?

And can you explain why the default value is not good enough?

**Comment by D3Hunter** [comment]
> Hi, not sure if I understand it correctly. In logical backend lightning will try to send data every 1MB. (`be.MaxChunkSize()` always return 1MB)
> 
> https://github.com/pingcap/tidb/blob/a4271136ecfdc8352f9ee30ddd6b707b04484236/br/pkg/lightning/backend/tidb/tidb.go#L614-L617
> 
> with the concurrency of `lightning.region-concurrency` from the configuration file. I think you want to make 1MB configurable?
> 
> And can you explain why the default value is not good enough?

this 1M is useless, as deliverLoop send in 96K batch, see https://github.com/pingcap/tidb/pull/46997#issuecomment-1880744664
