### ISSUE TITLE
need get float8 type suopport

### ISSUE THREAD

**Issue by RenlySir** [pingcap/tidb#46648]
## Feature Request

**Is your feature request related to a problem? Please describe:**
I am testing to replace mysql in the devlake background with tidb, and an error occurred during ALTER TABLE `_tool_gitlab_jobs` ADD `duration` float8

**Describe the feature you'd like:**
i need ti support float8/float4

**Describe alternatives you've considered:**
change devlake source code,but it's not good choice

**Teachability, Documentation, Adoption, Migration Strategy:**
need float8/float4 in tidb v7.4.0

**Comment by dveeden** [comment]
See also https://dev.mysql.com/doc/refman/8.1/en/other-vendor-data-types.html
