### ISSUE TITLE
ddl: attach the right resource group name in kv request for ddl/import tasks

### ISSUE THREAD

**Issue by glorv** [pingcap/tidb#46656]
## Development Task

The resource control feature implements quota limiter and scheduling logic in the client-go and tikv side, it uses the resource group name in the kv request to identify the task attached resource group. 

For most foreground SQLs, we set the resource-group-name parameter from the sessionctx but for DDL/Import like task, it uses a unified worker pool so the sessionctx's resource group is not the same as the user's session. We should attach the correct resource-group-name to let resource control feature work correctly.

**Comment by okJiang** [comment]
Can you tell me where `set the resource-group-name parameter from the sessionctx`? I will have a look. @glorv
