### ISSUE TITLE
lightning parallel import failed for tikv store size is imbalance

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#46654]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. 13 nodes parallel import to tc
2. every node import 3.4t data
3. tc open partition-raft-kv

### 2. What did you expect to see? (Required)
some nodes failed  because of low storage and tikv storage imbalance
[2023/09/04 23:40:27.451 +00:00] [ERROR] [main.go:103] ["tidb lightning encountered error stack info"] [error="[Lightning:Restore:ErrRestoreTable]restore table `db`.`table` failed: the remaining storage capacity of TiKV([tc-tikv-9.tc](http://tc-tikv-9.tc/)-tikv-peer.partition-raft-lfh99.svc:20160) is less than 10%; please increase the storage capacity of TiKV and try again"]
![image](https://github.com/pingcap/tidb/assets/50363732/308939d3-d68b-4bee-9904-537e785b1bef)
![image](https://github.com/pingcap/tidb/assets/50363732/6b251c19-7ebe-47cd-a12f-94194a5f51ce)

### 4. What is your TiDB version? (Required)
master

**Comment by lilinghai** [comment]
We have reduced the concurrency of lighting data import and divided it into three times imports. However, during the data import phase, the situation of unbalance store size still occurs.
![image](https://github.com/pingcap/tidb/assets/7677963/3657c61f-a8bd-49a1-b444-6fc23d726207)

**Comment by AkiraXie** [comment]
currently,the issue isn't seen in regular or cluster test
