### ISSUE TITLE
Calling stats_cache.Get too frequently

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#46715]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

<img width="1080" alt="image" src="https://github.com/pingcap/tidb/assets/3427324/9bbd412d-35c1-4aaf-8591-e1415d0d2f80">

**Comment by Rustin170506** [comment]
I believe the priority queue has solved the problem by reducing the need to rescan the entire cache.
