### ISSUE TITLE
add index task failed with “Error 1105 (HY000): context canceled”

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#46777]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、tidb_enable_dist_task='on'
2、run sysbench
sysbench --db-driver=mysql --time=0 --mysql-db=sysbench_64_7000w --mysql-host=tc-tidb.endless-ha-test-add-index-tps-2340022-1-766 --mysql-port=4000 --threads=64 --tables=64 --table-size=70000000 --mysql-ignore-errors=\"all\" --mysql-user=root --report-interval=10 oltp_read_write run
3、 add index
4、inject some error
![image](https://github.com/pingcap/tidb/assets/84712107/b9920426-c9ad-45e4-9d29-136f68d7cb47)

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index task failed with “Error 1105 (HY000): context canceled”

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 09a83b8a46cc53db68d4a79ff4b51e95cfa6e031
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-09-06 11:44:39
GoVersion: go1.21.0
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2023-09-07T09:15:52.804+0800

**Comment by ywqzzy** [comment]
close as #47313 fix it
