### ISSUE TITLE
tidb connection running loop panic error

### ISSUE THREAD

**Issue by imhun** [pingcap/tidb#46791]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
A random error occurs when the application executes specific services，for details about the sql, see logs

6.5 is ok, 7.1 to 7.3 have problems

### 2. What did you expect to see? (Required)
no error

### 3. What did you see instead (Required)
error occur

### 4. What is your TiDB version? (Required)
Release Version: v7.3.0
Edition: Community
Git Commit Hash: 40b72e7a9a4fc9670d4c5d974dd503a3c6097471
Git Branch: heads/refs/tags/v7.3.0
UTC Build Time: 2023-08-08 09:37:02
GoVersion: go1.20.7
Race Enabled: false
Check Table Before Drop: false
Store: tikv

2023-09-08T16:30:58.509517428+08:00 [2023/09/08 16:30:58.509 +08:00] [ERROR] [conn.go:962] ["connection running loop panic"] [conn=2791351548] [lastSQL="SELECT id, folder_id, form_code, form_name, release_status, sort, tenant_id, version_id, created_date, created_by, last_updated_date, last_updated_by, version_number FROM bg_auto_form WHERE (id = ?) AND ((bg_auto_form.created_by = 1503947622444519426 OR EXISTS (SELECT 1 FROM sys_perm_document_rule perm, sys_data_rule_table permt WHERE perm.document_type_id = permt.document_type_id AND ((perm.table_type = 1000 AND permt.c_table_name = 'bg_auto_form' AND perm.permission != 0) OR (perm.table_type = permt.table_type AND perm.document_id = bg_auto_form.id AND perm.cc_table_name = 'bg_auto_form' AND perm.permission != 0)) AND (perm.user_id = 1503947622444519426 OR perm.user_group_id IN (1632586065893220353, 1574937513391800322, 1590653737747836930)) AND perm.tenant_id = 1476472055858286593))) AND bg_auto_form.tenant_id = 1476472055858286593 [arguments: 1699702136627441666]"] 
[err="runtime error: invalid memory address or nil pointer dereference"]
[stack="github.com/pingcap/tidb/server.(*clientConn).Run.func1\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:965\nruntime.gopanic\n\t
/usr/local/go/src/runtime/panic.go:884\nruntime.panicmem\n\t
/usr/local/go/src/runtime/panic.go:260\nruntime.sigpanic\n\t
/usr/local/go/src/runtime/signal_unix.go:841\ngithub.com/pingcap/tidb/planner/core.getJoinHints\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/hints.go:111\n
github.com/pingcap/tidb/planner/core.genHintsFromSingle\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/hints.go:264\n
github.com/pingcap/tidb/planner/core.GenHintsFromFlatPlan\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/planner/core/hints.go:44\ngithub.com/pingcap/tidb/executor.getEncodedPlan\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1778\ngithub.com/pingcap/tidb/executor.(*ExecStmt).SummaryStmt.func1\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1835\ngithub.com/pingcap/tidb/util/stmtsummary.newStmtSummaryByDigestElement\n\t
/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:635\ngithub.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigest).add.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:590\ngithub.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigest).add\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:601\ngithub.com/pingcap/tidb/util/stmtsummary.(*stmtSummaryByDigestMap).AddStatement\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/stmtsummary/statement_summary.go:344\ngithub.com/pingcap/tidb/util/stmtsummary/v2.Add\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/util/stmtsummary/v2/stmtsummary.go:537\ngithub.com/pingcap/tidb/executor.(*ExecStmt).SummaryStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1933\ngithub.com/pingcap/tidb/executor.(*ExecStmt).FinishExecuteStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1375\ngithub.com/pingcap/tidb/executor.(*ExecStmt).CloseRecordSet\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:1457\ngithub.com/pingcap/tidb/executor.(*recordSet).Close\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/executor/adapter.go:185\ngithub.com/pingcap/tidb/session.(*execStmtResult).Close\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/session/session.go:2490\ngithub.com/pingcap/tidb/server/internal/resultset.(*tidbResultSet).Close\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/internal/resultset/resultset.go:69\ngithub.com/pingcap/tidb/parser/terror.Call\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/parser/terror/terror.go:315\ngithub.com/pingcap/tidb/server.(*clientConn).executePreparedStmtAndWriteResult\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:423\ngithub.com/pingcap/tidb/server.(*clientConn).executePlanCacheStmt\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:233\ngithub.com/pingcap/tidb/server.(*clientConn).handleStmtExecute\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn_stmt.go:225\ngithub.com/pingcap/tidb/server.(*clientConn).dispatch\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1298\ngithub.com/pingcap/tidb/server.(*clientConn).Run\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/conn.go:1050\ngithub.com/pingcap/tidb/server.(*Server).onConn\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/server/server.go:662"]

**Comment by imhun** [comment]
> @imhun Can you provide the table schema to help us reproduce the issue?

Do you still need the table schema?

**Comment by time-and-fate** [comment]
Closing this issue according to @qw4990 as explained in https://github.com/pingcap/tidb/pull/48640.
