### ISSUE TITLE
Speed up PhysicalTopN#containVirtualColumn

### ISSUE THREAD

**Issue by tedyu** [pingcap/tidb#46809]
## Enhancement
Currently `PhysicalTopN#containVirtualColumn` performs nested loop matching given columns with those of `ByItems`.

We can establish `map[int64]*expression.Column` at the beginning of the method keyed by column Ids of `tCols`.

This way, the loop over `p.ByItems` can utilize the `map` to perform O(1) lookup.

**Comment by hawkingrei** [comment]
Good Catch！ Have you interest to improve it.
