### ISSUE TITLE
slow test `TestPartitionTableRandomIndexMerge` in `executor/test/indexmergereadtest` pkg

### ISSUE THREAD

**Issue by wuhuizuo** [pingcap/tidb#46836]
## Bug Report

<details><summary><h3>Average timecost was 148760.0000ms between "2023-09-01" AND "2023-09-08"<h3></summary>

Found records: 1  (filter only for runs that timecost >= threshold)
Max timecost: 148760ms
Min timecost: 148760ms
Avg timecost: 148760.0000ms

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32392/): used 148760ms

</details>

**Comment by zimulala** [comment]
CI: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/32990/pipeline

**Comment by wuhuizuo** [comment]
Recently runs:

> Timecost "-1" means it's not finished in bazel test target run.
Branch | Suite Name | Case Name | Report Time | Timecost Ms | Build URL
-- | -- | -- | -- | -- | --
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-11-02T11:33:00+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36570/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-11-02T10:53:49+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36566/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-11-01T16:08:58+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36507/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-11-01T11:04:16+08:00 | 144370 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36470/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-31T18:07:17+08:00 | 147590 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36434/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-31T17:50:02+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36430/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-31T16:17:50+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36416/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-31T14:03:11+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36391/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-31T10:42:53+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36376/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-30T19:42:50+08:00 | 144860 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36338/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-30T17:05:06+08:00 | 143600 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36313/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-30T16:52:16+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36312/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-30T16:37:46+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36310/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-30T11:53:19+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36284/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-28T07:21:35+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36233/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-27T16:59:32+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36201/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-27T16:32:44+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36197/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-26T20:44:41+08:00 | 146110 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36156/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-26T18:07:08+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36151/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-26T16:27:34+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36141/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-26T13:23:17+08:00 | 142830 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36128/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-26T12:16:30+08:00 | 146040 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36120/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-26T11:18:32+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36116/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-25T18:10:00+08:00 | 149080 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36093/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-25T16:04:10+08:00 | 146190 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/36078/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-23T11:38:46+08:00 | 146040 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35941/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-20T15:04:14+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35868/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-20T14:56:28+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35870/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-20T10:12:09+08:00 | 146340 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35835/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-19T13:16:15+08:00 | 144000 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35752/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-19T11:40:23+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35744/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-18T17:40:59+08:00 | 144290 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35694/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-18T17:34:57+08:00 | 147880 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35693/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-18T17:10:10+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35687/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-18T11:37:47+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35638/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-18T00:36:43+08:00 | 144230 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35627/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T21:10:13+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35620/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T16:09:47+08:00 | 145470 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35583/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T16:03:24+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35582/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T15:59:36+08:00 | 146050 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35579/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T14:55:20+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35566/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T12:44:44+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35549/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T12:41:51+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35547/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-17T01:08:26+08:00 | 148140 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35527/
master | //pkg/executor/test/indexmergereadtest:indexmergereadtest_test | TestPartitionTableRandomIndexMerge | 2023-10-16T17:19:45+08:00 | -1 | https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/35459/
