### ISSUE TITLE
slow test `TestOrderByWithLimit` in `executor/test/indexmergereadtest` pkg

### ISSUE THREAD

**Issue by wuhuizuo** [pingcap/tidb#46841]
## Bug Report

<details><summary><h3>Average timecost was 144160.0000ms between "2023-09-01" AND "2023-09-08"<h3></summary>

Found records: 4  (filter only for runs that timecost >= threshold)
Max timecost: 145730ms
Min timecost: 142740ms
Avg timecost: 144160.0000ms

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32355/): used 142740ms
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/32278/): used 145400ms
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/31993/): used 142770ms
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/31867/): used 145730ms

</details>

**Comment by zimulala** [comment]
Here also encountered: CI: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/32849/pipeline

**Comment by zimulala** [comment]
CI :  https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/32904/pipeline
