### ISSUE TITLE
IN Operator on primary key causes full table scan?

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#4686]
We found that IN operations on TiDB is very slow. Is this a problem with the optimizer?

here's the output of explain:

```sql
create table t2  (id int, primary key(id));
insert into t2 values (1),(2),(3);

explain select * from t2 where id in (1,2);

+---------------+---------+----------+------+------------------------------------------------+-------+
| id            | parents | children | task | operator info                                  | count |
+---------------+---------+----------+------+------------------------------------------------+-------+
| TableScan_4   |         |          | cop  | table:t2, range:[1,1], [2,2], keep order:false | 0.006 |
| TableReader_5 |         |          | root | data:TableScan_4                               | 0.006 |
+---------------+---------+----------+------+------------------------------------------------+-------+

```

Release Version: 0.8.0
Git Commit Hash: 46c1a0e3c37b6026c68029fe18873ea086697fed
Git Branch: HEAD
UTC Build Time: 2017-09-27 03:11:49

**Comment by shenli** [comment]
@Darren The table size is too small, it is better to scan table in this case.
You can insert more data and run `analyze table t2;`. Then try it again.

**Comment by Darren** [comment]
@shenli 

Thanks for the tip. It works for me!

We have a 10 billion rows table,  After running analyze table (though still not finished yet now) query with in operator returns very quickly. awesome!

I assume it is only one shot thing to do after bulk loading by `loader` tool, and I don't have to run it manually periodically later,  Am I right?

**Comment by shenli** [comment]
Yes. And in the next lease, we will do analyze table work automatically.
