### ISSUE TITLE
planner: simplify `StatsHandler` and break it down into multiple smaller and simpler sub-modules

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#46905]
## Enhancement
As you can see from the diagram below, the `StatsHandler`(`statistics/handle/handle.go:Handle`) structure is too complex. 
Actually, there are multiple features(modules) decoupled in it, which makes it hard to maintain and evolve. 
And these features rely on memory to synchronize information, which brings some risks like `whether to lock or not when accessing some fields`, `which methods be thread-safe`, `how to synchronize information with other nodes`.

To make it easier to maintain, we'd better break it down since obviously maintaining multiple smaller and simpler modules is safer than maintaining a big and complex module.
And only allow them to synchronize information through the storage to avoid consensus problems and thread-safe issues.

![image](https://github.com/pingcap/tidb/assets/7499936/41e9feb0-ec2a-48ed-a2f0-90c204c40e33)

**Comment by qw4990** [comment]
`Handle.mu` should be removed:

![fe247aa0-da36-4d27-bb15-2ec1a85c8c98](https://github.com/pingcap/tidb/assets/7499936/c28c4b48-f99d-4d00-b2ec-04922707346c)

**Comment by hawkingrei** [comment]
I think it has been completed.
