### ISSUE TITLE
admin check table report " invalid data type: Unsupported datum flag 1 for Json vector"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#46917]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create table 
```
.......
```
2. IMPORT INTO test.item_core  FROM "s3://xxx"
3. admin check table 
### 2. What did you expect to see? (Required)
admin check table successfully
### 3. What did you see instead (Required)
mysql> admin check table item_core;
ERROR 1105 (HY000): invalid data type: Unsupported datum flag 1 for Json vector

### 4. What is your TiDB version? (Required)

tidb:  hub.pingcap.net/devbuild/tidb:v7.4.0-1805
tikv: hub.pingcap.net/devbuild/tikv:v7.4.0-1804

**Comment by seiya-annie** [comment]
[tidb-admincheck.log.gz](https://github.com/pingcap/tidb/files/12585714/tidb-admincheck.log.gz)

**Comment by seiya-annie** [comment]
table schema and log please contact liting@pingcap.com

**Comment by tangenta** [comment]
Closed by https://github.com/pingcap/tidb/pull/48597
