### ISSUE TITLE
flaky test: TestGC

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#46930]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
see https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/32983/pipeline/

```
[2023/09/12 23:28:53.736 +08:00] [INFO] [dispatcher.go:654] ["task state transform"] [from=running] [to=succeed]

    framework_test.go:595: 

        	Error Trace:	disttask/framework/framework_test.go:595

        	Error:      	Not equal: 

        	            	expected: 4

        	            	actual  : 0

        	Test:       	TestGC

--- FAIL: TestGC (8.83s)
```

**Comment by hawkingrei** [comment]
the same as https://github.com/pingcap/tidb/issues/46928.
