### ISSUE TITLE
import into job finished but no data exists when injecting one of tidb failure for 2mins

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#46951]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、import into user_data1 from 's3://brie/mvindex-10000000-csv/test.user_data1.*.csv?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http://minio.pingcap.net:9001&force-path-style=true/' WITH skip_rows=1
2、 injecting one of tidb failure for 2mins

### 2. What did you expect to see? (Required)
import into job finished and checksum is correct

### 3. What did you see instead (Required)
cCrc32Checksum is 0, expected cCrc32Checksum is 3417923749

### 4. What is your TiDB version? (Required)
./tidb-server -V
Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/8f8c43319dd616fc7cb690f43803bcd2f481345d
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-09-13 06:50:51
GoVersion: go1.21.1
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by D3Hunter** [comment]
another issue found during HA test:
- during subtask running, tidb owner quite for a while, the subtask is marked as failed with cancelled error(guess from log), and dispatcher exit
- dispatcher restart, it sees the task as running, but it don't query failed subtask, so it think prev stage is finished and go into next stage directly
https://github.com/pingcap/tidb/blob/a7e3176f30e0dff6d993eda0ddd1b64776ad98f6/disttask/framework/dispatcher/dispatcher.go#L237-L243

**Comment by D3Hunter** [comment]
fixed by https://github.com/pingcap/tidb/pull/45623
