### ISSUE TITLE
show grants should quote database name

### ISSUE THREAD

**Issue by GMHDBJD** [pingcap/tidb#46975]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
GRANT ALL PRIVILEGES ON `xx.xx`.* TO 'root'@'%';
SHOW GRANTS FOR 'root'@'%';
```

### 2. What did you expect to see? (Required)
```
GRANT ALL PRIVILEGES ON `xx.xx`.* TO 'root'@'%'
```
### 3. What did you see instead (Required)
```
GRANT ALL PRIVILEGES ON xx.xx.* TO 'root'@'%'
```
### 4. What is your TiDB version? (Required)

master

**Comment by djshow832** [comment]
This issue indeed affects more than one version, but these labels just make bug triage duplicated. I'll remove them.
