### ISSUE TITLE
commit 05aa17 cause 13% performance regression in ddl testing

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#46978]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster with tidb  with 1 TiDB + 6 TiKV
2. restore the data of ossinsight
3. run
```
set global tidb_ddl_enable_fast_reorg=ON;
alter table github_events add index test_idx(repo_id,type,action,closed_at,actor_login);
```
### 2. What did you expect to see? (Required)
no performance regression

### 3. What did you see instead (Required)
commit 2b766b4f7712b1244290e49cee633dad179c1478 ddl duration: 4522s
profile
[nightly_ossinsight_ossinsight-ddl-add-index_1_1694606569.zip](https://github.com/pingcap/tidb/files/12606853/nightly_ossinsight_ossinsight-ddl-add-index_1_1694606569.zip)

commit 05aa17143df86602fef68fced906c6e47a9a00e2 ddl duration: 4984s
profile
[nightly_ossinsight_ossinsight-ddl-add-index_1_1694532157.zip](https://github.com/pingcap/tidb/files/12606851/nightly_ossinsight_ossinsight-ddl-add-index_1_1694532157.zip)

![image](https://github.com/pingcap/tidb/assets/84501897/84119e1f-379b-4078-9d8f-4521e1821b41)

### 4. What is your TiDB version? (Required)

commit 05aa17143df86602fef68fced906c6e47a9a00e2
https://github.com/pingcap/tidb/pull/46355

**Comment by lance6716** [comment]
fixed by https://github.com/pingcap/tidb/pull/47147
