### ISSUE TITLE
golint not happy with these files

### ISSUE THREAD

**Issue by astaxie** [pingcap/tidb#47]
:smiley: 

```
golint ./...
driver.go:331:24: func LastInsertId should be LastInsertID
parser/scanner.go:41:30: exported func NewLexer returns unexported type *parser.lexer, which can be annoying to use
```

**Comment by ngaut** [comment]
Thanks.
LastInsertId can't be fixed, since it's an interface of  standard library.
And parser/scanner.go is generated by golex.

**Comment by astaxie** [comment]
just leave it there. golint will :angry: someday. 

http://reactiongifs.me/wp-content/uploads/2013/12/hell-yes-big-lebowski-lookin-out-my-backdoor.gif
