### ISSUE TITLE
some  SQL result is not the same when enable/disable plancache

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#47008]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

In a session without plancache

```sql
set @@tidb_enable_prepared_plan_cache=0;
set @@time_zone='UTC';
set @@collation_connection='utf8_general_ci';
prepare s from 'select DATE_FORMAT("2020-01-01","%W") = "wednesday"';
execute s; -- output 1
set @@collation_connection='utf8_bin';
execute s; -- output 0
```

In a session with plancache

```sql
set @@tidb_enable_prepared_plan_cache=1;
set @@time_zone='UTC';
set @@collation_connection='utf8_general_ci';
prepare s from 'select DATE_FORMAT("2020-01-01","%W") = "wednesday"';
execute s; -- output 1
set @@collation_connection='utf8_bin';
execute s; -- output 1
```

### 2. What did you expect to see? (Required)

The second execute should output a same value not matter `tidb_enable_prepared_plan_cache` is on or off

### 3. What did you see instead (Required)

The output of the second execute is not the same for different `tidb_enable_prepared_plan_cache` value

### 4. What is your TiDB version? (Required)

master

**Comment by lcwangchao** [comment]
I think the reason is the expression is computing it's collation using session collation here: https://github.com/pingcap/tidb/blob/533de3ba882d188e3e0da4e465f1e74a81b4ccad/expression/collation.go#L242

But when the collation of session changes, the cached plan still uses the old value.

**Comment by qw4990** [comment]
It seems like we should consider connection's charset when hitting the plan cache:
![image](https://github.com/pingcap/tidb/assets/7499936/0087a8cf-4795-40e2-ad45-9440efd9be80)

I'll fix it this week.
