### ISSUE TITLE
slow test `TestUpgradeClusteredIndexDefaultValue` in `session` pkg

### ISSUE THREAD

**Issue by wuhuizuo** [pingcap/tidb#47046]
## Bug Report

<details><summary><h3>Average timecost was 289530.0000ms between "2023-09-09" AND "2023-09-16"<h3></summary>

Found records: 1  (filter only for runs that timecost >= threshold)
Max timecost: 289530ms
Min timecost: 289530ms
Avg timecost: 289530.0000ms

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33155/): used 289530ms

</details>

**Comment by wuhuizuo** [comment]
<details><summary><h3>Average timecost was 289530.0000ms between "2023-09-09" AND "2023-09-16"<h3></summary>

Found records: 1  (filter only for runs that timecost >= threshold)
Max timecost: 289530ms
Min timecost: 289530ms
Avg timecost: 289530.0000ms

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/33155/): used 289530ms

</details>

**Comment by jebter** [comment]
severity major

**Comment by wuhuizuo** [comment]
<details><summary><h3>Average timecost was 297210.0000ms between "2023-11-10" AND "2023-11-22"<h3></summary>

Found records: 2  (filter only for runs that timecost >= threshold)
Max timecost: 297900ms
Min timecost: 296520ms
Avg timecost: 297210.0000ms

- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/37829/): used 297900ms
- [CI build](https://do.pingcap.net/jenkins/job/pingcap/job/tidb/job/ghpr_unit_test/37460/): used 296520ms

</details>

**Comment by wuhuizuo** [comment]
<img width="683" alt="image" src="https://github.com/pingcap/tidb/assets/2574558/40b7d008-7bcc-4e26-b471-e559080ed6d8">

**Comment by wuhuizuo** [comment]
Not happened in latest 30 days.
