### ISSUE TITLE
add index task failed with "Error 1105 (HY000): batch scan region" when inject one of tidb failure last for 1mins

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#47061]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、add index
2、inject one of tidb failure last for 1mins

### 2. What did you expect to see? (Required)
add index can be success.

### 3. What did you see instead (Required)
add index task failed with "Error 1105 (HY000): batch scan region" when inject one of tidb failure last for 1mins

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.4.0-alpha
Edition: Community
Git Commit Hash: 7975acf7f7a28301689f2b16efd59525c689da0d
Git Branch: heads/refs/tags/v7.4.0-alpha
UTC Build Time: 2023-09-14 11:45:04
GoVersion: go1.21.1
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2023-09-17T17:35:48.356+0800

**Comment by ywqzzy** [comment]
may be related with https://github.com/pingcap/tidb/issues/47992.
Close the issue, will reopen it when meet it again
