### ISSUE TITLE
decodeIndexKvForClusteredIndexVersion1 function cause strings: negative Repeat count

### ISSUE THREAD

**Issue by dua01** [pingcap/tidb#47115]
### 1. Minimal reproduce step (Required)
`create table t (a int, b int, k varchar(64), primary key (a, b), key `k` (k));`
insert value which k is end of  over 127 spaces.
OR 
[table/tables/index_test.go:66](https://github.com/pingcap/tidb/blob/6271d1c80b2698d84ba90a146ff5034f9841b00b/table/tables/index_test.go#L66) Add 128 spaces behind abc and run test

### 2. What did you expect to see? (Required)
Test Pass
### 3. What did you see instead (Required)
`panic: strings: negative Repeat count`
### 4. What is your TiDB version? (Required)
Tidb 5.0+

**Comment by zanmato1984** [comment]
Transfer to sig/transaction.
