### ISSUE TITLE
Multi-arch docker images

### ISSUE THREAD

**Issue by vaibhavsood** [pingcap/tidb#4712]
Hi, want to check if the tidb docker image can be made official? The steps for making an image official are as per here: https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

Once this is done, the tidb container will be listed at https://hub.docker.com/explore/ , this could then enable publishing of multi-arch images https://github.com/docker-library/official-images#multiple-architectures

**Comment by shenli** [comment]
@vaibhavsood Thanks for your advice!
We decide not to make tidb image to dockerhub official images.  Please refer to this issue: https://github.com/pingcap/pd/issues/783
