### ISSUE TITLE
distributed add index failed, and can't finish revert

### ISSUE THREAD

**Issue by okJiang** [pingcap/tidb#47126]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

insert 2TB data
set tidb_enable_dist_task=on
add index

### 2. What did you expect to see? (Required)

1. success
2. if failed, revert success

### 3. What did you see instead (Required)

1. add index failed
2. can't revert the task
![5e1df098-b6be-4a6c-ac72-0a073d94f4af](https://github.com/pingcap/tidb/assets/23556834/51620c94-f511-4a29-bdaf-4f78531081b7)

3. tidb can't drop that database, can't select(region unavailable)

### 4. What is your TiDB version? (Required)

cluster deleted, it tested in 9/19, use the master at that time

[logs (3).zip](https://github.com/pingcap/tidb/files/12669958/logs.3.zip)

**Comment by okJiang** [comment]
![422824c3-0704-427b-b9c4-59baa397b71a](https://github.com/pingcap/tidb/assets/23556834/95c68657-4f76-40f6-a6a3-d63d09216a39)

## Phenomenon
scheduler cancel task suddenly

**Comment by okJiang** [comment]
ref https://github.com/pingcap/tidb/issues/46258

**Comment by ywqzzy** [comment]
![image](https://github.com/pingcap/tidb/assets/26179892/cb52a344-39f9-4458-a430-1955512f668b)
In this pic, the query result is as expected.

**Comment by ywqzzy** [comment]
Can‘t reproduce in HA tests, close it.

**Comment by jebter** [comment]
If you can reproduce it, you can open it again.
