### ISSUE TITLE
remove sys var tidb_enable_tiflash_pipeline_model

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#47138]
## Enhancement
After discussion, decide to remove `tidb_enable_tiflash_pipeline_model`. Why:
1. Normally user doesn't care which tiflash execution engine they are using.
2. TiFlash Pipeline execution engine is only to make it possible to implement tiflash resource control.
3. Too many switches will increase the mental burden of users.
So we decide to remove `tidb_enable_tiflash_pipeline_model`

**Comment by shawn0915** [comment]
hi, @guo-shaoge @easonn7 
this issue should be rename to [deprecate], not [remove], is it?
