### ISSUE TITLE
EXCHANGE PARTITION issue: report error between list partition and non-empty table

### ISSUE THREAD

**Issue by snowballbear** [pingcap/tidb#47154]
## Bug Report

An error is reported when exchanging partitions between the list partition table and a non-empty table, and it is incompatible with MySQL behavior

### 1. Minimal reproduce step (Required)

List partition table: 
```mysql
CREATE TABLE t1(
`DATE_ID` VARCHAR(10) NOT NULL,
PRIMARY KEY (`DATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY LIST COLUMNS(`DATE_ID`)
(
PARTITION `P20211231` VALUES IN ("2021-12-31"),
PARTITION `P20220100` VALUES IN ("2022-01-00"),
PARTITION `P20220131` VALUES IN ("2022-01-31")
);
 
CREATE TABLE t2(
`DATE_ID` VARCHAR(10) NOT NULL,
PRIMARY KEY (`DATE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
 
INSERT INTO t2 (`DATE_ID`) VALUES ('2022-01-31');
 
-- EXCHANGE PARTITION:
ALTER TABLE t1 EXCHANGE PARTITION P20220131 WITH TABLE t2;
```

### 2. What did you expect to see? (Required)
Partition exchange successful

### 3. What did you see instead (Required)
TiDB: 
mysql> ALTER TABLE t1 EXCHANGE PARTITION P20220131 WITH TABLE t2;
**ERROR 1737 (HY000): Found a row that does not match the partition**

MySQL:
<img width="487" alt="image" src="https://github.com/pingcap/tidb/assets/66671526/72d4b10e-b363-4d97-86ea-eb2601d174c1">

### 4. What is your TiDB version? (Required)
v6.5.1

**Comment by mjonss** [comment]
This was fixed by https://github.com/pingcap/tidb/pull/46533
