### ISSUE TITLE
Send huge SQL with --compress=true fails

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#47157]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
# create a huge SQL
$ mysql -h127.1 -uroot -P4000
mysql> select concat('select ', repeat('a', 16*1024*1024)) into outfile '/tmp/data.txt';

$ mysql -h127.1 -uroot -P4000 --compress=true < /tmp/data.txt;
WARNING: --compress is deprecated and will be removed in a future version. Use --compression-algorithms instead.
ERROR 2013 (HY000) at line 1: Lost connection to MySQL server during query
```

### 2. What did you expect to see? (Required)

success

### 3. What did you see instead (Required)

Lost connection and TiDB logs `unexpected EOF`.

### 4. What is your TiDB version? (Required)

tidb: master

```
$ mysql --version
mysql  Ver 8.1.0 for macos12.6 on x86_64 (Homebrew)
```

**Comment by djshow832** [comment]
Reason:
A packet larger than 16M is split into multiple compressed packets. TiDB just reads the compressed header, allocates the memory, and assumes all the rest of the data(even in new packets) are uncompressed: https://github.com/pingcap/tidb/blob/72cf5dfaf1ede525fe9843befef5d76a3e74495e/server/packetio.go#L121
However, when the zlib reader reads the next compressed packet, it also takes the compressed header as uncompressed data.

**Comment by dveeden** [comment]
Looks like this needs `SET GLOBAL max_allowed_packet=17*1024*1024;` to allow reproducing this.

**Comment by djshow832** [comment]
> Looks like this needs `SET GLOBAL max_allowed_packet=17*1024*1024;` to allow reproducing this.

They work the same to me. Even if the `max_allowed_packet` stays 64M, it is the same.

BTW, I tried `--compression-algorithms=zstd` and `--compression-algorithms=zlib`, they both fail.

**Comment by dveeden** [comment]
> > Looks like this needs `SET GLOBAL max_allowed_packet=17*1024*1024;` to allow reproducing this.
> 
> They work the same to me. Even if the `max_allowed_packet` stays 64M (default value), it is the same.
I tried again and now it works fine with both a tiup playground with a nightly version and with `./tidb-server` (unistore). I guess I had modified `max_allowed_packet` in the past...
