### ISSUE TITLE
Querying huge data with useCompress=true fails

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#47161]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```java
        String url = "jdbc:mysql://127.1:4000/test?useCompression=true";
        String user = "root";

        Class.forName("com.mysql.cj.jdbc.Driver");

        Connection conn = null;
        ResultSet rs = null;
        try {
            conn = DriverManager.getConnection(url, user, "");
            Statement stmt = conn.createStatement();
            rs = stmt.executeQuery("select repeat('a', 16*1024*1024)");
            rs.next();
            System.out.println(rs.getString(1).length());
            stmt.close();
            rs.close();
        } finally {
            if (conn != null) conn.close();
        }
```

### 2. What did you expect to see? (Required)

Output 16777216

### 3. What did you see instead (Required)

```
Exception in thread "main" java.sql.SQLException: Packets received out of order
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
	at Charset.main(Charset.java:15)
```

### 4. What is your TiDB version? (Required)

tidb: master
JDBC: 8.01

**Comment by djshow832** [comment]
Reason: 
When TiDB writes a packet, the packet is split in size of 2^24-5: https://github.com/pingcap/tidb/blob/72cf5dfaf1ede525fe9843befef5d76a3e74495e/server/packetio.go#L217, while the uncompressed header is still 2^24-1.
This is wrong: when the packet length is between 2^24-4 to 2^24-1, MySQL splits the **compressed** packet, not the uncompressed packet. That is, the uncompressed header is still 2^24-1 and the uncompressed length stays still, but every compressed packet just contains a piece of the uncompressed packet, not all of them. Thus there will be at least 2 compressed packets.

**Comment by djshow832** [comment]
Besides, the compressed packet is split into 1M packets, whereas MySQL splits it into 16K + 16M, and Connector/J splits it into 16M. It's fine for TiDB to define a different size, but a too small size may cause an overflow of compressed sequence.
The `max_allow_packet` can be set up to 1GB. If every compressed packet is only 1M, there will be at most 1000 compressed packets, and the compressed sequence can't fit into a byte.

**Comment by sergiomcalzada** [comment]
Same issue here after upgrade from v6.5.2 to v7.3.0. In this case using the .net connector

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql
https://github.com/mysql-net/MySqlConnector

Disabling compression in the connection string seems to work but it isn't the desired approach

**Comment by dveeden** [comment]
> Besides, the compressed packet is split into 1M packets, whereas MySQL splits it into 16K + 16M, and Connector/J splits it into 16M. It's fine for TiDB to define a different size, but a too small size may cause an overflow of compressed sequence. The `max_allow_packet` can be set up to 1GB. If every compressed packet is only 1M, there will be at most 1000 compressed packets, and the compressed sequence can't fit into a byte.

From https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_compression_packet.html
![image](https://github.com/pingcap/tidb/assets/1272980/8dbfbd1a-f491-4a19-af33-1ceae16673ad)

and from https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_packets.html#sect_protocol_basic_packets_sequence_id

![image](https://github.com/pingcap/tidb/assets/1272980/5b3b22b1-a98c-4151-93eb-500ca0a121cc)

The compressed sequence id works just like the normal sequence id and it wraps around once it hits 0xFF.
