### ISSUE TITLE
plan: wrong calculated row count for `Selection` plan

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#4726]
Sometimes when `Selection` is the parent of `IndexLookUp`, the row count of `Selection` is larger than `IndexLookUp`, this will cause the bad plan to be chosen.

We have a test case that reproduces this issue.
See https://github.com/pingcap/tidb/blob/master/plan/explain_test.go#L209

**Comment by hanfei1991** [comment]
fix by #4769 and #4765
