### ISSUE TITLE
The compression ratio of TiDB is much worse than MySQL

### ISSUE THREAD

**Issue by djshow832** [pingcap/tidb#47278]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Use zlib compression to connect to TiDB with MySQL client or JDBC.
2. Send a 16M SQL to TiDB and TiDB returns a 16M result, e.g. `select 'aaaaaaaaa....'`.
3. Check the compressed data received and sent by TiDB.

### 2. What did you expect to see? (Required)

The compressed data from client to TiDB is about 16K, and the data from TiDB to client should be also around 16K.

### 3. What did you see instead (Required)

The data from TiDB to client is surprisingly up to 2M.

About zstd default level: the compression ratio is also worse than MySQL, but the gap is not as huge as zlib.

### 4. What is your TiDB version? (Required)

master

**Comment by djshow832** [comment]
The reason: MySQL uses level 6 as default (https://github.com/mysql/mysql-server/blob/trunk/mysys/my_compress.cc#L354), but TiDB uses https://github.com/klauspost/compress#huffman-only-compression. I don't think TiDB should behave differently with MySQL.

**Comment by djshow832** [comment]
As for zstd, I prefer to use https://github.com/DataDog/zstd:
- The compression ratio of klauspost/compress is worse MySQL even with the same level, but datadog/zstd is the same with MySQL.
- The speed of datadog/zstd is much faster than klauspost/compress: https://github.com/klauspost/compress/blob/master/zstd/README.md#performance

**Comment by dveeden** [comment]
With this patch:
```
diff --git a/server/internal/packetio.go b/server/internal/packetio.go
index e015c0ce08..2ffbf5ed7f 100644
--- a/server/internal/packetio.go
+++ b/server/internal/packetio.go
@@ -381,12 +381,13 @@ func (cw *compressedWriter) Flush() error {
        // https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_basic_compression_packet.html
        // suggests a MIN_COMPRESS_LENGTH of 50.
        minCompressLength := 50
+       zlibCompressDefaultLevel := 6
        data := cw.buf.Bytes()
        cw.buf.Reset()
 
        switch cw.compressionAlgorithm {
        case mysql.CompressionZlib:
-               w, err = zlib.NewWriterLevel(&payload, zlib.HuffmanOnly)
+               w, err = zlib.NewWriterLevel(&payload, zlibCompressDefaultLevel)
        case mysql.CompressionZstd:
                w, err = zstd.NewWriter(&payload, zstd.WithEncoderLevel(cw.zstdLevel))
        default:
```

Patched (165 bytes compressed, 2065 uncompressed):
![image](https://github.com/pingcap/tidb/assets/1272980/a391a756-00b3-4db9-b50d-6bade6de786b)

Original (411 bytes compressed, 2065 uncompressed):
![image](https://github.com/pingcap/tidb/assets/1272980/055b9ec3-aeec-4e1f-902f-33f2cf13af73)
