### ISSUE TITLE
add index failed with error (encountered TSO stream being closed unexpectedly)

### ISSUE THREAD

**Issue by ywqzzy** [pingcap/tidb#47291]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
name:"ha_pdleader_to_pdfollower_all_network_partition"
faultType:"kill"
selector:"pdleader_to_pdfollower(all)"
selectorPolicy:"parallelly"
period:"@every 5m"
faultTotalRunTime:1800000000000
warmUpTime:60000000000
faultDuration:300000000000
Spec:Object
type:"kill"
SelectorPeersList:Array[1]
0:Object
selectorPeers:Array[1]
0:"tc-pd-leader"
Pitr:null
TiCDC:null
ddl:Object
addIndex:Array[1]
0:Object
db:"sysbench_64_7000w"
table:"sbtest1"
times:5
index_col_name:"c"
timeout:3600000000000
job_type:"ingest"
admin_check:false
count_check:false
checkConfig:Object
balanceCheck:true
raftLogLagCheck:true
clusterHealthCheck:true
pdSchedulerCheck:false
tidbConnPanicCheck:Object
enabley:true
raftLogGcCheck:true
workloadErrLogCheck:Object
allPhases:Object
checkEnable:false
checkStartRelativeTime:"WarmUpStart"
CheckStartAbsTime:"2023-09-23T09:42:43.870913849+08:00"
CheckDuration:1860000000000
timeout:43200000000000
repeatExecTimes:0

### 2. What did you expect to see? (Required)
Add index success
### 3. What did you see instead (Required)
"add index failed at 2023-09-23 09:53:58 (Error 1105 (HY000): encountered TSO stream being closed unexpectedly)
### 4. What is your TiDB version? (Required)

7.4 alpha
githash: 4e8295279868bb4e3262ac40fdfc774a9a033dbd

**Comment by seiya-annie** [comment]
could you please upload the tidb.log? @ywqzzy

**Comment by ywqzzy** [comment]
close as not see this any more
