### ISSUE TITLE
Support configuring session variable in lightning logical backend

### ISSUE THREAD

**Issue by guoshouyan** [pingcap/tidb#47305]
## Feature Request

Can lightning support specifying session variables to use in lightning config?

In our case, we want to disable the `async_commit` in lightning, that is because during our test on stale read on TiDB cluster, we find out that async_commit could block stale_ts, which will block the whole tikv node. Since this issue will not be solved in a short time, we want to disable the async_commit in lightning for now and here is my pr: https://github.com/pingcap/tidb/pull/46961

But I think we can generalize it by enabling lightning to let users specify a lit of session variable in the config that they want to use.

What is your thinking on this?

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
Hi, I found in the last we already proposed to set lightning session variables https://github.com/pingcap/tidb/pull/28471 , but only limited to the scenario that lightning is used as a library. Maybe now we can change

```
	Vars                       map[string]string `toml:"-" json:"vars"`
```

to 

```
	Vars                       map[string]string `toml:"session-vars" json:"vars"`
```

? Do you think it's acceptable?

**Comment by guoshouyan** [comment]
> Hi, I found in the last we already proposed to set lightning session variables #28471 , but only limited to the scenario that lightning is used as a library. Maybe now we can change
> 
> ```
> 	Vars                       map[string]string `toml:"-" json:"vars"`
> ```
> 
> to
> 
> ```
> 	Vars                       map[string]string `toml:"session-vars" json:"vars"`
> ```
> 
> ? Do you think it's acceptable?

Yeah, I think it should work in our case.

**Comment by guoshouyan** [comment]
Hi @lance6716 are you making the changes or you need me to make the changes?

**Comment by lance6716** [comment]
@guoshouyan I'm on holiday this week and haven't start to make the change. We can check the linked PR of this issue to know if you or me have started, and I guess I will not come to work before Oct 08
