### ISSUE TITLE
[BUG]ORDER BY in subquery is ignored in TiDB v7.3.0

### ISSUE THREAD

**Issue by yiding-he** [pingcap/tidb#47351]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

A bug exists in TiDB v7.3 where the ORDER BY clause in a subquery is ignored in the overall query results. For example:

```sql
SELECT * FROM (
  SELECT ep.exam_project_id, ep.create_time 
  FROM exam_project ep
  ORDER BY create_time DESC
) aa
```

In this example, the subquery correctly orders the results by the create_time field in descending order. However, when used in the overall query, the ordering is lost and the results are not sorted by create_time.

The subquery order by is expected to affect the overall result order, but is incorrectly ignored. This results in incorrect query results compared to what is expected.

![dbeaver_8YWIliinJ5](https://github.com/pingcap/tidb/assets/900606/61326d76-5e9b-4cdc-9fd2-960080d4825e)

![OVgmA1x3HE](https://github.com/pingcap/tidb/assets/900606/a42a0d33-c968-4455-a342-951d79ef7b76)

### 2. What did you expect to see? (Required)
The subquery order by is expected to affect the overall result order.

### 3. What did you see instead (Required)
However, when used in the overall query, the ordering is lost and the results are not sorted by create_time.

### 4. What is your TiDB version? (Required)
Release Version: v7.3.0
Edition: Community
Git Commit Hash: 40b72e7a9a4fc9670d4c5d974dd503a3c6097471
Git Branch: heads/refs/tags/v7.3.0
UTC Build Time: 2023-08-08 10:08:14
GoVersion: go1.20.7
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by fixdb** [comment]
This is expected behaviour, which is also abide by the sql standard.
You can keep the ordering by set tidb_remove_orderby_in_subquery=off.
