### ISSUE TITLE
refactor `types` package to decouple it from `stmtctx`

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#47355]
## Enhancement

Currently, the package `types` methods rely on the package `stmtctx` as the context for value conversion. We'd better to 
 avoid it and decouple these two packages for some reasons:

- `types` is a basic package, it should not have an assumption that all the value operations happen in a statement of SQL.
- `stmtctx.StatementContext` has too many fields and is challenging to use. We should a simple object for context with clear semantics

For above reasons, we should redesign the context in `package` to introduce a new context named `types.Context` . For example:

```go
type Context struct {
    flags Flags
    loc *time.Location
    warningFunc func(err)
}
```

The new context definition has some fields:

- flags: some flags to indicate how to handle the value conversion.
- loc: the timezone info, it will be used by some time-related functions.
- warningFunc: in some cases, we only want to append a warning to somewhere instead of returning an error. This function will be called when an error happens and the context indicates to enable warnings.

It's better to make the `Context` as immutable to make it thread-safe and easier to use. So the inner fields are designed to be private.

The `Flags` type will be defined as an int with each bit stands for a flag:

```go
const (
	FlagIgnoreTruncateErr Flags = 1 << iota
	FlagTruncateAsWarning
	FlagClipNegativeToZero
	FlagIgnoreOverflowError
	FlagOverflowAsWarning
	FlagIgnoreZeroDateErr
	FlagZeroDateAsWarning
	FlagIgnoreZeroInDateErr
	FlagZeroInDateAsWarning
	FlagIgnoreInvalidDateErr
	FlagInvalidDateAsWarning
	FlagSkipASCIICheck
	FlagSkipUTF8Check
	FlagSkipUTF8MB4Check
)
```

## sub tasks

- [x] #47478
- [x] #47479
- [x] #47590
- [x] #47829
- [x] #47507
- [x] #47508
- [x] #47517
- [x] #47518
- [x] #47511
- [x] #48573
- [x] #48911
- [x] #49277
- [x] #48611
- [x] #48751
- [ ] #49122

**Comment by YangKeao** [comment]
Maybe it's time to remove all (or as most as possible) `stmtctx` from `types`. Let's do it! https://github.com/pingcap/tidb/issues/48080

**Comment by bb7133** [comment]
Can we close this issue now?

**Comment by lcwangchao** [comment]
> Can we close this issue now?

https://github.com/pingcap/tidb/pull/49122 is still in review. Maybe we can close it after it finished.
