### ISSUE TITLE
SQL_BIG_RESULT syntax support.

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#4735]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
CREATE TABLE t1 (
  spID int(10) unsigned,
  userID int(10) unsigned,
  score smallint(5) unsigned,
  key (spid),
  key (score)
);

select sql_big_result spid,sum(userid) from t1 group by spid;
```

2. What did you expect to see?

```
mysql> select sql_big_result spid,sum(userid) from t1 group by spid;
Empty set (0.00 sec)
```

3. What did you see instead?

```
mysql> select sql_big_result spid,sum(userid) from t1 group by spid;
ERROR 1054 (42S22): Unknown column 'sql_big_result' in 'field list'
mysql> select spid,sum(userid) from t1 group by spid;
Empty set (0.01 sec)
```

4. What version of TiDB are you using (`tidb-server -V`)?

```
Release Version: 0.9.0
Git Commit Hash: a7aaa64c76b5a1e5bb66caf94b888515cc334cf1
Git Branch: master
UTC Build Time: 2017-10-10 08:44:43
```

**Comment by winkyao** [comment]
ref https://dev.mysql.com/doc/refman/5.7/en/select.html

>SQL_BIG_RESULT or SQL_SMALL_RESULT can be used with GROUP BY or DISTINCT to tell the optimizer that the result set has many rows or is small, respectively. For SQL_BIG_RESULT, MySQL directly uses disk-based temporary tables if needed, and prefers sorting to using a temporary table with a key on the GROUP BY elements. For SQL_SMALL_RESULT, MySQL uses fast temporary tables to store the resulting table instead of using sorting. This should not normally be needed.

**Comment by winkyao** [comment]
`sql_buffer_result` is not supported too.

**Comment by kolbe** [comment]
This was resolved some time ago. SQL_BIG_RESULT, SQL_SMALL_RESULT, and SQL_BUFFER_RESULT are all now parsed but ignored by TiDB.
