### ISSUE TITLE
Memory leak occurs in TiDB execution statement block

### ISSUE THREAD

**Issue by keeplearning20221** [pingcap/tidb#47365]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```go
package executor_test
  
import (
        "testing"
        "fmt"
        "github.com/pingcap/tidb/testkit"
        //      "github.com/stretchr/testify/require"
)

func TestProcedureFetchSpillTable(t *testing.T) {
        store := testkit.CreateMockStore(t)
        tk := testkit.NewTestKit(t, store)
        tk.MustExec("use test")
        //require.Len(t, tk.Session().GetSessionVars().MemTracker.GetChildrenForTest(), 1)
        for i:= 0; i< 100 ; i++ {
        tk.MustQuery("select 1;select 2;")
        fmt.Println("show MemTracker len:",len(tk.Session().GetSessionVars().MemTracker.GetChildrenForTest()))
        } 
}
```

### 2. What did you expect to see? (Required)
<img width="245" alt="image" src="https://github.com/pingcap/tidb/assets/97376271/5925abb6-9da3-44b6-9bdf-9ec7db7c07c1">

### 3. What did you see instead (Required)
<img width="266" alt="image" src="https://github.com/pingcap/tidb/assets/97376271/bad4bda2-61d2-4952-b20f-fc6d2bcc468f">

### 4. What is your TiDB version? (Required)

Release Version: v7.5.0-alpha-2-ge7abbcac16
Edition: Community
Git Commit Hash: e7abbcac16c8221cd41b14fd386c0119ef18a7fe
Git Branch: master
UTC Build Time: 2023-09-28 08:50:47
GoVersion: go1.21.1
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by SeaRise** [comment]
```
func TestProcedureFetchSpillTable(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	require.Len(t, tk.Session().GetSessionVars().MemTracker.GetChildrenForTest(), 0)
	for i := 0; i < 100; i++ {
		tk.MustQuery("select 1;")
		require.Len(t, tk.Session().GetSessionVars().MemTracker.GetChildrenForTest(), 0)
	}
}
```
If it is modified like this, it will meet the expectations.
it seems that there will be issues with `tk.MustQuery("select 1;select 2")`.

**Comment by zanmato1984** [comment]
This is probably related to multi-statement execution. Handle it to sql/infra.

**Comment by SeaRise** [comment]
I couldn't reproduce the issue in the cluster, it might only occur in unit tests.
