### ISSUE TITLE
The tikv capacity size should be considered when br restore

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#47418]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

3 tikv 1.2 T, 2 tikv 600GB, br restore data
![img_v2_5ce74c8a-f324-45f8-9ea3-6c4407cd1acg](https://github.com/pingcap/tidb/assets/7677963/2f05a3d4-dce6-4f04-ba1c-bfb78e3da371)

### 2. What did you expect to see? (Required)
The low capacity tikv has disk full risk. The tikv capacity size should be considered when br restore.
### 4. What is your TiDB version? (Required)

master

**Comment by BornChanger** [comment]
The asymmetrical deployment can only bring the unnecessary overhead of placement. I don't think it's a good idea to take capacity difference into account.

**Comment by BornChanger** [comment]
@lilinghai I don't think this is a bug. And I don't think we should introduce the extra complexity to PD's scheduling logicl

**Comment by BornChanger** [comment]
@lilinghai lin @jebter Please close it or convert it to a requirement.
