### ISSUE TITLE
The workloads affect each other when resource control is limited

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#47410]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tikv is 12c * 12, tidb is 12c *10
P0 workload is oltp read only, resource capacity is about 175K RU/s
P1 workooad is oltp write read(write 80%), resource capacity is about 600k RU/s
1. Set extremely large RU quota (as unlimited) and evaluate the impact of p1 on the p0
P0 resource usage is set half capacity which is about 90k ru/s, and continuously increase the traffic of p1 workload and observe its impact on p0. Whe the p1 resource usage is about 73k ru/s, the p0 workload qps decrease about 10%, and then the cluster tikv cpu is about 70% usage.
As the traffic for p1 increases, the QPS for p0 drops significantly, up to a maximum of 40%.
2. Set normal RU quota and evaluate the impact of p1 on the p0
P0 ru quota is 90k ru/s, P0 ru quota is 73k ru/s.
P0 resource usage is set half capacity which is about 90k ru/s, and continuously increase the traffic of p1 workload and observe its impact on p0.
As the traffic for p1 increases, The QPS of p0 drops by no more than 10%.
### 2. What did you expect to see? (Required)
When the ru is normal limit , before the system resources are fully utilized , the P1 business should not prematurely impact the P0 business.
### 4. What is your TiDB version? (Required)

master

**Comment by nolouch** [comment]
closed by https://github.com/tikv/tikv/pull/15929
