### ISSUE TITLE
a table is created using ctas ,after alter table add datetime column, the table cannot be queried

### ISSUE THREAD

**Issue by bob34007** [pingcap/tidb#47430]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
**case1 :**
MySQL [test]> create table test.slow_test like information_schema.SLOW_QUERY;
Query OK, 0 rows affected (0.13 sec)

MySQL [test]> insert into test.slow_test select * from information_schema.SLOW_QUERY;
Query OK, 2 rows affected (0.01 sec)
Records: 2  Duplicates: 0  Warnings: 0

MySQL [test]> alter table slow_test add column start_time datetime default now();
Query OK, 0 rows affected (0.32 sec)

MySQL [test]> select * from slow_test;
ERROR 1105 (HY000): [components/tidb_query_executors/src/table_scan_executor.rs:422]: Data is corrupted, missing data for NOT NULL column (offset = 0)

**case2:**
MySQL [test]> create table test.cluster_slow_log like information_schema.CLUSTER_SLOW_QUERY;
Query OK, 0 rows affected (0.10 sec)
MySQL [test]> insert into cluster_slow_log  select * from information_schema.CLUSTER_SLOW_QUERY;
Query OK, 3 rows affected (0.01 sec)
Records: 3  Duplicates: 0  Warnings: 0
MySQL [test]> select count(*) from cluster_slow_log;
+----------+
| count(*) |
+----------+
|        3 |
+----------+
1 row in set (0.01 sec)
MySQL [test]> alter table cluster_slow_log add column  start_time datetime default  now();
Query OK, 0 rows affected (0.30 sec)

MySQL [test]> select * from cluster_slow_log;
ERROR 1105 (HY000): invalid data type: Failed to decode row v2 data as u64

### 2. What did you expect to see? (Required)
query successed
### 3. What did you see instead (Required)
ERROR 1105 (HY000): [components/tidb_query_executors/src/table_scan_executor.rs:422]: Data is corrupted, missing data for NOT NULL column (offset = 0)
### 4. What is your TiDB version? (Required)
Release Version: v6.5.4
Edition: Community
Git Commit Hash: d7ce2f2faa1da3177a0f0a7e825f6e8fccd13ec8
Git Branch: heads/refs/tags/v6.5.4
UTC Build Time: 2023-08-23 08:34:38
GoVersion: go1.19.12
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by zimulala** [comment]
@bob34007 Thanks for your report!
It should be a similar problem(https://github.com/pingcap/tidb/issues/45744), and we fixed it. Please try it in the latest master.
