### ISSUE TITLE
flaky test integrationtest.sh

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#47432]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/30640/pipeline/445

seems due to unstable order 

```
time="2023-10-08T12:00:37+08:00" level=error msg="run test [planner/core/integration_partition] err: sql:select * from t where a < 2;: failed to run query 
\"select * from t where a < 2;\" 
 around line 642, 
 we need(116):
 select * from t where a < 2;
 a\tb\tc
-2147483648\t0000-00-00 00:00:00\t
-2147483648\t0000-00-00 00:00:00\tNULL
1\tNULL\tWow

but got(116):
select * from t where a < 2;
a\tb\tc
-2147483648\t0000-00-00 00:00:00\tNULL
-2147483648\t0000-00-00 00:00:00\t
1\tNULL\tWow

"
```

### 4. What is your TiDB version? (Required)
master

**Comment by Defined2014** [comment]
fixed by https://github.com/pingcap/mysql-tester/pull/108 and https://github.com/pingcap/tidb/pull/47358
