### ISSUE TITLE
Insert is slow

### ISSUE THREAD

**Issue by sarmut** [pingcap/tidb#4745]
Hi,

I created a 6 node cluster (_3 TiKV, 3 PD with TiDb runs on same 2 VMs, latest bits_) and created a single table with 2 columns, keyname & keyvalue, both are varchar (50) & (100).  I connect to this cluster thru MySql .Net connector from a separate machine and execute ‘Insert Into..’ statements through MySqlCommand.ExecuteNonQuery().   I observe that each insert takes ~45-60 milliseconds to finish.  Looks slow to me but like to know the performance others see.  Can you please let me know whether this performance is correct?

I ran a second scenario, where I concat all the ‘Insert Into..’ lines together (_10,000 records at a time_) and sent it via same .ExecuteNonQuery().   This time the command never returns.  But when I run ‘Select count(*)..’ thru mysql terminal I get the record counts for some time.  From that I can see that the cluster inserts ~40 records per second and eventually that command also yields connection timeout.  

Can you please point me to the performance numbers you’ve published, if any, so I can validate mine against yours?

Thank you

**Comment by shenli** [comment]
@sarmut Thanks for your feedback!
There are some deployment recommendation [here](https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md) and some tunning guide [here](https://github.com/pingcap/docs/blob/master/op-guide/tune-TiKV.md). We do not encourage users use VM to deploy TiDB cluster, especially in production environment.
For the performance, MySQL usually has lower latency than TiDB when your data size is not too large. We are narrowing that gap. The real advantage to TiDB is the easy horizontal scalability without having to resort to sharding. As your business grow, you can easily get larger throughput by adding new node.

**Comment by sarmut** [comment]
@shenli Thank you for the reply.  My VM SKU is Azure's L4S.. It has 4 CPUs and 32 gb ram.  The data disk is SSD.   Apart from the above deployment & tunning guides, do you have any published benchmarks?

**Comment by shenli** [comment]
We will release the v1.0 with a benchmark result next week.

**Comment by sarmut** [comment]
@shenli Thank you
