### ISSUE TITLE
left join query return different result 

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#47477]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
from asktug: https://asktug.com/t/topic/1013225

### 4. What is your TiDB version? (Required)
v6.5.3

**Comment by elsa0520** [comment]
Please give use the **All explain analyze information** (need to include all columns)
and the create table statement

**Comment by chrysan** [comment]
Downgrade to major since no reproduce steps sofar, will upgrade it to critical after reproduce steps are provided.

**Comment by elsa0520** [comment]
Could not reproduce it. Just close it.
