### ISSUE TITLE
add index job rollback failed after inject ddl owner network partition

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#47476]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
      workloads:
        - type: sysbench
          storage: s3://benchmark/sysbench_64_7000w
          db: sysbench_64_7000w
          tableNum: 64
          tableSize: 70000000
          threads: 64
          subType: oltp_read_write
          ignoreErrors: "all"
      cases:
        - name: "ha_tidb(ddl-owner)_to_all_network_partition"
          warmUpTime: 1m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_all"
          period: "@every 5m"
          faultDuration: 3m
          faultTotalRunTime: 30m
          ddl:
            addIndex:
              - db: "sysbench_64_7000w"
                table: "sbtest1"
                timeout: 60m
                times: 5
                index_col_name: "c"
                job_type: "ingest"

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index job rollback failed after inject ddl owner network partition
[2023/10/05 15:34:44.677 +08:00] [INFO] [db.go:103] ["select job_id, job_type, state from information_schema.ddl_jobs where query = 'alter table sbtest1 add index index_test_1696491014339 (c)'"]
[2023/10/05 15:34:44.727 +08:00] [INFO] [add_index.go:312] ["jobId: 467, job type: add index /* ingest */, state: rollingback"]

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.5.0-alpha
Edition: Community
Git Commit Hash: a3bafcdffb1008d224fe06af717e231c82b8f6b1
Git Branch: heads/refs/tags/v7.5.0-alpha
UTC Build Time: 2023-10-04 11:43:31
GoVersion: go1.21.1
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by ywqzzy** [comment]
same with https://github.com/pingcap/tidb/issues/48303
