### ISSUE TITLE
viewing slow-query log makes terminal gibberish 

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#4747]
if there are chinese charaters in the query, slow-query-log sometimes writes logs with bad utf-8 string, when viewing such logs with cat, tail, it will render the terminal gibberish, I have to run `reset`   to bring it back to normal, it is a bit annoying.

**Comment by shenli** [comment]
Thanks! We will convert the binary data to other format.

**Comment by Darren** [comment]
@shenli 

How about set the width in units of Unicode code points instead of bytes?

```diff
diff --git a/executor/adapter.go b/executor/adapter.go
index 52a1fa78..6d702d7a 100644
--- a/executor/adapter.go
+++ b/executor/adapter.go
@@ -260,9 +260,8 @@ func (a *statement) logSlowQuery() {
        cfg := config.GetGlobalConfig()
        costTime := time.Since(a.startTime)
        sql := a.text
-       if len(sql) > cfg.Log.QueryLogMaxLen {
-               sql = sql[:cfg.Log.QueryLogMaxLen] + fmt.Sprintf("(len:%d)", len(sql))
-       }
+       sql = fmt.Sprintf("%.*s(len:%d)", cfg.Log.QueryLogMaxLen, sql, len(sql))
+
        connID := a.ctx.GetSessionVars().ConnectionID
        logEntry := log.WithFields(log.Fields{
                "connectionId": connID,
```

**Comment by shenli** [comment]
@Darren This is better.  
But this will not solve all the problems. For some SQL statement contains byes data, we still get bee-bee-bee. We should do more things to handle the raw SQL text.
