### ISSUE TITLE
panic:runtime error: invalid memory address or nil pointer

### ISSUE THREAD

**Issue by loong95** [pingcap/tidb#47531]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

dashboard页面“SQL语句分析”、“慢查询”；客户端执行`select * from cluster_processlist`

### 2. What did you expect to see? (Required)
功能正常使用

### 3. What did you see instead (Required)
SQL语句分析查询报错：
![image](https://github.com/pingcap/tidb/assets/16333958/e2946a33-6b9e-421e-a6f7-48679ba72907)

PD日志如下：
![image](https://github.com/pingcap/tidb/assets/16333958/62b61678-93f1-4713-8dc5-44341da082f7)

客户端查询cluster_processlist报错：
![image](https://github.com/pingcap/tidb/assets/16333958/7d57d170-d170-4027-b7b1-c9cacbc3091b)
tidb-server日志如下：
![image](https://github.com/pingcap/tidb/assets/16333958/967cd1a2-0dc5-455d-bc3d-6cc17f85a6df)

进入慢查询页面，报错：
![image](https://github.com/pingcap/tidb/assets/16333958/e268f543-f3e5-4853-88fd-ca80239772c7)

### 4. What is your TiDB version? (Required)

5.7.25-TiDB-v7.1.1

![image](https://github.com/pingcap/tidb/assets/16333958/fe0f4110-8a79-41e7-9bcd-0db581d6b774)

![image](https://github.com/pingcap/tidb/assets/16333958/88638c3f-b01b-4c30-8963-d8947c2b4634)

![image](https://github.com/pingcap/tidb/assets/16333958/91f1c8fa-a3c8-4c97-abcc-3150cf6fe0ed)

![image](https://github.com/pingcap/tidb/assets/16333958/bcb61365-f8f5-4b25-894a-dbc4ac18a6a5)

部署了两个集群，这个集群有问题，另一个集群没问题

**Comment by cfzjywxk** [comment]
/cc @LykxSassinator 
It seems there's a crash at `recordSlowStat`, PTAL

**Comment by LykxSassinator** [comment]
> /cc @LykxSassinator It seems there's a crash at `recordSlowStat`, PTAL

I can add one check before `recordSlowScoreStat`, just like:
![image](https://github.com/pingcap/tidb/assets/18441614/26c79281-79ae-43a4-8f65-66c6f03950e9)

 but I'm still wondering the reason why `rpcCtx.Store == nil` in this case.
 
 Any other same issues exist?

**Comment by rebelsre** [comment]
遇到类似的问题，执行 select * from INFORMATION_SCHEMA.CLUSTER_STATEMENTS_SUMMARY_HISTORY limit 1; 稳定重现
[replayer_lpj0ZXzLWwOSvnGNp9b-mQ==_1698649890339077634.zip](https://github.com/pingcap/tidb/files/13202043/replayer_lpj0ZXzLWwOSvnGNp9b-mQ._1698649890339077634.zip)

**Comment by cfzjywxk** [comment]
Close this issue as it's fixed in https://github.com/tikv/client-go/pull/1017, 
the client-go depency is already updated in tidb repo.

**Comment by rebelsre** [comment]
> 关闭此问题，因为它已在 [tikv/client-go#1017](https://github.com/tikv/client-go/pull/1017) 中修复，client-go depency 已经在 tidb repo 中更新。

请问有什么临时的解决方案让它重新可用不，而不是只能等下个版本的更新
