### ISSUE TITLE
analyze table with timestamp column reports spurious error?

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#4758]
1. What did you do?
```sql
create table t1 (i int, t timestamp NOT NULL, primary key(i));
insert t1 values (1, now());
analyze table t1;
```

2. What did you expect to see?

there should be no error.

3. What did you see instead?

analyze itself seems ok:
```sql
mysql> analyze table t1;
Query OK, 0 rows affected (6.01 sec)
```
but there's error in the log:

```log
2017/10/12 16:06:58.652 terror.go:342: [error] /Users/darren/Sources/go/src/github.com/pingcap/tidb/util/types/time.go:35: invalid time format
/Users/darren/Sources/go/src/github.com/pingcap/tidb/util/types/mytime.go:102: 
/Users/darren/Sources/go/src/github.com/pingcap/tidb/util/types/time.go:508: 
```

and each time tidb-server starts, while histogram trying to load buckets from mysql.stats_buckets also shows this error.

4. What version of TiDB are you using (`tidb-server -V`)?

Release Version: 0.9.0
Git Commit Hash: e488bcc23dd837ae747e8da8c4ec7769484d958d
Git Branch: master
UTC Build Time: 2017-10-12 08:00:24

**Comment by coocood** [comment]
Thank you for your report, we'll investigate this error soon.

**Comment by shenli** [comment]
@Darren Please try the latest master.
