### ISSUE TITLE
When upgrading from a version earlier than v6.2 to a later version, DDL owner change may be stuck due to network issues

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#47607]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

We will check the DDL owner in the following code.
https://github.com/pingcap/tidb/blob/bf8f570fcb64f0cffe3477a508dbba71d1093822/session/bootstrap.go#L1245-L1255

Then we do upgrades. But there may be an owner change case before finishing upgrades. So the judgment of the DDL job put KV or table may have miscalculation.

### 4. What is your TiDB version? (Required)

master

**Comment by zimulala** [comment]
Workaround： Restart the TiDB that is currently upgraded and block (as long as the cluster does not have the above scenario again

**Comment by wjhuang2016** [comment]
It's a corner case and has a workaround, I don't think it's a critical bug. Major is more appropriate.

**Comment by wjhuang2016** [comment]
I can't safely fix this bug, it's better to work around it manually.
