### ISSUE TITLE
Whether  _tidb_rowid  not unique is a severe problem for partitioned table?

### ISSUE THREAD

**Issue by L-maple** [pingcap/tidb#47621]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
As a heavy user, I always think of _tidb_rowid as unique. Because it is allocated incrementally. For a non-partitioned table, this is not a problem.
But for a partitioned-table, the _tidb_rowid can be non-unique. The record row prefix for partitioned table is `t{partitionID}_r{_tidb_rowid}` when no clustered primary key exists. When two record rows having the same `_tidb_rowid` belong to different partitions, the rows are still unique.
When rows in partitioned table may have the same `_tidb_rowid`? The case is `exchange partition`...
```SQL 
use test;
drop table if exists pt, nt;
create table pt (a int) partition by range(a) (
	partition p0 values less than (3),
	partition p1 values less than (6),
        partition p2 values less than (9),
        partition p3 values less than (50000000)
);
create table nt(a int);
insert into pt values (4), (8), (9);
insert into nt values (1);
select *, _tidb_rowid from pt;
```

### 2. What did you expect to see? (Required)
I am confused now. I don't know whether _tidb_rowid should be unique in a partitioned table.  
The document does not mark the _tidb_rowid as `Unique`. Does it means the _tidb_rowid could be non-unique?
![image](https://github.com/pingcap/tidb/assets/20724552/1af5b0ca-5266-452d-89f6-8a36cc53984f)

### 3. What did you see instead (Required)
<img width="416" alt="image" src="https://github.com/pingcap/tidb/assets/20724552/67ad4177-65fd-480f-a921-12c2ee08eccb">

### 4. What is your TiDB version? (Required)
<img width="627" alt="image" src="https://github.com/pingcap/tidb/assets/20724552/f262e543-b3ea-4d5b-90fb-ecef53d075d4">

**Comment by Defined2014** [comment]
Yes, `_tidb_rowid` could be `non-unique` after `exchange partition`. It's an expected behavior.

**Comment by L-maple** [comment]
> Yes, `_tidb_rowid` could be `non-unique` after `exchange partition`. It's an expected behavior.
@Defined2014 Thanks for your answer ~ I will close this issue.
