### ISSUE TITLE
Deploy a cluster using IPv6 address, initializtion fail 

### ISSUE THREAD

**Issue by fzzf678** [pingcap/tidb#47644]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```
tiup cluster deploy ipv6 v6.1.7 ./open_source_cluster_ipv6_priv.yaml -u root -p

tiup cluster start ipv6 --init
```

### 2. What did you expect to see? (Required)
init success
### 3. What did you see instead (Required)
init fail.
tidb log:

> [2023/10/16 11:41:32.366 +08:00] [FATAL] [main.go:726] ["failed to create the server"] [error="listen tcp: address :::4605: too many colons in address"] [stack="main.createServer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:726\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"] [stack="main.createServer\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:726\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/tidb-server/main.go:203\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]

### 4. What is your TiDB version? (Required)
v6.1.7  v5.4.3 v5.2.4 v5.1.5 v5.0.6

**Comment by jebter** [comment]
Please use the latest version 6.5.x and above ：https://docs.pingcap.com/tidb/stable/release-6.5.1#improvements
