### ISSUE TITLE
Support . _ and $ in user-defined variables

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#4771]
Please answer these questions before submitting your issue. Thanks!

> User variables are written as @var_name, where the variable name var_name consists of alphanumeric characters, ., _, and $. A user variable name can contain other characters if you quote it as a string or identifier (for example, @'my-var', @"my-var", or @`my-var`).

https://dev.mysql.com/doc/refman/5.7/en/user-variables.html

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql> set @'my-var' = 42;
ERROR 1105 (HY000): line 1 column 5 near "'my-var' = 42" (total length 18)

mysql> set @`my-var` = 42;
ERROR 1105 (HY000): line 1 column 5 near "`my-var` = 42" (total length 18)

mysql> set @my.var = 42;
ERROR 1105 (HY000): line 1 column 8 near "var = 42" (total length 16)
```

2. What did you expect to see?

Those should be valid user-defined variables.

**Comment by morgo** [comment]
This has been fixed in TiDB!  Confirming on my install:
```
mysql> set @'my-var' = 42;
Query OK, 0 rows affected (0.00 sec)

mysql> select @'my-var';
+----------+
| 'my-var' |
+----------+
| 42       |
+----------+
1 row in set (0.00 sec)

mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-305-gef0ad26da
Git Commit Hash: ef0ad26da8f99044a741fc0a781a0c4791446e8b
Git Branch: newmaster
UTC Build Time: 2018-12-10 05:50:33
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to re-open if you have any questions.  Thanks!
