### ISSUE TITLE
Error 403 is reported when trying to backup data to OSS(Alibaba)

### ISSUE THREAD

**Issue by smallhorsegg** [pingcap/tidb#47722]
tidb版本为6.6
br配置如下：
apiVersion: pingcap.com/v1alpha1
kind: Backup
metadata:
  name: demo1-full-backup-s3
  namespace: tidb-backup
spec:
  backupType: full
  br:
    cluster: basic
    clusterNamespace: tidb-cluster
  from:
    host: xxx
    port: 4000
    user: root
    secretName: backup-demo1-tidb-secret
  s3:
    provider: alibaba
    secretName: s3-secret
    region: oss-cn-beijing
    bucket: ops-gitlab-backup
    endpoint: http://oss-cn-beijing.aliyuncs.com

backup message:
 cluster tidb-backup/demo1-full-backup-s3, wait pipe message failed, errMsg [2023/10/17 10:24:44.986 +00:00] [ERROR] [backup.go:49] ["failed to backup"] [error="error occurred when checking backupmeta file: Forbidden: Forbidden\n\tstatus code: 403, request id: 652E60EC419DF73636E4DD1A, host id: "] [errorVerbose="Forbidden: Forbidden\n\tstatus code: 403, request id: 652E60EC419DF73636E4DD1A, host id: \ngithub.com/pingcap/errors.AddStack\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/errors.go:174\ngithub.com/pingcap/errors.Trace\n\t/go/pkg/mod/github.com/pingcap/errors@v0.11.5-0.20221009092201-b66cddb77c32/juju_adaptor.go:15\ngithub.com/pingcap/tidb/br/pkg/storage.(*S3Storage).FileExists\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/storage/s3.go:555\ngithub.com/pingcap/tidb/br/pkg/backup.(*Client).SetStorageAndCheckNotInUse\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/backup/client.go:228\ngithub.com/pingcap/tidb/br/pkg/task.RunBackup\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/pkg/task/backup.go:407\nmain.runBackupCommand\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/backup.go:48\nmain.newFullBackupCommand.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/backup.go:117\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\nerror occurred when checking backupmeta file"] [stack="main.runBackupCommand\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/backup.go:49\nmain.newFullBackupCommand.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/backup.go:117\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968\nmain.main\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/br/br/cmd/br/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"]

确认ak、sk权限正常，但找阿里云开单回复走的是sts认证，s3-secret：
apiVersion: v1
data:
  access_key:  xxx
  secret_key: xxx
kind: Secret
metadata:
  creationTimestamp: "2023-10-17T07:08:38Z"
  name: s3-secret
  namespace: tidb-backup
  resourceVersion: "1941967902"
  uid: a4f98ab3-cfe7-4948-b061-19c21cc181ed
type: Opaque

describe-job:
![Uploading image.png…]()

**Comment by bb7133** [comment]
@smallhorsegg Please avoid using Chinese in this repository, I've changed it to English. FYI.

**Comment by wuyudian1** [comment]
I also encountered the same problem. Why was this issue closed? Is there a solution available now?
