### ISSUE TITLE
Lighting failed parse pd host

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#47731]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
/tidb-lightning "-pd-urls" "tc-pd.e2e
-htap-ddl-tps-3240612-1-481:2379" "-tidb-host" "tc-tidb.e2e-htap-ddl-tps-3240612-1-481" "-tidb-port" "4000" "-tidb
-user" "root" "-tidb-password" "" "-backend" "local" "-sorted-kv-dir" "/tmp/sorted-kv-dir" "-d" "s3://nfs/
tiflash/csv-tpcc-100?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http%3a%2f%2fminio.pingcap.net%3a9000&force
-path-style=true" "-c" "/lightning.yaml"
```
lightning encountered error: [Lightning:KV:ErrCheckKVVersion]check tikv version error: Get "http://http//tc-pd-1.tc-pd-
peer.e2e-htap-ddl-tps-3240612-1-481.svc:2379/pd/api/v1/stores": dial tcp: lookup http on [169.254.25.10:53](http://169.254.25.10:53/): no such host
### 4. What is your TiDB version? (Required)

v7.1.2

**Comment by jebter** [comment]
duplicate https://github.com/pingcap/tidb/pull/47734
