### ISSUE TITLE
[global sort] can not add index with global sort concurrency

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#47758]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. enable global sort
2. add index for 2 tables concurrenty

### 2. What did you expect to see? (Required)
1. all running ddl jobs can use global sort add index
### 3. What did you see instead (Required)
1. only 1 ddl job can use ingest model and global sort
2. another add index job using txn merge 
### 4. What is your TiDB version? (Required)
```sql
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.5.0-alpha                             |
| Edition: Community                                        |
| Git Commit Hash: 79db4ec58be3856995d31013e20f3faa57e3a3ac |
| Git Branch: heads/refs/tags/v7.5.0-alpha                  |
| UTC Build Time: 2023-10-16 11:42:39                       |
| GoVersion: go1.21.3                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+

```

**Comment by ywqzzy** [comment]
For resource control and limit the resource that global sort consumed, we only allow one job running at the same time.
We will support running multiple jobs later.

**Comment by Benjamin2037** [comment]
We will remove this limitation in later version

**Comment by tangenta** [comment]
TiDB cannot add index concurrently even after https://github.com/pingcap/tidb/pull/48645.

**Comment by tangenta** [comment]
In order to cherry-pick v7.5.1, change to severity/major bug.
