### ISSUE TITLE
query with limit take a long time

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#47773]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
from asktug: https://asktug.com/t/topic/1014241

from @time-and-fate :
This key_skipped_count is the count of the internal mechanism of rocks db, not directly related to the mvcc level. Moreover, this table shows that the process key size is quite large. Whether it is reasonable or not may require colleagues from tikv to take a look.At the level of execution plan, because there is no index and the primary key does not match the filter column, the entire table can only be read. The specific number of rows that need to be read depends on the filtering performance of the filter. If there are no columns that match the filter in the table, the entire table needs to be read. Adding an index should be much better.Another known issue is that the first execution of a table that is too large may take a lot of time to load the region cache, but the second execution will be faster. I'm not sure if this is related.

After checking, it seems that the selection is indeed too slow.If the evaluation of'or list 'is false, then every sub-item must be evaluated to false, there is no shortcut.Although a large number of'or 'may also be the reason, there is indeed a high possibility that this cast will be slow. If you want to confirm it, you may still need to capture the profile. He also measured it carefully in his reply. At least you can rewrite the SQL first to see how much performance improvement there is to avoid this cast.

**Comment by time-and-fate** [comment]
The "key_skipped_count" related question is not quite related to tidb-server and there are also further explanations in the post.
For the execution plan, there's no more information to conclude some concrete bugs or improvements for tidb.
And there are also no more activities in the post, so closing this issue. Feel free to reopen it if there are further problems.
