### ISSUE TITLE
[global sort] add index takes a long time

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#47786]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. enable global sort
2. add index

### 2. What did you expect to see? (Required)
1. add index can finished in a reasonable time
### 3. What did you see instead (Required)
1. add index takes a long time(about 25h) and not finished
![图片](https://github.com/pingcap/tidb/assets/10184437/37ee5b62-f4e1-4e06-85b7-23fc2f91469e)

### 4. What is your TiDB version? (Required)
```sql
[16:20:12]TiDB root:mysql> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.5.0-alpha                             |
| Edition: Community                                        |
| Git Commit Hash: 79db4ec58be3856995d31013e20f3faa57e3a3ac |
| Git Branch: heads/refs/tags/v7.5.0-alpha                  |
| UTC Build Time: 2023-10-16 11:42:39                       |
| GoVersion: go1.21.3                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
```

**Comment by ywqzzy** [comment]
MergeIter read over 5000 files.
In normal case, mergeIter should read less than 1000 files to archive high performance.

**Comment by ywqzzy** [comment]
https://github.com/pingcap/tidb/pull/47886 This will eliminate the problem, close for now
