### ISSUE TITLE
How to modify the default collation of database/table?

### ISSUE THREAD

**Issue by lifw555** [pingcap/tidb#4782]
现在全部默认都是：utf8_bin。

我找遍个各种文档，没有发现在哪里设置？

因为我们从原来的mysql转移数据库的时候，发现原来默认的utf8_general_ci，现在都变成utf8_bin了。

希望提供一个启动参数，可以设置系统的默认collection。同时，在创建数据库时，可以设置collection，并且这个数据库中的所有表，及表中的相关字段都是使用Database的collection，比如：CREATE DATABASE IF NOT EXISTS yourdbname DEFAULT CHARSET utf8 COLLATE utf8_general_ci;

**Comment by shenli** [comment]
@lifw555 Please refer to this [doc](https://github.com/pingcap/docs-cn/blob/master/sql/character-set-support.md).
TiDB doesn't support any case insensitive collation. The collations in TiDB are case sensitive.

**Comment by lifw555** [comment]
got it.
