### ISSUE TITLE
sql query exception

### ISSUE THREAD

**Issue by ChengjinWu** [pingcap/tidb#4788]
![](https://raw.githubusercontent.com/ChengjinWu/AddoilTools/master/src/util/tidb_bug.png)

Server version: 5.7.1-TiDB-0.8.0 MySQL Community Server (Apache License 2.0)

**Comment by coocood** [comment]
@ChengjinWu 
Thank you for your report, this issues probably have been fixed by https://github.com/pingcap/tidb/pull/4413
and
https://github.com/pingcap/tidb/pull/4470

Please use the latest version and try again.
