### ISSUE TITLE
add index status was always running after inject ddl owner network partition

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#47954]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run workload
2、add index for one table of sysbench
3、add index repeatedly
4、inject ddl owner network partition

case config
      workloads:
        - type: sysbench
          storage: s3://benchmark/sysbench_64_7000w
          db: sysbench_64_7000w
          tableNum: 64
          tableSize: 70000000
          threads: 64
          subType: oltp_read_write
          ignoreErrors: "all"
      cases:
        - name: "ha_tidb(ddl-owner)_to_all_network_partition"
          warmUpTime: 1m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_all"
          period: "@every 5m"
          faultDuration: 3m
          faultTotalRunTime: 30m
          ddl:
            addIndex:
              - db: "sysbench_64_7000w"
                table: "sbtest1"
                timeout: 60m
                times: 5
                index_col_name: "c"
                job_type: "ingest"
                admin_check: false
                count_check: false

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index status was always running after inject ddl owner network partition

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: cd0587eb75d70c35f01153ac5b3b6bcafaff1bee
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2023-10-25 11:44:53
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by ywqzzy** [comment]
problem: tests after the first failed test can't scheduler add index dist task for getting no available nodes.
I am working on it.
