### ISSUE TITLE
Allow Dumpling CSV being ingested by Redshift

### ISSUE THREAD

**Issue by breezewish** [pingcap/tidb#47964]
## Enhancement

Usually, a BINARY column is represented in VARBYTE type in Redshift. Currently Dumpling outputs CSV as follows:

```sql
create table t (i int, b binary);
insert into t values (1, 'a'), (2, 'b'), (3, 'c');
```

Generated CSV:

```
"i","b"
1,"a"
2,"b"
3,"c"
```

However, Redshift requires the CSV content represented in Hex format when ingesting CSV files: https://docs.aws.amazon.com/redshift/latest/dg/copy-usage-varbyte.html

We propose to provide a new parameter called `--dialect` to control the output behavior.

When `--dialect=redshift`, the BINARY column in the CSV will be output as what Redshift requires.

Also, in future, when we discover other incompatible problems we could enhance this parameter, for example, we could add more transformations to the `--dialect=redshift` when necessary, and even introduce other dialects.

**Comment by Frank945946** [comment]
how about  --output-format="redshift" , --output-format="snowflake" .

**Comment by lichunzhu** [comment]
> how about --output-format="redshift" , --output-format="snowflake" .

SGTM

**Comment by breezewish** [comment]
"Output format" sounds related with JSON, CSV, SQL, etc, so that I think "dialect" might be better, or may be something like "output-dialect"? I'm open to all of these names.
