### ISSUE TITLE
Don't return `types.NameSlice` for `BuildLogicalPlanForTest` function

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#47974]
## Enhancement

The `BuildLogicalPlanForTest` function returns `p.OutputNames()` which is never used. So we can delete it.

**Comment by bagechengzi** [comment]
Hi, I would like to work on this issue, would you mind assign it to me？

**Comment by bagechengzi** [comment]
Hi, I would like to work on this issue, would you mind assign it to me

**Comment by Defined2014** [comment]
> Hi, I would like to work on this issue, would you mind assign it to me

Done
