### ISSUE TITLE
br v7.1.0 restore get error

### ISSUE THREAD

**Issue by RenlySir** [pingcap/tidb#47996]
### 1. Minimal reproduce step (Required)

1.br backup cluster1;(table-column-count-limit: 4096,table column is about 2500)
2.br restore cluster 2;(table-column-count-limit: 4096,table column is about 2500))
3.get error : Error: [dd1:11171Too many columns

### 2. What did you expect to see? (Required)
i can restore successfully

### 3. What did you see instead (Required)
get error : Error: [dd1:11171Too many columns

### 4. What is your TiDB version? (Required)
tidb v7.0.0

![image](https://github.com/pingcap/tidb/assets/40784771/a4f19494-53f7-4e24-86c0-d9f603741837)

**Comment by RenlySir** [comment]
v7.1.2 get it

**Comment by RenlySir** [comment]
v7.1.2 get it

**Comment by BornChanger** [comment]
@RenlySir Can you close the issue since it's fixed in v7.1.2?

**Comment by BornChanger** [comment]
@jebter can you please help close it?
