### ISSUE TITLE
Move sql escaping functionality from pkg/util/sqlexec to pkg/util/sqlescape

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#48055]
## Enhancement

The [sql escaping functionality](https://github.com/pingcap/tidb/blob/master/pkg/util/sqlexec/utils.go) in TiDB is excellent. For example, it covers both escaping strings and identifiers.

I would like to make use of this library outside of TiDB. However, in order to do so I end up with a bunch of other indirect dependencies. This is because the package `sqlexec` has additional functionality.

I would like to propose splitting this into two packages:
- `sqlexec`: existing functionality related to executing statements.
- `sqlescape`: the functionality limited to escaping

Happy to contribute a PR for this.

**Comment by YangKeao** [comment]
Is it enough to just split packages? As I know (not sure) Golang handles dependencies in mod level, so if the new package doesn't contain a standalone go.mod/go.sum (like parser), it'll still try to pull the whole TiDB and its dependencies 🤔.

**Comment by morgo** [comment]
I'm okay if it needs to pull it. Currently though it doubles the size of my go.mod file with indirect dependencies.

We are somewhat careful with dependencies, and pay attention to the licenses of them. Having a long list is a bit of a nightmare to manage.

I have a [branch here](https://github.com/morgo/tidb/tree/move-sqlescape) which I've tested against, and my go.mod remains clean. There are a few thumbs up now, so I'll submit this as a pull request.
