### ISSUE TITLE
import into failed when inject pdleader io delay 500ms 

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48065]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run import into
2、inject pdleader io delay 500ms
case config：
  - name: config_ha_pdleader_io_delay_500ms
    default: |
      tag: "ha-test-import-into"
      cases:
        - name: ha_pd(leader)_io_delay(500ms)
          faultType: iochaos_io_delay(volumePath:/var/lib/pd,path:/var/lib/pd/data/**/*,delay:500ms,percent:100)
          warmUpTime: 1m
          selector: pd(leader)
          period: "@every 5m"
          faultDuration: 1m
          faultTotalRunTime: 20m
          importInto:
            - db: "importtest"
              schema: "CREATE TABLE `user_data1` (
                `uid` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
                `data` mediumblob NOT NULL,
                `update_data` blob NOT NULL,
                `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
                `update_time` datetime DEFAULT NULL,
                PRIMARY KEY (`uid`) /*T![clustered_index] CLUSTERED */,
                KEY `k_1` (`update_time`)
                ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5850196;"
              cmd: "import into user_data1 from 's3://brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=minioadmin\u0026secret-access-key=minioadmin\u0026endpoint=http://minio.pingcap.net:9001\u0026force-path-style=true' WITH DETACHED,skip_rows=1"
              timeout: 120m
              crc32Checksum: 3582177512

### 2. What did you expect to see? (Required)
import into success

### 3. What did you see instead (Required)
import into failed when inject pdleader io delay 500ms

"the status of import job is not finished or running (now: 2023-10-29 15:10:05, jobId: 60008, step: importing, status: failed)
operatorLogs:
[2023-10-29 14:55:36] ###### start import into
import into user_data1 from 's3://brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=minioadmin&secret-access-key=minioadmin&endpoint=http://minio.pingcap.net:9001&force-path-style=true' WITH DETACHED,skip_rows=1
[2023-10-29 14:55:36] ###### wait for import job to finish
[2023-10-29 15:10:05] ###### wait for import job to finish failed
select id, step, status from mysql.tidb_import_jobs where start_time >= '2023-10-29 14:55:36'
jobId: 60008, step: importing, status: failed"

### 4. What is your TiDB version? (Required)
git hash：3682bd82cac05a75241ed9fc9f29a1d320d776a7

**Comment by D3Hunter** [comment]
duplicate with https://github.com/pingcap/tidb/issues/48075, will close this one
