### ISSUE TITLE
Chunks cannot be re-used across multiple `GetMatchedRowsAndPtrs` calls

### ISSUE THREAD

**Issue by YangKeao** [pingcap/tidb#48082]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run the benchmark `BenchmarkHashJoinExec`

### 2. What did you expect to see? (Required)

Allocating chunks will not cost too much resources.

### 3. What did you see instead (Required)

Allocating chunks takes a large percent of the total profiling.

Ref: https://github.com/pingcap/tidb/pull/41081.

**Comment by winoros** [comment]
So why does ARM suffer much more compared with x86?

**Comment by XuHuaiyu** [comment]
@winoros X86 uses v6.1, the bug code does not exist.
ARM uses v6.5.

**Comment by winoros** [comment]
> @winoros X86 uses v6.1, the bug code does not exist. ARM uses v6.5.

:joy: Reasonable!

**Comment by kennedy8312** [comment]
Regression Analysis
Issue didn't show up v6.1.6+x86 but v6.5.3+arm.
