### ISSUE TITLE
Support pushdown `lower` to TiKV

### ISSUE THREAD

**Issue by windtalker** [pingcap/tidb#48170]

**Comment by YangKeao** [comment]
This issue reminds me of an existing bug: https://github.com/pingcap/tidb/issues/32513#issuecomment-1687336019 :facepalm: . Maybe it's a good time to refine the implementation on both `tikv` and `tidb` side. The key is to provide different implementation of `lower/upper` for different collations. For example, the `utf8mb4_bin` collation should use Unicode 4.0 and `utf8mb4_0900_ai_ci` should use Unicode 9.0.

As for the implementation, the standard library for both rust and golang use a data structure to represent the segment of lower/upper shift of the original character. The MySQL just hard codes a big map from every characters to its lower and upper. See [`my_tolower_utf8mb4`](https://github.com/mysql/mysql-server/blob/19feac3674e2ae254b3e7fa7e116fc64ac284d8d/strings/ctype-utf8.cc#L7278C20-L7278C38) and [`uca900_data.h`](https://raw.githubusercontent.com/mysql/mysql-server/8.0/strings/uca900_data.h). IMO, both are fine. Maybe the MySQL way is much simpler to generate codes :laughing: .

If you are willing to provide a correct implementation on TiKV side, I'll help on fixing this issue (#32513) on TiDB :handshake: . Thanks.

**Comment by gengliqi** [comment]
> This issue reminds me of an existing bug: [#32513 (comment)](https://github.com/pingcap/tidb/issues/32513#issuecomment-1687336019) 🤦 . Maybe it's a good time to refine the implementation on both `tikv` and `tidb` side. The key is to provide different implementation of `lower/upper` for different collations. For example, the `utf8mb4_bin` collation should use Unicode 4.0 and `utf8mb4_0900_ai_ci` should use Unicode 9.0.
> 
> As for the implementation, the standard library for both rust and golang use a data structure to represent the segment of lower/upper shift of the original character. The MySQL just hard codes a big map from every characters to its lower and upper. See [`my_tolower_utf8mb4`](https://github.com/mysql/mysql-server/blob/19feac3674e2ae254b3e7fa7e116fc64ac284d8d/strings/ctype-utf8.cc#L7278C20-L7278C38) and [`uca900_data.h`](https://raw.githubusercontent.com/mysql/mysql-server/8.0/strings/uca900_data.h). IMO, both are fine. Maybe the MySQL way is much simpler to generate codes 😆 .
> 
> If you are willing to provide a correct implementation on TiKV side, I'll help on fixing this issue (#32513) on TiDB 🤝 . Thanks. (Or if this issue is somehow urgent, it's also fine to just ignore #32513 and just use the standard library, because only a little part of characters will be affected by this issue, and I'll try to fix it later.)

The behavior of `upper` and `lower` between rust standard library and go standard library is different. See details here https://github.com/tikv/tikv/issues/16159. I fixed it by porting the implementation of go standard library into rust. By the way, TiFlash also chose to port the implementation but I found a bug which I will fix soon https://github.com/pingcap/tiflash/issues/8484. So the result of `lower` and `upper` should remain the same on TiDB, TiKV, and TiFlash. Back to the issue you mentioned, I think we can fix it if we have time.
