### ISSUE TITLE
flaky test TestSupportedSuffixForServerDisk

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#48225]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```
     import_test.go:372: 
        	Error Trace:	pkg/executor/importer/import_test.go:372
        	Error:      	Target error should be in err chain:
        	            	expected: "[executor:8160]Failed to read source files. Reason: %s. %s"
        	            	in chain: 
        	Test:       	TestSupportedSuffixForServerDisk 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/48222/tiprow_fast_test/1719969333586694144#1:build-log.txt%3A1226

**Comment by D3Hunter** [comment]
seems not flaky, unit-test pass it, seems caused by environment, this test read a file with `0o000` permission

**Comment by D3Hunter** [comment]
![da38fcd7-b1d3-41cf-bfc6-16db618ec053](https://github.com/pingcap/tidb/assets/3312245/ee1a5820-99b8-4398-baa4-698a8443ea38)
the environment may not have filesystem permission check

**Comment by hawkingrei** [comment]
> ![da38fcd7-b1d3-41cf-bfc6-16db618ec053](https://user-images.githubusercontent.com/3312245/279914362-ee1a5820-99b8-4398-baa4-698a8443ea38.jpeg) the environment may not have filesystem permission check


File with 000 permission can be read / written by root. Now with RBE, it runs in the root.
