### ISSUE TITLE
set session character_set_results = NULL has errors in log

### ISSUE THREAD

**Issue by darren** [pingcap/tidb#4837]
1. What did you do?

This is also  a small compatibility issue.

This statement is from mysql jdbc driver for mysql:

```sql
set session character_set_results = NULL ;
```

2. What did you expect to see?

There should be no error.

3. What did you see instead?

the sql statement itself is ok
```sql
TiDB-Server [(none)]> set session character_set_results = NULL ;
Query OK, 0 rows affected (0.00 sec)
```

but there's error in the log:

```log
2017/10/20 10:33:07.796 terror.go:342: [error] /go/src/github.com/pingcap/tidb/util/types/datum.go:1478: cannot convert <nil>(type <nil>) to string
/go/src/github.com/pingcap/tidb/executor/set.go:150: 
2017/10/20 10:33:07.796 set.go:151: [info] [216] set system variable character_set_results = 
```

4. What version of TiDB are you using (`tidb-server -V`)?

Release Version: 1.0.0
Git Commit Hash: 21c21973c092e3e192c0210933448d7b394e74cb
Git Branch: master
UTC Build Time: 2017-10-17 01:35:28

**Comment by shenli** [comment]
@Darren Thanks!

**Comment by morgo** [comment]
I can confirm that in the current version there is no longer an error in the logs:
```
2018/12/10 11:03:19.098 domain.go:532: [info] [ddl] on DDL change, must reload



2018/12/10 11:05:39.966 set.go:180: [info] con:3 character_set_results=NULL
2018/12/10 11:05:43.834 set.go:180: [info] con:3 character_set_results=NULL
2018/12/10 11:05:47.782 domain.go:762: [info] [domain] reload privilege success.


2018/12/10 11:06:27.593 set.go:180: [info] con:3 character_set_results=NULL
```

I am going to close this issue now, but feel free to re-open if you have any additional questions.  Thanks!
