### ISSUE TITLE
oom when global sort import with gcs

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#48420]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
import with 2 16g32g nodes using global sort on gcs, tidb oom during write&ingest phase
gcs-sdk is using http2 which don't have any limit on read buffer, it keeps accumulating data if not read fast enough(http2 has flow control although), in local test each reader might accumulate several MiB data.

https://github.com/golang/net/blob/a720b30cbc2733d7b4daaab7a8cac65f3ff5131d/http2/transport.go#L2275

![img_v3_024v_625621fd-948b-4940-9abf-2b3a325ff87g](https://github.com/pingcap/tidb/assets/3312245/e9b5de72-7ed1-4d64-b49b-29916aad4752)
[heap0-4.pprof.tar.gz](https://github.com/pingcap/tidb/files/13294514/heap0-4.pprof.tar.gz)

**Comment by aytrack** [comment]
duplicate with #48384
