### ISSUE TITLE
check pd or pump status at bootstrap stage

### ISSUE THREAD

**Issue by LinuxGit** [pingcap/tidb#4848]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
While starting tidb service, if pd or pump is not ready, tidb should retry at bootstrap stage until pd and pump up, then tidb can listen on 4000 port and provide service. Maybe we need a policy. eg: tidb should exit after 10 minutes timeout.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V`)?

**Comment by shenli** [comment]
Yes, this is the right way.

**Comment by tiancaiamao** [comment]
I think it's acceptable for the current behavior of TiDB: exit if it can't work...

> tidb should exit after 10 minutes timeout

That's more cumbersome, you don't know whether it works or not, even it's "up".

**Comment by coocood** [comment]
@tiancaiamao 
It would be convenient If we can start PD, TiKV, TiDB and Pump at the same time.
When everything is ready, tidb-server open the 4000 port to serve requests.

**Comment by LinuxGit** [comment]
When we use systemd to manage TiDB, PD or Pump services and enable service to start on boot, it would be convenient and more safe.
