### ISSUE TITLE
Spilling for paralleled Sort make executor respond to the kill message slowly

### ISSUE THREAD

**Issue by solotzg** [pingcap/tidb#48515]
## Enhancement

Set `tidb_mem_quota_query` to a large value(like `20GB`) and make query trigger Spilling for paralleled Sort. The operation of sorting the partitions before writing to the disk takes too long, resulting in the inability to respond to the kill signal in time.

In TiDB v6.5.2:

![image](https://github.com/pingcap/tidb/assets/9016847/c18971c2-6335-4a11-81c8-383b8be0cfd1)
![image](https://github.com/pingcap/tidb/assets/9016847/0c11ccb0-b393-4d46-b995-ab591406dbc3)

**Comment by XuHuaiyu** [comment]
fixed by https://github.com/pingcap/tidb/pull/50510
