### ISSUE TITLE
update the mysql.stats_meta when lightning finishes without trigger analyze

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#48562]
## Enhancement

Currently, it's possible that the tidb-lightning finishes its import task without triggering the analyze jobs. At that time, the mysql.stats_meta will think each table's row count is 0 after the importing finishes. The side effect is that the auto analyze won't be triggered for these tables since TiDB thinks its row count is 0.

So it's better to modify the table `mysql.stats_meta` after the import task is finished without triggering analyze jobs by the following SQL:
```
update mysq.stats_meta where table_id = ? set modify_count = current_count, row_count = current_count, version = current txn timestamp
```

**Comment by lance6716** [comment]
@winoros In some configurations lightning will not know `current_count`, can I use an inaccurate value as `current_count`? like 100,000,000
