### ISSUE TITLE
[global sort] global sort s3 dir data does not clean 

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#48572]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy some cluster to use global sort import data or add index
2. set the `tidb_cloud_storage_uri` to s3
3. thre are import and add index jobs failed or success

### 2. What did you expect to see? (Required)
whether the jobs failed or success, the s3 global sort dir should be clean 
### 3. What did you see instead (Required)
there are some data not clean
### 4. What is your TiDB version? (Required)
master, v7.5.0

**Comment by ywqzzy** [comment]
Have no environment to triage the problem, and the cleanup logic is doomed to run.

**Comment by ywqzzy** [comment]
If the tidb cluster is suspended or cleared during global sort or right after global sort, still have possibility not cleanup s3 dir data. But we will have no way to clean the data without a tidb cluster.
