### ISSUE TITLE
global sort data-dir required privileges are not clear

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#48580]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. give the `AllObjectActions` , `ListObjectsInBucket`, `GetBucketLocation` to the tidb node 
2. import data from the s3 uri

### 2. What did you expect to see? (Required)
set `tidb_cloud_storage_uri` success but import data will failed with 403
### 3. What did you see instead (Required)
set `tidb_cloud_storage_uri`  success
import data success
### 4. What is your TiDB version? (Required)
master 
v7.5.0

**Comment by D3Hunter** [comment]
test with below bucket policy of which principal is removed, it works, but please give your bucket policy and the result of `aws sts get-caller-identity` on client side, i think there might be something wrong with your principal config

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "S3ConsoleAccess",
            "Effect": "Allow",
            "Principal": {},
            "Action": "s3:GetBucketLocation",
            "Resource": "arn:aws:s3:::my-bucket"
        },
        {
            "Sid": "ListObjectsInBucket",
            "Effect": "Allow",
            "Principal": {},
            "Action": "s3:ListBucket",
            "Resource": "arn:aws:s3:::my-bucket"
        },
        {
            "Sid": "AllObjectActions",
            "Effect": "Allow",
            "Principal": {},
            "Action": "s3:*Object",
            "Resource": "arn:aws:s3:::my-bucket/*"
        }
    ]
}
```

**Comment by D3Hunter** [comment]
closing
