### ISSUE TITLE
add index aborted while not enough sort-dir capacity

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#48586]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a v7.5.0 cluster 
2. the temp-dir have  a low capacity
3. create table and add index

### 2. What did you expect to see? (Required)
according to the doc add index should be run success .
> Index acceleration requires a [temp-dir](https://docs.pingcap.com/tidb/v7.4/tidb-configuration-file#temp-dir-new-in-v630) that is writable and has enough free space. If the temp-dir is unusable, TiDB falls back to non-accelerated index building. It is recommended to put the temp-dir on a SSD disk.

add index success while there are a low capacity temp-dir 
### 3. What did you see instead (Required)
report error 
```sql
[16:10:07]TiDB root:test> alter table t add index idx_b(b);
(8256, 'Check ingest environment failed: sort path: /tmp/tidb/tmp_ddl-4000, disk usage: 445323239424/494384795648, backend usage: 0, please clean up the disk and retry')
```
### 4. What is your TiDB version? (Required)
```sql
[16:10:40]TiDB root:test> select tidb_version();
+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v7.5.0                                   |
| Edition: Community                                        |
| Git Commit Hash: 700beafa79844b7b48dcba1c452ea3ff49d8f271 |
| Git Branch: heads/refs/tags/v7.5.0                        |
| UTC Build Time: 2023-11-10 14:38:24                       |
| GoVersion: go1.21.3                                       |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+
1 row in set
```

**Comment by ywqzzy** [comment]
Not a bug but a feature.

**Comment by D3Hunter** [comment]
need update doc
