### ISSUE TITLE
add index rollback and import into failed when failure one tidb or tidb rolling restart with global sort

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48633]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run workload
2、add index for one table or run import into
3、failure one tidb or tidb rolling restart

### 2. What did you expect to see? (Required)
add index or import into can success

### 3. What did you see instead (Required)
add index rollback and import into failed when failure one tidb or tidb rolling restart 

add index：
the status of ddl job is not synced or running (now: 2023-11-15 21:35:45, jobId: 425, job type: add index /* ingest cloud */, state: rollback done)
operatorLogs:
[2023-11-15 21:34:15] ###### start adding index
alter table sbtest1 add index index_test_1700055255114 (c)
[2023-11-15 21:34:15] ###### wait for ddl job finish
[2023-11-15 21:35:45] ###### wait for import job to finish failed
select job_id, job_type, state from information_schema.ddl_jobs where query = 'alter table sbtest1 add index index_test_1700055255114 (c)'
jobId: 425, job type: add index /* ingest cloud */, state: rollback done"

import into：
the status of ddl job is not synced or running (now: 2023-11-15 21:35:45, jobId: 425, job type: add index /* ingest cloud */, state: rollback done)
operatorLogs:
[2023-11-15 21:34:15] ###### start adding index
alter table sbtest1 add index index_test_1700055255114 (c)
[2023-11-15 21:34:15] ###### wait for ddl job finish
[2023-11-15 21:35:45] ###### wait for import job to finish failed
select job_id, job_type, state from information_schema.ddl_jobs where query = 'alter table sbtest1 add index index_test_1700055255114 (c)'
jobId: 425, job type: add index /* ingest cloud */, state: rollback done

### 4. What is your TiDB version? (Required)
git hash：151b5b1df9d595bf0b568ff82f2ea2e13ae3eddb

**Comment by D3Hunter** [comment]
duplicate with #48635
