### ISSUE TITLE
Run syncer with Aliyun RDS failed.

### ISSUE THREAD

**Issue by decker502** [pingcap/tidb#4865]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
按文档测试syner导入数据，源数据库为阿里云RDS

2. What did you expect to see?
导入数据成功

3. What did you see instead?
导入失败，日志如下
2017/10/23 12:30:03 syncer.go:591: [info] [query]/* rds internal mark */ grant PROCESS,usage, REPLICATION SLAVE, REPLICATION CLIENT  on *.* to 'xxxxxxxxxx'@'%' identified by password '*xxxxxxxxxxxxxxxxxxxxxxxxxxxx' with max_user_connections 0 [pos](mysql-bin.001723, 737295) [next pos](mysql-bin.001723, 737589) [gtid_next]7c3f79ac-652f-11e6-a6ab-6c92bf2c16c1:1-4632346
2017/10/23 12:30:03 syncer.go:849: [info] flush all jobs meta = syncer-binlog = (mysql-bin.001723, 732065), syncer-binlog-gtid = 7c3f79ac-652f-11e6-a6ab-6c92bf2c16c1:1-4632324
2017/10/23 12:30:03 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001723 binlog-pos:732065 binlog-gtid:7c3f79ac-652f-11e6-a6ab-6c92bf2c16c1:1-4632324
2017/10/23 12:30:03 main.go:75: [error] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/ddl.go:30: error while parsing sql: /* rds internal mark */ grant PROCESS,usage, REPLICATION SLAVE, REPLICATION CLIENT  on *.* to 'xxxxxxxxxx'@'%' identified by password '*xxxxxxxxxxxxxxxxxxxxxxxxxxx' with max_user_connections 0, err:line 0 column 43 near ", REPLICATION SLAVE, REPLICATION CLIENT  on *.* to 'xxxxxxxxx'@'%' identified by password '*xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' with max_user_connections 0" (total length 202)

4. What version of TiDB are you using (`tidb-server -V`)?

tidb-server -1.0

**Comment by coocood** [comment]
@decker502 
Thank you for your report.

@tiancaiamao 
We should support `with max_user_connections` option
https://dev.mysql.com/doc/refman/5.7/en/grant.html

**Comment by shenli** [comment]
@decker502 We are developing a tool to synchronize data from Aliyun RDS to TiDB. It will be released soon.
/cc @iamxy  PTAL

**Comment by decker502** [comment]
@coocood 
配置文件中添加这样的选项，没起作用，是配置不对吗？
skip-sqls = ["ALTER USER", "CREATE USER", "GRANT"]

**Comment by decker502** [comment]
@shenli 有大概时间点吗

**Comment by holys** [comment]
@decker502  rds 这条 binlog 多了前面的注释，不妨试试 `skip-sqls = ["ALTER USER", "CREATE USER", "/* rds internal mark */ grant"]`

**Comment by tiancaiamao** [comment]
parse解析的时候出错了，有可能走不到过滤的逻辑那里。@holys
今明天之内吧，可能关注下这个issue。@decker502

**Comment by holys** [comment]
@tiancaiamao  解析失败了，会尝试去过滤的。只是目前过滤规则比较简陋，我上面提到的 规则应该可以工作。 
@decker502   可以先试试，有问题可以随时反馈下。谢谢

**Comment by decker502** [comment]
@tiancaiamao 按 @holys 的方法，同步成功了，谢谢

**Comment by decker502** [comment]
@tiancaiamao 请问阿里RDS的同步工具进展如何了

**Comment by holys** [comment]
@tiancaiamao  Can we support all the privilege keywords in parser ? 

The following statement still can't be parsed:

```
 /* rds internal mark */ GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, RELOAD, PROCESS, INDEX, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES,      EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT,      TRIGGER on *.* to 'root2'@'%' identified by password '*sdsadsdsadssadsadsadsadsada' with grant option
```

**Comment by tiancaiamao** [comment]
```
RELOAD
CREATE TEMPORARY TABLES
LOCK TABLES
CREATE VIEW
SHOW VIEW
CREATE ROUTINE
ALTER ROUTINE
EVENT
```

Those privileges are still not parsed, I'll make another PR. @holys

**Comment by decker502** [comment]
@shenli @tiancaiamao RDS的同步工具可用了吗？考虑将tidb用在生产环境了，数据在RDS上，希望能用上这个工具

**Comment by holys** [comment]
@decker502  It's not recommended to use syncer to sync data from aliyun RDS because RDS would purge binlog very soon, and we are developing a new enterprise tool  which handle it well. If you are interested, please feel free to contact me  via `chendahui#pingcap.com` (replace # with @).
Best regards.
