### ISSUE TITLE
br: Error: [ddl:1069]Too many keys specified; max 64 keys allowed

### ISSUE THREAD

**Issue by qybf** [pingcap/tidb#48664]
My TiDB version is v6.5.3. When I try to restore a full backup from S3 to a new TiDB database using BR, I encounter an error. The error message is as follows: 

"Error: [ddl:1069]Too many keys specified; max 64 keys allowed."

I have already configured `index-limit = 512`, but I still encounter the error. How can I verify if the `index-limit` value in my database is indeed set to 512?

**Comment by BornChanger** [comment]
@qybf , the problem is already fixed in version 6.5.4 via issue https://github.com/pingcap/tidb/issues/45793.
