### ISSUE TITLE
Commit 87107b causes 1.5% - 2% performance regression in ycsb workloadc

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#48667]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy  a cluster and run ycsb workloadc

### 2. What did you expect to see? (Required)
No performance regression

### 3. What did you see instead (Required)
Compared with the last commit, commit 87107b causes 1.5% - 2% performance regression in ycsb-workloadc.
![image](https://github.com/pingcap/tidb/assets/84501897/3d52b068-dd98-4fce-8dd1-61bbe871d5a0)

### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/pull/48447

**Comment by tiancaiamao** [comment]
Now I figure out why!

![image](https://github.com/pingcap/tidb/assets/1420062/3cc38498-9f5a-4050-8d65-67b7fe7b6bc4)
After the bug fix, we **close the tidbResultSet and then reply to the client**.

![image](https://github.com/pingcap/tidb/assets/1420062/1369a5ab-92a2-4b55-bb59-fe2c8867c238)
Before the fix, **we reply to the client first, and then close tidbResultSet in terror.Call**.

The difference is that in the past we reply the result as soon as possible, and delay the Close operation (this cause the bug that if Close return error, the client can not know it).
Close tidbResultSet take time and this is where the 1.5%-2% regression come from.
