### ISSUE TITLE
crc32Checksum is inconsistency after import into finished which was injected ddl owner network partition

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48701]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run import into
2、 inject ddl owner network partition

case config：
tag: "ha-test-import-into"
cases:
- name: "ha_tidb(ddl-owner)_to_all_network_partition"
warmUpTime: 1m
faultType: network_partition
selector: "tidb(ddl-owner)_to_all"
period: "https://github.com/every 5m"
faultDuration: 3m
faultTotalRunTime: 30m
importInto:
- db: "importtest"
schema: "CREATE TABLE user_data1 (
uid bigint(20) unsigned NOT NULL AUTO_INCREMENT,
data mediumblob NOT NULL,
update_data blob NOT NULL,
create_time datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
update_time datetime DEFAULT NULL,
PRIMARY KEY (uid) /*T![clustered_index] CLUSTERED /,
KEY k_1 (update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=5850196;"
cmd: "import into user_data1 from 's3://qe-testing/brie/lightning-mhy-100G-csv/sysbench.user_data1.000001.csv?access-key=xxx\u0026secret-access-key=xxx\u0026endpoint=xxx\u0026force-path-style=false\u0026region=xxx\u0026provider=xxx' WITH DETACHED,thread=8,skip_rows=1"
timeout: 120m
crc32Checksum: 3582177512

### 2. What did you expect to see? (Required)
crc32Checksum is consistency

### 3. What did you see instead (Required)
crc32Checksum is inconsistency after import into finished which was injected ddl owner network partition

operatorLogs:
[2023-11-15 22:51:28] ###### start import into
import into user_data1 from 's3://qe-testing/brie/lightning-mhy-100G-csv/sysbench.user_data1.000001*.csv?access-key=xxx&secret-access-key=xxx&endpoint=xxx&force-path-style=false&region=xxx&provider=xxx' WITH DETACHED,thread=8,skip_rows=1
[2023-11-15 22:51:28] ###### wait for import job to finish
[2023-11-15 23:13:08] ###### import job finished
select id, step, status from mysql.tidb_import_jobs where start_time >= '2023-11-15 22:51:28'
jobId: 60005, step: , status: finished
import done, it takes: 21m40.447941577s

[2023/11/15 23:23:01.405 +08:00] [INFO] [client.go:826] ["Get table checksum"] [database=importtest] [table=user_data1] ["table crc32 checksum"=244735121]
ImportIntoConsistencyCheck failed: user_data1 expected cCrc32Checksum is 3582177512, the actual is 244735121

### 4. What is your TiDB version? (Required)
git hash：151b5b1df9d595bf0b568ff82f2ea2e13ae3eddb

**Comment by Benjamin2037** [comment]
fixed by https://github.com/pingcap/tidb/pull/48660

**Comment by Lily2025** [comment]
<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px;">one subtask is skipped(run but finished immediately), here is the timeline</p>
  | Tidb 0 | Tidb 1
-- | -- | --
22:51:29 | dispatcher generate encode&sort subtask |  
22:51:30 | Got 60035 and run | Got 60036 and run
22:53:25 |   | Dispatcher start
22:53:32 |   | Move 60035 to me Task state is set to pending
22:54:11 | Dispatcher exit |  
22:55:38 | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel There're many pd errors during this time range |  
23:01:21 | Dispatcher start |  
23:01:30 | Move 60035 and 60036 to me |  
23:01:30 | Run 60035 |  
23:01:31 |   | Dispatcher exit
23:03:28 |   | 60036 finished (we didn't check exec-id when updated, and set state directly.
23:03:42 |   | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel
23:09:17 |   | Dispatcher start
23:09:38 |   | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel Still logging [scheduler.go:108] ["scheduler canceled"]，and many [ERROR] [pd.go:236] ["updateTS error"] [txnScope=global] [error="context canceled"] errors in between GetFirstSubtaskInStates didn't use ctx of scheduler, so it cannot see it being cancelled. The scheduler run loop must be blocked on GetFirstSubtaskInStates.
23:09:40 |   | Move 60035 to me
23:09:40 |   | Run 60035
23:09:41 |   | Finish 60035 Since scheduler runCtx is cancelled, workers in WorkerPool all exist, and AsyncOperator.Wait don't return error. So the subtask just finished without error.
23:09:41 |   | dispatcher skip merge-sort Start generate write&ingest subtask
23:11:39 | Dispatcher exit |  
23:12:36 | Finish 60035 This place didn't check state of subtask, so it will update too.


<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px;">one subtask is skipped(run but finished immediately), here is the timeline</p><table role="table" style="box-sizing: border-box; border-spacing: 0px; border-collapse: collapse; margin-top: 0px; margin-bottom: 0px !important; display: block; width: max-content; max-width: 100%; overflow: auto;"><thead style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><th style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--borderColor-default, var(--color-border-default));"></th><th style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--borderColor-default, var(--color-border-default));">Tidb 0</th><th style="box-sizing: border-box; padding: 6px 13px; font-weight: var(--base-text-weight-semibold, 600); border: 1px solid var(--borderColor-default, var(--color-border-default));">Tidb 1</th></tr></thead><tbody style="box-sizing: border-box;"><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">22:51:29</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">dispatcher generate encode&amp;sort subtask</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">22:51:30</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Got 60035 and run</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Got 60036 and run</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">22:53:25</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Dispatcher start</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">22:53:32</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Move 60035 to me Task state is set to pending</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">22:54:11</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Dispatcher exit</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">22:55:38</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel There're many pd errors during this time range</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:01:21</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Dispatcher start</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:01:30</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Move 60035 and 60036 to me</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:01:30</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Run 60035</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:01:31</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Dispatcher exit</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:03:28</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">60036 finished (we didn't check exec-id when updated, and set state directly.</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:03:42</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:09:17</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Dispatcher start</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:09:38</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel Still logging [scheduler.go:108] ["scheduler canceled"]，and many [ERROR] [pd.go:236] ["updateTS error"] [txnScope=global] [error="context canceled"] errors in between GetFirstSubtaskInStates didn't use ctx of scheduler, so it cannot see it being cancelled. The scheduler run loop must be blocked on GetFirstSubtaskInStates.</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:09:40</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Move 60035 to me</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:09:40</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Run 60035</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:09:41</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Finish 60035 Since scheduler runCtx is cancelled, workers in WorkerPool all exist, and AsyncOperator.Wait don't return error. So the subtask just finished without error.</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:09:41</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">dispatcher skip merge-sort Start generate write&amp;ingest subtask</td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-default, var(--color-canvas-default)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">23:11:39</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));">Dispatcher exit</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default));"></td></tr><tr style="box-sizing: border-box; background-color: var(--bgColor-muted, var(--color-canvas-subtle)); border-top: 1px solid var(--borderColor-muted, var(--color-border-muted));"><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default)); color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">23:12:36</td><td style="box-sizing: border-box; padding: 6px 13px; border: 1px solid var(--borderColor-default, var(--color-border-default)); color: rgb(31, 35, 40); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Finish 60035 This place didn't check state of subtask, so it will update too.</td><br class="Apple-interchange-newline">
</body>
</html>

**Comment by Lily2025** [comment]
one subtask is skipped(run but finished immediately), here is the timeline
<html>
<body>




22:51:29 | dispatcher generate encode&sort subtask |  
22:51:30 | Got 60035 and run | Got 60036 and run
22:53:25 |   | Dispatcher start
22:53:32 |   | Move 60035 to me Task state is set to pending
22:54:11 | Dispatcher exit |  
22:55:38 | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel There're many pd errors during this time range |  
23:01:21 | Dispatcher start |  
23:01:30 | Move 60035 and 60036 to me |  
23:01:30 | Run 60035 |  
23:01:31 |   | Dispatcher exit
23:03:28 |   | 60036 finished (we didn't check exec-id when updated, and set state directly.
23:03:42 |   | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel
23:09:17 |   | Dispatcher start
23:09:38 |   | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel Still logging [scheduler.go:108] ["scheduler canceled"]，and many [ERROR] [pd.go:236] ["updateTS error"] [txnScope=global] [error="context canceled"] errors in between GetFirstSubtaskInStates didn't use ctx of scheduler, so it cannot see it being cancelled. The scheduler run loop must be blocked on GetFirstSubtaskInStates.
23:09:40 |   | Move 60035 to me
23:09:40 |   | Run 60035
23:09:41 |   | Finish 60035 Since scheduler runCtx is cancelled, workers in WorkerPool all exist, and AsyncOperator.Wait don't return error. So the subtask just finished without error.
23:09:41 |   | dispatcher skip merge-sort Start generate write&ingest subtask
23:11:39 | Dispatcher exit |  
23:12:36 | Finish 60035 This place didn't check state of subtask, so it will update too.

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by Lily2025** [comment]
one subtask is skipped(run but finished immediately), here is the timeline
|  | Tidb 0 | Tidb 1 |
| --- | --- | --- |
| 22:51:29 | dispatcher generate encode&sort subtask |  |
| 22:51:30 | Got 60035 and run | Got 60036 and run |
| 22:53:25 |  | Dispatcher start |
| 22:53:32 |  | Move 60035 to me Task state is set to pending |
| 22:54:11 | Dispatcher exit |  |
| 22:55:38 | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel  There're many pd errors during this time range |  |
| 23:01:21 | Dispatcher start |  |
| 23:01:30 | Move 60035 and 60036 to me  |  |
| 23:01:30 | Run 60035 |  |
| 23:01:31 |  | Dispatcher exit |
| 23:03:28 |  | 60036 finished (we didn't check exec-id when updated, and set state directly. |
| 23:03:42 |  | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel  |
| 23:09:17 |  | Dispatcher start |
| 23:09:38 |  | Scheduler cancel check routine noticed that all the subtask of it is gone, so call cancel  Still logging [scheduler.go:108] ["scheduler canceled"]，and many [ERROR] [pd.go:236] ["updateTS error"] [txnScope=global] [error="context canceled"] errors in between GetFirstSubtaskInStates didn't use ctx of scheduler, so it cannot see it being cancelled. The scheduler run loop must be blocked on GetFirstSubtaskInStates. |
| 23:09:40 |  | Move 60035 to me |
| 23:09:40 |  | Run 60035 |
| 23:09:41 |  | Finish 60035 Since scheduler runCtx is cancelled, workers in WorkerPool all exist, and AsyncOperator.Wait don't return error. So the subtask just finished without error. |
| 23:09:41 |  | dispatcher skip merge-sort Start generate write&ingest  subtask |
| 23:11:39 | Dispatcher exit |  |
| 23:12:36 | Finish 60035 This place didn't check state of subtask, so it will update too. |  |
