### ISSUE TITLE
 types.DecimalDiv has a bug if the format of arg "from2" like "0.0xxx"

### ISSUE THREAD

**Issue by hanjm** [pingcap/tidb#4873]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
using types.MyDecimal
```
package main

import (
	"fmt"
	"github.com/pingcap/tidb/util/types"
)

func main() {
	cD := &types.MyDecimal{}
	cD.FromString([]byte("51"))
	rD := &types.MyDecimal{}
	rD.FromString([]byte("0.003430"))
	result := &types.MyDecimal{}
	err := types.DecimalDiv(cD, rD, result, 6)
	if err != nil {
		fmt.Printf("DecimalDiv err:%s", err)
		return
	}
	fmt.Printf("%v", result)
}
```
2. What did you expect to see?

expected 14868.804665
3. What did you see instead?
but 14868.000000
4. What version of TiDB are you using (`tidb-server -V`)?
git-master

**Comment by shenli** [comment]
@hanjm Thanks for your feedback!
Would you mind send us a PR to fix this?

**Comment by hanjm** [comment]
**"select 51/0.003430;" output diffrent between tidb-1.0.0 and mysql5.7.**

$ /usr/local/bin/mysql -h 127.0.0.1 -P 4000 -u root
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.1-TiDB-1.0.0 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select 51/0.003430;
+-------------+
| 51/0.003430 |
+-------------+
|  14868.0000 |
+-------------+
1 row in set (0.00 sec)

---
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1307
Server version: 5.7.19 Homebrew

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select 51/0.003430;
+-------------+
| 51/0.003430 |
+-------------+
|  14868.8047 |
+-------------+
1 row in set (0.00 sec)
