### ISSUE TITLE
lightning: the schema of the imported data contains foreign key constraints

### ISSUE THREAD

**Issue by 7yyo** [pingcap/tidb#48730]
## Feature Request

**Is your feature request related to a problem? Please describe:**

If the data exported by dumpling contains foreign keys, when using lightning to import, it is easy to cause the import task to fail because the schema creation does not comply with the order of foreign key constraints.

If there are many such data tables, manually sorting out foreign key relationships is very time-consuming.

Hope we can consider improving this scenario. 

**Describe the feature you'd like:**

Ability to organize table relationships

**Describe alternatives you've considered:**

1. Delete foreign key constraints
2. Users organize foreign key relationships and create table structures themselves

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
Can you provide the log? We already use session variable "foreign_key_checks" to disbale it

**Comment by 7yyo** [comment]
> Can you provide the log? We already use session variable "foreign_key_checks" to disbale it

[2023/11/17 20:48:23.509 +08:00] [ERROR] [main.go:103] ["tidb lightning encountered error stack info"] [error="[Lightning:Restore:ErrCreateSchema]create schema failed, table: `cnhtc`.`tm_bu_dealer`, stmt: restore table schema: run create schema job failed: Error 3780 (HY000): Referencing column 'DEALER_ID' and referenced column 'DEALER_ID' in foreign key constraint 'FK_Reference_67' are incompatible."]

**Comment by lance6716** [comment]
> > Can you provide the log? We already use session variable "foreign_key_checks" to disbale it
> 
> [2023/11/17 20:48:23.509 +08:00] [ERROR] [main.go:103] ["tidb lightning encountered error stack info"] [error="[Lightning:Restore:ErrCreateSchema]create schema failed, table: `cnhtc`.`tm_bu_dealer`, stmt: restore table schema: run create schema job failed: Error 3780 (HY000): Referencing column 'DEALER_ID' and referenced column 'DEALER_ID' in foreign key constraint 'FK_Reference_67' are incompatible."]

I mean the full log
