### ISSUE TITLE
TiDB variable of new session doesn't inherit from global variable.

### ISSUE THREAD

**Issue by jansu-dev** [pingcap/tidb#48803]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```shell
tiup playground v6.1.5 --db 1 --kv 1 --tiflash 0 --pd 1
......
🎉 TiDB Playground Cluster is started, enjoy!

Connect TiDB:    mysql --comments --host 127.0.0.1 --port 4000 -u root
TiDB Dashboard:  http://127.0.0.1:59344/dashboard
Grafana:        http://127.0.0.1:59401

 mysql --comments --host 127.0.0.1 --port 4000 -u root -p test

mysql> show variables like 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.00 sec)

mysql> set global wait_timeout = 300000;
Query OK, 0 rows affected (0.02 sec)

mysql> exit

mysql --comments --host 127.0.0.1 --port 4000 -u root -p test

mysql> show variables like 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.00 sec)

mysql> show global variables like 'wait_timeout';
+---------------+--------+
| Variable_name | Value  |
+---------------+--------+
| wait_timeout  | 300000 |
+---------------+--------+
1 row in set (0.01 sec)
```

### 2. What did you expect to see? (Required)

IMO, the new session variable (wait_timeout) should be inherited from global variable, but, it didn't.

```sql
......
mysql> exit

mysql --comments --host 127.0.0.1 --port 4000 -u root -p test

mysql> show variables like 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 300000 |
+---------------+-------+
1 row in set (0.00 sec)
......
```

though, the [doc](https://docs.pingcap.com/tidb/stable/system-variables#system-variables) said : 
1. For variables with the Persists to cluster: Yes setting, when a global variable is changed, a notification is sent to all TiDB servers to refresh their system variable cache. **When you add additional TiDB servers or restart existing TiDB servers, the persisted configuration value is automatically used.**
2. I still think it's incompatible with [MySQL behavior](https://dev.mysql.com/doc/refman/8.0/en/show-variables.html).

### 3. What did you see instead (Required)

```sql
......
mysql> exit

mysql --comments --host 127.0.0.1 --port 4000 -u root -p test

mysql> show variables like 'wait_timeout';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| wait_timeout  | 28800 |
+---------------+-------+
1 row in set (0.00 sec)
......
```

### 4. What is your TiDB version? (Required)

```
mysql> select version();
+--------------------+
| version()          |
+--------------------+
| 5.7.25-TiDB-v6.1.5 |
+--------------------+
1 row in set (0.01 sec)
```

**Comment by mjonss** [comment]
I'm not sure this is a bug, it actually inherits the `@@session.wait_timeout` from `@@global.interactive_timeout`, which is what MySQL does as well.
```
mysql> select @@session.wait_timeout, @@session.interactive_timeout, @@global.wait_timeout, @@global.interactive_timeout;
+------------------------+-------------------------------+-----------------------+------------------------------+
| @@session.wait_timeout | @@session.interactive_timeout | @@global.wait_timeout | @@global.interactive_timeout |
+------------------------+-------------------------------+-----------------------+------------------------------+
|                   3600 |                          3600 |                  7200 |                         3600 |
+------------------------+-------------------------------+-----------------------+------------------------------+
1 row in set (0,00 sec)
```
vs TiDB:
```
tidb> select @@session.wait_timeout, @@session.interactive_timeout, @@global.wait_timeout, @@global.interactive_timeout;
+------------------------+-------------------------------+-----------------------+------------------------------+
| @@session.wait_timeout | @@session.interactive_timeout | @@global.wait_timeout | @@global.interactive_timeout |
+------------------------+-------------------------------+-----------------------+------------------------------+
|                   3600 |                          3600 |                  7200 |                         3600 |
+------------------------+-------------------------------+-----------------------+------------------------------+
1 row in set (0.00 sec)
```

**Comment by mjonss** [comment]
From [MySQL Manual](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout):
On thread startup, the session [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) value is initialized from the global [wait_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_wait_timeout) value or from the global [interactive_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_interactive_timeout) value, depending on the type of client (as defined by the CLIENT_INTERACTIVE connect option to [mysql_real_connect()](https://dev.mysql.com/doc/c-api/8.0/en/mysql-real-connect.html)). See also [interactive_timeout](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_interactive_timeout).

**Comment by jansu-dev** [comment]
ok, @mjonss
thanks for your quick response and help.
we can close it 🤔.
