### ISSUE TITLE
add index rollback to txn-merge when inject ddl owner network partition

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48861]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb_enable_dist_task='on'
1、run workload
2、add index for one table
3、inject network partition between ddl owner and all other pods
case config：
      workloads:
        - type: sysbench
          storage: s3://benchmark/sysbench_64_7000w
          db: sysbench_64_7000w
          tableNum: 64
          tableSize: 70000000
          threads: 64
          subType: oltp_read_write
          ignoreErrors: "all"
      cases:
        - name: "ha_tidb(ddl-owner)_to_all_network_partition"
          warmUpTime: 1m
          faultType: network_partition
          selector: "tidb(ddl-owner)_to_all"
          period: "@every 5m"
          faultDuration: 3m
          faultTotalRunTime: 30m
          ddl:
            addIndex:
              - db: "sysbench_64_7000w"
                table: "sbtest1"
                timeout: 60m
                times: 5
                index_col_name: "c"
                job_type: "ingest"
                admin_check: true
                count_check: false

### 2. What did you expect to see? (Required)
add index finished with ingest

### 3. What did you see instead (Required)
add index rollback to txn-merge

Job Type Check Failed(expected job types: 'ingest', actual job type: 'add index /* txn-merge */')
operatorLogs:
[2023-11-23 23:02:39] ###### start adding index
alter table sbtest1 add index index_test_1700751759798 (c)
[2023-11-23 23:02:39] ###### wait for ddl job finish
[2023-11-23 23:45:47] ###### ddl job finished
select job_id, job_type, state from information_schema.ddl_jobs where query = 'alter table sbtest1 add index index_test_1700751759798 (c)'
jobId: 597, job type: add index /* txn-merge */, state: synced

### 4. What is your TiDB version? (Required)
git hash：2b88d0420608654a20bd16faaf46600e8b7cc837

**Comment by tangenta** [comment]
Duplicated with #46468 and fixed by #48645.
