### ISSUE TITLE
The data returned by the select statement is incorrect

### ISSUE THREAD

**Issue by caicancai** [pingcap/tidb#48860]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `test` (
  `id` varchar(32) NOT NULL,
  UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
INSERT INTO `test` VALUES ('8145308033243873280','8145308033243873281','9145308033243873281');

```

### 2. What did you expect to see? (Required)
<img width="679" alt="捕获" src="https://github.com/pingcap/tidb/assets/77189278/322c14b4-6484-4264-b2c2-fe674897af0c">

<img width="689" alt="捕获1" src="https://github.com/pingcap/tidb/assets/77189278/c52ed9ce-8165-4b36-8fee-e7861d8ea211">

<img width="655" alt="捕获2" src="https://github.com/pingcap/tidb/assets/77189278/898f1ef0-a24e-4c94-a40e-4ddd846ea7e0">

### 4. What is your TiDB version? (Required)
7.x

**Comment by caicancai** [comment]
mysql also has this bug

**Comment by caicancai** [comment]
> ## Bug Report
> Please answer these questions before submitting your issue. Thanks!
> 
> ### 1. Minimal reproduce step (Required)
> ```sql
> CREATE TABLE `test` (
>   `id` varchar(32) NOT NULL,
>   UNIQUE KEY `id` (`id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
> INSERT INTO `test` VALUES ('8145308033243873280','8145308033243873281','9145308033243873281');
> ```
> 
> ### 2. What did you expect to see? (Required)
> <img alt="捕获" width="659" src="https://user-images.githubusercontent.com/77189278/285334705-e3dc40e7-5d2a-43ac-8300-69e2368493f1.PNG"> <img alt="捕获1" width="683" src="https://user-images.githubusercontent.com/77189278/285334719-da104910-9bd3-47b3-8a01-583920076a36.PNG">
> ### 3. What did you see instead (Required)
> ### 4. What is your TiDB version? (Required)

**Comment by caicancai** [comment]
<img width="722" alt="捕获3" src="https://github.com/pingcap/tidb/assets/77189278/9e0bb04a-7eef-410e-9cb0-5451d64f4eba">

Adding quotation marks will not have this problem, and it requires a specific number id to report this error, which can only be said to be a bit metaphysical

**Comment by aytrack** [comment]
caused by cast
```sql
[10:53:45]TiDB root:test> explain select id = 8145308033243873280 from test;
+---------------------+----------+-----------+--------------------------+------------------------------------------------------------------------+
| id                  | estRows  | task      | access object            | operator info                                                          |
+---------------------+----------+-----------+--------------------------+------------------------------------------------------------------------+
| Projection_3        | 10000.00 | root      |                          | eq(cast(test.test.id, double BINARY), 8.145308033243873e+18)->Column#3 |
| └─IndexReader_7     | 10000.00 | root      |                          | index:IndexFullScan_6                                                  |
|   └─IndexFullScan_6 | 10000.00 | cop[tikv] | table:test, index:id(id) | keep order:false, stats:pseudo                                         |
+---------------------+----------+-----------+--------------------------+------------------------------------------------------------------------+
3 rows in set
Time: 0.004s
[10:54:08]TiDB root:test> select cast('8145308033243873281' as double) ;
+---------------------------------------+
| cast('8145308033243873281' as double) |
+---------------------------------------+
| 8.145308033243873e+18                 |
+---------------------------------------+
1 row in set
Time: 0.008s
[10:54:15]TiDB root:test> select cast('8145308033243873280' as double) ;
+---------------------------------------+
| cast('8145308033243873280' as double) |
+---------------------------------------+
| 8.145308033243873e+18                 |
+---------------------------------------+
1 row in set
Time: 0.003s
```

**Comment by caicancai** [comment]
> caused by cast
> 
> ```sql
> [10:53:45]TiDB root:test> explain select id = 8145308033243873280 from test;
> +---------------------+----------+-----------+--------------------------+------------------------------------------------------------------------+
> | id                  | estRows  | task      | access object            | operator info                                                          |
> +---------------------+----------+-----------+--------------------------+------------------------------------------------------------------------+
> | Projection_3        | 10000.00 | root      |                          | eq(cast(test.test.id, double BINARY), 8.145308033243873e+18)->Column#3 |
> | └─IndexReader_7     | 10000.00 | root      |                          | index:IndexFullScan_6                                                  |
> |   └─IndexFullScan_6 | 10000.00 | cop[tikv] | table:test, index:id(id) | keep order:false, stats:pseudo                                         |
> +---------------------+----------+-----------+--------------------------+------------------------------------------------------------------------+
> 3 rows in set
> Time: 0.004s
> [10:54:08]TiDB root:test> select cast('8145308033243873281' as double) ;
> +---------------------------------------+
> | cast('8145308033243873281' as double) |
> +---------------------------------------+
> | 8.145308033243873e+18                 |
> +---------------------------------------+
> 1 row in set
> Time: 0.008s
> [10:54:15]TiDB root:test> select cast('8145308033243873280' as double) ;
> +---------------------------------------+
> | cast('8145308033243873280' as double) |
> +---------------------------------------+
> | 8.145308033243873e+18                 |
> +---------------------------------------+
> 1 row in set
> Time: 0.003s
> ```

Thank you for your reply

**Comment by caicancai** [comment]
![2023-11-29 23-34-45屏幕截图](https://github.com/pingcap/tidb/assets/77189278/c5df46e3-17b9-4f1e-9ba2-84ccc6a8041c)

**Comment by kennedy8312** [comment]
@zanmato1984 Hi, there was a long discussion for this issue on askTUG. https://asktug.com/t/topic/1018754. Could you please help look into this issue?

**Comment by zanmato1984** [comment]
TiDB behaves the same as MySQL (both v5 and v8). It is caused by a well documented implicit conversion rule of MySQL (https://dev.mysql.com/doc/refman/8.0/en/type-conversion.html). So this isn't really a bug. I'm closing it.
