### ISSUE TITLE
add index is always queueing due to task is blocked after tikv rolling restart

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#48904]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
tidb_enable_dist_task='on'
1、run workload
2、add index
3、tikv rolling restart

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index is always queueing due to task is blocked after do some fault test

### 4. What is your TiDB version? (Required)
git hash：8eb191303aca84982479c98407fd4e6bf158dc14

**Comment by Benjamin2037** [comment]
https://github.com/pingcap/tidb/pull/48971

**Comment by tangenta** [comment]
Closed by #50101
