### ISSUE TITLE
Should we keep `EnablePointGetCache` realted codes?

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#48958]
## Enhancement

We can only enable `EnablePointGetCache` by golang code rather than a global variable. And its default value is `false` which means it nerver be used anytime.

The realed global variable is deleted by #36844.  

(Seems https://github.com/pingcap/tidb/pull/36844 is a mistake, maybe we could add it back or totally remove it.

**Comment by Defined2014** [comment]
Seems https://github.com/pingcap/tidb/pull/36844 is a mistake, maybe we could add it back or totally remove it.

**Comment by qw4990** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/51007
