### ISSUE TITLE
Support KEY() based partitioning. 

### ISSUE THREAD

**Issue by cffycls** [pingcap/tidb#49017]
## Enhancement
增加对key()分区的支持

**Comment by bb7133** [comment]
Hi, it has been supported since v7.0: https://docs.pingcap.com/tidb/dev/partitioned-table#key-partitioning

I will close this issue and if you have any further questions, feel free to re-open it.

**Comment by bb7133** [comment]
Also, we suggest using English for all conversations in TiDB community, thanks!
