### ISSUE TITLE
Can tidb be used by other mysql db through federated engine?

### ISSUE THREAD

**Issue by lishichao8333** [pingcap/tidb#4902]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I use federated engine on mysql to query from tidb,and i am sure network availability

2. What did you expect to see?
get the result just like I used federated engine  query from other mysql

3. What did you see instead?
"ERROR 2013 (HY000): Lost connection to MySQL server during query"

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: 1.0.0

**Comment by ngaut** [comment]
Hi @lishichao8333, We haven't test federated engine yet. Could you post the error log of tidb-server?

**Comment by shenli** [comment]
@lishichao8333 Thanks for your feedback!
Could your please provide more detailed info?

**Comment by lishichao8333** [comment]
Sorry,The test environment is recycled,I can not get the log yet.
And the problem has not been revived in the new environment.
Thanks!

**Comment by shenli** [comment]
@lishichao8333 Thanks! 
If you could reproduce this in the future, please feel free to reopen this issue.
