### ISSUE TITLE
tidb will not trigger sync load for some join key

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#49075]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![img_v3_025l_5bcc1d6c-ec47-4b5e-95bf-197e5018482g](https://github.com/pingcap/tidb/assets/15825830/6397ff6d-fe3a-40d3-986c-844a8ce46704)

### 2. What did you expect to see? (Required)
should add join key into neededItem for sync load

### 3. What did you see instead (Required)
no

### 4. What is your TiDB version? (Required)

master

**Comment by hawkingrei** [comment]
The estimation for 'analyzeRowCount' can be based on the row count of other loaded columns. We will not fix this problem.
