### ISSUE TITLE
Will TiDB support Query Cache?

### ISSUE THREAD

**Issue by darren** [pingcap/tidb#4912]
This is MySQL's  query cache https://dev.mysql.com/doc/refman/5.7/en/query-cache.html

MySQL's query cache is not good for all applications like this one http://www.orczhou.com/index.php/2009/08/query-cache-1/

But our application benefits a lot from query cache:

```sql
MariaDB [(none)]> SHOW STATUS LIKE 'Qcache%';
+-------------------------+-----------+
| Variable_name           | Value     |
+-------------------------+-----------+
| Qcache_free_blocks      | 880       |
| Qcache_free_memory      | 14180720  |
| Qcache_hits             | 478930002 |
| Qcache_inserts          | 5241739   |
| Qcache_lowmem_prunes    | 3212331   |
| Qcache_not_cached       | 15667048  |
| Qcache_queries_in_cache | 46474     |
| Qcache_total_blocks     | 175779    |
+-------------------------+-----------+
```

I am expecting to see that TiDB will run faster and faster as you great guys are still making efforts in the query optimizer. 

But for now our application is slower in TiDB as compared to MySQL, we tried adding cache layer using  tools like ProxySQL, but it brings a lot of complexity and still do not figure out how to do cache invalidation.
We are very reluctant to use tools like this,  Simplifying the application layer is one of the reasons we choose TiDB.

I would like to see any thoughts about adding query cache in TiDB.

**Comment by shenli** [comment]
@Darren We already have plan cache now, but not enabled by default.
One of our contributor is working on adding a query cache in TiKV. See: https://github.com/pingcap/tikv/pull/2309

Could you talk more about your application? Are there many aggregations in your query?

**Comment by darren** [comment]
We miss query cache when tidb was not fast enough one year ago, since tidb improves a lot and we don't miss query cache any more. 

Let's close this.
