### ISSUE TITLE
The config warning in instance section should not ignore the invalid setting of other parameter

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#49129]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tiup playground v6.1.0  --db 1 --kv 1 --pd 1 --db.config ./tidb.toml

```
# tidb.toml
tmp-storage-quota = "100G"
[log]
slow-threshold = 300
[performance]
txn-total-size-limit = 1073741824
```
### 2. What did you expect to see? (Required)

tiup playground v6.1.0 --db 1 --kv 1 --pd 1 --db.config ./tidb.toml

```
# tidb.toml
tmp-storage-quota = "100G"
[performance]
txn-total-size-limit = 1073741824
```
As with the above config file, tidb-server will fail to start with the error:
`[FATAL] [terror.go:300] ["unexpected error"] [error="toml: line 1 (last key \"tmp-storage-quota\"): incompatible types: TOML value has type string; destination has type integer"]`

### 3. What did you see instead (Required)
The tidb-server will start successfully, sometimes the later parameter like `txn-total-size-limit` setting is ignored with its default value, depending on the order in which parameters are loaded.

### 4. What is your TiDB version? (Required)
v6.1.0 and above

**Comment by bb7133** [comment]
Fixed by https://github.com/pingcap/tidb/pull/51828.
