### ISSUE TITLE
'like' cause error 'Like needs 2 operands but got 3' with localstore.Driver

### ISSUE THREAD

**Issue by mccxj** [pingcap/tidb#4922]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
use test; 
create table t(name varchar(128)); 
insert into t values('mccxj');
```

localstore.Driver will fail. eg memory,boltdb,goleveldb.
```
./tidb-driver --store=memory
```

2. What did you expect to see?
```
+-------+
| name  |
+-------+
| mccxj |
+-------+
1 row in set (4.19 sec)
```

3. What did you see instead?

```
ERROR 1105 (HY000): [1 [19:3]Like needs 2 operands but got 3]
```

4. What version of TiDB are you using (`tidb-server -V`)?

```
Release Version: 1.0.0
Git Commit Hash: 3dcff496c160ddb08000fa82539b4b02b130ff4c
Git Commit Branch: master
UTC Build Time:  2017-10-23 01:16:01
```

**Comment by mccxj** [comment]
in optimizer.go#67 builder.build(node) origin plan use builtin_like
in optimizer.go#81 doOptimize will call likeToPBExpr, and then call evalLike eval_compare_ops.go#55

evalLike expects two Children, the like expr contains three Children (final children is escape).

**Comment by shenli** [comment]
@mccxj Thanks!
@zz-jason @XuHuaiyu PTAL

**Comment by hanfei1991** [comment]
localstore will be no longer supported.
