### ISSUE TITLE
tableWorker of IndexLookup didn't enable Paging at all

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#49240]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Discover this bug by checking code
1. When build indexReader of IndexLookup, it checked paging flag when build kvReq. [here](https://github.com/pingcap/tidb/blob/master/pkg/executor/distsql.go#L706). So when `@@tidb_enable_paging` is true, indexReader of IndexLooup will use paging protocol.
2. But when build tableReader of IndexLookup, it didn't setup paging flag when build kvReq, check [code](https://github.com/pingcap/tidb/blob/master/pkg/executor/distsql.go#L794), so tableReader of IndexLookup will not use paging protocol.

**Comment by Defined2014** [comment]
The code is introduced by https://github.com/pingcap/tidb/pull/30536.

After disscuss with @you06, it's unnecessary to enable paging for table worker because the workload of `tableReader` in `indexLookUp` is seldom very high.

Close this issue, feel free to reopen it if this affects some issues.
