### ISSUE TITLE
tidb v5.2.2 A normal join sql with join condition returns error "ERROR 8110 (HY000): Cartesian product is unsupported"

### ISSUE THREAD

**Issue by wakaka2019** [pingcap/tidb#49268]
## Bug Report
ERROR 8110 (HY000): Cartesian product is unsupported
Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set collation_connection="utf8mb4_bin";
CREATE TABLE `aaa` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT '自增id',
  `manage_office_name` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'XXXX',
  `XXXX` varchar(64) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT 'XXXX',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=90001 COMMENT='XXXX';

CREATE TABLE `bbb` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键',
  `time_period_key` varchar(64) DEFAULT NULL COMMENT '时间周期',
  `xxxx3` varchar(64) DEFAULT NULL COMMENT 'xxxx',
  `xxxx4` varchar(64) DEFAULT NULL COMMENT 'xxxx',
  `xxxx5` varchar(64) DEFAULT NULL COMMENT 'xxxx',
  `manage_office_name` varchar(64) DEFAULT NULL COMMENT 'xxxx',
 `base_target1` decimal(16,5) DEFAULT NULL COMMENT 'XXXX',
  PRIMARY KEY (`id`) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=152910 COMMENT='XXXX'
### 2. What did you expect to see? (Required)
SQL returns with no errors
### 3. What did you see instead (Required)
 select  time_period_key   , max(base_target1)     from bbb t   inner join        (      select  distinct manage_office_name       from aaa       where  1=1 ) t1  on t.manage_office_name=t1.manage_office_name  where  t.manage_office_name in ('abc')   group by time_period_key ;
ERROR 8110 (HY000): Cartesian product is unsupported
### 4. What is your TiDB version? (Required)
5.2.2

| Release Version: v5.2.2
Edition: Community
Git Commit Hash: da1c21fd45a4ea5900ac16d2f4a248143f378d18
Git Branch: heads/refs/tags/v5.2.2
UTC Build Time: 2021-10-20 06:08:33
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

**Comment by RenlySir** [comment]
![Uploading 20231208-105859.jpeg…]()

**Comment by XuHuaiyu** [comment]
The error message is thrown by planner. I'll change the label to sig/planner.
But I doubt this is an expected behavior instead of a bug.

**Comment by jebter** [comment]
This limitation has been removed in the latest version. Please try using the latest version.
