### ISSUE TITLE
all tidb panic during add index and inject network partition between pd leader and followers

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#49265]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、tidb_enable_dist_task='on'
2、run workload
3、add index for one table
4、inject network partition between pd leader and followers

### 2. What did you expect to see? (Required)
1、add index can success
2、no panic

### 3. What did you see instead (Required)
all tidb panic and qps drop to zero

{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:26:52.33799335+08:00 stderr F {\"level\":\"warn\",\"ts\":\"2023-12-07T21:26:52.337841+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3@v3.5.10/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc000b11a40/tc-pd:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:26:26.334326984+08:00 stderr F {\"level\":\"warn\",\"ts\":\"2023-12-07T21:26:26.334186+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3@v3.5.10/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc000b11a40/tc-pd:2379\",\"attempt\":0,\"error\":\"rpc error: code = Unknown desc = context deadline exceeded\"}","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:21:00.282718285+08:00 stderr F {\"level\":\"warn\",\"ts\":\"2023-12-07T21:21:00.282604+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3@v3.5.10/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc000b11a40/tc-pd:2379\",\"attempt\":0,\"error\":\"rpc error: code = Unknown desc = context deadline exceeded\"}","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:20:54.281320606+08:00 stderr F {\"level\":\"warn\",\"ts\":\"2023-12-07T21:20:54.281179+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3@v3.5.10/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc000b11a40/tc-pd:2379\",\"attempt\":0,\"error\":\"rpc error: code = Unknown desc = context deadline exceeded\"}","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:20:19.527136099+08:00 stderr F {\"level\":\"warn\",\"ts\":1701955219.527015,\"caller\":\"v3@v3.5.10/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc000d2cfc0/tc-pd-1.tc-pd-peer.endless-ha-test-add-index-tps-5100425-1-184.svc:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:20:18.276459698+08:00 stderr F {\"level\":\"warn\",\"ts\":\"2023-12-07T21:20:18.276258+0800\",\"logger\":\"etcd-client\",\"caller\":\"v3@v3.5.10/retry_interceptor.go:62\",\"msg\":\"retrying of unary invoker failed\",\"target\":\"etcd-endpoints://0xc000b11a40/tc-pd:2379\",\"attempt\":0,\"error\":\"rpc error: code = DeadlineExceeded desc = context deadline exceeded\"}","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:23.22561944+08:00 stdout F ","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:23.225614131+08:00 stdout F /tidb-server --store=tikv --advertise-address=tc-tidb-0.tc-tidb-peer.endless-ha-test-add-index-tps-5100425-1-184.svc --host=0.0.0.0 --path=tc-pd:2379 --config=/etc/tidb/tidb.toml","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:23.225577901+08:00 stdout F start tidb-server ...","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.503010408+08:00 stderr F \t/go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:72 +0x96","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.503008498+08:00 stderr F created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 79937253","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.503006727+08:00 stderr F \t/go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 +0x56","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.503004851+08:00 stderr F golang.org/x/sync/errgroup.(*Group).Go.func1()","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.503001332+08:00 stderr F \t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:770 +0x152","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.50299952+08:00 stderr F github.com/pingcap/tidb/pkg/ddl.(*indexWriteResultSink).collectResult(0xc02b485600)","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.50299766+08:00 stderr F \t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/backfilling_operators.go:793 +0xb1","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.50299436+08:00 stderr F github.com/pingcap/tidb/pkg/ddl.(*indexWriteResultSink).flush(0xc02b485600)","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502992181+08:00 stderr F \t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/ingest/backend.go:200 +0x2e8","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502990204+08:00 stderr F github.com/pingcap/tidb/pkg/ddl/ingest.(*litBackendCtx).Flush(0xc0560480b0, 0x14, 0x1?)","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.50297222+08:00 stderr F \t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/ingest/backend.go:160 +0x105","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502945692+08:00 stderr F github.com/pingcap/tidb/pkg/ddl/ingest.acquireLock({0x6377838, 0xc079be7ea0}, 0x0, {0xc084e921c0, 0x1b})","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.50292125+08:00 stderr F \t/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.10/concurrency/mutex.go:72 +0x26","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502918879+08:00 stderr F go.etcd.io/etcd/client/v3/concurrency.(*Mutex).Lock(0xc0a8e28e40, {0x6377838, 0xc079be7ea0})","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502916248+08:00 stderr F \t/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.10/concurrency/mutex.go:109 +0x40","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502913457+08:00 stderr F go.etcd.io/etcd/client/v3/concurrency.(*Mutex).tryAcquire(0xc0a8e28e40, {0x6377838, 0xc079be7ea0})","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502910178+08:00 stderr F \t/go/pkg/mod/go.etcd.io/etcd/client/v3@v3.5.10/concurrency/session.go:76","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502905912+08:00 stderr F go.etcd.io/etcd/client/v3/concurrency.(*Session).Client(...)","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502901556+08:00 stderr F goroutine 79952757 [running]:","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}
{"pod":"tc-tidb-0","container":"tidb","log":"2023-12-07T21:19:22.502898957+08:00 stderr F ","namespace":"endless-ha-test-add-index-tps-5100425-1-184"}

### 4. What is your TiDB version? (Required)
git hash：8dac7568ee59d6028db00ebfa6877f97d22b0295

**Comment by Benjamin2037** [comment]
it is duplicated with https://github.com/pingcap/tidb/issues/48546
