### ISSUE TITLE
flushWatcher loop may call refreshPluginState frequently when watch chan closed

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#49273]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/90e272abc31d22024c36ab095544bf20ba7f3575/pkg/plugin/plugin.go#L279-L289

This above code does not handle case `watchChan` closed, so `refreshPluginState` will be called frequently when this happens.

### 2. What did you expect to see? (Required)

When `watchChan` closed , we should close watch chan

### 3. What did you see instead (Required)

closed chan is not handled correctly

**Comment by siddontang** [comment]
@kevin-xianliu, please sort out the code that calls etcd directly, change them one by one, this is prohibited from now on.

**Comment by siddontang** [comment]
@kevin-xianliu
another thing you need to know is that one of the best way to avoid misconnecting etcd is to open Authentication in etcd and only pd-client can be allowed to connect it. please add an issue to track this.

**Comment by niubell** [comment]
> @kevin-xianliu another thing you need to know is that one of the best way to avoid misconnecting etcd is to open Authentication in etcd and only pd-client can be allowed to connect it. please add an issue to track this.

we don't provide uniform pd-client for Etcd now, but I think introducing the authentication mechanism for embedded Etcd is a good idea, will open an issue to track it after we sort out this module.
