### ISSUE TITLE
The parser.y not support `alter table table_name engine=``,add column column_name type;`

### ISSUE THREAD

**Issue by wolfstudy** [pingcap/tidb#4927]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
when i go to execute `alter table foo engine=``,add column id int;`
RDS support `alter table table_name engine=``;` 

2. What did you expect to see?
tidb can parser the sql

3. What did you see instead?
```
error while parsing sql:
 alter table bar engine=``,add column aaa int, err:line 1 column 29 near " column aaa int" (total length 44)
```

the reason is the `parser.y` not support, 

4. What version of TiDB are you using (`tidb-server -V`)?
```
Git Commit Hash: a0017eda04a1d48e9ec088457afe279a8cd064f4
UTC Build Time:  2017-08-18 10:35:56
```

**Comment by shenli** [comment]
@wolfstudy Thanks for your feedback!
