### ISSUE TITLE
planner: care to use errors.new and errors.errorf as your warnings and notes

### ISSUE THREAD

**Issue by AilinKid** [pingcap/tidb#49291]
## Enhancement
github/pingcap/errors.git has their own encapsulation of errors.new and errors.errorf, in which their will fetch stack trace of currently places. If your generation of this errors is used like warning and note, inside which the stack trace is never necessary, so try to avoid usage of this or use another stack-less errors

**Comment by AilinKid** [comment]
![image](https://github.com/pingcap/tidb/assets/15825830/f05ce04a-ec10-4f6f-8cfd-0227a659348f)
```
红色圈圈部分，我们在 v6.5.0 上是看不到的，为什么会在 v7.1.0 上成为性能问题呢（虽然生活可能整体来说占比不是很大，导致 planner 部分增长了约 （18.5-15.3）/18.5  = 17 个点）。研究发现，这部分基本上都是系统调用 caller的部分，主要是服务与 error.New() 和 errors.Errorf() 里面的填充的 stack 字段部分（stack: callers()）。这部分代码是 7.1新增用来 log warning 或者 note 用的。
```


we did find a performance problem from internal incall concluded by a lark document in planner component, you can search the keyword by `Care to use errors.New and errors.Errorf` in lark app, which is not suitable to put the link here.

stack-less error is called like `errors.NewNoStackError("msg")`

**Comment by jackysp** [comment]
<img width="1823" alt="image" src="https://github.com/pingcap/tidb/assets/4352397/2d10afc9-02ee-437b-88ec-f2520c8d4fff">
In version 7.1, I saw that in the batch write scenario, the CPU usage can reach up to 25%.
