### ISSUE TITLE
Speed up `create table` when the number of tables is relatively large

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#49370]
## Enhancement
Accelerate operations such as table creation when the number of tables is relatively large.

We have a cluster: 3 TiDB and TiKV, 1 PD
When the number of tables reaches 437k(the table structure inside is more complex), we get the following information（and we need to optimize it）:
<img width="1623" alt="截屏2023-12-12 15 15 27" src="https://github.com/pingcap/tidb/assets/4242506/e4369014-e4a5-4210-b8e4-32b12a53748f">

**Comment by kennedy8312** [comment]
candidate_1m

**Comment by 3AceShowHand** [comment]
https://github.com/pingcap/tiflow/pull/11125 This PR is cherry-pick back to the tiflow release-7.5 branch, but we found the PR    #49371 is not on the release-7.5 branch, so we need to cherry-pick it back to the release-7.5
