### ISSUE TITLE
some tests of disttask failed on `make ut`

### ISSUE THREAD

**Issue by ywqzzy** [pingcap/tidb#49463]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
make ut

### 2. What did you expect to see? (Required)
all tests passed
### 3. What did you see instead (Required)
```
556 [FAIL]  pkg/disttask/framework/storage TestBothTaskAndSubTaskTable
557 [FAIL]  pkg/disttask/framework/storage TestSubTaskTable
558 [FAIL]  pkg/disttask/framework/scheduler TestParallelPause
559[FAIL]  pkg/disttask/framework/handle TestHandle
560 [FAIL]  pkg/disttask/framework/storage TestGetTopUnfinishedTasks
562 [FAIL]  pkg/disttask/framework/storage TestTaskTable
```

**Comment by Defined2014** [comment]
After this issue closed, `make ut` could passed in my computer now. 🎉
