### ISSUE TITLE
Some tests can't pass when time_zone not equal to `Asia/Shanghai`

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#49493]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Some tests and feature can't pass when `time_zone != Asia/Shanghait`, we should fix it.

You could get list of test cases below

- [ ] TestStmtFile 
- [x] TestFlashbackCloseAndResetPDSchedule 
- [x] TestTiDBTrx 
- [ ] TestExactStalenessTransaction 
- [x] TestSetTransactionReadOnlyAsOf 
- [x] TestCancelFlashbackCluster 
- [ ] TestSetTiDBCloudStorageURI 
- [ ] TestIssue20236 
- [ ] TestClusterTableSlowQuery 
- [ ] TestGetLock 
- [ ] TestSelectClusterTable 
- [x] TestTiFlashFlashbackCluster 
- [x] TestGlobalVariablesOnFlashback 
- [ ] TestStmtFiles 
- [ ] TestChangingColOriginDefaultValueAfterAddColAndCastSucc 
- [x] TestAddDDLDuringFlashback 
- [ ] TestStmtFileInvalidLine 
- [x] [TestGetTimeZone](https://github.com/pingcap/tidb/issues/42755) 
- [x] TestRecoverClusterMeetError 

[log.txt](https://github.com/pingcap/tidb/files/13681847/log.txt)

### 2. What did you expect to see? (Required)

The test shouldn't related with time_zone.

### 3. What did you see instead (Required)

The test failed.

**Comment by Defined2014** [comment]
A related problem https://github.com/pingcap/tidb/issues/42755

**Comment by hawkingrei** [comment]
Can we use the bazel to our default ut tool? bazel has managed the unit test environment in the tidb repo.

https://github.com/pingcap/tidb/blob/f50e89450e388313574e3b955c696b4903569dac/.bazelrc#L21

**Comment by Defined2014** [comment]
> Can we use the bazel as our default ut tool? bazel has managed the unit test environment in the tidb repo.
> 
> https://github.com/pingcap/tidb/blob/f50e89450e388313574e3b955c696b4903569dac/.bazelrc#L21

But the problem is not only about test itself. We did not handle time_zone correctly in some features. Every test cases should pass in any time_zone.
