### ISSUE TITLE
tidb can not start with error "Unknown column 'type' in 'field list'" after restart this tidb

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#49507]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、restart one of tidb

### 2. What did you expect to see? (Required)
tidb can start successfully

### 3. What did you see instead (Required)
tidb can not start with error "Unknown column 'type' in 'field list'" after restart this tidb

"[terror.go:309] [\"unexpected error\"] [error=\"[planner:1054]Unknown column 'type' in 'field list'\"] [stack=\"github.com/pingcap/tidb/pkg/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/parser/terror/terror.go:309\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/cmd/tidb-server/main.go:403\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/cmd/tidb-server/main.go:302\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:267\"] [stack=\"github.com/pingcap/tidb/pkg/parser/terror.MustNil\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/parser/terror/terror.go:309\\nmain.createStoreAndDomain\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/cmd/tidb-server/main.go:403\\nmain.main\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/cmd/tidb-server/main.go:302\\nruntime.main\\n\\t/usr/local/go/src/runtime/proc.go:267\"]"

### 4. What is your TiDB version? (Required)
"[printer.go:47] [\"Welcome to TiDB.\"] [\"Release Version\"=v7.6.0-alpha] [Edition=Community] [\"Git Commit Hash\"=eb69dacc6eb648bd42b57f38762c96398752a902] [\"Git Branch\"=heads/refs/tags/v7.6.0-alpha] [\"UTC Build Time\"=\"2023-12-14 11:42:55\"] [GoVersion=go1.21.5] [\"Race Enabled\"=false] [\"Check Table Before Drop\"=false]"

**Comment by lance6716** [comment]
duplicated with https://github.com/pingcap/tidb/issues/49485
