### ISSUE TITLE
Lightning: split backoff is not long enough, and fail when EBS BR disabled region split

### ISSUE THREAD

**Issue by mittalrishabh** [pingcap/tidb#49517]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run EBS BR while lightning is running. It might fail lightning if BR suspends region split for more than 1 - 2 min. 

### 2. What did you expect to see? (Required)
Lightning to not fail if region split are suspended because of EBS BR
### 3. What did you see instead (Required)
Lightning failed
### 4. What is your TiDB version? (Required)
6.5

**Comment by D3Hunter** [comment]
```
failed to split: Err(Error(Kv(Error(Other(\\\"[src/server/raftkv/raft_extension.rs:128]: oneshot canceled\\\")))))\" "]
```
the error happens when doing EBS based backup, in which lightning don't support it
