### ISSUE TITLE
`HandleBinaryLiteral` should ignore `TypeNull`

### ISSUE THREAD

**Issue by YangKeao** [pingcap/tidb#49526]
## Enhancement

`from_binary(<nil>)` actually does nothing, but TiDB regards the `NULL` as binary string, so it may avoid some expressions to be pushed down to TiFlash. We can manually ignore this case.

(Though I don't know why this constant is not folded.)

**Comment by kennedy8312** [comment]
v5.4.0 seems to be the first release using "cast(from_binary(<nil>)".
![image](https://github.com/pingcap/tidb/assets/95329414/0ac1c101-e199-4b41-95d7-b7002cc9f227)

**Comment by kennedy8312** [comment]
v5.3.0 seems to be fine.
![image](https://github.com/pingcap/tidb/assets/95329414/0887acb3-2846-4919-be76-47b9c626afd9)

**Comment by kennedy8312** [comment]
Regression Analysis
PR caused this regression: https://github.com/pingcap/tidb/pull/30706

**Comment by kennedy8312** [comment]
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-alpha-458-geb6c89d6d4-dirty
Edition: Community
Git Commit Hash: eb6c89d6d4046509ace6ad6375b775fecdc46d00
Git Branch: HEAD
UTC Build Time: 2024-02-01 10:04:22
GoVersion: go1.21.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> explain select null as a union all select 'a' as a order by a;
+--------------------------+---------+------+---------------+-----------------+
| id                       | estRows | task | access object | operator info   |
+--------------------------+---------+------+---------------+-----------------+
| Sort_9                   | 2.00    | root |               | Column#3        |
| └─Union_11               | 2.00    | root |               |                 |
|   ├─Projection_13        | 1.00    | root |               | <nil>->Column#3 |
|   │ └─TableDual_14       | 1.00    | root |               | rows:1          |
|   └─Projection_15        | 1.00    | root |               | a->Column#3     |
|     └─TableDual_16       | 1.00    | root |               | rows:1          |
+--------------------------+---------+------+---------------+-----------------+
6 rows in set (0.00 sec)

mysql> select null as a union all select 'a' as a order by a;
+---+
| a |
+---+
| NULL |
| a |
+---+
2 rows in set (0.01 sec)

**Comment by kennedy8312** [comment]
mysql> explain select null as a union all select 'a' as a order by a;
+--------------------------+---------+------+---------------+---------------------------------------------------+
| id                       | estRows | task | access object | operator info                                     |
+--------------------------+---------+------+---------------+---------------------------------------------------+
| Sort_9                   | 2.00    | root |               | Column#3                                          |
| └─Union_11               | 2.00    | root |               |                                                   |
|   ├─Projection_13        | 1.00    | root |               | cast(from_binary(<nil>), var_string(1))->Column#3 |
|   │ └─TableDual_14       | 1.00    | root |               | rows:1                                            |
|   └─Projection_15        | 1.00    | root |               | a->Column#3                                       |
|     └─TableDual_16       | 1.00    | root |               | rows:1                                            |
+--------------------------+---------+------+---------------+---------------------------------------------------+
6 rows in set (0.00 sec)

mysql> select null as a union all select 'a' as a order by a;
+---+
| a |
+---+
| NULL |
| a |
+---+
2 rows in set (0.01 sec)

mysql> select tidb_version();
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0-alpha-459-g87ab28ebb2-dirty
Edition: Community
Git Commit Hash: 87ab28ebb2ac87b6e8d7c252187338c517598318
Git Branch: HEAD
UTC Build Time: 2024-02-01 10:09:06
GoVersion: go1.21.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
