### ISSUE TITLE
Insert a special datetime with time_zone results in loss of precision

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#49555]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t(a datetime(3));
insert into t values ('2020-01-01 12:00:00.123456 +0600 PST'); # The format is Golang’s default format
insert into t values ('2020-01-01 12:00:00.123456 -0600 PST');
select * from t;
```

### 2. What did you expect to see? (Required)

Got error during insert or keep result like `2020-01-01 12:00:00.123`

MySQL will report error during insert.

### 3. What did you see instead (Required)

```
mysql> select * from t;
+-------------------------+
| a                       |
+-------------------------+
| 2020-01-01 12:00:00.123 |
| 2020-01-01 12:00:00.000 |
+-------------------------+
2 rows in set (0.01 sec)
```

### 4. What is your TiDB version? (Required)

https://github.com/pingcap/tidb/commit/23953a7cbe82a18390f2a213777a57f48e203d18

**Comment by Defined2014** [comment]
Why the results are different in case of `+` and `-` is because code below. https://github.com/pingcap/tidb/blob/23953a7cbe82a18390f2a213777a57f48e203d18/pkg/types/time.go#L590

`unicode.IsPunct('+')` will return false and the result is true for `-`.

**Comment by SeaRise** [comment]
```
SET @@SESSION.SQL_MODE='ALLOW_INVALID_DATES';
drop table if exists t;
create table t(a datetime(3));
insert into t values ('2020-01-01 12:00:00.123456 +0600 PST'); # The format is Golang’s default format
insert into t values ('2020-01-01 12:00:00.123456 -0600 PST');
select * from t;
+-------------------------+
| a                       |
+-------------------------+
| 2020-01-01 12:00:00.123 |
| 2020-01-01 12:00:00.000 |
+-------------------------+
```
After `SET @@SESSION.SQL_MODE='ALLOW_INVALID_DATES';`, mysql is same as tidb

**Comment by SeaRise** [comment]
tidb
```
SET @@SESSION.SQL_MODE='ALLOW_INVALID_DATES';
drop table if exists t;
create table t(a datetime(3));
insert into t values ('2020-01-01 12:00:00.123456 +0600 PST'); # The format is Golang’s default format
insert into t values ('2020-01-01 12:00:00.123456 -0600 PST');
select * from t;
+-------------------------+
| a                       |
+-------------------------+
| 2020-01-01 12:00:00.123 |
| 2020-01-01 12:00:00.123 |
+------------------------
```
After SET @@SESSION.SQL_MODE='ALLOW_INVALID_DATES'; the result of tidb is both `2020-01-01 12:00:00.123`.

**Comment by SeaRise** [comment]
```
use test;
SET @@SESSION.SQL_MODE='ALLOW_INVALID_DATES';
drop table if exists t;
create table t(a datetime(3));
insert into t values ('2020-01-01 12:00:00.123456 +0600 PST');
insert into t values ('2020-01-01 12:00:00.123456 -0600 PST');
select * from t;
```

**Comment by SeaRise** [comment]
tiflash and tikv have similar problems.
https://github.com/pingcap/tiflash/issues/8754
https://github.com/tikv/tikv/issues/16492

**Comment by SeaRise** [comment]
related code introduced by https://github.com/pingcap/tidb/pull/9933
