### ISSUE TITLE
record subtask end time

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#49617]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

![image](https://github.com/pingcap/tidb/assets/1689766/6b8201f5-de0b-4159-a11c-17e084f448fd)

**Comment by ywqzzy** [comment]
All subtasks are affected

**Comment by D3Hunter** [comment]
not a bug, end_time is just added, hasn't implemented https://github.com/pingcap/tidb/pull/49020/files#diff-d337d4c9dc3da1a17f1792df53a00f6d59a5ea9977070d7068a7e248f674100a
