### ISSUE TITLE
Inconsistent DFE subtask count in two panels

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#49615]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Run a IMPORT INTO subtask

### 3. What did you see instead (Required)

We can see task 450001 the total subtasks count is 4
![image](https://github.com/pingcap/tidb/assets/1689766/ce929874-d07f-44a2-a3fd-c7e9a8784110)

but in another panel it's 5
![image](https://github.com/pingcap/tidb/assets/1689766/55045006-b15f-4d6d-a3ea-65fbe8723779)

**Comment by lance6716** [comment]
Maybe caused by wrong place to update the metrics (from @ywqzzy )

![image](https://github.com/pingcap/tidb/assets/1689766/3b3796f7-297c-4a2c-88ab-2c7b7244769c)

**Comment by okJiang** [comment]
The former is `total_cnt`. The latter is `running`

**Comment by okJiang** [comment]
36 + 4 - 35 = 5

**Comment by okJiang** [comment]
Some subtask has been balanced to other node...
<img width="1057" alt="image" src="https://github.com/pingcap/tidb/assets/23556834/8361f885-e757-45c7-9e84-cc5e1d1da155">
<img width="764" alt="image" src="https://github.com/pingcap/tidb/assets/23556834/fff27124-ef2b-46cd-b95c-668bc0d55834">
<img width="794" alt="image" src="https://github.com/pingcap/tidb/assets/23556834/b6531db5-745c-4c5a-bc61-a67c21b33e01">
<img width="760" alt="image" src="https://github.com/pingcap/tidb/assets/23556834/95dcc082-3880-489b-ab44-c35a6997c0b1">


We need record the exec_id.

**Comment by okJiang** [comment]
In https://github.com/pingcap/tidb/pull/50361, I have tried to collect metrics in `task_table.go` and added `exec_id`. However, metrics in different instance exist a instance lable. It is difficult to delete other instance metrics. So, the pending duration can't be deleted.
<img width="743" alt="image" src="https://github.com/pingcap/tidb/assets/23556834/ce6ebfdf-64d1-4761-ba2a-ac7b21cc9b2c">

So, the better way is collecting metrics in scheduler manager that regularly collect subtask information from `tidb_background_subtask`.

**Comment by okJiang** [comment]
> So, the better way is collecting metrics in scheduler manager that regularly collect subtask information from tidb_background_subtask.

How about this? @ywqzzy @D3Hunter

**Comment by D3Hunter** [comment]
> > So, the better way is collecting metrics in scheduler manager that regularly collect subtask information from tidb_background_subtask.
> 
> How about this? @ywqzzy @D3Hunter

up vote, https://github.com/pingcap/tidb/pull/47175#pullrequestreview-1641571628
