### ISSUE TITLE
Distributed task pending duration metrics is not reset, and ADD INDEX subtask has no prefix

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#49621]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

![image](https://github.com/pingcap/tidb/assets/1689766/45805e0a-b91c-4240-bad1-78e4c70e8534)

**Comment by lance6716** [comment]
Other metrics like 
![image](https://github.com/pingcap/tidb/assets/1689766/e2e8f0ef-ef01-4774-9c60-c4a2d7e493ee)
can also be reset

**Comment by okJiang** [comment]
https://github.com/pingcap/tidb/assets/23556834/b14ee0e2-e203-48d3-b1f0-f81565e8dabb

I am sorry I didn't reproduce the first problem.
