### ISSUE TITLE
state incorrect

### ISSUE THREAD

**Issue by daodaovps** [pingcap/tidb#4968]
```
» store
{
  "count": 2,
  "stores": [
    {
      "store": {
        "id": 1,
        "address": "192.168.2.118:20160",
        "state": 0,
        "state_name": "Down"
      },
      "status": {
        "leader_weight": 1,
        "region_weight": 1
      }
    },
    {
      "store": {
        "id": 4,
        "address": "192.168.2.117:20160",
        "state": 1,
        "state_name": "Offline"
      },
      "status": {
        "leader_weight": 1,
        "region_weight": 1
      }
    }
  ]
}

```

why  state=0 and state_name is Down about the store id 1 ?

and  state=1  waiting a long time about the store id 4  , not change to be  state=2.

**Comment by shenli** [comment]
@daodaovps Thanks for your feedback!
Please provide more information about your cluster. Such as how many nodes, the version of the binaries and your operation flow.

**Comment by shenli** [comment]
@disksing PTAL

**Comment by daodaovps** [comment]
two  kv  nodes, and I  `store delete 4`  ,  how can I   reconnect id 4 or  change it to status 2.
I use the http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz

**Comment by shenli** [comment]
@daodaovps You only have two tikv nodes but need at least three replicas for each raft-group.
When you send `store delete 4` command to pd, pd need to find someplace to hold the replicas for store 4. But it is impossible. So the offline process will get stuck.
@disksing Is there any way to change the store 4 to status 0?

**Comment by disksing** [comment]
@daodaovps You can use cURL to reset a store's state:
```
curl http://pd-addr:2379/pd/api/v1/store/4/state?state=Up
```

**Comment by daodaovps** [comment]
@disksing  `http://192.168.1.115:2379/pd/api/v1/store/1/state?state=Up`   but I got 404. 
I don't find the  reset action in the  doc ...... (https://cdn.rawgit.com/pingcap/docs/master/op-guide/pd-api-v1.html)

**Comment by disksing** [comment]
@daodaovps I forgot to set the HTTP method, sorry about that. The command should be
```
curl -X POST http://pd-addr:2379/pd/api/v1/store/4/state?state=Up
```
This API is used for unusual recovering, not normal case, so not included in the documents.
