### ISSUE TITLE
Build fails on 32-bit machine for subparts

### ISSUE THREAD

**Issue by mike9421** [pingcap/tidb#49712]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
When I used the "github.com/pingcap/tidb/pkg/parser" library and built it on a 32-bit machine, I got an "overflows" error.
![image](https://github.com/pingcap/tidb/assets/37992936/bda74f9a-8356-4f42-a2dd-69eb89db60d7)

### 2. What did you expect to see? (Required)
I hope it can be fixed if TIDB supports 32-bit machines.

### 4. What is your TiDB version? (Required)
github.com/pingcap/tidb/pkg/parser v0.0.0-20231222053804-6a8976f2fdd4

**Comment by Defined2014** [comment]
We won't be supporting this right now. So close this issue.
