### ISSUE TITLE
HTTP status API should show table storage size

### ISSUE THREAD

**Issue by hicqu** [pingcap/tidb#4989]
We need more HTTP status API in TiDB:
- [ ] get table storage size

**Comment by morgo** [comment]
This is available in `information_schema.tables`, so it would be quite easy to add to the status API.

**Comment by jianzhiyao** [comment]
I can help to support this issue, you can assign it to me :).
@morgo

**Comment by jianzhiyao** [comment]
Table storage information should be add in which api?

**Comment by jianzhiyao** [comment]
https://github.com/pingcap/tidb/pull/22859 is ready
