### ISSUE TITLE
`SHOW PLUGINS` doesn't display supported auth plugins

### ISSUE THREAD

**Issue by Mini256** [pingcap/tidb#49922]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
SHOW PLUGINS;
```

### 2. What did you expect to see? (Required)

```sql
MySQL root@127.0.0.1:test> SHOW PLUGINS;
+----------------------------------+----------+--------------------+---------+---------+
| Name                             | Status   | Type               | Library | License |
+----------------------------------+----------+--------------------+---------+---------+
| sha256_password                  | ACTIVE   | AUTHENTICATION     | <null>  | GPL     |
| caching_sha2_password            | ACTIVE   | AUTHENTICATION     | <null>  | GPL     |
| mysql_native_password            | ACTIVE   | AUTHENTICATION     | <null>  | GPL     |
+----------------------------------+----------+--------------------+---------+---------+
```

![image](https://github.com/pingcap/tidb/assets/5086433/69c08760-dd3d-47f5-9a18-5a9ca9a19278)

### 3. What did you see instead (Required)

```sql
mysql> SHOW PLUGINS;
Empty set (0.00 sec)
```

On the **Add user account** page of phpmyadmin's interface, users are unable to view the list of **Authentication plugins**. Since phpmyadmin can't get the exact auth type, it generates an incorrect `CREATE USER` SQL, which prevents PHP developers from using phpmyadmin to connect to TiDB to create new users.

![image](https://github.com/pingcap/tidb/assets/5086433/9099823e-b783-4671-8656-c1ac1c0521ae)

### 4. What is your TiDB version? (Required)

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:41:10
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv
1 row in set (0.01 sec)
```

**Comment by bb7133** [comment]
I won't treat this as a bug: TiDB has a different design & implementation of plugin with MySQL, and thus the 'auth methods' are not part of 'plugins'.

I will close this issue.

**Comment by Mini256** [comment]
@bb7133 Or consider as a feature request? 

phpmyadmin is probably not the only GUI tool that uses plugins information to get the current auth methods supported by the database.
