### ISSUE TITLE
distask scheduler takes step success while it's failed actually

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#49950]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

as we're checking whether task step fails or success using 2 sql, if the task fail in the middle, we will take it as success and switch task to next step. **if it's already the last step, the task will be marked as success incorrectly**
https://github.com/pingcap/tidb/blob/7af117d818dba9472a0b09b6445a46426865374d/pkg/disttask/framework/scheduler/scheduler.go#L322-L336

it might cause some real-tikv case fail
https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_check2/runs/381/nodes/107/steps/598/log/?start=0
```
[2023/12/29 11:06:09.434 +00:00] [INFO] [client.go:639] ["[pd] service mode changed"] [old-mode=UNKNOWN_SVC_MODE] [new-mode=PD_SVC_MODE]
    scheduler.go:387: Unexpected call to *mocklocal.MockTiKVModeSwitcher.ToNormalMode([context.Background.WithValue(type util.RequestSourceKeyType, val <not Stringer>).WithCancel.WithValue(type metric.ctxKeyType, val <not Stringer>)]) at pkg/disttask/importinto/scheduler.go:387 because: 
        expected call at tests/realtikvtest/importintotest/import_into_test.go:812 has already been called the max number of times
        expected call at tests/realtikvtest/importintotest/import_into_test.go:845 has already been called the max number of times
        expected call at tests/realtikvtest/importintotest/import_into_test.go:880 has already been called the max number of times
```

**Comment by hawkingrei** [comment]
It is the root cause for this error.

```
Error Trace:	pkg/disttask/framework/planner/planner_test.go:60
        	Error:      	Received unexpected error:
        	            	no managed nodes
        	            	[github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).getCPUCountOfManagedNodes](http://github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).getCPUCountOfManagedNodes)
        	            		pkg/disttask/framework/storage/task_table.go:1324
        	            	[github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).CreateTaskWithSession](http://github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).CreateTaskWithSession)
        	            		pkg/disttask/framework/storage/task_table.go:225
        	            	[github.com/pingcap/tidb/pkg/disttask/framework/planner.(*Planner).Run](http://github.com/pingcap/tidb/pkg/disttask/framework/planner.(*Planner).Run)
        	            		pkg/disttask/framework/planner/planner.go:39
        	            	pkg/disttask/framework/planner/planner_test_test.TestPlanner
        	            		pkg/disttask/framework/planner/planner_test.go:59
        	            	testing.tRunner
        	            		GOROOT/src/testing/testing.go:1595
        	            	runtime.goexit
        	            		src/runtime/asm_amd64.s:1650
        	Test:       	TestPlanner
```

**Comment by D3Hunter** [comment]
> It is the root cause for this error.
> 
> ```
> Error Trace:	pkg/disttask/framework/planner/planner_test.go:60
>         	Error:      	Received unexpected error:
>         	            	no managed nodes
>         	            	[github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).getCPUCountOfManagedNodes](http://github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).getCPUCountOfManagedNodes)
>         	            		pkg/disttask/framework/storage/task_table.go:1324
>         	            	[github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).CreateTaskWithSession](http://github.com/pingcap/tidb/pkg/disttask/framework/storage.(*TaskManager).CreateTaskWithSession)
>         	            		pkg/disttask/framework/storage/task_table.go:225
>         	            	[github.com/pingcap/tidb/pkg/disttask/framework/planner.(*Planner).Run](http://github.com/pingcap/tidb/pkg/disttask/framework/planner.(*Planner).Run)
>         	            		pkg/disttask/framework/planner/planner.go:39
>         	            	pkg/disttask/framework/planner/planner_test_test.TestPlanner
>         	            		pkg/disttask/framework/planner/planner_test.go:59
>         	            	testing.tRunner
>         	            		GOROOT/src/testing/testing.go:1595
>         	            	runtime.goexit
>         	            		src/runtime/asm_amd64.s:1650
>         	Test:       	TestPlanner
> ```

`no managed nodes` is caused by that we didn't wait node registered before submit task. they're fixed together though
