### ISSUE TITLE
flaky test `TestCreateDropCreateTable`

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#50061]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
--- FAIL: TestCreateDropCreateTable (5.46s)
    ddl_api_test.go:214: 
        	Error Trace:	/home/prow/go/src/github.com/pingcap/tidb/pkg/ddl/ddl_api_test.go:214
        	Error:      	"446773575105380352" is not less than "446773574582665216"
        	Test:       	TestCreateDropCreateTable
        	Messages:   	second create should finish after drop
```

https://prow.tidb.net/view/gs/prow-tidb-logs/logs/periodic-daily-tidb-unit-test/1742606910567223296

**Comment by hawkingrei** [comment]
It is still existed.

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/50718/tiprow_fast_test/1750704587880271872#1:build-log.txt%3A6724

**Comment by hawkingrei** [comment]
It still exists.

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/51319/tiprow_fast_test/1762374028326080512#1:build-log.txt%3A8661
