### ISSUE TITLE
count memory cost for returned []byte or SliceLocation

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#50131]
## Enhancement

We have limited the total memory block acquired from membuf.Pool to 16G, but the keys and values type which has their underlying array pointing to membuf.Pool also costs a lot memory so the node may OOM.

![image](https://github.com/pingcap/tidb/assets/1689766/65a81ee3-bb74-4f29-8176-700483d516e2)
⬇️
![image](https://github.com/pingcap/tidb/assets/1689766/3c5e494e-f862-4d3b-9445-caa8aa90f0b0)

**Comment by tangenta** [comment]
Adding index with global sort encounter OOM. We need to merge the fix to release-7.6. Let me change this issue to bug.
