### ISSUE TITLE
flaky case TestRecoverTempTable

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#50154]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/50129/tiprow_fast_test/1744184987835437056
```
    testkit.go:454: 
        	Error Trace:	pkg/testkit/testkit.go:454
        	            				pkg/executor/recover_test.go:273
        	Error:      	Error message not equal:
        	            	expected: "Can't find localTemporary/dropped/truncated table: tmp2_recover in DDL history jobs"
        	            	actual  : "Can't find dropped/truncated table 'tmp2_recover' in GC safe point 2024-01-06 02:34:21.8 +0000 UTC"
        	Test:       	TestRecoverTempTable
```

**Comment by Defined2014** [comment]
After https://github.com/pingcap/tidb/pull/50211 merged, I don't think this will happen again. So close this issue.
