### ISSUE TITLE
Cluster variables actual value is inconsistent in information_schema.variables_info

### ISSUE THREAD

**Issue by kennedy8312** [pingcap/tidb#50155]
## Bug Report
We observed the default values of some database variables in information_schema.variables_info are inconsistent with its current behavior in v7.6.0 and the [TiDB doc](https://docs.pingcap.com/tidb/stable/system-variables).

### 1. Minimal reproduce step (Required)
tiup playground nightly
select variable_name,default_value,current_value from information_schema.variables_info where default_value !=current_value and default_value !='';
select tidb_version();

### 2. What did you expect to see? (Required)
The default values in information_schema.variables_info is consistent with the value of current value, plus the tidb doc.

### 3. What did you see instead (Required)
mysql> select variable_name,default_value,current_value from information_schema.variables_info where default_value !=current_value and default_value !='';
+-----------------------------------+---------------+--------------------+
| variable_name                     | default_value | current_value      |
+-----------------------------------+---------------+--------------------+
| tidb_enable_mutation_checker      | OFF           | ON                 |
| collation_connection              | utf8mb4_bin   | utf8mb4_0900_ai_ci |
| tidb_pessimistic_txn_fair_locking | OFF           | ON                 |
| tidb_enable_1pc                   | OFF           | ON                 |
| tidb_enable_async_commit          | OFF           | ON                 |
| tidb_txn_assertion_level          | OFF           | FAST               |
| tidb_row_format_version           | 1             | 2                  |
| last_sql_use_alloc                | OFF           | ON                 |
| timestamp                         | 0             | 1704682533.9524422 |
+-----------------------------------+---------------+--------------------+
9 rows in set (0.02 sec)

### 4. What is your TiDB version? (Required)
| Release Version: v7.6.0-alpha
Edition: Community
Git Commit Hash: 9b0fd9ea299266da70456f6e6077ed14bd191cfc
Git Branch: heads/refs/tags/v7.6.0-alpha
UTC Build Time: 2024-01-06 14:28:16
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv |

**Comment by kennedy8312** [comment]
candidate_1m

**Comment by jiyfhust** [comment]
Seems same with what #49524 solves.
