### ISSUE TITLE
pause task might not succeed when some task is balanced away

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#50181]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
- run a task with 2 subtask on 1 node, and node1 start running
- scale out(or what ever case cause subtasks scheduled to balance state), so node1/node2 each have 1 subtask
- before node2 start task executor, the task is marked as pausing
- node1 will mark 1 subtask as paused
- node2 will never see the task, so the assigned subtask keeps in `pending`
- scheduler keeps waiting all subtasks to be paused

### 4. What is your TiDB version? (Required)
master

**Comment by ywqzzy** [comment]
manager.go:197-205 will handle this case
