### ISSUE TITLE
 CNF/DNF of OR is MVIndex, but mv index does not selected 

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#50265]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

SELECT item_primary_key FROM items WHERE
? member of (domains) OR 
? member of (image_signatures) OR
? member of (canonical_links) OR
json_contains(feed_profile_ids, '[?]')
/*+ this dnf item **could** be used as access condi since it has only one index path*/
limit 10

### 2. What did you expect to see? (Required)
mv index can be selected
### 3. What did you see instead (Required)
[9f9a201fe639fafc3984a2bac2cf792d8cb41e9e3989f92f4d14b244e827ce0e.txt](https://github.com/pingcap/tidb/files/13884674/9f9a201fe639fafc3984a2bac2cf792d8cb41e9e3989f92f4d14b244e827ce0e.txt)

### 4. What is your TiDB version? (Required)

master

**Comment by AilinKid** [comment]
```
/** SQ8-2 **/
SELECT
  item_primary_key
FROM
  items
WHERE
  "B2c32" member of (domains)
  OR "2eoqyp6399" member of (image_signatures)
  OR "E33EAdAc2Bee.com/s/link" member of (canonical_links)
  OR json_contains(feed_profile_ids, '[69236881]')
LIMIT
  10;
```
since json_contains is INTERSECTION logic, the embedded INTERSECTION indexMerge inside UNION indexMerge is banned. Currently fallback to table scan is reasonable.
