### ISSUE TITLE
Why we still not using tidb?

### ISSUE THREAD

**Issue by netroby** [pingcap/tidb#5037]
Hello, would you like share experience why you still  not using TiDB?

Me the first.
1. It not had the 100% feature like MySQL can provided(like memcached plugin, the JSON,  Spatial Data)
2. It required more complex step to setup a minimal running instance(MySQL can easy install and deploy)
3. Safe data replicate to mysql or vice versa.  
4. Gui management tools, like (mysql workbench)
5. Good document, (like mysql document, very impressive detail)
6. version changes prove and update notes(is it safe to upgrade, and can we back to mysql? ?)

**Comment by shenli** [comment]
@netroby Thanks for your feedback!


> It not had the 100% feature like MySQL can provided(like memcached plugin, the JSON, Spatial Data)
There will be not other database  except MySQL could be 100% compatible with MySQL. We support most of MySQL's feature. JSON is already supported. Please take a look at the [document](https://github.com/pingcap/docs-cn/blob/master/sql/json-functions-generated-column.md). Spatial index is on the way.
Many users have migrate their application from MySQL to TiDB. Is there any feature that is critical to you application but still missing in TiDB? Please create a new issue.


> It required more complex step to setup a minimal running instance(MySQL can easy install and deploy)
We have a tool based on ansible to help users deploy TiDB. And we are working on a more convenient way based on kuberetes to deply TiDB with 1-click. 

> Safe data replicate to mysql or vice versa.
You could look at the migration section of our document. There is a way to do this. We have used this in production environment.

> Gui management tools, like (mysql workbench)
Please try MySQLWorkbench on TiDB and enjoy it.

> Good document, (like mysql document, very impressive detail)
Document is much better now, but we are still improving it. If there is anything you could not find in the document repo ([docs](https://github.com/pingcap/docs) and [docs-cn](https://github.com/pingcap/docs-cn)), please let us know.

> version changes prove and update notes(is it safe to upgrade, and can we back to mysql? ?)
You can find the release notes [here](https://github.com/pingcap/docs/blob/master/release/rn.md).
We will aways be compatible with MySQL. So you can aways migrate back from TiDB to MySQL.

**Comment by netroby** [comment]
2. using ansible a bit more complex than just apt-get install  or dnf install

**Comment by netroby** [comment]
And thanks @shenli , I just want to share you ,why we still not using TiDB, there may much works to do if you and your team want MySQL user migrate to TiDB, best wishes for TiDB.

**Comment by shenli** [comment]
@netroby Thanks for your advice.
Yes, ansible is not as convenient as apt-get. So we choose to use docker+k8s to make it easier. TiDB is much more complex than MySQL. We need deploy the core components and the monitor system. It need a lot of work to config the whole system. So apt-get is not enough.
Installation is not a blocking issue in most cases but we will improve it.

**Comment by netroby** [comment]
Docker+k8s not  enterprise ready. most tradition company still using old way to install software.

**Comment by shenli** [comment]
So it is the reason why we still provide the ansible way. It is not perfect, but it is the best choice for now.

**Comment by shenli** [comment]
@netroby Hope to hear more suggestions from you!
