### ISSUE TITLE
mysql client v5.7.26 connect to tidb master fail for unknown error number

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#50401]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

root@wkload-0:/tools# /root/opt/mysql/5.1.72/bin/mysql -u nopw -h tc-tidb.testbed-endless-client-ncjv5 -P 4000 -e QUIT
root@wkload-0:/tools# /root/opt/mysql/5.7.26/bin/mysql -u nopw -h tc-tidb.testbed-endless-client-ncjv5 -P 4000 -e QUIT
ERROR 2026 (HY000): SSL connection error: unknown error number
root@wkload-0:/tools# /root/opt/mysql/8.0.17/bin/mysql -u nopw -h tc-tidb.testbed-endless-client-ncjv5 -P 4000 -e QUIT
root@wkload-0:/tools# 

### 2. What did you expect to see? (Required)

mysql client v5.7.26 can connect to master

### 3. What did you see instead (Required)
root@wkload-0:/tools# /root/opt/mysql/5.7.26/bin/mysql -u nopw -h tc-tidb.testbed-endless-client-ncjv5 -P 4000 -e QUIT
ERROR 2026 (HY000): SSL connection error: unknown error number
### 4. What is your TiDB version? (Required)

master

**Comment by hawkingrei** [comment]
It is designed by https://github.com/pingcap/tidb/pull/36037. 

MySQL 5.7 uses tls1.x as the default tls version. but it is deprecated in the mysql8.0.

You can read [this](https://cloud.tencent.com/developer/article/2005393) in detail.
