### ISSUE TITLE
make bazel running without nogo

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#50400]
## Enhancement

With nogo, we can run many linter with cache. but developers run it locally. it still takes too much time. so we need to add a new mode without nogo to build.

**Comment by ei-sugimoto** [comment]
This problem does not appear to have been solved for a long time. May I tackle it?
Here are my ideas.
```make
...
.PHONY: bazel_lint
NOGO_FLAG=true
bazel_lint: bazel_prepare
    bazel build //... --//build:with_nogo_flag=$(NOGO_FLAG)
...
```

```bash
make NOGO_FLAG=false
```
