### ISSUE TITLE
Support SHUTDOWN SQL command (and protocol cmd)

### ISSUE THREAD

**Issue by liubo0127** [pingcap/tidb#5046]
There is no smooth way to stop tidb and must stop the process by kill

**Comment by shenli** [comment]
OK, we will provide a way to shutdown tidb-server gracefully.

**Comment by morgo** [comment]
I suggest supporting the MySQL way: a `shutdown` api command (that mysqladmin can call) and an sql statement used in newer versions (`shutdown`).  MySQL 8.0 also has a `restart` command.

**Comment by morgo** [comment]
I think the semantic expected is just for a single instance shutdown.  I looked into this the other day, and the logical way seemed to do it was for `SHUTDOWN` or the protocol cmd `ComShutdown` to send an interrupt signal to the process.

The will then be caught by the main package, and start shutdown (not-withstanding a current issue that garbage collection doesn't like to be interrupted).

Thus, `SHUTDOWN` is just a nicer version of a `Control+c` to the window running `tidb-server`.

**Comment by ekalinin** [comment]
@morgo

Both PRs were merged (parser + tidb).

**Comment by SunRunAway** [comment]
Thanks.
