### ISSUE TITLE
br restore failed due to "split region failed"

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#50471]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Create a TiDB cluster with 20 TiKVs (16c64g)
2. run br restore 

![image](https://github.com/pingcap/tidb/assets/7403864/f4a56a2d-769e-4ab8-80eb-23529519ac82)

### 2. What did you expect to see? (Required)
Br restore should succeed

### 3. What did you see instead (Required)
Br restore failed

### 4. What is your TiDB version? (Required)
```
[root@br-0 tmp]# /br-no-limit -V                           
Release Version: v7.6.0-alpha-727-g40c77af-dirty           
Git Commit Hash: 40c77afaa130697b197c44181facb3621b406816  
Git Branch: forbidden_cache_from_statistic_and_coprocessor 
Go Version: go1.21.6                                       
UTC Build Time: 2024-01-16 08:23:31                        
Race Enabled: false                                                                             
```

**Comment by Leavrth** [comment]
https://github.com/pingcap/tidb/issues/50477

**Comment by 3pointer** [comment]
close it due to duplicate with https://github.com/pingcap/tidb/issues/50477
