### ISSUE TITLE
unsupported modify column charset utf8 not match origin binary

### ISSUE THREAD

**Issue by kylezhang** [pingcap/tidb#5049]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I alter table column use `1):sql` and `2): SequelPro GUI `(ps:images) both cann't success. But origin mysql database that is ok.

1).
```
ALTER TABLE `bak_report_overview_daily_bak` CHANGE `cp` `cp` VARCHAR(11)
 NOT NULL
 DEFAULT ''
 COMMENT '外键：项目ID';
```
![image](https://user-images.githubusercontent.com/3679798/32545919-d2b658ce-c442-11e7-9004-2f4b5f0fdfcb.png)

2).alter images
 
![image](https://user-images.githubusercontent.com/3679798/32545912-cc2a95a6-c442-11e7-85b4-d01d182ebc12.png)

2. What did you expect to see?

   I hope it like as mysql that i can alter table column success. Thanks.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V`)?
     `Server version: 5.7.1-TiDB-1.0.0 MySQL Community Server (Apache License 2.0)`

**Comment by coocood** [comment]
We don't support modify the type of a column yet.
You can checkout https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md
for more details.

**Comment by kylezhang** [comment]
yes, But I think this feature is very necessary.
[ddl](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md#ddl)
```
Note: The change/modifying column operation cannot make the length of the original type become shorter and it cannot change the unsigned/charset/collate attributes of the column.
```

**Comment by shenli** [comment]
@kylezhang Thanks for your feedback! This feature is not on our short term list. We will consider this later. May be after TiDB 2.0 .

**Comment by msgcode** [comment]
re create your table is fine
