### ISSUE TITLE
one tikv has no leader and slow down br restore speed

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#50566]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. use br to restore a full backup of 30TB 500k table cluster to a 20 TiKV nodes new cluster.
```
/br  restore  full "-s" "gcs://aaa/bbb-500k-table-30tb-backup-with-stats-3" "-u" "http://tc-pd:2379" "--check-requirements=false" "--ddl-batch-size=128" "--tikv-max-restore-concurrency=128" "--granularity=coarse-grained" "--send-credentials-to-tikv=true" "--checksum=false"
```

### 2. What did you expect to see? (Required)
all tikv should have restore tasks.

### 3. What did you see instead (Required)
One TiKV has no leader, and slow down the br restore speed.

![image](https://github.com/pingcap/tidb/assets/7403864/1774fb2c-d6b8-4545-bac0-5b151e27ea98)

### 4. What is your TiDB version? (Required)

[root@br-0 tmp]# /br -V
Release Version: v7.6.0-pr50518
Git Commit Hash: https://github.com/pingcap/tidb/commit/4888198abe9f8de0081975aa498f6b970833305a
Git Branch: heads/refs/tags/v7.6.0-pr50518
Go Version: go1.21.5
UTC Build Time: 2024-01-18 02:50:49
Race Enabled: false

**Comment by 3pointer** [comment]
This is because `evict-slow-store` triggeered by PD. we can fix this issue by remove this scheduler during restore.
