### ISSUE TITLE
Br restore download SST throughput not stable throughout the whole restore process

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#50593]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run br restore to restore a cluster of 110TB

### 2. What did you expect to see? (Required)
Download SST throughput should be use as much of the physical bandwidth as possible, and should be stable during the whole process.

### 3. What did you see instead (Required)
Download SST throughput can reach the disk throughtput limit (1200MB/s) sometime, but it is not stable enough,  there are some downgrade to 1GB or lower.
![image](https://github.com/pingcap/tidb/assets/7403864/01889616-a4e1-4359-8e3b-4c3b1c87a695)
![image](https://github.com/pingcap/tidb/assets/7403864/9ec95f35-265a-4fa3-9331-a34994f7ef62)

### 4. What is your TiDB version? (Required)
v7.6.0

**Comment by 3pointer** [comment]
The issue is suspect it reach the grpc server limitaion: `grpc-concurrent-stream` which means handling the requests throughput in a stream. and the default value is 1024.
