### ISSUE TITLE
add index with global sort report invalid range error

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#50609]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. add index with global sort for a table about 120T data
related issue: #50293 

### 2. What did you expect to see? (Required)
add index success 
### 3. What did you see instead (Required)
![图片](https://github.com/pingcap/tidb/assets/10184437/8f0c2d07-1164-461d-9d74-93074ca11f1b)

### 4. What is your TiDB version? (Required)
master 6db1d6b79c2855cf022f04ced86af3e6bc8b0dcf

**Comment by lance6716** [comment]
this should be fixed after https://github.com/pingcap/tidb/pull/50264 is merged.

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/tidb/pull/50264
