### ISSUE TITLE
br restore very slow (like it hangs) when merging files

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#50613]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Run br restore full to restore a 300 TB cluster backup to a cluster with 100 TiKV  nodes.

### 2. What did you expect to see? (Required)
Restore should succeeds.

### 3. What did you see instead (Required)
Restore is very slow,  it looks like it hangs when merging files. br restore doesn't enter "split and scatter phase" after ~40m of restore.

### 4. What is your TiDB version? (Required)
v7.6.0

**Comment by fubinzh** [comment]
[goroutine.1.txt](https://github.com/pingcap/tidb/files/14000837/goroutine.1.txt)
[goroutine.2.txt](https://github.com/pingcap/tidb/files/14000838/goroutine.2.txt)

**Comment by 3pointer** [comment]
To workaround.  we need skip merge files during restore

use `--merge-region-key-count=1` to make merge skipped.
