### ISSUE TITLE
memory_quota hint should be extracted for Union

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#50626]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create a table like sysbench tables, insert 1M rows.
2. 
```
select /*+ memory_quota(1 MB) */ id from sbtest1 where k > 1 union all select id from sbtest1 where k > 0;
```

### 2. What did you expect to see? (Required)
Memory quota exceeded.

### 3. What did you see instead (Required)
No error.
The following SQL works
```
select /*+ memory_quota(1 MB) */ * from (select /*+ memory_quota(1 MB) */ id from sbtest1 where k > 1 union all select id from sbtest2 where k > 0)
```

### 4. What is your TiDB version? (Required)
From v6.5 to v7.5

**Comment by hawkingrei** [comment]
I think it has been fix by https://github.com/pingcap/tidb/issues/50068 and https://github.com/pingcap/tidb/issues/50067
