### ISSUE TITLE
tidb是信创软件吗

### ISSUE THREAD

**Issue by iFence** [pingcap/tidb#50656]
## Feature Request
我们在做软件的国产化适配，请问Tidb在信创名单里面吗，Tidb算国产化软件吗，做政府项目要求的国产化软件，可以使用Tidb代替nginx吗

**Comment by shawn0915** [comment]
@iFence 感谢关注 TiDB ，欢迎来 [AskTUG](https://asktug.com) 论坛讨论。
关于信创，请参考帖子 https://asktug.com/t/topic/1009987
