### ISSUE TITLE
Support sql_mode 'PAD_CHAR_TO_FULL_LENGTH' when push predicate to kv-layer. 

### ISSUE THREAD

**Issue by spongedu** [pingcap/tidb#5072]
This pr(#5065) support sql_mode 'PAD_CHAR_TO_FULL_LENGTH' in SQL-layer and mock-tikv.  Since some predicates are pushed down to kv-layer, 'PAD_CHAR_TO_FULL_LENGTH' should also be supported in kv-layer

**Comment by morgo** [comment]
@spongedu I believe this issue can be closed?  Thank you!

**Comment by nullnotnil** [comment]
I am going to close this as stale. Thanks!
