### ISSUE TITLE
CPU usage of `handleTableName() -> SchemaByTable()` is high for many small queries when there are a lot of tables

### ISSUE THREAD

**Issue by time-and-fate** [pingcap/tidb#50754]
## Enhancement

In one of our customer scenarios, there are tens or hundreds of thousands of tables in the cluster, and the number of databases is also very large.

In the workload, there are many small OLTP queries (especially there are queries accessing empty tables and many prepare statements), and we noticed high CPU usage, most of which comes from `handleTableName() -> SchemaByTable()` of the `Preprocess` stage when we look into the CPU profile.

![img_v3_027f_fb2879f3-ed2a-4a1d-a45c-36b463b91e3g](https://github.com/pingcap/tidb/assets/25057648/00a4701f-888a-43cf-a1c8-789a2f22d114)

**Comment by tiancaiamao** [comment]
Closed by https://github.com/pingcap/tidb/pull/50917/

After we store the DB ID inside the table, the complexity decrease from O(M*N) to O(M), i.e.

```
for each schema
    for each table 
          if table name == query 
                ...  
```

to 

```
for each schema
       if schema id == query
```
