### ISSUE TITLE
potential data race in UnionExec

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#50846]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://github.com/pingcap/tidb/blob/master/pkg/executor/executor.go#L1946
`maxOpenedChildID` is not protected by mutex.

**Comment by XuHuaiyu** [comment]
Not a bug.

- Before obtaining the value of `e.mu.maxOpenedChildID`, it is necessary to clear `e.resultPool`. [Source](https://github.com/pingcap/tidb/blob/81da4f8811f2fc150ed176d7ef3bcde3ce112d9f/pkg/executor/unionexec/union.go#L215-L218).
- The `resultPool` channel is closed only after all `resultPuller`s exit. [Source](https://github.com/pingcap/tidb/blob/81da4f8811f2fc150ed176d7ef3bcde3ce112d9f/pkg/executor/unionexec/union.go#L88-L91).
- After all `resultPuller`s exit, `maxOpenedChildID` will no longer be written, thus there will be no data race in `UnionExec.Close`. [Source](https://github.com/pingcap/tidb/blob/81da4f8811f2fc150ed176d7ef3bcde3ce112d9f/pkg/executor/unionexec/union.go#L226).
