### ISSUE TITLE
Test cases for MySQL X Protocol

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#5084]
Thanks for @breeswish's help, we could run almost all [MySQL X Protocol official nodejs connector](https://github.com/mysql/mysql-connector-nodejs) test cases.
The current status is:
  694 passing (11s)
  28 pending
  10 failing
and some cases were commented for some reasons.
We need to fix the failing cases and commented cases which marked as "TODO(@jackysp)". @wentaoxu

**Comment by shenli** [comment]
Great!

**Comment by wentaoxu** [comment]
失败用例多为update操作失败
```
db.createCollection("countryinfo")

db.countryinfo.add(
{
    GNP: .6,
    IndepYear: 1967,
    Name: "Sealand",
    _id: "SEA",
    demographics: {
        LifeExpectancy: 79,
        Population: 27
    },
    geography: {
        Continent: "Europe",
        Region: "British Islands",
        SurfaceArea: 193
    },
    government: {
        GovernmentForm: "Monarchy",
        HeadOfState: "Michael Bates"
    }
  }
)

db.countryinfo.modify("_id = 'SEA'").set("demographics", {LifeExpectancy: 78, Population: 28})

翻译后语句为

UPDATE `test`.`countryinfo` SET doc=JSON_SET(doc,'$.demographics',JSON_OBJECT('LifeExpectancy',78,'Population',28)) WHERE (JSON_EXTRACT(doc,'$._id') = 'SEA')'
```
嵌入doc=后语句执行失败并且不报错，需要进一步分析

**Comment by mccxj** [comment]
copy row to newRowData is not deepcopy, it affects JSON object.
https://github.com/pingcap/tidb/blob/9048aa8afa08d5f012d552e982105610a7506544/executor/write.go#L1362

so 'changed' will be false, and then skip update.
https://github.com/pingcap/tidb/blob/9048aa8afa08d5f012d552e982105610a7506544/executor/write.go#L1322

**Comment by wentaoxu** [comment]
@mccxj good job, we will fix this soon.

**Comment by jackysp** [comment]
711 passing (15s)
  28 pending
All passed.
