### ISSUE TITLE
partition can't exchange when table schema is same 

### ISSUE THREAD

**Issue by Damon-Guo** [pingcap/tidb#50906]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. set tidb_enable_clustered_index=off;

2.
CREATE TABLE employees (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30),
    hired DATE NOT NULL DEFAULT '1970-01-01',
    separated DATE DEFAULT '9999-12-31',
    job_code INT,
    store_id INT NOT NULL,
    PRIMARY KEY (`store_id`,`id`)
);

3.
CREATE TABLE employees_p (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30),
    hired DATE NOT NULL DEFAULT '1970-01-01',
    separated DATE DEFAULT '9999-12-31',
    job_code INT,
    store_id INT NOT NULL,
    PRIMARY KEY (`store_id`,`id`)
) 

PARTITION BY RANGE (store_id) (
    PARTITION p0 VALUES LESS THAN (6),
    PARTITION p1 VALUES LESS THAN (11),
    PARTITION p2 VALUES LESS THAN (16),
    PARTITION p3 VALUES LESS THAN (21)
);

4.
alter table employees_p drop  primary key; 
5.
alter table employees_p add primary key (`store_id`,`id`);

6.
ALTER TABLE employees_p EXCHANGE PARTITION p0 WITH TABLE employees;

### 2. What did you expect to see? (Required)
partition exchange  scusessed
### 3. What did you see instead (Required)
 [HY000]: Non matching attribute 'index: PRIMARY' between partition and table
### 4. What is your TiDB version? (Required)

Release Version: v7.6.0

**Comment by jiyfhust** [comment]
This is a limitation of current implemention of `Exchange Partition`.
The `indexId` is logical table level of `Partition Table`, That is every `partition` use the same `indexId` to encode row data. 
So `Exchange partition` do the check if the `indexId` same between partition-table and non-partition-table, is not same, it will report error.

**Comment by Damon-Guo** [comment]
If there is such a restriction, should some documentation be provided?

**Comment by mjonss** [comment]
Exchange partition is based on metadata change internally in TiDB, where a partition can swap place with a table. But the table and partition must have the same structures, including index ids, otherwise it needs to rewrite the indexes, which we do not do in EXCHANGE PARTITION.
The workaround is to create a table exactly as the partitioned table, then remove the partitioning:
```mysql
create table employees like employees_p;
alter table employees remove partitioning;
```

One can check the [`INFORMATION_SCHEMA.TIDB_INDEXES`](https://docs.pingcap.com/tidb/stable/information-schema-tidb-indexes) for the index ids:
```mysql
tidb> alter table t exchange partition p0 with table t2;
ERROR 1731 (HY000): Non matching attribute 'index: PRIMARY' between partition and table
tidb> select * from information_schema.tidb_indexes where table_name in ('t','t2');
+--------------+------------+------------+----------+--------------+-------------+----------+---------------+------------+----------+------------+-----------+-----------+
| TABLE_SCHEMA | TABLE_NAME | NON_UNIQUE | KEY_NAME | SEQ_IN_INDEX | COLUMN_NAME | SUB_PART | INDEX_COMMENT | Expression | INDEX_ID | IS_VISIBLE | CLUSTERED | IS_GLOBAL |
+--------------+------------+------------+----------+--------------+-------------+----------+---------------+------------+----------+------------+-----------+-----------+
| test         | t          |          0 | PRIMARY  |            1 | a           |     NULL |               | NULL       |        2 | YES        | NO        |         0 |
| test         | t2         |          0 | PRIMARY  |            1 | a           |     NULL |               | NULL       |        1 | YES        | NO        |         0 |
+--------------+------------+------------+----------+--------------+-------------+----------+---------------+------------+----------+------------+-----------+-----------+
2 rows in set (0.00 sec)
```

**Comment by mjonss** [comment]
Closing, replacing with a documentation issue instead.
