### ISSUE TITLE
UCP: Support the operation of adding multi-columns 

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#5092]
## Description
Support adding multi-columns in one statement, the syntax as follows:
```
ALTER TABLE tbl_name
    [alter_specification [, alter_specification] ...]

alter_specification:
ADD [COLUMN] (col_name column_definition,...)
```

We can add a new action as `AddColumns` to handle this DDL job. We can achieve this by referring to [AddColumn](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md#add-column-operation) action.

#3627 implementation was basically okay for the current version, if you need it, you can also use it as a reference.

## Score 
* 2996

## Mentor(s)
* @zimulala

Contact the mentors: **#tidb-challenge-program** channel in [TiDB Community](https://join.slack.com/t/tidbcommunity/shared_invite/enQtNzc0MzI4ODExMDc4LWYwYmIzMjZkYzJiNDUxMmZlN2FiMGJkZjAyMzQ5NGU0NGY0NzI3NTYwMjAyNGQ1N2I2ZjAxNzc1OGUwYWM0NzE)  Slack Workspace

## Recommended Skills
* SQL executor
* TiDB DDL
* Golang

## Learning Materials
MySQL's [document]( https://dev.mysql.com/doc/refman/5.7/en/alter-table.html
) for syntax reference.
[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by shenli** [comment]
@breeswish PTAL

**Comment by breeswish** [comment]
related: https://github.com/pingcap/tidb/pull/3627

**Comment by zimulala** [comment]
@morgo I can't close this issue yet. We support composite indexes. But this issue says that it supports adding multiple columns in a statement, for example:
```
alter table tbl add column (c4 int default 1, c5 int);
```

**Comment by zimulala** [comment]
Related to issues：
- [ ] #9384 Support multiple table rename (swap table use case)
- [ ] #3364 Dropping column with index covered isn't fully compatible with mysql

**Comment by gauss1314** [comment]
Hi, @zimulala , I think there are 3 kinds of `add multi-columns`:
1. alter table t add column (b int, c int);
2. alter table t add column b int after a, add column c int after b;
3. alter table t add column (b int, c int), add column d int after b;

This issue only mentioned first one, and I think the lack of the latter two affects usability.
But implementing all three maybe a bit difficult. So what's your suggestion？

**Comment by zimulala** [comment]
These are just the different positions of the columns. We can adjust their position uniformly at the end of processing. The special function is adjustColumnInfoInAddColumn.
This issue itself may be more complicated. If you think it is necessary, we can implement the first type of statement first.
