### ISSUE TITLE
add index command report Duplicate key name 'domains' but success in "admin show ddl jobs"

### ISSUE THREAD

**Issue by seiya-annie** [pingcap/tidb#50981]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. delete all mv index in table a 
2. use multi-schema-change add all mv index back

### 2. What did you expect to see? (Required)
add index command runs successfully
### 3. What did you see instead (Required)
```
mysql> alter table a add index `index1` ((cast(`col1` as char(253) array))), add index `index2` ((cast(`col2` as char(32) array))), add index `index3` ((cast(`col3` as unsigned array))), add index `index4` ((cast(`col4` as char(1000) array))), add index `index5` ((cast(`col5` as unsigned array))), add index `index6` ((cast(`col6` as char(1000) array)),`point_of_sale_country`);

ERROR 2013 (HY000): Lost connection to MySQL server during query
No connection. Trying to reconnect...
Connection id:    434117668
Current database: test

ERROR 1061 (42000): Duplicate key name 'domains'; a background job is trying to add the same index, please check by `ADMIN SHOW DDL JOBS`
mysql> 
```
![20240205-151926](https://github.com/pingcap/tidb/assets/53471087/542734f1-ba7a-43d0-8f11-4422c324bc37)

### 4. What is your TiDB version? (Required)

7.6.0

**Comment by tangenta** [comment]
This problem is caused by the unstable connection of mysql-client. It will resend the SQL statement again after reconnecting, thus the error is expected.
