### ISSUE TITLE
Configurable resolution for tidb_low_resolution_tso

### ISSUE THREAD

**Issue by ari-e** [pingcap/tidb#51081]
## Enhancement

The session variable [tidb_low_resolution_tso](https://docs.pingcap.com/tidb/v4.0/system-variables#tidb_low_resolution_tso) helps read-heavy workloads. From the docs:
> After this feature is enabled, new transactions use a timestamp updated every 2 seconds to read data. The main applicable scenario is to reduce the overhead of acquiring TSO for small read-only transactions when reading old data is acceptable.

This is a great feature but the hardcoded 2 second interval within which to reuse timestamps for read operations makes it inflexible. Many use cases may want to trade off staleness with latency by using a low resolution timestamp, but need to control that staleness bound more closely.

Making this resolution configurable within some reasonable range, say [100ms, 10s] with a default of 2s makes this feature more powerful for users. A name proposal (up for discussion) for this new configuration is `tidb_low_resolution_tso_update_interval` and of course it would only be meaningful if `tidb_low_resolution_tso` is enabled.

Note that unlike `tidb_low_resolution_tso` which is SESSION scoped (because writes fail when it is enabled), the new configuration `tidb_low_resolution_tso_update_interval` should be INSTANCE | GLOBAL scoped, otherwise different sessions on the same node using different update intervals will create a lot of complexity and network calls to PD to get timestamps.

In addition to changes to tidb core to define and plumb the system variable, this will also require modifying the tikv go client since that is where this update interval logic ultimately converts into an rpc to PD. https://github.com/tikv/client-go/blob/cfee5d73dda3c5410a6d49f3e77074ed9d170375/tikv/kv.go#L102-L103

**Comment by joey-yez** [comment]
I think this is a good idea. This improve the performance of heavy-read workload.

**Comment by joey-yez** [comment]
We will plan to add this new variable as GLOBAL scoped.
