### ISSUE TITLE
9500, HY000, transaction too large, len:300001 

### ISSUE THREAD

**Issue by zzx8170** [pingcap/tidb#5114]
Please answer these questions before submitting your issue. Thanks!

版本：tidb1.0 
问题：mysql_tpcc工具load数据时，出现如下报错：

Loading Warehouse
Loading Stock Wid=1
.................................................. 5000
.................................................. 10000
.................................................. 15000
.................................................. 20000
.................................................. 25000
.................................................. 30000
.................................................. 35000
.................................................. 40000
.................................................. 45000
.................................................. 50000
.................................................. 55000
.................................................. 60000
.................................................. 65000
.................................................. 70000
.................................................. 75000
.................................................. 80000
.................................................. 85000
.................................................. 90000
.................................................. 95000
.................................................
9500, HY000, transaction too large, len:300001
Retrying ....
Loading Stock Wid=1       

循环报错，如何解决？

**Comment by shenli** [comment]
@zzx8170 Please refer to the FAQ: https://github.com/pingcap/docs/blob/master/FAQ.md#the-error-message-transaction-too-large-is-displayed
