### ISSUE TITLE
pitr: support log backup to s3 when object lock is enabled

### ISSUE THREAD

**Issue by BornChanger** [pingcap/tidb#51184]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Currently, full backup supports s3 object lock but log backup does not.

**Describe the feature you'd like:**

We need to also enable object lock support for log backup.

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by RidRisR** [comment]
Note: Only enable Object Lock will not trigger this problem. There is no special requirement of Object Lock.
However, the option `retention time` requires a header of content-MD5. See https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObject.html
