### ISSUE TITLE
wrong partition location for key partition 

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#51196]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `t3ca77250` (
  `col_80` json NOT NULL,
  `col_81` char(170) NOT NULL,
  `col_82` varchar(141) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `col_83` binary(16) DEFAULT 'PUuuyJtiJ\0\0\0\0\0\0\0',
  `col_84` int(11) NOT NULL,
  `col_85` mediumint(8) unsigned NOT NULL,
  `col_86` varbinary(53) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY KEY (`col_82`) PARTITIONS 7;

INSERT INTO `t3ca77250` VALUES('[0.878261783349996, 0.2244549974600441, 0.9369725465676337, 0.2906406947430319]','H41eHh1qpKYI+!P4Vd',NULL,x'57344859484c353d6155616f61280000',-1263051974,8388607,x'6325305a24'),('[0.16574151187251007, 0.5036156268118512, 0.9463938199173461, 0.3622145201911983]','H41eHh1qpKYI+!P4Vd',NULL,x'79624836000000000000000000000000',-1,1,x'2153783456504b4e3136447a3645'),('[0.3710246774376661, 0.004921654278889464, 0.1621897717575254, 0.5752233976960797, 0.5184942093243686]','%&tV394jQK','5v!S=BU$a0G4',NULL,-456381384,8223098,x'5732352937397050635e35486461'),('[0.9418036152287022, 0.06012240186083453, 0.21730868547592735, 0.7795473686455742]','U6%C#n*fTRcMO','2!&2',x'4f265435256852460000000000000000',1,2165113,x'592d21376c366c6e2b79215877'),('[0.8287632736417652, 0.5766431067703843]','~x(0RuiAt-G','oaA$gUJNk_thPj',x'715142694a2d475f7974615f38730000',174891391,9880829,x'332a7e6e6c415f66494a39365841345f28'),('[0.8785381220987197, 0.2760331121689333, 0.008128528331692695, 0.6206878702684281, 0.8763262881530381]','b)L&dj','Y=zWwt^',x'45424a376c496d5e6900000000000000',-1376643814,14767190,x'674d357937334624424b6f5656773d7a7121'),('[0.39012198530977227, 0.8656907669450639, 0.8196958826914118, 0.07312680711527268]','B(','~oI7(SN_U^ozoOP9',x'00000000000000000000000000000000',2087924880,16027406,x'7373344756'),('[0.5044549524283306, 0.327803622038757, 0.03855507522153538, 0.19420066928934293, 0.4996972303791596]','nytelnRb7',NULL,x'36297569433637000000000000000000',2147483647,8310890,x'307e58413839537e3348614723'),('[0.2825478221724143, 0.6242065198162221, 0.9517963940992751]','Q2qwaMPz-RFz!9#Hdt','Cdh*qvs',x'69296c4d796523655353590000000000',-1242527528,11170346,x'476765'),('[0.09804424396900342, 0.06820204948438345, 0.09288540101064473, 0.5009178126831317]','JRryeo^i8&z5',NULL,x'73337862000000000000000000000000',-1540775913,15346558,x'386143356862583959'),('[0.6253123174462912]','HjhV^','',x'6235765f4d64363051356b3823740000',-32014956,8256836,x'427e'),('[0.708039842406214, 0.9861019076170222]','+O8vy83Mm^FW%B%w','9=t!8',x'64367245234d51383800000000000000',-1015587280,13183530,x'645a256e62'),('[0.3042667341252692, 0.9450924016268359, 0.3243880918032669, 0.24747106106423641, 0.9939030724501318]','FmQQd^x','j',x'744d2a4b6b535635312d333644752d00',-2047116480,14068102,x'4b51633923'),('[0.23161491166841233]','i','bSF9j!0',x'6b712d37595356323550382654000000',1131884567,8388607,x'3065674626'),('[0.8275548942226252, 0.46119964689772597, 0.6780977409561638, 0.006258605476976181]','O^q_Qar^','_d',x'3d7a4c65353300000000000000000000',-1122139453,10081846,x'2d716a56'),('[0.3143969231034079, 0.08334939764416162, 0.20740106915909898]','CZU9L','nRF%5PBl0CF',NULL,-161351751,3092306,x'212452252643'),('[0.7308842564776512, 0.8265545096303557, 0.8451431855101331]','NNOjr1#LF8^l@','f-z26~J6JZJJCTv',x'494f7146794a744754255a6f78730000',-1497529527,14624906,x'674233'),('[0.28567156217960143, 0.04181358297402761, 0.5701680683793269]','IRy','prenv@c^RUfV',x'506c5e296b345e7140563d3300000000',491805847,16309816,x'32'),('[0.879735546293783, 0.9304466200177341, 0.10028461822491676]','hCPF','h2',x'592b56747348616f3600000000000000',623772928,2,x'58627372554c2d633574'),('[0.2040910671767843, 0.7010911602189376, 0.31035574623804496, 0.026200601614985868, 0.21677616414590256]','qh','vx9~5qQJavrFWT#~V',x'79410000000000000000000000000000',-1611079873,11921291,x'6f427a79537a21642178566f284c74'),('[0.5284472899989369, 0.5406561101393981, 0.635337876757992, 0.15517585329844766]','FZk&S8RX5h@Ua','RP@Fjly',x'467e7041510000000000000000000000',-666225735,15751742,x'5a3625656f6e344662554c6e'),('[0.7889308215260479]','_ey$yAK-66~h(HS!&rQ','fzy-w!',x'54440000000000000000000000000000',468389128,12019668,x'5e5331635a434e5057565f'),('[0.4316671978421498, 0.31838422387659265, 0.8794942780150892, 0.17653288856974778, 0.34263066500004585]','OCX4!Ao-o-1Yh_','s5%!IR',x'256c3554732d76404a66000000000000',895256415,11336472,x'466d'),('[0.8270655369988628]','4(k-FZ8wtw','9aB5i~_vYl^0ncpG',x'76260000000000000000000000000000',521245853,0,x'4e6d6e'),('[0.7107887299599154, 0.5403132824776644]','&T!qU0a3','p#K%SS95u0W&BQFX*',x'58632940740000000000000000000000',42727023,11257544,NULL),('[0.8969031367461618, 0.2993218960335018, 0.6227127663810389, 0.49765015939958523]',')vp6phl%E','l!_AK1Koo_~AX%v5L',x'6c6b3757755a364248466e4900000000',747075270,3058697,x''),('[0.9294067934782198, 0.46077214267432237, 0.7856974584533691, 0.4083299512873445]','&^N~^uXo1o&','1gBcsMAiH@7',x'735a7e672a4d482d5e285f0000000000',1239384952,8184407,x''),('[0.5234966507551178, 0.34855547079173127, 0.4869580467209277]','~+_exmhSFXky#Sz4i8#','O4',x'6f2d6543680000000000000000000000',1722991448,8388608,x'72443d4b53524634374b323946726a482a'),('[0.18174288212967143]','','BFKG',x'33662a532b546970356c2a3962547200',1859223645,14159067,x'462d5f73242d76467639783d38715a28396277'),('[0.16902040723785028, 0.8725903503031094, 0.030093089963406906, 0.44440279138373845, 0.49057231568564535]','l^19z1T2d_FG-','mqjCEMAV$pzPK',x'4373756b640000000000000000000000',-1631832590,16116145,x'423432'),('[0.1061003766143535]','g9mY@Qu^q%eg-zH#jy','&0U^8TL',x'38380000000000000000000000000000',-109994281,16369355,x'654a7a'),('[0.06350839923925998, 0.5944690025906874, 0.8957635171432455]','Ag8=3W&=DXT','f3NKs',x'54000000000000000000000000000000',1565984445,9484134,x'5a55646570285a4d637a3851302d');

SELECT 1 FROM `t3ca77250`  WHERE `t3ca77250`.`col_82` = 'f3NKs';
```

### 2. What did you expect to see? (Required)
One row
### 3. What did you see instead (Required)
``` SQL
mysql> SELECT 1 FROM `t3ca77250`  WHERE `t3ca77250`.`col_82` = 'f3NKs';
Empty set, 1 warning (0.01 sec)
```
### 4. What is your TiDB version? (Required)
1fc92b32b05e3f2f04b9d321a9e224b9125a4a82

**Comment by jiyfhust** [comment]
Seems fix by #51363, with this pr, for select query it no longer convert to binary collation, it will be same with dml.

**Comment by kennedy8312** [comment]
Regression Analysis
PR Caused this regression: https://github.com/pingcap/tidb/pull/48522

**Comment by kennedy8312** [comment]
Regression Analysis
Version v5.4.0 : Success
Version v6.0.0 : Success
Version v6.1.0 : Success
Version v6.2.0 : Success
Version v6.3.0 : Success
Version v6.4.0 : Success
Version v6.5.0 : Success
Version v6.6.0 : Success
Version v7.0.0 : Success
Version v7.1.0 : Success
Version v7.2.0 : Success
Version v7.3.0 : Success
Version v7.4.0 : Success
Version v7.5.0 : Success
Version v7.6.0 : Failure
Version nightly : Success

-----------------Regression Test Result on v7.5.0-----------------
Server on v7.5.0 started.
Validation passed. v7.5.0 is a good label
-----------------Test Case-----------------
mysql -h 127.0.0.1 -P 4000 -u root -D test --local-infile=true < issue51196_testcase.sql
issue51196_testcase.sql: 
drop table if exists `t3ca77250`;
CREATE TABLE `t3ca77250` (
  `col_80` json NOT NULL,
  `col_81` char(170) NOT NULL,
  `col_82` varchar(141) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `col_83` binary(16) DEFAULT 'PUuuyJtiJ\0\0\0\0\0\0\0',
  `col_84` int(11) NOT NULL,
  `col_85` mediumint(8) unsigned NOT NULL,
  `col_86` varbinary(53) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY KEY (`col_82`) PARTITIONS 7;

INSERT INTO `t3ca77250` VALUES('[0.878261783349996, 0.2244549974600441, 0.9369725465676337, 0.2906406947430319]','H41eHh1qpKYI+!P4Vd',NULL,x'57344859484c353d6155616f61280000',-1263051974,8388607,x'6325305a24'),('[0.16574151187251007, 0.5036156268118512, 0.9463938199173461, 0.3622145201911983]','H41eHh1qpKYI+!P4Vd',NULL,x'79624836000000000000000000000000',-1,1,x'2153783456504b4e3136447a3645'),('[0.3710246774376661, 0.004921654278889464, 0.1621897717575254, 0.5752233976960797, 0.5184942093243686]','%&tV394jQK','5v!S=BU$a0G4',NULL,-456381384,8223098,x'5732352937397050635e35486461'),('[0.9418036152287022, 0.06012240186083453, 0.21730868547592735, 0.7795473686455742]','U6%C#n*fTRcMO','2!&2',x'4f265435256852460000000000000000',1,2165113,x'592d21376c366c6e2b79215877'),('[0.8287632736417652, 0.5766431067703843]','~x(0RuiAt-G','oaA$gUJNk_thPj',x'715142694a2d475f7974615f38730000',174891391,9880829,x'332a7e6e6c415f66494a39365841345f28'),('[0.8785381220987197, 0.2760331121689333, 0.008128528331692695, 0.6206878702684281, 0.8763262881530381]','b)L&dj','Y=zWwt^',x'45424a376c496d5e6900000000000000',-1376643814,14767190,x'674d357937334624424b6f5656773d7a7121'),('[0.39012198530977227, 0.8656907669450639, 0.8196958826914118, 0.07312680711527268]','B(','~oI7(SN_U^ozoOP9',x'00000000000000000000000000000000',2087924880,16027406,x'7373344756'),('[0.5044549524283306, 0.327803622038757, 0.03855507522153538, 0.19420066928934293, 0.4996972303791596]','nytelnRb7',NULL,x'36297569433637000000000000000000',2147483647,8310890,x'307e58413839537e3348614723'),('[0.2825478221724143, 0.6242065198162221, 0.9517963940992751]','Q2qwaMPz-RFz!9#Hdt','Cdh*qvs',x'69296c4d796523655353590000000000',-1242527528,11170346,x'476765'),('[0.09804424396900342, 0.06820204948438345, 0.09288540101064473, 0.5009178126831317]','JRryeo^i8&z5',NULL,x'73337862000000000000000000000000',-1540775913,15346558,x'386143356862583959'),('[0.6253123174462912]','HjhV^','',x'6235765f4d64363051356b3823740000',-32014956,8256836,x'427e'),('[0.708039842406214, 0.9861019076170222]','+O8vy83Mm^FW%B%w','9=t!8',x'64367245234d51383800000000000000',-1015587280,13183530,x'645a256e62'),('[0.3042667341252692, 0.9450924016268359, 0.3243880918032669, 0.24747106106423641, 0.9939030724501318]','FmQQd^x','j',x'744d2a4b6b535635312d333644752d00',-2047116480,14068102,x'4b51633923'),('[0.23161491166841233]','i','bSF9j!0',x'6b712d37595356323550382654000000',1131884567,8388607,x'3065674626'),('[0.8275548942226252, 0.46119964689772597, 0.6780977409561638, 0.006258605476976181]','O^q_Qar^','_d',x'3d7a4c65353300000000000000000000',-1122139453,10081846,x'2d716a56'),('[0.3143969231034079, 0.08334939764416162, 0.20740106915909898]','CZU9L','nRF%5PBl0CF',NULL,-161351751,3092306,x'212452252643'),('[0.7308842564776512, 0.8265545096303557, 0.8451431855101331]','NNOjr1#LF8^l@','f-z26~J6JZJJCTv',x'494f7146794a744754255a6f78730000',-1497529527,14624906,x'674233'),('[0.28567156217960143, 0.04181358297402761, 0.5701680683793269]','IRy','prenv@c^RUfV',x'506c5e296b345e7140563d3300000000',491805847,16309816,x'32'),('[0.879735546293783, 0.9304466200177341, 0.10028461822491676]','hCPF','h2',x'592b56747348616f3600000000000000',623772928,2,x'58627372554c2d633574'),('[0.2040910671767843, 0.7010911602189376, 0.31035574623804496, 0.026200601614985868, 0.21677616414590256]','qh','vx9~5qQJavrFWT#~V',x'79410000000000000000000000000000',-1611079873,11921291,x'6f427a79537a21642178566f284c74'),('[0.5284472899989369, 0.5406561101393981, 0.635337876757992, 0.15517585329844766]','FZk&S8RX5h@Ua','RP@Fjly',x'467e7041510000000000000000000000',-666225735,15751742,x'5a3625656f6e344662554c6e'),('[0.7889308215260479]','_ey$yAK-66~h(HS!&rQ','fzy-w!',x'54440000000000000000000000000000',468389128,12019668,x'5e5331635a434e5057565f'),('[0.4316671978421498, 0.31838422387659265, 0.8794942780150892, 0.17653288856974778, 0.34263066500004585]','OCX4!Ao-o-1Yh_','s5%!IR',x'256c3554732d76404a66000000000000',895256415,11336472,x'466d'),('[0.8270655369988628]','4(k-FZ8wtw','9aB5i~_vYl^0ncpG',x'76260000000000000000000000000000',521245853,0,x'4e6d6e'),('[0.7107887299599154, 0.5403132824776644]','&T!qU0a3','p#K%SS95u0W&BQFX*',x'58632940740000000000000000000000',42727023,11257544,NULL),('[0.8969031367461618, 0.2993218960335018, 0.6227127663810389, 0.49765015939958523]',')vp6phl%E','l!_AK1Koo_~AX%v5L',x'6c6b3757755a364248466e4900000000',747075270,3058697,x''),('[0.9294067934782198, 0.46077214267432237, 0.7856974584533691, 0.4083299512873445]','&^N~^uXo1o&','1gBcsMAiH@7',x'735a7e672a4d482d5e285f0000000000',1239384952,8184407,x''),('[0.5234966507551178, 0.34855547079173127, 0.4869580467209277]','~+_exmhSFXky#Sz4i8#','O4',x'6f2d6543680000000000000000000000',1722991448,8388608,x'72443d4b53524634374b323946726a482a'),('[0.18174288212967143]','','BFKG',x'33662a532b546970356c2a3962547200',1859223645,14159067,x'462d5f73242d76467639783d38715a28396277'),('[0.16902040723785028, 0.8725903503031094, 0.030093089963406906, 0.44440279138373845, 0.49057231568564535]','l^19z1T2d_FG-','mqjCEMAV$pzPK',x'4373756b640000000000000000000000',-1631832590,16116145,x'423432'),('[0.1061003766143535]','g9mY@Qu^q%eg-zH#jy','&0U^8TL',x'38380000000000000000000000000000',-109994281,16369355,x'654a7a'),('[0.06350839923925998, 0.5944690025906874, 0.8957635171432455]','Ag8=3W&=DXT','f3NKs',x'54000000000000000000000000000000',1565984445,9484134,x'5a55646570285a4d637a3851302d');

SELECT 1 FROM `t3ca77250`  WHERE `t3ca77250`.`col_82` = 'f3NKs';
-----------------Test Result-----------------
Result : 
1
1
-----------------TiDB Version-----------------
tidb_version()
Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:41:10
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

-----------------End of regression test on v7.5.0-----------------

**Comment by kennedy8312** [comment]
-----------------Regression Test Result on v7.6.0-----------------
Server on v7.6.0 started.
Validation failed at run 1. v7.6.0 is a bad label.
Expected: 
1
1
Actual: 

-----------------Test Case-----------------
mysql -h 127.0.0.1 -P 4000 -u root -D test --local-infile=true < issue51196_testcase.sql
issue51196_testcase.sql: 
drop table if exists `t3ca77250`;
CREATE TABLE `t3ca77250` (
  `col_80` json NOT NULL,
  `col_81` char(170) NOT NULL,
  `col_82` varchar(141) COLLATE utf8mb4_general_ci DEFAULT NULL,
  `col_83` binary(16) DEFAULT 'PUuuyJtiJ\0\0\0\0\0\0\0',
  `col_84` int(11) NOT NULL,
  `col_85` mediumint(8) unsigned NOT NULL,
  `col_86` varbinary(53) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
PARTITION BY KEY (`col_82`) PARTITIONS 7;

INSERT INTO `t3ca77250` VALUES('[0.878261783349996, 0.2244549974600441, 0.9369725465676337, 0.2906406947430319]','H41eHh1qpKYI+!P4Vd',NULL,x'57344859484c353d6155616f61280000',-1263051974,8388607,x'6325305a24'),('[0.16574151187251007, 0.5036156268118512, 0.9463938199173461, 0.3622145201911983]','H41eHh1qpKYI+!P4Vd',NULL,x'79624836000000000000000000000000',-1,1,x'2153783456504b4e3136447a3645'),('[0.3710246774376661, 0.004921654278889464, 0.1621897717575254, 0.5752233976960797, 0.5184942093243686]','%&tV394jQK','5v!S=BU$a0G4',NULL,-456381384,8223098,x'5732352937397050635e35486461'),('[0.9418036152287022, 0.06012240186083453, 0.21730868547592735, 0.7795473686455742]','U6%C#n*fTRcMO','2!&2',x'4f265435256852460000000000000000',1,2165113,x'592d21376c366c6e2b79215877'),('[0.8287632736417652, 0.5766431067703843]','~x(0RuiAt-G','oaA$gUJNk_thPj',x'715142694a2d475f7974615f38730000',174891391,9880829,x'332a7e6e6c415f66494a39365841345f28'),('[0.8785381220987197, 0.2760331121689333, 0.008128528331692695, 0.6206878702684281, 0.8763262881530381]','b)L&dj','Y=zWwt^',x'45424a376c496d5e6900000000000000',-1376643814,14767190,x'674d357937334624424b6f5656773d7a7121'),('[0.39012198530977227, 0.8656907669450639, 0.8196958826914118, 0.07312680711527268]','B(','~oI7(SN_U^ozoOP9',x'00000000000000000000000000000000',2087924880,16027406,x'7373344756'),('[0.5044549524283306, 0.327803622038757, 0.03855507522153538, 0.19420066928934293, 0.4996972303791596]','nytelnRb7',NULL,x'36297569433637000000000000000000',2147483647,8310890,x'307e58413839537e3348614723'),('[0.2825478221724143, 0.6242065198162221, 0.9517963940992751]','Q2qwaMPz-RFz!9#Hdt','Cdh*qvs',x'69296c4d796523655353590000000000',-1242527528,11170346,x'476765'),('[0.09804424396900342, 0.06820204948438345, 0.09288540101064473, 0.5009178126831317]','JRryeo^i8&z5',NULL,x'73337862000000000000000000000000',-1540775913,15346558,x'386143356862583959'),('[0.6253123174462912]','HjhV^','',x'6235765f4d64363051356b3823740000',-32014956,8256836,x'427e'),('[0.708039842406214, 0.9861019076170222]','+O8vy83Mm^FW%B%w','9=t!8',x'64367245234d51383800000000000000',-1015587280,13183530,x'645a256e62'),('[0.3042667341252692, 0.9450924016268359, 0.3243880918032669, 0.24747106106423641, 0.9939030724501318]','FmQQd^x','j',x'744d2a4b6b535635312d333644752d00',-2047116480,14068102,x'4b51633923'),('[0.23161491166841233]','i','bSF9j!0',x'6b712d37595356323550382654000000',1131884567,8388607,x'3065674626'),('[0.8275548942226252, 0.46119964689772597, 0.6780977409561638, 0.006258605476976181]','O^q_Qar^','_d',x'3d7a4c65353300000000000000000000',-1122139453,10081846,x'2d716a56'),('[0.3143969231034079, 0.08334939764416162, 0.20740106915909898]','CZU9L','nRF%5PBl0CF',NULL,-161351751,3092306,x'212452252643'),('[0.7308842564776512, 0.8265545096303557, 0.8451431855101331]','NNOjr1#LF8^l@','f-z26~J6JZJJCTv',x'494f7146794a744754255a6f78730000',-1497529527,14624906,x'674233'),('[0.28567156217960143, 0.04181358297402761, 0.5701680683793269]','IRy','prenv@c^RUfV',x'506c5e296b345e7140563d3300000000',491805847,16309816,x'32'),('[0.879735546293783, 0.9304466200177341, 0.10028461822491676]','hCPF','h2',x'592b56747348616f3600000000000000',623772928,2,x'58627372554c2d633574'),('[0.2040910671767843, 0.7010911602189376, 0.31035574623804496, 0.026200601614985868, 0.21677616414590256]','qh','vx9~5qQJavrFWT#~V',x'79410000000000000000000000000000',-1611079873,11921291,x'6f427a79537a21642178566f284c74'),('[0.5284472899989369, 0.5406561101393981, 0.635337876757992, 0.15517585329844766]','FZk&S8RX5h@Ua','RP@Fjly',x'467e7041510000000000000000000000',-666225735,15751742,x'5a3625656f6e344662554c6e'),('[0.7889308215260479]','_ey$yAK-66~h(HS!&rQ','fzy-w!',x'54440000000000000000000000000000',468389128,12019668,x'5e5331635a434e5057565f'),('[0.4316671978421498, 0.31838422387659265, 0.8794942780150892, 0.17653288856974778, 0.34263066500004585]','OCX4!Ao-o-1Yh_','s5%!IR',x'256c3554732d76404a66000000000000',895256415,11336472,x'466d'),('[0.8270655369988628]','4(k-FZ8wtw','9aB5i~_vYl^0ncpG',x'76260000000000000000000000000000',521245853,0,x'4e6d6e'),('[0.7107887299599154, 0.5403132824776644]','&T!qU0a3','p#K%SS95u0W&BQFX*',x'58632940740000000000000000000000',42727023,11257544,NULL),('[0.8969031367461618, 0.2993218960335018, 0.6227127663810389, 0.49765015939958523]',')vp6phl%E','l!_AK1Koo_~AX%v5L',x'6c6b3757755a364248466e4900000000',747075270,3058697,x''),('[0.9294067934782198, 0.46077214267432237, 0.7856974584533691, 0.4083299512873445]','&^N~^uXo1o&','1gBcsMAiH@7',x'735a7e672a4d482d5e285f0000000000',1239384952,8184407,x''),('[0.5234966507551178, 0.34855547079173127, 0.4869580467209277]','~+_exmhSFXky#Sz4i8#','O4',x'6f2d6543680000000000000000000000',1722991448,8388608,x'72443d4b53524634374b323946726a482a'),('[0.18174288212967143]','','BFKG',x'33662a532b546970356c2a3962547200',1859223645,14159067,x'462d5f73242d76467639783d38715a28396277'),('[0.16902040723785028, 0.8725903503031094, 0.030093089963406906, 0.44440279138373845, 0.49057231568564535]','l^19z1T2d_FG-','mqjCEMAV$pzPK',x'4373756b640000000000000000000000',-1631832590,16116145,x'423432'),('[0.1061003766143535]','g9mY@Qu^q%eg-zH#jy','&0U^8TL',x'38380000000000000000000000000000',-109994281,16369355,x'654a7a'),('[0.06350839923925998, 0.5944690025906874, 0.8957635171432455]','Ag8=3W&=DXT','f3NKs',x'54000000000000000000000000000000',1565984445,9484134,x'5a55646570285a4d637a3851302d');

SELECT 1 FROM `t3ca77250`  WHERE `t3ca77250`.`col_82` = 'f3NKs';
-----------------Test Result-----------------
Result : 

-----------------TiDB Version-----------------
tidb_version()
Release Version: v7.6.0
Edition: Community
Git Commit Hash: 52794d985ba6325d75a714d4eaa0838d59425eb6
Git Branch: heads/refs/tags/v7.6.0
UTC Build Time: 2024-01-22 14:13:53
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

-----------------End of regression test on v7.6.0-----------------

**Comment by kennedy8312** [comment]
Regression Analysis
Commit 7c3746685d1fa242eac7cbf5653497f954a1ca73 : Success
Commit 0c7659c1907dd033af8b13b15eee1960a0d9ee79 : Failure
Commit e053c27f068bb9498b312dd6e4d95695824696a2 : Failure
