### ISSUE TITLE
upgrade will be hang since `create database sys` ddl job has been paused

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#51220]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. upgrade 7.5.0 cluster to nightly 

### 2. What did you expect to see? (Required)
upgrade success 
### 3. What did you see instead (Required)
upgrade has been hang because the `CREATE DATABASE IF NOT EXISTS sys` ddl job was paused.
```sql
MySQL [(none)]> admin show ddl jobs;
+--------+---------+---------------------------------+---------------------------+----------------------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+--------+
| JOB_ID | DB_NAME | TABLE_NAME                      | JOB_TYPE                  | SCHEMA_STATE         | SCHEMA_ID | TABLE_ID        | ROW_COUNT | CREATE_TIME         | START_TIME          | END_TIME            | STATE  |
+--------+---------+---------------------------------+---------------------------+----------------------+-----------+-----------------+-----------+---------------------+---------------------+---------------------+--------+
|    257 | sbtest1 | sbtest3                         | add index /* txn-merge */ | write reorganization |       102 |             228 |   4253616 | 2024-02-21 14:13:04 | 2024-02-21 14:13:40 | NULL                | paused |
|    258 | sbtest1 | sbtest2                         | add index                 | none                 |       102 |             232 |         0 | 2024-02-21 14:13:04 | 2024-02-21 14:16:43 | NULL                | paused |
|    259 | sbtest1 | sbtest4                         | add index                 | none                 |       102 |             225 |         0 | 2024-02-21 14:13:04 | 2024-02-21 14:16:43 | NULL                | paused |
|    284 | sys     |                                 | create schema             | none                 |       283 |               0 |         0 | 2024-02-21 14:16:56 | 2024-02-21 14:16:57 | NULL                | paused |
```
### 4. What is your TiDB version? (Required)
master 11f716e206c30d5acca83710c7292637c2f6cf67

**Comment by YangKeao** [comment]
It's a problem for pausing DDL queries during rolling upgrade. The old version of TiDB uses a too strict way to detect whether a DDL is submitted by internal session:

```go
func (d *ddl) processJobDuringUpgrade(sess *sess.Session, job *model.Job) (isRunnable bool, err error) {
	if d.stateSyncer.IsUpgradingState() {
		if job.IsPaused() {
			return false, nil
		}
		// We need to turn the 'pausing' job to be 'paused' in ddl worker,
		// and stop the reorganization workers
		if job.IsPausing() || hasSysDB(job) {
			return true, nil
		}
		var errs []error
		// During binary upgrade, pause all running DDL jobs
		errs, err = PauseJobsBySystem(sess.Session(), []int64{job.ID})
		if len(errs) > 0 && errs[0] != nil {
			err = errs[0]
		}
...
	}
}
```

The function `hasSysDB` will only return `true` when the schema is `mysql` in old version (and it also includes `sys` in the new version). During the rolling upgrade, the old version TiDB in the cluster will think `create database sys` is a user DDL and pause it, therefore blocking the upgrade.

**Comment by YangKeao** [comment]
After discussing with @zimulala, one possible solution is postponing the DDL after upgradation:

1. Don't run `sys` related DDL, if we found `d.stateSyncer.IsUpgradingState()`.
2. Run `sys` related DDL in `ClusterUpgradeHandler.FinishUpgrade`.

It cannot solve the problems in the future, especially when we are going to read/write `sys` schema (e.g. create more tables/views)... We'll need to get two different places to run upgrading DDLs, which is an extra burden in coding...

I think it's also related with the product life cycle. Need to think twice before fixing this problem.

**Comment by bb7133** [comment]
IMO we have 2 additional options:

1. Provide the patch for `hasSysDB` and backport it to patch releases, then the users can only make rolling upgrade to a newer version from those patch releases. For example, if we have this patch in v7.1.2, users who want to upgrade to v8.1.0 cannot make rolling upgrade on clusters with version >=v7.1.2. However, although we had similar [limitations in the past](https://docs.pingcap.com/tidb/v4.0/upgrade-tidb-using-tiup), those limitations are something we need to try avoiding. 
2. For the upgraded clusters, we do not provide `sys` schema for now. IMO this is acceptable because the tables in this schema are views, users can manually create them.

**Comment by bb7133** [comment]
> For the upgraded clusters, we do not provide sys schema for now. IMO this is acceptable because the tables in this schema are views, users can manually create them.
