### ISSUE TITLE
TiDB OOM because of querying information_schema.tables and information_schema.statistics

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#51260]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
we need add mem tracker for memTableRetriever

![image](https://github.com/pingcap/tidb/assets/7493273/84d3714b-fcd2-40bc-ab64-fc8ff824e6af)

### 4. What is your TiDB version? (Required)
v7.5.0

**Comment by ywqzzy** [comment]
How many tables?

**Comment by guo-shaoge** [comment]
> How many tables? Does the sql have filters？

About 30K tables
