### ISSUE TITLE
flaky case TestErrorBind

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#51288]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/4227/nodes/63/steps/69/log/?start=0
```
    bind_test.go:476: 
        	Error Trace:	pkg/bindinfo/tests/bind_test.go:476
        	Error:      	Not equal: 
        	            	expected: 0
        	            	actual  : 1
        	Test:       	TestErrorBind
```

**Comment by qw4990** [comment]
Can't reproduce, this issue might have been fixed by some PR. Please contact me if it occurs again.
