### ISSUE TITLE
flaky case TestPhysicalTableScanExtractCorrelatedCols

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#51289]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
https://do.pingcap.net/jenkins/blue/rest/organizations/jenkins/pipelines/pingcap/pipelines/tidb/pipelines/ghpr_unit_test/runs/4227/nodes/63/steps/69/log/?start=0
```
    physical_plan_test.go:495: 
        	Error Trace:	pkg/planner/core/physical_plan_test.go:495
        	Error:      	Not equal: 
        	            	expected: 1
        	            	actual  : 0
        	Test:       	TestPhysicalTableScanExtractCorrelatedCols
```

### 4. What is your TiDB version? (Required)
master

**Comment by zimulala** [comment]
Reproduce: https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/4257/pipeline
