### ISSUE TITLE
log densensitation

### ISSUE THREAD

**Issue by xhebox** [pingcap/tidb#51306]
## Main tasks

Mark sensitive data with `‹..›` when `tidb_redact_log=marker`, `‹` will be escaped to `‹‹`, similar to `›`. This is a new feature:

1. TiDB will produce logs with sensitive data marked with `<>`
2. Cloud or OP users could desensitive logs on their own by tidb-server sub commands or whatever.

It is basically because that users want the original log, and we (primarily tech supports) should only see desensitived logs.

- [x] #51307
- [x] #51588
- [x] #51310
- [x] #51557
- [x] #51641
- [x] #51717 
- [x] change docs https://github.com/pingcap/docs-cn/pull/16769
- [x] #51758

## tests

- [ ] test https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/5435/pipeline https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/51642/fast_test_tiprow/1767072980048809984
- [x] #52157 
- [x] #52158
- [x] #52359 #52364

**Comment by JaySon-Huang** [comment]
@xhebox  should we also update these related docs?

* https://github.com/pingcap/docs-cn/blob/1d6358a45add3e7339ad71feeb3cb0cad4a04bbf/log-redaction.md?plain=1#L10-L36
* https://github.com/pingcap/docs/blob/cd719695c040a41c1463f3fdba42f80aed8803d3/log-redaction.md?plain=1#L10-L38

**Comment by xhebox** [comment]
> @xhebox should we also update these related docs?
> 
>     * [pingcap/docs-cn@`1d6358a`/log-redaction.md?plain=1#L10-L36](https://github.com/pingcap/docs-cn/blob/1d6358a45add3e7339ad71feeb3cb0cad4a04bbf/log-redaction.md?plain=1#L10-L36)
> 
>     * [pingcap/docs@`cd71969`/log-redaction.md?plain=1#L10-L38](https://github.com/pingcap/docs/blob/cd719695c040a41c1463f3fdba42f80aed8803d3/log-redaction.md?plain=1#L10-L38)

Oh, I don't there is a dedicated page for this.
