### ISSUE TITLE
An batchCop query for a table containing generated columns returns an error

### ISSUE THREAD

**Issue by bindsang** [pingcap/tidb#51330]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
-- create table
create table generate_demo (
id bigint not null,
created_at datetime not null,
is_removed boolean not null,
updated_at datetime null,
__since_at datetime generated as (updated_at) virtual,
primary key (id)
);
-- set tiflash replica
alter table test.generate_demo set tiflash replica 1;
-- init data
insert into generate_demo (id, created_at, is_removed, updated_at) values (1, now(), 0, null), (2, now(), 1, now())
;
```
This error occurs only if the __since_at column is set to virtual. 
use 'alter table .... add column....' to add generated column is the same with the statement 'create table .....'

### 2. What did you expect to see? (Required)

I expect to see the below query execute successful and return correct results.

```sql
set tidb_isolation_read_engines = ‘tikv,tiflash’;
select * from generate_demo 
order by created_at asc
limit 100;
```

### 3. What did you see instead (Required)

I received error like this:

```plain
Error Code: 1105
Not found column table_scan_1 in block. There are only columns: table_scan_0, table_scan_2
```

the execution plan is:
```plain
id                          estRows  task               access object        operator info                                       
--------------------------  -------  -----------------  -------------------  ----------------------------------------------------
TopN_7                      2.00     root                                    test.generate_demo.created_at, offset:0, count:100  
└─TableReader_14            2.00     root                                    data:TopN_13                                        
  └─TopN_13                 2.00     batchCop[tiflash]                       test.generate_demo.created_at, offset:0, count:100  
    └─TableFullScan_12      2.00     batchCop[tiflash]  table:generate_demo  keep order:false, stats:pseudo                      
```

### 4. What is your TiDB version? (Required)

Release Version: v7.1.2
Edition: Community
Git Commit Hash: aa6ed99ae63191bc98e883fd4c369ae7482cccb7
Git Branch: heads/refs/tags/v7.1.2
UTC Build Time: 2023-10-21 07:46:04
GoVersion: go1.20.10
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore

**Comment by aytrack** [comment]
can not reproduce this on master and v7.5.1

**Comment by SeaRise** [comment]
same as https://github.com/pingcap/tiflash/issues/8787

**Comment by SeaRise** [comment]
> can not reproduce this on master and v7.5.1

https://github.com/pingcap/tiflash/issues/8787#issuecomment-1966005579
master branch also has this problem

**Comment by guo-shaoge** [comment]
https://github.com/pingcap/tiflash/issues/8787
