### ISSUE TITLE
data inconsistency in table after upgrade cluster v7.5.0 to v7.5.1

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#51332]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a 7.5.0 cluster
2. set global tidb_ddl_enable_fast_reorg=1; set global tidb_enable_dist_task=1
3. do add index
4. duraing add index, upgrade the cluster to v7.5.1 (457423cf1ac1deaa)
5. check the add index ddl jobs

### 2. What did you expect to see? (Required)
add index success and data is correct
### 3. What did you see instead (Required)
```sql
Error 8223 (HY000): data inconsistency in table: sbtest4, index: idxc, handle: 1692817, index-values:"" != record-values:"handle: 1692817, values: [KindString 00213351306-80522945476-12516733803-67361383194-59095689143-56755527917-69464322518-66654105761-60111563906-64745373451 KindString 06711118004-15680688
706-17136181078-32549810915-81402246909]
```
### 4. What is your TiDB version? (Required)
v7.5.0 -> v7.5.1 (457423cf1ac1deaa)

**Comment by tangenta** [comment]
Duplicated with #50895. Because the problematic code is in v7.5.0, we cannot avoid it.
