### ISSUE TITLE
Incorrect prefix index marking

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#5134]
```sql
create table city (
    city VARCHAR(2) KEY
);

alter table city change column city city varchar(50);

insert into city values ("abc"), ("abd");
```

Error:

ERROR 1062 (23000): Duplicate entry 'abd' for key 'PRIMARY'

This is because that when using the inline KEY syntax, we set its length to 2 instead of -1.

**Comment by mccxj** [comment]
mysql:
```
ERROR 1062 (23000): Duplicate entry 'London' for key 'PRIMARY'
```

**Comment by breeswish** [comment]
@mccxj I simplified the sample for better understanding.
