### ISSUE TITLE
planner: invalid Agg mode on MPP plans with sub-queries accessing partitioning tables under static partition mode

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#51362]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t (
  d date,
  v int,
  primary key(d, v)
) partition by range columns (d) (
  partition p1 values less than ('2023-07-02'),
  partition p2 values less than ('2023-07-03')
);

alter table t set tiflash replica 1;
set tidb_partition_prune_mode='static';
select * from information_schema.tiflash_replica; -- wait until the replication progress finish

select 1 from (
  select /*+ read_from_storage(tiflash[t]) */ sum(1)
  from t where d BETWEEN '2023-07-01' and '2023-07-03' group by d
) total;
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: Different aggregation mode detected, e.what() = DB::TiFlashException,
```

### 2. What did you expect to see? (Required)
No error

### 3. What did you see instead (Required)
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: Different aggregation mode detected, e.what() = DB::TiFlashException,

**Comment by qw4990** [comment]
It seems like we set the Agg mode incorrectly in this case, we can't use non-final mode with final mode together in a single Agg operator:
<img width="1701" alt="image" src="https://github.com/pingcap/tidb/assets/7499936/b03d1178-4f3b-4779-ae11-b3290bb3d294">

**Comment by kennedy8312** [comment]
mysql> select * from information_schema.tiflash_replica; -- wait until the replication progress finish
+--------------+------------+----------+---------------+-----------------+-----------+----------+
| TABLE_SCHEMA | TABLE_NAME | TABLE_ID | REPLICA_COUNT | LOCATION_LABELS | AVAILABLE | PROGRESS |
+--------------+------------+----------+---------------+-----------------+-----------+----------+
| test         | t          |      102 |             1 |                 |         1 |        1 |
+--------------+------------+----------+---------------+-----------------+-----------+----------+
1 row in set (0.02 sec)

mysql> select 1 from (
    ->   select /*+ read_from_storage(tiflash[t]) */ sum(1)
    ->   from t where d BETWEEN '2023-07-01' and '2023-07-03' group by d
    -> ) total;
ERROR 1105 (HY000): other error for mpp stream: Code: 0, e.displayText() = DB::TiFlashException: Different aggregation mode detected, e.what() = DB::TiFlashException,
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                 |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:41:10
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by kennedy8312** [comment]
Regression Analysis
The testcase started to fail on v7.3.0.
Start to analyze regression behavior among releases for issue 51362
Version v5.4.0 : Success
Version v6.0.0 : Success
Version v6.1.0 : Success
Version v6.2.0 : Success
Version v6.3.0 : Success
Version v6.4.0 : Success
Version v6.5.0 : Success
Version v6.6.0 : Success
Version v7.0.0 : Success
Version v7.1.0 : Success
Version v7.2.0 : Success
Version v7.3.0 : Failure
Version v7.4.0 : Failure
Version v7.5.0 : Failure
Version v7.6.0 : Failure
