### ISSUE TITLE
ranger: store the endpoint of range in plan phase by encoded value.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#5137]
We will need to sort the range.(e.g. merge the range of multiple-column index)
And this will decrease code about checking the corner case, like #5136 .
And we can use just one kind of range instead of three.
Currently, this is blocked by the wrong behavior when pk is unsigned.

**Comment by zz-jason** [comment]
@winoros Can we close this issue?

**Comment by winoros** [comment]
We've tried this someday ago but found it's not a easy task. Close it since we the performance of the planner don't affect the whole performance of TiDB currently.
