### ISSUE TITLE
Confusing AUTO_INCREMENT returned by SHOW CREATE TABLE

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#51416]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

I first create a table `t0` and fetch its creation by `SHOW CREATE TABLE`.
```sql
-- case 1
CREATE TABLE t0 ( c1 TINYINT AUTO_INCREMENT);
SHOW CREATE TABLE t0; -- lack AUTO_INCREMENT in table configuration
+-------+---------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                              |
+-------+---------------------------------------------------------------------------------------------------------------------------+
| t0    | CREATE TABLE `t0` (
  `c1` tinyint(4) NOT NULL AUTO_INCREMENT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+---------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```
After inserting a row, and refetch the creation of `t0`, in which the AUTO_INCREMENT value seems confusing to me. The AUTO_INCREMENT value is out of range to type tinyint.
```sql
INSERT INTO t0 VALUES (NULL); -- 1 is inserted
SHOW CREATE TABLE t0; -- the AUTO_INCREMENT value is out of range of TINYINT
+-------+------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                   |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------+
| t0    | CREATE TABLE `t0` (
  `c1` tinyint(4) NOT NULL AUTO_INCREMENT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001 |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```
I try to insert another value again.
```sql
INSERT INTO t0 VALUES (NULL); -- 3 is inserted, seems good to me
```
However, when I create a table `t1` by explicitly specifying the value of AUTO_INCREMENT.
```sql
-- case 2
CREATE TABLE t1 ( c1 TINYINT AUTO_INCREMENT) AUTO_INCREMENT=30001; -- a desinged AUTO_INCREMENT value
SHOW CREATE TABLE t1; -- the AUTO_INCREMENT value seems good
+-------+------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table
                                             |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `c1` tinyint(4) NOT NULL AUTO_INCREMENT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin AUTO_INCREMENT=30001 |
+-------+------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.001 sec)
```
However, I cannot execute the INSERT statement in `t1`.
```sql
INSERT INTO t1 VALUES (NULL);  -- ERROR 1690 (22003): constant 30001 overflows tinyint
```
### 2. What did you expect to see? (Required)
The AUTO_INCREMENT value returned by SHOW CREATE TABLE is more friendly to return the next stored value.
The current return result is not good.
### 3. What did you see instead (Required)
The AUTO_INCREMENT value returned is confusing, and out of range of the specified data type. 
### 4. What is your TiDB version? (Required)

Release Version: v7.6.0
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/52794d985ba6325d75a714d4eaa0838d59425eb6
Git Branch: heads/refs/tags/v7.6.0
UTC Build Time: 2024-01-22 14:20:42
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by tiancaiamao** [comment]
This behaviour is expected.

In case 1, `create table` and then `show create table`,  AUTO_INCREMENT is not displayed in the result, that's because we ignored adding the `AUTO_INCREMENT=xxx`  when `xxx` is 0.

After inserting one value, tidb will cache a batch of autoids, 30000 here. **if tidb down unexpectly, the next autoid should start from 30001**, so it displays `AUTO_INCREMENT=30001` in the show create table result.
Note that the next autoid allocating is from the tidb's cache, so it's not out of the range of 30000. 

In case 2, you directly set the `AUTO_INCREMENT=30001` in the `create table` statement, then `show create table`.
The next autoid allocated is 30001 because there is no cached autoids in tidb yet in this case, then it's out of the range of tinyint, you get the error.


-----------------

All above can be fixed by using `AUTO_ID_CACHE=1`, this make the behaviour compatible with MySQL.

**Comment by sayJason** [comment]
Great. I revise the `CREATE` statements as `CREATE TABLE t0 ( c1 TINYINT AUTO_INCREMENT) AUTO_ID_CACHE=1;`.
The behavior is expected to me. Thanks.
