### ISSUE TITLE
support extended statistics

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#5143]
## Description

Selectivity estimation of multi-column predicates heavily relies on independent assumption between these columns.

For example:

```sql
create table t(a bigint, b bigint);
select * from t where a = 1 and b = 2;
```

To estimate the selectivity of the predicate `a = 1 and b = 2`, we have made an assumption that the distribution of column `a` and column `b` is independent, thus the selectivity is estimated to `selectivity(a = 1) * selectivity(b = 2)`.

The independent assumption usually can not be held in user applications. Which causes a large selectivity estimation error, further cause an in-efficient SQL execution plan. For example, wrong access path, wrong join algorithm, wrong join order. etc.

With the help of extended statistics, we can build statistics on a group of columns, which helps to break the independent assumption, improves the selectivity estimation on the above scenario.

Related Work
- Build statistics for column groups.
- Build statistics for index prefixes.
- Support more kinds of statistics other than CM-Sketch, Histogram.

Useful links:

- https://blogs.oracle.com/optimizer/extended-statistics
- https://oracle-base.com/articles/12c/automatic-column-group-detection-extended-statistics-12cr1

## Category

- Stability
- Performance

### Value Description

- Improves row count estimation.
- It's also an optional workaround method when a wrong index is chosen.

### Value  Score

> Optional value: 1~5

- 4

### Workload Estimation

> 1 Point for 1 Person/Work Day

- 30 Points

**Comment by lamxTyler** [comment]
The construction of column group may need multi-pass of the data or sample. The automatic detection could be done after #5118, so we can use query log and graphical model to detect column groups, also the histograms of column groups could be adjusted in the same way.

**Comment by zz-jason** [comment]
Introduction about extended statistics in PGCon 2020: [create-statistics-pgcon.pdf](https://github.com/pingcap/tidb/files/4739789/create-statistics-pgcon.pdf)

**Comment by jebter** [comment]
Extended statistics have been supported as an experimental feature.：https://docs.pingcap.com/tidb/stable/extended-statistics,so I will close it. If there are any updates, you can reopen it.
