### ISSUE TITLE
task keeps in reverting state after upgrade

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#51464]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

the task became `reverting` somehow, and some node are scaled in after we create `revert_pending` subtasks, and we don't balance those type of subtasks, so no one handles those subtasks and the task keeps in `reverting` state

### 4. What is your TiDB version? (Required)
upgrade from 7.1 to 7.5

**Comment by D3Hunter** [comment]
a manually workaround is to update state of those subtasks from `revert_pending` to `reverted`

**Comment by seiya-annie** [comment]
Upgrade branch meets this issue:
source:  v7.1
target: v7.5
blocking stage: During upgrade
workaround: update state of those subtasks from revert_pending to reverted
