### ISSUE TITLE
[HY000][8243] unexpected end of JSON input

### ISSUE THREAD

**Issue by david-van** [pingcap/tidb#51597]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
对一个表执行truncate table语句，连续N次（不固定，2-10）。

### 2. What did you expect to see? (Required)
正常完成。

### 3. What did you see instead (Required)
偶发失败，提示错误信息：
![image](https://github.com/pingcap/tidb/assets/50688542/4b9cd0d1-3e06-408f-ae79-a0aec9e17d7d)
![Uploading image.png…]()

### 4. What is your TiDB version? (Required)
Release Version: v7.1.0
Edition: Community
Git Commit Hash: 635a4362235e8a3c0043542e629532e3c7bb2756
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-30 10:58:57
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by ywqzzy** [comment]
Can't reproduce the bug. Need detailed reproduce process.
<img width="331" alt="image" src="https://github.com/pingcap/tidb/assets/26179892/a279f9ce-8dc3-4916-bff3-eb194f29d122">
