### ISSUE TITLE
Table creation with auto_increment and default expressions has different error messages than MySQL

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#51592]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table t0 (c int(10), c1 date auto_increment default (current_date()));
```

### 2. What did you expect to see? (Required)
```
ERROR 1067 (42000): Invalid default value for 'c1'
```

### 3. What did you see instead (Required)
```
ERROR 1105 (HY000): Incorrect column specifier for column 'c1'
```

### 4. What is your TiDB version? (Required)

```
Release Version: v8.0.0-alpha-419-gf94a6bacf8-dirty
Edition: Community
Git Commit Hash: f94a6bacf872084630397b945ebf86561ce48bc8
Git Branch: master
```

**Comment by danqixu** [comment]
@zimulala I would like to try this issue, could you assign it to me?

**Comment by bb7133** [comment]
> @zimulala I would like to try this issue, could you assign it to me?

Assigned, thank you! @danqixu
