### ISSUE TITLE
after cancel ddl can not see it on job list when use fast ddl 

### ISSUE THREAD

**Issue by glkappe** [pingcap/tidb#51612]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

I think this is an uncommon question
### 2. What did you expect to see? (Required)
30482 can see
### 3. What did you see instead (Required)
30482 lost
<img width="1511" alt="image" src="https://github.com/pingcap/tidb/assets/21033020/29b64c94-66f3-4bfb-b7af-6a552508fe89">

### 4. What is your TiDB version? (Required)
v658

**Comment by tangenta** [comment]
By default, `admin show ddl jobs` only shows 10 jobs. You should see `30482` if you use `admin show ddl jobs 20` instead.

https://docs.pingcap.com/tidb/stable/sql-statement-admin-show-ddl#admin-show-ddl-jobsjob-queries:~:text=NUM%20is%20by%20default%2010
