### ISSUE TITLE
br node (8c27g) OOM when restore a big table of 150TB

### ISSUE THREAD

**Issue by fubinzh** [pingcap/tidb#51621]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. restore a 150TB big table on a 8c27g br node.

### 2. What did you expect to see? (Required)
br should not OOM.

### 3. What did you see instead (Required)
br OOM killed, stats is small for this backup.
![image](https://github.com/pingcap/tidb/assets/7403864/2468859f-a065-425d-adfe-ff9ea160dce2)

![image](https://github.com/pingcap/tidb/assets/7403864/605215df-a2a0-433f-8e38-8e8619cbf441)

### 4. What is your TiDB version? (Required)
master

**Comment by 3pointer** [comment]
https://github.com/pingcap/tidb/pull/51777 fixed it

**Comment by fubinzh** [comment]
This issue is still seen when restoring a backup of 30TB(~500k tables) using 32c110g br node with enviroment variable GOMEMLIMIT=16GiB, br parameters:  "--granularity=coarse-grained","--tikv-max-restore-concurrency=128", "--checksum=false", "--load-stats=true", "--ratelimit=600"
![image](https://github.com/pingcap/tidb/assets/7403864/c45692bf-ae44-4c3a-91d5-172da2a4cad1)
![image](https://github.com/pingcap/tidb/assets/7403864/3c6f7c22-b984-4c55-b63a-a26c8a07f499)
![image](https://github.com/pingcap/tidb/assets/7403864/1bad699f-e210-40b0-ab1d-9469d082aee2)
