### ISSUE TITLE
br: failed to get pd id when restore/log stop/log status

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#51638]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
br restore full/point or
br log stop or
br log status

### 3. What did you see instead (Required)
Error: [pd] failed to get cluster id
### 4. What is your TiDB version? (Required)

master

**Comment by BornChanger** [comment]
https://github.com/pingcap/tidb/pull/51706/files candidate pr.

**Comment by AkiraXie** [comment]
after cadidate pr merged, the issue was not seen
