### ISSUE TITLE
Support querying MVCC information through builtin function

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#51683]
## Enhancement

MVCC information is useful for debugging data inconsistenct issue. For now, we have HTTP API `mvcc/key/...` to query MVCC. However, it is not always convenient to construct a HTTP query. For example, when there are complex data types in index columns or clustered primary key columns like `timestamp`, `datetime` or even `binary`, query parameters cannot represent these values.

Maybe we can provide a builtin function like `tidb_mvcc_info()` achieve this purpose.

Note: the priviege should be considered to make sure there are no security issues.

**Comment by kennytm** [comment]
BTW should these functions require some privilege check to be invoked
