### ISSUE TITLE
master: tidb connection panic at batchRecvLoop

### ISSUE THREAD

**Issue by mayjiang0203** [pingcap/tidb#51702]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Add evict-leader-scheduler to on tikv with tpcc running repeatedly.

### 2. What did you expect to see? (Required)
No connection panic.

### 3. What did you see instead (Required)
```

{"namespace":"pdms-scheduling-oltp-tpcc-ops-tps-7500528-1-862","pod":"tc-tidb-0","level":"ERROR","container":"tidb","log":"[client_batch.go:672] [batchRecvLoop] [r=\"send on closed channel\"] [stack=\"github.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).batchRecvLoop.func1\\n\\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240308052415-af4f9a9b6e41/internal/client/client_batch.go:674\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:914\\nruntime.chansend\\n\\t/usr/local/go/src/runtime/chan.go:206\\nruntime.chansend1\\n\\t/usr/local/go/src/runtime/chan.go:145\\ngithub.com/tikv/client-go/v2/internal/client.(*batchCommandsClient).batchRecvLoop\\n\\t/go/pkg/mod/github.com/tikv/client-go/v2@v2.0.8-0.20240308052415-af4f9a9b6e41/internal/client/client_batch.go:730\"]"}
--



```

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.0.0-alpha
Edition: Community
Git Commit Hash: 715399f321c011f863d71b49cd1acab7575b4fb5
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time: 2024-03-11 11:44:06
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by cfzjywxk** [comment]
Duplicate with https://github.com/pingcap/tidb/issues/51728
