### ISSUE TITLE
qps drop to zero after inject one of tikv failure last for 10mins with enable tidb enable-forwarding

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#51728]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、enable tidb enable-forwarding
"tidb": "enable-forwarding = true"
2、run workload
3、inject one of tikv failure last for 10mins

### 2. What did you expect to see? (Required)
qps can recover within 2mins after inject one of tikv failure

### 3. What did you see instead (Required)
qps drop to zero after fault recover

![image](https://github.com/pingcap/tidb/assets/84712107/e5aa0d68-d51a-4936-9899-4bfed97e5472)

![image](https://github.com/pingcap/tidb/assets/84712107/7f9b6823-5370-4dc6-ac07-44e55f39ece7)

![img_v3_028u_ef43f85b-993f-48de-b875-e46cab8d9c4g](https://github.com/pingcap/tidb/assets/84712107/b8b77767-e6d5-459e-a524-3909a086ac17)

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.0.0-alpha
Edition: Community
Git Commit Hash: 661f6d61aeeac5036c227dff7dcc9b179dec5381
Git Branch: heads/refs/tags/v8.0.0-alpha
UTC Build Time: 2024-03-12 11:44:54
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-03-13T00:09:25.282+0800

**Comment by crazycs520** [comment]
This should be fixed by https://github.com/tikv/client-go/pull/1226 , and already update TiDB go.mod.
