### ISSUE TITLE
Incorrect result may caused by COALESCE and JOIN

### ISSUE THREAD

**Issue by Syang111** [pingcap/tidb#51843]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
Consider the following statements. 

In theory, query1 and query2 should return the same result. However, query1 return `NULL` while query2 return nothing.
```
CREATE TABLE t0(c0 FLOAT );
CREATE VIEW v0(c0) AS SELECT CAST( (-1 OR '0.1' )  AS TIME) FROM t0 WHERE '';
INSERT INTO t0 VALUES (0.1);

mysql> SELECT f1 FROM (SELECT COALESCE(v0.c0) AS f1 FROM v0 RIGHT JOIN t0 ON '1') AS t WHERE f1 <=> ''; --query1
+------+
| f1   |
+------+
| NULL |
+------+
1 row in set, 2 warnings (0.00 sec)

mysql> SELECT f1 FROM (SELECT COALESCE(v0.c0) AS f1, (COALESCE(v0.c0)<=>'') IS TRUE AS flag FROM  v0 RIGHT  OUTER JOIN t0 ON '1') AS t WHERE flag=1; --query2
Empty set, 1 warning (0.00 sec)
```

### 2. What is your TiDB version? (Required)
v7.6.0, v4.0.0

**Comment by aytrack** [comment]
similar to #51842

**Comment by windtalker** [comment]
Close this because it is the same bug as https://github.com/pingcap/tidb/issues/51842
