### ISSUE TITLE
Table attributes like fk_info and index_info is changed from null to [].

### ISSUE THREAD

**Issue by kennedy8312** [pingcap/tidb#51847]
## Bug Report

When a simple table is created without index and fk, some of its attributes, for example, fk_info and index_info would be null returned by the following api.
 '(http://{TiDBIP}:10080/schema/{db}/{table})' 
However, once the table is backup and restored. attributes like fk_info and index_info would change to [] instead of null. This would trigger issues like https://github.com/pingcap/tidb/issues/51807.
Here is a few things we might need to review.
(1) Shall we keep the attribute consistent before and after restore?
(2) Now we have fixed the precheck in exchange partition, is there other precheck needs to be fixed in tidb?

### 1. Minimal reproduce step (Required)
(1) create a table and check its attribute with the following api.
 '(http://{TiDBIP}:10080/schema/{db}/{table})' 
(2) backup the cluster and restore it to another cluster.
(3) check its attribute to see if there is any changes, for example, from null to [].

### 2. What did you expect to see? (Required)
To be reviewed. 

### 3. What did you see instead (Required)
![e74f703c-5b8d-4656-8ec5-18c3ddd8705b](https://github.com/pingcap/tidb/assets/95329414/6fe6387b-6b68-4396-bc5c-b016db7f5dfc)

### 4. What is your TiDB version? (Required)
v7.5.0

**Comment by YangKeao** [comment]
This issue can cause some headache bug. Ref #51807 #51762 and the fix https://github.com/pingcap/tidb/pull/51834.

It'd be better to handle both of the cases. I'll consider whether to use a linter (e.g. you have to use `sliceutil.IsNil(xxx)` to tell nil, and all other `xxx == nil` should be written as `len(xxx) == 0`...), but I'm not sure whether it's good.

**Comment by D3Hunter** [comment]
8.1 already has the fix
