### ISSUE TITLE
Compile duration P99 has become 8 times slower

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#51871]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a tidb cluster with 3 tidb + 3 tikv
2. run sysbench oltp_read_write/oltp_read_only

### 2. What did you expect to see? (Required)
No performance regression.

### 3. What did you see instead (Required)
Compile duration P99 has become 8 times slower, while the internal transactions per second (TPS) have increased by two orders of magnitude. However, the queries per second (QPS) have decreased by 12% to 15%.
![image](https://github.com/pingcap/tidb/assets/84501897/fd76cef0-e145-43de-af90-1cabcb382df1)

oltp_read_write
2024-03-15 QPS= 81705, compile duration p99=597us ,  commit https://github.com/pingcap/tidb/commit/f8ac982ebf06198657f8943575fee0995890c390 
![image](https://github.com/pingcap/tidb/assets/84501897/c6e0df82-55f5-4a3a-904c-57dbc1108772)

![image](https://github.com/pingcap/tidb/assets/84501897/c8f43c75-0d69-44ec-8237-0bbcb5f67dcb)

2024-03-16 QPS= 68905, compile duration p99=4.96ms ,  commit https://github.com/pingcap/tidb/commit/999e0bd38a7109f0f821e6e04409dc202b019a3e
![image](https://github.com/pingcap/tidb/assets/84501897/378f7a6c-df0b-4e59-8f41-d10e52b0c943)
![image](https://github.com/pingcap/tidb/assets/84501897/72360752-d8a3-434e-b13c-2759f6eb8739)

**Comment by time-and-fate** [comment]
Directly caused by https://github.com/pingcap/tidb/pull/47496, some details may need further investigation.

**Comment by winoros** [comment]
<img width="515" alt="image" src="https://github.com/pingcap/tidb/assets/7846227/243e5d2e-3fbe-4491-9251-f0a1150f2611">
sync load qps is high

**Comment by Yui-Song** [comment]
https://github.com/pingcap/tidb/pull/47496 also caused the regression of TiDB go-bench BenchmarkRangeColumnPartitionPruning. After the issue was fixed, the performance of the benchmark was restored.
![image](https://github.com/pingcap/tidb/assets/84501897/95ec7209-84e7-45d3-a25e-0fe1e739d1cd)

**Comment by kennedy8312** [comment]
Regression Analysis
PR caused this regression: https://github.com/pingcap/tidb/pull/47496
