### ISSUE TITLE
There is a 2%-4% performance regression in sysbench select_random_points

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#51898]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. deploy a tidb cluster 
2. run sysbench select_random_points

### 2. What did you expect to see? (Required)
No performance regression
### 3. What did you see instead (Required)
- 2424-01-30, QPS= 62463 , commit https://github.com/pingcap/tidb/commit/25f44f577dd32b351dbbaca82e7b2022590a7d42
![image](https://github.com/pingcap/tidb/assets/84501897/209fe97c-7db3-445b-bc1e-07c8f3566e5c)

- 2424-01-31, QPS= 59776 , commit https://github.com/pingcap/tidb/commit/27fbccb1daf28be14990fa1a92badbabe57a7e86
![image](https://github.com/pingcap/tidb/assets/84501897/4c34bf67-5051-4e24-bc09-997847aafcf9)

**Comment by XuHuaiyu** [comment]
<img width="855" alt="截屏2024-03-20 11 27 32" src="https://github.com/pingcap/tidb/assets/9039012/1c940c96-1e48-4b75-9b5e-38e3a8b67fff">

In the new CPU profile, we can see that there is additional CPU overhead in the index usage reporter section. This overhead was introduced by commit 7087f702e18f811c98d5a276eace7bb69292c6aa.
We will conduct tests on this commit to confirm whether the regression is indeed introduced by this commit.

**Comment by XuHuaiyu** [comment]
Change the sig label to sig/sql-infra

**Comment by YangKeao** [comment]
I tried to run `sysbench random_points` on #50773 and #50643. The change is not significant:

![image](https://github.com/pingcap/tidb/assets/5244316/79f9bf0b-08a8-4ab6-ad2a-b24d3bd52446)

Actually, the variance is too big :facepalm: (The upper 3 are #50773, and the next 3 are #50643)

**Comment by Yui-Song** [comment]
Tracing back to this PR will lead to regression in the following three benchmarks: BenchmarkBatchPointGet, BenchmarkPreparedPointGet, and BenchmarkPointGet.

https://github.com/pingcap/tidb/blob/master/Makefile#L299
`make bench-daily TO=/path/to/file.json`

![img_v3_029d_1bbff454-ff74-481b-bfce-9cf340c0076g](https://github.com/pingcap/tidb/assets/84501897/b7c2c3d5-0304-430c-8c3f-bdb9b3b44888)

**Comment by YangKeao** [comment]
To re-produce this issue, I wrote a simpler implementation of `select_random_points` in go, with client-side connection balancer, and it has a much stabler performance: https://gist.github.com/YangKeao/c02ada99d2602d5e7fb5fb94f0581015

For the commit with index usage, the average QPS (after enough warm-up, though I don't know why warm-up does help) is 58393, and the commit without index usage is 59029. The degradation is around 1.07%.

(Also, I don't know why this go-version is a little bit slower than the lua version, maybe the go client is not as fast as the driver used by sysbench).

**Comment by Yui-Song** [comment]
This issue is related to another issue, https://github.com/pingcap/tidb/issues/51852. All three workloads involve a large number of coprocessor operations. The performance can be fixed through the PR https://github.com/pingcap/tidb/pull/53429 and https://github.com/pingcap/tidb/issues/52887. For detailed details, please refer to the PR analysis.
