### ISSUE TITLE
regex_replace Cann't get the matched string 

### ISSUE THREAD

**Issue by coding7805** [pingcap/tidb#51895]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

select regexp_replace('abcd','(.*)(.{2})$','$1') as s;  

### 2. What did you expect to see? (Required)
+----+
| s      |
+----+
| ab    |
+----+

### 3. What did you see instead (Required)
+----+
| s      |
+----+
| $1    |
+----+
in mysql 8.0, the result is
+--------+
|  s            |
+--------+
| ab          |
+--------+

### 4. What is your TiDB version? (Required)
Release Version: v6.5.2

**Comment by windtalker** [comment]
Hi @coding7805 , TiDB uses different regexp lib from MySQL, so it is not 100% compatiable with MySQL, for your case, seems you wants to use substitutions, in TiDB, you shoud use `\\number` instead of `$number`, and also please note in TiDB, number only support `0-9`
```
mysql> select regexp_replace('abcd','(.*)(.{2})$','\\1') as s;
+----+
| s  |
+----+
| ab |
+----+
1 row in set (0.00 sec)
```

**Comment by coding7805** [comment]
I tried this way, but it didn't work.

**Comment by coding7805** [comment]
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.5.2
Edition: Community
Git Commit Hash: 29116c0256c52b224da2b34d712c1063d171c0ad
Git Branch: heads/refs/tags/v6.5.2
UTC Build Time: 2023-04-19 10:43:49
GoVersion: go1.19.8
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select regexp_replace('abcd','(.*)(.{2})$','\\1') as s;
+----+
| s  |
+----+
| \1 |
+----+
1 row in set (0.01 sec)

**Comment by coding7805** [comment]
[mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v6.5.2
Edition: Community
Git Commit Hash: 29116c0256c52b224da2b34d712c1063d171c0ad
Git Branch: heads/refs/tags/v6.5.2
UTC Build Time: 2023-04-19 10:43:49
GoVersion: go1.19.8
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> select regexp_replace('abcd','(.*)(.{2})$','\\\\1') as s;
+----+
| s  |
+----+
| \1 |
+----+
1 row in set (0.00 sec)](url)

**Comment by coding7805** [comment]
it works in v7.5.1, but it doesn't work in v7.1.0, v6.5.3, v6.5.2

**Comment by windtalker** [comment]
> it works in v7.5.1, but it doesn't work in v7.1.0, v6.5.3, v6.5.2

Yes, capture group support is added in v7.2.0 by https://github.com/pingcap/tidb/pull/43671
