### ISSUE TITLE
simple query reports 'Can't find a proper physical plan for this query'

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#51939]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

``` SQL
CREATE TABLE `tl` (
  `col_42` json NOT NULL,
  `col_43` tinyint(1) DEFAULT NULL,
  `col_44` char(168) CHARACTER SET gbk COLLATE gbk_bin DEFAULT NULL,
  `col_45` json DEFAULT NULL,
  `col_46` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_47` char(43) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'xW2YNb99pse4)',
  `col_48` time NOT NULL DEFAULT '12:31:25',
  PRIMARY KEY (`col_47`,`col_46`(2)) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tl` VALUES ('[\"01qHMy8yycbq2v1CZ80kiIECEQFLXYsnM0tpVh9vbx71DMpaPdp6hBkrpTodkXVt\", \"dGugZHV3pmqjLSdICAYbiwFGZsYWX9MrzgSGCslmEsfFzXYOiXyE0YMS1TSfnX5R\", \"Ypz8Jj0hBSBQbiWd3LbPRV2qvSEAxV8rlXnxpn93nXmFyMJkCQzyhtNn0FUwH6Ce\", \"Yf6kag9ruOT04V8AHT6NYhCNIa2CYZDVg8zWaxxHFm0GPAJh0e6Mc5Upa0EAp1Sr\", \"ljrRnPUdxJNkWxmkn4K25YeFwVtedGtLDrWlWYZyqt2Shpfg4p7jroOwbOZHuHiE\"]',0,'釸7鈡w歀痂暰苕rv)Ts','[5661899762065804824, 3294089805449875423, 2378579521053711229, 6262068190112960080]','Wxup81婱鍋cH爀
2潺檛楍1N7','2ZNeu2n5-2+Q3qYp','10:14:20'), ('[\"iOl0B9dVMoNYk8Qroj6JTwm0MaCJmr5qnQzdjMtaoDar4jGe6q20HAyVu3GacogW\", \"PBy3AXmGhzJMBX3Ow9INdeATLld8bVVjrIUVTlspzpHMZPuFGlEsDeRN6JOLqRLy\", \"jyr0odf7TOhLpuejrfbvsBbjqCchHSKEFZ079c5KUhu0FIuoqm6tBNbWCBb0xb3c\", \"PmPE8oZf73Zwffi97D7AaQM5g0xameUwPvO15LEUPVlF4iiDVsXyGMESSbEzR5L7\", \"4y0WxQIzPw217QeSXCySsK3pGbHdMxx6ETtIZQfGI8v7Pq9Rxhwkslr1ih8M7Dok\"]',0,'','[2142591371645505560, 2975660707908269211]','','aC794Ir-)iJZr&a','02:30:55'), ('[\"je9igPre8L6VdmtEtVDwxCgTqcuSKdqdO4fheHXRJOQLojiHx4F8cXmFpiYq9955\", \"zPjn7sAeMVLLGE3o9lpnZai26ad8qxHNQF6CSsMshFbP2fDuByV3SYxhxkVwIQd3\", \"Etj8PQZe64XWTbBElIEhWA3F3OcytxNMLvxQqr4miDxoK96Q8fGjBg34H3i4y3V5\", \"IDNAQjueBRQyUE285zoPSMhIvVKrxbiXAVvge0iC9AaEFK18Gh3sign84Nu6M3Ar\", \"MK79tEDnyHn2Cmw4W55hEzAsKvqUTZbViv6UyiEqnUE9jpBOnMEDQbq6yQip4qm3\"]',1,')譺
)RK5','[1760220588316922379, 4921535278728445755, 5623214347361271244, 5272407040485486430, 9017432485293265763]','RLFF','gS','06:27:28');

alter table tl add index idx_16(`col_48`,(cast(`col_45` as signed array)),`col_46`(5));

desc select col_47 from tl where col_48 = '10:14:20';
```

### 2. What did you expect to see? (Required)
No error
### 3. What did you see instead (Required)
``` sql
ERROR 1815 (HY000): Internal : Can't find a proper physical plan for this query
```
### 4. What is your TiDB version? (Required)
4e416993cc65b4da6786a7ce859b2ab99e5bba15

**Comment by kennedy8312** [comment]
Regression Analysis
**Issue with the same testcase didn't happen on v7.5.0 but on v7.6.0.**

-----------------Regression Test Result on v7.5.0-----------------
Server on v7.5.0 started.
Validation passed. v7.5.0 is a good label
-----------------Test Case-----------------
mysql -h 127.0.0.1 -P 4000 -u root -D test --local-infile=true < issue51939_testcase.sql
issue51939_testcase.sql: 
drop table if exists `tl`;

CREATE TABLE `tl` (
  `col_42` json NOT NULL,
  `col_43` tinyint(1) DEFAULT NULL,
  `col_44` char(168) CHARACTER SET gbk COLLATE gbk_bin DEFAULT NULL,
  `col_45` json DEFAULT NULL,
  `col_46` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_47` char(43) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'xW2YNb99pse4)',
  `col_48` time NOT NULL DEFAULT '12:31:25',
  PRIMARY KEY (`col_47`,`col_46`(2)) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tl` VALUES ('[\"01qHMy8yycbq2v1CZ80kiIECEQFLXYsnM0tpVh9vbx71DMpaPdp6hBkrpTodkXVt\", \"dGugZHV3pmqjLSdICAYbiwFGZsYWX9MrzgSGCslmEsfFzXYOiXyE0YMS1TSfnX5R\", \"Ypz8Jj0hBSBQbiWd3LbPRV2qvSEAxV8rlXnxpn93nXmFyMJkCQzyhtNn0FUwH6Ce\", \"Yf6kag9ruOT04V8AHT6NYhCNIa2CYZDVg8zWaxxHFm0GPAJh0e6Mc5Upa0EAp1Sr\", \"ljrRnPUdxJNkWxmkn4K25YeFwVtedGtLDrWlWYZyqt2Shpfg4p7jroOwbOZHuHiE\"]',0,'釸7鈡w歀痂暰苕rv)Ts','[5661899762065804824, 3294089805449875423, 2378579521053711229, 6262068190112960080]','Wxup81婱鍋cH爀
2潺檛楍1N7','2ZNeu2n5-2+Q3qYp','10:14:20'), ('[\"iOl0B9dVMoNYk8Qroj6JTwm0MaCJmr5qnQzdjMtaoDar4jGe6q20HAyVu3GacogW\", \"PBy3AXmGhzJMBX3Ow9INdeATLld8bVVjrIUVTlspzpHMZPuFGlEsDeRN6JOLqRLy\", \"jyr0odf7TOhLpuejrfbvsBbjqCchHSKEFZ079c5KUhu0FIuoqm6tBNbWCBb0xb3c\", \"PmPE8oZf73Zwffi97D7AaQM5g0xameUwPvO15LEUPVlF4iiDVsXyGMESSbEzR5L7\", \"4y0WxQIzPw217QeSXCySsK3pGbHdMxx6ETtIZQfGI8v7Pq9Rxhwkslr1ih8M7Dok\"]',0,'','[2142591371645505560, 2975660707908269211]','','aC794Ir-)iJZr&a','02:30:55'), ('[\"je9igPre8L6VdmtEtVDwxCgTqcuSKdqdO4fheHXRJOQLojiHx4F8cXmFpiYq9955\", \"zPjn7sAeMVLLGE3o9lpnZai26ad8qxHNQF6CSsMshFbP2fDuByV3SYxhxkVwIQd3\", \"Etj8PQZe64XWTbBElIEhWA3F3OcytxNMLvxQqr4miDxoK96Q8fGjBg34H3i4y3V5\", \"IDNAQjueBRQyUE285zoPSMhIvVKrxbiXAVvge0iC9AaEFK18Gh3sign84Nu6M3Ar\", \"MK79tEDnyHn2Cmw4W55hEzAsKvqUTZbViv6UyiEqnUE9jpBOnMEDQbq6yQip4qm3\"]',1,')譺
)RK5','[1760220588316922379, 4921535278728445755, 5623214347361271244, 5272407040485486430, 9017432485293265763]','RLFF','gS','06:27:28');

alter table tl add index idx_16(`col_48`,(cast(`col_45` as signed array)),`col_46`(5));

desc select col_47 from tl where col_48 = '10:14:20';

-----------------Test Result-----------------
Result : 
id	estRows	task	access object	operator info
Projection_4	10.00	root		test.tl.col_47
└─IndexMerge_7	10.00	root		type: union
  ├─IndexRangeScan_5(Build)	10.00	cop[tikv]	table:tl, index:idx_16(col_48, cast(`col_45` as signed array), col_46)	range:[10:14:20,10:14:20], keep order:false, stats:pseudo
  └─TableRowIDScan_6(Probe)	10.00	cop[tikv]	table:tl	keep order:false, stats:pseudo
-----------------TiDB Version-----------------
tidb_version()
Release Version: v7.5.0
Edition: Community
Git Commit Hash: 069631e2ecfedc000ffb92c67207bea81380f020
Git Branch: heads/refs/tags/v7.5.0
UTC Build Time: 2023-11-24 08:41:10
GoVersion: go1.21.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

-----------------End of regression test on v7.5.0-----------------
----------------------------------------------------------------------
mysqld is alive
----------------------------------------------------------------------
-----------------Regression Test Result on v7.6.0-----------------
Server on v7.6.0 started.
Validation failed at run 1. v7.6.0 is a bad label.
Expected: 
id	estRows	task	access object	operator info
Projection_4	10.00	root		test.tl.col_47
└─IndexMerge_7	10.00	root		type: union
  ├─IndexRangeScan_5(Build)	10.00	cop[tikv]	table:tl, index:idx_16(col_48, cast(`col_45` as signed array), col_46)	range:[10:14:20,10:14:20], keep order:false, stats:pseudo
  └─TableRowIDScan_6(Probe)	10.00	cop[tikv]	table:tl	keep order:false, stats:pseudo
Actual: 
ERROR 1815 (HY000) at line 20: Internal : Can't find a proper physical plan for this query
-----------------Test Case-----------------
mysql -h 127.0.0.1 -P 4000 -u root -D test --local-infile=true < issue51939_testcase.sql
issue51939_testcase.sql: 
drop table if exists `tl`;

CREATE TABLE `tl` (
  `col_42` json NOT NULL,
  `col_43` tinyint(1) DEFAULT NULL,
  `col_44` char(168) CHARACTER SET gbk COLLATE gbk_bin DEFAULT NULL,
  `col_45` json DEFAULT NULL,
  `col_46` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `col_47` char(43) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'xW2YNb99pse4)',
  `col_48` time NOT NULL DEFAULT '12:31:25',
  PRIMARY KEY (`col_47`,`col_46`(2)) /*T![clustered_index] CLUSTERED */
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tl` VALUES ('[\"01qHMy8yycbq2v1CZ80kiIECEQFLXYsnM0tpVh9vbx71DMpaPdp6hBkrpTodkXVt\", \"dGugZHV3pmqjLSdICAYbiwFGZsYWX9MrzgSGCslmEsfFzXYOiXyE0YMS1TSfnX5R\", \"Ypz8Jj0hBSBQbiWd3LbPRV2qvSEAxV8rlXnxpn93nXmFyMJkCQzyhtNn0FUwH6Ce\", \"Yf6kag9ruOT04V8AHT6NYhCNIa2CYZDVg8zWaxxHFm0GPAJh0e6Mc5Upa0EAp1Sr\", \"ljrRnPUdxJNkWxmkn4K25YeFwVtedGtLDrWlWYZyqt2Shpfg4p7jroOwbOZHuHiE\"]',0,'釸7鈡w歀痂暰苕rv)Ts','[5661899762065804824, 3294089805449875423, 2378579521053711229, 6262068190112960080]','Wxup81婱鍋cH爀
2潺檛楍1N7','2ZNeu2n5-2+Q3qYp','10:14:20'), ('[\"iOl0B9dVMoNYk8Qroj6JTwm0MaCJmr5qnQzdjMtaoDar4jGe6q20HAyVu3GacogW\", \"PBy3AXmGhzJMBX3Ow9INdeATLld8bVVjrIUVTlspzpHMZPuFGlEsDeRN6JOLqRLy\", \"jyr0odf7TOhLpuejrfbvsBbjqCchHSKEFZ079c5KUhu0FIuoqm6tBNbWCBb0xb3c\", \"PmPE8oZf73Zwffi97D7AaQM5g0xameUwPvO15LEUPVlF4iiDVsXyGMESSbEzR5L7\", \"4y0WxQIzPw217QeSXCySsK3pGbHdMxx6ETtIZQfGI8v7Pq9Rxhwkslr1ih8M7Dok\"]',0,'','[2142591371645505560, 2975660707908269211]','','aC794Ir-)iJZr&a','02:30:55'), ('[\"je9igPre8L6VdmtEtVDwxCgTqcuSKdqdO4fheHXRJOQLojiHx4F8cXmFpiYq9955\", \"zPjn7sAeMVLLGE3o9lpnZai26ad8qxHNQF6CSsMshFbP2fDuByV3SYxhxkVwIQd3\", \"Etj8PQZe64XWTbBElIEhWA3F3OcytxNMLvxQqr4miDxoK96Q8fGjBg34H3i4y3V5\", \"IDNAQjueBRQyUE285zoPSMhIvVKrxbiXAVvge0iC9AaEFK18Gh3sign84Nu6M3Ar\", \"MK79tEDnyHn2Cmw4W55hEzAsKvqUTZbViv6UyiEqnUE9jpBOnMEDQbq6yQip4qm3\"]',1,')譺
)RK5','[1760220588316922379, 4921535278728445755, 5623214347361271244, 5272407040485486430, 9017432485293265763]','RLFF','gS','06:27:28');

alter table tl add index idx_16(`col_48`,(cast(`col_45` as signed array)),`col_46`(5));

desc select col_47 from tl where col_48 = '10:14:20';

-----------------Test Result-----------------
Result : 
ERROR 1815 (HY000) at line 20: Internal : Can't find a proper physical plan for this query
-----------------TiDB Version-----------------
tidb_version()
Release Version: v7.6.0
Edition: Community
Git Commit Hash: 52794d985ba6325d75a714d4eaa0838d59425eb6
Git Branch: heads/refs/tags/v7.6.0
UTC Build Time: 2024-01-22 14:13:53
GoVersion: go1.21.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv

-----------------End of regression test on v7.6.0-----------------

**Comment by kennedy8312** [comment]
Regression Analysis
PR caused this regression: https://github.com/pingcap/tidb/pull/50183

Commit 2df8bd1fc0fb5100bddf94f6bebe4e43878becc2 : Failure
Commit a0ce8e02840a0725ff6b270a4aa06370d128dcc4 : Failure
Commit acd3ddc5e71ad2df44e6eb596553c5c20c4af818 : Success

**Comment by kennedy8312** [comment]
The regression causing pr https://github.com/pingcap/tidb/pull/50183 has already been merged to v7.5.1 and v7.1.4. Please help double check if we need to fix the issue in v7.1 and v7.5.

**Comment by winoros** [comment]
@kennedy8312 Complex usage of the Multi-value index is not regarded as GA in 7.5.

**Comment by time-and-fate** [comment]
Fixed by https://github.com/pingcap/tidb/pull/52067
