### ISSUE TITLE
tables info not updated for a long time

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#51942]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t (a int, b int, c varchar(5), primary key(a), index idx(c)) PARTITION BY RANGE (a) (PARTITION p0 VALUES LESS THAN (6), PARTITION p1 VALUES LESS THAN (11), PARTITION p2 VALUES LESS THAN (16));
insert into t(a, b, c) values(1, 2, 'c'), (7, 3, 'd'), (12, 4, 'e');
-- wait 20 * 3 to query the stats info 
select table_rows, avg_row_length, data_length, index_length from information_schema.tables where table_name='t' AND TABLE_SCHEMA='tibug_187_test';
-- wait 20 * 3 * 6 to query the stats info
select table_rows, avg_row_length, data_length, index_length from information_schema.tables where table_name='t' AND TABLE_SCHEMA='tibug_187_test';
```
### 2. What did you expect to see? (Required)
get the correct stats info 
### 3. What did you see instead (Required)
maybe introducted by https://github.com/pingcap/tidb/pull/50874
no data 
### 4. What is your TiDB version? (Required)
v8.0.0-pre

**Comment by kennedy8312** [comment]
Regression Analysis
PR caused this regression: https://github.com/pingcap/tidb/pull/50874

Commit 6701bf1527c7386a82396a1ecfb5322872daa2b3 : Success
Commit c3c067eb9334ba75d59e9712f0c21b378ffeca5e : Success
Commit a8a9a040774dea10c956c6cc10bde57142bf7298 : Failure
Commit a59551b701704ec2b3d33dc1299ea6c75c34acb8 : Failure
Commit 1678c4fa25dbe888582b10132edd4899a1203f41 : Success
Commit 0df9170791401b31539a40000ecb0739e7a43283 : Failure
Commit 6af4bbaabbbcbd50689d18b8d88b96194270b3e2 : Success
Commit f4e758a89daa73f846dbe40787b07d1bd2b0742e : Success
Commit 3c3ba00cb40dee3b525fb22cb8ab33c52820acce : Success
Commit 801de42a0e85270904bac297d8d42595b9175162 : Success

**Comment by ywqzzy** [comment]
Test on my local machine, the row count updated after 110s

**Comment by kennedy8312** [comment]
> Test on my local machine, the row count updated after 110s

This might be another issue. Please try the testcase as follows:
echo ''>test.log
for i in {1..100}; do
    mysql --comments --host 127.0.0.1 --port 4000 -u root test < issue51942_testcase.sql >> test.log
done

[issue51942_testcase.txt](https://github.com/pingcap/tidb/files/14667772/issue51942_testcase.txt)

In test.log with commit 0df9170791401b31539a40000ecb0739e7a43283, there are always "0	0	0	0" (usually 3 times) in the result.
However, in the test.log with the commit 801de42a0e85270904bac297d8d42595b9175162 which is one commit prior to 0df9170791401b31539a40000ecb0739e7a43283, there is no "0	0	0	0" in the result.
![image](https://github.com/pingcap/tidb/assets/95329414/a472ebb6-88f0-45e6-8f00-9cb083ea8ab2)
