### ISSUE TITLE
Do not support mysqldump to dump sql from TiDB

### ISSUE THREAD

**Issue by netroby** [pingcap/tidb#520]
```
mysqldump -u root -h 127.0.0.1 --port 4000 --opt test > test.sql
mysqldump: Error: 'table INFORMATION_SCHEMA.FILES does not exist' when trying to dump tablespaces
mysqldump: Couldn't execute 'UNLOCK TABLES': line 1 column 1 near "UNLOCK" (1105)

```

**Comment by netroby** [comment]
So the question was : how to backup TiDB ?

**Comment by ngaut** [comment]
Hi @netroby , We may support mysqldump later. 
Please take a look. @shenli

**Comment by shenli** [comment]
We need to add FILES, PARTITIONS table into INFORMATION_SCHEMA.
And then support flush tables, flush tables with read lock, unlock tables statements.

**Comment by netroby** [comment]
Or you can provided your own export sql tools. If it can replace mysqldump . Ate self dog food seems well done.
