### ISSUE TITLE
Error log : unknown sys var: version_comment

### ISSUE THREAD

**Issue by netroby** [pingcap/tidb#521]
```
2015/11/05 16:30:56 conn.go:240: [error] dispatch error Unknown sys var: version_comment
/home/huzhifeng/go/src/github.com/pingcap/tidb/expression/variable.go:87: 
/home/huzhifeng/go/src/github.com/pingcap/tidb/plan/plans/fields.go:83: 
/home/huzhifeng/go/src/github.com/pingcap/tidb/plan/plans/final.go:72: 
/home/huzhifeng/go/src/github.com/pingcap/tidb/rset/rsets/rsets.go:110: 
/home/huzhifeng/go/src/github.com/pingcap/tidb/tidb-server/server/driver_tidb.go:243: 
/home/huzhifeng/go/src/github.com/pingcap/tidb/tidb-server/server/conn.go:398: 
/home/huzhifeng/go/src/github.com/pingcap/tidb/tidb-server/server/conn.go:369: , conn: 127.0.0.1:39172, status: 3, charset: utf8, user: root, lastInsertId: 0
2015/11/05 16:30:56 conn.go:241: [error] cmd: select @@version_comment limit 1

```

base on the latest master branch source code

**Comment by shenli** [comment]
@netroby Thanks for your report.
I tried it with the lastest master but get nothing wrong.
May I have your git log info and detailed operations?

➜  tidb git:(master) ✗ git log | head -n 10
commit 89fa72467cdfaca4c1ca1ca54c29a592b1f2afb7
Merge: 3b0f94f 2f2e31c
Author: Ewan Chou <coocood@gmail.com>
Date:   Thu Nov 5 15:38:31 2015 +0800

    Merge pull request #491 from pingcap/coocood/binder
    
    ast,optimizer: switch to use new parser, and convert ast.Node to old statements.

commit 2f2e31c8f47c4b92d7ddd546a6534b74c6118e6d


➜  tidb git:(master) ✗ mysql -uroot -h127.0.0.1 -P4000
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10001
Server version: 5.5.31-TiDB-1.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> select @@version_comment limit 1;
+------------------------------+
| @@version_comment            |
+------------------------------+
| MySQL Community Server (GPL) |
+------------------------------+
1 row in set (0.00 sec)

mysql>

**Comment by netroby** [comment]
I can not reappear this problem now, may be it was fixed.
