### ISSUE TITLE
tpcc-mysql test very puzzled

### ISSUE THREAD

**Issue by zzx8170** [pingcap/tidb#5213]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

tpcc-mysql做压测，两个tidb，3个pd，3个tikv节点，用工具分别在1、2、4、8、16、32、64个并发跑。安装过程是安装官方文档：https://pingcap.com/docs-cn/QUICKSTART/  自动化部署的，没有修改任何参数，测试过程tidb使用了一个节点。

2. What did you expect to see?

随着并发增大，tpmc值增大，最后稳定后平缓下降

3. What did you see instead?

随着并发增大，tpmc值减小，并发为1的时候居然tmpc最大，不知道是什么原因？而且比同样配置下的mysql tpmc低很多。

4. What version of TiDB are you using (`tidb-server -V`)?

1.0

**Comment by shenli** [comment]
@zzx8170 If there are many transactions updating the same row, it will cause backoff and retry.
See: https://github.com/pingcap/docs/blob/master/FAQ.md#does-the-conflict-of-multiple-transactions-such-as-updating-the-same-row-at-the-same-time-cause-commit-failure-of-some-transactions

**Comment by zzx8170** [comment]
如何查询行锁等待和慢查询？有专门的工具或者日志吗？

**Comment by shenli** [comment]
You can use grafana to get an insight about write conflicts. The slow queries could be found in the log file of tidb-server by greping "slow-query".

**Comment by zzx8170** [comment]
测试过程中tidb.log有如下error：

2017/11/27 11:39:38.011 conn.go:427: [warning] [623] dispatch error:
id:623, addr:127.0.0.1:51723 status:0, collation:latin1_swedish_ci, user:root
"commit"
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:393: [623] can not retry select for
update statement
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:313:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:331:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/tidb.go:172:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:662:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:739:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/conn.go:733:
2017/11/27 11:39:38.011 2pc.go:558: [info] 2PC clean up done, tid: 396297234790481923
2017/11/27 11:39:38.011 simple.go:127: [info] [623] execute rollback statement
2017/11/27 11:39:38.011 txn.go:184: [info] [kv] Rollback txn 396297234803589121
2017/11/27 11:39:38.406 simple.go:127: [info] [626] execute rollback statement
2017/11/27 11:39:38.406 txn.go:184: [info] [kv] Rollback txn 396297234881970178
2017/11/27 11:39:48.259 coprocessor.go:336: [info] [TIME_COP_TASK] 10.229994968s backoff(4108ms [txnLockFast txnLockFast txnLockFast txnLockFast txnLockFast txnLockFast]) region(896 5 58) ranges(1) store(10.120.13.222:20160)
2017/11/27 11:39:48.259 adapter.go:293: [warning] slow-query costTime=10.240154202s sql=SELECT count(c_id) FROM customer WHERE c_w_id = ? AND c_d_id = ? AND c_last = ? type=slow-query connectionId=623 succ=true
2017/11/27 11:39:54.504 session.go:302: [warning] [623] retryable error: [try again later]: tikv restarts txn: Txn(Mvcc(WriteConflict { start_ts: 396297234803589122, conflict_ts: 396297235799474178, key: [116, 128, 0, 0, 0, 0, 0, 2, 255, 27, 95, 114, 128, 0, 0, 0, 0, 255, 0, 0, 1, 0, 0, 0, 0, 0, 250], primary: [116, 128, 0, 0, 0, 0, 0, 2, 27, 95, 114, 128, 0, 0, 0, 0, 0, 0, 1] })), txn: <nil>
2017/11/27 11:39:54.504 session.go:312: [warning] [623] finished txn:<nil>, [623] can not retry select for update statement
2017/11/27 11:39:54.504 session.go:660: [warning] [623] session error:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:393: [623] can not retry select for
update statement
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:313:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:331:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/tidb.go:172:
{
  "currDBName": "tpcc1000",
  "id": 623,
  "preparedStmtCount": 35,
  "status": 0,
  "strictMode": false,
  "user": {
    "Username": "root",
    "Hostname": "127.0.0.1"
  }
} 

改如何进一步分析？从数据看比单实例的mysql 测试要慢近10倍

**Comment by zzx8170** [comment]
download tpcc bench tools from url： https://github.com/pingcap/tidb-bench/tree/cwen/not_prepared_statement/sysbench

result as follow when executing tpcc-start with 1,2,4,8,16,32,64 concurrency ：

session/tpmc
1      367.000 TpmC
2     283.000 TpmC
4      286.000 TpmC
8     361.000 TpmC
16     321.000 TpmC
32     383.000 TpmC
64     365.000 TpmC

some error log occur in test duration,as follow:
payment 2:10
1105, HY000, [892] can not retry select for update statement
neword 0:9
1105, HY000, [891] can not retry select for update statement
payment 3:10
1105, HY000, [889] can not retry select for update statement

tidb.log occur some error log：
2017/11/28 14:23:53.415 conn.go:427: [warning] [967] dispatch error:
id:967, addr:127.0.0.1:17931 status:0, collation:latin1_swedish_ci, user:root
"commit"
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:393: [967] can not retry select for
update statement
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:313:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:331:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/tidb.go:172:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:662:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:739:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/server/conn.go:733:
2017/11/28 14:23:53.416 2pc.go:558: [info] 2PC clean up done, tid: 396322466386411522
2017/11/28 14:23:53.416 simple.go:127: [info] [967] execute rollback statement
2017/11/28 14:23:53.416 txn.go:184: [info] [kv] Rollback txn 396322467579166721
2017/11/28 14:23:54.231 coprocessor.go:336: [info] [TIME_COP_TASK] 8.87818939s backoff(8841ms [txnLockFast txnLockFas
t txnLockFast txnLockFast txnLockFast txnLockFast txnLockFast txnLockFast]) region(1166 5 62) ranges(1) store(10.120.
13.222:20160)
2017/11/28 14:23:54.232 adapter.go:293: [warning] slow-query sql=SELECT count(c_id) FROM customer WHERE c_w_id = ? AN
D c_d_id = ? AND c_last = ? type=slow-query connectionId=963 succ=true costTime=8.887599414s
2017/11/28 14:23:54.242 session.go:302: [warning] [963] retryable error: [try again later]: tikv restarts txn: Txn(Mv
cc(WriteConflict { start_ts: 396322465455800322, conflict_ts: 396322467513630721, key: [116, 128, 0, 0, 0, 0, 0, 2, 2
55, 68, 95, 114, 128, 0, 0, 0, 0, 255, 0, 0, 5, 0, 0, 0, 0, 0, 250], primary: [116, 128, 0, 0, 0, 0, 0, 2, 68, 95, 11
4, 128, 0, 0, 0, 0, 0, 0, 5] })), txn: <nil>
2017/11/28 14:23:54.242 session.go:312: [warning] [963] finished txn:<nil>, [963] can not retry select for update sta
tement
2017/11/28 14:23:54.242 session.go:660: [warning] [963] session error:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:393: [963] can not retry select for
update statement
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:313:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/session.go:331:
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/tidb.go:172:
{
  "currDBName": "tpcc1000",
  "id": 963,
  "preparedStmtCount": 35,
  "status": 0,
  "strictMode": false,
  "user": {
    "Username": "root",
    "Hostname": "127.0.0.1"
  }
} 


but single mysql instance，result as follow：
1 974.200 TpmC
2 2263.400 TpmC 
4 3979.400 TpmC
8 6161.600 TpmC
16  7520.600 TpmC
32 8178.200 TpmC
64 8263.400 TpmC

diff so large between tidb and single mysql instance，why？

**Comment by zimulala** [comment]
@zzx8170 
The SQL of `select for update` can't be retried in TiDB.  So in this case, its performance is not good.

**Comment by shenli** [comment]
@zzx8170 For TiDB the `select for update` statement will fail if it meet any conflict. So we need to modify tpcc to fit TiDB.
We usually use sysbench to test the performance. We could try it.

**Comment by zzx8170** [comment]
what statement can conflict with select for update? can't find from doc.

**Comment by morgo** [comment]
@zzx8170 Usually if there is a conflict (i.e. two transactions modified the same row) a retry will occur, and both transactions will succeed, but with some delay.  In the case of `select for update`, retry is disabled, and the transaction will return an error.

In a pessimistic locking system (like InnoDB), one transaction would instead block waiting on the lock until the other commits.

I hope this helps, please let me know if you have any further questions.

**Comment by nullnotnil** [comment]
The default locking in TIDB has changed to pessimistic, so the behavior will now be similar to InnoDB.

I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
