### ISSUE TITLE
How about importing  gkvdb into TiDB ?

### ISSUE THREAD

**Issue by bhzhu203** [pingcap/tidb#5217]
http://johng.cn/gkvdb-brief/

gkvdb  is a key vaule database which  seems having a excellent design.

**Comment by shenli** [comment]
@bhzhu203 Thanks for your suggestion. It is OK to use any storage engine which could provide a Golang client that implements the [Storage](https://github.com/pingcap/tidb/blob/master/kv/kv.go#L216) interface  as the storage engine for TiDB.

**Comment by tiancaiamao** [comment]
Actually, implement the interface need a storage that support scan operation.

**Comment by shenli** [comment]
@tiancaiamao Scan operation is required by the  [Snapshot](https://github.com/pingcap/tidb/blob/master/kv/kv.go#L201) interface which is the return value of [Storage.GetSnapshot()](https://github.com/pingcap/tidb/blob/master/kv/kv.go#L223) .
