### ISSUE TITLE
move lightning out of br directory

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#52182]
## Enhancement

lightning is separate product, but its code resides in `br/` directory due to history reasons, they do have some code in common, but most are not. it would be better to move it out, here is proposal:

- move `br/pkg/lightning` to `pkg/lightning`(as add-index and import-into depends on lightning too) or `lightning/`
  - or move codes common in lightning/add-index/import-into into `pkg/`, leave others inside `lightning/`
- move code common to br and lightning out into `pkg/`, such as
  - br/pkg/httputil"
  - br/pkg/membuf"
  - br/pkg/pdutil"
  - br/pkg/restore/split"
  - br/pkg/storage"
- some folder might not that easy to move such as `br/tests/lightning*`, they requires changing CI too, we can leave them there

**Comment by bb7133** [comment]
@D3Hunter I see now we have both `lightning` and `pkg/lightning` directories, please make sure this is an intermediate state.

**Comment by D3Hunter** [comment]
> @D3Hunter I see now we have both `lightning` and `pkg/lightning` directories, please make sure this is an intermediate state.

the top level `lightning` is for TiDB-lightning. `pkg/lightning` is for codes that's reused by TiDB-lightning/add-index/import-into, there are a few packages inside, i think we can keep this level of directory, so it's final. any ideas?
