### ISSUE TITLE
Would you please add Docker images support? 

### ISSUE THREAD

**Issue by netroby** [pingcap/tidb#522]
Would you please add Docker images ?
Docker container will be friendly for dev and deploy.

**Comment by ngaut** [comment]
Yes, sure. Would you like to do it?

**Comment by netroby** [comment]
Ok, May be it is a good start to setup a minimal TiDB Server docker container.

**Comment by ngaut** [comment]
Yep :)

**Comment by netroby** [comment]
https://github.com/pingcap/tidb/pull/566
