### ISSUE TITLE
arm/386 build fail

### ISSUE THREAD

**Issue by JonesSun** [pingcap/tidb#5224]
# github.com/pingcap/tidb/mysql
mysql\const.go:498:2: constant 2147483648 overflows SQLMode
mysql\const.go:499:2: constant 4294967296 overflows SQLMode
mysql\util.go:44:19: constant 4294967295 overflows int
mysql\util.go:45:19: constant 4294967295 overflows int

**Comment by tiancaiamao** [comment]
In production environment, TiDB is usually used under linux/64bit, **we don't release or provide maintenance for other system/platform**.
Many of us use osx for developing, that's okay, but arm/386 is not tested.
If you're interested, welcome to send a PR to fix it.
@JonesSun

**Comment by shenli** [comment]
We do not consider i386 platform. It is rarely used in production environment.
