### ISSUE TITLE
Unexpected values appeared in select query statements that should logically imply each other

### ISSUE THREAD

**Issue by Okakura-Tenshin** [pingcap/tidb#52262]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

 In theory,the result of sql2(distinct)  ∈  the result of sql1

 however,the value -20171112000000.100000 change to -2017111200000 after adding DISTINCT,which seems like a logical bug
### 1. Minimal reproduce step (Required)
```
create table table_3_utf8_undef (
`pk` int primary key,
`col_bigint_undef_signed` bigint  ,
`col_bigint_undef_unsigned` bigint unsigned ,
`col_bigint_key_signed` bigint  ,
`col_bigint_key_unsigned` bigint unsigned ,
`col_float_undef_signed` float  ,
`col_float_undef_unsigned` float unsigned ,
`col_float_key_signed` float  ,
`col_float_key_unsigned` float unsigned ,
`col_double_undef_signed` double  ,
`col_double_undef_unsigned` double unsigned ,
`col_double_key_signed` double  ,
`col_double_key_unsigned` double unsigned ,
`col_decimal(40, 20)_undef_signed` decimal(40, 20)  ,
`col_decimal(40, 20)_undef_unsigned` decimal(40, 20) unsigned ,
`col_decimal(40, 20)_key_signed` decimal(40, 20)  ,
`col_decimal(40, 20)_key_unsigned` decimal(40, 20) unsigned ,
`col_char(20)_undef_signed` char(20)  ,
`col_char(20)_key_signed` char(20)  ,
`col_varchar(20)_undef_signed` varchar(20)  ,
`col_varchar(20)_key_signed` varchar(20)  ,
key (`col_bigint_key_signed`),
key (`col_bigint_key_unsigned`),
key (`col_float_key_signed`),
key (`col_float_key_unsigned`),
key (`col_double_key_signed`),
key (`col_double_key_unsigned`),
key (`col_decimal(40, 20)_key_signed`),
key (`col_decimal(40, 20)_key_unsigned`),
key (`col_char(20)_key_signed`),
key (`col_varchar(20)_key_signed`)
) character set utf8 ;
insert into table_3_utf8_undef values (0,82.1847,1,39.0425,38.1089,-1,1,94.1106,1.009,12.991,19755,-13064,0,1,79.1429,-2,1,'well','3
','-0','e'),(1,1,20.0078,-9.183,68.1957,1,2,1,0.0001,12.991,2,71.0510,1,-1,2,12.991,12.991,'3	','1','3	','-0'),(2,-2,1,-21247,1.009,2,1.009,0.0001,36.0002,-2,2,-0,0.0001,-2,0.1598,47.1515,1.009,'3	','w','-1','e');
create table table_7_utf8_undef (
`pk` int primary key,
`col_bigint_undef_signed` bigint  ,
`col_bigint_undef_unsigned` bigint unsigned ,
`col_bigint_key_signed` bigint  ,
`col_bigint_key_unsigned` bigint unsigned ,
`col_float_undef_signed` float  ,
`col_float_undef_unsigned` float unsigned ,
`col_float_key_signed` float  ,
`col_float_key_unsigned` float unsigned ,
`col_double_undef_signed` double  ,
`col_double_undef_unsigned` double unsigned ,
`col_double_key_signed` double  ,
`col_double_key_unsigned` double unsigned ,
`col_decimal(40, 20)_undef_signed` decimal(40, 20)  ,
`col_decimal(40, 20)_undef_unsigned` decimal(40, 20) unsigned ,
`col_decimal(40, 20)_key_signed` decimal(40, 20)  ,
`col_decimal(40, 20)_key_unsigned` decimal(40, 20) unsigned ,
`col_char(20)_undef_signed` char(20)  ,
`col_char(20)_key_signed` char(20)  ,
`col_varchar(20)_undef_signed` varchar(20)  ,
`col_varchar(20)_key_signed` varchar(20)  ,
key (`col_bigint_key_signed`),
key (`col_bigint_key_unsigned`),
key (`col_float_key_signed`),
key (`col_float_key_unsigned`),
key (`col_double_key_signed`),
key (`col_double_key_unsigned`),
key (`col_decimal(40, 20)_key_signed`),
key (`col_decimal(40, 20)_key_unsigned`),
key (`col_char(20)_key_signed`),
key (`col_varchar(20)_key_signed`)
) character set utf8 ;
insert into table_7_utf8_undef values (0,-9.183,1,1.1384,2,15.1271,12.991,-2,0.0001,36.1270,79.1819,0.0001,0.0001,3.1387,52.0818,-0,0.0001,'1','3	','0','0'),(1,79,12.991,107,2,-0.0001,0,1.009,1.009,34,1,-1,69.0208,1,2,120,12.991,'3	','-1','if','b'),(2,-2,1,-9.183,1,12.991,0.0001,53,12.991,1.009,12.991,12.991,0.0001,-0.0001,12.991,0.0001,2,'3
','p','0','3	'),(3,-0.0001,12.991,1.009,1.009,-9.183,2,0,1,-2,1,2,1,2,1.009,2,12.991,'3
','0','k','0'),(4,1.009,0.0001,-1,12.991,2,47,2,0,12.991,12.991,1.009,0,1.009,1.009,-0.0001,6949,'-1','	3','1','m'),(5,-0,1,0,0,0.0001,28.1237,12.991,0,12.991,12.991,-0,12.991,2,2,2,1.009,'0','	3','0','	3'),(6,45.0855,1,38.1166,1,1.009,80.0284,2,122,0.0001,0,-1,11130,0,1,1,0,'know','-0','
3','3
');
```
sql1
```
SELECT 
  (_UTF8MB4'r' - OCTET_LENGTH(`f5`) * SQRT(8)) AS `f2`,
  (-`f4`) AS `f3`
FROM 
  (SELECT `col_decimal(40, 20)_key_signed` AS `f5` 
   FROM `table_3_utf8_undef`) AS `t1`
NATURAL JOIN 
  (SELECT (DATE_ADD(DATE(_UTF8MB4'2017-11-12 08:48:25'), INTERVAL 1 HOUR_MICROSECOND)) AS `f4` 
   FROM 
     (SELECT `col_double_undef_unsigned` AS `f10`,
             `col_decimal(40, 20)_undef_unsigned` AS `f12` 
      FROM `table_7_utf8_undef`) AS `t2` 
   WHERE 
     ((((COERCIBILITY(`f12`)) BETWEEN 1 AND _UTF8MB4'l') IS FALSE))) AS `t3`;

```
sql2
```
SELECT DISTINCT
  (_UTF8MB4'r' - OCTET_LENGTH(`f5`) * SQRT(8)) AS `f2`,
  (-`f4`) AS `f3`
FROM
  (SELECT `col_decimal(40, 20)_key_signed` AS `f5`
   FROM `table_3_utf8_undef`) AS `t1`
NATURAL JOIN
  (SELECT (DATE_ADD(DATE(_UTF8MB4'2017-11-12 08:48:25'), INTERVAL 1 HOUR_MICROSECOND)) AS `f4`
   FROM
     (SELECT `col_double_undef_unsigned` AS `f10`,
             `col_decimal(40, 20)_undef_unsigned` AS `f12`
      FROM `table_7_utf8_undef`) AS `t2`
   WHERE
     ((((COERCIBILITY(`f12`)) BETWEEN 1 AND _UTF8MB4'l') IS FALSE))) AS `t3`;

```
### 2. What did you expect to see? (Required)
sql1
```
 f2         |           f3           
--------------------+------------------------
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
 -65.05382386916237 | -20171112000000.100000 
```
sql2
```
 f2         |           f3           
--------------------+------------------------
 -65.05382386916237 | -20171112000000.100000 
```

### 3. What did you see instead (Required)
sql2
```
     f2         |       f3        
--------------------+-----------------
 -65.05382386916237 | -20171112000000 
(1 row)
```

### 4. What is your TiDB version? (Required)
tidb 7.6

**Comment by yibin87** [comment]
Reproduced using latest tidb.

**Comment by Okakura-Tenshin** [comment]
> Reproduced using latest tidb.

I have reproduced it in TiDB 8.0, and the results are the same as what I mentioned above.

**Comment by yibin87** [comment]
Narrow down the issue SQL to:
```
SELECT DISTINCT
  `f5`,
  (-`f4`) AS `f3`
FROM
  (SELECT `col_decimal(40, 20)_key_signed` AS `f5`
   FROM `table_3_utf8_undef`) AS `t1`
NATURAL JOIN
  (SELECT (DATE_ADD(DATE('2017-11-12 08:48:25'), INTERVAL 1 HOUR_MICROSECOND)) AS `f4` 
   FROM `table_7_utf8_undef`) AS `t2`;
```

**Comment by kennedy8312** [comment]
The issue happen on v5.4.0 as well.
    ->      ((((COERCIBILITY(`f12`)) BETWEEN 1 AND _UTF8MB4'l') IS FALSE))) AS `t3`;
+--------------------+-----------------+
| f2                 | f3              |
+--------------------+-----------------+
| -65.05382386916237 | -20171112000000 |
+--------------------+-----------------+
1 row in set, 2 warnings (0.00 sec)

mysql>
mysql>
mysql>
mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                       |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v5.4.0
Edition: Community
Git Commit Hash: 55f3b24c1c9f506bd652ef1d162283541e428872
Git Branch: heads/refs/tags/v5.4.0
UTC Build Time: 2022-01-25 08:41:03
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

**Comment by yibin87** [comment]
> Narrow down the issue SQL to:
> 
> ```
> SELECT DISTINCT
>   `f5`,
>   (-`f4`) AS `f3`
> FROM
>   (SELECT `col_decimal(40, 20)_key_signed` AS `f5`
>    FROM `table_3_utf8_undef`) AS `t1`
> NATURAL JOIN
>   (SELECT (DATE_ADD(DATE('2017-11-12 08:48:25'), INTERVAL 1 HOUR_MICROSECOND)) AS `f4` 
>    FROM `table_7_utf8_undef`) AS `t2`;
> ```

Further narrow down to:
SELECT DISTINCT
  `f5`,
  (-`f4`) AS `f3`
FROM
   (SELECT `col_bigint_undef_signed` as `f5`, (DATE_ADD(DATE('2017-11-12 08:48:25'), INTERVAL 1 HOUR_MICROSECOND)) AS `f4`
   FROM `table_7_utf8_undef`) AS `t2`;

**Comment by onlyacat** [comment]
Simplified the step and got the minimal sql to reproduce:
```sql
select distinct -cast(0.1 as time(1));
```
compared with 
```sql
select -cast(0.1 as time(1));
```

For now I suspect the reason may come from the Agg proceduce, in which the fraction has been discard.

**Comment by yibin87** [comment]
It seems the RetType of FirstRowFunc is wrong, will debug further.

**Comment by yibin87** [comment]
It turned out that the minus function's return type is incorrectly inferred in this function:
https://github.com/pingcap/tidb/blob/d2eb9026a476dd76a3fbb9449834867c4ad2a87b/pkg/expression/builtin.go#L146
It doesn't take any affect when no distinct key word is added. However, when 'distinct' is added, the minus function becomes the argument of firstRow, and firstRow will use the incorrect return type. It will cause the precision lose problem here.
