### ISSUE TITLE
The execution plan is displayed incorrectly in the tidb-dashboard 

### ISSUE THREAD

**Issue by vcdog** [pingcap/tidb#52303]
## Bug Report
详见此帖：
https://asktug.com/t/topic/1023977/1

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
对生产环境的一张业务大表进行analyze收集后，运行了几天，发现在dashboard统计到的同样的SQL的执行计划和命令行的执行计划不一样。
1.这个是从tidb dashboard里截取的执行计划：
![9fd91e67cb70c111e5a9ed6a820c3f10b28932c0_2_1035x505](https://github.com/pingcap/tidb/assets/7135182/c12ec89c-4396-4f7c-ae65-9a8c3476b363)

2.这个是命令行截取的执行计划：

![14263fcd4a06f69e2839267d56d5ff55e22b83c8](https://github.com/pingcap/tidb/assets/7135182/caf61eaf-2100-443a-b1c3-ca26862486e3)
![5e3e9cf90fc1f43c5a6af33c21d078237092f678](https://github.com/pingcap/tidb/assets/7135182/dcb25f2f-8638-4955-a82e-6960abaad483)
![a4cea365c99dae54e4a2141eb075bd6944c6bb30_2_1035x396](https://github.com/pingcap/tidb/assets/7135182/5f84b250-c1c8-4baa-9376-3214d7da0c0c)

**Comment by hawkingrei** [comment]
I cannot see any image.

**Comment by time-and-fate** [comment]
The "cop" should be a display error and it's actually "mpp".
This should be already resolved from v7.4.0. From v7.4.0, the execution plan on the dashboard should be consistent with what you see from the EXPLAIN ANALYZE statement.
Before v7.4.0, you can choose the "visual（图形）" tab, which provides a different view and should be correct.

**Comment by time-and-fate** [comment]
Closing this issue since it's solved in the newer version. Feel free to reopen it or create a new issue if there are further problems.
