### ISSUE TITLE
[FATAL] [lib.rs:477] ["called `Result::unwrap()` on an `Err` value: ParseIntError { kind: PosOverflow }"]

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#52356]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1 ( c1 float);
INSERT INTO t1 (c1) VALUES (-1.6175244930418992E38);
SELECT c1 FROM t1 WHERE CONV(c1, 8, 6);
```
### 2. What did you expect to see? (Required)
The statement is normally executed.
### 3. What did you see instead (Required)
The server crashed.
### 4. What is your TiDB version? (Required)

Release Version: v8.0.0
Edition: Community
Git Commit Hash: 8ba1fa452b1ccdbfb85879ea94b9254aabba2916
Git Branch: HEAD
UTC Build Time: 2024-03-28 14:22:15
GoVersion: go1.21.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by yibin87** [comment]
Checked that the issue exists in 5.4.0 also. It is corner case that the conv's first argument should be out of integer value range. Besides, this case can be workaround by rewrite the sql like:
select c1 FROM t1 WHERE CONV(cast(c1 as decimal(64,0)), 8, 6);
Thus, change the severity to major.

**Comment by gengliqi** [comment]
fixed by https://github.com/tikv/tikv/pull/16970
