### ISSUE TITLE
Table's last analyze time is not null while it is not analyzed in fact

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#52357]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

![image](https://github.com/pingcap/tidb/assets/7846227/892f1214-1c72-498b-bf35-44af65ce0890)

As you can see, the histogram is a fake one. This table has no stats. But its last analyze time is not NULL.

**Comment by hi-rustin** [comment]
I cannot reproduce this problem. I tried restoring from the BR and checking the stats_meta. They were all normal.

**Comment by fixdb** [comment]
Closing this issue since it is not reproducible.
