### ISSUE TITLE
qps drop to bottom when inject one of tikv failure 10mins with tidb "enable-forwarding = true"

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#52394]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run tpcc
          db : tpcc20000
          warehouse : 20000
          threads : 32
2、config tidb 
     "enable-forwarding = true"
3、inject one of tikv failure 10mins

### 2. What did you expect to see? (Required)
qps can recover within 2mins after inject one of tikv fault

### 3. What did you see instead (Required)
qps drop to bottom during  injectting fault
![img_v3_029n_bb5942ea-da94-4709-b86b-4cee992a4a3g](https://github.com/pingcap/tidb/assets/84712107/36902903-57ae-4640-a17f-60612d7efb1f)

### 4. What is your TiDB version? (Required)
git-hash：555ce0235229dc370cc8e63574437cf9ee60bdd0

**Comment by crazycs520** [comment]
This issue is only occure when TiDB config has `enable-forwarding = true`.

See more detail in https://github.com/tikv/client-go/issues/1274
