### ISSUE TITLE
Create JSON generated field table,  The integrity of creating a table is broken

### ISSUE THREAD

**Issue by neil4dong** [pingcap/tidb#5253]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Create a new table contains json generated column

CREATE TABLE `xxxxxxxx` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `x1` bigint(20) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x1')) STORED NOT NULL ,
  `x2` bigint(20) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x2')) VIRTUAL ,
  `x3` bigint(20) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x3')) VIRTUAL,
  `x4` json GENERATED ALWAYS AS (json_unquote(json_extract(`json_field`,'$.x4'))) VIRTUAL ,
  `x5` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x5')) VIRTUAL ,
  `x6` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x6')) VIRTUAL ,
  `x7` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x7')) VIRTUAL ,
  `x8` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x8')) VIRTUAL ,
  `x9` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x9')) VIRTUAL ,
  `x10` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x10')) VIRTUAL ,
  `x11` varchar(50) GENERATED ALWAYS AS (json_unquote(json_extract(`json_field`,'$.x11'))) VIRTUAL ,
  `x12` datetime GENERATED ALWAYS AS (cast(json_unquote(json_extract(`json_field`,'$.x12')) as datetime)) VIRTUAL ,
  `x13` datetime GENERATED ALWAYS AS (cast(json_unquote(json_extract(`json_field`,'$.x13')) as datetime)) VIRTUAL ,
  `json_field` json NOT NULL ,
  `x15` datetime GENERATED ALWAYS AS (cast(json_unquote(json_extract(`json_field`,'$.x15')) as datetime)) VIRTUAL ,
  `x16` int(11) GENERATED ALWAYS AS (json_extract(`json_field`,'$.x16')) VIRTUAL,
  `x17` tinyint(1) NOT NULL DEFAULT '1' ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_x1` (`x1`)
) ENGINE=InnoDB AUTO_INCREMENT=1388 DEFAULT CHARSET=utf8 ;
 

2. What did you expect to see?

3. What did you see instead?

Error Code: 1105. line 1 column 70 near ")" (total length 71)	20.125 sec

When Execute the DDL again：the server response the table already exists。

Besides the problem above which is acceptable, the another problem could be devastating **the tidb-server cannot restart after stopped。** 
**It seems that the integrity of creating a table is broken。**
log：2017/11/28 19:10:05.761 domain.go:486: [error] [ddl] new domain failed line 1 column 80 near ")" (total length 81)

4. What version of TiDB are you using (`tidb-server -V`)?

The newest version on docker.  the server is broken,so i cannot run  (`tidb-server -V`)

**Comment by zimulala** [comment]
@neil4dong 
We will handle it. Thanks for your report.
PTAL @hicqu

**Comment by neil4dong** [comment]
Release Version: v1.1.0-alpha-160-gb6e49c9
Git Commit Hash: b6e49c9bf923b57d6777b1f030750641336c06fb
Git Commit Branch: master
UTC Build Time:  2017-11-26 03:41:30

**Comment by neil4dong** [comment]
any further？

**Comment by hicqu** [comment]
It's a little bug. Fixed by #5262 , which may be merged later. Thanks for your report.

**Comment by XuHuaiyu** [comment]
@neil4dong 
We are working on this issue.
It may take a little time to fix it perfectly.
