### ISSUE TITLE
Restore txn kv fails and reports ErrRestoreInvalidRange

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#52574]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create a pure txn cluster(1 tikv, 1 pd)
2. rand generate txn data.
3. backup txn 
4. restore txn

repeat above steps several times.

### 2. What did you expect to see? (Required)
restore txn always success.

### 3. What did you see instead (Required)
sometimes failed and reported
[BR:Restore:ErrRestoreInvalidRange]invalid restore range\n    startKey > endKey xxx
### 4. What is your TiDB version? (Required)
master

**Comment by SonglinLife** [comment]
Similar issue, can you please take a look?
