### ISSUE TITLE
check `schema` in job2UniqueIDs for TruncateTable

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#52589]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

we use this function to return schema ids and table ids, so should check `schema` here
https://github.com/pingcap/tidb/blob/69d7770335a7611d05bb2f3a0888c79afb03e92a/pkg/ddl/job_table.go#L588-L589

### 4. What is your TiDB version? (Required)
master

**Comment by zimulala** [comment]
It seems this problem caused by the PR: https://github.com/pingcap/tidb/pull/40501
