### ISSUE TITLE
Encounter error when importing CSV data into TiDB

### ISSUE THREAD

**Issue by SepCorvus** [pingcap/tidb#5258]
向tidb中导入csv数据时，一直发生如下的错误，导致导入中断。
Error encountered when performing Introspect schema test: line 4 column 33 near " by seq_in_index separator '\n') as column_names,   non_unique from information_schema.statistics where table_schema = 'test' and       index_schema = 'test' and       index_name <> 'PRIMARY' group by   table_catalog,   table_schema,   table_name,   index_name,   index_type,   non_unique" (total length 395). line 4 column 33 near " by seq_in_index separator '\n') as column_names,   non_unique from information_schema.statistics where table_schema = 'test' and       index_schema = 'test' and       index_name <> 'PRIMARY' group by   table_catalog,   table_schema,   table_name,   index_name,   index_type,   non_unique" (total length 395)  (215ms)

**Comment by winoros** [comment]
Could you show us the data format in csv and the sql to reproduce the issue?

**Comment by SepCorvus** [comment]
tidb日志

2017/11/29 13:29:31.863 session.go:731: [warning] [1] parse error:
line 4 column 33 near " by seq_in_index separator '\n') as column_names,
  non_unique
from information_schema.statistics
where table_schema = 'test' and
      index_schema = 'test' and
      index_name <> 'PRIMARY'
group by
  table_catalog,
  table_schema,
  table_name,
  index_name,
  index_type,
  non_unique" (total length 395)
/* ApplicationName=DataGrip 2017.2.2 */ select
  table_name,
  index_name,
  group_concat(column_name order by seq_in_index separator '\n') as column_names,
  non_unique
from information_schema.statistics
where table_schema = 'test' and
      index_schema = 'test' and
      index_name <> 'PRIMARY'
group by
  table_catalog,
  table_schema,
  table_name,
  index_name,
  index_type,
  non_unique
2017/11/29 13:29:31.863 conn.go:430: [warning] [1] dispatch error:
id:1, addr:10.255.0.2:56421 status:1, collation:utf8_general_ci, user:root
"/* ApplicationName=DataGrip 2017.2.2 */ select\n  table_name,\n  index_name,\n  group_concat(column_name order by seq_in_index separator '\\n') as column_names,\n  non_unique\nfrom information_schema.statistics\nwhere table_schema = 'test' and\n      index_schema = 'test' and\n      index_name <> 'PRIMARY'\ngroup by\n  table_catalog,\n  table_schema,\n  table_name,\n  index_name,\n  index_type,\n  non_unique"
line 4 column 33 near " by seq_in_index separator '\n') as column_names,
  non_unique
from information_schema.statistics
where table_schema = 'test' and
      index_schema = 'test' and
      index_name <> 'PRIMARY'
group by
  table_catalog,
  table_schema,
  table_name,
  index_name,
  index_type,
  non_unique" (total length 395)
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session.go:732: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:744: 
2017/11/29 13:29:44.611 session.go:731: [warning] [2] parse error:
line 4 column 33 near " by seq_in_index separator '\n') as column_names,
  non_unique
from information_schema.statistics
where table_schema = 'test' and
      index_schema = 'test' and
      index_name <> 'PRIMARY'
group by
  table_catalog,
  table_schema,
  table_name,
  index_name,
  index_type,
  non_unique" (total length 395)
/* ApplicationName=DataGrip 2017.2.2 */ select
  table_name,
  index_name,
  group_concat(column_name order by seq_in_index separator '\n') as column_names,
  non_unique
from information_schema.statistics
where table_schema = 'test' and
      index_schema = 'test' and
      index_name <> 'PRIMARY'
group by
  table_catalog,
  table_schema,
  table_name,
  index_name,
  index_type,
  non_unique

CSV:
deviceId,rtime,sa,wtime
73,1511360763,b0:e2:35:45:1d:43,1511361060
73,1511360763,cc:25:ef:9d:f2:df,1511361060

**Comment by XuHuaiyu** [comment]
@SepCorvus 
`group_concat(column_name order by seq_in_index separator '\n') as column_names`
TiDB only support the syntax `GROUP_CONCAT([DISTINCT] expr [,expr ...])` now, so the query will cause a parse error.
How do you load the CSV file into TiDB?

**Comment by SepCorvus** [comment]
@XuHuaiyu 
Datagrip   ==> Import Data from File

**Comment by XuHuaiyu** [comment]
We'll take a look. @SepCorvus

**Comment by XuHuaiyu** [comment]
@SepCorvus 
You may try [load data](https://dev.mysql.com/doc/refman/5.7/en/load-data.html) command from the console to load the CSV file into table.
It seems Datagrip will autorun a sql whose syntax has not been fully supported as the former commet says when click `Import Data from File`.

**Comment by SepCorvus** [comment]
@XuHuaiyu 
OK
