### ISSUE TITLE
fast-path should support column projection pushdown

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#52592]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The fast-path point get in TiDB fetch the whole row from TiKV. There is no column projection pushdown for fast-path Get request as Cop result. This can cause performance degradation in below scenarios are:

1. Wide tables with many columns, where applications only query a few columns.
2. JSON fields with large column values, where queries may not necessarily retrieve the values of JSON columns or only extract specific small JSON content. 

**Describe the feature you'd like:**

fast-path point get should support column projection pushdown to TiKV, to reduce the GRPC response message size from TiKV and improve the performance, as well as the resource utilization.
Tn addition, the optimizer need to be aware it's worth to do column projection base on the statistics.

**Describe alternatives you've considered:**

none

**Teachability, Documentation, Adoption, Migration Strategy:**

performance enhancement.

**Comment by winoros** [comment]
To reduce further misunderstanding, I updated the title based on the final fixcontrol.

And due to there being some challenges in supporting the column pruning for the Get API, we just provide a fix control to disable generating a plan using the Get API.
