### ISSUE TITLE
current infoschema.SchemaByID is O(db_num) intead of constant time

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#52610]
## Enhancement

The infoschema only has a `map[string]*DBInfo` struct. So if we want to find the *DBInfo by its ID, the time complexity will become `O(n)` instead of O(1).

And the number of databases has increased quickly. Some customers want to put 300K databases into one TiDB cluster.

**Comment by D3Hunter** [comment]
it also causes performance degradation with many databases using non-prepared statement
