### ISSUE TITLE
Auth failed message show password instead of account.

### ISSUE THREAD

**Issue by BrickXu** [pingcap/tidb#5263]
1. What did you do?
A Flink streaming job with Spring jdbc template to flush data to TiDB.

2. What did you expect to see?
```
Access denied for user 'tf_fuwu_rw'@'zzzzzzzzz' (using password: YES)
```

3. What did you see instead?
```
Access denied for user 'tf_fu201931wu_rw'@'zzzzzzzzz' (using password: YES)
```

4. What version of TiDB are you using (`tidb-server -V`)?
```
Release Version: 1.0.0
Git Commit Hash: 1a175b562bc679694f606c336131a9373064b324
Git Commit Branch: release-1.0
UTC Build Time: 2017-10-19 02:38:02
```

Actually, `tf_fu201931wu_rw` is the password, not the usename, and we did not do anything to this job ( it works for about five days and works well ), but today the worker throws this exception with the wrong message, then we restart this job and this message does not occur.

**Comment by zz-jason** [comment]
@BrickXu Thanks for your feed back! @tiancaiamao PTAL.

**Comment by tiancaiamao** [comment]
Maybe something wrong with the String() method.
@breeswish PTAL

**Comment by breeswish** [comment]
Seems that we cannot easily reproduce this issue:

```
# breezewish @ ~/Work/PingCAP/src/github.com/pingcap/tidb on git:release-1.0 x [19:04:43] 
$ mysql -u root --column-type-info --host 127.0.0.1 --port 4000
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.1-TiDB-v1.0.3-1-ga80e796f MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> CREATE USER 'finley'@'localhost' IDENTIFIED BY 'password';
Query OK, 1 row affected (0.00 sec)

mysql> exit
Bye

# breezewish @ ~/Work/PingCAP/src/github.com/pingcap/tidb on git:release-1.0 x [19:06:27] 
$ mysql -u finley --column-type-info --host 127.0.0.1 --port 4000
ERROR 1045 (28000): Access denied for user 'finley'@'127.0.0.1' (using password: YES)

# breezewish @ ~/Work/PingCAP/src/github.com/pingcap/tidb on git:release-1.0 x [19:06:34] C:1
$ mysql -u finley --column-type-info --host 127.0.0.1 --port 4000 -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'finley'@'127.0.0.1' (using password: YES)

# breezewish @ ~/Work/PingCAP/src/github.com/pingcap/tidb on git:release-1.0 x [19:06:43] C:1
$ mysql -u finley --column-type-info --host 127.0.0.1 --port 4000 -p
Enter password: 
ERROR 1045 (28000): Access denied for user 'finley'@'127.0.0.1' (using password: YES)

# breezewish @ ~/Work/PingCAP/src/github.com/pingcap/tidb on git:release-1.0 x [19:06:46] C:1
$ 
```

@tiancaiamao any ideas?

**Comment by tiancaiamao** [comment]
I check the code, never find anywhere we use password as username in the error message. @breeswish 

Further more, in the handshake protocol, MySQL sends a MD5 hash encrypted password (not user's raw password), TiDB that password use a salt and encryption algorithm.
**TiDB never know or store user's raw password**, let alone return it as error message, so this issue must be a mistake, I'll close it.

If you can provide more detail to verify the issue, feel free to reopen it. @BrickXu

**Comment by BrickXu** [comment]
I never reproduce this issue these days. leave it as closed.

Thanks all of you.
