### ISSUE TITLE
For a key which is set as auto_increment, its value is not increased continuously if I restart tidb

### ISSUE THREAD

**Issue by PHILO-HE** [pingcap/tidb#5264]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I create a table by the following statement.
create table mytable(id INT AUTO_INCREMENT PRIMARY KEY, value INT);

When I insert a record by such statement.
insert into mytable(value) values(123);

The value of id can be initialized from 1 and can be set incrementally in the insert statement.

+----+-------+
| id | value |
+----+-------+
|  1 |   123 |
|  2 |   123 |
+----+-------+

But if I restart tidb and execute the insert statement as above, the value of id starts from 5001.

+------+-------+
| id   | value |
+------+-------+
|    1 |   123 |
|    2 |   123 |
| 5001 |   123 |
+------+-------+

2. What did you expect to see?

The value of id in the above table should auto increase continuously even though I restart tidb.  

3. What did you see instead?

I found the value of id is 5001, not 3, in the above example if i restart tidb.

4. What version of TiDB are you using (`tidb-server -V`)?
    Tidb-1.0.0-release. The version of Pd and Tikv instances is also 1.0.0-release.

**Comment by zimulala** [comment]
@PHILO-HE 
We don't support it.
You can refer to [docs-cn](https://github.com/pingcap/docs-cn/blob/master/sql/ddl.md) or [docs](https://github.com/pingcap/docs/blob/master/sql/ddl.md).

**Comment by PHILO-HE** [comment]
Got it. Thanks so much for your kindly reminder.

**Comment by zimulala** [comment]
@PHILO-HE 
Not at all.
