### ISSUE TITLE
Empty slow query text for a stmt that reads tidb_mdl_info

### ISSUE THREAD

**Issue by ekexium** [pingcap/tidb#52743]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Unknown. This seems to be an internal SQL.

### 2. What did you expect to see? (Required)

Slow query should display the query text.

### 3. What did you see instead (Required)

<img width="878" alt="image" src="https://github.com/pingcap/tidb/assets/31720476/ded13398-f5e0-4c5e-8e26-f5a3a3358a04">

The query text is empty.

### 4. What is your TiDB version? (Required)

master(8d9e67b37dea759db0980aeddf4da967bf93e83e)

**Comment by ekexium** [comment]
cc @wjhuang2016

**Comment by wjhuang2016** [comment]
It's an internal SQL, but it should not be empty for internal SQL?

**Comment by ekexium** [comment]
> It's an internal SQL, but it should not be empty for internal SQL?

Yes that's my expectation. Do you wanna take a look?

**Comment by wjhuang2016** [comment]
> > It's an internal SQL, but it should not be empty for internal SQL?
> 
> Yes that's my expectation. Do you wanna take a look?

I don't have an idea for it.

**Comment by ekexium** [comment]
<img width="1362" alt="image" src="https://github.com/pingcap/tidb/assets/31720476/33b11ea1-3d81-47a9-a218-bfa00fedd719">
<img width="1373" alt="image" src="https://github.com/pingcap/tidb/assets/31720476/c060598a-203d-4954-99eb-154170eff20a">
<img width="1365" alt="image" src="https://github.com/pingcap/tidb/assets/31720476/501884b2-35d9-4928-922b-46b723162338">
<img width="1336" alt="image" src="https://github.com/pingcap/tidb/assets/31720476/39b5dcf4-142a-4e58-be4f-77314a1da441">

Some other cases.
