### ISSUE TITLE
Lost connection to MySQL server during query

### ISSUE THREAD

**Issue by kevin19931015** [pingcap/tidb#5278]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
SELECT t1.*,t2.name as productName,t3.name as buildName,t4.name as projectName FROM `zt_testtask` AS t1 LEFT JOIN `zt_product` AS t2 ON t1.product=t2.id LEFT JOIN `zt_build` AS t3 ON t1.build=t3.id LEFT JOIN `zt_project` AS t4 ON t1.project=t4.id LEFT JOIN `zt_projectproduct` AS t5 ON t1.project=t5.project wHeRe t1.deleted = '0' AND t1.product IN ('7','6','4','3','1','5','2') AND t1.product = t5.product AND t1.status = 'wait' oRdEr bY t1.`id` desc lImiT 15;

2. What did you expect to see?
Get the data what I need.

3. What did you see instead?
ERROR 2013 (HY000): Lost connection to MySQL server during query

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: v1.1.0-alpha-195-g8a5b8d5

5. Tidb-log
2017/12/01 09:36:28.176 conn.go:391: [error] lastCmd SELECT t1.*,t2.name as productName,t3.name as buildName,t4.name as projectName FROM `zt_testtask` AS t1 LEFT JOIN `zt_product` AS t2 ON t1.product=t2.id LEFT JOIN `zt_build` AS t3 ON t1.build=t3.id LEFT JOIN `zt_project` AS t4 ON t1.project=t4.id LEFT JOIN `zt_projectproduct` AS t5 ON t1.project=t5.project wHeRe t1.deleted = '0' AND t1.product IN ('7','6','4','3','1','5','2') AND t1.product = t5.product AND t1.status = 'wait' oRdEr bY t1.`id` desc lImiT 15, runtime error: index out of range, goroutine 10434 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc421404210)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x10228a0, 0x1aef640)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/types.(*Datum).IsNull(...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/types/row.go:153
github.com/pingcap/tidb/types.DatumRow.IsNull(...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/types/row.go:153
github.com/pingcap/tidb/types.(*DatumRow).IsNull(0xc421633080, 0x17, 0x3)
        <autogenerated>:1 +0x58
github.com/pingcap/tidb/expression.(*Column).EvalInt(0xc42079d450, 0x1908640, 0xc421633080, 0xc421361f80, 0x3, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/column.go:216 +0x1a2
github.com/pingcap/tidb/expression.compareInt(0xc421632e20, 0x2, 0x2, 0x1908640, 0xc421633080, 0x18f5c20, 0xc420ad0d80, 0x61a8, 0xd80e01, 0x0, ...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1815 +0x14f
github.com/pingcap/tidb/expression.(*builtinEQIntSig).evalInt(0xc42115acc0, 0x1908640, 0xc421633080, 0x942394, 0xc42115acc0, 0x18f5c20, 0xc420ad0d80)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1425 +0x6a
github.com/pingcap/tidb/expression.(*ScalarFunction).EvalInt(0xc42115ad00, 0x1908640, 0xc421633080, 0xc421361f80, 0xc420097600, 0xc4224fa000, 0xc422a8a000, 0xc421c0d5f0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/scalar_function.go:223 +0x48
github.com/pingcap/tidb/expression.(*ScalarFunction).Eval(0xc42115ad00, 0x1908640, 0xc421633080, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/scalar_function.go:193 +0x2d6
github.com/pingcap/tidb/expression.EvalBool(0xc421a7a020, 0x1, 0x1, 0x1908640, 0xc421633080, 0x18f5c20, 0xc420ad0d80, 0x7f139ba14000, 0x0, 0x8)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/expression.go:103 +0xe1
github.com/pingcap/tidb/executor.(*SelectionExec).Next(0xc420b66850, 0x0, 0x10, 0xc4211f6280, 0x0, 0x10)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:510 +0x13a
github.com/pingcap/tidb/executor.(*TopNExec).Next(0xc420d46180, 0xc42118c300, 0x0, 0x1, 0x1, 0xc421b28070)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/sort.go:199 +0x529
github.com/pingcap/tidb/executor.(*ProjectionExec).Next(0xc420b668c0, 0x410a97, 0x3, 0xc42103ea80, 0xc4203caec0, 0x1086980)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:440 +0x5c
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc4212f0360, 0xc421c0db10, 0xef1543, 0xc4212f0360, 0xc421c0db00)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:77 +0x3e
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc4213423c0, 0x11fbd00, 0xc421c0dbd0, 0xc421c0dbe8, 0xef07b0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:294 +0x33
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc421404210, 0x18ef3c0, 0xc4213423c0, 0xc420130000, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:807 +0x257
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc421404210, 0x7f139b9341c0, 0xc4212866f0, 0xc4201321e1, 0x1cc, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:748 +0xfb

**Comment by kevin19931015** [comment]
I can get the data successfully when I am using tidb v1.0.0

**Comment by XuHuaiyu** [comment]
@kevin19931015 Thanks for your report.
Can the schema and data be provided?

**Comment by XuHuaiyu** [comment]
Please provide the explain info, thanks.

**Comment by kevin19931015** [comment]
when I use command line“show databases”，An error occurred。Is there any association with error above。
![image](https://user-images.githubusercontent.com/20453316/33465531-5509d95c-d683-11e7-94ec-a6b1debaa57c.png)

**Comment by kevin19931015** [comment]
This is an open-source project-manager project。
I am sorry not to learn its scheme。。。

**Comment by XuHuaiyu** [comment]
@kevin19931015 
```
desc SELECT t1.*,t2.name as productName,t3.name as buildName,t4.name as projectName FROM `zt_testtask` AS t1 LEFT JOIN `zt_product` AS t2 ON t1.product=t2.id LEFT JOIN `zt_build` AS t3 ON t1.build=t3.id LEFT JOIN `zt_project` AS t4 ON t1.project=t4.id LEFT JOIN `zt_projectproduct` AS t5 ON t1.project=t5.project wHeRe t1.deleted = '0' AND t1.product IN ('7','6','4','3','1','5','2') AND t1.product = t5.product AND t1.status = 'wait' oRdEr bY t1.`id` desc lImiT 15;
```
run the above sql in the console.

If possible, may the create table statements and part of insert data statements be provided?

**Comment by kevin19931015** [comment]
@XuHuaiyu 
+-----------------+-----------------+--------------------------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| id              | parents         | children                       | task | operator info                                                                                                                                                              | count              |
+-----------------+-----------------+--------------------------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+
| TableScan_34    | Selection_35    |                                | cop  | table:t1, range:(-inf,+inf), keep order:false                                                                                                                              |                  4 |
| Selection_35    |                 | TableScan_34                   | cop  | in(t1.product, 7, 6, 4, 3, 1, 5, 2)                                                                                                                                        |                  4 |
| TableReader_36  | Selection_33    |                                | root | data:Selection_35                                                                                                                                                          |                  4 |
| Selection_33    | IndexJoin_31    | TableReader_36                 | root | eq(t1.deleted, 0), eq(t1.status, wait)                                                                                                                                     |                3.2 |
| TableScan_29    |                 |                                | cop  | table:t2, range:(-inf,+inf), keep order:false                                                                                                                              |                  8 |
| TableReader_30  | IndexJoin_31    |                                | root | data:TableScan_29                                                                                                                                                          |                  8 |
| IndexJoin_31    | Projection_15   | Selection_33,TableReader_30    | root | outer:Selection_33, left outer join, outer key:t1.product, inner key:t2.id                                                                                                 |                3.2 |
| Projection_15   | HashLeftJoin_28 | IndexJoin_31                   | root | t1.id, t1.name, t1.product, t1.project, t1.build, t1.owner, t1.pri, t1.begin, t1.end, t1.mailto, t1.desc, t1.report, t1.status, t1.deleted, t2.id, t2.name, cast(t1.build) |                3.2 |
| TableScan_43    |                 |                                | cop  | table:t3, range:(-inf,+inf), keep order:false                                                                                                                              |                 21 |
| TableReader_44  | Projection_16   |                                | root | data:TableScan_43                                                                                                                                                          |                 21 |
| Projection_16   | HashLeftJoin_28 | TableReader_44                 | root | t3.id, t3.name, cast(t3.id)                                                                                                                                                |                 21 |
| HashLeftJoin_28 | IndexJoin_26    | Projection_15,Projection_16    | root | left outer join, small:Projection_16, equal:[eq(cast(t1.build), cast(t3.id))]                                                                                              |                3.2 |
| TableScan_24    |                 |                                | cop  | table:t4, range:(-inf,+inf), keep order:false                                                                                                                              |                 16 |
| TableReader_25  | IndexJoin_26    |                                | root | data:TableScan_24                                                                                                                                                          |                 16 |
| IndexJoin_26    | IndexJoin_22    | HashLeftJoin_28,TableReader_25 | root | outer:HashLeftJoin_28, left outer join, outer key:t1.project, inner key:t4.id                                                                                              |                3.2 |
| IndexScan_20    |                 |                                | cop  | table:t5, index:project, product, range:[<nil>,+inf], out of order:true                                                                                                    |                 15 |
| IndexReader_21  | IndexJoin_22    |                                | root | index:IndexScan_20                                                                                                                                                         |                 15 |
| IndexJoin_22    | Selection_19    | IndexJoin_26,IndexReader_21    | root | outer:IndexJoin_26, left outer join, outer key:t1.project, inner key:t5.project                                                                                            | 3.4285714285714284 |
| Selection_19    | TopN_17         | IndexJoin_22                   | root | eq(t1.product, t5.product)                                                                                                                                                 |  2.742857142857143 |
| TopN_17         | Projection_11   | Selection_19                   | root |                                                                                                                                                                            |  2.742857142857143 |
| Projection_11   |                 | TopN_17                        | root | t1.id, t1.name, t1.product, t1.project, t1.build, t1.owner, t1.pri, t1.begin, t1.end, t1.mailto, t1.desc, t1.report, t1.status, t1.deleted, t2.name, t3.name, t4.name      |  2.742857142857143 |
+-----------------+-----------------+--------------------------------+------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------------+

**Comment by XuHuaiyu** [comment]
PTAL @winoros

**Comment by XuHuaiyu** [comment]
please run `select tidb_version()` and provide us the result.

**Comment by kevin19931015** [comment]
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                              |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.1.0-alpha-195-g8a5b8d5
Git Commit Hash: 8a5b8d54a5f816ee718c5b5f5b466e1205db4664
Git Branch: master
UTC Build Time: 2017-11-30 11:27:07 |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+

thank you for your kind help！

**Comment by winoros** [comment]
This seems a bug which its fix is being reviewed.
@kevin19931015  Could you give us the schema as a create table statement so i can reproduce it easily？

**Comment by kevin19931015** [comment]
@winoros Thanks for your help.Is it like this?

| zt_testtask | CREATE TABLE `zt_testtask` (
  `id` mediumint(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` char(90) NOT NULL,
  `product` mediumint(8) UNSIGNED NOT NULL,
  `project` mediumint(8) UNSIGNED NOT NULL DEFAULT '0',
  `build` char(30) NOT NULL,
  `owner` varchar(30) NOT NULL,
  `pri` tinyint(3) UNSIGNED NOT NULL DEFAULT '0',
  `begin` date NOT NULL,
  `end` date NOT NULL,
  `mailto` text DEFAULT NULL,
  `desc` text NOT NULL,
  `report` text NOT NULL,
  `status` enum('blocked','doing','wait','done') NOT NULL DEFAULT 'wait',
  `deleted` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `build` (`build`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=5

| zt_product | CREATE TABLE `zt_product` (
  `id` mediumint(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(90) NOT NULL,
  `code` varchar(45) NOT NULL,
  `type` varchar(30) NOT NULL DEFAULT 'normal',
  `status` varchar(30) NOT NULL DEFAULT '',
  `desc` text NOT NULL,
  `PO` varchar(30) NOT NULL,
  `QD` varchar(30) NOT NULL,
  `RD` varchar(30) NOT NULL,
  `acl` enum('open','private','custom') NOT NULL DEFAULT 'open',
  `whitelist` text NOT NULL,
  `createdBy` varchar(30) NOT NULL,
  `createdDate` datetime NOT NULL,
  `createdVersion` varchar(20) NOT NULL,
  `order` mediumint(8) UNSIGNED NOT NULL,
  `deleted` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `order` (`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=8 |

| zt_build | CREATE TABLE `zt_build` (
  `id` mediumint(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `product` mediumint(8) UNSIGNED NOT NULL DEFAULT '0',
  `branch` mediumint(8) UNSIGNED NOT NULL DEFAULT '0',
  `project` mediumint(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` char(150) NOT NULL,
  `scmPath` char(255) NOT NULL,
  `filePath` char(255) NOT NULL,
  `date` date NOT NULL,
  `stories` text NOT NULL,
  `bugs` text NOT NULL,
  `builder` char(30) NOT NULL DEFAULT '',
  `desc` text NOT NULL,
  `deleted` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `build` (`product`,`project`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=22 |

| zt_project | CREATE TABLE `zt_project` (
  `id` mediumint(8) UNSIGNED NOT NULL AUTO_INCREMENT,
  `isCat` enum('1','0') NOT NULL DEFAULT '0',
  `catID` mediumint(8) UNSIGNED NOT NULL,
  `type` varchar(20) NOT NULL DEFAULT 'sprint',
  `parent` mediumint(8) UNSIGNED NOT NULL DEFAULT '0',
  `name` varchar(90) NOT NULL,
  `code` varchar(45) NOT NULL,
  `begin` date NOT NULL,
  `end` date NOT NULL,
  `days` smallint(5) UNSIGNED NOT NULL,
  `status` varchar(10) NOT NULL,
  `statge` enum('1','2','3','4','5') NOT NULL DEFAULT '1',
  `pri` enum('1','2','3','4') NOT NULL DEFAULT '1',
  `desc` text NOT NULL,
  `openedBy` varchar(30) NOT NULL DEFAULT '',
  `openedDate` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `openedVersion` varchar(20) NOT NULL,
  `closedBy` varchar(30) NOT NULL DEFAULT '',
  `closedDate` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `canceledBy` varchar(30) NOT NULL DEFAULT '',
  `canceledDate` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `PO` varchar(30) NOT NULL DEFAULT '',
  `PM` varchar(30) NOT NULL DEFAULT '',
  `QD` varchar(30) NOT NULL DEFAULT '',
  `RD` varchar(30) NOT NULL DEFAULT '',
  `team` varchar(30) NOT NULL,
  `acl` enum('open','private','custom') NOT NULL DEFAULT 'open',
  `whitelist` text NOT NULL,
  `order` mediumint(8) UNSIGNED NOT NULL,
  `deleted` enum('0','1') NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  KEY `project` (`parent`,`begin`,`end`,`status`,`order`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=15 |

| zt_projectproduct | CREATE TABLE `zt_projectproduct` (
  `project` mediumint(8) UNSIGNED NOT NULL,
  `product` mediumint(8) UNSIGNED NOT NULL,
  `branch` mediumint(8) UNSIGNED NOT NULL,
  PRIMARY KEY (`project`,`product`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |

**Comment by winoros** [comment]
Hello, you can try the newest master, let me know if there's still problem exists.

**Comment by kevin19931015** [comment]
@winoros I used docker to deploy tidb.I am a new githuber , could you tell me how to try newest master.

**Comment by winoros** [comment]
@kevin19931015  It will auto build every evening, i'll let you know if today someone trigger it manually.

**Comment by winoros** [comment]
You can try [this binary](http://pingcap-dev.hk.ufileos.com/builds/pingcap/tidb/23f526858d0f64723912374313f9dee6202ef9aa/centos7/tidb-server.tar.gz)
And this is how to use the binary version of tidb [Chinese version](https://github.com/pingcap/docs-cn/blob/master/op-guide/binary-deployment.md),  [English Version](https://github.com/pingcap/docs/blob/master/op-guide/binary-deployment.md).

**Comment by kevin19931015** [comment]
@winoros The error is still occur when I used the binary you give me。
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                              |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.1.0-alpha-199-g23f5268
Git Commit Hash: 23f526858d0f64723912374313f9dee6202ef9aa
Git Branch: master
UTC Build Time: 2017-12-01 10:25:36 |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------+
I see UTC Build Time: 2017-12-01 10:25:36,maybe it is not the latest version?

**Comment by winoros** [comment]
can you show explain this sql and show me the result?

**Comment by winoros** [comment]
Is there some error log around the panic log?

**Comment by kevin19931015** [comment]
@winoros this is my tidb-log,do you need pd log or tikv log.....

2017/12/05 09:02:17.237 conn.go:391: [error] lastCmd SELECT t1.*,t2.name as productName,t3.name as buildName,t4.name as projectName FROM zt_testtask AS t1 LEFT JOIN zt_product AS t2 ON t1.product=t2.id LEFT JOIN zt_build AS t3 ON t1.build=t3.id LEFT JOIN zt_project AS t4 ON t1.project=t4.id LEFT JOIN zt_projectproduct AS t5 ON t1.project=t5.project wHeRe t1.deleted = '0' AND t1.product IN ('7','6','4','3','1','5','2') AND t1.product = t5.product AND t1.status = 'wait' oRdEr bY t1.id desc lImiT 15, runtime error: index out of range, goroutine 639 [running]:
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0xc420b12790)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:389 +0xfd
panic(0x1031200, 0x1b07900)
        /usr/local/go/src/runtime/panic.go:491 +0x283
github.com/pingcap/tidb/types.(*Datum).IsNull(...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/types/row.go:153
github.com/pingcap/tidb/types.DatumRow.IsNull(...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/types/row.go:153
github.com/pingcap/tidb/types.(*DatumRow).IsNull(0xc420c0a140, 0x17, 0x3)
        <autogenerated>:1 +0x58
github.com/pingcap/tidb/expression.(*Column).EvalInt(0xc420baab60, 0x1920840, 0xc420c0a140, 0xc421bc9920, 0x3, 0x0, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/column.go:216 +0x1a2
github.com/pingcap/tidb/expression.compareInt(0xc42068a760, 0x2, 0x2, 0x1920840, 0xc420c0a140, 0x190dd80, 0xc420750b40, 0x61a8, 0xd89301, 0x0, ...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1815 +0x14f
github.com/pingcap/tidb/expression.(*builtinEQIntSig).evalInt(0xc420b85000, 0x1920840, 0xc420c0a140, 0x944404, 0xc420b85000, 0x190dd80, 0xc420750b40)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/builtin_compare.go:1425 +0x6a
github.com/pingcap/tidb/expression.(*ScalarFunction).EvalInt(0xc420b85040, 0x1920840, 0xc420c0a140, 0xc421bc9920, 0xc420698c00, 0xc421430000, 0xc4219c0000, 0xc420bdf5c8)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/scalar_function.go:223 +0x48
github.com/pingcap/tidb/expression.(*ScalarFunction).Eval(0xc420b85040, 0x1920840, 0xc420c0a140, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/scalar_function.go:193 +0x2d6
github.com/pingcap/tidb/expression.EvalBool(0xc421bf1360, 0x1, 0x1, 0x1920840, 0xc420c0a140, 0x190dd80, 0xc420750b40, 0x0, 0x0, 0x7f4be3acf458)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/expression/expression.go:103 +0xe1
github.com/pingcap/tidb/executor.(*SelectionExec).Next(0xc421ee4000, 0x7f4be3a77190, 0xc420b808a0, 0xc420864700, 0x0, 0x10, 0x3fb9022950057bf0, 0xc420bdf8b0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:591 +0x154
github.com/pingcap/tidb/executor.(*TopNExec).Next(0xc4200a5a20, 0x7f4be3a77190, 0xc420b808a0, 0xc421f5b7c0, 0x1905d00, 0xc42058df00, 0x0, 0x1)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/sort.go:354 +0x54c
github.com/pingcap/tidb/executor.(*ProjectionExec).Next(0xc420864300, 0x7f4be3a77190, 0xc420b808a0, 0xc420cf4080, 0xc420bdfa90, 0xd7c646, 0xc421ee4000, 0xc420c73300)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/executor.go:496 +0x76
github.com/pingcap/tidb/executor.(*recordSet).Next(0xc420bfe300, 0x7f4be3a77190, 0xc420b808a0, 0xc420bdfb08, 0xefe143, 0xc420bfe300, 0xc420bdfb00)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:77 +0x63
github.com/pingcap/tidb/server.(*tidbResultSet).Next(0xc42069a480, 0x7f4be3a77190, 0xc420b808a0, 0xc420bdfbe0, 0xefd3a0, 0x1095680, 0xc42069a480)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:294 +0x47
github.com/pingcap/tidb/server.(*clientConn).writeResultset(0xc420b12790, 0x7f4be3a77190, 0xc420b808a0, 0x19074a0, 0xc42069a480, 0xc420aa0000, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:807 +0x100
github.com/pingcap/tidb/server.(*clientConn).handleQuery(0xc420b12790, 0x7f4be3a77190, 0xc420b808a0, 0xc421bb63c1, 0x1c0, 0x0, 0x0)
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:748 +0x115
github.com/pingcap/tidb/server.(*clientConn).dispatch(0xc420b12790, 0xc421bb63c1, 0x1c1, 0x1c1, 0x0, 0x0)
        /home/jenkins/workspa
2017/12/05 09:02:17.237 server.go:297: [info] [1] close connection

**Comment by shenli** [comment]
@kevin19931015 The log of tidb-server is enough. Thanks!
@winoros PTAL

**Comment by winoros** [comment]
@kevin19931015 Could you leave some data to me? I generated some data but didn't reproduce the error.

**Comment by kevin19931015** [comment]
@winoros 
I have packed some date as zip format and sent it to your email，then you can unzip it and use loader to import the data to your tidb. 
1.unzip zentao.zip;
2./bin/loader -h 127.0.0.1 -u root -P 3306 -t 32 -d ./zentao/
3.use zentao
4.execute the sql that I provided above,then the error will occur.

**Comment by winoros** [comment]
Thanks a lot! I'll look into this.

**Comment by winoros** [comment]
We have located the problem. The patch will be pushed soon.

**Comment by winoros** [comment]
@kevin19931015 Now we fixed this, you can try the current docker version.

**Comment by shenli** [comment]
The new docker image will be pushed tomorrow morning.
