### ISSUE TITLE
performance problem, how to force use hash join and how to control the index join's concurrency？

### ISSUE THREAD

**Issue by meijies** [pingcap/tidb#5282]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I am testing tidb join performance. i have two table with 100,000,000 records. but the query needed 12 minutes. i check it's explain find index lookup join be used. and I can't find any way to force use hash join. 

many check DDL status log found. which cost many times with not high concurrency
![default](https://user-images.githubusercontent.com/13784260/33469815-08966ff0-d6a0-11e7-8e53-fbb64f12bab9.png)

the sql is select count(1) as cnt from event e left join session s on s.sid = e.sid where s.browser="Chrome" group by e.ip order by cnt desc limit 100; only sid has index for p_session table. if i use sid, browser as primary key for session table and use sid and eventid as primary key? can i get better performance?

I have one tidb-server, one pd-server and three tikv-server. tidb-server, pd-server and one tikv-server at same machine, another two machine have one tikv-server.

2. What did you expect to see?
the sql should use hash join for better performance.

3. What did you see instead?
the lookup join be used. 
![default](https://user-images.githubusercontent.com/13784260/33469749-9eed3a98-d69f-11e7-8418-8c7d1ce00da3.png)

4. What version of TiDB are you using (`tidb-server -V`)?
Release Version: v1.0.1-1-gaee0b39
Git Commit Hash: aee0b39af29c87742811f02c657dcf2b0fe1d60c
Git Commit Branch: release-1.0
UTC Build Time:  2017-11-01 01:51:09

**Comment by winoros** [comment]
Yes, currently we don't have hint to force to use hash join. We will add it.
 And this case seems that the driven table and driving table is wrong so make it very slow. https://github.com/pingcap/tidb/pull/5275 this pr is fixing this. We will let you know when this change is merged into release-1.0 branch.

**Comment by meijies** [comment]
thank you first.

when i test, i found cpu, io, network not busy. memory is not high. Is it limit by driving table is wrong problem or setup join concurrency is too low(now is 40)? 

other setup：
![default](https://user-images.githubusercontent.com/13784260/33471283-8cf7b8a6-d6a7-11e7-8fa4-ac49672daec0.png)

**Comment by winoros** [comment]
The index_lookup_concurrency is used for double read instead of IndexJoin. Currently indexJoin's batch concurrency is alway 1, i think this is the reason that the io, cpu, memory is not busy.

**Comment by meijies** [comment]
It's can be setup? I can't found it from configure file, doc and source code.

**Comment by winoros** [comment]
No it cannot be set currently. We'll improve this.

**Comment by winoros** [comment]
May i know that how many rows does `select * from s where s.browser="Chrome"` returns, is it some number around `14960` as the explain shows?

**Comment by winoros** [comment]
@meijies Hint for hash join was just merged into master branch. This hint may not be merged into release-1.0. Please wait next release.
And if you analyze at now, will the explain's `row count` still be so far from the real row count? If so, please use `show stats_meta` and `show stats_buckets` of the table `s`(you can see instruction in [this doc](https://github.com/pingcap/docs-cn/blob/master/sql/statistics.md)). I'll what's wrong in the selectivity calculation.

**Comment by meijies** [comment]
@winoros, I get it.  I have analyzed it and real row count returned. the sql executed by hash join algorithm with 3.5minutes.
