### ISSUE TITLE
Snapshot Restore: `CoarseGrained` completely replaces `FineGrained`

### ISSUE THREAD

**Issue by Leavrth** [pingcap/tidb#52877]
### Step 1 - Adjust the file directory structure
1. [release-8.2] There are too many files in the path `br/pkg/restore`. However, each file contains many struct, and imports each other.

- [x] https://github.com/pingcap/tidb/pull/52944

2. Separate the snap restore client and log restore client. And remove the `FineGrained` configure in the internal code.

- [x] https://github.com/pingcap/tidb/pull/53197

3. add more unit tests to cover more functions in `br/pkg/restore`.

- [x] https://github.com/pingcap/tidb/pull/53477

4. Since we doesn't use `FineGrained` snapshot restore, we can clean much codes.

**Comment by BornChanger** [comment]
done
