### ISSUE TITLE
Is this line useless?

### ISSUE THREAD

**Issue by biolee** [pingcap/tidb#5289]
https://github.com/pingcap/tidb/blob/master/.travis.yml#L10
```none
env:
    - TRAVIS_COVERAGE=0
    - TRAVIS_COVERAGE=1
```

**Comment by shenli** [comment]
No, we need this line.
We will run two jobs on travis. One without test coverage detection(which could be fast) and another one without test coverage detection(which is time consuming and allowed to fail.).

**Comment by shenli** [comment]
I will close the issue. Please feel free to reopen it when you have any new idea with this issue.
