### ISSUE TITLE
use `var_samp` as window function cause unexpected error

### ISSUE THREAD

**Issue by r33s3n6** [pingcap/tidb#52933]
## Bug Report
When used with the OVER clause, `var_samp` functions as a window function. When there are non-aggregate columns present, it should not throw an error. 
MySQL does not throw an error, and TiDB also does not throw errors for functions like `var_pop` and `variance`.

### 1. Minimal reproduce step (Required)
```sql
create table t1 (c1 int);
select c1, var_samp(c1) over (partition by c1) from t1;
```

### 2. What did you expect to see? (Required)
```
Empty set (0.00 sec)
```
### 3. What did you see instead (Required)
```
ERROR 8123 (HY000): In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'c1'; this is incompatible with sql_mode=only_full_group_by
```

### 4. What is your TiDB version? (Required)
```
Release Version: v8.0.0
Edition: Community
Git Commit Hash: 8ba1fa452b1ccdbfb85879ea94b9254aabba2916
Git Branch: HEAD
UTC Build Time: 2024-03-28 14:22:15
GoVersion: go1.21.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

**Comment by yibin87** [comment]
Reproduced locally, and select c1, sum(c1) over (partition by c1) from t1;
According to MySQL doc: https://dev.mysql.com/doc/refman/8.0/en/aggregate-functions.html#function_var-samp:~:text=VAR_SAMP(expr,and%20Syntax%E2%80%9D., we should be aligned with MySQL.

**Comment by yibin87** [comment]
This should be a planner issue.
