### ISSUE TITLE
Potential error in 'chunk_executor'  

### ISSUE THREAD

**Issue by spongedu** [pingcap/tidb#5293]
I'm working on #5244.  I found there's something wrong for `VectorizedFilter` in `chunk_executor`.
`VectorizedFilter` evaluate filter result using the following sentence:
```go
filterResult, isNull, err := filter.EvalInt(row, ctx.GetSessionVars().StmtCtx)
```
which does't work for predicates like the following sql(see line 436, executor/aggregate_test.go):

```sql
select sum(c1) from t group by c1 having sum(c1)
```

the predicate is a column-ref which type is not int. The result of `EvalInt` may be not as expected here.

**Comment by zz-jason** [comment]
@spongedu I think we should rewrite the filter in having clause to `sum(c1) != 0`

**Comment by spongedu** [comment]
@zz-jason maybe `cond != 0 && cond is not null` is better ?  colref `cond` may comes from somewhere else like subquery in `WHERE` clause, after all

**Comment by zz-jason** [comment]
@spongedu yes, you are right.

**Comment by coocood** [comment]
@spongedu 
`cond != 0` will be evaluated to `NULL` if `cond` is `NULL`

**Comment by spongedu** [comment]
@coocood yes. so there should be a `cond is not null` in the predicate.

**Comment by coocood** [comment]
@spongedu 
No, it produce the same result set without `cond is not null`, so we don't need to add it.

**Comment by spongedu** [comment]
@coocood yes, indeed

**Comment by morgo** [comment]
@coocood Can this issue be closed?
