### ISSUE TITLE
lightning: when tidb.tls config set to "false", TLSConfig didn't change, and db cannot connect

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#53001]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1.  set lightning.toml security 
![image](https://github.com/pingcap/tidb/assets/50363732/ab4c3ece-0490-4f80-9b13-9a1a895f9a59)

2. set lightning config toml [tidb.tls] to "false"
![image](https://github.com/pingcap/tidb/assets/50363732/cfaa03b3-627b-474f-b83a-fe5b6ec193d9)
3. tidb cluster open cluster tls but no client tls

### 2. What did you expect to see? (Required)
1. db connect ok
### 3. What did you see instead (Required)
1. tidb lightning encountered error: [Lightning:DB:ErrDBConnect]failed to connect database: TLS requested but server does not support TLS
2. some code shows that tlsconfig won't change
https://github.com/pingcap/tidb/blob/c60f97d16c6ff981b16279254ddee0f6b0e8ef19/pkg/lightning/config/config.go#L177-L200
### 4. What is your TiDB version? (Required)
master

**Comment by lance6716** [comment]
> tidb cluster open cluster tls but no client tls

Why do you expect the client can connect to TiDB cluster? https://docs.pingcap.com/zh/tidb/dev/enable-tls-between-clients-and-servers#%E9%85%8D%E7%BD%AE%E5%90%AF%E7%94%A8%E8%BA%AB%E4%BB%BD%E9%AA%8C%E8%AF%81

**Comment by AkiraXie** [comment]
> > tidb cluster open cluster tls but no client tls
> 
> Why do you expect the client can connect to TiDB cluster? https://docs.pingcap.com/zh/tidb/dev/enable-tls-between-clients-and-servers#%E9%85%8D%E7%BD%AE%E5%90%AF%E7%94%A8%E8%BA%AB%E4%BB%BD%E9%AA%8C%E8%AF%81

the cluster opened between-components tls but not between client-server tls , sorry for my incorrent words
