### ISSUE TITLE
lightning failing the entire bulk load with Error 1205: Lock wait timeout exceeded; try restarting transaction"

### ISSUE THREAD

**Issue by mittalrishabh** [pingcap/tidb#53042]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

Lightnining is failing the bulk load for intermittent bulk load requests. One common place where we see it failing is while updating the meta tasks. 
### 1. Minimal reproduce step (Required)

It was reproducible internally for intermittent connection issues. 

### 2. What did you expect to see? (Required)

I would expect retry with back off as connection errors are intermittent. 
### 3. What did you see instead (Required)
It is failing the whole bulk load. 
### 4. What is your TiDB version? (Required)
6.5

**Comment by D3Hunter** [comment]
lightning only runs the sql, might be issue of tidb, can you provide more info, like which sql causes the error and tidb logs related to the sql

**Comment by mittalrishabh** [comment]
i have created this PR https://github.com/pingcap/tidb/pull/53043

**Comment by bb7133** [comment]
Change the tag to 'lightning'

**Comment by lance6716** [comment]
closed by https://github.com/pingcap/tidb/pull/55670
