### ISSUE TITLE
syntax error: unexpected = in type declaration

### ISSUE THREAD

**Issue by denofiend** [pingcap/tidb#5308]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
build tidb from source, but get error:
util/chunk/compare.go:24: syntax error: unexpected = in type declaration

2. What did you expect to see?

build success

3. What did you see instead?
util/chunk/compare.go:24: syntax error: unexpected = in type declaration

4. What version of TiDB are you using (`tidb-server -V`)?
go version
go version go1.8.3 linux/amd64

**Comment by shenli** [comment]
@denofiend Please use Golang version >= 1.9.1.

**Comment by shenli** [comment]
See: https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md#go

**Comment by denofiend** [comment]
doc is >= 1.8. inter idear 1.9.2 is error

**Comment by shenli** [comment]
@denofiend Which document do you refer? We will correct it.

**Comment by denofiend** [comment]
https://github.com/pingcap/tidb/blob/master/docs/QUICKSTART.md

**Comment by shenli** [comment]
@denofiend Thanks! We will fix it. Or you could send us a PR to fix it.

**Comment by coocood** [comment]
Fixed by https://github.com/pingcap/tidb/pull/5310

@denofiend 
Thank you!
