### ISSUE TITLE
/etc/systemd/system not writable

### ISSUE THREAD

**Issue by zzx8170** [pingcap/tidb#5318]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

单机多实例安装,参考文档https://pingcap.com/docs-cn/op-guide/ansible-deployment/，
有没有更详细的配置文档，一个接一个的问题

2. What did you expect to see?

3. What did you see instead?

tidb安装的，有sudo所有权限，所有文件都可以写的，deploy的时候所有节点报错：

TASK [systemd : create systemd service configuration] ********************************************************************************************************
fatal: [TIKV-2]: FAILED! => {"changed": false, "checksum": "f7c9531753dc69119ac768542988653adfe8e0b5", "failed": true, "msg": "Destination
/etc/systemd/system not writable"} 

ok: [TiKV1-1] => (item=stop)
ok: [TiKV1-3] => (item=stop)
failed: [TiKV2-1] (item=start) => {"item": "start", "msg": "Failed to connect to the host via ssh: ", "unreachable": true}
failed: [TiKV2-3] (item=start) => {"item": "start", "msg": "Failed to connect to the host via ssh: ", "unreachable": true}
failed: [TiKV2-2] (item=start) => {"item": "start", "msg": "Failed to connect to the host via ssh: ", "unreachable": true}
ok: [TiKV1-4] => (item=start)
changed: [TiKV2-1] => (item=stop)
fatal: [TiKV2-1]: UNREACHABLE! => {"changed": true, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": "start", "msg": "Failed to connect to the host via ssh: ", "unreachable": true}, {"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": true, "checksum": "e28c98965569cee85bd1ceddc60b457de7d04247", "dest": "/data/tidb1/deploy/scripts/stop_node_exporter.sh", "diff": [], "failed": false, "gid": 2002, "group": "tidb", "invocation": {"module_args": {"attributes": null, "backup": false, "content": null, "delimiter": null, "dest": "/data/tidb1/deploy/scripts/stop_node_exporter.sh", "directory_mode": null, "follow": false, "force": true, "group": null, "local_follow": null, "mode": "0755", "original_basename": "stop_role.sh.j2", "owner": null, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "/home/tidb/.ansible/tmp/ansible-tmp-1512531150.26-87892463324121/source", "unsafe_writes": null, "validate": null}}, "item": "stop", "md5sum": "fa7bd511a0fb8202b516c833b63bacf2", "mode": "0755", "owner": "tidb", "secontext": "system_u:object_r:default_t:s0", "size": 777, "src": "/home/tidb/.ansible/tmp/ansible-tmp-1512531150.26-87892463324121/source", "state": "file", "uid": 2002}]}
ok: [TiKV2-2] => (item=stop)
fatal: [TiKV2-2]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": "start", "msg": "Failed
to connect to the host via ssh: ", "unreachable": true}, {"_ansible_item_result": true, "_ansible_no_log": false, "_ansible_parsed": true, "changed": false, "checksum": "c12dfff6cc2fed5257a3c757cb5a7a46f993a881", "diff": {"after": {"path": "/data/tidb2/deploy/scripts/stop_node_exporter.sh"}, "before": {"path": "/data/tidb2/deploy/scripts/stop_node_exporter.sh"}}, "failed": false, "gid": 2002, "group": "tidb", "invocation": {"module_args": {"attributes": null, "backup":
null, "content": null, "delimiter": null, "dest": "/data/tidb2/deploy/scripts/stop_node_exporter.sh", "diff_peek": null, "directory_mode": null, "follow": false, "force": false, "group": null, "mode": "0755", "original_basename": "stop_role.sh.j2", "owner": null, "path": "/data/tidb2/deploy/scripts/stop_node_exporter.sh", "recurse": false, "regexp": null, "remote_src": null, "selevel": null, "serole": null, "setype": null, "seuser": null, "src": "stop_role.sh.j2", "state": "file", "unsafe_writes": null, "validate": null}}, "item": "stop", "mode": "0755", "owner": "tidb", "path": "/data/tidb2/deploy/scripts/stop_node_exporter.sh", "secontext": "system_u:object_r:default_t:s0", "size": 777, "state": "file", "uid": 2002}]}
ok: [TiKV2-3] => (item=stop) 

TiKV1-1                    : ok=22   changed=2    unreachable=1    failed=0
TiKV1-2                    : ok=33   changed=6    unreachable=0    failed=0
TiKV1-3                    : ok=33   changed=6    unreachable=0    failed=0
TiKV1-4                    : ok=22   changed=2    unreachable=1    failed=0
TiKV2-1                    : ok=19   changed=5    unreachable=1    failed=0
TiKV2-2                    : ok=18   changed=0    unreachable=1    failed=0
TiKV2-3                    : ok=18   changed=0    unreachable=1    failed=0
TiKV2-4                    : ok=33   changed=6    unreachable=0    failed=0
TiKV3-1                    : ok=18   changed=0    unreachable=1    failed=0
TiKV3-2                    : ok=19   changed=5    unreachable=1    failed=0
TiKV3-3                    : ok=36   changed=12   unreachable=0    failed=0
TiKV3-4                    : ok=18   changed=0    unreachable=1    failed=0        
单实例上，有的节点ok，有的报错，是网络问题？

4. What version of TiDB are you using (`tidb-server -V`)?

1.0

**Comment by tshqin** [comment]
"item": "start", "msg": "Failed to connect to the host via ssh: ", "unreachable": true
ssh 通吗？确认 ssh 通了的话，加 -k 参数，按提示输入 ssh 密码

**Comment by zzx8170** [comment]
多deploy几次就ok了，晕

**Comment by shenli** [comment]
It seems caused by the network issue.
