### ISSUE TITLE
Select IN performance issue.

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#5320]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`SELECT id, k, c, pad FROM sbtest1 WHERE id IN (1234567,1357246,2461357,246810);
`

2. What did you expect to see?
get result about 0.01 seconds.
when I use = to select, the result is:
`SELECT id, k, c, pad FROM sbtest1 WHERE id = 1234567 or id = 1357246 or id = 2461357 or id = 246810;
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| id      | k          | c                                                                                                                       | pad                                                         |
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|  246810 | 1763028286 | 16547434518-65744061859-01753153042-08376049263-49612882667-77069390412-47942912744-74771449881-07797775103-58630923210 | 35977762123-77467647944-03930195890-38375677176-57180379040 |
| 1234567 | 1751547439 | 83643384050-30798284028-71576440800-38827790477-16315980364-43240375569-94017803222-96974496232-52667251043-80103401727 | 28433108010-48988153122-16343665324-63977247164-76459182903 |
| 1357246 | 1742158886 | 80570081282-26646947908-74135208782-51446953516-66362398897-46951601330-87229939268-64337756732-57368179118-60885706585 | 06654212476-96786538285-94997829885-09177787209-83142690180 |
| 2461357 | 1748141896 | 93259555265-11687572790-51729238667-16672045631-24454055497-60619591803-98317689418-07233372444-31864855401-38671263561 | 15586389705-02983482093-75126478453-82529224995-40696742883 |
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
4 rows in set (0.01 sec)
`

3. What did you see instead?
about 1 minutes.
`SELECT id, k, c, pad FROM sbtest1 WHERE id IN (1234567,1357246,2461357,246810);
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| id      | k          | c                                                                                                                       | pad                                                         |
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
|  246810 | 1763028286 | 16547434518-65744061859-01753153042-08376049263-49612882667-77069390412-47942912744-74771449881-07797775103-58630923210 | 35977762123-77467647944-03930195890-38375677176-57180379040 |
| 2461357 | 1748141896 | 93259555265-11687572790-51729238667-16672045631-24454055497-60619591803-98317689418-07233372444-31864855401-38671263561 | 15586389705-02983482093-75126478453-82529224995-40696742883 |
| 1234567 | 1751547439 | 83643384050-30798284028-71576440800-38827790477-16315980364-43240375569-94017803222-96974496232-52667251043-80103401727 | 28433108010-48988153122-16343665324-63977247164-76459182903 |
| 1357246 | 1742158886 | 80570081282-26646947908-74135208782-51446953516-66362398897-46951601330-87229939268-64337756732-57368179118-60885706585 | 06654212476-96786538285-94997829885-09177787209-83142690180 |
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
4 rows in set (59.23 sec)
`

4. What version of TiDB are you using (`tidb-server -V`)?
./tidb-server -V
Release Version: v1.0.2-11-gedcb9e9
Git Commit Hash: edcb9e9961d6396daa6bb4a728beedee0542ee28
Git Commit Branch: release-1.0
UTC Build Time:  2017-11-21 02:44:26

**Comment by winoros** [comment]
@DavisLinDB  Please provide the schema and the explain result.

**Comment by DavisLinDB** [comment]
table schema
` CREATE TABLE `sbtest1` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `k` bigint(20) NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin`

explain:
` explain SELECT id, k, c, pad FROM sbtest1 WHERE id IN (1234567,1357246,2461357,246810);
+---------------+---------+----------+------+-----------------------------------------------------------------------------------------------------------------+-------------+
| id            | parents | children | task | operator info                                                                                                   | count       |
+---------------+---------+----------+------+-----------------------------------------------------------------------------------------------------------------+-------------+
| TableScan_4   |         |          | cop  | table:sbtest1, range:[246810,246810], [1234567,1234567], [1357246,1357246], [2461357,2461357], keep order:false | 11898217.04 |
| TableReader_5 |         |          | root | data:TableScan_4                                                                                                | 11898217.04 |
+---------------+---------+----------+------+-----------------------------------------------------------------------------------------------------------------+-------------+
`

I use sysbench to benchmark and it create the schema.  I try to run select_random_points.lua but fail.  It shows that TiKV server too busy.  I check the sql statement found that using IN statement but poor performance.

**Comment by winoros** [comment]
You can use the information in grafana, https://github.com/pingcap/docs-cn/blob/master/op-guide/dashboard-overview-info.md. See that whether there's too many pending task in tikv.

**Comment by DavisLinDB** [comment]
@winoros 

Before running sysbench's select_random_points.lua, using IN or = operator get normal result:

`SELECT id, k, c, pad FROM sbtest1 WHERE id IN (1234567,1357246,2461357,7654321);
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| id      | k          | c                                                                                                                       | pad                                                         |
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 7654321 | 1766639899 | 66815868783-90943208151-30083344808-80291511648-53474953185-98427189031-90104198806-12695350640-49411818602-93916728647 | 16609167620-54455608633-62980774699-12988969661-03500669554 |
| 1234567 | 1751547439 | 83643384050-30798284028-71576440800-38827790477-16315980364-43240375569-94017803222-96974496232-52667251043-80103401727 | 28433108010-48988153122-16343665324-63977247164-76459182903 |
| 1357246 | 1742158886 | 80570081282-26646947908-74135208782-51446953516-66362398897-46951601330-87229939268-64337756732-57368179118-60885706585 | 06654212476-96786538285-94997829885-09177787209-83142690180 |
| 2461357 | 1748141896 | 93259555265-11687572790-51729238667-16672045631-24454055497-60619591803-98317689418-07233372444-31864855401-38671263561 | 15586389705-02983482093-75126478453-82529224995-40696742883 |
+---------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
4 rows in set (0.07 sec)
`
Then running select_random_points.lua and got error:

`sysbench --test=/usr/share/sysbench/select_random_points.lua --mysql-host=192.168.1.5 --mysql-port=4000 --mysql-user=sysbench --mysql-password=xxx --mysql-db=sysbench --report-interval=10 --max-requests=0 --max-time=120 --num-threads=256 --db-driver=mysql --tables=1 --table-size=3000000000 run
WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
WARNING: --num-threads is deprecated, use --threads instead
WARNING: --max-time is deprecated, use --time instead
sysbench 1.0.9 (using system LuaJIT 2.0.4)

Running the test with following options:
Number of threads: 256
Report intermediate results every 10 second(s)
Initializing random number generator from current time


Initializing worker threads...

Threads started!

[ 10s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 20s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 30s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 40s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 50s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 60s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 70s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
[ 80s ] thds: 256 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
FATAL: mysql_stmt_execute() returned error 9003 (TiKV server is busy[try again later]) for query '        SELECT id, k, c, pad
          FROM sbtest1
          WHERE k IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        '
FATAL: `thread_run' function failed: /usr/share/sysbench/select_random_points.lua:71: SQL error, errno = 9003, state = 'HY000': TiKV server is busy[try again later]
FATAL: mysql_stmt_execute() returned error 9003 (TiKV server is busy[try again later]) for query '        SELECT id, k, c, pad
          FROM sbtest1
          WHERE k IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        '
FATAL: `thread_run' function failed: /usr/share/sysbench/select_random_points.lua:71: SQL error, errno = 9003, state = 'HY000': TiKV server is busy[try again later]
FATAL: mysql_stmt_execute() returned error 9003 (TiKV server is busy[try again later]) for query '        SELECT id, k, c, pad
          FROM sbtest1
          WHERE k IN (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        '
FATAL: `thread_run' function failed: /usr/share/sysbench/select_random_points.lua:71: SQL error, errno = 9003, state = 'HY000': TiKV server is busy[try again later]
`
After got errors then IN or = operator get poor result:

`SELECT id, k, c, pad FROM sbtest1 WHERE id IN (112345670,113572460,124613570,176543210);
+-----------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| id        | k          | c                                                                                                                       | pad                                                         |
+-----------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 124613570 | 1755256127 | 22113611430-98679685551-46671198705-77332024514-82198722566-91785227770-57186117019-19837445579-62688613477-19586141159 | 32120970807-01717674294-89329261307-77370439430-05869610650 |
| 113572460 | 2055451203 | 11473978157-05063496191-83716003759-43834461426-96797965142-50830378480-49066340979-63188425560-24979998074-87680475398 | 09939658741-71876446863-58511051653-70296485170-14045538612 |
| 112345670 | 1755831841 | 60324437560-21964182450-90359795955-53601175142-67581703289-73403411766-56311868408-45063879934-03946069730-45362121225 | 10891843971-97819407087-87067384908-36145446118-55420421731 |
| 176543210 | 1742489986 | 98682114013-05524639845-17546147314-30404934287-87613133812-91777971719-70825816063-14422256817-64704526107-12543073105 | 98017386495-33508381483-66863942299-30333754535-57777020357 |
+-----------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
4 rows in set (54.23 sec)
`
` SELECT id, k, c, pad FROM sbtest1 WHERE id = 112345670 or id = 113572460 or id = 124613570 or id = 176543210;
+-----------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| id        | k          | c                                                                                                                       | pad                                                         |
+-----------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
| 124613570 | 1755256127 | 22113611430-98679685551-46671198705-77332024514-82198722566-91785227770-57186117019-19837445579-62688613477-19586141159 | 32120970807-01717674294-89329261307-77370439430-05869610650 |
| 113572460 | 2055451203 | 11473978157-05063496191-83716003759-43834461426-96797965142-50830378480-49066340979-63188425560-24979998074-87680475398 | 09939658741-71876446863-58511051653-70296485170-14045538612 |
| 176543210 | 1742489986 | 98682114013-05524639845-17546147314-30404934287-87613133812-91777971719-70825816063-14422256817-64704526107-12543073105 | 98017386495-33508381483-66863942299-30333754535-57777020357 |
| 112345670 | 1755831841 | 60324437560-21964182450-90359795955-53601175142-67581703289-73403411766-56311868408-45063879934-03946069730-45362121225 | 10891843971-97819407087-87067384908-36145446118-55420421731 |
+-----------+------------+-------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------+
4 rows in set (54.78 sec)
`
Then I check Grafana dashboard (running test about 10:00 ):
<img width="938" alt="tikv" src="https://user-images.githubusercontent.com/26958647/33695639-4240b8da-db39-11e7-8ab5-1c0b668d6743.png">

Looks like normal.

Then I check tikv logs:
TiKV1:
`2017/12/07 10:00:34.167 endpoint.rs:411: [INFO] [region 17618] handle Some(396522149748932867) [select] takes 54.017 [waiting: **51.185**, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000+\262\377" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0001>\214"))]
2017/12/07 10:00:34.389 endpoint.rs:411: [INFO] [region 17618] handle Some(396522149748932872) [select] takes 54.238 [waiting: 51.782, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000+\262\377" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0001>\214"))]
2017/12/07 10:00:34.722 endpoint.rs:411: [INFO] [region 17618] handle Some(396522149748932843) [select] takes 54.57 [waiting: 52.327, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000+\262\377" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0001>\214"))]
2017/12/07 10:00:34.723 endpoint.rs:411: [INFO] [region 1270] handle Some(396522162725060610) [select] takes 24.76 [waiting: 24.76, keys: 20, hit: 10, ranges: 10 (Some(start: "t\200\000\000\000\000\000\000\017_r\200\000\000\000\000\000\000\035" end: "t\200\000\000\000\000\000\000\017_r\200\000\000\000\000\000\000\036")`

TiKV2:
`2017/12/07 10:00:36.544 endpoint.rs:411: [INFO] [region 17626] handle Some(396522149748932989) [select] takes 30.009 [waiting: **27.507**, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0006\312\031" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000<U\246"))]
2017/12/07 10:00:36.621 endpoint.rs:411: [INFO] [region 17626] handle Some(396522149748933013) [select] takes 29.737 [waiting: 27.381, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0006\312\031" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000<U\246"))]
2017/12/07 10:00:36.731 endpoint.rs:411: [INFO] [region 17626] handle Some(396522149748933024) [select] takes 29.684 [waiting: 27.511, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0006\312\031" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000<U\246"))]
2017/12/07 10:00:36.735 endpoint.rs:411: [INFO] [region 17626] handle Some(396522149748932928) [select] takes 29.62 [waiting: 27.738, keys: 726812, hit: 726810, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\0006\312\031" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000<U\246"))]
`
tikv3
`2017/12/07 10:00:40.746 endpoint.rs:411: [INFO] [region 17614] handle Some(396522149748932793) [select] takes 60.339 [waiting: **60.339**, keys: 0, hit: 0, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000&'r" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000+\262\377"))]
2017/12/07 10:00:40.746 endpoint.rs:411: [INFO] [region 17598] handle Some(396522149748932953) [select] takes 60.34 [waiting: 60.34, keys: 0, hit: 0, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\017\371>" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\025\204\313"))]
2017/12/07 10:00:40.746 endpoint.rs:411: [INFO] [region 17598] handle Some(396522149748932992) [select] takes 60.34 [waiting: 60.34, keys: 0, hit: 0, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\017\371>" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\025\204\313"))]
2017/12/07 10:00:40.746 endpoint.rs:411: [INFO] [region 17602] handle Some(396522149748932817) [select] takes 60.34 [waiting: 60.34, keys: 0, hit: 0, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\025\204\313" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\033\020X"))]
2017/12/07 10:00:40.746 endpoint.rs:411: [INFO] [region 17586] handle Some(396522149748932965) [select] takes 60.339 [waiting: 60.339, keys: 0, hit: 0, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000\275_r\000\000\000\000\000\000\000\000" end: "t\200\000\000\000\000\000\000\275_r\200\000\000\000\000\004\342$"))]
`
So the problem is that select_random_points.lua do something let TiKV too busy then let the slow query result?  Can you pass sysbench select_random_points.lua test?

**Comment by shenli** [comment]
@DavisLinDB Please show me the graph of `coprocessor pending requests` on TiKV panel of coprocessor section.

**Comment by DavisLinDB** [comment]
@shenli 

I use 5 server to deploy TiDB cluster.
.1 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.2 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.3 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.5 E5620 CPU, 32G RAM, SAS HDD, TiDB
.6 E5620 CPU, 32G RAM, SAS HDD, TiDB
each running CentOS 7.

coprocessor pending requests:
<img width="473" alt="tikv3" src="https://user-images.githubusercontent.com/26958647/33748695-ecbfd0d6-dc04-11e7-8a7a-147c1d9695f9.png">


coprocessor CPU:
<img width="468" alt="tikv4" src="https://user-images.githubusercontent.com/26958647/33748698-ef6d4f7a-dc04-11e7-863e-3ae2d199da94.png">


some questions:
1. I run select_random_points.lua about 80 seconds then stop. But tikv_7's CPU still high loading, is it normally?
2. Bottleneck is CPU?  If I add new TiKV server avoid the problem?

**Comment by DavisLinDB** [comment]
almost 1 hour lator:

<img width="465" alt="tikv5" src="https://user-images.githubusercontent.com/26958647/33749424-a781ac2a-dc08-11e7-8d97-c82e455371d6.png">

**Comment by shenli** [comment]
@DavisLinDB Sorry for the late reply. We will investigate and fix this issue soon.

**Comment by DavisLinDB** [comment]
@shenli 

sysbench 1.0.9 (using system LuaJIT 2.0.4)

sysbench --test=/usr/share/sysbench/select_random_points.lua --mysql-host=192.168.1.55 --mysql-port=4000 --mysql-user=sysbench --mysql-password=xxxx --mysql-db=sysbench --report-interval=10 --max-requests=0 --max-time=120 --num-threads=256 --db-driver=mysql --tables=1 --table-size=3500000000 run

I try to test billions records in one table, so I change the oltp_common.lua:
sbtest.id from INTEGER to BIGINT
sbtest.k from INTEGER to BIGINT

`if sysbench.opt.auto_inc then
   id_def = "BIGINT NOT NULL AUTO_INCREMENT"


CREATE TABLE sbtest%d(
  id %s,
  k BIGINT DEFAULT '0' NOT NULL,
  c CHAR(120) DEFAULT '' NOT NULL,
  pad CHAR(60) DEFAULT '' NOT NULL,
  %s (id)
) %s %s]],`

So the sbtest1 table has 3 billion records to test.

Then I update TiDB to 1.0.4 and add a server as TiKV (from 3 TiKVs to 4 TiKVs).
The test result is:
<img width="468" alt="tikv6" src="https://user-images.githubusercontent.com/26958647/34284202-4540346a-e70b-11e7-8637-ff2967d816b8.png">

[oltp_common.lua.txt](https://github.com/pingcap/tidb/files/1581358/oltp_common.lua.txt)
[select_random_points.lua.txt](https://github.com/pingcap/tidb/files/1581359/select_random_points.lua.txt)

**Comment by shenli** [comment]
Got it. Thanks!
I will test it on my machine.

**Comment by DavisLinDB** [comment]
same in TiDB 2.0 RC1.

![2018-03-14 5 08 41](https://user-images.githubusercontent.com/26958647/37392924-98b170de-27aa-11e8-9945-87c3c8c172be.png)


Release Version:  v2.0.0-rc.1-21-g46f938c
Git Commit Hash:  46f938c632103ba7143775e884be33a1875cfa45
Git Commit Branch:  master
UTC Build Time:  2018-03-12 04:25:56
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  1.1.0-dev.2

**Comment by shenli** [comment]
@DavisLinDB Could you post your SQL and explain result here? Have you run analyze statement on the table you want to query?
@winoros PTAL

**Comment by DavisLinDB** [comment]
@shenli 
@winoros 

same test  as 2017.12.22 report:

`sysbench --test=/usr/share/sysbench/select_random_points.lua --mysql-host=192.168.1.55 --mysql-port=4000 --mysql-user=sysbench --mysql-password=xxxx --mysql-db=sysbench --report-interval=10 --max-requests=0 --max-time=120 --num-threads=256 --db-driver=mysql --tables=1 --table-size=3500000000 run
`

Release Version: v2.0.0-rc.1-21-g46f938c
Git Commit Hash: 46f938c632103ba7143775e884be33a1875cfa45
Git Commit Branch: master
UTC Build Time: 2018-03-12 04:25:56
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 1.1.0-dev.2

6 servers to deploy TiDB cluster.
.1 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.2 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.3 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.4 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV
.5 E5620 CPU, 32G RAM, SAS HDD, TiDB
.6 E5620 CPU, 32G RAM, SAS HDD, TiDB
each running CentOS 7.

Update from TiDB 1.0.4 to 2.0 RC1, seems the same test result.

**Comment by shenli** [comment]
@DavisLinDB Thanks! We will take a look.

**Comment by janurag** [comment]
@shenli I thinking about Tidb as an very good alternative for my Analytical requirement but many of my queries use  'Select IN'. Is there any tentative roadmap for this bug to resolve?

**Comment by cicerocomp** [comment]
I have the same problem here.

**Comment by tiancaiamao** [comment]
We have a issue https://github.com/pingcap/tidb/issues/6497 , it may account for this as well. @shenli @winoros 
And after some work by @AndreMouche , we have come to the conclusion that indexScan is slower than tableScan:
1. TiDB have lower concurrency for indexScan than tableScan
2. Index region have more records than data region in TiKV

**Comment by wwar** [comment]
@tiancaiamao I agree with your conclusion. I updated the test case in #6497 which demonstrates this a little bit cleaner with `EXPLAIN ANALYZE`. Should this issue be closed to reduce duplication?

**Comment by zz-jason** [comment]
> Should this issue be closed to reduce duplication?

Sure
