### ISSUE TITLE
SELECT execution failed

### ISSUE THREAD

**Issue by Nickelth** [pingcap/tidb#53229]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE t0(c0 INTEGER UNSIGNED );
CREATE TABLE t1(c0 BOOL , c1 CHAR, c2 INT);
insert into t0 values(1), (2), (3);
insert into t1 values(0, 'a', 1), (1, 'b', 2), (1, 'c', 3);
SELECT t1.c0 FROM  t0 RIGHT JOIN t1 ON (NOT (false));
```

### 2. What did you expect to see? (Required)
SELECT executed successfully, In MySQL 8.3.0, it produces:
```sql
+------+
| c0   |
+------+
|    0 |
|    0 |
|    0 |
|    1 |
|    1 |
|    1 |
|    1 |
|    1 |
|    1 |
+------+
```
### 3. What did you see instead (Required)
```sql
ERROR 8118 (HY000): Failed to build executor
```
### 4. What is your TiDB version? (Required)
release version 8.0.0

**Comment by yibin87** [comment]
Not reproduced using latest v8.0.0 version:
| Release Version: v8.0.0
Edition: Community
Git Commit Hash: 8ba1fa452b1ccdbfb85879ea94b9254aabba2916
Git Branch: HEAD
UTC Build Time: 2024-03-28 14:22:04
GoVersion: go1.21.6
Race Enabled: false
Check Table Before Drop: false
Store: tikv |
Neither with latest master version. Close it now.
