### ISSUE TITLE
tidb server can't start

### ISSUE THREAD

**Issue by zzx8170** [pingcap/tidb#5322]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

TASK [wait up] *****************************************************************
fatal: [10.1.1.210]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for search string TiDB in 10.1.1.210:4000"}
fatal: [10.1.1.211]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for search string TiDB in 10.1.1.211:4000"}
        to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/start.retry

PLAY RECAP *********************************************************************
10.1.1.210              : ok=22   changed=4    unreachable=0    failed=1
10.1.1.211              : ok=19   changed=3    unreachable=0    failed=1
10.1.1.212              : ok=18   changed=2    unreachable=0    failed=0
TiKV1-1                    : ok=18   changed=2    unreachable=0    failed=0
TiKV1-2                    : ok=18   changed=2    unreachable=0    failed=0
TiKV1-3                    : ok=18   changed=2    unreachable=0    failed=0
TiKV1-4                    : ok=18   changed=2    unreachable=0    failed=0
TiKV2-1                    : ok=18   changed=2    unreachable=0    failed=0
TiKV2-2                    : ok=18   changed=2    unreachable=0    failed=0
TiKV2-3                    : ok=18   changed=2    unreachable=0    failed=0
TiKV2-4                    : ok=18   changed=2    unreachable=0    failed=0
TiKV3-1                    : ok=18   changed=2    unreachable=0    failed=0
TiKV3-2                    : ok=18   changed=2    unreachable=0    failed=0
TiKV3-3                    : ok=18   changed=2    unreachable=0    failed=0
TiKV3-4                    : ok=18   changed=2    unreachable=0    failed=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0    

2. What did you expect to see?

3. What did you see instead?

单机多实例启动tikv和pd都启动了，但tidb server启动半天后超时退出，tidb.log显示如下：
2017/12/06 14:28:23.712 client.go:117: [info] [pd] init cluster id 6487714120992291427
2017/12/06 14:28:23.715 region_cache.go:447: [info] drop regions of store 4 from cache due to request fail, err: rpc
error: code = Unavailable desc = grpc: the connection is unavailable
2017/12/06 14:28:23.810 region_cache.go:447: [info] drop regions of store 1 from cache due to request fail, err: rpc
error: code = Unavailable desc = grpc: the connection is unavailable
2017/12/06 14:28:23.913 region_cache.go:447: [info] drop regions of store 5 from cache due to request fail, err: rpc
error: code = Unavailable desc = grpc: the connection is unavailable

4. What version of TiDB are you using (`tidb-server -V`)?

1.0

**Comment by tshqin** [comment]
1. on the tidb server, check if the tidb-server process works correctly, it should like below:
    `tidb      8023  8022  0 10:27 ?        00:01:42 bin/tidb-server -P 4000 --store=tikv --path=192.168.239.69:2379 --config conf/tidb.toml --status=10080 -L=info --log-file=/data/deploy/log/tidb.log`
2. check the communication ports of the cluster,
https://www.pingcap.com/docs-cn/op-guide/ansible-deployment/#自定义端口

**Comment by zzx8170** [comment]
normal now ,use  pd-ctl tool, store delete 1,4,5 ,restart cluster
