### ISSUE TITLE
Lightning:v6.5.0 always leads to panic and the incidence rate was 66.66%~

### ISSUE THREAD

**Issue by shaoxiqian** [pingcap/tidb#53272]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
use lightning:v6.5.0

### 2. What did you expect to see? (Required)
restore successfully
### 3. What did you see instead (Required)
panic
![image](https://github.com/pingcap/tidb/assets/85105033/e191fde2-2fb5-4636-a500-6294852046b6)

### 4. What is your TiDB version? (Required)
6.5.0

**Comment by lance6716** [comment]
The problem does not occur in latest release-6.5, so it's likely it's fixed afterwards.
