### ISSUE TITLE
not support SET character_set_client=binary, but support character_set_client=utf8

### ISSUE THREAD

**Issue by denofiend** [pingcap/tidb#5331]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
php SDK, every connection send 'not support SET character_set_client=binary' to server,

2. What did you expect to see?
work success.

3. What did you see instead?

2017/12/06 19:22:16.688 server.go:119: [info] [36] new connection 10.143.166.102:59039
2017/12/06 19:22:16.694 session.go:748: [warning] [36] parse error:
line 1 column 31 near "" (total length 31)
SET character_set_client=binary
2017/12/06 19:22:16.694 conn.go:430: [warning] [36] dispatch error:

4. What version of TiDB are you using (`tidb-server -V`)?
v1.1.0-alpha-221-gc46f289

**Comment by zz-jason** [comment]
@winkyao PTAL

**Comment by zz-jason** [comment]
@denofiend thanks for your feedback !

**Comment by denofiend** [comment]
hi

**Comment by winkyao** [comment]
TiDB can support binary character now.

```
mysql> SET character_set_client="binary";
Query OK, 0 rows affected (0.00 sec)
```
