### ISSUE TITLE
Add one more column in `information_schema.indexes` table to indicate it's a global index or not.

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#53342]

**Comment by Defined2014** [comment]
`show index` also could add this column, but doesn't it behave better like MySQL? /cc @mjonss

**Comment by mjonss** [comment]
> show index also could add this column, but doesn't it behave better like MySQL? If it's different with MySQL, maybe will make compatibility issues.

@Defined2014 I agree to not change `show index` to include this, we can reconsider if there are user/customer requests for it. Generally one should use `information_schema.tidb_indexes`, similar to one would use `information_schema.innodb_indexes`.
