### ISSUE TITLE
Using Fast online DDL reports no enough space

### ISSUE THREAD

**Issue by Nickelth** [pingcap/tidb#53351]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE t0(c0 BOOL);
CREATE INDEX i0 ON t0(c0);
ALTER TABLE t0 ADD PRIMARY KEY(c0);
```
### 2. What did you expect to see? (Required)
Statements executed successfully.
### 3. What did you see instead (Required)
Last two statements report:
```sql
ERROR 8256 (HY000): Check ingest environment failed: no enough space in /tmp/tidb/tmp_ddl-4000
```
But there's still 900+GB free space in my disk(I run tidb in docker and its root dir is /home):
![image](https://github.com/pingcap/tidb/assets/32243648/63a474d5-55ff-48e7-a44b-57f61853218d)
### 4. What is your TiDB version? (Required)
release version 8.0.0

**Comment by lance6716** [comment]
please check the available space of `/tmp/tidb/tmp_ddl-4000` rather than `/home`

**Comment by Nickelth** [comment]
> please check the available space of `/tmp/tidb/tmp_ddl-4000` inside docker rather than `/home` in host

![image](https://github.com/pingcap/tidb/assets/32243648/7046f51b-577b-4c26-a460-599f789a1dd8)

**Comment by lance6716** [comment]
please read the log, the error message should be enough
