### ISSUE TITLE
should not return zero when lightning exits while processing the task

### ISSUE THREAD

**Issue by zeminzhou** [pingcap/tidb#53384]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start tidb cluster
2. start lightning server
3. send task to lightning server
4. send `SIGINT` to lightning server

### 2. What did you expect to see? (Required)
lightnng server exit with status 1

### 3. What did you see instead (Required)
lightnng server exit with status 0

### 4. What is your TiDB version? (Required)
master

**Comment by lance6716** [comment]
`kill -9` will not let the program have a chance to handle it.

**Comment by zeminzhou** [comment]
> `kill -9` will not let the program have a chance to handle it.

should be `SIGINT`, not `SIGKILL`.

**Comment by D3Hunter** [comment]
required for k8s job, see https://github.com/pingcap/tidb/pull/53381#discussion_r1607535318
