### ISSUE TITLE
how to up for  offline or tombstone node?

### ISSUE THREAD

**Issue by zzx8170** [pingcap/tidb#5344]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

for test ,i delete store 1,the state become offline and tombstone

2. What did you expect to see?

i expect restart store 1 to up 

3. What did you see instead?

2017/12/08 10:53:16.935 tikv-server.rs:224: [ERROR] failed to start node: Pd(Other(StringError("store is tombstone")))  

4. What version of TiDB are you using (`tidb-server -V`)?

1.0

**Comment by zzx8170** [comment]
？

**Comment by disksing** [comment]
Hi @zzx8170,
Thanks for you feedback. You need to delete the data directory of tikv and then bring it up as a brand new tikv node.

**Comment by kolbe** [comment]
Hi @zzx8170, it looks like this question was answered a little over 1 year ago, so I am going to close it now. If you have any follow-up questions, you can re-open this issue at any time.
