### ISSUE TITLE
Optimize the memory usage of lightning when importing parquet data format files

### ISSUE THREAD

**Issue by zeminzhou** [pingcap/tidb#53466]
## Enhancement
Update `xitongsys/parquet-go` to optimize the memory usage of lightning.
Before update:
![img_v3_02b4_878ab795-c34b-42f4-8742-0236be09512g](https://github.com/pingcap/tidb/assets/50103576/5d8f8c9f-ba7d-4f24-9edb-40ab0ebd34cf)

After update:
![img_v3_02b4_69009e5a-b4e3-4287-87ab-afbc3cafbe5g](https://github.com/pingcap/tidb/assets/50103576/282d1245-40e9-4240-91ec-c5b7f3a31915)

**Comment by lance6716** [comment]
there's another more official package https://pkg.go.dev/github.com/apache/arrow/go/parquet I don't know why we choose current one 😂

**Comment by zeminzhou** [comment]
It's really drowsy, you know why? /cc @D3Hunter

**Comment by D3Hunter** [comment]
> xitongsys

sadly no 😂
