### ISSUE TITLE
 `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` env not work for aliyun provider

### ISSUE THREAD

**Issue by aytrack** [pingcap/tidb#53463]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. set the ak/sk through set the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` enviroment variables
2. dumpling/br the data to aliyun provider

from asktug: https://asktug.com/t/topic/1026409
after https://github.com/pingcap/tidb/pull/34309,  for Aliyun's provider will ignore the  ak/sk in the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.

### 2. What did you expect to see? (Required)
dumpling/br success  with the env `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` ak/sk
### 3. What did you see instead (Required)
dumpling/br failed 
### 4. What is your TiDB version? (Required)
affect release-6.1, 6.5, 7.1, 7.5, 8.1

**Comment by BornChanger** [comment]
duplicated with https://github.com/pingcap/tidb/issues/45551
