### ISSUE TITLE
tidb report redirect failed error

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#53528]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

This is hard to reproduce. But it happens during DDL(truncate table) process, tidb tries to fetch placement rule from PD, but didn't send HTTP request to PD leader directly. And PD errors happens when PD tries to redirect this HTTP request to PD leader.

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
PD return redirect failed error to TiDB
### 4. What is your TiDB version? (Required)
v6.5.7

**Comment by guo-shaoge** [comment]
TiDB should support retry when sending HTTP request to PD or send it to PD leader directly.

**Comment by lance6716** [comment]
after using PD HTTP client, this problem is likely fixed. Closing now
