### ISSUE TITLE
br restore splits too much regions if there are too many small tables whose data size is less than region size.

### ISSUE THREAD

**Issue by Leavrth** [pingcap/tidb#53532]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. create so many tables, but each table only has a little data.
2. backup cluster with `split-table=false/split-region-on-table=false`
3. restore cluster

### 2. What did you expect to see? (Required)
the number of regions of downstream cluster is closed to the number of upstream cluster.
### 3. What did you see instead (Required)
the number of regions has many regions.
### 4. What is your TiDB version? (Required)
master

**Comment by BornChanger** [comment]
It's an extension of https://github.com/pingcap/tidb/issues/50701

**Comment by Leavrth** [comment]
We need to do some clean work at first. See https://github.com/pingcap/tidb/issues/52877
