### ISSUE TITLE
throw exception when using "in" in where_condition,not compatible with mysql

### ISSUE THREAD

**Issue by Zhang-Jin-Hua** [pingcap/tidb#5353]
1. What did you do?
when use "in" in where_condition, just like below sql
`SELECT *
FROM test_db
WHERE field in ("test");`

2. What did you expect to see?
just like mysql

3. What did you see instead?

`[2017-12-10 18:43:53] [HY000][1105] other error: unknown error WireError(InvalidEnumValue(4004))`

4. What version of TiDB are you using (`tidb-server -V`)?
5.7.1-TiDB-v1.0.2-16-gb8bcf9c

**Comment by coocood** [comment]
@Zhang-Jin-Hua 
Thank you for your report.
Please provide the create table statement and the insert statement to reproduce this issue.

**Comment by coocood** [comment]
And please provide the version of TiKV.
```
tikv-server -V
```

**Comment by shenli** [comment]
@Zhang-Jin-Hua It seems that the tidb-server and tikv-server you used are not compatible with each other. Please use the binaries from the same downloaded pack. Or you could upgrade your tidb-server/tikv-server/pd-server to the latest version.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
