### ISSUE TITLE
can't recongnize date like 'YYYY-MM-dd HH',not compatible with mysql

### ISSUE THREAD

**Issue by Zhang-Jin-Hua** [pingcap/tidb#5354]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

`SELECT *
FROM test
WHERE create_time > '2017-08-10 12'`

2. What did you expect to see?
just like mysql

3. What did you see instead?

`[2017-12-10 18:55:35] [HY000][1105] invalid time format`

4. What version of TiDB are you using (`tidb-server -V`)?
5.7.1-TiDB-v1.0.2-16-gb8bcf9c

**Comment by coocood** [comment]
@Zhang-Jin-Hua 
Thank you for your report.
Please provide the create table statement and the insert statement to reproduce this issue.

**Comment by zz-jason** [comment]
this may be the same with https://github.com/pingcap/tidb/issues/5340

**Comment by wwar** [comment]
This bug has been fixed (the other one linked is not). I remember seeing a similar issue about it and noticing it was fixed. Here is a pastable testcase:

```
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (id int not null primary key auto_increment, b datetime);
INSERT INTO t1 (b) VALUES ('2020-01-01 00:00:00'), ('2020-02-02 00:00:00');
SELECT * FROM t1 WHERE b > '2020-01-02 12';

..

tidb> SELECT * FROM t1 WHERE b > '2020-01-02 12';
+----+---------------------+
| id | b                   |
+----+---------------------+
|  2 | 2020-02-02 00:00:00 |
+----+---------------------+
1 row in set (0.00 sec)

tidb> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-183-g57db6cec7
Git Commit Hash: 57db6cec7ffad78e74b6ac6c67a2bfe9a6718d17
Git Branch: master
UTC Build Time: 2020-04-04 08:06:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```
