### ISSUE TITLE
switch schema v2 cause `Information schema is changed`

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#53599]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

- apply below diff and run, it will fail with `Information schema is changed during the execution of the statement(for example, table definition may be updated by other DDL ran in parallel). If you see this error often, try increasing `tidb_max_delta_schema_count`. [try again later]`

```diff
diff --git a/pkg/ddl/tiflash_replica_test.go b/pkg/ddl/tiflash_replica_test.go
index e21b665189..416fd0c571 100644
--- a/pkg/ddl/tiflash_replica_test.go
+++ b/pkg/ddl/tiflash_replica_test.go
@@ -251,11 +251,13 @@ func TestSkipSchemaChecker(t *testing.T) {
 
 	store := testkit.CreateMockStoreWithSchemaLease(t, tiflashReplicaLease)
 	tk := testkit.NewTestKit(t, store)
+	tk.MustExec("set @@global.tidb_schema_cache_size = 0")
 	tk.MustExec("use test")
 	tk.MustExec("set global tidb_enable_metadata_lock=0")
 	tk.MustExec("drop table if exists t1")
 	tk.MustExec("create table t1 (a int)")
 	tk2 := testkit.NewTestKit(t, store)
+	tk2.MustExec("set @@global.tidb_schema_cache_size = 1024")
 	tk2.MustExec("use test")
 
 	// Test skip schema checker for ActionSetTiFlashReplica.

```

- the cause is that in the first reload after `tk2.MustExec("set @@global.tidb_schema_cache_size = 1024")`, it will trigger full load as we change from v1->v2, it triggers SchemaValidator reset, enqueue `53` into `schemaValidator` while `53` is the latest version. it cause `isRelatedTablesChanged` returns the error

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
failed
### 4. What is your TiDB version? (Required)
master

**Comment by GMHDBJD** [comment]
now we don't need full load when switch v1 to v2
