### ISSUE TITLE
Dump stats for debug

### ISSUE THREAD

**Issue by hanfei1991** [pingcap/tidb#5360]
Sometimes we meet a bug in production enviroument which cannot reproduce locally. A main reason is that we don't get a correct stats info. So a stats dump tool is needed.

**Comment by hanfei1991** [comment]
A brief idea: use http api to dump a json file to describe the current stats tables. The format of url could be `dump_stats/db_name/table_name`.
And use a special SQL command to load this json file.

**Comment by lamxTyler** [comment]
We can also include the table info in the file so that we need not manually create the table.

**Comment by hanfei1991** [comment]
I think there are two individual functions. We have `show create table` command to get a table create info. So there should be two files to load stats: `stats.json` and `schema.sql`.

the schema.sql is composed of `create table ....` and `load stats file stats.json`.
