### ISSUE TITLE
A non mandatory crash occurred here, have you ever encountered this problem? Or how should we solve it?

### ISSUE THREAD

**Issue by chaoxcheng** [pingcap/tidb#53693]
## Bug Report
![image](https://github.com/pingcap/tidb/assets/13311671/a09d825c-d7c5-452c-8d04-6d0e89e31cd4)
![image](https://github.com/pingcap/tidb/assets/13311671/9f15d293-5ca2-488e-bfb9-33dc06c6ba48)

**Comment by hawkingrei** [comment]
Please write according to the bug report format and provide reproduction steps and version information.

**Comment by hawkingrei** [comment]
BTW, Is it TiDB's code ?

**Comment by chaoxcheng** [comment]
> Please write according to the bug report format and provide reproduction steps and version information.

We are enterprise users and have already provided feedback to relevant liaison personnel

**Comment by chaoxcheng** [comment]
Sorry, this was an incorrect feedback. I will now close this issue
