### ISSUE TITLE
tidb restart with error log “[FATAL] [job_table.go:366] ["dispatch loop get cluster state failed, it should not happen, please try restart TiDB"]”

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#53808]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench mussel 
2、inject pd leader io delay 500ms

### 2. What did you expect to see? (Required)
tidb is normal

### 3. What did you see instead (Required)
tidb restart with error log “[FATAL] [job_table.go:366] ["dispatch loop get cluster state failed, it should not happen, please try restart TiDB"]”

`[2024/06/03 12:42:37.820 +08:00] [FATAL] [job_table.go:366] ["dispatch loop get cluster state failed, it should not happen, please try restart TiDB"] [category=ddl] [error="context canceled"] [stack="github.com/pingcap/tidb/pkg/ddl.(*jobScheduler).startDispatchLoop\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/ddl/job_table.go:366\ngithub.com/pingcap/tidb/pkg/util.(*WaitGroupWrapper).RunWithLog.func1\n\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/util/wait_group_wrapper.go:171"]`
### 4. What is your TiDB version? (Required)

./tidb-server -V
 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 8483dc538be95234dde6d6c31d1bb3248488440e
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-02 11:45:42
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-06-03T12:32:12.769+0800

**Comment by tangenta** [comment]
Related to #53548.
