### ISSUE TITLE
TiDB cannot handle `non-breaking space character` correctly

### ISSUE THREAD

**Issue by hi-rustin** [pingcap/tidb#53833]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. Start the Tidb cluser
2. Use MySQL client to connect the TiDB server
3. Try `select * from test limit 1;`
<img width="638" alt="image" src="https://github.com/pingcap/tidb/assets/29879298/7cf64506-0235-4705-a25f-150d3802e5de">

This is a `non-breaking space character`.

### 2. What did you expect to see? (Required)
It works well.
I tested it on v5.1.2, it worked well.

### 3. What did you see instead (Required)

```sql
mysql> select * from test limit 1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 14 near " from test limit 1"
```

### 4. What is your TiDB version? (Required)

- master
- v7.1.5
- v6.0.0

**Comment by hi-rustin** [comment]
And if you try: `select * from test limit 1;` it will not work on any version.
<img width="631" alt="image" src="https://github.com/pingcap/tidb/assets/29879298/c11b30f5-0ef4-468a-bb1c-2ad6cc35862d">

**Comment by YangKeao** [comment]
A simple fix is to modify `isIdentExtend` into:

```go
func isIdentExtend(ch byte) bool {
	return ch >= 0x80 && !unicode.IsSpace(rune(ch))
}
```

As the `\xA0` is considered as an ident, the lexer will keep scanning over it, and give us an ident `SELECT\xA0`, which is obviously invalid. However, I'm not familiar with the background of `isIdentExtend` function, so I'm not sure whether this change will bring other bugs :thinking: .

**Comment by YangKeao** [comment]
@hi-rustin Could you write the test in form like "SELECT *\xA0"? Copy/paste from github will discard the internal `\xA0` :facepalm:  :

```
echo 'select * from test limit 1;'|hexdump
0000000 6573 656c 7463 2a20 6620 6f72 206d 6574
0000010 7473 6c20 6d69 7469 3120 0a3b          
000001c
```

I've tried the following test:

```go
func TestSpecialChar(t *testing.T) {
	store := testkit.CreateMockStore(t)
	tk := testkit.NewTestKit(t, store)
	tk.MustExec("use test")
	tk.MustExec("create table test (a int)")
	tk.MustExec("insert into test values (1)")

	tk.MustQuery("select *\xA0from test limit 1;").Check(testkit.Rows("1"))
	tk.MustQuery("select\xA0*\xA0from\xA0test\xA0limit\xA01;").Check(testkit.Rows("1"))
	tk.MustQuery("select *\xA0from\xA0test\xA0limit\xA01;").Check(testkit.Rows("1"))
}
```

The first case can work on both the latest master and the 5.1.2. I'm still not sure which SQL behaves differently between 5.1.2 and latest master.

**Comment by hi-rustin** [comment]
It seems GitHub handles this character automatically.

[test1.txt](https://github.com/user-attachments/files/15581060/test1.txt)

Try this file on different versions.

**Comment by YangKeao** [comment]
> It seems GitHub handles this character automatically.
> 
> [test1.txt](https://github.com/user-attachments/files/15581060/test1.txt)
> 
> Try this file on different versions.

Good :+1:. In golang:

```go
tk.MustQuery("select *\u00a0from test limit 1;").Check(testkit.Rows("1"))
```

**Comment by YangKeao** [comment]
This bug is introduced in https://github.com/pingcap/tidb/pull/31039. Previously, the lexer worked `rune` by `rune`, so it can decode a `0xC0 0xA0` string into `0xA0` rune:

```
func (r *reader) peek() rune {
	if r.eof() {
		return unicode.ReplacementChar
	}
	v, w := rune(r.s[r.p.Offset]), 1
	switch {
	case v == 0:
		r.w = w
		return v // illegal UTF-8 encoding
	case v >= 0x80:
		v, w = utf8.DecodeRuneInString(r.s[r.p.Offset:])
		if v == utf8.RuneError && w == 1 {
			v = rune(r.s[r.p.Offset]) // illegal UTF-8 encoding
		}
	}
	r.w = w
	return v
}
```

Then the following `unicode.IsSpace` can read the `0xA0` and skip the whitespace.

After introducing this PR, it works byte by byte, so it'll be treated as `0xC0`, `0xA0` two bytes. The `0xC0` is not regarded as a whitespace, and return an error.

In 5.1.2, `\u00a0` should work well after some symbols (`*`, `&&`...), but also didn't work after meaningful identifiers (`SELECT`, `FROM`...). Because the `0xC0`, `0xA0` will be considered as a valid part of the identifier, and makes the identifier (`SELECT\u00a0`) invalid.

**Comment by YangKeao** [comment]
Then, I suggested to not fix! The current behavior of TiDB seems compatible with MySQL and easy to understand.

If we are going to fix, we can have two changes:
1. To be compatible with 5.1 (or before), we should specially handle the `0xC2`, `0xA0` combination and skip them for utf8 cases.
2. To be able to use `\u00a0` anywhere, besides the previous change, we should also change the `isIdentExtend` to avoid using `\u00a0` in the identifier.

**Comment by bb7133** [comment]
@hi-rustin @YangKeao I don't think we should try to fix this. After all now we're compatible with MySQL.

On the other hand, those 'invalid' characters are barely used by the customers, issues like this can be simply workarounded.

**Comment by YangKeao** [comment]
> @hi-rustin @YangKeao I don't think we should try to fix this. After all now we're compatible with MySQL.
> 
> On the other hand, those 'invalid' characters are barely used by the customers, issues like this can be simply workarounded.

Good. Let's close this issue.
