### ISSUE TITLE
Param as column alias can't be parsed in group statement

### ISSUE THREAD

**Issue by pcqz** [pingcap/tidb#53872]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create table test(id int, col int);
prepare stmt from "select id, ? as col1 from test where col=? group by id,col1";
set @a=100, @b=100;
execute stmt using @a,@b;
```
### 2. What did you expect to see? (Required)

No error

### 3. What did you see instead (Required)

ERROR 1105 (HY000): Unknown column '100' in 'group statement'

### 4. What is your TiDB version? (Required)

v8.1.0

**Comment by YangKeao** [comment]
I think it's caused by the special behavior of `group by ?`, which will group by the N-th field. Ref https://github.com/pingcap/tidb/issues/8153 :facepalm: . It's referred as `*ast.PositionExpr` in TiDB.

Every day I can learn a new mystery behavior of SQL.

**Comment by qw4990** [comment]
A workaround:
```
mysql>   prepare stmt from "select id, col1 from (select id, ? as col1 from test where col=?) t group by id,col1";
Query OK, 0 rows affected (0.00 sec)

mysql> set @a=100, @b=100;
Query OK, 0 rows affected (0.00 sec)

mysql> execute stmt using @a,@b;
Empty set (0.01 sec)
```

**Comment by elsa0520** [comment]
Maybe  order by will have the same problem ~ @qw4990
