### ISSUE TITLE
 Analyze is blocked long time when execute ddl in mounts of tables scenario

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#53915]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. prepare millions tables
2. create table/database and analyze table currently
https://github.com/pingcap/tidb/blame/master/pkg/statistics/handle/util/table_info.go#L47C31-L47C44 will lock long time
![image](https://github.com/pingcap/tidb/assets/7677963/8de55bae-3dcc-4e92-87b5-bf82a3365a2f)

### 4. What is your TiDB version? (Required)

Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 9c1a45ab46b0fdc228dd636e3ba00f0c38547272
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-04 11:48:16
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by tiancaiamao** [comment]
I think it's the caller of this function that cause the problem.
For example here, the caller will call this function in a loop, for 1M times: https://github.com/pingcap/tidb/blob/fedf3b7ba9a841e90de55cc3c4c1b037343f2339/pkg/statistics/handle/bootstrap.go#L136

**Comment by wjhuang2016** [comment]
closed by #54161
