### ISSUE TITLE
TestPauseCancelAndRerunPartitionTableStmt spend too much time

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#53925]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 3. What did you see instead (Required)

```

panic: test timed out after 5m0s
running tests:
	TestPauseCancelAndRerunPartitionTableStmt (5m0s) 
```

https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/53897/fast_test_tiprow/1800406545276604416#1:build-log.txt%3A3360

**Comment by D3Hunter** [comment]
i have fixed it here https://github.com/pingcap/tidb/pull/53887/files#diff-0f144015d1a8ee7242009478e919a0e293b068a8e727af10a07f00eec45268b8
