### ISSUE TITLE
update vendor github.com/Sirupsen/logrus to github.com/sirupsen/logrus

### ISSUE THREAD

**Issue by holys** [pingcap/tidb#5394]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Not an error

2. What did you expect to see?
github.com/sirupsen/logrus in source code

3. What did you see instead?
github.com/Sirupsen/logrus in source code

4. What version of TiDB are you using (`tidb-server -V`)?
713bc797bbdfe4873218783be7182ce3d3c95067

ref: https://github.com/pingcap/pd/issues/885

**Comment by shenli** [comment]
Solved in https://github.com/pingcap/tidb/pull/5400
