### ISSUE TITLE
Interpreter takes over terminal input

### ISSUE THREAD

**Issue by romanoff** [pingcap/tidb#54]
After I leave interpreter with Ctrl+D key combination, keyboard keys are no longer recognized in that terminal (I suppose they are taken over by other application). Is there any way to fix that?

Additional information:
```
andrey@andrey-ThinkCentre-M82:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
andrey@andrey-ThinkCentre-M82:~$ go version
go version go1.5 linux/amd64
```

**Comment by romanoff** [comment]
Update: seems like if you type some experssion and press enter, it will be executed. But you don't see symbols appearing in the terminal in the process of typing

**Comment by qiuyesuifeng** [comment]
@romanoff  Thanks for your report.
i try it in Ubuntu 14.04.1 and go1.5 for interpreter,  it works well.
try `Ctrl+C`? can this work?

**Comment by qiuyesuifeng** [comment]
@romanoff 
We  have fixed this bug, u can update and try again.
