### ISSUE TITLE
Decouple clean up ingest temp data from `BackendCtxMgr`

### ISSUE THREAD

**Issue by tangenta** [pingcap/tidb#54007]
## Enhancement

Use a separate loop for cleaning up is better. Otherwise, if there are no new add index jobs running, temp-dir cannot be cleaned up.

**Comment by lance6716** [comment]
About the problem "if there are no new add index jobs running, temp-dir cannot be cleaned up.", I agree we should use a background loop to periodically check temp-dir. However, the only ownership of temp-dir should still belong to BackendCtxMgr. In other words, only BackendCtxMgr creates and deletes the files under its workering directory which is temp-dr.

Currently my suggestion is spawn a goroutine that calls `BackendCtxMgr.CleanUpXXX`. And the caller passes `processingJobsIDs` as an argument to avoid `BackendCtxMgr` uses `getProcessingJobIDs`.

**Comment by tangenta** [comment]
@lance6716 I plan to remove `BackendCtxMgr` and let each backend context managed by ddl worker / distributed framework instead. This is one of the steps.

**Comment by lance6716** [comment]
> @lance6716 I plan to remove `BackendCtxMgr` and let each backend context managed by ddl worker / distributed framework instead. This is one of the steps.

OK, I realized that clean up stale files is not a functionality of one backend context, it belongs to the "backend context manager" but we are going to remove this concept.
