### ISSUE TITLE
TiDB consumes lots of resource when create table in million tables scenario and infoSchema V2 for loadSchema

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#54046]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

3 TiDB instatnce(16c 64GB)
tidb_schema_cache_size 2GB
open fast create table
create 100k schemas and about 15 tables each of schema. 1.5 million tables totally
```
select count(table_name), count(distinct TABLE_schema) from information_schema.tables where TABLE_SCHEMA like "mt%" ;
+-------------------+------------------------------+
| count(table_name) | count(distinct TABLE_schema) |
+-------------------+------------------------------+
|           1570000 |                       100000 |
+-------------------+------------------------------+
```
Taking the node 'tidb1' as an example, when the number of tables reaches a certain amount (perhaps around 700,000), continuing to create tables will trigger a "full load InfoSchema". Subsequently, the resource consumption of this TiDB instance will continue to increase. Even if we stop the DDL tasks, the CPU and memory usage will continue to maintain a high level.

![image](https://github.com/pingcap/tidb/assets/7677963/4f3e548e-0db0-4fde-8f6a-ea8d31a56484)

![image](https://github.com/pingcap/tidb/assets/7677963/16f4ada4-f103-4a47-a570-212fa50ef211)

### 4. What is your TiDB version? (Required)

 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 6cf8776242fbfe0b922488357867ca5244e7b8fa
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-13 11:49:48
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
