### ISSUE TITLE
Delete TiFlash placement rules in gc worker may take a long time

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tidb#54068]
## Enhancement

Now in gc worker, we delete placement rules of TiFlash one by one. It may takes a long time when `drop database` or `drop table` with a lot of partitions. We can easily optimize it by batch delete.

https://github.com/pingcap/tidb/blob/8f568472a39980f948a9f901f58f0b0073ac494e/pkg/store/gcworker/gc_worker.go#L1547-L1557

**Comment by JaySon-Huang** [comment]
Consider backport this to release-6.5/7.1/7.5/8.1
