### ISSUE TITLE
The SchemaByID func using InfoSchema v2 consume much time

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#54074]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tidb_schema_cache_size 2GB
create 100k schemas and about 15 tables each of schema. 1.5 million tables totally
insert data for above tables
when we using infoSchemaV2 the qps is about 10k, while the qps is about 18k when using infoSchemaV1
Here are some screenshots of the cluster when using infoSchemaV2.
The compile time is more than 2ms
![image](https://github.com/pingcap/tidb/assets/7677963/9858f5a4-3aec-4e7c-adae-9fa7a8e8b9c9)

![image](https://github.com/pingcap/tidb/assets/7677963/61ff31a4-6f99-4bd5-90a8-89996117384c)

As we can see from code https://github.com/pingcap/tidb/blob/master/pkg/infoschema/infoschema_v2.go#L642C25-L666, The SchemaByID func will reverse all the schemas btree to find the matched schema
### 4. What is your TiDB version? (Required)

Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 6cf8776242fbfe0b922488357867ca5244e7b8fa
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-13 11:49:48
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by jebter** [comment]
Releted to issue:#50052
