### ISSUE TITLE
PR#53537 caused 20-34% performance regression in oltp_read_only and oltp_read_write

### ISSUE THREAD

**Issue by Yui-Song** [pingcap/tidb#54070]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. deploy a cluster with 3 tidb and 3 tikv
2. run sysbench oltp_read_only and oltp_read_write with pr #53341 and  #53537

### 2. What did you expect to see? (Required)
No regression.

### 3. What did you see instead (Required)
PR#53537 caused performance regression in oltp_read_only (34%) and oltp_read_write(20%)
![image](https://github.com/pingcap/tidb/assets/84501897/dc28e1f3-2022-4b6f-8e7a-a05c5dd3df1d)

### 4. What is your TiDB version? (Required)

#53537

**Comment by jebter** [comment]
Releted to issue:https://github.com/pingcap/tidb/issues/49217
