### ISSUE TITLE
无法修改慢日志文件路径

### ISSUE THREAD

**Issue by ShiQiFangxiao** [pingcap/tidb#54078]
## Bug Report

Please answer these questions before submitting your issue. Thanks!
一、问题描述：

### 1. Minimal reproduce step (Required)

二、问题复现：
1、通过tiup cluster edit-config xxx修改慢日志文件名
server_configs:
  tidb:
    log.slow-query-file: /tidb-deploy/tidb-4000/log/testslow.log

2、reload集群：tiup cluster reload xxx

3、查看慢日志路径，对应的值是/tidb-deploy/tidb-4000/log/tidb_slow_query.log，并没有被改成testslow.log
show config where name like '%slow%';

4、如果将/tidb-deploy/deploy/tidb-4000/scripts/run_tidb.sh中slow-log的配置删除掉，然后重启restart集群，可以生成新路径的slowlog；但如果执行reload操作，又会被还原成/tidb-deploy/tidb-4000/log/testslow.log路径

### 2. What did you expect to see? (Required)
期望结果：
希望能正常修改慢日志路径。

### 4. What is your TiDB version? (Required)
tidb v8.1.0

**Comment by tiancaiamao** [comment]
This is not a TiDB bug, we should report a bug to tiup https://github.com/pingcap/tiup/issues/new?assignees=&labels=type%2Fbug&projects=&template=bug-report.md

**Comment by tiancaiamao** [comment]
I create a new one and close this one https://github.com/pingcap/tiup/issues/2428
