### ISSUE TITLE
The efficiency of auto analyze is low with auto_analyze_priority_queue and infoSchemaV2 open in million tables scenario

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#54086]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tidb_schema_cache_size 2GB
create 100k schemas and about 15 tables each of schema. 1.5 million tables totally
insert data for above tables
It takes about 10 minutes to execute a single analyze task on average when auto_analyze_priority_queue and infoSchemaV2 open. While 20 analyze tasks are executed per minute when auto_analyze_priority_queue or infoSchemaV2 close.
Currently, the automatic statistics collection task priority queue feature retrieves all table information each time it performs an `analyze`, selecting one from them to execute. If some tables are not in the `infoschema` cache, this process is quite time-consuming.
![image](https://github.com/pingcap/tidb/assets/7677963/4c66130e-f136-4a01-89c8-07bf5ac9462d)

### 4. What is your TiDB version? (Required)

Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 6cf8776242fbfe0b922488357867ca5244e7b8fa
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-06-13 11:49:48
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by Rustin170506** [comment]
Closed by https://github.com/pingcap/tidb/issues/55906
