### ISSUE TITLE
TestInfoBuiltin failed after enabling infoschema cache V2

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#54094]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
set DefTiDBSchemaCacheSize to 10 from 0
Run TestInfoBuiltin many times.

### 2. What did you expect to see? (Required)
Always passed.
### 3. What did you see instead (Required)
May fail.
``` 
[2024/06/18 19:55:52.646 +08:00] [INFO] [ddl.go:1317] ["DDL job is finished"] [category=ddl] [jobID=105]
[2024/06/18 19:55:52.646 +08:00] [INFO] [callback.go:140] ["performing DDL change, must reload"] [category=ddl]
    result.go:49: 
        	Error Trace:	/Users/bba/pc/tidb/pkg/testkit/result.go:49
        	            				/Users/bba/pc/tidb/pkg/expression/integration_test/integration_test.go:220
        	Error:      	Not equal: 
        	            	expected: "[3]\n"
        	            	actual  : "[60001]\n"
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -1,2 +1,2 @@
        	            	-[3]
        	            	+[60001]
        	            	 
        	Test:       	TestInfoBuiltin
        	Messages:   	sql:select last_insert_id();, args:[]
```
### 4. What is your TiDB version? (Required)
master

**Comment by lance6716** [comment]
I think the problem can be solved by https://github.com/pingcap/tidb/pull/54035 . We have set the lower bound for cache size, if user wants to set 10 as the cache size, it will be converted to 512 MB and the table cache eviction will not be so frequent. As a result, the allocator can keep its value.
