### ISSUE TITLE
Abnormal logs cause disk space to run out

### ISSUE THREAD

**Issue by spihiker** [pingcap/tidb#54112]
1.TiDB version: 6.5.9

 2 .tidb,pd,tikv on the same machine。tikv outputs a large amount of logs in a short period of time, running out of disk space.

3.tikv-2024-06-12T17-49-17.979.log  tikv-2024-06-12T17-50-54.548.log
tikv-2024-06-12T17-49-26.130.log  tikv-2024-06-12T17-51-02.419.log
tikv-2024-06-12T17-49-33.843.log  tikv-2024-06-12T17-51-10.428.log
tikv-2024-06-12T17-49-42.356.log  tikv-2024-06-12T17-51-18.304.log
tikv-2024-06-12T17-49-49.948.log  tikv-2024-06-12T17-51-25.927.log
tikv-2024-06-12T17-49-58.346.log  tikv-2024-06-12T17-51-35.388.log
tikv-2024-06-12T17-50-06.672.log  tikv-2024-06-12T17-51-43.484.log
tikv-2024-06-12T17-50-14.749.log  tikv-2024-06-12T17-51-51.812.log
tikv-2024-06-12T17-50-22.525.log  tikv-2024-06-12T17-51-59.826.log
tikv-2024-06-12T17-50-30.078.log  tikv-2024-06-14T18-49-55.991.log
tikv-2024-06-12T17-50-38.458.log  tikv.log

[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]
[2024/06/12 17:51:59.827 +08:00] [WARN] [pd.rs:1707] ["failed to update 
max timestamp for region 15101: Pd(Other(\"[components/pd_client/src/tso
.rs:97]: TimestampRequest channel is closed\"))"]

4.What causes this problem to occur? Thanks for your help.

**Comment by hbisheng** [comment]
This issue is the same as https://github.com/tikv/tikv/issues/15041 and has been fixed. We can close it.
