### ISSUE TITLE
strange behavior related with timestamp 

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tidb#5418]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Before is some sql command which can be used to reproduce this bug. 
```
create table t (id int, c1 datetime not null default CURRENT_TIMESTAMP);
select * from t;

set TIMESTAMP = 1234;
select @@timestamp;

insert t (id) values (1);
select * from t;
```
2. What did you expect to see?

```
id	c1
1	1970-01-01 08:20:34
```

3. What did you see instead?
```
id	c1
1	1969-12-31 18:20:34
```

4. What version of TiDB are you using (`tidb-server -V`)?
82b52f53bb11bc49f8850adfb37c72f4eb860117

**Comment by zhexuany** [comment]
The reason I found this bug is because I am at Chicago time which is 14 hours later. If we add 14 hour to `1969-12-31 18:20:34`, it is just `1970-01-01 08:20:34`. I guess this bug is related with time zone.

**Comment by zhexuany** [comment]
One more thing, you have to change the timezone of ur machine when you try to reproduce this.

**Comment by tiancaiamao** [comment]
I'm not sure it's a bug or not. 
Could you compare it with mysql's, when the time zone is Chicago?

**Comment by zhexuany** [comment]
verified with mysql. Behavior is identical. I guess what I was want to express is our test case didn't take timezone into account. Test case for this one always expect "1970-01-01 08:20:34". We can resolve this by letting test case consider timezone.
