### ISSUE TITLE
slow query in dashboard show a lot of ';'

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#54190]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

<img width="1058" alt="image" src="https://github.com/pingcap/tidb/assets/20839912/c913f60f-ec71-4e39-bfc9-e8934477d75a">

use tiup deploy a v8.1 cluster and do nothing

**Comment by jebter** [comment]
duplicate of https://github.com/pingcap/tidb/issues/52743
