### ISSUE TITLE
The data of stats_meta may be inaccurate in create and drop of a large number of tables scenarios

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#54265]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

fast create large number of tables(about 1 million) and drop large number of tables
![imzmC41VGI](https://github.com/pingcap/tidb/assets/7677963/30b65bc8-cc37-44e4-92de-65d2ff388d0d)
```
mysql> select * from stats_meta where table_id=2330618;
+--------------------+----------+--------------+-------+----------+
| version            | table_id | modify_count | count | snapshot |
+--------------------+----------+--------------+-------+----------+
| 450414941342269446 |  2330618 |          682 |   682 |        0 |
+--------------------+----------+--------------+-------+----------+
1 row in set (0.00 sec)

mysql> select TABLE_SCHEMA,TABLE_NAME from information_schema.tables where TIDB_TABLE_ID=2330618;
Empty set (2.37 sec)
```
### 4. What is your TiDB version? (Required)

master

**Comment by hawkingrei** [comment]
fast create large number of tables(about 1 million). which is a large task, our ddl event handler is a single thread handler. it cannot handle too many DDL events as soon as possible.

**Comment by Rustin170506** [comment]
Not reproducible.
