### ISSUE TITLE
lightning: v8.2 lightning failed to import data to v8.1 version tidb cluster

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#54341]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. setup v8.1 tidb cluster
2. use v8.2 lightning import data and use check-requirement = true

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
failed
### 4. What is your TiDB version? (Required)
v8.2

**Comment by D3Hunter** [comment]
the cause it PD and pd-client 8.2 introduced a new API which doesn't exists in 8.1, and lightning reports `unknown method BatchScanRegions for service pdpb.PD` during split-scatter, see https://github.com/pingcap/tidb/pull/54153

lightning doesn't support import into clusters of lower version officially, but it DOES can do it in theory before 8.2

**Comment by AkiraXie** [comment]
after #54365 merged, the issue cannot reproduce
