### ISSUE TITLE
testEvaluatorSuite.TestSubTimeSig fail if my system time zone is set to Denver

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#5436]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I'll testing TiDB if system time zone is not UTC+8 (Beijing), and find this unit test failed.
The system time zone is I used for testing is Denver.

2. What did you expect to see?

All the unit test should PASS. 

3. What did you see instead?

> ----------------------------------------------------------------------
> FAIL: builtin_time_test.go:818: testEvaluatorSuite.TestSubTimeSig
> 
> builtin_time_test.go:879:
>     c.Assert(result, Equals, t.expect)
> ... obtained string = "2017-10-10 13:34:55"
> ... expected string = "2017-10-10 12:34:55"
> 

OOPS: 0 passed, 1 FAILED
--- FAIL: TestT (0.01s

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

> ➜  tidb git:(master) ✗ ./bin/tidb-server -V
> Release Version: v1.1.0-alpha-286-g0a8d91d
> Git Commit Hash: 0a8d91d8965512724e1582592712c11efe564b15
> Git Commit Branch: master
> UTC Build Time:  2017-12-18 09:31:46

**Comment by zhixinwen** [comment]
see the same issue.

**Comment by morgo** [comment]
This bug appears to be fixed in https://github.com/pingcap/tidb/pull/5741

I am going to close this issue now.  Please feel free to re-open it if needed.
