### ISSUE TITLE
CPU usage is high

### ISSUE THREAD

**Issue by kevin19931015** [pingcap/tidb#5445]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

  
   PID USER      PR  NI    VIRT    RES    SHR S        %CPU    %MEM     TIME+ COMMAND                                                                                                                                                   
 17461 root      20   0 6155760 4.585g   6008 S    70.8         14.7   4048:49 tikv-server                                                                                                                                               
108011 root     20   0  169540  81408  12660 S    52.8         0.2     2783:36 tidb-server                                                                                                                                               
 17370 root      20   0 10.118g  73556   8104 S     24.3         0.2     1524:35 pd-server   

2. What did you expect to see?
cpu使用正常

3. What did you see instead?
cpu率使用过高

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
+-----------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                               |
+-----------------------------------------------------------------------------------------------------+
| Release Version: 1.0.0
Git Commit Hash: 93cc2bd4c5ce27480da71a3125ccb7ef7e8c7f6a
Git Branch: release-1.0
UTC Build Time: 2017-10-30 05:37:33 |
+-----------------------------------------------------------------------------------------------------+

**Comment by kevin19931015** [comment]
想知道应该如何定位问题

**Comment by coocood** [comment]
@kevin19931015 
What's the workload of the cluster?

**Comment by kevin19931015** [comment]
This cluster have 3 node,every node was deployed one tidb,one tikv,one pd.We have 2 databases，one is our company's internal project-management-web，workload is not high.Another is our statistics database which include 6 tables.The statistics database's read-write is comparatively frequent，but cpu is well-balanced before.So how I can locate which one sql bring this problem.

**Comment by coocood** [comment]
@kevin19931015 
You can inspect the TiDB log file, search the keyword `slow-query`.

**Comment by kevin19931015** [comment]
I just find this message。。。。
2017/12/19 19:28:46.667 adapter.go:293: [warning] slow-query costTime=594.330211ms sql=SELECT version, table_id, modify_count, count from mysql.stats_meta where version > 396802894616854536 order by version type=slow-query succ=true connectionId=0

**Comment by coocood** [comment]
This is an internal query, you can ignore it.
