### ISSUE TITLE
nightly : The ANALYZE TABLE command does not return a result, but it is actually successful

### ISSUE THREAD

**Issue by shaoxiqian** [pingcap/tidb#54475]
version: nightly

There are 100,000 databases, each containing 29 tables, with each table having 2,000 rows. In total, there are over 1 million tables across these databases, and 2,000 of these databases contain data.

profile:
![image](https://github.com/pingcap/tidb/assets/85105033/7416596b-7afa-4b5e-9b4c-843fa462d3d5)

**Comment by hawkingrei** [comment]
We need to wait for Infoschema v2 to speed up this.

**Comment by Rustin170506** [comment]
@shaoxiqian Can you test it with the latest TiDB, I guess we have fixed it.

**Comment by Rustin170506** [comment]
It has been fixed. You can try the nightly version to verify it.

**Comment by AilinKid** [comment]
any linked pull request for reference of this issue

**Comment by Rustin170506** [comment]
Fixed by https://github.com/pingcap/tidb/pull/57756
