### ISSUE TITLE
 分区表在达到什么数据量才会使用，有没有啥数据的数字指标.分区表用tiflash 是不是会比单表性能更好。

### ISSUE THREAD

**Issue by chiamingiang** [pingcap/tidb#54509]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by Defined2014** [comment]
TiDB 的分区表更多优势是体现在数据管理，比如根据日期建立分区，不需要的时候直接 drop 分区即可。

在性能上，底下都会被打散成各个 region，在性能上，大部分 SQL 两者之间不应该有显著的差别。
