### ISSUE TITLE
add index failed with "Error 1105 (HY000): When the state is JobStateRollbackDone or JobStateCancelled, historyJob.Error should never be nil" when tidb rolling restart

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#54533]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench
2、add index for one of table
3、tidb rolling restart

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index failed with "Error 1105 (HY000): When the state is JobStateRollbackDone or JobStateCancelled, historyJob.Error should never be nil" 

and add index always failed with error when add index again
Error 1105 (HY000): open /var/lib/tidb-data/tmp_ddl-4000/604/11285e7b-8edb-5e07-9896-b33e42d492ec.sst/8f0d6d7d-351e-4c6c-93e4-900f93871a66.sst: no such file or directory

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v8.2.0-alpha
Edition: Community
Git Commit Hash: 1b872e5d6ad29ffeb817a0b55b4ef6eef3de3ac2
Git Branch: heads/refs/tags/v8.2.0-alpha
UTC Build Time: 2024-07-08 11:46:28
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore
2024-07-09T23:20:31.517+0800

**Comment by tangenta** [comment]
Close by #54543
