### ISSUE TITLE
some flags are unexpectedly added to table info meta

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#54751]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

https://github.com/pingcap/tidb/blob/master/pkg/planner/core/find_best_task.go#L2446-L2452
And
https://github.com/pingcap/tidb/blob/f383e0e685b704e1b04ac441cd3dec78d6c2314c/pkg/executor/show.go#L143

### 2. What did you expect to see? (Required)
N/A
### 3. What did you see instead (Required)
N/A

### 4. What is your TiDB version? (Required)
master

**Comment by wshwsh12** [comment]
Fix by https://github.com/pingcap/tidb/pull/55463
