### ISSUE TITLE
Significant CPU usage for tryLockMDLAndUpdateSchemaIfNecessary for insert statement on table over 1k columns

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#54779]
## Enhancement
Even with plan cache hits, high cpu on tryLockMDLAndUpdateSchemaIfNecessary is observed, the table has over 1 thousands columns. seems the loops on `tbl.Meta().Columns` caused high cpu usage, need to see if anyway to optimize the cpu usage when the number of column on the table is high.

![image](https://github.com/user-attachments/assets/e3c54929-35e3-4f70-a8db-f1c06bec1d1c)

![image](https://github.com/user-attachments/assets/4729f57c-868a-41df-8aa1-14065b1df57a)

```
			// Check the column change.
			for _, col := range tbl.Meta().Columns {
				if col.State != model.StatePublic {
					continue
				}
				found := false
				for _, coll := range tableInfo.Columns {
					if col.Name.L == coll.Name.L && col.ID != coll.ID {
						logutil.BgLogger().Info("public column changed", zap.String("column", col.Name.L), zap.String("old_col", coll.Name.L), zap.Int64("new id", col.ID), zap.Int64("old id", coll.ID))
						found = true
						break
					}
				}
				if found {
					if !skipLock {
						sctx.GetSessionVars().GetRelatedTableForMDL().Delete(tableInfo.ID)
					}
					return nil, domain.ErrInfoSchemaChanged.GenWithStack("public column %s has changed", col.Name)
				}
			}
		}
```

**Comment by wjhuang2016** [comment]
I guess there is no DDL in your scenario, right?
We can simplify checking the table change by comparing Revision in tableInfo

**Comment by bb7133** [comment]
Could you please share the profiling file?
