### ISSUE TITLE
Support for $N placeholders in prepared statements

### ISSUE THREAD

**Issue by urandom** [pingcap/tidb#548]
Hi,

Would it be possible to add support for $N placeholders in prepared statements, similarly to what sqlite and postgresql support?
In sqlite N can be anything, number or text, whereas in postgresql N is always a number, and iirc, is sequential. Regardless, in both cases one can use $N where N is a number, keep things sequential, and allow for parameters to be repeatable by repeating some value of N for some parameters.

**Comment by ngaut** [comment]
Hi, @urandom 
We might support $N placeholders later.

**Comment by coocood** [comment]
This is not MySQL syntax, it will be supported when PostgreSQL syntax is supported.
Close this issue for now.
