### ISSUE TITLE
TiKV not free storage space?

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#5480]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I add a server to TiKV group (from 3 to 4), and it seems to rebalance the data to the new server.
I don't do anything these two days.
When I check the TiKV graph, some storage space disappear.
513.5 + 516.4 + 313.2 + 510 = 1853.1
511.9 + 516.3 + 430.7 + 508.9 = 1967.8
114.7GB space disappear.
<img width="461" alt="tikv2-1" src="https://user-images.githubusercontent.com/26958647/34331200-9d13405a-e95f-11e7-9dba-e6efb2af4642.png">
<img width="459" alt="tikv2-2" src="https://user-images.githubusercontent.com/26958647/34331202-a0484388-e95f-11e7-8995-e35660cbb480.png">

2. What did you expect to see?
Just move data to 4th TiKV and free space from other 3 servers.

3. What did you see instead?
114.7GB space disappear.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v1.0.4-1-ga05e014
Git Commit Hash: a05e0146bd7f085938d2631b3726cca7d102537e
Git Branch: release-1.0
UTC Build Time: 2017-12-11 03:07:11

**Comment by shenli** [comment]
@zhangjinpeng1987 PTAL

**Comment by zhangjinpeng1987** [comment]
@DavisLinDB If the space is very sensitive to you, 
1) Using the latest TiKV,
2) and then using tikv-ctl compact all data manually (this will take some time, and will use many system resource),
  $ ./tikv-ctl --host={tikv-ip:tikv-port} compact -c write
  $ ./tikv-ctl --host={tikv-ip:tikv-port} compact -c default
3) add `dynamic-level-bytes` to your config file and restart your TiKV.
 [rocksdb.defaultcf]
 dynamic-level-bytes = true
 [rocksdb.writecf]
 dynamic-level-bytes = true

**Comment by DavisLinDB** [comment]
I try to use command but return error:

./tikv-ctl --host={192.168.29.1:20160} compact -c write
```
error: Found argument '--host' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-ctl [OPTIONS] [SUBCOMMAND]

For more information try --help

```

./tikv-ctl --help
```
TiKV Ctl
PingCAP
Distributed transactional key value database powered by Rust and Raft

USAGE:
    tikv-ctl [OPTIONS] [SUBCOMMAND]

FLAGS:
        --help       Prints help information
    -V, --version    Prints version information

OPTIONS:
    -d <db>                    set rocksdb path
    -e <escaped-to-hex>        convert escaped key to hex key
    -h <hex-to-escaped>        convert hex key to escaped key
    -r <raftdb>                set raft rocksdb path

SUBCOMMANDS:
    diff     diff two region keys
    help     Prints this message or the help of the given subcommand(s)
    mvcc     print the mvcc value
    print    print the raw value
    raft     print raft log entry
    scan     print the range db range
    size     print region size

```
./tikv-ctl --version
```
TiKV Ctl
```

The tikv-ctl and tikv-server I use which in tidb-v1.0.4.tar.gz

[root@node7 bin]# ls -al
```
total 463892
drwxrwxr-x. 2 tidb tidb      4096 Dec 12 12:40 .
drwxrwxr-x. 3 tidb tidb      4096 Dec 12 12:39 ..
-rwxrwxr-x. 1 tidb tidb   3509080 Dec 12 12:39 goyacc
-rwxrwxr-x. 1 tidb tidb  19980219 Dec 12 12:40 pd-ctl
-rwxrwxr-x. 1 tidb tidb  12479766 Dec 12 12:40 pd-recover
-rwxrwxr-x. 1 tidb tidb  27249741 Dec 12 12:40 pd-server
-rwxrwxr-x. 1 tidb tidb  12084410 Dec 12 12:40 pd-tso-bench
-rwxrwxr-x. 1 tidb tidb  37536665 Dec 12 12:39 tidb-server
-rwxrwxr-x. 1 tidb tidb 130791480 Dec 12 12:39 tikv-ctl
-rwxrwxr-x. 1 tidb tidb  67272648 Dec 12 12:40 tikv-fail
-rwxrwxr-x. 1 tidb tidb 164102112 Dec 12 12:40 tikv-server

```

Are tikv-ctl and tikv-server the latest version?

**Comment by DavisLinDB** [comment]
If I don't compact manually,  these storage space will be reuse when insert data next time?

**Comment by DavisLinDB** [comment]
@zhangjinpeng1987 

I modify tikv config file, it free the space.
Thanks!

<img width="462" alt="tikv3-0" src="https://user-images.githubusercontent.com/26958647/34336290-cf7f0f52-e990-11e7-9159-bbc83c3a837d.png">
