### ISSUE TITLE
OOM in Codec.decodeColumn

### ISSUE THREAD

**Issue by frew** [pingcap/tidb#54919]
## Bug Report

We're getting intermittent OOM's in our TiDB daemon.

Looking at the heap dump from oom_records, we see large retained buffers from decodeColumn that don't appear to be accounted for in running_sql:
![image](https://github.com/user-attachments/assets/7ee63246-a331-4cd3-b21a-d2141021a5a3)

We're happy to debug further, but it's unclear what the best way is to understand where these large buffers are coming from or how to limit them. Help?

### 4. What is your TiDB version? (Required)

8.1.0

**Comment by XuHuaiyu** [comment]
Can you put the result of the following sqls here?

``` sql
show variables like '%paging%';
show variables like '%rate_limit%';
```

**Comment by frew** [comment]
Apologies for the delay here. It was an issue with TiKV returning many very large rows (1.5 MB each) in response to a query (ended up figuring it out from query logs). Unfortunately, no longer have the relevant dataset so can't easily find a reproducible subset - closing out this issue.
