### ISSUE TITLE
Every  new session will load global variables from tikv, which may be inefficient.

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#5497]
In `session.loadCommonGlobalVariablesIfNeeded` we will load global variables from tikv when we new a session. Maybe we can use a background routine to load it periodically (or use etcd to notify other TiDBs to load it when someone set global variables.)

**Comment by morgo** [comment]
@winkyao I assume this has this been fixed, because I think I remember seeing reload notices in the logs?

**Comment by nullnotnil** [comment]
This is now cached every 2 seconds. Closing this issue now. Thanks!
