### ISSUE TITLE
Navicat compatible problem

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#5502]
Meet the following error:
`
[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID=' at line 1
SELECT STATE AS `Status`, ROUND(SUM(DURATION),7) AS `Duration`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ;
2017/12/26 15:26:18.982 conn.go:428: [warning] [23] dispatch error:
id:23, addr:10.233.104.0:56637 status:2, collation:utf8_general_ci, user:root
"SELECT STATE AS `Status`, ROUND(SUM(DURATION),7) AS `Duration`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ;"
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/parser/yy_parser.go:138: [parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/*100,3), '%') AS `Percentage` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID=' at line 1
`

Navicat: 10.1.7

**Comment by XuHuaiyu** [comment]
fixed in https://github.com/pingcap/tidb/pull/5960
