### ISSUE TITLE
query stuck when trying to kill it because of OOM

### ISSUE THREAD

**Issue by guo-shaoge** [pingcap/tidb#55042]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. hack tidb code, delete following code, so we can set `tidb_mem_quota_query` a very small value to help reproduce this bug   https://github.com/pingcap/tidb/blob/199bf90c2a6e914d05733bc6dacd9ed2dea77b7f/pkg/sessionctx/variable/sysvar.go#L1127-L1130 
2. build tidb and start tiup playround
3. download [10-tidb-slow.log](https://github.com/user-attachments/files/16422699/10-tidb-slow.log) and `set @@tidb_slow_query_file = '/home/guojiangtao/10-tidb-slow.log';` (remember to change the slow query file path)
4. `set @@tidb_mem_quota_query = 10;`
5. run `select time,host host_ip,Query_time as exec_max_time,parse_time,compile_time,Query as sql_text,Digest as sql_id,is_internal,succ, Plan as plan_text,mem_max as mem_max,User as parse_user,DB as database_name,total_keys,request_count,process_time,process_keys from information_schema.SLOW_QUERY order by time desc;`
### 2. What did you expect to see? (Required)
query is canceled
### 3. What did you see instead (Required)
query is stucked
### 4. What is your TiDB version? (Required)
master 560e92ed721f9c64d22e2c5e4ff35518310cf48e

**Comment by yibin87** [comment]
Selecting plan from slow_query table without limit restriction is not recommanded behavior. And this is a long existing issue. Down to major.

**Comment by yibin87** [comment]
For version 6.5, 7.5, the query met illegal nil pointer: ERROR 1105 (HY000): runtime error: invalid memory address or nil pointer dereference

**Comment by yibin87** [comment]
v8.1.0 stuck also

**Comment by yibin87** [comment]
After debug, located the goroutine that get stuck:
First Projection executor tries to alloc memory:
https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/executor/projection.go#L289
Then, it triggers the memory action panic: 
https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/util/memory/action.go#L173
After it enters runtime.gopanic, and it invokes the recover function in executor::Next:
https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/executor/internal/exec/executor.go#L435
Finally, it got stuck when invokes runtime mcall(recovery)

**Comment by yibin87** [comment]
> The plan is Sort <=== Projection <==== MemTableReader After debug, located the goroutine that get stuck: First Projection executor tries to alloc memory:
> 
> https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/executor/projection.go#L289
> 
> 
> Then, it triggers the memory action panic:
> https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/util/memory/action.go#L173
> 
> 
> After it enters runtime.gopanic, and it invokes the recover function in executor::Next:
> https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/executor/internal/exec/executor.go#L435
> 
> 
> Finally, it got stuck when invokes runtime mcall(recovery)

It turned out to be debug only stuck on mac OS, the real stuck happen on the following stack:
![img_v3_02db_22a7a4bf-a3fb-4d28-b340-a6a3567f0c4g](https://github.com/user-attachments/assets/8a821fa6-6875-424e-85fc-29d8afb49401)

**Comment by yibin87** [comment]
And check the source code, found the unlock may not be invoked:
https://github.com/pingcap/tidb/blob/a187e9d63e87f5fad8c54e28938c572444722eb6/pkg/util/execdetails/execdetails.go#L1303

**Comment by yibin87** [comment]
After fix this, the stuck disappeared, still not know what's actually happening when the panic happen.
