### ISSUE TITLE
After restoring data with BR, the split regions will not result in a large number of merges, thus avoiding unreasonable splits.

### ISSUE THREAD

**Issue by shaoxiqian** [pingcap/tidb#55057]
## Enhancement
BR nightly resotre 50,000 databases, 250,000 tables.
After the restore is completed, the number of regions on the TiKV side is as follows.
![image](https://github.com/user-attachments/assets/7dff99c4-eefe-4e9f-8ff0-b105f2d15b50)
pd region healty
![image](https://github.com/user-attachments/assets/7a089025-d8e6-4311-8c91-332ef470584c)

in house testing  we found that both v1 and v2 see about  35～40% drop in QPS when schemas increase from 1 to 50001. The cause of the performance regression stems from the generation of a vast number of regions.

After merging regions, under the nightly v2 mode, the performance with 50001 schemas actually shows a slight improvement compared to having just 1 schema. But even with the schedule.merge-schedule-limit set to 512, it almost takes 24 hours to complete the merge of regions. The time cost is substantial.

Therefore, we hope that after restoring data with BR, the split regions will not generate a large number of merges, thus avoiding unreasonable splits.

**Comment by Leavrth** [comment]
related issue https://github.com/pingcap/tidb/issues/53532
