### ISSUE TITLE
start timestamp may fall behind safe point

### ISSUE THREAD

**Issue by kevin19931015** [pingcap/tidb#5507]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
We have a cluster with 3 node.
1---pd,tikv,tidb
2---pd,tikv,tidb
3---pd,tikv,tidb
One day,the 2nd node was down（docker was down）.
Then I execute command 'use mydatabase' on other two node,an error occured which tell me  'start timestamp may fall behind safe point'.

2. What did you expect to see?
Other two node can be use normally.

3. What did you see instead?
start timestamp may fall behind safe point

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
+-----------------------------------------------------------------------+
| tidb_version()                                                                                                                               |
+-----------------------------------------------------------------------+
| Release Version: 1.0.0
Git Commit Hash: 93cc2bd4c5ce27480da71a3125ccb7ef7e8c7f6a
Git Branch: release-1.0
UTC Build Time: 2017-10-30 05:37:33 |
+-----------------------------------------------------------------------+

**Comment by disksing** [comment]
Hi @kevin19931015 , thanks for your feedback.
Apparently the direct reason is the tidb-server failed to load the GC safe point from pd-server.
Could you check pd-server's health status by `curl http://pd-addr:2379/pd/api/v1/leader`? Also, attach the tidb and pd log files will help us troubleshoot.
