### ISSUE TITLE
Create interval partition not report error when partition numbers exceed limit number

### ISSUE THREAD

**Issue by Defined2014** [pingcap/tidb#55093]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
CREATE TABLE employees (
    id int unsigned NOT NULL
) PARTITION BY RANGE (id) INTERVAL (1) FIRST PARTITION LESS THAN (1) LAST PARTITION LESS THAN (81920);
```

### 2. What did you expect to see? (Required)

```
report error
```

### 3. What did you see instead (Required)

```
no error, created a table with 8192 partitions.
```

**Comment by Defined2014** [comment]
@mjonss Do you think it's a bug or not? Should we fix it?

**Comment by mjonss** [comment]
> @mjonss Do you think it's a bug or not? Should we fix it?

I consider it to be a bug, I propose to return an error instead of creating a table with one partition less than requested.
