### ISSUE TITLE
misc information is not reset when full load info schema

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#55132]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
func (isd *Data) resetBeforeFullLoad(schemaVersion int64) {
	resetTableInfoResidentBeforeFullLoad(isd.tableInfoResident, schemaVersion)

	resetByIDBeforeFullLoad(isd.byID, schemaVersion)
	resetByNameBeforeFullLoad(isd.byName, schemaVersion)

	resetSchemaMapBeforeFullLoad(isd.schemaMap, schemaVersion)
	resetSchemaID2NameBeforeFullLoad(isd.schemaID2Name, schemaVersion)

	resetPID2TIDBeforeFullLoad(isd.pid2tid, schemaVersion)
}
```
resetBeforeFullLoad already handles some V2-related data, but the common data in misc is not handled.
### 2. What did you expect to see? (Required)
N/A
### 3. What did you see instead (Required)
N/A
### 4. What is your TiDB version? (Required)
master

**Comment by tiancaiamao** [comment]
close by https://github.com/pingcap/tidb/pull/55229
