### ISSUE TITLE
tidb performance test by yeepay

### ISSUE THREAD

**Issue by sgphappy2007** [pingcap/tidb#5515]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
做tidb性能测试，并发insert数据，数据量达到10亿以上时，tikv一个节点down了，
机器配置：
centos7.3  ext4  tikv：ssd硬盘
拓扑结构：
110.151.112.115 tidb,MONITOR, PD
110.151.112.116 tidb,pd
110.151.112.216 tikv,pd
110.151.112.217 tikv
110.151.112.218 tikv

2. What did you expect to see?

给个查tikv down的原因的方法

3. What did you see instead?
10.151.11.218 
tikv log:
2017/12/27 15:17:05.342 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)
2017/12/27 15:17:05.342 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)
2017/12/27 15:17:05.342 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)
2017/12/27 15:17:05.349 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)
2017/12/27 15:17:06.458 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)
2017/12/27 15:17:06.458 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)
2017/12/27 15:17:06.459 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed)

centos系统  dmesg信息：
[518623.825029] ACPI Error: SMBus/IPMI/GenericSerialBus write requires Buffer of length 66, found length 32 (20130517/exfield-389)
[518623.825041] ACPI Error: Method parse/execution failed [\_SB_.PMI0._PMM] (Node ffff880169ae45c8), AE_AML_BUFFER_LIMIT (20130517/psparse-536)
[518623.825058] ACPI Exception: AE_AML_BUFFER_LIMIT, Evaluating _PMM (20130517/power_meter-339)
[518638.823419] ACPI Error: SMBus/IPMI/GenericSerialBus write requires Buffer of length 66, found length 32 (20130517/exfield-389)
[518638.823429] ACPI Error: Method parse/execution failed [\_SB_.PMI0._PMM] (Node ffff880169ae45c8), AE_AML_BUFFER_LIMIT (20130517/psparse-536)
[518638.823443] ACPI Exception: AE_AML_BUFFER_LIMIT, Evaluating _PMM (20130517/power_meter-339)
[518653.828952] ACPI Error: SMBus/IPMI/GenericSerialBus write requires Buffer of length 66, found length 32 (20130517/exfield-389)
[518653.828965] ACPI Error: Method parse/execution failed [\_SB_.PMI0._PMM] (Node ffff880169ae45c8), AE_AML_BUFFER_LIMIT (20130517/psparse-536)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.1.0-alpha-284-g4d57f42
Git Commit Hash: 4d57f422fe1d4ff4522f4ca3bedd56a026bf8a43
Git Commit Branch: master
UTC Build Time:  2017-12-16 03:00:52

**Comment by zhangjinpeng1987** [comment]
@sgphappy2007 How about your hardware configuration?

**Comment by zhangjinpeng1987** [comment]
@sgphappy2007 Any suspicious log in `tikv.log` file?

**Comment by sgphappy2007** [comment]
tikv配置：2cpu      40  Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

**Comment by sgphappy2007** [comment]
tikv:40  Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

**Comment by sgphappy2007** [comment]
cpu cores  : 10，memory：128G ,disk : 2.9T ssd

**Comment by sgphappy2007** [comment]
tikv.log中没有其它信息，就一直报 2017/12/27 15:17:06.459 kv.rs:804: [ERROR] send raft msg to raft store fail: Transport(Closed) ，我就想知道我怎么查错，给个思路，谢谢

**Comment by zhangjinpeng1987** [comment]
Have you  checked all tikv logs?

**Comment by zhangjinpeng1987** [comment]
Is there OOM error in dmesg log?

**Comment by zhangjinpeng1987** [comment]
How did you deploy the TiDB cluster?

**Comment by zhangjinpeng1987** [comment]
You can use the following command to check is there a thread named `rafstore`.
$ top -Hp tikv-pid

**Comment by sgphappy2007** [comment]
另外一台tikv的logs:

2017/12/28 10:09:03.002 transport.rs:229: [INFO] resolve store 5 address ok, addr 10.151.11.218:20160
2017/12/28 10:09:03.002 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:03.008 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:03.011 apply.rs:699: [INFO] [region 60353] 60355 execute admin command cmd_type: CompactLog compact_log {compact_index: 1408244 compact_term: 9} at [term: 9, index: 1408246]
2017/12/28 10:09:03.015 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:03.017 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:03.019 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:03.021 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))
2017/12/28 10:09:03.021 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))
2017/12/28 10:09:03.021 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))
2017/12/28 10:09:03.021 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))
2017/12/28 10:09:03.043 apply.rs:699: [INFO] [region 6605] 6607 execute admin command cmd_type: CompactLog compact_log {compact_index: 7193084 compact_term: 29} at [term: 29, index: 7193086]
2017/12/28 10:09:03.299 apply.rs:699: [INFO] [region 1789] 1791 execute admin command cmd_type: CompactLog compact_log {compact_index: 12336010 compact_term: 27} at [term: 27, index: 12336012]
2017/12/28 10:09:03.340 apply.rs:699: [INFO] [region 43445] 43447 execute admin command cmd_type: CompactLog compact_log {compact_index: 2036416 compact_term: 14} at [term: 14, index: 2036418]
2017/12/28 10:09:03.448 apply.rs:699: [INFO] [region 60045] 60047 execute admin command cmd_type: CompactLog compact_log {compact_index: 1416750 compact_term: 10} at [term: 10, index: 1416752]
2017/12/28 10:09:03.449 apply.rs:699: [INFO] [region 76935] 76937 execute admin command cmd_type: CompactLog compact_log {compact_index: 516192 compact_term: 8} at [term: 8, index: 516194]
2017/12/28 10:09:03.449 apply.rs:699: [INFO] [region 53136] 53138 execute admin command cmd_type: CompactLog compact_log {compact_index: 1674123 compact_term: 14} at [term: 14, index: 1674125]
2017/12/28 10:09:04.106 transport.rs:229: [INFO] resolve store 5 address ok, addr 10.151.11.218:20160
2017/12/28 10:09:04.106 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:04.111 raft_client.rs:55: [INFO] server: new connection with tikv endpoint: 10.151.11.218:20160
2017/12/28 10:09:04.131 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))
2017/12/28 10:09:04.131 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))
2017/12/28 10:09:04.131 raft_client.rs:95: [WARN] send raftmessage to 10.151.11.218:20160 failed: Grpc(RpcFinished(Some(RpcStatus { status: Cancelled, details: Some("Cancelled") })))

**Comment by sgphappy2007** [comment]
dmesg中没有OOM

**Comment by sgphappy2007** [comment]
用ansible方法部署的 tidb cluster

**Comment by sgphappy2007** [comment]
在故障tikv上通过top -Hp tikv-pid 未找到raftstore线程，难道是raftstore线程退出导致的？

**Comment by sgphappy2007** [comment]
这个raftstore线程怎么能起来？

**Comment by zhangjinpeng1987** [comment]
The full name of that thread is `raftstore-{store-id}`, can you provide the output of command `top -Hp tikv-pid`?

**Comment by sgphappy2007** [comment]
top -Hp 21875
Threads: 141 total,   0 running, 141 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0.1 us,  0.1 sy,  0.0 ni, 99.8 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 13182310+total,  8053516 free, 32422232 used, 91347360 buff/cache
KiB Swap:        0 total,        0 free,        0 used. 98586832 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                                               
21899 tidb      20   0 62.142g 0.029t  28788 S  5.0 23.8  31:47.24 promepusher                                                                                                                                           
21904 tidb      20   0 62.142g 0.029t  28788 S  3.4 23.8  35:35.27 rocksb-metrics-                                                                                                                                       
21892 tidb      20   0 62.142g 0.029t  28788 S  0.8 23.8   1317:54 grpc-server-0                                                                                                                                         
21875 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:05.58 tikv-server                                                                                                                                           
21880 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:00.07 tikv-server                                                                                                                                           
21881 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:12.50 tikv-server                                                                                                                                           
21882 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:28.25 pd-0                                                                                                                                                  
21883 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:00.00 tikv-server                                                                                                                                           
21884 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:42.95 time-monitor-wo                                                                                                                                       
21885 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 115:50.61 rocksdb:bg0                                                                                                                                           
21886 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 114:52.27 rocksdb:bg1                                                                                                                                           
21887 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 126:08.66 rocksdb:bg2                                                                                                                                           
21888 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 110:52.50 rocksdb:bg3                                                                                                                                           
21889 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8  95:41.54 rocksdb:bg4                                                                                                                                           
21890 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 194:45.40 rocksdb:bg0                                                                                                                                           
21891 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:00.54 store address r                                                                                                                                       
21893 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 885:10.85 grpc-server-1                                                                                                                                         
21894 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1404:47 grpc-server-2                                                                                                                                         
21895 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 925:15.91 grpc-server-3                                                                                                                                         
21896 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   0:00.00 debugger0                                                                                                                                             
21902 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 776:24.70 storage-schedul                                                                                                                                       
21906 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:29.48 endpoint-normal                                                                                                                                       
21908 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:40.05 endpoint-normal                                                                                                                                       
21909 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:42.34 endpoint-normal                                                                                                                                       
21910 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:26.58 endpoint-normal                                                                                                                                       
21911 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:15.18 endpoint-normal                                                                                                                                       
21912 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:45.11 endpoint-normal                                                                                                                                       
21913 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:28.72 endpoint-normal                                                                                                                                       
21914 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:41.31 endpoint-normal                                                                                                                                       
21915 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:36.13 endpoint-normal                                                                                                                                       
21916 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:54.05 endpoint-normal                                                                                                                                       
21917 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   2:03.19 endpoint-normal                                                                                                                                       
21918 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   3:24.17 pd worker                                                                                                                                             
21919 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:56.78 endpoint-normal                                                                                                                                       
21921 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:55.51 endpoint-normal                                                                                                                                       
21922 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 178:37.53 sched-worker-po                                                                                                                                       
21923 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8   1:14.40 endpoint-normal                                                                                                                                       
21924 tidb      20   0 62.142g 0.029t  28788 S  0.0 23.8 178:15.58 sched-worker-po

**Comment by sgphappy2007** [comment]
文件有点大，不确定哪些没用，所以全传了

**Comment by sgphappy2007** [comment]
[tikv.log.tar.gz](https://github.com/pingcap/tidb/files/1592610/tikv.log.tar.gz)

**Comment by BusyJay** [comment]
Thanks for the log. Can you also provide the version of TiKV?

**Comment by sgphappy2007** [comment]
Release Version: v1.1.0-alpha-284-g4d57f42
Git Commit Hash: 4d57f42
Git Commit Branch: master
UTC Build Time: 2017-12-16 03:00:52

**Comment by sgphappy2007** [comment]
| 5.7.1-TiDB-v1.1.0-alpha-284-g4d57f42

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to reopen if you have additional questions. Thanks!
