### ISSUE TITLE
No plan cache hit when sql-mode = "ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER"

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#55171]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

We found there is no plan cache hit when sql_mode is setting to `ONLY_FULL_GROUP_BY,NO_AUTO_CREATE_USER`
if this is a known limitation, we should document it.

### 2. What did you expect to see? (Required)
plan cache hit

### 3. What did you see instead (Required)
plan cache miss

### 4. What is your TiDB version? (Required)
v8.1.0+

**Comment by AilinKid** [comment]
if there some reproduce steps to show it, it will be more convenient to ack it as soon as possible

**Comment by Rustin170506** [comment]
@dbsid Please include some reproducible steps here. Thank you!

**Comment by qw4990** [comment]
After changing the sql_mode, the optimizer has to generate new plans using the new sql_mode, which can affect the plan cache hit. I guess this may be the reason of this issue.
And I can't reproduce this issue using both test_miss.txt and test_hits.txt, so I'll close this issue, but please reopen it and contact me if this happens again:

![Image](https://github.com/user-attachments/assets/912fdc01-98d0-46d6-91ea-7aa6228ee9f5)
