### ISSUE TITLE
table option PACK_KEYS compatibility in CREATE TABLE syntax

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#5525]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`create table t (a int(11)) ENGINE=InnoDB DEFAULT CHARSET=latin1 PACK_KEYS=1`

2. What did you expect to see?
```
mysql> create table t (a int(11)) ENGINE=InnoDB DEFAULT CHARSET=latin1 PACK_KEYS=1;
Query OK, 0 rows affected (0.02 sec)
```

3. What did you see instead?
```
MySQL [gin]> create table t (a int(11)) ENGINE=InnoDB DEFAULT CHARSET=latin1 PACK_KEYS=1;
ERROR 1105 (HY000): line 1 column 73 near "=1" (total length 75)
MySQL [gin]> create table t (a int(11)) ENGINE=InnoDB DEFAULT CHARSET=latin1;
Query OK, 0 rows affected (0.10 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v1.0.5
Git Commit Hash: efb13f13b331b340147a63271161e7920eba7e96
Git Branch: release-1.0
UTC Build Time: 2017-12-26 01:45:54
```

**Comment by zimulala** [comment]
Relate to #3574
