### ISSUE TITLE
Yml file format error

### ISSUE THREAD

**Issue by xiaoqiang2209** [pingcap/tidb#5526]
[root@cpdb01 tidb-ansible-master]# ansible-playbook local_prepare.yml
ERROR: file could not read: /root/tidb-ansible-master/roles/local/tasks/{{ deployment_method }}_deployment.yml
[root@cpdb01 tidb-ansible-master]# uname -a
Linux cpdb01.hfa.mysql 3.10.0-514.el7.x86_64 #1 SMP Tue Nov 22 16:42:41 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[root@cpdb01 tidb-ansible-master]# cat /etc/redhat-release 
CentOS Linux release 7.3.1611 (Core) 
[root@cpdb01 tidb-ansible-master]# cat inventory.ini |grep deployment_method
deployment_method = binary
[root@cpdb01 tidb-ansible-master]# ll /root/tidb-ansible-master/roles/local/tasks/binary_deployment.yml
-rw-r--r--. 1 root root 1403 Dec 22 12:02 /root/tidb-ansible-master/roles/local/tasks/binary_deployment.yml

**Comment by shenli** [comment]
@louishust PTAL

**Comment by LinuxGit** [comment]
@xiaoqiang2209 Hi. It seems that there's no `deployment_method ` in your` tidb-ansible/inventory.ini ` file. See [inventory.ini ](https://github.com/pingcap/tidb-ansible/blob/master/inventory.ini#L60).

**Comment by xiaoqiang2209** [comment]
@LinuxGit 
[root@cpdb01 tidb-ansible-master]# cat inventory.ini |grep deployment_method
deployment_method = binary

**Comment by LinuxGit** [comment]
Hi, what's your ansible version?  You can install it by following commands and try again.
```
yum install epel-release
yum install ansible
```

**Comment by xiaoqiang2209** [comment]
@LinuxGit hi,
[root@cpdb01 tidb-ansible-master]# yum install epel-release
yum install ansibleLoaded plugins: fastestmirror
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
Package epel-release-7-6.noarch already installed and latest version
Nothing to do
[root@cpdb01 tidb-ansible-master]# yum install ansible
Loaded plugins: fastestmirror
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
Package ansible-1.9.2-1.el7.noarch already installed and latest version
Nothing to do
[root@cpdb01 tidb-ansible-master]# ansible --version
ansible 1.9.2
  configured module search path = None

**Comment by LinuxGit** [comment]
@xiaoqiang2209 You need install Ansible 2.3 or later to your platform. See https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#install-ansible-in-the-control-machine. Please uninstall your ansible package and install ansible from epel repo again.
