### ISSUE TITLE
lightning might report "verify allocator base failed. local..." using parallel import and they have same task id

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#55384]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

suppose we are using 2 instances to do parallel import, if they start at same time, their task ID will be the same as we use current time as the id, but we expect 2, it might fail when allocating row ids.
https://github.com/pingcap/tidb/blob/7e9f85320d7614047c8441256803bb5120622a81/lightning/pkg/server/lightning.go#L359

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
fail
### 4. What is your TiDB version? (Required)
master

**Comment by D3Hunter** [comment]
start those instances one by one with some small interval can workaround this

**Comment by ei-sugimoto** [comment]
I would like to tackle this program. How about using uuid?

**Comment by D3Hunter** [comment]
> I would like to tackle this program. How about using uuid?

lgtm
