### ISSUE TITLE
Add support for alter table convert to syntax

### ISSUE THREAD

**Issue by holys** [pingcap/tidb#5540]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql > create table user(id int);
mysql>  alter table user  CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
```

2. What did you expect to see?

```
mysql> alter table user  CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
Query OK, 0 rows affected (0.09 sec)
Records: 0  Duplicates: 0  Warnings: 0
```

3. What did you see instead?

```
mysql>  alter table user  CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;
ERROR 1105 (HY000): line 1 column 25 near " TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin" (total length 70)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
tidb_version(): Release Version: v1.1.0-alpha-293-g0b5c0cf9
Git Commit Hash: 0b5c0cf94d852901f8e2392917a97d85eb851a55
Git Branch: master
UTC Build Time: 2018-01-02 07:53:48
```

Ref:
```
ALTER TABLE tbl_name
  | CONVERT TO CHARACTER SET charset_name [COLLATE collation_name]
```

**Comment by shenli** [comment]
@holys We will not support charset converting in short term.

**Comment by holys** [comment]
Can we support syntax in parser firstly and tell the user that we don't support this feature now.

**Comment by holys** [comment]
https://github.com/pingcap/tidb/pull/6416  supports it.
