### ISSUE TITLE
Add "Global" to SHOW INDEXES output

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#55452]
## Enhancement
Global index is currently in experimental state. `SHOW INDEXES IN t` does not have a column for GLOBAL, to indicate if it is a global index or not.

**Comment by samba-rgb** [comment]
Hi @mjonss  I would like to work on this issue.

**Comment by mjonss** [comment]
> Hi @mjonss I would like to work on this issue.

@samba-rgb I have assigned you, if you need any help, just ask! Looking at previous PRs may help as well :)

**Comment by samba-rgb** [comment]
Hi @mjonss , i am done with code but unable to create a pr, Doesnt have permission to push any new branch
can you please guide me in this

**Comment by mjonss** [comment]
Fixed by #56028
