### ISSUE TITLE
Panic when planner/core.tryLockMDLAndUpdateSchemaIfNecessary for insert statement

### ISSUE THREAD

**Issue by yibin87** [pingcap/tidb#55486]
Git Commit Hash\"=336d3a30f12cf11f10593b7131046c2291a22d4c] [\"Git Branch\"=heads/refs/tags/v8.3.0-alpha] [\"UTC Build Time\"=\"2024-08-17 11:45:28\"]

Error from regression test:
{"pod":"tc-tidb-1","container":"tidb","level":"ERROR","namespace":"endless-htap-consistency-chaos-tps-7551858-1-686","log":"[conn.go:1040] [\"connection running loop panic\"] [conn=302008324] [session_alias=] [lastSQL=\"insert into pk_is_handle1(a,b,c,d,e,g,h,i,j) values (-9223372036854758807,-929912433,\\\"FsnVyvDSuaayN2QqLVvq5dyvdvJqmaglBICv3TO98QMKYatOv4QfXrZ6I9x227Hxr837YRSMD2DKms0gjqsKnmiAZbZXxk9gON7V\\\",\\\"sxLtEgw7sfkijRlc11OXJWdm9XGenPhlQw2FowGqczpiMeqZaYDZWldoCJOllxm608i1PYHxIy5zrWHhxN4wAMK1oOrHvB0Q4mBs\\\",-1679312550,-3747901375904954483,-8808.8808,\\\"47870613\\\",\\\"94681230225656\\\"),(-9223372036854758806,-1746148455,\\\"KuFE5qZElYY4Ee8OVYhX5nzndZAxkC3pPq5miQrDXnPdabpjdx5sGe2uiaFA2krYVo03FmcUJ5eROtuLadCfttCkykrAMIxf4cDk\\\",\\\"tZ7i5dRQ86xvMVUJSSYSkGgeUINYR7mXFavmLaI7lUSZsepNxVqOU7YziNTwBPk1RTuPObvImmAvfYSXPh6VOwVxhNM8qi1HbDSc\\\",-838490856,98679124211438627,8949.8949,\\\"20000204\\\",\\\"60360718133333\\\"),(-9223372036854758805,1592274591,\\\"AblxnIa80dFCUlRc2OxcQv0irgwQAYuiNodOVS6XoOG8BVO9NpLeKvrn8bhXv8GG2NOVtbCUTEoDALeRpGYzP5ecSNWfZifCPBOK\\\",\\\"OZL9aVuRZKsYNVCaXDUwpLdZUePTDwmfpjNY74PSdAEYtXew5XXQQJXx598PCLxLRAgLJoHhr3D8Lqe8etfTFq04ydvbeO9gZZLm\\\",-278415956,-662998268240949610,6957.6957,\\\"49010614\\\",\\\"49490614102626\\\"),(-9223372036854758804,534299673,\\\"K9v8XIKoGuzfJUzOngbPn9i9aTwJwHVsj5fUFMJBPuCKpXdSCtlivKOF4NVmncZVTTBOMS8CmSf4cgsZHwIaBs3Jg2uYEwuOW2KG\\\",\\\"4F71PlqJeO3e10srEKM8XsnN0RlOIsUqxOzFlOEti5VMB86h9d5TaCggPm98xPcSyZyqNavMlx3IKxymGAurl2XKYZtVCf0LhMwq\\\",587223020,486142138552098739,1711.1711,\\\"42430512\\\",\\\"59640718133333\\\"),(-9223372036854758803,1473088847,\\\"gq9ll91tGH86Q13y48ZiQbdAcgbiNAcMLG50BGcjPqGhywAQ30uqHCTdRHQFeYB1bWQUqhfm8qycJNzOuVfTy8g6GKIm8CZiwISQ\\\",\\\"76uKbLyA9TgrzKCDpkoy4Z1ckSOI8ZyVAgIQMaCNq3t7Z4R3fs3wfb5F7RBygswLPcvpKvhZi22ktm2J4AdABJ762CKU1JVVNctF\\\",-369492894,-2854859301264981866,915.915,\\\"54300615\\\",\\\"84791026194949\\\"),(-9223372036854758802,-1740671013,\\\"8ZhLWd0KokEb5watXXFYwwhsZQ07GYk61K5T3DvMmbRGCxc6ndE3iIo0NiuQVSegZIPrgnVptiPmSqebpjSnJ8G4S82BDUVRxbxB\\\",\\\"b0fvwnCouu4r3NXmFmoLYXKWepzc7eYngyYqrNOSunr7xkKyW9kZRxqblvHZsYbBZ6c3VqNA22vc2svBU9fZZH7cxeCyfCMJdrnc\\\",475522711,3969958651960500315,1581.1581,\\\"87471126\\\",\\\"78421024184545\\\"),(-9223372036854758801,628977637,\\\"GKPJuUaIS5KARumXbZ5ifOFLUjhJbo369AFEZaqvNSegOZfgVvKjhyVAU5CsnswQ2djpJJOleAWI18WTHsrTVe88DyUdL3r888Uo\\\",\\\"RvVEm1fHpfGFL5vTsfKFmDNuPpSC7ihYi6dybQolCvkknpdZwH4oOXPnfVBMwANTaczqH1RAI8cFqIjEydB15oK1O6lcMoG584Xw\\\",-2144369181,3697671649614677189,2689.2689,\\\"79811025\\\",\\\"67580820153838\\\"),(-9223372036854758800,1637390919,\\\"BGomsoZpzLgv0VaeiE6NW5vkCwy8qXfKny1v9e24n1se1CRsXb4P3AbwrI6LlOqpmNnUaLbIu9NvOG2TZkv30Ep75qxYn2vtYPIt\\\",\\\"p5DpeLiDZmFVmfOrb800fvoHQFlnwukcobkWR26VJOubilKQ5sKdsrDfweNZlvuyEOwntFXBjn8nHHvJzeN1G78sJBx1JCaK00Bu\\\",553666683,726777572676208729,4551.4551,\\\"64900819\\\",\\\"25950306041010\\\"),(-9223372036854758799,34889530,\\\"SFAxvaR3ek6kkr3cak1HRCRSaQtMKeRacUOMUqXmUF0kmsrcDIslRfzzxFU7KnENVfkwPRyNrvUjOHjGOzXZSp7XgEtZOQsatQNi\\\",\\\"OIcV5aMJ1Irszb2LvbY80RD3P5P8NYDztcbnzTj0nlimhChOYjeNT2qvuF0SaTyRaaEh9inrUol9q5nOc0beOOqHDu4RNWKrKBKl\\\",-76714506,4380029918886034945,4971.4971,\\\"17350103\\\",\\\"64460819143636\\\"),(-9223372036854758798,1748319862,\\\"ohHPY8DEF55wOcvU5Jk0Kxs3tTBMo4BHpWU11kyHu3GaDR1xQqivcGMUSmRarWBYxp0n23r1Rt3kQO0egFB5f59ZY45nAYVG2TlE\\\",\\\"LplHMiSIu8OqOnmn5w5BlewLWUWm29ufbKApSGhDjkXJSHlwYSsJDnomyXjjYMKnzqyo8JA7Ma4B6Ud6mq88uBqch4itvR3ndncU\\\",-927712065,3042428565451235497,6641.6641,\\\"62090718\\\",\\\"69110821153939\\\"),(-9223372036854758797,-1520679473,\\\"uq7jAPvwrydjxzZcnG6Yze4b7tKIRBsyyeI7wPJDRSqDyXJ2xW3Z8qwkidbtM1javnJ5oS4StscYn3Pi0qb6UqtfkeUIcuQPwsdI\\\",\\\"cwLCgwUVwSfXPauRJ4ZoRf5tU6jBzpw46s6LUaLn7ev7GGebff3Ts5qJkHCSVrgMhzsZNJTODj5e9DI1TYpjS0zdTt2KwOnJeMI0\\\",-825798117,2576593771013727842,-5170.5170,\\\"88701127\\\",\\\"11580101000101\\\"),(-9223372036854758796,-384702557,\\\"mrrDf2DyTkXN7EyGxhjUYwVFia5ehihNfnSQvNtGIXrHb4iTqVsk7xB9QjtZbPn3MUDdc90PBjPBXJwLe1f29unWkvgUYRRPBGtC\\\",\\\"1tN9LcNmWfUULdrJqdLbjg9S34MCmXDaf3PKqFx1siGKZffH2vFOJuONi7uGyr6ksCjdCsM4aTMEe4seCVrw2e3xrVg5RgpOJ8TS\\\",626171091,-3228057002635451582,625.625,\\\"66800820\\\",\\\"36540409071717\\\"),(-9223372036854758795,1564533309,\\\"im9SSAjazBKMtSmzJSOOrFXzToulZt50VzPCPyEEkH8wM3SXE9GcRpdgMYY88w3NIFfXmgQFNQixMRn98fInfhmRxCpaetEYDF8C\\\",\\\"owO9UQLjl4s689FhB8X8vKYZBxuW7mYLrquwhJsitIFH9V1KmkoE8s8BVmWYAss4gKA40fhhzfaACgnq0fo0VH9IstBPcQ7f5MN6\\\",-68188796,998811214901181826,-1950.1950,\\\"20090204\\\",\\\"37520410071818\\\"),(-9223372036854758794,-1620508876,\\\"(len:309552)\"] [err=\"runtime error: invalid memory address or nil pointer dereference\"] [stack=\"[github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1043\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:914\\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile.func1\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/compiler.go:57\\nruntime.gopanic\\n\\t/usr/local/go/src/runtime/panic.go:914\\nruntime.panicmem\\n\\t/usr/local/go/src/runtime/panic.go:261\\nruntime.sigpanic\\n\\t/usr/local/go/src/runtime/signal_unix.go:861\\ngithub.com/pingcap/tidb/pkg/infoschema.(*SessionTables).ensureSchema\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema.go:757\\ngithub.com/pingcap/tidb/pkg/infoschema.(*SessionTables).AddTable\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema.go:703\\ngithub.com/pingcap/tidb/pkg/infoschema.(*SessionExtendedInfoSchema).UpdateTableInfo\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema.go:869\\ngithub.com/pingcap/tidb/pkg/planner/core.tryLockMDLAndUpdateSchemaIfNecessary\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:1943\\ngithub.com/pingcap/tidb/pkg/planner/core.(*preprocessor).handleTableName\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:1608\\ngithub.com/pingcap/tidb/pkg/planner/core.(*preprocessor).Enter\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:263\\ngithub.com/pingcap/tidb/pkg/parser/ast.(*InsertStmt).Accept\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/parser/ast/dml.go:2436\\ngithub.com/pingcap/tidb/pkg/planner/core.Preprocess\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:141\\ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/compiler.go:67\\ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2093\\ngithub.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/driver_tidb.go:291\\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:2051\\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1805\\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1379\\ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1141\\ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn\\n\\t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/server.go:741](http://github.com/pingcap/tidb/pkg/server.(*clientConn).Run.func1//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1043//nruntime.gopanic//n//t/usr/local/go/src/runtime/panic.go:914//ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile.func1//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/compiler.go:57//nruntime.gopanic//n//t/usr/local/go/src/runtime/panic.go:914//nruntime.panicmem//n//t/usr/local/go/src/runtime/panic.go:261//nruntime.sigpanic//n//t/usr/local/go/src/runtime/signal_unix.go:861//ngithub.com/pingcap/tidb/pkg/infoschema.(*SessionTables).ensureSchema//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema.go:757//ngithub.com/pingcap/tidb/pkg/infoschema.(*SessionTables).AddTable//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema.go:703//ngithub.com/pingcap/tidb/pkg/infoschema.(*SessionExtendedInfoSchema).UpdateTableInfo//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/infoschema/infoschema.go:869//ngithub.com/pingcap/tidb/pkg/planner/core.tryLockMDLAndUpdateSchemaIfNecessary//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:1943//ngithub.com/pingcap/tidb/pkg/planner/core.(*preprocessor).handleTableName//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:1608//ngithub.com/pingcap/tidb/pkg/planner/core.(*preprocessor).Enter//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:263//ngithub.com/pingcap/tidb/pkg/parser/ast.(*InsertStmt).Accept//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/parser/ast/dml.go:2436//ngithub.com/pingcap/tidb/pkg/planner/core.Preprocess//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/planner/core/preprocess.go:141//ngithub.com/pingcap/tidb/pkg/executor.(*Compiler).Compile//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/executor/compiler.go:67//ngithub.com/pingcap/tidb/pkg/session.(*session).ExecuteStmt//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/session/session.go:2093//ngithub.com/pingcap/tidb/pkg/server.(*TiDBContext).ExecuteStmt//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/driver_tidb.go:291//ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleStmt//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:2051//ngithub.com/pingcap/tidb/pkg/server.(*clientConn).handleQuery//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1805//ngithub.com/pingcap/tidb/pkg/server.(*clientConn).dispatch//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1379//ngithub.com/pingcap/tidb/pkg/server.(*clientConn).Run//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/conn.go:1141//ngithub.com/pingcap/tidb/pkg/server.(*Server).onConn//n//t/home/jenkins/agent/workspace/build-common/go/src/github.com/pingcap/tidb/pkg/server/server.go:741)\"]"}

**Comment by wjhuang2016** [comment]
Could you reproduce it ?

**Comment by yibin87** [comment]
Two tcms tests failed due to this panic, no simple cases to reproduce the issue now.

**Comment by wjhuang2016** [comment]
> Two tcms tests failed due to this panic just recently, no simple cases to reproduce the issue now.

So the bug may be introduced recently?

**Comment by yibin87** [comment]
> > Two tcms tests failed due to this panic just recently, no simple cases to reproduce the issue now.
> 
> So the bug may be introduced recently?

I think so

**Comment by wjhuang2016** [comment]
Maybe caused by https://github.com/pingcap/tidb/pull/55229
