### ISSUE TITLE
Infoschema V2 Cache Size metric is unchanged when set tidb_schema_cache_size 0

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#55490]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

set @@tidb_schema_cache_size =0
![img_v3_02dt_e9df03fa-ef37-4831-8756-056d08303b1g](https://github.com/user-attachments/assets/fdc70c4f-4f71-4587-9429-cb8e0436466d)

### 4. What is your TiDB version? (Required)

master

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
