### ISSUE TITLE
Allow to specify diagnostics folder

### ISSUE THREAD

**Issue by Tema** [pingcap/tidb#55513]
## Enhancement

TiDB Server piggybacks on [--log-file](https://docs.pingcap.com/tidb/stable/command-line-flags-for-tidb-configuration#--log-file) param or [filename](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#filename) config to define a folder where to put diagnostic data emitted by [PLAN REPLAYER](https://docs.pingcap.com/tidb/v8.2/sql-plan-replayer#use-plan-replayer-to-save-and-restore-the-on-site-information-of-a-cluster) or `oom_record` from [excessive memory usage](https://docs.pingcap.com/tidb/stable/configure-memory-usage#trigger-the-alarm-of-excessive-memory-usage).

The default value of [filename](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#filename) is empty string `""`, which translates to the working directory. In the container world it translates to the root directory `"/"` unless overridden in the container file. [TiDB Dockerfile](https://github.com/PingCAP-QE/artifacts/blob/8c68fc33a780e2c83b3f69133c17682385753192/dockerfiles/cd/builders/tidb/Dockerfile#L43) explicitly sets it to  the root directory as well.

Note that if [filename](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#filename)  is specified, the tidb-server logs stops going to the system output, which breaks easy log access using `kubectl log` command and breaks standard log export setup for kubernetes clusters.

Please consider to add a command line flag or system variable to specify the directory for the diagnostic data mentioned above.

**Comment by songrijie** [comment]
It makes sense to move the output of `PLAN REPLAYER` to [tmp-storage-path](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#tmp-storage-path), as it's for temporary storage in TiDB. 
For `oom_record`,  we will introduce another location for trace files. We will encourage users to setup permanent volumn for it.

**Comment by mengxian-li** [comment]
Created PR to fix the PLAN REPLAYER output dir: https://github.com/pingcap/tidb/pull/58228
Could you please review?

**Comment by mengxian-li** [comment]
@hawkingrei 
Hi Wenzhe, the PR `fast_test_tiprow` check [failed](https://tiprow.hawkingrei.com/view/gs/pingcapprow/pr-logs/pull/pingcap_tidb/58228/fast_test_tiprow/1868722444152344576) with error message
```
Init container initupload not ready: (state: terminated, reason: "Error", message: "ld-log.txt\",\"file\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs/upload.go:132\",\"func\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs.upload.func1\",\"level\":\"info\",\"msg\":\"Finished upload\",\"severity\":\"info\",\"time\":\"2024-12-16T18:19:58Z\"}\n{\"component\":\"initupload\",\"dest\":\"gs://pingcapprow/pr-logs/pull/pingcap_tidb/58228/fast_test_tiprow/1868722444152344576/clone-log.txt\",\"file\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs/upload.go:132\",\"func\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs.upload.func1\",\"level\":\"info\",\"msg\":\"Finished upload\",\"severity\":\"info\",\"time\":\"2024-12-16T18:19:58Z\"}\n{\"component\":\"initupload\",\"dest\":\"gs://pingcapprow/pr-logs/pull/pingcap_tidb/58228/fast_test_tiprow/1868722444152344576/clone-records.json\",\"file\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs/upload.go:132\",\"func\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs.upload.func1\",\"level\":\"info\",\"msg\":\"Finished upload\",\"severity\":\"info\",\"time\":\"2024-12-16T18:19:58Z\"}\n{\"component\":\"initupload\",\"dest\":\"gs://pingcapprow/pr-logs/pull/pingcap_tidb/58228/fast_test_tiprow/1868722444152344576/started.json\",\"file\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs/upload.go:132\",\"func\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs.upload.func1\",\"level\":\"info\",\"msg\":\"Finished upload\",\"severity\":\"info\",\"time\":\"2024-12-16T18:19:58Z\"}\n{\"component\":\"initupload\",\"dest\":\"gs://pingcapprow/pr-logs/pull/pingcap_tidb/58228/fast_test_tiprow/1868722444152344576/finished.json\",\"file\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs/upload.go:132\",\"func\":\"sigs.k8s.io/prow/pkg/pod-utils/gcs.upload.func1\",\"level\":\"info\",\"msg\":\"Finished upload\",\"severity\":\"info\",\"time\":\"2024-12-16T18:19:58Z\"}\n{\"component\":\"initupload\",\"file\":\"sigs.k8s.io/prow/pkg/gcsupload/run.go:79\",\"func\":\"sigs.k8s.io/prow/pkg/gcsupload.completeUpload\",\"level\":\"info\",\"msg\":\"Finished upload to blob storage\",\"severity\":\"info\",\"time\":\"2024-12-16T18:19:58Z\"}\n{\"component\":\"initupload\",\"error\":\"cloning the appropriate refs failed\",\"file\":\"sigs.k8s.io/prow/cmd/initupload/main.go:45\",\"func\":\"main.main\",\"level\":\"fatal\",\"msg\":\"Failed to initialize job\",\"severity\":\"fatal\",\"time\":\"2024-12-16T18:19:58Z\"}\n") Init container place-entrypoint not ready: (state: waiting, reason: "PodInitializing", message: "")
```
Could you help with that?
