### ISSUE TITLE
dependency conflict

### ISSUE THREAD

**Issue by booming** [pingcap/tidb#5553]
I'm building a gRPC service on TiKV, via your TiKV SDKs implemented in the TiDB project. but I encountered a dependency problem. The gRPC version on TiDB and the one I need to use are not the same. (If I use dep to manage vendor, dep always fails to init.) How can I fix this problem?

**Comment by shenli** [comment]
Please use the same version of gRPC with TiDB. TiDB depends on Etcd. So we have to use the same version of gRPC with Etcd.

**Comment by booming** [comment]
I got your point. but my workmates told me almost the same to use their version of gRPC. So is there a way to let TiDB use gRPC version a and my part use another version?

**Comment by booming** [comment]
Thanks, I'll make a try.

**Comment by disksing** [comment]
Closing it for inactivity. Please feel free to reopen it if need.
