### ISSUE TITLE
cpu usage on memTableReader should be optimized

### ISSUE THREAD

**Issue by dbsid** [pingcap/tidb#55603]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

enable small table cache by `alter table t cache;`

### 2. What did you expect to see? (Required)
fast read latency on small table cache

### 3. What did you see instead (Required)
slower performance than no cache
![image](https://github.com/user-attachments/assets/565024f6-24aa-473c-9b52-3f8ceac8f332)

### 4. What is your TiDB version? (Required)

v7.x

**Comment by tiancaiamao** [comment]
closed by https://github.com/pingcap/tidb/pull/55922
