### ISSUE TITLE
Fail to deploy a TiDB Cluster

### ISSUE THREAD

**Issue by javait90** [pingcap/tidb#5561]
wait prometheus up ： Timeout when waiting for search string 200 OK in 192.168.118.131:9090"
服务启动不了 , wait prometheus up 一直卡在这边 ; 整个部署已经耗时3天了，求大神解救

**Comment by shenli** [comment]
@LinuxGit PTAL

**Comment by jomenxiao** [comment]
Can you offer Prometheus's log? @javait90

**Comment by javait90** [comment]
找不到 {{ deploy_dir }}/log/prometheus.log这个文件 , log下都是空的 @jomenxiao

**Comment by jomenxiao** [comment]
All of configuring you defined in `inventory.ini` file
The process of Prometheus is running at  `monitoring_servers`
```
[monitoring_servers]
192.168.0.10
```
The `deploy_dir` you defined in `inventory.ini` file
example
```
deploy_dir = /home/tidb/deploy
```
So Prometheus log file is ` /home/tidb/deploy/log/prometheus.log`

Please login `monitoring_servers` and check Prometheus log file

Could you send the log files to my email?  My address is xiaozhoumin@pingcap.com

**Comment by javait90** [comment]
问题找到了 . 是用户权限问题,  deploy/scripts 下的文件,用户own是root, 不是tidb ; 
导致安装的时候出现waiting 状态.  prometheus 其实没启成功, 这种状况也没log的 . 
现阶段测试我直接chown为tidb ,tidb是root组.  已经成功启动了
