### ISSUE TITLE
result of a sql is not consistent with MySQL in TiDB

### ISSUE THREAD

**Issue by greatwallgoogle** [pingcap/tidb#5568]
mysql 查询记录的位置 TiDB支持这个语句有bug

The result of this sql is not consistent with MySQL,
``` sql
SELECT @rownum:=@rownum+1 AS rownum, table_name.*
FROM (SELECT @rownum:=0) r, table_name
```

**Comment by XuHuaiyu** [comment]
Thanks for your report, can you provide us the error log?
I tried a sql which is similar to yours and did not meet an error.
``` sql
create table t(a int, b int);
select @a := @a+1 as num, t.* from (select @a := 0) r, t;
```

**Comment by greatwallgoogle** [comment]
查询出来的rownum不是递增的

**Comment by greatwallgoogle** [comment]
执行该语句没有问题，但是查询出来的rownum不是递增的

**Comment by XuHuaiyu** [comment]
TiDB uses HashJoin to execute the sql, and we do not promise the result order in HashJoin now.
You may add `order by rownum` to get the expected result.
