### ISSUE TITLE
init stats(lite=false) might cause sync/async stats load not worked as expected

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#55684]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

![img_v3_02e5_c4ef4257-fa68-4eb4-a9f1-f82b88a518eg](https://github.com/user-attachments/assets/f48c32af-4e92-4103-a1ef-386f46cad30d)
If the decoding fails, it will delete the histogram

![image](https://github.com/user-attachments/assets/522c1a5c-5905-476d-8150-a92c1233ae8a)
Then sync load will treat that column as not found and the loading will fail.

master

**Comment by time-and-fate** [comment]
Related:
https://github.com/pingcap/tidb/pull/27033
https://github.com/pingcap/tidb/pull/36709
