### ISSUE TITLE
Support the Vector Index 

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#55693]
## Feature Request
**Is your feature request related to a problem? Please describe:**

This issue plans to support the same processing of vector indexes as ordinary indexes, its specific functions are as follows :
- Support adding and using vector indexes, including adding vector indexes during and after table creation.
- Support dropping and renaming vector indexes.

**Describe the feature you'd like:**

- [x] #55706
- [x] #55694
- [x] #55840
- [x] #56122
  - Support for Rename Vector Index 
- Support for search with Vector Index
    - [x] Update `ANNQueryInfo` in tipb: https://github.com/pingcap/tipb/pull/339
    - [x] #56510
- [x] Cherry-pick to master: https://github.com/pingcap/tidb/pull/56409
- [x] #56428

### Issues
- [x] #56491
- [x] [create table with vector index does not support gbk charset](https://github.com/pingcap/tidb/issues/56549)

**Comment by JaySon-Huang** [comment]
Link to the vector search feature: https://github.com/pingcap/tidb/issues/54245
