### ISSUE TITLE
Type mismatch in slices.SortFunc due to breaking change in golang.org/x/exp/slices

### ISSUE THREAD

**Issue by dt8269** [pingcap/tidb#55733]
### 1. Minimal reproduce step (Required)

- Clone the project and navigate to the file `charset/charset.go`.
- In the `GetSupportedCharsets()` function, the `slices.SortFunc` function is used to sort a slice of `*Charset` by the `Name` field.

### 2. What did you expect to see? (Required)

Expected the code to compile without errors and the sorting functionality using `slices.SortFunc` to work correctly with `Charset` objects.

### 3. What did you see instead? (Required)

The compilation failed with the following error message:
```
charset/charset.go:94:28: type func(i *Charset, j *Charset) int of func(i, j *Charset) int {…} does not match inferred type func(a *Charset, b *Charset) bool for func(a E, b E) bool external/com_github_go_mysql_org_go_mysql/replication/binlogsyncer.go:427
```

This error arises due to a breaking change in `golang.org/x/exp/slices`, where the signature of `slices.SortFunc` was changed from a `less function` (returning a boolean) to a `comparison function` (returning an integer). This change aligns the `exp/slices` package with the `slices` package introduced in Go 1.21.

### 4. Cause of the issue

The root cause of the issue is that the `golang.org/x/exp/slices` package was [updated](https://github.com/golang/exp/commit/302865e7556b4ae5de27248ce625d443ef4ad3ed) to match the Go 1.21 standard library `slices` package. This introduces a breaking change that affects projects using Go 1.19 (which lacks the `slices` package in the standard library) and relying on `golang.org/x/exp/slices`.

### 5. The fix (Suggested)
```
diff --git a/pkg/parser/charset/charset.go b/pkg/parser/charset/charset.go
index 2be7b9c21d..056c54ef9b 100644
--- a/pkg/parser/charset/charset.go
+++ b/pkg/parser/charset/charset.go
@@ -100,8 +100,8 @@ func GetSupportedCharsets() []*Charset {
 	}
 
 	// sort charset by name.
-	slices.SortFunc(charsets, func(i, j *Charset) int {
-		return strings.Compare(i.Name, j.Name)
+	slices.SortFunc(charsets, func(i, j *Charset) bool {
+		return strings.Compare(i.Name, j.Name) < 0
 	})
 	return charsets
 }
```
note: the [golang.org/x/exp](https://github.com/golang/exp) package was created to try experimentations and explicitly states that new versions may break existing code:

> Warning: Packages here are experimental and unreliable. Some may one day be promoted to the main repository or other subrepository, or they may be modified arbitrarily or even disappear altogether.

### 6. What is your TiDB version? (Required)
N/A

**Comment by lance6716** [comment]
> This introduces a breaking change that affects projects using Go 1.19

I prefer we should raise the version to 1.21 or 1.22 

https://github.com/pingcap/tidb/blob/f2856e3521f29f08f6502b1b3bd3857a17e52db4/pkg/parser/go.mod#L1-L3

cc @hawkingrei @xhebox

**Comment by xhebox** [comment]
> I prefer we should raise the version to 1.21 or 1.22

No blocking from my side.
