### ISSUE TITLE
got negative connection count in grafana

### ISSUE THREAD

**Issue by xiongjiwei** [pingcap/tidb#55746]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
<img width="584" alt="image" src="https://github.com/user-attachments/assets/1b919509-faa2-44d5-97de-5fc9838a7f13">

**Comment by YangKeao** [comment]
Which version? I've solved two similar issues :facepalm:.

https://github.com/pingcap/tidb/issues/54545
https://github.com/pingcap/tidb/issues/54545
https://github.com/pingcap/tidb/issues/51889

**Comment by xiongjiwei** [comment]
> Which version? I've solved two similar issues 🤦.
> 
> #54545 #54545 #51889

v8.1.0

**Comment by YangKeao** [comment]
> > Which version? I've solved two similar issues 🤦.
> > #54545 #54545 #51889
> 
> v8.1.0

Could you try with v8.1.1? It seems that https://github.com/pingcap/tidb/issues/54545 https://github.com/pingcap/tidb/issues/54545 are fixed in v8.1.1 🤔 .

I'd mark it as duplicated issue now. If you find that it's not fixed in v8.1.1, feel free to re-open it.
