### ISSUE TITLE
Does tidb support built-in function?

### ISSUE THREAD

**Issue by hanfei19910905** [pingcap/tidb#558]
tidb> select * from tbl_test where instr(name, 'a') != -1;
2015/11/10 15:17:31 session.go:336: [error] Syntax error: select * from tbl_test where instr(name, 'a') != -1;
2015/11/10 15:17:31 session.go:337: [error] Error occurs at line 1 column 35 near "(".
2015/11/10 15:17:31 main.go:231: [error] line 1 column 35 near "("
/root/coding/go/src/github.com/pingcap/tidb/tidb.go:129:
/root/coding/go/src/github.com/pingcap/tidb/session.go:338:
/root/coding/go/src/github.com/pingcap/tidb/driver.go:328:
/root/coding/go/src/github.com/pingcap/tidb/interpreter/main.go:63:

**Comment by siddontang** [comment]
Hi @hanfei19910905  
The string build in functions we have supported are listed here https://github.com/pingcap/tidb/issues/310
You can send us a PR to help us to complete it. 
Thank you :-)

**Comment by hanfei19910905** [comment]
Indeed, I'm pleased to contribute. But I found it's hard to fully understand the structure. Especially the plan made by the optimizer :(. Are there some logs to help understanding?

And I found that explain clause doesn't always show correct result.
I can't find any difference between these two queries according the explaining result

tidb> explain select  * from tbl_test a join tbl_test b on a.id + 1 = b.id;
+-------------------------------------------------+
|                                                 |
+-------------------------------------------------+
| ┌Compute CROSS Cartesian product of           |
| ┌Iterate all rows of table "tbl_test"         |
| └Output field names ["id" "name"]             |
| ┌Iterate all rows of table "tbl_test"         |
| └Output field names ["id" "name"]             |
| └Output field names ["id" "name" "id" "name"] |
| ┌Evaluate a.id, a.name, b.id, b.name,         |
| └Output field names ["id" "name" "id" "name"] |
+-------------------------------------------------+
8 rows in set (0.00 sec)
tidb> explain select  * from tbl_test a join tbl_test b on a.id = b.id;
+-------------------------------------------------+
|                                                 |
+-------------------------------------------------+
| ┌Compute CROSS Cartesian product of           |
| ┌Iterate all rows of table "tbl_test"         |
| └Output field names ["id" "name"]             |
| ┌Iterate all rows of table "tbl_test"         |
| └Output field names ["id" "name"]             |
| └Output field names ["id" "name" "id" "name"] |
| ┌Evaluate a.id, a.name, b.id, b.name,         |
| └Output field names ["id" "name" "id" "name"] |
+-------------------------------------------------+
8 rows in set (0.00 sec)

**Comment by siddontang** [comment]
Hi @hanfei19910905 

We will add some tutorials later.
The query explanation is primitive and simple, later we will improve it.

**Comment by hanfei19910905** [comment]
Hi @siddontang 
why not build a mailing list ?

**Comment by siddontang** [comment]
Em, maybe later. 
@ngaut

**Comment by ngaut** [comment]
Let's finish tutorials first.

**Comment by keithyau** [comment]
agree, no idea where to get start ~
