### ISSUE TITLE
global temporary table count error when query information_schema.tables

### ISSUE THREAD

**Issue by apollodafoni** [pingcap/tidb#55836]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
create global temporary global_temp(id int) on commit delete rows;
select count(*) from information_schema.tables where table_name='global_temp';
drop database test_01;
select count(*) from information_schema.tables where table_name='global_temp';
```

### 2. What did you expect to see? (Required)
after drop database , count(*) must be 0

### 3. What did you see instead (Required)
+----------+
| count(*) |
+----------+
|        1 |
+----------+
### 4. What is your TiDB version? (Required)

Release Version: v8.4.0-alpha
Edition: Community
Git Commit Hash: 2b54db53463e870ce62427c2c6164633bc5fe1c9
Git Branch: heads/refs/tags/v8.4.0-alpha
UTC Build Time: 2024-09-03 11:45:00
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by tiancaiamao** [comment]
duplicated with #55827
