### ISSUE TITLE
`show tables` get wrong result after restart tidb and a snapshot read

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#55835]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. use infoschema v2

```
set @@global.tidb_schema_cache_size = '512MB';
```

2. create table t and drop it, record the timestamp when t is available

```
use test;
create table t (id int);
select now();  ## get  '2024-09-04 09:48:54'
drop table t;
```

3. restart tidb

4. after a snapshot read, `show tables` goes wrong.

```
mysql> show tables;
Empty set (0.00 sec)

mysql> select * from t as of timestamp '2024-09-04 09:48:54';
Empty set (0.00 sec)

mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| t              |
+----------------+
1 row in set (0.00 sec)
```

### 2. What did you expect to see? (Required)

```
mysql> show tables;
Empty set (0.00 sec)

mysql> show full tables;
Empty set (0.00 sec)

mysql> select * from information_schema.tables where table_schema = 't';
Empty set (0.00 sec)
```

### 3. What did you see instead (Required)

```
mysql> show tables;
+----------------+
| Tables_in_test |
+----------------+
| t              |
+----------------+
1 row in set (0.00 sec)

mysql> show full tables;
Empty set (0.00 sec)

mysql> select * from information_schema.tables where table_schema = 't';
Empty set (0.00 sec)
```

### 4. What is your TiDB version? (Required)

master

**Comment by tiancaiamao** [comment]
This issue is similiar to https://github.com/pingcap/tidb/issues/54926

After create and drop table, the infoschema history should be:

```
version 54:  t
version 55:  t = tomb
```

Then reading latest infoschema get the tomb and we know there are no tables.

When we restart tidb, we have no infoschema versions history.

```
no versions
```

After a snapshot read, the snapshot infoschema is inserted:

```
version 54: t
```

Now things go wrong, we do not have a `tomb` of version 55, so we mistakenly read the t.

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
