### ISSUE TITLE
tidb's performance too poor ,that is why the official website has no test report

### ISSUE THREAD

**Issue by jake2009** [pingcap/tidb#5584]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I test tidb's performance on qq cloud,but the performance too poor .

2. What did you expect to see?
official test the performance and publish it .

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 v1.0.3

**Comment by shenli** [comment]
@jake2009 Thanks for your feedback!
We have published the sysbench result in the official document repo. You can find it [here](https://github.com/pingcap/docs/blob/master/benchmark/sysbench.md).

Could you describe your test scenario?

**Comment by shenli** [comment]
@jake2009 Since you have got the official performance report, I will close this issue. Feel free to reopen it if you have more information to feedback!
Thanks!
