### ISSUE TITLE
Some questions about using tidb-binlog tool

### ISSUE THREAD

**Issue by ayzmkk** [pingcap/tidb#5592]
Hi, we want to use tidb-binlog tool to subscribe to TiDB’s incremental data but we still have some questions.
1) Does this tool ensure data ordering? For example, T1 writes to TiServer1, and T2 writes to TiServer2, is it possible for Drain downstream to get T2->T1 which is not ordered? 
2) Will Kafka partition affect ordering? Since kafka only guarantees ordering in one partition.
3) How to ensure data is no loss if pump crashes? 

Please give me some introductions, Thanks.

**Comment by GregoryIan** [comment]
first of all, `drainer` pulls `binlogs` from all `pumps`, then do sort. 

1. yep, drainer would ensure the order
2. don't effect, now one pump writes one partition in kafka and drainer would restore order of binlogs.  In addition, we have algorithm to restore order of binlogs on multiple partitions(one pump writes multiple partitions)
3. pump and drainer has register and unregister mechanism, if pump crashs(offline and don't unregister), drainer would wait it restoration

**Comment by kolbe** [comment]
Hi @ayzmkk it looks like this was answered a little more than a year ago, so I'm going to close it now. If you have any followup questions related to this issue, please feel free to re-open it at any time.
