### ISSUE TITLE
Internal session cannot parse SQLs containing window functions

### ISSUE THREAD

**Issue by kaixu120811** [pingcap/tidb#55981]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

A clean cluster.
Create a binding for an SQL containing window function.
Shutdown and reboot the TiDB

### 2. What did you expect to see? (Required)

The binding is loaded correctly.

### 3. What did you see instead (Required)

No binding is read to TiDB's memory.

### 4. What is your TiDB version? (Required)

Version 6.5.7

**Comment by kaixu120811** [comment]
For someone who will be the owner of this bug fix, please contact Damon to get some information about bug repro.

**Comment by winoros** [comment]
6.1 6.5 7.1 7.5 will have a problem with loading the binding.
8.1 and master is fine with binding. But still doesn't set the `EnableWindowFunction` correctly for some internal session.
