### ISSUE TITLE
MPP (Massively Parallel Processing) support?

### ISSUE THREAD

**Issue by paulm17** [pingcap/tidb#56]
Would really love to see this.  As with mysql and postges, when dealing with very large queries.  It eventually goes down to using 1 core.

Would be awesome to see MPP.  An example of it being used, is CitusDB.  

Having MPP makes it very powerful indeed!  I believe, Aerospike uses it as well.  Although I could be wrong and Postgres 9.5 with Parallel Sequential Scan was going to be available.  But may have slipped.

**Comment by ngaut** [comment]
Thanks for your attention. We will support MPP after we finish "Asynchronous schema changes".

**Comment by no1youknowz** [comment]
:+1: Looking forward to the next builds.  I will keep an eye out for it.

**Comment by zz-jason** [comment]
For now we have TiFlash extension, it's very fast. Hope it would satisfy your workload. I'm going to close this issue now. If you have other performance problems, feel free to ask by opening another github issue.
