### ISSUE TITLE
encounter inconsistent data and index in branch v6.5.11

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#56041]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

It's found in our internal test. https://tcms.pingcap.net/dashboard/executions/plan/7553951

### 2. What did you expect to see? (Required)
Success
### 3. What did you see instead (Required)
Fail.
### 4. What is your TiDB version? (Required)
v6.5.11

**Comment by tangenta** [comment]
Fixed by https://github.com/pingcap/tidb/pull/56092
