### ISSUE TITLE
add index blocked after injection tikv io delay 500ms

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#56056]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench
2、add index for one table
3、injection tikv io delay 500ms

[tidb-0.zip](https://github.com/user-attachments/files/16987506/tidb-0.zip)

### 2. What did you expect to see? (Required)
add index can success

### 3. What did you see instead (Required)
add index blocked after injection tikv io delay 500ms

the status of ddl job is not synced after 1h0m0s (now: 2024-09-12 06:32:52, jobId: 570, job type: add index /* ingest */, state: running)
operatorLogs:
[2024-09-12 05:32:35] ###### start adding index
ALTER TABLE `sbtest1` ADD INDEX `index_test_1726090355629`(`c`)
[2024-09-12 05:32:35] ###### wait for ddl job finish
[2024-09-12 06:32:52] ###### wait for ddl job finish timeout(1h0m0s)
select job_id, db_name, table_name, job_type, create_time, start_time, end_time, state, query from information_schema.ddl_jobs where query = 'ALTER TABLE `sbtest1` ADD INDEX `index_test_1726090355629`(`c`)'
jobId: 570, job type: add index /* ingest */, state: running

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v6.5.11
Edition: Community
Git Commit Hash: 1097ba80c8da0b3c2f0456abd5edcaae532bacf3
Git Branch: HEAD
UTC Build Time: 2024-09-10 17:31:13
GoVersion: go1.19.13
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: unistore
2024-09-12T05:32:27.395+0800

**Comment by CbcWestwolf** [comment]
Can we close this issue if it can not be reproduced? @Lily2025

**Comment by CbcWestwolf** [comment]
Let's close this issue until we reproduce it
