### ISSUE TITLE
PR#56093 may cause 8.8% performance regression in benchmarksql

### ISSUE THREAD

**Issue by owlsome2501** [pingcap/tidb#56103]
### 1. Minimal reproduce step (Required)

1. Deploy a cluster with 3 TiDB and 3 Tikv.
2. Run benchmark benchmarksql (benchmarksql-1k).

### 2. What did you expect to see? (Required)

No performance regression.

### 3. What did you see instead (Required)

#56093 caused QPS regression 8.83% in benchmark benchmarksql (benchmarksql-1k) compared to baseline 60193.12.

| description       | tidb                                                    | tikv                                                 | pd                                               | QPS                   |
| ----------------- | ------------------------------------------------------- | ---------------------------------------------------- | ------------------------------------------------ | ------------------------------------ |
| last success      | pingcap/tidb@a21d9ea447cea626c897acaa982ce63b88eada5e     | tikv/tikv@7c612787d0bfc57a339907ebcb26777dc296fd5f     | tikv/pd@098b802fcda75b5ae0527b0b50b95ba8b31403cf     | 57369.65            |
| first regression  | pingcap/tidb@4c2ca6f341a12dd2030388786ef34893d58004fe | tikv/tikv@7c612787d0bfc57a339907ebcb26777dc296fd5f | tikv/pd@098b802fcda75b5ae0527b0b50b95ba8b31403cf | 54875.54        |

### 4. What is your TiDB version? (Required)

pingcap/tidb@4c2ca6f341a12dd2030388786ef34893d58004fe

**Comment by MyonKeminta** [comment]
The PR #56093 introduces https://github.com/tikv/pd/pull/8483 to TiDB.

It's reasonable that this PR does have risk to introduce performance regression in non-current mode (which would be default after finishing https://github.com/tikv/pd/issues/8432). However:

* After I rerun the failed bisect task twice, both of these reruns failed to reproduce the regression.
* According to the previously done microbench (mentioned https://github.com/tikv/pd/pull/8483#issuecomment-2345496796), the additional overhead introduced by that PR should not be that much.

So I think this report looks quite doubtful.

But anyway, I prepared this PR as a fix to this problem: https://github.com/tikv/pd/pull/8636

**Comment by MyonKeminta** [comment]
Failed to reproduce the regression after 4 retries in total. Regard this as a misreport for now.
