### ISSUE TITLE
Encounter unsupported expression in tidb randgen test

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tidb#56214]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

tcms: https://tcms.pingcap.net/dashboard/executions/plan/7555023

[agg_sub_data.txt](https://github.com/user-attachments/files/17092304/agg_sub_data.txt)

mysql> source agg_sub_data.txt

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

tidb raises `unsupported expression` error

### 4. What is your TiDB version? (Required)

nightly: 1acbbec8b5a376

**Comment by windtalker** [comment]
Root cause is in HashJoinV2, it does not handle `CorrelatedColumn` in `collectColumnIndexFromExpr`
