### ISSUE TITLE
Can't find column with constant expression

### ISSUE THREAD

**Issue by hawkingrei** [pingcap/tidb#56218]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```
SELECT 

            (SELECT 
                    100.00 
                FROM
                    (SELECT 
                    '2024-09-15' AS DATE ) newTb
                WHERE
                    T0.DATE = DATE_ADD(newTb.DATE, INTERVAL 1 MONTH)) AS 'PROFIT'
    FROM
        (SELECT 
        '2024-09-15' AS DATE
        ) T0
    GROUP BY T0.DATE 
     WITH ROLLUP
    ;
```

### 2. What did you expect to see? (Required)
```
+--------+
| PROFIT |
+--------+
| <null> |
| <null> |
+--------+
```
### 3. What did you see instead (Required)

```
(1105, "Can't find column Column#3 in schema Column: [] Unique key: []")
```
### 4. What is your TiDB version? (Required)

+-----------------------------------------------------------+
| tidb_version()                                            |
+-----------------------------------------------------------+
| Release Version: v8.4.0-alpha-187-g3ae6470ea7             |
| Edition: Community                                        |
| Git Commit Hash: 3ae6470ea785c371b91d28fd5656d48af3f45b94 |
| Git Branch: HEAD                                          |
| UTC Build Time: 2024-09-18 02:31:43                       |
| GoVersion: go1.21.10                                      |
| Race Enabled: false                                       |
| Check Table Before Drop: false                            |
| Store: tikv                                               |
+-----------------------------------------------------------+

**Comment by hawkingrei** [comment]
if we continue to simple the SQL like this.

```
 SELECT  (SELECT 100.00 FROM (SELECT '2024-09-15' AS DATE ) newTb ) AS 'PROFIT'     FROM         (SELECT         '2024-09-15' AS DATE         ) T0     GROUP BY T0.DATE      WITH ROLLUP     ;
```

In TiDB
```
(1815, "Internal : Can't find a proper physical plan for this query")
```

In MySQL

```
+--------+
| PROFIT |
+--------+
| 100.00 |
| 100.00 |
+--------+
```

**Comment by hawkingrei** [comment]
This is normal.

```
SELECT  (SELECT 100.00 FROM (SELECT '2024-09-15' AS DATE ) newTb ) AS 'PROFIT'     FROM         (SELECT         '2024-09-15' AS DATE         ) T0 GROUP BY T0.DATE
```

**Comment by hawkingrei** [comment]
> if we continue to simple the SQL like this.
> 
> ```
>  SELECT  (SELECT 100.00 FROM (SELECT '2024-09-15' AS DATE ) newTb ) AS 'PROFIT'     FROM         (SELECT         '2024-09-15' AS DATE         ) T0     GROUP BY T0.DATE      WITH ROLLUP     ;
> ```
> 
> In TiDB
> 
> ```
> (1815, "Internal : Can't find a proper physical plan for this query")
> ```
> 
> In MySQL
> 
> ```
> +--------+
> | PROFIT |
> +--------+
> | 100.00 |
> | 100.00 |
> +--------+
> ```

it has been fixed by https://github.com/pingcap/tidb/pull/54536

**Comment by AilinKid** [comment]
the original issue:
