### ISSUE TITLE
unsigned int primary key lookup fail

### ISSUE THREAD

**Issue by Darren** [pingcap/tidb#5625]
This is a regression brought by commit 4136b81c23b7a53564d72a896828138381996fe6

1. What did you do?

```sql
drop table t1;
create table t1 (i int unsigned, primary key(i));
insert into t1 values (1),(2),(3);
select * from t1 where i not in(1);
```

2. What did you expect to see?

```
+---+
| i |
+---+
| 2 |
| 3 |
+---+
```

3. What did you see instead?

Empty set 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.1.0-alpha-418-g31b606d3
Git Commit Hash: 31b606d30dcaccd4a571e3bcc459fa2e3a63623e
Git Branch: master
UTC Build Time: 2018-01-12 05:05:57

@winoros PTAL

**Comment by winoros** [comment]
This is a known issue, i'm working on it.
Currently, point query or range query that in [0, MAXINT64] can work properly.

**Comment by winoros** [comment]
@Darren Hello, now you can try the latest the master.

**Comment by Darren** [comment]
@winoros 
fixed! Great work
