### ISSUE TITLE
v5.3.4 tidb/tikv arm64 docker images are not functioning properly.

### ISSUE THREAD

**Issue by cangming** [pingcap/tidb#56281]
### 1. Minimal reproduce step (Required)
Deploying TiDB tag v5.3.4 using the TiDB Operator on an arm64 Kubernetes platform.
No arm64 v5.3.4 tag found in dockerhub repo pingcap/pd-arm64, pingcap/tidb-arm64, and pingcap/tikv-arm64, so I use image in pingcap/pd, pingcap/tidb, and pingcap/tikv

### 2. What did you expect to see? (Required)
tidb/tikv can start up normally.

### 3. What did you see instead (Required)
tidb/tikv stuck and just show log waiting for the verification of PD endpoints.

### 4. What is your TiDB version? (Required)
| Release Version: v5.3.4
Edition: Community
Git Commit Hash: 5ccc10beb8b45936d7f096b1848db51d4afc012c
Git Branch: heads/refs/tags/v5.3.4
UTC Build Time: 2022-11-15 09:01:10
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false |

### Additional information
After testing, it was found that the TiDB/TiKV images did not include wget and the necessary library libpsl.so.5.3.1, which caused startup errors. After adding wget and lib, the functionality worked properly.

**Comment by lance6716** [comment]
ptal @purelind @wuhuizuo

**Comment by jebter** [comment]
For ARM environment, please use version 6.5 or above.
