### ISSUE TITLE
`br debug decode` is useless when the backupmeta file got split.

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#56296]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Generate a full backup locally `br backup full -s '/tmp/testbr`
2. Decode the backupmeta file `br debug decode -s '/tmp/testbr`

### 2. What did you expect to see? (Required)

The entire content of the backupmeta can be readable in JSON

### 3. What did you see instead (Required)

We can only see the main `backupmeta.json` is referring to the split-off files:

```json
{
  "ddls": [],
  "cluster_id": 7418281098110393269,
  "cluster_version": "8.1.0",
  "br_version": "«snip»",
  "version": 1,
  "file_index": {
    "meta_files": [
      {
        "name": "backupmeta.datafile.000000001",
        "sha256": "2XIqo5osORmCTs0fWf0T59xYI98i6nZ/5IdqYwNQmF0=",
        "size": 4623
      }
    ]
  },
  "end_version": 452789007127937031,
  "schema_index": {
    "meta_files": [
      {
        "name": "backupmeta.schema.000000002",
        "sha256": "p2CbZh4isJ7lRdFWDoa/rQEYsV+0jr/v2KzX0JT2GeE=",
        "size": 290142
      }
    ]
  },
  "new_collations_enabled": "True",
  "backup_size": 401424
}
```

and the split-off files are *not* decoded into JSON:

```console
$ ls -aF1 /tmp/testbr
./
../
1/
backup.lock
backupmeta
backupmeta.datafile.000000001
backupmeta.json
backupmeta.schema.000000002
checkpoints/
```

### 4. What is your TiDB version? (Required)

checked on v8.1.0, master.

**Comment by BornChanger** [comment]
i think this behavior change is a consequence of backup metadata v2 from 7.6 and above. cc @Leavrth
