### ISSUE TITLE
Will the modification of the table structure cause a lock table

### ISSUE THREAD

**Issue by lvgithub** [pingcap/tidb#5630]
Will the modification of the table structure cause a lock table

1. What did you do?
a. I want to add two fields to the table。
b .this table have 30 million rows data。
c. support online DDL?

2. What did you expect to see?
I want to modify the structure of the table Online，but I'm afraid of interrupting service.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by shenli** [comment]
@lvgithub TiDB supports Online-DDL. No DDL will block DML. But we do not support all the DDL operation of MySQL. Please refer to the documents:
https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md#ddl
