### ISSUE TITLE
BR-restore should still perform checksum even when the schema checksum is missing

### ISSUE THREAD

**Issue by kennytm** [pingcap/tidb#56373]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Perform `br backup full --checksum=0`
2. Perform `br restore full --checksum=1`

### 2. What did you expect to see? (Required)

BR restore compare the `ADMIN CHECKSUM` with the sum of crc64xor of all files, which are always computed in `br backup` regardless of original `--checksum`.

### 3. What did you see instead (Required)

BR restore does not compare the checksum because it used the Schema's crc64xor which are not populated without `--checksum=1`.

### 4. What is your TiDB version? (Required)

v6.5 and above

**Comment by kennytm** [comment]
Split off from https://github.com/pingcap/tidb/issues/43007#issuecomment-2373481127.

Since that the table schema's crc64xor is just the sum of the table's data files, the schema checksum is redundant. BR restore could simply rely on the total of the file crc64xor. I suggest

1. Create a `br debug` command to populate the table schemas' crc64xor fields, so the backupmeta can be used with `br restore full --checksum=1` without upgrading BR (which has to match the target cluster version)
2. Adjust BR restore to operate on the sum of file crc64xor, so `--checksum=1` always works. If the schema crc64xor exists, do an additional check to ensure the two are equivalent.

**Comment by Tristan1900** [comment]
After this fixing this issue I feel like we need to adjust the semantics of the `--checksum` flag or maybe hide it, looks like when it enabled the only extra work it does is to compare the checksum of files from BR side to the original one in cop tikv, which is not recommended anymore per team's previous discussion.
