### ISSUE TITLE
upgrade/start master two-or-more tidbs tidb cluster got stuck

### ISSUE THREAD

**Issue by AkiraXie** [pingcap/tidb#56391]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1. start a master cluster with 3 tidbs 
2. or upgrade cluster  3 tidbs to master

### 2. What did you expect to see? (Required)
no error
### 3. What did you see instead (Required)
1.  new cluster would only bootstrap 1 tidb

![image](https://github.com/user-attachments/assets/8896de6b-c180-4fee-a440-6f51216a09bb)

2. upgrade would block by tidb
![image](https://github.com/user-attachments/assets/e453db38-6e1d-42f8-8b43-68b480e0eeb2)

### 4. What is your TiDB version? (Required)
master

**Comment by AkiraXie** [comment]
may dulicate with #56375

**Comment by wjhuang2016** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/56375
