### ISSUE TITLE
UTC_TIMESTAMP(7) gives different error code and message from MySQL

### ISSUE THREAD

**Issue by mjonss** [pingcap/tidb#56451]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
SELECT UTC_TIMESTAMP(7);
```

### 2. What did you expect to see? (Required)
MySQL 8.0.32:
```sql
mysql> SELECT UTC_TIMESTAMP(7);
ERROR 1426 (42000): Too-big precision 7 specified for 'utc_timestamp'. Maximum is 6.
```
### 3. What did you see instead (Required)
TiDB:
```sql
tidb> SELECT UTC_TIMESTAMP(7);
ERROR 1105 (HY000): Too-big precision 7 specified for 'curtime'. Maximum is 6
```
Which means that:
- error code is different
- sqlstate is different
- function name is not correct.
### 4. What is your TiDB version? (Required)

```
tidb_version(): Release Version: v8.3.0
Edition: Community
Git Commit Hash: 1a0c3ac3292fff7742faa0c00a662ccb66ba40db
Git Branch: HEAD
UTC Build Time: 2024-08-20 10:23:00
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```

**Comment by chagelo** [comment]
Hello, I made some fix, there are some my questions.
1. Are there any formats for naming a PR？
2. What should I do before push the change to the repo? (like make ut to test, but it seems to hanging)

**Comment by mjonss** [comment]
> Hello, I made some fix, there are some my questions.
> 
> 1. Are there any formats for naming a PR？
> 2. What should I do before push the change to the repo? (like run `make ut` to test, but it seems to hanging)

Hi @chagelo and thank you for contributing!

The format should be "<subsystem or *>: What changed", where subsystem is normally what comes after the pkg directory, see more in:
https://github.com/pingcap/community/blob/master/contributors/commit-message-pr-style.md
or just see other PRs or `git log` for inspiration.

`make ut` will run all unit tests as well as `make ; cd tests/integrationtest ; ./run-tests.sh -s ../../bin/tidb-server` which will run the integration tests.
If you added a unit test or changed any import, then `make bazel_prepare` which will update the BUILD.bazel files if needed.
But the CI will run all of them after you create the PR. 

There might be some good tips in the following links as well:
https://pingcap.github.io/tidb-dev-guide/index.html
https://github.com/pingcap/community/blob/master/contributors/README.md
