### ISSUE TITLE
Fail to execute query in tidb but succeeded in MySQL

### ISSUE THREAD

**Issue by Nickelth** [pingcap/tidb#56464]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
CREATE TABLE `t43` (`a` char(5) CHARACTER SET latin1);

INSERT INTO `t43` VALUES (x'f6');

SELECT t43.a FROM  t43 WHERE (('uWHghV')REGEXP(t43.a));
```

### 2. What did you expect to see? (Required)

Query executed successfully.

### 3. What did you see instead (Required)

```sql
mysql> SELECT t43.a FROM  t43 WHERE (('uWHghV')REGEXP(t43.a));
ERROR 1105 (HY000): invalid input value: FromUtf8Error { bytes: [246], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }
```

### 4. What is your TiDB version? (Required)
```sql
Release Version: v8.4.0-alpha-325-g74034d4ac2
Edition: Community
Git Commit Hash: 74034d4ac243b3c14dbf5f8a9edb92e740da4212
Git Branch: master
UTC Build Time: 2024-10-06 19:04:12
GoVersion: go1.22.5
Race Enabled: false
Check Table Before Drop: false
Store: tikv 
```

**Comment by Defined2014** [comment]
It's expected, in TiDB we think `latin1` is a subset for `utf8`, so we didn't use `cast` function. See https://docs.pingcap.com/tidb/stable/character-set-and-collation#character-sets-and-collations-supported-by-tidb to get details.
