### ISSUE TITLE
[FATAL] [lib.rs:478] ["range end index 4 out of range for slice of length 3"]

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#56494]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1 (c1 bit(24));
INSERT IGNORE t1 (c1) VALUES (b'100011111100001110010100001000000101000011011100000011010001110');
SELECT c1 FROM t1 WHERE FALSE NOT LIKE CONVERT(c1, CHAR);
```
### 2. What did you expect to see? (Required)
Execute without crash
### 3. What did you see instead (Required)
Crash down the server
### 4. What is your TiDB version? (Required)

Release Version: v8.3.0
Edition: Community
Git Commit Hash: 1a0c3ac3292fff7742faa0c00a662ccb66ba40db
Git Branch: HEAD
UTC Build Time: 2024-08-20 10:13:01
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by windtalker** [comment]
The root cause is the collation of `like` function is derived to be `utf8mb4_general_ci`, which is not expected. Since the collation of cast(bit as char) should be binary, and the collation of `like` should be binary.

**Comment by lcwangchao** [comment]
> The root cause is the collation of `like` function is derived to be `utf8mb4_general_ci`, which is not expected. Since the collation of cast(bit as char) should be binary, and the collation of `like` should be binary.

I think the collation of `cast(bit as char)` should still be  `utf8mb4_general_ci` wich is the connection collation. However, the cast should return a NULL value if the bit is not a legal utf8 format. That is what I tested in MySQL:

```
mysql> create table t1(a bit(24));
Query OK, 0 rows affected (0.02 sec)

mysql> insert into t1 values(0xffff);
Query OK, 1 row affected (0.01 sec)

mysql> select cast(a as char) from t1;
Field   1:  `cast(a as char)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_general_ci (45)
Length:     96
Max_length: 0
Decimals:   31
Flags:


+-----------------+
| cast(a as char) |
+-----------------+
| NULL            |
+-----------------+
1 row in set, 1 warning (0.01 sec)
```
