### ISSUE TITLE
unexpected "infoschema v1/v2 switch" log

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#56525]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start a new tidb, master version

### 2. What did you expect to see? (Required)

check the log, it should use infoschema v2

### 3. What did you see instead (Required)

found log like "infoschema v1/v2 switch"

### 4. What is your TiDB version? (Required)

master, v8.4.0

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
