### ISSUE TITLE
upgrade from v7.5 to master, @@tidb_schema_cache_size incorrect

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#56544]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

Start a old version tidb cluster:

```
tiup playground v7.6.0 --tiflash 0
```

kill the tidb-server and restart a master tidb-server

### 2. What did you expect to see? (Required)

```
mysql> select @@global.tidb_schema_cache_size;
+---------------------------------+
| @@global.tidb_schema_cache_size |
+---------------------------------+
| 536870912                      |
+---------------------------------+
1 row in set (0.00 sec)

mysql> select * from GLOBAL_VARIABLES where variable_name = 'tidb_schema_cache_size';
Empty set (0.01 sec)
```

This means the global variable @@tidb_schema_cache_size does not exist in tikv.
So the default value 536870912 is used.

Then upgrade an old tidb cluster from v7.5 to master, it will use infoschema v2.

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
