### ISSUE TITLE
use golang built-in functions rather than mathutil

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#56594]
## Enhancement

like we can use `max` rather than

https://github.com/pingcap/tidb/blob/7158ac65ee454d38455cd636b562649b08906e18/pkg/util/mathutil/math.go#L71-L80

**Comment by Anudhyan** [comment]
> /assign @Anudhyan

Please add hacktoberfest label @lance6716

**Comment by Anudhyan** [comment]
Thanks a lot @lance6716

**Comment by Anudhyan** [comment]
@lance6716 when will this be reviewed?

**Comment by lance6716** [comment]
> @lance6716 when will this be reviewed?

I'll take a look at Monday

**Comment by Anudhyan** [comment]
@lance6716  I have updated the code using inbuilt function and it is running without errors. Please check it

**Comment by lance6716** [comment]
@Anudhyan Please read the issue. Use golang built-in functions like https://pkg.go.dev/builtin#max. And delete `mathutil. Max`

**Comment by Anudhyan** [comment]
> @Anudhyan Please read the issue. Use golang built-in functions like https://pkg.go.dev/builtin#max. And delete `mathutil. Max`

Do I need to do the same for this file only? [tidb/pkg/util/mathutil/math.go]

I have used slices replace custom Max Min functions  and removed mathutil.max from line 45 with ^uint64(0). Please guide me if there is any error from my side. I am contributing for the first time!

**Comment by lance6716** [comment]
> Do I need to do the same for this file only? [tidb/pkg/util/mathutil/math.go]

No. Delete `mathutil.Max` and let caller use golang built-in `max`. Also for `min` and other proper functions.

**Comment by Anudhyan** [comment]
@lance6716 I was working on this issue. This is the first time I am working on issue for TiDB. Please reassign it to me

**Comment by VersatileVats** [comment]
@lance6716 are you talking about this change:

`result := math.Max(float64(a), float64(b))`

**Comment by lance6716** [comment]
> @lance6716 are you talking about this change:
> 
> `result := math.Max(float64(a), float64(b))`

I don't know where's the code you refer to. I think the issue is clear and I don't know how to provide more details

**Comment by VersatileVats** [comment]
Okay, thanks for the clarification! So, @Anudhyan you have to delete mathutil.Max and mathutil.Min and replace them with Go's built-in math.Max and math.Min functions throughout the codebase.

**Comment by lance6716** [comment]
> Okay, thanks for the clarification! So, @Anudhyan you have to delete mathutil.Max and mathutil.Min and replace them with Go's built-in math.Max and math.Min functions

The built-in functions are called `max`, `min` rather than `math.Max` and `math.Min`

**Comment by Anudhyan** [comment]
> > Okay, thanks for the clarification! So, @Anudhyan you have to delete mathutil.Max and mathutil.Min and replace them with Go's built-in math.Max and math.Min functions
> 
> The built-in functions are called `max`, `min` rather than `math.Max` and `math.Min`

@lance6716 the built in `max` and `min` are not variadic in nature. So how will I implement it here for variable n set of arguments?

**Comment by lance6716** [comment]
Obviously `max` and `min` ARE variadic in nature. Please learn some basic golang knowledge before you contribute.
