### ISSUE TITLE
memory leak of evicted stmt summary

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#56629]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

The same script with https://github.com/pingcap/tidb/issues/56619

After creating 2M users, change the script to "alter user ..." to update password for 2M users.

### 2. What did you expect to see? (Required)

No memory leak

### 3. What did you see instead (Required)

Take the heap profile after a while:

![image](https://github.com/user-attachments/assets/1c89a2b3-bb63-4490-8d25-5446b94297fe)

And after a long time later:

![image](https://github.com/user-attachments/assets/e7045909-a80e-43e1-8b50-cc9d107cdb77)

As you can see, the statement summary increase dramatically, this indicate a memory leak!

The test script execute 'alter user test%d ...' for 2M times, and the leaked object count is almost 2M:

![image](https://github.com/user-attachments/assets/67f23731-2d6a-48c0-b70a-7e17b44245bf)

### 4. What is your TiDB version? (Required)

master

**Comment by tiancaiamao** [comment]
Introduced by https://github.com/pingcap/tidb/pull/24513

**Comment by crazycs520** [comment]
This is not a memory leak, but it consumes more memory when there are many types of SQL.
