### ISSUE TITLE
How to get the disk usage of a specific table and how to show long-time-run transactions

### ISSUE THREAD

**Issue by congcongDBA** [pingcap/tidb#5662]
目前在使用TiDB过程中，有运维中一些不便之处
1、只能查看整体磁盘占用量，没法查看表占用磁盘空间大小，只能通过查看表region数量来估计占用大小
2、对于长时间执行的没及时提交的事务没有查看方法，类似mysql中show engine innodb status的命令来看看

**Comment by shenli** [comment]
@congcongDBA 
For the first question, we have a tool named [`tidb-ctl`](https://github.com/pingcap/tidb-ctl/blob/master/doc/tidb-ctl_table.md).
We do not have a solution to the second question now. Because the transaction is running on each tidb-server. You need to login to each tidb-server and use `show processlist` to check the queries.

**Comment by shenli** [comment]
We will add a new command to show the running time of each transaction in a tidb-server.

**Comment by kolbe** [comment]
@congcongDBA the ability to consult information_schema.tables to find the size of a table was recently added to TiDB, so you no longer need to use tidb-ctl to do that. Instead, you can execute a query like `select data_length from information_schema.tables where table_schema='myschema' and table_name='mytable'`.

For your second question about long-running transactions, it's important to know that TiDB's architecture means that long-running transactions are not nearly the problem they are in MySQL/InnoDB. In InnoDB, a long-running transaction can prevent UNDO records from being purged, which can cause really serious problems. TiDB uses optimistic locking, which behaves very differently and means you don't have a danger of a long-running transaction taking down the entire instance or cluster.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
