### ISSUE TITLE
[FATAL] [lib.rs:478] ["Rem resulted in NaN: FloatIsNan"]

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#56647]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1 (c1 DOUBLE);
INSERT INTO t1 (c1) VALUES (1.0E307);
SELECT c1 FROM t1 WHERE DEGREES(c1) MOD c1;
```
### 2. What did you expect to see? (Required)
 The server should not crash down.
### 3. What did you see instead (Required)
A fata error is returned.
### 4. What is your TiDB version? (Required)

Release Version: v8.3.0
Edition: Community
Git Commit Hash: 1a0c3ac3292fff7742faa0c00a662ccb66ba40db
Git Branch: HEAD
UTC Build Time: 2024-08-20 10:13:01
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by windtalker** [comment]
I think the issue is similar with https://github.com/pingcap/tidb/issues/56684

**Comment by yibin87** [comment]
Duplicated with https://github.com/pingcap/tidb/issues/56684

**Comment by gengliqi** [comment]
TiKV issue https://github.com/tikv/tikv/issues/17852. Fixed by https://github.com/tikv/tikv/pull/17853
