### ISSUE TITLE
Better Compatibility With Using Navicat for MySQL As TiDB Client

### ISSUE THREAD

**Issue by wsabc01** [pingcap/tidb#5666]
When I execute SQL in Navicat, It always print an error behind my execute result。
 For example：
sql:
````
SELECT * from xxxx
````
I  Find This In tidb.log .Also ,this error would display in  Navicat too.
````
2018/01/17 11:33:00.363 metrics.go:355: [warning] [EXPENSIVE_QUERY] SELECT * from  xxxx
2018/01/17 11:33:00.513 session.go:702: [warning] [29] parse error:
[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '/*100,3), '%') AS `百分比` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= ' at line 1
SELECT STATE AS `状态`, ROUND(SUM(DURATION),7) AS `期间`, CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `百分比` FROM INFORMATION_SCHEMA.PROFILING WHERE QUERY_ID= GROUP BY STATE ORDER BY SEQ

````
My Tidb Version:
````
release v1.0.3
````
My Navicat Version:
````
11.0.10
````

**Comment by XuHuaiyu** [comment]
Thank you for your report.
 @wsabc01 
This sql is auto-built by Navicat,
may be some return meta data in TiDB is not consistent with MySQL,
I'll check it next week.

**Comment by yangwenmai** [comment]
This SQL is incorrect "CONCAT(ROUND(SUM(DURATION)/*100,3), '%') AS `百分比`".

Another:

My Tidb Version:

```sh
tidb> select version();
+--------------------------------------------+
| version()                                  |
+--------------------------------------------+
| 5.7.1-TiDB-v1.1.0-alpha-556-g633d1b8-dirty |
+--------------------------------------------+
1 row in set (0.00 sec)
```

My Navicat Version:

`12.0.22 unregistered`

When I create a query after selected a database, this error would display in tidb console log.

```sh
2018/02/11 11:18:30.313 session.go:789: [warning] [6] parse error:
line 1 column 204 near " BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'test' ORDER BY ROUTINE_SCHEMA" (total length 565)
SELECT DISTINCT ROUTINE_SCHEMA, ROUTINE_NAME, PARAMS.PARAMETER FROM information_schema.ROUTINES LEFT JOIN ( SELECT SPECIFIC_SCHEMA, SPECIFIC_NAME, GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'test' ORDER BY ROUTINE_SCHEMA
2018/02/11 11:18:30.314 conn.go:472: [warning] [6] dispatch error:
id:6, addr:127.0.0.1:61799 status:2, collation:utf8_general_ci, user:root
"SELECT DISTINCT ROUTINE_SCHEMA, ROUTINE_NAME, PARAMS.PARAMETER FROM information_schema.ROUTINES LEFT JOIN ( SELECT SPECIFIC_SCHEMA, SPECIFIC_NAME, GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'test' ORDER BY ROUTINE_SCHEMA"
line 1 column 204 near " BY ORDINAL_POSITION SEPARATOR ', ') PARAMETER, ROUTINE_TYPE FROM information_schema.PARAMETERS GROUP BY SPECIFIC_SCHEMA, SPECIFIC_NAME, ROUTINE_TYPE ) PARAMS ON ROUTINES.ROUTINE_SCHEMA = PARAMS.SPECIFIC_SCHEMA AND ROUTINES.ROUTINE_NAME = PARAMS.SPECIFIC_NAME AND ROUTINES.ROUTINE_TYPE = PARAMS.ROUTINE_TYPE WHERE ROUTINE_SCHEMA = 'test' ORDER BY ROUTINE_SCHEMA" (total length 565)
/Users/maiyang/develop/golang/src/github.com/pingcap/tidb/parser/yy_parser.go:106:
/Users/maiyang/develop/golang/src/github.com/pingcap/tidb/session.go:790:
/Users/maiyang/develop/golang/src/github.com/pingcap/tidb/server/conn.go:842:
```

Then I think this `GROUP_CONCAT` function is not supported.

**Comment by XuHuaiyu** [comment]
yes, @yangwenmai 
It may be caused by the lack of support for the full syntax of GROUP_CONCAT as the following SQL shows,
`GROUP_CONCAT(CONCAT(DATA_TYPE, ' ', PARAMETER_NAME) ORDER BY ORDINAL_POSITION SEPARATOR ', ');`

**Comment by yangwenmai** [comment]
Yes, I found in https://github.com/pingcap/tidb/blob/master/executor/aggregate_test.go#L314.

Those test case is not incomplete.

**Comment by yangwenmai** [comment]
By the way, I highly recommended Sequel Pro, It's opensource software in MacOSX. 
It is better compatibility and more friendly interface and more powerful.

**Comment by yangwenmai** [comment]
@wsabc01 Are you sure the SQL "CONCAT (ROUND (SUM (DURATION) / * 100,3), '%') AS Percentage" come from tidb log?

This SQL can not be executed in MySQL, itself is not a valid SQL.

**Comment by yangwenmai** [comment]
https://dev.mysql.com/doc/refman/5.7/en/group-by-functions.html

```sql
GROUP_CONCAT([DISTINCT] expr [,expr ...]
             [ORDER BY {unsigned_integer | col_name | expr}
                 [ASC | DESC] [,col_name ...]]
             [SEPARATOR str_val])
```

**Comment by XuHuaiyu** [comment]
@yangwenmai 
Navicat in Windows auto-runs this sql.
https://github.com/pingcap/tidb/issues/5055 may be referred.

**Comment by wsabc01** [comment]
@yangwenmai  This sql does not look like a full sql ,it only prints a place which with wrong grammar . It seems  to be created and executed by  navicat when someone uses it to get result from TiDB, but TIDB  does not support.

**Comment by shenli** [comment]
@wsabc01 We will fix it soon.

**Comment by dreamquster** [comment]
@yangwenmai , @XuHuaiyu , In MySQL, I find the navicat send this SQL 
"SELECT STATE AS ``, ROUND(SUM(DURATION),7) AS ``, CONCAT(ROUND(SUM(DURATION)/0.015120*100,3), '%') AS `` FROM INFORMATION_SCHEMA.PROFILING
 WHERE QUERY_ID=3 GROUP BY STATE ORDER BY SEQ".
TiDB had omited the float number(like 0.015120) in comparsion with MySQL. The char sequence like '/*' is the begining of comments.

**Comment by dreamquster** [comment]
TiDB do not support such SQL:
SELECT QUERY_ID, SUM(DURATION) AS SUM_DURATION FROM INFORMATION_SCHEMA.PROFILING GROUP BY QUERY_ID

In MySQL, the result of the above sql is following:
QUERY_ID	SUM_DURATION
1	0.006733
2	0.001662

TiDB returns nothing
QUERY_ID	SUM_DURATION

**Comment by coocood** [comment]
@dreamquster

Good catch!
Thank you for your help!
We should implement profiling table to fix this issue.

**Comment by coocood** [comment]
@wsabc01 @dreamquster 

Would please try the latest master and check if the issue has been fixed?
