### ISSUE TITLE
[FATAL] [lib.rs:478] ["Multiplication resulted in NaN: FloatIsNan"]

### ISSUE THREAD

**Issue by sayJason** [pingcap/tidb#56684]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

```sql
CREATE TABLE t1 (c1 DOUBLE);
INSERT INTO t1 VALUES (1.0E308);
SELECT c1 FROM t1 WHERE RADIANS(c1) * 0;
```
### 2. What did you expect to see? (Required)
Normal execution.
### 3. What did you see instead (Required)
The server crashed.
### 4. What is your TiDB version? (Required)

Release Version: v8.3.0
Edition: Community
Git Commit Hash: 1a0c3ac3292fff7742faa0c00a662ccb66ba40db
Git Branch: HEAD
UTC Build Time: 2024-08-20 10:13:01
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by sayJason** [comment]
I notice that there exist another issue https://github.com/pingcap/tidb/issues/32623, which has the same error message as this one. But I cannot reproduce that issue in the same version that I found this bug.

**Comment by windtalker** [comment]
`RADIANS` in TiKV implements as follow
```
fn radians(arg: &Real) -> Result<Option<Real>> {
    Ok(Real::new(**arg * std::f64::consts::PI / 180_f64).ok())
}
```
Since 1E308 is the max float, I guess 1E308 * * std::f64::consts::PI will overflow and caused the error.

**Comment by gengliqi** [comment]
TiKV issue https://github.com/tikv/tikv/issues/17852. Fixed by https://github.com/tikv/tikv/pull/17853
