### ISSUE TITLE
"Truncated incorrect INTEGER value" Indicates that the select statement is warnings and the delete statement reports an error and fails to execute

### ISSUE THREAD

**Issue by cmz123** [pingcap/tidb#56770]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
CREATE TABLE `toto_operation_record` (
  `operation_key1` varchar(4000) DEFAULT NULL COMMENT '日志关键字1',
) 

<img width="748" alt="image" src="https://github.com/user-attachments/assets/f55a91b1-4483-4a60-8e9a-64fec8a93fd5">
<img width="1510" alt="image" src="https://github.com/user-attachments/assets/36f13639-be83-49bb-ba5c-44eb75e12f4a">
<img width="736" alt="image" src="https://github.com/user-attachments/assets/43ae14b5-0349-46d6-a6c1-9f291b6ab82d">
<img width="1337" alt="image" src="https://github.com/user-attachments/assets/9b75ff00-906a-495c-8594-ac9904164f08">

### 2. What did you expect to see? (Required)
It's either an error or an warning
### 3. What did you see instead (Required)
One is an warning and the other is an error
### 4. What is your TiDB version? (Required)
v7.5.2

**Comment by Defined2014** [comment]
This behavior is consistent with MySQL, so we will not change it.

```
mysql> select * from toto_operation_record where operation_key1 in (358804);
Empty set, 1 warning (0.00 sec)

mysql> delete from toto_operation_record where operation_key1 in (358804);
ERROR 1292 (22007): Truncated incorrect DOUBLE value: '(359762,)'
```
