### ISSUE TITLE
more db pool size is needed for br to create many databases

### ISSUE THREAD

**Issue by Leavrth** [pingcap/tidb#56866]
## Enhancement
Currently, BR only has 16 db pools to create databases, and it takes about more than one hour to create 200K databases. However, if BR uses 100 db pools to create databases, it only takes about half an hour to finish create 200K databases.

https://github.com/pingcap/tidb/blob/c550aae6a125e20c2aaa8d4f11a2f090bc8b2b50/br/pkg/restore/snap_client/client.go#L69

**Comment by princejha95** [comment]
Why we are only thinking till 200K databases ? Would this number can change in future ? If yes, we again have to make similar changes, right ?
