### ISSUE TITLE
SHOW GRANTS FOR CURRENT_USER() does not work

### ISSUE THREAD

**Issue by oceanho** [pingcap/tidb#5691]
Hi.
I'm execute command（by mysql cli）
`SHOW GRANTS FOR CURRENT_USER();`

get the error
`
ERROR 1105 (HY000): line 1 column 28 near "()" (total length 30)
`

tidb version:
`5.7.1-TiDB-v1.1.0-alpha-459-ga2a48b3`

BTW . 
tidb support MySQL Protocol , but not very compatible with MySQL's existing client tools ( `Navicat`， `MySQL-Front`，`mysql workbench`  and so on ) . Less convenient for developers to use it.

**Comment by shenli** [comment]
@oceanho Thanks for your feedback!
You can use `SHOW GRANTS FOR USER_NAME@HOST` for now. We will support this syntax latter. But it will not be a high priority task.
