### ISSUE TITLE
upgrade from 7.5.3 to 8.4.0 failed 

### ISSUE THREAD

**Issue by Lily2025** [pingcap/tidb#56924]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
1、run sysbench read write
2、upgrade from 7.5.3 to 8.4.0
[tidb-0.log](https://github.com/user-attachments/files/17551671/tidb-0.log)
[tidb-1.log](https://github.com/user-attachments/files/17551676/tidb-1.log)

### 2. What did you expect to see? (Required)
upgrade succeed

### 3. What did you see instead (Required)
upgrade blocked due to tidb can not start

### 4. What is your TiDB version? (Required)
./tidb-server -V
 Release Version: v7.5.3
Edition: Community
Git Commit Hash: 70bfd90035cc81e80d78b4f1f76ca4baef8a5756
Git Branch: HEAD
UTC Build Time: 2024-07-31 13:11:26
GoVersion: go1.21.10
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by Benjamin2037** [comment]
same root cause https://github.com/pingcap/tidb/issues/56713

**Comment by tangenta** [comment]
Related to https://github.com/pingcap/tidb/issues/53073
