### ISSUE TITLE
Why connect tidb more and more slowly when app start？

### ISSUE THREAD

**Issue by kylezhang** [pingcap/tidb#5707]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Why connect tidb more and more slowly when app(`nodejs/sequelizejs, sequel Pro`) start, often there will be a timeout, the solution is to acquireConnectionTimeout increase.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

![image](https://user-images.githubusercontent.com/3679798/35311422-684600b6-00f1-11e8-9895-04adda759970.png)

**Comment by shenli** [comment]
@kylezhang Thanks for your feedback! Please try the latest master or release 1.0.7. We just fixed a related issue in the last week.

**Comment by kylezhang** [comment]
@shenli Thanks, `1.0.7` can solve my problem?

**Comment by shenli** [comment]
@kylezhang Please take a look at this PR: https://github.com/pingcap/tidb/pull/5679

**Comment by kolbe** [comment]
Hi @kylezhang, did you have a chance to re-test this scenario after upgrading? Did you see any improvement in performance?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
