### ISSUE TITLE
Use terror instead of errors

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#572]
- [x] meta
- [ ] store
- [x] privilege
- [x] ddl
- [x] kv
- [x] structure
- [ ] optimizer
- [x] infoschema
- [x] table
- [x] tidb-server
- [x] domain
- [ ] util
- [ ] mysql
- [x] inspectkv
- [x] perfschema

**Comment by ngaut** [comment]
@zimulala Ping
