### ISSUE TITLE
Add min-required version for TiKV and PD

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#5729]
We need to add the min-required version of TiKV and PD. So it is easy to tell that a specific tidb-server could be compatible with a specific tikv-server and pd-server.
In the first step, we could use the `tidb_version()` function or `tidb-server -V` to get the min version info.

**Comment by siddontang** [comment]
@BusyJay @disksing 

We should unify the version format. E.g, for master, like TiKV does `version = "1.1.0-dev"`

**Comment by nullnotnil** [comment]
I believe this has been added (it can be seen in the output of `tidb_version()`).

I am going to close this issue now, but please feel free to re-open if in error. Thanks!
