### ISSUE TITLE
Is there any way to change a non-partitioned table using nonclustered index to a partitioned table, if this table is partitioned by non-primary key?

### ISSUE THREAD

**Issue by Nickelth** [pingcap/tidb#57302]
## Feature Request

I tried to change a non-partitioned table using nonclustered index to a partitioned table, like:

```sql
create table t0(c0 int primary key nonclustered, c1 int);
alter table t0 partition by hash(c1) partitions 2;
```
But it reports:
```sql
ERROR 8264 (HY000): Global Index is needed for index 'PRIMARY', since the unique index is not including all partitioning columns, and GLOBAL is not given as IndexOption
```
The error message said I need to create global index first, but global index can only be created on partitioned table.

**Comment by Defined2014** [comment]
Could use SQL below to do this.
```
alter table t0 partition by hash(c1) partitions 2 update indexes (`primary` global);
```

**Comment by Nickelth** [comment]
> Could use SQL below to do this.
> 
> ```
> alter table t0 partition by hash(c1) partitions 2 update indexes (`primary` global);
> ```
> 
> A ref doc link for it. [pingcap/docs#18543](https://github.com/pingcap/docs/pull/18543)

Thank you!
