### ISSUE TITLE
release:v7.5.5

### ISSUE THREAD

**Issue by EmmaDuDu** [pingcap/tidb#57442]
**Disclaimer**
The dates published in this issue are for planning purposes only. It is intended solely to help you plan your projects. A date that exists in the future should not be considered a firm release date as the release and timing of releases are subject to change at any time and are at PingCAP's sole discretion.

**Candidate SHA:**
TiDB: https://github.com/pingcap/tidb/commit/287f27ea0e5b7be6d75bd4c6fc9982f9d80e4cf7
TiKV: 7a8c4c7c003b7d658075172cdc09622c922eb60d
PD: 17f3ae3609fc50bae07e8783c0a373419b7daf9b
TiFlash: 3cad810ee920091cabccc706e74e4c2a55bed954
binlog: b5468bb20f95eded4ece7d0932daaf6f9e960bfc
tidb-tools: 5452cde00e818ccc3a16feb576187d7323f423c4
tiflow: 2ffc0f3c51d8559d24e659fbf73419a9b84a1ec8
ng-monitoring: 3a16c111d941bb66831c4309a05d339b2424ea5e
enterprise-plugin: 8be043bea8690532cbd6949fae8ee1539e375d29
tidb-dashboard: 834dbcafa2912ad8465fbfc5c4357120b88aab8d
monitoring: e29000d91c87c829905a385ea3fe984776fc8724

Working Tags: v7.5.5

**Check the diff in the current version:**
See the difference from the commit perspective:
TBD

**Release process checklist**

- [x] 0. Announce the release plan.
 
- [x] 1. Code freeze and RC build: Dec. 13, 2024

- [x] 2. Qualifying the release.

- [x] 3. Docs preparing for release.

- [x] 4. The release qualified.

- [x] 5. Docs are ready for release.

**Release date: Dec. 2024**

Do not proceed below until the release date.

- [x] 6. Publish TiDB Release

> - [x] fill in Candidate SHA above
> 
> - [x] fill in the release tag

- [x] 7. Update docs

- [x] 8. Update the official website

**Comment by wuhuizuo** [comment]
## Candidate SHAs

- TiDB: 287f27ea0e5b7be6d75bd4c6fc9982f9d80e4cf7
- TiKV: 7a8c4c7c003b7d658075172cdc09622c922eb60d
- PD: 17f3ae3609fc50bae07e8783c0a373419b7daf9b
- TiFlash: 3cad810ee920091cabccc706e74e4c2a55bed954
- binlog: b5468bb20f95eded4ece7d0932daaf6f9e960bfc
- tidb-tools: 5452cde00e818ccc3a16feb576187d7323f423c4
- tiflow: 2ffc0f3c51d8559d24e659fbf73419a9b84a1ec8
- ng-monitoring: 3a16c111d941bb66831c4309a05d339b2424ea5e
- enterprise-plugin: 8be043bea8690532cbd6949fae8ee1539e375d29
- tidb-dashboard: e29000d91c87c829905a385ea3fe984776fc8724
- monitoring: b5468bb20f95eded4ece7d0932daaf6f9e960bfc

## Working Tags

v7.5.5
