### ISSUE TITLE
lightning's internal table does not have PK so can't work with sql_require_primary_key=ON

### ISSUE THREAD

**Issue by lance6716** [pingcap/tidb#57479]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

turn on `sql_require_primary_key` and run lightning

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

lightning will create some internal tables, and failed with error `Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting.` This is because these tables have no PK

### 4. What is your TiDB version? (Required)

all version

**Comment by D3Hunter** [comment]
does DM have this issue?

**Comment by lance6716** [comment]
> does DM have this issue?

Yes we should also upgrade lightning dependency for DM

**Comment by D3Hunter** [comment]
I mean does any DM's internal table has no PK?

**Comment by lance6716** [comment]
forget to change the VIEW name, reopen.

**Comment by lance6716** [comment]
seems no need to change VIEW name, because we use CREATE OR REPLACE VIEW
