### ISSUE TITLE
Improve auto-analyze manageability - allow/disallow to run auto analyze on specific nodes

### ISSUE THREAD

**Issue by andreifedorov-bolt** [pingcap/tidb#57520]
Currently, when the auto-analyze process is triggered, there is no way to control which TiDB node it runs on, so it will run on a random node in the cluster. 

In more advanced environments, it's often desirable to separate background processes from the live traffic. 
Another use case is that auto-analyze sometimes has high memory demand, so it's preferable to keep one or just a few larger nodes for this purpose instead of scaling up all the TiDB nodes in the cluster.
There could be some small nodes in the cluster for management purposes, many analyze processes that run normally on 'live' nodes will fail due to low RAM on those - so would be nice to be able to avoid this situation.

An example could be tidb_enable_ddl option: https://docs.pingcap.com/tidb/stable/system-variables#tidb_enable_ddl-new-in-v630

**Comment by hawkingrei** [comment]
We have implement this feature. it has a system variable called [tidb_enable_stats_owner](https://docs.pingcap.com/tidb/dev/system-variables#tidb_enable_stats_owner-new-in-v840) and a config parameter called [tidb_enable_stats_owner](https://docs.pingcap.com/tidb/dev/tidb-configuration-file#tidb_enable_stats_owner-new-in-v840)

**Comment by hawkingrei** [comment]
@andreifedorov-bolt What version of tidb are you currently using?
