### ISSUE TITLE
TiDB crash caused by OOM

### ISSUE THREAD

**Issue by yixinGod** [pingcap/tidb#5756]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
this server(deploy pd/tidb-server) and dmesg stdout error：
[677407.991463] Out of memory: Kill process 1635 (tidb-server) score 985 or sacrifice child
[677407.992115] Killed process 1635 (tidb-server) total-vm:64842052kB, anon-rss:64713488kB, file-rss:0kB, shmem-rss:0kB

2. What did you expect to see?
tidb出错

3. What did you see instead?
正常运行

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?tidb：1.0.6

**Comment by tiancaiamao** [comment]
Is your SQL statement `select xxx order by xxx limit xxx`?
v1.0.6 has some known leak problem on this kind of query, and it have been fixed in master and  release-1.0 branch, you can have a try. @yixinGod

**Comment by yixinGod** [comment]
tikv produce this error :
2018/01/31 13:37:07.951 kv.rs:784: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))

we just insert data into tidb using mysqldump

**Comment by shenli** [comment]
@yixinGod The error `Failed to send Raft Message due to full` means that TiKV is under heavy write workload. Could you provide the hardware info and deployment topology of the TiDB Cluster?
/cc @siddontang

**Comment by shenli** [comment]
@yixinGod What is the SQL statement you are running when tidb-server meet OOM?
If this is a cluster for testing, you can try the latest master.

**Comment by yixinGod** [comment]
cluster is that:

172.16.36.125  tidb-pd01  tidb01
172.16.36.126  tidb-pd02  tidb02
172.16.36.127  tidb-pd03  grafana+pro
172.16.36.128  tidb-tikv01
172.16.36.129  tidb-tikv02
172.16.36.130  tidb-tikv03

实例规格：16核 64GB（本地SSD型 i1，ecs.i1.4xlarge）
两块盘 400多g,lvm 一起800多g,挂在在一个目录

**Comment by shenli** [comment]
May I have the access to your Grafana?

**Comment by tiancaiamao** [comment]
And what's the mysqldump command line arguments?  @yixinGod

**Comment by yixinGod** [comment]
mysqldump -hrr-bp1m774t1m9v19h8o.mysql.rds.aliyuncs.com --default-character-set=utf8 -u**** -p**** his_calm_online trade_item -t  --where='id>1100000000' --replace --skip-lock-tables|mysql --default-character-set=utf8 -h172.16.36.125 -P4000 -utidb -ptidb ods
data counts: 300000000+

**Comment by yixinGod** [comment]
our company access to Grafana needing vpn

**Comment by tiancaiamao** [comment]
Could you provide the TiDB log? you can send it to my email mkl@pingcap.com
If Grafana is not available to us, could you capture the picture of the memory monitor information

**Comment by yixinGod** [comment]
I have sending ,thanks

**Comment by shenli** [comment]
@yixinGod Thanks! 
@tiancaiamao  Any update?

**Comment by tiancaiamao** [comment]
I need some detail information to digest this issue. @shenli 
log of TiKV and grafana screenshot from PD is not helpful. 
Could you send me something about TiDB? @yixinGod 

![unnamed](https://user-images.githubusercontent.com/1420062/36238765-53c0afc6-11ca-11e8-8954-b7b26769d699.png)

![unnamed 1](https://user-images.githubusercontent.com/1420062/36238810-9ba3d836-11ca-11e8-8e9a-b7d2473747ef.png)
