### ISSUE TITLE
TiDCD CI failed after PR 57393

### ISSUE THREAD

**Issue by joechenrh** [pingcap/tidb#57646]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 2. What did you expect to see? (Required)

CI Pass.

### 3. What did you see instead (Required)

You can find the error in https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_kafka_test/detail/pull_cdc_integration_kafka_test/3278/pipeline/

**Comment by joechenrh** [comment]
Only affect master

**Comment by lcwangchao** [comment]
caused by #57396
