### ISSUE TITLE
Result wrong for query select TABLE_SCHEMA from information_schema.tables where TIDB_TABLE_ID= xx

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#57657]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

![image](https://github.com/user-attachments/assets/b3142fe2-1b67-4ab5-be5c-e9dd10c0e0d7)

```sql
-- return all schema names
select TABLE_SCHEMA from information_schema.tables where TIDB_TABLE_ID=4611686018427387967; 
```
### 4. What is your TiDB version? (Required)

8.5 master

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/60283
