### ISSUE TITLE
Backup hangs when processing a large number of tables

### ISSUE THREAD

**Issue by 3pointer** [pingcap/tidb#57666]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
similar with https://github.com/pingcap/tidb/issues/53480
but when backup large amount of tables on one store. and if backup slow, some requests might wait for more than one hour, cause the connection reset.

### 2. What did you expect to see? (Required)
backup succeed
### 3. What did you see instead (Required)
backup stuck
### 4. What is your TiDB version? (Required)
master

**Comment by 3pointer** [comment]
close due to https://github.com/pingcap/tidb/pull/55526 merged

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/60283
