### ISSUE TITLE
Dump stats delta updates causes a lot of time when the number of changed tables is large

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#57737]
## Enhancement

Two kinds of SQL are used for the process.
Updating the count and modify_count in table `mysql.stats_meta`.
![Image](https://github.com/user-attachments/assets/61d19eab-3ac9-473a-877e-f6fc580e8092)
Updating the total column size for the changed columns.
![Image](https://github.com/user-attachments/assets/00c4b2f7-220d-4641-be45-ef29b1c76edf)
Both of them are only updating one row per time. Causing that a lot of time wasted.

**Comment by Rustin170506** [comment]
subtask of https://github.com/pingcap/tidb/issues/57869
