### ISSUE TITLE
Same query results are inconsistent on TiKV and TiFlash when using complex predicate

### ISSUE THREAD

**Issue by fenfeng9** [pingcap/tidb#57739]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
prepare data
```sql
drop table if exists t0;
drop table if exists t1;
CREATE TABLE t0(c0 TEXT(495) CHECK (c0) );
CREATE TABLE t1 LIKE t0;
INSERT INTO t0(c0) VALUES ('A');
INSERT INTO t1(c0) VALUES ('B');
ALTER TABLE t0 SET TIFLASH REPLICA 1;
ALTER TABLE t1 SET TIFLASH REPLICA 1;
```
execute query
```sql
SELECT /*+ read_from_storage(tikv[t1]) */  t0.c0, t1.c0 FROM t1, t0 WHERE (~ ((CASE NULL WHEN '704380696' THEN t0.c0 ELSE (~ (t1.c0)) END )));
SELECT /*+ read_from_storage(tiflash[t1]) */  t0.c0, t1.c0 FROM t1, t0 WHERE (~ ((CASE NULL WHEN '704380696' THEN t0.c0 ELSE (~ (t1.c0)) END )));
```

### 2. What did you expect to see? (Required)
The results of the two queries are equal.

### 3. What did you see instead (Required)
Query1 result:
empty

Query2 result:
![Image](https://github.com/user-attachments/assets/e9fb0293-acf6-4d5d-a296-bf70a14e20cf)

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/1a9f0fa25580907d3266dc3edf000ba24379a600
Git Branch: HEAD
UTC Build Time: 2024-11-07 15:18:43
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by yibin87** [comment]
Duplicated with #57731, close it.
