### ISSUE TITLE
Same query results are inconsistent on TiKV and TiFlash when using `DATE_FORMAT`

### ISSUE THREAD

**Issue by fenfeng9** [pingcap/tidb#57733]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
prepare data
```sql
drop table if exists t0;
CREATE TABLE t0(c0 DOUBLE , PRIMARY KEY(c0));
INSERT IGNORE  INTO t0 VALUES (0.7137570398985166);
ALTER TABLE t0 SET TIFLASH REPLICA 1;
```
execute query
```sql
SELECT /*+ read_from_storage(tikv[t0]) */  t0.c0 FROM t0 WHERE DATE_FORMAT(t0.c0, 0.9639405634969745);
SELECT /*+ read_from_storage(tiflash[t0]) */  t0.c0 FROM t0 WHERE DATE_FORMAT(t0.c0, 0.9639405634969745);
```

### 2. What did you expect to see? (Required)
The results of the two queries are equal.

### 3. What did you see instead (Required)
Query1 result:
empty

Query2 result:
![Image](https://github.com/user-attachments/assets/a3cd13b2-1326-48d4-a47a-dbe15d58c97e)

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/1a9f0fa25580907d3266dc3edf000ba24379a600
Git Branch: HEAD
UTC Build Time: 2024-11-07 15:18:43
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by yibin87** [comment]
Duplicated with #52937, close it.
