### ISSUE TITLE
Same query results are inconsistent on TiKV and TiFlash when using ` (~ (BIN(t0.c1)))`.

### ISSUE THREAD

**Issue by fenfeng9** [pingcap/tidb#57736]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
prepare data
```sql
drop table if exists t0;
CREATE TABLE t0(c0 BOOL UNSIGNED , c1 DECIMAL DEFAULT -1042719178 , c2 TEXT(157) );
INSERT INTO t0 VALUES (true, 1888667073, '-808292594');
ALTER TABLE t0 SET TIFLASH REPLICA 1;
```

execute query
```sql
SELECT /*+ read_from_storage(tikv[t0]) */  t0.c0 FROM t0 WHERE (~ (BIN(t0.c1)));
SELECT /*+ read_from_storage(tiflash[t0]) */  t0.c0 FROM t0 WHERE (~ (BIN(t0.c1)));
```

### 2. What did you expect to see? (Required)
The results of the two queries are equal.

### 3. What did you see instead (Required)
Query1 result:
empty

Query2 result:
![Image](https://github.com/user-attachments/assets/bbf9e874-aa43-436d-9907-526110fcbae9)

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/1a9f0fa25580907d3266dc3edf000ba24379a600
Git Branch: HEAD
UTC Build Time: 2024-11-07 15:18:43
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by yibin87** [comment]
Duplicated with #57731, close it.
