### ISSUE TITLE
Same query results are inconsistent on TiKV and TiFlash when using complex predicate

### ISSUE THREAD

**Issue by fenfeng9** [pingcap/tidb#57734]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

##### It may require multiple executions of the query to reproduce.
prepare data
```sql
drop table if exists t0;
drop table if exists t1;
CREATE TABLE t0(c0 TINYINT UNSIGNED ZEROFILL , c1 NUMERIC UNSIGNED ZEROFILL  AS ('U') STORED , c2 TEXT(286) )PARTITION BY HASH(c0) PARTITIONS 56;
CREATE TABLE t1(c0 DOUBLE UNSIGNED ZEROFILL );
ALTER TABLE t0 ADD PRIMARY KEY(c0);
ALTER TABLE t0  ORDER BY c2 DESC, c0 DESC;
INSERT INTO t1 VALUES (1.935430493E9);
INSERT IGNORE  INTO t0(c0) VALUES (1291931716);
ALTER TABLE t0 SET TIFLASH REPLICA 1;
ALTER TABLE t1 SET TIFLASH REPLICA 1;
```
execute query
```sql
SELECT /*+ read_from_storage(tikv[t0]) */  * FROM t0, t1 WHERE ((((true)OR(t0.c0)))NOT LIKE(((269385965)AND(t0.c0))));

set @@tidb_enforce_mpp=1;
SELECT /*+ read_from_storage(tiflash[t0]) */  * FROM t0, t1 WHERE ((((true)OR(t0.c0)))NOT LIKE(((269385965)AND(t0.c0))));
```

### 2. What did you expect to see? (Required)
The results of the two queries are equal.

### 3. What did you see instead (Required)
Query1 result:
empty

Query2 result:
![Image](https://github.com/user-attachments/assets/be8308d2-c1cf-4131-98be-6a934d2be372)

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: https://github.com/pingcap/tidb/commit/1a9f0fa25580907d3266dc3edf000ba24379a600
Git Branch: HEAD
UTC Build Time: 2024-11-07 15:18:43
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by yibin87** [comment]
Not reproducible with latest version. Close it.
