### ISSUE TITLE
Get  wrong result while execute query using order by  on tidb v7.1.0

### ISSUE THREAD

**Issue by huangxinying3558** [pingcap/tidb#57745]
### 1. Minimal reproduce step (Required)

1.create a table which primary key is defined as  customizedMenuId  char(40) ;

2. insert some records with primary key (customizedMenuId  ) 's values as below :   1 ,1-1, 1-2, ...,5,,5-1 .....,12,12-1 ,12-2,13

3. using  select statement  to select these records  :  SELECT * FROM `CustomizedMenus`  order by customizedMenuId + 0 ;

### 2. What did you expect to see? (Required)

 records selected as blow:

1 
1-1
1-2
....
5
5-1
5-2
5-3
5-4
...
12
12-1
12-2
13

### 3. What did you see instead (Required)
1
1-1
1-2
....
5-1
5-4
5-3
5-2
5
....
12-2
12-1
12
13

### 4. What is your TiDB version? (Required)

7.1.0

Release Version: v7.1.0
Edition: Community
Git Commit Hash: 635a4362235e8a3c0043542e629532e3c7bb2756
Git Branch: heads/refs/tags/v7.1.0
UTC Build Time: 2023-05-30 10:58:57
GoVersion: go1.20.3
Race Enabled: false
TiKV Min Version: 6.2.0-alpha
Check Table Before Drop: false
Store: tikv

**Comment by Defined2014** [comment]
This is expected behavior. You could run `SELECT customizedMenuId + 0 FROM CustomizedMenus order by customizedMenuId + 0 ;`, and the result will like 
```
mysql> SELECT customizedMenuId + 0 FROM t order by customizedMenuId + 0 ;
+----------------------+
| customizedMenuId + 0 |
+----------------------+
|                    1 |
|                    1 |
|                    1 |
|                    1 |
|                    2 |
|                    2 |
|                    2 |
|                    2 |
|                    3 |
|                    3 |
|                    3 |
|                    3 |
|                    4 |
|                    4 |
|                    4 |
|                    4 |
|                    5 |
|                    5 |
|                    5 |
|                    5 |
|                    6 |
|                    6 |
|                    6 |
|                    6 |
|                    7 |
|                    7 |
|                    7 |
|                    7 |
|                    8 |
|                    8 |
|                    8 |
|                    8 |
|                    9 |
|                    9 |
|                    9 |
|                    9 |
|                   10 |
|                   10 |
|                   10 |
|                   10 |
+----------------------+
40 rows in set, 80 warnings (0.00 sec)
```

As shown above, `customizedMenuId + 0` will truncate string, so the result is expected.
