### ISSUE TITLE
It takes too long time for query tables with tidb_table_id

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#57779]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1.5M databases, 3M tables 
We should optimize the execution time of the follow query
```sql
mysql> select TABLE_SCHEMA from INFORMATION_SCHEMA.tables where tidb_table_id=200461;
+--------------+
| TABLE_SCHEMA |
+--------------+
| sb10wnormal1 |
+--------------+
1 row in set (14 min 21.65 sec)
```

### 4. What is your TiDB version? (Required)

master
Release Version: v8.5.0-alpha-230-gca395fa4be
Edition: Community
Git Commit Hash: ca395fa4be5278acbdec0b15803e26877bee66c0
Git Branch: HEAD
UTC Build Time: 2024-11-27 13:21:51
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/60283
