### ISSUE TITLE
It takes too long time for add index in million tables

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#57783]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

3M tables
Add index for a table with 10k rows takes about 20 minutes
```sql
   JOB_ID: 7504857
     DB_NAME: sbtest29
  TABLE_NAME: sbtest2
    JOB_TYPE: add index
SCHEMA_STATE: public
   SCHEMA_ID: 3324475
    TABLE_ID: 1000158
   ROW_COUNT: 20000
 CREATE_TIME: 2024-11-28 02:28:25.788000
  START_TIME: 2024-11-28 03:13:49.938000
    END_TIME: 2024-11-28 03:33:51.738000
       STATE: synced
    COMMENTS: ingest, DXF
```
### 4. What is your TiDB version? (Required)

Release Version: v8.5.0
Edition: Community
Git Commit Hash: 3da59f7067f3188f33117164572d2fe449c63249
Git Branch: HEAD
UTC Build Time: 2024-11-22 14:46:47
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/60283
