### ISSUE TITLE
Same query results are inconsistent on TiKV and TiFlash when involving `ELT` function and predicate.

### ISSUE THREAD

**Issue by fenfeng9** [pingcap/tidb#57858]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
prepare data
```sql
drop table if exists t0;
CREATE TABLE t0(c0 BOOL UNSIGNED  , c1 CHAR  AS (c2) STORED , c2 NUMERIC UNIQUE );
INSERT INTO t0(c0) VALUES (false), (true), (true);
ALTER TABLE t0 SET TIFLASH REPLICA 1;
```
execute query
```sql
SELECT /*+ read_from_storage(tikv[t0]) */  * FROM t0 WHERE ELT((true)|((t0.c2|t0.c1)OR('/')), '1');
SELECT /*+ read_from_storage(tiflash[t0]) */  * FROM t0 WHERE ELT((true)|((t0.c2|t0.c1)OR('/')), '1');
```

### 2. What did you expect to see? (Required)
The results of the two queries are equal.

### 3. What did you see instead (Required)
Query1: empty
Query2:
![Image](https://github.com/user-attachments/assets/2e27cbbc-5617-4b9e-a0aa-767215a4cb21)

### 4. What is your TiDB version? (Required)

Release Version: v8.4.0
Edition: Community
Git Commit Hash: 1a9f0fa25580907d3266dc3edf000ba24379a600
Git Branch: HEAD
UTC Build Time: 2024-11-07 15:18:43
GoVersion: go1.23.2
Race Enabled: false
Check Table Before Drop: false
Store: tikv

**Comment by fenfeng9** [comment]
May be a duplicate of https://github.com/pingcap/tidb/issues/57852

**Comment by yibin87** [comment]
Duplicate with #57852 , close it
