### ISSUE TITLE
Fail to execute statement when not using expr_pushdown_blacklist

### ISSUE THREAD

**Issue by Nickelth** [pingcap/tidb#57860]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)
```sql
create table `t0` (`a` timestamp);
insert into `t0` values ('1970-07-23 10:04:59'),('2038-01-19 03:14:07');

insert into mysql.expr_pushdown_blacklist values('=', 'tikv', '');
admin reload expr_pushdown_blacklist;
select * from `t0` where date_sub(`a`, interval 10 month)=date_sub('1970-07-23 10:04:59', interval 10 month);
delete from mysql.expr_pushdown_blacklist;
admin reload expr_pushdown_blacklist;
select * from `t0` where date_sub(`a`, interval 10 month)=date_sub('1970-07-23 10:04:59', interval 10 month);

```

### 2. What did you expect to see? (Required)

Statements executed successfully.

### 3. What did you see instead (Required)

```sql
mysql> insert into mysql.expr_pushdown_blacklist values('=', 'tikv', '');
Query OK, 1 row affected (0.01 sec)

mysql> admin reload expr_pushdown_blacklist;
Query OK, 0 rows affected (0.04 sec)

mysql> select * from `t0` where date_sub(`a`, interval 10 month)=date_sub('1970-07-23 10:04:59', interval 10 month);
+---------------------+
| a                   |
+---------------------+
| 1970-07-23 10:04:59 |
+---------------------+
1 row in set (0.00 sec)

mysql> delete from mysql.expr_pushdown_blacklist;
Query OK, 2 rows affected (0.04 sec)

mysql> admin reload expr_pushdown_blacklist;
Query OK, 0 rows affected (0.03 sec)

mysql> select * from `t0` where date_sub(`a`, interval 10 month)=date_sub('1970-07-23 10:04:59', interval 10 month);
ERROR 1105 (HY000): other error: [components/tidb_query_expr/src/lib.rs:857]: ScalarFunction SubDateDatetimeInt is not supported in batch mode
```

### 4. What is your TiDB version? (Required)
```sql
Release Version: v8.5.0-alpha-79-g426ce3e570
Edition: Community
Git Commit Hash: 426ce3e57069afbd8f061d7ae39c79d3f9e2ff5d
Git Branch: master
UTC Build Time: 2024-11-09 12:25:03
GoVersion: go1.23.0
Race Enabled: false
Check Table Before Drop: false
Store: tikv 
```

**Comment by yibin87** [comment]
Not reproducible with latest version:
```
mysql> explain analyze select * from `t0` where date_sub(`a`, interval 10 month)=date_sub('1970-07-23 10:04:59', interval 10 month);
+-------------------------+---------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+-----------+------+
| id                      | estRows | actRows | task      | access object | execution info                                                                                                                                                                                                                                                   | operator info                                                    | memory    | disk |
+-------------------------+---------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+-----------+------+
| TableReader_7           | 1.60    | 1       | root      |               | time:1.05ms, loops:2, RU:0.475822, cop_task: {num: 1, max: 875.5µs, proc_keys: 0, tot_proc: 2.47µs, tot_wait: 204.7µs, copr_cache_hit_ratio: 1.00, build_task_duration: 14.2µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:1, total_time:840.9µs}}      | data:Selection_6                                                 | 257 Bytes | N/A  |
| └─Selection_6           | 1.60    | 1       | cop[tikv] |               | tikv_task:{time:3ms, loops:1}, scan_detail: {get_snapshot_time: 173.9µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 2.47µs, total_wait_time: 204.7µs, tikv_wall_time: 373.8µs}                                                                     | eq(date_sub(test.t0.a, 10, "MONTH"), 1969-09-23 10:04:59.000000) | N/A       | N/A  |
|   └─TableFullScan_5     | 2.00    | 2       | cop[tikv] | table:t0      | tikv_task:{time:0s, loops:1}                                                                                                                                                                                                                                     | keep order:false, stats:pseudo                                   | N/A       | N/A  |
+-------------------------+---------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+-----------+------+
3 rows in set (0.00 sec)
```
Close it now, please feel free to open it if you reproduce it with latest version.

**Comment by Nickelth** [comment]
> Not reproducible with latest version:
> 
> ```
> mysql> explain analyze select * from `t0` where date_sub(`a`, interval 10 month)=date_sub('1970-07-23 10:04:59', interval 10 month);
> +-------------------------+---------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+-----------+------+
> | id                      | estRows | actRows | task      | access object | execution info                                                                                                                                                                                                                                                   | operator info                                                    | memory    | disk |
> +-------------------------+---------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+-----------+------+
> | TableReader_7           | 1.60    | 1       | root      |               | time:1.05ms, loops:2, RU:0.475822, cop_task: {num: 1, max: 875.5µs, proc_keys: 0, tot_proc: 2.47µs, tot_wait: 204.7µs, copr_cache_hit_ratio: 1.00, build_task_duration: 14.2µs, max_distsql_concurrency: 1}, rpc_info:{Cop:{num_rpc:1, total_time:840.9µs}}      | data:Selection_6                                                 | 257 Bytes | N/A  |
> | └─Selection_6           | 1.60    | 1       | cop[tikv] |               | tikv_task:{time:3ms, loops:1}, scan_detail: {get_snapshot_time: 173.9µs, rocksdb: {block: {}}}, time_detail: {total_process_time: 2.47µs, total_wait_time: 204.7µs, tikv_wall_time: 373.8µs}                                                                     | eq(date_sub(test.t0.a, 10, "MONTH"), 1969-09-23 10:04:59.000000) | N/A       | N/A  |
> |   └─TableFullScan_5     | 2.00    | 2       | cop[tikv] | table:t0      | tikv_task:{time:0s, loops:1}                                                                                                                                                                                                                                     | keep order:false, stats:pseudo                                   | N/A       | N/A  |
> +-------------------------+---------+---------+-----------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+-----------+------+
> 3 rows in set (0.00 sec)
> ```
> 
> Close it now, please feel free to open it if you reproduce it with latest version.

I rebuild tidb with latest version and found that I can still reproduce this bug. 
Here is the information of my environment:
TiDB:
```sql
Release Version: v8.5.0-alpha-281-g282430e657
Edition: Community
Git Commit Hash: 282430e657d49bb4bae578f0e0b732ac0df3ba57
Git Branch: master
UTC Build Time: 2024-12-04 09:16:29
GoVersion: go1.23.4
Race Enabled: false
Check Table Before Drop: false
Store: tikv
```
TiKV:
```sql 
Release Version:   8.3.0-alpha
Edition:           Community
Git Commit Hash:   2253c93376ced0a214ab2b56a4b963a1a0522be5
Git Commit Branch: master
UTC Build Time:    2024-08-01 08:23:46
Rust Version:      rustc 1.77.0-nightly (89e2160c4 2023-12-27)
Enable Features:   memory-engine pprof-fp jemalloc mem-profiling portable sse test-engine-kv-rocksdb test-engine-raft-raft-engine trace-async-tasks openssl-vendored
Profile:           release
```
PD
```sql
Release Version: v8.3.0-alpha-8-g45dac53d6-dirty
Edition: Community
Git Commit Hash: 45dac53d65c3903618e6a2a741fbd0bec20e3b44
Git Branch: master
UTC Build Time:  2024-08-29 05:32:14
```
