### ISSUE TITLE
statistics background update in-memory objects worker reads a lot of unneeded items from storage

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#57905]
## Enhancement
From https://github.com/pingcap/tidb/issues/57631#issuecomment-2499607905, we'll see that TiDB reads all the stats_meta whose last_update_version is higher than the given timestamp.
And it's not the end. It will then call `TableStatsFromStorage` for every table_id read from stats_meta and read all the things from `mysql.stats_histogram`, `mysql.stats_top_n` and `mysql.stats_buckets`.
It's a big waste since most of the tables are just updating the row count and modified_count and rare of them will be analyzed.
We need a more accurate control for the background worker to only read the things really needed to update the in-memory stats objects.

**Comment by Rustin170506** [comment]
duplicate of https://github.com/pingcap/tidb/issues/57868
