### ISSUE TITLE
snapshot infoschema should block GC

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#57952]
## Enhancement

Currently, the meta package use old transaction API, unlike normal internal transaction, those APIs can not block the GC safepoint advancing (not updating min start ts).

This may cause "GC life time is shorter than transaction duration" error for InfoSchema V2.

Maybe a possible fix is collect the min start ts of all snapshot infoschemas.

**Comment by lance6716** [comment]
maybe https://github.com/pingcap/tidb/issues/57960 is also related? Maintaining minTS for GC should be designed at a proper layer, without these special handling of infoschema and analyze

**Comment by tiancaiamao** [comment]
> maybe [#57960](https://github.com/pingcap/tidb/issues/57960) is also related? Maintaining minTS for GC should be designed at a proper layer, without these special handling of infoschema and analyze

I'm not sure. We need to check the error stack to confirm it.

**Comment by Rustin170506** [comment]
> maybe [#57960](https://github.com/pingcap/tidb/issues/57960) is also related? Maintaining minTS for GC should be designed at a proper layer, without these special handling of infoschema and analyze

For internal sessions, we already did https://github.com/pingcap/tidb/pull/32726 to improve it.

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
