### ISSUE TITLE
tidb_stats_cache_mem_quota can't control stats cache cost

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#58026]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

million tables and dml on the tables
set tidb_stats_cache_mem_quota 2gb
![Image](https://github.com/user-attachments/assets/a4e85c87-b4c4-4914-855c-3fcababde6b8)

### 4. What is your TiDB version? (Required)

Release Version: v8.5.0-alpha-279-g9812d85d0d
Edition: Community
Git Commit Hash: 9812d85d0d259547cf1dae88abbc7c406c56f935
Git Branch: HEAD
UTC Build Time: 2024-12-03 17:04:33
GoVersion: go1.23.3
Race Enabled: false
Check Table Before Drop: false
Store: unistore

**Comment by hawkingrei** [comment]
It is not a bugix. it is implemented by #58052
