### ISSUE TITLE
leading hint is inapplicable, check the join type or the join algorithm hint

### ISSUE THREAD

**Issue by yi888long** [pingcap/tidb#58067]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

create table;

`create database if not exists `test`; use `test`;CREATE TABLE `test1` (
  `id` char(32) NOT NULL,
  `bill_no` varchar(40) NOT NULL,
  `item_no` varchar(20) NOT NULL,
  `size_no` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] NONCLUSTERED */,
  UNIQUE KEY `uk_test1` (`bill_no`,`item_no`),
  KEY `idx_test1_item_no` (`item_no`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;`

`create database if not exists `test`; use `test`;CREATE TABLE `test2` (
  `id` char(32) NOT NULL,
  `bill_no` varchar(40) NOT NULL,
  `whole_country_flag` tinyint(4) DEFAULT '0',
  `start_time` datetime DEFAULT NULL,
  `expiry_time` datetime(3) DEFAULT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] NONCLUSTERED */,
  UNIQUE KEY `uk_price_change` (`bill_no`),
  KEY `idx_test2_start_time` (`start_time`),
  KEY `idx_test2_expiry_time` (`expiry_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;`

`create database if not exists `test`; use `test`;CREATE TABLE `test3` (
  `id` char(32) NOT NULL, 
  `bill_no` varchar(40) NOT NULL, 
  `organ_id` varchar(20) NOT NULL,
  PRIMARY KEY (`id`) /*T![clustered_index] NONCLUSTERED */,
  UNIQUE KEY `uk_test3` (`bill_no`,`organ_id`),
  KEY `uk_test3_organ_id` (`organ_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;`

Query SQL;

`SELECT  /*+ LEADING(c,a,b),INL_JOIN(c) */ 
	a.item_no,
	a.size_no,
	a.bill_no,
	b.start_time,
	b.expiry_time
FROM
	test1 a
	INNER JOIN test2 b ON a.bill_no = b.bill_no
	INNER JOIN test3 c ON a.bill_no = c.bill_no 
WHERE
    a.item_no = "20190103001334"
	AND c.organ_id IN ("NKWAAH","B5963","M0483" ) 
	AND b.whole_country_flag != '1' 
	AND b.start_time <= "2024-12-06 23:18:05.000000" 
	AND (
		b.expiry_time IS NULL 
		OR b.expiry_time >= "2024-12-06 23:18:05.000000"
	) 
ORDER BY
	b.start_time DESC,
	b.bill_no DESC 
	LIMIT 1`

show warnings;

`| Warning | 1815 | leading hint is inapplicable, check the join type or the join algorithm hint | `
`| Warning | 1815 | leading hint is inapplicable, check if the leading hint table is valid  `

### 2. What did you expect to see? (Required)

Upgrading from v6.5.6 to v7.5.4 should eliminate warnings.

### 3. What did you see instead (Required)

1. v7.5.4 eliminate warnings
2. v6.5.6 see warnings
3. v6.5.6 upgrade to v7.5.4 still see warnings

### 4. What is your TiDB version? (Required)
v7.5.4

| Release Version: v7.5.4
Edition: Community
Git Commit Hash: 15a52d8b9c7eb373fa0b9b71a0ac346f652b7cdf
Git Branch: HEAD
UTC Build Time: 2024-10-12 08:23:42
GoVersion: go1.21.13
Race Enabled: false
Check Table Before Drop: false
Store: tikv |

**Comment by Defined2014** [comment]
Need set `tidb_opt_advanced_join_hint` equals to true. See https://docs.pingcap.com/tidb/stable/system-variables#tidb_opt_advanced_join_hint-new-in-v700 get details.
