### ISSUE TITLE
slowQueryRetriever.parseLog panic when query cluster_slow_query

### ISSUE THREAD

**Issue by owlsome2501** [pingcap/tidb#58147]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1. Run ossinsight workload with 1 tidb, 6 tikv and 2 tiflash.
2. Wait for the problematic slow log to be output and execute `select * from information schema.cluster slow query` to trigger panic.

### 2. What did you expect to see? (Required)

no panic.

### 3. What did you see instead (Required)
![Image](https://github.com/user-attachments/assets/3805253c-170d-47c2-93be-4bc42244dfec)
![Image](https://github.com/user-attachments/assets/1a58b0db-5d77-43a0-babb-07f042edb0ed)
![Image](https://github.com/user-attachments/assets/23bd31e6-09e5-4ace-aed1-b4aee43a4147)

1. `splitByColon` function introduced by pr #54630 cannot correctly parse the problematic slow log.
2. The parseLog function encountered an "index out of range" error while accessing the `values` array.

### 4. What is your TiDB version? (Required)
nightly

**Comment by yibin87** [comment]
Do you know in what situation tidb will produce such problematic slow log? @owlsome2501
