### ISSUE TITLE
The max QPS of table creation by Lightning is slow in millions tables scenario

### ISSUE THREAD

**Issue by lilinghai** [pingcap/tidb#58141]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

500k schemas, 1 million tables
lighting import
![Image](https://github.com/user-attachments/assets/51f69483-4d06-4300-8b4d-244ec96b474c)

### 4. What is your TiDB version? (Required)

[2024/12/10 02:20:07.001 +00:00] [INFO] [info.go:53] ["Welcome to TiDB-Lightning"] [release-version=v8.5.0-alpha-306-gd6b313f268] [git-hash=d6b313f2680f96f775730c555e7ba1d9881d68d5] [git-branch=HEAD] [go-version=go1.23.4] [utc-build-time="2024-12-09 17:11:32"] [race-enabled=false]

**Comment by D3Hunter** [comment]
there are 2 problems here
- max create-table QPS is too low, as lightning uses max 8 threads to do it
- create-table getting slower, it's causes by that querying system table and reloading schema became slower, 

the second is a separate issue, and right now we cannot reproduce it.

this issue will only focus the first

**Comment by D3Hunter** [comment]
for the second problem, we track in https://github.com/pingcap/tidb/issues/58363

**Comment by D3Hunter** [comment]
we also track https://github.com/pingcap/tidb/issues/58649#issuecomment-2567330681 here

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/60283
