### ISSUE TITLE
Reduce the infoschema v2 btree memory usage

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#58321]
## Enhancement

Currently the infoschema v2 is a two level data struct:

```
Btree:   table name -> table id
Cache:   table id -> table
```

The size of cache is under control by @@tidb_schema_cache_size

The btree is not, it store the information of the table name to id index.

I tested the master branch, currently creating 100K tables the btree takes 40.69MB
creating 200K tables the btree takes 80.95MB
...
1M tables, the btree itself could take 400MB 
After restart (multiple versions excluded), 1M tables still takes 283MB

![Image](https://github.com/user-attachments/assets/5ce92425-3f0b-4e0b-ba5a-45ea4eb4d859)

So if we have 3M tables above, the memory usage by the btree might goes up to more than 1GB
Too many small objects also empose a huge burden on Go runtime GC.

**Comment by tiancaiamao** [comment]
After PR 58324 and 58390, I can see no further improvement with a low cost.
Close it for now.

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/50959
