### ISSUE TITLE
go tool trace is broken, "failed to parse any useful part of the trace: misuse of region in goroutine"

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#58364]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

start tidb, run some workload

then use the trace tool

```
curl 'http://127.0.0.1:10080/debug/pprof/trace?seconds=3' > trace.out
go tool trace -http=:6062 trace.out 
2024/12/18 11:29:22 Preparing trace for viewer...
failed to parse any useful part of the trace: misuse of region in goroutine 387: region end {228 pdclient.tsoReqSend} when the inner-most active region start event is {0 pdclient.tsoReqSend}
```

### 2. What did you expect to see? (Required)

go tool trace works.

### 3. What did you see instead (Required)

It's broken.

> failed to parse any useful part of the trace: misuse of region in goroutine 387: region end {228 pdclient.tsoReqSend} when the inner-most active region start event is {0 pdclient.tsoReqSend}

**Comment by tiancaiamao** [comment]
Checked again on master e1c78f239c2e6418da0b6180c11cf82105774ae9  and v8.5.0, cannot reprocedure.
Next I should record the version carefully.

**Comment by YangKeao** [comment]
It's fixed by https://github.com/tikv/pd/pull/8847.

**Comment by YangKeao** [comment]
For anyone who encountered this issue, please try to use https://github.com/YangKeao/go/tree/fix-tidb-trace-region this branch to view the trace. It patched the go trace tool to workaround this issue.
