### ISSUE TITLE
loadInfoSchema() slow when there are background query visiting INFORMATION_SCHEMA.TABLES

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#58363]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

1M table in the cluster already, run 'create table' workload together with a "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_SCHEMA = xxx' workload.

### 2. What did you expect to see? (Required)

DDL should be fast enough.

### 3. What did you see instead (Required)

DDL is slow, and the LoadSchemaDiff takes a long time.

![Image](https://github.com/user-attachments/assets/aa0b46e4-346b-423b-a3da-a2b21a01df4f)

![Image](https://github.com/user-attachments/assets/38c93e85-8eb1-4110-a1c3-301c9e93e8f5)

![Image](https://github.com/user-attachments/assets/90a79bb1-a1d9-469a-a4de-c50b9f0709b1)

### 4. What is your TiDB version? (Required)

master 

```
commit dde1dcd750d3037c8f4576d8bcca716a1b91cd09 (HEAD -> master, origin/master, origin/HEAD)
Author: Rustin <tech@rustin.me>
Date:   Tue Dec 17 18:05:42 2024 +0800

    session: add indexes for `mysql.analyze_jobs` (#58134)
    
    close pingcap/tidb#57996
```

**Comment by tiancaiamao** [comment]
It could be caused by the mutex lock contention.

Visiting INFORMATION_SCHEMA.TABLES hold the lock for a long time.
LoadSchemaDiff need to rebuild schema and add new record to the btree.
They conflicts.

**Comment by jebter** [comment]
Releted to issue: https://github.com/pingcap/tidb/issues/60283
