### ISSUE TITLE
V8.1.1 import into table_name from select * from table_name1 with thread = 3, disable_precheck; statement wants to add precheck to skip empty table check

### ISSUE THREAD

**Issue by xiaobingMo** [pingcap/tidb#58417]
## Feature Request
V8.1.1 import into table_name from select * from table_name1 with thread = 3, disable_precheck; statement wants to add precheck to skip empty table check

**Is your feature request related to a problem? Please describe:**

Import into gd4400_sc.gdods_prpcmain from
-> select
->a.proposalno,a.policyno.a.riskcode,
-> substr(a.operatedate,1,10) operatedate,
-> from gdb_exam.pmain a
-> left join gdb_exam.ptime b on a.policyno = b.certino and b.updatetype='C1"
-> where substr(a.othflag,4,1)<>'1"
-> and a.policyno is not nul1
-> With thread=64,disable precheck;
ERROR 8173 (HY000): PreCheck failed: target table is not empty

**Describe the feature you'd like:**

no error

**Describe alternatives you've considered:**

precheck to skip empty table check

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lance6716** [comment]
IMPORT INTO can only be used to an empty table. This is by design.
