### ISSUE TITLE
CPU usage is high

### ISSUE THREAD

**Issue by dabaosun** [pingcap/tidb#5844]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

insert data into one table which has 0.2 billion history data. 

2. What did you expect to see?
slow resource 

3. What did you see instead?
CPU usage is high: tikv about 30%, tidb about 25%;

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
'Release Version: v1.0.7-1-g4913f64\nGit Commit Hash: 4913f64c14f6b8e5761414def9fac3c477626f74\nGit Branch: release-1.0\nUTC Build Time: 2018-01-25 06:59:40'

5. Deployment Enviroment
5 physical servers:
24 Core+, 125GB,  SSD 450G, Gigabit network card *1 ,  TiDB/PD;
24 Core+, 125GB,  SSD 450G, Gigabit network card *1 ,  TiDB/PD;
24 Core+, 377GB,  SSD 450G, Gigabit network card *1 ,  TiKV;
24 Core+, 377GB,  SSD 450G, Gigabit network card *1 ,  TiKV;
24 Core+, 377GB,  SSD 450G, Gigabit network card *1 ,  TiKV;

**Comment by winkyao** [comment]
@dabaosun Thanks for your feedback.

But I'm misunderstand the issue, TiDB and TiKV cpu just use about 20% - 30% during you inserting 0.2 billion data, the cpu usage is not very high?

**Comment by winkyao** [comment]
Maybe your question is `why TiDB use CPU when inserting data`? Because TiDB need to parse the sql, and convert to the type of the column and do some Key-Value Encoding,  decoding, TiKV do the same thing too.

**Comment by dabaosun** [comment]
@winkyao 
Thanks for your response. 
I have another questions as below. Would you please give me some help?

1. With same test environment, TiKV nodes CPU usage is very low (about 10%) when the data is about 20 millions and can support about 10k concurrency including random ACUD. But, when the data is accumulated to about 0.2 billion, the TiKV CPU usage has significant rise, about 80% AND only can support 1k concurrency. Is it expected?

2. TiDB can support high concurrency or not ? And do you have any recommend on deployment environment for supporting billion data and 10k concurrency?

Thanks again.

**Comment by winkyao** [comment]
@dabaosun 

1. If your test runs immediately after you finished import the 0.2 billion data, the data maybe the balance is not finished, so maybe there is some hot spot data(Please see the [details](https://pingcap.com/blog/2017-07-24-tidbbestpractice/))

2. TiDB can support high concurrency, the more machine, the more throughput capacity.  You can see recommendation of depleyment [here](https://pingcap.com/docs/op-guide/recommendation/).

**Comment by dabaosun** [comment]
Thanks and got your comments.

I did that tests one day later, and also I’m a little confused why all tikv nodes have high CPU usage. Seem all tikv nodes becoming hot spot of R/W. Maybe I need add tikv to support more concurrency based on 0.2 billion data ?

**Comment by coocood** [comment]
@dabaosun 
Can you provide your table schema and query statements?
And how the 0.2 billion data is generated, imported from MySQL or generated by an application?

**Comment by dabaosun** [comment]
@coocood 

1. Table schema and query statements as below.
2. The data is generated by an application.

CREATE TABLE `Table1` (
  `Id` varchar(26) NOT NULL,
  `CreateAt` bigint(20) DEFAULT NULL,
  `UpdateAt` bigint(20) DEFAULT NULL,
  `EditAt` bigint(20) DEFAULT NULL,
  `DeleteAt` bigint(20) DEFAULT NULL,
  `Pinned` tinyint(4) DEFAULT NULL,
  `UserId` varchar(26) DEFAULT NULL,
  `DepartmentId` varchar(26) DEFAULT NULL,
  `RootId` varchar(26) DEFAULT NULL,
  `ParentId` varchar(26) DEFAULT NULL,
  `OriginalId` varchar(26) DEFAULT NULL,
  `Message` text DEFAULT NULL,
  `Type` varchar(26) DEFAULT NULL,
  `Props` text DEFAULT NULL,
  `Hashtags` text DEFAULT NULL,
  `Filenames` text DEFAULT NULL,
  `FileIds` varchar(150) DEFAULT NULL,
  `Reactions` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`Id`),
  KEY `idx_posts_department_id` (`DepartmentId`),
  KEY `idx_posts_root_id` (`RootId`),
  KEY `idx_posts_user_id` (`UserId`),
  KEY `idx_posts_pinned` (`Pinned`),
  KEY `idx_posts_department_id_update_at` (`DepartmentId`,`UpdateAt`),
  KEY `idx_posts_department_id_delete_at_create_at` (`DepartmentId`,`DeleteAt`,`CreateAt`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4 COLLATE=utf8_bin;

SELECT q2.* FROM Table1 q2 INNER JOIN
	(SELECT DISTINCT
		q3.RootId
	FROM
		(SELECT
		RootId
	FROM
		Table1
	WHERE
		DepartmentId = ?
			AND DeleteAt = 0
	ORDER BY CreateAt DESC
	LIMIT ? OFFSET ?) q3
	WHERE q3.RootId != '') q1
ON q1.RootId = q2.Id OR q1.RootId = q2.RootId
WHERE DepartmentId = ?	AND DeleteAt = 0

**Comment by dabaosun** [comment]
Meanwhile ,if only inserting data into the table with **10+** concurrency, all of TiKV nodes have about 30% usage. Not sure it's normal. In other words, Tidb supports high concurrency insert operations ,or not? Is it more dependent on the disk performance?

**Comment by coocood** [comment]
@dabaosun 
One possibility is that the data is generated randomly, and random insert has greater write amplification.

To confirm this, you can profile the TiKV process and generate a flame graph https://github.com/brendangregg/FlameGraph

**Comment by dabaosun** [comment]
The thread named endpoint-normal has high CPU  usage.  What is this thread used for and Do you have any suggestion on next step? Thanks.

**Comment by coocood** [comment]
@dabaosun 
The endpoint-normal is used to read data for select statements.
If data size fetched for the select statement is proportional to the dataset size, the CPU usage would be much higher when the dataset is larger.

**Comment by dabaosun** [comment]
@coocood 
Thanks.
How long will the PD migrate the data move to new nodes if new tikv nodes are added? And how does the user know the migration has been done?

**Comment by coocood** [comment]
@dabaosun 
PD has an HTTP API to get the balance info, see
https://github.com/pingcap/docs/blob/master/op-guide/monitor.md#pd-server
