### ISSUE TITLE
flaky assert "assert failed, TS used in import should in [now-1d, now]"

### ISSUE THREAD

**Issue by D3Hunter** [pingcap/tidb#58449]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

in real-tikv test, the clock might out of sync between tidb and pd, so this check fails
```
[2024/12/20 10:33:01.029 +00:00] [ERROR] [wait_group_wrapper.go:246] ["panic in error group"] [recover="assert failed, TS used in import should in [now-1d, now], but got 454738780250439970"]


454738780250439970 is 2024-12-20 18:33:01.595000
```

### 4. What is your TiDB version? (Required)
master

**Comment by lance6716** [comment]
it's better to request another TS from PD in `intest` functions and check the time range

**Comment by D3Hunter** [comment]
change the range to `[now-1d, now+1h]` wound be enough, the clock is synced with very little difference in most cases, above is within 1 second

**Comment by takaebato** [comment]
Hi! Can I take this issue?
