### ISSUE TITLE
Randgen test fail with error "Can't find column Column#81 in schema Column: [] PKOrUK: [] NullableUK: []"

### ISSUE THREAD

**Issue by xzhangxian1008** [pingcap/tidb#58454]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Minimal reproduce step (Required)

source   [test.txt](https://github.com/user-attachments/files/18224547/test.txt)

error sql: `SELECT  ( 4, 5 )  IN ( SELECT 8 , 0 UNION  SELECT 8, 8 ) AS field1 FROM ( D AS table1 RIGHT OUTER JOIN V AS table2 ON (table2 . col_varchar_binary = table1 . col_varchar_binary_key  ) ) WHERE (   EXISTS ( SELECT   SUBQUERY2_t1 . col_decimal_key AS SUBQUERY2_field1 FROM K AS SUBQUERY2_t1    ) ) OR ( table1 . col_varchar_binary_key >= 'm' OR table1 . col_varchar_binary_key  IN ('m') )  GROUP BY field1  ;`

### 2. What did you expect to see? (Required)

no error

### 3. What did you see instead (Required)

sql returns error: "Can't find column Column#81 in schema Column: [] PKOrUK: [] NullableUK: []"

### 4. What is your TiDB version? (Required)

tidb version: e53ec591b2c601755b63b6be0242fe4eb990313d

**Comment by xzhangxian1008** [comment]
We find that it's pr [#58261](https://github.com/pingcap/tidb/pull/58261) caused the failure.

**Comment by yibin87** [comment]
duplicated with https://github.com/pingcap/tidb/issues/58451
