### ISSUE TITLE
column does not support `COLLOATE`

### ISSUE THREAD

**Issue by leonchen83** [pingcap/tidb#5857]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

create table run following sql 
```  
CREATE TABLE `TEST` (
	`ID` BIGINT(20) NOT NULL COMMENT 'ID',
	`COMMENT` VARCHAR(128) NULL DEFAULT NULL COMMENT 'encoding=UTF8' COLLATE 'utf8_general_ci',
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

```

2. What did you expect to see?

No error occur  
  
Root cause:  
[parser.y](https://github.com/pingcap/tidb/blob/master/parser/parser.y) line 5264, parsed `COMMENT` but doesn't parse `COLLATE`

3. What did you see instead?

SQL EF 081105 09 1Aline 3 column 74 near " 'utf8_general_ci',	PRIMARY KEY (`ID`))COLLATE='latin1_swedish_ci'ENGINE=InnoDB" (total length 226)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.1.0-alpha.1-98-gde9c192
Git Commit Hash: de9c192cba5e461650dd99f654bf82d659373f15
Git Branch: master
UTC Build Time: 2018-02-08 03:33:14
GoVersion: go version go1.9.2 linux/amd64

**Comment by leonchen83** [comment]
But [docs](https://pingcap.com/docs-cn/sql/character-set-support/) points to  
列的 Character Set 和 Collation  
```  
col_name {CHAR | VARCHAR | TEXT} (col_length)
    [CHARACTER SET charset_name]
    [COLLATE collation_name]

col_name {ENUM | SET} (val_list)
    [CHARACTER SET charset_name]
    [COLLATE collation_name]
```

**Comment by lamxTyler** [comment]
`CHARACTER SET` and `COLLATE` should directly follow the `col_name {CHAR | VARCHAR | TEXT} (col_length)`, so you can create the table in this way:
```
CREATE TABLE `TEST` (
	`ID` BIGINT(20) NOT NULL COMMENT 'ID',
	`COMMENT` VARCHAR(128)  COLLATE 'utf8_general_ci' NULL DEFAULT NULL COMMENT 'encoding=UTF8',
	PRIMARY KEY (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
```

**Comment by leonchen83** [comment]
@lamxTyler Thanks to response.
Highly recommend compatible with mysql ddl syntax.
I will close this issue.
