### ISSUE TITLE
tidb and tikv instance are stopped after 5 hours

### ISSUE THREAD

**Issue by bbsyaya** [pingcap/tidb#5886]
在一台机器上同时启动了，一个pd，一个tikv,一个tidb
在启动5个小时之后，tikv进程和tidb自动停止服务了
tikv的log如下：
2018/02/19 02:03:29.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 878 compact_term: 8} at [term: 8, index: 880]
2018/02/19 02:23:31.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 929 compact_term: 8} at [term: 8, index: 931]
2018/02/19 02:43:24.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 980 compact_term: 8} at [term: 8, index: 982]
2018/02/19 03:03:27.025 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1031 compact_term: 8} at [term: 8, index: 1033]
2018/02/19 03:23:23.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1082 compact_term: 8} at [term: 8, index: 1084]
2018/02/19 03:43:24.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1133 compact_term: 8} at [term: 8, index: 1135]
2018/02/19 04:03:26.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1184 compact_term: 8} at [term: 8, index: 1186]
2018/02/19 04:23:30.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1235 compact_term: 8} at [term: 8, index: 1237]
2018/02/19 04:43:31.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1286 compact_term: 8} at [term: 8, index: 1288]
2018/02/19 05:03:24.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1337 compact_term: 8} at [term: 8, index: 1339]
2018/02/19 05:23:26.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1388 compact_term: 8} at [term: 8, index: 1390]
2018/02/19 05:43:29.426 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1439 compact_term: 8} at [term: 8, index: 1441]
2018/02/19 06:03:23.225 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1490 compact_term: 8} at [term: 8, index: 1492]
2018/02/19 06:23:26.425 apply.rs:699: [INFO] [region 16] 17 execute admin command cmd_type: CompactLog compact_log {compact_index: 1541 compact_term: 8} at [term: 8, index: 1543]
2018/02/19 06:40:22.495 signal_handler.rs:66: [INFO] receive signal 1, stopping server...
2018/02/19 06:40:22.495 mod.rs:394: [INFO] stoping end-point-worker
2018/02/19 06:40:22.495 mod.rs:394: [INFO] stoping snap-handler
2018/02/19 06:40:22.495 mod.rs:394: [INFO] stoping storage-scheduler
2018/02/19 06:40:22.498 scheduler.rs:1618: [INFO] scheduler stopped
2018/02/19 06:40:22.498 scheduler.rs:1618: [INFO] scheduler stopped
2018/02/19 06:40:22.502 mod.rs:554: [INFO] storage RaftKv closed.
2018/02/19 06:40:22.504 node.rs:370: [INFO] stop raft store 1 thread
2018/02/19 06:40:22.504 store.rs:2501: [INFO] [store 1] receive quit message
2018/02/19 06:40:22.504 store.rs:551: [INFO] start to stop raftstore.
2018/02/19 06:40:22.504 mod.rs:394: [INFO] stoping split check worker
2018/02/19 06:40:22.504 mod.rs:394: [INFO] stoping snapshot worker
2018/02/19 06:40:22.504 mod.rs:394: [INFO] stoping raft gc worker
2018/02/19 06:40:22.504 mod.rs:394: [INFO] stoping compact worker
2018/02/19 06:40:22.504 future.rs:174: [INFO] stoping pd worker
2018/02/19 06:40:22.504 mod.rs:394: [INFO] stoping consistency check worker
2018/02/19 06:40:22.504 mod.rs:394: [INFO] stoping apply worker
2018/02/19 06:40:22.505 store.rs:576: [INFO] stop raftstore finished.
2018/02/19 06:40:22.506 mod.rs:394: [INFO] stoping store address resolve worker

tidb的log如下：
2018/02/19 05:48:21.750 gc_worker.go:349: [info] [gc worker] 586aefd84780006 start delete 0 ranges
2018/02/19 05:48:21.750 gc_worker.go:414: [info] [gc worker] 586aefd84780006 finish delete 0 ranges, regions: 0, cost time: 559ns
2018/02/19 05:48:21.787 domain.go:561: [info] [domain] reload privilege success.
2018/02/19 05:50:01.753 gc_worker.go:684: [info] [gc worker] 586aefd84780006 start gc, concurrency 1, safePoint: 398201638541066240.
2018/02/19 05:50:01.765 gc_worker.go:705: [info] [gc worker] 586aefd84780006 finish gc, safePoint: 398201638541066240, successful regions: 15, failed regions: 0, total cost time: 12.515416ms
2018/02/19 05:58:21.742 gc_worker.go:234: [info] [gc worker] 586aefd84780006 starts the whole job, safePoint: 398201795827466240
2018/02/19 05:58:21.742 gc_worker.go:463: [info] [gc worker] 586aefd84780006 start resolve locks, safePoint: 398201795827466240.
2018/02/19 05:58:21.748 gc_worker.go:532: [info] [gc worker] 586aefd84780006 finish resolve locks, safePoint: 398201795827466240, regions: 15, total resolved: 0, cost time: 5.933585ms
2018/02/19 05:58:21.750 gc_worker.go:349: [info] [gc worker] 586aefd84780006 start delete 0 ranges
2018/02/19 05:58:21.750 gc_worker.go:414: [info] [gc worker] 586aefd84780006 finish delete 0 ranges, regions: 0, cost time: 542ns
2018/02/19 05:58:21.791 domain.go:561: [info] [domain] reload privilege success.
2018/02/19 06:00:01.753 gc_worker.go:684: [info] [gc worker] 586aefd84780006 start gc, concurrency 1, safePoint: 398201795827466240.
2018/02/19 06:00:01.765 gc_worker.go:705: [info] [gc worker] 586aefd84780006 finish gc, safePoint: 398201795827466240, successful regions: 15, failed regions: 0, total cost time: 12.65724ms
2018/02/19 06:03:47.036 conn.go:450: [error] [2] read packet error, close this connection read tcp 172.31.46.150:4000->123.123.111.109:59050: read: connection timed out
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:70: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:92: 
2018/02/19 06:03:47.036 conn.go:450: [error] [3] read packet error, close this connection read tcp 172.31.46.150:4000->123.123.111.109:59051: read: connection timed out
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:70: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:92: 
2018/02/19 06:03:47.036 server.go:296: [info] [2] close connection
2018/02/19 06:03:47.036 conn.go:450: [error] [5] read packet error, close this connection read tcp 172.31.46.150:4000->123.123.111.109:59053: read: connection timed out
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:70: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:92: 
2018/02/19 06:03:47.036 server.go:296: [info] [3] close connection
2018/02/19 06:03:47.036 server.go:296: [info] [5] close connection
2018/02/19 06:04:19.804 conn.go:450: [error] [6] read packet error, close this connection read tcp 172.31.46.150:4000->123.123.111.109:59054: read: connection timed out
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:70: 
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:92: 
2018/02/19 06:04:19.804 server.go:296: [info] [6] close connection
2018/02/19 06:08:21.742 gc_worker.go:234: [info] [gc worker] 586aefd84780006 starts the whole job, safePoint: 398201953113866240
2018/02/19 06:08:21.742 gc_worker.go:463: [info] [gc worker] 586aefd84780006 start resolve locks, safePoint: 398201953113866240.
2018/02/19 06:08:21.748 gc_worker.go:532: [info] [gc worker] 586aefd84780006 finish resolve locks, safePoint: 398201953113866240, regions: 15, total resolved: 0, cost time: 6.089954ms
2018/02/19 06:08:21.750 gc_worker.go:349: [info] [gc worker] 586aefd84780006 start delete 0 ranges
2018/02/19 06:08:21.750 gc_worker.go:414: [info] [gc worker] 586aefd84780006 finish delete 0 ranges, regions: 0, cost time: 554ns
2018/02/19 06:08:21.796 domain.go:561: [info] [domain] reload privilege success.
2018/02/19 06:10:01.753 gc_worker.go:684: [info] [gc worker] 586aefd84780006 start gc, concurrency 1, safePoint: 398201953113866240.
2018/02/19 06:10:01.766 gc_worker.go:705: [info] [gc worker] 586aefd84780006 finish gc, safePoint: 398201953113866240, successful regions: 15, failed regions: 0, total cost time: 12.484639ms
2018/02/19 06:18:21.743 gc_worker.go:234: [info] [gc worker] 586aefd84780006 starts the whole job, safePoint: 398202110400266240
2018/02/19 06:18:21.743 gc_worker.go:463: [info] [gc worker] 586aefd84780006 start resolve locks, safePoint: 398202110400266240.
2018/02/19 06:18:21.749 gc_worker.go:532: [info] [gc worker] 586aefd84780006 finish resolve locks, safePoint: 398202110400266240, regions: 15, total resolved: 0, cost time: 5.956396ms
2018/02/19 06:18:21.751 gc_worker.go:349: [info] [gc worker] 586aefd84780006 start delete 0 ranges
2018/02/19 06:18:21.751 gc_worker.go:414: [info] [gc worker] 586aefd84780006 finish delete 0 ranges, regions: 0, cost time: 589ns
2018/02/19 06:18:21.800 domain.go:561: [info] [domain] reload privilege success.
2018/02/19 06:20:01.754 gc_worker.go:684: [info] [gc worker] 586aefd84780006 start gc, concurrency 1, safePoint: 398202110400266240.
2018/02/19 06:20:01.767 gc_worker.go:705: [info] [gc worker] 586aefd84780006 finish gc, safePoint: 398202110400266240, successful regions: 15, failed regions: 0, total cost time: 12.68629ms
2018/02/19 06:28:21.742 gc_worker.go:234: [info] [gc worker] 586aefd84780006 starts the whole job, safePoint: 398202267686666240
2018/02/19 06:28:21.742 gc_worker.go:463: [info] [gc worker] 586aefd84780006 start resolve locks, safePoint: 398202267686666240.
2018/02/19 06:28:21.748 gc_worker.go:532: [info] [gc worker] 586aefd84780006 finish resolve locks, safePoint: 398202267686666240, regions: 15, total resolved: 0, cost time: 6.178543ms
2018/02/19 06:28:21.750 gc_worker.go:349: [info] [gc worker] 586aefd84780006 start delete 0 ranges
2018/02/19 06:28:21.750 gc_worker.go:414: [info] [gc worker] 586aefd84780006 finish delete 0 ranges, regions: 0, cost time: 583ns
2018/02/19 06:28:21.804 domain.go:561: [info] [domain] reload privilege success.
2018/02/19 06:30:01.753 gc_worker.go:684: [info] [gc worker] 586aefd84780006 start gc, concurrency 1, safePoint: 398202267686666240.
2018/02/19 06:30:01.766 gc_worker.go:705: [info] [gc worker] 586aefd84780006 finish gc, safePoint: 398202267686666240, successful regions: 15, failed regions: 0, total cost time: 13.209199ms
2018/02/19 06:38:21.742 gc_worker.go:234: [info] [gc worker] 586aefd84780006 starts the whole job, safePoint: 398202424973066240
2018/02/19 06:38:21.742 gc_worker.go:463: [info] [gc worker] 586aefd84780006 start resolve locks, safePoint: 398202424973066240.
2018/02/19 06:38:21.748 gc_worker.go:532: [info] [gc worker] 586aefd84780006 finish resolve locks, safePoint: 398202424973066240, regions: 15, total resolved: 0, cost time: 6.097344ms
2018/02/19 06:38:21.751 gc_worker.go:349: [info] [gc worker] 586aefd84780006 start delete 0 ranges
2018/02/19 06:38:21.751 gc_worker.go:414: [info] [gc worker] 586aefd84780006 finish delete 0 ranges, regions: 0, cost time: 779ns
2018/02/19 06:38:21.809 domain.go:561: [info] [domain] reload privilege success.
2018/02/19 06:40:01.754 gc_worker.go:684: [info] [gc worker] 586aefd84780006 start gc, concurrency 1, safePoint: 398202424973066240.
2018/02/19 06:40:01.766 gc_worker.go:705: [info] [gc worker] 586aefd84780006 finish gc, safePoint: 398202424973066240, successful regions: 15, failed regions: 0, total cost time: 12.618279ms
2018/02/19 06:40:22.497 main.go:399: [info] Got signal [hangup] to exit.
2018/02/19 06:40:22.497 manager.go:225: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 18fde03c-a08e-4a86-851a-85dfc6b2cdc6 isn't the owner
2018/02/19 06:40:22.507 delete_range.go:105: [info] [ddl] closing delRange session pool
2018/02/19 06:40:22.507 ddl.go:341: [info] close DDL:18fde03c-a08e-4a86-851a-85dfc6b2cdc6
2018/02/19 06:40:22.507 ddl.go:304: [info] stop DDL:18fde03c-a08e-4a86-851a-85dfc6b2cdc6
2018/02/19 06:40:22.507 manager.go:236: [info] [ddl] /tidb/ddl/fg/owner ownerManager 18fde03c-a08e-4a86-851a-85dfc6b2cdc6 break campaign loop, revoke err <nil>
2018/02/19 06:40:22.513 manager.go:225: [warning] [stats] /tidb/stats/owner ownerManager 18fde03c-a08e-4a86-851a-85dfc6b2cdc6 isn't the owner
2018/02/19 06:40:22.513 manager.go:185: [info] [stats] /tidb/stats/owner ownerManager 18fde03c-a08e-4a86-851a-85dfc6b2cdc6 etcd session is done, creates a new one
2018/02/19 06:40:22.513 manager.go:154: [warning] [stats] /tidb/stats/owner ownerManager 18fde03c-a08e-4a86-851a-85dfc6b2cdc6 failed to new session, err grpc: the client connection is closing

**Comment by shenli** [comment]
@bbsyaya Please check the FAQ.
By the way: we encourage to use English to communicate in this repo.

**Comment by tiancaiamao** [comment]
In TiKV log:

> 2018/02/19 06:40:22.495 signal_handler.rs:66: [INFO] receive signal 1, stopping server...

In TiDB log:

> 2018/02/19 06:40:22.497 main.go:399: [info] Got signal [hangup] to exit.

TiDB and TiKV stop service because they got those signal.
This may happen when you start them as front job and leave the console.

Maybe you can try the `nohup` command, and find more detail in wiki https://en.wikipedia.org/wiki/SIGHUP.

@bbsyaya

**Comment by shenli** [comment]
@bbsyaya You can get the answer here: https://github.com/pingcap/docs/blob/master/trouble-shooting.md#the-tidbtikvpd-process-aborts-unexpectedly

**Comment by yanbinghui** [comment]
> @bbsyaya You can get the answer here: https://github.com/pingcap/docs/blob/master/trouble-shooting.md#the-tidbtikvpd-process-aborts-unexpectedly

Hi, @shenli , the url is 404. I also encounter this issue, I deploy the pd, tidb and tikv in one single machine. and about 5 hour later, the tikv is crash, but the tidb and pd is ok

**Comment by zhouqiang-cl** [comment]
@yanbinghui  The url is back now
