### ISSUE TITLE
Will TiDB add Sorted Map (or something like Zset in Redis) in the future？

### ISSUE THREAD

**Issue by FreedomMatrix2015** [pingcap/tidb#5888]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by coocood** [comment]
@FreedomMatrix2015 

We don't have any plan to support Redis protocol.

**Comment by shenli** [comment]
@FreedomMatrix2015 We do not have a plan to provide structure API through some protocols such as Redis protocol. But you can use some structures by using TiDB as a library. Please refer to the code here：https://github.com/pingcap/tidb/tree/master/structure
