### ISSUE TITLE
Test compatibility using DataGrip

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#5892]
DataGrip is a Database management systems that support many databases, including MySQL. See https://www.jetbrains.com/datagrip/

**Comment by shenli** [comment]
In the first step, we need to check if there is any issue when running datagrid on TiDB.

**Comment by liangmingran** [comment]
first find a error report when runing datagrid on TiDB.

```
Error encountered when performing Introspect schema INFORMATION_SCHEMA: Unknown column 'generation_expression' in 'field list'.
Unknown column 'generation_expression' in 'field list'
and 5 duplicate reports (3 s 507 ms)
```
then datagrip cannot perform sql completion when  runing datagrid on TiDB

**Comment by coocood** [comment]
@liangmingran 
Thank you for your report.

**Comment by Xuanwo** [comment]
The same issue: https://github.com/pingcap/tidb/issues/6949

IDEA and datagrip use the same sql plugin.

**Comment by nullnotnil** [comment]
I downloaded DataGrip and manually verified that everything seems to work. I did manage to produce one unsupported query, when right clicking on a query to explain it:

```
[2020/09/01 20:56:52.651 -06:00] [INFO] [conn.go:745] ["command dispatched failed"] [conn=12] [connInfo="id:12, addr:127.0.0.1:34728 status:10, collation:utf8_general_ci, user:root"] [command=Query] [status="inTxn:0, autocommit:1"] [sql="/* ApplicationName=DataGrip 2020.2.2 */ explain extended SELECT * FROM test1"] [txn_mode=PESSIMISTIC] [err="[parser:1064]You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 63 near \"SELECT * FROM test1\" "]
```

I think this is acceptable since even if `EXPLAIN EXTENDED` was supported, the execution plan looks very different in TiDB. DataGrip still remains completely usable as well, so I am going to go ahead and close this issue.

**Comment by zhushuaiCoding** [comment]
Now I check the introspect using jdbc metadata option on the datagrip, which can cause the presentation information of the table to not be seen.
![image](https://user-images.githubusercontent.com/38322565/110598945-52082680-81bd-11eb-8736-82ed3118281e.png)
![image](https://user-images.githubusercontent.com/38322565/110599187-9267a480-81bd-11eb-82aa-a4e4cf2130d2.png)

**Comment by morgo** [comment]
@zhushuaiCoding can you confirm what version of TiDB you are using, by executing `select tidb_version()`.

This appears to be the same issue reported in https://github.com/pingcap/tidb/issues/6949 which has since been fixed.

**Comment by zhushuaiCoding** [comment]
Sorry, I didn't use tidb directly. I simply installed MySQL locally, and then the datagrip connection reported this error. Gothub search this problem, want to solve this problem, asked this problem, caused trouble to you, really sorry.
















At 2021-03-11 11:17:09, "Morgan Tocker" <notifications@github.com> wrote:

@zhushuaiCoding can you confirm what version of TiDB you are using, by executing select tidb_version().

This appears to be the same issue reported in #6949 which has since been fixed.

**Comment by 634750802** [comment]
Without `introspect using jdbc metadata` enabled, DataGrip couldn't fetch schema info and raise an exception:

```
Error: [42000][1253] COLLATION 'utf8_general_ci' is not valid for CHARACTER SET 'utf8mb4'.
```

DataGrip version: 2021.2.4

Release Version: v5.4.0-2-g2506c8651
Edition: Community
Git Commit Hash: 2506c8651c9614e3817891f107ff46bc0fae4fb4
Git Branch: HEAD
UTC Build Time: 2022-02-16 08:54:10
GoVersion: go1.16.4
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false

**Comment by WaitRainbow** [comment]
yes... I finally found someone who had encountered the same as me.

I finally tried using Navicat to connect TiDB and it worked. But I still want to know what is the problem with DataGrip connecting to TIDB, have you found a solution to this problem?

**Comment by rudian** [comment]
> 

still haven't supported yet... dont know how long gonna wait

**Comment by dveeden** [comment]
> > 
> 
> still haven't supported yet... dont know how long gonna wait

Hello. Do you get any error or missing functionality when you try this? What is the TiDB and DataGrip version?

**Comment by dveeden** [comment]
Some info I found on this:
- https://blog.jetbrains.com/datagrip/2022/06/07/datagrip-2022-1-5/
- https://youtrack.jetbrains.com/issue/DBE-14973

**Comment by dveeden** [comment]
There is a TiDB option in DataGrip 2023.1.2
![image](https://github.com/pingcap/tidb/assets/1272980/f59ade8d-526f-4fc0-86ea-0a7a5f547ac7)

**Comment by dveeden** [comment]
Some basic testing results are in https://youtrack.jetbrains.com/issue/DBE-14973/Add-TiDB-support#focus=Comments-27-7471752.0-0

**Comment by dveeden** [comment]
Basic support for TiDB in DataGrip seems to work well. There is some room for improvement, but I don't think there is much or anything we can do on the TiDB side at this moment to help with that.

Feel free to re-open this issue and/or create a new issue if there are specific issues with recent versions of DataGrip or any of the JetBrains tools for which improvements in TiDB could help.

**Comment by dveeden** [comment]
Note that DataGrip is already listed on https://docs.pingcap.com/tidb/stable/dev-guide-third-party-support#gui
