### ISSUE TITLE
Support LONG VHARCHAR alias

### ISSUE THREAD

**Issue by ilovesoup** [pingcap/tidb#5918]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Create table test (t LONG VARCHAR NULL);

2. What did you expect to see?
create table success. It's an alias of MEDIUMTEXT.

3. What did you see instead?
Error happened.

This will allow TiDB work as Hive/Spark's metaserver.

**Comment by zhexuany** [comment]
Related PR is already merged. Closing.
