### ISSUE TITLE
Can you release tpc-c and tpc-h test result ?thanks

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#5936]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?
TPC-C and TPC-H test result 

3. What did you see instead?

My SQL 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Assessming....

**Comment by shenli** [comment]
@duckstar2 Thanks for your attention!
We will consider releasing the TPC-H result after 1.1-GA. For the TPC-C, we do not have a plan now.

**Comment by kolbe** [comment]
Please find the results of TPC-H and other benchmarks here: https://github.com/pingcap/docs/tree/master/benchmark

**Comment by cyberspicecai** [comment]
the 

> Please find the results of TPC-H and other benchmarks here: https://github.com/pingcap/docs/tree/master/benchmark

the link is not available now

**Comment by jebter** [comment]
Please refer: https://docs.pingcap.com/tidbcloud/v8.1-performance-benchmarking-with-tpcc. I will close this issue, and you can reopen it if there is a need.
