### ISSUE TITLE
Duplicate entry for key PRIMARY

### ISSUE THREAD

**Issue by DeanThompson** [pingcap/tidb#5940]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
> SHOW CREATE TABLE product;

CREATE TABLE `product` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `content_id` varchar(50) DEFAULT NULL,
  `item_id` varchar(50) DEFAULT NULL,
  `column1` varchar(50) DEFAULT NULL,
  `column2` varchar(50) DEFAULT NULL,
  `item_title` varchar(255) DEFAULT NULL,
  `item_tags` varchar(255) DEFAULT NULL,
  `item_url` text DEFAULT NULL,
  `original_price` varchar(50) DEFAULT NULL,
  `promo_price` varchar(50) DEFAULT NULL,
  `sales` int(11) DEFAULT NULL,
  `url` text DEFAULT NULL,
  `dt` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ix_content_id` (`content_id`),
  KEY `ix_item_id` (`item_id`),
  KEY `ix_column1` (`column1`),
  KEY `ix_column2` (`column2`),
  KEY `ix_dt` (`dt`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=6184640;
```

Insert rows using Python pymysql:

```
query = '''
INSERT INTO `product` (
  `content_id`, `item_id`, `column1`, `column2`, `item_title`, `item_tags`, `item_url`, `original_price`, `promo_price`, `sales`, `url`, `dt`
) VALUES (
   %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s
)

rows = [...]
conn = pymysql.connect()
cursor = conn.cursor()
cursor.executemany(query, rows)
cursor.close()
conn.commit()
conn.close()
'''
```

Please notice that the primary key is AUTO_INCREMENT, and we didn't specific its value while inserting new records.

2. What did you expect to see?

The new records will be inserted into table successfully.

3. What did you see instead?

```
pymysql.err.IntegrityError: (1062, "Duplicate entry '6057610' for key 'PRIMARY'")
```

This error happens randomly, and is only found on this table so far.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.1.0-beta-17-g816c764
Git Commit Hash: 816c764cb5d1a144f441f269782b51a23f97db9e
Git Branch: master
UTC Build Time: 2018-02-27 03:07:20
GoVersion: go version go1.10 linux/amd64

**Comment by zimulala** [comment]
@DeanThompson 
Thanks for your report!
Could I know how many TiDBs in your cluster? How do you perform this insert statement? Is it executed concurrently?

**Comment by DeanThompson** [comment]
@zimulala 

3 tidb-server, the client connects to TiDB via Haproxy. The statement is executed in serial.

The table is migrated from another TiDB cluster (RC4, 0.8) by mydumper + loader.

And I solved the problem by reseting the AUTO_INCREMENT into a larger value than `MAX(id)`.

```
 ALTER TABLE product AUTO_INCREMENT=6171314;
```

**Comment by zimulala** [comment]
@DeanThompson 
Could you give your RC4 TiDB's `Git Commit Hash`(use `tidb-server -V`)? And please show the result of `select product from t where id < 1000 limit 10;` 
Do you know the value of  `AUTO_INCREMENT ` in the result `show create table` before you execute this `ALTER TABLE`?

**Comment by DeanThompson** [comment]
```
> SELECT tidb_version();

Release Version: 0.8.0
Git Commit Hash: 71694b05979021aeb1541f54beb72fec8b3601de
Git Branch: master
UTC Build Time: 2017-08-28 04:11:58
```

The source database was dropped from the cluster.

The original `AUTO_INCREMENT` is 6184640 (you can find in my first reply.)

**Comment by zimulala** [comment]
@DeanThompson 
Does this `product ` exist on the current cluster? If it exists, please show the result of `select product from t where id < 1000 limit 10;`

**Comment by zimulala** [comment]
>Do you know the value of  `AUTO_INCREMENT ` in the result `show create table` before you execute this `ALTER TABLE`?
The case of this question is on the new cluster(TiDB version: v1.1.0-beta-17-g816c764). I'm sorry, I did not make it clear.

**Comment by DeanThompson** [comment]
@zimulala 

> please show the result of `select product from t where id < 1000 limit 10;`

There is no table `t`, do you mean `SELECT * FROM product WHERE id < 1000 LIMIT 10;`? The result set is empty.

> Do you know the value of `AUTO_INCREMENT` in the result `show create table` before you execute this `ALTER TABLE`?

The result is `6184640`.

**Comment by zimulala** [comment]
@DeanThompson
Sorry.
`please show the result of select id from product where id < 1000 limit 10;`

**Comment by DeanThompson** [comment]
The result is empty, 0 rows affected.

**Comment by zimulala** [comment]
@DeanThompson 
The reason is that the old version(RC4) of the `auto_increment` field in the result of `show create table` was problematic.
e.g.
```
create table t (...) auto_increment = 1000;
insert into t ...;  ---1
...
insert into t ...;  ---n
```
Do not specify the field of primary_id(auto_increment). 
Then excute the statement of `show create table t;`
The old version(RC4) result: create table t (...) auto_increment = 1000;
The correct result: create table t (...) auto_increment = 1000 + n - 1;
So that you use the problematic `create table` statement to load data.
In the PR of #5470 we fixed it.

**Comment by DeanThompson** [comment]
@zimulala Thanks for the investigation. I think this could be closed.

**Comment by zimulala** [comment]
@DeanThompson 
Not at all.
