### ISSUE TITLE
Long running sql failed with "start timestamp fall behind safe point " in 5.7.1-TiDB-v1.0.7-1-g4913f64.

### ISSUE THREAD

**Issue by Robert-Xie** [pingcap/tidb#5956]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Run "select * from big_table_a" and fetch rows to a series of text files.
Comment: big_table_a has about **_500,000,000 rows_**. 

2. What did you expect to see?

success without errors.

3. What did you see instead?

failed in  5.7.1-TiDB-v1.0.7-1-g4913f64.
Message: **_start timestamp fall behind safe point_** 

(Same query succeeded in MariaDB10.1)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.1-TiDB-v1.0.7-1-g4913f64

**_How to deal with it?_**

**Comment by zimulala** [comment]
PTAL @disksing

**Comment by wentaoxu** [comment]
thank you for your report!!!
for this problem, you can make gc interval longer using 
```update mysql.tidb set variable_value='10h' where variable_name='tikv_gc_life_time';```.
here, '10h' is the interval needed to run the query.
By the way, for distributed oltp dbms, it is not a good way to run this huge query, it will fail easily, it will be helpful if you can break it into small queries using ```limit``` and ```when```.

**Comment by Robert-Xie** [comment]
Yes, thanks a lot.

**Comment by wentaoxu** [comment]
happy
