### ISSUE TITLE
Failed when updating all rows in table_a to fix data error.（ERROR 9500 (HY000): transaction too large, len:300001）.

### ISSUE THREAD

**Issue by Robert-Xie** [pingcap/tidb#5961]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

update table_a set `column1`='aaaaaa', `column2`=123456;

(Thare are **_840,694 rows_** in table_a ).

2. What did you expect to see?

Query OK ******

3. What did you see instead?

ERROR 9500 (HY000): **_transaction too large, len:300001_**

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                           |
+----------------------------------------------------------------------------------------------------------------------------------------------------------+
| **_Release Version: v1.0.8-1-gaacba4a_**
Git Commit Hash: aacba4a427f6c1dd64cd581e1f888e00aa64e948
Git Branch: release-1.0
UTC Build Time: 2018-02-11 12:21:59 |

**Comment by Robert-Xie** [comment]
Thanks

**Comment by maojing0609** [comment]
我目前也碰到了这个问题，用navicat向数据库导数据，提示[Err] 9500 - transaction too large, len:300001，单表有200w数据
