### ISSUE TITLE
How to use tidb parser to parse and format SQL ?

### ISSUE THREAD

**Issue by ruiaylin** [pingcap/tidb#597]
SQL like this : select * from t1 join (select id , name from t4 where id = 5 ) t2 left join t3 on t2.id = t3.id
解析完成之后是一个 *stmts.SelectStmt 结构 . From 部分  t1 join (select id , name from t4 where id = 5 ) t2 left join t3 on t2.id = t3.id 整体是一个  *rsets.JoinRset , 其 left ： t1 join (select id , name from t4 where id = 5 ) t2 , 也是一个 *rsets.JoinRset ， 这个*rsets.JoinRset的right部分已经是 *rsets.TableSource 了。 我的问题是 select id , name from t4 where id = 5 是一个标准的SelectStmt  ，这个 解析完成是一个 string 。 如何转换成为 SelectStmt   ？  

下面是我解析t1 join (select id , name from t4 where id = 5 ) t2 生成的格式： 

	node Left  >  t1  | lftype>  *rsets.TableSource
	table :  t1 
	node right >  (&{%!s(bool=false) [Field.Name:id, Field.Expr:id Field.Name:name, Field.Expr:name] t4 <nil> <nil> <nil> <nil>  %!s(*rsets.WhereRset=&{0xc20803a840 <nil>}) %!s(coldef.LockType=0) }) AS t2  | ritype>  *rsets.TableSource
	table :  (&{%!s(bool=false) [Field.Name:id, Field.Expr:id Field.Name:name, Field.Expr:name] t4 <nil> <nil> <nil> <nil>  %!s(*rsets.WhereRset=&{0xc20803a840 <nil>}) %!s(coldef.LockType=0) }) AS t2

**Comment by shenli** [comment]
See: https://github.com/pingcap/tidb/blob/master/parser/parser.y#L2873
It is a TableSource and the source is a SelectStmt.

**Comment by ruiaylin** [comment]
got it , thanks very much . @shenli
