### ISSUE TITLE
sub query with nick name failed.

### ISSUE THREAD

**Issue by Robert-Xie** [pingcap/tidb#5970]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

select * from (
     select id, name from table_a 
     union all
     select id, name from table_b
     union all
     select id, name from table_c
) t
order by t.id

2. What did you expect to see?

Result list.

3. What did you see instead?

_**ERROR 1054 (42S22): Unknown table 't'**_

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

_**Release Version: v1.0.8-1-gaacba4a**_
Git Commit Hash: aacba4a427f6c1dd64cd581e1f888e00aa64e948
Git Branch: release-1.0
UTC Build Time: 2018-02-11 12:21:59

**Comment by winoros** [comment]
@Robert-Xie  Thanks for reporting. Could you provide a full recipe? I tried simple sql and it runs successfully.
```
mysql> create table t(a int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t values(1);
Query OK, 1 row affected (0.10 sec)

mysql> select * from (
    -> select * from t
    -> union all
    -> select * from t
    -> union all
    -> select * from t
    -> ) tt;
+------+
| a    |
+------+
|    1 |
|    1 |
|    1 |
+------+
3 rows in set (0.00 sec)
mysql> select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                            |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v1.0.8-1-gaacba4a4
Git Commit Hash: aacba4a427f6c1dd64cd581e1f888e00aa64e948
Git Branch: release-1.0
UTC Build Time: 2018-03-07 10:12:31 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by Robert-Xie** [comment]
Like this:

MySQL [test]> show create table t1;
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                           |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
| t1    | CREATE TABLE `t1` (
  `id` int(11) NOT NULL,
  `name` varchar(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+-------+--------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

MySQL [test]> select t.* from (select * from t1 union all select * from t2) t order by t.id;
ERROR 1054 (42S22): Unknown table 't'


_**select t.***_

**Comment by XuHuaiyu** [comment]
@Robert-Xie 
Thank you for your feedback, we reproduce the problem.
It'll be fixed soon.

**Comment by XuHuaiyu** [comment]
@Robert-Xie You can try branch release-1.1 which will not cause this error.
