### ISSUE TITLE
STRAIGHT_JOIN error.

### ISSUE THREAD

**Issue by Robert-Xie** [pingcap/tidb#5971]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

select * from t1 STRAIGHT_JOIN t2 on t1.id = t2.id;

2. What did you expect to see?

Empty set (0.00 sec)

3. What did you see instead?

ERROR 1105 (HY000): line 1 column 33 near " on t1.id = t2.id" (total length 50)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.0.8-1-gaacba4a
Git Commit Hash: aacba4a427f6c1dd64cd581e1f888e00aa64e948
Git Branch: release-1.0
UTC Build Time: 2018-02-11 12:21:59

**Comment by winoros** [comment]
We haven't support `STRAIGHT_JOIN`, but it's in our TODO list. @zz-jason

**Comment by zz-jason** [comment]
@Robert-Xie I'll support `STRAIGHT_JOIN` in this week. Thanks for your feed back !

**Comment by Robert-Xie** [comment]
Thanks a lot.
