### ISSUE TITLE
when install 9 nodes TiDB cluster,ocurr the error:"join error context deadline exceeded"

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#5975]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
when install 9 nodes TiDB cluster, ocurr the following error :
第一个节点，启动pd1，启动正常
./bin/pd-server --name=pd1 --data-dir=pd1 --client-urls="http://100.185.120.108:2379" --peer-urls="http://100.185.120.108:2380" --initial-cluster="pd1=http://100.185.120.108:2380,pd2=http://100.185.120.109:2380,pd3=http://100.185.120.110:2380" -L "info" --log-file=pd.log &

第二个节点，启动pd2
按手册给的写法，执行报错
./bin/pd-server --name=pd2 -data-dir=pd2 --client-urls="http://100.185.120.109:2379" --peer-urls="http://100.185.120.109:2380" --initial-cluster="pd1=http://100.185.120.108:2380,pd2=http://100.185.120.109:2380,pd3=http://100.185.120.110:2380" --join="http://100.185.120.108:2379" -L "info" --log-file=pd.log &[1] 41752
[tidb@linux100185120109 tidb-latest-linux-amd64]$ FATA[0000] parse cmd flags error: -initial-cluster and -join can not be provided at the same time

修改后的命令，能执行，但日志报错，几十秒后进程退出
./bin/pd-server --name=pd2 --data-dir=pd2 --client-urls="http://100.185.120.109:2379" --peer-urls="http://100.185.120.109:2380" --join="http://100.185.120.108:2379" -L "info" --log-file=pd.log &
日志信息
[tidb@linux100185120109 tidb-latest-linux-amd64]$ cat pd.log 
2018/03/08 11:38:47.041 util.go:54: [info] Welcome to Placement Driver (PD).
2018/03/08 11:38:47.041 util.go:55: [info] Release Version: v1.1.0-beta-2-g824cb5e
2018/03/08 11:38:47.041 util.go:56: [info] Git Commit Hash: 824cb5e416c9250ef310b3a25b5b6abc080249d3
2018/03/08 11:38:47.041 util.go:57: [info] Git Branch: master
2018/03/08 11:38:47.041 util.go:58: [info] UTC Build Time:  2018-02-28 08:40:23
2018/03/08 11:38:47.041 metricutil.go:83: [info] disable Prometheus push client
2018/03/08 11:38:57.042 main.go:87: [fatal] join error context deadline exceeded
/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/pkg/etcdutil/etcdutil.go:90: 
/home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/join.go:100: 2. What did you expect to see?
Sucessful deployment of 9 nodes cluster, 2*TiDB+3*PD+4*TiKV

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by tiancaiamao** [comment]
Thanks for your feedback.
PTAL @disksing

**Comment by disksing** [comment]
Hi @duckstar2 ,

There are currently 2 ways to form a 3 nodes pd cluster.
1. Initialize 3 nodes cluster directly. Each pd should be started with `--initial-cluster="pd1:$addr1,pd2:$addr2,pd3:$addr3"` and `--join=""`.

2. Initialize a single node cluster first, then start 2 other pds to join the existed cluster. The first pd should run with `--initial-cluster="pd1:$pd1"` and `--join=""`, the other 2 pds should run with `--initial-cluster=""` and `--join="$addr1"`.

So you can either change the second pd's `join` to empty (initialize 3 nodes directly), or you can change the first pd's `initial-cluster` to `pd1=http://100.185.120.108:2380` and other pds' `initial-cluster` to "".
