### ISSUE TITLE
Circle CI failed. Failed case is TestDecodeColumnValue.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#5982]
FAIL: http_handler_test.go:335: HTTPHandlerTestSuite.TestDecodeColumnValue

See more https://circleci.com/gh/pingcap/tidb/16652?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by jackysp** [comment]
@zimulala is working on it.

**Comment by zimulala** [comment]
@ngaut @JackDrogon 
PR #5983
