### ISSUE TITLE
where is the mysql test suite?? Can provide mysql  test suite ??

### ISSUE THREAD

**Issue by Ah39** [pingcap/tidb#5992]
Before the use tidb on production. I need test tidb  support mysql sql well or not .
 **So can Provide the sql test suite or ORM test suite ??**

**Comment by shenli** [comment]
@Ah39 The `mysql test` is the internal project. So we can not provide it.

**Comment by Ah39** [comment]
whether if other  open source project have some test suite I can use ？？
