### ISSUE TITLE
Can not support sum(...) on json data?

### ISSUE THREAD

**Issue by aruanruan** [pingcap/tidb#6014]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
CREATE TABLE `t_logger_info` (
	 	  `id` varchar(64) NOT NULL,
	 	  `level` int NOT NULL,
	 	  `content` text NOT NULL,
	 	  `create_time` datetime NOT NULL,
	 	  `log_time` datetime NOT NULL,
          `tags` json DEFAULT NULL,
	 	  PRIMARY KEY (`id`)
	 	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

and insert 1 millons rows, some like: 
5a966eb5ecf6a05fbc7e2d84 | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": true, "i": 1, "app": "test-0", "os-name": 0}
-- | -- | -- | -- | -- | --
5a966eb5ecf6a05fbc7e2d85 | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": false, "i": 2, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d86 | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": true, "i": 3, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d87 | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": false, "i": 4, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d88 | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": true, "i": 5, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d89 | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": false, "i": 6, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d8a | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": true, "i": 7, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d8b | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": false, "i": 8, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d8c | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": true, "i": 9, "app": "test-0", "os-name": 0}
5a966eb5ecf6a05fbc7e2d8d | 2 | test batch 0 | 2018-02-28 16:56:21 | 2018-02-28 16:56:21 | {"b": false, "i": 10, "app": "test-0", "os-name": 0}

i use sum on json data:
SELECT  sum(tags->'$.i') FROM db_pangu.t_logger_info    

2. What did you expect to see?

in mysql:  give the result :  495000000
--
3. What did you see instead?

in tidb:  Error Code: 1105. cannot convert 0(type json.BinaryJSON) to float64

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.1-Tidb-v1.1.0-apha.1-85-gbe1eeac

**Comment by shenli** [comment]
@aruanruan Thanks for your feedback! 
@XuHuaiyu PTAL

**Comment by aruanruan** [comment]
I

**Comment by yangwenmai** [comment]
insert data

```sql
INSERT INTO `t_logger_info` (`id`, `level`, `content`, `create_time`, `log_time`, `tags`)
VALUES
	('5a966eb5ecf6a05fbc7e2d84', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": true, "i": 1, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d85', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": false, "i": 2, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d86', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": true, "i": 3, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d87', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": false, "i": 4, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d88', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": true, "i": 5, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d89', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": false, "i": 6, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d8a', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": true, "i": 7, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d8b', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": false, "i": 8, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d8c', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": true, "i": 9, "app": "test-0", "os-name": 0}'),
	('5a966eb5ecf6a05fbc7e2d8d', 2, 'test batch 0', '2018-02-28 16:56:21', '2018-02-28 16:56:21', '{"b": false, "i": 10, "app": "test-0", "os-name": 0}');
```
