### ISSUE TITLE
MySQL Workbench show error for json data

### ISSUE THREAD

**Issue by aruanruan** [pingcap/tidb#6015]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

when i use MySQL workbench(community 6.3) to managing tidb,  showing error on column of 'JSON'
Docments show that mysql support json data from version '5.7.8',
is tidb's version is too old?

using 'Server Status' in workbench shows version is 5.7.1

2. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.1-TiDB-v1.1.0-apha.1-85-gbe1eeac

**Comment by jackysp** [comment]
Thank you for your feedback! @aruanruan 
PTAL @hicqu

**Comment by aruanruan** [comment]
My DDL:

DROP TABLE `t_logger_info`;
CREATE TABLE `t_logger_info` (
	 	  `id` varchar(64) NOT NULL,
	 	  `level` int NOT NULL,
	 	  `content` text NOT NULL,
	 	  `create_time` datetime NOT NULL,
	 	  `log_time` datetime NOT NULL,
                 `tags` json DEFAULT NULL,
	 	  PRIMARY KEY (`id`)
	 	) ENGINE=InnoDB DEFAULT CHARSET=utf8;

**Comment by jackysp** [comment]
@aruanruan which operations did you do to cause this error? I've tried to reproduce it, but seems it is not easy. Could you please show me more details?

**Comment by aruanruan** [comment]
running ok, no error, workbench show syntax error only : syntax error: unexpected 'json' (identified)

**Comment by jackysp** [comment]
@aruanruan  I've reproduced it. We consider to fix it. Thanks for your report.
