### ISSUE TITLE
Another question about the parser ?

### ISSUE THREAD

**Issue by ruiaylin** [pingcap/tidb#603]
I try to use tidb's parser to parse  the delete Statement  like this two example 
a. DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3 WHERE t1.id=t2.id AND t2.id=t3.id;
parse result : 
stmt type   : *stmts.DeleteStmt 
stmt.Where        :  t1.id = t2.id && t2.id = t3.id  |  *expression.BinaryOperation
stmt.Order        :    |  *rsets.OrderByRset
stmt.Limit        :  <nil>  |  *rsets.LimitRset
stmt.LowPriority  :  false  |  bool
stmt.Ignore       :  false  |  bool
stmt.Quick        :  false  |  bool
stmt.MultiTable   :  true  |  bool
stmt.BeforeFrom   :  false  |  bool
stmt.TableIdents  :  [t1 t2]  |  []table.Ident
stmt.Refs         :  (t1 CROSS JOIN t2) CROSS JOIN t3  |  *rsets.JoinRset

TableIdents   contain t1 and t2  is right . 
b.   DELETE FROM t1 WHERE  id  in ( 2,4,5)  
parse result : 
stmt type   : *stmts.DeleteStmt 
stmt.Where        :  id IN (2,4,5)  |  *expression.PatternIn
stmt.Order        :    |  *rsets.OrderByRset
stmt.Limit        :  <nil>  |  *rsets.LimitRset
stmt.LowPriority  :  false  |  bool
stmt.Ignore       :  false  |  bool
stmt.Quick        :  false  |  bool
stmt.MultiTable   :  false  |  bool
stmt.BeforeFrom   :  false  |  bool
stmt.TableIdents  :  []  |  []table.Ident
stmt.Refs         :  <nil>  |  *rsets.JoinRset
in this result , TableIdents   is null . I want to know where is table t1 ?  Is there something wrong ? or i make a mistake . 

waiting for Respond ， thanks

**Comment by shenli** [comment]
@ruiaylin  In the second statement, t1 is in stmt.Refs.
Delete statement has two mode. 
The first sql is multitable mode, TableIdents is used in this mode to record the table list. Only the row in this table list can not delete.
https://dev.mysql.com/doc/refman/5.7/en/delete.html
The second sql is single table mode, we do not need TableIdents to record table list.

**Comment by ruiaylin** [comment]
@shenli  I know what you mean , but when i parse this :   DELETE FROM t1 WHERE  id  in ( 2,4,5)  statement , the result show stmt.Refs   is nil  :  
 _ sql  :  DELETE FROM t1 WHERE  id  in ( 2,4,5)  
stmt type   : *stmts.DeleteStmt 
stmt.Where        :  id IN (2,4,5)  |  *expression.PatternIn
stmt.Order        :    |  *rsets.OrderByRset
stmt.Limit        :  <nil>  |  *rsets.LimitRset
stmt.LowPriority  :  false  |  bool
stmt.Ignore       :  false  |  bool
stmt.Quick        :  false  |  bool
stmt.MultiTable   :  false  |  bool
stmt.BeforeFrom   :  false  |  bool
stmt.TableIdents  :  []  |  []table.Ident
stmt.Refs         :  <nil>  |  *rsets.JoinRset

stmt.Refs    is nil

**Comment by ruiaylin** [comment]
This makes  me  wonder

**Comment by shenli** [comment]
I add some debug log in parser.y:
@@ -1168,6 +1169,7 @@ DeleteFromStmt:
        {
                // Single Table
                join := &ast.Join{Left: &ast.TableSource{Source: $6.(ast.ResultSetNode)}, Right: nil}
+               fmt.Printf("Delete Stmt TableName: %v, Join.Left: %v\n", $6, join.Left)
                x := &ast.DeleteStmt{
                        TableRefs:      &ast.TableRefsClause{TableRefs: join},
                        LowPriority:    $2.(bool),

And test your case:
➜  interpreter git:(shenli/delete-debug) ✗ ./interpreter 
Welcome to the TiDB.
Version:
Git Commit Hash: 5491086695b6e267bc7a9dda320a5adc435e6734
UTC Build Time:  2015-11-18 07:30:29
tidb> DELETE FROM t1 WHERE id in ( 2,4,5);
Delete Stmt TableName: &{{} {[]}  t1 <nil> <nil>}, Join.Left: &{{} 0xc8200f6100 }

You can see t1 is in Join.Left.

**Comment by ruiaylin** [comment]
maybe something wrong in my code .  I will check it and try again , thanks @shenli
