### ISSUE TITLE
loader failed 

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6031]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2018/03/12 18:30:34 db.go:45: [error] query sql[CREATE TABLE tidb_loader.checkpoint (
                id char(6) NOT NULL,
                filename varchar(256) NOT NULL,
                cp_schema varchar(128) NOT NULL,
                cp_table varchar(128) NOT NULL,
                offset bigint NOT NULL,
                end_pos bigint NOT NULL,
                create_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                update_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                UNIQUE KEY uk_id_f (id,filename)
        );
] failed Error 1293: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
2018/03/12 18:30:34 checkpoint.go:76: [fatal] recover from check point failed, Error 1293: Incorrect table definition; there can be only one TIMESTAMP column with CURRENT_TIMESTAMP in DEFAULT or ON UPDATE clause
**configure file**
#### 日志输出等级；可以设置为debug, info, warn, error, fatal (默认为"info")
log-level = "info"
#### 指定loader 日志目录
log-file = "loader.log"
#### 需要导入的数据存放路径(default "./")
dir = "/10warehouse-data/warehouse/"
#### Loader 的pprof 地址，用于对Loader 进行性能调试(默认为":10084")
pprof-addr = "100.185.120.121:10084"
#### 会通过这个库获取上次运行的进度(默认为"tidb_loader")
#checkpoint-schema = "tidb_loader"
#### 线程数(默认为16). 每个线程同一时刻只能操作一个数据文件。
pool-size = 16
#### 目标数据库信息
[db]
host = "100.185.120.121"
user = "tidbuser"
password = "Gauss_234"
port = 3306
#### [[route-rules]]
####pattern-schema = "tpcc10w"
####pattern-table = "warehouse"
target-schema = "tpcc10w"
target-table = "warehouse"
2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by tiancaiamao** [comment]
What version of TiDB are you using (tidb-server -V or run select tidb_version(); on TiDB)?

**Comment by shenli** [comment]
@duckstar2 Please feel free to reopen this issue if you still have problem with loader.
