### ISSUE TITLE
In the TiDB cluster,mysql and TiDB relation,because connect port 3306 and 4000 are ok!

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6033]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by tiancaiamao** [comment]
The default port of TiDB is 4000

```
➜  pingcap mysql -h 127.0.0.1 -uroot -P4000 --column-type-info
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 3
Server version: 5.7.1-TiDB-v1.1.0-beta-57-gd3186dc MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2017, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.
```

Did you notice `Server version: 5.7.1-TiDB-v1.1.0-beta-57-gd3186dc` , that means it's TiDB. @duckstar2
