### ISSUE TITLE
jdbc error: select the Bigint(7) value -1, get result 4294967295(max value of big int)

### ISSUE THREAD

**Issue by JackFish** [pingcap/tidb#6036]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
try to select Bigint(7) value with jdbc'mysql:mysql-connector-java:6.0.6', the value is '-1'

![9 z_ 273 ky2_ _ rn0v](https://user-images.githubusercontent.com/1689611/37319781-7c3cd2ae-26ab-11e8-9d63-5c1e108ba45f.png)

2. What did you expect to see?

see the '-1' 

3. What did you see instead?
'4294967295' 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.0.0-rc.1-6-ge38f406
Git Commit Hash: e38f4067569152dd0acb233b4a8e0cc05644dee1
Git Branch: master
UTC Build Time: 2018-03-11 08:28:59
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 1.1.0-dev.2

**Comment by jackysp** [comment]
Thank you for your feedback! PTAL @zz-jason

**Comment by XuHuaiyu** [comment]
Hi, @JackFish 
Thank you for your feedback, 
can you provide us the complete reproduce procedure?
Such as the schema, data, java code?

**Comment by JackFish** [comment]
[tables_mysql.txt](https://github.com/pingcap/tidb/files/1809654/tables_mysql.txt)
bean define
<bean id="dataInitializeTrigger" class="org.springframework.scheduling.quartz.SimpleTriggerFactoryBean">
    <property name="jobDetail" ref="dataInitialize"/>
    <property name="repeatInterval" value="60000"/>
  </bean>

# spring-context-support-4.3.10.RELEASE.jar
public class SimpleTriggerFactoryBean implements FactoryBean<SimpleTrigger>, BeanNameAware, InitializingBean {

	/** Constants for the SimpleTrigger class */
	private static final Constants constants = new Constants(SimpleTrigger.class);


	private String name;

	private String group;

	private JobDetail jobDetail;

	private JobDataMap jobDataMap = new JobDataMap();

	private Date startTime;

	private long startDelay;

	private long repeatInterval;

	private int **repeatCount = -1;**

	private int priority;


![tim 20180314134331](https://user-images.githubusercontent.com/1689611/37385146-b8a2dc60-278d-11e8-8a21-1aed3e54dd8a.png)
after create job the '-1 ' change to '4294967295'
But in the mysql the result is correct

**Comment by zz-jason** [comment]
@JackFish which table are querying on ?

**Comment by JackFish** [comment]
@zz-jason QRTZ_SIMPLE_TRIGGERS

**Comment by zz-jason** [comment]
@JackFish I can not reproduce this issue on master branch:
```sql
CREATE TABLE QRTZ_SIMPLE_TRIGGERS (
SCHED_NAME VARCHAR(120) NOT NULL,
TRIGGER_NAME VARCHAR(190) NOT NULL,
TRIGGER_GROUP VARCHAR(190) NOT NULL,
REPEAT_COUNT BIGINT(7) NOT NULL,
REPEAT_INTERVAL BIGINT(12) NOT NULL,
TIMES_TRIGGERED BIGINT(10) NOT NULL,
PRIMARY KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP),
FOREIGN KEY (SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP)
REFERENCES QRTZ_TRIGGERS(SCHED_NAME,TRIGGER_NAME,TRIGGER_GROUP))
ENGINE=InnoDB;
```

```sql
TiDB(localhost) > insert into QRTZ_SIMPLE_TRIGGERS values("", "", "", -1, -1, -1);
Query OK, 1 row affected (0.00 sec)

TiDB(localhost) > select REPEAT_COUNT from QRTZ_SIMPLE_TRIGGERS;
+--------------+
| REPEAT_COUNT |
+--------------+
|           -1 |
+--------------+
1 row in set (0.00 sec)
```

How do you insert the data into the table?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
