### ISSUE TITLE
Using benchmarkSQL tool to test tpc-c ,occur the error,"Worker 000: ERROR: statement count 5001 exceeds the transaction limitation, autocommit = false"

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6042]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Worker 000: Loading ITEM
Worker 000: ERROR: statement count 5001 exceeds the transaction limitation, autocommit = false
2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by jackysp** [comment]
Thanks for your feedback! 
We add number of statement limitation in one transaction. Please try this option of TiDB : `stmt-count-limit = 100000000`. Then restart your tidb-server.

**Comment by jiancaiHub** [comment]
@jackysp hello! where can I conf stmt-count-limit = 100000000 ?

**Comment by tiancaiamao** [comment]
Don't create a empty config file. @jiancaiHub 
Here is a template https://github.com/pingcap/tidb/blob/master/config/config.toml.example

**Comment by tiancaiamao** [comment]
I notice `autocommit = false` in the log, maybe it's the root cause of the problem.
How did you test?
`set @@autocommit = true` maybe solve it.

**Comment by jackysp** [comment]
Hi @jiancaiHub ,
If you use ansible-playbook to manage TiDB cluster, you should set the config file in your own ansible root directory.
Check out {YOUR_ANSIBLE_ROOT}/conf/tidb.yml . 
Create a new empty config file for a standalone TiDB server will cause some problems. TiDB will use its default config when restart. It means the storage will use mocktikv, which is used for debugging, it is not the real TiKV. I think it will cause grafana panel exception.

**Comment by jiancaiHub** [comment]
Thank you very much for replying~
I'm dumping msyql data to tidb。 Because of lots of insert statements in a transaction, did not succeed!  So i want to add this add the limit by configing tidb.yml file,  but it doesn't seem to work.

config `conf/tidb.yml`  

`performance:`
`  # Max CPUs to use, 0 use number of CPUs in the machine.`
`  # max-procs: 0`
`  # StmtCountLimit limits the max count of statement inside a transaction.`
`  stmt-count-limit: 10000000`

error msg：
`[ERR] 1105 - statement count 5001 exceeds the transaction limitation, autocommit = false`

I think this operation is invalid. :(
> SQL：
> set @@autocommit = true
> flush privileges

ps. Grafana panel is working，when i remove customized file.

**Comment by jackysp** [comment]
It seems your config is not working in your server. Please check out the TiDB server log, which will print the configuration when it started.

**Comment by jiancaiHub** [comment]
You're right, the config is not working. At last I find I missed a step when restart tidb.
`ansible-playbook deploy.yml -D`
Everything is working again.
Thanks~

**Comment by zhangquan0126** [comment]
I started the tpcc but got the below error when loading the data:

1105, HY000, [try again later]: startTS 401115151428222977 is stale

Could you help take a look?

Thanks~

**Comment by jackysp** [comment]
Hi @zhangquan0126 ,
There are two ways to solve it. You can use any of them.
1. Uncomment [this line](https://github.com/pingcap/tidb-ansible/blob/00cf2e41dabc322f02fa344853ded1c8fdd16e93/conf/tidb.yml#L216), and set it false.
1. Uncomment [this line](https://github.com/pingcap/tidb-ansible/blob/00cf2e41dabc322f02fa344853ded1c8fdd16e93/conf/tidb.yml#L217), and set a much bigger number for it.

then restart your TiDB server.
