### ISSUE TITLE
select CHAR_LENGTH("中文") dont work right

### ISSUE THREAD

**Issue by Ah39** [pingcap/tidb#6043]
In  mysql 5.5.35-rel33.0-log . The result is 6 .
But in 5.7.1-TiDB-v1.1.0-alpha.1-26-g04960d4 The result is 2.
![image](https://user-images.githubusercontent.com/2367243/37332315-4ae15fb4-26e1-11e8-9dc3-c88d08452e90.png)

**Comment by jackysp** [comment]
Hi @Ah39 ,
TiDB is compatible with MySQL 5.7. In MySQL 5.7, the result is also 2.
Thank you for your feedback.

**Comment by Ah39** [comment]
The same version() but diffrent character_set . The result is different
![image](https://user-images.githubusercontent.com/2367243/37332812-b4f4298a-26e2-11e8-8c50-cb8ab60b5c83.png)

**Comment by jackysp** [comment]
You're right. It is a charset dependent result. TiDB supports only utf8-like charsets. So I think it is a reasonable result.
