### ISSUE TITLE
Some SQL grammars are supported by TIDB 

### ISSUE THREAD

**Issue by Ah39** [pingcap/tidb#6045]
version 5.7.1-TiDB-v1.1.0-alpha.1-26-g04960d4

SELECT INTERVAL 1   DAY + '2008-12-31';

SELECT DATE_ADD('2009-01-01', INTERVAL 6/4 HOUR_MINUTE);
### The sql is from mysql 5.7 doc

https://dev.mysql.com/doc/refman/5.7/en/date-and-time-functions.html#function_adddate

![image](https://user-images.githubusercontent.com/2367243/37334394-baa03aaa-26e6-11e8-9c80-5d387ba7e36e.png)

**Comment by jackysp** [comment]
Hi @Ah39 ,
Please do not remove the new issue template, just follow the issue template when you want to submit a new issue. 
```
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.


2. What did you expect to see?



3. What did you see instead?



4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```

**Comment by tiancaiamao** [comment]
You can try:

```
SELECT DATE_ADD('2008-12-31',  INTERVAL 1 DAY);
SELECT DATE_ADD('2009-01-01', INTERVAL '6:4' HOUR_MINUTE);
```

@Ah39

**Comment by zz-jason** [comment]
@tiancaiamao maybe we should support these query syntax ?

**Comment by shenli** [comment]
Yes, it is worth to support this.

**Comment by tiancaiamao** [comment]
Yeah, maybe there are some contributors would like to handle this issue after you tag the "help wanted" label.

**Comment by colinback** [comment]
I would like to take a look at this one.

**Comment by shenli** [comment]
@colinback Great!

**Comment by colinback** [comment]
@shenli Well, maybe I need some help.
I add a rule for SimpleExpr which makes `SELECT INTERVAL 1 DAY + '2008-12-31'` work. 
```
@@ -3093,6 +3094,17 @@ SimpleExpr:
        {
                $$ = &ast.ValuesExpr{Column: $3.(*ast.ColumnNameExpr)}
        }
+|      "INTERVAL" Expression TimeUnit '+' Expression %prec interval
+       {
+               $$ = &ast.FuncCallExpr{
+                       FnName: model.NewCIStr("DATE_ADD"),
+                       Args: []ast.ExprNode{
+                               $5,
+                               $2,
+                               ast.NewValueExpr($3),
+                       },
+               }
+       }
 |      SimpleIdent jss stringLit
```

However it affects INTERVA  function. `SELECT INTERVAL(1, 0, 1, 2)` fails now. I'm guessing maybe it's precedence problem. But what is `lowerThanIntervalKeyword` that is not actually defined? What does following %prec mean?
```
%precedence lowerThanIntervalKeyword
%precedence interval

"INTERVAL" %prec lowerThanIntervalKeyword
```

**Comment by colinback** [comment]
OK. lowerThanIntervalKeyword is a pseudo-token and I see 31 shift/reduce conflicts.
