### ISSUE TITLE
`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP may cause error when inserting data

### ISSUE THREAD

**Issue by Ah39** [pingcap/tidb#6047]
1. What did you do?
insert into order_test(content,create_time) value("helloworld22",null);

2. What did you expect to see?

### Can insert . In java ,some ORM may generator such sql .

3. What did you see instead?
In mysql . The sql can insert.
But in Tidb . The sql cannot insert 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

![image](https://user-images.githubusercontent.com/2367243/37343341-2a16e706-2702-11e8-84cc-e4e0df73ebb5.png)

**Comment by zz-jason** [comment]
@Ah39 Thanks for your feed back ! This is a know issue, which we are working on.

**Comment by jackysp** [comment]
Hi @Ah39 ,
The behavior of timestamp in TiDB is like explicit_defaults_for_timestamp = ON in MySQL. See the following link for the explanation of this system variable, 
https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp ,
which is OFF by default in MySQL.
