### ISSUE TITLE
Fill the TABLE_ROWS field of information_schema.TABLES with the information from statistics

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#6063]
We have updated row_count in the statistics. So we could use it to fill the result of INFORMATION_SCHEMA.TABLES.

**Comment by dreamquster** [comment]
INFORMATION_SCHEMA.TABLES count all rows in table.  statitics.handle record the delta change in mysql.stats_meta, but it doesn't count delta change caused by  DELETE statements. 
Where can I find correct row_count?

**Comment by lamxTyler** [comment]
@dreamquster It counts the delta caused by delete statement. Did you find bugs?

**Comment by dreamquster** [comment]
I'm sorry. Maybe it's caused by unexpected interruption. I'll fill the row_count with the value queried from myql.stats_meta.
