### ISSUE TITLE
Cannot do `insert ... on duplicate key udpate` after add a column of type `timestamp`

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb#6065]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

A streaming task do `insert ... on duplicate udpate` into TiDB instance **A**。
In the mean time，I do `alter table xxx add column created_time timestamp default current_timestamp` on TiDB instance **B**。
After the `alter table` returns, the streaming task gave the following error.

```
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/table/column.go:279: [table:1048]Column created_time can't be null.
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/table/column.go:293:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/executor/write.go:106:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/executor/write.go:1598:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/executor/write.go:939:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/executor/write.go:1129:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/executor/adapter.go:291:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/tidb.go:200:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/session.go:734:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/session.go:822:
/data/program/tistack/tistack-release/go/src/github.com/pingcap/tidb/server/conn.go:854:
```

2. What did you expect to see?

`insert ... on duplicate` should work like a charm.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

A custom build upon `0b7bf3eef59314b8bd0183af7d924afb138a690d`

**Comment by zz-jason** [comment]
@winkyao PTAL

**Comment by jackysp** [comment]
Related to https://github.com/pingcap/tidb/issues/6047

**Comment by XuHuaiyu** [comment]
@lerencao 
Thanks for your feedback.
As the above comment says, the behavior TiDB is implemented as `explicit_defaults_for_timestamp = ON` in [MySQL](https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_explicit_defaults_for_timestamp). 
But TiDB does not support the behavior as MySQL does when set `explicit_defaults_for_timestamp = ON` now. We're working on this.

**Comment by lerencao** [comment]
@XuHuaiyu Thx for the explanation!
What if I set the `created_time` to `NULL DEFAULT CURRENT_TIMESTAMP`, can it work?

**Comment by XuHuaiyu** [comment]
Hi,  @lerencao 
I cannot reproduce your problem.
Can you provide the result of `select tidb_version()`.

My step:
TiDB 1:
``` sql
create table t(a int);
```

TiDB 2 execute this sql every 0.5s:
``` sql
insert into test.t(a) values(1) on duplicate key update a=a+1;
```

TiDB 1:
``` sql
alter table t add column b timestamp default current_timestamp;
```

**Comment by XuHuaiyu** [comment]
Hi,  @lerencao 
I cannot reproduce your problem.
Can you provide the result of `select tidb_version()`.

My step:
TiDB 1:
 ```sql
create table t(a int primary key);
```

TiDB 2 execute this sql every 0.5s:
 ```sql
insert into test.t(a) values(1) on duplicate key update a=a+1;
```

TiDB 1:
 ```sql
alter table t add column b timestamp default current_timestamp;
```

**Comment by lerencao** [comment]
A build upon `0b7bf3eef59314b8bd0183af7d924afb138a690d`.

**Comment by lerencao** [comment]
@XuHuaiyu I believe variable `data` in  https://github.com/pingcap/tidb/blob/65440001d981e081f64b35b4f700ca1acde8b889/executor/write.go#L1577 has `timestamp` column set to null. 
Wish it can help.

**Comment by XuHuaiyu** [comment]
@lerencao
Please try `show create table your_table_name`,
and comment the result here.

**Comment by lerencao** [comment]
``` sql
CREATE TABLE `table1` (
  `pk` varchar(64) NOT NULL,
  `s1` varchar(64) DEFAULT NULL,
  `l1` bigint(20) DEFAULT NULL,
  `s2` varchar(512) DEFAULT NULL,
  `s3` varchar(512) DEFAULT NULL,
  `s4` varchar(512) DEFAULT NULL,
  `s5` varchar(512) DEFAULT NULL,
  `s6` varchar(512) DEFAULT NULL,
  `s7` varchar(512) DEFAULT NULL,
  `s8` varchar(512) DEFAULT NULL,
  `s9` varchar(512) DEFAULT NULL,
  `s10` varchar(512) DEFAULT NULL,
  `s11` varchar(512) DEFAULT NULL,
  `s12` varchar(512) DEFAULT NULL,
  `s13` varchar(512) DEFAULT NULL,
  `t1` mediumtext DEFAULT NULL,
  `i1` int(11) DEFAULT NULL,
  `s14` varchar(512) DEFAULT NULL,
  `l2` bigint(20) DEFAULT NULL,
  `t2` mediumtext DEFAULT NULL,
  `t3` mediumtext DEFAULT NULL,
  `s15` varchar(512) DEFAULT NULL,
  `s16` varchar(512) DEFAULT NULL,
  `d1` double DEFAULT NULL,
  `d2` double DEFAULT NULL,
  `i2` int(11) DEFAULT NULL,
  `i3` int(11) DEFAULT NULL,
  `s17` varchar(512) DEFAULT NULL,
  `s18` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`pk`),
  KEY `s1_idx` (`s1`),
  KEY `s2_idx` (`s2`),
  KEY `s3_idx` (`s3`),
  KEY `s4_idx` (`s4`),
  KEY `l1_idx` (`l1`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin

```

**Comment by lerencao** [comment]
The line  https://github.com/pingcap/tidb/blob/7f958c5a4028169782e345a33486113a63378176/table/tables/tables.go#L526 decodes into a null value for the column `created_time`.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
