### ISSUE TITLE
Navicat fails to connect (due to missing mysql.proc_priv table)

### ISSUE THREAD

**Issue by dreamquster** [pingcap/tidb#6066]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

   SELECT * FROM mysql.procs_priv;

2. What did you expect to see?
   
Host	Db	User	Routine_name	Routine_type	Grantor	Proc_priv	Timestamp

3. What did you see instead?
[Err] 1146 - Table 'mysql.procs_priv' doesn't exist

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
1.1.0-dev.2

TiDB don't have t mysql.proc_priv table.  Navicat have failed to login in TiDB with non-root user because it got an error by sending such sql query.

**Comment by XuHuaiyu** [comment]
@dreamquster  Thank you for your feedback. what's your Navicat version?

**Comment by dreamquster** [comment]
Navicat version: 11.2.7 (64-versionk)

**Comment by kolbe** [comment]
Newer versions of Navicat must handle this differently, as I have no issues connecting to recent releases of TiDB using Navicat 12.1.26.
