### ISSUE TITLE
TiDB support CTE? TiDB have no default configure file ?

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6070]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by XuHuaiyu** [comment]
1. TiDB does not support CTE now.
2. TiDB has a default config file.
The default configuration file config/config.toml.example can be referred.
You can start tidb-server with flag `  -config config_file_path`.

**Comment by duckstar2** [comment]
I installed TiDB cluster by binary method, I didn't find configure file. May I add a configure file in TidB?

**Comment by shenli** [comment]
@duckstar2 Please use ansible to install TiDB.
If you insist the current way, you could get a configure file [here](https://github.com/pingcap/tidb/blob/master/config/config.toml.example).

**Comment by duckstar2** [comment]
use ansible to install TiDB, need many dependencies packages,what difference betwee binary and ansialbe install?

**Comment by shenli** [comment]
@duckstar2 Ansialbe is a convenient way to maintain a cluster.
