### ISSUE TITLE
dep: "github.com/ngaut/pools" is missing?

### ISSUE THREAD

**Issue by qazbnm456** [pingcap/tidb#6082]
1. What did you do?
Get the dep "github.com/ngaut/pools".

2. What did you expect to see?
The dep should be there.

3. What did you see instead?
The dep is missing.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
`master` branch

**Comment by shenli** [comment]
@qazbnm456 Thanks for your feedback!
@ngaut Have you deleted that repo?

**Comment by ngaut** [comment]
Hi @qazbnm456 ,
Could you retry building it. I deleted the repo accidentally. Sorry about that.

**Comment by qazbnm456** [comment]
@shenli @ngaut All good! Thanks for your quick fix.
