### ISSUE TITLE
q: can storage engine been swapped? badgerdb would be nice to plug in.

### ISSUE THREAD

**Issue by glycerine** [pingcap/tidb#6083]
Is the storage engine for tidb swappable?  For instance, badgerdb shows remarkable performance, low write amplification on SSD, and would be quite nice to try.

https://github.com/dgraph-io/badger

**Comment by XuHuaiyu** [comment]
Thank you for your feedback. @glycerine 
But I'm sorry, we don't have the plan to support badgerdb now.
Supporting a new Database API is useful, but it is a long-term commitment, which requires a lot of work on implementation, documentation, and testing, and most importantly, it makes our existing code much more complicated, increases maintenance cost.

**Comment by glycerine** [comment]
> it makes our existing code much more complicated, increases maintenance cost.

Not really, in my experience. This doesn't seem to be a well thought out or well argued proposition.

Having a clean, plugable, storage engine API could make things drastically better. The fact that it seems difficult to imagine it does suggest that it is in fact could be quite useful to create cleaner, layered, structure.

**Comment by tiancaiamao** [comment]
TiDB is well designed and have a clean, plugable, storage engine API,  namely the `kv.Storage` interface. https://github.com/pingcap/tidb/blob/master/kv/kv.go#L238
In my opinion, it's not too hard to **implement a localstore** based on badger, which may be a funny hobby project.

A fully functional **distributed storage engine** involves much more work than a localstore, we don't intend to maintain multiple distributed storage engines now.
@glycerine

**Comment by glycerine** [comment]
>  the kv.Storage interface. https://github.com/pingcap/tidb/blob/master/kv/kv.go#L238

Great--that's what I was looking for. Thanks @tiancaiamao. 

I just wanted to experiment. No suggestion was implied that the TiDB project should maintain such experiments.

Thanks again for the pointer.
