### ISSUE TITLE
backup TiDB and TiKV data directory

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6084]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I want to test tpc-c in TiDB cluster,because load data is slow ,I will backup TiDB or TiKV data directory,use next test,ok?

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by XuHuaiyu** [comment]
You should backup data directory of TiKV and PD. @duckstar2

**Comment by duckstar2** [comment]
thank you
