### ISSUE TITLE
default value caused data missing

### ISSUE THREAD

**Issue by ElvizLai** [pingcap/tidb#609]
sorry，the title should be default value caused data missing

1、using goleveldb
2、a column name Pv defined as ``pv` BIGINT(20) NULL DEFAULT 1`
3、it insert succeed
4、restart db，all data inserted are missing

**Comment by ngaut** [comment]
Thanks for your report, @ElvizLai 
Any more details ?

**Comment by ElvizLai** [comment]
@ngaut sorry, i mis-touched my ''Enter" key.

testing code:
```
writing...wait a second
```

**Comment by ngaut** [comment]
Have you commit your transaction ?

**Comment by ElvizLai** [comment]
@ngaut @disksing am i miss something？

**Comment by shenli** [comment]
@ElvizLai I tested your code with and then check the db with interpreter tool(mv data dir to interpreter dir and  start interpreter).
The data is ready in the db.
tidb> select * from a;
+----+----------+----+
| id | name     | pv |
+----+----------+----+
| 0  | ElvizLai | 0  |
+----+----------+----+
1 row in set (0.00 sec)
tidb> select * from b;
+----+----------+----+
| id | name     | pv |
+----+----------+----+
| 0  | ElvizLai | 0  |
+----+----------+----+
1 row in set (0.00 sec)

**Comment by ElvizLai** [comment]
@shenli you are right. It seems that engine.InsertOne autocommit not work when db already exist.(U can run that code twice, but only one line data inserted). I tried using session to commit, and it succeed. I not very sure what caused this issue.
