### ISSUE TITLE
about TiDB offline install dependenciesis

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6090]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I want to install TiDB for using ansible,but can't find dependencies libraries,for example:python-pyasn1 0.1.8.Can you give me the library?

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by XuHuaiyu** [comment]
Chinese doc: https://pingcap.com/docs-cn/op-guide/offline-ansible-deployment/
English doc: https://pingcap.com/docs/op-guide/offline-ansible-deployment/
