### ISSUE TITLE
about offline install tidb

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6091]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
2018-03-19 18:30:21,086 p=18106 u=root |  100.185.120.112 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}
2018-03-19 18:30:21,101 p=18106 u=root |  100.185.120.121 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}
2018-03-19 18:30:21,108 p=18106 u=root |  100.185.120.120 | UNREACHABLE! => {
    "changed": false,
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n",
    "unreachable": true
}

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by zz-jason** [comment]
@duckstar2 seems you are using [TiDB-Ansible](https://github.com/pingcap/tidb-ansible) to deploy a TiDB cluster ? maybe you can try this:

```sh
ansible-playbook bootstrap.yml -k
ansible-playbook deploy.yml -k
ansible-playbook start.yml -k
```

**Comment by kolbe** [comment]
@duckstar2 were you able to get this to work? If you are still having issues with your deployment, please let us know!

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
