### ISSUE TITLE
run_tidb.sh dont work right ,may exit because of the linux signal

### ISSUE THREAD

**Issue by Ah39** [pingcap/tidb#6094]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
run_tidb.sh and then exit shell ,then the tidb down  

2. What did you expect to see?

exec bin/tidb-server \
    -P 4000 \
    --status="10080" \
    --path="10.242.6.45:2379" \
    --config=conf/tidb.toml \
    --log-file="/opt/tidb/deploy/log/tidb.log" 2> "/opt/tidb/deploy/log/tidb_stderr.log" # & 
 **add & in the line end** 

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.1.0-alpha.1-26-g04960d4
Git Commit Hash: 04960d4fe999ab6b1c222c5528ffdfcf59b6cd87

**Comment by XuHuaiyu** [comment]
@Ah39 You may try this.
``` shell
exec $TIPATH/bin/tidb-server \
-P 4000 \
--status=10080 \
--log-file=TiDB_LOG_PATH \
2> TiDB_ERR_PATH &
```
