### ISSUE TITLE
when i use spark jdbc insert records to tables,tidb-*.log has no insert log!

### ISSUE THREAD

**Issue by yotingting** [pingcap/tidb#6100]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I used spark jdbc api insert records to the table test, tidb-2018-02-19T*.log has no insert log.the following is the log. My code did the things like this:
1): delete test table records of the day '2018-02-19' using java executeUpdate api
2) insert records to the table test using spark jdbc API
3)delete test1 table records of the day '2018-02-19' using java executeUpdate api
4) insert records to the table test1 using spark jdbc API
I saw the log delete records, but couldnot saw the insert log! but when i select the result, the records had been insert the test and test1。is tidb has not insert log ?

```
018/02/20 03:02:30.145 terror.go:342: [error] /home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/util/types/datum.go:1478: cannot convert <nil>(type <nil>) to string
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/executor/set.go:150:
2018/02/20 03:02:30.145 set.go:151: [info] [34512854] set system variable character_set_results =
2018/02/20 03:02:30.146 set.go:151: [info] [34512834] set system variable autocommit = 1
2018/02/20 03:02:30.146 set.go:151: [info] [34512854] set system variable autocommit = 1
2018/02/20 03:02:30.150 server.go:118: [info] [34512866] new connection 58.215.168.167:9401
2018/02/20 03:02:30.156 server.go:280: [info] [34512854] close connection
2018/02/20 03:02:30.191 terror.go:342: [error] /home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/util/types/datum.go:1478: cannot convert <nil>(type <nil>) to string
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/executor/set.go:150:
2018/02/20 03:02:30.191 set.go:151: [info] [34512843] set system variable character_set_results =
2018/02/20 03:02:30.193 set.go:151: [info] [34512843] set system variable autocommit = 1
2018/02/20 03:02:30.199 metrics.go:355: [warning] [EXPENSIVE_QUERY] DElETE FROM test WHERE date = '2018-02-19'
2018/02/20 03:02:30.206 terror.go:342: [error] /home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/util/types/datum.go:1478: cannot convert <nil>(type <nil>) to string
/home/jenkins/workspace/build_tidb_1.0/go/src/github.com/pingcap/tidb/executor/set.go:150:
2018/02/20 03:02:30.206 set.go:151: [info] [34512851] set system variable character_set_results =
2018/02/20 03:02:30.207 set.go:151: [info] [34512851] set system variable autocommit = 1
2018/02/20 03:02:30.213 metrics.go:355: [warning] [EXPENSIVE_QUERY] DElETE FROM test1 WHERE date = '2018-02-19'
2018/02/20 03:02:30.260 server.go:280: [info] [34512843] close connection
2018/02/20 03:02:30.523 server.go:280: [info] [34512616] close connection
```

2. What did you expect to see?
I want see the insert log when I solve no result issues!

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

| tidb_version()                                                                                                                               |
+----------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: 1.0.0
Git Commit Hash: f4e08c15f41f52475184a181ea597ee1cc855c90
Git Branch: release-1.0
UTC Build Time: 2017-10-16 05:32:55 |

**Comment by XuHuaiyu** [comment]
@yotingting 
Yes, if INSERT is executed successfully, TiDB will not write it into the log file.
In which situation you need this?

**Comment by yotingting** [comment]
@XuHuaiyu  I had ran my code insert the table, but test tables record is 0. the other table's process is the same with test named test3  and the two table's process ran the same time. test3 has records insert into it, but test has no records. so I want to check the tidb.log to make sure whether the data was insert to test.
I also had seen some insert log in the logs, and the insert operation is success. I do not understand why the insert log appear in some situation， and sometime disappeared!

**Comment by XuHuaiyu** [comment]
Please check my comment before, I've edited it. @yotingting

**Comment by yotingting** [comment]
@XuHuaiyu I see! thank you very much!

**Comment by yotingting** [comment]
@XuHuaiyu when I Set this value in mysql client ,the error follows:

```
MySQL [(none)]> set @@tidb_general_log=1;
ERROR 1193 (HY000): unknown system variable 'tidb_general_log'
```

**Comment by lamxTyler** [comment]
@yotingting You can upgrade your tidb to at least 1.0.7 version to have this feature.
