### ISSUE TITLE
tidb sysbench demo is right ？？ Only deploy one PD

### ISSUE THREAD

**Issue by Ah39** [pingcap/tidb#6107]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

![image](https://user-images.githubusercontent.com/2367243/37708212-bc3bbae6-2d40-11e8-86f8-411e773462c8.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
https://github.com/pingcap/docs/blob/master/benchmark/sysbench.md

**Comment by winkyao** [comment]
@Ah39 Thanks for your feedback, actually, the TiDB cluster can work when deploying only one PD instance. Sysbench is just a benchmark, not a real production environment. So I think it doesn't matter.
