### ISSUE TITLE
error when deleting all data  in large table

### ISSUE THREAD

**Issue by aruanruan** [pingcap/tidb#6110]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
i have insert 239224 rows in table 't_metric_info'

then i run:
delete FROM t_metric_info;

table schema is:
CREATE TABLE `t_metric_info` (
  `id` varchar(64) NOT NULL,
  `name` varchar(128) NOT NULL,
  `value` json DEFAULT NULL,
  `create_time` datetime NOT NULL,
  `info_time` datetime NOT NULL,
  `tags` json DEFAULT NULL,
  PRIMARY KEY (`id`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 

2. What did you expect to see?

delete all rows, the table will be empty

3. What did you see instead?

Error Code: 9500. transaction is too large	6.583 sec

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.1-TiDB-v1.1.0-alpha.1-85-gbe1eeac

**Comment by lamxTyler** [comment]
@aruanruan The reason for transaction too large can be found [here](https://github.com/pingcap/docs/blob/master/FAQ.md#the-error-message-transaction-too-large-is-displayed).
If you want to delete all data in a large table, you can use `truncate table` to delete it.

**Comment by ihipop** [comment]
@winkyao 
What you said doesn't match the doc

![image](https://user-images.githubusercontent.com/423077/45466437-726ddc00-b74c-11e8-8be8-d8fe7a4c5983.png)

And I tried,The doc is right.
Must use `Detele+Limit` for now
