### ISSUE TITLE
java.util.NoSuchElementException: spark.tispark.pd.addresses

### ISSUE THREAD

**Issue by jasonkoo** [pingcap/tidb#6119]
I am following the guide on this page https://pingcap.com/docs-cn/tispark/tispark-quick-start-guide/ to test the functionality of tispark. I am able to import the sample data into tidb. Also I am able to start spark-shell without any issues. I can import TiContext. But when I tried to create the TiContext, I got the following exception.  Can anyone help me out of this problem? Thank you.

scala> import org.apache.spark.sql.TiContext
import org.apache.spark.sql.TiContext

scala> val ti = new TiContext(spark)
java.util.NoSuchElementException: spark.tispark.pd.addresses
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
  at org.apache.spark.SparkConf$$anonfun$get$1.apply(SparkConf.scala:243)
  at scala.Option.getOrElse(Option.scala:121)
  at org.apache.spark.SparkConf.get(SparkConf.scala:243)
  at com.pingcap.tispark.TiUtils$.sparkConfToTiConf(TiUtils.scala:163)
  at org.apache.spark.sql.TiContext.<init>(TiContext.scala:29)
  ... 48 elided

**Comment by lamxTyler** [comment]
Thanks for your feedback!
PTAL @ilovesoup

**Comment by winoros** [comment]
Thanks for your report, you'd better open a issue in https://github.com/pingcap/tispark next time.

**Comment by birdstorm** [comment]
Hi, jasonkoo.
Thanks for your feedback! It seems that you may not have correctly configured `spark.tispark.pd.addresses` in `$SPARK_HOME/conf/spark-defaults.conf`. You may check [this document](https://pingcap.com/docs-cn/tispark/tispark-user-guide/) for details.

**Comment by jasonkoo** [comment]
@birdstorm My fault. I will set this parameter and see if it's working. Thank you for your quick response!
