### ISSUE TITLE
Fail to build project

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tidb#612]
Hi,

I follow the instructions in `docs/QUICKSTART.md`:

```shell
git clone https://github.com/pingcap/tidb.git $GOPATH/src/github.com/pingcap/tidb
cd $GOPATH/src/github.com/pingcap/tidb
make
```
but fail to build the project. After executing command `make`, it reports errors like:

```text
go get github.com/tools/godep
go get github.com/pingcap/go-hbase
go get github.com/pingcap/go-themis
go get github.com/ngaut/tso/client
go get github.com/qiuyesuifeng/goyacc
go get github.com/qiuyesuifeng/golex
goyacc -o /dev/null -xegen temp_parser_file parser/parser.y; \
	goyacc -o parser/parser.go -xe temp_parser_file parser/parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; system("rm -f temp_parser_file"); exit 1;}}';
/bin/sh: goyacc: command not found
rm -f temp_parser_file; \
	rm -f y.output
sed: parser/parser.go: No such file or directory
sed: parser/parser.go: No such file or directory
make: *** [parser] Error 1
```

Is there anything wrong or any prerequisite should be fullfilled?

**Comment by shenli** [comment]
@hhkbp2  Do you set correct GOPATH and GOROOT, and append $GOPATH/bin to $PATH?

**Comment by hhkbp2** [comment]
@shenli No, I only set GOPATH. After adding `$GOPATH/bin` to `PATH`, the error is gone now.

I think putting this prerequisite for `PATH` in docs would be better. Or ensuring the `PATH` contains `$GOPATH/bin` in Makefile at the very first of the build process.

**Comment by shenli** [comment]
@hhkbp2 Thanks for your report.
We will add this to README.md.

**Comment by hhkbp2** [comment]
add this into the head part of `Makefile` should work(to avoid manually setting PATH, no need of #614)

```makefile
export PATH := $(GOPATH)/bin:$(PATH)
```

Please notice that the default `make` program(version 3.81) in Mac OS X is too old and fail to find `golex`/`goyacc` correctly using variable `PATH`(probably a bug).  To make the above line of code works correctly, you need to upgrade its version or install `make` from homebrew(which contains latest version 4.1 `make`, installed with prefix `g`).

**Comment by ngaut** [comment]
Thanks @hhkbp2 
Could you send us a PR to fix it?

**Comment by hhkbp2** [comment]
@ngaut Sure. The PR is raised as #615.
