### ISSUE TITLE
`mediumtext` returns 0xfa(250) instead of (0xfd)253

### ISSUE THREAD

**Issue by lerencao** [pingcap/tidb#6120]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

JDBC(version: 5.1.46) returns **byte array(instead of string)** for `mediumtext` type column in TiDB. 
But In MySQL, it returns string, which is natural.

I think the same behavior is also applied to `tinytext` and `longtext`, which may have big impacts on existed projects.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

git commit hash: `daa866cdd48e4c0f0d1969bc9238e727a87c6813`

**Comment by lamxTyler** [comment]
Thanks for your feedback!
PTAL @XuHuaiyu

**Comment by lerencao** [comment]
After look through myql jdbc connector, I found that it caused by JOOQ using an interface which mysql connector has a flawed implementation.
Maybe JOOQ should change to another interface, or maybe fix it in mysql connector.
Whatever, it's not related to TiDB.
