### ISSUE TITLE
sysbench is slow

### ISSUE THREAD

**Issue by sse-xmli** [pingcap/tidb#6133]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I hava checkout tidb and build it. After I run tidb_server, I use sysbench to test a insert operation performance. But I found that tidb is significantly slower than mysql5.7. The time of tidb insert 10000000 record is over 10minutes, while mysql is only over 2 minutes. Also the select performance is bad, when I use mysql console to login and excute this command "select count(*) from sbtest1", I found that tidb cost over 2 minutes but mysql only cost 1 second.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb version:v1.1.0-alpha.1-61-gfc699c9

**Comment by winoros** [comment]
Please provide us your configuration of the deployment. And your machine environment.

**Comment by sse-xmli** [comment]
CPU: I7-6700 
Memory: 8GB
OS: Ubuntu16.04 + Xfce Desktop
I just use the default config in the source code. Only one tidb_server process running in one machine.

**Comment by shenli** [comment]
@sse-xmli Have you deploy tikv and pd? We have published a sysbench result [here](https://github.com/pingcap/docs/blob/master/benchmark/sysbench.md#performace-test-result-for-tidb-using-sysbench).
