### ISSUE TITLE
how to recover tidb cluster?

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#6134]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
The tidb cluster:
.1 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.2 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.3 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV + PD
.4 E5620 CPU, 32G RAM, 480G * 4 SSD, TiKV
.5 E5620 CPU, 32G RAM, SAS HDD, TiDB
.6 E5620 CPU, 32G RAM, SAS HDD, TiDB
each running CentOS 7.

I erase all data on .1 server and re-install CentOS 7 from clean disk.
How can I re-join the .1 server to TiDB cluster? Any document shows that?

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.0.0-rc.1-21-g46f938c
Git Commit Hash: 46f938c632103ba7143775e884be33a1875cfa45
Git Commit Branch: master
UTC Build Time: 2018-03-12 04:25:56
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 1.1.0-dev.2

**Comment by lamxTyler** [comment]
@DavisLinDB You can refer to the docs at [here](https://github.com/pingcap/docs/blob/master/op-guide/horizontal-scale.md#add-a-node-dynamically-1) and [here](https://github.com/pingcap/docs/blob/master/op-guide/horizontal-scale.md#add-a-node-dynamically).

**Comment by shenli** [comment]
@DavisLinDB For TiKV, you need to [make the old instance offline](https://github.com/pingcap/docs/blob/master/op-guide/horizontal-scale.md#delete-a-node-dynamically-1) through pd-ctl then start a new instance on  server-1.
