### ISSUE TITLE
go-ycsb error when testing TiKV cluster

### ISSUE THREAD

**Issue by Borelset** [pingcap/tidb#6162]
1. What did you do?
For testing TiKV cluster, I deploy TiKVs and PDs like below, and run go-ycsb(load mod).

IP/Disk    Disk1  Disk2  Disk3  Disk4
*.*.*.117  TiKV1  TiKV2  TiKV3  PD1
*.*.*.118  TiKV4  TiKV5  TiKV6  PD2
*.*.*.119  TiKV7  TiKV8  TiKV9  PD3,go-ycsb

2. What did you expect to see?
TiKV cluster and go-ycsb all work as normal

3. What did you see instead?
go-ycsb works well at beginning, but after a while, something unexpected happened like below.

INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
INFO[0856] drop regions of store 7 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
WARN[0856] backoffer.maxSleep 20000ms is exceeded, errors:
send tikv request error: rpc error: code = Unavailable desc = grpc: the connection is unavailable, ctx: &{{3839 9 6} id:3839 end_key:":-2715434217924865417" region_epoch:<conf_ver:9 version:6 > peers:<id:3840 store_id:1 > peers:<id:3842 store_id:7 > peers:<id:3843 store_id:10 >  id:3842 store_id:7  200.200.172.118:20260}, try next peer later
send tikv request error: rpc error: code = Unavailable desc = grpc: the connection is unavailable, ctx: &{{3839 9 6} id:3839 end_key:":-2715434217924865417" region_epoch:<conf_ver:9 version:6 > peers:<id:3840 store_id:1 > peers:<id:3842 store_id:7 > peers:<id:3843 store_id:10 >  id:3842 store_id:7  200.200.172.118:20260}, try next peer later
send tikv request error: rpc error: code = Unavailable desc = grpc: the connection is unavailable, ctx: &{{3839 9 6} id:3839 end_key:":-2715434217924865417" region_epoch:<conf_ver:9 version:6 > peers:<id:3840 store_id:1 > peers:<id:3842 store_id:7 > peers:<id:3843 store_id:10 >  id:3842 store_id:7  200.200.172.118:20260}, try next peer later 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.0-rc.3-2-gb1e6249
Git Commit Hash: b1e624918d5cd3a12a47ef23d7ac5eccd7db4757
Git Branch: master
UTC Build Time:  2018-03-26 08:50:31

**Comment by lamxTyler** [comment]
Is the tikv server still alive? Is there something wrong with communication between go-ycsb and tikv?

**Comment by Borelset** [comment]
yeah, TiKVs and PDs are still running.
I have try to kill the go-ycsb and restart it, but it still does not work. 
would the limit of tcp connection or file descriptor result in this problem?

**Comment by shenli** [comment]
@siddontang PTAL

**Comment by Borelset** [comment]
In addition, some information could be found in several TiKV`s log.

2018/03/27 22:02:35.689 subchannel.c:687: [INFO] Connect failed: {"created":"@1522159355.689292013","description":"Failed to connect to remote host: OS Error","errno":111,"file":"/home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.0/grpc/src/core/lib/iomgr/tcp_client_posix.c","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:127.0.0.1:20160"}

**Comment by siddontang** [comment]
the target address showes `127.0.0.1:20160`, how do you configure your cluster? Seem you set a local address for the TiKV `advertise-addr`.

**Comment by Borelset** [comment]
Luckily, problem solved by increasing the limit of TCP connection and file descriptor.
