### ISSUE TITLE
[error] [167] read packet error, close this connection read tcp

### ISSUE THREAD

**Issue by Lloyd-longfei** [pingcap/tidb#6173]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

When I ask for a large amount of data and a relatively large time range, it will cause the TCP to disconnect.

2. What did you expect to see?

How can I set it up to solve this problem?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by zhexuany** [comment]
Thank you for using TiDB. We are really appreciated and we are truly want to help you. So please provide more information such as log and tidb's version.

**Comment by Lloyd-longfei** [comment]
> What version of TiDB are you using (tidb-server -V or run select tidb_version(); on TiDB)?


Release Version: v1.0.8-1-gaacba4a

> What did you see instead?

I'm querying a table for one month, and when the data volume reaches 30 million or so, the data is aggregated and the dimension is calculated. When tidb queries, it will prompt me to timeout after a certain period of time. I'm at tidb. Log found inside, as follows:
```
2018/03/28 15:18:28.557 domain.go:531: [info] [domain] reload privilege success.
2018/03/28 15:18:35.395 conn.go:400: [error] [164] read packet error, close this connection read tcp xxx.xx.xxx.xx:4000->xxx.xxx.xxx.:58851 : read: connection timed out
```

**Comment by Lloyd-longfei** [comment]
How do I need to solve the problem of timeout, what parameters need to be adjusted to control it?

**Comment by zhexuany** [comment]
It seems like tikv side ended connection first. Could you describe your topology of your cluster? If you use tikv as storage layer, could you check out of memory error by using `dmesg`?

**Comment by shenli** [comment]
@Lloyd-longfei Please check the OS's TCP keep-alive configuration.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
