### ISSUE TITLE
sysbench error info ALERT

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6189]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I download sysbench config,execute insert operator ,occur the following error:
ALERT: mysql_drv_query() returned error 1062 (Duplicate entry '252697' for key 'PRIMARY') for query 'INSERT INTO sbtest2 (id, k, c, pad) VALUES (252697, 497871, '71996770227-52540274443-57754438635-63667511419-77088508520-77931657882-25960606816-08167276498-64985531668-36631323311', '20020636634-66043967247-79687866887-34374287488-75357433304')'
FATAL: failed to execute function `event': 3
(last message repeated 1 times)
ALERT: mysql_drv_query() returned error 1062 (Duplicate entry '689752' for key 'PRIMARY') for query 'INSERT INTO sbtest5 (id, k, c, pad) VALUES (689752, 553861, '91168002800-77254671990-02979313094-52216096632-20452415057-87915159783-34254060618-18177676334-65454397301-48922099580', '69761061006-55189007702-51494407200-05877777775-77591983832')'
ALERT: mysql_drv_query() returned error 1062 (Duplicate entry '944457' for key 'PRIMARY') for query 'INSERT INTO sbtest9 (id, k, c, pad) VALUES (944457, 497393, '62617534524-3445449656
ySQL [sys_test_16]> desc sbtest1
    -> ;
+-------+------------------+------+------+---------+-------+
| Field | Type             | Null | Key  | Default | Extra |
+-------+------------------+------+------+---------+-------+
| id    | int(10) UNSIGNED | NO   | PRI  | NULL    |       |
| k     | int(10) UNSIGNED | NO   | MUL  | 0       |       |
| c     | char(120)        | NO   |      |         |       |
| pad   | char(60)         | NO   |      |         |       |
+-------+------------------+------+------+---------+-------+
4 rows in set (0.00 sec)
2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by zhexuany** [comment]
@duckstar2 It seems like you insert same data twice?
