### ISSUE TITLE
9 nodes Tidb cluster,cluster state is normal ,but grafana no monitor info 

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6201]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Almost all are no data points,check server and port are nornal. I don't know how to resolve

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by coocood** [comment]
@duckstar2 
Do you mean there are some of the metrics has data points?
What's the version of TiDB?

**Comment by duckstar2** [comment]
version is new ,about March , I find hosts list is empty, which config may be error?

**Comment by coocood** [comment]
@duckstar2 
There are many things can go wrong, we need more information to help.

**Comment by duckstar2** [comment]
ansible-playbook start.yml occur the following error:
[xxx.xxx.xxx.xxx]: Ansible FAILED! => playbook: start.yml; TASK: import grafana dashboards - run import script; message: {"changed": true, "cmd": "./grafana-config-copy.py", "delta": "0:00:00.099949", "end": "2018-04-02 19:12:50.743089", "msg": "non-zero return code", "rc": 126, "start": "2018-04-02 19:12:50.643140", "stderr": "/bin/sh: ./grafana-config-copy.py: Permission denied", "stderr_lines": ["/bin/sh: ./grafana-config-copy.py: Permission denied"], "stdout": "", "stdout_lines": []}

**Comment by coocood** [comment]
@LinuxGit PTAL

**Comment by LinuxGit** [comment]
```
cd /home/tidb/tidb-ansible/scripts
chmod a+x grafana-config-copy.py
```

**Comment by zhexuany** [comment]
@duckstar2 Have we resolved your problem? If yes, please close issue. If not, please give us more information. In addition, if you want real time help, please send email to sre@pingcap.com

**Comment by ggslove** [comment]
> It seems that grafana-config-copy.py in your server doesn't have execution permission. Run the following commands on the control node, then run `ansible-playbook start.yml`:
> 
> ```
> cd /home/tidb/tidb-ansible/scripts
> chmod a+x grafana-config-copy.py
> ```
thx，I resolve it

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
