### ISSUE TITLE
SQL Error

### ISSUE THREAD

**Issue by zhoffice** [pingcap/tidb#6208]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
SELECT t.* FROM(
select id from zyjkgt_t
UNION ALL
select id from zyzf_t) t

2. What did you expect to see?
The query result

3. What did you see instead?
Unknown table 't'

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v1.0.8-1-gaacba4a
Git Commit Hash: aacba4a
Git Branch: release-1.0
UTC Build Time: 2018-02-11 12:21:59

**Comment by shenli** [comment]
@zhoffice Thanks for your feedback! Please try the latest master.

**Comment by zhoffice** [comment]
Can I use ansible upgrade?

**Comment by shenli** [comment]
Yes. Please refer to the document: https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#ansible-deployment

**Comment by zhoffice** [comment]
OK. No problem in new version.
