### ISSUE TITLE
TiSpark support  to use spark-sql query and concurrent select ? 

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6219]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by zhexuany** [comment]
@duckstar2 

Thanks for your feedback. As you may know, we have a repo call `tispark`. It is better you ask there. 

Regarding of today's issue, the answer is yes. `tispark` supports both `spark-shell` and `spark-submit`, so does the concurrent select.
