### ISSUE TITLE
TIDB-SYNC-:4000: i/o timeout

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tidb#6228]
mysql] 2018/04/05 18:37:57 packets.go:33: read tcp 192.168.21.187:22804->192.168.21.187:4000: i/o timeout
2018/04/05 18:37:57 db.go:139: [error] exec sqls[[REPLACE INTO `db_shop`.`tbl_shop_food_price` (`itemID`,`unitKey`,`groupID`,`shopID`,`bookID`,`bookName`,`foodID`,`foodKey`,`foodCode`,`foodScore`,`unit`,`enUnit`,`price`,`prePrice`,`vipPrice`,`specialPrice`,`specialPrice2`,`specialPrice3`,`specialPrice4`,`specialPrice5`,`specialPrice6`,`settlementProportion`,`foodEstimateCost`,`settlementPrice`,`takeoutPackagingFee`,`minOrderCount`,`unitNote`,`rulePriorityLevel`,`startTime`,`endTime`,`sourceFoodUnitID`,`action`,`actionTime`,`createTime`,`onlineTsPrice`,`onlineWmPrice`,`onlineZtPrice`,`wdPrice`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);]] commit failed driver: bad connection
2018/04/05 18:37:57 db.go:92: [warning] sql stmt_exec retry 6: [REPLACE INTO `db_shop`.`tbl_shop_food_price` (`itemID`,`unitKey`,`groupID`,`shopID`,`bookID`,`bookName`,`foodID`,`foodKey`,`foodCode`,`foodScore`,`unit`,`enUnit`,`price`,`prePrice`,`vipPrice`,`specialPrice`,`specialPrice2`,`specialPrice3`,`specialPrice4`,`specialPrice5`,`specialPrice6`,`settlementProportion`,`foodEstimateCost`,`settlementPrice`,`takeoutPackagingFee`,`minOrderCount`,`unitNote`,`rulePriorityLevel`,`startTime`,`endTime`,`sourceFoodUnitID`,`action`,`actionTime`,`createTime`,`onlineTsPrice`,`onlineWmPrice`,`onlineZtPrice`,`wdPrice`) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);] - [[

同步过程一直有ERROR， 后面有WARNING,,,,有解决办法。

**Comment by shenli** [comment]
@dbaspace Thanks for your feedback! Could you provide some detailed information? I can not tell what’s happening in your cluster. It seems that the cluster is busy. And tikv is under heavy write workload.

**Comment by dbaspace** [comment]
[root@glusterfs9 bin]# tail -f /data2/tidb/tikv/logs/tikv.log
2018/04/05 18:59:33.497 apply.rs:699: [INFO] [region 2880] 2883 execute admin command cmd_type: CompactLog compact_log {compact_index: 99342 compact_term: 10} at [term: 10, index: 99347]
2018/04/05 18:59:33.498 apply.rs:699: [INFO] [region 1280] 1283 execute admin command cmd_type: CompactLog compact_log {compact_index: 44734 compact_term: 9} at [term: 9, index: 44736]
2018/04/05 18:59:33.523 apply.rs:699: [INFO] [region 10003] 19045 execute admin command cmd_type: CompactLog compact_log {compact_index: 11559 compact_term: 55} at [term: 55, index: 11561]
2018/04/05 18:59:33.526 apply.rs:699: [INFO] [region 14662] 14665 execute admin command cmd_type: CompactLog compact_log {compact_index: 13019 compact_term: 8} at [term: 8, index: 13021]
2018/04/05 18:59:34.158 apply.rs:699: [INFO] [region 2860] 2863 execute admin command cmd_type: CompactLog compact_log {compact_index: 76859 compact_term: 8} at [term: 8, index: 76861]
2018/04/05 18:59:34.946 apply.rs:699: [INFO] [region 4842] 11482 execute admin command cmd_type: CompactLog compact_log {compact_index: 37388 compact_term: 60} at [term: 60, index: 37390]
2018/04/05 18:59:35.400 apply.rs:699: [INFO] [region 1488] 1491 execute admin command cmd_type: CompactLog compact_log {compact_index: 29087 compact_term: 10} at [term: 10, index: 29089]
2018/04/05 18:59:35.875 apply.rs:699: [INFO] [region 3668] 3671 execute admin command cmd_type: CompactLog compact_log {compact_index: 24891 compact_term: 7} at [term: 7, index: 24893]
2018/04/05 18:59:35.876 apply.rs:699: [INFO] [region 380] 383 execute admin command cmd_type: CompactLog compact_log {compact_index: 88250 compact_term: 8} at [term: 8, index: 88252]
2018/04/05 18:59:35.877 apply.rs:699: [INFO] [region 452] 455 execute admin command cmd_type: CompactLog compact_log {compact_index: 51066 compact_term: 8} at [term: 8, index: 51069]
2018/04/05 18:59:37.051 apply.rs:699: [INFO] [region 3380] 3383 execute admin command cmd_type: CompactLog compact_log {compact_index: 70128 compact_term: 8} at [term: 8, index: 70131]
2018/04/05 18:59:38.945 apply.rs:699: [INFO] [region 2756] 2759 execute admin command cmd_type: CompactLog compact_log {compact_index: 24490 compact_term: 9} at [term: 9, index: 24492]
2018/04/05 18:59:38.958 apply.rs:699: [INFO] [region 1060] 1063 execute admin command cmd_type: CompactLog compact_log {compact_index: 35279 compact_term: 9} at [term: 9, index: 35281]
2018/04/05 18:59:38.958 apply.rs:699: [INFO] [region 408] 411 execute admin command cmd_type: CompactLog compact_log {compact_index: 148707 compact_term: 10} at [term: 10, index: 148710]
2018/04/05 18:59:38.958 apply.rs:699: [INFO] [region 7688] 30793 execute admin command cmd_type: CompactLog compact_log {compact_index: 348316 compact_term: 78} at [term: 78, index: 348318]
2018/04/05 18:59:38.959 apply.rs:699: [INFO] [region 3464] 3467 execute admin command cmd_type: CompactLog compact_log {compact_index: 20590 compact_term: 8} at [term: 8, index: 20592]
2018/04/05 18:59:38.959 apply.rs:699: [INFO] [region 2748] 2751 execute admin command cmd_type: CompactLog compact_log {compact_index: 30946 compact_term: 10} at [term: 10, index: 30948]
2018/04/05 18:59:38.959 apply.rs:699: [INFO] [region 2452] 2455 execute admin command cmd_type: CompactLog compact_log {compact_index: 19655 compact_term: 11} at [term: 11, index: 19657]
2018/04/05 18:59:38.959 apply.rs:699: [INFO] [region 9978] 11374 execute admin command cmd_type: CompactLog compact_log {compact_index: 11576 compact_term: 53} at [term: 53, index: 11578]
2018/04/05 18:59:38.960 apply.rs:699: [INFO] [region 2908] 2911 execute admin command cmd_type: CompactLog compact_log {compact_index: 54931 compact_term: 10} at [term: 10, index: 54933]

[root@glusterfs9 bin]# tail -f /data2/tidb/pd/logs/pd.log 
2018/04/05 14:24:31.525 log.go:85: [info] mvcc: [store.index: compact 57551]
2018/04/05 14:24:31.531 log.go:85: [info] mvcc: [finished scheduled compaction at 57551 (took 3.891626ms)]
2018/04/05 15:24:31.534 log.go:85: [info] mvcc: [store.index: compact 59321]
2018/04/05 15:24:31.543 log.go:85: [info] mvcc: [finished scheduled compaction at 59321 (took 6.074698ms)]
2018/04/05 16:24:31.544 log.go:85: [info] mvcc: [store.index: compact 61094]
2018/04/05 16:24:31.549 log.go:85: [info] mvcc: [finished scheduled compaction at 61094 (took 3.155759ms)]
2018/04/05 17:24:31.575 log.go:85: [info] mvcc: [store.index: compact 62850]
2018/04/05 17:24:31.581 log.go:85: [info] mvcc: [finished scheduled compaction at 62850 (took 3.852503ms)]
2018/04/05 18:24:31.585 log.go:85: [info] mvcc: [store.index: compact 64518]
2018/04/05 18:24:31.595 log.go:85: [info] mvcc: [finished scheduled compaction at 64518 (took 6.566632ms)]
MYSQL:
[root@glusterfs9 bin]# ping 192.168.2.65
PING 192.168.2.65 (192.168.2.65) 56(84) bytes of data.
64 bytes from 192.168.2.65: icmp_seq=1 ttl=62 time=0.664 ms
64 bytes from 192.168.2.65: icmp_seq=2 ttl=62 time=0.721 ms
64 bytes from 192.168.2.65: icmp_seq=3 ttl=62 time=0.633 ms
 集群目前在导入数据 ，同时有3个SYNCER 在同步

**Comment by dbaspace** [comment]
4个TIKV  3个PD   1个TIDB() -->4台服务器

**Comment by shenli** [comment]
Please refer to the [metrics document](https://github.com/pingcap/docs/blob/master/op-guide/dashboard-overview-info.md#key-metrics-description) to see if any of the key metrics of TiKV is abnormal.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
