### ISSUE TITLE
TIDB-SYNCER BNILOG

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tidb#6229]
2018-04-04 09:51:58 1 3.528905 3.528905 3.528905 3.528905 0 3.528905 6.5e-05 6.5e-05 6.5e-05 6.5e-05 0 6.5e-05 1 1 1 1 0 1 1.223838e+06 1.223838e+06 1.223838e+06 1.223838e+06 0 1.223838e+06 <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil> <nil>]][error]Error 1118: entry too large, size: 7719384
2018/04/05 19:30:44 syncer.go:862: [info] [syncer]total events = 260, total tps = 2, recent tps = 0, master-binlog = (mysql-bin.000020, 985654539), master-binlog-gtid=, syncer-binlog = (mysql-bin.000020, 939640289), syncer-binlog-gtid = 
2018/04/05 19:31:12 syncer.go:370: [fatal] Error 1118: entry too large, size: 7719384
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:134: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:101:

**Comment by dbaspace** [comment]
set @@tidb_batch_insert=on;
set @@tidb_batch_delete=on;
通过他们2个来控制？

**Comment by ciscoxll** [comment]
Thanks for your feedback! 
open `set @@session.tidb_batch_insert=1` 
close `set @@session.tidb_batch_insert=0` 
more questions can be viewed [FAQ.](https://pingcap.com/docs-cn/FAQ/)

**Comment by shenli** [comment]
@dbaspace Please refer to the [FAQ](https://github.com/pingcap/docs/blob/4fd71e2aacffba816a3485bd61a92c9330936c07/FAQ.md#the-error-message-transaction-too-large-is-displayed).

There are a few constraints in TiDB:
```
Each Key-Value entry is no more than 6MB
The total number of Key-Value entry is no more than 300,000 rows
The total size of Key-Value entry is no more than 100MB
```

The error message in you log shows `Error 1118: entry too large`. So I think there is a row in the binlog exceed 6MB. which is not allowed in TiDB. So there is no way to sync it into TiDB.

The only thing you can do is skipping that binlog entry.

**Comment by dbaspace** [comment]
2018/04/05 22:32:58 syncer.go:370: [fatal] Error 1118: entry too large, size: 7719384
跳过.....你发的这个 看过了 ，不可能因为大事务就跳过BINLOG，，，，，

**Comment by shenli** [comment]
The constraints are hardcoded in TiDB. Too large rows will hurt the performance and the stability of TiKV cluster. So skipping the binlog entry is the only way for your scenario.

**Comment by dbaspace** [comment]
不可能因为线上有大事务，就跳过的。不过还好给测试出来.....

**Comment by dbaspace** [comment]
公司的数据 经常有大事务操作，这就导致一个问题了，继续测试其他可能的问题
