### ISSUE TITLE
JDBC to TiDB doesn't support useCursorFetch?

### ISSUE THREAD

**Issue by xjlixd** [pingcap/tidb#6231]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
final String fetch = "&useCursorFetch=true&useServerPrepStmts=true&rewriteBatchedStatements=false";
JDBC 's url = URL + fetch;

2. What did you expect to see?
It will get data normally.

3. What did you see instead?
java.sql.SQLException: 
Cannot create PoolableConnectionFactory (ERROR 1105 (HY000): unsupported flag 1).
But when I cancel  "useCursorFetch=true", the JDBC is OK.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
TiDB， as follow:
| Release Version: v2.0.0-rc.3-23-gfaeaccc
Git Commit Hash: faeaccc35e9b0b98eda8edaa215c0e8e70d75b31
Git Branch: master
UTC Build Time: 2018-03-26 02:20:56
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 1.1.0-dev.2 |

**Comment by winoros** [comment]
Please grep `error` in tidb's log, then you can find the raw sql and the error stack information.
Then paste the error log here.

**Comment by mz1999** [comment]
I tried to investigate this issue.

According to MySQL Protocol, the command [COM_STMT_EXECUTE](https://dev.mysql.com/doc/internals/en/com-stmt-execute.html) asks the server to execute a prepared statement.

When a client set a property `useCursorFetch=ture`,  the JDBC driver will set flags to `OPEN_CURSOR_FLAG` (1)

```
PacketPayload packet = this.session.getSharedSendPacket();
packet.writeInteger(IntegerDataType.INT1, MysqlaConstants.COM_STMT_EXECUTE);
packet.writeInteger(IntegerDataType.INT4, this.serverStatementId);

if (this.resultFields != null && this.resultFields.getFields() != null && this.useCursorFetch && getResultSetType() == ResultSet.TYPE_FORWARD_ONLY
 && getFetchSize() > 0) {
    packet.writeInteger(IntegerDataType.INT1, OPEN_CURSOR_FLAG);
} else {
    packet.writeInteger(IntegerDataType.INT1, 0); // placeholder for flags
}
```

But now the TiDB server side only [handles `CURSOR_TYPE_NO_CURSOR` flag](https://github.com/pingcap/tidb/blob/fbae31e95921df08c60f178434ddc69b2ffbf9c8/server/conn_stmt.go#L121),  it does not seem to support Cursor. 

```
 // Now we only support CURSOR_TYPE_NO_CURSOR flag.
 if flag != 0 {
     return mysql.NewErrf(mysql.ErrUnknown, "unsupported flag %d", flag)
 }
```
