### ISSUE TITLE
install lvs,but can't connect tidb with lvs's virtual IP,can connect with tidb real IP address

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6237]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
install multi node tidb,and install LVS,but can't connect tidb with lvs's virtual IP,can connect with tidb real IP address

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by duckstar2** [comment]
ERROR 2003 (HY000): Can't connect to MySQL server on 'xxx.xxx.xxx.xxx' (110),xxx.xxx.xxx.xxx is virtual ip

**Comment by tiancaiamao** [comment]
Maybe there are something wrong with your LVS settings, the request seems never reach TiDB.
Please check the network environment, make sure it works first. @duckstar2

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
