### ISSUE TITLE
Something wrong with binlog

### ISSUE THREAD

**Issue by Lee-Think** [pingcap/tidb#6239]
I installed and tested the pump and drainer in March, and it works. Then I shut down the drainer. Today, I started the drainer discovery log to report "[warning] [stream] node erp-web-other03:8250, pos {Suffix:9 Offset:0}, error RPC error: code = Unknown desc = binlogger: file not found". I guess it may have been caused by the removal of the pump data after it expired. How can I solve this problem?

**Comment by WangXiangUSTC** [comment]
could you please provide the Git Commit Hash and the error log in detail, you can find Commit Hash in drainer's log.

**Comment by GregoryIan** [comment]
it seems u use old version binlog, it's a old bug.  there are two suggestions:

1. suggest u upgrade to have new version binlog that using kafka, u can use [tidb-ansible ](https://github.com/pingcap/docs-cn/blob/master/tools/tidb-binlog-kafka.md#使用-tidb-ansible-部署-pump)
2. u need to show use the binlog files in host erp-web-other03, then we help u to modify your save point file. [binlog files are under data dir configuration item of pump]

**Comment by Lee-Think** [comment]
@WangXiangUSTC Well,I can't find Commit Hash in drainer's log(if the drainer's log means drainer.log file). There is only a group of words that are recycled:
2018/04/09 16:51:23 collector.go:225: [info] erp-web-other03:8250 last CommitTS 0
2018/04/09 16:51:24 pump.go:385: [warning] [stream] node erp-web-other03:8250, pos {Suffix:9 Offset:0}, error rpc error: code = Unknown desc = binlogger: file not found
2018/04/09 16:51:27 pump.go:385: [warning] [stream] node erp-web-other03:8250, pos {Suffix:9 Offset:0}, error rpc error: code = Unknown desc = binlogger: file not found
2018/04/09 16:51:30 pump.go:385: [warning] [stream] node erp-web-other03:8250, pos {Suffix:9 Offset:0}, error rpc error: code = Unknown desc = binlogger: file not found

**Comment by Lee-Think** [comment]
@GregoryIan Ok,I'll try to use the new version. Thank you~

**Comment by WangXiangUSTC** [comment]
@Lee-Think  you can execute ./bin/drainer -V to get commit version

**Comment by Lee-Think** [comment]
@WangXiangUSTC Git Commit Hash: 90b25b725d5ae2aa0b9959825dffeb7b415ba829

**Comment by WangXiangUSTC** [comment]
do you remove some file by yourself?

**Comment by Lee-Think** [comment]
No, it should have been removed by pump

**Comment by WangXiangUSTC** [comment]
pump will gc expired file, and the default gc value is 7 days.

**Comment by Lee-Think** [comment]
I've understood, thanks~~
