### ISSUE TITLE
[Performance] Between mysql and tidb cluster

### ISSUE THREAD

**Issue by SonixLegend** [pingcap/tidb#6271]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I just wrote a benchmark method that insert record to a single table. the table has 1 int(19) auto increment primary key and 14 varchar column, put 20 char on each text column. The cluster contain 2 machine, first 4core 8G 50G HDD, second 4core 4G 50G HDD. I run it on the same machines with mysql or tidb. The tidb cluster has 2 pd, 2 kv and 2 server. But I got the result is mysql write double speed than tidb. It's maybe my servers are so poor, and less than your recommendation. Can you tell me how can I optimize the performance? I will try change the tikv option.

2. What did you expect to see?
I wanna the write speed on tidb cluster is faster than on single mysql server.

3. What did you see instead?
MySQL
>Result "MyBenchmark.testMethod":
>  N = 5
>  mean =      5.286 ±(99.9%) 1.075 ms/op
>
>  Histogram, ms/op:
>    [4.900, 4.950) = 1 
>    [4.950, 5.000) = 0 
>    [5.000, 5.050) = 0 
>    [5.050, 5.100) = 0 
>    [5.100, 5.150) = 1 
>    [5.150, 5.200) = 0 
>    [5.200, 5.250) = 0 
>    [5.250, 5.300) = 1 
>    [5.300, 5.350) = 0 
>    [5.350, 5.400) = 0 
>    [5.400, 5.450) = 0 
>    [5.450, 5.500) = 1 
>    [5.500, 5.550) = 0 
>    [5.550, 5.600) = 0 
>    [5.600, 5.650) = 1 
>
>  Percentiles, ms/op:
>      p(0.0000) =      4.933 ms/op
>     p(50.0000) =      5.267 ms/op
>     p(90.0000) =      5.623 ms/op
>     p(95.0000) =      5.623 ms/op
>     p(99.0000) =      5.623 ms/op
>     p(99.9000) =      5.623 ms/op
>     p(99.9900) =      5.623 ms/op
>     p(99.9990) =      5.623 ms/op
>     p(99.9999) =      5.623 ms/op
>    p(100.0000) =      5.623 ms/op
>
>
>Run complete. Total time: 00:00:20
>
>Benchmark                                    Mode  Cnt   Score   Error   Units
>MyBenchmark.testMethod                      thrpt    5   0.199 ± 0.021  ops/ms
>MyBenchmark.testMethod                       avgt    5   5.107 ± 0.831   ms/op
>MyBenchmark.testMethod                     sample  947   5.283 ± 0.170   ms/op
>MyBenchmark.testMethod:testMethod·p0.00    sample        3.502           ms/op
>MyBenchmark.testMethod:testMethod·p0.50    sample        5.038           ms/op
>MyBenchmark.testMethod:testMethod·p0.90    sample        5.857           ms/op
>MyBenchmark.testMethod:testMethod·p0.95    sample        6.375           ms/op
>MyBenchmark.testMethod:testMethod·p0.99    sample       12.486           ms/op
>MyBenchmark.testMethod:testMethod·p0.999   sample       33.948           ms/op
>MyBenchmark.testMethod:testMethod·p0.9999  sample       33.948           ms/op
>MyBenchmark.testMethod:testMethod·p1.00    sample       33.948           ms/op
>MyBenchmark.testMethod                         ss    5   5.286 ± 1.075   ms/op

TiDB
>Result "MyBenchmark.testMethod":
>  N = 5
>  mean =     11.155 ±(99.9%) 3.948 ms/op
>
>  Histogram, ms/op:
>    [ 9.000,  9.250) = 0 
>    [ 9.250,  9.500) = 0 
>    [ 9.500,  9.750) = 0 
>    [ 9.750, 10.000) = 1 
>    [10.000, 10.250) = 0 
>    [10.250, 10.500) = 0 
>    [10.500, 10.750) = 0 
>    [10.750, 11.000) = 2 
>    [11.000, 11.250) = 0 
>    [11.250, 11.500) = 1 
>    [11.500, 11.750) = 0 
>    [11.750, 12.000) = 0 
>    [12.000, 12.250) = 0 
>    [12.250, 12.500) = 0 
>    [12.500, 12.750) = 1 
>
>  Percentiles, ms/op:
>      p(0.0000) =      9.856 ms/op
>     p(50.0000) =     10.998 ms/op
>     p(90.0000) =     12.715 ms/op
>     p(95.0000) =     12.715 ms/op
>     p(99.0000) =     12.715 ms/op
>     p(99.9000) =     12.715 ms/op
>     p(99.9900) =     12.715 ms/op
>     p(99.9990) =     12.715 ms/op
>     p(99.9999) =     12.715 ms/op
>    p(100.0000) =     12.715 ms/op
>
>
>Run complete. Total time: 00:00:21
>
>Benchmark                                    Mode  Cnt   Score   Error   Units
>MyBenchmark.testMethod                      thrpt    5   0.083 ± 0.022  ops/ms
>MyBenchmark.testMethod                       avgt    5  11.769 ± 0.618   ms/op
>MyBenchmark.testMethod                     sample  420  11.940 ± 0.439   ms/op
>MyBenchmark.testMethod:testMethod·p0.00    sample        8.667           ms/op
>MyBenchmark.testMethod:testMethod·p0.50    sample       11.231           ms/op
>MyBenchmark.testMethod:testMethod·p0.90    sample       14.275           ms/op
>MyBenchmark.testMethod:testMethod·p0.95    sample       16.941           ms/op
>MyBenchmark.testMethod:testMethod·p0.99    sample       25.780           ms/op
>MyBenchmark.testMethod:testMethod·p0.999   sample       31.588           ms/op
>MyBenchmark.testMethod:testMethod·p0.9999  sample       31.588           ms/op
>MyBenchmark.testMethod:testMethod·p1.00    sample       31.588           ms/op
>MyBenchmark.testMethod                         ss    5  11.155 ± 3.948   ms/op

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version:  v2.0.0-rc.4-32-gfbae31e
Git Commit Hash:  fbae31e95921df08c60f178434ddc69b2ffbf9c8
Git Commit Branch:  master
UTC Build Time:  2018-04-08 07:13:10
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  1.1.0-dev.2

**Comment by tiancaiamao** [comment]
TiDB cluster can't beat MySQL in this environment.
Inter process communication cost is high on different machine, a distributed database 
has no advantages at such a scale.
You have to introduce better hardware, and use more machines, to archive the result "the write speed on tidb cluster is faster than on single mysql server" @SonixLegend
