### ISSUE TITLE
Can't set the log level for tikv client caused by vendor

### ISSUE THREAD

**Issue by arthurkiller** [pingcap/tidb#6277]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I'm working on tikv client benchmark.

But I realize that `logrus.SetLevel()` will not take effect caused by the vendor.

2. What did you expect to see?

If here is any way for me to set the log level for tikv go client client.

```golang
...

import "github.com/Sirupsen/logrus"
...

func main() {

...
    logrus.SetLevel(logrus.ErrorLevel)
...

}
```

3. What did you see instead?

nothing happened

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master branch

**Comment by tiancaiamao** [comment]
There is a `config.toml.example` file in the tidb/config dir, https://github.com/pingcap/tidb/blob/master/config/config.toml.example

You can change here as you like

```
[log]
# Log level: debug, info, warn, error, fatal.
level = "info"
```

and start TiDB with

```
./tidb-server -config config.toml.example
```

**Comment by arthurkiller** [comment]
@tiancaiamao Ehhh 

I mean How to set log level in KV client

**Comment by tiancaiamao** [comment]
There are benchkv file here https://github.com/pingcap/tidb/blob/master/cmd/benchkv/main.go
You can have a look.

```
func main() {
	flag.Parse()
	log.SetLevel(log.ErrorLevel) // Change this to whatever you like
	Init()
```

**Comment by arthurkiller** [comment]
@tiancaiamao  yes, but it won't take effort out side this repo in my project caused go will search vendor for this demo, and this `log.SetLevel()` only will take effect if your `main.go` is under `$GOPATH/github.com/pingcap/tidb/`

**Comment by tiancaiamao** [comment]
You want to set log level for your benchmark program, of set log level for TiDB ? @arthurkiller

**Comment by arthurkiller** [comment]
I get my own repo for tikv benchmark, and I import tikv client. But I can't set the log level for tikv client.

**Comment by tiancaiamao** [comment]
So, the problem is tikv client log nothing.
Whether you set log level or not, does not affect the output...

**Comment by arthurkiller** [comment]
correct

Best regards 
✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️✉️

Arthur lee

**Comment by arthurkiller** [comment]
@tiancaiamao why closed? this issue is not solved  yet?

**Comment by arthurkiller** [comment]
> So, the problem is tikv client log nothing.

tikv client default log level is info, the out puts has mixed up

**Comment by tiancaiamao** [comment]
Sorry, I don't get the point. @arthurkiller 
What do you really want to do? what's the log output do you expected? Is the output by your program or by the tikv client library?
Would you please show me your program source code?

**Comment by tiancaiamao** [comment]
So, show me the code or your repo, I can know what happened. 

A suspicious place, you should 
```
import "github.com/sirupsen/logrus"
```
not
```
import "github.com/Sirupsen/logrus"
```

**Comment by arthurkiller** [comment]
```

package main

import (
	"context"
	"flag"
	"fmt"
	"io"
	"math/rand"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"github.com/Sirupsen/logrus"
	"github.com/arthurkiller/perfm"
	"github.com/pingcap/tidb/config"
	"github.com/pingcap/tidb/kv"
	"github.com/pingcap/tidb/store/tikv"
)

var (
	num  int64
	rd   *rand.Rand = rand.New(rand.NewSource(time.Now().UnixNano()))
	lock sync.Mutex

	addr      *string = flag.String("addr", "10.10.34.77:2379,10.10.34.78:2379,10.10.32.223:2379", "indecate the pd cluster address")
	keysize   *int    = flag.Int("key", 1024, "set the key size for test")
	valuesize *int    = flag.Int("value", 10240, "set the vlaue size for test")
	scanlimit *int    = flag.Int("limit", 1024, "set the limit for scan")
	c         *int    = flag.Int("C", 100, "concurrency number for benchmark")
	t         *int    = flag.Int("T", 30, "benchmark duration in seconds")
	n         *int    = flag.Int("N", 0, "benchmark total requests count, default is zero will disable total mode")
)

// iwjob do increase + write in a transection
type iwjob struct {
	ident      int64
	store      kv.Storage
	key, value []byte
}

func (j *iwjob) Copy() (perfm.Job, error) {
	jc := *j
	jc.ident = atomic.AddInt64(&num, 1)
	var err error
	driver := tikv.Driver{}
	jc.store, err = driver.Open("tikv://" + *addr + "?cluster=1")
	if err != nil {
		return nil, err
	}
	jc.value = make([]byte, *valuesize)
	return &jc, nil
}
func (j *iwjob) Pre() (err error) {
	j.key = []byte(fmt.Sprintf("iwbench_%d", j.ident))
	lock.Lock()
	defer lock.Unlock()
	io.ReadFull(rd, j.value)

	return nil
}
func (j *iwjob) Do() error {
	tx, err := j.store.Begin()
	if err != nil {
		return err
	}
	_, err = kv.IncInt64(tx, kv.Key([]byte("index")), 1)
	if err != nil {
		return err
	}
	if err = tx.Set(kv.Key([]byte(append([]byte("value_"), byte(j.ident)))), j.value); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()
	if err = tx.Commit(ctx); err != nil {
		return tx.Rollback()
	}
	return nil
}
func (j *iwjob) After() {
	//j.store.Close()
}


func main() {
	logrus.SetLevel(logrus.ErrorLevel) // take no effect

	flag.Parse()
	if !flag.Parsed() {
		flag.Usage()
		return
	}
	perfm := perfm.New(perfm.WithBinsNumber(15), perfm.WithParallel(*c), perfm.WithDuration(*t), perfm.WithNumber(*n))

	fmt.Println("do iw bench")
	perfm.Regist(&iwjob{})
	perfm.Start()
	perfm.Wait()
}

```

**Comment by arthurkiller** [comment]
You get it

**Comment by arthurkiller** [comment]
@tiancaiamao I tried import `"github.com/Sirupsen/logrus"` but nothing changed

**Comment by arthurkiller** [comment]
![image](https://user-images.githubusercontent.com/11133870/38714298-1250b9ee-3f08-11e8-9621-ea8e2883c40e.png)

**Comment by jackysp** [comment]
@arthurkiller It looks like logs from https://github.com/pingcap/pd .

**Comment by arthurkiller** [comment]
@jackysp PD is not on this host...

**Comment by arthurkiller** [comment]
Really a confusing problem, hhh

**Comment by arthurkiller** [comment]
举一个最简单的例子, 

$GOPATH/src/github.com/pingcap/tidb/cmd/benchraw 这个项目我直接 go build , 执行没有 info log 输出


将, main.go copy 到 $GOPTAH/src/demo 下编译, 就会有 log 输出
![image](https://user-images.githubusercontent.com/11133870/38714656-d97715a8-3f09-11e8-8db0-57e0e086bf86.png)

**Comment by tiancaiamao** [comment]
Try this one "github.com/sirupsen/logrus" ? @arthurkiller

**Comment by arthurkiller** [comment]
@tiancaiamao have a look on my last comment

**Comment by tiancaiamao** [comment]
Oh, I see...
Your `GOPATH/src/github.com/sirupsen/logrus` is different from which in `tidb/vendor`

Go to `GOPATH/src/github.com/sirupsen/logrus`, checkout to that git hash and retry.

```
[[projects]]
  name = "github.com/sirupsen/logrus"
  packages = ["."]
  revision = "ba1b36c82c5e05c4f912a88eab0dcd91a171688f"
  version = "v0.11.5"
```

**Comment by arthurkiller** [comment]
![image](https://user-images.githubusercontent.com/11133870/38714950-3a42cee4-3f0b-11e8-8ab4-ea4bccadc785.png)

![image](https://user-images.githubusercontent.com/11133870/38714958-481313b2-3f0b-11e8-88b6-e3e32d7d68aa.png)

@tiancaiamao  noting. 

Caused the vendor has get its own `logrus`. And go will trate with two logrus(one in vendor , one in GOPATH) independently

**Comment by arthurkiller** [comment]
@tiancaiamao Bro, If u do this. You will see what will happen...

```
举一个最简单的例子,

$GOPATH/src/github.com/pingcap/tidb/cmd/benchraw 这个项目我直接 go build , 执行没有 info log 输出

将, main.go copy 到 $GOPTAH/src/demo 下编译, 就会有 log 输出
image

你们可以试一下, 然后这个问题就能理解了

@tiancaiamao 看下这个
```

**Comment by arthurkiller** [comment]
这个问题很难理解么?  [捂脸]

**Comment by tiancaiamao** [comment]
> $GOPATH/src/github.com/pingcap/tidb/cmd/benchraw 这个项目我直接 go build，执行没有 info log 输出

This case, Go use `$GOPATH/src/github.com/pingcap/tidb/vendor/github.com/sirupsen` to build the binary.

> 将, main.go copy 到 $GOPTAH/src/demo 下编译, 就会有 log 输出

In this case, Go use `$GOPATH/src/github.com/sirupsen` to build the binary.

> go import is not case-sensitive

It's Mac file system that case-insensitive, not Go.

```
sirupsen/logrus, not Sirupsen/logrus....
It's to better to remove Sirupsen/logrus directory
Upgrade your $GOPATH/src/github.com/pingcap/pd/pd-client to master, too.
```

It doesn't work?

We provide vendor to get rid of user's environment, and we use Makefile to control the build processing.
If user break the rule, we can't provide a repeatable build and it's very hard to digest the problem.

**Comment by arthurkiller** [comment]
> It's Mac file system that case-insensitive, not Go.

I have change the path name into lowercase, still can't help

If here is any solution setting log level freely for main.go outside tidb's vendor

**Comment by tiancaiamao** [comment]
Don't change the path name... remove it !

**Comment by arthurkiller** [comment]
After I remove the log, how shoud I set the tikv client log level in my code?

**Comment by arthurkiller** [comment]
> We provide vendor to get rid of user's environment, and we use Makefile to control the build processing.
> If user break the rule, we can't provide a repeatable build and it's very hard to digest the problem.

right, vendor is used to unique dependencies. But we are here talking about `how to use logrus`

In tidb's way, the global log instance is initialized when import logrus, and all the log action point to the same(and only) log instance.

It make's log become clean and unique. But the log instance will be a internal instance which can not be set by SDK user.

**Comment by arthurkiller** [comment]
I guess, You are pushing me to build my benchmark code under tikv project. Right?

**Comment by arthurkiller** [comment]
I just a tikv SDK user. [shrug]

**Comment by tiancaiamao** [comment]
If you remove "sirupsen/logrus", and reinstall it ... You may find it actually works.
I usually get into trouble with my computer, so I reboot it, it work!

**Comment by arthurkiller** [comment]
> I usually get into trouble with my computer, so I reboot it, it work!

Ridiculous.
I thing this problem is really clear

![image](https://user-images.githubusercontent.com/11133870/38718741-1ae586d4-3f21-11e8-839d-fb2c3670cf78.png)
![image](https://user-images.githubusercontent.com/11133870/38718756-269701b0-3f21-11e8-8e98-f9de42ab2d33.png)

**Comment by arthurkiller** [comment]
@ngaut @shenli Help wanted. It's really a slice of problem.

**Comment by coocood** [comment]
@arthurkiller 
You can try to add a function `SetLogLevel` in a package under `tidb`, then call that function in your benchmark code.

**Comment by coocood** [comment]
@arthurkiller 
There is a package `util/logutil` in `tidb, you can try this code.
```
        logutil.InitLogger(&logutil.LogConfig{
		Level: logLevel,
	})
```

**Comment by tiancaiamao** [comment]
Modify "$GOPATH/src/github.com/sirupsen/exported.go"

```
func SetLevel(level Level) {
	fmt.Println("SetLevel from GOPATH!!!!!")
	std.mu.Lock()
	defer std.mu.Unlock()
	std.Level = level
}
```

```
// Infoln logs a message at level Info on the standard logger.
func Infoln(args ...interface{}) {
        fmt.Println("Infoln from GOPATH!!!!!!!")
	std.Infoln(args...)
}
```

And modify "$GOPATH/src/github.com/pingcap/tidb/vendor/github.com/sirupsen/logrus/exported.go"

```
func SetLevel(level Level) {
	fmt.Println("SetLevel from TiDB vendor!!!!!")
	std.mu.Lock()
	defer std.mu.Unlock()
	std.Level = level
}
```

```
// Infoln logs a message at level Info on the standard logger.
func Infoln(args ...interface{}) {
        fmt.Println("Infoln from TiDB vendor!!!!!!!")
	std.Infoln(args...)
}
```

I guess it maybe helpful for debugging the problem. @arthurkiller

**Comment by coocood** [comment]
@arthurkiller 
We don't need a PR, the `logutil.InitLogger` function is already there, you can use it directly.

**Comment by arthurkiller** [comment]
Get it, Closed
