### ISSUE TITLE
sysbench 1024 currency test:oltp.sh ,occur the error:mysql_drv_query() returned error 1105 (Information schema is out of date.) for query 'COMMIT'

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6279]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
ALERT: mysql_drv_query() returned error 1105 (Information schema is out of date.) for query 'COMMIT'

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by tiancaiamao** [comment]
Something may help:
1. use lower currency, this error happen when TiKV is overload
2. modify config file, set `lease = "120s"`, and run 
`./tidb-server -config=config/config.toml.example`
