### ISSUE TITLE
sysbench 512 concurrency ,occur the erro:mysql_drv_query() returned error 9005 (Region is unavailable[try again later]) 

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6282]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
ALERT: mysql_drv_query() returned error 9005 (Region is unavailable[try again later]) for query 'SELECT c FROM sbtest3 WHERE id=999149'
FATAL: failed to execute function `event': 3

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by jackysp** [comment]
@duckstar2 , thank you for your feedback. This error mostly means TiKV is overloaded. Please use a lower currency test, or add more TiKV instances.
