### ISSUE TITLE
I want to test tpc-h 1000x performance ,use tispark,use "load data local infile" to import data,select count(*) ocurr the error:Region is unavailable, can recover automatically? 

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6291]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

MySQL [tpch1000x]> select count(*) from customer;
ERROR 9005 (HY000): Region is unavailable[try again later]

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by birdstorm** [comment]
Hi, @duckstar2 
Thanks for your feedback. I would like to know whether you are querying from TiDB or TiSpark. The situation you mention is most probably due to TiKV overloaded. You may try to use lower concurrency level or add more TiKV instances.

**Comment by tiancaiamao** [comment]
Use tispark? I'm a bit confused.
Are you loading date in TiSpark, and do `select count(*)` in TiDB ? @duckstar2

**Comment by duckstar2** [comment]
I didn't use tispark, use "load data local infile" to import data, file is bigger,after finishing a file import ,select count(*) in tidb.
I install 2 tikv in a server ,modfiy block-cache-size,but occurring errors yet

**Comment by tiancaiamao** [comment]
@birdstorm is right.

**Comment by duckstar2** [comment]
I restart tidb cluster ,execute "select count(*) from customer", occur the same error.

**Comment by shenli** [comment]
@duckstar2 Could you show us your Grafana? Without it, we could not tell what is happening.

**Comment by duckstar2** [comment]
I  redeply tidb cluster ,a server install tikv service 。because import data failed using “load data local infile” ，after I  have imported serveral files successfully。 So I try to use loader，this tools only import sql data，for example：insert into sbtest values (1,1),(2,2), cant' import such data ?
1,1
2,2
3,3

**Comment by duckstar2** [comment]
I can't show you  my Grafana, the cluster is in internal network

**Comment by tiancaiamao** [comment]
You can still capture the screen shot of Grafana. @duckstar2

**Comment by duckstar2** [comment]
I upload the png file failed ,I redeploy the cluster ( a server deoploy a tikv service ) and decrease the import data size,now no error

**Comment by duckstar2** [comment]
My server configure are the following:
vcpu:48core
memory:256GB
IO: 23 sas disk ->raid5 
network:10GE
how should I config the tidb cluster?

**Comment by tiancaiamao** [comment]
On one single machine? How about this repository as a quick start?
https://github.com/pingcap/tidb-docker-compose

**Comment by duckstar2** [comment]
not single machine ,9 servers，4tikv，3（pd+tidb），2tidb
if I deploy the cluster ：3（pd+tidb），2tidb，4server（8tikv，2tikv/server)，load data andcount(*) all occur the error : region is unavailable

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
