### ISSUE TITLE
alter table from default null to not null default '' false

### ISSUE THREAD

**Issue by victor-simida** [pingcap/tidb#6304]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
ALTER TABLE `xxx_tab` CHANGE `xxx` `xxx` VARCHAR(200)
 not NULL
 DEFAULT '';
returns: unsupported modify column null to not null
the data in this column is not empty string, but the table structure cannot change it to not null and default ''
2. What did you expect to see?
alter success

3. What did you see instead?
returns: unsupported modify column null to not null

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.0.5-1-g76fccd5
Git Commit Hash: 76fccd5ff26817d3fcced6d964c4c9e7012d8c3e
Git Branch: release-1.0
UTC Build Time: 2017-12-27 08:40:22

**Comment by tiancaiamao** [comment]
Modify column null to not null is not supported in TiDB now. @victor-simida

**Comment by victor-simida** [comment]
well, is it will be supported in the future?

**Comment by victor-simida** [comment]
@tiancaiamao

**Comment by shenli** [comment]
@victor-simida Without locking the table, we could not find a safe way to achieve this. So we do not have a plan now.
