### ISSUE TITLE
I use mydump/loader to import data,sometime give info :db.go:294: [info] checkpoint id:d48445 filename test_loader.item.sql already exists, skip it.

### ISSUE THREAD

**Issue by duckstar2** [pingcap/tidb#6310]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I execute to loader to import data more times,give me the following tip,and no import data
db.go:294: [info] checkpoint id:d48445 filename test_loader.item.sql already exists, skip it.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by zz-jason** [comment]
@duckstar2 Could you please provide us the tidb version and tidb log to help us locate the problem ?

**Comment by duckstar2** [comment]
5.7.10-TiDB-v2.0.0-rc.4-14-g905eda7

**Comment by holys** [comment]
@duckstar2  
1. Loader saves checkpoint data in tidb-server. Its default table is `tidb_loader.checkpoint`.
2. Before restoring data, loader saves the initial values for checkpoint record. It executes the following sql to do this.
```
INSERT INTO tidb_loader.checkpoint (id, filename, cp_schema, cp_table, offset, end_pos) VALUES(?,?,?,?,?)
```
Each table has a record in `tidb_loader.checkpoint`.
3. `checkpoint id:d48445 filename test_loader.item.sql already exists, skip it.`  Means it already has a record before, and tidb-server returns  `ErrDupEntry 1062` error, but we ignore it.

Does it has any problem?

**Comment by holys** [comment]
@duckstar2  If you want to make fresh start, it's better to drop that table(`tidb_loader.checkpoint`) before your restoring.
