### ISSUE TITLE
Insert into int field with '' failed

### ISSUE THREAD

**Issue by calmzealA** [pingcap/tidb#6317]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
CREATE TABLE test(
i1 INT(11),
s1 VARCHAR(16)
)
```

```
INSERT INTO test(i1,s1) VALUES ('11','aa');   //ok

INSERT INTO test(i1,s1) VALUES ('','aa');    //Error 'Data Truncated'

INSERT INTO test(i1,s1) VALUES (NULL,'aa') //ok
```

2. What did you expect to see?

While in mysql 5.7,the following sql returns ok

`INSERT INTO test(i1,s1) VALUES ('','aa'); `

3. What did you see instead?

//Error 'Data Truncated'

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v1.0.6-1-g17c1319
Git Commit Hash: 17c13192136c1f0bf26db6dec994b9f1b43c90f0
Git Branch: release-1.0
UTC Build Time: 2018-01-09 09:07:08

**Comment by PureWhiteWu** [comment]
It comes to me that mysql raises an error:
```
mysql> CREATE TABLE test(
    -> i1 INT(11),
    -> s1 VARCHAR(16)
    -> );
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO test(i1,s1) VALUES ('','aa');
ERROR 1366 (HY000): Incorrect integer value: '' for column 'i1' at row 1
```

My mysql version is 5.7.21

```
mysql> status;
--------------
mysql  Ver 14.14 Distrib 5.7.21, for osx10.13 (x86_64) using  EditLine wrapper

Connection id:		5
Current database:
Current user:		root@localhost
SSL:			Not in use
Current pager:		less
Using outfile:		''
Using delimiter:	;
Server version:		5.7.21-debug Homebrew
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/tmp/mysql.sock
Uptime:			2 min 32 sec

Threads: 1  Questions: 17  Slow queries: 0  Opens: 107  Flush tables: 1  Open tables: 100  Queries per second avg: 0.111
--------------
```

**Comment by zz-jason** [comment]
@PureWhiteWu In the case you present, TiDB behaves the same as MySQL, this error is caused by the strict sql mode, for a work around, you can:
```sql
set @@sql_mode='';
INSERT INTO test(i1,s1) VALUES ('','aa');

```
