### ISSUE TITLE
Does TiDB has backup in default?

### ISSUE THREAD

**Issue by kylezhang** [pingcap/tidb#6329]
Please answer these questions before submitting your issue. Thanks!
tidb默认有没有开启备份

1. What did you do?
If possible, provide a recipe for reproducing the error.
误删数据中数据。

2. What did you expect to see?
tidb默认有没有开启备份，如何恢复误删的数据。

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by shenli** [comment]
@kylezhang The data will not be delete until it meet gc command. Please follow the guide here to read the history data: https://github.com/pingcap/docs/blob/master/op-guide/history-read.md

**Comment by shenli** [comment]
If it is urgent, please enlarge the gc life time first.
update mysql.tidb set variable_value='24h' where variable_name='tikv_gc_life_time'

**Comment by kylezhang** [comment]
是很紧急的；我这里现在用的是默认的配置，没有做其他的配置。
我大约是在今天17:00删除的数据，目前`mysql.tidb`数据如下：
![image](https://user-images.githubusercontent.com/3679798/39045627-f52f1eaa-44c5-11e8-8e88-31195169e90d.png)

**Comment by shenli** [comment]
@kylezhang If so, the data may be already deleted by GC worker. The default lifetime is 10 minutes. So I said that:

> If it is urgent, please enlarge the gc life time first.
update mysql.tidb set variable_value='24h' where variable_name='tikv_gc_life_time'
