### ISSUE TITLE
Support `SELECT ... INTO OUTFILE 'foo'`

### ISSUE THREAD

**Issue by Hoverbear** [pingcap/tidb#6352]
### What did you do?

Tried to export a query output to a file:

```sql
SELECT 1 INTO OUTFILE 'test';
```

### What did you expect to see?

A file created called `test` in the current directory containing `1`.

### What did you see instead?

```
(1105, 'line 1 column 13 near " OUTFILE \'test\'" (total length 28)')
```

### What version of TiDB are you using?

v2.0.0-rc.4-95-gfb8efa

### References

https://dev.mysql.com/doc/refman/8.0/en/select-into.html
https://mariadb.com/kb/en/library/select-into-outfile/

**Comment by holys** [comment]
Seems duplicatded with https://github.com/pingcap/tidb/issues/4350

**Comment by Hoverbear** [comment]
@holys Yes, it's definitely a duplicate. I'm sorry for not searching better before opening this. Would you like me to close this or?
