### ISSUE TITLE
Could not find or access '/home/tidb/tidb-ansible/resources/bin/fio'"

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6359]
**1. What did you do?**

ansible-playbook bootstrap.yml

**2. What did you expect to see?**

**3. What did you see instead?**

ERROR MESSAGE SUMMARY ************************************************************************************
[]: Ansible FAILED! => playbook: bootstrap.yml; TASK: machine_benchmark : deploy fio; message: {"changed": false, "msg": "Could not find or access '/home/tidb/tidb-ansible/resources/bin/fio'"}

**4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?**
tidb_version = v2.0.0-rc.6

**Comment by XuHuaiyu** [comment]
@frwrdt Thank you for your reply, we'll take a look.

**Comment by frwrdt** [comment]
thank you

**Comment by LinuxGit** [comment]
You need to run 'ansible-playbook local_prepare.yml' before bootstrap stage.

**Comment by frwrdt** [comment]
Cannot connect to the external network, so i download the binary package by myself
and did not run  'ansible-playbook local_prepare.yml'

**Comment by frwrdt** [comment]
because i can not run 'ansible-playbook local_prepare.yml', is there other solutions?

**Comment by frwrdt** [comment]
after i create a directory '/home/tidb/tidb-ansible/resources/bin/fio',
then i run 'ansible-playbook bootstrap.yml' again,
it shows as follows

ERROR MESSAGE SUMMARY ***************************************************************************************************************************************
[]: Ansible FAILED! => playbook: bootstrap.yml; TASK: machine_benchmark : Preflight check - Does fio randread iops of deploy_dir disk meet requirement; message: {"changed": false, "msg": "fio: randread iops of deploy_dir disk is too low:  < 8500, it is strongly recommended to use SSD disks for TiKV, TiDB and PD, or there might be performance issues."}

**Comment by frwrdt** [comment]
my disk is not SSD
I add a line ‘machine_benchmark = False’ in tidb-ansible/inventory.ini file
But this is invalid, it still can not skip fio test.
thank you

**Comment by iamxy** [comment]
If you just want to try running TiDB cluster on your development environment, you could try docker-compose.

https://github.com/pingcap/docs/blob/master/op-guide/docker-compose.md

**Comment by GHRuiLiu** [comment]
I have the same problem,  have you solved it? 
randread iops of deploy_dir disk is too low: 3110 < 8500, it is strongly recommended to use SSD disks for TiKV, TiDB and PD, or there might be performance issues

**Comment by jampus** [comment]
me too ...

**Comment by LinuxGit** [comment]
@jampus @GHRuiLiu In test environment, you can set `dev_mode = True`, CPU, memory and disk performance will not be checked when dev_mode = True, False by default. But in production environment, it is strongly recommended to use SSD disks for TiKV, TiDB and PD, or there might be performance issues. See https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md.

**Comment by jampus** [comment]
@LinuxGit thanks, I   sett dev_mode = True, now it is work, 
SSD problem will be discussed later, Although it is now using Amazon's  SSD

**Comment by StoneZoul** [comment]
hello，I am using SSD disk，but it still not fit the requirement... when i do ansible-playbook bootstrap.yml it tells me "fio: randread iops of tikv_data_dir disk is too low: 11406 < 40000, it is strongly recommended to use SSD disks for TiKV and PD, or there might be performance issues."...  

I saw other users report said it requires 8500, but why it requires 40000 in my environment...
