### ISSUE TITLE
questions about general_log

### ISSUE THREAD

**Issue by aesirteam** [pingcap/tidb#6361]
MySQL可以通过设置general_log为“ON”来开启sql记录
TiDB如何记录进入的SQL语句？

原因:
由于将gitlab升级至10.6.4，报错：
Started POST "/projects" for 10.196.230.4 at 2018-04-24 17:05:13 +0800
Processing by ProjectsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "project"=>{"ci_cd_only"=>"false", "namespace_id"=>"2", "path"=>"mbh", "description"=>"", "visibility_level"=>"0"}}
Unable to save project. Error: Mysql2::Error: line 1 column 9 near " active_record_1" (total length 25): SAVEPOINT active_record_1Project ID: 60001

同样的操作在MySQL中是正常的，所以想通过sql语句来查找原因

**Comment by aesirteam** [comment]
tidb version： 2.0.0-rc6

**Comment by XuHuaiyu** [comment]
Seems to be a syntax error, 
you may check the tidb log and grep `parse error` around 17:05:13.

**Comment by aesirteam** [comment]
2018/04/24 16:25:48.232 session.go:809: [warning] [43035] parse error:
line 1 column 9 near " active_record_1" (total length 25)
SAVEPOINT active_record_1
2018/04/24 16:25:48.232 conn.go:481: [warning] [43035] dispatch error:
id:43035, addr:10.196.130.68:44228 status:3, collation:utf8_general_ci, user:root
"SAVEPOINT active_record_1"
line 1 column 9 near " active_record_1" (total length 25)
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/parser/yy_parser.go:106:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/session/session.go:810:
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/server/conn.go:851:

**Comment by shenli** [comment]
`SAVEPOINT active_record_1`. TiDB does not support savepoint now. @aesirteam

**Comment by aesirteam** [comment]
能支持savepoint吗? gitlab源码是这样用的 @shenli

**Comment by shenli** [comment]
We could support savepoint syntax in the parser. But we will not support its behaviour.
