### ISSUE TITLE
The Control Machine must have access to the Internet in order to download TiDB and related packages

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6373]
**1. What did you do?**
i do as 'Offline Deployment Using Ansible doc',
and run 
'cd tidb-ansible
ansible-playbook local_prepare.yml'
to download TiDB-Ansible and TiDB packages **on the download machine**

while the the download machine have access to the Internet

**2. What did you expect to see?**

**3. What did you see instead?**

ERROR MESSAGE SUMMARY ************************************************************************************
[localhost]: Ansible FAILED! => playbook: local_prepare.yml; TASK: local : fail; message: {"changed": false, "msg": "The Control Machine must have access to the Internet in order to download TiDB and related packages."}

thank you

**Comment by LinuxGit** [comment]
The download machine need to access to the Internet. Check it by running command `curl --connect-timeout 10 www.baidu.com`.

**Comment by frwrdt** [comment]
thank you for your reply, it is solved@LinuxGit
