### ISSUE TITLE
compatability issue with mysql

### ISSUE THREAD

**Issue by Jacklli** [pingcap/tidb#6374]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
MySQL [(none)]> SELECT  COALESCE(LOWER(CONV(BIT_XOR(CAST(CRC32(CONCAT_WS('#', `id`, `k`, `c`, `pad`)) AS UNSIGNED)), 10, 16)), 0) AS crc FROM `sbtest1`.`sbtest1` FORCE INDEX (`PRIMARY`) WHERE (1=1);

2. What did you expect to see?
MySQL [(none)]> SELECT  COALESCE(LOWER(CONV(BIT_XOR(CAST(CRC32(CONCAT_WS('#', `id`, `k`, `c`, `pad`)) AS UNSIGNED)), 10, 16)), 0) AS crc FROM `sbtest1`.`sbtest1` FORCE INDEX (`PRIMARY`) WHERE (1=1);
+----------+
| crc           |
+----------+
| 78149c25 |
+----------+
1 row in set (0.72 sec)

3. What did you see instead?
MySQL [(none)]> SELECT  COALESCE(LOWER(CONV(BIT_XOR(CAST(CRC32(CONCAT_WS('#', `id`, `k`, `c`, `pad`)) AS UNSIGNED)), 10, 16)), 0) AS crc FROM `sbtest1`.`sbtest1` FORCE INDEX (`PRIMARY`) WHERE (1=1);
ERROR 2013 (HY000): Lost connection to MySQL server during query

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
MySQL [(none)]> select version();
ERROR 2006 (HY000): MySQL server has gone away
No connection. Trying to reconnect...
Connection id:    88
Current database: *** NONE ***

+------------------------------+
| version()                    |
+------------------------------+
| 5.7.1-TiDB-v1.0.8-1-gaacba4a |
+------------------------------+
1 row in set (0.01 sec)

**Comment by winoros** [comment]
@Jacklli Please provide the table schema.

**Comment by Jacklli** [comment]
@winoros 
create database sbtest1;
use sbtest1;
CREATE TABLE `sbtest1` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `k` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k_1` (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=1030001;

**Comment by winoros** [comment]
This problem have been fixed in master and release-2.0 branch.

**Comment by winoros** [comment]
Open this issue if you meet this problem in current master.
