### ISSUE TITLE
Support “SET NAMES” Syntax

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#6381]
```
SET NAMES {'charset_name'
    [COLLATE 'collation_name'] | DEFAULT}
```
https://dev.mysql.com/doc/refman/8.0/en/set-names.html

**Comment by winkyao** [comment]
@zimulala Please ref to mysql version 5.7 docs.

**Comment by zimulala** [comment]
@winkyao 
Sorry.
https://dev.mysql.com/doc/refman/5.7/en/set-names.html

**Comment by spongedu** [comment]
@winkyao @zimulala  It seems that `SET NAMES` Syntax is already supported. The missing part is the `DEFAULT` option.

**Comment by morgo** [comment]
Fixed in the associated PR https://github.com/pingcap/tidb/pull/6404

I am going to close this issue now.  Please feel free to re-open if you have any followup questions.  Thanks!
