### ISSUE TITLE
how to change 'grafana_servers' in 'tidb-ansible/inventory.ini' when the cluster is started

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6397]
the cluster is started,
i want to cahnge 'grafana_servers' in 'tidb-ansible/inventory.ini'.

How should I do？
thank you!

**Comment by lamxTyler** [comment]
You can stop the cluster, change the `inventory.ini`, then deploy and start the cluster. @frwrdt

**Comment by frwrdt** [comment]
‘ansible-playbook bootstrap.yml’ is not needed?

**Comment by lamxTyler** [comment]
I think it is not needed. @frwrdt

**Comment by frwrdt** [comment]
@lamxTyler  thank you
