### ISSUE TITLE
Timeout when waiting for search string 200 OK in   :2379

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6406]
1. What did you do?

i run '**ansible-playbook start.yml**'

2. What did you expect to see?

3. What did you see instead?

ERROR MESSAGE SUMMARY ********************************************************************
[     ]: Ansible FAILED! => playbook: start.yml; TASK: wait for PD up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in        **:2379**"}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.0.0-rc.6

thank you!

**Comment by winkyao** [comment]
@liubo0127 PTAL

**Comment by frwrdt** [comment]
the message in '{{deploy_dir}}/log/pd.log' on the pd node is

2018/04/27 11:51:21.735 log.go:82: [warning] etcdserver: [could not get cluster response from http://172.18.173.22:2380: Get http://x.x.x.x:2380/members: dial tcp x.x.x.x:2380: connect: connection refused]
2018/04/27 11:51:21.735 etcdutil.go:65: [error] could not retrieve cluster information from the given urls

**Comment by iamxy** [comment]
Hi frwrdt,

1. Please check whether the IP address of PD in your inventory is correct, make sure it's a subnet IP.
2. Check if firewall policy restricts 2379.
3. Check the pd-server on the target machine is running properly, if the process exists, please provide its log.

**Comment by frwrdt** [comment]
actually, there are three PDs,
only one PD is started,
the other two PDs are not started, and it shows

ERROR MESSAGE SUMMARY ********************************************************************
[ ]: Ansible FAILED! => playbook: start.yml; TASK: wait for PD up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in :2379"}
[ ]: Ansible FAILED! => playbook: start.yml; TASK: wait for PD up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in :2379"}

**Comment by frwrdt** [comment]
@iamxy  it is solved, thank you

**Comment by Danier-Evens** [comment]
@frwrdt How do you solve this issue?
