### ISSUE TITLE
Kafka binlog error

### ISSUE THREAD

**Issue by Lee-Think** [pingcap/tidb#6420]
Hi, I try to use kafka binlog according to the guide, but when drainer has started, there are some errors in it's log as follow:
2018/04/28 11:22:51 version.go:18: [info] Git Commit Hash: 7816684370de5d7e18faa19957f8ded02769c4cc
2018/04/28 11:22:51 version.go:19: [info] Build TS: 2018-04-26 03:12:50
2018/04/28 11:22:51 version.go:20: [info] Go Version: go1.10
2018/04/28 11:22:51 version.go:21: [info] Go OS/Arch: linuxamd64
2018/04/28 11:22:51 server.go:75: [info] clusterID of drainer server is 6549329107821014733
2018/04/28 11:23:01 offset.go:117: [error] given position 0 is smaller than oldest message, some binlogs may lose
2018/04/28 11:23:01 collector.go:210: [info] node erp-web-other03:8250 get save point {0 0}
2018/04/28 11:23:11 schema.go:46: [info] [local schema/table] map[]
2018/04/28 11:23:11 schema.go:47: [info] [local schema] map[]
2018/04/28 11:23:11 schema.go:48: [info] [ignore schema] map[]
2018/04/28 11:23:11 file.go:131: [info] ignored file savePoint in wal
2018/04/28 11:23:11 server.go:211: [error] syncer exited, error /home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/binlogfile/file.go:25: binlogger: file not found
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/binlogfile/file.go:115: dir data.drainer
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/executor/pb.go:34: 
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/util.go:135: 
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/syncer.go:560: 
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/drainer/syncer.go:105: 
2018/04/28 11:23:11 server.go:205: [info] syncer goroutine exited 
2018/04/28 11:23:11 server.go:226: [info] heartbeat goroutine exited 
2018/04/28 11:23:11 server.go:307: [error] unregister drainer error context canceled
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/etcd/etcd.go:188: 
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pump/registry.go:125: 
2018/04/28 11:23:11 pump.go:405: [warning] [stream] node erp-web-other03:8250, pos {Suffix:0 Offset:452}, error context canceled
2018/04/28 11:23:14 server.go:177: [info] collect goroutine exited 
2018/04/28 11:23:14 server.go:307: [error] unregister drainer error grpc: the client connection is closing
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pkg/etcd/etcd.go:188: 
/home/jenkins/workspace/build_tidb_binlog_master/go/src/github.com/pingcap/tidb-binlog/pump/registry.go:125: 
2018/04/28 11:23:14 main.go:50: [error] start drainer server error, accept tcp 172.16.46.171:8249: use of closed network connection

Please help me find the reason, thanks!~

**Comment by lamxTyler** [comment]
PTAL @GregoryIan

**Comment by GregoryIan** [comment]
thanks!  it's a corner bug in tidb-binlog, we would fix it.  u can remove data-dir and retry

**Comment by Lee-Think** [comment]
Ok, I removed the dir, then it works.Thank you.
I used generate_binlog_position tool to generate the savepoint before, so there are these errors happened. And I found the generated savepoint's filename is "savePoint"(note in there, "P" is uppercase), but the correct filename should be "savepoint". I guess this different of case is the reason of those errors.
