### ISSUE TITLE
What’s the fastest method to load data to tidb?

### ISSUE THREAD

**Issue by iamjohnnyzhuang** [pingcap/tidb#6431]
您好：
我们有一个程序会从Kafka获取大量的数据然后写入数据库，然后前端程序会定时从数据库查询。
为了保证前端程序查询的实时性需要数据库能达到一定的吞吐量。

上周分别尝试了BATCH INSERT的方式以及LOAD DATA INFILE的方式，发现后者的效率更高。
三台TIKV服务器，一台TIDB/PD服务器。采用LOAD DATA INFILE的方式可以达到6w record/s的吞吐量。请问对于TIDB这是最好的、最快的数据插入方式吗？
如果只是写入性能想要往上提升，只需要扩容TIKV就可以吗？还是TIDB数量也得上去？

非常感谢！

---

(Automated translation)

Hello:
We have a program that gets a lot of data from Kafka and writes it to the database. The front-end program then queries the database periodically.
In order to ensure the real-time performance of front-end program queries, the database can achieve a certain throughput.

Last week tried BATCH INSERT and LOAD DATA INFILE, respectively, and found that the latter is more efficient.
Three TIKV servers and one TIDB/PD server. Using LOAD DATA INFILE can achieve 6w record/s throughput. Is this the best and fastest data insertion method for TIDB?
If you only want to increase the write performance, you only need to expand TIKV? Or the TIDB number has to go up?

thank you very much!

**Comment by lamxTyler** [comment]
Yes, `load data infile` could be better than `insert` because it does not need SQL parsing or some other thing.
You can also get better performance if you add more tidb as indicated by our [bench result](https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md#%E5%9C%BA%E6%99%AF%E4%BA%8Ctidb-%E6%B0%B4%E5%B9%B3%E6%89%A9%E5%B1%95%E8%83%BD%E5%8A%9B%E6%B5%8B%E8%AF%95).
Also, you can refer to our [best practice](https://pingcap.com/blog-cn/tidb-best-practice/) to get better performance.

**Comment by iamjohnnyzhuang** [comment]
@lamxTyler 
Thank you very much for your prompt reply, after trying today I found there's an odd question, I use the LOAD DATA LOCAL INFILE way to load a 100000 line DATA file (about 18 MB) to a table of TIDB, this table without any index.
If I use mysql shell client or Navicat, this operation only takes 4 seconds to 6 seconds, but if I use JDBC, it will last 25 seconds!
The MySQL driver package I am using version is 5.1.29. At the same time, I try the same action to mysql, I get the same result.
Is it may related to TIDB?

Here is my jdbc code:
``` java
		// ... init code
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn = DriverManager.getConnection(connectStr, username, password);

        long now = System.currentTimeMillis();
        PreparedStatement pstmt = conn.prepareStatement("LOAD DATA LOCAL INFILE '/tmp/performance/data.txt' INTO TABLE `MONITOR-DNSMAPCHK`;");
        pstmt.execute();
        conn.commit();
        System.out.println(System.currentTimeMillis() - now);
        // ... close code
```

**Comment by lamxTyler** [comment]
@iamjohnnyzhuang  I guess the reason is that tidb will read one packet, process it, then read another packet, so if the packet size is small, there will be a lot network cost, which results in bad performance. Could you try to increase the jdbc packet size and try again?

**Comment by iamjohnnyzhuang** [comment]
@lamxTyler 
Yes, I used tcpdump command found that there's packet on jdbc likely smaller than shell command. 
But I have searched on the internet and couldn't find the configs to increase the packet size of jdbc.

Would you mind tell me how to increase the jdbc packaet packet size? 

Thanks!

**Comment by lamxTyler** [comment]
@iamjohnnyzhuang I am sorry that I do not know how to increase it. The only thing that I found may be useful is https://docs.oracle.com/database/121/JJDBC/apxtips.htm#JJDBC28954

**Comment by iamjohnnyzhuang** [comment]
@lamxTyler
I have review the jdbc code of mysql-connector-java and found there it's send a package of 1MB ever times. maybe this is the of the slow performance.

If I'm using java, it's there something jdbc driver to be recommanding to use with tidb ?

**Comment by iamjohnnyzhuang** [comment]
I change the driver to mariadb-java-client (2.2.3) the speed is almost the same as shell client

**Comment by lamxTyler** [comment]
@iamjohnnyzhuang  Glad to hear that!

**Comment by iamjohnnyzhuang** [comment]
Thank you for your help very much!
