### ISSUE TITLE
WriteConflict when using Sqoop to export data from hdfs to tidb 

### ISSUE THREAD

**Issue by Lyle-liang** [pingcap/tidb#6434]
Please answer the question, thanks!

1. sqoop export --connect 'jdbc:mysql://host:4000/db' --username 'root' --table testTable --export-dir 'hdfs://test/' --input-fields-terminated-by '\001' --lines-terminated-by '\n' --input-null-string '\\N' --input-null-non-string '\\N' --update-mode allowinsert --update-key id -m 3

2. error log
![image](https://user-images.githubusercontent.com/14850448/39503521-faed6658-4df8-11e8-8013-1fe275583fb6.png)

3. How to deal with it？

**Comment by zhexuany** [comment]
@Lyle-liang It seems like you tried to insert same data twice? If that is the case, please try drop table and retry insert again.

**Comment by Lyle-liang** [comment]
@zhexuany the table is synchronizing data in real time，so what you said can not do. Do you have another solution？

**Comment by coocood** [comment]
@Lyle-liang 
Can you provide the corresponding TiDB log? you can use the value of start_ts as a keyword.

**Comment by Lyle-liang** [comment]
I try again and work well. nothing change.

**Comment by coocood** [comment]
@Lyle-liang 
closed for now, feel free to reopen it if the error happens again.
