### ISSUE TITLE
Does TIDB suitable for monitoring system to store and query monitoring data?

### ISSUE THREAD

**Issue by iamjohnnyzhuang** [pingcap/tidb#6440]
您好，
我们的监控系统早期使用MySQL作业监控数据存储，并且通过一个前端程序定时查询一系列SQL大量如：GROUP BY / LEFT JOIN 的语句。
现在考虑使用TIDB来取代MYSQL。我们的监控数据大概每秒20MB的数据量，不同的数据会存储于不同的表里，前端程序定时30s执行一次，一次大概有几百条的SQL语句。

目前已经对TIDB做了很多性能测试，但是从结果来看还不能完全确认是否满足我们的业务条件，请问tidb是否能符合我上述的业务场景呢？ 谢谢！

**Comment by coocood** [comment]
@iamjohnnyzhuang 
Thank you for evaluating TiDB!

Please answer the following questions:
1. Which version of TiDB did you test?
2. What is the hardware (Memory, SSD) environment?
3. Have you performed 'ANALYZE TABLE' statement before query?
4. What's the result and the expected result?

**Comment by iamjohnnyzhuang** [comment]
@coocood  
Hello，
1. Which version of TiDB did you test?
we use the newest version of tidb now.
2. What is the hardware (Memory, SSD) environment?
Centos 7  Memory：96G   SSD:1T
3. Have you performed 'ANALYZE TABLE' statement before query?
No, we just test by some simple sql,and now we just wonder whether this can meet our business requirements (20MB insert into per second, and nearly 1000 concurrent query)
4. What's the result and the expected result?
We expect to load 20 0000 messages into tidb per second,and 1000 concurrent query that get result under 1 second.

Thank you very much !

**Comment by coocood** [comment]
@iamjohnnyzhuang 
TiDB is not optimized for time series data for now, but it doesn't mean TiDB cannot handle it.
Can you provide the table schema and query statements?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
