### ISSUE TITLE
GC failed when TiKV Coprocessor is busy

### ISSUE THREAD

**Issue by zhangjinpeng1987** [pingcap/tidb#6448]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

2. What did you expect to see?
GC will never failed when TiKV's Coprocessor is busy.

3. What did you see instead?
GC will failed when TiKV's Coprocessor is busy.
```
2018/05/03 08:37:46.781 gc_worker.go:322: [error] [gc worker] 58b5f70ee280010 delete range returns an error [tikv:9003]TiKV server is busy[try again later]
/home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/store/tikv/gcworker/gc_worker.go:345:
```
I think here we should use high priority to load informations that GC needed.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.0-GA

**Comment by zhangjinpeng1987** [comment]
When TiKV's coprocessor is busy, checking GC leader also can failed.
```
2018/05/03 07:40:51.905 gc_worker.go:183: [warning] [gc worker] check leader err: [tikv:9003]TiKV server is busy[try again later]
```

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to open a new issue if you continue to experience issues. Thanks!
