### ISSUE TITLE
Cast function should not fail.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#645]
`select cast("-1" as UNSIGNED)` should return `18446744073709551615`, but we get "constant -1 overflows bigint" error.

This is because we use `Convert` function for cast, but actually `cast` works differently than `convert`.
`cast("xxx" as DATETIME)` should returns NULL, but `Convert` such an invalid time string returns zero time.

**Comment by qiuyesuifeng** [comment]
`select cast("-1" as UNSIGNED)` there will get an warning.
```
mysql> select cast("-1" as UNSIGNED);
+------------------------+
| cast("-1" as UNSIGNED) |
+------------------------+
|   18446744073709551615 |
+------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> show warnings;
+---------+------+-------------------------------------------------------------------------+
| Level   | Code | Message                                                                 |
+---------+------+-------------------------------------------------------------------------+
| Warning | 1105 | Cast to unsigned converted negative integer to it's positive complement |
+---------+------+-------------------------------------------------------------------------+
1 row in set (0.00 sec)
```
I think we should use error for type cast, like `18446744073709551615` is meaningless and it is difficult to do the same with MySQL.
