### ISSUE TITLE
Postgresql Support

### ISSUE THREAD

**Issue by posix4e** [pingcap/tidb#6459]
This is not a bug it's a feature! I am requesting postgreql suport via FDW. BTW I generated the capability to do PG FDW via Rust! https://github.com/posix4e/rpgffi. We probably don't wanna do this as a part of tidb though.
Some projects which use this code

- https://github.com/instructure/jsoncdc
- https://github.com/durch/google-bigtable-postgres-fdw

**Comment by posix4e** [comment]
I’d suggest an intermediate goal of a foriegn data wrapper.

**Comment by ilovejs** [comment]
Could possibly need tidb as cache layer first. Materialized view development in postgres is hard due to aggregation, sorting. Child view depends on parent view so any change would require to be changed.. Althrough, people can use table to replace view. But sometime AWS Aurora under large stress, database won't be back online anymore.

Its read replica during master DDL, will lock up...so session number went up to max..

Would you guys think of these user case ?

Thanks 💯

**Comment by posix4e** [comment]
I think not starting with a simple Fdw is hard.

**Comment by codelipenghui** [comment]
@shenli

**Comment by eurekaka** [comment]
@codelipenghui Here is the link of the [roadmap](https://www.pingcap.com/docs-cn/ROADMAP/), PostgreSQL protocol compatibility is not in our short term schedule.

**Comment by codelipenghui** [comment]
@eurekaka thanks.

**Comment by ForsakenHarmony** [comment]
What made you chose mysql over postgres support?

**Comment by eurekaka** [comment]
@shenli please help explain a little bit about the protocol choice, thanks.

**Comment by morgo** [comment]
@ForsakenHarmony in the MySQL-world it is very common to shard databases.  We targeted MySQL support first because we have something to offer their users.

**Comment by kaushalyap** [comment]
Any progress with this?

**Comment by scsldb** [comment]
Short to medium term focus on MySQL compatibility, no plans yet.

**Comment by xiaods** [comment]
cool feature. can't wait for it.

**Comment by alexshen-oda** [comment]
Dear friends,

Hope this project is the nice thing you are looking for.

https://github.com/DigitalChinaOpenSource/TiDB-for-PostgreSQL

**Comment by xqianer** [comment]
Maybe you can look at following projects, communications and contributions are welcomed.
https://github.com/DigitalChinaOpenSource/TiDB-for-PostgreSQL
https://github.com/DigitalChinaOpenSource/DCParser

**Comment by xavier83** [comment]
> Dear friends,
> 
> Hope this project is the nice thing you are looking for.
> 
> https://github.com/DigitalChinaOpenSource/TiDB-for-PostgreSQL

Cool! Now I can get wire compatibility for the following with a single TiDB data-store.:stuck_out_tongue_closed_eyes:  :rofl: 
* MySQL natively from TiDB.
* MangoDB via https://github.com/MangoDB-io/MangoDB
* PostgreSQL via https://github.com/DigitalChinaOpenSource/TiDB-for-PostgreSQL
