### ISSUE TITLE
Anyway to delete records in table quickly?

### ISSUE THREAD

**Issue by cnwarden** [pingcap/tidb#6469]
I want to delete "expired" records in db ( like memory db, items expire in certain time), is there anyway to make it? 

or I have to "delete * from xxx where updated_at < xxxx"? is it effective way to make it?

thanks！

**Comment by shenli** [comment]
The only way is using `delete` statement.

**Comment by cnwarden** [comment]
how about the performance of batch delete? I need delete 300Million records per day. and how I do? thanks.

**Comment by coocood** [comment]
@cnwarden 
Please take a look at https://github.com/pingcap/docs/blob/master/FAQ.md#what-is-the-most-efficient-way-of-deleting-data
