### ISSUE TITLE
TIDB Syncer DDL can't be skipped

### ISSUE THREAD

**Issue by cnwarden** [pingcap/tidb#6471]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do?**
If possible, provide a recipe for reproducing the error.

using syncer, I want to skip DDL like truncate. config like this.

skip-ddls = ["TRUNCATE TABLE", "CREATE TABLE"]

but 
when I truncate in master mysql database, syncer log shows table truncated:
2018/05/04 12:54:57 syncer.go:642: [info] [ddl][schema]xxx [start]TRUNCATE TABLE `dc`.`table_xxx`
2018/05/04 12:55:01 meta.go:120: [info] save position to file, binlog-name:mysql-bin.001787 binlog-pos:1003903178 binlog-gtid:
2018/05/04 12:55:01 syncer.go:650: [info] [ddl][end]TRUNCATE TABLE `dc`.`table_xxx`

and I verified data, the downstream tidb is truncated.

**2. What did you expect to see?**

TIDB won't truncated.

**Comment by coocood** [comment]
@cnwarden 
Thank you for your feedback!

@WangXiangUSTC PTAL

**Comment by cnwarden** [comment]
Is syncer on github? I need this feature :), so I want to make some change ASAP.

**Comment by holys** [comment]
@cnwarden  Syncer currently doesn't support skipping ddl like  `TRUNCATE TABLE`, `CREATE TABLE` which can be parsed by tidb parser. It's likely to be supported in the near future.

**Comment by cnwarden** [comment]
@holys @coocood is it possible to make syncer open source? I want to modify it for a few features.

**Comment by zhexuany** [comment]
Making syncer opensure is not feasible. It is belong to our business tool.

**Comment by 564064202** [comment]
when there is a create table ddl sql, syncer will Fall into a Infinite loop
