### ISSUE TITLE
TiDB Ansible restart failed

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6479]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

the TiDB cluster has been run for several days,
i stopped it to change '/export/deploy/conf/tikv.toml' on the tikv node,
then i run 'ansible-playbook start.yml' on the monitoring server

2. What did you expect to see?

3. What did you see instead?

ERROR MESSAGE SUMMARY ********************************************************************
[]: Ansible FAILED! => playbook: start.yml; TASK: wait for TiKV up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for PID:/export/deploy/status/tikv.pid to stop."}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by LinuxGit** [comment]
You need to use download latest tidb-ansible release-2.0 branch and confirm that thread_name_regex='tikv-server' in https://github.com/pingcap/tidb-ansible/blob/release-2.0/start.yml#L173. Or you need to check if tikv instance is running.

**Comment by frwrdt** [comment]
1. Can i just replace 'start.yml' ?

2.  tikv instance is not running

**Comment by LinuxGit** [comment]
It's better to update tidb-ansible, you can refer to https://github.com/pingcap/docs/blob/master/op-guide/tidb-v2-upgrade-guide.md.

There're start/stop scripts in your $deploy_dir/scripts（/export/deploy/scripts）: start_tikv.sh  and stop_tikv.sh.

**Comment by LinuxGit** [comment]
It seems that your tidb instance is not running. You can check it by hand.

**Comment by frwrdt** [comment]
the message in '/export/deploy/log/tidb.log' is

2018/05/07 13:41:47.854 region_cache.go:470: [info] drop regions of store 1 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2018/05/07 13:41:47.918 region_cache.go:470: [info] drop regions of store 4 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable
2018/05/07 13:41:48.077 region_cache.go:470: [info] drop regions of store 5 from cache due to request fail, err: rpc error: code = Unavailable desc = grpc: the connection is unavailable

**Comment by frwrdt** [comment]
i store delete 1,4,5,
restart failed still

**Comment by frwrdt** [comment]
i update tidb-ansible
thank you @LinuxGit

**Comment by frwrdt** [comment]
i restart the cluster several times, but it fails in most cases,
i will cost a lot of time to find the solutions which are different every time,
so,
what's the proper method to stop/restart the cluster?
before i stop the cluster, what can i do?
thank you
