### ISSUE TITLE
Performance issues of 'order by limit'

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6493]
1. What did you do?

i test TiDB with two queries,

**query1**  'select * from table_name where column1='xxx' order by column2 limit **100**;'
**query2**  'select * from table_name where column1='xxx' order by column2 limit **10000**;'

where 'column1' is index，'column2 ' is not index

i run **query2** first, then i run **query1**

2. What did you expect to see?

the time cost by query1 is shorter than query2

3. What did you see instead?

the time cost by query1 is longer than query2

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by winoros** [comment]
Please provide the explain result.
And do you analyze the table before run sql?

**Comment by frwrdt** [comment]
MySQL [test]> EXPLAIN select * from table_name where column1='xxx' order by column2 limit 100;
+----------------+--------------+----------------+------+----------------------------------------------------------------------------------------------+-----------+
| id             | parents      | children       | task | operator info                                                                                | count     |
+----------------+--------------+----------------+------+----------------------------------------------------------------------------------------------+-----------+
| IndexScan_39   |              |                | cop  | table:table_name, index:column2, column3, range:[<nil>,+inf], keep order:true                | 100000.00 |
| TableScan_40   | Selection_41 |                | cop  | table:table_name, keep order:false                                                           | 100000.00 |
| Selection_41   |              | TableScan_40   | cop  | eq(test.table_name.column1, xxx)                                                             | 100.00    |
| IndexLookUp_44 | Limit_12     |                | root | index:IndexScan_39, table:Selection_41                                                       | 100.00    |
| Limit_12       | Projection_7 | IndexLookUp_44 | root | offset:0, count:100                                                                          | 100.00    |
+----------------+--------------+----------------+------+----------------------------------------------------------------------------------------------+-----------+
6 rows in set (0.00 sec)



MySQL [test]> EXPLAIN select * from table_name where column1='xxx' order by column2 limit 10000;
+----------------+---------+----------------+------+------------------------------------------------------------------------------------------------------------+------------+
| id             | parents | children       | task | operator info                                                                                              | count      |
+----------------+---------+----------------+------+------------------------------------------------------------------------------------------------------------+------------+
| IndexScan_20   |         |                | cop  | table:table_name, index:column1, column4, range:[xxx,xxx], keep order:false                                | 2423706.59 |
| TableScan_21   | TopN_22 |                | cop  | table:table_name, keep order:false                                                                         | 2423706.59 |
| TopN_22        |         | TableScan_21   | cop  | test.table_name.column2:asc, offset:0, count:10000                                                         | 10000.00   |
| IndexLookUp_23 | TopN_9  |                | root | index:IndexScan_20, table:TopN_22                                                                          | 10000.00   |
| TopN_9         |         | IndexLookUp_23 | root | test.table_name.column2:asc, offset:0, count:10000                                                         | 10000.00   |
+----------------+---------+----------------+------+------------------------------------------------------------------------------------------------------------+------------+
5 rows in set (0.00 sec)

**Comment by winoros** [comment]
@frwrdt  Seems that the analyze didn't execute completely.
You can `curl http://TIDB_IP:TIDB_PORT/stats/dump/dbName/tableName`  to dump the stats and upload it.
Then you can try to analyze the table to see the problem is fixed or not.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
