### ISSUE TITLE
Ansible deploy Syntax Error

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6501]
1. What did you do?

i configure some parameters in  'tidb-ansible/conf/tikv.yml',
then i run 'ansible-playbook deploy.yml'

2. What did you expect to see?

3. What did you see instead?

ERROR MESSAGE SUMMARY ****************************************************************************************************************
[]: Ansible FAILED! => playbook: deploy.yml; TASK: tikv : load customized config; message: {"ansible_facts": {"tikv_conf_custom": {}}, "ansible_included_var_files": [], "changed": false, "message": "Syntax Error while loading YAML.\n  did not find expected key\n\nThe error appears to have been in 'True': line 270, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\n(could not open file to display line)"}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by frwrdt** [comment]
this error occurs when i configure ‘max-background-jobs’

**Comment by LinuxGit** [comment]
It reported yaml syntax error.  You can check if the indentation is correct and using colon after max-background-jobs .
```
rocksdb:
  # Maximum number of concurrent background jobs (compactions and flushes)
  max-background-jobs: 8
```

**Comment by frwrdt** [comment]
@LinuxGit thank you
