### ISSUE TITLE
query so slow!

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#6528]
tidb v2.0.0
mysql> select * from spider where ts_update <= "2018-05-10 17:52:00" and name = "Noseshore" limit 10;
+-----------------+-----------+----------------------------------------+----------------+---------+---------------------+
| uid | name | url | content | extend | ts_update |
+-----------------+-----------+----------------------------------------+----------------+---------+---------------------+
| 2f9ea39e5c0f000 | Noseshore | http://2.43.51.187/Buffalo City | Madison Pkwy | {"a":1} | 2018-05-10 14:35:34 |
| 2f9ebddf9002000 | Noseshore | http://164.179.194.124/Derby Center | Madison Rd | {"a":1} | 2018-05-10 14:42:44 |
| 2f9ec3500c0a001 | Noseshore | http://140.145.148.250/San Martin | Madison Trl | {"a":1} | 2018-05-10 14:44:13 |
| 2f9ef6f4dc03000 | Noseshore | http://34.168.111.40/Newstead | Jefferson Rdg | {"a":1} | 2018-05-10 14:58:19 |
| 2f9ef8da800f000 | Noseshore | http://85.85.89.197/Buffalo City | Jackson Circle | {"a":1} | 2018-05-10 14:58:50 |
| 2f9efc2c340a000 | Noseshore | http://230.20.7.55/Bury | Franklin Ct | {"a":1} | 2018-05-10 14:59:45 |
| 2f9eab2e600a001 | Noseshore | http://110.250.116.68/Kingsbridge | Wilson Ave | {"a":1} | 2018-05-10 14:37:38 |
| 2f9ead895401000 | Noseshore | http://121.131.139.195/Skidaway Island | Franklin Pl | {"a":1} | 2018-05-10 14:38:16 |
| 2f9ee56be00a000 | Noseshore | http://168.240.27.126/Baldock | Madison Pkwy | {"a":1} | 2018-05-10 14:53:32 |
| 2f9ee55399f7000 | Noseshore | http://169.44.40.106/Lucien | Adams Rdg | {"a":1} | 2018-05-10 14:53:39 |
+-----------------+-----------+----------------------------------------+----------------+---------+---------------------+
10 rows in set (0.01 sec)

mysql> select * from spider where ts_update <= "2018-05-10 17:52:00" and name = "Noseshore" limit 10;
+-----------------+-----------+-------------------------------------+----------------+---------+---------------------+
| uid | name | url | content | extend | ts_update |
+-----------------+-----------+-------------------------------------+----------------+---------+---------------------+
| 2f9ea39e5c0f000 | Noseshore | http://2.43.51.187/Buffalo City | Madison Pkwy | {"a":1} | 2018-05-10 14:35:34 |
| 2f9ef6f4dc03000 | Noseshore | http://34.168.111.40/Newstead | Jefferson Rdg | {"a":1} | 2018-05-10 14:58:19 |
| 2f9ef8da800f000 | Noseshore | http://85.85.89.197/Buffalo City | Jackson Circle | {"a":1} | 2018-05-10 14:58:50 |
| 2f9efc2c340a000 | Noseshore | http://230.20.7.55/Bury | Franklin Ct | {"a":1} | 2018-05-10 14:59:45 |
| 2f9ec6590805000 | Noseshore | http://12.128.198.84/Baldock | Madison Ave | {"a":1} | 2018-05-10 14:45:03 |
| 2f9ec7561c06000 | Noseshore | http://185.19.81.46/Bury | Wilson Ct | {"a":1} | 2018-05-10 14:45:19 |
| 2f9eca1c1408001 | Noseshore | http://46.165.57.11/Skidaway Island | Adams Blvd | {"a":1} | 2018-05-10 14:46:05 |
| 2f9eec7b3801000 | Noseshore | http://77.246.4.5/Derby Center | Jackson Ave | {"a":1} | 2018-05-10 14:55:28 |
| 2f9ed968d5f6002 | Noseshore | http://86.10.68.205/Bury | Wilson St | {"a":1} | 2018-05-10 14:50:15 |
| 2f9edbf999f8000 | Noseshore | http://64.241.58.220/Northleach | Madison Trl | {"a":1} | 2018-05-10 14:50:57 |
+-----------------+-----------+-------------------------------------+----------------+---------+---------------------+
10 rows in set (4.50 sec)

15% the query   is taking long time 
3000 insert per seconds

**Comment by winoros** [comment]
@474420502 Please provide schema(at least the index information). and the explain result of this two sql.

**Comment by 474420502** [comment]
@winoros 
CREATE TABLE `spider` (
      `uid` tinytext NOT NULL,
      `name` tinytext DEFAULT NULL,
      `url` text DEFAULT NULL,
      `content` blob DEFAULT NULL,
      `extend` json DEFAULT NULL,
      `ts_update` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
      UNIQUE KEY `uidx_uid` (`uid`(16)),
      KEY `idx_name` (`name`(6)),
      KEY `idx_url` (`url`(20)),
      KEY `idx_ts_update` (`ts_update`)

) DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

mysql> explain    select * from spider where ts_update <= "2018-05-10 19:55:15" and name = "Noseshore" limit 1 \G
*************************** 1. row ***************************
           id: IndexScan_19
      parents: 
     children: 
         task: cop
operator info: table:spider, index:name, range:[[78 111 115 101 115 104],[78 111 115 101 115 104]], keep order:false
        count: 0.00
*************************** 2. row ***************************
           id: TableScan_20
      parents: Selection_21
     children: 
         task: cop
operator info: table:spider, keep order:false
        count: 0.00
*************************** 3. row ***************************
           id: Selection_21
      parents: Limit_25
     children: TableScan_20
         task: cop
operator info: eq(log.spider.name, Noseshore), le(log.spider.ts_update, 2018-05-10 19:55:15.000000)
        count: 0.00
*************************** 4. row ***************************
           id: Limit_25
      parents: 
     children: Selection_21
         task: cop
operator info: offset:0, count:1
        count: 0.00
*************************** 5. row ***************************
           id: IndexLookUp_26
      parents: Limit_9
     children: 
         task: root
operator info: index:IndexScan_19, table:Limit_25
        count: 0.00
*************************** 6. row ***************************
           id: Limit_9
      parents: 
     children: IndexLookUp_26
         task: root
operator info: offset:0, count:1
        count: 0.00

**Comment by winoros** [comment]
@474420502 Thanks
Have you analyzed this table?
What's the explain result if you add index hint `use index(idx_ts_update)`.

**Comment by 474420502** [comment]
@winoros 
mysql> select * from spider USE INDEX(idx_ts_update)  where ts_update <= "2018-05-10 19:55:15" and name = "Noseshore"  limit 10;
+-----------------+-----------+----------------------------------------+------------------+---------+---------------------+
| uid             | name      | url                                    | content          | extend  | ts_update           |
+-----------------+-----------+----------------------------------------+------------------+---------+---------------------+
| 2f9ea39e5c0f000 | Noseshore | http://2.43.51.187/Buffalo City        | Madison Pkwy     | {"a":1} | 2018-05-10 14:35:34 |
| 2f9eab2e600a001 | Noseshore | http://110.250.116.68/Kingsbridge      | Wilson Ave       | {"a":1} | 2018-05-10 14:37:38 |
| 2f9ead895401000 | Noseshore | http://121.131.139.195/Skidaway Island | Franklin Pl      | {"a":1} | 2018-05-10 14:38:16 |
| 2f9eb0cce80a000 | Noseshore | http://204.169.221.103/Northleach      | Jefferson Circle | {"a":1} | 2018-05-10 14:39:10 |
| 2f9f0b9df00a000 | Noseshore | http://47.40.147.254/Ransom Canyon     | Adams Rd         | {"a":1} | 2018-05-10 15:03:58 |
| 2f9f11907c07001 | Noseshore | http://58.229.79.124/Brandwell         | Washington Pkwy  | {"a":1} | 2018-05-10 15:05:35 |
| 2f9f17951c02000 | Noseshore | http://65.120.94.16/Northleach         | Adams St         | {"a":1} | 2018-05-10 15:07:14 |
| 2f9f1de1b00e001 | Noseshore | http://183.102.118.28/Berkhamsted      | Lincoln St       | {"a":1} | 2018-05-10 15:08:57 |
| 2f9f221cf004000 | Noseshore | http://55.241.106.47/Kingsbridge       | Jefferson Trl    | {"a":1} | 2018-05-10 15:10:06 |
| 2f9ee2983404002 | Noseshore | http://125.95.198.103/Ransom Canyon    | Wilson Ct        | {"a":1} | 2018-05-10 14:52:46 |
+-----------------+-----------+----------------------------------------+------------------+---------+---------------------+
10 rows in set (24.26 sec)

mysql> explain select * from spider USE INDEX(idx_ts_update)  where ts_update <= "2018-05-10 19:55:
+----------------+--------------+----------------+------+-----------------------------------------------------------------------------------+-------------+
| id             | parents      | children       | task | operator info                                                                     | count       |
+----------------+--------------+----------------+------+-----------------------------------------------------------------------------------+-------------+
| IndexScan_13   |              |                | cop  | table:spider, index:ts_update, range:[-inf,2018-05-10 19:55:15], keep order:false | 15930657.00 |
| TableScan_14   | Selection_15 |                | cop  | table:spider, keep order:false                                                    | 15930657.00 |
| Selection_15   | Limit_16     | TableScan_14   | cop  | eq(log.spider.name, Noseshore)                                                    | 0.00        |
| Limit_16       |              | Selection_15   | cop  | offset:0, count:10                                                                | 0.00        |
| IndexLookUp_17 | Limit_9      |                | root | index:IndexScan_13, table:Limit_16                                                | 0.00        |
| Limit_9        |              | IndexLookUp_17 | root | offset:0, count:10                                                                | 0.00        |
+----------------+--------------+----------------+------+-----------------------------------------------------------------------------------+-------------+
6 rows in set (0.00 sec)

**Comment by 474420502** [comment]
@winoros is very very slow!

**Comment by 474420502** [comment]
I had analyzed this table so many times! :smile:  
But i feel i had know the reason. 
The query aways use single index.

**Comment by 474420502** [comment]
mysql> explain select * from spider use index(idx_ts_update_name) where ts_update <= "2018-05-12 15:02:36" and name = "Musesunrise" limit 1\G
*************************** 1. row ***************************
           id: IndexScan_13
      parents: 
     children: 
         task: cop
operator info: table:spider, index:ts_update, name, range:[-inf,2018-05-12 15:02:36], keep order:false
        count: 13044500.00
*************************** 2. row ***************************
           id: TableScan_14
      parents: Selection_15
     children: 
         task: cop
operator info: table:spider, keep order:false
        count: 13044500.00
*************************** 3. row ***************************
           id: Selection_15
      parents: Limit_16
     children: TableScan_14
         task: cop
operator info: eq(log.spider.name, Musesunrise)
        count: 0.00
*************************** 4. row ***************************
           id: Limit_16
      parents: 
     children: Selection_15
         task: cop
operator info: offset:0, count:1
        count: 0.00
*************************** 5. row ***************************
           id: IndexLookUp_17
      parents: Limit_9
     children: 
         task: root
operator info: index:IndexScan_13, table:Limit_16
        count: 0.00
*************************** 6. row ***************************
           id: Limit_9
      parents: 
     children: IndexLookUp_17
         task: root
operator info: offset:0, count:1
        count: 0.00
6 rows in set (0.01 sec)

mysql> select * from spider use index(idx_ts_update_name) where ts_update <= "2018-05-12 15:02:36" and name = "Musesunrise" limit 1;
+-----------------+-------------+--------------------------------------+-------------+---------+---------------------+
| uid             | name        | url                                  | content     | extend  | ts_update           |
+-----------------+-------------+--------------------------------------+-------------+---------+---------------------+
| 2fc65fe5f002000 | Musesunrise | http://199.45.68.223/Skidaway Island | Jackson Ave | {"a":1} | 2018-05-12 12:53:17 |
+-----------------+-------------+--------------------------------------+-------------+---------+---------------------+
1 row in set (20.44 sec)

Index on this two column .
But it is very very very very slow!

**Comment by winoros** [comment]
@474420502 The index in tidb is stored by order. So for one index(a, b, c). the filter on b won't be used for seeking range unless the condition on `a` is equal condition.
So for your sql, you should build index `(name, ts_update)` instead of `(ts_update, name)`

**Comment by 474420502** [comment]
mysql> select * from spider use index(idx_name_ts_update)  where  ts_update <= "2018-05-13 21:48:36"  and name = "Wyrmplum" limit 1;
^[[A+-----------------+----------+------------------------------------+--------------+---------+---------------------+
| uid             | name     | url                                | content      | extend  | ts_update           |
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
| 2fcfe89c6009001 | Wyrmplum | http://224.187.234.10/Buffalo City | Jackson Blvd | {"a":1} | 2018-05-12 23:59:45 |
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
1 row in set (0.44 sec)

mysql> select * from spider use index(idx_name_ts_update)  where  ts_update <= "2018-05-13 21:48:36"  and name = "Wyrmplum" limit 1;
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
| uid             | name     | url                                | content      | extend  | ts_update           |
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
| 2fcfe89c6009001 | Wyrmplum | http://224.187.234.10/Buffalo City | Jackson Blvd | {"a":1} | 2018-05-12 23:59:45 |
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
1 row in set (1.35 sec)

mysql> select * from spider use index(idx_name_ts_update)  where  ts_update <= "2018-05-13 21:48:36"  and name = "Wyrmplum" limit 1;
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
| uid             | name     | url                                | content      | extend  | ts_update           |
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
| 2fcfe89c6009001 | Wyrmplum | http://224.187.234.10/Buffalo City | Jackson Blvd | {"a":1} | 2018-05-12 23:59:45 |
+-----------------+----------+------------------------------------+--------------+---------+---------------------+
1 row in set (0.02 sec)

I think it needs to be optimized！
I test Myrocks in the same condition.
Myrocks is running very well!

**Comment by winoros** [comment]
@474420502 May i know that how you create the index? i.e. The sql you used to create index.

**Comment by 474420502** [comment]
@winoros  
create index idx_name_ts_update on spider (name, ts_update);

**Comment by winoros** [comment]
@474420502 
`name` is a `tinytext` field. So when you create index, you need to specify key length. 
If the length you set cannot cover the filter condition(i.e. shorter than the filter you used). TiDB will need to seek it in index and then seek again in table. This will definitely cost a lot more than 
stand-alone database.

**Comment by 474420502** [comment]
@winoros create index idx_name_ts_update on spider (name(6), ts_update);
I forget it. in fact, i had add it;
I had known why slow.
But I think  the optimization   of myrocks is better than  tidb;

**Comment by winoros** [comment]
@474420502 
We'll make continuous improvement. Thanks for your reporting!
If you have some more questions, feel free to open new issue.
