### ISSUE TITLE
offline store can't be up 

### ISSUE THREAD

**Issue by frwrdt** [pingcap/tidb#6533]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
i store delete 1,2,7
then i run 'curl -X POST "http://pd-addr:2379/pd/api/v1/store/1/state?state=Up"'

2. What did you expect to see?

3. What did you see instead?
i wait some time, but the stores on grafana  are still offline

when i check the "state_name"  with pd-ctl, it shows 
"state_name": "Up"
for 3 store

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by disksing** [comment]
pd-ctl shows _Up_ means the state is already updated.
The reason you can still see the offline store on grafana could be you are not viewing the leader's metrics. You can select current leader instance from the top-left most drop list.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
