### ISSUE TITLE
build failed on i386

### ISSUE THREAD

**Issue by di3663** [pingcap/tidb#6538]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```
go get github.com/pingcap/...
```

2. What did you expect to see?
no error

3. What did you see instead?
```
# github.com/pingcap/tidb/mysql
..\.gopath\src\github.com\pingcap\tidb\mysql\const.go:500:2: constant 2147483648 overflows SQLMode
..\.gopath\src\github.com\pingcap\tidb\mysql\const.go:501:2: constant 4294967296 overflows SQLMode
..\.gopath\src\github.com\pingcap\tidb\mysql\util.go:44:19: constant 4294967295 overflows int
..\.gopath\src\github.com\pingcap\tidb\mysql\util.go:45:19: constant 4294967295 overflows int
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
not installed yet

**os: win7 x64,  go: 1.9.2/386**

**Comment by winoros** [comment]
@di3663 https://github.com/pingcap/tidb/issues/5224 See this issue, we only provide maintenance for  linux/64bit.
