### ISSUE TITLE
HashJoin is slow

### ISSUE THREAD

**Issue by pipamc** [pingcap/tidb#6547]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I have three big table and the size of each table is around 5000W. Here, we just name these A, B, C. We need to join these three tables, query like this:
SELECT count(*) from A left join B on A.primary_key = B.primary_key left join C on A.primary_key = C.primary_key where A.time_index > '2018-03-28 00:00:00' and A.time_index < '2018-03-29 00:00:00';
I can not get result until timeout. So I explain this query, and tell me 
+-----------------+-----------------+-------------------------------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| id              | parents         | children                      | task | operator info                                                                                                                                          | count             |
+-----------------+-----------------+-------------------------------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
| IndexScan_20    |                 |                               | cop  | table:A, index:time_index, range:[2018-03-28 00:00:00.000,2018-03-29 00:00:00.000), out of order:true                                          |               250 |
| TableScan_21    |                 |                               | cop  | table:A, keep order:false                                                                                                                           |               250 |
| IndexLookUp_22  | IndexJoin_15    |                               | root | index:IndexScan_20, table:TableScan_21                                                                                                                 |               250 |
| TableScan_13    |                 |                               | cop  | table:B, range:(-inf,+inf), keep order:false                                                                                           |              8000 |
| TableReader_14  | IndexJoin_15    |                               | root | data:TableScan_13                                                                                                                                      |              8000 |
| IndexJoin_15    | HashLeftJoin_12 | IndexLookUp_22,TableReader_14 | root | outer:IndexLookUp_22, outer key:mdm.A.primary_key, inner key:mdm.B.primary_key
                                    | 4166.666666666666 |
| TableScan_25    |                 |                               | cop  | table:C, range:(-inf,+inf), keep order:false                                                                                 |              8000 |
| TableReader_26  | HashLeftJoin_12 |                               | root | data:TableScan_25                                                                                                                                      |              8000 |
| HashLeftJoin_12 |                 | IndexJoin_15,TableReader_26   | root | left outer join, small:TableReader_26, equal:[eq(mdm.A.primary_key, mdm.C.primary_key)] | 5208.333333333332 |
+-----------------+-----------------+-------------------------------+------+--------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------+
And I check the code, I find that the plan of join is to get all the data of out to the root and do the hashJoin (maybe I'm wrong). So any improvement  here and any suggestion for use?
Thanks.
2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v1.0.8-1-gaacba4a

**Comment by pipamc** [comment]
the data size of the final result just around 8000

**Comment by winoros** [comment]
I suggest you upgrade first then analyze these table.

**Comment by pipamc** [comment]
Thanks, I will

**Comment by zz-jason** [comment]
@pipamc Have you upgraded your tidb cluster to release-2.0? Does the execution of hash join is still slow?

**Comment by pipamc** [comment]
We have upgraded to release-2.0 and it's becoming fast, thank you

**Comment by zz-jason** [comment]
OK

**Comment by gregwebs** [comment]
@pipamc should we close this issue now?

**Comment by pipamc** [comment]
Yes, you can
