### ISSUE TITLE
Query slower after batch delete `old` rows

### ISSUE THREAD

**Issue by cnwarden** [pingcap/tidb#6556]
Please answer these questions before submitting your issue. Thanks!

**1. What did you do?**
If possible, provide a recipe for reproducing the error.

I delete old rows(the created_at field is a week ago)

**2. What did you expect to see?**

I want to see the query is faster than now. I had created the index on this field. previous about 10 millions records, now about 5 millions records.

query is like
> select max(f_created_at) from T;

I have tried the tikv-ctl compact, is it affected?

**3. What did you see instead?**

The query is slower.

previous is less than **1 second, now about 5 seconds.**

> What I should do after delete old rows to make sure better performance?

**4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?**
Release Version:  v2.0.0
Git Commit Hash:  637e130e6a9ba2e54e158131c0466233db39a60e
Git Commit Branch:  release-2.0
UTC Build Time:  2018-04-27 11:43:00
GoVersion:  go version go1.10 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1

**Comment by zz-jason** [comment]
@cnwarden could you provide us the execution plan of this sql by executing the following sql:
```sql
select max(f_created_at) from T;
```

and the create table statement by:
```sql
show create table T;
```

**Comment by cnwarden** [comment]
+----------------+--------------+----------------+------+------------------------------------------------------------------------------------------------+-------+
| id             | parents      | children       | task | operator info                                                                                  | count |
+----------------+--------------+----------------+------+------------------------------------------------------------------------------------------------+-------+
| IndexScan_31   | Limit_35     |                | cop  | table:T, index:f_created_at, range:[<nil>,+inf], keep order:true, desc | 1.00  |
| Limit_35       |              | IndexScan_31   | cop  | offset:0, count:1                                                                              | 1.00  |
| IndexReader_36 | Limit_16     |                | root | index:Limit_35                                                                                 | 1.00  |
| Limit_16       | StreamAgg_12 | IndexReader_36 | root | offset:0, count:1                                                                              | 1.00  |
| StreamAgg_12   |              | Limit_16       | root | , funcs:max(T.f_created_at)                                         | 1.00  |
+----------------+--------------+----------------+------+------------------------------------------------------------------------------------------------+-------+


** I omit some fields **

CREATE TABLE `T` (
  `f_id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT 
  `f_created_at` bigint(20) UNSIGNED NOT NULL 
  `f_updated_at` bigint(20) UNSIGNED NOT NULL 
  PRIMARY KEY (`f_id`),
  KEY `i_f_created_at` (`f_created_at`),
  KEY `i_f_updated_at` (`f_updated_at`),
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=7760947956

**Comment by cnwarden** [comment]
by the way, this table insert or update TPS about 3k. is it reason?

**Comment by tiancaiamao** [comment]
> May I know what Tidb will do after I delete batch of rows

In MVCC storage, delete operation is not a real physical delete, it's actually appending a new version to the data, that is to say, mark the data as deleted.
After insert/delete many times, there would be some staled version of data, it may affect performance because read the MVCC record need scan the storage, covering more data.
There will be also a background GC worker to recycle the old MVCC data.

That's how it works. @cnwarden
