### ISSUE TITLE
Can I replace TiKV with HBase?

### ISSUE THREAD

**Issue by vipsql** [pingcap/tidb#6561]
如果把tikv替换为hbase;可降低对机器性能的要求,scaleout完全由hbase控制

**Comment by tiancaiamao** [comment]
Back to the early days of TiDB, we actually tried to use hbase as the storage engine, but later find it's too slow and less customed to satisfy our needs, then we began the development of TiKV.

TiDB is a flexible SQL layer with pluginable storage engine, as long as you implement the storage interface https://github.com/pingcap/tidb/blob/master/kv/kv.go#L243

There would be a lot of burden for us to maintain several storage engine, so the canonical answer is 'no', we won't do that. But nothing may prevent you from re-inventing the wheel, and that maybe fun, after all, all code is open sourced.

**Comment by vipsql** [comment]
@tiancaiamao  thanks

**Comment by jiamo** [comment]
how about: https://github.com/apple/foundationdb

**Comment by XuHuaiyu** [comment]
Hi, @jiamo 
This answer is still efficient.
>TiDB is a flexible SQL layer with pluginable storage engine, as long as you implement the storage interface https://github.com/pingcap/tidb/blob/master/kv/kv.go#L243
There would be a lot of burden for us to maintain several storage engine, so the canonical answer is 'no', we won't do that. But nothing may prevent you from re-inventing the wheel, and that maybe fun, after all, all code is open sourced.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
