### ISSUE TITLE
unsupported modify column collate utf8_bin not match origin utf8_general_ci

### ISSUE THREAD

**Issue by sdoheji1234** [pingcap/tidb#6573]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

use syncer tool
[error]Error 1105: unsupported modify column collate utf8_bin not match origin utf8_general_ci

<img width="1899" alt="2c7ee45f-58da-4807-919c-d542521b0967" src="https://user-images.githubusercontent.com/39373173/40182188-6dbdcb52-5a1d-11e8-823e-a855ad3c4c2e.png">

2. What did you expect to see?

I hope it like as mysql that i can sync success. Thanks.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Server version: 5.7.10-TiDB-v2.0.0-rc.4-174-g57c0101 MySQL Community Server (Apache License 2.0)

**Comment by jackysp** [comment]
Thank you for your feedback, @sdoheji1234 . TiDB does not support case sensitive collate and it can not change collate from case sensitive to case insensitive by ALTER TABLE. I think the syncer tool developers can help you to make it work by other way. I'll ask them for help.

**Comment by holys** [comment]
@sdoheji1234 What's your previous table schema? (`show create table xxx`)

**Comment by jackysp** [comment]
Hi @sdoheji1234 , there is a way to avoid this error. Modify your SQL from 
`ALTER TABLE [table name] MODIFY COLUMN [column name] varchar(16) NULL DEFAULT NULL COMMENT [comments] AFTER [another column name]`
to
`ALTER TABLE [table name] MODIFY COLUMN [column name] character set [column charset] collate utf8_general_ci varchar(16) NULL DEFAULT NULL COMMENT [comments] AFTER [another column name]`
This SQL set the origin collate explicitly. It will avoid to convert the collate to the default collate.

**Comment by jackysp** [comment]
Hi @sdoheji1234 ,
1. Did you try to change the `ALTER TABLE` to fix the error?
2. TiDB does not show column collation in `SHOW CREATE TABLE`, could you show the original `CREATE TABLE` DDL?

**Comment by sdoheji1234** [comment]
HI @jackysp 
Thanks for your answer,according to the way you changed but still won't do.
I need to change all of database,don't just column.

**Comment by jackysp** [comment]
So, you've added `character set sign_name collate utf8_general_ci`, but it still not work? What's the error message?

**Comment by sdoheji1234** [comment]
Yes.

AFTER `user_id`;] - [[]]
2018/05/18 17:50:52 db.go:123: [warning] [exec][sql]USE `taodai_website_sdev`; ALTER TABLE `taodai_website_sdev`.`taodai_total_commission` MODIFY COLUMN `sign_name` varchar(16) NULL DEFAULT NULL COMMENT '登录用户名(操作员)' AFTER `user_id`;[args][][error]Error 1105: unsupported modify column collate utf8_bin not match origin utf8_general_ci
2018/05/18 17:50:52 db.go:87: [warning] sql stmt_exec retry 3: [USE `taodai_website_sdev`; ALTER TABLE `taodai_website_sdev`.`taodai_total_commission` MODIFY COLUMN `sign_name` varchar(16) NULL DEFAULT NULL COMMENT '登录用户名(操作员)'

**Comment by jackysp** [comment]
It seems you have not modified your sql.

Please change 
```
ALTER TABLE `taodai_website_sdev`.`taodai_total_commission` MODIFY COLUMN `sign_name` varchar(16) NULL DEFAULT NULL COMMENT '登录用户名(操作员)' AFTER `user_id`;
```
to
```
ALTER TABLE `taodai_website_sdev`.`taodai_total_commission` MODIFY COLUMN `sign_name` varchar(16) character set sign_name collate utf8_general_ci NULL DEFAULT NULL COMMENT '登录用户名(操作员)' AFTER `user_id`;
```
, and then try again.

**Comment by sdoheji1234** [comment]
@jackysp 
Tested in test environment. According to the way you changed but still won't do.
```
2018/05/22 12:04:05 db.go:123: [warning] [exec][sql]USE `taodai_website_sdev`; ALTER TABLE `taodai_website_sdev`.`taodai_total_commission` MODIFY COLUMN `sign_name` varchar(16) NULL DEFAULT NULL COMMENT '登录用户名(操作员)' AFTER `user_id`;[args][][error]Error 1105: unsupported modify column collate utf8_bin not match origin utf8_general_ci
```
<img width="1307" alt="a6defc78-bf80-480f-8765-2cffb163e109" src="https://user-images.githubusercontent.com/39373173/40351710-a927fa58-5ddf-11e8-9fa3-ed6a27d9f9a3.png">

**Comment by jackysp** [comment]
I am curious that why you say you have changed the SQL by my advice, but you really did not do that. Did you really add "**character set sign_name collate utf8_general_ci**" in your SQL? This part can not be found in your error message.
Plz change your SQL as the following one:
```
ALTER TABLE `taodai_website_sdev`.`taodai_total_commission` MODIFY COLUMN `sign_name` ```
varchar(16) character set sign_name collate utf8_general_ci NULL DEFAULT NULL COMMENT '登录用户名(操作员)' AFTER `user_id`;
```

**Comment by aalinyu** [comment]
[error] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/ddl.go:48: error while parsing sql: alter table api_notify_message convert to charset utf8 collate utf8_bin, err:line 1 column 38 near " to charset utf8 collate utf8_bin" (total length 71)

**Comment by aalinyu** [comment]
@jackysp why i excute the sql to change charset ,and when syncer again ,the error is `ddl.go:48: error while parsing sql: alter table api_notify_message convert to charset utf8 collate utf8_bin, err:line 1 column 38 near " to charset utf8 collate utf8_bin`

**Comment by sdoheji1234** [comment]
<img width="1903" alt="8f8b0331-aa2c-4fdb-8d4b-c771155701e5" src="https://user-images.githubusercontent.com/39373173/40355378-cd405544-5de8-11e8-8d4d-ae5c77f18539.png">

**Comment by jackysp** [comment]
@aalinyu It is a parser error. TiDB does not support this syntax. Please check out [TiDB docs](https://pingcap.github.io/docs-cn/)

**Comment by jackysp** [comment]
@sdoheji1234 I've got your point. This sql does not convert the collation, it keep the collation as it used to be. It means if you do not skip the error sql. It will always throw an error when it tries to convert  the collation. I think you do not know how to skip a specified sql in syncer. I'll find the docs for it.

**Comment by sdoheji1234** [comment]
docs:
<img width="513" alt="b3e5e3c3-e27c-49fc-b6ba-31f0c9b37771" src="https://user-images.githubusercontent.com/39373173/40362881-6cbb48ec-5e00-11e8-8c24-01ed4a5520a2.png">

configuration:
<img width="556" alt="5c73d556-62ca-4178-b7ef-3ebfa52dd42c" src="https://user-images.githubusercontent.com/39373173/40362899-77221298-5e00-11e8-895f-28921db64ebc.png">

error:
<img width="1900" alt="3d59ccb1-cb83-4c38-a6a5-9c8a92ec4e48" src="https://user-images.githubusercontent.com/39373173/40362904-7c488af4-5e00-11e8-858e-2e27fa855cfe.png">

**Comment by sdoheji1234** [comment]
Thank you, @holys .

**Comment by holys** [comment]
@sdoheji1234   Does it work for you?

**Comment by sdoheji1234** [comment]
Yes, it's helpful to me.

**Comment by shenli** [comment]
@sdoheji1234 Please feel free to reopen this issue if you have any more problem.
