### ISSUE TITLE
QPS slow down when data growth.

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#6594]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
QPS slow down when data growth.

I use tidb-bench/sysbench (https://github.com/pingcap/tidb-bench) to generate two databases.
db1 have 1 billion rows data in one table.
db2 have 3.5 billion rows data in one table.
Then run oltp.sh to test.

db1 QPS is 5.5k
db2 QPS is 30.3k

![grafana - test-cluster-tidb 2018-05-21 18-13-30](https://user-images.githubusercontent.com/26958647/40303198-675e4ae8-5d24-11e8-9076-8eaacafb29ac.png)

The tables have same table schema:
```
sbtest1 | CREATE TABLE `sbtest1` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `k` int(10) UNSIGNED NOT NULL DEFAULT '0',
  `c` char(120) NOT NULL DEFAULT '',
  `pad` char(60) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `k_1` (`k`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=3500070001 |
+---------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)
```

Is the test result correct?
I suppose that TiDB not slow down when data growth.

2. What did you expect to see?
TiDB not slow down when data growth.

3. What did you see instead?
TiDB slow down when data growth.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.0.0-rc.4-133-g0fda3b4
Git Commit Hash: 0fda3b408f17c7ff4504bf6ac95c37379d5211a4
Git Branch: master
UTC Build Time: 2018-05-02 09:19:31
GoVersion: go version go1.10 linux/amd64
Race Enabled: false
TiKV Min Version: 2.0.0-rc.4.1

**Comment by jackysp** [comment]
Hi @DavisLinDB ,

Thank you for your feedback.

```
db1 have 1 billion rows data in one table.
db2 have 3.5 billion rows data in one table.
Then run oltp.sh to test.

db1 QPS is 5.5k
db2 QPS is 30.3k
```

So it is not slow down I think.

**Comment by DavisLinDB** [comment]
@jackysp

sorry, 
db1 have 1 billion rows data in one table.
db2 have 3.5 billion rows data in one table.
Then run oltp.sh to test.

db1 1 billion rows, QPS is 30.3k
db2 3.5 billion rows, QPS is 5.5k

more data become slower

**Comment by DavisLinDB** [comment]
@jackysp 

TiKV * 4 use physical machine, each machine has 32G Ram.  Using block_cache_size default value in TiKV config file.

```
cat tikv.toml
# TiKV config template
#  Human-readable big numbers:
#   File size(based on byte): KB, MB, GB, TB, PB
#    e.g.: 1_048_576 = "1MB"
#   Time(based on ms): ms, s, m, h
#    e.g.: 78_000 = "1.3m"


[readpool.storage]

[readpool.coprocessor]

[server]
labels = {  }

[storage]

[pd]
# This section will be overwritten by command line parameters

[metric]
address = "192.168.29.155:9091"
interval = "15s"
job = "tikv"

[raftstore]
raftdb-path = ""
sync-log = true

[coprocessor]

[rocksdb]
wal-dir = ""

[rocksdb.defaultcf]

[rocksdb.lockcf]

[rocksdb.writecf]

[raftdb]

[raftdb.defaultcf]

[security]
ca-path = ""
cert-path = ""
key-path = ""

[import]
```

**Comment by jackysp** [comment]
There is a config file template in tidb-ansible/conf/tikv.yml. You can change them to a suitable value for your tests according to your grafana -> tikv -> server -> cf size.

**Comment by DavisLinDB** [comment]
@jackysp 

I change the block_cache_size value and using 3.5 billion row's db to test.  QPS between 4k~6k.  How can I get higher QPS, such as 30K?  Add more memory helpful?

**Comment by jackysp** [comment]
We have a document for [tuning TiKV](https://github.com/pingcap/docs/blob/master/op-guide/tune-tikv.md) , and here is the [Chinese version](https://github.com/pingcap/docs-cn/blob/master/op-guide/tune-tikv.md). I think they could help you. And don't forget to warmup your database after restarting the cluster.

**Comment by kolbe** [comment]
New link to Tuning TiKV documentation: https://pingcap.com/docs/dev/reference/performance/tune-tikv/

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
