### ISSUE TITLE
Distributed transaction rollback is abnormal.

### ISSUE THREAD

**Issue by zhuxiujia** [pingcap/tidb#6636]
In the micro-service environment, A,B 2 servers are independent from each other, A service changes the data, A calls the B service to modify the data of B, and A is at the end of rollback; But B's data didn't roll back.
微服务环境下A,B2个服务器互相独立，A服务修改数据，A调用了B服务修改了B的数据，A在结束时rollback;但是B的数据没有回滚

**Comment by tiancaiamao** [comment]
> A service changes the data

Is it committed or not?

> A calls the B service to modify the data of B

Is both A and B's data belongs to same transaction?

**Comment by shenli** [comment]
@zhuxiujia I can not get your point. Maybe you misunderstand distributed transaction.
