### ISSUE TITLE
JSON_EXTRACT supports parsing multiple fields

### ISSUE THREAD

**Issue by melin** [pingcap/tidb#6650]
JSON_EXTRACT parses only one field at a time, and if more fields are retrieved from json, it is slower to parse multiple times, Similar to hive udtf function

**Comment by XuHuaiyu** [comment]
Hi, @melin , sorry for late reply and thank you for your feedback.
Can you put the link to the corresponded implementation of hive here?
``` go
func (b *builtinJSONExtractSig) evalJSON(row types.Row) (res json.BinaryJSON, isNull bool, err error) {
	res, isNull, err = b.args[0].EvalJSON(b.ctx, row)
	if isNull || err != nil {
		return
	}
	pathExprs := make([]json.PathExpression, 0, len(b.args)-1)
	for _, arg := range b.args[1:] {
		var s string
		s, isNull, err = arg.EvalString(b.ctx, row)
		if isNull || err != nil {
			return res, isNull, errors.Trace(err)
		}
		pathExpr, err := json.ParseJSONPathExpr(s)    <==== Is this what you mean?
		if err != nil {
			return res, true, errors.Trace(err)
		}
		pathExprs = append(pathExprs, pathExpr)
	}
	var found bool
	if res, found = res.Extract(pathExprs); !found {
		return res, true, nil
	}
	return res, false, nil
}
```

**Comment by melin** [comment]
hive example:

select a.name, b.name1, b.addr  from test_users_dt a 
lateral view bigdata.json_extract_value('{"name":"binsong.li", "address":"hangzhou"}', 'name', "address") b as name1, addr;

select bigdata.json_extract_value('{"name":"binsong.li", "address":{"name": "hangzhou"}}', "name", "address/name") as (name, address)
from bigdata.test_users_dt

//解析json 数组
select bigdata.json_extract_value('[{"name":"binsong.li"}, {"name":"tongdun"}]', "/0/name", "/1/name") as (name1, name2)
from bigdata.test_users_dt

**Comment by XuHuaiyu** [comment]
@melin This manual may help you://dev.mysql.com/doc/refman/8.0/en/json-search-functions.html#function_json-extract

``` sql
tidb> select json_extract('{"name":"zs", "address":"hz"}', "$.name", "$.address");
+----------------------------------------------------------------------+
| json_extract('{"name":"zs", "address":"hz"}', "$.name", "$.address") |
+----------------------------------------------------------------------+
| ["zs","hz"]                                                          |
+----------------------------------------------------------------------+
1 row in set (0.00 sec)
```

**Comment by xiongjiwei** [comment]
close due to supported
