### ISSUE TITLE
Failed to deploy TiDB cluster on MacOS by docker-compose

### ISSUE THREAD

**Issue by kirinse** [pingcap/tidb#6659]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
on Mac + docker-machine:
$ git clone https://github.com/pingcap/tidb-docker-compose.git
$ cd tidb-docker-compose && docker-compose up -d

2. What did you expect to see?

3. What did you see instead?
docker logs -f tidbdockercompose_pd0_1
2018/05/27 23:50:01.700 log.go:78: [fatal] mvcc/backend: [cannot open database at /data/pd0/member/snap/db (invalid argument)]

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.0

**Comment by XuHuaiyu** [comment]
related to https://github.com/pingcap/tidb-docker-compose/issues/23
