### ISSUE TITLE
duplicated store address

### ISSUE THREAD

**Issue by mia0x75** [pingcap/tidb#6662]
After stop the tikv server, change the data folder, restart service

May 28 15:55:46.101 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.101 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.102 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.103 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.103 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.103 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.104 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.104 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.105 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.105 ERRO fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("duplicated store address: id:11 address:\"10.0.4.45:20160\" , already registered by id:1 address:\"10.0.4.45:20160\" ") }))
May 28 15:55:46.106 ERRO failed to start node: Pd(Other(StringError("[src/pd/util.rs:323]: fail to request")))

try to delete store 1

```
# curl -v -X DELETE http://10.0.4.54:2379/pd/api/v1/store/1
* About to connect() to 10.0.4.54 port 2379 (#0)
*   Trying 10.0.4.54...
* Connected to 10.0.4.54 (10.0.4.54) port 2379 (#0)
> DELETE /pd/api/v1/store/1 HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.0.4.54:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Length: 5
< Content-Type: application/json; charset=UTF-8
< Date: Mon, 28 May 2018 08:30:27 GMT
< 
null
* Connection #0 to host 10.0.4.54 left intact
```

```
# curl http://10.0.4.54:2379/pd/api/v1/store/1          
{
  "store": {
    "id": 1,
    "address": "10.0.4.45:20160",
    "state": 1,
    "state_name": "Offline"
  },
  "status": {
    "leader_count": 1,
    "leader_weight": 1,
    "leader_score": 1,
    "leader_size": 1,
    "region_count": 1,
    "region_weight": 1,
    "region_score": 1,
    "region_size": 1,
    "start_ts": "1970-01-01T08:00:00+08:00"
  }
}
```

**Comment by XuHuaiyu** [comment]
PTAL @nolouch

**Comment by nolouch** [comment]
@mia0x75 you need to wait for the state of `store 1` become `Tombstone`, then start the new TiKV.` delete store 1` will let it become an offline store, and the scheduler will begin to delete the replicas on store 1. If the store is down, it will remove the down peer directly in the Region(raft group). when there is no peer on the store, it will be a `Tombstone` store.

**Comment by mia0x75** [comment]
thanks for reply.

I will shut down the machine and check the state tomorrow.

PS. Is it possible to return a human readable message rather than null?

**Comment by mia0x75** [comment]
after 10+ hours, the state of the node is still offline.

```
$ curl http://10.0.4.54:2379/pd/api/v1/store/1
{
  "store": {
    "id": 1,
    "address": "10.0.4.45:20160",
    "state": 1,
    "state_name": "Offline"
  },
  "status": {
    "leader_count": 1,
    "leader_weight": 1,
    "leader_score": 1,
    "leader_size": 1,
    "region_count": 1,
    "region_weight": 1,
    "region_score": 1,
    "region_size": 1,
    "start_ts": "1970-01-01T08:00:00+08:00"
  }
}
```

How can I remove the node manually?

**Comment by nolouch** [comment]
@mia0x75  you can try `curl -v -X DELETE http://10.0.4.54:2379/pd/api/v1/store/1?force=true`

**Comment by mia0x75** [comment]
No, I just start tikv, after a while, kill the process, restart tikv from another path. Anyway, I rebuilt the whole test environments.
