### ISSUE TITLE
Tens of billions of data incremental tidb storage problems

### ISSUE THREAD

**Issue by 444728248** [pingcap/tidb#6663]
At present, the data is incrementally increased by several billion per day, and the business database needs to provide the corresponding second level, which involves join, count, order by operation.
Tidb suits？

**Comment by XuHuaiyu** [comment]
Hi, @444728248 
TiDB can serve your needs well.
Many company examples can be referred from our official website.
You can find from the left navigation.

**Comment by 444728248** [comment]
Okay, thank you
Is there a good suggestion for me to test the size of the cluster?

**Comment by iamxy** [comment]
Your scene is very suitable for using TiDB to make your data scalable, and perform some complex queries on it. We attach great importance to your case. Please feel free to send an email to info@pingcap.com and describe your needs in detail. In addition, we can also keep communication by using some IM software.

**Comment by 444728248** [comment]
Ladies and gentlemen, mail has been sent ，Mail content description is relatively simple, and I hope to maintain communication with the company.
