### ISSUE TITLE
 playbook  rolling_update_monitor.yml TASK set_fact failed

### ISSUE THREAD

**Issue by calmzealA** [pingcap/tidb#6666]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
updating from tidb1.0.6 to tidb2.0.2.
follow https://www.pingcap.com/docs-cn/op-guide/tidb-v2-upgrade-guide/

$ ansible-playbook local_prepare.yml
success
$ ansible-playbook rolling_update.yml
success
$ ansible-playbook migrate_monitor.yml
success
$ ansible-playbook rolling_update_monitor.yml
failed

2. What did you expect to see?

3. What did you see instead?

[]: Ansible FAILED! => playbook: rolling_update_monitor.yml; TASK: set_fact; message: {"msg": "The conditional check '((existing_api_keys['json'] | selectattr(\"name\", \"equalto\", \"grafana_apikey\")) | list) | length == 1' failed. The error was: no test named 'equalto'\n\nThe error appears to have been in '/home/tidb/tidb-ansible/create_grafana_api_keys.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
updating from tidb1.0.6 to tidb2.0.2.

**Comment by LinuxGit** [comment]
Please check your jinja2 version:
 $ pip show jinja2
Name: Jinja2
Version: 2.9.6
You should use use pip to install Ansible and its dependencies according to  https://www.pingcap.com/docs-cn/op-guide/tidb-v2-upgrade-guide/.
