### ISSUE TITLE
Change password can not work properly

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#6668]
环境

target | version
--- |---
docker | v18.03-ce
tidb | v2.0.1 from docker hub

集群有3个tidb节点tidb1，tidb2，tidb3

往tidb1连接，执行命令
```
USE mysql;
UPDATE user SET Password = PASSWORD('password') WHERE user = 'root';
FLUSH PRIVILEGES;
```
在tidb1连接，需要连接使用`-uroot -P4000 -p'password'`

在tidb2，和tidb3使用上面的命令不能连接，不带`-ppassword`则可以连接

**Comment by jackysp** [comment]
Thanks for your feedback! @dayuanyuan1989 Did you try it on MySQL server?

**Comment by tiancaiamao** [comment]
Don't modify the mysql's table directly:
1. it can't guarantee the data consistency in all related tables
2. it can't notify all TiDB nodes to update cache information.

You can try `SET PASSWORD` statement. @dayuanyuan1989 
https://pingcap.com/docs/sql/privilege/

**Comment by dayuanyuan1989** [comment]
Yeah! I try it success with your suggest!

Really appreciate your help.
