### ISSUE TITLE
undefined: kv.ErrRetryable

### ISSUE THREAD

**Issue by luyee** [pingcap/tidb#667]
go get github.com/pingcap/go-themis
# github.com/pingcap/go-themis
../go-themis/themis_txn.go:173: undefined: kv.ErrRetryable
../go-themis/themis_txn.go:183: undefined: kv.ErrRetryable
../go-themis/themis_txn.go:189: undefined: kv.ErrRetryable
../go-themis/themis_txn.go:197: undefined: kv.ErrRetryable

&
go version
go version go1.5 linux/amd64

**Comment by ngaut** [comment]
@luyee Thanks for your report.
Fixed! Could you take another retry?

**Comment by c4pt0r** [comment]
Fix in https://github.com/pingcap/tidb/pull/668
and https://github.com/pingcap/go-themis/pull/21

**Comment by luyee** [comment]
·@ngaut is ok  make make server make interpreter

**Comment by ngaut** [comment]
@luyee Good to know, thanks.
