### ISSUE TITLE
want to record the committer of sql

### ISSUE THREAD

**Issue by powqabc** [pingcap/tidb#6673]
Now，we can set @@tidb_general_log=1 and record all the SQL statements in the log. But the committer of SQL is not recorded in the log. We want to make analysis on the details of the SQL.
Can tidb support to the committer of every SQL？The demo of log can add the committer of SQL based on the tidb_slow_query.log
Like this:
[info] cost_time:582.76183ms succ:true connection_id:457 txn_start_ts:399880415363465346 database:a table_ids:[] index_ids:[] committer:xxx sql:select count(1) from a.b;

**Comment by XuHuaiyu** [comment]
Hi, @powqabc , thank you for your feedback.
The `committer` you mentioned here is the `user` with which the session login?

**Comment by powqabc** [comment]
Yes.
There is an other question.Is each record  a complete statement without carriage return?
Thank you.

**Comment by melin** [comment]
Json format is recommended to facilitate parsing

**Comment by coocood** [comment]
@lysu the host is included in the user string.
