### ISSUE TITLE
Support ZEROFILL attribute for numeric type  

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#6688]
1. What did you do?
If possible, provide a recipe for reproducing the error.

```
drop table if exists t1;
create table t1 (a int(3) zerofill);
insert into t1 values (3);
```

2. What did you expect to see?

```
mysql> select * from t1;
+------+
| a    |
+------+
|  003 |
+------+
```

3. What did you see instead?

```
mysql> select * from t1;
+------+
| a    |
+------+
|    3 |
+------+
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v2.0.0-rc.4-253-gc1fb53c3-dirty
Git Commit Hash: c1fb53c31fd1ad8a2fbf63a002713810c6fb0014
Git Branch: fix-decimal-overflow-warnings
UTC Build Time: 2018-05-29 01:51:07
GoVersion: go version go1.10.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.0.0-rc.4.1
```

Current, when create table with `ZEROFILL` attribute is no real effact.
Maybe we can support this attribute just like mysql.

```
  | TINYINT[(length)] [UNSIGNED] [ZEROFILL]
  | SMALLINT[(length)] [UNSIGNED] [ZEROFILL]
  | MEDIUMINT[(length)] [UNSIGNED] [ZEROFILL]
  | INT[(length)] [UNSIGNED] [ZEROFILL]
  | INTEGER[(length)] [UNSIGNED] [ZEROFILL]
  | BIGINT[(length)] [UNSIGNED] [ZEROFILL]
  | REAL[(length,decimals)] [UNSIGNED] [ZEROFILL]
  | DOUBLE[(length,decimals)] [UNSIGNED] [ZEROFILL]
  | FLOAT[(length,decimals)] [UNSIGNED] [ZEROFILL]
  | DECIMAL[(length[,decimals])] [UNSIGNED] [ZEROFILL]
  | NUMERIC[(length[,decimals])] [UNSIGNED] [ZEROFILL]
```

https://dev.mysql.com/doc/refman/8.0/en/create-table.html
https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html

**Comment by morgo** [comment]
I expect that MySQL will deprecate and remove ZEROFILL in the future.  I no longer work on the MySQL team, but wrote about this here in 2015:
http://www.tocker.ca/2015/07/02/proposal-to-deprecate-mysql-integer-display-width-and-zerofill.html

**Comment by coocood** [comment]
@morgo 
Thank you for your information!
Now we decided to not support this feature.
