### ISSUE TITLE
Support enabling  grpc tracing

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#6689]
Sometimes we need to debug grpc issues. However according to https://github.com/pingcap/tidb/pull/1981 it is disabled due to memory leaks. Adding a config (defaults to false) will be better.

**Comment by tiancaiamao** [comment]
Provide that config is dangerous.
If it's just for debugging, maybe you can change the code. @breeswish

**Comment by breeswish** [comment]
By the way I'm suspicious about the memory leak 😢 The tracing functionality itself will keep some data in memory for each request (so that you can view its details later). This actually means the memory usage should always grow if tracing is enabled..

**Comment by zhexuany** [comment]
Maybe we need dive deep into this issue. @shenli What do you think?

**Comment by breeswish** [comment]
Ok it seems that grpc tracing feature is not useful at all. What we can know from `net/trace` are almost logged elsewhere, and what we really needs is not in there. Closing.
