### ISSUE TITLE
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

### ISSUE THREAD

**Issue by walterzhaoJR** [pingcap/tidb#6715]
I use Docker Compose.

ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

Docker version 18.03.1-ce, build 9ee9f40
![image](https://user-images.githubusercontent.com/22393698/40772237-fdb71298-64f1-11e8-957f-cc8b21acbf48.png)

![image](https://user-images.githubusercontent.com/22393698/40772313-2fee60ae-64f2-11e8-885e-ccb704dd5883.png)

thx

**Comment by lamxTyler** [comment]
@walterzhaoJR It seems that your tidb didn't restart normally. Is it already started? Or could you provide the tidb log?

**Comment by walterzhaoJR** [comment]
OK,I have solved the problem.
The problem may be due to problems with my directory and permissions.
THX,I will close the issue.
