### ISSUE TITLE
did it support master-slave real time replication/sync?

### ISSUE THREAD

**Issue by ivanjoy42** [pingcap/tidb#6727]
I mean the replica between two tidb cluster, not for mysql.

**Comment by winkyao** [comment]
TiDB has binlog, you can get more details in https://pingcap.com/docs/tools/tidb-binlog-kafka/

**Comment by morgo** [comment]
As winkyao suggested, TiDB-Binlog is the recommended tool to replicate between TiDB clusters.

I am going to close this issue now, but please feel free to re-open if you have any additional questions.  Thanks!
