### ISSUE TITLE
did tidb support physical machine isolation?

### ISSUE THREAD

**Issue by ivanjoy42** [pingcap/tidb#6728]
I need move some tables/databases into a specific physical machine/group.
Avoid resource competition.
Just like hbase rsgroup feature.

**Comment by nolouch** [comment]
@ivanjoy42  Actually, we Initial support it by setting table namespace via [`pd-ctl`](https://github.com/pingcap/docs-cn/blob/master/tools/pd-control.md#table_ns-create--add--remove--set_store--rm_store--set_meta--rm_meta).  Firstly, you should create a namespace, then adds the stores to the namespace, Finally adds the table to the namespace.
