### ISSUE TITLE
I made a random write test, and its very slow at the beginning.

### ISSUE THREAD

**Issue by ivanjoy42** [pingcap/tidb#6729]
**1. What did you do?**
I made a benchmark test, that insert 1 billion record to a table. Its very slow at the first 30 minutes. And I try to [manually split regions](https://github.com/pingcap/tidb/issues/6633), but without effect.
![cpu](https://user-images.githubusercontent.com/9277639/40835841-3da51cee-65c7-11e8-9c8a-0c405f9f4803.jpg)
![io](https://user-images.githubusercontent.com/9277639/40835846-4210173e-65c7-11e8-826e-0086fae7f18d.jpg)
![ops](https://user-images.githubusercontent.com/9277639/40836303-c9e0d422-65c8-11e8-96d2-5091ce952688.png)

**2. What did you expect to see?**
I need good performance from the start.
50 tikv working at beginning, 110000ops

**3. What did you see instead?**
1-5 minutes only 3 tikv working, 20000 ops
1-10 minutes about 10 tikv working, 70000 ops
30 minutes later 50 tikv working, 110000 ops

**4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?**
Release Version: v2.0.1
10 tidb/tikv server
1 prometheus/nginx server
3 pd server
10 client * 10 thread, batch write 1000 record once time
create table bm (a bigint unsigned primary key, b bigint unsigned, c bigint unsigned, d bigint unsigned, e bigint unsigned, f varchar(100), g varchar(100), h varchar(100), i varchar(100), j varchar(100));
create index idx_bm on bm (b,c,d);

**Comment by siddontang** [comment]
@ivanjoy42 

how many regions do you split at first? if you split the regions, the PD will take some time to balance the regions.

**Comment by ivanjoy42** [comment]
In this case I did not split region. At first only 3 region, 5 minutes later about 10-15 region.
How to balance the regions into different store?

**Comment by nolouch** [comment]
@ivanjoy42  you can observe the regions distribution during the test. the `Server` row the `TiKV` dashboard on `grafana` will show it in details. and the regions will automatically split with the data increasing and then `PD` schedule it automatically to the other idle stores.

**Comment by ivanjoy42** [comment]
5 minutes: 55 regions in only 5 store.
10 minutes: 53 regions in 3 hot store, 83 regions in 44 store, 0 regions in 13 idle store.
It gets better after 30 minutes.

![5](https://user-images.githubusercontent.com/9277639/40841727-0552da40-65de-11e8-8fed-b3ee5ae266a5.png)
![10](https://user-images.githubusercontent.com/9277639/40841728-058cad6a-65de-11e8-8b79-cca046826082.png)
![30](https://user-images.githubusercontent.com/9277639/40841729-05c4092c-65de-11e8-8b7c-02c94110b157.png)

**Comment by nolouch** [comment]
@ivanjoy42  you can tune it via [`pd-ctl`](https://github.com/pingcap/docs/blob/master/tools/pd-control.md#config-show--set-option-value) to speed up the balance. However, we recommend keeping the default value in production. the balance also brings some overhead, which may affect the business.

**Comment by kolbe** [comment]
@ivanjoy42 did you continue working on this deployment after June of last year? Did you make any progress in either speeding up the import or better understanding the behavior of the cluster? Please let us know if you're still working with TiDB and/or if you are still running into issues.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
