### ISSUE TITLE
Does tidb support Spatial database?

### ISSUE THREAD

**Issue by netroby** [pingcap/tidb#673]
Does tidb support Spatial database?
```
A spatial database, or geodatabase is a database that is optimized to store and query data that represents objects defined in a geometric space. Most spatial databases allow representing simple geometric objects such as points, lines and polygons. Some spatial databases handle more complex structures such as 3D objects, topological coverages, linear networks, and TINs. While typical databases are designed to manage various numeric and character types of data, additional functionality needs to be added for databases to process spatial data types efficiently. These are typically called geometry or feature. The Open Geospatial Consortium created the Simple Features specification and sets standards for adding spatial functionality to database systems.
```

**Comment by netroby** [comment]
https://en.wikipedia.org/wiki/Spatial_database

**Comment by ngaut** [comment]
TiDB doesn't support the feature currently. We may reconsider the feature later.

**Comment by netroby** [comment]
https://www.rethinkdb.com/docs/geo-support/python/ 
Now days, we built social apps with geospatial query and store data. We also store and query JSON format.   MySQL 5.7 added JSON support, Better spatial support, They were good for modern DEV needed.

**Comment by lavvy** [comment]
Any milestone for this feature. Geospatial and realtime?  This is one of the biggest features of modern databases

**Comment by shenli** [comment]
@lavvy Thanks for your feedback! We do not have plan for this feature now. We may reconsider the feature later. But it will be no early than the end of this year.
