### ISSUE TITLE
SQL FLUSH PRIVILEGES problem

### ISSUE THREAD

**Issue by denisbertini** [pingcap/tidb#674]
Hi Guys,
trying to create a user i am facing the following problem when 
using the command
mysql> flush privileges;
ERROR 1105 (HY000): line 1 column 1 near "flush"

Somehow the SQL statement is not recognise ... ( in use the tidb-server mode)

Any idea ?
Is there a specific way to create User and grant privileges using tidb ?

Thanks in advance !
Denis

**Comment by shenli** [comment]
hi @denisbertini Thanks for your report.

TiDB support some of the privilege sql statements such as CreateUser and Grant statement.
You can try statements like "CREATE USER 'monty'@'localhost' IDENTIFIED BY 'some_pass';" and "GRANT ALL PRIVILEGES ON *.* TO 'monty'@'localhost';".
Please refer to mysql reference manual. http://dev.mysql.com/doc/refman/5.7/en/create-user.html  http://dev.mysql.com/doc/refman/5.7/en/grant.html.

Flush statement is not supported now. We will work on it.

**Comment by denisbertini** [comment]
Well ok !
For now i can connect the tiDB only with root and empty password.
I am nevertheless facing others issues when creating table ... i have to study what is
happening and give you a report...
