### ISSUE TITLE
Create databases

### ISSUE THREAD

**Issue by denisbertini** [pingcap/tidb#675]
Hi,
I can create database using SQL "CREATE DATABASE" but it is impossible
to access it (using tidb-server mode) using mysql_real_connect() from the mysql C API
driver ... 
Any idea ?
PS: i can nevertheless access the predefined database ( mysql, test ) using user:root
and empty  password ...

**Comment by shenli** [comment]
@denisbertini Thanks for your report.
May I have your source code? Can you connect to TiDB with MySQL command line client?

**Comment by shenli** [comment]
I write a test case with MySQL C API and get no error. Could you provide more detailed information?

My source code:  https://gist.github.com/shenli/914c36f7a304db6edf20
Result:
➜  mysql  gcc -I/usr/local/mysql/include -L/usr/local/mysql/lib -lmysqlclient main.c
➜  mysql  ./a.out 
Begin
Connect sucess
End
➜  mysql  mysql -uroot -h127.0.0.1 -P4000 -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 10007
Server version: 5.5.31-TiDB-1.0 MySQL Community Server (GPL)

Copyright (c) 2000, 2015, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> use test;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> select * from Cars;
+------+------+-------+
| Id   | Name | Price |
+------+------+-------+
|    1 | Audi | 52642 |
+------+------+-------+
1 row in set (0.00 sec)

**Comment by denisbertini** [comment]
Yes,
I got the details point. one has to use the explicit IP number ( 127.0.0.1) . With localhost it does not
work ... why?  no idea !!

**Comment by morefreeze** [comment]
@denisbertini Would you take a look your `/etc/hosts` file content. You can use `localhost` if `127.0.0.1 localhost`in `/etc/hosts`
