### ISSUE TITLE
how to get sql metric info from tidb such as tps, qps

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#6757]
My Tidb cluster deployed by docker, not ansible

I want to monitor tidb sql metric on prometheus

I used the sql statement `show global status`, nothing metirc info can read from the returned info

```
+--------------------+--------------------------------------+
| Variable_name      | Value                                |
+--------------------+--------------------------------------+
| Ssl_cipher         |                                      |
| Ssl_cipher_list    |                                      |
| Ssl_verify_mode    | 0                                    |
| Ssl_version        |                                      |
| server_id          | 34f4466b-b297-4c9d-92f8-eaba7d0b6a52 |
| ddl_schema_version | 16                                   |
+--------------------+--------------------------------------+
```

---

Wish your suggestions

**Comment by lamxTyler** [comment]
@dayuanyuan1989  How did you start the cluster using docker? If you are using docker-compose, you can just access http://localhost:3000 as documented [here](https://github.com/pingcap/docs/blob/master/op-guide/docker-compose.md#deploy-tidb-using-docker-compose).

**Comment by dayuanyuan1989** [comment]
@lamxTyler  I start cluster as [Docker Deployment](https://github.com/pingcap/docs/blob/master/op-guide/docker-deployment.md), not docker-compose

After I started the cluster, I install the prometheus cluster by hand.

I wanted to use sqld-exporter to get tidb metrics, but cannot get useful metric data from `show global status`

**Comment by winkyao** [comment]
@iamxy PTAL

**Comment by dayuanyuan1989** [comment]
To use the push_gateway to get metrics from tidb is the only way to get sql metrics from tidb-cluster?
