### ISSUE TITLE
pushgateway 0.5.1 is not compatible with tidb 2.1.0

### ISSUE THREAD

**Issue by mouqi123** [pingcap/tidb#6759]
tidb version: 2.1.0, pushgateway: 0.5.1
config tidb-server, tikv-server, pd-server's pushgateway, then run pushgateway.
then curl 127.0.0.1:9091/metrics, error occurs:
`* collected metric go_memstats_alloc_bytes_total label:<name:"instance" value:"appiatestdb" > label:<name:"job" value:"pd3" > counter:<value:3.9238263088e+10 >  has label dimensions inconsistent with previously collected metrics in the same metric family`

prometheus change client_golang lib, it's not compatible with old release. What is happening is that for some reason, metrics like
`metric_name{label1="value1"}
metric_name{label1="value1",label2="value2"}`
are being generated. This is illegal, but this was not enforced in the past. The correct way is to pad all metrics to have the same set of label names, using empty values where there is nothing to put in a particular label. The above should be
`metric_name{label1="value1",label2=""}
metric_name{label1="value1",label2="value2"}`

**Comment by shenli** [comment]
@mouqi123 Thanks for your feedback!
Please use pushgateway 0.4.0 for now.

**Comment by zz-jason** [comment]
I've closed this issue. feel free to reopen it if the problem still exists.
