### ISSUE TITLE
Cast float to integer

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#6763]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

mysql> SELECT First_Name, CAST(Score AS Integer) Int_Score FROM Student_Score;
ERROR 1105 (HY000): line 1 column 40 near ") Int_Score FROM Student_Score" (total length 70)
mysql> select * from student_Score;
+-----------+------------+-------+
| StudentID | First_Name | Score |
+-----------+------------+-------+
|         1 | Jenny      |  85.2 |
|         2 | Bob        |  92.5 |
|         3 | Alice      |    90 |
|         4 | James      | 120.1 |
+-----------+------------+-------+
4 rows in set (0.14 sec)

mysql> show columns from student_Score;
+------------+----------+------+------+---------+-------+
| Field      | Type     | Null | Key  | Default | Extra |
+------------+----------+------+------+---------+-------+
| StudentID  | int(4)   | YES  |      | NULL    |       |
| First_Name | char(20) | YES  |      | NULL    |       |
| Score      | float    | YES  |      | NULL    |       |
+------------+----------+------+------+---------+-------+
3 rows in set (0.03 sec)

2. What did you expect to see?

MariaDB [test]> SELECT First_Name, CAST(Score AS Integer) Int_Score FROM Student_Score;
+------------+-----------+
| First_Name | Int_Score |
+------------+-----------+
| Jenny      |        85 |
| Bob        |        92 |
| Alice      |        90 |
| James      |       120 |
+------------+-----------+

3. What did you see instead?

mysql> SELECT First_Name, CAST(Score AS Integer) Int_Score FROM Student_Score;
ERROR 1105 (HY000): line 1 column 40 near ") Int_Score FROM Student_Score" (total length 70)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.0.1

**Comment by XuHuaiyu** [comment]
Hi, @CrazyNash 
MySQL does not support cast( xx as integer) ,
you can use cast(xx as signed) instead.

refer: MySQL manual https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast

**Comment by CrazyNash** [comment]
But it works from MariaDB

**Comment by zz-jason** [comment]
@CrazyNash For now we don't have a plan to make TiDB compatible with MariaDB, maybe we can do it later.
