### ISSUE TITLE
convert float to integer

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#6764]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

mysql> select * from student_Score;
+-----------+------------+-------+
| StudentID | First_Name | Score |
+-----------+------------+-------+
|         1 | Jenny      |  85.2 |
|         2 | Bob        |  92.5 |
|         3 | Alice      |    90 |
|         4 | James      | 120.1 |
+-----------+------------+-------+
4 rows in set (0.14 sec)

mysql> show columns from student_Score;
+------------+----------+------+------+---------+-------+
| Field      | Type     | Null | Key  | Default | Extra |
+------------+----------+------+------+---------+-------+
| StudentID  | int(4)   | YES  |      | NULL    |       |
| First_Name | char(20) | YES  |      | NULL    |       |
| Score      | float    | YES  |      | NULL    |       |
+------------+----------+------+------+---------+-------+
3 rows in set (0.03 sec)

mysql> SELECT First_Name, CONVERT(Score, Integer) Int_Score FROM Student_Score;
ERROR 1105 (HY000): line 1 column 41 near ") Int_Score FROM Student_Score" (total length 71)

2. What did you expect to see?

MariaDB [test]> SELECT First_Name, CONVERT(Score, Integer) Int_Score FROM Student_Score;
+------------+-----------+
| First_Name | Int_Score |
+------------+-----------+
| Jenny      |        85 |
| Bob        |        92 |
| Alice      |        90 |
| James      |       120 |
+------------+-----------+
4 rows in set (0.00 sec)

3. What did you see instead?

ERROR 1105 (HY000): line 1 column 41 near ") Int_Score FROM Student_Score" (total length 71)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.0.1

**Comment by morgo** [comment]
This syntax appears to be a MariaDB extension.  In MySQL 5.7 the keyword `Integer` is not supported:
```
mysql 57> CREATE TABLE Student_Score (
    ->  StudentID INTEGER,
    ->  First_Name CHAR(20),
    ->  Score FLOAT
    -> );
Query OK, 0 rows affected (0.04 sec)

mysql 57> 
mysql 57> SELECT First_Name, CONVERT(Score, Integer) Int_Score FROM Student_Score;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Integer) Int_Score FROM Student_Score' at line 1
mysql 57> SELECT First_Name, CONVERT(Score, Unsigned) Int_Score FROM Student_Score;
Empty set (0.00 sec)

```

**Comment by CrazyNash** [comment]
Thanks!
