### ISSUE TITLE
check  constraint doesn't work

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#6765]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

mysql> CREATE TABLE Customer
    -> (SID integer CHECK (SID > 0),
    -> Last_Name varchar (30),
    -> First_Name varchar(30));
Query OK, 0 rows affected (0.18 sec)
mysql> INSERT INTO Customer VALUES (-3, 'Gonzales', 'Lynn');
Query OK, 1 row affected (0.16 sec)
mysql> show columns from Customer;
+------------+-------------+------+------+---------+-------+
| Field      | Type        | Null | Key  | Default | Extra |
+------------+-------------+------+------+---------+-------+
| SID        | int(11)     | YES  |      | NULL    |       |
| Last_Name  | varchar(30) | YES  |      | NULL    |       |
| First_Name | varchar(30) | YES  |      | NULL    |       |
+------------+-------------+------+------+---------+-------+
3 rows in set (0.03 sec)
mysql> select * from customer;
+------+-----------+------------+
| SID  | Last_Name | First_Name |
+------+-----------+------------+
|   -3 | Gonzales  | Lynn       |
+------+-----------+------------+
1 row in set (0.04 sec)

2. What did you expect to see?

The insert operation should fail with error

3. What did you see instead?

It completed successfully

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 v2.0.1

**Comment by CrazyNash** [comment]
It doesn't make sense to maintain a "bug" compatibility, does it?

**Comment by zhexuany** [comment]
@CrazyNash Kindly remind you, although the links showing "bug", it actually a feature request. You can certainly take a look over that website. Thanks. ;)

**Comment by nullnotnil** [comment]
Check constraints are now on the roadmap! The majority of the work is already done. You can track the project at: https://github.com/pingcap/tidb/projects/46

I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
