### ISSUE TITLE
Select create doesn't work

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#6766]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql> CREATE TABLE User_Higher_Than_200  SELECT User_ID, SUM(Score) FROM User_Score  GROUP BY User_ID  HAVING SUM(Score) > 200;
ERROR 1105 (HY000): line 1 column 41 near " User_ID, SUM(Score) FROM User_Score  GROUP BY User_ID  HAVING SUM(Score) > 200" (total length 120)
```
2. What did you expect to see?

success

3. What did you see instead?

failed with error

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.0.1

**Comment by zhexuany** [comment]
@CrazyNash 

Thanks for using `TiDB`.

Have you tried this query in `MySQL` 5.7? `TiDB` is only compatible with this version of `MySQL`. 

In addition, could you also provide table's schema? It can help us better assisting you regarding of this issue.

**Comment by zhexuany** [comment]
You can get a table schema by using `show create table` syntax. For example, if you have a table whose name is `t`, `show create table t` will give us a result. You can simply copy and past the result here.

**Comment by CrazyNash** [comment]
This is from mysql
>mysql> show create table User_Score;
+------------+-----------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                      |
+------------+-----------------------------------------------------------------------------------------------------------------------------------+
| User_Score | CREATE TABLE `User_Score` (
  `User_ID` int(11) DEFAULT NULL,
  `Score` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 |
+------------+-----------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)


This is from TiDB
>MySQL [test]> show create table User_Score;
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| Table      | Create Table                                                                                                                                     |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
| User_Score | CREATE TABLE `User_Score` (
  `User_ID` int(11) DEFAULT NULL,
  `Score` float DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+------------+--------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.03 sec)

**Comment by zhexuany** [comment]
Thanks for your help. It is an compatibility issue. We will fix it shortly. Please keep a eye on this issue, once this get closed meaning such problem is resolved at upstream.

**Comment by zz-jason** [comment]
duplicated with https://github.com/pingcap/tidb/issues/4754
