### ISSUE TITLE
Intersect

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#6767]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

mysql> SELECT Txn_Date FROM Store_Information
    -> INTERSECT
    -> SELECT Txn_Date FROM Internet_Sales;
ERROR 1105 (HY000): line 3 column 7 near " Txn_Date FROM Internet_Sales" (total length 84)

2. What did you expect to see?

success

3. What did you see instead?

failed

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.0.1

**Comment by winkyao** [comment]
Sees like mysql not support `INTERSECT` syntax too? TiDB is compatible with MySQL 5.7, what is your MySQL version?

**Comment by CrazyNash** [comment]
Just verified by mysql 5.7.22, it failed too.

Feel free to make this as a feature request or close it. 

Thanks!

**Comment by morgo** [comment]
Thank you.  I will close this issue for now.  Please feel free to re-open it if you have followup questions!
