### ISSUE TITLE
MINUS doesn't work

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#6768]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

mysql> SELECT Txn_Date FROM Store_Information
    -> MINUS
    -> SELECT Txn_Date FROM Internet_Sales;
ERROR 1105 (HY000): line 3 column 7 near " Txn_Date FROM Internet_Sales" (total length 80)

2. What did you expect to see?

success

3. What did you see instead?

failed

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.0.1

**Comment by spongedu** [comment]
MySQL seems doesn't support `MINUS`, `INTERSECTION` operator. Is this a `MariaDB` behavior?

**Comment by shenli** [comment]
@CrazyNash TiDB/MySQL doesn't support this syntax. Please refer to the documents.
