### ISSUE TITLE
select from dual can not do order by

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#6782]
1. What did you do?
If possible, provide a recipe for reproducing the error.

```
mysql> select 1 as a from dual order by a;
```

2. What did you expect to see?

```
mysql> select 1 as a from dual order by a;
+---+
| a |
+---+
| 1 |
+---+

```

3. What did you see instead?

```
mysql> select 1 as a from dual order by a;
ERROR 1105 (HY000): line 1 column 29 near " by a" (total length 34)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.1.0-alpha-25-gdb4888a6-dirty
Git Commit Hash: db4888a6976ad85f81e3e1289d7b7fabc411883a
Git Branch: dev-check-union-limit
UTC Build Time: 2018-06-07 10:56:33
GoVersion: go version go1.10.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-2f291dc12b0e05d71eb8873881c3ed11d343d6e6

**Comment by mail2fish** [comment]
After traced the issue in the tidb-server, I found that error was raised at parser/yy_parser.go:103 line.  Are there some documents for the parser developing?
