### ISSUE TITLE
CPU is too high

### ISSUE THREAD

**Issue by cnwarden** [pingcap/tidb#6794]
3PD, 3TIKV, 3TIDB

one tidb cpu is **too high**,(48 vcore, cpu usages is about **4200%**, all is about **90%**), but other two are very low. when I kill one, other one will be high.

May I know how to know the detail of the workload of TIDB?

**Comment by jackysp** [comment]
Thank you for your feedback! @cnwarden 
TiDB grafana -> Query Summary -> QPS by instance may help you for the detail workload of TiDB.

**Comment by cnwarden** [comment]
about 10k

**Comment by jackysp** [comment]
10k on only one TiDB instance? The other two are 0?
I think it depends on your load balance component.

**Comment by zhexuany** [comment]
@cnwarden It will be more helpful if you can also provide the topology of your deployment.

**Comment by zhexuany** [comment]
@cnwarden Any updates?

**Comment by cnwarden** [comment]
let me close it now, once happen again, raise new one.
