### ISSUE TITLE
tidb secondary index strategy

### ISSUE THREAD

**Issue by gouchaoer** [pingcap/tidb#6799]
hey, i have a table for log:
id int auto_incremet,
day date,
msg varchar(128),
primary key(id),
key(day)

as you can see the day column is always the same. when i insert man logs, does this cause a hot region problem for the index kv pair?

**Comment by gouchaoer** [comment]
i don't like the application sharding method such as log_1, log_2...log_n to avoid timestamp index's hot region problem. i can  use a day/hour instead of seconds for time column

**Comment by shenli** [comment]
@gouchaoer Sorry, I can not get your point.

**Comment by gouchaoer** [comment]
我是说我有一张log表，需要给timestamp加索引方便查询，但是文档里说这样会导致热点region存在（timestamp的索引是kv pair，而timestamp是有序的）。。。但是如果我把timestamp换成date的话（我接受只按天的精读来查询），由于一天以内的插入的log的date字段都是一样的，所以在tikv中如果tikv的kv pair的key是不稳定排序的话，那么log就可以分散到所有region不存在插入热点，否则就存在热点，到底是哪一种情况呢？

**Comment by morgo** [comment]
I believe this overlaps with this feature request: https://github.com/pingcap/tidb/issues/9469 ?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
