### ISSUE TITLE
time_test failure

### ISSUE THREAD

**Issue by mtorromeo** [pingcap/tidb#68]
Hi,
when running the tests I get a failure:

```
FAIL: time_test.go:292: testTimeSuite.TestCodec

time_test.go:305:
    c.Assert(t.String(), Not(Equals), t1.String())
... obtained string = "2010-10-10 10:11:11"
... expected string = "2010-10-10 10:11:11
```

I think the problem is that the tested timezone is equal to my local timezone while it is assumed to be different.

**Comment by siddontang** [comment]
Hi @mtorromeo 
can you tell me what's your timezone?

**Comment by mtorromeo** [comment]
`Europe/Rome` which is equivalent to the tested `Europe/Berlin`.

**Comment by siddontang** [comment]
got it. 
We will fix it ASAP.

**Comment by qiuyesuifeng** [comment]
fixed.

@mtorromeo  u can update tidb and try again.
Thanks for report.

**Comment by mtorromeo** [comment]
Yep, it works now.
Thanks for the fast fix!
