### ISSUE TITLE
syncer：Sync mysql data error when  using syncer

### ISSUE THREAD

**Issue by a13794479495** [pingcap/tidb#6801]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I drops the colunm 'goods_channel_id' of the table 'city_shop_tag',
and then mysql automatically drops the index 'goods_channel_id_index' together.
when syncer sync this DDL statement and then tidb executes, 
syncer reports an error，as following picture shows,the error is  so clear,please help.

2. What did you expect to see?
Normal synchronous data

3. What did you see instead?

![image](https://user-images.githubusercontent.com/18589654/41209852-a19441ee-6d60-11e8-8fac-2466ef2d0d43.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.2

**Comment by wilanhuang** [comment]
It is the DDL restriction of TiDB ： DROP COLUMN 操作目前不支持删除的列为主键列或索引列

**Comment by a13794479495** [comment]
OK，thanks
