### ISSUE TITLE
Prometheus monitoring the meaning of tidb alarm item

### ISSUE THREAD

**Issue by xgmxgmxm** [pingcap/tidb#6802]
Please answer these questions before submitting your issue. Thanks!

pd.rules.yml
tidb.rules.yml
tikv.rules.yml

How to understand the alarm items in these configuration files and how to find out the values?

**Comment by ljluestc** [comment]
配置文件（pd.rules.yml、tidb.rules.yml 和 tikv.rules.yml）通常用于在 TiDB 环境中设置监控和警报规则 。 这些规则通常与 Prometheus 和 Grafana 等监控系统一起使用。

But, is there any specific questions with more technical details so we could possibly assist?

**Comment by jebter** [comment]
The lifecycle of version 4.0 and earlier has ended. Let's close it. https://www.pingcap.com/tidb-release-support-policy/
