### ISSUE TITLE
"CONVERT_TZ()" error message differ to mysql

### ISSUE THREAD

**Issue by DavisLinDB** [pingcap/tidb#6807]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

"CONVERT_TZ()" error message differ to mysql

2. What did you expect to see?

MySQL:
```
SELECT CONVERT_TZ("2018-06-07 3:00:00","EDT","MET");
+----------------------------------------------+
| CONVERT_TZ("2018-06-07 3:00:00","EDT","MET") |
+----------------------------------------------+
| NULL                                         |
+----------------------------------------------+
```

3. What did you see instead?

TiDB:
```
SELECT CONVERT_TZ("2018-06-07 3:00:00","EDT","MET");
ERROR 1105 (HY000): open /usr/local/go/lib/time/zoneinfo.zip: no such file or directory
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

5.7.10-TiDB-v2.1.0-alpha-13-g8a326ca

**Comment by DavisLinDB** [comment]
@zz-jason 

centos-release-7-4.1708.el7.centos.x86_64
I use https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md to deploy.
I don't install golang and set $GOROOT manually.

**Comment by zz-jason** [comment]
@tiancaiamao PTAL

**Comment by zz-jason** [comment]
1. When we can not find the zip file, we should not throw the error to the client, this issue describes this problem
2. When we can not find the time zone in that zip file, we should throw the error to the client either, the following case describes this problem:
```sql
TiDB(localhost:4000) > SELECT CONVERT_TZ("2018-06-07 3:00:00","EDT","MET");
ERROR 1105 (HY000): cannot find EDT in zip file /Users/jianzhang.zj/opt/goroot/lib/time/zoneinfo.zip
```

**Comment by lysu** [comment]
https://github.com/golang/go/blob/161874da2ab6d5372043a1f3938a81a19d1165ad/src/time/zoneinfo_unix.go#L21 

EDT not find in `/usr/share/zoneinfo/`

**Comment by zz-jason** [comment]
@lysu The right result of this query should be `NULL`, instead we should handle the error returned by golang lib and returns `NULL` as well.

**Comment by tiancaiamao** [comment]
Either "EDT" or "MET" is an invalid time zone, but TiDB should not return error.
We'll improve it. 
Thanks for your feedback. @DavisLinDB

**Comment by DavisLinDB** [comment]
@zz-jason 

When I using CONVERT_TZ() with "MET" or others in MySQL, I use mysql_tzinfo_to_sql to generate the time zone tables. I saw the discussion above, TiDB use golang lib to do so.  So I don't need to use mysql_tzinfo_to_sql to generate the time zone tables? Or it's unuseful although I generate the time zone tables to TiDB?  If TiDB need the zip files, will modify the ansible deploy process to avoid the problem?

**Comment by morgo** [comment]
This has been improved in the latest TiDB:
```
mysql> SELECT CONVERT_TZ("2018-06-07 3:00:00","EDT","MET");
ERROR 1105 (HY000): unknown time zone EDT
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta.1-54-g3dbea7930
Git Commit Hash: 3dbea79303158300fd954ed93f6876e53d411f66
Git Branch: improve-log-message
UTC Build Time: 2019-04-05 05:49:00
GoVersion: go version go1.12.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

It is not identical to MySQL out of the box, as MySQL does not load the TZ tables by default.  But I think it is an improvement, and useful for applications.

I am going to close this issue now.  Thank you for the bug report.
