### ISSUE TITLE
How to get tikv-metrics from tikv-node, not use push-gateway

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#6811]
I deployed tidb-cluster as [ docker-deploy](https://pingcap.com/docs-cn/op-guide/docker-deployment/)

I wanted to get metrics from tidb. I know that every node in tidb-cluster is a exporter-node, and I didn't want to get metrics from push-gateway.

I got tidb metrics from http://{TIDB_HOST}:10080/metrics, got pd metrics from http://{PD_HOST}:2379/metrics, **but I cannot find any way to get tikv metrics**

What should I do to get tikv metrics, not use push-gateway?

**Comment by breeswish** [comment]
I think you can't without modifying code. TiKV uses rust-prometheus and it directly pushes metrics to the push gateway using protobuf protocol. Also there is no http API in TiKV for now. At least you need a metric export API exposed via TiKV's gRPC interface.

**Comment by dayuanyuan1989** [comment]
Thanks for your support.

**Comment by breeswish** [comment]
@dayuanyuan1989 If you really need this feature, you can open an issue in TiKV :) And we will give it some priority and implement it like what I said if many users request for it. Anyway, we may expose it via gRPC APIs, still not HTTP APIs.

**Comment by baiwfg2** [comment]
However, I can get metrics from localhost:20180/metrics on tikv server, which means if I start a prometheus server on the same host as tikve, I can get its metrics from /metrics. Why is that ?

**Comment by breeswish** [comment]
@baiwfg2 This is our new feature added to TiKV recently, supporting pulling metrics in the same way as TiDB does.
