### ISSUE TITLE
Error Code: 1105. runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by anjieych** [pingcap/tidb#6828]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
  ```
create table a (f1 int ,f2 varchar(32) ,primary key (f1));
  insert into a(f1,f2) 
  values(1,'a'),
  (2,'b'),
  (3,'c');
  
  select a.*
  from a
  inner join (
	select 1 as k1,'k2-1' as k2
    union all select 4,'k2-4'
  ) as k on a.f1=k.k1
  where a.f1<3 and k.k2!='k2-3';
```

2. What did you expect to see?
```
get correct return:
------------
f1       f2
1         a
```

3. What did you see instead?

`**Error Code: 1105. runtime error: invalid memory address or nil pointer dereference**`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)? `5.7.10-TiDB-v2.0.0`

**Comment by shenli** [comment]
@anjieych Thanks for your feedback!
Please post the full output of `select tidb_version();` here.

**Comment by anjieych** [comment]
Release Version: v2.0.0
Git Commit Hash: 637e130e6a9ba2e54e158131c0466233db39a60e
Git Branch: release-2.0
UTC Build Time: 2018-04-27 11:43:00
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1

**Comment by coocood** [comment]
@anjieych 
Thank you for your report, we have reproduced this bug, we'll fix it soon.
