### ISSUE TITLE
Behavior of str_to_date() is different from mysql

### ISSUE THREAD

**Issue by iamtianyuan** [pingcap/tidb#6835]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
`select str_to_date('2018-6-14', '%Y-%m-%d');`
`select str_to_date('2018-6-14', '%Y-%c-%d');`

2. What did you expect to see?
'2018-06-14'

3. What did you see instead?
NULL

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-alpha-48-ge2c8c4e
UTC Build Time:  2018-06-13 12:05:19

**Comment by mail2fish** [comment]
I am looking into it.

**Comment by zz-jason** [comment]
@mail2fish Thanks for your contribution, hope the following message can help you to solve this issue, in the source file **types/time.go**:
```go
2411 func monthNumericTwoDigits(t *MysqlTime, input string, ctx map[string]int) (string, bool) {
2412     v, succ := parseDigits(input, 2)
2413     if !succ || v > 12 {
2414         return input, false
2415     }
2416
2417     t.month = uint8(v)
2418     return input[2:], true
2419 }
```

we should not just pass parameter `2` to the function `parseDigits`
