### ISSUE TITLE
How to disable pprof to prevent it listens 8888

### ISSUE THREAD

**Issue by Unknwon** [pingcap/tidb#684]
This behavior is completely unexpected and seems no way to turn it off.

**Comment by ngaut** [comment]
Hi:
Currently, we don't have any flag to disable pprof. Does it bother you ? Or you just want to change default port number?

**Comment by Unknwon** [comment]
Yes, it feels like a ghost port when embedded to other port, I want to a way to disable it.

**Comment by ngaut** [comment]
Just set Debug flag to false. @Unknwon 
https://github.com/pingcap/tidb/blob/master/tidb.go#L91

**Comment by Unknwon** [comment]
From what I understand, the `Debug` will never be `false` before TiDB starts listening on port 8888.

Because it is put in [init function](https://github.com/pingcap/tidb/blob/master/tidb.go#L354), and it always executes before my code.

**Comment by ngaut** [comment]
We need to figure out a better way to handle this if you don't want to patch the source.
We need to keep pporf open for debugging....

**Comment by Unknwon** [comment]
Any other entry point (function) must be called for using TiDB?

**Comment by ngaut** [comment]
Nop, we may support it by configuration later.

**Comment by Unknwon** [comment]
Maybe disable by environment variable?

e.g. `TIDB_DEBUG=0`

**Comment by ngaut** [comment]
LGTM, Could you send a PR ? Thanks.

**Comment by Unknwon** [comment]
Sure, should I remove `Debug` variable? Or keep it and set its value by reading the env variable?

**Comment by Unknwon** [comment]
https://github.com/pingcap/tidb/pull/687
