### ISSUE TITLE
please support savepoint

### ISSUE THREAD

**Issue by aesirteam** [pingcap/tidb#6840]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```sql
START TRANSACTION;
SELECT 1 FROM dual;
SAVEPOINT save1;
SELECT 1 FROM dual;
ROLLBACK TO SAVEPOINT save1;
COMMIT;
```

2. What did you expect to see?

All statements succeed.

3. What did you see instead?

```sql
mysql> START TRANSACTION;
Query OK, 0 rows affected (0.00 sec)

mysql> SELECT 1 FROM dual;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

mysql> SAVEPOINT save1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 9 near "SAVEPOINT save1" 
mysql> SELECT 1 FROM dual;
+---+
| 1 |
+---+
| 1 |
+---+
1 row in set (0.00 sec)

mysql> ROLLBACK TO SAVEPOINT save1;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 11 near "TO SAVEPOINT save1" 
mysql> COMMIT;
Query OK, 0 rows affected (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-alpha-48-ge2c8c4e
Git Commit Hash: e2c8c4e9758b038b24fc05794a266a678570f7a6
Git Branch: master
UTC Build Time: 2018-06-13 12:05:19
GoVersion: go version go1.10.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-c4133d3ef0f099f8716a916c198390b26293ec00

**Comment by zimulala** [comment]
@aesirteam 
We don't support `savepoint`, and it isn't on our roadmap now.

**Comment by breeswish** [comment]
Duplicate with https://github.com/pingcap/tidb/issues/3663

**Comment by lysu** [comment]
@muyu66  yes, `savepoint` is a very useful feature,  it's not on our short-term roadmap, but we maybe try to implement that in future, and welcome to contribute too~

**Comment by ihipop** [comment]
@lysu  https://github.com/pingcap/docs/pull/682   this pull just  add the compatibility of `savepoint`,not the function of savepoint,is it right?

**Comment by lysu** [comment]
@ihipop , yes , savepoint isn't supported until now..

**Comment by chris-ng-scmp** [comment]
Good to see if savepoint can be supported

**Comment by wuwangben** [comment]
Is there a plan to support savepoint?

**Comment by wzru** [comment]
Recently when I test GORM and TiDB compatibility (inspired by https://github.com/pingcap/tidb/issues/24194)
GORM tests failed because TiDB has not supported SAVEPOINT:
```bash
2021/08/16 11:14:38 gorm.io/driver/mysql@v1.1.1/mysql.go:330 
Error 1064: You have an error in your SQL syntax; 
check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 11 near "TO SAVEPOINT save_point1"
[0.190ms] [rows:0] ROLLBACK TO SAVEPOINT save_point1
--- FAIL: TestTransactionWithSavePoint (0.01s)
    transaction_test.go:193: Should not find rollbacked record
```
With SAVEPOINT supported, TiDB will also be more compatible with GORM.

**Comment by bb7133** [comment]
@wzru Yes, savepoint is on the roadmap, thanks!

**Comment by Allan-Nava** [comment]
Any news?

**Comment by xujiajun** [comment]
+1

**Comment by cjphaha** [comment]
Is it supported now?

**Comment by crazycs520** [comment]
I will work on this now

**Comment by cjphaha** [comment]
> I will work on this now

Hi bro, is it convenient to ask? Which version supports savepoint？

**Comment by crazycs520** [comment]
> > I will work on this now
> 
> Hi bro, is it convenient to ask? Which version supports savepoint？

If it goes well, savepoint may be supported in TiDB v6.2.0.

**Comment by mstao** [comment]
+1, Seata needs the support of saveponit

**Comment by miadabrin** [comment]
+1 We need it as well since django uses it heavily to run tests (and roll them back)
https://code.djangoproject.com/ticket/28263

**Comment by fishfree** [comment]
@crazycs520 I notice v6.2.0 just released, is the feature SAVEPOINT added in it?

**Comment by xhebox** [comment]
> @crazycs520 I notice v6.2.0 just released, is the feature SAVEPOINT added in it?

Yes. You could check release notes [here](https://docs.pingcap.com/tidb/v6.2/release-6.2.0). It seems that github release notes are not completed.

**Comment by HashZhang** [comment]
Since savepoint is implemented, why is it still stated that in the document:
> @Transactional(propagation = Propagation.NESTED) is not supported

**Comment by Icemap** [comment]
> Since savepoint is implemented, why is it still stated that in the document:
> @transactional(propagation = Propagation.NESTED) is not supported

@HashZhang Nice catch! I'll update develop guide ASAP.

**Comment by Icemap** [comment]
Actually, I already updated the [Choose Driver or ORM](https://docs.pingcap.com/tidb/v6.2/dev-guide-choose-driver-or-orm#java-orm-frameworks) doc.
So, as we talked before. Maybe cheery-pick this PR to all versions is a good idea? @Oreoxmt PTAL

![image](https://user-images.githubusercontent.com/26212551/200994038-c93075cc-5b6d-4c1f-b5b4-530b2fa5e91c.png)

**Comment by Oreoxmt** [comment]
> Actually, I already updated the [Choose Driver or ORM](https://docs.pingcap.com/tidb/v6.2/dev-guide-choose-driver-or-orm#java-orm-frameworks) doc. So, as we talked before. Maybe cheery-pick this PR to all versions is a good idea? @Oreoxmt PTAL
> 
> ![image](https://user-images.githubusercontent.com/26212551/200994038-c93075cc-5b6d-4c1f-b5b4-530b2fa5e91c.png)

This note has been added to v6.1 and later versions. https://docs.pingcap.com/tidb/stable/dev-guide-choose-driver-or-orm
