### ISSUE TITLE
alert:region_err

### ISSUE THREAD

**Issue by sdoheji1234** [pingcap/tidb#6841]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

[FIRING:1] TiDB_tikvclient_region_err_total puyi-cluster tidb_4000 tidb not_leader (puyi-cluster increase( tidb_tikvclient_region_err_total[10m] )  > 6000 emergency prometheus)
alert: instance: tidb_4000 values: 21680.40201005025 TiDB tikvclient_backoff_count error 21680.40201005025
Alerts Firing:
Labels:
 - alertname = TiDB_tikvclient_region_err_total
 - cluster = puyi-cluster
 - env = puyi-cluster
 - expr = increase( tidb_tikvclient_region_err_total[10m] )  > 6000
 - instance = tidb_4000
 - job = tidb
 - level = emergency
 - monitor = prometheus
 - type = not_leader
Annotations:
 - description = alert: instance: tidb_4000 values: 21680.40201005025
 - summary = TiDB tikvclient_backoff_count error
 - value = 21680.40201005025
Source: http://10.2.0.78:9090/graph?g0.expr=increase%28tidb_tikvclient_region_err_total%5B10m%5D%29+%3E+6000&g0.tab=1

AlertmanagerUrl:
http://monitor:9093/#/alerts?receiver=wechat

This is the Prometheus alarm,but I don't understand the impact of this warning on tikv.

2. What did you expect to see?

I hope not error

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Server version: 5.7.10-TiDB-v2.0.0-rc.4-174-g57c0101 MySQL Community Server (Apache License 2.0)

**Comment by zimulala** [comment]
@sdoheji1234 
Thanks for your feedback!
Could you give me a screenshot of the `leader` module on the `Cluster` panel in the `TiKV` page on grafana at that time?
And please give me some error information about `NotLeader` in tikv.log. You can use this operation `grep -i "NotLeader" -C 30 tikv.log`.

**Comment by sdoheji1234** [comment]
Tikv.log does not have this error in it.
But there's a mistake in alert.
<img width="1283" alt="a452bf3f-30c2-41d7-94de-5e3c2664f6d6" src="https://user-images.githubusercontent.com/39373173/41576252-e3b6dbbe-73b8-11e8-9a0f-45cb94fff609.png">

**Comment by tiancaiamao** [comment]
When you get an alert, you should check the `grafana` to verify  what's happening.
Was tikv too busy at that time? was there any machine of the cluster down? @sdoheji1234

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
