### ISSUE TITLE
talbe scan stop without any errors

### ISSUE THREAD

**Issue by gensmusic** [pingcap/tidb#6848]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
We have about 70000000 data in one table, and we want to import data to elasticsearch.
Here is what we do.
We use golang to do sql.Query(), then
```
for rows.Next() {
// handle error and send to elasticsearch
}
```
It run for  about 25 minites then stop without any error.
But we only handle about 35000000 data.
Is there any timeout for a query in tidb ?

2. What did you expect to see?

All data is imported.

3. What did you see instead?

Only about half of data is imported.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

2.0.0

**Comment by shenli** [comment]
@gensmusic Thanks for your feedback!
Please provide more information. From your description, I can not tell what happened.
Can you provide the reproduce process?

**Comment by gensmusic** [comment]
ok, I got the err
`[Err] 9006 — GC life time is shorter than transaction duration`

**Comment by winoros** [comment]
@gensmusic Sorry for late response, this is a hard-coded limit. May i know the procedure you used for importing data?

**Comment by gensmusic** [comment]
We just want to scan a very big table and get all the data, so we can analyse and send them to es or other systems. It's too big to finish this job in an hour, therefore I encounter this error every time after running about 25 minute more or less. With golang, it's like the following.

```
rows, err := sql.Query(`select * from account`)
if err ! =nil {
	panic(err)
}

for rows.Next() {
	err := rows.Scan(...)
	if err != nil {
                panic(err)
	}
	// do something with the data
}

if err := rows.Err(); err != nil {
	panic(err) // here is the error! [Err] 9006 — GC life time is shorter than transaction duration
}
```

**Comment by shenli** [comment]
@gensmusic Please enlarge the GC lifetime. Please refer to [this doc](https://github.com/pingcap/docs/blob/master/op-guide/gc.md).
To make a long story short: if the query exceeds GC lifetime, TiDB could not guarantee the data you are reading is there. So you get the error.

**Comment by winoros** [comment]
@gensmusic If there's any index existing. Use the index and construct the range scan to limit the data you read once.
And hence you can also start multiple thread to importing your data.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
