### ISSUE TITLE
ERROR 1105 (HY000): ERROR 1105 (HY000): command 17 not supported now

### ISSUE THREAD

**Issue by denghuancong** [pingcap/tidb#6862]
> base info:
tidb : v2.0.1
two lb machine , deploy using proxysql  and  access through vip, we config two user for proxysql and tidb , one is uadmin, the other is root,  uadmin for monitor the tidb cluster. root for access  data.
three tidb machine as mysql-server

we using vip through proxysql access tidb, when we input command as following , it ouput error, and we post issue to the porxysql group , they said the reason is tidb don;t support CHANGE_USER protocol of mysql.
```
// error info 
mysql> show databases;
ERROR 1105 (HY000): ERROR 1105 (HY000): command 17 not supported now
```

#### the issue about proxysql is :
https://github.com/sysown/proxysql/issues/1557

**Comment by coocood** [comment]
@denghuancong 
Command CHANGE_USER has been supported in v2.0.4, please upgrade the TiDB cluster.
