### ISSUE TITLE
order by IFNULL and limit throw error 'runtime error: index out of range'

### ISSUE THREAD

**Issue by majian159** [pingcap/tidb#6864]
```SQL
CREATE TABLE `tB` (
  `ReplyTime` datetime(3) NOT NULL,
  `Pid` bigint(20) NOT NULL,
  `Id` bigint(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

CREATE TABLE `tA` (
  `SendTime` datetime(3) NOT NULL,
  `Id` bigint(20) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
```SQL
  select ifnull(b.ReplyTime,a.SendTime)
  from tA a left join tB b on a.id=b.PId
  order by ifnull(b.ReplyTime,a.SendTime) desc
  limit 10
```

> 2018-06-20T03:54:32.604973000Z 2018/06/20 03:54:32.603 column.go:315: [error] Can't find column b.replytime in schema Column: [a.sendtime,a.id] Unique key: [[a.id]]
2018-06-20T03:54:32.605294000Z 2018/06/20 03:54:32.603 column.go:315: [error] Can't find column b.replytime in schema Column: [a.sendtime,a.id] Unique key: [[a.id]]
2018-06-20T03:54:32.610886000Z panic: runtime error: index out of range

**Comment by winoros** [comment]
Thanks for your reporting!
@majian159  What version of tidb do you use? You can use `select tidb_version()` to get the information.

**Comment by majian159** [comment]
@winoros 
Release Version: v2.1.0-alpha-56-g3c0bfc1
Git Commit Hash: 3c0bfc19b252c129f918ab645c5e7d34d0c3d154
Git Branch: master
UTC Build Time: 2018-06-19 12:29:08
GoVersion: go version go1.10.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-c4133d3ef0f099f8716a916c198390b26293ec00

**Comment by winoros** [comment]
@majian159 Patch to fix this issue now is in reviewing.
