### ISSUE TITLE
Is there any user manual about binary deployment, besides the ansible deployment?

### ISSUE THREAD

**Issue by sunism** [pingcap/tidb#6878]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by tiancaiamao** [comment]
Hi, @sunism 
Here is the document:
https://pingcap.com/docs/op-guide/binary-deployment/

But we suggest you to use the ansible deployment, it's easier to maintain for a large cluster.

**Comment by kolbe** [comment]
Hi @sunism, we haven't heard anything from you in quite a while on this, so I'm going to close this issue now. If you have any more questions about binary deployments, feel free to re-open!
