### ISSUE TITLE
rolling update faild while check current PD leader

### ISSUE THREAD

**Issue by calmzealA** [pingcap/tidb#6881]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I am updating tidb using ansible. from V1.0.6,to v2.0.4
Following this guide:
https://www.pingcap.com/docs-cn/op-guide/tidb-v2-upgrade-guide/

> ansible-playbook rolling_update.yml

2. What did you expect to see?
Update success.
We have success update tidb from 1.0.6 to v2.0.3 in the **TEST ENV** before。

3. What did you see instead?
we have 3 pds, the 1st and 2nd update with no error.
the 3rd pd report error:

Ansible FAILED! => playbook: rolling_update.yml; TASK: check current PD leader; message: {"msg": "The conditional check 'pd_leader_info.json.name is defined and pd_leader_info.json.name != pd_name' failed. The error was: error while evaluating conditional (pd_leader_info.json.name is defined and pd_leader_info.json.name != pd_name): 'dict object' has no attribute 'json'"}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v1.0.6-1

ps:
When check the rolling_update.yml：
https://github.com/pingcap/tidb-ansible/blob/master/rolling_update.yml

> # curl http://xxxxxx.139:2379/pd/api/v1/leader
> {
>   "name": "pd3",
>   "member_id": 6795350017215450226,
>   "peer_urls": [
>     "http://xxxxx.139:2380"
>   ],
>   "client_urls": [
>     "http://xxxxx.139:2379"
>   ]
> }

I make a post as the rolling_update.yml does.
> [root]# curl -X POST http://xxxxx.139:2379/pd/api/v1/leader/resign
> null
> [root]# curl -X POST http://xxxx.139::2379/pd/api/v1/leader/resign
> no leader

then i check it

> [root]# curl http://1xxx.139:2379/pd/api/v1/leader
> no leader
> [root]# curl http://1xxxx.139:2379/pd/api/v1/leader
> no leader
> [root]# curl http://1xxxx.139:2379/pd/api/v1/leader
> {
>   "name": "pd3",
>   "member_id": 6795350017215450226,
>   "peer_urls": [
>     "http://xxxxx.139:2380"
>   ],
>   "client_urls": [
>     "http://xxx.139:2379"
>   ]
> }

**Comment by calmzealA** [comment]
It seems PD3 can not transfer  to another PD server

**Comment by ciscoxll** [comment]
@calmzealA Please provide more log information for `PD3`.

**Comment by calmzealA** [comment]
@ciscoxll 
谢谢
已经处理好了。

主要的问题在于每次选举leader都是pd3，可能跟pd1,pd2已经升级到2.0.4,pd3还是1.0.6有关。
然后我们采用下面的方法绕过了：
1. 手动停掉 pd3。 这时候leader能切换到pd1。
2. 修改inventory.ini，在PD list 配置里面，将PD3 放在第一个。（否则，再次执行rolling update，还是会从pd1，pd2开始升级，这样会将leader再切到pd3.）
3. 执行升级。

**Comment by liuhuanHappyStudy** [comment]
您好。请教一个问题：如果我配置一个PD，能够实现滚动升级吗？
我的配置：PD和TiDB各配置一个，并且在一台机器上。TiKV配置三个，分别在三台服务器上。
172.18.5.9 PD和TiDB
172.18.5.10    TiKV1
172.18.5.11    TiKV2
172.18.5.12    TiKV3

使用：tidb-ansible将TiDB v2.1.0-rc.3滚动升级到TiDB-v3.0.0。遇到如下问题：


[tidb@izwz9gckpmdcwq2glh1kitz tidb-ansible]$ ansible-playbook excessive_rolling_update.yml

PLAY [check config locally] ***************************************************************
TASK [check_config_static : Ensure only one monitoring host exists] ***********************
TASK [check_config_static : Ensure monitored_servers exists] ******************************
TASK [check_config_static : Ensure TiDB host exists] **************************************
TASK [check_config_static : Ensure PD host exists] ****************************************
TASK [check_config_static : Ensure TiKV host exists] **************************************
TASK [check_config_static : Check ansible_user variable] **********************************
TASK [check_config_static : Ensure timezone variable is set] ******************************
TASK [check_config_static : Close old SSH control master processes] ***********************
ok: [localhost]

PLAY [check system environment] ***********************************************************

TASK [check_system_dynamic : Disk space check - Fail task when disk is full] **************
ok: [172.18.5.9]

TASK [check_system_dynamic : get facts] ***************************************************
ok: [172.18.5.9]

TASK [check_system_dynamic : Preflight check - Get hostnames of all nodes in cluster] *****
ok: [172.18.5.9]

TASK [check_system_dynamic : Preflight check - Does every node in cluster have different hostname] ***

TASK [check_system_dynamic : Preflight check - Get NTP service status] ********************
ok: [172.18.5.9]

TASK [check_system_dynamic : Preflight check - NTP service] *******************************

TASK [check_system_dynamic : Preflight check - Get umask] *********************************
ok: [172.18.5.9]

TASK [check_system_dynamic : Preflight check - Does the system have a standard umask] *****

TASK [check_system_dynamic : Preflight check - Get maximum number of open file descriptors limit] ***
ok: [172.18.5.9]

TASK [check_system_dynamic : Preflight check - ulimit -n] *********************************

TASK [check_system_dynamic : Preflight check - Check swap] ********************************

PLAY [gather all facts, and check dest] ***************************************************

TASK [check_config_dynamic : Set enable_binlog variable] **********************************

TASK [check_config_dynamic : Set deploy_dir if not set] ***********************************

TASK [check_config_dynamic : environment check (deploy dir)] ******************************
ok: [172.18.5.11]
ok: [172.18.5.10]
ok: [172.18.5.12]
ok: [172.18.5.9]

TASK [check_config_dynamic : Preflight check - Does deploy dir have appropriate permission] ***

TASK [check_config_dynamic : environment check (supervise)] *******************************

TASK [check_config_dynamic : config skip variables (default)] *****************************
ok: [172.18.5.9]
ok: [172.18.5.11]
ok: [172.18.5.10]
ok: [172.18.5.12]

TASK [check_config_dynamic : config skip variables] ***************************************
ok: [172.18.5.9]
ok: [172.18.5.10]
ok: [172.18.5.11]
ok: [172.18.5.12]

TASK [check_config_dynamic : config skip variables] ***************************************

PLAY [Pre-check for rolling update] *******************************************************

TASK [shell] ******************************************************************************
changed: [172.18.5.9]

TASK [Check whether can perform rolling update] *******************************************

PLAY [rolling update PD cluster] **********************************************************

TASK [set_fact] ***************************************************************************
ok: [172.18.5.9]

TASK [include_tasks] **********************************************************************
included: /home/tidb/tidb-ansible/common_tasks/get_pd_name.yml for 172.18.5.9

TASK [get PD name] ************************************************************************
ok: [172.18.5.9]

TASK [set_fact] ***************************************************************************
ok: [172.18.5.9]

TASK [display PD name] ********************************************************************
ok: [172.18.5.9] => {
    "pd_name": [
        "pd_izwz9gckpmdcwq2glh1kitz"
    ]
}

TASK [display PD address] *****************************************************************
ok: [172.18.5.9] => {
    "pd_addr": "172.18.5.9:2379"
}

TASK [include_tasks] **********************************************************************
included: /home/tidb/tidb-ansible/common_tasks/get_pd_leader.yml for 172.18.5.9

TASK [get PD leader info] *****************************************************************
ok: [172.18.5.9]

TASK [include_tasks] **********************************************************************

TASK [include_tasks] **********************************************************************
included: /home/tidb/tidb-ansible/common_tasks/transfer_pd_leader.yml for 172.18.5.9

TASK [set_fact] ***************************************************************************
ok: [172.18.5.9]

TASK [display PD leader name] *************************************************************
ok: [172.18.5.9] => {
    "pd_leader_name": "pd_izwz9gckpmdcwq2glh1kitz"
}

TASK [transfer PD leader to another PD server] ********************************************

TASK [transfer PD leader to another PD server when enable_tls|default(false)] *************

TASK [wait for transfering PD leader] *****************************************************

TASK [check current PD leader] ************************************************************

TASK [check current PD leader when enable_tls|default(false)] *****************************

TASK [stop PD by supervise] ***************************************************************

TASK [stop PD by systemd] *****************************************************************
changed: [172.18.5.9]

TASK [wait until the PD port is down] #刚开始停在这里很长时间（等待PD端口关闭），然后就报错了*****************************************************
fatal: [172.18.5.9]: FAILED! => {"changed": false, "elapsed": 300, "msg": "the PD port 2379 is not down"}
#错误#错误#错误#错误#错误#错误#错误#错误#错误#错误#错误#错误

NO MORE HOSTS LEFT ************************************************************************
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/excessive_rolling_update.retry

PLAY RECAP ********************************************************************************
172.18.5.9             : ok=22   changed=2    unreachable=0    failed=1   ##错误#错误#错误#错误#错误
172.18.5.10             : ok=3    changed=0    unreachable=0    failed=0   
172.18.5.11             : ok=3    changed=0    unreachable=0    failed=0   
172.18.5.12             : ok=3    changed=0    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

#错误#错误#错误#错误#错误#错误
### ERROR MESSAGE SUMMARY *********************************************************************
[172.18.5.9]: Ansible FAILED! => playbook: excessive_rolling_update.yml; TASK: wait until the PD port is down; message: {"changed": false, "elapsed": 300, "msg": "the PD port 2379 is not down"}

Ask for help:
Contact us: support@pingcap.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the tidb-ansible/inventory.ini and tidb-ansible/log/ansible.log files and the error message, or new issue on https://github.com/pingcap/tidb-ansible/issues. We'll try our best to help you deploy a TiDB cluster. Thanks. :-)

**Comment by lonng** [comment]
Related issue: https://github.com/pingcap/tidb/issues/11240
