### ISSUE TITLE
snapshot 

### ISSUE THREAD

**Issue by huang10598** [pingcap/tidb#6883]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I can't use snapshot .

2. What did you expect to see?
Suggest adding a snapshot .
If continuous changing table is wrong (Business data ), I want to go back . so 

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by ciscoxll** [comment]
@huang10598 Thank you for your suggestion.

**Comment by huang10598** [comment]
Now my company is going to use it.  I'm worried .
Is there any other alternative .

**Comment by ciscoxll** [comment]
We will support snapshots in the future. you can use mydumper to solve your problem
Please refer to the [link](https://pingcap.com/docs-cn/op-guide/backup-restore/#%E4%BD%BF%E7%94%A8-mydumper-loader-%E5%85%A8%E9%87%8F%E5%A4%87%E4%BB%BD%E6%81%A2%E5%A4%8D%E6%95%B0%E6%8D%AE).

**Comment by huang10598** [comment]
@ciscoxll  thanks

**Comment by tiancaiamao** [comment]
@huang10598  There is a feature in TiDB:
https://pingcap.com/blog-cn/time-travel/

You can read snapshot data of any MVCC version, as long as it's not been GC.
