### ISSUE TITLE
Timeout when waiting for search string TiDB in

### ISSUE THREAD

**Issue by jiancaiHub** [pingcap/tidb#6889]
deploy:
`## TiDB Cluster Part`
`[tidb_servers]`
`172.20.94.37`
`
`[tikv_servers]`
`172.20.94.36`
`172.20.94.35`
`172.20.94.38`
`
`[pd_servers]`
`172.20.94.36`
`172.20.94.35`
`172.20.94.38`

output:
> [172.20.94.37]: Ansible FAILED! => playbook: start.yml; TASK: wait for TiDB up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string TiDB in 172.20.94.37:10080"}

tidb.log:
> 2018/06/23 17:49:01.893 printer.go:38: [info] Welcome to TiDB.
> 2018/06/23 17:49:01.893 printer.go:39: [info] Release Version: v2.0.4-1-g06a0bf5
> 2018/06/23 17:49:01.893 printer.go:40: [info] Git Commit Hash: 06a0bf594559630a35e7121e7401f24de9903d31
> 2018/06/23 17:49:01.893 printer.go:41: [info] Git Branch: release-2.0
> 2018/06/23 17:49:01.893 printer.go:42: [info] UTC Build Time:  2018-06-19 05:32:47
> 2018/06/23 17:49:01.893 printer.go:43: [info] GoVersion:  go version go1.10.2 linux/amd64
> 2018/06/23 17:49:01.893 printer.go:44: [info] TiKV Min Version: 2.0.0-rc.4.1
> 2018/06/23 17:49:01.893 printer.go:49: [info] Config: {"host":"0.0.0.0","port":4000,"store":"tikv","path":"172.20.94.36:2379,172.20.94.35:2379,172.20.94.38:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/data1/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"172.20.94.34:9091","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"retry-limit":10,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.7},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"plan-cache":{"enabled":false,"capacity":2560,"shards":256},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enbale":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"commit-timeout":"41s"},"binlog":{"binlog-socket":"","write-timeout":"15s","ignore-error":false}}
> 2018/06/23 17:49:01.893 tidb.go:279: [info] new store
> 2018/06/23 17:49:01.894 client.go:114: [info] [pd] create pd client with endpoints [172.20.94.36:2379 172.20.94.35:2379 172.20.94.38:2379]
> 2018/06/23 17:49:01.900 client.go:212: [info] [pd] leader switches to: http://172.20.94.36:2379, previous: 
> 2018/06/23 17:49:01.900 client.go:133: [info] [pd] init cluster id 6570212687796597969
> 2018/06/23 17:49:22.968 backoff.go:218: [warning] backoffer.maxSleep 20000ms is exceeded, errors:
> region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"
> region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"
> region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"
> 2018/06/23 17:49:22.968 session.go:1232: [fatal] check bootstrapped err [tikv:9001]PD server timeout[try again later]

**Comment by tiancaiamao** [comment]
Please verify that the PD server is alive. @jiancaiHub

**Comment by jiancaiHub** [comment]
谢谢回复！问题解决了~
问题：
1. 集群启动失败（卡在TiDB Server启动过程中）。PD Server中会有连接pm失败的log。
2. [找到[修改ulimit -n 1000000](https://github.com/pingcap/docs-cn/issues/182)]，依然没有解决问题。
想到我部署集群的时候换过中控机（从TiDB换到监控的机器上）部署过多次，猜测是否是部署多次产生的数据造成的，分别在两台中控机上进行停止、clean、销毁集群的操作。最后重启。顺利启动~
