### ISSUE TITLE
store: returned error from`loadTime()` when `make dev`

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tidb#6892]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

1. change your timezone to Thailand
2. run `make dev` at root directory of `tidb`. 
2. What did you expect to see?
All tests are passed. 

3. What did you see instead?
```
gc_worker_test.go:88:
    c.Assert(err, IsNil)
... value *errors.Err = &errors.Err{message:"", cause:(*time.ParseError)(0xc429653c20), previous:(*errors.Err)(0xc429653cc0), file:"/Users/zhexuany/repo/go/src/github.com/pingcap/tidb/store/tikv/gcworker/gc_worker.go", line:252} ("parsing time \"20180624-11:39:48 +0700 +07\" as \"20060102-15:04:05 -0700 MST\": cannot parse \"+07\" as \"MST\"")
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: None
Git Commit Hash: None
Git Branch: None
UTC Build Time: None
GoVersion: None
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-2f291dc12b0e05d71eb8873881c3ed11d343d6e6

```

**Comment by zhexuany** [comment]
already created a ticket on `go`'s repo. It seems like its the problem of `go`'s `time` package.

**Comment by zhexuany** [comment]
https://github.com/golang/go/issues/26029

**Comment by zhexuany** [comment]
Per the discussion with engineer from `go` team, `time.Parse`'s behavior will be changed after `go 1.11`. So leave this open and monitor when such version will be released.

**Comment by MyonKeminta** [comment]
This seems to be fixed by https://github.com/pingcap/tidb/pull/8745 . How about closing it?

**Comment by nullnotnil** [comment]
Sounds good. Thanks!
