### ISSUE TITLE
can we record more information about slow_sql log 

### ISSUE THREAD

**Issue by kitdine** [pingcap/tidb#6898]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Now, in the slow_sql log file we just can see happening time, type,succ,connectionId,costTime,database,sql

2. What did you expect to see?
can we record the execute user and request ip address

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version:  v2.0.3-1-g98c480c
Git Commit Hash:  98c480c7795110ce90bc4e87f86a06626f0d6e50
Git Commit Branch:  release-2.0
UTC Build Time:  2018-06-03 03:09:10
GoVersion:  go version go1.10.2 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1

**Comment by liuqian1990** [comment]
appname能记录吗

**Comment by tiancaiamao** [comment]
No. `appname` belongs to the application's logic, not database's @liuqian1990

**Comment by lysu** [comment]
@kitdine user and ip is address in #6673 and #6748

**Comment by lysu** [comment]
@kitdine In pratice, you can add appName or appId or traceid in sql as a sql comment, e.g.

```
/*appid:121, traceid:2134*/ select name from user where id = 1;
```
and you can union encapsulate this attach action in your data access layer or framework then you can see it in db log.

**Comment by kitdine** [comment]
@lysu so which tidb version has this feature，I do not find it on the 2.0.3 version

**Comment by lysu** [comment]
@kitdine Sorry, let me see... it's in master and doesn't pick to 2.0.x now..

**Comment by kitdine** [comment]
@lysu ok so when can we have a version that  include this feature?

**Comment by lysu** [comment]
for current, you can use master code for test, and we will port this feature to 2.0.x in next release.
