### ISSUE TITLE
inner join is slow

### ISSUE THREAD

**Issue by alexv1** [pingcap/tidb#6900]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I have three big table. Here, we just name these A(2000w), B(12000w), C(15000w). A is many-to-many with C，B is Middle table，unique_key(primary_key1, primary_key2).
 We need to join these three tables, query like this:
`SELECT * from A inner join B on A.primary_key = B.primary_key1 inner join C on B.primary_key2 = C.primary_key where A.name='xxxx' and C.name='xxxxxxx';`
Final result is one only，but query use over 6 minutes！
name column of two tables was added index too.
explain is blow, 

id | parents | children | task | operator info | count
-- | -- | -- | -- | -- | --
IndexScan_90 |   |   | cop | table:t1, index:name, sourceflag, range:[xxx,xxx], keep order:false | 26947.77
IndexReader_91 | IndexJoin_65 |   | root | index:IndexScan_90 | 26947.77
IndexScan_62 |   |   | cop | table:t2, index:staff_id, range:[<nil>,+inf], keep order:false | 119196011
TableScan_63 |   |   | cop | table:B, keep order:false | 119196011
IndexLookUp_64 | IndexJoin_65 |   | root | index:IndexScan_62, table:TableScan_63 | 119196011
IndexJoin_65 | IndexJoin_13 | IndexReader_91,IndexLookUp_64 | root | outer:IndexReader_91, inner join, outer key:t1.id, inner key:t2.staff_id | 33684.71
TableScan_10 | Selection_11 |   | cop | table:t3, range:[0,+inf], keep order:false | 151364456
Selection_11 |   | TableScan_10 | cop | eq(t3.name, 有限公司) | 151364456
TableReader_12 | IndexJoin_13 |   | root | data:Selection_11 | 151364456
IndexJoin_13 | Projection_8 | IndexJoin_65,TableReader_12 | root | outer:IndexJoin_65, inner join, outer key:t2.company_id, inner key:t3.id | 42105.89
Projection_8 |   | IndexJoin_13 | root | t1.id, t1.name, t2.company_id, t2.staff_type_name, t3.name, t3.base, t3.estiblish_time, t3.reg_capital, t3.reg_status | 42105.89

It seems use hash join
So any improvement here and any suggestion for use?
Thanks.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version:  v2.0.2
Git Commit Hash:  78b49e80fdc1f5eba8e01bdb6053803d395d1401
Git Commit Branch:  release-2.0
UTC Build Time:  2018-05-21 09:31:50
GoVersion:  go version go1.10.2 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1
cluster is one tidb node + 3 tikv node

**Comment by winoros** [comment]
@alexv1 Thanks for your reporting. What if you use the hint `/*+ TIDB_HJ(A, B, C) */`? You can refer to [中文版本](https://github.com/pingcap/docs-cn/blob/master/sql/tidb-specific.md#optimizer-hint) or [English version](https://github.com/pingcap/docs/blob/master/sql/tidb-specific.md#optimizer-hint)

**Comment by alexv1** [comment]
最新情况，查询性能突然变好了，新的查询计划如下。问题关闭吧，还是很困扰......
"id"	"parents"	"children"	"task"	"operator info"	"count"
"IndexScan_94"	""	""	"cop"	"table:t1, index:name, sourceflag, range:[xxx,xxx], keep order:false"	"26983.34"
"IndexReader_95"	"IndexJoin_69"	""	"root"	"index:IndexScan_94"	"26983.34"
"IndexScan_66"	""	""	"cop"	"table:t2, index:staff_id, range:[<nil>,+inf], keep order:false"	"120412608.00"
"TableScan_67"	""	""	"cop"	"table:company_staff, keep order:false"	"120412608.00"
"IndexLookUp_68"	"IndexJoin_69"	""	"root"	"index:IndexScan_66, table:TableScan_67"	"120412608.00"
"IndexJoin_69"	"HashLeftJoin_14"	"IndexReader_95,IndexLookUp_68"	"root"	"outer:IndexReader_95, inner join, outer key:t1.id, inner key:t2.staff_id"	"33729.18"
"IndexScan_103"	""	""	"cop"	"table:t3, index:name, source_flag, range:[有限公司,有限公司], keep order:false"	"1.01"
"TableScan_104"	""	""	"cop"	"table:company, keep order:false"	"1.01"
"IndexLookUp_105"	"HashLeftJoin_14"	""	"root"	"index:IndexScan_103, table:TableScan_104"	"1.01"
"HashLeftJoin_14"	"Projection_8"	"IndexJoin_69,IndexLookUp_105"	"root"	"inner join, inner:IndexLookUp_105, equal:[eq(t2.company_id, t3.id)]"	"1.01"
"Projection_8"	""	"HashLeftJoin_14"	"root"	"t1.id, t1.name, t2.company_id, t2.staff_type_name, t3.name, t3.base, t3.estiblish_time, t3.reg_capital, t3.reg_status"	"1.01"

**Comment by winoros** [comment]
@alexv1 The plan is changed. It was used to index join, but now hash join.

**Comment by shenli** [comment]
@alexv1 Have you upgraded your TiDB cluster？

**Comment by kolbe** [comment]
There hasn't been any reply on this issue in almost a year, so I'm going to close it now. @alexv1 if you are still seeing this issue, please re-open.
