### ISSUE TITLE
 local.ERROR: PDOException: SQLSTATE[HY000]: General error: 1105 line 87 column 38 near " rollup^M

### ISSUE THREAD

**Issue by 007mawenbin** [pingcap/tidb#6906]
pingcap各位大牛早上好，问下为什么我这边跑sql总是有1105报错呢，我是用docker封装的php程序去跑sql脚本的。
#52 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#53 /var/www/html/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#54 {main}
[2018-06-25 16:27:50] local.ERROR: PDOException: SQLSTATE[HY000]: General error: 1105 line 87 column 38 near " rollup^M
" (total length 41523) in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:319
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(319): PDO->prepare('\r\n    select\r\n ...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('\r\n    select\r\n ...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(607): Illuminate\Database\Connection->runQueryCallback('\r\n    select\r\n ...', Array, Object(Closure))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(326): Illuminate\Database\Connection->run('\r\n    select\r\n ...', Array, Object(Closure))

**Comment by tiancaiamao** [comment]
From the log of the application, it seems the SQL statement is wrong.
Please post the error log of TiDB for us to debug. @007mawenbin

**Comment by shenli** [comment]
@007mawenbin Thanks for your feedback.
From the error message, I can see there is a MySQL syntax don't support by TiDB. You can get it from tidb-server's log. Use `grep` to search `rollup` in the log file.

**Comment by zz-jason** [comment]
Thanks for your feedback, the root cause is that TiDB has not supported the group by modifier currently

**Comment by zz-jason** [comment]
duplicated with this issue: https://github.com/pingcap/tidb/issues/4250
