### ISSUE TITLE
PD is closed

### ISSUE THREAD

**Issue by huang10598** [pingcap/tidb#6907]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
PD often closes itself

2. What did you expect to see?
Solve this problem。

3. What did you see instead?
2018/06/25 18:41:54.420 log.go:84: [info] compactor: [Starting auto-compaction at revision 5086 (retention: 1h0m0s)]
2018/06/25 18:41:54.421 log.go:86: [info] mvcc: [store.index: compact 5086]
2018/06/25 18:41:54.421 log.go:84: [info] compactor: [Finished auto-compaction at revision 5086]
2018/06/25 18:41:54.426 log.go:86: [info] mvcc: [finished scheduled compaction at 5086 (took 4.654913ms)]
2018/06/25 19:41:54.423 log.go:84: [info] compactor: [Starting auto-compaction at revision 6171 (retention: 1h0m0s)]
2018/06/25 19:41:54.424 log.go:86: [info] mvcc: [store.index: compact 6171]
2018/06/25 19:41:54.424 log.go:84: [info] compactor: [Finished auto-compaction at revision 6171]
2018/06/25 19:41:54.426 log.go:86: [info] mvcc: [finished scheduled compaction at 6171 (took 1.413062ms)]
2018/06/25 20:17:54.894 main.go:104: [info] Got signal [1] to exit.
2018/06/25 20:17:54.894 server.go:239: [info] ### closing server
2018/06/25 20:17:54.894 leader.go:277: [info] keep alive channel is closed
2018/06/25 20:17:54.894 coordinator.go:435: [info] label-scheduler stopped: context canceled
2018/06/25 20:17:54.894 coordinator.go:435: [info] balance-region-scheduler stopped: context canceled
2018/06/25 20:17:54.894 coordinator.go:435: [info] balance-hot-region-scheduler stopped: context canceled
2018/06/25 20:17:54.894 coordinator.go:435: [info] balance-leader-scheduler stopped: context canceled
2018/06/25 20:17:54.894 leader.go:73: [info] server is closed, return leader loop
2018/06/25 20:17:54.895 log.go:86: [info] etcdserver: [skipped leadership transfer for single member cluster]
2018/06/25 20:17:54.900 server.go:255: [info] ### close server
2018/06/26 09:35:18.507 util.go:54: [info] Welcome to Placement Driver (PD).
2018/06/26 09:35:18.508 util.go:55: [info] Release Version: v2.1.0-alpha-41-g94d19ae
2018/06/26 09:35:18.508 util.go:56: [info] Git Commit Hash: 94d19ae3b5c9e6c348f6cb05ff7464e4022c9492
2018/06/26 09:35:18.508 util.go:57: [info] Git Branch: master
2018/06/26 09:35:18.508 util.go:58: [info] UTC Build Time:  2018-06-22 03:46:29
2018/06/26 09:35:18.508 metricutil.go:79: [info] disable Prometheus push client

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz

**Comment by disksing** [comment]
Hi @huang10598 ,
Thanks for the feedback. From the log `2018/06/25 20:17:54.894 main.go:104: [info] Got signal [1] to exit.` we can see pd-server quits due to receiving SIGHUP. You may want to use [nohup](https://en.wikipedia.org/wiki/Nohup) to start pd-server. You may also consider using our deploy tool [tidb-ansible](https://github.com/pingcap/tidb-ansible) to setup your cluster.

**Comment by huang10598** [comment]
But there was no operation at that point. @disksing

**Comment by disksing** [comment]
The signal is sent when the session ends. Its time may relate to your ssh timeout config. Here is a good article about how to keep your process running: https://www.tecmint.com/keep-remote-ssh-sessions-running-after-disconnection/

**Comment by disksing** [comment]
Closing the issue now. If there are further questions feel free to leave a message.
