### ISSUE TITLE
Could I separately restart a certain TiDB server?

### ISSUE THREAD

**Issue by 007mawenbin** [pingcap/tidb#6916]
In the scenario of server migration, could I separately restart a certain TiDB server? For example, only restart the TiDB server with the IP "192.168.1.10".

**Comment by lilin90** [comment]
**Original Title in Chinese:** 可以单独重启某个tidb服务器吗？

**Original Description in Chinese:** 你好，如有遇到有服务器迁移的情况，可以只重启某个服务器吗？比如只重启tidb服务器，ip为：192.168.1.10

**Comment by july2993** [comment]
ansible-playbook -h
you can see this option
```
-l SUBSET, --limit=SUBSET
                        further limit selected hosts to an additional pattern
```
you can use like
ansible-playbook start.yml -l 192.168.1.10

**Comment by jackysp** [comment]
Solved.
