### ISSUE TITLE
Running ansible-playbook start.yml meets some errors

### ISSUE THREAD

**Issue by mawenbin666** [pingcap/tidb#6917]
PLAY RECAP ******************************************************************************************************************
172.16.168.62              : ok=12   changed=0    unreachable=0    failed=1   
172.16.168.63              : ok=19   changed=0    unreachable=0    failed=0   
172.16.168.64              : ok=16   changed=0    unreachable=0    failed=0   
172.16.168.65              : ok=18   changed=0    unreachable=0    failed=0   
172.16.168.66              : ok=18   changed=0    unreachable=0    failed=0   
172.16.168.67              : ok=18   changed=0    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ERROR MESSAGE SUMMARY *******************************************************************************************************
[172.16.168.62]: Ansible FAILED! => playbook: start.yml; TASK: wait for node_exporter up; message: {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for search string 200 OK in 172.16.168.62:9100"}

Ask for help:
Contact us: support@pingcap.com

**Comment by shenli** [comment]
@007mawenbin Thanks for your feedback! Could you make the issue title more readable?

**Comment by 007mawenbin** [comment]
运行 ansible-playbook start.yml ，然后报如上错误。

**Comment by Mingdr** [comment]
The same problem,my solution is reinstallation.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open it if you are continuing to experience problems. Thanks!
