### ISSUE TITLE
https://github.com/pingcap/tidb.wiki.git

### ISSUE THREAD

**Issue by chenchengpeng** [pingcap/tidb#6938]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by XuHuaiyu** [comment]
hi, @chenchengpeng 
Thank you for your attention.
What's your question here?
Doc of TiDB can be found [here](https://pingcap.github.io/docs/) (or [这里](https://pingcap.github.io/docs-cn/))

**Comment by jackysp** [comment]
Meanless issue title and empty issue description. Closed.
