### ISSUE TITLE
Get DDL owner information form PD by TiDB-API

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#6961]
We want to know easily which TiDB is the DDL owner. Now we can get it from executing SQL. But we only know if the current TiDB is the DDL owner.
So we need to get it from PD. And before that, we need to establish a mapping relationship between the DDL ID and TiDB.

**Comment by shenli** [comment]
We could put more information about TiDB in Etcd. Such as ip/name/isOwner/lease/status_port.

**Comment by shenli** [comment]
@iamxy PTAL

**Comment by zimulala** [comment]
I think we needn't the information about "isOwner", we can get it from PD directly after we support the mapping relationship between the DDL ID and TiDB. And if we need "isOwner", we should update it.

**Comment by iamxy** [comment]
At the beginning, this information is enough:
- listening IP/Port
- instance's name
- isOwner
- some basic configuration such as lease
- status_port
- version
- is binlog opened
