### ISSUE TITLE
Cannot have more than one value for the type of RANGE partitioning

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#6974]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
CREATE TABLE t (
    id INT NOT NULL,
    store_id INT NOT NULL
)
PARTITION BY RANGE (store_id) (
    PARTITION p0 VALUES LESS THAN (6 , 10)
);
```

2. What did you expect to see?
```
ERROR 1657 (HY000): Cannot have more than one value for this type of RANGE partitioning
```

3. What did you see instead?
```
Query OK, 0 rows affected (0.01 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2018/07/03 20:31:24.910 printer.go:39: [info] Welcome to TiDB.
2018/07/03 20:31:24.910 printer.go:40: [info] Release Version: v2.1.0-beta-11-g1f6e12cc5
2018/07/03 20:31:24.910 printer.go:41: [info] Git Commit Hash: 1f6e12cc55e534bf514eef212f1091a91b8592c9
2018/07/03 20:31:24.910 printer.go:42: [info] Git Branch: master
2018/07/03 20:31:24.910 printer.go:43: [info] UTC Build Time:  2018-07-03 12:28:37
2018/07/03 20:31:24.910 printer.go:44: [info] GoVersion:  go version go1.10 darwin/amd64
2018/07/03 20:31:24.910 printer.go:45: [info] Race Enabled: false

**Comment by tiancaiamao** [comment]
This is not accurate, it should be "Cannot have more than one value for the type of RANGE columns partition".
