### ISSUE TITLE
unsupport single '@' syntax in select statement

### ISSUE THREAD

**Issue by qazbnm456** [pingcap/tidb#6990]
1. What did you do?
Execute following statements:
```sql
SELECT 1<@;
SELECT * FROM t WHERE 1<@;
SELECT @;
```

2. What did you expect to see?
http://sqlfiddle.com/#!9/b0b15d/1307

3. What did you see instead?
For the first statement:
`WARN[0000] [con:1] parse error: line 1 column 10 near "" (total length 10)`
For the second statement:
`WARN[0000] [con:1] parse error: line 1 column 25 near "" (total length 25)`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb@[1f6e12c](https://github.com/pingcap/tidb/commit/1f6e12cc55e534bf514eef212f1091a91b8592c9)

**Comment by lysu** [comment]
Thank you for your report! @qazbnm456 and we will tackle this problem later~
and welcome to contribute too~
