### ISSUE TITLE
rolling_update_monitor error

### ISSUE THREAD

**Issue by sdoheji1234** [pingcap/tidb#6998]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
playbook: rolling_update_monitor.yml; TASK: set_fact; message: {"msg": "The conditional check '((existing_api_keys['json'] | selectattr(\"name\", \"equalto\", \"grafana_apikey\")) | list) | length == 1' failed. The error was: no test named 'equalto'\n\nThe error appears to have been in '/home/tidb/tidb-ansible/create_grafana_api_keys.yml': line 21, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}
```

2. What did you expect to see?

Update succeed

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by lysu** [comment]
@sdoheji1234 Thank you for your report. and what's your TiDB-Ansible's git hash?(`git log` and first line)

@LinuxGit PTAL thx

**Comment by LinuxGit** [comment]
It is required to use pip to install Ansible and its dependencies. Your jinja2 version is low.
See https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#step-4-install-ansible-and-its-dependencies-on-the-control-machine.
