### ISSUE TITLE
set tidb_disable_txn_auto_retry error

### ISSUE THREAD

**Issue by 276875692** [pingcap/tidb#7000]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
accout:root
execute :
set @@global.tidb_disable_txn_auto_retry = 1;

2. What did you expect to see?
set @@global.tidb_disable_txn_auto_retry = 1;

3. What did you see instead?

[SQL] set @@global.tidb_disable_txn_auto_retry = 1;
[Err] 1193 - unknown system variable 'tidb_disable_txn_auto_retry'

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.4-1-g06a0bf5
Git Commit Hash: 06a0bf594559630a35e7121e7401f24de9903d31
Git Branch: release-2.0
UTC Build Time: 2018-06-19 05:32:47
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1

**Comment by jackysp** [comment]
Thank you for your report, @276875692 ! 
PTAL @coocood

**Comment by lysu** [comment]
hi @276875692  this option by bd5bbdb3523c73e7a07b2f550a16b6e4967758cc will be landed in 2.0.5(planed in tomorrow)

today, you can test it in master branch code.
