### ISSUE TITLE
question about quick rollback

### ISSUE THREAD

**Issue by dulumao** [pingcap/tidb#7033]
之前用mysql的时候，做了一个类从服务器的东西,用来逆向做回滚，请问tidb要如何处理，是基于tidb-binlog做二次开发吗，还是有其他方式

**Comment by lamxTyler** [comment]
@dulumao Since TiDB is compatible with MySQL, you can do it almost the same with MySQL.

**Comment by dulumao** [comment]
@lamxTyler Yes, but I am using mysql master-slave implementation, how to do it in tidb?

**Comment by lamxTyler** [comment]
@dulumao You can do it through binlog. You can get more details in https://pingcap.com/docs/tools/tidb-binlog-kafka/

**Comment by lysu** [comment]
what's mean of "逆向做回滚"?

**Comment by dulumao** [comment]
@lysu like this two users

**Comment by jackysp** [comment]
Do you mean this https://en.wikipedia.org/wiki/Point-in-time_recovery ?

**Comment by dulumao** [comment]
@lysu Such as user operations:

User A

update amount = amount + 100 
delete user_wallet where id = user A

My tools will created SQLs like:

update amount = amount - 100
insert user_wallert (100)

**Comment by dulumao** [comment]
@jackysp yeah,it's Point-in-time_recover
