### ISSUE TITLE
When TiDB-Binlog open source?

### ISSUE THREAD

**Issue by dulumao** [pingcap/tidb#7045]

**Comment by GregoryIan** [comment]
There is no plan for open source now.  But TiDB-Binlog supports sending `Binlog` to kafka, the` Binlog` protocol is open source, and we have provided some simple use cases ref 
[slave binlog](https://github.com/pingcap/tidb-tools/tree/master/tidb_binlog)

**Comment by dulumao** [comment]
@GregoryIan OK,thx
