### ISSUE TITLE
Tidb server default character set is latin1

### ISSUE THREAD

**Issue by aylen** [pingcap/tidb#7046]
MySQL [(none)]> show variables like '%char%';
+--------------------------------------+--------------------------------------------------------+
| Variable_name                        | Value                                                  |
+--------------------------------------+--------------------------------------------------------+
| character_set_client                 | utf8                                                   |
| character_set_connection             | utf8                                                   |
| character_set_system                 | utf8                                                   |
| character_set_results                | utf8                                                   |
| character_sets_dir                   | /usr/local/mysql-5.6.25-osx10.8-x86_64/share/charsets/ |
| character_set_filesystem             | binary                                                 |
| character_set_database               | latin1                                                 |
| character_set_server                 | latin1                                                 |
| validate_password_special_char_count | 1                                                      |

character_set_server and character_set_database   are latin1, why not utf8

**Comment by lamxTyler** [comment]
Because the default charset for mysql is latin1. You can refer to https://dev.mysql.com/doc/refman/5.7/en/charset-server.html.

**Comment by aylen** [comment]
@lamxTyler   
If you specify only a character set (for example, latin1) but not a collation, that is the same as saying --character-set-server=latin1 --collation-server=latin1_swedish_ci because latin1_swedish_ci is the default collation for latin1. Therefore, the following three commands all have the same effect:

this is from https://dev.mysql.com/doc/refman/5.7/en/charset-server.html.

**Comment by shenli** [comment]
@aylen Thanks for your feedback!
TiDB treats all strings as utf8mb4. I think we should change the default charset/collation to utf8. We will investigate this issue.
