### ISSUE TITLE
Can TiDB support distributed transaction cross multiple process?

### ISSUE THREAD

**Issue by beanww** [pingcap/tidb#7066]
In microservices scenario,  services in different application servers,  
A service(in server1) invoke B(in server2)..,
Can A/B be in one transaction?

**Comment by kolbe** [comment]
@beanww This limitation is now documented at https://www.pingcap.com/docs/sql/mysql-compatibility/: XA syntax (TiDB uses a two-phase commit internally, but this is not exposed via an SQL interface). I'm going to close issue, but please re-open if you have any related questions.
