### ISSUE TITLE
master build broken

### ISSUE THREAD

**Issue by kylewolfe** [pingcap/tidb#710]
```
$ go get github.com/pingcap/tidb
# github.com/pingcap/tidb/parser
github.com\pingcap\tidb\parser\yy_parser.go:17: undefined: yyLexer
github.com\pingcap\tidb\parser\yy_parser.go:18: undefined: yyParse
# github.com/pingcap/go-themis
github.com\pingcap\go-themis\themis_txn.go:257: multiple-value txn.client.LocateRegion() in single-value context
```

**Comment by ngaut** [comment]
Thanks for your report.

Please follow the quick start instructions:
git clone https://github.com/pingcap/tidb.git $GOPATH/src/github.com/pingcap/tidb
cd $GOPATH/src/github.com/pingcap/tidb
make

**Comment by kylewolfe** [comment]
@ngaut,

This is not ideal for this who want to use tidb in an embedded scenerio. Is it not possible to clean master up to allow it to be go getable?

**Comment by ngaut** [comment]
@kylewolfe You are right. We can make it go getable if we add files that generated by goyacc and golex.
But It do has some downsides if we add those generated files.
It's look ugly  for reviewing when parser.y changed.

We will make it go getable later. 

For now you may still need to do:
make update
make

**Comment by kylewolfe** [comment]
Actually, since this is not buildable without make, you can not use it as an embedded db. All compile errors need to be cleaned up to be used as documented here: https://github.com/pingcap/tidb/blob/master/docs/USAGE.md

**Comment by kylewolfe** [comment]
This doesn't seem to be a make related error:

```
..\go-themis\themis_txn.go:257: multiple-value txn.client.LocateRegion() in single-value context
```

**Comment by ngaut** [comment]
@kylewolfe For now you may still need to run "make update" to update related package, than 
make
