### ISSUE TITLE
Occasionally raise the error 'InternalError: (1105, u'start timestamp fall behind safe point')'

### ISSUE THREAD

**Issue by mail2fish** [pingcap/tidb#7131]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

We have a  tidb cluster in production env. Which  occasionally raise the error 'InternalError: (1105, u'start timestamp fall behind safe point')' when we write or select data. After reconnected the db, the error disappeared.

2. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Server version: 5.7.1-TiDB-v1.0.8-1-gaacba4a MySQL Community Server (Apache License 2.0)

After checked code and found that error was raised by 

func (s *tikvStore) CheckVisibility(startTime uint64) error {

Is there a hint for this problem?

**Comment by coocood** [comment]
@mail2fish 
Please take a look at this 
https://github.com/pingcap/docs/blob/master/FAQ.md#error-9001-hy000-pd-server-timeoutstart-timestamp-may-fall-behind-safepoint

**Comment by mail2fish** [comment]
After checked the tidb master code.  The error  code  has changed since
```
	if startTime < cachedSafePoint {
		return errFallBehind
	}
```

to

```
	if startTime < cachedSafePoint {
		return ErrGCTooEarly
	}
```

Is that mean the error is caused by this?

ERROR 9006 (HY000): GC life time is shorter than transaction duration

The interval of GC Life Time is too short. The data that should have been read by long transactions might be deleted. You can add GC Life Time using the following command:

update mysql.tidb set variable_value='30m' where variable_name='tikv_gc_life_time';

    Note: "30m" means only cleaning up the data generated 30 minutes ago, which might consume some extra storage space.

**Comment by mail2fish** [comment]
@coocood  Do you know what is the exactly problem for the above error?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
