### ISSUE TITLE
pd server timeout?

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#7140]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?
sys-log = false.
pd server timeout.
insert and update can trigger it once in a while.
![error](https://user-images.githubusercontent.com/9397764/43127911-3cd16ff0-8f63-11e8-817a-5db431b6e253.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.0.5

**Comment by disksing** [comment]
Hi @474420502 , could you also check the error log of tidb-server? BTW, if you have installed prometheus and grafana, please check `TiDB - PD Client - PD Client CMD Fail OPS` to determine the specific error type.

**Comment by 474420502** [comment]
@disksing i set sys-log = true; and all ok !
but i can't  try it again, it is Production Environment;

**Comment by 474420502** [comment]
@disksing 
raftstore:
  # true (default value) for high reliability, this can prevent data loss when power failure.
  sync-log: true

**Comment by 474420502** [comment]
sorry !  sync-log is right.

**Comment by 474420502** [comment]
![1](https://user-images.githubusercontent.com/9397764/43186945-cfad1562-9022-11e8-81b2-753c5fdef11e.png)
@disksing

**Comment by disksing** [comment]
Hi @474420502 , during the time when error occurs, is the load of pd or tidb too high? Can you discover anything abnormal in log files of tidb and PD? In addition, is pd deployed on the same host as tikv, causing disk i/o contention?

**Comment by 474420502** [comment]
insert 70 per seconds and update 70 per seconds . io very low; when i setting sync-log = true, that is all running well. i want not to see the log. i must solve this problem in a time.
@disksing

**Comment by victorggsimida** [comment]
@disksing  hi i meet the same question.

and  in grafana pannel.  pd client fail: i  see tso error only.
how to solve?

**Comment by disksing** [comment]
hi @victorggsimida , I think it is not the same issue. Please fire an issue to https://github.com/pingcap/pd
