### ISSUE TITLE
Create function is error?

### ISSUE THREAD

**Issue by yowner** [pingcap/tidb#7187]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

CREATE FUNCTION `FN_UP_TRADEDAY`(
  endDay int(11),   
  upDays int(11), 
  marketx varchar(20) 
) RETURNS int(11)
    READS SQL DATA
BEGIN
  
  declare beginDay int(11);
  declare days int(11) default upDays-1;
     
  select
    day into beginDay
  from t_tradeday 
  where market = marketx and day <= endDay
  order by day desc limit days, 1;  
  
  RETURN beginDay;
END;

2. What did you expect to see?
    Create success.

3. What did you see instead?
   [Err] 1105 - line 1 column 15 near " `FN_UP_TRADEDAY`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.5
Git Commit Hash: 43ab80012ae6a154e221e124a2ad3a396f0de822
Git Branch: release-2.0
UTC Build Time: 2018-07-06 08:52:37
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1

**Comment by yowner** [comment]
Oh, When will it be supported?

**Comment by zimulala** [comment]
@yowner 
We don't support it, and it isn't on our roadmap now.

**Comment by zz-jason** [comment]
@yowner thanks for your feedback, TiDB does not support UDF/UDAF/UDTF currently, maybe you can try TiSpark on these OLAP features as a workaround.
