### ISSUE TITLE
Resource isolation in TiDB

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#7189]
HI：
   pingcap 团队。
想通过将多个垂直的数据库，合并到一个TIDB集群中。想实现资源的隔离，A团队的表的物理资源，不能影响到B团队表的物理资源。

**Comment by tiancaiamao** [comment]
One TiDB cluster can't achieve that goal, team A and team B will share the resources.
If you want those databases or tables to be strictly isolated, deploy them in different clusters.
@shenlijungg

**Comment by shenlijungg** [comment]
namespace 不行吗

**Comment by shenli** [comment]
`namespace` is deprecated.

**Comment by Darren** [comment]
@tiancaiamao 
when you say different clusters. do you mean cluster with whole set of tidb/tikv/pd, or just tidb-server or just tidb-server instance?

**Comment by shenlijungg** [comment]
就一个tidb 集群，能否实现2个库互相不影响呢
