### ISSUE TITLE
transform semi join to inner join

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#7205]
Take this query as an example:
```sql
select * from t1 where t1.a in (select a from t2);
```

The plan for this query can be:
<img width="392" alt="2018-07-31 16 36 18" src="https://user-images.githubusercontent.com/5268763/43448284-20488936-94e0-11e8-892b-e0b1edaa7d53.png">

Here the above "semi join" can be transformed to an "inner join":
<img width="411" alt="2018-07-31 16 42 43" src="https://user-images.githubusercontent.com/5268763/43448547-d4012852-94e0-11e8-9a93-46d817a5be7c.png">

This transform is logically equivalent, they can result different physical plans.

In some scenarios, table **"t1"** has an index on column **"t1.a"**, the transformed **"InnerJoin"** can be implemented by a **"IndexJoin"**, which uses the result of the **"Aggregate"** as the outer rows to build the index ranges on **"t1.a"**, directly extract the matched rows on table **"t1"**. That is to say: the physical plan of the later one can be more efficient than the former one.

**Comment by winoros** [comment]
It depends on stats so i think we'd better not add it in the current optimizer.

**Comment by zz-jason** [comment]
@winoros Yes, it's better after we have supported the volcano or cascades planner model.

**Comment by winoros** [comment]
Done by #7531.
It will be controlled by cost in the cascades-like planner.
