### ISSUE TITLE
How to run GRANT ALL PRIVILEGES ON *.* to root@"%" identified by "password"; 

### ISSUE THREAD

**Issue by keithyau** [pingcap/tidb#721]
HI there, as title, wondering how to add a user more than 127.0.0.1 ?

**Comment by shenli** [comment]
@keithyau Try this: 
mysql> grant all on *.* to 'root'@'%' identified by '123';

I will add "all privileges" syntax support.

Thanks for your report!

**Comment by keithyau** [comment]
looks like not working


![image](https://cloud.githubusercontent.com/assets/659311/11775627/61b06b82-a27b-11e5-80f2-e6b20c644f47.png)

**Comment by shenli** [comment]
mysql> grant all on *.* to 'root'@'%' identified by 'thomas';
Query OK, 0 rows affected (0.00 sec)

Each of your three statements has a few synatx error.
1. user name should be 'name'@'host' (Do not miss the quote), 
2. and 3. target should be *.*

**Comment by keithyau** [comment]
i just tried copy and paste the command:

![image](https://cloud.githubusercontent.com/assets/659311/11776396/b30d55d4-a281-11e5-93f3-574ee2bb0d93.png)

is that my version is wrong ? I just use the docker in the quick start guide

**Comment by shenli** [comment]
Pleas replace '.' with '*'.'*' or databasename.tablename in your statement.

**Comment by keithyau** [comment]
Got, thanks
