### ISSUE TITLE
Check how MySQL sort privilege cache items exactly

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#7229]
https://github.com/pingcap/tidb/pull/7211 try to sort the user records according to the document https://dev.mysql.com/doc/refman/5.5/en/connection-access.html

The document missing many details, so maybe we should check the MySQL source code to see how to do it.

**Comment by tiancaiamao** [comment]
@XuHuaiyu

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. If there are specific bugs discovered, we can create new issues.
