### ISSUE TITLE
Fix static analysis issues

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#7247]
#7240 is showing many issues in static analysis. After that is merged, run `make check-fail`. The most important to fix is probably `errcheck` and `gosec`.

**Comment by winoros** [comment]
related issue: https://github.com/pingcap/tidb/issues/3120

**Comment by gregwebs** [comment]
A PR was just sent to fix some issues: https://github.com/pingcap/tidb/pull/8101

This site can be used to check progress on some of these: https://goreportcard.com/report/github.com/pingcap/tidb

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if there are additional issues. Thanks!
