### ISSUE TITLE
Support MySQLWorkbench

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#725]
2015/12/14 22:04:49 session.go:395: [error] Syntax error: SELECT name, type FROM mysql.proc WHERE Db='test'
2015/12/14 22:04:49 session.go:396: [error] Error occurs at [schema:2]table mysql.proc does not exist.
2015/12/14 22:04:49 conn.go:240: [error] dispatch error /Users/shenli/workspace/go/src/github.com/pingcap/tidb/infoschema/infoschema.go:109: [schema:2]table mysql.proc does not exist
2015/12/14 22:04:49 conn.go:241: [error] cmd: SELECT name, type FROM mysql.proc WHERE Db='test'
2015/12/14 22:04:49 tidb.go:136: [warning] compiling SHOW PROCEDURE STATUS WHERE Db='test', error: line 1 column 6 near "PROCEDURE"
2015/12/14 22:04:49 session.go:395: [error] Syntax error: SHOW PROCEDURE STATUS WHERE Db='test'
2015/12/14 22:04:49 session.go:396: [error] Error occurs at line 1 column 6 near "PROCEDURE".
2015/12/14 22:04:49 conn.go:240: [error] dispatch error line 1 column 6 near "PROCEDURE"
2015/12/14 22:04:49 conn.go:241: [error] cmd: SHOW PROCEDURE STATUS WHERE Db='test'
2015/12/14 22:04:49 tidb.go:136: [warning] compiling SHOW PROCEDURE STATUS WHERE Db='test', error: line 1 column 6 near "PROCEDURE"
2015/12/14 22:04:49 session.go:395: [error] Syntax error: SHOW PROCEDURE STATUS WHERE Db='test'
2015/12/14 22:04:49 session.go:396: [error] Error occurs at line 1 column 6 near "PROCEDURE".
2015/12/14 22:04:49 conn.go:240: [error] dispatch error line 1 column 6 near "PROCEDURE"
2015/12/14 22:04:49 conn.go:241: [error] cmd: SHOW PROCEDURE STATUS WHERE Db='test'
2015/12/14 22:05:22 tidb.go:136: [warning] compiling SHOW PROCEDURE STATUS WHERE Db='test1', error: line 1 column 6 near "PROCEDURE"
2015/12/14 22:05:22 session.go:395: [error] Syntax error: SHOW PROCEDURE STATUS WHERE Db='test1'
2015/12/14 22:05:22 session.go:396: [error] Error occurs at line 1 column 6 near "PROCEDURE".
2015/12/14 22:05:22 conn.go:240: [error] dispatch error line 1 column 6 near "PROCEDURE"
2015/12/14 22:05:22 conn.go:241: [error] cmd: SHOW PROCEDURE STATUS WHERE Db='test1'

**Comment by shenli** [comment]
2015/12/14 22:12:36 conn.go:240: [error] dispatch error /Users/shenli/workspace/go/src/github.com/pingcap/tidb/expression/binop.go:124: eval Tables_in_test = "t1" && Table_type != "VIEW" err: eval Tables_in_test = "t1" err: unknown field tables_in_test
2015/12/14 22:12:36 conn.go:241: [error] cmd: SHOW FULL TABLES FROM `test` WHERE `Tables_in_test` = 't1' AND Table_type != 'VIEW'

**Comment by ngaut** [comment]
Can we close this issue?

**Comment by AkihiroSuda** [comment]
With #834, I can connect to TiDB from MySQL Workbench 6.3.

However, I'm still hitting the error: `table mysql.proc does not exist.`

So I suggest reopening this issue, and introducing some dummy `mysql.proc` table.

(When I forcibly try to execute some queries, `Error Code: 0 Server sent unknown charsetnr (0) .` is shown on MySQL Workbench console, as I mentioned in #834.)

**Comment by ngaut** [comment]
Reopen the issue, Thanks @AkihiroSuda

**Comment by ngaut** [comment]
@AkihiroSuda Are you working on this issue ?

**Comment by AkihiroSuda** [comment]
@ngaut Yes, but not yet ready for pull request.

**Comment by AkihiroSuda** [comment]
After discussion at https://github.com/AkihiroSuda/tidb/commit/db660fe0b8a51eaf6223647765a353088b786740, @shenli committed #849, and we can execute query in Workbench.

I think this issue is now closable, although some nice Workbench features (e.g., listing up tables in GUI) are not working yet.

**Comment by shenli** [comment]
@AkihiroSuda I am agree with you. We will work on this. 
If you can send us a PR, we will be appreciate.
