### ISSUE TITLE
Optimizer selected nested loop over hash join incorrectly

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7253]
I migrated mysql to tidb and executed the following sql statement. Found that tidb is much slower than mysql

`
select wallet.*,coin.name as coinName,coin.short_name as shortName
    from bae_coin.user_coin_wallet wallet
	LEFT JOIN bae_coin.system_coin_type coin on wallet.coin_id = coin.id
    where uid = 2 and coin.status != 2 order by coin.sort_id
`

mysql: 0.21 sec; 
tidb: 11.21 sec;

table user_coin_wallet has 2840000+ records, table system_coin_type has 34 records

Is it because I used LEFT JOIN?

**Comment by winoros** [comment]
@gutongjiang Thanks for your reporting!
Could you show me the explain result of this sql?

**Comment by jackysp** [comment]
Hi @gutongjiang , thanks for your report! Please show your `explain` results.

**Comment by winoros** [comment]
@gutongjiang No, TiDB can transform the outer join to inner join automatically.
The plan seems correct.
I need more information to figure out why it's so slow.
1. What's the row count after join.
2. Will condition `uid = 2` filter out too many row?
3. If `2.` is true, is there a index whose prefix is (uid, coin_id) or (coin_id, uid)

**Comment by gutongjiang** [comment]
@winoros 
1. 26 
2. yes
3. yes

**Comment by winoros** [comment]
@gutongjiang What if you use index to force choose that index?
And you can use `select tidb_version()` to get the tidb information and paster it here.

**Comment by gutongjiang** [comment]
| tidb_version()                                                                                                                                                                                                          
Release Version: v2.0.5
Git Commit Hash: 43ab80012ae6a154e221e124a2ad3a396f0de822
Git Branch: release-2.0
UTC Build Time: 2018-07-06 08:52:37
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

**Comment by gutongjiang** [comment]
>> "What if you use index to force choose that index?"

i dont understand your mean.

**Comment by winoros** [comment]
@gutongjiang If the name the index whose prefix is (uid, coin_id) or (coin_id, uid)is `idx_name`. `use index (idx_name)` to force to choose that index.

**Comment by winoros** [comment]
@gutongjiang What's the explain result when there isn't `coin.status!=2`?

**Comment by gutongjiang** [comment]
![_20180802191253](https://user-images.githubusercontent.com/13601367/43580503-4b25a7c0-9688-11e8-8373-b4f496167acc.png)

**Comment by gutongjiang** [comment]
@winoros Thanks, It's works well, mail has been sent

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
