### ISSUE TITLE
Support utf8mb4 as alias for utf8

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#7267]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I tried to install wordpress using default options.  Because TiDB identifies itself as MySQL 5.7, wordpress defaults to using utf8mb4 as the character set.  The only customization I made was to enable debugging (which logs errors; I wanted to see if it complained about TiDB).

2. What did you expect to see?

I think it's safe for TiDB to treat utf8mb4/utf8 equally.  It seems common for frameworks to explicitly select `utf8mb4` because MySQL's utf8 is limited.

3. What did you see instead?

There are errors in wordpress' log about an unknown character set.  The query seems to relate to the debugging enabled, so it at least does not break a default install.  Here is the simplified testcase:

```
MySQL [(none)]> SELECT CONVERT( CONVERT( 'xxx' USING ascii ) USING utf8mb4 ) AS xxx;
ERROR 1115 (42000): Unknown character set: 'utf8mb4'
MySQL [(none)]> SELECT CONVERT( CONVERT( 'xxx' USING ascii ) USING utf8 ) AS xxx;
+------+
| xxx  |
+------+
| xxx  |
+------+
1 row in set (0.00 sec)
```
                                                                                                                                                                               
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

MySQL [(none)]> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-beta-156-g5e7aa1d
Git Commit Hash: 5e7aa1d97d6459843949ae3587c9b5ac6661bb37
Git Branch: master
UTC Build Time: 2018-08-01 02:49:37
GoVersion: go version go1.10.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
1 row in set (0.00 sec)

**Comment by shenli** [comment]
@morgo I find that the root cause is that `utf8mb4` is missing in [this table](https://github.com/pingcap/tidb/blob/master/util/charset/encoding_table.go#L38). We should add it there.

**Comment by morgo** [comment]
If that's the case, I would like to attempt a patch :-)

I'm out tomorrow / Monday.  I'll attempt mid next week.
