### ISSUE TITLE
auto-increment primary key setting error, leading to primary key auto-increment problem

### ISSUE THREAD

**Issue by jiancaiHub** [pingcap/tidb#7271]
问题：自增主键自增异常

尝试设置自增步长为1解决问题，问题未能解决；
`SET auto_increment_increment=1;`

尝试删除数据库并重建，问题仍未能解决；

主键：
1
2
3
4
5
6
7
8
9
10
11
12
13
14
30001
30002
30003
30004
30005
30006
30007
30008
30009
30010
30011
30012
30013
30014
30015
30016
30017
30018
30019
30020
30021
30022
30023
30024
30025
30026
30027
30028
30029
30030
30031
60001
60002
60003
60004
60005
60006
60007
60008
60009
60010
60011
60012
60013
60014
60015
60016
60017
60018
60019
60020
60021
60022
60023
60024
60025
60026
60027
60028
60029
60030
60031
60032
60033
60034
60035
60036
60037
60038
60039
60040
60041
60042
60043
60044
60045
60046
60047
60048
60049
60050
60051
60052
60053
60054
60055
60056
60057
60058
60059
60060
60061
60062
60063
60064
60065
60066
60067
60068
60069
60070
60071
60072
60073
60074
60075
60076
60077
60078
60079
60080
60081
60082
60083
60084
60085
60086
60087
60088
60089
60090
60091
60092
60093
60094
60095
60096
60097
60098
60099
60100
60101
60102
60103
60104
60105
60106
60107
60108
60109
60110
60111
60112
60113
60114
60115
60116
60117
60118
60119
60120
60121
60122
60123
60124
60125
60126
60127
60128
60129
60130
60131
60132
60133
60134
60135
60136
60137
60138
90001
90002
90003
90004
90005
90006
90007
90008
90009
90010
90011
90012
90013
90014
90015
90016
90017
90018
90019
90020
90021
90022
90023
90024
90025
90026
90027
90028
90029
90030
90031
90032
90033
90034
120001
120002
120003
120004
120005
120006
120007

**Comment by ciscoxll** [comment]
@jiancaiHub Thanks for your report!

**Comment by ciscoxll** [comment]
You can try ` RebaseAutoID `, you can use `alter tabletableName auto_increment = 1;`.

**Comment by ciscoxll** [comment]
@jiancaiHub Do you have multiple tidb servers?

**Comment by ciscoxll** [comment]
@jiancaiHub The AUTO_INCREMENT ID is only guaranteed to be self-incrementing and unique, and does not guarantee continuous allocation.

**Comment by zimulala** [comment]
@jiancaiHub 
You can refer to the [docs-cn](https://github.com/pingcap/docs-cn/blob/master/sql/mysql-compatibility.md#%E8%87%AA%E5%A2%9E-id).
And the step(5000) is out of date, now it's 30000. We will update this doc.
