### ISSUE TITLE
Tinyint type check error

### ISSUE THREAD

**Issue by jebter** [pingcap/tidb#7272]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

mysql> CREATE TABLE t1(a tinyint);
Query OK, 0 rows affected (0.02 sec)

mysql> INSERT INTO t1 VALUES ('-838:59:59.0000002');
ERROR 1264 (22003): Out of range value for column 'a' at row 1
mysql>

3. What did you see instead?

mysql root@10.146.156.253:test> CREATE TABLE t1(a tinyint);
Query OK, 0 rows affected
Time: 0.968s
mysql root@10.146.156.253:test> INSERT INTO t1 VALUES ('-838:59:59.0000002')
Query OK, 1 row affected
Time: 1.071s
mysql root@10.146.156.253:test> select MIN(a) from t1;
+--------+
| MIN(a) |
+--------+
| -128   |
+--------+
1 row in set
Time: 0.104s

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

+--------------------------------------------------------------------------+
| tidb_version()                                                           |
+--------------------------------------------------------------------------+
| Release Version: v2.1.0-beta-132-g33367fd                                |
| Git Commit Hash: 33367fdd48bf10560a11347ff2d904fbb723b3b9                |
| Git Branch: master                                                       |
| UTC Build Time: 2018-07-30 03:54:53                                      |
| GoVersion: go version go1.10.2 linux/amd64                               |
| Race Enabled: false                                                      |
| TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
+--------------------------------------------------------------------------+

**Comment by ciscoxll** [comment]
@XuHuaiyu Please help to see.

**Comment by morgo** [comment]
I was not able to reproduce this issue.  Can you please paste the output of `show variables like 'sql_mode';`?  Thank you!

```
mysql> CREATE TABLE t1(a tinyint);
Query OK, 0 rows affected (0.09 sec)

mysql> INSERT INTO t1 VALUES ('-838:59:59.0000002');
ERROR 1366 (HY000): Incorrect tinyint value: '-838:59:59.0000002' for column 'a' at row 1
mysql> select MIN(a) from t1;
+--------+
| MIN(a) |
+--------+
|   NULL |
+--------+
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-75-gbe5c56991-dirty
Git Commit Hash: be5c56991537989a55436de480dfb24ac7202bd8
Git Branch: usage-priv
UTC Build Time: 2018-10-18 09:44:16
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by jebter** [comment]
This issue has been fixed in the new version of Tidb, I closed it.
mysql root@192.168.199.170:test> INSERT INTO t1 VALUES ('-838:59:59.0000002');
(1366, u"Incorrect tinyint value: '-838:59:59.0000002' for column 'a' at row 1")
mysql root@192.168.199.170:test> select @@sql_mode
+--------------------------------------------+
| @@sql_mode                                 |
+--------------------------------------------+
| STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION |
+--------------------------------------------+
1 row in set
Time: 0.022s
mysql root@192.168.199.170:test> select tidb_version();
+--------------------------------------------------------------------------+
| tidb_version()                                                           |
+--------------------------------------------------------------------------+
| Release Version: v2.1.0-rc.3-45-g95edaf0                                 |
| Git Commit Hash: 95edaf02e0c0446b14af2847af1300fe4778b11e                |
| Git Branch: master                                                       |
| UTC Build Time: 2018-10-16 08:45:34                                      |
| GoVersion: go version go1.11 linux/amd64                                 |
| Race Enabled: false                                                      |
| TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e |
| Check Table Before Drop: false                                           |
+--------------------------------------------------------------------------+
1 row in set
Time: 0.016s
