### ISSUE TITLE
Grafana cannot be accessed normally

### ISSUE THREAD

**Issue by SchopenhauerZhang** [pingcap/tidb#7275]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
http://172.16.10.3:3000/

2. What did you expect to see?
open it and show the monitor .
打开浏览器，访问以下监控平台：

地址：http://172.16.10.3:3000， 默认帐户和密码为：admin@admin。

3. What did you see instead?

can not open the link "http://172.16.10.3:3000"   and pingcap  can resolve it ？thanks!

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

maybe it is the next hadoop for the "big data ".

**Comment by ciscoxll** [comment]
@SchopenhauerZhang Thanks for your report! How did you deploy it?

**Comment by ciscoxll** [comment]
@SchopenhauerZhang Maybe grafana service did not start successfully, you can refer to the [deployment document.](https://pingcap.com/docs-cn/op-guide/ansible-deployment/)

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
