### ISSUE TITLE
Does tidb support json_contains?

### ISSUE THREAD

**Issue by secmask** [pingcap/tidb#7299]
1. What did you do?

query: select json_contains('[3,4]','4');

2. What did you expect to see?

`|1|`

3. What did you see instead?

FUNCTION json_contains does not exist

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.0.6

we're trying to use TiDB in application, and I know that not all json function is supported, can I know when it/they will be get support?

**Comment by jackysp** [comment]
Thanks for your feedback, @secmask ! TiDB does not support `json_contains` now.

**Comment by secmask** [comment]
@jackysp thanks for quick answer, I have read thought issues and know that it does not support now. but, could you estimate when it will get support? because I need to know should I wait.

**Comment by jackysp** [comment]
PTAL @shenli

**Comment by zz-jason** [comment]
fixed by https://github.com/pingcap/tidb/pull/7443
