### ISSUE TITLE
parser.y: Ambiguous grammar

### ISSUE THREAD

**Issue by cznic** [pingcap/tidb#73]
It seems that [parser.y](https://github.com/pingcap/tidb/blob/8920a55dab883c1ca064b978fe88aea28ef6c29b/parser/parser.y) has several shift/reduce and reduce/reduce conflicts.

S/R conflicts are *sometimes* expected and/or acceptable, but I don't think this applies in this case. R/R conflicts, on the other hand, are almost never okay.

The current state of the grammar with all of the conflicts means that there are valid sentences, part of the intended-to-parse language, which will parse incorrectly or not at all because the grammar is ambiguous and does not reflect the proper language.

I suggest to get rid of *all* conflicts in `parser.y` and, above that, perhaps use the `-cr` goyacc flag to verify reducibility of all grammar productions.

**Comment by qiuyesuifeng** [comment]
@shenli  PTAL. 
Thanks for your suggestion, and thank u for your awesome job again :)

**Comment by coocood** [comment]
resolved by final PR https://github.com/pingcap/tidb/pull/122
