### ISSUE TITLE
connection tidb unstable

### ISSUE THREAD

**Issue by yezhibo** [pingcap/tidb#7310]
我用了4台服务器来部署TiDB, 但是实际测试过程中发现测试结果很不稳定，请问有遇到过类似的问题吗？

**Comment by jackysp** [comment]
Thank you for your feedback, @yezhibo ! Please show more details for your test, e.g.
1. which test case you used?
1. what error you met?

**Comment by yezhibo** [comment]
how to show you my grafana?   by the way can you give me some advice to use the grafana?

**Comment by shenli** [comment]
You can send your grafana ip/username/pwd to `shenli at pingcap.com`. 
[Here](https://github.com/pingcap/docs/blob/master/op-guide/dashboard-overview-info.md) is the related document for the monitor system.
