### ISSUE TITLE
Does TiDB support multi-datasource connection?

### ISSUE THREAD

**Issue by ximengyun** [pingcap/tidb#7313]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by lysu** [comment]
hi @ximengyun, what do you mean about "多数据源连接"?

**Comment by XuHuaiyu** [comment]
@ximengyun https://github.com/pingcap/tidb/issues/6083
Hi, can this issue solve your problem?

**Comment by shenli** [comment]
@ximengyun TiDB only supports one data source. You can't access multiple data sources in a TiDB cluster.

**Comment by kolbe** [comment]
@ximengyun it looks like this question has been answered, so I am going to close it now. If you have any followup, please re-open and provide additional details!
