### ISSUE TITLE
any hello world guide ?

### ISSUE THREAD

**Issue by keithyau** [pingcap/tidb#732]
Wondering if i can debug myself for the support of PHP applications. If any guide/blog post for hello world is appreciated.

**Comment by shenli** [comment]
@keithyau 
There are a few docs in tidb/docs.
https://github.com/pingcap/tidb/blob/master/docs/QUICKSTART.md
https://github.com/pingcap/tidb/blob/master/docs/HBASE_QUICKSTART.md
https://github.com/pingcap/tidb/blob/master/docs/USAGE.md

**Comment by keithyau** [comment]
sorry to be trouble maker.. just ..

![image](https://cloud.githubusercontent.com/assets/659311/11831752/7a9f7fe4-a3ec-11e5-9490-845d6533a333.png)

i tried a go get command success, but make fail

**Comment by shenli** [comment]
@keithyau May I have your golang version? You can get it by "go version".

**Comment by keithyau** [comment]
![image](https://cloud.githubusercontent.com/assets/659311/11831815/1e6335b2-a3ed-11e5-920f-42df323f4c76.png)

**Comment by shenli** [comment]
We need golang version >= 1.5. Please upgrade your golang.
“Go environment. Currently a 64-bit version of go >= 1.5 is required.”

**Comment by keithyau** [comment]
Does it support mac ?

![image](https://cloud.githubusercontent.com/assets/659311/11831942/78869560-a3ee-11e5-96bf-46c1ab89f353.png)

**Comment by qiuyesuifeng** [comment]
@keithyau Thanks for your report.
Yes, tidb can run well on Mac OS.
Could u show some more details? including the lastest commit version and the whole `make` output.
Also u can send an email to cuiqiu@pingcap.com.

**Comment by keithyau** [comment]
i just download it this morning with the quickstart guide, so it probably is latest.

output too long,just capture errors

![image](https://cloud.githubusercontent.com/assets/659311/11832261/900b6500-a3f1-11e5-8e99-b0342be35b44.png)

![image](https://cloud.githubusercontent.com/assets/659311/11832258/8998f23c-a3f1-11e5-8896-29608aeaed7d.png)

![image](https://cloud.githubusercontent.com/assets/659311/11832270/a9345514-a3f1-11e5-8be8-311228867445.png)

**Comment by shenli** [comment]
@keithyau
This error message shows a test case failed. In that test case we init the privilege table for test@'127.0.0.1'/'localhost'/'::1'. But it seems that when the case run on your machine, it use another ip address to connect to the server. So the auth failed.
So it is a bug in test case. I will fix this.

**Comment by shenli** [comment]
@keithyau I just pushed a new branch shenli/fix-server-testcase to fix this. Would you please checkout this branch and check if it is ok?
Thanks!

**Comment by keithyau** [comment]
yes, can compile on Mac now.
