### ISSUE TITLE
the secondary tidb-node doesn't work

### ISSUE THREAD

**Issue by alexv1** [pingcap/tidb#7324]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I add tidb002 to cluster successful, and it show in grafana
but the tidb002 has no connection!
![1](https://user-images.githubusercontent.com/5744909/43839065-c028d10c-9b4f-11e8-87f4-e71e8ab15851.png)
when I run sysbench test, the tidb001 cpu is full, the tidb002 doesn't process any requests!
what's problem?

2. What did you expect to see?
two tidb server can load balance

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb 2.0.2

**Comment by alexv1** [comment]
I find the answer： I need to access tidb002 directly！
I feel confused that, tidb why not provide load-balance component！It makes many problems in production env.

**Comment by lysu** [comment]
Thanks for your feedback, @alexv1 ! there are many comprehensive load-balance solutions(both layer4 or layer7) existed, it's better to use them directly for now.

**Comment by kolbe** [comment]
@alexv1 it looks like this question has been answered, so I am going to close it now. The recommendation is to use an existing load balancer that meets the needs of your environment and application. Each application may have a different need in terms of using a layer4 or layer7 load balancer, and deployment environments may provide their own hardware- or software-based load balancers that could be better than something integrated into the TiDB Platform.

If you have additional questions related to this issue, please re-open it.
