### ISSUE TITLE
Is there any log size limit for TiDB?

### ISSUE THREAD

**Issue by ssnijik** [pingcap/tidb#7344]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
After loading data into TiDB several times, huge amount of errors were written into log file. Every 300M of log file will be written in to a separate file. But all log file will be kept, which may be several hundreds of gigabytes.

2. What did you expect to see?
A configuration option to limit total size of log file

3. What did you see instead?
several hundred gigabytes of log file

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.0
Git Commit Hash: 637e130e6a9ba2e54e158131c0466233db39a60e
Git Branch: release-2.0
UTC Build Time: 2018-04-27 11:43:00
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

**Comment by XuHuaiyu** [comment]
Hi, @ssnijik , thank you for your feedback.
TiDB provides some configuration item to set the limitation of log files.
You can find it [here](https://github.com/pingcap/docs/blob/master/op-guide/tidb-config-file.md#logfile).
