### ISSUE TITLE
Data and loads are not well distributed in my benchmark

### ISSUE THREAD

**Issue by jaltabike** [pingcap/tidb#7349]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

I tried to insert tuples into TiDB by using YCSB (Yahoo! Cloud Serving Benchmark).
My TiDB settings were as follows:
- I used 9 AWS EC2 instances (each instance is i3.2xlarge: 8 vCPUs, 61GiB RAM , 1 x 1900GB nvme disk)
   . node#1~#3: 1 x TiDB & 1 x PD ware deployed on each instance (i.e., total 3 x TiDBs & 3 x PDs)
   . node#4~#9: 1 x TiKV was deployed on each instance (i.e., total 6 x TiKVs)
- tidb_version: v2.0.5
- I used the default TiDB config. Exception is as follows:
   . prepared_plan_cache: enabled: true
- I used the default PD config.
- I used the default TiKV config. Exceptions are as follows:
   . raftstore: sync-log: false
   . rocksdb: bytes-per-sync: "1MB"
   . rocksdb: wal-bytes-per-sync: "512KB"
   . raftdb: bytes-per-sync: "1MB"
   . raftdb: wal-bytes-per-sync: "512KB"
   . storage: scheduler-concurrency: 1024000
   . storage: scheduler-worker-pool-size: 6
   . *: max-write-buffer-number: 10
- I created one table like follows:
CREATE TABLE usertable (
	YCSB_KEY VARCHAR(255) PRIMARY KEY,
	FIELD0 TEXT, FIELD1 TEXT,
	FIELD2 TEXT, FIELD3 TEXT,
	FIELD4 TEXT, FIELD5 TEXT,
	FIELD6 TEXT, FIELD7 TEXT,
	FIELD8 TEXT, FIELD9 TEXT
);

And YCSB settings were as follows:
- I used YCSB "load" command to insert tuples into TiDB
- I used the following config for YCSB "load"
   . maxexecutiontime: 3600 (i.e., insert tuples for 3600 seconds)
   . target: 32000 (i.e., insert tuples at a rate 32000 insertions per sec)
   . threads: 512 (i.e., use 512 client threads to insert tuples)
   . db.batchsize: 100 & jdbc.autocommit: false (i.e., commit every 100 inserts)

2. What did you expect to see?
I expected the data and loads to be well distributed.

3. What did you see instead?
Data and loads were not well distributed. I think the performance (TPS and latency) was limited by this.

Data were not well distributed as follows:
- Sore size => store size of tikv_1 and tikv7 was 3 times larger than that of the others
![image](https://user-images.githubusercontent.com/1661884/43942927-cb69addc-9cb4-11e8-895a-cf4c41099a5d.png)
- Leader and region distribution => It was unbalanced
![image](https://user-images.githubusercontent.com/1661884/43944361-8f94a618-9cb9-11e8-9942-49f1b9d543dc.png)
![image](https://user-images.githubusercontent.com/1661884/43944365-977012fa-9cb9-11e8-8c65-196ccb0798c1.png)

Loads for TiKV were not well distributed as follows:
(In overall, tikv1 seemed to be overloaded.)
- CPU => tikv_1 (also tikv_7) used about 200% (100%) more CPU than other tikvs
![image](https://user-images.githubusercontent.com/1661884/43943753-9c2adde0-9cb7-11e8-8f36-3ce6e7a83f47.png)
- Load => load received by tikv1(=tikv_1) was twice more than that of the others 
![image](https://user-images.githubusercontent.com/1661884/43943865-0fc1bce2-9cb8-11e8-9a19-cc4f61af0f7e.png)
- IO Util => IO util of tikv1(=tikv_1) and tikv5(=tikv_7) was six times (twice for tikv5) more than that of the others
![image](https://user-images.githubusercontent.com/1661884/43944002-7239ce0a-9cb8-11e8-95e0-c5b9811578ef.png)
- Network traffic Inbound => Inbound of tikv1 and tikv5 was twice more than that of the others
![image](https://user-images.githubusercontent.com/1661884/43944199-11a5f6d0-9cb9-11e8-95b7-54c51854051d.png)
- Network traffic Outbound => Outbound of tikv1 was very larger than that of the others
![image](https://user-images.githubusercontent.com/1661884/43944278-5419a700-9cb9-11e8-81df-635ec100ec14.png)
- Region average written keys => most of keys seemd to be written into tikv_1
![image](https://user-images.githubusercontent.com/1661884/43945241-84baf6a4-9cbc-11e8-8188-042f0a660b0c.png)
- Scheduler pending commands => most of scheduler pending commands were issued from tikv_1
![image](https://user-images.githubusercontent.com/1661884/43944749-f0a52eb8-9cba-11e8-829f-a31657726d69.png)

4. Questions
Why were data not well-distributed in my situation?
Why were loads (CPU, IO, Network) not well-distributed in my situation?
What is "scheduler pending commands"? Is it related to unbalanced load or data?
Can the region size exceed region-max-size? Following graph shows average region size was 20.3GiB which is too big! It seems that there was one very large size region. If there was such a region, why did not this large size region split?
![image](https://user-images.githubusercontent.com/1661884/43945161-4c41800e-9cbc-11e8-991f-47bf7d48f4a1.png)

5. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.0.5

**Comment by XuHuaiyu** [comment]
Hi, @jaltabike Thank you for your feedback.
We'll reply to you soon.

**Comment by XuHuaiyu** [comment]
PTAL @liukun4515

**Comment by liukun4515** [comment]
Can you provide more detailed ycsb workload file and load script?
@jaltabike

**Comment by jaltabike** [comment]
@liukun4515 
My YCSB properties(configs) are as follows:
- maxexecutiontime=3600
- recordcount=1000000000
- operationcount=1000000000
- workload=com.yahoo.ycsb.workloads.CoreWorkload
- readallfields=true
- readproportion=0
- updateproportion=0
- scanproportion=0
- insertproportion=1
- requestdistribution=zipfian
- insertstart=0
- fieldcount=10
- fieldlength=100
- reportlatencyforeacherror=true
- db.driver=com.mysql.jdbc.Driver
- db.url=jdbc:mysql://tidb-proxy:4001/ycsb?useSSL=false&useServerPrepStmts=true
- db.user=???
- db.passwd=???
- db.batchsize=100
- jdbc.batchupdateapi=false
- jdbc.autocommit=false

And, my load script is as follows:
ycsb -jvm-args="${JVM_ARGS}" load jdbc -P ${PROPERTY_FILE} -s -target 32000 -threads 512
where
- JVM_ARGS="-Xms8G -Xmx8G -XX:PermSize=512m -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CMSParallelRemarkEnabled -XX:SurvivorRatio=8 -XX:MaxTenuringThreshold=1 -XX:CMSInitiatingOccupancyFraction=75  -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSWaitDuration=10000 -XX:+CMSParallelInitialMarkEnabled -XX:+CMSEdenChunksRecordAlways -XX:+CMSClassUnloadingEnabled"
- PROPERTY_FILE contains properties I listed above.

*** My first comment contained incorrect information, so I've corrected the information: I've changed the "target" value of the YCSB config from 20000 to 32000.

**Comment by liukun4515** [comment]
This situation is caused by hot region.
You can refer to [_tidb_rowid](https://pingcap.com/docs/sql/tidb-specific/#shard-row-id-bits) and [SHARD_ROW_ID_BITS](https://pingcap.com/docs/sql/tidb-specific/#shard-row-id-bits).
@jaltabike

**Comment by jaltabike** [comment]
Thank you, @liukun4515 
I will change the value of SHARD_ROW_ID_BITS and run the ycsb benchmark again.
By the way, can the region size exceed region-max-size?
"approximate region size", the graph I attached above, shows that average region size is 20.3GiB which is far larger than region-max-size (default: 144MB).
Why do not regions whose size is far larger than region-max-size be splitted?

**Comment by liukun4515** [comment]
Any update for your benchmark result?

**Comment by dbjoa** [comment]
@liukun4515 Can TiDB split the region automatically if the user changes SHARD_ROW_ID_BITS via ALTER TABLE?

**Comment by liukun4515** [comment]
The value of SHARD_ROW_ID_BITS doesn't impact the region split. @dbjoa

**Comment by jaltabike** [comment]
Thank you for your answer, @liukun4515 
I currently can not access my workspace until next Tuesday (Aug. 21st).
I will run the benchmark next Wednesday (Aug. 22nd), and I will share the results as soon as possible.

**Comment by jaltabike** [comment]
@liukun4515 @XuHuaiyu
I would like to share my new benchmark results.

I just set the value of SHARD_ROW_ID_BITS to 4,

and performed the same benchmark as the first one mentioned [above](https://github.com/pingcap/tidb/issues/7349#issue-349415040).

As the result, it seemed that data and loads were well-distributed as follows:

- Data were well-distributed:
![image](https://user-images.githubusercontent.com/1661884/44447993-effa6c80-a624-11e8-8e0f-987eee1fc9de.png)
![image](https://user-images.githubusercontent.com/1661884/44448007-f7217a80-a624-11e8-9047-6c1a46a869d8.png)
![image](https://user-images.githubusercontent.com/1661884/44448016-fd175b80-a624-11e8-9c76-87bc694a2ab7.png)

- Loads for TiKV were relatively well-distributed:
![image](https://user-images.githubusercontent.com/1661884/44448153-6303e300-a625-11e8-81f4-eb5fcde5ee98.png)
![image](https://user-images.githubusercontent.com/1661884/44448238-a2caca80-a625-11e8-9655-509b634b77ba.png)
![image](https://user-images.githubusercontent.com/1661884/44448327-e7566600-a625-11e8-95d7-80263e2351e4.png)
![image](https://user-images.githubusercontent.com/1661884/44448364-01904400-a626-11e8-9cf4-67ff4f411b50.png)
![image](https://user-images.githubusercontent.com/1661884/44448453-3dc3a480-a626-11e8-8459-42c03c53c4a8.png)
(*For outbound network traffic, tikv2 was twice as much as the others.)
![image](https://user-images.githubusercontent.com/1661884/44448532-7ebbb900-a626-11e8-9281-89b8b6b47366.png)
(*For "region average written keys", tikv_4(=tikv2) was up to twice as much as the others.)
![image](https://user-images.githubusercontent.com/1661884/44448585-9f840e80-a626-11e8-989a-24f96ea31150.png)


- Region size seemed normal:
![image](https://user-images.githubusercontent.com/1661884/44448640-c2aebe00-a626-11e8-990a-654e81412074.png)

Now, i'm performing the same benchmark as the second one mentioned [above](https://github.com/pingcap/tidb/issues/7349#issuecomment-412473725), which will take about a day.

I'll also share the results as soon as possible.

By the way, why might "setting a large value of SHARD_ROW_ID_BITS" lead to a large number of RPC requests?

And, what does "scheduler pending commands" means?

**Comment by winoros** [comment]
@jaltabike 
When there's no int primary key and you performed a range query on table's primary key and try to get data that not only containing index key but also other columns, TiDB will first scan index and get its corresponding `__tidb_rowid` then use the `__tidb_rowid` to seek the table data. You can explain the sql to see its execution plan. 
`SHARD_ROW_ID_BITS` won't affect the process of scanning index, but will affect the process of scanning table.
Table's data is stored in `__tidb_rowid`'s order. So when there's no `SHARD_ROW_ID_BITS`, the continuous index values' corresponding `__tidb_rowid` is more likely stored in same region. But it will stored in multiple region to avoid hot spot when there's `SHARD_ROW_ID_BITS`.
One RPC task sending to tikv will only contain one region. So the more region one query involved, the more RPC request is sent.

**Comment by breeswish** [comment]
Hi, this is an answer for your previous question:

> What is "scheduler pending commands"? Is it related to unbalanced load or data?

TiKV handles write requests in a component called Scheduler. If there are many scheduler pending commands for one TiKV instance, it usually means that there are too many writes for this TiKV instance. If only one TiKV instance has many pending commands but others do not, it means that the write requests are not balanced to all TiKVs, which usually means that there are hot write regions.

**Comment by jaltabike** [comment]
@winoros @breeswish
Thank you for your answer~!

**Comment by siddontang** [comment]
@jaltabike 

I find that you use zipfian for the request distribution, it will cause hot keys and then cause hot region. Maybe a better way is to use uniform.

**Comment by jaltabike** [comment]
@liukun4515 @XuHuaiyu
I would like to share my new benchmark results.

I just set the value of SHARD_ROW_ID_BITS to 4,

and performed the same benchmark as the second one mentioned [above](https://github.com/pingcap/tidb/issues/7349#issuecomment-412473725).

As the result, it seemed that data and loads were relatively well-distributed as follows:

- Data were relatively well-distributed:
![image](https://user-images.githubusercontent.com/1661884/44497847-7a3ee100-a6b6-11e8-9456-9aa1079b24f9.png)
![image](https://user-images.githubusercontent.com/1661884/44497829-62fff380-a6b6-11e8-952e-5b2492520817.png)
![image](https://user-images.githubusercontent.com/1661884/44497843-7317d300-a6b6-11e8-9df6-72f2ead5896c.png)

- Loads for TiKV were relatively not well-distributed, but there were no major differences or bottleneck nodes:
![image](https://user-images.githubusercontent.com/1661884/44497900-cee25c00-a6b6-11e8-902f-8a219d298f38.png)
(*For "cpu", tikv_4(=tikv2) was about twice higher than tikv_6(=tikv4) over a certain period of time (12:00-16:00).
![image](https://user-images.githubusercontent.com/1661884/44497961-1c5ec900-a6b7-11e8-886f-a31ad0123891.png)
(*For "Load", tikv2 was about 5 times higher than tikv4 over a certain period of time (12:00-16:00).
![image](https://user-images.githubusercontent.com/1661884/44498274-7744f000-a6b8-11e8-9fd0-5cd63e01554f.png)
![image](https://user-images.githubusercontent.com/1661884/44498313-b2472380-a6b8-11e8-9dd8-c868d9c92b31.png)
![image](https://user-images.githubusercontent.com/1661884/44498412-39949700-a6b9-11e8-932a-52c1c7d306ad.png)
("IO Util" and "Network Traffic" were relatively well-distributed.)


- Region size seemed normal:
![image](https://user-images.githubusercontent.com/1661884/44498420-5204b180-a6b9-11e8-87d7-f635adb385ec.png)

- Exception#1
Memory used by tikv_4 (also, tikv_5) dropped abruptly at 16:43 (20:45 for tikv_5).
This causes a sudden temporary performance (TPS) degradation.
At the similar time, "flush messages per server" of tikv_4 (also, tikv_5) increased abruptly.
In addition, until the similar time, "scheduler pending commands" of tikv_4 (also, tikv_5) was quite higher than others.
Could you explain what happened at tikv_4 and tikv_5?
![image](https://user-images.githubusercontent.com/1661884/44497910-d73a9700-a6b6-11e8-83c0-1bc84186db2e.png)
![image](https://user-images.githubusercontent.com/1661884/44500810-664eab80-a6c5-11e8-82b3-2cd4f33a4ae7.png)
![image](https://user-images.githubusercontent.com/1661884/44500586-3bb02300-a6c4-11e8-8c33-9b5da1ac2573.png)

- Exception#2
There were some peaks for "region average written keys" (around at 12:00, 14:00, 20:00-22:00)
"active written leaders" seemed to be related to the symptoms.
Could you explain what happened at those times?
![image](https://user-images.githubusercontent.com/1661884/44498376-12d66080-a6b9-11e8-8d6d-06fbe2f825b1.png)
![image](https://user-images.githubusercontent.com/1661884/44501611-f04c4380-a6c8-11e8-9840-945bf0f6eca9.png)

Except for above two exceptions, everything works well now!
I wrote two questions about these exceptions above.
Could you explain why those things happened?

**Comment by jaltabike** [comment]
@siddontang 
Because there is enough memory available (total memory size: 61GiB, memory used by tikv_4: 15GiB at max), it is unlikely that OOM occurred.
Although I couldn't find any OOM messeage in dmesg (*command I used: dmesg | egrep -i 'killed process'),
tikv.log says that tikv restarted at that time as you expected.
And there is an error that seems to be related to this restart:
`2018/08/22 16:41:24.075 panic_hook.rs:97: [ERROR] thread 'apply worker' panicked 'schedule WriteFinished msg failed, cid=301417729, err:channel is full' at "src/storage/txn/scheduler.rs:305"
stack backtrace:
   0:     0x56532b8eea9e - backtrace::backtrace::libunwind::trace::h79c4af28be231e54
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace::h56424d341baa1bce
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x56532b417937 - tikv::util::panic_hook::set_exit_hook::{{closure}}::h0b6c560535990cc2
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/pingcap/tikv/target/release/build/backtrace-5e253aa535e0fe5b/out/capture.rs:79
   2:     0x56532bac1005 - std::panicking::rust_panic_with_hook::h1be8ff44b2f85fd7
                        at libstd/panicking.rs:403
   3:     0x56532bac0e9d - std::panicking::begin_panic_fmt::h9462a882b9175ee8
                        at libstd/panicking.rs:349
   4:     0x56532b4ae536 - tikv::storage::txn::scheduler::make_engine_cb::{{closure}}::hfe27a1a97e21ecd1
                        at src/storage/txn/scheduler.rs:305
                         - <F as alloc::boxed::FnBox<A>>::call_box::h57ec56596bccc902
                        at /checkout/src/liballoc/boxed.rs:635
   5:     0x56532b210cc1 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h82cf0030dfdbbb3c
                        at /checkout/src/liballoc/boxed.rs:655
                         - <tikv::storage::engine::raftkv::RaftKv<S> as tikv::storage::engine::Engine>::async_write::{{closure}}::ha91f34c2dcbcc53f
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/pingcap/tikv/src/storage/engine/raftkv.rs:351
                         - <F as alloc::boxed::FnBox<A>>::call_box::h1b7136ccb46725a4
                        at /checkout/src/liballoc/boxed.rs:635
   6:     0x56532b2157e6 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h2a1f8642cca6fa56
                        at /checkout/src/liballoc/boxed.rs:655
                         - <tikv::storage::engine::raftkv::RaftKv<S>>::exec_write_requests::{{closure}}::h814c4b4d2178d49f
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/pingcap/tikv/src/storage/engine/raftkv.rs:253
                         - <F as alloc::boxed::FnBox<A>>::call_box::hd11a74bf0727282b
                        at /checkout/src/liballoc/boxed.rs:635
   7:     0x56532b481e13 - <alloc::boxed::Box<alloc::boxed::FnBox<A, Output$u3d$R$GT$$u20$$u2b$$u20$core..marker..Send$u20$$u2b$$u20$$u27$a$GT$$u20$as$u20$core..ops..function..FnOnce$LT$A$GT$$GT$::call_once::h89ecb0376eab96e6
                        at /checkout/src/liballoc/boxed.rs:655
                         - tikv::raftstore::store::msg::Callback::invoke_with_response::hd97635c8677b0280
                        at src/raftstore/store/msg.rs:74
   8:     0x56532b639959 - tikv::raftstore::store::worker::apply::ApplyCallback::invoke_all::{{closure}}::hef317f5553c32ffa
                        at src/raftstore/store/worker/apply.rs:210
                         - <core::option::Option<T>>::map::hd0180dda22da680f
                        at /checkout/src/libcore/option.rs:404
                         - tikv::raftstore::store::worker::apply::ApplyCallback::invoke_all::h041788c5f74ac70a
                        at src/raftstore/store/worker/apply.rs:210
                         - tikv::raftstore::store::worker::apply::ApplyContextCore::write_to_db::hc40d3a232f21a17d
                        at src/raftstore/store/worker/apply.rs:332
   9:     0x56532b63a69f - tikv::raftstore::store::worker::apply::ApplyContextCore::commit_opt::hcdee16c5f1789e29
                        at src/raftstore/store/worker/apply.rs:313
  10:     0x56532b6375fc - tikv::raftstore::store::worker::apply::ApplyContextCore::commit::h0c1ba7daa9da77d5
                        at src/raftstore/store/worker/apply.rs:307
                         - tikv::raftstore::store::worker::apply::ApplyDelegate::handle_raft_entry_normal::h4985fdb9a600f05b
                        at src/raftstore/store/worker/apply.rs:620
                         - tikv::raftstore::store::worker::apply::ApplyDelegate::handle_raft_committed_entries::hd1fb2174284af3f3
                        at src/raftstore/store/worker/apply.rs:572
  11:     0x56532b632e72 - tikv::raftstore::store::worker::apply::Runner::handle_applies::hb6b17ca3a51a2254
                        at src/raftstore/store/worker/apply.rs:2104
                         - <tikv::raftstore::store::worker::apply::Runner as tikv::util::worker::Runnable<tikv::raftstore::store::worker::apply::Task>>::run::h6e962018c2147a26
                        at src/raftstore/store/worker/apply.rs:2218
  12:     0x56532bb17adb - <tikv::util::worker::Worker<T>>::start_with_timer::{{closure}}::hb0a2fddaf412a89c
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/pingcap/tikv/src/util/worker/mod.rs:101
                         - std::sys_common::backtrace::__rust_begin_short_backtrace::hd6f18288a5a93ece
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  13:     0x56532b2163a4 - std::thread::Builder::spawn::{{closure}}::h6682623a4453c1b1
                        at /checkout/src/libstd/thread/mod.rs:406
                         - <F as alloc::boxed::FnBox<A>>::call_box::hfa61078dd51ed6db
                        at /checkout/src/liballoc/boxed.rs:635
  14:     0x56532bab7c87 - std::sys::unix::thread::Thread::new::thread_start::h0c3a0b0523777f20
                        at /checkout/src/liballoc/boxed.rs:645
  15:     0x7f24397566b9 - start_thread
  16:     0x7f243927641c - clone
  17:                0x0 - <unknown>`

**Comment by siddontang** [comment]
oh, this is a known problem.

/cc @breeswish

**Comment by dbjoa** [comment]
@siddontang, would you let us know the issue filed?

**Comment by breeswish** [comment]
Hmm, currently when our scheduler channel is full, tikv will panic. You can adjust the configuration `scheduler-notify-capacity` to a larger value, i.e. `102400`, so that it will be less likely to crash.

The reason that scheduler channel is full is related to large amount of log output from scheduler when operations takes > 1s. This issue has been solved in master branch, but not 2.0.x.

**Comment by jaltabike** [comment]
@siddontang @breeswish 
Thank you for your comments.

Again, I performed the same benchmark with my latest benchmark [above](https://github.com/pingcap/tidb/issues/7349#issuecomment-415263515).

The only difference was a tidb version; I used the tidb version 2.1.0-rc.1 which is the latest version I can install by using tidb-ansible now.

As the result, it seemed that data and loads were relatively well-distributed, and there was no error during the benchmark.

However, there were two unusual things.

1. The average TPS maintained a target TPS (20,000), but there were several temporary decreases in TPS during the benchmark, as follows:
![image](https://user-images.githubusercontent.com/1661884/44692390-b058d800-aa9d-11e8-872d-5e84d8a48e97.png)
Note that, prior benchmark's result showed relatively stable TPS.
Could you explain what caused this phenomenon?

2. There were some peaks for "region average written keys" (around at 04:00~06:00, 12:00-16:00)
"active written leaders" seemed to be related to the symptoms.
Could you explain what happened at those times?
![image](https://user-images.githubusercontent.com/1661884/44692631-c0bd8280-aa9e-11e8-8b21-7306dd6b1041.png)

**Comment by breeswish** [comment]
@jaltabike Sorry I missed the notification. Would you like to share the TiKV metrics in the "Threads" section? We can help diagnosis the issue. Currently we indeed have some known edge cases that may cause what you see and the fix requires some adjustments of configurations. However we need to first identify it.

**Comment by jaltabike** [comment]
Thank you, @breeswish 
TiKV metrics in the "Threads" section are as follows:
![image](https://user-images.githubusercontent.com/1661884/44984840-394da300-afb9-11e8-9714-710f01173459.png)
![image](https://user-images.githubusercontent.com/1661884/44984850-3fdc1a80-afb9-11e8-8a20-c6085ec10bdb.png)

There are only 2 metrics in the "Threads" section.
Each metric contains various types of values, so that it is not easy to see the metrics.
If you specify some types you want to see, I will share the metrics contains only those types of values.

**Comment by breeswish** [comment]
@jaltabike Hi, there should be a dashboard called "xxx-tikv" (by default, `IP:3000/dashboard/db/test-cluster-tikv`), in which there is a panel called "Thread CPU".

**Comment by jaltabike** [comment]
@breeswish 
TiKV metrics in the "Thread CPU" section are as follows:
![image](https://user-images.githubusercontent.com/1661884/45074576-f4438100-b11e-11e8-9410-bbb2ae8b1045.png)
![image](https://user-images.githubusercontent.com/1661884/45074585-fc032580-b11e-11e8-985f-db8058f20d4d.png)
![image](https://user-images.githubusercontent.com/1661884/45074612-10472280-b11f-11e8-83c3-b340e74a18a1.png)
![image](https://user-images.githubusercontent.com/1661884/45074623-176e3080-b11f-11e8-9b46-ca1148fbcde6.png)

I also attach again the metrics that seemed to have problems.
![image](https://user-images.githubusercontent.com/1661884/45074667-4d131980-b11f-11e8-85f9-53ff1f07b834.png)

**Comment by breeswish** [comment]
Hi @jaltabike 

The jitter has a direct relationship with the panic issue you face previously. Previously this kind of jitter will cause panic, now it will not panic, but will slow down the write for a short time. This situation is relaxed in 2.1 (master) branch, because logging becomes async.

Currently I have no idea about the active written leader issue. Would you like to share your logs? We may be able to investigate its cause according to logs. Also you could try with latest master, which provides better region split functionality, maybe helpful to stabilize the write QPS.

**Comment by jaltabike** [comment]
@breeswish 
I attached my log files:
[tikv-logac.zip](https://github.com/pingcap/tidb/files/2364796/tikv-logac.zip)
[tikv-logad.zip](https://github.com/pingcap/tidb/files/2364797/tikv-logad.zip)
[tikv-logaa.zip](https://github.com/pingcap/tidb/files/2364798/tikv-logaa.zip)
[tikv-logab.zip](https://github.com/pingcap/tidb/files/2364799/tikv-logab.zip)

Please notice that there are some errors such as "get snapshot failed".

Thank you.

**Comment by breeswish** [comment]
@jaltabike I have got your logs. Will keep you updated once there are some findings.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open it if you are still experiencing issues. Thank you!
