### ISSUE TITLE
RegionNotFound should be retryable

### ISSUE THREAD

**Issue by BusyJay** [pingcap/tidb#7354]
According to the code

https://github.com/pingcap/tidb/blob/3ac6d3a9f40335d9c1de399aea8e8409f4815efa/store/tikv/region_request.go#L235-L239

RegionNotFound error will not be retried. However if a region is merged, it will report `RegionNotFound`, which should be retried again.

**Comment by disksing** [comment]
@BusyJay It is retryable, it just doesn't try again by resending the same request.

**Comment by coocood** [comment]
@BusyJay 
Have you met the error in a cluster?
Is it possible that the error retried but the retry limit is reached?

**Comment by BusyJay** [comment]
Looks like a bug from TiKV, which handles the errors from internal API calls inappropriately.
