### ISSUE TITLE
select for update 

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7360]
I execute the same sql in mysql and TiDB, but TiDB spend more time then mysql,
TiDB needs 0.27sec, mysql nees 0.02sec
the sql is `select total from user_coin_wallet where uid = 3 and coin_id = 2 for update;`
and the explain:
![_20180811153420](https://user-images.githubusercontent.com/13601367/43989439-9a9af4c2-9d7c-11e8-97d4-7966afa08be0.png)

**Comment by lysu** [comment]
Thanks for your feedback!  @gutongjiang 

What about execute time & explain result for same query without `for update`~?

**Comment by lysu** [comment]
And maybe give us a MySQL explain result if convient, thx~

**Comment by zz-jason** [comment]
@gutongjiang Could you provide us the following information to help us locating why the sql runs slower than MySQL:

- what is the result of the following two queries:
```sql
select count(*) from user_coin_wallet where uid = 3;
select count(*) from user_coin_wallet where uid = 3 and coin_id=2;
```
- `create table` statement for the `user_coin_wallet` table in the query:
```sql
show create table user_coin_wallet\G
```
- TiDB version:
```sql
select tidb_version()\G
```
- the statistics data of the table `user_coin_wallet`:
```sh
curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > ${table_name}_stats.json
```

- the execution plan of MySQL:
```sql
explain format = json
select total from user_coin_wallet where uid = 3 and coin_id=2 for update;
```

**Comment by kolbe** [comment]
@gutongjiang it's been 9 months since you opened this question and we have not heard any reply from you to questions asking for additional details, so I am going to close this question now. If you are still seeing similar performance issues and want to provide some additional details, please re-open this issue.
