### ISSUE TITLE
lost connection when I create partitioned table

### ISSUE THREAD

**Issue by chainkite** [pingcap/tidb#7362]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I tried to load data into tidb with tidb‘s `loader`, but it always lost connection while loading metadata sql, without any error information.

Finally I found out the reason... it lost connection while creating partitioned table. 

Reproduce the issue:
```
mysql> create table test_partition(id bigint, name varchar(255), primary key(id)) ENGINE=InnoDB DEFAULT CHARSET=utf8 PARTITION BY RANGE  COLUMNS(id) (PARTITION p1 VALUES LESS THAN (10) ENGINE = InnoDB);
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

2. What did you expect to see?
Detail error message.

3. What did you see instead?
Lost connection.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.4-1-g06a0bf5
Git Commit Hash: 06a0bf594559630a35e7121e7401f24de9903d31
Git Branch: release-2.0
UTC Build Time: 2018-06-19 05:32:47
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

**Comment by winkyao** [comment]
@ciscoxll PTAL

**Comment by winkyao** [comment]
@ciscoxll I am looking into it.

**Comment by tiancaiamao** [comment]
It's fixed in https://github.com/pingcap/tidb/pull/7252 
Curiously, this bug should not happen in any released version.
Did you ever upgrade the TiDB from an older version? @chainkite

**Comment by winkyao** [comment]
@tiancaiamao No, it is another issue
