### ISSUE TITLE
`State` column in `show processlist` should provide more information.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#7367]
The `show processlist` currently only show a number `2` which represents `autocommit`, but the `State` column is string type, should describe the execution state.

**Comment by morgo** [comment]
I just came across this while load testing.  The states do not need to be identical to MySQL, but currently, I can not differentiate between `running`, and `queued` (i.e. waiting on locks) :(

**Comment by morgo** [comment]
See also: https://github.com/pingcap/tidb/issues/8482

**Comment by clark1013** [comment]
Let me fix it

**Comment by clark1013** [comment]
Oh, sorry I removed the assignment unexpected. I will still fix this issue.

**Comment by zz-jason** [comment]
> Oh, sorry I removed the assignment unexpected. I will still fix this issue.

Don't worry, I reassigned you back. 😂
