### ISSUE TITLE
Programming language sql-driver/mysql-connector test

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#737]
- [x] Golang
- [x] Java
- [x] PHP
- [x] Python
- [x] C/C++
- [x] JavaScript

**Comment by zhangysh1995** [comment]
Connection access denied for `Python 3`:

````
mysql-python-connector: 8.0.19 
OS: Ubuntu 18.04, 4.15.0-72-generic
````

How to reproduce:
*  `$ tiup tidb`
*  `$ sudo MySQL -u root -p`
*  `set password for 'root'@'localhost' = ''; `
* `create user 'name'@'localhost' identified by 'anypasswd';`
* `GRANT ALL PRIVILEGES ON * . * TO 'name'@'localhost';`
* `flush privileges;`
* `create database test;`
* Use script to connect `cnx = mysql.connector.connect(user=name, password='anypasswd', host='127.0.0.1', port=4000, database='test')`

**Comment by Deardrops** [comment]
@zhangysh1995 I try to reproduce this case, But `mysql-connect` can access tidb in this case.

By the way, the case you given is 
```
sudo MySQL -u root -p
```
(connect to Mysql)
instead of 
```
mysql -uroot -h 127.0.0.1 -P 4000
```
(connect to TiDB)

Am I right?

**Comment by zhangysh1995** [comment]
> I try to reproduce this case, But mysql-connect can access tidb in this case.

MySQL recommends using `mysql-python-connector`. 

> By the way, the case you given is
> sudo MySQL -u root -p

Sorry,  I made a typo, it should be `sudo mysql -P 4000 -u root -p `.
This connection is used to create the new user. The bug is triggered when accessing the database with the new user. You could see the config here: 

> Use script to connect cnx = mysql.connector.connect(user=name, password='anypasswd', host='127.0.0.1', port=4000, database='test')

**Comment by Deardrops** [comment]
I download `mysql-python-connector 8.0.19` and try these step by step:
login TiDB and run:
```sql
create user 'name'@'localhost' identified by 'anypasswd';
GRANT ALL PRIVILEGES ON * . * TO 'name'@'localhost';
flush privileges;
create database a2;
```

and then run a python script:
```python
import mysql.connector
 
cnx = mysql.connector.connect(user='name', password='anypasswd', host='127.0.0.1', port=4000, database='a2')


cur = cnx.cursor()
cur.execute("select tidb_version();")
for i in cur: print(i)
```

the output is:
```
➜  ~ python test.py
('Release Version: v4.0.0-beta.2-302-g8c455e86c\nGit Commit Hash: 8c455e86c136ac020129998c94f890448367f62a\nGit Branch: master\nUTC Build Time: 2020-04-22 02:50:24\nGoVersion: go1.14.1\nRace Enabled: false\nTiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306\nCheck Table Before Drop: false',)
```

**Comment by kolbe** [comment]
@zhangysh1995  Your test case uses 'name'@'localhost', but your example connects as 'zhangys'@'127.0.0.1'. Can you please create a test case that shows your connection failure using the real CREATE USER and GRANT statements that you use in your python program?

Please also send the output of this command: `SELECT user, host FROM mysql.user;`

**Comment by zhangysh1995** [comment]
@kolbe @Deardrops Thanks for your explanation, it seems the problem is with my connection configuration. I should use '127.0.0.1' instead of 'localhost'. Sorry for the inconvenience!

**Comment by nullnotnil** [comment]
I have verified that the C/C++ and PHP connectors work as expected.
