### ISSUE TITLE
Make the use of `FixedZone` correct

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tidb#7377]
In our current codebase, we use `FixedZone` to create a customized timezone when  is not set. I suspect our use of `FixedZone` is not correct. 

```
./sessionctx/variable/varsutil.go:401:			return time.FixedZone("UTC", ofst), nil
./store/mockstore/mocktikv/analyze.go:123:	sc.TimeZone = time.FixedZone("UTC", int(analyzeReq.TimeZoneOffset))
./store/mockstore/mocktikv/cop_handler_dag.go:157:		sc.TimeZone = time.FixedZone("UTC", int(dagReq.TimeZoneOffset))
./session/session_test.go:1940:	date := time.Now().In(time.FixedZone("UTC", -8*int(time.Hour/time.Second)))
./session/session_test.go:1944:	date = time.Now().In(time.FixedZone("UTC", 8*int(time.Hour/time.Second)))
```

Running `go doc time.FixedZone`, the following output will be given:
```
func FixedZone(name string, offset int) *Location
    FixedZone returns a Location that always uses the given zone name and offset
    (seconds east of UTC).
```
The given zone name should be unique and different compared with builtin timezone name.

**Comment by zhexuany** [comment]
cc @zz-jason @tiancaiamao for second opinion. ;)

**Comment by zz-jason** [comment]
```
./sessionctx/variable/varsutil.go:401:			return time.FixedZone("UTC", ofst), nil
```

This is how we handle the query like:
```sql
set time_zone = "+08:00"
```

I think this behavior is correct, @tiancaiamao What's your opinion?

**Comment by coocood** [comment]
Go src use the empty string as the fixed zone name, I think we can do the same.

https://github.com/golang/go/blob/master/src/archive/zip/struct.go#L208

**Comment by zhexuany** [comment]
Suppose you have the following situation:

```
loc := time.FixedZone("UTC", int(analyzeReq.TimeZoneOffset))
sc.TimeZone = loc
```

Right now, `sc.TimeZone` is not the `UTC` location but rather the customized location we just created. 

After initialized this `sc.TimeZone`, you need to use this variable in another place. To be exact, you want to adjust the `sc.TimeZone` when `sc.TimeZone.String()` is `UTC`. This is where the confusion arises.

**Comment by zhexuany** [comment]
@zz-jason @coocood Any comments on this issue?

**Comment by zz-jason** [comment]
@zhexuany 
1. in tidb-server, call `time.FixedZone("", offset)` to make a customized timezone.
2. coprocessor also need to handle timezone name/offset for the analyze request in the same way that select request does.

**Comment by zz-jason** [comment]
I'm working on this in https://github.com/pingcap/tidb/pull/7372

**Comment by zhexuany** [comment]
If we set timezone name to the empty string, KV layer does not require any changes. #7372 seems not strongly dependent with this issue. This issue aims to make all use of `FixedZone` correct rather than just change the way we construct time zone in coprocessor layer.

**Comment by tiancaiamao** [comment]
What's the difference between
```
time.FixedZone("UTC", TimeZoneOffset)
```
and 
```
time.FixedZone("", TimeZoneOffset)
```
@zhexuany  @zz-jason

**Comment by tiancaiamao** [comment]
When using offset, I think we should always based on UTC,  there will never be "Asia/Shanghai + offset" sense. @zhexuany 

> To be exact, you want to adjust the sc.TimeZone to Asia/Shanghai when sc.TimeZone.String() is UTC.

**Comment by coocood** [comment]
@tiancaiamao 
If we use an empty string for the fixed zone,  "UTC" will always have the zero offset.
