### ISSUE TITLE
Finish TODOs 

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#738]
Go through all the TODOs in TiDB source code and finish necessary ones.

**Comment by shenli** [comment]
We got 227 TODOs in TiDB.
➜  tidb git:(master) ✗ grep "TODO" -r ./ | wc -l
     227

**Comment by morgo** [comment]
@shenli should we close this issue?

There are still TODOs, but in many cases, they relate to planned future functionality and not bugs.  It will be very hard to close this issue if the goal is zero TODOs :-)
