### ISSUE TITLE
Does TiDB support Hash sharding?

### ISSUE THREAD

**Issue by ddorian** [pingcap/tidb#7392]
Hi,

Will you implement hash sharding together with range-sharding ?
Cause some tables/dbs can be better colocated by <hash(key)>, which will keep many transactions in the same server (like vitess, citusdb etc).

regards,
ddorian

**Comment by lysu** [comment]
Thanks for your feedback! @ddorian 

Current, TiDB only supports range-based sharding.
But with coming soon feature ---- table partition will support range/list also hash re-sharding.

**Comment by ddorian** [comment]
Will the hash partitioning allow multiple tables to be colocated with same value hash(column_id) ?

**Comment by tiancaiamao** [comment]
You can view the implementation as two layer mapping:
1. How to mapping table data to a logical key-value range.
2. How the logical key-value range data is stored into physical TiKV instances.

Hash partitioning will happen in 1, so different table will be hash to different key-value range.
Where the key-range data will be located happen in 2, and it's controlled by https://github.com/pingcap/pd

We use `tableID` in the key prefix, so different tables will hash to different key-range, the logical space of `hash(column_id)` won't be the same.
But at the physical point of view, using some schedule strategy in PD, it maybe possible to make multiple tables data colocated in the same TiKV instance.

@ddorian

**Comment by tiancaiamao** [comment]
> keep many transactions in the same server

While "keep many transactions in the same server" is better for performance, it is not really distributed transaction. It's still transaction on single machine and sharding.
TiDB is a real distributed database.

**Comment by ddorian** [comment]
@tiancaiamao 

Getting good performance on high scalability is understanding the domain really well and how to partition it.
While range-sharding is better scalable, sometimes hash-sharding is better. 
Best way would be to chose what you need depending on table.

Should I keep this open as a feature request to colocate different tables to same server with same `hash(value)` ?

**Comment by tiancaiamao** [comment]
From the user's point of view, he should not care about how the database is implemented.

The ultimate pursue of our database is that, even the user know nothing about range-sharding or hash-sharding (which is about implementations), the database is still very scalable and get a high performance.

Of course, a good understanding of the implementation is very useful to constructing a better system for the user's business. **We should provide more flexible options for those advanced users.** For example, [table partition](https://github.com/pingcap/tidb/projects/6) is currently under active development.

I think it's okay to leave this issue open, it's a good suggestion.
When one day TiDB could achieve the same performance benefits, with more user friendly mechanism, then it's time to close.

@ddorian

**Comment by ddorian** [comment]
@tiancaiamao 

There is **no** product  good with scalability / performance where the user shouldn't care how the database is implemented. 

You can think hbase, cassandra, scylladb, elasticsearch, redis, postgresql,tidb, on all of them you should be careful with your schema,partitioning,indexes,hotspots depending on your workload. While they will work knowing ^ will 10x+ your speed.

Extreme/best case is redis, where you have per-command time-complexity.
Or scylladb has auto configuration, but you need to be very careful with schema/partitioning/compaction-strategy.

**Comment by tiancaiamao** [comment]
> There is no product good with scalability / performance where the user shouldn't care how the database is implemented.

That's happening...

MySQL: SQL is a friendly user interface
hbase, cassandra, scylladb, elasticsearch ... : NoSQL is highly scalable 
Spanner, TiDB, CockroachDB: I see a wonderful future!

**Comment by ddorian** [comment]
Let's take cockroachdb since it's closer to TiDB. To get best performance you need to know and use:
https://www.cockroachlabs.com/docs/stable/performance-best-practices-overview.html

Even adding an index, you have to be careful on the order of fields, cause you may get a new hotspot if it starts with low-cardinality/timestamp/autoincrement field. See column families, partitioning, all the subpages there. All of them explain how the db works underneath so they're on your mind when you design/use it.

While you can get `ok` performance on mysql/postgresql, you will have to get good performance. Ex: hot tuple updates in postgresql etc.

Nosql is highly scalable, but when you don't know how things work underneath (at least partitioning + data layout + querying) you'll have a bad time very soon.

**Comment by tiancaiamao** [comment]
CockroachDB's best practices mostly applicable to TiDB. 
There is also this one https://pingcap.com/blog/2017-07-24-tidbbestpractice/

> a good understanding of the implementation is very useful to constructing a better system for the user's business.

I've said it before, but there are still something need to clarify: the best practices tell you how to use the database, it's should not be a emphasize on how the database is implemented.

Take this example as an analogy, does one need to know all things about the engines, dynamics... to drive a car? No! what he needs is the driving skill. It's similar to the database implementation and its user guide. When one day, AI is strong enough (that's happening), even the driving skill is not required.

As a user, he should forget the sharding details, those knowledge will not be important one day.
Our vision should be opening the new age, rather than becoming another NoSQL.

**Comment by ddorian** [comment]
`will not be important one day`, yes, one day when network latency is 0ms.
Until then, everybody who will make single-node joins/transactions will get better performance.
