### ISSUE TITLE
investigate can we replace logrus with uber zap 

### ISSUE THREAD

**Issue by zhexuany** [pingcap/tidb#7413]
`zap` is much more faster than `logrus`. If we can replace it, then overall performance will benefit from this replacement.

**Comment by shenli** [comment]
There is already an issue about zap.
https://github.com/pingcap/tidb/issues?utf8=%E2%9C%93&q=is%3Aissue+zap

**Comment by nullnotnil** [comment]
I am going to close this as stale. `zap` is now used in a lot of places.
