### ISSUE TITLE
region not found for key "mBootstra\xffpKey\x00\x00\x00\x00\xfb\x00\x00\x00\x00\x00\x00\x00s"

### ISSUE THREAD

**Issue by Lyle-liang** [pingcap/tidb#7416]
> ansible-playbook start.yml
error log
![image](https://user-images.githubusercontent.com/14850448/44192625-c3e17600-a162-11e8-843d-fd768e66f4a8.png)

![image](https://user-images.githubusercontent.com/14850448/44192664-e4113500-a162-11e8-8c63-5cbc95ff115b.png)

why and what to do?
 Thanks.

**Comment by lamxTyler** [comment]
@Lyle-liang Could you verify that is the pd server alive?

**Comment by Lyle-liang** [comment]
@lamxTyler I am trying to deploy. wait for a moment.

**Comment by Lyle-liang** [comment]
@lamxTyler 
![image](https://user-images.githubusercontent.com/14850448/44194774-977d2800-a169-11e8-91c7-51ef31391062.png)

I meet the error again. I verify the pd servers are alive.

**Comment by Lyle-liang** [comment]
I use this demo 
![image](https://user-images.githubusercontent.com/14850448/44195130-b7611b80-a16a-11e8-9c72-e35b8b0b6049.png)

**Comment by Lyle-liang** [comment]
I find Tikv server is not work. Why? the config like demo.

**Comment by lamxTyler** [comment]
Thanks for your feedback. PTAL @breeswish

**Comment by Lyle-liang** [comment]
get it. Thanks.
