### ISSUE TITLE
实时查询结果怎么落地

### ISSUE THREAD

**Issue by jimmie0204** [pingcap/tidb#7432]
哈喽，我用TiDB做统计报表，在数据量比较大的情况下，一些OLAP实时查询返回可能需要十秒左右，这种对于查看报表的用户来说也是不能接受的。请问我能把实时查询的统计报表结果落到一个表里吗？这样就不用每次都重新计算查询了。或者TIDB还提供了其他更优雅的解决方式吗？

**Comment by ngaut** [comment]
Duplicate issue, closed. #https://github.com/pingcap/docs-cn/issues/844
