### ISSUE TITLE
[tidb-server] connection closing should cancel current running transaction even in retry. 

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#746]
when the connection is been closed, we will close the session, but if the session is retrying transaction, it can't be closed.
we should find a way to cancel the retrying transaction when session closes. 

Btw, we should check the connection closed too and close the session, but now if the transaction is in retry, we can't know the connection closed or not easily. 

@shenli @coocood

**Comment by coocood** [comment]
We can add a method `IsStopped` in Context to check if the transaction is stopped, and in every `Next` method in executor, call this method, if it is stopped, return `ErrStopped`.

**Comment by siddontang** [comment]
I prefer Cancelled. :-)

**Comment by morgo** [comment]
@coocood @shenli can we close this old issue?
