### ISSUE TITLE
2003 - Can't connect  to mysql server on (61 "Connection refused")

### ISSUE THREAD

**Issue by jiancaiHub** [pingcap/tidb#7466]
TiDB执行查找重复记录的SQL时报：2003 - Can't connect  to mysql server on (61 "Connection refused")
表的大小：2000万
执行的SQL：
`insert into duplicate_ids select id from record where unique_id in (select unique_id from record group by unique_id having count(*) > 1) and id not in (select max(id) from record  group by unique_id having count(*) > 1);`
TiDB的配置：
TiDB/PD 2核4G * 3
TiKV  4核16G * 3 （本地SSD）

**Comment by winoros** [comment]
@jiancaiHub 
Could you give more information such as tidb log of that time?
`2003 error` is usually caused that there's no server listening on the port.
We need more information to know what happened on tidb that time.
