### ISSUE TITLE
TiDB should be able to use sql to get the disk usage

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#7468]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

There's a builtin function or something else, which we can use to get the disk-usage of one table or one database.

3. What did you see instead?

Currently there's only http API to do this. And we can use `tidb-ctl` to do this.
But sql may be much easier.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by morgo** [comment]
The SQL standard way to do this is `information_schema`.  Currently TiDB sets `information_schema.tables.data_length` to always be 16384 (1 InnoDB page).

+1 for exposing more features through the server.  The MySQL team is doing this too (See [#1 Use SQL](https://mysqlserverteam.com/making-mysql-easier-to-use-our-new-server-usability-guidelines/)).

**Comment by shenli** [comment]
@morgo Use SQL API is on the plan. I think it is more convenient. We have a project to expose more cluster internal info to users and tidb admin tools. Will public it on the Github soon.

**Comment by morgo** [comment]
Related to this, `SHOW TABLE STATUS` and `information_schema` both report different numbers for data size statistics (0 versus 100).  When a value is not available, it is better to report `NULL`:

```
MySQL [world]> show table status like 'country'\G
*************************** 1. row ***************************
           Name: country
         Engine: InnoDB
        Version: 10
     Row_format: Compact
           Rows: 100
 Avg_row_length: 100
    Data_length: 100
Max_data_length: 100
   Index_length: 100
      Data_free: 100
 Auto_increment: 100
    Create_time: 2018-08-13 15:36:54.137 +0000 UTC
    Update_time: 2018-08-28 15:13:23
     Check_time: 2018-08-28 15:13:23
      Collation: utf8_general_ci
       Checksum:
 Create_options:
        Comment:
1 row in set (0.00 sec)

MySQL [world]> SELECT * FROM information_schema.tables WHERE table_name='country'\G
*************************** 1. row ***************************
  TABLE_CATALOG: def
   TABLE_SCHEMA: world
     TABLE_NAME: country
     TABLE_TYPE: BASE TABLE
         ENGINE: InnoDB
        VERSION: 10
     ROW_FORMAT: Compact
     TABLE_ROWS: 239
 AVG_ROW_LENGTH: 0
    DATA_LENGTH: 16384
MAX_DATA_LENGTH: 0
   INDEX_LENGTH: 0
      DATA_FREE: 0
 AUTO_INCREMENT: 0
    CREATE_TIME: 2018-08-13 15:36:54
    UPDATE_TIME: NULL
     CHECK_TIME: NULL
TABLE_COLLATION: utf8_bin
      CHECK_SUM: NULL
 CREATE_OPTIONS:
  TABLE_COMMENT:
1 row in set (0.03 sec)
```
