### ISSUE TITLE
loader error

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7478]
Use loader to import database and get an error: 

`
2018/08/24 11:36:27 db.go:45: [error] query sql[CREATE SCHEMA `tidb_loader`] failed Error 1105: privilege check fail
2018/08/24 11:36:27 main.go:56: [fatal] [loader] initialize loader error Error 1105: privilege check fail
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:47: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:259: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/checkpoint.go:91: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/checkpoint.go:80: recover from checkpoint failed
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:289:
`

**Comment by tiancaiamao** [comment]
It seems that you have the privilege to execute the SQL.
Use another account, such as `root`, and try again. @gutongjiang

**Comment by kolbe** [comment]
@gutongjiang were you able to retry this with a TiDB user who has the correct privileges to load data into this table?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
