### ISSUE TITLE
using prepare statement to update bit column failure

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#7497]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
CREATE TABLE bit_update ( id INT NOT NULL PRIMARY KEY, bit BIT NOT NULL )
```

using MySQL API exec sql:

```
UPDATE bit_update SET bit = ? WHERE id = ?
```

configurate parameter bind like this:

```
    char bit[1];
    bit[0]= 0x01;
    unsigned long bit_length= sizeof(bit);
    memset(mysql_bind_param, 0, sizeof(mysql_bind_param));
    mysql_bind_param[0].buffer_type= MYSQL_TYPE_TINY;
    mysql_bind_param[0].buffer= &bit;
    mysql_bind_param[0].buffer_length= sizeof(bit);
```
then  bind, exec and check

```
    if(mysql_stmt_bind_param(mysql_stmt, mysql_bind_param))
    {
        my_chk_stmt(&mysql, mysql_stmt, __LINE__);
    }


    if(mysql_stmt_execute(mysql_stmt))
    {
        my_chk_stmt(&mysql, mysql_stmt, __LINE__);  /* 1265 Data Truncated */
    }
```

2. What did you expect to see?

success update(just as in MySQL)

3. What did you see instead?

```
1265 : Data Truncated
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

2.0.1.rc1

**Comment by lysu** [comment]
We will fix this, but this question can be workaround before our fix.

change

```
    mysql_bind_param[0].buffer_type= MYSQL_TYPE_STRING;
```
to 

```
    mysql_bind_param[0].buffer_type= MYSQL_TYPE_TINY;
```
this question is caused by convert string to int in prepare stituation, so using num type can works before our fix.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
