### ISSUE TITLE
tikv server timeout

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7499]
3 tikv cpu usage is very different, there is a special high, then tikv server timeout appears

**Comment by winoros** [comment]
There may be hot spot. We need more information to know what happened.

**Comment by shenli** [comment]
@gutongjiang Please fill the issue template. Do not delete them.

**Comment by gutongjiang** [comment]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.



2. What did you expect to see?



3. What did you see instead?



4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by victorggsimida** [comment]
i meet the same question.  do i need to open another issue?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
