### ISSUE TITLE
question about deleting tikv from pd-ctl

### ISSUE THREAD

**Issue by goldwinner** [pingcap/tidb#7507]
今天刚用ansible方案装好了TIDB集群，2个tidb、3个pd、3个tikv，运行都正常。之后手贱的想试试缩容命令，然后就悲剧了。
执行命令如下：
pd-ctl -u "http://{pd-addr}:2379" -d store delete store_id，命令执行成功
pd-ctl -u "http://{pd-addr}:2379" -d store
查看这个tikv节点的"state_name"为offline，看指南说等一段时间会变成Tombstone
，等啊等，等了两个小时还是offline状态。当时没看到这个https://github.com/pingcap/tidb/issues/4968
就对这个节点进行初始化、安装tikv节点，再滚动升级，升级之后上grafana看状态，store节点倒是有3个，但之前下线的那个节点的store_id变了，而且还有1个处在Tombstone状态的store节点。

请问大神，如何才能在grafana上去掉这个处在Tombstone状态的store节点？非常感谢！

**Comment by winoros** [comment]
Thanks for your reporting, we'll reply you soon.

**Comment by disksing** [comment]
@goldwinner Another thing is that we need to move all data from the offline store to another available store before switching it to _Tombstone_ state. As your cluster has only 3 TiKV nodes, there is no other TiKV to store data, so the state will never proceed to _Tomestone_.

**Comment by goldwinner** [comment]
@nolouch 你的意思是grafana里面的这个“处在Tombstone状态的store节点”，没有办法去除掉了，对吗？

@disksing 我在https://github.com/pingcap/tidb/issues/4968 里面看到过类似信息，可惜我之前没看到。
但就我的集群来说，那个节点我折腾了很久：初始化、清空tikv节点数据、重新加入集群、重启集群、滚动升级等等都试了个遍，一直都是offline状态。突然有一次滚动升级之后，这个store节点就变up状态了。但是store_id不是之前的5，变成了1001。在grafana里面看就是有4个store，3个up、1个tombstone。

我想提个建议：“在做缩容的时候检测一下节点数量，对于已经是最小配置的集群(3 PD、3TiKV、2TiDB)，就提示无法缩容，以免其他人犯和我一样的错误”
最后，感谢两位的答复。

**Comment by disksing** [comment]
@goldwinner Thank you for your suggestion. I added an issue in the backlog. We might consider improving it  in the future.

**Comment by kolbe** [comment]
@goldwinner this question has been answered and your recommendation to give better feedback to the user has been implemented, so I am going to close this issue now.
