### ISSUE TITLE
tidb grafana no data points

### ISSUE THREAD

**Issue by GiggleAll** [pingcap/tidb#7509]
I run tidb tikv pd in the test env. the config like this:
![image](https://user-images.githubusercontent.com/12868931/44698769-f6b93180-aab3-11e8-8466-8435f6056f16.png)
![image](https://user-images.githubusercontent.com/12868931/44698776-fde03f80-aab3-11e8-8733-36b8010cdd3e.png)

And above config file like this:
pd.toml:
![image](https://user-images.githubusercontent.com/12868931/44698821-1d776800-aab4-11e8-82af-49be58fdec44.png)
tikv.toml:
![image](https://user-images.githubusercontent.com/12868931/44698835-2700d000-aab4-11e8-86fd-639ba68a1c6e.png)

pushgateway run like this:
![image](https://user-images.githubusercontent.com/12868931/44698859-3a13a000-aab4-11e8-8530-e3291726e230.png)

promethus run like this:
![image](https://user-images.githubusercontent.com/12868931/44698887-53b4e780-aab4-11e8-9273-f47ddd3da10f.png)
and it's config file like this:
![image](https://user-images.githubusercontent.com/12868931/44698911-6b8c6b80-aab4-11e8-809d-1e10eb362661.png)

But grafana display like this:
![image](https://user-images.githubusercontent.com/12868931/44698941-8c54c100-aab4-11e8-8ca7-6d1e3643d520.png)

there is no data. and network display like this:
![image](https://user-images.githubusercontent.com/12868931/44698986-b9a16f00-aab4-11e8-847a-c8f59959ecbc.png)

If you need docker logs, tell me.

**Comment by winkyao** [comment]
@LinuxGit @tennix PTAL

**Comment by LinuxGit** [comment]
You can https://github.com/pingcap/tidb-docker-compose or https://github.com/pingcap/tidb-operator d driectly.
You should import  prometheus datasource for grafana. And check if there's metrics on pushgateway and prometheus web pages.

**Comment by GiggleAll** [comment]
Yep. I already import datasource for grafana. the info like this:
I config prometheus.yml like this ：
![image](https://user-images.githubusercontent.com/12868931/44701441-510cbf00-aac1-11e8-94cf-8f8fd8221726.png)
when access prometheus it's display like this:
![image](https://user-images.githubusercontent.com/12868931/44701471-7bf71300-aac1-11e8-9af0-80153bf91be8.png)
I think maybe "http://120.220.14.94:9091/metrics" "/metrics"  it's problem.  
But I access pushgateway. It display like this:
![image](https://user-images.githubusercontent.com/12868931/44701543-c4aecc00-aac1-11e8-95d4-41bd07ece966.png)
no "/metrics" it's work well. And these are my config like the office documents. I copy that to my config.
![image](https://user-images.githubusercontent.com/12868931/44701575-f758c480-aac1-11e8-9233-7db7ef2e4f1c.png)
my run it like above picture.
What's wrong? Can you help me ?

**Comment by LinuxGit** [comment]
You can try pushgateway v0.4.0, and check if there's metrics in pushgateway job group, pushgateway' `/metrics` interface need to be available.

**Comment by GiggleAll** [comment]
Yep  the v0.4.0 work well.  and the v0.5.0 hava bugs, and the bug has not been fixed so far.  I found pushgateway issue, someone said that we should not use 0.5.x.  
thanks @LinuxGit .maybe update your office document(tidb) to avoid this problem.

**Comment by GiggleAll** [comment]
That's cool, But if use prometheus to pull metrics directly, each node needs an open port. It is not safe for a user with many nodes to open the port. Will you have the better way to solve it?

**Comment by LinuxGit** [comment]
TiDB, PD and binlog modules have /metrics interface already on its service port or status port.
