### ISSUE TITLE
`tls: bad certificate` when starting pd

### ISSUE THREAD

**Issue by hh8shyy** [pingcap/tidb#7514]
WARNING: 2018/08/28 13:56:04 Failed to dial 0.0.0.0:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
WARNING: 2018/08/28 13:56:04 Failed to dial x.x.x.x:2379: connection error: desc = "transport: authentication handshake failed: remote error: tls: bad certificate"; please retry.
2018/08/28 13:56:04.228 log.go:82: [warning] etcdserver: [failed to reach the peerURL(https://c.c.c.c:2380) of member 155cafce75bd3446 (Get https://c.c.c.c:2380/version: dial tcp c.c.c.c:2380: connect: connection refused)]
2018/08/28 13:56:04.228 log.go:82: [warning] etcdserver: [cannot get the version of member 155cafce75bd3446 (Get https://c.c.c.c:2380/version: dial tcp c.c.c.c:2380: connect: connection refused)]
2018/08/28 13:56:06.644 log.go:82: [warning] rafthttp: [health check for peer 155cafce75bd3446 could not connect: dial tcp c.c.c.c:2380: connect: connection refused]
2018/08/28 13:56:07.202 main.go:92: [fatal] run server failed: context deadline exceeded
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/server.go:164: 
/home/jenkins/workspace/build_pd_2.0/go/src/github.com/pingcap/pd/server/server.go:276:

不知道这个是什么问题

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
