### ISSUE TITLE
enhance partition pruning for table partition

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#7516]
There are two known issues for current partition pruning implementation:

1. it doesn't support filter conditions that can't be push down to datasource 
2. it doesn't support expressions that can't calculate range

Both of them are not reasonable.

@coocood advised in https://github.com/pingcap/tidb/pull/6642 to ignore the selection node above datasoure node, so filter conditions that can't be push down to datasource won't be considered by partition pruning function, that's why limitation 1 exists.

Suppose we haven't implement timestamp type in TiKV yet, the filter condition will not be pushed down to datasource, then partition pruning can't work on this example:

```
select ts from t where ts > 20060308110502
```

Limitation 2 comes from the fact that we currently use range calculation to implement partition pruning.

```
create table t (id int) partition by range (to_days(id)) ...
select * from t where id > 2018-03-08
```

`to_days` is a function, we can't calculate range for it, so partition pruning can't work.

**Comment by winoros** [comment]
This is also the limitation the non-partitioned table have when calculating range.

**Comment by tiancaiamao** [comment]
A demo for it https://gist.github.com/tiancaiamao/4aab62ba70381fce15da1e4572fbd0b1

**Comment by morgo** [comment]
In #7523 I have a small feature request which complements test-cases for partition pruning.

**Comment by tiancaiamao** [comment]
I have already make partition info visible in this PR:
https://github.com/pingcap/tidb/pull/7505/files#diff-0d9c730193ced8057a092d0c770ea44fR28

There is a lot of room for improvement, any suggestion is welcome. @morgo

**Comment by lerencao** [comment]
Awesome
