### ISSUE TITLE
syncer tool run failed.  "xxx table doesn't exist"

### ISSUE THREAD

**Issue by GiggleAll** [pingcap/tidb#7526]
I use syncer tools that it work well in the test env,but when I run dev env it have some problems.
![image](https://user-images.githubusercontent.com/12868931/44765805-0d7d8800-ab89-11e8-8796-54137234e8fd.png)
this check all pass.

but I run "./bin/syncer -config config.toml -log-file ./syncer.log"
the error like this:
![image](https://user-images.githubusercontent.com/12868931/44765875-60efd600-ab89-11e8-9e35-30d614328efa.png)
But I have this databases and tables. I selected it and these tables have data.
Do you known the reason?  Please help me.
thanks

**Comment by Lunatictwo** [comment]
@GiggleAll Can you share how you fix this problem? I have the same issue.

**Comment by Lunatictwo** [comment]
Thanks @GiggleAll , got it. I fixed it yesterday by setting specific tables (setting [[replicate-do-table]]) in my syncer config file.

**Comment by GiggleAll** [comment]
good idea if you don't need the table, it the better by the way.
