### ISSUE TITLE
optimize count distinct a single column individually 

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#7539]
The implementation of the aggregate function `count(distinct xx)` calculates the value of the input column, encodes it to a `byte` slice, and visits a `map` with that `byte` slice to check whether the input is a distinct value.

It results in a poor performance, which takes **1 min 16.23 sec**:

```sql
TiDB(10.0.1.4:4000)> select count(distinct L_QUANTITY) from lineitem;
+----------------------------+
| count(distinct L_QUANTITY) |
+----------------------------+
|                         50 |
+----------------------------+
1 row in set (1 min 16.23 sec)
```

But we can specially handle the scenario that there is only one parameter in the `count` function, which might be easy with the help of `xxxSet` defined in **executor/aggfuncs/sets.go**.

And after the optimization, `count(distinct)` a single column should be at least as fast as `avg(distinct)`, which takes **56.60 sec**:
```sql
TiDB(10.0.1.4:4000)> select avg(distinct L_QUANTITY) from lineitem;
+--------------------------+
| avg(distinct L_QUANTITY) |
+--------------------------+
|                     25.5 |
+--------------------------+
1 row in set (56.60 sec)
```

**Comment by winoros** [comment]
Another fact is that if we can choose stream agg with index to do the distinct, its performance is far more better than hash.
Maybe we can first rewrite the things with single distinct to group by first. Then optimize the group-by's performance.

**Comment by zz-jason** [comment]
@winoros yes, the optimizations you mentioned should also be considered. But we still need to optimize the performance of `count(distinct)` a single column, because in some scenarios, we have to calculate the `count(distinct)` directly:

```sql
select count(distinct a), count(distinct b) from t group by c;
```

@winoros It's better to file another issue to describe the rewrite method.
