### ISSUE TITLE
PD server timeoutstart timestamp may fall behind safe point

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#7547]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?
root@vn101:~# mysql -h 192.168.6.101 -P 4000 -u root -D log
ERROR 9001 (HY000): PD server timeoutstart timestamp may fall behind safe point
错误明显忽然时间戳在凌晨5点出现这个问题.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.10-TiDB-v2.1.0-rc.1-1-g01c6bd8

**Comment by coocood** [comment]
@474420502 
Thank you for your report.

Please take a look at https://github.com/pingcap/docs/blob/c198d01eed47b76d0fb3aad552167ed96364d117/FAQ.md#error-9001-hy000-pd-server-timeout-start-timestamp-may-fall-behind-safe-point

**Comment by coocood** [comment]
@474420502 
Another possible reason is that the disk on the PD's machine is slow.

**Comment by coocood** [comment]
You can try to deploy PD on a dedicated server and see if the error happens again.

**Comment by 474420502** [comment]
@coocood  :+1:  :ok_hand:  thanks!

**Comment by shenli** [comment]
@474420502 Does it solve your problem?

**Comment by 474420502** [comment]
@shenli  我已经把该节点分散负载了, 目前还没什么问题, 但是我也不想还原之前的场景.

**Comment by zhexuany** [comment]
@coocood It is worth to add "Another possible reason is that the disk on the PD's machine is slow and busy." to our doc.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
