### ISSUE TITLE
unexpected dml statement found in query event

### ISSUE THREAD

**Issue by bqwzhl20** [pingcap/tidb#7552]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
使用syncer同步数据，然后用pt-table-checksum检查数据一致性
语句如下：
pt-table-checksum -uroot -pxxx -h10.24.195.1 -P3307 --no-check-binlog-format

报错信息如下：
2018/08/30 16:24:17 syncer.go:691: [info] [query]DELETE FROM `percona`.`checksums` WHERE db = 'test' AND tb
l = 'table_test' [current pos](mysql-log-bin.000068, 465066953) [next pos](mysql-log-bin.000068, 465067236) [cu
rrent gtid set]57d7fc65-ef70-11e6-ac32-00163e0e1b0c:1-31872182,56c3ca62-419b-11e5-b955-00163e0052f8:1-21002
65 [next gtid set]56c3ca62-419b-11e5-b955-00163e0052f8:1-2100265,57d7fc65-ef70-11e6-ac32-00163e0e1b0c:1-318
72183
2018/08/30 16:24:17 syncer.go:697: [error] fail to be parsed, error query DELETE FROM `percona`.`checksums`
 WHERE db = 'test' AND tbl = 'table_test': unexpected dml statement found in query event
2018/08/30 16:24:17 syncer.go:962: [info] flush all jobs meta = syncer-binlog = (mysql-log-bin.000068, 4650
66096), syncer-binlog-gtid = 56c3ca62-419b-11e5-b955-00163e0052f8:1-2100265,57d7fc65-ef70-11e6-ac32-00163e0
e1b0c:1-31872252
2018/08/30 16:24:17 meta.go:137: [info] save position to file, binlog-name:mysql-log-bin.000068 binlog-pos:
465066096 binlog-gtid:56c3ca62-419b-11e5-b955-00163e0052f8:1-2100265,57d7fc65-ef70-11e6-ac32-00163e0e1b0c:1
-31872181
2018/08/30 16:24:17 main.go:79: [error] /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/g
ithub.com/pingcap/tidb-enterprise-tools/syncer/ddl.go:29: unexpected dml statement found in query event
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/
syncer/ddl.go:76: query DELETE FROM `percona`.`checksums` WHERE db = 'test' AND tbl = 'table_test'
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/
syncer/syncer.go:698:

2. What did you expect to see?
syncer能在使用pt-table-checksum检查数据一致性时正常同步数据

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by WangXiangUSTC** [comment]
when use pt-table-checksum to compare data, this tool will set binlog format to `statement`, but syncer require `row` format, so this binlog event parsed failed in syncer.

**Comment by WangXiangUSTC** [comment]
@bqwzhl20 any other question? or I will close this issue.

**Comment by chenmin1992** [comment]
how to skip these parse errors???@WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
can't skip parse errors now, you need update syncer.meta file use new binlog position.

**Comment by WangXiangUSTC** [comment]
we have a tool named sync-diff-inspector, it can compare two table's data, and if data is not equal, it will generate sql to fix data. you can quit syncer, and use sync-diff-inspector to generate fix sql, and execute these sql in tidb, and then use the new position to start syncer. you can see this project at https://github.com/pingcap/tidb-tools/tree/develop @chenmin1992

**Comment by chenmin1992** [comment]
thanks for your patient answer. 
but how does it work?does it have performance downgrade to production environment? @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
https://github.com/pingcap/tidb-tools/blob/develop/sync_diff_inspector/config.toml
this is a example config file, if you don't want disturb the production environment, you can set the `check-thread-count` to 1, and use a small value as `chunk-size`

**Comment by chenmin1992** [comment]
I think it should be upgraded by recognizing and skipping statement format binlog.
