### ISSUE TITLE
TiDB will kill process of a simple select sql about 2 minutes

### ISSUE THREAD

**Issue by lvleijie** [pingcap/tidb#7555]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

This is what happened to me, when I tried to query with a simple select sql, It will be killed automatically after about 2 minutes. Just like this :

mysql> select * from mbk_orders where orderid>'1';
已杀死(has been killed)

2. What did you expect to see?

I want to know which parameter control this action and how to change it.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

version 2.0.6

**Comment by winoros** [comment]
@lvleijie 
Thanks for your reporting.
Could you provide more information such as the tidb log or dmesg log around the time executing this sql?
And what error returned from the terminal? Is it something like `Lost connection to MySQL server`?

**Comment by tiancaiamao** [comment]
It seems that mysql client OOM. @lvleijie
