### ISSUE TITLE
question of the guide of syncer

### ISSUE THREAD

**Issue by goldwinner** [pingcap/tidb#7567]
在官方文档：https://pingcap.com/docs-cn/tools/syncer/#syncer-%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3 里面的“配置 Syncer 监控与告警”段落

能否详细解释一下这个expr表达式是什么意思？谢谢！
IF syncer_binlog_file{node='master'} - ON(instance, job) syncer_binlog_file{node='syncer'} > 1

**Comment by zhexuany** [comment]
@goldwinner Thanks for using `TiDB`. This repo may not be a good fit for this question. Maybe you should ask this question in syncer repo.

**Comment by goldwinner** [comment]
@zhexuany syncer不是闭源的吗？请问它的repo地址是多少？

**Comment by zhexuany** [comment]
My bad. I already forwarded this issue to sre team.

**Comment by WangXiangUSTC** [comment]
it means the syncer's synced position is one binlog file behind the master, for example, you show master status in mysql, the binlog position is binlog.00002, but the syncer only synced the binlog.00001, it can means that syncer can not sync data in real time, you need pay attention to it.

**Comment by shenli** [comment]
@goldwinner Does it solve your problem?

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
