### ISSUE TITLE
When TIDB uses mydumper to back up, how much impact will it have on the original performance?

### ISSUE THREAD

**Issue by AlexNewTao** [pingcap/tidb#7569]
1 When TIDB uses mydumper to back up, you need to obtain a global write lock. How much impact will this have on TIDB's original performance?
2 Do you have data to illustrate such an impact?
3 Is there any plan to develop TIDB's own backup solution?
4 When mydumper does not get the global write lock of TIDB, how to ensure the consistency of data?
5 if we get the global write lock of TIDB,how much negtive impact on the  performance

**Comment by coocood** [comment]
@AlexNewTao 
Thank you for your interest in TiDB.

1. it will increase the query latency, but not by much, the accurate impact number depends on the cluster environment.
2. Not yet.
3. Our own backup solution is in the roadmap.
4. The data consistency is ensured by a global timestamp, future inserted data is not visible for the transaction reader.
5. We don't have a global write lock.

**Comment by AlexNewTao** [comment]
@coocood  Thank you very much for replying me so soon. There are still some questions here, I look forward to receiving your answer.

1 What time the backup solution suppose to be released ? Where can I see the roadmap of your development plan?
2 You said the data consistency is ensured by a global timestamp,can you explain it detail?
3 In order to make TIDB better, can you provide details about the solution of tidb backup, we can discuss in detail.

**Comment by csuzhangxc** [comment]
@AlexNewTao 
1. New backup solution will be released around the end of this year, and the roadmap is not yet public.
2. When executing `SHOW MASTER STATUS`, TiDB will return a global timestamp like MySQL's binlog pos.
3. The backup solution is still in the early stage of design.

**Comment by gregwebs** [comment]
Its worth noting that for consistency you need to use our [fork of mydumper](https://github.com/pingcap/mydumper) until we get our changes pushed upstream.

**Comment by morgo** [comment]
Also noting, you can track the progress of merging upstream [in this pull request](https://github.com/maxbube/mydumper/pull/155).

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
