### ISSUE TITLE
pd error 

### ISSUE THREAD

**Issue by iakisey** [pingcap/tidb#7590]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
start pd

2. What did you expect to see?
pd run 

3. What did you see instead?
![431535961443_ pic_hd](https://user-images.githubusercontent.com/20331418/44974445-40ad8600-af92-11e8-9ed4-7297c764e114.jpg)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.1.0-rc.1-7-g38c939f

**Comment by zhexuany** [comment]
@iakisey Thanks for using TiDB. It seems to be a pd problem and you could create a issue at github.com/pingcap/pd

**Comment by nolouch** [comment]
@iakisey  Have you downgraded the PD? Please check the log. Now Version 2.1 can't be downgraded to Version 2.0, you can still use the 2.1 version or use [pd-recover](https://github.com/pingcap/docs/blob/master/tools/pd-recover.md) to recover the PD cluster to 2.0.

**Comment by kolbe** [comment]
@iakisey we haven't heard back from you in a little over 8 months, so I'm going to close this issue now. If you are still seeing this problem, please re-open.
