### ISSUE TITLE
why is this sql so slow

### ISSUE THREAD

**Issue by guohonglei** [pingcap/tidb#7592]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I have a sql ,i don't know why it runs so slow.
the sql is 
``` sql
SELECT *
FROM taxi_ride tr 
WHERE tr.passenger_id = 30317977 AND tr.create_time >= '2018-08-20' AND tr.create_time < '2018-08-31' 
ORDER BY tr.id DESC 
LIMIT 0,20;
```

2. What did you expect to see?
I hope this sql can runs fast in some way

3. What did you see instead?
I don't know.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.0.4-1

**Comment by winoros** [comment]
@guohonglei Thanks for your report.
Please provide the table schema and the `EXPLAIN` result of this sql.

**Comment by zz-jason** [comment]
Could you provide us the following information to help locating why the sql runs slow:

- the execution plan of this SQL in TiDB
```sql
explain format="dot" select ...
explain select ...
```

- TiDB version
```sql
select tidb_version()\G
```

- the `create table` statement for the involved tables
```sql
show create table ${involved_table_1}\G
show create table ${involved_table_2}\G
...
```

- the statistics data of the involved tables
```sh
curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > ${table_name}_stats.json
```

- is the query always slow, or just occasionally

**Comment by guohonglei** [comment]
![sql_explain](https://user-images.githubusercontent.com/22292400/44986947-0e168400-afb8-11e8-8678-3bed9df4e813.png)

**Comment by guohonglei** [comment]
tidb version:  v2.0.4-1

**Comment by winoros** [comment]
@guohonglei What's the index on this table? Or you just want to see the performance without index?

**Comment by zz-jason** [comment]
It's an known issue, you can
1. update the cluster to the latest master version to gain the performance improvement.
2. handcraft the sql to avoid the `desc` order by. For example: if there are total N records without the `limit` clause, the records which have the top 20 least `id` is the same with the records which have the top N-20 largest `id`

**Comment by guohonglei** [comment]
![sql_index](https://user-images.githubusercontent.com/22292400/44987312-669a5100-afb9-11e8-85ba-28165b340134.png)

**Comment by guohonglei** [comment]
@zz-jason   I don't know how to fix it with mysql syntax

**Comment by guohonglei** [comment]
@zz-jason  without limit ,how can I get the top 20

**Comment by zz-jason** [comment]
1. you can get the number of records by this sql query:
```sql
select count(*)
from taxi_ride tr
where tr.passenger_id = 30317977 and tr.create_time >= '2018-08-20' and tr.create_time < '2018-08-31';
```

2. the equivalent sql query for this issue is:
```sql
select *
from (select *
      from taxi_ride tr
      where tr.passenger_id = 30317977 and tr.create_time >= '2018-08-20' and tr.create_time < '2018-08-31'
      order by tr.id asc
      limit N-20, 20
) tmp
order by tmp.id desc;
```

`N` is the result of the former query.

**Comment by guohonglei** [comment]
I find one way , but I don't konw why
```sql
select * from(
SELECT *
FROM taxi_ride tr 
WHERE tr.create_time >= '2018-08-20' AND tr.create_time < '2018-08-31' 
    ORDER BY tr.create_time DESC 
    )t 
    where t.passenger_id = 30317977 

LIMIT 0,20
```

**Comment by zz-jason** [comment]
@gregwebs If it's not convenient to update the cluster to the latest master branch, maybe you can try to update it to the latest `v2.0.6` release version. The performance should also be improved.

**Comment by zz-jason** [comment]
@guohonglei I think the result of this modified query is not the same with the original query, because the modified query orders the result by the value of `create_time`, while the original query orders the result by the value of `id`.

**Comment by guohonglei** [comment]
why order by different field  costs different time, more than 60 seconds and less than 1 second

**Comment by guohonglei** [comment]
Today's slow SQL suddenly runs faster.I'm confused.
I think we haven't changed anything.

**Comment by guohonglei** [comment]
the version is still v2.0.4-1

**Comment by winoros** [comment]
@guohonglei Is the plan changed? You can `explain` and paste the new result.

**Comment by guohonglei** [comment]
here is the new explain:
![sql_explain_new](https://user-images.githubusercontent.com/22292400/45015719-24265200-b055-11e8-8bf0-629797088ca3.png)

**Comment by guohonglei** [comment]
It seems to have changed a lot

**Comment by guohonglei** [comment]
How to analyze table tr?

**Comment by xiaoma20082008** [comment]
@guohonglei run `analyze table tr` in your command line

**Comment by zhexuany** [comment]
@guohonglei Can we close this issue?

**Comment by guohonglei** [comment]
> @guohonglei Can we close this issue?

Yes, although I don't understand the reason

**Comment by zhexuany** [comment]
> Yes, although I don't understand the reason

the reason of why is query so slow?

**Comment by guohonglei** [comment]
> > Yes, although I don't understand the reason
> 
> the reason of why is query so slow?

this question and why suddenly be faster

**Comment by zhexuany** [comment]
> It's an known issue, you can

> update the cluster to the latest master version to gain the performance improvement.
> handcraft the sql to avoid the desc order by. For example: if there are total N records without the limit clause, the records which have the top 20 least id are the same with the records which have the top N-20 largest id

Did you see the above reply from my colleague?

**Comment by zhexuany** [comment]
auto-analyze is running at background. That is could be why.
