### ISSUE TITLE
Is there windows release version ?

### ISSUE THREAD

**Issue by orangeyts** [pingcap/tidb#760]
I just want to test my exist  system.

**Comment by shenli** [comment]
@orangeyts TiDB depends on golang. So I think TiDB can run if you setup your golang environment properly on Windows.

**Comment by orangeyts** [comment]
Thanks,I will try.

**Comment by shenli** [comment]
OK! @orangeyts 
Please feel free to raise an issue if you encounter any problem.

**Comment by orangeyts** [comment]
...tidb-0.5-alpha/ast
...tidb-0.5-alpha/column
...   ...
Like above dir list, which  dir should be set for  "GOPATH"?

**Comment by yanzhe-chen** [comment]
@orangeyts `GOPATH` is your workspace path. It should be set uniformly across all go projects in your machine. Please reference [this](https://golang.org/doc/code.html) doc for more details. Once you have setup your `GOPATH`, you can put `tidb` in `$GOPATH/src/github.com/pingcap/`.
