### ISSUE TITLE
I removed 5 of the 8 tikv machines, can the data be restored

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7601]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

I removed 5 of the 8 tikv machines, can the data be restored?

**Comment by zhexuany** [comment]
Thanks for using `TiDB`. It is possible but the change is small. In my opinion, it depends on region distribution. @breeswish please confirm this.
