### ISSUE TITLE
parser failed to parse comment starts with two dash without whitespace but follows by other control character

### ISSUE THREAD

**Issue by holys** [pingcap/tidb#7603]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
--
-- this is a comment.
--
CREATE TABLE `test`.`test_table_with_comment` (`id` int);
```

Note: The is no whitespace after the first `--` and third `--`.

If we use "%q" in Go to format, it will look like:
```
"--\n-- this is a comment.\n--\nCREATE TABLE `test`.`test_table_with_comment` (`id` int);\n"
```

Btw, I test with parser code, not execution in mysql client.

2. What did you expect to see?
```
Query OK, 0 rows affected (0.20 sec)
```

3. What did you see instead?

```
line 1 column 1 near "-
-- this is a comment.
--
CREATE TABLE `test`.`test_table_with_comment` (`id` int);
" (total length 86)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

418cdf2308c8ebedadbf356142f9afbab9aea111

According to mysql doc: https://dev.mysql.com/doc/refman/5.7/en/ansi-diff-comments.html
>Standard SQL uses “--” as a start-comment sequence. MySQL Server uses # as the start comment character. MySQL Server also supports a variant of the -- comment style. That is, the -- start-comment sequence must be followed by a space (or by a control character such as a newline). 

I found that we only support whitespace in `lexer.go`

```
func startWithDash(s *Scanner) (tok int, pos Pos, lit string) {
	pos = s.r.pos()
         // should we support more control character(space character) ?
	if strings.HasPrefix(s.r.s[pos.Offset:], "-- ") {
		s.r.incN(3)
		s.r.incAsLongAs(func(ch rune) bool {
			return ch != '\n'
		})
		return s.scan()
	}
	if strings.HasPrefix(s.r.s[pos.Offset:], "->>") {
		tok = juss
		s.r.incN(3)
		return
	}
	if strings.HasPrefix(s.r.s[pos.Offset:], "->") {
		tok = jss
		s.r.incN(2)
		return
	}
	tok = int('-')
	s.r.inc()
	return
}

```

**Comment by shenli** [comment]
We should consider comment with `--` and a newline [here](https://github.com/pingcap/tidb/blob/master/parser/lexer.go#L310).

**Comment by kennytm** [comment]
Just quote my comment from Slack,

> i think the proper way is this,
>
> 1. check if `HasPrefix("--") && len() >= 3 && isSpace(s[offset + 2])`
> 2. `incN(2)` instead of 3 (so keep the `\n`)
>    * or just don't `incN()` at all since `'-' != '\n'`
> 3. consume the line until the `\n` like before

If we could figure out the precise definition of "control character" from the MySQL doc we could replace that `isSpace`.

(Maybe need to handle the case where a `--` appears at EOF as well)
