### ISSUE TITLE
TIKV DISCONNECTED!! Raftstore Busy!!

### ISSUE THREAD

**Issue by victorggsimida** [pingcap/tidb#7620]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

i do nothing 

2. What did you expect to see?

tikv just work as normal

3. What did you see instead?

tikv is disconnected in pd ctl with store command

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

| Release Version: v2.1.0-beta-229-g5404e2e
Git Commit Hash: 5404e2eaae27b9ce31264a4eff0a41aa92ffe328
Git Branch: master
UTC Build Time: 2018-08-14 01:46:09
GoVersion: go version go1.10.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e

5. my view
in tikv log 

```
2018/09/05 21:15:09.600 peer_storage.rs:820: [INFO] [region 43171036] 48196358 begin to apply snapshot
2018/09/05 21:15:19.121 kv.rs:1062: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))
2018/09/05 21:15:19.121 kv.rs:1062: [ERROR] send raft msg to raft store fail: Transport(Discard("Failed to send Raft Message due to full"))

another part log

2018/09/05 21:51:56.382 mod.rs:102: [WARN] handle task Snap apply for 48149787 [ta
kes Duration { secs: 421, nanos: 489000000 }]
2018/09/05 21:51:56.395 kv.rs:1062: [ERROR] send raft msg to raft store fail: Tran
sport(Discard("Failed to send Raft Message due to full"))
2018/09/05 21:51:56.396 kv.rs:1062: [ERROR] send raft msg to raft store fail: Tran
sport(Discard("Failed to send Raft Message due to full"))
2018/09/05 21:51:56.407 kv.rs:1062: [ERROR] send raft msg to raft store fail: Tran
sport(Discard("Failed to send Raft Message due to full"))
2018/09/05 21:51:56.407 kv.rs:1062: [ERROR] send raft msg to raft store fail: Tran
sport(Discard("Failed to send Raft Message due to full"))
"

somestime： it print the same log "send raft msg to raft store fail:"  for 5minutes.
```
in tidb log

```
2018/09/05 21:45:21.901 region_request.go:220: [warning] tikv reports `ServerIsBusy`, reason: raftstore is busy
```

6. server status

check cpu and io with top and iostat.  the server is very free

7. You help

Have talked to PINGCAP OP and provide the log! 
BUT, the problem is still going on. And it affect the application request.
It make us (especially my leaders)  feel that  TIDB is not stable and not worth trust。

**Comment by crazycs520** [comment]
Thanks for your feedback. @coocood PTAL.

**Comment by crazycs520** [comment]
@breeswish PTAL

**Comment by victorggsimida** [comment]
more info

1. the problem happen in different tikv. and the  error log 'send raft msg to raft store fail'  always come after apply snapshot

2.I find that the snap directory in data is sometimes 240M or very small several kb in different tikv.

3.I don't know how to fix it. it is very important for us.

**Comment by victorggsimida** [comment]
@siddontang  
hi, I will give it to u tomorrow! Can u give me your email address! 
the log is a little big!

**Comment by Connor1996** [comment]
@victorggsimida you can give the log to me `zhangbokang#pingcap.com`(Please replace # with @)

**Comment by siddontang** [comment]
@victorggsimida 

There is a report icon on the TiKV Grafana page, like

![image](https://user-images.githubusercontent.com/1080370/45102871-2d9ce080-b161-11e8-84f4-880555e0b54b.png)

you can click it and generate a PDF for the whole metric page.

**Comment by victorggsimida** [comment]
@siddontang  ok thanks so much!

**Comment by victorggsimida** [comment]
another problem with syncer 

syncer version

```
Release Version: v1.0.0-8-g6c307cd
Git Commit Hash: 6c307cded4ab46aba6e06b1c14cf277e0e0f3f01
Git Branch: master
UTC Build Time: 2018-05-23 12:47:59
Go Version: go version go1.10.2 linux/amd64
```




1. data in mysql 
```
 table charset: latin1
name varchar(255) : save  utf8  data  ,chinese char
jsondata json type:  save json data , some values  in it is chinese

table definition:
json DEFAULT NULL
DEFAULT CHARSET=latin1 COLLATE=latin1_bin
```

2. after syncer sync the data  to tidb
name is ok,chinese is ok
but the json : chinese is 

```
  name: M's 兰博碁尼[限免]
 json ： extns: {"app_product":{"billesc":{"pgory":"add on","name":"å……æ»¡åŠ›é‡æ„Ÿçš„è·‘è½¦"},,"sunt":1}

as u see:  name is Garbled
```

3. my test

golang： connect mysql with latin1 set in the connection : insert the data to tidb  with another utf8 connection. all data is ok.

but I found that the same data:  

in syncer log I see that the json column bytes is not the same as the result I do with golang test.

4. my view

```
maybe is there something wrong with the binlog parse where json have chinese character
```

But, maybe my view is wrong. Maybe u can test with the same and see will meet the same problem.
Or maybe the latest syncer has fix the problem. I haven't test it !

**Comment by Connor1996** [comment]
@victorggsimida This is off topic which is not convenient for future searching, would you mind create another issue to describe that? I will ask someone take a look tomorrow morning.

**Comment by victorggsimida** [comment]
@Connor1996  log is sent to u.
grafana report is not ready to export!

**Comment by crazycs520** [comment]
@victorggsimida Currently, TiDB only supports utf8 charset.

**Comment by Connor1996** [comment]
By the way, which type is your storage?

**Comment by victorggsimida** [comment]
@Connor1996  SSD.  disk performance is sent to u

**Comment by victorggsimida** [comment]
@Connor1996  write  means sequential write？  or random write？

**Comment by victorggsimida** [comment]
@Connor1996  is there any progress after sending u the tikv report.

It seems that the problem is more serious yesterday!

**Comment by Connor1996** [comment]
@victorggsimida Please check your email, we need some adjustment for metrics showing

**Comment by Connor1996** [comment]
Then most details are involved in email, here just give a brief report. 
From the log, we see that write operations to RocksDB cost too much time which caused by write stall, so raft message channel is full. In RocksDB log, find the reason for write stalls is too many pending compaction bytes that all comes from write cf. But the write workload is not too heavy, and then we find that the "dynamic-level-bytes" for write cf is set to "true". After communication, it is confirmed that @victorggsimida did change that config, and used tikv-ctl to compact before changing, but only compact default cf rather write cf. So this cause unexpected LSM tree structure and make too many pending compaction bytes.
Solution: set that config back to "false", and let RocksDB to finish compaction.

**Comment by xujiapei** [comment]
@victorggsimida I have the same problem to you.do u  resolve this problem

**Comment by victorggsimida** [comment]
@xujiapei   this is related with the write input which is too large that the device is too busy or tikv is too busy
