### ISSUE TITLE
enhance the predicate push down on join operator

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#7628]
For example, the DNF `(t1.a=1 and t2.a=1) or (t1.a=2 and t2.a=2);` can be transformed to the following CNF:

```
(t1.a=1 or t1.a=2)
and
(t1.a=1 or t2.a=2)
and
(t2.a=1 or t1.a=2)
and
(t2.a=1 or t2.a=2);
```

**Comment by winoros** [comment]
There's no algorithm to do this transformation with a acceptable time complexity.
Spliting it to `(a = .. or a = ..) and (b = .. or b =..) and original DNF expr` is more exercisable

**Comment by tiancaiamao** [comment]
```
(a and b) or c 
==> 
(a or c) and (b or c)
```

If we continue to apply this transform rule to

`(t1.a=1 and t2.a=1) or (t1.a=2 and t2.a=2);`

==>

`(t1.a=1 or (t1.a=2 and t2.a=2)) and (t2.a=1 or (t1.a=2 and t2.a=2))`

==>

`(t1.a=1 or t1.a=2) and (t1.a=1 or t2.a=2) and (t2.a=1 or t1.a=2) and (t2.a=1 or t2.a=2)`

@winoros

**Comment by zz-jason** [comment]
Yeah, considered the time complexity and we only need filters on certain columns, how about simply implement the function:

```
ExtractFiltersOnColumn(*Column, Expression)
```

**Comment by zz-jason** [comment]
and some SQL queries are made by scripts, not handcrafted

**Comment by lysu** [comment]
it seems gp try to solve same question~ https://sourcegraph.com/github.com/postgres/postgres/-/commit/9888192fb7732cdd1a85a7af9582d72a297d9a6d

**Comment by eurekaka** [comment]
@lysu I have taken a brief glance of the PG patch, it should provide same functionality as what `ExtractFiltersFromDNFs` does in TiDB, i.e, extract common CNF items appeared in all DNF items, for example:
```
(a = 1 and b = 1) or (a = 1 and a = 1 and b = 1) or (a = 1 and b = 2)
=>
((b = 1) or (b = 1) or (b = 2)) AND (a = 1)
```
this cannot handle cases of this issue like `(a = 1 and b = 1) or (a = 2 and b = 2)`, because no common expression can be extracted.
