### ISSUE TITLE
Data missing from index

### ISSUE THREAD

**Issue by hustwk** [pingcap/tidb#7637]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

1.1 create test table 
```
CREATE TABLE `tt` (
  `c1` varchar(10),
  `c2` decimal(22)
);
```

1.2 insert value
```
insert into tt values ('abc', 201710);
```

1.3 select data without index
```
select * from tt where c1='abc' and c2=201710;
+------+--------+
| c1   | c2     |
+------+--------+
| abc  | 201710 |
+------+--------+
1 row in set (0.00 sec)
```

1.4 create index
```
create index idx_tt on tt(`c1`,`c2`);    
Query OK, 0 rows affected (3.02 sec)
```

1.5 select data again with index, NO DATA selected
```
select * from tt where c1='abc' and c2=201710;
Empty set (0.01 sec)
``` 

2. What did you expect to see?
The data selected with index is the same as not using index.

3. What did you see instead?
Data is missing!

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
 Release Version: v2.0.5
Git Commit Hash: 43ab80012ae6a154e221e124a2ad3a396f0de822
Git Branch: release-2.0
UTC Build Time: 2018-07-06 08:52:37
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |
```

**Comment by crazycs520** [comment]
@hustwk Thanks for your feedback.
The bug is already fix in mater.

**Comment by hustwk** [comment]
Glad to hear that. You guys are so great！
