### ISSUE TITLE
Inappropriate handle empty value in load data

### ISSUE THREAD

**Issue by ssnijik** [pingcap/tidb#7652]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
When loading data(csv) into tidb, if numeric field(integer, double, ...) is empty, it will raise an error from function StrToFloat.

2. What did you expect to see?
I try to insert following record into table(decimal(18,0),varchar(64),tinyint,smallint,double,double,double,double,char(1),int,double,char(1),char(1),char(1),char(1))
`123456789,xyzxyz,1,-99,,,,,N,,,N,N,N,N`
I think it will be insert into table correctly

3. What did you see instead?
Error is raised from function StrToFloat. Since almost every record raise such an error log, log is filled with tons of the same error.

> 2018/09/07 00:44:50.440 write.go:712: [warning] ignore err:[types:1265]Data Truncated
> /home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/types/convert.go:421: 
> /home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/types/convert.go:321: 
> /home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/types/datum.go:742: 
> /home/jenkins/workspace/build_tidb_2.0/go/src/github.com/pingcap/tidb/table/column.go:154:

If i change record to following style, everything goes fine.
`123456789,xyzxyz,1,-99,0,0,0,0,N,0,0,N,N,N,N`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.0
Git Commit Hash: 637e130e6a9ba2e54e158131c0466233db39a60e
Git Branch: release-2.0
UTC Build Time: 2018-04-27 11:43:00
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

It'll be appreciated if you can also answer the following questions:
1. Is there any schdule for new data importing tool **lighting**?
2. What's the most effect way to import data for now, **load data** or **batch insert**? I tried both, but both of them are too slow for me.

**Comment by crazycs520** [comment]
Hi @ssnijik , Thanks for your feedback. 
1. Dose 123456789,xyzxyz,1,-99,,,,,N,,,N,N,N,N insert into table in MySQL correctly?
2. new data importing tool, [syncer](https://github.com/pingcap/docs-cn/blob/master/tools/syncer.md) , [loader](https://github.com/pingcap/docs-cn/blob/master/tools/loader.md).
3. import data from where?

**Comment by jackysp** [comment]
Hi  @ssnijik , 
Could you show your data in TiDB by `select * from`, after loading data `123456789,xyzxyz,1,-99,,,,,N,,,N,N,N,N` into TiDB. 
Are these results expected as you wish?

**Comment by ssnijik** [comment]
The result is correct, but too many errors mean (a)log file for tidb is too large and (b) tidb need disk IO for every record 
@crazycs520 I don't use syncer or loader because my data source is hdfs not mysql. For data format, I import data by `load data local infile 'part-00001' into table user fields terminated by ',' lines terminated by '\n';', 'part-00001' is a csv file

**Comment by ssnijik** [comment]
Actually the result is different. If the value is empty, i think it should be null, but it is set to be 0.

**Comment by jackysp** [comment]
Thanks for your reply. Does the result the same with MySQL, if you load this line to MySQL?

**Comment by jackysp** [comment]
@ssnijik , if the results are the same with MySQL, I think it is not a bug, due to TiDB is compatible with MySQL. The error your shown is an error which TiDB ignored as a warning. If you do not want it, you could set the log level of TiDB server to error or fatal. 
Btw: Lightning is generally available now. It is much faster than `load data`. I think it is exactly what you need. There is just one thing to mention Lightning also uses the same logic to handle truncate issues. You need also to set the log level of Lightning higher if you do not want this error message.

**Comment by kennytm** [comment]
Hi @ssnijik,

The current version of Lightning is focused on importing local SQL dump only, which may not be suitable for your use case. We plan to implement CSV support by the end of 2018. If you are interested, you may send a mail to info@pingcap.com for inquiry.

**Comment by kennytm** [comment]
@ssnijik Yes. Specifically the output of [mydumper](https://github.com/maxbube/mydumper).

**Comment by ssnijik** [comment]
I think output format of mydumper is ok for me. When will lighting officially be released?

**Comment by kennytm** [comment]
@ssnijik We plan to release the first version by October. We'll post further info when it's ready 🙂.

**Comment by ssnijik** [comment]
Thanks. Looking forward to it. 🙂
