### ISSUE TITLE
checker of tidb

### ISSUE THREAD

**Issue by hlld3344** [pingcap/tidb#7664]
## Question

I've read the doc of data transfer from mysql to tidb and come across this :

./bin/checker -host 127.0.0.1 -port 3306 -user root test t_error
2016/10/27 13:19:28 checker.go:48: [info] Checking database test
2016/10/27 13:19:28 main.go:37: [info] Database DSN: root:@tcp(127.0.0.1:3306)/test?charset=utf8
2016/10/27 13:19:28 checker.go:63: [info] Checking table t_error
2016/10/27 13:19:28 checker.go:67: [error] Check table t_error failed with err: line 1 column 56 near ") ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=latin1"
github.com/pingcap/tidb/parser/yy_parser.go:111:
github.com/pingcap/tidb/parser/yy_parser.go:124:
/home/jenkins/workspace/WORKFLOW_TOOLS_BUILDING/go/src/github.com/pingcap/tidb-tools/checker/checker.go:122:  parse **CREATE TABLE `t_error` (
  `c` timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
) ENGINE=InnoDB DEFAULT CHARSET=latin1** error
/home/jenkins/workspace/WORKFLOW_TOOLS_BUILDING/go/src/github.com/pingcap/tidb-tools/checker/checker.go:114:
2016/10/27 13:19:28 main.go:68: [error] Check database test with 1 errors and 0 warnings.

Since mysql in our production env all has a date_updated column which has the attribute (ON UPDATE CURRENT_TIMESTAMP), I'm wondering if the new verion of tidb solve the issue?

thanks very much~

**Comment by crazycs520** [comment]
Hi @hlld3344 , Thanks for your feedback.
We have solved the issue. You can have a try in version  `v2.1.0-rc.1`

**Comment by hlld3344** [comment]
Hi @crazycs520 thank you very much

**Comment by hlld3344** [comment]
@crazycs520 another question~ when will your tidb version of v2.1.0-rc.1 release?
