### ISSUE TITLE
PD rebalance is right？

### ISSUE THREAD

**Issue by ljhmily** [pingcap/tidb#7668]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
structure：5 tikv，2tidb，3pd
first，drop table a（800w+）
then，rebuild a，and insert data with java program
while insert datas，we execute SQL，too slow（800 col，use more than 45s）
SELECT
t.lookup_type lookupType,
t.lookup_code lookupCode,
t.meaning,
t.description,
t.lookup_tag lookupTag
FROM
amp_lookup_value t
WHERE
t.lookup_type = 'MON_PERIOD'
AND t.enable_flag = 'Y'
at the backend，5 tikv，the two CPU is full，the three is normal

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
2.1-rc1

**Comment by crazycs520** [comment]
Hi, @ljhmily Thanks for your feedback.
Could you describe in more detail？ Such as table schema, specific version of TiDB.
"while insert datas，we execute SQL，too slow（800 col，use more than 45s" ?  800 col ?

**Comment by zz-jason** [comment]
I'm going to close this since it's a long time without any response. feel free to reopen it if you met the same issue again.
