### ISSUE TITLE
Decode row lazily

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#767]
Currently, we always decode the whole row even we just want one column. Also decode to  slice of interface{} is extremely slow. We should decode it lazily(when we actually use it).

**Comment by coocood** [comment]
I rethinked about the problem, all the column values has to be decoded in order to return to client.

So I figured out a better solution.

We define a struct like this:
```
type Value struct {
	IntVal int64
	StrVal []byte
	Val interface{}
}
```

Since most of the value type is `Int64` and `[]byte` (we also use []byte for string type), in most of the case, we don't need to wrap a value into an interface{}.

A row is of type `[]Value`.

I did a benchmark.

```

func BenchmarkValue(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ss := make([]Value, 10)
		for j := 0; j<10; j++ {
			ss[j].IntVal = int64(j)
		}
	}
}

func BenchmarkInterface(b *testing.B) {
	for i := 0; i < b.N; i++ {
		ss := make([]interface{}, 10)
		for j := 0; j<10; j++ {
			ss[j] = j
		}
	}
}
```

result:
```
BenchmarkValue-4	50000000	        26.7 ns/op
BenchmarkInterface-4      	 3000000	       410 ns/op
```

But this way require we know the number of columns for the row, if we append a new value, it costs much more, around ` 150 ns/op`

**Comment by disksing** [comment]
In fact, we can go further by defining a struct like
```
type Value struct {
    tag byte
    Int *int64
    Bytes []byte
    Time *mysql.Time
    ...
}
```
Then we can avoid using `interface{}` completely.

BTW, for now column values are stored separately. So I suppose the problem should be 'loading all columns' rather than 'decoding all columns'.

**Comment by coocood** [comment]
@disksing We don't need to make Int a pointer, the tag can indicate if it is nil.

**Comment by siddontang** [comment]
A benchmark here : http://play.golang.org/p/hSHfqaweat

Using pointer is much faster than origin int when appending in []interface{}.
I prefer using an interface Datum to mange and handle all data types. 

I knew that @shenli want to support it in DataItem before, but this needs changing too many places now.

**Comment by coocood** [comment]
another approach
```
const (
	TpInt64 int = iota + 1
	TpString
)

type Datum struct {
	tp   int
	ptr  unsafe.Pointer
}

func (d *Datum) Type() {
	return d.tp
}

func (d *Datum) GetInt64() int64 {
	return *(*int64)(d.ptr)
}

func (d *Datum) SetInt64(i int64) {
	d.tp = TpInt64
	d.ptr = unsafe.Pointer(&i)
}

func (d *Datum) SetString(s string) {
	d.tp = TpString
	d.ptr = unsafe.Pointer(&s)
}

func (d *Datum) GetString() string {
	return *(*string)(d.ptr)
}
```

**Comment by coocood** [comment]
A refined multi-field approach:

http://play.golang.org/p/VqfGh4sIF4

I prefer to use a concrete type and use it as value instead of pointer.

Address a  value to a pointer will cause memory allocation.

**Comment by coocood** [comment]
Datum is added to solve this problem.
