### ISSUE TITLE
How to remove Offline store? 

### ISSUE THREAD

**Issue by siuu** [pingcap/tidb#7677]
I have a TIKV node that has expired. I tried to delete this node using `pd-ctl store delete`, but it is always in the Offline state.

**Comment by ciscoxll** [comment]
@siuu Thanks for your feedback.

**Comment by ciscoxll** [comment]
@siuu TIKV node that has expired？please refer to [docs.](https://pingcap.com/docs-cn/op-guide/horizontal-scale/#%E5%8A%A8%E6%80%81%E5%88%A0%E9%99%A4%E8%8A%82%E7%82%B9)

**Comment by siuu** [comment]
I have deleted the store according to the docs, but he has been in the Offline state and has not become a tombstone. Other TiKV nodes always output an error log requesting the failure of this node.

**Comment by siuu** [comment]
```
    {
      "store": {
        "id": 134012,
        "address": "172.31.10.142:20172",
        "state": 1,
        "labels": [
          {
            "key": "host",
            "value": "tikv3"
          }
        ],
        "state_name": "Offline"
      },
      "status": {
        "leader_weight": 1,
        "region_weight": 1
      }
    }
```

**Comment by jackysp** [comment]
@LinuxGit ，please provide an official way to recover the cluster when it meets some fault operations.

**Comment by rleungx** [comment]
@siuu Hi, Could you provide more detailed information? 
e.g.
- Which version of PD and TiKV do you use?
- How do you set up the label?
- How long does this status last for?

**Comment by siuu** [comment]
- `tidb_version = v2.0.0`
-  inventory.ini
```
[tikv_servers]
TiKV1-1 ansible_host=172.31.10.139 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv1"
TiKV2-1 ansible_host=172.31.10.141 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv2"
#TiKV3-1 ansible_host=172.31.10.142 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv3"
#TiKV3-2 ansible_host=172.31.10.142 deploy_dir=/data2/deploy tikv_port=20172 labels="host=tikv3"
TiKV4-1 ansible_host=172.31.10.151 deploy_dir=/data1/deploy tikv_port=20171 labels="host=tikv4"
```

- This state lasted for one day.

**Comment by rleungx** [comment]
@siuu Can you provide the error log and all regions' info by using `region` command in `pd-ctl`?

**Comment by siuu** [comment]
this is tikv error log.

`2018/09/13 14:17:02.093 subchannel.c:687: [INFO] Connect failed: {"created":"@1536819422.093243717","description":"Failed to connect to remote host: OS Error","errno":111,"file":"/home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.1/grpc/src/core/lib/iomgr/tcp_client_posix.c","file_line":201,"os_error":"Connection refused","syscall":"connect","target_address":"ipv4:172.31.10.142:20171"}`

**Comment by rleungx** [comment]
@siuu The reason why the state of this store cannot become tombstone is there are still some regions leaving on this store which are supposed to be removed. Please make sure that you remove the store through these steps:
-  run `store delete <store_id>` in `pd-ctl`
-  wait for this store to become tombstone
-  run `ansible-playbook stop.yml -l <alias_name_of_the_store>`
-  comment this store in `inventory.ini`

Furthermore, could you tell me more about your operations? It confuses me that it seems you delete one store and comment two stores in `inventory.ini` without waiting for it to become tombstone. 
Please also make sure that you have enough space on other stores to make replicas, otherwise it won't become tombstone.
If all above is in the right way, we might need the regions' info to figure out which region leaves and why it can't be removed.

**Comment by siuu** [comment]
I have done a wrong operation before. i didn't wait for store to become tombstone. I stop node and rm db file.

**Comment by rleungx** [comment]
Here is the [documentation](https://pingcap.com/docs/op-guide/ansible-deployment-scale/) about how to scale the cluster using `Ansible`.

**Comment by siuu** [comment]
but now I can't remove the Offline node? I don't care about the region above.

**Comment by siuu** [comment]
I solved it by using `tikv-ctl unsafe-recover remove-fail-stores`. Thanks for your help.

**Comment by truong-hua** [comment]
I tried `pd-ctl unsafe remove-failed-stores store-id` according to https://docs.pingcap.com/tidb/dev/online-unsafe-recovery and `pd-ctl unsafe remove-failed-stores show` report that `"Last recovery has finished."` but that store is still in `Offline` status. So how can I enforce it to `Tombstone` in order to remove it and rejoin it to the cluster as a new node?

These are my cluster information

```
/ # /pd-ctl -V
Release Version: v5.3.1
Edition: Community
Git Commit Hash: b99630de0a59a14f1a6a00d99fd2e49016ab9aa1
Git Branch: heads/refs/tags/v5.3.1
UTC Build Time:  2022-02-23 05:17:56
```

```
/ # /tikv-ctl -V
TiKV Control (tikv-ctl)
Release Version:   5.3.1
Edition:           Community
Git Commit Hash:   ecc2549ed63fc21f1f6e11f1b85f19c2465234a5
Git Commit Branch: heads/refs/tags/v5.3.1
UTC Build Time:    2022-03-03 10:10:50
Rust Version:      rustc 1.56.0-nightly (2faabf579 2021-07-27)
Enable Features:   jemalloc mem-profiling portable sse protobuf-codec test-engines-rocksdb cloud-aws cloud-gcp
Profile:           dist_release
```

**Comment by truong-hua** [comment]
@rleungx can you help to reopen this issue?

**Comment by Connor1996** [comment]
@truong-hua You're referring to the wrong version of doc, should check the doc of v5.3 https://docs.pingcap.com/tidb/v5.3/online-unsafe-recovery. Online recovery is not GA in that version, and behavior changes a lot after that. In v5.3, it doesn't tombstone the store. 

BTW, it's not recommended to use it in v5.3, please try it in v6.1.

**Comment by truong-hua** [comment]
Thank Connor for that. But if it does not tombstone the store, do you know
how to completely remove that store from the list? I would like to add it
back to the cluster after hardware recovered.

**Comment by Connor1996** [comment]
It needs waiting for the scheduler to remove the peer of the store, after all have done, it would be in tombstone state. There is no way to set the tombstone state directly.

**Comment by truong-hua** [comment]
@Connor1996 , so is there any way to remove an Offline store in 5.3? My Offline store is crashed and there is no way to recover the data.

This is output of `/pd-ctrl store`

```
{
      "store": {
        "id": 1696001,
        "address": "tikv.s1.docker.youthdev.net:20160",
        "state": 1,
        "version": "5.3.1",
        "status_address": "0.0.0.0:20180",
        "git_hash": "ecc2549ed63fc21f1f6e11f1b85f19c2465234a5",
        "start_timestamp": 1656705754,
        "deploy_path": "/",
        "last_heartbeat": 1656948902731951081,
        "state_name": "Offline"
      },
      "status": {
        "capacity": "0B",
        "available": "0B",
        "used_size": "0B",
        "leader_count": 0,
        "leader_weight": 1,
        "leader_score": 0,
        "leader_size": 0,
        "region_count": 5,
        "region_weight": 1,
        "region_score": 87,
        "region_size": 87,
        "slow_score": 0,
        "start_ts": "2022-07-01T20:02:34Z",
        "last_heartbeat_ts": "2022-07-04T15:35:02.731951081Z",
        "uptime": "67h32m28.731951081s"
      }
    }
```

In PD dashboard, that store is stuck with Leaving state.
