### ISSUE TITLE
unknown error Mvcc(Engine(Request(message: "key is not in region"

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7683]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

`update f_entrust set fstatus=4 where fstatus in (1,2);`

2. What did you expect to see?

3. What did you see instead?

`ERROR 1105 (HY000): other error: unknown error Mvcc(Engine(Request(message: "key is not in region" key_not_in_region {key: "t\200\000\000\000\000\000\001\377A_i\200\000\000\000\000\377\000\000\002\003\200\000\000\000\377\000\000\000\002\000\000\000\000\373" region_id: 3192 start_key: "t\200\000\000\000\000\000\001\377A\000\000\000\000\000\000\000\370" end_key: "t\200\000\000\000\000\000\001\377A_i\200\000\000\000\000\377\000\000\002\003\200\000\000\000\377\000\000\000\001\003\200\000\000\377\001M\343^k\000\000\000\374"})))`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidb_version(): Release Version: v2.1.0-rc.1-7-g38c939f
Git Commit Hash: 38c939f4f95c802d85a5b6fd098a7a33daf0937f
Git Branch: master
UTC Build Time: 2018-08-27 01:53:09
GoVersion: go version go1.10.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

below is explain message:
 
![image](https://user-images.githubusercontent.com/13601367/45464368-e6a38200-b742-11e8-831f-0fe0eade5fb7.png)

**Comment by jackysp** [comment]
@gutongjiang , thanks for your feedback! I think it a known bug which already fixed in TiKV. PTAL @Connor1996 , please confirm if it is the fixed bug.

**Comment by ciscoxll** [comment]
@gutongjiang Thanks for your feedback, please provide `schema` information.

**Comment by gutongjiang** [comment]
mysql> SELECT * FROM information_schema.tables WHERE table_name='f_entrust'\G
*************************** 1. row ***************************
  TABLE_CATALOG: def
   TABLE_SCHEMA: bae_coin
     TABLE_NAME: f_entrust
     TABLE_TYPE: BASE TABLE
         ENGINE: InnoDB
        VERSION: 10
     ROW_FORMAT: Compact
     TABLE_ROWS: 2306
 AVG_ROW_LENGTH: 0
    DATA_LENGTH: 16384
MAX_DATA_LENGTH: 0
   INDEX_LENGTH: 0
      DATA_FREE: 0
 AUTO_INCREMENT: 9440633640
    CREATE_TIME: 2018-09-07 18:12:11
    UPDATE_TIME: NULL
     CHECK_TIME: NULL
TABLE_COLLATION: utf8_bin
      CHECK_SUM: NULL
 CREATE_OPTIONS: 
  TABLE_COMMENT: 用戶委單列表
1 row in set (0.01 sec)

**Comment by Connor1996** [comment]
What version of TiKV are you using (tikv-server --version)?

**Comment by gutongjiang** [comment]
@Connor1996 
`./tikv-server --version
TiKV 
Release Version:   2.1.0-rc.1
Git Commit Hash:   18f10b0f1968c442b8d5e807e0f81871e189e1af
Git Commit Branch: master
UTC Build Time:    2018-08-27 10:19:16
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)`

**Comment by Connor1996** [comment]
@gutongjiang This is a known issue already fixed in TiKV master, you can upgrade TiKV to latest master to fix this. Also you can also wait until later tomorrow when we will release 2.1.0-rc.2.

**Comment by gutongjiang** [comment]
@Connor1996  I am using TiDB-Ansible to deploy the cluster, how to upgrade tikv separately

**Comment by Connor1996** [comment]
1. complie new tikv binary
2. copy`tikv-server` to tidb-ansible-dir/resources/bin/
3. run `ansible-playbook rolling_update.yml --tags=tikv` in tidb-ansible-dir

**Comment by 474420502** [comment]
I also have this problem!

**Comment by shenli** [comment]
@474420502 Yes
Please use the latest master.

**Comment by kolbe** [comment]
@474420502 it sounds like this issue was resolved by upgrading to a newer release of TiKV, so I'm going to close this issue now.
