### ISSUE TITLE
TiDB mem heap is over 1GiB

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#7686]
We have an instance setup as slave of mysql via syncer, currently a lot of mem heap alert fired like this. After checking tidb logs and monitors, can't find anything obviously.

```
description:instance: 379433a4a318_4000 values: 2.865184768e+09
summary:TiDB mem heap is over 1GiB

```

* What we should do when got this alert?
* What does instance 379433a4a318_4000 stand for and where is the value from?
* Why it's 1GB? how to adjust from different environment?
* Where is the source code to learn this part?

Thank you very much!

**Comment by ciscoxll** [comment]
@CrazyNash Thanks for your feedback. 
`What does instance 379433a4a318_4000 stand for and where is the value from?`
Instance is the hostname and values is the current memory footprint.

**Comment by ciscoxll** [comment]
`Why it's 1GB? how to adjust from different environment?`[ reference link](https://github.com/pingcap/tidb-ansible/blob/master/roles/prometheus/files/tidb.rules.yml#L64)

**Comment by LinuxGit** [comment]
Hi, default value of TiDB_memory_abnormal alert rule is 10 GB now, it is suitable for OLTP scenarios.
If you have a lot of OLAP quries, you can modify its's value according to your situation.
see https://github.com/pingcap/tidb-ansible/blob/master/roles/prometheus/files/tidb.rules.yml#L64
After you modified the value, you can run `ansible-playbook rolling_update_monitor.yml --tags=prometheus` to make it work.

**Comment by CrazyNash** [comment]
Thank you all for your kind support @jackysp @ciscoxll 

One last question where is the source code from tidb to collect mem heap?

**Comment by CrazyNash** [comment]
@shenli thank you!
