### ISSUE TITLE
drainer error

### ISSUE THREAD

**Issue by sakufo** [pingcap/tidb#7699]
启动drainer提示以下错误，请问如何解决。
2018/09/14 14:25:05 offset_seeker.go:82: [info] kafka consumer version 0.8.2.0
2018/09/14 14:25:05 client.go:115: [sarama] Initializing new client
2018/09/14 14:25:05 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:05 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:05 client.go:646: [sarama] client/metadata fetching metadata for all topics from broker 10.10.10.8:9092
2018/09/14 14:25:05 broker.go:146: [sarama] Connected to broker at 10.10.10.8:9092 (unregistered)
2018/09/14 14:25:05 client.go:429: [sarama] client/brokers registered new broker #2 at 10.10.10.8:9092
2018/09/14 14:25:05 client.go:429: [sarama] client/brokers registered new broker #1 at 10.10.10.3:9092
2018/09/14 14:25:05 client.go:429: [sarama] client/brokers registered new broker #0 at 10.10.10.11:9092
2018/09/14 14:25:05 client.go:161: [sarama] Successfully initialized new client
2018/09/14 14:25:05 client.go:115: [sarama] Initializing new client
2018/09/14 14:25:05 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:05 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:05 client.go:646: [sarama] client/metadata fetching metadata for all topics from broker 10.10.10.8:9092
2018/09/14 14:25:05 broker.go:146: [sarama] Connected to broker at 10.10.10.8:9092 (unregistered)
2018/09/14 14:25:05 client.go:429: [sarama] client/brokers registered new broker #2 at 10.10.10.8:9092
2018/09/14 14:25:05 client.go:429: [sarama] client/brokers registered new broker #1 at 10.10.10.3:9092
2018/09/14 14:25:05 client.go:429: [sarama] client/brokers registered new broker #0 at 10.10.10.11:9092
2018/09/14 14:25:05 client.go:161: [sarama] Successfully initialized new client
2018/09/14 14:25:05 syncer.go:115: [info] [prepare] begin to construct schema infomation in syncer
2018/09/14 14:25:15 collector.go:365: [info] commit ts 0's safe commit ts is 0
2018/09/14 14:25:15 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:15 broker.go:144: [sarama] Connected to broker at 10.10.10.11:9092 (registered as #0)
2018/09/14 14:25:15 offset.go:115: [info] seek position 0 in topic 6600878647361733047_tp_8250 partition 0, oldest offset 0, newest offset 908
2018/09/14 14:25:15 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:15 broker.go:144: [sarama] Connected to broker at 10.10.10.11:9092 (registered as #0)
2018/09/14 14:25:15 consumer.go:738: [sarama] consumer/broker/0 added subscription to 6600878647361733047_tp_8250/0
2018/09/14 14:25:15 consumer.go:721: [sarama] consumer/broker/0 disconnecting due to error processing FetchRequest: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876
2018/09/14 14:25:15 broker.go:189: [sarama] Closed connection to broker 10.10.10.11:9092
2018/09/14 14:25:15 consumer.go:330: [sarama] kafka: error while consuming 6600878647361733047_tp_8250/0: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876
2018/09/14 14:25:17 consumer.go:345: [sarama] consumer/6600878647361733047_tp_8250/0 finding new broker
2018/09/14 14:25:17 client.go:644: [sarama] client/metadata fetching metadata for [6600878647361733047_tp_8250] from broker 10.10.10.8:9092
2018/09/14 14:25:17 config.go:351: [sarama] ClientID is the default of 'sarama', you should consider setting it to something application-specific.
2018/09/14 14:25:17 consumer.go:738: [sarama] consumer/broker/0 added subscription to 6600878647361733047_tp_8250/0
2018/09/14 14:25:17 broker.go:144: [sarama] Connected to broker at 10.10.10.11:9092 (registered as #0)
2018/09/14 14:25:17 consumer.go:721: [sarama] consumer/broker/0 disconnecting due to error processing FetchRequest: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876
2018/09/14 14:25:17 broker.go:189: [sarama] Closed connection to broker 10.10.10.11:9092
2018/09/14 14:25:17 consumer.go:330: [sarama] kafka: error while consuming 6600878647361733047_tp_8250/0: kafka: error decoding packet: CRC didn't match expected 0x0 got 0xe38a6876

**Comment by july2993** [comment]
look like you are using kafka 2.0?, drainer don't  support 2.0 now,  you can use version 1.*, we may update to support 2.0 later

**Comment by kolbe** [comment]
@july2993 is support for only Kafka 1.* still an issue in TiDB-Binlog?

**Comment by kolbe** [comment]
I'm told that the Kafka drainer *does* now support Kafka 2.0, so I'm going to close this issue now. If you encounter additional problems, please open a new issue!
