### ISSUE TITLE
Question: why is tidb-server  NOT full load  running `tidb-bench`

### ISSUE THREAD

**Issue by ideascf** [pingcap/tidb#7702]
## Question
The tidb-server can't be full load, when running tidb-bench. 
[![image](https://user-images.githubusercontent.com/5330706/45537636-5f840600-b837-11e8-9bdf-fa3db290a24b.png)
]

## Details
- version
  - TiDB: 2.0.7
  - sysbench: 1.0.9
  - OS: all is `CentOS Linux release 7.5.1804 (Core)`
- The TiDB cluster was installed follow (ansible-deployment)[https://pingcap.com/docs-cn/op-guide/ansible-deployment] 
- We have 4 server, all is AWS-EC2 instance, and instance type is `m5d.2xlarge` which have 8 vcpu,  32 GiB mem, one 300Gib NVMe SSD.
- The tikv-server was deployed with three instance on three different server,  and the PD/tidb-server was deployed on another server.
- The part of tidb-bench conf.sh.
```sh
tcount=16
tsize=1000000
threads=256
dbname=sbtest1

# report interval
interval=10

# max time in seconds
maxtime=600

# just large enough to fit maxtime
requests=2000000000

driver=mysql
```

- follow this situation, benchmark result is:  insert speed of TiDB is  10 times lower than mysql.  

So, why is so slow?   thank you for your help.

**Comment by shenli** [comment]
@ideascf We have a benchmark report [here](https://github.com/pingcap/docs/blob/master/benchmark/sysbench.md). Could you follow the steps?

**Comment by shenli** [comment]
Can we access your Grafana? I need to check the metrics system to see what is happening.

**Comment by ideascf** [comment]
sure, I send a email to your Gmail. pls  check soon.

**Comment by shenli** [comment]
From the metrics, I found that the sysbench concurrency is 1?

**Comment by ideascf** [comment]
How to change the concurrency of sysbench?  I use the default value on conf.sh which is 256. The screenshot is:


原始邮件
发件人:Shen Linotifications@github.com
收件人:pingcap/tidbtidb@noreply.github.com
抄送:ideascfchenfei@qfpay.com; Mentionmention@noreply.github.com
发送时间:2018年9月14日(周五) 18:10
主题:Re: [pingcap/tidb] Question: why is tidb-server NOT full load running `tidb-bench` (#7702)


From the metrics, I found that the sysbench concurrency is 1?

**Comment by ideascf** [comment]
Sorry, it's my problem.

Thank you for your the best support.

**Comment by zhexuany** [comment]
Closing issue since the problem has been resolved.
