### ISSUE TITLE
Does TiDB support delayed replication like MySQL?

### ISSUE THREAD

**Issue by sakufo** [pingcap/tidb#7703]
如题，谢谢。

**Comment by sakufo** [comment]
补充：Drainer 该工具是否支持延迟输出，或者有没有其它工具可以实现类似的功能

**Comment by jackysp** [comment]
Thank you for your attaction, @sakufo ! Please do not delete the issue template when you create an issue. PTAL @GregoryIan @csuzhangxc ！

**Comment by july2993** [comment]
@sakufo  
drainer don't supports delayed replication
