### ISSUE TITLE
Show TiDB region information via information_schema

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#7714]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The tidb fork of mydumper currently uses the following query to see if a _tidb_rowid exists for a table:
```
SELECT _tidb_rowid FROM db.table LIMIT 0;
```
Source: https://github.com/pingcap/mydumper/blob/master/mydumper.c#L2765-L2766

This works fine, but it produces an error on tables that don't have this column.  It would be nice if there were a standard metadata way to collect the pseudo primary key column in a format designed for logical dumpers.

**Describe the feature you'd like:**

Here is the ultimate format imho (since it can be easily chunk-split dumped in parallel):
```
CREATE TABLE TIDB_TABLE_PRIMARY_KEY (
 TABLE_CATALOG varchar(255),
 TABLE_SCHEMA varchar(64),
 TABLE_NAME varchar(64),
 TABLE_PRIMARY_KEY varchar(64),
 TABLE_START_VALUE BIGINT,
 TABLE_END_VALUE BIGINT
);
```
It can also be joined on `tables` to get `avg_row_length` and `data_length`.

**Describe alternatives you've considered:**

The current solution technically works.  TiDB just has a strong technical advantage for logical dumpers since every table (a) has primary key and (b) the primary key can easily be divided into ranges.

An alternative/feature extension would to give a logical view of all data regions for a table in `information_schema` instead.

**Teachability, Documentation, Adoption, Migration Strategy:**

Adoption will mostly be for automated tools.

**Comment by shenli** [comment]
@morgo All tables in TiDB would have a `_tidb_rowid`.  For the requirement:

> the primary key can easily be divided into ranges

We should find a way to get the physical distribution of the data.

**Comment by morgo** [comment]
@shenli Sounds good!  A quick update: I wrote an [example dumper](https://github.com/morgo/tidump) as a weekend project (not a go programmer sorry!).

It is a lot simpler than mydumper because relative to MySQL, TiDB has a reliable/fast implementation of `information_schema`.  I can get almost everything I need from the server in one query:

```
SELECT
 t.table_schema,
 t.table_name,
 if(AVG_ROW_LENGTH=0,100,AVG_ROW_LENGTH) as avg_row_length,
 t.data_length,
 IFNULL(pk.likely_primary_key,'_tidb_rowid'),
 c.insertable
FROM
 INFORMATION_SCHEMA.TABLES t
LEFT JOIN 
 (SELECT table_schema, table_name, column_name as likely_primary_key FROM information_schema.key_column_usage WHERE constraint_name='PRIMARY') pk
 ON t.table_schema = pk.table_schema AND t.table_name=pk.table_name
LEFT JOIN 
 (SELECT table_schema, table_name, GROUP_CONCAT(COLUMN_NAME)as insertable FROM information_schema.COLUMNS WHERE extra NOT LIKE '%%GENERATED%%' GROUP BY table_schema, table_name) c
 ON t.table_schema = c.table_schema AND t.table_name=c.table_name
WHERE
 t.TABLE_SCHEMA NOT IN ('mysql', 'INFORMATION_SCHEMA', 'PERFORMANCE_SCHEMA')
```

There are only two things missing here:
* A check to see if `_tidb_rowid` exists.
* The min/max values for the primary key

If the server exposed region ranges, I could also use those instead of dividing the key into ranges myself.  I assume a lighting-type loader would like this.

**Comment by shenli** [comment]
This could not guarantee to split data into equal size ranges. RowID is the logical space. Consider the following scenarios:
* a successive range is deleted
* the primary-key is integer (its value is used as the RowID) and  user could assign whatever they want to its value

The better way is using PD's routing info to split the ranges. @winkyao has a lot of insight about this.

**Comment by morgo** [comment]
Makes sense.  I edited my previous comment to also say `SHOW CREATE TABLE` for each table is missing.  If Information_schema exposed that, a logical dumper could cut down on queries.

**Comment by nullnotnil** [comment]
This has been added. 

See: https://docs.pingcap.com/tidb/stable/sql-statement-show-table-regions (show statement version) and https://docs.pingcap.com/tidb/stable/information-schema-tikv-region-status (information schema version)

I am going to close this issue now. Thanks!
