### ISSUE TITLE
Do it support that create index to a virtual column?

### ISSUE THREAD

**Issue by deepeye** [pingcap/tidb#7734]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
CREATE TABLE `push_data` (
	`rowId` VARCHAR(100) NOT NULL,
  	`pubSource` VARCHAR(50) NULL DEFAULT NULL,
	`crc32PubSource` BIGINT(20) AS (crc32(`pubsource`)) VIRTUAL,
	PRIMARY KEY (`rowId`),
	INDEX `crc32PubSource_idx` (`crc32PubSource`)
)
COLLATE='utf8_bin'
ENGINE=InnoDB

MySQL [test]> explain select pubsource, crc32PubSource from push_data where crc32PubSource=1254490381 limit 10 
    -> ;
+--------------------------+-------+------+--------------------------------------------------------------------+
| id                       | count | task | operator info                                                      |
+--------------------------+-------+------+--------------------------------------------------------------------+
| Projection_10            | 10.00 | root | test.push_data.pubsource, cast(crc32(test.push_data.pubsource))    |
| └─Limit_13               | 10.00 | root | offset:0, count:10                                                 |
|   └─Selection_14         | 10.00 | root | eq(cast(crc32(test.push_data.pubsource)), 1254490381)              |
|     └─TableReader_16     | 10.00 | root | data:TableScan_15                                                  |
|       └─TableScan_15     | 10.00 | cop  | table:push_data, range:[-inf,+inf], keep order:false, stats:pseudo |
+--------------------------+-------+------+--------------------------------------------------------------------+
5 rows in set (0.00 sec)

2. What did you expect to see?
I have found TableScan，not IndexScan。Don't tidb support add index to a virtual column?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Server version: 5.7.10-TiDB-v2.1.0-rc.1-39-g1f2841f

**Comment by jackysp** [comment]
Thanks for your attention! It is not supported yet.

**Comment by deepeye** [comment]
Thanks！Will we plan to support that in the future？

**Comment by jackysp** [comment]
It's already in our todo list.

**Comment by morgo** [comment]
This is now supported in TiDB:
```
mysql> CREATE TABLE push_data (
    -> rowId VARCHAR(100) NOT NULL,
    -> pubSource VARCHAR(50) NULL DEFAULT NULL,
    -> crc32PubSource BIGINT(20) AS (crc32(pubsource)) VIRTUAL,
    -> PRIMARY KEY (rowId),
    -> INDEX crc32PubSource_idx (crc32PubSource)
    -> );
Query OK, 0 rows affected (0.01 sec)

mysql> SHOW CREATE TABLE push_data\G
*************************** 1. row ***************************
       Table: push_data
Create Table: CREATE TABLE `push_data` (
  `rowId` varchar(100) NOT NULL,
  `pubSource` varchar(50) DEFAULT NULL,
  `crc32PubSource` bigint(20) GENERATED ALWAYS AS (crc32(`pubsource`)) VIRTUAL,
  PRIMARY KEY (`rowId`),
  KEY `crc32PubSource_idx` (`crc32PubSource`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to re-open it if you have any further questions.  Thanks!
