### ISSUE TITLE
tikv's leader count! fail and retry

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#7743]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

ansible-playbook rolling_update.yml

TASK [check tikv's leader count] *****************************************************************************
FAILED - RETRYING: check tikv's leader count (18 retries left).
FAILED - RETRYING: check tikv's leader count (17 retries left).
FAILED - RETRYING: check tikv's leader count (16 retries left).
FAILED - RETRYING: check tikv's leader count (15 retries left).
FAILED - RETRYING: check tikv's leader count (14 retries left).
FAILED - RETRYING: check tikv's leader count (13 retries left).
FAILED - RETRYING: check tikv's leader count (12 retries left).
FAILED - RETRYING: check tikv's leader count (11 retries left).
FAILED - RETRYING: check tikv's leader count (10 retries left).
FAILED - RETRYING: check tikv's leader count (9 retries left).
FAILED - RETRYING: check tikv's leader count (8 retries left).
FAILED - RETRYING: check tikv's leader count (7 retries left).
FAILED - RETRYING: check tikv's leader count (6 retries left).
FAILED - RETRYING: check tikv's leader count (5 retries left).
FAILED - RETRYING: check tikv's leader count (4 retries left).
FAILED - RETRYING: check tikv's leader count (3 retries left).
FAILED - RETRYING: check tikv's leader count (2 retries left).
FAILED - RETRYING: check tikv's leader count (1 retries left).

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb-ansible 
commit f76d431d38740e60f63da594c50e1b505c5e53d7
tidb 2.1.0 rc2

**Comment by lysu** [comment]
Thanks for your report, @474420502 ！
PTAL @nolouch  .

**Comment by nolouch** [comment]
@474420502  when doing a rolling update, ansible will call API to evict the leader in the TiKV that being upgraded. If the leader is not evicted clean it will do retry. can you show how many leaders in that `tikv` when doing a rolling update?

**Comment by 474420502** [comment]
@nolouch  I will pay attention to the next update.

**Comment by meilihao** [comment]
me, too.

rolling update from 5.7.25-TiDB-v4.0.0-alpha-531-g46c3f1a91 to latest,today.

env:
pd:1
tidb:1
tikv:1
