### ISSUE TITLE
syncer doesn't work after restart

### ISSUE THREAD

**Issue by gutongjiang** [pingcap/tidb#7747]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

When I first run syncer, it's OK, the Insert records can be synchronized.
then I shutdown syncer and restart it, insert one record into mysql, the record didn't sync to TiDB

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by gutongjiang** [comment]
Waited a long time, the record sync

**Comment by lysu** [comment]
@gutongjiang Thanks for your report~

maybe we need more detail information, what about wait-sync data amout~? and is any tidb or syncer log question during unsync time?

@WangXiangUSTC maybe PTAL~

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
