### ISSUE TITLE
tikv not start

### ISSUE THREAD

**Issue by wsh-sun** [pingcap/tidb#7752]
tikv not start 

command：
docker run -d --name tikv \
  -p 20160:20160 \
  --ulimit nofile=1000000:1000000 \
  -v /etc/localtime:/etc/localtime:ro \
  -v /data:/data \
  pingcap/tikv:latest \
  --addr="0.0.0.0:20160" \
  --advertise-addr="127.0.0.1:20160" \
  --data-dir="/data/tikv" \
  --log-file="/data/tikv/tikv.log" \
  --pd="172.0.0.1:2379"

log:
2018/09/20 10:52:31.488 INFO config.rs:646: kernel parameters vm.swappiness: 0
2018/09/20 10:52:31.488 WARN tikv-server.rs:87: Limit("kernel parameters net.core.somaxconn got 128, expect 32768")
2018/09/20 10:52:31.488 WARN tikv-server.rs:87: Limit("check_kernel_params failed No such file or directory (os error 2)")
2018/09/20 10:52:31.488 INFO config.rs:824: data_path: "/data/tikv", mount fs info: FsInfo { tp: "xfs", opts: "rw,seclabel,relatime,attr2,inode64,noquota", mnt_dir: "/data", fsname: "/dev/mapper/localvg-data" }
2018/09/20 10:52:31.488 WARN tikv-server.rs:92: rockdsb check data dir: FileSystem("data-dir.rotation.get: \"/dev/mapper/localvg-data\" no device find in block")
2018/09/20 10:52:31.489 INFO config.rs:824: data_path: "/data/tikv/raft", mount fs info: FsInfo { tp: "xfs", opts: "rw,seclabel,relatime,attr2,inode64,noquota", mnt_dir: "/data", fsname: "/dev/mapper/localvg-data" }
2018/09/20 10:52:31.489 WARN tikv-server.rs:96: raft check data dir: FileSystem("data-dir.rotation.get: \"/dev/mapper/localvg-data\" no device find in block")
2018/09/20 10:52:31.491 INFO util.rs:406: connecting to PD endpoint: "172.0.0.1:2379"
2018/09/20 10:52:33.493 ERRO util.rs:366: PD endpoint 172.0.0.1:2379 failed to respond: Grpc(RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") }))
2018/09/20 10:52:33.493 ERRO tikv-server.rs:407: failed to create rpc client: Other(StringError("[src/pd/util.rs:397]: PD cluster failed to respond"))

pd ：
[root@aa ~]# nc -v -z 127.0.0.1 2379
Connection to 127.0.0.1 2379 port [tcp/*] succeeded!
[root@aa ~]# curl -v 127.0.0.1:2379/pd/api/v1/leader
* About to connect() to 127.0.0.1 port 2379 (#0)
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 2379 (#0)
> GET /pd/api/v1/leader HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 127.0.0.1:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: accept, content-type, authorization
< Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=UTF-8
< Date: Thu, 20 Sep 2018 03:00:06 GMT
< Content-Length: 161
< 
{
  "name": "pd",
  "member_id": 9850296721428341765,
  "peer_urls": [
    "http://172.17.45.241:2380"
  ],
  "client_urls": [
    "http://127.0.0.1:2379"
  ]
}
* Connection #0 to host 127.0.0.1 left intact

**Comment by lysu** [comment]
Thanks for your report, @wsh-sun ！
PTAL @nolouch.

**Comment by nolouch** [comment]
@wsh-sun  Are you sure the docker network can access to PD?

**Comment by nolouch** [comment]
@wsh-sun  you should create a bridge network and use it. https://docs.docker.com/network/bridge/
