### ISSUE TITLE
Tidb cluster deploy by container, causes machine to restart abnormally

### ISSUE THREAD

**Issue by barnettZQG** [pingcap/tidb#7754]
## Question
We recommend that users deploy the tidb cluster.
pd, kv and server are all three nodes.
However, the machine deploying tidb will be restarted irregularly, and it is not clear why.
Is it possible that tidb is too high on the disk read-write frequency to cause a hardware failure?

**Comment by lysu** [comment]
Hi @barnettZQG, Thanks for your report~ tidb-server node doesn't take heavy disk I/O(mainly some log) but it will frequency communicate with kv via network, then kv node will do disk I/O.

if irregular restart process is `tidb-server` node maybe we can:

1. check system monitor (load,cpu, io...) from your machine monitor to see any sth wrong happen (tidb's grafana also help)
2. check `last -x` result
3. check `/var/log` logfile detail before last restart, like: messages(or some system name: `syslog`), kern.log, user.log, debug...maybe found some useful info.

**Comment by barnettZQG** [comment]
![image](https://user-images.githubusercontent.com/18493394/46118982-94cb2380-c23b-11e8-9642-402ef7f08623.png)
We discovered the problem by getting the kernel crash logs.
rocksdb caused a kernel bug.

**Comment by barnettZQG** [comment]
The cause of the problem has been determined.  rocksdb maybe do not well support `nfs` storage.
