### ISSUE TITLE
Table 'INFORMATION_SCHEMA.COLLATIONS' doesn't exist

### ISSUE THREAD

**Issue by LincolnBruce** [pingcap/tidb#7763]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Table 'INFORMATION_SCHEMA.COLLATIONS' doesn't exist

2. What did you expect to see?

正常情况下应该不出现此类提示问题

3. What did you see instead?

正常情况下应该不出现此类提示问题

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

create table的时候字符集使用了utf8mb4;

**Comment by morgo** [comment]
(reading this via google translation) It is a known bug that the `collations` table in `information_schema` did not show all collations.  This was fixed recently in https://github.com/pingcap/tidb/pull/7647

**Comment by lysu** [comment]
Hello, @LincolnBruce where is exception occured? mysql cli? or jdbc? or other langauge sdk?

maybe you can use mysql cli to login tidb-server `mysql -P4000 -h127.0.0.1 -uyour_user -pyou_pwd information_schema;` and try 

```
select * from collations;
```
to check is any problem?

at last, please give us your tidb-version

```
4. What version of TiDB are you using (tidb-server -V or run select tidb_version(); on TiDB)?
```

**Comment by AndrewDi** [comment]
无法重现这个问题喔。
![image](https://user-images.githubusercontent.com/7589147/45928499-47b72b00-bf77-11e8-9953-b3234eff4aac.png)

**Comment by shenli** [comment]
@LincolnBruce For the blank name table, could you know the correct name for it? TiDB will print log for every DDL statement. You can grep its name in tidb-server's log.

**Comment by LincolnBruce** [comment]
Yeah may be a coding problem, but it appeared with issue #7763

**Comment by lysu** [comment]
> Hello, @LincolnBruce where is exception occured? mysql cli? or jdbc? or other langauge sdk?
> 
> maybe you can use mysql cli to login tidb-server `mysql -P4000 -h127.0.0.1 -uyour_user -pyou_pwd information_schema;` and try
> 
> ```
> select * from collations;
> ```
> to check is any problem?
> 
> at last, please give us your tidb-version
> 
> ```
> 4. What version of TiDB are you using (tidb-server -V or run select tidb_version(); on TiDB)?
> ```

@LincolnBruce please answer my question

**Comment by LincolnBruce** [comment]
```syslog
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| INFORMATION_SCHEMA |
| PERFORMANCE_SCHEMA |
| mysql              |
| test               |
| warehouse          |
+--------------------+
5 rows in set (0.00 sec)

mysql> use INFORMATION_SCHEMA
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+---------------------------------------+
| Tables_in_INFORMATION_SCHEMA          |
+---------------------------------------+
| CHARACTER_SETS                        |
| COLLATIONS                            |
| COLLATION_CHARACTER_SET_APPLICABILITY |
| COLUMNS                               |
| COLUMN_PRIVILEGES                     |
| ENGINES                               |
| EVENTS                                |
| FILES                                 |
| GLOBAL_STATUS                         |
| GLOBAL_VARIABLES                      |
| KEY_COLUMN_USAGE                      |
| OPTIMIZER_TRACE                       |
| PARAMETERS                            |
| PARTITIONS                            |
| PLUGINS                               |
| PROFILING                             |
| REFERENTIAL_CONSTRAINTS               |
| ROUTINES                              |
| SCHEMATA                              |
| SCHEMA_PRIVILEGES                     |
| SESSION_STATUS                        |
| SESSION_VARIABLES                     |
| STATISTICS                            |
| TABLES                                |
| TABLESPACES                           |
| TABLE_CONSTRAINTS                     |
| TABLE_PRIVILEGES                      |
| TRIGGERS                              |
| USER_PRIVILEGES                       |
| VIEWS                                 |
+---------------------------------------+
30 rows in set (0.00 sec)

mysql> select * from collations;
ERROR 1146 (42S02): Table 'INFORMATION_SCHEMA.collations' doesn't exist
```
tidb tikv version
![image](https://user-images.githubusercontent.com/7814560/46855065-4d48b800-ce35-11e8-8477-12cb8dc239d6.png)
![image](https://user-images.githubusercontent.com/7814560/46855105-60f41e80-ce35-11e8-815a-76c518f40588.png)

**Comment by lysu** [comment]
@LincolnBruce 

How about 

```
select * from INFORMATION_SCHEMA.COLLATIONS;
```
got~?

and maybe take a look

```
select @@lower_case_table_names;
```

result

**Comment by LincolnBruce** [comment]
![image](https://user-images.githubusercontent.com/7814560/46929074-570a2f80-d070-11e8-8b4f-2e0af8efd1b3.png)

**Comment by kolbe** [comment]
I've been unable to reproduce this using Sequel Pro 1.1.2 connected to TiDB Server v3.0.0-beta.1-255-g7deedf841. Maybe it's been fixed either in Sequel Pro or TiDB. @LincolnBruce can you please try again with the Windows release?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!

**Comment by SantoshkumarBiradar** [comment]
Hi, how we can check if a column exists on Table in MySQL without using Stored Procedure. MySQL v3.23 which won't support writing Store Procedure.
