### ISSUE TITLE
Table Name is Null...

### ISSUE THREAD

**Issue by LincolnBruce** [pingcap/tidb#7764]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

创建表的时候，偶然出现了一个表名为空的表

2. What did you expect to see?

表名为空不应该让其创建成功

3. What did you see instead?

表名为空不应该让其创建成功

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

create table 时字符集为utf8mb4

**Comment by lysu** [comment]
@LincolnBruce  Thanks for report~

I try it but couldn't reproduce that...

```sql
mysql> create table ` ` (id int, x int);
ERROR 1103 (42000): Incorrect table name ' '
mysql> create table `` (id int, x int);
ERROR 1103 (42000): Incorrect table name ''
mysql> create table  (id int, x int);
ERROR 1105 (HY000): line 1 column 15 near "id int, x int)" (total length 29)
```

should you give us the reproduce create table statement~ thx :cat: 

or maybe you can use a program to read table name and see which char "空" is?

**Comment by lysu** [comment]
and also we need tidb version info

```
4.What version of TiDB are you using (tidb-server -V or run select tidb_version(); on TiDB)?
```

**Comment by lysu** [comment]
@LincolnBruce table name check logic is https://github.com/pingcap/tidb/blob/267ccf54a08c8efbbab72ef500ec957688ef395e/plan/preprocess.go#L492

do you have interesting to fix that~? if you find the special char

**Comment by LincolnBruce** [comment]
this time... database name is nil......WTF
![image](https://user-images.githubusercontent.com/7814560/47759275-d1ca8000-dce9-11e8-815e-4d546950481c.png)

**Comment by LincolnBruce** [comment]
I used the docker version of the tidb-server. After I re-run the docker, everything is fine. I also helped the pingcap engineers find the bug.

**Comment by shenli** [comment]
@LincolnBruce Have you run any query before the db/table name change to an empty string?

**Comment by LincolnBruce** [comment]
SQL DDL

**Comment by zz-jason** [comment]
Hi @LincolnBruce, Is this still an issue? Or, have you found the reproduce steps?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to re-open if you can reproduce. Thanks!
