### ISSUE TITLE
tidb Support    Online DDL ?

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#7780]
alter table add column     ,tidb Support    Online DDL ?

**Comment by crazycs520** [comment]
Hi ~ @shenlijungg . 
Yes , TiDB support online DDL.

**Comment by zimulala** [comment]
@shenlijungg 
Specific support can refer to [doc](https://github.com/pingcap/docs/blob/master/sql/mysql-compatibility.md#ddl).
