### ISSUE TITLE
Precision of aggregation's result for exact value is wrong.

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#7781]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(a int, b int);
insert into t values(1, 0), (2, 1), (2, 2);
select avg(b) from t group by a;
```

2. What did you expect to see?
The result should be `0.0000` and `1.500`.

3. What did you see instead?
It's `0` and `1.500`.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master with commit f387dfff09068f1bde478a287897a03e0dabcf6f.

**Comment by wwar** [comment]
This has been fixed:
```
tidb> select avg(b) from t group by a;
+--------+
| avg(b) |
+--------+
| 1.5000 |
| 0.0000 |
+--------+
2 rows in set (0.00 sec)

tidb> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-183-g57db6cec7
Git Commit Hash: 57db6cec7ffad78e74b6ac6c67a2bfe9a6718d17
Git Branch: master
UTC Build Time: 2020-04-04 08:06:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```
