### ISSUE TITLE
store: make it easier to implement new storage engines for TiDB

### ISSUE THREAD

**Issue by disksing** [pingcap/tidb#782]
Currently, interfaces in kv and store package are too complicated and disordered. It is very hard to implement a new storage engine for TiDB.

I plan to make it easier with following steps:
1. Simplify local store and hbase store. Storages should implement as less interfaces as possible.
2. Refine interfaces. Distinguish interfaces that should be completed by storages from those are already complete in kv.
3. Write a guide document.

**Comment by nieyy** [comment]
sounds great, will keep watching your progress, :+1:
