### ISSUE TITLE
sqlParser issue not support some column type(such as 'point' and so on)

### ISSUE THREAD

**Issue by Johnson0125** [pingcap/tidb#7820]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

run tidb-server source code in my machine, i want get createTableStmt from DDL while
error log is

`panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1130be2]

goroutine 1 [running]:
github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*methodType).PC(0x0, 0x12dad84)
	/development/gowork/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/check.go:60 +0x22
github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*C).logCaller(0xc000176000, 0x3)
	/development/gowork/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/check.go:285 +0x98
github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*C).internalCheck(0xc000176000, 0x1391653, 0x6, 0x1347a40, 0xc000096f20, 0x13f3f80, 0x18689d8, 0x0, 0x0, 0x0, ...)
	/development/gowork/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/helpers.go:221 +0x2b0
github.com/pingcap/tidb/vendor/github.com/pingcap/check.(*C).Assert(0xc000176000, 0x1347a40, 0xc000096f20, 0x13f3f80, 0x18689d8, 0x0, 0x0, 0x0)
	/development/gowork/src/github.com/pingcap/tidb/vendor/github.com/pingcap/check/helpers.go:178 +0x99
main.TestDDLStatements(0xc000176000)
	/development/gowork/src/github.com/pingcap/tidb/test/main.go:67 +0x155
main.main()
	/development/gowork/src/github.com/pingcap/tidb/test/main.go:14 +0x3b`

**while
i use the code below to get the createTableStmt(which will show in json style)**

`func  TestDDLStatements(c *C) {
	parser := parser.New()
	// Tests that whatever the charset it is define, we always assign utf8 charset and utf8_bin collate.
	createTableStr :=  "create Table **"
	stmts, err := parser.Parse(createTableStr, "", "")
	c.Assert(err, IsNil)
	stmt := stmts[0].(*ast.CreateTableStmt)
	fmt.Println("json:", stmt.String())

}`

**ps: the column type form mariadb10.3, and sql runs well under mariadb**

`create table my_test (
a tinyint(2),
b smallint(2),
c mediumint(2),
d int(3),
e bigint(10),
f bit(12),

g float,
h double,
i decimal,
j char(10),
k varchar(10),
l tinytext,
m text,
n mediumtext,
o longtext,
p json,
q binary(200),
r varbinary(250),
s tinyblob,
t1 blob,
u mediumblob,
v longblob,
w date,
x1 time,
y1 year,
z datetime,
aa timestamp,
ab point,
ac linestring,
ad polygon,
ae geometry,
af multipoint,
ag multilinestring,
ah multipolygon,
ai geometrycollection

)`

2. What did you expect to see?
it can runs well, it can get the createTableStmt result correct

3. What did you see instead?
i found the column type below maybe is not support by sqlParse:
`ab point,
ac linestring,
ad polygon,
ae geometry,
af multipoint,
ag multilinestring,
ah multipolygon,
ai geometrycollection`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

i am running the current tibd source code ,  branch is master

**Comment by lamxTyler** [comment]
@Johnson0125 We do not support spatial type, you can take a look at [tidb data type](https://github.com/pingcap/docs/blob/master/sql/datatype.md#tidb-data-type)

**Comment by Johnson0125** [comment]
@lamxTyler Thanks to answer me, while 
i found this one
TypeGeometry   byte = 0xff
in mysql/type.go line 47, 
so i guess such type about geometry could runs well
but i did not found the geometry type under the link you given to me

**Comment by lamxTyler** [comment]
@Johnson0125 No, we do not support spatial type.

**Comment by Johnson0125** [comment]
@lamxTyler well i understand 3Q, other way what tidb suggest take the place of spatial type when we want to use such type.

**Comment by lamxTyler** [comment]
@Johnson0125 You can store it in other types like json, but all the operations have to be done by the applications.
