### ISSUE TITLE
DROP VIEW IF EXISTS causes server crash (breaking mydumper)

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#7833]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

myloader tries to drop a table as both a view and a table when restoring with the `-o` option (overwrite).  It crashes tidb, which I managed to reduce to this test case:

```
MySQL [test]> CREATE TABLE t1 (a int);
DRQuery OK, 0 rows affected (0.53 sec)

MySQL [test]> DROP VIEW IF EXISTS t1;
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

2. What did you expect to see?

Not crash.

3. What did you see instead?

See above.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
MySQL [test]> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-5-g99c4a15ce
Git Commit Hash: 99c4a15ce422603a6ad02be8ace19a43f8a26162
Git Branch: newmaster
UTC Build Time: 2018-10-07 04:24:32
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by shenli** [comment]
We will fix it soon.

**Comment by tianjiqx** [comment]
I found that this bug seems to be just a simple null pointer problem.Just modify one line to fix it.

<img width="381" alt="snipaste_2018-10-15_19-51-29" src="https://user-images.githubusercontent.com/7732802/46949503-2b109d80-d0b4-11e8-90c4-c674f17ed147.png">

**Comment by zz-jason** [comment]
@tianjiqx Good! Could you file a PR to fix this issue?

**Comment by tianjiqx** [comment]
@zz-jason    
I checked if I should use the `p.Schema()` function in other places instead of using `p.schema` directly?
Or if there are no bugs, it will not change other places. 
<img width="391" alt="snipaste_2018-10-15_20-17-18" src="https://user-images.githubusercontent.com/7732802/46950459-58127f80-d0b7-11e8-845c-5fcebed95d6c.png">

**Comment by tianjiqx** [comment]
@zz-jason 
That's right. Well, I need to continue to look at the relevant code logic.

**Comment by tianjiqx** [comment]
drop view statement as ast.DoStmt handled in buildDo,I think can set schema at here
```
--- a/planner/core/planbuilder.go
+++ b/planner/core/planbuilder.go
@@ -227,6 +227,8 @@ func (b *PlanBuilder) buildDo(v *ast.DoStmt) (Plan, error) {
                        RetType:  expr.GetType(),
                })
        }
+       //make dual schema if not
+       var _ = dual.Schema()
        p.SetChildren(dual)
        p.self = p
        p.SetSchema(schema)
```
BTW，The view function does not seem to be fully implemented yet? 
```
mysql> CREATE VIEW v AS SELECT qty, price, qty*price AS value FROM t;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE VIEW v AS SELECT qty, price, qty*price AS value FROM t;
Query OK, 0 rows affected (0.00 sec)

mysql> CREATE VIEW v AS SELECT qty, price, qty*price AS value FROM t;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from v;
ERROR 1146 (42S02): Table 'test.v' doesn't exist

mysql> drop view if exists v;
Query OK, 0 rows affected (0.00 sec)
```

**Comment by shenli** [comment]
@tianjiqx Actually, TiDB doesn't support View.
