### ISSUE TITLE
Some questions related to the SQL ->KV encoding & decoding

### ISSUE THREAD

**Issue by nieyy** [pingcap/tidb#784]
### HBase column families

```bash
hbase(main):051:0> desc 'testdb'
Table testdb is ENABLED                                                                                                                                              
testdb, {TABLE_ATTRIBUTES => {METADATA => {'__themis.returned.table.desc__' => 'true'}}                                                                              
COLUMN FAMILIES DESCRIPTION                                                                                                                                          
{NAME => '#d', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '2147483647', TTL => 'FOREVER', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}                                                    
{NAME => '#p', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '2147483647', TTL => 'FOREVER', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true'}                                                    
{NAME => 'L', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', COMPRESSION => 'NONE', VERSIONS => '1', TTL => 'FOREVER', MIN_VERSIONS => '0', KEEP_DELETED_CELLS => 'FALSE', BLOCKSIZE => '65536', IN_MEMORY => 'true', BLOCKCACHE => 'true'}                                                               
{NAME => 'f', DATA_BLOCK_ENCODING => 'NONE', BLOOMFILTER => 'ROW', REPLICATION_SCOPE => '0', VERSIONS => '2147483647', COMPRESSION => 'NONE', MIN_VERSIONS => '0', TTL => 'FOREVER', KEEP_DELETED_CELLS => 'false', BLOCKSIZE => '65536', IN_MEMORY => 'false', BLOCKCACHE => 'true', METADATA => {'THEMIS_ENABLE' => 'true'}}            
4 row(s) in 0.0270 seconds
```

From tidb/store/hbase/kv.go, I can see there has a CF named **'f'**, and that's the only place I can found in tidb's code, what are the other 3 CFs used for? ('#d', '#p', 'L'), maybe it's used for themis only?

### Do we have any document to describe how SQL mapping to KV work in details? Where is the code?

**Comment by shenli** [comment]
@nieyy Thanks for your report.
We are writing documents for Tidb. KV encoding/decoding is on the schedule. I think it won't be long.

**Comment by disksing** [comment]
Hi @nieyy ,
You are right about the 3 CFs. They are indeed created and used by Themis. Please refer https://github.com/XiaoMi/themis and https://github.com/pingcap/go-themis for more details.

**Comment by nieyy** [comment]
@shenli Glad to hear that.

Could you please tell me where is the code about the mapping/encoding/decoding, just show me the major related go files and methods first, thanks.

**Comment by nieyy** [comment]
@disksing , thanks for your answer.

**Comment by disksing** [comment]
Hi @nieyy ,
In brief, `util/codec` provides a series of functions that can encode values into mem-comparable `[]byte`. How structured data in RMDBS are transformed to key-value pairs are mainly in package `table/tables` and `kv`. You may trace function calls to `codec` functions to get the clue. : )

**Comment by nieyy** [comment]
@disksing thanks for your answer.
