### ISSUE TITLE
TiDB HTTP API supports cross-domain requests

### ISSUE THREAD

**Issue by xuechunL** [pingcap/tidb#7850]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB HTTP API requests from the front-end page (different origin) return rejected responses.

![image](https://user-images.githubusercontent.com/11324004/46651597-2723dd80-cbd3-11e8-8515-af9514d97308.png)

**Describe the feature you'd like:**

Is it possible to set the HTTP Response Header like this?

![image](https://user-images.githubusercontent.com/11324004/46651697-6b16e280-cbd3-11e8-9c74-b1ff1f1f9003.png)

**Comment by xuechunL** [comment]
PTAL @winkyao @lamxTyler

**Comment by Apollo1993** [comment]
#7850

**Comment by lamxTyler** [comment]
Fixed by https://github.com/pingcap/tidb/pull/7939
