### ISSUE TITLE
tidb update error

### ISSUE THREAD

**Issue by sakufo** [pingcap/tidb#7855]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
ansible-playbook local_prepare.yml

2. What did you expect to see?

3. What did you see instead?
FAILED - RETRYING: download tidb binary (4 retries left).
FAILED - RETRYING: download tidb binary (3 retries left).
FAILED - RETRYING: download tidb binary (2 retries left).
FAILED - RETRYING: download tidb binary (1 retries left).
failed: [localhost] (item={u'url': u'http://download.pingcap.org/tidb-latest-linux-amd64-unportable.tar.gz', u'version': u'latest', u'name': u'tidb'}) => {"attempts": 4, "changed": false, "dest": "/home/tidb/tidb-ansible/downloads/tidb-latest.tar.gz", "item": {"name": "tidb", "url": "http://download.pingcap.org/tidb-latest-linux-amd64-unportable.tar.gz", "version": "latest"}, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.pingcap.org/tidb-latest-linux-amd64-unportable.tar.gz"}

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.1-46-gf270b10

**Comment by iamxy** [comment]
Thanks for the feedback.
Please keep your `release-2.0` branch of `tidb-ansible` up-to-date
