### ISSUE TITLE
When the delete sql exceeds 256MB, the 4000th port of tidb node stops.

### ISSUE THREAD

**Issue by bianxindong** [pingcap/tidb#7861]
As the title says,when the delete sql exceeds 256MB, the 4000th port of tidb node stops.
What I want to know is how to write the sql when I want to delete the information of the large table.

**Comment by jackysp** [comment]
Thanks for your report, @bianxindong !
Do you mean the size of the SQL file is larger than 256MB?
Please provide the TiDB server's log and TiDB version.

**Comment by bianxindong** [comment]
> Thanks for your report, @bianxindong !
> Do you mean the size of the SQL file is larger than 256MB?
> Please provide the TiDB server's log and TiDB version.

![image](https://user-images.githubusercontent.com/26322785/46726227-83106400-ccb0-11e8-8616-b5148c10b574.png)
![image](https://user-images.githubusercontent.com/26322785/46726351-bb17a700-ccb0-11e8-86ce-2235619b1b6e.png)
![image](https://user-images.githubusercontent.com/26322785/46726396-d1bdfe00-ccb0-11e8-8f1b-96730e3dae13.png)
![image](https://user-images.githubusercontent.com/26322785/46726443-f1edbd00-ccb0-11e8-85c0-5020dc6072ad.png)
![image](https://user-images.githubusercontent.com/26322785/46726706-79d3c700-ccb1-11e8-8ecd-58a1a46e6da8.png)


tidb version :
Release Version:  v2.0.1
Git Commit Hash:  389703aa5bcf325d79fb3980194f9ce3d2d3a9d5
Git Commit Branch:  release-2.0
UTC Build Time:  2018-05-16 03:39:30
GoVersion:  go version go1.10.2 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1

When rd exec the delete sql,our alarm system called me the result. All 4000th ports of tidb nodes were down.I had to exec the script of stop_tidb.sh and start_tidb.sh,and then those service were back to normal.

**Comment by jackysp** [comment]
It seems a fixed issue. Could you please update to the latest version v2.0.7?
I'll ask an expert for help.
PTAL @WangXiangUSTC .

**Comment by WangXiangUSTC** [comment]
seems fixed in this pr https://github.com/pingcap/tidb/pull/7086
you can update to v2.0.7 and try again. @bianxindong

**Comment by bianxindong** [comment]
When our service is back to normal, I exec the sql that's added condition. It looks ok.
So the limitation of memory is 256MB, Did what I operated cause out of memory ?

**Comment by zhexuany** [comment]
@bianxindong It is a fixed problem. You did not do anything wrong. Rather, it is a problem on our side. Closing since the problem had been resolved.
