### ISSUE TITLE
[FR] Use SQL or HTTP-API to get the hotspot

### ISSUE THREAD

**Issue by shenli** [pingcap/tidb#7870]
## Feature Request

**Is your feature request related to a problem? Please describe:**

It is not easy to find out which table/index is the hotspot when the database is slow.

**Describe the feature you'd like:**

We could get the hotspot through `pd-ctl`. But it is inconvenient for the users to got insight which table/index is the hotspot. They have to decode the region start-key/end-key to get table/index id, then use tidb's HTTP API to locate the table/index name.

We'd better provide a one-click way to show which table/index is the hotspot.

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

When the TiDB cluster is slow, user could easily find out the root cause.

**Comment by shenli** [comment]
[Here](https://github.com/pingcap/docs/blob/master/tools/pd-control.md#hot-read--write--store) is the API to get the hot read/write regions.

**Comment by lysu** [comment]
maybe “get current table/index name of storage hot region” is more suitable requirement title😂

the hotspot is storage region，not table/index

**Comment by shenli** [comment]
@lysu The data in the hot region must belong to a table/index.
