### ISSUE TITLE
The query is too slow，How to optimize performance？

### ISSUE THREAD

**Issue by Lyle-liang** [pingcap/tidb#7889]
![image](https://user-images.githubusercontent.com/14850448/46902165-04efcf80-cef3-11e8-8e89-8b3d2351dab0.png)

![image](https://user-images.githubusercontent.com/14850448/46902142-724f3080-cef2-11e8-8b14-68de34801836.png)

![image](https://user-images.githubusercontent.com/14850448/46902280-281b7e80-cef5-11e8-856b-3cbe40c365d7.png)

**Comment by jackysp** [comment]
Hi, @Lyle-liang . Please use the default template to summit an issue.
BTW: the first plot was not uploaded successful.

**Comment by Lyle-liang** [comment]
## Question

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Cluster information:
TiDB： 3  mem:120G  cpu:8
PD： 3  mem:120G  cpu:16
TiKV： 6   mem:120G  cpu:16

Tide-ansible v2.6.5


2. What did you expect to see?
Current Data Storage : 2T ，Continuous writing

execute SQL time： about 10s

![image](https://user-images.githubusercontent.com/14850448/46905608-ddb3f500-cf28-11e8-836d-276440e9dea8.png)

3. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

TiDB version 2.1.0-rc.2

4. What can I do for it?  What are the optimization suggestions?

Thanks.

**Comment by jackysp** [comment]
Thanks for your providing these detail information, @Lyle-liang !
I have one question for you. What does "Continuous writing"? Or what's the workload of your cluster?
It seems your coprocessor CPU goes to very high but the raft store is very slow. It could be some heavy reading workload instead of writing ones. Only one TiKV reach the CPU uplimit, I think there are some hot region in your workload.
For the cluster deployment, I have one suggestion that it will waste some resources if you deploy the PD server to a Hi-end machine. It could be deployed on the TiDB/TiKV server.

**Comment by Lyle-liang** [comment]
@jackysp 
This is the last 4 hours of query time  between TiDB and mysql .  (unit: ms)

![image](https://user-images.githubusercontent.com/14850448/46906345-a9463600-cf34-11e8-91da-d934246cf427.png)

**Comment by Lyle-liang** [comment]
@jackysp 
Don't care about "Continuous writing". I want to tune cluster parameters for better performance. Thanks.

**Comment by jackysp** [comment]
@Lyle-liang without the detail workload, I cannot give my suggestion for tuning the performance. Please follow our tuning guide yourself https://github.com/pingcap/docs/blob/master/op-guide/tune-tikv.md

**Comment by Lyle-liang** [comment]
@jackysp  I plan to use TIDB as an archive database.  Max statement ops is 100.  Now write performance is good and read performance is poor. So can you give me some good suggestions?

**Comment by Lyle-liang** [comment]
@jackysp I have read Official document and optimized the parameters of tikv, but read  performance  is the same before.

**Comment by jackysp** [comment]
It's glad to see more details of your workload, @Lyle-liang ! 
Could you provide us the following information to help to locate why the SQL runs slow:

- the execution plan of this SQL in TiDB
```sql
explain format="dot" select ...
explain select ...
```

- TiDB version and the exact git commit hash value.
```sql
select tidb_version()\G
```

- the `create table` statement for the involved tables
```sql
show create table ${involved_table_1}\G
show create table ${involved_table_2}\G
...
```

- the statistics data of the involved tables
```sh
curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > ${table_name}_stats.json
```

- is the query always slow, or just occasionally

**Comment by jackysp** [comment]
Thanks, @Lyle-liang ! PTAL @zz-jason .

**Comment by zz-jason** [comment]
@Lyle-liang 
According to the result of `explain format="dot"`, the execution plan of the query is:
<img width="444" alt="2018-10-14 23 52 36" src="https://user-images.githubusercontent.com/5268763/46919078-46c06900-d00c-11e8-8c8a-75d29d242f82.png">

There is a full range index scan, which can cause the tikv cluster busy if the data size of the queried table is too large.

1. Could you please provide the exact query so that we can help you improve the performance of the query?
2. Could you please provide the detailed execution plan of the query by executing the command `explain ${query}`

**Comment by Lyle-liang** [comment]
@zz-jason  Thanks.  I hope the information is useful  for you. 
1. sql:
> explain SELECT 'false' AS QUERYID, id,version,a,b,c,d,e,f,g,h,created_time,j,k,l,m, f_finished_at, n,o,p, canceled_time,updated_time, r, s FROM proarcdb.t_test WHERE b = 123456789 AND p IN ( 5,6,7 ) AND created_time > 1522556131460  AND created_time < 1538150399000 ORDER BY id DESC LIMIT 20;

2. explain ${query}
>+--------------------------+-------+------+-----------------------------------------------------------------------------------------------------------------------+
| id                       | count | task | operator info                                                                                                         |
+--------------------------+-------+------+-----------------------------------------------------------------------------------------------------------------------+
| Projection_7             | 0.00  | root | "false", proarcdb.t_test.id,...                                                                                       |
| └─TopN_10                | 0.00  | root | proarcdb.t_test.id:desc, offset:0, count:20                                                                           |
|   └─IndexLookUp_34       | 0.00  | root |                                                                                                                       |
|     ├─IndexScan_31       | 0.00  | cop  | table:t_test, index:n, p, range:[1339248 5,1339248 5], [1339248 6,1339248 6], [1339248 7,1339248 7], keep order:false |
|     └─Selection_33       | 0.00  | cop  | gt(proarcdb.t_test.created_time, 1522556131460), lt(proarcdb.t_test.created_time, 1538150399000)                      |
|       └─TableScan_32     | 0.00  | cop  | table:t_test, keep order:false                                                                                        |
+--------------------------+-------+------+-----------------------------------------------------------------------------------------------------------------------+

**Comment by zz-jason** [comment]
@Lyle-liang 
1. The `${query}` and the result of `explain ${query}` is not match.


    The used index is `(n, p)` and the range calculated is: `[1339248 5,1339248 5], [1339248 6,1339248 6], [1339248 7,1339248 7]`

    But in the query, the filter is `b = 123456789 AND p IN ( 5,6,7 ) AND created_time > 1522556131460 AND created_time < 1538150399000`. As you can see, there is no filter on column `n`

2. The row count estimated is `0.00`. Have you analyzed the table `proarcdb.t_test`? If not, please analyze the table and check the query plan again:

```sql
-- analyze table:
analyze table proarcdb.t_test;

-- check the query plan:
explain select 'false' as queryid, id, version, a, b, c, d, e, f, g, h, created_time, j, k, l, m, f_finished_at, n, o, p, canceled_time, updated_time, r, s
from proarcdb.t_test
where   b = 123456789 and
        p in (5,6,7) and
        created_time > 1522556131460 and
        created_time < 1538150399000
order by id desc
limit 20;

-- it's better to provide the result of the following queries:
select count(*) from proarcdb.t_test where b = 123456789 and p in (5,6,7);
select count(*) from proarcdb.t_test where b = 123456789 and p in (5,6,7) and created_time > 1522556131460 and created_time < 1538150399000;
```

**Comment by Lyle-liang** [comment]
@zz-jason 

>show stats_healthy;
proarcdb.t_test  |        80

analyze operation is auto.


>select count(1) from proarcdb.t_test where **n** = 123456789 and p in (5,6,7);
985
select count(1) from proarcdb.t_test where **n** = 123456789 and p in (5,6,7) and created_time > 1522556131460 and created_time < 1538150399000;
821

sorry，sql like that:
>explain SELECT 'false' AS QUERYID, id,version,a,b,c,d,e,f,g,h,created_time,j,k,l,m, f_finished_at, n,o,p, canceled_time,updated_time, r, s FROM proarcdb.t_test WHERE **n** = 123456789 AND p IN ( 5,6,7 ) AND created_time > 1522556131460 AND created_time < 1538150399000 ORDER BY id DESC LIMIT 20;

**Comment by zz-jason** [comment]
@Lyle-liang It seems that the query plan for this sql is correct. Is the query always slow, or just occasionally?

**Comment by Lyle-liang** [comment]
@zz-jason The query  always show slow query。

**Comment by Lyle-liang** [comment]
@zz-jason 
![image](https://user-images.githubusercontent.com/14850448/46927065-4359cb80-d066-11e8-8c7e-bcfe2cec781b.png)

**Comment by zz-jason** [comment]
@Lyle-liang The image can not be loaded. How long does it take to run the query when the cluster is not busy?

**Comment by Lyle-liang** [comment]
@zz-jason 
![image](https://user-images.githubusercontent.com/14850448/46927226-edd1ee80-d066-11e8-8e3f-2cd44b7e4413.png)

The picture show coprocessor request duration.

The sql costs 500-900ms.

**Comment by zz-jason** [comment]
@Lyle-liang the coprocessor request duration can be affected by other queries, I think this query maybe is not the root cause which slows down the TPS/QPS/OPS, is there any other slow queries? Could you provide us the tidb log?

**Comment by zz-jason** [comment]
@Lyle-liang can we get access to the TiDB Grafana Monitor?

**Comment by Lyle-liang** [comment]
@zz-jason 
Can we communicate through WeChat?
WeChat ID：13609827103

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
