### ISSUE TITLE
I hope that tidb officially can provide operational documentation on disaster recovery.

### ISSUE THREAD

**Issue by sakufo** [pingcap/tidb#7891]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**
For example, if the records, tables, and libraries are incorrectly updated or deleted, what methods are available to quickly recover the data.

It is best to provide a quick and easy way to quickly read binlog operation records within a specified time or pos range. And can filter the statement according to the library and table. In order to quickly recover the tidb data that was left wrong.

**Describe alternatives you've considered:**
Reference mysql data recovery program

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by jackysp** [comment]
Good suggestion!

**Comment by WangXiangUSTC** [comment]
you can use drainer to output binlog to local file, and use mydumper backup data regular. And then you can use reparo to recover data to any time. We will upload the user guide of reparo recently, please pay attention to it.
