### ISSUE TITLE
The metadata produced by mydumper is short of data

### ISSUE THREAD

**Issue by bianxindong** [pingcap/tidb#7900]
![image](https://user-images.githubusercontent.com/26322785/46938018-43bd8b00-d095-11e8-8f6c-bd7310e278af.png)

As the picture says, metadata is short of some data.I can't find config of binlog and I think something wrong in my case.

![image](https://user-images.githubusercontent.com/26322785/46938269-e1b15580-d095-11e8-87d5-1bd02179d27f.png)

**Comment by bianxindong** [comment]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I am migrating data from mysql to tidb.When I use mydumper to back up data, I find  the metadata is short of some data.
The version of mysql is 5.6.26 and the data files are over 600G.

2. What did you expect to see?
I want to get data of binlog to execute syncer.


3. What did you see instead?
As the picture says.


4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
 /data1/tidb/deploy/bin/tidb-server -V
Release Version:  v2.0.7
Git Commit Hash:  29ec059cb3b7d14b6f52c2f219f94a89570162bc
Git Commit Branch:  release-2.0
UTC Build Time:  2018-09-07 12:36:02
GoVersion:  go version go1.11 linux/amd64
TiKV Min Version:  2.0.0-rc.4.1

**Comment by jackysp** [comment]
Thanks for your detail info, @bianxindong !
PTAL @holys .

**Comment by kennytm** [comment]
Hi @bianxindong thanks for the report.

Could you tell us where did you get the mydumper? If you are using the one provided by the system package manager, we recommend using our fork of mydumper instead ([instructions](https://github.com/pingcap/mydumper#how-to-install-mydumpermyloader)).

**Comment by bianxindong** [comment]
I use the tool provided by you.
![image](https://user-images.githubusercontent.com/26322785/46941038-c39b2380-d09c-11e8-97bd-9a59637c6d09.png)
I used the same tool to migrate data from mysql to tidb some months ago and i was ok!

**Comment by kennytm** [comment]
@bianxindong Thanks again. Could you check the followings?

1. If by "short of data" you mean the `SHOW MASTER STATUS` information is missing, please verify if binlog is enabled in the source MySQL server

    ```sql
    SHOW BINARY LOGS;
    ```

2. If binlog is properly enabled, please try to upgrade to the latest mydumper (v0.9.5). I've tried locally and the metadata does contain the SHOW MASTER STATUS.
    
<img width="507" alt="screenshot 2018-10-15 at 17 39 54" src="https://user-images.githubusercontent.com/103023/46946327-ebdd4f00-d0a9-11e8-8e29-220884c7a3f1.png">
    
<img width="745" alt="screenshot 2018-10-15 at 18 30 22" src="https://user-images.githubusercontent.com/103023/46946332-f39cf380-d0a9-11e8-81c2-7c48119bd879.png">

**Comment by kennytm** [comment]
No problem 😄
