### ISSUE TITLE
enhance the access path pruning

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#7945]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No

**Describe the feature you'd like:**

For table paths, if the filter is a `in` scalar function, we can also chose the table path directly, remove other possible access paths.

For index paths, we can handle the `in` scalar function as the what we do in the table path pruning.

For now, we only considered the equal conditions:
https://github.com/pingcap/tidb/blob/master/planner/core/logical_plans.go#L356

**Comment by zz-jason** [comment]
another thing is, we can also prune the access paths if the filter involves an auto increment column and the filter on that column is equal or in conditions.

**Comment by yu34po** [comment]
Interesting this problem, I'll solve it.

**Comment by zz-jason** [comment]
After searching the code, I found that this issue has been fixed. @winoros Please confirm whether we can close this issue.

**Comment by winoros** [comment]
Confirmed that this one can be fixed
