### ISSUE TITLE
Support for view feature

### ISSUE THREAD

**Issue by AndrewDi** [pingcap/tidb#7974]
## Feature Request

**Is your feature request related to a problem? Please describe:**

No
**Describe the feature you'd like:**

MySQL view feature compatibility
From now on, I have complete following function:

1. Create or Replace viename AS select statement 
ref [MySQL Document Create or Replace VIEW](https://dev.mysql.com/doc/refman/8.0/en/create-view.html)
`create or replace view v as select a+199*0.5 from t;`
![image](https://user-images.githubusercontent.com/7589147/47264726-d73c0380-d54e-11e8-8d95-ec93a8691b7f.png)
2. show full ables grammar support view
ref [MySQL Document Show full tables](https://dev.mysql.com/doc/refman/8.0/en/show-tables.html)
`show full tables`
![image](https://user-images.githubusercontent.com/7589147/47264758-41ed3f00-d54f-11e8-9b74-b561a4158b14.png)
3.show create table grammar support view
ref [MySQL Document show create table](https://dev.mysql.com/doc/refman/8.0/en/show-create-table.html)
`show create table v`
![image](https://user-images.githubusercontent.com/7589147/47264771-6c3efc80-d54f-11e8-913e-5b5390e6dd1c.png)

**Teachability, Documentation, Adoption, Migration Strategy:**

Design Doc:
https://docs.google.com/document/d/1fzWxn9eqi4qwhS5KmIgQd-AhNt1J1HZfc4jf7HTSAzo/edit?usp=sharing

**Comment by shenli** [comment]
@AndrewDi Thanks!

**Comment by nullnotnil** [comment]
I am going to close this issue now, as views are now available. Known issues are being tracked in https://github.com/pingcap/tidb/issues/9798

Thanks!
