### ISSUE TITLE
What's the meaning of interface Visitor?

### ISSUE THREAD

**Issue by roger-lijian** [pingcap/tidb#798]
I find interface **Visitor** was defined in three go files.
```c
ast.go (tidb\ast):type Visitor interface {
plan.go (tidb\optimizer\plan):type Visitor interface {
visitor.go (tidb\expression):type Visitor interface {
```

In particular, the definitions in plan.go and ast.go are exactly the same.
```go
type Visitor interface {
	// Enter is called before children nodes are visited.
	// The returned node must be the same type as the input node n.
	// skipChildren returns true means children nodes should be skipped,
	// this is useful when work is done in Enter and there is no need to visit children.
	Enter(n Node) (node Node, skipChildren bool)
	// Leave is called after children nodes have been visited.
	// The returned node's type can be different from the input node if it is a ExprNode,
	// Non-expression node must be the same type as the input node n.
	// ok returns false to stop visiting.
	Leave(n Node) (node Node, ok bool)
}
```
what's the meaning of this interface? Can you explain the functions Enter/Leave in detail?

thx.

**Comment by coocood** [comment]
I think it's easier to understand it by a simple example.
Take a look at
https://github.com/pingcap/tidb/blob/master/executor/prepared.go#L50

The `paramMarkerExtractor` visitor extracts parameter markers ('?') in a query statement.
When a node call its `Accept` method, every element will be `Enter` and `Leave` once, so the visitor can do something about it. For this example, it collect parameter marker.

**Comment by roger-lijian** [comment]
ok, thx
