### ISSUE TITLE
有关xfs文件系统的疑问

### ISSUE THREAD

**Issue by daikon12** [pingcap/tidb#7992]
有关xfs文件系统的疑问
在TIDB官网上，推荐的文件系统只有EXT4一种，目前我的集群中多半是XFS，少数是EXT4。不知道用XFS的节点部署TIDB、TIKV、PD可以吗，如果不可以是因为什么原因呢

**Comment by crazycs520** [comment]
@LinuxGit PTAL

**Comment by LinuxGit** [comment]
refer to https://github.com/pingcap/docs-cn/issues/939
