### ISSUE TITLE
ansible-playbook deploy.yml 时候报错 hostnames of all nodes in cluster

### ISSUE THREAD

**Issue by xiaokang69** [pingcap/tidb#7994]
TASK [check_system_dynamic : Preflight check - Does every node in cluster have different hostname] ************
fatal: [192.168.111.201]: FAILED! => {"changed": false, "msg": "hostnames of all nodes in cluster: [localhost, localhost, localhost, localhost, localhost, localhost]\n"}

NO MORE HOSTS LEFT ********************************************************************************************
        to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/deploy.retry

PLAY RECAP ****************************************************************************************************
192.168.111.201            : ok=3    changed=0    unreachable=0    failed=1
192.168.111.202            : ok=2    changed=0    unreachable=0    failed=0
192.168.111.203            : ok=2    changed=0    unreachable=0    failed=0
192.168.111.204            : ok=2    changed=0    unreachable=0    failed=0
192.168.111.205            : ok=2    changed=0    unreachable=0    failed=0
192.168.111.206            : ok=2    changed=0    unreachable=0    failed=0
localhost                  : ok=1    changed=0    unreachable=0    failed=0

ERROR MESSAGE SUMMARY *****************************************************************************************
[192.168.111.201]: Ansible FAILED! => playbook: deploy.yml; TASK: check_system_dynamic : Preflight check - Does every node in cluster have different hostname; message: {"changed": false, "msg": "hostnames of all nodes in cluster: [localhost, localhost, localhost, localhost, localhost, localhost]\n"}

Ask for help:
Contact us: support@pingcap.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the tidb-ansible/inventory.ini and tidb-ansible/log/ansible.log files and the error message, or new issue on https://github.com/pingcap/tidb-ansible/issues. We'll try our best to help you deploy a TiDB cluster. Thanks. :-)

**Comment by crazycs520** [comment]
@LinuxGit PTAL

**Comment by LinuxGit** [comment]
refer to the error messages, you should set different hostname for every node in cluster.
