### ISSUE TITLE
The := operator is supported in the set syntax

### ISSUE THREAD

**Issue by xjxyxgq** [pingcap/tidb#7995]
## Feature Request

The set syntax assignment operator description in the mysql document:
"The following sections describe SET syntax for setting variables. They use the = assignment operator, but the := assignment operator is also permitted for this purpose."

Whether tidb can also support these two assignment operators to avoid compatibility problems encountered in the program, thank you.

`
mysql> SET @@SQL_MODE := "";
Query OK, 0 rows affected (0.00 sec)

tidb> mysql> SET @@SQL_MODE := "";
ERROR 1105 (HY000): line 1 column 17 near " """ (total length 20)
`

[ref](https://dev.mysql.com/doc/refman/8.0/en/set-variable.html)

**Comment by crazycs520** [comment]
@tiancaiamao PTAL
