### ISSUE TITLE
suport DDL enable/disable flag or a special tool.

### ISSUE THREAD

**Issue by siddontang** [pingcap/tidb#801]
not all servers can run the DDL, maybe we can run DDL in only a little servers or with some special tools later. 

so what we can do later maybe:
- [ ] supply a flag to control DDL, default is false, so these servers can only re-load schema regularly, but can't do DDL jobs, not support DDL query. 
- [ ] supply a special tool like F1 to run DDL.

@qiuyesuifeng any to add?

**Comment by qiuyesuifeng** [comment]
LGTM

**Comment by coocood** [comment]
Implemented.
