### ISSUE TITLE
Optimize "DELETE" statement without "WHERE" clause.

### ISSUE THREAD

**Issue by coocood** [pingcap/tidb#802]
Currently truncate table deletes all the keys with a prefix, this would take a long time.

After we finished the truncate, if we insert a new row and scan the table again with "select \* from t", the table only contains one row, but all the deleted rows wil be scanned, this would take us very long time to just select a single row.

This behaviour doesn't meet the user expectation that the empty table should to be performant after truncate.

We should create a new table with the same schema and rename it to the original table, the operation can return imediately, and  scan the new table would be fast.

Some times user deletes table with no condition, which is equalent to truncate table, in this case, we should convert the statement to truncate statement.

**Comment by siddontang** [comment]
If we have a huge table, and delete data with limit, at last, we have only one row in this table, then we insert a row and `select * from t`, how to optimize it?

**Comment by coocood** [comment]
@siddontang In this case, we have to wait for garbage collector to physical delete those rows.

**Comment by coocood** [comment]
TRUNCATE table has been optimized, now we need to optimize DELETE without WHERE.

**Comment by coocood** [comment]
Truncate is changed to DDL.
For the delete without where clause, since we limited the size of a transaction, this is obsolete.
