### ISSUE TITLE
TiDB log shows `[warning] con:0 parse error`

### ISSUE THREAD

**Issue by weilain** [pingcap/tidb#8029]
2018/10/24 10:24:43.398 session.go:818: [warning] con:0 parse error:
line 1 column 114 near " duplicate key update tot_col_size = tot_col_size + values(tot_col_size), version = values(version)" (total length 213)
insert into mysql.stats_histograms (table_id, is_index, hist_id, distinct_count, tot_col_size, version) values  on duplicate key update tot_col_size = tot_col_size + values(tot_col_size), version = values(version)
请问这是出现什么问题了吗

**Comment by XuHuaiyu** [comment]
Hi, @weilain 
What's your tidb-server version?
You can check it using `select tidb_version()`.

**Comment by XuHuaiyu** [comment]
PTAL @lamxTyler

**Comment by weilain** [comment]
mysql> select tidb_version();
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                          |
+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.0.6
Git Commit Hash: b13bc08462a584a085f377625a7bab0cc0351570
Git Branch: release-2.0
UTC Build Time: 2018-08-06 10:57:46
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

**Comment by weilain** [comment]
@XuHuaiyu

**Comment by lamxTyler** [comment]
@weilain It has been fixed in 2.0.7, you can upgrade your tidb server.

**Comment by weilain** [comment]
@lamxTyler What is the way to upgrade, now there is a mysql database synchronization tidb will not be interrupted?

**Comment by weilain** [comment]
Incremental synchronization

**Comment by XuHuaiyu** [comment]
PTAL @WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
which tool you used to sync data? @weilain

**Comment by weilain** [comment]
Tidb built in Alibaba Cloud Now use syncer to synchronize the data of Alibaba Cloud RDS to tidb. If you upgrade tidb now, the synchronization will not be interrupted.

**Comment by weilain** [comment]
Two days ago, I remember that there was no such error. Yesterday I turned on the slow query of tidb, modified the parameter enable_slow_query_log, and then performed an instance rolling upgrade. This is the case, is this the reason？

**Comment by lamxTyler** [comment]
@weilain No, it is not the reason. It is an internal bug.

**Comment by july2993** [comment]
> Tidb built in Alibaba Cloud Now use syncer to synchronize the data of Alibaba Cloud RDS to tidb. If you upgrade tidb now, the synchronization will not be interrupted.

Syncer will not be interrupted and continue syncing data to data you TiDB is down just in a small window time, so you can just upgrade TiDB,  after this, check Syncer still working or start Syncer again(syncer will save the checkpoint into a file)

**Comment by weilain** [comment]
@lamxTyler https://pingcap.com/docs-cn/op-guide/ansible-deployment-rolling-update/#%E5%8D%87%E7%BA%A7%E7%BB%84%E4%BB%B6%E7%89%88%E6%9C%AC 
Upgrade according to the documentation? Download binary and then use Ansible to scroll and upgrade. Synchronization should interrupt the service.

**Comment by weilain** [comment]
@july2993 Just rolling upgrade the tidb node?

**Comment by july2993** [comment]
@weilain 
- stop Syncer
- rolling upgrade the tidb node according the doc
- start back Syncer and check everything working

**Comment by weilain** [comment]
Ok, let me try! ,Thank you

**Comment by weilain** [comment]
failed: [localhost] (item={u'url': u'http://download.pingcap.org/tidb-v2.0.7-linux-amd64-unportable.tar.gz', u'version': u'v2.0.7', u'name': u'tidb'}) => {"attempts": 4, "changed": false, "dest": "/home/tidb/tidb-ansible/downloads/tidb-v2.0.7.tar.gz", "item": {"name": "tidb", "url": "http://download.pingcap.org/tidb-v2.0.7-linux-amd64-unportable.tar.gz", "version": "v2.0.7"}, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://download.pingcap.org/tidb-v2.0.7-linux-amd64-unportable.tar.gz"}

**Comment by weilain** [comment]
@july2993 Where did the error occur?

**Comment by weilain** [comment]
![image](https://user-images.githubusercontent.com/42827119/47412079-3bec9d80-d79d-11e8-9e2e-bbb4c414a9bd.png)

**Comment by LinuxGit** [comment]
@weilain Please download latest tidb-ansible release-2.0 branch, tidb package's download url has changed.

**Comment by weilain** [comment]
Can you give the next page address?

**Comment by july2993** [comment]
https://github.com/pingcap/tidb-ansible
use the release-2.0 branch

**Comment by weilain** [comment]
Does the operation affect the original service?

**Comment by weilain** [comment]
Is it equivalent to downloading the latest tidb-absible, reconfigure?

**Comment by july2993** [comment]
@liubo0127 PTAL about ansible

**Comment by weilain** [comment]
Can you elaborate?

**Comment by LinuxGit** [comment]
@weilain You can refer to https://github.com/pingcap/docs/blob/master/op-guide/tidb-v2-upgrade-guide.md#download-tidb-ansible-to-the-control-machine, 
reconfigure inventory.ini.

If you have previously customized the configuration file of TiDB cluster components, refer to the backup file to modify the corresponding configuration file in /home/tidb/tidb-ansible/conf.

It does not affect the original services.
