### ISSUE TITLE
How can I test TiDB with sysbench? Which version of sysbench can be compatible with TiDB, or which version of sysbench need to be patched to test? How to patch?

### ISSUE THREAD

**Issue by xtay573269555** [pingcap/tidb#8040]
## Question
请问如何用sysbench测试TiDB？github和官网上的sysbench测试都只有结果，对测试方法只给了个 https://github.com/pingcap/docs/blob/master/benchmark/sysbench.md 链接，这个链接对这些问题都没有说明。
哪个版本的sysbench可以兼容TiDB，或需要使用哪个版本的sysbench打补丁后可以测试？
我下载了 tidb-bench-master.zip ，看到其中有 sysbench-patch 目录，但没有找到打补丁的说明？

**Comment by jackysp** [comment]
Hi @xtay573269555 ,
Thanks for your attention! We used the official sysbench to test the performance of TiDB, and the results in your report were from version 1.0.6. In fact, versions after 1.0 are all available for trial use. Versions 0.4 and 0.5 have not been tested.
We plan to give TiDB's sysbench detailed test recommendations in the future, including TiDB parameter optimization, etc., so stay tuned.

**Comment by xtay573269555** [comment]
tidb-sysbench步骤
安装mysql-client
安装sysbench 1.0.15

下载https://github.com/pingcap/tidb-bench

修改测试参数
tidb-bench-master/sysbench/conf.sh
############################################################
host=218.168.129.14
port=4000
user=root
password='123456'
tcount=32
tsize=1000000
threads=64
dbname=sysbench_db

# report interval
interval=10

# max time in seconds
maxtime=7200

# just large enough to fit maxtime
requests=2000000000

driver=mysql
############################################################

准备基础数据
nohup sh parallel-prepare.sh > 0_prepare.log 2>&1 &

开始sysbench测试
nohup sh oltp.sh > 1_run.log 2>&1 &
