### ISSUE TITLE
unsupported add column constraint - 3

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#8086]
## Bug Report

1. What did you do?

```
ALTER TABLE `users` ADD `id` int unsigned AUTO_INCREMENT;
unsupported add column constraint - 3
```

2. What did you expect to see?

unsupported add column constraint AUTO_INCREMENT when altering "users.id".

3. What did you see instead?

I did not expect to see the number `3` in the output.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

2.0.7

**Comment by gregwebs** [comment]
see a similar error message here: https://github.com/pingcap/tidb/issues/532

**Comment by morgo** [comment]
I chatted to @gregwebs about this briefly.  Since add/drop primary key is an incompatibility we will have for a while, we should improve the error messages so it is clearer for users.

**Comment by crazycs520** [comment]
I will do it.
