### ISSUE TITLE
panic_hook.rs:97: [ERROR] thread 'cop-normal0' panicked 'key t\200\000\000\000\000\000\000\377f_r\200\000\000\000\003\377N\312\303\000\000\000\000\000\372 not found, ts 403674747099676686' at "src/storage/mvcc/reader.rs:92

### ISSUE THREAD

**Issue by OPSTime** [pingcap/tidb#8099]
**tidb** version： 
tidb-v2.0.3

**OS** version：
CentOS Linux release 7.4.1708 (Core)

**Error** log：
`
2018/10/29 07:40:37.311 endpoint.rs:404: [INFO] [region 5076] [slow-query] execute takes 16.917, wait takes Some(772.767), peer: "ipv4:192.168.1.9:33522", start_ts: 403903397867290629, table_id: 102, scan_type: select (desc: Some(true)) [keys: 1327074, hit: 663536, ranges: 1 (Some(start: "t\200\000\000\000\000\000\000f_r\200\000\000\000\003i\211\034" end: "t\200\000\000\000\000\000\000f_r\200\000\000\000\003n\231\024"))]
2018/10/29 07:40:37.797 panic_hook.rs:97: [ERROR] thread 'cop-normal0' panicked 'key t\200\000\000\000\000\000\000\377f_r\200\000\000\000\003\377N\312\303\000\000\000\000\000\372 not found, ts 403674747099676686' at "src/storage/mvcc/reader.rs:92"
stack backtrace:
   0:     0x557f2fa6ca2e - backtrace::backtrace::libunwind::trace::h79c4af28be231e54
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace::h56424d341baa1bce
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x557f2f538427 - tikv::util::panic_hook::set_exit_hook::{{closure}}::ha68d6f11948f10b7
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/pingcap/tikv/target/release/build/backtrace-5e253aa535e0fe5b/out/capture.rs:79
   2:     0x557f2fc3e4e5 - std::panicking::rust_panic_with_hook::h1be8ff44b2f85fd7
                        at libstd/panicking.rs:403
   3:     0x557f2fc3e37d - std::panicking::begin_panic_fmt::h9462a882b9175ee8
                        at libstd/panicking.rs:349
   4:     0x557f2f6c993b - tikv::storage::mvcc::reader::MvccReader::load_data::hdd970f42f4dfc0c6
                        at src/storage/mvcc/reader.rs:92
                         - tikv::storage::mvcc::reader::MvccReader::get::hd7e656df5d830371
                        at src/storage/mvcc/reader.rs:237
   5:     0x557f2f6e20d2 - tikv::storage::mvcc::reader::MvccReader::reverse_seek::h2b460181f6eccd58
                        at src/storage/mvcc/reader.rs:404
                         - tikv::storage::txn::store::StoreScanner::reverse_seek::hbfaf0997e5afe739
                        at src/storage/txn/store.rs:129
                         - tikv::coprocessor::dag::executor::scanner::Scanner::next_row::h510a79e8d60462ec
                        at src/coprocessor/dag/executor/scanner.rs:101
   6:     0x557f2f6df56b - tikv::coprocessor::dag::executor::table_scan::TableScanExecutor::get_row_from_range_scanner::he760b8c0313f6928
                        at src/coprocessor/dag/executor/table_scan.rs:84
                         - <tikv::coprocessor::dag::executor::table_scan::TableScanExecutor as tikv::coprocessor::dag::executor::Executor>::next::h6b3b0ae381b0d306
                        at src/coprocessor/dag/executor/table_scan.rs:121
   7:     0x557f2f76b1cc - <tikv::coprocessor::dag::executor::selection::SelectionExecutor as tikv::coprocessor::dag::executor::Executor>::next::hde286313a2464f08
                        at src/coprocessor/dag/executor/selection.rs:58
   8:     0x557f2f76a862 - <tikv::coprocessor::dag::executor::limit::LimitExecutor<'a> as tikv::coprocessor::dag::executor::Executor>::next::h4713de0704a9b937
                        at src/coprocessor/dag/executor/limit.rs:47
   9:     0x557f2f6bf85e - tikv::coprocessor::dag::dag::DAGContext::handle_request::h8d37a1a8977371ad
                        at src/coprocessor/dag/dag.rs:76
                         - tikv::coprocessor::endpoint::Host::handle_request::{{closure}}::h73c143944c97eafe
                        at src/coprocessor/endpoint.rs:157
                         - <tikv::util::futurepool::FuturePool<T>>::spawn::{{closure}}::h9dad150e937eda45
                        at src/util/futurepool.rs:239
                         - <futures::future::lazy::Lazy<F, R>>::get::hf43f8533e3264bd7
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/lazy.rs:64
                         - <futures::future::lazy::Lazy<F, R> as futures::future::Future>::poll::h0a433aa5a2528d8c
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/lazy.rs:82
  10:     0x557f2f4e807a - futures::future::catch_unwind::<impl futures::future::Future for std::panic::AssertUnwindSafe<F>>::poll::ha4c0a52349b35fdb
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/catch_unwind.rs:49
                         - <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll::{{closure}}::hfa85f527ac25a22f
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/catch_unwind.rs:32
                         - std::panicking::try::do_call::h44dacc2d8c33352e
                        at /checkout/src/libstd/panicking.rs:306
                         - <futures_cpupool::MySender<F, core::result::Result<<F as futures::future::Future>::Item, <F as futures::future::Future>::Error>> as futures::future::Future>::poll::h3cf704cb51247f3f
                        at /checkout/src/libpanic_unwind/lib.rs:102
  11:     0x557f2fa52eb8 - futures_cpupool::Inner::work::h56244bfe00b04f10
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.17/src/future/mod.rs:113
                         - futures_cpupool::Builder::create::{{closure}}::hb1e43f39fa264c47
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-cpupool-0.1.8/src/lib.rs:427
                         - std::sys_common::backtrace::__rust_begin_short_backtrace::h4b56c18cc87848b4
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
  12:     0x557f2fa51b97 - std::thread::Builder::spawn::{{closure}}::{{closure}}::hcb7a9d53db76bea4
                        at /checkout/src/libstd/thread/mod.rs:406
                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h30ab1c893faccad4
                        at /checkout/src/libstd/panic.rs:296
                         - std::panicking::try::do_call::hc09e6aed54986ba4
                        at /checkout/src/libstd/panicking.rs:306
                         - std::panicking::try::h2d3f2743155defaa
                        at /checkout/src/libpanic_unwind/lib.rs:102
                         - std::panic::catch_unwind::h24e6789e7e72ac79
                        at /checkout/src/libstd/panic.rs:361
                         - std::thread::Builder::spawn::{{closure}}::he95d7750ff209956
                        at /checkout/src/libstd/thread/mod.rs:405
                         - <F as alloc::boxed::FnBox<A>>::call_box::hc10af84fcbb2b34c
                        at /checkout/src/liballoc/boxed.rs:635
  13:     0x557f2fc35167 - std::sys::unix::thread::Thread::new::thread_start::h0c3a0b0523777f20
                        at /checkout/src/liballoc/boxed.rs:645
  14:     0x7fdaed56ce24 - start_thread
  15:     0x7fdaed08434c - __clone
  16:                0x0 - <unknown>
2018/10/29 07:40:55.575 mod.rs:350: [INFO] Welcome to TiKV.`

**Comment by XuHuaiyu** [comment]
Hi, @lyddragon Thanks for your feedback.

Can you provide us:
1. The result of `./tidb-server -V` and `./tikv-server -V`
2. The actions of what you've in the cluster.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
