### ISSUE TITLE
Upgrade version report transfer PD leader to another PD server error

### ISSUE THREAD

**Issue by evancao77** [pingcap/tidb#8120]
在版本升级的时候碰到报错如下：
TASK [transfer PD leader to another PD server] ************************************************************************************************************************************************
fatal: [192.168.60.43]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://192.168.60.43:2379/pd/api/v1/leader/resign"}

麻烦看下

**Comment by ciscoxll** [comment]
@evancao77 What version was it before the upgrade? , what version to upgrade to? Can provide a log?

**Comment by evancao77** [comment]
describe in the  title 
Release Version: v1.0.8-1-gaacba4a to 2.0.8

**Comment by evancao77** [comment]
the upgrade log:
PLAY [check config locally] *******************************************************************************************************************************************************************

TASK [check_config_static : Ensure only one monitoring host exists] ***************************************************************************************************************************

TASK [check_config_static : Ensure monitored_servers exists] **********************************************************************************************************************************

TASK [check_config_static : Ensure TiDB host exists] ******************************************************************************************************************************************

TASK [check_config_static : Ensure zookeeper address of kafka cluster is set when enable_binlog] **********************************************************************************************

TASK [check_config_static : Ensure PD host exists] ********************************************************************************************************************************************

TASK [check_config_static : Ensure TiKV host exists] ******************************************************************************************************************************************

TASK [check_config_static : Check ansible_user variable] **************************************************************************************************************************************

TASK [check_config_static : Ensure timezone variable is set] **********************************************************************************************************************************

TASK [check_config_static : Close old SSH control master processes] ***************************************************************************************************************************
ok: [localhost]

PLAY [check system environment] ***************************************************************************************************************************************************************

TASK [check_system_dynamic : Disk space check - Fail task when disk is full] ******************************************************************************************************************
ok: [192.168.60.47]
ok: [192.168.60.43]
ok: [192.168.60.45]
ok: [192.168.60.46]
ok: [192.168.60.44]
ok: [192.168.60.48]

TASK [check_system_dynamic : get facts] *******************************************************************************************************************************************************
ok: [192.168.60.43]
ok: [192.168.60.47]
ok: [192.168.60.46]
ok: [192.168.60.45]
ok: [192.168.60.44]
ok: [192.168.60.48]

TASK [check_system_dynamic : Preflight check - Get hostnames of all nodes in cluster] *********************************************************************************************************
ok: [192.168.60.43]

TASK [check_system_dynamic : Preflight check - Does every node in cluster have different hostname] ********************************************************************************************

TASK [check_system_dynamic : Preflight check - Get NTP service status] ************************************************************************************************************************

TASK [check_system_dynamic : Preflight check - NTP service] ***********************************************************************************************************************************

TASK [check_system_dynamic : Preflight check - Get umask] *************************************************************************************************************************************
ok: [192.168.60.47]
ok: [192.168.60.45]
ok: [192.168.60.43]
ok: [192.168.60.46]
ok: [192.168.60.44]
ok: [192.168.60.48]

TASK [check_system_dynamic : Preflight check - Does the system have a standard umask] *********************************************************************************************************

TASK [check_system_dynamic : Preflight check - Get maximum number of open file descriptors limit] *********************************************************************************************
ok: [192.168.60.43]
ok: [192.168.60.45]
ok: [192.168.60.46]
ok: [192.168.60.47]
ok: [192.168.60.44]
ok: [192.168.60.48]

TASK [check_system_dynamic : Preflight check - ulimit -n] *************************************************************************************************************************************

TASK [check_system_dynamic : Preflight check - Check swap] ************************************************************************************************************************************

PLAY [gather all facts, and check dest] *******************************************************************************************************************************************************

TASK [check_config_dynamic : Set enable_binlog variable] **************************************************************************************************************************************

TASK [check_config_dynamic : Set deploy_dir if not set] ***************************************************************************************************************************************

TASK [check_config_dynamic : environment check (deploy dir)] **********************************************************************************************************************************
ok: [192.168.60.47]
ok: [192.168.60.43]
ok: [192.168.60.46]
ok: [192.168.60.45]
ok: [192.168.60.44]
ok: [192.168.60.48]

TASK [check_config_dynamic : Preflight check - Does deploy dir have appropriate permission] ***************************************************************************************************

TASK [check_config_dynamic : environment check (supervise)] ***********************************************************************************************************************************

TASK [check_config_dynamic : config skip variables (default)] *********************************************************************************************************************************
ok: [192.168.60.43]
ok: [192.168.60.44]
ok: [192.168.60.45]
ok: [192.168.60.46]
ok: [192.168.60.48]
ok: [192.168.60.47]

TASK [check_config_dynamic : config skip variables] *******************************************************************************************************************************************
ok: [192.168.60.44]
ok: [192.168.60.43]
ok: [192.168.60.45]
ok: [192.168.60.46]
ok: [192.168.60.47]
ok: [192.168.60.48]

TASK [check_config_dynamic : config skip variables] *******************************************************************************************************************************************

PLAY [rolling update PD cluster] **************************************************************************************************************************************************************

TASK [set_fact] *******************************************************************************************************************************************************************************
ok: [192.168.60.43]

TASK [display PD name] ************************************************************************************************************************************************************************
ok: [192.168.60.43] => {
    "pd_name": "pd1"
}

TASK [display PD address] *********************************************************************************************************************************************************************
ok: [192.168.60.43] => {
    "pd_addr": "192.168.60.43:2379"
}

TASK [include_tasks] **************************************************************************************************************************************************************************
included: /home/tidb/tidb-ansible/common_tasks/get_pd_leader.yml for 192.168.60.43

TASK [get PD leader info] *********************************************************************************************************************************************************************
ok: [192.168.60.43]

TASK [include_tasks] **************************************************************************************************************************************************************************

TASK [include_tasks] **************************************************************************************************************************************************************************
included: /home/tidb/tidb-ansible/common_tasks/transfer_pd_leader.yml for 192.168.60.43

TASK [set_fact] *******************************************************************************************************************************************************************************
ok: [192.168.60.43]

TASK [display PD leader name] *****************************************************************************************************************************************************************
ok: [192.168.60.43] => {
    "pd_leader_name": "pd1"
}

TASK [transfer PD leader to another PD server] ************************************************************************************************************************************************
fatal: [192.168.60.43]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://192.168.60.43:2379/pd/api/v1/leader/resign"}

NO MORE HOSTS LEFT ****************************************************************************************************************************************************************************
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/rolling_update.retry

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.60.43              : ok=16   changed=0    unreachable=0    failed=1   
192.168.60.44              : ok=7    changed=0    unreachable=0    failed=0   
192.168.60.45              : ok=7    changed=0    unreachable=0    failed=0   
192.168.60.46              : ok=7    changed=0    unreachable=0    failed=0   
192.168.60.47              : ok=7    changed=0    unreachable=0    failed=0   
192.168.60.48              : ok=7    changed=0    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   


ERROR MESSAGE SUMMARY *************************************************************************************************************************************************************************
[192.168.60.43]: Ansible FAILED! => playbook: rolling_update.yml; TASK: transfer PD leader to another PD server; message: {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://192.168.60.43:2379/pd/api/v1/leader/resign"}

Ask for help:

**Comment by ciscoxll** [comment]
@nolouch PTAL.

**Comment by evancao77** [comment]
I restarted another PD and succeeded in skipping it, but I encountered a new error：
fatal: [192.168.60.44]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 192.168.60.44:2379 to stop."}

**Comment by liubo0127** [comment]
Error-1：
fatal: [192.168.60.43]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Connection failure: timed out", "redirected": false, "status": -1, "url": "http://192.168.60.43:2379/pd/api/v1/leader/resign"}

1、There may be a problem with the network
2、You can manually execute http://192.168.60.43:2379/pd/api/v1/leader/resign to see the results


Error-2：
fatal: [192.168.60.44]: FAILED! => {"changed": false, "elapsed": 300, "msg": "Timeout when waiting for 192.168.60.44:2379 to stop."}

The pd service on 192.168.60.44 may not be stopped. You can check it on this machine.

**Comment by shenli** [comment]
@evancao77 Please do not use the rolling-update to upgrade your cluster from 1.x to 2.x.  Stop the whole cluster, deploy new binaries and then start your cluster. Please note to use the correct tidb-ansible version.

**Comment by evancao77** [comment]
i want to want  to upgrade  online.

**Comment by shenli** [comment]
@evancao77 We do not have that promise when upgrading cross two major version.

**Comment by evancao77** [comment]
I successfully upgraded the tidb cluster, but scrolling to upgrade the TiDB monitoring component  use 
 ansible-playbook migrate_monitor.yml , the following problems:
TASK [stop node_exporter by systemd] **********************************************************************************************************************************************************
fatal: [192.168.60.43]: FAILED! => {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}
fatal: [192.168.60.46]: FAILED! => {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}
fatal: [192.168.60.45]: FAILED! => {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}
fatal: [192.168.60.44]: FAILED! => {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}
fatal: [192.168.60.47]: FAILED! => {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}
fatal: [192.168.60.48]: FAILED! => {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

NO MORE HOSTS LEFT ****************************************************************************************************************************************************************************
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/migrate_monitor.retry

PLAY RECAP ************************************************************************************************************************************************************************************
192.168.60.43              : ok=3    changed=0    unreachable=0    failed=1   
192.168.60.44              : ok=3    changed=0    unreachable=0    failed=1   
192.168.60.45              : ok=3    changed=0    unreachable=0    failed=1   
192.168.60.46              : ok=3    changed=0    unreachable=0    failed=1   
192.168.60.47              : ok=3    changed=0    unreachable=0    failed=1   
192.168.60.48              : ok=3    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   


ERROR MESSAGE SUMMARY *************************************************************************************************************************************************************************
[192.168.60.43]: Ansible FAILED! => playbook: migrate_monitor.yml; TASK: stop node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

[192.168.60.46]: Ansible FAILED! => playbook: migrate_monitor.yml; TASK: stop node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

[192.168.60.45]: Ansible FAILED! => playbook: migrate_monitor.yml; TASK: stop node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

[192.168.60.44]: Ansible FAILED! => playbook: migrate_monitor.yml; TASK: stop node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

[192.168.60.47]: Ansible FAILED! => playbook: migrate_monitor.yml; TASK: stop node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

[192.168.60.48]: Ansible FAILED! => playbook: migrate_monitor.yml; TASK: stop node_exporter by systemd; message: {"changed": false, "msg": "Could not find the requested service node_exporter.service: host"}

**Comment by evancao77** [comment]
I upgraded successfully. Thank you

**Comment by keithyzk** [comment]
@evancao77  I have the same problem . 
fatal: [PD2]: FAILED! => {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://192.168.1.20:2379/pd/api/v1/leader"}
 How do you solve this problem? Thank you .
