### ISSUE TITLE
index path pruining when  first column of composite  PK with auto_increment property

### ISSUE THREAD

**Issue by yu34po** [pingcap/tidb#8121]
## Feature Request
No
**Describe the feature you'd like:**
consider composite primary key and first column have auto_increment  property,
TABLE:
CREATE TABLE `test` (
  `a` bigint(20) NOT NULL AUTO_INCREMENT ,
  `b` int(11) NOT NULL ,
  PRIMARY KEY (`a`,`b`)
);
QUERY:
select * from test where a = 1;

in index path pruining, we can  chose the index (`a`,`b`) path directly,pruining other  index path

**Comment by ciscoxll** [comment]
@yu34po Thanks for your feedback. We will take a look.

**Comment by zz-jason** [comment]
agreed with the comment https://github.com/pingcap/tidb/pull/8122#issuecomment-434932814. Here we can directly use index (a, b) is because of it's declared as a primary key.

If we declare the index as a normal secondary index, we should chose this index based on the cost estimation.
