### ISSUE TITLE
About nested prepare stmt

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#8123]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
prepare stmt1 from 'select 1';
prepare stmt2 from 'execute stmt1';
```

2. What did you expect to see?

When run `prepare stmt2 from 'execute stmt1';` Got error.

3. What did you see instead?

It executed successfully.

And run `execute stmt2;` get empty result.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master dc8b94b51f09d8199c4cbf86f4fb8bafd06bfabc

## SIG slack channel

 [#sig-planner](https://slack.tidb.io/invite?team=tidb-community&channel=sig-planner&ref=high-performance)

## Score

- 300

## Mentor

* @lzmhhh123

**Comment by AndrewDi** [comment]
@winoros Even mysql can not address such prepare usage...
```
mysql> prepare stmt1 from 'select 1';
Query OK, 0 rows affected (0.00 sec)
Statement prepared

mysql> prepare stmt2 from 'execute stmt1'; 
ERROR 1295 (HY000): This command is not supported in the prepared statement protocol yet
```

**Comment by wjhuang2016** [comment]
Duplicate with https://github.com/pingcap/tidb/issues/17412
