### ISSUE TITLE
snapshot isolation

### ISSUE THREAD

**Issue by oylz** [pingcap/tidb#8138]
## Bug Report

As the [https://pingcap.com/docs/sql/transaction-isolation/] say,
I tested it , but and the same as [mysql's repeatable read].
and two transactions were successfuly.
version:
----docker:
pingcap/tidb        latest
pingcap/tikv        latest
pingcap/pd          latest

**Comment by oylz** [comment]
detail:
# official said
![official said](https://github.com/oylz/mix/raw/master/tidb_note1.jpg)
# my test
![my test](https://github.com/oylz/mix/raw/master/tidb_note2.jpg)

**Comment by jackysp** [comment]
Hi @oylz , 

![](https://github.com/oylz/mix/raw/master/tidb_note1.jpg)

I think the key point which you misunderstanding is "Transaction Retries in TiDB might fail", it does not mean the transaction always failed.
Actually TiDB will retry 10 times for the conflict transaction by default, it nearly could not fail.

**Comment by jackysp** [comment]
@oylz , it is as expected that no exception would be throw out because TiDB is MySQL compatible. It seems you've already got the retry log.

**Comment by oylz** [comment]
@jackysp ok, thanks. I will close the issue.
