### ISSUE TITLE
Different client query results are different

### ISSUE THREAD

**Issue by bobdeng** [pingcap/tidb#8145]
表结构和查询语句如下：
`
CREATE TABLE `tb_goods_sku` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `goods_id` int(11) DEFAULT NULL COMMENT '商品id',
  `name` varchar(100) DEFAULT NULL COMMENT '规格名',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci AUTO_INCREMENT=30222 COMMENT='商品规格';

CREATE TABLE `tb_goods_sku_attribute` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sku_id` int(11) DEFAULT NULL,
  `value` varchar(100) DEFAULT NULL COMMENT '规格值\n',
  `pic_url` varchar(255) DEFAULT NULL COMMENT '规格图片url',
  `sort` int(11) DEFAULT '0' COMMENT '排序',
  `create_time` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci AUTO_INCREMENT=30459 COMMENT='商品sku属性表';

CREATE TABLE `tb_goods_sku_detail` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `goods_id` int(11) DEFAULT NULL COMMENT '商品id\n',
  `sku_attribute_id_list` varchar(255) DEFAULT NULL COMMENT '规格属性id列表',
  `daily_price` decimal(10,2) DEFAULT NULL COMMENT '日常售价',
  `daily_supply_price` decimal(10,2) DEFAULT NULL COMMENT '日常供货价',
  `small_promotion_price` decimal(10,2) DEFAULT NULL COMMENT '小促售价',
  `controlled_price` int(11) DEFAULT '0' COMMENT '是否控价,1:是,0:否',
  `big_promotion_price` decimal(10,2) DEFAULT '0.00' COMMENT '大促售价(最低控价)',
  `stock` int(11) DEFAULT NULL COMMENT '库存\n',
  `create_time` datetime DEFAULT NULL,
  `small_supply_price` decimal(10,2) DEFAULT NULL COMMENT '小促供货价',
  `big_supply_price` decimal(10,2) DEFAULT NULL COMMENT '大促供货价',
  `meidian_sku_id` varchar(255) DEFAULT NULL COMMENT '美店skuId',
  `sku_unique_code` varchar(100) DEFAULT NULL COMMENT 'sku唯一编码',
  `original_price` decimal(10,2) DEFAULT NULL COMMENT '原价',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci AUTO_INCREMENT=30504 COMMENT='商品sku明细表';

select
    gs.name,
    gsa.value
from tb_goods_sku_attribute gsa, tb_goods_sku gs
where find_in_set(gsa.id, (
    select group_concat(gsa.id)
    from tb_goods_sku_attribute gsa, tb_goods_sku_detail gsd
    where find_in_set(gsa.id, gsd.sku_attribute_id_list) and gsd.id = #{skuDetailId}))
      and gs.id = gsa.sku_id
`
代码是Spring+mybatis进行查询，查询的结果看起来是 and gsd.id = #{skuDetailId}这个条件被忽略后的结果。
用Mysql的client连接上查询又没有问题。

部署了3台PD和3台TiDB。
版本如下：
 Release Version: v2.0.6
Git Commit Hash: b13bc08462a584a085f377625a7bab0cc0351570
Git Branch: release-2.0
UTC Build Time: 2018-08-06 10:57:46
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

**Comment by ciscoxll** [comment]
@bobdeng Can I provide `Spring` and `mybatis` versions?

**Comment by ciscoxll** [comment]
We have encountered the same problem. please use `2.1.0-rc.4`.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
