### ISSUE TITLE
Ask for help on branch master build break

### ISSUE THREAD

**Issue by hhkbp2** [pingcap/tidb#815]
Hi,

I would like to find a start point to contribute some code. This start point should be a stable version of source code, which is better to be recent enough(to minimize the effort of merging PR back in future). I check out the master branch with currently latest commit(d64166c), but it fails to build through with errors like:

```shell
$ make
go get github.com/tools/godep
go get github.com/pingcap/go-hbase
go get github.com/pingcap/go-themis
go get github.com/ngaut/tso/client
go get github.com/qiuyesuifeng/goyacc
go get github.com/qiuyesuifeng/golex
goyacc -o /dev/null -xegen temp_parser_file parser/parser.y
Parse table entries: 323944 of 831792, x 16 bits == 647888 bytes
goyacc -o parser/parser.go -xe temp_parser_file parser/parser.y 2>&1 | egrep "(shift|reduce)/reduce" | awk '{print} END {if (NR > 0) {print "Find conflict in parser.y. Please check y.output for more information."; system("rm -f temp_parser_file"); exit 1;}}'
rm -f temp_parser_file
rm -f y.output
golex -o parser/scanner.go parser/scanner.l
godep go build
# github.com/pingcap/tidb/store/hbase
store/hbase/kv.go:192: cannot use tableName (type string) as type hbase.TableName in argument to hbase.NewTableDesciptor
store/hbase/kv.go:207: too many arguments in call to oracles.NewRemoteOracle
godep: go exit status 2
Makefile:52: recipe for target 'build' failed
make: *** [build] Error 1
```

how to find a built-through version of source code in this situation? Is there any dev workflow that should be followed?

**Comment by ngaut** [comment]
Thanks for your report. @hhkbp2 
It's a dependency issue. You may run "make update" to fix it. We will remove HBase dependency or using godeps to manage dependency later.

**Comment by qiuyesuifeng** [comment]
Sorry for that. 
You can try  `make update`,  then `make` again.
For tidb depends on `go-hbase` package which may be updated, later we will move it to Godeps workspace.

**Comment by hhkbp2** [comment]
@ngaut @qiuyesuifeng Thank you both for the quick answer. The problem solved.
