### ISSUE TITLE
Difference between TiDB 2.1 RC4 Release Notes and TiDB 2.0.8 Release Notes version

### ISSUE THREAD

**Issue by weilain** [pingcap/tidb#8155]

**Comment by shenli** [comment]
@weilain Sorry, I don't get your point.

**Comment by weilain** [comment]
Due to TIDB internal error, need to upgrade. I have this question only after seeing the release version history.

**Comment by weilain** [comment]
![image](https://user-images.githubusercontent.com/42827119/47907225-c469ed00-dec5-11e8-8a2c-6f3c9bff8a88.png)

**Comment by weilain** [comment]
Current version
Release Version: v2.0.6
Git Commit Hash: b13bc08462a584a085f377625a7bab0cc0351570
Git Branch: release-2.0
UTC Build Time: 2018-08-06 10:57:46
GoVersion: go version go1.10.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1

**Comment by winoros** [comment]
@weilain 
`2.0.6` that you current use and `2.0.8` we just released are all patch version based on `2.0`. The difference between `2.0.6` and `2.0.8` is that the latter one containing more bugfix.

`2.1` is our next release version. It has a lot of differences compared with `2.0.*`, and still in release candidate phase. We'll publish GA version soon.

So if you're in testing, you can try to upgrade to `2.1`. If you're in production, you can upgrade to `2.0.8`.

**Comment by weilain** [comment]
@winoros 
Will the online business use be affected during the upgrade process? If an error occurs during the upgrade process, it will not affect the online business.

**Comment by shenli** [comment]
@weilain You need to stop/deploy/start the cluster from 2.0.x to 2.1.x.

**Comment by shenli** [comment]
You can find the full release notes [here](https://github.com/pingcap/docs/blob/master/releases/rn.md).

**Comment by weilain** [comment]
Will the online business use be affected during the upgrade process? If an error occurs during the upgrade process, it will not affect the online business.
I need steps

**Comment by weilain** [comment]
@shenli 
need to stop/deploy/start the cluster from 2.0.x to 2.1.x.
The meaning of this sentence is not very clear

**Comment by shenli** [comment]
@weilain You cannot use rolling update when upgrading from 2.0.x to 2.1.x. So you need to stop the whole cluster first. Please refer to our document.
