### ISSUE TITLE
Version upgrade has encountered problems

### ISSUE THREAD

**Issue by weilain** [pingcap/tidb#8167]
![image](https://user-images.githubusercontent.com/42827119/47980733-f5cffc00-e103-11e8-855d-16ba90d79b7d.png)
Begging for a solution

**Comment by weilain** [comment]
Can this be solved with this method?
![image](https://user-images.githubusercontent.com/42827119/47981664-bb685e00-e107-11e8-9c1d-41517a562d3b.png)

**Comment by lysu** [comment]
@weilain Thanks for your feedback

@LinuxGit  PTAL~

**Comment by LinuxGit** [comment]
You need to update tidb-ansible. We have changed the download url.

**Comment by weilain** [comment]
Download the new TiDB-Ansible and change only the IP information of the inventory.ini file and the two variables proposed in the document.
![image](https://user-images.githubusercontent.com/42827119/48037905-55ccae00-e1a9-11e8-9385-4dd6624a2409.png)

**Comment by LinuxGit** [comment]
Yes, you need to configure inventory.ini.
If you have previously customized the configuration file of TiDB cluster components, refer to the backup file to modify the corresponding configuration file in /home/tidb/tidb-ansible/conf.
