### ISSUE TITLE
memory leak when preparing data

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#8195]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
i used sysbench's prepare script to insert data to database.

2. What did you expect to see?
memory should not keep growing.

3. What did you see instead?
memory keep growing.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
commit 6ccfec6d2e66a880931abde9b97ad0387091558e (origin/master, origin/HEAD)
Author: Jack Yu <yusp@pingcap.com>
Date:   Tue Nov 6 11:25:11 2018 +0800

**Comment by ngaut** [comment]
mem profile:

go tool pprof http://127.0.0.1:10081/debug/pprof/heap
Fetching profile over HTTP from http://127.0.0.1:10081/debug/pprof/heap
Saved profile in /Users/max/pprof/pprof.alloc_objects.alloc_space.inuse_objects.inuse_space.009.pb.gz
Type: inuse_space
Time: Nov 6, 2018 at 1:32pm (CST)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top30 -cum
Showing nodes accounting for 4576.91MB, 96.72% of 4732.23MB total
Dropped 163 nodes (cum <= 23.66MB)
Showing top 30 nodes out of 37
      flat  flat%   sum%        cum   cum%
         0     0%     0%  4620.51MB 97.64%  github.com/pingcap/tidb/server.(*Server).onConn
         0     0%     0%  4618.99MB 97.61%  github.com/pingcap/tidb/server.(*clientConn).Run
         0     0%     0%  4618.33MB 97.59%  github.com/pingcap/tidb/session.(*session).Execute
         0     0%     0%  4618.33MB 97.59%  github.com/pingcap/tidb/session.(*session).execute
         0     0%     0%  4616.33MB 97.55%  github.com/pingcap/tidb/server.(*TiDBContext).Execute
         0     0%     0%  4615.82MB 97.54%  github.com/pingcap/tidb/server.(*clientConn).dispatch
         0     0%     0%  4615.82MB 97.54%  github.com/pingcap/tidb/server.(*clientConn).handleQuery
         0     0%     0%  4604.26MB 97.30%  github.com/pingcap/tidb/session.(*session).executeStatement
         0     0%     0%  4604.26MB 97.30%  github.com/pingcap/tidb/session.runStmt
         0     0%     0%  3835.04MB 81.04%  github.com/pingcap/tidb/kv.WalkMemBuffer
 3832.87MB 80.99% 80.99%  3832.87MB 80.99%  github.com/pingcap/goleveldb/leveldb/memdb.(*DB).Put
         0     0% 80.99%  3832.87MB 80.99%  github.com/pingcap/tidb/kv.(*memDbBuffer).Set
         0     0% 80.99%  3832.56MB 80.99%  github.com/pingcap/tidb/session.(*session).StmtCommit
         0     0% 80.99%  3831.46MB 80.97%  github.com/pingcap/tidb/kv.(*lazyMemBuffer).Set
         0     0% 80.99%  3831.46MB 80.97%  github.com/pingcap/tidb/kv.(*unionStore).Set
         0     0% 80.99%  3831.46MB 80.97%  github.com/pingcap/tidb/session.(*session).StmtCommit.func1
         0     0% 80.99%  3831.46MB 80.97%  github.com/pingcap/tidb/store/tikv.(*tikvTxn).Set
         0     0% 80.99%   750.25MB 15.85%  github.com/pingcap/tidb/session.(*TxnState).Commit
         0     0% 80.99%   750.25MB 15.85%  github.com/pingcap/tidb/session.(*session).CommitTxn
         0     0% 80.99%   750.25MB 15.85%  github.com/pingcap/tidb/session.(*session).doCommit
         0     0% 80.99%   750.25MB 15.85%  github.com/pingcap/tidb/session.(*session).doCommitWithRetry
         0     0% 80.99%   750.25MB 15.85%  github.com/pingcap/tidb/store/tikv.(*tikvTxn).Commit

**Comment by tiancaiamao** [comment]
With `latch` enabled ? master branch enable it by default. @ngaut 
There is a known issue for `latch` and here is the fix https://github.com/pingcap/tidb/pull/8186
Try to disable `latch` and test again, or wait for the fix.

**Comment by shenli** [comment]
@ngaut It is fixed already. Please try the latest master.
