### ISSUE TITLE
TIDB-SERVER START BUG

### ISSUE THREAD

**Issue by dbaspace** [pingcap/tidb#8208]
集群启动 无任何报错，TIDB-SERVER 提示日志
2018/11/07 09:48:26.076 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 646.734µs
2018/11/07 09:48:26.077 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.126 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 724.391µs
2018/11/07 09:48:26.127 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.176 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 747.118µs
2018/11/07 09:48:26.177 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.226 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 682.834µs
2018/11/07 09:48:26.227 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.276 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 669.526µs
2018/11/07 09:48:26.277 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.326 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 741.901µs
2018/11/07 09:48:26.327 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.376 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 688.46µs
2018/11/07 09:48:26.377 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.426 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 700.28µs
2018/11/07 09:48:26.427 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.476 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 743.678µs
2018/11/07 09:48:26.477 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:48:26.526 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 839.494µs
2018/11/07 09:48:26.527 domain.go:309: [info] [ddl] full load and reset schema validator.

**Comment by dbaspace** [comment]
018/11/07 09:32:44.296 tidb.go:291: [info] new store
2018/11/07 09:32:44.296 client.go:114: [info] [pd] create pd client with endpoints [192.168.21.190:2379 192.168.21.189:2379 192.168.21.187:2379]
2018/11/07 09:32:44.307 client.go:212: [info] [pd] leader switches to: http://192.168.21.187:2379, previous:
2018/11/07 09:32:44.307 client.go:133: [info] [pd] init cluster id 6620923188373486642
2018/11/07 09:32:44.315 tidb.go:64: [info] store tikv-6620923188373486642 new domain, ddl lease 100ms, stats lease 3000000000
2018/11/07 09:32:44.315 ddl.go:287: [info] [ddl] start delRangeManager OK, with emulator: false
2018/11/07 09:32:44.317 ddl.go:294: [info] [ddl] start DDL:b9fc4dc3-29a2-4c6d-9ef6-785a372f6b70
2018/11/07 09:32:44.323 domain.go:117: [info] [ddl] full load InfoSchema from version 0 to 0, in 891.882µs
2018/11/07 09:32:44.324 domain.go:309: [info] [ddl] full load and reset schema validator.
2018/11/07 09:32:44.324 tidb.go:182: [info] RollbackTxn for ddl/autocommit error.
2018/11/07 09:32:44.324 txn.go:201: [info] [kv] Rollback txn 404109227274797061
2018/11/07 09:32:44.325 session.go:727: [warning] [0] session error:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:99: [schema:1049]Unknown database 'mysql'
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:92:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:52:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:291:
/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/tidb.go:199:
{
  "currDBName": "",
  "id": 0,
  "status": 2,
  "strictMode": true,
  "user": null
}
2018/11/07 09:32:44.325 session.go:804: [warning] [0] compile error:
[schema:1146]Table 'mysql.tidb' doesn't exist
SELECT VARIABLE_VALUE FROM mysql.tidb WHERE VARIABLE_NAME="bootstrapped"
2018/11/07 09:32:44.325 session.go:1662: [info] [CRUCIAL OPERATION] CREATE DATABASE IF NOT EXISTS test (by <nil>).
2018/11/07 09:32:44.340 ddl.go:428: [info] [ddl] start DDL job ID:2, Type:create schema, State:none, SchemaState:none, SchemaID:1, TableID:0, RowCount:0, ArgLen:1, start time: 2018-11-07 09:32:44.299 +0800 CST, Query:CREATE DATABASE IF NOT EXISTS test

**Comment by zimulala** [comment]
@dbaspace 
What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by shenli** [comment]
@dbaspace Please keep the issue template and fill it. Thanks!

**Comment by tisonkun** [comment]
closed as no response. @dbaspace feel free to open a new issue following the issue template if the question is still there.
