### ISSUE TITLE
Create table alway failed from syncer(mysql to proxysql + tidb) 

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#8219]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Sync data from mysql to tidb. Proxysql was set upon tidb. 

syncer failed for 
```
2018/11/07 17:32:51 db.go:94: [warning] sql stmt_exec retry 16: [USE `nash`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;] - [[]]
2018/11/07 17:33:04 db.go:121: [error] exec sqls[[USE `nash`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;]] begin failed Error 1105: line 1 column 10 near "`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`" (total length 253)
```
tidb error log

```
2018/11/07 17:36:22.038 session.go:808: [warning] [con:154] parse error:
line 1 column 10 near "`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`" (total length 253)
use ``nash`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`
```

2. What did you expect to see?

action success

3. What did you see instead?

failure

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

2.0.4

Seems like interop issue between syncer and proxysql. When I run syncer without proxysql, the work completed successfully. the log looks like

```
2018/11/07 17:58:17.536 session.go:1399: [info] [CRUCIAL OPERATION] [con:199]  CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8; (by root@10.23.13.27).
2018/11/07 17:58:17.545 session.go:976: [info] [con:199] NewTxn() inside a transaction auto commit: 404117178945372164
2018/11/07 17:58:17.555 ddl.go:436: [info] [ddl] start DDL job ID:116, Type:create table, State:none, SchemaState:none, SchemaID:113, TableID:115, RowCount:0, ArgLen:1, start time: 2018-11-07 

17:58:17.515 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0, Query: CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
2018/11/07 17:58:18.091 domain.go:102: [info] [ddl] diff load InfoSchema from version 47 to 48, in 2.39617ms
2018/11/07 17:58:18.557 ddl.go:468: [info] [ddl] DDL job 116 is finished
2018/11/07 17:58:18.557 domain.go:412: [info] [ddl] on DDL change, must reload
2018/11/07 17:58:18.559 adapter.go:353: [warning] [SLOW_QUERY] cost_time:1.022094042s succ:true connection_id:199 txn_start_ts:404117178945372167 database:nash table_ids:[] index_ids:[] sql: CREATE 

TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
2018/11/07 17:58:33.673 server.go:303: [info] [con:200] new connection 10.23.67.26:41522
2018/11/07 17:58:33.674 server.go:305: [info] [con:200] close connection
2018/11/07 17:58:34.284 server.go:303: [info] [con:201] new connection 10.23.189.166:47574
2018/11/07 17:58:34.284 server.go:305: [info] [con:201] close connection

```

**Comment by lamxTyler** [comment]
PTAL @csuzhangxc

**Comment by csuzhangxc** [comment]
@CrazyNash what original statement did you executed in upstream MySQL?

**Comment by CrazyNash** [comment]
@csuzhangxc  

```
create database nash;

use nash;

CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

```

**Comment by csuzhangxc** [comment]
does multi statements support enabled in proxysql?

**Comment by shenli** [comment]
@CrazyNash I guess TiDB did get the correct SQL statement. It is started with "**`;**".

```sql
`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8`
```

**Comment by CrazyNash** [comment]
@csuzhangxc not sure how to check, I can't find any related configuration field. Do you have any idea?

**Comment by csuzhangxc** [comment]
@CrazyNash 
In syncer, we append a `USE database-name;` statement before SQLs need to sync as you see above.

So, at first I guess this may be caused because ProxySQL not enable multi statements **for both backends and frontends**.
 
It seems the recent version of ProxySQL have enable this **for backends**, ref #sysown/proxysql/issues/100 and https://proxysql.com/blog/releasing-proxysql-149

Then I test with _enable or not enable_ multi statements in syncer, but I got the same error (`Error 1105` as you have got). But it's differ from the error with not enable multi statements in syncer to MySQL (`Error 1064`).

So, I suspect that ProxySQL may do some conversion incorrectly for multi statements **for frontends** (syncer in this case). But I not familiar with ProxySQL, and have not dig into with this.

Our syncer was designed for TiDB, and it not well tested with other downstream server.

Why do you need to add ProxySQL upon TiDB? and is it necessary?

**Comment by csuzhangxc** [comment]
@CrazyNash 
UPDATED!

I test the case `MySQL -> syncer -> ProxySQL -> MySQL`, got another error
```
2018/11/10 20:42:10 db.go:141: [error] exec sqls[[USE `nash`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;]] commit failed Error 1102: Incorrect database name '`nash`; CREATE TABLE `t_test_test_test_test_test` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black'
```

it seems ProxySQL send incorrect statement to downstream, which make database name in `USE` **plus the second statement** as a whole database name.

have you test some thing like `USE ***; CREATE TABLE ***;` with ProxySQL in application?
(application -> ProxySQL -> MySQL)

**Comment by CrazyNash** [comment]
@csuzhangxc thank you for your quick update.  I didn't test with that setup, but I did test in (app --> proxySQL --> TiDB), and it worked very well.

**Comment by csuzhangxc** [comment]
@CrazyNash in you test with  (app --> proxySQL --> TiDB), where has 
added`USE **;`  before `CREATE TABLE ***` ?

**Comment by CrazyNash** [comment]
@csuzhangxc Just did another test 

[root@10-23-13-27 ~]# mysql -h XXXX -P 10068 -pXXXX -e "use 'nash33'; create table 't_test2'('id' int(11), 'black_api_name' int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8;"
ERROR 1105 (HY000) at line 1: line 1 column 22 near "('id' int(11), 'black_api_name' int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8" (total length 96)

error log from proxysql
```
2018-11-12 17:03:22 MySQL_Session.cpp:2863:handler(): [WARNING] Error during query on (0,10.23.86.229,10074): 1105, line 1 column 22 near "('id' int(11), 'black_api_name' int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8" (total length 96)
```
error log from tidb
```
2018/11/12 17:03:22.409 session.go:808: [warning] [con:529] parse error:
line 1 column 22 near "('id' int(11), 'black_api_name' int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8" (total length 96)
create table 't_test2'('id' int(11), 'black_api_name' int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8
```

HOWEVER, when I drop single quote mark from filed name, it worked.
```
[root@10-23-13-27 ~]# mysql -h XXX -P 10068 -pXXX -e "use 'nash33'; create table t_test2(id int(11), black_api_name int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8;"
```

So seems like an issue from single quote mark upon field name. Can you drop the single quote mark when generating sql statement from syncer?

**Comment by CrazyNash** [comment]
@csuzhangxc Aha, my mistake 

```
[root@10-23-13-27 ~]# mysql -h XXX -P 10068 -pXXX -e "USE `nash33`; CREATE TABLE `t_test3`(`id` int(11), `black_api_name` int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8;"
-bash: nash33: command not found
-bash: t_test3: command not found
-bash: black_api_name: command not found
ERROR at line 1: USE must be followed by a database name
ERROR 1105 (HY000) at line 1: line 1 column 14 near "uid=0(root) gid=0(root) groups=0(root) int(11),  int(11))ENGINE=InnoDB DEFAULT CHARSET=utf8" (total length 105)

```

this time, bash was upset by the \`, anyway I think ` is the culprit here, can you try to drop the mark from syncer and have a try?

**Comment by csuzhangxc** [comment]
@CrazyNash 
two things.
1. we can not drop this marker ( **`** ), because we need to handle such a case  
	- database `nash.db` (not `nash` database for `db` table)
	- table name `nash.table`.
	- if we drop the marker, table name combine with database name will become `nash.db.nash.table`. now we do not know how to split this to database name and table name back (maybe `nash` database for `db.nash.table` table and some others)
2. for you case where can not use **`** in bash, maybe you can test it with any other programing language

**Comment by CrazyNash** [comment]
@csuzhangxc I did following tests for this:

```
USE `nash`; CREATE TABLE `t_test25` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

```
## go app --> proxysql + tidb

interesting, "database/sql" driver returned success, but I can't find the table from DB, proxysql log is very clean. Regardless &multiStatements=true was set or not.

## go app --> mysql

There is an error without &multiStatements=true from connection string.
After &multiStatements=true was added, same test completed successfully, and I can find the table from DB.

So this is for sure proxysql issue. However if syncer could split USE out CREATE statement I believe it would work, can you think about this?

### what we can refer to 

* for mysqldump, it doesn't use USE statement, as the sql file named with DB name.
* for binglog, yes we can refer to binlog, it writes a USE statement when database changed.

```
use `nash`/*!*/;
SET TIMESTAMP=1542024726/*!*/;
CREATE TABLE `t_test25` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!*/;

```

**Comment by csuzhangxc** [comment]
@CrazyNash 
> So this is for sure proxysql issue. However if syncer could split USE out CREATE statement I believe it would work, can you think about this?

do you mean, split
```
USE `nash`; CREATE TABLE `t_test25` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

to 

```
USE `nash;`
```

with 

```
CREATE TABLE `t_test25` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `black_api_name` varchar(64) NOT NULL DEFAULT '',
  `create_time` int(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by CrazyNash** [comment]
@csuzhangxc this looks good to me, thank you for your kind support.

**Comment by CrazyNash** [comment]
we really need this to be fixed, can you reconsider this feature request? or tell me where is the code to change then I can have a try?
