### ISSUE TITLE
No error returned when insert statement fails due to unique index

### ISSUE THREAD

**Issue by teodor-pripoae** [pingcap/tidb#822]
Hi,

I have the following code using gorm:

```go
package main

import (
	"fmt"
	"os"

	_ "github.com/go-sql-driver/mysql"
	"github.com/jinzhu/gorm"
)

// Account keeps accounts in the database
type Account struct {
	gorm.Model
	Email string `sql:"type:varchar(100);not null;unique_index"`
}

func logExit(msg string, err error) {
	fmt.Printf("Error: %s, %v\n", msg, err)
	os.Exit(1)
}

func main() {
	url := "root:@tcp(192.168.99.100:3306)/testdb?charset=utf8&parseTime=True&loc=Local"
	db, err := gorm.Open("mysql", url)
	if err != nil {
		logExit("Error connecting to db", err)
	}

	db.AutoMigrate(&Account{})

	account := Account{Email: "fooaaa@gmail.com"}

	if err := db.Create(&account).Error; err != nil {
		logExit("Error in first insert", err)
	} else {
		fmt.Printf("No error for first insert\n")
	}

	account = Account{Email: "fooaaa@gmail.com"}

	if err := db.Create(&account).Error; err != nil {
		logExit("Error in second insert", err)
	} else {
		fmt.Printf("No error for second insert\n")
	}
}
```

First time, the value is inserted and all works fine. Second time the value is not inserted, but no error is returned. If I'm using mysql, I get the following error:

```
No error for first insert

(Error 1062: Duplicate entry 'fooaaa@gmail.com' for key 'uix_accounts_email')
[2016-01-04 05:52:52]
Error: Error in second insert, Error 1062: Duplicate entry 'fooaaa@gmail.com' for key 'uix_accounts_email'
exit status 1
```

If I'm using tidb: 

```
No error for first insert
No error for second insert
```

Logs:

```
2016/01/04 03:53:43 session.go:393: [warning] session:{
  "currDBName": "testdb",
  "sid": 3
}, err:[kv:3]key already exist
2016/01/04 03:53:43 conn.go:240: [error] dispatch error [kv:3]key already exist
/opt/goworkspace/src/github.com/pingcap/tidb/kv/union_store.go:179:
/opt/goworkspace/src/github.com/pingcap/tidb/store/localstore/txn.go:88:
/opt/goworkspace/src/github.com/pingcap/tidb/store/localstore/txn.go:111:
/opt/goworkspace/src/github.com/pingcap/tidb/session.go:175:
/opt/goworkspace/src/github.com/pingcap/tidb/tidb.go:181:
/opt/goworkspace/src/github.com/pingcap/tidb/session.go:394:
/opt/goworkspace/src/github.com/pingcap/tidb/tidb-server/server/conn.go:367: , conn: 192.168.99.1:50566, status: 2, charset: utf8, user: root, lastInsertId: 2
2016/01/04 03:53:43 conn.go:241: [error] cmd: COMMIT
2016/01/04 03:53:43 server.go:156: [info] close conn: 192.168.99.1:50566, status: 2, charset: utf8, user: root, lastInsertId: 2
```

**Comment by shenli** [comment]
@teodor-pripoae Thanks for your report. We will work on this.

**Comment by teodor-pripoae** [comment]
Thank you very much for your quick answer ! If it is an easy fix I'll be glad to help with a PR.

I think something is wrong with the wire response and gorm is not detecting it.

**Comment by shenli** [comment]
Great!
I go through TiDB source code and make sure that we return the same error code as MySQL for duplicate entry error (1062). So I suspect that gorm judge error no only by error code.

**Comment by shenli** [comment]
@teodor-pripoae We find there is a bug in gorm. It ignores error of db.Commit(). See https://github.com/jinzhu/gorm/blob/master/scope.go#L383
In TiDB duplicate entry is checked at commit stage, so the error is logged at TiDB log but ignored by gorm.
We are going to send a PR to gorm.

Thanks!

**Comment by ngaut** [comment]
@teodor-pripoae It should be fixed. Please update your gorm and check again. Thanks.

**Comment by teodor-pripoae** [comment]
Yes. It is fixed. Thank you ! But it doesn't say which key is duplicate. It will be difficult to debug which key is the problem.

Will it work after [this PR](https://github.com/pingcap/tidb/pull/631) will be merged ? 

```
No error for first insert
Error: Error in second insert, Error 1062: key already exist
exit status 1
```

**Comment by shenli** [comment]
@teodor-pripoae That pr will not work.
TiDB use lazy check for unique index. https://github.com/pingcap/tidb/blob/master/kv/kv.go#L21
The job is finished at commit stage by the storage layer for performance consideration(We want to check duplication in a batch way). 
The interface between sql layer and storage layer is not rich enough to pass information such as index name and original key data (we only got encoded key at storage layer). So we do not get enough information about which key is duplicate at the place where the error rise.

We will figure out how to show rich information in the error message recently. Thanks!

**Comment by shenli** [comment]
@teodor-pripoae We find a way to solve this. See the PR above please.

**Comment by teodor-pripoae** [comment]
Thank you !
