### ISSUE TITLE
inactive connections should be closed after `wait_timeout`

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#8245]
## Bug Report

Currently TiDB doesn't close a connection automatically, however if the client was down or something goes wrong, some connections are turned to be idle forever, which should be closed.

MySQL use the variable `wait_timeout` to define the number of seconds the server waits for activity on a non-interactive connection before closing it. We can follow this behavior as well.

For more detail, see: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_wait_timeout

**Comment by jackysp** [comment]
When the client is down or something goes wrong, some connections will not turned to be idle forever, unless `tcp-keep-alive = false`
I've tested it manually when `tcp-keep-alive = true`
1. start 1000 sysbench threads to bench the TiDB
1. kill -9 sysbench before the test finish
1. check the connection number in the grafana

![image](https://user-images.githubusercontent.com/4352397/48248137-144e3400-e431-11e8-9b22-c16737648368.png)

**Comment by jackysp** [comment]
Anyway, MySQL variable `wait_timeout` could be supported in TiDB.

**Comment by morgo** [comment]
For MySQL compatibility, there are actually two settings: `wait_timeout` and `interactive_timeout`.

Interactive applies to command line clients etc.  Anything that sets the interactive 'bit' in the client protocol.

**Comment by hhxcc** [comment]
I will try to do this.

**Comment by morgo** [comment]
Support for `wait_timeout` has been added, so I am going to close this issue now.  Support for `interactive_timeout` can be tracked in https://github.com/pingcap/tidb/issues/8487
