### ISSUE TITLE
Do we have any plan to implement a feature like MySQL performance_schema?

### ISSUE THREAD

**Issue by nieyy** [pingcap/tidb#825]
If we do have, maybe we can discuss the design, or if you don't have, we are interesting to do so and contribute.

Any suggestions?

**Comment by ngaut** [comment]
@nieyy Good idea. 
Yes, we have plan to do that. But we haven't started yet.
And we are happy to  discuss the design :)

**Comment by nieyy** [comment]
@ngaut Great, we have just finished the integration of TiDB and our own storage (thanks for your doc), generally saying we are going to work on performance optimizations next, thus we need performance_schema first to help to diagnose performance issues.

We have started to look into it, and will submit more ideas later, and we hope we can work together and do more essential contribution besides built-in functions.

**Comment by ngaut** [comment]
@nieyy Glad to hear that. Currently we are working on optimizing query plan (condition push down, parallel executing and even more). Obviously we need more and more help to make TiDB better. And welcome to join the technical party.

**Comment by nieyy** [comment]
@ngaut , condition push down and SMP (parallel execution) are two big topics, we are also planning to do so, glad to hear that ur guys already working on that, :+1:
