### ISSUE TITLE
How to prevent tidb server out of memory

### ISSUE THREAD

**Issue by club-hong** [pingcap/tidb#8254]
Detecting expensive SQL consumption memory is about 250MB
Obtained by the mem-quota-query=262144000  parameter

Detailed log：
2018/11/09 18:06:05.089 action.go:44: [warning] [executor:8001]SELECT
	id,
	source,
	source_name,
	target,
	target_name,
	original,
	create_time
FROM
	im_chat_message
WHERE
	chat_type = 1
ORDER BY
	create_time DESC
LIMIT 2000000,50
LIMIT 2534150,50 holds 262152768B memory, exceeds threshold 262144000B.
"SELECT
	id,
	source,
	source_name,
	target,
	target_name,
	original,
	create_time
FROM
	im_chat_message
WHERE
	chat_type = 1
ORDER BY
	create_time DESC
LIMIT 2000000,50
LIMIT 2534150,50"{
  "quota": 250 MB
  "consumed": 250.00836181640625 MB
  "TopN_10"{
    "quota": 32 GB
    "consumed": 250.00836181640625 MB
    "rowChunks"{
      "consumed": 234.74273681640625 MB
    }
  }
}

A lot of expensive SQL causes the entire cluster to crash，all tidb-server memory cgroup out of memory

How to prevent tidb server out of memory？

Is there any parameter that can be controlled?
How to configure it, 
So that when new memory is low
other new query requests are waiting

**Comment by zz-jason** [comment]
@qw303374929 Sorry for the inconvenient, TiDB only has a simple memory control for now. That is, you can config the `oom-action = "cancel"`. With this configuration, the query runs out of memory quota can be cancelled.

**Comment by qw303374929** [comment]
@zz-jason How much is the appropriate setting, expensive SQL is not executed?
How do large page queries in the example optimize memory usage?

**Comment by zz-jason** [comment]
@qw303374929 It's depends on the query and system resource, hope this doc can help you: https://github.com/pingcap/docs/blob/master/sql/tidb-memory-control.md

**Comment by qw303374929** [comment]
i don't know how to set it up 
because the memory consumed by each SQL is different.
business is hybrid.
if the limit setting is small, some services will be crashed.
if the setting is large, it will affect the concurrency.


i think TiDB should use code to control memory usage and concurrency, just like MySQL

**Comment by zz-jason** [comment]
@qw303374929 For memory control, we're planning to spill to disk if the memory consumption exceeds a certain threshold.

As for the concurrency control, what problem did you encounter?

**Comment by qw303374929** [comment]
i have not set concurrency control
but expensive SQL currently makes me OOM,   as explained in the problem
i am looking for a solution

spill to disk which version will be implemented in the future?

**Comment by qw303374929** [comment]
when I use mydumper tools to export Tidb data, both TiDB and TiKV are OOM.
the largest number of table data rows is about 20 million rows.

What tools should I use for TiDB database full backup?

**Comment by shenli** [comment]
@qw303374929 What is the hardware of your machine? Especially the RAM.
You can try to reduce the thread number of mydumper.

**Comment by qw303374929** [comment]
test the machine memory on the cluster as 8G
if I use a 16G memory machine, does it mean that I can only export 40 million, 32G 80 million?


copy the command on the pingcap website
the number of thread is 16

**Comment by zz-jason** [comment]
@qw303374929 You can use both `-t` and `-F` options to limit the memory consumption. Take the command in https://github.com/pingcap/docs/blob/master/op-guide/backup-restore.md#backup-data-from-tidb as an example:

```
./bin/mydumper -h 127.0.0.1 -P 4000 -u root -t 16 -F 64 -B test -T t1,t2 --skip-tz-utc -o ./var/test
```

**Comment by shenli** [comment]
Please follow the [hardware recommendation](https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md).

**Comment by qw303374929** [comment]
@zz-jason thank you, I will try.
currently, the method of controlling TiDB memory is only set TiDB Specific System Variables??
is there any other way?

**Comment by zz-jason** [comment]
@qw303374929 For TiDB version >= 2.0, the memory quota for a query can also be set in the config file. Take this as an example: https://github.com/pingcap/tidb/blob/master/config/config.toml.example#L39

The document should be updated, sorry for the inconvenient.

**Comment by denghuancong** [comment]
we also  met this problem , mydump is crash , and tidb-server oom

**Comment by club-hong** [comment]
@denghuancong  You can use both -t and -F options to limit the memory consumption

**Comment by denghuancong** [comment]
we set the oom-aciton to cancel, but backup problem isn't resolve, mydumper is crash anyway, we use -t 16 -F 64

**Comment by club-hong** [comment]
can try `-t 1 -F 64`

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to open a new issue if you are still experiencing problems. Thanks!
