### ISSUE TITLE
Question: how to connect the multi-node cluster from MySQL client?

### ISSUE THREAD

**Issue by AkihiroSuda** [pingcap/tidb#826]
Is it possible to connect the multi-node TiDB cluster from MySQL client?

In Apache Phoenix, we can use a JDBC string like `"jdbc:phoenix:zookeeperserver1,zookeeperserver2:3333"` to connect the multi-node cluster from JDBC client.
Is there something like this for TiDB?

**Comment by shenli** [comment]
Thanks for your feedback! @AkihiroSuda 
In TiDB's design, we  have a load balancer between client and tidb node. https://github.com/pingcap/tidb/blob/master/docs/architecture.png

You can use a load balancer such as LVS to connect to TiDB cluster.

**Comment by AkihiroSuda** [comment]
@shenli, Thanks for the quick anser!
