### ISSUE TITLE
Configuration requirements are so high, the club's official website can Tidb, kv, pd is deployed in a 16 GB of memory on the server to save costs?

### ISSUE THREAD

**Issue by zhuxiujia** [pingcap/tidb#8266]
Configuration requirements are so high, the club's official website can Tidb, kv, pd is deployed in a 16 GB of memory on the server to save costs?

**Comment by lamxTyler** [comment]
@zhuxiujia Yes, and you can try it using [docker compose](https://github.com/pingcap/docs/blob/master/op-guide/docker-compose.md).

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
