### ISSUE TITLE
tikv is busy when sqoop 10 millions records

### ISSUE THREAD

**Issue by cnwarden** [pingcap/tidb#8267]
when using Sqoop export data to tidb for query, we found **tikv is busy**, do we need any parameters to start this job?

**Comment by lamxTyler** [comment]
@cnwarden Yes, it means tikv has reached its limit of processing queries. You can limit the concurrency of sqoop or `token-limit` of tidb.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
