### ISSUE TITLE
OOM falure when use mydumper for backup database on tidb

### ISSUE THREAD

**Issue by AlexNewTao** [pingcap/tidb#8271]
when i use mydumper backup databases in tidb, oom mistake happend ；

the log is 
```
215190:{"log":"2018/11/12 03:19:46.061 adapter.go:353: 
[warning] [SLOW_QUERY] cost_time:17.063465542s succ:true connection_id:0 txn_start_ts:404216602716012545 database: table_ids:[29]
index_ids:[] sql:select table_id, is_index, hist_id, distinct_count, version, null_count, cm_sketch, tot_col_size from mysql.stats_histograms\n","stream":"stderr","time":"2018-11-11T19:19:46.062151108Z"}

```
the system log is 

```
kernel: mydumper[3623]: segfault at 10 ip 0000000000425e67 sp 00007fe92fffec90 error 4 in mydumper[400000+33b000]
```

**Comment by lamxTyler** [comment]
Thanks for your feedback.
PTAL @csuzhangxc

**Comment by csuzhangxc** [comment]
@AlexNewTao 
can you provide more information like:
1. mydumper version (and `maxbube/mydumper` or `pingcap/mydumper`)
2. TiDB version
3. mydumper config
4. any other useful info

**Comment by AlexNewTao** [comment]
actual the problem was related to this issue:
https://github.com/pingcap/tidb/issues/8254

lets discuss in this issue
