### ISSUE TITLE
when use mydumper，this tool occured some problem about Couldn't generate @@tidb_snapshot

### ISSUE THREAD

**Issue by dualc** [pingcap/tidb#8284]
## Question
when use mydumper，it occured some problem as below
CRITICAL **: Couldn't generate @@tidb_snapshot: line 1 column 11 near " STATUS" (total length 18) 
I dont understand what it means

**Comment by csuzhangxc** [comment]
@dualc 
can you provide more information?
1. mydumper version (and maxbube/mydumper or pingcap/mydumper)
2. MySQL / TiDB version (are you dump from MySQL or TiDB)
3. mydumper config
4. any other useful info

**Comment by dualc** [comment]
@csuzhangxc 
mydumper 0.9.5, built against MySQL 5.7.23，which is tidb version，tidb version is Release Version:  v2.0.0-rc.1，before i dumped data from tidb，we have written some data to tidb，but we have stop it now，it still can't dump。
dump config as below：
tidb-enterprise-tools-latest-linux-amd64/bin/mydumper  -l 120 -h xxx  -P 4000 -u xxx -t 16 -F 64 -B xxx -T ${line} -o /data/disk01/table/${line} 。

**Comment by csuzhangxc** [comment]
@dualc 
I think you TiDB (version v2.0.0-rc.1) do not support to be dumped with this mydumper.
you can test this with `SHOW MASTER STATUS` in TiDB.

for PRs in TiDB to support this, you can ref: https://github.com/pingcap/tidb/pull/6785, https://github.com/pingcap/tidb/pull/6842

**Comment by dualc** [comment]
@csuzhangxc 
thanks,get it，but I confused why when we used earlier version，it supported it

**Comment by csuzhangxc** [comment]
@dualc 
you mean, you used an earlier mydumper version?
maybe you can ref this: https://github.com/pingcap/mydumper/pull/8

**Comment by morgo** [comment]
cc @kennytm - I chatted to @shenli and we should add a parsable version so clients can check the server they are connected to.  https://github.com/pingcap/tidb/issues/7736

**Comment by kennytm** [comment]
Oh I've implemented the parsing in Lightning as well (PR 67 if you wanna check). I like the function to directly obtain the semver, though it would only be available on 2.1+. 

BTW we could skip the snapshot by passing `-z ''` to mydumper.
