### ISSUE TITLE
Self-tuning database

### ISSUE THREAD

**Issue by joelchen** [pingcap/tidb#829]
Is self-tuning feature possible in TiDB like in [Concourse][1], removing the need for database configurations?
[1]: https://github.com/cinchapi/concourse

**Comment by shenli** [comment]
@joelchen Thanks for your advice!
Concourse has many interesting features. And some of the features are already supported by TiDB such as ACID transaction, Query data from the past. 
But currently we will focus on OLTP. Automatic Indexing and Schemaless are not on our roadmap.

**Comment by joelchen** [comment]
The goal is to optimize performance as the data evolves over time, and cut time spent on database administration with automation.

**Comment by shenli** [comment]
TiDB support online schema change. DBAs can modify schema and index without downtime. I think DBA managed schema (including index) is more suitable for enterprise usage. 
Self-tuning is an attractive feature, but it may bring more uncertainty. For example automatic indexing may cause more space usage and slow down insert/update/delete operations. And schemaless is convenient sometimes but it may also cause error-prone codes.

So it is not on our plan now. But TiDB is involving rapidly. We will keep eyes on Concourse and learn from it. Maybe we will provide similar feature in the future. Thanks!
