### ISSUE TITLE
Why the kvcache.SimpleLRUCache doesn't have lock?

### ISSUE THREAD

**Issue by klkyy** [pingcap/tidb#8294]
## Question
我看到你们实现的[simple_lru.go](https://github.com/pingcap/tidb/blob/master/util/kvcache/simple_lru.go)中实现了lru的cache，想问一下并发put的时候没有问题吗？

**Comment by zz-jason** [comment]
@klkyy It's not thread safe: https://github.com/pingcap/tidb/blob/master/util/kvcache/simple_lru.go#L35

**Comment by klkyy** [comment]
ok
