### ISSUE TITLE
mockstore: return copTask execution info for explain analyze

### ISSUE THREAD

**Issue by lysu** [pingcap/tidb#8300]
## Feature Request

**Is your feature request related to a problem? Please describe:**

current explain analyze result doesn't contain copTask's execution info, we need impl that in mockstore first, then port it to tikv

**Describe the feature you'd like:**

collect execution in mockstore and piggyback to tidb

**Comment by qw4990** [comment]
It seems that this issue has already resolved by this [PR](https://github.com/pingcap/tidb/pull/9057/files#diff-b7776f772f76c1be90188fa55fc7988eR224);
