### ISSUE TITLE
compatibility with schemaspy

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#8303]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

I created foreign keys that show up in the information schema and then ran schema spy

``` bash
#!/usr/bin/env bash
set -euo pipefail

mkdir -p doc/schema
sudo chown -R 1000:1000 doc/schema/
./scripts/docker -v "$PWD/doc/schema:/output" schemaspy/schemaspy -u root -db <database> -t mysql -port 4000 -host <host> -s <schema>
sudo chown -R $(whoami):$(whoami) doc/schema/
```

Foreign keys show up with this query:

```
 SELECT 
    ->   TABLE_NAME,COLUMN_NAME,CONSTRAINT_NAME, REFERENCED_TABLE_NAME,REFERENCED_COLUMN_NAME
    -> FROM
    ->   INFORMATION_SCHEMA.KEY_COLUMN_USAGE
    -> WHERE
    ->   REFERENCED_TABLE_SCHEMA = '<database>' AND
    ->   REFERENCED_TABLE_NAME = 'clusters';
```

2. What did you expect to see?

Entity relations at relationships.html

3. What did you see instead?

All Relationships
×
 Missed Relationships!
No relationships were detected in the schema.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

pingcap/tidb:v2.1.0-rc.4

**Comment by gregwebs** [comment]
Is there a general query log in TiDB or a debug level setting that would show all queries?

**Comment by gregwebs** [comment]
Thanks, that is quite helpful! I didn't see it with a quick google search, but it is probably in our docs somewhere already.

Schema Spy does not appear to query the information schema for foreign keys (which is a bit odd because it queries that for other things). It does run `SHOW CREATE TABLE` which also seems odd. I am creating my foreign keys after the tables are created. So this might be the issue.

So this seems like a bug in Schema Spy for not using the information schema. I will look for a different diagramming tool...

```
/* mysql-connector-java-6.0.6 ( Revision: 3dab84f4d9bede3cdd14d57b99e9e98a02a5b97d ) */SELECT  @@session.auto_increment_increment AS auto_increment_increment, @@character_set_client AS character_set_client, @@character_set_connection AS character_set_connection, @@character_set_results AS character_set_results, @@character_set_server AS character_set_server, @@init_connect AS init_connect, @@interactive_timeout AS interactive_timeout, @@license AS license, @@lower_case_table_names AS lower_case_table_names, @@max_allowed_packet AS max_allowed_packet, @@net_buffer_length AS net_buffer_length, @@net_write_timeout AS net_write_timeout, @@query_cache_size AS query_cache_size, @@query_cache_type AS query_cache_type, @@sql_mode AS sql_mode, @@system_time_zone AS system_time_zone, @@time_zone AS time_zone, @@tx_isolation AS tx_isolation, @@wait_timeout AS wait_timeout
SET character_set_results = NULL
SET autocommit=1
select table_schema as table_catalog, null as table_schema, table_name, table_comment, table_rows from information_schema.tables where table_schema='db' and table_type='BASE TABLE'
SHOW FULL TABLES FROM `db` LIKE 'users'
SHOW FULL COLUMNS FROM `users` FROM `db` LIKE '%'
select * from db.users where 0 = 1
SHOW INDEX FROM `users` FROM `db`
SHOW KEYS FROM `users` FROM `db`
...
select table_name, column_name, replace(column_type,"','","', '") as column_type, left(column_type, locate("(", column_type)-1) as short_column_type from information_schema.columns where table_schema='db' and (column_type like 'enum(%' or column_type like 'set(%')
select routine_name, routine_type, dtd_identifier, routine_body, routine_definition, is_deterministic LIKE 'Yes' as is_deterministic, sql_data_access, security_type, sql_mode, routine_comment from information_schema.routines where routine_schema='db'
select specific_name, parameter_name, dtd_identifier, parameter_mode from information_schema.parameters where specific_schema='db' and ordinal_position != 0 order by ordinal_position
...
SHOW CREATE TABLE `db`.`users`
```

**Comment by gregwebs** [comment]
Both MySQL workbench and dbeaver also seem to use `SHOW CREATE TABLE` for their diagrams. Perhaps this is the only place where the foreign key constraint name shows up?

The `SHOW CREATE TABLE` MySQL documentation was confusing for me as it seemed to indicate that it showed just the original statement. However, other documentation says to use this to look at foreign key constraints (with no warnings about alterations).

I think we need to show added foreign key constraints in `SHOW CREATE TABLE`. I haven't actually tested MySQL.

**Comment by nullnotnil** [comment]
@gregwebs I believe this can be closed now (in master). Can you confirm?

**Comment by nullnotnil** [comment]
This is assumed to be fixed in https://github.com/pingcap/tidb/pull/18360

I am going to close this issue now, but feel free to re-open if you discover otherwise. Thanks!
