### ISSUE TITLE
 Whether tidb support emojis?

### ISSUE THREAD

**Issue by wangpeng3477** [pingcap/tidb#8345]
I want to save emojis, tidb whether support?

**Comment by tiancaiamao** [comment]
TiDB support the standard utf8 encoding, and emojis is in the utf8 form, so I think the answer is yes.
@wangpeng3477

**Comment by morgo** [comment]
Most emojis are 4-byte utf8 characters.

It is important to clarify that `utf8` support in TiDB is the same as `utf8mb4` in MySQL.  So emojis work fine!
