### ISSUE TITLE
Admin check session not stopped when job is killed

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#8366]
## Bug Report

MySQL Session 1: admin check table xxxx

MySQL Session 2: kill tidb xxx (id = admin check table job id)

After kill, session 1 still waiting for admin check result.

**Comment by jackysp** [comment]
PTAL @zimulala

**Comment by nullnotnil** [comment]
I can confirm that this is fixed.

I prepared a large table (`tiup bench tpcc prepare --warehouses 50`) and then killed the check thread. It showed as interrupted as expected:

```
mysql> admin check table stock;
ERROR 1317 (70100): Query execution was interrupted
```

I am going to close this issue now.
