### ISSUE TITLE
Drop index operation on hash partitioned table

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#8378]
## Feature Request

Here is the entrance of DropIndex: https://github.com/pingcap/tidb/blob/master/ddl/ddl_api.go#L2111
The a new DDL job is created and put the the job queue https://github.com/pingcap/tidb/blob/master/ddl/ddl_worker.go#L188
https://github.com/pingcap/tidb/blob/master/ddl/ddl_worker.go#L331
The DDL worker will handle the job here:
https://github.com/pingcap/tidb/blob/master/ddl/ddl_worker.go#L494

Drop index on a hash partitioned table should take into consideration the the table is hash partitioned,  drop index data of all the partitions.

**Teachability, Documentation, Adoption, Migration Strategy:**

Maybe useful:
ddl:support drop index for the partitioned table https://github.com/pingcap/tidb/pull/7306
https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-19-table-partition.md
https://pingcap.com/blog-cn/tidb-source-code-reading-20/

**Comment by zimulala** [comment]
@tiancaiamao Could we close this issue?
