### ISSUE TITLE
Add index on a hash partitioned table

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#8379]
## Feature Request

Add index should consider the partition information
https://github.com/pingcap/tidb/blob/master/ddl/index.go#L232

Maybe add index on each partition one by one, be careful when saving the state during add index.

**Teachability, Documentation, Adoption, Migration Strategy:**

Maybe useful:
ddl: implement reorganize for table partition when adding index https://github.com/pingcap/tidb/pull/6814
https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-19-table-partition.md
https://pingcap.com/blog-cn/tidb-source-code-reading-20/

**Comment by crazycs520** [comment]
Add index for hash table looks same with range partition table. 
There is no anything need todo. 😂

**Comment by tiancaiamao** [comment]
So would you like to add more test cases to cover the hash partitioned table? @crazycs520

**Comment by crazycs520** [comment]
ok.

**Comment by zimulala** [comment]
@tiancaiamao Could we close this issue?
