### ISSUE TITLE
Some statement is troublesome on retry or rollback

### ISSUE THREAD

**Issue by tiancaiamao** [pingcap/tidb#8393]
## Feature Request

**Is your feature request related to a problem? Please describe:**

```
begin;
set variable = xxx;
// do something meet transaction conflict
rollback
```

The "set variable" executes locally, so it always success, while the transaction may conflict and retry.
During retrying, the previous `set variable` may take effect, and may cause some trouble.

"set variable = xxx" is one of the example, actually there are many kinds of similar statement.
`set @@tidb_snapshot` ...
`prepare stmt ...`  ... prepared twice during retry?
`execute stmt use ...` ... execute using the wrong environment ?
`dealloc stmt ...` dealloc twice ?

There are two kinds of statement mixed in the `begin ... commit` transaction, some of them executes locally so always guarantee to success, and other may fail. During retry or rollback, it's quite troublesome.

**Describe the feature you'd like:**

We should find a general mechanism to handle the problem.

**Describe alternatives you've considered:**

An open discuss is welcomed in this thread.

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by zz-jason** [comment]
Confirmed that user variables are not reverted back in TiDB:

create a table:

```sql
drop table if exists t;
create table t(a bigint, b bigint);
```

begin a transaction, modify a variable and insert a record, but revert it:

```sql
begin;
set @a = 100;
insert into t values(1, 1);
rollback;
```

check the variable and the table, you can see the user variable has been changed:

```sql

TiDB(root@127.0.0.1:test) > select @a;
+------+
| @a   |
+------+
| 100  |
+------+
1 row in set (0.00 sec)

TiDB(root@127.0.0.1:test) > select * from t;
Empty set (0.00 sec)
```

Only TiDB has this problem, MySQL works correctly:

```sql
MySQL(root@127.0.0.1:test) > select @@a;
ERROR 1193 (HY000): Unknown system variable 'a'
MySQL(root@127.0.0.1:test) > select * from t;
Empty set (0.00 sec)
```

My TiDB version:

```sql
TiDB(root@127.0.0.1:test) > select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-838-gb249dc578-dirty
Edition: Community
Git Commit Hash: b249dc5780407b256d1383e92f56bd843d2682ed
Git Branch: master
UTC Build Time: 2020-07-27 08:15:29
GoVersion: go1.13.12
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

My MySQL version:

```sql
MySQL(root@127.0.0.1:test) > select version();
+-----------+
| version() |
+-----------+
| 8.0.21    |
+-----------+
1 row in set (0.00 sec)
```

**Comment by zz-jason** [comment]
It also affects session/global variables.

An example of a session variable:

```sql
TiDB(root@127.0.0.1:test) > select @@sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@sql_mode                                                                                                                                |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

TiDB(root@127.0.0.1:test) > begin;
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > set @@sql_mode='';
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > insert into t values(1, 1);
Query OK, 1 row affected (0.00 sec)

TiDB(root@127.0.0.1:test) > rollback;
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > select @@sql_mode;
+------------+
| @@sql_mode |
+------------+
|            |
+------------+
1 row in set (0.00 sec)
```

An example of a global variable:

```sql
TiDB(root@127.0.0.1:test) > select @@global.sql_mode;
+-------------------------------------------------------------------------------------------------------------------------------------------+
| @@global.sql_mode                                                                                                                         |
+-------------------------------------------------------------------------------------------------------------------------------------------+
| ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
+-------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

TiDB(root@127.0.0.1:test) > begin;
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > set @@global.sql_mode = '';
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > insert into t values(1, 1);
Query OK, 1 row affected (0.01 sec)

TiDB(root@127.0.0.1:test) > rollback;
Query OK, 0 rows affected (0.00 sec)

TiDB(root@127.0.0.1:test) > select @@global.sql_mode;
+-------------------+
| @@global.sql_mode |
+-------------------+
|                   |
+-------------------+
1 row in set (0.00 sec)
```

**Comment by zz-jason** [comment]
@cfzjywxk @zhangjinpeng1987 PTAL. It more like a bug.

**Comment by cfzjywxk** [comment]
@tiancaiamao PTAL if it still exist

**Comment by tiancaiamao** [comment]
I decide not to fix this for **system session variables** because those variables are bind to special semantic and when they take effect is vague.
Some system session variables are not simply a value, they also behave as a switch.

We may take them as data at the first thought: after a statement finish they take effect inside a transaction, and if the transaction rollbacks their effects are gone. 

However, some variables are special.
For example, `autocommit`, change the value would commit the transaction immediately, so rollback the statement is not possible anymore.
And another example is the variable `tidb_snapshot`, change this makes TiDB goes into a snapshot state.
And there are more variables like one-shot transaction mode, they all make the fix quite troublesome.

We can fix user-defined variables and global variables, as they are either not bind with special behavior, or take effect only on new sessions.

**Comment by mjonss** [comment]
I think there is a typo in the MySQL test:
```
MySQL(root@127.0.0.1:test) > select @@a;
ERROR 1193 (HY000): Unknown system variable 'a'
```
I think it should have been
```
select @a;
```
which is the user variable set in the test. `@@a` is interpreted as a session/global system variable and could not be found, so the error is correct, but using `select @a;` instead, it would give the same result as in TiDB: 100

**Comment by tiancaiamao** [comment]
OK, it seems we misunderstand MySQL's behaviour. @mjonss
