### ISSUE TITLE
contributing guidelines

### ISSUE THREAD

**Issue by astaxie** [pingcap/tidb#845]
As tidb become more popular, I think tidb need to add contributing guidelines. That explains how a participant should do things like format code, test fixes, and submit patches.

Here is the introduce: https://github.com/blog/1184-contributing-guidelines

Here is the beego's guide: https://github.com/astaxie/beego/blob/develop/CONTRIBUTING.md

**Comment by ngaut** [comment]
Thanks @astaxie 
Please take a look https://github.com/pingcap/tidb/blob/master/docs/CONTRIBUTING.md

**Comment by astaxie** [comment]
You need to place the file in the root directory. otherwise these's no tips when create issues or pull request .

**Comment by ngaut** [comment]
SGTM.
Thanks @astaxie
