### ISSUE TITLE
tidb-server options -socket and -host are incompatible

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#8459]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
./bin/tidb-server -socket /tmp/mysql.sock -host 127.0.0.1 -P 3306
```

2. What did you expect to see?

I would expect it to listen on both.  This is important because of MySQL's special handling of localhost:
- For the libmysql derived clients it will switch to using unix socket.
- For other drivers like JDBC it will only ever use tcp.

So it is useful to be able to have the server listen on both for a fully local install.

3. What did you see instead?

 It will only listen on one (the socket!)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-beta-644-g89cd59d21
Git Commit Hash: 89cd59d217637f5e79fdc81681c98531c668e688
Git Branch: newmaster
UTC Build Time: 2018-11-26 04:47:59
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by morgo** [comment]
I looked at `server/server.go`:
```
// NewServer creates a new Server.
func NewServer(cfg *config.Config, driver IDriver) (*Server, error) {
..
        if cfg.Socket != "" {
                if s.listener, err = net.Listen("unix", cfg.Socket); err == nil {
                        log.Infof("Server is running MySQL Protocol through Socket [%s]", cfg.Socket)
                }
        } else {
                addr := fmt.Sprintf("%s:%d", s.cfg.Host, s.cfg.Port)
                if s.listener, err = net.Listen("tcp", addr); err == nil {
                        log.Infof("Server is running MySQL Protocol at [%s]", addr)
                }
        }
```
For simplicity, would it be okay to forward the unix socket to the tcp address?  Unix socket is not a major use case for TiDB, and this solution looks quite straight forward to add.

**Comment by morgo** [comment]
PTAL @jackysp

**Comment by jackysp** [comment]
I found the same thing some days before, and got the suggestion that it would not be fixed. I can't quite remember the reason. Please give me       some time to find out the reason.

**Comment by morgo** [comment]
@jackysp OK :-)  I can fix it if you are okay with the suggested fix (redirection to tcp socket).  It is an important fix for allowing local development (homebrew, dbdeployer) and have some apps use JDBC with others using PHP etc.

**Comment by jackysp** [comment]
@morgo , I discussed this with @coocood . It was not supported because it was not important at that time. Now that it has a high priority, I think we can support it.
