### ISSUE TITLE
Could tidb support other kv store?

### ISSUE THREAD

**Issue by gengxin** [pingcap/tidb#8461]
For example, tikv and hbase (or bigtable) share similar data model and replication feature, hbase is like a tikv without transaction. So is it possible? Or may be already supported? Thanks

**Comment by morgo** [comment]
Hi @gengxin, see https://github.com/pingcap/tidb/issues/6561

(Yes, it's possible.  In the early days we did try supporting hbase.)

**Comment by gengxin** [comment]
Thanks!
