### ISSUE TITLE
TIKV SHUTDOWM WHEN INSERT

### ISSUE THREAD

**Issue by evancao77** [pingcap/tidb#8463]
tidb version 2.0.8

The tidb node was shutdown  when the data was inserted in bulk.and I couldn't start it whit then err:

2018/11/27 11:37:08.106 util.rs:373: [INFO] All PD endpoints are consistent: ["172.xxx.xxx.28:2379", "172.xxx.xxx.29:2379", "172.xxx.xxx.30:2379"]
2018/11/27 11:37:08.107 tikv-server.rs:425: [INFO] connect to PD cluster 6623668385181707215
2018/11/27 11:37:08.115 mod.rs:346: [INFO] starting working thread: store address resolve worker
2018/11/27 11:37:11.430 mod.rs:425: [INFO] storage RaftKv started.
2018/11/27 11:37:11.491 server.rs:99: [INFO] listening on 0.0.0.0:20160
2018/11/27 11:37:11.496 node.rs:334: [INFO] start raft store 5 thread
2018/11/27 11:37:11.498 peer.rs:305: [INFO] [region 2] create peer with id 21
2018/11/27 11:37:11.499 <unknown>:795: [INFO] [region 2] 21 became follower at term 5583
2018/11/27 11:37:11.499 <unknown>:395: [INFO] [region 2] 21 newRaft [peers: [3, 21, 23], term: 5583, commit: 9746, applied: 9746, last_index: 9746, last_term: 5583]
2018/11/27 11:37:11.499 peer.rs:305: [INFO] [region 6] create peer with id 24
2018/11/27 11:37:11.499 <unknown>:795: [INFO] [region 6] 24 became follower at term 4580
2018/11/27 11:37:11.499 <unknown>:395: [INFO] [region 6] 24 newRaft [peers: [7, 16, 24], term: 4580, commit: 282833, applied: 282833, last_index: 282833, last_term: 4580]
2018/11/27 11:37:11.499 peer.rs:305: [INFO] [region 8] create peer with id 17
2018/11/27 11:37:11.499 <unknown>:795: [INFO] [region 8] 17 became follower at term 4355
2018/11/27 11:37:11.499 <unknown>:395: [INFO] [region 8] 17 newRaft [peers: [9, 17, 29], term: 4355, commit: 4460, applied: 4460, last_index: 4460, last_term: 4355]
2018/11/27 11:37:11.499 peer.rs:305: [INFO] [region 10] create peer with id 30
2018/11/27 11:37:11.622 panic_hook.rs:97: [ERROR] thread 'raftstore-5' panicked '[region 10] 30 unexpected raft log index: last_index 4365 < applied_index 4433' at "src/raftstore/store/peer_storage.rs:472"
stack backtrace:
   0:     0x7ff6b80f720e - backtrace::backtrace::libunwind::trace::h79c4af28be231e54
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace::h56424d341baa1bce
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x7ff6b7bc70b7 - tikv::util::panic_hook::set_exit_hook::{{closure}}::h476b47e8b1c02c1b
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/target/release/build/backtrace-5e253aa535e0fe5b/out/capture.rs:79
   2:     0x7ff6b82c97f5 - std::panicking::rust_panic_with_hook::h1be8ff44b2f85fd7
                        at libstd/panicking.rs:403
   3:     0x7ff6b82c968d - std::panicking::begin_panic_fmt::h9462a882b9175ee8
                        at libstd/panicking.rs:349
   4:     0x7ff6b7a15845 - tikv::raftstore::store::peer::Peer::new::hda0b0835d66339d4
                        at src/raftstore/store/peer_storage.rs:472
   5:     0x7ff6b7a16d2f - tikv::raftstore::store::peer::Peer::create::h93f14bdb77ed45d9
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/raftstore/store/peer.rs:310
   6:     0x7ff6b832515d - <tikv::raftstore::store::store::Store<T, C>>::init::h5a54455ec3a79a5e
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/raftstore/store/store.rs:325
                         - <tikv::raftstore::store::store::Store<T, C>>::new::h8b66c56dd6a46676
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/raftstore/store/store.rs:264
                         - <tikv::server::node::Node<C>>::start_store::{{closure}}::h4600845a08a1872c
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/server/node.rs:352
   7:     0x7ff6b8320fbd - std::sys_common::backtrace::__rust_begin_short_backtrace::h5edcf7a3a3007102
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
   8:     0x7ff6b7a1d02b - std::thread::Builder::spawn::{{closure}}::h4878cecbaa087850
                        at /checkout/src/libstd/thread/mod.rs:406
                         - <F as alloc::boxed::FnBox<A>>::call_box::hfbe2437636039f76
                        at /checkout/src/liballoc/boxed.rs:635
   9:     0x7ff6b82c0477 - std::sys::unix::thread::Thread::new::thread_start::h0c3a0b0523777f20
                        at /checkout/src/liballoc/boxed.rs:645
  10:     0x7ff6b6e87e24 - start_thread
  11:     0x7ff6b699f34c - __clone
  12:                0x0 - <unknown>

**Comment by jackysp** [comment]
Thanks for your report, @evancao77 !
PTAL @rleungx

**Comment by hicqu** [comment]
@evancao77 Seems you didn't enable sync-log, and then the machine shutdown, some raft logs are lost.
Could you share more information with us:
- How many TiKV machines do you have?
- How many TiKV machines were down?

**Comment by evancao77** [comment]
How can I restart this tikv node Thanks for help  @hicqu

**Comment by hicqu** [comment]
You can try to use `tikv-ctl tombstone` command to remove all corrupted regions from that machine. For example:
```
tikv-ctl --db /path/to/the/tikv/data/db --pd 127.0.0.1:2379 tombstone -r 8
```
to set the corrupted region `8` to tombstone. Please remember to stop the TiKV process before you run this, and replace the `pd` with real endpoints you have.

**Comment by evancao77** [comment]
Thanks for help  Let me try. Does it affect other running clusters?

I find in document:
Raft uses strong consistency, and only when the data has been written into more than 50% of the nodes, the application returns ACK (two out of three nodes). In this case, data consistency is guaranteed. However, theoretically, two nodes might crash. Therefore, for scenarios that have a strict requirement on data security, such as scenarios in financial industry, you need to enable the sync-log.
 I see a 30% drop in performance in document.  Is this a bug or normal ? @hicqu

**Comment by evancao77** [comment]
2018/11/27 17:52:39.823 panic_hook.rs:97: [ERROR] thread 'raftstore-5' panicked '[region 25] 27 unexpected raft log index: last_index 4327 < applied_index 4398' at "src/raftstore/store/peer_storage.rs:472"
stack backtrace:
   0:     0x7f0742cf620e - backtrace::backtrace::libunwind::trace::h79c4af28be231e54
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace::h56424d341baa1bce
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x7f07427c60b7 - tikv::util::panic_hook::set_exit_hook::{{closure}}::h476b47e8b1c02c1b
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/target/release/build/backtrace-5e253aa535e0fe5b/out/capture.rs:79
   2:     0x7f0742ec87f5 - std::panicking::rust_panic_with_hook::h1be8ff44b2f85fd7
                        at libstd/panicking.rs:403
   3:     0x7f0742ec868d - std::panicking::begin_panic_fmt::h9462a882b9175ee8
                        at libstd/panicking.rs:349
   4:     0x7f0742614845 - tikv::raftstore::store::peer::Peer::new::hda0b0835d66339d4
                        at src/raftstore/store/peer_storage.rs:472
   5:     0x7f0742615d2f - tikv::raftstore::store::peer::Peer::create::h93f14bdb77ed45d9
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/raftstore/store/peer.rs:310
   6:     0x7f0742f2415d - <tikv::raftstore::store::store::Store<T, C>>::init::h5a54455ec3a79a5e
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/raftstore/store/store.rs:325
                         - <tikv::raftstore::store::store::Store<T, C>>::new::h8b66c56dd6a46676
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/raftstore/store/store.rs:264
                         - <tikv::server::node::Node<C>>::start_store::{{closure}}::h4600845a08a1872c
                        at /home/jenkins/workspace/build_tikv_2.0/go/src/github.com/tikv/tikv/src/server/node.rs:352
   7:     0x7f0742f1ffbd - std::sys_common::backtrace::__rust_begin_short_backtrace::h5edcf7a3a3007102
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
   8:     0x7f074261c02b - std::thread::Builder::spawn::{{closure}}::h4878cecbaa087850
                        at /checkout/src/libstd/thread/mod.rs:406
                         - <F as alloc::boxed::FnBox<A>>::call_box::hfbe2437636039f76
                        at /checkout/src/liballoc/boxed.rs:635
   9:     0x7f0742ebf477 - std::sys::unix::thread::Thread::new::thread_start::h0c3a0b0523777f20
                        at /checkout/src/liballoc/boxed.rs:645
  10:     0x7f0741a86e24 - start_thread
  11:     0x7f074159e34c - __clone
  12:                0x0 - <unknown>

another region is err? 
If there are many such situations, how can I solve it？

**Comment by evancao77** [comment]
@hicqu Please give me a hand.

**Comment by evancao77** [comment]
@jackysp Could you help me?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to re-open if you can reproduce on a later version. Thanks!
