### ISSUE TITLE
 format error: select str_to_date('18/10/22','%y/%m/%d') from dual

### ISSUE THREAD

**Issue by jeff-zou** [pingcap/tidb#8465]
select str_to_date('18/10/22','%y/%m/%d') from dual 
return null

**Comment by jackysp** [comment]
Thanks for your report, @jeff-zou !
PTAL @XuHuaiyu

**Comment by FateTHarlaown** [comment]
I'm tying to fix this bug and found the SQL
`select str_to_date('18/10/22','%Y/%m/%d') from dual`
also return null in TiDB.
 But in MySQL5.7.18,  I got 
`2018-10-22`
It seems that the func "yearNumericFourDigits" can only deal with 4 numers, should we change it ?

**Comment by XuHuaiyu** [comment]
@FateTHarlaown Thanks for your contribution.
It seems we should.
