### ISSUE TITLE
mydumper crash when table name ends with a backslash (\)

### ISSUE THREAD

**Issue by wl21787** [pingcap/tidb#8472]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
backup all databases:
mydumper -h 127.0.0.1 -u dba--password='test1.q' -P 3936  -t 8  -o /data/mysql/backup/20181127/

but after a while:
Segmentation fault

the mydumper process crash

2. What did you expect to see?
when I use percona-mydumper,the mydumper process do well work

3. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.3-219-g1e0876f
Git Commit Hash: 1e0876fe810a832721aac52275dd2b7792fd2892
Git Branch: master
UTC Build Time: 2018-11-23 11:50:37
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |

**Comment by kennytm** [comment]
Hi @wl21787, could you provide some information about the mydumper version -

* are you using the mydumper from https://github.com/pingcap/mydumper#how-to-install-mydumpermyloader ?

* what is the mydumper version? 

    ```console
    $ mydumper -V
    mydumper 0.9.5, built against MySQL 5.7.22
    ```

* is there any log before the segfault?

Thank you!

**Comment by wl21787** [comment]
Thank you for your attention！

The mydumper from:
wget http://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz

the mydumper version:
mydumper 0.9.5, built against MySQL 5.7.23

**Comment by kennytm** [comment]
@wl21787 Thank you. Would you mind sharing the logs before the segfault by executing mydumper with `-v 3`?

```console
$ mydumper -v 3 -h 127.0.0.1 -u dba --password='test1.q' -P 3936 -t 8 -o /data/mysql/backup/20181127/
** Message: 10:49:38.541: Server version reported as: 8.0.12
** Message: 10:49:38.547: Connected to a MySQL server
** Message: 10:49:38.558: Started dump at: 2018-11-28 10:49:38
** Message: 10:49:38.558: Written master status
** Message: 10:49:38.609: Thread 1 connected using MySQL connection ID 38
** Message: 10:49:38.647: Thread 2 connected using MySQL connection ID 39
...
```

**Comment by wl21787** [comment]
** Message: Server version reported as: 5.6.23-72.1-log
** Message: Connected to a MySQL server
** Message: Using Percona Backup Locks
** Message: Started dump at: 2018-11-28 11:06:22

** Message: Written master status
** Message: Thread 1 connected using MySQL connection ID 15700788
** Message: Thread 2 connected using MySQL connection ID 15700789
** Message: Thread 3 connected using MySQL connection ID 15700790
** Message: Thread 4 connected using MySQL connection ID 15700791
** Message: Thread 5 connected using MySQL connection ID 15700792
** Message: Thread 6 connected using MySQL connection ID 15700793
** Message: Thread 7 connected using MySQL connection ID 15700794
** Message: Thread 8 connected using MySQL connection ID 15700795
 Message: Thread 3 dumping data for `anti_spam`.`antispam_content_scope`
** Message: Thread 3 dumping data for `anti_spam`.`antispam_content_strategy_unit_fileds`
** Message: Thread 3 dumping data for `anti_spam`.`antispam_strategy`
** Message: Thread 3 dumping data for `anti_spam`.`antispam_user_log`
** Message: Thread 3 dumping data for `anti_spam`.`bad_word`
** Message: Thread 3 dumping data for `anti_spam`.`combine_badwords`
** Message: Thread 4 dumping data for `anti_spam`.`common_badword`
** Message: Thread 3 dumping data for `anti_spam`.`common_badword_bak`
** Message: Thread 4 dumping data for `anti_spam`.`common_badwords`
** Message: Thread 4 dumping data for `anti_spam`.`common_black_list`
** Message: Empty table anti_spam.common_black_list
** Message: Thread 4 dumping data for `anti_spam`.`common_reject_list`
** Message: Thread 8 dumping data for `anti_spam`.`cookie_agent`
** Message: Thread 4 dumping data for `anti_spam`.`general_words_detail`
** Message: Thread 4 dumping data for `anti_spam`.`general_words_type`
** Message: Thread 4 dumping data for `anti_spam`.`housing_agent`
** Message: Thread 3 dumping data for `anti_spam`.`limit_info`
** Message: Empty table anti_spam.limit_info
** Message: Thread 3 dumping data for `anti_spam`.`parttime_wanted_agent`
** Message: Thread 3 dumping data for `anti_spam`.`pet_agent`
** Message: Empty table anti_spam.pet_agent
** Message: Thread 3 dumping data for `anti_spam`.`report_detail`
** Message: Thread 3 dumping data for `anti_spam`.`secondmarket_agent`
** Message: Thread 5 dumping data for `anti_spam`.`strategy`
** Message: Thread 5 dumping data for `anti_spam`.`strategy_base_config`
** Message: Thread 5 dumping data for `anti_spam`.`strategy_hit`
** Message: Thread 5 dumping data for `anti_spam`.`strategy_log`
** Message: Thread 5 dumping data for `anti_spam`.`ticketing_agent`
** Message: Thread 7 dumping data for `anti_spam`.`vehicle_agent`
** Message: Thread 6 dumping data for `anti_spam`.`wanted_agent
** Message: Thread 5 dumping data for `anti_spam_dev`.`strategy`
** Message: Thread 5 dumping data for `anti_spam_dev`.`strategy_base_config`
** Message: Thread 5 dumping data for `anti_spam_dev`.`strategy_copy`
** Message: Thread 5 dumping data for `anti_spam_dev`.`strategy_copy1`
** Message: Thread 5 dumping data for `anti_spam_dev`.`strategy_hit`
** Message: Empty table anti_spam_dev.strategy_hit
** Message: Thread 5 dumping data for `anti_spam_dev`.`strategy_log`
** Message: Thread 5 dumping data for `anti_spam_dev`.`ticketing_agent`
** Message: Empty table anti_spam_dev.ticketing_agent
** Message: Thread 5 dumping data for `anti_spam_dev`.`vehicle_agent`
** Message: Empty table anti_spam_dev.vehicle_agent
** Message: Thread 5 dumping data for `anti_spam_dev`.`wanted_agent`
** Message: Empty table anti_spam_dev.wanted_agent
** Message: Thread 5 dumping data for `anti_spam_v2`.`antispam_strategy`
** Message: Thread 5 dumping data for `anti_spam_v2`.`antispam_user_log`
** Message: Thread 5 dumping data for `anti_spam_v2`.`bad_word`
** Message: Thread 5 dumping data for `anti_spam_v2`.`combine_badwords`
** Message: Thread 5 dumping data for `anti_spam_v2`.`common_badword`
** Message: Thread 5 dumping data for `anti_spam_v2`.`common_badwords`
** Message: Thread 5 dumping data for `anti_spam_v2`.`common_reject_list`
** Message: Thread 5 dumping data for `anti_spam_v2`.`cookie_agent`
** Message: Thread 2 dumping data for `anti_spam_v2`.`general_words_detail`
** Message: Thread 2 dumping data for `anti_spam_v2`.`general_words_type`
** Message: Thread 2 dumping data for `anti_spam_v2`.`housing_agent`
** Message: Empty table data_service.jz_label_ab_test
** Message: Thread 7 dumping data for `data_service`.`mgmt_effect_conversation_push_m`
** Message: Empty table data_service.mgmt_effect_conversation_push_m
** Message: Thread 7 dumping data for `data_service`.`mgmt_last_7_day_push_d`
** Message: Empty table data_service.mgmt_last_7_day_push_d
** Message: Thread 7 dumping data for `data_service`.`mgmt_next_day_push_d`
** Message: Empty table data_service.mgmt_next_day_push_d
** Message: Thread 7 dumping data for `data_service`.`mgmt_no_binding_push_m`
** Message: Empty table data_service.mgmt_no_binding_push_m
** Message: Thread 7 dumping data for `data_service`.`post_display_click`
** Message: Thread 7 dumping data for `data_service`.`post_lastday_cvr`
** Message: Thread 7 dumping data for `data_service`.`push_ channel_ statistics`
** Message: Empty table data_service.push_ channel_ statistics
** Message: Thread 7 dumping data for `data_service`.`push_ statistics_info`
** Message: Empty table data_service.push_ statistics_info
** Message: Thread 7 dumping data for `data_service`.`push_spider_data`
** Message: Thread 7 dumping data for `data_service`.`push_statistics_info`
** Message: Thread 7 dumping data for `data_service`.`push_token_status`
** Message: Thread 1 dumping data for `data_service`.`push_token_status_1`
** Message: Non-InnoDB dump complete, unlocking tables
** Message: Thread 7 dumping data for `dw_jianzhi`.`ab_city`
** Message: Thread 7 dumping data for `dw_jianzhi`.`alg_cpa_mysql_user_feature`
** Message: Thread 3 dumping data for `dw_jianzhi`.`candidate_20180723`
** Message: Thread 3 dumping data for `dw_jianzhi`.`candidate_20180724_4874953`
** Message: Thread 3 dumping data for `dw_jianzhi`.`cheated1008`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_datasource`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_datasource_type`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_group`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_menu`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_properties`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_role`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_role_menu`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_user`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_user_group`
** Message: Thread 3 dumping data for `dw_jianzhi`.`core_user_role`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_20180724_4874953`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_20180724_4874953_v2`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_20180726_4874953_v1`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_20180726_4874953_v2`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_4513291`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_4513291_jianzhi`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_4513291_v2`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_48894156`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_48894156v2`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_4894482`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_4894482_v2`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_phone_white_list`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_rpo_4787399`
** Message: Thread 3 dumping data for `dw_jianzhi`.`data_rpo_4787399\`
Segmentation fault

**Comment by kennytm** [comment]
Thanks @wl21787. We've determined this is caused by the trailing backslash in a table name. 

Reproduction:

```sql
CREATE DATABASE sample;
USE sample;
CREATE TABLE `foo\` (a INT);
\q
```

```console
$ ./mydumper -v 3 -h 127.0.0.1 -u root --password='' -P 3306 -B sample -t 8 -o dataa
...
** Message: 11:33:34.520: Thread 3 dumping data for `sample`.`foo\`
Segmentation fault: 11
```

(This bug doesn't happen in the maxbabe version)

**Comment by wl21787** [comment]
Thank you very much!
