### ISSUE TITLE
tidb crash

### ISSUE THREAD

**Issue by liusga2019** [pingcap/tidb#8512]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
pd  error:
WARNING: 2018/11/28 01:50:27 grpc: addrConn.transportMonitor exits due to: grpc: the connection is closing
2018/11/28 01:50:27.941 server.go:276: [info] close server

2018/11/28 01:48:52.991 gc_worker.go:298: [info] [gc worker] leaderTick on 59d567682e8000c: gc interval (10m0s) haven't past since last run (2018-11-28 01:40:52 +0800 CST). no need to gc
2018/11/28 01:49:52.991 gc_worker.go:298: [info] [gc worker] leaderTick on 59d567682e8000c: gc interval (10m0s) haven't past since last run (2018-11-28 01:40:52 +0800 CST). no need to gc
2018/11/28 01:50:27.940 signal_posix.go:51: [info] Got signal [hangup] to exit.
2018/11/28 01:50:27.940 http_status.go:132: [info] http: Server closed
2018/11/28 01:50:27.940 syncer.go:273: [warning] [etcd-cli] delete key /tidb/ddl/all_schema_versions/55654cad-7f5e-424a-9517-100f623d8fba failed rpc error: code = Unavailable desc = transport
 is closing no.0
2018/11/28 01:50:27.940 manager.go:265: [warning] [ddl] /tidb/ddl/fg/owner ownerManager 55654cad-7f5e-424a-9517-100f623d8fba isn't the owner
2018/11/28 01:50:27.940 manager.go:224: [info] [ddl] /tidb/ddl/fg/owner ownerManager 55654cad-7f5e-424a-9517-100f623d8fba etcd session is done, creates a new one
2018/11/28 01:50:27.940 manager.go:228: [info] [ddl] /tidb/ddl/fg/owner ownerManager 55654cad-7f5e-424a-9517-100f623d8fba break campaign loop, NewSession err context canceled
2018/11/28 01:50:27.949 client.go:415: [error] [pd] getTS error: EOF
2018/11/28 01:50:27.949 client.go:369: [error] [pd] create tso stream error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection err
or: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
2018/11/28 01:50:27.949 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://127.0.0.1:2379]
2018/11/28 01:50:27.949 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://127.0.0.1:2379]
2018/11/28 01:50:28.949 client.go:369: [error] [pd] create tso stream error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection err
or: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
2018/11/28 01:50:28.949 pd.go:127: [error] updateTS error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transp
ort: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
2018/11/28 01:50:28.949 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://127.0.0.1:2379]
2018/11/28 01:50:29.940 syncer.go:273: [warning] [etcd-cli] delete key /tidb/ddl/all_schema_versions/55654cad-7f5e-424a-9517-100f623d8fba failed context deadline exceeded no.1
2018/11/28 01:50:29.949 client.go:369: [error] [pd] create tso stream error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection err
or: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
2018/11/28 01:50:29.949 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://127.0.0.1:2379]
2018/11/28 01:50:30.949 client.go:369: [error] [pd] create tso stream error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection err
or: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
2018/11/28 01:50:30.949 pd.go:127: [error] updateTS error: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transp
ort: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused"
2018/11/28 01:50:30.949 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://127.0.0.1:2379]
2018/11/28 01:50:31.940 syncer.go:273: [warning] [etcd-cli] delete key /tidb/ddl/all_schema_versions/55654cad-7f5e-424a-9517-100f623d8fba failed context deadline exceeded no.2
2018/11/28 01:50:31.940 ddl.go:404: [error] [ddl] remove self version path failed context deadline exceeded
2018/11/28 01:50:31.940 delete_range.go:103: [info] [ddl] closing delRange session pool

2. What did you expect to see?
2018/11/28 00:52:34.529 conn.go:457: [error] con:2 read packet error, close this connection read tcp 192.168.0.117:4000->192.168.0.128:64693: read: connection timed out
github.com/pingcap/errors.AddStack
	/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
	/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb/server.(*packetIO).readOnePacket
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:70
github.com/pingcap/tidb/server.(*packetIO).readPacket
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:90
github.com/pingcap/tidb/server.(*clientConn).readPacket
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:211
github.com/pingcap/tidb/server.(*clientConn).Run
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:452
github.com/pingcap/tidb/server.(*Server).onConn
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:324
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
2018/11/28 00:52:34.529 conn.go:457: [error] con:1 read packet error, close this connection read tcp 192.168.0.117:4000->192.168.0.128:64692: read: connection timed out
github.com/pingcap/errors.AddStack
	/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
	/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb/server.(*packetIO).readOnePacket
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:70
github.com/pingcap/tidb/server.(*packetIO).readPacket
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/packetio.go:90
github.com/pingcap/tidb/server.(*clientConn).readPacket
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:211
github.com/pingcap/tidb/server.(*clientConn).Run
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:452
github.com/pingcap/tidb/server.(*Server).onConn
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:324
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
2018/11/28 00:52:34.529 server.go:316: [info] con:1 close connection
2018/11/28 00:52:34.529 server.go:316: [info] con:2 close connection

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.1.0-rc.3-219-g1e0876f
Git Commit Hash: 1e0876fe810a832721aac52275dd2b7792fd2892
Git Branch: master
UTC Build Time: 2018-11-23 11:50:37
GoVersio

**Comment by c4pt0r** [comment]
Seems like your PD is not setup correctly. Can you provide more information? Like cluster topology, and how did launch your pd/tidb/tikv?

**Comment by c4pt0r** [comment]
2018/11/28 01:40:34.368 log.go:88: [info] mvcc: [finished scheduled compaction at 29968 (took 810.185µs)]
2018/11/28 01:50:27.939 main.go:105: [info] Got signal [1] to exit. <---- Did you manual shut down your shell?
2018/11/28 01:50:27.939 server.go:257: [info] closing server

**Comment by c4pt0r** [comment]
Seems pd process received SIGHUP, then quit.

**Comment by c4pt0r** [comment]
The way you launch PD/TiKV/TiDB will cause a situation that the process will be killed when your shell is closed. Please try nohup.
