### ISSUE TITLE
date_add interval month diffs from mysql

### ISSUE THREAD

**Issue by haplone** [pingcap/tidb#8521]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```sql
select date_add('2018-08-31', interval 1 month);
```

2. What did you expect to see?
2018-09-30

3. What did you see instead?
2018-10-01

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Welcome to TiDB.
Release Version: v2.0.9-19-g51c2e66be
Git Commit Hash: 51c2e66bedc4f205c900b92aaf33ad5197f9f85c
Git Branch: release-2.0
UTC Build Time:  2018-11-29 12:26:44
GoVersion:  go version go1.11.2 darwin/amd64
TiKV Min Version: 2.0.0-rc.4.1
```

I think this bug is due to golang api time/time.go#AddDate.
in this api we could see comments:
```
// AddDate returns the time corresponding to adding the
// given number of years, months, and days to t.
// For example, AddDate(-1, 2, 3) applied to January 1, 2011
// returns March 4, 2010.
//
// AddDate normalizes its result in the same way that Date does,
// so, for example, adding one month to October 31 yields
// December 1, the normalized form for November 31.
func (t Time) AddDate(years int, months int, days int) Time {
   year, month, day := t.Date()
   hour, min, sec := t.Clock()
   return Date(year+years, month+Month(months), day+days, hour, min, sec, int(t.nsec()), t.Location())
}
```
it's diffs from mysql date_sub api.
we could fix it in expression/builtin_time.go

I could file a PR  to fix it (already solve it).
https://github.com/pingcap/tidb/pull/8534

**Comment by jackysp** [comment]
Fixed by https://github.com/pingcap/tidb/pull/8988
