### ISSUE TITLE
kernel:unregister_netdevice: waiting for vethbc7be59 to become free. Usage count = 1

### ISSUE THREAD

**Issue by wangpeng3477** [pingcap/tidb#8524]
I ran into a bug in development when using the docker compose deployment
error log:
kernel:unregister_netdevice: waiting for vethbc7be59 to become free. Usage count = 1

is there a solution?

**Comment by zimulala** [comment]
PTAL @zhouqiang-cl

**Comment by zhouqiang-cl** [comment]
This is not a tidb bug. but seems a kernel bug
You can try the following method(if it does not work, please let us know and will continue to solve it):

- the short-term solution is to reboot your system。
- the long-term solution is upgrade kernel(but it have a risk to break other things down)

refer to: 
1. https://github.com/kubernetes/kubernetes/issues/64743
2. https://github.com/coreos/bugs/issues/254
3. https://github.com/moby/moby/issues/5618

**Comment by wangpeng3477** [comment]
@zhouqiang-cl 我想知道 如果在生产环境中用Ansible的集群部署方案 还有这种问题存在吗

**Comment by zhouqiang-cl** [comment]
@wangpeng3477 使用 ansible 部署的不会出现这种问题，这种问题只有在不同的增删网络接口才会出现

**Comment by zhouqiang-cl** [comment]
@dElogics  which kernel did you upgrade to. It seems need to upgrade to 4.12 or later

**Comment by yangshuai93** [comment]
@zhouqiang-cl    ansible 部署和这个问题有什么关联吗？ 
这个bug 对系统会有什么具体的影响呢？

**Comment by caihy05** [comment]
> @wangpeng3477 使用 ansible 部署的不会出现这种问题，这种问题只有在不同的增删网络接口才会出现，ansible 是使用物理机部署，不会涉及到网络接口增删


This issueswill still occur
