### ISSUE TITLE
Can TiDB be compiled and run on MIPS server？ 

### ISSUE THREAD

**Issue by zhengxiaochuan-3** [pingcap/tidb#8525]
Can TiDB be compiled and run on MIPS server？ and how ?

**Comment by zimulala** [comment]
@zhengxiaochuan-3 
If this environment can run the go program normally, I feel that it is normal to run TiDB. You can try it like a normal environment.

**Comment by zhu168** [comment]
@zhengxiaochuan-3
you can compile and use go programs normally on the loongson. Loongson is a MIPS CPU.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
