### ISSUE TITLE
can't  go get github.com/coreos/etcd/clientv3

### ISSUE THREAD

**Issue by vickhello** [pingcap/tidb#8531]
when I use "go get" command to get this clientv3 package, err happened. as follows:
![image](https://user-images.githubusercontent.com/33645617/49276576-df764f80-f4b9-11e8-90d9-e98e25258f39.png)
![image](https://user-images.githubusercontent.com/33645617/49276594-e69d5d80-f4b9-11e8-8316-7a8a1fc3cca9.png)

**Comment by jackysp** [comment]
Maybe it is not a TiDB related issue.
Closed.

**Comment by shenli** [comment]
@vickhello Etcd has a new organization. https://github.com/etcd-io/etcd
