### ISSUE TITLE
Collect CPU metrics for TiDB Server

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#8539]
## Feature Request

**Is your feature request related to a problem? Please describe:**

At present, we can not know the CPU usage of the `tidb-server` process in the monitor.

**Describe the feature you'd like:**

As the title said, a simple demo is:
```go
package main

import (
    "fmt"
    "os"
    "sync"
    "time"

    "github.com/struCoder/pidusage"
)

func printStat() {
    sysInfo, err := pidusage.GetStat(os.Getpid())
    if err != nil {
        fmt.Printf("%v\n", err)
    } else {
        fmt.Printf("CPU: %v, MEM: %v\n", sysInfo.CPU, sysInfo.Memory)
    }
}

func useCPU(wg *sync.WaitGroup) int {
    defer wg.Done()

    sum := 1
    for i := 0; i < 1000000000; i++ {
        if i%997 == 0 {
            sum += i
        } else {
            sum -= i
        }
    }
    return sum
}

func main() {
    wg := sync.WaitGroup{}
    wg.Add(8)
    for i := 0; i < 8; i++ {
        go useCPU(&wg)
    }

    time.Sleep(2 * time.Second)
    printStat()

    wg.Wait()
}
```

**Describe alternatives you've considered:**

Maybe there are other libs that can obtain the CPU usage of a process in golang.

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by ziyi-yan** [comment]
I am working on this with a simple and quick implementation.

**Comment by ziyi-yan** [comment]
I use the suggested package from @zz-jason to make this simple solution. The implementation is not well considered, such as the interval of updating the gauges. Feedback is welcome!
