### ISSUE TITLE
leader and region balance ratio are 100%

### ISSUE THREAD

**Issue by hanyu100** [pingcap/tidb#8555]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
the servers upgraded to version 2.1
![image](https://user-images.githubusercontent.com/10152316/49357704-11322500-f70b-11e8-966b-50f9f0c2b837.png)

2. What did you expect to see?

Normally,The balance Ratio is less than 20%

3. What did you see instead?
Now，The Ratio is 100%

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.1.0
Git Commit Hash: 08f0168a6caea0280d6157e5be69f2dc6fd0d5b3
Git Branch: release-2.1
UTC Build Time: 2018-11-30 11:39:09
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by zimulala** [comment]
@hanyu100 
Thanks for your feedback!
PTAL @disksing

**Comment by disksing** [comment]
Hi @hanyu100 , could you show me the screenshot of all panels of the 'balance' section?

**Comment by fzhedu** [comment]
close it due to no response since Dec 2018.
