### ISSUE TITLE
How about tidb supporting UDF with lua

### ISSUE THREAD

**Issue by haoxiang47** [pingcap/tidb#8557]
## Feature Request

**Describe the feature you'd like:**

This idea just from the pingcap hackathon 2018, our team(@haoxiang47 @TennyZhuang @jiangplus) implemented a Lua based UDF. Now we want to continue this idea.

**Describe alternatives you've considered:**

During the hackathon, we implement a simple demo to use lua code to write a Fibonacci function and create this function to be a UDF. because of the time limit, we just use a simple method to finish this demo. 
1. we hack the parser to make it support CREATE FUNCTION syntax.
2. we make builtin function to support our new UDF.
3. we develop a simple UDF server to save Lua script and send it to tikv.
4. we add a new coprocessor in tikv to call Lua vm.
5. because of the constant folding with SQL Optimizer, it will make our UDF do not push down to the tikv, so we also implement a go-Lua module to run Lua in tidb directly.

In our mind, if tidb wants to fully support UDF, we should firstly make tidb-parser to support new syntax, then the PD maybe can replace the UDF server.  

This feature seems will have a huge change in tidb/tikv/tipb/tidb-parser/pd, so now we firstly open this issue to discuss a suitable design.

**Comment by XuHuaiyu** [comment]
Hi, @haoxiang47 @TennyZhuang @jiangplus
Thank you for your enthusiasm for TiDB.
What you've done was really cool.

Sure we need a detailed discussion for this huge feature.
Will it be ok that you write a proposal following [this doc](https://github.com/pingcap/tidb/tree/master/docs/design#tidb-design-documents).

**Comment by zz-jason** [comment]
> 5. because of the constant folding with SQL Optimizer, it will make our UDF do not push down to the tikv, so we also implement a go-Lua module to run Lua in tidb directly.

The place to control whether a UDF can be pushed down to TiKV coprocessor is controlled by this function:
```go
100 // PredicatePushDown implements LogicalPlan PredicatePushDown interface.
101 func (ds *DataSource) PredicatePushDown(predicates []expression.Expression) ([]expression.Expression, LogicalPlan) {
102     _, ds.pushedDownConds, predicates = expression.ExpressionsToPB(ds.ctx.GetSessionVars().StmtCtx, predicates, ds.ctx.GetClient())
103     return predicates, ds
104 }
```

**Comment by zz-jason** [comment]
Here is the document about MySQL UDF, hope it would be useful to the contributors who are interested in this issue: https://dev.mysql.com/doc/refman/5.7/en/adding-udf.html

**Comment by zz-jason** [comment]
Things needs to be considered:
- How to easily write a UDF? Program language, common API, etc.
- How to register a UDF to TiDB? Copy the UDF implementation to TiDB install dir? Upload the UDF through a client?
- How to control the UDF's privilege?
- How to control the resource used by the UDF? How many CPU cores, memory can the UDF gain?

**Comment by morgo** [comment]
This is great!  Is it possible to also use lua as a replacement for sql/psm triggers?

**Comment by TennyZhuang** [comment]
Hi all, here is our proposal.

https://docs.google.com/document/d/1jThyalBWLUgKrcy5NoghciEBnAlVvny_a1iLdUQa_3A/edit?usp=sharing

**Comment by haoxiang47** [comment]
Hi all, here is our proposal PR: https://github.com/pingcap/tidb/pull/8777

**Comment by zz-jason** [comment]
I'm going to close this issue since it's duplicated with https://github.com/pingcap/tidb/issues/17531. BTW https://github.com/pingcap/tidb/issues/17531 also has a bigger scope, we can discuss things about UDF in that issue.
