### ISSUE TITLE
docs:Please add some discription about the meaning of each directory

### ISSUE THREAD

**Issue by zxylvlp** [pingcap/tidb#857]
I think it is hard to know what the code mean without docs.
Please add the arch of the project.
It is bad to pre-contributor.

**Comment by shenli** [comment]
@zxylvlp Thanks for your advice.
We will add some docs for contributors.

**Comment by shenli** [comment]
@zxylvlp 
You can find some docs here: https://github.com/tidb-cn/docs
It is a starting and more docs are on the way.

**Comment by zxylvlp** [comment]
@shenli 
Thx for your reply.
