### ISSUE TITLE
number of rows less than 300K? 

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb#8583]
## Question
just want to double check

[best practice](https://pingcap.com/blog/2017-07-24-tidbbestpractice/) says this:

- Each row of data is less than 60MB
- **The total number of rows * (1+ the number of indexes) is less than 300,000 rows**
- The total data of a single commit is less than 100MB

what's the recommended practice if i have a table consisting of a few million rows? i think your [sysbench report](https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md) mentions a test with a table that has 10million rows.

**Comment by tiancaiamao** [comment]
> Each row of data is less than 60MB

60MB is a typo, it should be 6MB

> The total number of rows * (1+ the number of indexes) is less than 300,000 rows

This is also a mistaken representation. It should be:

> The total number of Key-Value entry is no more than 300,000 rows **in one transaction**

The key-value entries count of one row modification = 1 (this row itself) + number of indexes, 
so the key-value entries count of one transaction  (roughly) =  rows count * (1+ the number of indexes)  

DDL operation like "alter table add index" is not restricted by this.

The correct link is here:
https://github.com/pingcap/docs/blob/master/FAQ.md#the-error-message-transaction-too-large-is-displayed

Thanks for your feedback, we'll update our web site @tkalanick
