### ISSUE TITLE
Can't get index scan when index's columns >=3!

### ISSUE THREAD

**Issue by roger-lijian** [pingcap/tidb#859]
In the process of testing TPCC, I find a bug. If the index's column>=3,tidb can't use index scan.
like this:
```bash
mysql>  SELECT c_first, c_middle, c_last, c_street_1, c_street_2, c_city, c_state, c_zip, c_phone, c_credit, c_credit_lim, c_discount, c_balance, c_since FROM customer WHERE c_w_id = 1 AND c_d_id = 4 AND c_id = 2250;
+---------------+----------+--------------+----------------+---------------+----------------------+---------+-----------+------------------+----------+--------------+------------+-----------+---------------------+
| c_first       | c_middle | c_last       | c_street_1     | c_street_2    | c_city               | c_state | c_zip     | c_phone          | c_credit | c_credit_lim | c_discount | c_balance | c_since             |
+---------------+----------+--------------+----------------+---------------+----------------------+---------+-----------+------------------+----------+--------------+------------+-----------+---------------------+
| crxXDlgcTvLua | OE       | EINGCALLYESE | zckcHksOpSZLqm | SctxnccP5Xix6 | UX34HdLzWiowH7n23Deu | RW      | 256136851 | 3231895072206302 | BC       |        50000 |       0.25 |    -10.00 | 2016-01-15 10:20:46 |
+---------------+----------+--------------+----------------+---------------+----------------------+---------+-----------+------------------+----------+--------------+------------+-----------+---------------------+
1 row in set (11 min 7.03 sec)
```
this query execute 11min，table customer has primary key (c_id,c_d_id,c_w_id), obviously the query use table scan and get all record of table customer.

I write a simple example to describe this bug:
1,create table
create table t1(a int,b int,c int,d int,e int,primary key(a,b,c));
2,insert record
insert into t1 values(1,1,1,1,1),(2,2,2,2,2),(3,3,3,3,3),(4,4,4,4,4);
3,execute query
select * from t1 where a=2 and b=2 and c=2;

In the step 3, we can find tidb get all records from t1, the query use table scan instead of index scan. It should use index scan.

I trace the code and print log. I think the bug is caused by splitWhere in planbuilder.go:
```bash
--- a/optimizer/plan/planbuilder.go
+++ b/optimizer/plan/planbuilder.go
@@ -216,8 +216,8 @@ func (b *planBuilder) splitWhere(where ast.ExprNode) []ast.ExprNode {
        switch x := where.(type) {
        case *ast.BinaryOperationExpr:
                if x.Op == opcode.AndAnd {
-                       conditions = append(conditions, x.L)
-                       conditions = append(conditions, b.splitWhere(x.R)...)
+                       conditions = append(conditions, x.R)
+                       conditions = append(conditions, b.splitWhere(x.L)...)
                } else {
                        conditions = append(conditions, x)
                }
```
In the parser.y, expressions in where clause is parsed in left prec, so where a=2 and b=2 and c=2 is parsed into ((a=2 and b=2) and c=2), x.L may be a multi-expression like opcode.AndAnd. x.R is a single expression. splitWhere should return conditions like (a=2) (b=2) (c=2).

**Comment by coocood** [comment]
Thank you for your report, I'll fix the `splitWhere` bug, and also use multiple columns in a composite index.

**Comment by ngaut** [comment]
Cool, could you send a PR to fix it ? @roger-lijian

**Comment by coocood** [comment]
After a recent refactoring, multi-column index only uses the first column.

**Comment by ngaut** [comment]
@roger-lijian PTAL
