### ISSUE TITLE
Fail to deploy using tidb-ansible

### ISSUE THREAD

**Issue by wangpeng3477** [pingcap/tidb#8599]
在执行这个命令的时候 ansible-playbook bootstrap.yml遇到如下错误

Ansible FAILED! => playbook: bootstrap.yml; TASK: machine_benchmark : Preflight check - Does fio randread iops of tikv_data_dir disk meet requirement; message: {"changed": false, "msg": "fio: randread iops of tikv_data_dir disk is too low: 3265 < 40000, it is strongly recommended to use SSD disks for TiKV and PD, or there might be performance issues."}

但是我有100G的SSD数据盘 这个怎么设置让他通过检测

**Comment by tiancaiamao** [comment]
PTAL @LinuxGit

**Comment by tiancaiamao** [comment]
https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md

**Comment by tiancaiamao** [comment]
@wangpeng3477  Here is the document about how to set data dir
https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#%E5%A6%82%E4%BD%95%E8%87%AA%E5%AE%9A%E4%B9%89%E9%83%A8%E7%BD%B2%E7%9B%AE%E5%BD%95

**Comment by wangpeng3477** [comment]
这个错应该说的是我的ssd iops慢

**Comment by tiancaiamao** [comment]
Maybe you can try 'find tidb-ansible -type f | xargs grep 40000' to find the limit and change it manually @wangpeng3477

**Comment by wangpeng3477** [comment]
ok,I'll try it later

**Comment by shenli** [comment]
@wangpeng3477 We suggest using a better disk.
