### ISSUE TITLE
Some questions about tikv details

### ISSUE THREAD

**Issue by Tachone** [pingcap/tidb#8613]
We want to build a kv-database based on TiKv, database may support some semantic apis.
I have some questions that did not find on docs.
* TiKv only have a go-client currently, do you have to plan for a c++ TiKv client?
* RawKVClient has BatchGet/Put funcs, does TiKV guarantee request all success or not?
* Do you have more detail examples for TiKvClient usage? database-based is better

**Comment by tiancaiamao** [comment]
@Tachone 
There are Go and Java client, but no c++ client yet, and there is no plan or time schedule for c++ client as far as I know.
The protocol is defined in grpc https://github.com/pingcap/kvproto, it's possible to implement a c++ client porting the current Go code.

> RawKVClient has BatchGet/Put funcs, does TiKV guarantee request all success or not?

Yes



> Do you have more detail examples for TiKvClient usage? database-based is better

Redis compatible layer based on TiKV https://github.com/meitu/titan
Or the meta API in TiDB https://github.com/pingcap/tidb/blob/master/meta/meta.go

**Comment by Tachone** [comment]
@tiancaiamao thanks very much!

**Comment by shenli** [comment]
@Tachone We have a plan for c/c++ tikv client. See: https://github.com/c4pt0r/tikv-cpp  https://github.com/tikv/client-c

**Comment by Tachone** [comment]
@shenli very nice. Can this repo be fully tested or just a personal work?
any way, i will refer to this project, thanks a lot.

**Comment by siddontang** [comment]
@Tachone 

We have been building a Rust client and then we can provide a C wrapper client based on Rust, seem strange but it can work :-) 

Another way is to build a C++ client from scratch, if you are interested, you can help us(an RFC is required). At first, we can add sync APIs as @c4pt0r did above. Then we can go on and support async APIs.

**Comment by Tachone** [comment]
@siddontang surprise! How long will the rust client be released?

**Comment by gregwebs** [comment]
@tiancaiamao @shenli can we direct these questions to the TiKV org instead of answering them here? That will help get the most accurate answers and help others find them also.
