### ISSUE TITLE
sql_mode compatibility 

### ISSUE THREAD

**Issue by jianhaiqing** [pingcap/tidb#8636]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
*  run the following DDL both on TIBD and MySQL;

```
CREATE TABLE a (
  id int(11) DEFAULT NULL,
  agent_start_time timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
```

* sql_mode:

`TIDB: STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
MySQL: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION`

2. What did you expect to see?

TIDB: run OK.

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by jackysp** [comment]
Duplicated with #8637
