### ISSUE TITLE
doubling number of TiKV and TiDB nodes has no effect on overall throughput?

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb#8658]
## Question
i built a cluster according to the [hardware recommendations](https://github.com/pingcap/docs/blob/master/op-guide/recommendation.md#production-environment) using latest[ tidb-operator](https://github.com/pingcap/tidb-operator), (TiDB 2.1) on GKE.

and i was able to do 30K read qps. 

i had 20 million rows in the sbtest table and my query is:
`SELECT id, k, c FROM sbtest WHERE k = ${__Random(1,1000000,)};` 

Table definition:
`CREATE TABLE sbtest (id INT auto_increment, k INT NOT NULL, c VARCHAR(255) NOT NULL, pad TEXT, PRIMARY KEY (id), KEY k (k));`

i store 2K characters in the pad column. so i ended up with 433 regions.

in order to test scalability, i expanded my cluster to TiKVx6, TiDBx6, PDx4. with the same data set and the same query, i was only able to to 40K read qps. 

- TiKV: 20%-60% CPU usage (of 15.5 CPU/node), and 45% memory usage (of 32GB/node)
- TiDB: 20%-50% CPU usage (of 15.5 CPU/node)
- PD: one node at 50% CPU usage (of 4 CPU/node), other nodes are hardly used. memory usage is also low (1%).

on the client side, i have 5 jmeter slaves, each trying to establish 200 JDBC connections. 1000 threads are started on each salve. i tried to increase connection count and thread count but saw no effects on TiDB.
 
i don't see hot regions, where else should i look for performance bottlenecks? 

my goal is to build a correlation between cluster size and overall throughput at least for the following TiKV node numbers:
3, 6, 12, 24, 50, 100.
 
so far my correlation is:
3 node - 30K read QPS, 
6 node - 40K read QPS, 
...

not sure if that's what you would expect?
 
<img width="484" alt="screen shot 2018-12-11 at 11 27 05 am" src="https://user-images.githubusercontent.com/45215660/49828145-fa5d8500-fd3f-11e8-9802-555b36de2240.png">
<img width="709" alt="screen shot 2018-12-11 at 12 22 43 pm" src="https://user-images.githubusercontent.com/45215660/49828149-fcbfdf00-fd3f-11e8-9d5a-9c360e6a4147.png">
<img width="701" alt="screen shot 2018-12-11 at 12 23 02 pm" src="https://user-images.githubusercontent.com/45215660/49828150-fe89a280-fd3f-11e8-8e26-d14cb9138818.png">
<img width="940" alt="screen shot 2018-12-11 at 12 24 49 pm" src="https://user-images.githubusercontent.com/45215660/49828156-00536600-fd40-11e8-8cf8-12b9f7e88024.png">

<img width="1434" alt="screen shot 2018-12-11 at 12 29 01 pm" src="https://user-images.githubusercontent.com/45215660/49828862-d0a55d80-fd41-11e8-93d5-d720e031fc2f.png">

**Comment by tkalanick** [comment]
the issue seems to be caused by transactions.  i am getting linear scalability after i set my transaction isolation level to "READ UNCOMMITTED".

1. can you let me know where is the bottleneck when transaction is enabled on point select queries?

2. following graph shows a before and after throughput
- during the first half i was doing 100% "dirty read"
- during the second half i was doing 95% "dirty read" + 5% insert. 

notice there is a huge difference in overall throughput after the 5% insert traffic was introduced while the latency did change much. this seems to suggest that the JDBC client-server communication is serialized. do you agree that is the case?  

<img width="1342" alt="screen shot 2018-12-11 at 4 16 12 pm" src="https://user-images.githubusercontent.com/45215660/49841228-acf70d00-fd6b-11e8-8cf0-196f87097d54.png">

**Comment by shenli** [comment]
@tkalanick Thanks for your feedback!
I have a few questions about your test:
1. How many machines did you use in your test?
2. What type of disk did you use for TiKV instance?
3. From the SQL `SELECT id, k, c FROM sbtest WHERE k = ${__Random(1,1000000,)};` I guess that you only query the first 1 million data. These data may be located in a few regions. Is this by design?
4.  Could we access your grafana?

**Comment by tennix** [comment]
I believe the disk used in the benchmark is persistent ssd disk as documented in tidb-operator [gke tutorial](https://github.com/pingcap/tidb-operator/blob/master/docs/google-kubernetes-tutorial.md).

Currently, the local ssd disk performance is worse than persistent ssd disk. Because by default the local ssd disk is not mounted with `nobarrier` option and the [linux guest environment](https://github.com/GoogleCloudPlatform/compute-image-packages) is not installed on GKE node. These two settings impact performance a lot, but we cannot customize GKE node image.

**Comment by tkalanick** [comment]
@shenli 
i'd like to focus my question on the mixed read/write scenario. 

according to your [sysbench report](https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md), there is a 10 times difference between throughput read and write. the report didn't mention a mixed test.

what is expected behavior if you run a load test with 95% read and 5% write? it looks to me that the throughput is limited by the 5% write. meaning given an identical system setup.
if you do 100K QPS on read, and 10K QPS on write when testing separately, you can only get 10K QPS with 5% write + 95% read. is this expected?

**Comment by lysu** [comment]
@tkalanick 

1. just as #8674 's discuss, please don't `set read_uncommited`
2. we meet some disk problem in gke too, it's better to take care @tennix 's advise to check disk at first
3. current [sysbench report](https://github.com/pingcap/docs-cn/blob/master/benchmark/sysbench.md) doesn't give mixed r/w scenario, we will do it in furture. write is slower then read and write will consume more resource in both tidb/tidb and your test-jdbc, “标准oltp” will give some sense.
4. TSO is normal doesn't  be bottleneck, maybe take more look at TiKV's cpu & disk metrics
5. At last, I'm insteresting how you write test construct? is write is mixed with read in same transaction? or seperated in different transaction?

thx~

**Comment by tkalanick** [comment]
Hi Lysu, thanks for writing back.

i have attached the jmeter's test plan. if you don't like to read plain text, do the following:
1. rename attached JDBC_users.txt to JDBC_users.jmx. i had to rename it because github doesn't allow *.jmx files.
2. download [apache jmeter here](https://jmeter.apache.org/download_jmeter.cgi) and install.
3. launch jmeter UI and open JDBC_users.jmx

the test plan is executed using the [framework here](https://blog.kubernauts.io/load-testing-as-a-service-with-jmeter-on-kubernetes-fc5288bb0c8b). 

although not the case if you look at the JDBC_users.jmx file, because i have been trying different parameter combinations. in general i try to allocate 1 jmeter slave for every TiDB node. and start about 1000 threads on each slave. the JDBC connection pool size is about 40-50. however i don't know well this connection pool concept works in our distributed environment. 

[JDBC_users.txt](https://github.com/pingcap/tidb/files/2674844/JDBC_users.txt)

**Comment by lysu** [comment]
@tkalanick I just want to say disk is one useful check item.

it's better see more tikv/tidb/system metric to find reason, could you export you grafana metrics for that test time as pdf zip attachment? thx~

ps: Sorry, I'm not very familiar with jmeter,  but maybe `dbread` should be `autocommit=true` and `transactionIsolation=DEFAULT`...

**Comment by tkalanick** [comment]
thanks for the help.
