### ISSUE TITLE
Rolling upgrade failed, tikv error: version should compatible with version  3.0.0-alpha, got 2.1.0

### ISSUE THREAD

**Issue by alwaystest18** [pingcap/tidb#8667]
v2.1.0-rc.3升级到2.1GA
之前安装使用了tidb-ansible的master分支，本次下载了2.1的分支，修改了inventory.ini文件以及tikv.conf与原来保持一致，升级过程中出现`FAILED - RETRYING: check tikv's leader count` 错误，
最后报了`Timeout when waiting for search string TiDB in 10.x.x.x:10080`，跟进发现tikv启动失败，错误信息为
```
2018/12/12 16:18:20.554 ERRO util.rs:336: fail to request: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("version should compatible with version  3.0.0-alpha, got 2.1.0") }))
2018/12/12 16:18:20.554 ERRO tikv-server.rs:235: failed to start node: Pd(Other(StringError("[src/pd/util.rs:344]: fail to request")))
```
求帮助

**Comment by alwaystest18** [comment]
inventory.ini文件与原来并非完全一致，比如原来
tidb_version = latest
现在是tidb_version = v2.1.0

**Comment by alwaystest18** [comment]
这里再说下，一开始升级失败tikv_stderr.log出现了如下错误
`thread 'main' panicked at 'invalid auto generated configuration file "/data/deploy/data/last_tikv.toml", err invalid value: string "1d", expected valid duration, only h, m, s, ms are supported. for key `log-rotation-timespan`', src/config.rs:1120:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook
             at libstd/panicking.rs:227
   3: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   4: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   6: tikv_server::main
             at src/config.rs:1120
   7: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
   8: main
   9: __libc_start_main
  10: <unknown>`
手动修改将/data/deploy/data/last_tikv.toml中的log-rotation-timespan = "1d"改为log-rotation-timespan = "24h"后，出现了version should compatible with version 3.0.0-alpha, got 2.1.0的问题

**Comment by lysu** [comment]
@alwaystest18  Hi, what's your tikv version now?  could you paste the result of  `./tikv-server -V` and `./pd-server -V` result in `deploy/bin` folder? thanks~

**Comment by alwaystest18** [comment]
> ./tikv-server -V

Release Version:   3.0.0-alpha
Git Commit Hash:   aa5a5359f2470417e815f8456172bd478666fc63
Git Commit Branch: master
UTC Build Time:    2018-12-11 12:29:10
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by lysu** [comment]
@alwaystest18  emmm, tikv 3.0 is too new to pd 2.1, so maybe you should degrade tikv to 2.1, and keep tidb-pd-tikv all be 2.1

**Comment by alwaystest18** [comment]
@lysu 
first I execute `ansible-playbook rolling_update.yml --tags=tikv`
now tikv version is
`Release Version:   2.1.0
Git Commit Hash:   7db8e5b17c9084b5ddf950ae8547b568d144ca90
Git Commit Branch: release-2.1
UTC Build Time:    2018-12-08 07:35:07
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)`
but tikv can't start,the error is still `version should compatible with version  3.0.0-alpha, got 2.1.0`

**Comment by overvenus** [comment]
Hi @alwaystest18 

Looks like PD thinks you are trying to downgrade a marjor version, that is a false alarm. You can update the version recorded in PD via pd ctl.
`./pd-ctl -u "pd-address"  -d config set cluster-version "2.1.0"`

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
