### ISSUE TITLE
Dropping a column isn't reducing the disk size

### ISSUE THREAD

**Issue by clanstyles** [pingcap/tidb#8673]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Write a bunch of data, drop the column.

2. What did you expect to see?
The on disk size to go down

3. What did you see instead?
Stays the same, actually goes up a little bit.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
'Release Version: v2.0.7\nGit Commit Hash: 29ec059cb3b7d14b6f52c2f219f94a89570162bc\nGit Branch: release-2.0\nUTC Build Time: 2018-09-07 12:36:02\nGoVersion: go version go1.11 linux/amd64\nTiKV Min Version: 2.0.0-rc.4.1'
```

**Comment by zimulala** [comment]
@clanstyles 
After we do an operation of `drop column`, we only drop a column schema and don't drop the data Now.
We will drop the column data in the future.

**Comment by zimulala** [comment]
@clanstyles 
The problem of insufficient space due to not reclaiming the space after the "drop column" has not yet been resolved. We will deal with this issue.
