### ISSUE TITLE
GC life time is shorter than transaction duration

### ISSUE THREAD

**Issue by tkalanick** [pingcap/tidb#8674]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
 my setup is described in [issue #8658](https://github.com/pingcap/tidb/issues/8658).
basically i was doing a load test by running point select statements at 300K QPS on a [12 TiDB] and [12 TiKV] cluster. 
   
2. What did you expect to see?

not sure if it is expected. no warnings ? notice i am doing **dirty read** and **auto commit = false**

3. What did you see instead?
after 15 minutes TiDB service stops sending requests to TiKV
<img width="679" alt="screen shot 2018-12-12 at 12 29 36 pm" src="https://user-images.githubusercontent.com/45215660/49896958-a7500480-fe09-11e8-9854-8d9413077992.png">

see a lot of warning messages 

2018/12/12 20:20:45.713 conn.go:490: [warning] con:6088 dispatch error:
id:6088, addr:10.52.5.62:34678 status:1, collation:utf8_general_ci, user:test1
"SELECT id, k, c FROM sbtest WHERE k = 3275"
[tikv:9006]GC life time is shorter than transaction duration, transaction starts at 2018-12-12 19:59:28.052 +0000 UTC, GC safe point is 2018-12-12 20:06:43.852 +0000 UTC
github.com/pingcap/errors.AddStack
	/home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
	/home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20181206080309-80784c39ca74/terror/terror.go:231
github.com/pingcap/tidb/store/tikv.(*tikvStore).CheckVisibility
	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/store/tikv/kv.go:170
github.com/pingcap/tidb/store/tikv.(*copIterator).Next
	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/store/tikv/coprocessor.go:556
github.com/pingcap/tidb/distsql.(*selectResult).fetch
	/home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/distsql/select_result.go:85
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
V2.1

**Comment by lysu** [comment]
@tkalanick 

TiDB only offers the Repeatable Read isolation level.  https://pingcap.com/docs/sql/transaction-isolation/#tidb-transaction-isolation-levels, so it's no use to set 'read uncommited' and no dirty read and better not do that.

And for GC life time error, we are not recommend let transaction too long to N minutes, if that's your real requirement you can change GC time. https://pingcap.com/docs/FAQ/#error-9006-hy000-gc-life-time-is-shorter-than-transaction-duration, for your case it seems test cast forgot commit?
