### ISSUE TITLE
syncer exit unexpectly with an info "got signal [hangup], exit"

### ISSUE THREAD

**Issue by didi909** [pingcap/tidb#8675]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I want to made TiDB a readonly slave for Mysql,so I sync Mysql data to TiDB using shell :
nohup syncer -config ./syncer_all.toml 2>&1 1>> syncer_all.log &

2. What did you expect to see?
With no error 、 exception or manual stop signal , syncer can run continuously

3. What did you see instead?
syncer exit unexpectly with an info "got signal [hangup], exit"
<img width="1268" alt="1" src="https://user-images.githubusercontent.com/25740515/49913778-cca44780-fec9-11e8-9115-ac754fa5383a.png">

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.3-254-g36bcf5d

**Comment by lysu** [comment]
Hi @didi909  it seems `nohup`'s question, after run nohup, you need typein `exit` to exit current shell, if you close shell direct, program still will got SIGHUP too(https://blog.csdn.net/frockee/article/details/80356121 if can see chinese :laughing: )

maybe you can try `screen` or `tmux`, but It's better let syncer run in `systemd` like demon service to protect machine restart.

**Comment by didi909** [comment]
> Hi @didi909 it seems `nohup`'s question, after run nohup, you need typein `exit` to exit current shell, if you close shell direct, program still will got SIGHUP too(https://blog.csdn.net/frockee/article/details/80356121 if can see chinese 😆 )
> 
> maybe you can try `screen` or `tmux`, but It's better let syncer run in `systemd` like demon service to protect machine restart.

Hi,@Iysu, appreciate for your reply and it is realy a problem trigger by close the ssh terminal dirtectly. I am now using setsid to startup syncer and works well till this second
