### ISSUE TITLE
An error was reported after updating the configuration

### ISSUE THREAD

**Issue by xujingbin** [pingcap/tidb#8678]
## update tikv.yml:
grpc-concurrency = 8
grpc-raft-conn-num = 24 
[defaultcf]
block-cache-size = "12GB"
[writecf]
block-cache-size = "5GB"
[raftdb.defaultcf]
block-cache-size = "2GB"
## Question
tikv.log:
2018/12/13 14:03:37.269 ERRO endpoint.rs:468: Locked(primary_lock: "t\200\000\000\000\000\000\000?_i\200\000\000\000\000\000\000\001\0011099gaSI\3779QEcZdPT\377U9rl967b\3779\000\000\000\000\000\000\000\370\003\200\000\000\000\000\000\000\002\001109196\000\000\375\001AndroidG\377ame\000\000\000\000\000\372" lock_version: 404928860585459975 key: "t\200\000\000\000\000\000\000?_i\200\000\000\000\000\000\000\001\00120682279\37796\000\000\000\000\000\000\371\003\200\000\000\000\000\000\000\001\001109196\000\000\375\001AndroidG\377ame\000\000\000\000\000\372" lock_ttl: 3003)

**Comment by lysu** [comment]
@overvenus PTAL thx~

**Comment by overvenus** [comment]
Looks like Coprocessor meets locks, this is a recoverable error, tidb will try to resolve the lock later.

**Comment by dinggel** [comment]
The log is still reporting errors，the first error is 
2018/12/12 11:39:03.850 ERRO endpoint.rs:468: Locked(primary_lock:

**Comment by liaoxuefeng** [comment]
I had same issue.

**Comment by xujiapei** [comment]
I had same issue.do u resolve it

**Comment by liaoxuefeng** [comment]
> I had same issue.do u resolve it

No

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
