### ISSUE TITLE
Need enable tidb-vision option during install tidb-ansible

### ISSUE THREAD

**Issue by fengzhao** [pingcap/tidb#8681]
## Feature Request

**Is your feature request related to a problem? Please describe:**

用ansbile方式安装之后，没有tidb-vision这个组件。
**Describe the feature you'd like:**

希望能在ansible全局配置文件种，增加是否启用tidb-vision这个组件的选项
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by lysu** [comment]
@superlzs0476 PTAL thx

**Comment by superlzs0476** [comment]
@fengzhao  PTAL https://github.com/pingcap/tidb-ansible/blob/master/inventory.ini#L95-L96
tidb-ansible has this feature .

**Comment by fengzhao** [comment]
> @fengzhao PTAL https://github.com/pingcap/tidb-ansible/blob/master/inventory.ini#L95-L96
> tidb-ansible has this feature .

在哪里？你说的配置这个选项是在哪里？是master分支吗？


![image](https://user-images.githubusercontent.com/6206340/49987739-6d206780-ffaf-11e8-9969-e8dee88e0274.png)

**Comment by zimulala** [comment]
@fengzhao 
The URL( https://github.com/pingcap/tidb-ansible/blob/master/inventory.ini#L95-L96) is the master branch.

**Comment by fengzhao** [comment]
但是你确定这个95-96行的语句是控制tidb-vision的选项吗？

**Comment by superlzs0476** [comment]
This requested feature has a lower priority and no plans.

**Comment by fengzhao** [comment]
@superlzs0476  为什么这个需求的优先级就不考虑了呢？

**Comment by shenli** [comment]
@fengzhao The tidb-vision is not production ready and we do not have enough hands to maintain it.

**Comment by fengzhao** [comment]
@shenli  可以吧，你开源你说了算。

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
