### ISSUE TITLE
last_tikv.toml", err invalid value: string "1d", expected valid duration, only h, m, s, ms are supported

### ISSUE THREAD

**Issue by ljhmily** [pingcap/tidb#8682]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
update from 2.1-rc5 to 2.1-GA

2. What did you expect to see?
tikv startup normal.

3. What did you see instead?
thread 'main' panicked at 'invalid auto generated configuration file "/app/tidb/data/last_tikv.toml", err invalid value: string "1d", expected valid duration, only h, m, s, ms are supported. for key `log-rotation-timespan`', src/config.rs:1120:17
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook
             at libstd/panicking.rs:227
   3: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   4: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   6: tikv_server::main
             at src/config.rs:1120
   7: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
   8: main
   9: __libc_start_main
  10: <unknown>

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by overvenus** [comment]
A quick workdaround is changing `1d` to `24h`.

The panic shows the `rotation-timespan` is filled with `1d`, and tikv does not support `d`. The feature is supported in the commit https://github.com/tikv/tikv/commit/2077be14ba321cbea779cbb175424111806306e4. But it is included in the 2.1-GA. 

BTW, I wonder if you upgraded tikv from master to 2.1-GA.

**Comment by nullnotnil** [comment]
This bug has been fixed in TiDB 4.0. I am going to close this issue now, but please feel free to re-open if you have additional questions. Thanks!
