### ISSUE TITLE
tikv always has one that can't start.

### ISSUE THREAD

**Issue by 894383755** [pingcap/tidb#8691]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
我使用ansible启动tidb集群（3tikv、3pd、1tidb）

![image](https://user-images.githubusercontent.com/20180037/49982089-e0b57b00-ff95-11e8-9730-738625bbc9c1.png)
![_20181214114541](https://user-images.githubusercontent.com/20180037/49982099-e4e19880-ff95-11e8-937f-fc3cf44cb6c5.png)
![_20181214114549](https://user-images.githubusercontent.com/20180037/49982091-e14e1180-ff95-11e8-998f-6a8333684068.png)
![_20181214114549](https://user-images.githubusercontent.com/20180037/49982100-e4e19880-ff95-11e8-9fd0-e7926963b8d1.png)
![_20181214114553](https://user-images.githubusercontent.com/20180037/49982101-e57a2f00-ff95-11e8-86ba-881ab7bb2fd9.png)
![image](https://user-images.githubusercontent.com/20180037/49982129-06db1b00-ff96-11e8-9ca0-061327fcf5b1.png)

2. What did you expect to see?
tidb 集群正常启动。

3. What did you see instead?
ansible-playbook start.yml 时，只报tidb错误，但发现tikv有一台进程不存在。
我再次重启（这次配置2个tikv），仍只报tidb错误，有一台tikv进程不存在。
我再次重启（这次只配置1个tikv），仍只报tidb错误，有一台tikv进程不存在。
4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

**Comment by siddontang** [comment]
maybe you meet the same problem here https://github.com/pingcap/tidb/issues/8683#issuecomment-446968165

can you check it at first? @894383755

**Comment by 894383755** [comment]
@shenli 好像不一样，我这边tikv日志没有报错，也没有升级，都是从新安装的。
不正常的：
![image](https://user-images.githubusercontent.com/20180037/49986960-ab685780-ffac-11e8-8488-7f8c2f8e6ee1.png)
正常的：
![image](https://user-images.githubusercontent.com/20180037/49986979-b91ddd00-ffac-11e8-9b1d-d8f0b42965f2.png)

**Comment by siddontang** [comment]
any message in tikv error log?

**Comment by 894383755** [comment]
tikv.log:
2018/12/17 16:51:51.202 INFO util.rs:406: connecting to PD endpoint: "192.100.1.79:2379"
2018/12/17 16:51:51.207 INFO util.rs:406: connecting to PD endpoint: "192.100.1.80:2379"
2018/12/17 16:51:51.209 INFO util.rs:406: connecting to PD endpoint: "192.100.1.89:2379"
2018/12/17 16:51:51.211 INFO util.rs:406: connecting to PD endpoint: "http://192.100.1.80:2379"
2018/12/17 16:51:51.213 INFO util.rs:406: connecting to PD endpoint: "http://192.100.1.79:2379"
2018/12/17 16:51:51.215 INFO util.rs:465: connected to PD leader "http://192.100.1.79:2379"
2018/12/17 16:51:51.215 INFO util.rs:394: All PD endpoints are consistent: ["192.100.1.79:2379", "192.100.1.80:2379", "192.100.1.89:2379"]
2018/12/17 16:51:51.217 INFO tikv-server.rs:421: connect to PD cluster 6634897751991172956
2018/12/17 16:51:51.227 INFO mod.rs:343: starting working thread: addr-resolver
2018/12/17 16:51:51.443 INFO mod.rs:343: starting working thread: storage-scheduler
2018/12/17 16:51:51.443 INFO mod.rs:343: starting working thread: gc-worker
2018/12/17 16:51:51.443 INFO mod.rs:597: Storage (RaftKv engine) started.
2018/12/17 16:52:06.640 INFO mod.rs:27: Welcome to TiKV.
Release Version:   3.0.0-alpha
Git Commit Hash:   e772a8cba1cbeeba1f6a001c4cf68724e3a2392e
Git Commit Branch: master
UTC Build Time:    2018-11-28 02:04:34
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)
2018/12/17 16:52:06.641 INFO tikv-server.rs:398: using config:
tikv_stderr.log:
![image](https://user-images.githubusercontent.com/20180037/50062161-865c2a80-01e0-11e9-9752-98186180a606.png)

**Comment by siddontang** [comment]
PTAL @LinuxGit 

seem that the TiKV starts successfully, but ansible shows failure, strange.

**Comment by LinuxGit** [comment]
```
$ cd /home/tidb/deploy/scripts
$ bash -x run_tikv.sh
```

And check if there're any errors.

**Comment by LinuxGit** [comment]
What's your Linux system destro and version? Could you post the result of the following commnad?
```
$ uname -a
```

It seems that the binaries could not run on your system.

**Comment by 894383755** [comment]
[root@ct7-85-tikv ~]# uname -a
Linux ct7-85-tikv 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

There's always a problem with tikv, and all the other tikv's working.

**Comment by 894383755** [comment]
same as others
44f6c8ce5fc5b553e0a45cde7358e2f0  bin/tikv-server
44f6c8ce5fc5b553e0a45cde7358e2f0  bin/tikv-server
44f6c8ce5fc5b553e0a45cde7358e2f0  bin/tikv-server

I also duplicate the replacement mode and can't start it properly.

I found that I could install tikv-server in another way and start it successfully (use tidb-latest-linux-amd64.tar.gz)
but i find other tikv-server is error：
2018/12/29 19:16:18.412 INFO util.rs:465: connected to PD leader "http://192.100.1.89:2379"
2018/12/29 19:16:18.412 INFO util.rs:394: All PD endpoints are consistent: ["192.100.1.89:2379", "192.100.1.90:2379", "192.100.1.91:2379"]
2018/12/29 19:16:18.414 INFO tikv-server.rs:421: connect to PD cluster 6640352509811249458
2018/12/29 19:16:18.426 INFO mod.rs:343: starting working thread: addr-resolver
2018/12/29 19:16:33.648 INFO mod.rs:27: Welcome to TiKV.

**Comment by LinuxGit** [comment]
What's your tidb-version in inventory.ini?
It seems that your tikv binary has some compile problem. Could you download latest version of tidb-ansible, and run following command to download specified version.

```
ansible-playbook local_prepare.yml
```

https://github.com/pingcap/docs-cn/blob/master/op-guide/ansible-deployment.md#在中控机器上下载-tidb-ansible

If you want to upgrade, you could refer to https://github.com/pingcap/docs-cn/blob/master/op-guide/tidb-v2.1-upgrade-guide.md.
