### ISSUE TITLE
error result when int join decimal

### ISSUE THREAD

**Issue by xucui220** [pingcap/tidb#8697]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
drop table if exists t1;
create table t1(i int  not null default 22, dc decimal(12,3) not null default 2.2) ;
insert into t1 values(1,1.1);
insert into t1 values(2,2.2);
insert into t1 values(3,3);
drop table if exists t2;
create table t2(i int , dc decimal(12,3)) ;
insert into t2 values(1,1.1);
insert into t2 values(2,2.2);
insert into t2 values(3,3);
select distinct t1.i,t2.dc from t1,t2 where t1.i=t2.dc ;

2. What did you expect to see?
mysql> select distinct t1.i,t2.dc from t1,t2 where t1.i=t2.dc ;
+---+-------+
| i | dc    |
+---+-------+
| 3 | 3.000 |
+---+-------+
1 row in set (0.00 sec)

3. What did you see instead?
mysql> select distinct t1.i,t2.dc from t1,t2 where t1.i=t2.dc ;
Empty set (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-302-ge4c3359
Git Commit Hash: e4c3359535a9a1d712a0f8ca66cd810083f83b0e
Git Branch: master
UTC Build Time: 2018-12-13 06:58:33
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by zz-jason** [comment]
@XuHuaiyu PTAL

**Comment by XuHuaiyu** [comment]
@qw4990 is working on this.

**Comment by XuHuaiyu** [comment]
``` go
tidb> show create table t;
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Table | Create Table                                                                                                                                                                                                            |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| t     | CREATE TABLE `t` (
  `a` int(11) DEFAULT NULL,
  `b` decimal(13,2) DEFAULT NULL,
  `c` decimal(14,4) DEFAULT NULL,
  KEY `idx_b` (`b`),
  KEY `idx_c` (`c`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin |
+-------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

tidb> select * from t;
+------+------+--------+
| a    | b    | c      |
+------+------+--------+
|    1 | 1.12 | 1.1200 |
+------+------+--------+
1 row in set (0.00 sec)

tidb> select /*+ TIDB_INLJ(t1,t2) */ * from t t1 join t t2 on t1.b = t2.c;
+------+------+--------+------+------+--------+
| a    | b    | c      | a    | b    | c      |
+------+------+--------+------+------+--------+
|    1 | 1.12 | 1.1200 |    1 | 1.12 | 1.1200 |
+------+------+--------+------+------+--------+
1 row in set (0.00 sec)

tidb> select /*+ TIDB_HJ(t1,t2) */ * from t t1 join t t2 on t1.b = t2.c;
Empty set (0.00 sec)
```
