### ISSUE TITLE
Load data doesn't handle  incorrect data correctly

### ISSUE THREAD

**Issue by xucui220** [pingcap/tidb#8699]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
drop table if exists t1;
create table t1(i int  default 2222 ,vc varchar(20),dc decimal(12,3) default -22.22) ;
load data local infile '/data/go/find_bug/data/t_default.tbl' into table t1 fields terminated by ',';

t_default.tbl:
, one,1.100
,two,0.020
1,three,
11,four,

2. What did you expect to see?
mysql> load data infile '/Users/xucui/find_bug/t_default.tbl' into table t1 fields terminated by ',';
ERROR 1366 (HY000): Incorrect integer value: '' for column 'i' at row 1

3. What did you see instead?
mysql> load data local infile '/data/go/find_bug/data/t_default.tbl' into table t1 fields terminated by ',';
Query OK, 4 rows affected, 4 warnings (0.02 sec)
mysql> show warnings;
+---------+------+----------------+
| Level   | Code | Message        |
+---------+------+----------------+
| Warning | 1265 | Data Truncated |
| Warning | 1265 | Data Truncated |
| Warning | 1105 | Bad Number     |
| Warning | 1105 | Bad Number     |
+---------+------+----------------+
4 rows in set (0.01 sec)
mysql> select * from t1;
+------+-------+-------+
| i    | vc    | dc    |
+------+-------+-------+
|    0 |  one  | 1.100 |
|    0 | two   | 0.020 |
|    1 | three | 0.000 |
|   11 | four  | 0.000 |
+------+-------+-------+
4 rows in set (0.00 sec)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.0-rc.3-302-ge4c3359
Git Commit Hash: e4c3359535a9a1d712a0f8ca66cd810083f83b0e
Git Branch: master
UTC Build Time: 2018-12-13 06:58:33
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)

**Comment by jackysp** [comment]
It's already fixed in master branch.
