### ISSUE TITLE
does syncer support ddl when mysql table structure changed or  a new table created

### ISSUE THREAD

**Issue by introspection3** [pingcap/tidb#8705]
does syncer support ddl when mysql table structure changed or  a new table created

**Comment by lysu** [comment]
@564064202  Yes, syncer will handle DDL QUERY_EVENT and sync them to target.

maybe can see detail at https://github.com/pingcap/blog-cn/blob/master/tidb-syncer.md

**Comment by 564064202** [comment]
![image](https://user-images.githubusercontent.com/12368358/51507754-54686480-1e2d-11e9-9b45-38ba09631a85.png)
NO,your answer is wrong

**Comment by 564064202** [comment]
pelase reopen it

**Comment by 564064202** [comment]
@lysu

**Comment by 564064202** [comment]
when there is a create table ddl sql, syncer will Fall into a Infinite loop

**Comment by tiancaiamao** [comment]
PTAL @GregoryIan

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
