### ISSUE TITLE
add a post process after physical plan generation in planner/core

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#8713]
This post process can be added in `DoOptimize()` in package "planner/core". In this post process, we can:

1. eliminate physical projection `eliminatePhysicalProjection`
2. infer parameter type for aggregate function arguments and build a `Project` child operator if necessary, that is: https://github.com/pingcap/tidb/blob/master/executor/builder.go#L956

So after this code change, the plan in `explain xx` is equals to `explain analyze xx`, and the plan generation is back to the "planner" package.

Hope this can make the code more readable and maintainable.

**Comment by qw4990** [comment]
I'm working on it

**Comment by morgo** [comment]
@qw4990 can this issue be closed now?
