### ISSUE TITLE
Does TiDB consider implement “The Rule System” refer to postgresql

### ISSUE THREAD

**Issue by tornadotang** [pingcap/tidb#8720]
## Does TiDB consider implement “The Rule System” refer to postgresql

Since TiDB have not implement stored procedure, the rule system can implement the similar function, which allow you accomplish some compatiblity.

i.e
previous:
select name from users where id = 1;

current:
when createTime < 2018
select name from users where id = 1;
when createTime >= 2018
select concat(prefix, name) as name from users where id = 1;

then we can use The Rule System to meet the Scenario

**Comment by shenli** [comment]
@tornadotang Please refine this issue or close it.

**Comment by lysu** [comment]
@tornadotang sorry, it's not our short roadmap now, but welcome to contribution :laughing:

**Comment by nullnotnil** [comment]
With the original question answered, I am going to close this issue for now. Please feel free to create a new issue if you have additional questions. Thanks!
