### ISSUE TITLE
Geo-distributed setup?

### ISSUE THREAD

**Issue by cweagans** [pingcap/tidb#8723]
Just curious about whether or not there's any guidance around running tidb across multiple data centers. The use case I'm looking at requires that data is available from multiple places around the world. Assuming I can provide a suitable network link, is there any issue with running tidb in this way? Are there any particular gotchas to look out for? Sorry this is kind of a vague question - I'm not 100% sure what I need to be asking here tbh. I'm looking for something like cockroachdb, but not cockroachdb.

**Comment by disksing** [comment]
Hi, @cweagans . We happen to be preparing a cross-DC deployment document. Related information I will provide later in this issue. I hope to be able to send a PR today (UTC+0800).

**Comment by cweagans** [comment]
Wow, what service! 😁 I look forward to seeing it and I'll happily test whatever you come up with if you let me know when it's in good shape!

**Comment by disksing** [comment]
Hi, we have finished the first draft of the cross-DC deployment solutions (not merged yet), you can view it through this link now: https://github.com/pingcap/docs/blob/b9921e9bcc02b17025a3e79fbab82cedb9bd4c7a/op-guide/cross-dc-deployment.md
Please let me know if there are any questions :smile:

**Comment by cweagans** [comment]
That gives me a lot of good information. I have a couple of specific questions:

1. Is there way to force the complete set of data to get replicated to all of the different members of the cluster? My use case will have all writes happening on one of the replicas, and then all of the other replicas will be read only (there will be a small server process co-located with each replica that will serve data to that geographic area).

2. If it's not possible to replicate all data to all members, will the data automatically be copied to where it's most actively used? Or is the location of any given record randomly determined?

3. Is there any limit on the number of data centers that could feasibly be added in this kind of setup? I'm looking at somewhere in the neighborhood of 10-15 separate locations eventually.

**Comment by disksing** [comment]
1, the default placement rule is to make the replicas as isolated as possible, so no extra settings are required. As long as your cluster contains enough DCs, the replicas will be arranged on different DCs. The read-only replica is actually under development. we call the feature _follower read_, which will make the raft follower or learner readable. Please stay tuned.

2, The locations are randomly determined, as long as they do not violate the isolation constraints. We do have longterm plan to support data locality but not in the near future.

3, No such restrictions. However, paying attention to high network latency between data centers can affect performance.

Hope this helps. :smile:

**Comment by disksing** [comment]
Closing it for inactivity. Please feel free to reopen if need.

**Comment by cweagans** [comment]
Thanks again for the information. This is good enough to get me started. I'm very interested in the read-only replica feature and data locality policies, but I don't think this is a showstopper for my current needs.
