### ISSUE TITLE
TIDB 启动报错--- FAILED - RETRYING: wait for PD up 

### ISSUE THREAD

**Issue by leoones** [pingcap/tidb#8727]
ansible-playbook start.yml

PLAY [check config locally] *********************************************************************************************************************************************************************

TASK [check_config_static : Ensure only one monitoring host exists] *****************************************************************************************************************************

TASK [check_config_static : Ensure monitored_servers exists] ************************************************************************************************************************************

TASK [check_config_static : Ensure TiDB host exists] ********************************************************************************************************************************************

TASK [check_config_static : Ensure PD host exists] **********************************************************************************************************************************************

TASK [check_config_static : Ensure TiKV host exists] ********************************************************************************************************************************************

TASK [check_config_static : Check ansible_user variable] ****************************************************************************************************************************************

TASK [check_config_static : Ensure timezone variable is set] ************************************************************************************************************************************

TASK [check_config_static : Close old SSH control master processes] *****************************************************************************************************************************
ok: [localhost]

PLAY [gather all facts, and check dest] *********************************************************************************************************************************************************

TASK [check_config_dynamic : Set enable_binlog variable] ****************************************************************************************************************************************

TASK [check_config_dynamic : Set deploy_dir if not set] *****************************************************************************************************************************************

TASK [check_config_dynamic : environment check (deploy dir)] ************************************************************************************************************************************
ok: [172.16.186.24]
ok: [172.16.186.23]
ok: [172.16.186.25]
ok: [172.16.186.22]

TASK [check_config_dynamic : Preflight check - Does deploy dir have appropriate permission] *****************************************************************************************************

TASK [check_config_dynamic : environment check (supervise)] *************************************************************************************************************************************

TASK [check_config_dynamic : config skip variables (default)] ***********************************************************************************************************************************
ok: [172.16.186.22]
ok: [172.16.186.23]
ok: [172.16.186.24]
ok: [172.16.186.25]

TASK [check_config_dynamic : config skip variables] *********************************************************************************************************************************************
ok: [172.16.186.22]
ok: [172.16.186.23]
ok: [172.16.186.24]
ok: [172.16.186.25]

TASK [check_config_dynamic : config skip variables] *********************************************************************************************************************************************

PLAY [monitored_servers] ************************************************************************************************************************************************************************

TASK [start node_exporter by supervise] *********************************************************************************************************************************************************

TASK [start node_exporter by systemd] ***********************************************************************************************************************************************************
changed: [172.16.186.23]
changed: [172.16.186.25]
changed: [172.16.186.22]
changed: [172.16.186.24]

TASK [wait for node_exporter up] ****************************************************************************************************************************************************************
ok: [172.16.186.25]
ok: [172.16.186.24]
ok: [172.16.186.23]
ok: [172.16.186.22]

PLAY [monitored_servers] ************************************************************************************************************************************************************************

TASK [start blackbox_exporter by supervise] *****************************************************************************************************************************************************

TASK [start blackbox_exporter by systemd] *******************************************************************************************************************************************************
changed: [172.16.186.23]
changed: [172.16.186.25]
changed: [172.16.186.24]
changed: [172.16.186.22]

TASK [wait for blackbox_exporter up] ************************************************************************************************************************************************************
ok: [172.16.186.24]
ok: [172.16.186.23]
ok: [172.16.186.25]
ok: [172.16.186.22]

PLAY [alertmanager_servers] *********************************************************************************************************************************************************************
skipping: no hosts matched

PLAY [monitoring_servers] ***********************************************************************************************************************************************************************

TASK [start monitoring modules by supervise] ****************************************************************************************************************************************************

TASK [start monitoring modules by systemd] ******************************************************************************************************************************************************
changed: [172.16.186.22] => (item=pushgateway-9091.service)
changed: [172.16.186.22] => (item=prometheus-9090.service)

TASK [wait for pushgateway up] ******************************************************************************************************************************************************************
ok: [172.16.186.22]

TASK [wait for prometheus up] *******************************************************************************************************************************************************************
ok: [172.16.186.22]

PLAY [kafka_exporter_servers] *******************************************************************************************************************************************************************
skipping: no hosts matched

PLAY [pd_servers] *******************************************************************************************************************************************************************************

TASK [start PD by supervise] ********************************************************************************************************************************************************************

TASK [start PD by systemd] **********************************************************************************************************************************************************************
changed: [172.16.186.22]

TASK [wait for PD up] ***************************************************************************************************************************************************************************

TASK [wait for PD up] ***************************************************************************************************************************************************************************
FAILED - RETRYING: wait for PD up (10 retries left).
FAILED - RETRYING: wait for PD up (9 retries left).
FAILED - RETRYING: wait for PD up (8 retries left).
FAILED - RETRYING: wait for PD up (7 retries left).
FAILED - RETRYING: wait for PD up (6 retries left).
FAILED - RETRYING: wait for PD up (5 retries left).
FAILED - RETRYING: wait for PD up (4 retries left).
FAILED - RETRYING: wait for PD up (3 retries left).
FAILED - RETRYING: wait for PD up (2 retries left).
FAILED - RETRYING: wait for PD up (1 retries left).
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 2] 没有那个文件或目录
fatal: [172.16.186.22]: FAILED! => {"attempts": 10, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: An unknown error occurred: [Errno 2] 没有那个文件或目录", "redirected": false, "status": -1, "url": "https://172.16.186.22:2379/pd/api/v1/members"}
        to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/start.retry

PLAY RECAP **************************************************************************************************************************************************************************************
172.16.186.22              : ok=11   changed=4    unreachable=0    failed=1   
172.16.186.23              : ok=7    changed=2    unreachable=0    failed=0   
172.16.186.24              : ok=7    changed=2    unreachable=0    failed=0   
172.16.186.25              : ok=7    changed=2    unreachable=0    failed=0   
localhost                  : ok=1    changed=0    unreachable=0    failed=0   

ERROR MESSAGE SUMMARY ***************************************************************************************************************************************************************************
[172.16.186.22]: Ansible FAILED! => playbook: start.yml; TASK: wait for PD up; message: {"attempts": 10, "changed": false, "content": "", "msg": "Status code was -1 and not [200]: An unknown error occurred: [Errno 2] 没有那个文件或目录", "redirected": false, "status": -1, "url": "https://172.16.186.22:2379/pd/api/v1/members"}
Ask for help:
Contact us: support@pingcap.com
It seems that you encounter some problems. You can send an email to the above email address, attached with the tidb-ansible/inventory.ini and tidb-ansible/log/ansible.log files and the error message, or new issue on https://github.com/pingcap/tidb-ansible/issues. We'll try our best to help you deploy a TiDB cluster. Thanks. :-)

**Comment by lysu** [comment]
@leoones Thanks for feedback~ 

@leoones @LinuxGit  PTAL

**Comment by LinuxGit** [comment]
Please make sure your pd process is running, and check if there are any errors in pd's log.
@liubo0127 @superlzs0476 PTAL

**Comment by leoones** [comment]
> 请确保您的pd进程正在运行，并检查pd日志中是否有任何错误。
> @ liubo0127 @ superlzs0476 PTAL

以下是我的pd.log和 pd运行情况
[tidb@tidb log]$ cat  pd.log
2018/12/18 22:24:07.696 cluster.go:488: [warning] store id:1 address:"172.16.186.24:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:24:07.696 cluster.go:488: [warning] store id:3 address:"172.16.186.25:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:24:07.696 cluster.go:488: [warning] store id:4 address:"172.16.186.23:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:24:23.676 tso.go:137: [warning] clock offset: 328.054542ms, prev: 2018-12-18 22:24:23.348810298 +0800 CST m=+14958.758231656, now: 2018-12-18 22:24:23.67686484 +0800 CST m=+14959.086286101
2018/12/18 22:24:33.635 tso.go:137: [warning] clock offset: 235.659155ms, prev: 2018-12-18 22:24:33.399875257 +0800 CST m=+14968.809296547, now: 2018-12-18 22:24:33.635534412 +0800 CST m=+14969.044955666
2018/12/18 22:25:07.697 cluster.go:488: [warning] store id:1 address:"172.16.186.24:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:25:07.697 cluster.go:488: [warning] store id:3 address:"172.16.186.25:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:25:07.697 cluster.go:488: [warning] store id:4 address:"172.16.186.23:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:25:26.260 main.go:105: [info] Got signal [15] to exit.
2018/12/18 22:25:26.260 server.go:250: [info] closing server
2018/12/18 22:25:26.261 leader.go:153: [info] server is closed, exit etcd leader loop
2018/12/18 22:25:26.261 coordinator.go:435: [info] label-scheduler stopped: context canceled
2018/12/18 22:25:26.261 server.go:322: [info] server is closed, exit metrics loop
2018/12/18 22:25:26.261 cluster.go:135: [info] coordinator: Stopped coordinator
2018/12/18 22:25:26.261 coordinator.go:435: [info] balance-region-scheduler stopped: context canceled
2018/12/18 22:25:26.261 coordinator.go:435: [info] balance-leader-scheduler stopped: context canceled
2018/12/18 22:25:26.261 coordinator.go:435: [info] balance-hot-region-scheduler stopped: context canceled
2018/12/18 22:25:26.261 leader.go:116: [error] campaign leader err server closed
github.com/pingcap/pd/server.(*Server).campaignLeader
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/leader.go:287
github.com/pingcap/pd/server.(*Server).leaderLoop
	/home/jenkins/workspace/build_pd_2.1/go/src/github.com/pingcap/pd/server/leader.go:115
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1333
2018/12/18 22:25:26.261 leader.go:75: [info] server is closed, return leader loop
2018/12/18 22:25:26.261 log.go:88: [info] etcdserver: [skipped leadership transfer for single member cluster]
2018/12/18 22:25:26.262 server.go:266: [info] close server
2018/12/18 22:26:58.429 util.go:56: [info] Welcome to Placement Driver (PD).
2018/12/18 22:26:58.429 util.go:57: [info] Release Version: v2.1.1
2018/12/18 22:26:58.429 util.go:58: [info] Git Commit Hash: 092362cbbd28a1da2c01bb249ad5c9ddd6bd8065
2018/12/18 22:26:58.429 util.go:59: [info] Git Branch: release-2.1
2018/12/18 22:26:58.429 util.go:60: [info] UTC Build Time:  2018-12-12 10:55:55
2018/12/18 22:26:58.429 metricutil.go:79: [info] disable Prometheus push client
2018/12/18 22:26:58.430 server.go:104: [info] PD config - {
  "client-urls": "http://172.16.186.22:2379",
  "peer-urls": "http://172.16.186.22:2380",
  "advertise-client-urls": "http://172.16.186.22:2379",
  "advertise-peer-urls": "http://172.16.186.22:2380",
  "name": "pd1",
  "data-dir": "/data1/deploy/data.pd",
  "initial-cluster": "pd1=http://172.16.186.22:2380",
  "initial-cluster-state": "new",
  "join": "",
  "lease": 3,
  "log": {
    "level": "info",
    "format": "text",
    "disable-timestamp": false,
    "file": {
      "filename": "/data1/deploy/log/pd.log",
      "log-rotate": true,
      "max-size": 300,
      "max-days": 0,
      "max-backups": 0
    }
  },
  "log-file": "",
  "log-level": "",
  "tso-save-interval": "3s",
  "metric": {
    "job": "pd1",
    "address": "",
    "interval": "0s"
  },
  "schedule": {
    "max-snapshot-count": 3,
    "max-pending-peer-count": 16,
    "max-merge-region-size": 0,
    "max-merge-region-keys": 0,
    "split-merge-interval": "1h0m0s",
    "patrol-region-interval": "100ms",
    "max-store-down-time": "30m0s",
    "leader-schedule-limit": 4,
    "region-schedule-limit": 4,
    "replica-schedule-limit": 8,
    "merge-schedule-limit": 8,
    "tolerant-size-ratio": 5,
    "low-space-ratio": 0.8,
    "high-space-ratio": 0.6,
    "disable-raft-learner": "false",
    "disable-remove-down-replica": "false",
    "disable-replace-offline-replica": "false",
    "disable-make-up-replica": "false",
    "disable-remove-extra-replica": "false",
    "disable-location-replacement": "false",
    "disable-namespace-relocation": "false",
    "schedulers-v2": [
      {
        "type": "balance-region",
        "args": null,
        "disable": false
      },
      {
        "type": "balance-leader",
        "args": null,
        "disable": false
      },
      {
        "type": "hot-region",
        "args": null,
        "disable": false
      },
      {
        "type": "label",
        "args": null,
        "disable": false
      }
    ]
  },
  "replication": {
    "max-replicas": 3,
    "location-labels": ""
  },
  "namespace": {},
  "cluster-version": "0.0.0",
  "quota-backend-bytes": "0 B",
  "auto-compaction-mode": "periodic",
  "auto-compaction-retention-v2": "1h",
  "TickInterval": "500ms",
  "ElectionInterval": "3s",
  "PreVote": true,
  "security": {
    "cacert-path": "",
    "cert-path": "",
    "key-path": ""
  },
  "label-property": null,
  "WarningMsgs": null,
  "namespace-classifier": "table"
}
2018/12/18 22:26:58.431 server.go:136: [info] start embed etcd
2018/12/18 22:26:58.431 log.go:88: [info] embed: [pprof is enabled under /debug/pprof]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [name = pd1]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [data dir = /data1/deploy/data.pd]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [member dir = /data1/deploy/data.pd/member]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [heartbeat = 500ms]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [election = 3000ms]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [snapshot count = 100000]
2018/12/18 22:26:58.432 log.go:88: [info] etcdserver: [advertise client URLs = http://172.16.186.22:2379]
2018/12/18 22:26:58.438 systime_mon.go:24: [info] start system time monitor
2018/12/18 22:26:58.514 log.go:88: [info] etcdserver: [restarting member 12e6ae86d2eedfbb in cluster 2172aa0da0496990 at commit index 25591]
2018/12/18 22:26:58.515 raft.go:656: [info] 12e6ae86d2eedfbb became follower at term 17
2018/12/18 22:26:58.515 raft.go:364: [info] newRaft 12e6ae86d2eedfbb [peers: [], term: 17, commit: 25591, applied: 0, lastindex: 25591, lastterm: 17]
2018/12/18 22:26:58.522 log.go:88: [info] mvcc: [restore compact to 23858]
2018/12/18 22:26:58.524 log.go:84: [warning] auth: [simple token is not cryptographically signed]
2018/12/18 22:26:58.527 log.go:88: [info] embed: [12e6ae86d2eedfbb starting with cors ["*"]]
2018/12/18 22:26:58.527 log.go:88: [info] embed: [12e6ae86d2eedfbb starting with host whitelist ["*"]]
2018/12/18 22:26:58.527 log.go:88: [info] etcdserver: [starting server... [version: 3.3.0+git, cluster version: to_be_decided]]
2018/12/18 22:26:58.529 log.go:88: [info] embed: [listening for peers on  172.16.186.22:2380]
2018/12/18 22:26:58.530 log.go:88: [info] etcdserver/membership: [added member 12e6ae86d2eedfbb [http://172.16.186.22:2380] to cluster 2172aa0da0496990]
2018/12/18 22:26:58.530 log.go:86: [info] etcdserver/membership: [set the initial cluster version to 3.3]
2018/12/18 22:26:58.530 log.go:88: [info] etcdserver/api: [enabled capabilities for version 3.3]
2018/12/18 22:27:03.017 raft.go:857: [info] 12e6ae86d2eedfbb is starting a new election at term 17
2018/12/18 22:27:03.017 raft.go:684: [info] 12e6ae86d2eedfbb became pre-candidate at term 17
2018/12/18 22:27:03.017 raft.go:755: [info] 12e6ae86d2eedfbb received MsgPreVoteResp from 12e6ae86d2eedfbb at term 17
2018/12/18 22:27:03.017 raft.go:669: [info] 12e6ae86d2eedfbb became candidate at term 18
2018/12/18 22:27:03.017 raft.go:755: [info] 12e6ae86d2eedfbb received MsgVoteResp from 12e6ae86d2eedfbb at term 18
2018/12/18 22:27:03.017 raft.go:712: [info] 12e6ae86d2eedfbb became leader at term 18
2018/12/18 22:27:03.017 node.go:306: [info] raft.node: 12e6ae86d2eedfbb elected leader 12e6ae86d2eedfbb at term 18
2018/12/18 22:27:03.018 log.go:88: [info] etcdserver: [published {Name:pd1 ClientURLs:[http://172.16.186.22:2379]} to cluster 2172aa0da0496990]
2018/12/18 22:27:03.018 log.go:88: [info] embed: [ready to serve client requests]
2018/12/18 22:27:03.019 log.go:86: [info] embed: [serving insecure client requests on 172.16.186.22:2379, this is strongly discouraged!]
2018/12/18 22:27:03.019 server.go:166: [info] create etcd v3 client with endpoints [http://172.16.186.22:2379]
2018/12/18 22:27:03.022 server.go:205: [info] init cluster id 6634795676908264200
2018/12/18 22:27:03.022 namespace_classifier.go:438: [info] load 0 namespacesInfo cost 348.772µs
2018/12/18 22:27:03.023 leader.go:95: [warning] leader is still name:"pd1" member_id:1361967831413874619 peer_urls:"http://172.16.186.22:2380" client_urls:"http://172.16.186.22:2379" , delete and campaign again
2018/12/18 22:27:03.040 cluster_info.go:71: [info] load 3 stores cost 1.77583ms
2018/12/18 22:27:03.042 cluster_info.go:77: [info] load 78 regions cost 971.176µs
2018/12/18 22:27:03.042 namespace_classifier.go:438: [info] load 0 namespacesInfo cost 289.498µs
2018/12/18 22:27:03.042 coordinator.go:208: [info] coordinator: Start collect cluster information
2018/12/18 22:27:03.043 tso.go:104: [info] sync and save timestamp: last 2018-12-18 22:25:26.450286745 +0800 CST save 2018-12-18 22:27:06.042792783 +0800 CST m=+7.630197160 next 2018-12-18 22:27:03.042792783 +0800 CST m=+4.630197160
2018/12/18 22:27:03.043 leader.go:263: [info] cluster version is 2.1.1
2018/12/18 22:27:03.043 leader.go:264: [info] PD cluster leader pd1 is ready to serve
2018/12/18 22:28:03.043 cluster.go:488: [warning] store id:1 address:"172.16.186.24:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:28:03.043 cluster.go:488: [warning] store id:3 address:"172.16.186.25:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:28:03.043 cluster.go:488: [warning] store id:4 address:"172.16.186.23:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:29:03.043 cluster.go:488: [warning] store id:3 address:"172.16.186.25:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:29:03.043 cluster.go:488: [warning] store id:4 address:"172.16.186.23:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:29:03.043 cluster.go:488: [warning] store id:1 address:"172.16.186.24:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:30:03.043 cluster.go:488: [warning] store id:3 address:"172.16.186.25:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:30:03.044 cluster.go:488: [warning] store id:4 address:"172.16.186.23:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica
2018/12/18 22:30:03.044 cluster.go:488: [warning] store id:1 address:"172.16.186.24:20160" version:"2.1.1"  may not turn into Tombstone, there are no extra up node has enough space to accommodate the extra replica

[tidb@tidb log]$ time curl -v "172.16.186.22:2379/pd/api/v1/members"
* About to connect() to 172.16.186.22 port 2379 (#0)
*   Trying 172.16.186.22...
* Connected to 172.16.186.22 (172.16.186.22) port 2379 (#0)
> GET /pd/api/v1/members HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.16.186.22:2379
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Headers: accept, content-type, authorization
< Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE
< Access-Control-Allow-Origin: *
< Content-Type: application/json; charset=UTF-8
< Date: Tue, 18 Dec 2018 14:32:32 GMT
< Content-Length: 685
< 
{
  "header": {
    "cluster_id": 6634795676908264200
  },
  "members": [
    {
      "name": "pd1",
      "member_id": 1361967831413874619,
      "peer_urls": [
        "http://172.16.186.22:2380"
      ],
      "client_urls": [
        "http://172.16.186.22:2379"
      ]
    }
  ],
  "leader": {
    "name": "pd1",
    "member_id": 1361967831413874619,
    "peer_urls": [
      "http://172.16.186.22:2380"
    ],
    "client_urls": [
      "http://172.16.186.22:2379"
    ]
  },
  "etcd_leader": {
    "name": "pd1",
    "member_id": 1361967831413874619,
    "peer_urls": [
      "http://172.16.186.22:2380"
    ],
    "client_urls": [
      "http://172.16.186.22:2379"
    ]
  }
}
* Connection #0 to host 172.16.186.22 left intact

real    0m0.011s
user    0m0.005s
sys     0m0.003s

**Comment by Mingdr** [comment]
so am I，I have the same problem with this

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open it if you continue to experience issues. Thanks!

**Comment by leoones** [comment]
> I am going to close this issue as stale. Please feel free to re-open it if you continue to experience issues. Thanks!

OK
