### ISSUE TITLE
does tidb support mysql database or  table structure sql just as information_schema.tables 

### ISSUE THREAD

**Issue by 564064202** [pingcap/tidb#8744]
does tidb support mysql database or  table structure sql just as information_schema.tables

**Comment by shenli** [comment]
@564064202 Yes, there is a database named `mysql` and `information_schema.tables` table in TiDB.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
