### ISSUE TITLE
Does TIDB support multiple ssd?

### ISSUE THREAD

**Issue by whyliyu** [pingcap/tidb#8756]
I have some machines, each of which mounts 6 ssd mounted on 6 dirs. I wonder if the TIKV instance support running with more than one ssd. 

If so, will this config in ansible file "inventory.ini" work?
[tikv_servers]
tikv-1 ansible_host=10.200.168.194 tikv_data_dir=/disk1/data,/disk2/data,...

**Comment by lamxTyler** [comment]
@whyliyu No, but you can have multiple tikv instances on single machine, see https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#option-2-use-the-cluster-topology-of-multiple-tikv-instances-on-each-tikv-node

**Comment by morgo** [comment]
You could also consider using LVM to combine the 6 disks into one volume group.  See the [example here](https://superuser.com/questions/83034/how-do-i-combine-two-hard-drives-in-ubuntu/84060#84060).

**Comment by guokr321** [comment]
I think it is a problem about sth. like file system midwares and tikv interaction. You need a midware to distribute the tikv file among different hardwares to parallel  process different part of the file.

**Comment by whyliyu** [comment]
Thanks a lot for your kind help! @lamxTyler @guokr321 @lamxTyler 
It seems to be true that tikv cannot use mutiple ssd simultaneously becuase its underlying strorage RocksDB can't;
But I found another way to use this 6 ssd together.
Exactly speaking，the problme is the fact that TIKV cannot use multiple directory path rather than multiple ssd. If we can mount the 6ssd on a single path, we can solve the problem;So，Using what @morgo suggested may be a good chioce.
What I have done is Using Raid0,by which I successfully mount the 6 ssd on a single path in my server, and TIKV has successfully started
