### ISSUE TITLE
Is there a way to specify aggregate algorithm in the SQL query?

### ISSUE THREAD

**Issue by mnikogit** [pingcap/tidb#8776]
目前有一个测试样例，相同的简单聚合函查询，

QUERY1: SELECT COUNT(*),COLA FROM TABLE WHERE COLB=1 GROUP BY COLA;
使用HashAgg。

QUERY2: SELECT COUNT(*),COLA FROM TABLE WHERE COLB=0 GROUP BY COLA;
使用StreamAgg。

总数据量相对集群规模很小，COLA建立了单列索引，COLB没有索引，
QUERY2的时长超过QUERY1 10倍以上。

**Comment by winoros** [comment]
@mnikogit Could you provide the `explain` and `explain analyze` result of this two SQL?
