### ISSUE TITLE
some errors which should be checked are ignored

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#8779]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Some errors which should be checked are ignored, which may leads some bugs;

These errors are in this [report](https://goreportcard.com/report/github.com/pingcap/tidb#ineffassign) (search key word "assignment to err" in this page);

2. What did you expect to see?

These errors should be checked;

3. What did you see instead?

These errors are ignored;

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

Release Version: v2.1.0-rc.3-354-g062267674
Git Commit Hash: 06226767499f33a34b5cdce08ef7749dc2426c62
Git Branch: ignored_err
UTC Build Time: 2018-12-24 02:36:24
GoVersion: go version go1.11.3 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by shenli** [comment]
@qw4990 [This PR](https://github.com/pingcap/tidb/pull/8770) will fix some of the ignored errors in the DDL package.

**Comment by zimulala** [comment]
@qw4990 
That PR is merged. If there are still problems, you can reopen it.

**Comment by zimulala** [comment]
@qw4990 
That PR is merged. If there are still problems, you can reopen it.
