### ISSUE TITLE
syncer: add a configuration to specially handle `use`

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#8784]
## Feature Request

**Is your feature request related to a problem? Please describe:**

proxysql + tidb，使用syncer同步binlog报错，表创建一直没有成功，一直在重试

**Describe the feature you'd like:**

经过测试，proxysql的use经过特殊处理

use db; create table ... 后面的操作会被忽略，所以表一直创建失败

**Describe alternatives you've considered:**

syncer对use db支持 db.table转换

如use db; create table ... 能支持参数设置，使syncer处理方式变更为 create db.table ...

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by GregoryIan** [comment]
now we are developing  `ast restore` feature (ref https://github.com/pingcap/tidb/issues/8532), we can implement `create db.table ...`

**Comment by GregoryIan** [comment]
@dayuanyuan1989 what is your company, what business scenarios do you use `syncer` users in? I would try my best to help you

**Comment by CrazyNash** [comment]
@GregoryIan Previously there was an issue https://github.com/pingcap/tidb/issues/8219 which discussed this issue a bit, but it's closed silently later. I have been waiting for this feature for a while, really excited to hear this good news. Can you share release plan of this change(#8532) ?

**Comment by GregoryIan** [comment]
you can get detail progress in
https://github.com/pingcap/tidb/issues/8532, items that with checked flag are finished

**Comment by CrazyNash** [comment]
@GregoryIan Hi, #8532 was closed, is this issue fixed together?

**Comment by WangXiangUSTC** [comment]
not do this now, we will do this later @CrazyNash

**Comment by CrazyNash** [comment]
From previous discussion, it's a quick fix when we have #8532 done. Can you pls provide a fix plan?

**Comment by WangXiangUSTC** [comment]
we have a tools called dm can do this, you can take a look https://github.com/pingcap/dm

**Comment by CrazyNash** [comment]
@WangXiangUSTC yes, I heard about DM, but it's pretty complicated comparing to the syncer. Can we get this simple work done together?

**Comment by WangXiangUSTC** [comment]
we are doing things about this on dm, you can take a look
https://github.com/pingcap/dm/pull/54 
after this pr is merged, we will support two mode like below,
1. use`test`; create table `t1` ....
2. create table `test`.`t1`

but the deadline is not clear.

**Comment by CrazyNash** [comment]
@WangXiangUSTC Thanks for your support,  pingcap/dm#54 was merged, is this fixed together in latest syncer? how to configure syncer to use test.tl model?

**Comment by WangXiangUSTC** [comment]
now dm support sql like `create table test.t1..`, can you use dm instead of syncer? @CrazyNash

**Comment by CrazyNash** [comment]
@WangXiangUSTC we have a script written upon syncer and quite easy to use, now we still hope get this feature in syncer so we can keep playing with the script. DM is too heavy for us at the moment. If this is not much work to do, can you please get this integrated?

**Comment by jebter** [comment]
Binlog is no longer recommended for use: https://docs.pingcap.com/tidb/dev/tidb-binlog-overview, so I will close it. If there are any updates, you can reopen it.
