### ISSUE TITLE
when I use in .NET (ef) variable 'tx_isolation' does not yet support value: SERIALIZABLE

### ISSUE THREAD

**Issue by 564064202** [pingcap/tidb#8793]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
use .NET (entity framework) code first.

2. What did you expect to see?

just like mysql

3. What did you see instead?
variable 'tx_isolation' does not yet support value: SERIALIZABLE

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
docker lastest version

MySql.Data.MySqlClient.MySqlException (0x80004005): variable 'tx_isolation' does not yet support value: SERIALIZABLE
   在 MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   在 MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   在 MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)

**Comment by 564064202** [comment]
how I can resolve this ?

**Comment by 564064202** [comment]
@lamxTyler finished

**Comment by lamxTyler** [comment]
@564064202 TiDB only supports Repeatable Read isolation level. You can change the isolation level configuration in the frame work.

**Comment by 564064202** [comment]
how I can do in .NET ?

**Comment by shenli** [comment]
@564064202 Please consult the .Net's document.

**Comment by 564064202** [comment]
no,we can't set any thing on entity framework (code first)

**Comment by zhexuany** [comment]
I also met this issue in jdbc mysql connector. https://github.com/pingcap/tidb/pull/862 brought this change. Some frameworks often send query like "SET SESSION TRANSACTION ISOLATION LEVEL SERIALIZABLE". 

Printing a warning message would be better in my opinion.  

@564064202 Regarding your case, you may change to release 2.0 which does not contain this change.

**Comment by morgo** [comment]
This was discussed in https://github.com/pingcap/tidb/issues/2712 and fixed in https://github.com/pingcap/tidb/pull/8625

The issue is that a user could lose data by being led to believe TiDB supports a stronger isolation level than it does.  Most clients ignore warnings.

**Comment by zhexuany** [comment]
@564064202 you can solve this by using the latest master. For more details, please refer to https://github.com/pingcap/tidb/pull/10065. Closing.
