### ISSUE TITLE
Tidb not supported on windows built it?

### ISSUE THREAD

**Issue by insionng** [pingcap/tidb#88]
C:\Users\insio>go get  github.com/pingcap/tidb
# github.com/pingcap/tidb/parser
E:\gopath\src\github.com\pingcap\tidb\parser\yy_parser.go:17: undefined: yyLexer
E:\gopath\src\github.com\pingcap\tidb\parser\yy_parser.go:18: undefined: yyParse

**Comment by shenli** [comment]
Thanks for your feedback.
Do you have github.com/qiuyesuifeng/golex  and github.com/qiuyesuifeng/goyacc in you GOPATH?

**Comment by qiuyesuifeng** [comment]
@insionng 
building tidb should use `make` to generate `parser/parser.go` and `parser/scanner.go` which is needed by `yy_parser.go`.

please refer README, use `go get -d github.com/pingcap/tidb` then `make`.
u can try again.

**Comment by insionng** [comment]
Because the windows do not "make" command, I compiled by writing shell.

make.sh/make.bat:

···
go get github.com/qiuyesuifeng/goyacc
go get github.com/qiuyesuifeng/golex
touch temp.XXXXXX
goyacc -o /dev/null -xegen "temp.XXXXXX" parser/parser.y
goyacc -o parser/parser.go -xe "temp.XXXXXX" parser/parser.y
rm -f "temp.XXXXXX"
rm -f y.output
···

**Comment by Unknwon** [comment]
@insionng you can make a PR for `make.bat` :clap:

**Comment by insionng** [comment]
@Unknwon Okay~

**Comment by Unknwon** [comment]
cc @ngaut

**Comment by ngaut** [comment]
Good job, looking forward for your PR

**Comment by insionng** [comment]
@ngaut https://github.com/pingcap/tidb/pull/130/files

**Comment by ngaut** [comment]
Done.
