### ISSUE TITLE
The error message for wrong collate is not properly

### ISSUE THREAD

**Issue by jackysp** [pingcap/tidb#8803]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create database abc charset=utf8mb4 collate=abc;
```

2. What did you expect to see?
```
mysql> create database abc charset=utf8mb4 collate=abc;
ERROR 1273 (HY000): Unknown collation: 'abc'
```

3. What did you see instead?
```
mysql> create database abc charset=utf8mb4 collate=abc;
ERROR 1115 (42000): Unknown character set: 'utf8mb4'
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.3-360-gc385cbdcc
Git Commit Hash: c385cbdcca83eeed283139814a7ea149e3116e66
Git Branch: master
UTC Build Time: 2018-12-25 07:07:49
GoVersion: go version go1.11.4 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by bb7133** [comment]
fixed by https://github.com/pingcap/parser/pull/301
