### ISSUE TITLE
Tidb support read/write seperate?

### ISSUE THREAD

**Issue by zhoffice** [pingcap/tidb#8823]
tidb是否支持读写分离呢？

**Comment by shenlijungg** [comment]
hi   @jackysp   read-only  write-only   That configuration file？

**Comment by jackysp** [comment]
No, each TiDB server support read/write. It's better to set them for read-only or write-only by the proxy.

**Comment by shenlijungg** [comment]
@jackysp   thanks!!!

**Comment by zhoffice** [comment]
@jackysp thanks

**Comment by yilongrong** [comment]
TiDB 5.0  PRM    https://asktug.com/t/topic/34614/26
