### ISSUE TITLE
get some error when using TiDB-Lightning

### ISSUE THREAD

**Issue by AIKiller** [pingcap/tidb#8830]
## Question
when I using TiDB-Lightning tool , I get some error in log file.
I use the tidb version is 2.1 and  ansible is ansible 2.6.11.

I don't see some error when I run start_lightning.sh.  but I get empty page in dashboard . such as 
![](http://ww1.sinaimg.cn/large/93d61c99gy1fyk5omkvt0j21h90nr40u.jpg)
and check log file can get some error info:
`2018/12/26 06:38:11.590 version.go:41: [info] Welcome to lightning
2018/12/26 06:38:11.590 version.go:42: [info] Release Version: v2.1.2
2018/12/26 06:38:11.590 version.go:43: [info] Git Commit Hash: 2428999ba2d053ffd695741d18da26918bfd5485
2018/12/26 06:38:11.590 version.go:44: [info] Git Branch: release-2.1
2018/12/26 06:38:11.590 version.go:45: [info] UTC Build Time: 2018-12-21 12:48:01
2018/12/26 06:38:11.590 version.go:46: [info] Go Version: go version go1.11.2 linux/amd64
2018/12/26 06:38:11.590 lightning.go:59: [info] cfg {"lightning":{"level":"info","file":"log/tidb_lightning.log","max-size":128,"max-days":28,"max-backups":14,"table-concurrency":8,"region-concurrency":8,"pprof-port":10089,"check-requirements":true},"tidb":{"host":"172.16.0.236","port":4000,"user":"root","status-port":10080,"pd-addr":"172.16.0.234:2379","sql-mode":"STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION","log-level":"error","distsql-scan-concurrency":16,"build-stats-concurrency":20,"index-serial-scan-concurrency":20,"checksum-table-concurrency":16},"checkpoint":{"enable":true,"schema":"tidb_lightning_checkpoint","driver":"file","keep-after-success":false},"mydumper":{"read-block-size":4096,"region-min-size":268435456,"data-source-dir":"/data1/deploy/mysql-back-up","no-schema":false,"character-set":"auto"},"black-white-list":null,"tikv-importer":{"addr":"172.16.0.234:20170","batch-size":500},"post-restore":{"compact":true,"checksum":true,"analyze":true},"cron":{"switch-mode":"5m0s","log-progress":"5m0s"},"config-file":"./conf/tidb-lightning.toml"}
2018/12/26 06:38:11.590 lightning.go:107: [error] failed to load mydumper source : mydumper dir not exists
github.com/pingcap/tidb-lightning/lightning/mydump.init
        /home/jenkins/workspace/build_tidb_lightning_2.1/go/src/github.com/pingcap/tidb-lightning/lightning/mydump/loader.go:18
github.com/pingcap/tidb-lightning/lightning.init
        <autogenerated>:1
main.init
        <autogenerated>:1
runtime.main
        /usr/local/go/src/runtime/proc.go:189
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
dir /data1/deploy/mysql-back-up
2018/12/26 06:38:11.590 main.go:52: [error] tidb lightning encountered error:mydumper dir not exists
github.com/pingcap/tidb-lightning/lightning/mydump.init
        /home/jenkins/workspace/build_tidb_lightning_2.1/go/src/github.com/pingcap/tidb-lightning/lightning/mydump/loader.go:18
github.com/pingcap/tidb-lightning/lightning.init
        <autogenerated>:1
main.init
        <autogenerated>:1
runtime.main
        /usr/local/go/src/runtime/proc.go:189
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
dir /data1/deploy/mysql-back-up`

How can help me ?

**Comment by eurekaka** [comment]
@WangXiangUSTC PTAL?

**Comment by eurekaka** [comment]
@csuzhangxc PTAL

**Comment by csuzhangxc** [comment]
> [error] failed to load mydumper source : mydumper dir not exists 

you must specify a correct path to you dumped files.
