### ISSUE TITLE
How to set up topic name by myself?

### ISSUE THREAD

**Issue by wl21787** [pingcap/tidb#8832]
## Question
How to set up kafka-topic name by myself?

When I use TiDB-binlog ,found some questions.
For example:
I don't konw the topic in the below: what does it mean?
![image](https://user-images.githubusercontent.com/21055334/50438152-ad74d380-0927-11e9-9eb9-73e5e980e256.png)

I just know "6636925016299136240" is clusterID，what does it mean? can I set it by myself?

I hope to receive your reply.

**Comment by eurekaka** [comment]
Thank you for the feedback, @csuzhangxc PTAL

**Comment by july2993** [comment]
```
# when db-type is kafka, you can uncomment this to config the down stream kafka, it will be the globle config kafka default
#[syncer.to]
# only need config one of zookeeper-addrs and kafka-addrs, will get kafka address if zookeeper-addrs is configed.
# zookeeper-addrs = "127.0.0.1:2181"
# kafka-addrs = "127.0.0.1:9092"
# kafka-version = "0.8.2.0"
# kafka-max-messages = 1024
#
#
# the topic name drainer will push msg, the default name is <cluster-id>_obinlog
# be careful don't use the same name if run multi drainer instances
# topic-name = ""
```
@wl21787 you can set it while `topic-name`
