### ISSUE TITLE
cannot use auth.callOpts

### ISSUE THREAD

**Issue by ligangbin117** [pingcap/tidb#8834]
when I try go api with:
https://github.com/tikv/tikv/blob/master/docs/clients/go-client-api.md
I got some errors:
# github.com/coreos/etcd/clientv3
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:116:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthEnable
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:121:74: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.AuthDisable
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:126:100: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserAdd
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:131:86: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserDelete
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:136:122: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserChangePassword
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:141:104: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGrantRole
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:146:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserGet
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:151:72: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserList
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:156:106: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.UserRevokeRole
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:161:80: cannot use auth.callOpts (type []"github.com/coreos/etcd/vendor/google.golang.org/grpc".CallOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".CallOption in argument to auth.remote.RoleAdd
/root/go/src/github.com/coreos/etcd/clientv3/auth.go:161:80: too many errors

I found this:
https://github.com/etcd-io/etcd/pull/10044

**Comment by ligangbin117** [comment]
I remove old etcd package with rm -rf /root/go/src/github.com/coreos/etcd
change import from github.com/coreos/etcd to go.etcd.io/etcd in go file.
then:

github.com/pingcap/tidb/store/tikv
/root/go/src/github.com/pingcap/tidb/store/tikv/kv.go:56:3: cannot use []"google.golang.org/grpc".DialOption literal (type []"google.golang.org/grpc".DialOption) as type []"go.etcd.io/etcd/vendor/google.golang.org/grpc".DialOption in field value

so rm -rf /root/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc
solved this problem

then I got error when I'm run example:
INFO[0000] [pd] create pd client with endpoints [192.168.199.113:2379]
ERRO[0003] [pd] failed to get cluster id: rpc error: code = DeadlineExceeded desc = context deadline
I suggest changing 192.168.199.113 to 127.0.0.1 in example.

**Comment by ligangbin117** [comment]
@jackysp  I just use `go get -v -u github.com/pingcap/tidb/store/tikv' to install package, and `go run example.go'. then I got errors. reference:
https://github.com/tikv/tikv/blob/master/docs/clients/go-client-api.md
I think this has something to do with the package.

**Comment by jackysp** [comment]
@nolouch , could you please take a look at the pd error message?

**Comment by nolouch** [comment]
duplicate with https://github.com/tikv/tikv/issues/3981．

**Comment by suilongfei** [comment]
@nolouch 你最后提供的这个链接已经没有内容了啊
the link you has given,is nothing in there.

PS: 你给的连接里面多了一个“.”
the link you has given,has a "." at the last
