### ISSUE TITLE
using appendVisitInfo does not preserve MySQL compatible errors

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#8838]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Using `appendVisitInfo` in `planner/core/planbuilder.go` is useful to ensure permission checks are applied correctly.  See PRs #8837, #8486 (incomplete) for examples.

But a privilege check fail results in a generic error:
```
tidb> SET GLOBAL innodb_commit_concurrency=16;
ERROR 1105 (HY000): privilege check fail
```
The MySQL compatible behaviour should be:

```
mysql> SET GLOBAL innodb_buffer_pool_size=1;
ERROR 1227 (42000): Access denied; you need (at least one of) the SUPER privilege(s) for this operation
```

**Describe the feature you'd like:**

My suggestion is that `appendVisitInfo` should have an additional argument which is the error upon failure.  i.e.

```
err = variable.ErrAccessDenied.GenWithStackByArgs(name, val)
b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SuperPriv, "", "", "", err)
```

I think that this argument should be compulsory, and for the first crack at it, undetermined errors can be set to `core.ErrPrivilegeCheckFail` (a new error code that is a hack: it will return the existing error code + message, which is not MySQL compatible).  Over time this hack code can be removed.

**Describe alternatives you've considered:**

* The error could be optional.. but since we want full error code/string compatibility, this sounds like carrying baggage for an easier upgrade.

* A different error code to `core.ErrPrivilegeCheckFail` could be used, or research could be done to correctly identify the correct error code in all cases, but the patch may be large considering the number of test cases that may break.  I instead prefer to migrate the messages to the correct code over followup PRs, and then delete `core.ErrPrivilegeCheckFail`.

**Teachability, Documentation, Adoption, Migration Strategy:**

* Requires minimal docs since it is the MySQL compatible behaviour.
* Requires good follow-through to make sure remaining `core.ErrPrivilegeCheckFail` examples are removed, but I can use `grep` + a checklist issue for new contributors to make sure they are handled.

There are that many cases to migrate:
```
morgo@ryzen:~/go/src/github.com/pingcap/tidb$ grep -rFi appendVisitInfo . | grep -v func
Binary file ./bin/tidb-server matches
Binary file ./cmd/explaintest/explain_test matches
./planner/core/planbuilder.go:			b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SuperPriv, "", "", "")
./planner/core/planbuilder.go:	b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SuperPriv, "", "", "")
./planner/core/planbuilder.go:			b.visitInfo = appendVisitInfo(b.visitInfo, mysql.AllPrivMask, show.Table.Schema.L, show.Table.Name.L, "")
./planner/core/planbuilder.go:		b.visitInfo = appendVisitInfo(b.visitInfo, mysql.CreateUserPriv, "", "", "")
./planner/core/planbuilder.go:		b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SuperPriv, "", "", "")
./planner/core/planbuilder.go:					b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SuperPriv, "", "", "")
./planner/core/planbuilder.go:	vi = appendVisitInfo(vi, mysql.GrantPriv, dbName, tableName, "")
./planner/core/planbuilder.go:		vi = appendVisitInfo(vi, item.Priv, dbName, tableName, "")
./planner/core/planbuilder.go:		vi = appendVisitInfo(vi, priv, dbName, tableName, "")
./planner/core/logical_plan_builder.go:	b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SelectPriv, dbName.L, tableInfo.Name.L, "")
./planner/core/logical_plan_builder.go:		b.visitInfo = appendVisitInfo(b.visitInfo, mysql.SelectPriv, dbName, t.Name.L, "")
./planner/core/logical_plan_builder.go:		b.visitInfo = appendVisitInfo(b.visitInfo, mysql.UpdatePriv, col.DBName.L, col.TblName.L, "")
./planner/core/logical_plan_builder.go:			b.visitInfo = appendVisitInfo(b.visitInfo, mysql.DeletePriv, tn.Schema.L, tn.TableInfo.Name.L, "")
./planner/core/logical_plan_builder.go:			b.visitInfo = appendVisitInfo(b.visitInfo, mysql.DeletePriv, dbName, v.Name.L, "")

```

**Comment by morgo** [comment]
@tiancaiamao, @shenli PTAL.  Thx!

**Comment by tiancaiamao** [comment]
Hi @morgo 
Currently I'm kind of busy. You know, focus on one thing at a period of time maybe more productive. I have plan to do that around 2019.2

We'll going to implement RBAC(Role-based access control) feature in TiDB enterprise edition according to https://dev.mysql.com/doc/refman/8.0/en/roles.html
And at the same time improve privilege compatibility, address something like this issue.

Features in TiDB enterprise edition would be provide by plugin, so we must make the implementation more flexible.
Access control implementation actually contains two details:
1. What actions are done
2. What privileges a role have

The core database provides 1, something like `appendVisitInfo`.
`What privileges a role have` and check the privileges leaves to higher level or plugin's work.
You suggestion is nice, we should, of course, make the error more user friendly.
I'll consider it in more details later.
