### ISSUE TITLE
support global status like 'uptime'

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#8842]
## Feature Request

**Is your feature request related to a problem? Please describe:**

TiDB does not support the status variable 'uptime'.  MySQL dbas use it idiomatically:
* I restart the server, I check it is the correctly rebooted.
* My client disconnected.  Was it because of a server crash?  check uptime.
* has the server freshly started?  = slow performance (not applicable to tidb, since it's stateless).

So it is not critical but helps improve 'comfort'.

**Describe the feature you'd like:**

`SHOW GLOBAL STATUS like 'Uptime'` should report uptime in seconds.

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

Compatibility with MySQL.

**Comment by morgo** [comment]
> I found the command is `show status like 'uptime'` not `show global VARIABLES ...`.

Yes, you are right!  I've updated the description.

**Comment by laidahe** [comment]
How can the command be implemented? Is there any similar pr? I want to implement it.

**Comment by morgo** [comment]
@laidahe , yes see: https://github.com/pingcap/tidb/pull/8888

**Comment by laidahe** [comment]
You have implemented it?But I can not see test cases in [#8888](https://github.com/pingcap/tidb/pull/8888). @morgo

**Comment by morgo** [comment]
I am looking for feedback on how to test (see checklist).  The obvious way is to use sleep, but I am not sure that is acceptable :-) Looking for feedback.

**Comment by morgo** [comment]
Uptime information is available when prometheus is running:
```
 select * from  metrics_schema.uptime;
```
