### ISSUE TITLE
Does tidb support column compression or table compression？

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#8847]
Does tidb support column compression or table compression？  

https://dev.mysql.com/doc/refman/5.6/en/innodb-compression-tuning.html

**Comment by jackysp** [comment]
Hi @shenlijungg ,
Compression is not supported now. If the create table statement contains compression options, TiDB will ignore them.

**Comment by shenlijungg** [comment]
@jackysp  Without compression, how to get high performance of DML select?

**Comment by ngaut** [comment]
Compression is enabled by default inside TiKV.

**Comment by shenlijungg** [comment]
@ngaut  thanks
