### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#8849]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

● tikv-20160.service - tikv-20160 service
   Loaded: loaded (/etc/systemd/system/tikv-20160.service; disabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2018-12-27 17:47:40 CST; 26
  Process: 27373 ExecStart=/data/deploy/scripts/run_tikv.sh (code=exited, status=1/FAILURE)
 Main PID: 27373 (code=exited, status=1/FAILURE)
一直启动不起来, v2.1.2.1
TiKV 
Release Version:   2.1.2
Git Commit Hash:   509c8764cb14c173fc66d457639d9806449b890d
Git Commit Branch: release-2.1
UTC Build Time:    2018-12-21 05:39:30
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by 474420502** [comment]
哎, 这个更新搞到生产库都起不来.

**Comment by shenli** [comment]
Is there any error log for tikv-server?

**Comment by 474420502** [comment]
2018/12/27 17:30:27.744 INFO <unknown>:1279: [region 335325] 335327 sends MsgTimeoutNow to 362772 immediately as 362772 already has up-to-date log
2018/12/27 17:30:27.764 INFO <unknown>:920: [region 335325] 335327 [term: 38] received a MsgRequestVote message with higher term from 362772 [term: 39]
2018/12/27 17:30:27.764 INFO <unknown>:719: [region 335325] 335327 became follower at term 39
2018/12/27 17:30:27.764 INFO <unknown>:1083: [region 335325] 335327 [logterm: 38, index: 87, vote: 0] cast MsgRequestVote for 362772 [logterm: 38, index: 87] at term 39
2018/12/27 17:30:27.871 INFO pd.rs:575: [region 417390] try to transfer leader from id: 417391 store_id: 1 to id: 764686 store_id: 7
2018/12/27 17:30:27.943 INFO <unknown>:920: [region 585728] 769271 [term: 21] received a MsgRequestVote message with higher term from 585729 [term: 22]
2018/12/27 17:30:27.943 INFO <unknown>:719: [region 585728] 769271 became follower at term 22
2018/12/27 17:30:27.943 INFO <unknown>:1083: [region 585728] 769271 [logterm: 21, index: 52, vote: 0] cast MsgRequestVote for 585729 [logterm: 21, index: 52] at term 22
2018/12/27 17:30:27.943 INFO peer.rs:1485: [region 417390] 417391 transfer leader to id: 764686 store_id: 7
2018/12/27 17:30:27.943 INFO <unknown>:1269: [region 417390] 417391 [term 26] starts to transfer leadership to 764686
2018/12/27 17:30:27.943 INFO <unknown>:1279: [region 417390] 417391 sends MsgTimeoutNow to 764686 immediately as 764686 already has up-to-date log
2018/12/27 17:30:27.951 INFO snap.rs:756: [region 332965] scan snapshot /data/deploy/data/snap/gen_332965_25_58_(default|lock|write).sst, cf default, key count 2633, size 44937791
2018/12/27 17:30:27.951 INFO snap.rs:756: [region 332965] scan snapshot /data/deploy/data/snap/gen_332965_25_58_(default|lock|write).sst, cf lock, key count 0, size 0
2018/12/27 17:30:27.959 INFO peer_storage.rs:752: [region 782559] 782560 requesting snapshot...
2018/12/27 17:30:27.976 INFO snap.rs:756: [region 332965] scan snapshot /data/deploy/data/snap/gen_332965_25_58_(default|lock|write).sst, cf write, key count 2633, size 121118
2018/12/27 17:30:28.073 INFO <unknown>:920: [region 417390] 417391 [term: 26] received a MsgRequestVote message with higher term from 764686 [term: 27]
2018/12/27 17:30:28.073 INFO <unknown>:719: [region 417390] 417391 became follower at term 27
2018/12/27 17:30:28.073 INFO <unknown>:1083: [region 417390] 417391 [logterm: 26, index: 53, vote: 0] cast MsgRequestVote for 764686 [logterm: 26, index: 53] at term 27
2018/12/27 17:30:28.139 INFO snap.rs:857: [region 332965] scan snapshot /data/deploy/data/snap/gen_332965_25_58_(default|lock|write).sst, size 12786297, key count 5266, takes 1.206876684s
2018/12/27 17:30:28.613 ERRO endpoint.rs:468: Locked(primary_lock: "t\200\000\000\000\000\000\036\022_i\200\000\000\000\000\000\000\001\0010b08ea09\377-09ba-11\377e9-b\000\000\000\000\373" lock_version: 405249203307020310 key: "t\200\000\000\000\000\000\036\022_i\200\000\000\000\000\000\000\002\004\000\000\000\000\000\000\000#\003\200\000\000\000\000\000\000\000\004\031\241\266\227\233\000\000\000\003\200\000\000\000\006\241\000)" lock_ttl: 3010)
2018/12/27 17:30:29.419 INFO snap.rs:756: [region 782559] scan snapshot /data/deploy/data/snap/gen_782559_10_369_(default|lock|write).sst, cf default, key count 6954, size 105586088
2018/12/27 17:30:29.420 INFO snap.rs:756: [region 782559] scan snapshot /data/deploy/data/snap/gen_782559_10_369_(default|lock|write).sst, cf lock, key count 0, size 0
2018/12/27 17:30:29.478 INFO snap.rs:756: [region 782559] scan snapshot /data/deploy/data/snap/gen_782559_10_369_(default|lock|write).sst, cf write, key count 23440, size 1078240
2018/12/27 17:30:29.517 INFO snap.rs:385: [region 332965] sent snapshot 332965_25_58 [size: 12786297, dur: 356.572884ms]
2018/12/27 17:30:29.532 INFO peer.rs:115: [region 332965] report snapshot status id: 792185 store_id: 4 is_learner: true Finish
2018/12/27 17:30:29.676 INFO snap.rs:857: [region 782559] scan snapshot /data/deploy/data/snap/gen_782559_10_369_(default|lock|write).sst, size 23512457, key count 30394, takes 1.708046282s

重启不了TIKV没任何日志啊

**Comment by 474420502** [comment]
我回滚到rc版本就可以了, 吓出屎了.

**Comment by Connor1996** [comment]
you can search `Welcome` in tikv log, and paste some logs before it.

**Comment by 474420502** [comment]
我查了一下tikv的日志, 真是Erro 都有1G多 全部都是这些 几个月内都是这些.

**Comment by BusyJay** [comment]
How about tikv_stderr.log?

**Comment by 474420502** [comment]
@BusyJay 
pure virtual method called
pure virtual method called
pure virtual method called
pure virtual method called
terminate called without an active exception
terminate called recursively
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help
error: Found argument '--status-addr' which wasn't expected, or isn't valid in this context

USAGE:
    tikv-server --addr <IP:PORT> --advertise-addr <IP:PORT>

For more information try --help

**Comment by Connor1996** [comment]
Error log doesn't mean there are some unexpected behaviors. Don't worry. Most of the error logs are as expected and then try again.

**Comment by 474420502** [comment]
@Connor1996  但是我确实升级不了. 一直在rc版本了.

**Comment by Connor1996** [comment]
Oh, it seems that you didn't update your ansible, so it starts TiKV with wrong command arguments.

**Comment by 474420502** [comment]
@Connor1996  更新Python的ansible?

**Comment by 474420502** [comment]
如果是tidb-ansible我是更新了最新, 然后再local_prepare.yml

**Comment by Connor1996** [comment]
wait for a while, I am asking someone familiar with it to take a look.

**Comment by 474420502** [comment]
1b1492c (HEAD -> ***) HEAD@{0}: reset: moving to 1b1492c6bb93477ded41e58dfcdffb39bc6ef468
e4e4ae8 HEAD@{1}: commit (merge): Merge branch 'master' into ***
1b1492c (HEAD -> ***) HEAD@{2}: checkout: moving from master to ***
df133fd (origin/master, origin/HEAD, master) HEAD@{3}: pull: Fast-forward
95932b4 HEAD@{4}: checkout: moving from *** to master
1b1492c (HEAD -> ***) HEAD@{5}: commit: 滚动更新准备

**Comment by 474420502** [comment]
thanks! 
sorry!
I was scared out of shit just now!
I also smelled the stench!

**Comment by Connor1996** [comment]
Is that you use the master branch of tidb-ansible? You should use the release-2.1 branch of ansible.

**Comment by LinuxGit** [comment]
It seems that you use tidb-ansible master branch, and your tikv's binary is not latest version.

If you've deployed 2.1, and want to update, please see the following docs:
https://github.com/pingcap/docs-cn/blob/master/op-guide/tidb-v2.1-upgrade-guide.md

**Comment by 474420502** [comment]
忘记了， 合的很匆忙，几个问题同时进行。我再回头测试下， 谢。
