### ISSUE TITLE
Ssl doesn't work to open tls between mysql and tidb

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#8850]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

 #### To open tls between Mysql and TiDB as [MySQL 与 TiDB 间开启 TLS](https://pingcap.com/docs-cn/op-guide/security/)

- 准备证书
> mysql_ssl_rsa_setup --datadir=certs

- 配置单向认证

```
[security]
# Path of file that contains list of trusted SSL CAs.
ssl-ca = ""
# Path of file that contains X509 certificate in PEM format.
ssl-cert = "/root/certs/server.pem"
# Path of file that contains X509 key in PEM format.
ssl-key = "/root/certs/server-key.pem"
```
- restart tidb

> docker restart tidb

- 使用mysql-client 5.7连接

>　mysql -u root --host 127.0.0.1 --port 4000 --ssl-mode=REQUIRED -p

报错

```
Enter password: 
ERROR 2026 (HY000): SSL connection error: SSL is required but the server doesn't support it
```

2. What did you expect to see?

Can connect db successfully

3. What did you see instead?

error occur

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidb: v2.0.4

mysql-client: mysql  Ver 14.14 Distrib 5.7.24, for Linux (x86_64) using  EditLine wrapper

**Comment by jackysp** [comment]
Thanks for your report, @dayuanyuan1989 !
PTAL @breeswish

**Comment by breeswish** [comment]
Please take a look at TiDB logs. If you find something like "2018/12/29 14:02:01.136 server.go:188: [info] Secure connection is enabled (client verification enabled = false)", it means that TLS is enabled. Otherwise, it means that your configuration is incorrect. For example, maybe you can see something like:

```
2018/12/29 14:01:15.978 server.go:205: [warning] open /Users/breezewish/Work/PingCAP/certs/server.pem: no such file or directory
2018/12/29 14:01:15.978 server.go:194: [warning] Secure connection is NOT ENABLED
```

This means that the certificate you provided does not exist, so that TLS is not enabled.

Please refer to this documentation: [使用加密连接](https://github.com/pingcap/docs-cn/blob/1e8e61634e5814d48ab5f7255cc3d7b1ca51d145/sql/encrypted-connections.md)

I believe the documentation in [MySQL 与 TiDB 间开启 TLS](https://pingcap.com/docs-cn/op-guide/security/ is incorrect), which provides an incorrect certificate path. @Connor1996 Please fix the docs.

**Comment by Connor1996** [comment]
oh, my mistake, seems that the config should be
```
ssl-cert = "/root/certs/server-cert.pem"
```
instead of 
```
ssl-cert = "/root/certs/server.pem"
```

**Comment by dayuanyuan1989** [comment]
@Connor1996 

Thanks a lot, my tidb can work with ssl successfully by `单向认证`

Then, I test `配置双向认证`

```
[security]
# Path of file that contains list of trusted SSL CAs for connection with mysql client.
ssl-ca = "/data/certs/ca.pem"
# # # Path of file that contains X509 certificate in PEM format for connection with mysql client.
ssl-cert = "/data/certs/server-cert.pem"
# # # Path of file that contains X509 key in PEM format for connection with mysql client.
ssl-key = "/data/certs/server-key.pem"

```

I can find some key successful words in the log

```
{"file":"server.go","level":"info","line":182,"msg":"Secure connection is enabled (client verification enabled = true)","time":"2019/01/03 17:52:51.121"}
{"file":"server.go","level":"info","line":155,"msg":"Server is running MySQL Protocol at [0.0.0.0:4000]","time":"2019/01/03 17:52:51.121"}
```

Then, I use mysql-client to connect to server with ssl verification, error occur

> mysql --host 127.0.0.1 -uroot -P4000   --ssl-cert=certs/client-cert.pem --ssl-key=certs/client-key.pem --ssl-ca=certs/ca.pem --ssl-mode=VERIFY_IDENTITY
```
ERROR 2026 (HY000): SSL connection error: SSL certificate validation failure
```

**Comment by Connor1996** [comment]
Sorry, our neglect. I check the MySQL document, seems that the ssl-mode= VERIFY_IDENTITY doesn't not work for the certs generated by `mysql_ssl_rsa_setup`.
> Host name identity verification with VERIFY_IDENTITY does not work with self-signed certificates created automatically by the server, or manually using mysql_ssl_rsa_setup (see Section 6.4.3.1, “Creating SSL and RSA Certificates and Keys using MySQL”). Such self-signed certificates do not contain the server name as the Common Name value.

Please try other modes, like
```
mysql --host 127.0.0.1 -uroot -P4000 --ssl-cert=certs/client-cert.pem --ssl-key=certs/client-key.pem --ssl-ca=certs/ca.pem --ssl-mode=REQUIRED
```

**Comment by dayuanyuan1989** [comment]
Thanks a lot.

It worked successfully.
