### ISSUE TITLE
The latest version of the rolling upgrade has problems

### ISSUE THREAD

**Issue by weilain** [pingcap/tidb#8852]
Ansible FAILED! => playbook: rolling_update.yml; TASK: get PD leader info; message: {"changed": false, "content": "", "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://192.168.246.103:2379/pd/api/v1/leader"}

**Comment by jackysp** [comment]
Thanks for your report, @weilain !
Please show the latest version hash code of tidb-ansible.
PTAL @LinuxGit , @nolouch .

**Comment by LinuxGit** [comment]
Please make sure http://192.168.246.103:2379/pd/api/v1/leader page's return code is 200 and the pd instance is healthy.

**Comment by weilain** [comment]
cul

**Comment by weilain** [comment]
Failed connect to 172.16.246.103:2379; Connection refused

**Comment by weilain** [comment]
Version upgrade I did not involve the configuration file and the operation of the service. This problem did not occur in the last upgrade.

**Comment by weilain** [comment]
Can you give a query method?

**Comment by LinuxGit** [comment]
1. Please refer to https://github.com/pingcap/docs/blob/master/op-guide/tidb-v2.1-upgrade-guide.md.
2. `get PD leader info` task was run before updating your pd instance. It seems that your pd is not running.
3. Please check your pd process and logs in `${deploy_dir}/logs`.
Or you could start your pd instance by running `./start_pd.sh` in `${deploy_dir}/scripts` directory.

**Comment by weilain** [comment]
Yes, pd down, how do I start it?

**Comment by weilain** [comment]
tidb-ansible/scripts Directory not seen start_pd.sh

**Comment by weilain** [comment]
Confirm pd down, I want to start but did not find the startup file ，Trouble

**Comment by LinuxGit** [comment]
You could find deploy_dir info in https://github.com/pingcap/docs/blob/master/op-guide/ansible-deployment.md#configure-the-deployment-directory
