### ISSUE TITLE
syncer exited, error

### ISSUE THREAD

**Issue by jy4618272** [pingcap/tidb#8868]
1、What did you do? If possible, provide a recipe for reproducing the error.
when sync data from tidb to mysql 5.7

2、What did you expect to see?

3、What did you see instead?
[error] syncer exited, error /home/jenkins/workspace/build_tidb_binlog_2.1/go/src/github.com/pingcap/tidb-binlog/drainer/syncer.go:568: gen update sqls failed: table `demo`.`xxx_mem`:  row data is corruption [], schema: demo, table: xxx_mem

4、What version of TiDB are you using (tidb-server -V or run select tidb_version(); on TiDB)?
V 2.1.1

**Comment by csuzhangxc** [comment]
@jy4618272 I'll close this issue and if you have any problem you can reopen it.
