### ISSUE TITLE
how to clear all tidb binlog ？

### ISSUE THREAD

**Issue by jy4618272** [pingcap/tidb#8869]
when i use syncer to sync data from tidb to mysql ，the syncer crash and always fail （[error] syncer exited, error /home/jenkins/workspace/build_tidb_binlog_2.1/go/src/github.com/pingcap/tidb-binlog/drainer/syncer.go:568: gen update sqls failed: row data is corruption）. mybey the binlog data has some errors. how to clear all tidb binlog ？

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
