### ISSUE TITLE
add parameter to decide some rows to put in specific tikv instance.

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb#8880]
## Feature Request

**Is your feature request related to a problem? Please describe:**

some data are historical data and are rarely accessed , I hope put them to specific tikv instance based on HDD.
**Describe the feature you'd like:**

give a condition for exampe "t1.ts1 > 1546071291 = tikv11", the data in table t1 satisfying ts1 > 1546071291 can store in tikv11 instance.
**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

put some data in slow performance disks. improve the data govermance ability.

**Comment by zhuboshuai** [comment]
> Good suggestion, @zhuboshuai !
> We already have plans to do something similar.

thanks!

**Comment by zz-jason** [comment]
@nolouch Can we achieve this by [placement rules](https://docs.pingcap.com/tidb/stable/configure-placement-rules#placement-rules)?

**Comment by nolouch** [comment]
Yes, maybe you can use partition and move the partition to the HDD. something similar we are doing now, you can check it in https://github.com/pingcap/tidb/issues/18030. @zhuboshuai

**Comment by zz-jason** [comment]
I'm going to close this issue:

- TiDB 4.0 supports placement rule in PD. you can follow the [user document](https://docs.pingcap.com/tidb/stable/configure-placement-rules#placement-rules) to manually place code data to HDD disks.
- For usability improvement, defining placement rule with SQL is scheduled to be delivered in TiDB 5.0. It's a P0 priority feature, you can trace the progress in https://github.com/pingcap/tidb/issues/18030
