### ISSUE TITLE
did it support log_slave_updates variable？

### ISSUE THREAD

**Issue by wl21787** [pingcap/tidb#8883]
## Feature Request
when use tidb as mysql's slave,did it surpport log_slave_updates variables?

**Comment by jackysp** [comment]
No, `log_slave_updates` is not supported, @wl21787 .

**Comment by wl21787** [comment]
That is to say, Syner import data incrementally,but not write binlog to tidb?

**Comment by WangXiangUSTC** [comment]
syncer only translate mysql's binlog to sqls, and then execute these sqls to tidb. whether tidb write binlog depend on tidb's binlog config.

**Comment by wl21787** [comment]
I have already config enable_binlog = True.

The tidb process like this:
`bin/tidb-server -P 4000 --status=10080 --advertise-address=10.216.91.116 --path=10.216.91.116:2379,10.216.91.117:2379,10.216.91.118:2379 --config=conf/tidb.toml --enable-binlog --log-slow-query=/data/mysql/tidb/deploy/log/tidb_slow_query.log --log-file=/data/mysql/tidb/deploy/log/tidb.log`

The pump have already install and starting,but I dont't kown whether tidb  write binlog.

**Comment by WangXiangUSTC** [comment]
you can check pump's directory or monitoring in grafana.

**Comment by wl21787** [comment]
Thanks!

**Comment by WangXiangUSTC** [comment]
I close this issue now, you can reopen it if have other question.
