### ISSUE TITLE
about tranaction in tidb

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#8894]
I have a transaction, two target: resource and task

transaction steps:
1. select * from t_resource where state='idle' limit 1;
2. update t_resource set state='busy' where id={resource_id};
3. update t_job set resource_id={resource id};

It has some probability that two job use a same t_resource at the same time

for example

jobA, jobB run the transaction at the same time, when jobA to query a resource which id is `r111`, the jobB can also query the resource which id is `r111`

To parse the log, the work flow looks like as follows

jobA step | jobB step
--- | ---
step 1 |  --
step 2 | step 1
   --   |  step 2
  --  |  step 3
step 3 |  --

---
tidb-version: v2.0.4

the tranaction retry param `retry-count` is 10 in tidb configuration 

---

**My question**
- Is the workflow right in my case?
- to prevent the error in my case, must I to set  `retry-count` to 0?

**Comment by morgo** [comment]
I believe I understand the problem you are hinting at:
- The transactions `SELECT` data from the table.
- They then `UPDATE` with a modification based on what data they saw in the `SELECT`.
- If a retry occurs, there is a chance of a lost update.

To handle this correctly, I would recommend using `SELECT .. FOR UPDATE`.  The `FOR UPDATE` modifier will prevent retry, and cause an error if the data had been modified.  The behaviour is described in https://github.com/pingcap/tidb/issues/6591

Please let me know if I missed something here, or you have further questions.  Thanks!

**Comment by dayuanyuan1989** [comment]
@morgo 

Thanks for you quick reply

In mysql, my case can be handled correctly, a resource can not be assigned to two task

In tidb, the error occur, if I do not use `select ... for update` or do not set the `retry-count` to 0

---

I don't understand the reason of different behavior in transaction between tidb and mysql

If the program used mysql before, then use tidb instead, the logic will be error

Is it reasonable? Or pingcap has other thinking

**Comment by morgo** [comment]
The core difference is because TiDB uses optimistic locking instead of pessimistic locking as in MySQL.  While it can cause incompatibility, it is not unique to TiDB.  Many modern/distributed systems use optimistic because it performs better in the common-case where there are few conflicts.

This is [documented in the manual here](https://www.pingcap.com/docs/sql/mysql-compatibility/#transaction-model).

**Comment by dayuanyuan1989** [comment]
Thanks for your support. I had use `select ... for update` in my code.
