### ISSUE TITLE
add reverse iterator support in snapshot?

### ISSUE THREAD

**Issue by aronfan** [pingcap/tidb#8901]
Wish to add a reverse iterator in snapshot.
The reverse iterator had been implemented in transaction, but not in snapshot.

File: tidb/store/tikv/snapshot.go
Line: 294

**Comment by zz-jason** [comment]
@aronfan Could you provide some use cases about the reverse iterator?

**Comment by aronfan** [comment]
@zz-jason
In game development, we use ZRANGE and ZREVRANGE to rank players' score. The ZRANGE cmd can be implemented by the iterator in snapshot.

workaround: use ZCARD & ZRANGE to simulate the ZREVRANGE cmd if there's no reverse iterator in snapshot.

**Comment by zz-jason** [comment]
@zhangjinpeng1987 PTAL

**Comment by Defined2014** [comment]
This is now supported by https://github.com/pingcap/tidb/pull/45315, close this issue.
