### ISSUE TITLE
syncer failed to start

### ISSUE THREAD

**Issue by longhuguoji** [pingcap/tidb#8905]
我启动syncer，报如下错误，后来修改root密码，更改权限为%，所有客户端都能连接成功，但仍然报如下错误：
2019/01/02 17:19:20 printer.go:52: [info] Welcome to syncer
2019/01/02 17:19:20 printer.go:53: [info] Release Version: v1.0.0-51-gd2ff8d6
2019/01/02 17:19:20 printer.go:54: [info] Git Commit Hash: d2ff8d6639c29b1bcd7eafd7231e5707a864465d
2019/01/02 17:19:20 printer.go:55: [info] Git Branch: master
2019/01/02 17:19:20 printer.go:56: [info] UTC Build Time: 2018-12-12 06:27:14
2019/01/02 17:19:20 printer.go:57: [info] Go Version: go version go1.11.2 linux/amd64
2019/01/02 17:19:20 main.go:55: [info] config: {"log-level":"info","log-file":"","log-rotate":"day","status-addr":"20.4.18.43:10086","server-id":43,"meta":"./syncer.meta","persistent-dir":"","flavor":"mysql","worker-count":16,"batch":10,"max-retry":100,"replicate-do-table":[{"db-name":"pboc_tm","tbl-name":"pboc_tm"}],"replicate-do-db":null,"replicate-ignore-table":null,"replicate-ignore-db":null,"skip-sqls":null,"skip-dmls":null,"route-rules":[{"pattern-schema":"pboc_tm","pattern-table":"person_basicinf*","target-schema":"pboc_tm","target-table":"person_basicinf"}],"from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"localhost","user":"root","port":4000},"enable-gtid":false,"auto-fix-gtid":false,"disable-detect":false,"safe-mode":false,"config-file":"../conf/config.toml","stop-on-ddl":false,"execute-ddl-timeout":"3h","execute-dml-timeout":"1m","execute-queue-length":5000,"enable-ansi-quotes":false}
[2019/01/02 17:19:20] [info] binlogsyncer.go:132 create BinlogSyncer with config {43 mysql 20.4.17.6 3306 root    false false <nil> false UTC true 0 30s 1m0s 0 false}
2019/01/02 17:19:20 metrics.go:117: [info] listening on 20.4.18.43:10086 for status and metrics report.
2019/01/02 17:19:20 main.go:79: [error] Error 1045: Access denied for user 'root'@'20.4.18.43' (using password: YES)
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:436: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:405: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:528: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:182:

**Comment by csuzhangxc** [comment]
the error indicates access denied by the downstream instance (maybe TiDB), not the upstream MySQL.
have you changed the password with `%` for downstream instance?
and can connect to TiDB with the password from `20.4.18.43` with any MySQL client?

**Comment by longhuguoji** [comment]
是的，我修改了下游（TIDB）的密码和权限（%），但还是报同样的错。

> the error indicates access denied by the downstream instance (maybe TiDB), not the upstream MySQL.
> have you changed the password with `%` for downstream instance?
> and can connect to TiDB with the password from `20.4.18.43` with any MySQL client?

**Comment by csuzhangxc** [comment]
have you tested with other MySQL client？

**Comment by csuzhangxc** [comment]
and try to change `{"host":"localhost","user":"root","port":4000}` to `{"host":"20.4.18.43","user":"root","port":4000}` for `[to]`.

**Comment by longhuguoji** [comment]
> and try to change `{"host":"localhost","user":"root","port":4000}` to `{"host":"20.4.18.43","user":"root","port":4000}` for `[to]`.

localhost、127.0.0.1、20.4.18.43都试了，都不行。但是我通过navicat、其他服务器的mysql-client，都可以访问tidb。只是用syncer启动会报错。

**Comment by csuzhangxc** [comment]
> 2019/01/02 17:19:20 main.go:55: [info] config: {"log-level":"info","log-file":"","log-rotate":"day","status-addr":"20.4.18.43:10086","server-id":43,"meta":"./syncer.meta","persistent-dir":"","flavor":"mysql","worker-count":16,"batch":10,"max-retry":100,"replicate-do-table":[{"db-name":"pboc_tm","tbl-name":"pboc_tm"}],"replicate-do-db":null,"replicate-ignore-table":null,"replicate-ignore-db":null,"skip-sqls":null,"skip-dmls":null,"route-rules":[{"pattern-schema":"pboc_tm","pattern-table":"person_basicinf*","target-schema":"pboc_tm","target-table":"person_basicinf"}],"from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"localhost","user":"root","port":4000},"enable-gtid":false,"auto-fix-gtid":false,"disable-detect":false,"safe-mode":false,"config-file":"../conf/config.toml","stop-on-ddl":false,"execute-ddl-timeout":"3h","execute-dml-timeout":"1m","execute-queue-length":5000,"enable-ansi-quotes":false}
[2019/01/02 17:19:20] [info] binlogsyncer.go:132 create BinlogSyncer with config {43 mysql 20.4.17.6 3306 root false false false UTC true 0 30s 1m0s 0 false}
2019/01/02 17:19:20 metrics.go:117: [info] listening on 20.4.18.43:10086 for status and metrics report.
2019/01/02 17:19:20 main.go:79: [error] Error 1045: Access denied for user 'root'@'20.4.18.43' (using password: YES)

have you modified the log, or you copied them unchanged?

if `Access denied` with this trace stack, the error should be `Access denied for user 'root'@'20.4.17.6' (using password: YES)` not `Access denied for user 'root'@'20.4.18.43' (using password: YES)`

**Comment by csuzhangxc** [comment]
I mean, is the IP address in the log changed before you paste it here?
the error 
```
2019/01/02 17:19:20 main.go:79: [error] Error 1045: Access denied for user 'root'@'20.4.18.43' (using password: YES)
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:436:
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:405:
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:528:
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:182:
```
not match
```
"from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"localhost","user":"root","port":4000},
```

can you paste the content of `config.toml`?

**Comment by longhuguoji** [comment]
> I mean, is the IP address in the log modified before you paste it here?
> the error
> 
> ```
> 2019/01/02 17:19:20 main.go:79: [error] Error 1045: Access denied for user 'root'@'20.4.18.43' (using password: YES)
> /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:436:
> /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/db.go:405:
> /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:528:
> /home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:182:
> ```
> not match
> 
> ```
> "from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"localhost","user":"root","port":4000},
> ```
> can you paste the content of `config.toml`?

log-level = "info"

server-id = 43

## meta 文件地址
meta = "./syncer.meta"

worker-count = 16
batch = 10

## pprof 调试地址, Prometheus 也可以通过该地址拉取 syncer metrics
## 将 127.0.0.1 修改为相应主机 IP 地址
status-addr = "20.4.18.43:10086"

[[replicate-do-table]]
db-name ="pboc_tm"
tbl-name = "pboc_tm"

[[route-rules]]
pattern-schema = "pboc_tm"
pattern-table = "person_basicinf*"
target-schema = "pboc_tm"
target-table = "person_basicinf"




[from]
host = "20.4.17.6"
user = "root"
password = "jcfc@root"
port = 3306

[to]
host = "20.4.18.43"
user = "root"
password = "jcfc@root"
port = 4000

**Comment by csuzhangxc** [comment]
also the log with current `config.toml`?
at least the part from `Welcome to syncer` to `access denied for user`

**Comment by csuzhangxc** [comment]
the log above seems not to match the `config.toml` you paste?
can you paste the log with `config.toml` above?

**Comment by longhuguoji** [comment]
> the log above seems not to match the `config.toml` you paste?
> can you paste the log with `config.toml` above?

你说的是ip吧，我config.toml写的20.4.18.43，log输出:{"host":"localhost","user":"root","port":4000}。是这样，config.toml中的下游ip用localhost或者ip，输出的日志一样，我已经做过比对。如果用20.4.18.43，则输出日志:{"host":"20.4.18.43","user":"root","port":4000}。其他日志部分一模一样。

**Comment by csuzhangxc** [comment]
so, for the config
```
"from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"localhost","user":"root","port":4000},
```

the error is 
```
[error] Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
```
or 
```
[error] Error 1045: Access denied for user 'root'@'20.4.17.6' (using password: YES)
``

**Comment by longhuguoji** [comment]
> so, for the config
> 
> ```
> "from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"localhost","user":"root","port":4000},
> ```
> the error is
> 
> ```
> [error] Error 1045: Access denied for user 'root'@'localhost' (using password: YES)
> ```
> or
> 
> ```
> [error] Error 1045: Access denied for user 'root'@'20.4.17.6' (using password: YES)
> ``
> ```

无论config中下游配置ip、localhost或者127.0.0.1，日志始终输出下游登录失败，即'[error] Error 1045: Access denied for user 'root'@'20.4.18.43' (using password: YES)。不是'root'@'20.4.17.6'（即上游）。

**Comment by csuzhangxc** [comment]
> 日志始终输出下游登录失败

can you paste a whole log with 
```
"from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"127.0.0.1","user":"root","port":4000},
```

**Comment by longhuguoji** [comment]
> > 日志始终输出下游登录失败
> 
> can you paste a whole log with
> 
> ```
> "from":{"host":"20.4.17.6","user":"root","port":3306},"to":{"host":"127.0.0.1","user":"root","port":4000},
> ```

1、请问，tidb的root密码修改了，需要重启生效吗？如何进行重启或者如何生效？
2、TIDB官方修改root密码：SET PASSWORD FOR 'root'@'%' = 'xxx'; 
      MYSQL修改root密码：update user set password="" where user="root";    flush privileges;
      请问两者修改效果一样吗？

**Comment by longhuguoji** [comment]
> > 但是我通过navicat、其他服务器的mysql-client，都可以访问tidb。
> 
> you have tested and it takes effect, right?

我重新改了一下tidb密码，登录不上了，请帮忙回答一下如下问题。
1、请问，tidb的root密码修改了，需要重启生效吗？如何进行重启或者如何生效？
2、TIDB官方修改root密码：SET PASSWORD FOR 'root'@'%' = 'xxx';
MYSQL修改root密码：update user set password="" where user="root"; flush privileges;
请问两者修改效果一样吗？

**Comment by crazycs520** [comment]
TiDB 也需要用 `flush privileges;` 才能立即生效，负责会有一定延迟。
>TiDB 启动时，将一些权限检查的表加载到内存，之后使用缓存的数据来验证权限。系统会周期性的将授权表从数据库同步到缓存，生效则是由同步的周期决定，目前这个值设定的是5分钟。

>修改了授权表，如果需要立即生效，可以手动调用：

>FLUSH PRIVILEGES;

**Comment by Wythetells** [comment]
hi ,I have a problem with the same，
#mysql-server 10.92.6.16
mysql> show grants for bakup@10.92.6.68;
+---------------------------------------------------------------------------------------------------------------+
| Grants for bakup@10.92.6.68                                                                                   |
+---------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO 'bakup'@'10.92.6.68' IDENTIFIED BY PASSWORD '*87BDBFEF8F59A90F3B999095BDAEF5E62CA72896' |
| GRANT ALL PRIVILEGES ON `zabbix`.* TO 'bakup'@'10.92.6.68'                                                    |
+---------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)
#tidb-server 10.92.6.68  
mysql> show grants for bakup@10.92.6.68;
+----------------------------------------------------------+
| Grants for bakup@10.92.6.68                              |
+----------------------------------------------------------+
| GRANT ALL PRIVILEGES ON zabbix.* TO 'bakup'@'10.92.6.68' |
+----------------------------------------------------------+
1 row in set (0.00 sec)
#tidb login
[tidb@tidb-tipddb01-10-92-6-68 tidb-enterprise-tools-latest-linux-amd64]$ mysql -h10.92.6.68 -ubakup -P4000 -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 20283
Server version: 5.7.10-TiDB-v2.1.2-1-g8ba8096 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 
#mysql login
[tidb@tidb-tipddb01-10-92-6-68 tidb-enterprise-tools-latest-linux-amd64]$ mysql -h10.92.6.16 -ubakup -P3306 -p
Enter password: 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 15141196
Server version: 5.6.40-log MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> 

2019/01/10 11:43:15 main.go:79: [error] ERROR 1045 (28000): Access denied for user 'bakup'@'10.92.6.68' (using password: YES)
#use syncer
[tidb@tidb-tipddb01-10-92-6-68 tidb-enterprise-tools-latest-linux-amd64]$ ./bin/syncer -config syncer.config.toml
2019/01/10 11:59:53 printer.go:52: [info] Welcome to syncer
2019/01/10 11:59:53 printer.go:53: [info] Release Version: v1.0.0-58-gdd236a7
2019/01/10 11:59:53 printer.go:54: [info] Git Commit Hash: dd236a7499d5120f7f1df0ec7b3ae29ab2119bc4
2019/01/10 11:59:53 printer.go:55: [info] Git Branch: master
2019/01/10 11:59:53 printer.go:56: [info] UTC Build Time: 2019-01-01 04:58:46
2019/01/10 11:59:53 printer.go:57: [info] Go Version: go version go1.11.2 linux/amd64
2019/01/10 11:59:53 main.go:55: [info] config: {"log-level":"info","log-file":"","log-rotate":"day","status-addr":"127.0.0.1:10086","server-id":103,"meta":"./syncer.meta","persistent-dir":"","flavor":"mysql","worker-count":16,"batch":10,"max-retry":100,"replicate-do-table":null,"replicate-do-db":["zabbix"],"replicate-ignore-table":null,"replicate-ignore-db":null,"skip-sqls":null,"skip-dmls":null,"route-rules":null,"from":{"host":"10.92.6.16","user":"bakup","port":3306},"to":{"host":"192.168.6.68","user":"bakup","port":4000},"enable-gtid":false,"auto-fix-gtid":false,"disable-detect":false,"safe-mode":false,"config-file":"syncer.config.toml","stop-on-ddl":false,"execute-ddl-timeout":"3h","execute-dml-timeout":"1m","execute-queue-length":5000,"enable-ansi-quotes":false}
[2019/01/10 11:59:53] [info] binlogsyncer.go:132 create BinlogSyncer with config {103 mysql 10.92.6.16 3306 bakup    false false <nil> false UTC true 0 30s 1m0s 0 false}
2019/01/10 11:59:53 metrics.go:117: [info] listening on 127.0.0.1:10086 for status and metrics report.
[2019/01/10 11:59:53] [info] binlogsyncer.go:346 begin to sync binlog from position (mysql-bin.000457, 377745308)
[2019/01/10 11:59:53] [info] binlogsyncer.go:195 register slave for master server 10.92.6.16:3306
2019/01/10 11:59:53 syncer.go:956: [info] [syncer] last slave connection id 15141350
2019/01/10 11:59:53 main.go:79: [error] ERROR 1045 (28000): Access denied for user 'bakup'@'10.92.6.68' (using password: YES)
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:283: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:319: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:581: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:356: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:1056: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:551: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:189:  
[2019/01/10 11:59:53] [info] binlogsyncer.go:163 syncer is closing...
[2019/01/10 11:59:53] [info] binlogsyncer.go:178 syncer is closed


I check all of config,that is right,and i can login mysql from mysql-client,but con't use sysncer.
I don't know what I should to do.
please help me!thanks!

**Comment by Wythetells** [comment]
hi ,I have a problem with the same，
#mysql-server 10.92.6.16
mysql> show grants for bakup@10.92.6.68;
+---------------------------------------------------------------------------------------------------------------+
| Grants for bakup@10.92.6.68 |
+---------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON . TO 'bakup'@'10.92.6.68' IDENTIFIED BY PASSWORD '87BDBFEF8F59A90F3B999095BDAEF5E62CA72896' |
| GRANT ALL PRIVILEGES ON zabbix. TO 'bakup'@'10.92.6.68' |
+---------------------------------------------------------------------------------------------------------------+
2 rows in set (0.00 sec)
#tidb-server 10.92.6.68
mysql> show grants for bakup@10.92.6.68;
+----------------------------------------------------------+
| Grants for bakup@10.92.6.68 |
+----------------------------------------------------------+
| GRANT ALL PRIVILEGES ON zabbix.* TO 'bakup'@'10.92.6.68' |
+----------------------------------------------------------+
1 row in set (0.00 sec)
#tidb login
[tidb@tidb-tipddb01-10-92-6-68 tidb-enterprise-tools-latest-linux-amd64]$ mysql -h10.92.6.68 -ubakup -P4000 -p
Enter password:
Welcome to the MySQL monitor. Commands end with ; or \g.
Your MySQL connection id is 20283
Server version: 5.7.10-TiDB-v2.1.2-1-g8ba8096 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>
#mysql login
[tidb@tidb-tipddb01-10-92-6-68 tidb-enterprise-tools-latest-linux-amd64]$ mysql -h10.92.6.16 -ubakup -P3306 -p
Enter password:
Welcome to the MySQL monitor. Commands end with ; or \g.
Your MySQL connection id is 15141196
Server version: 5.6.40-log MySQL Community Server (GPL)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql>

2019/01/10 11:43:15 main.go:79: [error] ERROR 1045 (28000): Access denied for user 'bakup'@'10.92.6.68' (using password: YES)
#use syncer
[tidb@tidb-tipddb01-10-92-6-68 tidb-enterprise-tools-latest-linux-amd64]$ ./bin/syncer -config syncer.config.toml
2019/01/10 12:03:58 printer.go:52: [info] Welcome to syncer
2019/01/10 12:03:58 printer.go:53: [info] Release Version: v1.0.0-58-gdd236a7
2019/01/10 12:03:58 printer.go:54: [info] Git Commit Hash: dd236a7499d5120f7f1df0ec7b3ae29ab2119bc4
2019/01/10 12:03:58 printer.go:55: [info] Git Branch: master
2019/01/10 12:03:58 printer.go:56: [info] UTC Build Time: 2019-01-01 04:58:46
2019/01/10 12:03:58 printer.go:57: [info] Go Version: go version go1.11.2 linux/amd64
2019/01/10 12:03:58 main.go:55: [info] config: {"log-level":"info","log-file":"","log-rotate":"day","status-addr":"127.0.0.1:10086","server-id":103,"meta":"./syncer.meta","persistent-dir":"","flavor":"mysql","worker-count":16,"batch":10,"max-retry":100,"replicate-do-table":null,"replicate-do-db":["zabbix"],"replicate-ignore-table":null,"replicate-ignore-db":null,"skip-sqls":null,"skip-dmls":null,"route-rules":null,"from":{"host":"10.92.6.16","user":"bakup","port":3306},"to":{"host":"10.92.6.68","user":"bakup","port":4000},"enable-gtid":false,"auto-fix-gtid":false,"disable-detect":false,"safe-mode":false,"config-file":"syncer.config.toml","stop-on-ddl":false,"execute-ddl-timeout":"3h","execute-dml-timeout":"1m","execute-queue-length":5000,"enable-ansi-quotes":false}
[2019/01/10 12:03:58] [info] binlogsyncer.go:132 create BinlogSyncer with config {103 mysql 10.92.6.16 3306 bakup    false false <nil> false UTC true 0 30s 1m0s 0 false}
2019/01/10 12:03:58 metrics.go:117: [info] listening on 127.0.0.1:10086 for status and metrics report.
[2019/01/10 12:03:58] [info] binlogsyncer.go:346 begin to sync binlog from position (mysql-bin.000457, 377745308)
[2019/01/10 12:03:58] [info] binlogsyncer.go:195 register slave for master server 10.92.6.16:3306
2019/01/10 12:03:58 syncer.go:956: [info] [syncer] last slave connection id 15141915
2019/01/10 12:03:58 main.go:79: [error] ERROR 1045 (28000): Access denied for user 'bakup'@'10.92.6.68' (using password: YES)
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:283: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:319: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:581: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/pkg/mod/github.com/siddontang/go-mysql@v0.0.0-20181028041111-76c059e36c62/replication/binlogsyncer.go:356: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:1056: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:551: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/syncer/syncer.go:189:  
[2019/01/10 12:03:58] [info] binlogsyncer.go:163 syncer is closing...
[2019/01/10 12:03:58] [info] binlogsyncer.go:178 syncer is closed
I check all of config,that is right,and i can login mysql from mysql-client,but con't use sysncer.
I don't know what I should to do.
please help me!thanks!

**Comment by WangXiangUSTC** [comment]
@longhuguoji this error log show that you don't have the privilege to execute `SHOW GLOBAL VARIABLES LIKE 'sql_mode'` or `SHOW GLOBAL VARIABLES LIKE 'binlog_format'` in mysql, please check it.

**Comment by WangXiangUSTC** [comment]
@Wythetells I see that you only grant database `zabbix `'s privilege to the user, in fact, syncer need select , replication slave , replication client these privileges, Please grant these privileges and try again.

**Comment by longhuguoji** [comment]
@crazycs520  我还没有解决，咱俩问题一样。他们说的都解决不了。你如果解决了说一下解决方法。

**Comment by WangXiangUSTC** [comment]
@longhuguoji you can execute `SHOW GLOBAL VARIABLES LIKE 'sql_mode'` or `SHOW GLOBAL VARIABLES LIKE 'binlog_format'` success in mysql?

**Comment by longhuguoji** [comment]
@WangXiangUSTC sql_mode如下：ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION；
binlog_format: ROW

**Comment by WangXiangUSTC** [comment]
could you please show your privileges for user  'root' with 'localhost'、'127.0.0.1' and '20.4.18.43'? @longhuguoji

**Comment by longhuguoji** [comment]
@WangXiangUSTC User:'root'@'127.0.0.1'、User:'root'@'localhost'。没有配置‘20.4.18.43’

**Comment by WangXiangUSTC** [comment]
@longhuguoji please add grant for ‘20.4.18.43’ and try again

**Comment by WangXiangUSTC** [comment]
is this meta file grenerate by other user?  you can just chmod +666 to this file and try again

**Comment by Wythetells** [comment]
@WangXiangUSTC I used sudo TT

**Comment by WangXiangUSTC** [comment]
@longhuguoji @Wythetells  is your syncer work now?

**Comment by Wythetells** [comment]
@WangXiangUSTC yes ，my syncer is working ,but my syncer can only run in vty, if the window synchronization is turned off, it will end. I want it to run all the time.

**Comment by WangXiangUSTC** [comment]
you need use nohup run syncer @Wythetells

**Comment by WangXiangUSTC** [comment]
Seems your problem is solved, I will close this issue, you can reopen it if meet privileges question again. @Wythetells @longhuguoji

**Comment by longhuguoji** [comment]
> Seems your problem is solved, I will close this issue, you can reopen it if meet privileges question again. @Wythetells @longhuguoji

@WangXiangUSTC 非常感谢，按照你的方法已经解决了。
