### ISSUE TITLE
execution sql  appear privilege check fail  

### ISSUE THREAD

**Issue by weilain** [pingcap/tidb#8911]
docker-compose  deploy

-------------------------------
issue ：
mysql> update  tb_wehub_server a set a.active_count=a.active_count+1,a.used_count=a.used_count+1 where id=1;
ERROR 1105 (HY000): privilege check fail
![image](https://user-images.githubusercontent.com/42827119/50595149-310b6300-0eda-11e9-91ed-7c3f38ea1824.png)

MySQL [(none)]> select tidb_version();

| Release Version: v2.1.0-rc.3-385-ge730186
Git Commit Hash: e7301865a12c9dd8f5403c30be46e13c95f6de64
Git Branch: master
UTC Build Time: 2018-12-28 12:11:34
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
------------------------------------------------------------------------

**Comment by morgo** [comment]
Closing this issue - related bug has been fixed.
