### ISSUE TITLE
Incorrect row count estimation in TiDB 2.1.1

### ISSUE THREAD

**Issue by Guru107** [pingcap/tidb#8921]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

    Create a table with a composite primary key. 
```
CREATE TABLE `table1` (
`column_1` bigint(20) NOT NULL,
`column_2` int(11) NOT NULL,
`column_3` varchar(10) DEFAULT NULL,
`column_4` bigint(20) DEFAULT NULL,
`column_5` varchar(20) DEFAULT NULL,
`column_6` varchar(10) DEFAULT NULL,
`column_7` int(11) DEFAULT NULL,
`column_8` varchar(4) DEFAULT NULL,
`column_9` int(11) DEFAULT NULL,
`column_10` varchar(50) DEFAULT NULL,
`column_11` smallint(6) DEFAULT NULL,
`column_12` varchar(4000) DEFAULT NULL,
`column_13` decimal(10,2) DEFAULT NULL,
`column_14` decimal(10,2) DEFAULT NULL,
`column_15` decimal(10,2) DEFAULT NULL,
`column_16` varchar(1) DEFAULT NULL,
`column_17` datetime NOT NULL,
`column_18` varchar(200) DEFAULT NULL,
`column_19` varchar(2) DEFAULT NULL,
`column_20` text DEFAULT NULL,
`column_21` varchar(255) DEFAULT NULL,
`column_22` text DEFAULT NULL,
`column_23` varchar(50) DEFAULT NULL,
`column_24` varchar(20) DEFAULT NULL,
`column_25` bigint(20) DEFAULT NULL,
`column_26` varchar(1500) DEFAULT NULL,
`column_27` int(11) DEFAULT NULL,
`column_28` varchar(1000) DEFAULT NULL,
`column_29` text DEFAULT NULL,
`column_30` text DEFAULT NULL,
`column_31` decimal(10,2) DEFAULT NULL,
`column_32` decimal(10,2) DEFAULT NULL,
`column_33` decimal(10,2) DEFAULT NULL,
`column_34` decimal(10,2) DEFAULT NULL,
`column_35` datetime DEFAULT NULL,
`column_36` text DEFAULT NULL,
`column_37` varchar(5) DEFAULT NULL,
`column_38` int(11) DEFAULT NULL,
`column_39` varchar(1) DEFAULT NULL,
`column_40` varchar(1) DEFAULT NULL,
`column_41` varchar(5) DEFAULT NULL,
`column_42` int(11) DEFAULT NULL,
`column_43` varchar(5) DEFAULT NULL,
`column_44` decimal(10,2) DEFAULT NULL,
`column_45` decimal(10,2) DEFAULT NULL,
`column_46` int(11) DEFAULT NULL,
`column_47` decimal(10,2) DEFAULT NULL,
`column_48` varchar(5) DEFAULT NULL,
`column_49` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
`column_50` decimal(10,2) DEFAULT NULL,
`column_51` decimal(10,2) DEFAULT NULL,
`column_52` decimal(10,2) DEFAULT NULL,
`column_53` decimal(10,2) DEFAULT NULL,
`column_54` varchar(2) DEFAULT NULL,
`column_55` varchar(50) DEFAULT NULL,
`column_56` datetime DEFAULT NULL,
`column_57` varchar(500) DEFAULT NULL,
`column_58` varchar(5) DEFAULT NULL,
`column_59` varchar(100) DEFAULT NULL,
`column_60` varchar(10) DEFAULT NULL,
`column_61` datetime DEFAULT NULL,
`column_62` varchar(100) DEFAULT NULL,
`column_63` varchar(20) DEFAULT NULL,
`column_64` varchar(5) DEFAULT NULL,
`column_65` varchar(10) DEFAULT NULL,
`column_66` varchar(10) DEFAULT NULL,
`column_67` decimal(10,2) DEFAULT NULL,
`column_68` decimal(10,2) DEFAULT NULL,
`column_69` decimal(10,2) DEFAULT NULL,
`column_70` decimal(10,2) DEFAULT NULL,
`column_71` decimal(10,0) DEFAULT NULL,
`column_72` decimal(10,0) DEFAULT NULL,
`column_73` decimal(10,0) DEFAULT NULL,
`column_74` varchar(10) DEFAULT NULL,
`column_75` int(11) DEFAULT NULL,
`column_76` varchar(30) DEFAULT NULL,
`column_77` int(11) DEFAULT NULL,
`column_78` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (`column_1`,`column_2`),
  KEY `column_17` (`column_17`),
  KEY `column_49` (`column_49`),
  KEY `column_1` (`column_1`),
  KEY `column_40` (`column_40`),
  KEY `column_9` (`column_9`),
  KEY `column_43` (`column_43`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
```

Run query 
```explain select column1, column2 from `table1` where (column1=01092213 AND column2=1) OR (column1=01091904 AND column2=2) OR (column1=01091970 AND column2=2) OR (column1=01092706 AND column2=1) OR (column1=01092355 AND column2=1) OR (column1=01092578 AND column2=2) OR (column1=01092623 AND column2=4) OR (column1=01092651 AND column2=1) OR (column1=01092369 AND column2=2) OR (column1=01092365 AND column2=1) OR (column1=01092238 AND column2=2) OR (column1=01092799 AND column2=1) OR (column1=01092770 AND column2=3) OR (column1=01092363 AND column2=2) OR (column1=01092365 AND column2=2) OR (column1=01093579 AND column2=1) OR (column1=01093051 AND column2=2) OR (column1=01093032 AND column2=1) OR (column1=01093100 AND column2=2) OR (column1=01093534 AND column2=1) OR (column1=01093432 AND column2=1) OR (column1=01092914 AND column2=1) OR (column1=01092861 AND column2=2) OR (column1=01093054 AND column2=2) OR (column1=01093298 AND column2=1) OR (column1=01093293 AND column2=3);```

2. What did you expect to see?
Running `explain` on TiDB 2.0.8 returns
<img width="845" alt="screen shot 2019-01-03 at 12 13 10 pm" src="https://user-images.githubusercontent.com/5235591/50626636-686b2580-0f55-11e9-98af-da2bd623e805.png">

3. What did you see instead?
Running `explain` on TiDB 2.1.1 returns a full table scan
<img width="732" alt="screen shot 2019-01-03 at 12 16 05 pm" src="https://user-images.githubusercontent.com/5235591/50626663-82a50380-0f55-11e9-8a24-a4ed7005c1bb.png">

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

   TiDB v2.1.1

**Comment by Guru107** [comment]
@eurekaka Yes it is showing Index scan but it is scanning all rows in 2.1.1 as seen in `count` column. But in 2.0.8 if you see the `count` column it is only 40.

**Comment by eurekaka** [comment]
@Guru107 Does the table have changes between these 2 explains? seems like 2.1.1 uses `column_1` index instead of primary index now. Please provide the statistics information I mentioned above, and **complete** result of `explain analyze` of the above query. Since you can provide the SQL query, I guess there should be no sensitive information need to hide in the explain output?

**Comment by winoros** [comment]
@Guru107 The column `count` is the count estimated by TiDB's planner. It's a value the TiDB **think** it should be, not the actual count.
As you can see in the column `operator info`, there're things like `range: [0 1, 0 1], [1 3, 1 3] ...` This indicates the range infomation that is used to seek index.
And you can see when you ran `explain analyze` statement, There's an extra row that contains the information of `loops`, `time`, `rows`. `rows` here is actual rows that fectched by the executor. And as you can see it `50`.

**Comment by eurekaka** [comment]
Yes, `explain analyze` shows 50 rows retrieved actually. BTW, the statistics seems to be empty, can you `analyze` the table first, and check the `count` again to see if it is still 100?

**Comment by eurekaka** [comment]
@Guru107 thanks, please provide the latest statistics information again, then we would check if the estimation count change is reasonable.

**Comment by Guru107** [comment]
@eurekaka Here's the table stats after `analyze`
[table_stats.txt](https://github.com/pingcap/tidb/files/2723249/table_stats.txt)

**Comment by eurekaka** [comment]
@Guru107 Thanks.

**Comment by eurekaka** [comment]
The behavior change is caused by these lines in `deriveIndexPathStats`:
```golang
458     // If the `countAfterAccess` is less than `stats.RowCount`, there must be some inconsistent stats info.
459     // We prefer the `stats.RowCount` because it could use more stats info to calculate the selectivity.
460     if path.countAfterAccess < ds.stats.RowCount {
461         path.countAfterAccess = math.Min(ds.stats.RowCount/selectionFactor, float64(ds.statisticTable.Count))
462     }
```
this part is different in 2.0.8 and 2.1.1. @Guru107 thanks for the report, we will try to improve it.

**Comment by Guru107** [comment]
@eurekaka Does this impact query performance?

**Comment by eurekaka** [comment]
@Guru107 In your case, the query plan chosen is correct, so no performance impaction.

**Comment by eurekaka** [comment]
The change is introduced in https://github.com/pingcap/tidb/pull/7233, @lamxTyler PTAL if we should make some adjustment.

**Comment by lamxTyler** [comment]
The change is reasonable and needs no change. The root cause of the problem is the selectivity cannot process DNF now, refer https://github.com/pingcap/tidb/blob/master/statistics/selectivity.go#L249.

**Comment by eurekaka** [comment]
So if filter is in DNF form, `selectivity` may return estimation not as accurate as `GetRowCountByIndexRanges` because ranger handles DNF now while `selectivity` does not? then shall we mark whether it is DNF filter in `selectivity` and add a check in `deriveIndexPathStats` like:
```golang
460     if path.countAfterAccess < ds.stats.RowCount && notInDNF {
461         path.countAfterAccess = math.Min(ds.stats.RowCount/selectionFactor, float64(ds.statisticTable.Count))
462     }
```
