### ISSUE TITLE
Support SQL Plan Management

### ISSUE THREAD

**Issue by yu34po** [pingcap/tidb#8935]
## Feature Request

The optimizer chooses a plan based on several environmental factors, such as statistics, optimizer parameters, schema definitions and so on. Once the environment changes, we cannot guarantee that the newly optimized plan is always better than the old plan. Therefore we need to provide ways to bind the plan for applications that cannot take the risk of a changed plan.

**Describe the feature you'd like:**
support the SQL plan management. With the help of it, we can force the optimizer to choose a certain plan without modifying the SQL text.

**Describe alternatives you've considered:**
No 

**Teachability, Documentation, Adoption, Migration Strategy:**
@yu34po will work on this issue.

**Comment by yu34po** [comment]
we have complete code develop, now work in unit and integration test,
will  complete featuer in 3 PRs
1.support global create/drop/show bind cmd and store data in system table and global cache
2.for every query sql , try to match global hint cache and add hint to original sql
3.session cache support

**Comment by shenli** [comment]
@yu34po Good job!

**Comment by zz-jason** [comment]
The core function of SQL Plan Management is supported by now, let's close this issue.
