### ISSUE TITLE
Set mysql compatible error codes in visitInfo

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#8946]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Following on from https://github.com/pingcap/tidb/pull/8855, `visitInfo` now allows a custom error to be attached.  This issue can serve to track improving all the `appendVisitInfo` calls to attach a correct error code.

Some other privilege checks, such as https://github.com/pingcap/tidb/pull/8426/files can also be moved back into `visitInfo`.

**Describe the feature you'd like:**

Improve privilege checks in `visitInfo`.  This can be broken down into smaller PRs as well.

* [x] SET GLOBAL https://github.com/pingcap/tidb/pull/9095
* [x] Analyze table https://github.com/pingcap/tidb/pull/9095
* [ ] ADMIN command (need to create custom TiDB error?)
* [x] SHOW CREATE TABLE https://github.com/pingcap/tidb/pull/9112
* [x] CREATE USER, DROP USER, ALTER USER https://github.com/pingcap/tidb/pull/9112
* [ ] GRANT statement
* [ ] Kill statement
* [ ] Insert statement
* [ ] Alter table / create database / create index / create table / create view / drop database / drop index / drop table / truncate table / rename table
* [ ] move: setpassword statement

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

MySQL compatible behavior

**Comment by nullnotnil** [comment]
I am going to close this issue. The code has changed a bit, and separate issues can be filed to fix error messages in specific cases.
