### ISSUE TITLE
`flag provided but not defined: -L/usr/local/opt/libxml2/lib` when I compile TiDB on mac

### ISSUE THREAD

**Issue by acmerfight** [pingcap/tidb#8955]
I met `flag provided but not defined: -L/usr/local/opt/libxml2/lib`,when I compile TiDB on mac
I have installed libxml2 and add config to .zshrc
`go version go1.11.4 darwin/amd64`
```
export PATH="/usr/local/opt/libxml2/bin:$PATH"
export LDFLAGS="-L/usr/local/opt/libxml2/lib"
export CPPFLAGS="-I/usr/local/opt/libxml2/include"
export PKG_CONFIG_PATH="/usr/local/opt/libxml2/lib/pkgconfig"
```

![image](https://user-images.githubusercontent.com/1516479/50725099-6b237180-1133-11e9-9a0c-b9cbca0086f3.png)

![image](https://user-images.githubusercontent.com/1516479/50725374-be97be80-1137-11e9-9d22-e81cc078d90c.png)

**Comment by darren** [comment]
tidb does not use libxml2 at all. Don't add these environment variables to .zshrc, only use them when you build tools/libraries that actually depend on libxml2.

if you don't want to change that, then reset LDFLAGS variable when build tidb-server

```bash
LDFLAGS= make server
```

**Comment by wfnuser** [comment]
Meet same question for `llvm`. 
Reset LDFLAGS variable when build tidb-server makes it work.
`LDFLAGS= make server`

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
