### ISSUE TITLE
loader failed ,tidb die?

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#8958]
Release Version: v2.1.0-5-g4dad722
Git Commit Hash: 4dad722bbf573050477328ce8ff5bcb7f1a1c7f1
Git Branch: release-2.1
UTC Build Time: 2018-12-07 02:29:19
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

nohup ./loader -h ip -u root -P 3306 -t 64 -d /data/db_bak > nohupcluster 2>&1 &

![image](https://user-images.githubusercontent.com/35753836/50736096-9ff6fd80-11f3-11e9-8dd6-5a2cfb451b82.png)

**Comment by jackysp** [comment]
Thanks for your report, @shenlijungg !
PTAL @csuzhangxc @WangXiangUSTC

**Comment by csuzhangxc** [comment]
@shenlijungg 
have you tested with any MySQL client from the host of loader running to connect to `10.4.17.148:4000` with the user/password set in loader's config.

**Comment by shenlijungg** [comment]
@csuzhangxc   tidb 有6台，其中几台报check point error .但有几台成功的。  是因为我没有设置密码的问题？但为什么有几台是正常的。check point 应该和 tidb_loader下 table   checkpoint 有关，如何检查或取消报错。

**Comment by shenlijungg** [comment]
@csuzhangxc   
/loader -h 10.4.17.148 -u root -P 4000 -t 5 -d /data/xx      目前只能开 5个，默认16 tidb 4000端口 会死掉!
logs:
 2019/01/04 17:00:33.282 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:01:33.283 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:02:33.284 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:03:03.085 domain.go:762: [info] [domain] reload privilege success.
2019/01/04 17:03:33.285 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:04:33.285 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:05:33.286 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:06:33.286 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:07:33.287 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:08:33.288 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:09:33.288 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:10:33.289 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:11:33.289 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:12:33.290 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:13:03.103 domain.go:762: [info] [domain] reload privilege success.
2019/01/04 17:13:33.290 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:14:33.291 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:15:33.291 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:16:33.292 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/04 17:17:33.292 server.go:271: [error] listener stopped, waiting for manual kill.

![image](https://user-images.githubusercontent.com/35753836/50871790-b8d00080-13f7-11e9-9fdf-1c74a1c4c9f9.png)

**Comment by csuzhangxc** [comment]
@crazycs520 PTAL

**Comment by crazycs520** [comment]
@shenlijungg ， Could you upload the tidb.log file?

**Comment by shenlijungg** [comment]
@crazycs520 
2019/01/06 14:04:50.789 printer.go:52: [info] Config: {"host":"0.0.0.0","advertise-address":"10.4.17.150","port":4000,"store":"tikv","path":"10.4.17.135:2379,10.4.17.136:2379,10.4.17.129:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"txn-local-latches":{"enabled":false,"capacity":10240000},"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/home/tidb/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0.05,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.8,"force-priority":"NO_PRIORITY"},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enable":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"grpc-keepalive-time":10,"grpc-keepalive-timeout":3,"commit-timeout":"41s"},"binlog":{"enable":true,"write-timeout":"15s","ignore-error":false},"compatible-kill-query":false}
2019/01/06 14:05:27.220 printer.go:52: [info] Config: {"host":"0.0.0.0","advertise-address":"10.4.17.150","port":4000,"store":"tikv","path":"10.4.17.135:2379,10.4.17.136:2379,10.4.17.129:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"txn-local-latches":{"enabled":false,"capacity":10240000},"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/home/tidb/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0.05,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.8,"force-priority":"NO_PRIORITY"},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enable":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"grpc-keepalive-time":10,"grpc-keepalive-timeout":3,"commit-timeout":"41s"},"binlog":{"enable":true,"write-timeout":"15s","ignore-error":false},"compatible-kill-query":false}
2019/01/06 14:12:17.072 server.go:376: [info] [server] kill all connections.
2019/01/06 14:16:17.054 printer.go:52: [info] Config: {"host":"0.0.0.0","advertise-address":"10.4.17.150","port":4000,"store":"tikv","path":"10.4.17.135:2379,10.4.17.136:2379,10.4.17.129:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"txn-local-latches":{"enabled":false,"capacity":10240000},"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/home/tidb/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0.05,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.8,"force-priority":"NO_PRIORITY"},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enable":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"grpc-keepalive-time":10,"grpc-keepalive-timeout":3,"commit-timeout":"41s"},"binlog":{"enable":true,"write-timeout":"15s","ignore-error":false},"compatible-kill-query":false}
2019/01/06 14:34:37.464 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:35:37.465 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:36:37.465 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:37:37.466 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:38:37.467 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:39:37.467 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:40:37.468 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:41:37.469 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:42:37.469 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:43:37.470 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:44:37.471 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:45:37.471 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:46:37.472 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:47:37.472 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:48:37.473 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:49:37.473 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:50:37.474 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:51:37.475 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:52:37.475 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:53:37.476 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:54:37.477 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:55:37.477 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:56:37.478 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:57:37.478 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:58:37.479 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 14:59:37.479 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:00:37.480 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:01:37.481 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:02:37.481 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:03:37.482 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:04:37.483 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:05:37.483 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:06:37.484 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:07:37.485 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:08:37.486 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:09:37.486 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:10:37.487 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:11:37.487 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:12:37.488 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:13:37.488 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:14:37.489 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 15:16:00.547 printer.go:52: [info] Config: {"host":"0.0.0.0","advertise-address":"10.4.17.150","port":4000,"store":"tikv","path":"10.4.17.135:2379,10.4.17.136:2379,10.4.17.129:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"txn-local-latches":{"enabled":false,"capacity":10240000},"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/home/tidb/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0.05,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.8,"force-priority":"NO_PRIORITY"},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enable":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"grpc-keepalive-time":10,"grpc-keepalive-timeout":3,"commit-timeout":"41s"},"binlog":{"enable":true,"write-timeout":"15s","ignore-error":false},"compatible-kill-query":false}
2019/01/06 17:06:08.574 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:07:08.575 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:08:08.575 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:09:08.575 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:10:08.576 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:11:08.577 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:12:08.577 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:13:08.578 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:14:08.578 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:15:06.147 printer.go:52: [info] Config: {"host":"0.0.0.0","advertise-address":"10.4.17.150","port":4000,"store":"tikv","path":"10.4.17.135:2379,10.4.17.136:2379,10.4.17.129:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"txn-local-latches":{"enabled":false,"capacity":10240000},"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/home/tidb/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0.05,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.8,"force-priority":"NO_PRIORITY"},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enable":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"grpc-keepalive-time":10,"grpc-keepalive-timeout":3,"commit-timeout":"41s"},"binlog":{"enable":true,"write-timeout":"15s","ignore-error":false},"compatible-kill-query":false}
2019/01/06 17:16:20.833 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:17:20.833 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:18:20.835 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:19:20.835 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:20:20.836 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:21:20.837 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 17:57:47.556 printer.go:52: [info] Config: {"host":"0.0.0.0","advertise-address":"10.4.17.150","port":4000,"store":"tikv","path":"10.4.17.135:2379,10.4.17.136:2379,10.4.17.129:2379","socket":"","lease":"45s","run-ddl":true,"split-table":true,"token-limit":1000,"oom-action":"log","mem-quota-query":34359738368,"enable-streaming":false,"txn-local-latches":{"enabled":false,"capacity":10240000},"lower-case-table-names":2,"log":{"level":"info","format":"text","disable-timestamp":false,"file":{"filename":"/home/tidb/deploy/log/tidb.log","log-rotate":true,"max-size":300,"max-days":0,"max-backups":0},"slow-query-file":"","slow-threshold":300,"expensive-threshold":10000,"query-log-max-len":2048},"security":{"skip-grant-table":false,"ssl-ca":"","ssl-cert":"","ssl-key":"","cluster-ssl-ca":"","cluster-ssl-cert":"","cluster-ssl-key":""},"status":{"report-status":true,"status-port":10080,"metrics-addr":"","metrics-interval":15},"performance":{"max-procs":0,"tcp-keep-alive":true,"cross-join":true,"stats-lease":"3s","run-auto-analyze":true,"stmt-count-limit":5000,"feedback-probability":0.05,"query-feedback-limit":1024,"pseudo-estimate-ratio":0.8,"force-priority":"NO_PRIORITY"},"xprotocol":{"xserver":false,"xhost":"","xport":0,"xsocket":""},"prepared-plan-cache":{"enabled":false,"capacity":100},"opentracing":{"enable":false,"sampler":{"type":"const","param":1,"sampling-server-url":"","max-operations":0,"sampling-refresh-interval":0},"reporter":{"queue-size":0,"buffer-flush-interval":0,"log-spans":false,"local-agent-host-port":""},"rpc-metrics":false},"proxy-protocol":{"networks":"","header-timeout":5},"tikv-client":{"grpc-connection-count":16,"grpc-keepalive-time":10,"grpc-keepalive-timeout":3,"commit-timeout":"41s"},"binlog":{"enable":true,"write-timeout":"15s","ignore-error":false},"compatible-kill-query":false}
2019/01/06 18:02:35.011 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:03:35.012 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:04:35.013 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:05:35.013 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:06:35.014 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:07:35.015 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:08:35.016 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:09:35.017 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:10:35.017 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:11:35.018 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:12:35.018 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:13:35.019 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:14:35.020 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:15:35.020 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:16:35.021 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:17:35.022 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:18:35.023 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:19:35.024 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:20:35.024 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:21:35.025 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:22:35.026 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:23:35.027 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:24:35.027 server.go:271: [error] listener stopped, waiting for manual kill.
2019/01/06 18:25:35.028 server.go:271: [error] listener stopped, waiting for manual kill.

**Comment by weekface** [comment]
How to solve this problem, tidb-operator users have also encountered this problem: https://github.com/pingcap/tidb-operator/issues/605

@crazycs520 @csuzhangxc
