### ISSUE TITLE
The error code of rename ddl is not compatible with mysql 

### ISSUE THREAD

**Issue by nange** [pingcap/tidb#8959]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
create database test1;
create database test2;
alter table test1.t rename to test2.t;
```

2. What did you expect to see?
``` ERROR 1146 (42S02): Table 'test1.t' doesn't exist ```

3. What did you see instead?
``` ERROR 1017 (HY000): Can't find file: './test1/t.frm' ```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
``` 
Release Version: v2.1.2-1-g8ba8096
Git Commit Hash: 8ba809622668a1287e9f7152bfd34ad6be220304
Git Branch: release-2.1
UTC Build Time: 2018-12-21 03:45:55
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

-----------------
I summarized all the incompatible scenes with below:

![default](https://user-images.githubusercontent.com/2505751/50737128-b9527680-1200-11e9-9aa5-c27c2b2832d4.png)

**Comment by shenli** [comment]
@nange Nice catch!
