### ISSUE TITLE
🎉自动化接口和文档APIJSON已支持TiDB，提供从API到TiDB的完整Demo

### ISSUE THREAD

**Issue by TommyLemon** [pingcap/tidb#8961]
APIJSON 接入 TiDB 的详细图文上手教程
https://www.zhihu.com/question/58767602/answer/557035883

**Comment by shenli** [comment]
@TommyLemon Amazing work! 👍 
Could you translate the title and description into English? So others could know about your work.

**Comment by TommyLemon** [comment]
@shenli Well, thank you for your support and advice.

**Comment by TommyLemon** [comment]
I wrote another issue with English for foreigners, and this issue will be kept for Chinese.
https://github.com/pingcap/tidb/issues/8963

**Comment by nullnotnil** [comment]
I have moved this to the docs project as https://github.com/pingcap/docs/issues/3530

I am going to close this issue now. Thanks for the great work!

**Comment by TommyLemon** [comment]
@nullnotnil ok, thx
