### ISSUE TITLE
unsupported modify column length 255 is less than origin 512

### ISSUE THREAD

**Issue by lwlw217** [pingcap/tidb#8965]
## Question
When I modify a column length:
` ALTER TABLE `jianzhi`.`jz_third_api_log` CHANGE COLUMN `token` `token` varchar(255) DEFAULT '' NOT NULL COMMENT 'token值';`
tips:
unsupported modify column length 255 is less than origin 512.

The table structure like this:
`CREATE TABLE `jz_third_api_log` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `user_mobile` varchar(64) NOT NULL DEFAULT '' COMMENT '用户手机号',
  `user_name` varchar(64) NOT NULL DEFAULT '' COMMENT '用户姓名',
  `user_type` tinyint(4) NOT NULL DEFAULT '0' COMMENT '用户类型:1-新用户,2-老用户',
  `ca_source` varchar(64) NOT NULL DEFAULT '' COMMENT '来源',
  `token` varchar(512) NOT NULL DEFAULT '' COMMENT 'token值',
  `ip` varchar(40) NOT NULL DEFAULT '' COMMENT 'ip地址',
  `expire_at` int(11) NOT NULL DEFAULT '0' COMMENT '过期时间',
  `create_at` int(11) NOT NULL DEFAULT '0' COMMENT '创建时间',
  `modify_at` int(11) NOT NULL DEFAULT '0' COMMENT '修改时间',
  PRIMARY KEY (`id`),
  KEY `idx_mobile_source` (`user_mobile`,`ca_source`),
  KEY `idx_token` (`token`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=30002 COMMENT='第三方请求接口记录'`

**Comment by winoros** [comment]
Yes, TiDB currently cannot alter one column to reduce its length.
@zimulala @winkyao @crazycs520 PTAL

**Comment by wl21787** [comment]
Whether consider add this feature in the furture?

**Comment by zimulala** [comment]
@wl21787 
We plan to support this feature this year.

**Comment by wl21787** [comment]
Thanks for your attention and reply !

**Comment by nullnotnil** [comment]
Here is a minimal test case against master:
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
 id int not null primary key auto_increment,
 token varchar(512) NOT NULL DEFAULT '',
 index (token)
);
INSERT INTO t1 VALUES (NULL, 'aa');
ALTER TABLE t1 CHANGE COLUMN token token varchar(255) DEFAULT '' NOT NULL;

..

mysql> ALTER TABLE t1 CHANGE COLUMN token token varchar(255) DEFAULT '' NOT NULL;
ERROR 8200 (HY000): Unsupported modify column: length 255 is less than origin 512
mysql> SELECT tidb_version()
    -> \G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-859-gccfc9b2ad
Edition: Community
Git Commit Hash: ccfc9b2ad0dcf8e447210de5f559d7fc208db968
Git Branch: master
UTC Build Time: 2020-07-29 09:37:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue and merge it with https://github.com/pingcap/tidb/issues/17530
