### ISSUE TITLE
it seems broken when compile the latest code

### ISSUE THREAD

**Issue by swingbach** [pingcap/tidb#898]
when i download the latest code from master branch, and execute make command:

it reports error like this:

store/hbase/kv.go:207: too many arguments in call to oracles.NewRemoteOracle
godep: go exit status 2

could you guys shed some light on this?

**Comment by shenli** [comment]
@swingbach Have you run "make update"?

**Comment by swingbach** [comment]
@shenli it solves after executing "make update"

Thanks
