### ISSUE TITLE
Cannot modify column type from varchar(16) to varchar(64)

### ISSUE THREAD

**Issue by shalcanleo** [pingcap/tidb#8987]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
I want to change column col1 data type from varchar(16) to varch(64) by: 
ALTER TABLE `db`.`table` CHANGE COLUMN  `col1` `col1` `mobile` varchar(64) 

2. What did you expect to see?
change column success.

3. What did you see instead?
2019/01/06 00:00:17 db.go:130: [warning] [exec][sql]USE `toproperty`; ALTER TABLE `db`.`table` CHANGE COLUMN `col1` `col1` varchar(64) COMMENT 'coment col';[args][][error]Error 1105: unsupported modify column charset utf8mb4 not match origin utf8

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb_version()

Release Version: v2.1.2-1-g8ba8096\nGit Commit Hash: 8ba809622668a1287e9f7152bfd34ad6be220304\nGit Branch: release-2.1\nUTC Build Time: 2018-12-21 03:45:55\nGoVersion: go version go1.11.2 linux/amd64\nRace Enabled: false\nTiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e\nCheck Table Before Drop: false

**Comment by morgo** [comment]
The error message looks like you are changing the character set as well as the `VARCHAR` size.  What happens if you try one of the following:

```
SET NAMES utf8;
ALTER TABLE db.table CHANGE COLUMN col1 col1 mobile varchar(64)
```
-or-
```
SET NAMES utf8mb4;
ALTER TABLE db.table CHANGE COLUMN col1 col1 mobile varchar(64)
```

**Comment by ciscoxll** [comment]
There are two problems here.
1. Execute sql and try `ALTER TABLE db.table CHANGE COLUMN col1 col1 mobile varchar(16) charset utf8`.
2. Alter table `varchar(16) to varch(64)` there are plans to do this year.

**Comment by nullnotnil** [comment]
Confirming that both of the reported issues have been fixed in master:
```sql
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (
 id INT NOT NULL PRIMARY KEY auto_increment,
 b VARCHAR(16)
) CHARACTER SET utf8;

INSERT INTO t1 VALUES (1, 'a');
ALTER TABLE t1 CHANGE COLUMN b b VARCHAR(64);
SHOW CREATE TABLE t1\G
ALTER TABLE t1 CHANGE COLUMN b b VARCHAR(100) CHARACTER SET utf8mb4;
SHOW CREATE TABLE t1\G
SELECT tidb_version()\G

..

mysql> ALTER TABLE t1 CHANGE COLUMN b b VARCHAR(64);
Query OK, 0 rows affected (0.08 sec)

mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=30002
1 row in set (0.00 sec)

mysql> ALTER TABLE t1 CHANGE COLUMN b b VARCHAR(100) CHARACTER SET utf8mb4;
Query OK, 0 rows affected (0.08 sec)

mysql> SHOW CREATE TABLE t1\G
*************************** 1. row ***************************
       Table: t1
Create Table: CREATE TABLE `t1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `b` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=30002
1 row in set (0.00 sec)

mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-821-gfe07417e6
Edition: Community
Git Commit Hash: fe07417e6b2f28eb334117d44640d0760d7e9866
Git Branch: master
UTC Build Time: 2020-07-22 12:51:37
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```

I am going to close this issue now, but please feel free to re-open if you have additional questions. Thanks!
