### ISSUE TITLE
Any differences between query from TiDB and TiSpark

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#8993]
我想问下 一下直接用jdbc连接tidb做sql query，和用tispark做parksql查询有什么区别？可以用tidb的jdbcl做复杂的时间长的sql查询吗？这样就不需要再多学一个spark了？

**Comment by XuHuaiyu** [comment]
Hi, @ericisme 
Thanks for your attention.
1. TiDB and TiSpark are two compute engines but share the same storage TiKV. More details about TiSpark can be referred [here](https://pingcap.com/docs-cn/tispark/tispark-user-guide/)
2. TiDB can handle most of the complex queries, but whether to use TiDB or TiSpark is affected by different business scenario. Cases from our customer can be found [here](https://pingcap.com/cases-cn/).

**Comment by ericisme** [comment]
> Hi, @ericisme
> Thanks for your attention.
> 
> 1. TiDB and TiSpark are two compute engines but share the same storage TiKV. More details about TiSpark can be referred [here](https://pingcap.com/docs-cn/tispark/tispark-user-guide/)
> 2. TiDB can handle most of the complex queries, but whether to use TiDB or TiSpark is affected by different business scenario. Cases from our customer can be found [here](https://pingcap.com/cases-cn/).

你的意思是spark可以处理非sql统计逻辑吗？ 那这个应该算是功能上的差异，我想问下，除了这个功能上的差异，如果是同事处理sql，性能上有差异吗，比如我看问题TiDB节点是无状态的，意味这一条sql只能由一个TiDB节点处理计算（如join逻辑），还是会多个TiDB协作处理？ spark应该是多节点协作处理吧，这是spark在性能上的优势吗？ 另外如果是这样，可以开发一个类似于spark这样的多节点处理的但对用户透明的TiDB节点吗，这样我们很多统计就可以直接用jdbc实现了，可以简单很多也少依赖和学习多一个spark, 谢谢？

**Comment by winoros** [comment]
>意味这一条sql只能由一个TiDB节点处理计算（如join逻辑）

Yes, One sql's execution will happen on only one TiDB for now. Spark's execution framework is stronger than current TiDB.

>可以开发一个类似于spark这样的多节点处理的但对用户透明的TiDB节点吗

We definitely will do it. But it'll take much time to make this feature production-ready. So currently you may still need to rely on TiSpark to speed up some of your complex queries.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
