### ISSUE TITLE
how to decode start key of record regions

### ISSUE THREAD

**Issue by dawnbreaks** [pingcap/tidb#8995]
I can fetch all region info by the TIDB HTTP API, but how to decode the start key and end key of record regions to the origin primary key of the table?  Anyone give me some advices? It would be nice that A new TIDB HTTP API can do this.

$curl http://127.0.0.1:10080/regions/4001
{
    "end_key": "dIAAAAAAAAEk",
    "frames": [
        {
            "db_name": "test",
            "is_record": true,
            "table_id": 286,
            "table_name": "t1"
        }
    ],
    "region_id": 4001,
    "start_key": "dIAAAAAAAAEe"
}

**Comment by morgo** [comment]
TiKV recently proposed an RFC to [unify how to present the key](https://github.com/tikv/rfcs/blob/master/text/2018-11-12-unified-key-format.md).  Feedback welcome!

As an aside, I also created a https://github.com/pingcap/tidb/issues/7714 to be able to show the region info inside of TiDB directly.

I hope this helps!

**Comment by morgo** [comment]
@dawnbreaks I wanted to follow up and check if this answered your original question?  Let me know if I can clarify further.

**Comment by dawnbreaks** [comment]
It would be great that if we could query the region info for a table by sql. I had found that i could use the methods in the tablecodec.go to decode those keys, and it would be appreciated that if you guys could decode those key to human readable table columns.

**Comment by morgo** [comment]
I agree!  I have a feature request for information_schema support here: https://github.com/pingcap/tidb/issues/7714
