### ISSUE TITLE
Configure tikv.toml in tidb-ansible or tikv server/conf/tikv.toml?

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#8996]
1  :Configure tikv.toml in tidb-ansible?
需要在中控上新建tikv.toml，操作上直接重启，还是需要 执行?
ansible-playbook stop.yml -l   kvip
ansible-playbook bootstrap.yml -l   kvip
ansible-playbook deploy.yml -l   kvip
ansible-playbook start.yml -l   kvip

2  :Configure tikv.toml in tikv server/conf/tikv.toml?
vi  tikv.toml     
ansible-playbook stop.yml -l   kvip
ansible-playbook start.yml -l   kvip

**Comment by shenlijungg** [comment]
drainer_mysql_drainer.toml      ansible-playbook rolling_update.yml --l  drainerhost?   @liubo0127

**Comment by liubo0127** [comment]
The drainer is a single point service, you need to stop the service first, then update the configuration, and finally start the service.If you want to modify the configuration of drainer1(alias in inventory.ini) the steps are as follows:
1. `ansible-playbook stop_drainer.yml -l drainer1`
2. `ansible-playbook deploy_drainer.yml -l drainer1`
3. `ansible-playbook start_drainer.yml -l drainer1`

**Comment by shenlijungg** [comment]
**thanks** @liubo127
