### ISSUE TITLE
deploy tidb cluster using tidb-docker-compose failed

### ISSUE THREAD

**Issue by azza77** [pingcap/tidb#9000]
机器信息：1 核 1 GB 50G云硬盘
将docker-compose.yml pd2/tikv2 + tispark 启动信息去掉了 
docker-compose up -d 启动后 docker ps查看  tikv-server 的status 一直是restart状态
mysql 登录提示：
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

相关信息如下：

docker images:
REPOSITORY                                   TAG                 IMAGE ID            CREATED             SIZE
docker.io/pingcap/pd                         latest              57d8d6047816        2 days ago          73.1 MB
docker.io/pingcap/tikv                       latest              9d3b82bae098        2 days ago          311 MB
docker.io/pingcap/tidb                       latest              4df95900d9bd        2 days ago          59.1 MB
docker.io/pingcap/tispark                    latest              388fbc963dfb        8 weeks ago         827 MB
docker.io/grafana/grafana                    5.3.0               7a7874a2caba        3 months ago        223 MB
docker.io/pingcap/tidb-dashboard-installer   v2.0.0              525237773def        4 months ago        62 MB
docker.io/pingcap/tidb-vision                latest              e9b25d9f7bdb        8 months ago        47.6 MB
docker.io/prom/prometheus                    v2.2.1              cc866859f8df        10 months ago       113 MB
docker.io/prom/pushgateway                   v0.3.1              434efa6ed9db        2 years ago         13.3 MB

docker ps:
ee3a889477c4        pingcap/tidb:latest          "/tidb-server --st..."   6 minutes ago       Up 2 seconds                        0.0.0.0:4000->4000/tcp, 0.0.0.0:10080->10080/tcp    tidb-docker-compose_tidb_1
9a69242659df        pingcap/tikv:latest          "/tikv-server --ad..."   6 minutes ago       Restarting (1) About a minute ago                                                       tidb-docker-compose_tikv0_1
52e6b5fccf91        pingcap/tikv:latest          "/tikv-server --ad..."   6 minutes ago       Restarting (1) About a minute ago                                                       tidb-docker-compose_tikv1_1
53fe956846e1        pingcap/pd:latest            "/pd-server --name..."   6 minutes ago       Up 6 minutes                        2380/tcp, 0.0.0.0:32778->2379/tcp                   tidb-docker-compose_pd1_1
7630c4d06587        pingcap/pd:latest            "/pd-server --name..."   6 minutes ago       Up 6 minutes                        2380/tcp, 0.0.0.0:32777->2379/tcp                   tidb-docker-compose_pd0_1
6eccb7c4fca2        prom/prometheus:v2.2.1       "/bin/prometheus -..."   11 hours ago        Up 6 minutes                        0.0.0.0:9090->9090/tcp                              tidb-docker-compose_prometheus_1
f2584342bba4        grafana/grafana:5.3.0        "/run.sh"                11 hours ago        Up 6 minutes                        0.0.0.0:3000->3000/tcp                              tidb-docker-compose_grafana_1
e4c0b9206dae        pingcap/tidb-vision:latest   "/bin/sh -c 'sed -..."   11 hours ago        Up 6 minutes                        80/tcp, 443/tcp, 2015/tcp, 0.0.0.0:8010->8010/tcp   tidb-docker-compose_tidb-vision_1
bdaff37c5f91        prom/pushgateway:v0.3.1      "/bin/pushgateway ..."   11 hours ago        Up 6 minutes                        9091/tcp                                            tidb-docker-compose_pushgateway_1

docker info:
Containers: 14
 Running: 7
 Paused: 0
 Stopped: 7
Images: 9
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc docker-runc
Default Runtime: docker-runc
Init Binary: /usr/libexec/docker/docker-init-current
containerd version:  (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: N/A (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: fec3683b971d9c3ef73f284f176672c44b448662 (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
Kernel Version: 3.10.0-514.26.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 1
Total Memory: 992.7 MiB
Name: VM_16_11_centos
ID: ELKH:PBBG:JGII:DCWQ:3US3:T6VA:Z5TM:JZPR:WLIO:PMGX:CMMA:XTFW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Registries: docker.io (secure)

docker network ls:
NETWORK ID          NAME                          DRIVER              SCOPE
010e25300fcf        bridge                        bridge              local
b21d1f8b94c0        host                          host                local
c0777bc7bde5        none                          null                local
9e06cd1420e9        tidb-docker-compose_default   bridge              local

route:
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U     0      0        0 br-9e06cd1420e9

**Comment by siddontang** [comment]
Can you check the TiKV logs in your logs directory?

**Comment by tennix** [comment]
Yes, you can check TiKV logs in `logs` directory.

**Comment by azza77** [comment]
tikv0 和tikv1 最近的log:
2019/01/09 16:17:09.053 ERRO tikv-server.rs:437: invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")
2019/01/09 16:36:32.553 ERRO tikv-server.rs:437: invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")
2019/01/10 02:07:43.391 ERRO tikv-server.rs:437: invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")
2019/01/10 02:08:35.428 ERRO tikv-server.rs:437: invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")
2019/01/10 02:13:44.012 ERRO tikv-server.rs:437: invalid configuration: StringError("default rocksdb exist, buf raftdb not exist")

**Comment by siddontang** [comment]
so, seem you have too old data in the docker-compose, you can remove data directory and start again if you just want to test.

**Comment by azza77** [comment]
也试过了  data&logs目录清空 重新docker-compose up -d  
mysql 登录提示：
mysql -h127.0.0.1 -P4000 -uroot
ERROR 2013 (HY000): Lost connection to MySQL server at 'reading initial communication packet', system error: 0

tidb log:
2019/01/10 05:34:30.519 client.go:170: [error] [pd] failed to get cluster id: rpc error: code = Unknown desc = server not started
2019/01/10 05:34:30.526 client.go:170: [error] [pd] failed to get cluster id: rpc error: code = Unknown desc = server not started
2019/01/10 05:34:31.611 client.go:170: [error] [pd] failed to get cluster id: rpc error: code = Unknown desc = server not started
2019/01/10 05:34:31.613 client.go:170: [error] [pd] failed to get cluster id: rpc error: code = Unknown desc = server not started
2019/01/10 05:34:42.159 client.go:333: [error] tso request is canceled due to timeout
2019/01/10 05:42:25.762 client.go:415: [error] [pd] getTS error: rpc error: code = Canceled desc = context canceled
2019/01/10 05:44:46.573 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379 http://pd1:2379]
2019/01/10 05:44:32.584 pd.go:127: [error] updateTS error: rpc error: code = Canceled desc = context canceled
2019/01/10 05:44:55.398 kv.go:245: [error] fail to load safepoint from pd: context deadline exceeded
2019/01/10 05:48:47.545 client.go:333: [error] tso request is canceled due to timeout
2019/01/10 05:51:00.783 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379 http://pd1:2379]
2019/01/10 05:51:47.203 main.go:233: [error] could not push metrics to Prometheus Pushgateway: Post http://pushgateway:9091/metrics/job/tidb/instance/ee3a889477c4_4000: dial tcp: i/o timeout
2019/01/10 05:51:55.129 client.go:415: [error] [pd] getTS error: rpc error: code = Canceled desc = context canceled

pd0 log:
2019/01/10 07:12:00.245 etcd_kv.go:116: [error] load from etcd error: context deadline exceeded
2019/01/10 07:13:06.028 leader.go:136: [error] failed to load leader priority: context deadline exceeded
2019/01/10 07:13:16.570 leader.go:87: [error] get leader err context deadline exceeded
2019/01/10 07:14:03.688 metricutil.go:69: [error] could not push metrics to Prometheus Pushgateway: Put http://pushgateway:9091/metrics/job/pd0/instance/7630c4d06587: dial tcp: lookup pushgateway on 127.0.0.11:5
3: read udp 127.0.0.1:44473->127.0.0.11:53: i/o timeout
2019/01/10 07:14:11.933 etcd_kv.go:116: [error] load from etcd error: context deadline exceeded
2019/01/10 07:14:13.686 leader.go:87: [error] get leader err context deadline exceeded
2019/01/10 07:14:19.729 etcd_kv.go:116: [error] load from etcd error: context deadline exceeded
2019/01/10 07:14:20.867 leader.go:136: [error] failed to load leader priority: context deadline exceeded
2019/01/10 07:14:34.389 etcd_kv.go:116: [error] load from etcd error: context deadline exceeded
2019/01/10 07:14:39.770 leader.go:87: [error] get leader err context deadline exceeded
2019/01/10 07:15:46.685 log.go:82: [error] rafthttp: [failed to read 47149ed249f68e2b on stream MsgApp v2 (read tcp 172.18.0.3:44736->172.18.0.4:2380: i/o timeout)]

tikv1 log:
2019/01/10 07:17:14.507 ERRO util.rs:453: failed to connect to http://pd0:2379, Grpc(RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") }))
2019/01/10 07:17:15.345 ERRO util.rs:297: request failed: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("rpc error: code = Unavailable desc = not leader") })), retry
2019/01/10 07:17:15.672 ERRO util.rs:453: failed to connect to http://pd0:2379, Grpc(RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") }))
2019/01/10 07:17:17.346 ERRO util.rs:453: failed to connect to http://pd1:2379, Grpc(RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") }))
2019/01/10 07:17:17.660 ERRO gc_worker.rs:790: failed to get safe point from pd: Other(StringError("[src/storage/gc_worker.rs:75]: failed to get safe point from PD: Grpc(RpcFailure(RpcStatus { status: DeadlineEx
ceeded, details: Some(\"Deadline Exceeded\") }))"))
2019/01/10 07:17:20.203 ERRO util.rs:453: failed to connect to http://pd0:2379, Grpc(RpcFailure(RpcStatus { status: DeadlineExceeded, details: Some("Deadline Exceeded") }))
2019/01/10 07:17:20.915 ERRO util.rs:297: request failed: Grpc(RpcFailure(RpcStatus { status: Unknown, details: Some("rpc error: code = Unavailable desc = not leader") })), retry

**Comment by ericisme** [comment]
我这边windows docker也不行，后来发现是不能挂着data目录到windows上，logs目录是可以的，data目录不挂载可以启动成功，不然会报EOF的错

**Comment by siddontang** [comment]
> 将docker-compose.yml pd2/tikv2 + tispark 启动信息去掉了

Can you show me the `docker-compose.yml`

**Comment by tennix** [comment]
@azza77 Seems containers in your docker-compose can't connect with each other. Can you try to exec into a running container, say `pd0`:
```shell
docker-compose exec pd0 sh
```
And then access pushgateway service by `wget -qO- http://pushgateway:9091/metrics` to see if you can connect from one container to another.

**Comment by azza77** [comment]
@siddontang  放在这了  https://github.com/azza77/docker-compose/blob/master/docker-compose.yml

**Comment by azza77** [comment]
@tennix  docker-compose exec pd0 sh  
RROR: An HTTP request took too long to complete. 
云服务器 买的便宜  配置太差，同一个docker-compose.yml配置不同机器错误日志不太一样

**Comment by azza77** [comment]
@tennix  
https://github.com/azza77/docker-compose/blob/master/pushgateway.txt

**Comment by tennix** [comment]
From your pushgateway output, the connection is OK. But the error `An HTTP request took too long to complete.` may be the cause of the failure. 1 CPU and 1GB memory may not bring up the whole TiDB cluster. Could you comment out all except PD sections to see if PD can run correctly? If this works, you can just deploy one PD/TiKV/TiDB by [customizing docker-compose with Helm](https://github.com/pingcap/tidb-docker-compose/#customize-tidb-cluster)

Besides why you deploy two PD and two TiKV? Two nodes of PD or TiKV doesn't have fault tolerance by design.

**Comment by azza77** [comment]
只是为了测试 验证些功能，一个pd/tikv/tidb节点 也是失败，
2019/01/11 07:11:36.595 client.go:170: [error] [pd] failed to get cluster id: rpc error: code = Unknown desc = server not started
2019/01/11 07:11:55.072 client.go:333: [error] tso request is canceled due to timeout
2019/01/11 07:11:57.370 kv.go:245: [error] fail to load safepoint from pd: context deadline exceeded
2019/01/11 07:11:57.957 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:00.054 client.go:415: [error] [pd] getTS error: rpc error: code = Canceled desc = context canceled
2019/01/11 07:12:00.516 pd.go:127: [error] updateTS error: rpc error: code = Canceled desc = context canceled
2019/01/11 07:12:02.114 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:07.421 client.go:333: [error] tso request is canceled due to timeout
2019/01/11 07:12:16.950 kv.go:245: [error] fail to load safepoint from pd: context deadline exceeded
2019/01/11 07:12:20.392 client.go:415: [error] [pd] getTS error: rpc error: code = Canceled desc = context canceled
2019/01/11 07:12:20.392 pd.go:127: [error] updateTS error: rpc error: code = Canceled desc = context canceled
2019/01/11 07:12:22.280 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:23.281 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:26.352 client.go:333: [error] tso request is canceled due to timeout
2019/01/11 07:12:43.236 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:43.458 kv.go:245: [error] fail to load safepoint from pd: context deadline exceeded
2019/01/11 07:12:43.458 client.go:415: [error] [pd] getTS error: rpc error: code = Canceled desc = context canceled
2019/01/11 07:12:43.458 pd.go:127: [error] updateTS error: rpc error: code = Canceled desc = context canceled
2019/01/11 07:12:43.692 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:43.692 client.go:415: [error] [pd] getTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
2019/01/11 07:12:43.692 pd.go:127: [error] updateTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
2019/01/11 07:12:43.694 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:43.741 client.go:415: [error] [pd] getTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
2019/01/11 07:12:43.741 pd.go:127: [error] updateTS error: rpc error: code = Unknown desc = rpc error: code = Unavailable desc = not leader
2019/01/11 07:12:43.742 client.go:311: [error] [pd] failed updateLeader: failed to get leader from [http://pd0:2379]
2019/01/11 07:12:54.069 session.go:1404: [fatal] check bootstrapped err [tikv:9001]PD server timeout[try again later]

**Comment by tennix** [comment]
@azza77 What about PD's log?

**Comment by azza77** [comment]
2019/01/11 07:50:19.154 leader.go:87: [error] get leader err context deadline exceeded
2019/01/11 07:50:36.181 leader.go:116: [error] campaign leader err save timestamp failed, maybe we lost leader
github.com/pingcap/pd/server.(*Server).saveTimestamp
        /home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/tso.go:69
github.com/pingcap/pd/server.(*Server).syncTimestamp
        /home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/tso.go:99
github.com/pingcap/pd/server.(*Server).campaignLeader
        /home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/leader.go:253
github.com/pingcap/pd/server.(*Server).leaderLoop
        /home/jenkins/workspace/build_pd_master/go/src/github.com/pingcap/pd/server/leader.go:115

**Comment by azza77** [comment]
Server version: 5.7.10-TiDB-v2.1.0-rc.3-426-g8468e7e MySQL Community Server (Apache License 2.0)
配置升级core:2 memroy:2g 单节点部署成功了
多谢各位 帮忙排查，我自己的坑。。。

**Comment by winshu** [comment]
> 挂载可以启动成功

请问不能挂载 data 目录到 windows  是什么意思 ？
