### ISSUE TITLE
Leader balance ratio and Region balance ratio  are 100%?

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#9002]
version:
'5.7.10-TiDB-v2.1.0-5-g4dad722'

## Question

tidb  Detailed Description of Important Monitoring Indicators
![image](https://user-images.githubusercontent.com/35753836/50944643-35ccaa00-14cc-11e9-832e-a403bff736a5.png)

my grafana  show
![image](https://user-images.githubusercontent.com/35753836/50944627-23eb0700-14cc-11e9-88d3-4d8499f9af96.png)

**Comment by shenlijungg** [comment]
![image](https://user-images.githubusercontent.com/35753836/50944829-01a5b900-14cd-11e9-80ff-9c044a3519b2.png)

**Comment by shenlijungg** [comment]
![image](https://user-images.githubusercontent.com/35753836/50944880-3fa2dd00-14cd-11e9-970f-3c90d68cbb96.png)

**Comment by nolouch** [comment]
@shenlijungg  can you show the metrics of the `Balance` panel.

**Comment by shenlijungg** [comment]
@nolouch 
![image](https://user-images.githubusercontent.com/35753836/50946295-7bd93c00-14d3-11e9-8224-122847688429.png)
![image](https://user-images.githubusercontent.com/35753836/50946315-94495680-14d3-11e9-94bf-0773d4a017f7.png)
![image](https://user-images.githubusercontent.com/35753836/50946329-a1664580-14d3-11e9-8621-e99befb8937a.png)

**Comment by nolouch** [comment]
Seems you have a tombstone store. This ratio is according the maximum and minimum score，so the ratio is high. But the cluster is normal, we will improve these metrics in the next version.

**Comment by shenlijungg** [comment]
@nolouch   thanks!
