### ISSUE TITLE
character gbk to be supported ?

### ISSUE THREAD

**Issue by jianhaiqing** [pingcap/tidb#9013]
## Question

* will gbk be supported in the coming days ? columns needs to be sorted by Chinese.
```
阿民哥    a
白天      b
冬雪      d
```
* sql as follows
```
SELECT  
  * 
FROM  
  ep_gbk_comming  
WHERE  
  class_id= 'xxxxxxxxxxxxxxxxxxxxxx' 
  AND  isdeleted= '0' 
ORDER BY  
  CONVERT( student_name  USING  gbk) asc;
```

- Searched open and closed [GitHub issues](https://github.com/pingcap/tidb/issues?utf8=%E2%9C%93&q=is%3Aissue)
- Read the documentation:
  - [TiDB Readme](https://github.com/pingcap/tidb)
  - [TiDB Doc](https://github.com/pingcap/docs)

**Comment by morgo** [comment]
TiDB currently sorts results based on binary order. It is possible with collations to respect the sorting rules of various languages.

This feature is on the [roadmap](https://pingcap.com/docs/ROADMAP/), initially with a general case insensitive collation.

Please let me know if I can help answer further.  Thanks!

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!

**Comment by nullnotnil** [comment]
A duplicate issue to track this issue is available in https://github.com/pingcap/tidb/issues/10760
