### ISSUE TITLE
incorrect error msg for utf8mb4 unsupport value

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#9016]
utf8mb4 doesn't support value unhex('303030cac7'), the error msg is not correct.

repro steps:
```
create table t600(name varchar(100) charset utf8mb4) charset=utf8mb4;
insert into t600 values ( unhex('303030cac7') );
```

MySQL:
> mysql> create table t600(name varchar(100) charset utf8mb4) charset=utf8mb4;
> Query OK, 0 rows affected (0.13 sec)
> 
> mysql> insert into t600 values ( unhex('303030cac7') );
> ERROR 1366 (HY000): incorrect utf8 value 303030cac7(000for column name

MySQL:

> mysql> create table t600(name varchar(100) charset utf8mb4) charset=utf8mb4;
> Query OK, 0 rows affected (0.02 sec)
> 
> mysql> insert into t600 values ( unhex('303030cac7') );
> ERROR 1366 (HY000): Incorrect string value: '\xCA\xC7' for column 'name' at row 1

> Release Version: v2.1.2-1-g8ba8096
> Git Commit Hash: 8ba809622668a1287e9f7152bfd34ad6be220304
> Git Branch: release-2.1
> UTC Build Time: 2018-12-21 03:45:55
> GoVersion: go version go1.11.2 linux/amd64
> Race Enabled: false
> TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
> Check Table Before Drop: false

**Comment by ciscoxll** [comment]
Waiting for this PR https://github.com/pingcap/tidb/pull/8818.

**Comment by winkyao** [comment]
Close via #8818

**Comment by winkyao** [comment]
@ciscoxll This issue is the wrong message. Not the same thing with #8818 .

**Comment by ciscoxll** [comment]
@winkyao I am writing a PR again to fix.

**Comment by nullnotnil** [comment]
Confirming this can still be reproduced:
```
..
mysql> insert into t600 values ( unhex('303030cac7') );
ERROR 1366 (HY000): incorrect utf8 value 303030cac7(000��) for column name
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-870-g2a8b96845
Edition: Community
Git Commit Hash: 2a8b968453520e4fcf9d6ff46c9f23b4ad23feee
Git Branch: master
UTC Build Time: 2020-07-31 08:45:35
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)
```
