### ISSUE TITLE
Do we need ntpd to perform clock synchronization during servers in the cluster

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9018]
tidb 各个服务器需要做ntpd时间同步吗？

**Comment by XuHuaiyu** [comment]
Hi, @ericisme 
ntpd is not needed in TiDB, we use PD to allocate the global unique timestamp.
[This](https://www.jianshu.com/p/4680bc2c2c65) can be referred.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
