### ISSUE TITLE
Query is slow and many `peer is not leader` errors appear in log

### ISSUE THREAD

**Issue by 474420502** [pingcap/tidb#9036]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
2019/01/14 14:58:19.244 ERRO endpoint.rs:468: Region(message: "peer is not leader" not_leader {region_id: 463256 leader {id: 855655 store_id: 5}})
2019/01/14 14:58:19.246 ERRO endpoint.rs:468: Region(message: "peer is not leader" not_leader {region_id: 648399 leader {id: 794218 store_id: 4}})
2019/01/14 14:58:19.246 ERRO endpoint.rs:468: Region(message: "peer is not leader" not_leader {region_id: 500006 leader {id: 756840 store_id: 7}})
2019/01/14 14:58:19.246 ERRO endpoint.rs:468: Region(message: "peer is not leader" not_leader {region_id: 525739 leader {id: 792206 store_id: 4}})
2019/01/14 14:58:19.246 ERRO endpoint.rs:468: Region(message: "peer is not leader" not_leader {region_id: 470628 leader {id: 907298 store_id: 4}})

忽然大量的这种日志, 非常的慢.

2. What did you expect to see?

3. What did you see instead?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

| Release Version: v2.1.0-rc.3-381-g7108881
Git Commit Hash: 71088815e7c5121e069d7ec10595d176a44b9bea
Git Branch: master
UTC Build Time: 2018-12-27 09:17:13
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.06 sec)

**Comment by rleungx** [comment]
Thanks for your feedback! @474420502 
How long does this problem last for? And what is your TiKV version?

**Comment by 474420502** [comment]
@rleungx  2 hours
TiKV 
Release Version:   3.0.0-alpha
Git Commit Hash:   72bf02f8a71fef7d66c69deb1f9e0b25ba49a9ee
Git Commit Branch: master
UTC Build Time:    2018-12-27 03:07:19
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by 474420502** [comment]
@rleungx  知道问题了, 数据量不大日志行数太多(5亿). 拆出来就问题就减缓了.

**Comment by rleungx** [comment]
> 数据量不大日志行数太多(5亿). 拆出来就问题就减缓了.

@474420502 Hmmm...sorry, I do not quite understand what you did. Could you explain more? What do you mean about splitting?

**Comment by 474420502** [comment]
就是 有很多insert 冲突, 单表行数太大 - 这样的情境.  然后我暴力的把表的数据拆出来, 新创建一个新表. 然后恢复正常!
