### ISSUE TITLE
str_to_date function does not support ms

### ISSUE THREAD

**Issue by zhaojunliRain** [pingcap/tidb#9039]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
Run sql: select str_to_date('1982-10-01 20:37:16.100', '%Y-%m-%d %H:%i:%s.%f');

2. What did you expect to see?
Return a data time value: 1982-10-01 20:37:16.100

3. What did you see instead?
Return value: null

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.0
Git Commit Hash: 637e130e6a9ba2e54e158131c0466233db39a60e
Git Branch: release-2.0
UTC Build Time: 2018-04-27 11:43:00
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1

**Comment by XuHuaiyu** [comment]
@zhaojunliRain 
Thanks for your feedback.

**Comment by shinytang6** [comment]
can l work on that?

**Comment by zz-jason** [comment]
> can l work on that?

Sure!

**Comment by shinytang6** [comment]
After digging into the code, l found that almost all the functions defined [here](https://github.com/pingcap/tidb/blob/master/types/time.go#L2151) have the same problems, tidb limits the length while mysql uses automatically zero padding.

e.g.

     select str_to_date('1982-10-01 20:37:1.100', '%Y-%m-%d %H:%i:%s');

also return null because the second is `1` not `01`.

@zz-jason @XuHuaiyu Is there any implementation of automatic zero padding in tidb now?

**Comment by nullnotnil** [comment]
Confirming that this is fixed in master:
```sql
mysql> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-859-gccfc9b2ad
Edition: Community
Git Commit Hash: ccfc9b2ad0dcf8e447210de5f559d7fc208db968
Git Branch: master
UTC Build Time: 2020-07-29 09:37:45
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

mysql> select str_to_date('1982-10-01 20:37:16.100', '%Y-%m-%d %H:%i:%s.%f');
+----------------------------------------------------------------+
| str_to_date('1982-10-01 20:37:16.100', '%Y-%m-%d %H:%i:%s.%f') |
+----------------------------------------------------------------+
| 1982-10-01 20:37:16.100000                                     |
+----------------------------------------------------------------+
1 row in set (0.00 sec)
```
