### ISSUE TITLE
problems about mydumper, loader, syncer

### ISSUE THREAD

**Issue by longhuguoji** [pingcap/tidb#9041]
question1:
在使用mydumper/loader的过程中，需要一定的时间。同步完之后，再提起syncer会丢失一定数据。请问，是先提起来syncer然后再执行mydumper/loader过程吗？
qustion2:
mydumper中的-t参数代表提起来n个线程卸数，t一般定义多大？
qustion3:
loader中的-t参数代表提起来n个线程装数据，且一个线程同一时间只能处理一个表，假如装100张表，是否t使用100，效率会高？

**Comment by WangXiangUSTC** [comment]
1. you need get the binlog position `pos` before execute mydumper, after all data is loaded in tidb by loader, use  this `pos` to start syncer
2. the default value of threads is 4, you can adjust it according to your mysql and system's configuration. 
3. it depends on your mysql/tidb's performance and your system's cpu performance. Under normal circumstances，the default value 16 is enough.

**Comment by WangXiangUSTC** [comment]
I will close this issue, you can reopen it if have any other question. @longhuguoji

**Comment by longhuguoji** [comment]
@WangXiangUSTC 你好，通的某个库下面有表，show tables可以看到，但是执行select语句报表不存在:table 'pboc.person_info; 'doesn't exist'；请问怎么回事？

**Comment by XuHuaiyu** [comment]
Maybe you need to change \`pboc.person_info;\` to \`pboc.person_info\`. @longhuguoji

**Comment by longhuguoji** [comment]
@WangXiangUSTC 你好，我想请假几个问题。
1、我想在Prometheus监控tidb通过syner实时同步mysql的日志，但是官网文档写的比较模糊：在 Prometheus 中添加 Syncer job 信息，将以下内容刷新到 Prometheus 配置文件，配置文件在哪儿？
配置 Prometheus 告警，将以下内容刷新到 alert.rule 配置文件， alert.rule文件找不见？
2、我想搭建一套生产环境，现在A平台生产一共2T多的数据，请问用虚拟机+全sas盘部署，性能有多少影响？
3、暂时我会把tidb做mysql的从库，将来切换主库后，有没有相应的回退机制？是提前把mysql做成tidb的从库吗？还是有更好的方案？

**Comment by amyangfei** [comment]
@longhuguoji 
1. `syncer` has no `Prometheus` deployment integration，If you want to send metrics to `Prometheus` you need to deploy `Prometheus` first, and then add `relevant` relevant configurations to `Prometheus` config.
2. If you use `loader` to load 2TB data into TiDB, even if you use `physical machine with SSD PCI-E`, it may still cost much time. For large data full mode import, [TiDB-lightning](https://github.com/pingcap/tidb-lightning) is recommended.
3. you can use `TiDB binlog tool` to sync data from TiDB to MySQL, but it is not recommended. A better may be MySQL -> TiDB(master) -> TiDB(slave), traffic to MySQL, then change traffic to TiDB with TiDB(master) -> TiDB(slave). Besides TiDB itself is high availability already

**Comment by WangXiangUSTC** [comment]
@kennytm PTAL
@longhuguoji it is better to create a new issue if you have another question.

**Comment by kennytm** [comment]
@longhuguoji The current TiDB-Lightning version doesn't support merging sharded tables yet. There's currently a PR pingcap/tidb-lightning#95 waiting to be reviewed, so the support and documentation will come in the future.
