### ISSUE TITLE
tikv cluster cpu usage different

### ISSUE THREAD

**Issue by wangpeng3477** [pingcap/tidb#9054]
I have three tikvs
Why are the CPU usage of the three tikvs very different？
![image](https://user-images.githubusercontent.com/12760152/51154851-7f443d00-18b0-11e9-81fd-b9fd23bc2412.png)

**Comment by rleungx** [comment]
@wangpeng3477 Thanks for your feedback! 
What is your TiKV version? And could you please check if there is a hot spot in PD dashboard?

**Comment by wangpeng3477** [comment]
![image](https://user-images.githubusercontent.com/12760152/51156083-fda2de00-18b4-11e9-9f38-fe07596d7a46.png)
![image](https://user-images.githubusercontent.com/12760152/51156143-2c20b900-18b5-11e9-90b5-a16f1bba1250.png)

**Comment by rleungx** [comment]
@wangpeng3477 Could you also share the `HotRegion` panel?

**Comment by wangpeng3477** [comment]
![image](https://user-images.githubusercontent.com/12760152/51156675-93d80380-18b7-11e9-834b-b6d3e61db6dd.png)

**Comment by wangpeng3477** [comment]
![image](https://user-images.githubusercontent.com/12760152/51156714-bbc76700-18b7-11e9-9c60-e128803e0c8c.png)

**Comment by rleungx** [comment]
It seems that store 1 has a read hot spot. I guess this is the reason why the usage of CPU on store1 is higher than others. You can also check `gRPC message count` in TiKV dashboard to see if most of requests are sent to store 1. The way to do it is as follows:
- modify the query by using `sum(rate(tikv_grpc_msg_duration_seconds_count{job=~"$job", type!="kv_gc"}[1m])) by (type, job)` in `grpc message count` on gRPC panel.
- change the `Legend format` to `{{type}} {{job}}`

**Comment by rleungx** [comment]
@wangpeng3477 You can click it and edit this panel.

**Comment by wangpeng3477** [comment]
![image](https://user-images.githubusercontent.com/12760152/51163408-85e4ab80-18d4-11e9-860a-06d99c57569c.png)
What should I do can average the load?

**Comment by rleungx** [comment]
You can use `pd-ctl` to check which Region is hot. The command lists as follows: 
```
./pd-ctl -u http://<ip>:<port>
>> hot read
```
After you find the Regions, you can transfer the leader of that Region into another store by using the following command:
```
>> operator add transfer-leader <region_id> <store_id>
```
If only one Region is hot, you can use split command to divide it into two Regions and then transfer the leader if needed:
```
>> operator add split-region <region_id>
```

**Comment by wangpeng3477** [comment]
If I maintain the status quo, will there be a problem?
such as tikv1 is full, will it be saved to other tikvs

**Comment by rleungx** [comment]
@wangpeng3477 In general, if only one TiKV is full, there are still two TiKV, which can meet the majority. It won't affect the normal service. What does matter is after TiKV1 is full, it can't be written. So it will cause some Regions only have two replicas. 
And in your case, I find the Region size is balanced. So this situation may not happen. When TiKV1 is full, the others may also be out of space.

**Comment by wangpeng3477** [comment]
I feel that the current CPU exception may still need to be improved, according to the method you said can be resolved
And <region_id> <store_id> where to get it

**Comment by wangpeng3477** [comment]
My topology is 1 pd_server,1 tidb,3 tikv.
Does it have anything to do with this?

**Comment by rleungx** [comment]
@wangpeng3477 When you use the following command, it will list some Regions which are hot spots. You can find <region_id> from the output. As for <store_id>, you can choose store 4 or store 5 in your case.
```
./pd-ctl -u http://<ip>:<port>
>> hot read
```

**Comment by wangpeng3477** [comment]
<ip>:<port>  are pd's machine param?

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
