### ISSUE TITLE
how to change IP address for tidb cluster

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#9056]
## Question
目前集群已搭建 5tidb,6 tidv,3pd,3pump,1 drainer，目前有数据已有。
目前集群部署在eth0   10.xxx.xxx.xxx 地址
想切换的eth2   172.xxx.xxx.xxx 地址
目前测试环境失败，PD, ETCD 是否需要重新部署，pd 的data.pd  是否需要复制到新节点。

**Comment by nolouch** [comment]
@shenlijungg  Or you can test with this way:
1. use [`pd-recover`](https://github.com/pingcap/docs-cn/blob/master/tools/pd-recover.md) to rebuild  the PD cluster.
2. modify the PD address in other component configuration file.

**Comment by shenlijungg** [comment]
@XuHuaiyu @nolouch  thanks!
