### ISSUE TITLE
Manual deployment monitoring? 

### ISSUE THREAD

**Issue by duhongx** [pingcap/tidb#9068]
I am an Operations and Maintenance Engineer, using Ansible offline deployment of all components have been installed, there are no binary installation steps, follow-up deployment is no longer deployed in the Internet environment, need to manually install export, prometheus, grafana, alertmanager components, how these components are installed, can you tell me?

**Comment by liubo0127** [comment]
You can refer to the documentation: https://pingcap.com/docs-cn/op-guide/offline-ansible-deployment/. Using the offline download method, you still need to execute local_prepare.yml (download related dependencies) on a networked machine, and then transfer it to the corresponding machine. Follow the online method to deploy, all components will be deployed automatically.

**Comment by duhongx** [comment]
Is there any way to manually deploy tidb/pd/tikv monitoring? For example, if you deploy tidb using docker, how should you deploy monitoring?
