### ISSUE TITLE
Disk IO keep close to 100%, even if I remove the region leaders on that node

### ISSUE THREAD

**Issue by jeeffy** [pingcap/tidb#9069]
Tidb cluster with 5 nodes are installed by docker, version is v2.1.2, cluser info as follows:
``` 
tidb-1   24C 128G 4TSAS
pd-1    24C 128G 4TSAS
tikv-1  32C 128G 512GSSD
tikv-2  32C 128G 512GSSD
tikv-3  32C 128G 512GSSD
```
I found that the disk IO of tikv-3 was very high, close to 100%, but the other two nodes were very low, about 20%. By the pd-ctl command `scheduler add evict-leader-scheduler 6`, all the region leaders on tikv-3 are evicted, and the disk IO is still close to 100%, the other two nodes are about 60%.

Disk IO(sdb) info of tikv-3
![image](https://user-images.githubusercontent.com/10725676/51170702-095cc780-18ea-11e9-9618-07df8c4ecc39.png)

```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00   10.00     0.00   160.00    32.00     0.14   13.50    0.00   13.50   9.70   9.70
sdb               0.00    10.00    4.00  272.00   512.00 67196.00   490.64   135.63  495.52  619.50  493.69   3.62 100.00
```

**Comment by rleungx** [comment]
@jeeffy Thanks for your feedback!
Could you please check if there is a write stall? Or if there is another process to write the disk?

**Comment by jeeffy** [comment]
Only tikv-3 is using the disk，how to check write stall in docker?

**Comment by rleungx** [comment]
@ethercflow PTAL.

**Comment by ethercflow** [comment]
@jeeffy 

Eg: your tikv-3's data disk is /dev/sdb, you can analyze IO performance as follows
```
blktrace -d /dev/sdb (after 2 mins, ctrl-c to stop)
blkparse -i sdb -d sdb.blktrace.bin > /dev/null 2>&1
btt -i sdb.blktrace.bin > sdb.btt
```
then please upload sda.btt.

Notice, please run blktrace on other disks, it can generate IO request too.

**Comment by jeeffy** [comment]
@ethercflow Thanks, disk sdb performance as follows.  check with ``

**Comment by jeeffy** [comment]
Result of blktrace performance testing:
```
==================== All Devices ====================

            ALL           MIN           AVG           MAX           N
--------------- ------------- ------------- ------------- -----------

Q2Q               0.000001354   0.385233767   5.007913056          13
Q2G               0.000000666   0.000003183   0.000011095           6
G2I               0.000000690   0.000013946   0.000024828           6
Q2M               0.000000350   0.000000573   0.000001366           8
I2D               0.000000620   0.000010348   0.000020437           6
M2D               0.000004486   0.000013452   0.000031329           8
D2C               0.000027220   0.000068879   0.000093731          14
Q2C               0.000029327   0.000088669   0.000133251          14

==================== Device Overhead ====================

       DEV |       Q2G       G2I       Q2M       I2D       D2C
---------- | --------- --------- --------- --------- ---------
 (  8, 16) |   1.5386%   6.7407%   0.3694%   5.0016%  77.6807%
---------- | --------- --------- --------- --------- ---------
   Overall |   1.5386%   6.7407%   0.3694%   5.0016%  77.6807%

==================== Device Merge Information ====================

       DEV |       #Q       #D   Ratio |   BLKmin   BLKavg   BLKmax    Total
---------- | -------- -------- ------- | -------- -------- -------- --------
 (  8, 16) |       14        6     2.3 |        8       18       56      112

==================== Device Q2Q Seek Information ====================

       DEV |          NSEEKS            MEAN          MEDIAN | MODE           
---------- | --------------- --------------- --------------- | ---------------
 (  8, 16) |              14      71366462.3               0 | 0(9)
---------- | --------------- --------------- --------------- | ---------------
   Overall |          NSEEKS            MEAN          MEDIAN | MODE           
   Average |              14      71366462.3               0 | 0(9)

==================== Device D2D Seek Information ====================

       DEV |          NSEEKS            MEAN          MEDIAN | MODE           
---------- | --------------- --------------- --------------- | ---------------
 (  8, 16) |               6     166521745.3               0 | 0(1)
                                                               ...(5 more)
---------- | --------------- --------------- --------------- | ---------------
   Overall |          NSEEKS            MEAN          MEDIAN | MODE           
   Average |               6     166521745.3               0 | 0(1)
                                                               ...(5 more)


==================== Plug Information ====================

       DEV |    # Plugs # Timer Us  | % Time Q Plugged
---------- | ---------- ----------  | ----------------
 (  8, 16) |          2(         0) |   0.000803788%

       DEV |    IOs/Unp   IOs/Unp(to)
---------- | ----------   ----------
 (  8, 16) |        2.5          0.0
---------- | ----------   ----------
   Overall |    IOs/Unp   IOs/Unp(to)
   Average |        2.5          0.0

==================== Active Requests At Q Information ====================

       DEV |  Avg Reqs @ Q
---------- | -------------
 (  8, 16) |           1.3

==================== I/O Active Period Information ====================

       DEV |     # Live      Avg. Act     Avg. !Act % Live
---------- | ---------- ------------- ------------- ------
 (  8, 16) |          3   0.000064831   2.503984403   0.00
---------- | ---------- ------------- ------------- ------
 Total Sys |          3   0.000064831   2.503984403   0.00

# Total System
#     Total System : q activity
  0.000001973   0.0
  0.000001973   0.4
  0.000098256   0.4
  0.000098256   0.0
  5.008011312   0.0
  5.008011312   0.4
  5.008040941   0.4
  5.008040941   0.0

#     Total System : c activity
  0.000078306   0.5
  0.000078306   0.9
  0.000127583   0.9
  0.000127583   0.5
  5.008144563   0.5
  5.008144563   0.9
  5.008163300   0.9
  5.008163300   0.5

# Per process
#             jbd2 : q activity
  0.000001973   1.0
  0.000001973   1.4
  0.000098256   1.4
  0.000098256   1.0

#             jbd2 : c activity

#           kernel : q activity

#           kernel : c activity
  0.000078306   2.5
  0.000078306   2.9
  0.000127583   2.9
  0.000127583   2.5
  5.008144563   2.5
  5.008144563   2.9
  5.008163300   2.9
  5.008163300   2.5

#          kworker : q activity
  5.008011312   3.0
  5.008011312   3.4
  5.008040941   3.4
  5.008040941   3.0

#          kworker : c activity
```

**Comment by jeeffy** [comment]
All the disks on 3 tikvs are the same, they are Intel 545s 512G. Why is only the disk IO of tikv-3 full?

**Comment by StoneZoul** [comment]
hi, i have met the same issue...
I am using SSD disk，but it still not fit the requirement... when i do ansible-playbook bootstrap.yml it tells me "fio: randread iops of tikv_data_dir disk is too low: 11377 < 40000, it is strongly recommended to use SSD disks for TiKV and PD, or there might be performance issues."...

I saw previous issue: https://github.com/pingcap/tidb/issues/6359 said 8500 is min read iops reqirement, why it requires 40000 now...? 

how can i skip machine performace checking?  I have try to set "dev_mode = True" and "machine_benchmark = False" in tidb-ansible/inventory.ini but it is not working... 

the tidb_version in tidb-ansible/inventory.ini  is v2.0.11

thank you

**Comment by ethercflow** [comment]
@rleungx PTAL

**Comment by rleungx** [comment]
@StoneZoul You can try to use the following command:
`ansible-playbook bootstrap.yml --extra-vars "dev_mode=True"`

**Comment by rleungx** [comment]
@jeeffy Can you share us more metrics? 
- write flow and compaction flow in both `RocksDB-kv` and `RocksDB-raft` panel of TiKV dashborad.
- grpc message count in `Grpc` panel of TiKV dashborad.
Before you upload them, you can use edit it and modify the query like this:
![image](https://user-images.githubusercontent.com/35896542/51250543-a34b6f80-19d1-11e9-816e-a22a584ac863.png)
- leader count and leader score in Balance panel of PD dashborad.

**Comment by StoneZoul** [comment]
> @StoneZoul You can try to use the following command:
> `ansible-playbook bootstrap.yml --extra-vars "dev_mode=True"`

thank you,  ansible-playbook bootstrap.yml --extra-vars "dev_mode=True" works

**Comment by siddontang** [comment]
@jeeffy 

I think you can use `iotop` to check which costs high IO.

**Comment by jeeffy** [comment]
@siddontang snapshot of iotop
![9pnpk k36jcy44zen dym9](https://user-images.githubusercontent.com/10725676/51289861-e0991700-1a3c-11e9-8c23-ca0729d246c8.png)

Snapshot of `top -H`
![295j3 tp ff2j5nv2uzfaom](https://user-images.githubusercontent.com/10725676/51289948-2ce45700-1a3d-11e9-908d-1b1c1a9a69cc.png)

**Comment by ethercflow** [comment]
@jeeffy Would you please share us more info?

- Hosts os version
- filesystem mount parameters
- Is there any errors in demos

You may use https://github.com/ethercflow/diff-system-params/blob/master/recorder.sh to record the hosts kernel parameters and diff, let us make sure there's no difference between them.

BTW, please upload the other two  `iotop`  infos. Thank you.

**Comment by StoneZoul** [comment]
hi, guys. i have some questions...  The follow command is used to benchmark disk io performance in bootstrap.yml
" ./fio -ioengine=psync -bs=32k -fdatasync=1 -thread -rw=randread -size=10G -filename=fio_randread_test.txt -name='fio randread test' -iodepth=4 -runtime=60 -numjobs=4 -group_reporting --output-format=json --output=fio_randread_result.json"

my question is why choose "-ioengine=psync" instead of "-ioengine=libaio" ? why choose "-bs=32k -fdatasync=1" ? as the parameter of fio command?

**Comment by ethercflow** [comment]
@StoneZoul We use `psync` because it matches our current IO characteristics, below is the detail: https://www.jianshu.com/p/9d823b353f22 
Welcome discussion

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
