### ISSUE TITLE
Batch insert data with multi-threads meet error

### ISSUE THREAD

**Issue by vipsql** [pingcap/tidb#9077]
## Bug Report

1. What did you do?
多线程批量插入数据(采用mysql方式的批量数据插入),出现:
错误1: tikv gc worker is busy
错误2: tidbserver  [domain:1]Information schema is out of date.
github.com/pingcap/tidb/vendor/github.com/pkg/errors.AddStack
        /home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/vendor/github.com/pkg/errors/errors.go:173

2. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.0-rc.3-15-gaec4814
Git Commit Hash: aec4814ffef54801e24b4ce89435d0e5cb3dfdee
Git Branch: master
UTC Build Time: 2018-10-08 02:09:26
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

3.部署架构:
3台服务器,配置如下:
   Hardware:  30Core   128G   2*SSD+1SATA  1000Mbps  
   操作系统: CentOS Linux release 7.5.1804 (Core)
   TIDB部署:  3*TIDB-SERVER(Haproxy)  3*PDServer   3*TIKVSERVER

**Comment by jackysp** [comment]
Thanks for your report, @vipsql !
What is the specific bulking-insert workload?

**Comment by zhangjinpeng1987** [comment]
@vipsql Can you provide TiDB and TiKV 's log?

**Comment by vipsql** [comment]
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580434, error Request(message: "peer is not leader" not_leader {region_id: 12229})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580435, error Request(message: "peer is not leader" not_leader {region_id: 16325})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580437, error Request(message: "peer is not leader" not_leader {region_id: 11761})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580440, error Request(message: "peer is not leader" not_leader {region_id: 11761})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580441, error Request(message: "peer is not leader" not_leader {region_id: 13293})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580442, error Request(message: "peer is not leader" not_leader {region_id: 10833})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580443, error Request(message: "peer is not leader" not_leader {region_id: 12229})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580444, error Request(message: "peer is not leader" not_leader {region_id: 10833})
2019/01/16 11:33:44.733 ERRO process.rs:179: get snapshot failed for cid=1580449, error Request(message: "peer is not leader" not_leader {region_id: 13293})
2019/01/16 11:33:44.737 ERRO process.rs:179: get snapshot failed for cid=1566936, error Request(message: "peer is not leader" not_leader {region_id: 10833})
2019/01/16 11:33:44.737 ERRO process.rs:179: get snapshot failed for cid=1562811, error Request(message: "peer is not leader" not_leader {region_id: 13293})
2019/01/16 11:33:44.740 ERRO process.rs:179: get snapshot failed for cid=1580671, error Request(message: "peer is not leader" not_leader {region_id: 13293})
2019/01/16 11:33:44.740 ERRO process.rs:179: get snapshot failed for cid=1580708, error Request(message: "peer is not leader" not_leader {region_id: 16325})
2019/01/16 11:33:44.741 ERRO process.rs:179: get snapshot failed for cid=1580814, error Request(message: "peer is not leader" not_leader {region_id: 11761})
2019/01/16 11:33:44.741 ERRO process.rs:179: get snapshot failed for cid=1580822, error Request(message: "peer is not leader" not_leader {region_id: 10833})
2019/01/16 11:33:44.743 ERRO process.rs:179: get snapshot failed for cid=1578881, error Request(message: "peer is not leader" not_leader {region_id: 16325})
2019/01/16 11:33:44.743 ERRO process.rs:179: get snapshot failed for cid=1575651, error Request(message: "peer is not leader" not_leader {region_id: 10833})
2019/01/16 11:33:44.743 ERRO process.rs:179: get snapshot failed for cid=1571107, error Request(message: "peer is not leader" not_leader {region_id: 10833})

**Comment by vipsql** [comment]
TiDB Error:
2019/01/16 11:36:44.601 backoff.go:240: [warning] backoffer.maxSleep 20000ms is exceeded, errors:
server is busy, ctx: &{{11477 5 315} id:11477 start_key:"t\200\000\000\000\000\000\000\334_i\200\000\000\000\000\000\000\001\001eb25ed36\3773d42ec46\37712e7238c\3773b05d9dc\37776746e66\37765646362\37702346fb7\377ee708d4a\377461f8717\3770eb56984\37730313233\37734353637\377\000\000\000\000\000\000\000\000\367" end_key:"t\200\000\000\000\000\000\000\334_i\200\000\000\000\000\000\000\001\001ebf1badc\377edcf763f\377fc86ad53\377ce05a5b5\377e99988e6\377b2bbe694\377f917d86a\3778d3f19e6\37752319c6a\3778061f2f8\377e4b8ade4\377b99de4b9\377\000\000\000\000\000\000\000\000\367" region_epoch:<conf_ver:5 version:315 > peers:<id:11478 store_id:1 > peers:<id:11479 store_id:4 > peers:<id:11480 store_id:6 >  id:11479 store_id:4  172.12.104.108:20160} at 2019-01-16T11:36:29.048240077+08:00

2019/01/16 11:36:39.723 region_request.go:220: [warning] tikv reports `ServerIsBusy`, reason: scheduler is busy, ctx: &{{18649 5 315} id:18649 start_key:"t\200\000\000\000\000\000\000\334_i\200\000\000\000\000\000\000\001\001ee3e980f\37716b98171\37771608f7f\37791fa29b7\377c3b17473\377706f6e6d\377f4d23679\377526c38b2\3775f1d239d\377a3b47a0c\37730313235\37737464861\377\000\000\000\000\000\000\000\000\367" end_key:"t\200\000\000\000\000\000\000\334_i\200\000\000\000\000\000\000\001\001ef07a61b\3775c792ed2\377182d5b98\377204e982d\377e999a2e5\377a4aee59b\3772e50dbbc\37717f7132b\377268b0892\3775b7e38e6\37730313233\377363839e4\377\000\000\000\000\000\000\000\000\367" region_epoch:<conf_ver:5 version:315 > peers:<id:18650 store_id:1 > peers:<id:18651 store_id:4 > peers:<id:18652 store_id:6 >  id:18651 store_id:4  172.12.104.108:20160}, retry later

**Comment by vipsql** [comment]
@jackysp i want to make the stream calculate result store to tidb

**Comment by zhangjinpeng1987** [comment]
`errors: server is busy` it is caused by TiKV's flow control mechanism, there is too much data pour into TiKV in a short time.

**Comment by zhangjinpeng1987** [comment]
How large your batch size is? And how about the client concurrency?

**Comment by vipsql** [comment]
@zhangjinpeng1987  the batch size is about 3000 rows/s  and the client is about 40~50

**Comment by zhangjinpeng1987** [comment]
You said `tikv gc worker is busy`, it was `sever is busy` error indeed?

**Comment by zhangjinpeng1987** [comment]
For version 2.1 and for this 3 node tikv cluster, you can try small batch size like 100, or smaller concurrency like 8. You also can try version 3.0 GA which has better performance.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel fee to re-open it if you have additional questions. Thanks!
