### ISSUE TITLE
Weird index / table scan beahvior for same SQL

### ISSUE THREAD

**Issue by ihipop** [pingcap/tidb#9084]
## Bug Report

1. What did you do?
Same SQL，Chnange the `mobile` and `username` in SQL，One will have a bunch of table scan，The other have `0` index Scan and table scan

## sql#1
![image](https://user-images.githubusercontent.com/423077/51224984-6e183080-1983-11e9-9cfa-81794472b225.png)

## sql#2
![image](https://user-images.githubusercontent.com/423077/51227094-aa508e80-198d-11e9-9135-58e53e24314b.png)

When **sql#2** executed ,one of the `KV` will have a very big amount of `read` ,sometime to `Gbps`

![image](https://user-images.githubusercontent.com/423077/51227337-ba1ca280-198e-11e9-9991-4d56d06e5380.png)

The trigger param (`mobile` and `username` ) of **sql#2** is random,but if happened,This can be repeated stably

2. What did you expect to see?
like **sql#1**

3. What did you see instead?
like **sql#2**

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
Release Version: v2.1.0
Git Commit Hash: 08f0168a6caea0280d6157e5be69f2dc6fd0d5b3
Git Branch: release-2.1
UTC Build Time: 2018-11-30 11:39:09
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by eurekaka** [comment]
@ihipop Thanks for your feedback.

The behavior is decided by the data in your table, i.e, if a lot of rows satisfy the condition `receiver_mobile = xxx`, then the `read` metrics would increase. You can run the following SQL to know how many rows actually scanned:
```sql
select count(*) from platform_order use index (receiver_mobile-company_id) where receiver_mobile = xxx;
```

**Comment by ihipop** [comment]
@eurekaka But what about this,I use index to select the exact order no
```sql
explain select * from `platform_order_item` use index (`order_id`) where `platform_order_item`.order_id`='7977c4b2-180e-11e9-b458-339fbf8ebf51' 
```
there is a index named `order_id`
![image](https://user-images.githubusercontent.com/423077/51240681-332ff000-19b7-11e9-9590-70f88b39b902.png)

still have both `table scan` and `index scan`
and a very low query speed 

with a bunch of read  and many `GRPC error` and db slow down

![image](https://user-images.githubusercontent.com/423077/51240868-99b50e00-19b7-11e9-9597-4fb11cc9cc67.png)

**Comment by ihipop** [comment]
@eurekaka But what about this,I use index to select the exact order id
```sql
explain select * from `platform_order_item` use index (`order_no`) where `platform_order_item`.order_no ='xxxxxxxx'  and platform_type = 2
```
![image](https://user-images.githubusercontent.com/423077/51241882-b2262800-19b9-11e9-89e5-f94756731ad5.png)

there is a index named `order_no`

![image](https://user-images.githubusercontent.com/423077/51241812-8f940f00-19b9-11e9-8858-de9a6712e2d0.png)


still have both `table scan` and `index scan`

if I remove `use index (`order_no`)` it will cause  and a slow query speed and with a bunch  Mbps of read and some `GRPC error`

![image](https://user-images.githubusercontent.com/423077/51241911-c538f800-19b9-11e9-9d75-397cd39e1414.png)

# But
 if i change `xxxxxxxx` to `yyyyyyy` which `platform_type=1` (platform_type=1 **is most of all in the table**)
I don't need the   `use index (`order_no`)` ,it's a very fast,this is Weird

![image](https://user-images.githubusercontent.com/423077/51241738-68d5d880-19b9-11e9-9d17-8aa3b641a4ec.png)

**Comment by ihipop** [comment]
@eurekaka if i change `order_no` from `xxxxxxxx` to `yyyyyyy` which `platform_type=1` (platform_type=1 **is most of all in the table**)，the index of explain become `0`，but there is one row returned.
```
count 预计当前算子将会输出的数据条数，基于统计信息以及算子的执行逻辑估算而来。
```


# And

有时候查询索引的选择也有问题，表里面**只有且只有一个**order_id相关索引，查询条件也只有一个order_id，使用的使用还是必须对查询 使用 use index 指定order_id索引，否则就是表扫
![image](https://user-images.githubusercontent.com/423077/51243903-b3a61f00-19be-11e9-9e60-185bcfebc9f5.png)

```
explain select * from `platform_order_item` where `platform_order_item`.`order_id` = 'f7220b47-e70e-11e8-8233-69161ff5ce4c'
```

```
TableReader_7	349552526.00	root	data:Selection_6
└─Selection_6	349552526.00	cop	eq(sync_orders.platform_order_item.order_id, "f7220b47-e70e-11e8-8233-69161ff5ce4c")
  └─TableScan_5	349552526.00	cop	table:platform_order_item, range:[-inf,+inf], keep order:false
```

**Comment by eurekaka** [comment]
First, `count` of explain is an estimation, not the real number of rows returned. Second, planner would compare the cost of index scan and table scan, if the filter is always true, table scan would be faster than index scan, because index scan would be accompanied with a table scan to get the whole row as you pasted above, that would incur cost. From the explain output you pasted, planner believes `order_id = 'f7220b47-e70e-11e8-8233-69161ff5ce4c'` can filter out no rows, so it prefers table scan over index lookup.

**Comment by ihipop** [comment]
@eurekaka Thanks for your patient

> From the explain output you pasted, planner believes `order_id = 'f7220b47-e70e-11e8-8233-69161ff5ce4c'` can filter out no rows, so it prefers table scan over index lookup.

 But ,**The `planner` choose the wrong way. In this Example**, `planner`  prefers `table scan` over `index lookup`, But it cause a very slow query speed **in Minutes**. If I re-query it with ```use index (`order_id`)``` trick  , **the result will return in 0.0x seconds**, 
Same SQL ,different `UUID`,Some `UUID` of `order_id` doesn't need the ``use index`` trick,Some Must,You've said that is data depended, But The behavior of `planner` is so un-predictable，In My business logic, I'm right about  ``use index`` trick to force the  `planner`  to choose the `index lookup`,what about the data that I'm wrong when  `table scan` is faster than `index lookup` on some of data? I cant predict it.

**Comment by eurekaka** [comment]
@ihipop First, planner makes its decision of using table scan or index lookup based on statistics information and the value of the `order_id` in your query, so different `order_id` may lead to different decisions, that is normal, not "un-predictable", you can refer to https://github.com/pingcap/docs-cn/blob/master/sql/statistics.md for details of statistics.

Second, as you mentioned, using `use index` would speed up the query, that indicates planner makes wrong decision. There are 2 possible reasons accounting for this wrong decision:
1) statistics is out of date;
2) if statistics is not of date, then it indicates that planner has bug in estimating the cost;

Please follow the below step to check the reason causing the wrong decision:
1) save the current statistics information first:
```sh
curl -G "http://${tidb-server-ip}:${tidb-server-status-port}/stats/dump/${db_name}/${table_name}" > ${table_name}_stats.json
```
2) save the current execution plan of the query, including using index hint and not using index hint respectively:
```sql
explain analyze select ...
explain format="dot" select ...
explain select ...
```
3) update statistics information of the table manually:
```sql
analyze table {table_name};
```
4) check if the execution plan has changes after updating stats:
```sql
explain analyze select ...
explain format="dot" select ...
explain select ...
```
5) if planner still chooses table scan and the query is much slower than index scan, please save the schema of the tables and upload the stats saved in the first step to help us investigate this problem.
```sql
show create table ${involved_table}\G
```

**Comment by ihipop** [comment]
@eurekaka Thanks for your information，I will look into it and dig some information with our DBA to find some thing about it. I will continue to post our progress here if there is any update

**Comment by ihipop** [comment]
@eurekaka does `tidb_auto_analyze_ratio` indicates that the `auto_analyze` is disabled?

**Comment by eurekaka** [comment]
@ihipop yes, if `tidb_auto_analyze_ratio` is 0, auto analyze is disabled; if `tidb_auto_analyze_ratio` is larger than 0 but less than 0.3, it would be adjusted to 0.3; if `tidb_auto_analyze_ratio` is larger than 0.3, it would be the value specified.

**Comment by ihipop** [comment]
@eurekaka My `tidb_auto_analyze_ratio` is 0,but why the table meta still beeing updated?

```
dbname	table_u	2019-01-17 14:12:16	12785155	159919895
dbname	table_e	2019-01-17 14:05:15	416502	52705884
dbname	table_o	2019-01-17 14:10:35	13728652	223699892
dbname	table_oi	2019-01-17 14:10:34	8090148	352397624
```

And mean while the `Stats Inaccuracy Rate-99` is almost 80%  ?

https://user-images.githubusercontent.com/423077/51296850-d422b780-1a58-11e9-8acb-2be65552e856.png

**Comment by eurekaka** [comment]
Stats would be updated not only by manual analyze or auto analyze, but also statistics feedback mechanism. @lamxTyler please double confirm this.

**Comment by lamxTyler** [comment]
Yes, and when you perform DML queries, the stats meta will also be updated. You can refer to https://github.com/pingcap/docs/blob/master/sql/statistics.md#automatic-update

**Comment by ihipop** [comment]
@eurekaka so in my case , `SHOW STATS_META`/`SHOW STATS_HISTOGRAMS`returns normal and said that it is almost the latest updated,But  `SHOW STATS_BUCKETS` returns 

![image](https://user-images.githubusercontent.com/423077/51300374-9c227100-1a66-11e9-8e4c-125d9b4a99ae.png)

does the wrong decision of `order_id` made by planner is caused by this reason?

**Comment by eurekaka** [comment]
No, it is saying that your stats **inaccuracy** rate is 80%, and the `Modify_count` is pretty high, both indicates stats is out of date. @lamxTyler please take a look at the error of `show stats_buckets`, is it normal?

**Comment by lamxTyler** [comment]
@ihipop Could you provide the detailed tidb log when the error happens?

**Comment by ihipop** [comment]
> @ihipop Could you provide the detailed tidb log when the error happens?

@lamxTyler 

```
2019/01/17 15:31:32.407 conn.go:499: [warning] con:95034 dispatch error:
id:95034, addr:10.40.30.6:40366 status:2, collation:utf8_general_ci, user:root
"SHOW STATS_BUCKETS"
insufficient bytes to decode value
github.com/pingcap/tidb/util/codec.decodeBytes
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/util/codec/bytes.go:78
github.com/pingcap/tidb/util/codec.DecodeBytes
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/util/codec/bytes.go:124
github.com/pingcap/tidb/util/codec.DecodeOne
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/util/codec/codec.go:381
github.com/pingcap/tidb/util/codec.DecodeRange
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/util/codec/codec.go:328
github.com/pingcap/tidb/statistics.ValueToString
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/statistics/histogram.go:352
github.com/pingcap/tidb/executor.(*ShowExec).bucketsToRows
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/show_stats.go:120
github.com/pingcap/tidb/executor.(*ShowExec).fetchShowStatsBuckets
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/show_stats.go:101
github.com/pingcap/tidb/executor.(*ShowExec).fetchAll
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/show.go:141
github.com/pingcap/tidb/executor.(*ShowExec).Next
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/show.go:70
github.com/pingcap/tidb/executor.(*recordSet).Next
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/adapter.go:97
github.com/pingcap/tidb/server.(*tidbResultSet).Next
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/driver_tidb.go:346
github.com/pingcap/tidb/server.(*clientConn).writeChunks
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:1002
github.com/pingcap/tidb/server.(*clientConn).writeResultset
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:966
github.com/pingcap/tidb/server.(*clientConn).handleQuery
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:883
github.com/pingcap/tidb/server.(*clientConn).dispatch
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:623
github.com/pingcap/tidb/server.(*clientConn).Run
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:481
github.com/pingcap/tidb/server.(*Server).onConn
 /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/server.go:324
runtime.goexit
 /usr/local/go/src/runtime/asm_amd64.s:1333
```

**Comment by lamxTyler** [comment]
@ihipop Thanks for your feedback! I will look into this problem.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
