### ISSUE TITLE
Inserting data slows down as the amount of data increases

### ISSUE THREAD

**Issue by jeeffy** [pingcap/tidb#9089]
Tidb cluster with 5 nodes are installed by docker, version is v2.1.2, cluser info as follows:
```
tidb-1  24C 128G 4TSAS
pd-1    24C 128G 4TSAS
tikv-1  32C 128G 512GSSD
tikv-2  32C 128G 512GSSD
tikv-3  32C 128G 512GSSD
```
Inserting data slows down as the amount of data increases.

|data increasement| cost|
|--------------------|-----|
|0->0.8 billion         |15h |
|1.1->1.5 billion      |15h |

At the same time, the amount of data inserted is reduced by half. Query performance also decreases dramatically as the amount of data increases.

**Comment by tiancaiamao** [comment]
PTAL @zhangjinpeng1987

**Comment by dbjoa** [comment]
@jeeffy Would you try to use [SHARD_ROW_ID_BITS](https://pingcap.com/docs/sql/tidb-specific/#shard-row-id-bits) when creating the tables?

**Comment by siddontang** [comment]
PTAL @Connor1996

**Comment by siddontang** [comment]
@jeeffy 

Does your Grafana show the same scenario as meituan's?

**Comment by jeeffy** [comment]
@siddontang The scenario is similar, but I don't configure heartbeat.

**Comment by Connor1996** [comment]
Do you sure the number of regions is decreased after enabling merge?

**Comment by Connor1996** [comment]
and please make sure `merge-schedule-limit` is not zero.
BTW, "max-merge-region-size" is too large, 20 is enough.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
