### ISSUE TITLE
Any chance to support changing the primary key with Syncer?

### ISSUE THREAD

**Issue by DamonYellow** [pingcap/tidb#9092]
In this doc: https://pingcap.com/docs-cn/tools/syncer/#sharding-同步支持, we found that one of the sharding rules is: "分表中是否包含唯一递增主键，或者合并后是否包含数据上有冲突的唯一索引或者主键".
Unfortunately, we set a auto-increment primary key starting from 1 in our separate tables(we think most people would also do that), but we do have another key that is globally unique, could we set it as the primary key for syncer sharding please?

**Comment by tiancaiamao** [comment]
PTAL @GregoryIan

**Comment by ljluestc** [comment]
```

CREATE TABLE `your_table` (
    `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Primary Key',
    `globally_unique_key` VARCHAR(255) NOT NULL COMMENT 'Globally Unique Key',
    ... -- Other columns
    PRIMARY KEY (`globally_unique_key`),
    UNIQUE KEY `id` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
