### ISSUE TITLE
tikv monitor data is missing

### ISSUE THREAD

**Issue by duhongx** [pingcap/tidb#9101]
Using ansible to deploy tidb cluster, after deployment, tikv monitoring data on grafana is not available, other data is normal, how to solve this problem?
![image](https://user-images.githubusercontent.com/27199500/51299778-890ea180-1a64-11e9-84b5-ad8bc6681ed7.png)

**Comment by duhongx** [comment]
![image](https://user-images.githubusercontent.com/27199500/51299861-c83cf280-1a64-11e9-9fb6-32cff4cfc5f2.png)
Other data are normal, only tikv data is missing。How to check and solve it?

**Comment by duhongx** [comment]
[root@bigdata2 bin]# ./tikv-server -V
TiKV 
Release Version:   2.1.2
Git Commit Hash:   509c8764cb14c173fc66d457639d9806449b890d
Git Commit Branch: release-2.1
UTC Build Time:    2018-12-21 05:39:30
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

[tidb@tidb tidb-ansible]$ ansible --version
ansible 2.6.11
  config file = /home/tidb/tidb-ansible/ansible.cfg
  configured module search path = [u'/home/tidb/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  4 2017, 00:39:18) [GCC 4.8.5 20150623 (Red Hat 4.8.5-16)]

**Comment by duhongx** [comment]
From /home/tidb/tidb-ansible/roles/collector_tikv/tasks
You can see that we use insight. py script to collect config and log of tikv, from data collection to writing prometheus, and finally show it on grafana. Do you have the corresponding documents in the middle? In the case of the disappearance of monitoring data, it is necessary to know the details to determine where the data disappeared.

**Comment by siddontang** [comment]
@rleungx 

seem this version uses `pull` mode?

**Comment by rleungx** [comment]
@duhongx Sorry for misleading. Actually, I mean your `tidb-ansible` version. BTW, you can visit web address of Prometheus to find if there is any data?
@siddontang This `Commit Hash` does not contain the pull mechanism.

**Comment by rleungx** [comment]
@duhongx Does your pushgateway works well? And can you find if there is any data in Prometheus?

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
