### ISSUE TITLE
don't resolve the charset of column from the table

### ISSUE THREAD

**Issue by IANTHEREAL** [pingcap/tidb#9120]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

* use `loader` to import data from mysql to tidb

* the schema is
```sql
CREATE TABLE `t` (
  `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `t` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_bin 
```
*  insert statement
```sql
00000000: 494e 5345 5254 2049 4e54 4f20 6074 6020  INSERT INTO `t` 
00000010: 5641 4c55 4553 2028 312c 22f6 6c22 293b  VALUES (1,".l");
```
`0xf6` is [West European Character Sets](https://dev.mysql.com/doc/refman/8.0/en/charset-we-sets.html)

2. What did you expect to see?

data is imported into tidb without error

3. What did you see instead?

```log
[warning] [exec][sql][USE `testutf8`; INSERT INTO `t` VALUES (1,"�l"); UPDATE `tidb_loader`.`checkpoint` SET `offset`=33 WHERE `id` ='2beae3' AND `filename`='testutf8.B_Ro][error]Error 1366: incorrect utf8 value f66c(�l) for column t

```
`CHARACTER SET` of column `t` should be `latin1`, but it's `utf8mb4_bin` in TiDB

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

`v2.1.2`

**Comment by GregoryIan** [comment]
https://github.com/pingcap/tidb/pull/9105 fix it

**Comment by nullnotnil** [comment]
This has been fixed. I am going to close this issue.
