### ISSUE TITLE
occasionally rollback failure

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb#9130]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
2019/01/14 16:57:42.554 session.go:1460: [info] [GENERAL_LOG] con:84608 user:xxx@1.2.3.4 schema_ver:39423 txn_start_ts:0 sql:SELECT 1
2019/01/14 16:57:42.557 session.go:1460: [info] [GENERAL_LOG] con:84608 user:xxx@1.2.3.4 schema_ver:39423 txn_start_ts:0 sql:SET autocommit=0
2019/01/14 16:57:42.557 set.go:180: [info] con:84608 autocommit=0
2019/01/14 16:57:42.752 session.go:1460: [info] [GENERAL_LOG] con:84608 user:xxx@1.2.3.4 schema_ver:39423 txn_start_ts:0 sql:insert into table1 (create_time, update_time, channel_id, contain_album, content_type, description, name, open_pid, qipu_id, type, uploader_id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [arguments: 2019-01-14 16:54:49, 2019-01-14 16:54:49, 1, 0, 0, 播单新时代update, 嫦娥飞天13, 2932030, 6000132, 6, 13280390]
2019/01/14 16:57:42.810 session.go:1460: [info] [GENERAL_LOG] con:84608 user:xxx@1.2.3.4 schema_ver:39423 txn_start_ts:0 sql:insert into table2 (create_time, update_time, active_end_time, active_start_time, audit_status, check_reason, content_source, keyword, page_first_publish_time, page_publish_status, page_publish_time, page_url, platform, play_order, play_order_by, public_level, resource_qipu_id, short_display_name) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [arguments: 2019-01-14 16:54:49, 2019-01-14 16:54:49, 2019-01-16 16:54:49, 2019-01-12 16:54:49, 2, 通过, 2, AI大会, 1547456089831, 1, 2019-01-15 16:54:49, http://xxx/yyy.html, 2,3,5,9, 1, 1, 1, 23802812, 播单短标题update]
2019/01/14 16:57:42.810 tidb.go:164: [info] RollbackTxn for ddl/autocommit error.
2019/01/14 16:57:42.810 conn.go:490: [warning] con:84608 dispatch error:
2019/01/14 16:57:42.885 session.go:1460: [info] [GENERAL_LOG] con:84608 user:xxx@1.2.3.4 schema_ver:39423 txn_start_ts:0 sql:rollback
2019/01/14 16:57:42.888 session.go:1460: [info] [GENERAL_LOG] con:84608 user:xxx@1.2.3.4 schema_ver:39423 txn_start_ts:0 sql:SET autocommit=1

2. What did you expect to see?
rollback the transaction.

3. What did you see instead?
the trasaction can't rollback completely

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.0

**Comment by shenli** [comment]
@zhuboshuai Thanks for your feedback!
@jackysp PTAL

**Comment by tiancaiamao** [comment]
This is a fixed bug on master ... 

```
set autocommit = 0;
execute xxx using xxx // bug: execute prepared statement commit the transaction directly!
```

Please try the TiDB release 2.1.3 @zhuboshuai
