### ISSUE TITLE
Syncer doesn't honor syscall.SIGTERM when retrying errors

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#9131]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Syncing data from mysql to proxysql+TiDB, with create table DDL.

2. What did you expect to see?

Syncer should exit gracefully when received signal SIGTERM

3. What did you see instead?

It's known issue ( https://github.com/pingcap/tidb/issues/8784 ) that create table DDL would fail in the scenario,  I hope syncer exit immediately after received SIGTERM signal. However syncer still retrying the error every 3s, until the 100th retry, that's 5 minutes later after received  SIGTERM signal

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.0.4 but it's not interested.

I tried KILL signal, syncer exited immediately from the same scenario.

**Comment by tiancaiamao** [comment]
@GregoryIan

**Comment by CrazyNash** [comment]
any update?

**Comment by WangXiangUSTC** [comment]
I will check it @CrazyNash

**Comment by WangXiangUSTC** [comment]
@CrazyNash it is fixed in latest version, you can download from download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz

**Comment by CrazyNash** [comment]
@WangXiangUSTC thanks
