### ISSUE TITLE
Syncer keeps position in target DB like loader

### ISSUE THREAD

**Issue by CrazyNash** [pingcap/tidb#9132]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Syncer can't ensure data consistency ( I mean Syncer can't flush latest binlog position to syncer.meta before exit) in many scenarios, like when getting KILL signal.

**Describe the feature you'd like:**

The problem here is the position info is kept in a local file, the file couldn't be updated in some scenarios,  if the position meta info could be kept in target DB, just like loader, than the position info would always be consistent, we can restart syncer with the consistent position info anytime. 

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by scsldb** [comment]
Writing to the target database also has problems such as write failure and untimely write, if real-time write cost is relatively high.

**Comment by IANTHEREAL** [comment]
dm do it
