### ISSUE TITLE
when there is a create table ddl sql, syncer will Fall into a Infinite loop

### ISSUE THREAD

**Issue by introspection3** [pingcap/tidb#9145]
when there is a create table ddl sql, syncer will Fall into a Infinite loop

**Comment by shenli** [comment]
@564064202 Please keep the issue template and fill it. We need more detailed info to track the issue.
Thanks!

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
