### ISSUE TITLE
create table with sql ,there is a bug

### ISSUE THREAD

**Issue by 564064202** [pingcap/tidb#9148]
[SQL]CREATE TABLE IF NOT EXISTS `AA` (
  `PrimaryKey` bigint(20) NOT NULL AUTO_INCREMENT,
  `Mac` varchar(50) CHARACTER SET utf8 NOT NULL,
  `StartDateTimeTicks` bigint(20) NOT NULL,
  `IsMerged` tinyint(1) NOT NULL,
  `MvcUserId` int(11) NOT NULL,
  `Marked` tinyint(1) NOT NULL,
  `NodeName` varchar(200) CHARACTER SET utf8 DEFAULT NULL,
  `Id` varchar(36) CHARACTER SET utf8 NOT NULL,
  `FirstRequestId` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `IsFirstRequest` tinyint(1) NOT NULL,
  `ParentId` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `Host` varchar(200) CHARACTER SET utf8 NOT NULL,
  `HostIp` varchar(200) CHARACTER SET utf8 NOT NULL,
  `RunningIntantanceName` varchar(200) CHARACTER SET utf8 NOT NULL,
  `ProjectType` int(11) NOT NULL,
  `Location` varchar(200) CHARACTER SET utf8 NOT NULL,
  `StartDateTime` datetime NOT NULL,
  `EndDateTime` datetime NOT NULL,
  `UsedTime` double NOT NULL,
  `IsEnd` tinyint(1) NOT NULL,
  `IsSuccess` tinyint(1) NOT NULL,
  `RequestMethodType` varchar(50) CHARACTER SET utf8 NOT NULL,
  `ClientRealIp` varchar(100) CHARACTER SET utf8 DEFAULT NULL,
  `Parameters` longtext CHARACTER SET utf8 DEFAULT NULL,
  `Headers` longtext CHARACTER SET utf8 DEFAULT NULL,
  PRIMARY KEY (`PrimaryKey`),
  UNIQUE KEY `AA_Id_Unique_Index` (`Id`) USING HASH,
  KEY `AA_Location_Index` (`Location`) USING HASH,
  KEY `AA_UsedTime_Index` (`UsedTime`) USING HASH,
  KEY `AA_NodeName_Index` (`NodeName`) USING HASH,
  KEY `AA_FirstRequestId_Index` (`FirstRequestId`) USING HASH,
  KEY `AA_BUG_Index` (`Location`,`NodeName`,`StartDateTime`) USING HASH
)   DEFAULT CHARSET=utf8;
受影响的行: 0
时间: 0.009s

[Err] 1055 - Expression #1 of ORDER BY is not in GROUP BY clause and contains nonaggregated column '' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by

**Comment by rla** [comment]
That error does not seem to be related to the table definition. It likely comes from a query that uses a `GROUP BY` expression. Usually it raises when you select non-aggregate columns that are not itself in the `GROUP BY` expression.

**Comment by 564064202** [comment]
but there is no "group  by"

**Comment by tiancaiamao** [comment]
Could you provide more details about the error in the tidb log?
@564064202

**Comment by wjhuang2016** [comment]
Close because this issue is no longer active, reopen it after we receive the reply from @564064202 .
