### ISSUE TITLE
MySQL 8.0: Make server respond 8.0.11 instead of 5.7.10

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9158]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The version specified in `parser/mysql/const.go` is currently `5.7.10-TiDB`.

**Describe the feature you'd like:**

Change the version to `8.0.11-TiDB`.

**Describe alternatives you've considered:**

This should not require a compatibility mode.

**Teachability, Documentation, Adoption, Migration Strategy:**
Improves MySQL 8.0 compatibility, makes TiDB easier to explain.

**Comment by Defined2014** [comment]
Already done it, close this issue.
