### ISSUE TITLE
Does select for update really lock the record selected?

### ISSUE THREAD

**Issue by lunny** [pingcap/tidb#9162]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
I'm writing tests for tidb on xorm, see the PR https://github.com/go-xorm/xorm/pull/1207

2. What did you expect to see?

mysql could PASS all the tests, expect tidb will do.

3. What did you see instead?

tidb failed on select for update tests.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

docker pingcap/tidb:v2.1.2

**Comment by lunny** [comment]
Maybe https://github.com/pingcap/tidb/issues/8894 explained that?

**Comment by lamxTyler** [comment]
@lunny Yes, you are right.

**Comment by shenli** [comment]
@lunny Please refer to the [document](https://pingcap.com/docs/FAQ/#does-tidb-support-select-for-update).

**Comment by lunny** [comment]
@lamxTyler @shenli thanks!
