### ISSUE TITLE
new column not found which added after truncate

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb#9164]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
-  truncate table
-  add new column
-  insert into table

error:new column not found

tidb log:
```
{"log":"{\"file\":\"session.go\",\"level\":\"warning\",\"line\":488,\"msg\":\"[con:86] Retry:0 query:0 insert into **** (resource_id,product_name,product_status,ures_status,ubill_status,product_property,ures_property,ubill_property,result_desc,row_create_time,row_update_time,biz_status,res_status,bill_status) values (?,?,?,?,?,?,?,?,?,NOW(),NOW(),?,?,?) ON DUPLICATE KEY UPDATE product_name=?,product_status=?,ures_status=?,ubill_status=?,product_property=?,ures_property=?,ubill_property=?,result_desc=?,row_update_time=NOW(),biz_status=?,res_status=?,bill_status=? \",\"time\":\"2019/01/23 19:13:06.919\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.919587276Z"}
{"log":"{\"file\":\"session.go\",\"level\":\"warning\",\"line\":340,\"msg\":\"[con:29] retryable error: [try again later]: tikv restarts txn: Txn(Mvcc(WriteConflict { start_ts: 405862347362795669, conflict_ts: 405862347362795899, key: [116, 128, 0, 0, 0, 0, 0, 0, 255, 230, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 1, 53, 49, 97, 99, 255, 49, 101, 48, 52, 255, 45, 52, 54, 255, 102, 101, 45, 52, 55, 255, 50, 56, 255, 45, 56, 100, 100, 102, 45, 255, 100, 255, 57, 98, 102, 97, 53, 99, 48, 255, 255, 100, 100, 101, 52, 0, 0, 0, 0, 255, 251, 0, 0, 0, 0, 0, 0, 0, 248], primary: [116, 128, 0, 0, 0, 0, 0, 0, 230, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 1, 53, 49, 97, 99, 49, 101, 48, 52, 255, 45, 52, 54, 102, 101, 45, 52, 55, 255, 50, 56, 45, 56, 100, 100, 102, 45, 255, 100, 57, 98, 102, 97, 53, 99, 48, 255, 100, 100, 101, 52, 0, 0, 0, 0, 251] })), txn: {\\u003cnil\\u003e \\u003cnil\\u003e 0xc422d64120 map[] [] \\u003cnil\\u003e}\",\"time\":\"2019/01/23 19:13:06.920\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.92076096Z"}
{"log":"{\"file\":\"session.go\",\"level\":\"warning\",\"line\":488,\"msg\":\"[con:29] Retry:0 query:0 insert into **** (resource_id,product_name,product_status,ures_status,ubill_status,product_property,ures_property,ubill_property,result_desc,row_create_time,row_update_time,biz_status,res_status,bill_status) values (?,?,?,?,?,?,?,?,?,NOW(),NOW(),?,?,?) ON DUPLICATE KEY UPDATE product_name=?,product_status=?,ures_status=?,ubill_status=?,product_property=?,ures_property=?,ubill_property=?,result_desc=?,row_update_time=NOW(),biz_status=?,res_status=?,bill_status=? \",\"time\":\"2019/01/23 19:13:06.920\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.920808312Z"}
{"log":"{\"file\":\"2pc.go\",\"level\":\"info\",\"line\":570,\"msg\":\"[con:59] 2PC clean up done, tid: 405862347362795553\",\"time\":\"2019/01/23 19:13:06.920\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.920955632Z"}
{"log":"{\"file\":\"2pc.go\",\"level\":\"info\",\"line\":570,\"msg\":\"[con:10] 2PC clean up done, tid: 405862347362795962\",\"time\":\"2019/01/23 19:13:06.923\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.92345761Z"}
{"log":"{\"file\":\"2pc.go\",\"level\":\"info\",\"line\":570,\"msg\":\"[con:86] 2PC clean up done, tid: 405862347362795726\",\"time\":\"2019/01/23 19:13:06.923\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.923490513Z"}
{"log":"{\"file\":\"session.go\",\"level\":\"warning\",\"line\":340,\"msg\":\"[con:126] retryable error: [try again later]: tikv restarts txn: Txn(Mvcc(WriteConflict { start_ts: 405862347362796047, conflict_ts: 405862347362796120, key: [116, 128, 0, 0, 0, 0, 0, 0, 255, 230, 95, 105, 128, 0, 0, 0, 0, 255, 0, 0, 1, 1, 55, 99, 54, 54, 255, 55, 99, 48, 52, 255, 45, 53, 100, 255, 51, 57, 45, 52, 52, 255, 52, 53, 255, 45, 57, 52, 51, 99, 45, 255, 48, 255, 101, 99, 102, 55, 98, 51, 57, 255, 255, 54, 51, 57, 101, 0, 0, 0, 0, 255, 251, 0, 0, 0, 0, 0, 0, 0, 248], primary: [116, 128, 0, 0, 0, 0, 0, 0, 230, 95, 105, 128, 0, 0, 0, 0, 0, 0, 1, 1, 55, 99, 54, 54, 55, 99, 48, 52, 255, 45, 53, 100, 51, 57, 45, 52, 52, 255, 52, 53, 45, 57, 52, 51, 99, 45, 255, 48, 101, 99, 102, 55, 98, 51, 57, 255, 54, 51, 57, 101, 0, 0, 0, 0, 251] })), txn: {\\u003cnil\\u003e \\u003cnil\\u003e 0xc422faebe0 map[] [] \\u003cnil\\u003e}\",\"time\":\"2019/01/23 19:13:06.923\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.923687399Z"}
{"log":"{\"file\":\"session.go\",\"level\":\"warning\",\"line\":488,\"msg\":\"[con:126] Retry:0 query:0 insert into **** (resource_id,product_name,product_status,ures_status,ubill_status,product_property,ures_property,ubill_property,result_desc,row_create_time,row_update_time,biz_status,res_status,bill_status) values (?,?,?,?,?,?,?,?,?,NOW(),NOW(),?,?,?) ON DUPLICATE KEY UPDATE product_name=?,product_status=?,ures_status=?,ubill_status=?,product_property=?,ures_property=?,ubill_property=?,result_desc=?,row_update_time=NOW(),biz_status=?,res_status=?,bill_status=? \",\"time\":\"2019/01/23 19:13:06.923\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.923779169Z"}
{"log":"{\"file\":\"2pc.go\",\"level\":\"info\",\"line\":570,\"msg\":\"[con:29] 2PC clean up done, tid: 405862347362795669\",\"time\":\"2019/01/23 19:13:06.924\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.925014705Z"}
{"log":"{\"file\":\"2pc.go\",\"level\":\"info\",\"line\":570,\"msg\":\"[con:126] 2PC clean up done, tid: 405862347362796047\",\"time\":\"2019/01/23 19:13:06.927\"}\n","stream":"stderr","time":"2019-01-23T11:13:06.9275659Z"}
```

2. What did you expect to see?
insert success

3. What did you see instead?
new column not found 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
tidb: "v2.0.4"
tikv: "v2.0.4"

**Comment by XSHui** [comment]
@tiancaiamao

**Comment by lamxTyler** [comment]
@XSHui Thanks for your feedback. From the log, I can only tell that tidb is retry the sql due to write conflicts. Why do you say the new column is not found? Can you provide more logs?

**Comment by XSHui** [comment]
we use desc to check, sometimes we can get the new column @lamxTyler

**Comment by lamxTyler** [comment]
@XSHui So do you mean after the new column is added, when using `desc table`, sometimes you can get the column, while sometimes cannot?

**Comment by XSHui** [comment]
是的
我们先对一张表做truncate操作， 然后增加几列，接着插入数据，报错新增的列不存在。
desc 查看有时候结果中有新增的列，有时候没有。

**Comment by tiancaiamao** [comment]
Three tidb instances under a proxy? @XSHui 
Would you please login each tidb instances and check the `desc` result ?
And is there a network partition between tidb and pd, or between tidb and tikv?

**Comment by XSHui** [comment]
1. Three tidb instances under two proxys

2. all tidb , pd , tikv in the same network partition
@tiancaiamao

**Comment by tiancaiamao** [comment]
The TiDB log shows transaction conflict:

```
tikv restarts txn: Txn(Mvcc(WriteConflict { start_ts: 405862347362796047, 
```

It should have nothing to do with the problem you described:

```
error:new column not found
```

A possible condition for this is that through proxy, you first request is sent to a TiDB (DDL owner), while the second request is sent to another TiDB(DDL worker) and the third is to the original one (DDL owner) again.

Schema change may not finish simultaneously in different TiDB (depends on the time a TiDB instance load the latest database schema), so if the proxy switch between the TiDB instance, it's possible to see different schema.

If you can further provide the accurate error log of TiDB, @zimulala may help debugging it. @XSHui

**Comment by XSHui** [comment]
In this case:
- How long does it usually take to complete the synchronization? 
- And how about the worst case ? 
- Is there any parameter we can regulation it ?
@tiancaiamao @zimulala

**Comment by tiancaiamao** [comment]
1. How long does it usually take to complete the synchronization?

So I asked 
> is there a network partition between tidb and pd, or between tidb and tikv?

If the network is OK, you should seldom see this problem.

2. And how about the worst case ?

Nothing wrong.

DDL is a **non-block operation** using online schema change, it means that **one user may change the schame (maybe add a column) and you never know it**. You will not be blocked waiting for that DDL operation to finish during the schema change.

The table column change from (a b c) to (a b c d), and you're still insert using (1 2 3), so the server deny that request.

You could just retry the request if you know the cause of the problem is that someone add a column.

3. Is there any parameter we can regulation it ?

You can tell the proxy not to change TiDB instance, unless the connection is closed.
And you can specify the columns to make your SQL more robust to this kind of change:
```
select (a b c) from t  // add column d doesn't affect a/b/c
select * from t
```

**Comment by zimulala** [comment]
@XSHui 
In your case, as follows:
> truncate table
add column
insert data (get error response)
desc table

Does the statement that adds the column return the result normally when you do `insert data` or `desc table`？

**Comment by nullnotnil** [comment]
I am going to close this issue as stale, but please feel free to re-open it with additional details.

Thanks!
