### ISSUE TITLE
enum + insert on duplicate update > data truncate

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb#9165]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
CREATE TABLE `table1` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `f2` enum('cluster','default','common') DEFAULT 'common',
  `f3` varchar(1000) DEFAULT NULL,
  `f4` varchar(255) DEFAULT NULL COMMENT 'group by f3',
  `f5` int(11) DEFAULT NULL ,
  `f6` int(11) DEFAULT NULL ,
  `f7` int(11) DEFAULT '100' ,
  `f8` int(11) DEFAULT NULL,
  `f9` int(11) DEFAULT NULL,
  `f10` varchar(50) DEFAULT NULL,
  `f11` varchar(200) DEFAULT NULL,
  `f12` varchar(500) DEFAULT 'email,hotchat,message' ,
  `f13` int(11) DEFAULT '1',
  `f14` datetime DEFAULT NULL,
  `f15` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

sql xxx:
insert into `test`.`table1`(`f2` , `f3` , `f4` , `f5` , `f6` , `f7` , `f8` , `f9` , `f10` , `f11` , `f12` , `f13` , `f14` , `f15` , `id`) values (1 , '{"group":"hubble","metric":"cpu.load.5min.per.core,agent.alive,proc.used.monitor"}' , '' , 10 , 2 , 1 , 3 , 1 , 'weiwei' , 'weiwei' , 'email,message,hotchat' , 1 , NULL , '2019-01-23 15:36:25' , 34) on duplicate key update `f2`=values(`f2`) , `f3`=values(`f3`) , `f4`=values(`f4`) , `f5`=values(`f5`) , `f6`=values(`f6`) , `f7`=values(`f7`) , `f8`=values(`f8`) , `f9`=values(`f9`) , `f10`=values(`f10`) , `f11`=values(`f11`) , `f12`=values(`f12`) , `f13`=values(`f13`) , `f14`=values(`f14`) , `f15`=values(`f15`) , `id`=values(`id`);

its OK

replace sql xxx the value of type to 2 ,execute sql xxx again.

its wrong

2. What did you expect to see?
select * from table1;
the value of type is default

3. What did you see instead?
he value of type is cluster

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.0, just specific tidb cluster can recur.
if remove the field f2, the error dissapear.
show warnings :  Data Truncated

**Comment by zz-jason** [comment]
It's not the same reason with #8934 

1. For #8934, it's because the builtin function `Values()` hasn't correctly handled the `float` input value.
2. For this issue, it's because the builtin function `Values()` hasn't correctly handled the `enum` input value.
