### ISSUE TITLE
can't access after rolling update 

### ISSUE THREAD

**Issue by zhuboshuai** [pingcap/tidb#9177]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
update a cluster from v2.0.0.rc6 to v2.0.1, it's OK after udapte.
update the same culster from v2.0.1 to v2.1.2 , it's not OK ater update.
all the acesses fails. the log show below:
[error] User connection verification failed xxx@192.168.0.1
the reason is mysql.host table add a line, the password is empty:  
host user password
%     xxx   
the special point is the update is executed twice continuously.

2. What did you expect to see?
the tidb database can be accessed normally after update. 

3. What did you see instead?
the tidb database can't be accessed  after update. 

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
v2.1.2

**Comment by lamxTyler** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
```
the reason is mysql.host table add a line, the password is empty:
host user password
```

There is no mysql.host table. @zhuboshuai 

You can modify the config file add this:

```
[security]
skip-grant-table = true
```

Restart the tidb using the modified config file, then try to login again.

I'll verify the upgrading progress from v2.0.1 to v2.1.2

**Comment by tiancaiamao** [comment]
I tested with mocktikv just now, upgrading TiDB from v2.0.1 to v2.1.2, and it works well.
Is there any error log in your TiDB cluster, especially protocol error between TiDB and TiKV ?
@zhuboshuai

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
