### ISSUE TITLE
panic while adding a new tikv instance

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9196]
windows机器，机械硬盘，开始三台机器，3个pd,3个tikv,3个tidb(nginx loadbalance), 然后mysql导入了一个数据库备份，各种操作，无异常， 但动态加入一台机器增加一个tikv节点时稳定报这个错误：

2019/01/28 01:29:38.515 ERRO mod.rs:490: thread 'region-collector-worker' panicked 'assertion failed: `(left != right)` (left: `0`, right: `0`)' at "src/raftstore/coprocessor/region_info_accessor.rs:324"
stack backtrace:
   0:     0x563e74fb930c - backtrace::backtrace::libunwind::trace::he68352cf614e381d
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/libunwind.rs:54
                         - backtrace::backtrace::trace::h1cbb7437af9419f9
                        at /home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.2.3/src/backtrace/mod.rs:70
   1:     0x563e749ac724 - tikv::util::set_panic_hook::{{closure}}::hd972e99d3e076394
                        at /home/jenkins/workspace/build_tikv_master/go/src/github.com/tikv/tikv/target/release/build/backtrace-268b6593d69dacc9/out/capture.rs:79
   2:     0x563e750b015f - std::panicking::rust_panic_with_hook::h60a37fb79e459606
                        at libstd/panicking.rs:479
   3:     0x563e750affbe - std::panicking::continue_panic_fmt::hb542a58a3d52cb5c
                        at libstd/panicking.rs:390
   4:     0x563e750aff62 - std::panicking::begin_panic_fmt::ha198d387c12d5535
                        at libstd/panicking.rs:345
   5:     0x563e74b8836c - tikv::raftstore::coprocessor::region_info_accessor::RegionCollector::check_region_range::haac95071fa6d3665
                        at src/raftstore/coprocessor/region_info_accessor.rs:324
                         - tikv::raftstore::coprocessor::region_info_accessor::RegionCollector::handle_raftstore_event::h7b69ca1b04d01e9f
                        at src/raftstore/coprocessor/region_info_accessor.rs:380
                         - <tikv::raftstore::coprocessor::region_info_accessor::RegionCollector as tikv::util::worker::Runnable<tikv::raftstore::coprocessor::region_info_accessor::RegionCollectorMsg>>::run::hff967e45ac811ffb
                        at src/raftstore/coprocessor/region_info_accessor.rs:407
                         - tikv::util::worker::Runnable::run_batch::h522afbf2f18f95ca
                        at src/util/worker/mod.rs:98
                         - <tikv::util::worker::DefaultRunnerWithTimer<R> as tikv::util::worker::Runnable<T>>::run_batch::h3975c09c93161bf2
                        at src/util/worker/mod.rs:118
                         - tikv::util::worker::poll::h30a61f281d275f09
                        at src/util/worker/mod.rs:276
                         - <tikv::util::worker::Worker<T>>::start_with_timer::{{closure}}::h1e11d464d4c38672
                        at src/util/worker/mod.rs:354
                         - std::sys_common::backtrace::__rust_begin_short_backtrace::hb1865405e67e00bf
                        at /checkout/src/libstd/sys_common/backtrace.rs:136
   6:     0x563e74b8294a - std::thread::Builder::spawn::{{closure}}::{{closure}}::hb7676c75daa45b37
                        at /checkout/src/libstd/thread/mod.rs:409
                         - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hbc141d8c6fb2ec57
                        at /checkout/src/libstd/panic.rs:313
                         - std::panicking::try::do_call::he2afe0d38dd7eae7
                        at /checkout/src/libstd/panicking.rs:310
                         - std::panicking::try::h325dd45569e9aad1
                        at /checkout/src/libpanic_unwind/lib.rs:106
                         - std::panic::catch_unwind::ha2261cd7e952bb0a
                        at /checkout/src/libstd/panic.rs:392
                         - std::thread::Builder::spawn::{{closure}}::h1d7b590a57746231
                        at /checkout/src/libstd/thread/mod.rs:408
                         - <F as alloc::boxed::FnBox<A>>::call_box::ha88df66a7a8a7a1a
                        at /checkout/src/liballoc/boxed.rs:640
   7:     0x563e7509dff3 - std::sys::unix::thread::Thread::new::thread_start::h96884314b12ba24c
                        at /checkout/src/liballoc/boxed.rs:650
   8:     0x7fbe72b73d2b - <unknown>
   9:     0x7fbe72287e3e - __clone
  10:                0x0 - <unknown>
2019/01/28 01:29:38.515 INFO mod.rs:504: logger switched, outputs further logs to stderr

启动脚本为：
docker run -d --name tikv4 ^
  -p 20160:20160 ^
  --ulimit nofile=1000000:1000000 ^
  pingcap/tikv:latest ^
  --addr="0.0.0.0:20160" ^
  --advertise-addr="192.168.9.227:20160" ^
  --data-dir="/data/tikv4" ^
  --pd="192.168.9.119:2379,192.168.9.59:2379,192.168.9.107:2379"

**Comment by lamxTyler** [comment]
Thanks for your feedback. PTAL @overvenus

**Comment by overvenus** [comment]
Hi @ericisme What's your TiKV version?

**Comment by siddontang** [comment]
@overvenus 

Refer to https://github.com/tikv/rfcs/blob/master/text/2018-12-19-unified-log-format.md, seem should be "DEBUG".

**Comment by ericisme** [comment]
@overvenus  
"store": {
        "id": 6,
        "address": "192.168.9.107:20160",
        "version": "3.0.0-alpha",
        "state_name": "Up"
      },

**Comment by MyonKeminta** [comment]
Could you please also provide the commit hash of the TiKV that you tried to add to thre cluster? You can find it in the beginning of its log or by running `./tikv-server -V`.

**Comment by ericisme** [comment]
@MyonKeminta 

docker exec -it tikv2 ./tikv-server -V
TiKV
Release Version:   3.0.0-alpha
Git Commit Hash:   979e1f791775d6a64c49add1bca66014e0a6f95b
Git Commit Branch: master
UTC Build Time:    2019-01-07 11:51:30
Rust Version:      rustc 1.29.0-nightly (4f3c7a472 2018-07-17)

**Comment by MyonKeminta** [comment]
@ericisme It seems that's a bug that has been fixed in TiKV's commit dd322faad9877cce8ea84a110766c6b83ca58ee9 . Could you please try a version after that commit in master branch?

**Comment by ericisme** [comment]
@MyonKeminta
thank you very much, the bug was disappeared after i update the pingcap/tikv docker images to tag->latest.

**Comment by MyonKeminta** [comment]
You are welcome
