### ISSUE TITLE
The expression in the added generated column is not processed when the boundary value is exceeded

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#9213]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(
  y year NOT NULL DEFAULT '2155'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin;
insert into t values();
ALTER TABLE t ADD COLUMN y1 year as (y + 2);
select * from t;
```

2. What did you expect to see?
<img width="556" alt="screen shot 2019-01-29 at 18 51 28" src="https://user-images.githubusercontent.com/4242506/51908813-c2042a00-2405-11e9-8748-14d7b6c3d6bd.png">

3. What did you see instead?
<img width="538" alt="screen shot 2019-01-29 at 18 51 51" src="https://user-images.githubusercontent.com/4242506/51908877-ecee7e00-2405-11e9-8ac4-06f19c883d1c.png">

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.0-beta-18-g7648317da
Git Commit Hash: 7648317dad4fe4b076158339fd205dfa76b0d5ea
Git Branch: master

**Comment by LittleFall** [comment]
This issue has been fixed in [pr/12407](https://github.com/pingcap/tidb/pull/12407) after refactoring reading logic of virtual generate column.

```sql
Release Version: v4.0.0-beta.2-221-g15e961ad3

select * from t;
+------+------+
| y    | y1   |
+------+------+
| 2155 | 0000 |
+------+------+
```
