### ISSUE TITLE
About TIDB-Lighting question

### ISSUE THREAD

**Issue by longhuguoji** [pingcap/tidb#9220]
1、请问TiDB-lightning支持mysql的分表分库合并导入TIDB吗，tidb-loader是支持的。
2、如果支持，能否说一下如何配置分表分库导入，或者有没有说明的地址，我先尝试一下。

**Comment by longhuguoji** [comment]
@july2993 请问TiDB-lightning读取mysql从库时，是否会增加全局读锁？影响mysql从库和主库的同步。

**Comment by july2993** [comment]
> @july2993 请问TiDB-lightning读取mysql从库时，是否会增加全局读锁？影响mysql从库和主库的同步。


mydumper will use  `flush tables with read lock`. Lightning will not read MySQL directly but read the files dumped by  mydumper.
you can read the docs first before try to use it: https://pingcap.com/docs-cn/tools/lightning/overview-architecture/

**Comment by longhuguoji** [comment]
@july2993 请问mydumper和TiDB-lightning可以同时开启吗？还是mydumper执行完之后，再开启TiDB-lightning？

**Comment by jebter** [comment]
You can ask new questions at https://asktug.com/. I will close this issue. If there are any updates, you can reopen it.
