### ISSUE TITLE
tidb start Shared connection to 192.168.130.81 closed

### ISSUE THREAD

**Issue by wlj030341** [pingcap/tidb#9221]
fatal: [192.168.130.81]: FAILED! => {"changed": false, "module_stderr": "Shared connection to 192.168.130.81 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_H0a1Bw/ansible_module_wait_for.py\", line 579, in <module>\r\n    main()\r\n  File \"/tmp/ansible_H0a1Bw/ansible_module_wait_for.py\", line 519, in main\r\n    response = s.recv(1024)\r\nsocket.error: [Errno 104] Connection reset by peer\r\n", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/tidb/tidb-ansible/retry_files/start.retry

**Comment by lamxTyler** [comment]
Thanks for your feedback. PTAL @liubo0127

**Comment by liubo0127** [comment]
Please give more detailed error information and log information of the corresponding service.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
