### ISSUE TITLE
when using tidb as embedded db in go, how can i use mysql client to visit the db

### ISSUE THREAD

**Issue by defia** [pingcap/tidb#924]

**Comment by shenli** [comment]
@defia You can use go sql driver to access TiDB. 
See: https://github.com/pingcap/tidb/blob/master/docs/USAGE.md

**Comment by defia** [comment]
@shenli what i mean , if I can use tidb as embedded db in go, and use mysql client to visit the db to check the db at the same time

我的意思是在嵌入式使用的同时,能够通过客户端访问数据库 以查看数据.

**Comment by shenli** [comment]
This is impossible. Why not use tidb-server? You can access it by multiple clients.
