### ISSUE TITLE
StringError("[src/storage/engine/raftkv.rs:521]

### ISSUE THREAD

**Issue by cesar-blog** [pingcap/tidb#9242]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

### 1. Error msg 

`StringError("[src/storage/engine/raftkv.rs:521]: key t\\200\\000\\000\\000\\000\\000\\001\\377o_r\\200\\000\\000\\000\\000\\377\\001\\325\\302\\000\\000\\000\\000\\000\\372 is not in region key range [t\\200\\000\\000\\000\\000\\000\\001\\377o\\000\\000\\000\\000\\000\\000\\000\\370, t\\200\\000\\000\\000\\000\\000\\001\\377o_r\\200\\000\\000\\000\\000\\377\\000\\335\\375\\000\\000\\000\\000\\000\\372) for region 18117"))))`

### 2. Tidb version

`
Release Version: v2.1.0-rc.1-46-gf270b10
Git Commit Hash: f270b105c90973761208bf9a2e79a2ac8ed7ec71
Git Branch: master
UTC Build Time: 2018-09-03 02:57:06
GoVersion: go version go1.11 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false`

### 3. Sql

`SELECT * FROM gov_organization WHERE es_name = 'l_53bc8f43-98f9-4c0f-a4ed-e88f323cc1aa_b41c03bc-8b31-4517-94dd-ee627084764c';`

### 4. Sql execution plan

![2](https://user-images.githubusercontent.com/17369383/52160955-24587580-26f9-11e9-8cdc-57fa0a088c10.png)

### 5. Table Structure

![1](https://user-images.githubusercontent.com/17369383/52160953-1571c300-26f9-11e9-99e4-fcff327c9345.png)

### 6. Tidb log

[tidb.txt](https://github.com/pingcap/tidb/files/2824137/tidb.txt)

### 7. Tikv log

[tikv.txt](https://github.com/pingcap/tidb/files/2824138/tikv.txt)

-----------------------------------------------------------------------------

**Comment by winoros** [comment]
@cesar-blog Please provide the `show create table` result. The table structure you provided is not very useful.

**Comment by nullnotnil** [comment]
@cesar-blog I am going to close this issue as stale, but please feel free to re-open it (specifying additional details requested). Thank you!
