### ISSUE TITLE
Full Vectorized Expression Evaluation

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#9245]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The current expression evaluation interface are row-oriented, not efficient. To evaluate a batch of inputs, 1024 rows for example, 1024 function calls are invoked.

**Describe the feature you'd like:**

Expand the expression evaluation interface to add a column-oriented method, evaluate the builtin functions column by column. 

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by SunRunAway** [comment]
@qw4990 Could this issue be closed now?

**Comment by qw4990** [comment]
Close due to finished https://github.com/pingcap/tidb/issues/12058.
