### ISSUE TITLE
Dependency-free single binary

### ISSUE THREAD

**Issue by ivanjaros** [pingcap/tidb#9257]
Hi,
would it be possible to release a version that would be dependency-free(tikv, pd...) single binary, like cockroach db?

**Comment by morgo** [comment]
I am currently working on it :-)

Technical details:
It is possible to run the `tidb-server` with the `mocktikv` storage engine, and no `pd` or `tikv`.  Mocktikv is based on goleveldb, which is much slower than TiKV (5x in my tests), but it is useful for development environments to test TiDB compatibility.  For production, it will always be recommended to use TiKV.

May I ask which platform you are interested in?

**Comment by ivanjaros** [comment]
That's good news.
Why goleveldb and not badger though? Doesn't that require cgo?

**Comment by morgo** [comment]
Badger support may be added in the future.

Goleveldb is a port to Go, and doesn't require cgo.  The test-suite currently uses TiDB without tikv or pd,  so most of the work is already done.  It still requires packaging and misc bug fixes such as https://github.com/pingcap/tidb/pull/8836 and https://github.com/pingcap/tidb/pull/8886
