### ISSUE TITLE
mattermost compatibility requires support for FULLTEXT indexes

### ISSUE THREAD

**Issue by sokoow** [pingcap/tidb#9259]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
Tried to launch mattermost 5.7.1

2. What did you expect to see?
Working product

3. What did you see instead?
This:

```$ ./mattermost
{"level":"info","ts":1549780891.3968744,"caller":"utils/i18n.go:78","msg":"Loaded system translations for 'en' from '/home/mattermost/i18n/en.json'"}
{"level":"info","ts":1549780891.3970153,"caller":"app/app.go:143","msg":"Server is initializing..."}
{"level":"info","ts":1549780891.4000347,"caller":"sqlstore/supplier.go:207","msg":"Pinging SQL master database"}
{"level":"info","ts":1549780904.62149,"caller":"sqlstore/upgrade.go:105","msg":"The database schema has been set to version 5.7.0"}
{"level":"error","ts":1549780917.1679149,"caller":"sqlstore/supplier.go:749","msg":"Failed to create index Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 17 near \"FULLTEXT  INDEX idx_channel_search_txt ON Channels (Name, DisplayName, Purpose)\" "}
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
latest

**Comment by lamxTyler** [comment]
> line 1 column 17 near \"FULLTEXT  INDEX idx_channel_search_txt ON Channels (Name, DisplayName, Purpose)

@sokoow Thanks for your feedback! TiDB does not support full text yet. Ref https://github.com/pingcap/tidb/issues/1793

**Comment by sokoow** [comment]
Any timeline when this will be implemented and how ?

**Comment by lamxTyler** [comment]
Currently, there is no such plan.

**Comment by morgo** [comment]
I am going to close this issue to reduce duplication with https://github.com/pingcap/tidb/issues/1793

Please feel free to re-open it if you have any further questions.  Thank you!
