### ISSUE TITLE
Distributed backup ?

### ISSUE THREAD

**Issue by ddorian** [pingcap/tidb#9262]
Hi,

So TiDB is for big data. Say 10 servers with 2TB each (multi core, nvme etc). 
How do you do a distributed backup/restore ? Looking at the docs it's not available.

Am I missing something ? 
Do you expect to do a single-machine-backup on 50 machines ?

Regards

**Comment by morgo** [comment]
For backup, TiDB supports `mydumper` as a logical dump.  We provide documentation for it here: https://www.pingcap.com/docs/tools/mydumper/

Restore can be done via either [loader](https://www.pingcap.com/docs/tools/loader/) or [lightning](https://www.pingcap.com/docs/tools/mydumper/#).  Lightning currently restores at over 100GiB/hr.

Incremental backup is also possible via [TiDB Binlog](https://www.pingcap.com/docs/tools/tidb-binlog-cluster/).  Physical backup is also on our roadmap.

Please let me know if you have any further questions.  Thanks!

**Comment by ddorian** [comment]
Still even lighting/load/mydmpuer look to be single-server, correct ?

**Comment by morgo** [comment]
Yes, they will require data to be on a single server.  Support for streaming to object storage is planned.
