### ISSUE TITLE
PD server timeout[try again later] when using mysql command to import data.

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9263]
command:

mysql.exe --protocol=tcp --host=192.168.9.119 --user=root --port=4000 --default-character-set=utf8 --database=erp_20190125  < "E:\\20190125.sql\\data\\dbdata\\mysqlbak\\erp\\20190125.sql"

error:

ERROR 9001 (HY000) at line 7384: PD server timeout[try again later]

that is second times i meet this error, i want to know what it is going on, and how to prevent this problem, thanks

**Comment by lysu** [comment]
@ericisme Thanks for the feedback.

This error occurred when TiDB gets info from PD but failure even after some retries. Could you post the TiDB & PD log during that time?  Thanks

**Comment by ericisme** [comment]
@lysu sorry, the mysql command did not print the time when it error, the task run serveral hours , i don't know when it cash....

**Comment by lysu** [comment]
Hi @ericisme maybe we can `grep` 'PD server timeout' in tidb log to find time, then take more look at tidb/tikv log at that time

**Comment by ericisme** [comment]
@lysu, do you know how to search docker container's log?  i did not config log dir, it only printly at docker cmd, but docker -logs command has no grep function...

**Comment by lysu** [comment]
> do you know how to search docker container's log? i did not config log dir, it only printly at docker cmd, but docker -logs command has no grep function...

@tennix help needed thx~

**Comment by tennix** [comment]
If you are using docker without docker-compose, then `docker logs {container-id}` will print the container logs. And the grep command can be used after a pipe.

**Comment by jackysp** [comment]
@ericisme , I'll close this issue for no updated for a long time, feel free to reopen it.
