### ISSUE TITLE
[Question] Tools For PostgreSQL

### ISSUE THREAD

**Issue by codelipenghui** [pingcap/tidb#9277]
## Question

Is there a tool to import data to tikv from postgresql?

**Comment by eurekaka** [comment]
IIRC, there is no such tool for PG data immigration. @lonng Does tidb-lightning work for PostgreSQL? please help confirm here.

**Comment by lonng** [comment]
@codelipenghui TiDB-Lightning does not work for PostgreSQL so far. We will support CSV as data source after https://github.com/pingcap/tidb-lightning/pull/111 merged.

**Comment by codelipenghui** [comment]
@lonng thanks.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
