### ISSUE TITLE
TIDB upgrade failure

### ISSUE THREAD

**Issue by longhuguoji** [pingcap/tidb#9278]
TIDB现版本release-2.0(inventory.ini显示2.0.8)，升级版本release-2.1(inventory.ini显示2.1.3)。
升级过程中，有一步骤报错，如下：

TASK [wait until the TiKV port is down] **************************************************************************************************************************************************************************************************************************************
fatal: [20.4.18.41]: FAILED! => {"changed": false, "elapsed": 300, "msg": "the TiKV port 20160 is not down"}
请问，升级前是否需要手动停止所有tikv节点，还是需要怎么解决？20.4.18.41是tikv的leader_count节点。

**Comment by eurekaka** [comment]
Are you using tidb-ansible for deploying and upgrading the cluster?

**Comment by longhuguoji** [comment]
我在20.4.18.41(TIKV)节点查看日志，有如下报错信息。
2019/02/12 10:58:56.580 util.rs:431: [ERROR] failed to connect to http://20.4.18.43:2379, Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
2019/02/12 10:58:57.549 util.rs:431: [ERROR] failed to connect to http://20.4.18.43:2379, Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
2019/02/12 10:58:58.538 util.rs:431: [ERROR] failed to connect to http://20.4.18.43:2379, Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
2019/02/12 10:58:59.539 util.rs:431: [ERROR] failed to connect to http://20.4.18.43:2379, Grpc(RpcFailure(RpcStatus { status: Unavailable, details: Some("Connect Failed") }))
2019/02/12 10:59:00.700 client.rs:337: [ERROR] failed to send heartbeat: Grpc(RpcFinished(Some(RpcStatus { status: Unavailable, details: Some("Endpoint read failed") })))
2019/02/12 10:59:00.700 util.rs:264: [ERROR] request failed: Grpc(RpcFinished(Some(RpcStatus { status: Unavailable, details: Some("Endpoint read failed") })))
2019/02/12 10:59:10.066 raft_client.rs:176: [ERROR] server: drop conn with tikv endpoint 20.4.18.40:20160 flush conn error: SendError("...")
2019/02/12 10:59:26.423 scheduler.rs:1306: [ERROR] get snapshot failed for cids=[100709], error Request(message: "peer is not leader" not_leader {region_id: 490 leader {id: 492 store_id: 5}})
2019/02/12 10:59:29.184 scheduler.rs:1306: [ERROR] get snapshot failed for cids=[100749], error Request(message: "peer is not leader" not_leader {region_id: 1742 leader {id: 1744 store_id: 5}})

**Comment by longhuguoji** [comment]
@eurekaka 是的，我使用tidb-ansible-release-2.1进行升级。

**Comment by longhuguoji** [comment]
@eurekaka 请问，可以定位到问题吗？

**Comment by eurekaka** [comment]
@liubo0127 PTAL

**Comment by longhuguoji** [comment]
@eurekaka 已经解决问题，解决步骤如下：
1、找到报错的tikv节点。
2、到该节点，查看tikv进程，然后kill掉。
3、重新执行升级操作，即可成功，kill掉的tikv进程会自动拉起。
感谢！！！
