### ISSUE TITLE
compatibility: some clauses are 'order sensitive' within the CREATE TABLE statement

### ISSUE THREAD

**Issue by tshqin** [pingcap/tidb#9292]
```
create table taba(a varchar(10) default null COLLATE utf8mb4_bin);
create table tabb(a varchar(10) COLLATE utf8mb4_bin default null);
```

TiDB 2.1.3:

> MySQL [gin]> create table taba(a varchar(10) default null COLLATE utf8mb4_bin);
> ERROR 1105 (HY000): line 1 column 52 near " utf8mb4_bin)" (total length 65)
> MySQL [gin]> create table tabb(a varchar(10) COLLATE utf8mb4_bin default null);
> Query OK, 0 rows affected (0.12 sec)

MySQL 5.7.20:
> mysql> create table taba(a varchar(10) default null COLLATE utf8mb4_bin);
> Query OK, 0 rows affected (0.02 sec)
> mysql> create table tabb(a varchar(10) COLLATE utf8mb4_bin default null);
> Query OK, 0 rows affected (0.02 sec)

tidb_verson():

> Release Version: v2.1.3
> Git Commit Hash: d842dc373a4bf9e19c1a756e1409a3ad60787d01
> Git Branch: release-2.1
> UTC Build Time: 2019-01-28 06:38:45
> GoVersion: go version go1.11.2 linux/amd64
> Race Enabled: false
> TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
> Check Table Before Drop: false

**Comment by wwar** [comment]
Confirming that this is fixed:
```
tidb> SELECT tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v4.0.0-beta.2-183-g57db6cec7
Git Commit Hash: 57db6cec7ffad78e74b6ac6c67a2bfe9a6718d17
Git Branch: master
UTC Build Time: 2020-04-04 08:06:18
GoVersion: go1.13
Race Enabled: false
TiKV Min Version: v3.0.0-60965b006877ca7234adaced7890d7b029ed1306
Check Table Before Drop: false
1 row in set (0.00 sec)

tidb> create table taba(a varchar(10) default null COLLATE utf8mb4_bin);
Query OK, 0 rows affected (0.08 sec)

tidb> create table tabb(a varchar(10) COLLATE utf8mb4_bin default null);
Query OK, 0 rows affected (0.07 sec)

```

**Comment by nullnotnil** [comment]
I also double-checked, and this issue is fixed.
