### ISSUE TITLE
compare data between MySQL and TiDB

### ISSUE THREAD

**Issue by WangXiangUSTC** [pingcap/tidb#9296]
We have DM or syncer to synchronize data from MySQL to TiDB, and then we need compare data between MySQL and TiDB to ensure the data consistency.

Now we have a tools named `sync-diff-inspector` to do this.

##  sync-diff-inspector

English document：[sync-diff-inspector](https://github.com/pingcap/docs/blob/master/tools/sync-diff-inspector.md)
中文文档：[sync-diff-inspector](https://github.com/pingcap/docs-cn/blob/master/tools/sync-diff-inspector.md)

### Key features

- Compare the table schema and data
- Generate the SQL statements used to repair data if the data inconsistency exists
- Support comparing the data of multiple tables with the data of a single table (for the scenario of synchronizing data from sharded tables into the combined table)
- Support comparing the data of different schemas or tables with different names

### Principle

1. split a table to several chunks.
we have two strategy to split chunk. The first one is get some random values on a suitable column(with primary key or unique key or index) , and then use these random values to split chunk. Another one is use TiDB's  statistical information to split chunks.

2. calculate the checksum for each chunk
use sql to calculate the checksum, see details at [tidb-tools/pkg/dbutil/common.go#L343](https://github.com/pingcap/tidb-tools/blob/1e17541441200466ec9ca2f59c70e45c35bef827/pkg/dbutil/common.go#L343)

3. select the chunk's data to generate fix sql
if some chunk's checksum is different, will select data from this chunk, and then compare data row by row, find the different row and then generate fix sql write to file.

### Limitations

- don't support online check
before check data, need stop DM or syncer.
- don't support some binary type field, like bit, blob.

### Plan

- support online check
already have a solutions to do this. 
1. lock chunk in MySQL, then get the binlog position `P1`
2. calculate the checksum of this chunk in MySQL, the checksum is `c1`
2. wait DM or syncer reach the `p1`
3. calculate the checksum of this chunk in TiDB, the checksum is `c2`
4. compare `c1` and `c2`
5. unlock this chunk

- support checkpoint
save the check status in a table named `checkpoint`, can exit sync-diff-inspector and the restart it, will continue compare chunk which is not finished.

There is another tool named `pt-table-checksum`, this tool is developed by Percona.

## pt-table-checksum

document: [pt-table-checksum](https://www.percona.com/doc/percona-toolkit/LATEST/pt-table-checksum.html#cmdoption-pt-table-checksum-replicate-check-only)

### Key features

- Compare data between master and slave
- Support online check
- Can use another tool `pt-table-sync` to fix different data

### Principle

1. split a table to several chunks.
2. calculate the checksum for each chunk
a. lock this chunk in master
b. get the binlog position
c. execute a sql to calculate this chunk's checksum and write checksum to a table, the sql is similar with sync-diff-inspector's
d. when the sql above sync to slave by binlog, slave calculate it's checksum.
e. unlock this chunk in master
f. compare the checksum between master and slave

### Limitations

- requires statement-based replication
will set binlog_format to statement

- can't compare data with different schema name or table named

if we want use pt-table-checksum to compare data between MySQL and TiDB, we need modify the pt-table-checksum and DM/syncer.

- DM/syncer need support sync binlog in statement mode.

- pt-table-checksum need support set the downstream's config. now find slave in master by run `show processlist` and other sql.

- pt-table-checksum need support compare data with different schema name or table name.

- pt-table-checksum need support compare multiple table's data with one table.

- pt-table-checksum should use another way to wait slave's sync position. now use master_pos_wait() function, which is used for time-out control, as we lock the chunk, we need release the lock as soon as posible.

**Comment by zz-jason** [comment]
Seems the problem this issue wants to solve is the same with https://github.com/pingcap/tidb/issues/1895
