### ISSUE TITLE
Extend variables system to cover 'INSTANCE'

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9298]
## Feature Request

**Is your feature request related to a problem? Please describe:**

MySQL supports two types of variable scope: `SESSION` and `GLOBAL`.  `SESSION` variables apply to a single connection and `GLOBAL` to a running server.  There is no native notion of a cluster in MySQL, so global is really the running instance.

In TiDB `GLOBAL` variable changes are automatically propagated to the cluster (which is fine), but it makes for some variables to be `GLOBAL`-but-instance-only.  The TiDB way of managing these is to make them `SESSION` variables, which is a little weird:

```
/sessionctx/variable/sysvar.go:
  /* The following variable is defined as session scope but is actually server scope. */
  {ScopeSession, TiDBGeneralLog, strconv.Itoa(DefTiDBGeneralLog)},
  {ScopeSession, TiDBSlowLogThreshold, strconv.Itoa(logutil.DefaultSlowThreshold)},
  {ScopeSession, TiDBQueryLogMaxLen, strconv.Itoa(logutil.DefaultQueryLogMaxLen)},
  {ScopeSession, TiDBConfig, ""},
  {ScopeGlobal, TiDBDDLReorgWorkerCount, strconv.Itoa(DefTiDBDDLReorgWorkerCount)},
  {ScopeGlobal, TiDBDDLReorgBatchSize, strconv.Itoa(DefTiDBDDLReorgBatchSize)},
  {ScopeSession, TiDBDDLReorgPriority, "PRIORITY_LOW"},
  {ScopeSession, TiDBForcePriority, mysql.Priority2Str[DefTiDBForcePriority]},
  {ScopeSession, TiDBEnableRadixJoin, boolToIntStr(DefTiDBUseRadixJoin)},
```

**Describe the feature you'd like:**

I would like to stop polluting the session namespace with global variables.  I think it should be possible to change any* global variable on an instance-only basis with the syntax:

```
SET INSTANCE variable_name=value;
```

* TBD, there might be some restrictions.

The other advantage of creating an instance-level for configuration is that the server can (mostly) be used without a config file.  Currently, there is a bit of a mismatch between `config.toml` and `global variables`.

**Describe alternatives you've considered:**

We could change the word 'global' to mean instance only, and create a new 'cluster' scope.  But I think it is unnecessary to break backward compatibility.

It has a nuance that @@ or @ cannot be used to address instance-level variables, but I think that's okay.

**Teachability, Documentation, Adoption, Migration Strategy:**

I think it is an easy feature to understand.  DBAs also like to be able to make changes in isolation first and then propagate to the cluster, so I think adoption will be straight forward.

**Comment by morgo** [comment]
@shenli @jackysp PTAL

**Comment by zz-jason** [comment]
I think we can do the first step: add the syntax support for instance-level variables.

**Comment by zz-jason** [comment]
> I think we can do the first step: add the syntax support for instance-level variables.

@SunRunAway can we support it in TiDB 5.0? to distinguish session, instance, and global level variables in the query syntax firstly.

**Comment by SunRunAway** [comment]
Closing it and let's discuss here. https://github.com/pingcap/tidb/issues/19332
