### ISSUE TITLE
LOAD DATA LOCAL INFILE tells error 'not found'

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#9321]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

run sql command `LOAD DATA LOCAL INFILE ...` in tidb tells a error `...not found (Errcode: 2)`

I had confirmed that the file of  `/root/test.txt` had existed

the command
```
mysql -h 127.0.0.1 -P 3306 -u root --local-infile=1 -p'password' -D test -e "LOAD DATA LOCAL INFILE '/root/test.txt' INTO TABLE dbgen_version FIELDS TERMINATED BY '|' LINES TERMINATED BY '\n';"
```

I exec the command in mysql, no error occured

---

2. What did you expect to see?

no error

3. What did you see instead?

error tells

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

tidb version : 2.0.4
docker version: 18.03
os : centos 7.2
mysql-client: 5.7
mysql-server: 5.7

**Comment by jackysp** [comment]
Hi @dayuanyuan1989 , could you please provide the TiDB log error message of this command?

**Comment by dayuanyuan1989** [comment]
Thanks for your reply. I had found the reason that proxysql doesn't support `load local infile`.

I use proxysql as the load balance for tidb
