### ISSUE TITLE
Tidb failed writing to pump after restarted by OOM

### ISSUE THREAD

**Issue by alex-lx** [pingcap/tidb#9334]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

> 1. What did you do?
If possible, provide a recipe for reproducing the error.

There're three tidb servers. They were working with binlog cluster well. Last friday one tidb server was killed by OOM. Forunally systemctl restart the process. After that this tidb server started complaining it can't write to pump and stop listerner after started for a few of minutes. while the other two tidb servers works good, and binlogctl tells that all the pump servers are online.

> 2. What did you expect to see?

All tidb servers keep working well

> 3. What did you see instead?

One tidb server can't write to pump.

> 4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.1.2

**Comment by csuzhangxc** [comment]
@alex-lx can you provide some log for this restarted TiDB server?
