### ISSUE TITLE
[proposal] DistSQL Cache on TiDB

### ISSUE THREAD

**Issue by blacktear23** [pingcap/tidb#9336]
## Feature Request

Add cache on DistSQL level to reduce TiKV calculation on DistSQL and make repeat SQL run faster after second time.

## Background

Before this proposal there has a DistSQL implements on TiKV side and this may introduce some problem:

* One DistSQL cache have one lock, so TiKV may block on this lock when many DistSQL is send to it, and it will even block insert and update.
* It will introduce more overhead on cache memory and life-cycle management  on TiKV side.

## New Design

This design is more like HTTP cache mechanism.

* On TiKV side each DistSQL result will take Raft Log ID
* On TiDB side DistSQLCache will hold result data and Raft Log ID
* DistSQLCache key will generated by DistSQL’s SQL
* DistSQLCache entry will hold three data: Raft Log ID, TS and result’s data
* On DistSQL execute, if DistSQL hit cache it will send cached Raft Log ID to TiKV
* If TiKV found the Raft Log ID is match with this DistSQL’s snapshot, it will send a empty result and with match_raft_log_id field.
* If TiDB see match_raft_log_id DistSQL result will get from DistSQLCache.

This is basically like HTTP Last Modified, If-Modified-Since and 304 Not Modified logic.

Below is the pesudo code on TiDB side:

```
func DistSQL::execute() {
    if (this.worth_cache()) {
        cache_key = this.generate_cache_key()
        entry = DistSQLCache.get(cache_key))
        if (entry != NULL && entry.TS <= this.TS) {
            result = this.send_to_tikv_with_raft_log_id(entry.raft_log_id)
            if (result.match_raft_log_id) {
                return entry.data
            } else {
                return result.data
            }
        } else {
            result = this.send_to_tikv()
            raft_log_id = result.raft_log_id
            DistSQLCache.put(cache_key, raft_log_id, result.data)
            return result.data
        }
    } else {
        result = this.send_to_tikv()
        return result.data
    }
}
```

This design we will get some benefit:

* No cache lock on TiKV side
* No cache memory and life-cycle management on TiKV side
* Cache can implement as interface and can introduce plugin system to let end user to determine which cache system can be use.

## TODO List

1. Update protobuf structural for coprocessor
2. TiKV support fill Raft Log ID for each coprocessor query
3. TiKV support check Raft Log ID for coprocessor query
4. Add cache logic for TiDB

**Comment by shenli** [comment]
@blacktear23 Thanks!
/cc @breeswish @zz-jason

**Comment by zz-jason** [comment]
A cache can only be hit only when the same query comes again?

**Comment by siddontang** [comment]
PTAL @BusyJay

**Comment by blacktear23** [comment]
@zz-jason yes

**Comment by siddontang** [comment]
@zz-jason 

I just discussed with @blacktear23, we can introduce the cache in ticlient, so here we don't cache query, but cache AST.

So every the query is changed, the AST for some regions is still the same.

**Comment by blacktear23** [comment]
After discussed with @siddontang I think we can call it CoprocessorCache.

**Comment by shenli** [comment]
@blacktear23 @siddontang I am confused. Why cache the AST? Is it a plan cache? Or a query result cache?

**Comment by blacktear23** [comment]
@shenli the cache should be implemented on coprocessor.go and the cache key is calculated by tikvrpc.Request

**Comment by BusyJay** [comment]
Interesting. The idea of the design is very clean and promising. But to be noted, the result can be changed not just when the data on TiKV is changed but also when the TS of a transaction changes. So the TS needs to be stored besides the cache key and log ID.

**Comment by blacktear23** [comment]
@BusyJay is TS unique for each DistSQL? or always change? If TS is always change the cache may always missing.

**Comment by BusyJay** [comment]
> Or we just hit cache when TS is greater or equals than cached?

Yes, It's exactly what I meant.

**Comment by shenli** [comment]
@blacktear23 @BusyJay Yes, we need to store the max ts that affects the coprocessor result in the cache.
We could make a quick call to discuss this proposal. It is quite promising.

**Comment by breeswish** [comment]
Also notice that session variables affects results..

**Comment by blacktear23** [comment]
After dive into TiDB source code I think the cache logic should add at copIteratorWorker.handleTaskOnce function

**Comment by shenli** [comment]
Related with https://github.com/tikv/tikv/issues/4230

**Comment by nullnotnil** [comment]
This feature request is to cache coprocessor cache results in TiDB - differing from the already implemented coprocessor cache. It may overlap with https://github.com/pingcap/tidb/issues/17469 - in which case maybe we should close this issue to reduce duplication?

**Comment by breeswish** [comment]
@nullnotnil This feature is already implemented. Coprocessor cache caches results in TiDB exactly as what this issue describes. I think we can close this issue.
