### ISSUE TITLE
 Is the memory overhead of tikv large in gc? 

### ISSUE THREAD

**Issue by AlexNewTao** [pingcap/tidb#9353]
## General Question

Before asking a question, make sure you have:

1 When tikv is doing gc, what is the consumption of memory? Is there a certain relationship between consumption and the amount of instance data?

2 In the case of the instance data, or query, tikv three nodes, the memory usage is significantly increased only one node. Even after this node oom is restored, the memory overhead is still large at this node. What is the reason behind this situation? 

3 Is the tikv memory size limit of the same instance related to the tidb memory size limit? If you increase the memory limit of tidb, will it make tikv easier to reach the set threshold, causing the tikv node oom?

the tidb version：2.0.4

**Comment by Connor1996** [comment]
1. For GC, TiKV only iterates the outdated keys and delete them one by one. It would not cost too much memory. And there is no certain relationship between consumption and the amount of instance data.
2. Can you give more details? How is the workload like, and how did the memory usage of TiKV change?  And how large the memory it uses?
3. No, there is no relation. But if you deploy TiDB and TiKV on one machine, it does make TiKV easier to OOM. You'd better change the config `block-cache-size` of TiKV which let it use to use too much memory.

**Comment by AlexNewTao** [comment]
@Connor1996   Thank you for your answer, here are some detailed information. 

The total amount of data for an instance exceeds 400g, and there are frequent complex statement operations. Data is deleted and imported frequently.

1 Container memory increase


![image](https://user-images.githubusercontent.com/15013656/53089284-228b1080-3547-11e9-8d2b-514c46b7b8ba.png)


The oom container has more than 10g of memory in just 3 hours, and there is no data import during this period，but there are some query operations of type EXPENSIVE_QUERY


During the other two tikv nodes, there is almost no increase in memory, and the size is about 28g.

2 the  tikv log

the log as follow:
```
{"log":"2019/02/20 14:46:05.864 scheduler.rs:1306: [ERROR] get snapshot failed for cids=[177119, 177059], error Request(message: \"region is stale\" stale_epoch {new_regions {id: 27676 start_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377wjhg\\377bv\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" end_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_r\\200\\000\\000\\000\\000\\377\\004\\266c\\000\\000\\000\\000\\000\\372\" region_epoch {conf_ver: 5 version: 1545} peers {id: 27677 store_id: 4} peers {id: 27678 store_id: 5} peers {id: 27679 store_id: 18154}} new_regions {id: 27720 start_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377piws\\377ql\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" end_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377wjhg\\377bv\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" region_epoch {conf_ver: 5 version: 1545} peers {id: 27721 store_id: 4} peers {id: 27722 store_id: 5} peers {id: 27723 store_id: 18154}}})\n","stream":"stderr","time":"2019-02-20T06:46:05.864852366Z"}
{"log":"2019/02/20 14:46:05.864 scheduler.rs:1306: [ERROR] get snapshot failed for cids=[177058, 177066], error Request(message: \"region is stale\" stale_epoch {new_regions {id: 27676 start_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377wjhg\\377bv\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" end_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_r\\200\\000\\000\\000\\000\\377\\004\\266c\\000\\000\\000\\000\\000\\372\" region_epoch {conf_ver: 5 version: 1545} peers {id: 27677 store_id: 4} peers {id: 27678 store_id: 5} peers {id: 27679 store_id: 18154}} new_regions {id: 27720 start_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377piws\\377ql\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" end_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377wjhg\\377bv\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" region_epoch {conf_ver: 5 version: 1545} peers {id: 27721 store_id: 4} peers {id: 27722 store_id: 5} peers {id: 27723 store_id: 18154}}})\n","stream":"stderr","time":"2019-02-20T06:46:05.865028803Z"}
{"log":"2019/02/20 14:46:05.865 scheduler.rs:1306: [ERROR] get snapshot failed for cids=[177144, 177060], error Request(message: \"region is stale\" stale_epoch {new_regions {id: 27676 start_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377wjhg\\377bv\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" end_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_r\\200\\000\\000\\000\\000\\377\\004\\266c\\000\\000\\000\\000\\000\\372\" region_epoch {conf_ver: 5 version: 1545} peers {id: 27677 store_id: 4} peers {id: 27678 store_id: 5} peers {id: 27679 store_id: 18154}} new_regions {id: 27720 start_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377piws\\377ql\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" end_key: \"t\\200\\000\\000\\000\\000\\000\\001\\377\\215_i\\200\\000\\000\\000\\000\\377\\000\\000\\001\\001eip-\\377wjhg\\377bv\\000\\377\\000\\000\\000\\000\\000\\371\\000\\000\\375\" region_epoch {conf_ver: 5 version: 1545} peers {id: 27721 store_id: 4} peers {id: 27722 store_id: 5} peers {id: 27723 store_id: 18154}}})\n","stream":"stderr","time":"2019-02-20T06:46:05.865294161Z"}

```

There are a lot of error logs for "region is stale"，In the other two tikv nodes, there are also the same logs.

3 the tidb log
```
{"log":"{\"file\":\"server.go\",\"level\":\"info\",\"line\":305,\"msg\":\"[con:79507] close connection\",\"time\":\"2019/02/20 15:23:01.025\"}\n","stream":"stderr","time":"2019-02-20T07:23:01.0260693Z"}
{"log":"{\"file\":\"compiler.go\",\"level\":\"warning\",\"line\":78,\"msg\":\"[EXPENSIVE_QUERY] \\tSELECT \\trexxxe_id,product_name,proxxx_status,ures_status,uxxxtatus,prodxxxxoperty,uxxxperty,uxxxroperty,\\n\\t\\t\\trexxxsc,biz_status,resxxxs,bill_status \\n\\tFROM txxxxxatch\\n\\t\\n\\tORDER BY rexxxx_id ASC\\n\\tLIMIT 0,400000\",\"time\":\"2019/02/20 15:23:08.167\"}\n","stream":"stderr","time":"2019-02-20T07:23:08.167615314Z"}

```

In the instance where the tikv node oom occurs, there are often some operations of type EXPENSIVE_QUERY，I wonder why the memory increments of the other two tikv nodes are small. Oom always happens on a node.

4 solution

When I queryed the problem, I found that pingcap is on the PD side. Version 2.1 optimizes the hotspot scheduling function, collects more detailed and accurate cluster load information, and makes more reasonable scheduling. The CBO framework has been further improved in the SQL optimizer. Increase cost estimation accuracy。


Our current version of tidb is 2.0.4. The pd hotspot scheduling function is not optimized. The persistent concurrent writes and EXPENSIVE_QUERY cause the disk IO to soar. The number of regions grows rapidly and the hotspots are concentrated. A large number of region scheduling causes a large number of The snapshot operation, which in turn aggravated the consumption of disk IO, eventually led to a vicious circle where the nodes that were originally written were constantly stacked and could not be dispatched.

Therefore, I would like to consult：
1 pd hotspot scheduling function can solve this problem? 
2 The reason for the uneven memory consumption of the tikv node is the issue of hotspot scheduling?
3 You have dealt with similar problems with unbalanced memory overhead. Can you provide the corresponding issue link?

**Comment by Connor1996** [comment]
How large is your `block-cache-size` config?
As for PD hotspot schedule @nolouch PTAL

**Comment by AlexNewTao** [comment]
@Connor1996 

the config is 

block-cache-size = "10GB"

**Comment by AlexNewTao** [comment]
@Connor1996   Can you answer a few questions I mentioned before?

1 pd hotspot scheduling function can solve this problem?
2 The reason for the uneven memory consumption of the tikv node is the issue of hotspot scheduling?
3 You have dealt with similar problems with unbalanced memory overhead. Can you provide the corresponding issue link?

**Comment by Connor1996** [comment]
Sorry for the delay.
1 If the problem due to hot-spot, PD hotspot scheduling maybe can alleviate it.
2 Not for sure.
3 No similar problems.

**Comment by Connor1996** [comment]
Whether the high memory usage is persistent or just high under high load? If the block cache usage is uneven in these TiKVs too?(you can check it in grafana)

And please provide `block-cache-size` config in `rocksdb.writecf` and `rocksdb.lockcf` too.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
