### ISSUE TITLE
tidb oom

### ISSUE THREAD

**Issue by XSHui** [pingcap/tidb#9355]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
- set tidb oom-action = "cancel"
- tidb container memory quota = 60G

2. What did you expect to see?

    tidb work fine

3. What did you see instead?

    tidb oom

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

    tidb-v2.0.4

5. other question 

    How to confirm the parameter  “oom-action” take effect？

**Comment by winoros** [comment]
@XSHui 
Currently, the memory management of TiDB is not well enough. So the oom-action may not work as expected. Could you please tell us what kind of workload/query caused OOM.

**Comment by XSHui** [comment]
thanks for your reply ! @winoros 

Some expensive query, we set tidb container memory quota = 45G before and query be canceld. Now we set tidb container memory quota = 60G, but tidb oom

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. Please try the latest version. If there are any updates, you can reopen it.
