### ISSUE TITLE
Fail to deploy TiDB Cluster 

### ISSUE THREAD

**Issue by XIANGFANGCODE** [pingcap/tidb#9363]
Hello ,

I have four hosts， which are:

```
host name | ip | use for
tidbserver04 | 128.160.185.166 | tikv
tidbserver03 | 128.160.185.168 | tikv
tidbserver02 | 128.160.185.167 | tikv
tidbserver01 | 128.160.184.225 | download host、tipd、tidb
```
I deploy Tidb on tidbserver01.

Everything go well untill i run the command:

`ansible-playbook deploy.yml`

`2019-02-18 17:48:53,680 p=25241 u=tidb |  [MS1]: Ansible FAILED! => playbook: deploy.yml; TASK: collect_diagnosis : uncompress tidb-insight scripts; message: {"changed": false, "module_stderr": "Shared connection to 128.160.185.166 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_j9y574k0/ansible_module_unarchive.py\", line 136, in <module>\r\n    from ansible.module_utils.urls import fetch_url\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 955, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 656, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 626, in _load_backward_compatible\r\n  File \"/tmp/ansible_j9y574k0/ansible_modlib.zip/ansible/module_utils/urls.py\", line 340, in <module>\r\nAttributeError: module 'urllib.request' has no attribute 'HTTPSHandler'\r\n", "msg": "MODULE FAILURE", "rc": 1}
`

ansible logs and fail logs are here:

[ansible.log](https://github.com/pingcap/tidb/files/2882859/ansible.log)
[fail.log](https://github.com/pingcap/tidb/files/2882860/fail.log)

This problem has been bothering me for two days. 

Thank you for any help.

**Comment by jebter** [comment]
The lifecycle of version 4.0 and earlier has ended(https://www.pingcap.com/tidb-release-support-policy/). Let's close it. Please try the latest version. If there are any updates, you can reopen it.
