### ISSUE TITLE
"explain extended" is not supported in TiDB

### ISSUE THREAD

**Issue by PerfectXD** [pingcap/tidb#9366]
When running select ddl in SQLyog v8.14, software prompt error as below.
![image](https://user-images.githubusercontent.com/13029641/53067040-62cd9d00-350d-11e9-9d87-5b9ffd43f0a4.png)

After enable tidb_general_log，warning occurs in the log.
[tidb.log](https://github.com/pingcap/tidb/files/2883079/tidb.log)

**Comment by morgo** [comment]
Duplicate of #3640.

Please note that the format of `EXPLAIN` in TiDB differs from MySQL.  The use case for `EXPLAIN EXTENDED` is to run `show warnings` after.

**Comment by zz-jason** [comment]
close due to duplication.
