### ISSUE TITLE
Add index to the stored generated column whose expression contains the column added by "add column"

### ISSUE THREAD

**Issue by zimulala** [pingcap/tidb#9372]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
create table t(id int);
insert into t values(1);
ALTER TABLE t ADD COLUMN a int as (id+1) stored;
select * from t;
```

2. What did you expect to see?
```
mysql> create table t(id int);
Query OK, 0 rows affected (0.03 sec)
mysql> insert into t values(1);
Query OK, 1 row affected (0.00 sec)
mysql> ALTER TABLE t ADD COLUMN a int as (id+1) stored;
Query OK, 1 row affected (0.03 sec)
Records: 1  Duplicates: 0  Warnings: 0
mysql> select * from t;
+------+------+
| id   | a    |
+------+------+
|    1 |    2 |
+------+------+
1 row in set (0.01 sec)
```

3. What did you see instead?
```
tidb> create table t(id int);
Query OK, 0 rows affected (0.00 sec)
tidb> insert into t values(1);
Query OK, 1 row affected (0.00 sec)
tidb> ALTER TABLE t ADD COLUMN a int as (id+1) stored;
Query OK, 0 rows affected (0.02 sec)
tidb> select * from t;
+------+------+
| id   | a    |
+------+------+
|    1 | NULL |
+------+------+
1 row in set (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v3.0.0-beta-69-g84d1513b0
Git Commit Hash: 84d1513b09222c60ffba2d3397b6745e5148a603
Git Branch: master

**Comment by zimulala** [comment]
> You cannot add the generated column in the storage type of STORED through ALTER TABLE.
You cannot create an index on the generated column through ALTER TABLE.

Refer to https://github.com/pingcap/docs/blob/master/sql/generated-columns.md#limitations

**Comment by wjhuang2016** [comment]
Duplicate with #9288
