### ISSUE TITLE
Variables should use status var interface

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9381]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I found a bug in https://github.com/pingcap/tidb/pull/9365

It looks like the variables are initialized before the config file is parsed.  So if the port is non-default, it won't be reflected.

**Describe the feature you'd like:**

Instead of having configuration all in one place, I think a nicer design would be to have individual components 'register' sysvars.  This would make it work closer to how status vars currently work.

The advantage would be that plugins could also add additional variables to the server.

(This would make it work similar to MySQL too..)

**Describe alternatives you've considered:**

An easy workaround would be to update the sysvars after the server starts.

**Teachability, Documentation, Adoption, Migration Strategy:**

It would take some initial work to move sysvars to the correct component.  Initially, they could all be put under the server.

**Comment by morgo** [comment]
PTAL @tiancaiamao 

Do you see any flaws in this strategy?

**Comment by tiancaiamao** [comment]
individual components 'register' sysvars sounds a good idea.
/cc @lysu

**Comment by lysu** [comment]
+1 plugin also needs a mechanism to "register sysvar" into hosted TiDB too,  and now plugins use ugly way to do it. we should improve it.

**Comment by nullnotnil** [comment]
@lysu do you mind if I take this over?

**Comment by lysu** [comment]
> @lysu do you mind if I take this over?

:D surely maybe after finish https://github.com/pingcap/tidb/pull/18717 then maybe have to do this

**Comment by nullnotnil** [comment]
I meant I would like to work on this if that is okay with you :)

I think it works best as multiple PRs:
1. Convert variables to using status var interface.
2. Refine the sysVar struct to hold min/max/validation (anonymous function), and move it out of ` ValidateSetSystemVar`: https://github.com/pingcap/tidb/blob/master/sessionctx/variable/varsutil.go#L326-L327
3. Add an `information_schema.variables_info` table (based on what is there in MySQL 8.0).
4. Start work on instance scoped variables. i.e. https://github.com/pingcap/tidb/issues/19332

**Comment by lysu** [comment]
> I meant I would like to work on this if that is okay with you :)
> 
> I think it works best as multiple PRs:
> 
> 1. Convert variables to using status var interface.
> 2. Refine the sysVar struct to hold min/max/type/validation (anonymous function), and move it out of ` ValidateSetSystemVar`: https://github.com/pingcap/tidb/blob/master/sessionctx/variable/varsutil.go#L326-L327
> 3. Fix #15131
> 4. Add an `information_schema.variables_info` table (based on what is there in MySQL 8.0).
> 5. Start work on instance scoped variables. i.e. #19332

:+1: Yes, it's ok for me~ :blush:
