### ISSUE TITLE
Support multiple table rename (swap table use case)

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9384]
## Feature Request

**Is your feature request related to a problem? Please describe:**

I know that multiple DDL changes are currently on the roadmap.  My feature request is to support a much smaller subset, which is an atomic rename of two tables.

This supports the use case of swapping tables, something that occurs frequently in the replication stream due to its usage by tools such as `pt-online-schema-change`.

**Describe the feature you'd like:**

```
mysql> CREATE TABLE t1 (a int);
Query OK, 0 rows affected (0.01 sec)

mysql> CREATE TABLE t2 (a int, b int);
Query OK, 0 rows affected (0.01 sec)

mysql> RENAME TABLE t1 to t1_old, t2 to t1; <--- should work 
ERROR 1105 (HY000): can't run multi schema change
```

**Describe alternatives you've considered:**

The alternative is to do this non-atomically (breaks apps) or under a global lock (not yet supported by TiDB).  So there is not really a good alternative.

**Teachability, Documentation, Adoption, Migration Strategy:**

MySQL compatible behavior.

## Score
1500

## SIG Slack Channel
You can join [#sig-ddl ](https://app.slack.com/client/TH91JCS4W/CMAKWBNJU)on slack in your spare time to discuss and get help with mentors or others.

## Mentor(s)
* @zimulala 

## Recommended Skills
* DDL
* Golang

## Learning Materials
MySQL's [document](https://dev.mysql.com/doc/refman/8.0/en/invisible-indexes.html) for syntax reference.
[TiDB DDL architecture](https://github.com/pingcap/tidb/blob/master/docs/design/2018-10-08-online-DDL.md)

**Comment by morgo** [comment]
@shenli @winkyao PTAL

**Comment by winkyao** [comment]
@morgo Got it, we are planning to have a design document of the multiple DDL changes. Multi table rename can be developed first.

**Comment by zimulala** [comment]
```
RENAME TABLE
    tbl_name TO new_tbl_name
    [, tbl_name2 TO new_tbl_name2] ...
```
Refer to: https://dev.mysql.com/doc/refman/5.7/en/rename-table.html
