### ISSUE TITLE
make `newFirstChunk` more effective

### ISSUE THREAD

**Issue by hicqu** [pingcap/tidb#9396]
## General Question
Here is a call graph about TiDB's CPU usage in attached file.
![profile001](https://user-images.githubusercontent.com/8407317/53147025-3be09b00-35e1-11e9-9173-6f77c4bed16c.png)

We can see `newFirstChunk` utilizes about 10% CPU of total.

I have tried to use a `sync.Pool` to cache `*column`s to improve it, but the result is not better. With the patch `sync.Pool` itself becomes the new bottle neck.

So please try to find a good wait to cache `*column`s to improve it.

**Comment by winoros** [comment]
What's your workload?
@zz-jason What about testing column pool in this environment?

**Comment by zz-jason** [comment]
There are many ways to implement a column pool. For example, `sync.Pool`, lock free list, channel based resource reuse.

- `sync.Pool`: the put and get operations is very fast, but the content in that pool is freed when golang GC is triggered.
- lock free list, channel: the put and get operations is slow compared with `sync.Pool`, but the content in the pool can be control by ourself.

There is still some problem to solve in the column pool implementation, I think we can leave this optimization in the future. For now, let's focused on chunk size control to improve the query latency.

**Comment by zz-jason** [comment]
There are some pool implementations and the benchmark results in this gist: https://gist.github.com/zz-jason/c98d942dddbb32c134c9cadffd983f61

This is a simple lock free list implementation: https://github.com/zz-jason/lockfree, the benchmark can be gained by running `BenchmarkPushPop()`

**Comment by hicqu** [comment]
I have tested `sync.Pool` but the result is bad. I prefer to use some lockfree collections or a channel, but I'm blocked on 1 thing: we must release `*column` manual and return it back to the pool. Could you help me? @zz-jason

**Comment by XuHuaiyu** [comment]
> I'm blocked on 1 thing: we must release `*column` manual and return it back to the pool.
Can you describe more on this part?

**Comment by SunRunAway** [comment]
We can give `sync.Pool` a try again using go1.13beta. See https://github.com/golang/go/issues/22950

**Comment by SunRunAway** [comment]
I used `sysbench oltp_read_only` to test on the master branch with go1.13beta1, it seems `newFirstChunk` is not a hot path. I'll close this issue and if someone finds another performance problem with `newFirstChunk`, feel free to reopen it.
