### ISSUE TITLE
Support for caching_sha2_password

### ISSUE THREAD

**Issue by ian-p-cooke** [pingcap/tidb#9411]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Windows 10
libmysql 8.0.4-3 installed via vcpkg
Visual Studio 2017

```C
// MysqlTest.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"
#include <mysql/mysql.h>

int main()
{
	MYSQL mysql;

	mysql_init(&mysql);
	mysql_options(&mysql, MYSQL_SET_CHARSET_NAME, "utf8");
	if (!mysql_real_connect(&mysql, "127.0.0.1", "root", "", "information_schema", 4000, NULL, 0))
	{
		fprintf(stderr, "Failed to connect to database: Error: %s\n",
			mysql_error(&mysql));
		return 1;
	}
	else
	{
		printf("success!\n");
		return 0;
	}
}
```

build/run an example C client that uses libmysql to connect to database.  I actually started out trying to use Rust with Diesel but boiled the problem down to using the C library.

2. What did you expect to see?

"success!"

especially since DataGrip (JDBC driver) and mysql cli can connect and work fine.

3. What did you see instead?

"Failed to connect to database: Error: Unknown MySQL error"

TiDB had no errors it its log.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

deployed via docker-compose (https://github.com/pingcap/tidb-docker-compose)

Release Version: v3.0.0-beta-27-g6398788
Git Commit Hash: 6398788f6bb722d29d06b754e3d1d61d02a3090e
Git Branch: master
UTC Build Time: 2019-01-31 08:42:28
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

**Comment by ian-p-cooke** [comment]
I found a solution: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password

So, after calling 
```C
	mysql_options(&mysql, MYSQL_DEFAULT_AUTH, "mysql_native_password");
```
I was able to connect.

Do you plan on supporting AUTH via `caching_sha2_password`?

**Comment by zimulala** [comment]
@ian-p-cooke 
Thanks for your report!
We don't intend to support this feature in the near future.

**Comment by ian-p-cooke** [comment]
ok, I can use mysql_native_password so I'm ok with that.  You can close this issue if you like.

**Comment by nullnotnil** [comment]
Support for auth switch has been added to master in https://github.com/pingcap/tidb/pull/19959 - so MySQL 8.0 clients will now work without changes.

I will leave this issue open for actually adding `caching_sha2_password`. But likely the priority is now lower.

**Comment by dveeden** [comment]
There are two modes of caching_sha2 authentication:
- *fast authentication*: This works if the server has a cache entry for the account. This does work over insecure connections. This is the caching part of `caching_sha2_password`.
- *full authentication*: This is needed in case there is no cache entry. This means the plaintext password gets send over a secure connection to the server allowing the server to validate it and to create a cache entry for it.

There are basically 3 types of secure connections that can be used:
- *TLS* (sometimes referred to as SSL)
- *UNIX socket*
- RSA public key based. The server has a RSA keypair and the client can request the public key and use that to encrypt the password before sending it to the server. 

Here is a simple protocol description
N is Non-TLS and T stands for TLS.

Fast authentication over TLS:
N -> ServerGreeting (with SSL flag set)
N <- Login (empty, with SSL flag set)
T <- Login with authdata
T -> FastAuthOK (command 1, payload 3)
T -> OK Packet

Full authentication over TLS:
N -> ServerGreeting (with SSL flag set)
N <- Login (empty, with SSL flag set)
T <- Login with authdata
T -> FullAuthRequired (command 1, payload 4)
T <- ClearTextPassword
T -> OK Packet

I think it would be good to:
- Initially only support TLS (and maybe UNIX socket) for connections. The RSA key support isn't as secure and is difficult to operate.
- Initially only support full authentication
- Not have/set `default_authentication_plugin` but leave this set on `mysql.AuthNativePassword`. This could mean extra roundtrips but as the official client ignores this that is probably not even the case.
- Have an `plugin` column on `mysql.user` to store the plugin that is used for that account. This is how MySQL does it. The alternative would be to rely on the length of `mysql.user.authentication_string`.
