### ISSUE TITLE
v2.1.4 tidb-server init can't login without password

### ISSUE THREAD

**Issue by pcleon** [pingcap/tidb#9424]
i download tidb from https://download.pingcap.org/tidb-v2.1.4-linux-amd64.tar.gz and run a new tidb-server cluster, everything is ok .
then i want to login with "mysql -uroot -hx.x.x.x -p4000 " , it report 
`
2019/02/22 20:21:29.366 terror.go:342: [error] lookup 29.4.4.10.in-addr.arpa. on 10.16.227.13:53: server misbehaving
github.com/pingcap/errors.AddStack
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/errors.Trace
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/juju_adaptor.go:12
github.com/pingcap/tidb/session.getHostByIP
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:1101
github.com/pingcap/tidb/session.(*session).Auth
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:1082
github.com/pingcap/tidb/server.(*TiDBContext).Auth
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/driver_tidb.go:273
github.com/pingcap/tidb/server.(*clientConn).openSessionAndDoAuth
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:413
github.com/pingcap/tidb/server.(*clientConn).readOptionalSSLRequestAndHandshakeResponse
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:389
github.com/pingcap/tidb/server.(*clientConn).handshake
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/conn.go:127
github.com/pingcap/tidb/server.(*Server).onConn
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/server/server.go:306
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
2019/02/22 20:21:29.366 session.go:1092: [error] User connection verification failed root@10.4.4.29
`

tidb-server version info below:
`Release Version: v2.1.4
Git Commit Hash: a1d10c17039ec289ef490481b25c7091dba7ac31
Git Branch: release-2.1
UTC Build Time: 2019-02-15 06:24:33
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
`
i want to add parameter "-skip-grant-table=true" but prompt no this parameter, how to solve this problem??

**Comment by pcleon** [comment]
tidb's log show something below:
`2019/02/22 23:44:18.702 session.go:795: [warning] con:0 schema_ver:0 session error:
[schema:1049]Unknown database 'mysql'
github.com/pingcap/errors.AddStack
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190118033454-a52e5bde3bd2/terror/terror.go:231
github.com/pingcap/tidb/executor.(*SimpleExec).executeUse
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/simple.go:90
github.com/pingcap/tidb/executor.(*SimpleExec).Next
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/simple.go:57
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/adapter.go:291
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/adapter.go:238
github.com/pingcap/tidb/session.runStmt
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/tidb.go:185
github.com/pingcap/tidb/session.(*session).executeStatement
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:792
github.com/pingcap/tidb/session.(*session).execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:856
github.com/pingcap/tidb/session.(*session).Execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:809
github.com/pingcap/tidb/session.checkBootstrapped
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/bootstrap.go:269
github.com/pingcap/tidb/session.bootstrap
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/bootstrap.go:216
github.com/pingcap/tidb/session.runInBootstrapSession
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:1234
github.com/pingcap/tidb/session.BootstrapSession
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:1172
main.createStoreAndDomain
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/tidb-server/main.go:166
main.main
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/tidb-server/main.go:140
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
{
  "currDBName": "",
  "id": 0,
  "status": 2,
  "strictMode": true,
  "user": null
}
2019/02/22 23:44:18.703 session.go:850: [warning] con:0 compile error:
[schema:1146]Table 'mysql.tidb' doesn't exist
SELECT HIGH_PRIORITY VARIABLE_VALUE FROM mysql.tidb WHERE VARIABLE_NAME="bootstrapped"
2019/02/22 23:44:18.703 session.go:1477: [info] [CRUCIAL OPERATION] con:0 schema_ver:0 CREATE DATABASE IF NOT EXISTS test (by <nil>).
2019/02/22 23:44:18.717 ddl.go:492: [info] [ddl] start DDL job ID:2, Type:create schema, State:none, SchemaState:none, SchemaID:1, TableID:0, RowCount:0, ArgLen:1, start time: 2019-02-22 23:44:18.683 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0, Query:CREATE DATABASE IF NOT EXISTS test
`

**Comment by pcleon** [comment]
tidb's log show something below:
`2019/02/22 23:44:18.702 session.go:795: [warning] con:0 schema_ver:0 session error:
[schema:1049]Unknown database 'mysql'
github.com/pingcap/errors.AddStack
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
        /home/jenkins/workspace/build_tidb_2.1/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190118033454-a52e5bde3bd2/terror/terror.go:231
github.com/pingcap/tidb/executor.(*SimpleExec).executeUse
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/simple.go:90
github.com/pingcap/tidb/executor.(*SimpleExec).Next
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/simple.go:57
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/adapter.go:291
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/executor/adapter.go:238
github.com/pingcap/tidb/session.runStmt
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/tidb.go:185
github.com/pingcap/tidb/session.(*session).executeStatement
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:792
github.com/pingcap/tidb/session.(*session).execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:856
github.com/pingcap/tidb/session.(*session).Execute
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:809
github.com/pingcap/tidb/session.checkBootstrapped
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/bootstrap.go:269
github.com/pingcap/tidb/session.bootstrap
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/bootstrap.go:216
github.com/pingcap/tidb/session.runInBootstrapSession
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:1234
github.com/pingcap/tidb/session.BootstrapSession
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/session/session.go:1172
main.createStoreAndDomain
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/tidb-server/main.go:166
main.main
        /home/jenkins/workspace/build_tidb_2.1/go/src/github.com/pingcap/tidb/tidb-server/main.go:140
runtime.main
        /usr/local/go/src/runtime/proc.go:201
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1333
{
  "currDBName": "",
  "id": 0,
  "status": 2,
  "strictMode": true,
  "user": null
}
2019/02/22 23:44:18.703 session.go:850: [warning] con:0 compile error:
[schema:1146]Table 'mysql.tidb' doesn't exist
SELECT HIGH_PRIORITY VARIABLE_VALUE FROM mysql.tidb WHERE VARIABLE_NAME="bootstrapped"
2019/02/22 23:44:18.703 session.go:1477: [info] [CRUCIAL OPERATION] con:0 schema_ver:0 CREATE DATABASE IF NOT EXISTS test (by <nil>).
2019/02/22 23:44:18.717 ddl.go:492: [info] [ddl] start DDL job ID:2, Type:create schema, State:none, SchemaState:none, SchemaID:1, TableID:0, RowCount:0, ArgLen:1, start time: 2019-02-22 23:44:18.683 +0800 CST, Err:<nil>, ErrCount:0, SnapshotVersion:0, Query:CREATE DATABASE IF NOT EXISTS test
`

**Comment by zimulala** [comment]
@pcleon 
Thanks for your report!

> mysql -uroot -hx.x.x.x -p4000
Did you connect with to the database "mysql -uroot -hx.x.x.x -p4000" or "mysql -uroot -hx.x.x.x -P4000"?

**Comment by pcleon** [comment]
> @pcleon
> Thanks for your report!
> 
> > mysql -uroot -hx.x.x.x -p4000
> 
> Did you connect to the database with "mysql -uroot -hx.x.x.x -p4000" or "mysql -uroot -hx.x.x.x -P4000"?

use the capitals P
