### ISSUE TITLE
Support for utf8mb4_0900_ai_ci

### ISSUE THREAD

**Issue by ian-p-cooke** [pingcap/tidb#9426]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

attempt to connect to database using utf8mb4 as the default character set.

```Bash
> mysql -P4000 -uroot --default-character-set=utf8mb4
```

2. What did you expect to see?

a mysql prompt.

3. What did you see instead?

`ERROR 1105 (HY000): Unknown charset id 255`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

| Release Version: v3.0.0-beta-27-g6398788
Git Commit Hash: 6398788f6bb722d29d06b754e3d1d61d02a3090e
Git Branch: master
UTC Build Time: 2019-01-31 08:42:28
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |

-- 

Setting the character set after connecting works as expected:
```SQL
PS C:\> mysql -P4000 -uroot --default-character-set=utf8
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 54
Server version: 5.7.10-TiDB-v3.0.0-beta-27-g6398788 MySQL Community Server (Apache License 2.0)

Copyright (c) 2000, 2018, Oracle and/or its affiliates. All rights reserved.

Oracle is a registered trademark of Oracle Corporation and/or its
affiliates. Other names may be trademarks of their respective
owners.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_system     | utf8    |
| character_set_client     | utf8    |
| character_set_results    | utf8    |
| character_set_connection | utf8    |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_server     | utf8mb4 |
+--------------------------+---------+
7 rows in set (0.01 sec)

mysql> set names utf8mb4;
Query OK, 0 rows affected (0.00 sec)

mysql> SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_system     | utf8    |
| character_set_client     | utf8mb4 |
| character_set_results    | utf8mb4 |
| character_set_connection | utf8mb4 |
| character_set_server     | utf8mb4 |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
+--------------------------+---------+
7 rows in set (0.00 sec)
```

**Comment by ian-p-cooke** [comment]
i actually encountered this problem with diesel first because it sets the default character set programmatically to utf8mb4.   I see now there's an existing issue #6942.  Why is it a problem with the default character set but not setting the `names` variable?

**Comment by zimulala** [comment]
@ian-p-cooke 
Thanks for you report!
PTAL @lysu

**Comment by lysu** [comment]
> Why is it a problem with the default character set but not setting the `names` variable?

Hi, `ERROR 1105 (HY000): Unknown charset id 255` is misleading, the real unknown in here is `collation id` instead of charset id, and collation implies character.

the question in here is mysql 8.0 change default collation to new `utf8mb4_0900_ai_ci`, and 8.0 mysqlclient will set collation with collation id when establish connection to server if use utf8mb4 charset but tidb doesn't support that collation now,  so user will got that error.

on the other side,  `set names` just change charset doesn't modify collation so it has not problem.

**Comment by morgo** [comment]
I am going to repurpose this as a new-feature request.  We currently only claim 5.7 support, which does not include `utf8mb4_0900_ai_ci`, but will track it with respect to 8.0 support.

**Comment by Enver-Yilmaz** [comment]
What is the actual plan here? Just fake it for the client or genuinely implement utf8mb4_0900_ai_ci?

**Comment by winkyao** [comment]
@Enver-Yilmaz We are planning to fix this error in https://github.com/pingcap/parser/pull/294#pullrequestreview-228079286

**Comment by bb7133** [comment]
Hi @ian-p-cooke , I closed this before because this issue is about ’supporting it in syntax'(at least we treated it this way), however TiDB doesn't support the semantic of `utf8mb4_0900_ai_ci`.

In order to avoid ambiguity, I'm going to re-title this issue to "Support for utf8mb4_0900_ai_ci in syntax'. And please feel free to file another issue if you need its 'real semantic'.
