### ISSUE TITLE
MySQL query layer as standalone project?

### ISSUE THREAD

**Issue by thumbsized** [pingcap/tidb#9429]
Hi,
since TiDB uses k-v storage under the hood, would it be possible to make the MySQL's SQL layer into separate project so people could swap the underlying storage with badger or bolt or other kv database?

I've asked this the folk at CockroachDB but they said they are too tied to the RocksDB. What's the status in here?

**Comment by lonng** [comment]
Sure, you can register other stores as TiDB storage layer, which should implement kv.Storage interface.

**Comment by morgo** [comment]
@thumbsized the test-suite for example uses goleveldb.  You can startup TiDB without tikv by specifying the store as `mocktikv`.
