### ISSUE TITLE
tidb-server gradually oom when join two tables

### ISSUE THREAD

**Issue by Still4** [pingcap/tidb#9430]
## Bug Report

1. What did you do?
Here is the sql running on multiple databases:

SELECT ... FROM user u INNER JOIN pay p USE INDEX(idx_time) ON p.uid = u.uid WHERE p.time >= 1533859200000 AND p.time < 1533945600000;

table user we have 20m rows, uid is primary key,
table pay we have 6m rows, uid is index, adding condition p.time >= '1533859200000' and p.time < '1533945600000' we have about 20k rows.

2. What did you see?
Every time the sql runs, tidb-server use 1G memory, until tidb-server got killed, even, so after our 3 databases runs about 20 days report, we get error shows Mysql server has gone, and tidb-server was killed by system and automatically restarted.
We tried to establish connections every time we execute this sql, but didn't work.

3. What did you expect to see?
Our scripts have been working fine for couple months with v2.0.6, until we upgraded to v2.1.4 this week.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.1.4
Git Commit Hash: a1d10c17039ec289ef490481b25c7091dba7ac31
Git Branch: release-2.1
UTC Build Time: 2019-02-15 06:24:33
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

5.This is what we saw when explain the sql.
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/13746605/53291177-28ece700-37ea-11e9-9426-2bd777e47853.png">

**Comment by zimulala** [comment]
@Still4  Thanks for your feedback!
Could you tell me the size of your server memory? And you introduced the `user` and `pay` tables, so what is the table of `t` and `user_pay` in the explain result?

**Comment by Still4** [comment]
> @Still4 Thanks for your feedback!
> Could you tell me the size of your server memory? And you introduced the `user` and `pay` tables, so what is the table of `t` and `user_pay` in the explain result?

thanks for reply, `user_pay` is the `pay` table, I  thought `user` and `pay` tables are easier to understand, sorry about that, here is the original sql:
explain select count(1) from user_attribution t inner join user_pay p use index(idx_time) on p.uid = t.uid where p,time >= '1533859200000' and p.time < '1533945600000';
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/13746605/53297943-1bbf0f00-3861-11e9-87b0-660c6aad5175.png">

tidv-server running with 64G memory

we read last 30 days data and generate aggregated reports, and this sql reads data day by day, like  2019-01-25, 2019-01-26 ... 2019-02-23

after todays tests, we found the main issue is we have two big databases to run, and we let them runs at the same time, if we run sqls on the second database 30 mins after running the first database, there will be no more crash, memory usage automatically released.
seems like some cached data, if so, do we have params to make cache time shorter, because we really need the data ready at the same time, thanks!

**Comment by Still4** [comment]
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/13746605/53302165-555e3d00-3896-11e9-8c68-73771c483a64.png">

We found something interesting, after created a same structure table `user_attribution_new` and put some data from `user_attribution`, something different shows, new table use range: decided by [p.uid], I think this is how tidb join works, the old one might be a full scan

Then we realized after upgraded to v2.1.4, some utf8mb4 data cannot be correctly insert, so we changed character to utf8mb4 from utf8 for every field, could it be this operation caused primary key no longer useful?

**Comment by shenli** [comment]
> Then we realized after upgraded to v2.1.4, some utf8mb4 data cannot be correctly insert,

@Still4 Could you show me more detailed info?

**Comment by zimulala** [comment]
@Still4 

> table user we have 20m rows, uid is primary key,

From your reply, I guess the `user` is `user_attribution`.
Observe the result of `explain`, it seems that there is a gap between the number of rows in the table of `user_attribution` and the actual number of rows. Cloud you execute the operation of `analyze table user_attribution`? Then show me the result of `explain`.

**Comment by Still4** [comment]
@zimulala 
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/13746605/53313245-75701980-38f3-11e9-88e3-6d967a60c115.png">

it works ! 
we've renamed user_attribution to user_attribution_old, seems we need it back now.
thanks a lot!

**Comment by Still4** [comment]
@shenli 
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/13746605/53313824-25468680-38f6-11e9-8d3b-20fc87251510.png">
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/13746605/53314007-009ede80-38f7-11e9-8515-617e34a54769.png">

INSERT INTO adcreative (`id`,`name`) VALUES ("23842963827120421","🏆2018 Game Top rated (4.4★★★★★)");
