### ISSUE TITLE
Using InnoDb storage engine instead of RocksDB

### ISSUE THREAD

**Issue by diwakarpp** [pingcap/tidb#9433]
Hi,

We have a database of around 150 GB data in around 270 tables. For some of the queries, the TiDB takes between 1 second to 6 seconds where the MySQL InnoDB based db takes just less than 1 second. Do you think if I change the TiKV layer to use InnoDb Engine instead of RocksDB, would it help speed of the results? I request your suggestions if InnoDB would really help here or could it make worse than RocksDB for this scenario?

Thanks and regards,
Diwakar

**Comment by morgo** [comment]
There are several reasons why performance may differ between MySQL and TiDB; RocksDB is of course one of them.

If you paste the output of `EXPLAIN <query>` from MySQL and TiDB, plus the differences in execution time I would be happy to clarify further.

**Comment by diwakarpp** [comment]
Hi, thank you for your prompt reply. I will try to get the EXPLAIN and other stats sent soon(one of my team members will get this). Meanwhile, could you pl let me know any references/documents or notes on how to change storage engine used in TiKV (technically replacing the RocksDB with any other storage engine)? So this could be an attempt by us to compare it like for like comparison between the TiDB with RocksDB and TiDB with InnoDB performance difference.

**Comment by morgo** [comment]
TiKV has adding a cleaner storage engine abstraction on their roadmap, as they are working on more efficient blob storage with Titan (a RocksDB-like engine).  But there are no plans for InnoDB support.

If you wanted to test out InnoDB vs RocksDB in a more MySQL-like scenario, you could test with Percona Server for example.

**Comment by diwakarpp** [comment]
Just to add to my question, by quickly glancing the code I see we could introduce a new "store" at  https://github.com/pingcap/tidb/tree/master/store level. Is there a Storage API doc/reference to do this? Any notes and pointers on this would be much helpful so we can replace the RocksDb (with InnoDB or any other DB easily).

**Comment by diwakarpp** [comment]
Ok thank you for your reply. Looks like our messages crossed each other :-) :-) Sure, I will try it with Percona Server cluster.

**Comment by morgo** [comment]
> Just to add to my question, by quickly glancing the code I see we could introduce a new "store" at https://github.com/pingcap/tidb/tree/master/store level. Is there a Storage API doc/reference to do this? Any notes and pointers on this would be much helpful so we can replace the RocksDb (with InnoDB or any other DB easily).

Yes, TiDB also supports a storage-engine like abstraction (kv.Storage interface).  But there will be a lot for you to implement since TiDB relies on TiKV for replication and HA.

**Comment by diwakarpp** [comment]
Thank you very much. Cheers.

**Comment by morgo** [comment]
@diwakarpp Quick followup, do you have the output from `EXPLAIN <query>` for any of the statements that were slower in TiDB?  I would be happy to comment in more detail..

**Comment by diwakarpp** [comment]
@morgo thank you for your assistance, Sorry, for time being we have removed TiDB from our cluster because of time and resource constraints and opted MySQL MaxScale cluster. When TiDB is improved to use InnoDB storage engine or some of other efficient, we will be happy to try TiDB. Basically, we join queries joining 9 tables in a single query that selects around 500K records and fetches 50 records per request (paging with 50 records per page). Cheers.

**Comment by morgo** [comment]
Thanks @diwakarpp. InnoDB support is not on our current roadmap, so I am going to close this issue for now.
