### ISSUE TITLE
Support creating an index the same as the column name

### ISSUE THREAD

**Issue by c-wind** [pingcap/tidb#946]
Mysql support this feature
I found the following code in the function buildIndexInfo
`
    for _, col := range tblInfo.Columns {
        if col.Name.L == indexName.L {
            return nil, errors.Errorf("CREATE INDEX: index name collision with existing column: %s", indexName)
        }
    }
`
This code can be removed?

**Comment by coocood** [comment]
Yes, those lines can be removed.
Thank you for your report!
Would you please send a PR to fix this?

**Comment by c-wind** [comment]
Ok, I will try
