### ISSUE TITLE
`select constants` is not same with MySQL.

### ISSUE THREAD

**Issue by xiekeyi98** [pingcap/tidb#9463]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

Exec
```SQL
select 1;
select 12;
select 123;
```

2. What did you expect to see?

![image](https://user-images.githubusercontent.com/7782671/53387761-504adc00-39c3-11e9-8dcf-ca881f3220da.png)

3. What did you see instead?

![image](https://user-images.githubusercontent.com/7782671/53387797-69ec2380-39c3-11e9-8b04-8905cb6bf6b1.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
mysql> select TiDB_version()\G
*************************** 1. row ***************************
TiDB_version(): Release Version: v3.0.0-beta-117-gc48ac8af1-dirty
Git Commit Hash: c48ac8af1817bd92847c15d98b9d8eaf3d389130
Git Branch: master
UTC Build Time: 2019-02-26 02:07:00
GoVersion: go version go1.11.5 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by xiekeyi98** [comment]
@wjhuang2016 
Thanks for your contribution.

Would you mean you change the code of Mysql-client, change the flag `IS_NOT_NULL` by hardcode, and recompile it?
And then it works well, right? (Seems we need to send this flag to MySQL?)

**Comment by wjhuang2016** [comment]
@xiekeyi98 
That is all what I do:
In server/column.go

	buffer = dumpLengthEncodedString(buffer, []byte("def"))
	buffer = dumpLengthEncodedString(buffer, []byte(column.Schema))
	buffer = dumpLengthEncodedString(buffer, []byte(column.Table))
	buffer = dumpLengthEncodedString(buffer, []byte(column.OrgTable))
	buffer = dumpLengthEncodedString(buffer, []byte(column.Name))
	buffer = dumpLengthEncodedString(buffer, []byte(column.OrgName))

	buffer = append(buffer, 0x0c)
       
    // Add NotNullFlag by hardcode
	if column.Type == 8 {
		column.Flag |= uint16(mysql.NotNullFlag)
	}

	buffer = dumpUint16(buffer, column.Charset)
	buffer = dumpUint32(buffer, column.ColumnLength)
	buffer = append(buffer, dumpType(column.Type))
	buffer = dumpUint16(buffer, dumpFlag(column.Type, column.Flag))
	buffer = append(buffer, column.Decimal)
	buffer = append(buffer, 0, 0)

By doing this, the Mysql-client recognizes the NotNullFlag and displays properly.
I think setting the NotNullFlag to a ValueExpr is resonable as long as it isn't NULL.

**Comment by xiekeyi98** [comment]
@lysu  PTAL, Thanks♪(･ω･)ﾉ

**Comment by lysu** [comment]
@wjhuang2016 Thanks~ 
agree with you, it should be NotNullFlag problem, should you convenient to fire a PR~? :D

**Comment by wjhuang2016** [comment]
@lysu 
At first I add the code like this in types/parser_driver/value_expr_go:

	if ve, ok := value.(*ValueExpr); ok {
		return ve
	}
	ve := &ValueExpr{}
	ve.SetValue(value)
	types.DefaultTypeForValue(value, &ve.Type)
	**if ve.Type.Tp != mysql.TypeNull {
		ve.Type.Flag |= mysql.NotNullFlag
	}**
	ve.projectionOffset = -1
	return ve

It works well for 1、 1.0 , But when it comes to -1 or 1+1 it doesn't work.
I try to make it work for `select -1;` and `select 1+1;`, can you give me some advises?

**Comment by jackysp** [comment]
Fixed by https://github.com/pingcap/tidb/pull/9689
