### ISSUE TITLE
index data should support shard

### ISSUE THREAD

**Issue by yu34po** [pingcap/tidb#9469]
## Feature Request

**Describe the feature you'd like:**

The hotspot of the table data can solve  by shard_row_id, but the table usually has an index related to data like "creation time", then there may  be  hotspot of the index,  this should be 
performance bottlenecks. shard_row_id can't  solve this

**Comment by jackysp** [comment]
https://github.com/pingcap/tidb/pull/10409 could pre-split index regions. It could be useful for shard index region hotspot.
