### ISSUE TITLE
avoid tikv access historical data

### ISSUE THREAD

**Issue by yu34po** [pingcap/tidb#9471]
## Feature Request

Tikv may access historical data. If the expired data is not gc  in time, it will be queried by tikv as tidb query, which takes much more time with large amounts of historical data scan .

**Comment by jackysp** [comment]
TiKV scans data from the new version to the old, the data need-to-GC does not have much impact. If there are too many versions of data and the snapshot is too old, it will affect the performance.

**Comment by jackysp** [comment]
TiKV scans data from the new version to the old, the data need-to-GC does not have much impact. If there are too many versions of data and the snapshot is too old, it will affect the performance.
