### ISSUE TITLE
TOO SLOW WITH DDL

### ISSUE THREAD

**Issue by victorggsimida** [pingcap/tidb#9490]
## Performance Questions

- What version of TiDB are you using?

```SQL
| Release Version: v2.0.11
Git Commit Hash: 83889a5d821f40412be1af2ad2f2393737f517fd
Git Branch: release-2.0
UTC Build Time: 2019-01-03 09:27:12
GoVersion: go version go1.11.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |
```
- What's the observed and your expected performance respectively?
ddl  performance

- Have you compared TiDB with other databases? If yes, what's their difference?

drop table  is extremely  slow.

```SQL
mysql> drop table test;
Query OK, 0 rows affected (1 min 8.08 sec)

mysql> create table test(a int(11));
Query OK, 0 rows affected (19.12 sec)

mysql> drop table test;
Query OK, 0 rows affected (1 min 20.01 sec)
```

what I do before I found this problem

1. add pd new node : 3 node . 
2. transfer leader to new node: member transfer 
3. delete 3pd old node: member delete name ...

After doing this ,I found that ddl is stalled in tidb cluster. And I restart the tidb servers.

But yesterday: I found: drop table is still very slow 

- For a specific slow SQL query, please provide the following information:
    - Whether you analyzed the tables involved in the query and how long it is after you ran the last `ANALYZE`.
    - Whether this SQL query always or occasionally runs slowly.
    - The `EXPLAIN ANALYZE` result of this query if your TiDB version is higher than 2.1, or you can just provide the `EXPLAIN` result.
    - The plain text of the SQL query and table schema so we can test it locally. It would be better if you can provide the dumped statistics information.
        
        
    - The `EXPLAIN` result of the compared database. For MySQL, `EXPLAIN format=json`'s result will be more helpful.
    - Other information that is useful from your perspective.

- For a general performance question, e.g. the benchmark result you got by yourself is not expected, please provide the following information:
    - Your cluster's topology architecture.
    - A simple description of you workload.
    - The metrics PDF generated from Grafana monitor. Remember to set the time range to the performance issue duration.

**Comment by zimulala** [comment]
@victorggsimida 
Thanks for your report!
You can refer to situations described in https://github.com/pingcap/docs/blob/master/FAQ.md#why-it-is-very-slow-to-run-ddl-statements-sometimes

**Comment by victorggsimida** [comment]
@zimulala   
I meet  the problem  after the pd server restart  and  the problem continues happening for three days.

**Comment by zimulala** [comment]
@victorggsimida 
Could you tell me how many TiDB in this cluster？

**Comment by victorggsimida** [comment]
@zimulala   12 tidb servers.

**Comment by victorggsimida** [comment]
the  problem of running "drop table"  is solved by itself after four days .

**Comment by XuHuaiyu** [comment]
hi, @victorggsimida 
1. To find the root cause, we need to run `admin show ddl` on every tidb-server.
The result of this SQL would like this:
``` sql
tidb> admin show ddl;
+------------+--------------------------------------+------+--------------------------------------+
| SCHEMA_VER | OWNER                                | JOB  | SELF_ID                              |
+------------+--------------------------------------+------+--------------------------------------+
|        133 | 5676ab76-bee3-4a11-9f46-e8b049c3a1b3 |      | 5676ab76-bee3-4a11-9f46-e8b049c3a1b3 |
+------------+--------------------------------------+------+--------------------------------------+
1 row in set (0.00 sec)
```
2. When finding `OWNER` == `SELF_ID`, if possible, please provide use the log of this tidb-server to see what happened during the slow-drop-table period.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you are continuing to experience issues. Thanks!
