### ISSUE TITLE
support all window functions 

### ISSUE THREAD

**Issue by lamxTyler** [pingcap/tidb#9499]
After https://github.com/pingcap/tidb/pull/9450, the window function framework is almost done. We need to support all window functions under that framework, which includes:

- [x] CUME_DIST(https://github.com/pingcap/tidb/pull/9619)
- [x] DENSE_RANK(https://github.com/pingcap/tidb/pull/9500)
- [x] FIRST_VALUE(https://github.com/pingcap/tidb/pull/9560)
- [x] LAG(https://github.com/pingcap/tidb/pull/9672)
- [x] LAST_VALUE(https://github.com/pingcap/tidb/pull/9560)
- [x] LEAD(https://github.com/pingcap/tidb/pull/9672)
- [x] NTH_VALUE(https://github.com/pingcap/tidb/pull/9596)
- [x] NTILE(https://github.com/pingcap/tidb/pull/9682)
- [x] PERCENT_RANK(https://github.com/pingcap/tidb/pull/9671)
- [x] RANK(https://github.com/pingcap/tidb/pull/9500)
- [x] ROW_NUMBER(https://github.com/pingcap/tidb/pull/9098)

**Comment by hhxcc** [comment]
@lamxTyler May I take some functions to do ?

**Comment by lamxTyler** [comment]
@hhxcc Of course! You can mark the functions that you want to take in the description. Thanks!

**Comment by vkingnew** [comment]
Does Common Table Expression (with statement) support? And when release CTE functions and windows functions?

**Comment by lamxTyler** [comment]
@vkingnew Window function will be released in 3.0. Common table expression is not yet supported, you can take a look at https://github.com/pingcap/tidb/issues/6824.

**Comment by vkingnew** [comment]
@lamxTyler  CTE is used  more frequently then windows functions,Desire it to support In version 3. Come on！
