### ISSUE TITLE
Compared to mysql insertion performance, TIDB is about 10 times lower than it.

### ISSUE THREAD

**Issue by lchb369** [pingcap/tidb#9505]
在4核8G的物理机上同时安装
Mysql:
Server version: 5.5.60-MariaDB MariaDB Server
TIDB:
Server version: 5.7.10-TiDB-v3.0.0-beta-27-g6398788 MySQL Community Server (Apache License 2.0)

测试脚本,循环插入1000条数据

$row=[
   'name'=>'name',
   'sex'=>'1',
   'age'=>11,
   'address'=>'dddddd',
   'email'=>'fff@qq.com'
];
testInsert($db,$row);
function testInsert($db,$row){
$start=microtime(true);
for($i=0;$i<1000;$i++){
        $row['age']=rand(10,70);
        $row['name']='name'.$i;
        $db->insert("test",$row);
}
$cost=microtime(true)-$start;
echo $cost;
}

运行结果:
mysql:2.194s
tidb:22.706s

tidb写入性能比mysql慢10倍左右。为什么相差有这么大。

dstat对系统监控状况:

1,没有跑脚本的情况下
----total-cpu-usage---- -dsk/total- ---load-avg--- ------memory-usage----- -net/total- ---procs--- ----swap--- ---system-- ----system----
usr sys idl wai hiq siq| read  writ| 1m   5m  15m | used  buff  cach  free| recv  send|run blk new| used  free| int   csw |     time     

  1   1  99   0   0   0|   0     0 |0.41 0.20 0.17|2929M  144M 3472M 1277M|1932B 2566B|  0   0 2.0|   0     0 |1776  2131 |28-02 15:46:41
  1   1  99   0   0   0|   0     0 |0.41 0.20 0.17|2929M  144M 3472M 1277M|  15k   17k|  0   0   0|   0     0 |1955  2529 |28-02 15:46:42
  1   0  99   0   0   0|   0    44k|0.41 0.20 0.17|2929M  144M 3472M 1277M|5206B 6078B|  0   0   0|   0     0 |1880  2434 |28-02 15:46:43
  1   1  98   0   0   0|   0     0 |0.38 0.20 0.17|2929M  144M 3472M 1277M|4648B 5506B|  0   0  90|   0     0 |2558  3322 |28-02 15:46:44
  1   1  99   0   0   0|   0     0 |0.38 0.20 0.17|2929M  144M 3472M 1277M|  16k   17k|  0   0   0|   0     0 |1893  2403 |28-02 15:46:45
  1   1  98   0   0   0|   0   140k|0.38 0.20 0.17|2931M  144M 3472M 1275M|  10k   11k|  0   0 3.0|   0     0 |2118  2615 |28-02 15:46:46
  1   1  98   0   0   0|   0    48k|0.38 0.20 0.17|2930M  144M 3472M 1276M|3848B 4016B|  0   0   0|   0     0 |1778  2141 |28-02 15:46:47
  1   0  99   0   0   0|   0     0 |0.38 0.20 0.17|2930M  144M 3472M 1276M|  16k   18k|  0   0   0|   0     0 |2048  2613 |28-02 15:46:48
  1   1  99   0   0   0|   0    80k|0.35 0.19 0.17|2930M  144M 3472M 1276M|4784B 5630B|  0   0   0|   0     0 |1826  2287 |28-02 15:46:49
  3   2  90   5   0   0|   0   796k|0.35 0.19 0.17|2934M  145M 3472M 1272M|  73k   78k|  0 1.0 2.0|   0     0 |4571  7082 |28-02 15:46:50

2,向TIDB插入数据时
----total-cpu-usage---- -dsk/total- ---load-avg--- ------memory-usage----- -net/total- ---procs--- ----swap--- ---system-- ----system----
usr sys idl wai hiq siq| read  writ| 1m   5m  15m | used  buff  cach  free| recv  send|run blk new| used  free| int   csw |     time     
  0   0 100   0   0   0| 112B   17k|0.23 0.24 0.19|2932M  145M 3474M 1272M|   0     0 |0.0   0 2.6|   0     0 | 664   763 |28-02 15:48:24
  1   1  98   1   0   0|   0    32k|0.23 0.24 0.19|2932M  145M 3474M 1272M|7482B 8088B|1.0   0   0|   0     0 |2022  2581 |28-02 15:48:25
  1   1  98   0   0   0|   0     0 |0.23 0.24 0.19|2932M  145M 3474M 1272M|7021B 8162B|  0   0 2.0|   0     0 |1925  2366 |28-02 15:48:26
  5   2  87   6   0   0|   0   972k|0.23 0.24 0.19|2936M  145M 3474M 1268M| 102k  111k|1.0   0 2.0|   0     0 |5625  8822 |28-02 15:48:27
  6   4  72  17   0   1|   0  2672k|0.23 0.24 0.19|2936M  145M 3474M 1268M| 218k  239k|  0 1.0   0|   0     0 |  12k   20k|28-02 15:48:28
  6   5  70  19   0   1|   0  2440k|0.37 0.27 0.20|2937M  145M 3474M 1267M| 199k  219k|  0 1.0  90|   0     0 |  12k   20k|28-02 15:48:29
  6   5  70  19   0   1|   0  2668k|0.37 0.27 0.20|2937M  145M 3474M 1267M| 216k  237k|  0 1.0   0|   0     0 |  12k   20k|28-02 15:48:30
  7   5  70  18   0   1|   0  3080k|0.37 0.27 0.20|2937M  145M 3474M 1267M| 249k  274k|  0 1.0 2.0|   0     0 |  15k   23k|28-02 15:48:31
  5   5  70  19   0   1|   0  2532k|0.37 0.27 0.20|2937M  145M 3474M 1267M| 207k  227k|3.0   0   0|   0     0 |  12k   19k|28-02 15:48:32
  7   4  70  18   0   1|   0  2740k|0.37 0.27 0.20|2937M  145M 3474M 1267M| 231k  253k|  0 1.0   0|   0     0 |  13k   21k|28-02 15:48:33
  6   5  70  18   0   1|   0  3064k|0.75 0.35 0.23|2937M  145M 3474M 1267M| 244k  269k|  0 1.0   0|   0     0 |  14k   23k|28-02 15:48:34
  6   5  70  18   0   1|   0  2832k|0.75 0.35 0.23|2937M  145M 3474M 1266M| 234k  257k|  0 1.0   0|   0     0 |  14k   22k|28-02 15:48:35
  8   5  68  18   0   1|   0  2712k|0.75 0.35 0.23|2937M  145M 3474M 1266M| 241k  259k|1.0 1.0 2.0|   0     0 |  14k   22k|28-02 15:48:36
  6   5  70  19   0   1|   0  2820k|0.75 0.35 0.23|2937M  145M 3474M 1266M| 209k  229k|  0 1.0   0|   0     0 |  13k   20k|28-02 15:48:37^C

3,向Mysql插入数据时
----total-cpu-usage---- -dsk/total- ---load-avg--- ------memory-usage----- -net/total- ---procs--- ----swap--- ---system-- ----system----
usr sys idl wai hiq siq| read  writ| 1m   5m  15m | used  buff  cach  free| recv  send|run blk new| used  free| int   csw |     time     
  0   0 100   0   0   0| 112B   17k|0.91 0.50 0.30|5710M 60.6M 1888M  164M|   0     0 |  0   0 2.6|   0     0 | 664   763 |28-02 15:50:03
  2   2  96   0   0   0|   0    72k|0.83 0.50 0.30|5710M 60.6M 1888M  164M|  21k  734k|  0   0   0|   0     0 |3160  3787 |28-02 15:50:04
  1   1  97   0   0   0|   0    16k|0.83 0.50 0.30|5710M 60.6M 1888M  164M|  23k  686k|  0   0   0|   0     0 |3247  3991 |28-02 15:50:05
  3   2  84  12   0   0|4076k  484k|0.83 0.50 0.30|5713M 60.6M 1892M  157M|  42k  720k|  0 1.0 3.0|   0     0 |4241  5372 |28-02 15:50:06
  2   2  74  22   0   0|  36k 1144k|0.83 0.50 0.30|5714M 60.6M 1892M  156M|  23k  709k|1.0 1.0 2.0|   0     0 |5072  6906 |28-02 15:50:07
  2   2  74  21   0   1|  40k 1304k|0.83 0.50 0.30|5714M 60.6M 1892M  156M|  23k  671k|2.0   0   0|   0     0 |5025  6791 |28-02 15:50:08
  5   2  72  20   0   1|2908k 1272k|0.85 0.50 0.30|5709M 60.6M 1895M  158M|  63k  774k|  0   0   0|   0     0 |5851  8278 |28-02 15:50:09
  2   1  97   1   0   0|   0   736k|0.85 0.50 0.30|5706M 60.6M 1895M  162M|  20k  699k|  0   0   0|   0     0 |3153  3542 |28-02 15:50:10
  2   2  97   0   0   0|1472k   16k|0.85 0.50 0.30|5705M 60.6M 1896M  161M|  22k  691k|  0   0   0|   0     0 |3235  3921 |28-02 15:50:11
  2   1  97   0   0   0|   0     0 |0.85 0.50 0.30|5705M 60.6M 1896M  160M|  28k  704k|  0   0 2.0|   0     0 |3191  3704 |28-02 15:50:12^

可以看到tidb运行时---system-- 的int和csw都非常高。而mysql还比较平缓。在写入磁盘的数据量上，tidb也比mysql大一倍左右。

上下文切换相当高 。比较怀疑代码质量。。。应该还有优化空间。

**Comment by zimulala** [comment]
@lchb369 
Thanks for your feedback！
You can check if these links([faq1](https://github.com/pingcap/docs/blob/master/FAQ.md#whats-the-relationship-between-the-tidb-cluster-capacity-qps-and-the-number-of-nodes-how-does-tidb-compare-to-mysql), [faq2](https://github.com/pingcap/docs/blob/master/FAQ.md#the-performance-test-of-mysql-and-tidb-by-our-dba-shows-that-the-performance-of-a-standalone-tidb-is-not-as-good-as-mysql)) can help you.

**Comment by AndrewDi** [comment]
Mysql是写一份，tidb是写三份，单机的mysql基本上只有少量的上下文切换。。。tidb默认就会存在大量rpc调用，所以这些小数据量完全测试不出来的。

**Comment by morgo** [comment]
This benchmark also appears to be single threaded, which is [documented under compatibility](https://www.pingcap.com/docs/sql/mysql-compatibility/#single-threaded-workloads) as not a good use for TiDB.

I recommend using sysbench to test this instead. This workload is closest to sysbench update-index.  You can find our numbers for TiDB 2.1 [here](https://github.com/pingcap/docs/blob/master/benchmark/sysbench-v3.md).  We will update with TiDB 3.0 BETA results soon.

**Comment by lchb369** [comment]
感谢回复，我换个2.1版本，重新测试一下。

**Comment by morgo** [comment]
Sysbench results for TiDB 3.0 beta are [now available](https://github.com/pingcap/docs/blob/master/benchmark/sysbench-v4.md).

**Comment by jackysp** [comment]
It seems that there has been no update for a while, I will close this issue first. Please feel free to open if you have any updates. @lchb369
