### ISSUE TITLE
`go get latest` get v2.0.11 instead of v2.1.5 

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb#9519]
## Bug Report

1. What did you do?
`go get github.com/pingcap/tidb@latest`

2. What did you expect to see?
`github.com/pingcap/tidb v2.1.5+incompatible`

3. What did you see instead?
`github.com/pingcap/tidb v2.0.11+incompatible`

**Comment by XuHuaiyu** [comment]
related issue:
https://github.com/golang/go/issues/30499

**Comment by XuHuaiyu** [comment]
Need investigation

**Comment by tisonkun** [comment]
@rleungx is it still valid? From my local env it returns 

```
go: downloading github.com/pingcap/tidb v1.1.0-beta
go: downloading github.com/pingcap/tidb v2.0.11+incompatible
```

cc @zhouqiang-cl

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
