### ISSUE TITLE
Query returns duplicated result

### ISSUE THREAD

**Issue by shengbinxu** [pingcap/tidb#9525]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
执行sql : 
`select id,task_id from $table_name where task_id in (id1,id2,id3...) ORDER BY work_time, index_id;` 
说明：
     - sql的长度390k (in条件数量1万多个)
     - id是主键

2. What did you expect to see?
同一条记录(主键id相同)，出现一次

3. What did you see instead?
同一条记录(主键id相同)，在返回结果中出现多次
![image](https://user-images.githubusercontent.com/3232275/53630654-8a2e1380-3c4b-11e9-9b31-d1871a43abc7.png)

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
5.7.10-TiDB-v2.0.0

**Comment by XuHuaiyu** [comment]
Hi, @shengbinxu 
Can you provide us the following things:
1. The schema of this `show create table $table_name`?
2. The result of `select tidb_version()`?;
3. How does the data be inserted into the table? use `insert into $table_name values` or `load data ..` or others?
4. The result of `select _tidb_rowid, id from $table_name where id = 836767 or id = 6768 and task_id in (id1,id2,id3...);`

**Comment by jackysp** [comment]
If you can, execute `admin check table $table_name` and provide the results of it. @shengbinxu 
Thanks!

**Comment by shengbinxu** [comment]
@XuHuaiyu 
1.
show create table fpm_turing_work_log;

| fpm_turing_work_log | CREATE TABLE `fpm_turing_work_log` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `sid` varchar(64) NOT NULL COMMENT '',
  `iid` varchar(64) NOT NULL COMMENT '',
  `source` varchar(64) NOT NULL COMMENT '',
  `source_type` varchar(64) NOT NULL COMMENT '',
  `business_type` varchar(64) NOT NULL COMMENT '',
  `sub_business_type` varchar(64) NOT NULL COMMENT '',
  `action` varchar(64) NOT NULL COMMENT '状态(操作类型)',
  `msg` text DEFAULT NULL COMMENT '操作备注',
  `status` varchar(64) NOT NULL COMMENT '操作结果',
  `operator_comment` text DEFAULT NULL COMMENT '操作备注',
  `operator_id` varchar(64) DEFAULT NULL COMMENT '操作人id',
  `operator_name` varchar(64) DEFAULT NULL COMMENT '操作人姓名',
  `operator_hi_name` varchar(64) DEFAULT NULL COMMENT '',
  `operator_company` varchar(128) DEFAULT NULL COMMENT '操作人公司',
  `created_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `process_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '处理时间',
  `processed` int(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '',
  `task_id` varchar(64) DEFAULT NULL,
  `user_id` varchar(64) DEFAULT NULL,
  `work_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `index_id` varchar(64) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `fpm_turing_work_log_created_time` (`created_time`),
  KEY `idx_work_time` (`work_time`),
  KEY `idx_task_id` (`task_id`(10))
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin AUTO_INCREMENT=8190001 COMMENT='' |

2.
select tidb_version();
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                        |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.0.0
Git Commit Hash: 637e130e6a9ba2e54e158131c0466233db39a60e
Git Branch: release-2.0
UTC Build Time: 2018-04-27 11:43:00
GoVersion: go version go1.10 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |
+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.05 sec)

3.
INSERT IGNORE INTO $tablename ( ) VALUES (   ),(   ),(   ),(  )

4.
Unknown column '_tidb_rowid' in 'field list'

If this is not enough, I am more than happy to provide more information.

**Comment by shengbinxu** [comment]
@jackysp 
admin check table fpm_turing_work_log;
ERROR 1105 (HY000): fpm_turing_work_log err:[admin:1]index:&{836761 [{2 0 0 0 1847041026095579136 [] <nil>}]} != record:&{836761 [{13 0 0 0 1847041026095579136 [] {{2019 1 1 0 27 54 0} 12 0}}]}

**Comment by crazycs520** [comment]
@shengbinxu , Can you execute `admin check index fpm_turing_work_log idx_work_time` to check index and data. 

`admin check table fpm_turing_work_log;` return the error is cause by a old bug of admin check, I still can not sure whether exists inconsistancy in index and record. 

So could you run `admin check index fpm_turing_work_log idx_work_time`?

**Comment by lysu** [comment]
@shengbinxu does index `idx_task_id`added after those data be inserted?

maybe take look the result of ` curl http://tidb-server-ip:10080/ddl/history`

thx~

**Comment by jackysp** [comment]
It seems something wrong with `idx_task_id`, you could try `admin check index fpm_turing_work_log idx_task_id` @shengbinxu .

**Comment by shengbinxu** [comment]
@crazycs520 
mysql> admin check index fpm_turing_work_log idx_work_time;
Query OK, 0 rows affected (12.31 sec)

mysql> admin check index fpm_turing_work_log fpm_turing_work_log_created_time  ;
Query OK, 0 rows affected (11.66 sec)

mysql> admin check index fpm_turing_work_log idx_task_id   ;
Query OK, 0 rows affected (35.65 sec)

**Comment by shengbinxu** [comment]
@lysu 
`mysql> alter table fpm_turing_work_log add index idx_task_id(task_id(10));`

yes,index idx_task_id was added after some data be inserted

**Comment by shengbinxu** [comment]
@jackysp

mysql> admin check index fpm_turing_work_log idx_task_id ;
Query OK, 0 rows affected (35.65 sec)

**Comment by jackysp** [comment]
Many thanks, @shengbinxu !
It seems that the data are ok. Did the duplicated values still appear? Or whether the duplicated data in this table has been deleted? Or you can try the following SQLs:
```
begin;
select id from fpm_turing_work_log use index(idx_task_id) where id = 836767;
select id from fpm_turing_work_log where id = 836767;
admin check index fpm_turing_work_log idx_task_id;
rollback;
```

**Comment by shengbinxu** [comment]
@jackysp 
![image](https://user-images.githubusercontent.com/3232275/53783862-58b88f00-3f4e-11e9-9b26-909024df8614.png)

> Did the duplicated values still appear? 

yes

> Or whether the duplicated data in this table has been deleted

the data is not changed, and the data in table never  duplicated , I think The reason of duplicated  output is the tidb bug, Let's look at the example:

1、
![image](https://user-images.githubusercontent.com/3232275/53784061-0b88ed00-3f4f-11e9-8f9b-8ed66f61a654.png)


2、`select id,task_id from $table_name where task_id in (id1,id2,id3...) ORDER BY work_time, index_id;`

![image](https://user-images.githubusercontent.com/3232275/53784115-3115f680-3f4f-11e9-8525-6ebe95f686d4.png)

The first two examples are all I just executed, So I think it`s the bug of tidb Parsing engine

**Comment by jackysp** [comment]
@XuHuaiyu and @zz-jason PTAL

**Comment by winoros** [comment]
@shengbinxu What if you limit the element size of the `IN()` clause? e.g. only contain the value which appears multiple times.

**Comment by zz-jason** [comment]
@shengbinxu Could you post the explain result of the SQL, i.e. execute the following SQL and post the result here:
```sql
explain select id, task_id from $table_name where task_id in (id1,id2,id3...) ORDER BY work_time, index_id;
```

**Comment by shengbinxu** [comment]
@winoros 
1、
`SELECT `id`, `task_id` FROM `fpm_turing_work_log` WHERE (`task_id` IN ('5c0e56ddea206740823ca50a_3170850872', '5c0e56e8ea2067e12d3ca5f9_3170850872', '5c0e63e9ea20679b4d3ca517_3170850872', '5c0e6483ea2067e6863ca59e_3170850872', '5c0e6495ea2067cf9c3ca908_3170850872', '5c0e6495ea206764693cb026_3170850872', '5c0e649bea206771173ca471_3170850872', '5c0e64efea2067b23b3ca888_3170850872', '5c0e7213ea2067614d3ca825_3170850872', '5c0e7237ea206751163ca80b_3170850872')) AND (user_id <> 9999999);`
![image](https://user-images.githubusercontent.com/3232275/53792643-1bacc680-3f67-11e9-8ce1-7b0c344b09ae.png)

2、
`SELECT `id`, `task_id` FROM `fpm_turing_work_log` WHERE task_id in('5c0e6495ea2067cf9c3ca908_3170850872','5c0e6495ea206764693cb026_3170850872') AND (user_id r_id <> 9999999);`
![image](https://user-images.githubusercontent.com/3232275/53792834-89f18900-3f67-11e9-8212-7d35399cc1e3.png)

and the explain result is:
![image](https://user-images.githubusercontent.com/3232275/53793139-3469ac00-3f68-11e9-8ff6-b648b2ca7da6.png)


3、
![image](https://user-images.githubusercontent.com/3232275/53792955-e0f75e00-3f67-11e9-90f0-4baf7766ba95.png)

this is ok 

4、
![image](https://user-images.githubusercontent.com/3232275/53792929-cf15bb00-3f67-11e9-94a8-a1966402c05e.png)

this is ok

**Comment by shengbinxu** [comment]
@zz-jason 
Look at my previous comment

**Comment by shengbinxu** [comment]
@winoros  thank you very much !
what do you mean is the issue is prefix index,
if I upgrade the tidb , or
if I change 
`alter table fpm_turing_work_log add index idx_task_id(task_id(10));` 
to 
`alter table fpm_turing_work_log add index idx_task_id(task_id);`,
 and it will work?

**Comment by shenli** [comment]
@shengbinxu We suggest upgrading your cluster to the latest release: 2.0.11 or 2.1.5.
If you want to upgrade to 2.1.x, please refer to the [release note](https://github.com/pingcap/docs/blob/master/v2.1/releases/2.1ga.md#upgrade-caveat).

**Comment by winoros** [comment]
@shengbinxu Yes, alter table and change the index to the one without prefix column will also help.

**Comment by shengbinxu** [comment]
@shenli  ok
