### ISSUE TITLE
when I use lightning, I get some error with database name.

### ISSUE THREAD

**Issue by AIKiller** [pingcap/tidb#9532]
when I use lightning tool for importing  data to tidb , I got some error, as below picture.
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qimo1ptfj20vk0dtwgm.jpg)
I guess the lightning tool may be not support for chart '-' in database name, so some error encountered.
but I don't search any solutions in faq page.  someone can help me ?

**Comment by tiancaiamao** [comment]
Would you like to provide the full SQL text? I guess it could be found in the TiDB log near this error message.
@AIKiller

**Comment by AIKiller** [comment]
yes, I will provide the all concerned files.
first, the pay-service_micro_db.cash_type-schema.sql include: 
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qjgy2qguj209q07kwel.jpg)
and, the table is empty,so not have sql file.
finally, the tidb.log  as below picture
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qjniqc9pj21ed0megpr.jpg)

I use navicat to check the database information in tidb, I can found the database and table.
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qjpenwyoj20l40hzt9w.jpg)

This shows that the operation of creating the database and the table has been completed, but there is still a unknown error. and the import program is interrupted.
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qjt18iwcj20zv0aiacx.jpg)

**Comment by AIKiller** [comment]
but, I got same error with orther table in same database.
the sql file is :
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qkcwqwaej21ge0mijyx.jpg)
and the schema content is:
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qke2r1ljj20ch0aoq37.jpg)
but not found some error in tidb.log
the lightning tool show as below picture:
![](http://ww1.sinaimg.cn/large/93d61c99ly1g0qkfxsiczj20w50dudhz.jpg)
can you help me ? thank.  @tiancaiamao

**Comment by WangXiangUSTC** [comment]
I will take a look @AIKiller

**Comment by WangXiangUSTC** [comment]
could you please provide the lightning version by execute `tidb-binlog -V`? @AIKiller

**Comment by AIKiller** [comment]
I'm sory that I use TiDB-Lightning for fast full import of large amounts of data into a TiDB cluster. and don't deploy 'TiDB-Binlog' tool ,so I can't found ‘tidb-binlog ’ file 
but I have got version about  tidb-lightning -V 

Release Version: v2.1.4
Git Commit Hash: 10b9033448798c57b1f97cbcba02030673be4495
Git Branch: release-2.1
UTC Build Time: 2019-02-15 09:16:31
Go Version: go version go1.11.2 linux/amd64
@WangXiangUSTC

**Comment by WangXiangUSTC** [comment]
I'm sorry, I mean `tidb-lightning -V`

**Comment by AIKiller** [comment]
It doesn't matter.  and the result of  `tidb-lightning -V` is:
Release Version: v2.1.4
Git Commit Hash: 10b9033448798c57b1f97cbcba02030673be4495
Git Branch: release-2.1
UTC Build Time: 2019-02-15 09:16:31
Go Version: go version go1.11.2 linux/amd64

**Comment by WangXiangUSTC** [comment]
it seems we need add quote for database in https://github.com/pingcap/tidb/blob/0267a7fbdf1c8564daca066df116c51a28ad773c/util/kvencoder/kv_encoder.go#L228

**Comment by kennytm** [comment]
Thanks for the issue report @AIKiller, we're going to fix this in v2.1.6.

Alternatively, you could also rename the database to not include the hyphen to workaround the bug.
