### ISSUE TITLE
How to synchronize tikv data to a `mocktikv` based tidb which act as a memory cache?

### ISSUE THREAD

**Issue by shenlijungg** [pingcap/tidb#9535]
question:
如何将分布式tikv数据同步到其中一台tidb mocktikv 作为memory ？
select version()
5.7.10-TiDB-v2.1.0-5-g4dad722

5 tidb    其中一个是mocktikv,  想做缓存库。
6 tikv
3 pd

**Comment by tiancaiamao** [comment]
Do you mean you have 5 tidb and want to use one of them as a cache layer? Read data from this TiDB is an in-memory operation and the result always keep the same with the cluster? @shenlijungg 
...
If so, there is no such setting.

**Comment by shenlijungg** [comment]
@tiancaiamao  是的。有没有其他架构思路吗。目前有先表数据只有百万级别，有先表示千万级别。百万级别的表查询的时候分布式效率并不高，打算使用内存表，或单机数据库解决。问题是单机的高可用，和多个数据源数据同步的问题。

**Comment by tiancaiamao** [comment]
No solution for this yet.

If you have some **small, hot** tables, you may consider add a cache layer in the logic of the product.

**Comment by shenlijungg** [comment]
@tiancaiamao 谢谢
