### ISSUE TITLE
TIDB-Lightning问题

### ISSUE THREAD

**Issue by longhuguoji** [pingcap/tidb#9538]
版本：http://download.pingcap.org/tidb-v2.1.5-linux-amd64.tar.gz
原因：当时提出在issue提出bug后（9269），在2.1.5进行了修复。
现存在的问题：
我用2.1.5进行导入，创建完表之后，就不执行了，所有表一条数据都没有导入。有个A表只有13条数据也没有导入。tidb-lijghtning没有错误日志，tikv-importer重复打印如下日志：
WARN kv_service.rs:157: send rpc response: RemoteStopped

**Comment by WangXiangUSTC** [comment]
seems same with https://github.com/pingcap/tidb/issues/9269
