### ISSUE TITLE
tikv-server fails to start and reports "illegal instruction"

### ISSUE THREAD

**Issue by mark988** [pingcap/tidb#9543]
./tikv-server --pd="127.0.0.1:2379" --data-dir=tikv --log-file=tikv.log
执行上面的指令，报错如下，
Illegal instruction (core dumped)

**Comment by tiancaiamao** [comment]
PTAL @rleungx

**Comment by mark988** [comment]
请问怎么解决？

**Comment by mark988** [comment]
环境使用的是 center os  7  .     软件是最新版本。  使用wget http://download.pingcap.org/tidb-latest-linux-amd64.tar.gz 获取的最新版本

**Comment by mark988** [comment]
能不能留个QQ聊一下？  或者加我的一下也可以。QQ:80692072

**Comment by rleungx** [comment]
@mark988 Thanks for your feedback!
The related issue can be found here: https://github.com/tikv/tikv/issues/2874.

**Comment by nullnotnil** [comment]
I am going to close this as a duplicate of https://github.com/tikv/tikv/issues/2874 Thanks!
