### ISSUE TITLE
syncer close by main.go:69: [info] got signal [hangup], exit

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9549]
使用 syncer来同步Mysql(5.6) 到， tidb,  一共有两个tidb， 其中有一个运行一段时间（如一天）之后就会自动exit, 重新启动又能继续跑没具体业务异常输出， syncer.log 打印这个：
2019/03/05 02:11:16 main.go:69: [info] got signal [hangup], exit

**Comment by shenli** [comment]
@ericisme Thanks for your feedback!
Please keep/fill the issue template and try to [search in our document](https://github.com/pingcap/docs/search?utf8=%E2%9C%93&q=hangup&type=).

**Comment by ericisme** [comment]
@shenli thanks a lot

**Comment by WangXiangUSTC** [comment]
syncer exit because got signal hangup, what is your command to run syncer? do you forgot add run with nohup? @ericisme

**Comment by ericisme** [comment]
@WangXiangUSTC  yes, i using nohup directly on shell command, 
 but as shenli says:
  @ericisme Thanks for your feedback!
Please keep/fill the issue template and try to search in our document.

now, i put the nohup command in to a start_syncer.sh scrpit,  and now it is running, i will check if it will cash in feature times.

**Comment by WangXiangUSTC** [comment]
ok, you can run like `nohup  start_syncer.sh` @ericisme
