### ISSUE TITLE
ERROR 1105 (HY000): inconsistent extra index PRIMARY

### ISSUE THREAD

**Issue by jinruin** [pingcap/tidb#9550]
CREATE TABLE `sys_dept` (
  `id` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

CREATE TABLE `sys_user` (
  `plat` varchar(255) NOT NULL,
  `id` varchar(255) NOT NULL,
  `dept` int(11) DEFAULT NULL,
  PRIMARY KEY (`plat`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

insert into sys_dept values(1, 'xian');
insert into sys_dept values(2, 'shanghai');

insert into sys_user values('p', 'mofy', 1);
insert into sys_user values('p', 'yangyy', 2);

delete from sys_user where dept in(select id from sys_dept where name = 'shanghai');

select count(*) from sys_user where plat= 'p' and id = 'yangyy';
count should return 0, but return 1 instead.

select * from sys_user where plat= 'p' and id = 'yangyy';
should return Empty set, but return ERROR 1105 (HY000): inconsistent extra index PRIMARY

**Comment by XuHuaiyu** [comment]
Hi, @jinruin 
Can you provide us the result of `select tidb_version()`?

**Comment by jinruin** [comment]
Release Version: v2.1.0-rc.3-294-g6e2d6c7

**Comment by jinruin** [comment]
would you give me the link for the fixed issue and commit id

**Comment by shenli** [comment]
@jinruin https://github.com/pingcap/tidb/issues/8853

**Comment by shenli** [comment]
@jinruin Feel free to reopen this issue if you meet any other problem.
