### ISSUE TITLE
Unexpected error when using window function and view

### ISSUE THREAD

**Issue by winoros** [pingcap/tidb#9552]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
CREATE VIEW v AS
SELECT i, j, MIN(i+j) OVER (ORDER BY j DESC ROWS UNBOUNDED PRECEDING) min,
      MAX(i+j) OVER (ORDER BY j DESC ROWS UNBOUNDED PRECEDING) max FROM t;
SHOW CREATE VIEW v;
SELECT * FROM v;
```

2. What did you expect to see?

All query worked.

3. What did you see instead?

parser error when running `SELECT * FROM v`.
`ERROR 1105 (HY000): line 1 column 28 near "(ORDER BY j DESC ROWS UNBOUNDED PRECEDING) min,       MAX(i+j) OVER (ORDER BY j DESC ROWS UNBOUNDED PRECEDING) max FROM t"`

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

master e7ff050a453c8b8564b30c7c55b993a11c44b1d9

**Comment by AndrewDi** [comment]
@winoros I will fix this bug...Let me do some research.
