### ISSUE TITLE
Transaction behavior is not as what the doc  have described

### ISSUE THREAD

**Issue by ihipop** [pingcap/tidb#9561]
## General Question

https://github.com/pingcap/docs/blob/84acfa3/sql/transaction-isolation.md#statement-rollback

said that

>  If you execute a statement within a transaction, the statement does not take effect when an error occurs.
> ```
> begin;
> insert into test values (1);
> insert into tset values (2);  // This statement does not take effect because "test" is misspelled as "tset".
> insert into test values (3);
> commit;
> ```
> In the above example, the second insert statement fails, while the other two insert statements (1 & 3) can be successfully committed.
> 

I write some test

DDL:
```sql
CREATE TABLE `test_1` (
  `test` varchar(255) NOT NULL,
  PRIMARY KEY (`test`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```
```sql
CREATE TABLE `test_2` (
  `test` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

code:
```php
$pdo->createCommand('
begin;
INSERT INTO `test_1` VALUES (1);//SQL1
INSERT INTO `test_2` VALUES (1);//SQL2
INSERT INTO `test_1` VALUES (1);//SQL3
INSERT INTO `test_2` VALUES (1);//SQL4
commit;
')->execute();
```
 
as your doc  described, `SQL3` will fail, because of duplicate primary key,
SQL1,SQL2,SQL4 will success
but, actually they both fail.

What's wrong ?

```sql
show VARIABLES like 'version'
```
`
5.7.10-TiDB-v2.1.0-beta-273-gf3325e2
`

**Comment by jackysp** [comment]
It is by design for performance. The behavior is not exactly the same as MySQL.

**Comment by ihipop** [comment]
> It is by design for performance. The behavior is not exactly the same as MySQL. TiDB will check all the unique constraint for insert statement when the transaction commits.
> Thanks for your attention, @ihipop !


@jackysp **Please note that the test  above is against the  `5.7.10-TiDB-v2.1.0-beta-273-gf3325e2` not `Mysql`**

`table_2` doesn't have primary key constraint. according to  your Doc https://github.com/pingcap/docs/blob/84acfa3/sql/transaction-isolation.md#statement-rollback ,Every failed SQL won't affect other SQL to be commit. 

And I write this test below just like your doc, it didn't pass the test also.

```php
$pdo->createCommand('
begin;
INSERT INTO `test_2` VALUES (1);//`table_2` doesn't have primary key constraint. this should success according to the TIDB doc
INSERT INTO `test_3` VALUES (1);//table`test_3` is not exists
INSERT INTO `test_2` VALUES (1);//`table_2` doesn't have primary key constraint. this should success according to the TIDB doc
commit;
')->execute();
```
Maybe there is something wrong with your Doc or tidb

**Comment by jackysp** [comment]
> > It is by design for performance. The behavior is not exactly the same as MySQL. TiDB will check all the unique constraint for insert statement when the transaction commits.
> > Thanks for your attention, @ihipop !
> 
> @jackysp **Please note that the test above is against the `5.7.10-TiDB-v2.1.0-beta-273-gf3325e2` not `Mysql`**

**I really note that it is not `MySQL`.**
I've tested your question on the same commit version.
```
mysql> truncate table test_1;
Query OK, 0 rows affected (0.01 sec)

mysql> truncate table test_2;
Query OK, 0 rows affected (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO `test_1` VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO `test_2` VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO `test_1` VALUES (1);
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql> INSERT INTO `test_2` VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test_1;
+------+
| test |
+------+
| 1    |
+------+
1 row in set (0.00 sec)

mysql> select * from test_2;
+------+
| test |
+------+
| 1    |
| 1    |
+------+
2 rows in set (0.00 sec)

mysql> show create table test_1;
+--------+--------------------------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                                         |
+--------+--------------------------------------------------------------------------------------------------------------------------------------+
| test_1 | CREATE TABLE `test_1` (
  `test` varchar(255) NOT NULL,
  PRIMARY KEY (`test`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+--------+--------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> show create table test_2;
+--------+------------------------------------------------------------------------------------------------------------------+
| Table  | Create Table                                                                                                     |
+--------+------------------------------------------------------------------------------------------------------------------+
| test_2 | CREATE TABLE `test_2` (
  `test` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin |
+--------+------------------------------------------------------------------------------------------------------------------+
1 row in set (0.01 sec)

mysql> select tidb_version();
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| tidb_version()                                                                                                                                                                                                                                                                                                                   |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Release Version: v2.1.0-beta-273-gf3325e272
Git Commit Hash: f3325e272deee54e9ea394335f486b103e6a8aad
Git Branch: HEAD
UTC Build Time: 2019-03-06 02:20:34
GoVersion: go version go1.12 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)

mysql> 
```
I think it is not the same as your question. But if there is already a duplicated row in test_1, it will be the same as your question, because commit failed. The reason is I've mentioned before.
```
mysql> truncate table test_1;
Query OK, 0 rows affected (0.02 sec)

mysql> truncate table test_2;
Query OK, 0 rows affected (0.01 sec)

mysql> insert into test_1 values (1);
Query OK, 1 row affected (0.00 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO `test_1` VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> INSERT INTO `test_2` VALUES (1);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO `test_1` VALUES (1);
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql> INSERT INTO `test_2` VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> commit;
ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
mysql> select * from test_1;
+------+
| test |
+------+
| 1    |
+------+
1 row in set (0.00 sec)

mysql> select * from test_2;
Empty set (0.00 sec)
```

> And I write this test below just like your doc, it didn't pass the test too.
> 
> ```
> $pdo->createCommand('
> begin;
> INSERT INTO `test_2` VALUES (1);//`table_2` doesn't have primary key constraint. this should success according to the TIDB doc
> INSERT INTO `test_3` VALUES (1);//table `test_3` is not exists
> INSERT INTO `test_2` VALUES (1);//`table_2` doesn't have primary key constraint. this should success according to the TIDB doc
> commit;
> ')->execute();
> ```
> 
> The result is that table `test_2` have nothing inserted.
> According to the TIDB doc,the SQL 1 & 3 should success.
> 
> Maybe there is something wrong with your Doc or tidb

I also tested this case, but cannot reproduce it.
```
mysql> truncate table test_2;
Query OK, 0 rows affected (0.01 sec)

mysql> begin;
Query OK, 0 rows affected (0.00 sec)

mysql> INSERT INTO `test_2` VALUES (1);
Query OK, 1 row affected (0.01 sec)

mysql> INSERT INTO `test_3` VALUES (1);
ERROR 1146 (42S02): Table 'test.test_3' doesn't exist
mysql> INSERT INTO `test_2` VALUES (1);
Query OK, 1 row affected (0.00 sec)

mysql> commit;
Query OK, 0 rows affected (0.00 sec)

mysql> select * from test_2;
+------+
| test |
+------+
| 1    |
| 1    |
+------+
2 rows in set (0.00 sec)
```

Did you notice the `commit` success or not? I think it is the key point. @ihipop

**Comment by tiancaiamao** [comment]
A failed statement should contribute nothing to the transaction.

The given example is a special case, we have an optimization of lazy check for the unique index. Instead of checking the statement every time (which need a network round trip and decrease performance), the check will happen in the end of the commit statement. Then the whole transaction is failed. @ihipop 

Maybe we should update the document @jackysp

**Comment by jackysp** [comment]
Yes, I have not found the introduction of the lazy check in our document. @tiancaiamao

**Comment by ihipop** [comment]
@jackysp I use the native command line mysql client to run both test case ,Only No.2  was passed. 
And I know the reason that  @tiancaiamao have explained now. **You  really should add the  introduction of the lazy check in your document.**
**But** I Just don't understand that why `PDO` driver break the the whole Transaction if any SQL error happens, In test case No.2 ,when use [`Pdo`](http://php.net/manual/en/intro.pdo.php) or other   mysql client (I've tests [Dbeaver](https://dbeaver.io/download/),Navicat) ,They Have alike behavior.Test case No.2 won't pass.
In Navicat: SQL3 wont be executed,SQL1 will be commit and success
In Pdo: All SQL will fail
In  [Dbeaver](https://dbeaver.io/download/): All SQL will fail just like Pdo (They use java mysql driver)

The behavior of Dbeaver and Pdo is more alike to the program in production business,They both use the native driver in their  program language,So,the behavior described in Document will rarely happen in production business，I think. I want to know why very much.

**Comment by jackysp** [comment]
Which case is No.2?

**Comment by ihipop** [comment]
@jackysp the case with the none exists table `test_3`

**Comment by ihipop** [comment]
@jackysp the case with the none exists table test_3

**Comment by ihipop** [comment]
I reproduced Doc's behavior with `Pdo`

```php
$pdo->createCommand('truncate test_2;')->execute();
$pdo->createCommand('
begin;
INSERT INTO `test_2` VALUES ("2-1"); -- SQL 1
INSERT INTO `test_3` VALUES ("3-1"); -- SQL 2 ,table test_3 not exists
INSERT INTO `test_2` VALUES ("2-2"); -- SQL 3
')->execute();
// Then RUN SQL 4 in different context in same connection (The Transaction is not committed yet.)
$pdo->createCommand('
INSERT INTO `test_2` VALUES ("2-3"); -- SQL 4
commit;
')->execute();
```
`SQL 1` / `SQL 4` success be committed, and `SQL 2` /`SQL 3` Failed. Table `test_2` have `2-1` and `2-3` in it finally.

Seems that this driver will stop to execute `SQL 3` when `SQL 2` fail. Not affect with `SQL 1` and `SQL 4` to be committed.
I now understand this behavior.
and ,please update your Doc about **add the introduction of the lazy check** in your document then close this issue. Thanks for your Great Work.

**Comment by jackysp** [comment]
We'll update the docs. Thanks for your attention, @ihipop !
