### ISSUE TITLE
Is there any risk in using m.2 SSD as the storage of TiDB

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9582]
现在的m.2SSD真的很快，而且也很便宜，像760P, 单盘就有有20w的ipos，用来做kv 随机读写
应该很棒，单是 TCL的SSD读写寿命较短， 我看了aliyun有些Mvne的ECS,下面也有注明风险：

“ 当前实例的数据缓存盘是本地盘，有丢失数据的风险（比如 NVMe SSD 故障或宿主机宕机时）如果您的应用不能做到数据可靠性的架构，我们强烈建议您使用云盘搭建您的实例”

而其中的 ”您的应用不能做到数据可靠性的架构“， 我像问如tidb这样带默认3replica的架构，是不是就是数据可靠的架构，如果本身软件有3replica， 再用nvme组raid1 的话，是不是可以用来做tidb的存储设备了。

**Comment by rleungx** [comment]
@ericisme Thanks for your feedback! I found some details about Samsung 970 EVO from https://www.samsung.com/semiconductor/minisite/ssd/product/consumer/970evo:

> * TBW: Terabytes Written
> * Warrantied TBW for 970 EVO: 150 TBW for 250GB model, 300 TBW for 500GB model, 600 TBW for 1TB model, 1,200 TBW for 2TB model.
> * 5-years or TBW, whichever comes first. For more information on the warranty, please find the enclosed warranty statement in the package.

We won't lose data unless two persist storages, which have the two replica of a Region, can not work at the same time. So in theory, it can be used. But for now, we haven't tested m.2 SSD. We cannot guarantee it.

**Comment by morgo** [comment]
I use a 1TB 970 EVO for developing/testing TiDB. It works very well, the only thing you need to know is that it is a consumer category drive.  The TBW statistics are lower than the corresponding 970 PRO.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
