### ISSUE TITLE
unnecessary and annoying warnings printed when eliminating outer join

### ISSUE THREAD

**Issue by eurekaka** [pingcap/tidb#9590]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

```
mysql> create table a(c1 int);
Query OK, 0 rows affected (0.01 sec)

mysql> create table b(c1 int primary key);
Query OK, 0 rows affected (0.01 sec)

mysql> explain select * from a left join b on a.c1 = b.c1;
```
in TiDB log, we can see an empty warning log:
```
2019/03/07 14:51:14.766 rule_join_elimination.go:94: [warning] <nil>
```

2. What did you expect to see?

Not printing this empty log. We need to check if err is not nil before calling `log.Warn(err)` in line 94:
```golang
 86 // check whether schema cols of join's parent plan are all from outer join table
 87 func (o *outerJoinEliminator) isParentColsAllFromOuterTable(outerPlan LogicalPlan, parentSchema *expression.Schema) bool {
 88     if parentSchema == nil {
 89         return false
 90     }
 91     for _, col := range parentSchema.Columns {
 92         columnName := &ast.ColumnName{Schema: col.DBName, Table: col.TblName, Name: col.ColName}
 93         if c, err := outerPlan.Schema().FindColumn(columnName); c == nil {
 94             log.Warn(err)
 95             return false
 96         }
 97     }
 98     return true
 99 }
```

3. What did you see instead?

An empty warning log.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
```
Release Version: v3.0.0-beta-158-g247777d87
Git Commit Hash: 247777d8705fff77773508c833a40f0c00309784
Git Branch: master
UTC Build Time: 2019-03-07 06:49:36
GoVersion: go version go1.11.1 darwin/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
```

**Comment by wjhuang2016** [comment]
I think we shouldn't use log.Warn(err) here since err is not nil normally. Maybe we can use errors.Trace or just ignore it?

**Comment by eurekaka** [comment]
@wjhuang2016 I think we'd better check if the err is nil before taking actions.

**Comment by wjhuang2016** [comment]
@eurekaka Thus we need to modify interfaces of most functions in in rule_join_elimination.go to return the err to "optimize(p LogicalPlan) (LogicalPlan, error)",  for most functions in rule_join_elimination.go don't return nil.

**Comment by eurekaka** [comment]
@wjhuang2016 Oh I mean just make sure the err is not nil before logging it here, but your proposal of refining interfaces for functions in rule_join_elimination.go to return error back is also reasonable I think.
