### ISSUE TITLE
batchCommandsClient might cause a memory leak  

### ISSUE THREAD

**Issue by rleungx** [pingcap/tidb#9604]
## Bug Report
1. What did you do?
After we introduce `batch` mechanism, there might be a memory leak when the store is gone. Under this situation, the goroutine won't exit. See https://github.com/pingcap/tidb/blob/b78490e403c52f58f71150c6d06fba6dc7a2fbbc/store/tikv/client.go#L273

2. What did you expect to see?
goroutine should exit when the store is gone.

3. What did you see instead?
It won't exit.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
master

**Comment by tiancaiamao** [comment]
PTAL @hicqu

**Comment by qw4990** [comment]
Is this problem resolved? @hicqu

**Comment by hicqu** [comment]
It's resolved. `batchSendLoop` will return if its source channel is closed.
