### ISSUE TITLE
syncer: syncer err when sync a table not in [[replicate-do-table]]

### ISSUE THREAD

**Issue by beecep** [pingcap/tidb#9620]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
in config.toml add  [[replicate-do-table]] option , and no replicate-do-db.
but, syncer err , because syncer want to sync a table not in  [[replicate-do-table]] option.

2. What did you expect to see?
in config.toml, if only  [[replicate-do-table]] option,  the syncer just only sync table in  [[replicate-do-table]] option

3. What did you see instead?

![image](https://user-images.githubusercontent.com/18275486/54025856-ca0a7300-41d6-11e9-8be6-083543fffb28.png)

![image](https://user-images.githubusercontent.com/18275486/54025927-09d15a80-41d7-11e9-8ae3-f06b0785fe08.png)

if i want skip the table "t_bas_flex_property_L", i must be add [[replicate-ignore-table]] option ?

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
Release Version: v2.0.11
Git Commit Hash: 83889a5d821f40412be1af2ad2f2393737f517fd
Git Branch: release-2.0
UTC Build Time: 2019-01-03 09:27:12
GoVersion: go version go1.11.2 linux/amd64
TiKV Min Version: 2.0.0-rc.4.1 |

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @amyangfei

**Comment by amyangfei** [comment]
In current syncer implement, when we meet a DDL binlog event, syncer runs as following:
1. parse DDL statement
2. if meets parse error, check if we have configured to skip this DDL (via `skip-ddls` config)
    2.1. if not skip this DDL, return parse error
    2.2. if skip this DDL, continue to execute the next binlog event
3. if no parse error, check if we have configured to do or ignore `schema`.`table` (via `replicate-do-db`, `replicate-do-table`, `replicate-ignore-db`, `replicate-ignore-table`)

So in your case, syncer runs with procedure 1 -> 2 -> 2.1

You could config `skip-ddls = ["^SET\\s+STATEMENT\\smax_statement_time"]` to skip this DDL.

**Comment by jebter** [comment]
The issue has not been updated for too long, so I will close it. If there are any updates, you can reopen it.
