### ISSUE TITLE
tidb-server should support a default -config

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9621]
## Feature Request

**Is your feature request related to a problem? Please describe:**

The `tidb-server` binary does not have a default location that it looks for a configuration file in.  This would be helpful in homebrew support on Linux/Windows (WSL), since homebrew [does not support services](https://github.com/Homebrew/brew/issues/5847).  Expecting someone to type this full path each time is unreasonable:

```
tidb-server -config /usr/local/etc/tidb-server.toml
```

**Describe the feature you'd like:**
```
morgans-mini:etc morgo$ tidb-server -help
Usage of tidb-server:
..
  -config string
        config file path (default "/etc/tidb.toml")
..
```

**Describe alternatives you've considered:**

I could create a shell script wrapper around `tidb-server` to make a single callable binary.  This seems unnecessary.

I could also patch and change the default `path` to the correct location since this is the only thing I really need to change. I will look at doing this as an intermediate solution, but I think it is valuable to have a sample config file that is editable.

**Teachability, Documentation, Adoption, Migration Strategy:**

MySQL does something similar with `/etc/my.cnf`, so it is pretty well understood by users.

**Comment by morgo** [comment]
@kolbe Do you mind working on this?  It will be useful for homebrew.

**Comment by kolbe** [comment]
To summarize the conversation we had on Slack...

I think a default config location is fine, but I think that once you start with this you end up needing to add a tidb-config.d directory, you end up needing to support multiple config files that get merged together, etc.

And adding any of that ultimately is only very meaningful (especially for 3rd-party distros) if you add a build-time option to set the root directory. Different distros are going to want your config files to be in /etc/ or /etc/config.d/ or /usr/local/etc/ or whatever other crazy place.

So this becomes a much bigger project that has more implications than I think certainly I can manage in this one issue.

**Comment by nullnotnil** [comment]
Closing for now (TiUP is easier to use than homebrew). We can re-open if these is demand.
