### ISSUE TITLE
Leader balance ratio and Region balance ratio are 100%?

### ISSUE THREAD

**Issue by wl21787** [pingcap/tidb#9623]
tidb_version = v2.1.5

当我测试tikv集群高可用时，重装tikv节点服务器的系统模拟故障。
tikv state_name=offline，grafana显示Tombstone stores值增加。
但是：
Leader balance ratio and Region balance ratio are 100%?

![image](https://user-images.githubusercontent.com/21055334/54069567-43b46680-4294-11e9-9d50-c5afc5b5c735.png)

我在#9002 看到了相同的问题（tidb_version=2.1.0），官方说会在下个版本更新,可是我的版本是v2.1.5，问题依然存在。

**Comment by lamxTyler** [comment]
Thanks for your feedback! PTAL @nolouch

**Comment by nolouch** [comment]
@wl21787 I did not express it clearly, we plan to reorganize metrics in 3.0.  But this metric is really confusing,  so I should see it as a bug and fix it first. I will give priority to this problem. Thanks for your feedback.

**Comment by nolouch** [comment]
move to  https://github.com/pingcap/pd/issues/1456

**Comment by daikon12** [comment]
请问这个问题 需要等到3.0才会修复吗？现在猜到beta版 ，2.1.6也会有这个问题吗

**Comment by daikon12** [comment]
请问这个问题 需要等到3.0才会修复吗？现在猜到beta版 ，2.1.6也会有这个问题吗 @nolouch

**Comment by daikon12** [comment]
请问这个问题 需要等到3.0才会修复吗？现在才到beta版 ，2.1.6也会有这个问题吗 @nolouch
