### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#9635]
There are some redundant computing in charset.go(https://github.com/pingcap/parser/blob/master/charset/charset.go), some of the functions may just return constants.  There is no need to do compute every time if we save a map/slice and initialize them. Such as:

GetAllCharsets, GetCharsetInfoByID.

We may also change the type of argument from string to integer in GetCharsetDesc.
With better redesign, we can save more memory and CPU.

**Comment by hawkingrei** [comment]
I will try to improve GetAllCharsets. it is so interesting

**Comment by winkyao** [comment]
@hawkingrei Thanks, some tips here: 
1. GetAllCharsets can be inited at the `init` function, and GetAllCharsets can return the inited array directly.
2. GetCharsetInfoByID can use a map to fetch `Collation` effectively, like `var collationsMap = make(map[int]*Collation)`, and init the map in the `init` function too.

**Comment by lkk2003rty** [comment]
I'll try to improve `GetCharsetInfoByID`

**Comment by winkyao** [comment]
Actually, you should modify the code in https://github.com/pingcap/parser/blob/master/charset/charset.go, and update the TiDB go.mod.

**Comment by winkyao** [comment]
@lkk2003rty Are you interested in this issue https://github.com/pingcap/tidb/issues/9638?

**Comment by lkk2003rty** [comment]
> @lkk2003rty Are you interested in this issue #9638?

yep, I can do it
