### ISSUE TITLE
Performance improvement in the SetProcessInfo

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#9638]
## Performance Questions

https://github.com/pingcap/tidb/blob/ddbf60f6d013aadaba29676ccc47765a592b8841/session/session.go#L868 

```
func (s *session) SetProcessInfo(sql string, t time.Time, command byte) {
	pi := util.ProcessInfo{
		ID:      s.sessionVars.ConnectionID,
		DB:      s.sessionVars.CurrentDB,
		Command: mysql.Command2Str[command],
		Time:    t,
		State:   s.Status(),
		Info:    sql,
	}
	if s.sessionVars.User != nil {
		pi.User = s.sessionVars.User.Username
		pi.Host = s.sessionVars.User.Hostname
	}
	s.processInfo.Store(pi)
}
```
we can store the command byte directly, normally, the command(byte) need to change to a string only when the client exec `show processlist`. So we can do the transition in the function https://github.com/pingcap/tidb/blob/ddbf60f6d013aadaba29676ccc47765a592b8841/session/session.go#L1617:

```
func (s *session) ShowProcess() util.ProcessInfo {
	var pi util.ProcessInfo
	tmp := s.processInfo.Load()
	if tmp != nil {
		pi = tmp.(util.ProcessInfo)
	}
	return pi
}
```

Because of the SetProcessInfo is the main statement execution path, so the improvement is worth.

**Comment by xiekeyi98** [comment]
@lkk2003rty 
I'm so sorry that when I file the PR, I found you are handling this issue.
How is your work doing?

**Comment by lkk2003rty** [comment]
> @lkk2003rty
> I'm so sorry that when I file the PR, I found you are handling this issue.
> How is your work doing?

I'll file a pr about this issue today

**Comment by xiekeyi98** [comment]
@lkk2003rty 
Feel free to file the PR.
Because my PR is not good enough, I'm looking forward for you PR.
My PR will be closed.
And when you file PR, I was wondering if you could @me and let me learn it.
Thanks a lot!

**Comment by lkk2003rty** [comment]
@xiekeyi98 
Your PR is the same as mine. You can reopen your PR. 
I just have one question, may be change `executor/show.go` 252 line to use map to do  the transition work would be better? But I worried that modification will affect other part function.
