### ISSUE TITLE
Avoid unnecessary looking up inside map

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#9642]
There are some unnecessary looking up in datum.go, See an example:
https://github.com/pingcap/tidb/blob/469fa877d6c3f8851760eade5f8601dcbbbd4d59/types/datum.go#L1412

We can write a few function which just use switch table is good enough, and Go compiler will inline it, With this way, there is no memory allocation at all.

**Comment by liufuyang** [comment]
I am new to Golang, but I'd like to try do this :) 
Stupid questions will come if you don't mind :)

**Comment by ngaut** [comment]
Thank you @liufuyang 
Please feel free to ask any questions.

**Comment by liufuyang** [comment]
TODO list:
* [ ] Build repo locally and able to run some tests (following this https://github.com/pingcap/tidb/blob/master/CONTRIBUTING.md)
* [ ] Understand the issue better then do some changes while keep test passing
* [ ] Create a PR for this issue then try get it done 😄

**Comment by liufuyang** [comment]
@ngaut 
I can see the function `SignedLowerBound` is defined in `convert.go`. 
If we aim to use a function instead of this map, where do you think I should define this function? In `convert.go` or in `datum.go`?

**Comment by liufuyang** [comment]
@ngaut  Should we close this issue now? 
Let me know whether there are more easy stuff to do like this :)

**Comment by ngaut** [comment]
Sure, thanks.
