### ISSUE TITLE
Can I use a TiDB secondary instance as a cache?

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9656]
按照tidb的架构，对于只读请求，理论上不段横向扩展机器，增加副本数量，是可以不断扩展他的并发性能的， 如果搭建这个的一个系统，两个tidb,主实例的标准的3副本，用于写请求，然后再通过binlog准实时同步给另一个高副本高节点数的另一个tidb只读实例，   然后把原来需要用缓存的地方，改成直查备库， 

这样的话 可以大大省去 缓存层(redis,kv结构) 与 数据层(sql结构) 之间大量的一致性保证工作（如对写请求进行缓存清理/更新等），
不知道这样做可行吗？ 说白了就是用机器换人力成本。

另外如果说硬盘的速度和内存还是差很多可能不划算的话，不知道是否可以有内存型的tikv实现，专门用于这种当作缓存用的场景，类似于一开始的mysql cluster(ndb),也是纯内存的存储引擎。

**Comment by lamxTyler** [comment]
@ericisme Yes, you may experience higher latency than redis because TiKV has to do more things to guarantee data durability and consistency. Currently, we do not have such a plan to support the memory type TiKV.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
