### ISSUE TITLE
Why can't I use the primary key properly?

### ISSUE THREAD

**Issue by highfei2011** [pingcap/tidb#9657]
## I created a table as follow:
![image](https://user-images.githubusercontent.com/18230501/54169477-cd8b4c00-44ad-11e9-9c83-cfcb5ca496d4.png)

## But when I used this primary key id query, I found that no index was used.
![image](https://user-images.githubusercontent.com/18230501/54169547-12af7e00-44ae-11e9-8a77-4fd4f7da41fb.png)

## However, if I create the same table in mysql, use the same sql statement, mysql will use the index, is this the difference between mysql and tidb?
![image](https://user-images.githubusercontent.com/18230501/54169694-c6b10900-44ae-11e9-82ec-2825edb0b7bc.png)

**Comment by lamxTyler** [comment]
@highfei2011 TiDB actually uses the index in this case. As you can see, the `2019` actually appears in the scan range. You can read the [document](https://www.pingcap.com/docs/sql/understanding-the-query-execution-plan/) to understand the query plan.

**Comment by highfei2011** [comment]
Thank you.
