### ISSUE TITLE
Remove unnecessary integer to string conversion

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#9661]
Method fmt.Sprintf is quite expensive, by better design we should store ID instead of string, and delay converting ID to string when we need to show it.

**Comment by ngaut** [comment]
![pprof007](https://user-images.githubusercontent.com/878009/54173806-58744280-44be-11e9-97d3-1e1c8880aef5.jpg)
![pprof009](https://user-images.githubusercontent.com/878009/54173939-e4866a00-44be-11e9-8c26-73924e839b91.jpg)
<img width="963" alt="Screen Shot 2019-03-12 at 12 05 58 PM" src="https://user-images.githubusercontent.com/878009/54173998-3fb85c80-44bf-11e9-9d48-c43dabf13398.png">

**Comment by jackysp** [comment]
https://github.com/pingcap/tidb/pull/10139 and https://github.com/pingcap/tidb/pull/10223 fixed this issue.
