### ISSUE TITLE
Performance degrade about 5% with incorrect usage of logutil.WithRecvTs

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#9665]
See snapshot of profile

<img width="1085" alt="Screen Shot 2019-03-12 at 2 50 48 PM" src="https://user-images.githubusercontent.com/878009/54180626-0855aa00-44d7-11e9-9b88-d947a107f351.png">

**Comment by coocood** [comment]
https://github.com/pingcap/tidb/commit/4188ae19c0f3cfaa1b3bd4a283ec27dd3d621904#diff-dc417f5322100e2e83a8818c70a25878R588
