### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by leshalv** [pingcap/tidb#9670]
根据官方文档使用mydumper对mysql数据进行导出过程中，出现  Segmentation fault (core dumped) 错误
![QQ截图20190312152025](https://user-images.githubusercontent.com/30397655/54184156-e52ff800-44e0-11e9-839d-7e8b38323bed.png)
我系统版本为：Ubuntu 16.04.5 LTS

**Comment by lamxTyler** [comment]
@leshalv Thanks for your feedback! Could you provide us the mydumper and TiDB version and provide some logs using `mydumper -v 3`?

**Comment by leshalv** [comment]
mydumper 版本我不是很清楚，我是按照官方文档来的，对了wget http://download.pingcap.org/mydumper-linux-amd64.sha256 不存在，提示404
![QQ截图20190312162616](https://user-images.githubusercontent.com/30397655/54185293-99cb1900-44e3-11e9-921b-1e03036bb3f5.png)

tidb版本为v2.1.4 ，日志我不会看，您能提供一下资料吗？

**Comment by lamxTyler** [comment]
- To get the version of mydumper, use `mydumper -V`
- To get the log of mydumper, use `mydumper -v 3`, for example
```
$ mydumper -v 3 -h 127.0.0.1 -u dba --password='test1.q' -P 3936 -t 8 -o /data/mysql/backup/20181127/
** Message: 10:49:38.541: Server version reported as: 8.0.12
** Message: 10:49:38.547: Connected to a MySQL server
** Message: 10:49:38.558: Started dump at: 2018-11-28 10:49:38
** Message: 10:49:38.558: Written master status
** Message: 10:49:38.609: Thread 1 connected using MySQL connection ID 38
** Message: 10:49:38.647: Thread 2 connected using MySQL connection ID 39
```

**Comment by leshalv** [comment]
这个是版本，问题解决了，因为我使用了域名，我怀疑是域名问题造成的，改成ip就好了
![image](https://user-images.githubusercontent.com/30397655/54187971-abafba80-44e9-11e9-8426-02027c80974f.png)

**Comment by lamxTyler** [comment]
OK, I will close this issue. Feel free to reopen it.
