### ISSUE TITLE
A TIKV  suddenly down

### ISSUE THREAD

**Issue by Wythetells** [pingcap/tidb#9678]
hi 
I installed a TiDB for zabbix;
there have 4 hosts; Which includes 3TiKV ,1TiDB&TiPD 
today a tikv suddenly down at 14:37
I don't know this why
I con't find some log about this error
I want konw should i what to do now ~
please help me !thinks!~
There some info
![image](https://user-images.githubusercontent.com/32082652/54194116-765d9980-44f6-11e9-9994-f03500fb95bc.png)
![image](https://user-images.githubusercontent.com/32082652/54194129-7d84a780-44f6-11e9-8b60-b3d22d4505e3.png)
some TiKV log
![image](https://user-images.githubusercontent.com/32082652/54194166-8aa19680-44f6-11e9-95bc-cce937f7147a.png)
some TiDB log
![image](https://user-images.githubusercontent.com/32082652/54194191-955c2b80-44f6-11e9-920a-4e625b1ae808.png)

**Comment by lamxTyler** [comment]
@Wythetells Please fill in the template.

**Comment by Wythetells** [comment]
> @Wythetells Please fill in the template.

OK ~I have updated

**Comment by lamxTyler** [comment]
@Wythetells From the metrics, I think it is the TiDB that goes done at 14:37, and it has recovered. You can provide the TiDB log around that time. As for the tikv, you can first find the tikv that currently down, and provide the log of it.

**Comment by Wythetells** [comment]
> @Wythetells From the metrics, I think it is the TiDB that goes down at 14:37, and it has recovered. You can provide the TiDB log around that time. As for the tikv, you can first find the tikv that currently down, and provide the log of it.

yeah,the TiDB is recovered at 14:37,it only have a alert from zabbix about 'databases down'.
but I con't find the log of tikv whitch is down on today,
The log of the most recent timestamp is  2/15.
![image](https://user-images.githubusercontent.com/32082652/54197540-2b944f80-44ff-11e9-8b5e-6c925c780dfc.png)

**Comment by lamxTyler** [comment]
@Wythetells Is there anything in `tikv_stderr.log`?

**Comment by zhangjinpeng1987** [comment]
@Wythetells Please check the dmesg.

**Comment by Wythetells** [comment]
> @Wythetells Is there anything in `tikv_stderr.log`?
there is some logs
`[admin@tidb-tikv02-10-95-6-66 log]$ cat tikv_stderr.log  | more
E0120 14:49:23.423393432  122957 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0120 14:49:23.775190420  122956 chttp2_transport.c:1143]    Received a GOAWAY with error code ENHANCE_YOUR_CALM and debug data equal to "too_many_pings"
E0127 01:21:52.724232811  122968 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1548523312.724202476","description":"polling_island_create","file":"/home/jenkins/.cargo/registry/src/github.
com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1548523312.724200905","description":"OS Error","errno":23,"file":"/
home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_c
reate1"}]}
E0127 01:21:52.733639959  122968 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1548523312.733623245","description":"polling_island_create","file":"/home/jenkins/.cargo/registry/src/github.
com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1548523312.733622319","description":"OS Error","errno":23,"file":"/
home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_c
reate1"}]}
E0127 01:21:52.733822570  122968 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1548523312.733808156","description":"polling_island_create","file":"/home/jenkins/.cargo/registry/src/github.
com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1548523312.733807575","description":"OS Error","errno":23,"file":"/
home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_c
reate1"}]}
E0127 01:21:52.733982246  122968 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1548523312.733968543","description":"polling_island_create","file":"/home/jenkins/.cargo/registry/src/github.
com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1548523312.733968030","description":"OS Error","errno":23,"file":"/
home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_c
reate1"}]}
E0127 01:21:52.734146536  122968 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1548523312.734133214","description":"polling_island_create","file":"/home/jenkins/.cargo/registry/src/github.
com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1548523312.734132656","description":"OS Error","errno":23,"file":"/
home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_c
reate1"}]}
E0127 01:21:52.734302199  122968 ev_epollsig_linux.c:1560]   add_poll_object: {"created":"@1548523312.734286439","description":"polling_island_create","file":"/home/jenkins/.cargo/registry/src/github.
com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":245,"referenced_errors":[{"created":"@1548523312.734285847","description":"OS Error","errno":23,"file":"/
home/jenkins/.cargo/registry/src/github.com-1ecc6299db9ec823/grpcio-sys-0.2.3/grpc/src/core/lib/iomgr/ev_epollsig_linux.c","file_line":484,"os_error":"Too many open files in system","syscall":"epoll_c
reate1"}]}`

**Comment by lamxTyler** [comment]
Yes, I think so. @zhangjinpeng1987 Please help verify it.

**Comment by Wythetells** [comment]
Today I added two new nodes.one TiVK and one TiDB .But both nodes are not working···Maybe I must to solve this problem first.

**Comment by Wythetells** [comment]
> @Wythetells Please check the dmesg.

Think you for your reply！
This some dmesg info
```
···
   5.506109] alg: No test for __gcm-aes-aesni (__driver-gcm-aes-aesni)
[    5.506691] alg: No test for __generic-gcm-aes-aesni (__driver-generic-gcm-aes-aesni)
[    5.523519] ppdev: user-space parallel port driver
[    5.535541] Adding 4063228k swap on /dev/mapper/cl-swap.  Priority:-2 extents:1 across:4063228k FS
[    5.554791] EDAC sbridge: Seeking for: PCI ID 8086:6fa0
[    5.554800] EDAC sbridge:  Ver: 1.1.2 
[    5.729209] XFS (sda1): Starting recovery (logdev: internal)
[    5.741452] XFS (sda1): Ending recovery (logdev: internal)
[    7.591267] EXT4-fs (dm-2): mounted filesystem with ordered data mode. Opts: nodelalloc
[    8.130403] floppy0: no floppy controllers found
[    8.262747] type=1305 audit(1550232646.563:3): audit_pid=10619 old=0 auid=4294967295 ses=4294967295 res=1
[    8.576335] nf_conntrack version 0.5.0 (65536 buckets, 262144 max)
[    8.697418] NET: Registered protocol family 40
[    8.986012] IPv6: ADDRCONF(NETDEV_UP): ens192: link is not ready
[    8.990246] vmxnet3 0000:0b:00.0 ens192: intr type 3, mode 0, 9 vectors allocated
[    8.992100] vmxnet3 0000:0b:00.0 ens192: NIC Link is Up 10000 Mbps
[   10.206808] TCP: hybla registered
[1782651.811240] Adding 4063228k swap on /dev/mapper/cl-swap.  Priority:-2 extents:1 across:4063228k FS
[1783088.171266] Adding 4063228k swap on /dev/mapper/cl-swap.  Priority:-2 extents:1 across:4063228k FS
(END)
```

**Comment by Wythetells** [comment]
```
 {
      "store": {
        "id": 4,
        "address": "10.92.6.66:20160",
        "version": "2.1.2",
        "state_name": "Down"
      },
      "status": {
        "capacity": "954 GiB",
        "available": "780 GiB",
        "leader_weight": 1,
        "region_weight": 1,
        "start_ts": "2019-02-06T13:32:49+08:00",
        "last_heartbeat_ts": "2019-02-15T20:08:07.899706427+08:00",
        "uptime": "222h35m18.899706427s"
      }
```
I find this TiKV's process is dead.I use this cmd to restart this Tikv's process.now ,it is normal work~

> ansible-playbook start.yml -l 10.92.6.66

anyway, thinks very much ~
I will continue to see if tikv will suddenly down.

**Comment by lamxTyler** [comment]
OK. Feel free to reopen this issue if TikV goes down.
