### ISSUE TITLE
tidb.toml change breaks backwards compatibility

### ISSUE THREAD

**Issue by gregwebs** [pingcap/tidb#9686]
The type of a configuration parameter was change in https://github.com/pingcap/tidb/pull/9625

This breaks backwards compatibility. For example, tidb-operator no longer works with the latest TiDB.
The request is to establish a technique for making type changes in the toml that are backwards compatible.
The usual approaches would be
1) Parse into multiple different types (either a string or a boolean). This is often supported for YAML, but I am not sure about doing this in TOML with go.
2) Use a new key name for the new type (I am having trouble coming up with a good name) and support the old key type

**Comment by WangXiangUSTC** [comment]
pr https://github.com/pingcap/tidb/pull/9688  fix it

**Comment by morgo** [comment]
The PR referenced has been closed, so I am going to close this issue now.  Please feel free to reopen it if you have any further questions.  Thanks!
