### ISSUE TITLE
Support password expiry, last changed, lifetime attributes

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9709]
## Feature Request

**Is your feature request related to a problem? Please describe:**

In MySQL 5.7 the user table has attributes for `password_expired`, `password_last_changed`, `password_lifetime`.  These are helpful for user management.

**Describe the feature you'd like:**

* It should be possible to set a password as expired.
* It should be possible to see the date a password was last changed.
* It should be possible to force a password to be changed every n days.

**Describe alternatives you've considered:**

N/A

**Teachability, Documentation, Adoption, Migration Strategy:**

These are features of MySQL 5.7.

**Comment by zz-jason** [comment]
To fully support these attributes, seems we need to support the [Password Expiration Policy](https://dev.mysql.com/doc/refman/5.7/en/password-management.html#password-expiration-policy) in MySQL.

**Comment by dveeden** [comment]
The [user attributes](https://dev.mysql.com/doc/refman/8.0/en/information-schema-user-attributes-table.html) introduced in MySQL 8.0 should also be considered as part of this if possible.

**Comment by dveeden** [comment]
@CbcWestwolf What's missing here? Maybe add a list to the description?

**Comment by CbcWestwolf** [comment]
@dveeden I think we can close this issue now :-)
The feature has been implemented in the mentioned PR.
