### ISSUE TITLE
Import init database script failed!

### ISSUE THREAD

**Issue by cppmule** [pingcap/tidb#971]
# Init schema
# --- !Ups

-- MySQL dump 10.13  Distrib 5.6.15, for osx10.7 (x86_64)
--
-- Host: localhost    Database: waimai
-- ------------------------------------------------------
-- Server version       5.6.15

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Table structure for table `admin`
--

DROP TABLE IF EXISTS `admin`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;

**Comment by shenli** [comment]
@cppmule Thanks for your report.
May I have your TiDB git commit id and your error log?
I tested the above with the latest master but no error occurs.

**Comment by shenli** [comment]
@cppmule I found that TiDB treat "/!40101 SET character_set_client = utf8 */;" as comment but MySQL treat it as "SET character_set_client = utf8". I will fix it.
Is there any other problem?

**Comment by shenli** [comment]
@cppmule Please checkout the latest master and check if there is any other problem.
Thanks!
