### ISSUE TITLE
connect close tidb error when use mysql-connector pooling

### ISSUE THREAD

**Issue by pcleon** [pingcap/tidb#9724]
```
#!/usr/bin/python
#coding: utf-8

import mysql.connector.pooling
MYSQL_HOST = 'x.x.x.x'
MYSQL_PORT = 4000
MYSQL_USER = 'tidb'
MYSQL_PWD = 'tidb'
MYSQL_DB_NAME = 'mysql'
mysql_pool = mysql.connector.pooling.MySQLConnectionPool(
  pool_name="mypool", 
  pool_size=20, 
  host=MYSQL_HOST, 
  port=MYSQL_PORT,
  database=MYSQL_DB_NAME, 
  user=MYSQL_USER, 
  password=MYSQL_PWD,
  pool_reset_session=True
)
try:
    conn = mysql_pool.get_connection()
    cursor = conn.cursor()
    sql = 'select * from user limit 2'
    cursor.execute(sql)
    data = cursor.fetchall()
    print data
except Exception as e:
    print e
finally: 
    cursor.close()
    conn.close()  #here exception!
```

  File "x.py", line 33, in <module>
    conn.close()
  File "/usr/lib64/python2.7/site-packages/mysql/connector/pooling.py", line 123, in close
    cnx.reset_session()
  File "/usr/lib64/python2.7/site-packages/mysql/connector/connection.py", line 771, in reset_session
    self.cmd_reset_connection()
  File "/usr/lib64/python2.7/site-packages/mysql/connector/connection.py", line 1121, in cmd_reset_connection
    self._handle_ok(self._send_cmd(ServerCmd.RESET_CONNECTION))
  File "/usr/lib64/python2.7/site-packages/mysql/connector/connection.py", line 375, in _handle_ok
    raise errors.get_exception(packet)
mysql.connector.errors.DatabaseError: 1105 (HY000): ERROR 1105 (HY000): command 31 not supported now

tidb version : v2.1.4

**Comment by lamxTyler** [comment]
@pcleon TiDB does not handle `RESET_CONNECTION` currently. Maybe you can try to set `pool_reset_session` to false.

**Comment by pcleon** [comment]
> @pcleon TiDB does not handle `RESET_CONNECTION` currently. Maybe you can try to set `pool_reset_session` to false.

i set the pool_reset_session to false and it's work, thank you!

**Comment by protossyk** [comment]
hi,has the feature of "RESET_CONNECTION" been supported by Tidb?
