### ISSUE TITLE
Transfer database failed

### ISSUE THREAD

**Issue by cppmule** [pingcap/tidb#974]
version: Master.
I am using navcat to transfer database from remote to localhost. I got an error:

[Msg] [Dtf] Datatransfer started
[Msg] [Dtf] Gather Information
[Msg] [Dtf] Drop table: `address`
[Msg] [Dtf] Get table data for `address`
[Msg] [Dtf] Create table: `address`
[Err] [Dtf] Transfer Data [CREATE TABLE `address` (
	`id` bigint(20) NOT NULL AUTO_INCREMENT,
	`create_at` datetime NOT NULL,
	`deleted` tinyint(1) NOT NULL,
	`update_at` datetime NOT NULL,
	`version` bigint(20) DEFAULT NULL,
	`address` varchar(128) NOT NULL,
	`address_detail` varchar(128) NOT NULL,
	`cellphone` varchar(16) NOT NULL,
	`latitude` double NOT NULL,
	`longitude` double NOT NULL,
	`name` varchar(16) NOT NULL,
	`sex` tinyint(1) NOT NULL,
	`user_id` bigint(20) NOT NULL,
	PRIMARY KEY (`id`),
	CONSTRAINT `FK_7rod8a71yep5vxasb0ms3osbg` FOREIGN KEY (`user_id`) REFERENCES `waimaiqa`.`user` (`id`),
	INDEX `FK_7rod8a71yep5vxasb0ms3osbg` (`user_id`) comment ''
) ENGINE=`InnoDB` AUTO_INCREMENT=30 DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ROW_FORMAT=COMPACT COMMENT='' CHECKSUM=0 DELAY_KEY_WRITE=0;]:
line 17 column 51 near "comment"
[Err] [Dtf] Terminated
--------------------------------------------

**Comment by shenli** [comment]
@cppmule Thanks for your report!
It seems that some of the create_table options are not supported by TiDB. I will fix them.
