### ISSUE TITLE
Syncer automatically exits

### ISSUE THREAD

**Issue by leshalv** [pingcap/tidb#9742]
在使用syncer 进行数据增量同步的过程中，我开启了两个syncer ，还是用了守护进程，但是其中一个syncer 并没有按照正常预计工作，下面是日志，这个是什么原因导致的呢？
![image](https://user-images.githubusercontent.com/30397655/54400751-5b11aa80-46ff-11e9-824a-b9a5109a1f29.png)

**Comment by amyangfei** [comment]
From log we can see syncer receives `sighup` signal and exits. Check whether your terminal exits and sends sighup signal to syncer.
 
https://en.wikipedia.org/wiki/SIGHUP
