### ISSUE TITLE
Is `(-inf` or `+inf)` a good choice instead of ``[-inf` or `+inf]`` to express range info?

### ISSUE THREAD

**Issue by wjhuang2016** [pingcap/tidb#9756]
When excute `desc select * from t;`
We get
```
+-------------------+----------+------+------------------------------------------------------------+
| id                | count    | task | operator info                                              |
+-------------------+----------+------+------------------------------------------------------------+
| TableReader_5     | 10000.00 | root | data:TableScan_4                                           |
| └─TableScan_4     | 10000.00 | cop  | table:t, range:[-inf,+inf], keep order:false, stats:pseudo |
+-------------------+----------+------+------------------------------------------------------------+
2 rows in set (0.00 sec)
```

The range info here is `[-inf,+inf]`, according to #9231 and #8588, we can improve it as `[NULL,+inf)` or `(NULL,+inf)` when `explain select * from t use index(idx) where a is not null;`

It seems that `(-inf` or `+inf)` is more reasonable than `[-inf` or `+inf]`.
Should we use `(-inf` or `+inf)` even the scan is not a full range scan?

**Comment by eurekaka** [comment]
From the code perspective, `NULL` is "less" than `-inf`, if we adjust the display like your suggestion, when the range is full range with NULL, it would be like `[NULL, +inf)`, and this implies that `-inf` is included in the range, which is inconsistent with the implication of `(-inf, +inf)`?

**Comment by wjhuang2016** [comment]
I got it. So we should use `[NULL,+inf]` to express a full range scan with NULL and `(NULL,+inf]` to express a full range scan without NULL?

**Comment by eurekaka** [comment]
I prefer `[NULL, +inf]` for full range, while `[-inf, +inf]` for full range without null. @zz-jason @winoros what's your opinions?

**Comment by winoros** [comment]
Another case is that the `inf` of some numeric type is an actual number not an unbounded limit.
For bigint type, `+inf` is 2^63-1 for signed. `+inf]` is the same with `2^63-1]` and `+inf)` is the same with `2^63-1)`. There're some reasons that we cannot treat the `+inf` of some numeric type as an unbounded limit for now. So to not annoy our users, i prefer use `[]` for all types.
