### ISSUE TITLE
-skip-grant-table=true not work

### ISSUE THREAD

**Issue by pcleon** [pingcap/tidb#9772]
want to test forgot password situation, from the faq i should 
`Restart the TiDB service, add the -skip-grant-table=true parameter in the configuration file.`
but i make "skip-grant-table=true" in tidb.toml or "-skip-grant-table=true" in command line then restart tidb-server , it still needs i entering my password.
then i add "skip-grant-table=true" in tidb.toml then stop pd-server,tikv-server,tidb-server and restart all service , also not work.
how to make it right ? my tidb version is v2.1.4

**Comment by eurekaka** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
Are you deploy the TiDB cluster using the [tidb-ansible](https://github.com/pingcap/tidb-ansible)?
If so, you need to update this file https://github.com/pingcap/tidb-ansible/blob/master/conf/tidb.yml (find it in the deploy directory), because tidb.toml is generated by this one and overwrite every time.

Or, you may still update the tidb.toml file: kill the tidb-server process manually (do not use the tidb-ansible way), let it restart and then the new configure should take effect.

@pcleon

**Comment by pcleon** [comment]
> Are you deploy the TiDB cluster using the [tidb-ansible](https://github.com/pingcap/tidb-ansible)?
> If so, you need to update this file https://github.com/pingcap/tidb-ansible/blob/master/conf/tidb.yml (find it in the deploy directory), because tidb.toml is generated by this one and overwrite every time.
> 
> Or, you may still update the tidb.toml file: kill the tidb-server process manually (do not use the tidb-ansible way), let it restart and then the new configure should take effect.
> 
> @pcleon

i deploy the cluster by binary package without ansible playbook , every step is hand by hand . so the tidb.toml can't be changed by ansible .

**Comment by tiancaiamao** [comment]
```
[security]
skip-grant-table = true

# Path of file that contains list of trusted SSL CAs for connection with mysql client.
ssl-ca = ""
```

Is your tidb.toml file looks like this? @pcleon

**Comment by pcleon** [comment]
no, i don't know it must be in security section, so i make it under global config section in the first line .
i change it to security section and it works ! thank you ~~

**Comment by tiancaiamao** [comment]
FAQ say nothing about `skip-grant-table` because we hope our user never use it.

**Comment by vkingnew** [comment]
the configure file is yaml,right way:
>[security]
skip-grant-table : true
