### ISSUE TITLE
support `skip-name-resolve` 

### ISSUE THREAD

**Issue by YuanDdQiao** [pingcap/tidb#9778]
我sqlyog 客户端，隔短时间不操作后，客户端就需要重新连接，
等待时间比较长后才能正常使用。

**Comment by eurekaka** [comment]
Please provide the following information:
- TiDB version by using:
```
select tidb_version();
```

- the output of the following command:
```
show variables like '%timeout%';
```

- TiDB log when you observe the phenomenon you described.

**Comment by YuanDdQiao** [comment]
1. TiDB version by using:

Release Version: v3.0.0-beta-215-gb76b2da8f
Git Commit Hash: b76b2da8f626076a42ad2db2ea3677e4395fcb7c
Git Branch: master
UTC Build Time: 2019-03-14 05:06:03
GoVersion: go version go1.12 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false

2. the output of the following command:
Variable_name	Value
innodb_rollback_on_timeout	OFF
wait_timeout	28800
interactive_timeout	28800
rpl_semi_sync_master_timeout	
connect_timeout	10
net_read_timeout	30
innodb_lock_wait_timeout	50
net_write_timeout	60
slave_net_timeout	3600
rpl_stop_slave_timeout	31536000
innodb_flush_log_at_timeout	1
lock_wait_timeout	31536000
delayed_insert_timeout	300

3. 没有日志输出，或者无关的日志

**Comment by eurekaka** [comment]
The variables look reasonable, how long was your client being in idle state before observing this phenomenon? @tiancaiamao Do you have any idea?

**Comment by YuanDdQiao** [comment]
usually，mabe 5-10min 
but on docker, it's not exists this question.

**Comment by eurekaka** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
When the client reconnect, is there a log in tidb like this:

> [2019/03/20 13:40:09.764 +08:00] [INFO] [server.go:398] ["new connection"] [conn=1] [remoteAddr=127.0.0.1:58750]

And how long it takes between you operation in sqlyog and you see this log?

**Comment by YuanDdQiao** [comment]
> When the client reconnect, is there a log in tidb like this:
> 
> > [2019/03/20 13:40:09.764 +08:00] [INFO] [server.go:398] ["new connection"] [conn=1] [remoteAddr=127.0.0.1:58750]
> 
> And how long it takes between you operation in sqlyog and you see this log?



i see in tidb_err.log：

2019/03/19 18:40:09.040 domain.go:112: [info] [ddl] diff load InfoSchema from version 39 to 40 in 8.082478ms, tableIDs [113]
2019/03/20 10:50:46.752 set.go:178: [info] con:252434 wait_timeout=28800
2019/03/20 11:10:27.891 set.go:178: [info] con:257199 wait_timeout=28800
2019/03/20 11:10:27.899 tidb.go:157: [info] RollbackTxn for ddl/autocommit error.
2019/03/20 11:10:27.899 session.go:892: [warning] con:257199 schema_ver:40 session error:
[schema:1049]Unknown database 'aaaaxx'
github.com/pingcap/errors.AddStack
	/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/errors@v0.11.0/errors.go:174
github.com/pingcap/parser/terror.(*Error).GenWithStackByArgs
	/home/jenkins/workspace/build_tidb_master/go/pkg/mod/github.com/pingcap/parser@v0.0.0-20190312024907-3f6280b08c8b/terror/terror.go:233
github.com/pingcap/tidb/executor.(*SimpleExec).executeUse
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:109
github.com/pingcap/tidb/executor.(*SimpleExec).Next
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/simple.go:59
github.com/pingcap/tidb/executor.(*ExecStmt).handleNoDelayExecutor
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:298
github.com/pingcap/tidb/executor.(*ExecStmt).Exec
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/executor/adapter.go:244
github.com/pingcap/tidb/session.runStmt
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/tidb.go:206
github.com/pingcap/tidb/session.(*session).executeStatement
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:889
github.com/pingcap/tidb/session.(*session).execute
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:957
github.com/pingcap/tidb/session.(*session).Execute
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/session/session.go:910
github.com/pingcap/tidb/server.(*TiDBContext).Execute
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/driver_tidb.go:246
github.com/pingcap/tidb/server.(*clientConn).handleQuery
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:1024
github.com/pingcap/tidb/server.(*clientConn).dispatch
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:752
github.com/pingcap/tidb/server.(*clientConn).Run
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/conn.go:588
github.com/pingcap/tidb/server.(*Server).onConn
	/home/jenkins/workspace/build_tidb_master/go/src/github.com/pingcap/tidb/server/server.go:408
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1337
{
  "currDBName": "",
  "id": 257199,
  "status": 2,
  "strictMode": true,
  "user": {
    "Username": "root",
    "Hostname": "my network ip",
    "CurrentUser": false,
    "AuthUsername": "root",
    "AuthHostname": "%"
  }
}

**Comment by YuanDdQiao** [comment]
and tidb.log no message print.

**Comment by tiancaiamao** [comment]
> 2019/03/20 15:07:31.194 session.go:892: [warning] con:314189 schema_ver:40 session error:
> [schema:1049]Unknown database 'aaaaxx'

This is a normal log, there is no 'aaaaxx' database.

I mean, is there any evidence for your observation:

1. client reconnect after idle for a while 
2. tidb does not respond to the client for a long time

To prove 1, you should grep the "new connection" log in TiDB
To prove 2, you need to trace the actual time costed

**Comment by YuanDdQiao** [comment]
i got another diffrent report abort sqlyog .
i don't know why only mine computer timeout-reconnect...
so it's no issure ...thanks...
thank you very much,
i'm sorry to this mistake ！

**Comment by YuanDdQiao** [comment]
1.new connection log:
when i fist connect to tidb:   
[2019/03/25 16:41:57.182 +08:00] [INFO] [server.go:398] ["new connection"] [conn=80] [remoteAddr=xxx.xx.xxx.xxx:49368]
[2019/03/25 16:41:57.300 +08:00] [INFO] [server.go:398] ["new connection"] [conn=81] [remoteAddr=xxx.xx.xxx.xxx:49369]
[2019/03/25 16:41:57.494 +08:00] [INFO] [server.go:398] ["new connection"] [conn=82] [remoteAddr=xxx.xx.xxx.xxx:49370]
[2019/03/25 16:41:58.205 +08:00] [INFO] [server.go:400] ["close connection"] [conn=82]

passed 10 minute: reconnect on sqlyog that i'm reflush database list. only print in tidb.log->

[2019/03/25 16:54:25.139 +08:00] [INFO] [server.go:398] ["new connection"] [conn=108] [remoteAddr=xxx.xx.xxx.xxx:50181]

2. what is the trace ?how do i do ?

**Comment by tiancaiamao** [comment]
> [2019/03/25 16:54:25.139 +08:00] [INFO] [server.go:398] ["new connection"] [conn=108] [remoteAddr=xxx.xx.xxx.xxx:50181]

How long it takes between this time `2019/03/25 16:54:25.139 +08:00` and the time you can operate sqlyog ? @YuanDdQiao

**Comment by YuanDdQiao** [comment]
5 minute+

**Comment by YuanDdQiao** [comment]
i mean ,i can operate between "5 minute +", but ,if not operate any after about 10minute + ,the sqlyog will need to reconnect a while..

**Comment by tiancaiamao** [comment]
Could you enable the TiDB server general log, and repeat the operation, to see what's send to tidb?

Ref: https://github.com/pingcap/tidb/blob/master/docs/tidb_http_api.md

```
Enable/Disable TiDB server general log

curl -X POST -d "tidb_general_log=1" http://{TiDBIP}:10080/settings
curl -X POST -d "tidb_general_log=0" http://{TiDBIP}:10080/settings
```

Replace {TiDBIP} with something like 127.0.0.1

**Comment by YuanDdQiao** [comment]
yes,yes,
i gots dubbo same return,:
[root@tidb-01 ~]# tail -100f /data1/deploy/tidb/log/tidb.log |grep -E "close connection|new connection"
[2019/03/26 17:49:56.557 +08:00] [INFO] [server.go:398] ["new connection"] [conn=3106] [remoteAddr=xxx.xxx.xxx.xxx:51851]
[2019/03/26 17:49:56.772 +08:00] [INFO] [server.go:398] ["new connection"] [conn=3107] [remoteAddr=xxx.xxx.xxx.xxx:51853]
[2019/03/26 17:49:56.985 +08:00] [INFO] [server.go:398] ["new connection"] [conn=3108] [remoteAddr=xxx.xxx.xxx.xxx:51854]
[2019/03/26 17:49:57.651 +08:00] [INFO] [server.go:400] ["close connection"] [conn=3108]
[2019/03/26 18:05:32.022 +08:00] [INFO] [server.go:398] ["new connection"] [conn=3141] [remoteAddr=xxx.xxx.xxx.xxx:52913]
[2019/03/26 20:01:16.580 +08:00] [INFO] [server.go:400] ["close connection"] [conn=3106]
[2019/03/26 20:01:16.580 +08:00] [INFO] [server.go:400] ["close connection"] [conn=3107]
[2019/03/26 20:17:33.988 +08:00] [INFO] [server.go:400] ["close connection"] [conn=3141]

**Comment by tiancaiamao** [comment]
```
grep -E "GENERAL_LOG" /data1/deploy/tidb/log/tidb.log
```

I'd like to know what sqlyog send to tidb when it reconnect @YuanDdQiao

**Comment by morgo** [comment]
I think this is a reasonable feature request.

I was wondering what happens when name resolution fails in TiDB, and it looks like it's not clear. This is a common problem in MySQL, and on high traffic systems its common to skip-name-resolve.
