### ISSUE TITLE
Support explain on replace/insert statement

### ISSUE THREAD

**Issue by amyangfei** [pingcap/tidb#9808]
## Feature Request

**Is your feature request related to a problem? Please describe:**
`explain` for `insert` or `replace` statement returns `ERROR 1105 (HY000): Unsupported type *core.Insert` now

**Describe the feature you'd like:**

we can get right `execute plan` for `insert` and `replace` statement. 

**Describe alternatives you've considered:**

I don't know whether run explain on `insert` or `replace` is a little weird, it seems `insert` has no query plan?

**Comment by shenli** [comment]
@amyangfei It is not a bug. This should be a feature request.

**Comment by amyangfei** [comment]
> @amyangfei It is not a bug. This should be a feature request.

ok, I have changed the issue content

**Comment by morgo** [comment]
It would be nice to make everything explainable :-)  I have a FR to explain DDL as well https://github.com/pingcap/tidb/issues/8429

**Comment by zz-jason** [comment]
confirmed that it have been supported since TiDB 4.0:
```sql
TiDB(root@127.0.0.1:test) > desc insert into t values(1, 1);
+----------+---------+------+---------------+---------------+
| id       | estRows | task | access object | operator info |
+----------+---------+------+---------------+---------------+
| Insert_1 | N/A     | root |               | N/A           |
+----------+---------+------+---------------+---------------+
1 row in set (0.00 sec)

TiDB(root@127.0.0.1:test) > desc replace into t values(1, 1);
+----------+---------+------+---------------+---------------+
| id       | estRows | task | access object | operator info |
+----------+---------+------+---------------+---------------+
| Insert_1 | N/A     | root |               | N/A           |
+----------+---------+------+---------------+---------------+
1 row in set (0.00 sec)
```
