### ISSUE TITLE
Pass ORM's tests with MySQL compatible mode.

### ISSUE THREAD

**Issue by ngaut** [pingcap/tidb#981]
- [ ] beego
- [x] xorm
- [x] gorm
- [ ] Hibernate
- [x] iBATIS
- [ ] Spot
- [ ] Propel
- [ ] Sequelize
- [ ] SQLAlchemy
- [ ] peewee

**Comment by astaxie** [comment]
you miss the `-` before `[ ]`

- [ ] beego
- [ ] xorm
- [ ] gorm
....

**Comment by jkryanchou** [comment]
Is sqlalchemy compatible with TiDB now?

**Comment by ngaut** [comment]
We haven't test sqlalchemy yet. Please feel free to fire an issue.

**Comment by jkryanchou** [comment]
@ngaut OK, I would test it later and fire an issue if it exists.

**Comment by chiehwen** [comment]
Is Sequelize compatible with TiDB now?

**Comment by lysu** [comment]
Hi @chiehwen  we haven't test Sequelize, but we are compatible with MySQL protocol, in theory you can use any framework based on MySQL protocol to use TiDB, and feel free to fire issue if you meet any problem.

**Comment by bb7133** [comment]
Working on SQLAlchemy and Hibernate, I will update an report for them in this issue and #212

**Comment by winwisely99** [comment]
This is s very nice golang orm.
https://github.com/volatiletech/sqlboiler

Unlike many there is no reflection at runtime.
It also is database first in that it generates the golang code from the schema in the database

It would be awesome if this was also tested I think.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Compatibility has improved a lot in the last two years, and if there are any specific problems discovered, it is best to create a specific issue.
