### ISSUE TITLE
`kill tidb [session id]` can't stop executors and release resources

### ISSUE THREAD

**Issue by qw4990** [pingcap/tidb#9831]
## Feature Request

**Is your feature request related to a problem? Please describe:**

When users want to cancel a SQL, they may use `kill tidb [session id]`.
But it can't stop executors since executors don't watch the `ctx` used to cancel the session and the cancelled session don't call `executor.Close()` to stop them.
So after `kill tidb`, these executors will continue to consume resources to do their job.

**Describe the feature you'd like:**

Background executors should be stopped quickly after `kill tidb`.

**Comment by qw4990** [comment]
I'm working on this now.

**Comment by laimisnd** [comment]
Meanwhile, is the `systemctl restart tidb-4000.service` a good enough solution to the query/session kill problem ?
