### ISSUE TITLE
`LOAD DATA LOCAL INFILE` with IGNORE will report an error

### ISSUE THREAD

**Issue by dayuanyuan1989** [pingcap/tidb#9847]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

run `load data` with `ignore` will occur an error

`
mysql -h {host} -P {port} -u root --local-infile=1 -p{password} -D SCALIFIED -e LOAD DATA LOCAL INFILE 'SCALIFIED.T_STU' IGNORE  INTO TABLE SCALIFIED.T_STU FIELDS TERMINATED BY '\t' LINES TERMINATED BY '\n';
`

the command run against mysql successfully.

2. What did you expect to see?

load data into tidb successfully.

3. What did you see instead?

error occurs.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

v2.1.4

**Comment by dayuanyuan1989** [comment]
the content of file `SCALIFIED.T_STU`

```
1	xiaoming	11
2	xiaohong	10
```

**Comment by eurekaka** [comment]
@dayuanyuan1989 thanks for the report, please provide:
- the tidb log when this error occurs;
- schema of table `T_STU` by using `show create table T_STU`;

**Comment by morgo** [comment]
Here is the test case:
```
cat << EOF > /tmp/t.csv
a,b
1,2
2,3
2,4
3,4
EOF

# mysql test --local-infile
DROP TABLE IF EXISTS t1;
CREATE TABLE t1 (a INT NOT NULL PRIMARY KEY, b INT NOT NULL);
LOAD DATA LOCAL INFILE '/tmp/t.csv' IGNORE INTO TABLE t1 FIELDS TERMINATED BY ',' LINES TERMINATED BY '\n'; 
```

This is a parse error in TiDB, but works fine in MySQL 5.7.

This feature relates to [duplicate key handling](https://dev.mysql.com/doc/refman/8.0/en/load-data.html#load-data-duplicate-key-handling) of `load data infile`.  Note that when the command is `load data local infile` the default behavior is actually **IGNORE**.  The other option is **REPLACE**.

**Comment by eurekaka** [comment]
I have tested on my laptop, parser would report error when `REPLACE` or `IGNORE` keyword exists, that is to say, we only support implicit `IGNORE` now.

**Comment by sundl123** [comment]
Can I have a try? This is interesting

**Comment by shenli** [comment]
Sure, please go ahead :)

**Comment by travis-ray** [comment]
Thanks - this is really helpful!
