### ISSUE TITLE
SHOW PROCESSLIST always reports idle sessions as zero seconds

### ISSUE THREAD

**Issue by morgo** [pingcap/tidb#9853]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?

After https://github.com/pingcap/tidb/pull/9842 was merged, `SHOW PROCESSLIST` always reports sleeping sessions as idle zero seconds.

If I go back to release-2.1, it looks like there is a behavior difference where `SHOW PROCESSLIST` reports idle sessions correctly, but `SELECT * FROM information_schema.processlist` does not.  Refactoring in https://github.com/pingcap/tidb/pull/9842 caused both to behave incorrectly.

2. What did you expect to see?

Idle sessions showing how long they were idle.

3. What did you see instead?

Idle sessions showed zero seconds.

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

```
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v3.0.0-beta-256-g961f0d235-dirty
Git Commit Hash: 961f0d23514c6ab033a76b2f64c20c87d46e7fdf
Git Branch: fix-idle-connections
UTC Build Time: 2019-03-21 02:33:13
GoVersion: go version go1.12.1 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)
```

**Comment by tiancaiamao** [comment]
So here is right https://github.com/pingcap/tidb/pull/9842/files#diff-df919d9361195b93310b219738ea1aeeL253
and here is wrong https://github.com/pingcap/tidb/pull/9842/files#diff-7a9e970fa682861b6af9689a4a8088daL645

and when I abstract them to one function here https://github.com/pingcap/tidb/pull/9842/files#diff-673787e737513db3a354592cbac58953R43, I take the wrong one...

I'll take another fix

**Comment by tiancaiamao** [comment]
You fixed it, Thanks! @morgo
