### ISSUE TITLE
Performance issue in IsMemoryDB

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#9873]
https://github.com/pingcap/tidb/blob/59c7b69187e8ad1975a3a19724e210df4fb53526/infoschema/infoschema.go#L371

IsMemoryDB is called by buildDataSource, it is on the main path.

we can change the drivers from an array to a map.

```
var drivers []*virtualTableDriver
```

**Comment by tiancaiamao** [comment]
`drivers` is nearly empty @winkyao

**Comment by winkyao** [comment]
Just `PERFORMANCE_SCHEMA`? @tiancaiamao
