### ISSUE TITLE
EXPLAIN Select * from view requires different privileges to MySQL

### ISSUE THREAD

**Issue by erjiaqing** [pingcap/tidb#9875]
## Bug Report

1. What did you do?
If possible, provide a recipe for reproducing the error.

root:
```sql
use test;
create table t ( c int );
create view v as select * from t;
create user u@'%';
grant select on v to u@'%';
```

u@'%':
```sql
use test;
select * from v;
--> ok, no error
select * from t;
--> ok, no priv
explain select * from v;
```

2. What did you expect to see?

`ERROR 1345 (HY000): EXPLAIN/SHOW can not be issued; lacking privileges for underlying table`

3. What did you see instead?

no error

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?

`v3.0.0-beta-271-g630671e41`

**Comment by wjhuang2016** [comment]
Note that to explain a view, user also need priv`SHOW VIEW` See https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_show-view
and 

> EXPLAIN requires the SELECT privilege for any tables or views accessed, including any underlying tables of views. For views, EXPLAIN also requires the SHOW VIEW privilege.

**Comment by xiekeyi98** [comment]
And the key is :
![image](https://user-images.githubusercontent.com/7782671/54902107-680a7700-4f13-11e9-9010-980314a37749.png)


@wjhuang2016  May you help us try to solve this issue?

**Comment by wjhuang2016** [comment]
> And the key is :
> ![image](https://user-images.githubusercontent.com/7782671/54902107-680a7700-4f13-11e9-9010-980314a37749.png)
> 
> @wjhuang2016 May you help us try to solve this issue?

Sure :)

**Comment by xiekeyi98** [comment]
@wjhuang2016 
Thank you!
There are some similar PRs for your reference:
- https://github.com/pingcap/tidb/pull/9870
- https://github.com/pingcap/tidb/pull/9872

**Comment by xiekeyi98** [comment]
> Note that to explain a view, user also need priv`SHOW VIEW` See https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_show-view
> and
> 
> > EXPLAIN requires the SELECT privilege for any tables or views accessed, including any underlying tables of views. For views, EXPLAIN also requires the SHOW VIEW privilege.

I found the document you used is MySQL8.0, I think we'd better use MySQL5.7 manual.

**Comment by wjhuang2016** [comment]
> > Note that to explain a view, user also need priv`SHOW VIEW` See https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_show-view
> > and
> > > EXPLAIN requires the SELECT privilege for any tables or views accessed, including any underlying tables of views. For views, EXPLAIN also requires the SHOW VIEW privilege.
> 
> I found the document you used is MySQL8.0, I think we'd better use MySQL5.7 manual.

Ok, and could you tell me that in what sisutaion we should use 8.0 doc?

**Comment by xiekeyi98** [comment]
The existing features of TiDB are all compatible with MySQL 5.7.
Currently, we don’t have a plan to make them compatible with MySQL 8.0. 
For now, only the Window Functions and RBAC are compatible with MySQL 8.0.

**Comment by wjhuang2016** [comment]
> The existing features of TiDB are all compatible with MySQL 5.7.
> Currently, we don’t have a plan to make them compatible with MySQL 8.0.
> For now, only the Window Functions and RBAC are compatible with MySQL 8.0.

Thanks, I got it.

**Comment by wjhuang2016** [comment]
@xiekeyi98 
When build the visitInfo in BuildDataSourceFromView we need to know that whether the current stmt is a explain stmt or not. However, planBuilder doesn't provide info about explain.
So I want to add a `isExplainStmt` in planBuilder.
 And the problem is:
https://github.com/pingcap/tidb/blob/d6490c1cab3a634e2faba004802fab442d153035/planner/core/planbuilder.go#L1659-L1667

Presently we have no way to pass the `isExplainStmt` info to `OptimizeAstNode`, it's seem that we need to modify the interface of `OptimizeAstNode` and `Optimize`
I'm not sure if it's a good idea, could you think of a good idea or give we some advises?

**Comment by xiekeyi98** [comment]
@zz-jason  PTAL, Thanks.

**Comment by zz-jason** [comment]
@wjhuang2016 You can add a `InExplain` boolean field in `StatementContext`, which can be obtained by `b.ctx.GetSessionVars().StmtCtx`

**Comment by wjhuang2016** [comment]
> @wjhuang2016 You can add a `InExplain` boolean field in `StatementContext`, which can be obtained by `b.ctx.GetSessionVars().StmtCtx`

Great! It's prefect!
