### ISSUE TITLE
Support query hot read / write regions by SQL

### ISSUE THREAD

**Issue by breeswish** [pingcap/tidb#9885]
## Feature Request

It would be great if we can directly use SQL to query hot read and hot write regions.

The respond schema may be like:

```
region id | database id | database name | table id | table name | index id (if any) | index name (if any)
```

**Comment by winoros** [comment]
Implement it as a function and return a JSON object?

**Comment by morgo** [comment]
Is it possible to show this in `information_schema`?  I have a similar request to [show region info](https://github.com/pingcap/tidb/issues/7714) here.

**Comment by breeswish** [comment]
@winoros I think it can provide data in table format, so that users can use this function very easily.

**Comment by breeswish** [comment]
@morgo Yes, we have a hackathon project based on similar ideas. Maybe we can reuse that project.

**Comment by winoros** [comment]
@breeswish 
The following is the HTTP API result:
```
$curl http://127.0.0.1:10080/regions/hot
{
  "read": [

  ],
  "write": [
    {
      "db_name": "sbtest1",
      "table_name": "sbtest13",
      "index_name": "",
      "flow_bytes": 220718,
      "max_hot_degree": 12,
      "region_count": 1
    }
  ]
}
```
Is the `flow_bytes`, `max_hot_degree`, `region_count` useful?

**Comment by breeswish** [comment]
@winoros Yes! Maybe it's useful? Can we know the index if index region is in the hot region?

**Comment by winoros** [comment]
@breeswish 
What does `if index region is in the hot region` mean?

**Comment by breeswish** [comment]
Sorry for my typo. I was asking, can we know that particular index is the cause of hot region? If we can know it from the API you give, then it's fine!
