### ISSUE TITLE
support online config reloading for section "performance"

### ISSUE THREAD

**Issue by zz-jason** [pingcap/tidb#9892]
## Feature Request

**Is your feature request related to a problem? Please describe:**

this is a subtask of https://github.com/pingcap/tidb/issues/9891

**Describe the feature you'd like:**

support online config reloading for config items listed in the `performance` section

**Describe alternatives you've considered:**

No

**Teachability, Documentation, Adoption, Migration Strategy:**

No

**Comment by qw4990** [comment]
As we describe in https://github.com/pingcap/tidb/issues/9891, we will not support online config reloading.
We should create new SQL variables for attributes in the section `performance` if we really want to change them online.

**Comment by tisonkun** [comment]
closed as wontfix
