### ISSUE TITLE
v2.1.4 timezone bug！！！！

### ISSUE THREAD

**Issue by denghuancong** [pingcap/tidb#9903]
tidb version：v2.1.4
---------------------------
we upgrade tidb from v2.0.4 to v2.1.4，the system NOW() returns the time is diffrence
there are two tidb cluster in same machine using docker container：

THE first tidb cluster：
```
mysql> SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
1 row in set (0.03 sec)

mysql> select NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2019-03-26 18:47:46 |
+---------------------+
1 row in set (0.02 sec)
```

THE second tidb cluster：
```
mysql> select NOW();
+---------------------+
| NOW()               |
+---------------------+
| 2019-03-26 10:49:37 |
+---------------------+
1 row in set (0.03 sec)

mysql> SELECT @@global.time_zone, @@session.time_zone;
+--------------------+---------------------+
| @@global.time_zone | @@session.time_zone |
+--------------------+---------------------+
| SYSTEM             | SYSTEM              |
+--------------------+---------------------+
1 row in set (0.03 sec)

```

**Comment by jackysp** [comment]
What's the time zone setting of OS in the container?

**Comment by denghuancong** [comment]
@jackysp I check the container date output , the value is same as the select now(), but we using the same template to build the container , why is that date time difference ?

```
# docker exec -it e3969df8f520 sh
/ # date
Wed Mar 27 10:54:22 CST 2019
/ # exit
```

the other container
```
docker exec -it ac50eb17e883 sh
/ # date
Wed Mar 27 02:52:15 UTC 2019
/ # exit

```

**Comment by denghuancong** [comment]
```
[host1]# docker exec -it 1507f82f14d7 sh                                                                             
/ # echo $TZ
UTC
/ # exit
[host2]# docker exec -it ac50eb17e883 sh                                                                             
/ # echo $TZ
UTC
/ # exit
```
both TZ env value is UTC， why tidb server output the different timezone value？

**Comment by jackysp** [comment]
Hi @denghuancong ,
TiDB server uses https://github.com/pingcap/tidb/blob/05bd727bdd3f2f151f9a23b57dac3efb703464a2/util/timeutil/time.go#L44
to determine the timezone of it in release 2.1 which is not the same as it is in release 2.0. I think using the system timezone files are more reasonable.
I think you could check these files in your containers.

**Comment by denghuancong** [comment]
we now using system command to change tz ，we hope it can persist to tikv and no change because the docker container env。
```
SET time_zone = 'Asia/Shanghai';
SET GLOBAL time_zone = 'Asia/Shanghai';
```

**Comment by morgo** [comment]
@denghuancong Yes, `SET GLOBAL time_zone` will propagate to other TiDB nodes and persist.  The `SET time_zone` will only apply to your session.

**Comment by nullnotnil** [comment]
I am going to close this issue as stale. Please feel free to re-open it if you are continuing to experience problems. Thanks!
