### ISSUE TITLE
wrong result of `select cast("12.9910" as signed)`

### ISSUE THREAD

**Issue by XuHuaiyu** [pingcap/tidb#9905]
## Bug Report

Please answer these questions before submitting your issue. Thanks!

1. What did you do?
``` go
select cast("12.9910" as signed);
```

2. What did you expect to see?
``` go
+-----------------------------+
| cast("12.9910" as signed) |
+-----------------------------+
|                          12 |
+-----------------------------+
1 row in set, 1 warning (0.00 sec)
```

3. What did you see instead?
``` go
+---------------------------+
| cast("12.9910" as signed) |
+---------------------------+
|                        13 |
+---------------------------+
1 row in set, 1 warning (0.00 sec)
```

4. What version of TiDB are you using (`tidb-server -V` or run `select tidb_version();` on TiDB)?
`5025d582a7a69ac9c2f6f8ed744aa23ce687d433`

**Comment by XuHuaiyu** [comment]
related issue https://github.com/pingcap/tidb/issues/7511
related PR https://github.com/pingcap/tidb/pull/8157

**Comment by wjhuang2016** [comment]
I don't think it's a bug. It should  return 13 instead of 12.
```
mysql> drop table if exists t1;
Query OK, 0 rows affected (0.01 sec)

mysql> create table t1(c1 int);
Query OK, 0 rows affected (0.01 sec)

mysql> insert into t1 values('12.9910');
Query OK, 1 row affected (0.00 sec)

mysql> select c1, cast('12.9910' as signed) from t1;
+------+---------------------------+
| c1   | cast('12.9910' as signed) |
+------+---------------------------+
|   13 |                        13 |
+------+---------------------------+
1 row in set (0.01 sec)
mysql> select cast(12.9910 as signed);
+-------------------------+
| cast(12.9910 as signed) |
+-------------------------+
|                      13 |
+-------------------------+
1 row in set (0.00 sec)
```
See also https://bugs.mysql.com/bug.php?id=79292

**Comment by XuHuaiyu** [comment]
@wjhuang2016 
Thanks for your remind.
What's the result of `select version()` in your MySQL?
Mine is 
``` sql
+-----------+
| version() |
+-----------+
| 5.7.23    |
+-----------+
1 row in set (0.01 sec)
```

**Comment by wjhuang2016** [comment]
@XuHuaiyu 
The result I just posed is for TiDB
In MySQL 8.0.15:
```
mysql> drop table if exists t1;
Query OK, 0 rows affected (0.18 sec)

mysql> create table t1(c1 int);
Query OK, 0 rows affected (0.13 sec)

mysql> insert into t1 values('12.9910');
Query OK, 1 row affected (0.02 sec)

mysql> select c1, cast('12.9910' as signed) from t1;
+------+---------------------------+
| c1   | cast('12.9910' as signed) |
+------+---------------------------+
|   13 |                        12 |
+------+---------------------------+
1 row in set, 1 warning (0.00 sec)

mysql> select cast(12.9910 as signed);
+-------------------------+
| cast(12.9910 as signed) |
+-------------------------+
|                      13 |
+-------------------------+
1 row in set (0.00 sec)

mysql> select version();
+-----------+
| version() |
+-----------+
| 8.0.15    |
+-----------+
1 row in set (0.00 sec)

```
It seems that this bug has not been fixed yet in MySQL.

**Comment by XuHuaiyu** [comment]
Hi, @morgo 
What do you think of this? Should we make this behavior of TiDB to be compatible with MySQL?

**Comment by morgo** [comment]
I believe that **both behaviors** appear to actually SQL standard compliant.  Note the comment on this [bug report](https://bugs.mysql.com/bug.php?id=27736) for context:

```
SQL Standard 2003, part 2:  Foundation, section 9.2 Store
assignment, General Rules, paragraph 2), case a), sub-case x):

x) If the declared type of T is numeric, then
  Case:
  1) If V is a member of the declared type of T, then T is
  set to V.
  2) If a member of the declared type of T can be obtained
  from V by rounding or truncation, then T is set to that
  value. If the declared type of T is exact numeric, then it
  is implementation-defined whether the approximation is
  obtained by rounding or by truncation.
  3) Otherwise, an exception condition is raised: "data
  exception -- numeric value out of range."
```
(i.e. either truncation or rounding are both permitted).

TiDB is not strictly SQL standards compliant, but MySQL compatible - so the question is what does MySQL think of their behavior?  [BUG #79292](https://bugs.mysql.com/bug.php?id=79292) is open and verified, so I think that acknowledges that it might not be intended.  I also verified what PostgreSQL does, and the result is also round.

So while we aim to be MySQL compatible, I don't think that needs to include bugs. I would be happy to break from it here, as long as we document it.

**Comment by morgo** [comment]
@wjhuang2016 your testcase is really interesting.  It looks like MySQL applies both truncation and rounding depending on context.  It would be nice to just say we always round, as does I assume postgresql.
