### ISSUE TITLE
is that tikv only leader region will be readed/queried? 

### ISSUE THREAD

**Issue by ericisme** [pingcap/tidb#9934]
is that tikv only leader region will be readed/queried? 
wiil  the replication data or fllower region data be readed/queried ?

**Comment by jackysp** [comment]
> is that tikv only leader region will be readed/queried?

Yes.

> wiil the replication data or fllower region data be readed/queried ?

No.

**Comment by nullnotnil** [comment]
TiDB now also provides [follower read support](https://docs.pingcap.com/tidb/stable/follower-read). The default remains to read from the leader.

I am going to close this issue as stale. Please feel free to re-open if you have additional questions. Thanks!
