### ISSUE TITLE
recovery  data from TiDB 2.1.1 to TiDB2.1.7 error by mydumper and loader

### ISSUE THREAD

**Issue by vkingnew** [pingcap/tidb#9945]
--TiDB version:
>
mysql> select tidb_version()\G
*************************** 1. row ***************************
tidb_version(): Release Version: v2.1.7
Git Commit Hash: f5b52cb9dc5a8a546121aa6ce1fc672bd567ca48
Git Branch: HEAD
UTC Build Time: 2019-03-28 07:54:41
GoVersion: go version go1.11.2 linux/amd64
Race Enabled: false
TiKV Min Version: 2.1.0-alpha.1-ff3dd160846b7d1aed9079c389fc188f7f5ea13e
Check Table Before Drop: false
1 row in set (0.00 sec)

--error info:
>2019/03/29 09:45:41 db.go:122: [warning] [exec][sql][USE `tpch`; INSERT INTO `t` VALUES(174642400197869583,"YJP-TR-IS001","OrderSettle",NULL,20190225,1,"FCEAFC68-056 UPDATE `tidb_loader`.`checkpoint` SET `offset`=57989961 WHERE `id` ='12ae35' AND `filename`='tpch.t.][error]Error 1366: incorrect utf8 value 7b22617265616964223a2231363130363934373835383332353138383338222c226b6579223a22f0a0a7a7e89b8b227d({"areaid":"1610694785832518838","key":"১蛋"}) for column business
2019/03/29 09:45:41 loader.go:124: [fatal] Error 1366: incorrect utf8 value 7b22617265616964223a2231363130363934373835383332353138383338222c226b6579223a22f0a0a7a7e89b8b227d({"areaid":"1610694785832518838","key":"১蛋"}) for column business
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/db.go:90: 
/home/jenkins/workspace/build_tidb_enterprise_tools_master/go/src/github.com/pingcap/tidb-enterprise-tools/loader/loader.go:124: file tpch.t.000000060.sql

--table define:（which backup by official Mydumper）
>CREATE TABLE `t` (
  `id` bigint(20) NOT NULL COMMENT '雪花算法产生的id',
  `app_id` varchar(100) NOT NULL COMMENT '运行酒批应用的一个应用ID',
  `page_id` varchar(100) NOT NULL COMMENT '页面ID',
  `page_url` varchar(500) DEFAULT NULL COMMENT '页面的url',
  `data_time` int(11) DEFAULT NULL,
  `log_type` int(4) NOT NULL COMMENT '1:进入页面 2：离开页面 3: 点击事件',
  `device_id` varchar(100) DEFAULT NULL COMMENT '设备唯一ID',
  `device_type` varchar(100) DEFAULT NULL COMMENT '设备型号,包含手机品牌（如三星）手机具体型号（如三星note3）',
  `device_brand` varchar(100) DEFAULT NULL COMMENT '手机品牌',
  `os` varchar(100) DEFAULT NULL COMMENT '操作系统',
  `os_version` varchar(100) DEFAULT NULL COMMENT '操作系统版本',
  `ip` varchar(100) DEFAULT NULL COMMENT '客户端访问ip地址',
  `browser_type` varchar(100) DEFAULT NULL COMMENT '浏览器类型',
  `browser_version` varchar(100) DEFAULT NULL COMMENT '浏览器版本',
  `app_type` varchar(100) DEFAULT NULL COMMENT 'iOS,android',
  `app_version` varchar(100) DEFAULT NULL COMMENT '客户端版本号',
  `city_id` int(10) NOT NULL COMMENT '用户所在城市Id',
  `user_id` varchar(100) DEFAULT NULL COMMENT '酒批注册用户id',
  `uuid` varchar(100) DEFAULT NULL COMMENT '全局唯一用户id',
  `request_time` varchar(100) NOT NULL COMMENT '请求时间yyyy-MM-dd HH:mm:ss,必须是这种格式，如果不是这种格式，程序直接抛弃此数据',
  `session_id` varchar(100) NOT NULL COMMENT '会话编号',
  `ref_page_id` varchar(100) DEFAULT NULL COMMENT '来源页页面ID',
  `first_request_flag` int(4) DEFAULT NULL COMMENT '判断是否是第一次访问：1，是。0，否。',
  `last_request_flag` int(4) DEFAULT NULL COMMENT '判断是否是最后一次访问：1，是。0，否。',
  `url_request_seq_num` int(11) DEFAULT NULL COMMENT '本次会话内该页面累计浏览次数',
  `business` text DEFAULT NULL COMMENT '产品，搜索或者活动的额外信息，“{skuid:xxxxx}”,“{kwd:xxxxx}”,“{activeid:xxxx,starttime:yyyyMMddHHmmss,endtime:yyyyMMddHHmmss}”',
  `create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `page_duration` varchar(128) DEFAULT NULL COMMENT '页面停留时长',
  `page_tag` varchar(128) DEFAULT NULL COMMENT 'spm编码，用来追踪用户访问路径',
  PRIMARY KEY (`id`),
  KEY `idx_logDay` (`data_time`),
  KEY `ix_createtime` (`create_time`),
  KEY `ix_appid_pageid_apptype` (`app_id`,`page_id`,`app_type`),
  KEY `ix_pageid` (`page_id`),
  KEY `ix_datatime_pageid` (`data_time`,`page_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

--key info:
> column business is text data type ,store JSON data.

**Comment by jackysp** [comment]
The latest TiDB version added a config
https://github.com/pingcap/tidb/blob/release-2.1/config/config.toml.example#L52
which will more strictly check the utf8 characters. I think there are some `incorrect utf8 value ` in the backup data.
For a workaround way, I think you can turn it to false, then restart the tidb-server.

**Comment by vkingnew** [comment]
the official advice，by test it works.
>把表结构中的字符集改成utf8mb4或者修改tidb-ansible/conf/tidb.yml 中的 check-mb4-value-in-utf8: false 然后rolling update tidb
