### ISSUE TITLE
How to read all the data in TiDB quickly

### ISSUE THREAD

**Issue by Cavinlz** [pingcap/tidb#9958]
有种场景需要快速遍历TiDB里的所有数据， 请问能通过什么方法拿到Region 的数据分布信息么？以便于可以多线程根据不同region 去遍历数据。比如 Mongo 集群里 我们可以通过查询chunk的分块信息， 不知道TiDB是否也支持类似的方法。 谢谢

**Comment by zz-jason** [comment]
@Cavinlz To retrieve all the data of a table, you can simple write a sql like:
```sql
select * from t;
```

To increase the read concurrency and retrieve latency, you can execute the following sql:
```sql
-- if your server has 40 virtual cores:
set @@tidb_distsql_scan_concurrency = 40;
```

**Comment by lennonwoo** [comment]
hi, if the overall data is too big, and the primary key is un-ordered, how could we retrieve data from TiDB by batch?

**Comment by jebter** [comment]
Please refer: https://docs.pingcap.com/tidb/stable/dev-guide-paginate-results. I will close this issue. If there are any updates, you can reopen it.
