### ISSUE TITLE
Privilege check failed error to be consistent with MySQL

### ISSUE THREAD

**Issue by winkyao** [pingcap/tidb#9962]
https://github.com/pingcap/tidb/blob/master/planner/core/planbuilder.go#L1208

visitInfo.err is used to return to the client when the privilege check is failed. we should keep the error message consistent with MySQL, using `nil` will return only `privilege check fail`

```
// CheckPrivilege checks the privilege for a user.
func CheckPrivilege(pm privilege.Manager, vs []visitInfo) error {
	for _, v := range vs {
		if !pm.RequestVerification(v.db, v.table, v.column, v.privilege) {
			if v.err == nil {
				return ErrPrivilegeCheckFail
			}
			return v.err
		}
	}
	return nil
}
```

**Comment by zz-jason** [comment]
I think this issue is duplicated with https://github.com/pingcap/tidb/issues/8946, @morgo PTAL

**Comment by nullnotnil** [comment]
Closing as duplicate.
