### ISSUE TITLE
tidb drainer source code

### ISSUE THREAD

**Issue by nitins64** [pingcap/tidb#9971]
Hi there,

I am looking into change capture capabilities (API) for TiDB. Is seems drainer role reads the bin log and can export the mutation to an external system?

Could you point me to source code for drainer?

Thanks!

**Comment by qw4990** [comment]
PTAL~ @lonng

**Comment by lonng** [comment]
@nitins64 Hi, I am sorry for telling you that you could not get the drainer source code because of related projects have not open source.

**Comment by jebter** [comment]
Please refer: https://github.com/pingcap/tidb-binlog. I will close this issue. If there are any updates, you can reopen it.
