### ISSUE TITLE
Syncer sync time zone issue

### ISSUE THREAD

**Issue by leshalv** [pingcap/tidb#9972]
将阿里云RES 数据同步到下游TIDB 时区不对，差十二小时，上游和下游数据库时区经过验证一致同为UTC +8，从上游全量导出并导入到下游数据正确，我怀疑是Syncer原因导致和造成的此问题，希望能尽快修复，已经影响到了生产，大范围，其中上游数据库时间字段类型为 timestamp

**Comment by zimulala** [comment]
@leshalv Thanks for your feedback!
PTAL @lonng

**Comment by lonng** [comment]
Could you provide the timezones of upstream and downstream?

**Comment by leshalv** [comment]
China Standard Time UT+8:00

**Comment by csuzhangxc** [comment]
can you provide more information? like:

1. Syncer version
2. some binlog events with timestamp (output of `SHOW BINLOG EVENTS` or mysqlbinlog)

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/55309280-e45f0600-548f-11e9-8b05-89275b8117f0.png)

**Comment by csuzhangxc** [comment]
can you show a record both with `SELECT` and `SHOW BINLOG EVENTS` (or mysqlbinlog)

**Comment by csuzhangxc** [comment]
and another question
> 差十二小时

which one is greater? TiDB > MySQL or MySQL > TiDB?

so, can you show some example records?

**Comment by leshalv** [comment]
MySQL正确，TIDB少12小时

**Comment by leshalv** [comment]
你能帮我写个关于带有时间戳的biglog语句吗

**Comment by csuzhangxc** [comment]
I mean you can get the original binlog event data by `SHOW BINLOG EVENTS` or mysqlbinlog tool, like (**only example below, please know what you are doing**)
- ```SHOW BINLOG EVENTS in 'mysql-bin.000003';```
- ```mysqlbinlog --base64-output=decode-rows --verbose mysql-bin.000003```

another question, what's the timezone of your machine running Syncer?

**Comment by leshalv** [comment]
运行Syncer的时区是China Standard Time UT+8:00

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/55311534-c98f9000-5495-11e9-91c0-810c1c143ade.png)

**Comment by csuzhangxc** [comment]
is there timestamp column exists in `uaa_miro_db.jhi_persistent_audit_event`?
if so, you can provide **one special record** with the following information:

1. output of `mysqlbinlog --base64-output=decode-rows --verbose`
2. output of `SELECT` in upstream MySQL
3. output of `SELECT` in downstream TiDB

**Comment by leshalv** [comment]
# at 73429
#190331 22:21:39 server id 1924496971  end_log_pos 73623 CRC32 0x6c2a21d3 	Table_map: `appointment_micro_db`.`appointment` mapped to number 101
# at 73623
#190331 22:21:39 server id 1924496971  end_log_pos 74055 CRC32 0xf4d81b04 	Write_rows: table id 101 flags: STMT_END_F
### INSERT INTO `appointment_micro_db`.`appointment`
### SET
###   @1='65239222-db68-49f3-8cff-baa678f93f06'
###   @2='a1f4321f-03e1-4aad-8c1e-94920ee457e8'
###   @3=''
###   @4=''
###   @5='0106'
###   @6=''
###   @7='5360'
###   @8=''
###   @9='2019-04-01'
###   @10=NULL
###   @11=1
###   @12='1'
###   @13='08:04:00'
###   @14='08:04:00'
###   @15=''
###   @16='-1'
###   @17=1
###   @18=0
###   @19=0
###   @20=0.00
###   @21=13.00
###   @22='f5679cb7-9b4a-408f-b9b0-7fdfb3e95832'
###   @23=''
###   @24=''
###   @25=''
###   @26=''
###   @27='1'
###   @28='4b08780ed4e046af81d593630bb9fa8e'
###   @29=3
###   @30=3
###   @31='4'
###   @32=NULL
###   @33='system'
###   @34=
###   @35='system'
###   @36=
###   @37=
###   @38=
###   @39=NULL
###   @40=0
###   @41=NULL
###   @42=NULL
###   @43=NULL
###   @44=NULL
###   @45=NULL
###   @46=NULL
# Number of rows: 1
# at 74055
#190331 22:21:39 server id 1924496971  end_log_pos 74086 CRC32 0x6ee60f32 	Xid = 2196367057
COMMIT/*!*/;

**Comment by csuzhangxc** [comment]
which column in this table (``` `appointment_micro_db`.`appointment` ```) has a timestamp type?

I don't find it, only `@9='2019-04-01'`/`@13='08:04:00'`/`@14='08:04:00'` are similar, but I think they are not.

can you provide the output of ``` SHOW CREATE TABLE `appointment_micro_db`.`appointment` ```

**Comment by leshalv** [comment]
```
CREATE TABLE `appointment` (
  `id` varchar(64) NOT NULL DEFAULT '',
  `appoint_id` varchar(100) NOT NULL,
  `account_id` varchar(36) NOT NULL,
  `sch_id` varchar(100) NOT NULL,
  `dept_id` varchar(50) DEFAULT NULL,
  `dept_name` varchar(50) DEFAULT NULL,
  `doctor_id` varchar(50) DEFAULT NULL,
  `doctor_name` varchar(50) DEFAULT NULL,
  `sch_date` varchar(11) NOT NULL,
  `appoint_address` varchar(50) DEFAULT NULL,
  `week_day` int(11) DEFAULT NULL,
  `noon_code` varchar(1) DEFAULT NULL,
  `sch_time` varchar(50) NOT NULL,
  `start_time` varchar(8) DEFAULT NULL,
  `end_time` varchar(8) DEFAULT NULL,
  `sch_seq` varchar(20) DEFAULT NULL,
  `is_card` int(11) DEFAULT NULL,
  `is_dopay` int(11) DEFAULT '0',
  `is_today` int(11) DEFAULT NULL,
  `service_fee` decimal(10,2) DEFAULT NULL,
  `reg_fee` decimal(10,2) DEFAULT NULL,
  `patient_id` varchar(36) NOT NULL,
  `patient_name` varchar(255) NOT NULL,
  `patient_id_card_no` varchar(255) DEFAULT NULL,
  `patient_card_id` varchar(50) DEFAULT NULL,
  `patient_phone` varchar(11) NOT NULL,
  `hos_area` varchar(50) DEFAULT NULL,
  `hos_id` varchar(50) NOT NULL,
  `state` int(11) DEFAULT NULL,
  `hos_state` int(11) DEFAULT NULL,
  `platform_id` varchar(10) NOT NULL,
  `cancel_platform_id` varchar(10) DEFAULT NULL,
  `created_by` varchar(50) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `last_modified_by` varchar(50) DEFAULT NULL,
  `last_modified_date` timestamp NULL DEFAULT NULL,
  `op_time` timestamp NULL DEFAULT NULL,
  `modify_time` timestamp NULL DEFAULT NULL,
  `project_type` varchar(10) DEFAULT NULL,
  `countdown` int(11) DEFAULT '-1',
  `trade_no` varchar(64) DEFAULT NULL,
  `out_trade_no` varchar(64) DEFAULT NULL,
  `his_trade_no` varchar(64) DEFAULT NULL,
  `cancel_error_msg` varchar(300) DEFAULT NULL,
  `reason` varchar(255) DEFAULT NULL,
  `id_card_type` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `UC_APPOINTMENTID_COL` (`id`),
  KEY `idx_optime` (`op_time`),
  KEY `idx_accountid_hosid_modifytime` (`account_id`,`hos_id`,`modify_time`),
  KEY `idx_appointid_accountid_hosid` (`appoint_id`,`account_id`,`hos_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8

```

**Comment by csuzhangxc** [comment]
from this table schema, type of `created_date`/`last_modified_date`/`op_time`/`modify_time` is timestamp.

1. compare it to the binlog event above, `###   @34=` is `NULL`, but ``` `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP ```, have you alter `created_date` from `NULL` to `NOT NULL`?

2. can you provide a records both in upstream and downstream with `id=65239222-db68-49f3-8cff-baa678f93f06`?

**Comment by leshalv** [comment]
我对提交上去的binlog进行了更改，有些信息删除了

**Comment by leshalv** [comment]
tidb binlog如何查询呢？查询id为 65239222-db68-49f3-8cff-baa678f93f06 的binlog ，能给个demo吗？

**Comment by csuzhangxc** [comment]
can you provide values for `created_date/last_modified_date/op_time/modify_time` :
1. binlog event
2. upstream MySQL
3. downstream TiDB

no need to query values in TiDB binlog, `SELECT` from table is enough.

**Comment by leshalv** [comment]
字段太多，我只给你提供日
![image](https://user-images.githubusercontent.com/30397655/55320278-48da8f00-54a9-11e9-9854-3694b13b5369.png)

**Comment by csuzhangxc** [comment]
these four column's values in 
1. binlog event
2. upstream MySQL
3. downstream TiDB

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/55321661-d53a8100-54ac-11e9-8ab5-377735f2889c.png)
![image](https://user-images.githubusercontent.com/30397655/55321718-eedbc880-54ac-11e9-888e-c3015b65ac21.png)

binlog对应： 
 created_date: 1554042099
 last_modified_date: 1554042099
 op_time: 1554041815
 modify_time: 1554041815

**Comment by csuzhangxc** [comment]
what is the output of `SELECT @@GLOBAL.time_zone, @@SESSION.time_zone;` in downstream and upstream?

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/55368089-9f37e400-5522-11e9-950a-136ce06ec06d.png)
![image](https://user-images.githubusercontent.com/30397655/55368115-c55d8400-5522-11e9-9747-8992b88c8909.png)
![image](https://user-images.githubusercontent.com/30397655/55368242-6fd5a700-5523-11e9-8bf1-91ed8456143d.png)

老哥，我们的时间都是标准的啊

**Comment by csuzhangxc** [comment]
> the output of date in the upstream machine, downstream machine, and Syncer machine.

can you also provide these?

**Comment by leshalv** [comment]
能给我个命令吗？

**Comment by csuzhangxc** [comment]
execute `date` in a terminal

**Comment by leshalv** [comment]
![image](https://user-images.githubusercontent.com/30397655/55370843-88978a00-552e-11e9-8b81-52d359bd2ae9.png)

阿里云RDS看不了终端，但是我们是青岛机房，默认中国标准时间，且源数据没毛病

**Comment by csuzhangxc** [comment]
what is the output in the machine which is running Syncer?

**Comment by leshalv** [comment]
就是上面这个，我们部署在一台服务器

**Comment by csuzhangxc** [comment]
can you provide the output of 
```
select unix_timestamp(created_date) from appointment where id = '65239222-db68-49f3-8cff-baa678f93f06'
```
both in MySQL and TiDB?

**Comment by leshalv** [comment]
![TIDB](https://user-images.githubusercontent.com/30397655/55372166-56d4f200-5533-11e9-9dce-d5106c19338b.png)

![阿里云](https://user-images.githubusercontent.com/30397655/55372182-694f2b80-5533-11e9-8c2c-13cf3eebc14c.png)

**Comment by csuzhangxc** [comment]
Can you:
1. download our latest version from <http://download.pingcap.org/tidb-enterprise-tools-latest-linux-amd64.tar.gz>
	```
	# ./syncer -V
	Release Version: v1.0.0-63-g248ef5a
	Git Commit Hash: 248ef5a4867ea7bd8fb48efe4616a4a0cbf4de41
	Git Branch: master
	UTC Build Time: 2019-04-02 06:56:30
	Go Version: go version go1.12 linux/amd64
	```
2. add a new config item `timezone = "Asia/Shanghai"` to the config file
3. re-sync the data using this new Syncer
4. observe the timestamp values whether are correct in downstream

**Comment by csuzhangxc** [comment]
@leshalv have you tried the new version? Is it working correctly now?

**Comment by csuzhangxc** [comment]
@leshalv I'll close this issue. If you have any problem, you can reopen it.
